SDL3: SDL-main/include/SDL3/SDL_clipboard.h File Reference
SDL_clipboard.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Typedefs
typedef void(SDLCALL * SDL_ClipboardCleanupCallback) (void *userdata)
typedef const void *(SDLCALL * SDL_ClipboardDataCallback) (void *userdata, const char *mime_type, size_t *size)
Functions
SDL_DECLSPEC bool SDLCALL SDL_ClearClipboardData (void)
SDL_DECLSPEC void *SDLCALL SDL_GetClipboardData (const char *mime_type, size_t *size)
SDL_DECLSPEC char **SDLCALL SDL_GetClipboardMimeTypes (size_t *num_mime_types)
SDL_DECLSPEC char *SDLCALL SDL_GetClipboardText (void)
SDL_DECLSPEC char *SDLCALL SDL_GetPrimarySelectionText (void)
SDL_DECLSPEC bool SDLCALL SDL_HasClipboardData (const char *mime_type)
SDL_DECLSPEC bool SDLCALL SDL_HasClipboardText (void)
SDL_DECLSPEC bool SDLCALL SDL_HasPrimarySelectionText (void)
SDL_DECLSPEC bool SDLCALL SDL_SetClipboardData (SDL_ClipboardDataCallback callback, SDL_ClipboardCleanupCallback cleanup, void *userdata, const char **mime_types, size_t num_mime_types)
SDL_DECLSPEC bool SDLCALL SDL_SetClipboardText (const char *text)
SDL_DECLSPEC bool SDLCALL SDL_SetPrimarySelectionText (const char *text)
Typedef Documentation
SDL_ClipboardCleanupCallback
typedef void(SDLCALL * SDL_ClipboardCleanupCallback) (void *userdata)
Callback function that will be called when the clipboard is cleared, or new data is set.
Parameters
userdata a pointer to provided user data.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
SDL_ClipboardDataCallback
typedef const void *(SDLCALL * SDL_ClipboardDataCallback) (void *userdata, const char *mime_type, size_t *size)
Callback function that will be called when data for the specified mime-type is requested by the OS.
The callback function is called with NULL as the mime_type when the clipboard is cleared or new data is set. The clipboard is automatically cleared in SDL_Quit().
Parameters
userdata a pointer to provided user data.
mime_type the requested mime-type.
size a pointer filled in with the length of the returned data.
Returns
a pointer to the data for the provided mime-type. Returning NULL or setting length to 0 will cause no data to be sent to the "receiver". It is up to the receiver to handle this. Essentially returning no data is more or less undefined behavior and may cause breakage in receiving applications. The returned data will not be freed so it needs to be retained and dealt with internally.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
Function Documentation
SDL_ClearClipboardData()
SDL_DECLSPEC bool SDLCALL SDL_ClearClipboardData (void) extern
Clear the clipboard data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
{
    return SDL_SetClipboardData(NULL, NULL, NULL, NULL, 0);
}
References NULL, and SDL_SetClipboardData().
Referenced by SDL_SetClipboardData(), and SDL_SetClipboardText().
SDL_GetClipboardData()
SDL_DECLSPEC void *SDLCALL SDL_GetClipboardData (const char * mime_type, size_t * size) extern
Get the data from clipboard for a given mime type.
The size of text data does not include the terminator, but the text is guaranteed to be null terminated.
Parameters
mime_type the mime type to read from the clipboard.
size a pointer filled in with the length of the returned data.
Returns
the retrieved data buffer or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasClipboardData
SDL_SetClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t unused;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (!mime_type) {
        SDL_InvalidParamError("mime_type");
        return NULL;
    }
    if (!size) {
        size = &unused;
    }
    // Initialize size to empty, so implementations don't have to worry about it
    *size = 0;
    if (_this->GetClipboardData) {
        return _this->GetClipboardData(_this, mime_type, size);
    } else if (_this->GetClipboardText && SDL_IsTextMimeType(mime_type)) {
        char *text = _this->GetClipboardText(_this);
        if (text) {
            if (*text == '\0') {
                SDL_free(text);
                text = NULL;
            } else {
                *size = SDL_strlen(text);
            }
        }
        return text;
    } else {
        return SDL_GetInternalClipboardData(_this, mime_type, size);
    }
}
References _this, NULL, SDL_free(), SDL_GetInternalClipboardData(), SDL_GetVideoDevice(), SDL_InvalidParamError, SDL_IsTextMimeType(), SDL_strlen(), and SDL_UninitializedVideo().
Referenced by SDL_GetClipboardText().
SDL_GetClipboardMimeTypes()
SDL_DECLSPEC char **SDLCALL SDL_GetClipboardMimeTypes (size_t * num_mime_types) extern
Retrieve the list of mime types available in the clipboard.
Parameters
num_mime_types a pointer filled with the number of mime types, may be NULL.
Returns
a null terminated array of strings with mime types, or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (num_mime_types) {
        *num_mime_types = 0;
    }
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (num_mime_types) {
        *num_mime_types = _this->num_clipboard_mime_types;
    }
    return SDL_CopyClipboardMimeTypes((const char **)_this->clipboard_mime_types, _this->num_clipboard_mime_types, false);
}
References _this, NULL, SDL_CopyClipboardMimeTypes(), SDL_GetVideoDevice(), and SDL_UninitializedVideo().
SDL_GetClipboardText()
SDL_DECLSPEC char *SDLCALL SDL_GetClipboardText (void) extern
Get UTF-8 text from the clipboard.
This functions returns an empty string if there was not enough memory left for a copy of the clipboard's content.
Returns
the clipboard text on success or an empty string on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasClipboardText
SDL_SetClipboardText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t i, num_mime_types;
    const char **text_mime_types;
    size_t length;
    char *text = NULL;
    if (!_this) {
        SDL_UninitializedVideo();
        return SDL_strdup("");
    }
    text_mime_types = SDL_GetTextMimeTypes(_this, &num_mime_types);
    for (i = 0; i < num_mime_types; ++i) {
        void *clipdata = SDL_GetClipboardData(text_mime_types[i], &length);
        if (clipdata) {
            text = (char *)clipdata;
            break;
        }
    }
    if (!text) {
        text = SDL_strdup("");
    }
    return text;
}
References _this, NULL, SDL_GetClipboardData(), SDL_GetTextMimeTypes(), SDL_GetVideoDevice(), SDL_strdup(), and SDL_UninitializedVideo().
SDL_GetPrimarySelectionText()
SDL_DECLSPEC char *SDLCALL SDL_GetPrimarySelectionText (void) extern
Get UTF-8 text from the primary selection.
This functions returns an empty string if there was not enough memory left for a copy of the primary selection's content.
Returns
the primary selection text on success or an empty string on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasPrimarySelectionText
SDL_SetPrimarySelectionText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        SDL_UninitializedVideo();
        return SDL_strdup("");
    }
    if (_this->GetPrimarySelectionText) {
        return _this->GetPrimarySelectionText(_this);
    } else {
        const char *text = _this->primary_selection_text;
        if (!text) {
            text = "";
        }
        return SDL_strdup(text);
    }
}
References _this, SDL_GetVideoDevice(), SDL_strdup(), and SDL_UninitializedVideo().
SDL_HasClipboardData()
SDL_DECLSPEC bool SDLCALL SDL_HasClipboardData (const char * mime_type) extern
Query whether there is data in the clipboard for the provided mime type.
Parameters
mime_type the mime type to check for data for.
Returns
true if there exists data in clipboard for the provided mime type, false if it does not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
SDL_GetClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!mime_type) {
        return SDL_InvalidParamError("mime_type");
    }
    if (_this->HasClipboardData) {
        return _this->HasClipboardData(_this, mime_type);
    } else if (_this->HasClipboardText && SDL_IsTextMimeType(mime_type)) {
        return _this->HasClipboardText(_this);
    } else {
        return SDL_HasInternalClipboardData(_this, mime_type);
    }
}
References _this, SDL_GetVideoDevice(), SDL_HasInternalClipboardData(), SDL_InvalidParamError, SDL_IsTextMimeType(), and SDL_UninitializedVideo().
Referenced by SDL_HasClipboardText().
SDL_HasClipboardText()
SDL_DECLSPEC bool SDLCALL SDL_HasClipboardText (void) extern
Query whether the clipboard exists and contains a non-empty text string.
Returns
true if the clipboard has text, or false if it does not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetClipboardText
SDL_SetClipboardText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t i, num_mime_types;
    const char **text_mime_types;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    text_mime_types = SDL_GetTextMimeTypes(_this, &num_mime_types);
    for (i = 0; i < num_mime_types; ++i) {
        if (SDL_HasClipboardData(text_mime_types[i])) {
            return true;
        }
    }
    return false;
}
References _this, SDL_GetTextMimeTypes(), SDL_GetVideoDevice(), SDL_HasClipboardData(), and SDL_UninitializedVideo().
SDL_HasPrimarySelectionText()
SDL_DECLSPEC bool SDLCALL SDL_HasPrimarySelectionText (void) extern
Query whether the primary selection exists and contains a non-empty text string.
Returns
true if the primary selection has text, or false if it does not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPrimarySelectionText
SDL_SetPrimarySelectionText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (_this->HasPrimarySelectionText) {
        return _this->HasPrimarySelectionText(_this);
    } else {
        if (_this->primary_selection_text && _this->primary_selection_text[0] != '\0') {
            return true;
        } else {
            return false;
        }
    }
}
References _this, SDL_GetVideoDevice(), and SDL_UninitializedVideo().
SDL_SetClipboardData()
SDL_DECLSPEC bool SDLCALL SDL_SetClipboardData (SDL_ClipboardDataCallback callback, SDL_ClipboardCleanupCallback cleanup, void * userdata, const char ** mime_types, size_t num_mime_types) extern
Offer clipboard data to the OS.
Tell the operating system that the application is offering clipboard data for each of the provided mime-types. Once another application requests the data the callback function will be called, allowing it to generate and respond with the data for the requested mime-type.
The size of text data does not include any terminator, and the text does not need to be null terminated (e.g. you can directly copy a portion of a document).
Parameters
callback a function pointer to the function that provides the clipboard data.
cleanup a function pointer to the function that cleans up the clipboard data.
userdata an opaque pointer that will be forwarded to the callbacks.
mime_types a list of mime-types that are being offered.
num_mime_types the number of mime-types in the mime_types list.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearClipboardData
SDL_GetClipboardData
SDL_HasClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    // Parameter validation
    if (!((callback && mime_types && num_mime_types > 0) ||
          (!callback && !mime_types && num_mime_types == 0))) {
        return SDL_SetError("Invalid parameters");
    }
    SDL_CancelClipboardData(0);
    ++_this->clipboard_sequence;
    if (!_this->clipboard_sequence) {
        _this->clipboard_sequence = 1;
    }
    _this->clipboard_callback = callback;
    _this->clipboard_cleanup = cleanup;
    _this->clipboard_userdata = userdata;
    if (!SDL_SaveClipboardMimeTypes(mime_types, num_mime_types)) {
        SDL_ClearClipboardData();
        return false;
    }
    if (_this->SetClipboardData) {
        if (!_this->SetClipboardData(_this)) {
            return false;
        }
    } else if (_this->SetClipboardText) {
        char *text = NULL;
        size_t size;
        for (size_t i = 0; i < num_mime_types; ++i) {
            const char *mime_type = _this->clipboard_mime_types[i];
            if (SDL_IsTextMimeType(mime_type)) {
                const void *data = _this->clipboard_callback(_this->clipboard_userdata, mime_type, &size);
                if (data) {
                    text = (char *)SDL_malloc(size + 1);
                    SDL_memcpy(text, data, size);
                    text[size] = '\0';
                    if (!_this->SetClipboardText(_this, text)) {
                        SDL_free(text);
                        return false;
                    }
                    break;
                }
            }
        }
        if (text) {
            SDL_free(text);
        } else {
            if (!_this->SetClipboardText(_this, "")) {
                return false;
            }
        }
    }
    char **mime_types_copy = SDL_CopyClipboardMimeTypes(mime_types, num_mime_types, true);
    if (!mime_types_copy)
        return SDL_SetError("unable to copy current mime types");
    SDL_SendClipboardUpdate(true, mime_types_copy, num_mime_types);
    return true;
}
References _this, NULL, SDL_CancelClipboardData(), SDL_ClearClipboardData(), SDL_CopyClipboardMimeTypes(), SDL_free(), SDL_GetVideoDevice(), SDL_IsTextMimeType(), SDL_malloc(), SDL_memcpy, SDL_SaveClipboardMimeTypes(), SDL_SendClipboardUpdate(), SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_ClearClipboardData(), and SDL_SetClipboardText().
SDL_SetClipboardText()
SDL_DECLSPEC bool SDLCALL SDL_SetClipboardText (const char * text) extern
CategoryClipboard
SDL provides access to the system clipboard, both for reading information from other processes and publishing information of its own.
This is not just text! SDL apps can access and publish data by mimetype.
Basic use (text)
Obtaining and publishing simple text to the system clipboard is as easy as calling SDL_GetClipboardText() and SDL_SetClipboardText(), respectively. These deal with C strings in UTF-8 encoding. Data transmission and encoding conversion is completely managed by SDL.
Clipboard callbacks (data other than text)
Things get more complicated when the clipboard contains something other than text. Not only can the system clipboard contain data of any type, in some cases it can contain the same data in different formats! For example, an image painting app might let the user copy a graphic to the clipboard, and offers it in .BMP, .JPG, or .PNG format for other apps to consume.
Obtaining clipboard data ("pasting") like this is a matter of calling SDL_GetClipboardData() and telling it the mimetype of the data you want. But how does one know if that format is available? SDL_HasClipboardData() can report if a specific mimetype is offered, and SDL_GetClipboardMimeTypes() can provide the entire list of mimetypes available, so the app can decide what to do with the data and what formats it can support.
Setting the clipboard ("copying") to arbitrary data is done with SDL_SetClipboardData. The app does not provide the data in this call, but rather the mimetypes it is willing to provide and a callback function. During the callback, the app will generate the data. This allows massive data sets to be provided to the clipboard, without any data being copied before it is explicitly requested. More specifically, it allows an app to offer data in multiple formats without providing a copy of all of them upfront. If the app has an image that it could provide in PNG or JPG format, it doesn't have to encode it to either of those unless and until something tries to paste it.
Primary Selection
The X11 and Wayland video targets have a concept of the "primary selection" in addition to the usual clipboard. This is generally highlighted (but not explicitly copied) text from various apps. SDL offers APIs for this through SDL_GetPrimarySelectionText() and SDL_SetPrimarySelectionText(). SDL offers these APIs on platforms without this concept, too, but only so far that it will keep a copy of a string that the app sets for later retrieval; the operating system will not ever attempt to change the string externally if it doesn't support a primary selection. Put UTF-8 text into the clipboard.
Parameters
text the text to store in the clipboard.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetClipboardText
SDL_HasClipboardText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t num_mime_types;
    const char **text_mime_types;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (text && *text) {
        text_mime_types = SDL_GetTextMimeTypes(_this, &num_mime_types);
        return SDL_SetClipboardData(SDL_ClipboardTextCallback, SDL_free, SDL_strdup(text), text_mime_types, num_mime_types);
    }
    return SDL_ClearClipboardData();
}
References _this, SDL_ClearClipboardData(), SDL_ClipboardTextCallback(), SDL_free(), SDL_GetTextMimeTypes(), SDL_GetVideoDevice(), SDL_SetClipboardData(), SDL_strdup(), and SDL_UninitializedVideo().
SDL_SetPrimarySelectionText()
SDL_DECLSPEC bool SDLCALL SDL_SetPrimarySelectionText (const char * text) extern
Put UTF-8 text into the primary selection.
Parameters
text the text to store in the primary selection.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPrimarySelectionText
SDL_HasPrimarySelectionText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!text) {
        text = "";
    }
    if (_this->SetPrimarySelectionText) {
        if (!_this->SetPrimarySelectionText(_this, text)) {
            return false;
        }
    } else {
        SDL_free(_this->primary_selection_text);
        _this->primary_selection_text = SDL_strdup(text);
    }
    char **mime_types = SDL_CopyClipboardMimeTypes((const char **)_this->clipboard_mime_types, _this->num_clipboard_mime_types, true);
    if (!mime_types)
        return SDL_SetError("unable to copy current mime types");
    SDL_SendClipboardUpdate(true, mime_types, _this->num_clipboard_mime_types);
    return true;
}
References _this, SDL_CopyClipboardMimeTypes(), SDL_free(), SDL_GetVideoDevice(), SDL_SendClipboardUpdate(), SDL_SetError(), SDL_strdup(), and SDL_UninitializedVideo().