SDL3: SDL-main/src/stdlib/SDL_crc16.c File Reference
SDL_crc16.c File Reference
#include "SDL_internal.h"
Functions
static Uint16 crc16_for_byte (Uint8 r)
Uint16 SDL_crc16 (Uint16 crc, const void *data, size_t len)
Function Documentation
crc16_for_byte()
Uint16 crc16_for_byte (Uint8 r) static
{
    Uint16 crc = 0;
    int i;
    for (i = 0; i < 8; ++i) {
        crc = ((crc ^ r) & 1 ? 0xA001 : 0) ^ crc >> 1;
        r >>= 1;
    }
    return crc;
}
Referenced by SDL_crc16().
SDL_crc16()
Uint16 SDL_crc16 (Uint16 crc, const void * data, size_t len)
Calculate a CRC-16 value.
https://en.wikipedia.org/wiki/Cyclic_redundancy_check
This function can be called multiple times, to stream data to be checksummed in blocks. Each call must provide the previous CRC-16 return value to be updated with the next block. The first call to this function for a set of blocks should pass in a zero CRC value.
Parameters
crc the current checksum for this data set, or 0 for a new data set.
data a new block of data to add to the checksum.
len the size, in bytes, of the new block of data.
Returns
a CRC-16 checksum value of all blocks in the data set.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    // As an optimization we can precalculate a 256 entry table for each byte
    size_t i;
    for (i = 0; i < len; ++i) {
        crc = crc16_for_byte((Uint8)crc ^ ((const Uint8 *)data)[i]) ^ crc >> 8;
    }
    return crc;
}
References crc16_for_byte().
Referenced by SDL_CreateJoystickGUID().