SDL3: SDL-main/src/thread/windows/SDL_sysrwlock_srw.c File Reference
SDL_sysrwlock_srw.c File Reference
#include "SDL_internal.h"
#include "SDL_sysmutex_c.h"
#include "../generic/SDL_sysrwlock_c.h"
Data Structures
struct SDL_rwlock_impl_t
struct SDL_rwlock_srw
Macros
#define LOOKUP_SRW_SYM(sym)
Typedefs
typedef VOID(WINAPI * pfnAcquireSRWLockExclusive) (PSRWLOCK)
typedef VOID(WINAPI * pfnAcquireSRWLockShared) (PSRWLOCK)
typedef VOID(WINAPI * pfnInitializeSRWLock) (PSRWLOCK)
typedef VOID(WINAPI * pfnReleaseSRWLockExclusive) (PSRWLOCK)
typedef VOID(WINAPI * pfnReleaseSRWLockShared) (PSRWLOCK)
typedef SDL_RWLock *(* pfnSDL_CreateRWLock) (void)
typedef void(* pfnSDL_DestroyRWLock) (SDL_RWLock *)
typedef void(* pfnSDL_LockRWLockForReading) (SDL_RWLock *)
typedef void(* pfnSDL_LockRWLockForWriting) (SDL_RWLock *)
typedef bool(* pfnSDL_TryLockRWLockForReading) (SDL_RWLock *)
typedef bool(* pfnSDL_TryLockRWLockForWriting) (SDL_RWLock *)
typedef void(* pfnSDL_UnlockRWLock) (SDL_RWLock *)
typedef BOOLEAN(WINAPI * pfnTryAcquireSRWLockExclusive) (PSRWLOCK)
typedef BOOLEAN(WINAPI * pfnTryAcquireSRWLockShared) (PSRWLOCK)
typedef struct SDL_rwlock_impl_t SDL_rwlock_impl_t
typedef struct SDL_rwlock_srw SDL_rwlock_srw
Functions
SDL_RWLock * SDL_CreateRWLock (void)
static SDL_RWLock * SDL_CreateRWLock_srw (void)
void SDL_DestroyRWLock (SDL_RWLock *rwlock)
static void SDL_DestroyRWLock_srw (SDL_RWLock *_rwlock)
void SDL_LockRWLockForReading (SDL_RWLock *rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
static void SDL_LockRWLockForReading_srw (SDL_RWLock *_rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
void SDL_LockRWLockForWriting (SDL_RWLock *rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
static void SDL_LockRWLockForWriting_srw (SDL_RWLock *_rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
bool SDL_TryLockRWLockForReading (SDL_RWLock *rwlock)
static bool SDL_TryLockRWLockForReading_srw (SDL_RWLock *_rwlock)
bool SDL_TryLockRWLockForWriting (SDL_RWLock *rwlock)
static bool SDL_TryLockRWLockForWriting_srw (SDL_RWLock *_rwlock)
void SDL_UnlockRWLock (SDL_RWLock *rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
static void SDL_UnlockRWLock_srw (SDL_RWLock *_rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
Variables
static pfnAcquireSRWLockExclusive pAcquireSRWLockExclusive = NULL
static pfnAcquireSRWLockShared pAcquireSRWLockShared = NULL
static pfnInitializeSRWLock pInitializeSRWLock = NULL
static pfnReleaseSRWLockExclusive pReleaseSRWLockExclusive = NULL
static pfnReleaseSRWLockShared pReleaseSRWLockShared = NULL
static pfnTryAcquireSRWLockExclusive pTryAcquireSRWLockExclusive = NULL
static pfnTryAcquireSRWLockShared pTryAcquireSRWLockShared = NULL
static SDL_rwlock_impl_t SDL_rwlock_impl_active = { 0 }
static const SDL_rwlock_impl_t SDL_rwlock_impl_generic
static const SDL_rwlock_impl_t SDL_rwlock_impl_srw
Macro Definition Documentation
LOOKUP_SRW_SYM
#define LOOKUP_SRW_SYM (sym)
Value:
if (okay) { if ((p##sym = (pfn##sym)GetProcAddress(kernel32, #sym)) == NULL) { okay = false; } }
Referenced by SDL_CreateRWLock().
Typedef Documentation
pfnAcquireSRWLockExclusive
typedef VOID(WINAPI * pfnAcquireSRWLockExclusive) (PSRWLOCK)
pfnAcquireSRWLockShared
typedef VOID(WINAPI * pfnAcquireSRWLockShared) (PSRWLOCK)
pfnInitializeSRWLock
typedef VOID(WINAPI * pfnInitializeSRWLock) (PSRWLOCK)
Implementation based on Slim Reader/Writer (SRW) Locks for Win 7 and newer.
pfnReleaseSRWLockExclusive
typedef VOID(WINAPI * pfnReleaseSRWLockExclusive) (PSRWLOCK)
pfnReleaseSRWLockShared
typedef VOID(WINAPI * pfnReleaseSRWLockShared) (PSRWLOCK)
pfnSDL_CreateRWLock
typedef SDL_RWLock *(* pfnSDL_CreateRWLock) (void)
pfnSDL_DestroyRWLock
typedef void(* pfnSDL_DestroyRWLock) (SDL_RWLock *)
pfnSDL_LockRWLockForReading
typedef void(* pfnSDL_LockRWLockForReading) (SDL_RWLock *)
pfnSDL_LockRWLockForWriting
typedef void(* pfnSDL_LockRWLockForWriting) (SDL_RWLock *)
pfnSDL_TryLockRWLockForReading
typedef bool(* pfnSDL_TryLockRWLockForReading) (SDL_RWLock *)
pfnSDL_TryLockRWLockForWriting
typedef bool(* pfnSDL_TryLockRWLockForWriting) (SDL_RWLock *)
pfnSDL_UnlockRWLock
typedef void(* pfnSDL_UnlockRWLock) (SDL_RWLock *)
pfnTryAcquireSRWLockExclusive
typedef BOOLEAN(WINAPI * pfnTryAcquireSRWLockExclusive) (PSRWLOCK)
pfnTryAcquireSRWLockShared
typedef BOOLEAN(WINAPI * pfnTryAcquireSRWLockShared) (PSRWLOCK)
SDL_rwlock_impl_t
typedef struct SDL_rwlock_impl_t SDL_rwlock_impl_t
SDL_rwlock_srw
typedef struct SDL_rwlock_srw SDL_rwlock_srw
Function Documentation
SDL_CreateRWLock()
SDL_RWLock * SDL_CreateRWLock (void)
Create a new read/write lock.
A read/write lock is useful for situations where you have multiple threads trying to access a resource that is rarely updated. All threads requesting a read-only lock will be allowed to run in parallel; if a thread requests a write lock, it will be provided exclusive access. This makes it safe for multiple threads to use a resource at the same time if they promise not to change it, and when it has to be changed, the rwlock will serve as a gateway to make sure those changes can be made safely.
In the right situation, a rwlock can be more efficient than a mutex, which only lets a single thread proceed at a time, even if it won't be modifying the data.
All newly-created read/write locks begin in the unlocked state.
Calls to SDL_LockRWLockForReading() and SDL_LockRWLockForWriting will not return while the rwlock is locked for writing by another thread. See SDL_TryLockRWLockForReading() and SDL_TryLockRWLockForWriting() to attempt to lock without blocking.
SDL read/write locks are only recursive for read-only locks! They are not guaranteed to be fair, or provide access in a FIFO manner! They are not guaranteed to favor writers. You may not lock a rwlock for both read-only and write access at the same time from the same thread (so you can't promote your read-only lock to a write lock without unlocking first).
Returns
the initialized and unlocked read/write lock or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyRWLock
SDL_LockRWLockForReading
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
    if (!SDL_rwlock_impl_active.Create) {
        // Default to generic implementation, works with all mutex implementations
        const SDL_rwlock_impl_t *impl = &SDL_rwlock_impl_generic;
        {
            HMODULE kernel32 = GetModuleHandle(TEXT("kernel32.dll"));
            if (kernel32) {
                bool okay = true;
                #define LOOKUP_SRW_SYM(sym) if (okay) { if ((p##sym = (pfn##sym)GetProcAddress(kernel32, #sym)) == NULL) { okay = false; } }
                LOOKUP_SRW_SYM(InitializeSRWLock);
                LOOKUP_SRW_SYM(ReleaseSRWLockShared);
                LOOKUP_SRW_SYM(AcquireSRWLockShared);
                LOOKUP_SRW_SYM(TryAcquireSRWLockShared);
                LOOKUP_SRW_SYM(ReleaseSRWLockExclusive);
                LOOKUP_SRW_SYM(AcquireSRWLockExclusive);
                LOOKUP_SRW_SYM(TryAcquireSRWLockExclusive);
                #undef LOOKUP_SRW_SYM
                if (okay) {
                    impl = &SDL_rwlock_impl_srw;  // Use the Windows provided API instead of generic fallback
                }
            }
        }
        SDL_copyp(&SDL_rwlock_impl_active, impl);
    }
    return SDL_rwlock_impl_active.Create();
}
References SDL_RWLock::condition, kernel32, SDL_RWLock::lock, LOOKUP_SRW_SYM, NULL, SDL_RWLock::reader_count, SDL_calloc(), SDL_copyp, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroyMutex(), SDL_free(), SDL_rwlock_impl_active, SDL_rwlock_impl_generic, SDL_rwlock_impl_srw, SDL_SetAtomicInt(), and SDL_RWLock::writer_count.
Referenced by SDL_CameraInit(), SDL_CreateHashTable(), SDL_InitAudio(), and SDL_InitPen().
SDL_CreateRWLock_srw()
SDL_RWLock * SDL_CreateRWLock_srw (void) static
{
    SDL_rwlock_srw *rwlock = (SDL_rwlock_srw *)SDL_calloc(1, sizeof(*rwlock));
    if (rwlock) {
        pInitializeSRWLock(&rwlock->srw);
    }
    return (SDL_RWLock *)rwlock;
}
References pInitializeSRWLock, SDL_calloc(), and SDL_rwlock_srw::srw.
SDL_DestroyRWLock()
void SDL_DestroyRWLock (SDL_RWLock * rwlock)
Destroy a read/write lock created with SDL_CreateRWLock().
This function must be called on any read/write lock that is no longer needed. Failure to destroy a rwlock will result in a system memory or resource leak. While it is safe to destroy a rwlock that is unlocked, it is not safe to attempt to destroy a locked rwlock, and may result in undefined behavior depending on the platform.
Parameters
rwlock the rwlock to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRWLock
{
    if (rwlock) {
        SDL_rwlock_impl_active.Destroy(rwlock);
    }
}
References SDL_RWLock::condition, SDL_RWLock::lock, SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_free(), and SDL_rwlock_impl_active.
Referenced by SDL_CameraInit(), SDL_DestroyHashTable(), SDL_InitAudio(), SDL_QuitAudio(), SDL_QuitCamera(), and SDL_QuitPen().
SDL_DestroyRWLock_srw()
void SDL_DestroyRWLock_srw (SDL_RWLock * _rwlock) static
{
    SDL_rwlock_srw *rwlock = (SDL_rwlock_srw *) _rwlock;
    // There are no kernel allocated resources
    SDL_free(rwlock);
}
References SDL_free().
SDL_LockRWLockForReading()
void SDL_LockRWLockForReading (SDL_RWLock * rwlock)
Lock the read/write lock for read only operations.
This will block until the rwlock is available, which is to say it is not locked for writing by any other thread. Of all threads waiting to lock the rwlock, all may do so at the same time as long as they are requesting read-only access; if a thread wants to lock for writing, only one may do so at a time, and no other threads, read-only or not, may hold the lock at the same time.
It is legal for the owning thread to lock an already-locked rwlock for reading. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive rwlock").
Note that locking for writing is not recursive (this is only available to read-only locks).
It is illegal to request a read-only lock from a thread that already holds the write lock. Doing so results in undefined behavior. Unlock the write lock before requesting a read-only lock. (But, of course, if you have the write lock, you don't need further locks to read in any case.)
This function does not fail; if rwlock is NULL, it will return immediately having locked nothing. If the rwlock is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
rwlock the read/write lock to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_UnlockRWLock
{
    if (rwlock) {
        SDL_rwlock_impl_active.LockForReading(rwlock);
    }
}
References SDL_AddAtomicInt(), SDL_assert, SDL_GetAtomicInt(), SDL_LockMutex(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_impl_active, and SDL_UnlockMutex().
Referenced by CreatePhysicalAudioDevice(), GetAudioDevices(), GetFirstAddedAudioDevice(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), ObtainPhysicalCamera(), SDL_AddCamera(), SDL_AudioDeviceDisconnected(), SDL_FindInHashTable(), SDL_FindPenByCallback(), SDL_FindPenByHandle(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetAudioDeviceName(), SDL_GetCameras(), SDL_GetPenStatus(), SDL_HashTableEmpty(), SDL_IterateHashTable(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_UpdateAudio(), and SDL_UpdateCamera().
SDL_LockRWLockForReading_srw()
void SDL_LockRWLockForReading_srw (SDL_RWLock * _rwlock) static
{
    SDL_rwlock_srw *rwlock = (SDL_rwlock_srw *) _rwlock;
    pAcquireSRWLockShared(&rwlock->srw);
}
References pAcquireSRWLockShared, SDL_NO_THREAD_SAFETY_ANALYSIS, and SDL_rwlock_srw::srw.
SDL_LockRWLockForWriting()
void SDL_LockRWLockForWriting (SDL_RWLock * rwlock)
Lock the read/write lock for write operations.
This will block until the rwlock is available, which is to say it is not locked for reading or writing by any other thread. Only one thread may hold the lock when it requests write access; all other threads, whether they also want to write or only want read-only access, must wait until the writer thread has released the lock.
It is illegal for the owning thread to lock an already-locked rwlock for writing (read-only may be locked recursively, writing can not). Doing so results in undefined behavior.
It is illegal to request a write lock from a thread that already holds a read-only lock. Doing so results in undefined behavior. Unlock the read-only lock before requesting a write lock.
This function does not fail; if rwlock is NULL, it will return immediately having locked nothing. If the rwlock is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
rwlock the read/write lock to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
    if (rwlock) {
        SDL_rwlock_impl_active.LockForWriting(rwlock);
    }
}
References SDL_AddAtomicInt(), SDL_GetAtomicInt(), SDL_LockMutex(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_impl_active, and SDL_WaitCondition().
Referenced by CreatePhysicalAudioDevice(), DestroyLogicalAudioDevice(), OnAudioStreamCreated(), OnAudioStreamDestroy(), SDL_AddAudioDevice(), SDL_AddCamera(), SDL_AddPenDevice(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CameraDisconnected(), SDL_CameraPermissionOutcome(), SDL_ClearHashTable(), SDL_DefaultAudioDeviceChanged(), SDL_InsertIntoHashTable(), SDL_OpenAudioDevice(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_RemoveAllPenDevices(), SDL_RemoveFromHashTable(), SDL_RemovePenDevice(), SDL_UpdateAudio(), SDL_UpdateCamera(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().
SDL_LockRWLockForWriting_srw()
void SDL_LockRWLockForWriting_srw (SDL_RWLock * _rwlock) static
{
    SDL_rwlock_srw *rwlock = (SDL_rwlock_srw *) _rwlock;
    pAcquireSRWLockExclusive(&rwlock->srw);
    rwlock->write_owner = SDL_GetCurrentThreadID();
}
References pAcquireSRWLockExclusive, SDL_GetCurrentThreadID(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_srw::srw, and SDL_rwlock_srw::write_owner.
SDL_TryLockRWLockForReading()
bool SDL_TryLockRWLockForReading (SDL_RWLock * rwlock)
Try to lock a read/write lock for reading without blocking.
This works just like SDL_LockRWLockForReading(), but if the rwlock is not available, then this function returns false immediately.
This technique is useful if you need access to a resource but don't want to wait for it, and will return to it to try again later.
Trying to lock for read-only access can succeed if other threads are holding read-only locks, as this won't prevent access.
This function returns true if passed a NULL rwlock.
Parameters
rwlock the rwlock to try to lock.
Returns
true on success, false if the lock would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
    bool result = true;
    if (rwlock) {
        result = SDL_rwlock_impl_active.TryLockForReading(rwlock);
    }
    return result;
}
References SDL_rwlock_impl_active, and SDL_TryLockRWLockForReading_generic().
SDL_TryLockRWLockForReading_srw()
bool SDL_TryLockRWLockForReading_srw (SDL_RWLock * _rwlock) static
{
    SDL_rwlock_srw *rwlock = (SDL_rwlock_srw *) _rwlock;
    return pTryAcquireSRWLockShared(&rwlock->srw);
}
References pTryAcquireSRWLockShared, and SDL_rwlock_srw::srw.
SDL_TryLockRWLockForWriting()
bool SDL_TryLockRWLockForWriting (SDL_RWLock * rwlock)
Try to lock a read/write lock for writing without blocking.
This works just like SDL_LockRWLockForWriting(), but if the rwlock is not available, then this function returns false immediately.
This technique is useful if you need exclusive access to a resource but don't want to wait for it, and will return to it to try again later.
It is illegal for the owning thread to lock an already-locked rwlock for writing (read-only may be locked recursively, writing can not). Doing so results in undefined behavior.
It is illegal to request a write lock from a thread that already holds a read-only lock. Doing so results in undefined behavior. Unlock the read-only lock before requesting a write lock.
This function returns true if passed a NULL rwlock.
Parameters
rwlock the rwlock to try to lock.
Returns
true on success, false if the lock would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_UnlockRWLock
{
    bool result = true;
    if (rwlock) {
        result = SDL_rwlock_impl_active.TryLockForWriting(rwlock);
    }
    return result;
}
References SDL_rwlock_impl_active, and SDL_TryLockRWLockForWriting_generic().
SDL_TryLockRWLockForWriting_srw()
bool SDL_TryLockRWLockForWriting_srw (SDL_RWLock * _rwlock) static
{
    SDL_rwlock_srw *rwlock = (SDL_rwlock_srw *) _rwlock;
    if (pTryAcquireSRWLockExclusive(&rwlock->srw)) {
        rwlock->write_owner = SDL_GetCurrentThreadID();
        return true;
    } else {
        return false;
    }
}
References pTryAcquireSRWLockExclusive, SDL_GetCurrentThreadID(), SDL_rwlock_srw::srw, and SDL_rwlock_srw::write_owner.
SDL_UnlockRWLock()
void SDL_UnlockRWLock (SDL_RWLock * rwlock)
Unlock the read/write lock.
Use this function to unlock the rwlock, whether it was locked for read-only or write operations.
It is legal for the owning thread to lock an already-locked read-only lock. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive rwlock").
It is illegal to unlock a rwlock that has not been locked by the current thread, and doing so results in undefined behavior.
Parameters
rwlock the rwlock to unlock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_TryLockRWLockForWriting
{
    if (rwlock) {
        SDL_rwlock_impl_active.Unlock(rwlock);
    }
}
References SDL_AddAtomicInt(), SDL_BroadcastCondition(), SDL_GetAtomicInt(), SDL_LockMutex(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_impl_active, and SDL_UnlockMutex().
Referenced by CreatePhysicalAudioDevice(), DestroyLogicalAudioDevice(), GetAudioDevices(), GetFirstAddedAudioDevice(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), ObtainPhysicalCamera(), OnAudioStreamCreated(), OnAudioStreamDestroy(), SDL_AddAudioDevice(), SDL_AddCamera(), SDL_AddPenDevice(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CameraDisconnected(), SDL_CameraPermissionOutcome(), SDL_ClearHashTable(), SDL_DefaultAudioDeviceChanged(), SDL_FindInHashTable(), SDL_FindPenByCallback(), SDL_FindPenByHandle(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetAudioDeviceName(), SDL_GetCameras(), SDL_GetPenStatus(), SDL_HashTableEmpty(), SDL_InsertIntoHashTable(), SDL_IterateHashTable(), SDL_OpenAudioDevice(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_RemoveAllPenDevices(), SDL_RemoveFromHashTable(), SDL_RemovePenDevice(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_UpdateAudio(), SDL_UpdateCamera(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().
SDL_UnlockRWLock_srw()
void SDL_UnlockRWLock_srw (SDL_RWLock * _rwlock) static
{
    SDL_rwlock_srw *rwlock = (SDL_rwlock_srw *) _rwlock;
    if (rwlock->write_owner == SDL_GetCurrentThreadID()) {
        rwlock->write_owner = 0;
        pReleaseSRWLockExclusive(&rwlock->srw);
    } else {
        pReleaseSRWLockShared(&rwlock->srw);
    }
}
References pReleaseSRWLockExclusive, pReleaseSRWLockShared, SDL_GetCurrentThreadID(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_srw::srw, and SDL_rwlock_srw::write_owner.
Variable Documentation
pAcquireSRWLockExclusive
pfnAcquireSRWLockExclusive pAcquireSRWLockExclusive = NULL static
Referenced by SDL_LockRWLockForWriting_srw().
pAcquireSRWLockShared
pfnAcquireSRWLockShared pAcquireSRWLockShared = NULL static
Referenced by SDL_LockRWLockForReading_srw().
pInitializeSRWLock
pfnInitializeSRWLock pInitializeSRWLock = NULL static
Referenced by SDL_CreateRWLock_srw().
pReleaseSRWLockExclusive
pfnReleaseSRWLockExclusive pReleaseSRWLockExclusive = NULL static
Referenced by SDL_UnlockRWLock_srw().
pReleaseSRWLockShared
pfnReleaseSRWLockShared pReleaseSRWLockShared = NULL static
Referenced by SDL_UnlockRWLock_srw().
pTryAcquireSRWLockExclusive
pfnTryAcquireSRWLockExclusive pTryAcquireSRWLockExclusive = NULL static
Referenced by SDL_TryLockRWLockForWriting_srw().
pTryAcquireSRWLockShared
pfnTryAcquireSRWLockShared pTryAcquireSRWLockShared = NULL static
Referenced by SDL_TryLockRWLockForReading_srw().
SDL_rwlock_impl_active
SDL_rwlock_impl_t SDL_rwlock_impl_active = { 0 } static
{ 0 };
Referenced by SDL_CreateRWLock(), SDL_DestroyRWLock(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_TryLockRWLockForReading(), SDL_TryLockRWLockForWriting(), and SDL_UnlockRWLock().
SDL_rwlock_impl_generic
const SDL_rwlock_impl_t SDL_rwlock_impl_generic static
Initial value:
= {
    &SDL_CreateRWLock_generic,
    &SDL_DestroyRWLock_generic,
    &SDL_LockRWLockForReading_generic,
    &SDL_LockRWLockForWriting_generic,
    &SDL_TryLockRWLockForReading_generic,
    &SDL_TryLockRWLockForWriting_generic,
    &SDL_UnlockRWLock_generic
}
{
    &SDL_CreateRWLock_generic,
    &SDL_DestroyRWLock_generic,
    &SDL_LockRWLockForReading_generic,
    &SDL_LockRWLockForWriting_generic,
    &SDL_TryLockRWLockForReading_generic,
    &SDL_TryLockRWLockForWriting_generic,
    &SDL_UnlockRWLock_generic
};
Referenced by SDL_CreateRWLock().
SDL_rwlock_impl_srw
const SDL_rwlock_impl_t SDL_rwlock_impl_srw static
Initial value:
= {
    &SDL_CreateRWLock_srw,
    &SDL_DestroyRWLock_srw,
    &SDL_LockRWLockForReading_srw,
    &SDL_LockRWLockForWriting_srw,
    &SDL_TryLockRWLockForReading_srw,
    &SDL_TryLockRWLockForWriting_srw,
    &SDL_UnlockRWLock_srw
}
{
    &SDL_CreateRWLock_srw,
    &SDL_DestroyRWLock_srw,
    &SDL_LockRWLockForReading_srw,
    &SDL_LockRWLockForWriting_srw,
    &SDL_TryLockRWLockForReading_srw,
    &SDL_TryLockRWLockForWriting_srw,
    &SDL_UnlockRWLock_srw
};
Referenced by SDL_CreateRWLock().