SDL3: SDL-main/src/haptic/SDL_haptic.c File Reference
SDL_haptic.c File Reference
#include "SDL_internal.h"
#include "SDL_syshaptic.h"
#include "SDL_haptic_c.h"
#include "../joystick/SDL_joystick_c.h"
#include "../SDL_hints_c.h"
Data Structures
struct SDL_Haptic_VIDPID_Naxes
Macros
#define CHECK_HAPTIC_MAGIC(haptic, result)
Typedefs
typedef struct SDL_Haptic_VIDPID_Naxes SDL_Haptic_VIDPID_Naxes
Functions
void SDL_CloseHaptic (SDL_Haptic *haptic)
SDL_HapticEffectID SDL_CreateHapticEffect (SDL_Haptic *haptic, const SDL_HapticEffect *effect)
void SDL_DestroyHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect)
bool SDL_GetHapticEffectStatus (SDL_Haptic *haptic, SDL_HapticEffectID effect)
Uint32 SDL_GetHapticFeatures (SDL_Haptic *haptic)
SDL_Haptic * SDL_GetHapticFromID (SDL_HapticID instance_id)
SDL_HapticID SDL_GetHapticID (SDL_Haptic *haptic)
static bool SDL_GetHapticIndex (SDL_HapticID instance_id, int *driver_index)
const char * SDL_GetHapticName (SDL_Haptic *haptic)
const char * SDL_GetHapticNameForID (SDL_HapticID instance_id)
SDL_HapticID * SDL_GetHaptics (int *count)
int SDL_GetMaxHapticEffects (SDL_Haptic *haptic)
int SDL_GetMaxHapticEffectsPlaying (SDL_Haptic *haptic)
int SDL_GetNumHapticAxes (SDL_Haptic *haptic)
static int SDL_Haptic_Get_Naxes (Uint16 vid, Uint16 pid)
static void SDL_Haptic_Load_Axes_List (SDL_Haptic_VIDPID_Naxes **entries, int *num_entries)
static int SDL_Haptic_Naxes_List_Index (struct SDL_Haptic_VIDPID_Naxes *entries, int num_entries, Uint16 vid, Uint16 pid)
bool SDL_HapticEffectSupported (SDL_Haptic *haptic, const SDL_HapticEffect *effect)
bool SDL_HapticRumbleSupported (SDL_Haptic *haptic)
bool SDL_InitHapticRumble (SDL_Haptic *haptic)
bool SDL_InitHaptics (void)
bool SDL_IsJoystickHaptic (SDL_Joystick *joystick)
bool SDL_IsMouseHaptic (void)
SDL_Haptic * SDL_OpenHaptic (SDL_HapticID instance_id)
SDL_Haptic * SDL_OpenHapticFromJoystick (SDL_Joystick *joystick)
SDL_Haptic * SDL_OpenHapticFromMouse (void)
bool SDL_PauseHaptic (SDL_Haptic *haptic)
bool SDL_PlayHapticRumble (SDL_Haptic *haptic, float strength, Uint32 length)
void SDL_QuitHaptics (void)
bool SDL_ResumeHaptic (SDL_Haptic *haptic)
bool SDL_RunHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect, Uint32 iterations)
bool SDL_SetHapticAutocenter (SDL_Haptic *haptic, int autocenter)
bool SDL_SetHapticGain (SDL_Haptic *haptic, int gain)
bool SDL_StopHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect)
bool SDL_StopHapticEffects (SDL_Haptic *haptic)
bool SDL_StopHapticRumble (SDL_Haptic *haptic)
bool SDL_UpdateHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect, const SDL_HapticEffect *data)
static bool ValidEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect)
Variables
static SDL_Haptic * SDL_haptics = NULL
Macro Definition Documentation
CHECK_HAPTIC_MAGIC
#define CHECK_HAPTIC_MAGIC (haptic, result)
Value:
    if (!SDL_ObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC)) { \
        SDL_InvalidParamError("haptic");                    \
        return result;                                      \
    }
#define CHECK_HAPTIC_MAGIC(haptic, result)                  \
    if (!SDL_ObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC)) { \
        SDL_InvalidParamError("haptic");                    \
        return result;                                      \
    }
Referenced by SDL_CloseHaptic(), SDL_CreateHapticEffect(), SDL_DestroyHapticEffect(), SDL_GetHapticEffectStatus(), SDL_GetHapticFeatures(), SDL_GetHapticID(), SDL_GetHapticName(), SDL_GetMaxHapticEffects(), SDL_GetMaxHapticEffectsPlaying(), SDL_GetNumHapticAxes(), SDL_HapticEffectSupported(), SDL_HapticRumbleSupported(), SDL_InitHapticRumble(), SDL_PauseHaptic(), SDL_PlayHapticRumble(), SDL_ResumeHaptic(), SDL_RunHapticEffect(), SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_StopHapticEffect(), SDL_StopHapticEffects(), SDL_StopHapticRumble(), and SDL_UpdateHapticEffect().
Typedef Documentation
SDL_Haptic_VIDPID_Naxes
typedef struct SDL_Haptic_VIDPID_Naxes SDL_Haptic_VIDPID_Naxes
Function Documentation
SDL_CloseHaptic()
void SDL_CloseHaptic (SDL_Haptic * haptic)
Close a haptic device previously opened with SDL_OpenHaptic().
Parameters
haptic the SDL_Haptic device to close.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHaptic
{
    SDL_HapticEffectID i;
    SDL_Haptic *hapticlist;
    SDL_Haptic *hapticlistprev;
    CHECK_HAPTIC_MAGIC(haptic,);
    // Check if it's still in use
    if (--haptic->ref_count > 0) {
        return;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        SDL_HIDAPI_HapticClose(haptic);
    } else
    #endif
    {
        // Close it, properly removing effects if needed
        for (i = 0; i < haptic->neffects; i++) {
            if (haptic->effects[i].hweffect != NULL) {
                SDL_DestroyHapticEffect(haptic, i);
            }
        }
        SDL_SYS_HapticClose(haptic);
    }
    SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, false);
    // Remove from the list
    hapticlist = SDL_haptics;
    hapticlistprev = NULL;
    while (hapticlist) {
        if (haptic == hapticlist) {
            if (hapticlistprev) {
                // unlink this entry
                hapticlistprev->next = hapticlist->next;
            } else {
                SDL_haptics = haptic->next;
            }
            break;
        }
        hapticlistprev = hapticlist;
        hapticlist = hapticlist->next;
    }
    // Free the data associated with this device
    SDL_free(haptic->name);
    SDL_free(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, haptic_effect::hweffect, SDL_Haptic::name, SDL_Haptic::neffects, SDL_Haptic::next, NULL, SDL_Haptic::ref_count, SDL_DestroyHapticEffect(), SDL_free(), SDL_haptics, SDL_HIDAPI_HapticClose(), SDL_HIDAPI_HapticIsHidapi(), SDL_OBJECT_TYPE_HAPTIC, SDL_SetObjectValid(), and SDL_SYS_HapticClose().
Referenced by SDL_QuitHaptics().
SDL_CreateHapticEffect()
SDL_HapticEffectID SDL_CreateHapticEffect (SDL_Haptic * haptic, const SDL_HapticEffect * effect)
Create a new haptic effect on a specified device.
Parameters
haptic an SDL_Haptic device to create the effect on.
effect an SDL_HapticEffect structure containing the properties of the effect to create.
Returns
the ID of the effect on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyHapticEffect
SDL_RunHapticEffect
SDL_UpdateHapticEffect
{
    SDL_HapticEffectID i;
    CHECK_HAPTIC_MAGIC(haptic, -1);
    if (!effect) {
        SDL_InvalidParamError("effect");
        return -1;
    }
    // Check to see if effect is supported
    if (SDL_HapticEffectSupported(haptic, effect) == false) {
        SDL_SetError("Haptic: Effect not supported by haptic device.");
        return -1;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticNewEffect(haptic, effect);
    }
    #endif
    // See if there's a free slot
    for (i = 0; i < haptic->neffects; i++) {
        if (haptic->effects[i].hweffect == NULL) {
            // Now let the backend create the real effect
            if (!SDL_SYS_HapticNewEffect(haptic, &haptic->effects[i], effect)) {
                return -1; // Backend failed to create effect
            }
            SDL_memcpy(&haptic->effects[i].effect, effect,
                       sizeof(SDL_HapticEffect));
            return i;
        }
    }
    SDL_SetError("Haptic: Device has no free space left.");
    return -1;
}
References CHECK_HAPTIC_MAGIC, haptic_effect::effect, SDL_Haptic::effects, haptic_effect::hweffect, SDL_Haptic::neffects, NULL, SDL_HapticEffectSupported(), SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticNewEffect(), SDL_InvalidParamError, SDL_memcpy, SDL_SetError(), and SDL_SYS_HapticNewEffect().
Referenced by SDL_InitHapticRumble().
SDL_DestroyHapticEffect()
void SDL_DestroyHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect)
Destroy a haptic effect on the device.
This will stop the effect if it's running. Effects are automatically destroyed when the device is closed.
Parameters
haptic the SDL_Haptic device to destroy the effect on.
effect the ID of the haptic effect to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateHapticEffect
{
    CHECK_HAPTIC_MAGIC(haptic,);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        SDL_HIDAPI_HapticDestroyEffect(haptic, effect);
        return;
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return;
    }
    // Not allocated
    if (haptic->effects[effect].hweffect == NULL) {
        return;
    }
    SDL_SYS_HapticDestroyEffect(haptic, &haptic->effects[effect]);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, haptic_effect::hweffect, NULL, SDL_HIDAPI_HapticDestroyEffect(), SDL_HIDAPI_HapticIsHidapi(), SDL_SYS_HapticDestroyEffect(), and ValidEffect().
Referenced by SDL_CloseHaptic().
SDL_GetHapticEffectStatus()
bool SDL_GetHapticEffectStatus (SDL_Haptic * haptic, SDL_HapticEffectID effect)
Get the status of the current effect on the specified haptic device.
Device must support the SDL_HAPTIC_STATUS feature.
Parameters
haptic the SDL_Haptic device to query for the effect status on.
effect the ID of the haptic effect to query its status.
Returns
true if it is playing, false if it isn't playing or haptic status isn't supported.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticGetEffectStatus(haptic, effect);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    if (!(haptic->supported & SDL_HAPTIC_STATUS)) {
        return SDL_SetError("Haptic: Device does not support status queries.");
    }
    SDL_ClearError();
    return (SDL_SYS_HapticGetEffectStatus(haptic, &haptic->effects[effect]) > 0);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, SDL_ClearError(), SDL_HAPTIC_STATUS, SDL_HIDAPI_HapticGetEffectStatus(), SDL_HIDAPI_HapticIsHidapi(), SDL_SetError(), SDL_SYS_HapticGetEffectStatus(), SDL_Haptic::supported, and ValidEffect().
SDL_GetHapticFeatures()
Uint32 SDL_GetHapticFeatures (SDL_Haptic * haptic)
Get the haptic device's supported features in bitwise manner.
Parameters
haptic the SDL_Haptic device to query.
Returns
a list of supported haptic features in bitwise manner (OR'd), or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_HapticEffectSupported
SDL_GetMaxHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, 0);
    return haptic->supported;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::supported.
SDL_GetHapticFromID()
SDL_Haptic * SDL_GetHapticFromID (SDL_HapticID instance_id)
Get the SDL_Haptic associated with an instance ID, if it has been opened.
Parameters
instance_id the instance ID to get the SDL_Haptic for.
Returns
an SDL_Haptic on success or NULL on failure or if it hasn't been opened yet; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Haptic *haptic;
    for (haptic = SDL_haptics; haptic; haptic = haptic->next) {
        if (instance_id == haptic->instance_id) {
            break;
        }
    }
    return haptic;
}
References SDL_Haptic::instance_id, SDL_Haptic::next, and SDL_haptics.
SDL_GetHapticID()
SDL_HapticID SDL_GetHapticID (SDL_Haptic * haptic)
Get the instance ID of an opened haptic device.
Parameters
haptic the SDL_Haptic device to query.
Returns
the instance ID of the specified haptic device on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_HAPTIC_MAGIC(haptic, 0);
    return haptic->instance_id;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::instance_id.
SDL_GetHapticIndex()
bool SDL_GetHapticIndex (SDL_HapticID instance_id, int * driver_index) static
{
    int num_haptics, device_index;
    if (instance_id > 0) {
        num_haptics = SDL_SYS_NumHaptics();
        for (device_index = 0; device_index < num_haptics; ++device_index) {
            SDL_HapticID haptic_id = SDL_SYS_HapticInstanceID(device_index);
            if (haptic_id == instance_id) {
                *driver_index = device_index;
                return true;
            }
        }
    }
    SDL_SetError("Haptic device %" SDL_PRIu32 " not found", instance_id);
    return false;
}
References SDL_PRIu32, SDL_SetError(), SDL_SYS_HapticInstanceID(), and SDL_SYS_NumHaptics().
Referenced by SDL_GetHapticNameForID(), and SDL_OpenHaptic().
SDL_GetHapticName()
const char * SDL_GetHapticName (SDL_Haptic * haptic)
Get the implementation dependent name of a haptic device.
Parameters
haptic the SDL_Haptic obtained from SDL_OpenJoystick().
Returns
the name of the selected haptic device. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticNameForID
{
    CHECK_HAPTIC_MAGIC(haptic, NULL);
    return SDL_GetPersistentString(haptic->name);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::name, NULL, and SDL_GetPersistentString().
SDL_GetHapticNameForID()
const char * SDL_GetHapticNameForID (SDL_HapticID instance_id)
Get the implementation dependent name of a haptic device.
This can be called before any haptic devices are opened.
Parameters
instance_id the haptic device instance ID.
Returns
the name of the selected haptic device. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticName
SDL_OpenHaptic
{
    int device_index;
    const char *name = NULL;
    if (SDL_GetHapticIndex(instance_id, &device_index)) {
        name = SDL_GetPersistentString(SDL_SYS_HapticName(device_index));
    }
    return name;
}
References NULL, SDL_GetHapticIndex(), SDL_GetPersistentString(), and SDL_SYS_HapticName().
SDL_GetHaptics()
SDL_HapticID * SDL_GetHaptics (int * count)
Get a list of currently connected haptic devices.
Parameters
count a pointer filled in with the number of haptic devices returned, may be NULL.
Returns
a 0 terminated array of haptic device instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHaptic
{
    int device_index;
    int haptic_index = 0, num_haptics = 0;
    SDL_HapticID *haptics;
    num_haptics = SDL_SYS_NumHaptics();
    haptics = (SDL_HapticID *)SDL_malloc((num_haptics + 1) * sizeof(*haptics));
    if (haptics) {
        if (count) {
            *count = num_haptics;
        }
        for (device_index = 0; device_index < num_haptics; ++device_index) {
            haptics[haptic_index] = SDL_SYS_HapticInstanceID(device_index);
            SDL_assert(haptics[haptic_index] > 0);
            ++haptic_index;
        }
        haptics[haptic_index] = 0;
    } else {
        if (count) {
            *count = 0;
        }
    }
    return haptics;
}
References count, SDL_assert, SDL_malloc(), SDL_SYS_HapticInstanceID(), and SDL_SYS_NumHaptics().
SDL_GetMaxHapticEffects()
int SDL_GetMaxHapticEffects (SDL_Haptic * haptic)
Get the number of effects a haptic device can store.
On some platforms this isn't fully supported, and therefore is an approximation. Always check to see if your created effect was actually created and do not rely solely on SDL_GetMaxHapticEffects().
Parameters
haptic the SDL_Haptic device to query.
Returns
the number of effects the haptic device can store or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMaxHapticEffectsPlaying
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, -1);
    return haptic->neffects;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::neffects.
SDL_GetMaxHapticEffectsPlaying()
int SDL_GetMaxHapticEffectsPlaying (SDL_Haptic * haptic)
Get the number of effects a haptic device can play at the same time.
This is not supported on all platforms, but will always return a value.
Parameters
haptic the SDL_Haptic device to query maximum playing effects.
Returns
the number of effects the haptic device can play at the same time or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMaxHapticEffects
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, -1);
    return haptic->nplaying;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::nplaying.
SDL_GetNumHapticAxes()
int SDL_GetNumHapticAxes (SDL_Haptic * haptic)
Get the number of haptic axes the device has.
The number of haptic axes might be useful if working with the SDL_HapticDirection effect.
Parameters
haptic the SDL_Haptic device to query.
Returns
the number of axes on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_HAPTIC_MAGIC(haptic, -1);
    return haptic->naxes;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::naxes.
SDL_Haptic_Get_Naxes()
int SDL_Haptic_Get_Naxes (Uint16 vid, Uint16 pid) static
{
    int num_entries = 0, index = 0, naxes = -1;
    SDL_Haptic_VIDPID_Naxes *naxes_list = NULL;
    SDL_Haptic_Load_Axes_List(&naxes_list, &num_entries);
    if (!num_entries || !naxes_list)
        return -1;
    // Perform "wildcard" pass
    index = SDL_Haptic_Naxes_List_Index(naxes_list, num_entries, 0xffff, 0xffff);
    if (index >= 0)
        naxes = naxes_list[index].naxes;
    index = SDL_Haptic_Naxes_List_Index(naxes_list, num_entries, vid, pid);
    if (index >= 0)
        naxes = naxes_list[index].naxes;
    SDL_free(naxes_list);
    return naxes;
}
References SDL_Haptic_VIDPID_Naxes::naxes, NULL, SDL_free(), SDL_Haptic_Load_Axes_List(), and SDL_Haptic_Naxes_List_Index().
Referenced by SDL_OpenHapticFromJoystick().
SDL_Haptic_Load_Axes_List()
void SDL_Haptic_Load_Axes_List (SDL_Haptic_VIDPID_Naxes ** entries, int * num_entries) static
{
    SDL_Haptic_VIDPID_Naxes entry;
    const char *spot;
    int length = 0;
    spot = SDL_GetHint(SDL_HINT_JOYSTICK_HAPTIC_AXES);
    if (!spot)
        return;
    while (SDL_sscanf(spot, "0x%hx/0x%hx/%hu%n", &entry.vid, &entry.pid, &entry.naxes, &length) == 3) {
        SDL_assert(length > 0);
        spot += length;
        length = 0;
        if ((*num_entries % 8) == 0) {
            int new_max = *num_entries + 8;
            SDL_Haptic_VIDPID_Naxes *new_entries =
                (SDL_Haptic_VIDPID_Naxes *)SDL_realloc(*entries, new_max * sizeof(**entries));
            // Out of memory, go with what we have already
            if (!new_entries)
                break;
            *entries = new_entries;
        }
        (*entries)[(*num_entries)++] = entry;
        if (spot[0] == ',')
            spot++;
    }
}
References SDL_Haptic_VIDPID_Naxes::naxes, SDL_Haptic_VIDPID_Naxes::pid, SDL_assert, SDL_GetHint(), SDL_HINT_JOYSTICK_HAPTIC_AXES, SDL_realloc(), SDL_sscanf(), and SDL_Haptic_VIDPID_Naxes::vid.
Referenced by SDL_Haptic_Get_Naxes().
SDL_Haptic_Naxes_List_Index()
int SDL_Haptic_Naxes_List_Index (struct SDL_Haptic_VIDPID_Naxes * entries, int num_entries, Uint16 vid, Uint16 pid) static
{
    if (!entries)
        return -1;
    int i;
    for (i = 0; i < num_entries; ++i) {
        if (entries[i].vid == vid && entries[i].pid == pid)
            return i;
    }
    return -1;
}
Referenced by SDL_Haptic_Get_Naxes().
SDL_HapticEffectSupported()
bool SDL_HapticEffectSupported (SDL_Haptic * haptic, const SDL_HapticEffect * effect)
Check to see if an effect is supported by a haptic device.
Parameters
haptic the SDL_Haptic device to query.
effect the desired effect to query.
Returns
true if the effect is supported or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateHapticEffect
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!effect) {
        return false;
    }
    if ((haptic->supported & effect->type) != 0) {
        return true;
    }
    return false;
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::supported, and SDL_HapticEffect::type.
Referenced by SDL_CreateHapticEffect().
SDL_HapticRumbleSupported()
bool SDL_HapticRumbleSupported (SDL_Haptic * haptic)
Check whether rumble is supported on a haptic device.
Parameters
haptic haptic device to check for rumble support.
Returns
true if the effect is supported or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_InitHapticRumble
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    // Most things can use SINE, but XInput only has LEFTRIGHT.
    return (haptic->supported & (SDL_HAPTIC_SINE | SDL_HAPTIC_LEFTRIGHT)) != 0;
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_LEFTRIGHT, SDL_HAPTIC_SINE, and SDL_Haptic::supported.
SDL_InitHapticRumble()
bool SDL_InitHapticRumble (SDL_Haptic * haptic)
Initialize a haptic device for simple rumble playback.
Parameters
haptic the haptic device to initialize for simple rumble playback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_PlayHapticRumble
SDL_StopHapticRumble
SDL_HapticRumbleSupported
{
    SDL_HapticEffect *efx = &haptic->rumble_effect;
    CHECK_HAPTIC_MAGIC(haptic, false);
    // Already allocated.
    if (haptic->rumble_id >= 0) {
        return true;
    }
    SDL_zerop(efx);
    if (haptic->supported & SDL_HAPTIC_SINE) {
        efx->type = SDL_HAPTIC_SINE;
        efx->periodic.direction.type = SDL_HAPTIC_CARTESIAN;
        efx->periodic.period = 1000;
        efx->periodic.magnitude = 0x4000;
        efx->periodic.length = 5000;
        efx->periodic.attack_length = 0;
        efx->periodic.fade_length = 0;
    } else if (haptic->supported & SDL_HAPTIC_LEFTRIGHT) { // XInput?
        efx->type = SDL_HAPTIC_LEFTRIGHT;
        efx->leftright.length = 5000;
        efx->leftright.large_magnitude = 0x4000;
        efx->leftright.small_magnitude = 0x4000;
    } else {
        return SDL_SetError("Device doesn't support rumble");
    }
    haptic->rumble_id = SDL_CreateHapticEffect(haptic, &haptic->rumble_effect);
    if (haptic->rumble_id >= 0) {
        return true;
    }
    return false;
}
References SDL_HapticPeriodic::attack_length, CHECK_HAPTIC_MAGIC, SDL_HapticPeriodic::direction, SDL_HapticPeriodic::fade_length, SDL_HapticLeftRight::large_magnitude, SDL_HapticEffect::leftright, SDL_HapticLeftRight::length, SDL_HapticPeriodic::length, SDL_HapticPeriodic::magnitude, SDL_HapticPeriodic::period, SDL_HapticEffect::periodic, SDL_Haptic::rumble_effect, SDL_Haptic::rumble_id, SDL_CreateHapticEffect(), SDL_HAPTIC_CARTESIAN, SDL_HAPTIC_LEFTRIGHT, SDL_HAPTIC_SINE, SDL_SetError(), SDL_zerop, SDL_HapticLeftRight::small_magnitude, SDL_Haptic::supported, SDL_HapticDirection::type, and SDL_HapticEffect::type.
SDL_InitHaptics()
bool SDL_InitHaptics (void)
{
    if (!SDL_SYS_HapticInit()) {
        return false;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (!SDL_HIDAPI_HapticInit()) {
        SDL_SYS_HapticQuit();
        return false;
    }
    #endif
    return true;
}
References SDL_HIDAPI_HapticInit(), SDL_SYS_HapticInit(), and SDL_SYS_HapticQuit().
Referenced by SDL_InitSubSystem().
SDL_IsJoystickHaptic()
bool SDL_IsJoystickHaptic (SDL_Joystick * joystick)
Query if a joystick has haptic features.
Parameters
joystick the SDL_Joystick to test for haptic capabilities.
Returns
true if the joystick is haptic or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHapticFromJoystick
{
    bool result = false;
    SDL_LockJoysticks();
    {
        // Must be a valid joystick
        if (SDL_IsJoystickValid(joystick) &&
            !SDL_IsGamepad(SDL_GetJoystickID(joystick))) {
            #ifdef SDL_JOYSTICK_HIDAPI
            result = SDL_SYS_JoystickIsHaptic(joystick) || SDL_HIDAPI_JoystickIsHaptic(joystick);
            #else
            result = SDL_SYS_JoystickIsHaptic(joystick);
            #endif
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetJoystickID(), SDL_HIDAPI_JoystickIsHaptic(), SDL_IsGamepad(), SDL_IsJoystickValid(), SDL_LockJoysticks(), SDL_SYS_JoystickIsHaptic(), and SDL_UnlockJoysticks().
Referenced by SDL_OpenHapticFromJoystick().
SDL_IsMouseHaptic()
bool SDL_IsMouseHaptic (void)
Query whether or not the current mouse has haptic capabilities.
Returns
true if the mouse is haptic or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHapticFromMouse
{
    if (SDL_SYS_HapticMouse() < 0) {
        return false;
    }
    return true;
}
References SDL_SYS_HapticMouse().
SDL_OpenHaptic()
SDL_Haptic * SDL_OpenHaptic (SDL_HapticID instance_id)
Open a haptic device for use.
The index passed as an argument refers to the N'th haptic device on this system.
When opening a haptic device, its gain will be set to maximum and autocenter will be disabled. To modify these values use SDL_SetHapticGain() and SDL_SetHapticAutocenter().
Parameters
instance_id the haptic device instance ID.
Returns
the device identifier or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseHaptic
SDL_GetHaptics
SDL_OpenHapticFromJoystick
SDL_OpenHapticFromMouse
SDL_SetHapticAutocenter
SDL_SetHapticGain
{
    SDL_Haptic *haptic;
    SDL_Haptic *hapticlist;
    const char *name;
    int device_index = 0;
    if (!SDL_GetHapticIndex(instance_id, &device_index)) {
        return NULL;
    }
    hapticlist = SDL_haptics;
    /* If the haptic device is already open, return it
     * it is important that we have a single haptic device for each instance id
     */
    while (hapticlist) {
        if (instance_id == hapticlist->instance_id) {
            haptic = hapticlist;
            ++haptic->ref_count;
            return haptic;
        }
        hapticlist = hapticlist->next;
    }
    // Create the haptic device
    haptic = (SDL_Haptic *)SDL_calloc(1, sizeof(*haptic));
    if (!haptic) {
        return NULL;
    }
    // Initialize the haptic device
    haptic->instance_id = instance_id;
    haptic->rumble_id = -1;
    if (!SDL_SYS_HapticOpen(haptic)) {
        SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, false);
        SDL_free(haptic);
        return NULL;
    }
    if (!haptic->name) {
        name = SDL_SYS_HapticName(device_index);
        if (name) {
            haptic->name = SDL_strdup(name);
        }
    }
    // Add haptic to list
    ++haptic->ref_count;
    // Link the haptic in the list
    haptic->next = SDL_haptics;
    SDL_haptics = haptic;
    SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, true);
    // Disable autocenter and set gain to max.
    if (haptic->supported & SDL_HAPTIC_GAIN) {
        SDL_SetHapticGain(haptic, 100);
    }
    if (haptic->supported & SDL_HAPTIC_AUTOCENTER) {
        SDL_SetHapticAutocenter(haptic, 0);
    }
    return haptic;
}
References SDL_Haptic::instance_id, SDL_Haptic::name, SDL_Haptic::next, NULL, SDL_Haptic::ref_count, SDL_Haptic::rumble_id, SDL_calloc(), SDL_free(), SDL_GetHapticIndex(), SDL_HAPTIC_AUTOCENTER, SDL_HAPTIC_GAIN, SDL_haptics, SDL_OBJECT_TYPE_HAPTIC, SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_SetObjectValid(), SDL_strdup(), SDL_SYS_HapticName(), SDL_SYS_HapticOpen(), and SDL_Haptic::supported.
Referenced by SDL_OpenHapticFromMouse().
SDL_OpenHapticFromJoystick()
SDL_Haptic * SDL_OpenHapticFromJoystick (SDL_Joystick * joystick)
Open a haptic device for use from a joystick device.
You must still close the haptic device separately. It will not be closed with the joystick.
When opened from a joystick you should first close the haptic device before closing the joystick device. If not, on some implementations the haptic device will also get unallocated and you'll be unable to use force feedback on that device.
Parameters
joystick the SDL_Joystick to create a haptic device from.
Returns
a valid haptic device identifier on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseHaptic
SDL_IsJoystickHaptic
{
    SDL_Haptic *haptic;
    SDL_Haptic *hapticlist;
    SDL_LockJoysticks();
    {
        // Joystick must be valid and haptic
        if (!SDL_IsJoystickHaptic(joystick)) {
            SDL_SetError("Haptic: Joystick isn't a haptic device.");
            SDL_UnlockJoysticks();
            return NULL;
        }
        hapticlist = SDL_haptics;
        // Check to see if joystick's haptic is already open
        while (hapticlist) {
            #ifdef SDL_JOYSTICK_HIDAPI
            if (SDL_SYS_JoystickSameHaptic(hapticlist, joystick) || SDL_HIDAPI_JoystickSameHaptic(hapticlist, joystick)) {
            #else
            if (SDL_SYS_JoystickSameHaptic(hapticlist, joystick)) {
            #endif
                haptic = hapticlist;
                ++haptic->ref_count;
                SDL_UnlockJoysticks();
                return haptic;
            }
            hapticlist = hapticlist->next;
        }
        // Create the haptic device
        haptic = (SDL_Haptic *)SDL_calloc(1, sizeof(*haptic));
        if (!haptic) {
            SDL_UnlockJoysticks();
            return NULL;
        }
        /* Initialize the haptic device
         * This function should fill in the instance ID and name.
         */
        SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, true);
        haptic->rumble_id = -1;
        #ifdef SDL_JOYSTICK_HIDAPI
        if (SDL_HIDAPI_JoystickIsHaptic(joystick)) {
            if (!SDL_HIDAPI_HapticOpenFromJoystick(haptic, joystick)) {
                SDL_SetError("Haptic: SDL_HIDAPI_HapticOpenFromJoystick failed.");
                SDL_free(haptic);
                SDL_UnlockJoysticks();
                return NULL;
            }
        } else
        #endif
        if (!SDL_SYS_HapticOpenFromJoystick(haptic, joystick)) {
            SDL_SetError("Haptic: SDL_SYS_HapticOpenFromJoystick failed.");
            SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, false);
            SDL_free(haptic);
            SDL_UnlockJoysticks();
            return NULL;
        }
        SDL_assert(haptic->instance_id != 0);
    }
    SDL_UnlockJoysticks();
    // Check if custom number of haptic axes was defined
    Uint16 vid = SDL_GetJoystickVendor(joystick);
    Uint16 pid = SDL_GetJoystickProduct(joystick);
    int general_axes = SDL_GetNumJoystickAxes(joystick);
    int naxes = SDL_Haptic_Get_Naxes(vid, pid);
    if (naxes > 0)
        haptic->naxes = naxes;
    // Limit to the actual number of axes found on the device
    if (general_axes >= 0 && naxes > general_axes)
        haptic->naxes = general_axes;
    // Add haptic to list
    ++haptic->ref_count;
    // Link the haptic in the list
    haptic->next = SDL_haptics;
    SDL_haptics = haptic;
    SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, true);
    // Disable autocenter and set gain to max.
    if (haptic->supported & SDL_HAPTIC_GAIN) {
        SDL_SetHapticGain(haptic, 100);
    }
    if (haptic->supported & SDL_HAPTIC_AUTOCENTER) {
        SDL_SetHapticAutocenter(haptic, 0);
    }
    return haptic;
}
References SDL_Haptic::instance_id, SDL_Haptic::naxes, SDL_Haptic::next, NULL, SDL_Haptic::ref_count, SDL_Haptic::rumble_id, SDL_assert, SDL_calloc(), SDL_free(), SDL_GetJoystickProduct(), SDL_GetJoystickVendor(), SDL_GetNumJoystickAxes(), SDL_HAPTIC_AUTOCENTER, SDL_HAPTIC_GAIN, SDL_Haptic_Get_Naxes(), SDL_haptics, SDL_HIDAPI_HapticOpenFromJoystick(), SDL_HIDAPI_JoystickIsHaptic(), SDL_HIDAPI_JoystickSameHaptic(), SDL_IsJoystickHaptic(), SDL_LockJoysticks(), SDL_OBJECT_TYPE_HAPTIC, SDL_SetError(), SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_SetObjectValid(), SDL_SYS_HapticOpenFromJoystick(), SDL_SYS_JoystickSameHaptic(), SDL_UnlockJoysticks(), and SDL_Haptic::supported.
SDL_OpenHapticFromMouse()
SDL_Haptic * SDL_OpenHapticFromMouse (void)
Try to open a haptic device from the current mouse.
Returns
the haptic device identifier or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseHaptic
SDL_IsMouseHaptic
{
    int device_index;
    device_index = SDL_SYS_HapticMouse();
    if (device_index < 0) {
        SDL_SetError("Haptic: Mouse isn't a haptic device.");
        return NULL;
    }
    return SDL_OpenHaptic(device_index);
}
References NULL, SDL_OpenHaptic(), SDL_SetError(), and SDL_SYS_HapticMouse().
SDL_PauseHaptic()
bool SDL_PauseHaptic (SDL_Haptic * haptic)
Pause a haptic device.
Device must support the SDL_HAPTIC_PAUSE feature. Call SDL_ResumeHaptic() to resume playback.
Do not modify the effects nor add new ones while the device is paused. That can cause all sorts of weird errors.
Parameters
haptic the SDL_Haptic device to pause.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResumeHaptic
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_PAUSE)) {
        return SDL_SetError("Haptic: Device does not support setting pausing.");
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticPause(haptic);
    }
    #endif
    return SDL_SYS_HapticPause(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_PAUSE, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticPause(), SDL_SetError(), SDL_SYS_HapticPause(), and SDL_Haptic::supported.
SDL_PlayHapticRumble()
bool SDL_PlayHapticRumble (SDL_Haptic * haptic, float strength, Uint32 length)
Run a simple rumble effect on a haptic device.
Parameters
haptic the haptic device to play the rumble effect on.
strength strength of the rumble to play as a 0-1 float value.
length length of the rumble to play in milliseconds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_InitHapticRumble
SDL_StopHapticRumble
{
    SDL_HapticEffect *efx;
    Sint16 magnitude;
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (haptic->rumble_id < 0) {
        return SDL_SetError("Haptic: Rumble effect not initialized on haptic device");
    }
    // Clamp strength.
    if (strength > 1.0f) {
        strength = 1.0f;
    } else if (strength < 0.0f) {
        strength = 0.0f;
    }
    magnitude = (Sint16)(32767.0f * strength);
    efx = &haptic->rumble_effect;
    if (efx->type == SDL_HAPTIC_SINE) {
        efx->periodic.magnitude = magnitude;
        efx->periodic.length = length;
    } else if (efx->type == SDL_HAPTIC_LEFTRIGHT) {
        efx->leftright.small_magnitude = efx->leftright.large_magnitude = magnitude;
        efx->leftright.length = length;
    } else {
        SDL_assert(!"This should have been caught elsewhere");
    }
    if (!SDL_UpdateHapticEffect(haptic, haptic->rumble_id, &haptic->rumble_effect)) {
        return false;
    }
    return SDL_RunHapticEffect(haptic, haptic->rumble_id, 1);
}
References CHECK_HAPTIC_MAGIC, SDL_HapticLeftRight::large_magnitude, SDL_HapticEffect::leftright, SDL_HapticLeftRight::length, SDL_HapticPeriodic::length, SDL_HapticPeriodic::magnitude, SDL_HapticEffect::periodic, SDL_Haptic::rumble_effect, SDL_Haptic::rumble_id, SDL_assert, SDL_HAPTIC_LEFTRIGHT, SDL_HAPTIC_SINE, SDL_RunHapticEffect(), SDL_SetError(), SDL_UpdateHapticEffect(), SDL_HapticLeftRight::small_magnitude, and SDL_HapticEffect::type.
SDL_QuitHaptics()
void SDL_QuitHaptics (void)
{
    while (SDL_haptics) {
        SDL_CloseHaptic(SDL_haptics);
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    SDL_HIDAPI_HapticQuit();
    #endif
    SDL_SYS_HapticQuit();
}
References SDL_CloseHaptic(), SDL_haptics, SDL_HIDAPI_HapticQuit(), and SDL_SYS_HapticQuit().
Referenced by SDL_QuitSubSystem().
SDL_ResumeHaptic()
bool SDL_ResumeHaptic (SDL_Haptic * haptic)
Resume a haptic device.
Call to unpause after SDL_PauseHaptic().
Parameters
haptic the SDL_Haptic device to unpause.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseHaptic
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_PAUSE)) {
        return true; // Not going to be paused, so we pretend it's unpaused.
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticResume(haptic);
    }
    #endif
    return SDL_SYS_HapticResume(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_PAUSE, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticResume(), SDL_SYS_HapticResume(), and SDL_Haptic::supported.
SDL_RunHapticEffect()
bool SDL_RunHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect, Uint32 iterations)
Run the haptic effect on its associated haptic device.
To repeat the effect over and over indefinitely, set iterations to SDL_HAPTIC_INFINITY. (Repeats the envelope - attack and fade.) To make one instance of the effect last indefinitely (so the effect does not fade), set the effect's length in its structure/union to SDL_HAPTIC_INFINITY instead.
Parameters
haptic the SDL_Haptic device to run the effect on.
effect the ID of the haptic effect to run.
iterations the number of iterations to run the effect; use SDL_HAPTIC_INFINITY to repeat forever.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticEffectStatus
SDL_StopHapticEffect
SDL_StopHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticRunEffect(haptic, effect, iterations);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    // Run the effect
    if (!SDL_SYS_HapticRunEffect(haptic, &haptic->effects[effect], iterations)) {
        return false;
    }
    return true;
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticRunEffect(), SDL_SYS_HapticRunEffect(), and ValidEffect().
Referenced by SDL_PlayHapticRumble().
SDL_SetHapticAutocenter()
bool SDL_SetHapticAutocenter (SDL_Haptic * haptic, int autocenter)
Set the global autocenter of the device.
Autocenter should be between 0 and 100. Setting it to 0 will disable autocentering.
Device must support the SDL_HAPTIC_AUTOCENTER feature.
Parameters
haptic the SDL_Haptic device to set autocentering on.
autocenter value to set autocenter to (0-100).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_AUTOCENTER)) {
        return SDL_SetError("Haptic: Device does not support setting autocenter.");
    }
    if ((autocenter < 0) || (autocenter > 100)) {
        return SDL_SetError("Haptic: Autocenter must be between 0 and 100.");
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticSetAutocenter(haptic, autocenter);
    }
    #endif
    return SDL_SYS_HapticSetAutocenter(haptic, autocenter);
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_AUTOCENTER, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticSetAutocenter(), SDL_SetError(), SDL_SYS_HapticSetAutocenter(), and SDL_Haptic::supported.
Referenced by SDL_OpenHaptic(), and SDL_OpenHapticFromJoystick().
SDL_SetHapticGain()
bool SDL_SetHapticGain (SDL_Haptic * haptic, int gain)
Set the global gain of the specified haptic device.
Device must support the SDL_HAPTIC_GAIN feature.
The user may specify the maximum gain by setting the environment variable SDL_HAPTIC_GAIN_MAX which should be between 0 and 100. All calls to SDL_SetHapticGain() will scale linearly using SDL_HAPTIC_GAIN_MAX as the maximum.
Parameters
haptic the SDL_Haptic device to set the gain on.
gain value to set the gain to, should be between 0 and 100 (0 - 100).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticFeatures
{
    const char *env;
    int real_gain, max_gain;
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_GAIN)) {
        return SDL_SetError("Haptic: Device does not support setting gain.");
    }
    if ((gain < 0) || (gain > 100)) {
        return SDL_SetError("Haptic: Gain must be between 0 and 100.");
    }
    // The user can use an environment variable to override the max gain.
    env = SDL_getenv("SDL_HAPTIC_GAIN_MAX");
    if (env) {
        max_gain = SDL_atoi(env);
        // Check for sanity.
        if (max_gain < 0) {
            max_gain = 0;
        } else if (max_gain > 100) {
            max_gain = 100;
        }
        // We'll scale it linearly with SDL_HAPTIC_GAIN_MAX
        real_gain = (gain * max_gain) / 100;
    } else {
        real_gain = gain;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticSetGain(haptic, real_gain);
    }
    #endif
    return SDL_SYS_HapticSetGain(haptic, real_gain);
}
References CHECK_HAPTIC_MAGIC, SDL_atoi(), SDL_getenv(), SDL_HAPTIC_GAIN, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticSetGain(), SDL_SetError(), SDL_SYS_HapticSetGain(), and SDL_Haptic::supported.
Referenced by SDL_OpenHaptic(), and SDL_OpenHapticFromJoystick().
SDL_StopHapticEffect()
bool SDL_StopHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect)
Stop the haptic effect on its associated haptic device.
Parameters
haptic the SDL_Haptic device to stop the effect on.
effect the ID of the haptic effect to stop.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_RunHapticEffect
SDL_StopHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticStopEffect(haptic, effect);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    // Stop the effect
    if (!SDL_SYS_HapticStopEffect(haptic, &haptic->effects[effect])) {
        return false;
    }
    return true;
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticStopEffect(), SDL_SYS_HapticStopEffect(), and ValidEffect().
Referenced by SDL_StopHapticRumble().
SDL_StopHapticEffects()
bool SDL_StopHapticEffects (SDL_Haptic * haptic)
Stop all the currently playing effects on a haptic device.
Parameters
haptic the SDL_Haptic device to stop.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_RunHapticEffect
SDL_StopHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticStopAll(haptic);
    }
    #endif
    return SDL_SYS_HapticStopAll(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticStopAll(), and SDL_SYS_HapticStopAll().
SDL_StopHapticRumble()
bool SDL_StopHapticRumble (SDL_Haptic * haptic)
Stop the simple rumble on a haptic device.
Parameters
haptic the haptic device to stop the rumble effect on.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_PlayHapticRumble
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (haptic->rumble_id < 0) {
        return SDL_SetError("Haptic: Rumble effect not initialized on haptic device");
    }
    return SDL_StopHapticEffect(haptic, haptic->rumble_id);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::rumble_id, SDL_SetError(), and SDL_StopHapticEffect().
SDL_UpdateHapticEffect()
bool SDL_UpdateHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect, const SDL_HapticEffect * data)
Update the properties of an effect.
Can be used dynamically, although behavior when dynamically changing direction may be strange. Specifically the effect may re-upload itself and start playing from the start. You also cannot change the type either when running SDL_UpdateHapticEffect().
Parameters
haptic the SDL_Haptic device that has the effect.
effect the identifier of the effect to update.
data an SDL_HapticEffect structure containing the new effect properties to use.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateHapticEffect
SDL_RunHapticEffect
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticUpdateEffect(haptic, effect, data);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    if (!data) {
        return SDL_InvalidParamError("data");
    }
    // Can't change type dynamically.
    if (data->type != haptic->effects[effect].effect.type) {
        return SDL_SetError("Haptic: Updating effect type is illegal.");
    }
    // Updates the effect
    if (!SDL_SYS_HapticUpdateEffect(haptic, &haptic->effects[effect], data)) {
        return false;
    }
    SDL_memcpy(&haptic->effects[effect].effect, data,
               sizeof(SDL_HapticEffect));
    return true;
}
References CHECK_HAPTIC_MAGIC, haptic_effect::effect, SDL_Haptic::effects, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticUpdateEffect(), SDL_InvalidParamError, SDL_memcpy, SDL_SetError(), SDL_SYS_HapticUpdateEffect(), SDL_HapticEffect::type, and ValidEffect().
Referenced by SDL_PlayHapticRumble().
ValidEffect()
bool ValidEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect) static
{
    if ((effect < 0) || (effect >= haptic->neffects)) {
        SDL_SetError("Haptic: Invalid effect identifier.");
        return false;
    }
    return true;
}
References SDL_Haptic::neffects, and SDL_SetError().
Referenced by SDL_DestroyHapticEffect(), SDL_GetHapticEffectStatus(), SDL_RunHapticEffect(), SDL_StopHapticEffect(), and SDL_UpdateHapticEffect().
Variable Documentation
SDL_haptics
SDL_Haptic* SDL_haptics = NULL static
Referenced by SDL_CloseHaptic(), SDL_GetHapticFromID(), SDL_OpenHaptic(), SDL_OpenHapticFromJoystick(), and SDL_QuitHaptics().