SDL3: SDL-main/src/joystick/SDL_steam_virtual_gamepad.c File Reference
SDL_steam_virtual_gamepad.c File Reference
#include "SDL_internal.h"
#include "SDL_joystick_c.h"
#include "SDL_steam_virtual_gamepad.h"
#include <sys/types.h>
#include <sys/stat.h>
Macros
#define SDL_HINT_STEAM_VIRTUAL_GAMEPAD_INFO_FILE "SteamVirtualGamepadInfo"
Functions
static void AddVirtualGamepadInfo (int slot, SDL_SteamVirtualGamepadInfo *info)
static Uint64 GetFileModificationTime (const char *file)
static void SDL_FreeSteamVirtualGamepadInfo (void)
const SDL_SteamVirtualGamepadInfo * SDL_GetSteamVirtualGamepadInfo (int slot)
static char *SDL_steam_virtual_gamepad_info_file SDL_GUARDED_BY (SDL_joystick_lock) = NULL
void SDL_InitSteamVirtualGamepadInfo (void)
void SDL_QuitSteamVirtualGamepadInfo (void)
bool SDL_SteamVirtualGamepadEnabled (void)
bool SDL_UpdateSteamVirtualGamepadInfo (void)
Macro Definition Documentation
SDL_HINT_STEAM_VIRTUAL_GAMEPAD_INFO_FILE
#define SDL_HINT_STEAM_VIRTUAL_GAMEPAD_INFO_FILE "SteamVirtualGamepadInfo"
Referenced by SDL_InitSteamVirtualGamepadInfo().
Function Documentation
AddVirtualGamepadInfo()
void AddVirtualGamepadInfo (int slot, SDL_SteamVirtualGamepadInfo * info) static
{
    SDL_SteamVirtualGamepadInfo *new_info;
    SDL_AssertJoysticksLocked();
    if (slot < 0) {
        return;
    }
    if (slot >= SDL_steam_virtual_gamepad_info_count) {
        SDL_SteamVirtualGamepadInfo **slots = (SDL_SteamVirtualGamepadInfo **)SDL_realloc(SDL_steam_virtual_gamepad_info, (slot + 1)*sizeof(*SDL_steam_virtual_gamepad_info));
        if (!slots) {
            return;
        }
        while (SDL_steam_virtual_gamepad_info_count <= slot) {
            slots[SDL_steam_virtual_gamepad_info_count++] = NULL;
        }
        SDL_steam_virtual_gamepad_info = slots;
    }
    if (SDL_steam_virtual_gamepad_info[slot]) {
        // We already have this slot info
        return;
    }
    new_info = (SDL_SteamVirtualGamepadInfo *)SDL_malloc(sizeof(*new_info));
    if (!new_info) {
        return;
    }
    SDL_copyp(new_info, info);
    SDL_steam_virtual_gamepad_info[slot] = new_info;
    SDL_zerop(info);
}
References NULL, SDL_AssertJoysticksLocked(), SDL_copyp, SDL_malloc(), SDL_realloc(), and SDL_zerop.
Referenced by SDL_UpdateSteamVirtualGamepadInfo().
GetFileModificationTime()
Uint64 GetFileModificationTime (const char * file) static
{
    Uint64 modification_time = 0;
#ifdef SDL_PLATFORM_WIN32
    WCHAR *wFile = WIN_UTF8ToStringW(file);
    if (wFile) {
        HANDLE hFile = CreateFileW(wFile, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
        if (hFile != INVALID_HANDLE_VALUE) {
            FILETIME last_write_time;
            if (GetFileTime(hFile, NULL, NULL, &last_write_time)) {
                modification_time = last_write_time.dwHighDateTime;
                modification_time <<= 32;
                modification_time |= last_write_time.dwLowDateTime;
            }
            CloseHandle(hFile);
        }
        SDL_free(wFile);
    }
#else
    struct stat sb;
    if (stat(file, &sb) == 0) {
        modification_time = (Uint64)sb.st_mtime;
    }
#endif
    return modification_time;
}
References NULL, SDL_free(), and WIN_UTF8ToStringW.
Referenced by SDL_UpdateSteamVirtualGamepadInfo().
SDL_FreeSteamVirtualGamepadInfo()
void SDL_FreeSteamVirtualGamepadInfo (void) static
{
    int i;
    SDL_AssertJoysticksLocked();
    for (i = 0; i < SDL_steam_virtual_gamepad_info_count; ++i) {
        SDL_SteamVirtualGamepadInfo *entry = SDL_steam_virtual_gamepad_info[i];
        if (entry) {
            SDL_free(entry->name);
            SDL_free(entry);
        }
    }
    SDL_free(SDL_steam_virtual_gamepad_info);
    SDL_steam_virtual_gamepad_info = NULL;
    SDL_steam_virtual_gamepad_info_count = 0;
}
References SDL_SteamVirtualGamepadInfo::name, NULL, SDL_AssertJoysticksLocked(), and SDL_free().
Referenced by SDL_QuitSteamVirtualGamepadInfo(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_GetSteamVirtualGamepadInfo()
const SDL_SteamVirtualGamepadInfo * SDL_GetSteamVirtualGamepadInfo (int slot)
{
    SDL_AssertJoysticksLocked();
    if (slot < 0 || slot >= SDL_steam_virtual_gamepad_info_count) {
        return NULL;
    }
    return SDL_steam_virtual_gamepad_info[slot];
}
References NULL, and SDL_AssertJoysticksLocked().
Referenced by SDL_GetJoystickVirtualGamepadInfoForID().
SDL_GUARDED_BY()
int SDL_steam_virtual_gamepad_info_count SDL_GUARDED_BY (SDL_joystick_lock) = NULL static
References NULL, and SDL_joystick_lock.
SDL_InitSteamVirtualGamepadInfo()
void SDL_InitSteamVirtualGamepadInfo (void)
{
    const char *file;
    SDL_AssertJoysticksLocked();
    // The file isn't available inside the macOS sandbox
    if (SDL_GetSandbox() == SDL_SANDBOX_MACOS) {
        return;
    }
    file = SDL_GetHint(SDL_HINT_STEAM_VIRTUAL_GAMEPAD_INFO_FILE);
    if (file && *file) {
        SDL_steam_virtual_gamepad_info_file = SDL_strdup(file);
    }
    SDL_UpdateSteamVirtualGamepadInfo();
}
References SDL_AssertJoysticksLocked(), SDL_GetHint(), SDL_GetSandbox(), SDL_HINT_STEAM_VIRTUAL_GAMEPAD_INFO_FILE, SDL_SANDBOX_MACOS, SDL_strdup(), and SDL_UpdateSteamVirtualGamepadInfo().
Referenced by SDL_InitJoysticks().
SDL_QuitSteamVirtualGamepadInfo()
void SDL_QuitSteamVirtualGamepadInfo (void)
{
    SDL_AssertJoysticksLocked();
    if (SDL_steam_virtual_gamepad_info_file) {
        SDL_FreeSteamVirtualGamepadInfo();
        SDL_free(SDL_steam_virtual_gamepad_info_file);
        SDL_steam_virtual_gamepad_info_file = NULL;
    }
}
References NULL, SDL_AssertJoysticksLocked(), SDL_free(), and SDL_FreeSteamVirtualGamepadInfo().
Referenced by SDL_QuitJoysticks().
SDL_SteamVirtualGamepadEnabled()
bool SDL_SteamVirtualGamepadEnabled (void)
{
    SDL_AssertJoysticksLocked();
    return (SDL_steam_virtual_gamepad_info != NULL);
}
References NULL, and SDL_AssertJoysticksLocked().
Referenced by SDL_GetJoystickVirtualGamepadInfoForID().
SDL_UpdateSteamVirtualGamepadInfo()
bool SDL_UpdateSteamVirtualGamepadInfo (void)
{
    const int UPDATE_CHECK_INTERVAL_MS = 3000;
    Uint64 now;
    Uint64 mtime;
    char *data, *end, *next, *line, *value;
    size_t size;
    int slot, new_slot;
    SDL_SteamVirtualGamepadInfo info;
    SDL_AssertJoysticksLocked();
    if (!SDL_steam_virtual_gamepad_info_file) {
        return false;
    }
    now = SDL_GetTicks();
    if (SDL_steam_virtual_gamepad_info_check_time &&
        now < (SDL_steam_virtual_gamepad_info_check_time + UPDATE_CHECK_INTERVAL_MS)) {
        return false;
    }
    SDL_steam_virtual_gamepad_info_check_time = now;
    mtime = GetFileModificationTime(SDL_steam_virtual_gamepad_info_file);
    if (mtime == 0 || mtime == SDL_steam_virtual_gamepad_info_file_mtime) {
        return false;
    }
    data = (char *)SDL_LoadFile(SDL_steam_virtual_gamepad_info_file, &size);
    if (!data) {
        return false;
    }
    SDL_FreeSteamVirtualGamepadInfo();
    slot = -1;
    SDL_zero(info);
    for (next = data, end = data + size; next < end; ) {
        while (next < end && (*next == '\0' || *next == '\r' || *next == '\n')) {
            ++next;
        }
        line = next;
        while (next < end && (*next != '\r' && *next != '\n')) {
            ++next;
        }
        *next = '\0';
        if (SDL_sscanf(line, "[slot %d]", &new_slot) == 1) {
            if (slot >= 0) {
                AddVirtualGamepadInfo(slot, &info);
            }
            slot = new_slot;
        } else {
            value = SDL_strchr(line, '=');
            if (value) {
                *value++ = '\0';
                if (SDL_strcmp(line, "name") == 0) {
                    SDL_free(info.name);
                    info.name = SDL_strdup(value);
                } else if (SDL_strcmp(line, "VID") == 0) {
                    info.vendor_id = (Uint16)SDL_strtoul(value, NULL, 0);
                } else if (SDL_strcmp(line, "PID") == 0) {
                    info.product_id = (Uint16)SDL_strtoul(value, NULL, 0);
                } else if (SDL_strcmp(line, "type") == 0) {
                    info.type = SDL_GetGamepadTypeFromString(value);
                } else if (SDL_strcmp(line, "handle") == 0) {
                    info.handle = (Uint64)SDL_strtoull(value, NULL, 0);
                }
            }
        }
    }
    if (slot >= 0) {
        AddVirtualGamepadInfo(slot, &info);
    }
    SDL_free(info.name);
    SDL_free(data);
    SDL_steam_virtual_gamepad_info_file_mtime = mtime;
    return true;
}
References AddVirtualGamepadInfo(), GetFileModificationTime(), SDL_SteamVirtualGamepadInfo::handle, SDL_SteamVirtualGamepadInfo::name, NULL, SDL_SteamVirtualGamepadInfo::product_id, SDL_AssertJoysticksLocked(), SDL_free(), SDL_FreeSteamVirtualGamepadInfo(), SDL_GetGamepadTypeFromString(), SDL_GetTicks(), SDL_LoadFile(), SDL_sscanf(), SDL_strchr(), SDL_strcmp(), SDL_strdup(), SDL_strtoul(), SDL_strtoull(), SDL_zero, SDL_SteamVirtualGamepadInfo::type, and SDL_SteamVirtualGamepadInfo::vendor_id.
Referenced by SDL_InitSteamVirtualGamepadInfo(), and SDL_UpdateJoysticks().