SDL3: SDL-main/src/misc/windows/SDL_sysurl.c File Reference
SDL_sysurl.c File Reference
#include "SDL_internal.h"
#include "../SDL_sysurl.h"
#include "../../core/windows/SDL_windows.h"
#include <shellapi.h>
Functions
bool SDL_SYS_OpenURL (const char *url)
Function Documentation
SDL_SYS_OpenURL()
bool SDL_SYS_OpenURL (const char * url)
{
    WCHAR *wurl;
    HINSTANCE rc;
    // MSDN says for safety's sake, make sure COM is initialized.
    const HRESULT hr = WIN_CoInitialize();
    if (FAILED(hr)) {
        return WIN_SetErrorFromHRESULT("CoInitialize failed", hr);
    }
    wurl = WIN_UTF8ToStringW(url);
    if (!wurl) {
        WIN_CoUninitialize();
        return false;
    }
    // Success returns value greater than 32. Less is an error.
    rc = ShellExecuteW(NULL, L"open", wurl, NULL, NULL, SW_SHOWNORMAL);
    SDL_free(wurl);
    WIN_CoUninitialize();
    if (rc <= ((HINSTANCE)32)) {
        return WIN_SetError("Couldn't open given URL.");
    }
    return true;
}
References FAILED, NULL, SDL_free(), WIN_CoInitialize(), WIN_CoUninitialize(), WIN_SetError(), WIN_SetErrorFromHRESULT(), and WIN_UTF8ToStringW.