SDL3: SDL-main/src/SDL_assert.c File Reference
SDL_assert.c File Reference
#include "SDL_internal.h"
#include "SDL_assert_c.h"
#include "video/SDL_sysvideo.h"
Macros
#define ENDLINE "\n"
#define SDL_MAX_ASSERT_MESSAGE_STACK 256
Functions
static void debug_print (const char *fmt,...)
static SDL_NORETURN void SDL_AbortAssertion (void)
static void SDL_AddAssertionToReport (SDL_AssertData *data)
void SDL_AssertionsQuit (void)
SDL_NORETURN void SDL_ExitProcess (int exitcode)
static void SDL_GenerateAssertionReport (void)
SDL_AssertionHandler SDL_GetAssertionHandler (void **userdata)
const SDL_AssertData * SDL_GetAssertionReport (void)
SDL_AssertionHandler SDL_GetDefaultAssertionHandler (void)
static SDL_AssertState SDLCALL SDL_PromptAssertion (const SDL_AssertData *data, void *userdata)
static int SDL_RenderAssertMessage (char *buf, size_t buf_len, const SDL_AssertData *data)
SDL_AssertState SDL_ReportAssertion (SDL_AssertData *data, const char *func, const char *file, int line)
void SDL_ResetAssertionReport (void)
void SDL_SetAssertionHandler (SDL_AssertionHandler handler, void *userdata)
Variables
static SDL_AssertionHandler assertion_handler = SDL_PromptAssertion
static SDL_Mutex * assertion_mutex = NULL
static void * assertion_userdata = NULL
static SDL_AssertData * triggered_assertions = NULL
Macro Definition Documentation
ENDLINE
#define ENDLINE "\n"
Referenced by SDL_RenderAssertMessage().
SDL_MAX_ASSERT_MESSAGE_STACK
#define SDL_MAX_ASSERT_MESSAGE_STACK 256
Referenced by SDL_PromptAssertion().
Function Documentation
debug_print()
void debug_print (const char * fmt, ...) static
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(SDL_LOG_CATEGORY_ASSERT, SDL_LOG_PRIORITY_WARN, fmt, ap);
    va_end(ap);
}
References SDL_LOG_CATEGORY_ASSERT, SDL_LOG_PRIORITY_WARN, and SDL_LogMessageV().
Referenced by SDL_GenerateAssertionReport(), and SDL_PromptAssertion().
SDL_AbortAssertion()
SDL_NORETURN void SDL_AbortAssertion (void) static
{
    SDL_Quit();
    SDL_ExitProcess(42);
}
References SDL_ExitProcess(), SDL_NORETURN, and SDL_Quit().
Referenced by SDL_ReportAssertion().
SDL_AddAssertionToReport()
void SDL_AddAssertionToReport (SDL_AssertData * data) static
{
    /* (data) is always a static struct defined with the assert macros, so
       we don't have to worry about copying or allocating them. */
    data->trigger_count++;
    if (data->trigger_count == 1) { // not yet added?
        data->next = triggered_assertions;
        triggered_assertions = data;
    }
}
References triggered_assertions.
Referenced by SDL_ReportAssertion().
SDL_AssertionsQuit()
void SDL_AssertionsQuit (void)
{
#if SDL_ASSERT_LEVEL > 0
    SDL_GenerateAssertionReport();
#ifndef SDL_THREADS_DISABLED
    if (assertion_mutex) {
        SDL_DestroyMutex(assertion_mutex);
        assertion_mutex = NULL;
    }
#endif
#endif // SDL_ASSERT_LEVEL > 0
}
References assertion_mutex, NULL, SDL_DestroyMutex(), and SDL_GenerateAssertionReport().
Referenced by SDL_Quit().
SDL_ExitProcess()
SDL_NORETURN void SDL_ExitProcess (int exitcode) extern
{
#if defined(SDL_PLATFORM_WINDOWS)
    /* "if you do not know the state of all threads in your process, it is
       better to call TerminateProcess than ExitProcess"
       https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx */
    TerminateProcess(GetCurrentProcess(), exitcode);
    /* MingW doesn't have TerminateProcess marked as noreturn, so add an
       ExitProcess here that will never be reached but make MingW happy. */
    ExitProcess(exitcode);
#elif defined(SDL_PLATFORM_EMSCRIPTEN)
    emscripten_cancel_main_loop();   // this should "kill" the app.
    emscripten_force_exit(exitcode); // this should "kill" the app.
    exit(exitcode);
#elif defined(SDL_PLATFORM_HAIKU)  // Haiku has _Exit, but it's not marked noreturn.
    _exit(exitcode);
#elif defined(HAVE__EXIT) // Upper case _Exit()
    _Exit(exitcode);
#else
    _exit(exitcode);
#endif
}
References SDL_NORETURN.
Referenced by SDL_AbortAssertion(), and SDL_ReportAssertion().
SDL_GenerateAssertionReport()
void SDL_GenerateAssertionReport (void) static
{
    const SDL_AssertData *item = triggered_assertions;
    // only do this if the app hasn't assigned an assertion handler.
    if ((item) && (assertion_handler != SDL_PromptAssertion)) {
        debug_print("\n\nSDL assertion report.\n");
        debug_print("All SDL assertions between last init/quit:\n\n");
        while (item) {
            debug_print(
                "'%s'\n"
                "    * %s (%s:%d)\n"
                "    * triggered %u time%s.\n"
                "    * always ignore: %s.\n",
                item->condition, item->function, item->filename,
                item->linenum, item->trigger_count,
                (item->trigger_count == 1) ? "" : "s",
                item->always_ignore ? "yes" : "no");
            item = item->next;
        }
        debug_print("\n");
        SDL_ResetAssertionReport();
    }
}
References SDL_AssertData::always_ignore, assertion_handler, SDL_AssertData::condition, debug_print(), SDL_AssertData::filename, SDL_AssertData::function, SDL_AssertData::linenum, SDL_AssertData::next, SDL_PromptAssertion(), SDL_ResetAssertionReport(), SDL_AssertData::trigger_count, and triggered_assertions.
Referenced by SDL_AssertionsQuit().
SDL_GetAssertionHandler()
SDL_AssertionHandler SDL_GetAssertionHandler (void ** puserdata)
Get the current assertion handler.
This returns the function pointer that is called when an assertion is triggered. This is either the value last passed to SDL_SetAssertionHandler(), or if no application-specified function is set, is equivalent to calling SDL_GetDefaultAssertionHandler().
The parameter puserdata is a pointer to a void*, which will store the "userdata" pointer that was passed to SDL_SetAssertionHandler(). This value will always be NULL for the default handler. If you don't care about this data, it is safe to pass a NULL pointer to this function to ignore it.
Parameters
puserdata pointer which is filled with the "userdata" pointer that was passed to SDL_SetAssertionHandler().
Returns
the SDL_AssertionHandler that is called when an assert triggers.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAssertionHandler
{
    if (userdata) {
        *userdata = assertion_userdata;
    }
    return assertion_handler;
}
References assertion_handler, and assertion_userdata.
SDL_GetAssertionReport()
const SDL_AssertData * SDL_GetAssertionReport (void)
Get a list of all assertion failures.
This function gets all assertions triggered since the last call to SDL_ResetAssertionReport(), or the start of the program.
The proper way to examine this data looks something like this:
const SDL_AssertData *item = SDL_GetAssertionReport();
while (item) {
   printf("'%s', %s (%s:%d), triggered %u times, always ignore: %s.\\n",
          item->condition, item->function, item->filename,
          item->linenum, item->trigger_count,
          item->always_ignore ? "yes" : "no");
   item = item->next;
}
Returns
a list of all failed assertions or NULL if the list is empty. This memory should not be modified or freed by the application. This pointer remains valid until the next call to SDL_Quit() or SDL_ResetAssertionReport().
Thread Safety
This function is not thread safe. Other threads calling SDL_ResetAssertionReport() simultaneously, may render the returned pointer invalid.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResetAssertionReport
{
    return triggered_assertions;
}
References triggered_assertions.
SDL_GetDefaultAssertionHandler()
SDL_AssertionHandler SDL_GetDefaultAssertionHandler (void)
Get the default assertion handler.
This returns the function pointer that is called by default when an assertion is triggered. This is an internal function provided by SDL, that is used for assertions when SDL_SetAssertionHandler() hasn't been used to provide a different function.
Returns
the default SDL_AssertionHandler that is called when an assert triggers.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAssertionHandler
{
    return SDL_PromptAssertion;
}
References SDL_PromptAssertion().
SDL_PromptAssertion()
SDL_AssertState SDLCALL SDL_PromptAssertion (const SDL_AssertData * data, void * userdata) static
{
    SDL_AssertState state = SDL_ASSERTION_ABORT;
    SDL_Window *window;
    SDL_MessageBoxData messagebox;
    SDL_MessageBoxButtonData buttons[] = {
        { 0, SDL_ASSERTION_RETRY, "Retry" },
        { 0, SDL_ASSERTION_BREAK, "Break" },
        { 0, SDL_ASSERTION_ABORT, "Abort" },
        { SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT,
          SDL_ASSERTION_IGNORE, "Ignore" },
        { SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT,
          SDL_ASSERTION_ALWAYS_IGNORE, "Always Ignore" }
    };
    int selected;
    char stack_buf[SDL_MAX_ASSERT_MESSAGE_STACK];
    char *message = stack_buf;
    size_t buf_len = sizeof(stack_buf);
    int len;
    (void)userdata; // unused in default handler.
    // Assume the output will fit...
    len = SDL_RenderAssertMessage(message, buf_len, data);
    // .. and if it didn't, try to allocate as much room as we actually need.
    if (len >= (int)buf_len) {
        if (SDL_size_add_check_overflow(len, 1, &buf_len)) {
            message = (char *)SDL_malloc(buf_len);
            if (message) {
                len = SDL_RenderAssertMessage(message, buf_len, data);
            } else {
                message = stack_buf;
            }
        }
    }
    // Something went very wrong
    if (len < 0) {
        if (message != stack_buf) {
            SDL_free(message);
        }
        return SDL_ASSERTION_ABORT;
    }
    debug_print("\n\n%s\n\n", message);
    // let env. variable override, so unit tests won't block in a GUI.
    const char *hint = SDL_GetHint(SDL_HINT_ASSERT);
    if (hint) {
        if (message != stack_buf) {
            SDL_free(message);
        }
        if (SDL_strcmp(hint, "abort") == 0) {
            return SDL_ASSERTION_ABORT;
        } else if (SDL_strcmp(hint, "break") == 0) {
            return SDL_ASSERTION_BREAK;
        } else if (SDL_strcmp(hint, "retry") == 0) {
            return SDL_ASSERTION_RETRY;
        } else if (SDL_strcmp(hint, "ignore") == 0) {
            return SDL_ASSERTION_IGNORE;
        } else if (SDL_strcmp(hint, "always_ignore") == 0) {
            return SDL_ASSERTION_ALWAYS_IGNORE;
        } else {
            return SDL_ASSERTION_ABORT; // oh well.
        }
    }
    // Leave fullscreen mode, if possible (scary!)
    window = SDL_GetToplevelForKeyboardFocus();
    if (window) {
        if (window->fullscreen_exclusive) {
            SDL_MinimizeWindow(window);
        } else {
            // !!! FIXME: ungrab the input if we're not fullscreen?
            // No need to mess with the window
            window = NULL;
        }
    }
    // Show a messagebox if we can, otherwise fall back to stdio
    SDL_zero(messagebox);
    messagebox.flags = SDL_MESSAGEBOX_WARNING;
    messagebox.window = window;
    messagebox.title = "Assertion Failed";
    messagebox.message = message;
    messagebox.numbuttons = SDL_arraysize(buttons);
    messagebox.buttons = buttons;
    if (SDL_ShowMessageBox(&messagebox, &selected)) {
        if (selected == -1) {
            state = SDL_ASSERTION_IGNORE;
        } else {
            state = (SDL_AssertState)selected;
        }
    } else {
#ifdef SDL_PLATFORM_PRIVATE_ASSERT
        SDL_PRIVATE_PROMPTASSERTION();
#elif defined(SDL_PLATFORM_EMSCRIPTEN)
        // This is nasty, but we can't block on a custom UI.
        for (;;) {
            bool okay = true;
            /* *INDENT-OFF* */ // clang-format off
            int reply = MAIN_THREAD_EM_ASM_INT({
                var str =
                    UTF8ToString($0) + '\n\n' +
                    'Abort/Retry/Ignore/AlwaysIgnore? [ariA] :';
                var reply = window.prompt(str, "i");
                if (reply === null) {
                    reply = "i";
                }
                return reply.length === 1 ? reply.charCodeAt(0) : -1;
            }, message);
            /* *INDENT-ON* */ // clang-format on
            switch (reply) {
            case 'a':
                state = SDL_ASSERTION_ABORT;
                break;
#if 0 // (currently) no break functionality on Emscripten
            case 'b':
                state = SDL_ASSERTION_BREAK;
                break;
#endif
            case 'r':
                state = SDL_ASSERTION_RETRY;
                break;
            case 'i':
                state = SDL_ASSERTION_IGNORE;
                break;
            case 'A':
                state = SDL_ASSERTION_ALWAYS_IGNORE;
                break;
            default:
                okay = false;
                break;
            }
            if (okay) {
                break;
            }
        }
#elif defined(HAVE_STDIO_H) && !defined(SDL_PLATFORM_3DS)
        // this is a little hacky.
        for (;;) {
            char buf[32];
            (void)fprintf(stderr, "Abort/Break/Retry/Ignore/AlwaysIgnore? [abriA] : ");
            (void)fflush(stderr);
            if (fgets(buf, sizeof(buf), stdin) == NULL) {
                break;
            }
            if (SDL_strncmp(buf, "a", 1) == 0) {
                state = SDL_ASSERTION_ABORT;
                break;
            } else if (SDL_strncmp(buf, "b", 1) == 0) {
                state = SDL_ASSERTION_BREAK;
                break;
            } else if (SDL_strncmp(buf, "r", 1) == 0) {
                state = SDL_ASSERTION_RETRY;
                break;
            } else if (SDL_strncmp(buf, "i", 1) == 0) {
                state = SDL_ASSERTION_IGNORE;
                break;
            } else if (SDL_strncmp(buf, "A", 1) == 0) {
                state = SDL_ASSERTION_ALWAYS_IGNORE;
                break;
            }
        }
#else
        SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_WARNING, "Assertion Failed", message, window);
#endif // HAVE_STDIO_H
    }
    // Re-enter fullscreen mode
    if (window) {
        SDL_RestoreWindow(window);
    }
    if (message != stack_buf) {
        SDL_free(message);
    }
    return state;
}
References SDL_MessageBoxData::buttons, debug_print(), SDL_MessageBoxData::flags, SDL_MessageBoxData::message, NULL, SDL_MessageBoxData::numbuttons, SDL_arraysize, SDL_ASSERTION_ABORT, SDL_ASSERTION_ALWAYS_IGNORE, SDL_ASSERTION_BREAK, SDL_ASSERTION_IGNORE, SDL_ASSERTION_RETRY, SDL_free(), SDL_GetHint(), SDL_GetToplevelForKeyboardFocus(), SDL_HINT_ASSERT, SDL_malloc(), SDL_MAX_ASSERT_MESSAGE_STACK, SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT, SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT, SDL_MESSAGEBOX_WARNING, SDL_MinimizeWindow(), SDL_RenderAssertMessage(), SDL_RestoreWindow(), SDL_ShowMessageBox(), SDL_ShowSimpleMessageBox(), SDL_size_add_check_overflow(), SDL_strcmp(), SDL_strncmp(), SDL_zero, SDLCALL, SDL_MessageBoxData::title, void(), and SDL_MessageBoxData::window.
Referenced by SDL_GenerateAssertionReport(), SDL_GetDefaultAssertionHandler(), and SDL_SetAssertionHandler().
SDL_RenderAssertMessage()
int SDL_RenderAssertMessage (char * buf, size_t buf_len, const SDL_AssertData * data) static
{
    return SDL_snprintf(buf, buf_len,
                        "Assertion failure at %s (%s:%d), triggered %u %s:" ENDLINE "  '%s'",
                        data->function, data->filename, data->linenum,
                        data->trigger_count, (data->trigger_count == 1) ? "time" : "times",
                        data->condition);
}
References ENDLINE, and SDL_snprintf().
Referenced by SDL_PromptAssertion().
SDL_ReportAssertion()
SDL_AssertState SDL_ReportAssertion (SDL_AssertData * data, const char * func, const char * file, int line)
Never call this directly.
Use the SDL_assert macros instead.
Parameters
data assert data structure.
func function name.
file file name.
line line number.
Returns
assert state.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_AssertState state = SDL_ASSERTION_IGNORE;
    static int assertion_running = 0;
#ifndef SDL_THREADS_DISABLED
    static SDL_SpinLock spinlock = 0;
    SDL_LockSpinlock(&spinlock);
    if (!assertion_mutex) { // never called SDL_Init()?
        assertion_mutex = SDL_CreateMutex();
        if (!assertion_mutex) {
            SDL_UnlockSpinlock(&spinlock);
            return SDL_ASSERTION_IGNORE; // oh well, I guess.
        }
    }
    SDL_UnlockSpinlock(&spinlock);
    SDL_LockMutex(assertion_mutex);
#endif // !SDL_THREADS_DISABLED
    // doing this because Visual C is upset over assigning in the macro.
    if (data->trigger_count == 0) {
        data->function = func;
        data->filename = file;
        data->linenum = line;
    }
    SDL_AddAssertionToReport(data);
    assertion_running++;
    if (assertion_running > 1) { // assert during assert! Abort.
        if (assertion_running == 2) {
            SDL_AbortAssertion();
        } else if (assertion_running == 3) { // Abort asserted!
            SDL_ExitProcess(42);
        } else {
            while (1) { // do nothing but spin; what else can you do?!
            }
        }
    }
    if (!data->always_ignore) {
        state = assertion_handler(data, assertion_userdata);
    }
    switch (state) {
    case SDL_ASSERTION_ALWAYS_IGNORE:
        state = SDL_ASSERTION_IGNORE;
        data->always_ignore = true;
        break;
    case SDL_ASSERTION_IGNORE:
    case SDL_ASSERTION_RETRY:
    case SDL_ASSERTION_BREAK:
        break; // macro handles these.
    case SDL_ASSERTION_ABORT:
        SDL_AbortAssertion();
        // break;  ...shouldn't return, but oh well.
    }
    assertion_running--;
#ifndef SDL_THREADS_DISABLED
    SDL_UnlockMutex(assertion_mutex);
#endif
    return state;
}
References assertion_handler, assertion_mutex, assertion_userdata, SDL_AbortAssertion(), SDL_AddAssertionToReport(), SDL_ASSERTION_ABORT, SDL_ASSERTION_ALWAYS_IGNORE, SDL_ASSERTION_BREAK, SDL_ASSERTION_IGNORE, SDL_ASSERTION_RETRY, SDL_CreateMutex(), SDL_ExitProcess(), SDL_LockMutex(), SDL_LockSpinlock(), SDL_UnlockMutex(), and SDL_UnlockSpinlock().
SDL_ResetAssertionReport()
void SDL_ResetAssertionReport (void)
Clear the list of all assertion failures.
This function will clear the list of all assertions triggered up to that point. Immediately following this call, SDL_GetAssertionReport will return no items. In addition, any previously-triggered assertions will be reset to a trigger_count of zero, and their always_ignore state will be false.
Thread Safety
This function is not thread safe. Other threads triggering an assertion, or simultaneously calling this function may cause memory leaks or crashes.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAssertionReport
{
    SDL_AssertData *next = NULL;
    SDL_AssertData *item;
    for (item = triggered_assertions; item; item = next) {
        next = (SDL_AssertData *)item->next;
        item->always_ignore = false;
        item->trigger_count = 0;
        item->next = NULL;
    }
    triggered_assertions = NULL;
}
References SDL_AssertData::always_ignore, SDL_AssertData::next, NULL, SDL_AssertData::trigger_count, and triggered_assertions.
Referenced by SDL_GenerateAssertionReport().
SDL_SetAssertionHandler()
void SDL_SetAssertionHandler (SDL_AssertionHandler handler, void * userdata)
Set an application-defined assertion handler.
This function allows an application to show its own assertion UI and/or force the response to an assertion failure. If the application doesn't provide this, SDL will try to do the right thing, popping up a system-specific GUI dialog, and probably minimizing any fullscreen windows.
This callback may fire from any thread, but it runs wrapped in a mutex, so it will only fire from one thread at a time.
This callback is NOT reset to SDL's internal handler upon SDL_Quit()!
Parameters
handler the SDL_AssertionHandler function to call when an assertion fails or NULL for the default handler.
userdata a pointer that is passed to handler.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAssertionHandler
{
    if (handler != NULL) {
        assertion_handler = handler;
        assertion_userdata = userdata;
    } else {
        assertion_handler = SDL_PromptAssertion;
        assertion_userdata = NULL;
    }
}
References assertion_handler, assertion_userdata, NULL, and SDL_PromptAssertion().
Variable Documentation
assertion_handler
SDL_AssertionHandler assertion_handler = SDL_PromptAssertion static
Referenced by SDL_GenerateAssertionReport(), SDL_GetAssertionHandler(), SDL_ReportAssertion(), and SDL_SetAssertionHandler().
assertion_mutex
SDL_Mutex* assertion_mutex = NULL static
Referenced by SDL_AssertionsQuit(), and SDL_ReportAssertion().
assertion_userdata
void* assertion_userdata = NULL static
Referenced by SDL_GetAssertionHandler(), SDL_ReportAssertion(), and SDL_SetAssertionHandler().
triggered_assertions
SDL_AssertData* triggered_assertions = NULL static
Referenced by SDL_AddAssertionToReport(), SDL_GenerateAssertionReport(), SDL_GetAssertionReport(), and SDL_ResetAssertionReport().