SDL3: SDL_VideoDevice Struct Reference
SDL_VideoDevice Struct Reference
#include <SDL_sysvideo.h>
Data Fields
void(* AcceptDragAndDrop)(SDL_Window *window, bool accept)
bool(* ApplyWindowProgress)(SDL_VideoDevice *_this, SDL_Window *window)
bool checked_texture_framebuffer
bool(* ClearComposition)(SDL_VideoDevice *_this, SDL_Window *window)
SDL_ClipboardDataCallback clipboard_callback
SDL_ClipboardCleanupCallback clipboard_cleanup
char ** clipboard_mime_types
Uint32 clipboard_sequence
void * clipboard_userdata
bool(* CreateSDLWindow)(SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID create_props)
bool(* CreateWindowFramebuffer)(SDL_VideoDevice *_this, SDL_Window *window, SDL_PixelFormat *format, void **pixels, int *pitch)
SDL_GLContext current_glctx
SDL_TLSID current_glctx_tls
SDL_Window * current_glwin
SDL_TLSID current_glwin_tls
SDL_Rect desktop_bounds
void(* DestroyWindow)(SDL_VideoDevice *_this, SDL_Window *window)
void(* DestroyWindowFramebuffer)(SDL_VideoDevice *_this, SDL_Window *window)
Uint32 device_caps
SDL_VideoDisplay ** displays
void * egl_attrib_callback_userdata
SDL_EGLIntArrayCallback egl_contextattrib_callback
SDL_EGLAttribArrayCallback egl_platformattrib_callback
SDL_EGLIntArrayCallback egl_surfaceattrib_callback
bool(* FlashWindow)(SDL_VideoDevice *_this, SDL_Window *window, SDL_FlashOperation operation)
void(* free)(SDL_VideoDevice *_this)
void *(* GetClipboardData)(SDL_VideoDevice *_this, const char *mime_type, size_t *size)
char *(* GetClipboardText)(SDL_VideoDevice *_this)
bool(* GetDisplayBounds)(SDL_VideoDevice *_this, SDL_VideoDisplay *display, SDL_Rect *rect)
SDL_DisplayID(* GetDisplayForWindow)(SDL_VideoDevice *_this, SDL_Window *window)
bool(* GetDisplayModes)(SDL_VideoDevice *_this, SDL_VideoDisplay *display)
bool(* GetDisplayUsableBounds)(SDL_VideoDevice *_this, SDL_VideoDisplay *display, SDL_Rect *rect)
char *(* GetPrimarySelectionText)(SDL_VideoDevice *_this)
const char **(* GetTextMimeTypes)(SDL_VideoDevice *_this, size_t *num_mime_types)
bool(* GetWindowBordersSize)(SDL_VideoDevice *_this, SDL_Window *window, int *top, int *left, int *bottom, int *right)
float(* GetWindowContentScale)(SDL_VideoDevice *_this, SDL_Window *window)
bool(* GetWindowFramebufferVSync)(SDL_VideoDevice *_this, SDL_Window *window, int *vsync)
void *(* GetWindowICCProfile)(SDL_VideoDevice *_this, SDL_Window *window, size_t *size)
void(* GetWindowSizeInPixels)(SDL_VideoDevice *_this, SDL_Window *window, int *w, int *h)
bool gl_allow_no_surface
struct {
int accelerated
int accum_alpha_size
int accum_blue_size
int accum_green_size
int accum_red_size
int alpha_size
int blue_size
int buffer_size
int depth_size
SDL_SharedObject * dll_handle
int double_buffer
int driver_loaded
char driver_path [256]
int egl_platform
int flags
int floatbuffers
int framebuffer_srgb_capable
int green_size
int major_version
int minor_version
int multisamplebuffers
int multisamplesamples
int no_error
int profile_mask
int red_size
int release_behavior
int reset_notification
int retained_backing
int share_with_current_context
int stencil_size
int stereo
} gl_config
SDL_GLContext(* GL_CreateContext)(SDL_VideoDevice *_this, SDL_Window *window)
struct SDL_GLDriverData * gl_data
void(* GL_DefaultProfileConfig)(SDL_VideoDevice *_this, int *mask, int *major, int *minor)
bool(* GL_DestroyContext)(SDL_VideoDevice *_this, SDL_GLContext context)
SDL_EGLSurface(* GL_GetEGLSurface)(SDL_VideoDevice *_this, SDL_Window *window)
SDL_FunctionPointer(* GL_GetProcAddress)(SDL_VideoDevice *_this, const char *proc)
bool(* GL_GetSwapInterval)(SDL_VideoDevice *_this, int *interval)
bool(* GL_LoadLibrary)(SDL_VideoDevice *_this, const char *path)
bool(* GL_MakeCurrent)(SDL_VideoDevice *_this, SDL_Window *window, SDL_GLContext context)
bool(* GL_SetSwapInterval)(SDL_VideoDevice *_this, int interval)
bool(* GL_SwapWindow)(SDL_VideoDevice *_this, SDL_Window *window)
void(* GL_UnloadLibrary)(SDL_VideoDevice *_this)
SDL_Window * grabbed_window
bool(* HasClipboardData)(SDL_VideoDevice *_this, const char *mime_type)
bool(* HasClipboardText)(SDL_VideoDevice *_this)
bool(* HasPrimarySelectionText)(SDL_VideoDevice *_this)
bool(* HasScreenKeyboardSupport)(SDL_VideoDevice *_this)
void(* HideScreenKeyboard)(SDL_VideoDevice *_this, SDL_Window *window)
void(* HideWindow)(SDL_VideoDevice *_this, SDL_Window *window)
SDL_VideoData * internal
bool is_dummy
bool(* IsScreenKeyboardShown)(SDL_VideoDevice *_this, SDL_Window *window)
void(* MaximizeWindow)(SDL_VideoDevice *_this, SDL_Window *window)
SDL_MetalView(* Metal_CreateView)(SDL_VideoDevice *_this, SDL_Window *window)
void(* Metal_DestroyView)(SDL_VideoDevice *_this, SDL_MetalView view)
void *(* Metal_GetLayer)(SDL_VideoDevice *_this, SDL_MetalView view)
void(* MinimizeWindow)(SDL_VideoDevice *_this, SDL_Window *window)
const char * name
size_t num_clipboard_mime_types
int num_displays
void(* OnWindowEnter)(SDL_VideoDevice *_this, SDL_Window *window)
char * primary_selection_text
void(* PumpEvents)(SDL_VideoDevice *_this)
void(* RaiseWindow)(SDL_VideoDevice *_this, SDL_Window *window)
void(* RefreshDisplays)(SDL_VideoDevice *_this)
void(* ResetTouch)(SDL_VideoDevice *_this)
void(* RestoreWindow)(SDL_VideoDevice *_this, SDL_Window *window)
void(* SendWakeupEvent)(SDL_VideoDevice *_this, SDL_Window *window)
bool(* SetClipboardData)(SDL_VideoDevice *_this)
bool(* SetClipboardText)(SDL_VideoDevice *_this, const char *text)
bool(* SetDisplayMode)(SDL_VideoDevice *_this, SDL_VideoDisplay *display, SDL_DisplayMode *mode)
bool(* SetPrimarySelectionText)(SDL_VideoDevice *_this, const char *text)
void(* SetTextInputProperties)(SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID props)
bool setting_display_mode
void(* SetWindowAlwaysOnTop)(SDL_VideoDevice *_this, SDL_Window *window, bool on_top)
void(* SetWindowAspectRatio)(SDL_VideoDevice *_this, SDL_Window *window)
void(* SetWindowBordered)(SDL_VideoDevice *_this, SDL_Window *window, bool bordered)
bool(* SetWindowFocusable)(SDL_VideoDevice *_this, SDL_Window *window, bool focusable)
bool(* SetWindowFramebufferVSync)(SDL_VideoDevice *_this, SDL_Window *window, int vsync)
SDL_FullscreenResult(* SetWindowFullscreen)(SDL_VideoDevice *_this, SDL_Window *window, SDL_VideoDisplay *display, SDL_FullscreenOp fullscreen)
bool(* SetWindowHitTest)(SDL_Window *window, bool enabled)
bool(* SetWindowIcon)(SDL_VideoDevice *_this, SDL_Window *window, SDL_Surface *icon)
bool(* SetWindowKeyboardGrab)(SDL_VideoDevice *_this, SDL_Window *window, bool grabbed)
void(* SetWindowMaximumSize)(SDL_VideoDevice *_this, SDL_Window *window)
void(* SetWindowMinimumSize)(SDL_VideoDevice *_this, SDL_Window *window)
bool(* SetWindowModal)(SDL_VideoDevice *_this, SDL_Window *window, bool modal)
bool(* SetWindowMouseGrab)(SDL_VideoDevice *_this, SDL_Window *window, bool grabbed)
bool(* SetWindowMouseRect)(SDL_VideoDevice *_this, SDL_Window *window)
bool(* SetWindowOpacity)(SDL_VideoDevice *_this, SDL_Window *window, float opacity)
bool(* SetWindowParent)(SDL_VideoDevice *_this, SDL_Window *window, SDL_Window *parent)
bool(* SetWindowPosition)(SDL_VideoDevice *_this, SDL_Window *window)
void(* SetWindowResizable)(SDL_VideoDevice *_this, SDL_Window *window, bool resizable)
void(* SetWindowSize)(SDL_VideoDevice *_this, SDL_Window *window)
void(* SetWindowTitle)(SDL_VideoDevice *_this, SDL_Window *window)
bool(* ShowMessageBox)(SDL_VideoDevice *_this, const SDL_MessageBoxData *messageboxdata, int *buttonID)
void(* ShowScreenKeyboard)(SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID props)
void(* ShowWindow)(SDL_VideoDevice *_this, SDL_Window *window)
void(* ShowWindowSystemMenu)(SDL_Window *window, int x, int y)
bool(* StartTextInput)(SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID props)
bool(* StopTextInput)(SDL_VideoDevice *_this, SDL_Window *window)
bool suspend_screensaver
bool(* SuspendScreenSaver)(SDL_VideoDevice *_this)
bool(* SyncWindow)(SDL_VideoDevice *_this, SDL_Window *window)
SDL_SystemTheme system_theme
SDL_ThreadID thread
bool(* UpdateTextInputArea)(SDL_VideoDevice *_this, SDL_Window *window)
bool(* UpdateWindowFramebuffer)(SDL_VideoDevice *_this, SDL_Window *window, const SDL_Rect *rects, int numrects)
bool(* UpdateWindowShape)(SDL_VideoDevice *_this, SDL_Window *window, SDL_Surface *shape)
bool(* VideoInit)(SDL_VideoDevice *_this)
void(* VideoQuit)(SDL_VideoDevice *_this)
struct {
SDL_SharedObject * loader_handle
int loader_loaded
char loader_path [256]
SDL_FunctionPointer vkEnumerateInstanceExtensionProperties
SDL_FunctionPointer vkGetInstanceProcAddr
} vulkan_config
bool(* Vulkan_CreateSurface)(SDL_VideoDevice *_this, SDL_Window *window, VkInstance instance, const struct VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void(* Vulkan_DestroySurface)(SDL_VideoDevice *_this, VkInstance instance, VkSurfaceKHR surface, const struct VkAllocationCallbacks *allocator)
char const *const *(* Vulkan_GetInstanceExtensions)(SDL_VideoDevice *_this, Uint32 *count)
bool(* Vulkan_GetPresentationSupport)(SDL_VideoDevice *_this, VkInstance instance, VkPhysicalDevice physicalDevice, Uint32 queueFamilyIndex)
bool(* Vulkan_LoadLibrary)(SDL_VideoDevice *_this, const char *path)
void(* Vulkan_UnloadLibrary)(SDL_VideoDevice *_this)
int(* WaitEventTimeout)(SDL_VideoDevice *_this, Sint64 timeoutNS)
void * wakeup_window
SDL_Window * windows
Field Documentation
accelerated
int SDL_VideoDevice::accelerated
AcceptDragAndDrop
void(* SDL_VideoDevice::AcceptDragAndDrop) (SDL_Window *window, bool accept)
accum_alpha_size
int SDL_VideoDevice::accum_alpha_size
accum_blue_size
int SDL_VideoDevice::accum_blue_size
accum_green_size
int SDL_VideoDevice::accum_green_size
accum_red_size
int SDL_VideoDevice::accum_red_size
alpha_size
int SDL_VideoDevice::alpha_size
ApplyWindowProgress
bool(* SDL_VideoDevice::ApplyWindowProgress) (SDL_VideoDevice *_this, SDL_Window *window)
blue_size
int SDL_VideoDevice::blue_size
buffer_size
int SDL_VideoDevice::buffer_size
checked_texture_framebuffer
bool SDL_VideoDevice::checked_texture_framebuffer
ClearComposition
bool(* SDL_VideoDevice::ClearComposition) (SDL_VideoDevice *_this, SDL_Window *window)
clipboard_callback
SDL_ClipboardDataCallback SDL_VideoDevice::clipboard_callback
clipboard_cleanup
SDL_ClipboardCleanupCallback SDL_VideoDevice::clipboard_cleanup
clipboard_mime_types
char** SDL_VideoDevice::clipboard_mime_types
clipboard_sequence
Uint32 SDL_VideoDevice::clipboard_sequence
clipboard_userdata
void* SDL_VideoDevice::clipboard_userdata
CreateSDLWindow
bool(* SDL_VideoDevice::CreateSDLWindow) (SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID create_props)
Referenced by createDevice().
CreateWindowFramebuffer
bool(* SDL_VideoDevice::CreateWindowFramebuffer) (SDL_VideoDevice *_this, SDL_Window *window, SDL_PixelFormat *format, void **pixels, int *pitch)
Referenced by createDevice().
current_glctx
SDL_GLContext SDL_VideoDevice::current_glctx
current_glctx_tls
SDL_TLSID SDL_VideoDevice::current_glctx_tls
current_glwin
SDL_Window* SDL_VideoDevice::current_glwin
current_glwin_tls
SDL_TLSID SDL_VideoDevice::current_glwin_tls
depth_size
int SDL_VideoDevice::depth_size
desktop_bounds
SDL_Rect SDL_VideoDevice::desktop_bounds
DestroyWindow
void(* SDL_VideoDevice::DestroyWindow) (SDL_VideoDevice *_this, SDL_Window *window)
Referenced by createDevice().
DestroyWindowFramebuffer
void(* SDL_VideoDevice::DestroyWindowFramebuffer) (SDL_VideoDevice *_this, SDL_Window *window)
device_caps
Uint32 SDL_VideoDevice::device_caps
displays
SDL_VideoDisplay** SDL_VideoDevice::displays
dll_handle
SDL_SharedObject* SDL_VideoDevice::dll_handle
double_buffer
int SDL_VideoDevice::double_buffer
driver_loaded
int SDL_VideoDevice::driver_loaded
driver_path
char SDL_VideoDevice::driver_path[256]
egl_attrib_callback_userdata
void* SDL_VideoDevice::egl_attrib_callback_userdata
egl_contextattrib_callback
SDL_EGLIntArrayCallback SDL_VideoDevice::egl_contextattrib_callback
egl_platform
int SDL_VideoDevice::egl_platform
egl_platformattrib_callback
SDL_EGLAttribArrayCallback SDL_VideoDevice::egl_platformattrib_callback
egl_surfaceattrib_callback
SDL_EGLIntArrayCallback SDL_VideoDevice::egl_surfaceattrib_callback
flags
int SDL_VideoDevice::flags
FlashWindow
bool(* SDL_VideoDevice::FlashWindow) (SDL_VideoDevice *_this, SDL_Window *window, SDL_FlashOperation operation)
floatbuffers
int SDL_VideoDevice::floatbuffers
framebuffer_srgb_capable
int SDL_VideoDevice::framebuffer_srgb_capable
free
void(* SDL_VideoDevice::free) (SDL_VideoDevice *_this)
Referenced by createDevice().
GetClipboardData
void *(* SDL_VideoDevice::GetClipboardData) (SDL_VideoDevice *_this, const char *mime_type, size_t *size)
GetClipboardText
char *(* SDL_VideoDevice::GetClipboardText) (SDL_VideoDevice *_this)
GetDisplayBounds
bool(* SDL_VideoDevice::GetDisplayBounds) (SDL_VideoDevice *_this, SDL_VideoDisplay *display, SDL_Rect *rect)
GetDisplayForWindow
SDL_DisplayID(* SDL_VideoDevice::GetDisplayForWindow) (SDL_VideoDevice *_this, SDL_Window *window)
GetDisplayModes
bool(* SDL_VideoDevice::GetDisplayModes) (SDL_VideoDevice *_this, SDL_VideoDisplay *display)
GetDisplayUsableBounds
bool(* SDL_VideoDevice::GetDisplayUsableBounds) (SDL_VideoDevice *_this, SDL_VideoDisplay *display, SDL_Rect *rect)
GetPrimarySelectionText
char *(* SDL_VideoDevice::GetPrimarySelectionText) (SDL_VideoDevice *_this)
GetTextMimeTypes
const char **(* SDL_VideoDevice::GetTextMimeTypes) (SDL_VideoDevice *_this, size_t *num_mime_types)
GetWindowBordersSize
bool(* SDL_VideoDevice::GetWindowBordersSize) (SDL_VideoDevice *_this, SDL_Window *window, int *top, int *left, int *bottom, int *right)
GetWindowContentScale
float(* SDL_VideoDevice::GetWindowContentScale) (SDL_VideoDevice *_this, SDL_Window *window)
GetWindowFramebufferVSync
bool(* SDL_VideoDevice::GetWindowFramebufferVSync) (SDL_VideoDevice *_this, SDL_Window *window, int *vsync)
GetWindowICCProfile
void *(* SDL_VideoDevice::GetWindowICCProfile) (SDL_VideoDevice *_this, SDL_Window *window, size_t *size)
GetWindowSizeInPixels
void(* SDL_VideoDevice::GetWindowSizeInPixels) (SDL_VideoDevice *_this, SDL_Window *window, int *w, int *h)
gl_allow_no_surface
bool SDL_VideoDevice::gl_allow_no_surface
[struct]
struct { ... } SDL_VideoDevice::gl_config
GL_CreateContext
SDL_GLContext(* SDL_VideoDevice::GL_CreateContext) (SDL_VideoDevice *_this, SDL_Window *window)
Referenced by createDevice().
gl_data
struct SDL_GLDriverData* SDL_VideoDevice::gl_data
GL_DefaultProfileConfig
void(* SDL_VideoDevice::GL_DefaultProfileConfig) (SDL_VideoDevice *_this, int *mask, int *major, int *minor)
GL_DestroyContext
bool(* SDL_VideoDevice::GL_DestroyContext) (SDL_VideoDevice *_this, SDL_GLContext context)
Referenced by createDevice().
GL_GetEGLSurface
SDL_EGLSurface(* SDL_VideoDevice::GL_GetEGLSurface) (SDL_VideoDevice *_this, SDL_Window *window)
GL_GetProcAddress
SDL_FunctionPointer(* SDL_VideoDevice::GL_GetProcAddress) (SDL_VideoDevice *_this, const char *proc)
Referenced by createDevice().
GL_GetSwapInterval
bool(* SDL_VideoDevice::GL_GetSwapInterval) (SDL_VideoDevice *_this, int *interval)
GL_LoadLibrary
bool(* SDL_VideoDevice::GL_LoadLibrary) (SDL_VideoDevice *_this, const char *path)
Referenced by createDevice().
GL_MakeCurrent
bool(* SDL_VideoDevice::GL_MakeCurrent) (SDL_VideoDevice *_this, SDL_Window *window, SDL_GLContext context)
Referenced by createDevice().
GL_SetSwapInterval
bool(* SDL_VideoDevice::GL_SetSwapInterval) (SDL_VideoDevice *_this, int interval)
Referenced by createDevice().
GL_SwapWindow
bool(* SDL_VideoDevice::GL_SwapWindow) (SDL_VideoDevice *_this, SDL_Window *window)
Referenced by createDevice().
GL_UnloadLibrary
void(* SDL_VideoDevice::GL_UnloadLibrary) (SDL_VideoDevice *_this)
Referenced by createDevice().
grabbed_window
SDL_Window* SDL_VideoDevice::grabbed_window
green_size
int SDL_VideoDevice::green_size
HasClipboardData
bool(* SDL_VideoDevice::HasClipboardData) (SDL_VideoDevice *_this, const char *mime_type)
HasClipboardText
bool(* SDL_VideoDevice::HasClipboardText) (SDL_VideoDevice *_this)
HasPrimarySelectionText
bool(* SDL_VideoDevice::HasPrimarySelectionText) (SDL_VideoDevice *_this)
HasScreenKeyboardSupport
bool(* SDL_VideoDevice::HasScreenKeyboardSupport) (SDL_VideoDevice *_this)
HideScreenKeyboard
void(* SDL_VideoDevice::HideScreenKeyboard) (SDL_VideoDevice *_this, SDL_Window *window)
HideWindow
void(* SDL_VideoDevice::HideWindow) (SDL_VideoDevice *_this, SDL_Window *window)
Referenced by createDevice().
internal
SDL_VideoData* SDL_VideoDevice::internal
Referenced by createDevice().
is_dummy
bool SDL_VideoDevice::is_dummy
IsScreenKeyboardShown
bool(* SDL_VideoDevice::IsScreenKeyboardShown) (SDL_VideoDevice *_this, SDL_Window *window)
loader_handle
SDL_SharedObject* SDL_VideoDevice::loader_handle
loader_loaded
int SDL_VideoDevice::loader_loaded
loader_path
char SDL_VideoDevice::loader_path[256]
major_version
int SDL_VideoDevice::major_version
MaximizeWindow
void(* SDL_VideoDevice::MaximizeWindow) (SDL_VideoDevice *_this, SDL_Window *window)
Metal_CreateView
SDL_MetalView(* SDL_VideoDevice::Metal_CreateView) (SDL_VideoDevice *_this, SDL_Window *window)
Metal_DestroyView
void(* SDL_VideoDevice::Metal_DestroyView) (SDL_VideoDevice *_this, SDL_MetalView view)
Metal_GetLayer
void *(* SDL_VideoDevice::Metal_GetLayer) (SDL_VideoDevice *_this, SDL_MetalView view)
MinimizeWindow
void(* SDL_VideoDevice::MinimizeWindow) (SDL_VideoDevice *_this, SDL_Window *window)
minor_version
int SDL_VideoDevice::minor_version
multisamplebuffers
int SDL_VideoDevice::multisamplebuffers
multisamplesamples
int SDL_VideoDevice::multisamplesamples
name
const char* SDL_VideoDevice::name
no_error
int SDL_VideoDevice::no_error
num_clipboard_mime_types
size_t SDL_VideoDevice::num_clipboard_mime_types
num_displays
int SDL_VideoDevice::num_displays
OnWindowEnter
void(* SDL_VideoDevice::OnWindowEnter) (SDL_VideoDevice *_this, SDL_Window *window)
primary_selection_text
char* SDL_VideoDevice::primary_selection_text
profile_mask
int SDL_VideoDevice::profile_mask
PumpEvents
void(* SDL_VideoDevice::PumpEvents) (SDL_VideoDevice *_this)
Referenced by createDevice().
RaiseWindow
void(* SDL_VideoDevice::RaiseWindow) (SDL_VideoDevice *_this, SDL_Window *window)
red_size
int SDL_VideoDevice::red_size
RefreshDisplays
void(* SDL_VideoDevice::RefreshDisplays) (SDL_VideoDevice *_this)
release_behavior
int SDL_VideoDevice::release_behavior
reset_notification
int SDL_VideoDevice::reset_notification
ResetTouch
void(* SDL_VideoDevice::ResetTouch) (SDL_VideoDevice *_this)
Referenced by SDL_GetTouch().
RestoreWindow
void(* SDL_VideoDevice::RestoreWindow) (SDL_VideoDevice *_this, SDL_Window *window)
retained_backing
int SDL_VideoDevice::retained_backing
SendWakeupEvent
void(* SDL_VideoDevice::SendWakeupEvent) (SDL_VideoDevice *_this, SDL_Window *window)
SetClipboardData
bool(* SDL_VideoDevice::SetClipboardData) (SDL_VideoDevice *_this)
SetClipboardText
bool(* SDL_VideoDevice::SetClipboardText) (SDL_VideoDevice *_this, const char *text)
SetDisplayMode
bool(* SDL_VideoDevice::SetDisplayMode) (SDL_VideoDevice *_this, SDL_VideoDisplay *display, SDL_DisplayMode *mode)
SetPrimarySelectionText
bool(* SDL_VideoDevice::SetPrimarySelectionText) (SDL_VideoDevice *_this, const char *text)
SetTextInputProperties
void(* SDL_VideoDevice::SetTextInputProperties) (SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID props)
setting_display_mode
bool SDL_VideoDevice::setting_display_mode
SetWindowAlwaysOnTop
void(* SDL_VideoDevice::SetWindowAlwaysOnTop) (SDL_VideoDevice *_this, SDL_Window *window, bool on_top)
SetWindowAspectRatio
void(* SDL_VideoDevice::SetWindowAspectRatio) (SDL_VideoDevice *_this, SDL_Window *window)
SetWindowBordered
void(* SDL_VideoDevice::SetWindowBordered) (SDL_VideoDevice *_this, SDL_Window *window, bool bordered)
SetWindowFocusable
bool(* SDL_VideoDevice::SetWindowFocusable) (SDL_VideoDevice *_this, SDL_Window *window, bool focusable)
SetWindowFramebufferVSync
bool(* SDL_VideoDevice::SetWindowFramebufferVSync) (SDL_VideoDevice *_this, SDL_Window *window, int vsync)
SetWindowFullscreen
SDL_FullscreenResult(* SDL_VideoDevice::SetWindowFullscreen) (SDL_VideoDevice *_this, SDL_Window *window, SDL_VideoDisplay *display, SDL_FullscreenOp fullscreen)
SetWindowHitTest
bool(* SDL_VideoDevice::SetWindowHitTest) (SDL_Window *window, bool enabled)
SetWindowIcon
bool(* SDL_VideoDevice::SetWindowIcon) (SDL_VideoDevice *_this, SDL_Window *window, SDL_Surface *icon)
SetWindowKeyboardGrab
bool(* SDL_VideoDevice::SetWindowKeyboardGrab) (SDL_VideoDevice *_this, SDL_Window *window, bool grabbed)
SetWindowMaximumSize
void(* SDL_VideoDevice::SetWindowMaximumSize) (SDL_VideoDevice *_this, SDL_Window *window)
SetWindowMinimumSize
void(* SDL_VideoDevice::SetWindowMinimumSize) (SDL_VideoDevice *_this, SDL_Window *window)
SetWindowModal
bool(* SDL_VideoDevice::SetWindowModal) (SDL_VideoDevice *_this, SDL_Window *window, bool modal)
SetWindowMouseGrab
bool(* SDL_VideoDevice::SetWindowMouseGrab) (SDL_VideoDevice *_this, SDL_Window *window, bool grabbed)
SetWindowMouseRect
bool(* SDL_VideoDevice::SetWindowMouseRect) (SDL_VideoDevice *_this, SDL_Window *window)
SetWindowOpacity
bool(* SDL_VideoDevice::SetWindowOpacity) (SDL_VideoDevice *_this, SDL_Window *window, float opacity)
SetWindowParent
bool(* SDL_VideoDevice::SetWindowParent) (SDL_VideoDevice *_this, SDL_Window *window, SDL_Window *parent)
SetWindowPosition
bool(* SDL_VideoDevice::SetWindowPosition) (SDL_VideoDevice *_this, SDL_Window *window)
SetWindowResizable
void(* SDL_VideoDevice::SetWindowResizable) (SDL_VideoDevice *_this, SDL_Window *window, bool resizable)
SetWindowSize
void(* SDL_VideoDevice::SetWindowSize) (SDL_VideoDevice *_this, SDL_Window *window)
Referenced by createDevice().
SetWindowTitle
void(* SDL_VideoDevice::SetWindowTitle) (SDL_VideoDevice *_this, SDL_Window *window)
share_with_current_context
int SDL_VideoDevice::share_with_current_context
ShowMessageBox
bool(* SDL_VideoDevice::ShowMessageBox) (SDL_VideoDevice *_this, const SDL_MessageBoxData *messageboxdata, int *buttonID)
ShowScreenKeyboard
void(* SDL_VideoDevice::ShowScreenKeyboard) (SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID props)
ShowWindow
void(* SDL_VideoDevice::ShowWindow) (SDL_VideoDevice *_this, SDL_Window *window)
Referenced by createDevice().
ShowWindowSystemMenu
void(* SDL_VideoDevice::ShowWindowSystemMenu) (SDL_Window *window, int x, int y)
StartTextInput
bool(* SDL_VideoDevice::StartTextInput) (SDL_VideoDevice *_this, SDL_Window *window, SDL_PropertiesID props)
Referenced by SDL_SetKeyboardFocus().
stencil_size
int SDL_VideoDevice::stencil_size
stereo
int SDL_VideoDevice::stereo
StopTextInput
bool(* SDL_VideoDevice::StopTextInput) (SDL_VideoDevice *_this, SDL_Window *window)
Referenced by SDL_SetKeyboardFocus().
suspend_screensaver
bool SDL_VideoDevice::suspend_screensaver
SuspendScreenSaver
bool(* SDL_VideoDevice::SuspendScreenSaver) (SDL_VideoDevice *_this)
SyncWindow
bool(* SDL_VideoDevice::SyncWindow) (SDL_VideoDevice *_this, SDL_Window *window)
system_theme
SDL_SystemTheme SDL_VideoDevice::system_theme
thread
SDL_ThreadID SDL_VideoDevice::thread
UpdateTextInputArea
bool(* SDL_VideoDevice::UpdateTextInputArea) (SDL_VideoDevice *_this, SDL_Window *window)
UpdateWindowFramebuffer
bool(* SDL_VideoDevice::UpdateWindowFramebuffer) (SDL_VideoDevice *_this, SDL_Window *window, const SDL_Rect *rects, int numrects)
Referenced by createDevice().
UpdateWindowShape
bool(* SDL_VideoDevice::UpdateWindowShape) (SDL_VideoDevice *_this, SDL_Window *window, SDL_Surface *shape)
VideoInit
bool(* SDL_VideoDevice::VideoInit) (SDL_VideoDevice *_this)
Referenced by createDevice().
VideoQuit
void(* SDL_VideoDevice::VideoQuit) (SDL_VideoDevice *_this)
Referenced by createDevice().
vkEnumerateInstanceExtensionProperties
SDL_FunctionPointer SDL_VideoDevice::vkEnumerateInstanceExtensionProperties
vkGetInstanceProcAddr
SDL_FunctionPointer SDL_VideoDevice::vkGetInstanceProcAddr
[struct]
struct { ... } SDL_VideoDevice::vulkan_config
Vulkan_CreateSurface
bool(* SDL_VideoDevice::Vulkan_CreateSurface) (SDL_VideoDevice *_this, SDL_Window *window, VkInstance instance, const struct VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
Vulkan_DestroySurface
void(* SDL_VideoDevice::Vulkan_DestroySurface) (SDL_VideoDevice *_this, VkInstance instance, VkSurfaceKHR surface, const struct VkAllocationCallbacks *allocator)
Vulkan_GetInstanceExtensions
char const *const *(* SDL_VideoDevice::Vulkan_GetInstanceExtensions) (SDL_VideoDevice *_this, Uint32 *count)
Vulkan_GetPresentationSupport
bool(* SDL_VideoDevice::Vulkan_GetPresentationSupport) (SDL_VideoDevice *_this, VkInstance instance, VkPhysicalDevice physicalDevice, Uint32 queueFamilyIndex)
Vulkan_LoadLibrary
bool(* SDL_VideoDevice::Vulkan_LoadLibrary) (SDL_VideoDevice *_this, const char *path)
Vulkan_UnloadLibrary
void(* SDL_VideoDevice::Vulkan_UnloadLibrary) (SDL_VideoDevice *_this)
WaitEventTimeout
int(* SDL_VideoDevice::WaitEventTimeout) (SDL_VideoDevice *_this, Sint64 timeoutNS)
wakeup_window
void* SDL_VideoDevice::wakeup_window
windows
SDL_Window* SDL_VideoDevice::windows
The documentation for this struct was generated from the following file:
SDL-main/src/video/SDL_sysvideo.h