SDL3: SDL-main/src/audio/dummy/SDL_dummyaudio.c File Reference
SDL_dummyaudio.c File Reference
#include "SDL_internal.h"
#include "../SDL_sysaudio.h"
#include "SDL_dummyaudio.h"
Functions
static void DUMMYAUDIO_CloseDevice (SDL_AudioDevice *device)
static Uint8 * DUMMYAUDIO_GetDeviceBuf (SDL_AudioDevice *device, int *buffer_size)
static bool DUMMYAUDIO_Init (SDL_AudioDriverImpl *impl)
static bool DUMMYAUDIO_OpenDevice (SDL_AudioDevice *device)
static int DUMMYAUDIO_RecordDevice (SDL_AudioDevice *device, void *buffer, int buflen)
static bool DUMMYAUDIO_WaitDevice (SDL_AudioDevice *device)
Variables
AudioBootStrap DUMMYAUDIO_bootstrap
Function Documentation
DUMMYAUDIO_CloseDevice()
void DUMMYAUDIO_CloseDevice (SDL_AudioDevice * device) static
{
    if (device->hidden) {
        // on Emscripten without threads, we just fire a repeating timer to consume audio.
        #if defined(SDL_PLATFORM_EMSCRIPTEN) && !defined(__EMSCRIPTEN_PTHREADS__)
        MAIN_THREAD_EM_ASM({
            var a = Module['SDL3'].dummy_audio;
            if (a.timers[$0] !== undefined) { clearInterval(a.timers[$0]); }
            a.timers[$0] = undefined;
        }, device->recording ? 1 : 0);
        #endif
        SDL_free(device->hidden->mixbuf);
        SDL_free(device->hidden);
        device->hidden = NULL;
    }
}
References SDL_AudioDevice::hidden, SDL_PrivateAudioData::mixbuf, NULL, SDL_AudioDevice::recording, and SDL_free().
Referenced by DUMMYAUDIO_Init().
DUMMYAUDIO_GetDeviceBuf()
Uint8 * DUMMYAUDIO_GetDeviceBuf (SDL_AudioDevice * device, int * buffer_size) static
{
    return device->hidden->mixbuf;
}
References SDL_AudioDevice::hidden, and SDL_PrivateAudioData::mixbuf.
Referenced by DUMMYAUDIO_Init().
DUMMYAUDIO_Init()
bool DUMMYAUDIO_Init (SDL_AudioDriverImpl * impl) static
{
    impl->OpenDevice = DUMMYAUDIO_OpenDevice;
    impl->CloseDevice = DUMMYAUDIO_CloseDevice;
    impl->WaitDevice = DUMMYAUDIO_WaitDevice;
    impl->GetDeviceBuf = DUMMYAUDIO_GetDeviceBuf;
    impl->WaitRecordingDevice = DUMMYAUDIO_WaitDevice;
    impl->RecordDevice = DUMMYAUDIO_RecordDevice;
    impl->OnlyHasDefaultPlaybackDevice = true;
    impl->OnlyHasDefaultRecordingDevice = true;
    impl->HasRecordingSupport = true;
    // on Emscripten without threads, we just fire a repeating timer to consume audio.
    #if defined(SDL_PLATFORM_EMSCRIPTEN) && !defined(__EMSCRIPTEN_PTHREADS__)
    MAIN_THREAD_EM_ASM({
        if (typeof(Module['SDL3']) === 'undefined') {
            Module['SDL3'] = {};
        }
        Module['SDL3'].dummy_audio = {};
        Module['SDL3'].dummy_audio.timers = [];
        Module['SDL3'].dummy_audio.timers[0] = undefined;
        Module['SDL3'].dummy_audio.timers[1] = undefined;
    });
    impl->ProvidesOwnCallbackThread = true;
    #endif
    return true;
}
References SDL_AudioDriverImpl::CloseDevice, DUMMYAUDIO_CloseDevice(), DUMMYAUDIO_GetDeviceBuf(), DUMMYAUDIO_OpenDevice(), DUMMYAUDIO_RecordDevice(), DUMMYAUDIO_WaitDevice(), SDL_AudioDriverImpl::GetDeviceBuf, SDL_AudioDriverImpl::HasRecordingSupport, SDL_AudioDriverImpl::OnlyHasDefaultPlaybackDevice, SDL_AudioDriverImpl::OnlyHasDefaultRecordingDevice, SDL_AudioDriverImpl::OpenDevice, SDL_AudioDriverImpl::ProvidesOwnCallbackThread, SDL_AudioDriverImpl::RecordDevice, SDL_AudioDriverImpl::WaitDevice, and SDL_AudioDriverImpl::WaitRecordingDevice.
DUMMYAUDIO_OpenDevice()
bool DUMMYAUDIO_OpenDevice (SDL_AudioDevice * device) static
{
    device->hidden = (struct SDL_PrivateAudioData *) SDL_calloc(1, sizeof(*device->hidden));
    if (!device->hidden) {
        return false;
    }
    if (!device->recording) {
        device->hidden->mixbuf = (Uint8 *) SDL_malloc(device->buffer_size);
        if (!device->hidden->mixbuf) {
            return false;
        }
    }
    device->hidden->io_delay = ((device->sample_frames * 1000) / device->spec.freq);
    const char *hint = SDL_GetHint(SDL_HINT_AUDIO_DUMMY_TIMESCALE);
    if (hint) {
        double scale = SDL_atof(hint);
        if (scale >= 0.0) {
            device->hidden->io_delay = (Uint32)SDL_round(device->hidden->io_delay * scale);
        }
    }
    // on Emscripten without threads, we just fire a repeating timer to consume audio.
    #if defined(SDL_PLATFORM_EMSCRIPTEN) && !defined(__EMSCRIPTEN_PTHREADS__)
    MAIN_THREAD_EM_ASM({
        var a = Module['SDL3'].dummy_audio;
        if (a.timers[$0] !== undefined) { clearInterval(a.timers[$0]); }
        a.timers[$0] = setInterval(function() { dynCall('vi', $3, [$4]); }, ($1 / $2) * 1000);
    }, device->recording ? 1 : 0, device->sample_frames, device->spec.freq, device->recording ? SDL_RecordingAudioThreadIterate : SDL_PlaybackAudioThreadIterate, device);
    #endif
    return true; // we're good; don't change reported device format.
}
References SDL_AudioDevice::buffer_size, SDL_AudioSpec::freq, SDL_AudioDevice::hidden, SDL_PrivateAudioData::io_delay, SDL_PrivateAudioData::mixbuf, SDL_AudioDevice::recording, SDL_AudioDevice::sample_frames, SDL_atof(), SDL_calloc(), SDL_GetHint(), SDL_HINT_AUDIO_DUMMY_TIMESCALE, SDL_malloc(), SDL_PlaybackAudioThreadIterate(), SDL_RecordingAudioThreadIterate(), SDL_round(), and SDL_AudioDevice::spec.
Referenced by DUMMYAUDIO_Init().
DUMMYAUDIO_RecordDevice()
int DUMMYAUDIO_RecordDevice (SDL_AudioDevice * device, void * buffer, int buflen) static
{
    // always return a full buffer of silence.
    SDL_memset(buffer, device->silence_value, buflen);
    return buflen;
}
References SDL_memset, and SDL_AudioDevice::silence_value.
Referenced by DUMMYAUDIO_Init().
DUMMYAUDIO_WaitDevice()
bool DUMMYAUDIO_WaitDevice (SDL_AudioDevice * device) static
{
    SDL_Delay(device->hidden->io_delay);
    return true;
}
References SDL_AudioDevice::hidden, SDL_PrivateAudioData::io_delay, and SDL_Delay().
Referenced by DUMMYAUDIO_Init().
Variable Documentation
DUMMYAUDIO_bootstrap
AudioBootStrap DUMMYAUDIO_bootstrap
Initial value:
= {
    "dummy", "SDL dummy audio driver", DUMMYAUDIO_Init, true, false
}
{
    "dummy", "SDL dummy audio driver", DUMMYAUDIO_Init, true, false
};