SDL3: SDL-main/src/dialog/unix/SDL_zenitydialog.c File Reference
SDL_zenitydialog.c File Reference
#include "SDL_internal.h"
#include "../SDL_dialog_utils.h"
Data Structures
struct zenityArgs
Macros
#define COPY_STRING_PROPERTY(dst, prop)
#define X11_HANDLE_MAX_WIDTH 28
Functions
static zenityArgs * create_zenity_args (SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props)
static void free_zenity_args (zenityArgs *args)
static bool get_x11_window_handle (SDL_PropertiesID props, char *out)
static void run_zenity (SDL_DialogFileCallback callback, void *userdata, void *argv)
static int run_zenity_thread (void *ptr)
bool SDL_Zenity_detect (void)
void SDL_Zenity_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props)
static char * zenity_clean_name (const char *name)
Macro Definition Documentation
COPY_STRING_PROPERTY
#define COPY_STRING_PROPERTY (dst, prop)
Value:
    {                                                               \
        const char *str = SDL_GetStringProperty(props, prop, NULL); \
        if (str) {                                                  \
            dst = SDL_strdup(str);                                  \
            if (!dst) {                                             \
                goto cleanup;                                       \
            }                                                       \
        }                                                           \
    }
Referenced by create_zenity_args().
X11_HANDLE_MAX_WIDTH
#define X11_HANDLE_MAX_WIDTH 28
Referenced by get_x11_window_handle().
Function Documentation
create_zenity_args()
zenityArgs * create_zenity_args (SDL_FileDialogType type, SDL_DialogFileCallback callback, void * userdata, SDL_PropertiesID props) static
{
    zenityArgs *args = SDL_calloc(1, sizeof(*args));
    if (!args) {
        return NULL;
    }
    args->callback = callback;
    args->userdata = userdata;
    args->nfilters = SDL_GetNumberProperty(props, SDL_PROP_FILE_DIALOG_NFILTERS_NUMBER, 0);
    const char **argv = SDL_malloc(
        sizeof(*argv) * (3   /* zenity --file-selection --separator=\n */
                         + 1 /* --multiple */
                         + 2 /* --directory | --save --confirm-overwrite */
                         + 2 /* --filename [file] */
                         + 3 /* --modal --attach [handle] */
                         + 2 /* --title [title] */
                         + 2 /* --ok-label [label] */
                         + 2 /* --cancel-label [label] */
                         + args->nfilters + 1 /* NULL */));
    if (!argv) {
        goto cleanup;
    }
    args->argv = argv;
    /* Properties can be destroyed as soon as the function returns; copy over what we need. */
#define COPY_STRING_PROPERTY(dst, prop)                             \
    {                                                               \
        const char *str = SDL_GetStringProperty(props, prop, NULL); \
        if (str) {                                                  \
            dst = SDL_strdup(str);                                  \
            if (!dst) {                                             \
                goto cleanup;                                       \
            }                                                       \
        }                                                           \
    }
    COPY_STRING_PROPERTY(args->filename, SDL_PROP_FILE_DIALOG_LOCATION_STRING);
    COPY_STRING_PROPERTY(args->title, SDL_PROP_FILE_DIALOG_TITLE_STRING);
    COPY_STRING_PROPERTY(args->accept, SDL_PROP_FILE_DIALOG_ACCEPT_STRING);
    COPY_STRING_PROPERTY(args->cancel, SDL_PROP_FILE_DIALOG_CANCEL_STRING);
#undef COPY_STRING_PROPERTY
    // ARGV PASS
    int argc = 0;
    argv[argc++] = "zenity";
    argv[argc++] = "--file-selection";
    argv[argc++] = "--separator=\n";
    if (SDL_GetBooleanProperty(props, SDL_PROP_FILE_DIALOG_MANY_BOOLEAN, false)) {
        argv[argc++] = "--multiple";
    }
    switch (type) {
    case SDL_FILEDIALOG_OPENFILE:
        break;
    case SDL_FILEDIALOG_SAVEFILE:
        argv[argc++] = "--save";
        /* Asking before overwriting while saving seems like a sane default */
        argv[argc++] = "--confirm-overwrite";
        break;
    case SDL_FILEDIALOG_OPENFOLDER:
        argv[argc++] = "--directory";
        break;
    };
    if (args->filename) {
        argv[argc++] = "--filename";
        argv[argc++] = args->filename;
    }
    if (get_x11_window_handle(props, args->x11_window_handle)) {
        argv[argc++] = "--modal";
        argv[argc++] = "--attach";
        argv[argc++] = args->x11_window_handle;
    }
    if (args->title) {
        argv[argc++] = "--title";
        argv[argc++] = args->title;
    }
    if (args->accept) {
        argv[argc++] = "--ok-label";
        argv[argc++] = args->accept;
    }
    if (args->cancel) {
        argv[argc++] = "--cancel-label";
        argv[argc++] = args->cancel;
    }
    const SDL_DialogFileFilter *filters = SDL_GetPointerProperty(props, SDL_PROP_FILE_DIALOG_FILTERS_POINTER, NULL);
    if (filters) {
        args->filters_slice = (char **)&argv[argc];
        for (int i = 0; i < args->nfilters; i++) {
            char *filter_str = convert_filter(filters[i],
                                              zenity_clean_name,
                                              "--file-filter=", " | ", "",
                                              "*.", " *.", "");
            if (!filter_str) {
                while (i--) {
                    SDL_free(args->filters_slice[i]);
                }
                goto cleanup;
            }
            args->filters_slice[i] = filter_str;
        }
        argc += args->nfilters;
    }
    argv[argc] = NULL;
    return args;
cleanup:
    SDL_free(args->filename);
    SDL_free(args->title);
    SDL_free(args->accept);
    SDL_free(args->cancel);
    SDL_free(argv);
    SDL_free(args);
    return NULL;
}
References zenityArgs::accept, zenityArgs::argv, zenityArgs::callback, zenityArgs::cancel, convert_filter(), COPY_STRING_PROPERTY, zenityArgs::filename, zenityArgs::filters_slice, get_x11_window_handle(), zenityArgs::nfilters, NULL, SDL_calloc(), SDL_FILEDIALOG_OPENFILE, SDL_FILEDIALOG_OPENFOLDER, SDL_FILEDIALOG_SAVEFILE, SDL_free(), SDL_GetBooleanProperty(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_malloc(), SDL_PROP_FILE_DIALOG_ACCEPT_STRING, SDL_PROP_FILE_DIALOG_CANCEL_STRING, SDL_PROP_FILE_DIALOG_FILTERS_POINTER, SDL_PROP_FILE_DIALOG_LOCATION_STRING, SDL_PROP_FILE_DIALOG_MANY_BOOLEAN, SDL_PROP_FILE_DIALOG_NFILTERS_NUMBER, SDL_PROP_FILE_DIALOG_TITLE_STRING, zenityArgs::title, zenityArgs::userdata, zenityArgs::x11_window_handle, and zenity_clean_name().
Referenced by SDL_Zenity_ShowFileDialogWithProperties().
free_zenity_args()
void free_zenity_args (zenityArgs * args) static
{
    if (args->filters_slice) {
        for (int i = 0; i < args->nfilters; i++) {
            SDL_free(args->filters_slice[i]);
        }
    }
    SDL_free(args->filename);
    SDL_free(args->title);
    SDL_free(args->accept);
    SDL_free(args->cancel);
    SDL_free(args->argv);
    SDL_free(args);
}
References zenityArgs::accept, zenityArgs::argv, zenityArgs::cancel, zenityArgs::filename, zenityArgs::filters_slice, zenityArgs::nfilters, SDL_free(), and zenityArgs::title.
Referenced by run_zenity_thread(), and SDL_Zenity_ShowFileDialogWithProperties().
get_x11_window_handle()
bool get_x11_window_handle (SDL_PropertiesID props, char * out) static
{
    SDL_Window *window = SDL_GetPointerProperty(props, SDL_PROP_FILE_DIALOG_WINDOW_POINTER, NULL);
    if (!window) {
        return false;
    }
    SDL_PropertiesID window_props = SDL_GetWindowProperties(window);
    if (!window_props) {
        return false;
    }
    Uint64 handle = (Uint64)SDL_GetNumberProperty(window_props, SDL_PROP_WINDOW_X11_WINDOW_NUMBER, 0);
    if (!handle) {
        return false;
    }
    if (SDL_snprintf(out, X11_HANDLE_MAX_WIDTH, "0x%" SDL_PRIx64, handle) >= X11_HANDLE_MAX_WIDTH) {
        return false;
    };
    return true;
}
References NULL, SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetWindowProperties(), SDL_PRIx64, SDL_PROP_FILE_DIALOG_WINDOW_POINTER, SDL_PROP_WINDOW_X11_WINDOW_NUMBER, SDL_snprintf(), and X11_HANDLE_MAX_WIDTH.
Referenced by create_zenity_args().
run_zenity()
void run_zenity (SDL_DialogFileCallback callback, void * userdata, void * argv) static
{
    SDL_Process *process = NULL;
    SDL_Environment *env = NULL;
    int status = -1;
    size_t bytes_read = 0;
    char *container = NULL;
    size_t narray = 1;
    char **array = NULL;
    bool result = false;
    env = SDL_CreateEnvironment(true);
    if (!env) {
        goto done;
    }
    /* Recent versions of Zenity have different exit codes, but picks up
      different codes from the environment */
    SDL_SetEnvironmentVariable(env, "ZENITY_OK", "0", true);
    SDL_SetEnvironmentVariable(env, "ZENITY_CANCEL", "1", true);
    SDL_SetEnvironmentVariable(env, "ZENITY_ESC", "1", true);
    SDL_SetEnvironmentVariable(env, "ZENITY_EXTRA", "2", true);
    SDL_SetEnvironmentVariable(env, "ZENITY_ERROR", "2", true);
    SDL_SetEnvironmentVariable(env, "ZENITY_TIMEOUT", "2", true);
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, argv);
    SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER, env);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROCESS_STDIO_NULL);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_PROCESS_STDIO_APP);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDERR_NUMBER, SDL_PROCESS_STDIO_NULL);
    process = SDL_CreateProcessWithProperties(props);
    SDL_DestroyProperties(props);
    if (!process) {
        goto done;
    }
    container = SDL_ReadProcess(process, &bytes_read, &status);
    if (!container) {
        goto done;
    }
    array = (char **)SDL_malloc((narray + 1) * sizeof(char *));
    if (!array) {
        goto done;
    }
    array[0] = container;
    array[1] = NULL;
    for (int i = 0; i < bytes_read; i++) {
        if (container[i] == '\n') {
            container[i] = '\0';
            // Reading from a process often leaves a trailing \n, so ignore the last one
            if (i < bytes_read - 1) {
                array[narray] = container + i + 1;
                narray++;
                char **new_array = (char **)SDL_realloc(array, (narray + 1) * sizeof(char *));
                if (!new_array) {
                    goto done;
                }
                array = new_array;
                array[narray] = NULL;
            }
        }
    }
    // 0 = the user chose one or more files, 1 = the user canceled the dialog
    if (status == 0 || status == 1) {
        callback(userdata, (const char *const *)array, -1);
    } else {
        SDL_SetError("Could not run zenity: exit code %d", status);
        callback(userdata, NULL, -1);
    }
    result = true;
done:
    SDL_free(array);
    SDL_free(container);
    SDL_DestroyEnvironment(env);
    SDL_DestroyProcess(process);
    if (!result) {
        callback(userdata, NULL, -1);
    }
}
References NULL, SDL_CreateEnvironment(), SDL_CreateProcessWithProperties(), SDL_CreateProperties(), SDL_DestroyEnvironment(), SDL_DestroyProcess(), SDL_DestroyProperties(), SDL_free(), SDL_malloc(), SDL_PROCESS_STDIO_APP, SDL_PROCESS_STDIO_NULL, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER, SDL_PROP_PROCESS_CREATE_STDERR_NUMBER, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_ReadProcess(), SDL_realloc(), SDL_SetEnvironmentVariable(), SDL_SetError(), SDL_SetNumberProperty(), and SDL_SetPointerProperty().
Referenced by run_zenity_thread().
run_zenity_thread()
int run_zenity_thread (void * ptr) static
{
    zenityArgs *args = ptr;
    run_zenity(args->callback, args->userdata, args->argv);
    free_zenity_args(args);
    return 0;
}
References zenityArgs::argv, zenityArgs::callback, free_zenity_args(), run_zenity(), and zenityArgs::userdata.
Referenced by SDL_Zenity_ShowFileDialogWithProperties().
SDL_Zenity_detect()
bool SDL_Zenity_detect (void)
Returns
non-zero if available, zero if unavailable
{
    const char *args[] = {
        "zenity", "--version", NULL
    };
    int status = -1;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, args);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROCESS_STDIO_NULL);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_PROCESS_STDIO_NULL);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDERR_NUMBER, SDL_PROCESS_STDIO_NULL);
    SDL_Process *process = SDL_CreateProcessWithProperties(props);
    SDL_DestroyProperties(props);
    if (process) {
        SDL_WaitProcess(process, true, &status);
        SDL_DestroyProcess(process);
    }
    return (status == 0);
}
References NULL, SDL_CreateProcessWithProperties(), SDL_CreateProperties(), SDL_DestroyProcess(), SDL_DestroyProperties(), SDL_PROCESS_STDIO_NULL, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, SDL_PROP_PROCESS_CREATE_STDERR_NUMBER, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_SetNumberProperty(), SDL_SetPointerProperty(), and SDL_WaitProcess().
Referenced by detect_available_methods().
SDL_Zenity_ShowFileDialogWithProperties()
void SDL_Zenity_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void * userdata, SDL_PropertiesID props)
{
    zenityArgs *args = create_zenity_args(type, callback, userdata, props);
    if (!args) {
        callback(userdata, NULL, -1);
        return;
    }
    SDL_Thread *thread = SDL_CreateThread(run_zenity_thread, "SDL_ZenityFileDialog", (void *)args);
    if (!thread) {
        free_zenity_args(args);
        callback(userdata, NULL, -1);
        return;
    }
    SDL_DetachThread(thread);
}
References create_zenity_args(), free_zenity_args(), NULL, run_zenity_thread(), SDL_CreateThread, and SDL_DetachThread().
Referenced by detect_available_methods().
zenity_clean_name()
char * zenity_clean_name (const char * name) static
{
    char *newname = SDL_strdup(name);
    /* Filter out "|", which Zenity considers a special character. Let's hope
       there aren't others. TODO: find something better. */
    for (char *c = newname; *c; c++) {
        if (*c == '|') {
            // Zenity doesn't support escaping with '\'
            *c = '/';
        }
    }
    return newname;
}
References SDL_strdup().
Referenced by create_zenity_args().