SDL3: SDL-main/include/SDL3/SDL_timer.h File Reference
SDL_timer.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDL_MS_PER_SECOND 1000
#define SDL_MS_TO_NS(MS)
#define SDL_NS_PER_MS 1000000
#define SDL_NS_PER_SECOND 1000000000LL
#define SDL_NS_PER_US 1000
#define SDL_NS_TO_MS(NS)
#define SDL_NS_TO_SECONDS(NS)
#define SDL_NS_TO_US(NS)
#define SDL_SECONDS_TO_NS(S)
#define SDL_US_PER_SECOND 1000000
#define SDL_US_TO_NS(US)
Typedefs
typedef Uint64(SDLCALL * SDL_NSTimerCallback) (void *userdata, SDL_TimerID timerID, Uint64 interval)
typedef Uint32(SDLCALL * SDL_TimerCallback) (void *userdata, SDL_TimerID timerID, Uint32 interval)
typedef Uint32 SDL_TimerID
Functions
SDL_DECLSPEC SDL_TimerID SDLCALL SDL_AddTimer (Uint32 interval, SDL_TimerCallback callback, void *userdata)
SDL_DECLSPEC SDL_TimerID SDLCALL SDL_AddTimerNS (Uint64 interval, SDL_NSTimerCallback callback, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_Delay (Uint32 ms)
SDL_DECLSPEC void SDLCALL SDL_DelayNS (Uint64 ns)
SDL_DECLSPEC void SDLCALL SDL_DelayPrecise (Uint64 ns)
SDL_DECLSPEC Uint64 SDLCALL SDL_GetPerformanceCounter (void)
SDL_DECLSPEC Uint64 SDLCALL SDL_GetPerformanceFrequency (void)
SDL_DECLSPEC Uint64 SDLCALL SDL_GetTicks (void)
SDL_DECLSPEC Uint64 SDLCALL SDL_GetTicksNS (void)
SDL_DECLSPEC bool SDLCALL SDL_RemoveTimer (SDL_TimerID id)
Macro Definition Documentation
SDL_MS_PER_SECOND
#define SDL_MS_PER_SECOND 1000
CategoryTimer
SDL provides time management functionality. It is useful for dealing with (usually) small durations of time.
This is not to be confused with calendar time management, which is provided by [CategoryTime](CategoryTime).
This category covers measuring time elapsed (SDL_GetTicks(), SDL_GetPerformanceCounter()), putting a thread to sleep for a certain amount of time (SDL_Delay(), SDL_DelayNS(), SDL_DelayPrecise()), and firing a callback function after a certain amount of time has elasped (SDL_AddTimer(), etc).
There are also useful macros to convert between time units, like SDL_SECONDS_TO_NS() and such. Number of milliseconds in a second.
This is always 1000.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_InitTicks().
SDL_MS_TO_NS
#define SDL_MS_TO_NS (MS)
Value:
(((Uint64)(MS)) * SDL_NS_PER_MS)
Convert milliseconds to nanoseconds.
This only converts whole numbers, not fractional milliseconds.
Parameters
MS the number of milliseconds to convert.
Returns
MS, expressed in nanoseconds.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by hidapi_thread_addtime(), SDL_AddTimer(), SDL_Delay(), SDL_SimulateRenderVSync(), SDL_TimerThread(), SDL_WaitConditionTimeout(), SDL_WaitEventTimeout(), and SDL_WaitSemaphoreTimeout().
SDL_NS_PER_MS
#define SDL_NS_PER_MS 1000000
Number of nanoseconds in a millisecond.
This is always 1000000.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_DelayPrecise(), and SDL_IOReady().
SDL_NS_PER_SECOND
#define SDL_NS_PER_SECOND 1000000000LL
Number of nanoseconds in a second.
This is always 1000000000.
Since
This macro is available since SDL 3.2.0.
Referenced by MainCallbackRateHintChanged(), SDL_CalculateSimulatedVSyncInterval(), SDL_DateTimeIsValid(), SDL_InitTicks(), SDL_IOReady(), SDL_WaitConditionTimeoutNS(), and SDL_WaitSemaphoreTimeoutNS().
SDL_NS_PER_US
#define SDL_NS_PER_US 1000
Number of nanoseconds in a microsecond.
This is always 1000.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_IOReady().
SDL_NS_TO_MS
#define SDL_NS_TO_MS (NS)
Value:
((NS) / SDL_NS_PER_MS)
Convert nanoseconds to milliseconds.
This performs a division, so the results can be dramatically different if NS is an integer or floating point value.
Parameters
NS the number of nanoseconds to convert.
Returns
NS, expressed in milliseconds.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by hidapi_thread_cond_timedwait(), MainCallbackRateHintChanged(), SDL_IOReady(), SDL_TimerThread(), and SDL_WaitConditionTimeoutNS_cv().
SDL_NS_TO_SECONDS
#define SDL_NS_TO_SECONDS (NS)
Value:
((NS) / SDL_NS_PER_SECOND)
Convert nanoseconds to seconds.
This performs a division, so the results can be dramatically different if NS is an integer or floating point value.
Parameters
NS the number of nanoseconds to convert.
Returns
NS, expressed in seconds.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_DateTimeToTime().
SDL_NS_TO_US
#define SDL_NS_TO_US (NS)
Value:
((NS) / SDL_NS_PER_US)
Convert nanoseconds to microseconds.
This performs a division, so the results can be dramatically different if NS is an integer or floating point value.
Parameters
NS the number of nanoseconds to convert.
Returns
NS, expressed in microseconds.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_IOReady(), and SDL_SYS_DelayNS().
SDL_SECONDS_TO_NS
#define SDL_SECONDS_TO_NS (S)
Value:
(((Uint64)(S)) * SDL_NS_PER_SECOND)
Convert seconds to nanoseconds.
This only converts whole numbers, not fractional seconds.
Parameters
S the number of seconds to convert.
Returns
S, expressed in nanoseconds.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_DateTimeToTime().
SDL_US_PER_SECOND
#define SDL_US_PER_SECOND 1000000
Number of microseconds in a second.
This is always 1000000.
Since
This macro is available since SDL 3.2.0.
SDL_US_TO_NS
#define SDL_US_TO_NS (US)
Value:
(((Uint64)(US)) * SDL_NS_PER_US)
Convert microseconds to nanoseconds.
This only converts whole numbers, not fractional microseconds.
Parameters
US the number of microseconds to convert.
Returns
US, expressed in nanoseconds.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_WaitConditionTimeoutNS(), and SDL_WaitSemaphoreTimeoutNS().
Typedef Documentation
SDL_NSTimerCallback
typedef Uint64(SDLCALL * SDL_NSTimerCallback) (void *userdata, SDL_TimerID timerID, Uint64 interval)
Function prototype for the nanosecond timer callback function.
The callback function is passed the current timer interval and returns the next timer interval, in nanoseconds. If the returned value is the same as the one passed in, the periodic alarm continues, otherwise a new alarm is scheduled. If the callback returns 0, the periodic alarm is canceled and will be removed.
Parameters
userdata an arbitrary pointer provided by the app through SDL_AddTimer, for its own use.
timerID the current timer being processed.
interval the current callback time interval.
Returns
the new callback time interval, or 0 to disable further runs of the callback.
Thread Safety
SDL may call this callback at any time from a background thread; the application is responsible for locking resources the callback touches that need to be protected.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_AddTimerNS
SDL_TimerCallback
typedef Uint32(SDLCALL * SDL_TimerCallback) (void *userdata, SDL_TimerID timerID, Uint32 interval)
Function prototype for the millisecond timer callback function.
The callback function is passed the current timer interval and returns the next timer interval, in milliseconds. If the returned value is the same as the one passed in, the periodic alarm continues, otherwise a new alarm is scheduled. If the callback returns 0, the periodic alarm is canceled and will be removed.
Parameters
userdata an arbitrary pointer provided by the app through SDL_AddTimer, for its own use.
timerID the current timer being processed.
interval the current callback time interval.
Returns
the new callback time interval, or 0 to disable further runs of the callback.
Thread Safety
SDL may call this callback at any time from a background thread; the application is responsible for locking resources the callback touches that need to be protected.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_AddTimer
SDL_TimerID
typedef Uint32 SDL_TimerID
Definition of the timer ID type.
Since
This datatype is available since SDL 3.2.0.
Function Documentation
SDL_AddTimer()
SDL_DECLSPEC SDL_TimerID SDLCALL SDL_AddTimer (Uint32 interval, SDL_TimerCallback callback, void * userdata) extern
Call a callback function at a future time.
The callback function is passed the current timer interval and the user supplied parameter from the SDL_AddTimer() call and should return the next timer interval. If the value returned from the callback is 0, the timer is canceled and will be removed.
The callback is run on a separate thread, and for short timeouts can potentially be called before this function returns.
Timers take into account the amount of time it took to execute the callback. For example, if the callback took 250 ms to execute and returned 1000 (ms), the timer would only wait another 750 ms before its next iteration.
Timing may be inexact due to OS scheduling. Be sure to note the current time with SDL_GetTicksNS() or SDL_GetPerformanceCounter() in case your callback needs to adjust for variances.
Parameters
interval the timer delay, in milliseconds, passed to callback.
callback the SDL_TimerCallback function to call when the specified interval elapses.
userdata a pointer that is passed to callback.
Returns
a timer ID or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddTimerNS
SDL_RemoveTimer
{
    return SDL_CreateTimer(SDL_MS_TO_NS(interval), callback, NULL, userdata);
}
References NULL, SDL_CreateTimer(), and SDL_MS_TO_NS.
SDL_AddTimerNS()
SDL_DECLSPEC SDL_TimerID SDLCALL SDL_AddTimerNS (Uint64 interval, SDL_NSTimerCallback callback, void * userdata) extern
Call a callback function at a future time.
The callback function is passed the current timer interval and the user supplied parameter from the SDL_AddTimerNS() call and should return the next timer interval. If the value returned from the callback is 0, the timer is canceled and will be removed.
The callback is run on a separate thread, and for short timeouts can potentially be called before this function returns.
Timers take into account the amount of time it took to execute the callback. For example, if the callback took 250 ns to execute and returned 1000 (ns), the timer would only wait another 750 ns before its next iteration.
Timing may be inexact due to OS scheduling. Be sure to note the current time with SDL_GetTicksNS() or SDL_GetPerformanceCounter() in case your callback needs to adjust for variances.
Parameters
interval the timer delay, in nanoseconds, passed to callback.
callback the SDL_TimerCallback function to call when the specified interval elapses.
userdata a pointer that is passed to callback.
Returns
a timer ID or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddTimer
SDL_RemoveTimer
{
    return SDL_CreateTimer(interval, NULL, callback, userdata);
}
References NULL, and SDL_CreateTimer().
SDL_Delay()
SDL_DECLSPEC void SDLCALL SDL_Delay (Uint32 ms) extern
Wait a specified number of milliseconds before returning.
This function waits a specified number of milliseconds before returning. It waits at least the specified time, but possibly longer due to OS scheduling.
Parameters
ms the number of milliseconds to delay.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DelayNS
SDL_DelayPrecise
{
    SDL_SYS_DelayNS(SDL_MS_TO_NS(ms));
}
References SDL_MS_TO_NS, and SDL_SYS_DelayNS().
Referenced by DUMMYAUDIO_WaitDevice(), SDL_DestroySemaphore(), SDL_LoadFile_IO(), SDL_LockSpinlock(), SDL_PlaybackAudioThreadShutdown(), SDL_SaveFile_IO(), SDL_ShouldInit(), SDL_ShouldQuit(), ZombieWaitDevice(), and ZombieWaitDevice().
SDL_DelayNS()
SDL_DECLSPEC void SDLCALL SDL_DelayNS (Uint64 ns) extern
Wait a specified number of nanoseconds before returning.
This function waits a specified number of nanoseconds before returning. It waits at least the specified time, but possibly longer due to OS scheduling.
Parameters
ns the number of nanoseconds to delay.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Delay
SDL_DelayPrecise
{
    SDL_SYS_DelayNS(ns);
}
References SDL_SYS_DelayNS().
Referenced by SDL_WaitEventTimeoutNS(), and SDL_WaitSemaphoreTimeoutNS().
SDL_DelayPrecise()
SDL_DECLSPEC void SDLCALL SDL_DelayPrecise (Uint64 ns) extern
Wait a specified number of nanoseconds before returning.
This function waits a specified number of nanoseconds before returning. It will attempt to wait as close to the requested time as possible, busy waiting if necessary, but could return later due to OS scheduling.
Parameters
ns the number of nanoseconds to delay.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Delay
SDL_DelayNS
{
    Uint64 current_value = SDL_GetTicksNS();
    const Uint64 target_value = current_value + ns;
    // Sleep for a short number of cycles when real sleeps are desired.
    // We'll use 1 ms, it's the minimum guaranteed to produce real sleeps across
    // all platforms.
    const Uint64 SHORT_SLEEP_NS = 1 * SDL_NS_PER_MS;
    // Try to sleep short of target_value. If for some crazy reason
    // a particular platform sleeps for less than 1 ms when 1 ms was requested,
    // that's fine, the code below can cope with that, but in practice no
    // platforms behave that way.
    Uint64 max_sleep_ns = SHORT_SLEEP_NS;
    while (current_value + max_sleep_ns < target_value) {
        // Sleep for a short time
        SDL_SYS_DelayNS(SHORT_SLEEP_NS);
        const Uint64 now = SDL_GetTicksNS();
        const Uint64 next_sleep_ns = (now - current_value);
        if (next_sleep_ns > max_sleep_ns) {
            max_sleep_ns = next_sleep_ns;
        }
        current_value = now;
    }
    // Do a shorter sleep of the remaining time here, less the max overshoot in
    // the first loop. Due to maintaining max_sleep_ns as
    // greater-than-or-equal-to-1 ms, we can always subtract off 1 ms to get
    // the duration overshot beyond a 1 ms sleep request; if the system never
    // overshot, great, it's zero duration. By choosing the max overshoot
    // amount, we're likely to not overshoot here. If the sleep here ends up
    // functioning like SDL_DelayNS(0) internally, that's fine, we just don't
    // get to do a more-precise-than-1 ms-resolution sleep to undershoot by a
    // small amount on the current system, but SDL_DelayNS(0) does at least
    // introduce a small, yielding delay on many platforms, better than an
    // unyielding busyloop.
    //
    // Note that we'll always do at least one sleep in this function, so the
    // minimum resolution will be that of SDL_SYS_DelayNS()
    if (current_value < target_value && (target_value - current_value) > (max_sleep_ns - SHORT_SLEEP_NS)) {
        const Uint64 delay_ns = (target_value - current_value) - (max_sleep_ns - SHORT_SLEEP_NS);
        SDL_SYS_DelayNS(delay_ns);
        current_value = SDL_GetTicksNS();
    }
    // We've likely undershot target_value at this point by a pretty small
    // amount, but maybe not. The footgun case if not handled here is where
    // we've undershot by a large amount, like several ms, but still smaller
    // than the amount max_sleep_ns overshot by; in such a situation, the above
    // shorter-sleep block didn't do any delay, the if-block wasn't entered.
    // Also, maybe the shorter-sleep undershot by several ms, so we still don't
    // want to spin a lot then. In such a case, we accept the possibility of
    // overshooting to not spin much, or if overshot here, not at all, keeping
    // CPU/power usage down in any case. Due to scheduler sloppiness, it's
    // entirely possible to end up undershooting/overshooting here by much less
    // than 1 ms even if the current system's sleep function is only 1
    // ms-resolution, as SDL_GetTicksNS() generally is better resolution than 1
    // ms on the systems SDL supports.
    while (current_value + SHORT_SLEEP_NS < target_value) {
        SDL_SYS_DelayNS(SHORT_SLEEP_NS);
        current_value = SDL_GetTicksNS();
    }
    // Spin for any remaining time
    while (current_value < target_value) {
        SDL_CPUPauseInstruction();
        current_value = SDL_GetTicksNS();
    }
}
References SDL_CPUPauseInstruction, SDL_GetTicksNS(), SDL_NS_PER_MS, and SDL_SYS_DelayNS().
Referenced by SDL_EnterAppMainCallbacks(), and SDL_SimulateRenderVSync().
SDL_GetPerformanceCounter()
SDL_DECLSPEC Uint64 SDLCALL SDL_GetPerformanceCounter (void) extern
Get the current value of the high resolution counter.
This function is typically used for profiling.
The counter values are only meaningful relative to each other. Differences between values can be converted to times by using SDL_GetPerformanceFrequency().
Returns
the current counter value.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPerformanceFrequency
{
    return static_cast<Uint64>(User::TickCount());
}
Referenced by SDL_GetTicks(), SDL_GetTicksNS(), SDL_InitTicks(), and SDL_srand().
SDL_GetPerformanceFrequency()
SDL_DECLSPEC Uint64 SDLCALL SDL_GetPerformanceFrequency (void) extern
Get the count per second of the high resolution counter.
Returns
a platform-specific count per second.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPerformanceCounter
{
    // On Symbian S60v1, tick frequency is 64 Hz => 1 tick = 15,625 microseconds.
    return 64;
}
Referenced by SDL_InitTicks().
SDL_GetTicks()
SDL_DECLSPEC Uint64 SDLCALL SDL_GetTicks (void) extern
Get the number of milliseconds that have elapsed since the SDL library initialization.
Returns
an unsigned 64bit integer that represents the number of milliseconds that have elapsed since the SDL library was initialized (typically via a call to SDL_Init).
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTicksNS
{
    Uint64 starting_value, value;
    if (!tick_start) {
        SDL_InitTicks();
    }
    starting_value = (SDL_GetPerformanceCounter() - tick_start);
    value = (starting_value * tick_numerator_ms);
    SDL_assert(value >= starting_value);
    value /= tick_denominator_ms;
    return value;
}
References SDL_assert, SDL_GetPerformanceCounter(), SDL_InitTicks(), tick_denominator_ms, tick_numerator_ms, and tick_start.
Referenced by HIDAPI_UpdateDiscovery(), IOS_JoystickOpen(), IOS_MFIJoystickUpdate(), SDL_OpenJoystick(), SDL_PrivateSendMouseButton(), SDL_ReleaseAutoReleaseKeys(), SDL_RumbleJoystick(), SDL_RumbleJoystickTriggers(), SDL_SendGamepadButton(), SDL_SendKeyboardKeyInternal(), SDL_SetJoystickLED(), SDL_UpdateJoysticks(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_GetTicksNS()
SDL_DECLSPEC Uint64 SDLCALL SDL_GetTicksNS (void) extern
Get the number of nanoseconds since SDL library initialization.
Returns
an unsigned 64-bit value representing the number of nanoseconds since the SDL library initialized.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    Uint64 starting_value, value;
    if (!tick_start) {
        SDL_InitTicks();
    }
    starting_value = (SDL_GetPerformanceCounter() - tick_start);
    value = (starting_value * tick_numerator_ns);
    SDL_assert(value >= starting_value);
    value /= tick_denominator_ns;
    return value;
}
References SDL_assert, SDL_GetPerformanceCounter(), SDL_InitTicks(), tick_denominator_ns, tick_numerator_ns, and tick_start.
Referenced by GetEventTimestamp(), GetEventTimestamp(), hidapi_thread_cond_timedwait(), hidapi_thread_gettime(), IOS_MFIJoystickUpdate(), RecenterGamepad(), SDL_CameraThreadIterate(), SDL_CreateTimer(), SDL_DelayPrecise(), SDL_DeviceNotificationFunc(), SDL_EnterAppMainCallbacks(), SDL_GamepadHandleDelayedGuideButton(), SDL_MaybeEnableWarpEmulation(), SDL_PrivateJoystickForceRecentering(), SDL_PushEvent(), SDL_SimulateRenderVSync(), SDL_TimerThread(), SDL_WaitEventTimeout_Device(), SDL_WaitEventTimeoutNS(), SDL_WaitSemaphoreTimeoutNS(), and ZombieAcquireFrame().
SDL_RemoveTimer()
SDL_DECLSPEC bool SDLCALL SDL_RemoveTimer (SDL_TimerID id) extern
Remove a timer created with SDL_AddTimer().
Parameters
id the ID of the timer to remove.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddTimer
{
    SDL_TimerData *data = &SDL_timer_data;
    SDL_TimerMap *prev, *entry;
    bool canceled = false;
    if (!id) {
        return SDL_InvalidParamError("id");
    }
    // Find the timer
    SDL_LockMutex(data->timermap_lock);
    prev = NULL;
    for (entry = data->timermap; entry; prev = entry, entry = entry->next) {
        if (entry->timerID == id) {
            if (prev) {
                prev->next = entry->next;
            } else {
                data->timermap = entry->next;
            }
            break;
        }
    }
    SDL_UnlockMutex(data->timermap_lock);
    if (entry) {
        if (!SDL_GetAtomicInt(&entry->timer->canceled)) {
            SDL_SetAtomicInt(&entry->timer->canceled, 1);
            canceled = true;
        }
        SDL_free(entry);
    }
    if (canceled) {
        return true;
    } else {
        return SDL_SetError("Timer not found");
    }
}
References SDL_Timer::canceled, SDL_TimerMap::next, NULL, SDL_free(), SDL_GetAtomicInt(), SDL_InvalidParamError, SDL_LockMutex(), SDL_SetAtomicInt(), SDL_SetError(), SDL_timer_data, SDL_UnlockMutex(), SDL_TimerMap::timer, and SDL_TimerMap::timerID.
Referenced by SDL_CreateTimer().