SDL3: SDL-main/src/timer/SDL_timer_c.h File Reference
SDL_timer_c.h File Reference
#include "SDL_internal.h"
Macros
#define ROUND_RESOLUTION(X)
Functions
void SDL_InitTicks (void)
bool SDL_InitTimers (void)
void SDL_QuitTicks (void)
void SDL_QuitTimers (void)
void SDL_SYS_DelayNS (Uint64 ns)
Macro Definition Documentation
ROUND_RESOLUTION
#define ROUND_RESOLUTION (X)
Value:
    (((X + TIMER_RESOLUTION - 1) / TIMER_RESOLUTION) * TIMER_RESOLUTION)
#define ROUND_RESOLUTION(X) \
    (((X + TIMER_RESOLUTION - 1) / TIMER_RESOLUTION) * TIMER_RESOLUTION)
Function Documentation
SDL_InitTicks()
void SDL_InitTicks (void) extern
{
    Uint64 tick_freq;
    Uint32 gcd;
    if (tick_start) {
        return;
    }
    /* If we didn't set a precision, set it high. This affects lots of things
       on Windows besides the SDL timers, like audio callbacks, etc. */
    SDL_AddHintCallback(SDL_HINT_TIMER_RESOLUTION,
                        SDL_TimerResolutionChanged, NULL);
    tick_freq = SDL_GetPerformanceFrequency();
    SDL_assert(tick_freq > 0 && tick_freq <= (Uint64)SDL_MAX_UINT32);
    gcd = SDL_CalculateGCD(SDL_NS_PER_SECOND, (Uint32)tick_freq);
    tick_numerator_ns = (SDL_NS_PER_SECOND / gcd);
    tick_denominator_ns = (Uint32)(tick_freq / gcd);
    gcd = SDL_CalculateGCD(SDL_MS_PER_SECOND, (Uint32)tick_freq);
    tick_numerator_ms = (SDL_MS_PER_SECOND / gcd);
    tick_denominator_ms = (Uint32)(tick_freq / gcd);
    tick_start = SDL_GetPerformanceCounter();
    if (!tick_start) {
        --tick_start;
    }
}
References NULL, SDL_AddHintCallback(), SDL_assert, SDL_CalculateGCD(), SDL_GetPerformanceCounter(), SDL_GetPerformanceFrequency(), SDL_HINT_TIMER_RESOLUTION, SDL_MAX_UINT32, SDL_MS_PER_SECOND, SDL_NS_PER_SECOND, SDL_TimerResolutionChanged(), tick_denominator_ms, tick_denominator_ns, tick_numerator_ms, tick_numerator_ns, and tick_start.
Referenced by SDL_GetTicks(), SDL_GetTicksNS(), SDL_InitMainThread(), and SDL_VideoInit().
SDL_InitTimers()
bool SDL_InitTimers (void) extern
{
    SDL_TimerData *data = &SDL_timer_data;
    if (!SDL_ShouldInit(&data->init)) {
        return true;
    }
    data->timermap_lock = SDL_CreateMutex();
    if (!data->timermap_lock) {
        goto error;
    }
    data->sem = SDL_CreateSemaphore(0);
    if (!data->sem) {
        goto error;
    }
    SDL_SetAtomicInt(&data->active, true);
    // Timer threads use a callback into the app, so we can't set a limited stack size here.
    data->thread = SDL_CreateThread(SDL_TimerThread, "SDLTimer", data);
    if (!data->thread) {
        goto error;
    }
    SDL_SetInitialized(&data->init, true);
    return true;
error:
    SDL_SetInitialized(&data->init, true);
    SDL_QuitTimers();
    return false;
}
References SDL_CreateMutex(), SDL_CreateSemaphore(), SDL_CreateThread, SDL_QuitTimers(), SDL_SetAtomicInt(), SDL_SetInitialized(), SDL_ShouldInit(), SDL_timer_data, and SDL_TimerThread().
Referenced by SDL_CheckInitTimers().
SDL_QuitTicks()
void SDL_QuitTicks (void) extern
{
    SDL_RemoveHintCallback(SDL_HINT_TIMER_RESOLUTION,
                        SDL_TimerResolutionChanged, NULL);
    SDL_SetSystemTimerResolutionMS(0); // always release our timer resolution request.
    tick_start = 0;
}
References NULL, SDL_HINT_TIMER_RESOLUTION, SDL_RemoveHintCallback(), SDL_SetSystemTimerResolutionMS(), SDL_TimerResolutionChanged(), and tick_start.
Referenced by SDL_QuitMainThread().
SDL_QuitTimers()
void SDL_QuitTimers (void) extern
{
    SDL_TimerData *data = &SDL_timer_data;
    SDL_Timer *timer;
    SDL_TimerMap *entry;
    if (!SDL_ShouldQuit(&data->init)) {
        return;
    }
    SDL_SetAtomicInt(&data->active, false);
    // Shutdown the timer thread
    if (data->thread) {
        SDL_SignalSemaphore(data->sem);
        SDL_WaitThread(data->thread, NULL);
        data->thread = NULL;
    }
    if (data->sem) {
        SDL_DestroySemaphore(data->sem);
        data->sem = NULL;
    }
    // Clean up the timer entries
    while (data->timers) {
        timer = data->timers;
        data->timers = timer->next;
        SDL_free(timer);
    }
    while (data->freelist) {
        timer = data->freelist;
        data->freelist = timer->next;
        SDL_free(timer);
    }
    while (data->timermap) {
        entry = data->timermap;
        data->timermap = entry->next;
        SDL_free(entry);
    }
    if (data->timermap_lock) {
        SDL_DestroyMutex(data->timermap_lock);
        data->timermap_lock = NULL;
    }
    SDL_SetInitialized(&data->init, false);
}
References SDL_Timer::next, SDL_TimerMap::next, NULL, SDL_DestroyMutex(), SDL_DestroySemaphore(), SDL_free(), SDL_SetAtomicInt(), SDL_SetInitialized(), SDL_ShouldQuit(), SDL_SignalSemaphore(), SDL_timer_data, SDL_WaitThread(), and SDL_TimerMap::timer.
Referenced by SDL_InitTimers(), and SDL_Quit().
SDL_SYS_DelayNS()
void SDL_SYS_DelayNS (Uint64 ns) extern
{
    User::After(SDL_NS_TO_US(ns));
}
References SDL_NS_TO_US.
Referenced by SDL_Delay(), SDL_DelayNS(), and SDL_DelayPrecise().