SDL3: SDL-main/src/core/SDL_core_unsupported.c File Reference
SDL_core_unsupported.c File Reference
#include "SDL_internal.h"
Typedefs
typedef void(SDLCALL * SDL_RequestAndroidPermissionCallback) (void *userdata, const char *permission, bool granted)
Functions
SDL_DECLSPEC Sint32 SDLCALL JNI_OnLoad (void *vm, void *reserved)
SDL_DECLSPEC void SDLCALL SDL_GDKResumeGPU (SDL_GPUDevice *device)
SDL_DECLSPEC void SDLCALL SDL_GDKSuspendComplete (void)
SDL_DECLSPEC void SDLCALL SDL_GDKSuspendGPU (SDL_GPUDevice *device)
SDL_DECLSPEC void *SDLCALL SDL_GetAndroidActivity (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetAndroidCachePath (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetAndroidExternalStoragePath (void)
SDL_DECLSPEC Uint32 SDLCALL SDL_GetAndroidExternalStorageState (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetAndroidInternalStoragePath (void)
SDL_DECLSPEC void *SDLCALL SDL_GetAndroidJNIEnv (void)
SDL_DECLSPEC int SDLCALL SDL_GetAndroidSDKVersion (void)
SDL_DECLSPEC bool SDLCALL SDL_GetGDKDefaultUser (void *outUserHandle)
SDL_DECLSPEC bool SDLCALL SDL_IsChromebook (void)
SDL_DECLSPEC bool SDLCALL SDL_IsDeXMode (void)
SDL_DECLSPEC bool SDLCALL SDL_RegisterApp (const char *name, Uint32 style, void *hInst)
SDL_DECLSPEC bool SDLCALL SDL_RequestAndroidPermission (const char *permission, SDL_RequestAndroidPermissionCallback cb, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_SendAndroidBackButton (void)
SDL_DECLSPEC bool SDLCALL SDL_SendAndroidMessage (Uint32 command, int param)
SDL_DECLSPEC bool SDLCALL SDL_SetLinuxThreadPriority (Sint64 threadID, int priority)
SDL_DECLSPEC bool SDLCALL SDL_SetLinuxThreadPriorityAndPolicy (Sint64 threadID, int sdlPriority, int schedPolicy)
SDL_DECLSPEC void SDLCALL SDL_SetWindowsMessageHook (void *callback, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_SetX11EventHook (SDL_X11EventHook callback, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_ShowAndroidToast (const char *message, int duration, int gravity, int xoffset, int yoffset)
SDL_DECLSPEC void SDLCALL SDL_UnregisterApp (void)
Typedef Documentation
SDL_RequestAndroidPermissionCallback
typedef void(SDLCALL * SDL_RequestAndroidPermissionCallback) (void *userdata, const char *permission, bool granted)
Function Documentation
JNI_OnLoad()
Sint32 JNI_OnLoad (void * vm, void * reserved)
{
    (void)vm;
    (void)reserved;
    SDL_Unsupported();
    return -1; // JNI_ERR
}
References SDL_Unsupported, and void().
SDL_GDKResumeGPU()
void SDL_GDKResumeGPU (SDL_GPUDevice * device)
{
}
SDL_GDKSuspendComplete()
SDL_DECLSPEC void SDLCALL SDL_GDKSuspendComplete (void)
Callback from the application to let the suspend continue.
This function is only needed for Xbox GDK support; all other platforms will do nothing and set an "unsupported" error message.
Since
This function is available since SDL 3.2.0.
{
    SDL_Unsupported();
}
References SDL_Unsupported.
SDL_GDKSuspendGPU()
void SDL_GDKSuspendGPU (SDL_GPUDevice * device)
{
}
SDL_GetAndroidActivity()
void * SDL_GetAndroidActivity (void)
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
SDL_GetAndroidCachePath()
const char * SDL_GetAndroidCachePath (void)
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
SDL_GetAndroidExternalStoragePath()
const char * SDL_GetAndroidExternalStoragePath (void)
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
SDL_GetAndroidExternalStorageState()
Uint32 SDL_GetAndroidExternalStorageState (void)
{
    SDL_Unsupported();
    return 0;
}
References SDL_Unsupported.
SDL_GetAndroidInternalStoragePath()
const char * SDL_GetAndroidInternalStoragePath (void)
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
Referenced by SDL_GetGamepadMappingFilePath(), and SDL_IOFromFile().
SDL_GetAndroidJNIEnv()
void * SDL_GetAndroidJNIEnv (void)
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
Referenced by CHIDDevice::BOpen(), CHIDDevice::Close(), PLATFORM_hid_init(), CHIDDevice::ReadReport(), RequestBluetoothPermissionCallback(), and CHIDDevice::WriteReport().
SDL_GetAndroidSDKVersion()
SDL_DECLSPEC int SDLCALL SDL_GetAndroidSDKVersion (void)
{
    return SDL_Unsupported();
}
References SDL_Unsupported.
Referenced by PLATFORM_hid_init(), and SDL_PrivateAddGamepadMapping().
SDL_GetGDKDefaultUser()
bool SDL_GetGDKDefaultUser (void * outUserHandle)
{
    return SDL_Unsupported();
}
References SDL_Unsupported.
SDL_IsChromebook()
bool SDL_IsChromebook (void)
{
    SDL_Unsupported();
    return false;
}
References SDL_Unsupported.
SDL_IsDeXMode()
bool SDL_IsDeXMode (void)
{
    SDL_Unsupported();
    return false;
}
References SDL_Unsupported.
SDL_RegisterApp()
bool SDL_RegisterApp (const char * name, Uint32 style, void * hInst)
{
    (void)name;
    (void)style;
    (void)hInst;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
SDL_RequestAndroidPermission()
bool SDL_RequestAndroidPermission (const char * permission, SDL_RequestAndroidPermissionCallback cb, void * userdata)
{
    (void)permission;
    (void)cb;
    (void)userdata;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
Referenced by PLATFORM_hid_init().
SDL_SendAndroidBackButton()
void SDL_SendAndroidBackButton (void)
{
    SDL_Unsupported();
}
References SDL_Unsupported.
SDL_SendAndroidMessage()
bool SDL_SendAndroidMessage (Uint32 command, int param)
{
    (void)command;
    (void)param;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
SDL_SetLinuxThreadPriority()
bool SDL_SetLinuxThreadPriority (Sint64 threadID, int priority)
{
    (void)threadID;
    (void)priority;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
SDL_SetLinuxThreadPriorityAndPolicy()
bool SDL_SetLinuxThreadPriorityAndPolicy (Sint64 threadID, int sdlPriority, int schedPolicy)
{
    (void)threadID;
    (void)sdlPriority;
    (void)schedPolicy;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
Referenced by SDL_SYS_SetThreadPriority().
SDL_SetWindowsMessageHook()
void SDL_SetWindowsMessageHook (void * callback, void * userdata)
{
    (void)callback;
    (void)userdata;
    SDL_Unsupported();
}
References SDL_Unsupported, and void().
SDL_SetX11EventHook()
SDL_DECLSPEC void SDLCALL SDL_SetX11EventHook (SDL_X11EventHook callback, void * userdata)
Set a callback for every X11 event.
The callback may modify the event, and should return true if the event should continue to be processed, or false to prevent further processing.
Parameters
callback the SDL_X11EventHook function to call.
userdata a pointer to pass to every iteration of callback.
Since
This function is available since SDL 3.2.0.
{
}
SDL_ShowAndroidToast()
bool SDL_ShowAndroidToast (const char * message, int duration, int gravity, int xoffset, int yoffset)
{
    (void)message;
    (void)duration;
    (void)gravity;
    (void)xoffset;
    (void)yoffset;
    return SDL_Unsupported();
}
References SDL_Unsupported, void(), xoffset, and yoffset.
SDL_UnregisterApp()
void SDL_UnregisterApp (void)
{
    SDL_Unsupported();
}
References SDL_Unsupported.