SDL3: SDL-main/src/locale/SDL_locale.c File Reference
SDL_locale.c File Reference
#include "SDL_internal.h"
#include "SDL_syslocale.h"
Functions
static SDL_Locale ** build_locales_from_csv_string (char *csv, int *count)
SDL_Locale ** SDL_GetPreferredLocales (int *count)
Function Documentation
build_locales_from_csv_string()
SDL_Locale ** build_locales_from_csv_string (char * csv, int * count) static
{
    int i, num_locales;
    size_t slen;
    size_t alloclen;
    char *ptr;
    SDL_Locale *loc;
    SDL_Locale **result;
    if (count) {
        *count = 0;
    }
    while (csv && *csv && SDL_isspace(*csv)) {
        ++csv;
    }
    if (!csv || !*csv) {
        return NULL; // nothing to report
    }
    num_locales = 1; // at least one
    for (ptr = csv; *ptr; ptr++) {
        if (*ptr == ',') {
            num_locales++;
        }
    }
    slen = ((size_t)(ptr - csv)) + 1; // SDL_strlen(csv) + 1
    alloclen = ((num_locales + 1) * sizeof(SDL_Locale *)) + (num_locales * sizeof(SDL_Locale)) + slen;
    result = (SDL_Locale **)SDL_calloc(1, alloclen);
    if (!result) {
        return NULL; // oh well
    }
    loc = (SDL_Locale *)(result + (num_locales + 1));
    ptr = (char *)(loc + num_locales);
    SDL_memcpy(ptr, csv, slen);
    i = 0;
    result[i++] = loc;
    while (true) { // parse out the string
        while (SDL_isspace(*ptr)) {
            ptr++; // skip whitespace.
        }
        if (*ptr == '\0') {
            break;
        }
        loc->language = ptr++;
        while (true) {
            const char ch = *ptr;
            if (ch == '_') {
                *(ptr++) = '\0';
                loc->country = ptr;
            } else if (SDL_isspace(ch)) {
                *(ptr++) = '\0'; // trim ending whitespace and keep going.
            } else if (ch == ',') {
                *(ptr++) = '\0';
                loc++;
                result[i++] = loc;
                break;
            } else if (ch == '\0') {
                break;
            } else {
                ptr++; // just keep going, still a valid string
            }
        }
    }
    if (count) {
        *count = num_locales;
    }
    return result;
}
References count, SDL_Locale::country, SDL_Locale::language, NULL, SDL_calloc(), SDL_isspace(), and SDL_memcpy.
Referenced by SDL_GetPreferredLocales().
SDL_GetPreferredLocales()
SDL_Locale ** SDL_GetPreferredLocales (int * count)
Report the user's preferred locale.
Returned language strings are in the format xx, where 'xx' is an ISO-639 language specifier (such as "en" for English, "de" for German, etc). Country strings are in the format YY, where "YY" is an ISO-3166 country code (such as "US" for the United States, "CA" for Canada, etc). Country might be NULL if there's no specific guidance on them (so you might get { "en", "US" } for American English, but { "en", NULL } means "English language, generically"). Language strings are never NULL, except to terminate the array.
Please note that not all of these strings are 2 characters; some are three or more.
The returned list of locales are in the order of the user's preference. For example, a German citizen that is fluent in US English and knows enough Japanese to navigate around Tokyo might have a list like: { "de", "en_US", "jp", NULL }. Someone from England might prefer British English (where "color" is spelled "colour", etc), but will settle for anything like it: { "en_GB", "en", NULL }.
This function returns NULL on error, including when the platform does not supply this information at all.
This might be a "slow" call that has to query the operating system. It's best to ask for this once and save the results. However, this list can change, usually because the user has changed a system preference outside of your program; SDL will send an SDL_EVENT_LOCALE_CHANGED event in this case, if possible, and you can call this function again to get an updated copy of preferred locales.
Parameters
count a pointer filled in with the number of locales returned, may be NULL.
Returns
a NULL terminated array of locale pointers, or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    char locbuf[128]; // enough for 21 "xx_YY," language strings.
    const char *hint = SDL_GetHint(SDL_HINT_PREFERRED_LOCALES);
    if (hint) {
        SDL_strlcpy(locbuf, hint, sizeof(locbuf));
    } else {
        SDL_zeroa(locbuf);
        SDL_SYS_GetPreferredLocales(locbuf, sizeof(locbuf));
    }
    return build_locales_from_csv_string(locbuf, count);
}
References build_locales_from_csv_string(), count, SDL_GetHint(), SDL_HINT_PREFERRED_LOCALES, SDL_strlcpy(), SDL_SYS_GetPreferredLocales(), and SDL_zeroa.