SDL3: SDL-main/include/SDL3/SDL_keyboard.h File Reference
SDL_keyboard.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_keycode.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_rect.h>
#include <SDL3/SDL_scancode.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDL_PROP_TEXTINPUT_ANDROID_INPUTTYPE_NUMBER "SDL.textinput.android.inputtype"
#define SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN "SDL.textinput.autocorrect"
#define SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER "SDL.textinput.capitalization"
#define SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN "SDL.textinput.multiline"
#define SDL_PROP_TEXTINPUT_TYPE_NUMBER "SDL.textinput.type"
Typedefs
typedef enum SDL_Capitalization SDL_Capitalization
typedef Uint32 SDL_KeyboardID
typedef enum SDL_TextInputType SDL_TextInputType
Enumerations
enum SDL_Capitalization { SDL_CAPITALIZE_NONE , SDL_CAPITALIZE_SENTENCES , SDL_CAPITALIZE_WORDS , SDL_CAPITALIZE_LETTERS }
enum SDL_TextInputType {
SDL_TEXTINPUT_TYPE_TEXT , SDL_TEXTINPUT_TYPE_TEXT_NAME , SDL_TEXTINPUT_TYPE_TEXT_EMAIL , SDL_TEXTINPUT_TYPE_TEXT_USERNAME ,
SDL_TEXTINPUT_TYPE_TEXT_PASSWORD_HIDDEN , SDL_TEXTINPUT_TYPE_TEXT_PASSWORD_VISIBLE , SDL_TEXTINPUT_TYPE_NUMBER , SDL_TEXTINPUT_TYPE_NUMBER_PASSWORD_HIDDEN ,
SDL_TEXTINPUT_TYPE_NUMBER_PASSWORD_VISIBLE
}
Functions
SDL_DECLSPEC bool SDLCALL SDL_ClearComposition (SDL_Window *window)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetKeyboardFocus (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetKeyboardNameForID (SDL_KeyboardID instance_id)
SDL_DECLSPEC SDL_KeyboardID *SDLCALL SDL_GetKeyboards (int *count)
SDL_DECLSPEC const bool *SDLCALL SDL_GetKeyboardState (int *numkeys)
SDL_DECLSPEC SDL_Keycode SDLCALL SDL_GetKeyFromName (const char *name)
SDL_DECLSPEC SDL_Keycode SDLCALL SDL_GetKeyFromScancode (SDL_Scancode scancode, SDL_Keymod modstate, bool key_event)
SDL_DECLSPEC const char *SDLCALL SDL_GetKeyName (SDL_Keycode key)
SDL_DECLSPEC SDL_Keymod SDLCALL SDL_GetModState (void)
SDL_DECLSPEC SDL_Scancode SDLCALL SDL_GetScancodeFromKey (SDL_Keycode key, SDL_Keymod *modstate)
SDL_DECLSPEC SDL_Scancode SDLCALL SDL_GetScancodeFromName (const char *name)
SDL_DECLSPEC const char *SDLCALL SDL_GetScancodeName (SDL_Scancode scancode)
SDL_DECLSPEC bool SDLCALL SDL_GetTextInputArea (SDL_Window *window, SDL_Rect *rect, int *cursor)
SDL_DECLSPEC bool SDLCALL SDL_HasKeyboard (void)
SDL_DECLSPEC bool SDLCALL SDL_HasScreenKeyboardSupport (void)
SDL_DECLSPEC void SDLCALL SDL_ResetKeyboard (void)
SDL_DECLSPEC bool SDLCALL SDL_ScreenKeyboardShown (SDL_Window *window)
SDL_DECLSPEC void SDLCALL SDL_SetModState (SDL_Keymod modstate)
SDL_DECLSPEC bool SDLCALL SDL_SetScancodeName (SDL_Scancode scancode, const char *name)
SDL_DECLSPEC bool SDLCALL SDL_SetTextInputArea (SDL_Window *window, const SDL_Rect *rect, int cursor)
SDL_DECLSPEC bool SDLCALL SDL_StartTextInput (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_StartTextInputWithProperties (SDL_Window *window, SDL_PropertiesID props)
SDL_DECLSPEC bool SDLCALL SDL_StopTextInput (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_TextInputActive (SDL_Window *window)
Macro Definition Documentation
SDL_PROP_TEXTINPUT_ANDROID_INPUTTYPE_NUMBER
#define SDL_PROP_TEXTINPUT_ANDROID_INPUTTYPE_NUMBER "SDL.textinput.android.inputtype"
SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN
#define SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN "SDL.textinput.autocorrect"
Referenced by SDL_GetTextInputAutocorrect().
SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER
#define SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER "SDL.textinput.capitalization"
Referenced by SDL_GetTextInputCapitalization().
SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN
#define SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN "SDL.textinput.multiline"
Referenced by SDL_GetTextInputMultiline().
SDL_PROP_TEXTINPUT_TYPE_NUMBER
#define SDL_PROP_TEXTINPUT_TYPE_NUMBER "SDL.textinput.type"
Referenced by SDL_GetTextInputType().
Typedef Documentation
SDL_Capitalization
typedef enum SDL_Capitalization SDL_Capitalization
Auto capitalization type.
These are the valid values for SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER. Not every value is valid on every platform, but where a value isn't supported, a reasonable fallback will be used.
Since
This enum is available since SDL 3.2.0.
See also
SDL_StartTextInputWithProperties
SDL_KeyboardID
typedef Uint32 SDL_KeyboardID
CategoryKeyboard
SDL keyboard management.
Please refer to the Best Keyboard Practices document for details on how best to accept keyboard input in various types of programs:
https://wiki.libsdl.org/SDL3/BestKeyboardPractices This is a unique ID for a keyboard for the time it is connected to the system, and is never reused for the lifetime of the application.
If the keyboard is disconnected and reconnected, it will get a new ID.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
SDL_TextInputType
typedef enum SDL_TextInputType SDL_TextInputType
Text input type.
These are the valid values for SDL_PROP_TEXTINPUT_TYPE_NUMBER. Not every value is valid on every platform, but where a value isn't supported, a reasonable fallback will be used.
Since
This enum is available since SDL 3.2.0.
See also
SDL_StartTextInputWithProperties
Enumeration Type Documentation
SDL_Capitalization
enum SDL_Capitalization
Auto capitalization type.
These are the valid values for SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER. Not every value is valid on every platform, but where a value isn't supported, a reasonable fallback will be used.
Since
This enum is available since SDL 3.2.0.
See also
SDL_StartTextInputWithProperties
Enumerator
SDL_CAPITALIZE_NONE
No auto-capitalization will be done
SDL_CAPITALIZE_SENTENCES
The first letter of sentences will be capitalized
SDL_CAPITALIZE_WORDS
The first letter of words will be capitalized
SDL_CAPITALIZE_LETTERS
All letters will be capitalized
{
    SDL_CAPITALIZE_NONE,        /**< No auto-capitalization will be done */
    SDL_CAPITALIZE_SENTENCES,   /**< The first letter of sentences will be capitalized */
    SDL_CAPITALIZE_WORDS,       /**< The first letter of words will be capitalized */
    SDL_CAPITALIZE_LETTERS      /**< All letters will be capitalized */
} SDL_Capitalization;
SDL_TextInputType
enum SDL_TextInputType
Text input type.
These are the valid values for SDL_PROP_TEXTINPUT_TYPE_NUMBER. Not every value is valid on every platform, but where a value isn't supported, a reasonable fallback will be used.
Since
This enum is available since SDL 3.2.0.
See also
SDL_StartTextInputWithProperties
Enumerator
SDL_TEXTINPUT_TYPE_TEXT
The input is text
SDL_TEXTINPUT_TYPE_TEXT_NAME
The input is a person's name
SDL_TEXTINPUT_TYPE_TEXT_EMAIL
The input is an e-mail address
SDL_TEXTINPUT_TYPE_TEXT_USERNAME
The input is a username
SDL_TEXTINPUT_TYPE_TEXT_PASSWORD_HIDDEN
The input is a secure password that is hidden
SDL_TEXTINPUT_TYPE_TEXT_PASSWORD_VISIBLE
The input is a secure password that is visible
SDL_TEXTINPUT_TYPE_NUMBER
The input is a number
SDL_TEXTINPUT_TYPE_NUMBER_PASSWORD_HIDDEN
The input is a secure PIN that is hidden
SDL_TEXTINPUT_TYPE_NUMBER_PASSWORD_VISIBLE
The input is a secure PIN that is visible
{
    SDL_TEXTINPUT_TYPE_TEXT,                        /**< The input is text */
    SDL_TEXTINPUT_TYPE_TEXT_NAME,                   /**< The input is a person's name */
    SDL_TEXTINPUT_TYPE_TEXT_EMAIL,                  /**< The input is an e-mail address */
    SDL_TEXTINPUT_TYPE_TEXT_USERNAME,               /**< The input is a username */
    SDL_TEXTINPUT_TYPE_TEXT_PASSWORD_HIDDEN,        /**< The input is a secure password that is hidden */
    SDL_TEXTINPUT_TYPE_TEXT_PASSWORD_VISIBLE,       /**< The input is a secure password that is visible */
    SDL_TEXTINPUT_TYPE_NUMBER,                      /**< The input is a number */
    SDL_TEXTINPUT_TYPE_NUMBER_PASSWORD_HIDDEN,      /**< The input is a secure PIN that is hidden */
    SDL_TEXTINPUT_TYPE_NUMBER_PASSWORD_VISIBLE      /**< The input is a secure PIN that is visible */
} SDL_TextInputType;
Function Documentation
SDL_ClearComposition()
SDL_DECLSPEC bool SDLCALL SDL_ClearComposition (SDL_Window * window) extern
Dismiss the composition window/IME without disabling the subsystem.
Parameters
window the window to affect.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
SDL_StopTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    if (_this->ClearComposition) {
        return _this->ClearComposition(_this, window);
    }
    return true;
}
References _this, and CHECK_WINDOW_MAGIC.
SDL_GetKeyboardFocus()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetKeyboardFocus (void) extern
Query the window which currently has keyboard focus.
Returns
the window with keyboard focus.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    return keyboard->focus;
}
References SDL_Keyboard::focus, and SDL_keyboard.
Referenced by SDL_BLooper::_HandleKey(), SDL_BLooper::_HandleKeyboardFocus(), DBus_MessageFilter(), SDL_CaptureMouse(), SDL_DestroyWindow(), SDL_Fcitx_ProcessKeyEvent(), SDL_GetToplevelForKeyboardFocus(), SDL_PrivateJoystickShouldIgnoreEvent(), SDL_SetRelativeMouseMode(), SDL_ShowMessageBox(), and SDL_UpdateRelativeMouseMode().
SDL_GetKeyboardNameForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetKeyboardNameForID (SDL_KeyboardID instance_id) extern
Get the name of a keyboard.
This function returns "" if the keyboard doesn't have a name.
Parameters
instance_id the keyboard instance ID.
Returns
the name of the selected keyboard or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboards
{
    int keyboard_index = SDL_GetKeyboardIndex(instance_id);
    if (keyboard_index < 0) {
        SDL_SetError("Keyboard %" SDL_PRIu32 " not found", instance_id);
        return NULL;
    }
    return SDL_GetPersistentString(SDL_keyboards[keyboard_index].name);
}
References NULL, SDL_GetKeyboardIndex(), SDL_GetPersistentString(), SDL_keyboards, SDL_PRIu32, and SDL_SetError().
SDL_GetKeyboards()
SDL_DECLSPEC SDL_KeyboardID *SDLCALL SDL_GetKeyboards (int * count) extern
Get a list of currently connected keyboards.
Note that this will include any device or virtual driver that includes keyboard functionality, including some mice, KVM switches, motherboard power buttons, etc. You should wait for input from a device before you consider it actively in use.
Parameters
count a pointer filled in with the number of keyboards returned, may be NULL.
Returns
a 0 terminated array of keyboards instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboardNameForID
SDL_HasKeyboard
{
    int i;
    SDL_KeyboardID *keyboards;
    keyboards = (SDL_JoystickID *)SDL_malloc((SDL_keyboard_count + 1) * sizeof(*keyboards));
    if (keyboards) {
        if (count) {
            *count = SDL_keyboard_count;
        }
        for (i = 0; i < SDL_keyboard_count; ++i) {
            keyboards[i] = SDL_keyboards[i].instance_id;
        }
        keyboards[i] = 0;
    } else {
        if (count) {
            *count = 0;
        }
    }
    return keyboards;
}
References count, SDL_keyboard_count, SDL_keyboards, and SDL_malloc().
SDL_GetKeyboardState()
SDL_DECLSPEC const bool *SDLCALL SDL_GetKeyboardState (int * numkeys) extern
Get a snapshot of the current state of the keyboard.
The pointer returned is a pointer to an internal SDL array. It will be valid for the whole lifetime of the application and should not be freed by the caller.
A array element with a value of true means that the key is pressed and a value of false means that it is not. Indexes into this array are obtained by using SDL_Scancode values.
Use SDL_PumpEvents() to update the state array.
This function gives you the current state after all events have been processed, so if a key or button has been pressed and released before you process events, then the pressed state will never show up in the SDL_GetKeyboardState() calls.
Note: This function doesn't take into account whether shift has been pressed or not.
Parameters
numkeys if non-NULL, receives the length of the returned array.
Returns
a pointer to an array of key states.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PumpEvents
SDL_ResetKeyboard
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (numkeys != (int *)0) {
        *numkeys = SDL_SCANCODE_COUNT;
    }
    return keyboard->keystate;
}
References SDL_Keyboard::keystate, SDL_keyboard, and SDL_SCANCODE_COUNT.
SDL_GetKeyFromName()
SDL_DECLSPEC SDL_Keycode SDLCALL SDL_GetKeyFromName (const char * name) extern
Get a key code from a human-readable name.
Parameters
name the human-readable key name.
Returns
key code, or SDLK_UNKNOWN if the name wasn't recognized; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyFromScancode
SDL_GetKeyName
SDL_GetScancodeFromName
{
    const bool uppercase = true;
    SDL_Keycode key;
    // Check input
    if (!name) {
        return SDLK_UNKNOWN;
    }
    // If it's a single UTF-8 character, then that's the keycode itself
    key = *(const unsigned char *)name;
    if (key >= 0xF0) {
        if (SDL_strlen(name) == 4) {
            int i = 0;
            key = (Uint16)(name[i] & 0x07) << 18;
            key |= (Uint16)(name[++i] & 0x3F) << 12;
            key |= (Uint16)(name[++i] & 0x3F) << 6;
            key |= (Uint16)(name[++i] & 0x3F);
        } else {
            key = SDLK_UNKNOWN;
        }
    } else if (key >= 0xE0) {
        if (SDL_strlen(name) == 3) {
            int i = 0;
            key = (Uint16)(name[i] & 0x0F) << 12;
            key |= (Uint16)(name[++i] & 0x3F) << 6;
            key |= (Uint16)(name[++i] & 0x3F);
        } else {
            key = SDLK_UNKNOWN;
        }
    } else if (key >= 0xC0) {
        if (SDL_strlen(name) == 2) {
            int i = 0;
            key = (Uint16)(name[i] & 0x1F) << 6;
            key |= (Uint16)(name[++i] & 0x3F);
        } else {
            key = SDLK_UNKNOWN;
        }
    } else {
        if (SDL_strlen(name) != 1) {
            key = SDLK_UNKNOWN;
        }
    }
    if (key != SDLK_UNKNOWN) {
        if (uppercase) {
            // SDL_Keycode is defined as the unshifted key on the keyboard,
            // but the key name is defined as the letter printed on that key,
            // which is usually the shifted capital letter.
            SDL_Keymap *keymap = SDL_GetCurrentKeymap(false);
            SDL_Keymod modstate;
            SDL_Scancode scancode = SDL_GetKeymapScancode(keymap, key, &modstate);
            if (scancode != SDL_SCANCODE_UNKNOWN && (modstate & (SDL_KMOD_SHIFT | SDL_KMOD_CAPS))) {
                key = SDL_GetKeymapKeycode(keymap, scancode, SDL_KMOD_NONE);
            }
        }
        return key;
    }
    // Check the extended key names
    for (SDL_Keycode i = 0; i < SDL_arraysize(SDL_extended_key_names); ++i) {
        if (SDL_strcasecmp(name, SDL_extended_key_names[i]) == 0) {
            return (i + 1) | SDLK_EXTENDED_MASK;
        }
    }
    return SDL_GetKeyFromScancode(SDL_GetScancodeFromName(name), SDL_KMOD_NONE, false);
}
References scancode, SDL_arraysize, SDL_extended_key_names, SDL_GetCurrentKeymap(), SDL_GetKeyFromScancode(), SDL_GetKeymapKeycode(), SDL_GetKeymapScancode(), SDL_GetScancodeFromName(), SDL_KMOD_CAPS, SDL_KMOD_NONE, SDL_KMOD_SHIFT, SDL_SCANCODE_UNKNOWN, SDL_strcasecmp(), SDL_strlen(), SDLK_EXTENDED_MASK, and SDLK_UNKNOWN.
SDL_GetKeyFromScancode()
SDL_DECLSPEC SDL_Keycode SDLCALL SDL_GetKeyFromScancode (SDL_Scancode scancode, SDL_Keymod modstate, bool key_event) extern
Get the key code corresponding to the given scancode according to the current keyboard layout.
If you want to get the keycode as it would be delivered in key events, including options specified in SDL_HINT_KEYCODE_OPTIONS, then you should pass key_event as true. Otherwise this function simply translates the scancode based on the given modifier state.
Parameters
scancode the desired SDL_Scancode to query.
modstate the modifier state to use when translating the scancode to a keycode.
key_event true if the keycode will be used in key events.
Returns
the SDL_Keycode that corresponds to the given SDL_Scancode.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyName
SDL_GetScancodeFromKey
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (key_event) {
        SDL_Keymap *keymap = SDL_GetCurrentKeymap(false);
        bool numlock = (modstate & SDL_KMOD_NUM) != 0;
        SDL_Keycode keycode;
        // We won't be applying any modifiers by default
        modstate = SDL_KMOD_NONE;
        if ((keyboard->keycode_options & KEYCODE_OPTION_FRENCH_NUMBERS) &&
            keymap && keymap->french_numbers &&
            (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_0)) {
            // Add the shift state to generate a numeric keycode
            modstate |= SDL_KMOD_SHIFT;
        }
        keycode = SDL_GetKeymapKeycode(keymap, scancode, modstate);
        if (keyboard->keycode_options & KEYCODE_OPTION_HIDE_NUMPAD) {
            keycode = SDL_ConvertNumpadKeycode(keycode, numlock);
        }
        return keycode;
    }
    return SDL_GetKeymapKeycode(keyboard->keymap, scancode, modstate);
}
References SDL_Keymap::french_numbers, keycode, KEYCODE_OPTION_FRENCH_NUMBERS, KEYCODE_OPTION_HIDE_NUMPAD, SDL_Keyboard::keycode_options, SDL_Keyboard::keymap, scancode, SDL_ConvertNumpadKeycode(), SDL_GetCurrentKeymap(), SDL_GetKeymapKeycode(), SDL_keyboard, SDL_KMOD_NONE, SDL_KMOD_NUM, SDL_KMOD_SHIFT, SDL_SCANCODE_0, and SDL_SCANCODE_1.
Referenced by SDL_GetKeyFromName(), and SDL_SendKeyboardKeyInternal().
SDL_GetKeyName()
SDL_DECLSPEC const char *SDLCALL SDL_GetKeyName (SDL_Keycode key) extern
Get a human-readable name for a key.
If the key doesn't have a name, this function returns an empty string ("").
Letters will be presented in their uppercase form, if applicable.
Parameters
key the desired SDL_Keycode to query.
Returns
a UTF-8 encoded string of the key name.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyFromName
SDL_GetKeyFromScancode
SDL_GetScancodeFromKey
{
    const bool uppercase = true;
    char name[8];
    char *end;
    if (key & SDLK_SCANCODE_MASK) {
        return SDL_GetScancodeName((SDL_Scancode)(key & ~SDLK_SCANCODE_MASK));
    }
    if (key & SDLK_EXTENDED_MASK) {
        const SDL_Keycode idx = (key & ~SDLK_EXTENDED_MASK);
        if (idx > 0 && (idx - 1) < SDL_arraysize(SDL_extended_key_names)) {
            return SDL_extended_key_names[idx - 1];
        }
        // Key out of name index bounds.
        SDL_InvalidParamError("key");
        return "";
    }
    switch (key) {
    case SDLK_RETURN:
        return SDL_GetScancodeName(SDL_SCANCODE_RETURN);
    case SDLK_ESCAPE:
        return SDL_GetScancodeName(SDL_SCANCODE_ESCAPE);
    case SDLK_BACKSPACE:
        return SDL_GetScancodeName(SDL_SCANCODE_BACKSPACE);
    case SDLK_TAB:
        return SDL_GetScancodeName(SDL_SCANCODE_TAB);
    case SDLK_SPACE:
        return SDL_GetScancodeName(SDL_SCANCODE_SPACE);
    case SDLK_DELETE:
        return SDL_GetScancodeName(SDL_SCANCODE_DELETE);
    default:
        if (uppercase) {
            // SDL_Keycode is defined as the unshifted key on the keyboard,
            // but the key name is defined as the letter printed on that key,
            // which is usually the shifted capital letter.
            if (key > 0x7F || (key >= 'a' && key <= 'z')) {
                SDL_Keymap *keymap = SDL_GetCurrentKeymap(false);
                SDL_Keymod modstate;
                SDL_Scancode scancode = SDL_GetKeymapScancode(keymap, key, &modstate);
                if (scancode != SDL_SCANCODE_UNKNOWN && !(modstate & SDL_KMOD_SHIFT)) {
                    SDL_Keycode capital = SDL_GetKeymapKeycode(keymap, scancode, SDL_KMOD_SHIFT);
                    if (capital > 0x7F || (capital >= 'A' && capital <= 'Z')) {
                        key = capital;
                    }
                }
            }
        }
        end = SDL_UCS4ToUTF8(key, name);
        *end = '\0';
        return SDL_GetPersistentString(name);
    }
}
References scancode, SDL_arraysize, SDL_extended_key_names, SDL_GetCurrentKeymap(), SDL_GetKeymapKeycode(), SDL_GetKeymapScancode(), SDL_GetPersistentString(), SDL_GetScancodeName(), SDL_InvalidParamError, SDL_KMOD_SHIFT, SDL_SCANCODE_BACKSPACE, SDL_SCANCODE_DELETE, SDL_SCANCODE_ESCAPE, SDL_SCANCODE_RETURN, SDL_SCANCODE_SPACE, SDL_SCANCODE_TAB, SDL_SCANCODE_UNKNOWN, SDL_UCS4ToUTF8(), SDLK_BACKSPACE, SDLK_DELETE, SDLK_ESCAPE, SDLK_EXTENDED_MASK, SDLK_RETURN, SDLK_SCANCODE_MASK, SDLK_SPACE, and SDLK_TAB.
SDL_GetModState()
SDL_DECLSPEC SDL_Keymod SDLCALL SDL_GetModState (void) extern
Get the current key modifier state for the keyboard.
Returns
an OR'd combination of the modifier keys for the keyboard. See SDL_Keymod for details.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboardState
SDL_SetModState
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    return keyboard->modstate;
}
References SDL_Keyboard::modstate, and SDL_keyboard.
Referenced by Fcitx_ModState(), and SDL_SendKeyboardKeyAndKeycode().
SDL_GetScancodeFromKey()
SDL_DECLSPEC SDL_Scancode SDLCALL SDL_GetScancodeFromKey (SDL_Keycode key, SDL_Keymod * modstate) extern
Get the scancode corresponding to the given key code according to the current keyboard layout.
Note that there may be multiple scancode+modifier states that can generate this keycode, this will just return the first one found.
Parameters
key the desired SDL_Keycode to query.
modstate a pointer to the modifier state that would be used when the scancode generates this key, may be NULL.
Returns
the SDL_Scancode that corresponds to the given SDL_Keycode.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyFromScancode
SDL_GetScancodeName
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    return SDL_GetKeymapScancode(keyboard->keymap, key, modstate);
}
References SDL_Keyboard::keymap, SDL_GetKeymapScancode(), and SDL_keyboard.
SDL_GetScancodeFromName()
SDL_DECLSPEC SDL_Scancode SDLCALL SDL_GetScancodeFromName (const char * name) extern
Get a scancode from a human-readable name.
Parameters
name the human-readable scancode name.
Returns
the SDL_Scancode, or SDL_SCANCODE_UNKNOWN if the name wasn't recognized; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyFromName
SDL_GetScancodeFromKey
SDL_GetScancodeName
{
    int i;
    if (!name || !*name) {
        SDL_InvalidParamError("name");
        return SDL_SCANCODE_UNKNOWN;
    }
    for (i = 0; i < SDL_arraysize(SDL_scancode_names); ++i) {
        if (!SDL_scancode_names[i]) {
            continue;
        }
        if (SDL_strcasecmp(name, SDL_scancode_names[i]) == 0) {
            return (SDL_Scancode)i;
        }
    }
    SDL_InvalidParamError("name");
    return SDL_SCANCODE_UNKNOWN;
}
References SDL_arraysize, SDL_InvalidParamError, SDL_scancode_names, SDL_SCANCODE_UNKNOWN, and SDL_strcasecmp().
Referenced by SDL_GetKeyFromName().
SDL_GetScancodeName()
SDL_DECLSPEC const char *SDLCALL SDL_GetScancodeName (SDL_Scancode scancode) extern
Get a human-readable name for a scancode.
Warning: The returned name is by design not stable across platforms, e.g. the name for SDL_SCANCODE_LGUI is "Left GUI" under Linux but "Left Windows" under Microsoft Windows, and some scancodes like SDL_SCANCODE_NONUSBACKSLASH don't have any name at all. There are even scancodes that share names, e.g. SDL_SCANCODE_RETURN and SDL_SCANCODE_RETURN2 (both called "Return"). This function is therefore unsuitable for creating a stable cross-platform two-way mapping between strings and scancodes.
Parameters
scancode the desired SDL_Scancode to query.
Returns
a pointer to the name for the scancode. If the scancode doesn't have a name this function returns an empty string ("").
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetScancodeFromKey
SDL_GetScancodeFromName
SDL_SetScancodeName
{
    const char *name;
    if (((int)scancode) < SDL_SCANCODE_UNKNOWN || scancode >= SDL_SCANCODE_COUNT) {
        SDL_InvalidParamError("scancode");
        return "";
    }
    name = SDL_scancode_names[scancode];
    if (!name) {
        name = "";
    }
    // This is pointing to static memory or application managed memory
    return name;
}
References scancode, SDL_InvalidParamError, SDL_SCANCODE_COUNT, SDL_scancode_names, and SDL_SCANCODE_UNKNOWN.
Referenced by SDL_GetKeyName(), and SDL_SendKeyboardKeyInternal().
SDL_GetTextInputArea()
SDL_DECLSPEC bool SDLCALL SDL_GetTextInputArea (SDL_Window * window, SDL_Rect * rect, int * cursor) extern
Get the area used to type Unicode text input.
This returns the values previously set by SDL_SetTextInputArea().
Parameters
window the window for which to query the text input area.
rect a pointer to an SDL_Rect filled in with the text input area, may be NULL.
cursor a pointer to the offset of the current cursor location relative to rect->x, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextInputArea
{
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        SDL_copyp(rect, &window->text_input_rect);
    }
    if (cursor) {
        *cursor = window->text_input_cursor;
    }
    return true;
}
References CHECK_WINDOW_MAGIC, and SDL_copyp.
SDL_HasKeyboard()
SDL_DECLSPEC bool SDLCALL SDL_HasKeyboard (void) extern
Return whether a keyboard is currently connected.
Returns
true if a keyboard is connected, false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboards
{
    return (SDL_keyboard_count > 0);
}
References SDL_keyboard_count.
Referenced by AutoShowingScreenKeyboard().
SDL_HasScreenKeyboardSupport()
SDL_DECLSPEC bool SDLCALL SDL_HasScreenKeyboardSupport (void) extern
Check whether the platform has screen keyboard support.
Returns
true if the platform has some screen keyboard support or false if not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
SDL_ScreenKeyboardShown
{
    if (_this && _this->HasScreenKeyboardSupport) {
        return _this->HasScreenKeyboardSupport(_this);
    }
    return false;
}
References _this.
SDL_ResetKeyboard()
SDL_DECLSPEC void SDLCALL SDL_ResetKeyboard (void) extern
Clear the state of the keyboard.
This function will generate key up events for all pressed keys.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboardState
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    int scancode;
#ifdef DEBUG_KEYBOARD
    SDL_Log("Resetting keyboard");
#endif
    for (scancode = SDL_SCANCODE_UNKNOWN; scancode < SDL_SCANCODE_COUNT; ++scancode) {
        if (keyboard->keystate[scancode]) {
            SDL_SendKeyboardKey(0, SDL_GLOBAL_KEYBOARD_ID, 0, (SDL_Scancode)scancode, false);
        }
    }
}
References SDL_Keyboard::keystate, scancode, SDL_GLOBAL_KEYBOARD_ID, SDL_keyboard, SDL_Log(), SDL_SCANCODE_COUNT, SDL_SCANCODE_UNKNOWN, and SDL_SendKeyboardKey().
Referenced by SDL_SetKeyboardFocus(), and SDL_ShowMessageBox().
SDL_ScreenKeyboardShown()
SDL_DECLSPEC bool SDLCALL SDL_ScreenKeyboardShown (SDL_Window * window) extern
Check whether the screen keyboard is shown for given window.
Parameters
window the window for which screen keyboard should be queried.
Returns
true if screen keyboard is shown or false if not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasScreenKeyboardSupport
{
    CHECK_WINDOW_MAGIC(window, false);
    if (_this->IsScreenKeyboardShown) {
        return _this->IsScreenKeyboardShown(_this, window);
    }
    return false;
}
References _this, and CHECK_WINDOW_MAGIC.
Referenced by SDL_StartTextInputWithProperties(), and SDL_StopTextInput().
SDL_SetModState()
SDL_DECLSPEC void SDLCALL SDL_SetModState (SDL_Keymod modstate) extern
Set the current key modifier state for the keyboard.
The inverse of SDL_GetModState(), SDL_SetModState() allows you to impose modifier key states on your application. Simply pass your desired modifier states into modstate. This value may be a bitwise, OR'd combination of SDL_Keymod values.
This does not change the keyboard state, only the key modifier flags that SDL reports.
Parameters
modstate the desired SDL_Keymod for the keyboard.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetModState
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    keyboard->modstate = modstate;
}
References SDL_Keyboard::modstate, and SDL_keyboard.
SDL_SetScancodeName()
SDL_DECLSPEC bool SDLCALL SDL_SetScancodeName (SDL_Scancode scancode, const char * name) extern
Set a human-readable name for a scancode.
Parameters
scancode the desired SDL_Scancode.
name the name to use for the scancode, encoded as UTF-8. The string is not copied, so the pointer given to this function must stay valid while SDL is being used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetScancodeName
{
    if (((int)scancode) < SDL_SCANCODE_UNKNOWN || scancode >= SDL_SCANCODE_COUNT) {
        return SDL_InvalidParamError("scancode");
    }
    SDL_scancode_names[scancode] = name;
    return true;
}
References scancode, SDL_InvalidParamError, SDL_SCANCODE_COUNT, SDL_scancode_names, and SDL_SCANCODE_UNKNOWN.
SDL_SetTextInputArea()
SDL_DECLSPEC bool SDLCALL SDL_SetTextInputArea (SDL_Window * window, const SDL_Rect * rect, int cursor) extern
Set the area used to type Unicode text input.
Native input methods may place a window with word suggestions near the cursor, without covering the text being entered.
Parameters
window the window for which to set the text input area.
rect the SDL_Rect representing the text input area, in window coordinates, or NULL to clear it.
cursor the offset of the current cursor location relative to rect->x, in window coordinates.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextInputArea
SDL_StartTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        SDL_copyp(&window->text_input_rect, rect);
        window->text_input_cursor = cursor;
    } else {
        SDL_zero(window->text_input_rect);
        window->text_input_cursor = 0;
    }
    if (_this && _this->UpdateTextInputArea) {
        if (!_this->UpdateTextInputArea(_this, window)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_copyp, and SDL_zero.
SDL_StartTextInput()
SDL_DECLSPEC bool SDLCALL SDL_StartTextInput (SDL_Window * window) extern
Start accepting Unicode text input events in a window.
This function will enable text input (SDL_EVENT_TEXT_INPUT and SDL_EVENT_TEXT_EDITING events) in the specified window. Please use this function paired with SDL_StopTextInput().
Text input events are not received by default.
On some platforms using this function shows the screen keyboard and/or activates an IME, which can prevent some key press events from being passed through.
Parameters
window the window to enable text input.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextInputArea
SDL_StartTextInputWithProperties
SDL_StopTextInput
SDL_TextInputActive
{
    return SDL_StartTextInputWithProperties(window, 0);
}
References SDL_StartTextInputWithProperties().
SDL_StartTextInputWithProperties()
SDL_DECLSPEC bool SDLCALL SDL_StartTextInputWithProperties (SDL_Window * window, SDL_PropertiesID props) extern
Start accepting Unicode text input events in a window, with properties describing the input.
This function will enable text input (SDL_EVENT_TEXT_INPUT and SDL_EVENT_TEXT_EDITING events) in the specified window. Please use this function paired with SDL_StopTextInput().
Text input events are not received by default.
On some platforms using this function shows the screen keyboard and/or activates an IME, which can prevent some key press events from being passed through.
These are the supported properties:
SDL_PROP_TEXTINPUT_TYPE_NUMBER - an SDL_TextInputType value that describes text being input, defaults to SDL_TEXTINPUT_TYPE_TEXT.
SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER - an SDL_Capitalization value that describes how text should be capitalized, defaults to SDL_CAPITALIZE_SENTENCES for normal text entry, SDL_CAPITALIZE_WORDS for SDL_TEXTINPUT_TYPE_TEXT_NAME, and SDL_CAPITALIZE_NONE for e-mail addresses, usernames, and passwords.
SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN - true to enable auto completion and auto correction, defaults to true.
SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN - true if multiple lines of text are allowed. This defaults to true if SDL_HINT_RETURN_KEY_HIDES_IME is "0" or is not set, and defaults to false if SDL_HINT_RETURN_KEY_HIDES_IME is "1".
On Android you can directly specify the input type:
SDL_PROP_TEXTINPUT_ANDROID_INPUTTYPE_NUMBER - the text input type to use, overriding other properties. This is documented at https://developer.android.com/reference/android/text/InputType
Parameters
window the window to enable text input.
props the properties to use.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextInputArea
SDL_StartTextInput
SDL_StopTextInput
SDL_TextInputActive
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->text_input_props) {
        SDL_DestroyProperties(window->text_input_props);
        window->text_input_props = 0;
    }
    if (props) {
        window->text_input_props = SDL_CreateProperties();
        if (!window->text_input_props) {
            return false;
        }
        if (!SDL_CopyProperties(props, window->text_input_props)) {
            return false;
        }
    }
    if (_this->SetTextInputProperties) {
        _this->SetTextInputProperties(_this, window, props);
    }
    // Show the on-screen keyboard, if desired
    if (AutoShowingScreenKeyboard() && !SDL_ScreenKeyboardShown(window)) {
        if (_this->ShowScreenKeyboard) {
            _this->ShowScreenKeyboard(_this, window, props);
        }
    }
    if (!window->text_input_active) {
        // Finally start the text input system
        if (_this->StartTextInput) {
            if (!_this->StartTextInput(_this, window, props)) {
                return false;
            }
        }
        window->text_input_active = true;
    }
    return true;
}
References _this, AutoShowingScreenKeyboard(), CHECK_WINDOW_MAGIC, SDL_CopyProperties(), SDL_CreateProperties(), SDL_DestroyProperties(), and SDL_ScreenKeyboardShown().
Referenced by SDL_StartTextInput().
SDL_StopTextInput()
SDL_DECLSPEC bool SDLCALL SDL_StopTextInput (SDL_Window * window) extern
Stop receiving any text input events in a window.
If SDL_StartTextInput() showed the screen keyboard, this function will hide it.
Parameters
window the window to disable text input.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->text_input_active) {
        // Stop the text input system
        if (_this->StopTextInput) {
            _this->StopTextInput(_this, window);
        }
        window->text_input_active = false;
    }
    // Hide the on-screen keyboard, if desired
    if (AutoShowingScreenKeyboard() && SDL_ScreenKeyboardShown(window)) {
        if (_this->HideScreenKeyboard) {
            _this->HideScreenKeyboard(_this, window);
        }
    }
    return true;
}
References _this, AutoShowingScreenKeyboard(), CHECK_WINDOW_MAGIC, and SDL_ScreenKeyboardShown().
SDL_TextInputActive()
SDL_DECLSPEC bool SDLCALL SDL_TextInputActive (SDL_Window * window) extern
Check whether or not Unicode text input events are enabled for a window.
Parameters
window the window to check.
Returns
true if text input events are enabled else false.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    return window->text_input_active;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_BLooper::_HandleKey(), SDL_SendEditingText(), SDL_SendEditingTextCandidates(), SDL_SendKeyboardText(), and SDL_SetKeyboardFocus().