SDL3: SDL-main/src/thread/pthread/SDL_sysmutex.c File Reference
SDL_sysmutex.c File Reference
#include "SDL_internal.h"
#include <errno.h>
#include <pthread.h>
#include "SDL_sysmutex_c.h"
Functions
SDL_Mutex * SDL_CreateMutex (void)
void SDL_DestroyMutex (SDL_Mutex *mutex)
void SDL_LockMutex (SDL_Mutex *mutex) SDL_NO_THREAD_SAFETY_ANALYSIS
bool SDL_TryLockMutex (SDL_Mutex *mutex)
void SDL_UnlockMutex (SDL_Mutex *mutex) SDL_NO_THREAD_SAFETY_ANALYSIS
Function Documentation
SDL_CreateMutex()
SDL_Mutex * SDL_CreateMutex (void)
Create a new mutex.
All newly-created mutexes begin in the unlocked state.
Calls to SDL_LockMutex() will not return while the mutex is locked by another thread. See SDL_TryLockMutex() to attempt to lock without blocking.
SDL mutexes are reentrant.
Returns
the initialized and unlocked mutex or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyMutex
SDL_LockMutex
SDL_TryLockMutex
SDL_UnlockMutex
{
    SDL_Mutex *mutex;
    pthread_mutexattr_t attr;
    // Allocate the structure
    mutex = (SDL_Mutex *)SDL_calloc(1, sizeof(*mutex));
    if (mutex) {
        pthread_mutexattr_init(&attr);
#ifdef SDL_THREAD_PTHREAD_RECURSIVE_MUTEX
        pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
#elif defined(SDL_THREAD_PTHREAD_RECURSIVE_MUTEX_NP)
        pthread_mutexattr_setkind_np(&attr, PTHREAD_MUTEX_RECURSIVE_NP);
#else
        // No extra attributes necessary
#endif
        if (pthread_mutex_init(&mutex->id, &attr) != 0) {
            SDL_SetError("pthread_mutex_init() failed");
            SDL_free(mutex);
            mutex = NULL;
        }
    }
    return mutex;
}
References SDL_Mutex::id, NULL, SDL_Mutex::owner, SDL_Mutex::recursive, SDL_calloc(), SDL_CreateSemaphore(), SDL_free(), SDL_SetError(), and SDL_Mutex::sem.
Referenced by CreatePhysicalAudioDevice(), hidapi_thread_state_init(), PrepareThreadpool(), SDL_AddCamera(), SDL_AsyncIOFromFile(), SDL_CreateAudioStream(), SDL_CreateCondition(), SDL_CreateEnvironment(), SDL_CreateProperties(), SDL_CreateRendererWithProperties(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateThreadBarrier(), SDL_Generic_InitTLSData(), SDL_InitEventWatchList(), SDL_InitJoysticks(), SDL_InitLog(), SDL_InitMainThreadCallbacks(), SDL_InitSensors(), SDL_InitTimers(), SDL_ReportAssertion(), SDL_StartEventLoop(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), and SDL_TryLockSpinlock().
SDL_DestroyMutex()
void SDL_DestroyMutex (SDL_Mutex * mutex)
Destroy a mutex created with SDL_CreateMutex().
This function must be called on any mutex that is no longer needed. Failure to destroy a mutex will result in a system memory or resource leak. While it is safe to destroy a mutex that is unlocked, it is not safe to attempt to destroy a locked mutex, and may result in undefined behavior depending on the platform.
Parameters
mutex the mutex to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateMutex
{
    if (mutex) {
        pthread_mutex_destroy(&mutex->id);
        SDL_free(mutex);
    }
}
References SDL_Mutex::id, SDL_DestroySemaphore(), SDL_free(), and SDL_Mutex::sem.
Referenced by CreatePhysicalAudioDevice(), DestroyCameraHashItem(), DestroyPhysicalAudioDevice(), generic_asyncio_destroy(), generic_asyncioqueue_destroy(), GetAsyncIOTaskOutcome(), hidapi_thread_state_destroy(), PrepareThreadpool(), SDL_AddCamera(), SDL_AssertionsQuit(), SDL_AsyncIOFromFile(), SDL_CreateCondition(), SDL_CreateProperties(), SDL_CreateRWLock(), SDL_DestroyAudioStream(), SDL_DestroyEnvironment(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroyRWLock(), SDL_DestroySemaphore(), SDL_DestroyThreadBarrier(), SDL_FreeProperties(), SDL_Generic_QuitTLSData(), SDL_QuitEventWatchList(), SDL_QuitLog(), SDL_QuitMainThreadCallbacks(), SDL_QuitTimers(), SDL_StopEventLoop(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), SDL_UnlockJoysticks(), SDL_UnlockSensors(), and ShutdownThreadpool().
SDL_LockMutex()
void SDL_LockMutex (SDL_Mutex * mutex)
Lock the mutex.
This will block until the mutex is available, which is to say it is in the unlocked state and the OS has chosen the caller as the next thread to lock it. Of all threads waiting to lock the mutex, only one may do so at a time.
It is legal for the owning thread to lock an already-locked mutex. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive mutex").
This function does not fail; if mutex is NULL, it will return immediately having locked nothing. If the mutex is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
mutex the mutex to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_TryLockMutex
SDL_UnlockMutex
{
    if (mutex) {
#ifdef FAKE_RECURSIVE_MUTEX
        pthread_t this_thread = pthread_self();
        if (mutex->owner == this_thread) {
            ++mutex->recursive;
        } else {
            /* The order of operations is important.
               We set the locking thread id after we obtain the lock
               so unlocks from other threads will fail.
             */
            const int rc = pthread_mutex_lock(&mutex->id);
            SDL_assert(rc == 0);  // assume we're in a lot of trouble if this assert fails.
            mutex->owner = this_thread;
            mutex->recursive = 0;
        }
#else
        const int rc = pthread_mutex_lock(&mutex->id);
        SDL_assert(rc == 0);  // assume we're in a lot of trouble if this assert fails.
#endif
    }
}
References NULL, SDL_assert, SDL_GetCurrentThreadID(), SDL_NO_THREAD_SAFETY_ANALYSIS, and SDL_WaitSemaphore().
Referenced by AsyncIOTaskComplete(), AsyncIOThreadpoolWorker(), ClosePhysicalAudioDevice(), DestroyLogicalAudioDevice(), DestroyPhysicalAudioDevice(), generic_asyncioqueue_cancel_task(), generic_asyncioqueue_get_results(), generic_asyncioqueue_signal(), generic_asyncioqueue_wait_results(), GetAsyncIOTaskOutcome(), hidapi_thread_mutex_lock(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), ObtainPhysicalCameraObj(), PutAudioStreamBuffer(), QueueAsyncIOTask(), RequestAsyncIO(), SDL_AddEventWatchList(), SDL_BindAudioStreams(), SDL_CameraThreadIterate(), SDL_ClearAudioStream(), SDL_CloseAsyncIO(), SDL_CopyProperties(), SDL_CreateTimer(), SDL_DestroySemaphore(), SDL_DispatchEventWatchList(), SDL_EnumerateProperties(), SDL_FilterEvents(), SDL_FlushAudioStream(), SDL_FlushEvents(), SDL_Generic_GetTLSData(), SDL_Generic_QuitTLSData(), SDL_Generic_SetTLSData(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), SDL_GetAudioStreamDevice(), SDL_GetAudioStreamFormat(), SDL_GetAudioStreamFrequencyRatio(), SDL_GetAudioStreamGain(), SDL_GetAudioStreamInputChannelMap(), SDL_GetAudioStreamOutputChannelMap(), SDL_GetAudioStreamProperties(), SDL_GetAudioStreamQueued(), SDL_GetBooleanProperty(), SDL_GetEnvironmentVariable(), SDL_GetEnvironmentVariables(), SDL_GetEventFilter(), SDL_GetFloatProperty(), SDL_GetLogOutputFunction(), SDL_GetLogPriority(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetSemaphoreValue(), SDL_GetStringProperty(), SDL_HasEvents(), SDL_LockAudioStream(), SDL_LockJoysticks(), SDL_LockProperties(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_LockSensors(), SDL_LogMessageV(), SDL_PeepEventsInternal(), SDL_PlaybackAudioThreadIterate(), SDL_PrivateSetProperty(), SDL_PutAudioStreamPlanarData(), SDL_QuitMainThreadCallbacks(), SDL_RecordingAudioThreadIterate(), SDL_RemoveEventWatchList(), SDL_RemoveTimer(), SDL_ReportAssertion(), SDL_ResetLogPriorities(), SDL_RunMainThreadCallbacks(), SDL_RunOnMainThread(), SDL_SetAudioStreamFormat(), SDL_SetAudioStreamFrequencyRatio(), SDL_SetAudioStreamGain(), SDL_SetAudioStreamGetCallback(), SDL_SetAudioStreamPutCallback(), SDL_SetEnvironmentVariable(), SDL_SetEventFilter(), SDL_SetLogOutputFunction(), SDL_SetLogPriorities(), SDL_SetLogPriority(), SDL_SetLogPriorityPrefix(), SDL_SetRenderTarget(), SDL_SignalSemaphore(), SDL_StartEventLoop(), SDL_StopEventLoop(), SDL_TryLockSpinlock(), SDL_UnbindAudioStreams(), SDL_UnlockJoysticks(), SDL_UnlockRWLock(), SDL_UnlockSensors(), SDL_UnsetEnvironmentVariable(), SDL_WaitConditionTimeoutNS_generic(), SDL_WaitSemaphoreTimeoutNS(), SDL_WaitThreadBarrier(), SetAudioStreamChannelMap(), ShutdownThreadpool(), SynchronousIO(), and UpdateAudioStreamFormatsPhysical().
SDL_TryLockMutex()
bool SDL_TryLockMutex (SDL_Mutex * mutex)
Try to lock a mutex without blocking.
This works just like SDL_LockMutex(), but if the mutex is not available, this function returns false immediately.
This technique is useful if you need exclusive access to a resource but don't want to wait for it, and will return to it to try again later.
This function returns true if passed a NULL mutex.
Parameters
mutex the mutex to try to lock.
Returns
true on success, false if the mutex would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockMutex
SDL_UnlockMutex
{
    bool result = true;
    if (mutex) {
#ifdef FAKE_RECURSIVE_MUTEX
        pthread_t this_thread = pthread_self();
        if (mutex->owner == this_thread) {
            ++mutex->recursive;
        } else {
            /* The order of operations is important.
               We set the locking thread id after we obtain the lock
               so unlocks from other threads will fail.
             */
            const int rc = pthread_mutex_trylock(&mutex->id);
            if (rc == 0) {
                mutex->owner = this_thread;
                mutex->recursive = 0;
            } else if (rc == EBUSY) {
                result = false;
            } else {
                SDL_assert(!"Error trying to lock mutex");  // assume we're in a lot of trouble if this assert fails.
                result = false;
            }
        }
#else
        const int rc = pthread_mutex_trylock(&mutex->id);
        if (rc != 0) {
            if (rc == EBUSY) {
                result = false;
            } else {
                SDL_assert(!"Error trying to lock mutex");  // assume we're in a lot of trouble if this assert fails.
                result = false;
            }
        }
#endif
    }
    return result;
}
References SDL_Mutex::id, SDL_Mutex::owner, SDL_Mutex::recursive, SDL_assert, SDL_GetCurrentThreadID(), SDL_TryWaitSemaphore(), and SDL_Mutex::sem.
Referenced by SDL_TryLockRWLockForReading_generic(), and SDL_TryLockRWLockForWriting_generic().
SDL_UnlockMutex()
void SDL_UnlockMutex (SDL_Mutex * mutex)
Unlock the mutex.
It is legal for the owning thread to lock an already-locked mutex. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive mutex").
It is illegal to unlock a mutex that has not been locked by the current thread, and doing so results in undefined behavior.
Parameters
mutex the mutex to unlock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockMutex
SDL_TryLockMutex
{
    if (mutex) {
#ifdef FAKE_RECURSIVE_MUTEX
        // We can only unlock the mutex if we own it
        if (pthread_self() == mutex->owner) {
            if (mutex->recursive) {
                --mutex->recursive;
            } else {
                /* The order of operations is important.
                   First reset the owner so another thread doesn't lock
                   the mutex and set the ownership before we reset it,
                   then release the lock semaphore.
                 */
                mutex->owner = 0;
                pthread_mutex_unlock(&mutex->id);
            }
        } else {
            SDL_SetError("mutex not owned by this thread");
            return;
        }
#else
        const int rc = pthread_mutex_unlock(&mutex->id);
        SDL_assert(rc == 0);  // assume we're in a lot of trouble if this assert fails.
#endif // FAKE_RECURSIVE_MUTEX
    }
}
References NULL, SDL_assert, SDL_GetCurrentThreadID(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_SetError(), and SDL_SignalSemaphore().
Referenced by AsyncIOTaskComplete(), AsyncIOThreadpoolWorker(), ClosePhysicalAudioDevice(), DestroyLogicalAudioDevice(), DestroyPhysicalAudioDevice(), generic_asyncioqueue_cancel_task(), generic_asyncioqueue_get_results(), generic_asyncioqueue_signal(), generic_asyncioqueue_wait_results(), GetAsyncIOTaskOutcome(), hidapi_thread_mutex_unlock(), ObtainLogicalAudioDevice(), PutAudioStreamBuffer(), QueueAsyncIOTask(), ReleaseAudioDevice(), ReleaseCamera(), RequestAsyncIO(), SDL_AddEventWatchList(), SDL_BindAudioStreams(), SDL_CameraThreadIterate(), SDL_ClearAudioStream(), SDL_CloseAsyncIO(), SDL_CopyProperties(), SDL_CreateTimer(), SDL_DestroySemaphore(), SDL_DispatchEventWatchList(), SDL_EnumerateProperties(), SDL_FilterEvents(), SDL_FlushAudioStream(), SDL_FlushEvents(), SDL_Generic_GetTLSData(), SDL_Generic_QuitTLSData(), SDL_Generic_SetTLSData(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), SDL_GetAudioStreamDevice(), SDL_GetAudioStreamFormat(), SDL_GetAudioStreamFrequencyRatio(), SDL_GetAudioStreamGain(), SDL_GetAudioStreamInputChannelMap(), SDL_GetAudioStreamOutputChannelMap(), SDL_GetAudioStreamProperties(), SDL_GetAudioStreamQueued(), SDL_GetBooleanProperty(), SDL_GetEnvironmentVariable(), SDL_GetEnvironmentVariables(), SDL_GetEventFilter(), SDL_GetFloatProperty(), SDL_GetLogOutputFunction(), SDL_GetLogPriority(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetSemaphoreValue(), SDL_GetStringProperty(), SDL_HasEvents(), SDL_LockRWLockForReading(), SDL_LogMessageV(), SDL_PeepEventsInternal(), SDL_PlaybackAudioThreadIterate(), SDL_PrivateSetProperty(), SDL_PutAudioStreamPlanarData(), SDL_QuitMainThreadCallbacks(), SDL_RecordingAudioThreadIterate(), SDL_RemoveEventWatchList(), SDL_RemoveTimer(), SDL_ReportAssertion(), SDL_ResetLogPriorities(), SDL_RunMainThreadCallbacks(), SDL_RunOnMainThread(), SDL_SetAudioStreamFormat(), SDL_SetAudioStreamFrequencyRatio(), SDL_SetAudioStreamGain(), SDL_SetAudioStreamGetCallback(), SDL_SetAudioStreamPutCallback(), SDL_SetEnvironmentVariable(), SDL_SetEventFilter(), SDL_SetLogOutputFunction(), SDL_SetLogPriorities(), SDL_SetLogPriority(), SDL_SetLogPriorityPrefix(), SDL_SetRenderTarget(), SDL_SignalSemaphore(), SDL_StartEventLoop(), SDL_StopEventLoop(), SDL_TryLockRWLockForReading_generic(), SDL_TryLockRWLockForWriting_generic(), SDL_TryLockSpinlock(), SDL_UnbindAudioStreams(), SDL_UnlockAudioStream(), SDL_UnlockJoysticks(), SDL_UnlockProperties(), SDL_UnlockRWLock(), SDL_UnlockSensors(), SDL_UnsetEnvironmentVariable(), SDL_WaitConditionTimeoutNS_generic(), SDL_WaitSemaphoreTimeoutNS(), SDL_WaitThreadBarrier(), SetAudioStreamChannelMap(), ShutdownThreadpool(), SynchronousIO(), and UpdateAudioStreamFormatsPhysical().