SDL3: SDL-main/src/thread/generic/SDL_sysrwlock.c File Reference
SDL_sysrwlock.c File Reference
#include "SDL_internal.h"
#include "SDL_systhread_c.h"
#include "../generic/SDL_sysrwlock_c.h"
Data Structures
struct SDL_RWLock
Macros
#define SDL_CreateRWLock_generic SDL_CreateRWLock
#define SDL_DestroyRWLock_generic SDL_DestroyRWLock
#define SDL_LockRWLockForReading_generic SDL_LockRWLockForReading
#define SDL_LockRWLockForWriting_generic SDL_LockRWLockForWriting
#define SDL_UnlockRWLock_generic SDL_UnlockRWLock
Functions
SDL_RWLock * SDL_CreateRWLock (void)
void SDL_DestroyRWLock (SDL_RWLock *rwlock)
void SDL_LockRWLockForReading (SDL_RWLock *rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
void SDL_LockRWLockForWriting (SDL_RWLock *rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
bool SDL_TryLockRWLockForReading (SDL_RWLock *rwlock)
bool SDL_TryLockRWLockForReading_generic (SDL_RWLock *rwlock)
bool SDL_TryLockRWLockForWriting (SDL_RWLock *rwlock)
bool SDL_TryLockRWLockForWriting_generic (SDL_RWLock *rwlock)
void SDL_UnlockRWLock (SDL_RWLock *rwlock) SDL_NO_THREAD_SAFETY_ANALYSIS
Macro Definition Documentation
SDL_CreateRWLock_generic
#define SDL_CreateRWLock_generic SDL_CreateRWLock
SDL_DestroyRWLock_generic
#define SDL_DestroyRWLock_generic SDL_DestroyRWLock
SDL_LockRWLockForReading_generic
#define SDL_LockRWLockForReading_generic SDL_LockRWLockForReading
SDL_LockRWLockForWriting_generic
#define SDL_LockRWLockForWriting_generic SDL_LockRWLockForWriting
SDL_UnlockRWLock_generic
#define SDL_UnlockRWLock_generic SDL_UnlockRWLock
Function Documentation
SDL_CreateRWLock()
SDL_RWLock * SDL_CreateRWLock (void)
Create a new read/write lock.
A read/write lock is useful for situations where you have multiple threads trying to access a resource that is rarely updated. All threads requesting a read-only lock will be allowed to run in parallel; if a thread requests a write lock, it will be provided exclusive access. This makes it safe for multiple threads to use a resource at the same time if they promise not to change it, and when it has to be changed, the rwlock will serve as a gateway to make sure those changes can be made safely.
In the right situation, a rwlock can be more efficient than a mutex, which only lets a single thread proceed at a time, even if it won't be modifying the data.
All newly-created read/write locks begin in the unlocked state.
Calls to SDL_LockRWLockForReading() and SDL_LockRWLockForWriting will not return while the rwlock is locked for writing by another thread. See SDL_TryLockRWLockForReading() and SDL_TryLockRWLockForWriting() to attempt to lock without blocking.
SDL read/write locks are only recursive for read-only locks! They are not guaranteed to be fair, or provide access in a FIFO manner! They are not guaranteed to favor writers. You may not lock a rwlock for both read-only and write access at the same time from the same thread (so you can't promote your read-only lock to a write lock without unlocking first).
Returns
the initialized and unlocked read/write lock or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyRWLock
SDL_LockRWLockForReading
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
    SDL_RWLock *rwlock = (SDL_RWLock *) SDL_calloc(1, sizeof (*rwlock));
    if (!rwlock) {
        return NULL;
    }
#ifndef SDL_THREADS_DISABLED
    rwlock->lock = SDL_CreateMutex();
    if (!rwlock->lock) {
        SDL_free(rwlock);
        return NULL;
    }
    rwlock->condition = SDL_CreateCondition();
    if (!rwlock->condition) {
        SDL_DestroyMutex(rwlock->lock);
        SDL_free(rwlock);
        return NULL;
    }
    SDL_SetAtomicInt(&rwlock->reader_count, 0);
    SDL_SetAtomicInt(&rwlock->writer_count, 0);
#endif
    return rwlock;
}
SDL_DestroyRWLock()
void SDL_DestroyRWLock (SDL_RWLock * rwlock)
Destroy a read/write lock created with SDL_CreateRWLock().
This function must be called on any read/write lock that is no longer needed. Failure to destroy a rwlock will result in a system memory or resource leak. While it is safe to destroy a rwlock that is unlocked, it is not safe to attempt to destroy a locked rwlock, and may result in undefined behavior depending on the platform.
Parameters
rwlock the rwlock to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRWLock
{
    if (rwlock) {
#ifndef SDL_THREADS_DISABLED
        SDL_DestroyMutex(rwlock->lock);
        SDL_DestroyCondition(rwlock->condition);
#endif
        SDL_free(rwlock);
    }
}
SDL_LockRWLockForReading()
void SDL_LockRWLockForReading (SDL_RWLock * rwlock)
Lock the read/write lock for read only operations.
This will block until the rwlock is available, which is to say it is not locked for writing by any other thread. Of all threads waiting to lock the rwlock, all may do so at the same time as long as they are requesting read-only access; if a thread wants to lock for writing, only one may do so at a time, and no other threads, read-only or not, may hold the lock at the same time.
It is legal for the owning thread to lock an already-locked rwlock for reading. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive rwlock").
Note that locking for writing is not recursive (this is only available to read-only locks).
It is illegal to request a read-only lock from a thread that already holds the write lock. Doing so results in undefined behavior. Unlock the write lock before requesting a read-only lock. (But, of course, if you have the write lock, you don't need further locks to read in any case.)
This function does not fail; if rwlock is NULL, it will return immediately having locked nothing. If the rwlock is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
rwlock the read/write lock to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_UnlockRWLock
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        // !!! FIXME: these don't have to be atomic, we always gate them behind a mutex.
        SDL_LockMutex(rwlock->lock);
        SDL_assert(SDL_GetAtomicInt(&rwlock->writer_count) == 0);  // shouldn't be able to grab lock if there's a writer!
        SDL_AddAtomicInt(&rwlock->reader_count, 1);
        SDL_UnlockMutex(rwlock->lock);   // other readers can attempt to share the lock.
    }
#endif
}
SDL_LockRWLockForWriting()
void SDL_LockRWLockForWriting (SDL_RWLock * rwlock)
Lock the read/write lock for write operations.
This will block until the rwlock is available, which is to say it is not locked for reading or writing by any other thread. Only one thread may hold the lock when it requests write access; all other threads, whether they also want to write or only want read-only access, must wait until the writer thread has released the lock.
It is illegal for the owning thread to lock an already-locked rwlock for writing (read-only may be locked recursively, writing can not). Doing so results in undefined behavior.
It is illegal to request a write lock from a thread that already holds a read-only lock. Doing so results in undefined behavior. Unlock the read-only lock before requesting a write lock.
This function does not fail; if rwlock is NULL, it will return immediately having locked nothing. If the rwlock is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
rwlock the read/write lock to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        SDL_LockMutex(rwlock->lock);
        while (SDL_GetAtomicInt(&rwlock->reader_count) > 0) {  // while something is holding the shared lock, keep waiting.
            SDL_WaitCondition(rwlock->condition, rwlock->lock);  // release the lock and wait for readers holding the shared lock to release it, regrab the lock.
        }
        // we hold the lock!
        SDL_AddAtomicInt(&rwlock->writer_count, 1);  // we let these be recursive, but the API doesn't require this. It _does_ trust you unlock correctly!
    }
#endif
}
SDL_TryLockRWLockForReading()
bool SDL_TryLockRWLockForReading (SDL_RWLock * rwlock)
Try to lock a read/write lock for reading without blocking.
This works just like SDL_LockRWLockForReading(), but if the rwlock is not available, then this function returns false immediately.
This technique is useful if you need access to a resource but don't want to wait for it, and will return to it to try again later.
Trying to lock for read-only access can succeed if other threads are holding read-only locks, as this won't prevent access.
This function returns true if passed a NULL rwlock.
Parameters
rwlock the rwlock to try to lock.
Returns
true on success, false if the lock would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
    return SDL_TryLockRWLockForReading_generic(rwlock);
}
SDL_TryLockRWLockForReading_generic()
bool SDL_TryLockRWLockForReading_generic (SDL_RWLock * rwlock)
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        if (!SDL_TryLockMutex(rwlock->lock)) {
            // !!! FIXME: there is a small window where a reader has to lock the mutex, and if we hit that, we will return SDL_RWLOCK_TIMEDOUT even though we could have shared the lock.
            return false;
        }
        SDL_assert(SDL_GetAtomicInt(&rwlock->writer_count) == 0);  // shouldn't be able to grab lock if there's a writer!
        SDL_AddAtomicInt(&rwlock->reader_count, 1);
        SDL_UnlockMutex(rwlock->lock);   // other readers can attempt to share the lock.
    }
#endif
    return true;
}
References SDL_RWLock::lock, SDL_RWLock::reader_count, SDL_AddAtomicInt(), SDL_assert, SDL_GetAtomicInt(), SDL_TryLockMutex(), SDL_UnlockMutex(), and SDL_RWLock::writer_count.
Referenced by SDL_TryLockRWLockForReading().
SDL_TryLockRWLockForWriting()
bool SDL_TryLockRWLockForWriting (SDL_RWLock * rwlock)
Try to lock a read/write lock for writing without blocking.
This works just like SDL_LockRWLockForWriting(), but if the rwlock is not available, then this function returns false immediately.
This technique is useful if you need exclusive access to a resource but don't want to wait for it, and will return to it to try again later.
It is illegal for the owning thread to lock an already-locked rwlock for writing (read-only may be locked recursively, writing can not). Doing so results in undefined behavior.
It is illegal to request a write lock from a thread that already holds a read-only lock. Doing so results in undefined behavior. Unlock the read-only lock before requesting a write lock.
This function returns true if passed a NULL rwlock.
Parameters
rwlock the rwlock to try to lock.
Returns
true on success, false if the lock would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_UnlockRWLock
{
    return SDL_TryLockRWLockForWriting_generic(rwlock);
}
SDL_TryLockRWLockForWriting_generic()
bool SDL_TryLockRWLockForWriting_generic (SDL_RWLock * rwlock)
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        if (!SDL_TryLockMutex(rwlock->lock)) {
            return false;
        }
        if (SDL_GetAtomicInt(&rwlock->reader_count) > 0) {  // a reader is using the shared lock, treat it as unavailable.
            SDL_UnlockMutex(rwlock->lock);
            return false;
        }
        // we hold the lock!
        SDL_AddAtomicInt(&rwlock->writer_count, 1);  // we let these be recursive, but the API doesn't require this. It _does_ trust you unlock correctly!
    }
#endif
    return true;
}
References SDL_RWLock::lock, SDL_RWLock::reader_count, SDL_AddAtomicInt(), SDL_GetAtomicInt(), SDL_TryLockMutex(), SDL_UnlockMutex(), and SDL_RWLock::writer_count.
Referenced by SDL_TryLockRWLockForWriting().
SDL_UnlockRWLock()
void SDL_UnlockRWLock (SDL_RWLock * rwlock)
Unlock the read/write lock.
Use this function to unlock the rwlock, whether it was locked for read-only or write operations.
It is legal for the owning thread to lock an already-locked read-only lock. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive rwlock").
It is illegal to unlock a rwlock that has not been locked by the current thread, and doing so results in undefined behavior.
Parameters
rwlock the rwlock to unlock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_TryLockRWLockForWriting
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        SDL_LockMutex(rwlock->lock);  // recursive lock for writers, readers grab lock to make sure things are sane.
        if (SDL_GetAtomicInt(&rwlock->reader_count) > 0) {  // we're a reader
            SDL_AddAtomicInt(&rwlock->reader_count, -1);
            SDL_BroadcastCondition(rwlock->condition);  // alert any pending writers to attempt to try to grab the lock again.
        } else if (SDL_GetAtomicInt(&rwlock->writer_count) > 0) {  // we're a writer
            SDL_AddAtomicInt(&rwlock->writer_count, -1);
            SDL_UnlockMutex(rwlock->lock);  // recursive unlock.
        }
        SDL_UnlockMutex(rwlock->lock);
    }
#endif
}