SDL3: SDL-main/src/stdlib/SDL_stdlib.c File Reference
SDL_stdlib.c File Reference
#include "SDL_internal.h"
#include "../libm/math_libm.h"
Functions
int SDL_abs (int x)
double SDL_acos (double val)
float SDL_acosf (float val)
void * SDL_aligned_alloc (size_t alignment, size_t size)
void SDL_aligned_free (void *mem)
double SDL_asin (double val)
float SDL_asinf (float val)
double SDL_atan (double x)
double SDL_atan2 (double y, double x)
float SDL_atan2f (float y, float x)
float SDL_atanf (float x)
double SDL_ceil (double x)
float SDL_ceilf (float x)
double SDL_copysign (double x, double y)
float SDL_copysignf (float x, float y)
double SDL_cos (double x)
float SDL_cosf (float x)
double SDL_exp (double x)
float SDL_expf (float x)
double SDL_fabs (double x)
float SDL_fabsf (float x)
double SDL_floor (double x)
float SDL_floorf (float x)
double SDL_fmod (double x, double y)
float SDL_fmodf (float x, float y)
int SDL_isalnum (int x)
int SDL_isalpha (int x)
int SDL_isblank (int x)
int SDL_iscntrl (int x)
int SDL_isdigit (int x)
int SDL_isgraph (int x)
int SDL_isinf (double x)
int SDL_isinff (float x)
int SDL_islower (int x)
int SDL_isnan (double x)
int SDL_isnanf (float x)
int SDL_isprint (int x)
int SDL_ispunct (int x)
int SDL_isspace (int x)
int SDL_isupper (int x)
int SDL_isxdigit (int x)
double SDL_log (double x)
double SDL_log10 (double x)
float SDL_log10f (float x)
float SDL_logf (float x)
long SDL_lround (double arg)
long SDL_lroundf (float arg)
double SDL_modf (double x, double *y)
float SDL_modff (float x, float *y)
double SDL_pow (double x, double y)
float SDL_powf (float x, float y)
double SDL_round (double arg)
float SDL_roundf (float arg)
double SDL_scalbn (double x, int n)
float SDL_scalbnf (float x, int n)
double SDL_sin (double x)
float SDL_sinf (float x)
double SDL_sqrt (double x)
float SDL_sqrtf (float x)
double SDL_tan (double x)
float SDL_tanf (float x)
int SDL_tolower (int x)
int SDL_toupper (int x)
double SDL_trunc (double x)
float SDL_truncf (float x)
Function Documentation
SDL_abs()
int SDL_abs (int x)
Compute the absolute value of x.
Parameters
x an integer value.
Returns
the absolute value of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_ABS
    return abs(x);
#else
    return (x < 0) ? -x : x;
#endif
}
Referenced by ChooseBestCameraSpec(), RenderLineBresenham(), and SDL_SendJoystickAxis().
SDL_acos()
double SDL_acos (double x)
Compute the arc cosine of x.
The definition of y = acos(x) is x = cos(y).
Domain: -1 <= x <= 1
Range: 0 <= y <= Pi
This function operates on double-precision floating point values, use SDL_acosf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc cosine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_acosf
SDL_asin
SDL_cos
{
#ifdef HAVE_ACOS
    return acos(val);
#else
    double result;
    if (val == -1.0) {
        result = SDL_PI_D;
    } else {
        result = SDL_atan(SDL_sqrt(1.0 - val * val) / val);
        if (result < 0.0) {
            result += SDL_PI_D;
        }
    }
    return result;
#endif
}
References SDL_atan(), SDL_PI_D, and SDL_sqrt().
Referenced by SDL_acosf(), and SDL_asin().
SDL_acosf()
float SDL_acosf (float x)
Compute the arc cosine of x.
The definition of y = acos(x) is x = cos(y).
Domain: -1 <= x <= 1
Range: 0 <= y <= Pi
This function operates on single-precision floating point values, use SDL_acos for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc cosine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_acos
SDL_asinf
SDL_cosf
{
#ifdef HAVE_ACOSF
    return acosf(val);
#else
    return (float)SDL_acos((double)val);
#endif
}
References SDL_acos().
SDL_aligned_alloc()
void * SDL_aligned_alloc (size_t alignment, size_t size)
Allocate memory aligned to a specific alignment.
The memory returned by this function must be freed with SDL_aligned_free(), not SDL_free().
If alignment is less than the size of void *, it will be increased to match that.
The returned memory address will be a multiple of the alignment value, and the size of the memory allocated will be a multiple of the alignment value.
Parameters
alignment the alignment of the memory.
size the size to allocate.
Returns
a pointer to the aligned memory, or NULL if allocation failed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_aligned_free
{
    size_t padding;
    Uint8 *result = NULL;
    size_t requested_size = size;
    if (alignment < sizeof(void *)) {
        alignment = sizeof(void *);
    }
    padding = (alignment - (size % alignment));
    if (SDL_size_add_check_overflow(size, alignment, &size) &&
        SDL_size_add_check_overflow(size, sizeof(void *), &size) &&
        SDL_size_add_check_overflow(size, padding, &size)) {
        void *original = SDL_malloc(size);
        if (original) {
            // Make sure we have enough space to store the original pointer
            result = (Uint8 *)original + sizeof(original);
            // Align the pointer we're going to return
            result += alignment - (((size_t)result) % alignment);
            // Store the original pointer right before the returned value
            SDL_memcpy(result - sizeof(original), &original, sizeof(original));
            // Initialize the padding to zero
            if (padding > 0) {
                SDL_memset(result + requested_size, 0, padding);
            }
        }
    }
    return result;
}
References NULL, SDL_malloc(), SDL_memcpy, SDL_memset, and SDL_size_add_check_overflow().
Referenced by EnsureAudioStreamWorkBufferSize(), OpenPhysicalAudioDevice(), PS2AUDIO_OpenDevice(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CreateSurface(), SDL_ResetAudioQueueHistory(), SDL_SetAudioPostmixCallback(), and ZombieAcquireFrame().
SDL_aligned_free()
void SDL_aligned_free (void * mem)
Free memory allocated by SDL_aligned_alloc().
The pointer is no longer valid after this call and cannot be dereferenced anymore.
If mem is NULL, this function does nothing.
Parameters
mem a pointer previously returned by SDL_aligned_alloc(), or NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_aligned_alloc
{
    if (mem) {
        void *original;
        SDL_memcpy(&original, ((Uint8 *)mem - sizeof(original)), sizeof(original));
        SDL_free(original);
    }
}
References SDL_free(), and SDL_memcpy.
Referenced by ClosePhysicalAudioDevice(), ClosePhysicalCamera(), EnsureAudioStreamWorkBufferSize(), PS2AUDIO_CloseDevice(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_DestroyAudioQueue(), SDL_DestroyAudioStream(), SDL_DestroySurface(), and SDL_ResetAudioQueueHistory().
SDL_asin()
double SDL_asin (double x)
Compute the arc sine of x.
The definition of y = asin(x) is x = sin(y).
Domain: -1 <= x <= 1
Range: -Pi/2 <= y <= Pi/2
This function operates on double-precision floating point values, use SDL_asinf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc sine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_asinf
SDL_acos
SDL_sin
{
#ifdef HAVE_ASIN
    return asin(val);
#else
    double result;
    if (val == -1.0) {
        result = -(SDL_PI_D / 2.0);
    } else {
        result = (SDL_PI_D / 2.0) - SDL_acos(val);
    }
    return result;
#endif
}
References SDL_acos(), and SDL_PI_D.
Referenced by SDL_asinf().
SDL_asinf()
float SDL_asinf (float x)
Compute the arc sine of x.
The definition of y = asin(x) is x = sin(y).
Domain: -1 <= x <= 1
Range: -Pi/2 <= y <= Pi/2
This function operates on single-precision floating point values, use SDL_asin for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc sine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_asin
SDL_acosf
SDL_sinf
{
#ifdef HAVE_ASINF
    return asinf(val);
#else
    return (float)SDL_asin((double)val);
#endif
}
References SDL_asin().
SDL_atan()
double SDL_atan (double x)
Compute the arc tangent of x.
The definition of y = atan(x) is x = tan(y).
Domain: -INF <= x <= INF
Range: -Pi/2 <= y <= Pi/2
This function operates on double-precision floating point values, use SDL_atanf for single-precision floats.
To calculate the arc tangent of y / x, use SDL_atan2.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc tangent of of x in radians, or 0 if x = 0.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atanf
SDL_atan2
SDL_tan
{
#ifdef HAVE_ATAN
    return atan(x);
#else
    return SDL_uclibc_atan(x);
#endif
}
References atan, and SDL_uclibc_atan().
Referenced by SDL_acos(), and SDL_atanf().
SDL_atan2()
double SDL_atan2 (double y, double x)
Compute the arc tangent of y / x, using the signs of x and y to adjust the result's quadrant.
The definition of z = atan2(x, y) is y = x tan(z), where the quadrant of z is determined based on the signs of x and y.
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -Pi <= y <= Pi
This function operates on double-precision floating point values, use SDL_atan2f for single-precision floats.
To calculate the arc tangent of a single value, use SDL_atan.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
y floating point value of the numerator (y coordinate).
x floating point value of the denominator (x coordinate).
Returns
arc tangent of of y / x in radians, or, if x = 0, either -Pi/2, 0, or Pi/2, depending on the value of y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atan2f
SDL_atan
SDL_tan
{
#ifdef HAVE_ATAN2
    return atan2(y, x);
#else
    return SDL_uclibc_atan2(y, x);
#endif
}
References SDL_uclibc_atan2().
Referenced by SDL_atan2f().
SDL_atan2f()
float SDL_atan2f (float y, float x)
Compute the arc tangent of y / x, using the signs of x and y to adjust the result's quadrant.
The definition of z = atan2(x, y) is y = x tan(z), where the quadrant of z is determined based on the signs of x and y.
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -Pi <= y <= Pi
This function operates on single-precision floating point values, use SDL_atan2 for double-precision floats.
To calculate the arc tangent of a single value, use SDL_atanf.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
y floating point value of the numerator (y coordinate).
x floating point value of the denominator (x coordinate).
Returns
arc tangent of of y / x in radians, or, if x = 0, either -Pi/2, 0, or Pi/2, depending on the value of y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atan2
SDL_atan
SDL_tan
{
#ifdef HAVE_ATAN2F
    return atan2f(y, x);
#else
    return (float)SDL_atan2((double)y, (double)x);
#endif
}
References SDL_atan2().
SDL_atanf()
float SDL_atanf (float x)
Compute the arc tangent of x.
The definition of y = atan(x) is x = tan(y).
Domain: -INF <= x <= INF
Range: -Pi/2 <= y <= Pi/2
This function operates on single-precision floating point values, use SDL_atan for dboule-precision floats.
To calculate the arc tangent of y / x, use SDL_atan2f.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc tangent of of x in radians, or 0 if x = 0.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atan
SDL_atan2f
SDL_tanf
{
#ifdef HAVE_ATANF
    return atanf(x);
#else
    return (float)SDL_atan((double)x);
#endif
}
References SDL_atan().
SDL_ceil()
double SDL_ceil (double x)
Compute the ceiling of x.
The ceiling of x is the smallest integer y such that y > x, i.e x rounded up to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_ceilf for single-precision floats.
Parameters
x floating point value.
Returns
the ceiling of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ceilf
SDL_floor
SDL_trunc
SDL_round
SDL_lround
{
#ifdef HAVE_CEIL
    return ceil(x);
#else
    double integer = SDL_floor(x);
    double fraction = x - integer;
    if (fraction > 0.0) {
        integer += 1.0;
    }
    return integer;
#endif // HAVE_CEIL
}
References SDL_floor().
Referenced by SDL_ceilf(), SDL_round(), and SDL_trunc().
SDL_ceilf()
float SDL_ceilf (float x)
Compute the ceiling of x.
The ceiling of x is the smallest integer y such that y > x, i.e x rounded up to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_ceil for double-precision floats.
Parameters
x floating point value.
Returns
the ceiling of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ceil
SDL_floorf
SDL_truncf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_CEILF
    return ceilf(x);
#else
    return (float)SDL_ceil((double)x);
#endif
}
References SDL_ceil().
Referenced by SDL_GetRenderSafeArea(), SDL_GetRenderViewport(), SDL_GetWindowSizeInPixels(), SDL_MaybeEnableWarpEmulation(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), UpdatePixelClipRect(), and UpdatePixelViewport().
SDL_copysign()
double SDL_copysign (double x, double y)
Copy the sign of one floating-point value to another.
The definition of copysign is that copysign(x, y) = abs(x) * sign(y).
Domain: -INF <= x <= INF, -INF <= y <= f
Range: -INF <= z <= INF
This function operates on double-precision floating point values, use SDL_copysignf for single-precision floats.
Parameters
x floating point value to use as the magnitude.
y floating point value to use as the sign.
Returns
the floating point value with the sign of y and the magnitude of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_copysignf
SDL_fabs
{
#ifdef HAVE_COPYSIGN
    return copysign(x, y);
#elif defined(HAVE__COPYSIGN)
    return _copysign(x, y);
#elif defined(__WATCOMC__) && defined(__386__)
    // this is nasty as hell, but it works..
    unsigned int *xi = (unsigned int *)&x,
                 *yi = (unsigned int *)&y;
    xi[1] = (yi[1] & 0x80000000) | (xi[1] & 0x7fffffff);
    return x;
#else
    return SDL_uclibc_copysign(x, y);
#endif // HAVE_COPYSIGN
}
References copysign, and SDL_uclibc_copysign().
Referenced by SDL_copysignf().
SDL_copysignf()
float SDL_copysignf (float x, float y)
Copy the sign of one floating-point value to another.
The definition of copysign is that copysign(x, y) = abs(x) * sign(y).
Domain: -INF <= x <= INF, -INF <= y <= f
Range: -INF <= z <= INF
This function operates on single-precision floating point values, use SDL_copysign for double-precision floats.
Parameters
x floating point value to use as the magnitude.
y floating point value to use as the sign.
Returns
the floating point value with the sign of y and the magnitude of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_copysign
SDL_fabsf
{
#ifdef HAVE_COPYSIGNF
    return copysignf(x, y);
#else
    return (float)SDL_copysign((double)x, (double)y);
#endif
}
References SDL_copysign().
SDL_cos()
double SDL_cos (double x)
Compute the cosine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on double-precision floating point values, use SDL_cosf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
cosine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_cosf
SDL_acos
SDL_sin
{
#ifdef HAVE_COS
    return cos(x);
#else
    return SDL_uclibc_cos(x);
#endif
}
References cos, and SDL_uclibc_cos().
Referenced by SDL_cosf().
SDL_cosf()
float SDL_cosf (float x)
Compute the cosine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on single-precision floating point values, use SDL_cos for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
cosine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_cos
SDL_acosf
SDL_sinf
{
#ifdef HAVE_COSF
    return cosf(x);
#else
    return (float)SDL_cos((double)x);
#endif
}
References SDL_cos().
Referenced by SDL_RenderTextureRotated().
SDL_exp()
double SDL_exp (double x)
Compute the exponential of x.
The definition of y = exp(x) is y = e^x, where e is the base of the natural logarithm. The inverse is the natural logarithm, SDL_log.
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
The output will overflow if exp(x) is too large to be represented.
This function operates on double-precision floating point values, use SDL_expf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
value of e^x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_expf
SDL_log
{
#ifdef HAVE_EXP
    return exp(x);
#else
    return SDL_uclibc_exp(x);
#endif
}
References SDL_uclibc_exp().
Referenced by SDL_expf().
SDL_expf()
float SDL_expf (float x)
Compute the exponential of x.
The definition of y = exp(x) is y = e^x, where e is the base of the natural logarithm. The inverse is the natural logarithm, SDL_logf.
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
The output will overflow if exp(x) is too large to be represented.
This function operates on single-precision floating point values, use SDL_exp for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
value of e^x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_exp
SDL_logf
{
#ifdef HAVE_EXPF
    return expf(x);
#else
    return (float)SDL_exp((double)x);
#endif
}
References SDL_exp().
SDL_fabs()
double SDL_fabs (double x)
Compute the absolute value of x
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
This function operates on double-precision floating point values, use SDL_fabsf for single-precision floats.
Parameters
x floating point value to use as the magnitude.
Returns
the absolute value of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fabsf
{
#ifdef HAVE_FABS
    return fabs(x);
#else
    return SDL_uclibc_fabs(x);
#endif
}
References fabs, and SDL_uclibc_fabs().
Referenced by SDL_fabsf(), and SDL_PrivateSendMouseButton().
SDL_fabsf()
float SDL_fabsf (float x)
Compute the absolute value of x
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
This function operates on single-precision floating point values, use SDL_fabs for double-precision floats.
Parameters
x floating point value to use as the magnitude.
Returns
the absolute value of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fabs
{
#ifdef HAVE_FABSF
    return fabsf(x);
#else
    return (float)SDL_fabs((double)x);
#endif
}
References SDL_fabs().
Referenced by ChooseBestCameraSpec(), SDL_GetClosestFullscreenDisplayMode(), SDL_RectsEqualEpsilon(), and UpdateLogicalPresentation().
SDL_floor()
double SDL_floor (double x)
Compute the floor of x.
The floor of x is the largest integer y such that y > x, i.e x rounded down to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_floorf for single-precision floats.
Parameters
x floating point value.
Returns
the floor of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_floorf
SDL_ceil
SDL_trunc
SDL_round
SDL_lround
{
#ifdef HAVE_FLOOR
    return floor(x);
#else
    return SDL_uclibc_floor(x);
#endif
}
References floor, and SDL_uclibc_floor().
Referenced by SDL_ceil(), SDL_floorf(), SDL_round(), and SDL_trunc().
SDL_floorf()
float SDL_floorf (float x)
Compute the floor of x.
The floor of x is the largest integer y such that y > x, i.e x rounded down to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_floor for double-precision floats.
Parameters
x floating point value.
Returns
the floor of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_floor
SDL_ceilf
SDL_truncf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_FLOORF
    return floorf(x);
#else
    return (float)SDL_floor((double)x);
#endif
}
References SDL_floor().
Referenced by SDL_MaybeEnableWarpEmulation(), UpdateLogicalPresentation(), UpdatePixelClipRect(), and UpdatePixelViewport().
SDL_fmod()
double SDL_fmod (double x, double y)
Return the floating-point remainder of x / y
Divides x by y, and returns the remainder.
Domain: -INF <= x <= INF, -INF <= y <= INF, y != 0
Range: -y <= z <= y
This function operates on double-precision floating point values, use SDL_fmodf for single-precision floats.
Parameters
x the numerator.
y the denominator. Must not be 0.
Returns
the remainder of x / y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fmodf
SDL_modf
SDL_trunc
SDL_ceil
SDL_floor
SDL_round
SDL_lround
{
#ifdef HAVE_FMOD
    return fmod(x, y);
#else
    return SDL_uclibc_fmod(x, y);
#endif
}
References SDL_uclibc_fmod().
Referenced by SDL_fmodf().
SDL_fmodf()
float SDL_fmodf (float x, float y)
Return the floating-point remainder of x / y
Divides x by y, and returns the remainder.
Domain: -INF <= x <= INF, -INF <= y <= INF, y != 0
Range: -y <= z <= y
This function operates on single-precision floating point values, use SDL_fmod for double-precision floats.
Parameters
x the numerator.
y the denominator. Must not be 0.
Returns
the remainder of x / y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fmod
SDL_truncf
SDL_modff
SDL_ceilf
SDL_floorf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_FMODF
    return fmodf(x, y);
#else
    return (float)SDL_fmod((double)x, (double)y);
#endif
}
References SDL_fmod().
SDL_isalnum()
int SDL_isalnum (int x)
Query if a character is alphabetic (a letter) or a number.
WARNING: Regardless of system locale, this will only treat ASCII values for English 'a-z', 'A-Z', and '0-9' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (SDL_isalpha(x)) || (SDL_isdigit(x)); }
References SDL_isalpha(), and SDL_isdigit().
Referenced by SDL_ispunct().
SDL_isalpha()
int SDL_isalpha (int x)
Query if a character is alphabetic (a letter).
WARNING: Regardless of system locale, this will only treat ASCII values for English 'a-z' and 'A-Z' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (SDL_isupper(x)) || (SDL_islower(x)); }
References SDL_islower(), and SDL_isupper().
Referenced by SDL_isalnum().
SDL_isblank()
int SDL_isblank (int x)
Report if a character is blank (a space or tab).
WARNING: Regardless of system locale, this will only treat ASCII values 0x20 (space) or 0x9 (tab) as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) == ' ') || ((x) == '\t'); }
SDL_iscntrl()
int SDL_iscntrl (int x)
Report if a character is a control character.
WARNING: Regardless of system locale, this will only treat ASCII values 0 through 0x1F, and 0x7F, as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (((x) >= '\0') && ((x) <= '\x1f')) || ((x) == '\x7f'); }
Referenced by SDL_SendKeyboardText().
SDL_isdigit()
int SDL_isdigit (int x)
Report if a character is a numeric digit.
WARNING: Regardless of system locale, this will only treat ASCII values '0' (0x30) through '9' (0x39), as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= '0') && ((x) <= '9'); }
Referenced by ParseLogCategory(), ParseLogPriority(), SDL_GetStringInteger(), SDL_isalnum(), SDL_isxdigit(), SDL_PrivateParseGamepadElement(), SDL_ScanFloat(), and SDL_SetKeymap().
SDL_isgraph()
int SDL_isgraph (int x)
Report if a character is any "printable" except space.
Be advised that "printable" has a definition that goes back to text terminals from the dawn of computing, making this a sort of special case function that is not suitable for Unicode (or most any) text management.
WARNING: Regardless of system locale, this is equivalent to ‘(SDL_isprint(x)) && ((x) != ’ ')`.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isprint
{ return (SDL_isprint(x)) && ((x) != ' '); }
References SDL_isprint().
Referenced by SDL_ispunct().
SDL_isinf()
int SDL_isinf (double x)
Return whether the value is infinity.
Parameters
x double-precision floating point value.
Returns
non-zero if the value is infinity, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isinff
{
#ifdef HAVE_ISINF
    return isinf(x);
#else
    return SDL_uclibc_isinf(x);
#endif
}
References SDL_uclibc_isinf().
SDL_isinff()
int SDL_isinff (float x)
Return whether the value is infinity.
Parameters
x floating point value.
Returns
non-zero if the value is infinity, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isinf
{
#ifdef HAVE_ISINF_FLOAT_MACRO
    return isinf(x);
#elif defined(HAVE_ISINFF)
    return isinff(x);
#else
    return SDL_uclibc_isinff(x);
#endif
}
References SDL_uclibc_isinff().
SDL_islower()
int SDL_islower (int x)
Report if a character is lower case.
WARNING: Regardless of system locale, this will only treat ASCII values 'a' through 'z' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'a') && ((x) <= 'z'); }
Referenced by SDL_isalpha().
SDL_isnan()
int SDL_isnan (double x)
Return whether the value is NaN.
Parameters
x double-precision floating point value.
Returns
non-zero if the value is NaN, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isnanf
{
#ifdef HAVE_ISNAN
    return isnan(x);
#else
    return SDL_uclibc_isnan(x);
#endif
}
References SDL_uclibc_isnan().
SDL_isnanf()
int SDL_isnanf (float x)
Return whether the value is NaN.
Parameters
x floating point value.
Returns
non-zero if the value is NaN, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isnan
{
#ifdef HAVE_ISNAN_FLOAT_MACRO
    return isnan(x);
#elif defined(HAVE_ISNANF)
    return isnanf(x);
#else
    return SDL_uclibc_isnanf(x);
#endif
}
References SDL_uclibc_isnanf().
SDL_isprint()
int SDL_isprint (int x)
Report if a character is "printable".
Be advised that "printable" has a definition that goes back to text terminals from the dawn of computing, making this a sort of special case function that is not suitable for Unicode (or most any) text management.
WARNING: Regardless of system locale, this will only treat ASCII values ' ' (0x20) through '~' (0x7E) as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= ' ') && ((x) < '\x7f'); }
Referenced by SDL_isgraph(), and Translate_to_text().
SDL_ispunct()
int SDL_ispunct (int x)
Report if a character is a punctuation mark.
WARNING: Regardless of system locale, this is equivalent to ((SDL_isgraph(x)) && (!SDL_isalnum(x))).
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isgraph
SDL_isalnum
{ return (SDL_isgraph(x)) && (!SDL_isalnum(x)); }
References SDL_isalnum(), and SDL_isgraph().
SDL_isspace()
int SDL_isspace (int x)
Report if a character is whitespace.
WARNING: Regardless of system locale, this will only treat the following ASCII values as true:
space (0x20)
tab (0x09)
newline (0x0A)
vertical tab (0x0B)
form feed (0x0C)
return (0x0D)
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) == ' ') || ((x) == '\t') || ((x) == '\r') || ((x) == '\n') || ((x) == '\f') || ((x) == '\v'); }
Referenced by build_locales_from_csv_string(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_ScanFloat(), SDL_ScanUnsignedLongLongInternal(), SDL_ScanUnsignedLongLongInternalW(), and SDL_vsscanf().
SDL_isupper()
int SDL_isupper (int x)
Report if a character is upper case.
WARNING: Regardless of system locale, this will only treat ASCII values 'A' through 'Z' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'A') && ((x) <= 'Z'); }
Referenced by SDL_isalpha().
SDL_isxdigit()
int SDL_isxdigit (int x)
Report if a character is a hexadecimal digit.
WARNING: Regardless of system locale, this will only treat ASCII values 'A' through 'F', 'a' through 'f', and '0' through '9', as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (((x) >= 'A') && ((x) <= 'F')) || (((x) >= 'a') && ((x) <= 'f')) || (SDL_isdigit(x)); }
References SDL_isdigit().
SDL_log()
double SDL_log (double x)
Compute the natural logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on double-precision floating point values, use SDL_logf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the natural logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_logf
SDL_log10
SDL_exp
{
#ifdef HAVE_LOG
    return log(x);
#else
    return SDL_uclibc_log(x);
#endif
}
References SDL_uclibc_log().
Referenced by SDL_logf().
SDL_log10()
double SDL_log10 (double x)
Compute the base-10 logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on double-precision floating point values, use SDL_log10f for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_log10f
SDL_log
SDL_pow
{
#ifdef HAVE_LOG10
    return log10(x);
#else
    return SDL_uclibc_log10(x);
#endif
}
References SDL_uclibc_log10().
Referenced by SDL_log10f().
SDL_log10f()
float SDL_log10f (float x)
Compute the base-10 logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on single-precision floating point values, use SDL_log10 for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_log10
SDL_logf
SDL_powf
{
#ifdef HAVE_LOG10F
    return log10f(x);
#else
    return (float)SDL_log10((double)x);
#endif
}
References SDL_log10().
SDL_logf()
float SDL_logf (float x)
Compute the natural logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on single-precision floating point values, use SDL_log for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the natural logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_log
SDL_expf
{
#ifdef HAVE_LOGF
    return logf(x);
#else
    return (float)SDL_log((double)x);
#endif
}
References SDL_log().
SDL_lround()
long SDL_lround (double x)
Round x to the nearest integer representable as a long
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: MIN_LONG <= y <= MAX_LONG
This function operates on double-precision floating point values, use SDL_lroundf for single-precision floats. To get the result as a floating-point type, use SDL_round.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_lroundf
SDL_round
SDL_floor
SDL_ceil
SDL_trunc
{
#if defined HAVE_LROUND
    return lround(arg);
#else
    return (long)SDL_round(arg);
#endif
}
References SDL_round().
SDL_lroundf()
long SDL_lroundf (float x)
Round x to the nearest integer representable as a long
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: MIN_LONG <= y <= MAX_LONG
This function operates on single-precision floating point values, use SDL_lround for double-precision floats. To get the result as a floating-point type, use SDL_roundf.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_lround
SDL_roundf
SDL_floorf
SDL_ceilf
SDL_truncf
{
#if defined HAVE_LROUNDF
    return lroundf(arg);
#else
    return (long)SDL_round((double)arg);
#endif
}
References SDL_round().
SDL_modf()
double SDL_modf (double x, double * y)
Split x into integer and fractional parts
This function operates on double-precision floating point values, use SDL_modff for single-precision floats.
Parameters
x floating point value.
y output pointer to store the integer part of x.
Returns
the fractional part of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_modff
SDL_trunc
SDL_fmod
{
#ifdef HAVE_MODF
    return modf(x, y);
#else
    return SDL_uclibc_modf(x, y);
#endif
}
References modf, and SDL_uclibc_modf().
Referenced by SDL_modff(), and SDL_PrintFloat().
SDL_modff()
float SDL_modff (float x, float * y)
Split x into integer and fractional parts
This function operates on single-precision floating point values, use SDL_modf for double-precision floats.
Parameters
x floating point value.
y output pointer to store the integer part of x.
Returns
the fractional part of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_modf
SDL_truncf
SDL_fmodf
{
#ifdef HAVE_MODFF
    return modff(x, y);
#else
    double double_result, double_y;
    double_result = SDL_modf((double)x, &double_y);
    *y = (float)double_y;
    return (float)double_result;
#endif
}
References SDL_modf().
Referenced by SDL_PrivateSendMouseMotion(), SDL_RenderTextureTiled_Iterate(), and SDL_SendMouseWheel().
SDL_pow()
double SDL_pow (double x, double y)
Raise x to the power y
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -INF <= z <= INF
If y is the base of the natural logarithm (e), consider using SDL_exp instead.
This function operates on double-precision floating point values, use SDL_powf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x the base.
y the exponent.
Returns
x raised to the power y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_powf
SDL_exp
SDL_log
{
#ifdef HAVE_POW
    return pow(x, y);
#else
    return SDL_uclibc_pow(x, y);
#endif
}
References SDL_uclibc_pow().
Referenced by decode_fraction(), and SDL_powf().
SDL_powf()
float SDL_powf (float x, float y)
Raise x to the power y
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -INF <= z <= INF
If y is the base of the natural logarithm (e), consider using SDL_exp instead.
This function operates on single-precision floating point values, use SDL_pow for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x the base.
y the exponent.
Returns
x raised to the power y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_pow
SDL_expf
SDL_logf
{
#ifdef HAVE_POWF
    return powf(x, y);
#else
    return (float)SDL_pow((double)x, (double)y);
#endif
}
References SDL_pow().
Referenced by SDL_PQfromNits(), SDL_PQtoNits(), SDL_sRGBfromLinear(), and SDL_sRGBtoLinear().
SDL_round()
double SDL_round (double x)
Round x to the nearest integer.
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_roundf for single-precision floats. To get the result as an integer type, use SDL_lround.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_roundf
SDL_lround
SDL_floor
SDL_ceil
SDL_trunc
{
#if defined HAVE_ROUND
    return round(arg);
#else
    if (arg >= 0.0) {
        return SDL_floor(arg + 0.5);
    } else {
        return SDL_ceil(arg - 0.5);
    }
#endif
}
References SDL_ceil(), and SDL_floor().
Referenced by DUMMYAUDIO_OpenDevice(), SDL_BlitSurfaceScaled(), SDL_GetNumberProperty(), SDL_GetSurfaceImage(), SDL_GetSystemRAM(), SDL_lround(), SDL_lroundf(), SDL_PrintFloat(), SDL_roundf(), and SDL_WriteSurfacePixelFloat().
SDL_roundf()
float SDL_roundf (float x)
Round x to the nearest integer.
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_round for double-precision floats. To get the result as an integer type, use SDL_lroundf.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_round
SDL_lroundf
SDL_floorf
SDL_ceilf
SDL_truncf
{
#if defined HAVE_ROUNDF
    return roundf(arg);
#else
    return (float)SDL_round((double)arg);
#endif
}
References SDL_round().
Referenced by IOS_MFIJoystickUpdate(), RenderLinesWithRectsF(), SDL_Blit_Slow_Float(), SDL_BlitSurface9Grid(), SDL_ClearSurface(), SDL_GetTextureAlphaMod(), SDL_GetTextureColorMod(), SDL_MixAudio(), SDL_SetWindowSize(), and WriteFloatPixel().
SDL_scalbn()
double SDL_scalbn (double x, int n)
Scale x by an integer power of two.
Multiplies x by the nth power of the floating point radix (always 2).
Domain: -INF <= x <= INF, n integer
Range: -INF <= y <= INF
This function operates on double-precision floating point values, use SDL_scalbnf for single-precision floats.
Parameters
x floating point value to be scaled.
n integer exponent.
Returns
x * 2^n.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_scalbnf
SDL_pow
{
#ifdef HAVE_SCALBN
    return scalbn(x, n);
#elif defined(HAVE__SCALB)
    return _scalb(x, n);
#elif defined(HAVE_LIBC) && defined(HAVE_FLOAT_H) && (FLT_RADIX == 2)
    /* from scalbn(3): If FLT_RADIX equals 2 (which is
     * usual), then scalbn() is equivalent to ldexp(3). */
    return ldexp(x, n);
#else
    return SDL_uclibc_scalbn(x, n);
#endif
}
References scalbn, and SDL_uclibc_scalbn().
Referenced by SDL_scalbnf().
SDL_scalbnf()
float SDL_scalbnf (float x, int n)
Scale x by an integer power of two.
Multiplies x by the nth power of the floating point radix (always 2).
Domain: -INF <= x <= INF, n integer
Range: -INF <= y <= INF
This function operates on single-precision floating point values, use SDL_scalbn for double-precision floats.
Parameters
x floating point value to be scaled.
n integer exponent.
Returns
x * 2^n.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_scalbn
SDL_powf
{
#ifdef HAVE_SCALBNF
    return scalbnf(x, n);
#else
    return (float)SDL_scalbn((double)x, n);
#endif
}
References SDL_scalbn().
SDL_sin()
double SDL_sin (double x)
Compute the sine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on double-precision floating point values, use SDL_sinf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
sine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sinf
SDL_asin
SDL_cos
{
#ifdef HAVE_SIN
    return sin(x);
#else
    return SDL_uclibc_sin(x);
#endif
}
References SDL_uclibc_sin(), and sin.
Referenced by SDL_sinf().
SDL_sinf()
float SDL_sinf (float x)
Compute the sine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on single-precision floating point values, use SDL_sin for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
sine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sin
SDL_asinf
SDL_cosf
{
#ifdef HAVE_SINF
    return sinf(x);
#else
    return (float)SDL_sin((double)x);
#endif
}
References SDL_sin().
Referenced by SDL_RenderTextureRotated(), and SincTable().
SDL_sqrt()
double SDL_sqrt (double x)
Compute the square root of x.
Domain: 0 <= x <= INF
Range: 0 <= y <= INF
This function operates on double-precision floating point values, use SDL_sqrtf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than or equal to 0.
Returns
square root of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sqrtf
{
#ifdef HAVE_SQRT
    return sqrt(x);
#else
    return SDL_uclibc_sqrt(x);
#endif
}
References SDL_uclibc_sqrt().
Referenced by SDL_acos(), and SDL_sqrtf().
SDL_sqrtf()
float SDL_sqrtf (float x)
Compute the square root of x.
Domain: 0 <= x <= INF
Range: 0 <= y <= INF
This function operates on single-precision floating point values, use SDL_sqrt for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than or equal to 0.
Returns
square root of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sqrt
{
#ifdef HAVE_SQRTF
    return sqrtf(x);
#else
    return (float)SDL_sqrt((double)x);
#endif
}
References SDL_sqrt().
Referenced by GenerateResamplerFilter().
SDL_tan()
double SDL_tan (double x)
Compute the tangent of x.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF
This function operates on double-precision floating point values, use SDL_tanf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
tangent of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_tanf
SDL_sin
SDL_cos
SDL_atan
SDL_atan2
{
#ifdef HAVE_TAN
    return tan(x);
#else
    return SDL_uclibc_tan(x);
#endif
}
References SDL_uclibc_tan(), and tan.
Referenced by SDL_tanf().
SDL_tanf()
float SDL_tanf (float x)
Compute the tangent of x.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF
This function operates on single-precision floating point values, use SDL_tan for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
tangent of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_tan
SDL_sinf
SDL_cosf
SDL_atanf
SDL_atan2f
{
#ifdef HAVE_TANF
    return tanf(x);
#else
    return (float)SDL_tan((double)x);
#endif
}
References SDL_tan().
SDL_tolower()
int SDL_tolower (int x)
Convert low-ASCII English letters to lowercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'A' through 'Z' to lowercase.
This function returns the lowercase equivalent of x. If a character cannot be converted, or is already lowercase, this function returns x.
Parameters
x character value to check.
Returns
lowercase version of x, or x if no conversion available.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'A') && ((x) <= 'Z') ? ('a' + ((x) - 'A')) : (x); }
Referenced by PrefixMatch(), SDL_strlwr(), and SDL_vsscanf().
SDL_toupper()
int SDL_toupper (int x)
Convert low-ASCII English letters to uppercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'a' through 'z' to uppercase.
This function returns the uppercase equivalent of x. If a character cannot be converted, or is already uppercase, this function returns x.
Parameters
x character value to check.
Returns
capitalized version of x, or x if no conversion available.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'a') && ((x) <= 'z') ? ('A' + ((x) - 'a')) : (x); }
Referenced by SDL_strupr().
SDL_trunc()
double SDL_trunc (double x)
Truncate x to an integer.
Rounds x to the next closest integer to 0. This is equivalent to removing the fractional part of x, leaving only the integer part.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_truncf for single-precision floats.
Parameters
x floating point value.
Returns
x truncated to an integer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_truncf
SDL_fmod
SDL_ceil
SDL_floor
SDL_round
SDL_lround
{
#ifdef HAVE_TRUNC
    return trunc(x);
#else
    if (x >= 0.0f) {
        return SDL_floor(x);
    } else {
        return SDL_ceil(x);
    }
#endif
}
References SDL_ceil(), and SDL_floor().
Referenced by SDL_truncf().
SDL_truncf()
float SDL_truncf (float x)
Truncate x to an integer.
Rounds x to the next closest integer to 0. This is equivalent to removing the fractional part of x, leaving only the integer part.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_trunc for double-precision floats.
Parameters
x floating point value.
Returns
x truncated to an integer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_trunc
SDL_fmodf
SDL_ceilf
SDL_floorf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_TRUNCF
    return truncf(x);
#else
    return (float)SDL_trunc((double)x);
#endif
}
References SDL_trunc().
Referenced by SDL_PrivateSendMouseMotion().