SDL3: SDL-main/src/thread/generic/SDL_syscond.c File Reference
SDL_syscond.c File Reference
#include "SDL_internal.h"
#include "../generic/SDL_syscond_c.h"
Data Structures
struct SDL_cond_generic
Macros
#define SDL_BroadcastCondition_generic SDL_BroadcastCondition
#define SDL_CreateCondition_generic SDL_CreateCondition
#define SDL_DestroyCondition_generic SDL_DestroyCondition
#define SDL_SignalCondition_generic SDL_SignalCondition
Typedefs
typedef struct SDL_cond_generic SDL_cond_generic
Functions
void SDL_BroadcastCondition (SDL_Condition *_cond)
SDL_Condition * SDL_CreateCondition (void)
void SDL_DestroyCondition (SDL_Condition *_cond)
void SDL_SignalCondition (SDL_Condition *_cond)
bool SDL_WaitConditionTimeoutNS (SDL_Condition *cond, SDL_Mutex *mutex, Sint64 timeoutNS)
bool SDL_WaitConditionTimeoutNS_generic (SDL_Condition *_cond, SDL_Mutex *mutex, Sint64 timeoutNS)
Macro Definition Documentation
SDL_BroadcastCondition_generic
#define SDL_BroadcastCondition_generic SDL_BroadcastCondition
SDL_CreateCondition_generic
#define SDL_CreateCondition_generic SDL_CreateCondition
SDL_DestroyCondition_generic
#define SDL_DestroyCondition_generic SDL_DestroyCondition
Referenced by SDL_CreateCondition().
SDL_SignalCondition_generic
#define SDL_SignalCondition_generic SDL_SignalCondition
Typedef Documentation
SDL_cond_generic
typedef struct SDL_cond_generic SDL_cond_generic
Function Documentation
SDL_BroadcastCondition()
void SDL_BroadcastCondition (SDL_Condition * cond)
Restart all threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    SDL_cond_generic *cond = (SDL_cond_generic *)_cond;
    if (!cond) {
        return;
    }
#ifndef SDL_THREADS_DISABLED
    /* If there are waiting threads not already signalled, then
       signal the condition and wait for the thread to respond.
     */
    SDL_WaitSemaphore(cond->signal_sem);
    if (cond->num_waiting > cond->num_signals) {
        const int num_waiting = (cond->num_waiting - cond->num_signals);
        cond->num_signals = cond->num_waiting;
        for (int i = 0; i < num_waiting; i++) {
            SDL_SignalSemaphore(cond->sem);
        }
        /* Now all released threads are blocked here, waiting for us.
           Collect them all (and win fabulous prizes!) :-)
         */
        SDL_SignalSemaphore(cond->signal_sem);
        for (int i = 0; i < num_waiting; i++) {
            SDL_WaitSemaphore(cond->handshake_sem);
        }
    } else {
        SDL_SignalSemaphore(cond->signal_sem);
    }
#endif
}
SDL_CreateCondition()
SDL_Condition * SDL_CreateCondition (void)
Create a condition variable.
Returns
a new condition variable or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
SDL_DestroyCondition
{
    SDL_cond_generic *cond = (SDL_cond_generic *)SDL_calloc(1, sizeof(*cond));
#ifndef SDL_THREADS_DISABLED
    if (cond) {
        cond->sem = SDL_CreateSemaphore(0);
        cond->handshake_sem = SDL_CreateSemaphore(0);
        cond->signal_sem = SDL_CreateSemaphore(1);
        if (!cond->sem || !cond->handshake_sem || !cond->signal_sem) {
            SDL_DestroyCondition_generic((SDL_Condition *)cond);
            cond = NULL;
        }
    }
#endif
    return (SDL_Condition *)cond;
}
SDL_DestroyCondition()
void SDL_DestroyCondition (SDL_Condition * cond)
Destroy a condition variable.
Parameters
cond the condition variable to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateCondition
{
    SDL_cond_generic *cond = (SDL_cond_generic *)_cond;
    if (cond) {
        if (cond->sem) {
            SDL_DestroySemaphore(cond->sem);
        }
        if (cond->handshake_sem) {
            SDL_DestroySemaphore(cond->handshake_sem);
        }
        if (cond->signal_sem) {
            SDL_DestroySemaphore(cond->signal_sem);
        }
        SDL_free(cond);
    }
}
SDL_SignalCondition()
void SDL_SignalCondition (SDL_Condition * cond)
Restart one of the threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    SDL_cond_generic *cond = (SDL_cond_generic *)_cond;
    if (!cond) {
        return;
    }
#ifndef SDL_THREADS_DISABLED
    /* If there are waiting threads not already signalled, then
       signal the condition and wait for the thread to respond.
     */
    SDL_WaitSemaphore(cond->signal_sem);
    if (cond->num_waiting > cond->num_signals) {
        cond->num_signals++;
        SDL_SignalSemaphore(cond->sem);
        SDL_SignalSemaphore(cond->signal_sem);
        SDL_WaitSemaphore(cond->handshake_sem);
    } else {
        SDL_SignalSemaphore(cond->signal_sem);
    }
#endif
}
SDL_WaitConditionTimeoutNS()
bool SDL_WaitConditionTimeoutNS (SDL_Condition * cond, SDL_Mutex * mutex, Sint64 timeoutNS)
{
    return SDL_WaitConditionTimeoutNS_generic(cond, mutex, timeoutNS);
}
SDL_WaitConditionTimeoutNS_generic()
bool SDL_WaitConditionTimeoutNS_generic (SDL_Condition * _cond, SDL_Mutex * mutex, Sint64 timeoutNS)
{
    SDL_cond_generic *cond = (SDL_cond_generic *)_cond;
    bool result = true;
    if (!cond || !mutex) {
        return true;
    }
#ifndef SDL_THREADS_DISABLED
    /* Obtain the protection mutex, and increment the number of waiters.
       This allows the signal mechanism to only perform a signal if there
       are waiting threads.
     */
    SDL_WaitSemaphore(cond->signal_sem);
    cond->num_waiting++;
    SDL_SignalSemaphore(cond->signal_sem);
    // Unlock the mutex, as is required by condition variable semantics
    SDL_UnlockMutex(mutex);
    // Wait for a signal
    result = SDL_WaitSemaphoreTimeoutNS(cond->sem, timeoutNS);
    /* Let the signaler know we have completed the wait, otherwise
       the signaler can race ahead and get the condition semaphore
       if we are stopped between the mutex unlock and semaphore wait,
       giving a deadlock.  See the following URL for details:
       http://web.archive.org/web/20010914175514/http://www-classic.be.com/aboutbe/benewsletter/volume_III/Issue40.html#Workshop
     */
    SDL_WaitSemaphore(cond->signal_sem);
    if (cond->num_signals > 0) {
        SDL_SignalSemaphore(cond->handshake_sem);
        cond->num_signals--;
    }
    cond->num_waiting--;
    SDL_SignalSemaphore(cond->signal_sem);
    // Lock the mutex, as is required by condition variable semantics
    SDL_LockMutex(mutex);
#endif
    return result;
}
References SDL_cond_generic::handshake_sem, SDL_cond_generic::num_signals, SDL_cond_generic::num_waiting, SDL_LockMutex(), SDL_SignalSemaphore(), SDL_UnlockMutex(), SDL_WaitSemaphore(), SDL_WaitSemaphoreTimeoutNS(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by SDL_WaitConditionTimeoutNS().