SDL3: SDL-main/src/io/n3ds/SDL_iostreamromfs.h File Reference
SDL_iostreamromfs.h File Reference
#include "SDL_internal.h"
Functions
FILE * N3DS_FileOpen (const char *file, const char *mode)
Function Documentation
N3DS_FileOpen()
FILE * N3DS_FileOpen (const char * file, const char * mode)
{
    // romfs are read-only
    if (!IsReadMode(mode)) {
        return fopen(file, mode);
    }
    // If the path has an explicit prefix, we skip the guess work
    if (HasPrefix(file, "romfs:/") || HasPrefix(file, "sdmc:/")) {
        return fopen(file, mode);
    }
    return TryOpenFile(file, mode);
}
References HasPrefix(), IsReadMode(), and TryOpenFile().
Referenced by SDL_IOFromFile().