SDL3: SDL-main/src/io/SDL_asyncio.c File Reference
SDL_asyncio.c File Reference
#include "SDL_internal.h"
#include "SDL_sysasyncio.h"
#include "SDL_asyncio_c.h"
Functions
static const char * AsyncFileModeValid (const char *mode)
static bool GetAsyncIOTaskOutcome (SDL_AsyncIOTask *task, SDL_AsyncIOOutcome *outcome)
static bool RequestAsyncIO (bool reading, SDL_AsyncIO *asyncio, void *ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue *queue, void *userdata)
SDL_AsyncIO * SDL_AsyncIOFromFile (const char *file, const char *mode)
bool SDL_CloseAsyncIO (SDL_AsyncIO *asyncio, bool flush, SDL_AsyncIOQueue *queue, void *userdata)
SDL_AsyncIOQueue * SDL_CreateAsyncIOQueue (void)
void SDL_DestroyAsyncIOQueue (SDL_AsyncIOQueue *queue)
bool SDL_GetAsyncIOResult (SDL_AsyncIOQueue *queue, SDL_AsyncIOOutcome *outcome)
Sint64 SDL_GetAsyncIOSize (SDL_AsyncIO *asyncio)
bool SDL_LoadFileAsync (const char *file, SDL_AsyncIOQueue *queue, void *userdata)
void SDL_QuitAsyncIO (void)
bool SDL_ReadAsyncIO (SDL_AsyncIO *asyncio, void *ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue *queue, void *userdata)
void SDL_SignalAsyncIOQueue (SDL_AsyncIOQueue *queue)
bool SDL_WaitAsyncIOResult (SDL_AsyncIOQueue *queue, SDL_AsyncIOOutcome *outcome, Sint32 timeoutMS)
bool SDL_WriteAsyncIO (SDL_AsyncIO *asyncio, void *ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue *queue, void *userdata)
Function Documentation
AsyncFileModeValid()
const char * AsyncFileModeValid (const char * mode) static
{
    static const struct { const char *valid; const char *with_binary; } mode_map[] = {
        { "r", "rb" },
        { "w", "wb" },
        { "r+","r+b" },
        { "w+", "w+b" }
    };
    for (int i = 0; i < SDL_arraysize(mode_map); i++) {
        if (SDL_strcmp(mode, mode_map[i].valid) == 0) {
            return mode_map[i].with_binary;
        }
    }
    return NULL;
}
References NULL, SDL_arraysize, and SDL_strcmp().
Referenced by SDL_AsyncIOFromFile().
GetAsyncIOTaskOutcome()
bool GetAsyncIOTaskOutcome (SDL_AsyncIOTask * task, SDL_AsyncIOOutcome * outcome) static
{
    if (!task || !outcome) {
        return false;
    }
    SDL_AsyncIO *asyncio = task->asyncio;
    SDL_zerop(outcome);
    outcome->asyncio = asyncio->oneshot ? NULL : asyncio;
    outcome->result = task->result;
    outcome->type = task->type;
    outcome->buffer = task->buffer;
    outcome->offset = task->offset;
    outcome->bytes_requested = task->requested_size;
    outcome->bytes_transferred = task->result_size;
    outcome->userdata = task->app_userdata;
    // Take the completed task out of the SDL_AsyncIO that created it.
    SDL_LockMutex(asyncio->lock);
    LINKED_LIST_UNLINK(task, asyncio);
    // see if it's time to queue a pending close request (close requested and no other pending tasks)
    SDL_AsyncIOTask *closing = asyncio->closing;
    if (closing && (task != closing) && (LINKED_LIST_START(asyncio->tasks, asyncio) == NULL)) {
        LINKED_LIST_PREPEND(closing, asyncio->tasks, asyncio);
        SDL_AddAtomicInt(&closing->queue->tasks_inflight, 1);
        const bool async_close_task_was_queued = asyncio->iface.close(asyncio->userdata, closing);
        SDL_assert(async_close_task_was_queued);  // !!! FIXME: if this fails to queue the task, we're leaking resources!
        if (!async_close_task_was_queued) {
            SDL_AddAtomicInt(&closing->queue->tasks_inflight, -1);
        }
    }
    SDL_UnlockMutex(task->asyncio->lock);
    // was this the result of a closing task? Finally destroy the asyncio.
    bool retval = true;
    if (closing && (task == closing)) {
        if (asyncio->oneshot) {
            retval = false;  // don't send the close task results on to the app, just the read task for these.
        }
        asyncio->iface.destroy(asyncio->userdata);
        SDL_DestroyMutex(asyncio->lock);
        SDL_free(asyncio);
    }
    SDL_AddAtomicInt(&task->queue->tasks_inflight, -1);
    SDL_free(task);
    return retval;
}
References SDL_AsyncIOTask::app_userdata, SDL_AsyncIOOutcome::asyncio, SDL_AsyncIOTask::asyncio, SDL_AsyncIOOutcome::buffer, SDL_AsyncIOTask::buffer, SDL_AsyncIOOutcome::bytes_requested, SDL_AsyncIOOutcome::bytes_transferred, SDL_AsyncIOInterface::close, SDL_AsyncIO::closing, SDL_AsyncIOInterface::destroy, SDL_AsyncIO::iface, LINKED_LIST_PREPEND, LINKED_LIST_START, LINKED_LIST_UNLINK, SDL_AsyncIO::lock, NULL, SDL_AsyncIOOutcome::offset, SDL_AsyncIOTask::offset, SDL_AsyncIO::oneshot, SDL_AsyncIOTask::queue, SDL_AsyncIOTask::requested_size, SDL_AsyncIOOutcome::result, SDL_AsyncIOTask::result, SDL_AsyncIOTask::result_size, SDL_AddAtomicInt(), SDL_assert, SDL_DestroyMutex(), SDL_free(), SDL_LockMutex(), SDL_UnlockMutex(), SDL_zerop, SDL_AsyncIO::tasks, SDL_AsyncIOQueue::tasks_inflight, SDL_AsyncIOOutcome::type, SDL_AsyncIOTask::type, SDL_AsyncIO::userdata, and SDL_AsyncIOOutcome::userdata.
Referenced by SDL_DestroyAsyncIOQueue(), SDL_GetAsyncIOResult(), and SDL_WaitAsyncIOResult().
RequestAsyncIO()
bool RequestAsyncIO (bool reading, SDL_AsyncIO * asyncio, void * ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue * queue, void * userdata) static
{
    if (!asyncio) {
        return SDL_InvalidParamError("asyncio");
    } else if (!ptr) {
        return SDL_InvalidParamError("ptr");
    } else if (!queue) {
        return SDL_InvalidParamError("queue");
    }
    SDL_AsyncIOTask *task = (SDL_AsyncIOTask *) SDL_calloc(1, sizeof (*task));
    if (!task) {
        return false;
    }
    task->asyncio = asyncio;
    task->type = reading ? SDL_ASYNCIO_TASK_READ : SDL_ASYNCIO_TASK_WRITE;
    task->offset = offset;
    task->buffer = ptr;
    task->requested_size = size;
    task->app_userdata = userdata;
    task->queue = queue;
    SDL_LockMutex(asyncio->lock);
    if (asyncio->closing) {
        SDL_free(task);
        SDL_UnlockMutex(asyncio->lock);
        return SDL_SetError("SDL_AsyncIO is closing, can't start new tasks");
    }
    LINKED_LIST_PREPEND(task, asyncio->tasks, asyncio);
    SDL_AddAtomicInt(&queue->tasks_inflight, 1);
    SDL_UnlockMutex(asyncio->lock);
    const bool queued = reading ? asyncio->iface.read(asyncio->userdata, task) : asyncio->iface.write(asyncio->userdata, task);
    if (!queued) {
        SDL_AddAtomicInt(&queue->tasks_inflight, -1);
        SDL_LockMutex(asyncio->lock);
        LINKED_LIST_UNLINK(task, asyncio);
        SDL_UnlockMutex(asyncio->lock);
        SDL_free(task);
        task = NULL;
    }
    return (task != NULL);
}
References SDL_AsyncIOTask::app_userdata, SDL_AsyncIOTask::asyncio, SDL_AsyncIOTask::buffer, SDL_AsyncIO::closing, SDL_AsyncIO::iface, LINKED_LIST_PREPEND, LINKED_LIST_UNLINK, SDL_AsyncIO::lock, NULL, SDL_AsyncIOTask::offset, SDL_AsyncIOTask::queue, SDL_AsyncIOInterface::read, SDL_AsyncIOTask::requested_size, SDL_AddAtomicInt(), SDL_ASYNCIO_TASK_READ, SDL_ASYNCIO_TASK_WRITE, SDL_calloc(), SDL_free(), SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), SDL_UnlockMutex(), SDL_AsyncIO::tasks, SDL_AsyncIOQueue::tasks_inflight, SDL_AsyncIOTask::type, SDL_AsyncIO::userdata, and SDL_AsyncIOInterface::write.
Referenced by SDL_ReadAsyncIO(), and SDL_WriteAsyncIO().
SDL_AsyncIOFromFile()
SDL_AsyncIO * SDL_AsyncIOFromFile (const char * file, const char * mode)
Use this function to create a new SDL_AsyncIO object for reading from and/or writing to a named file.
The mode string understands the following values:
"r": Open a file for reading only. It must exist.
"w": Open a file for writing only. It will create missing files or truncate existing ones.
"r+": Open a file for update both reading and writing. The file must exist.
"w+": Create an empty file for both reading and writing. If a file with the same name already exists its content is erased and the file is treated as a new empty file.
There is no "b" mode, as there is only "binary" style I/O, and no "a" mode for appending, since you specify the position when starting a task.
This function supports Unicode filenames, but they must be encoded in UTF-8 format, regardless of the underlying operating system.
This call is not asynchronous; it will open the file before returning, under the assumption that doing so is generally a fast operation. Future reads and writes to the opened file will be async, however.
Parameters
file a UTF-8 string representing the filename to open.
mode an ASCII string representing the mode to be used for opening the file.
Returns
a pointer to the SDL_AsyncIO structure that is created or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseAsyncIO
SDL_ReadAsyncIO
SDL_WriteAsyncIO
{
    if (!file) {
        SDL_InvalidParamError("file");
        return NULL;
    } else if (!mode) {
        SDL_InvalidParamError("mode");
        return NULL;
    }
    const char *binary_mode = AsyncFileModeValid(mode);
    if (!binary_mode) {
        SDL_SetError("Unsupported file mode");
        return NULL;
    }
    SDL_AsyncIO *asyncio = (SDL_AsyncIO *)SDL_calloc(1, sizeof(*asyncio));
    if (!asyncio) {
        return NULL;
    }
    asyncio->lock = SDL_CreateMutex();
    if (!asyncio->lock) {
        SDL_free(asyncio);
        return NULL;
    }
    if (!SDL_SYS_AsyncIOFromFile(file, binary_mode, asyncio)) {
        SDL_DestroyMutex(asyncio->lock);
        SDL_free(asyncio);
        return NULL;
    }
    return asyncio;
}
References AsyncFileModeValid(), SDL_AsyncIO::lock, NULL, SDL_calloc(), SDL_CreateMutex(), SDL_DestroyMutex(), SDL_free(), SDL_InvalidParamError, SDL_SetError(), and SDL_SYS_AsyncIOFromFile().
Referenced by SDL_LoadFileAsync().
SDL_CloseAsyncIO()
bool SDL_CloseAsyncIO (SDL_AsyncIO * asyncio, bool flush, SDL_AsyncIOQueue * queue, void * userdata)
Close and free any allocated resources for an async I/O object.
Closing a file is also an asynchronous task! If a write failure were to happen during the closing process, for example, the task results will report it as usual.
Closing a file that has been written to does not guarantee the data has made it to physical media; it may remain in the operating system's file cache, for later writing to disk. This means that a successfully-closed file can be lost if the system crashes or loses power in this small window. To prevent this, call this function with the flush parameter set to true. This will make the operation take longer, and perhaps increase system load in general, but a successful result guarantees that the data has made it to physical storage. Don't use this for temporary files, caches, and unimportant data, and definitely use it for crucial irreplaceable files, like game saves.
This function guarantees that the close will happen after any other pending tasks to asyncio, so it's safe to open a file, start several operations, close the file immediately, then check for all results later. This function will not block until the tasks have completed.
Once this function returns true, asyncio is no longer valid, regardless of any future outcomes. Any completed tasks might still contain this pointer in their SDL_AsyncIOOutcome data, in case the app was using this value to track information, but it should not be used again.
If this function returns false, the close wasn't started at all, and it's safe to attempt to close again later.
An SDL_AsyncIOQueue must be specified. The newly-created task will be added to it when it completes its work.
Parameters
asyncio a pointer to an SDL_AsyncIO structure to close.
flush true if data should sync to disk before the task completes.
queue a queue to add the new SDL_AsyncIO to.
userdata an app-defined pointer that will be provided with the task results.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but two threads should not attempt to close the same object.
Since
This function is available since SDL 3.2.0.
{
    if (!asyncio) {
        return SDL_InvalidParamError("asyncio");
    } else if (!queue) {
        return SDL_InvalidParamError("queue");
    }
    SDL_LockMutex(asyncio->lock);
    if (asyncio->closing) {
        SDL_UnlockMutex(asyncio->lock);
        return SDL_SetError("Already closing");
    }
    SDL_AsyncIOTask *task = (SDL_AsyncIOTask *) SDL_calloc(1, sizeof (*task));
    if (task) {
        task->asyncio = asyncio;
        task->type = SDL_ASYNCIO_TASK_CLOSE;
        task->app_userdata = userdata;
        task->queue = queue;
        task->flush = flush;
        asyncio->closing = task;
        if (LINKED_LIST_START(asyncio->tasks, asyncio) == NULL) { // no tasks? Queue the close task now.
            LINKED_LIST_PREPEND(task, asyncio->tasks, asyncio);
            SDL_AddAtomicInt(&queue->tasks_inflight, 1);
            if (!asyncio->iface.close(asyncio->userdata, task)) {
                // uhoh, maybe they can try again later...?
                SDL_AddAtomicInt(&queue->tasks_inflight, -1);
                LINKED_LIST_UNLINK(task, asyncio);
                SDL_free(task);
                task = asyncio->closing = NULL;
            }
        }
    }
    SDL_UnlockMutex(asyncio->lock);
    return (task != NULL);
}
References SDL_AsyncIOTask::app_userdata, SDL_AsyncIOTask::asyncio, SDL_AsyncIOInterface::close, SDL_AsyncIO::closing, SDL_AsyncIOTask::flush, SDL_AsyncIO::iface, LINKED_LIST_PREPEND, LINKED_LIST_START, LINKED_LIST_UNLINK, SDL_AsyncIO::lock, NULL, SDL_AsyncIOTask::queue, SDL_AddAtomicInt(), SDL_ASYNCIO_TASK_CLOSE, SDL_calloc(), SDL_free(), SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), SDL_UnlockMutex(), SDL_AsyncIO::tasks, SDL_AsyncIOQueue::tasks_inflight, SDL_AsyncIOTask::type, and SDL_AsyncIO::userdata.
Referenced by SDL_LoadFileAsync().
SDL_CreateAsyncIOQueue()
SDL_AsyncIOQueue * SDL_CreateAsyncIOQueue (void)
Create a task queue for tracking multiple I/O operations.
Async I/O operations are assigned to a queue when started. The queue can be checked for completed tasks thereafter.
Returns
a new task queue object or NULL if there was an error; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyAsyncIOQueue
SDL_GetAsyncIOResult
SDL_WaitAsyncIOResult
{
    SDL_AsyncIOQueue *queue = SDL_calloc(1, sizeof (*queue));
    if (queue) {
        SDL_SetAtomicInt(&queue->tasks_inflight, 0);
        if (!SDL_SYS_CreateAsyncIOQueue(queue)) {
            SDL_free(queue);
            return NULL;
        }
    }
    return queue;
}
References NULL, SDL_calloc(), SDL_free(), SDL_SetAtomicInt(), SDL_SYS_CreateAsyncIOQueue(), and SDL_AsyncIOQueue::tasks_inflight.
SDL_DestroyAsyncIOQueue()
void SDL_DestroyAsyncIOQueue (SDL_AsyncIOQueue * queue)
Destroy a previously-created async I/O task queue.
If there are still tasks pending for this queue, this call will block until those tasks are finished. All those tasks will be deallocated. Their results will be lost to the app.
Any pending reads from SDL_LoadFileAsync() that are still in this queue will have their buffers deallocated by this function, to prevent a memory leak.
Once this function is called, the queue is no longer valid and should not be used, including by other threads that might access it while destruction is blocking on pending tasks.
Do not destroy a queue that still has threads waiting on it through SDL_WaitAsyncIOResult(). You can call SDL_SignalAsyncIOQueue() first to unblock those threads, and take measures (such as SDL_WaitThread()) to make sure they have finished their wait and won't wait on the queue again.
Parameters
queue the task queue to destroy.
Thread Safety
It is safe to call this function from any thread, so long as no other thread is waiting on the queue with SDL_WaitAsyncIOResult.
Since
This function is available since SDL 3.2.0.
{
    if (queue) {
        // block until any pending tasks complete.
        while (SDL_GetAtomicInt(&queue->tasks_inflight) > 0) {
            SDL_AsyncIOTask *task = queue->iface.wait_results(queue->userdata, -1);
            if (task) {
                if (task->asyncio->oneshot) {
                    SDL_free(task->buffer);  // throw away the buffer from SDL_LoadFileAsync that will never be consumed/freed by app.
                    task->buffer = NULL;
                }
                SDL_AsyncIOOutcome outcome;
                GetAsyncIOTaskOutcome(task, &outcome);  // this frees the task, and does other upkeep.
            }
        }
        queue->iface.destroy(queue->userdata);
        SDL_free(queue);
    }
}
References SDL_AsyncIOTask::asyncio, SDL_AsyncIOTask::buffer, SDL_AsyncIOQueueInterface::destroy, GetAsyncIOTaskOutcome(), SDL_AsyncIOQueue::iface, NULL, SDL_AsyncIO::oneshot, SDL_free(), SDL_GetAtomicInt(), SDL_AsyncIOQueue::tasks_inflight, SDL_AsyncIOQueue::userdata, and SDL_AsyncIOQueueInterface::wait_results.
SDL_GetAsyncIOResult()
bool SDL_GetAsyncIOResult (SDL_AsyncIOQueue * queue, SDL_AsyncIOOutcome * outcome)
Query an async I/O task queue for completed tasks.
If a task assigned to this queue has finished, this will return true and fill in outcome with the details of the task. If no task in the queue has finished, this function will return false. This function does not block.
If a task has completed, this function will free its resources and the task pointer will no longer be valid. The task will be removed from the queue.
It is safe for multiple threads to call this function on the same queue at once; a completed task will only go to one of the threads.
Parameters
queue the async I/O task queue to query.
outcome details of a finished task will be written here. May not be NULL.
Returns
true if a task has completed, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_WaitAsyncIOResult
{
    if (!queue || !outcome) {
        return false;
    }
    return GetAsyncIOTaskOutcome(queue->iface.get_results(queue->userdata), outcome);
}
References SDL_AsyncIOQueueInterface::get_results, GetAsyncIOTaskOutcome(), SDL_AsyncIOQueue::iface, and SDL_AsyncIOQueue::userdata.
SDL_GetAsyncIOSize()
Sint64 SDL_GetAsyncIOSize (SDL_AsyncIO * asyncio)
Use this function to get the size of the data stream in an SDL_AsyncIO.
This call is not asynchronous; it assumes that obtaining this info is a non-blocking operation in most reasonable cases.
Parameters
asyncio the SDL_AsyncIO to get the size of the data stream from.
Returns
the size of the data stream in the SDL_IOStream on success or a negative error code on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!asyncio) {
        SDL_InvalidParamError("asyncio");
        return -1;
    }
    return asyncio->iface.size(asyncio->userdata);
}
References SDL_AsyncIO::iface, SDL_InvalidParamError, SDL_AsyncIOInterface::size, and SDL_AsyncIO::userdata.
Referenced by SDL_LoadFileAsync().
SDL_LoadFileAsync()
bool SDL_LoadFileAsync (const char * file, SDL_AsyncIOQueue * queue, void * userdata)
Load all the data from a file path, asynchronously.
This function returns as quickly as possible; it does not wait for the read to complete. On a successful return, this work will continue in the background. If the work begins, even failure is asynchronous: a failing return value from this function only means the work couldn't start at all.
The data is allocated with a zero byte at the end (null terminated) for convenience. This extra byte is not included in SDL_AsyncIOOutcome's bytes_transferred value.
This function will allocate the buffer to contain the file. It must be deallocated by calling SDL_free() on SDL_AsyncIOOutcome's buffer field after completion.
An SDL_AsyncIOQueue must be specified. The newly-created task will be added to it when it completes its work.
Parameters
file the path to read all available data from.
queue a queue to add the new SDL_AsyncIO to.
userdata an app-defined pointer that will be provided with the task results.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_LoadFile_IO
{
    if (!file) {
        return SDL_InvalidParamError("file");
    } else if (!queue) {
        return SDL_InvalidParamError("queue");
    }
    bool retval = false;
    SDL_AsyncIO *asyncio = SDL_AsyncIOFromFile(file, "r");
    if (asyncio) {
        asyncio->oneshot = true;
        Uint8 *ptr = NULL;
        const Sint64 flen = SDL_GetAsyncIOSize(asyncio);
        if (flen >= 0) {
            // !!! FIXME: check if flen > address space, since it'll truncate and we'll just end up with an incomplete buffer or a crash.
            ptr = (Uint8 *) SDL_malloc((size_t) (flen + 1));  // over-allocate by one so we can add a null-terminator.
            if (ptr) {
                ptr[flen] = '\0';
                retval = SDL_ReadAsyncIO(asyncio, ptr, 0, (Uint64) flen, queue, userdata);
                if (!retval) {
                    SDL_free(ptr);
                }
            }
        }
        SDL_CloseAsyncIO(asyncio, false, queue, userdata);  // if this fails, we'll have a resource leak, but this would already be a dramatic system failure.
    }
    return retval;
}
References NULL, SDL_AsyncIO::oneshot, SDL_AsyncIOFromFile(), SDL_CloseAsyncIO(), SDL_free(), SDL_GetAsyncIOSize(), SDL_InvalidParamError, SDL_malloc(), and SDL_ReadAsyncIO().
SDL_QuitAsyncIO()
void SDL_QuitAsyncIO (void)
{
    SDL_SYS_QuitAsyncIO();
}
References SDL_SYS_QuitAsyncIO().
Referenced by SDL_Quit().
SDL_ReadAsyncIO()
bool SDL_ReadAsyncIO (SDL_AsyncIO * asyncio, void * ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue * queue, void * userdata)
Start an async read.
This function reads up to size bytes from offset position in the data source to the area pointed at by ptr. This function may read less bytes than requested.
This function returns as quickly as possible; it does not wait for the read to complete. On a successful return, this work will continue in the background. If the work begins, even failure is asynchronous: a failing return value from this function only means the work couldn't start at all.
ptr must remain available until the work is done, and may be accessed by the system at any time until then. Do not allocate it on the stack, as this might take longer than the life of the calling function to complete!
An SDL_AsyncIOQueue must be specified. The newly-created task will be added to it when it completes its work.
Parameters
asyncio a pointer to an SDL_AsyncIO structure.
ptr a pointer to a buffer to read data into.
offset the position to start reading in the data source.
size the number of bytes to read from the data source.
queue a queue to add the new SDL_AsyncIO to.
userdata an app-defined pointer that will be provided with the task results.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_WriteAsyncIO
SDL_CreateAsyncIOQueue
{
    return RequestAsyncIO(true, asyncio, ptr, offset, size, queue, userdata);
}
References RequestAsyncIO().
Referenced by SDL_LoadFileAsync().
SDL_SignalAsyncIOQueue()
void SDL_SignalAsyncIOQueue (SDL_AsyncIOQueue * queue)
Wake up any threads that are blocking in SDL_WaitAsyncIOResult().
This will unblock any threads that are sleeping in a call to SDL_WaitAsyncIOResult for the specified queue, and cause them to return from that function.
This can be useful when destroying a queue to make sure nothing is touching it indefinitely. In this case, once this call completes, the caller should take measures to make sure any previously-blocked threads have returned from their wait and will not touch the queue again (perhaps by setting a flag to tell the threads to terminate and then using SDL_WaitThread() to make sure they've done so).
Parameters
queue the async I/O task queue to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_WaitAsyncIOResult
{
    if (queue) {
        queue->iface.signal(queue->userdata);
    }
}
References SDL_AsyncIOQueue::iface, SDL_AsyncIOQueueInterface::signal, and SDL_AsyncIOQueue::userdata.
SDL_WaitAsyncIOResult()
bool SDL_WaitAsyncIOResult (SDL_AsyncIOQueue * queue, SDL_AsyncIOOutcome * outcome, Sint32 timeoutMS)
Block until an async I/O task queue has a completed task.
This function puts the calling thread to sleep until there a task assigned to the queue that has finished.
If a task assigned to the queue has finished, this will return true and fill in outcome with the details of the task. If no task in the queue has finished, this function will return false.
If a task has completed, this function will free its resources and the task pointer will no longer be valid. The task will be removed from the queue.
It is safe for multiple threads to call this function on the same queue at once; a completed task will only go to one of the threads.
Note that by the nature of various platforms, more than one waiting thread may wake to handle a single task, but only one will obtain it, so timeoutMS is a maximum wait time, and this function may return false sooner.
This function may return false if there was a system error, the OS inadvertently awoke multiple threads, or if SDL_SignalAsyncIOQueue() was called to wake up all waiting threads without a finished task.
A timeout can be used to specify a maximum wait time, but rather than polling, it is possible to have a timeout of -1 to wait forever, and use SDL_SignalAsyncIOQueue() to wake up the waiting threads later.
Parameters
queue the async I/O task queue to wait on.
outcome details of a finished task will be written here. May not be NULL.
timeoutMS the maximum time to wait, in milliseconds, or -1 to wait indefinitely.
Returns
true if task has completed, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalAsyncIOQueue
{
    if (!queue || !outcome) {
        return false;
    }
    return GetAsyncIOTaskOutcome(queue->iface.wait_results(queue->userdata, timeoutMS), outcome);
}
References GetAsyncIOTaskOutcome(), SDL_AsyncIOQueue::iface, SDL_AsyncIOQueue::userdata, and SDL_AsyncIOQueueInterface::wait_results.
SDL_WriteAsyncIO()
bool SDL_WriteAsyncIO (SDL_AsyncIO * asyncio, void * ptr, Uint64 offset, Uint64 size, SDL_AsyncIOQueue * queue, void * userdata)
Start an async write.
This function writes size bytes from offset position in the data source to the area pointed at by ptr.
This function returns as quickly as possible; it does not wait for the write to complete. On a successful return, this work will continue in the background. If the work begins, even failure is asynchronous: a failing return value from this function only means the work couldn't start at all.
ptr must remain available until the work is done, and may be accessed by the system at any time until then. Do not allocate it on the stack, as this might take longer than the life of the calling function to complete!
An SDL_AsyncIOQueue must be specified. The newly-created task will be added to it when it completes its work.
Parameters
asyncio a pointer to an SDL_AsyncIO structure.
ptr a pointer to a buffer to write data from.
offset the position to start writing to the data source.
size the number of bytes to write to the data source.
queue a queue to add the new SDL_AsyncIO to.
userdata an app-defined pointer that will be provided with the task results.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ReadAsyncIO
SDL_CreateAsyncIOQueue
{
    return RequestAsyncIO(false, asyncio, ptr, offset, size, queue, userdata);
}
References RequestAsyncIO().