SDL3: SDL-main/src/io/generic/SDL_asyncio_generic.c File Reference
SDL_asyncio_generic.c File Reference
#include "SDL_internal.h"
#include "../SDL_sysasyncio.h"
Data Structures
struct GenericAsyncIOData
struct GenericAsyncIOQueueData
Macros
#define SDL_ASYNCIO_USE_THREADPOOL 1
Typedefs
typedef struct GenericAsyncIOData GenericAsyncIOData
typedef struct GenericAsyncIOQueueData GenericAsyncIOQueueData
Functions
static void AsyncIOTaskComplete (SDL_AsyncIOTask *task)
static int SDLCALL AsyncIOThreadpoolWorker (void *data)
static void generic_asyncio_destroy (void *userdata)
static bool generic_asyncio_io (void *userdata, SDL_AsyncIOTask *task)
static Sint64 generic_asyncio_size (void *userdata)
static void generic_asyncioqueue_cancel_task (void *userdata, SDL_AsyncIOTask *task)
static void generic_asyncioqueue_destroy (void *userdata)
static SDL_AsyncIOTask * generic_asyncioqueue_get_results (void *userdata)
static bool generic_asyncioqueue_queue_task (void *userdata, SDL_AsyncIOTask *task)
static void generic_asyncioqueue_signal (void *userdata)
static SDL_AsyncIOTask * generic_asyncioqueue_wait_results (void *userdata, Sint32 timeoutMS)
static bool MaybeSpinNewWorkerThread (void)
static bool PrepareThreadpool (void)
static void QueueAsyncIOTask (SDL_AsyncIOTask *task)
bool SDL_SYS_AsyncIOFromFile (const char *file, const char *mode, SDL_AsyncIO *asyncio)
bool SDL_SYS_AsyncIOFromFile_Generic (const char *file, const char *mode, SDL_AsyncIO *asyncio)
bool SDL_SYS_CreateAsyncIOQueue (SDL_AsyncIOQueue *queue)
bool SDL_SYS_CreateAsyncIOQueue_Generic (SDL_AsyncIOQueue *queue)
void SDL_SYS_QuitAsyncIO (void)
void SDL_SYS_QuitAsyncIO_Generic (void)
static void ShutdownThreadpool (void)
static void SynchronousIO (SDL_AsyncIOTask *task)
Variables
static int idle_threadpool_threads = 0
static int max_threadpool_threads = 0
static int running_threadpool_threads = 0
static bool stop_threadpool = false
static SDL_Condition * threadpool_condition = NULL
static SDL_InitState threadpool_init
static SDL_Mutex * threadpool_lock = NULL
static SDL_AsyncIOTask threadpool_tasks
static int threadpool_threads_spun = 0
Macro Definition Documentation
SDL_ASYNCIO_USE_THREADPOOL
#define SDL_ASYNCIO_USE_THREADPOOL 1
Typedef Documentation
GenericAsyncIOData
typedef struct GenericAsyncIOData GenericAsyncIOData
GenericAsyncIOQueueData
typedef struct GenericAsyncIOQueueData GenericAsyncIOQueueData
Function Documentation
AsyncIOTaskComplete()
void AsyncIOTaskComplete (SDL_AsyncIOTask * task) static
{
    SDL_assert(task->queue);
    GenericAsyncIOQueueData *data = (GenericAsyncIOQueueData *) task->queue->userdata;
    SDL_LockMutex(data->lock);
    LINKED_LIST_PREPEND(task, data->completed_tasks, queue);
    SDL_SignalCondition(data->condition);  // wake a thread waiting on the queue.
    SDL_UnlockMutex(data->lock);
}
References LINKED_LIST_PREPEND, SDL_AsyncIOTask::queue, SDL_assert, SDL_LockMutex(), SDL_SignalCondition(), SDL_UnlockMutex(), and SDL_AsyncIOQueue::userdata.
Referenced by generic_asyncioqueue_cancel_task(), QueueAsyncIOTask(), ShutdownThreadpool(), and SynchronousIO().
AsyncIOThreadpoolWorker()
int SDLCALL AsyncIOThreadpoolWorker (void * data) static
{
    SDL_LockMutex(threadpool_lock);
    while (!stop_threadpool) {
        SDL_AsyncIOTask *task = LINKED_LIST_START(threadpool_tasks, threadpool);
        if (!task) {
            // if we go 30 seconds without a new task, terminate unless we're the only thread left.
            idle_threadpool_threads++;
            const bool rc = SDL_WaitConditionTimeout(threadpool_condition, threadpool_lock, 30000);
            idle_threadpool_threads--;
            if (!rc) {
                // decide if we have too many idle threads, and if so, quit to let thread pool shrink when not busy.
                if (idle_threadpool_threads) {
                    break;
                }
            }
            continue;
        }
        LINKED_LIST_UNLINK(task, threadpool);
        SDL_UnlockMutex(threadpool_lock);
        // bookkeeping is done, so we drop the mutex and fire the work.
        SynchronousIO(task);
        SDL_LockMutex(threadpool_lock);  // take the lock again and see if there's another task (if not, we'll wait on the Condition).
    }
    running_threadpool_threads--;
    // this is kind of a hack, but this lets us reuse threadpool_condition to block on shutdown until all threads have exited.
    if (stop_threadpool) {
        SDL_BroadcastCondition(threadpool_condition);
    }
    SDL_UnlockMutex(threadpool_lock);
    return 0;
}
References idle_threadpool_threads, LINKED_LIST_START, LINKED_LIST_UNLINK, running_threadpool_threads, SDL_BroadcastCondition(), SDL_LockMutex(), SDL_UnlockMutex(), SDL_WaitConditionTimeout(), SDLCALL, stop_threadpool, SynchronousIO(), threadpool_condition, threadpool_lock, and threadpool_tasks.
Referenced by MaybeSpinNewWorkerThread().
generic_asyncio_destroy()
void generic_asyncio_destroy (void * userdata) static
{
    GenericAsyncIOData *data = (GenericAsyncIOData *) userdata;
    SDL_DestroyMutex(data->lock);
    SDL_free(data);
}
References SDL_DestroyMutex(), and SDL_free().
Referenced by SDL_SYS_AsyncIOFromFile_Generic().
generic_asyncio_io()
bool generic_asyncio_io (void * userdata, SDL_AsyncIOTask * task) static
{
    return task->queue->iface.queue_task(task->queue->userdata, task);
}
References SDL_AsyncIOQueue::iface, SDL_AsyncIOTask::queue, SDL_AsyncIOQueueInterface::queue_task, and SDL_AsyncIOQueue::userdata.
Referenced by SDL_SYS_AsyncIOFromFile_Generic().
generic_asyncio_size()
Sint64 generic_asyncio_size (void * userdata) static
{
    GenericAsyncIOData *data = (GenericAsyncIOData *) userdata;
    return SDL_GetIOSize(data->io);
}
References SDL_GetIOSize().
Referenced by SDL_SYS_AsyncIOFromFile_Generic().
generic_asyncioqueue_cancel_task()
void generic_asyncioqueue_cancel_task (void * userdata, SDL_AsyncIOTask * task) static
{
    #if !SDL_ASYNCIO_USE_THREADPOOL  // in theory, this was all synchronous and should never call this, but just in case.
    task->result = SDL_ASYNCIO_CANCELED;
    AsyncIOTaskComplete(task);
    #else
    // we can't stop i/o that's in-flight, but we _can_ just refuse to start it if the threadpool hadn't picked it up yet.
    SDL_LockMutex(threadpool_lock);
    if (LINKED_LIST_PREV(task, threadpool) != NULL) {  // still in the queue waiting to be run? Take it out.
        LINKED_LIST_UNLINK(task, threadpool);
        task->result = SDL_ASYNCIO_CANCELED;
        AsyncIOTaskComplete(task);
    }
    SDL_UnlockMutex(threadpool_lock);
    #endif
}
References AsyncIOTaskComplete(), LINKED_LIST_PREV, LINKED_LIST_UNLINK, NULL, SDL_AsyncIOTask::result, SDL_ASYNCIO_CANCELED, SDL_LockMutex(), SDL_UnlockMutex(), and threadpool_lock.
Referenced by SDL_SYS_CreateAsyncIOQueue_Generic().
generic_asyncioqueue_destroy()
void generic_asyncioqueue_destroy (void * userdata) static
{
    GenericAsyncIOQueueData *data = (GenericAsyncIOQueueData *) userdata;
    SDL_DestroyMutex(data->lock);
    SDL_DestroyCondition(data->condition);
    SDL_free(data);
}
References SDL_DestroyCondition(), SDL_DestroyMutex(), and SDL_free().
Referenced by SDL_SYS_CreateAsyncIOQueue_Generic().
generic_asyncioqueue_get_results()
SDL_AsyncIOTask * generic_asyncioqueue_get_results (void * userdata) static
{
    GenericAsyncIOQueueData *data = (GenericAsyncIOQueueData *) userdata;
    SDL_LockMutex(data->lock);
    SDL_AsyncIOTask *task = LINKED_LIST_START(data->completed_tasks, queue);
    if (task) {
        LINKED_LIST_UNLINK(task, queue);
    }
    SDL_UnlockMutex(data->lock);
    return task;
}
References LINKED_LIST_START, LINKED_LIST_UNLINK, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_SYS_CreateAsyncIOQueue_Generic().
generic_asyncioqueue_queue_task()
bool generic_asyncioqueue_queue_task (void * userdata, SDL_AsyncIOTask * task) static
{
    #if SDL_ASYNCIO_USE_THREADPOOL
    QueueAsyncIOTask(task);
    #else
    SynchronousIO(task);  // oh well. Get a better platform.
    #endif
    return true;
}
References QueueAsyncIOTask(), and SynchronousIO().
Referenced by SDL_SYS_CreateAsyncIOQueue_Generic().
generic_asyncioqueue_signal()
void generic_asyncioqueue_signal (void * userdata) static
{
    GenericAsyncIOQueueData *data = (GenericAsyncIOQueueData *) userdata;
    SDL_LockMutex(data->lock);
    SDL_BroadcastCondition(data->condition);
    SDL_UnlockMutex(data->lock);
}
References SDL_BroadcastCondition(), SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_SYS_CreateAsyncIOQueue_Generic().
generic_asyncioqueue_wait_results()
SDL_AsyncIOTask * generic_asyncioqueue_wait_results (void * userdata, Sint32 timeoutMS) static
{
    GenericAsyncIOQueueData *data = (GenericAsyncIOQueueData *) userdata;
    SDL_LockMutex(data->lock);
    SDL_AsyncIOTask *task = LINKED_LIST_START(data->completed_tasks, queue);
    if (!task) {
        SDL_WaitConditionTimeout(data->condition, data->lock, timeoutMS);
        task = LINKED_LIST_START(data->completed_tasks, queue);
    }
    if (task) {
        LINKED_LIST_UNLINK(task, queue);
    }
    SDL_UnlockMutex(data->lock);
    return task;
}
References LINKED_LIST_START, LINKED_LIST_UNLINK, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_WaitConditionTimeout().
Referenced by SDL_SYS_CreateAsyncIOQueue_Generic().
MaybeSpinNewWorkerThread()
bool MaybeSpinNewWorkerThread (void) static
{
    // if all existing threads are busy and the pool of threads isn't maxed out, make a new one.
    if ((idle_threadpool_threads == 0) && (running_threadpool_threads < max_threadpool_threads)) {
        char threadname[32];
        SDL_snprintf(threadname, sizeof (threadname), "SDLasyncio%d", threadpool_threads_spun);
        SDL_Thread *thread = SDL_CreateThread(AsyncIOThreadpoolWorker, threadname, NULL);
        if (thread == NULL) {
            return false;
        }
        SDL_DetachThread(thread);  // these terminate themselves when idle too long, so we never WaitThread.
        running_threadpool_threads++;
        threadpool_threads_spun++;
    }
    return true;
}
References AsyncIOThreadpoolWorker(), idle_threadpool_threads, max_threadpool_threads, NULL, running_threadpool_threads, SDL_CreateThread, SDL_DetachThread(), SDL_snprintf(), and threadpool_threads_spun.
Referenced by PrepareThreadpool(), and QueueAsyncIOTask().
PrepareThreadpool()
bool PrepareThreadpool (void) static
{
    bool okay = true;
    if (SDL_ShouldInit(&threadpool_init)) {
        max_threadpool_threads = (SDL_GetNumLogicalCPUCores() * 2) + 1;  // !!! FIXME: this should probably have a hint to override.
        max_threadpool_threads = SDL_clamp(max_threadpool_threads, 1, 8);  // 8 is probably more than enough.
        okay = (okay && ((threadpool_lock = SDL_CreateMutex()) != NULL));
        okay = (okay && ((threadpool_condition = SDL_CreateCondition()) != NULL));
        okay = (okay && MaybeSpinNewWorkerThread());  // make sure at least one thread is going, since we'll need it.
        if (!okay) {
            if (threadpool_condition) {
                SDL_DestroyCondition(threadpool_condition);
                threadpool_condition = NULL;
            }
            if (threadpool_lock) {
                SDL_DestroyMutex(threadpool_lock);
                threadpool_lock = NULL;
            }
        }
        SDL_SetInitialized(&threadpool_init, okay);
    }
    return okay;
}
References max_threadpool_threads, MaybeSpinNewWorkerThread(), NULL, SDL_clamp, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_GetNumLogicalCPUCores(), SDL_SetInitialized(), SDL_ShouldInit(), threadpool_condition, threadpool_init, and threadpool_lock.
Referenced by SDL_SYS_AsyncIOFromFile_Generic(), and SDL_SYS_CreateAsyncIOQueue_Generic().
QueueAsyncIOTask()
void QueueAsyncIOTask (SDL_AsyncIOTask * task) static
{
    SDL_assert(task != NULL);
    SDL_LockMutex(threadpool_lock);
    if (stop_threadpool) {  // just in case.
        task->result = SDL_ASYNCIO_CANCELED;
        AsyncIOTaskComplete(task);
    } else {
        LINKED_LIST_PREPEND(task, threadpool_tasks, threadpool);
        MaybeSpinNewWorkerThread();  // okay if this fails or the thread pool is maxed out. Something will get there eventually.
        // tell idle threads to get to work.
        // This is a broadcast because we want someone from the thread pool to wake up, but
        // also shutdown might also be blocking on this. One of the threads will grab
        // it, the others will go back to sleep.
        SDL_BroadcastCondition(threadpool_condition);
    }
    SDL_UnlockMutex(threadpool_lock);
}
References AsyncIOTaskComplete(), LINKED_LIST_PREPEND, MaybeSpinNewWorkerThread(), NULL, SDL_AsyncIOTask::result, SDL_assert, SDL_ASYNCIO_CANCELED, SDL_BroadcastCondition(), SDL_LockMutex(), SDL_UnlockMutex(), stop_threadpool, threadpool_condition, threadpool_lock, and threadpool_tasks.
Referenced by generic_asyncioqueue_queue_task().
SDL_SYS_AsyncIOFromFile()
bool SDL_SYS_AsyncIOFromFile (const char * file, const char * mode, SDL_AsyncIO * asyncio)
{
    return SDL_SYS_AsyncIOFromFile_Generic(file, mode, asyncio);
}
References SDL_SYS_AsyncIOFromFile_Generic().
Referenced by SDL_AsyncIOFromFile().
SDL_SYS_AsyncIOFromFile_Generic()
bool SDL_SYS_AsyncIOFromFile_Generic (const char * file, const char * mode, SDL_AsyncIO * asyncio)
{
    #if SDL_ASYNCIO_USE_THREADPOOL
    if (!PrepareThreadpool()) {
        return false;
    }
    #endif
    GenericAsyncIOData *data = (GenericAsyncIOData *) SDL_calloc(1, sizeof (*data));
    if (!data) {
        return false;
    }
    data->lock = SDL_CreateMutex();
    if (!data->lock) {
        SDL_free(data);
        return false;
    }
    data->io = SDL_IOFromFile(file, mode);
    if (!data->io) {
        SDL_DestroyMutex(data->lock);
        SDL_free(data);
        return false;
    }
    static const SDL_AsyncIOInterface SDL_AsyncIOFile_Generic = {
        generic_asyncio_size,
        generic_asyncio_io,
        generic_asyncio_io,
        generic_asyncio_io,
        generic_asyncio_destroy
    };
    SDL_copyp(&asyncio->iface, &SDL_AsyncIOFile_Generic);
    asyncio->userdata = data;
    return true;
}
References generic_asyncio_destroy(), generic_asyncio_io(), generic_asyncio_size(), SDL_AsyncIO::iface, PrepareThreadpool(), SDL_calloc(), SDL_copyp, SDL_CreateMutex(), SDL_DestroyMutex(), SDL_free(), SDL_IOFromFile(), and SDL_AsyncIO::userdata.
Referenced by SDL_SYS_AsyncIOFromFile().
SDL_SYS_CreateAsyncIOQueue()
bool SDL_SYS_CreateAsyncIOQueue (SDL_AsyncIOQueue * queue)
{
    return SDL_SYS_CreateAsyncIOQueue_Generic(queue);
}
References SDL_SYS_CreateAsyncIOQueue_Generic().
Referenced by SDL_CreateAsyncIOQueue().
SDL_SYS_CreateAsyncIOQueue_Generic()
bool SDL_SYS_CreateAsyncIOQueue_Generic (SDL_AsyncIOQueue * queue)
{
    #if SDL_ASYNCIO_USE_THREADPOOL
    if (!PrepareThreadpool()) {
        return false;
    }
    #endif
    GenericAsyncIOQueueData *data = (GenericAsyncIOQueueData *) SDL_calloc(1, sizeof (*data));
    if (!data) {
        return false;
    }
    data->lock = SDL_CreateMutex();
    if (!data->lock) {
        SDL_free(data);
        return false;
    }
    data->condition = SDL_CreateCondition();
    if (!data->condition) {
        SDL_DestroyMutex(data->lock);
        SDL_free(data);
        return false;
    }
    static const SDL_AsyncIOQueueInterface SDL_AsyncIOQueue_Generic = {
        generic_asyncioqueue_queue_task,
        generic_asyncioqueue_cancel_task,
        generic_asyncioqueue_get_results,
        generic_asyncioqueue_wait_results,
        generic_asyncioqueue_signal,
        generic_asyncioqueue_destroy
    };
    SDL_copyp(&queue->iface, &SDL_AsyncIOQueue_Generic);
    queue->userdata = data;
    return true;
}
References generic_asyncioqueue_cancel_task(), generic_asyncioqueue_destroy(), generic_asyncioqueue_get_results(), generic_asyncioqueue_queue_task(), generic_asyncioqueue_signal(), generic_asyncioqueue_wait_results(), SDL_AsyncIOQueue::iface, PrepareThreadpool(), SDL_calloc(), SDL_copyp, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroyMutex(), SDL_free(), and SDL_AsyncIOQueue::userdata.
Referenced by SDL_SYS_CreateAsyncIOQueue().
SDL_SYS_QuitAsyncIO()
void SDL_SYS_QuitAsyncIO (void)
{
    SDL_SYS_QuitAsyncIO_Generic();
}
References SDL_SYS_QuitAsyncIO_Generic().
Referenced by SDL_QuitAsyncIO().
SDL_SYS_QuitAsyncIO_Generic()
void SDL_SYS_QuitAsyncIO_Generic (void)
{
    #if SDL_ASYNCIO_USE_THREADPOOL
    ShutdownThreadpool();
    #endif
}
References ShutdownThreadpool().
Referenced by SDL_SYS_QuitAsyncIO().
ShutdownThreadpool()
void ShutdownThreadpool (void) static
{
    if (SDL_ShouldQuit(&threadpool_init)) {
        SDL_LockMutex(threadpool_lock);
        // cancel anything that's still pending.
        SDL_AsyncIOTask *task;
        while ((task = LINKED_LIST_START(threadpool_tasks, threadpool)) != NULL) {
            LINKED_LIST_UNLINK(task, threadpool);
            task->result = SDL_ASYNCIO_CANCELED;
            AsyncIOTaskComplete(task);
        }
        stop_threadpool = true;
        SDL_BroadcastCondition(threadpool_condition);  // tell the whole threadpool to wake up and quit.
        while (running_threadpool_threads > 0) {
            // each threadpool thread will broadcast this condition before it terminates if stop_threadpool is set.
            // we can't just join the threads because they are detached, so the thread pool can automatically shrink as necessary.
            SDL_WaitCondition(threadpool_condition, threadpool_lock);
        }
        SDL_UnlockMutex(threadpool_lock);
        SDL_DestroyMutex(threadpool_lock);
        threadpool_lock = NULL;
        SDL_DestroyCondition(threadpool_condition);
        threadpool_condition = NULL;
        max_threadpool_threads = running_threadpool_threads = idle_threadpool_threads = threadpool_threads_spun = 0;
        stop_threadpool = false;
        SDL_SetInitialized(&threadpool_init, false);
    }
}
References AsyncIOTaskComplete(), idle_threadpool_threads, LINKED_LIST_START, LINKED_LIST_UNLINK, max_threadpool_threads, NULL, SDL_AsyncIOTask::result, running_threadpool_threads, SDL_ASYNCIO_CANCELED, SDL_BroadcastCondition(), SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_LockMutex(), SDL_SetInitialized(), SDL_ShouldQuit(), SDL_UnlockMutex(), SDL_WaitCondition(), stop_threadpool, threadpool_condition, threadpool_init, threadpool_lock, threadpool_tasks, and threadpool_threads_spun.
Referenced by SDL_SYS_QuitAsyncIO_Generic().
SynchronousIO()
void SynchronousIO (SDL_AsyncIOTask * task) static
{
    SDL_assert(task->result != SDL_ASYNCIO_CANCELED);  // shouldn't have gotten in here if canceled!
    GenericAsyncIOData *data = (GenericAsyncIOData *) task->asyncio->userdata;
    SDL_IOStream *io = data->io;
    const size_t size = (size_t) task->requested_size;
    void *ptr = task->buffer;
    // this seek won't work if two tasks are reading from the same file at the same time,
    // so we lock here. This makes multiple reads from a single file serialize, but different
    // files will still run in parallel. An app can also open the same file twice to avoid this.
    SDL_LockMutex(data->lock);
    if (task->type == SDL_ASYNCIO_TASK_CLOSE) {
        bool okay = true;
        if (task->flush) {
            okay = SDL_FlushIO(data->io);
        }
        okay = SDL_CloseIO(data->io) && okay;
        task->result = okay ? SDL_ASYNCIO_COMPLETE : SDL_ASYNCIO_FAILURE;
    } else if (SDL_SeekIO(io, (Sint64) task->offset, SDL_IO_SEEK_SET) < 0) {
        task->result = SDL_ASYNCIO_FAILURE;
    } else {
        const bool writing = (task->type == SDL_ASYNCIO_TASK_WRITE);
        task->result_size = (Uint64) (writing ? SDL_WriteIO(io, ptr, size) : SDL_ReadIO(io, ptr, size));
        if (task->result_size == task->requested_size) {
            task->result = SDL_ASYNCIO_COMPLETE;
        } else {
            if (writing) {
                task->result = SDL_ASYNCIO_FAILURE;  // it's always a failure on short writes.
            } else {
                const SDL_IOStatus status = SDL_GetIOStatus(io);
                SDL_assert(status != SDL_IO_STATUS_READY);  // this should have either failed or been EOF.
                SDL_assert(status != SDL_IO_STATUS_NOT_READY);  // these should not be non-blocking reads!
                task->result = (status == SDL_IO_STATUS_EOF) ? SDL_ASYNCIO_COMPLETE : SDL_ASYNCIO_FAILURE;
            }
        }
    }
    SDL_UnlockMutex(data->lock);
    AsyncIOTaskComplete(task);
}
References SDL_AsyncIOTask::asyncio, AsyncIOTaskComplete(), SDL_AsyncIOTask::buffer, SDL_AsyncIOTask::flush, SDL_AsyncIOTask::offset, SDL_AsyncIOTask::requested_size, SDL_AsyncIOTask::result, SDL_AsyncIOTask::result_size, SDL_assert, SDL_ASYNCIO_CANCELED, SDL_ASYNCIO_COMPLETE, SDL_ASYNCIO_FAILURE, SDL_ASYNCIO_TASK_CLOSE, SDL_ASYNCIO_TASK_WRITE, SDL_CloseIO(), SDL_FlushIO(), SDL_GetIOStatus(), SDL_IO_SEEK_SET, SDL_IO_STATUS_EOF, SDL_IO_STATUS_NOT_READY, SDL_IO_STATUS_READY, SDL_LockMutex(), SDL_ReadIO(), SDL_SeekIO(), SDL_UnlockMutex(), SDL_WriteIO(), SDL_AsyncIOTask::type, and SDL_AsyncIO::userdata.
Referenced by AsyncIOThreadpoolWorker(), and generic_asyncioqueue_queue_task().
Variable Documentation
idle_threadpool_threads
int idle_threadpool_threads = 0 static
Referenced by AsyncIOThreadpoolWorker(), MaybeSpinNewWorkerThread(), and ShutdownThreadpool().
max_threadpool_threads
int max_threadpool_threads = 0 static
Referenced by MaybeSpinNewWorkerThread(), PrepareThreadpool(), and ShutdownThreadpool().
running_threadpool_threads
int running_threadpool_threads = 0 static
Referenced by AsyncIOThreadpoolWorker(), MaybeSpinNewWorkerThread(), and ShutdownThreadpool().
stop_threadpool
bool stop_threadpool = false static
Referenced by AsyncIOThreadpoolWorker(), QueueAsyncIOTask(), and ShutdownThreadpool().
threadpool_condition
SDL_Condition* threadpool_condition = NULL static
Referenced by AsyncIOThreadpoolWorker(), PrepareThreadpool(), QueueAsyncIOTask(), and ShutdownThreadpool().
threadpool_init
SDL_InitState threadpool_init static
Referenced by PrepareThreadpool(), and ShutdownThreadpool().
threadpool_lock
SDL_Mutex* threadpool_lock = NULL static
Referenced by AsyncIOThreadpoolWorker(), generic_asyncioqueue_cancel_task(), PrepareThreadpool(), QueueAsyncIOTask(), and ShutdownThreadpool().
threadpool_tasks
SDL_AsyncIOTask threadpool_tasks static
Referenced by AsyncIOThreadpoolWorker(), QueueAsyncIOTask(), and ShutdownThreadpool().
threadpool_threads_spun
int threadpool_threads_spun = 0 static
Referenced by MaybeSpinNewWorkerThread(), and ShutdownThreadpool().