SDL3: SDL-main/src/sensor/SDL_sensor_c.h File Reference
SDL_sensor_c.h File Reference
#include "SDL_internal.h"
Functions
void SDL_AssertSensorsLocked (void) SDL_ASSERT_CAPABILITY(SDL_sensor_lock)
bool SDL_InitSensors (void)
void SDL_LockSensors (void) SDL_ACQUIRE(SDL_sensor_lock)
void SDL_QuitSensors (void)
void SDL_SendSensorUpdate (Uint64 timestamp, SDL_Sensor *sensor, Uint64 sensor_timestamp, float *data, int num_values)
bool SDL_SensorsInitialized (void)
bool SDL_SensorsLocked (void)
bool SDL_SensorsOpened (void)
void SDL_UnlockSensors (void) SDL_RELEASE(SDL_sensor_lock)
void SDL_UpdateSensor (SDL_Sensor *sensor)
Function Documentation
SDL_AssertSensorsLocked()
void SDL_AssertSensorsLocked (void) extern
{
    SDL_assert(SDL_SensorsLocked());
}
References SDL_assert, and SDL_SensorsLocked().
Referenced by SDL_SendSensorUpdate().
SDL_InitSensors()
bool SDL_InitSensors (void) extern
{
    int i;
    bool status;
    // Create the sensor list lock
    if (SDL_sensor_lock == NULL) {
        SDL_sensor_lock = SDL_CreateMutex();
    }
    if (!SDL_InitSubSystem(SDL_INIT_EVENTS)) {
        return false;
    }
    SDL_LockSensors();
    SDL_sensors_initialized = true;
    status = false;
    for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
        if (SDL_sensor_drivers[i]->Init()) {
            status = true;
        }
    }
    SDL_UnlockSensors();
    if (!status) {
        SDL_QuitSensors();
    }
    return status;
}
References NULL, SDL_arraysize, SDL_CreateMutex(), SDL_INIT_EVENTS, SDL_InitSubSystem(), SDL_LockSensors(), SDL_QuitSensors(), SDL_sensor_drivers, SDL_sensor_lock, SDL_sensors_initialized, and SDL_UnlockSensors().
Referenced by SDL_InitSubSystem().
SDL_LockSensors()
void SDL_LockSensors (void) extern
{
    (void)SDL_AtomicIncRef(&SDL_sensor_lock_pending);
    SDL_LockMutex(SDL_sensor_lock);
    (void)SDL_AtomicDecRef(&SDL_sensor_lock_pending);
    ++SDL_sensors_locked;
}
References SDL_AtomicDecRef, SDL_AtomicIncRef, SDL_LockMutex(), SDL_sensor_lock, SDL_sensor_lock_pending, SDL_sensors_locked, and void().
Referenced by SDL_CloseSensor(), SDL_GetSensorData(), SDL_GetSensorFromID(), SDL_GetSensorID(), SDL_GetSensorName(), SDL_GetSensorNameForID(), SDL_GetSensorNonPortableType(), SDL_GetSensorNonPortableTypeForID(), SDL_GetSensorProperties(), SDL_GetSensors(), SDL_GetSensorType(), SDL_GetSensorTypeForID(), SDL_InitSensors(), SDL_OpenSensor(), SDL_QuitSensors(), SDL_SensorsOpened(), SDL_UpdateSensor(), and SDL_UpdateSensors().
SDL_QuitSensors()
void SDL_QuitSensors (void) extern
{
    int i;
    SDL_LockSensors();
    // Stop the event polling
    while (SDL_sensors) {
        SDL_sensors->ref_count = 1;
        SDL_CloseSensor(SDL_sensors);
    }
    // Quit the sensor setup
    for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
        SDL_sensor_drivers[i]->Quit();
    }
    SDL_QuitSubSystem(SDL_INIT_EVENTS);
    SDL_sensors_initialized = false;
    SDL_UnlockSensors();
}
References SDL_arraysize, SDL_CloseSensor(), SDL_INIT_EVENTS, SDL_LockSensors(), SDL_QuitSubSystem(), SDL_sensor_drivers, SDL_sensors_initialized, and SDL_UnlockSensors().
Referenced by SDL_InitSensors(), and SDL_QuitSubSystem().
SDL_SendSensorUpdate()
void SDL_SendSensorUpdate (Uint64 timestamp, SDL_Sensor * sensor, Uint64 sensor_timestamp, float * data, int num_values) extern
{
    SDL_AssertSensorsLocked();
    // Allow duplicate events, for things like steps and heartbeats
    // Update internal sensor state
    num_values = SDL_min(num_values, SDL_arraysize(sensor->data));
    SDL_memcpy(sensor->data, data, num_values * sizeof(*data));
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_SENSOR_UPDATE)) {
        SDL_Event event;
        event.type = SDL_EVENT_SENSOR_UPDATE;
        event.common.timestamp = timestamp;
        event.sensor.which = sensor->instance_id;
        num_values = SDL_min(num_values, SDL_arraysize(event.sensor.data));
        SDL_memset(event.sensor.data, 0, sizeof(event.sensor.data));
        SDL_memcpy(event.sensor.data, data, num_values * sizeof(*data));
        event.sensor.sensor_timestamp = sensor_timestamp;
        SDL_PushEvent(&event);
    }
    SDL_GamepadSensorWatcher(timestamp, sensor->instance_id, sensor_timestamp, data, num_values);
}
References SDL_arraysize, SDL_AssertSensorsLocked(), SDL_EVENT_SENSOR_UPDATE, SDL_EventEnabled(), SDL_GamepadSensorWatcher(), SDL_memcpy, SDL_memset, SDL_min, and SDL_PushEvent().
SDL_SensorsInitialized()
bool SDL_SensorsInitialized (void) extern
{
    return SDL_sensors_initialized;
}
References SDL_sensors_initialized.
SDL_SensorsLocked()
bool SDL_SensorsLocked (void) extern
{
    return (SDL_sensors_locked > 0);
}
References SDL_sensors_locked.
Referenced by SDL_AssertSensorsLocked().
SDL_SensorsOpened()
bool SDL_SensorsOpened (void) extern
{
    bool opened;
    SDL_LockSensors();
    {
        if (SDL_sensors != NULL) {
            opened = true;
        } else {
            opened = false;
        }
    }
    SDL_UnlockSensors();
    return opened;
}
References NULL, SDL_LockSensors(), and SDL_UnlockSensors().
Referenced by SDL_events_get_polling_interval().
SDL_UnlockSensors()
void SDL_UnlockSensors (void) extern
{
    bool last_unlock = false;
    --SDL_sensors_locked;
    if (!SDL_sensors_initialized) {
        // NOTE: There's a small window here where another thread could lock the mutex after we've checked for pending locks
        if (!SDL_sensors_locked && SDL_GetAtomicInt(&SDL_sensor_lock_pending) == 0) {
            last_unlock = true;
        }
    }
    /* The last unlock after sensors are uninitialized will cleanup the mutex,
     * allowing applications to lock sensors while reinitializing the system.
     */
    if (last_unlock) {
        SDL_Mutex *sensor_lock = SDL_sensor_lock;
        SDL_LockMutex(sensor_lock);
        {
            SDL_UnlockMutex(SDL_sensor_lock);
            SDL_sensor_lock = NULL;
        }
        SDL_UnlockMutex(sensor_lock);
        SDL_DestroyMutex(sensor_lock);
    } else {
        SDL_UnlockMutex(SDL_sensor_lock);
    }
}
References NULL, SDL_DestroyMutex(), SDL_GetAtomicInt(), SDL_LockMutex(), SDL_sensor_lock, SDL_sensor_lock_pending, SDL_sensors_initialized, SDL_sensors_locked, and SDL_UnlockMutex().
Referenced by SDL_CloseSensor(), SDL_GetSensorData(), SDL_GetSensorFromID(), SDL_GetSensorID(), SDL_GetSensorName(), SDL_GetSensorNameForID(), SDL_GetSensorNonPortableType(), SDL_GetSensorNonPortableTypeForID(), SDL_GetSensorProperties(), SDL_GetSensors(), SDL_GetSensorType(), SDL_GetSensorTypeForID(), SDL_InitSensors(), SDL_OpenSensor(), SDL_QuitSensors(), SDL_SensorsOpened(), SDL_UpdateSensor(), and SDL_UpdateSensors().
SDL_UpdateSensor()
void SDL_UpdateSensor (SDL_Sensor * sensor) extern
{
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor,);
        sensor->driver->Update(sensor);
    }
    SDL_UnlockSensors();
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), and SDL_UnlockSensors().