SDL3: SDL-main/src/storage/SDL_storage.c File Reference
SDL_storage.c File Reference
#include "SDL_internal.h"
#include "SDL_sysstorage.h"
#include "../filesystem/SDL_sysfilesystem.h"
Data Structures
struct SDL_Storage
Macros
#define CHECK_STORAGE_MAGIC()
#define CHECK_STORAGE_MAGIC_RET(result)
Functions
static bool GlobStorageDirectoryEnumerator (const char *path, SDL_EnumerateDirectoryCallback cb, void *cbuserdata, void *userdata)
static bool GlobStorageDirectoryGetPathInfo (const char *path, SDL_PathInfo *info, void *userdata)
bool SDL_CloseStorage (SDL_Storage *storage)
bool SDL_CopyStorageFile (SDL_Storage *storage, const char *oldpath, const char *newpath)
bool SDL_CreateStorageDirectory (SDL_Storage *storage, const char *path)
bool SDL_EnumerateStorageDirectory (SDL_Storage *storage, const char *path, SDL_EnumerateDirectoryCallback callback, void *userdata)
bool SDL_GetStorageFileSize (SDL_Storage *storage, const char *path, Uint64 *length)
bool SDL_GetStoragePathInfo (SDL_Storage *storage, const char *path, SDL_PathInfo *info)
Uint64 SDL_GetStorageSpaceRemaining (SDL_Storage *storage)
char ** SDL_GlobStorageDirectory (SDL_Storage *storage, const char *path, const char *pattern, SDL_GlobFlags flags, int *count)
SDL_Storage * SDL_OpenFileStorage (const char *path)
SDL_Storage * SDL_OpenStorage (const SDL_StorageInterface *iface, void *userdata)
SDL_Storage * SDL_OpenTitleStorage (const char *override, SDL_PropertiesID props)
SDL_Storage * SDL_OpenUserStorage (const char *org, const char *app, SDL_PropertiesID props)
bool SDL_ReadStorageFile (SDL_Storage *storage, const char *path, void *destination, Uint64 length)
bool SDL_RemoveStoragePath (SDL_Storage *storage, const char *path)
bool SDL_RenameStoragePath (SDL_Storage *storage, const char *oldpath, const char *newpath)
bool SDL_StorageReady (SDL_Storage *storage)
bool SDL_WriteStorageFile (SDL_Storage *storage, const char *path, const void *source, Uint64 length)
static bool ValidateStoragePath (const char *path)
Variables
static TitleStorageBootStrap * titlebootstrap []
static UserStorageBootStrap * userbootstrap []
Macro Definition Documentation
CHECK_STORAGE_MAGIC
#define CHECK_STORAGE_MAGIC ()
Value:
    if (!storage) {                                       \
        return SDL_SetError("Invalid storage container"); \
    }
#define CHECK_STORAGE_MAGIC()                             \
    if (!storage) {                                       \
        return SDL_SetError("Invalid storage container"); \
    }
Referenced by SDL_CloseStorage(), SDL_CopyStorageFile(), SDL_CreateStorageDirectory(), SDL_EnumerateStorageDirectory(), SDL_GetStoragePathInfo(), SDL_ReadStorageFile(), SDL_RemoveStoragePath(), SDL_RenameStoragePath(), and SDL_WriteStorageFile().
CHECK_STORAGE_MAGIC_RET
#define CHECK_STORAGE_MAGIC_RET (result)
Value:
    if (!storage) {                                \
        SDL_SetError("Invalid storage container"); \
        return result;                             \
    }
#define CHECK_STORAGE_MAGIC_RET(result)            \
    if (!storage) {                                \
        SDL_SetError("Invalid storage container"); \
        return result;                             \
    }
Referenced by SDL_GetStorageSpaceRemaining(), SDL_GlobStorageDirectory(), and SDL_StorageReady().
Function Documentation
GlobStorageDirectoryEnumerator()
bool GlobStorageDirectoryEnumerator (const char * path, SDL_EnumerateDirectoryCallback cb, void * cbuserdata, void * userdata) static
{
    return SDL_EnumerateStorageDirectory((SDL_Storage *) userdata, path, cb, cbuserdata);
}
References SDL_EnumerateStorageDirectory().
Referenced by SDL_GlobStorageDirectory().
GlobStorageDirectoryGetPathInfo()
bool GlobStorageDirectoryGetPathInfo (const char * path, SDL_PathInfo * info, void * userdata) static
{
    return SDL_GetStoragePathInfo((SDL_Storage *) userdata, path, info);
}
References SDL_GetStoragePathInfo().
Referenced by SDL_GlobStorageDirectory().
SDL_CloseStorage()
bool SDL_CloseStorage (SDL_Storage * storage)
Closes and frees a storage container.
Parameters
storage a storage container to close.
Returns
true if the container was freed with no errors, false otherwise; call SDL_GetError() for more information. Even if the function returns an error, the container data will be freed; the error is only for informational purposes.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenFileStorage
SDL_OpenStorage
SDL_OpenTitleStorage
SDL_OpenUserStorage
{
    bool result = true;
    CHECK_STORAGE_MAGIC()
    if (storage->iface.close) {
        result = storage->iface.close(storage->userdata);
    }
    SDL_free(storage);
    return result;
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_free(), and SDL_Storage::userdata.
SDL_CopyStorageFile()
bool SDL_CopyStorageFile (SDL_Storage * storage, const char * oldpath, const char * newpath)
Copy a file in a writable storage container.
Parameters
storage a storage container.
oldpath the old path.
newpath the new path.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!oldpath) {
        return SDL_InvalidParamError("oldpath");
    } else if (!newpath) {
        return SDL_InvalidParamError("newpath");
    } else if (!ValidateStoragePath(oldpath)) {
        return false;
    } else if (!ValidateStoragePath(newpath)) {
        return false;
    } else if (!storage->iface.copy) {
        return SDL_Unsupported();
    }
    return storage->iface.copy(storage->userdata, oldpath, newpath);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_CreateStorageDirectory()
bool SDL_CreateStorageDirectory (SDL_Storage * storage, const char * path)
Create a directory in a writable storage container.
Parameters
storage a storage container.
path the path of the directory to create.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.mkdir) {
        return SDL_Unsupported();
    }
    return storage->iface.mkdir(storage->userdata, path);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_EnumerateStorageDirectory()
bool SDL_EnumerateStorageDirectory (SDL_Storage * storage, const char * path, SDL_EnumerateDirectoryCallback callback, void * userdata)
Enumerate a directory in a storage container through a callback function.
This function provides every directory entry through an app-provided callback, called once for each directory entry, until all results have been provided or the callback returns either SDL_ENUM_SUCCESS or SDL_ENUM_FAILURE.
This will return false if there was a system problem in general, or if a callback returns SDL_ENUM_FAILURE. A successful return means a callback returned SDL_ENUM_SUCCESS to halt enumeration, or all directory entries were enumerated.
If path is NULL, this is treated as a request to enumerate the root of the storage container's tree. An empty string also works for this.
Parameters
storage a storage container.
path the path of the directory to enumerate, or NULL for the root.
callback a function that is called for each entry in the directory.
userdata a pointer that is passed to callback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        path = "";  // we allow NULL to mean "root of the storage tree".
    }
    if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.enumerate) {
        return SDL_Unsupported();
    }
    return storage->iface.enumerate(storage->userdata, path, callback, userdata);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
Referenced by GlobStorageDirectoryEnumerator().
SDL_GetStorageFileSize()
bool SDL_GetStorageFileSize (SDL_Storage * storage, const char * path, Uint64 * length)
Query the size of a file within a storage container.
Parameters
storage a storage container to query.
path the relative path of the file to query.
length a pointer to be filled with the file's length.
Returns
true if the file could be queried or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ReadStorageFile
SDL_StorageReady
{
    SDL_PathInfo info;
    if (SDL_GetStoragePathInfo(storage, path, &info)) {
        if (length) {
            *length = info.size;
        }
        return true;
    } else {
        if (length) {
            *length = 0;
        }
        return false;
    }
}
References SDL_GetStoragePathInfo(), and SDL_PathInfo::size.
SDL_GetStoragePathInfo()
bool SDL_GetStoragePathInfo (SDL_Storage * storage, const char * path, SDL_PathInfo * info)
Get information about a filesystem path in a storage container.
Parameters
storage a storage container.
path the path to query.
info a pointer filled in with information about the path, or NULL to check for the existence of a file.
Returns
true on success or false if the file doesn't exist, or another failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    SDL_PathInfo dummy;
    if (!info) {
        info = &dummy;
    }
    SDL_zerop(info);
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.info) {
        return SDL_Unsupported();
    }
    return storage->iface.info(storage->userdata, path, info);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_StorageInterface::info, SDL_InvalidParamError, SDL_Unsupported, SDL_zerop, SDL_Storage::userdata, and ValidateStoragePath().
Referenced by GlobStorageDirectoryGetPathInfo(), and SDL_GetStorageFileSize().
SDL_GetStorageSpaceRemaining()
Uint64 SDL_GetStorageSpaceRemaining (SDL_Storage * storage)
Queries the remaining space in a storage container.
Parameters
storage a storage container to query.
Returns
the amount of remaining space, in bytes.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
SDL_WriteStorageFile
{
    CHECK_STORAGE_MAGIC_RET(0)
    if (!storage->iface.space_remaining) {
        SDL_Unsupported();
        return 0;
    }
    return storage->iface.space_remaining(storage->userdata);
}
References CHECK_STORAGE_MAGIC_RET, SDL_Storage::iface, SDL_Unsupported, and SDL_Storage::userdata.
SDL_GlobStorageDirectory()
char ** SDL_GlobStorageDirectory (SDL_Storage * storage, const char * path, const char * pattern, SDL_GlobFlags flags, int * count)
Enumerate a directory tree, filtered by pattern, and return a list.
Files are filtered out if they don't match the string in pattern, which may contain wildcard characters * (match everything) and ? (match one character). If pattern is NULL, no filtering is done and all results are returned. Subdirectories are permitted, and are specified with a path separator of '/'. Wildcard characters * and ? never match a path separator.
flags may be set to SDL_GLOB_CASEINSENSITIVE to make the pattern matching case-insensitive.
The returned array is always NULL-terminated, for your iterating convenience, but if count is non-NULL, on return it will contain the number of items in the array, not counting the NULL terminator.
If path is NULL, this is treated as a request to enumerate the root of the storage container's tree. An empty string also works for this.
Parameters
storage a storage container.
path the path of the directory to enumerate, or NULL for the root.
pattern the pattern that files in the directory must match. Can be NULL.
flags SDL_GLOB_* bitflags that affect this search.
count on return, will be set to the number of items in the returned array. Can be NULL.
Returns
an array of strings on success or NULL on failure; call SDL_GetError() for more information. The caller should pass the returned pointer to SDL_free when done with it. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread, assuming the storage object is thread-safe.
Since
This function is available since SDL 3.2.0.
{
    CHECK_STORAGE_MAGIC_RET(NULL)
    if (!path) {
        path = "";  // we allow NULL to mean "root of the storage tree".
    }
    if (!ValidateStoragePath(path)) {
        return NULL;
    }
    return SDL_InternalGlobDirectory(path, pattern, flags, count, GlobStorageDirectoryEnumerator, GlobStorageDirectoryGetPathInfo, storage);
}
References CHECK_STORAGE_MAGIC_RET, count, GlobStorageDirectoryEnumerator(), GlobStorageDirectoryGetPathInfo(), NULL, SDL_InternalGlobDirectory(), and ValidateStoragePath().
SDL_OpenFileStorage()
SDL_Storage * SDL_OpenFileStorage (const char * path)
Opens up a container for local filesystem storage.
This is provided for development and tools. Portable applications should use SDL_OpenTitleStorage() for access to game data and SDL_OpenUserStorage() for access to user data.
Parameters
path the base path prepended to all storage paths, or NULL for no base path.
Returns
a filesystem storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_GetStorageSpaceRemaining
SDL_OpenTitleStorage
SDL_OpenUserStorage
SDL_ReadStorageFile
SDL_WriteStorageFile
{
    return GENERIC_OpenFileStorage(path);
}
References GENERIC_OpenFileStorage().
SDL_OpenStorage()
SDL_Storage * SDL_OpenStorage (const SDL_StorageInterface * iface, void * userdata)
Opens up a container using a client-provided storage interface.
Applications do not need to use this function unless they are providing their own SDL_Storage implementation. If you just need an SDL_Storage, you should use the built-in implementations in SDL, like SDL_OpenTitleStorage() or SDL_OpenUserStorage().
This function makes a copy of iface and the caller does not need to keep it around after this call.
Parameters
iface the interface that implements this storage, initialized using SDL_INIT_INTERFACE().
userdata the pointer that will be passed to the interface functions.
Returns
a storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_GetStorageSpaceRemaining
SDL_INIT_INTERFACE
SDL_ReadStorageFile
SDL_StorageReady
SDL_WriteStorageFile
{
    SDL_Storage *storage;
    if (!iface) {
        SDL_InvalidParamError("iface");
        return NULL;
    }
    if (iface->version < sizeof(*iface)) {
        // Update this to handle older versions of this interface
        SDL_SetError("Invalid interface, should be initialized with SDL_INIT_INTERFACE()");
        return NULL;
    }
    storage = (SDL_Storage *)SDL_calloc(1, sizeof(*storage));
    if (storage) {
        SDL_copyp(&storage->iface, iface);
        storage->userdata = userdata;
    }
    return storage;
}
References SDL_Storage::iface, NULL, SDL_calloc(), SDL_copyp, SDL_InvalidParamError, SDL_SetError(), SDL_Storage::userdata, and SDL_StorageInterface::version.
Referenced by GENERIC_OpenFileStorage(), GENERIC_Title_Create(), GENERIC_User_Create(), and STEAM_User_Create().
SDL_OpenTitleStorage()
SDL_Storage * SDL_OpenTitleStorage (const char * override, SDL_PropertiesID props)
Opens up a read-only container for the application's filesystem.
By default, SDL_OpenTitleStorage uses the generic storage implementation. When the path override is not provided, the generic implementation will use the output of SDL_GetBasePath as the base path.
Parameters
override a path to override the backend's default title root.
props a property list that may contain backend-specific information.
Returns
a title storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_OpenUserStorage
SDL_ReadStorageFile
{
    SDL_Storage *storage = NULL;
    int i = 0;
    // Select the proper storage driver
    const char *driver_name = SDL_GetHint(SDL_HINT_STORAGE_TITLE_DRIVER);
    if (driver_name && *driver_name != 0) {
        const char *driver_attempt = driver_name;
        while (driver_attempt && *driver_attempt != 0 && !storage) {
            const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
            for (i = 0; titlebootstrap[i]; ++i) {
                if ((driver_attempt_len == SDL_strlen(titlebootstrap[i]->name)) &&
                    (SDL_strncasecmp(titlebootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                    storage = titlebootstrap[i]->create(override, props);
                    break;
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
    } else {
        for (i = 0; titlebootstrap[i]; ++i) {
            storage = titlebootstrap[i]->create(override, props);
            if (storage) {
                break;
            }
        }
    }
    if (storage) {
        SDL_DebugLogBackend("title_storage", titlebootstrap[i]->name);
    } else {
        if (driver_name) {
            SDL_SetError("%s not available", driver_name);
        } else {
            SDL_SetError("No available title storage driver");
        }
    }
    return storage;
}
References NULL, SDL_DebugLogBackend(), SDL_GetHint(), SDL_HINT_STORAGE_TITLE_DRIVER, SDL_SetError(), SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), and titlebootstrap.
SDL_OpenUserStorage()
SDL_Storage * SDL_OpenUserStorage (const char * org, const char * app, SDL_PropertiesID props)
Opens up a container for a user's unique read/write filesystem.
While title storage can generally be kept open throughout runtime, user storage should only be opened when the client is ready to read/write files. This allows the backend to properly batch file operations and flush them when the container has been closed; ensuring safe and optimal save I/O.
Parameters
org the name of your organization.
app the name of your application.
props a property list that may contain backend-specific information.
Returns
a user storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_GetStorageSpaceRemaining
SDL_OpenTitleStorage
SDL_ReadStorageFile
SDL_StorageReady
SDL_WriteStorageFile
{
    SDL_Storage *storage = NULL;
    int i = 0;
    // Select the proper storage driver
    const char *driver_name = SDL_GetHint(SDL_HINT_STORAGE_USER_DRIVER);
    if (driver_name && *driver_name != 0) {
        const char *driver_attempt = driver_name;
        while (driver_attempt && *driver_attempt != 0 && !storage) {
            const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
            for (i = 0; userbootstrap[i]; ++i) {
                if ((driver_attempt_len == SDL_strlen(userbootstrap[i]->name)) &&
                    (SDL_strncasecmp(userbootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                    storage = userbootstrap[i]->create(org, app, props);
                    break;
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
    } else {
        for (i = 0; userbootstrap[i]; ++i) {
            storage = userbootstrap[i]->create(org, app, props);
            if (storage) {
                break;
            }
        }
    }
    if (storage) {
        SDL_DebugLogBackend("user_storage", userbootstrap[i]->name);
    } else {
        if (driver_name) {
            SDL_SetError("%s not available", driver_name);
        } else {
            SDL_SetError("No available user storage driver");
        }
    }
    return storage;
}
References NULL, SDL_DebugLogBackend(), SDL_GetHint(), SDL_HINT_STORAGE_USER_DRIVER, SDL_SetError(), SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), and userbootstrap.
SDL_ReadStorageFile()
bool SDL_ReadStorageFile (SDL_Storage * storage, const char * path, void * destination, Uint64 length)
Synchronously read a file from a storage container into a client-provided buffer.
The value of length must match the length of the file exactly; call SDL_GetStorageFileSize() to get this value. This behavior may be relaxed in a future release.
Parameters
storage a storage container to read from.
path the relative path of the file to read.
destination a client-provided buffer to read the file into.
length the length of the destination buffer.
Returns
true if the file was read or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetStorageFileSize
SDL_StorageReady
SDL_WriteStorageFile
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.read_file) {
        return SDL_Unsupported();
    }
    return storage->iface.read_file(storage->userdata, path, destination, length);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_RemoveStoragePath()
bool SDL_RemoveStoragePath (SDL_Storage * storage, const char * path)
Remove a file or an empty directory in a writable storage container.
Parameters
storage a storage container.
path the path of the directory to enumerate.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.remove) {
        return SDL_Unsupported();
    }
    return storage->iface.remove(storage->userdata, path);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_RenameStoragePath()
bool SDL_RenameStoragePath (SDL_Storage * storage, const char * oldpath, const char * newpath)
Rename a file or directory in a writable storage container.
Parameters
storage a storage container.
oldpath the old path.
newpath the new path.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!oldpath) {
        return SDL_InvalidParamError("oldpath");
    } else if (!newpath) {
        return SDL_InvalidParamError("newpath");
    } else if (!ValidateStoragePath(oldpath)) {
        return false;
    } else if (!ValidateStoragePath(newpath)) {
        return false;
    } else if (!storage->iface.rename) {
        return SDL_Unsupported();
    }
    return storage->iface.rename(storage->userdata, oldpath, newpath);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_StorageReady()
bool SDL_StorageReady (SDL_Storage * storage)
Checks if the storage container is ready to use.
This function should be called in regular intervals until it returns true - however, it is not recommended to spinwait on this call, as the backend may depend on a synchronous message loop. You might instead poll this in your game's main loop while processing events and drawing a loading screen.
Parameters
storage a storage container to query.
Returns
true if the container is ready, false otherwise.
Since
This function is available since SDL 3.2.0.
{
    CHECK_STORAGE_MAGIC_RET(false)
    if (storage->iface.ready) {
        return storage->iface.ready(storage->userdata);
    }
    return true;
}
References CHECK_STORAGE_MAGIC_RET, SDL_Storage::iface, and SDL_Storage::userdata.
SDL_WriteStorageFile()
bool SDL_WriteStorageFile (SDL_Storage * storage, const char * path, const void * source, Uint64 length)
Synchronously write a file from client memory into a storage container.
Parameters
storage a storage container to write to.
path the relative path of the file to write.
source a client-provided buffer to write from.
length the length of the source buffer.
Returns
true if the file was written or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetStorageSpaceRemaining
SDL_ReadStorageFile
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.write_file) {
        return SDL_Unsupported();
    }
    return storage->iface.write_file(storage->userdata, path, source, length);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
ValidateStoragePath()
bool ValidateStoragePath (const char * path) static
{
    if (SDL_strchr(path, '\\')) {
        return SDL_SetError("Windows-style path separators ('\\') not permitted, use '/' instead.");
    }
    const char *ptr;
    const char *prev = path;
    while ((ptr = SDL_strchr(prev, '/')) != NULL) {
        if ((SDL_strncmp(prev, "./", 2) == 0) || (SDL_strncmp(prev, "../", 3) == 0)) {
            return SDL_SetError("Relative paths not permitted");
        }
        prev = ptr + 1;
    }
    // check the last path element (or the only path element).
    if ((SDL_strcmp(prev, ".") == 0) || (SDL_strcmp(prev, "..") == 0)) {
        return SDL_SetError("Relative paths not permitted");
    }
    return true;
}
References NULL, SDL_SetError(), SDL_strchr(), SDL_strcmp(), and SDL_strncmp().
Referenced by SDL_CopyStorageFile(), SDL_CreateStorageDirectory(), SDL_EnumerateStorageDirectory(), SDL_GetStoragePathInfo(), SDL_GlobStorageDirectory(), SDL_ReadStorageFile(), SDL_RemoveStoragePath(), SDL_RenameStoragePath(), and SDL_WriteStorageFile().
Variable Documentation
titlebootstrap
TitleStorageBootStrap* titlebootstrap[] static
Initial value:
= {
    &GENERIC_titlebootstrap,
    NULL
}
{
    &GENERIC_titlebootstrap,
    NULL
};
Referenced by SDL_OpenTitleStorage().
userbootstrap
UserStorageBootStrap* userbootstrap[] static
Initial value:
= {
    &GENERIC_userbootstrap,
    NULL
}
{
#ifdef SDL_STORAGE_STEAM
    &STEAM_userbootstrap,
#endif
#ifdef SDL_STORAGE_PRIVATE
    &PRIVATE_userbootstrap,
#endif
    &GENERIC_userbootstrap,
    NULL
};
Referenced by SDL_OpenUserStorage().