SDL3: SDL-main/src/joystick/controller_type.c File Reference
controller_type.c File Reference
#include "SDL_internal.h"
#include "controller_type.h"
#include "controller_list.h"
Functions
static const char * GetControllerTypeOverride (int nVID, int nPID)
const char * GuessControllerName (int nVID, int nPID)
EControllerType GuessControllerType (int nVID, int nPID)
Function Documentation
GetControllerTypeOverride()
const char * GetControllerTypeOverride (int nVID, int nPID) static
{
    const char *hint = SDL_GetHint(SDL_HINT_GAMECONTROLLERTYPE);
    if (hint) {
        char key[32];
        const char *spot = NULL;
        SDL_snprintf(key, sizeof(key), "0x%.4x/0x%.4x=", nVID, nPID);
        spot = SDL_strstr(hint, key);
        if (!spot) {
            SDL_snprintf(key, sizeof(key), "0x%.4X/0x%.4X=", nVID, nPID);
            spot = SDL_strstr(hint, key);
        }
        if (spot) {
            spot += SDL_strlen(key);
            if (SDL_strncmp(spot, "k_eControllerType_", 18) == 0) {
                spot += 18;
            }
            return spot;
        }
    }
    return NULL;
}
References NULL, SDL_GetHint(), SDL_HINT_GAMECONTROLLERTYPE, SDL_snprintf(), SDL_strlen(), SDL_strncmp(), and SDL_strstr().
Referenced by GuessControllerType().
GuessControllerName()
const char * GuessControllerName (int nVID, int nPID)
{
    unsigned int unDeviceID = MAKE_CONTROLLER_ID( nVID, nPID );
    int iIndex;
    for ( iIndex = 0; iIndex < sizeof( arrControllers ) / sizeof( arrControllers[0] ); ++iIndex )
    {
        if ( unDeviceID == arrControllers[ iIndex ].m_unDeviceID )
        {
            return arrControllers[ iIndex ].m_pszName;
        }
    }
    return NULL;
}
References arrControllers, MAKE_CONTROLLER_ID, and NULL.
Referenced by SDL_CreateJoystickName().
GuessControllerType()
EControllerType GuessControllerType (int nVID, int nPID)
{
#if 0//def _DEBUG
    // Verify that there are no duplicates in the controller list
    // If the list were sorted, we could do this much more efficiently, as well as improve lookup speed.
    static bool s_bCheckedForDuplicates;
    if ( !s_bCheckedForDuplicates )
    {
        s_bCheckedForDuplicates = true;
        int i, j;
        for ( i = 0; i < sizeof( arrControllers ) / sizeof( arrControllers[ 0 ] ); ++i )
        {
            for ( j = i + 1; j < sizeof( arrControllers ) / sizeof( arrControllers[ 0 ] ); ++j )
            {
                if ( arrControllers[ i ].m_unDeviceID == arrControllers[ j ].m_unDeviceID )
                {
                    Log( "Duplicate controller entry found for VID 0x%.4x PID 0x%.4x\n", ( arrControllers[ i ].m_unDeviceID >> 16 ), arrControllers[ i ].m_unDeviceID & 0xFFFF );
                }
            }
        }
    }
#endif // _DEBUG
    unsigned int unDeviceID = MAKE_CONTROLLER_ID( nVID, nPID );
    int iIndex;
    const char *pszOverride = GetControllerTypeOverride( nVID, nPID );
    if ( pszOverride )
    {
        if ( SDL_strncasecmp( pszOverride, "Xbox360", 7 ) == 0 )
        {
            return k_eControllerType_XBox360Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "XboxOne", 7 ) == 0 )
        {
            return k_eControllerType_XBoxOneController;
        }
        if ( SDL_strncasecmp( pszOverride, "PS3", 3 ) == 0 )
        {
            return k_eControllerType_PS3Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "PS4", 3 ) == 0 )
        {
            return k_eControllerType_PS4Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "PS5", 3 ) == 0 )
        {
            return k_eControllerType_PS5Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "SwitchPro", 9 ) == 0 )
        {
            return k_eControllerType_SwitchProController;
        }
        if ( SDL_strncasecmp( pszOverride, "Steam", 5 ) == 0 )
        {
            return k_eControllerType_SteamController;
        }
        return k_eControllerType_UnknownNonSteamController;
    }
    for ( iIndex = 0; iIndex < sizeof( arrControllers ) / sizeof( arrControllers[0] ); ++iIndex )
    {
        if ( unDeviceID == arrControllers[ iIndex ].m_unDeviceID )
        {
            return arrControllers[ iIndex ].m_eControllerType;
        }
    }
    return k_eControllerType_UnknownNonSteamController;
}
References arrControllers, GetControllerTypeOverride(), k_eControllerType_PS3Controller, k_eControllerType_PS4Controller, k_eControllerType_PS5Controller, k_eControllerType_SteamController, k_eControllerType_SwitchProController, k_eControllerType_UnknownNonSteamController, k_eControllerType_XBox360Controller, k_eControllerType_XBoxOneController, MAKE_CONTROLLER_ID, and SDL_strncasecmp().
Referenced by SDL_GetGamepadTypeFromVIDPID(), SDL_GetJoystickGUIDType(), SDL_IsJoystickNintendoSwitchJoyCon(), SDL_IsJoystickNintendoSwitchJoyConLeft(), SDL_IsJoystickNintendoSwitchJoyConRight(), SDL_IsJoystickNintendoSwitchPro(), SDL_IsJoystickNintendoSwitchProInputOnly(), SDL_IsJoystickPS4(), SDL_IsJoystickPS5(), SDL_IsJoystickSteamController(), SDL_IsJoystickSteamDeck(), and SDL_IsJoystickXboxOne().