SDL3: SDL-main/src/hidapi/SDL_hidapi_c.h File Reference
SDL_hidapi_c.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_HIDAPI_ShouldIgnoreDevice (int bus_type, Uint16 vendor_id, Uint16 product_id, Uint16 usage_page, Uint16 usage)
Function Documentation
SDL_HIDAPI_ShouldIgnoreDevice()
bool SDL_HIDAPI_ShouldIgnoreDevice (int bus_type, Uint16 vendor_id, Uint16 product_id, Uint16 usage_page, Uint16 usage) extern
{
    // See if there are any devices we should skip in enumeration
    if (SDL_hidapi_only_controllers && usage_page) {
        if (vendor_id == USB_VENDOR_VALVE) {
            // Ignore the mouse/keyboard interface on Steam Controllers
            if (
#ifdef SDL_PLATFORM_WIN32
                // Check the usage page and usage on both USB and Bluetooth
#else
                // Only check the usage page and usage on USB
                bus == HID_API_BUS_USB &&
#endif
                usage_page == USB_USAGEPAGE_GENERIC_DESKTOP &&
                (usage == USB_USAGE_GENERIC_KEYBOARD || usage == USB_USAGE_GENERIC_MOUSE)) {
                return true;
            }
        } else if (vendor_id == USB_VENDOR_FLYDIGI && product_id == USB_PRODUCT_FLYDIGI_GAMEPAD) {
            if (usage_page == USB_USAGEPAGE_VENDOR_FLYDIGI) {
                return false;
            }
            return true;
        } else if (usage_page == USB_USAGEPAGE_GENERIC_DESKTOP &&
                   (usage == USB_USAGE_GENERIC_JOYSTICK || usage == USB_USAGE_GENERIC_GAMEPAD || usage == USB_USAGE_GENERIC_MULTIAXISCONTROLLER)) {
            // This is a controller
        } else {
            return true;
        }
    }
    if (SDL_hidapi_ignored_devices) {
        char vendor_match[16], product_match[16];
        SDL_snprintf(vendor_match, sizeof(vendor_match), "0x%.4x/0x0000", vendor_id);
        SDL_snprintf(product_match, sizeof(product_match), "0x%.4x/0x%.4x", vendor_id, product_id);
        if (SDL_strcasestr(SDL_hidapi_ignored_devices, vendor_match) ||
            SDL_strcasestr(SDL_hidapi_ignored_devices, product_match)) {
            return true;
        }
    }
    return false;
}
References HID_API_BUS_USB, SDL_hidapi_ignored_devices, SDL_hidapi_only_controllers, SDL_snprintf(), SDL_strcasestr(), USB_PRODUCT_FLYDIGI_GAMEPAD, USB_USAGE_GENERIC_GAMEPAD, USB_USAGE_GENERIC_JOYSTICK, USB_USAGE_GENERIC_KEYBOARD, USB_USAGE_GENERIC_MOUSE, USB_USAGE_GENERIC_MULTIAXISCONTROLLER, USB_USAGEPAGE_GENERIC_DESKTOP, USB_USAGEPAGE_VENDOR_FLYDIGI, USB_VENDOR_FLYDIGI, and USB_VENDOR_VALVE.
Referenced by PLATFORM_hid_enumerate().