SDL3: SDL-main/src/events/SDL_events.c File Reference
SDL_events.c File Reference
#include "SDL_internal.h"
#include "SDL_events_c.h"
#include "SDL_eventwatch_c.h"
#include "SDL_windowevents_c.h"
#include "../SDL_hints_c.h"
#include "../audio/SDL_audio_c.h"
#include "../camera/SDL_camera_c.h"
#include "../timer/SDL_timer_c.h"
#include "../joystick/SDL_joystick_c.h"
#include "../sensor/SDL_sensor_c.h"
#include "../video/SDL_sysvideo.h"
Data Structures
struct SDL2_SysWMmsg
struct SDL2_version
struct SDL_DisabledEventBlock
struct SDL_EventEntry
struct SDL_MainThreadCallbackEntry
struct SDL_TemporaryMemory
struct SDL_TemporaryMemoryState
Macros
#define ENUMERATION_POLL_INTERVAL_NS (3 * SDL_NS_PER_SECOND)
#define EVENT_POLL_INTERVAL_NS SDL_MS_TO_NS(1)
#define PRINT_AUDIODEV_EVENT(event)
#define PRINT_CAMERADEV_EVENT(event)
#define PRINT_CBUTTON_EVENT(event)
#define PRINT_CTOUCHPAD_EVENT(event)
#define PRINT_DROP_EVENT(event)
#define PRINT_FINGER_EVENT(event)
#define PRINT_GAMEPADDEV_EVENT(event)
#define PRINT_JBUTTON_EVENT(event)
#define PRINT_JOYDEV_EVENT(event)
#define PRINT_KEY_EVENT(event)
#define PRINT_KEYDEV_EVENT(event)
#define PRINT_MBUTTON_EVENT(event)
#define PRINT_MOUSEDEV_EVENT(event)
#define PRINT_PBUTTON_EVENT(event)
#define PRINT_PPROXIMITY_EVENT(event)
#define PRINT_PTOUCH_EVENT(event)
#define SDL2_SYSWMEVENT 0x201
#define SDL_DISPLAYEVENT_CASE(x)
#define SDL_EVENT_CASE(x)
#define SDL_MAX_QUEUED_EVENTS 65535
#define SDL_RENDEREVENT_CASE(x)
#define SDL_WINDOWEVENT_CASE(x)
#define uint unsigned int
Typedefs
typedef struct SDL2_SysWMmsg SDL2_SysWMmsg
typedef struct SDL2_version SDL2_version
typedef struct SDL_EventEntry SDL_EventEntry
typedef struct SDL_MainThreadCallbackEntry SDL_MainThreadCallbackEntry
typedef struct SDL_TemporaryMemory SDL_TemporaryMemory
typedef struct SDL_TemporaryMemoryState SDL_TemporaryMemoryState
Enumerations
enum SDL2_SYSWM_TYPE { SDL2_SYSWM_UNKNOWN }
enum SDL_MainThreadCallbackState { SDL_MAIN_CALLBACK_WAITING , SDL_MAIN_CALLBACK_COMPLETE , SDL_MAIN_CALLBACK_CANCELED }
Functions
static int SDL_AddEvent (SDL_Event *event)
bool SDL_AddEventWatch (SDL_EventFilter filter, void *userdata)
void * SDL_AllocateTemporaryMemory (size_t size)
static void SDLCALL SDL_AutoUpdateJoysticksChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
static void SDLCALL SDL_AutoUpdateSensorsChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
static bool SDL_CallEventWatchers (SDL_Event *event)
void * SDL_ClaimTemporaryMemory (const void *mem)
static void SDL_CleanupTemporaryMemory (void *data)
SDL_COMPILE_TIME_ASSERT (SDL_Event_type, sizeof(Uint32)==sizeof(SDL_EventType))
static SDL_MainThreadCallbackEntry * SDL_CreateMainThreadCallback (SDL_MainThreadCallback callback, void *userdata, bool wait_complete)
const char * SDL_CreateTemporaryString (const char *string)
static void SDL_CutEvent (SDL_EventEntry *entry)
static void SDL_DestroyMainThreadCallback (SDL_MainThreadCallbackEntry *entry)
bool SDL_EventEnabled (Uint32 type)
static void SDLCALL SDL_EventLoggingChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
static Sint64 SDL_events_get_polling_interval (void)
void SDL_FilterEvents (SDL_EventFilter filter, void *userdata)
static SDL_Window * SDL_find_active_window (SDL_VideoDevice *_this)
void SDL_FlushEvent (Uint32 type)
void SDL_FlushEvents (Uint32 minType, Uint32 maxType)
static void * SDL_FreeLater (void *memory)
void SDL_FreeTemporaryMemory (void)
static void SDL_FreeTemporaryMemoryEntry (SDL_TemporaryMemoryState *state, SDL_TemporaryMemory *entry, bool free_data)
int SDL_GetEventDescription (const SDL_Event *event, char *buf, int buflen)
bool SDL_GetEventFilter (SDL_EventFilter *filter, void **userdata)
static SDL_TemporaryMemory * SDL_GetTemporaryMemoryEntry (SDL_TemporaryMemoryState *state, const void *mem)
static SDL_TemporaryMemoryState * SDL_GetTemporaryMemoryState (bool create)
bool SDL_HasEvent (Uint32 type)
bool SDL_HasEvents (Uint32 minType, Uint32 maxType)
bool SDL_InitEvents (void)
static void SDL_InitMainThreadCallbacks (void)
static void SDL_LinkTemporaryMemoryEntry (SDL_TemporaryMemoryState *state, SDL_TemporaryMemory *entry)
static void SDL_LinkTemporaryMemoryToEvent (SDL_EventEntry *event, const void *mem)
static void SDL_LogEvent (const SDL_Event *event)
int SDL_PeepEvents (SDL_Event *events, int numevents, SDL_EventAction action, Uint32 minType, Uint32 maxType)
static int SDL_PeepEventsInternal (SDL_Event *events, int numevents, SDL_EventAction action, Uint32 minType, Uint32 maxType, bool include_sentinel)
bool SDL_PollEvent (SDL_Event *event)
static void SDLCALL SDL_PollSentinelChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
void SDL_PumpEventMaintenance (void)
void SDL_PumpEvents (void)
static void SDL_PumpEventsInternal (bool push_sentinel)
bool SDL_PushEvent (SDL_Event *event)
void SDL_QuitEvents (void)
static void SDL_QuitMainThreadCallbacks (void)
Uint32 SDL_RegisterEvents (int numevents)
void SDL_RemoveEventWatch (SDL_EventFilter filter, void *userdata)
static void SDL_RunMainThreadCallbacks (void)
bool SDL_RunOnMainThread (SDL_MainThreadCallback callback, void *userdata, bool wait_complete)
void SDL_SendAppEvent (SDL_EventType eventType)
void SDL_SendKeymapChangedEvent (void)
void SDL_SendLocaleChangedEvent (void)
void SDL_SendSystemThemeChangedEvent (void)
static void SDL_SendWakeupEvent (void)
void SDL_SetEventEnabled (Uint32 type, bool enabled)
void SDL_SetEventFilter (SDL_EventFilter filter, void *userdata)
bool SDL_StartEventLoop (void)
void SDL_StopEventLoop (void)
static void SDL_TransferSysWMMemoryToEvent (SDL_EventEntry *event)
static void SDL_TransferTemporaryMemoryFromEvent (SDL_EventEntry *event)
static void SDL_TransferTemporaryMemoryToEvent (SDL_EventEntry *event)
static void SDL_UnlinkTemporaryMemoryEntry (SDL_TemporaryMemoryState *state, SDL_TemporaryMemory *entry)
bool SDL_WaitEvent (SDL_Event *event)
bool SDL_WaitEventTimeout (SDL_Event *event, Sint32 timeoutMS)
static int SDL_WaitEventTimeout_Device (SDL_VideoDevice *_this, SDL_Window *wakeup_window, SDL_Event *event, Uint64 start, Sint64 timeoutNS)
bool SDL_WaitEventTimeoutNS (SDL_Event *event, Sint64 timeoutNS)
Variables
static SDL_DisabledEventBlock * SDL_disabled_events [256]
static SDL_EventWatchList SDL_event_watchers
static int SDL_EventLoggingVerbosity = 0
struct {
bool active
SDL_AtomicInt count
SDL_EventEntry * free
SDL_EventEntry * head
SDL_Mutex * lock
int max_events_seen
SDL_EventEntry * tail
} SDL_EventQ = { NULL, false, { 0 }, 0, NULL, NULL, NULL }
static Uint32 SDL_last_event_id = 0
static SDL_MainThreadCallbackEntry * SDL_main_callbacks_head
static SDL_Mutex * SDL_main_callbacks_lock
static SDL_MainThreadCallbackEntry * SDL_main_callbacks_tail
static SDL_AtomicInt SDL_sentinel_pending
static SDL_TLSID SDL_temporary_memory
static bool SDL_update_joysticks = true
static bool SDL_update_sensors = true
static SDL_AtomicInt SDL_userevents
Macro Definition Documentation
ENUMERATION_POLL_INTERVAL_NS
#define ENUMERATION_POLL_INTERVAL_NS (3 * SDL_NS_PER_SECOND)
Referenced by SDL_events_get_polling_interval().
EVENT_POLL_INTERVAL_NS
#define EVENT_POLL_INTERVAL_NS SDL_MS_TO_NS(1)
Referenced by SDL_events_get_polling_interval(), and SDL_WaitEventTimeoutNS().
PRINT_AUDIODEV_EVENT
#define PRINT_AUDIODEV_EVENT (event)
Value:
(void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u recording=%s)", (uint)event->adevice.timestamp, (uint)event->adevice.which, event->adevice.recording ? "true" : "false")
Referenced by SDL_GetEventDescription().
PRINT_CAMERADEV_EVENT
#define PRINT_CAMERADEV_EVENT (event)
Value:
(void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->cdevice.timestamp, (uint)event->cdevice.which)
Referenced by SDL_GetEventDescription().
PRINT_CBUTTON_EVENT
#define PRINT_CBUTTON_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d button=%u state=%s)", \
                       (uint)event->gbutton.timestamp, (int)event->gbutton.which,               \
                       (uint)event->gbutton.button, event->gbutton.down ? "pressed" : "released")
Referenced by SDL_GetEventDescription().
PRINT_CTOUCHPAD_EVENT
#define PRINT_CTOUCHPAD_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d touchpad=%d finger=%d x=%f y=%f pressure=%f)", \
                       (uint)event->gtouchpad.timestamp, (int)event->gtouchpad.which,                                    \
                       (int)event->gtouchpad.touchpad, (int)event->gtouchpad.finger,                                     \
                       event->gtouchpad.x, event->gtouchpad.y, event->gtouchpad.pressure)
Referenced by SDL_GetEventDescription().
PRINT_DROP_EVENT
#define PRINT_DROP_EVENT (event)
Value:
(void)SDL_snprintf(details, sizeof(details), " (data='%s' timestamp=%u windowid=%u x=%f y=%f)", event->drop.data, (uint)event->drop.timestamp, (uint)event->drop.windowID, event->drop.x, event->drop.y)
Referenced by SDL_GetEventDescription().
PRINT_FINGER_EVENT
#define PRINT_FINGER_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u touchid=%" SDL_PRIu64 " fingerid=%" SDL_PRIu64 " x=%f y=%f dx=%f dy=%f pressure=%f)", \
                       (uint)event->tfinger.timestamp, event->tfinger.touchID,                                                              \
                       event->tfinger.fingerID, event->tfinger.x, event->tfinger.y,                                                         \
                       event->tfinger.dx, event->tfinger.dy, event->tfinger.pressure)
Referenced by SDL_GetEventDescription().
PRINT_GAMEPADDEV_EVENT
#define PRINT_GAMEPADDEV_EVENT (event)
Value:
(void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d)", (uint)event->gdevice.timestamp, (int)event->gdevice.which)
Referenced by SDL_GetEventDescription().
PRINT_JBUTTON_EVENT
#define PRINT_JBUTTON_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d button=%u state=%s)", \
                       (uint)event->jbutton.timestamp, (int)event->jbutton.which,               \
                       (uint)event->jbutton.button, event->jbutton.down ? "pressed" : "released")
Referenced by SDL_GetEventDescription().
PRINT_JOYDEV_EVENT
#define PRINT_JOYDEV_EVENT (event)
Value:
(void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d)", (uint)event->jdevice.timestamp, (int)event->jdevice.which)
Referenced by SDL_GetEventDescription().
PRINT_KEY_EVENT
#define PRINT_KEY_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u state=%s repeat=%s scancode=%u keycode=%u mod=0x%x)", \
                       (uint)event->key.timestamp, (uint)event->key.windowID, (uint)event->key.which,                                       \
                       event->key.down ? "pressed" : "released",                                                            \
                       event->key.repeat ? "true" : "false",                                                                                \
                       (uint)event->key.scancode,                                                                                           \
                       (uint)event->key.key,                                                                                                \
                       (uint)event->key.mod)
Referenced by SDL_GetEventDescription().
PRINT_KEYDEV_EVENT
#define PRINT_KEYDEV_EVENT (event)
Value:
(void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->kdevice.timestamp, (uint)event->kdevice.which)
Referenced by SDL_GetEventDescription().
PRINT_MBUTTON_EVENT
#define PRINT_MBUTTON_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u button=%u state=%s clicks=%u x=%g y=%g)", \
                       (uint)event->button.timestamp, (uint)event->button.windowID,                                             \
                       (uint)event->button.which, (uint)event->button.button,                                                   \
                       event->button.down ? "pressed" : "released",                                                             \
                       (uint)event->button.clicks, event->button.x, event->button.y)
Referenced by SDL_GetEventDescription().
PRINT_MOUSEDEV_EVENT
#define PRINT_MOUSEDEV_EVENT (event)
Value:
(void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->mdevice.timestamp, (uint)event->mdevice.which)
Referenced by SDL_GetEventDescription().
PRINT_PBUTTON_EVENT
#define PRINT_PBUTTON_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g button=%u state=%s)", \
                       (uint)event->pbutton.timestamp, (uint)event->pbutton.windowID, (uint)event->pbutton.which, (uint)event->pbutton.pen_state, event->pbutton.x, event->pbutton.y, \
                       (uint)event->pbutton.button, event->pbutton.down ? "down" : "up");
Referenced by SDL_GetEventDescription().
PRINT_PPROXIMITY_EVENT
#define PRINT_PPROXIMITY_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u)", \
                       (uint)event->pproximity.timestamp, (uint)event->pproximity.windowID, (uint)event->pproximity.which);
Referenced by SDL_GetEventDescription().
PRINT_PTOUCH_EVENT
#define PRINT_PTOUCH_EVENT (event)
Value:
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g eraser=%s state=%s)", \
                       (uint)event->ptouch.timestamp, (uint)event->ptouch.windowID, (uint)event->ptouch.which, (uint)event->ptouch.pen_state, event->ptouch.x, event->ptouch.y, \
                       event->ptouch.eraser ? "yes" : "no", event->ptouch.down ? "down" : "up");
Referenced by SDL_GetEventDescription().
SDL2_SYSWMEVENT
#define SDL2_SYSWMEVENT 0x201
Referenced by SDL_TransferTemporaryMemoryToEvent().
SDL_DISPLAYEVENT_CASE
#define SDL_DISPLAYEVENT_CASE (x)
Value:
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name));   \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u display=%u event=%s data1=%d, data2=%d)", \
                           (uint)event->display.timestamp, (uint)event->display.displayID, name, (int)event->display.data1, (int)event->display.data2); \
        break
Referenced by SDL_GetEventDescription().
SDL_EVENT_CASE
#define SDL_EVENT_CASE (x)
Value:
    case x:               \
        SDL_strlcpy(name, #x, sizeof(name));
Referenced by SDL_GetEventDescription().
SDL_MAX_QUEUED_EVENTS
#define SDL_MAX_QUEUED_EVENTS 65535
Referenced by SDL_AddEvent().
SDL_RENDEREVENT_CASE
#define SDL_RENDEREVENT_CASE (x)
Value:
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name));   \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u event=%s windowid=%u)", \
                           (uint)event->display.timestamp, name, (uint)event->render.windowID); \
        break
Referenced by SDL_GetEventDescription().
SDL_WINDOWEVENT_CASE
#define SDL_WINDOWEVENT_CASE (x)
Value:
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name)); \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u event=%s data1=%d data2=%d)", \
                           (uint)event->window.timestamp, (uint)event->window.windowID, name, (int)event->window.data1, (int)event->window.data2); \
        break
Referenced by SDL_GetEventDescription().
uint
#define uint unsigned int
Referenced by put_queue(), put_utf8(), and SDL_GetEventDescription().
Typedef Documentation
SDL2_SysWMmsg
typedef struct SDL2_SysWMmsg SDL2_SysWMmsg
SDL2_version
typedef struct SDL2_version SDL2_version
SDL_EventEntry
typedef struct SDL_EventEntry SDL_EventEntry
SDL_MainThreadCallbackEntry
typedef struct SDL_MainThreadCallbackEntry SDL_MainThreadCallbackEntry
SDL_TemporaryMemory
typedef struct SDL_TemporaryMemory SDL_TemporaryMemory
SDL_TemporaryMemoryState
typedef struct SDL_TemporaryMemoryState SDL_TemporaryMemoryState
Enumeration Type Documentation
SDL2_SYSWM_TYPE
enum SDL2_SYSWM_TYPE
Enumerator
SDL2_SYSWM_UNKNOWN
{
  SDL2_SYSWM_UNKNOWN
} SDL2_SYSWM_TYPE;
SDL_MainThreadCallbackState
enum SDL_MainThreadCallbackState
Enumerator
SDL_MAIN_CALLBACK_WAITING
SDL_MAIN_CALLBACK_COMPLETE
SDL_MAIN_CALLBACK_CANCELED
{
    SDL_MAIN_CALLBACK_WAITING,
    SDL_MAIN_CALLBACK_COMPLETE,
    SDL_MAIN_CALLBACK_CANCELED,
} SDL_MainThreadCallbackState;
Function Documentation
SDL_AddEvent()
int SDL_AddEvent (SDL_Event * event) static
{
    SDL_EventEntry *entry;
    const int initial_count = SDL_GetAtomicInt(&SDL_EventQ.count);
    int final_count;
    if (initial_count >= SDL_MAX_QUEUED_EVENTS) {
        SDL_SetError("Event queue is full (%d events)", initial_count);
        return 0;
    }
    if (SDL_EventQ.free == NULL) {
        entry = (SDL_EventEntry *)SDL_malloc(sizeof(*entry));
        if (entry == NULL) {
            return 0;
        }
    } else {
        entry = SDL_EventQ.free;
        SDL_EventQ.free = entry->next;
    }
    if (SDL_EventLoggingVerbosity > 0) {
        SDL_LogEvent(event);
    }
    SDL_copyp(&entry->event, event);
    if (event->type == SDL_EVENT_POLL_SENTINEL) {
        SDL_AddAtomicInt(&SDL_sentinel_pending, 1);
    }
    entry->memory = NULL;
    SDL_TransferTemporaryMemoryToEvent(entry);
    if (SDL_EventQ.tail) {
        SDL_EventQ.tail->next = entry;
        entry->prev = SDL_EventQ.tail;
        SDL_EventQ.tail = entry;
        entry->next = NULL;
    } else {
        SDL_assert(!SDL_EventQ.head);
        SDL_EventQ.head = entry;
        SDL_EventQ.tail = entry;
        entry->prev = NULL;
        entry->next = NULL;
    }
    final_count = SDL_AddAtomicInt(&SDL_EventQ.count, 1) + 1;
    if (final_count > SDL_EventQ.max_events_seen) {
        SDL_EventQ.max_events_seen = final_count;
    }
    ++SDL_last_event_id;
    return 1;
}
References SDL_EventEntry::event, SDL_EventEntry::memory, SDL_EventEntry::next, NULL, SDL_EventEntry::prev, SDL_AddAtomicInt(), SDL_assert, SDL_copyp, SDL_EVENT_POLL_SENTINEL, SDL_EventLoggingVerbosity, SDL_EventQ, SDL_GetAtomicInt(), SDL_last_event_id, SDL_LogEvent(), SDL_malloc(), SDL_MAX_QUEUED_EVENTS, SDL_sentinel_pending, SDL_SetError(), and SDL_TransferTemporaryMemoryToEvent().
Referenced by SDL_PeepEventsInternal().
SDL_AddEventWatch()
bool SDL_AddEventWatch (SDL_EventFilter filter, void * userdata)
Add a callback to be triggered when an event is added to the event queue.
filter will be called when an event happens, and its return value is ignored.
WARNING: Be very careful of what you do in the event filter function, as it may run in a different thread!
If the quit event is generated by a signal (e.g. SIGINT), it will bypass the internal queue and be delivered to the watch callback immediately, and arrive at the next event poll.
Note: the callback is called for events posted by the user through SDL_PushEvent(), but not for disabled events, nor for events by a filter callback set with SDL_SetEventFilter(), nor for events posted by the user through SDL_PeepEvents().
Parameters
filter an SDL_EventFilter function to call when an event happens.
userdata a pointer that is passed to filter.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveEventWatch
SDL_SetEventFilter
{
    return SDL_AddEventWatchList(&SDL_event_watchers, filter, userdata);
}
References SDL_AddEventWatchList(), SDL_event_watchers, and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_EnterAppMainCallbacks(), SDL_InitGamepads(), and SDL_InitMainCallbacks().
SDL_AllocateTemporaryMemory()
void * SDL_AllocateTemporaryMemory (size_t size)
{
    return SDL_FreeLater(SDL_malloc(size));
}
References SDL_FreeLater(), and SDL_malloc().
Referenced by CreateCandidatesForEvent(), SDL_CopyClipboardMimeTypes(), and SDL_TransferSysWMMemoryToEvent().
SDL_AutoUpdateJoysticksChanged()
void SDLCALL SDL_AutoUpdateJoysticksChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    SDL_update_joysticks = SDL_GetStringBoolean(hint, true);
}
References SDL_GetStringBoolean(), SDL_update_joysticks, and SDLCALL.
Referenced by SDL_InitEvents(), and SDL_QuitEvents().
SDL_AutoUpdateSensorsChanged()
void SDLCALL SDL_AutoUpdateSensorsChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    SDL_update_sensors = SDL_GetStringBoolean(hint, true);
}
References SDL_GetStringBoolean(), SDL_update_sensors, and SDLCALL.
Referenced by SDL_InitEvents(), and SDL_QuitEvents().
SDL_CallEventWatchers()
bool SDL_CallEventWatchers (SDL_Event * event) static
{
    if (event->common.type == SDL_EVENT_POLL_SENTINEL) {
        return true;
    }
    return SDL_DispatchEventWatchList(&SDL_event_watchers, event);
}
References SDL_DispatchEventWatchList(), SDL_EVENT_POLL_SENTINEL, and SDL_event_watchers.
Referenced by SDL_PushEvent(), and SDL_SendAppEvent().
SDL_ClaimTemporaryMemory()
void * SDL_ClaimTemporaryMemory (const void * mem)
{
    SDL_TemporaryMemoryState *state;
    state = SDL_GetTemporaryMemoryState(false);
    if (state && mem) {
        SDL_TemporaryMemory *entry = SDL_GetTemporaryMemoryEntry(state, mem);
        if (entry) {
            SDL_UnlinkTemporaryMemoryEntry(state, entry);
            SDL_FreeTemporaryMemoryEntry(state, entry, false);
            return (void *)mem;
        }
    }
    return NULL;
}
References NULL, SDL_FreeTemporaryMemoryEntry(), SDL_GetTemporaryMemoryEntry(), SDL_GetTemporaryMemoryState(), and SDL_UnlinkTemporaryMemoryEntry().
SDL_CleanupTemporaryMemory()
void SDL_CleanupTemporaryMemory (void * data) static
{
    SDL_TemporaryMemoryState *state = (SDL_TemporaryMemoryState *)data;
    SDL_FreeTemporaryMemory();
    SDL_free(state);
}
References SDL_free(), and SDL_FreeTemporaryMemory().
Referenced by SDL_GetTemporaryMemoryState().
SDL_COMPILE_TIME_ASSERT()
SDL_COMPILE_TIME_ASSERT (SDL_Event_type , sizeof(Uint32) = =sizeof(SDL_EventType))
SDL_CreateMainThreadCallback()
SDL_MainThreadCallbackEntry * SDL_CreateMainThreadCallback (SDL_MainThreadCallback callback, void * userdata, bool wait_complete) static
{
    SDL_MainThreadCallbackEntry *entry = (SDL_MainThreadCallbackEntry *)SDL_malloc(sizeof(*entry));
    if (!entry) {
        return NULL;
    }
    entry->callback = callback;
    entry->userdata = userdata;
    SDL_SetAtomicInt(&entry->state, SDL_MAIN_CALLBACK_WAITING);
    if (wait_complete) {
        entry->semaphore = SDL_CreateSemaphore(0);
        if (!entry->semaphore) {
            SDL_free(entry);
            return NULL;
        }
    } else {
        entry->semaphore = NULL;
    }
    entry->next = NULL;
    return entry;
}
References SDL_MainThreadCallbackEntry::callback, SDL_MainThreadCallbackEntry::next, NULL, SDL_CreateSemaphore(), SDL_free(), SDL_MAIN_CALLBACK_WAITING, SDL_malloc(), SDL_SetAtomicInt(), SDL_MainThreadCallbackEntry::semaphore, SDL_MainThreadCallbackEntry::state, and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_RunOnMainThread().
SDL_CreateTemporaryString()
const char * SDL_CreateTemporaryString (const char * string)
{
    if (string) {
        return (const char *)SDL_FreeLater(SDL_strdup(string));
    }
    return NULL;
}
References NULL, SDL_FreeLater(), and SDL_strdup().
Referenced by SDL_SendDrop(), SDL_SendEditingText(), and SDL_SendKeyboardText().
SDL_CutEvent()
void SDL_CutEvent (SDL_EventEntry * entry) static
{
    SDL_TransferTemporaryMemoryFromEvent(entry);
    if (entry->prev) {
        entry->prev->next = entry->next;
    }
    if (entry->next) {
        entry->next->prev = entry->prev;
    }
    if (entry == SDL_EventQ.head) {
        SDL_assert(entry->prev == NULL);
        SDL_EventQ.head = entry->next;
    }
    if (entry == SDL_EventQ.tail) {
        SDL_assert(entry->next == NULL);
        SDL_EventQ.tail = entry->prev;
    }
    if (entry->event.type == SDL_EVENT_POLL_SENTINEL) {
        SDL_AddAtomicInt(&SDL_sentinel_pending, -1);
    }
    entry->next = SDL_EventQ.free;
    SDL_EventQ.free = entry;
    SDL_assert(SDL_GetAtomicInt(&SDL_EventQ.count) > 0);
    SDL_AddAtomicInt(&SDL_EventQ.count, -1);
}
References SDL_EventEntry::event, SDL_EventEntry::next, NULL, SDL_EventEntry::prev, SDL_AddAtomicInt(), SDL_assert, SDL_EVENT_POLL_SENTINEL, SDL_EventQ, SDL_GetAtomicInt(), SDL_sentinel_pending, SDL_TransferTemporaryMemoryFromEvent(), and SDL_Event::type.
Referenced by SDL_FilterEvents(), SDL_FlushEvents(), SDL_PeepEventsInternal(), and SDL_SetEventFilter().
SDL_DestroyMainThreadCallback()
void SDL_DestroyMainThreadCallback (SDL_MainThreadCallbackEntry * entry) static
{
    if (entry->semaphore) {
        SDL_DestroySemaphore(entry->semaphore);
    }
    SDL_free(entry);
}
References SDL_DestroySemaphore(), SDL_free(), and SDL_MainThreadCallbackEntry::semaphore.
Referenced by SDL_QuitMainThreadCallbacks(), SDL_RunMainThreadCallbacks(), and SDL_RunOnMainThread().
SDL_EventEnabled()
bool SDL_EventEnabled (Uint32 type)
Query the state of processing events by type.
Parameters
type the type of event; see SDL_EventType for details.
Returns
true if the event is being processed, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetEventEnabled
{
    Uint8 hi = ((type >> 8) & 0xff);
    Uint8 lo = (type & 0xff);
    if (SDL_disabled_events[hi] &&
        (SDL_disabled_events[hi]->bits[lo / 32] & (1U << (lo & 31)))) {
        return false;
    } else {
        return true;
    }
}
References SDL_disabled_events.
Referenced by IsAcceptingDragAndDrop(), SDL_AddPenDevice(), SDL_GamepadEventsEnabled(), SDL_GamepadEventWatcher(), SDL_JoystickEventsEnabled(), SDL_PrivateJoystickAdded(), SDL_PrivateJoystickRemoved(), SDL_PrivateSendMouseButton(), SDL_PrivateSendMouseMotion(), SDL_PumpEventsInternal(), SDL_RemovePenDevice(), SDL_SendAppEvent(), SDL_SendClipboardUpdate(), SDL_SendDisplayEvent(), SDL_SendDrop(), SDL_SendEditingText(), SDL_SendEditingTextCandidates(), SDL_SendGamepadAxis(), SDL_SendGamepadButton(), SDL_SendJoystickAxis(), SDL_SendJoystickBall(), SDL_SendJoystickButton(), SDL_SendJoystickHat(), SDL_SendJoystickPowerInfo(), SDL_SendJoystickSensor(), SDL_SendJoystickTouchpad(), SDL_SendKeyboardKeyInternal(), SDL_SendKeyboardText(), SDL_SendMouseWheel(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SendSensorUpdate(), SDL_SendTouch(), SDL_SendTouchMotion(), SDL_SendWindowEvent(), SDL_UpdateAudio(), SDL_UpdateCamera(), and SDL_UpdateJoysticks().
SDL_EventLoggingChanged()
void SDLCALL SDL_EventLoggingChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    SDL_EventLoggingVerbosity = (hint && *hint) ? SDL_clamp(SDL_atoi(hint), 0, 3) : 0;
}
References SDL_atoi(), SDL_clamp, SDL_EventLoggingVerbosity, and SDLCALL.
Referenced by SDL_InitEvents(), and SDL_QuitEvents().
SDL_events_get_polling_interval()
Sint64 SDL_events_get_polling_interval (void) static
{
    Sint64 poll_intervalNS = SDL_MAX_SINT64;
#ifndef SDL_JOYSTICK_DISABLED
    if (SDL_WasInit(SDL_INIT_JOYSTICK) && SDL_update_joysticks) {
        if (SDL_JoysticksOpened()) {
            // If we have joysticks open, we need to poll rapidly for events
            poll_intervalNS = SDL_min(poll_intervalNS, EVENT_POLL_INTERVAL_NS);
        } else {
            // If not, just poll every few seconds to enumerate new joysticks
            poll_intervalNS = SDL_min(poll_intervalNS, ENUMERATION_POLL_INTERVAL_NS);
        }
    }
#endif
#ifndef SDL_SENSOR_DISABLED
    if (SDL_WasInit(SDL_INIT_SENSOR) && SDL_update_sensors && SDL_SensorsOpened()) {
        // If we have sensors open, we need to poll rapidly for events
        poll_intervalNS = SDL_min(poll_intervalNS, EVENT_POLL_INTERVAL_NS);
    }
#endif
    return poll_intervalNS;
}
References ENUMERATION_POLL_INTERVAL_NS, EVENT_POLL_INTERVAL_NS, SDL_INIT_JOYSTICK, SDL_INIT_SENSOR, SDL_JoysticksOpened(), SDL_MAX_SINT64, SDL_min, SDL_SensorsOpened(), SDL_update_joysticks, SDL_update_sensors, and SDL_WasInit().
Referenced by SDL_WaitEventTimeout_Device().
SDL_FilterEvents()
void SDL_FilterEvents (SDL_EventFilter filter, void * userdata)
Run a specific filter function on the current event queue, removing any events for which the filter returns false.
See SDL_SetEventFilter() for more information. Unlike SDL_SetEventFilter(), this function does not change the filter permanently, it only uses the supplied filter until this function returns.
Parameters
filter the SDL_EventFilter function to call when an event happens.
userdata a pointer that is passed to filter.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEventFilter
SDL_SetEventFilter
{
    SDL_LockMutex(SDL_EventQ.lock);
    {
        SDL_EventEntry *entry, *next;
        for (entry = SDL_EventQ.head; entry; entry = next) {
            next = entry->next;
            if (!filter(userdata, &entry->event)) {
                SDL_CutEvent(entry);
            }
        }
    }
    SDL_UnlockMutex(SDL_EventQ.lock);
}
References SDL_EventEntry::event, SDL_EventEntry::next, SDL_MainThreadCallbackEntry::next, SDL_CutEvent(), SDL_EventQ, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_SendWindowEvent().
SDL_find_active_window()
SDL_Window * SDL_find_active_window (SDL_VideoDevice * _this) static
{
    SDL_Window *window;
    for (window = _this->windows; window; window = window->next) {
        if (!window->is_destroying) {
            return window;
        }
    }
    return NULL;
}
References _this, and NULL.
Referenced by SDL_WaitEventTimeoutNS().
SDL_FlushEvent()
void SDL_FlushEvent (Uint32 type)
Clear events of a specific type from the event queue.
This will unconditionally remove any events from the queue that match type. If you need to remove a range of event types, use SDL_FlushEvents() instead.
It's also normal to just ignore events you don't care about in your event loop without calling this function.
This function only affects currently queued events. If you want to make sure that all pending OS events are flushed, you can call SDL_PumpEvents() on the main thread immediately before the flush call.
If you have user events with custom data that needs to be freed, you should use SDL_PeepEvents() to remove and clean up those events before calling this function.
Parameters
type the type of event to be cleared; see SDL_EventType for details.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_FlushEvents
{
    SDL_FlushEvents(type, type);
}
References SDL_FlushEvents().
Referenced by SDL_SetEventEnabled(), and SDL_SetRelativeMouseMode().
SDL_FlushEvents()
void SDL_FlushEvents (Uint32 minType, Uint32 maxType)
Clear events of a range of types from the event queue.
This will unconditionally remove any events from the queue that are in the range of minType to maxType, inclusive. If you need to remove a single event type, use SDL_FlushEvent() instead.
It's also normal to just ignore events you don't care about in your event loop without calling this function.
This function only affects currently queued events. If you want to make sure that all pending OS events are flushed, you can call SDL_PumpEvents() on the main thread immediately before the flush call.
Parameters
minType the low end of event type to be cleared, inclusive; see SDL_EventType for details.
maxType the high end of event type to be cleared, inclusive; see SDL_EventType for details.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_FlushEvent
{
    SDL_EventEntry *entry, *next;
    Uint32 type;
    // Make sure the events are current
#if 0
    /* Actually, we can't do this since we might be flushing while processing
       a resize event, and calling this might trigger further resize events.
    */
    SDL_PumpEvents();
#endif
    // Lock the event queue
    SDL_LockMutex(SDL_EventQ.lock);
    {
        // Don't look after we've quit
        if (!SDL_EventQ.active) {
            SDL_UnlockMutex(SDL_EventQ.lock);
            return;
        }
        for (entry = SDL_EventQ.head; entry; entry = next) {
            next = entry->next;
            type = entry->event.type;
            if (minType <= type && type <= maxType) {
                SDL_CutEvent(entry);
            }
        }
    }
    SDL_UnlockMutex(SDL_EventQ.lock);
}
References SDL_EventEntry::event, SDL_EventEntry::next, SDL_CutEvent(), SDL_EventQ, SDL_LockMutex(), SDL_PumpEvents(), SDL_UnlockMutex(), and SDL_Event::type.
Referenced by SDL_FlushEvent().
SDL_FreeLater()
void * SDL_FreeLater (void * memory) static
{
    SDL_TemporaryMemoryState *state;
    if (memory == NULL) {
        return NULL;
    }
    // Make sure we're not adding this to the list twice
    //SDL_assert(!SDL_ClaimTemporaryMemory(memory));
    state = SDL_GetTemporaryMemoryState(true);
    if (!state) {
        return memory;  // this is now a leak, but you probably have bigger problems if malloc failed.
    }
    SDL_TemporaryMemory *entry = (SDL_TemporaryMemory *)SDL_malloc(sizeof(*entry));
    if (!entry) {
        return memory;  // this is now a leak, but you probably have bigger problems if malloc failed. We could probably pool up and reuse entries, though.
    }
    entry->memory = memory;
    SDL_LinkTemporaryMemoryEntry(state, entry);
    return memory;
}
References SDL_EventEntry::memory, SDL_TemporaryMemory::memory, NULL, SDL_GetTemporaryMemoryState(), SDL_LinkTemporaryMemoryEntry(), and SDL_malloc().
Referenced by SDL_AllocateTemporaryMemory(), and SDL_CreateTemporaryString().
SDL_FreeTemporaryMemory()
void SDL_FreeTemporaryMemory (void)
{
    SDL_TemporaryMemoryState *state;
    state = SDL_GetTemporaryMemoryState(false);
    if (!state) {
        return;
    }
    while (state->head) {
        SDL_TemporaryMemory *entry = state->head;
        SDL_UnlinkTemporaryMemoryEntry(state, entry);
        SDL_FreeTemporaryMemoryEntry(state, entry, true);
    }
}
References SDL_TemporaryMemoryState::head, SDL_FreeTemporaryMemoryEntry(), SDL_GetTemporaryMemoryState(), and SDL_UnlinkTemporaryMemoryEntry().
Referenced by SDL_CleanupTemporaryMemory(), and SDL_PumpEventsInternal().
SDL_FreeTemporaryMemoryEntry()
void SDL_FreeTemporaryMemoryEntry (SDL_TemporaryMemoryState * state, SDL_TemporaryMemory * entry, bool free_data) static
{
    if (free_data) {
        SDL_free(entry->memory);
    }
    SDL_free(entry);
}
References SDL_TemporaryMemory::memory, and SDL_free().
Referenced by SDL_ClaimTemporaryMemory(), and SDL_FreeTemporaryMemory().
SDL_GetEventDescription()
int SDL_GetEventDescription (const SDL_Event * event, char * buf, int buflen)
Generate a human-readable description of an event.
This will fill buf with a null-terminated string that might look something like this:
SDL_EVENT_MOUSE_MOTION (timestamp=1140256324 windowid=2 which=0 state=0 x=492.99 y=139.09 xrel=52 yrel=6)
The exact format of the string is not guaranteed; it is intended for logging purposes, to be read by a human, and not parsed by a computer.
The returned value follows the same rules as SDL_snprintf(): buf will always be NULL-terminated (unless buflen is zero), and will be truncated if buflen is too small. The return code is the number of bytes needed for the complete string, not counting the NULL-terminator, whether the string was truncated or not. Unlike SDL_snprintf(), though, this function never returns -1.
Parameters
event an event to describe. May be NULL.
buf the buffer to fill with the description string. May be NULL.
buflen the maximum bytes that can be written to buf.
Returns
number of bytes needed for the full string, not counting the null-terminator byte.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (!event) {
        return SDL_snprintf(buf, buflen, "(null)");
    }
    static const char *pen_axisnames[] = { "PRESSURE", "XTILT", "YTILT", "DISTANCE", "ROTATION", "SLIDER", "TANGENTIAL_PRESSURE" };
    SDL_COMPILE_TIME_ASSERT(pen_axisnames_array_matches, SDL_arraysize(pen_axisnames) == SDL_PEN_AXIS_COUNT);
    char name[64];
    char details[128];
// this is to make (void)SDL_snprintf() calls cleaner.
#define uint unsigned int
    name[0] = '\0';
    details[0] = '\0';
    // !!! FIXME: This code is kinda ugly, sorry.
    if ((event->type >= SDL_EVENT_USER) && (event->type <= SDL_EVENT_LAST)) {
        char plusstr[16];
        SDL_strlcpy(name, "SDL_EVENT_USER", sizeof(name));
        if (event->type > SDL_EVENT_USER) {
            (void)SDL_snprintf(plusstr, sizeof(plusstr), "+%u", ((uint)event->type) - SDL_EVENT_USER);
        } else {
            plusstr[0] = '\0';
        }
        (void)SDL_snprintf(details, sizeof(details), "%s (timestamp=%u windowid=%u code=%d data1=%p data2=%p)",
                           plusstr, (uint)event->user.timestamp, (uint)event->user.windowID,
                           (int)event->user.code, event->user.data1, event->user.data2);
    }
    switch (event->type) {
#define SDL_EVENT_CASE(x) \
    case x:               \
        SDL_strlcpy(name, #x, sizeof(name));
        SDL_EVENT_CASE(SDL_EVENT_FIRST)
        SDL_strlcpy(details, " (THIS IS PROBABLY A BUG!)", sizeof(details));
        break;
        SDL_EVENT_CASE(SDL_EVENT_QUIT)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u)", (uint)event->quit.timestamp);
        break;
        SDL_EVENT_CASE(SDL_EVENT_TERMINATING)
        break;
        SDL_EVENT_CASE(SDL_EVENT_LOW_MEMORY)
        break;
        SDL_EVENT_CASE(SDL_EVENT_WILL_ENTER_BACKGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_DID_ENTER_BACKGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_WILL_ENTER_FOREGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_DID_ENTER_FOREGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_LOCALE_CHANGED)
        break;
        SDL_EVENT_CASE(SDL_EVENT_SYSTEM_THEME_CHANGED)
        break;
        SDL_EVENT_CASE(SDL_EVENT_KEYMAP_CHANGED)
        break;
        SDL_EVENT_CASE(SDL_EVENT_CLIPBOARD_UPDATE)
        break;
#define SDL_RENDEREVENT_CASE(x)                \
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name));   \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u event=%s windowid=%u)", \
                           (uint)event->display.timestamp, name, (uint)event->render.windowID); \
        break
        SDL_RENDEREVENT_CASE(SDL_EVENT_RENDER_TARGETS_RESET);
        SDL_RENDEREVENT_CASE(SDL_EVENT_RENDER_DEVICE_RESET);
        SDL_RENDEREVENT_CASE(SDL_EVENT_RENDER_DEVICE_LOST);
#define SDL_DISPLAYEVENT_CASE(x)               \
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name));   \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u display=%u event=%s data1=%d, data2=%d)", \
                           (uint)event->display.timestamp, (uint)event->display.displayID, name, (int)event->display.data1, (int)event->display.data2); \
        break
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_ORIENTATION);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_ADDED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_REMOVED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_MOVED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED);
#undef SDL_DISPLAYEVENT_CASE
#define SDL_WINDOWEVENT_CASE(x)                \
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name)); \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u event=%s data1=%d data2=%d)", \
                           (uint)event->window.timestamp, (uint)event->window.windowID, name, (int)event->window.data1, (int)event->window.data2); \
        break
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_SHOWN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_HIDDEN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_EXPOSED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MOVED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_RESIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_METAL_VIEW_RESIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_SAFE_AREA_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MINIMIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MAXIMIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_RESTORED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MOUSE_ENTER);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MOUSE_LEAVE);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_FOCUS_GAINED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_FOCUS_LOST);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_CLOSE_REQUESTED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_HIT_TEST);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_ICCPROF_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_DISPLAY_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_OCCLUDED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_ENTER_FULLSCREEN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_LEAVE_FULLSCREEN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_DESTROYED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_HDR_STATE_CHANGED);
#undef SDL_WINDOWEVENT_CASE
#define PRINT_KEYDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->kdevice.timestamp, (uint)event->kdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_KEYBOARD_ADDED)
        PRINT_KEYDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_KEYBOARD_REMOVED)
        PRINT_KEYDEV_EVENT(event);
        break;
#undef PRINT_KEYDEV_EVENT
#define PRINT_KEY_EVENT(event)                                                                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u state=%s repeat=%s scancode=%u keycode=%u mod=0x%x)", \
                       (uint)event->key.timestamp, (uint)event->key.windowID, (uint)event->key.which,                                       \
                       event->key.down ? "pressed" : "released",                                                            \
                       event->key.repeat ? "true" : "false",                                                                                \
                       (uint)event->key.scancode,                                                                                           \
                       (uint)event->key.key,                                                                                                \
                       (uint)event->key.mod)
        SDL_EVENT_CASE(SDL_EVENT_KEY_DOWN)
        PRINT_KEY_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_KEY_UP)
        PRINT_KEY_EVENT(event);
        break;
#undef PRINT_KEY_EVENT
        SDL_EVENT_CASE(SDL_EVENT_TEXT_EDITING)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u text='%s' start=%d length=%d)",
                           (uint)event->edit.timestamp, (uint)event->edit.windowID,
                           event->edit.text, (int)event->edit.start, (int)event->edit.length);
        break;
        SDL_EVENT_CASE(SDL_EVENT_TEXT_EDITING_CANDIDATES)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u num_candidates=%d selected_candidate=%d)",
                           (uint)event->edit_candidates.timestamp, (uint)event->edit_candidates.windowID,
                           (int)event->edit_candidates.num_candidates, (int)event->edit_candidates.selected_candidate);
        break;
        SDL_EVENT_CASE(SDL_EVENT_TEXT_INPUT)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u text='%s')", (uint)event->text.timestamp, (uint)event->text.windowID, event->text.text);
        break;
#define PRINT_MOUSEDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->mdevice.timestamp, (uint)event->mdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_ADDED)
        PRINT_MOUSEDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_REMOVED)
        PRINT_MOUSEDEV_EVENT(event);
        break;
#undef PRINT_MOUSEDEV_EVENT
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u state=%u x=%g y=%g xrel=%g yrel=%g)",
                           (uint)event->motion.timestamp, (uint)event->motion.windowID,
                           (uint)event->motion.which, (uint)event->motion.state,
                           event->motion.x, event->motion.y,
                           event->motion.xrel, event->motion.yrel);
        break;
#define PRINT_MBUTTON_EVENT(event)                                                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u button=%u state=%s clicks=%u x=%g y=%g)", \
                       (uint)event->button.timestamp, (uint)event->button.windowID,                                             \
                       (uint)event->button.which, (uint)event->button.button,                                                   \
                       event->button.down ? "pressed" : "released",                                                             \
                       (uint)event->button.clicks, event->button.x, event->button.y)
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_BUTTON_DOWN)
        PRINT_MBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_BUTTON_UP)
        PRINT_MBUTTON_EVENT(event);
        break;
#undef PRINT_MBUTTON_EVENT
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_WHEEL)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u x=%g y=%g integer_x=%d integer_y=%d direction=%s)",
                           (uint)event->wheel.timestamp, (uint)event->wheel.windowID,
                           (uint)event->wheel.which, event->wheel.x, event->wheel.y,
                           (int)event->wheel.integer_x, (int)event->wheel.integer_y,
                           event->wheel.direction == SDL_MOUSEWHEEL_NORMAL ? "normal" : "flipped");
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_AXIS_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d axis=%u value=%d)",
                           (uint)event->jaxis.timestamp, (int)event->jaxis.which,
                           (uint)event->jaxis.axis, (int)event->jaxis.value);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BALL_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d ball=%u xrel=%d yrel=%d)",
                           (uint)event->jball.timestamp, (int)event->jball.which,
                           (uint)event->jball.ball, (int)event->jball.xrel, (int)event->jball.yrel);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_HAT_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d hat=%u value=%u)",
                           (uint)event->jhat.timestamp, (int)event->jhat.which,
                           (uint)event->jhat.hat, (uint)event->jhat.value);
        break;
#define PRINT_JBUTTON_EVENT(event)                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d button=%u state=%s)", \
                       (uint)event->jbutton.timestamp, (int)event->jbutton.which,               \
                       (uint)event->jbutton.button, event->jbutton.down ? "pressed" : "released")
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BUTTON_DOWN)
        PRINT_JBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BUTTON_UP)
        PRINT_JBUTTON_EVENT(event);
        break;
#undef PRINT_JBUTTON_EVENT
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BATTERY_UPDATED)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d state=%u percent=%d)",
                           (uint)event->jbattery.timestamp, (int)event->jbattery.which,
                           event->jbattery.state, event->jbattery.percent);
        break;
#define PRINT_JOYDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d)", (uint)event->jdevice.timestamp, (int)event->jdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_ADDED)
        PRINT_JOYDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_REMOVED)
        PRINT_JOYDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_UPDATE_COMPLETE)
        PRINT_JOYDEV_EVENT(event);
        break;
#undef PRINT_JOYDEV_EVENT
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_AXIS_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d axis=%u value=%d)",
                           (uint)event->gaxis.timestamp, (int)event->gaxis.which,
                           (uint)event->gaxis.axis, (int)event->gaxis.value);
        break;
#define PRINT_CBUTTON_EVENT(event)                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d button=%u state=%s)", \
                       (uint)event->gbutton.timestamp, (int)event->gbutton.which,               \
                       (uint)event->gbutton.button, event->gbutton.down ? "pressed" : "released")
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_BUTTON_DOWN)
        PRINT_CBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_BUTTON_UP)
        PRINT_CBUTTON_EVENT(event);
        break;
#undef PRINT_CBUTTON_EVENT
#define PRINT_GAMEPADDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d)", (uint)event->gdevice.timestamp, (int)event->gdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_ADDED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_REMOVED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_REMAPPED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_UPDATE_COMPLETE)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
#undef PRINT_GAMEPADDEV_EVENT
#define PRINT_CTOUCHPAD_EVENT(event)                                                                                     \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d touchpad=%d finger=%d x=%f y=%f pressure=%f)", \
                       (uint)event->gtouchpad.timestamp, (int)event->gtouchpad.which,                                    \
                       (int)event->gtouchpad.touchpad, (int)event->gtouchpad.finger,                                     \
                       event->gtouchpad.x, event->gtouchpad.y, event->gtouchpad.pressure)
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN)
        PRINT_CTOUCHPAD_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_TOUCHPAD_UP)
        PRINT_CTOUCHPAD_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION)
        PRINT_CTOUCHPAD_EVENT(event);
        break;
#undef PRINT_CTOUCHPAD_EVENT
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_SENSOR_UPDATE)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d sensor=%d data[0]=%f data[1]=%f data[2]=%f)",
                           (uint)event->gsensor.timestamp, (int)event->gsensor.which, (int)event->gsensor.sensor,
                           event->gsensor.data[0], event->gsensor.data[1], event->gsensor.data[2]);
        break;
#define PRINT_FINGER_EVENT(event)                                                                                                                      \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u touchid=%" SDL_PRIu64 " fingerid=%" SDL_PRIu64 " x=%f y=%f dx=%f dy=%f pressure=%f)", \
                       (uint)event->tfinger.timestamp, event->tfinger.touchID,                                                              \
                       event->tfinger.fingerID, event->tfinger.x, event->tfinger.y,                                                         \
                       event->tfinger.dx, event->tfinger.dy, event->tfinger.pressure)
        SDL_EVENT_CASE(SDL_EVENT_FINGER_DOWN)
        PRINT_FINGER_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_FINGER_UP)
        PRINT_FINGER_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_FINGER_CANCELED)
        PRINT_FINGER_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_FINGER_MOTION)
        PRINT_FINGER_EVENT(event);
        break;
#undef PRINT_FINGER_EVENT
#define PRINT_PTOUCH_EVENT(event)                                                                             \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g eraser=%s state=%s)", \
                       (uint)event->ptouch.timestamp, (uint)event->ptouch.windowID, (uint)event->ptouch.which, (uint)event->ptouch.pen_state, event->ptouch.x, event->ptouch.y, \
                       event->ptouch.eraser ? "yes" : "no", event->ptouch.down ? "down" : "up");
        SDL_EVENT_CASE(SDL_EVENT_PEN_DOWN)
        PRINT_PTOUCH_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_UP)
        PRINT_PTOUCH_EVENT(event);
        break;
#undef PRINT_PTOUCH_EVENT
#define PRINT_PPROXIMITY_EVENT(event)                                                                             \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u)", \
                       (uint)event->pproximity.timestamp, (uint)event->pproximity.windowID, (uint)event->pproximity.which);
        SDL_EVENT_CASE(SDL_EVENT_PEN_PROXIMITY_IN)
        PRINT_PPROXIMITY_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_PROXIMITY_OUT)
        PRINT_PPROXIMITY_EVENT(event);
        break;
#undef PRINT_PPROXIMITY_EVENT
        SDL_EVENT_CASE(SDL_EVENT_PEN_AXIS)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g axis=%s value=%g)",
                           (uint)event->paxis.timestamp, (uint)event->paxis.windowID, (uint)event->paxis.which, (uint)event->paxis.pen_state, event->paxis.x, event->paxis.y,
                           ((((int) event->paxis.axis) >= 0) && (event->paxis.axis < SDL_arraysize(pen_axisnames))) ? pen_axisnames[event->paxis.axis] : "[UNKNOWN]", event->paxis.value);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g)",
                           (uint)event->pmotion.timestamp, (uint)event->pmotion.windowID, (uint)event->pmotion.which, (uint)event->pmotion.pen_state, event->pmotion.x, event->pmotion.y);
        break;
#define PRINT_PBUTTON_EVENT(event)                                                                                                               \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g button=%u state=%s)", \
                       (uint)event->pbutton.timestamp, (uint)event->pbutton.windowID, (uint)event->pbutton.which, (uint)event->pbutton.pen_state, event->pbutton.x, event->pbutton.y, \
                       (uint)event->pbutton.button, event->pbutton.down ? "down" : "up");
        SDL_EVENT_CASE(SDL_EVENT_PEN_BUTTON_DOWN)
        PRINT_PBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_BUTTON_UP)
        PRINT_PBUTTON_EVENT(event);
        break;
#undef PRINT_PBUTTON_EVENT
#define PRINT_DROP_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (data='%s' timestamp=%u windowid=%u x=%f y=%f)", event->drop.data, (uint)event->drop.timestamp, (uint)event->drop.windowID, event->drop.x, event->drop.y)
        SDL_EVENT_CASE(SDL_EVENT_DROP_FILE)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_TEXT)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_BEGIN)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_COMPLETE)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_POSITION)
        PRINT_DROP_EVENT(event);
        break;
#undef PRINT_DROP_EVENT
#define PRINT_AUDIODEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u recording=%s)", (uint)event->adevice.timestamp, (uint)event->adevice.which, event->adevice.recording ? "true" : "false")
        SDL_EVENT_CASE(SDL_EVENT_AUDIO_DEVICE_ADDED)
        PRINT_AUDIODEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_AUDIO_DEVICE_REMOVED)
        PRINT_AUDIODEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED)
        PRINT_AUDIODEV_EVENT(event);
        break;
#undef PRINT_AUDIODEV_EVENT
#define PRINT_CAMERADEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->cdevice.timestamp, (uint)event->cdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_ADDED)
        PRINT_CAMERADEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_REMOVED)
        PRINT_CAMERADEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_APPROVED)
        PRINT_CAMERADEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_DENIED)
        PRINT_CAMERADEV_EVENT(event);
        break;
#undef PRINT_CAMERADEV_EVENT
        SDL_EVENT_CASE(SDL_EVENT_SENSOR_UPDATE)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d data[0]=%f data[1]=%f data[2]=%f data[3]=%f data[4]=%f data[5]=%f)",
                           (uint)event->sensor.timestamp, (int)event->sensor.which,
                           event->sensor.data[0], event->sensor.data[1], event->sensor.data[2],
                           event->sensor.data[3], event->sensor.data[4], event->sensor.data[5]);
        break;
#undef SDL_EVENT_CASE
    case SDL_EVENT_POLL_SENTINEL:
        // No logging necessary for this one
        break;
    default:
        if (!name[0]) {
            if (event->type >= SDL_EVENT_USER) {
                SDL_strlcpy(name, "USER", sizeof(name));
            } else {
                SDL_strlcpy(name, "UNKNOWN", sizeof(name));
            }
            (void)SDL_snprintf(details, sizeof(details), " 0x%x", (uint)event->type);
        }
        break;
    }
#undef uint
    int retval = 0;
    if (name[0]) {
        retval = SDL_snprintf(buf, buflen, "%s%s", name, details);
    } else if (buf && (buflen > 0)) {
        *buf = '\0';
    }
    return retval;
}
References PRINT_AUDIODEV_EVENT, PRINT_CAMERADEV_EVENT, PRINT_CBUTTON_EVENT, PRINT_CTOUCHPAD_EVENT, PRINT_DROP_EVENT, PRINT_FINGER_EVENT, PRINT_GAMEPADDEV_EVENT, PRINT_JBUTTON_EVENT, PRINT_JOYDEV_EVENT, PRINT_KEY_EVENT, PRINT_KEYDEV_EVENT, PRINT_MBUTTON_EVENT, PRINT_MOUSEDEV_EVENT, PRINT_PBUTTON_EVENT, PRINT_PPROXIMITY_EVENT, PRINT_PTOUCH_EVENT, SDL_arraysize, SDL_COMPILE_TIME_ASSERT, SDL_DISPLAYEVENT_CASE, SDL_EVENT_AUDIO_DEVICE_ADDED, SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED, SDL_EVENT_AUDIO_DEVICE_REMOVED, SDL_EVENT_CAMERA_DEVICE_ADDED, SDL_EVENT_CAMERA_DEVICE_APPROVED, SDL_EVENT_CAMERA_DEVICE_DENIED, SDL_EVENT_CAMERA_DEVICE_REMOVED, SDL_EVENT_CASE, SDL_EVENT_CLIPBOARD_UPDATE, SDL_EVENT_DID_ENTER_BACKGROUND, SDL_EVENT_DID_ENTER_FOREGROUND, SDL_EVENT_DISPLAY_ADDED, SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED, SDL_EVENT_DISPLAY_MOVED, SDL_EVENT_DISPLAY_ORIENTATION, SDL_EVENT_DISPLAY_REMOVED, SDL_EVENT_DROP_BEGIN, SDL_EVENT_DROP_COMPLETE, SDL_EVENT_DROP_FILE, SDL_EVENT_DROP_POSITION, SDL_EVENT_DROP_TEXT, SDL_EVENT_FINGER_CANCELED, SDL_EVENT_FINGER_DOWN, SDL_EVENT_FINGER_MOTION, SDL_EVENT_FINGER_UP, SDL_EVENT_FIRST, SDL_EVENT_GAMEPAD_ADDED, SDL_EVENT_GAMEPAD_AXIS_MOTION, SDL_EVENT_GAMEPAD_BUTTON_DOWN, SDL_EVENT_GAMEPAD_BUTTON_UP, SDL_EVENT_GAMEPAD_REMAPPED, SDL_EVENT_GAMEPAD_REMOVED, SDL_EVENT_GAMEPAD_SENSOR_UPDATE, SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED, SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN, SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION, SDL_EVENT_GAMEPAD_TOUCHPAD_UP, SDL_EVENT_GAMEPAD_UPDATE_COMPLETE, SDL_EVENT_JOYSTICK_ADDED, SDL_EVENT_JOYSTICK_AXIS_MOTION, SDL_EVENT_JOYSTICK_BALL_MOTION, SDL_EVENT_JOYSTICK_BATTERY_UPDATED, SDL_EVENT_JOYSTICK_BUTTON_DOWN, SDL_EVENT_JOYSTICK_BUTTON_UP, SDL_EVENT_JOYSTICK_HAT_MOTION, SDL_EVENT_JOYSTICK_REMOVED, SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_EVENT_KEY_DOWN, SDL_EVENT_KEY_UP, SDL_EVENT_KEYBOARD_ADDED, SDL_EVENT_KEYBOARD_REMOVED, SDL_EVENT_KEYMAP_CHANGED, SDL_EVENT_LAST, SDL_EVENT_LOCALE_CHANGED, SDL_EVENT_LOW_MEMORY, SDL_EVENT_MOUSE_ADDED, SDL_EVENT_MOUSE_BUTTON_DOWN, SDL_EVENT_MOUSE_BUTTON_UP, SDL_EVENT_MOUSE_MOTION, SDL_EVENT_MOUSE_REMOVED, SDL_EVENT_MOUSE_WHEEL, SDL_EVENT_PEN_AXIS, SDL_EVENT_PEN_BUTTON_DOWN, SDL_EVENT_PEN_BUTTON_UP, SDL_EVENT_PEN_DOWN, SDL_EVENT_PEN_MOTION, SDL_EVENT_PEN_PROXIMITY_IN, SDL_EVENT_PEN_PROXIMITY_OUT, SDL_EVENT_PEN_UP, SDL_EVENT_POLL_SENTINEL, SDL_EVENT_QUIT, SDL_EVENT_RENDER_DEVICE_LOST, SDL_EVENT_RENDER_DEVICE_RESET, SDL_EVENT_RENDER_TARGETS_RESET, SDL_EVENT_SENSOR_UPDATE, SDL_EVENT_SYSTEM_THEME_CHANGED, SDL_EVENT_TERMINATING, SDL_EVENT_TEXT_EDITING, SDL_EVENT_TEXT_EDITING_CANDIDATES, SDL_EVENT_TEXT_INPUT, SDL_EVENT_USER, SDL_EVENT_WILL_ENTER_BACKGROUND, SDL_EVENT_WILL_ENTER_FOREGROUND, SDL_EVENT_WINDOW_CLOSE_REQUESTED, SDL_EVENT_WINDOW_DESTROYED, SDL_EVENT_WINDOW_DISPLAY_CHANGED, SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED, SDL_EVENT_WINDOW_ENTER_FULLSCREEN, SDL_EVENT_WINDOW_EXPOSED, SDL_EVENT_WINDOW_FOCUS_GAINED, SDL_EVENT_WINDOW_FOCUS_LOST, SDL_EVENT_WINDOW_HDR_STATE_CHANGED, SDL_EVENT_WINDOW_HIDDEN, SDL_EVENT_WINDOW_HIT_TEST, SDL_EVENT_WINDOW_ICCPROF_CHANGED, SDL_EVENT_WINDOW_LEAVE_FULLSCREEN, SDL_EVENT_WINDOW_MAXIMIZED, SDL_EVENT_WINDOW_METAL_VIEW_RESIZED, SDL_EVENT_WINDOW_MINIMIZED, SDL_EVENT_WINDOW_MOUSE_ENTER, SDL_EVENT_WINDOW_MOUSE_LEAVE, SDL_EVENT_WINDOW_MOVED, SDL_EVENT_WINDOW_OCCLUDED, SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, SDL_EVENT_WINDOW_RESIZED, SDL_EVENT_WINDOW_RESTORED, SDL_EVENT_WINDOW_SAFE_AREA_CHANGED, SDL_EVENT_WINDOW_SHOWN, SDL_MOUSEWHEEL_NORMAL, SDL_PEN_AXIS_COUNT, SDL_RENDEREVENT_CASE, SDL_snprintf(), SDL_strlcpy(), SDL_WINDOWEVENT_CASE, uint, and void().
Referenced by SDL_LogEvent().
SDL_GetEventFilter()
bool SDL_GetEventFilter (SDL_EventFilter * filter, void ** userdata)
Query the current event filter.
This function can be used to "chain" filters, by saving the existing filter before replacing it with a function that will call that saved filter.
Parameters
filter the current callback function will be stored here.
userdata the pointer that is passed to the current event filter will be stored here.
Returns
true on success or false if there is no event filter set.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetEventFilter
{
    SDL_EventWatcher event_ok;
    SDL_LockMutex(SDL_event_watchers.lock);
    {
        event_ok = SDL_event_watchers.filter;
    }
    SDL_UnlockMutex(SDL_event_watchers.lock);
    if (filter) {
        *filter = event_ok.callback;
    }
    if (userdata) {
        *userdata = event_ok.userdata;
    }
    return event_ok.callback ? true : false;
}
References SDL_EventWatcher::callback, SDL_event_watchers, SDL_LockMutex(), SDL_UnlockMutex(), true, SDL_EventWatcher::userdata, and SDL_MainThreadCallbackEntry::userdata.
SDL_GetTemporaryMemoryEntry()
SDL_TemporaryMemory * SDL_GetTemporaryMemoryEntry (SDL_TemporaryMemoryState * state, const void * mem) static
{
    SDL_TemporaryMemory *entry;
    // Start from the end, it's likely to have been recently allocated
    for (entry = state->tail; entry; entry = entry->prev) {
        if (mem == entry->memory) {
            return entry;
        }
    }
    return NULL;
}
References SDL_TemporaryMemory::memory, NULL, SDL_TemporaryMemory::prev, and SDL_TemporaryMemoryState::tail.
Referenced by SDL_ClaimTemporaryMemory(), and SDL_LinkTemporaryMemoryToEvent().
SDL_GetTemporaryMemoryState()
SDL_TemporaryMemoryState * SDL_GetTemporaryMemoryState (bool create) static
{
    SDL_TemporaryMemoryState *state;
    state = (SDL_TemporaryMemoryState *)SDL_GetTLS(&SDL_temporary_memory);
    if (!state) {
        if (!create) {
            return NULL;
        }
        state = (SDL_TemporaryMemoryState *)SDL_calloc(1, sizeof(*state));
        if (!state) {
            return NULL;
        }
        if (!SDL_SetTLS(&SDL_temporary_memory, state, SDL_CleanupTemporaryMemory)) {
            SDL_free(state);
            return NULL;
        }
    }
    return state;
}
References NULL, SDL_calloc(), SDL_CleanupTemporaryMemory(), SDL_free(), SDL_GetTLS(), SDL_SetTLS(), and SDL_temporary_memory.
Referenced by SDL_ClaimTemporaryMemory(), SDL_FreeLater(), SDL_FreeTemporaryMemory(), SDL_LinkTemporaryMemoryToEvent(), and SDL_TransferTemporaryMemoryFromEvent().
SDL_HasEvent()
bool SDL_HasEvent (Uint32 type)
Check for the existence of a certain event type in the event queue.
If you need to check for a range of event types, use SDL_HasEvents() instead.
Parameters
type the type of event to be queried; see SDL_EventType for details.
Returns
true if events matching type are present, or false if events matching type are not present.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasEvents
{
    return SDL_HasEvents(type, type);
}
References SDL_HasEvents().
SDL_HasEvents()
bool SDL_HasEvents (Uint32 minType, Uint32 maxType)
Check for the existence of certain event types in the event queue.
If you need to check for a single event type, use SDL_HasEvent() instead.
Parameters
minType the low end of event type to be queried, inclusive; see SDL_EventType for details.
maxType the high end of event type to be queried, inclusive; see SDL_EventType for details.
Returns
true if events with type >= minType and <= maxType are present, or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasEvents
{
    bool found = false;
    SDL_LockMutex(SDL_EventQ.lock);
    {
        if (SDL_EventQ.active) {
            for (SDL_EventEntry *entry = SDL_EventQ.head; entry; entry = entry->next) {
                const Uint32 type = entry->event.type;
                if (minType <= type && type <= maxType) {
                    found = true;
                    break;
                }
            }
        }
    }
    SDL_UnlockMutex(SDL_EventQ.lock);
    return found;
}
References SDL_EventQ, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_HasEvent().
SDL_InitEvents()
bool SDL_InitEvents (void)
{
#ifdef SDL_PLATFORM_ANDROID
    Android_InitEvents();
#endif
#ifndef SDL_JOYSTICK_DISABLED
    SDL_AddHintCallback(SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_AutoUpdateJoysticksChanged, NULL);
#endif
#ifndef SDL_SENSOR_DISABLED
    SDL_AddHintCallback(SDL_HINT_AUTO_UPDATE_SENSORS, SDL_AutoUpdateSensorsChanged, NULL);
#endif
    SDL_AddHintCallback(SDL_HINT_EVENT_LOGGING, SDL_EventLoggingChanged, NULL);
    SDL_AddHintCallback(SDL_HINT_POLL_SENTINEL, SDL_PollSentinelChanged, NULL);
    SDL_InitMainThreadCallbacks();
    if (!SDL_StartEventLoop()) {
        SDL_RemoveHintCallback(SDL_HINT_EVENT_LOGGING, SDL_EventLoggingChanged, NULL);
        return false;
    }
    SDL_InitQuit();
    return true;
}
References Android_InitEvents(), NULL, SDL_AddHintCallback(), SDL_AutoUpdateJoysticksChanged(), SDL_AutoUpdateSensorsChanged(), SDL_EventLoggingChanged(), SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_HINT_AUTO_UPDATE_SENSORS, SDL_HINT_EVENT_LOGGING, SDL_HINT_POLL_SENTINEL, SDL_InitMainThreadCallbacks(), SDL_InitQuit(), SDL_PollSentinelChanged(), SDL_RemoveHintCallback(), and SDL_StartEventLoop().
Referenced by SDL_InitSubSystem().
SDL_InitMainThreadCallbacks()
void SDL_InitMainThreadCallbacks (void) static
{
    SDL_main_callbacks_lock = SDL_CreateMutex();
    SDL_assert(SDL_main_callbacks_head == NULL &&
               SDL_main_callbacks_tail == NULL);
}
References NULL, SDL_assert, SDL_CreateMutex(), SDL_main_callbacks_head, SDL_main_callbacks_lock, and SDL_main_callbacks_tail.
Referenced by SDL_InitEvents().
SDL_LinkTemporaryMemoryEntry()
void SDL_LinkTemporaryMemoryEntry (SDL_TemporaryMemoryState * state, SDL_TemporaryMemory * entry) static
{
    entry->prev = state->tail;
    entry->next = NULL;
    if (state->tail) {
        state->tail->next = entry;
    } else {
        state->head = entry;
    }
    state->tail = entry;
}
References SDL_TemporaryMemoryState::head, SDL_TemporaryMemory::next, NULL, SDL_TemporaryMemory::prev, and SDL_TemporaryMemoryState::tail.
Referenced by SDL_FreeLater(), and SDL_TransferTemporaryMemoryFromEvent().
SDL_LinkTemporaryMemoryToEvent()
void SDL_LinkTemporaryMemoryToEvent (SDL_EventEntry * event, const void * mem) static
{
    SDL_TemporaryMemoryState *state;
    SDL_TemporaryMemory *entry;
    state = SDL_GetTemporaryMemoryState(false);
    if (!state) {
        return;
    }
    entry = SDL_GetTemporaryMemoryEntry(state, mem);
    if (entry) {
        SDL_UnlinkTemporaryMemoryEntry(state, entry);
        entry->next = event->memory;
        event->memory = entry;
    }
}
References SDL_TemporaryMemory::memory, SDL_TemporaryMemory::next, SDL_GetTemporaryMemoryEntry(), SDL_GetTemporaryMemoryState(), and SDL_UnlinkTemporaryMemoryEntry().
Referenced by SDL_TransferSysWMMemoryToEvent(), and SDL_TransferTemporaryMemoryToEvent().
SDL_LogEvent()
void SDL_LogEvent (const SDL_Event * event) static
{
    if (!event) {
        return;
    }
    // sensor/mouse/pen/finger motion are spammy, ignore these if they aren't demanded.
    if ((SDL_EventLoggingVerbosity < 2) &&
        ((event->type == SDL_EVENT_MOUSE_MOTION) ||
         (event->type == SDL_EVENT_FINGER_MOTION) ||
         (event->type == SDL_EVENT_PEN_AXIS) ||
         (event->type == SDL_EVENT_PEN_MOTION) ||
         (event->type == SDL_EVENT_GAMEPAD_AXIS_MOTION) ||
         (event->type == SDL_EVENT_GAMEPAD_SENSOR_UPDATE) ||
         (event->type == SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION) ||
         (event->type == SDL_EVENT_GAMEPAD_UPDATE_COMPLETE) ||
         (event->type == SDL_EVENT_JOYSTICK_AXIS_MOTION) ||
         (event->type == SDL_EVENT_JOYSTICK_UPDATE_COMPLETE) ||
         (event->type == SDL_EVENT_SENSOR_UPDATE))) {
        return;
    }
    char buf[256];
    const int rc = SDL_GetEventDescription(event, buf, sizeof (buf));
    SDL_assert(rc < sizeof (buf));  // if this overflows, we should make `buf` larger, but this is currently larger than the max SDL_GetEventDescription returns.
    if (buf[0]) {
        SDL_Log("SDL EVENT: %s", buf);
    }
}
References SDL_assert, SDL_EVENT_FINGER_MOTION, SDL_EVENT_GAMEPAD_AXIS_MOTION, SDL_EVENT_GAMEPAD_SENSOR_UPDATE, SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION, SDL_EVENT_GAMEPAD_UPDATE_COMPLETE, SDL_EVENT_JOYSTICK_AXIS_MOTION, SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_EVENT_MOUSE_MOTION, SDL_EVENT_PEN_AXIS, SDL_EVENT_PEN_MOTION, SDL_EVENT_SENSOR_UPDATE, SDL_EventLoggingVerbosity, SDL_GetEventDescription(), and SDL_Log().
Referenced by SDL_AddEvent(), and SDL_SendAppEvent().
SDL_PeepEvents()
int SDL_PeepEvents (SDL_Event * events, int numevents, SDL_EventAction action, Uint32 minType, Uint32 maxType)
Check the event queue for messages and optionally return them.
action may be any of the following:
SDL_ADDEVENT: up to numevents events will be added to the back of the event queue.
SDL_PEEKEVENT: numevents events at the front of the event queue, within the specified minimum and maximum type, will be returned to the caller and will not be removed from the queue. If you pass NULL for events, then numevents is ignored and the total number of matching events will be returned.
SDL_GETEVENT: up to numevents events at the front of the event queue, within the specified minimum and maximum type, will be returned to the caller and will be removed from the queue.
You may have to call SDL_PumpEvents() before calling this function. Otherwise, the events may not be ready to be filtered when you call SDL_PeepEvents().
Parameters
events destination buffer for the retrieved events, may be NULL to leave the events in the queue and return the number of events that would have been stored.
numevents if action is SDL_ADDEVENT, the number of events to add back to the event queue; if action is SDL_PEEKEVENT or SDL_GETEVENT, the maximum number of events to retrieve.
action action to take; see Remarks for details.
minType minimum value of the event type to be considered; SDL_EVENT_FIRST is a safe choice.
maxType maximum value of the event type to be considered; SDL_EVENT_LAST is a safe choice.
Returns
the number of events actually stored or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_PumpEvents
SDL_PushEvent
{
    return SDL_PeepEventsInternal(events, numevents, action, minType, maxType, false);
}
References SDL_PeepEventsInternal().
Referenced by SDL_DispatchMainCallbackEvents(), SDL_PushEvent(), SDL_WaitEventTimeout_Device(), and SDL_WaitEventTimeoutNS().
SDL_PeepEventsInternal()
int SDL_PeepEventsInternal (SDL_Event * events, int numevents, SDL_EventAction action, Uint32 minType, Uint32 maxType, bool include_sentinel) static
{
    int i, used, sentinels_expected = 0;
    // Lock the event queue
    used = 0;
    SDL_LockMutex(SDL_EventQ.lock);
    {
        // Don't look after we've quit
        if (!SDL_EventQ.active) {
            // We get a few spurious events at shutdown, so don't warn then
            if (action == SDL_GETEVENT) {
                SDL_SetError("The event system has been shut down");
            }
            SDL_UnlockMutex(SDL_EventQ.lock);
            return -1;
        }
        if (action == SDL_ADDEVENT) {
            if (!events) {
                SDL_UnlockMutex(SDL_EventQ.lock);
                return SDL_InvalidParamError("events");
            }
            for (i = 0; i < numevents; ++i) {
                used += SDL_AddEvent(&events[i]);
            }
        } else {
            SDL_EventEntry *entry, *next;
            Uint32 type;
            for (entry = SDL_EventQ.head; entry && (events == NULL || used < numevents); entry = next) {
                next = entry->next;
                type = entry->event.type;
                if (minType <= type && type <= maxType) {
                    if (events) {
                        SDL_copyp(&events[used], &entry->event);
                        if (action == SDL_GETEVENT) {
                            SDL_CutEvent(entry);
                        }
                    }
                    if (type == SDL_EVENT_POLL_SENTINEL) {
                        // Special handling for the sentinel event
                        if (!include_sentinel) {
                            // Skip it, we don't want to include it
                            continue;
                        }
                        if (events == NULL || action != SDL_GETEVENT) {
                            ++sentinels_expected;
                        }
                        if (SDL_GetAtomicInt(&SDL_sentinel_pending) > sentinels_expected) {
                            // Skip it, there's another one pending
                            continue;
                        }
                    }
                    ++used;
                }
            }
        }
    }
    SDL_UnlockMutex(SDL_EventQ.lock);
    if (used > 0 && action == SDL_ADDEVENT) {
        SDL_SendWakeupEvent();
    }
    return used;
}
References SDL_EventEntry::event, SDL_EventEntry::next, NULL, SDL_ADDEVENT, SDL_AddEvent(), SDL_copyp, SDL_CutEvent(), SDL_EVENT_POLL_SENTINEL, SDL_EventQ, SDL_GetAtomicInt(), SDL_GETEVENT, SDL_InvalidParamError, SDL_LockMutex(), SDL_SendWakeupEvent(), SDL_sentinel_pending, SDL_SetError(), SDL_UnlockMutex(), and SDL_Event::type.
Referenced by SDL_PeepEvents(), SDL_PumpEventsInternal(), and SDL_WaitEventTimeoutNS().
SDL_PollEvent()
bool SDL_PollEvent (SDL_Event * event)
Poll for currently pending events.
If event is not NULL, the next event is removed from the queue and stored in the SDL_Event structure pointed to by event. The 1 returned refers to this event, immediately stored in the SDL Event structure – not an event to follow.
If event is NULL, it simply returns 1 if there is an event in the queue, but will not remove it from the queue.
As this function may implicitly call SDL_PumpEvents(), you can only call this function in the thread that set the video mode.
SDL_PollEvent() is the favored way of receiving system events since it can be done from the main loop and does not suspend the main loop while waiting on an event to be posted.
The common practice is to fully process the event queue once every frame, usually as a first step before updating the game's state:
while (game_is_still_running) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {  // poll until all events are handled!
        // decide what to do with this event.
    }
    // update game state, draw the current frame
}
Parameters
event the SDL_Event structure to be filled with the next event from the queue, or NULL.
Returns
true if this got an event or false if there are none available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PushEvent
SDL_WaitEvent
SDL_WaitEventTimeout
{
    return SDL_WaitEventTimeoutNS(event, 0);
}
References SDL_WaitEventTimeoutNS().
Referenced by CSDLmain::RunL().
SDL_PollSentinelChanged()
void SDLCALL SDL_PollSentinelChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    SDL_SetEventEnabled(SDL_EVENT_POLL_SENTINEL, SDL_GetStringBoolean(hint, true));
}
References SDL_EVENT_POLL_SENTINEL, SDL_GetStringBoolean(), SDL_SetEventEnabled(), and SDLCALL.
Referenced by SDL_InitEvents(), and SDL_QuitEvents().
SDL_PumpEventMaintenance()
void SDL_PumpEventMaintenance (void)
{
#ifndef SDL_AUDIO_DISABLED
    SDL_UpdateAudio();
#endif
#ifndef SDL_CAMERA_DISABLED
    SDL_UpdateCamera();
#endif
#ifndef SDL_SENSOR_DISABLED
    // Check for sensor state change
    if (SDL_update_sensors) {
        SDL_UpdateSensors();
    }
#endif
#ifndef SDL_JOYSTICK_DISABLED
    // Check for joystick state change
    if (SDL_update_joysticks) {
        SDL_UpdateJoysticks();
    }
#endif
    SDL_UpdateTrays();
    SDL_SendPendingSignalEvents(); // in case we had a signal handler fire, etc.
}
References SDL_SendPendingSignalEvents(), SDL_update_joysticks, SDL_update_sensors, SDL_UpdateAudio(), SDL_UpdateCamera(), SDL_UpdateJoysticks(), SDL_UpdateSensors(), and SDL_UpdateTrays().
Referenced by SDL_OnWindowLiveResizeUpdate(), and SDL_PumpEventsInternal().
SDL_PumpEvents()
void SDL_PumpEvents (void)
Pump the event loop, gathering events from the input devices.
This function updates the event queue and internal input device state.
SDL_PumpEvents() gathers all the pending input information from devices and places it in the event queue. Without calls to SDL_PumpEvents() no events would ever be placed on the queue. Often the need for calls to SDL_PumpEvents() is hidden from the user since SDL_PollEvent() and SDL_WaitEvent() implicitly call SDL_PumpEvents(). However, if you are not polling or waiting for events (e.g. you are filtering them), then you must call SDL_PumpEvents() to force an event queue update.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_WaitEvent
{
    SDL_PumpEventsInternal(false);
}
References SDL_PumpEventsInternal().
Referenced by EmscriptenInternalMainloop(), CSDLmain::RunL(), SDL_FlushEvents(), and SDL_IterateMainCallbacks().
SDL_PumpEventsInternal()
void SDL_PumpEventsInternal (bool push_sentinel) static
{
    // Free any temporary memory from old events
    SDL_FreeTemporaryMemory();
    // Release any keys held down from last frame
    SDL_ReleaseAutoReleaseKeys();
    // Run any pending main thread callbacks
    SDL_RunMainThreadCallbacks();
#ifdef SDL_PLATFORM_ANDROID
    // Android event processing is independent of the video subsystem
    Android_PumpEvents(0);
#else
    // Get events from the video subsystem
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (_this) {
        _this->PumpEvents(_this);
    }
#endif
    SDL_PumpEventMaintenance();
    if (push_sentinel && SDL_EventEnabled(SDL_EVENT_POLL_SENTINEL)) {
        SDL_Event sentinel;
        // Make sure we don't already have a sentinel in the queue, and add one to the end
        if (SDL_GetAtomicInt(&SDL_sentinel_pending) > 0) {
            SDL_PeepEventsInternal(&sentinel, 1, SDL_GETEVENT, SDL_EVENT_POLL_SENTINEL, SDL_EVENT_POLL_SENTINEL, true);
        }
        sentinel.type = SDL_EVENT_POLL_SENTINEL;
        sentinel.common.timestamp = 0;
        SDL_PushEvent(&sentinel);
    }
}
References _this, Android_PumpEvents(), SDL_Event::common, SDL_EVENT_POLL_SENTINEL, SDL_EventEnabled(), SDL_FreeTemporaryMemory(), SDL_GetAtomicInt(), SDL_GETEVENT, SDL_GetVideoDevice(), SDL_PeepEventsInternal(), SDL_PumpEventMaintenance(), SDL_PushEvent(), SDL_ReleaseAutoReleaseKeys(), SDL_RunMainThreadCallbacks(), SDL_sentinel_pending, SDL_CommonEvent::timestamp, and SDL_Event::type.
Referenced by SDL_PumpEvents(), SDL_WaitEventTimeout_Device(), and SDL_WaitEventTimeoutNS().
SDL_PushEvent()
bool SDL_PushEvent (SDL_Event * event)
Add an event to the event queue.
The event queue can actually be used as a two way communication channel. Not only can events be read from the queue, but the user can also push their own events onto it. event is a pointer to the event structure you wish to push onto the queue. The event is copied into the queue, and the caller may dispose of the memory pointed to after SDL_PushEvent() returns.
Note: Pushing device input events onto the queue doesn't modify the state of the device within SDL.
Note: Events pushed onto the queue with SDL_PushEvent() get passed through the event filter but events added with SDL_PeepEvents() do not.
For pushing application-specific events, please use SDL_RegisterEvents() to get an event type that does not conflict with other code that also wants its own custom event types.
Parameters
event the SDL_Event to be added to the queue.
Returns
true on success, false if the event was filtered or on failure; call SDL_GetError() for more information. A common reason for error is the event queue being full.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PeepEvents
SDL_PollEvent
SDL_RegisterEvents
{
    if (!event->common.timestamp) {
        event->common.timestamp = SDL_GetTicksNS();
    }
    if (!SDL_CallEventWatchers(event)) {
        SDL_ClearError();
        return false;
    }
    if (SDL_PeepEvents(event, 1, SDL_ADDEVENT, 0, 0) <= 0) {
        return false;
    }
    return true;
}
References SDL_ADDEVENT, SDL_CallEventWatchers(), SDL_ClearError(), SDL_GetTicksNS(), and SDL_PeepEvents().
Referenced by SDL_AddKeyboard(), SDL_AddMouse(), SDL_AddPenDevice(), SDL_GamepadEventWatcher(), SDL_PrivateGamepadAdded(), SDL_PrivateGamepadRemapped(), SDL_PrivateGamepadRemoved(), SDL_PrivateJoystickAdded(), SDL_PrivateJoystickRemoved(), SDL_PrivateSendMouseButton(), SDL_PrivateSendMouseMotion(), SDL_PumpEventsInternal(), SDL_RemoveKeyboard(), SDL_RemoveMouse(), SDL_RemovePenDevice(), SDL_SendAppEvent(), SDL_SendClipboardUpdate(), SDL_SendDisplayEvent(), SDL_SendDrop(), SDL_SendEditingText(), SDL_SendEditingTextCandidates(), SDL_SendGamepadAxis(), SDL_SendGamepadButton(), SDL_SendJoystickAxis(), SDL_SendJoystickBall(), SDL_SendJoystickButton(), SDL_SendJoystickHat(), SDL_SendJoystickPowerInfo(), SDL_SendJoystickSensor(), SDL_SendJoystickTouchpad(), SDL_SendKeyboardKeyInternal(), SDL_SendKeyboardText(), SDL_SendMouseWheel(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SendSensorUpdate(), SDL_SendTouch(), SDL_SendTouchMotion(), SDL_SendWindowEvent(), SDL_UpdateAudio(), SDL_UpdateCamera(), SDL_UpdateJoysticks(), and SendSteamHandleUpdateEvents().
SDL_QuitEvents()
void SDL_QuitEvents (void)
{
    SDL_QuitQuit();
    SDL_StopEventLoop();
    SDL_QuitMainThreadCallbacks();
    SDL_RemoveHintCallback(SDL_HINT_POLL_SENTINEL, SDL_PollSentinelChanged, NULL);
    SDL_RemoveHintCallback(SDL_HINT_EVENT_LOGGING, SDL_EventLoggingChanged, NULL);
#ifndef SDL_JOYSTICK_DISABLED
    SDL_RemoveHintCallback(SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_AutoUpdateJoysticksChanged, NULL);
#endif
#ifndef SDL_SENSOR_DISABLED
    SDL_RemoveHintCallback(SDL_HINT_AUTO_UPDATE_SENSORS, SDL_AutoUpdateSensorsChanged, NULL);
#endif
#ifdef SDL_PLATFORM_ANDROID
    Android_QuitEvents();
#endif
}
References Android_QuitEvents(), NULL, SDL_AutoUpdateJoysticksChanged(), SDL_AutoUpdateSensorsChanged(), SDL_EventLoggingChanged(), SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_HINT_AUTO_UPDATE_SENSORS, SDL_HINT_EVENT_LOGGING, SDL_HINT_POLL_SENTINEL, SDL_PollSentinelChanged(), SDL_QuitMainThreadCallbacks(), SDL_QuitQuit(), SDL_RemoveHintCallback(), and SDL_StopEventLoop().
Referenced by SDL_QuitSubSystem().
SDL_QuitMainThreadCallbacks()
void SDL_QuitMainThreadCallbacks (void) static
{
    SDL_MainThreadCallbackEntry *entry;
    SDL_LockMutex(SDL_main_callbacks_lock);
    {
        entry = SDL_main_callbacks_head;
        SDL_main_callbacks_head = NULL;
        SDL_main_callbacks_tail = NULL;
    }
    SDL_UnlockMutex(SDL_main_callbacks_lock);
    while (entry) {
        SDL_MainThreadCallbackEntry *next = entry->next;
        if (entry->semaphore) {
            // Let the waiting thread know this is canceled
            SDL_SetAtomicInt(&entry->state, SDL_MAIN_CALLBACK_CANCELED);
            SDL_SignalSemaphore(entry->semaphore);
        } else {
            // Nobody's waiting for this, clean it up
            SDL_DestroyMainThreadCallback(entry);
        }
        entry = next;
    }
    SDL_DestroyMutex(SDL_main_callbacks_lock);
    SDL_main_callbacks_lock = NULL;
}
References SDL_MainThreadCallbackEntry::next, NULL, SDL_DestroyMainThreadCallback(), SDL_DestroyMutex(), SDL_LockMutex(), SDL_MAIN_CALLBACK_CANCELED, SDL_main_callbacks_head, SDL_main_callbacks_lock, SDL_main_callbacks_tail, SDL_SetAtomicInt(), SDL_SignalSemaphore(), SDL_UnlockMutex(), SDL_MainThreadCallbackEntry::semaphore, and SDL_MainThreadCallbackEntry::state.
Referenced by SDL_QuitEvents().
SDL_RegisterEvents()
Uint32 SDL_RegisterEvents (int numevents)
Allocate a set of user-defined events, and return the beginning event number for that set of events.
Parameters
numevents the number of events to be allocated.
Returns
the beginning event number, or 0 if numevents is invalid or if there are not enough user-defined events left.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PushEvent
{
    Uint32 event_base = 0;
    if (numevents > 0) {
        int value = SDL_AddAtomicInt(&SDL_userevents, numevents);
        if (value >= 0 && value <= (SDL_EVENT_LAST - SDL_EVENT_USER)) {
            event_base = (Uint32)(SDL_EVENT_USER + value);
        }
    }
    return event_base;
}
References SDL_AddAtomicInt(), SDL_EVENT_LAST, SDL_EVENT_USER, and SDL_userevents.
SDL_RemoveEventWatch()
void SDL_RemoveEventWatch (SDL_EventFilter filter, void * userdata)
Remove an event watch callback added with SDL_AddEventWatch().
This function takes the same input as SDL_AddEventWatch() to identify and delete the corresponding callback.
Parameters
filter the function originally passed to SDL_AddEventWatch().
userdata the pointer originally passed to SDL_AddEventWatch().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddEventWatch
{
    SDL_RemoveEventWatchList(&SDL_event_watchers, filter, userdata);
}
References SDL_event_watchers, SDL_RemoveEventWatchList(), and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_QuitGamepads(), and SDL_QuitMainCallbacks().
SDL_RunMainThreadCallbacks()
void SDL_RunMainThreadCallbacks (void) static
{
    SDL_MainThreadCallbackEntry *entry;
    SDL_LockMutex(SDL_main_callbacks_lock);
    {
        entry = SDL_main_callbacks_head;
        SDL_main_callbacks_head = NULL;
        SDL_main_callbacks_tail = NULL;
    }
    SDL_UnlockMutex(SDL_main_callbacks_lock);
    while (entry) {
        SDL_MainThreadCallbackEntry *next = entry->next;
        entry->callback(entry->userdata);
        if (entry->semaphore) {
            // Let the waiting thread know this is done
            SDL_SetAtomicInt(&entry->state, SDL_MAIN_CALLBACK_COMPLETE);
            SDL_SignalSemaphore(entry->semaphore);
        } else {
            // Nobody's waiting for this, clean it up
            SDL_DestroyMainThreadCallback(entry);
        }
        entry = next;
    }
}
References SDL_MainThreadCallbackEntry::callback, SDL_MainThreadCallbackEntry::next, NULL, SDL_DestroyMainThreadCallback(), SDL_LockMutex(), SDL_MAIN_CALLBACK_COMPLETE, SDL_main_callbacks_head, SDL_main_callbacks_lock, SDL_main_callbacks_tail, SDL_SetAtomicInt(), SDL_SignalSemaphore(), SDL_UnlockMutex(), SDL_MainThreadCallbackEntry::semaphore, SDL_MainThreadCallbackEntry::state, and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_PumpEventsInternal().
SDL_RunOnMainThread()
bool SDL_RunOnMainThread (SDL_MainThreadCallback callback, void * userdata, bool wait_complete)
Call a function on the main thread during event processing.
If this is called on the main thread, the callback is executed immediately. If this is called on another thread, this callback is queued for execution on the main thread during event processing.
Be careful of deadlocks when using this functionality. You should not have the main thread wait for the current thread while this function is being called with wait_complete true.
Parameters
callback the callback to call on the main thread.
userdata a pointer that is passed to callback.
wait_complete true to wait for the callback to complete, false to return immediately.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_IsMainThread
{
    if (SDL_IsMainThread() || !SDL_WasInit(SDL_INIT_EVENTS)) {
        // No need to queue the callback
        callback(userdata);
        return true;
    }
    SDL_MainThreadCallbackEntry *entry = SDL_CreateMainThreadCallback(callback, userdata, wait_complete);
    if (!entry) {
        return false;
    }
    SDL_LockMutex(SDL_main_callbacks_lock);
    {
        if (SDL_main_callbacks_tail) {
            SDL_main_callbacks_tail->next = entry;
            SDL_main_callbacks_tail = entry;
        } else {
            SDL_main_callbacks_head = entry;
            SDL_main_callbacks_tail = entry;
        }
    }
    SDL_UnlockMutex(SDL_main_callbacks_lock);
    // If the main thread is waiting for events, wake it up
    SDL_SendWakeupEvent();
    if (!wait_complete) {
        // Queued for execution, wait not requested
        return true;
    }
    SDL_WaitSemaphore(entry->semaphore);
    switch (SDL_GetAtomicInt(&entry->state)) {
    case SDL_MAIN_CALLBACK_COMPLETE:
        // Execution complete!
        SDL_DestroyMainThreadCallback(entry);
        return true;
    case SDL_MAIN_CALLBACK_CANCELED:
        // The callback was canceled on the main thread
        SDL_DestroyMainThreadCallback(entry);
        return SDL_SetError("Callback canceled");
    default:
        // Probably hit a deadlock in the callback
        // We can't destroy the entry as the semaphore will be signaled
        // if it ever comes back, just leak it here.
        return SDL_SetError("Callback timed out");
    }
}
References SDL_MainThreadCallbackEntry::callback, SDL_CreateMainThreadCallback(), SDL_DestroyMainThreadCallback(), SDL_GetAtomicInt(), SDL_INIT_EVENTS, SDL_IsMainThread(), SDL_LockMutex(), SDL_MAIN_CALLBACK_CANCELED, SDL_MAIN_CALLBACK_COMPLETE, SDL_main_callbacks_head, SDL_main_callbacks_lock, SDL_main_callbacks_tail, SDL_SendWakeupEvent(), SDL_SetError(), SDL_UnlockMutex(), SDL_WaitSemaphore(), SDL_WasInit(), SDL_MainThreadCallbackEntry::semaphore, SDL_MainThreadCallbackEntry::state, and SDL_MainThreadCallbackEntry::userdata.
SDL_SendAppEvent()
void SDL_SendAppEvent (SDL_EventType eventType)
{
    if (SDL_EventEnabled(eventType)) {
        SDL_Event event;
        event.type = eventType;
        event.common.timestamp = 0;
        switch (eventType) {
        case SDL_EVENT_TERMINATING:
        case SDL_EVENT_LOW_MEMORY:
        case SDL_EVENT_WILL_ENTER_BACKGROUND:
        case SDL_EVENT_DID_ENTER_BACKGROUND:
        case SDL_EVENT_WILL_ENTER_FOREGROUND:
        case SDL_EVENT_DID_ENTER_FOREGROUND:
            // We won't actually queue this event, it needs to be handled in this call stack by an event watcher
            if (SDL_EventLoggingVerbosity > 0) {
                SDL_LogEvent(&event);
            }
            SDL_CallEventWatchers(&event);
            break;
        default:
            SDL_PushEvent(&event);
            break;
        }
    }
}
References SDL_CallEventWatchers(), SDL_EVENT_DID_ENTER_BACKGROUND, SDL_EVENT_DID_ENTER_FOREGROUND, SDL_EVENT_LOW_MEMORY, SDL_EVENT_TERMINATING, SDL_EVENT_WILL_ENTER_BACKGROUND, SDL_EVENT_WILL_ENTER_FOREGROUND, SDL_EventEnabled(), SDL_EventLoggingVerbosity, SDL_LogEvent(), and SDL_PushEvent().
Referenced by GDK_RegisterChangeNotifications(), SDL_OnApplicationDidEnterBackground(), SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationDidReceiveMemoryWarning(), SDL_OnApplicationWillEnterBackground(), SDL_OnApplicationWillEnterForeground(), SDL_OnApplicationWillTerminate(), SDL_SendKeymapChangedEvent(), SDL_SendLocaleChangedEvent(), SDL_SendQuit(), and SDL_SendSystemThemeChangedEvent().
SDL_SendKeymapChangedEvent()
void SDL_SendKeymapChangedEvent (void)
{
    SDL_SendAppEvent(SDL_EVENT_KEYMAP_CHANGED);
}
References SDL_EVENT_KEYMAP_CHANGED, and SDL_SendAppEvent().
Referenced by SDL_SetKeymap().
SDL_SendLocaleChangedEvent()
void SDL_SendLocaleChangedEvent (void)
{
    SDL_SendAppEvent(SDL_EVENT_LOCALE_CHANGED);
}
References SDL_EVENT_LOCALE_CHANGED, and SDL_SendAppEvent().
Referenced by SDL_BLooper::MessageReceived().
SDL_SendSystemThemeChangedEvent()
void SDL_SendSystemThemeChangedEvent (void)
{
    SDL_SendAppEvent(SDL_EVENT_SYSTEM_THEME_CHANGED);
}
References SDL_EVENT_SYSTEM_THEME_CHANGED, and SDL_SendAppEvent().
Referenced by SDL_SetSystemTheme().
SDL_SendWakeupEvent()
void SDL_SendWakeupEvent (void) static
{
#ifdef SDL_PLATFORM_ANDROID
    Android_SendLifecycleEvent(SDL_ANDROID_LIFECYCLE_WAKE);
#else
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (_this == NULL || !_this->SendWakeupEvent) {
        return;
    }
    // We only want to do this once while waiting for an event, so set it to NULL atomically here
    SDL_Window *wakeup_window = (SDL_Window *)SDL_SetAtomicPointer(&_this->wakeup_window, NULL);
    if (wakeup_window) {
        _this->SendWakeupEvent(_this, wakeup_window);
    }
#endif
}
References _this, Android_SendLifecycleEvent(), NULL, SDL_ANDROID_LIFECYCLE_WAKE, SDL_GetVideoDevice(), and SDL_SetAtomicPointer().
Referenced by SDL_PeepEventsInternal(), and SDL_RunOnMainThread().
SDL_SetEventEnabled()
void SDL_SetEventEnabled (Uint32 type, bool enabled)
Set the state of processing events by type.
Parameters
type the type of event; see SDL_EventType for details.
enabled whether to process the event or not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_EventEnabled
{
    bool current_state;
    Uint8 hi = ((type >> 8) & 0xff);
    Uint8 lo = (type & 0xff);
    if (SDL_disabled_events[hi] &&
        (SDL_disabled_events[hi]->bits[lo / 32] & (1U << (lo & 31)))) {
        current_state = false;
    } else {
        current_state = true;
    }
    if ((enabled != false) != current_state) {
        if (enabled) {
            SDL_assert(SDL_disabled_events[hi] != NULL);
            SDL_disabled_events[hi]->bits[lo / 32] &= ~(1U << (lo & 31));
            // Gamepad events depend on joystick events
            switch (type) {
            case SDL_EVENT_GAMEPAD_ADDED:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_ADDED, true);
                break;
            case SDL_EVENT_GAMEPAD_REMOVED:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_REMOVED, true);
                break;
            case SDL_EVENT_GAMEPAD_AXIS_MOTION:
            case SDL_EVENT_GAMEPAD_BUTTON_DOWN:
            case SDL_EVENT_GAMEPAD_BUTTON_UP:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_AXIS_MOTION, true);
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_HAT_MOTION, true);
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_BUTTON_DOWN, true);
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_BUTTON_UP, true);
                break;
            case SDL_EVENT_GAMEPAD_UPDATE_COMPLETE:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, true);
                break;
            default:
                break;
            }
        } else {
            // Disable this event type and discard pending events
            if (!SDL_disabled_events[hi]) {
                SDL_disabled_events[hi] = (SDL_DisabledEventBlock *)SDL_calloc(1, sizeof(SDL_DisabledEventBlock));
            }
            // Out of memory, nothing we can do...
            if (SDL_disabled_events[hi]) {
                SDL_disabled_events[hi]->bits[lo / 32] |= (1U << (lo & 31));
                SDL_FlushEvent(type);
            }
        }
        /* turn off drag'n'drop support if we've disabled the events.
           This might change some UI details at the OS level. */
        if (type == SDL_EVENT_DROP_FILE || type == SDL_EVENT_DROP_TEXT) {
            SDL_ToggleDragAndDropSupport();
        }
    }
}
References NULL, SDL_assert, SDL_calloc(), SDL_disabled_events, SDL_EVENT_DROP_FILE, SDL_EVENT_DROP_TEXT, SDL_EVENT_GAMEPAD_ADDED, SDL_EVENT_GAMEPAD_AXIS_MOTION, SDL_EVENT_GAMEPAD_BUTTON_DOWN, SDL_EVENT_GAMEPAD_BUTTON_UP, SDL_EVENT_GAMEPAD_REMOVED, SDL_EVENT_GAMEPAD_UPDATE_COMPLETE, SDL_EVENT_JOYSTICK_ADDED, SDL_EVENT_JOYSTICK_AXIS_MOTION, SDL_EVENT_JOYSTICK_BUTTON_DOWN, SDL_EVENT_JOYSTICK_BUTTON_UP, SDL_EVENT_JOYSTICK_HAT_MOTION, SDL_EVENT_JOYSTICK_REMOVED, SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_FlushEvent(), SDL_SetEventEnabled(), and SDL_ToggleDragAndDropSupport().
Referenced by SDL_PollSentinelChanged(), SDL_SetEventEnabled(), SDL_SetGamepadEventsEnabled(), and SDL_SetJoystickEventsEnabled().
SDL_SetEventFilter()
void SDL_SetEventFilter (SDL_EventFilter filter, void * userdata)
Set up a filter to process all events before they are added to the internal event queue.
If you just want to see events without modifying them or preventing them from being queued, you should use SDL_AddEventWatch() instead.
If the filter function returns true when called, then the event will be added to the internal queue. If it returns false, then the event will be dropped from the queue, but the internal state will still be updated. This allows selective filtering of dynamically arriving events.
WARNING: Be very careful of what you do in the event filter function, as it may run in a different thread!
On platforms that support it, if the quit event is generated by an interrupt signal (e.g. pressing Ctrl-C), it will be delivered to the application at the next event poll.
Note: Disabled events never make it to the event filter function; see SDL_SetEventEnabled().
Note: Events pushed onto the queue with SDL_PushEvent() get passed through the event filter, but events pushed onto the queue with SDL_PeepEvents() do not.
Parameters
filter an SDL_EventFilter function to call when an event happens.
userdata a pointer that is passed to filter.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddEventWatch
SDL_SetEventEnabled
SDL_GetEventFilter
SDL_PeepEvents
SDL_PushEvent
{
    SDL_EventEntry *event, *next;
    SDL_LockMutex(SDL_event_watchers.lock);
    {
        // Set filter and discard pending events
        SDL_event_watchers.filter.callback = filter;
        SDL_event_watchers.filter.userdata = userdata;
        if (filter) {
            // Cut all events not accepted by the filter
            SDL_LockMutex(SDL_EventQ.lock);
            {
                for (event = SDL_EventQ.head; event; event = next) {
                    next = event->next;
                    if (!filter(userdata, &event->event)) {
                        SDL_CutEvent(event);
                    }
                }
            }
            SDL_UnlockMutex(SDL_EventQ.lock);
        }
    }
    SDL_UnlockMutex(SDL_event_watchers.lock);
}
References SDL_MainThreadCallbackEntry::next, SDL_CutEvent(), SDL_event_watchers, SDL_EventQ, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_MainThreadCallbackEntry::userdata.
SDL_StartEventLoop()
bool SDL_StartEventLoop (void)
{
    /* We'll leave the event queue alone, since we might have gotten
       some important events at launch (like SDL_EVENT_DROP_FILE)
       FIXME: Does this introduce any other bugs with events at startup?
     */
    // Create the lock and set ourselves active
#ifndef SDL_THREADS_DISABLED
    if (!SDL_EventQ.lock) {
        SDL_EventQ.lock = SDL_CreateMutex();
        if (SDL_EventQ.lock == NULL) {
            return false;
        }
    }
    SDL_LockMutex(SDL_EventQ.lock);
    if (!SDL_InitEventWatchList(&SDL_event_watchers)) {
        SDL_UnlockMutex(SDL_EventQ.lock);
        return false;
    }
#endif // !SDL_THREADS_DISABLED
    SDL_InitWindowEventWatch();
    SDL_EventQ.active = true;
#ifndef SDL_THREADS_DISABLED
    SDL_UnlockMutex(SDL_EventQ.lock);
#endif
    return true;
}
References NULL, SDL_CreateMutex(), SDL_event_watchers, SDL_EventQ, SDL_InitEventWatchList(), SDL_InitWindowEventWatch(), SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_InitEvents().
SDL_StopEventLoop()
void SDL_StopEventLoop (void)
{
    const char *report = SDL_GetHint("SDL_EVENT_QUEUE_STATISTICS");
    int i;
    SDL_EventEntry *entry;
    SDL_LockMutex(SDL_EventQ.lock);
    SDL_EventQ.active = false;
    if (report && SDL_atoi(report)) {
        SDL_Log("SDL EVENT QUEUE: Maximum events in-flight: %d",
                SDL_EventQ.max_events_seen);
    }
    // Clean out EventQ
    for (entry = SDL_EventQ.head; entry;) {
        SDL_EventEntry *next = entry->next;
        SDL_TransferTemporaryMemoryFromEvent(entry);
        SDL_free(entry);
        entry = next;
    }
    for (entry = SDL_EventQ.free; entry;) {
        SDL_EventEntry *next = entry->next;
        SDL_free(entry);
        entry = next;
    }
    SDL_SetAtomicInt(&SDL_EventQ.count, 0);
    SDL_EventQ.max_events_seen = 0;
    SDL_EventQ.head = NULL;
    SDL_EventQ.tail = NULL;
    SDL_EventQ.free = NULL;
    SDL_SetAtomicInt(&SDL_sentinel_pending, 0);
    // Clear disabled event state
    for (i = 0; i < SDL_arraysize(SDL_disabled_events); ++i) {
        SDL_free(SDL_disabled_events[i]);
        SDL_disabled_events[i] = NULL;
    }
    SDL_QuitEventWatchList(&SDL_event_watchers);
    SDL_QuitWindowEventWatch();
    SDL_Mutex *lock = NULL;
    if (SDL_EventQ.lock) {
        lock = SDL_EventQ.lock;
        SDL_EventQ.lock = NULL;
    }
    SDL_UnlockMutex(lock);
    if (lock) {
        SDL_DestroyMutex(lock);
    }
}
References lock, SDL_EventEntry::next, NULL, SDL_arraysize, SDL_atoi(), SDL_DestroyMutex(), SDL_disabled_events, SDL_event_watchers, SDL_EventQ, SDL_free(), SDL_GetHint(), SDL_LockMutex(), SDL_Log(), SDL_QuitEventWatchList(), SDL_QuitWindowEventWatch(), SDL_sentinel_pending, SDL_SetAtomicInt(), SDL_TransferTemporaryMemoryFromEvent(), and SDL_UnlockMutex().
Referenced by SDL_QuitEvents().
SDL_TransferSysWMMemoryToEvent()
void SDL_TransferSysWMMemoryToEvent (SDL_EventEntry * event) static
{
    SDL2_SysWMmsg **wmmsg = (SDL2_SysWMmsg **)((&event->event.common)+1);
    SDL2_SysWMmsg *mem = SDL_AllocateTemporaryMemory(sizeof(*mem));
    if (mem) {
        SDL_copyp(mem, *wmmsg);
        *wmmsg = mem;
        SDL_LinkTemporaryMemoryToEvent(event, mem);
    }
}
References SDL_AllocateTemporaryMemory(), SDL_copyp, and SDL_LinkTemporaryMemoryToEvent().
Referenced by SDL_TransferTemporaryMemoryToEvent().
SDL_TransferTemporaryMemoryFromEvent()
void SDL_TransferTemporaryMemoryFromEvent (SDL_EventEntry * event) static
{
    SDL_TemporaryMemoryState *state;
    SDL_TemporaryMemory *entry, *next;
    if (!event->memory) {
        return;
    }
    state = SDL_GetTemporaryMemoryState(true);
    if (!state) {
        return;  // this is now a leak, but you probably have bigger problems if malloc failed.
    }
    for (entry = event->memory; entry; entry = next) {
        next = entry->next;
        SDL_LinkTemporaryMemoryEntry(state, entry);
    }
    event->memory = NULL;
}
References SDL_EventEntry::next, SDL_TemporaryMemory::next, NULL, SDL_GetTemporaryMemoryState(), and SDL_LinkTemporaryMemoryEntry().
Referenced by SDL_CutEvent(), and SDL_StopEventLoop().
SDL_TransferTemporaryMemoryToEvent()
void SDL_TransferTemporaryMemoryToEvent (SDL_EventEntry * event) static
{
    switch (event->event.type) {
    case SDL_EVENT_TEXT_EDITING:
        SDL_LinkTemporaryMemoryToEvent(event, event->event.edit.text);
        break;
    case SDL_EVENT_TEXT_EDITING_CANDIDATES:
        SDL_LinkTemporaryMemoryToEvent(event, event->event.edit_candidates.candidates);
        break;
    case SDL_EVENT_TEXT_INPUT:
        SDL_LinkTemporaryMemoryToEvent(event, event->event.text.text);
        break;
    case SDL_EVENT_DROP_BEGIN:
    case SDL_EVENT_DROP_FILE:
    case SDL_EVENT_DROP_TEXT:
    case SDL_EVENT_DROP_COMPLETE:
    case SDL_EVENT_DROP_POSITION:
        SDL_LinkTemporaryMemoryToEvent(event, event->event.drop.source);
        SDL_LinkTemporaryMemoryToEvent(event, event->event.drop.data);
        break;
    case SDL_EVENT_CLIPBOARD_UPDATE:
        SDL_LinkTemporaryMemoryToEvent(event, event->event.clipboard.mime_types);
        break;
    case SDL2_SYSWMEVENT:
        // We need to copy the stack pointer into temporary memory
        SDL_TransferSysWMMemoryToEvent(event);
        break;
    default:
        break;
    }
}
References SDL2_SYSWMEVENT, SDL_EVENT_CLIPBOARD_UPDATE, SDL_EVENT_DROP_BEGIN, SDL_EVENT_DROP_COMPLETE, SDL_EVENT_DROP_FILE, SDL_EVENT_DROP_POSITION, SDL_EVENT_DROP_TEXT, SDL_EVENT_TEXT_EDITING, SDL_EVENT_TEXT_EDITING_CANDIDATES, SDL_EVENT_TEXT_INPUT, SDL_LinkTemporaryMemoryToEvent(), and SDL_TransferSysWMMemoryToEvent().
Referenced by SDL_AddEvent().
SDL_UnlinkTemporaryMemoryEntry()
void SDL_UnlinkTemporaryMemoryEntry (SDL_TemporaryMemoryState * state, SDL_TemporaryMemory * entry) static
{
    if (state->head == entry) {
        state->head = entry->next;
    }
    if (state->tail == entry) {
        state->tail = entry->prev;
    }
    if (entry->prev) {
        entry->prev->next = entry->next;
    }
    if (entry->next) {
        entry->next->prev = entry->prev;
    }
    entry->prev = NULL;
    entry->next = NULL;
}
References SDL_TemporaryMemoryState::head, SDL_TemporaryMemory::next, NULL, SDL_TemporaryMemory::prev, and SDL_TemporaryMemoryState::tail.
Referenced by SDL_ClaimTemporaryMemory(), SDL_FreeTemporaryMemory(), and SDL_LinkTemporaryMemoryToEvent().
SDL_WaitEvent()
bool SDL_WaitEvent (SDL_Event * event)
Wait indefinitely for the next available event.
If event is not NULL, the next event is removed from the queue and stored in the SDL_Event structure pointed to by event.
As this function may implicitly call SDL_PumpEvents(), you can only call this function in the thread that initialized the video subsystem.
Parameters
event the SDL_Event structure to be filled in with the next event from the queue, or NULL.
Returns
true on success or false if there was an error while waiting for events; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_PushEvent
SDL_WaitEventTimeout
{
    return SDL_WaitEventTimeoutNS(event, -1);
}
References SDL_WaitEventTimeoutNS().
Referenced by GenericIterateMainCallbacks().
SDL_WaitEventTimeout()
bool SDL_WaitEventTimeout (SDL_Event * event, Sint32 timeoutMS)
Wait until the specified timeout (in milliseconds) for the next available event.
If event is not NULL, the next event is removed from the queue and stored in the SDL_Event structure pointed to by event.
As this function may implicitly call SDL_PumpEvents(), you can only call this function in the thread that initialized the video subsystem.
The timeout is not guaranteed, the actual wait time could be longer due to system scheduling.
Parameters
event the SDL_Event structure to be filled in with the next event from the queue, or NULL.
timeoutMS the maximum number of milliseconds to wait for the next available event.
Returns
true if this got an event or false if the timeout elapsed without any events available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_PushEvent
SDL_WaitEvent
{
    Sint64 timeoutNS;
    if (timeoutMS > 0) {
        timeoutNS = SDL_MS_TO_NS(timeoutMS);
    } else {
        timeoutNS = timeoutMS;
    }
    return SDL_WaitEventTimeoutNS(event, timeoutNS);
}
References SDL_MS_TO_NS, and SDL_WaitEventTimeoutNS().
SDL_WaitEventTimeout_Device()
int SDL_WaitEventTimeout_Device (SDL_VideoDevice * _this, SDL_Window * wakeup_window, SDL_Event * event, Uint64 start, Sint64 timeoutNS) static
{
    Sint64 loop_timeoutNS = timeoutNS;
    Sint64 poll_intervalNS = SDL_events_get_polling_interval();
    for (;;) {
        int status;
        /* Pump events on entry and each time we wake to ensure:
           a) All pending events are batch processed after waking up from a wait
           b) Waiting can be completely skipped if events are already available to be pumped
           c) Periodic processing that takes place in some platform PumpEvents() functions happens
           d) Signals received in WaitEventTimeout() are turned into SDL events
        */
        SDL_PumpEventsInternal(true);
        status = SDL_PeepEvents(event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST);
        if (status < 0) {
            // Got an error: return
            break;
        }
        if (status > 0) {
            // There is an event, we can return.
            return 1;
        }
        // No events found in the queue, call WaitEventTimeout to wait for an event.
        if (timeoutNS > 0) {
            Sint64 elapsed = SDL_GetTicksNS() - start;
            if (elapsed >= timeoutNS) {
                return 0;
            }
            loop_timeoutNS = (timeoutNS - elapsed);
        }
        // Adjust the timeout for any polling requirements we currently have.
        if (poll_intervalNS != SDL_MAX_SINT64) {
            if (loop_timeoutNS >= 0) {
                loop_timeoutNS = SDL_min(loop_timeoutNS, poll_intervalNS);
            } else {
                loop_timeoutNS = poll_intervalNS;
            }
        }
        SDL_SetAtomicPointer(&_this->wakeup_window, wakeup_window);
        status = _this->WaitEventTimeout(_this, loop_timeoutNS);
        SDL_SetAtomicPointer(&_this->wakeup_window, NULL);
        if (status == 0 && poll_intervalNS != SDL_MAX_SINT64 && loop_timeoutNS == poll_intervalNS) {
            // We may have woken up to poll. Try again
            continue;
        } else if (status <= 0) {
            // There is either an error or the timeout is elapsed: return
            return status;
        }
        /* An event was found and pumped into the SDL events queue. Continue the loop
          to let SDL_PeepEvents pick it up .*/
    }
    return 0;
}
References _this, NULL, SDL_EVENT_FIRST, SDL_EVENT_LAST, SDL_events_get_polling_interval(), SDL_GETEVENT, SDL_GetTicksNS(), SDL_MAX_SINT64, SDL_min, SDL_PeepEvents(), SDL_PumpEventsInternal(), and SDL_SetAtomicPointer().
Referenced by SDL_WaitEventTimeoutNS().
SDL_WaitEventTimeoutNS()
bool SDL_WaitEventTimeoutNS (SDL_Event * event, Sint64 timeoutNS)
{
    Uint64 start, expiration;
    bool include_sentinel = (timeoutNS == 0);
    int result;
    if (timeoutNS > 0) {
        start = SDL_GetTicksNS();
        expiration = start + timeoutNS;
    } else {
        start = 0;
        expiration = 0;
    }
    // If there isn't a poll sentinel event pending, pump events and add one
    if (SDL_GetAtomicInt(&SDL_sentinel_pending) == 0) {
        SDL_PumpEventsInternal(true);
    }
    // First check for existing events
    result = SDL_PeepEventsInternal(event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST, include_sentinel);
    if (result < 0) {
        return false;
    }
    if (include_sentinel) {
        if (event) {
            if (event->type == SDL_EVENT_POLL_SENTINEL) {
                // Reached the end of a poll cycle, and not willing to wait
                return false;
            }
        } else {
            // Need to peek the next event to check for sentinel
            SDL_Event dummy;
            if (SDL_PeepEventsInternal(&dummy, 1, SDL_PEEKEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST, true) &&
                dummy.type == SDL_EVENT_POLL_SENTINEL) {
                SDL_PeepEventsInternal(&dummy, 1, SDL_GETEVENT, SDL_EVENT_POLL_SENTINEL, SDL_EVENT_POLL_SENTINEL, true);
                // Reached the end of a poll cycle, and not willing to wait
                return false;
            }
        }
    }
    if (result == 0) {
        if (timeoutNS == 0) {
            // No events available, and not willing to wait
            return false;
        }
    } else {
        // Has existing events
        return true;
    }
    // We should have completely handled timeoutNS == 0 above
    SDL_assert(timeoutNS != 0);
#ifdef SDL_PLATFORM_ANDROID
    for (;;) {
        if (SDL_PeepEvents(event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST) > 0) {
            return true;
        }
        Uint64 delay = -1;
        if (timeoutNS > 0) {
            Uint64 now = SDL_GetTicksNS();
            if (now >= expiration) {
                // Timeout expired and no events
                return false;
            }
            delay = (expiration - now);
        }
        Android_PumpEvents(delay);
    }
#else
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (_this && _this->WaitEventTimeout && _this->SendWakeupEvent) {
        // Look if a shown window is available to send the wakeup event.
        SDL_Window *wakeup_window = SDL_find_active_window(_this);
        if (wakeup_window) {
            result = SDL_WaitEventTimeout_Device(_this, wakeup_window, event, start, timeoutNS);
            if (result > 0) {
                return true;
            } else if (result == 0) {
                return false;
            } else {
                /* There may be implementation-defined conditions where the backend cannot
                 * reliably wait for the next event. If that happens, fall back to polling.
                 */
            }
        }
    }
    for (;;) {
        SDL_PumpEventsInternal(true);
        if (SDL_PeepEvents(event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST) > 0) {
            return true;
        }
        Uint64 delay = EVENT_POLL_INTERVAL_NS;
        if (timeoutNS > 0) {
            Uint64 now = SDL_GetTicksNS();
            if (now >= expiration) {
                // Timeout expired and no events
                return false;
            }
            delay = SDL_min((expiration - now), delay);
        }
        SDL_DelayNS(delay);
    }
#endif // SDL_PLATFORM_ANDROID
}
References _this, Android_PumpEvents(), EVENT_POLL_INTERVAL_NS, SDL_assert, SDL_DelayNS(), SDL_EVENT_FIRST, SDL_EVENT_LAST, SDL_EVENT_POLL_SENTINEL, SDL_find_active_window(), SDL_GetAtomicInt(), SDL_GETEVENT, SDL_GetTicksNS(), SDL_GetVideoDevice(), SDL_min, SDL_PEEKEVENT, SDL_PeepEvents(), SDL_PeepEventsInternal(), SDL_PumpEventsInternal(), SDL_sentinel_pending, SDL_WaitEventTimeout_Device(), and SDL_Event::type.
Referenced by SDL_PollEvent(), SDL_WaitEvent(), and SDL_WaitEventTimeout().
Variable Documentation
active
bool active
Referenced by SDL_hid_ble_scan(), SDL_InsertTrayEntryAt(), and SDL_BWin::WindowActivated().
count
SDL_AtomicInt count
Referenced by SDL_BLooper::_HandleKey(), build_locales_from_csv_string(), get_appindicator_id(), GetAudioDevices(), GetMouseClickState(), glColorSubTable(), glCopyTexSubImage3D(), glCreateShaderProgramv(), glDebugMessageControl(), glDeleteSamplers(), glDrawArrays(), glDrawArraysInstanced(), glDrawElements(), glDrawElements(), glDrawElementsBaseVertex(), glDrawElementsInstanced(), glDrawElementsInstancedBaseVertex(), glDrawRangeElements(), glDrawRangeElements(), glDrawRangeElementsBaseVertex(), glGenSamplers(), glGetAttachedShaders(), glGetDebugMessageLog(), glGetInternalformativ(), glGetSeparableFilter(), glGetSynciv(), glPopName(), glProgramUniform1fv(), glProgramUniform1iv(), glProgramUniform1uiv(), glProgramUniform2fv(), glProgramUniform2iv(), glProgramUniform2uiv(), glProgramUniform3fv(), glProgramUniform3iv(), glProgramUniform3uiv(), glProgramUniform4fv(), glProgramUniform4iv(), glProgramUniform4uiv(), glProgramUniformMatrix2fv(), glProgramUniformMatrix2x3fv(), glProgramUniformMatrix2x4fv(), glProgramUniformMatrix3fv(), glProgramUniformMatrix3x2fv(), glProgramUniformMatrix3x4fv(), glProgramUniformMatrix4fv(), glProgramUniformMatrix4x2fv(), glProgramUniformMatrix4x3fv(), glShaderBinary(), glShaderBinary(), glShaderSource(), glTransformFeedbackVaryings(), glUniform1fv(), glUniform1iv(), glUniform1uiv(), glUniform2fv(), glUniform2iv(), glUniform2uiv(), glUniform3fv(), glUniform3iv(), glUniform3uiv(), glUniform4fv(), glUniform4iv(), glUniform4uiv(), glUniformMatrix2fv(), glUniformMatrix2x3fv(), glUniformMatrix2x4fv(), glUniformMatrix3fv(), glUniformMatrix3x2fv(), glUniformMatrix3x4fv(), glUniformMatrix4fv(), glUniformMatrix4x2fv(), glUniformMatrix4x3fv(), new_tmp_filename(), NGAGE_DrawLines(), NGAGE_DrawPoints(), NGAGE_FillRects(), pthread_barrier_init(), QueueCmdDrawLines(), QueueCmdDrawPoints(), QueueCmdFillRects(), RenderLinesWithRectsF(), RenderPointsWithRects(), SDL_BlendFillRects(), SDL_BlendLines(), SDL_BlendPoints(), SDL_CaseFoldUnicode(), SDL_CleanupTrays(), SDL_CreateThreadBarrier(), SDL_DispatchEventWatchList(), SDL_DispatchMainCallbackEvents(), SDL_DrawLines(), SDL_DrawPoints(), SDL_ENCLOSEPOINTS(), SDL_FillSurfaceRects(), SDL_GetAudioDeviceChannelMap(), SDL_GetAudioPlaybackDevices(), SDL_GetAudioRecordingDevices(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamInputChannelMap(), SDL_GetAudioStreamOutputChannelMap(), SDL_GetCameras(), SDL_GetCameraSupportedFormats(), SDL_GetDisplays(), SDL_GetFullscreenDisplayModes(), SDL_GetGamepadBindings(), SDL_GetGamepadMappings(), SDL_GetGamepads(), SDL_GetHaptics(), SDL_GetJoysticks(), SDL_GetKeyboards(), SDL_GetMice(), SDL_GetObjects(), SDL_GetPreferredLocales(), SDL_GetRectEnclosingPoints(), SDL_GetRectEnclosingPointsFloat(), SDL_GetSensors(), SDL_GetSurfaceImages(), SDL_GetTouchDevices(), SDL_GetTouchFingers(), SDL_GetTrayEntries(), SDL_GetWindows(), SDL_GlobDirectory(), SDL_GlobStorageDirectory(), SDL_InternalGlobDirectory(), SDL_RemoveEventWatchList(), SDL_RenderFillRects(), SDL_RenderGeometryRaw(), SDL_RenderLines(), SDL_RenderPoints(), SDL_RenderRects(), SDL_ScanLong(), SDL_ScanLongLong(), SDL_ScanLongW(), SDL_ScanUnsignedLong(), SDL_ScanUnsignedLongLong(), SDL_ScanUnsignedLongLongInternal(), SDL_ScanUnsignedLongLongInternalW(), SDL_SYS_GetPreferredLocales(), SDL_vsscanf(), SDL_Vulkan_GetInstanceExtensions(), and WaveLoad().
free
SDL_EventEntry* free
head
SDL_EventEntry* head
Referenced by SDL_ListAdd(), SDL_ListClear(), SDL_ListPop(), and SDL_ListRemove().
lock
SDL_Mutex* lock
Referenced by SDL_BindAudioStreams(), SDL_LockSpinlock(), SDL_StopEventLoop(), SDL_TryLockSpinlock(), and SDL_UnlockSpinlock().
max_events_seen
int max_events_seen
SDL_disabled_events
SDL_DisabledEventBlock* SDL_disabled_events[256] static
Referenced by SDL_EventEnabled(), SDL_SetEventEnabled(), and SDL_StopEventLoop().
SDL_event_watchers
SDL_EventWatchList SDL_event_watchers static
Referenced by SDL_AddEventWatch(), SDL_CallEventWatchers(), SDL_GetEventFilter(), SDL_RemoveEventWatch(), SDL_SetEventFilter(), SDL_StartEventLoop(), and SDL_StopEventLoop().
SDL_EventLoggingVerbosity
int SDL_EventLoggingVerbosity = 0 static
Verbosity of logged events as defined in SDL_HINT_EVENT_LOGGING:
0: (default) no logging
1: logging of most events
2: as above, plus mouse, pen, and finger motion
Referenced by SDL_AddEvent(), SDL_EventLoggingChanged(), SDL_LogEvent(), and SDL_SendAppEvent().
[struct]
struct { ... } SDL_EventQ
Referenced by SDL_AddEvent(), SDL_CutEvent(), SDL_FilterEvents(), SDL_FlushEvents(), SDL_HasEvents(), SDL_PeepEventsInternal(), SDL_SetEventFilter(), SDL_StartEventLoop(), and SDL_StopEventLoop().
SDL_last_event_id
Uint32 SDL_last_event_id = 0 static
Referenced by SDL_AddEvent().
SDL_main_callbacks_head
SDL_MainThreadCallbackEntry* SDL_main_callbacks_head static
Referenced by SDL_InitMainThreadCallbacks(), SDL_QuitMainThreadCallbacks(), SDL_RunMainThreadCallbacks(), and SDL_RunOnMainThread().
SDL_main_callbacks_lock
SDL_Mutex* SDL_main_callbacks_lock static
Referenced by SDL_InitMainThreadCallbacks(), SDL_QuitMainThreadCallbacks(), SDL_RunMainThreadCallbacks(), and SDL_RunOnMainThread().
SDL_main_callbacks_tail
SDL_MainThreadCallbackEntry* SDL_main_callbacks_tail static
Referenced by SDL_InitMainThreadCallbacks(), SDL_QuitMainThreadCallbacks(), SDL_RunMainThreadCallbacks(), and SDL_RunOnMainThread().
SDL_sentinel_pending
SDL_AtomicInt SDL_sentinel_pending static
Referenced by SDL_AddEvent(), SDL_CutEvent(), SDL_PeepEventsInternal(), SDL_PumpEventsInternal(), SDL_StopEventLoop(), and SDL_WaitEventTimeoutNS().
SDL_temporary_memory
SDL_TLSID SDL_temporary_memory static
Referenced by SDL_GetTemporaryMemoryState().
SDL_update_joysticks
bool SDL_update_joysticks = true static
Referenced by SDL_AutoUpdateJoysticksChanged(), SDL_events_get_polling_interval(), and SDL_PumpEventMaintenance().
SDL_update_sensors
bool SDL_update_sensors = true static
Referenced by SDL_AutoUpdateSensorsChanged(), SDL_events_get_polling_interval(), and SDL_PumpEventMaintenance().
SDL_userevents
SDL_AtomicInt SDL_userevents static
Referenced by SDL_RegisterEvents().
tail
SDL_EventEntry* tail
Referenced by SDL_AddTrackToAudioQueue().