SDL3: SDL-main/include/SDL3/SDL_stdinc.h File Reference
SDL_stdinc.h File Reference
#include <SDL3/SDL_platform_defines.h>
#include <stdarg.h>
#include <stdint.h>
#include <string.h>
#include <wchar.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define __bool_true_false_are_defined 1
#define bool unsigned char
#define false 0
#define SDL_arraysize(array)
#define SDL_COMPILE_TIME_ASSERT(name, x)
#define SDL_SIZE_MAX ((size_t) -1)
#define SDL_STRINGIFY_ARG(arg)
#define true 1
Cast operators
Use proper C++ casts when compiled as C++ to be compatible with the option -Wold-style-cast of GCC (and -Werror=old-style-cast in GCC 4.2 and above).
#define SDL_const_cast(type, expression)
#define SDL_FOURCC(A, B, C, D)
#define SDL_reinterpret_cast(type, expression)
#define SDL_SINT64_C(c)
#define SDL_static_cast(type, expression)
#define SDL_UINT64_C(c)
Functions
void * alloca (size_t)
Basic data types
#define SDL_MAX_SINT16 ((Sint16)0x7FFF) /* 32767 */
#define SDL_MAX_SINT32 ((Sint32)0x7FFFFFFF) /* 2147483647 */
#define SDL_MAX_SINT64 SDL_SINT64_C(0x7FFFFFFFFFFFFFFF) /* 9223372036854775807 */
#define SDL_MAX_SINT8 ((Sint8)0x7F) /* 127 */
#define SDL_MAX_TIME SDL_MAX_SINT64
#define SDL_MAX_UINT16 ((Uint16)0xFFFF) /* 65535 */
#define SDL_MAX_UINT32 ((Uint32)0xFFFFFFFFu) /* 4294967295 */
#define SDL_MAX_UINT64 SDL_UINT64_C(0xFFFFFFFFFFFFFFFF) /* 18446744073709551615 */
#define SDL_MAX_UINT8 ((Uint8)0xFF) /* 255 */
#define SDL_MIN_SINT16 ((Sint16)(~0x7FFF)) /* -32768 */
#define SDL_MIN_SINT32 ((Sint32)(~0x7FFFFFFF)) /* -2147483648 */
#define SDL_MIN_SINT64 ~SDL_SINT64_C(0x7FFFFFFFFFFFFFFF) /* -9223372036854775808 */
#define SDL_MIN_SINT8 ((Sint8)(~0x7F)) /* -128 */
#define SDL_MIN_TIME SDL_MIN_SINT64
#define SDL_MIN_UINT16 ((Uint16)0x0000) /* 0 */
#define SDL_MIN_UINT32 ((Uint32)0x00000000) /* 0 */
#define SDL_MIN_UINT64 SDL_UINT64_C(0x0000000000000000) /* 0 */
#define SDL_MIN_UINT8 ((Uint8)0x00) /* 0 */
typedef Sint64 SDL_Time
typedef int16_t Sint16
typedef int32_t Sint32
typedef int64_t Sint64
typedef int8_t Sint8
typedef uint16_t Uint16
typedef uint32_t Uint32
typedef uint64_t Uint64
typedef uint8_t Uint8
Floating-point constants
SDL_DECLSPEC int SDLCALL SDL_abs (int x)
SDL_DECLSPEC double SDLCALL SDL_acos (double x)
SDL_DECLSPEC float SDLCALL SDL_acosf (float x)
SDL_DECLSPEC SDL_MALLOC void *SDLCALL SDL_aligned_alloc (size_t alignment, size_t size)
SDL_DECLSPEC void SDLCALL SDL_aligned_free (void *mem)
SDL_DECLSPEC SDL_ALLOC_SIZE (2) void *SDLCALL SDL_realloc(void *mem
SDL_DECLSPEC SDL_MALLOC SDL_ALLOC_SIZE2 (1, 2) void *SDLCALL SDL_calloc(size_t nmemb
SDL_DECLSPEC double SDLCALL SDL_asin (double x)
SDL_DECLSPEC float SDLCALL SDL_asinf (float x)
SDL_DECLSPEC int SDLCALL SDL_asprintf (char **strp, const char *fmt,...)
SDL_DECLSPEC double SDLCALL SDL_atan (double x)
SDL_DECLSPEC double SDLCALL SDL_atan2 (double y, double x)
SDL_DECLSPEC float SDLCALL SDL_atan2f (float y, float x)
SDL_DECLSPEC float SDLCALL SDL_atanf (float x)
SDL_DECLSPEC double SDLCALL SDL_atof (const char *str)
SDL_DECLSPEC int SDLCALL SDL_atoi (const char *str)
SDL_DECLSPEC void *SDLCALL SDL_bsearch (const void *key, const void *base, size_t nmemb, size_t size, SDL_CompareCallback compare)
SDL_DECLSPEC void *SDLCALL SDL_bsearch_r (const void *key, const void *base, size_t nmemb, size_t size, SDL_CompareCallback_r compare, void *userdata)
typedef void *(SDLCALL * SDL_calloc_func) (size_t nmemb, size_t size)
SDL_DECLSPEC double SDLCALL SDL_ceil (double x)
SDL_DECLSPEC float SDLCALL SDL_ceilf (float x)
#define SDL_clamp(x, a, b)
typedef int(SDLCALL * SDL_CompareCallback) (const void *a, const void *b)
typedef int(SDLCALL * SDL_CompareCallback_r) (void *userdata, const void *a, const void *b)
#define SDL_copyp(dst, src)
SDL_DECLSPEC double SDLCALL SDL_copysign (double x, double y)
SDL_DECLSPEC float SDLCALL SDL_copysignf (float x, float y)
SDL_DECLSPEC double SDLCALL SDL_cos (double x)
SDL_DECLSPEC float SDLCALL SDL_cosf (float x)
SDL_DECLSPEC Uint16 SDLCALL SDL_crc16 (Uint16 crc, const void *data, size_t len)
SDL_DECLSPEC Uint32 SDLCALL SDL_crc32 (Uint32 crc, const void *data, size_t len)
SDL_DECLSPEC SDL_Environment *SDLCALL SDL_CreateEnvironment (unsigned char populated)
SDL_DECLSPEC void SDLCALL SDL_DestroyEnvironment (SDL_Environment *env)
typedef struct SDL_Environment SDL_Environment
SDL_DECLSPEC double SDLCALL SDL_exp (double x)
SDL_DECLSPEC float SDLCALL SDL_expf (float x)
SDL_DECLSPEC double SDLCALL SDL_fabs (double x)
SDL_DECLSPEC float SDLCALL SDL_fabsf (float x)
SDL_DECLSPEC double SDLCALL SDL_floor (double x)
SDL_DECLSPEC float SDLCALL SDL_floorf (float x)
#define SDL_FLT_EPSILON 1.1920928955078125e-07F /* 0x0.000002p0 */
SDL_DECLSPEC double SDLCALL SDL_fmod (double x, double y)
SDL_DECLSPEC float SDLCALL SDL_fmodf (float x, float y)
SDL_DECLSPEC void SDLCALL SDL_free (void *mem)
typedef void(SDLCALL * SDL_free_func) (void *mem)
typedef void(* SDL_FunctionPointer) (void)
SDL_DECLSPEC const char *SDLCALL SDL_getenv (const char *name)
SDL_DECLSPEC const char *SDLCALL SDL_getenv_unsafe (const char *name)
SDL_DECLSPEC SDL_Environment *SDLCALL SDL_GetEnvironment (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetEnvironmentVariable (SDL_Environment *env, const char *name)
SDL_DECLSPEC char **SDLCALL SDL_GetEnvironmentVariables (SDL_Environment *env)
SDL_DECLSPEC void SDLCALL SDL_GetMemoryFunctions (SDL_malloc_func *malloc_func, SDL_calloc_func *calloc_func, SDL_realloc_func *realloc_func, SDL_free_func *free_func)
SDL_DECLSPEC int SDLCALL SDL_GetNumAllocations (void)
SDL_DECLSPEC void SDLCALL SDL_GetOriginalMemoryFunctions (SDL_malloc_func *malloc_func, SDL_calloc_func *calloc_func, SDL_realloc_func *realloc_func, SDL_free_func *free_func)
SDL_DECLSPEC size_t SDLCALL SDL_iconv (SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft)
SDL_DECLSPEC int SDLCALL SDL_iconv_close (SDL_iconv_t cd)
#define SDL_ICONV_E2BIG (size_t)-2
#define SDL_ICONV_EILSEQ (size_t)-3
#define SDL_ICONV_EINVAL (size_t)-4
#define SDL_ICONV_ERROR (size_t)-1
SDL_DECLSPEC SDL_iconv_t SDLCALL SDL_iconv_open (const char *tocode, const char *fromcode)
SDL_DECLSPEC char *SDLCALL SDL_iconv_string (const char *tocode, const char *fromcode, const char *inbuf, size_t inbytesleft)
typedef struct SDL_iconv_data_t * SDL_iconv_t
#define SDL_iconv_utf8_locale(S)
#define SDL_iconv_utf8_ucs2(S)
#define SDL_iconv_utf8_ucs4(S)
#define SDL_iconv_wchar_utf8(S)
#define SDL_IN_BYTECAP(x)
#define SDL_INIT_INTERFACE(iface)
#define SDL_INOUT_Z_CAP(x)
#define SDL_INVALID_UNICODE_CODEPOINT 0xFFFD
SDL_DECLSPEC int SDLCALL SDL_isalnum (int x)
SDL_DECLSPEC int SDLCALL SDL_isalpha (int x)
SDL_DECLSPEC int SDLCALL SDL_isblank (int x)
SDL_DECLSPEC int SDLCALL SDL_iscntrl (int x)
SDL_DECLSPEC int SDLCALL SDL_isdigit (int x)
SDL_DECLSPEC int SDLCALL SDL_isgraph (int x)
SDL_DECLSPEC int SDLCALL SDL_isinf (double x)
SDL_DECLSPEC int SDLCALL SDL_isinff (float x)
SDL_DECLSPEC int SDLCALL SDL_islower (int x)
SDL_DECLSPEC int SDLCALL SDL_isnan (double x)
SDL_DECLSPEC int SDLCALL SDL_isnanf (float x)
SDL_DECLSPEC int SDLCALL SDL_isprint (int x)
SDL_DECLSPEC int SDLCALL SDL_ispunct (int x)
SDL_DECLSPEC int SDLCALL SDL_isspace (int x)
SDL_DECLSPEC int SDLCALL SDL_isupper (int x)
SDL_DECLSPEC int SDLCALL SDL_isxdigit (int x)
SDL_DECLSPEC char *SDLCALL SDL_itoa (int value, char *str, int radix)
SDL_DECLSPEC char *SDLCALL SDL_lltoa (long long value, char *str, int radix)
SDL_DECLSPEC double SDLCALL SDL_log (double x)
SDL_DECLSPEC double SDLCALL SDL_log10 (double x)
SDL_DECLSPEC float SDLCALL SDL_log10f (float x)
SDL_DECLSPEC float SDLCALL SDL_logf (float x)
SDL_DECLSPEC long SDLCALL SDL_lround (double x)
SDL_DECLSPEC long SDLCALL SDL_lroundf (float x)
SDL_DECLSPEC char *SDLCALL SDL_ltoa (long value, char *str, int radix)
SDL_DECLSPEC SDL_MALLOC void *SDLCALL SDL_malloc (size_t size)
typedef void *(SDLCALL * SDL_malloc_func) (size_t size)
#define SDL_max(x, y)
SDL_DECLSPEC int SDLCALL SDL_memcmp (const void *s1, const void *s2, size_t len)
SDL_DECLSPEC void *SDLCALL SDL_memcpy (void *dst, const void *src, size_t len)
#define SDL_memcpy memcpy
SDL_DECLSPEC void *SDLCALL SDL_memmove (void *dst, const void *src, size_t len)
#define SDL_memmove memmove
SDL_DECLSPEC void *SDLCALL SDL_memset (void *dst, int c, size_t len)
#define SDL_memset memset
SDL_DECLSPEC void *SDLCALL SDL_memset4 (void *dst, Uint32 val, size_t dwords)
#define SDL_min(x, y)
SDL_DECLSPEC double SDLCALL SDL_modf (double x, double *y)
SDL_DECLSPEC float SDLCALL SDL_modff (float x, float *y)
SDL_DECLSPEC Uint32 SDLCALL SDL_murmur3_32 (const void *data, size_t len, Uint32 seed)
#define SDL_OUT_BYTECAP(x)
#define SDL_OUT_CAP(x)
#define SDL_OUT_Z_BYTECAP(x)
#define SDL_OUT_Z_CAP(x)
#define SDL_PI_D 3.141592653589793238462643383279502884
#define SDL_PI_F 3.141592653589793238462643383279502884F
SDL_DECLSPEC double SDLCALL SDL_pow (double x, double y)
SDL_DECLSPEC float SDLCALL SDL_powf (float x, float y)
#define SDL_PRILL_PREFIX "ll"
#define SDL_PRILLd SDL_PRILL_PREFIX "d"
#define SDL_PRILLu SDL_PRILL_PREFIX "u"
#define SDL_PRILLX SDL_PRILL_PREFIX "X"
#define SDL_PRILLx SDL_PRILL_PREFIX "x"
#define SDL_PRINTF_FORMAT_STRING
#define SDL_PRINTF_VARARG_FUNC(fmtargnumber)
#define SDL_PRINTF_VARARG_FUNCV(fmtargnumber)
#define SDL_PRIs32 "d"
#define SDL_PRIs64 "lld"
#define SDL_PRIu32 "u"
#define SDL_PRIu64 "llu"
#define SDL_PRIX32 "X"
#define SDL_PRIx32 "x"
#define SDL_PRIX64 "llX"
#define SDL_PRIx64 "llx"
SDL_DECLSPEC void SDLCALL SDL_qsort (void *base, size_t nmemb, size_t size, SDL_CompareCallback compare)
SDL_DECLSPEC void SDLCALL SDL_qsort_r (void *base, size_t nmemb, size_t size, SDL_CompareCallback_r compare, void *userdata)
SDL_DECLSPEC Sint32 SDLCALL SDL_rand (Sint32 n)
SDL_DECLSPEC Uint32 SDLCALL SDL_rand_bits (void)
SDL_DECLSPEC Uint32 SDLCALL SDL_rand_bits_r (Uint64 *state)
SDL_DECLSPEC Sint32 SDLCALL SDL_rand_r (Uint64 *state, Sint32 n)
SDL_DECLSPEC float SDLCALL SDL_randf (void)
SDL_DECLSPEC float SDLCALL SDL_randf_r (Uint64 *state)
typedef void *(SDLCALL * SDL_realloc_func) (void *mem, size_t size)
SDL_DECLSPEC double SDLCALL SDL_round (double x)
SDL_DECLSPEC float SDLCALL SDL_roundf (float x)
SDL_DECLSPEC double SDLCALL SDL_scalbn (double x, int n)
SDL_DECLSPEC float SDLCALL SDL_scalbnf (float x, int n)
#define SDL_SCANF_FORMAT_STRING
#define SDL_SCANF_VARARG_FUNC(fmtargnumber)
#define SDL_SCANF_VARARG_FUNCV(fmtargnumber)
SDL_DECLSPEC int SDLCALL SDL_setenv_unsafe (const char *name, const char *value, int overwrite)
SDL_DECLSPEC unsigned char SDLCALL SDL_SetEnvironmentVariable (SDL_Environment *env, const char *name, const char *value, unsigned char overwrite)
SDL_DECLSPEC unsigned char SDLCALL SDL_SetMemoryFunctions (SDL_malloc_func malloc_func, SDL_calloc_func calloc_func, SDL_realloc_func realloc_func, SDL_free_func free_func)
SDL_DECLSPEC double SDLCALL SDL_sin (double x)
SDL_DECLSPEC float SDLCALL SDL_sinf (float x)
SDL_FORCE_INLINE unsigned char SDL_size_add_check_overflow (size_t a, size_t b, size_t *ret)
SDL_FORCE_INLINE unsigned char SDL_size_mul_check_overflow (size_t a, size_t b, size_t *ret)
SDL_DECLSPEC int SDLCALL SDL_snprintf (char *text, size_t maxlen, const char *fmt,...)
SDL_DECLSPEC double SDLCALL SDL_sqrt (double x)
SDL_DECLSPEC float SDLCALL SDL_sqrtf (float x)
SDL_DECLSPEC void SDLCALL SDL_srand (Uint64 seed)
SDL_DECLSPEC int SDLCALL SDL_sscanf (const char *text, const char *fmt,...)
#define SDL_stack_alloc(type, count)
#define SDL_stack_free(data)
SDL_DECLSPEC Uint32 SDLCALL SDL_StepBackUTF8 (const char *start, const char **pstr)
SDL_DECLSPEC Uint32 SDLCALL SDL_StepUTF8 (const char **pstr, size_t *pslen)
SDL_DECLSPEC int SDLCALL SDL_strcasecmp (const char *str1, const char *str2)
SDL_DECLSPEC char *SDLCALL SDL_strcasestr (const char *haystack, const char *needle)
SDL_DECLSPEC char *SDLCALL SDL_strchr (const char *str, int c)
SDL_DECLSPEC int SDLCALL SDL_strcmp (const char *str1, const char *str2)
SDL_DECLSPEC SDL_MALLOC char *SDLCALL SDL_strdup (const char *str)
SDL_DECLSPEC size_t SDLCALL SDL_strlcat (char *dst, const char *src, size_t maxlen)
SDL_DECLSPEC size_t SDLCALL SDL_strlcpy (char *dst, const char *src, size_t maxlen)
SDL_DECLSPEC size_t SDLCALL SDL_strlen (const char *str)
SDL_DECLSPEC char *SDLCALL SDL_strlwr (char *str)
SDL_DECLSPEC int SDLCALL SDL_strncasecmp (const char *str1, const char *str2, size_t maxlen)
SDL_DECLSPEC int SDLCALL SDL_strncmp (const char *str1, const char *str2, size_t maxlen)
SDL_DECLSPEC SDL_MALLOC char *SDLCALL SDL_strndup (const char *str, size_t maxlen)
SDL_DECLSPEC size_t SDLCALL SDL_strnlen (const char *str, size_t maxlen)
SDL_DECLSPEC char *SDLCALL SDL_strnstr (const char *haystack, const char *needle, size_t maxlen)
SDL_DECLSPEC char *SDLCALL SDL_strpbrk (const char *str, const char *breakset)
SDL_DECLSPEC char *SDLCALL SDL_strrchr (const char *str, int c)
SDL_DECLSPEC char *SDLCALL SDL_strrev (char *str)
SDL_DECLSPEC char *SDLCALL SDL_strstr (const char *haystack, const char *needle)
SDL_DECLSPEC double SDLCALL SDL_strtod (const char *str, char **endp)
SDL_DECLSPEC char *SDLCALL SDL_strtok_r (char *str, const char *delim, char **saveptr)
SDL_DECLSPEC long SDLCALL SDL_strtol (const char *str, char **endp, int base)
SDL_DECLSPEC long long SDLCALL SDL_strtoll (const char *str, char **endp, int base)
SDL_DECLSPEC unsigned long SDLCALL SDL_strtoul (const char *str, char **endp, int base)
SDL_DECLSPEC unsigned long long SDLCALL SDL_strtoull (const char *str, char **endp, int base)
SDL_DECLSPEC char *SDLCALL SDL_strupr (char *str)
SDL_DECLSPEC int SDLCALL SDL_swprintf (wchar_t *text, size_t maxlen, const wchar_t *fmt,...)
SDL_DECLSPEC double SDLCALL SDL_tan (double x)
SDL_DECLSPEC float SDLCALL SDL_tanf (float x)
SDL_DECLSPEC int SDLCALL SDL_tolower (int x)
SDL_DECLSPEC int SDLCALL SDL_toupper (int x)
SDL_DECLSPEC double SDLCALL SDL_trunc (double x)
SDL_DECLSPEC float SDLCALL SDL_truncf (float x)
SDL_DECLSPEC char *SDLCALL SDL_UCS4ToUTF8 (Uint32 codepoint, char *dst)
SDL_DECLSPEC char *SDLCALL SDL_uitoa (unsigned int value, char *str, int radix)
SDL_DECLSPEC char *SDLCALL SDL_ulltoa (unsigned long long value, char *str, int radix)
SDL_DECLSPEC char *SDLCALL SDL_ultoa (unsigned long value, char *str, int radix)
SDL_DECLSPEC int SDLCALL SDL_unsetenv_unsafe (const char *name)
SDL_DECLSPEC unsigned char SDLCALL SDL_UnsetEnvironmentVariable (SDL_Environment *env, const char *name)
SDL_DECLSPEC size_t SDLCALL SDL_utf8strlcpy (char *dst, const char *src, size_t dst_bytes)
SDL_DECLSPEC size_t SDLCALL SDL_utf8strlen (const char *str)
SDL_DECLSPEC size_t SDLCALL SDL_utf8strnlen (const char *str, size_t bytes)
SDL_DECLSPEC int SDLCALL SDL_vasprintf (char **strp, const char *fmt, va_list ap)
SDL_DECLSPEC int SDLCALL SDL_vsnprintf (char *text, size_t maxlen, const char *fmt, va_list ap)
SDL_DECLSPEC int SDLCALL SDL_vsscanf (const char *text, const char *fmt, va_list ap)
SDL_DECLSPEC int SDLCALL SDL_vswprintf (wchar_t *text, size_t maxlen, const wchar_t *fmt, va_list ap)
SDL_DECLSPEC int SDLCALL SDL_wcscasecmp (const wchar_t *str1, const wchar_t *str2)
SDL_DECLSPEC int SDLCALL SDL_wcscmp (const wchar_t *str1, const wchar_t *str2)
SDL_DECLSPEC wchar_t *SDLCALL SDL_wcsdup (const wchar_t *wstr)
SDL_DECLSPEC size_t SDLCALL SDL_wcslcat (wchar_t *dst, const wchar_t *src, size_t maxlen)
SDL_DECLSPEC size_t SDLCALL SDL_wcslcpy (wchar_t *dst, const wchar_t *src, size_t maxlen)
SDL_DECLSPEC size_t SDLCALL SDL_wcslen (const wchar_t *wstr)
SDL_DECLSPEC int SDLCALL SDL_wcsncasecmp (const wchar_t *str1, const wchar_t *str2, size_t maxlen)
SDL_DECLSPEC int SDLCALL SDL_wcsncmp (const wchar_t *str1, const wchar_t *str2, size_t maxlen)
SDL_DECLSPEC size_t SDLCALL SDL_wcsnlen (const wchar_t *wstr, size_t maxlen)
SDL_DECLSPEC wchar_t *SDLCALL SDL_wcsnstr (const wchar_t *haystack, const wchar_t *needle, size_t maxlen)
SDL_DECLSPEC wchar_t *SDLCALL SDL_wcsstr (const wchar_t *haystack, const wchar_t *needle)
SDL_DECLSPEC long SDLCALL SDL_wcstol (const wchar_t *str, wchar_t **endp, int base)
#define SDL_WPRINTF_VARARG_FUNC(fmtargnumber)
#define SDL_WPRINTF_VARARG_FUNCV(fmtargnumber)
#define SDL_zero(x)
#define SDL_zeroa(x)
#define SDL_zerop(x)
SDL_DECLSPEC SDL_MALLOC size_t size
Macro Definition Documentation
__bool_true_false_are_defined
#define __bool_true_false_are_defined 1
bool
#define bool unsigned char
CategoryStdinc
SDL provides its own implementation of some of the most important C runtime functions.
Using these functions allows an app to have access to common C functionality without depending on a specific C runtime (or a C runtime at all). More importantly, the SDL implementations work identically across platforms, so apps can avoid surprises like snprintf() behaving differently between Windows and Linux builds, or itoa() only existing on some platforms.
For many of the most common functions, like SDL_memcpy, SDL might just call through to the usual C runtime behind the scenes, if it makes sense to do so (if it's faster and always available/reliable on a given platform), reducing library size and offering the most optimized option.
SDL also offers other C-runtime-adjacent functionality in this header that either isn't, strictly speaking, part of any C runtime standards, like SDL_crc32() and SDL_reinterpret_cast, etc. It also offers a few better options, like SDL_strlcpy(), which functions as a safer form of strcpy().
Referenced by SDL_IsGamepad().
false
#define false 0
Referenced by SDL_CameraThreadIterate().
SDL_arraysize
#define SDL_arraysize (array)
Value:
(sizeof(array)/sizeof(array[0]))
The number of elements in a static array.
This will compile but return incorrect results for a pointer to an array; it has to be an array the compiler knows the size of.
This macro looks like it double-evaluates the argument, but it does so inside of sizeof, so there are no side-effects here, as expressions do not actually run any code in these cases.
Since
This macro is available since SDL 3.2.0.
Referenced by __kernel_rem_pio2(), AsyncFileModeValid(), AttemptSensorFusion(), CaseFoldUtf8String(), CleanupLogPrefixes(), ClosePhysicalCamera(), ConvertAudio(), handleKeyboardEvent(), InterleaveAudioChannels(), IOS_MFIJoystickUpdate(), ParseLogCategory(), ParseLogPriorities(), SDL_AddGamepadMappingsFromIO(), SDL_CreateAudioTrack(), SDL_CreateDeviceName(), SDL_DispatchMainCallbackEvents(), SDL_GamepadEventsEnabled(), SDL_GamepadSensorWatcher(), SDL_GetDefaultScancodeFromKey(), SDL_GetDriverAndJoystickIndex(), SDL_GetDriverAndSensorIndex(), SDL_GetEventDescription(), SDL_GetGamepadAxisFromString(), SDL_GetGamepadSensorData(), SDL_GetGamepadTypeFromString(), SDL_GetJoysticks(), SDL_GetKeyFromName(), SDL_GetKeyName(), SDL_GetLogPriority(), SDL_GetNumCameraDrivers(), SDL_GetNumGPUDrivers(), SDL_GetNumRenderDrivers(), SDL_GetPowerInfo(), SDL_GetScancodeFromName(), SDL_GetSensorData(), SDL_GetSensors(), SDL_GetTextMimeTypes(), SDL_GetUserFolder(), SDL_GetWindowFlagProperties(), SDL_HasJoystick(), SDL_iconv_open(), SDL_InitJoysticks(), SDL_InitSensors(), SDL_InitWindowEventWatch(), SDL_JoystickEventsEnabled(), SDL_JoystickHandledByAnotherDriver(), SDL_LogOutput(), SDL_PrepareCameraSurfaces(), SDL_PrivateGetGamepadButtonFromString(), SDL_PromptAssertion(), SDL_QuitFilesystem(), SDL_QuitJoysticks(), SDL_QuitSensors(), SDL_QuitWindowEventWatch(), SDL_ResetLogPriorities(), SDL_SendJoystickSensor(), SDL_SendPenButton(), SDL_SendSensorUpdate(), SDL_SetGamepadEventsEnabled(), SDL_SetJoystickEventsEnabled(), SDL_SetLogPriorities(), SDL_SetLogPriority(), SDL_StopEventLoop(), SDL_UpdateJoysticks(), SDL_UpdateSensors(), SDL_WasInit(), Translate_to_keycode(), updateKeyboard(), and WaveGetFormatGUIDEncoding().
SDL_clamp
#define SDL_clamp (x, a, b)
Value:
(((x) < (a)) ? (a) : (((x) > (b)) ? (b) : (x)))
Return a value clamped to a range.
If x is outside the range a values between a and b, the returned value will be a or b as appropriate. Otherwise, x is returned.
This macro will produce incorrect results if b is less than a.
This is a helper macro that might be more clear than writing out the comparisons directly, and works with any type that can be compared with the < and > operators. However, it double-evaluates all its parameters, so do not use expressions with side-effects here.
Parameters
x the value to compare.
a the low end value.
b the high end value.
Returns
x, clamped between a and b.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by PrepareThreadpool(), SDL_Blit_Slow_Float(), SDL_ClearSurface(), SDL_DateTimeToTime(), SDL_EventLoggingChanged(), SDL_GetTextureAlphaMod(), SDL_GetTextureColorMod(), SDL_PQfromNits(), SDL_SetGPUAllowedFramesInFlight(), SDL_SetWindowProgressValue(), SDL_TimeFromWindows(), SDL_WriteSurfacePixelFloat(), and WriteFloatPixel().
SDL_COMPILE_TIME_ASSERT
#define SDL_COMPILE_TIME_ASSERT (name, x)
Value:
       typedef int SDL_compile_time_assert_ ## name[(x) * 2 - 1]
#define SDL_COMPILE_TIME_ASSERT(name, x)               \
       typedef int SDL_compile_time_assert_ ## name[(x) * 2 - 1]
Referenced by SDL_AddAtomicInt(), SDL_CompareAndSwapAtomicInt(), SDL_CompareAndSwapAtomicU32(), SDL_GetAtomicInt(), SDL_GetAtomicU32(), SDL_GetEventDescription(), SDL_powerof2(), SDL_SetAtomicInt(), SDL_SetAtomicU32(), and SDL_TryLockSpinlock().
SDL_const_cast
#define SDL_const_cast (type, expression)
Value:
((type)(expression))
Referenced by SDL_SetTLS(), SDL_strchr(), SDL_strnstr(), SDL_strrchr(), SDL_strstr(), and SDL_wcsstr().
SDL_copyp
#define SDL_copyp (dst, src)
Value:
    { SDL_COMPILE_TIME_ASSERT(SDL_copyp, sizeof (*(dst)) == sizeof (*(src))); }             \
    SDL_memcpy((dst), (src), sizeof(*(src)))
A macro to copy memory between objects, with basic type checking.
SDL_memcpy and SDL_memmove do not care where you copy memory to and from, which can lead to bugs. This macro aims to avoid most of those bugs by making sure that the source and destination are both pointers to objects that are the same size. It does not check that the objects are the same type, just that the copy will not overflow either object.
The size check happens at compile time, and the compiler will throw an error if the objects are different sizes.
Generally this is intended to copy a single object, not an array.
This macro looks like it double-evaluates its parameters, but the extras them are in sizeof sections, which generate no code nor side-effects.
Parameters
dst a pointer to the destination object. Must not be NULL.
src a pointer to the source object. Must not be NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
#define SDL_copyp(dst, src)                                                                 \
    { SDL_COMPILE_TIME_ASSERT(SDL_copyp, sizeof (*(dst)) == sizeof (*(src))); }             \
    SDL_memcpy((dst), (src), sizeof(*(src)))
Referenced by AddVirtualGamepadInfo(), ChooseBestCameraSpec(), ClosePhysicalAudioDevice(), CopyOneProperty(), CreatePhysicalAudioDevice(), NextAudioStreamIter(), OpenPhysicalAudioDevice(), QueueCmdSetClipRect(), QueueCmdSetViewport(), SDL_AddEvent(), SDL_AddPenDevice(), SDL_AddVideoDisplay(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_BindAudioStreams(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_CheckWindowSafeAreaChanged(), SDL_CreateAudioTrack(), SDL_CreateCondition(), SDL_CreateRWLock(), SDL_GetAudioDeviceFormat(), SDL_GetAudioStreamFormat(), SDL_GetCameraFormat(), SDL_GetClosestFullscreenDisplayMode(), SDL_GetGamepadBindings(), SDL_GetRenderClipRect(), SDL_GetRenderLogicalPresentationRect(), SDL_GetTextInputArea(), SDL_GetTouchFingers(), SDL_GetWindowSafeArea(), SDL_NextAudioQueueIter(), SDL_OpenAudioDeviceStream(), SDL_OpenCamera(), SDL_OpenIO(), SDL_OpenStorage(), SDL_PeepEventsInternal(), SDL_PlaybackAudioThreadIterate(), SDL_PutAudioStreamPlanarData(), SDL_RecordingAudioThreadIterate(), SDL_RenderLogicalPresentation(), SDL_RenderTextureTiled_Iterate(), SDL_SetAudioStreamFormat(), SDL_SetCurrentDisplayMode(), SDL_SetDesktopDisplayMode(), SDL_SetDisplayHDRProperties(), SDL_SetRenderClipRect(), SDL_SetRenderViewport(), SDL_SetTextInputArea(), SDL_SetWindowFullscreen(), SDL_SetWindowFullscreenMode(), SDL_SetWindowHDRProperties(), SDL_SetWindowResizable(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), SDL_TransferSysWMMemoryToEvent(), SDL_UpdateDesktopBounds(), UpdateAudioStreamFormatsPhysical(), and UpdateAudioStreamInputSpec().
SDL_FLT_EPSILON
#define SDL_FLT_EPSILON 1.1920928955078125e-07F /* 0x0.000002p0 */
Epsilon constant, used for comparing floating-point numbers.
Equals by default to platform-defined FLT_EPSILON, or 1.1920928955078125e-07F if that's not available.
Since
This macro is available since SDL 3.2.0.
Referenced by BesselI0(), and SDL_RectsEqualFloat().
SDL_FOURCC
#define SDL_FOURCC (A, B, C, D)
Value:
    ((SDL_static_cast(Uint32, SDL_static_cast(Uint8, (A))) << 0) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (B))) << 8) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (C))) << 16) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (D))) << 24))
Define a four character code as a Uint32.
Parameters
A the first ASCII character.
B the second ASCII character.
C the third ASCII character.
D the fourth ASCII character.
Returns
the four characters converted into a Uint32, one character per-byte.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
#define SDL_FOURCC(A, B, C, D) \
    ((SDL_static_cast(Uint32, SDL_static_cast(Uint8, (A))) << 0) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (B))) << 8) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (C))) << 16) | \
     (SDL_static_cast(Uint32, SDL_static_cast(Uint8, (D))) << 24))
SDL_ICONV_E2BIG
#define SDL_ICONV_E2BIG (size_t)-2
Output buffer was too small.
Referenced by SDL_iconv(), and SDL_iconv_string().
SDL_ICONV_EILSEQ
#define SDL_ICONV_EILSEQ (size_t)-3
Invalid input sequence was encountered.
Referenced by SDL_iconv_string().
SDL_ICONV_EINVAL
#define SDL_ICONV_EINVAL (size_t)-4
Incomplete input sequence was encountered.
Referenced by SDL_iconv(), and SDL_iconv_string().
SDL_ICONV_ERROR
#define SDL_ICONV_ERROR (size_t)-1
Generic error. Check SDL_GetError()?
Referenced by SDL_iconv(), and SDL_iconv_string().
SDL_iconv_utf8_locale
#define SDL_iconv_utf8_locale (S)
Value:
SDL_iconv_string("", "UTF-8", S, SDL_strlen(S)+1)
Convert a UTF-8 string to the current locale's character encoding.
This is a helper macro that might be more clear than calling SDL_iconv_string directly. However, it double-evaluates its parameter, so do not use an expression with side-effects here.
Parameters
S the string to convert.
Returns
a new string, converted to the new encoding, or NULL on error.
Since
This macro is available since SDL 3.2.0.
SDL_iconv_utf8_ucs2
#define SDL_iconv_utf8_ucs2 (S)
Value:
(Uint16 *)SDL_iconv_string("UCS-2", "UTF-8", S, SDL_strlen(S)+1)
Convert a UTF-8 string to UCS-2.
This is a helper macro that might be more clear than calling SDL_iconv_string directly. However, it double-evaluates its parameter, so do not use an expression with side-effects here.
Parameters
S the string to convert.
Returns
a new string, converted to the new encoding, or NULL on error.
Since
This macro is available since SDL 3.2.0.
SDL_iconv_utf8_ucs4
#define SDL_iconv_utf8_ucs4 (S)
Value:
(Uint32 *)SDL_iconv_string("UCS-4", "UTF-8", S, SDL_strlen(S)+1)
Convert a UTF-8 string to UCS-4.
This is a helper macro that might be more clear than calling SDL_iconv_string directly. However, it double-evaluates its parameter, so do not use an expression with side-effects here.
Parameters
S the string to convert.
Returns
a new string, converted to the new encoding, or NULL on error.
Since
This macro is available since SDL 3.2.0.
SDL_iconv_wchar_utf8
#define SDL_iconv_wchar_utf8 (S)
Value:
SDL_iconv_string("UTF-8", "WCHAR_T", (char *)S, (SDL_wcslen(S)+1)*sizeof(wchar_t))
Convert a wchar_t string to UTF-8.
This is a helper macro that might be more clear than calling SDL_iconv_string directly. However, it double-evaluates its parameter, so do not use an expression with side-effects here.
Parameters
S the string to convert.
Returns
a new string, converted to the new encoding, or NULL on error.
Since
This macro is available since SDL 3.2.0.
Referenced by register_string_error_to_buffer(), and register_winapi_error_to_buffer().
SDL_IN_BYTECAP
#define SDL_IN_BYTECAP (x)
SDL_INIT_INTERFACE
#define SDL_INIT_INTERFACE (iface)
Value:
    do {                                        \
        SDL_zerop(iface);                       \
        (iface)->version = sizeof(*(iface));    \
    } while (0)
A macro to initialize an SDL interface.
This macro will initialize an SDL interface structure and should be called before you fill out the fields with your implementation.
You can use it like this:
SDL_IOStreamInterface iface;
SDL_INIT_INTERFACE(&iface);
// Fill in the interface function pointers with your implementation
iface.seek = ...
stream = SDL_OpenIO(&iface, NULL);
If you are using designated initializers, you can use the size of the interface as the version, e.g.
SDL_IOStreamInterface iface = {
    .version = sizeof(iface),
    .seek = ...
};
stream = SDL_OpenIO(&iface, NULL);
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
See also
SDL_IOStreamInterface
SDL_StorageInterface
SDL_VirtualJoystickDesc
#define SDL_INIT_INTERFACE(iface)               \
    do {                                        \
        SDL_zerop(iface);                       \
        (iface)->version = sizeof(*(iface));    \
    } while (0)
Referenced by SDL_IOFromConstMem(), SDL_IOFromDynamicMem(), SDL_IOFromFD(), SDL_IOFromFile(), and SDL_IOFromMem().
SDL_INOUT_Z_CAP
#define SDL_INOUT_Z_CAP (x)
SDL_INVALID_UNICODE_CODEPOINT
#define SDL_INVALID_UNICODE_CODEPOINT 0xFFFD
The Unicode REPLACEMENT CHARACTER codepoint.
SDL_StepUTF8() and SDL_StepBackUTF8() report this codepoint when they encounter a UTF-8 string with encoding errors.
This tends to render as something like a question mark in most places.
Since
This macro is available since SDL 3.2.0.
See also
SDL_StepBackUTF8
SDL_StepUTF8
Referenced by SDL_UCS4ToUTF8(), StepUTF32(), and StepUTF8().
SDL_max
#define SDL_max (x, y)
Value:
(((x) > (y)) ? (x) : (y))
Return the greater of two values.
This is a helper macro that might be more clear than writing out the comparisons directly, and works with any type that can be compared with the > operator. However, it double-evaluates both its parameters, so do not use expressions with side-effects here.
Parameters
x the first value to compare.
y the second value to compare.
Returns
the greater of x and y.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by CalculateMaxFrameSize(), CharacterMatchesSet(), ConstrainMousePosition(), GetAudioStreamDataInternal(), OpenPhysicalAudioDevice(), RenderLineBresenham(), RenderLinesWithRectsF(), SDL_AddVideoDisplay(), SDL_CalculateGPUTextureFormatSize(), SDL_GetCPUFeatures(), SDL_GetResamplerInputFrames(), SDL_GetSurfaceImage(), SDL_PQtoNits(), SDL_SendMouseButtonClicks(), SDL_SetDisplayHDRProperties(), SDL_SetWindowHDRProperties(), SDL_SetWindowMinimumSize(), SDL_UpdatedAudioDeviceFormat(), and TonemapChrome().
SDL_MAX_SINT16
#define SDL_MAX_SINT16 ((Sint16)0x7FFF) /* 32767 */
Referenced by SDL_MixAudio().
SDL_MAX_SINT32
#define SDL_MAX_SINT32 ((Sint32)0x7FFFFFFF) /* 2147483647 */
Referenced by GetAudioStreamAvailableFrames(), NextAudioStreamIter(), SDL_COMPILE_TIME_ASSERT(), SDL_MixAudio(), SDL_RECT_CAN_OVERFLOW(), STEAM_ReadStorageFile(), STEAM_WriteStorageFile(), and WaveReadFormat().
SDL_MAX_SINT64
#define SDL_MAX_SINT64 SDL_SINT64_C(0x7FFFFFFFFFFFFFFF) /* 9223372036854775807 */
Referenced by ResamplerAdd(), ResamplerMul(), SDL_events_get_polling_interval(), SDL_GetResamplerInputFrames(), SDL_GetResamplerOutputFrames(), SDL_WaitEventTimeout_Device(), WaveLoad(), and WaveNextChunk().
SDL_MAX_SINT8
#define SDL_MAX_SINT8 ((Sint8)0x7F) /* 127 */
Referenced by SDL_MixAudio().
SDL_MAX_TIME
#define SDL_MAX_TIME SDL_MAX_SINT64
Referenced by SDL_DateTimeToTime(), and SDL_TimeFromWindows().
SDL_MAX_UINT16
#define SDL_MAX_UINT16 ((Uint16)0xFFFF) /* 65535 */
Referenced by ReadFloatPixel(), SDL_BlitSurfaceUncheckedScaled(), SDL_StretchSurface(), and WriteFloatPixel().
SDL_MAX_UINT32
#define SDL_MAX_UINT32 ((Uint32)0xFFFFFFFFu) /* 4294967295 */
Referenced by IMA_ADPCM_Decode(), LAW_Decode(), MS_ADPCM_Decode(), PCM_ConvertSint24ToSint32(), PCM_Decode(), SDL_InitTicks(), and WaveLoad().
SDL_MAX_UINT64
#define SDL_MAX_UINT64 SDL_UINT64_C(0xFFFFFFFFFFFFFFFF) /* 18446744073709551615 */
Referenced by GENERIC_GetStorageSpaceRemaining().
SDL_MAX_UINT8
#define SDL_MAX_UINT8 ((Uint8)0xFF) /* 255 */
SDL_memcpy
#define SDL_memcpy memcpy
Referenced by SDL_BLooper::_HandleKey(), hid_buffer::assign(), build_locales_from_csv_string(), ConvertAudio(), CopyEnvStrings(), CreateCandidatesForEvent(), CreateIconFromSurface(), CreateStringFromJString(), CreateWStringFromWString(), float_to_half(), CHIDDevice::GetInput(), InterleaveAudioChannels(), mem_io(), memcpy(), NewByteArray(), PeekIntoAudioQueueFuture(), PeekIntoAudioQueuePast(), ReadFromAudioQueue(), CHIDDevice::ReadReport(), SDL_AddBasicVideoDisplay(), SDL_AddCamera(), SDL_AddFullscreenDisplayMode(), SDL_aligned_alloc(), SDL_aligned_free(), SDL_BlitCopy(), SDL_ChannelMapDup(), SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateAudioTrack(), SDL_CreateDeviceName(), SDL_CreateGPURenderState(), SDL_CreateHapticEffect(), SDL_DuplicatePixels(), SDL_FlipSurfaceHorizontal(), SDL_FlipSurfaceVertical(), SDL_GetCameraSupportedFormats(), SDL_GetFullscreenDisplayModes(), SDL_GetFullscreenModeMatch(), SDL_GetGamepadSensorData(), SDL_GetInternalClipboardData(), SDL_GetPenStatus(), SDL_GetSensorData(), SDL_GetSurfaceImages(), SDL_LoadVIDPIDListFromHints(), SDL_murmur3_32(), SDL_PlaybackAudioThreadIterate(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateGetGamepadNameFromMappingString(), SDL_PrivateMatchGamepadMappingForGUID(), SDL_PutAudioStreamData(), SDL_PutAudioStreamPlanarData(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_SendJoystickSensor(), SDL_SendSensorUpdate(), SDL_SetClipboardData(), SDL_SetGPURenderStateFragmentUniforms(), SDL_SetPaletteColors(), SDL_SetWindowMouseRect(), SDL_ShowMessageBox(), SDL_strdup(), SDL_strlcpy(), SDL_strndup(), SDL_UpdateHapticEffect(), SDL_utf8strlcpy(), SDL_wcsdup(), SDL_wcslcpy(), SDL_WriteSurfacePixel(), SDL_WriteSurfacePixelFloat(), UpdateAudioQueueHistory(), UpdateAudioStreamInputSpec(), and WriteToAudioTrack().
SDL_memmove
#define SDL_memmove memmove
Referenced by HIDAPI_UpdateDiscovery(), memmove(), SDL_AddCamera(), SDL_BlitCopy(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_CreateDeviceName(), SDL_DelFinger(), SDL_DelVideoDisplay(), SDL_DispatchEventWatchList(), SDL_GetGamepads(), SDL_IntPrecisionAdjust(), SDL_PrintFloat(), SDL_RemoveEventWatchList(), SDL_RemoveKeyboard(), SDL_RemoveMouse(), SDL_RemovePenDevice(), SDL_RemoveWindowRenderer(), and UpdateAudioQueueHistory().
SDL_memset
#define SDL_memset memset
Referenced by __kernel_rem_pio2(), CreateDebugTextAtlas(), DUMMYAUDIO_RecordDevice(), InterleaveAudioChannels(), Java_org_libsdl_app_HIDDeviceManager_HIDDeviceConnected(), memset(), PeekIntoAudioQueueFuture(), PS2AUDIO_OpenDevice(), SDL_aligned_alloc(), SDL_ClearHashTable(), SDL_CreatePalette(), SDL_CreateSurface(), SDL_CreateWindowTexture(), SDL_FillSurfaceRects(), SDL_GetInternalClipboardData(), SDL_GetPenStatus(), SDL_iconv_string(), SDL_IntPrecisionAdjust(), SDL_PlaybackAudioThreadIterate(), SDL_PostInitMouse(), SDL_PrintFloat(), SDL_PrintString(), SDL_PrivateLoadButtonMapping(), SDL_Quit(), SDL_ResetAudioQueueHistory(), SDL_SendJoystickSensor(), SDL_SendSensorUpdate(), SDL_SetJoystickIDForPlayerIndex(), SDL_StringToGUID(), windows_ShowFileDialog(), ZombieAcquireFrame(), and ZombieRecordDevice().
SDL_min
#define SDL_min (x, y)
Value:
(((x) < (y)) ? (x) : (y))
Return the lesser of two values.
This is a helper macro that might be more clear than writing out the comparisons directly, and works with any type that can be compared with the < operator. However, it double-evaluates both its parameters, so do not use expressions with side-effects here.
Parameters
x the first value to compare.
y the second value to compare.
Returns
the lesser of x and y.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by CalculateHashBucketsFromEstimate(), CharacterMatchesSet(), GetAudioStreamDataInternal(), PeekIntoAudioQueueFuture(), ReadFromAudioQueue(), RenderLinesWithRectsF(), SDL_events_get_polling_interval(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), SDL_GetAudioStreamQueued(), SDL_GetGamepadSensorData(), SDL_GetPenStatus(), SDL_GetSensorData(), SDL_PrintFloat(), SDL_PrintString(), SDL_PrivateSendMouseButton(), SDL_RumbleJoystick(), SDL_RumbleJoystickTriggers(), SDL_SendJoystickSensor(), SDL_SendSensorUpdate(), SDL_SetWindowMaximumSize(), SDL_strlcpy(), SDL_SYS_GetPreferredLocales_vista(), SDL_utf8strlcpy(), SDL_WaitEventTimeout_Device(), SDL_WaitEventTimeoutNS(), SDL_WasInit(), SDL_wcslcpy(), and WriteToAudioTrack().
SDL_MIN_SINT16
#define SDL_MIN_SINT16 ((Sint16)(~0x7FFF)) /* -32768 */
Referenced by SDL_MixAudio(), and SDL_OpenJoystick().
SDL_MIN_SINT32
#define SDL_MIN_SINT32 ((Sint32)(~0x7FFFFFFF)) /* -2147483648 */
Referenced by SDL_MixAudio(), and SDL_RECT_CAN_OVERFLOW().
SDL_MIN_SINT64
#define SDL_MIN_SINT64 ~SDL_SINT64_C(0x7FFFFFFFFFFFFFFF) /* -9223372036854775808 */
SDL_MIN_SINT8
#define SDL_MIN_SINT8 ((Sint8)(~0x7F)) /* -128 */
Referenced by SDL_MixAudio().
SDL_MIN_TIME
#define SDL_MIN_TIME SDL_MIN_SINT64
Referenced by SDL_DateTimeToTime(), and SDL_TimeFromWindows().
SDL_MIN_UINT16
#define SDL_MIN_UINT16 ((Uint16)0x0000) /* 0 */
SDL_MIN_UINT32
#define SDL_MIN_UINT32 ((Uint32)0x00000000) /* 0 */
SDL_MIN_UINT64
#define SDL_MIN_UINT64 SDL_UINT64_C(0x0000000000000000) /* 0 */
SDL_MIN_UINT8
#define SDL_MIN_UINT8 ((Uint8)0x00) /* 0 */
SDL_OUT_BYTECAP
#define SDL_OUT_BYTECAP (x)
SDL_OUT_CAP
#define SDL_OUT_CAP (x)
SDL_OUT_Z_BYTECAP
#define SDL_OUT_Z_BYTECAP (x)
SDL_OUT_Z_CAP
#define SDL_OUT_Z_CAP (x)
Referenced by SDL_snprintf(), SDL_swprintf(), SDL_vsnprintf(), and SDL_vswprintf().
SDL_PI_D
#define SDL_PI_D 3.141592653589793238462643383279502884
The value of Pi, as a double-precision floating point literal.
Since
This macro is available since SDL 3.2.0.
See also
SDL_PI_F pi (double)
Referenced by SDL_acos(), SDL_asin(), and SDL_RenderTextureRotated().
SDL_PI_F
#define SDL_PI_F 3.141592653589793238462643383279502884F
The value of Pi, as a single-precision floating point literal.
Since
This macro is available since SDL 3.2.0.
See also
SDL_PI_D pi (float)
Referenced by SincTable().
SDL_PRILL_PREFIX
#define SDL_PRILL_PREFIX "ll"
SDL_PRILLd
#define SDL_PRILLd SDL_PRILL_PREFIX "d"
SDL_PRILLu
#define SDL_PRILLu SDL_PRILL_PREFIX "u"
SDL_PRILLX
#define SDL_PRILLX SDL_PRILL_PREFIX "X"
SDL_PRILLx
#define SDL_PRILLx SDL_PRILL_PREFIX "x"
SDL_PRINTF_FORMAT_STRING
#define SDL_PRINTF_FORMAT_STRING
Referenced by SDL_asprintf(), SDL_asprintf(), SDL_IOprintf(), SDL_IOvprintf(), SDL_Log(), SDL_LogCritical(), SDL_LogDebug(), SDL_LogError(), SDL_LogInfo(), SDL_LogMessage(), SDL_LogMessageV(), SDL_LogTrace(), SDL_LogVerbose(), SDL_LogWarn(), SDL_RenderDebugTextFormat(), SDL_SetError(), SDL_SetErrorV(), SDL_snprintf(), SDL_snprintf(), SDL_swprintf(), SDL_swprintf(), SDL_vasprintf(), SDL_vasprintf(), SDL_vsnprintf(), SDL_vsnprintf(), SDL_vswprintf(), SDLTest_Assert(), SDLTest_AssertCheck(), SDLTest_AssertPass(), SDLTest_Log(), SDLTest_LogError(), and SDLTest_TextWindowAddText().
SDL_PRINTF_VARARG_FUNC
#define SDL_PRINTF_VARARG_FUNC (fmtargnumber)
Referenced by SDL_asprintf(), SDL_snprintf(), SDLTest_Assert(), SDLTest_AssertCheck(), SDLTest_AssertPass(), SDLTest_Log(), SDLTest_LogError(), and SDLTest_TextWindowAddText().
SDL_PRINTF_VARARG_FUNCV
#define SDL_PRINTF_VARARG_FUNCV (fmtargnumber)
Referenced by SDL_vasprintf(), and SDL_vsnprintf().
SDL_PRIs32
#define SDL_PRIs32 "d"
Referenced by SDL_LoadBMP_IO().
SDL_PRIs64
#define SDL_PRIs64 "lld"
Referenced by SDL_DumpPropertiesCallback(), and SDL_GetStringProperty().
SDL_PRIu32
#define SDL_PRIu32 "u"
Referenced by SDL_GetDriverAndJoystickIndex(), SDL_GetDriverAndSensorIndex(), SDL_GetHapticIndex(), SDL_GetKeyboardNameForID(), SDL_GetMouseNameForID(), SDL_OpenGamepad(), and WaveLoad().
SDL_PRIu64
#define SDL_PRIu64 "llu"
SDL_PRIX32
#define SDL_PRIX32 "X"
SDL_PRIx32
#define SDL_PRIx32 "x"
SDL_PRIX64
#define SDL_PRIX64 "llX"
SDL_PRIx64
#define SDL_PRIx64 "llx"
Referenced by get_x11_window_handle(), and SDL_DumpPropertiesCallback().
SDL_reinterpret_cast
#define SDL_reinterpret_cast (type, expression)
Value:
((type)(expression))
SDL_SCANF_FORMAT_STRING
#define SDL_SCANF_FORMAT_STRING
Referenced by SDL_sscanf(), SDL_sscanf(), SDL_vsscanf(), and SDL_vsscanf().
SDL_SCANF_VARARG_FUNC
#define SDL_SCANF_VARARG_FUNC (fmtargnumber)
Referenced by SDL_sscanf().
SDL_SCANF_VARARG_FUNCV
#define SDL_SCANF_VARARG_FUNCV (fmtargnumber)
Referenced by SDL_vsscanf().
SDL_SINT64_C
#define SDL_SINT64_C (c)
Value:
c ## LL
SDL_SIZE_MAX
#define SDL_SIZE_MAX ((size_t) -1)
Referenced by GENERIC_ReadStorageFile(), GENERIC_WriteStorageFile(), NextAudioStreamIter(), SDL_COMPILE_TIME_ASSERT(), SDL_GetAudioQueueQueued(), SDL_LoadFile_IO(), SDL_NextAudioQueueIter(), SDL_size_add_check_overflow(), and SDL_size_mul_check_overflow().
SDL_stack_alloc
#define SDL_stack_alloc (type, count)
Value:
(type*)alloca(sizeof(type)*(count))
Referenced by SDL_ConvertSurfaceAndColorspace().
SDL_stack_free
#define SDL_stack_free (data)
Referenced by SDL_ConvertSurfaceAndColorspace().
SDL_static_cast
#define SDL_static_cast (type, expression)
Value:
((type)(expression))
Referenced by SDL_memset4(), SDL_Swap16(), SDL_Swap32(), and SDL_Swap64().
SDL_STRINGIFY_ARG
#define SDL_STRINGIFY_ARG (arg)
Value:
#arg
Macro useful for building other macros with strings in them.
For example:
#define LOG_ERROR(X) OutputDebugString(SDL_STRINGIFY_ARG(__FUNCTION__) ": " X "\n")`
Parameters
arg the text to turn into a string literal.
Since
This macro is available since SDL 3.2.0.
SDL_UINT64_C
#define SDL_UINT64_C (c)
Value:
c ## ULL
SDL_WPRINTF_VARARG_FUNC
#define SDL_WPRINTF_VARARG_FUNC (fmtargnumber)
Referenced by SDL_swprintf().
SDL_WPRINTF_VARARG_FUNCV
#define SDL_WPRINTF_VARARG_FUNCV (fmtargnumber)
Referenced by SDL_vswprintf().
SDL_zero
#define SDL_zero (x)
Value:
SDL_memset(&(x), 0, sizeof((x)))
Clear an object's memory to zero.
This is wrapper over SDL_memset that handles calculating the object size, so there's no chance of copy/paste errors, and the code is cleaner.
This requires an object, not a pointer to an object, nor an array.
Parameters
x the object to clear.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
See also
SDL_zerop
SDL_zeroa
Referenced by __kernel_rem_pio2(), ClosePhysicalCamera(), CreateIconFromSurface(), GetMouseClickState(), HIDAPI_InitializeDiscovery(), IMA_ADPCM_Decode(), IOS_JoystickGetDeviceGUID(), MS_ADPCM_Decode(), SDL_AddAudioDevice(), SDL_AddBasicVideoDisplay(), SDL_AddKeyboard(), SDL_AddMouse(), SDL_AddPenDevice(), SDL_Blit_Slow_Float(), SDL_CameraInit(), SDL_ClearAudioStream(), SDL_CreateJoystickGUID(), SDL_CreateTray(), SDL_CreateWindowWithProperties(), SDL_DefaultAudioDeviceChanged(), SDL_GetAudioStreamDataAdjustGain(), SDL_GetJoystickGUIDForID(), SDL_GetWindowPosition(), SDL_GPU_FetchBlitPipeline(), SDL_InitAudio(), SDL_InternalGlobDirectory(), SDL_LoadWAV_IO(), SDL_OnWindowDisplayChanged(), SDL_PrivateGetGamepadMapping(), SDL_PrivateParseGamepadElement(), SDL_PromptAssertion(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitEventWatchList(), SDL_RemoveKeyboard(), SDL_RemoveMouse(), SDL_RemovePenDevice(), SDL_RunApp(), SDL_SendDrop(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SetCurrentDisplayMode(), SDL_SetRenderClipRect(), SDL_SetTextInputArea(), SDL_SetWindowFullscreen(), SDL_SetWindowFullscreenMode(), SDL_SetWindowMouseRect(), SDL_SetWindowPosition(), SDL_ShowSimpleMessageBox(), SDL_SYS_GetPreferredLocales(), SDL_SYS_OpenURL(), SDL_UpdateAudio(), SDL_UpdateCamera(), SDL_UpdateDesktopBounds(), SDL_UpdateFullscreenMode(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_vsnprintf(), SendSteamHandleUpdateEvents(), ShouldAttemptSensorFusion(), videoInit(), WaveLoad(), and WIN_InitDeviceNotification().
SDL_zeroa
#define SDL_zeroa (x)
Value:
SDL_memset((x), 0, sizeof((x)))
Clear an array's memory to zero.
This is wrapper over SDL_memset that handles calculating the array size, so there's no chance of copy/paste errors, and the code is cleaner.
This requires an array, not an object, nor a pointer to an object.
Parameters
x an array to clear.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
See also
SDL_zero
SDL_zeroa
Referenced by SDL_BLooper::_HandleKey(), ClosePhysicalCamera(), MS_ADPCM_Decode(), SDL_AcquireGPUCommandBuffer(), SDL_EndGPUComputePass(), SDL_EndGPURenderPass(), SDL_GetPreferredLocales(), SDL_PrepareCameraSurfaces(), and SDL_PrivateParseGamepadConfigString().
SDL_zerop
#define SDL_zerop (x)
Value:
SDL_memset((x), 0, sizeof(*(x)))
Clear an object's memory to zero, using a pointer.
This is wrapper over SDL_memset that handles calculating the object size, so there's no chance of copy/paste errors, and the code is cleaner.
This requires a pointer to an object, not an object itself, nor an array.
Parameters
x a pointer to the object to clear.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
See also
SDL_zero
SDL_zeroa
Referenced by AddVirtualGamepadInfo(), ChooseBestCameraSpec(), delete_item(), GetAsyncIOTaskOutcome(), GetAudioStreamHead(), GetMouseInputSource(), InitMemoryPool(), SDL_AddPenDevice(), SDL_CreateAudioTrack(), SDL_CreateRendererWithProperties(), SDL_GetCameraFormat(), SDL_GetClosestFullscreenDisplayMode(), SDL_GetErrBuf(), SDL_GetPathInfo(), SDL_GetRenderClipRect(), SDL_GetRenderLogicalPresentationRect(), SDL_GetRenderSafeArea(), SDL_GetRenderViewport(), SDL_GetStoragePathInfo(), SDL_GetSurfaceClipRect(), SDL_GetWindowSafeArea(), SDL_InitHapticRumble(), SDL_InitializeSurface(), SDL_InitPixelFormatDetails(), SDL_LoadWAV(), SDL_LoadWAV_IO(), SDL_PreInitMouse(), SDL_PrivateJoystickAddSensor(), SDL_UNIONRECT(), and STEAM_GetStoragePathInfo().
true
#define true 1
Referenced by SDL_GetBooleanProperty(), SDL_GetEventFilter(), SDL_HardwareKeyboardKeyPressed(), SDL_IsJoystickHIDAPI(), SDL_IsJoystickMFI(), SDL_IsJoystickRAWINPUT(), SDL_IsJoystickVIRTUAL(), SDL_IsJoystickWGI(), SDL_IsJoystickXInput(), SDL_PointInRect(), SDL_PointInRectFloat(), SDL_RectEmpty(), SDL_RectEmptyFloat(), SDL_RectsEqual(), SDL_RectsEqualEpsilon(), SDL_SetBooleanProperty(), SDL_SetRenderVSync(), SDL_WindowHasSurface(), and SetLogicalAudioDevicePauseState().
Typedef Documentation
SDL_calloc_func
typedef void *(SDLCALL * SDL_calloc_func) (size_t nmemb, size_t size)
A callback used to implement SDL_calloc().
SDL will always ensure that the passed nmemb and size are both greater than 0.
Parameters
nmemb the number of elements in the array.
size the size of each element of the array.
Returns
a pointer to the allocated array, or NULL if allocation failed.
Thread Safety
It should be safe to call this callback from any thread.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_calloc
SDL_GetOriginalMemoryFunctions
SDL_GetMemoryFunctions
SDL_SetMemoryFunctions
SDL_CompareCallback
typedef int(SDLCALL * SDL_CompareCallback) (const void *a, const void *b)
A callback used with SDL sorting and binary search functions.
Parameters
a a pointer to the first element being compared.
b a pointer to the second element being compared.
Returns
-1 if a should be sorted before b, 1 if b should be sorted before a, 0 if they are equal. If two elements are equal, their order in the sorted array is undefined.
Since
This callback is available since SDL 3.2.0.
See also
SDL_bsearch
SDL_qsort
SDL_CompareCallback_r
typedef int(SDLCALL * SDL_CompareCallback_r) (void *userdata, const void *a, const void *b)
A callback used with SDL sorting and binary search functions.
Parameters
userdata the userdata pointer passed to the sort function.
a a pointer to the first element being compared.
b a pointer to the second element being compared.
Returns
-1 if a should be sorted before b, 1 if b should be sorted before a, 0 if they are equal. If two elements are equal, their order in the sorted array is undefined.
Since
This callback is available since SDL 3.2.0.
See also
SDL_qsort_r
SDL_bsearch_r
SDL_Environment
typedef struct SDL_Environment SDL_Environment
A thread-safe set of environment variables
Since
This struct is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariable
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
SDL_DestroyEnvironment
SDL_free_func
typedef void(SDLCALL * SDL_free_func) (void *mem)
A callback used to implement SDL_free().
SDL will always ensure that the passed mem is a non-NULL pointer.
Parameters
mem a pointer to allocated memory.
Thread Safety
It should be safe to call this callback from any thread.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_free
SDL_GetOriginalMemoryFunctions
SDL_GetMemoryFunctions
SDL_SetMemoryFunctions
SDL_FunctionPointer
typedef void(* SDL_FunctionPointer) (void)
SDL_iconv_t
typedef struct SDL_iconv_data_t* SDL_iconv_t
An opaque handle representing string encoding conversion state.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_iconv_open
SDL_malloc_func
typedef void *(SDLCALL * SDL_malloc_func) (size_t size)
A callback used to implement SDL_malloc().
SDL will always ensure that the passed size is greater than 0.
Parameters
size the size to allocate.
Returns
a pointer to the allocated memory, or NULL if allocation failed.
Thread Safety
It should be safe to call this callback from any thread.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_malloc
SDL_GetOriginalMemoryFunctions
SDL_GetMemoryFunctions
SDL_SetMemoryFunctions
SDL_realloc_func
typedef void *(SDLCALL * SDL_realloc_func) (void *mem, size_t size)
A callback used to implement SDL_realloc().
SDL will always ensure that the passed size is greater than 0.
Parameters
mem a pointer to allocated memory to reallocate, or NULL.
size the new size of the memory.
Returns
a pointer to the newly allocated memory, or NULL if allocation failed.
Thread Safety
It should be safe to call this callback from any thread.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_realloc
SDL_GetOriginalMemoryFunctions
SDL_GetMemoryFunctions
SDL_SetMemoryFunctions
SDL_Time
typedef Sint64 SDL_Time
SDL times are signed, 64-bit integers representing nanoseconds since the Unix epoch (Jan 1, 1970).
They can be converted between POSIX time_t values with SDL_NS_TO_SECONDS() and SDL_SECONDS_TO_NS(), and between Windows FILETIME values with SDL_TimeToWindows() and SDL_TimeFromWindows().
Since
This datatype is available since SDL 3.2.0.
See also
SDL_MAX_SINT64
SDL_MIN_SINT64
Sint16
typedef int16_t Sint16
A signed 16-bit integer type.
Since
This macro is available since SDL 3.2.0.
Sint32
typedef int32_t Sint32
A signed 32-bit integer type.
Since
This macro is available since SDL 3.2.0.
Sint64
typedef int64_t Sint64
A signed 64-bit integer type.
Since
This macro is available since SDL 3.2.0.
See also
SDL_SINT64_C
Sint8
typedef int8_t Sint8
A signed 8-bit integer type.
Since
This macro is available since SDL 3.2.0.
Uint16
typedef uint16_t Uint16
An unsigned 16-bit integer type.
Since
This macro is available since SDL 3.2.0.
Uint32
typedef uint32_t Uint32
An unsigned 32-bit integer type.
Since
This macro is available since SDL 3.2.0.
Uint64
typedef uint64_t Uint64
An unsigned 64-bit integer type.
Since
This macro is available since SDL 3.2.0.
See also
SDL_UINT64_C
Uint8
typedef uint8_t Uint8
An unsigned 8-bit integer type.
Since
This macro is available since SDL 3.2.0.
Function Documentation
alloca()
void * alloca (size_t)
SDL_abs()
SDL_DECLSPEC int SDLCALL SDL_abs (int x) extern
Compute the absolute value of x.
Parameters
x an integer value.
Returns
the absolute value of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_ABS
    return abs(x);
#else
    return (x < 0) ? -x : x;
#endif
}
Referenced by ChooseBestCameraSpec(), RenderLineBresenham(), and SDL_SendJoystickAxis().
SDL_acos()
SDL_DECLSPEC double SDLCALL SDL_acos (double x) extern
Compute the arc cosine of x.
The definition of y = acos(x) is x = cos(y).
Domain: -1 <= x <= 1
Range: 0 <= y <= Pi
This function operates on double-precision floating point values, use SDL_acosf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc cosine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_acosf
SDL_asin
SDL_cos
{
#ifdef HAVE_ACOS
    return acos(val);
#else
    double result;
    if (val == -1.0) {
        result = SDL_PI_D;
    } else {
        result = SDL_atan(SDL_sqrt(1.0 - val * val) / val);
        if (result < 0.0) {
            result += SDL_PI_D;
        }
    }
    return result;
#endif
}
References SDL_atan(), SDL_PI_D, and SDL_sqrt().
Referenced by SDL_acosf(), and SDL_asin().
SDL_acosf()
SDL_DECLSPEC float SDLCALL SDL_acosf (float x) extern
Compute the arc cosine of x.
The definition of y = acos(x) is x = cos(y).
Domain: -1 <= x <= 1
Range: 0 <= y <= Pi
This function operates on single-precision floating point values, use SDL_acos for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc cosine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_acos
SDL_asinf
SDL_cosf
{
#ifdef HAVE_ACOSF
    return acosf(val);
#else
    return (float)SDL_acos((double)val);
#endif
}
References SDL_acos().
SDL_aligned_alloc()
SDL_DECLSPEC SDL_MALLOC void *SDLCALL SDL_aligned_alloc (size_t alignment, size_t size) extern
Allocate memory aligned to a specific alignment.
The memory returned by this function must be freed with SDL_aligned_free(), not SDL_free().
If alignment is less than the size of void *, it will be increased to match that.
The returned memory address will be a multiple of the alignment value, and the size of the memory allocated will be a multiple of the alignment value.
Parameters
alignment the alignment of the memory.
size the size to allocate.
Returns
a pointer to the aligned memory, or NULL if allocation failed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_aligned_free
{
    size_t padding;
    Uint8 *result = NULL;
    size_t requested_size = size;
    if (alignment < sizeof(void *)) {
        alignment = sizeof(void *);
    }
    padding = (alignment - (size % alignment));
    if (SDL_size_add_check_overflow(size, alignment, &size) &&
        SDL_size_add_check_overflow(size, sizeof(void *), &size) &&
        SDL_size_add_check_overflow(size, padding, &size)) {
        void *original = SDL_malloc(size);
        if (original) {
            // Make sure we have enough space to store the original pointer
            result = (Uint8 *)original + sizeof(original);
            // Align the pointer we're going to return
            result += alignment - (((size_t)result) % alignment);
            // Store the original pointer right before the returned value
            SDL_memcpy(result - sizeof(original), &original, sizeof(original));
            // Initialize the padding to zero
            if (padding > 0) {
                SDL_memset(result + requested_size, 0, padding);
            }
        }
    }
    return result;
}
References NULL, SDL_malloc(), SDL_memcpy, SDL_memset, and SDL_size_add_check_overflow().
Referenced by EnsureAudioStreamWorkBufferSize(), OpenPhysicalAudioDevice(), PS2AUDIO_OpenDevice(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CreateSurface(), SDL_ResetAudioQueueHistory(), SDL_SetAudioPostmixCallback(), and ZombieAcquireFrame().
SDL_aligned_free()
SDL_DECLSPEC void SDLCALL SDL_aligned_free (void * mem) extern
Free memory allocated by SDL_aligned_alloc().
The pointer is no longer valid after this call and cannot be dereferenced anymore.
If mem is NULL, this function does nothing.
Parameters
mem a pointer previously returned by SDL_aligned_alloc(), or NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_aligned_alloc
{
    if (mem) {
        void *original;
        SDL_memcpy(&original, ((Uint8 *)mem - sizeof(original)), sizeof(original));
        SDL_free(original);
    }
}
References SDL_free(), and SDL_memcpy.
Referenced by ClosePhysicalAudioDevice(), ClosePhysicalCamera(), EnsureAudioStreamWorkBufferSize(), PS2AUDIO_CloseDevice(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_DestroyAudioQueue(), SDL_DestroyAudioStream(), SDL_DestroySurface(), and SDL_ResetAudioQueueHistory().
SDL_ALLOC_SIZE()
SDL_DECLSPEC SDL_ALLOC_SIZE (2) extern
Change the size of allocated memory.
The memory returned by this function must be freed with SDL_free().
If size is 0, it will be set to 1. Note that this is unlike some other C runtime realloc implementations, which may treat realloc(mem, 0) the same way as free(mem).
If mem is NULL, the behavior of this function is equivalent to SDL_malloc(). Otherwise, the function can have one of three possible outcomes:
If it returns the same pointer as mem, it means that mem was resized in place without freeing.
If it returns a different non-NULL pointer, it means that mem was freed and cannot be dereferenced anymore.
If it returns NULL (indicating failure), then mem will remain valid and must still be freed with SDL_free().
If the allocation is successfully resized, the returned pointer is guaranteed to be aligned to either the fundamental alignment (alignof(max_align_t) in C11 and later) or 2 * sizeof(void *), whichever is smaller.
Parameters
mem a pointer to allocated memory to reallocate, or NULL.
size the new size of the memory.
Returns
a pointer to the newly allocated memory, or NULL if allocation failed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_free
SDL_malloc
SDL_calloc
References SDL_ALLOC_SIZE, SDL_DECLSPEC, SDL_free(), SDL_realloc(), and SDLCALL.
SDL_ALLOC_SIZE2()
SDL_DECLSPEC SDL_MALLOC SDL_ALLOC_SIZE2 (1 , 2) extern
Allocate a zero-initialized array.
The memory returned by this function must be freed with SDL_free().
If either of nmemb or size is 0, they will both be set to 1.
If the allocation is successful, the returned pointer is guaranteed to be aligned to either the fundamental alignment (alignof(max_align_t) in C11 and later) or 2 * sizeof(void *), whichever is smaller.
Parameters
nmemb the number of elements in the array.
size the size of each element of the array.
Returns
a pointer to the allocated array, or NULL if allocation failed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_free
SDL_malloc
SDL_realloc
References SDL_calloc(), SDL_DECLSPEC, SDL_MALLOC, SDLCALL, and void().
SDL_asin()
SDL_DECLSPEC double SDLCALL SDL_asin (double x) extern
Compute the arc sine of x.
The definition of y = asin(x) is x = sin(y).
Domain: -1 <= x <= 1
Range: -Pi/2 <= y <= Pi/2
This function operates on double-precision floating point values, use SDL_asinf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc sine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_asinf
SDL_acos
SDL_sin
{
#ifdef HAVE_ASIN
    return asin(val);
#else
    double result;
    if (val == -1.0) {
        result = -(SDL_PI_D / 2.0);
    } else {
        result = (SDL_PI_D / 2.0) - SDL_acos(val);
    }
    return result;
#endif
}
References SDL_acos(), and SDL_PI_D.
Referenced by SDL_asinf().
SDL_asinf()
SDL_DECLSPEC float SDLCALL SDL_asinf (float x) extern
Compute the arc sine of x.
The definition of y = asin(x) is x = sin(y).
Domain: -1 <= x <= 1
Range: -Pi/2 <= y <= Pi/2
This function operates on single-precision floating point values, use SDL_asin for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc sine of x, in radians.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_asin
SDL_acosf
SDL_sinf
{
#ifdef HAVE_ASINF
    return asinf(val);
#else
    return (float)SDL_asin((double)val);
#endif
}
References SDL_asin().
SDL_asprintf()
SDL_DECLSPEC int SDLCALL SDL_asprintf (char ** strp, const char * fmt, ...) extern
This works exactly like asprintf() but doesn't require access to a C runtime.
Functions identically to SDL_snprintf(), except it allocates a buffer large enough to hold the output string on behalf of the caller.
On success, this function returns the number of bytes (not characters) comprising the output string, not counting the null-terminator character, and sets *strp to the newly-allocated string.
On error, this function returns a negative number, and the value of *strp is undefined.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
strp on output, is set to the new string. Must not be NULL.
fmt a printf-style format string. Must not be NULL.
... a list of values to be used with the format string.
Returns
the number of bytes in the newly-allocated string, not counting the null-terminator char, or a negative value on error.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_asprintf(), SDL_DECLSPEC, SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNC, and SDLCALL.
Referenced by GENERIC_INTERNAL_CreateFullPath(), GENERIC_OpenFileStorage(), GENERIC_Title_Create(), GlobDirectoryCallback(), SDL_asprintf(), SDL_GetGamepadMappingForID(), SDL_GetStringProperty(), SDL_IOFromFile(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_SetEnvironmentVariable(), SDL_SYS_GetPrefPath(), and TryOpenInRomfs().
SDL_atan()
SDL_DECLSPEC double SDLCALL SDL_atan (double x) extern
Compute the arc tangent of x.
The definition of y = atan(x) is x = tan(y).
Domain: -INF <= x <= INF
Range: -Pi/2 <= y <= Pi/2
This function operates on double-precision floating point values, use SDL_atanf for single-precision floats.
To calculate the arc tangent of y / x, use SDL_atan2.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc tangent of of x in radians, or 0 if x = 0.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atanf
SDL_atan2
SDL_tan
{
#ifdef HAVE_ATAN
    return atan(x);
#else
    return SDL_uclibc_atan(x);
#endif
}
References atan, and SDL_uclibc_atan().
Referenced by SDL_acos(), and SDL_atanf().
SDL_atan2()
SDL_DECLSPEC double SDLCALL SDL_atan2 (double y, double x) extern
Compute the arc tangent of y / x, using the signs of x and y to adjust the result's quadrant.
The definition of z = atan2(x, y) is y = x tan(z), where the quadrant of z is determined based on the signs of x and y.
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -Pi <= y <= Pi
This function operates on double-precision floating point values, use SDL_atan2f for single-precision floats.
To calculate the arc tangent of a single value, use SDL_atan.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
y floating point value of the numerator (y coordinate).
x floating point value of the denominator (x coordinate).
Returns
arc tangent of of y / x in radians, or, if x = 0, either -Pi/2, 0, or Pi/2, depending on the value of y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atan2f
SDL_atan
SDL_tan
{
#ifdef HAVE_ATAN2
    return atan2(y, x);
#else
    return SDL_uclibc_atan2(y, x);
#endif
}
References SDL_uclibc_atan2().
Referenced by SDL_atan2f().
SDL_atan2f()
SDL_DECLSPEC float SDLCALL SDL_atan2f (float y, float x) extern
Compute the arc tangent of y / x, using the signs of x and y to adjust the result's quadrant.
The definition of z = atan2(x, y) is y = x tan(z), where the quadrant of z is determined based on the signs of x and y.
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -Pi <= y <= Pi
This function operates on single-precision floating point values, use SDL_atan2 for double-precision floats.
To calculate the arc tangent of a single value, use SDL_atanf.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
y floating point value of the numerator (y coordinate).
x floating point value of the denominator (x coordinate).
Returns
arc tangent of of y / x in radians, or, if x = 0, either -Pi/2, 0, or Pi/2, depending on the value of y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atan2
SDL_atan
SDL_tan
{
#ifdef HAVE_ATAN2F
    return atan2f(y, x);
#else
    return (float)SDL_atan2((double)y, (double)x);
#endif
}
References SDL_atan2().
SDL_atanf()
SDL_DECLSPEC float SDLCALL SDL_atanf (float x) extern
Compute the arc tangent of x.
The definition of y = atan(x) is x = tan(y).
Domain: -INF <= x <= INF
Range: -Pi/2 <= y <= Pi/2
This function operates on single-precision floating point values, use SDL_atan for dboule-precision floats.
To calculate the arc tangent of y / x, use SDL_atan2f.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
arc tangent of of x in radians, or 0 if x = 0.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atan
SDL_atan2f
SDL_tanf
{
#ifdef HAVE_ATANF
    return atanf(x);
#else
    return (float)SDL_atan((double)x);
#endif
}
References SDL_atan().
SDL_atof()
SDL_DECLSPEC double SDLCALL SDL_atof (const char * str) extern
Parse a double from a string.
The result of calling SDL_atof(str) is equivalent to SDL_strtod(str, NULL).
Parameters
str The null-terminated string to read. Must not be NULL.
Returns
the parsed double.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_strtol
SDL_strtoul
SDL_strtoll
SDL_strtoull
SDL_strtod
{
#ifdef HAVE_ATOF
    return atof(string);
#else
    return SDL_strtod(string, NULL);
#endif // HAVE_ATOF
}
References NULL, and SDL_strtod().
Referenced by DUMMYAUDIO_OpenDevice(), MainCallbackRateHintChanged(), SDL_Blit_Slow_Float(), SDL_GetFloatProperty(), SDL_MouseNormalSpeedScaleChanged(), and SDL_MouseRelativeSpeedScaleChanged().
SDL_atoi()
SDL_DECLSPEC int SDLCALL SDL_atoi (const char * str) extern
Parse an int from a string.
The result of calling SDL_atoi(str) is equivalent to (int)SDL_strtol(str, NULL, 10).
Parameters
str The null-terminated string to read. Must not be NULL.
Returns
the parsed int.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atof
SDL_strtol
SDL_strtoul
SDL_strtoll
SDL_strtoull
SDL_strtod
SDL_itoa
{
#ifdef HAVE_ATOI
    return atoi(string);
#else
    return SDL_strtol(string, NULL, 10);
#endif // HAVE_ATOI
}
References NULL, and SDL_strtol().
Referenced by load_default_icon(), ParseLogCategory(), ParseLogPriority(), PrepareAudioFormat(), SDL_EventLoggingChanged(), SDL_GetDefaultSampleFramesFromFreq(), SDL_GetDefaultSystemCursor(), SDL_GetRenderLineMethod(), SDL_GetStringInteger(), SDL_MouseDoubleClickRadiusChanged(), SDL_MouseDoubleClickTimeChanged(), SDL_MouseIntegerModeChanged(), SDL_PrivateAddGamepadMapping(), SDL_PrivateParseGamepadElement(), SDL_SetHapticGain(), SDL_StopEventLoop(), and SDL_TimerResolutionChanged().
SDL_bsearch()
SDL_DECLSPEC void *SDLCALL SDL_bsearch (const void * key, const void * base, size_t nmemb, size_t size, SDL_CompareCallback compare) extern
Perform a binary search on a previously sorted array.
For example:
typedef struct {
    int key;
    const char *string;
} data;
int SDLCALL compare(const void *a, const void *b)
{
    const data *A = (const data *)a;
    const data *B = (const data *)b;
    if (A->n < B->n) {
        return -1;
    } else if (B->n < A->n) {
        return 1;
    } else {
        return 0;
    }
}
data values[] = {
    { 1, "first" }, { 2, "second" }, { 3, "third" }
};
data key = { 2, NULL };
data *result = SDL_bsearch(&key, values, SDL_arraysize(values), sizeof(values[0]), compare);
Parameters
key a pointer to a key equal to the element being searched for.
base a pointer to the start of the array.
nmemb the number of elements in the array.
size the size of the elements in the array.
compare a function used to compare elements in the array.
Returns
a pointer to the matching element in the array, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_bsearch_r
SDL_qsort
{
References NULL.
SDL_bsearch_r()
SDL_DECLSPEC void *SDLCALL SDL_bsearch_r (const void * key, const void * base, size_t nmemb, size_t size, SDL_CompareCallback_r compare, void * userdata) extern
Perform a binary search on a previously sorted array, passing a userdata pointer to the compare function.
For example:
typedef enum {
    sort_increasing,
    sort_decreasing,
} sort_method;
typedef struct {
    int key;
    const char *string;
} data;
int SDLCALL compare(const void *userdata, const void *a, const void *b)
{
    sort_method method = (sort_method)(uintptr_t)userdata;
    const data *A = (const data *)a;
    const data *B = (const data *)b;
    if (A->key < B->key) {
        return (method == sort_increasing) ? -1 : 1;
    } else if (B->key < A->key) {
        return (method == sort_increasing) ? 1 : -1;
    } else {
        return 0;
    }
}
data values[] = {
    { 1, "first" }, { 2, "second" }, { 3, "third" }
};
data key = { 2, NULL };
data *result = SDL_bsearch_r(&key, values, SDL_arraysize(values), sizeof(values[0]), compare, (const void *)(uintptr_t)sort_increasing);
Parameters
key a pointer to a key equal to the element being searched for.
base a pointer to the start of the array.
nmemb the number of elements in the array.
size the size of the elements in the array.
compare a function used to compare elements in the array.
userdata a pointer to pass to the compare function.
Returns
a pointer to the matching element in the array, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_bsearch
SDL_qsort_r
{
    const void *pivot;
    size_t corr;
    int rc;
    while (nmemb) {
        /* algorithm needs -1 correction if remaining elements are an even number. */
        corr = nmemb % 2;
        nmemb /= 2;
        pivot = (const char *)base + (nmemb * size);
        rc = compare(userdata, key, pivot);
        if (rc > 0) {
            base = (const char *)pivot + size;
            /* applying correction */
            nmemb -= (1 - corr);
        } else if (rc == 0) {
            return (void *)pivot;
        }
    }
SDL_ceil()
SDL_DECLSPEC double SDLCALL SDL_ceil (double x) extern
Compute the ceiling of x.
The ceiling of x is the smallest integer y such that y > x, i.e x rounded up to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_ceilf for single-precision floats.
Parameters
x floating point value.
Returns
the ceiling of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ceilf
SDL_floor
SDL_trunc
SDL_round
SDL_lround
{
#ifdef HAVE_CEIL
    return ceil(x);
#else
    double integer = SDL_floor(x);
    double fraction = x - integer;
    if (fraction > 0.0) {
        integer += 1.0;
    }
    return integer;
#endif // HAVE_CEIL
}
References SDL_floor().
Referenced by SDL_ceilf(), SDL_round(), and SDL_trunc().
SDL_ceilf()
SDL_DECLSPEC float SDLCALL SDL_ceilf (float x) extern
Compute the ceiling of x.
The ceiling of x is the smallest integer y such that y > x, i.e x rounded up to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_ceil for double-precision floats.
Parameters
x floating point value.
Returns
the ceiling of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ceil
SDL_floorf
SDL_truncf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_CEILF
    return ceilf(x);
#else
    return (float)SDL_ceil((double)x);
#endif
}
References SDL_ceil().
Referenced by SDL_GetRenderSafeArea(), SDL_GetRenderViewport(), SDL_GetWindowSizeInPixels(), SDL_MaybeEnableWarpEmulation(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), UpdatePixelClipRect(), and UpdatePixelViewport().
SDL_copysign()
SDL_DECLSPEC double SDLCALL SDL_copysign (double x, double y) extern
Copy the sign of one floating-point value to another.
The definition of copysign is that copysign(x, y) = abs(x) * sign(y).
Domain: -INF <= x <= INF, -INF <= y <= f
Range: -INF <= z <= INF
This function operates on double-precision floating point values, use SDL_copysignf for single-precision floats.
Parameters
x floating point value to use as the magnitude.
y floating point value to use as the sign.
Returns
the floating point value with the sign of y and the magnitude of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_copysignf
SDL_fabs
{
#ifdef HAVE_COPYSIGN
    return copysign(x, y);
#elif defined(HAVE__COPYSIGN)
    return _copysign(x, y);
#elif defined(__WATCOMC__) && defined(__386__)
    // this is nasty as hell, but it works..
    unsigned int *xi = (unsigned int *)&x,
                 *yi = (unsigned int *)&y;
    xi[1] = (yi[1] & 0x80000000) | (xi[1] & 0x7fffffff);
    return x;
#else
    return SDL_uclibc_copysign(x, y);
#endif // HAVE_COPYSIGN
}
References copysign, and SDL_uclibc_copysign().
Referenced by SDL_copysignf().
SDL_copysignf()
SDL_DECLSPEC float SDLCALL SDL_copysignf (float x, float y) extern
Copy the sign of one floating-point value to another.
The definition of copysign is that copysign(x, y) = abs(x) * sign(y).
Domain: -INF <= x <= INF, -INF <= y <= f
Range: -INF <= z <= INF
This function operates on single-precision floating point values, use SDL_copysign for double-precision floats.
Parameters
x floating point value to use as the magnitude.
y floating point value to use as the sign.
Returns
the floating point value with the sign of y and the magnitude of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_copysign
SDL_fabsf
{
#ifdef HAVE_COPYSIGNF
    return copysignf(x, y);
#else
    return (float)SDL_copysign((double)x, (double)y);
#endif
}
References SDL_copysign().
SDL_cos()
SDL_DECLSPEC double SDLCALL SDL_cos (double x) extern
Compute the cosine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on double-precision floating point values, use SDL_cosf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
cosine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_cosf
SDL_acos
SDL_sin
{
#ifdef HAVE_COS
    return cos(x);
#else
    return SDL_uclibc_cos(x);
#endif
}
References cos, and SDL_uclibc_cos().
Referenced by SDL_cosf().
SDL_cosf()
SDL_DECLSPEC float SDLCALL SDL_cosf (float x) extern
Compute the cosine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on single-precision floating point values, use SDL_cos for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
cosine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_cos
SDL_acosf
SDL_sinf
{
#ifdef HAVE_COSF
    return cosf(x);
#else
    return (float)SDL_cos((double)x);
#endif
}
References SDL_cos().
Referenced by SDL_RenderTextureRotated().
SDL_crc16()
SDL_DECLSPEC Uint16 SDLCALL SDL_crc16 (Uint16 crc, const void * data, size_t len) extern
Calculate a CRC-16 value.
https://en.wikipedia.org/wiki/Cyclic_redundancy_check
This function can be called multiple times, to stream data to be checksummed in blocks. Each call must provide the previous CRC-16 return value to be updated with the next block. The first call to this function for a set of blocks should pass in a zero CRC value.
Parameters
crc the current checksum for this data set, or 0 for a new data set.
data a new block of data to add to the checksum.
len the size, in bytes, of the new block of data.
Returns
a CRC-16 checksum value of all blocks in the data set.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    // As an optimization we can precalculate a 256 entry table for each byte
    size_t i;
    for (i = 0; i < len; ++i) {
        crc = crc16_for_byte((Uint8)crc ^ ((const Uint8 *)data)[i]) ^ crc >> 8;
    }
    return crc;
}
References crc16_for_byte().
Referenced by SDL_CreateJoystickGUID().
SDL_crc32()
SDL_DECLSPEC Uint32 SDLCALL SDL_crc32 (Uint32 crc, const void * data, size_t len) extern
Calculate a CRC-32 value.
https://en.wikipedia.org/wiki/Cyclic_redundancy_check
This function can be called multiple times, to stream data to be checksummed in blocks. Each call must provide the previous CRC-32 return value to be updated with the next block. The first call to this function for a set of blocks should pass in a zero CRC value.
Parameters
crc the current checksum for this data set, or 0 for a new data set.
data a new block of data to add to the checksum.
len the size, in bytes, of the new block of data.
Returns
a CRC-32 checksum value of all blocks in the data set.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    // As an optimization we can precalculate a 256 entry table for each byte
    size_t i;
    for (i = 0; i < len; ++i) {
        crc = crc32_for_byte((Uint8)crc ^ ((const Uint8 *)data)[i]) ^ crc >> 8;
    }
    return crc;
}
References crc32_for_byte().
SDL_CreateEnvironment()
SDL_DECLSPEC SDL_Environment *SDLCALL SDL_CreateEnvironment (unsigned char populated) extern
Create a set of environment variables
Parameters
populated true to initialize it from the C runtime environment, false to create an empty environment.
Returns
a pointer to the new environment or NULL on failure; call SDL_GetError() for more information.
Thread Safety
If populated is false, it is safe to call this function from any thread, otherwise it is safe if no other threads are calling setenv() or unsetenv()
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironmentVariable
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
SDL_DestroyEnvironment
References SDL_CreateEnvironment(), SDL_DECLSPEC, SDL_GetEnvironmentVariable(), SDL_GetEnvironmentVariables(), and SDLCALL.
Referenced by run_zenity(), SDL_CreateEnvironment(), and SDL_SYS_OpenURL().
SDL_DestroyEnvironment()
SDL_DECLSPEC void SDLCALL SDL_DestroyEnvironment (SDL_Environment * env) extern
Destroy a set of environment variables.
Parameters
env the environment to destroy.
Thread Safety
It is safe to call this function from any thread, as long as the environment is no longer in use.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateEnvironment
{
    if (!env || env == SDL_environment) {
        return;
    }
    SDL_DestroyMutex(env->lock);
    SDL_DestroyHashTable(env->strings);
    SDL_free(env);
}
References SDL_Environment::lock, SDL_DestroyHashTable(), SDL_DestroyMutex(), SDL_environment, SDL_free(), and SDL_Environment::strings.
Referenced by run_zenity(), SDL_QuitEnvironment(), SDL_SetEnvironmentVariable(), and SDL_SYS_OpenURL().
SDL_exp()
SDL_DECLSPEC double SDLCALL SDL_exp (double x) extern
Compute the exponential of x.
The definition of y = exp(x) is y = e^x, where e is the base of the natural logarithm. The inverse is the natural logarithm, SDL_log.
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
The output will overflow if exp(x) is too large to be represented.
This function operates on double-precision floating point values, use SDL_expf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
value of e^x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_expf
SDL_log
{
#ifdef HAVE_EXP
    return exp(x);
#else
    return SDL_uclibc_exp(x);
#endif
}
References SDL_uclibc_exp().
Referenced by SDL_expf().
SDL_expf()
SDL_DECLSPEC float SDLCALL SDL_expf (float x) extern
Compute the exponential of x.
The definition of y = exp(x) is y = e^x, where e is the base of the natural logarithm. The inverse is the natural logarithm, SDL_logf.
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
The output will overflow if exp(x) is too large to be represented.
This function operates on single-precision floating point values, use SDL_exp for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value.
Returns
value of e^x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_exp
SDL_logf
{
#ifdef HAVE_EXPF
    return expf(x);
#else
    return (float)SDL_exp((double)x);
#endif
}
References SDL_exp().
SDL_fabs()
SDL_DECLSPEC double SDLCALL SDL_fabs (double x) extern
Compute the absolute value of x
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
This function operates on double-precision floating point values, use SDL_fabsf for single-precision floats.
Parameters
x floating point value to use as the magnitude.
Returns
the absolute value of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fabsf
{
#ifdef HAVE_FABS
    return fabs(x);
#else
    return SDL_uclibc_fabs(x);
#endif
}
References fabs, and SDL_uclibc_fabs().
Referenced by SDL_fabsf(), and SDL_PrivateSendMouseButton().
SDL_fabsf()
SDL_DECLSPEC float SDLCALL SDL_fabsf (float x) extern
Compute the absolute value of x
Domain: -INF <= x <= INF
Range: 0 <= y <= INF
This function operates on single-precision floating point values, use SDL_fabs for double-precision floats.
Parameters
x floating point value to use as the magnitude.
Returns
the absolute value of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fabs
{
#ifdef HAVE_FABSF
    return fabsf(x);
#else
    return (float)SDL_fabs((double)x);
#endif
}
References SDL_fabs().
Referenced by ChooseBestCameraSpec(), SDL_GetClosestFullscreenDisplayMode(), SDL_RectsEqualEpsilon(), and UpdateLogicalPresentation().
SDL_floor()
SDL_DECLSPEC double SDLCALL SDL_floor (double x) extern
Compute the floor of x.
The floor of x is the largest integer y such that y > x, i.e x rounded down to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_floorf for single-precision floats.
Parameters
x floating point value.
Returns
the floor of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_floorf
SDL_ceil
SDL_trunc
SDL_round
SDL_lround
{
#ifdef HAVE_FLOOR
    return floor(x);
#else
    return SDL_uclibc_floor(x);
#endif
}
References floor, and SDL_uclibc_floor().
Referenced by SDL_ceil(), SDL_floorf(), SDL_round(), and SDL_trunc().
SDL_floorf()
SDL_DECLSPEC float SDLCALL SDL_floorf (float x) extern
Compute the floor of x.
The floor of x is the largest integer y such that y > x, i.e x rounded down to the nearest integer.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_floor for double-precision floats.
Parameters
x floating point value.
Returns
the floor of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_floor
SDL_ceilf
SDL_truncf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_FLOORF
    return floorf(x);
#else
    return (float)SDL_floor((double)x);
#endif
}
References SDL_floor().
Referenced by SDL_MaybeEnableWarpEmulation(), UpdateLogicalPresentation(), UpdatePixelClipRect(), and UpdatePixelViewport().
SDL_fmod()
SDL_DECLSPEC double SDLCALL SDL_fmod (double x, double y) extern
Return the floating-point remainder of x / y
Divides x by y, and returns the remainder.
Domain: -INF <= x <= INF, -INF <= y <= INF, y != 0
Range: -y <= z <= y
This function operates on double-precision floating point values, use SDL_fmodf for single-precision floats.
Parameters
x the numerator.
y the denominator. Must not be 0.
Returns
the remainder of x / y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fmodf
SDL_modf
SDL_trunc
SDL_ceil
SDL_floor
SDL_round
SDL_lround
{
#ifdef HAVE_FMOD
    return fmod(x, y);
#else
    return SDL_uclibc_fmod(x, y);
#endif
}
References SDL_uclibc_fmod().
Referenced by SDL_fmodf().
SDL_fmodf()
SDL_DECLSPEC float SDLCALL SDL_fmodf (float x, float y) extern
Return the floating-point remainder of x / y
Divides x by y, and returns the remainder.
Domain: -INF <= x <= INF, -INF <= y <= INF, y != 0
Range: -y <= z <= y
This function operates on single-precision floating point values, use SDL_fmod for double-precision floats.
Parameters
x the numerator.
y the denominator. Must not be 0.
Returns
the remainder of x / y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_fmod
SDL_truncf
SDL_modff
SDL_ceilf
SDL_floorf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_FMODF
    return fmodf(x, y);
#else
    return (float)SDL_fmod((double)x, (double)y);
#endif
}
References SDL_fmod().
SDL_free()
SDL_DECLSPEC void SDLCALL SDL_free (void * mem) extern
Free allocated memory.
The pointer is no longer valid after this call and cannot be dereferenced anymore.
If mem is NULL, this function does nothing.
Parameters
mem a pointer to allocated memory, or NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_malloc
SDL_calloc
SDL_realloc
{
    if (!ptr) {
        return;
    }
    s_mem.free_func(ptr);
    DECREMENT_ALLOCATION_COUNT();
}
References DECREMENT_ALLOCATION_COUNT, and s_mem.
Referenced by AttemptSensorFusion(), CleanupFreeableProperty(), CleanupHintProperty(), CleanupLogPrefixes(), CleanupLogPriorities(), convert_ext_list(), convert_filter(), convert_filters(), CopyOneProperty(), create_zenity_args(), CreatePhysicalAudioDevice(), createWindow(), DBus_MessageFilter(), decode_edid(), deleteDevice(), DeleteHIDDeviceWrapper(), DestroyCameraHashItem(), DestroyLogicalAudioDevice(), DestroyMemoryPool(), DestroyPhysicalAudioDevice(), DestroySDLMenu(), DUMMYAUDIO_CloseDevice(), dynamic_mem_close(), escape_label(), FcitxClientCreateIC(), fd_close(), free_zenity_args(), FreeAllocatedAudioBuffer(), FreeMemoryPoolBlock(), freeWinArgs(), freeWinFArgs(), generic_asyncio_destroy(), generic_asyncioqueue_destroy(), GENERIC_CloseStorage(), GENERIC_CopyStorageFile(), GENERIC_CreateStorageDirectory(), GENERIC_EnumerateDirectory(), GENERIC_EnumerateStorageDirectory(), GENERIC_GetStoragePathInfo(), GENERIC_OpenFileStorage(), GENERIC_ReadStorageFile(), GENERIC_RemoveStoragePath(), GENERIC_RenameStoragePath(), GENERIC_Title_Create(), GENERIC_User_Create(), GENERIC_WriteStorageFile(), GetAsyncIOTaskOutcome(), GetFileModificationTime(), glGetConfig(), GlobDirectoryCallback(), IgnoredDevicesChanged(), IMA_ADPCM_Decode(), IOS_RemoveJoystickDevice(), IsROGAlly(), LAW_Decode(), mem_close(), MS_ADPCM_Decode(), PopMappingChangeTracking(), PS2AUDIO_CloseDevice(), register_string_error_to_buffer(), register_winapi_error_to_buffer(), RequestAsyncIO(), ResetHintsCallback(), resize(), run_zenity(), RunInputThread(), SDL_AddCamera(), SDL_AddFullscreenDisplayMode(), SDL_AddGamepadMappingsFromIO(), SDL_AddHintCallback(), SDL_AddPenDevice(), SDL_AddVideoDisplay(), SDL_aligned_free(), SDL_ALLOC_SIZE(), SDL_AsyncIOFromFile(), SDL_CameraInit(), SDL_CleanupTemporaryMemory(), SDL_CleanupTLS(), SDL_CleanupTrays(), SDL_CleanupWindowTextureData(), SDL_CloseAsyncIO(), SDL_CloseGamepad(), SDL_CloseHaptic(), SDL_CloseIO(), SDL_CloseJoystick(), SDL_CloseSensor(), SDL_CloseStorage(), SDL_ConvertAudioSamples(), SDL_CreateAsyncIOQueue(), SDL_CreateAudioStream(), SDL_CreateCondition(), SDL_CreateDirectory(), SDL_CreateEnvironment(), SDL_CreateMainThreadCallback(), SDL_CreateMutex(), SDL_CreatePalette(), SDL_CreateProperties(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateTimer(), SDL_CreateTray(), SDL_CreateWindowTexture(), SDL_DelTouch(), SDL_DelVideoDisplay(), SDL_DestroyAsyncIOQueue(), SDL_DestroyAudioQueue(), SDL_DestroyAudioStream(), SDL_DestroyCondition(), SDL_DestroyCondition_cv(), SDL_DestroyCursor(), SDL_DestroyEnvironment(), SDL_DestroyGPURenderState(), SDL_DestroyHashKey(), SDL_DestroyHashKeyAndValue(), SDL_DestroyHashTable(), SDL_DestroyHashValue(), SDL_DestroyKeymap(), SDL_DestroyMainThreadCallback(), SDL_DestroyMutex(), SDL_DestroyPalette(), SDL_DestroyProcess(), SDL_DestroyRenderer(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroyRWLock(), SDL_DestroyRWLock_srw(), SDL_DestroySemaphore(), SDL_DestroySurface(), SDL_DestroyTextureInternal(), SDL_DestroyTray(), SDL_DestroyWindow(), SDL_DiscardAllCommands(), SDL_Fcitx_Quit(), SDL_FreeClipboardMimeTypes(), SDL_FreeProperties(), SDL_FreePropertyWithCleanup(), SDL_FreeSteamVirtualGamepadInfo(), SDL_FreeTemporaryMemoryEntry(), SDL_FreeVIDPIDList(), SDL_Generic_QuitTLSData(), SDL_Generic_SetTLSData(), SDL_GetClipboardData(), SDL_GetGamepadMappings(), SDL_GetPixelFormatDetails(), SDL_GetSurfaceImage(), SDL_GetTemporaryMemoryState(), SDL_Haptic_Get_Naxes(), SDL_HasGamepad(), SDL_hid_exit(), SDL_hid_free_enumeration(), SDL_iconv_close(), SDL_iconv_string(), SDL_InitAudio(), SDL_InitGamepads(), SDL_InsertTrayEntryAt(), SDL_InternalGlobDirectory(), SDL_InvalidateMap(), SDL_IOFromConstMem(), SDL_IOFromDynamicMem(), SDL_IOFromFile(), SDL_IOFromMem(), SDL_IOprintf(), SDL_IOvprintf(), SDL_ListClear(), SDL_ListPop(), SDL_ListRemove(), SDL_LoadFile_IO(), SDL_LoadFileAsync(), SDL_LoadGamepadHints(), SDL_LoadVIDPIDListFromHint(), SDL_LoadWAV_IO(), SDL_LogMessageV(), SDL_LogOutput(), SDL_OpenAudioDevice(), SDL_OpenGamepad(), SDL_OpenHaptic(), SDL_OpenHapticFromJoystick(), SDL_OpenJoystick(), SDL_OpenSensor(), SDL_PrintStringW(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateParseGamepadElement(), SDL_PromptAssertion(), SDL_PutAudioStreamData(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitEventWatchList(), SDL_QuitFilesystem(), SDL_QuitGamepadMappings(), SDL_QuitJoysticks(), SDL_QuitKeyboard(), SDL_QuitMouse(), SDL_QuitPen(), SDL_QuitSteamVirtualGamepadInfo(), SDL_QuitTimers(), SDL_QuitTouch(), SDL_RemoveAllPenDevices(), SDL_RemoveHintCallback(), SDL_RemoveKeyboard(), SDL_RemoveMouse(), SDL_RemovePenDevice(), SDL_RemoveSurfaceAlternateImages(), SDL_RemoveTimer(), SDL_RemoveTrayEntry(), SDL_RenderDebugTextFormat(), SDL_ResetFullscreenDisplayModes(), SDL_ResetHint(), SDL_RunThread(), SDL_SetAudioStreamFormat(), SDL_SetClipboardData(), SDL_SetClipboardText(), SDL_SetDefaultCursor(), SDL_SetDesktopDisplayMode(), SDL_setenv_unsafe(), SDL_SetEnvironmentVariable(), SDL_SetGPURenderStateFragmentUniforms(), SDL_SetHintWithPriority(), SDL_SetLogPriorityPrefix(), SDL_SetPrimarySelectionText(), SDL_SetStringProperty(), SDL_SetTLS(), SDL_SetTrayEntryLabel(), SDL_SetTrayTooltip(), SDL_SetWindowTitle(), SDL_StopEventLoop(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), SDL_SYS_GetBasePath(), SDL_SYS_GetPrefPath(), SDL_SYS_OpenURL(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UnregisterTray(), SDL_UpdateAudio(), SDL_UpdateCamera(), SDL_UpdateDesktopBounds(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_UpdateTextureNative(), SDL_vasprintf(), SDL_VideoQuit(), SDL_vswprintf(), SDL_WaitThread(), SDL_WSCONS_Init_Keyboard(), SDL_WSCONS_Init_Mouse(), SDL_WSCONS_Quit(), SDL_WSCONS_Quit_Mouse(), SetAudioStreamChannelMap(), ShowFileDialog(), STEAM_CloseStorage(), STEAM_User_Create(), TryOpenInRomfs(), WaveFreeChunkData(), win_get_filters(), windows_ShowFileDialog(), and windows_ShowFolderDialog().
SDL_getenv()
SDL_DECLSPEC const char *SDLCALL SDL_getenv (const char * name) extern
Get the value of a variable in the environment.
This function uses SDL's cached copy of the environment and is thread-safe.
Parameters
name the name of the variable to get.
Returns
a pointer to the value of the variable or NULL if it can't be found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return SDL_GetEnvironmentVariable(SDL_GetEnvironment(), name);
}
References SDL_GetEnvironment(), and SDL_GetEnvironmentVariable().
Referenced by GetHintEnvironmentVariable(), getlocale(), InitIME(), SDL_DetectSandbox(), SDL_SetEnvironmentVariable(), SDL_SetHapticGain(), and SDL_SYS_GetPreferredLocales().
SDL_getenv_unsafe()
SDL_DECLSPEC const char *SDLCALL SDL_getenv_unsafe (const char * name) extern
Get the value of a variable in the environment.
This function bypasses SDL's cached copy of the environment and is not thread-safe.
Parameters
name the name of the variable to get.
Returns
a pointer to the value of the variable or NULL if it can't be found.
Thread Safety
This function is not thread safe, consider using SDL_getenv() instead.
Since
This function is available since SDL 3.2.0.
See also
SDL_getenv
{
    size_t len, i;
    const char *value = NULL;
    // Input validation
    if (!name || *name == '\0') {
        return NULL;
    }
    if (environ) {
        len = SDL_strlen(name);
        for (i = 0; environ[i]; ++i) {
            if ((SDL_strncmp(environ[i], name, len) == 0) &&
                (environ[i][len] == '=')) {
                value = &environ[i][len + 1];
                break;
            }
        }
    }
    return value;
}
References environ, NULL, SDL_strlen(), and SDL_strncmp().
Referenced by SDL_setenv_unsafe(), and SDL_SetEnvironmentVariable().
SDL_GetEnvironment()
SDL_DECLSPEC SDL_Environment *SDLCALL SDL_GetEnvironment (void) extern
Get the process environment.
This is initialized at application start and is not affected by setenv() and unsetenv() calls after that point. Use SDL_SetEnvironmentVariable() and SDL_UnsetEnvironmentVariable() if you want to modify this environment, or SDL_setenv_unsafe() or SDL_unsetenv_unsafe() if you want changes to persist in the C runtime environment after SDL_Quit().
Returns
a pointer to the environment for the process or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironmentVariable
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    if (!SDL_environment) {
        SDL_environment = SDL_CreateEnvironment(true);
    }
    return SDL_environment;
}
References SDL_CreateEnvironment(), and SDL_environment.
Referenced by SDL_getenv(), SDL_InitEnvironment(), SDL_setenv_unsafe(), and SDL_unsetenv_unsafe().
SDL_GetEnvironmentVariable()
SDL_DECLSPEC const char *SDLCALL SDL_GetEnvironmentVariable (SDL_Environment * env, const char * name) extern
Get the value of a variable in the environment.
Parameters
env the environment to query.
name the name of the variable to get.
Returns
a pointer to the value of the variable or NULL if it can't be found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    const char *result = NULL;
    if (!env) {
        return NULL;
    } else if (!name || *name == '\0') {
        return NULL;
    }
    SDL_LockMutex(env->lock);
    {
        const char *value;
        if (SDL_FindInHashTable(env->strings, name, (const void **)&value)) {
            result = SDL_GetPersistentString(value);
        }
    }
    SDL_UnlockMutex(env->lock);
    return result;
}
References SDL_Environment::lock, NULL, SDL_FindInHashTable(), SDL_GetPersistentString(), SDL_LockMutex(), SDL_UnlockMutex(), and SDL_Environment::strings.
Referenced by SDL_CreateEnvironment(), and SDL_getenv().
SDL_GetEnvironmentVariables()
SDL_DECLSPEC char **SDLCALL SDL_GetEnvironmentVariables (SDL_Environment * env) extern
Get all variables in the environment.
Parameters
env the environment to query.
Returns
a NULL terminated array of pointers to environment variables in the form "variable=value" or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    char **result = NULL;
    if (!env) {
        SDL_InvalidParamError("env");
        return NULL;
    }
    SDL_LockMutex(env->lock);
    {
        // First pass, get the size we need for all the strings
        CountEnvStringsData countdata = { 0, 0 };
        SDL_IterateHashTable(env->strings, CountEnvStrings, &countdata);
        // Allocate memory for the strings
        result = (char **)SDL_malloc((countdata.count + 1) * sizeof(*result) + countdata.length);
        if (result) {
            // Second pass, copy the strings
            char *string = (char *)(result + countdata.count + 1);
            CopyEnvStringsData cpydata = { result, string, 0 };
            SDL_IterateHashTable(env->strings, CopyEnvStrings, &cpydata);
            SDL_assert(countdata.count == cpydata.count);
            result[cpydata.count] = NULL;
        }
    }
    SDL_UnlockMutex(env->lock);
    return result;
}
References CopyEnvStrings(), CopyEnvStringsData::count, CountEnvStringsData::count, CountEnvStrings(), CountEnvStringsData::length, SDL_Environment::lock, NULL, SDL_assert, SDL_InvalidParamError, SDL_IterateHashTable(), SDL_LockMutex(), SDL_malloc(), SDL_UnlockMutex(), and SDL_Environment::strings.
Referenced by SDL_CreateEnvironment().
SDL_GetMemoryFunctions()
SDL_DECLSPEC void SDLCALL SDL_GetMemoryFunctions (SDL_malloc_func * malloc_func, SDL_calloc_func * calloc_func, SDL_realloc_func * realloc_func, SDL_free_func * free_func) extern
Get the current set of SDL memory functions.
Parameters
malloc_func filled with malloc function.
calloc_func filled with calloc function.
realloc_func filled with realloc function.
free_func filled with free function.
Thread Safety
This does not hold a lock, so do not call this in the unlikely event of a background thread calling SDL_SetMemoryFunctions simultaneously.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetMemoryFunctions
SDL_GetOriginalMemoryFunctions
{
    if (malloc_func) {
        *malloc_func = s_mem.malloc_func;
    }
    if (calloc_func) {
        *calloc_func = s_mem.calloc_func;
    }
    if (realloc_func) {
        *realloc_func = s_mem.realloc_func;
    }
    if (free_func) {
        *free_func = s_mem.free_func;
    }
}
References calloc_func, free_func, malloc_func, realloc_func, and s_mem.
SDL_GetNumAllocations()
SDL_DECLSPEC int SDLCALL SDL_GetNumAllocations (void) extern
Get the number of outstanding (unfreed) allocations.
Returns
the number of allocations or -1 if allocation counting is disabled.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_TRACK_ALLOCATION_COUNT
    return SDL_GetAtomicInt(&s_mem.num_allocations);
#else
    return -1;
#endif
}
References s_mem, and SDL_GetAtomicInt().
SDL_GetOriginalMemoryFunctions()
SDL_DECLSPEC void SDLCALL SDL_GetOriginalMemoryFunctions (SDL_malloc_func * malloc_func, SDL_calloc_func * calloc_func, SDL_realloc_func * realloc_func, SDL_free_func * free_func) extern
Get the original set of SDL memory functions.
This is what SDL_malloc and friends will use by default, if there has been no call to SDL_SetMemoryFunctions. This is not necessarily using the C runtime's malloc functions behind the scenes! Different platforms and build configurations might do any number of unexpected things.
Parameters
malloc_func filled with malloc function.
calloc_func filled with calloc function.
realloc_func filled with realloc function.
free_func filled with free function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (malloc_func) {
        *malloc_func = real_malloc;
    }
    if (calloc_func) {
        *calloc_func = real_calloc;
    }
    if (realloc_func) {
        *realloc_func = real_realloc;
    }
    if (free_func) {
        *free_func = real_free;
    }
}
References calloc_func, free_func, malloc_func, real_calloc, real_free, real_malloc, real_realloc, and realloc_func.
Referenced by SDL_GetErrBuf().
SDL_iconv()
SDL_DECLSPEC size_t SDLCALL SDL_iconv (SDL_iconv_t cd, const char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft) extern
This function converts text between encodings, reading from and writing to a buffer.
It returns the number of succesful conversions on success. On error, SDL_ICONV_E2BIG is returned when the output buffer is too small, or SDL_ICONV_EILSEQ is returned when an invalid input sequence is encountered, or SDL_ICONV_EINVAL is returned when an incomplete input sequence is encountered.
On exit:
inbuf will point to the beginning of the next multibyte sequence. On error, this is the location of the problematic input sequence. On success, this is the end of the input sequence.
inbytesleft will be set to the number of bytes left to convert, which will be 0 on success.
outbuf will point to the location where to store the next output byte.
outbytesleft will be set to the number of bytes left in the output buffer.
Parameters
cd The character set conversion context, created in SDL_iconv_open().
inbuf Address of variable that points to the first character of the input sequence.
inbytesleft The number of bytes in the input buffer.
outbuf Address of variable that points to the output buffer.
outbytesleft The number of bytes in the output buffer.
Returns
the number of conversions on success, or a negative error code.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv_open
SDL_iconv_close
SDL_iconv_string
{
    // For simplicity, we'll convert everything to and from UCS-4
    const char *src;
    char *dst;
    size_t srclen, dstlen;
    Uint32 ch = 0;
    size_t total;
    if ((size_t)cd == SDL_ICONV_ERROR) {
        return SDL_ICONV_ERROR;
    }
    if (!inbuf || !*inbuf) {
        // Reset the context
        return 0;
    }
    if (!outbuf || !*outbuf || !outbytesleft || !*outbytesleft) {
        return SDL_ICONV_E2BIG;
    }
    src = *inbuf;
    srclen = (inbytesleft ? *inbytesleft : 0);
    dst = *outbuf;
    dstlen = *outbytesleft;
    switch (cd->src_fmt) {
    case ENCODING_UTF16:
        // Scan for a byte order marker
        {
            Uint8 *p = (Uint8 *)src;
            size_t n = srclen / 2;
            while (n) {
                if (p[0] == 0xFF && p[1] == 0xFE) {
                    cd->src_fmt = ENCODING_UTF16BE;
                    break;
                } else if (p[0] == 0xFE && p[1] == 0xFF) {
                    cd->src_fmt = ENCODING_UTF16LE;
                    break;
                }
                p += 2;
                --n;
            }
            if (n == 0) {
                // We can't tell, default to host order
                cd->src_fmt = ENCODING_UTF16NATIVE;
            }
        }
        break;
    case ENCODING_UTF32:
        // Scan for a byte order marker
        {
            Uint8 *p = (Uint8 *)src;
            size_t n = srclen / 4;
            while (n) {
                if (p[0] == 0xFF && p[1] == 0xFE &&
                    p[2] == 0x00 && p[3] == 0x00) {
                    cd->src_fmt = ENCODING_UTF32BE;
                    break;
                } else if (p[0] == 0x00 && p[1] == 0x00 &&
                           p[2] == 0xFE && p[3] == 0xFF) {
                    cd->src_fmt = ENCODING_UTF32LE;
                    break;
                }
                p += 4;
                --n;
            }
            if (n == 0) {
                // We can't tell, default to host order
                cd->src_fmt = ENCODING_UTF32NATIVE;
            }
        }
        break;
    }
    switch (cd->dst_fmt) {
    case ENCODING_UTF16:
        // Default to host order, need to add byte order marker
        if (dstlen < 2) {
            return SDL_ICONV_E2BIG;
        }
        *(Uint16 *)dst = UNICODE_BOM;
        dst += 2;
        dstlen -= 2;
        cd->dst_fmt = ENCODING_UTF16NATIVE;
        break;
    case ENCODING_UTF32:
        // Default to host order, need to add byte order marker
        if (dstlen < 4) {
            return SDL_ICONV_E2BIG;
        }
        *(Uint32 *)dst = UNICODE_BOM;
        dst += 4;
        dstlen -= 4;
        cd->dst_fmt = ENCODING_UTF32NATIVE;
        break;
    }
    total = 0;
    while (srclen > 0) {
        // Decode a character
        switch (cd->src_fmt) {
        case ENCODING_ASCII:
        {
            Uint8 *p = (Uint8 *)src;
            ch = (Uint32)(p[0] & 0x7F);
            ++src;
            --srclen;
        } break;
        case ENCODING_LATIN1:
        {
            Uint8 *p = (Uint8 *)src;
            ch = (Uint32)p[0];
            ++src;
            --srclen;
        } break;
        case ENCODING_UTF8: // RFC 3629
        {
            Uint8 *p = (Uint8 *)src;
            size_t left = 0;
            bool overlong = false;
            if (p[0] >= 0xF0) {
                if ((p[0] & 0xF8) != 0xF0) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    if (p[0] == 0xF0 && srclen > 1 && (p[1] & 0xF0) == 0x80) {
                        overlong = true;
                    }
                    ch = (Uint32)(p[0] & 0x07);
                    left = 3;
                }
            } else if (p[0] >= 0xE0) {
                if ((p[0] & 0xF0) != 0xE0) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    if (p[0] == 0xE0 && srclen > 1 && (p[1] & 0xE0) == 0x80) {
                        overlong = true;
                    }
                    ch = (Uint32)(p[0] & 0x0F);
                    left = 2;
                }
            } else if (p[0] >= 0xC0) {
                if ((p[0] & 0xE0) != 0xC0) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    if ((p[0] & 0xDE) == 0xC0) {
                        overlong = true;
                    }
                    ch = (Uint32)(p[0] & 0x1F);
                    left = 1;
                }
            } else {
                if (p[0] & 0x80) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    ch = (Uint32)p[0];
                }
            }
            ++src;
            --srclen;
            if (srclen < left) {
                return SDL_ICONV_EINVAL;
            }
            while (left--) {
                ++p;
                if ((p[0] & 0xC0) != 0x80) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                    break;
                }
                ch <<= 6;
                ch |= (p[0] & 0x3F);
                ++src;
                --srclen;
            }
            if (overlong) {
                /* Potential security risk
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
            }
            if ((ch >= 0xD800 && ch <= 0xDFFF) ||
                (ch == 0xFFFE || ch == 0xFFFF) || ch > 0x10FFFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
            }
        } break;
        case ENCODING_UTF16BE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)src;
            Uint16 W1, W2;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            W1 = ((Uint16)p[0] << 8) | (Uint16)p[1];
            src += 2;
            srclen -= 2;
            if (W1 < 0xD800 || W1 > 0xDFFF) {
                ch = (Uint32)W1;
                break;
            }
            if (W1 > 0xDBFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            p = (Uint8 *)src;
            W2 = ((Uint16)p[0] << 8) | (Uint16)p[1];
            src += 2;
            srclen -= 2;
            if (W2 < 0xDC00 || W2 > 0xDFFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            ch = (((Uint32)(W1 & 0x3FF) << 10) |
                  (Uint32)(W2 & 0x3FF)) +
                 0x10000;
        } break;
        case ENCODING_UTF16LE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)src;
            Uint16 W1, W2;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            W1 = ((Uint16)p[1] << 8) | (Uint16)p[0];
            src += 2;
            srclen -= 2;
            if (W1 < 0xD800 || W1 > 0xDFFF) {
                ch = (Uint32)W1;
                break;
            }
            if (W1 > 0xDBFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            p = (Uint8 *)src;
            W2 = ((Uint16)p[1] << 8) | (Uint16)p[0];
            src += 2;
            srclen -= 2;
            if (W2 < 0xDC00 || W2 > 0xDFFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            ch = (((Uint32)(W1 & 0x3FF) << 10) |
                  (Uint32)(W2 & 0x3FF)) +
                 0x10000;
        } break;
        case ENCODING_UCS2LE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[1] << 8) | (Uint32)p[0];
            src += 2;
            srclen -= 2;
        } break;
        case ENCODING_UCS2BE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[0] << 8) | (Uint32)p[1];
            src += 2;
            srclen -= 2;
        } break;
        case ENCODING_UCS4BE:
        case ENCODING_UTF32BE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 4) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[0] << 24) |
                 ((Uint32)p[1] << 16) |
                 ((Uint32)p[2] << 8) | (Uint32)p[3];
            src += 4;
            srclen -= 4;
        } break;
        case ENCODING_UCS4LE:
        case ENCODING_UTF32LE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 4) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[3] << 24) |
                 ((Uint32)p[2] << 16) |
                 ((Uint32)p[1] << 8) | (Uint32)p[0];
            src += 4;
            srclen -= 4;
        } break;
        }
        // Encode a character
        switch (cd->dst_fmt) {
        case ENCODING_ASCII:
        {
            Uint8 *p = (Uint8 *)dst;
            if (dstlen < 1) {
                return SDL_ICONV_E2BIG;
            }
            if (ch > 0x7F) {
                *p = UNKNOWN_ASCII;
            } else {
                *p = (Uint8)ch;
            }
            ++dst;
            --dstlen;
        } break;
        case ENCODING_LATIN1:
        {
            Uint8 *p = (Uint8 *)dst;
            if (dstlen < 1) {
                return SDL_ICONV_E2BIG;
            }
            if (ch > 0xFF) {
                *p = UNKNOWN_ASCII;
            } else {
                *p = (Uint8)ch;
            }
            ++dst;
            --dstlen;
        } break;
        case ENCODING_UTF8: // RFC 3629
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (ch <= 0x7F) {
                if (dstlen < 1) {
                    return SDL_ICONV_E2BIG;
                }
                *p = (Uint8)ch;
                ++dst;
                --dstlen;
            } else if (ch <= 0x7FF) {
                if (dstlen < 2) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = 0xC0 | (Uint8)((ch >> 6) & 0x1F);
                p[1] = 0x80 | (Uint8)(ch & 0x3F);
                dst += 2;
                dstlen -= 2;
            } else if (ch <= 0xFFFF) {
                if (dstlen < 3) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = 0xE0 | (Uint8)((ch >> 12) & 0x0F);
                p[1] = 0x80 | (Uint8)((ch >> 6) & 0x3F);
                p[2] = 0x80 | (Uint8)(ch & 0x3F);
                dst += 3;
                dstlen -= 3;
            } else {
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = 0xF0 | (Uint8)((ch >> 18) & 0x07);
                p[1] = 0x80 | (Uint8)((ch >> 12) & 0x3F);
                p[2] = 0x80 | (Uint8)((ch >> 6) & 0x3F);
                p[3] = 0x80 | (Uint8)(ch & 0x3F);
                dst += 4;
                dstlen -= 4;
            }
        } break;
        case ENCODING_UTF16BE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (ch < 0x10000) {
                if (dstlen < 2) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = (Uint8)(ch >> 8);
                p[1] = (Uint8)ch;
                dst += 2;
                dstlen -= 2;
            } else {
                Uint16 W1, W2;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                ch = ch - 0x10000;
                W1 = 0xD800 | (Uint16)((ch >> 10) & 0x3FF);
                W2 = 0xDC00 | (Uint16)(ch & 0x3FF);
                p[0] = (Uint8)(W1 >> 8);
                p[1] = (Uint8)W1;
                p[2] = (Uint8)(W2 >> 8);
                p[3] = (Uint8)W2;
                dst += 4;
                dstlen -= 4;
            }
        } break;
        case ENCODING_UTF16LE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (ch < 0x10000) {
                if (dstlen < 2) {
                    return SDL_ICONV_E2BIG;
                }
                p[1] = (Uint8)(ch >> 8);
                p[0] = (Uint8)ch;
                dst += 2;
                dstlen -= 2;
            } else {
                Uint16 W1, W2;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                ch = ch - 0x10000;
                W1 = 0xD800 | (Uint16)((ch >> 10) & 0x3FF);
                W2 = 0xDC00 | (Uint16)(ch & 0x3FF);
                p[1] = (Uint8)(W1 >> 8);
                p[0] = (Uint8)W1;
                p[3] = (Uint8)(W2 >> 8);
                p[2] = (Uint8)W2;
                dst += 4;
                dstlen -= 4;
            }
        } break;
        case ENCODING_UCS2BE:
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0xFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (dstlen < 2) {
                return SDL_ICONV_E2BIG;
            }
            p[0] = (Uint8)(ch >> 8);
            p[1] = (Uint8)ch;
            dst += 2;
            dstlen -= 2;
        } break;
        case ENCODING_UCS2LE:
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0xFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (dstlen < 2) {
                return SDL_ICONV_E2BIG;
            }
            p[1] = (Uint8)(ch >> 8);
            p[0] = (Uint8)ch;
            dst += 2;
            dstlen -= 2;
        } break;
        case ENCODING_UTF32BE:
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            SDL_FALLTHROUGH;
        case ENCODING_UCS4BE:
            if (ch > 0x7FFFFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            {
                Uint8 *p = (Uint8 *)dst;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = (Uint8)(ch >> 24);
                p[1] = (Uint8)(ch >> 16);
                p[2] = (Uint8)(ch >> 8);
                p[3] = (Uint8)ch;
                dst += 4;
                dstlen -= 4;
            }
            break;
        case ENCODING_UTF32LE:
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            SDL_FALLTHROUGH;
        case ENCODING_UCS4LE:
            if (ch > 0x7FFFFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            {
                Uint8 *p = (Uint8 *)dst;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                p[3] = (Uint8)(ch >> 24);
                p[2] = (Uint8)(ch >> 16);
                p[1] = (Uint8)(ch >> 8);
                p[0] = (Uint8)ch;
                dst += 4;
                dstlen -= 4;
            }
            break;
        }
        // Update state
        *inbuf = src;
        *inbytesleft = srclen;
        *outbuf = dst;
        *outbytesleft = dstlen;
        ++total;
    }
    return total;
}
References SDL_iconv_data_t::dst_fmt, ENCODING_ASCII, ENCODING_LATIN1, ENCODING_UCS2BE, ENCODING_UCS2LE, ENCODING_UCS4BE, ENCODING_UCS4LE, ENCODING_UTF16, ENCODING_UTF16BE, ENCODING_UTF16LE, ENCODING_UTF16NATIVE, ENCODING_UTF32, ENCODING_UTF32BE, ENCODING_UTF32LE, ENCODING_UTF32NATIVE, ENCODING_UTF8, left, SDL_FALLTHROUGH, SDL_ICONV_E2BIG, SDL_ICONV_EINVAL, SDL_ICONV_ERROR, SDL_iconv_data_t::src_fmt, UNICODE_BOM, UNKNOWN_ASCII, and UNKNOWN_UNICODE.
Referenced by SDL_iconv_string().
SDL_iconv_close()
SDL_DECLSPEC int SDLCALL SDL_iconv_close (SDL_iconv_t cd) extern
This function frees a context used for character set conversion.
Parameters
cd The character set conversion handle.
Returns
0 on success, or -1 on failure.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv
SDL_iconv_open
SDL_iconv_string
{
    if (cd == (SDL_iconv_t)-1) {
        return -1;
    }
    SDL_free(cd);
    return 0;
}
References SDL_free().
Referenced by SDL_iconv_string().
SDL_iconv_open()
SDL_DECLSPEC SDL_iconv_t SDLCALL SDL_iconv_open (const char * tocode, const char * fromcode) extern
This function allocates a context for the specified character set conversion.
Parameters
tocode The target character encoding, must not be NULL.
fromcode The source character encoding, must not be NULL.
Returns
a handle that must be freed with SDL_iconv_close, or SDL_ICONV_ERROR on failure.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv
SDL_iconv_close
SDL_iconv_string
{
    int src_fmt = ENCODING_UNKNOWN;
    int dst_fmt = ENCODING_UNKNOWN;
    int i;
    char fromcode_buffer[64];
    char tocode_buffer[64];
    if (!fromcode || !*fromcode) {
        fromcode = getlocale(fromcode_buffer, sizeof(fromcode_buffer));
    }
    if (!tocode || !*tocode) {
        tocode = getlocale(tocode_buffer, sizeof(tocode_buffer));
    }
    for (i = 0; i < SDL_arraysize(encodings); ++i) {
        if (SDL_strcasecmp(fromcode, encodings[i].name) == 0) {
            src_fmt = encodings[i].format;
            if (dst_fmt != ENCODING_UNKNOWN) {
                break;
            }
        }
        if (SDL_strcasecmp(tocode, encodings[i].name) == 0) {
            dst_fmt = encodings[i].format;
            if (src_fmt != ENCODING_UNKNOWN) {
                break;
            }
        }
    }
    if (src_fmt != ENCODING_UNKNOWN && dst_fmt != ENCODING_UNKNOWN) {
        SDL_iconv_t cd = (SDL_iconv_t)SDL_malloc(sizeof(*cd));
        if (cd) {
            cd->src_fmt = src_fmt;
            cd->dst_fmt = dst_fmt;
            return cd;
        }
    }
    return (SDL_iconv_t)-1;
}
References SDL_iconv_data_t::dst_fmt, ENCODING_UNKNOWN, encodings, getlocale(), SDL_arraysize, SDL_malloc(), SDL_strcasecmp(), and SDL_iconv_data_t::src_fmt.
Referenced by SDL_iconv_string().
SDL_iconv_string()
SDL_DECLSPEC char *SDLCALL SDL_iconv_string (const char * tocode, const char * fromcode, const char * inbuf, size_t inbytesleft) extern
Helper function to convert a string's encoding in one call.
This function converts a buffer or string between encodings in one pass.
The string does not need to be NULL-terminated; this function operates on the number of bytes specified in inbytesleft whether there is a NULL character anywhere in the buffer.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
tocode the character encoding of the output string. Examples are "UTF-8", "UCS-4", etc.
fromcode the character encoding of data in inbuf.
inbuf the string to convert to a different encoding.
inbytesleft the size of the input string in bytes.
Returns
a new string, converted to the new encoding, or NULL on error.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv_open
SDL_iconv_close
SDL_iconv
{
    SDL_iconv_t cd;
    char *string;
    size_t stringsize;
    char *outbuf;
    size_t outbytesleft;
    size_t retCode = 0;
    if (!tocode || !*tocode) {
        tocode = "UTF-8";
    }
    if (!fromcode || !*fromcode) {
        fromcode = "UTF-8";
    }
    cd = SDL_iconv_open(tocode, fromcode);
    if (cd == (SDL_iconv_t)-1) {
        return NULL;
    }
    stringsize = inbytesleft;
    string = (char *)SDL_malloc(stringsize + sizeof(Uint32));
    if (!string) {
        SDL_iconv_close(cd);
        return NULL;
    }
    outbuf = string;
    outbytesleft = stringsize;
    SDL_memset(outbuf, 0, sizeof(Uint32));
    while (inbytesleft > 0) {
        const size_t oldinbytesleft = inbytesleft;
        retCode = SDL_iconv(cd, &inbuf, &inbytesleft, &outbuf, &outbytesleft);
        switch (retCode) {
        case SDL_ICONV_E2BIG:
        {
            const ptrdiff_t diff = (ptrdiff_t) (outbuf - string);
            char *oldstring = string;
            stringsize *= 2;
            string = (char *)SDL_realloc(string, stringsize + sizeof(Uint32));
            if (!string) {
                SDL_free(oldstring);
                SDL_iconv_close(cd);
                return NULL;
            }
            outbuf = string + diff;
            outbytesleft = stringsize - diff;
            SDL_memset(outbuf, 0, sizeof(Uint32));
            continue;
        }
        case SDL_ICONV_EILSEQ:
            // Try skipping some input data - not perfect, but...
            ++inbuf;
            --inbytesleft;
            break;
        case SDL_ICONV_EINVAL:
        case SDL_ICONV_ERROR:
            // We can't continue...
            inbytesleft = 0;
            break;
        }
        // Avoid infinite loops when nothing gets converted
        if (oldinbytesleft == inbytesleft) {
            break;
        }
    }
    SDL_memset(outbuf, 0, sizeof(Uint32));
    SDL_iconv_close(cd);
    return string;
}
References NULL, SDL_free(), SDL_iconv(), SDL_iconv_close(), SDL_ICONV_E2BIG, SDL_ICONV_EILSEQ, SDL_ICONV_EINVAL, SDL_ICONV_ERROR, SDL_iconv_open(), SDL_malloc(), SDL_memset, and SDL_realloc().
Referenced by SDL_PrintStringW(), and SDL_vswprintf().
SDL_isalnum()
SDL_DECLSPEC int SDLCALL SDL_isalnum (int x) extern
Query if a character is alphabetic (a letter) or a number.
WARNING: Regardless of system locale, this will only treat ASCII values for English 'a-z', 'A-Z', and '0-9' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (SDL_isalpha(x)) || (SDL_isdigit(x)); }
References SDL_isalpha(), and SDL_isdigit().
Referenced by SDL_ispunct().
SDL_isalpha()
SDL_DECLSPEC int SDLCALL SDL_isalpha (int x) extern
Query if a character is alphabetic (a letter).
WARNING: Regardless of system locale, this will only treat ASCII values for English 'a-z' and 'A-Z' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (SDL_isupper(x)) || (SDL_islower(x)); }
References SDL_islower(), and SDL_isupper().
Referenced by SDL_isalnum().
SDL_isblank()
SDL_DECLSPEC int SDLCALL SDL_isblank (int x) extern
Report if a character is blank (a space or tab).
WARNING: Regardless of system locale, this will only treat ASCII values 0x20 (space) or 0x9 (tab) as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) == ' ') || ((x) == '\t'); }
SDL_iscntrl()
SDL_DECLSPEC int SDLCALL SDL_iscntrl (int x) extern
Report if a character is a control character.
WARNING: Regardless of system locale, this will only treat ASCII values 0 through 0x1F, and 0x7F, as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (((x) >= '\0') && ((x) <= '\x1f')) || ((x) == '\x7f'); }
Referenced by SDL_SendKeyboardText().
SDL_isdigit()
SDL_DECLSPEC int SDLCALL SDL_isdigit (int x) extern
Report if a character is a numeric digit.
WARNING: Regardless of system locale, this will only treat ASCII values '0' (0x30) through '9' (0x39), as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= '0') && ((x) <= '9'); }
Referenced by ParseLogCategory(), ParseLogPriority(), SDL_GetStringInteger(), SDL_isalnum(), SDL_isxdigit(), SDL_PrivateParseGamepadElement(), SDL_ScanFloat(), and SDL_SetKeymap().
SDL_isgraph()
SDL_DECLSPEC int SDLCALL SDL_isgraph (int x) extern
Report if a character is any "printable" except space.
Be advised that "printable" has a definition that goes back to text terminals from the dawn of computing, making this a sort of special case function that is not suitable for Unicode (or most any) text management.
WARNING: Regardless of system locale, this is equivalent to ‘(SDL_isprint(x)) && ((x) != ’ ')`.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isprint
{ return (SDL_isprint(x)) && ((x) != ' '); }
References SDL_isprint().
Referenced by SDL_ispunct().
SDL_isinf()
SDL_DECLSPEC int SDLCALL SDL_isinf (double x) extern
Return whether the value is infinity.
Parameters
x double-precision floating point value.
Returns
non-zero if the value is infinity, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isinff
{
#ifdef HAVE_ISINF
    return isinf(x);
#else
    return SDL_uclibc_isinf(x);
#endif
}
References SDL_uclibc_isinf().
SDL_isinff()
SDL_DECLSPEC int SDLCALL SDL_isinff (float x) extern
Return whether the value is infinity.
Parameters
x floating point value.
Returns
non-zero if the value is infinity, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isinf
{
#ifdef HAVE_ISINF_FLOAT_MACRO
    return isinf(x);
#elif defined(HAVE_ISINFF)
    return isinff(x);
#else
    return SDL_uclibc_isinff(x);
#endif
}
References SDL_uclibc_isinff().
SDL_islower()
SDL_DECLSPEC int SDLCALL SDL_islower (int x) extern
Report if a character is lower case.
WARNING: Regardless of system locale, this will only treat ASCII values 'a' through 'z' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'a') && ((x) <= 'z'); }
Referenced by SDL_isalpha().
SDL_isnan()
SDL_DECLSPEC int SDLCALL SDL_isnan (double x) extern
Return whether the value is NaN.
Parameters
x double-precision floating point value.
Returns
non-zero if the value is NaN, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isnanf
{
#ifdef HAVE_ISNAN
    return isnan(x);
#else
    return SDL_uclibc_isnan(x);
#endif
}
References SDL_uclibc_isnan().
SDL_isnanf()
SDL_DECLSPEC int SDLCALL SDL_isnanf (float x) extern
Return whether the value is NaN.
Parameters
x floating point value.
Returns
non-zero if the value is NaN, 0 otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isnan
{
#ifdef HAVE_ISNAN_FLOAT_MACRO
    return isnan(x);
#elif defined(HAVE_ISNANF)
    return isnanf(x);
#else
    return SDL_uclibc_isnanf(x);
#endif
}
References SDL_uclibc_isnanf().
SDL_isprint()
SDL_DECLSPEC int SDLCALL SDL_isprint (int x) extern
Report if a character is "printable".
Be advised that "printable" has a definition that goes back to text terminals from the dawn of computing, making this a sort of special case function that is not suitable for Unicode (or most any) text management.
WARNING: Regardless of system locale, this will only treat ASCII values ' ' (0x20) through '~' (0x7E) as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= ' ') && ((x) < '\x7f'); }
Referenced by SDL_isgraph(), and Translate_to_text().
SDL_ispunct()
SDL_DECLSPEC int SDLCALL SDL_ispunct (int x) extern
Report if a character is a punctuation mark.
WARNING: Regardless of system locale, this is equivalent to ((SDL_isgraph(x)) && (!SDL_isalnum(x))).
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_isgraph
SDL_isalnum
{ return (SDL_isgraph(x)) && (!SDL_isalnum(x)); }
References SDL_isalnum(), and SDL_isgraph().
SDL_isspace()
SDL_DECLSPEC int SDLCALL SDL_isspace (int x) extern
Report if a character is whitespace.
WARNING: Regardless of system locale, this will only treat the following ASCII values as true:
space (0x20)
tab (0x09)
newline (0x0A)
vertical tab (0x0B)
form feed (0x0C)
return (0x0D)
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) == ' ') || ((x) == '\t') || ((x) == '\r') || ((x) == '\n') || ((x) == '\f') || ((x) == '\v'); }
Referenced by build_locales_from_csv_string(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_ScanFloat(), SDL_ScanUnsignedLongLongInternal(), SDL_ScanUnsignedLongLongInternalW(), and SDL_vsscanf().
SDL_isupper()
SDL_DECLSPEC int SDLCALL SDL_isupper (int x) extern
Report if a character is upper case.
WARNING: Regardless of system locale, this will only treat ASCII values 'A' through 'Z' as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'A') && ((x) <= 'Z'); }
Referenced by SDL_isalpha().
SDL_isxdigit()
SDL_DECLSPEC int SDLCALL SDL_isxdigit (int x) extern
Report if a character is a hexadecimal digit.
WARNING: Regardless of system locale, this will only treat ASCII values 'A' through 'F', 'a' through 'f', and '0' through '9', as true.
Parameters
x character value to check.
Returns
non-zero if x falls within the character class, zero otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return (((x) >= 'A') && ((x) <= 'F')) || (((x) >= 'a') && ((x) <= 'f')) || (SDL_isdigit(x)); }
References SDL_isdigit().
SDL_itoa()
SDL_DECLSPEC char *SDLCALL SDL_itoa (int value, char * str, int radix) extern
Convert an integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget possible negative signs, null terminator bytes, etc).
Parameters
value the integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_uitoa
SDL_ltoa
SDL_lltoa
{
#ifdef HAVE_ITOA
    return itoa(value, string, radix);
#else
    return SDL_ltoa((long)value, string, radix);
#endif // HAVE_ITOA
}
References SDL_ltoa().
Referenced by SDL_AddVideoDisplay().
SDL_lltoa()
SDL_DECLSPEC char *SDLCALL SDL_lltoa (long long value, char * str, int radix) extern
Convert a long long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget possible negative signs, null terminator bytes, etc).
Parameters
value the long long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ulltoa
SDL_itoa
SDL_ltoa
{
#ifdef HAVE__I64TOA
    return _i64toa(value, string, radix);
#else
    char *bufp = string;
    if (value < 0) {
        *bufp++ = '-';
        SDL_ulltoa(-value, bufp, radix);
    } else {
        SDL_ulltoa(value, bufp, radix);
    }
    return string;
#endif // HAVE__I64TOA
}
References SDL_ulltoa().
Referenced by SDL_PrintLongLong().
SDL_log()
SDL_DECLSPEC double SDLCALL SDL_log (double x) extern
Compute the natural logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on double-precision floating point values, use SDL_logf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the natural logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_logf
SDL_log10
SDL_exp
{
#ifdef HAVE_LOG
    return log(x);
#else
    return SDL_uclibc_log(x);
#endif
}
References SDL_uclibc_log().
Referenced by SDL_logf().
SDL_log10()
SDL_DECLSPEC double SDLCALL SDL_log10 (double x) extern
Compute the base-10 logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on double-precision floating point values, use SDL_log10f for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_log10f
SDL_log
SDL_pow
{
#ifdef HAVE_LOG10
    return log10(x);
#else
    return SDL_uclibc_log10(x);
#endif
}
References SDL_uclibc_log10().
Referenced by SDL_log10f().
SDL_log10f()
SDL_DECLSPEC float SDLCALL SDL_log10f (float x) extern
Compute the base-10 logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on single-precision floating point values, use SDL_log10 for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_log10
SDL_logf
SDL_powf
{
#ifdef HAVE_LOG10F
    return log10f(x);
#else
    return (float)SDL_log10((double)x);
#endif
}
References SDL_log10().
SDL_logf()
SDL_DECLSPEC float SDLCALL SDL_logf (float x) extern
Compute the natural logarithm of x.
Domain: 0 < x <= INF
Range: -INF <= y <= INF
It is an error for x to be less than or equal to 0.
This function operates on single-precision floating point values, use SDL_log for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than 0.
Returns
the natural logarithm of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_log
SDL_expf
{
#ifdef HAVE_LOGF
    return logf(x);
#else
    return (float)SDL_log((double)x);
#endif
}
References SDL_log().
SDL_lround()
SDL_DECLSPEC long SDLCALL SDL_lround (double x) extern
Round x to the nearest integer representable as a long
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: MIN_LONG <= y <= MAX_LONG
This function operates on double-precision floating point values, use SDL_lroundf for single-precision floats. To get the result as a floating-point type, use SDL_round.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_lroundf
SDL_round
SDL_floor
SDL_ceil
SDL_trunc
{
#if defined HAVE_LROUND
    return lround(arg);
#else
    return (long)SDL_round(arg);
#endif
}
References SDL_round().
SDL_lroundf()
SDL_DECLSPEC long SDLCALL SDL_lroundf (float x) extern
Round x to the nearest integer representable as a long
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: MIN_LONG <= y <= MAX_LONG
This function operates on single-precision floating point values, use SDL_lround for double-precision floats. To get the result as a floating-point type, use SDL_roundf.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_lround
SDL_roundf
SDL_floorf
SDL_ceilf
SDL_truncf
{
#if defined HAVE_LROUNDF
    return lroundf(arg);
#else
    return (long)SDL_round((double)arg);
#endif
}
References SDL_round().
SDL_ltoa()
SDL_DECLSPEC char *SDLCALL SDL_ltoa (long value, char * str, int radix) extern
Convert a long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget possible negative signs, null terminator bytes, etc).
Parameters
value the long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ultoa
SDL_itoa
SDL_lltoa
{
#ifdef HAVE__LTOA
    return _ltoa(value, string, radix);
#else
    char *bufp = string;
    if (value < 0) {
        *bufp++ = '-';
        SDL_ultoa(-value, bufp, radix);
    } else {
        SDL_ultoa(value, bufp, radix);
    }
    return string;
#endif // HAVE__LTOA
}
References SDL_ultoa().
Referenced by SDL_itoa(), and SDL_PrintLong().
SDL_malloc()
SDL_DECLSPEC SDL_MALLOC void *SDLCALL SDL_malloc (size_t size) extern
Allocate uninitialized memory.
The allocated memory returned by this function must be freed with SDL_free().
If size is 0, it will be set to 1.
If the allocation is successful, the returned pointer is guaranteed to be aligned to either the fundamental alignment (alignof(max_align_t) in C11 and later) or 2 * sizeof(void *), whichever is smaller. Use SDL_aligned_alloc() if you need to allocate memory aligned to an alignment greater than this guarantee.
Parameters
size the size to allocate.
Returns
a pointer to the allocated memory, or NULL if allocation failed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_free
SDL_calloc
SDL_realloc
SDL_aligned_alloc
{
    void *mem;
    if (!size) {
        size = 1;
    }
    mem = s_mem.malloc_func(size);
    if (mem) {
        INCREMENT_ALLOCATION_COUNT();
    } else {
        SDL_OutOfMemory();
    }
    return mem;
}
References INCREMENT_ALLOCATION_COUNT, s_mem, and SDL_OutOfMemory().
Referenced by AddDeviceToEnumeration(), AddVirtualGamepadInfo(), AllocNewMemoryPoolBlock(), CaseFoldUtf8String(), convert_ext_list(), convert_filter(), CopyOneProperty(), create_zenity_args(), CreateMappingString(), DUMMYAUDIO_OpenDevice(), escape_label(), Fcitx_GetPreeditString(), GetAudioDevices(), glGetConfig(), IMA_ADPCM_Decode(), MS_ADPCM_Init(), PushMappingChangeTracking(), run_zenity(), SDL_AddAudioDevice(), SDL_AddCamera(), SDL_AddEvent(), SDL_AddFinger(), SDL_AddFullscreenDisplayMode(), SDL_AddHintCallback(), SDL_AddTouch(), SDL_AddVideoDisplay(), SDL_aligned_alloc(), SDL_AllocateTemporaryMemory(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CameraDisconnected(), SDL_CameraPermissionOutcome(), SDL_ChannelMapDup(), SDL_CleanupTrays(), SDL_ConvertAudioSamples(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_ConvertSurfaceAndColorspace(), SDL_CopyClipboardMimeTypes(), SDL_CreateCondition(), SDL_CreateDeviceName(), SDL_CreateMainThreadCallback(), SDL_CreatePalette(), SDL_CreateSemaphore(), SDL_CreateSurface(), SDL_CreateSurfaceFrom(), SDL_CreateTimer(), SDL_CreateWindowTexture(), SDL_DefaultAudioDeviceChanged(), SDL_FreeLater(), SDL_Generic_SetTLSData(), SDL_GetCameras(), SDL_GetCameraSupportedFormats(), SDL_GetDisplays(), SDL_GetEnvironmentVariables(), SDL_GetFullscreenDisplayModes(), SDL_GetGamepadBindings(), SDL_GetGamepadMappings(), SDL_GetHaptics(), SDL_GetInternalClipboardData(), SDL_GetJoysticks(), SDL_GetKeyboards(), SDL_GetMice(), SDL_GetPixelFormatDetails(), SDL_GetSensors(), SDL_GetSurfaceImages(), SDL_GetTouchDevices(), SDL_GetTouchFingers(), SDL_GetWindows(), SDL_iconv_open(), SDL_iconv_string(), SDL_InternalGlobDirectory(), SDL_ListAdd(), SDL_LoadFile_IO(), SDL_LoadFileAsync(), SDL_LoadVIDPIDListFromHints(), SDL_LogMessageV(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateGetGamepadNameFromMappingString(), SDL_PromptAssertion(), SDL_PutAudioStreamData(), SDL_PutAudioStreamPlanarData(), SDL_SaveClipboardMimeTypes(), SDL_SetClipboardData(), SDL_setenv_unsafe(), SDL_SetGPURenderStateFragmentUniforms(), SDL_SetHintWithPriority(), SDL_SetLogPriority(), SDL_strdup(), SDL_strndup(), SDL_SYS_GetPrefPath(), SDL_UpdateTextureNative(), SDL_vasprintf(), SDL_wcsdup(), ShowFileDialog(), ShowFolderDialog(), STEAM_User_Create(), WaveReadPartialChunkData(), win_get_filters(), and windows_ShowFileDialog().
SDL_memcmp()
SDL_DECLSPEC int SDLCALL SDL_memcmp (const void * s1, const void * s2, size_t len) extern
Compare two buffers of memory.
Parameters
s1 the first buffer to compare. NULL is not permitted!
s2 the second buffer to compare. NULL is not permitted!
len the number of bytes to compare between the buffers.
Returns
less than zero if s1 is "less than" s2, greater than zero if s1 is "greater than" s2, and zero if the buffers match exactly for len bytes.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_PLATFORM_VITA
    /*
      Using memcmp on NULL is UB per POSIX / C99 7.21.1/2.
      But, both linux and bsd allow that, with an exception:
      zero length strings are always identical, so NULLs are never dereferenced.
      sceClibMemcmp on PSVita doesn't allow that, so we check ourselves.
    */
    if (len == 0) {
        return 0;
    }
    return sceClibMemcmp(s1, s2, len);
#elif defined(HAVE_MEMCMP)
    return memcmp(s1, s2, len);
#else
    char *s1p = (char *)s1;
    char *s2p = (char *)s2;
    while (len--) {
        if (*s1p != *s2p) {
            return *s1p - *s2p;
        }
        ++s1p;
        ++s2p;
    }
    return 0;
#endif // HAVE_MEMCMP
}
References memcmp.
Referenced by decode_header(), Map1to1(), QueueCmdSetClipRect(), QueueCmdSetViewport(), SDL_AddCamera(), SDL_AudioChannelMapsEqual(), SDL_AudioSpecsEqual(), SDL_CheckWindowSafeAreaChanged(), SDL_ConvertSurfaceAndColorspace(), SDL_endswith(), SDL_GetFullscreenModeMatch(), SDL_GetGamepadMappings(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateMatchGamepadMappingForGUID(), SDL_PrivateParseGamepadElement(), SDL_SetGamepadMapping(), SDL_URIToLocal(), SetAudioStreamChannelMap(), and WaveGetFormatGUIDEncoding().
SDL_memcpy()
SDL_DECLSPEC void *SDLCALL SDL_memcpy (void * dst, const void * src, size_t len) extern
Copy non-overlapping memory.
The memory regions must not overlap. If they do, use SDL_memmove() instead.
Parameters
dst The destination memory region. Must not be NULL, and must not overlap with src.
src The source memory region. Must not be NULL, and must not overlap with dst.
len The length in bytes of both dst and src.
Returns
dst.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_memmove
References SDL_DECLSPEC, and SDLCALL.
SDL_memmove()
SDL_DECLSPEC void *SDLCALL SDL_memmove (void * dst, const void * src, size_t len) extern
Copy memory ranges that might overlap.
It is okay for the memory regions to overlap. If you are confident that the regions never overlap, using SDL_memcpy() may improve performance.
Parameters
dst The destination memory region. Must not be NULL.
src The source memory region. Must not be NULL.
len The length in bytes of both dst and src.
Returns
dst.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_memcpy
References SDL_DECLSPEC, and SDLCALL.
SDL_memset()
SDL_DECLSPEC void *SDLCALL SDL_memset (void * dst, int c, size_t len) extern
Initialize all bytes of buffer of memory to a specific value.
This function will set len bytes, pointed to by dst, to the value specified in c.
Despite c being an int instead of a char, this only operates on bytes; c must be a value between 0 and 255, inclusive.
Parameters
dst the destination memory region. Must not be NULL.
c the byte value to set.
len the length, in bytes, to set in dst.
Returns
dst.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, and SDLCALL.
SDL_memset4()
SDL_DECLSPEC void *SDLCALL SDL_memset4 (void * dst, Uint32 val, size_t dwords) extern
Initialize all 32-bit words of buffer of memory to a specific value.
This function will set a buffer of dwords Uint32 values, pointed to by dst, to the value specified in val.
Unlike SDL_memset, this sets 32-bit values, not bytes, so it's not limited to a range of 0-255.
Parameters
dst the destination memory region. Must not be NULL.
val the Uint32 value to set.
dwords the number of Uint32 values to set in dst.
Returns
dst.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#if defined(__APPLE__) && defined(HAVE_STRING_H)
    memset_pattern4(dst, &val, dwords * 4);
#elif defined(__GNUC__) && defined(__i386__)
    int u0, u1, u2;
    __asm__ __volatile__(
        "cld \n\t"
        "rep ; stosl \n\t"
        : "=&D"(u0), "=&a"(u1), "=&c"(u2)
        : "0"(dst), "1"(val), "2"(SDL_static_cast(Uint32, dwords))
        : "memory");
#else
    size_t _n = (dwords + 3) / 4;
    Uint32 *_p = SDL_static_cast(Uint32 *, dst);
    Uint32 _val = (val);
    if (dwords == 0) {
        return dst;
    }
    switch (dwords % 4) {
    case 0:
        do {
            *_p++ = _val;
            SDL_FALLTHROUGH;
        case 3:
            *_p++ = _val;
            SDL_FALLTHROUGH;
        case 2:
            *_p++ = _val;
            SDL_FALLTHROUGH;
        case 1:
            *_p++ = _val;
        } while (--_n);
    }
#endif
    return dst;
}
References SDL_FALLTHROUGH, and SDL_static_cast.
Referenced by SDL_FillSurfaceRect1(), SDL_FillSurfaceRect2(), and SDL_FillSurfaceRect4().
SDL_modf()
SDL_DECLSPEC double SDLCALL SDL_modf (double x, double * y) extern
Split x into integer and fractional parts
This function operates on double-precision floating point values, use SDL_modff for single-precision floats.
Parameters
x floating point value.
y output pointer to store the integer part of x.
Returns
the fractional part of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_modff
SDL_trunc
SDL_fmod
{
#ifdef HAVE_MODF
    return modf(x, y);
#else
    return SDL_uclibc_modf(x, y);
#endif
}
References modf, and SDL_uclibc_modf().
Referenced by SDL_modff(), and SDL_PrintFloat().
SDL_modff()
SDL_DECLSPEC float SDLCALL SDL_modff (float x, float * y) extern
Split x into integer and fractional parts
This function operates on single-precision floating point values, use SDL_modf for double-precision floats.
Parameters
x floating point value.
y output pointer to store the integer part of x.
Returns
the fractional part of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_modf
SDL_truncf
SDL_fmodf
{
#ifdef HAVE_MODFF
    return modff(x, y);
#else
    double double_result, double_y;
    double_result = SDL_modf((double)x, &double_y);
    *y = (float)double_y;
    return (float)double_result;
#endif
}
References SDL_modf().
Referenced by SDL_PrivateSendMouseMotion(), SDL_RenderTextureTiled_Iterate(), and SDL_SendMouseWheel().
SDL_murmur3_32()
SDL_DECLSPEC Uint32 SDLCALL SDL_murmur3_32 (const void * data, size_t len, Uint32 seed) extern
Calculate a 32-bit MurmurHash3 value for a block of data.
https://en.wikipedia.org/wiki/MurmurHash
A seed may be specified, which changes the final results consistently, but this does not work like SDL_crc16 and SDL_crc32: you can't feed a previous result from this function back into itself as the next seed value to calculate a hash in chunks; it won't produce the same hash as it would if the same data was provided in a single call.
If you aren't sure what to provide for a seed, zero is fine. Murmur3 is not cryptographically secure, so it shouldn't be used for hashing top-secret data.
Parameters
data the data to be hashed.
len the size of data, in bytes.
seed a value that alters the final hash value.
Returns
a Murmur3 32-bit hash value.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    const Uint8 *bytes = (const Uint8 *)data;
    Uint32 hash = seed;
    Uint32 k;
    // Read in groups of 4.
    if ((((uintptr_t)bytes) & 3) == 0) {
        // We can do aligned 32-bit reads
        for (size_t i = len >> 2; i--; ) {
            k = *(const Uint32 *)bytes;
            k = SDL_Swap32LE(k);
            bytes += sizeof(Uint32);
            hash ^= murmur_32_scramble(k);
            hash = (hash << 13) | (hash >> 19);
            hash = hash * 5 + 0xe6546b64;
        }
    } else {
        for (size_t i = len >> 2; i--; ) {
            SDL_memcpy(&k, bytes, sizeof(Uint32));
            k = SDL_Swap32LE(k);
            bytes += sizeof(Uint32);
            hash ^= murmur_32_scramble(k);
            hash = (hash << 13) | (hash >> 19);
            hash = hash * 5 + 0xe6546b64;
        }
    }
    // Read the rest.
    size_t left = (len & 3);
    if (left) {
        k = 0;
        for (size_t i = left; i--; ) {
            k <<= 8;
            k |= bytes[i];
        }
        // A swap is *not* necessary here because the preceding loop already
        // places the low bytes in the low places according to whatever endianness
        // we use. Swaps only apply when the memory is copied in a chunk.
        hash ^= murmur_32_scramble(k);
    }
    /* Finalize. */
    hash ^= len;
    hash ^= hash >> 16;
    hash *= 0x85ebca6b;
    hash ^= hash >> 13;
    hash *= 0xc2b2ae35;
    hash ^= hash >> 16;
    return hash;
}
References left, murmur_32_scramble(), SDL_memcpy, SDL_Swap32LE, and SDLCALL.
Referenced by SDL_HashPointer().
SDL_pow()
SDL_DECLSPEC double SDLCALL SDL_pow (double x, double y) extern
Raise x to the power y
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -INF <= z <= INF
If y is the base of the natural logarithm (e), consider using SDL_exp instead.
This function operates on double-precision floating point values, use SDL_powf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x the base.
y the exponent.
Returns
x raised to the power y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_powf
SDL_exp
SDL_log
{
#ifdef HAVE_POW
    return pow(x, y);
#else
    return SDL_uclibc_pow(x, y);
#endif
}
References SDL_uclibc_pow().
Referenced by decode_fraction(), and SDL_powf().
SDL_powf()
SDL_DECLSPEC float SDLCALL SDL_powf (float x, float y) extern
Raise x to the power y
Domain: -INF <= x <= INF, -INF <= y <= INF
Range: -INF <= z <= INF
If y is the base of the natural logarithm (e), consider using SDL_exp instead.
This function operates on single-precision floating point values, use SDL_pow for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x the base.
y the exponent.
Returns
x raised to the power y.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_pow
SDL_expf
SDL_logf
{
#ifdef HAVE_POWF
    return powf(x, y);
#else
    return (float)SDL_pow((double)x, (double)y);
#endif
}
References SDL_pow().
Referenced by SDL_PQfromNits(), SDL_PQtoNits(), SDL_sRGBfromLinear(), and SDL_sRGBtoLinear().
SDL_qsort()
SDL_DECLSPEC void SDLCALL SDL_qsort (void * base, size_t nmemb, size_t size, SDL_CompareCallback compare) extern
Sort an array.
For example:
typedef struct {
    int key;
    const char *string;
} data;
int SDLCALL compare(const void *a, const void *b)
{
    const data *A = (const data *)a;
    const data *B = (const data *)b;
    if (A->n < B->n) {
        return -1;
    } else if (B->n < A->n) {
        return 1;
    } else {
        return 0;
    }
}
data values[] = {
    { 3, "third" }, { 1, "first" }, { 2, "second" }
};
SDL_qsort(values, SDL_arraysize(values), sizeof(values[0]), compare);
Parameters
base a pointer to the start of the array.
nmemb the number of elements in the array.
size the size of the elements in the array.
compare a function used to compare elements in the array.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_bsearch
SDL_qsort_r
Referenced by SDL_AddCamera(), and SDL_AddFullscreenDisplayMode().
SDL_qsort_r()
SDL_DECLSPEC void SDLCALL SDL_qsort_r (void * base, size_t nmemb, size_t size, SDL_CompareCallback_r compare, void * userdata) extern
Sort an array, passing a userdata pointer to the compare function.
For example:
typedef enum {
    sort_increasing,
    sort_decreasing,
} sort_method;
typedef struct {
    int key;
    const char *string;
} data;
int SDLCALL compare(const void *userdata, const void *a, const void *b)
{
    sort_method method = (sort_method)(uintptr_t)userdata;
    const data *A = (const data *)a;
    const data *B = (const data *)b;
    if (A->key < B->key) {
        return (method == sort_increasing) ? -1 : 1;
    } else if (B->key < A->key) {
        return (method == sort_increasing) ? 1 : -1;
    } else {
        return 0;
    }
}
data values[] = {
    { 3, "third" }, { 1, "first" }, { 2, "second" }
};
SDL_qsort_r(values, SDL_arraysize(values), sizeof(values[0]), compare, (const void *)(uintptr_t)sort_increasing);
Parameters
base a pointer to the start of the array.
nmemb the number of elements in the array.
size the size of the elements in the array.
compare a function used to compare elements in the array.
userdata a pointer to pass to the compare function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_bsearch_r
SDL_qsort
{
  if (nmemb<=1) return;
  if (((uintptr_t)base|size)&(WORD_BYTES-1))
    qsort_r_nonaligned(base,nmemb,size,compare,userdata);
  else if (size!=WORD_BYTES)
    qsort_r_aligned(base,nmemb,size,compare,userdata);
References qsort_r_aligned(), qsort_r_nonaligned(), and WORD_BYTES.
SDL_rand()
SDL_DECLSPEC Sint32 SDLCALL SDL_rand (Sint32 n) extern
Generate a pseudo-random number less than n for positive n
The method used is faster and of better quality than rand() % n. Odds are roughly 99.9% even for n = 1 million. Evenness is better for smaller n, and much worse as n gets bigger.
Example: to simulate a d6 use SDL_rand(6) + 1 The +1 converts 0..5 to 1..6
If you want to generate a pseudo-random number in the full range of Sint32, you should use: (Sint32)SDL_rand_bits()
If you want reproducible output, be sure to initialize with SDL_srand() first.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
n the number of possible outcomes. n must be positive.
Returns
a random value in the range of [0 .. n-1].
Thread Safety
All calls should be made from a single thread
Since
This function is available since SDL 3.2.0.
See also
SDL_srand
SDL_randf
{
    if (!SDL_rand_initialized) {
        SDL_srand(0);
    }
    return SDL_rand_r(&SDL_rand_state, n);
}
References SDL_rand_initialized, SDL_rand_r(), SDL_rand_state, and SDL_srand().
Referenced by SDL_vasprintf().
SDL_rand_bits()
SDL_DECLSPEC Uint32 SDLCALL SDL_rand_bits (void) extern
Generate 32 pseudo-random bits.
You likely want to use SDL_rand() to get a psuedo-random number instead.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Returns
a random value in the range of [0-SDL_MAX_UINT32].
Thread Safety
All calls should be made from a single thread
Since
This function is available since SDL 3.2.0.
See also
SDL_rand
SDL_randf
SDL_srand
{
    if (!SDL_rand_initialized) {
        SDL_srand(0);
    }
    return SDL_rand_bits_r(&SDL_rand_state);
}
References SDL_rand_bits_r(), SDL_rand_initialized, SDL_rand_state, and SDL_srand().
Referenced by SDL_vasprintf().
SDL_rand_bits_r()
SDL_DECLSPEC Uint32 SDLCALL SDL_rand_bits_r (Uint64 * state) extern
Generate 32 pseudo-random bits.
You likely want to use SDL_rand_r() to get a psuedo-random number instead.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
state a pointer to the current random number state, this may not be NULL.
Returns
a random value in the range of [0-SDL_MAX_UINT32].
Thread Safety
This function is thread-safe, as long as the state pointer isn't shared between threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_rand_r
SDL_randf_r
{
    if (!state) {
        return 0;
    }
    // The C and A parameters of this LCG have been chosen based on hundreds
    // of core-hours of testing with PractRand and TestU01's Crush.
    // Using a 32-bit A improves performance on 32-bit architectures.
    // C can be any odd number, but < 256 generates smaller code on ARM32
    // These values perform as well as a full 64-bit implementation against
    // Crush and PractRand. Plus, their worst-case performance is better
    // than common 64-bit constants when tested against PractRand using seeds
    // with only a single bit set.
    // We tested all 32-bit and 33-bit A with all C < 256 from a v2 of:
    // Steele GL, Vigna S. Computationally easy, spectrally good multipliers
    // for congruential pseudorandom number generators.
    // Softw Pract Exper. 2022;52(2):443-458. doi: 10.1002/spe.3030
    // https://arxiv.org/abs/2001.05304v2
    *state = *state * 0xff1cd035ul + 0x05;
    // Only return top 32 bits because they have a longer period
    return (Uint32)(*state >> 32);
}
Referenced by SDL_rand_bits(), SDL_rand_r(), SDL_randf_r(), and SDL_vasprintf().
SDL_rand_r()
SDL_DECLSPEC Sint32 SDLCALL SDL_rand_r (Uint64 * state, Sint32 n) extern
Generate a pseudo-random number less than n for positive n
The method used is faster and of better quality than rand() % n. Odds are roughly 99.9% even for n = 1 million. Evenness is better for smaller n, and much worse as n gets bigger.
Example: to simulate a d6 use SDL_rand_r(state, 6) + 1 The +1 converts 0..5 to 1..6
If you want to generate a pseudo-random number in the full range of Sint32, you should use: (Sint32)SDL_rand_bits_r(state)
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
state a pointer to the current random number state, this may not be NULL.
n the number of possible outcomes. n must be positive.
Returns
a random value in the range of [0 .. n-1].
Thread Safety
This function is thread-safe, as long as the state pointer isn't shared between threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_rand
SDL_rand_bits_r
SDL_randf_r
{
    // Algorithm: get 32 bits from SDL_rand_bits() and treat it as a 0.32 bit
    // fixed point number. Multiply by the 31.0 bit n to get a 31.32 bit
    // result. Shift right by 32 to get the 31 bit integer that we want.
    if (n < 0) {
        // The algorithm looks like it works for numbers < 0 but it has an
        // infinitesimal chance of returning a value out of range.
        // Returning -SDL_rand(abs(n)) blows up at INT_MIN instead.
        // It's easier to just say no.
        return 0;
    }
    // On 32-bit arch, the compiler will optimize to a single 32-bit multiply
    Uint64 val = (Uint64)SDL_rand_bits_r(state) * n;
    return (Sint32)(val >> 32);
}
References SDL_rand_bits_r().
Referenced by SDL_rand(), and SDL_vasprintf().
SDL_randf()
SDL_DECLSPEC float SDLCALL SDL_randf (void) extern
Generate a uniform pseudo-random floating point number less than 1.0
If you want reproducible output, be sure to initialize with SDL_srand() first.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Returns
a random value in the range of [0.0, 1.0).
Thread Safety
All calls should be made from a single thread
Since
This function is available since SDL 3.2.0.
See also
SDL_srand
SDL_rand
{
    if (!SDL_rand_initialized) {
        SDL_srand(0);
    }
    return SDL_randf_r(&SDL_rand_state);
}
References SDL_rand_initialized, SDL_rand_state, SDL_randf_r(), and SDL_srand().
Referenced by SDL_vasprintf().
SDL_randf_r()
SDL_DECLSPEC float SDLCALL SDL_randf_r (Uint64 * state) extern
Generate a uniform pseudo-random floating point number less than 1.0
If you want reproducible output, be sure to initialize with SDL_srand() first.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
state a pointer to the current random number state, this may not be NULL.
Returns
a random value in the range of [0.0, 1.0).
Thread Safety
This function is thread-safe, as long as the state pointer isn't shared between threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_rand_bits_r
SDL_rand_r
SDL_randf
{
    // Note: its using 24 bits because float has 23 bits significand + 1 implicit bit
    return (SDL_rand_bits_r(state) >> (32 - 24)) * 0x1p-24f;
}
References SDL_rand_bits_r().
Referenced by SDL_randf(), and SDL_vasprintf().
SDL_round()
SDL_DECLSPEC double SDLCALL SDL_round (double x) extern
Round x to the nearest integer.
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_roundf for single-precision floats. To get the result as an integer type, use SDL_lround.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_roundf
SDL_lround
SDL_floor
SDL_ceil
SDL_trunc
{
#if defined HAVE_ROUND
    return round(arg);
#else
    if (arg >= 0.0) {
        return SDL_floor(arg + 0.5);
    } else {
        return SDL_ceil(arg - 0.5);
    }
#endif
}
References SDL_ceil(), and SDL_floor().
Referenced by DUMMYAUDIO_OpenDevice(), SDL_BlitSurfaceScaled(), SDL_GetNumberProperty(), SDL_GetSurfaceImage(), SDL_GetSystemRAM(), SDL_lround(), SDL_lroundf(), SDL_PrintFloat(), SDL_roundf(), and SDL_WriteSurfacePixelFloat().
SDL_roundf()
SDL_DECLSPEC float SDLCALL SDL_roundf (float x) extern
Round x to the nearest integer.
Rounds x to the nearest integer. Values halfway between integers will be rounded away from zero.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_round for double-precision floats. To get the result as an integer type, use SDL_lroundf.
Parameters
x floating point value.
Returns
the nearest integer to x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_round
SDL_lroundf
SDL_floorf
SDL_ceilf
SDL_truncf
{
#if defined HAVE_ROUNDF
    return roundf(arg);
#else
    return (float)SDL_round((double)arg);
#endif
}
References SDL_round().
Referenced by IOS_MFIJoystickUpdate(), RenderLinesWithRectsF(), SDL_Blit_Slow_Float(), SDL_BlitSurface9Grid(), SDL_ClearSurface(), SDL_GetTextureAlphaMod(), SDL_GetTextureColorMod(), SDL_MixAudio(), SDL_SetWindowSize(), and WriteFloatPixel().
SDL_scalbn()
SDL_DECLSPEC double SDLCALL SDL_scalbn (double x, int n) extern
Scale x by an integer power of two.
Multiplies x by the nth power of the floating point radix (always 2).
Domain: -INF <= x <= INF, n integer
Range: -INF <= y <= INF
This function operates on double-precision floating point values, use SDL_scalbnf for single-precision floats.
Parameters
x floating point value to be scaled.
n integer exponent.
Returns
x * 2^n.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_scalbnf
SDL_pow
{
#ifdef HAVE_SCALBN
    return scalbn(x, n);
#elif defined(HAVE__SCALB)
    return _scalb(x, n);
#elif defined(HAVE_LIBC) && defined(HAVE_FLOAT_H) && (FLT_RADIX == 2)
    /* from scalbn(3): If FLT_RADIX equals 2 (which is
     * usual), then scalbn() is equivalent to ldexp(3). */
    return ldexp(x, n);
#else
    return SDL_uclibc_scalbn(x, n);
#endif
}
References scalbn, and SDL_uclibc_scalbn().
Referenced by SDL_scalbnf().
SDL_scalbnf()
SDL_DECLSPEC float SDLCALL SDL_scalbnf (float x, int n) extern
Scale x by an integer power of two.
Multiplies x by the nth power of the floating point radix (always 2).
Domain: -INF <= x <= INF, n integer
Range: -INF <= y <= INF
This function operates on single-precision floating point values, use SDL_scalbn for double-precision floats.
Parameters
x floating point value to be scaled.
n integer exponent.
Returns
x * 2^n.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_scalbn
SDL_powf
{
#ifdef HAVE_SCALBNF
    return scalbnf(x, n);
#else
    return (float)SDL_scalbn((double)x, n);
#endif
}
References SDL_scalbn().
SDL_setenv_unsafe()
SDL_DECLSPEC int SDLCALL SDL_setenv_unsafe (const char * name, const char * value, int overwrite) extern
Set the value of a variable in the environment.
Parameters
name the name of the variable to set.
value the value of the variable to set.
overwrite 1 to overwrite the variable if it exists, 0 to return success without setting the variable if it already exists.
Returns
0 on success, -1 on error.
Thread Safety
This function is not thread safe, consider using SDL_SetEnvironmentVariable() instead.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetEnvironmentVariable
{
    int added;
    size_t len, i;
    char **new_env;
    char *new_variable;
    // Input validation
    if (!name || *name == '\0' || SDL_strchr(name, '=') != NULL || !value) {
        return -1;
    }
    // See if it already exists
    if (!overwrite && SDL_getenv_unsafe(name)) {
        return 0;
    }
    SDL_SetEnvironmentVariable(SDL_GetEnvironment(), name, value, (overwrite != 0));
    // Allocate memory for the variable
    len = SDL_strlen(name) + SDL_strlen(value) + 2;
    new_variable = (char *)SDL_malloc(len);
    if (!new_variable) {
        return -1;
    }
    SDL_snprintf(new_variable, len, "%s=%s", name, value);
    value = new_variable + SDL_strlen(name) + 1;
    name = new_variable;
    // Actually put it into the environment
    added = 0;
    i = 0;
    if (environ) {
        // Check to see if it's already there...
        len = (value - name);
        for (; environ[i]; ++i) {
            if (SDL_strncmp(environ[i], name, len) == 0) {
                // If we found it, just replace the entry
                SDL_free(environ[i]);
                environ[i] = new_variable;
                added = 1;
                break;
            }
        }
    }
    // Didn't find it in the environment, expand and add
    if (!added) {
        new_env = SDL_realloc(environ, (i + 2) * sizeof(char *));
        if (new_env) {
            environ = new_env;
            environ[i++] = new_variable;
            environ[i++] = (char *)0;
            added = 1;
        } else {
            SDL_free(new_variable);
        }
    }
    return added ? 0 : -1;
}
References environ, NULL, SDL_free(), SDL_getenv_unsafe(), SDL_GetEnvironment(), SDL_malloc(), SDL_realloc(), SDL_SetEnvironmentVariable(), SDL_snprintf(), SDL_strchr(), SDL_strlen(), and SDL_strncmp().
Referenced by SDL_SetEnvironmentVariable().
SDL_SetEnvironmentVariable()
SDL_DECLSPEC unsigned char SDLCALL SDL_SetEnvironmentVariable (SDL_Environment * env, const char * name, const char * value, unsigned char overwrite) extern
Set the value of a variable in the environment.
Parameters
env the environment to modify.
name the name of the variable to set.
value the value of the variable to set.
overwrite true to overwrite the variable if it exists, false to return success without setting the variable if it already exists.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariable
SDL_GetEnvironmentVariables
SDL_UnsetEnvironmentVariable
References SDL_DECLSPEC, SDL_DestroyEnvironment(), SDL_getenv(), SDL_getenv_unsafe(), SDL_setenv_unsafe(), SDL_SetEnvironmentVariable(), SDL_unsetenv_unsafe(), SDL_UnsetEnvironmentVariable(), and SDLCALL.
Referenced by run_zenity(), and SDL_SetEnvironmentVariable().
SDL_SetMemoryFunctions()
SDL_DECLSPEC unsigned char SDLCALL SDL_SetMemoryFunctions (SDL_malloc_func malloc_func, SDL_calloc_func calloc_func, SDL_realloc_func realloc_func, SDL_free_func free_func) extern
Replace SDL's memory allocation functions with a custom set.
It is not safe to call this function once any allocations have been made, as future calls to SDL_free will use the new allocator, even if they came from an SDL_malloc made with the old one!
If used, usually this needs to be the first call made into the SDL library, if not the very first thing done at program startup time.
Parameters
malloc_func custom malloc function.
calloc_func custom calloc function.
realloc_func custom realloc function.
free_func custom free function.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but one should not replace the memory functions once any allocations are made!
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMemoryFunctions
SDL_GetOriginalMemoryFunctions
{
    if (!malloc_func) {
        return SDL_InvalidParamError("malloc_func");
    }
    if (!calloc_func) {
        return SDL_InvalidParamError("calloc_func");
    }
    if (!realloc_func) {
        return SDL_InvalidParamError("realloc_func");
    }
    if (!free_func) {
        return SDL_InvalidParamError("free_func");
    }
    s_mem.malloc_func = malloc_func;
    s_mem.calloc_func = calloc_func;
    s_mem.realloc_func = realloc_func;
    s_mem.free_func = free_func;
    return true;
}
References calloc_func, free_func, malloc_func, realloc_func, s_mem, and SDL_InvalidParamError.
SDL_sin()
SDL_DECLSPEC double SDLCALL SDL_sin (double x) extern
Compute the sine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on double-precision floating point values, use SDL_sinf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
sine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sinf
SDL_asin
SDL_cos
{
#ifdef HAVE_SIN
    return sin(x);
#else
    return SDL_uclibc_sin(x);
#endif
}
References SDL_uclibc_sin(), and sin.
Referenced by SDL_sinf().
SDL_sinf()
SDL_DECLSPEC float SDLCALL SDL_sinf (float x) extern
Compute the sine of x.
Domain: -INF <= x <= INF
Range: -1 <= y <= 1
This function operates on single-precision floating point values, use SDL_sin for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
sine of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sin
SDL_asinf
SDL_cosf
{
#ifdef HAVE_SINF
    return sinf(x);
#else
    return (float)SDL_sin((double)x);
#endif
}
References SDL_sin().
Referenced by SDL_RenderTextureRotated(), and SincTable().
SDL_size_add_check_overflow()
SDL_FORCE_INLINE unsigned char SDL_size_add_check_overflow (size_t a, size_t b, size_t * ret)
Add two integers, checking for overflow.
If a + b would overflow, return false.
Otherwise store a + b via ret and return true.
Parameters
a the first addend.
b the second addend.
ret on non-overflow output, stores the addition result, may not be NULL.
Returns
false on overflow, true if result is added without overflow.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (b > SDL_SIZE_MAX - a) {
        return false;
    }
    *ret = a + b;
    return true;
}
References SDL_FORCE_INLINE, and SDL_SIZE_MAX.
Referenced by SDL_aligned_alloc(), SDL_CalculateRGBSize(), SDL_CalculateYUVSize(), SDL_LogMessageV(), and SDL_PromptAssertion().
SDL_size_mul_check_overflow()
SDL_FORCE_INLINE unsigned char SDL_size_mul_check_overflow (size_t a, size_t b, size_t * ret)
Multiply two integers, checking for overflow.
If a * b would overflow, return false.
Otherwise store a * b via ret and return true.
Parameters
a the multiplicand.
b the multiplier.
ret on non-overflow output, stores the multiplication result, may not be NULL.
Returns
false on overflow, true if result is multiplied without overflow.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (a != 0 && b > SDL_SIZE_MAX / a) {
        return false;
    }
    *ret = a * b;
    return true;
}
References SDL_FORCE_INLINE, and SDL_SIZE_MAX.
Referenced by SDL_CalculateRGBSize(), and SDL_CalculateYUVSize().
SDL_snprintf()
SDL_DECLSPEC int SDLCALL SDL_snprintf (char * text, size_t maxlen, const char * fmt, ...) extern
This works exactly like snprintf() but doesn't require access to a C runtime.
Format a string of up to maxlen-1 bytes, converting each '' item with values provided through variable arguments.
While some C runtimes differ on how to deal with too-large strings, this function null-terminates the output, by treating the null-terminator as part of the maxlen count. Note that if maxlen is zero, however, no bytes will be written at all.
This function returns the number of bytes (not characters) that should be written, excluding the null-terminator character. If this returns a number >= maxlen, it means the output string was truncated. A negative return value means an error occurred.
Referencing the output string's pointer with a format item is undefined behavior.
Parameters
text the buffer to write the string into. Must not be NULL.
maxlen the maximum bytes to write, including the null-terminator.
fmt a printf-style format string. Must not be NULL.
... a list of values to be used with the format string.
Returns
the number of bytes that should be written, not counting the null-terminator char, or a negative value on error.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDL_OUT_Z_CAP, SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNC, SDL_snprintf(), and SDLCALL.
Referenced by convert_filter(), CreateMappingString(), get_appindicator_id(), get_x11_window_handle(), GetAppName(), GetControllerTypeOverride(), MaybeSpinNewWorkerThread(), new_tmp_filename(), SDL_CreateDeviceName(), SDL_GetAudioThreadName(), SDL_GetCameraThreadName(), SDL_GetEventDescription(), SDL_GetGamepadMappingFilePath(), SDL_HIDAPI_ShouldIgnoreDevice(), SDL_InsertTrayEntryAt(), SDL_LogOutput(), SDL_PrivateAppendToMappingString(), SDL_PrivateGenerateAutomaticGamepadMapping(), SDL_RenderAssertMessage(), SDL_RunApp(), SDL_setenv_unsafe(), SDL_SetTrayEntryLabel(), SDL_snprintf(), and SDL_SYS_GetPreferredLocales_winxp().
SDL_sqrt()
SDL_DECLSPEC double SDLCALL SDL_sqrt (double x) extern
Compute the square root of x.
Domain: 0 <= x <= INF
Range: 0 <= y <= INF
This function operates on double-precision floating point values, use SDL_sqrtf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than or equal to 0.
Returns
square root of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sqrtf
{
#ifdef HAVE_SQRT
    return sqrt(x);
#else
    return SDL_uclibc_sqrt(x);
#endif
}
References SDL_uclibc_sqrt().
Referenced by SDL_acos(), and SDL_sqrtf().
SDL_sqrtf()
SDL_DECLSPEC float SDLCALL SDL_sqrtf (float x) extern
Compute the square root of x.
Domain: 0 <= x <= INF
Range: 0 <= y <= INF
This function operates on single-precision floating point values, use SDL_sqrt for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value. Must be greater than or equal to 0.
Returns
square root of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_sqrt
{
#ifdef HAVE_SQRTF
    return sqrtf(x);
#else
    return (float)SDL_sqrt((double)x);
#endif
}
References SDL_sqrt().
Referenced by GenerateResamplerFilter().
SDL_srand()
SDL_DECLSPEC void SDLCALL SDL_srand (Uint64 seed) extern
Seeds the pseudo-random number generator.
Reusing the seed number will cause SDL_rand() to repeat the same stream of 'random' numbers.
Parameters
seed the value to use as a random number seed, or 0 to use SDL_GetPerformanceCounter().
Thread Safety
This should be called on the same thread that calls SDL_rand()
Since
This function is available since SDL 3.2.0.
See also
SDL_rand
SDL_rand_bits
SDL_randf
{
    if (!seed) {
        seed = SDL_GetPerformanceCounter();
    }
    SDL_rand_state = seed;
    SDL_rand_initialized = true;
}
References SDL_GetPerformanceCounter(), SDL_rand_initialized, and SDL_rand_state.
Referenced by SDL_rand(), SDL_rand_bits(), SDL_randf(), and SDL_vasprintf().
SDL_sscanf()
SDL_DECLSPEC int SDLCALL SDL_sscanf (const char * text, const char * fmt, ...) extern
This works exactly like sscanf() but doesn't require access to a C runtime.
Scan a string, matching a format string, converting each '' item and storing it to pointers provided through variable arguments.
Parameters
text the string to scan. Must not be NULL.
fmt a printf-style format string. Must not be NULL.
... a list of pointers to values to be filled in with scanned items.
Returns
the number of items that matched the format string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDL_SCANF_FORMAT_STRING, SDL_SCANF_VARARG_FUNC, and SDLCALL.
Referenced by ParseDisplayUsableBoundsHint(), SDL_Haptic_Load_Axes_List(), SDL_UpdateSteamVirtualGamepadInfo(), and WaveLoad().
SDL_StepBackUTF8()
SDL_DECLSPEC Uint32 SDLCALL SDL_StepBackUTF8 (const char * start, const char ** pstr) extern
Decode a UTF-8 string in reverse, one Unicode codepoint at a time.
This will go to the start of the previous Unicode codepoint in the string, move *pstr to that location and return that codepoint.
If *pstr is already at the start of the string), it will not advance *pstr at all.
Generally this function is called in a loop until it returns zero, adjusting its parameter each iteration.
If an invalid UTF-8 sequence is encountered, this function returns SDL_INVALID_UNICODE_CODEPOINT.
Several things can generate invalid UTF-8 sequences, including overlong encodings, the use of UTF-16 surrogate values, and truncated data. Please refer to RFC3629 for details.
Parameters
start a pointer to the beginning of the UTF-8 string.
pstr a pointer to a UTF-8 string pointer to be read and adjusted.
Returns
the previous Unicode codepoint in the string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!pstr || *pstr <= start) {
        return 0;
    }
    // Step back over the previous UTF-8 character
    const char *str = *pstr;
    do {
        if (str == start) {
            break;
        }
        --str;
    } while ((*str & 0xC0) == 0x80);
    size_t length = (*pstr - str);
    *pstr = str;
    return StepUTF8(&str, length);
}
References StepUTF8().
SDL_StepUTF8()
SDL_DECLSPEC Uint32 SDLCALL SDL_StepUTF8 (const char ** pstr, size_t * pslen) extern
Decode a UTF-8 string, one Unicode codepoint at a time.
This will return the first Unicode codepoint in the UTF-8 encoded string in *pstr, and then advance *pstr past any consumed bytes before returning.
It will not access more than *pslen bytes from the string. *pslen will be adjusted, as well, subtracting the number of bytes consumed.
pslen is allowed to be NULL, in which case the string must be NULL-terminated, as the function will blindly read until it sees the NULL char.
if *pslen is zero, it assumes the end of string is reached and returns a zero codepoint regardless of the contents of the string buffer.
If the resulting codepoint is zero (a NULL terminator), or *pslen is zero, it will not advance *pstr or *pslen at all.
Generally this function is called in a loop until it returns zero, adjusting its parameters each iteration.
If an invalid UTF-8 sequence is encountered, this function returns SDL_INVALID_UNICODE_CODEPOINT and advances the string/length by one byte (which is to say, a multibyte sequence might produce several SDL_INVALID_UNICODE_CODEPOINT returns before it syncs to the next valid UTF-8 sequence).
Several things can generate invalid UTF-8 sequences, including overlong encodings, the use of UTF-16 surrogate values, and truncated data. Please refer to RFC3629 for details.
Parameters
pstr a pointer to a UTF-8 string pointer to be read and adjusted.
pslen a pointer to the number of bytes in the string, to be read and adjusted. NULL is allowed.
Returns
the first Unicode codepoint in the string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!pslen) {
        return StepUTF8(pstr, 4);  // 4 == max codepoint size.
    }
    const char *origstr = *pstr;
    const Uint32 result = StepUTF8(pstr, *pslen);
    *pslen -= (size_t) (*pstr - origstr);
    return result;
}
References StepUTF8().
Referenced by CaseFoldUtf8String(), SDL_RenderDebugText(), SDL_strcasestr(), SDL_utf8strlen(), and SDL_utf8strnlen().
SDL_strcasecmp()
SDL_DECLSPEC int SDLCALL SDL_strcasecmp (const char * str1, const char * str2) extern
Compare two null-terminated UTF-8 strings, case-insensitively.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Since this handles Unicode, it expects the string to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    UNICODE_STRCASECMP(8, 4, 4, (void) str1start, (void) str2start);  // always NULL-terminated, no need to adjust lengths.
}
References UNICODE_STRCASECMP.
Referenced by AutoShowingScreenKeyboard(), SDL_Blit_Slow_Float(), SDL_CameraInit(), SDL_CreateWindowTexture(), SDL_GetGamepadAxisFromString(), SDL_GetGamepadTypeFromString(), SDL_GetKeyFromName(), SDL_GetScancodeFromName(), SDL_GetStringBoolean(), SDL_GetStringInteger(), SDL_GPUSelectBackend(), SDL_iconv_open(), SDL_InitAudio(), SDL_PrivateAddGamepadMapping(), SDL_PrivateGetGamepadButtonFromString(), SDL_ShouldMinimizeOnFocusLoss(), and ShouldAttemptTextureFramebuffer().
SDL_strcasestr()
SDL_DECLSPEC char *SDLCALL SDL_strcasestr (const char * haystack, const char * needle) extern
Search a UTF-8 string for the first instance of a specific substring, case-insensitively.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Since this handles Unicode, it expects the strings to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Parameters
haystack the string to search. Must not be NULL.
needle the string to search for. Must not be NULL.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    const size_t length = SDL_strlen(needle);
    do {
        if (SDL_strncasecmp(haystack, needle, length) == 0) {
            return (char *)haystack;
        }
    } while (SDL_StepUTF8(&haystack, NULL));  // move ahead by a full codepoint at a time, regardless of bytes.
    return NULL;
}
References NULL, SDL_StepUTF8(), SDL_strlen(), and SDL_strncasecmp().
Referenced by SDL_HIDAPI_ShouldIgnoreDevice().
SDL_strchr()
SDL_DECLSPEC char *SDLCALL SDL_strchr (const char * str, int c) extern
Search a string for the first instance of a specific byte.
The search ends once it finds the requested byte value, or a null terminator byte to end the string.
Note that this looks for bytes, not characters, so you cannot match against a Unicode codepoint > 255, regardless of character encoding.
Parameters
str the string to search. Must not be NULL.
c the byte value to search for.
Returns
a pointer to the first instance of c in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRCHR
    return SDL_const_cast(char *, strchr(string, c));
#elif defined(HAVE_INDEX)
    return SDL_const_cast(char *, index(string, c));
#else
    while (*string) {
        if (*string == c) {
            return (char *)string;
        }
        ++string;
    }
    if (c == '\0') {
        return (char *)string;
    }
    return NULL;
#endif // HAVE_STRCHR
}
References NULL, and SDL_const_cast.
Referenced by getlocale(), IsReadMode(), normalize_locale_str(), normalize_locales(), ParseLogPriorities(), SDL_AddGamepadMappingsFromIO(), SDL_CameraInit(), SDL_CPUFeatureMaskFromHint(), SDL_CreateEnvironment(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_GetGamepadTypeForID(), SDL_GL_ExtensionSupported(), SDL_InitAudio(), SDL_LoadGamepadHints(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_PrivateGetGamepadNameFromMappingString(), SDL_setenv_unsafe(), SDL_SetEnvironmentVariable(), SDL_ShowMessageBox(), SDL_unsetenv_unsafe(), SDL_UnsetEnvironmentVariable(), SDL_UpdateGamepadFaceStyle(), SDL_UpdateGamepadType(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_URIToLocal(), SDL_VideoInit(), and ValidateStoragePath().
SDL_strcmp()
SDL_DECLSPEC int SDLCALL SDL_strcmp (const char * str1, const char * str2) extern
Compare two null-terminated UTF-8 strings.
Due to the nature of UTF-8 encoding, this will work with Unicode strings, since effectively this function just compares bytes until it hits a null-terminating character. Also due to the nature of UTF-8, this can be used with SDL_qsort() to put strings in (roughly) alphabetical order.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRCMP
    return strcmp(str1, str2);
#else
    int result;
    while (1) {
        result = ((unsigned char)*str1 - (unsigned char)*str2);
        if (result != 0 || (*str1 == '\0' /* && *str2 == '\0'*/)) {
            break;
        }
        ++str1;
        ++str2;
    }
    return result;
#endif // HAVE_STRCMP
}
References strcmp.
Referenced by AsyncFileModeValid(), convert_ext_list(), DBus_MessageFilter(), detect_available_methods(), GetHintEnvironmentVariable(), getlocale(), HIDAPI_UpdateDiscovery(), InitIME(), IsROGAlly(), MainCallbackRateHintChanged(), PLATFORM_hid_open_path(), ResetHintsCallback(), SDL_CreateWindowTexture(), SDL_DefaultGraphicsBackends(), SDL_GetAppMetadataProperty(), SDL_GetCPUCacheLineSize(), SDL_GetGamepadFaceStyleFromString(), SDL_GetGamepadName(), SDL_GetGamepadNameForID(), SDL_GetGamepadTypeFromVIDPID(), SDL_GetNumAudioDrivers(), SDL_GetNumVideoDrivers(), SDL_GL_ExtensionSupported(), SDL_GL_LoadLibrary(), SDL_HasInternalClipboardData(), SDL_InitAudio(), SDL_KeyMatchString(), SDL_LoadBMP_IO(), SDL_PrivateAddGamepadMapping(), SDL_PromptAssertion(), SDL_RenderDebugTextFormat(), SDL_ResetHint(), SDL_SetDisplayModeForDisplay(), SDL_SetHintWithPriority(), SDL_SetWindowTitle(), SDL_ShouldIgnoreGamepad(), SDL_ShouldMinimizeOnFocusLoss(), SDL_SYS_SetThreadPriority(), SDL_UpdateFullscreenMode(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_ValidMetadataProperty(), SDL_Vulkan_LoadLibrary(), ShouldAttemptTextureFramebuffer(), validate_list(), ValidateStoragePath(), WaveGetFactChunkHint(), WaveGetRiffSizeHint(), and WaveGetTruncationHint().
SDL_strdup()
SDL_DECLSPEC SDL_MALLOC char *SDLCALL SDL_strdup (const char * str) extern
Allocate a copy of a string.
This allocates enough space for a null-terminated copy of str, using SDL_malloc, and then makes a copy of the string into this space.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
str the string to copy.
Returns
a pointer to the newly-allocated string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t len = SDL_strlen(string) + 1;
    char *newstr = (char *)SDL_malloc(len);
    if (newstr) {
        SDL_memcpy(newstr, string, len);
    }
    return newstr;
}
References SDL_malloc(), SDL_memcpy, and SDL_strlen().
Referenced by clear_filt_names(), convert_filter(), convert_filters(), CopyHIDDeviceInfo(), CopyOneProperty(), CreatePhysicalAudioDevice(), FcitxClientCreateIC(), GENERIC_EnumerateDirectory(), GENERIC_OpenFileStorage(), GENERIC_Title_Create(), GetAppName(), IgnoredDevicesChanged(), SDL_AddCamera(), SDL_AddKeyboard(), SDL_AddMouse(), SDL_AddPenDevice(), SDL_AddTouch(), SDL_AddVideoDisplay(), SDL_CameraInit(), SDL_CreateDeviceName(), SDL_CreateDirectory(), SDL_CreateEnvironment(), SDL_CreateJoystickName(), SDL_CreateTemporaryString(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateWindowTexture(), SDL_GetClipboardText(), SDL_GetPersistentString(), SDL_GetPrimarySelectionText(), SDL_InitAudio(), SDL_InitSteamVirtualGamepadInfo(), SDL_InternalGlobDirectory(), SDL_LoadGamepadHints(), SDL_OpenHaptic(), SDL_OpenJoystick(), SDL_OpenSensor(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_PrivateSetProperty(), SDL_SaveClipboardMimeTypes(), SDL_SetClipboardText(), SDL_SetHintWithPriority(), SDL_SetLogPriorityPrefix(), SDL_SetPrimarySelectionText(), SDL_SetStringProperty(), SDL_SetWindowTitle(), SDL_SYS_GetBasePath(), SDL_SYS_GetPrefPath(), SDL_SYS_GetUserFolder(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UpdateSteamVirtualGamepadInfo(), ShowFileDialog(), ShowFolderDialog(), windows_ShowFileDialog(), and zenity_clean_name().
SDL_strlcat()
SDL_DECLSPEC size_t SDLCALL SDL_strlcat (char * dst, const char * src, size_t maxlen) extern
Concatenate strings.
This function appends up to maxlen - SDL_strlen(dst) - 1 characters from src to the end of the string in dst, then appends a null terminator.
src and dst must not overlap.
If maxlen - SDL_strlen(dst) - 1 is less than or equal to 0, then dst is unmodified.
Parameters
dst The destination buffer already containing the first null-terminated string. Must not be NULL and must not overlap with src.
src The second null-terminated string. Must not be NULL, and must not overlap with dst.
maxlen The length (in characters) of the destination buffer.
Returns
the length (in characters, excluding the null terminator) of the string in dst plus the length of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strlcpy
References SDL_DECLSPEC, SDL_MALLOC, and SDLCALL.
Referenced by convert_ext_list(), convert_filters(), CreateMappingString(), normalize_locale_str(), SDL_CreateMappingForHIDAPIGamepad(), SDL_CreateMappingForRAWINPUTGamepad(), SDL_CreateMappingForWGIGamepad(), SDL_PrivateAppendToMappingString(), SDL_SYS_GetPreferredLocales(), and SDL_SYS_GetPrefPath().
SDL_strlcpy()
SDL_DECLSPEC size_t SDLCALL SDL_strlcpy (char * dst, const char * src, size_t maxlen) extern
Copy a string.
This function copies up to maxlen - 1 characters from src to dst, then appends a null terminator.
If maxlen is 0, no characters are copied and no null terminator is written.
If you want to copy an UTF-8 string but need to ensure that multi-byte sequences are not truncated, consider using SDL_utf8strlcpy().
Parameters
dst The destination buffer. Must not be NULL, and must not overlap with src.
src The null-terminated string to copy. Must not be NULL, and must not overlap with dst.
maxlen The length (in characters) of the destination buffer.
Returns
the length (in characters, excluding the null terminator) of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strlcat
SDL_utf8strlcpy
References SDL_DECLSPEC, and SDLCALL.
Referenced by Fcitx_GetPreeditString(), getlocale(), IOS_GetAppleSFSymbolsNameForButton(), SDL_AddGamepadMappingsFromIO(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_CreateJoystickGUID(), SDL_CreateMappingForHIDAPIGamepad(), SDL_CreateMappingForRAWINPUTGamepad(), SDL_CreateMappingForWGIGamepad(), SDL_CreateTray(), SDL_GetCPUType(), SDL_GetEventDescription(), SDL_GetGamepadMappingFilePath(), SDL_GetGamepadMappings(), SDL_GetPreferredLocales(), SDL_PrivateGenerateAutomaticGamepadMapping(), SDL_SYS_GetPreferredLocales(), SDL_SYS_SetupThread(), and windows_ShowFileDialog().
SDL_strlen()
SDL_DECLSPEC size_t SDLCALL SDL_strlen (const char * str) extern
This works exactly like strlen() but doesn't require access to a C runtime.
Counts the bytes in str, excluding the null terminator.
If you need the length of a UTF-8 string, consider using SDL_utf8strlen().
Parameters
str The null-terminated string to read. Must not be NULL.
Returns
the length (in bytes, excluding the null terminator) of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strnlen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_STRLEN
    return strlen(string);
#else
    size_t len = 0;
    while (*string++) {
        ++len;
    }
    return len;
#endif // HAVE_STRLEN
}
Referenced by CaseFoldUtf8String(), convert_ext_list(), convert_filter(), convert_filters(), CopyEnvStrings(), CountEnvStrings(), CreateCandidatesForEvent(), CreateMappingString(), escape_label(), Fcitx_GetPreeditString(), GENERIC_EnumerateDirectory(), GENERIC_EnumerateStorageDirectory(), GENERIC_OpenFileStorage(), GENERIC_Title_Create(), GetControllerTypeOverride(), GlobDirectoryCallback(), HasPrefix(), HIDAPI_UpdateDiscovery(), IOS_GetAppleSFSymbolsNameForButton(), ParseLogPriorities(), SDL_ClipboardTextCallback(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_CopyClipboardMimeTypes(), SDL_CPUFeatureMaskFromHint(), SDL_CreateDeviceName(), SDL_CreateDirectory(), SDL_CreateJoystickGUID(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_endswith(), SDL_GetClipboardData(), SDL_getenv_unsafe(), SDL_GetGamepadMappings(), SDL_GetKeyFromName(), SDL_GL_ExtensionSupported(), SDL_HashString(), SDL_InternalGlobDirectory(), SDL_IntPrecisionAdjust(), SDL_LogOutput(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_PrintString(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_PrivateParseGamepadElement(), SDL_setenv_unsafe(), SDL_SetEnvironmentVariable(), SDL_ShowMessageBox(), SDL_startswith(), SDL_strcasestr(), SDL_strdup(), SDL_StringToGUID(), SDL_strlcat(), SDL_strlcpy(), SDL_strnstr(), SDL_strrchr(), SDL_strrev(), SDL_strstr(), SDL_SYS_GetPreferredLocales(), SDL_SYS_OpenURL(), SDL_unsetenv_unsafe(), SDL_URIDecode(), SDL_URIToLocal(), SDL_utf8strlcpy(), SDL_VideoInit(), validate_list(), win_get_filters(), and windows_ShowFileDialog().
SDL_strlwr()
SDL_DECLSPEC char *SDLCALL SDL_strlwr (char * str) extern
Convert a string to lowercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'A' through 'Z' to lowercase.
This function operates on a null-terminated string of bytes–even if it is malformed UTF-8!–and converts ASCII characters 'A' through 'Z' to their lowercase equivalents in-place, returning the original str pointer.
Parameters
str the string to convert in-place. Can not be NULL.
Returns
the str pointer passed into this function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strupr
{
    char *bufp = string;
    while (*bufp) {
        *bufp = (char)SDL_tolower((unsigned char)*bufp);
        ++bufp;
    }
    return string;
}
References SDL_tolower().
Referenced by SDL_PrintString().
SDL_strncasecmp()
SDL_DECLSPEC int SDLCALL SDL_strncasecmp (const char * str1, const char * str2, size_t maxlen) extern
Compare two UTF-8 strings, case-insensitively, up to a number of bytes.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Since this handles Unicode, it expects the string to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Note that while this function is intended to be used with UTF-8, maxlen specifies a byte limit! If the limit lands in the middle of a multi-byte UTF-8 sequence, it may convert a portion of the final character to one or more Unicode character U+FFFD (REPLACEMENT CHARACTER) so as not to overflow a buffer.
maxlen specifies a maximum number of bytes to compare; if the strings match to this number of bytes (or both have matched to a null-terminator character before this number of bytes), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of bytes to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t slen1 = maxlen;
    size_t slen2 = maxlen;
    UNICODE_STRCASECMP(8, slen1, slen2, slen1 -= (size_t) (str1 - ((const char *) str1start)), slen2 -= (size_t) (str2 - ((const char *) str2start)));
}
References UNICODE_STRCASECMP.
Referenced by GuessControllerType(), ParseLogCategory(), ParseLogPriority(), SDL_AddGamepadMappingsFromIO(), SDL_CreateDeviceName(), SDL_CreateRendererWithProperties(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_ShowMessageBox(), SDL_strcasestr(), SDL_URIToLocal(), and SDL_VideoInit().
SDL_strncmp()
SDL_DECLSPEC int SDLCALL SDL_strncmp (const char * str1, const char * str2, size_t maxlen) extern
Compare two UTF-8 strings up to a number of bytes.
Due to the nature of UTF-8 encoding, this will work with Unicode strings, since effectively this function just compares bytes until it hits a null-terminating character. Also due to the nature of UTF-8, this can be used with SDL_qsort() to put strings in (roughly) alphabetical order.
Note that while this function is intended to be used with UTF-8, it is doing a bytewise comparison, and maxlen specifies a byte limit! If the limit lands in the middle of a multi-byte UTF-8 sequence, it will only compare a portion of the final character.
maxlen specifies a maximum number of bytes to compare; if the strings match to this number of bytes (or both have matched to a null-terminator character before this number of bytes), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of bytes to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRNCMP
    return strncmp(str1, str2, maxlen);
#else
    int result = 0;
    while (maxlen) {
        result = (int)(unsigned char)*str1 - (unsigned char)*str2;
        if (result != 0 || *str1 == '\0' /* && *str2 == '\0'*/) {
            break;
        }
        ++str1;
        ++str2;
        --maxlen;
    }
    return result;
#endif // HAVE_STRNCMP
}
Referenced by GetControllerTypeOverride(), HasPrefix(), PrefixMatch(), ref_string_equals(), SDL_Blit_Slow_Float(), SDL_getenv_unsafe(), SDL_IOFromFile(), SDL_IsTextMimeType(), SDL_LoadBMP_IO(), SDL_PromptAssertion(), SDL_setenv_unsafe(), SDL_ShouldIgnoreGamepad(), SDL_startswith(), SDL_strnstr(), SDL_unsetenv_unsafe(), SDL_vsnprintf(), SDL_vsscanf(), ShouldAttemptSensorFusion(), and ValidateStoragePath().
SDL_strndup()
SDL_DECLSPEC SDL_MALLOC char *SDLCALL SDL_strndup (const char * str, size_t maxlen) extern
Allocate a copy of a string, up to n characters.
This allocates enough space for a null-terminated copy of str, up to maxlen bytes, using SDL_malloc, and then makes a copy of the string into this space.
If the string is longer than maxlen bytes, the returned string will be maxlen bytes long, plus a null-terminator character that isn't included in the count.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
str the string to copy.
maxlen the maximum length of the copied string, not counting the null-terminator character.
Returns
a pointer to the newly-allocated string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t len = SDL_strnlen(string, maxlen);
    char *newstr = (char *)SDL_malloc(len + 1);
    if (newstr) {
        SDL_memcpy(newstr, string, len);
        newstr[len] = '\0';
    }
    return newstr;
}
References SDL_malloc(), SDL_memcpy, and SDL_strnlen().
SDL_strnlen()
SDL_DECLSPEC size_t SDLCALL SDL_strnlen (const char * str, size_t maxlen) extern
This works exactly like strnlen() but doesn't require access to a C runtime.
Counts up to a maximum of maxlen bytes in str, excluding the null terminator.
If you need the length of a UTF-8 string, consider using SDL_utf8strnlen().
Parameters
str The null-terminated string to read. Must not be NULL.
maxlen The maximum amount of bytes to count.
Returns
the length (in bytes, excluding the null terminator) of src but never more than maxlen.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strlen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_STRNLEN
    return strnlen(string, maxlen);
#else
    size_t len = 0;
    while (len < maxlen && *string++) {
        ++len;
    }
    return len;
#endif // HAVE_STRNLEN
}
Referenced by SDL_strndup().
SDL_strnstr()
SDL_DECLSPEC char *SDLCALL SDL_strnstr (const char * haystack, const char * needle, size_t maxlen) extern
Search a string, up to n bytes, for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator byte to end the string, or maxlen bytes have been examined. It is possible to use this function on a string without a null terminator.
Note that this looks for strings of bytes, not characters, so it's legal to search for malformed and incomplete UTF-8 sequences.
Parameters
haystack the string to search. Must not be NULL.
needle the string to search for. Must not be NULL.
maxlen the maximum number of bytes to search in haystack.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRNSTR
    return SDL_const_cast(char *, strnstr(haystack, needle, maxlen));
#else
    size_t length = SDL_strlen(needle);
    if (length == 0) {
        return (char *)haystack;
    }
    while (maxlen >= length && *haystack) {
        if (SDL_strncmp(haystack, needle, length) == 0) {
            return (char *)haystack;
        }
        ++haystack;
        --maxlen;
    }
    return NULL;
#endif // HAVE_STRSTR
}
References NULL, SDL_const_cast, SDL_strlen(), and SDL_strncmp().
Referenced by SDL_strstr().
SDL_strpbrk()
SDL_DECLSPEC char *SDLCALL SDL_strpbrk (const char * str, const char * breakset) extern
Searches a string for the first occurence of any character contained in a breakset, and returns a pointer from the string to that character.
Parameters
str The null-terminated string to be searched. Must not be NULL, and must not overlap with breakset.
breakset A null-terminated string containing the list of characters to look for. Must not be NULL, and must not overlap with str.
Returns
A pointer to the location, in str, of the first occurence of a character present in the breakset, or NULL if none is found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRPBRK
    return strpbrk(str, breakset);
#else
    for (; *str; str++) {
        const char *b;
        for (b = breakset; *b; b++) {
            if (*str == *b) {
                return (char *) str;
            }
        }
    }
    return NULL;
#endif
}
References NULL.
SDL_strrchr()
SDL_DECLSPEC char *SDLCALL SDL_strrchr (const char * str, int c) extern
Search a string for the last instance of a specific byte.
The search must go until it finds a null terminator byte to end the string.
Note that this looks for bytes, not characters, so you cannot match against a Unicode codepoint > 255, regardless of character encoding.
Parameters
str the string to search. Must not be NULL.
c the byte value to search for.
Returns
a pointer to the last instance of c in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRRCHR
    return SDL_const_cast(char *, strrchr(string, c));
#elif defined(HAVE_RINDEX)
    return SDL_const_cast(char *, rindex(string, c));
#else
    const char *bufp = string + SDL_strlen(string);
    while (bufp >= string) {
        if (*bufp == c) {
            return (char *)bufp;
        }
        --bufp;
    }
    return NULL;
#endif // HAVE_STRRCHR
}
References NULL, SDL_const_cast, and SDL_strlen().
Referenced by GetAppName(), SDL_GetExeName(), and SDL_SYS_GetPreferredLocales().
SDL_strrev()
SDL_DECLSPEC char *SDLCALL SDL_strrev (char * str) extern
Reverse a string's contents.
This reverses a null-terminated string in-place. Only the content of the string is reversed; the null-terminator character remains at the end of the reversed string.
WARNING: This function reverses the bytes of the string, not the codepoints. If str is a UTF-8 string with Unicode codepoints > 127, this will ruin the string data. You should only use this function on strings that are completely comprised of low ASCII characters.
Parameters
str the string to reverse.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE__STRREV
    return _strrev(string);
#else
    size_t len = SDL_strlen(string);
    char *a = &string[0];
    char *b = &string[len - 1];
    len /= 2;
    while (len--) {
        const char c = *a; // NOLINT(clang-analyzer-core.uninitialized.Assign)
        *a++ = *b;
        *b-- = c;
    }
    return string;
#endif // HAVE__STRREV
}
References SDL_strlen().
Referenced by SDL_ulltoa(), and SDL_ultoa().
SDL_strstr()
SDL_DECLSPEC char *SDLCALL SDL_strstr (const char * haystack, const char * needle) extern
Search a string for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator byte to end the string.
Note that this looks for strings of bytes, not characters, so it's legal to search for malformed and incomplete UTF-8 sequences.
Parameters
haystack the string to search. Must not be NULL.
needle the string to search for. Must not be NULL.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRSTR
    return SDL_const_cast(char *, strstr(haystack, needle));
#else
    return SDL_strnstr(haystack, needle, SDL_strlen(haystack));
#endif // HAVE_STRSTR
}
References SDL_const_cast, SDL_strlen(), and SDL_strnstr().
Referenced by CreateMappingString(), Fcitx_SetCapabilities(), GetControllerTypeOverride(), InitIME(), SDL_AddGamepadMappingsFromIO(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_GetGamepadTypeForID(), SDL_GetGamepadTypeFromVIDPID(), SDL_GL_ExtensionSupported(), SDL_KeycodeOptionsChanged(), SDL_LoadVIDPIDListFromHint(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadMappingForNameAndGUID(), SDL_PrivateMatchGamepadMappingForGUID(), SDL_PrivateParseGamepadElement(), SDL_ShouldIgnoreGamepad(), SDL_UpdateGamepadFaceStyle(), SDL_UpdateGamepadType(), SDL_URIToLocal(), and ShouldAttemptSensorFusion().
SDL_strtod()
SDL_DECLSPEC double SDLCALL SDL_strtod (const char * str, char ** endp) extern
Parse a double from a string.
This function makes fewer guarantees than the C runtime strtod:
Only decimal notation is guaranteed to be supported. The handling of scientific and hexadecimal notation is unspecified.
Whether or not INF and NAN can be parsed is unspecified.
The precision of the result is unspecified.
Parameters
str the null-terminated string to read. Must not be NULL.
endp if not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
Returns
the parsed double, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoll
SDL_strtoul
SDL_strtoull
{
#ifdef HAVE_STRTOD
    return strtod(string, endp);
#else
    double value;
    size_t len = SDL_ScanFloat(string, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOD
}
References SDL_ScanFloat().
Referenced by SDL_atof().
SDL_strtok_r()
SDL_DECLSPEC char *SDLCALL SDL_strtok_r (char * str, const char * delim, char ** saveptr) extern
This works exactly like strtok_r() but doesn't require access to a C runtime.
Break a string up into a series of tokens.
To start tokenizing a new string, str should be the non-NULL address of the string to start tokenizing. Future calls to get the next token from the same string should specify a NULL.
Note that this function will overwrite pieces of str with null chars to split it into tokens. This function cannot be used with const/read-only strings!
saveptr just needs to point to a char * that can be overwritten; SDL will use this to save tokenizing state between calls. It is initialized if str is non-NULL, and used to resume tokenizing when str is NULL.
Parameters
str the string to tokenize, or NULL to continue tokenizing.
delim the delimiter string that separates tokens.
saveptr pointer to a char *, used for ongoing state.
Returns
A pointer to the next token, or NULL if no tokens remain.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRTOK_R
    return strtok_r(s1, s2, ptr);
#else /* SDL implementation */
/*
 * Adapted from _PDCLIB_strtok() of PDClib library at
 * https://github.com/DevSolar/pdclib.git
 *
 * The code was under CC0 license:
 * https://creativecommons.org/publicdomain/zero/1.0/legalcode :
 *
 *                        No Copyright
 *
 * The person who associated a work with this deed has dedicated the
 * work to the public domain by waiving all of his or her rights to
 * the work worldwide under copyright law, including all related and
 * neighboring rights, to the extent allowed by law.
 *
 * You can copy, modify, distribute and perform the work, even for
 * commercial purposes, all without asking permission. See Other
 * Information below.
 */
    const char *p = s2;
    if (!s2 || !ptr || (!s1 && !*ptr)) return NULL;
    if (s1 != NULL) {  /* new string */
        *ptr = s1;
    } else { /* old string continued */
        if (*ptr == NULL) {
        /* No old string, no new string, nothing to do */
            return NULL;
        }
        s1 = *ptr;
    }
    /* skip leading s2 characters */
    while (*p && *s1) {
        if (*s1 == *p) {
        /* found separator; skip and start over */
            ++s1;
            p = s2;
            continue;
        }
        ++p;
    }
    if (! *s1) { /* no more to parse */
        *ptr = s1;
        return NULL;
    }
    /* skipping non-s2 characters */
    *ptr = s1;
    while (**ptr) {
        p = s2;
        while (*p) {
            if (**ptr == *p++) {
            /* found separator; overwrite with '\0', position *ptr, return */
                *((*ptr)++) = '\0';
                return s1;
            }
        }
        ++(*ptr);
    }
    /* parsed to end of string */
    return s1;
#endif
}
References NULL.
SDL_strtol()
SDL_DECLSPEC long SDLCALL SDL_strtol (const char * str, char ** endp, int base) extern
Parse a long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside a long, the result is clamped to the minimum and maximum representable long values.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtoul
SDL_strtoll
SDL_strtoull
SDL_strtod
SDL_ltoa
SDL_wcstol
{
#ifdef HAVE_STRTOL
    return strtol(string, endp, base);
#else
    long value = 0;
    size_t len = SDL_ScanLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOL
}
References SDL_ScanLong().
Referenced by SDL_atoi(), SDL_LoadVIDPIDListFromHint(), SDL_PrivateAddMappingForGUID(), SDL_PrivateMatchGamepadMappingForGUID(), and SDL_vsnprintf().
SDL_strtoll()
SDL_DECLSPEC long long SDLCALL SDL_strtoll (const char * str, char ** endp, int base) extern
Parse a long long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside a long long, the result is clamped to the minimum and maximum representable long long values.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed long long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoul
SDL_strtoull
SDL_strtod
SDL_lltoa
{
#ifdef HAVE_STRTOLL
    return strtoll(string, endp, base);
#else
    long long value = 0;
    size_t len = SDL_ScanLongLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOLL
}
References SDL_ScanLongLong().
Referenced by SDL_GetNumberProperty().
SDL_strtoul()
SDL_DECLSPEC unsigned long SDLCALL SDL_strtoul (const char * str, char ** endp, int base) extern
Parse an unsigned long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside an unsigned long, the result is clamped to the maximum representable unsigned long value.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed unsigned long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoll
SDL_strtoull
SDL_strtod
SDL_ultoa
{
#ifdef HAVE_STRTOUL
    return strtoul(string, endp, base);
#else
    unsigned long value = 0;
    size_t len = SDL_ScanUnsignedLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOUL
}
References SDL_ScanUnsignedLong().
Referenced by SDL_UpdateSteamVirtualGamepadInfo().
SDL_strtoull()
SDL_DECLSPEC unsigned long long SDLCALL SDL_strtoull (const char * str, char ** endp, int base) extern
Parse an unsigned long long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside an unsigned long long, the result is clamped to the maximum representable unsigned long long value.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed unsigned long long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoll
SDL_strtoul
SDL_strtod
SDL_ulltoa
{
#ifdef HAVE_STRTOULL
    return strtoull(string, endp, base);
#else
    unsigned long long value = 0;
    size_t len = SDL_ScanUnsignedLongLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOULL
}
References SDL_ScanUnsignedLongLong().
Referenced by SDL_ScanFloat(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_strupr()
SDL_DECLSPEC char *SDLCALL SDL_strupr (char * str) extern
Convert a string to uppercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'A' through 'Z' to uppercase.
This function operates on a null-terminated string of bytes–even if it is malformed UTF-8!–and converts ASCII characters 'a' through 'z' to their uppercase equivalents in-place, returning the original str pointer.
Parameters
str the string to convert in-place. Can not be NULL.
Returns
the str pointer passed into this function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strlwr
{
    char *bufp = string;
    while (*bufp) {
        *bufp = (char)SDL_toupper((unsigned char)*bufp);
        ++bufp;
    }
    return string;
}
References SDL_toupper().
Referenced by SDL_PrintString().
SDL_swprintf()
SDL_DECLSPEC int SDLCALL SDL_swprintf (wchar_t * text, size_t maxlen, const wchar_t * fmt, ...) extern
This works exactly like swprintf() but doesn't require access to a C runtime.
Format a wide string of up to maxlen-1 wchar_t values, converting each '' item with values provided through variable arguments.
While some C runtimes differ on how to deal with too-large strings, this function null-terminates the output, by treating the null-terminator as part of the maxlen count. Note that if maxlen is zero, however, no wide characters will be written at all.
This function returns the number of wide characters (not codepoints) that should be written, excluding the null-terminator character. If this returns a number >= maxlen, it means the output string was truncated. A negative return value means an error occurred.
Referencing the output string's pointer with a format item is undefined behavior.
Parameters
text the buffer to write the wide string into. Must not be NULL.
maxlen the maximum wchar_t values to write, including the null-terminator.
fmt a printf-style format string. Must not be NULL.
... a list of values to be used with the format string.
Returns
the number of wide characters that should be written, not counting the null-terminator char, or a negative value on error.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDL_OUT_Z_CAP, SDL_PRINTF_FORMAT_STRING, SDL_swprintf(), SDL_WPRINTF_VARARG_FUNC, and SDLCALL.
Referenced by SDL_swprintf().
SDL_tan()
SDL_DECLSPEC double SDLCALL SDL_tan (double x) extern
Compute the tangent of x.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF
This function operates on double-precision floating point values, use SDL_tanf for single-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
tangent of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_tanf
SDL_sin
SDL_cos
SDL_atan
SDL_atan2
{
#ifdef HAVE_TAN
    return tan(x);
#else
    return SDL_uclibc_tan(x);
#endif
}
References SDL_uclibc_tan(), and tan.
Referenced by SDL_tanf().
SDL_tanf()
SDL_DECLSPEC float SDLCALL SDL_tanf (float x) extern
Compute the tangent of x.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF
This function operates on single-precision floating point values, use SDL_tan for double-precision floats.
This function may use a different approximation across different versions, platforms and configurations. i.e, it can return a different value given the same input on different machines or operating systems, or if SDL is updated.
Parameters
x floating point value, in radians.
Returns
tangent of x.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_tan
SDL_sinf
SDL_cosf
SDL_atanf
SDL_atan2f
{
#ifdef HAVE_TANF
    return tanf(x);
#else
    return (float)SDL_tan((double)x);
#endif
}
References SDL_tan().
SDL_tolower()
SDL_DECLSPEC int SDLCALL SDL_tolower (int x) extern
Convert low-ASCII English letters to lowercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'A' through 'Z' to lowercase.
This function returns the lowercase equivalent of x. If a character cannot be converted, or is already lowercase, this function returns x.
Parameters
x character value to check.
Returns
lowercase version of x, or x if no conversion available.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'A') && ((x) <= 'Z') ? ('a' + ((x) - 'A')) : (x); }
Referenced by PrefixMatch(), SDL_strlwr(), and SDL_vsscanf().
SDL_toupper()
SDL_DECLSPEC int SDLCALL SDL_toupper (int x) extern
Convert low-ASCII English letters to uppercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'a' through 'z' to uppercase.
This function returns the uppercase equivalent of x. If a character cannot be converted, or is already uppercase, this function returns x.
Parameters
x character value to check.
Returns
capitalized version of x, or x if no conversion available.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{ return ((x) >= 'a') && ((x) <= 'z') ? ('A' + ((x) - 'a')) : (x); }
Referenced by SDL_strupr().
SDL_trunc()
SDL_DECLSPEC double SDLCALL SDL_trunc (double x) extern
Truncate x to an integer.
Rounds x to the next closest integer to 0. This is equivalent to removing the fractional part of x, leaving only the integer part.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on double-precision floating point values, use SDL_truncf for single-precision floats.
Parameters
x floating point value.
Returns
x truncated to an integer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_truncf
SDL_fmod
SDL_ceil
SDL_floor
SDL_round
SDL_lround
{
#ifdef HAVE_TRUNC
    return trunc(x);
#else
    if (x >= 0.0f) {
        return SDL_floor(x);
    } else {
        return SDL_ceil(x);
    }
#endif
}
References SDL_ceil(), and SDL_floor().
Referenced by SDL_truncf().
SDL_truncf()
SDL_DECLSPEC float SDLCALL SDL_truncf (float x) extern
Truncate x to an integer.
Rounds x to the next closest integer to 0. This is equivalent to removing the fractional part of x, leaving only the integer part.
Domain: -INF <= x <= INF
Range: -INF <= y <= INF, y integer
This function operates on single-precision floating point values, use SDL_trunc for double-precision floats.
Parameters
x floating point value.
Returns
x truncated to an integer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_trunc
SDL_fmodf
SDL_ceilf
SDL_floorf
SDL_roundf
SDL_lroundf
{
#ifdef HAVE_TRUNCF
    return truncf(x);
#else
    return (float)SDL_trunc((double)x);
#endif
}
References SDL_trunc().
Referenced by SDL_PrivateSendMouseMotion().
SDL_UCS4ToUTF8()
SDL_DECLSPEC char *SDLCALL SDL_UCS4ToUTF8 (Uint32 codepoint, char * dst) extern
Convert a single Unicode codepoint to UTF-8.
The buffer pointed to by dst must be at least 4 bytes long, as this function may generate between 1 and 4 bytes of output.
This function returns the first byte after the newly-written UTF-8 sequence, which is useful for encoding multiple codepoints in a loop, or knowing where to write a NULL-terminator character to end the string (in either case, plan to have a buffer of more than 4 bytes!).
If codepoint is an invalid value (outside the Unicode range, or a UTF-16 surrogate value, etc), this will use U+FFFD (REPLACEMENT CHARACTER) for the codepoint instead, and not set an error.
If dst is NULL, this returns NULL immediately without writing to the pointer and without setting an error.
Parameters
codepoint a Unicode codepoint to convert to UTF-8.
dst the location to write the encoded UTF-8. Must point to at least 4 bytes!
Returns
the first byte past the newly-written UTF-8 sequence.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!dst) {
        return NULL;  // I guess...?
    } else if (codepoint > 0x10FFFF) {  // Outside the range of Unicode codepoints (also, larger than can be encoded in 4 bytes of UTF-8!).
        codepoint = SDL_INVALID_UNICODE_CODEPOINT;
    } else if ((codepoint >= 0xD800) && (codepoint <= 0xDFFF)) {  // UTF-16 surrogate values are illegal in UTF-8.
        codepoint = SDL_INVALID_UNICODE_CODEPOINT;
    }
    Uint8 *p = (Uint8 *)dst;
    if (codepoint <= 0x7F) {
        *p = (Uint8)codepoint;
        ++dst;
    } else if (codepoint <= 0x7FF) {
        p[0] = 0xC0 | (Uint8)((codepoint >> 6) & 0x1F);
        p[1] = 0x80 | (Uint8)(codepoint & 0x3F);
        dst += 2;
    } else if (codepoint <= 0xFFFF) {
        p[0] = 0xE0 | (Uint8)((codepoint >> 12) & 0x0F);
        p[1] = 0x80 | (Uint8)((codepoint >> 6) & 0x3F);
        p[2] = 0x80 | (Uint8)(codepoint & 0x3F);
        dst += 3;
    } else {
        SDL_assert(codepoint <= 0x10FFFF);
        p[0] = 0xF0 | (Uint8)((codepoint >> 18) & 0x07);
        p[1] = 0x80 | (Uint8)((codepoint >> 12) & 0x3F);
        p[2] = 0x80 | (Uint8)((codepoint >> 6) & 0x3F);
        p[3] = 0x80 | (Uint8)(codepoint & 0x3F);
        dst += 4;
    }
    return dst;
}
References NULL, SDL_assert, and SDL_INVALID_UNICODE_CODEPOINT.
Referenced by SDL_GetKeyName().
SDL_uitoa()
SDL_DECLSPEC char *SDLCALL SDL_uitoa (unsigned int value, char * str, int radix) extern
Convert an unsigned integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget null terminator bytes, etc).
Parameters
value the unsigned integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_itoa
SDL_ultoa
SDL_ulltoa
{
#ifdef HAVE__UITOA
    return _uitoa(value, string, radix);
#else
    return SDL_ultoa((unsigned long)value, string, radix);
#endif // HAVE__UITOA
}
References SDL_ultoa().
SDL_ulltoa()
SDL_DECLSPEC char *SDLCALL SDL_ulltoa (unsigned long long value, char * str, int radix) extern
Convert an unsigned long long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget null terminator bytes, etc).
Parameters
value the unsigned long long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_lltoa
SDL_uitoa
SDL_ultoa
{
#ifdef HAVE__UI64TOA
    return _ui64toa(value, string, radix);
#else
    char *bufp = string;
    if (value) {
        while (value > 0) {
            *bufp++ = ntoa_table[value % radix];
            value /= radix;
        }
    } else {
        *bufp++ = '0';
    }
    *bufp = '\0';
    // The numbers went into the string backwards. :)
    SDL_strrev(string);
    return string;
#endif // HAVE__UI64TOA
}
References ntoa_table, and SDL_strrev().
Referenced by SDL_lltoa(), SDL_PrintPointer(), and SDL_PrintUnsignedLongLong().
SDL_ultoa()
SDL_DECLSPEC char *SDLCALL SDL_ultoa (unsigned long value, char * str, int radix) extern
Convert an unsigned long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget null terminator bytes, etc).
Parameters
value the unsigned long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ltoa
SDL_uitoa
SDL_ulltoa
{
#ifdef HAVE__ULTOA
    return _ultoa(value, string, radix);
#else
    char *bufp = string;
    if (value) {
        while (value > 0) {
            *bufp++ = ntoa_table[value % radix];
            value /= radix;
        }
    } else {
        *bufp++ = '0';
    }
    *bufp = '\0';
    // The numbers went into the string backwards. :)
    SDL_strrev(string);
    return string;
#endif // HAVE__ULTOA
}
References ntoa_table, and SDL_strrev().
Referenced by SDL_ltoa(), SDL_PrintUnsignedLong(), and SDL_uitoa().
SDL_unsetenv_unsafe()
SDL_DECLSPEC int SDLCALL SDL_unsetenv_unsafe (const char * name) extern
Clear a variable from the environment.
Parameters
name the name of the variable to unset.
Returns
0 on success, -1 on error.
Thread Safety
This function is not thread safe, consider using SDL_UnsetEnvironmentVariable() instead.
Since
This function is available since SDL 3.2.0.
See also
SDL_UnsetEnvironmentVariable
{
    size_t len, i;
    // Input validation
    if (!name || *name == '\0' || SDL_strchr(name, '=') != NULL) {
        return -1;
    }
    SDL_UnsetEnvironmentVariable(SDL_GetEnvironment(), name);
    if (environ) {
        len = SDL_strlen(name);
        for (i = 0; environ[i]; ++i) {
            if ((SDL_strncmp(environ[i], name, len) == 0) &&
                (environ[i][len] == '=')) {
                // Just clear out this entry for now
                *environ[i] = '\0';
                break;
            }
        }
    }
    return 0;
}
References environ, NULL, SDL_GetEnvironment(), SDL_strchr(), SDL_strlen(), SDL_strncmp(), and SDL_UnsetEnvironmentVariable().
Referenced by SDL_SetEnvironmentVariable().
SDL_UnsetEnvironmentVariable()
SDL_DECLSPEC unsigned char SDLCALL SDL_UnsetEnvironmentVariable (SDL_Environment * env, const char * name) extern
Clear a variable from the environment.
Parameters
env the environment to modify.
name the name of the variable to unset.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariable
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    bool result = false;
    if (!env) {
        return SDL_InvalidParamError("env");
    } else if (!name || *name == '\0' || SDL_strchr(name, '=') != NULL) {
        return SDL_InvalidParamError("name");
    }
    SDL_LockMutex(env->lock);
    {
        const void *value;
        if (SDL_FindInHashTable(env->strings, name, &value)) {
            result = SDL_RemoveFromHashTable(env->strings, name);
        } else {
            result = true;
        }
    }
    SDL_UnlockMutex(env->lock);
    return result;
}
References SDL_Environment::lock, NULL, SDL_FindInHashTable(), SDL_InvalidParamError, SDL_LockMutex(), SDL_RemoveFromHashTable(), SDL_strchr(), SDL_UnlockMutex(), and SDL_Environment::strings.
Referenced by SDL_SetEnvironmentVariable(), SDL_SYS_OpenURL(), and SDL_unsetenv_unsafe().
SDL_utf8strlcpy()
SDL_DECLSPEC size_t SDLCALL SDL_utf8strlcpy (char * dst, const char * src, size_t dst_bytes) extern
Copy an UTF-8 string.
This function copies up to dst_bytes - 1 bytes from src to dst while also ensuring that the string written to dst does not end in a truncated multi-byte sequence. Finally, it appends a null terminator.
src and dst must not overlap.
Note that unlike SDL_strlcpy(), this function returns the number of bytes written, not the length of src.
Parameters
dst The destination buffer. Must not be NULL, and must not overlap with src.
src The null-terminated UTF-8 string to copy. Must not be NULL, and must not overlap with dst.
dst_bytes The length (in bytes) of the destination buffer. Must not be 0.
Returns
the number of bytes written, excluding the null terminator.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strlcpy
References SDL_DECLSPEC, and SDLCALL.
SDL_utf8strlen()
SDL_DECLSPEC size_t SDLCALL SDL_utf8strlen (const char * str) extern
Count the number of codepoints in a UTF-8 string.
Counts the codepoints, not bytes, in str, excluding the null terminator.
If you need to count the bytes in a string instead, consider using SDL_strlen().
Since this handles Unicode, it expects the strings to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), so a malformed or incomplete UTF-8 sequence might increase the count by several replacement characters.
Parameters
str The null-terminated UTF-8 string to read. Must not be NULL.
Returns
The length (in codepoints, excluding the null terminator) of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_utf8strnlen
SDL_strlen
{
    size_t result = 0;
    while (SDL_StepUTF8(&str, NULL)) {
        result++;
    }
    return result;
}
References NULL, and SDL_StepUTF8().
Referenced by Fcitx_GetPreeditString().
SDL_utf8strnlen()
SDL_DECLSPEC size_t SDLCALL SDL_utf8strnlen (const char * str, size_t bytes) extern
Count the number of codepoints in a UTF-8 string, up to n bytes.
Counts the codepoints, not bytes, in str, excluding the null terminator.
If you need to count the bytes in a string instead, consider using SDL_strnlen().
The counting stops at bytes bytes (not codepoints!). This seems counterintuitive, but makes it easy to express the total size of the string's buffer.
Since this handles Unicode, it expects the strings to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), so a malformed or incomplete UTF-8 sequence might increase the count by several replacement characters.
Parameters
str The null-terminated UTF-8 string to read. Must not be NULL.
bytes The maximum amount of bytes to count.
Returns
The length (in codepoints, excluding the null terminator) of src but never more than maxlen.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_utf8strlen
SDL_strnlen
{
    size_t result = 0;
    while (SDL_StepUTF8(&str, &bytes)) {
        result++;
    }
    return result;
}
References SDL_StepUTF8().
Referenced by DBus_MessageFilter().
SDL_vasprintf()
SDL_DECLSPEC int SDLCALL SDL_vasprintf (char ** strp, const char * fmt, va_list ap) extern
This works exactly like vasprintf() but doesn't require access to a C runtime.
Functions identically to SDL_asprintf(), except it takes a va_list instead of using ... variable arguments.
Parameters
strp on output, is set to the new string. Must not be NULL.
fmt a printf-style format string. Must not be NULL.
ap a va_list values to be used with the format string.
Returns
the number of bytes in the newly-allocated string, not counting the null-terminator char, or a negative value on error.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNCV, SDL_rand(), SDL_rand_bits(), SDL_rand_bits_r(), SDL_rand_r(), SDL_randf(), SDL_randf_r(), SDL_srand(), SDL_vasprintf(), and SDLCALL.
Referenced by SDL_IOprintf(), SDL_IOvprintf(), SDL_RenderDebugTextFormat(), and SDL_vasprintf().
SDL_vsnprintf()
SDL_DECLSPEC int SDLCALL SDL_vsnprintf (char * text, size_t maxlen, const char * fmt, va_list ap) extern
This works exactly like vsnprintf() but doesn't require access to a C runtime.
Functions identically to SDL_snprintf(), except it takes a va_list instead of using ... variable arguments.
Parameters
text the buffer to write the string into. Must not be NULL.
maxlen the maximum bytes to write, including the null-terminator.
fmt a printf-style format string. Must not be NULL.
ap a va_list values to be used with the format string.
Returns
the number of bytes that should be written, not counting the null-terminator char, or a negative value on error.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDL_OUT_Z_CAP, SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNCV, SDL_vsnprintf(), and SDLCALL.
Referenced by SDL_LogMessageV(), SDL_SetErrorV(), and SDL_vsnprintf().
SDL_vsscanf()
SDL_DECLSPEC int SDLCALL SDL_vsscanf (const char * text, const char * fmt, va_list ap) extern
This works exactly like vsscanf() but doesn't require access to a C runtime.
Functions identically to SDL_sscanf(), except it takes a va_list instead of using ... variable arguments.
Parameters
text the string to scan. Must not be NULL.
fmt a printf-style format string. Must not be NULL.
ap a va_list of pointers to values to be filled in with scanned items.
Returns
the number of items that matched the format string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDL_SCANF_FORMAT_STRING, SDL_SCANF_VARARG_FUNCV, SDL_vsscanf(), and SDLCALL.
Referenced by SDL_vsscanf().
SDL_vswprintf()
SDL_DECLSPEC int SDLCALL SDL_vswprintf (wchar_t * text, size_t maxlen, const wchar_t * fmt, va_list ap) extern
This works exactly like vswprintf() but doesn't require access to a C runtime.
Functions identically to SDL_swprintf(), except it takes a va_list instead of using ... variable arguments.
Parameters
text the buffer to write the string into. Must not be NULL.
maxlen the maximum wide characters to write, including the null-terminator.
fmt a printf-style format wide string. Must not be NULL.
ap a va_list values to be used with the format string.
Returns
the number of wide characters that should be written, not counting the null-terminator char, or a negative value on error.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDL_OUT_Z_CAP, SDL_PRINTF_FORMAT_STRING, SDL_vswprintf(), SDL_WPRINTF_VARARG_FUNCV, and SDLCALL.
Referenced by SDL_vswprintf().
SDL_wcscasecmp()
SDL_DECLSPEC int SDLCALL SDL_wcscasecmp (const wchar_t * str1, const wchar_t * str2) extern
Compare two null-terminated wide strings, case-insensitively.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Depending on your platform, "wchar_t" might be 2 bytes, and expected to be UTF-16 encoded (like Windows), or 4 bytes in UTF-32 format. Since this handles Unicode, it expects the string to be well-formed and not a null-terminated string of arbitrary bytes. Characters that are not valid UTF-16 (or UTF-32) are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#if (SDL_SIZEOF_WCHAR_T == 2)
    const Uint16 *str1 = (const Uint16 *) wstr1;
    const Uint16 *str2 = (const Uint16 *) wstr2;
    UNICODE_STRCASECMP(16, 2, 2, (void) str1start, (void) str2start);  // always NULL-terminated, no need to adjust lengths.
#elif (SDL_SIZEOF_WCHAR_T == 4)
    const Uint32 *str1 = (const Uint32 *) wstr1;
    const Uint32 *str2 = (const Uint32 *) wstr2;
    UNICODE_STRCASECMP(32, 1, 1, (void) str1start, (void) str2start);  // always NULL-terminated, no need to adjust lengths.
#else
    #error Unexpected wchar_t size
    return -1;
#endif
}
References UNICODE_STRCASECMP.
SDL_wcscmp()
SDL_DECLSPEC int SDLCALL SDL_wcscmp (const wchar_t * str1, const wchar_t * str2) extern
Compare two null-terminated wide strings.
This only compares wchar_t values until it hits a null-terminating character; it does not care if the string is well-formed UTF-16 (or UTF-32, depending on your platform's wchar_t size), or uses valid Unicode values.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_WCSCMP
    return wcscmp(str1, str2);
#else
    while (*str1 && *str2) {
        if (*str1 != *str2) {
            break;
        }
        ++str1;
        ++str2;
    }
    return *str1 - *str2;
#endif // HAVE_WCSCMP
}
References wcscmp.
Referenced by TrayWindowProc().
SDL_wcsdup()
SDL_DECLSPEC wchar_t *SDLCALL SDL_wcsdup (const wchar_t * wstr) extern
Allocate a copy of a wide string.
This allocates enough space for a null-terminated copy of wstr, using SDL_malloc, and then makes a copy of the string into this space.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
wstr the string to copy.
Returns
a pointer to the newly-allocated wide string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t len = ((SDL_wcslen(string) + 1) * sizeof(wchar_t));
    wchar_t *newstr = (wchar_t *)SDL_malloc(len);
    if (newstr) {
        SDL_memcpy(newstr, string, len);
    }
    return newstr;
}
References SDL_malloc(), SDL_memcpy, and SDL_wcslen().
SDL_wcslcat()
SDL_DECLSPEC size_t SDLCALL SDL_wcslcat (wchar_t * dst, const wchar_t * src, size_t maxlen) extern
Concatenate wide strings.
This function appends up to maxlen - SDL_wcslen(dst) - 1 wide characters from src to the end of the wide string in dst, then appends a null terminator.
src and dst must not overlap.
If maxlen - SDL_wcslen(dst) - 1 is less than or equal to 0, then dst is unmodified.
Parameters
dst The destination buffer already containing the first null-terminated wide string. Must not be NULL and must not overlap with src.
src The second null-terminated wide string. Must not be NULL, and must not overlap with dst.
maxlen The length (in wide characters) of the destination buffer.
Returns
the length (in wide characters, excluding the null terminator) of the string in dst plus the length of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_wcslcpy
References SDL_DECLSPEC, and SDLCALL.
SDL_wcslcpy()
SDL_DECLSPEC size_t SDLCALL SDL_wcslcpy (wchar_t * dst, const wchar_t * src, size_t maxlen) extern
Copy a wide string.
This function copies maxlen - 1 wide characters from src to dst, then appends a null terminator.
src and dst must not overlap.
If maxlen is 0, no wide characters are copied and no null terminator is written.
Parameters
dst The destination buffer. Must not be NULL, and must not overlap with src.
src The null-terminated wide string to copy. Must not be NULL, and must not overlap with dst.
maxlen The length (in wide characters) of the destination buffer.
Returns
the length (in wide characters, excluding the null terminator) of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_wcslcat
References SDL_DECLSPEC, and SDLCALL.
Referenced by SDL_CreateTray(), and SDL_SetTrayTooltip().
SDL_wcslen()
SDL_DECLSPEC size_t SDLCALL SDL_wcslen (const wchar_t * wstr) extern
This works exactly like wcslen() but doesn't require access to a C runtime.
Counts the number of wchar_t values in wstr, excluding the null terminator.
Like SDL_strlen only counts bytes and not codepoints in a UTF-8 string, this counts wchar_t values in a string, even if the string's encoding is of variable width, like UTF-16.
Also be aware that wchar_t is different sizes on different platforms (4 bytes on Linux, 2 on Windows, etc).
Parameters
wstr The null-terminated wide string to read. Must not be NULL.
Returns
the length (in wchar_t values, excluding the null terminator) of wstr.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_wcsnlen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_WCSLEN
    return wcslen(string);
#else
    size_t len = 0;
    while (*string++) {
        ++len;
    }
    return len;
#endif // HAVE_WCSLEN
}
References wcslen.
Referenced by CreateWStringFromWString(), SDL_CreateEnvironment(), SDL_PrintStringW(), SDL_SetTrayEntryLabel(), SDL_vswprintf(), SDL_wcsdup(), SDL_wcslcat(), SDL_wcslcpy(), SDL_wcsnstr(), SDL_wcsstr(), and windows_ShowFileDialog().
SDL_wcsncasecmp()
SDL_DECLSPEC int SDLCALL SDL_wcsncasecmp (const wchar_t * str1, const wchar_t * str2, size_t maxlen) extern
Compare two wide strings, case-insensitively, up to a number of wchar_t.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Depending on your platform, "wchar_t" might be 2 bytes, and expected to be UTF-16 encoded (like Windows), or 4 bytes in UTF-32 format. Since this handles Unicode, it expects the string to be well-formed and not a null-terminated string of arbitrary bytes. Characters that are not valid UTF-16 (or UTF-32) are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Note that while this function might deal with variable-sized characters, maxlen specifies a wchar limit! If the limit lands in the middle of a multi-byte UTF-16 sequence, it may convert a portion of the final character to one or more Unicode character U+FFFD (REPLACEMENT CHARACTER) so as not to overflow a buffer.
maxlen specifies a maximum number of wchar_t values to compare; if the strings match to this number of wchar_t (or both have matched to a null-terminator character before this number of bytes), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of wchar_t values to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t slen1 = maxlen;
    size_t slen2 = maxlen;
#if (SDL_SIZEOF_WCHAR_T == 2)
    const Uint16 *str1 = (const Uint16 *) wstr1;
    const Uint16 *str2 = (const Uint16 *) wstr2;
    UNICODE_STRCASECMP(16, slen1, slen2, slen1 -= (size_t) (str1 - str1start), slen2 -= (size_t) (str2 - str2start));
#elif (SDL_SIZEOF_WCHAR_T == 4)
    const Uint32 *str1 = (const Uint32 *) wstr1;
    const Uint32 *str2 = (const Uint32 *) wstr2;
    UNICODE_STRCASECMP(32, slen1, slen2, slen1 -= (size_t) (str1 - str1start), slen2 -= (size_t) (str2 - str2start));
#else
    #error Unexpected wchar_t size
    return -1;
#endif
}
References UNICODE_STRCASECMP.
SDL_wcsncmp()
SDL_DECLSPEC int SDLCALL SDL_wcsncmp (const wchar_t * str1, const wchar_t * str2, size_t maxlen) extern
Compare two wide strings up to a number of wchar_t values.
This only compares wchar_t values; it does not care if the string is well-formed UTF-16 (or UTF-32, depending on your platform's wchar_t size), or uses valid Unicode values.
Note that while this function is intended to be used with UTF-16 (or UTF-32, depending on your platform's definition of wchar_t), it is comparing raw wchar_t values and not Unicode codepoints: maxlen specifies a wchar_t limit! If the limit lands in the middle of a multi-wchar UTF-16 sequence, it will only compare a portion of the final character.
maxlen specifies a maximum number of wchar_t to compare; if the strings match to this number of wide chars (or both have matched to a null-terminator character before this count), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of wchar_t to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_WCSNCMP
    return wcsncmp(str1, str2, maxlen);
#else
    while (*str1 && *str2 && maxlen) {
        if (*str1 != *str2) {
            break;
        }
        ++str1;
        ++str2;
        --maxlen;
    }
    if (!maxlen) {
        return 0;
    }
    return *str1 - *str2;
#endif // HAVE_WCSNCMP
}
Referenced by SDL_wcsnstr().
SDL_wcsnlen()
SDL_DECLSPEC size_t SDLCALL SDL_wcsnlen (const wchar_t * wstr, size_t maxlen) extern
This works exactly like wcsnlen() but doesn't require access to a C runtime.
Counts up to a maximum of maxlen wchar_t values in wstr, excluding the null terminator.
Like SDL_strnlen only counts bytes and not codepoints in a UTF-8 string, this counts wchar_t values in a string, even if the string's encoding is of variable width, like UTF-16.
Also be aware that wchar_t is different sizes on different platforms (4 bytes on Linux, 2 on Windows, etc).
Also, maxlen is a count of wide characters, not bytes!
Parameters
wstr The null-terminated wide string to read. Must not be NULL.
maxlen The maximum amount of wide characters to count.
Returns
the length (in wide characters, excluding the null terminator) of wstr but never more than maxlen.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_wcslen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_WCSNLEN
    return wcsnlen(string, maxlen);
#else
    size_t len = 0;
    while (len < maxlen && *string++) {
        ++len;
    }
    return len;
#endif // HAVE_WCSNLEN
}
SDL_wcsnstr()
SDL_DECLSPEC wchar_t *SDLCALL SDL_wcsnstr (const wchar_t * haystack, const wchar_t * needle, size_t maxlen) extern
Search a wide string, up to n wide chars, for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator value to end the string, or maxlen wide character have been examined. It is possible to use this function on a wide string without a null terminator.
Note that this looks for strings of wide characters, not codepoints, so it's legal to search for malformed and incomplete UTF-16 sequences.
Parameters
haystack the wide string to search. Must not be NULL.
needle the wide string to search for. Must not be NULL.
maxlen the maximum number of wide characters to search in haystack.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t length = SDL_wcslen(needle);
    if (length == 0) {
        return (wchar_t *)haystack;
    }
    while (maxlen >= length && *haystack) {
        if (maxlen >= length && SDL_wcsncmp(haystack, needle, length) == 0) {
            return (wchar_t *)haystack;
        }
        ++haystack;
        --maxlen;
    }
    return NULL;
}
References NULL, SDL_wcslen(), and SDL_wcsncmp().
Referenced by SDL_wcsstr().
SDL_wcsstr()
SDL_DECLSPEC wchar_t *SDLCALL SDL_wcsstr (const wchar_t * haystack, const wchar_t * needle) extern
Search a wide string for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator byte to end the string.
Note that this looks for strings of wide characters, not codepoints, so it's legal to search for malformed and incomplete UTF-16 sequences.
Parameters
haystack the wide string to search. Must not be NULL.
needle the wide string to search for. Must not be NULL.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_WCSSTR
    return SDL_const_cast(wchar_t *, wcsstr(haystack, needle));
#else
    return SDL_wcsnstr(haystack, needle, SDL_wcslen(haystack));
#endif // HAVE_WCSSTR
}
References SDL_const_cast, SDL_wcslen(), SDL_wcsnstr(), and wcsstr.
SDL_wcstol()
SDL_DECLSPEC long SDLCALL SDL_wcstol (const wchar_t * str, wchar_t ** endp, int base) extern
Parse a long from a wide string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside a long, the result is clamped to the minimum and maximum representable long values.
Parameters
str The null-terminated wide string to read. Must not be NULL.
endp If not NULL, the address of the first invalid wide character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strtol
{
#ifdef HAVE_WCSTOL
    return wcstol(string, endp, base);
#else
    long value = 0;
    size_t len = SDL_ScanLongW(string, 0, base, &value);
    if (endp) {
        *endp = (wchar_t *)string + len;
    }
    return value;
#endif // HAVE_WCSTOL
}
References SDL_ScanLongW(), and wcstol.
Variable Documentation
size
SDL_DECLSPEC size_t size