SDL3: SDL-main/src/SDL_internal.h File Reference
SDL_internal.h File Reference
#include "SDL_build_config.h"
#include "dynapi/SDL_dynapi.h"
#include <SDL3/SDL.h>
#include <SDL3/SDL_intrin.h>
#include <SDL3/SDL_main.h>
#include "SDL_utils_c.h"
#include "SDL_hashtable.h"
Macros
#define _GNU_SOURCE
#define _LARGEFILE64_SOURCE 1
#define O_CLOEXEC 0
#define POP_SDL_ERROR()
#define PUSH_SDL_ERROR()
#define SDL_BeginThreadFunction NULL
#define SDL_EndThreadFunction NULL
#define SDL_HAVE_BLIT_0 1
#define SDL_HAVE_BLIT_1 1
#define SDL_HAVE_BLIT_A 1
#define SDL_HAVE_BLIT_AUTO 1
#define SDL_HAVE_BLIT_N 1
#define SDL_HAVE_BLIT_N_RGB565 1
#define SDL_HAVE_RLE 1
#define SDL_HAVE_STB 1
#define SDL_HAVE_YUV 1
#define SDL_INTERNAL
#define SDL_MAIN_NOIMPL
#define SDL_MAX_SMALL_ALLOC_STACKSIZE 128
#define SDL_small_alloc(type, count, pisstack)
#define SDL_small_free(ptr, isstack)
#define SDL_VARIABLE_LENGTH_ARRAY
#define SDL_VIDEO_RENDER_SW 1
Functions
void SDL_InitMainThread (void)
bool SDLCALL SDL_WaitConditionTimeoutNS (SDL_Condition *cond, SDL_Mutex *mutex, Sint64 timeoutNS)
bool SDLCALL SDL_WaitEventTimeoutNS (SDL_Event *event, Sint64 timeoutNS)
bool SDLCALL SDL_WaitSemaphoreTimeoutNS (SDL_Semaphore *sem, Sint64 timeoutNS)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
_LARGEFILE64_SOURCE
#define _LARGEFILE64_SOURCE 1
O_CLOEXEC
#define O_CLOEXEC 0
Referenced by get_hid_report_descriptor(), hid_enumerate_callback(), parse_hid_vid_pid_from_uevent_path(), PLATFORM_hid_enumerate(), PLATFORM_hid_open_path(), SDL_WSCONS_Init_Keyboard(), and SDL_WSCONS_Init_Mouse().
POP_SDL_ERROR
#define POP_SDL_ERROR ()
Value:
    SDL_SetError("%s", _error); SDL_free(_error); }
#define POP_SDL_ERROR() \
    SDL_SetError("%s", _error); SDL_free(_error); }
Referenced by SDL_CreateWindowWithProperties().
PUSH_SDL_ERROR
#define PUSH_SDL_ERROR ()
Value:
    { char *_error = SDL_strdup(SDL_GetError());
#define PUSH_SDL_ERROR() \
    { char *_error = SDL_strdup(SDL_GetError());
Referenced by SDL_CreateWindowWithProperties().
SDL_BeginThreadFunction
#define SDL_BeginThreadFunction NULL
SDL_EndThreadFunction
#define SDL_EndThreadFunction NULL
SDL_HAVE_BLIT_0
#define SDL_HAVE_BLIT_0 1
SDL_HAVE_BLIT_1
#define SDL_HAVE_BLIT_1 1
SDL_HAVE_BLIT_A
#define SDL_HAVE_BLIT_A 1
SDL_HAVE_BLIT_AUTO
#define SDL_HAVE_BLIT_AUTO 1
SDL_HAVE_BLIT_N
#define SDL_HAVE_BLIT_N 1
SDL_HAVE_BLIT_N_RGB565
#define SDL_HAVE_BLIT_N_RGB565 1
SDL_HAVE_RLE
#define SDL_HAVE_RLE 1
SDL_HAVE_STB
#define SDL_HAVE_STB 1
SDL_HAVE_YUV
#define SDL_HAVE_YUV 1
SDL_INTERNAL
#define SDL_INTERNAL
SDL_MAIN_NOIMPL
#define SDL_MAIN_NOIMPL
SDL_MAX_SMALL_ALLOC_STACKSIZE
#define SDL_MAX_SMALL_ALLOC_STACKSIZE 128
SDL_small_alloc
#define SDL_small_alloc (type, count, pisstack)
Value:
((*(pisstack) = ((sizeof(type) * (count)) < SDL_MAX_SMALL_ALLOC_STACKSIZE)), (*(pisstack) ? SDL_stack_alloc(type, count) : (type *)SDL_malloc(sizeof(type) * (count))))
Referenced by IOS_MFIJoystickUpdate(), QueueCmdFillRects(), RenderLineBresenham(), RenderLinesWithRectsF(), RenderPointsWithRects(), SDL_FlipSurfaceHorizontal(), SDL_FlipSurfaceVertical(), SDL_LogOutput(), SDL_RenderFillRects(), SDL_RenderLines(), SDL_ShowMessageBox(), SDL_SYS_GetPreferredLocales(), SDL_SYS_GetPreferredLocales_vista(), and SDL_vswprintf().
SDL_small_free
#define SDL_small_free (ptr, isstack)
Value:
    if ((isstack)) {                 \
        SDL_stack_free(ptr);         \
    } else {                         \
        SDL_free(ptr);               \
    }
#define SDL_small_free(ptr, isstack) \
    if ((isstack)) {                 \
        SDL_stack_free(ptr);         \
    } else {                         \
        SDL_free(ptr);               \
    }
Referenced by IOS_MFIJoystickUpdate(), QueueCmdFillRects(), RenderLineBresenham(), RenderLinesWithRectsF(), RenderPointsWithRects(), SDL_FlipSurfaceHorizontal(), SDL_FlipSurfaceVertical(), SDL_LogOutput(), SDL_RenderFillRects(), SDL_RenderLines(), SDL_ShowMessageBox(), SDL_SYS_GetPreferredLocales(), SDL_SYS_GetPreferredLocales_vista(), and SDL_vswprintf().
SDL_VARIABLE_LENGTH_ARRAY
#define SDL_VARIABLE_LENGTH_ARRAY
SDL_VIDEO_RENDER_SW
#define SDL_VIDEO_RENDER_SW 1
Function Documentation
SDL_InitMainThread()
void SDL_InitMainThread (void) extern
{
    static bool done_info = false;
    SDL_InitTLSData();
    SDL_InitEnvironment();
    SDL_InitTicks();
    SDL_InitFilesystem();
    if (!done_info) {
        const char *value;
        value = SDL_GetAppMetadataProperty(SDL_PROP_APP_METADATA_NAME_STRING);
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "App name: %s", value ? value : "<unspecified>");
        value = SDL_GetAppMetadataProperty(SDL_PROP_APP_METADATA_VERSION_STRING);
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "App version: %s", value ? value : "<unspecified>");
        value = SDL_GetAppMetadataProperty(SDL_PROP_APP_METADATA_IDENTIFIER_STRING);
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "App ID: %s", value ? value : "<unspecified>");
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "SDL revision: %s", SDL_REVISION);
        done_info = true;
    }
}
References SDL_GetAppMetadataProperty(), SDL_InitEnvironment(), SDL_InitFilesystem(), SDL_InitTicks(), SDL_InitTLSData(), SDL_LOG_CATEGORY_SYSTEM, SDL_LogInfo(), SDL_PROP_APP_METADATA_IDENTIFIER_STRING, SDL_PROP_APP_METADATA_NAME_STRING, SDL_PROP_APP_METADATA_VERSION_STRING, and SDL_REVISION.
Referenced by SDL_CreateThreadWithPropertiesRuntime(), and SDL_InitSubSystem().
SDL_WaitConditionTimeoutNS()
bool SDLCALL SDL_WaitConditionTimeoutNS (SDL_Condition * cond, SDL_Mutex * mutex, Sint64 timeoutNS) extern
{
    return SDL_WaitConditionTimeoutNS_generic(cond, mutex, timeoutNS);
}
References SDL_Condition::cond, SDL_Mutex::id, NULL, SDL_cond_impl_active, SDL_NS_PER_SECOND, SDL_US_TO_NS, and SDL_WaitConditionTimeoutNS_generic().
Referenced by SDL_WaitCondition(), SDL_WaitConditionTimeout(), and SDL_WaitSemaphoreTimeoutNS().
SDL_WaitEventTimeoutNS()
bool SDLCALL SDL_WaitEventTimeoutNS (SDL_Event * event, Sint64 timeoutNS) extern
{
    Uint64 start, expiration;
    bool include_sentinel = (timeoutNS == 0);
    int result;
    if (timeoutNS > 0) {
        start = SDL_GetTicksNS();
        expiration = start + timeoutNS;
    } else {
        start = 0;
        expiration = 0;
    }
    // If there isn't a poll sentinel event pending, pump events and add one
    if (SDL_GetAtomicInt(&SDL_sentinel_pending) == 0) {
        SDL_PumpEventsInternal(true);
    }
    // First check for existing events
    result = SDL_PeepEventsInternal(event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST, include_sentinel);
    if (result < 0) {
        return false;
    }
    if (include_sentinel) {
        if (event) {
            if (event->type == SDL_EVENT_POLL_SENTINEL) {
                // Reached the end of a poll cycle, and not willing to wait
                return false;
            }
        } else {
            // Need to peek the next event to check for sentinel
            SDL_Event dummy;
            if (SDL_PeepEventsInternal(&dummy, 1, SDL_PEEKEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST, true) &&
                dummy.type == SDL_EVENT_POLL_SENTINEL) {
                SDL_PeepEventsInternal(&dummy, 1, SDL_GETEVENT, SDL_EVENT_POLL_SENTINEL, SDL_EVENT_POLL_SENTINEL, true);
                // Reached the end of a poll cycle, and not willing to wait
                return false;
            }
        }
    }
    if (result == 0) {
        if (timeoutNS == 0) {
            // No events available, and not willing to wait
            return false;
        }
    } else {
        // Has existing events
        return true;
    }
    // We should have completely handled timeoutNS == 0 above
    SDL_assert(timeoutNS != 0);
#ifdef SDL_PLATFORM_ANDROID
    for (;;) {
        if (SDL_PeepEvents(event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST) > 0) {
            return true;
        }
        Uint64 delay = -1;
        if (timeoutNS > 0) {
            Uint64 now = SDL_GetTicksNS();
            if (now >= expiration) {
                // Timeout expired and no events
                return false;
            }
            delay = (expiration - now);
        }
        Android_PumpEvents(delay);
    }
#else
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (_this && _this->WaitEventTimeout && _this->SendWakeupEvent) {
        // Look if a shown window is available to send the wakeup event.
        SDL_Window *wakeup_window = SDL_find_active_window(_this);
        if (wakeup_window) {
            result = SDL_WaitEventTimeout_Device(_this, wakeup_window, event, start, timeoutNS);
            if (result > 0) {
                return true;
            } else if (result == 0) {
                return false;
            } else {
                /* There may be implementation-defined conditions where the backend cannot
                 * reliably wait for the next event. If that happens, fall back to polling.
                 */
            }
        }
    }
    for (;;) {
        SDL_PumpEventsInternal(true);
        if (SDL_PeepEvents(event, 1, SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST) > 0) {
            return true;
        }
        Uint64 delay = EVENT_POLL_INTERVAL_NS;
        if (timeoutNS > 0) {
            Uint64 now = SDL_GetTicksNS();
            if (now >= expiration) {
                // Timeout expired and no events
                return false;
            }
            delay = SDL_min((expiration - now), delay);
        }
        SDL_DelayNS(delay);
    }
#endif // SDL_PLATFORM_ANDROID
}
References _this, Android_PumpEvents(), EVENT_POLL_INTERVAL_NS, SDL_assert, SDL_DelayNS(), SDL_EVENT_FIRST, SDL_EVENT_LAST, SDL_EVENT_POLL_SENTINEL, SDL_find_active_window(), SDL_GetAtomicInt(), SDL_GETEVENT, SDL_GetTicksNS(), SDL_GetVideoDevice(), SDL_min, SDL_PEEKEVENT, SDL_PeepEvents(), SDL_PeepEventsInternal(), SDL_PumpEventsInternal(), SDL_sentinel_pending, SDL_WaitEventTimeout_Device(), and SDL_Event::type.
Referenced by SDL_PollEvent(), SDL_WaitEvent(), and SDL_WaitEventTimeout().
SDL_WaitSemaphoreTimeoutNS()
bool SDLCALL SDL_WaitSemaphoreTimeoutNS (SDL_Semaphore * sem, Sint64 timeoutNS) extern
{
    bool result = false;
    if (!sem) {
        return true;
    }
    if (timeoutNS == 0) {
        SDL_LockMutex(sem->count_lock);
        if (sem->count > 0) {
            --sem->count;
            result = true;
        }
        SDL_UnlockMutex(sem->count_lock);
    } else if (timeoutNS < 0) {
        SDL_LockMutex(sem->count_lock);
        ++sem->waiters_count;
        while (sem->count == 0) {
            SDL_WaitConditionTimeoutNS(sem->count_nonzero, sem->count_lock, -1);
        }
        --sem->waiters_count;
        --sem->count;
        result = true;
        SDL_UnlockMutex(sem->count_lock);
    } else {
        Uint64 stop_time = SDL_GetTicksNS() + timeoutNS;
        SDL_LockMutex(sem->count_lock);
        ++sem->waiters_count;
        while (sem->count == 0) {
            Sint64 waitNS = (Sint64)(stop_time - SDL_GetTicksNS());
            if (waitNS > 0) {
                SDL_WaitConditionTimeoutNS(sem->count_nonzero, sem->count_lock, waitNS);
            } else {
                break;
            }
        }
        --sem->waiters_count;
        if (sem->count > 0) {
            --sem->count;
            result = true;
        }
        SDL_UnlockMutex(sem->count_lock);
    }
    return result;
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, NULL, SDL_DelayNS(), SDL_GetTicksNS(), SDL_LockMutex(), SDL_NS_PER_SECOND, SDL_UnlockMutex(), SDL_US_TO_NS, SDL_WaitConditionTimeoutNS(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_TimerThread(), SDL_TryWaitSemaphore(), SDL_WaitConditionTimeoutNS_generic(), SDL_WaitSemaphore(), and SDL_WaitSemaphoreTimeout().