SDL3: SDL-main/include/SDL3/SDL_hidapi.h File Reference
SDL_hidapi.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_hid_device_info
Typedefs
typedef enum SDL_hid_bus_type SDL_hid_bus_type
typedef struct SDL_hid_device SDL_hid_device
typedef struct SDL_hid_device_info SDL_hid_device_info
Enumerations
enum SDL_hid_bus_type {
SDL_HID_API_BUS_UNKNOWN = 0x00 , SDL_HID_API_BUS_USB = 0x01 , SDL_HID_API_BUS_BLUETOOTH = 0x02 , SDL_HID_API_BUS_I2C = 0x03 ,
SDL_HID_API_BUS_SPI = 0x04
}
Functions
SDL_DECLSPEC void SDLCALL SDL_hid_ble_scan (bool active)
SDL_DECLSPEC int SDLCALL SDL_hid_close (SDL_hid_device *dev)
SDL_DECLSPEC Uint32 SDLCALL SDL_hid_device_change_count (void)
SDL_DECLSPEC SDL_hid_device_info *SDLCALL SDL_hid_enumerate (unsigned short vendor_id, unsigned short product_id)
SDL_DECLSPEC int SDLCALL SDL_hid_exit (void)
SDL_DECLSPEC void SDLCALL SDL_hid_free_enumeration (SDL_hid_device_info *devs)
SDL_DECLSPEC SDL_hid_device_info *SDLCALL SDL_hid_get_device_info (SDL_hid_device *dev)
SDL_DECLSPEC int SDLCALL SDL_hid_get_feature_report (SDL_hid_device *dev, unsigned char *data, size_t length)
SDL_DECLSPEC int SDLCALL SDL_hid_get_indexed_string (SDL_hid_device *dev, int string_index, wchar_t *string, size_t maxlen)
SDL_DECLSPEC int SDLCALL SDL_hid_get_input_report (SDL_hid_device *dev, unsigned char *data, size_t length)
SDL_DECLSPEC int SDLCALL SDL_hid_get_manufacturer_string (SDL_hid_device *dev, wchar_t *string, size_t maxlen)
SDL_DECLSPEC int SDLCALL SDL_hid_get_product_string (SDL_hid_device *dev, wchar_t *string, size_t maxlen)
SDL_DECLSPEC int SDLCALL SDL_hid_get_report_descriptor (SDL_hid_device *dev, unsigned char *buf, size_t buf_size)
SDL_DECLSPEC int SDLCALL SDL_hid_get_serial_number_string (SDL_hid_device *dev, wchar_t *string, size_t maxlen)
SDL_DECLSPEC int SDLCALL SDL_hid_init (void)
SDL_DECLSPEC SDL_hid_device *SDLCALL SDL_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
SDL_DECLSPEC SDL_hid_device *SDLCALL SDL_hid_open_path (const char *path)
SDL_DECLSPEC int SDLCALL SDL_hid_read (SDL_hid_device *dev, unsigned char *data, size_t length)
SDL_DECLSPEC int SDLCALL SDL_hid_read_timeout (SDL_hid_device *dev, unsigned char *data, size_t length, int milliseconds)
SDL_DECLSPEC int SDLCALL SDL_hid_send_feature_report (SDL_hid_device *dev, const unsigned char *data, size_t length)
SDL_DECLSPEC int SDLCALL SDL_hid_set_nonblocking (SDL_hid_device *dev, int nonblock)
SDL_DECLSPEC int SDLCALL SDL_hid_write (SDL_hid_device *dev, const unsigned char *data, size_t length)
Typedef Documentation
SDL_hid_bus_type
typedef enum SDL_hid_bus_type SDL_hid_bus_type
HID underlying bus types.
Since
This enum is available since SDL 3.2.0.
SDL_hid_device
typedef struct SDL_hid_device SDL_hid_device
CategoryHIDAPI
Header file for SDL HIDAPI functions.
This is an adaptation of the original HIDAPI interface by Alan Ott, and includes source code licensed under the following license:
HIDAPI - Multi-Platform library for
communication with HID devices.
Copyright 2009, Alan Ott, Signal 11 Software.
All Rights Reserved.
This software may be used by anyone for any reason so
long as the copyright notice in the source files
remains intact.
(Note that this license is the same as item three of SDL's zlib license, so it adds no new requirements on the user.)
If you would like a version of SDL without this code, you can build SDL with SDL_HIDAPI_DISABLED defined to 1. You might want to do this for example on iOS or tvOS to avoid a dependency on the CoreBluetooth framework. An opaque handle representing an open HID device.
Since
This struct is available since SDL 3.2.0.
SDL_hid_device_info
typedef struct SDL_hid_device_info SDL_hid_device_info
hidapi info structure Information about a connected HID device
Since
This struct is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_hid_bus_type
enum SDL_hid_bus_type
HID underlying bus types.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_HID_API_BUS_UNKNOWN
Unknown bus type
SDL_HID_API_BUS_USB
USB bus Specifications: https://usb.org/hid
SDL_HID_API_BUS_BLUETOOTH
Bluetooth or Bluetooth LE bus Specifications: https://www.bluetooth.com/specifications/specs/human-interface-device-profile-1-1-1/ https://www.bluetooth.com/specifications/specs/hid-service-1-0/ https://www.bluetooth.com/specifications/specs/hid-over-gatt-profile-1-0/
SDL_HID_API_BUS_I2C
I2C bus Specifications: https://docs.microsoft.com/previous-versions/windows/hardware/design/dn642101(v=vs.85)
SDL_HID_API_BUS_SPI
SPI bus Specifications: https://www.microsoft.com/download/details.aspx?id=103325
{
    /** Unknown bus type */
    SDL_HID_API_BUS_UNKNOWN = 0x00,
    /** USB bus
       Specifications:
       https://usb.org/hid */
    SDL_HID_API_BUS_USB = 0x01,
    /** Bluetooth or Bluetooth LE bus
       Specifications:
       https://www.bluetooth.com/specifications/specs/human-interface-device-profile-1-1-1/
       https://www.bluetooth.com/specifications/specs/hid-service-1-0/
       https://www.bluetooth.com/specifications/specs/hid-over-gatt-profile-1-0/ */
    SDL_HID_API_BUS_BLUETOOTH = 0x02,
    /** I2C bus
       Specifications:
       https://docs.microsoft.com/previous-versions/windows/hardware/design/dn642101(v=vs.85) */
    SDL_HID_API_BUS_I2C = 0x03,
    /** SPI bus
       Specifications:
       https://www.microsoft.com/download/details.aspx?id=103325 */
    SDL_HID_API_BUS_SPI = 0x04
} SDL_hid_bus_type;
Function Documentation
SDL_hid_ble_scan()
SDL_DECLSPEC void SDLCALL SDL_hid_ble_scan (bool active) extern
Start or stop a BLE scan on iOS and tvOS to pair Steam Controllers.
Parameters
active true to start the scan, false to stop the scan.
Since
This function is available since SDL 3.2.0.
{
#if !defined(SDL_HIDAPI_DISABLED) && (defined(SDL_PLATFORM_IOS) || defined(SDL_PLATFORM_TVOS))
    extern void hid_ble_scan(int bStart);
    hid_ble_scan(active);
#endif
}
References active.
SDL_hid_close()
SDL_DECLSPEC int SDLCALL SDL_hid_close (SDL_hid_device * dev) extern
Close a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    device->backend->hid_close(device->device);
    DeleteHIDDeviceWrapper(device);
    return 0;
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, DeleteHIDDeviceWrapper(), SDL_hid_device::device, and hidapi_backend::hid_close.
SDL_hid_device_change_count()
SDL_DECLSPEC Uint32 SDLCALL SDL_hid_device_change_count (void) extern
Check to see if devices may have been added or removed.
Enumerating the HID devices is an expensive operation, so you can call this to see if there have been any system device changes since the last call to this function. A change in the counter returned doesn't necessarily mean that anything has changed, but you can call SDL_hid_enumerate() to get an updated device list.
Calling this function for the first time may cause a thread or other system resource to be allocated to track device change notifications.
Returns
a change counter that is incremented with each potential device change, or 0 if device change detection isn't available.
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_enumerate
{
    Uint32 counter = 0;
#ifndef SDL_HIDAPI_DISABLED
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return 0;
    }
    HIDAPI_UpdateDiscovery();
    if (SDL_HIDAPI_discovery.m_unDeviceChangeCounter == 0) {
        // Counter wrapped!
        ++SDL_HIDAPI_discovery.m_unDeviceChangeCounter;
    }
    counter = SDL_HIDAPI_discovery.m_unDeviceChangeCounter;
#endif // !SDL_HIDAPI_DISABLED
    return counter;
}
References HIDAPI_UpdateDiscovery(), SDL_hid_init(), SDL_HIDAPI_discovery, and SDL_hidapi_refcount.
SDL_hid_enumerate()
SDL_DECLSPEC SDL_hid_device_info *SDLCALL SDL_hid_enumerate (unsigned short vendor_id, unsigned short product_id) extern
Enumerate the HID Devices.
This function returns a linked list of all the HID devices attached to the system which match vendor_id and product_id. If vendor_id is set to 0 then any vendor matches. If product_id is set to 0 then any product matches. If vendor_id and product_id are both set to 0, then all HID devices will be returned.
By default SDL will only enumerate controllers, to reduce risk of hanging or crashing on bad drivers, but SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS can be set to "0" to enumerate all HID devices.
Parameters
vendor_id the Vendor ID (VID) of the types of device to open, or 0 to match any vendor.
product_id the Product ID (PID) of the types of device to open, or 0 to match any product.
Returns
a pointer to a linked list of type SDL_hid_device_info, containing information about the HID devices attached to the system, or NULL in the case of failure. Free this linked list by calling SDL_hid_free_enumeration().
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_device_change_count
{
    struct hid_device_info *driver_devs = NULL;
    struct hid_device_info *usb_devs = NULL;
    struct hid_device_info *raw_devs = NULL;
    struct hid_device_info *dev;
    struct SDL_hid_device_info *devs = NULL, *last = NULL;
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return NULL;
    }
    // Collect the available devices
#ifdef HAVE_DRIVER_BACKEND
    driver_devs = DRIVER_hid_enumerate(vendor_id, product_id);
#endif
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle) {
        usb_devs = LIBUSB_hid_enumerate(vendor_id, product_id);
        if (use_libusb_whitelist) {
            RemoveNonWhitelistedDevicesFromEnumeration(&usb_devs,  LIBUSB_hid_free_enumeration);
        }
    }
#endif // HAVE_LIBUSB
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        raw_devs = PLATFORM_hid_enumerate(vendor_id, product_id);
    }
#endif
    // Highest priority are custom driver devices
    for (dev = driver_devs; dev; dev = dev->next) {
        AddDeviceToEnumeration("driver", dev, &devs, &last);
#ifdef HAVE_LIBUSB
        RemoveDeviceFromEnumeration("libusb", dev, &usb_devs, LIBUSB_hid_free_enumeration);
#endif
#ifdef HAVE_PLATFORM_BACKEND
        RemoveDeviceFromEnumeration("raw", dev, &raw_devs, PLATFORM_hid_free_enumeration);
#endif
    }
    // If whitelist is in effect, libusb has priority, otherwise raw devices do
    if (use_libusb_whitelist) {
        for (dev = usb_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("libusb", dev, &devs, &last);
#ifdef HAVE_PLATFORM_BACKEND
            RemoveDeviceFromEnumeration("raw", dev, &raw_devs, PLATFORM_hid_free_enumeration);
#endif
        }
        for (dev = raw_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("platform", dev, &devs, &last);
        }
    } else {
        for (dev = raw_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("raw", dev, &devs, &last);
#ifdef HAVE_LIBUSB
            RemoveDeviceFromEnumeration("libusb", dev, &usb_devs, LIBUSB_hid_free_enumeration);
#endif
        }
        for (dev = usb_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("libusb", dev, &devs, &last);
        }
    }
#ifdef HAVE_DRIVER_BACKEND
    DRIVER_hid_free_enumeration(driver_devs);
#endif
#ifdef HAVE_LIBUSB
    LIBUSB_hid_free_enumeration(usb_devs);
#endif
#ifdef HAVE_PLATFORM_BACKEND
    PLATFORM_hid_free_enumeration(raw_devs);
#endif
    return devs;
}
References AddDeviceToEnumeration(), hid_device_info::next, NULL, PLATFORM_hid_enumerate(), PLATFORM_hid_free_enumeration(), SDL_hid_device_info::product_id, SDL_hid_init(), SDL_hidapi_refcount, udev_ctx, use_libusb_whitelist, and SDL_hid_device_info::vendor_id.
SDL_hid_exit()
SDL_DECLSPEC int SDLCALL SDL_hid_exit (void) extern
Finalize the HIDAPI library.
This function frees all of the static data associated with HIDAPI. It should be called at the end of execution to avoid memory leaks.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_init
{
    int result = 0;
    if (SDL_hidapi_refcount == 0) {
        return 0;
    }
    --SDL_hidapi_refcount;
    if (SDL_hidapi_refcount > 0) {
        return 0;
    }
    SDL_hidapi_refcount = 0;
#ifndef SDL_HIDAPI_DISABLED
    HIDAPI_ShutdownDiscovery();
#endif
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        result |= PLATFORM_hid_exit();
    }
#ifdef SDL_PLATFORM_LINUX
    SDL_UDEV_ReleaseUdevSyms();
#endif // __LINUX __
#endif // HAVE_PLATFORM_BACKEND
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle) {
        result |= LIBUSB_hid_exit();
#ifdef SDL_LIBUSB_DYNAMIC
        SDL_UnloadObject(libusb_ctx.libhandle);
#endif
        libusb_ctx.libhandle = NULL;
    }
#endif // HAVE_LIBUSB
    SDL_RemoveHintCallback(SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, OnlyControllersChanged, NULL);
    SDL_RemoveHintCallback(SDL_HINT_HIDAPI_IGNORE_DEVICES, IgnoredDevicesChanged, NULL);
    if (SDL_hidapi_ignored_devices) {
        SDL_free(SDL_hidapi_ignored_devices);
        SDL_hidapi_ignored_devices = NULL;
    }
    return result;
}
References HIDAPI_ShutdownDiscovery(), IgnoredDevicesChanged(), NULL, OnlyControllersChanged(), PLATFORM_hid_exit(), SDL_free(), SDL_hidapi_ignored_devices, SDL_hidapi_refcount, SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, SDL_HINT_HIDAPI_IGNORE_DEVICES, SDL_RemoveHintCallback(), SDL_UnloadObject(), and udev_ctx.
SDL_hid_free_enumeration()
SDL_DECLSPEC void SDLCALL SDL_hid_free_enumeration (SDL_hid_device_info * devs) extern
Free an enumeration linked list.
This function frees a linked list created by SDL_hid_enumerate().
Parameters
devs pointer to a list of struct_device returned from SDL_hid_enumerate().
Since
This function is available since SDL 3.2.0.
{
    while (devs) {
        struct SDL_hid_device_info *next = devs->next;
        SDL_free(devs->path);
        SDL_free(devs->serial_number);
        SDL_free(devs->manufacturer_string);
        SDL_free(devs->product_string);
        SDL_free(devs);
        devs = next;
    }
}
References SDL_hid_device_info::manufacturer_string, SDL_hid_device_info::next, SDL_hid_device_info::path, SDL_hid_device_info::product_string, SDL_free(), and SDL_hid_device_info::serial_number.
SDL_hid_get_device_info()
SDL_DECLSPEC SDL_hid_device_info *SDLCALL SDL_hid_get_device_info (SDL_hid_device * dev) extern
Get the device info from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
Returns
a pointer to the SDL_hid_device_info for this hid_device or NULL on failure; call SDL_GetError() for more information. This struct is valid until the device is closed with SDL_hid_close().
Since
This function is available since SDL 3.2.0.
{
    struct hid_device_info *info;
    CHECK_DEVICE_MAGIC(device, NULL);
    info = device->backend->hid_get_device_info(device->device);
    if (info) {
        CopyHIDDeviceInfo(info, &device->info);
        return &device->info;
    } else {
        return NULL;
    }
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, CopyHIDDeviceInfo(), SDL_hid_device::device, hidapi_backend::hid_get_device_info, SDL_hid_device::info, and NULL.
SDL_hid_get_feature_report()
SDL_DECLSPEC int SDLCALL SDL_hid_get_feature_report (SDL_hid_device * dev, unsigned char * data, size_t length) extern
Get a feature report from a HID device.
Set the first byte of data to the Report ID of the report to be read. Make sure to allow space for this extra byte in data. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into, including the Report ID. Set the first byte of data to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length the number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_feature_report(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_feature_report.
SDL_hid_get_indexed_string()
SDL_DECLSPEC int SDLCALL SDL_hid_get_indexed_string (SDL_hid_device * dev, int string_index, wchar_t * string, size_t maxlen) extern
Get a string from a HID device, based on its string index.
Parameters
dev a device handle returned from SDL_hid_open().
string_index the index of the string to get.
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_indexed_string(device->device, string_index, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_indexed_string.
SDL_hid_get_input_report()
SDL_DECLSPEC int SDLCALL SDL_hid_get_input_report (SDL_hid_device * dev, unsigned char * data, size_t length) extern
Get an input report from a HID device.
Set the first byte of data to the Report ID of the report to be read. Make sure to allow space for this extra byte in data. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into, including the Report ID. Set the first byte of data to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length the number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_input_report(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_input_report.
SDL_hid_get_manufacturer_string()
SDL_DECLSPEC int SDLCALL SDL_hid_get_manufacturer_string (SDL_hid_device * dev, wchar_t * string, size_t maxlen) extern
Get The Manufacturer String from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_manufacturer_string(device->device, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_manufacturer_string.
SDL_hid_get_product_string()
SDL_DECLSPEC int SDLCALL SDL_hid_get_product_string (SDL_hid_device * dev, wchar_t * string, size_t maxlen) extern
Get The Product String from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_product_string(device->device, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_product_string.
SDL_hid_get_report_descriptor()
SDL_DECLSPEC int SDLCALL SDL_hid_get_report_descriptor (SDL_hid_device * dev, unsigned char * buf, size_t buf_size) extern
Get a report descriptor from a HID device.
User has to provide a preallocated buffer where descriptor will be copied to. The recommended size for a preallocated buffer is 4096 bytes.
Parameters
dev a device handle returned from SDL_hid_open().
buf the buffer to copy descriptor into.
buf_size the size of the buffer in bytes.
Returns
the number of bytes actually copied or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_report_descriptor(device->device, buf, buf_size);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_report_descriptor.
SDL_hid_get_serial_number_string()
SDL_DECLSPEC int SDLCALL SDL_hid_get_serial_number_string (SDL_hid_device * dev, wchar_t * string, size_t maxlen) extern
Get The Serial Number String from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_serial_number_string(device->device, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_serial_number_string.
SDL_hid_init()
SDL_DECLSPEC int SDLCALL SDL_hid_init (void) extern
Initialize the HIDAPI library.
This function initializes the HIDAPI library. Calling it is not strictly necessary, as it will be called automatically by SDL_hid_enumerate() and any of the SDL_hid_open_*() functions if it is needed. This function should be called at the beginning of execution however, if there is a chance of HIDAPI handles being opened by different threads simultaneously.
Each call to this function should have a matching call to SDL_hid_exit()
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_exit
{
    int attempts = 0, success = 0;
    if (SDL_hidapi_refcount > 0) {
        ++SDL_hidapi_refcount;
        return 0;
    }
    SDL_AddHintCallback(SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, OnlyControllersChanged, NULL);
    SDL_AddHintCallback(SDL_HINT_HIDAPI_IGNORE_DEVICES, IgnoredDevicesChanged, NULL);
#ifdef SDL_USE_LIBUDEV
    if (!SDL_GetHintBoolean(SDL_HINT_HIDAPI_UDEV, true)) {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "udev disabled by SDL_HINT_HIDAPI_UDEV");
        linux_enumeration_method = ENUMERATION_FALLBACK;
    } else if (SDL_GetSandbox() != SDL_SANDBOX_NONE) {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "Container detected, disabling HIDAPI udev integration");
        linux_enumeration_method = ENUMERATION_FALLBACK;
    } else {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "Using udev for HIDAPI joystick device discovery");
        linux_enumeration_method = ENUMERATION_LIBUDEV;
    }
#endif
    use_libusb_whitelist = SDL_GetHintBoolean(SDL_HINT_HIDAPI_LIBUSB_WHITELIST,
                                              SDL_HINT_HIDAPI_LIBUSB_WHITELIST_DEFAULT);
#ifdef HAVE_LIBUSB
    if (!SDL_GetHintBoolean(SDL_HINT_HIDAPI_LIBUSB, true)) {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "libusb disabled with SDL_HINT_HIDAPI_LIBUSB");
        libusb_ctx.libhandle = NULL;
    } else {
        ++attempts;
#ifdef SDL_LIBUSB_DYNAMIC
        libusb_ctx.libhandle = SDL_LoadObject(SDL_LIBUSB_DYNAMIC);
#else
        libusb_ctx.libhandle = (void *)1;
#endif
        if (libusb_ctx.libhandle != NULL) {
            bool loaded = true;
#ifdef SDL_LIBUSB_DYNAMIC
#define LOAD_LIBUSB_SYMBOL(type, func)                                                                  \
    if ((libusb_ctx.func = (type)SDL_LoadFunction(libusb_ctx.libhandle, "libusb_" #func)) == NULL) {    \
        loaded = false;                                                                                 \
    }
#else
#define LOAD_LIBUSB_SYMBOL(type, func) \
    libusb_ctx.func = libusb_##func;
#endif
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_context **), init)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(libusb_context *), exit)
            LOAD_LIBUSB_SYMBOL(ssize_t (LIBUSB_CALL *)(libusb_context *, libusb_device ***), get_device_list)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(libusb_device **, int), free_device_list)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, struct libusb_device_descriptor *), get_device_descriptor)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, struct libusb_config_descriptor **), get_active_config_descriptor)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, uint8_t, struct libusb_config_descriptor **), get_config_descriptor)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(struct libusb_config_descriptor *), free_config_descriptor)
            LOAD_LIBUSB_SYMBOL(uint8_t (LIBUSB_CALL *)(libusb_device *), get_bus_number)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *dev, uint8_t *port_numbers, int port_numbers_len), get_port_numbers)
            LOAD_LIBUSB_SYMBOL(uint8_t (LIBUSB_CALL *)(libusb_device *), get_device_address)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, libusb_device_handle **), open)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(libusb_device_handle *), close)
            LOAD_LIBUSB_SYMBOL(libusb_device * (LIBUSB_CALL *)(libusb_device_handle *dev_handle), get_device)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), claim_interface)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), release_interface)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), kernel_driver_active)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), detach_kernel_driver)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), attach_kernel_driver)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int, int), set_interface_alt_setting)
            LOAD_LIBUSB_SYMBOL(struct libusb_transfer * (LIBUSB_CALL *)(int), alloc_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(struct libusb_transfer *), submit_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(struct libusb_transfer *), cancel_transfer)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(struct libusb_transfer *), free_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, uint8_t, uint8_t, uint16_t, uint16_t, unsigned char *, uint16_t, unsigned int), control_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, unsigned char, unsigned char *, int, int *, unsigned int), interrupt_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_context *), handle_events)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_context *, int *), handle_events_completed)
            LOAD_LIBUSB_SYMBOL(const char * (LIBUSB_CALL *)(int), error_name)
#undef LOAD_LIBUSB_SYMBOL
            if (!loaded) {
#ifdef SDL_LIBUSB_DYNAMIC
                SDL_UnloadObject(libusb_ctx.libhandle);
#endif
                libusb_ctx.libhandle = NULL;
                // SDL_LogWarn(SDL_LOG_CATEGORY_INPUT, SDL_LIBUSB_DYNAMIC " found but could not load function");
            } else if (LIBUSB_hid_init() < 0) {
#ifdef SDL_LIBUSB_DYNAMIC
                SDL_UnloadObject(libusb_ctx.libhandle);
#endif
                libusb_ctx.libhandle = NULL;
            } else {
                ++success;
            }
        }
    }
#endif // HAVE_LIBUSB
#ifdef HAVE_PLATFORM_BACKEND
    ++attempts;
#ifdef SDL_PLATFORM_LINUX
    udev_ctx = SDL_UDEV_GetUdevSyms();
#endif // __LINUX __
    if (udev_ctx && PLATFORM_hid_init() == 0) {
        ++success;
    }
#endif // HAVE_PLATFORM_BACKEND
    if (attempts > 0 && success == 0) {
        return -1;
    }
#if defined(SDL_PLATFORM_MACOS) && !defined(SDL_HIDAPI_DISABLED)
    hid_darwin_set_open_exclusive(0);
#endif
    ++SDL_hidapi_refcount;
    return 0;
}
References hid_darwin_set_open_exclusive(), IgnoredDevicesChanged(), NULL, OnlyControllersChanged(), PLATFORM_hid_init(), SDL_AddHintCallback(), SDL_GetHintBoolean(), SDL_GetSandbox(), SDL_hidapi_refcount, SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, SDL_HINT_HIDAPI_IGNORE_DEVICES, SDL_HINT_HIDAPI_LIBUSB, SDL_HINT_HIDAPI_LIBUSB_WHITELIST, SDL_HINT_HIDAPI_LIBUSB_WHITELIST_DEFAULT, SDL_HINT_HIDAPI_UDEV, SDL_LoadObject(), SDL_LOG_CATEGORY_INPUT, SDL_LogDebug(), SDL_SANDBOX_NONE, SDL_UnloadObject(), udev_ctx, and use_libusb_whitelist.
Referenced by SDL_hid_device_change_count(), SDL_hid_enumerate(), SDL_hid_open(), and SDL_hid_open_path().
SDL_hid_open()
SDL_DECLSPEC SDL_hid_device *SDLCALL SDL_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number) extern
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
If serial_number is NULL, the first device with the specified VID and PID is opened.
Parameters
vendor_id the Vendor ID (VID) of the device to open.
product_id the Product ID (PID) of the device to open.
serial_number the Serial Number of the device to open (Optionally NULL).
Returns
a pointer to a SDL_hid_device object on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
#if defined(HAVE_PLATFORM_BACKEND) || defined(HAVE_DRIVER_BACKEND) || defined(HAVE_LIBUSB)
    void *pDevice = NULL;
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return NULL;
    }
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        pDevice = PLATFORM_hid_open(vendor_id, product_id, serial_number);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &PLATFORM_Backend);
        }
    }
#endif // HAVE_PLATFORM_BACKEND
#ifdef HAVE_DRIVER_BACKEND
    pDevice = DRIVER_hid_open(vendor_id, product_id, serial_number);
    if (pDevice != NULL) {
        return CreateHIDDeviceWrapper(pDevice, &DRIVER_Backend);
    }
#endif // HAVE_DRIVER_BACKEND
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle != NULL) {
        pDevice = LIBUSB_hid_open(vendor_id, product_id, serial_number);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &LIBUSB_Backend);
        }
    }
#endif // HAVE_LIBUSB
#endif // HAVE_PLATFORM_BACKEND || HAVE_DRIVER_BACKEND || HAVE_LIBUSB
    return NULL;
}
References NULL, PLATFORM_hid_open(), SDL_hid_device_info::product_id, SDL_hid_init(), SDL_hidapi_refcount, SDL_hid_device_info::serial_number, udev_ctx, and SDL_hid_device_info::vendor_id.
SDL_hid_open_path()
SDL_DECLSPEC SDL_hid_device *SDLCALL SDL_hid_open_path (const char * path) extern
Open a HID device by its path name.
The path name be determined by calling SDL_hid_enumerate(), or a platform-specific path name can be used (eg: /dev/hidraw0 on Linux).
Parameters
path the path name of the device to open.
Returns
a pointer to a SDL_hid_device object on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
#if defined(HAVE_PLATFORM_BACKEND) || defined(HAVE_DRIVER_BACKEND) || defined(HAVE_LIBUSB)
    void *pDevice = NULL;
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return NULL;
    }
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        pDevice = PLATFORM_hid_open_path(path);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &PLATFORM_Backend);
        }
    }
#endif // HAVE_PLATFORM_BACKEND
#ifdef HAVE_DRIVER_BACKEND
    pDevice = DRIVER_hid_open_path(path);
    if (pDevice != NULL) {
        return CreateHIDDeviceWrapper(pDevice, &DRIVER_Backend);
    }
#endif // HAVE_DRIVER_BACKEND
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle != NULL) {
        pDevice = LIBUSB_hid_open_path(path);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &LIBUSB_Backend);
        }
    }
#endif // HAVE_LIBUSB
#endif // HAVE_PLATFORM_BACKEND || HAVE_DRIVER_BACKEND || HAVE_LIBUSB
    return NULL;
}
References NULL, SDL_hid_device_info::path, PLATFORM_hid_open_path(), SDL_hid_init(), SDL_hidapi_refcount, and udev_ctx.
SDL_hid_read()
SDL_DECLSPEC int SDLCALL SDL_hid_read (SDL_hid_device * dev, unsigned char * data, size_t length) extern
Read an Input report from a HID device.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into.
length the number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
Returns
the actual number of bytes read and -1 on failure; call SDL_GetError() for more information. If no packet was available to be read and the handle is in non-blocking mode, this function returns 0.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_read(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_read.
SDL_hid_read_timeout()
SDL_DECLSPEC int SDLCALL SDL_hid_read_timeout (SDL_hid_device * dev, unsigned char * data, size_t length, int milliseconds) extern
Read an Input report from a HID device with timeout.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into.
length the number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
milliseconds timeout in milliseconds or -1 for blocking wait.
Returns
the actual number of bytes read and -1 on on failure; call SDL_GetError() for more information. If no packet was available to be read within the timeout period, this function returns 0.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_read_timeout(device->device, data, length, milliseconds);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_read_timeout.
SDL_hid_send_feature_report()
SDL_DECLSPEC int SDLCALL SDL_hid_send_feature_report (SDL_hid_device * dev, const unsigned char * data, size_t length) extern
Send a Feature report to the device.
Feature reports are sent over the Control endpoint as a Set_Report transfer. The first byte of data must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to SDL_hid_send_feature_report() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to SDL_hid_send_feature_report(): the Report ID (or 0x0, for devices which do not use numbered reports), followed by the report data (16 bytes). In this example, the length passed in would be 17.
Parameters
dev a device handle returned from SDL_hid_open().
data the data to send, including the report number as the first byte.
length the length in bytes of the data to send, including the report number.
Returns
the actual number of bytes written and -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_send_feature_report(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_send_feature_report.
SDL_hid_set_nonblocking()
SDL_DECLSPEC int SDLCALL SDL_hid_set_nonblocking (SDL_hid_device * dev, int nonblock) extern
Set the device handle to be non-blocking.
In non-blocking mode calls to SDL_hid_read() will return immediately with a value of 0 if there is no data to be read. In blocking mode, SDL_hid_read() will wait (block) until there is data to read before returning.
Nonblocking can be turned on and off at any time.
Parameters
dev a device handle returned from SDL_hid_open().
nonblock enable or not the nonblocking reads - 1 to enable nonblocking - 0 to disable nonblocking.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_set_nonblocking(device->device, nonblock);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_set_nonblocking.
SDL_hid_write()
SDL_DECLSPEC int SDLCALL SDL_hid_write (SDL_hid_device * dev, const unsigned char * data, size_t length) extern
Write an Output report to a HID device.
The first byte of data must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to SDL_hid_write() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to SDL_hid_write(), the Report ID (or 0x0, for devices with a single report), followed by the report data (16 bytes). In this example, the length passed in would be 17.
SDL_hid_write() will send the data on the first OUT endpoint, if one exists. If it does not, it will send the data through the Control Endpoint (Endpoint 0).
Parameters
dev a device handle returned from SDL_hid_open().
data the data to send, including the report number as the first byte.
length the length in bytes of the data to send.
Returns
the actual number of bytes written and -1 on on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_write(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_write.