var dir_47534c17af0c8004befc6cf3df715f4d =
[
    [ "steam", "dir_713b02d78679de1a2f59771f012c941d.html", "dir_713b02d78679de1a2f59771f012c941d" ],
    [ "SDL_hidapi_8bitdo.c", "d3/d4e/SDL__hidapi__8bitdo_8c.html", null ],
    [ "SDL_hidapi_combined.c", "dc/d5c/SDL__hidapi__combined_8c.html", null ],
    [ "SDL_hidapi_flydigi.c", "d0/dad/SDL__hidapi__flydigi_8c.html", null ],
    [ "SDL_hidapi_gamecube.c", "d1/d39/SDL__hidapi__gamecube_8c.html", null ],
    [ "SDL_hidapi_gip.c", "d9/d8e/SDL__hidapi__gip_8c.html", null ],
    [ "SDL_hidapi_lg4ff.c", "d5/d6c/SDL__hidapi__lg4ff_8c.html", null ],
    [ "SDL_hidapi_luna.c", "d7/d01/SDL__hidapi__luna_8c.html", null ],
    [ "SDL_hidapi_nintendo.h", "d4/d50/SDL__hidapi__nintendo_8h.html", "d4/d50/SDL__hidapi__nintendo_8h" ],
    [ "SDL_hidapi_ps3.c", "d0/db6/SDL__hidapi__ps3_8c.html", null ],
    [ "SDL_hidapi_ps4.c", "d4/d1c/SDL__hidapi__ps4_8c.html", null ],
    [ "SDL_hidapi_ps5.c", "d6/d3f/SDL__hidapi__ps5_8c.html", null ],
    [ "SDL_hidapi_rumble.c", "d9/d17/SDL__hidapi__rumble_8c.html", null ],
    [ "SDL_hidapi_rumble.h", "d6/d30/SDL__hidapi__rumble_8h.html", null ],
    [ "SDL_hidapi_shield.c", "d4/d22/SDL__hidapi__shield_8c.html", null ],
    [ "SDL_hidapi_sinput.c", "dd/d29/SDL__hidapi__sinput_8c.html", null ],
    [ "SDL_hidapi_stadia.c", "d9/dc9/SDL__hidapi__stadia_8c.html", null ],
    [ "SDL_hidapi_steam.c", "d8/da7/SDL__hidapi__steam_8c.html", null ],
    [ "SDL_hidapi_steam_hori.c", "de/de4/SDL__hidapi__steam__hori_8c.html", null ],
    [ "SDL_hidapi_steamdeck.c", "d2/d8c/SDL__hidapi__steamdeck_8c.html", null ],
    [ "SDL_hidapi_switch.c", "d3/d9f/SDL__hidapi__switch_8c.html", null ],
    [ "SDL_hidapi_wii.c", "d2/db2/SDL__hidapi__wii_8c.html", null ],
    [ "SDL_hidapi_xbox360.c", "d2/d46/SDL__hidapi__xbox360_8c.html", null ],
    [ "SDL_hidapi_xbox360w.c", "d3/d95/SDL__hidapi__xbox360w_8c.html", null ],
    [ "SDL_hidapi_xboxone.c", "d0/da9/SDL__hidapi__xboxone_8c.html", null ],
    [ "SDL_hidapijoystick.c", "d6/dff/SDL__hidapijoystick_8c.html", null ],
    [ "SDL_hidapijoystick_c.h", "d7/dcd/SDL__hidapijoystick__c_8h.html", "d7/dcd/SDL__hidapijoystick__c_8h" ]
];