SDL3: SDL-main/include/SDL3/SDL_locale.h File Reference
SDL_locale.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_Locale
Typedefs
typedef struct SDL_Locale SDL_Locale
Functions
SDL_DECLSPEC SDL_Locale **SDLCALL SDL_GetPreferredLocales (int *count)
Typedef Documentation
SDL_Locale
typedef struct SDL_Locale SDL_Locale
CategoryLocale
SDL locale services.
This provides a way to get a list of preferred locales (language plus country) for the user. There is exactly one function: SDL_GetPreferredLocales(), which handles all the heavy lifting, and offers documentation on all the strange ways humans might have configured their language settings. A struct to provide locale data.
Locale data is split into a spoken language, like English, and an optional country, like Canada. The language will be in ISO-639 format (so English would be "en"), and the country, if not NULL, will be an ISO-3166 country code (so Canada would be "CA").
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPreferredLocales
Function Documentation
SDL_GetPreferredLocales()
SDL_DECLSPEC SDL_Locale **SDLCALL SDL_GetPreferredLocales (int * count) extern
Report the user's preferred locale.
Returned language strings are in the format xx, where 'xx' is an ISO-639 language specifier (such as "en" for English, "de" for German, etc). Country strings are in the format YY, where "YY" is an ISO-3166 country code (such as "US" for the United States, "CA" for Canada, etc). Country might be NULL if there's no specific guidance on them (so you might get { "en", "US" } for American English, but { "en", NULL } means "English language, generically"). Language strings are never NULL, except to terminate the array.
Please note that not all of these strings are 2 characters; some are three or more.
The returned list of locales are in the order of the user's preference. For example, a German citizen that is fluent in US English and knows enough Japanese to navigate around Tokyo might have a list like: { "de", "en_US", "jp", NULL }. Someone from England might prefer British English (where "color" is spelled "colour", etc), but will settle for anything like it: { "en_GB", "en", NULL }.
This function returns NULL on error, including when the platform does not supply this information at all.
This might be a "slow" call that has to query the operating system. It's best to ask for this once and save the results. However, this list can change, usually because the user has changed a system preference outside of your program; SDL will send an SDL_EVENT_LOCALE_CHANGED event in this case, if possible, and you can call this function again to get an updated copy of preferred locales.
Parameters
count a pointer filled in with the number of locales returned, may be NULL.
Returns
a NULL terminated array of locale pointers, or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    char locbuf[128]; // enough for 21 "xx_YY," language strings.
    const char *hint = SDL_GetHint(SDL_HINT_PREFERRED_LOCALES);
    if (hint) {
        SDL_strlcpy(locbuf, hint, sizeof(locbuf));
    } else {
        SDL_zeroa(locbuf);
        SDL_SYS_GetPreferredLocales(locbuf, sizeof(locbuf));
    }
    return build_locales_from_csv_string(locbuf, count);
}
References build_locales_from_csv_string(), count, SDL_GetHint(), SDL_HINT_PREFERRED_LOCALES, SDL_strlcpy(), SDL_SYS_GetPreferredLocales(), and SDL_zeroa.