SDL3: SDL-main/src/storage/generic/SDL_genericstorage.c File Reference
SDL_genericstorage.c File Reference
#include "SDL_internal.h"
#include "../SDL_sysstorage.h"
Data Structures
struct GenericEnumerateData
Typedefs
typedef struct GenericEnumerateData GenericEnumerateData
Functions
static bool GENERIC_CloseStorage (void *userdata)
static bool GENERIC_CopyStorageFile (void *userdata, const char *oldpath, const char *newpath)
static bool GENERIC_CreateStorageDirectory (void *userdata, const char *path)
static SDL_EnumerationResult SDLCALL GENERIC_EnumerateDirectory (void *userdata, const char *dirname, const char *fname)
static bool GENERIC_EnumerateStorageDirectory (void *userdata, const char *path, SDL_EnumerateDirectoryCallback callback, void *callback_userdata)
static bool GENERIC_GetStoragePathInfo (void *userdata, const char *path, SDL_PathInfo *info)
static Uint64 GENERIC_GetStorageSpaceRemaining (void *userdata)
static char * GENERIC_INTERNAL_CreateFullPath (const char *base, const char *relative)
SDL_Storage * GENERIC_OpenFileStorage (const char *path)
static bool GENERIC_ReadStorageFile (void *userdata, const char *path, void *destination, Uint64 length)
static bool GENERIC_RemoveStoragePath (void *userdata, const char *path)
static bool GENERIC_RenameStoragePath (void *userdata, const char *oldpath, const char *newpath)
static SDL_Storage * GENERIC_Title_Create (const char *override, SDL_PropertiesID props)
static SDL_Storage * GENERIC_User_Create (const char *org, const char *app, SDL_PropertiesID props)
static bool GENERIC_WriteStorageFile (void *userdata, const char *path, const void *source, Uint64 length)
Variables
static const SDL_StorageInterface GENERIC_file_iface
static const SDL_StorageInterface GENERIC_title_iface
TitleStorageBootStrap GENERIC_titlebootstrap
static const SDL_StorageInterface GENERIC_user_iface
UserStorageBootStrap GENERIC_userbootstrap
Typedef Documentation
GenericEnumerateData
typedef struct GenericEnumerateData GenericEnumerateData
Function Documentation
GENERIC_CloseStorage()
bool GENERIC_CloseStorage (void * userdata) static
{
    SDL_free(userdata);
    return true;
}
References SDL_free().
GENERIC_CopyStorageFile()
bool GENERIC_CopyStorageFile (void * userdata, const char * oldpath, const char * newpath) static
{
    bool result = false;
    char *fulloldpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, oldpath);
    char *fullnewpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, newpath);
    if (fulloldpath && fullnewpath) {
        result = SDL_CopyFile(fulloldpath, fullnewpath);
    }
    SDL_free(fulloldpath);
    SDL_free(fullnewpath);
    return result;
}
References GENERIC_INTERNAL_CreateFullPath(), SDL_CopyFile(), and SDL_free().
GENERIC_CreateStorageDirectory()
bool GENERIC_CreateStorageDirectory (void * userdata, const char * path) static
{
    // TODO: Recursively create subdirectories with SDL_CreateDirectory
    bool result = false;
    char *fullpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, path);
    if (fullpath) {
        result = SDL_CreateDirectory(fullpath);
        SDL_free(fullpath);
    }
    return result;
}
References GENERIC_INTERNAL_CreateFullPath(), SDL_CreateDirectory(), and SDL_free().
GENERIC_EnumerateDirectory()
SDL_EnumerationResult SDLCALL GENERIC_EnumerateDirectory (void * userdata, const char * dirname, const char * fname) static
{
    // SDL_EnumerateDirectory will return the full path, so for Storage we
    // can take the base directory and add its length to the dirname string,
    // effectively trimming the root without having to strdup anything.
    const GenericEnumerateData *wrap_data = (GenericEnumerateData *)userdata;
    dirname += wrap_data->base_len;  // skip the base, just return the part inside of the Storage.
    #ifdef SDL_PLATFORM_WINDOWS
    char *dirnamecpy = NULL;
    const size_t slen = SDL_strlen(dirname);
    if (slen && (dirname[slen - 1] == '\\')) {
        dirnamecpy = SDL_strdup(dirname);
        if (!dirnamecpy) {
            return SDL_ENUM_FAILURE;
        }
        dirnamecpy[slen - 1] = '/';  // storage layer always uses '/' path separators.
        dirname = dirnamecpy;
    }
    const SDL_EnumerationResult retval = wrap_data->real_callback(wrap_data->real_userdata, dirname, fname);
    SDL_free(dirnamecpy);
    return retval;
    #else
    return wrap_data->real_callback(wrap_data->real_userdata, dirname, fname);
    #endif
}
References GenericEnumerateData::base_len, NULL, GenericEnumerateData::real_callback, GenericEnumerateData::real_userdata, SDL_ENUM_FAILURE, SDL_free(), SDL_strdup(), SDL_strlen(), and SDLCALL.
Referenced by GENERIC_EnumerateStorageDirectory().
GENERIC_EnumerateStorageDirectory()
bool GENERIC_EnumerateStorageDirectory (void * userdata, const char * path, SDL_EnumerateDirectoryCallback callback, void * callback_userdata) static
{
    bool result = false;
    GenericEnumerateData wrap_data;
    char *fullpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, path);
    if (fullpath) {
        wrap_data.base_len = SDL_strlen((char *)userdata);
        wrap_data.real_callback = callback;
        wrap_data.real_userdata = callback_userdata;
        result = SDL_EnumerateDirectory(fullpath, GENERIC_EnumerateDirectory, &wrap_data);
        SDL_free(fullpath);
    }
    return result;
}
References GenericEnumerateData::base_len, GENERIC_EnumerateDirectory(), GENERIC_INTERNAL_CreateFullPath(), GenericEnumerateData::real_callback, GenericEnumerateData::real_userdata, SDL_EnumerateDirectory(), SDL_free(), and SDL_strlen().
GENERIC_GetStoragePathInfo()
bool GENERIC_GetStoragePathInfo (void * userdata, const char * path, SDL_PathInfo * info) static
{
    bool result = false;
    char *fullpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, path);
    if (fullpath) {
        result = SDL_GetPathInfo(fullpath, info);
        SDL_free(fullpath);
    }
    return result;
}
References GENERIC_INTERNAL_CreateFullPath(), SDL_free(), and SDL_GetPathInfo().
GENERIC_GetStorageSpaceRemaining()
Uint64 GENERIC_GetStorageSpaceRemaining (void * userdata) static
{
    // TODO: There's totally a way to query a folder root's quota...
    return SDL_MAX_UINT64;
}
References SDL_MAX_UINT64.
GENERIC_INTERNAL_CreateFullPath()
char * GENERIC_INTERNAL_CreateFullPath (const char * base, const char * relative) static
{
    char *result = NULL;
    SDL_asprintf(&result, "%s%s", base ? base : "", relative);
    return result;
}
References NULL, and SDL_asprintf().
Referenced by GENERIC_CopyStorageFile(), GENERIC_CreateStorageDirectory(), GENERIC_EnumerateStorageDirectory(), GENERIC_GetStoragePathInfo(), GENERIC_ReadStorageFile(), GENERIC_RemoveStoragePath(), GENERIC_RenameStoragePath(), and GENERIC_WriteStorageFile().
GENERIC_OpenFileStorage()
SDL_Storage * GENERIC_OpenFileStorage (const char * path)
{
    SDL_Storage *result;
    size_t len = 0;
    char *basepath = NULL;
    if (path) {
        len += SDL_strlen(path);
    }
    if (len > 0) {
        #ifdef SDL_PLATFORM_WINDOWS
        const bool appended_separator = (path[len-1] == '/') || (path[len-1] == '\\');
        #else
        const bool appended_separator = (path[len-1] == '/');
        #endif
        if (appended_separator) {
            basepath = SDL_strdup(path);
            if (!basepath) {
                return NULL;
            }
        } else {
            if (SDL_asprintf(&basepath, "%s/", path) < 0) {
                return NULL;
            }
        }
    }
    result = SDL_OpenStorage(&GENERIC_file_iface, basepath);
    if (result == NULL) {
        SDL_free(basepath);
    }
    return result;
}
References GENERIC_file_iface, NULL, SDL_asprintf(), SDL_free(), SDL_OpenStorage(), SDL_strdup(), and SDL_strlen().
Referenced by SDL_OpenFileStorage().
GENERIC_ReadStorageFile()
bool GENERIC_ReadStorageFile (void * userdata, const char * path, void * destination, Uint64 length) static
{
    bool result = false;
    if (length > SDL_SIZE_MAX) {
        return SDL_SetError("Read size exceeds SDL_SIZE_MAX");
    }
    char *fullpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, path);
    if (fullpath) {
        SDL_IOStream *stream = SDL_IOFromFile(fullpath, "rb");
        if (stream) {
            // FIXME: Should SDL_ReadIO use u64 now...?
            if (SDL_ReadIO(stream, destination, (size_t)length) == length) {
                result = true;
            } else {
                SDL_SetError("File length did not exactly match the destination length");
            }
            SDL_CloseIO(stream);
        }
        SDL_free(fullpath);
    }
    return result;
}
References GENERIC_INTERNAL_CreateFullPath(), SDL_CloseIO(), SDL_free(), SDL_IOFromFile(), SDL_ReadIO(), SDL_SetError(), and SDL_SIZE_MAX.
GENERIC_RemoveStoragePath()
bool GENERIC_RemoveStoragePath (void * userdata, const char * path) static
{
    bool result = false;
    char *fullpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, path);
    if (fullpath) {
        result = SDL_RemovePath(fullpath);
        SDL_free(fullpath);
    }
    return result;
}
References GENERIC_INTERNAL_CreateFullPath(), SDL_free(), and SDL_RemovePath().
GENERIC_RenameStoragePath()
bool GENERIC_RenameStoragePath (void * userdata, const char * oldpath, const char * newpath) static
{
    bool result = false;
    char *fulloldpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, oldpath);
    char *fullnewpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, newpath);
    if (fulloldpath && fullnewpath) {
        result = SDL_RenamePath(fulloldpath, fullnewpath);
    }
    SDL_free(fulloldpath);
    SDL_free(fullnewpath);
    return result;
}
References GENERIC_INTERNAL_CreateFullPath(), SDL_free(), and SDL_RenamePath().
GENERIC_Title_Create()
SDL_Storage * GENERIC_Title_Create (const char * override, SDL_PropertiesID props) static
{
    SDL_Storage *result = NULL;
    char *basepath = NULL;
    if (override != NULL) {
        // make sure override has a path separator at the end. If you're not on Windows and used '\\', that's on you.
        const size_t slen = SDL_strlen(override);
        const bool need_sep = (!slen || ((override[slen-1] != '/') && (override[slen-1] != '\\')));
        if (SDL_asprintf(&basepath, "%s%s", override, need_sep ? "/" : "") == -1) {
            return NULL;
        }
    } else {
        const char *base = SDL_GetBasePath();
        basepath = base ? SDL_strdup(base) : NULL;
    }
    if (basepath != NULL) {
        result = SDL_OpenStorage(&GENERIC_title_iface, basepath);
        if (result == NULL) {
            SDL_free(basepath);  // otherwise CloseStorage will free it.
        }
    }
    return result;
}
References GENERIC_title_iface, NULL, SDL_asprintf(), SDL_free(), SDL_GetBasePath(), SDL_OpenStorage(), SDL_strdup(), and SDL_strlen().
GENERIC_User_Create()
SDL_Storage * GENERIC_User_Create (const char * org, const char * app, SDL_PropertiesID props) static
{
    SDL_Storage *result;
    char *prefpath = SDL_GetPrefPath(org, app);
    if (prefpath == NULL) {
        return NULL;
    }
    result = SDL_OpenStorage(&GENERIC_user_iface, prefpath);
    if (result == NULL) {
        SDL_free(prefpath);  // otherwise CloseStorage will free it.
    }
    return result;
}
References GENERIC_user_iface, NULL, SDL_free(), SDL_GetPrefPath(), and SDL_OpenStorage().
GENERIC_WriteStorageFile()
bool GENERIC_WriteStorageFile (void * userdata, const char * path, const void * source, Uint64 length) static
{
    // TODO: Recursively create subdirectories with SDL_CreateDirectory
    bool result = false;
    if (length > SDL_SIZE_MAX) {
        return SDL_SetError("Write size exceeds SDL_SIZE_MAX");
    }
    char *fullpath = GENERIC_INTERNAL_CreateFullPath((char *)userdata, path);
    if (fullpath) {
        SDL_IOStream *stream = SDL_IOFromFile(fullpath, "wb");
        if (stream) {
            // FIXME: Should SDL_WriteIO use u64 now...?
            if (SDL_WriteIO(stream, source, (size_t)length) == length) {
                result = true;
            } else {
                SDL_SetError("Resulting file length did not exactly match the source length");
            }
            SDL_CloseIO(stream);
        }
        SDL_free(fullpath);
    }
    return result;
}
References GENERIC_INTERNAL_CreateFullPath(), SDL_CloseIO(), SDL_free(), SDL_IOFromFile(), SDL_SetError(), SDL_SIZE_MAX, and SDL_WriteIO().
Variable Documentation
GENERIC_file_iface
const SDL_StorageInterface GENERIC_file_iface static
Initial value:
= {
    sizeof(SDL_StorageInterface),
    GENERIC_CloseStorage,
    NULL,
    GENERIC_EnumerateStorageDirectory,
    GENERIC_GetStoragePathInfo,
    GENERIC_ReadStorageFile,
    GENERIC_WriteStorageFile,
    GENERIC_CreateStorageDirectory,
    GENERIC_RemoveStoragePath,
    GENERIC_RenameStoragePath,
    GENERIC_CopyStorageFile,
    GENERIC_GetStorageSpaceRemaining
}
{
    sizeof(SDL_StorageInterface),
    GENERIC_CloseStorage,
    NULL,   // ready
    GENERIC_EnumerateStorageDirectory,
    GENERIC_GetStoragePathInfo,
    GENERIC_ReadStorageFile,
    GENERIC_WriteStorageFile,
    GENERIC_CreateStorageDirectory,
    GENERIC_RemoveStoragePath,
    GENERIC_RenameStoragePath,
    GENERIC_CopyStorageFile,
    GENERIC_GetStorageSpaceRemaining
};
Referenced by GENERIC_OpenFileStorage().
GENERIC_title_iface
const SDL_StorageInterface GENERIC_title_iface static
Initial value:
= {
    sizeof(SDL_StorageInterface),
    GENERIC_CloseStorage,
    NULL,
    GENERIC_EnumerateStorageDirectory,
    GENERIC_GetStoragePathInfo,
    GENERIC_ReadStorageFile,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
}
{
    sizeof(SDL_StorageInterface),
    GENERIC_CloseStorage,
    NULL,   // ready
    GENERIC_EnumerateStorageDirectory,
    GENERIC_GetStoragePathInfo,
    GENERIC_ReadStorageFile,
    NULL,   // write_file
    NULL,   // mkdir
    NULL,   // remove
    NULL,   // rename
    NULL,   // copy
    NULL    // space_remaining
};
Referenced by GENERIC_Title_Create().
GENERIC_titlebootstrap
TitleStorageBootStrap GENERIC_titlebootstrap
Initial value:
= {
    "generic",
    "SDL generic title storage driver",
    GENERIC_Title_Create
}
{
    "generic",
    "SDL generic title storage driver",
    GENERIC_Title_Create
};
GENERIC_user_iface
const SDL_StorageInterface GENERIC_user_iface static
Initial value:
= {
    sizeof(SDL_StorageInterface),
    GENERIC_CloseStorage,
    NULL,
    GENERIC_EnumerateStorageDirectory,
    GENERIC_GetStoragePathInfo,
    GENERIC_ReadStorageFile,
    GENERIC_WriteStorageFile,
    GENERIC_CreateStorageDirectory,
    GENERIC_RemoveStoragePath,
    GENERIC_RenameStoragePath,
    GENERIC_CopyStorageFile,
    GENERIC_GetStorageSpaceRemaining
}
{
    sizeof(SDL_StorageInterface),
    GENERIC_CloseStorage,
    NULL,   // ready
    GENERIC_EnumerateStorageDirectory,
    GENERIC_GetStoragePathInfo,
    GENERIC_ReadStorageFile,
    GENERIC_WriteStorageFile,
    GENERIC_CreateStorageDirectory,
    GENERIC_RemoveStoragePath,
    GENERIC_RenameStoragePath,
    GENERIC_CopyStorageFile,
    GENERIC_GetStorageSpaceRemaining
};
Referenced by GENERIC_User_Create().
GENERIC_userbootstrap
UserStorageBootStrap GENERIC_userbootstrap
Initial value:
= {
    "generic",
    "SDL generic user storage driver",
    GENERIC_User_Create
}
{
    "generic",
    "SDL generic user storage driver",
    GENERIC_User_Create
};