SDL3: SDL-main/src/render/SDL_sysrender.h File Reference
SDL_sysrender.h File Reference
#include "SDL_internal.h"
#include "../video/SDL_surface_c.h"
#include "SDL_yuv_sw_c.h"
Data Structures
struct SDL_DRect
struct SDL_GPURenderState
struct SDL_GPURenderStateUniformBuffer
struct SDL_RenderCommand
struct SDL_RenderDriver
struct SDL_Renderer
struct SDL_RenderViewState
struct SDL_Texture
struct SDL_VertexSolid
Macros
#define RENDER_SAMPLER_COUNT (((1 << 0) | (1 << 1) | (1 << 2)) + 1)
#define RENDER_SAMPLER_HASHKEY(scale_mode, address_u, address_v)
Typedefs
typedef struct SDL_DRect SDL_DRect
typedef struct SDL_GPURenderStateUniformBuffer SDL_GPURenderStateUniformBuffer
typedef struct SDL_RenderCommand SDL_RenderCommand
typedef struct SDL_RenderDriver SDL_RenderDriver
typedef struct SDL_RenderViewState SDL_RenderViewState
typedef struct SDL_VertexSolid SDL_VertexSolid
Enumerations
enum SDL_RenderCommandType {
SDL_RENDERCMD_NO_OP , SDL_RENDERCMD_SETVIEWPORT , SDL_RENDERCMD_SETCLIPRECT , SDL_RENDERCMD_SETDRAWCOLOR ,
SDL_RENDERCMD_CLEAR , SDL_RENDERCMD_DRAW_POINTS , SDL_RENDERCMD_DRAW_LINES , SDL_RENDERCMD_FILL_RECTS ,
SDL_RENDERCMD_COPY , SDL_RENDERCMD_COPY_EX , SDL_RENDERCMD_GEOMETRY
}
enum SDL_RenderLineMethod { SDL_RENDERLINEMETHOD_POINTS , SDL_RENDERLINEMETHOD_LINES , SDL_RENDERLINEMETHOD_GEOMETRY }
Functions
bool SDL_AddSupportedTextureFormat (SDL_Renderer *renderer, SDL_PixelFormat format)
void * SDL_AllocateRenderVertices (SDL_Renderer *renderer, size_t numbytes, size_t alignment, size_t *offset)
void SDL_ConvertFromLinear (SDL_FColor *color)
void SDL_ConvertToLinear (SDL_FColor *color)
void SDL_DestroyRendererWithoutFreeing (SDL_Renderer *renderer)
SDL_BlendOperation SDL_GetBlendModeAlphaOperation (SDL_BlendMode blendMode)
SDL_BlendOperation SDL_GetBlendModeColorOperation (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeDstAlphaFactor (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeDstColorFactor (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeSrcAlphaFactor (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeSrcColorFactor (SDL_BlendMode blendMode)
void SDL_QuitRender (void)
bool SDL_RenderingLinearSpace (SDL_Renderer *renderer)
void SDL_SetupRendererColorspace (SDL_Renderer *renderer, SDL_PropertiesID props)
Variables
SDL_RenderDriver D3D11_RenderDriver
SDL_RenderDriver D3D12_RenderDriver
SDL_RenderDriver D3D_RenderDriver
SDL_RenderDriver GL_RenderDriver
SDL_RenderDriver GLES2_RenderDriver
SDL_RenderDriver GPU_RenderDriver
SDL_RenderDriver METAL_RenderDriver
SDL_RenderDriver NGAGE_RenderDriver
SDL_RenderDriver PS2_RenderDriver
SDL_RenderDriver PSP_RenderDriver
SDL_RenderDriver SW_RenderDriver
SDL_RenderDriver VITA_GXM_RenderDriver
SDL_RenderDriver VULKAN_RenderDriver
Macro Definition Documentation
RENDER_SAMPLER_COUNT
#define RENDER_SAMPLER_COUNT (((1 << 0) | (1 << 1) | (1 << 2)) + 1)
RENDER_SAMPLER_HASHKEY
#define RENDER_SAMPLER_HASHKEY (scale_mode, address_u, address_v)
Value:
    (((scale_mode == SDL_SCALEMODE_NEAREST) << 0) |                 \
     ((address_u == SDL_TEXTURE_ADDRESS_WRAP) << 1) |               \
     ((address_v == SDL_TEXTURE_ADDRESS_WRAP) << 2))
#define RENDER_SAMPLER_HASHKEY(scale_mode, address_u, address_v)    \
    (((scale_mode == SDL_SCALEMODE_NEAREST) << 0) |                 \
     ((address_u == SDL_TEXTURE_ADDRESS_WRAP) << 1) |               \
     ((address_v == SDL_TEXTURE_ADDRESS_WRAP) << 2))
Typedef Documentation
SDL_DRect
typedef struct SDL_DRect SDL_DRect
A rectangle, with the origin at the upper left (double precision).
SDL_GPURenderStateUniformBuffer
typedef struct SDL_GPURenderStateUniformBuffer SDL_GPURenderStateUniformBuffer
SDL_RenderCommand
typedef struct SDL_RenderCommand SDL_RenderCommand
SDL_RenderDriver
typedef struct SDL_RenderDriver SDL_RenderDriver
SDL_RenderViewState
typedef struct SDL_RenderViewState SDL_RenderViewState
SDL_VertexSolid
typedef struct SDL_VertexSolid SDL_VertexSolid
Enumeration Type Documentation
SDL_RenderCommandType
enum SDL_RenderCommandType
Enumerator
SDL_RENDERCMD_NO_OP
SDL_RENDERCMD_SETVIEWPORT
SDL_RENDERCMD_SETCLIPRECT
SDL_RENDERCMD_SETDRAWCOLOR
SDL_RENDERCMD_CLEAR
SDL_RENDERCMD_DRAW_POINTS
SDL_RENDERCMD_DRAW_LINES
SDL_RENDERCMD_FILL_RECTS
SDL_RENDERCMD_COPY
SDL_RENDERCMD_COPY_EX
SDL_RENDERCMD_GEOMETRY
{
    SDL_RENDERCMD_NO_OP,
    SDL_RENDERCMD_SETVIEWPORT,
    SDL_RENDERCMD_SETCLIPRECT,
    SDL_RENDERCMD_SETDRAWCOLOR,
    SDL_RENDERCMD_CLEAR,
    SDL_RENDERCMD_DRAW_POINTS,
    SDL_RENDERCMD_DRAW_LINES,
    SDL_RENDERCMD_FILL_RECTS,
    SDL_RENDERCMD_COPY,
    SDL_RENDERCMD_COPY_EX,
    SDL_RENDERCMD_GEOMETRY
} SDL_RenderCommandType;
SDL_RenderLineMethod
enum SDL_RenderLineMethod
Enumerator
SDL_RENDERLINEMETHOD_POINTS
SDL_RENDERLINEMETHOD_LINES
SDL_RENDERLINEMETHOD_GEOMETRY
{
    SDL_RENDERLINEMETHOD_POINTS,
    SDL_RENDERLINEMETHOD_LINES,
    SDL_RENDERLINEMETHOD_GEOMETRY,
} SDL_RenderLineMethod;
Function Documentation
SDL_AddSupportedTextureFormat()
bool SDL_AddSupportedTextureFormat (SDL_Renderer * renderer, SDL_PixelFormat format) extern
{
    SDL_PixelFormat *texture_formats = (SDL_PixelFormat *)SDL_realloc((void *)renderer->texture_formats, (renderer->num_texture_formats + 2) * sizeof(SDL_PixelFormat));
    if (!texture_formats) {
        return false;
    }
    texture_formats[renderer->num_texture_formats++] = format;
    texture_formats[renderer->num_texture_formats] = SDL_PIXELFORMAT_UNKNOWN;
    renderer->texture_formats = texture_formats;
    SDL_SetPointerProperty(SDL_GetRendererProperties(renderer), SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER, texture_formats);
    return true;
}
References SDL_Renderer::num_texture_formats, SDL_GetRendererProperties(), SDL_PIXELFORMAT_UNKNOWN, SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER, SDL_realloc(), SDL_SetPointerProperty(), and SDL_Renderer::texture_formats.
SDL_AllocateRenderVertices()
void * SDL_AllocateRenderVertices (SDL_Renderer * renderer, size_t numbytes, size_t alignment, size_t * offset) extern
{
    const size_t needed = renderer->vertex_data_used + numbytes + alignment;
    const size_t current_offset = renderer->vertex_data_used;
    const size_t aligner = (alignment && ((current_offset & (alignment - 1)) != 0)) ? (alignment - (current_offset & (alignment - 1))) : 0;
    const size_t aligned = current_offset + aligner;
    if (renderer->vertex_data_allocation < needed) {
        const size_t current_allocation = renderer->vertex_data ? renderer->vertex_data_allocation : 1024;
        size_t newsize = current_allocation * 2;
        void *ptr;
        while (newsize < needed) {
            newsize *= 2;
        }
        ptr = SDL_realloc(renderer->vertex_data, newsize);
        if (!ptr) {
            return NULL;
        }
        renderer->vertex_data = ptr;
        renderer->vertex_data_allocation = newsize;
    }
    if (offset) {
        *offset = aligned;
    }
    renderer->vertex_data_used += aligner + numbytes;
    return ((Uint8 *)renderer->vertex_data) + aligned;
}
References NULL, SDL_realloc(), SDL_Renderer::vertex_data, SDL_Renderer::vertex_data_allocation, and SDL_Renderer::vertex_data_used.
SDL_ConvertFromLinear()
void SDL_ConvertFromLinear (SDL_FColor * color) extern
{
    color->r = SDL_sRGBfromLinear(color->r);
    color->g = SDL_sRGBfromLinear(color->g);
    color->b = SDL_sRGBfromLinear(color->b);
}
References SDL_FColor::b, SDL_FColor::g, SDL_FColor::r, and SDL_sRGBfromLinear().
SDL_ConvertToLinear()
void SDL_ConvertToLinear (SDL_FColor * color) extern
{
    color->r = SDL_sRGBtoLinear(color->r);
    color->g = SDL_sRGBtoLinear(color->g);
    color->b = SDL_sRGBtoLinear(color->b);
}
References SDL_FColor::b, SDL_FColor::g, SDL_FColor::r, and SDL_sRGBtoLinear().
SDL_DestroyRendererWithoutFreeing()
void SDL_DestroyRendererWithoutFreeing (SDL_Renderer * renderer) extern
{
    SDL_assert(renderer != NULL);
    SDL_assert(!renderer->destroyed);
    renderer->destroyed = true;
    SDL_RemoveWindowEventWatch(SDL_WINDOW_EVENT_WATCH_NORMAL, SDL_RendererEventWatch, renderer);
    if (renderer->window) {
        SDL_PropertiesID props = SDL_GetWindowProperties(renderer->window);
        if (SDL_GetPointerProperty(props, SDL_PROP_WINDOW_RENDERER_POINTER, NULL) == renderer) {
            SDL_ClearProperty(props, SDL_PROP_WINDOW_RENDERER_POINTER);
        }
        SDL_RemoveWindowRenderer(renderer->window, renderer);
    }
    if (renderer->software) {
        // Make sure all drawing to a surface is complete
        FlushRenderCommands(renderer);
    }
    SDL_DiscardAllCommands(renderer);
    if (renderer->debug_char_texture_atlas) {
        SDL_DestroyTexture(renderer->debug_char_texture_atlas);
        renderer->debug_char_texture_atlas = NULL;
    }
    // Free existing textures for this renderer
    while (renderer->textures) {
        SDL_Texture *tex = renderer->textures;
        SDL_DestroyTextureInternal(renderer->textures, true /* is_destroying */);
        SDL_assert(tex != renderer->textures); // satisfy static analysis.
    }
    // Clean up renderer-specific resources
    if (renderer->DestroyRenderer) {
        renderer->DestroyRenderer(renderer);
    }
    if (renderer->target_mutex) {
        SDL_DestroyMutex(renderer->target_mutex);
        renderer->target_mutex = NULL;
    }
    if (renderer->vertex_data) {
        SDL_free(renderer->vertex_data);
        renderer->vertex_data = NULL;
    }
    if (renderer->texture_formats) {
        SDL_free(renderer->texture_formats);
        renderer->texture_formats = NULL;
    }
    if (renderer->props) {
        SDL_DestroyProperties(renderer->props);
        renderer->props = 0;
    }
}
References SDL_Renderer::debug_char_texture_atlas, SDL_Renderer::destroyed, SDL_Renderer::DestroyRenderer, FlushRenderCommands(), NULL, SDL_Renderer::props, SDL_assert, SDL_ClearProperty(), SDL_DestroyMutex(), SDL_DestroyProperties(), SDL_DestroyTexture(), SDL_DestroyTextureInternal(), SDL_DiscardAllCommands(), SDL_free(), SDL_GetPointerProperty(), SDL_GetWindowProperties(), SDL_PROP_WINDOW_RENDERER_POINTER, SDL_RemoveWindowEventWatch(), SDL_RemoveWindowRenderer(), SDL_RendererEventWatch(), SDL_WINDOW_EVENT_WATCH_NORMAL, SDL_Renderer::software, SDL_Renderer::target_mutex, SDL_Renderer::texture_formats, SDL_Renderer::textures, SDL_Renderer::vertex_data, and SDL_Renderer::window.
Referenced by SDL_CreateRendererWithProperties(), SDL_DestroyRenderer(), and SDL_DestroyWindow().
SDL_GetBlendModeAlphaOperation()
SDL_BlendOperation SDL_GetBlendModeAlphaOperation (SDL_BlendMode blendMode) extern
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendOperation)(((Uint32)blendMode >> 16) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeColorOperation()
SDL_BlendOperation SDL_GetBlendModeColorOperation (SDL_BlendMode blendMode) extern
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendOperation)(((Uint32)blendMode >> 0) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeDstAlphaFactor()
SDL_BlendFactor SDL_GetBlendModeDstAlphaFactor (SDL_BlendMode blendMode) extern
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 24) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeDstColorFactor()
SDL_BlendFactor SDL_GetBlendModeDstColorFactor (SDL_BlendMode blendMode) extern
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 8) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeSrcAlphaFactor()
SDL_BlendFactor SDL_GetBlendModeSrcAlphaFactor (SDL_BlendMode blendMode) extern
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 20) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeSrcColorFactor()
SDL_BlendFactor SDL_GetBlendModeSrcColorFactor (SDL_BlendMode blendMode) extern
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 4) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_QuitRender()
void SDL_QuitRender (void) extern
{
    while (SDL_renderers) {
        SDL_DestroyRenderer(SDL_renderers);
    }
}
References SDL_DestroyRenderer(), and SDL_renderers.
Referenced by SDL_QuitSubSystem().
SDL_RenderingLinearSpace()
bool SDL_RenderingLinearSpace (SDL_Renderer * renderer) extern
{
    SDL_Colorspace colorspace;
    if (renderer->target) {
        colorspace = renderer->target->colorspace;
    } else {
        colorspace = renderer->output_colorspace;
    }
    if (colorspace == SDL_COLORSPACE_SRGB_LINEAR) {
        return true;
    }
    return false;
}
References SDL_Texture::colorspace, SDL_Renderer::output_colorspace, SDL_COLORSPACE_SRGB_LINEAR, and SDL_Renderer::target.
SDL_SetupRendererColorspace()
void SDL_SetupRendererColorspace (SDL_Renderer * renderer, SDL_PropertiesID props) extern
{
    renderer->output_colorspace = (SDL_Colorspace)SDL_GetNumberProperty(props, SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER, SDL_COLORSPACE_SRGB);
}
References SDL_Renderer::output_colorspace, SDL_COLORSPACE_SRGB, SDL_GetNumberProperty(), and SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER.
Variable Documentation
D3D11_RenderDriver
SDL_RenderDriver D3D11_RenderDriver extern
D3D12_RenderDriver
SDL_RenderDriver D3D12_RenderDriver extern
D3D_RenderDriver
SDL_RenderDriver D3D_RenderDriver extern
GL_RenderDriver
SDL_RenderDriver GL_RenderDriver extern
GLES2_RenderDriver
SDL_RenderDriver GLES2_RenderDriver extern
GPU_RenderDriver
SDL_RenderDriver GPU_RenderDriver extern
METAL_RenderDriver
SDL_RenderDriver METAL_RenderDriver extern
NGAGE_RenderDriver
SDL_RenderDriver NGAGE_RenderDriver extern
PS2_RenderDriver
SDL_RenderDriver PS2_RenderDriver extern
PSP_RenderDriver
SDL_RenderDriver PSP_RenderDriver extern
SW_RenderDriver
SDL_RenderDriver SW_RenderDriver extern
VITA_GXM_RenderDriver
SDL_RenderDriver VITA_GXM_RenderDriver extern
VULKAN_RenderDriver
SDL_RenderDriver VULKAN_RenderDriver extern