SDL3: SDL-main/src/events/SDL_clipboardevents_c.h File Reference
SDL_clipboardevents_c.h File Reference
#include "SDL_internal.h"
Functions
void SDL_SendClipboardUpdate (bool owner, char **mime_types, size_t num_mime_types)
Function Documentation
SDL_SendClipboardUpdate()
void SDL_SendClipboardUpdate (bool owner, char ** mime_types, size_t num_mime_types) extern
{
    if (!owner) {
        SDL_CancelClipboardData(0);
        SDL_SaveClipboardMimeTypes((const char **)mime_types, num_mime_types);
    }
    if (SDL_EventEnabled(SDL_EVENT_CLIPBOARD_UPDATE)) {
        SDL_Event event;
        event.type = SDL_EVENT_CLIPBOARD_UPDATE;
        SDL_ClipboardEvent *cevent = &event.clipboard;
        cevent->timestamp = 0;
        cevent->owner = owner;
        cevent->mime_types = (const char **)mime_types;
        cevent->num_mime_types = (Uint32)num_mime_types;
        SDL_PushEvent(&event);
    }
}
References SDL_ClipboardEvent::mime_types, SDL_ClipboardEvent::num_mime_types, SDL_ClipboardEvent::owner, SDL_CancelClipboardData(), SDL_EVENT_CLIPBOARD_UPDATE, SDL_EventEnabled(), SDL_PushEvent(), SDL_SaveClipboardMimeTypes(), and SDL_ClipboardEvent::timestamp.
Referenced by SDL_SetClipboardData(), and SDL_SetPrimarySelectionText().