SDL3: SDL-main/src/audio/ps2/SDL_ps2audio.c File Reference
SDL_ps2audio.c File Reference
#include "SDL_internal.h"
#include "../SDL_sysaudio.h"
#include "SDL_ps2audio.h"
#include <kernel.h>
#include <audsrv.h>
#include <ps2_audio_driver.h>
Functions
static void PS2AUDIO_CloseDevice (SDL_AudioDevice *device)
static void PS2AUDIO_Deinitialize (void)
static Uint8 * PS2AUDIO_GetDeviceBuf (SDL_AudioDevice *device, int *buffer_size)
static bool PS2AUDIO_Init (SDL_AudioDriverImpl *impl)
static bool PS2AUDIO_OpenDevice (SDL_AudioDevice *device)
static bool PS2AUDIO_PlayDevice (SDL_AudioDevice *device, const Uint8 *buffer, int buflen)
static void PS2AUDIO_ThreadInit (SDL_AudioDevice *device)
static bool PS2AUDIO_WaitDevice (SDL_AudioDevice *device)
Variables
AudioBootStrap PS2AUDIO_bootstrap
Function Documentation
PS2AUDIO_CloseDevice()
void PS2AUDIO_CloseDevice (SDL_AudioDevice * device) static
{
    if (device->hidden) {
        if (device->hidden->channel >= 0) {
            audsrv_stop_audio();
            device->hidden->channel = -1;
        }
        if (device->hidden->rawbuf) {
            SDL_aligned_free(device->hidden->rawbuf);
            device->hidden->rawbuf = NULL;
        }
        SDL_free(device->hidden);
        device->hidden = NULL;
    }
}
References SDL_PrivateAudioData::channel, SDL_AudioDevice::hidden, NULL, SDL_PrivateAudioData::rawbuf, SDL_aligned_free(), and SDL_free().
Referenced by PS2AUDIO_Init().
PS2AUDIO_Deinitialize()
void PS2AUDIO_Deinitialize (void) static
{
    deinit_audio_driver();
}
Referenced by PS2AUDIO_Init().
PS2AUDIO_GetDeviceBuf()
Uint8 * PS2AUDIO_GetDeviceBuf (SDL_AudioDevice * device, int * buffer_size) static
{
    Uint8 *buffer = device->hidden->mixbufs[device->hidden->next_buffer];
    device->hidden->next_buffer = (device->hidden->next_buffer + 1) % NUM_BUFFERS;
    return buffer;
}
References SDL_AudioDevice::hidden, SDL_PrivateAudioData::mixbufs, SDL_PrivateAudioData::next_buffer, and NUM_BUFFERS.
Referenced by PS2AUDIO_Init().
PS2AUDIO_Init()
bool PS2AUDIO_Init (SDL_AudioDriverImpl * impl) static
{
    if (init_audio_driver() < 0) {
        return false;
    }
    impl->OpenDevice = PS2AUDIO_OpenDevice;
    impl->PlayDevice = PS2AUDIO_PlayDevice;
    impl->WaitDevice = PS2AUDIO_WaitDevice;
    impl->GetDeviceBuf = PS2AUDIO_GetDeviceBuf;
    impl->CloseDevice = PS2AUDIO_CloseDevice;
    impl->ThreadInit = PS2AUDIO_ThreadInit;
    impl->Deinitialize = PS2AUDIO_Deinitialize;
    impl->OnlyHasDefaultPlaybackDevice = true;
    return true; // this audio target is available.
}
References SDL_AudioDriverImpl::CloseDevice, SDL_AudioDriverImpl::Deinitialize, SDL_AudioDriverImpl::GetDeviceBuf, SDL_AudioDriverImpl::OnlyHasDefaultPlaybackDevice, SDL_AudioDriverImpl::OpenDevice, SDL_AudioDriverImpl::PlayDevice, PS2AUDIO_CloseDevice(), PS2AUDIO_Deinitialize(), PS2AUDIO_GetDeviceBuf(), PS2AUDIO_OpenDevice(), PS2AUDIO_PlayDevice(), PS2AUDIO_ThreadInit(), PS2AUDIO_WaitDevice(), SDL_AudioDriverImpl::ThreadInit, and SDL_AudioDriverImpl::WaitDevice.
PS2AUDIO_OpenDevice()
bool PS2AUDIO_OpenDevice (SDL_AudioDevice * device) static
{
    device->hidden = (struct SDL_PrivateAudioData *) SDL_calloc(1, sizeof(*device->hidden));
    if (!device->hidden) {
        return false;
    }
    // These are the native supported audio PS2 configs
    switch (device->spec.freq) {
    case 11025:
    case 12000:
    case 22050:
    case 24000:
    case 32000:
    case 44100:
    case 48000:
        break;  // acceptable value, keep it
    default:
        device->spec.freq = 48000;
        break;
    }
    device->sample_frames = 512;
    device->spec.channels = device->spec.channels == 1 ? 1 : 2;
    device->spec.format = device->spec.format == SDL_AUDIO_S8 ? SDL_AUDIO_S8 : SDL_AUDIO_S16;
    struct audsrv_fmt_t format;
    format.bits = device->spec.format == SDL_AUDIO_S8 ? 8 : 16;
    format.freq = device->spec.freq;
    format.channels = device->spec.channels;
    device->hidden->channel = audsrv_set_format(&format);
    audsrv_set_volume(MAX_VOLUME);
    if (device->hidden->channel < 0) {
        return SDL_SetError("Couldn't reserve hardware channel");
    }
    // Update the fragment size as size in bytes.
    SDL_UpdatedAudioDeviceFormat(device);
    /* Allocate the mixing buffer.  Its size and starting address must
       be a multiple of 64 bytes.  Our sample count is already a multiple of
       64, so spec->size should be a multiple of 64 as well. */
    const int mixlen = device->buffer_size * NUM_BUFFERS;
    device->hidden->rawbuf = (Uint8 *)SDL_aligned_alloc(64, mixlen);
    if (!device->hidden->rawbuf) {
        return SDL_SetError("Couldn't allocate mixing buffer");
    }
    SDL_memset(device->hidden->rawbuf, device->silence_value, mixlen);
    for (int i = 0; i < NUM_BUFFERS; i++) {
        device->hidden->mixbufs[i] = &device->hidden->rawbuf[i * device->buffer_size];
    }
    return true;
}
References SDL_AudioDevice::buffer_size, SDL_PrivateAudioData::channel, SDL_AudioSpec::channels, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::hidden, SDL_PrivateAudioData::mixbufs, NUM_BUFFERS, SDL_PrivateAudioData::rawbuf, SDL_AudioDevice::sample_frames, SDL_aligned_alloc(), SDL_AUDIO_S16, SDL_AUDIO_S8, SDL_calloc(), SDL_memset, SDL_SetError(), SDL_UpdatedAudioDeviceFormat(), SDL_AudioDevice::silence_value, and SDL_AudioDevice::spec.
Referenced by PS2AUDIO_Init().
PS2AUDIO_PlayDevice()
bool PS2AUDIO_PlayDevice (SDL_AudioDevice * device, const Uint8 * buffer, int buflen) static
{
    // this returns number of bytes accepted or a negative error. We assume anything other than buflen is a fatal error.
    return (audsrv_play_audio((char *)buffer, buflen) == buflen);
}
Referenced by PS2AUDIO_Init().
PS2AUDIO_ThreadInit()
void PS2AUDIO_ThreadInit (SDL_AudioDevice * device) static
{
    /* Increase the priority of this audio thread by 1 to put it
       ahead of other SDL threads. */
    const int32_t thid = GetThreadId();
    ee_thread_status_t status;
    if (ReferThreadStatus(thid, &status) == 0) {
        ChangeThreadPriority(thid, status.current_priority - 1);
    }
}
Referenced by PS2AUDIO_Init().
PS2AUDIO_WaitDevice()
bool PS2AUDIO_WaitDevice (SDL_AudioDevice * device) static
{
    audsrv_wait_audio(device->buffer_size);
    return true;
}
References SDL_AudioDevice::buffer_size.
Referenced by PS2AUDIO_Init().
Variable Documentation
PS2AUDIO_bootstrap
AudioBootStrap PS2AUDIO_bootstrap
Initial value:
= {
    "ps2", "PS2 audio driver", PS2AUDIO_Init, false, false
}
{
    "ps2", "PS2 audio driver", PS2AUDIO_Init, false, false
};