SDL3: SDL-main/src/SDL_hashtable.c File Reference
SDL_hashtable.c File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_HashItem
struct SDL_HashTable
Macros
#define MAX_HASHITEM_SIZEOF 32u
#define MAX_HASHTABLE_SIZE (0x80000000u / (MAX_HASHITEM_SIZEOF))
Typedefs
typedef struct SDL_HashItem SDL_HashItem
Functions
static SDL_INLINE Uint32 calc_hash (const SDL_HashTable *table, const void *key)
static Uint32 CalculateHashBucketsFromEstimate (int estimated_capacity)
static void delete_item (SDL_HashTable *ht, SDL_HashItem *item)
static void destroy_all (SDL_HashTable *table)
static SDL_HashItem * find_first_item (const SDL_HashTable *ht, const void *key, Uint32 hash)
static SDL_HashItem * find_item (const SDL_HashTable *ht, const void *key, Uint32 hash, Uint32 *i, Uint32 *probe_len)
static SDL_INLINE Uint32 get_probe_length (Uint32 zero_idx, Uint32 actual_idx, Uint32 num_buckets)
static SDL_INLINE Uint32 hash_string_djbxor (const char *str, size_t len)
static SDL_HashItem * insert_item (SDL_HashItem *item_to_insert, SDL_HashItem *table, Uint32 hash_mask, Uint32 *max_probe_len_ptr)
static bool maybe_resize (SDL_HashTable *ht)
static bool resize (SDL_HashTable *ht, Uint32 new_size)
void SDL_ClearHashTable (SDL_HashTable *table)
SDL_COMPILE_TIME_ASSERT (SDL_HashID_KeySize, sizeof(Uint32)<=sizeof(const void *))
SDL_COMPILE_TIME_ASSERT (sizeof_SDL_HashItem, sizeof(SDL_HashItem)<=32u)
SDL_HashTable * SDL_CreateHashTable (int estimated_capacity, bool threadsafe, SDL_HashCallback hash, SDL_HashKeyMatchCallback keymatch, SDL_HashDestroyCallback destroy, void *userdata)
void SDL_DestroyHashKey (void *unused, const void *key, const void *value)
void SDL_DestroyHashKeyAndValue (void *unused, const void *key, const void *value)
void SDL_DestroyHashTable (SDL_HashTable *table)
void SDL_DestroyHashValue (void *unused, const void *key, const void *value)
bool SDL_FindInHashTable (const SDL_HashTable *table, const void *key, const void **value)
Uint32 SDL_HashID (void *unused, const void *key)
Uint32 SDL_HashPointer (void *unused, const void *key)
Uint32 SDL_HashString (void *unused, const void *key)
bool SDL_HashTableEmpty (SDL_HashTable *table)
bool SDL_InsertIntoHashTable (SDL_HashTable *table, const void *key, const void *value, bool replace)
bool SDL_IterateHashTable (const SDL_HashTable *table, SDL_HashTableIterateCallback callback, void *userdata)
bool SDL_KeyMatchID (void *unused, const void *a, const void *b)
bool SDL_KeyMatchPointer (void *unused, const void *a, const void *b)
bool SDL_KeyMatchString (void *unused, const void *a, const void *b)
bool SDL_RemoveFromHashTable (SDL_HashTable *table, const void *key)
Macro Definition Documentation
MAX_HASHITEM_SIZEOF
#define MAX_HASHITEM_SIZEOF 32u
Referenced by SDL_COMPILE_TIME_ASSERT().
MAX_HASHTABLE_SIZE
#define MAX_HASHTABLE_SIZE (0x80000000u / (MAX_HASHITEM_SIZEOF))
Referenced by CalculateHashBucketsFromEstimate(), and maybe_resize().
Typedef Documentation
SDL_HashItem
typedef struct SDL_HashItem SDL_HashItem
Function Documentation
calc_hash()
SDL_INLINE Uint32 calc_hash (const SDL_HashTable * table, const void * key) static
{
    const Uint32 BitMixer = 0x9E3779B1u;
    return table->hash(table->userdata, key) * BitMixer;
}
References SDL_HashTable::hash, SDL_INLINE, and SDL_HashTable::userdata.
Referenced by SDL_FindInHashTable(), SDL_InsertIntoHashTable(), and SDL_RemoveFromHashTable().
CalculateHashBucketsFromEstimate()
Uint32 CalculateHashBucketsFromEstimate (int estimated_capacity) static
{
    if (estimated_capacity <= 0) {
        return 4;  // start small, grow as necessary.
    }
    const Uint32 estimated32 = (Uint32) estimated_capacity;
    Uint32 buckets = ((Uint32) 1) << SDL_MostSignificantBitIndex32(estimated32);
    if (!SDL_HasExactlyOneBitSet32(estimated32)) {
        buckets <<= 1;  // need next power of two up to fit overflow capacity bits.
    }
    return SDL_min(buckets, MAX_HASHTABLE_SIZE);
}
References MAX_HASHTABLE_SIZE, SDL_HasExactlyOneBitSet32(), SDL_min, and SDL_MostSignificantBitIndex32().
Referenced by SDL_CreateHashTable().
delete_item()
void delete_item (SDL_HashTable * ht, SDL_HashItem * item) static
{
    const Uint32 hash_mask = ht->hash_mask;
    SDL_HashItem *table = ht->table;
    if (ht->destroy) {
        ht->destroy(ht->userdata, item->key, item->value);
    }
    SDL_assert(ht->num_occupied_slots > 0);
    ht->num_occupied_slots--;
    Uint32 idx = (Uint32)(item - ht->table);
    while (true) {
        idx = (idx + 1) & hash_mask;
        SDL_HashItem *next_item = table + idx;
        if (next_item->probe_len < 1) {
            SDL_zerop(item);
            return;
        }
        *item = *next_item;
        item->probe_len -= 1;
        SDL_assert(item->probe_len < ht->max_probe_len);
        item = next_item;
    }
}
References SDL_HashTable::destroy, SDL_HashTable::hash_mask, SDL_HashItem::key, SDL_HashTable::max_probe_len, SDL_HashTable::num_occupied_slots, SDL_HashItem::probe_len, SDL_assert, SDL_zerop, SDL_HashTable::table, SDL_HashTable::userdata, and SDL_HashItem::value.
Referenced by SDL_InsertIntoHashTable(), and SDL_RemoveFromHashTable().
destroy_all()
void destroy_all (SDL_HashTable * table) static
{
    SDL_HashDestroyCallback destroy = table->destroy;
    if (destroy) {
        void *userdata = table->userdata;
        SDL_HashItem *end = table->table + (table->hash_mask + 1);
        for (SDL_HashItem *i = table->table; i < end; ++i) {
            if (i->live) {
                i->live = false;
                destroy(userdata, i->key, i->value);
            }
        }
    }
}
References SDL_HashTable::destroy, SDL_HashTable::hash_mask, SDL_HashTable::table, and SDL_HashTable::userdata.
Referenced by SDL_ClearHashTable(), and SDL_DestroyHashTable().
find_first_item()
SDL_HashItem * find_first_item (const SDL_HashTable * ht, const void * key, Uint32 hash) static
{
    Uint32 i = hash & ht->hash_mask;
    Uint32 probe_len = 0;
    return find_item(ht, key, hash, &i, &probe_len);
}
References find_item(), and SDL_HashTable::hash_mask.
Referenced by SDL_FindInHashTable(), SDL_InsertIntoHashTable(), and SDL_RemoveFromHashTable().
find_item()
SDL_HashItem * find_item (const SDL_HashTable * ht, const void * key, Uint32 hash, Uint32 * i, Uint32 * probe_len) static
{
    Uint32 hash_mask = ht->hash_mask;
    Uint32 max_probe_len = ht->max_probe_len;
    SDL_HashItem *table = ht->table;
    while (true) {
        SDL_HashItem *item = table + *i;
        Uint32 item_hash = item->hash;
        if (!item->live) {
            return NULL;
        }
        if (item_hash == hash && ht->keymatch(ht->userdata, item->key, key)) {
            return item;
        }
        Uint32 item_probe_len = item->probe_len;
        SDL_assert(item_probe_len == get_probe_length(item_hash & hash_mask, (Uint32)(item - table), hash_mask + 1));
        if (*probe_len > item_probe_len) {
            return NULL;
        }
        if (++*probe_len > max_probe_len) {
            return NULL;
        }
        *i = (*i + 1) & hash_mask;
    }
}
References get_probe_length(), SDL_HashItem::hash, SDL_HashTable::hash_mask, SDL_HashItem::key, SDL_HashTable::keymatch, SDL_HashItem::live, SDL_HashTable::max_probe_len, NULL, SDL_HashItem::probe_len, SDL_assert, SDL_HashTable::table, and SDL_HashTable::userdata.
Referenced by find_first_item().
get_probe_length()
SDL_INLINE Uint32 get_probe_length (Uint32 zero_idx, Uint32 actual_idx, Uint32 num_buckets) static
{
    // returns the probe sequence length from zero_idx to actual_idx
    if (actual_idx < zero_idx) {
        return num_buckets - zero_idx + actual_idx;
    }
    return actual_idx - zero_idx;
}
References SDL_INLINE.
Referenced by find_item(), and insert_item().
hash_string_djbxor()
SDL_INLINE Uint32 hash_string_djbxor (const char * str, size_t len) static
{
    Uint32 hash = 5381;
    while (len--) {
        hash = ((hash << 5) + hash) ^ *(str++);
    }
    return hash;
}
References SDL_INLINE.
Referenced by SDL_HashString().
insert_item()
SDL_HashItem * insert_item (SDL_HashItem * item_to_insert, SDL_HashItem * table, Uint32 hash_mask, Uint32 * max_probe_len_ptr) static
{
    const Uint32 num_buckets = hash_mask + 1;
    Uint32 idx = item_to_insert->hash & hash_mask;
    SDL_HashItem *target = NULL;
    SDL_HashItem temp_item;
    while (true) {
        SDL_HashItem *candidate = table + idx;
        if (!candidate->live) {
            // Found an empty slot. Put it here and we're done.
            *candidate = *item_to_insert;
            if (target == NULL) {
                target = candidate;
            }
            const Uint32 probe_len = get_probe_length(candidate->hash & hash_mask, idx, num_buckets);
            candidate->probe_len = probe_len;
            if (*max_probe_len_ptr < probe_len) {
                *max_probe_len_ptr = probe_len;
            }
            break;
        }
        const Uint32 candidate_probe_len = candidate->probe_len;
        SDL_assert(candidate_probe_len == get_probe_length(candidate->hash & hash_mask, idx, num_buckets));
        const Uint32 new_probe_len = get_probe_length(item_to_insert->hash & hash_mask, idx, num_buckets);
        if (candidate_probe_len < new_probe_len) {
            // Robin Hood hashing: the item at idx has a better probe length than our item would at this position.
            // Evict it and put our item in its place, then continue looking for a new spot for the displaced item.
            // This algorithm significantly reduces clustering in the table, making lookups take very few probes.
            temp_item = *candidate;
            *candidate = *item_to_insert;
            if (target == NULL) {
                target = candidate;
            }
            *item_to_insert = temp_item;
            SDL_assert(new_probe_len == get_probe_length(candidate->hash & hash_mask, idx, num_buckets));
            candidate->probe_len = new_probe_len;
            if (*max_probe_len_ptr < new_probe_len) {
                *max_probe_len_ptr = new_probe_len;
            }
        }
        idx = (idx + 1) & hash_mask;
    }
    return target;
}
References get_probe_length(), SDL_HashItem::hash, SDL_HashItem::live, NULL, SDL_HashItem::probe_len, and SDL_assert.
Referenced by resize(), and SDL_InsertIntoHashTable().
maybe_resize()
bool maybe_resize (SDL_HashTable * ht) static
{
    const Uint32 capacity = ht->hash_mask + 1;
    if (capacity >= MAX_HASHTABLE_SIZE) {
        return false;
    }
    const Uint32 max_load_factor = 217; // range: 0-255; 217 is roughly 85%
    const Uint32 resize_threshold = (Uint32)((max_load_factor * (Uint64)capacity) >> 8);
    if (ht->num_occupied_slots > resize_threshold) {
        return resize(ht, capacity * 2);
    }
    return true;
}
References SDL_HashTable::hash_mask, MAX_HASHTABLE_SIZE, SDL_HashTable::num_occupied_slots, and resize().
Referenced by SDL_InsertIntoHashTable().
resize()
bool resize (SDL_HashTable * ht, Uint32 new_size) static
{
    const Uint32 new_hash_mask = new_size - 1;
    SDL_HashItem *new_table = SDL_calloc(new_size, sizeof(*new_table));
    if (!new_table) {
        return false;
    }
    SDL_HashItem *old_table = ht->table;
    const Uint32 old_size = ht->hash_mask + 1;
    ht->max_probe_len = 0;
    ht->hash_mask = new_hash_mask;
    ht->table = new_table;
    for (Uint32 i = 0; i < old_size; ++i) {
        SDL_HashItem *item = old_table + i;
        if (item->live) {
            insert_item(item, new_table, new_hash_mask, &ht->max_probe_len);
        }
    }
    SDL_free(old_table);
    return true;
}
References SDL_HashTable::hash_mask, insert_item(), SDL_HashItem::live, SDL_HashTable::max_probe_len, SDL_calloc(), SDL_free(), and SDL_HashTable::table.
Referenced by maybe_resize().
SDL_ClearHashTable()
void SDL_ClearHashTable (SDL_HashTable * table)
Remove all items in a hash table.
This will call the hash table's SDL_HashDestroyCallback for each item in the table, removing all inserted items.
When this function returns, the hash table will be empty.
Parameters
table the hash table to clear.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (table) {
        SDL_LockRWLockForWriting(table->lock);
        {
            destroy_all(table);
            SDL_memset(table->table, 0, sizeof(*table->table) * (table->hash_mask + 1));
            table->num_occupied_slots = 0;
        }
        SDL_UnlockRWLock(table->lock);
    }
}
References destroy_all(), SDL_HashTable::hash_mask, SDL_HashTable::lock, SDL_HashTable::num_occupied_slots, SDL_LockRWLockForWriting(), SDL_memset, SDL_UnlockRWLock(), and SDL_HashTable::table.
SDL_COMPILE_TIME_ASSERT() [1/2]
SDL_COMPILE_TIME_ASSERT (SDL_HashID_KeySize , sizeof(Uint32)<=sizeof(const void *))
SDL_COMPILE_TIME_ASSERT() [2/2]
SDL_COMPILE_TIME_ASSERT (sizeof_SDL_HashItem , sizeof(SDL_HashItem)<= 32u)
References MAX_HASHITEM_SIZEOF.
SDL_CreateHashTable()
SDL_HashTable * SDL_CreateHashTable (int estimated_capacity, bool threadsafe, SDL_HashCallback hash, SDL_HashKeyMatchCallback keymatch, SDL_HashDestroyCallback destroy, void * userdata)
Create a new hash table.
To deal with different datatypes and needs of the caller, hash tables require several callbacks that deal with some specifics: how to hash a key, how to compare a key for equality, and how to clean up keys and values. SDL provides a few generic functions that can be used for these callbacks:
SDL_HashString and SDL_KeyMatchString for C strings.
SDL_HashPointer and SDL_KeyMatchPointer for generic pointers.
SDL_HashID and SDL_KeyMatchID for generic (possibly small) integers.
Oftentimes, these are all you need for any hash table, but depending on your dataset, custom implementations might make more sense.
You can specify an estimate of the number of items expected to be stored in the table, which can help make the table run more efficiently. The table will preallocate resources to accommodate this number of items, which is most useful if you intend to fill the table with a lot of data right after creating it. Otherwise, it might make more sense to specify the minimum you expect the table to hold and let it grow as necessary from there. This number is only a hint, and the table will be able to handle any amount of data–as long as the system doesn't run out of resources–so a perfect answer is not required. A value of 0 signifies no guess at all, and the table will start small and reallocate as necessary; often this is the correct thing to do.
!!! FIXME: add note about threadsafe here. And update threadsafety tags. !!! FIXME: note that threadsafe tables can't be recursively locked, so !!! FIXME: you can't use destroy callbacks that might end up relocking.
Note that SDL provides a higher-level option built on its hash tables: SDL_PropertiesID lets you map strings to various datatypes, and this might be easier to use. It only allows strings for keys, however. Those are created with SDL_CreateProperties().
The returned hash table should be destroyed with SDL_DestroyHashTable() when no longer needed.
Parameters
estimated_capacity the approximate maximum number of items to be held in the hash table, or 0 for no estimate.
threadsafe true to create an internal rwlock for this table.
hash the function to use to hash keys.
keymatch the function to use to compare keys.
destroy the function to use to clean up keys and values, may be NULL.
userdata a pointer that is passed to the callbacks.
Returns
a newly-created hash table, or NULL if there was an error; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_DestroyHashTable
{
    const Uint32 num_buckets = CalculateHashBucketsFromEstimate(estimated_capacity);
    SDL_HashTable *table = (SDL_HashTable *)SDL_calloc(1, sizeof(SDL_HashTable));
    if (!table) {
        return NULL;
    }
    if (threadsafe) {
        table->lock = SDL_CreateRWLock();
        if (!table->lock) {
            SDL_DestroyHashTable(table);
            return NULL;
        }
    }
    table->table = (SDL_HashItem *)SDL_calloc(num_buckets, sizeof(SDL_HashItem));
    if (!table->table) {
        SDL_DestroyHashTable(table);
        return NULL;
    }
    table->hash_mask = num_buckets - 1;
    table->userdata = userdata;
    table->hash = hash;
    table->keymatch = keymatch;
    table->destroy = destroy;
    return table;
}
References CalculateHashBucketsFromEstimate(), SDL_HashTable::destroy, SDL_HashTable::hash, SDL_HashTable::hash_mask, SDL_HashTable::keymatch, SDL_HashTable::lock, NULL, SDL_calloc(), SDL_CreateRWLock(), SDL_DestroyHashTable(), SDL_HashTable::table, and SDL_HashTable::userdata.
Referenced by SDL_CameraInit(), SDL_CreateEnvironment(), SDL_CreateKeymap(), SDL_CreateProperties(), SDL_GetPersistentString(), SDL_GetPixelFormatDetails(), SDL_InitAudio(), SDL_InitProperties(), SDL_IsGamepad(), SDL_MapSurface(), and SDL_SetObjectValid().
SDL_DestroyHashKey()
void SDL_DestroyHashKey (void * unused, const void * key, const void * value)
Free just the value pointer of a hash table item.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of data to be used with the hash table.
This literally calls SDL_free(key); and leaves value alone.
Parameters
unused this parameter is ignored.
key the key to be destroyed.
value the value to be destroyed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)value;
    (void)unused;
    SDL_free((void *)key);
}
References SDL_free(), and void().
Referenced by SDL_CreateEnvironment().
SDL_DestroyHashKeyAndValue()
void SDL_DestroyHashKeyAndValue (void * unused, const void * key, const void * value)
Free both the key and value pointers of a hash table item.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of data to be used with the hash table.
This literally calls SDL_free(key); and SDL_free(value);.
Parameters
unused this parameter is ignored.
key the key to be destroyed.
value the value to be destroyed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    SDL_free((void *)key);
    SDL_free((void *)value);
}
References SDL_free(), and void().
SDL_DestroyHashTable()
void SDL_DestroyHashTable (SDL_HashTable * table)
Destroy a hash table.
This will call the hash table's SDL_HashDestroyCallback for each item in the table, removing all inserted items, before deallocating the table itself.
The table becomes invalid once this function is called, and no other thread should be accessing this table once this function has started.
Parameters
table the hash table to destroy.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (table) {
        destroy_all(table);
        if (table->lock) {
            SDL_DestroyRWLock(table->lock);
        }
        SDL_free(table->table);
        SDL_free(table);
    }
}
References destroy_all(), SDL_HashTable::lock, SDL_DestroyRWLock(), SDL_free(), and SDL_HashTable::table.
Referenced by SDL_CameraInit(), SDL_CreateHashTable(), SDL_DestroyEnvironment(), SDL_DestroyKeymap(), SDL_FreePersistentStrings(), SDL_FreeProperties(), SDL_InitAudio(), SDL_InvalidateMap(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitGamepadMappings(), SDL_QuitPixelFormatDetails(), SDL_QuitProperties(), and SDL_SetObjectsInvalid().
SDL_DestroyHashValue()
void SDL_DestroyHashValue (void * unused, const void * key, const void * value)
Free just the value pointer of a hash table item.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of data to be used with the hash table.
This literally calls SDL_free(value); and leaves key alone.
Parameters
unused this parameter is ignored.
key the key to be destroyed.
value the value to be destroyed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)key;
    (void)unused;
    SDL_free((void *)value);
}
References SDL_free(), and void().
Referenced by SDL_GetPersistentString(), and SDL_GetPixelFormatDetails().
SDL_FindInHashTable()
bool SDL_FindInHashTable (const SDL_HashTable * table, const void * key, const void ** value)
Look up an item in a hash table.
On return, the value associated with key is stored to *value. If the key does not exist in the table, *value will be set to NULL.
It is legal for value to be NULL, to not retrieve the key's value. In this case, the return value is still useful for reporting if the key exists in the table at all.
Parameters
table the hash table to search.
key the key to search for in the table.
value the found value will be stored here. Can be NULL.
Returns
true if key exists in the table, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_InsertIntoHashTable
{
    if (!table) {
        if (value) {
            *value = NULL;
        }
        return SDL_InvalidParamError("table");
    }
    SDL_LockRWLockForReading(table->lock);
    bool result = false;
    const Uint32 hash = calc_hash(table, key);
    SDL_HashItem *i = find_first_item(table, key, hash);
    if (i) {
        if (value) {
            *value = i->value;
        }
        result = true;
    }
    SDL_UnlockRWLock(table->lock);
    return result;
}
References calc_hash(), find_first_item(), SDL_HashTable::lock, NULL, SDL_InvalidParamError, SDL_LockRWLockForReading(), SDL_UnlockRWLock(), and SDL_HashItem::value.
Referenced by ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalCamera(), SDL_CopyProperties(), SDL_CreateProperties(), SDL_DestroyProperties(), SDL_EnumerateProperties(), SDL_GetAudioDeviceName(), SDL_GetBooleanProperty(), SDL_GetEnvironmentVariable(), SDL_GetFloatProperty(), SDL_GetKeymapKeycode(), SDL_GetKeymapScancode(), SDL_GetNumberProperty(), SDL_GetPersistentString(), SDL_GetPixelFormatDetails(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetStringProperty(), SDL_IsGamepad(), SDL_LockProperties(), SDL_LookupRGBAColor(), SDL_ObjectValid(), SDL_PrivateSetProperty(), SDL_SetEnvironmentVariable(), SDL_SetKeymapEntry(), SDL_UnlockProperties(), and SDL_UnsetEnvironmentVariable().
SDL_HashID()
Uint32 SDL_HashID (void * unused, const void * key)
Generate a hash from an integer ID.
The key is intended to a unique integer, possibly within a small range.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Note that the implementation may change in the future; do not expect the results to be stable vs future SDL releases. Use this in a hash table in the current process and don't store them to disk for the future.
Parameters
unused this parameter is ignored.
key the key to hash as a generic pointer.
Returns
a 32-bit hash of the key.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return (Uint32)(uintptr_t)key;
}
References void().
Referenced by SDL_CameraInit(), SDL_CreateKeymap(), SDL_GetPixelFormatDetails(), SDL_InitProperties(), SDL_IsGamepad(), and SDL_MapSurface().
SDL_HashPointer()
Uint32 SDL_HashPointer (void * unused, const void * key)
Generate a hash from a generic pointer.
The key is intended to be a unique pointer to any datatype.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Note that the implementation may change in the future; do not expect the results to be stable vs future SDL releases. Use this in a hash table in the current process and don't store them to disk for the future.
Parameters
unused this parameter is ignored.
key the key to hash as a generic pointer.
Returns
a 32-bit hash of the key.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return SDL_murmur3_32(&key, sizeof(key), 0);
}
References SDL_murmur3_32(), and void().
SDL_HashString()
Uint32 SDL_HashString (void * unused, const void * key)
Generate a hash from a C string.
The key is intended to be a NULL-terminated string, in UTF-8 format.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Note that the implementation may change in the future; do not expect the results to be stable vs future SDL releases. Use this in a hash table in the current process and don't store them to disk for the future.
Parameters
unused this parameter is ignored.
key the key to hash as a generic pointer.
Returns
a 32-bit hash of the key.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    const char *str = (const char *)key;
    return hash_string_djbxor(str, SDL_strlen(str));
}
References hash_string_djbxor(), SDL_strlen(), and void().
Referenced by SDL_CreateEnvironment(), SDL_CreateProperties(), and SDL_GetPersistentString().
SDL_HashTableEmpty()
bool SDL_HashTableEmpty (SDL_HashTable * table)
Check if any items are currently stored in a hash table.
If there are no items stored (the table is completely empty), this will return true.
Parameters
table the hash table to check.
Returns
true if the table is completely empty, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_ClearHashTable
{
    if (!table) {
        return SDL_InvalidParamError("table");
    }
    SDL_LockRWLockForReading(table->lock);
    const bool retval = (table->num_occupied_slots == 0);
    SDL_UnlockRWLock(table->lock);
    return retval;
}
References SDL_HashTable::lock, SDL_HashTable::num_occupied_slots, SDL_InvalidParamError, SDL_LockRWLockForReading(), and SDL_UnlockRWLock().
Referenced by SDL_SetObjectsInvalid().
SDL_InsertIntoHashTable()
bool SDL_InsertIntoHashTable (SDL_HashTable * table, const void * key, const void * value, bool replace)
Add an item to a hash table.
All keys in the table must be unique. If attempting to insert a key that already exists in the hash table, what will be done depends on the replace value:
If replace is false, this function will return false without modifying the table.
If replace is true, SDL will remove the previous item first, so the new value is the only one associated with that key. This will call the hash table's SDL_HashDestroyCallback for the previous item.
Parameters
table the hash table to insert into.
key the key of the new item to insert.
value the value of the new item to insert.
replace true if a duplicate key should replace the previous value.
Returns
true if the new item was inserted, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (!table) {
        return SDL_InvalidParamError("table");
    }
    bool result = false;
    SDL_LockRWLockForWriting(table->lock);
    const Uint32 hash = calc_hash(table, key);
    SDL_HashItem *item = find_first_item(table, key, hash);
    bool do_insert = true;
    if (item) {
        if (replace) {
            delete_item(table, item);
        } else {
            SDL_SetError("key already exists and replace is disabled");
            do_insert = false;
        }
    }
    if (do_insert) {
        SDL_HashItem new_item;
        new_item.key = key;
        new_item.value = value;
        new_item.hash = hash;
        new_item.live = true;
        new_item.probe_len = 0;
        table->num_occupied_slots++;
        if (!maybe_resize(table)) {
            table->num_occupied_slots--;
        } else {
            // This never returns NULL
            insert_item(&new_item, table->table, table->hash_mask, &table->max_probe_len);
            result = true;
        }
    }
    SDL_UnlockRWLock(table->lock);
    return result;
}
References calc_hash(), delete_item(), find_first_item(), SDL_HashItem::hash, SDL_HashTable::hash_mask, insert_item(), SDL_HashItem::key, SDL_HashItem::live, SDL_HashTable::lock, SDL_HashTable::max_probe_len, maybe_resize(), SDL_HashTable::num_occupied_slots, SDL_HashItem::probe_len, SDL_InvalidParamError, SDL_LockRWLockForWriting(), SDL_SetError(), SDL_UnlockRWLock(), SDL_HashTable::table, and SDL_HashItem::value.
Referenced by CopyOneProperty(), CreatePhysicalAudioDevice(), PopMappingChangeTracking(), SDL_AddCamera(), SDL_CreateEnvironment(), SDL_CreateProperties(), SDL_GetPersistentString(), SDL_GetPixelFormatDetails(), SDL_IsGamepad(), SDL_LookupRGBAColor(), SDL_OpenAudioDevice(), SDL_PrivateSetProperty(), SDL_SetEnvironmentVariable(), SDL_SetKeymapEntry(), and SDL_SetObjectValid().
SDL_IterateHashTable()
bool SDL_IterateHashTable (const SDL_HashTable * table, SDL_HashTableIterateCallback callback, void * userdata)
Iterate all key/value pairs in a hash table.
This function will call callback once for each key/value pair in the table, until either all pairs have been presented to the callback, or the callback has returned false to signal it is done.
There is no guarantee what order results will be returned in.
Parameters
table the hash table to iterate.
callback the function pointer to call for each value.
userdata a pointer that is passed to callback.
Returns
true if iteration happened, false if not (bogus parameter, etc.).
Since
This function is available since SDL 3.4.0.
{
    if (!table) {
        return SDL_InvalidParamError("table");
    } else if (!callback) {
        return SDL_InvalidParamError("callback");
    }
    SDL_LockRWLockForReading(table->lock);
    SDL_HashItem *end = table->table + (table->hash_mask + 1);
    Uint32 num_iterated = 0;
    for (SDL_HashItem *item = table->table; item < end; item++) {
        if (item->live) {
            if (!callback(userdata, table, item->key, item->value)) {
                break;  // callback requested iteration stop.
            } else if (++num_iterated >= table->num_occupied_slots) {
                break;  // we can drop out early because we've seen all the live items.
            }
        }
    }
    SDL_UnlockRWLock(table->lock);
    return true;
}
References SDL_HashTable::hash_mask, SDL_HashTable::lock, SDL_HashTable::num_occupied_slots, SDL_InvalidParamError, SDL_LockRWLockForReading(), SDL_UnlockRWLock(), and SDL_HashTable::table.
Referenced by GetAudioDevices(), GetFirstAddedAudioDevice(), SDL_CopyProperties(), SDL_EnumerateProperties(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetCameras(), SDL_GetEnvironmentVariables(), SDL_GetObjects(), SDL_QuitAudio(), SDL_QuitProperties(), and SDL_SetObjectsInvalid().
SDL_KeyMatchID()
bool SDL_KeyMatchID (void * unused, const void * a, const void * b)
Compare two integer IDs as hash table keys.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Parameters
unused this parameter is ignored.
a the first ID to compare.
b the second ID to compare.
Returns
true if the IDs are the same, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return (a == b);
}
References void().
Referenced by SDL_CameraInit(), SDL_CreateKeymap(), SDL_GetPixelFormatDetails(), SDL_InitAudio(), SDL_InitProperties(), SDL_IsGamepad(), and SDL_MapSurface().
SDL_KeyMatchPointer()
bool SDL_KeyMatchPointer (void * unused, const void * a, const void * b)
Compare two generic pointers as hash table keys.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Parameters
unused this parameter is ignored.
a the first generic pointer to compare.
b the second generic pointer to compare.
Returns
true if the pointers are the same, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return (a == b);
}
References void().
SDL_KeyMatchString()
bool SDL_KeyMatchString (void * unused, const void * a, const void * b)
Compare two C strings as hash table keys.
Strings will be compared in a case-sensitive manner. More specifically, they'll be compared as NULL-terminated arrays of bytes.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Parameters
unused this parameter is ignored.
a the first string to compare.
b the second string to compare.
Returns
true if the strings are the same, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    const char *a_string = (const char *)a;
    const char *b_string = (const char *)b;
    (void)unused;
    if (a == b) {
        return true; // same pointer, must match.
    } else if (!a || !b) {
        return false; // one pointer is NULL (and first test shows they aren't the same pointer), must not match.
    } else if (a_string[0] != b_string[0]) {
        return false; // we know they don't match
    }
    return (SDL_strcmp(a_string, b_string) == 0); // Check against actual string contents.
}
References SDL_strcmp(), and void().
Referenced by SDL_CreateEnvironment(), SDL_CreateProperties(), and SDL_GetPersistentString().
SDL_RemoveFromHashTable()
bool SDL_RemoveFromHashTable (SDL_HashTable * table, const void * key)
Remove an item from a hash table.
If there is an item that matches key, it is removed from the table. This will call the hash table's SDL_HashDestroyCallback for the item to be removed.
Parameters
table the hash table to remove from.
key the key of the item to remove from the table.
Returns
true if a key was removed, false if the key was not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (!table) {
        return SDL_InvalidParamError("table");
    }
    SDL_LockRWLockForWriting(table->lock);
    bool result = false;
    const Uint32 hash = calc_hash(table, key);
    SDL_HashItem *item = find_first_item(table, key, hash);
    if (item) {
        delete_item(table, item);
        result = true;
    }
    SDL_UnlockRWLock(table->lock);
    return result;
}
References calc_hash(), delete_item(), find_first_item(), SDL_HashTable::lock, SDL_InvalidParamError, SDL_LockRWLockForWriting(), and SDL_UnlockRWLock().
Referenced by DestroyLogicalAudioDevice(), SDL_DestroyProperties(), SDL_PrivateSetProperty(), SDL_SetObjectValid(), SDL_UnsetEnvironmentVariable(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().