SDL3: SDL-main/src/events/SDL_keyboard.c File Reference
SDL_keyboard.c File Reference
#include "SDL_internal.h"
#include "SDL_events_c.h"
#include "SDL_keymap_c.h"
#include "../video/SDL_sysvideo.h"
Data Structures
struct SDL_Keyboard
struct SDL_KeyboardInstance
Macros
#define DEFAULT_KEYCODE_OPTIONS (KEYCODE_OPTION_FRENCH_NUMBERS | KEYCODE_OPTION_LATIN_LETTERS)
#define KEYBOARD_AUTORELEASE 0x04
#define KEYBOARD_HARDWARE 0x01
#define KEYBOARD_IGNOREMODIFIERS 0x08
#define KEYBOARD_SOURCE_MASK (KEYBOARD_HARDWARE | KEYBOARD_AUTORELEASE)
#define KEYBOARD_VIRTUAL 0x02
#define KEYCODE_OPTION_FRENCH_NUMBERS 0x02
#define KEYCODE_OPTION_HIDE_NUMPAD 0x01
#define KEYCODE_OPTION_LATIN_LETTERS 0x04
Typedefs
typedef struct SDL_Keyboard SDL_Keyboard
typedef struct SDL_KeyboardInstance SDL_KeyboardInstance
Functions
static const char *const * CreateCandidatesForEvent (char **candidates, int num_candidates)
static SDL_Scancode GetNextReservedScancode (void)
void SDL_AddKeyboard (SDL_KeyboardID keyboardID, const char *name, bool send_event)
static SDL_Keycode SDL_ConvertNumpadKeycode (SDL_Keycode keycode, bool numlock)
SDL_Keymap * SDL_GetCurrentKeymap (bool ignore_options)
SDL_Window * SDL_GetKeyboardFocus (void)
static int SDL_GetKeyboardIndex (SDL_KeyboardID keyboardID)
const char * SDL_GetKeyboardNameForID (SDL_KeyboardID instance_id)
SDL_KeyboardID * SDL_GetKeyboards (int *count)
const bool * SDL_GetKeyboardState (int *numkeys)
SDL_Keycode SDL_GetKeyFromScancode (SDL_Scancode scancode, SDL_Keymod modstate, bool key_event)
SDL_Keymod SDL_GetModState (void)
SDL_Scancode SDL_GetScancodeFromKey (SDL_Keycode key, SDL_Keymod *modstate)
bool SDL_HardwareKeyboardKeyPressed (void)
bool SDL_HasKeyboard (void)
bool SDL_InitKeyboard (void)
bool SDL_IsKeyboard (Uint16 vendor, Uint16 product, int num_keys)
static void SDLCALL SDL_KeycodeOptionsChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
void SDL_QuitKeyboard (void)
void SDL_ReleaseAutoReleaseKeys (void)
void SDL_RemoveKeyboard (SDL_KeyboardID keyboardID, bool send_event)
void SDL_ResetKeyboard (void)
void SDL_SendEditingText (const char *text, int start, int length)
void SDL_SendEditingTextCandidates (char **candidates, int num_candidates, int selected_candidate, bool horizontal)
bool SDL_SendKeyboardKey (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down)
bool SDL_SendKeyboardKeyAndKeycode (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, SDL_Keycode keycode, bool down)
bool SDL_SendKeyboardKeyAutoRelease (Uint64 timestamp, SDL_Scancode scancode)
bool SDL_SendKeyboardKeyIgnoreModifiers (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down)
static bool SDL_SendKeyboardKeyInternal (Uint64 timestamp, Uint32 flags, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down)
void SDL_SendKeyboardText (const char *text)
void SDL_SendKeyboardUnicodeKey (Uint64 timestamp, Uint32 ch)
bool SDL_SetKeyboardFocus (SDL_Window *window)
void SDL_SetKeymap (SDL_Keymap *keymap, bool send_event)
void SDL_SetModState (SDL_Keymod modstate)
void SDL_ToggleModState (SDL_Keymod modstate, bool toggle)
static void SetKeymapEntry (SDL_Scancode scancode, SDL_Keymod modstate, SDL_Keycode keycode)
Variables
static SDL_Keyboard SDL_keyboard
static int SDL_keyboard_count
static SDL_KeyboardInstance * SDL_keyboards
Macro Definition Documentation
DEFAULT_KEYCODE_OPTIONS
#define DEFAULT_KEYCODE_OPTIONS (KEYCODE_OPTION_FRENCH_NUMBERS | KEYCODE_OPTION_LATIN_LETTERS)
Referenced by SDL_KeycodeOptionsChanged().
KEYBOARD_AUTORELEASE
#define KEYBOARD_AUTORELEASE 0x04
Referenced by SDL_ReleaseAutoReleaseKeys(), SDL_SendKeyboardKeyAutoRelease(), and SDL_SendKeyboardKeyInternal().
KEYBOARD_HARDWARE
#define KEYBOARD_HARDWARE 0x01
Referenced by SDL_HardwareKeyboardKeyPressed(), SDL_SendKeyboardKey(), SDL_SendKeyboardKeyAndKeycode(), SDL_SendKeyboardKeyIgnoreModifiers(), and SDL_SendKeyboardKeyInternal().
KEYBOARD_IGNOREMODIFIERS
#define KEYBOARD_IGNOREMODIFIERS 0x08
Referenced by SDL_SendKeyboardKeyIgnoreModifiers(), and SDL_SendKeyboardKeyInternal().
KEYBOARD_SOURCE_MASK
#define KEYBOARD_SOURCE_MASK (KEYBOARD_HARDWARE | KEYBOARD_AUTORELEASE)
Referenced by SDL_SendKeyboardKeyInternal().
KEYBOARD_VIRTUAL
#define KEYBOARD_VIRTUAL 0x02
Referenced by SDL_SendKeyboardUnicodeKey().
KEYCODE_OPTION_FRENCH_NUMBERS
#define KEYCODE_OPTION_FRENCH_NUMBERS 0x02
Referenced by SDL_GetKeyFromScancode(), and SDL_KeycodeOptionsChanged().
KEYCODE_OPTION_HIDE_NUMPAD
#define KEYCODE_OPTION_HIDE_NUMPAD 0x01
Referenced by SDL_GetKeyFromScancode(), and SDL_KeycodeOptionsChanged().
KEYCODE_OPTION_LATIN_LETTERS
#define KEYCODE_OPTION_LATIN_LETTERS 0x04
Referenced by SDL_GetCurrentKeymap(), and SDL_KeycodeOptionsChanged().
Typedef Documentation
SDL_Keyboard
typedef struct SDL_Keyboard SDL_Keyboard
SDL_KeyboardInstance
typedef struct SDL_KeyboardInstance SDL_KeyboardInstance
Function Documentation
CreateCandidatesForEvent()
const char *const * CreateCandidatesForEvent (char ** candidates, int num_candidates) static
{
    const char **event_candidates;
    int i;
    char *ptr;
    size_t total_length = (num_candidates + 1) * sizeof(*event_candidates);
    for (i = 0; i < num_candidates; ++i) {
        size_t length = SDL_strlen(candidates[i]) + 1;
        total_length += length;
    }
    event_candidates = (const char **)SDL_AllocateTemporaryMemory(total_length);
    if (!event_candidates) {
        return NULL;
    }
    ptr = (char *)(event_candidates + (num_candidates + 1));
    for (i = 0; i < num_candidates; ++i) {
        size_t length = SDL_strlen(candidates[i]) + 1;
        event_candidates[i] = ptr;
        SDL_memcpy(ptr, candidates[i], length);
        ptr += length;
    }
    event_candidates[i] = NULL;
    return event_candidates;
}
References NULL, SDL_AllocateTemporaryMemory(), SDL_memcpy, and SDL_strlen().
Referenced by SDL_SendEditingTextCandidates().
GetNextReservedScancode()
SDL_Scancode GetNextReservedScancode (void) static
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->keymap) {
        keyboard->keymap = SDL_CreateKeymap(true);
    }
    return SDL_GetKeymapNextReservedScancode(keyboard->keymap);
}
References SDL_Keyboard::keymap, SDL_CreateKeymap(), SDL_GetKeymapNextReservedScancode(), and SDL_keyboard.
Referenced by SDL_SendKeyboardUnicodeKey().
SDL_AddKeyboard()
void SDL_AddKeyboard (SDL_KeyboardID keyboardID, const char * name, bool send_event)
{
    int keyboard_index = SDL_GetKeyboardIndex(keyboardID);
    if (keyboard_index >= 0) {
        // We already know about this keyboard
        return;
    }
    SDL_assert(keyboardID != 0);
    SDL_KeyboardInstance *keyboards = (SDL_KeyboardInstance *)SDL_realloc(SDL_keyboards, (SDL_keyboard_count + 1) * sizeof(*keyboards));
    if (!keyboards) {
        return;
    }
    SDL_KeyboardInstance *instance = &keyboards[SDL_keyboard_count];
    instance->instance_id = keyboardID;
    instance->name = SDL_strdup(name ? name : "");
    SDL_keyboards = keyboards;
    ++SDL_keyboard_count;
    if (send_event) {
        SDL_Event event;
        SDL_zero(event);
        event.type = SDL_EVENT_KEYBOARD_ADDED;
        event.kdevice.which = keyboardID;
        SDL_PushEvent(&event);
    }
}
References SDL_KeyboardInstance::instance_id, SDL_KeyboardInstance::name, SDL_assert, SDL_EVENT_KEYBOARD_ADDED, SDL_GetKeyboardIndex(), SDL_keyboard_count, SDL_keyboards, SDL_PushEvent(), SDL_realloc(), SDL_strdup(), and SDL_zero.
Referenced by SDL_WSCONS_Init_Keyboard(), and videoInit().
SDL_ConvertNumpadKeycode()
SDL_Keycode SDL_ConvertNumpadKeycode (SDL_Keycode keycode, bool numlock) static
{
    switch (keycode) {
    case SDLK_KP_DIVIDE:
        return SDLK_SLASH;
    case SDLK_KP_MULTIPLY:
        return SDLK_ASTERISK;
    case SDLK_KP_MINUS:
        return SDLK_MINUS;
    case SDLK_KP_PLUS:
        return SDLK_PLUS;
    case SDLK_KP_ENTER:
        return SDLK_RETURN;
    case SDLK_KP_1:
        return numlock ? SDLK_1 : SDLK_END;
    case SDLK_KP_2:
        return numlock ? SDLK_2 : SDLK_DOWN;
    case SDLK_KP_3:
        return numlock ? SDLK_3 : SDLK_PAGEDOWN;
    case SDLK_KP_4:
        return numlock ? SDLK_4 : SDLK_LEFT;
    case SDLK_KP_5:
        return numlock ? SDLK_5 : SDLK_CLEAR;
    case SDLK_KP_6:
        return numlock ? SDLK_6 : SDLK_RIGHT;
    case SDLK_KP_7:
        return numlock ? SDLK_7 : SDLK_HOME;
    case SDLK_KP_8:
        return numlock ? SDLK_8 : SDLK_UP;
    case SDLK_KP_9:
        return numlock ? SDLK_9 : SDLK_PAGEUP;
    case SDLK_KP_0:
        return numlock ? SDLK_0 : SDLK_INSERT;
    case SDLK_KP_PERIOD:
        return numlock ? SDLK_PERIOD : SDLK_DELETE;
    case SDLK_KP_EQUALS:
        return SDLK_EQUALS;
    case SDLK_KP_COMMA:
        return SDLK_COMMA;
    case SDLK_KP_EQUALSAS400:
        return SDLK_EQUALS;
    case SDLK_KP_LEFTPAREN:
        return SDLK_LEFTPAREN;
    case SDLK_KP_RIGHTPAREN:
        return SDLK_RIGHTPAREN;
    case SDLK_KP_LEFTBRACE:
        return SDLK_LEFTBRACE;
    case SDLK_KP_RIGHTBRACE:
        return SDLK_RIGHTBRACE;
    case SDLK_KP_TAB:
        return SDLK_TAB;
    case SDLK_KP_BACKSPACE:
        return SDLK_BACKSPACE;
    case SDLK_KP_A:
        return SDLK_A;
    case SDLK_KP_B:
        return SDLK_B;
    case SDLK_KP_C:
        return SDLK_C;
    case SDLK_KP_D:
        return SDLK_D;
    case SDLK_KP_E:
        return SDLK_E;
    case SDLK_KP_F:
        return SDLK_F;
    case SDLK_KP_PERCENT:
        return SDLK_PERCENT;
    case SDLK_KP_LESS:
        return SDLK_LESS;
    case SDLK_KP_GREATER:
        return SDLK_GREATER;
    case SDLK_KP_AMPERSAND:
        return SDLK_AMPERSAND;
    case SDLK_KP_COLON:
        return SDLK_COLON;
    case SDLK_KP_HASH:
        return SDLK_HASH;
    case SDLK_KP_SPACE:
        return SDLK_SPACE;
    case SDLK_KP_AT:
        return SDLK_AT;
    case SDLK_KP_EXCLAM:
        return SDLK_EXCLAIM;
    case SDLK_KP_PLUSMINUS:
        return SDLK_PLUSMINUS;
    default:
        return keycode;
    }
}
References keycode, SDLK_0, SDLK_1, SDLK_2, SDLK_3, SDLK_4, SDLK_5, SDLK_6, SDLK_7, SDLK_8, SDLK_9, SDLK_A, SDLK_AMPERSAND, SDLK_ASTERISK, SDLK_AT, SDLK_B, SDLK_BACKSPACE, SDLK_C, SDLK_CLEAR, SDLK_COLON, SDLK_COMMA, SDLK_D, SDLK_DELETE, SDLK_DOWN, SDLK_E, SDLK_END, SDLK_EQUALS, SDLK_EXCLAIM, SDLK_F, SDLK_GREATER, SDLK_HASH, SDLK_HOME, SDLK_INSERT, SDLK_KP_0, SDLK_KP_1, SDLK_KP_2, SDLK_KP_3, SDLK_KP_4, SDLK_KP_5, SDLK_KP_6, SDLK_KP_7, SDLK_KP_8, SDLK_KP_9, SDLK_KP_A, SDLK_KP_AMPERSAND, SDLK_KP_AT, SDLK_KP_B, SDLK_KP_BACKSPACE, SDLK_KP_C, SDLK_KP_COLON, SDLK_KP_COMMA, SDLK_KP_D, SDLK_KP_DIVIDE, SDLK_KP_E, SDLK_KP_ENTER, SDLK_KP_EQUALS, SDLK_KP_EQUALSAS400, SDLK_KP_EXCLAM, SDLK_KP_F, SDLK_KP_GREATER, SDLK_KP_HASH, SDLK_KP_LEFTBRACE, SDLK_KP_LEFTPAREN, SDLK_KP_LESS, SDLK_KP_MINUS, SDLK_KP_MULTIPLY, SDLK_KP_PERCENT, SDLK_KP_PERIOD, SDLK_KP_PLUS, SDLK_KP_PLUSMINUS, SDLK_KP_RIGHTBRACE, SDLK_KP_RIGHTPAREN, SDLK_KP_SPACE, SDLK_KP_TAB, SDLK_LEFT, SDLK_LEFTBRACE, SDLK_LEFTPAREN, SDLK_LESS, SDLK_MINUS, SDLK_PAGEDOWN, SDLK_PAGEUP, SDLK_PERCENT, SDLK_PERIOD, SDLK_PLUS, SDLK_PLUSMINUS, SDLK_RETURN, SDLK_RIGHT, SDLK_RIGHTBRACE, SDLK_RIGHTPAREN, SDLK_SLASH, SDLK_SPACE, SDLK_TAB, and SDLK_UP.
Referenced by SDL_GetKeyFromScancode().
SDL_GetCurrentKeymap()
SDL_Keymap * SDL_GetCurrentKeymap (bool ignore_options)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    SDL_Keymap *keymap = SDL_keyboard.keymap;
    if (!ignore_options) {
        if (keymap && keymap->thai_keyboard) {
            // Thai keyboards are QWERTY plus Thai characters, use the default QWERTY keymap
            return NULL;
        }
        if ((keyboard->keycode_options & KEYCODE_OPTION_LATIN_LETTERS) &&
            keymap && !keymap->latin_letters) {
            // We'll use the default QWERTY keymap
            return NULL;
        }
    }
    return keyboard->keymap;
}
References KEYCODE_OPTION_LATIN_LETTERS, SDL_Keyboard::keycode_options, SDL_Keyboard::keymap, SDL_Keymap::latin_letters, NULL, SDL_keyboard, and SDL_Keymap::thai_keyboard.
Referenced by SDL_GetKeyFromName(), SDL_GetKeyFromScancode(), and SDL_GetKeyName().
SDL_GetKeyboardFocus()
SDL_Window * SDL_GetKeyboardFocus (void)
Query the window which currently has keyboard focus.
Returns
the window with keyboard focus.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    return keyboard->focus;
}
References SDL_Keyboard::focus, and SDL_keyboard.
Referenced by SDL_BLooper::_HandleKey(), SDL_BLooper::_HandleKeyboardFocus(), DBus_MessageFilter(), SDL_CaptureMouse(), SDL_DestroyWindow(), SDL_Fcitx_ProcessKeyEvent(), SDL_GetToplevelForKeyboardFocus(), SDL_PrivateJoystickShouldIgnoreEvent(), SDL_SetRelativeMouseMode(), SDL_ShowMessageBox(), and SDL_UpdateRelativeMouseMode().
SDL_GetKeyboardIndex()
int SDL_GetKeyboardIndex (SDL_KeyboardID keyboardID) static
{
    for (int i = 0; i < SDL_keyboard_count; ++i) {
        if (keyboardID == SDL_keyboards[i].instance_id) {
            return i;
        }
    }
    return -1;
}
References SDL_keyboard_count, and SDL_keyboards.
Referenced by SDL_AddKeyboard(), SDL_GetKeyboardNameForID(), and SDL_RemoveKeyboard().
SDL_GetKeyboardNameForID()
const char * SDL_GetKeyboardNameForID (SDL_KeyboardID instance_id)
Get the name of a keyboard.
This function returns "" if the keyboard doesn't have a name.
Parameters
instance_id the keyboard instance ID.
Returns
the name of the selected keyboard or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboards
{
    int keyboard_index = SDL_GetKeyboardIndex(instance_id);
    if (keyboard_index < 0) {
        SDL_SetError("Keyboard %" SDL_PRIu32 " not found", instance_id);
        return NULL;
    }
    return SDL_GetPersistentString(SDL_keyboards[keyboard_index].name);
}
References NULL, SDL_GetKeyboardIndex(), SDL_GetPersistentString(), SDL_keyboards, SDL_PRIu32, and SDL_SetError().
SDL_GetKeyboards()
SDL_KeyboardID * SDL_GetKeyboards (int * count)
Get a list of currently connected keyboards.
Note that this will include any device or virtual driver that includes keyboard functionality, including some mice, KVM switches, motherboard power buttons, etc. You should wait for input from a device before you consider it actively in use.
Parameters
count a pointer filled in with the number of keyboards returned, may be NULL.
Returns
a 0 terminated array of keyboards instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboardNameForID
SDL_HasKeyboard
{
    int i;
    SDL_KeyboardID *keyboards;
    keyboards = (SDL_JoystickID *)SDL_malloc((SDL_keyboard_count + 1) * sizeof(*keyboards));
    if (keyboards) {
        if (count) {
            *count = SDL_keyboard_count;
        }
        for (i = 0; i < SDL_keyboard_count; ++i) {
            keyboards[i] = SDL_keyboards[i].instance_id;
        }
        keyboards[i] = 0;
    } else {
        if (count) {
            *count = 0;
        }
    }
    return keyboards;
}
References count, SDL_keyboard_count, SDL_keyboards, and SDL_malloc().
SDL_GetKeyboardState()
const bool * SDL_GetKeyboardState (int * numkeys)
Get a snapshot of the current state of the keyboard.
The pointer returned is a pointer to an internal SDL array. It will be valid for the whole lifetime of the application and should not be freed by the caller.
A array element with a value of true means that the key is pressed and a value of false means that it is not. Indexes into this array are obtained by using SDL_Scancode values.
Use SDL_PumpEvents() to update the state array.
This function gives you the current state after all events have been processed, so if a key or button has been pressed and released before you process events, then the pressed state will never show up in the SDL_GetKeyboardState() calls.
Note: This function doesn't take into account whether shift has been pressed or not.
Parameters
numkeys if non-NULL, receives the length of the returned array.
Returns
a pointer to an array of key states.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PumpEvents
SDL_ResetKeyboard
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (numkeys != (int *)0) {
        *numkeys = SDL_SCANCODE_COUNT;
    }
    return keyboard->keystate;
}
References SDL_Keyboard::keystate, SDL_keyboard, and SDL_SCANCODE_COUNT.
SDL_GetKeyFromScancode()
SDL_Keycode SDL_GetKeyFromScancode (SDL_Scancode scancode, SDL_Keymod modstate, bool key_event)
Get the key code corresponding to the given scancode according to the current keyboard layout.
If you want to get the keycode as it would be delivered in key events, including options specified in SDL_HINT_KEYCODE_OPTIONS, then you should pass key_event as true. Otherwise this function simply translates the scancode based on the given modifier state.
Parameters
scancode the desired SDL_Scancode to query.
modstate the modifier state to use when translating the scancode to a keycode.
key_event true if the keycode will be used in key events.
Returns
the SDL_Keycode that corresponds to the given SDL_Scancode.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyName
SDL_GetScancodeFromKey
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (key_event) {
        SDL_Keymap *keymap = SDL_GetCurrentKeymap(false);
        bool numlock = (modstate & SDL_KMOD_NUM) != 0;
        SDL_Keycode keycode;
        // We won't be applying any modifiers by default
        modstate = SDL_KMOD_NONE;
        if ((keyboard->keycode_options & KEYCODE_OPTION_FRENCH_NUMBERS) &&
            keymap && keymap->french_numbers &&
            (scancode >= SDL_SCANCODE_1 && scancode <= SDL_SCANCODE_0)) {
            // Add the shift state to generate a numeric keycode
            modstate |= SDL_KMOD_SHIFT;
        }
        keycode = SDL_GetKeymapKeycode(keymap, scancode, modstate);
        if (keyboard->keycode_options & KEYCODE_OPTION_HIDE_NUMPAD) {
            keycode = SDL_ConvertNumpadKeycode(keycode, numlock);
        }
        return keycode;
    }
    return SDL_GetKeymapKeycode(keyboard->keymap, scancode, modstate);
}
References SDL_Keymap::french_numbers, keycode, KEYCODE_OPTION_FRENCH_NUMBERS, KEYCODE_OPTION_HIDE_NUMPAD, SDL_Keyboard::keycode_options, SDL_Keyboard::keymap, scancode, SDL_ConvertNumpadKeycode(), SDL_GetCurrentKeymap(), SDL_GetKeymapKeycode(), SDL_keyboard, SDL_KMOD_NONE, SDL_KMOD_NUM, SDL_KMOD_SHIFT, SDL_SCANCODE_0, and SDL_SCANCODE_1.
Referenced by SDL_GetKeyFromName(), and SDL_SendKeyboardKeyInternal().
SDL_GetModState()
SDL_Keymod SDL_GetModState (void)
Get the current key modifier state for the keyboard.
Returns
an OR'd combination of the modifier keys for the keyboard. See SDL_Keymod for details.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboardState
SDL_SetModState
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    return keyboard->modstate;
}
References SDL_Keyboard::modstate, and SDL_keyboard.
Referenced by Fcitx_ModState(), and SDL_SendKeyboardKeyAndKeycode().
SDL_GetScancodeFromKey()
SDL_Scancode SDL_GetScancodeFromKey (SDL_Keycode key, SDL_Keymod * modstate)
Get the scancode corresponding to the given key code according to the current keyboard layout.
Note that there may be multiple scancode+modifier states that can generate this keycode, this will just return the first one found.
Parameters
key the desired SDL_Keycode to query.
modstate a pointer to the modifier state that would be used when the scancode generates this key, may be NULL.
Returns
the SDL_Scancode that corresponds to the given SDL_Keycode.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyFromScancode
SDL_GetScancodeName
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    return SDL_GetKeymapScancode(keyboard->keymap, key, modstate);
}
References SDL_Keyboard::keymap, SDL_GetKeymapScancode(), and SDL_keyboard.
SDL_HardwareKeyboardKeyPressed()
bool SDL_HardwareKeyboardKeyPressed (void)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    int scancode;
    for (scancode = SDL_SCANCODE_UNKNOWN; scancode < SDL_SCANCODE_COUNT; ++scancode) {
        if (keyboard->keysource[scancode] & KEYBOARD_HARDWARE) {
            return true;
        }
    }
    return keyboard->hardware_timestamp ? true : false;
}
References SDL_Keyboard::hardware_timestamp, KEYBOARD_HARDWARE, SDL_Keyboard::keysource, scancode, SDL_keyboard, SDL_SCANCODE_COUNT, SDL_SCANCODE_UNKNOWN, and true.
SDL_HasKeyboard()
bool SDL_HasKeyboard (void)
Return whether a keyboard is currently connected.
Returns
true if a keyboard is connected, false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboards
{
    return (SDL_keyboard_count > 0);
}
References SDL_keyboard_count.
Referenced by AutoShowingScreenKeyboard().
SDL_InitKeyboard()
bool SDL_InitKeyboard (void)
{
    SDL_AddHintCallback(SDL_HINT_KEYCODE_OPTIONS,
                        SDL_KeycodeOptionsChanged, &SDL_keyboard);
    return true;
}
References SDL_AddHintCallback(), SDL_HINT_KEYCODE_OPTIONS, SDL_keyboard, and SDL_KeycodeOptionsChanged().
Referenced by SDL_VideoInit().
SDL_IsKeyboard()
bool SDL_IsKeyboard (Uint16 vendor, Uint16 product, int num_keys)
{
    const int REAL_KEYBOARD_KEY_COUNT = 50;
    if (num_keys > 0 && num_keys < REAL_KEYBOARD_KEY_COUNT) {
        return false;
    }
    // Eventually we'll have a blacklist of devices that enumerate as keyboards but aren't really
    return true;
}
SDL_KeycodeOptionsChanged()
void SDLCALL SDL_KeycodeOptionsChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    SDL_Keyboard *keyboard = (SDL_Keyboard *)userdata;
    if (hint && *hint) {
        keyboard->keycode_options = 0;
        if (!SDL_strstr(hint, "none")) {
            if (SDL_strstr(hint, "hide_numpad")) {
                keyboard->keycode_options |= KEYCODE_OPTION_HIDE_NUMPAD;
            }
            if (SDL_strstr(hint, "french_numbers")) {
                keyboard->keycode_options |= KEYCODE_OPTION_FRENCH_NUMBERS;
            }
            if (SDL_strstr(hint, "latin_letters")) {
                keyboard->keycode_options |= KEYCODE_OPTION_LATIN_LETTERS;
            }
        }
    } else {
        keyboard->keycode_options = DEFAULT_KEYCODE_OPTIONS;
    }
}
References DEFAULT_KEYCODE_OPTIONS, KEYCODE_OPTION_FRENCH_NUMBERS, KEYCODE_OPTION_HIDE_NUMPAD, KEYCODE_OPTION_LATIN_LETTERS, SDL_Keyboard::keycode_options, SDL_strstr(), and SDLCALL.
Referenced by SDL_InitKeyboard(), and SDL_QuitKeyboard().
SDL_QuitKeyboard()
void SDL_QuitKeyboard (void)
{
    for (int i = SDL_keyboard_count; i--;) {
        SDL_RemoveKeyboard(SDL_keyboards[i].instance_id, false);
    }
    SDL_free(SDL_keyboards);
    SDL_keyboards = NULL;
    if (SDL_keyboard.keymap && SDL_keyboard.keymap->auto_release) {
        SDL_DestroyKeymap(SDL_keyboard.keymap);
        SDL_keyboard.keymap = NULL;
    }
    SDL_RemoveHintCallback(SDL_HINT_KEYCODE_OPTIONS,
                        SDL_KeycodeOptionsChanged, &SDL_keyboard);
}
References NULL, SDL_DestroyKeymap(), SDL_free(), SDL_HINT_KEYCODE_OPTIONS, SDL_keyboard, SDL_keyboard_count, SDL_keyboards, SDL_KeycodeOptionsChanged(), SDL_RemoveHintCallback(), and SDL_RemoveKeyboard().
Referenced by SDL_VideoInit(), and SDL_VideoQuit().
SDL_ReleaseAutoReleaseKeys()
void SDL_ReleaseAutoReleaseKeys (void)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    int scancode;
    if (keyboard->autorelease_pending) {
        for (scancode = SDL_SCANCODE_UNKNOWN; scancode < SDL_SCANCODE_COUNT; ++scancode) {
            if (keyboard->keysource[scancode] == KEYBOARD_AUTORELEASE) {
                SDL_SendKeyboardKeyInternal(0, KEYBOARD_AUTORELEASE, SDL_GLOBAL_KEYBOARD_ID, 0, (SDL_Scancode)scancode, false);
            }
        }
        keyboard->autorelease_pending = false;
    }
    if (keyboard->hardware_timestamp) {
        // Keep hardware keyboard "active" for 250 ms
        if (SDL_GetTicks() >= keyboard->hardware_timestamp + 250) {
            keyboard->hardware_timestamp = 0;
        }
    }
}
References SDL_Keyboard::autorelease_pending, SDL_Keyboard::hardware_timestamp, KEYBOARD_AUTORELEASE, SDL_Keyboard::keysource, scancode, SDL_GetTicks(), SDL_GLOBAL_KEYBOARD_ID, SDL_keyboard, SDL_SCANCODE_COUNT, SDL_SCANCODE_UNKNOWN, and SDL_SendKeyboardKeyInternal().
Referenced by SDL_PumpEventsInternal().
SDL_RemoveKeyboard()
void SDL_RemoveKeyboard (SDL_KeyboardID keyboardID, bool send_event)
{
    int keyboard_index = SDL_GetKeyboardIndex(keyboardID);
    if (keyboard_index < 0) {
        // We don't know about this keyboard
        return;
    }
    SDL_free(SDL_keyboards[keyboard_index].name);
    if (keyboard_index != SDL_keyboard_count - 1) {
        SDL_memmove(&SDL_keyboards[keyboard_index], &SDL_keyboards[keyboard_index + 1], (SDL_keyboard_count - keyboard_index - 1) * sizeof(SDL_keyboards[keyboard_index]));
    }
    --SDL_keyboard_count;
    if (send_event) {
        SDL_Event event;
        SDL_zero(event);
        event.type = SDL_EVENT_KEYBOARD_REMOVED;
        event.kdevice.which = keyboardID;
        SDL_PushEvent(&event);
    }
}
References SDL_EVENT_KEYBOARD_REMOVED, SDL_free(), SDL_GetKeyboardIndex(), SDL_keyboard_count, SDL_keyboards, SDL_memmove, SDL_PushEvent(), and SDL_zero.
Referenced by SDL_QuitKeyboard().
SDL_ResetKeyboard()
void SDL_ResetKeyboard (void)
Clear the state of the keyboard.
This function will generate key up events for all pressed keys.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetKeyboardState
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    int scancode;
#ifdef DEBUG_KEYBOARD
    SDL_Log("Resetting keyboard");
#endif
    for (scancode = SDL_SCANCODE_UNKNOWN; scancode < SDL_SCANCODE_COUNT; ++scancode) {
        if (keyboard->keystate[scancode]) {
            SDL_SendKeyboardKey(0, SDL_GLOBAL_KEYBOARD_ID, 0, (SDL_Scancode)scancode, false);
        }
    }
}
References SDL_Keyboard::keystate, scancode, SDL_GLOBAL_KEYBOARD_ID, SDL_keyboard, SDL_Log(), SDL_SCANCODE_COUNT, SDL_SCANCODE_UNKNOWN, and SDL_SendKeyboardKey().
Referenced by SDL_SetKeyboardFocus(), and SDL_ShowMessageBox().
SDL_SendEditingText()
void SDL_SendEditingText (const char * text, int start, int length)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->focus || !SDL_TextInputActive(keyboard->focus)) {
        return;
    }
    if (!text) {
        return;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_TEXT_EDITING)) {
        SDL_Event event;
        event.type = SDL_EVENT_TEXT_EDITING;
        event.common.timestamp = 0;
        event.edit.windowID = keyboard->focus ? keyboard->focus->id : 0;
        event.edit.start = start;
        event.edit.length = length;
        event.edit.text = SDL_CreateTemporaryString(text);
        if (!event.edit.text) {
            return;
        }
        SDL_PushEvent(&event);
    }
}
References SDL_Keyboard::focus, SDL_Window::id, SDL_CreateTemporaryString(), SDL_EVENT_TEXT_EDITING, SDL_EventEnabled(), SDL_keyboard, SDL_PushEvent(), and SDL_TextInputActive().
Referenced by DBus_MessageFilter().
SDL_SendEditingTextCandidates()
void SDL_SendEditingTextCandidates (char ** candidates, int num_candidates, int selected_candidate, bool horizontal)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->focus || !SDL_TextInputActive(keyboard->focus)) {
        return;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_TEXT_EDITING_CANDIDATES)) {
        SDL_Event event;
        event.type = SDL_EVENT_TEXT_EDITING_CANDIDATES;
        event.common.timestamp = 0;
        event.edit.windowID = keyboard->focus ? keyboard->focus->id : 0;
        if (num_candidates > 0) {
            const char * const *event_candidates = CreateCandidatesForEvent(candidates, num_candidates);
            if (!event_candidates) {
                return;
            }
            event.edit_candidates.candidates = event_candidates;
            event.edit_candidates.num_candidates = num_candidates;
            event.edit_candidates.selected_candidate = selected_candidate;
            event.edit_candidates.horizontal = horizontal;
        } else {
            event.edit_candidates.candidates = NULL;
            event.edit_candidates.num_candidates = 0;
            event.edit_candidates.selected_candidate = -1;
            event.edit_candidates.horizontal = false;
        }
        SDL_PushEvent(&event);
    }
}
References CreateCandidatesForEvent(), SDL_Keyboard::focus, SDL_Window::id, NULL, SDL_EVENT_TEXT_EDITING_CANDIDATES, SDL_EventEnabled(), SDL_keyboard, SDL_PushEvent(), and SDL_TextInputActive().
SDL_SendKeyboardKey()
bool SDL_SendKeyboardKey (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down)
{
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_HARDWARE, keyboardID, rawcode, scancode, down);
}
References KEYBOARD_HARDWARE, scancode, and SDL_SendKeyboardKeyInternal().
Referenced by SDL_BLooper::_HandleKey(), handleKeyboardEvent(), SDL_ResetKeyboard(), Translate_to_keycode(), and updateKeyboard().
SDL_SendKeyboardKeyAndKeycode()
bool SDL_SendKeyboardKeyAndKeycode (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, SDL_Keycode keycode, bool down)
{
    if (down) {
        // Make sure we have this keycode in our keymap
        SetKeymapEntry(scancode, SDL_GetModState(), keycode);
    }
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_HARDWARE, keyboardID, rawcode, scancode, down);
}
References KEYBOARD_HARDWARE, keycode, scancode, SDL_GetModState(), SDL_SendKeyboardKeyInternal(), and SetKeymapEntry().
SDL_SendKeyboardKeyAutoRelease()
bool SDL_SendKeyboardKeyAutoRelease (Uint64 timestamp, SDL_Scancode scancode)
{
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_AUTORELEASE, SDL_GLOBAL_KEYBOARD_ID, 0, scancode, true);
}
References KEYBOARD_AUTORELEASE, scancode, SDL_GLOBAL_KEYBOARD_ID, and SDL_SendKeyboardKeyInternal().
SDL_SendKeyboardKeyIgnoreModifiers()
bool SDL_SendKeyboardKeyIgnoreModifiers (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down)
{
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_HARDWARE | KEYBOARD_IGNOREMODIFIERS, keyboardID, rawcode, scancode, down);
}
References KEYBOARD_HARDWARE, KEYBOARD_IGNOREMODIFIERS, scancode, and SDL_SendKeyboardKeyInternal().
SDL_SendKeyboardKeyInternal()
bool SDL_SendKeyboardKeyInternal (Uint64 timestamp, Uint32 flags, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down) static
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    bool posted = false;
    SDL_Keycode keycode = SDLK_UNKNOWN;
    Uint32 type;
    bool repeat = false;
    const Uint8 source = flags & KEYBOARD_SOURCE_MASK;
#ifdef DEBUG_KEYBOARD
    SDL_Log("The '%s' key has been %s", SDL_GetScancodeName(scancode), down ? "pressed" : "released");
#endif
    // Figure out what type of event this is
    if (down) {
        type = SDL_EVENT_KEY_DOWN;
    } else {
        type = SDL_EVENT_KEY_UP;
    }
    if (scancode > SDL_SCANCODE_UNKNOWN && scancode < SDL_SCANCODE_COUNT) {
        // Drop events that don't change state
        if (down) {
            if (keyboard->keystate[scancode]) {
                if (!(keyboard->keysource[scancode] & source)) {
                    keyboard->keysource[scancode] |= source;
                    return false;
                }
                repeat = true;
            }
            keyboard->keysource[scancode] |= source;
        } else {
            if (!keyboard->keystate[scancode]) {
                return false;
            }
            keyboard->keysource[scancode] = 0;
        }
        // Update internal keyboard state
        keyboard->keystate[scancode] = down;
        keycode = SDL_GetKeyFromScancode(scancode, keyboard->modstate, true);
    } else if (rawcode == 0) {
        // Nothing to do!
        return false;
    }
    if (source == KEYBOARD_HARDWARE) {
        keyboard->hardware_timestamp = SDL_GetTicks();
    } else if (source == KEYBOARD_AUTORELEASE) {
        keyboard->autorelease_pending = true;
    }
    // Update modifiers state if applicable
    if (!(flags & KEYBOARD_IGNOREMODIFIERS) && !repeat) {
        SDL_Keymod modifier;
        switch (keycode) {
        case SDLK_LCTRL:
            modifier = SDL_KMOD_LCTRL;
            break;
        case SDLK_RCTRL:
            modifier = SDL_KMOD_RCTRL;
            break;
        case SDLK_LSHIFT:
            modifier = SDL_KMOD_LSHIFT;
            break;
        case SDLK_RSHIFT:
            modifier = SDL_KMOD_RSHIFT;
            break;
        case SDLK_LALT:
            modifier = SDL_KMOD_LALT;
            break;
        case SDLK_RALT:
            modifier = SDL_KMOD_RALT;
            break;
        case SDLK_LGUI:
            modifier = SDL_KMOD_LGUI;
            break;
        case SDLK_RGUI:
            modifier = SDL_KMOD_RGUI;
            break;
        case SDLK_MODE:
            modifier = SDL_KMOD_MODE;
            break;
        default:
            modifier = SDL_KMOD_NONE;
            break;
        }
        if (SDL_EVENT_KEY_DOWN == type) {
            switch (keycode) {
            case SDLK_NUMLOCKCLEAR:
                keyboard->modstate ^= SDL_KMOD_NUM;
                break;
            case SDLK_CAPSLOCK:
                keyboard->modstate ^= SDL_KMOD_CAPS;
                break;
            case SDLK_SCROLLLOCK:
                keyboard->modstate ^= SDL_KMOD_SCROLL;
                break;
            default:
                keyboard->modstate |= modifier;
                break;
            }
        } else {
            keyboard->modstate &= ~modifier;
        }
    }
    // Post the event, if desired
    if (SDL_EventEnabled(type)) {
        SDL_Event event;
        event.type = type;
        event.common.timestamp = timestamp;
        event.key.scancode = scancode;
        event.key.key = keycode;
        event.key.mod = keyboard->modstate;
        event.key.raw = (Uint16)rawcode;
        event.key.down = down;
        event.key.repeat = repeat;
        event.key.windowID = keyboard->focus ? keyboard->focus->id : 0;
        event.key.which = keyboardID;
        posted = SDL_PushEvent(&event);
    }
    /* If the keyboard is grabbed and the grabbed window is in full-screen,
       minimize the window when we receive Alt+Tab, unless the application
       has explicitly opted out of this behavior. */
    if (keycode == SDLK_TAB && down &&
        (keyboard->modstate & SDL_KMOD_ALT) &&
        keyboard->focus &&
        (keyboard->focus->flags & SDL_WINDOW_KEYBOARD_GRABBED) &&
        (keyboard->focus->flags & SDL_WINDOW_FULLSCREEN) &&
        SDL_GetHintBoolean(SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED, true)) {
        /* We will temporarily forfeit our grab by minimizing our window,
           allowing the user to escape the application */
        SDL_MinimizeWindow(keyboard->focus);
    }
    return posted;
}
References SDL_Keyboard::autorelease_pending, SDL_Window::flags, SDL_Keyboard::focus, SDL_Keyboard::hardware_timestamp, SDL_Window::id, KEYBOARD_AUTORELEASE, KEYBOARD_HARDWARE, KEYBOARD_IGNOREMODIFIERS, KEYBOARD_SOURCE_MASK, keycode, SDL_Keyboard::keysource, SDL_Keyboard::keystate, SDL_Keyboard::modstate, scancode, SDL_EVENT_KEY_DOWN, SDL_EVENT_KEY_UP, SDL_EventEnabled(), SDL_GetHintBoolean(), SDL_GetKeyFromScancode(), SDL_GetScancodeName(), SDL_GetTicks(), SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED, SDL_keyboard, SDL_KMOD_ALT, SDL_KMOD_CAPS, SDL_KMOD_LALT, SDL_KMOD_LCTRL, SDL_KMOD_LGUI, SDL_KMOD_LSHIFT, SDL_KMOD_MODE, SDL_KMOD_NONE, SDL_KMOD_NUM, SDL_KMOD_RALT, SDL_KMOD_RCTRL, SDL_KMOD_RGUI, SDL_KMOD_RSHIFT, SDL_KMOD_SCROLL, SDL_Log(), SDL_MinimizeWindow(), SDL_PushEvent(), SDL_SCANCODE_COUNT, SDL_SCANCODE_UNKNOWN, SDL_WINDOW_FULLSCREEN, SDL_WINDOW_KEYBOARD_GRABBED, SDLK_CAPSLOCK, SDLK_LALT, SDLK_LCTRL, SDLK_LGUI, SDLK_LSHIFT, SDLK_MODE, SDLK_NUMLOCKCLEAR, SDLK_RALT, SDLK_RCTRL, SDLK_RGUI, SDLK_RSHIFT, SDLK_SCROLLLOCK, SDLK_TAB, and SDLK_UNKNOWN.
Referenced by SDL_ReleaseAutoReleaseKeys(), SDL_SendKeyboardKey(), SDL_SendKeyboardKeyAndKeycode(), SDL_SendKeyboardKeyAutoRelease(), SDL_SendKeyboardKeyIgnoreModifiers(), and SDL_SendKeyboardUnicodeKey().
SDL_SendKeyboardText()
void SDL_SendKeyboardText (const char * text)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->focus || !SDL_TextInputActive(keyboard->focus)) {
        return;
    }
    if (!text || !*text) {
        return;
    }
    // Don't post text events for unprintable characters
    if (SDL_iscntrl((unsigned char)*text)) {
        return;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_TEXT_INPUT)) {
        SDL_Event event;
        event.type = SDL_EVENT_TEXT_INPUT;
        event.common.timestamp = 0;
        event.text.windowID = keyboard->focus ? keyboard->focus->id : 0;
        event.text.text = SDL_CreateTemporaryString(text);
        if (!event.text.text) {
            return;
        }
        SDL_PushEvent(&event);
    }
}
References SDL_Keyboard::focus, SDL_Window::id, SDL_CreateTemporaryString(), SDL_EVENT_TEXT_INPUT, SDL_EventEnabled(), SDL_iscntrl(), SDL_keyboard, SDL_PushEvent(), and SDL_TextInputActive().
Referenced by SDL_BLooper::_HandleKey(), DBus_MessageFilter(), and Translate_to_text().
SDL_SendKeyboardUnicodeKey()
void SDL_SendKeyboardUnicodeKey (Uint64 timestamp, Uint32 ch)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    SDL_Keymod modstate = SDL_KMOD_NONE;
    SDL_Scancode scancode;
    if (ch == '\n') {
        ch = SDLK_RETURN;
    }
    scancode = SDL_GetKeymapScancode(keyboard->keymap, ch, &modstate);
    // Make sure we have this keycode in our keymap
    if (scancode == SDL_SCANCODE_UNKNOWN && ch < SDLK_SCANCODE_MASK) {
        scancode = GetNextReservedScancode();
        SetKeymapEntry(scancode, modstate, ch);
    }
    if (modstate & SDL_KMOD_SHIFT) {
        // If the character uses shift, press shift down
        SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, SDL_SCANCODE_LSHIFT, true);
    }
    // Send a keydown and keyup for the character
    SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, scancode, true);
    SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, scancode, false);
    if (modstate & SDL_KMOD_SHIFT) {
        // If the character uses shift, release shift
        SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, SDL_SCANCODE_LSHIFT, false);
    }
}
References GetNextReservedScancode(), KEYBOARD_VIRTUAL, SDL_Keyboard::keymap, scancode, SDL_GetKeymapScancode(), SDL_GLOBAL_KEYBOARD_ID, SDL_keyboard, SDL_KMOD_NONE, SDL_KMOD_SHIFT, SDL_SCANCODE_LSHIFT, SDL_SCANCODE_UNKNOWN, SDL_SendKeyboardKeyInternal(), SDLK_RETURN, SDLK_SCANCODE_MASK, and SetKeymapEntry().
SDL_SetKeyboardFocus()
bool SDL_SetKeyboardFocus (SDL_Window * window)
{
    SDL_VideoDevice *video = SDL_GetVideoDevice();
    SDL_Keyboard *keyboard = &SDL_keyboard;
    SDL_Mouse *mouse = SDL_GetMouse();
    if (window) {
        if (!SDL_ObjectValid(window, SDL_OBJECT_TYPE_WINDOW) || window->is_destroying) {
            return SDL_SetError("Invalid window");
        }
    }
    if (keyboard->focus && !window) {
        // We won't get anymore keyboard messages, so reset keyboard state
        SDL_ResetKeyboard();
        // Also leave mouse relative mode
        if (mouse->relative_mode) {
            SDL_SetRelativeMouseMode(false);
            SDL_Window *focus = keyboard->focus;
            if ((focus->flags & SDL_WINDOW_MINIMIZED) != 0) {
                // We can't warp the mouse within minimized windows, so manually restore the position
                float x = focus->x + mouse->x;
                float y = focus->y + mouse->y;
                SDL_WarpMouseGlobal(x, y);
            }
        }
    }
    // See if the current window has lost focus
    if (keyboard->focus && keyboard->focus != window) {
        SDL_SendWindowEvent(keyboard->focus, SDL_EVENT_WINDOW_FOCUS_LOST, 0, 0);
        // Ensures IME compositions are committed
        if (SDL_TextInputActive(keyboard->focus)) {
            if (video && video->StopTextInput) {
                video->StopTextInput(video, keyboard->focus);
            }
        }
    }
    keyboard->focus = window;
    if (keyboard->focus) {
        SDL_SendWindowEvent(keyboard->focus, SDL_EVENT_WINDOW_FOCUS_GAINED, 0, 0);
        if (SDL_TextInputActive(keyboard->focus)) {
            if (video && video->StartTextInput) {
                video->StartTextInput(video, keyboard->focus, keyboard->focus->text_input_props);
            }
        }
    }
    SDL_UpdateRelativeMouseMode();
    return true;
}
References SDL_Window::flags, SDL_Keyboard::focus, SDL_Mouse::relative_mode, SDL_EVENT_WINDOW_FOCUS_GAINED, SDL_EVENT_WINDOW_FOCUS_LOST, SDL_GetMouse(), SDL_GetVideoDevice(), SDL_keyboard, SDL_OBJECT_TYPE_WINDOW, SDL_ObjectValid(), SDL_ResetKeyboard(), SDL_SendWindowEvent(), SDL_SetError(), SDL_SetRelativeMouseMode(), SDL_TextInputActive(), SDL_UpdateRelativeMouseMode(), SDL_WarpMouseGlobal(), SDL_WINDOW_MINIMIZED, SDL_VideoDevice::StartTextInput, SDL_VideoDevice::StopTextInput, SDL_Window::text_input_props, SDL_Mouse::x, SDL_Window::x, SDL_Mouse::y, and SDL_Window::y.
Referenced by SDL_BLooper::_HandleKeyboardFocus(), GDK_RegisterChangeNotifications(), SDL_DestroyWindow(), SDL_HideWindow(), SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationWillEnterBackground(), and SDL_ShowWindow().
SDL_SetKeymap()
void SDL_SetKeymap (SDL_Keymap * keymap, bool send_event)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (keyboard->keymap && keyboard->keymap->auto_release) {
        SDL_DestroyKeymap(keyboard->keymap);
    }
    keyboard->keymap = keymap;
    if (keymap && !keymap->layout_determined) {
        keymap->layout_determined = true;
        // Detect French number row (all symbols)
        keymap->french_numbers = true;
        for (int i = SDL_SCANCODE_1; i <= SDL_SCANCODE_0; ++i) {
            if (SDL_isdigit(SDL_GetKeymapKeycode(keymap, (SDL_Scancode)i, SDL_KMOD_NONE)) ||
                !SDL_isdigit(SDL_GetKeymapKeycode(keymap, (SDL_Scancode)i, SDL_KMOD_SHIFT))) {
                keymap->french_numbers = false;
                break;
                }
        }
        // Detect non-Latin keymap
        keymap->thai_keyboard = false;
        keymap->latin_letters = false;
        for (int i = SDL_SCANCODE_A; i <= SDL_SCANCODE_D; ++i) {
            SDL_Keycode key = SDL_GetKeymapKeycode(keymap, (SDL_Scancode)i, SDL_KMOD_NONE);
            if (key <= 0xFF) {
                keymap->latin_letters = true;
                break;
            }
            if (key >= 0x0E00 && key <= 0x0E7F) {
                keymap->thai_keyboard = true;
                break;
            }
        }
    }
    if (send_event) {
        SDL_SendKeymapChangedEvent();
    }
}
References SDL_Keymap::auto_release, SDL_Keymap::french_numbers, SDL_Keyboard::keymap, SDL_Keymap::latin_letters, SDL_Keymap::layout_determined, SDL_DestroyKeymap(), SDL_GetKeymapKeycode(), SDL_isdigit(), SDL_keyboard, SDL_KMOD_NONE, SDL_KMOD_SHIFT, SDL_SCANCODE_0, SDL_SCANCODE_1, SDL_SCANCODE_A, SDL_SCANCODE_D, SDL_SendKeymapChangedEvent(), and SDL_Keymap::thai_keyboard.
SDL_SetModState()
void SDL_SetModState (SDL_Keymod modstate)
Set the current key modifier state for the keyboard.
The inverse of SDL_GetModState(), SDL_SetModState() allows you to impose modifier key states on your application. Simply pass your desired modifier states into modstate. This value may be a bitwise, OR'd combination of SDL_Keymod values.
This does not change the keyboard state, only the key modifier flags that SDL reports.
Parameters
modstate the desired SDL_Keymod for the keyboard.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetModState
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    keyboard->modstate = modstate;
}
References SDL_Keyboard::modstate, and SDL_keyboard.
SDL_ToggleModState()
void SDL_ToggleModState (SDL_Keymod modstate, bool toggle)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (toggle) {
        keyboard->modstate |= modstate;
    } else {
        keyboard->modstate &= ~modstate;
    }
}
References SDL_Keyboard::modstate, and SDL_keyboard.
SetKeymapEntry()
void SetKeymapEntry (SDL_Scancode scancode, SDL_Keymod modstate, SDL_Keycode keycode) static
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->keymap) {
        keyboard->keymap = SDL_CreateKeymap(true);
    }
    SDL_SetKeymapEntry(keyboard->keymap, scancode, modstate, keycode);
}
References keycode, SDL_Keyboard::keymap, scancode, SDL_CreateKeymap(), SDL_keyboard, and SDL_SetKeymapEntry().
Referenced by SDL_SendKeyboardKeyAndKeycode(), and SDL_SendKeyboardUnicodeKey().
Variable Documentation
SDL_keyboard
SDL_Keyboard SDL_keyboard static
Referenced by GetNextReservedScancode(), SDL_GetCurrentKeymap(), SDL_GetKeyboardFocus(), SDL_GetKeyboardState(), SDL_GetKeyFromScancode(), SDL_GetModState(), SDL_GetScancodeFromKey(), SDL_HardwareKeyboardKeyPressed(), SDL_InitKeyboard(), SDL_QuitKeyboard(), SDL_ReleaseAutoReleaseKeys(), SDL_ResetKeyboard(), SDL_SendEditingText(), SDL_SendEditingTextCandidates(), SDL_SendKeyboardKeyInternal(), SDL_SendKeyboardText(), SDL_SendKeyboardUnicodeKey(), SDL_SetKeyboardFocus(), SDL_SetKeymap(), SDL_SetModState(), SDL_ToggleModState(), and SetKeymapEntry().
SDL_keyboard_count
int SDL_keyboard_count static
Referenced by SDL_AddKeyboard(), SDL_GetKeyboardIndex(), SDL_GetKeyboards(), SDL_HasKeyboard(), SDL_QuitKeyboard(), and SDL_RemoveKeyboard().
SDL_keyboards
SDL_KeyboardInstance* SDL_keyboards static
Referenced by SDL_AddKeyboard(), SDL_GetKeyboardIndex(), SDL_GetKeyboardNameForID(), SDL_GetKeyboards(), SDL_QuitKeyboard(), and SDL_RemoveKeyboard().