SDL3: SDL-main/src/dialog/SDL_dialog.h File Reference
SDL_dialog.h File Reference
Functions
void SDL_SYS_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props)
Function Documentation
SDL_SYS_ShowFileDialogWithProperties()
void SDL_SYS_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void * userdata, SDL_PropertiesID props)
{
    SDL_DialogFileFilter *filters = SDL_GetPointerProperty(props, SDL_PROP_FILE_DIALOG_FILTERS_POINTER, NULL);
    int nfilters = (int) SDL_GetNumberProperty(props, SDL_PROP_FILE_DIALOG_NFILTERS_NUMBER, 0);
    bool allow_many = SDL_GetBooleanProperty(props, SDL_PROP_FILE_DIALOG_MANY_BOOLEAN, false);
    bool is_save;
    if (SDL_GetHint(SDL_HINT_FILE_DIALOG_DRIVER) != NULL) {
        SDL_SetError("File dialog driver unsupported (don't set SDL_HINT_FILE_DIALOG_DRIVER)");
        callback(userdata, NULL, -1);
        return;
    }
    switch (type) {
    case SDL_FILEDIALOG_OPENFILE:
        is_save = false;
        break;
    case SDL_FILEDIALOG_SAVEFILE:
        is_save = true;
        break;
    case SDL_FILEDIALOG_OPENFOLDER:
        SDL_Unsupported();
        callback(userdata, NULL, -1);
        return;
    };
    if (!Android_JNI_OpenFileDialog(callback, userdata, filters, nfilters, is_save, allow_many)) {
        // SDL_SetError is already called when it fails
        callback(userdata, NULL, -1);
    }
}
References Android_JNI_OpenFileDialog(), detect_available_methods(), detected_function, NULL, SDL_FALLTHROUGH, SDL_FILEDIALOG_OPENFILE, SDL_FILEDIALOG_OPENFOLDER, SDL_FILEDIALOG_SAVEFILE, SDL_free(), SDL_GetBooleanProperty(), SDL_GetError(), SDL_GetHint(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetStringProperty(), SDL_HINT_FILE_DIALOG_DRIVER, SDL_InitBeApp(), SDL_OutOfMemory(), SDL_PROP_FILE_DIALOG_ACCEPT_STRING, SDL_PROP_FILE_DIALOG_CANCEL_STRING, SDL_PROP_FILE_DIALOG_FILTERS_POINTER, SDL_PROP_FILE_DIALOG_LOCATION_STRING, SDL_PROP_FILE_DIALOG_MANY_BOOLEAN, SDL_PROP_FILE_DIALOG_NFILTERS_NUMBER, SDL_PROP_FILE_DIALOG_TITLE_STRING, SDL_PROP_FILE_DIALOG_WINDOW_POINTER, SDL_SetError(), SDL_strdup(), SDL_Unsupported, CallbackLooper::SetToBeFreed(), ShowFileDialog(), ShowFolderDialog(), and validate_filters().
Referenced by SDL_ShowFileDialogWithProperties().