SDL3: SDL-main/src/events/SDL_quit.c File Reference
SDL_quit.c File Reference
#include "SDL_internal.h"
#include "SDL_events_c.h"
Functions
bool SDL_InitQuit (void)
void SDL_QuitQuit (void)
void SDL_SendPendingSignalEvents (void)
void SDL_SendQuit (void)
Function Documentation
SDL_InitQuit()
bool SDL_InitQuit (void)
{
#ifdef HAVE_SIGNAL_SUPPORT
    if (!SDL_GetHintBoolean(SDL_HINT_NO_SIGNAL_HANDLERS, false)) {
        return SDL_QuitInit_Internal();
    }
#endif
    return true;
}
References SDL_GetHintBoolean(), and SDL_HINT_NO_SIGNAL_HANDLERS.
Referenced by SDL_InitEvents().
SDL_QuitQuit()
void SDL_QuitQuit (void)
{
#ifdef HAVE_SIGNAL_SUPPORT
    if (!disable_signals) {
        SDL_QuitQuit_Internal();
    }
#endif
}
Referenced by SDL_QuitEvents().
SDL_SendPendingSignalEvents()
void SDL_SendPendingSignalEvents (void)
{
#ifdef HAVE_SIGNAL_SUPPORT
    if (send_quit_pending) {
        SDL_SendQuit();
        SDL_assert(!send_quit_pending);
    }
#ifdef SDL_BACKGROUNDING_SIGNAL
    if (send_backgrounding_pending) {
        send_backgrounding_pending = false;
        SDL_OnApplicationWillEnterBackground();
    }
#endif
#ifdef SDL_FOREGROUNDING_SIGNAL
    if (send_foregrounding_pending) {
        send_foregrounding_pending = false;
        SDL_OnApplicationDidEnterForeground();
    }
#endif
#endif
}
References SDL_assert, SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationWillEnterBackground(), and SDL_SendQuit().
Referenced by SDL_PumpEventMaintenance().
SDL_SendQuit()
void SDL_SendQuit (void)
{
#ifdef HAVE_SIGNAL_SUPPORT
    send_quit_pending = false;
#endif
    SDL_SendAppEvent(SDL_EVENT_QUIT);
}
References SDL_EVENT_QUIT, and SDL_SendAppEvent().
Referenced by SDL_SendPendingSignalEvents(), SDL_SendWindowEvent(), and SDL_UnregisterTray().