SDL3: SDL-main/src/core/linux/SDL_ime.c File Reference
SDL_ime.c File Reference
#include "SDL_internal.h"
#include "SDL_ime.h"
#include "SDL_ibus.h"
#include "SDL_fcitx.h"
Typedefs
typedef bool(* SDL_IME_Init_t) (void)
typedef bool(* SDL_IME_ProcessKeyEvent_t) (Uint32, Uint32, bool down)
typedef void(* SDL_IME_PumpEvents_t) (void)
typedef void(* SDL_IME_Quit_t) (void)
typedef void(* SDL_IME_Reset_t) (void)
typedef void(* SDL_IME_SetFocus_t) (bool)
typedef void(* SDL_IME_UpdateTextInputArea_t) (SDL_Window *window)
Functions
static void InitIME (void)
bool SDL_IME_Init (void)
bool SDL_IME_ProcessKeyEvent (Uint32 keysym, Uint32 keycode, bool down)
void SDL_IME_PumpEvents (void)
void SDL_IME_Quit (void)
void SDL_IME_Reset (void)
void SDL_IME_SetFocus (bool focused)
void SDL_IME_UpdateTextInputArea (SDL_Window *window)
Variables
static SDL_IME_Init_t SDL_IME_Init_Real = NULL
static SDL_IME_ProcessKeyEvent_t SDL_IME_ProcessKeyEvent_Real = NULL
static SDL_IME_PumpEvents_t SDL_IME_PumpEvents_Real = NULL
static SDL_IME_Quit_t SDL_IME_Quit_Real = NULL
static SDL_IME_Reset_t SDL_IME_Reset_Real = NULL
static SDL_IME_SetFocus_t SDL_IME_SetFocus_Real = NULL
static SDL_IME_UpdateTextInputArea_t SDL_IME_UpdateTextInputArea_Real = NULL
Typedef Documentation
SDL_IME_Init_t
typedef bool(* SDL_IME_Init_t) (void)
SDL_IME_ProcessKeyEvent_t
typedef bool(* SDL_IME_ProcessKeyEvent_t) (Uint32, Uint32, bool down)
SDL_IME_PumpEvents_t
typedef void(* SDL_IME_PumpEvents_t) (void)
SDL_IME_Quit_t
typedef void(* SDL_IME_Quit_t) (void)
SDL_IME_Reset_t
typedef void(* SDL_IME_Reset_t) (void)
SDL_IME_SetFocus_t
typedef void(* SDL_IME_SetFocus_t) (bool)
SDL_IME_UpdateTextInputArea_t
typedef void(* SDL_IME_UpdateTextInputArea_t) (SDL_Window *window)
Function Documentation
InitIME()
void InitIME (void) static
{
    static bool inited = false;
#ifdef HAVE_FCITX
    const char *im_module = SDL_getenv("SDL_IM_MODULE");
    const char *xmodifiers = SDL_getenv("XMODIFIERS");
#endif
    if (inited == true) {
        return;
    }
    inited = true;
    // See if fcitx IME support is being requested
#ifdef HAVE_FCITX
    if (!SDL_IME_Init_Real &&
        ((im_module && SDL_strcmp(im_module, "fcitx") == 0) ||
         (!im_module && xmodifiers && SDL_strstr(xmodifiers, "@im=fcitx") != NULL))) {
        SDL_IME_Init_Real = SDL_Fcitx_Init;
        SDL_IME_Quit_Real = SDL_Fcitx_Quit;
        SDL_IME_SetFocus_Real = SDL_Fcitx_SetFocus;
        SDL_IME_Reset_Real = SDL_Fcitx_Reset;
        SDL_IME_ProcessKeyEvent_Real = SDL_Fcitx_ProcessKeyEvent;
        SDL_IME_UpdateTextInputArea_Real = SDL_Fcitx_UpdateTextInputArea;
        SDL_IME_PumpEvents_Real = SDL_Fcitx_PumpEvents;
    }
#endif // HAVE_FCITX
    // default to IBus
#ifdef HAVE_IBUS_IBUS_H
    if (!SDL_IME_Init_Real) {
        SDL_IME_Init_Real = SDL_IBus_Init;
        SDL_IME_Quit_Real = SDL_IBus_Quit;
        SDL_IME_SetFocus_Real = SDL_IBus_SetFocus;
        SDL_IME_Reset_Real = SDL_IBus_Reset;
        SDL_IME_ProcessKeyEvent_Real = SDL_IBus_ProcessKeyEvent;
        SDL_IME_UpdateTextInputArea_Real = SDL_IBus_UpdateTextInputArea;
        SDL_IME_PumpEvents_Real = SDL_IBus_PumpEvents;
    }
#endif // HAVE_IBUS_IBUS_H
}
References NULL, SDL_Fcitx_Init(), SDL_Fcitx_ProcessKeyEvent(), SDL_Fcitx_PumpEvents(), SDL_Fcitx_Quit(), SDL_Fcitx_Reset(), SDL_Fcitx_SetFocus(), SDL_Fcitx_UpdateTextInputArea(), SDL_getenv(), SDL_IME_Init_Real, SDL_IME_ProcessKeyEvent_Real, SDL_IME_PumpEvents_Real, SDL_IME_Quit_Real, SDL_IME_Reset_Real, SDL_IME_SetFocus_Real, SDL_IME_UpdateTextInputArea_Real, SDL_strcmp(), and SDL_strstr().
Referenced by SDL_IME_Init().
SDL_IME_Init()
bool SDL_IME_Init (void)
{
    InitIME();
    if (SDL_IME_Init_Real) {
        if (SDL_IME_Init_Real()) {
            return true;
        }
        // uhoh, the IME implementation's init failed! Disable IME support.
        SDL_IME_Init_Real = NULL;
        SDL_IME_Quit_Real = NULL;
        SDL_IME_SetFocus_Real = NULL;
        SDL_IME_Reset_Real = NULL;
        SDL_IME_ProcessKeyEvent_Real = NULL;
        SDL_IME_UpdateTextInputArea_Real = NULL;
        SDL_IME_PumpEvents_Real = NULL;
    }
    return false;
}
References InitIME(), NULL, SDL_IME_Init_Real, SDL_IME_ProcessKeyEvent_Real, SDL_IME_PumpEvents_Real, SDL_IME_Quit_Real, SDL_IME_Reset_Real, SDL_IME_SetFocus_Real, and SDL_IME_UpdateTextInputArea_Real.
SDL_IME_ProcessKeyEvent()
bool SDL_IME_ProcessKeyEvent (Uint32 keysym, Uint32 keycode, bool down)
{
    if (SDL_IME_ProcessKeyEvent_Real) {
        return SDL_IME_ProcessKeyEvent_Real(keysym, keycode, down);
    }
    return false;
}
References keycode, and SDL_IME_ProcessKeyEvent_Real.
SDL_IME_PumpEvents()
void SDL_IME_PumpEvents (void)
{
    if (SDL_IME_PumpEvents_Real) {
        SDL_IME_PumpEvents_Real();
    }
}
References SDL_IME_PumpEvents_Real.
SDL_IME_Quit()
void SDL_IME_Quit (void)
{
    if (SDL_IME_Quit_Real) {
        SDL_IME_Quit_Real();
    }
}
References SDL_IME_Quit_Real.
SDL_IME_Reset()
void SDL_IME_Reset (void)
{
    if (SDL_IME_Reset_Real) {
        SDL_IME_Reset_Real();
    }
}
References SDL_IME_Reset_Real.
SDL_IME_SetFocus()
void SDL_IME_SetFocus (bool focused)
{
    if (SDL_IME_SetFocus_Real) {
        SDL_IME_SetFocus_Real(focused);
    }
}
References SDL_IME_SetFocus_Real.
SDL_IME_UpdateTextInputArea()
void SDL_IME_UpdateTextInputArea (SDL_Window * window)
{
    if (SDL_IME_UpdateTextInputArea_Real) {
        SDL_IME_UpdateTextInputArea_Real(window);
    }
}
References SDL_IME_UpdateTextInputArea_Real.
Variable Documentation
SDL_IME_Init_Real
SDL_IME_Init_t SDL_IME_Init_Real = NULL static
Referenced by InitIME(), and SDL_IME_Init().
SDL_IME_ProcessKeyEvent_Real
SDL_IME_ProcessKeyEvent_t SDL_IME_ProcessKeyEvent_Real = NULL static
Referenced by InitIME(), SDL_IME_Init(), and SDL_IME_ProcessKeyEvent().
SDL_IME_PumpEvents_Real
SDL_IME_PumpEvents_t SDL_IME_PumpEvents_Real = NULL static
Referenced by InitIME(), SDL_IME_Init(), and SDL_IME_PumpEvents().
SDL_IME_Quit_Real
SDL_IME_Quit_t SDL_IME_Quit_Real = NULL static
Referenced by InitIME(), SDL_IME_Init(), and SDL_IME_Quit().
SDL_IME_Reset_Real
SDL_IME_Reset_t SDL_IME_Reset_Real = NULL static
Referenced by InitIME(), SDL_IME_Init(), and SDL_IME_Reset().
SDL_IME_SetFocus_Real
SDL_IME_SetFocus_t SDL_IME_SetFocus_Real = NULL static
Referenced by InitIME(), SDL_IME_Init(), and SDL_IME_SetFocus().
SDL_IME_UpdateTextInputArea_Real
SDL_IME_UpdateTextInputArea_t SDL_IME_UpdateTextInputArea_Real = NULL static
Referenced by InitIME(), SDL_IME_Init(), and SDL_IME_UpdateTextInputArea().