SDL3: SDL-main/src/main/ngage/SDL_sysmain_main.cpp File Reference
SDL_sysmain_main.cpp File Reference
#include "SDL_internal.h"
#include <e32std.h>
#include <estlib.h>
#include <stdlib.h>
#include <stdio.h>
#include "SDL_sysmain_main.hpp"
#include "../../audio/ngage/SDL_ngageaudio.hpp"
#include "../../render/ngage/SDL_render_ngage_c.hpp"
Functions
GLDEF_C TInt E32Main ()
SDL_AppResult SDL_AppEvent (void *appstate, SDL_Event *event)
SDL_AppResult SDL_AppInit (void **appstate, int argc, char *argv[])
SDL_AppResult SDL_AppIterate (void *appstate)
void SDL_AppQuit (void *appstate, SDL_AppResult result)
Variables
static bool callbacks_initialized = false
CRenderer * gRenderer = 0
Function Documentation
E32Main()
GLDEF_C TInt E32Main ()
{
    // Get args and environment.
    int argc = 1;
    char *argv[] = { "game", NULL };
    char **envp = NULL;
    // Create lvalue variables for __crt0 arguments.
    char **argv_lvalue = argv;
    char **envp_lvalue = envp;
    CTrapCleanup *cleanup = CTrapCleanup::New();
    if (!cleanup)
    {
        return KErrNoMemory;
    }
    TRAPD(err,
    {
        CActiveScheduler *scheduler = new (ELeave) CActiveScheduler();
        CleanupStack::PushL(scheduler);
        CActiveScheduler::Install(scheduler);
        TInt posixErr = SpawnPosixServerThread();
        if (posixErr != KErrNone)
        {
            SDL_Log("Error: Failed to spawn POSIX server thread: %d", posixErr);
            User::Leave(posixErr);
        }
        __crt0(argc, argv_lvalue, envp_lvalue);
        // Increase heap size.
        RHeap *newHeap = User::ChunkHeap(NULL, 7500000, 7500000, KMinHeapGrowBy);
        if (!newHeap)
        {
            SDL_Log("Error: Failed to create new heap");
            User::Leave(KErrNoMemory);
        }
        CleanupStack::PushL(newHeap);
        RHeap *oldHeap = User::SwitchHeap(newHeap);
        TInt targetLatency = 225;
        InitAudio(&targetLatency);
        // Wait until audio is ready.
        while (!AudioIsReady())
        {
            User::After(100000); // 100ms.
        }
        // Create and start the rendering backend.
        gRenderer = CRenderer::NewL();
        CleanupStack::PushL(gRenderer);
        // Create and start the SDL main runner.
        CSDLmain *mainApp = CSDLmain::NewL();
        CleanupStack::PushL(mainApp);
        mainApp->Start();
        // Start the active scheduler to handle events.
        CActiveScheduler::Start();
        CleanupStack::PopAndDestroy(gRenderer);
        CleanupStack::PopAndDestroy(mainApp);
        User::SwitchHeap(oldHeap);
        CleanupStack::PopAndDestroy(newHeap);
        CleanupStack::PopAndDestroy(scheduler);
    });
    if (err != KErrNone)
    {
        SDL_Log("Error: %d", err);
    }
    return err;
}
References AudioIsReady(), gRenderer, InitAudio(), CRenderer::NewL(), CSDLmain::NewL(), NULL, SDL_Log(), and CSDLmain::Start().
SDL_AppEvent()
SDL_AppResult SDL_AppEvent (void * appstate, SDL_Event * event) extern
Referenced by CSDLmain::RunL().
SDL_AppInit()
SDL_AppResult SDL_AppInit (void ** appstate, int argc, char * argv[]) extern
Referenced by CSDLmain::RunL().
SDL_AppIterate()
SDL_AppResult SDL_AppIterate (void * appstate) extern
Referenced by CSDLmain::RunL().
SDL_AppQuit()
void SDL_AppQuit (void * appstate, SDL_AppResult result) extern
Referenced by CSDLmain::RunL().
Variable Documentation
callbacks_initialized
bool callbacks_initialized = false static
Referenced by CSDLmain::RunL().
gRenderer
CRenderer* gRenderer = 0
Referenced by E32Main().