SDL3: SDL-main/src/joystick/SDL_joystick_c.h File Reference
SDL_joystick_c.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_GamepadMapping
struct SDL_InputMapping
struct SDL_vidpid_list
Typedefs
typedef struct SDL_GamepadMapping SDL_GamepadMapping
typedef struct SDL_InputMapping SDL_InputMapping
Enumerations
enum EMappingKind { EMappingKind_None , EMappingKind_Button , EMappingKind_Axis , EMappingKind_Hat }
Functions
void SDL_AssertJoysticksLocked (void) SDL_ASSERT_CAPABILITY(SDL_joystick_lock)
SDL_GUID SDL_CreateJoystickGUID (Uint16 bus, Uint16 vendor, Uint16 product, Uint16 version, const char *vendor_name, const char *product_name, Uint8 driver_signature, Uint8 driver_data)
SDL_GUID SDL_CreateJoystickGUIDForName (const char *name)
char * SDL_CreateJoystickName (Uint16 vendor, Uint16 product, const char *vendor_name, const char *product_name)
void SDL_FreeVIDPIDList (SDL_vidpid_list *list)
SDL_GamepadType SDL_GetGamepadTypeFromGUID (SDL_GUID guid, const char *name)
SDL_GamepadType SDL_GetGamepadTypeFromVIDPID (Uint16 vendor, Uint16 product, const char *name, bool forUI)
const struct SDL_SteamVirtualGamepadInfo * SDL_GetJoystickVirtualGamepadInfoForID (SDL_JoystickID instance_id)
bool SDL_InitJoysticks (void)
bool SDL_IsJoystickAmazonLunaController (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickBeingAdded (void)
bool SDL_IsJoystickBluetoothXboxOne (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickDualSenseEdge (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickFlydigiController (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickGameCube (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickGoogleStadiaController (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickHIDAPI (SDL_GUID guid)
bool SDL_IsJoystickHoriSteamController (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickMFI (SDL_GUID guid)
bool SDL_IsJoystickNintendoSwitchJoyCon (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickNintendoSwitchJoyConGrip (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickNintendoSwitchJoyConLeft (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickNintendoSwitchJoyConPair (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickNintendoSwitchJoyConRight (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickNintendoSwitchPro (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickNintendoSwitchProInputOnly (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickNVIDIASHIELDController (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickPS4 (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickPS5 (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickRAWINPUT (SDL_GUID guid)
bool SDL_IsJoystickSInputController (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickSteamController (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickSteamDeck (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickSteamVirtualGamepad (Uint16 vendor_id, Uint16 product_id, Uint16 version)
bool SDL_IsJoystickValid (SDL_Joystick *joystick)
bool SDL_IsJoystickVIRTUAL (SDL_GUID guid)
bool SDL_IsJoystickWGI (SDL_GUID guid)
bool SDL_IsJoystickWheel (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickXboxOne (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickXboxOneElite (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickXboxSeriesX (Uint16 vendor_id, Uint16 product_id)
bool SDL_IsJoystickXInput (SDL_GUID guid)
bool SDL_JoystickGUIDUsesVersion (SDL_GUID guid)
bool SDL_JoystickHandledByAnotherDriver (struct SDL_JoystickDriver *driver, Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
bool SDL_JoysticksInitialized (void)
bool SDL_JoysticksLocked (void)
bool SDL_JoysticksOpened (void)
bool SDL_JoysticksQuitting (void)
void SDL_LoadVIDPIDList (SDL_vidpid_list *list)
void SDL_LoadVIDPIDListFromHints (SDL_vidpid_list *list, const char *included_list, const char *excluded_list)
void SDL_PrivateJoystickAdded (SDL_JoystickID instance_id)
void SDL_PrivateJoystickAddSensor (SDL_Joystick *joystick, SDL_SensorType type, float rate)
void SDL_PrivateJoystickAddTouchpad (SDL_Joystick *joystick, int nfingers)
void SDL_PrivateJoystickForceRecentering (SDL_Joystick *joystick)
bool SDL_PrivateJoystickGetAutoGamepadMapping (SDL_JoystickID instance_id, SDL_GamepadMapping *out)
void SDL_PrivateJoystickRemoved (SDL_JoystickID instance_id)
void SDL_PrivateJoystickSensorRate (SDL_Joystick *joystick, SDL_SensorType type, float rate)
void SDL_QuitJoysticks (void)
void SDL_SendJoystickAxis (Uint64 timestamp, SDL_Joystick *joystick, Uint8 axis, Sint16 value)
void SDL_SendJoystickBall (Uint64 timestamp, SDL_Joystick *joystick, Uint8 ball, Sint16 xrel, Sint16 yrel)
void SDL_SendJoystickButton (Uint64 timestamp, SDL_Joystick *joystick, Uint8 button, bool down)
void SDL_SendJoystickHat (Uint64 timestamp, SDL_Joystick *joystick, Uint8 hat, Uint8 value)
void SDL_SendJoystickPowerInfo (SDL_Joystick *joystick, SDL_PowerState state, int percent)
void SDL_SendJoystickSensor (Uint64 timestamp, SDL_Joystick *joystick, SDL_SensorType type, Uint64 sensor_timestamp, const float *data, int num_values)
void SDL_SendJoystickTouchpad (Uint64 timestamp, SDL_Joystick *joystick, int touchpad, int finger, bool down, float x, float y, float pressure)
void SDL_SetJoystickGUIDCRC (SDL_GUID *guid, Uint16 crc)
void SDL_SetJoystickGUIDProduct (SDL_GUID *guid, Uint16 product)
void SDL_SetJoystickGUIDVendor (SDL_GUID *guid, Uint16 vendor)
void SDL_SetJoystickGUIDVersion (SDL_GUID *guid, Uint16 version)
bool SDL_ShouldIgnoreJoystick (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
bool SDL_VIDPIDInList (Uint16 vendor_id, Uint16 product_id, const SDL_vidpid_list *list)
Typedef Documentation
SDL_GamepadMapping
typedef struct SDL_GamepadMapping SDL_GamepadMapping
SDL_InputMapping
typedef struct SDL_InputMapping SDL_InputMapping
Enumeration Type Documentation
EMappingKind
enum EMappingKind
Enumerator
EMappingKind_None
EMappingKind_Button
EMappingKind_Axis
EMappingKind_Hat
{
    EMappingKind_None,
    EMappingKind_Button,
    EMappingKind_Axis,
    EMappingKind_Hat,
} EMappingKind;
Function Documentation
SDL_AssertJoysticksLocked()
void SDL_AssertJoysticksLocked (void) extern
{
    SDL_assert(SDL_JoysticksLocked());
}
References SDL_assert, and SDL_JoysticksLocked().
Referenced by AddMappingChangeTracking(), AddVirtualGamepadInfo(), AdjustSensorOrientation(), AttemptSensorFusion(), CleanupSensorFusion(), CreateMappingString(), HandleJoystickAxis(), HandleJoystickButton(), HandleJoystickHat(), HasMappingChangeTracking(), PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_FindFreePlayerIndex(), SDL_FreeSteamVirtualGamepadInfo(), SDL_GamepadEventWatcher(), SDL_GamepadHandleDelayedGuideButton(), SDL_GetDriverAndJoystickIndex(), SDL_GetJoystickIDForPlayerIndex(), SDL_GetPlayerIndexForJoystickID(), SDL_GetSteamVirtualGamepadInfo(), SDL_InitGamepadMappings(), SDL_InitSteamVirtualGamepadInfo(), SDL_IsJoystickValid(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGamepadRemoved(), SDL_PrivateGetGamepadMapping(), SDL_PrivateGetGamepadMappingForNameAndGUID(), SDL_PrivateJoystickAdded(), SDL_PrivateJoystickAddSensor(), SDL_PrivateJoystickAddTouchpad(), SDL_PrivateJoystickForceRecentering(), SDL_PrivateJoystickRemoved(), SDL_PrivateJoystickSensorRate(), SDL_PrivateLoadButtonMapping(), SDL_PrivateMatchGamepadMappingForGUID(), SDL_PrivateParseGamepadElement(), SDL_QuitGamepadMappings(), SDL_QuitSteamVirtualGamepadInfo(), SDL_SendGamepadAxis(), SDL_SendGamepadButton(), SDL_SendJoystickAxis(), SDL_SendJoystickBall(), SDL_SendJoystickButton(), SDL_SendJoystickHat(), SDL_SendJoystickPowerInfo(), SDL_SendJoystickSensor(), SDL_SendJoystickTouchpad(), SDL_SetJoystickIDForPlayerIndex(), SDL_SteamVirtualGamepadEnabled(), SDL_UpdateGamepadFaceStyle(), SDL_UpdateGamepadType(), SDL_UpdateSteamVirtualGamepadInfo(), and ShouldAttemptSensorFusion().
SDL_CreateJoystickGUID()
SDL_GUID SDL_CreateJoystickGUID (Uint16 bus, Uint16 vendor, Uint16 product, Uint16 version, const char * vendor_name, const char * product_name, Uint8 driver_signature, Uint8 driver_data) extern
{
    SDL_GUID guid;
    Uint16 *guid16 = (Uint16 *)guid.data;
    Uint16 crc = 0;
    SDL_zero(guid);
    if (vendor_name && *vendor_name && product_name && *product_name) {
        crc = SDL_crc16(crc, vendor_name, SDL_strlen(vendor_name));
        crc = SDL_crc16(crc, " ", 1);
        crc = SDL_crc16(crc, product_name, SDL_strlen(product_name));
    } else if (product_name) {
        crc = SDL_crc16(crc, product_name, SDL_strlen(product_name));
    }
    // We only need 16 bits for each of these; space them out to fill 128.
    // Byteswap so devices get same GUID on little/big endian platforms.
    *guid16++ = SDL_Swap16LE(bus);
    *guid16++ = SDL_Swap16LE(crc);
    if (vendor) {
        *guid16++ = SDL_Swap16LE(vendor);
        *guid16++ = 0;
        *guid16++ = SDL_Swap16LE(product);
        *guid16++ = 0;
        *guid16++ = SDL_Swap16LE(version);
        guid.data[14] = driver_signature;
        guid.data[15] = driver_data;
    } else {
        size_t available_space = sizeof(guid.data) - 4;
        if (driver_signature) {
            available_space -= 2;
            guid.data[14] = driver_signature;
            guid.data[15] = driver_data;
        }
        if (product_name) {
            SDL_strlcpy((char *)guid16, product_name, available_space);
        }
    }
    return guid;
}
References SDL_GUID::data, SDL_crc16(), SDL_strlcpy(), SDL_strlen(), SDL_Swap16LE, and SDL_zero.
Referenced by SDL_CreateJoystickGUIDForName().
SDL_CreateJoystickGUIDForName()
SDL_GUID SDL_CreateJoystickGUIDForName (const char * name) extern
{
    return SDL_CreateJoystickGUID(SDL_HARDWARE_BUS_UNKNOWN, 0, 0, 0, NULL, name, 0, 0);
}
References NULL, SDL_CreateJoystickGUID(), and SDL_HARDWARE_BUS_UNKNOWN.
SDL_CreateJoystickName()
char * SDL_CreateJoystickName (Uint16 vendor, Uint16 product, const char * vendor_name, const char * product_name) extern
{
    const char *custom_name = GuessControllerName(vendor, product);
    if (custom_name) {
        return SDL_strdup(custom_name);
    }
    return SDL_CreateDeviceName(vendor, product, vendor_name, product_name, "Controller");
}
References GuessControllerName(), SDL_CreateDeviceName(), and SDL_strdup().
SDL_FreeVIDPIDList()
void SDL_FreeVIDPIDList (SDL_vidpid_list * list) extern
{
    if (list->included_hint_name) {
        SDL_RemoveHintCallback(list->included_hint_name, SDL_VIDPIDIncludedHintChanged, list);
    }
    if (list->excluded_hint_name) {
        SDL_RemoveHintCallback(list->excluded_hint_name, SDL_VIDPIDExcludedHintChanged, list);
    }
    if (list->included_entries) {
        SDL_free(list->included_entries);
        list->included_entries = NULL;
        list->num_included_entries = 0;
        list->max_included_entries = 0;
    }
    if (list->excluded_entries) {
        SDL_free(list->excluded_entries);
        list->excluded_entries = NULL;
        list->num_excluded_entries = 0;
        list->max_excluded_entries = 0;
    }
    list->initialized = false;
}
References SDL_vidpid_list::excluded_entries, SDL_vidpid_list::excluded_hint_name, SDL_vidpid_list::included_entries, SDL_vidpid_list::included_hint_name, SDL_vidpid_list::initialized, SDL_vidpid_list::max_excluded_entries, SDL_vidpid_list::max_included_entries, NULL, SDL_vidpid_list::num_excluded_entries, SDL_vidpid_list::num_included_entries, SDL_free(), SDL_RemoveHintCallback(), SDL_VIDPIDExcludedHintChanged(), and SDL_VIDPIDIncludedHintChanged().
Referenced by SDL_QuitGamepadMappings(), SDL_QuitJoysticks(), and ShouldAttemptSensorFusion().
SDL_GetGamepadTypeFromGUID()
SDL_GamepadType SDL_GetGamepadTypeFromGUID (SDL_GUID guid, const char * name) extern
{
    SDL_GamepadType type;
    Uint16 vendor, product;
    SDL_GetJoystickGUIDInfo(guid, &vendor, &product, NULL, NULL);
    type = SDL_GetGamepadTypeFromVIDPID(vendor, product, name, true);
    if (type == SDL_GAMEPAD_TYPE_STANDARD) {
        if (SDL_IsJoystickXInput(guid)) {
            // This is probably an Xbox One controller
            return SDL_GAMEPAD_TYPE_XBOXONE;
        }
#ifdef SDL_JOYSTICK_HIDAPI
        if (SDL_IsJoystickHIDAPI(guid)) {
            return HIDAPI_GetGamepadTypeFromGUID(guid);
        }
#endif // SDL_JOYSTICK_HIDAPI
    }
    return type;
}
References HIDAPI_GetGamepadTypeFromGUID(), NULL, SDL_GAMEPAD_TYPE_STANDARD, SDL_GAMEPAD_TYPE_XBOXONE, SDL_GetGamepadTypeFromVIDPID(), SDL_GetJoystickGUIDInfo(), SDL_IsJoystickHIDAPI(), and SDL_IsJoystickXInput().
Referenced by SDL_CreateMappingForHIDAPIGamepad(), SDL_GetRealGamepadType(), and SDL_GetRealGamepadTypeForID().
SDL_GetGamepadTypeFromVIDPID()
SDL_GamepadType SDL_GetGamepadTypeFromVIDPID (Uint16 vendor, Uint16 product, const char * name, bool forUI) extern
{
    SDL_GamepadType type = SDL_GAMEPAD_TYPE_STANDARD;
    if (vendor == 0x0000 && product == 0x0000) {
        // Some devices are only identifiable by their name
        if (name &&
            (SDL_strcmp(name, "Lic Pro Controller") == 0 ||
             SDL_strcmp(name, "Nintendo Wireless Gamepad") == 0 ||
             SDL_strcmp(name, "Wireless Gamepad") == 0)) {
            // HORI or PowerA Switch Pro Controller clone
            type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO;
        }
    } else if (vendor == 0x0001 && product == 0x0001) {
        type = SDL_GAMEPAD_TYPE_STANDARD;
    } else if (vendor == USB_VENDOR_NINTENDO && product == USB_PRODUCT_NINTENDO_SWITCH_JOYCON_LEFT) {
        type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT;
    } else if (vendor == USB_VENDOR_NINTENDO && product == USB_PRODUCT_NINTENDO_SWITCH_JOYCON_RIGHT) {
        if (name && SDL_strstr(name, "NES Controller") != NULL) {
            // We don't have a type for the Nintendo Online NES Controller
            type = SDL_GAMEPAD_TYPE_STANDARD;
        } else {
            type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT;
        }
    } else if (vendor == USB_VENDOR_NINTENDO && product == USB_PRODUCT_NINTENDO_SWITCH_JOYCON_GRIP) {
        if (name && SDL_strstr(name, "(L)") != NULL) {
            type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT;
        } else {
            type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT;
        }
    } else if (vendor == USB_VENDOR_NINTENDO && product == USB_PRODUCT_NINTENDO_SWITCH_JOYCON_PAIR) {
        type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR;
    } else if (forUI && SDL_IsJoystickGameCube(vendor, product)) {
        type = SDL_GAMEPAD_TYPE_GAMECUBE;
    } else {
        switch (GuessControllerType(vendor, product)) {
        case k_eControllerType_XBox360Controller:
            type = SDL_GAMEPAD_TYPE_XBOX360;
            break;
        case k_eControllerType_XBoxOneController:
            type = SDL_GAMEPAD_TYPE_XBOXONE;
            break;
        case k_eControllerType_PS3Controller:
            type = SDL_GAMEPAD_TYPE_PS3;
            break;
        case k_eControllerType_PS4Controller:
            type = SDL_GAMEPAD_TYPE_PS4;
            break;
        case k_eControllerType_PS5Controller:
            type = SDL_GAMEPAD_TYPE_PS5;
            break;
        case k_eControllerType_XInputPS4Controller:
            if (forUI) {
                type = SDL_GAMEPAD_TYPE_PS4;
            } else {
                type = SDL_GAMEPAD_TYPE_STANDARD;
            }
            break;
        case k_eControllerType_SwitchProController:
        case k_eControllerType_SwitchInputOnlyController:
            type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO;
            break;
        case k_eControllerType_XInputSwitchController:
            if (forUI) {
                type = SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO;
            } else {
                type = SDL_GAMEPAD_TYPE_STANDARD;
            }
            break;
        default:
            break;
        }
    }
    return type;
}
References GuessControllerType(), k_eControllerType_PS3Controller, k_eControllerType_PS4Controller, k_eControllerType_PS5Controller, k_eControllerType_SwitchInputOnlyController, k_eControllerType_SwitchProController, k_eControllerType_XBox360Controller, k_eControllerType_XBoxOneController, k_eControllerType_XInputPS4Controller, k_eControllerType_XInputSwitchController, NULL, SDL_GAMEPAD_TYPE_GAMECUBE, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO, SDL_GAMEPAD_TYPE_PS3, SDL_GAMEPAD_TYPE_PS4, SDL_GAMEPAD_TYPE_PS5, SDL_GAMEPAD_TYPE_STANDARD, SDL_GAMEPAD_TYPE_XBOX360, SDL_GAMEPAD_TYPE_XBOXONE, SDL_IsJoystickGameCube(), SDL_strcmp(), SDL_strstr(), USB_PRODUCT_NINTENDO_SWITCH_JOYCON_GRIP, USB_PRODUCT_NINTENDO_SWITCH_JOYCON_LEFT, USB_PRODUCT_NINTENDO_SWITCH_JOYCON_PAIR, USB_PRODUCT_NINTENDO_SWITCH_JOYCON_RIGHT, and USB_VENDOR_NINTENDO.
Referenced by SDL_CreateDeviceName(), and SDL_GetGamepadTypeFromGUID().
SDL_GetJoystickVirtualGamepadInfoForID()
const struct SDL_SteamVirtualGamepadInfo * SDL_GetJoystickVirtualGamepadInfoForID (SDL_JoystickID instance_id) extern
{
    SDL_JoystickDriver *driver;
    int device_index;
    const SDL_SteamVirtualGamepadInfo *info = NULL;
    if (SDL_SteamVirtualGamepadEnabled() &&
        SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        info = SDL_GetSteamVirtualGamepadInfo(driver->GetDeviceSteamVirtualGamepadSlot(device_index));
    }
    return info;
}
References SDL_JoystickDriver::GetDeviceSteamVirtualGamepadSlot, NULL, SDL_GetDriverAndJoystickIndex(), SDL_GetSteamVirtualGamepadInfo(), and SDL_SteamVirtualGamepadEnabled().
Referenced by SDL_GetGamepadType(), SDL_GetJoystickName(), SDL_GetJoystickNameForID(), SDL_GetJoystickProduct(), SDL_GetJoystickProductForID(), SDL_GetJoystickVendor(), SDL_GetJoystickVendorForID(), SDL_GetRealGamepadTypeForID(), SDL_OpenJoystick(), and SendSteamHandleUpdateEvents().
SDL_InitJoysticks()
bool SDL_InitJoysticks (void) extern
{
    int i;
    bool result = false;
    // Create the joystick list lock
    if (SDL_joystick_lock == NULL) {
        SDL_joystick_lock = SDL_CreateMutex();
    }
    if (!SDL_InitSubSystem(SDL_INIT_EVENTS)) {
        return false;
    }
    SDL_LockJoysticks();
    SDL_joysticks_initialized = true;
    SDL_LoadVIDPIDList(&old_xboxone_controllers);
    SDL_LoadVIDPIDList(&arcadestick_devices);
    SDL_LoadVIDPIDList(&blacklist_devices);
    SDL_LoadVIDPIDList(&flightstick_devices);
    SDL_LoadVIDPIDList(&gamecube_devices);
    SDL_LoadVIDPIDList(&rog_gamepad_mice);
    SDL_LoadVIDPIDList(&throttle_devices);
    SDL_LoadVIDPIDList(&wheel_devices);
    SDL_LoadVIDPIDList(&zero_centered_devices);
    SDL_InitGamepadMappings();
    // See if we should allow joystick events while in the background
    SDL_AddHintCallback(SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS,
                        SDL_JoystickAllowBackgroundEventsChanged, NULL);
    SDL_InitSteamVirtualGamepadInfo();
    for (i = 0; i < SDL_arraysize(SDL_joystick_drivers); ++i) {
        if (SDL_joystick_drivers[i]->Init()) {
            result = true;
        }
    }
    SDL_UnlockJoysticks();
    if (!result) {
        SDL_QuitJoysticks();
    }
    return result;
}
References arcadestick_devices, blacklist_devices, flightstick_devices, gamecube_devices, NULL, old_xboxone_controllers, rog_gamepad_mice, SDL_AddHintCallback(), SDL_arraysize, SDL_CreateMutex(), SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, SDL_INIT_EVENTS, SDL_InitGamepadMappings(), SDL_InitSteamVirtualGamepadInfo(), SDL_InitSubSystem(), SDL_joystick_drivers, SDL_joystick_lock, SDL_JoystickAllowBackgroundEventsChanged(), SDL_joysticks_initialized, SDL_LoadVIDPIDList(), SDL_LockJoysticks(), SDL_QuitJoysticks(), SDL_UnlockJoysticks(), throttle_devices, wheel_devices, and zero_centered_devices.
Referenced by SDL_InitSubSystem().
SDL_IsJoystickAmazonLunaController()
bool SDL_IsJoystickAmazonLunaController (Uint16 vendor_id, Uint16 product_id) extern
{
    return ((vendor_id == USB_VENDOR_AMAZON && product_id == USB_PRODUCT_AMAZON_LUNA_CONTROLLER) ||
            (vendor_id == BLUETOOTH_VENDOR_AMAZON && product_id == BLUETOOTH_PRODUCT_LUNA_CONTROLLER));
}
References BLUETOOTH_PRODUCT_LUNA_CONTROLLER, BLUETOOTH_VENDOR_AMAZON, USB_PRODUCT_AMAZON_LUNA_CONTROLLER, and USB_VENDOR_AMAZON.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickBeingAdded()
bool SDL_IsJoystickBeingAdded (void) extern
{
    return SDL_joystick_being_added;
}
References SDL_joystick_being_added.
Referenced by SDL_PrivateGamepadAdded(), and SDL_PrivateGamepadRemapped().
SDL_IsJoystickBluetoothXboxOne()
bool SDL_IsJoystickBluetoothXboxOne (Uint16 vendor_id, Uint16 product_id) extern
{
    if (vendor_id == USB_VENDOR_MICROSOFT) {
        if (product_id == USB_PRODUCT_XBOX_ONE_ADAPTIVE_BLUETOOTH ||
            product_id == USB_PRODUCT_XBOX_ONE_ADAPTIVE_BLE ||
            product_id == USB_PRODUCT_XBOX_ONE_S_REV1_BLUETOOTH ||
            product_id == USB_PRODUCT_XBOX_ONE_S_REV2_BLUETOOTH ||
            product_id == USB_PRODUCT_XBOX_ONE_S_REV2_BLE ||
            product_id == USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLUETOOTH ||
            product_id == USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLE ||
            product_id == USB_PRODUCT_XBOX_SERIES_X_BLE) {
            return true;
        }
    }
    return false;
}
References USB_PRODUCT_XBOX_ONE_ADAPTIVE_BLE, USB_PRODUCT_XBOX_ONE_ADAPTIVE_BLUETOOTH, USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLE, USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLUETOOTH, USB_PRODUCT_XBOX_ONE_S_REV1_BLUETOOTH, USB_PRODUCT_XBOX_ONE_S_REV2_BLE, USB_PRODUCT_XBOX_ONE_S_REV2_BLUETOOTH, USB_PRODUCT_XBOX_SERIES_X_BLE, and USB_VENDOR_MICROSOFT.
SDL_IsJoystickDualSenseEdge()
bool SDL_IsJoystickDualSenseEdge (Uint16 vendor_id, Uint16 product_id) extern
{
    if (vendor_id == USB_VENDOR_SONY) {
        if (product_id == USB_PRODUCT_SONY_DS5_EDGE) {
            return true;
        }
    }
    return false;
}
References USB_PRODUCT_SONY_DS5_EDGE, and USB_VENDOR_SONY.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickFlydigiController()
bool SDL_IsJoystickFlydigiController (Uint16 vendor_id, Uint16 product_id) extern
{
    return vendor_id == USB_VENDOR_FLYDIGI && product_id == USB_PRODUCT_FLYDIGI_GAMEPAD;
}
References USB_PRODUCT_FLYDIGI_GAMEPAD, and USB_VENDOR_FLYDIGI.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickGameCube()
bool SDL_IsJoystickGameCube (Uint16 vendor_id, Uint16 product_id) extern
{
    return SDL_VIDPIDInList(vendor_id, product_id, &gamecube_devices);
}
References gamecube_devices, and SDL_VIDPIDInList().
Referenced by SDL_CreateMappingForHIDAPIGamepad(), SDL_GetGamepadTypeFromVIDPID(), and SDL_PrivateAddGamepadMapping().
SDL_IsJoystickGoogleStadiaController()
bool SDL_IsJoystickGoogleStadiaController (Uint16 vendor_id, Uint16 product_id) extern
{
    return vendor_id == USB_VENDOR_GOOGLE && product_id == USB_PRODUCT_GOOGLE_STADIA_CONTROLLER;
}
References USB_PRODUCT_GOOGLE_STADIA_CONTROLLER, and USB_VENDOR_GOOGLE.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickHIDAPI()
bool SDL_IsJoystickHIDAPI (SDL_GUID guid) extern
{
    return (guid.data[14] == 'h') ? true : false;
}
References SDL_GUID::data, and true.
Referenced by SDL_GetGamepadTypeFromGUID(), SDL_GetJoystickGUIDType(), SDL_OpenJoystick(), SDL_PrivateGetGamepadMappingForGUID(), and SDL_PrivateLoadButtonMapping().
SDL_IsJoystickHoriSteamController()
bool SDL_IsJoystickHoriSteamController (Uint16 vendor_id, Uint16 product_id) extern
{
    return vendor_id == USB_VENDOR_HORI && (product_id == USB_PRODUCT_HORI_STEAM_CONTROLLER || product_id == USB_PRODUCT_HORI_STEAM_CONTROLLER_BT);
}
References USB_PRODUCT_HORI_STEAM_CONTROLLER, USB_PRODUCT_HORI_STEAM_CONTROLLER_BT, and USB_VENDOR_HORI.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickMFI()
bool SDL_IsJoystickMFI (SDL_GUID guid) extern
{
    return (guid.data[14] == 'm') ? true : false;
}
References SDL_GUID::data, and true.
Referenced by SDL_JoystickGUIDUsesVersion().
SDL_IsJoystickNintendoSwitchJoyCon()
bool SDL_IsJoystickNintendoSwitchJoyCon (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_SwitchJoyConLeft || eType == k_eControllerType_SwitchJoyConRight;
}
References GuessControllerType(), k_eControllerType_SwitchJoyConLeft, and k_eControllerType_SwitchJoyConRight.
SDL_IsJoystickNintendoSwitchJoyConGrip()
bool SDL_IsJoystickNintendoSwitchJoyConGrip (Uint16 vendor_id, Uint16 product_id) extern
{
    return vendor_id == USB_VENDOR_NINTENDO && product_id == USB_PRODUCT_NINTENDO_SWITCH_JOYCON_GRIP;
}
References USB_PRODUCT_NINTENDO_SWITCH_JOYCON_GRIP, and USB_VENDOR_NINTENDO.
SDL_IsJoystickNintendoSwitchJoyConLeft()
bool SDL_IsJoystickNintendoSwitchJoyConLeft (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_SwitchJoyConLeft;
}
References GuessControllerType(), and k_eControllerType_SwitchJoyConLeft.
SDL_IsJoystickNintendoSwitchJoyConPair()
bool SDL_IsJoystickNintendoSwitchJoyConPair (Uint16 vendor_id, Uint16 product_id) extern
{
    return vendor_id == USB_VENDOR_NINTENDO && product_id == USB_PRODUCT_NINTENDO_SWITCH_JOYCON_PAIR;
}
References USB_PRODUCT_NINTENDO_SWITCH_JOYCON_PAIR, and USB_VENDOR_NINTENDO.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickNintendoSwitchJoyConRight()
bool SDL_IsJoystickNintendoSwitchJoyConRight (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_SwitchJoyConRight;
}
References GuessControllerType(), and k_eControllerType_SwitchJoyConRight.
SDL_IsJoystickNintendoSwitchPro()
bool SDL_IsJoystickNintendoSwitchPro (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_SwitchProController || eType == k_eControllerType_SwitchInputOnlyController;
}
References GuessControllerType(), k_eControllerType_SwitchInputOnlyController, and k_eControllerType_SwitchProController.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickNintendoSwitchProInputOnly()
bool SDL_IsJoystickNintendoSwitchProInputOnly (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_SwitchInputOnlyController;
}
References GuessControllerType(), and k_eControllerType_SwitchInputOnlyController.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickNVIDIASHIELDController()
bool SDL_IsJoystickNVIDIASHIELDController (Uint16 vendor_id, Uint16 product_id) extern
{
    return (vendor_id == USB_VENDOR_NVIDIA &&
            (product_id == USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V103 ||
             product_id == USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V104));
}
References USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V103, USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V104, and USB_VENDOR_NVIDIA.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickPS4()
bool SDL_IsJoystickPS4 (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_PS4Controller;
}
References GuessControllerType(), and k_eControllerType_PS4Controller.
SDL_IsJoystickPS5()
bool SDL_IsJoystickPS5 (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_PS5Controller;
}
References GuessControllerType(), and k_eControllerType_PS5Controller.
SDL_IsJoystickRAWINPUT()
bool SDL_IsJoystickRAWINPUT (SDL_GUID guid) extern
{
    return (guid.data[14] == 'r') ? true : false;
}
References SDL_GUID::data, and true.
Referenced by SDL_OpenJoystick(), and SDL_PrivateGetGamepadMappingForGUID().
SDL_IsJoystickSInputController()
bool SDL_IsJoystickSInputController (Uint16 vendor_id, Uint16 product_id) extern
{
    if (vendor_id == USB_VENDOR_RASPBERRYPI) {
        if (product_id == USB_PRODUCT_HANDHELDLEGEND_SINPUT_GENERIC ||
            product_id == USB_PRODUCT_HANDHELDLEGEND_PROGCC ||
            product_id == USB_PRODUCT_HANDHELDLEGEND_GCULTIMATE ||
            product_id == USB_PRODUCT_BONJIRICHANNEL_FIREBIRD) {
            return true;
        }
    }
    return false;
}
References USB_PRODUCT_BONJIRICHANNEL_FIREBIRD, USB_PRODUCT_HANDHELDLEGEND_GCULTIMATE, USB_PRODUCT_HANDHELDLEGEND_PROGCC, USB_PRODUCT_HANDHELDLEGEND_SINPUT_GENERIC, and USB_VENDOR_RASPBERRYPI.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickSteamController()
bool SDL_IsJoystickSteamController (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_SteamController || eType == k_eControllerType_SteamControllerV2;
}
References GuessControllerType(), k_eControllerType_SteamController, and k_eControllerType_SteamControllerV2.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickSteamDeck()
bool SDL_IsJoystickSteamDeck (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_SteamControllerNeptune;
}
References GuessControllerType(), and k_eControllerType_SteamControllerNeptune.
SDL_IsJoystickSteamVirtualGamepad()
bool SDL_IsJoystickSteamVirtualGamepad (Uint16 vendor_id, Uint16 product_id, Uint16 version) extern
{
#ifdef SDL_PLATFORM_MACOS
    return (vendor_id == USB_VENDOR_MICROSOFT && product_id == USB_PRODUCT_XBOX360_WIRED_CONTROLLER && version == 0);
#else
    return (vendor_id == USB_VENDOR_VALVE && product_id == USB_PRODUCT_STEAM_VIRTUAL_GAMEPAD);
#endif
}
References USB_PRODUCT_STEAM_VIRTUAL_GAMEPAD, USB_PRODUCT_XBOX360_WIRED_CONTROLLER, USB_VENDOR_MICROSOFT, and USB_VENDOR_VALVE.
Referenced by SDL_ShouldIgnoreGamepad().
SDL_IsJoystickValid()
bool SDL_IsJoystickValid (SDL_Joystick * joystick) extern
{
    SDL_AssertJoysticksLocked();
    return SDL_ObjectValid(joystick, SDL_OBJECT_TYPE_JOYSTICK);
}
References SDL_AssertJoysticksLocked(), SDL_OBJECT_TYPE_JOYSTICK, and SDL_ObjectValid().
Referenced by SDL_IsJoystickHaptic().
SDL_IsJoystickVIRTUAL()
bool SDL_IsJoystickVIRTUAL (SDL_GUID guid) extern
{
    return (guid.data[14] == 'v') ? true : false;
}
References SDL_GUID::data, and true.
Referenced by SDL_GetJoystickGUIDType(), SDL_PrivateGetGamepadMappingForGUID(), and SDL_SendJoystickAxis().
SDL_IsJoystickWGI()
bool SDL_IsJoystickWGI (SDL_GUID guid) extern
{
    return (guid.data[14] == 'w') ? true : false;
}
References SDL_GUID::data, and true.
Referenced by SDL_GetJoystickGUIDType(), SDL_OpenJoystick(), and SDL_PrivateGetGamepadMappingForGUID().
SDL_IsJoystickWheel()
bool SDL_IsJoystickWheel (Uint16 vendor_id, Uint16 product_id)
{
    return SDL_VIDPIDInList(vendor_id, product_id, &wheel_devices);
}
References SDL_VIDPIDInList(), and wheel_devices.
Referenced by SDL_CreateMappingForHIDAPIGamepad(), and SDL_GetJoystickGUIDType().
SDL_IsJoystickXboxOne()
bool SDL_IsJoystickXboxOne (Uint16 vendor_id, Uint16 product_id) extern
{
    EControllerType eType = GuessControllerType(vendor_id, product_id);
    return eType == k_eControllerType_XBoxOneController;
}
References GuessControllerType(), and k_eControllerType_XBoxOneController.
SDL_IsJoystickXboxOneElite()
bool SDL_IsJoystickXboxOneElite (Uint16 vendor_id, Uint16 product_id) extern
{
    if (vendor_id == USB_VENDOR_MICROSOFT) {
        if (product_id == USB_PRODUCT_XBOX_ONE_ELITE_SERIES_1 ||
            product_id == USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2 ||
            product_id == USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLUETOOTH ||
            product_id == USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLE) {
            return true;
        }
    }
    return false;
}
References USB_PRODUCT_XBOX_ONE_ELITE_SERIES_1, USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2, USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLE, USB_PRODUCT_XBOX_ONE_ELITE_SERIES_2_BLUETOOTH, and USB_VENDOR_MICROSOFT.
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickXboxSeriesX()
bool SDL_IsJoystickXboxSeriesX (Uint16 vendor_id, Uint16 product_id) extern
{
    // Most new controllers have the share button, so we'll default to true and
    // have a list of older XBox One controllers that are known not to have it.
    if (SDL_VIDPIDInList(vendor_id, product_id, &old_xboxone_controllers)) {
        return false;
    }
    return true;
}
References old_xboxone_controllers, and SDL_VIDPIDInList().
Referenced by SDL_CreateMappingForHIDAPIGamepad().
SDL_IsJoystickXInput()
bool SDL_IsJoystickXInput (SDL_GUID guid) extern
{
    return (guid.data[14] == 'x') ? true : false;
}
References SDL_GUID::data, and true.
Referenced by SDL_GetGamepadTypeFromGUID(), SDL_GetJoystickGUIDType(), SDL_OpenJoystick(), and SDL_PrivateGetGamepadMappingForGUID().
SDL_JoystickGUIDUsesVersion()
bool SDL_JoystickGUIDUsesVersion (SDL_GUID guid) extern
{
    Uint16 vendor, product;
    if (SDL_IsJoystickMFI(guid)) {
        // The version bits are used as button capability mask
        return false;
    }
    SDL_GetJoystickGUIDInfo(guid, &vendor, &product, NULL, NULL);
    if (vendor && product) {
        return true;
    }
    return false;
}
References NULL, SDL_GetJoystickGUIDInfo(), and SDL_IsJoystickMFI().
Referenced by SDL_PrivateGetGamepadMappingForGUID().
SDL_JoystickHandledByAnotherDriver()
bool SDL_JoystickHandledByAnotherDriver (struct SDL_JoystickDriver * driver, Uint16 vendor_id, Uint16 product_id, Uint16 version, const char * name) extern
{
    int i;
    bool result = false;
    SDL_LockJoysticks();
    {
        for (i = 0; i < SDL_arraysize(SDL_joystick_drivers); ++i) {
            if (driver == SDL_joystick_drivers[i]) {
                // Higher priority drivers do not have this device
                break;
            }
            if (SDL_joystick_drivers[i]->IsDevicePresent(vendor_id, product_id, version, name)) {
                result = true;
                break;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_arraysize, SDL_joystick_drivers, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_JoysticksInitialized()
bool SDL_JoysticksInitialized (void) extern
{
    return SDL_joysticks_initialized;
}
References SDL_joysticks_initialized.
SDL_JoysticksLocked()
bool SDL_JoysticksLocked (void) extern
{
    return (SDL_joysticks_locked > 0);
}
References SDL_joysticks_locked.
Referenced by SDL_AssertJoysticksLocked().
SDL_JoysticksOpened()
bool SDL_JoysticksOpened (void) extern
{
    bool opened;
    SDL_LockJoysticks();
    {
        if (SDL_joysticks != NULL) {
            opened = true;
        } else {
            opened = false;
        }
    }
    SDL_UnlockJoysticks();
    return opened;
}
References NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_events_get_polling_interval().
SDL_JoysticksQuitting()
bool SDL_JoysticksQuitting (void) extern
{
    return SDL_joysticks_quitting;
}
References SDL_joysticks_quitting.
Referenced by SDL_PrivateJoystickAdded().
SDL_LoadVIDPIDList()
void SDL_LoadVIDPIDList (SDL_vidpid_list * list) extern
{
    const char *included_list = NULL;
    const char *excluded_list = NULL;
    if (list->included_hint_name) {
        SDL_AddHintCallback(list->included_hint_name, SDL_VIDPIDIncludedHintChanged, list);
    }
    if (list->excluded_hint_name) {
        SDL_AddHintCallback(list->excluded_hint_name, SDL_VIDPIDExcludedHintChanged, list);
    }
    list->initialized = true;
    if (list->included_hint_name) {
        included_list = SDL_GetHint(list->included_hint_name);
    }
    if (list->excluded_hint_name) {
        excluded_list = SDL_GetHint(list->excluded_hint_name);
    }
    SDL_LoadVIDPIDListFromHints(list, included_list, excluded_list);
}
References SDL_vidpid_list::excluded_hint_name, SDL_vidpid_list::included_hint_name, SDL_vidpid_list::initialized, NULL, SDL_AddHintCallback(), SDL_GetHint(), SDL_LoadVIDPIDListFromHints(), SDL_VIDPIDExcludedHintChanged(), and SDL_VIDPIDIncludedHintChanged().
Referenced by SDL_InitGamepadMappings(), and SDL_InitJoysticks().
SDL_LoadVIDPIDListFromHints()
void SDL_LoadVIDPIDListFromHints (SDL_vidpid_list * list, const char * included_list, const char * excluded_list) extern
{
    // Empty the list
    list->num_included_entries = 0;
    list->num_excluded_entries = 0;
    // Add the initial entries
    if (list->num_initial_entries > 0) {
        if (list->num_included_entries < list->num_initial_entries) {
            Uint32 *entries = (Uint32 *)SDL_malloc(list->num_initial_entries * sizeof(*entries));
            if (entries) {
                SDL_memcpy(entries, list->initial_entries, list->num_initial_entries * sizeof(*entries));
                list->included_entries = entries;
                list->num_included_entries = list->num_initial_entries;
                list->max_included_entries = list->num_initial_entries;
            }
        }
    }
    // Add the included entries from the hint
    SDL_LoadVIDPIDListFromHint(included_list, &list->num_included_entries, &list->max_included_entries, &list->included_entries);
    // Add the excluded entries from the hint
    SDL_LoadVIDPIDListFromHint(excluded_list, &list->num_excluded_entries, &list->max_excluded_entries, &list->excluded_entries);
}
References SDL_vidpid_list::excluded_entries, SDL_vidpid_list::included_entries, SDL_vidpid_list::initial_entries, SDL_vidpid_list::max_excluded_entries, SDL_vidpid_list::max_included_entries, SDL_vidpid_list::num_excluded_entries, SDL_vidpid_list::num_included_entries, SDL_vidpid_list::num_initial_entries, SDL_LoadVIDPIDListFromHint(), SDL_malloc(), and SDL_memcpy.
Referenced by SDL_LoadVIDPIDList(), SDL_VIDPIDExcludedHintChanged(), SDL_VIDPIDIncludedHintChanged(), and ShouldAttemptSensorFusion().
SDL_PrivateJoystickAdded()
void SDL_PrivateJoystickAdded (SDL_JoystickID instance_id) extern
{
    SDL_JoystickDriver *driver;
    int device_index;
    int player_index = -1;
    bool is_gamepad;
    SDL_AssertJoysticksLocked();
    if (SDL_JoysticksQuitting()) {
        return;
    }
    SDL_joystick_being_added = true;
    if (SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        player_index = driver->GetDeviceSteamVirtualGamepadSlot(device_index);
        if (player_index < 0) {
            player_index = driver->GetDevicePlayerIndex(device_index);
        }
    }
    if (player_index < 0 && SDL_IsGamepad(instance_id)) {
        player_index = SDL_FindFreePlayerIndex();
    }
    if (player_index >= 0) {
        SDL_SetJoystickIDForPlayerIndex(player_index, instance_id);
    }
    {
        SDL_Event event;
        event.type = SDL_EVENT_JOYSTICK_ADDED;
        event.common.timestamp = 0;
        if (SDL_EventEnabled(event.type)) {
            event.jdevice.which = instance_id;
            SDL_PushEvent(&event);
        }
    }
    // This might create an automatic gamepad mapping, so wait to send the event
    is_gamepad = SDL_IsGamepad(instance_id);
    SDL_joystick_being_added = false;
    if (is_gamepad) {
        SDL_PrivateGamepadAdded(instance_id);
    }
}
References SDL_JoystickDriver::GetDevicePlayerIndex, SDL_JoystickDriver::GetDeviceSteamVirtualGamepadSlot, SDL_AssertJoysticksLocked(), SDL_EVENT_JOYSTICK_ADDED, SDL_EventEnabled(), SDL_FindFreePlayerIndex(), SDL_GetDriverAndJoystickIndex(), SDL_IsGamepad(), SDL_joystick_being_added, SDL_JoysticksQuitting(), SDL_PrivateGamepadAdded(), SDL_PushEvent(), and SDL_SetJoystickIDForPlayerIndex().
SDL_PrivateJoystickAddSensor()
void SDL_PrivateJoystickAddSensor (SDL_Joystick * joystick, SDL_SensorType type, float rate) extern
{
    int nsensors;
    SDL_JoystickSensorInfo *sensors;
    SDL_AssertJoysticksLocked();
    nsensors = joystick->nsensors + 1;
    sensors = (SDL_JoystickSensorInfo *)SDL_realloc(joystick->sensors, (nsensors * sizeof(SDL_JoystickSensorInfo)));
    if (sensors) {
        SDL_JoystickSensorInfo *sensor = &sensors[nsensors - 1];
        SDL_zerop(sensor);
        sensor->type = type;
        sensor->rate = rate;
        joystick->nsensors = nsensors;
        joystick->sensors = sensors;
    }
}
References SDL_JoystickSensorInfo::rate, SDL_AssertJoysticksLocked(), SDL_realloc(), SDL_zerop, and SDL_JoystickSensorInfo::type.
Referenced by AttemptSensorFusion(), and IOS_JoystickOpen().
SDL_PrivateJoystickAddTouchpad()
void SDL_PrivateJoystickAddTouchpad (SDL_Joystick * joystick, int nfingers) extern
{
    int ntouchpads;
    SDL_JoystickTouchpadInfo *touchpads;
    SDL_AssertJoysticksLocked();
    ntouchpads = joystick->ntouchpads + 1;
    touchpads = (SDL_JoystickTouchpadInfo *)SDL_realloc(joystick->touchpads, (ntouchpads * sizeof(SDL_JoystickTouchpadInfo)));
    if (touchpads) {
        SDL_JoystickTouchpadInfo *touchpad = &touchpads[ntouchpads - 1];
        SDL_JoystickTouchpadFingerInfo *fingers = (SDL_JoystickTouchpadFingerInfo *)SDL_calloc(nfingers, sizeof(SDL_JoystickTouchpadFingerInfo));
        if (fingers) {
            touchpad->nfingers = nfingers;
            touchpad->fingers = fingers;
        } else {
            // Out of memory, this touchpad won't be active
            touchpad->nfingers = 0;
            touchpad->fingers = NULL;
        }
        joystick->ntouchpads = ntouchpads;
        joystick->touchpads = touchpads;
    }
}
References SDL_JoystickTouchpadInfo::fingers, SDL_JoystickTouchpadInfo::nfingers, NULL, SDL_AssertJoysticksLocked(), SDL_calloc(), and SDL_realloc().
Referenced by IOS_JoystickOpen().
SDL_PrivateJoystickForceRecentering()
void SDL_PrivateJoystickForceRecentering (SDL_Joystick * joystick) extern
{
    Uint8 i, j;
    Uint64 timestamp = SDL_GetTicksNS();
    SDL_AssertJoysticksLocked();
    // Tell the app that everything is centered/unpressed...
    for (i = 0; i < joystick->naxes; i++) {
        if (joystick->axes[i].has_initial_value) {
            SDL_SendJoystickAxis(timestamp, joystick, i, joystick->axes[i].zero);
        }
    }
    for (i = 0; i < joystick->nbuttons; i++) {
        SDL_SendJoystickButton(timestamp, joystick, i, false);
    }
    for (i = 0; i < joystick->nhats; i++) {
        SDL_SendJoystickHat(timestamp, joystick, i, SDL_HAT_CENTERED);
    }
    for (i = 0; i < joystick->ntouchpads; i++) {
        SDL_JoystickTouchpadInfo *touchpad = &joystick->touchpads[i];
        for (j = 0; j < touchpad->nfingers; ++j) {
            SDL_SendJoystickTouchpad(timestamp, joystick, i, j, false, 0.0f, 0.0f, 0.0f);
        }
    }
}
References SDL_JoystickTouchpadInfo::nfingers, SDL_AssertJoysticksLocked(), SDL_GetTicksNS(), SDL_HAT_CENTERED, SDL_SendJoystickAxis(), SDL_SendJoystickButton(), SDL_SendJoystickHat(), and SDL_SendJoystickTouchpad().
Referenced by SDL_PrivateJoystickRemoved().
SDL_PrivateJoystickGetAutoGamepadMapping()
bool SDL_PrivateJoystickGetAutoGamepadMapping (SDL_JoystickID instance_id, SDL_GamepadMapping * out) extern
{
    SDL_JoystickDriver *driver;
    int device_index;
    bool is_ok = false;
    SDL_LockJoysticks();
    if (SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        is_ok = driver->GetGamepadMapping(device_index, out);
    }
    SDL_UnlockJoysticks();
    return is_ok;
}
References SDL_JoystickDriver::GetGamepadMapping, SDL_GetDriverAndJoystickIndex(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_PrivateGetGamepadMapping().
SDL_PrivateJoystickRemoved()
void SDL_PrivateJoystickRemoved (SDL_JoystickID instance_id) extern
{
    SDL_Joystick *joystick = NULL;
    int player_index;
    SDL_Event event;
    SDL_AssertJoysticksLocked();
    // Find this joystick...
    for (joystick = SDL_joysticks; joystick; joystick = joystick->next) {
        if (joystick->instance_id == instance_id) {
            SDL_PrivateJoystickForceRecentering(joystick);
            joystick->attached = false;
            break;
        }
    }
    if (SDL_IsGamepad(instance_id)) {
        SDL_PrivateGamepadRemoved(instance_id);
    }
    event.type = SDL_EVENT_JOYSTICK_REMOVED;
    event.common.timestamp = 0;
    if (SDL_EventEnabled(event.type)) {
        event.jdevice.which = instance_id;
        SDL_PushEvent(&event);
    }
    player_index = SDL_GetPlayerIndexForJoystickID(instance_id);
    if (player_index >= 0) {
        SDL_joystick_players[player_index] = 0;
    }
}
References NULL, SDL_AssertJoysticksLocked(), SDL_EVENT_JOYSTICK_REMOVED, SDL_EventEnabled(), SDL_GetPlayerIndexForJoystickID(), SDL_IsGamepad(), SDL_PrivateGamepadRemoved(), SDL_PrivateJoystickForceRecentering(), and SDL_PushEvent().
Referenced by IOS_RemoveJoystickDevice(), and SDL_QuitJoysticks().
SDL_PrivateJoystickSensorRate()
void SDL_PrivateJoystickSensorRate (SDL_Joystick * joystick, SDL_SensorType type, float rate) extern
{
    int i;
    SDL_AssertJoysticksLocked();
    for (i = 0; i < joystick->nsensors; ++i) {
        if (joystick->sensors[i].type == type) {
            joystick->sensors[i].rate = rate;
        }
    }
}
References SDL_AssertJoysticksLocked().
SDL_QuitJoysticks()
void SDL_QuitJoysticks (void) extern
{
    int i;
    SDL_JoystickID *joysticks;
    SDL_LockJoysticks();
    SDL_joysticks_quitting = true;
    joysticks = SDL_GetJoysticks(NULL);
    if (joysticks) {
        for (i = 0; joysticks[i]; ++i) {
            SDL_PrivateJoystickRemoved(joysticks[i]);
        }
        SDL_free(joysticks);
    }
    while (SDL_joysticks) {
        SDL_joysticks->ref_count = 1;
        SDL_CloseJoystick(SDL_joysticks);
    }
    // Quit drivers in reverse order to avoid breaking dependencies between drivers
    for (i = SDL_arraysize(SDL_joystick_drivers) - 1; i >= 0; --i) {
        SDL_joystick_drivers[i]->Quit();
    }
    if (SDL_joystick_players) {
        SDL_free(SDL_joystick_players);
        SDL_joystick_players = NULL;
        SDL_joystick_player_count = 0;
    }
    SDL_QuitSubSystem(SDL_INIT_EVENTS);
    SDL_QuitSteamVirtualGamepadInfo();
    SDL_RemoveHintCallback(SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS,
                        SDL_JoystickAllowBackgroundEventsChanged, NULL);
    SDL_FreeVIDPIDList(&old_xboxone_controllers);
    SDL_FreeVIDPIDList(&arcadestick_devices);
    SDL_FreeVIDPIDList(&blacklist_devices);
    SDL_FreeVIDPIDList(&flightstick_devices);
    SDL_FreeVIDPIDList(&gamecube_devices);
    SDL_FreeVIDPIDList(&rog_gamepad_mice);
    SDL_FreeVIDPIDList(&throttle_devices);
    SDL_FreeVIDPIDList(&wheel_devices);
    SDL_FreeVIDPIDList(&zero_centered_devices);
    SDL_QuitGamepadMappings();
    SDL_joysticks_quitting = false;
    SDL_joysticks_initialized = false;
    SDL_UnlockJoysticks();
}
References arcadestick_devices, blacklist_devices, flightstick_devices, gamecube_devices, NULL, old_xboxone_controllers, rog_gamepad_mice, SDL_arraysize, SDL_CloseJoystick(), SDL_free(), SDL_FreeVIDPIDList(), SDL_GetJoysticks(), SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS, SDL_INIT_EVENTS, SDL_joystick_drivers, SDL_JoystickAllowBackgroundEventsChanged(), SDL_joysticks_initialized, SDL_joysticks_quitting, SDL_LockJoysticks(), SDL_PrivateJoystickRemoved(), SDL_QuitGamepadMappings(), SDL_QuitSteamVirtualGamepadInfo(), SDL_QuitSubSystem(), SDL_RemoveHintCallback(), SDL_UnlockJoysticks(), throttle_devices, wheel_devices, and zero_centered_devices.
Referenced by SDL_InitJoysticks(), and SDL_QuitSubSystem().
SDL_SendJoystickAxis()
void SDL_SendJoystickAxis (Uint64 timestamp, SDL_Joystick * joystick, Uint8 axis, Sint16 value) extern
{
    SDL_JoystickAxisInfo *info;
    SDL_AssertJoysticksLocked();
    // Make sure we're not getting garbage or duplicate events
    if (axis >= joystick->naxes) {
        return;
    }
    info = &joystick->axes[axis];
    if (!info->has_initial_value ||
        (!info->has_second_value && (info->initial_value <= -32767 || info->initial_value == 32767) && SDL_abs(value) < (SDL_JOYSTICK_AXIS_MAX / 4))) {
        info->initial_value = value;
        info->value = value;
        info->zero = value;
        info->has_initial_value = true;
    } else if (value == info->value && !info->sending_initial_value) {
        return;
    } else {
        info->has_second_value = true;
    }
    if (!info->sent_initial_value) {
        // Make sure we don't send motion until there's real activity on this axis
        const int MAX_ALLOWED_JITTER = SDL_JOYSTICK_AXIS_MAX / 80; // ShanWan PS3 controller needed 96
        if (SDL_abs(value - info->value) <= MAX_ALLOWED_JITTER &&
            !SDL_IsJoystickVIRTUAL(joystick->guid)) {
            return;
        }
        info->sent_initial_value = true;
        info->sending_initial_value = true;
        SDL_SendJoystickAxis(timestamp, joystick, axis, info->initial_value);
        info->sending_initial_value = false;
    }
    /* We ignore events if we don't have keyboard focus, except for centering
     * events.
     */
    if (SDL_PrivateJoystickShouldIgnoreEvent()) {
        if (info->sending_initial_value ||
            (value > info->zero && value >= info->value) ||
            (value < info->zero && value <= info->value)) {
            return;
        }
    }
    // Update internal joystick state
    SDL_assert(timestamp != 0);
    info->value = value;
    joystick->update_complete = timestamp;
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_JOYSTICK_AXIS_MOTION)) {
        SDL_Event event;
        event.type = SDL_EVENT_JOYSTICK_AXIS_MOTION;
        event.common.timestamp = timestamp;
        event.jaxis.which = joystick->instance_id;
        event.jaxis.axis = axis;
        event.jaxis.value = value;
        SDL_PushEvent(&event);
    }
}
References SDL_JoystickAxisInfo::has_initial_value, SDL_JoystickAxisInfo::has_second_value, SDL_JoystickAxisInfo::initial_value, SDL_abs(), SDL_assert, SDL_AssertJoysticksLocked(), SDL_EVENT_JOYSTICK_AXIS_MOTION, SDL_EventEnabled(), SDL_IsJoystickVIRTUAL(), SDL_JOYSTICK_AXIS_MAX, SDL_PrivateJoystickShouldIgnoreEvent(), SDL_PushEvent(), SDL_SendJoystickAxis(), SDL_JoystickAxisInfo::sending_initial_value, SDL_JoystickAxisInfo::sent_initial_value, SDL_JoystickAxisInfo::value, SDL_JoystickAxisInfo::zero, and zero.
Referenced by IOS_MFIJoystickUpdate(), SDL_PrivateJoystickForceRecentering(), and SDL_SendJoystickAxis().
SDL_SendJoystickBall()
void SDL_SendJoystickBall (Uint64 timestamp, SDL_Joystick * joystick, Uint8 ball, Sint16 xrel, Sint16 yrel) extern
{
    SDL_AssertJoysticksLocked();
    // Make sure we're not getting garbage events
    if (ball >= joystick->nballs) {
        return;
    }
    // We ignore events if we don't have keyboard focus.
    if (SDL_PrivateJoystickShouldIgnoreEvent()) {
        return;
    }
    // Update internal mouse state
    joystick->balls[ball].dx += xrel;
    joystick->balls[ball].dy += yrel;
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_JOYSTICK_BALL_MOTION)) {
        SDL_Event event;
        event.type = SDL_EVENT_JOYSTICK_BALL_MOTION;
        event.common.timestamp = timestamp;
        event.jball.which = joystick->instance_id;
        event.jball.ball = ball;
        event.jball.xrel = xrel;
        event.jball.yrel = yrel;
        SDL_PushEvent(&event);
    }
}
References SDL_AssertJoysticksLocked(), SDL_EVENT_JOYSTICK_BALL_MOTION, SDL_EventEnabled(), SDL_PrivateJoystickShouldIgnoreEvent(), and SDL_PushEvent().
SDL_SendJoystickButton()
void SDL_SendJoystickButton (Uint64 timestamp, SDL_Joystick * joystick, Uint8 button, bool down) extern
{
    SDL_Event event;
    SDL_AssertJoysticksLocked();
    if (down) {
        event.type = SDL_EVENT_JOYSTICK_BUTTON_DOWN;
    } else {
        event.type = SDL_EVENT_JOYSTICK_BUTTON_UP;
    }
    if (joystick->swap_face_buttons) {
        switch (button) {
        case 0:
            button = 1;
            break;
        case 1:
            button = 0;
            break;
        case 2:
            button = 3;
            break;
        case 3:
            button = 2;
            break;
        default:
            break;
        }
    }
    // Make sure we're not getting garbage or duplicate events
    if (button >= joystick->nbuttons) {
        return;
    }
    if (down == joystick->buttons[button]) {
        return;
    }
    /* We ignore events if we don't have keyboard focus, except for button
     * release. */
    if (SDL_PrivateJoystickShouldIgnoreEvent()) {
        if (down) {
            return;
        }
    }
    // Update internal joystick state
    SDL_assert(timestamp != 0);
    joystick->buttons[button] = down;
    joystick->update_complete = timestamp;
    // Post the event, if desired
    if (SDL_EventEnabled(event.type)) {
        event.common.timestamp = timestamp;
        event.jbutton.which = joystick->instance_id;
        event.jbutton.button = button;
        event.jbutton.down = down;
        SDL_PushEvent(&event);
    }
}
References SDL_assert, SDL_AssertJoysticksLocked(), SDL_EVENT_JOYSTICK_BUTTON_DOWN, SDL_EVENT_JOYSTICK_BUTTON_UP, SDL_EventEnabled(), SDL_PrivateJoystickShouldIgnoreEvent(), and SDL_PushEvent().
Referenced by IOS_MFIJoystickUpdate(), and SDL_PrivateJoystickForceRecentering().
SDL_SendJoystickHat()
void SDL_SendJoystickHat (Uint64 timestamp, SDL_Joystick * joystick, Uint8 hat, Uint8 value) extern
{
    SDL_AssertJoysticksLocked();
    // Make sure we're not getting garbage or duplicate events
    if (hat >= joystick->nhats) {
        return;
    }
    if (value == joystick->hats[hat]) {
        return;
    }
    /* We ignore events if we don't have keyboard focus, except for centering
     * events.
     */
    if (SDL_PrivateJoystickShouldIgnoreEvent()) {
        if (value != SDL_HAT_CENTERED) {
            return;
        }
    }
    // Update internal joystick state
    SDL_assert(timestamp != 0);
    joystick->hats[hat] = value;
    joystick->update_complete = timestamp;
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_JOYSTICK_HAT_MOTION)) {
        SDL_Event event;
        event.type = SDL_EVENT_JOYSTICK_HAT_MOTION;
        event.common.timestamp = timestamp;
        event.jhat.which = joystick->instance_id;
        event.jhat.hat = hat;
        event.jhat.value = value;
        SDL_PushEvent(&event);
    }
}
References SDL_assert, SDL_AssertJoysticksLocked(), SDL_EVENT_JOYSTICK_HAT_MOTION, SDL_EventEnabled(), SDL_HAT_CENTERED, SDL_PrivateJoystickShouldIgnoreEvent(), and SDL_PushEvent().
Referenced by IOS_MFIJoystickUpdate(), and SDL_PrivateJoystickForceRecentering().
SDL_SendJoystickPowerInfo()
void SDL_SendJoystickPowerInfo (SDL_Joystick * joystick, SDL_PowerState state, int percent) extern
{
    SDL_AssertJoysticksLocked();
    if (state != joystick->battery_state || percent != joystick->battery_percent) {
        joystick->battery_state = state;
        joystick->battery_percent = percent;
        if (SDL_EventEnabled(SDL_EVENT_JOYSTICK_BATTERY_UPDATED)) {
            SDL_Event event;
            event.type = SDL_EVENT_JOYSTICK_BATTERY_UPDATED;
            event.common.timestamp = 0;
            event.jbattery.which = joystick->instance_id;
            event.jbattery.state = state;
            event.jbattery.percent = percent;
            SDL_PushEvent(&event);
        }
    }
}
References SDL_AssertJoysticksLocked(), SDL_EVENT_JOYSTICK_BATTERY_UPDATED, SDL_EventEnabled(), and SDL_PushEvent().
Referenced by IOS_MFIJoystickUpdate().
SDL_SendJoystickSensor()
void SDL_SendJoystickSensor (Uint64 timestamp, SDL_Joystick * joystick, SDL_SensorType type, Uint64 sensor_timestamp, const float * data, int num_values) extern
{
    SDL_AssertJoysticksLocked();
    // We ignore events if we don't have keyboard focus
    if (SDL_PrivateJoystickShouldIgnoreEvent()) {
        return;
    }
    for (int i = 0; i < joystick->nsensors; ++i) {
        SDL_JoystickSensorInfo *sensor = &joystick->sensors[i];
        if (sensor->type == type) {
            if (sensor->enabled) {
                num_values = SDL_min(num_values, SDL_arraysize(sensor->data));
                // Update internal sensor state
                SDL_memcpy(sensor->data, data, num_values * sizeof(*data));
                joystick->update_complete = timestamp;
                // Post the event, if desired
                if (SDL_EventEnabled(SDL_EVENT_GAMEPAD_SENSOR_UPDATE)) {
                    SDL_Event event;
                    event.type = SDL_EVENT_GAMEPAD_SENSOR_UPDATE;
                    event.common.timestamp = timestamp;
                    event.gsensor.which = joystick->instance_id;
                    event.gsensor.sensor = type;
                    num_values = SDL_min(num_values,
                                         SDL_arraysize(event.gsensor.data));
                    SDL_memset(event.gsensor.data, 0,
                               sizeof(event.gsensor.data));
                    SDL_memcpy(event.gsensor.data, data,
                               num_values * sizeof(*data));
                    event.gsensor.sensor_timestamp = sensor_timestamp;
                    SDL_PushEvent(&event);
                }
            }
            break;
        }
    }
}
References SDL_JoystickSensorInfo::data, SDL_JoystickSensorInfo::enabled, SDL_arraysize, SDL_AssertJoysticksLocked(), SDL_EVENT_GAMEPAD_SENSOR_UPDATE, SDL_EventEnabled(), SDL_memcpy, SDL_memset, SDL_min, SDL_PrivateJoystickShouldIgnoreEvent(), SDL_PushEvent(), and SDL_JoystickSensorInfo::type.
Referenced by IOS_MFIJoystickUpdate(), and SDL_GamepadSensorWatcher().
SDL_SendJoystickTouchpad()
void SDL_SendJoystickTouchpad (Uint64 timestamp, SDL_Joystick * joystick, int touchpad, int finger, bool down, float x, float y, float pressure) extern
{
    SDL_JoystickTouchpadInfo *touchpad_info;
    SDL_JoystickTouchpadFingerInfo *finger_info;
    Uint32 event_type;
    SDL_AssertJoysticksLocked();
    if (touchpad < 0 || touchpad >= joystick->ntouchpads) {
        return;
    }
    touchpad_info = &joystick->touchpads[touchpad];
    if (finger < 0 || finger >= touchpad_info->nfingers) {
        return;
    }
    finger_info = &touchpad_info->fingers[finger];
    if (!down) {
        if (x == 0.0f && y == 0.0f) {
            x = finger_info->x;
            y = finger_info->y;
        }
        pressure = 0.0f;
    }
    if (x < 0.0f) {
        x = 0.0f;
    } else if (x > 1.0f) {
        x = 1.0f;
    }
    if (y < 0.0f) {
        y = 0.0f;
    } else if (y > 1.0f) {
        y = 1.0f;
    }
    if (pressure < 0.0f) {
        pressure = 0.0f;
    } else if (pressure > 1.0f) {
        pressure = 1.0f;
    }
    if (down == finger_info->down) {
        if (!down ||
            (x == finger_info->x && y == finger_info->y && pressure == finger_info->pressure)) {
            return;
        }
    }
    if (down == finger_info->down) {
        event_type = SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION;
    } else if (down) {
        event_type = SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN;
    } else {
        event_type = SDL_EVENT_GAMEPAD_TOUCHPAD_UP;
    }
    // We ignore events if we don't have keyboard focus, except for touch release
    if (SDL_PrivateJoystickShouldIgnoreEvent()) {
        if (event_type != SDL_EVENT_GAMEPAD_TOUCHPAD_UP) {
            return;
        }
    }
    // Update internal joystick state
    SDL_assert(timestamp != 0);
    finger_info->down = down;
    finger_info->x = x;
    finger_info->y = y;
    finger_info->pressure = pressure;
    joystick->update_complete = timestamp;
    // Post the event, if desired
    if (SDL_EventEnabled(event_type)) {
        SDL_Event event;
        event.type = event_type;
        event.common.timestamp = timestamp;
        event.gtouchpad.which = joystick->instance_id;
        event.gtouchpad.touchpad = touchpad;
        event.gtouchpad.finger = finger;
        event.gtouchpad.x = x;
        event.gtouchpad.y = y;
        event.gtouchpad.pressure = pressure;
        SDL_PushEvent(&event);
    }
}
References SDL_JoystickTouchpadFingerInfo::down, SDL_JoystickTouchpadInfo::fingers, SDL_JoystickTouchpadInfo::nfingers, SDL_JoystickTouchpadFingerInfo::pressure, SDL_assert, SDL_AssertJoysticksLocked(), SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN, SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION, SDL_EVENT_GAMEPAD_TOUCHPAD_UP, SDL_EventEnabled(), SDL_PrivateJoystickShouldIgnoreEvent(), SDL_PushEvent(), SDL_JoystickTouchpadFingerInfo::x, and SDL_JoystickTouchpadFingerInfo::y.
Referenced by IOS_MFIJoystickUpdate(), and SDL_PrivateJoystickForceRecentering().
SDL_SetJoystickGUIDCRC()
void SDL_SetJoystickGUIDCRC (SDL_GUID * guid, Uint16 crc) extern
{
    Uint16 *guid16 = (Uint16 *)guid->data;
    guid16[1] = SDL_Swap16LE(crc);
}
References SDL_GUID::data, and SDL_Swap16LE.
Referenced by SDL_PrivateAddMappingForGUID(), SDL_PrivateGenerateAutomaticGamepadMapping(), and SDL_PrivateMatchGamepadMappingForGUID().
SDL_SetJoystickGUIDProduct()
void SDL_SetJoystickGUIDProduct (SDL_GUID * guid, Uint16 product) extern
{
    Uint16 *guid16 = (Uint16 *)guid->data;
    guid16[4] = SDL_Swap16LE(product);
}
References SDL_GUID::data, and SDL_Swap16LE.
SDL_SetJoystickGUIDVendor()
void SDL_SetJoystickGUIDVendor (SDL_GUID * guid, Uint16 vendor) extern
{
    Uint16 *guid16 = (Uint16 *)guid->data;
    guid16[2] = SDL_Swap16LE(vendor);
}
References SDL_GUID::data, and SDL_Swap16LE.
SDL_SetJoystickGUIDVersion()
void SDL_SetJoystickGUIDVersion (SDL_GUID * guid, Uint16 version) extern
{
    Uint16 *guid16 = (Uint16 *)guid->data;
    guid16[6] = SDL_Swap16LE(version);
}
References SDL_GUID::data, and SDL_Swap16LE.
Referenced by SDL_PrivateMatchGamepadMappingForGUID().
SDL_ShouldIgnoreJoystick()
bool SDL_ShouldIgnoreJoystick (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char * name) extern
{
    // Check the joystick blacklist
    if (SDL_VIDPIDInList(vendor_id, product_id, &blacklist_devices)) {
        return true;
    }
    if (!SDL_GetHintBoolean(SDL_HINT_JOYSTICK_ROG_CHAKRAM, false)) {
        if (SDL_VIDPIDInList(vendor_id, product_id, &rog_gamepad_mice)) {
            return true;
        }
    }
    if (SDL_ShouldIgnoreGamepad(vendor_id, product_id, version, name)) {
        return true;
    }
    return false;
}
References blacklist_devices, rog_gamepad_mice, SDL_GetHintBoolean(), SDL_HINT_JOYSTICK_ROG_CHAKRAM, SDL_ShouldIgnoreGamepad(), and SDL_VIDPIDInList().
SDL_VIDPIDInList()
bool SDL_VIDPIDInList (Uint16 vendor_id, Uint16 product_id, const SDL_vidpid_list * list) extern
{
    int i;
    Uint32 vidpid = MAKE_VIDPID(vendor_id, product_id);
    for (i = 0; i < list->num_excluded_entries; ++i) {
        if (vidpid == list->excluded_entries[i]) {
            return false;
        }
    }
    for (i = 0; i < list->num_included_entries; ++i) {
        if (vidpid == list->included_entries[i]) {
            return true;
        }
    }
    return false;
}
References SDL_vidpid_list::excluded_entries, SDL_vidpid_list::included_entries, MAKE_VIDPID, SDL_vidpid_list::num_excluded_entries, and SDL_vidpid_list::num_included_entries.
Referenced by SDL_IsJoystickArcadeStick(), SDL_IsJoystickFlightStick(), SDL_IsJoystickGameCube(), SDL_IsJoystickThrottle(), SDL_IsJoystickWheel(), SDL_IsJoystickXboxSeriesX(), SDL_JoystickAxesCenteredAtZero(), SDL_ShouldIgnoreGamepad(), SDL_ShouldIgnoreJoystick(), and ShouldAttemptSensorFusion().