SDL3: SDL-main/include/SDL3/SDL_mouse.h File Reference
SDL_mouse.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_surface.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDL_BUTTON_LEFT 1
#define SDL_BUTTON_LMASK SDL_BUTTON_MASK(SDL_BUTTON_LEFT)
#define SDL_BUTTON_MASK(X)
#define SDL_BUTTON_MIDDLE 2
#define SDL_BUTTON_MMASK SDL_BUTTON_MASK(SDL_BUTTON_MIDDLE)
#define SDL_BUTTON_RIGHT 3
#define SDL_BUTTON_RMASK SDL_BUTTON_MASK(SDL_BUTTON_RIGHT)
#define SDL_BUTTON_X1 4
#define SDL_BUTTON_X1MASK SDL_BUTTON_MASK(SDL_BUTTON_X1)
#define SDL_BUTTON_X2 5
#define SDL_BUTTON_X2MASK SDL_BUTTON_MASK(SDL_BUTTON_X2)
Typedefs
typedef struct SDL_Cursor SDL_Cursor
typedef Uint32 SDL_MouseButtonFlags
typedef Uint32 SDL_MouseID
typedef void(SDLCALL * SDL_MouseMotionTransformCallback) (void *userdata, Uint64 timestamp, SDL_Window *window, SDL_MouseID mouseID, float *x, float *y)
typedef enum SDL_MouseWheelDirection SDL_MouseWheelDirection
typedef enum SDL_SystemCursor SDL_SystemCursor
Enumerations
enum SDL_MouseWheelDirection { SDL_MOUSEWHEEL_NORMAL , SDL_MOUSEWHEEL_FLIPPED }
enum SDL_SystemCursor {
SDL_SYSTEM_CURSOR_DEFAULT , SDL_SYSTEM_CURSOR_TEXT , SDL_SYSTEM_CURSOR_WAIT , SDL_SYSTEM_CURSOR_CROSSHAIR ,
SDL_SYSTEM_CURSOR_PROGRESS , SDL_SYSTEM_CURSOR_NWSE_RESIZE , SDL_SYSTEM_CURSOR_NESW_RESIZE , SDL_SYSTEM_CURSOR_EW_RESIZE ,
SDL_SYSTEM_CURSOR_NS_RESIZE , SDL_SYSTEM_CURSOR_MOVE , SDL_SYSTEM_CURSOR_NOT_ALLOWED , SDL_SYSTEM_CURSOR_POINTER ,
SDL_SYSTEM_CURSOR_NW_RESIZE , SDL_SYSTEM_CURSOR_N_RESIZE , SDL_SYSTEM_CURSOR_NE_RESIZE , SDL_SYSTEM_CURSOR_E_RESIZE ,
SDL_SYSTEM_CURSOR_SE_RESIZE , SDL_SYSTEM_CURSOR_S_RESIZE , SDL_SYSTEM_CURSOR_SW_RESIZE , SDL_SYSTEM_CURSOR_W_RESIZE ,
SDL_SYSTEM_CURSOR_COUNT
}
Functions
SDL_DECLSPEC bool SDLCALL SDL_CaptureMouse (bool enabled)
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_CreateColorCursor (SDL_Surface *surface, int hot_x, int hot_y)
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_CreateCursor (const Uint8 *data, const Uint8 *mask, int w, int h, int hot_x, int hot_y)
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_CreateSystemCursor (SDL_SystemCursor id)
SDL_DECLSPEC bool SDLCALL SDL_CursorVisible (void)
SDL_DECLSPEC void SDLCALL SDL_DestroyCursor (SDL_Cursor *cursor)
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_GetCursor (void)
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_GetDefaultCursor (void)
SDL_DECLSPEC SDL_MouseButtonFlags SDLCALL SDL_GetGlobalMouseState (float *x, float *y)
SDL_DECLSPEC SDL_MouseID *SDLCALL SDL_GetMice (int *count)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetMouseFocus (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetMouseNameForID (SDL_MouseID instance_id)
SDL_DECLSPEC SDL_MouseButtonFlags SDLCALL SDL_GetMouseState (float *x, float *y)
SDL_DECLSPEC SDL_MouseButtonFlags SDLCALL SDL_GetRelativeMouseState (float *x, float *y)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowRelativeMouseMode (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_HasMouse (void)
SDL_DECLSPEC bool SDLCALL SDL_HideCursor (void)
SDL_DECLSPEC bool SDLCALL SDL_SetCursor (SDL_Cursor *cursor)
SDL_DECLSPEC bool SDLCALL SDL_SetRelativeMouseTransform (SDL_MouseMotionTransformCallback callback, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowRelativeMouseMode (SDL_Window *window, bool enabled)
SDL_DECLSPEC bool SDLCALL SDL_ShowCursor (void)
SDL_DECLSPEC bool SDLCALL SDL_WarpMouseGlobal (float x, float y)
SDL_DECLSPEC void SDLCALL SDL_WarpMouseInWindow (SDL_Window *window, float x, float y)
Macro Definition Documentation
SDL_BUTTON_LEFT
#define SDL_BUTTON_LEFT 1
Referenced by SDL_BWin::_MouseButtonEvent(), SDL_PrivateSendMouseButton(), SDL_PrivateSendMouseMotion(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SendTouch(), and updateMouse().
SDL_BUTTON_LMASK
#define SDL_BUTTON_LMASK SDL_BUTTON_MASK(SDL_BUTTON_LEFT)
SDL_BUTTON_MASK
#define SDL_BUTTON_MASK (X)
Value:
(1u << ((X)-1))
Referenced by GetMouseInputSource(), and SDL_PrivateSendMouseButton().
SDL_BUTTON_MIDDLE
#define SDL_BUTTON_MIDDLE 2
Referenced by SDL_BWin::_MouseButtonEvent(), and SDL_SendPenButton().
SDL_BUTTON_MMASK
#define SDL_BUTTON_MMASK SDL_BUTTON_MASK(SDL_BUTTON_MIDDLE)
SDL_BUTTON_RIGHT
#define SDL_BUTTON_RIGHT 3
Referenced by SDL_BWin::_MouseButtonEvent(), and SDL_SendPenButton().
SDL_BUTTON_RMASK
#define SDL_BUTTON_RMASK SDL_BUTTON_MASK(SDL_BUTTON_RIGHT)
SDL_BUTTON_X1
#define SDL_BUTTON_X1 4
Referenced by SDL_SendPenButton().
SDL_BUTTON_X1MASK
#define SDL_BUTTON_X1MASK SDL_BUTTON_MASK(SDL_BUTTON_X1)
SDL_BUTTON_X2
#define SDL_BUTTON_X2 5
Referenced by SDL_SendPenButton().
SDL_BUTTON_X2MASK
#define SDL_BUTTON_X2MASK SDL_BUTTON_MASK(SDL_BUTTON_X2)
Typedef Documentation
SDL_Cursor
typedef struct SDL_Cursor SDL_Cursor
The structure used to identify an SDL cursor.
This is opaque data.
Since
This struct is available since SDL 3.2.0.
SDL_MouseButtonFlags
typedef Uint32 SDL_MouseButtonFlags
A bitmask of pressed mouse buttons, as reported by SDL_GetMouseState, etc.
Button 1: Left mouse button
Button 2: Middle mouse button
Button 3: Right mouse button
Button 4: Side mouse button 1
Button 5: Side mouse button 2
Since
This datatype is available since SDL 3.2.0.
See also
SDL_GetMouseState
SDL_GetGlobalMouseState
SDL_GetRelativeMouseState
SDL_MouseID
typedef Uint32 SDL_MouseID
CategoryMouse
Any GUI application has to deal with the mouse, and SDL provides functions to manage mouse input and the displayed cursor.
Most interactions with the mouse will come through the event subsystem. Moving a mouse generates an SDL_EVENT_MOUSE_MOTION event, pushing a button generates SDL_EVENT_MOUSE_BUTTON_DOWN, etc, but one can also query the current state of the mouse at any time with SDL_GetMouseState().
For certain games, it's useful to disassociate the mouse cursor from mouse input. An FPS, for example, would not want the player's motion to stop as the mouse hits the edge of the window. For these scenarios, use SDL_SetWindowRelativeMouseMode(), which hides the cursor, grabs mouse input to the window, and reads mouse input no matter how far it moves.
Games that want the system to track the mouse but want to draw their own cursor can use SDL_HideCursor() and SDL_ShowCursor(). It might be more efficient to let the system manage the cursor, if possible, using SDL_SetCursor() with a custom image made through SDL_CreateColorCursor(), or perhaps just a specific system cursor from SDL_CreateSystemCursor().
SDL can, on many platforms, differentiate between multiple connected mice, allowing for interesting input scenarios and multiplayer games. They can be enumerated with SDL_GetMice(), and SDL will send SDL_EVENT_MOUSE_ADDED and SDL_EVENT_MOUSE_REMOVED events as they are connected and unplugged.
Since many apps only care about basic mouse input, SDL offers a virtual mouse device for touch and pen input, which often can make a desktop application work on a touchscreen phone without any code changes. Apps that care about touch/pen separately from mouse input should filter out events with a which field of SDL_TOUCH_MOUSEID/SDL_PEN_MOUSEID. This is a unique ID for a mouse for the time it is connected to the system, and is never reused for the lifetime of the application.
If the mouse is disconnected and reconnected, it will get a new ID.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
SDL_MouseMotionTransformCallback
typedef void(SDLCALL * SDL_MouseMotionTransformCallback) (void *userdata, Uint64 timestamp, SDL_Window *window, SDL_MouseID mouseID, float *x, float *y)
A callback used to transform mouse motion delta from raw values.
This is called during SDL's handling of platform mouse events to scale the values of the resulting motion delta.
Parameters
userdata what was passed as userdata to SDL_SetRelativeMouseTransform().
timestamp the associated time at which this mouse motion event was received.
window the associated window to which this mouse motion event was addressed.
mouseID the associated mouse from which this mouse motion event was emitted.
x pointer to a variable that will be treated as the resulting x-axis motion.
y pointer to a variable that will be treated as the resulting y-axis motion.
Thread Safety
This callback is called by SDL's internal mouse input processing procedure, which may be a thread separate from the main event loop that is run at realtime priority. Stalling this thread with too much work in the callback can therefore potentially freeze the entire system. Care should be taken with proper synchronization practices when adding other side effects beyond mutation of the x and y values.
Since
This datatype is available since SDL 3.4.0.
See also
SDL_SetRelativeMouseTransform
SDL_MouseWheelDirection
typedef enum SDL_MouseWheelDirection SDL_MouseWheelDirection
Scroll direction types for the Scroll event
Since
This enum is available since SDL 3.2.0.
SDL_SystemCursor
typedef enum SDL_SystemCursor SDL_SystemCursor
Cursor types for SDL_CreateSystemCursor().
Since
This enum is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_MouseWheelDirection
enum SDL_MouseWheelDirection
Scroll direction types for the Scroll event
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_MOUSEWHEEL_NORMAL
The scroll direction is normal
SDL_MOUSEWHEEL_FLIPPED
The scroll direction is flipped / natural
{
    SDL_MOUSEWHEEL_NORMAL,    /**< The scroll direction is normal */
    SDL_MOUSEWHEEL_FLIPPED    /**< The scroll direction is flipped / natural */
} SDL_MouseWheelDirection;
SDL_SystemCursor
enum SDL_SystemCursor
Cursor types for SDL_CreateSystemCursor().
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_SYSTEM_CURSOR_DEFAULT
Default cursor. Usually an arrow.
SDL_SYSTEM_CURSOR_TEXT
Text selection. Usually an I-beam.
SDL_SYSTEM_CURSOR_WAIT
Wait. Usually an hourglass or watch or spinning ball.
SDL_SYSTEM_CURSOR_CROSSHAIR
Crosshair.
SDL_SYSTEM_CURSOR_PROGRESS
Program is busy but still interactive. Usually it's WAIT with an arrow.
SDL_SYSTEM_CURSOR_NWSE_RESIZE
Double arrow pointing northwest and southeast.
SDL_SYSTEM_CURSOR_NESW_RESIZE
Double arrow pointing northeast and southwest.
SDL_SYSTEM_CURSOR_EW_RESIZE
Double arrow pointing west and east.
SDL_SYSTEM_CURSOR_NS_RESIZE
Double arrow pointing north and south.
SDL_SYSTEM_CURSOR_MOVE
Four pointed arrow pointing north, south, east, and west.
SDL_SYSTEM_CURSOR_NOT_ALLOWED
Not permitted. Usually a slashed circle or crossbones.
SDL_SYSTEM_CURSOR_POINTER
Pointer that indicates a link. Usually a pointing hand.
SDL_SYSTEM_CURSOR_NW_RESIZE
Window resize top-left. This may be a single arrow or a double arrow like NWSE_RESIZE.
SDL_SYSTEM_CURSOR_N_RESIZE
Window resize top. May be NS_RESIZE.
SDL_SYSTEM_CURSOR_NE_RESIZE
Window resize top-right. May be NESW_RESIZE.
SDL_SYSTEM_CURSOR_E_RESIZE
Window resize right. May be EW_RESIZE.
SDL_SYSTEM_CURSOR_SE_RESIZE
Window resize bottom-right. May be NWSE_RESIZE.
SDL_SYSTEM_CURSOR_S_RESIZE
Window resize bottom. May be NS_RESIZE.
SDL_SYSTEM_CURSOR_SW_RESIZE
Window resize bottom-left. May be NESW_RESIZE.
SDL_SYSTEM_CURSOR_W_RESIZE
Window resize left. May be EW_RESIZE.
SDL_SYSTEM_CURSOR_COUNT
{
    SDL_SYSTEM_CURSOR_DEFAULT,      /**< Default cursor. Usually an arrow. */
    SDL_SYSTEM_CURSOR_TEXT,         /**< Text selection. Usually an I-beam. */
    SDL_SYSTEM_CURSOR_WAIT,         /**< Wait. Usually an hourglass or watch or spinning ball. */
    SDL_SYSTEM_CURSOR_CROSSHAIR,    /**< Crosshair. */
    SDL_SYSTEM_CURSOR_PROGRESS,     /**< Program is busy but still interactive. Usually it's WAIT with an arrow. */
    SDL_SYSTEM_CURSOR_NWSE_RESIZE,  /**< Double arrow pointing northwest and southeast. */
    SDL_SYSTEM_CURSOR_NESW_RESIZE,  /**< Double arrow pointing northeast and southwest. */
    SDL_SYSTEM_CURSOR_EW_RESIZE,    /**< Double arrow pointing west and east. */
    SDL_SYSTEM_CURSOR_NS_RESIZE,    /**< Double arrow pointing north and south. */
    SDL_SYSTEM_CURSOR_MOVE,         /**< Four pointed arrow pointing north, south, east, and west. */
    SDL_SYSTEM_CURSOR_NOT_ALLOWED,  /**< Not permitted. Usually a slashed circle or crossbones. */
    SDL_SYSTEM_CURSOR_POINTER,      /**< Pointer that indicates a link. Usually a pointing hand. */
    SDL_SYSTEM_CURSOR_NW_RESIZE,    /**< Window resize top-left. This may be a single arrow or a double arrow like NWSE_RESIZE. */
    SDL_SYSTEM_CURSOR_N_RESIZE,     /**< Window resize top. May be NS_RESIZE. */
    SDL_SYSTEM_CURSOR_NE_RESIZE,    /**< Window resize top-right. May be NESW_RESIZE. */
    SDL_SYSTEM_CURSOR_E_RESIZE,     /**< Window resize right. May be EW_RESIZE. */
    SDL_SYSTEM_CURSOR_SE_RESIZE,    /**< Window resize bottom-right. May be NWSE_RESIZE. */
    SDL_SYSTEM_CURSOR_S_RESIZE,     /**< Window resize bottom. May be NS_RESIZE. */
    SDL_SYSTEM_CURSOR_SW_RESIZE,    /**< Window resize bottom-left. May be NESW_RESIZE. */
    SDL_SYSTEM_CURSOR_W_RESIZE,     /**< Window resize left. May be EW_RESIZE. */
    SDL_SYSTEM_CURSOR_COUNT
} SDL_SystemCursor;
Function Documentation
SDL_CaptureMouse()
SDL_DECLSPEC bool SDLCALL SDL_CaptureMouse (bool enabled) extern
Capture the mouse and to track input outside an SDL window.
Capturing enables your app to obtain mouse events globally, instead of just within your window. Not all video targets support this function. When capturing is enabled, the current window will get all mouse events, but unlike relative mode, no change is made to the cursor and it is not restrained to your window.
This function may also deny mouse input to other windows–both those in your application and others on the system–so you should use this function sparingly, and in small bursts. For example, you might want to track the mouse while the user is dragging something, until the user releases a mouse button. It is not recommended that you capture the mouse for long periods of time, such as the entire time your app is running. For that, you should probably use SDL_SetWindowRelativeMouseMode() or SDL_SetWindowMouseGrab(), depending on your goals.
While captured, mouse events still report coordinates relative to the current (foreground) window, but those coordinates may be outside the bounds of the window (including negative values). Capturing is only allowed for the foreground window. If the window loses focus while capturing, the capture will be disabled automatically.
While capturing is enabled, the current window will have the SDL_WINDOW_MOUSE_CAPTURE flag set.
Please note that SDL will attempt to "auto capture" the mouse while the user is pressing a button; this is to try and make mouse behavior more consistent between platforms, and deal with the common case of a user dragging the mouse outside of the window. This means that if you are calling SDL_CaptureMouse() only to deal with this situation, you do not have to (although it is safe to do so). If this causes problems for your app, you can disable auto capture by setting the SDL_HINT_MOUSE_AUTO_CAPTURE hint to zero.
Parameters
enabled true to enable capturing, false to disable.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGlobalMouseState
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (!mouse->CaptureMouse) {
        return SDL_Unsupported();
    }
#if defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
    /* Windows mouse capture is tied to the current thread, and must be called
     * from the thread that created the window being captured. Since we update
     * the mouse capture state from the event processing, any application state
     * changes must be processed on that thread as well.
     */
    if (!SDL_OnVideoThread()) {
        return SDL_SetError("SDL_CaptureMouse() must be called on the main thread");
    }
#endif // defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
    if (enabled && SDL_GetKeyboardFocus() == NULL) {
        return SDL_SetError("No window has focus");
    }
    mouse->capture_desired = enabled;
    return SDL_UpdateMouseCapture(false);
}
References SDL_Mouse::capture_desired, SDL_Mouse::CaptureMouse, NULL, SDL_GetKeyboardFocus(), SDL_GetMouse(), SDL_OnVideoThread(), SDL_SetError(), SDL_Unsupported, and SDL_UpdateMouseCapture().
Referenced by SDL_QuitMouse().
SDL_CreateColorCursor()
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_CreateColorCursor (SDL_Surface * surface, int hot_x, int hot_y) extern
Create a color cursor.
If this function is passed a surface with alternate representations added with SDL_AddSurfaceAlternateImage(), the surface will be interpreted as the content to be used for 100% display scale, and the alternate representations will be used for high DPI situations. For example, if the original surface is 32x32, then on a 2x macOS display or 200% display scale on Windows, a 64x64 version of the image will be used, if available. If a matching version of the image isn't available, the closest larger size image will be downscaled to the appropriate size and be used instead, if available. Otherwise, the closest smaller image will be upscaled and be used instead.
Parameters
surface an SDL_Surface structure representing the cursor image.
hot_x the x position of the cursor hot spot.
hot_y the y position of the cursor hot spot.
Returns
the new cursor on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddSurfaceAlternateImage
SDL_CreateCursor
SDL_CreateSystemCursor
SDL_DestroyCursor
SDL_SetCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_Surface *temp = NULL;
    SDL_Cursor *cursor;
    if (!surface) {
        SDL_InvalidParamError("surface");
        return NULL;
    }
    // Allow specifying the hot spot via properties on the surface
    SDL_PropertiesID props = SDL_GetSurfaceProperties(surface);
    hot_x = (int)SDL_GetNumberProperty(props, SDL_PROP_SURFACE_HOTSPOT_X_NUMBER, hot_x);
    hot_y = (int)SDL_GetNumberProperty(props, SDL_PROP_SURFACE_HOTSPOT_Y_NUMBER, hot_y);
    // Sanity check the hot spot
    if ((hot_x < 0) || (hot_y < 0) ||
        (hot_x >= surface->w) || (hot_y >= surface->h)) {
        SDL_SetError("Cursor hot spot doesn't lie within cursor");
        return NULL;
    }
    if (surface->format != SDL_PIXELFORMAT_ARGB8888) {
        temp = SDL_ConvertSurface(surface, SDL_PIXELFORMAT_ARGB8888);
        if (!temp) {
            return NULL;
        }
        surface = temp;
    }
    if (mouse->CreateCursor) {
        cursor = mouse->CreateCursor(surface, hot_x, hot_y);
    } else {
        cursor = (SDL_Cursor *)SDL_calloc(1, sizeof(*cursor));
    }
    if (cursor) {
        cursor->next = mouse->cursors;
        mouse->cursors = cursor;
    }
    SDL_DestroySurface(temp);
    return cursor;
}
References SDL_Mouse::CreateCursor, SDL_Mouse::cursors, SDL_Cursor::next, NULL, SDL_calloc(), SDL_ConvertSurface(), SDL_DestroySurface(), SDL_GetMouse(), SDL_GetNumberProperty(), SDL_GetSurfaceProperties(), SDL_InvalidParamError, SDL_PIXELFORMAT_ARGB8888, SDL_PROP_SURFACE_HOTSPOT_X_NUMBER, SDL_PROP_SURFACE_HOTSPOT_Y_NUMBER, and SDL_SetError().
Referenced by SDL_CreateCursor(), and SDL_PostInitMouse().
SDL_CreateCursor()
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_CreateCursor (const Uint8 * data, const Uint8 * mask, int w, int h, int hot_x, int hot_y) extern
Create a cursor using the specified bitmap data and mask (in MSB format).
mask has to be in MSB (Most Significant Bit) format.
The cursor width (w) must be a multiple of 8 bits.
The cursor is created in black and white according to the following:
data=0, mask=1: white
data=1, mask=1: black
data=0, mask=0: transparent
data=1, mask=0: inverted color if possible, black if not.
Cursors created with this function must be freed with SDL_DestroyCursor().
If you want to have a color cursor, or create your cursor from an SDL_Surface, you should use SDL_CreateColorCursor(). Alternately, you can hide the cursor and draw your own as part of your game's rendering, but it will be bound to the framerate.
Also, SDL_CreateSystemCursor() is available, which provides several readily-available system cursors to pick from.
Parameters
data the color value for each pixel of the cursor.
mask the mask value for each pixel of the cursor.
w the width of the cursor.
h the height of the cursor.
hot_x the x-axis offset from the left of the cursor image to the mouse x position, in the range of 0 to w - 1.
hot_y the y-axis offset from the top of the cursor image to the mouse y position, in the range of 0 to h - 1.
Returns
a new cursor with the specified parameters on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateColorCursor
SDL_CreateSystemCursor
SDL_DestroyCursor
SDL_SetCursor
{
    SDL_Surface *surface;
    SDL_Cursor *cursor;
    int x, y;
    Uint32 *pixels;
    Uint8 datab = 0, maskb = 0;
    const Uint32 black = 0xFF000000;
    const Uint32 white = 0xFFFFFFFF;
    const Uint32 transparent = 0x00000000;
#if defined(SDL_PLATFORM_WIN32)
    // Only Windows backend supports inverted pixels in mono cursors.
    const Uint32 inverted = 0x00FFFFFF;
#else
    const Uint32 inverted = 0xFF000000;
#endif // defined(SDL_PLATFORM_WIN32)
    // Make sure the width is a multiple of 8
    w = ((w + 7) & ~7);
    // Create the surface from a bitmap
    surface = SDL_CreateSurface(w, h, SDL_PIXELFORMAT_ARGB8888);
    if (!surface) {
        return NULL;
    }
    for (y = 0; y < h; ++y) {
        pixels = (Uint32 *)((Uint8 *)surface->pixels + y * surface->pitch);
        for (x = 0; x < w; ++x) {
            if ((x % 8) == 0) {
                datab = *data++;
                maskb = *mask++;
            }
            if (maskb & 0x80) {
                *pixels++ = (datab & 0x80) ? black : white;
            } else {
                *pixels++ = (datab & 0x80) ? inverted : transparent;
            }
            datab <<= 1;
            maskb <<= 1;
        }
    }
    cursor = SDL_CreateColorCursor(surface, hot_x, hot_y);
    SDL_DestroySurface(surface);
    return cursor;
}
References NULL, SDL_CreateColorCursor(), SDL_CreateSurface(), SDL_DestroySurface(), and SDL_PIXELFORMAT_ARGB8888.
SDL_CreateSystemCursor()
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_CreateSystemCursor (SDL_SystemCursor id) extern
Create a system cursor.
Parameters
id an SDL_SystemCursor enum value.
Returns
a cursor on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_Cursor *cursor;
    if (!mouse->CreateSystemCursor) {
        SDL_SetError("CreateSystemCursor is not currently supported");
        return NULL;
    }
    cursor = mouse->CreateSystemCursor(id);
    if (cursor) {
        cursor->next = mouse->cursors;
        mouse->cursors = cursor;
    }
    return cursor;
}
References SDL_Mouse::CreateSystemCursor, SDL_Mouse::cursors, SDL_Cursor::next, NULL, SDL_GetMouse(), and SDL_SetError().
SDL_CursorVisible()
SDL_DECLSPEC bool SDLCALL SDL_CursorVisible (void) extern
Return whether the cursor is currently being shown.
Returns
true if the cursor is being shown, or false if the cursor is hidden.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HideCursor
SDL_ShowCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    return mouse->cursor_visible;
}
References SDL_Mouse::cursor_visible, and SDL_GetMouse().
Referenced by SDL_BLooper::_HandleMouseMove(), and SDL_ShowMessageBox().
SDL_DestroyCursor()
SDL_DECLSPEC void SDLCALL SDL_DestroyCursor (SDL_Cursor * cursor) extern
Free a previously-created cursor.
Use this function to free cursor resources created with SDL_CreateCursor(), SDL_CreateColorCursor() or SDL_CreateSystemCursor().
Parameters
cursor the cursor to free.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateColorCursor
SDL_CreateCursor
SDL_CreateSystemCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_Cursor *curr, *prev;
    if (!cursor) {
        return;
    }
    if (cursor == mouse->def_cursor) {
        return;
    }
    if (cursor == mouse->cur_cursor) {
        SDL_SetCursor(mouse->def_cursor);
    }
    for (prev = NULL, curr = mouse->cursors; curr;
         prev = curr, curr = curr->next) {
        if (curr == cursor) {
            if (prev) {
                prev->next = curr->next;
            } else {
                mouse->cursors = curr->next;
            }
            if (mouse->FreeCursor && curr->internal) {
                mouse->FreeCursor(curr);
            } else {
                SDL_free(curr);
            }
            return;
        }
    }
}
References SDL_Mouse::cur_cursor, SDL_Mouse::cursors, SDL_Mouse::def_cursor, SDL_Mouse::FreeCursor, SDL_Cursor::internal, SDL_Cursor::next, NULL, SDL_free(), SDL_GetMouse(), and SDL_SetCursor().
Referenced by SDL_QuitMouse().
SDL_GetCursor()
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_GetCursor (void) extern
Get the active cursor.
This function returns a pointer to the current cursor which is owned by the library. It is not necessary to free the cursor with SDL_DestroyCursor().
Returns
the active cursor or NULL if there is no mouse.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (!mouse) {
        return NULL;
    }
    return mouse->cur_cursor;
}
References SDL_Mouse::cur_cursor, NULL, and SDL_GetMouse().
SDL_GetDefaultCursor()
SDL_DECLSPEC SDL_Cursor *SDLCALL SDL_GetDefaultCursor (void) extern
Get the default cursor.
You do not have to call SDL_DestroyCursor() on the return value, but it is safe to do so.
Returns
the default cursor on success or NULL on failuree; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (!mouse) {
        return NULL;
    }
    return mouse->def_cursor;
}
References SDL_Mouse::def_cursor, NULL, and SDL_GetMouse().
SDL_GetGlobalMouseState()
SDL_DECLSPEC SDL_MouseButtonFlags SDLCALL SDL_GetGlobalMouseState (float * x, float * y) extern
Query the platform for the asynchronous mouse button state and the desktop-relative platform-cursor position.
This function immediately queries the platform for the most recent asynchronous state, more costly than retrieving SDL's cached state in SDL_GetMouseState().
Passing non-NULL pointers to x or y will write the destination with respective x or y coordinates relative to the desktop.
In Relative Mode, the platform-cursor's position usually contradicts the SDL-cursor's position as manually calculated from SDL_GetMouseState() and SDL_GetWindowPosition.
This function can be useful if you need to track the mouse outside of a specific window and SDL_CaptureMouse() doesn't fit your needs. For example, it could be useful if you need to track the mouse while dragging a window, where coordinates relative to a window might not be in sync at all times.
Parameters
x a pointer to receive the platform-cursor's x-position from the desktop's top left corner, can be NULL if unused.
y a pointer to receive the platform-cursor's y-position from the desktop's top left corner, can be NULL if unused.
Returns
a 32-bit bitmask of the button state that can be bitwise-compared against the SDL_BUTTON_MASK(X) macro.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CaptureMouse
SDL_GetMouseState
SDL_GetGlobalMouseState
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->GetGlobalMouseState) {
        float tmpx, tmpy;
        // make sure these are never NULL for the backend implementations...
        if (!x) {
            x = &tmpx;
        }
        if (!y) {
            y = &tmpy;
        }
        *x = *y = 0.0f;
        return mouse->GetGlobalMouseState(x, y);
    } else {
        return SDL_GetMouseState(x, y);
    }
}
References SDL_Mouse::GetGlobalMouseState, SDL_GetMouse(), and SDL_GetMouseState().
SDL_GetMice()
SDL_DECLSPEC SDL_MouseID *SDLCALL SDL_GetMice (int * count) extern
Get a list of currently connected mice.
Note that this will include any device or virtual driver that includes mouse functionality, including some game controllers, KVM switches, etc. You should wait for input from a device before you consider it actively in use.
Parameters
count a pointer filled in with the number of mice returned, may be NULL.
Returns
a 0 terminated array of mouse instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMouseNameForID
SDL_HasMouse
{
    int i;
    SDL_MouseID *mice;
    mice = (SDL_JoystickID *)SDL_malloc((SDL_mouse_count + 1) * sizeof(*mice));
    if (mice) {
        if (count) {
            *count = SDL_mouse_count;
        }
        for (i = 0; i < SDL_mouse_count; ++i) {
            mice[i] = SDL_mice[i].instance_id;
        }
        mice[i] = 0;
    } else {
        if (count) {
            *count = 0;
        }
    }
    return mice;
}
References count, SDL_malloc(), SDL_mice, and SDL_mouse_count.
SDL_GetMouseFocus()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetMouseFocus (void) extern
Get the window which currently has mouse focus.
Returns
the window with mouse focus.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_Mouse *mouse = SDL_GetMouse();
    return mouse->focus;
}
References SDL_Mouse::focus, and SDL_GetMouse().
Referenced by SDL_BLooper::_HandleMouseFocus(), SDL_DestroyWindow(), and SDL_RestoreMousePosition().
SDL_GetMouseNameForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetMouseNameForID (SDL_MouseID instance_id) extern
Get the name of a mouse.
This function returns "" if the mouse doesn't have a name.
Parameters
instance_id the mouse instance ID.
Returns
the name of the selected mouse, or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMice
{
    int mouse_index = SDL_GetMouseIndex(instance_id);
    if (mouse_index < 0) {
        SDL_SetError("Mouse %" SDL_PRIu32 " not found", instance_id);
        return NULL;
    }
    return SDL_GetPersistentString(SDL_mice[mouse_index].name);
}
References NULL, SDL_GetMouseIndex(), SDL_GetPersistentString(), SDL_mice, SDL_PRIu32, and SDL_SetError().
SDL_GetMouseState()
SDL_DECLSPEC SDL_MouseButtonFlags SDLCALL SDL_GetMouseState (float * x, float * y) extern
Query SDL's cache for the synchronous mouse button state and the window-relative SDL-cursor position.
This function returns the cached synchronous state as SDL understands it from the last pump of the event queue.
To query the platform for immediate asynchronous state, use SDL_GetGlobalMouseState.
Passing non-NULL pointers to x or y will write the destination with respective x or y coordinates relative to the focused window.
In Relative Mode, the SDL-cursor's position usually contradicts the platform-cursor's position as manually calculated from SDL_GetGlobalMouseState() and SDL_GetWindowPosition.
Parameters
x a pointer to receive the SDL-cursor's x-position from the focused window's top left corner, can be NULL if unused.
y a pointer to receive the SDL-cursor's y-position from the focused window's top left corner, can be NULL if unused.
Returns
a 32-bit bitmask of the button state that can be bitwise-compared against the SDL_BUTTON_MASK(X) macro.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGlobalMouseState
SDL_GetRelativeMouseState
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (x) {
        *x = mouse->x;
    }
    if (y) {
        *y = mouse->y;
    }
    return SDL_GetMouseButtonState(mouse, SDL_GLOBAL_MOUSE_ID, true);
}
References SDL_GetMouse(), SDL_GetMouseButtonState(), SDL_GLOBAL_MOUSE_ID, SDL_Mouse::x, and SDL_Mouse::y.
Referenced by SDL_GetGlobalMouseState(), and SDL_RestoreMousePosition().
SDL_GetRelativeMouseState()
SDL_DECLSPEC SDL_MouseButtonFlags SDLCALL SDL_GetRelativeMouseState (float * x, float * y) extern
Query SDL's cache for the synchronous mouse button state and accumulated mouse delta since last call.
This function returns the cached synchronous state as SDL understands it from the last pump of the event queue.
To query the platform for immediate asynchronous state, use SDL_GetGlobalMouseState.
Passing non-NULL pointers to x or y will write the destination with respective x or y deltas accumulated since the last call to this function (or since event initialization).
This function is useful for reducing overhead by processing relative mouse inputs in one go per-frame instead of individually per-event, at the expense of losing the order between events within the frame (e.g. quickly pressing and releasing a button within the same frame).
Parameters
x a pointer to receive the x mouse delta accumulated since last call, can be NULL if unused.
y a pointer to receive the y mouse delta accumulated since last call, can be NULL if unused.
Returns
a 32-bit bitmask of the button state that can be bitwise-compared against the SDL_BUTTON_MASK(X) macro.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMouseState
SDL_GetGlobalMouseState
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (x) {
        *x = mouse->x_accu;
    }
    if (y) {
        *y = mouse->y_accu;
    }
    mouse->x_accu = 0.0f;
    mouse->y_accu = 0.0f;
    return SDL_GetMouseButtonState(mouse, SDL_GLOBAL_MOUSE_ID, true);
}
References SDL_GetMouse(), SDL_GetMouseButtonState(), SDL_GLOBAL_MOUSE_ID, SDL_Mouse::x_accu, and SDL_Mouse::y_accu.
SDL_GetWindowRelativeMouseMode()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowRelativeMouseMode (SDL_Window * window) extern
Query whether relative mouse mode is enabled for a window.
Parameters
window the window to query.
Returns
true if relative mode is enabled for a window or false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowRelativeMouseMode
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->flags & SDL_WINDOW_MOUSE_RELATIVE_MODE) {
        return true;
    } else {
        return false;
    }
}
References CHECK_WINDOW_MAGIC, and SDL_WINDOW_MOUSE_RELATIVE_MODE.
Referenced by SDL_SetWindowRelativeMouseMode().
SDL_HasMouse()
SDL_DECLSPEC bool SDLCALL SDL_HasMouse (void) extern
Return whether a mouse is currently connected.
Returns
true if a mouse is connected, false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMice
{
    return (SDL_mouse_count > 0);
}
References SDL_mouse_count.
SDL_HideCursor()
SDL_DECLSPEC bool SDLCALL SDL_HideCursor (void) extern
Hide the cursor.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CursorVisible
SDL_ShowCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->cursor_visible) {
        mouse->cursor_visible = false;
        SDL_RedrawCursor();
    }
    return true;
}
References SDL_Mouse::cursor_visible, SDL_GetMouse(), and SDL_RedrawCursor().
Referenced by SDL_ShowMessageBox().
SDL_SetCursor()
SDL_DECLSPEC bool SDLCALL SDL_SetCursor (SDL_Cursor * cursor) extern
Set the active cursor.
This function sets the currently active cursor to the specified one. If the cursor is currently visible, the change will be immediately represented on the display. SDL_SetCursor(NULL) can be used to force cursor redraw, if this is desired for any reason.
Parameters
cursor a cursor to make active.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    // already on this cursor, no further action required
    if (cursor == mouse->cur_cursor) {
        return true;
    }
    // Set the new cursor
    if (cursor) {
        // Make sure the cursor is still valid for this mouse
        if (cursor != mouse->def_cursor) {
            SDL_Cursor *found;
            for (found = mouse->cursors; found; found = found->next) {
                if (found == cursor) {
                    break;
                }
            }
            if (!found) {
                return SDL_SetError("Cursor not associated with the current mouse");
            }
        }
        mouse->cur_cursor = cursor;
    }
    SDL_RedrawCursor();
    return true;
}
References SDL_Mouse::cur_cursor, SDL_Mouse::cursors, SDL_Mouse::def_cursor, SDL_Cursor::next, SDL_GetMouse(), SDL_RedrawCursor(), and SDL_SetError().
Referenced by SDL_DestroyCursor(), and SDL_SetDefaultCursor().
SDL_SetRelativeMouseTransform()
SDL_DECLSPEC bool SDLCALL SDL_SetRelativeMouseTransform (SDL_MouseMotionTransformCallback callback, void * userdata) extern
Set a user-defined function by which to transform relative mouse inputs.
This overrides the relative system scale and relative speed scale hints. Should be called prior to enabling relative mouse mode, fails otherwise.
Parameters
callback a callback used to transform relative mouse motion, or NULL for default behavior.
userdata a pointer that will be passed to callback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->relative_mode) {
        return SDL_SetError("Can't set mouse transform while relative mode is active");
    }
    mouse->InputTransform = transform;
    mouse->input_transform_data = userdata;
    return true;
}
References SDL_Mouse::input_transform_data, SDL_Mouse::InputTransform, SDL_Mouse::relative_mode, SDL_GetMouse(), and SDL_SetError().
SDL_SetWindowRelativeMouseMode()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowRelativeMouseMode (SDL_Window * window, bool enabled) extern
Set relative mouse mode for a window.
While the window has focus and relative mouse mode is enabled, the cursor is hidden, the mouse position is constrained to the window, and SDL will report continuous relative mouse motion even if the mouse is at the edge of the window.
If you'd like to keep the mouse position fixed while in relative mode you can use SDL_SetWindowMouseRect(). If you'd like the cursor to be at a specific location when relative mode ends, you should use SDL_WarpMouseInWindow() before disabling relative mode.
This function will flush any pending mouse motion for this window.
Parameters
window the window to change.
enabled true to enable relative mode, false to disable.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowRelativeMouseMode
{
    CHECK_WINDOW_MAGIC(window, false);
    /* If the app toggles relative mode directly, it probably shouldn't
     * also be emulating it using repeated mouse warps, so disable
     * mouse warp emulation by default.
     */
    SDL_DisableMouseWarpEmulation();
    if (enabled == SDL_GetWindowRelativeMouseMode(window)) {
        return true;
    }
    if (enabled) {
        window->flags |= SDL_WINDOW_MOUSE_RELATIVE_MODE;
    } else {
        window->flags &= ~SDL_WINDOW_MOUSE_RELATIVE_MODE;
    }
    SDL_UpdateRelativeMouseMode();
    return true;
}
References CHECK_WINDOW_MAGIC, SDL_DisableMouseWarpEmulation(), SDL_GetWindowRelativeMouseMode(), SDL_UpdateRelativeMouseMode(), and SDL_WINDOW_MOUSE_RELATIVE_MODE.
SDL_ShowCursor()
SDL_DECLSPEC bool SDLCALL SDL_ShowCursor (void) extern
Show the cursor.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CursorVisible
SDL_HideCursor
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->warp_emulation_active) {
        SDL_SetRelativeMouseMode(false);
        mouse->warp_emulation_active = false;
    }
    if (!mouse->cursor_visible) {
        mouse->cursor_visible = true;
        SDL_RedrawCursor();
    }
    return true;
}
References SDL_Mouse::cursor_visible, SDL_GetMouse(), SDL_RedrawCursor(), SDL_SetRelativeMouseMode(), and SDL_Mouse::warp_emulation_active.
Referenced by SDL_QuitMouse(), and SDL_ShowMessageBox().
SDL_WarpMouseGlobal()
SDL_DECLSPEC bool SDLCALL SDL_WarpMouseGlobal (float x, float y) extern
Move the mouse to the given position in global screen space.
This function generates a mouse motion event.
A failure of this function usually means that it is unsupported by a platform.
Note that this function will appear to succeed, but not actually move the mouse when used over Microsoft Remote Desktop.
Parameters
x the x coordinate.
y the y coordinate.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_WarpMouseInWindow
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->WarpMouseGlobal) {
        return mouse->WarpMouseGlobal(x, y);
    }
    return SDL_Unsupported();
}
References SDL_GetMouse(), SDL_Unsupported, and SDL_Mouse::WarpMouseGlobal.
Referenced by SDL_SetKeyboardFocus().
SDL_WarpMouseInWindow()
SDL_DECLSPEC void SDLCALL SDL_WarpMouseInWindow (SDL_Window * window, float x, float y) extern
Move the mouse cursor to the given position within the window.
This function generates a mouse motion event if relative mode is not enabled. If relative mode is enabled, you can force mouse events for the warp by setting the SDL_HINT_MOUSE_RELATIVE_WARP_MOTION hint.
Note that this function will appear to succeed, but not actually move the mouse when used over Microsoft Remote Desktop.
Parameters
window the window to move the mouse into, or NULL for the current mouse focus.
x the x coordinate within the window.
y the y coordinate within the window.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_WarpMouseGlobal
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_MaybeEnableWarpEmulation(window, x, y);
    SDL_PerformWarpMouseInWindow(window, x, y, mouse->warp_emulation_active);
}
References SDL_GetMouse(), SDL_MaybeEnableWarpEmulation(), SDL_PerformWarpMouseInWindow(), and SDL_Mouse::warp_emulation_active.
Referenced by SDL_RestoreMousePosition().