SDL3: SDL-main/src/stdlib/SDL_string.c File Reference
SDL_string.c File Reference
#include "SDL_internal.h"
#include "SDL_vacopy.h"
#include "SDL_sysstdlib.h"
#include "SDL_casefolding.h"
Data Structures
struct SDL_FormatInfo
Macros
#define SDL_SIZEOF_WCHAR_T 4
#define TEXT_AND_LEN_ARGS (length < maxlen) ? &text[length] : NULL, (length < maxlen) ? (maxlen - length) : 0
#define UNICODE_STRCASECMP(bits, slen1, slen2, update_slen1, update_slen2)
#define UTF8_IsLeadByte(c)
#define UTF8_IsTrailingByte(c)
Enumerations
enum SDL_letter_case { SDL_CASE_NOCHANGE , SDL_CASE_LOWER , SDL_CASE_UPPER }
Functions
static bool CharacterMatchesSet (char c, const char *set, size_t set_len)
int SDL_asprintf (char **strp, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
double SDL_atof (const char *string)
int SDL_atoi (const char *string)
int SDL_CaseFoldUnicode (Uint32 from, Uint32 *to)
SDL_COMPILE_TIME_ASSERT (sizeof_wchar_t, sizeof(wchar_t)==4)
SDL_COMPILE_TIME_ASSERT (wchar_t_int, sizeof(wchar_t)<=sizeof(int))
static void SDL_IntPrecisionAdjust (char *num, size_t maxlen, SDL_FormatInfo *info)
char * SDL_itoa (int value, char *string, int radix)
char * SDL_lltoa (long long value, char *string, int radix)
char * SDL_ltoa (long value, char *string, int radix)
int SDL_memcmp (const void *s1, const void *s2, size_t len)
static size_t SDL_PrintFloat (char *text, size_t maxlen, SDL_FormatInfo *info, double arg, bool g)
static size_t SDL_PrintLong (char *text, size_t maxlen, SDL_FormatInfo *info, long value)
static size_t SDL_PrintLongLong (char *text, size_t maxlen, SDL_FormatInfo *info, long long value)
static size_t SDL_PrintPointer (char *text, size_t maxlen, SDL_FormatInfo *info, const void *value)
static size_t SDL_PrintString (char *text, size_t maxlen, SDL_FormatInfo *info, const char *string)
static size_t SDL_PrintStringW (char *text, size_t maxlen, SDL_FormatInfo *info, const wchar_t *wide_string)
static size_t SDL_PrintUnsignedLong (char *text, size_t maxlen, SDL_FormatInfo *info, unsigned long value)
static size_t SDL_PrintUnsignedLongLong (char *text, size_t maxlen, SDL_FormatInfo *info, unsigned long long value)
static size_t SDL_ScanFloat (const char *text, double *valuep)
static size_t SDL_ScanLong (const char *text, int count, int radix, long *valuep)
static size_t SDL_ScanLongLong (const char *text, int count, int radix, long long *valuep)
static size_t SDL_ScanLongW (const wchar_t *text, int count, int radix, long *valuep)
static size_t SDL_ScanUintPtrT (const char *text, uintptr_t *valuep)
static size_t SDL_ScanUnsignedLong (const char *text, int count, int radix, unsigned long *valuep)
static size_t SDL_ScanUnsignedLongLong (const char *text, int count, int radix, unsigned long long *valuep)
static size_t SDL_ScanUnsignedLongLongInternal (const char *text, int count, int radix, unsigned long long *valuep, bool *negativep)
static size_t SDL_ScanUnsignedLongLongInternalW (const wchar_t *text, int count, int radix, unsigned long long *valuep, bool *negativep)
int SDL_snprintf (SDL_OUT_Z_CAP(maxlen) char *text, size_t maxlen, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
int SDL_sscanf (const char *text, SDL_SCANF_FORMAT_STRING const char *fmt,...)
Uint32 SDL_StepBackUTF8 (const char *start, const char **pstr)
Uint32 SDL_StepUTF8 (const char **pstr, size_t *pslen)
int SDL_strcasecmp (const char *str1, const char *str2)
char * SDL_strcasestr (const char *haystack, const char *needle)
char * SDL_strchr (const char *string, int c)
int SDL_strcmp (const char *str1, const char *str2)
char * SDL_strdup (const char *string)
size_t SDL_strlcat (SDL_INOUT_Z_CAP(maxlen) char *dst, const char *src, size_t maxlen)
size_t SDL_strlcpy (SDL_OUT_Z_CAP(maxlen) char *dst, const char *src, size_t maxlen)
size_t SDL_strlen (const char *string)
char * SDL_strlwr (char *string)
int SDL_strncasecmp (const char *str1, const char *str2, size_t maxlen)
int SDL_strncmp (const char *str1, const char *str2, size_t maxlen)
char * SDL_strndup (const char *string, size_t maxlen)
size_t SDL_strnlen (const char *string, size_t maxlen)
char * SDL_strnstr (const char *haystack, const char *needle, size_t maxlen)
char * SDL_strpbrk (const char *str, const char *breakset)
char * SDL_strrchr (const char *string, int c)
char * SDL_strrev (char *string)
char * SDL_strstr (const char *haystack, const char *needle)
double SDL_strtod (const char *string, char **endp)
long SDL_strtol (const char *string, char **endp, int base)
long long SDL_strtoll (const char *string, char **endp, int base)
unsigned long SDL_strtoul (const char *string, char **endp, int base)
unsigned long long SDL_strtoull (const char *string, char **endp, int base)
char * SDL_strupr (char *string)
int SDL_swprintf (SDL_OUT_Z_CAP(maxlen) wchar_t *text, size_t maxlen, SDL_PRINTF_FORMAT_STRING const wchar_t *fmt,...)
char * SDL_UCS4ToUTF8 (Uint32 codepoint, char *dst)
char * SDL_uitoa (unsigned int value, char *string, int radix)
char * SDL_ulltoa (unsigned long long value, char *string, int radix)
char * SDL_ultoa (unsigned long value, char *string, int radix)
size_t SDL_utf8strlcpy (SDL_OUT_Z_CAP(dst_bytes) char *dst, const char *src, size_t dst_bytes)
size_t SDL_utf8strlen (const char *str)
size_t SDL_utf8strnlen (const char *str, size_t bytes)
int SDL_vasprintf (char **strp, SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap)
int SDL_vsnprintf (SDL_OUT_Z_CAP(maxlen) char *text, size_t maxlen, SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap)
int SDL_vsscanf (const char *text, SDL_SCANF_FORMAT_STRING const char *fmt, va_list ap)
int SDL_vswprintf (SDL_OUT_Z_CAP(maxlen) wchar_t *text, size_t maxlen, const wchar_t *fmt, va_list ap)
int SDL_wcscasecmp (const wchar_t *wstr1, const wchar_t *wstr2)
int SDL_wcscmp (const wchar_t *str1, const wchar_t *str2)
wchar_t * SDL_wcsdup (const wchar_t *string)
size_t SDL_wcslcat (SDL_INOUT_Z_CAP(maxlen) wchar_t *dst, const wchar_t *src, size_t maxlen)
size_t SDL_wcslcpy (SDL_OUT_Z_CAP(maxlen) wchar_t *dst, const wchar_t *src, size_t maxlen)
size_t SDL_wcslen (const wchar_t *string)
int SDL_wcsncasecmp (const wchar_t *wstr1, const wchar_t *wstr2, size_t maxlen)
int SDL_wcsncmp (const wchar_t *str1, const wchar_t *str2, size_t maxlen)
size_t SDL_wcsnlen (const wchar_t *string, size_t maxlen)
wchar_t * SDL_wcsnstr (const wchar_t *haystack, const wchar_t *needle, size_t maxlen)
wchar_t * SDL_wcsstr (const wchar_t *haystack, const wchar_t *needle)
long SDL_wcstol (const wchar_t *string, wchar_t **endp, int base)
static Uint32 StepUTF32 (const Uint32 **_str, const size_t slen)
static Uint32 StepUTF8 (const char **_str, const size_t slen)
static size_t UTF8_GetTrailingBytes (unsigned char c)
Variables
static const char ntoa_table []
Macro Definition Documentation
SDL_SIZEOF_WCHAR_T
#define SDL_SIZEOF_WCHAR_T 4
Referenced by SDL_COMPILE_TIME_ASSERT().
TEXT_AND_LEN_ARGS
#define TEXT_AND_LEN_ARGS (length < maxlen) ? &text[length] : NULL, (length < maxlen) ? (maxlen - length) : 0
Referenced by SDL_PrintPointer(), SDL_PrintStringW(), and SDL_vsnprintf().
UNICODE_STRCASECMP
#define UNICODE_STRCASECMP (bits, slen1, slen2, update_slen1, update_slen2)
#define UNICODE_STRCASECMP(bits, slen1, slen2, update_slen1, update_slen2) \
    Uint32 folded1[3], folded2[3]; \
    int head1 = 0, tail1 = 0, head2 = 0, tail2 = 0; \
    while (true) { \
        Uint32 cp1, cp2; \
        if (head1 != tail1) { \
            cp1 = folded1[tail1++]; \
        } else { \
            const Uint##bits *str1start = (const Uint##bits *) str1; \
            head1 = SDL_CaseFoldUnicode(StepUTF##bits(&str1, slen1), folded1); \
            update_slen1; \
            cp1 = folded1[0]; \
            tail1 = 1; \
        } \
        if (head2 != tail2) { \
            cp2 = folded2[tail2++]; \
        } else { \
            const Uint##bits *str2start = (const Uint##bits *) str2; \
            head2 = SDL_CaseFoldUnicode(StepUTF##bits(&str2, slen2), folded2); \
            update_slen2; \
            cp2 = folded2[0]; \
            tail2 = 1; \
        } \
        if (cp1 < cp2) { \
            return -1; \
        } else if (cp1 > cp2) { \
            return 1; \
        } else if (cp1 == 0) { \
            break;  /* complete match. */ \
        } \
    } \
    return 0
Referenced by SDL_strcasecmp(), SDL_strncasecmp(), SDL_wcscasecmp(), and SDL_wcsncasecmp().
UTF8_IsLeadByte
#define UTF8_IsLeadByte (c)
Value:
((c) >= 0xC0 && (c) <= 0xF4)
Referenced by SDL_utf8strlcpy().
UTF8_IsTrailingByte
#define UTF8_IsTrailingByte (c)
Value:
((c) >= 0x80 && (c) <= 0xBF)
Referenced by SDL_utf8strlcpy().
Enumeration Type Documentation
SDL_letter_case
enum SDL_letter_case
Enumerator
SDL_CASE_NOCHANGE
SDL_CASE_LOWER
SDL_CASE_UPPER
{
    SDL_CASE_NOCHANGE,
    SDL_CASE_LOWER,
    SDL_CASE_UPPER
} SDL_letter_case;
Function Documentation
CharacterMatchesSet()
bool CharacterMatchesSet (char c, const char * set, size_t set_len) static
{
    bool invert = false;
    bool result = false;
    if (*set == '^') {
        invert = true;
        ++set;
        --set_len;
    }
    while (set_len > 0 && !result) {
        if (set_len >= 3 && set[1] == '-') {
            char low_char = SDL_min(set[0], set[2]);
            char high_char = SDL_max(set[0], set[2]);
            if (c >= low_char && c <= high_char) {
                result = true;
            }
            set += 3;
            set_len -= 3;
        } else {
            if (c == *set) {
                result = true;
            }
            ++set;
            --set_len;
        }
    }
    if (invert) {
        result = !result;
    }
    return result;
}
References SDL_max, and SDL_min.
Referenced by SDL_vsscanf().
SDL_asprintf()
int SDL_asprintf (char ** strp, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
{
    va_list ap;
    int result;
    va_start(ap, fmt);
    result = SDL_vasprintf(strp, fmt, ap);
    va_end(ap);
    return result;
}
References SDL_PRINTF_FORMAT_STRING, and SDL_vasprintf().
SDL_atof()
double SDL_atof (const char * str)
Parse a double from a string.
The result of calling SDL_atof(str) is equivalent to SDL_strtod(str, NULL).
Parameters
str The null-terminated string to read. Must not be NULL.
Returns
the parsed double.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_strtol
SDL_strtoul
SDL_strtoll
SDL_strtoull
SDL_strtod
{
#ifdef HAVE_ATOF
    return atof(string);
#else
    return SDL_strtod(string, NULL);
#endif // HAVE_ATOF
}
References NULL, and SDL_strtod().
Referenced by DUMMYAUDIO_OpenDevice(), MainCallbackRateHintChanged(), SDL_Blit_Slow_Float(), SDL_GetFloatProperty(), SDL_MouseNormalSpeedScaleChanged(), and SDL_MouseRelativeSpeedScaleChanged().
SDL_atoi()
int SDL_atoi (const char * str)
Parse an int from a string.
The result of calling SDL_atoi(str) is equivalent to (int)SDL_strtol(str, NULL, 10).
Parameters
str The null-terminated string to read. Must not be NULL.
Returns
the parsed int.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atof
SDL_strtol
SDL_strtoul
SDL_strtoll
SDL_strtoull
SDL_strtod
SDL_itoa
{
#ifdef HAVE_ATOI
    return atoi(string);
#else
    return SDL_strtol(string, NULL, 10);
#endif // HAVE_ATOI
}
References NULL, and SDL_strtol().
Referenced by load_default_icon(), ParseLogCategory(), ParseLogPriority(), PrepareAudioFormat(), SDL_EventLoggingChanged(), SDL_GetDefaultSampleFramesFromFreq(), SDL_GetDefaultSystemCursor(), SDL_GetRenderLineMethod(), SDL_GetStringInteger(), SDL_MouseDoubleClickRadiusChanged(), SDL_MouseDoubleClickTimeChanged(), SDL_MouseIntegerModeChanged(), SDL_PrivateAddGamepadMapping(), SDL_PrivateParseGamepadElement(), SDL_SetHapticGain(), SDL_StopEventLoop(), and SDL_TimerResolutionChanged().
SDL_CaseFoldUnicode()
int SDL_CaseFoldUnicode (Uint32 from, Uint32 * to)
{
    // !!! FIXME: since the hashtable is static, maybe we should binary
    // !!! FIXME: search it instead of walking the whole bucket.
    if (from < 128) {   // low-ASCII, easy!
        if ((from >= 'A') && (from <= 'Z')) {
            *to = 'a' + (from - 'A');
            return 1;
        }
    } else if (from <= 0xFFFF) {  // the Basic Multilingual Plane.
        const Uint8 hash = ((from ^ (from >> 8)) & 0xFF);
        const Uint16 from16 = (Uint16) from;
        // see if it maps to a single char (most common)...
        {
            const CaseFoldHashBucket1_16 *bucket = &case_fold_hash1_16[hash];
            const int count = (int) bucket->count;
            for (int i = 0; i < count; i++) {
                const CaseFoldMapping1_16 *mapping = &bucket->list[i];
                if (mapping->from == from16) {
                    *to = mapping->to0;
                    return 1;
                }
            }
        }
        // see if it folds down to two chars...
        {
            const CaseFoldHashBucket2_16 *bucket = &case_fold_hash2_16[hash & 15];
            const int count = (int) bucket->count;
            for (int i = 0; i < count; i++) {
                const CaseFoldMapping2_16 *mapping = &bucket->list[i];
                if (mapping->from == from16) {
                    to[0] = mapping->to0;
                    to[1] = mapping->to1;
                    return 2;
                }
            }
        }
        // okay, maybe it's _three_ characters!
        {
            const CaseFoldHashBucket3_16 *bucket = &case_fold_hash3_16[hash & 3];
            const int count = (int) bucket->count;
            for (int i = 0; i < count; i++) {
                const CaseFoldMapping3_16 *mapping = &bucket->list[i];
                if (mapping->from == from16) {
                    to[0] = mapping->to0;
                    to[1] = mapping->to1;
                    to[2] = mapping->to2;
                    return 3;
                }
            }
        }
    } else {  // codepoint that doesn't fit in 16 bits.
        const Uint8 hash = ((from ^ (from >> 8)) & 0xFF);
        const CaseFoldHashBucket1_32 *bucket = &case_fold_hash1_32[hash & 15];
        const int count = (int) bucket->count;
        for (int i = 0; i < count; i++) {
            const CaseFoldMapping1_32 *mapping = &bucket->list[i];
            if (mapping->from == from) {
                *to = mapping->to0;
                return 1;
            }
        }
    }
    // Not found...there's no folding needed for this codepoint.
    *to = from;
    return 1;
}
References case_fold_hash1_16, case_fold_hash1_32, case_fold_hash2_16, case_fold_hash3_16, CaseFoldHashBucket1_16::count, CaseFoldHashBucket1_32::count, CaseFoldHashBucket2_16::count, CaseFoldHashBucket3_16::count, count, CaseFoldMapping1_16::from, CaseFoldMapping1_32::from, CaseFoldMapping2_16::from, CaseFoldMapping3_16::from, CaseFoldHashBucket1_16::list, CaseFoldHashBucket1_32::list, CaseFoldHashBucket2_16::list, CaseFoldHashBucket3_16::list, CaseFoldMapping1_16::to0, CaseFoldMapping1_32::to0, CaseFoldMapping2_16::to0, CaseFoldMapping3_16::to0, CaseFoldMapping2_16::to1, CaseFoldMapping3_16::to1, and CaseFoldMapping3_16::to2.
Referenced by CaseFoldUtf8String().
SDL_COMPILE_TIME_ASSERT() [1/2]
SDL_COMPILE_TIME_ASSERT (sizeof_wchar_t , sizeof(wchar_t) = =4)
References SDL_SIZEOF_WCHAR_T.
SDL_COMPILE_TIME_ASSERT() [2/2]
SDL_COMPILE_TIME_ASSERT (wchar_t_int , sizeof(wchar_t)<=sizeof(int))
SDL_IntPrecisionAdjust()
void SDL_IntPrecisionAdjust (char * num, size_t maxlen, SDL_FormatInfo * info) static
{ // left-pad num with zeroes.
    size_t sz, pad, have_sign;
    if (!info) {
        return;
    }
    have_sign = 0;
    if (*num == '-' || *num == '+') {
        have_sign = 1;
        ++num;
        --maxlen;
    }
    sz = SDL_strlen(num);
    if (info->precision > 0 && sz < (size_t)info->precision) {
        pad = (size_t)info->precision - sz;
        if (pad + sz + 1 <= maxlen) { // otherwise ignore the precision
            SDL_memmove(num + pad, num, sz + 1);
            SDL_memset(num, '0', pad);
        }
    }
    info->precision = -1; // so that SDL_PrintString() doesn't make a mess.
    if (info->pad_zeroes && info->width > 0 && (size_t)info->width > sz + have_sign) {
        /* handle here: spaces are added before the sign
           but zeroes must be placed _after_ the sign. */
        // sz hasn't changed: we ignore pad_zeroes if a precision is given.
        pad = (size_t)info->width - sz - have_sign;
        if (pad + sz + 1 <= maxlen) {
            SDL_memmove(num + pad, num, sz + 1);
            SDL_memset(num, '0', pad);
        }
        info->width = 0; // so that SDL_PrintString() doesn't make a mess.
    }
}
References SDL_FormatInfo::pad_zeroes, SDL_FormatInfo::precision, SDL_memmove, SDL_memset, SDL_strlen(), and SDL_FormatInfo::width.
Referenced by SDL_PrintLong(), SDL_PrintLongLong(), SDL_PrintUnsignedLong(), and SDL_PrintUnsignedLongLong().
SDL_itoa()
char * SDL_itoa (int value, char * str, int radix)
Convert an integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget possible negative signs, null terminator bytes, etc).
Parameters
value the integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_uitoa
SDL_ltoa
SDL_lltoa
{
#ifdef HAVE_ITOA
    return itoa(value, string, radix);
#else
    return SDL_ltoa((long)value, string, radix);
#endif // HAVE_ITOA
}
References SDL_ltoa().
Referenced by SDL_AddVideoDisplay().
SDL_lltoa()
char * SDL_lltoa (long long value, char * str, int radix)
Convert a long long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget possible negative signs, null terminator bytes, etc).
Parameters
value the long long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ulltoa
SDL_itoa
SDL_ltoa
{
#ifdef HAVE__I64TOA
    return _i64toa(value, string, radix);
#else
    char *bufp = string;
    if (value < 0) {
        *bufp++ = '-';
        SDL_ulltoa(-value, bufp, radix);
    } else {
        SDL_ulltoa(value, bufp, radix);
    }
    return string;
#endif // HAVE__I64TOA
}
References SDL_ulltoa().
Referenced by SDL_PrintLongLong().
SDL_ltoa()
char * SDL_ltoa (long value, char * str, int radix)
Convert a long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget possible negative signs, null terminator bytes, etc).
Parameters
value the long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ultoa
SDL_itoa
SDL_lltoa
{
#ifdef HAVE__LTOA
    return _ltoa(value, string, radix);
#else
    char *bufp = string;
    if (value < 0) {
        *bufp++ = '-';
        SDL_ultoa(-value, bufp, radix);
    } else {
        SDL_ultoa(value, bufp, radix);
    }
    return string;
#endif // HAVE__LTOA
}
References SDL_ultoa().
Referenced by SDL_itoa(), and SDL_PrintLong().
SDL_memcmp()
int SDL_memcmp (const void * s1, const void * s2, size_t len)
Compare two buffers of memory.
Parameters
s1 the first buffer to compare. NULL is not permitted!
s2 the second buffer to compare. NULL is not permitted!
len the number of bytes to compare between the buffers.
Returns
less than zero if s1 is "less than" s2, greater than zero if s1 is "greater than" s2, and zero if the buffers match exactly for len bytes.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_PLATFORM_VITA
    /*
      Using memcmp on NULL is UB per POSIX / C99 7.21.1/2.
      But, both linux and bsd allow that, with an exception:
      zero length strings are always identical, so NULLs are never dereferenced.
      sceClibMemcmp on PSVita doesn't allow that, so we check ourselves.
    */
    if (len == 0) {
        return 0;
    }
    return sceClibMemcmp(s1, s2, len);
#elif defined(HAVE_MEMCMP)
    return memcmp(s1, s2, len);
#else
    char *s1p = (char *)s1;
    char *s2p = (char *)s2;
    while (len--) {
        if (*s1p != *s2p) {
            return *s1p - *s2p;
        }
        ++s1p;
        ++s2p;
    }
    return 0;
#endif // HAVE_MEMCMP
}
References memcmp.
Referenced by decode_header(), Map1to1(), QueueCmdSetClipRect(), QueueCmdSetViewport(), SDL_AddCamera(), SDL_AudioChannelMapsEqual(), SDL_AudioSpecsEqual(), SDL_CheckWindowSafeAreaChanged(), SDL_ConvertSurfaceAndColorspace(), SDL_endswith(), SDL_GetFullscreenModeMatch(), SDL_GetGamepadMappings(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateMatchGamepadMappingForGUID(), SDL_PrivateParseGamepadElement(), SDL_SetGamepadMapping(), SDL_URIToLocal(), SetAudioStreamChannelMap(), and WaveGetFormatGUIDEncoding().
SDL_PrintFloat()
size_t SDL_PrintFloat (char * text, size_t maxlen, SDL_FormatInfo * info, double arg, bool g) static
{
    char num[327];
    size_t length = 0;
    size_t integer_length;
    int precision = info->precision;
    // This isn't especially accurate, but hey, it's easy. :)
    unsigned long long value;
    if (arg < 0.0 || (arg == 0.0 && 1.0 / arg < 0.0)) { // additional check for signed zero
        num[length++] = '-';
        arg = -arg;
    } else if (info->force_sign) {
        num[length++] = '+';
    }
    value = (unsigned long long)arg;
    integer_length = SDL_PrintUnsignedLongLong(&num[length], sizeof(num) - length, NULL, value);
    length += integer_length;
    arg -= value;
    if (precision < 0) {
        precision = 6;
    }
    if (g) {
        // The precision includes the integer portion
        precision -= SDL_min((int)integer_length, precision);
    }
    if (info->force_type || precision > 0) {
        const char decimal_separator = '.';
        double integer_value;
        SDL_assert(length < sizeof(num));
        num[length++] = decimal_separator;
        while (precision > 1) {
            arg *= 10.0;
            arg = SDL_modf(arg, &integer_value);
            SDL_assert(length < sizeof(num));
            num[length++] = '0' + (char)integer_value;
            --precision;
        }
        if (precision == 1) {
            arg *= 10.0;
            integer_value = SDL_round(arg);
            if (integer_value == 10.0) {
                // Carry the one...
                size_t i;
                for (i = length; i--; ) {
                    if (num[i] == decimal_separator) {
                        continue;
                    }
                    if (num[i] == '9') {
                        num[i] = '0';
                        if (i == 0 || num[i - 1] == '-' || num[i - 1] == '+') {
                            SDL_memmove(&num[i+1], &num[i], length - i);
                            num[i] = '1';
                            ++length;
                            break;
                        }
                    } else {
                        ++num[i];
                        break;
                    }
                }
                SDL_assert(length < sizeof(num));
                num[length++] = '0';
            } else {
                SDL_assert(length < sizeof(num));
                num[length++] = '0' + (char)integer_value;
            }
        }
        if (g) {
            // Trim trailing zeroes and decimal separator
            size_t i;
            for (i = length - 1; num[i] != decimal_separator; --i) {
                if (num[i] == '0') {
                    --length;
                } else {
                    break;
                }
            }
            if (num[i] == decimal_separator) {
                --length;
            }
        }
    }
    num[length] = '\0';
    info->precision = -1;
    length = SDL_PrintString(text, maxlen, info, num);
    if (info->width > 0 && (size_t)info->width > length) {
        const char fill = info->pad_zeroes ? '0' : ' ';
        size_t width = info->width - length;
        size_t filllen, movelen;
        filllen = SDL_min(width, maxlen);
        movelen = SDL_min(length, (maxlen - filllen));
        SDL_memmove(&text[filllen], text, movelen);
        SDL_memset(text, fill, filllen);
        length += width;
    }
    return length;
}
References SDL_FormatInfo::force_sign, SDL_FormatInfo::force_type, NULL, SDL_FormatInfo::pad_zeroes, SDL_FormatInfo::precision, SDL_assert, SDL_memmove, SDL_memset, SDL_min, SDL_modf(), SDL_PrintString(), SDL_PrintUnsignedLongLong(), SDL_round(), and SDL_FormatInfo::width.
Referenced by SDL_vsnprintf().
SDL_PrintLong()
size_t SDL_PrintLong (char * text, size_t maxlen, SDL_FormatInfo * info, long value) static
{
    char num[130], *p = num;
    if (info->force_sign && value >= 0L) {
        *p++ = '+';
    }
    SDL_ltoa(value, p, info ? info->radix : 10);
    SDL_IntPrecisionAdjust(num, sizeof(num), info);
    return SDL_PrintString(text, maxlen, info, num);
}
References SDL_FormatInfo::force_sign, SDL_FormatInfo::radix, SDL_IntPrecisionAdjust(), SDL_ltoa(), and SDL_PrintString().
Referenced by SDL_vsnprintf().
SDL_PrintLongLong()
size_t SDL_PrintLongLong (char * text, size_t maxlen, SDL_FormatInfo * info, long long value) static
{
    char num[130], *p = num;
    if (info->force_sign && value >= (Sint64)0) {
        *p++ = '+';
    }
    SDL_lltoa(value, p, info ? info->radix : 10);
    SDL_IntPrecisionAdjust(num, sizeof(num), info);
    return SDL_PrintString(text, maxlen, info, num);
}
References SDL_FormatInfo::force_sign, SDL_FormatInfo::radix, SDL_IntPrecisionAdjust(), SDL_lltoa(), and SDL_PrintString().
Referenced by SDL_vsnprintf().
SDL_PrintPointer()
size_t SDL_PrintPointer (char * text, size_t maxlen, SDL_FormatInfo * info, const void * value) static
{
    char num[130];
    size_t length;
    if (!value) {
        return SDL_PrintString(text, maxlen, info, NULL);
    }
    SDL_ulltoa((unsigned long long)(uintptr_t)value, num, 16);
    length = SDL_PrintString(text, maxlen, info, "0x");
    return length + SDL_PrintString(TEXT_AND_LEN_ARGS, info, num);
}
References NULL, SDL_PrintString(), SDL_ulltoa(), and TEXT_AND_LEN_ARGS.
Referenced by SDL_vsnprintf().
SDL_PrintString()
size_t SDL_PrintString (char * text, size_t maxlen, SDL_FormatInfo * info, const char * string) static
{
    const char fill = (info && info->pad_zeroes) ? '0' : ' ';
    size_t width = 0;
    size_t filllen = 0;
    size_t length = 0;
    size_t slen, sz;
    if (!string) {
        string = "(null)";
    }
    sz = SDL_strlen(string);
    if (info && info->width > 0 && (size_t)info->width > sz) {
        width = info->width - sz;
        if (info->precision >= 0 && (size_t)info->precision < sz) {
            width += sz - (size_t)info->precision;
        }
        filllen = SDL_min(width, maxlen);
        if (!info->left_justify) {
            SDL_memset(text, fill, filllen);
            text += filllen;
            maxlen -= filllen;
            length += width;
            filllen = 0;
        }
    }
    SDL_strlcpy(text, string, maxlen);
    length += sz;
    if (filllen > 0) {
        SDL_memset(text + sz, fill, filllen);
        length += width;
    }
    if (info) {
        if (info->precision >= 0 && (size_t)info->precision < sz) {
            slen = (size_t)info->precision;
            if (slen < maxlen) {
                text[slen] = '\0';
            }
            length -= (sz - slen);
        }
        if (maxlen > 1) {
            if (info->force_case == SDL_CASE_LOWER) {
                SDL_strlwr(text);
            } else if (info->force_case == SDL_CASE_UPPER) {
                SDL_strupr(text);
            }
        }
    }
    return length;
}
References SDL_FormatInfo::force_case, SDL_FormatInfo::left_justify, SDL_FormatInfo::pad_zeroes, SDL_FormatInfo::precision, SDL_CASE_LOWER, SDL_CASE_UPPER, SDL_memset, SDL_min, SDL_strlcpy(), SDL_strlen(), SDL_strlwr(), SDL_strupr(), and SDL_FormatInfo::width.
Referenced by SDL_PrintFloat(), SDL_PrintLong(), SDL_PrintLongLong(), SDL_PrintPointer(), SDL_PrintStringW(), SDL_PrintUnsignedLong(), SDL_PrintUnsignedLongLong(), and SDL_vsnprintf().
SDL_PrintStringW()
size_t SDL_PrintStringW (char * text, size_t maxlen, SDL_FormatInfo * info, const wchar_t * wide_string) static
{
    size_t length = 0;
    if (wide_string) {
        char *string = SDL_iconv_string("UTF-8", "WCHAR_T", (char *)(wide_string), (SDL_wcslen(wide_string) + 1) * sizeof(*wide_string));
        length = SDL_PrintString(TEXT_AND_LEN_ARGS, info, string);
        SDL_free(string);
    } else {
        length = SDL_PrintString(TEXT_AND_LEN_ARGS, info, NULL);
    }
    return length;
}
References NULL, SDL_free(), SDL_iconv_string(), SDL_PrintString(), SDL_wcslen(), and TEXT_AND_LEN_ARGS.
Referenced by SDL_vsnprintf().
SDL_PrintUnsignedLong()
size_t SDL_PrintUnsignedLong (char * text, size_t maxlen, SDL_FormatInfo * info, unsigned long value) static
{
    char num[130];
    SDL_ultoa(value, num, info ? info->radix : 10);
    SDL_IntPrecisionAdjust(num, sizeof(num), info);
    return SDL_PrintString(text, maxlen, info, num);
}
References SDL_FormatInfo::radix, SDL_IntPrecisionAdjust(), SDL_PrintString(), and SDL_ultoa().
Referenced by SDL_vsnprintf().
SDL_PrintUnsignedLongLong()
size_t SDL_PrintUnsignedLongLong (char * text, size_t maxlen, SDL_FormatInfo * info, unsigned long long value) static
{
    char num[130];
    SDL_ulltoa(value, num, info ? info->radix : 10);
    SDL_IntPrecisionAdjust(num, sizeof(num), info);
    return SDL_PrintString(text, maxlen, info, num);
}
References SDL_FormatInfo::radix, SDL_IntPrecisionAdjust(), SDL_PrintString(), and SDL_ulltoa().
Referenced by SDL_PrintFloat(), and SDL_vsnprintf().
SDL_ScanFloat()
size_t SDL_ScanFloat (const char * text, double * valuep) static
{
    const char *text_start = text;
    const char *number_start = text_start;
    double value = 0.0;
    bool negative = false;
    while (SDL_isspace(*text)) {
        ++text;
    }
    if (*text == '-' || *text == '+') {
        negative = *text == '-';
        ++text;
    }
    number_start = text;
    if (SDL_isdigit(*text)) {
        value += SDL_strtoull(text, (char **)(&text), 10);
        if (*text == '.') {
            double denom = 10;
            ++text;
            while (SDL_isdigit(*text)) {
                value += (double)(*text - '0') / denom;
                denom *= 10;
                ++text;
            }
        }
    }
    if (text == number_start) {
        // no number was parsed, and thus no characters were consumed
        text = text_start;
    } else if (negative) {
        value = -value;
    }
    *valuep = value;
    return text - text_start;
}
References SDL_isdigit(), SDL_isspace(), and SDL_strtoull().
Referenced by SDL_strtod(), and SDL_vsscanf().
SDL_ScanLong()
size_t SDL_ScanLong (const char * text, int count, int radix, long * valuep) static
{
    const unsigned long long_max = (~0UL) >> 1;
    unsigned long long value;
    bool negative;
    size_t len = SDL_ScanUnsignedLongLongInternal(text, count, radix, &value, &negative);
    if (negative) {
        const unsigned long abs_long_min = long_max + 1;
        if (value == 0 || value > abs_long_min) {
            value = 0ULL - abs_long_min;
        } else {
            value = 0ULL - value;
        }
    } else if (value > long_max) {
        value = long_max;
    }
    *valuep = (long)value;
    return len;
}
References count, and SDL_ScanUnsignedLongLongInternal().
Referenced by SDL_strtol(), and SDL_vsscanf().
SDL_ScanLongLong()
size_t SDL_ScanLongLong (const char * text, int count, int radix, long long * valuep) static
{
    const unsigned long long llong_max = (~0ULL) >> 1;
    unsigned long long value;
    bool negative;
    size_t len = SDL_ScanUnsignedLongLongInternal(text, count, radix, &value, &negative);
    if (negative) {
        const unsigned long long abs_llong_min = llong_max + 1;
        if (value == 0 || value > abs_llong_min) {
            value = 0ULL - abs_llong_min;
        } else {
            value = 0ULL - value;
        }
    } else if (value > llong_max) {
        value = llong_max;
    }
    *valuep = value;
    return len;
}
References count, and SDL_ScanUnsignedLongLongInternal().
Referenced by SDL_strtoll(), and SDL_vsscanf().
SDL_ScanLongW()
size_t SDL_ScanLongW (const wchar_t * text, int count, int radix, long * valuep) static
{
    const unsigned long long_max = (~0UL) >> 1;
    unsigned long long value;
    bool negative;
    size_t len = SDL_ScanUnsignedLongLongInternalW(text, count, radix, &value, &negative);
    if (negative) {
        const unsigned long abs_long_min = long_max + 1;
        if (value == 0 || value > abs_long_min) {
            value = 0ULL - abs_long_min;
        } else {
            value = 0ULL - value;
        }
    } else if (value > long_max) {
        value = long_max;
    }
    *valuep = (long)value;
    return len;
}
References count, and SDL_ScanUnsignedLongLongInternalW().
Referenced by SDL_wcstol().
SDL_ScanUintPtrT()
size_t SDL_ScanUintPtrT (const char * text, uintptr_t * valuep) static
{
    const uintptr_t uintptr_max = ~(uintptr_t)0;
    unsigned long long value;
    bool negative;
    size_t len = SDL_ScanUnsignedLongLongInternal(text, 0, 16, &value, &negative);
    if (negative) {
        if (value == 0 || value > uintptr_max) {
            value = uintptr_max;
        } else if (value == uintptr_max) {
            value = 1;
        } else {
            value = 0ULL - value;
        }
    } else if (value > uintptr_max) {
        value = uintptr_max;
    }
    *valuep = (uintptr_t)value;
    return len;
}
References SDL_ScanUnsignedLongLongInternal().
Referenced by SDL_vsscanf().
SDL_ScanUnsignedLong()
size_t SDL_ScanUnsignedLong (const char * text, int count, int radix, unsigned long * valuep) static
{
    const unsigned long ulong_max = ~0UL;
    unsigned long long value;
    bool negative;
    size_t len = SDL_ScanUnsignedLongLongInternal(text, count, radix, &value, &negative);
    if (negative) {
        if (value == 0 || value > ulong_max) {
            value = ulong_max;
        } else if (value == ulong_max) {
            value = 1;
        } else {
            value = 0ULL - value;
        }
    } else if (value > ulong_max) {
        value = ulong_max;
    }
    *valuep = (unsigned long)value;
    return len;
}
References count, and SDL_ScanUnsignedLongLongInternal().
Referenced by SDL_strtoul(), and SDL_vsscanf().
SDL_ScanUnsignedLongLong()
size_t SDL_ScanUnsignedLongLong (const char * text, int count, int radix, unsigned long long * valuep) static
{
    const unsigned long long ullong_max = ~0ULL;
    bool negative;
    size_t len = SDL_ScanUnsignedLongLongInternal(text, count, radix, valuep, &negative);
    if (negative) {
        if (*valuep == 0) {
            *valuep = ullong_max;
        } else {
            *valuep = 0ULL - *valuep;
        }
    }
    return len;
}
References count, and SDL_ScanUnsignedLongLongInternal().
Referenced by SDL_strtoull(), and SDL_vsscanf().
SDL_ScanUnsignedLongLongInternal()
size_t SDL_ScanUnsignedLongLongInternal (const char * text, int count, int radix, unsigned long long * valuep, bool * negativep) static
Parses an unsigned long long and returns the unsigned value and sign bit.
Positive values are clamped to ULLONG_MAX. The result value == 0 && negative indicates negative overflow and might need to be handled differently depending on whether a signed or unsigned integer is being parsed.
{
    const unsigned long long ullong_max = ~0ULL;
    const char *text_start = text;
    const char *number_start = text_start;
    unsigned long long value = 0;
    bool negative = false;
    bool overflow = false;
    if (radix == 0 || (radix >= 2 && radix <= 36)) {
        while (SDL_isspace(*text)) {
            ++text;
        }
        if (*text == '-' || *text == '+') {
            negative = *text == '-';
            ++text;
        }
        if ((radix == 0 || radix == 16) && *text == '0' && (text[1] == 'x' || text[1] == 'X')) {
            text += 2;
            radix = 16;
        } else if (radix == 0 && *text == '0' && (text[1] >= '0' && text[1] <= '9')) {
            ++text;
            radix = 8;
        } else if (radix == 0) {
            radix = 10;
        }
        number_start = text;
        do {
            unsigned long long digit;
            if (*text >= '0' && *text <= '9') {
                digit = *text - '0';
            } else if (radix > 10) {
                if (*text >= 'A' && *text < 'A' + (radix - 10)) {
                    digit = 10 + (*text - 'A');
                } else if (*text >= 'a' && *text < 'a' + (radix - 10)) {
                    digit = 10 + (*text - 'a');
                } else {
                    break;
                }
            } else {
                break;
            }
            if (value != 0 && radix > ullong_max / value) {
                overflow = true;
            } else {
                value *= radix;
                if (digit > ullong_max - value) {
                    overflow = true;
                } else {
                    value += digit;
                }
            }
            ++text;
        } while (count == 0 || (text - text_start) != count);
    }
    if (text == number_start) {
        if (radix == 16 && text > text_start && (*(text - 1) == 'x' || *(text - 1) == 'X')) {
            // the string was "0x"; consume the '0' but not the 'x'
            --text;
        } else {
            // no number was parsed, and thus no characters were consumed
            text = text_start;
        }
    }
    if (overflow) {
        if (negative) {
            value = 0;
        } else {
            value = ullong_max;
        }
    } else if (value == 0) {
        negative = false;
    }
    *valuep = value;
    *negativep = negative;
    return text - text_start;
}
References count, and SDL_isspace().
Referenced by SDL_ScanLong(), SDL_ScanLongLong(), SDL_ScanUintPtrT(), SDL_ScanUnsignedLong(), and SDL_ScanUnsignedLongLong().
SDL_ScanUnsignedLongLongInternalW()
size_t SDL_ScanUnsignedLongLongInternalW (const wchar_t * text, int count, int radix, unsigned long long * valuep, bool * negativep) static
Parses an unsigned long long and returns the unsigned value and sign bit.
Positive values are clamped to ULLONG_MAX. The result value == 0 && negative indicates negative overflow and might need to be handled differently depending on whether a signed or unsigned integer is being parsed.
{
    const unsigned long long ullong_max = ~0ULL;
    const wchar_t *text_start = text;
    const wchar_t *number_start = text_start;
    unsigned long long value = 0;
    bool negative = false;
    bool overflow = false;
    if (radix == 0 || (radix >= 2 && radix <= 36)) {
        while (SDL_isspace(*text)) {
            ++text;
        }
        if (*text == '-' || *text == '+') {
            negative = *text == '-';
            ++text;
        }
        if ((radix == 0 || radix == 16) && *text == '0' && (text[1] == 'x' || text[1] == 'X')) {
            text += 2;
            radix = 16;
        } else if (radix == 0 && *text == '0' && (text[1] >= '0' && text[1] <= '9')) {
            ++text;
            radix = 8;
        } else if (radix == 0) {
            radix = 10;
        }
        number_start = text;
        do {
            unsigned long long digit;
            if (*text >= '0' && *text <= '9') {
                digit = *text - '0';
            } else if (radix > 10) {
                if (*text >= 'A' && *text < 'A' + (radix - 10)) {
                    digit = 10 + (*text - 'A');
                } else if (*text >= 'a' && *text < 'a' + (radix - 10)) {
                    digit = 10 + (*text - 'a');
                } else {
                    break;
                }
            } else {
                break;
            }
            if (value != 0 && radix > ullong_max / value) {
                overflow = true;
            } else {
                value *= radix;
                if (digit > ullong_max - value) {
                    overflow = true;
                } else {
                    value += digit;
                }
            }
            ++text;
        } while (count == 0 || (text - text_start) != count);
    }
    if (text == number_start) {
        if (radix == 16 && text > text_start && (*(text - 1) == 'x' || *(text - 1) == 'X')) {
            // the string was "0x"; consume the '0' but not the 'x'
            --text;
        } else {
            // no number was parsed, and thus no characters were consumed
            text = text_start;
        }
    }
    if (overflow) {
        if (negative) {
            value = 0;
        } else {
            value = ullong_max;
        }
    } else if (value == 0) {
        negative = false;
    }
    *valuep = value;
    *negativep = negative;
    return text - text_start;
}
References count, and SDL_isspace().
Referenced by SDL_ScanLongW().
SDL_snprintf()
int SDL_snprintf (SDL_OUT_Z_CAP(maxlen) char * text, size_t maxlen, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
{
    va_list ap;
    int result;
    va_start(ap, fmt);
    result = SDL_vsnprintf(text, maxlen, fmt, ap);
    va_end(ap);
    return result;
}
References SDL_PRINTF_FORMAT_STRING, and SDL_vsnprintf().
SDL_sscanf()
int SDL_sscanf (const char * text, SDL_SCANF_FORMAT_STRING const char * fmt, ...)
{
    int rc;
    va_list ap;
    va_start(ap, fmt);
    rc = SDL_vsscanf(text, fmt, ap);
    va_end(ap);
    return rc;
}
References SDL_SCANF_FORMAT_STRING, and SDL_vsscanf().
SDL_StepBackUTF8()
Uint32 SDL_StepBackUTF8 (const char * start, const char ** pstr)
Decode a UTF-8 string in reverse, one Unicode codepoint at a time.
This will go to the start of the previous Unicode codepoint in the string, move *pstr to that location and return that codepoint.
If *pstr is already at the start of the string), it will not advance *pstr at all.
Generally this function is called in a loop until it returns zero, adjusting its parameter each iteration.
If an invalid UTF-8 sequence is encountered, this function returns SDL_INVALID_UNICODE_CODEPOINT.
Several things can generate invalid UTF-8 sequences, including overlong encodings, the use of UTF-16 surrogate values, and truncated data. Please refer to RFC3629 for details.
Parameters
start a pointer to the beginning of the UTF-8 string.
pstr a pointer to a UTF-8 string pointer to be read and adjusted.
Returns
the previous Unicode codepoint in the string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!pstr || *pstr <= start) {
        return 0;
    }
    // Step back over the previous UTF-8 character
    const char *str = *pstr;
    do {
        if (str == start) {
            break;
        }
        --str;
    } while ((*str & 0xC0) == 0x80);
    size_t length = (*pstr - str);
    *pstr = str;
    return StepUTF8(&str, length);
}
References StepUTF8().
SDL_StepUTF8()
Uint32 SDL_StepUTF8 (const char ** pstr, size_t * pslen)
Decode a UTF-8 string, one Unicode codepoint at a time.
This will return the first Unicode codepoint in the UTF-8 encoded string in *pstr, and then advance *pstr past any consumed bytes before returning.
It will not access more than *pslen bytes from the string. *pslen will be adjusted, as well, subtracting the number of bytes consumed.
pslen is allowed to be NULL, in which case the string must be NULL-terminated, as the function will blindly read until it sees the NULL char.
if *pslen is zero, it assumes the end of string is reached and returns a zero codepoint regardless of the contents of the string buffer.
If the resulting codepoint is zero (a NULL terminator), or *pslen is zero, it will not advance *pstr or *pslen at all.
Generally this function is called in a loop until it returns zero, adjusting its parameters each iteration.
If an invalid UTF-8 sequence is encountered, this function returns SDL_INVALID_UNICODE_CODEPOINT and advances the string/length by one byte (which is to say, a multibyte sequence might produce several SDL_INVALID_UNICODE_CODEPOINT returns before it syncs to the next valid UTF-8 sequence).
Several things can generate invalid UTF-8 sequences, including overlong encodings, the use of UTF-16 surrogate values, and truncated data. Please refer to RFC3629 for details.
Parameters
pstr a pointer to a UTF-8 string pointer to be read and adjusted.
pslen a pointer to the number of bytes in the string, to be read and adjusted. NULL is allowed.
Returns
the first Unicode codepoint in the string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!pslen) {
        return StepUTF8(pstr, 4);  // 4 == max codepoint size.
    }
    const char *origstr = *pstr;
    const Uint32 result = StepUTF8(pstr, *pslen);
    *pslen -= (size_t) (*pstr - origstr);
    return result;
}
References StepUTF8().
Referenced by CaseFoldUtf8String(), SDL_RenderDebugText(), SDL_strcasestr(), SDL_utf8strlen(), and SDL_utf8strnlen().
SDL_strcasecmp()
int SDL_strcasecmp (const char * str1, const char * str2)
Compare two null-terminated UTF-8 strings, case-insensitively.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Since this handles Unicode, it expects the string to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    UNICODE_STRCASECMP(8, 4, 4, (void) str1start, (void) str2start);  // always NULL-terminated, no need to adjust lengths.
}
References UNICODE_STRCASECMP.
Referenced by AutoShowingScreenKeyboard(), SDL_Blit_Slow_Float(), SDL_CameraInit(), SDL_CreateWindowTexture(), SDL_GetGamepadAxisFromString(), SDL_GetGamepadTypeFromString(), SDL_GetKeyFromName(), SDL_GetScancodeFromName(), SDL_GetStringBoolean(), SDL_GetStringInteger(), SDL_GPUSelectBackend(), SDL_iconv_open(), SDL_InitAudio(), SDL_PrivateAddGamepadMapping(), SDL_PrivateGetGamepadButtonFromString(), SDL_ShouldMinimizeOnFocusLoss(), and ShouldAttemptTextureFramebuffer().
SDL_strcasestr()
char * SDL_strcasestr (const char * haystack, const char * needle)
Search a UTF-8 string for the first instance of a specific substring, case-insensitively.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Since this handles Unicode, it expects the strings to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Parameters
haystack the string to search. Must not be NULL.
needle the string to search for. Must not be NULL.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    const size_t length = SDL_strlen(needle);
    do {
        if (SDL_strncasecmp(haystack, needle, length) == 0) {
            return (char *)haystack;
        }
    } while (SDL_StepUTF8(&haystack, NULL));  // move ahead by a full codepoint at a time, regardless of bytes.
    return NULL;
}
References NULL, SDL_StepUTF8(), SDL_strlen(), and SDL_strncasecmp().
Referenced by SDL_HIDAPI_ShouldIgnoreDevice().
SDL_strchr()
char * SDL_strchr (const char * str, int c)
Search a string for the first instance of a specific byte.
The search ends once it finds the requested byte value, or a null terminator byte to end the string.
Note that this looks for bytes, not characters, so you cannot match against a Unicode codepoint > 255, regardless of character encoding.
Parameters
str the string to search. Must not be NULL.
c the byte value to search for.
Returns
a pointer to the first instance of c in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRCHR
    return SDL_const_cast(char *, strchr(string, c));
#elif defined(HAVE_INDEX)
    return SDL_const_cast(char *, index(string, c));
#else
    while (*string) {
        if (*string == c) {
            return (char *)string;
        }
        ++string;
    }
    if (c == '\0') {
        return (char *)string;
    }
    return NULL;
#endif // HAVE_STRCHR
}
References NULL, and SDL_const_cast.
Referenced by getlocale(), IsReadMode(), normalize_locale_str(), normalize_locales(), ParseLogPriorities(), SDL_AddGamepadMappingsFromIO(), SDL_CameraInit(), SDL_CPUFeatureMaskFromHint(), SDL_CreateEnvironment(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_GetGamepadTypeForID(), SDL_GL_ExtensionSupported(), SDL_InitAudio(), SDL_LoadGamepadHints(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_PrivateGetGamepadNameFromMappingString(), SDL_setenv_unsafe(), SDL_SetEnvironmentVariable(), SDL_ShowMessageBox(), SDL_unsetenv_unsafe(), SDL_UnsetEnvironmentVariable(), SDL_UpdateGamepadFaceStyle(), SDL_UpdateGamepadType(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_URIToLocal(), SDL_VideoInit(), and ValidateStoragePath().
SDL_strcmp()
int SDL_strcmp (const char * str1, const char * str2)
Compare two null-terminated UTF-8 strings.
Due to the nature of UTF-8 encoding, this will work with Unicode strings, since effectively this function just compares bytes until it hits a null-terminating character. Also due to the nature of UTF-8, this can be used with SDL_qsort() to put strings in (roughly) alphabetical order.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRCMP
    return strcmp(str1, str2);
#else
    int result;
    while (1) {
        result = ((unsigned char)*str1 - (unsigned char)*str2);
        if (result != 0 || (*str1 == '\0' /* && *str2 == '\0'*/)) {
            break;
        }
        ++str1;
        ++str2;
    }
    return result;
#endif // HAVE_STRCMP
}
References strcmp.
Referenced by AsyncFileModeValid(), convert_ext_list(), DBus_MessageFilter(), detect_available_methods(), GetHintEnvironmentVariable(), getlocale(), HIDAPI_UpdateDiscovery(), InitIME(), IsROGAlly(), MainCallbackRateHintChanged(), PLATFORM_hid_open_path(), ResetHintsCallback(), SDL_CreateWindowTexture(), SDL_DefaultGraphicsBackends(), SDL_GetAppMetadataProperty(), SDL_GetCPUCacheLineSize(), SDL_GetGamepadFaceStyleFromString(), SDL_GetGamepadName(), SDL_GetGamepadNameForID(), SDL_GetGamepadTypeFromVIDPID(), SDL_GetNumAudioDrivers(), SDL_GetNumVideoDrivers(), SDL_GL_ExtensionSupported(), SDL_GL_LoadLibrary(), SDL_HasInternalClipboardData(), SDL_InitAudio(), SDL_KeyMatchString(), SDL_LoadBMP_IO(), SDL_PrivateAddGamepadMapping(), SDL_PromptAssertion(), SDL_RenderDebugTextFormat(), SDL_ResetHint(), SDL_SetDisplayModeForDisplay(), SDL_SetHintWithPriority(), SDL_SetWindowTitle(), SDL_ShouldIgnoreGamepad(), SDL_ShouldMinimizeOnFocusLoss(), SDL_SYS_SetThreadPriority(), SDL_UpdateFullscreenMode(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_ValidMetadataProperty(), SDL_Vulkan_LoadLibrary(), ShouldAttemptTextureFramebuffer(), validate_list(), ValidateStoragePath(), WaveGetFactChunkHint(), WaveGetRiffSizeHint(), and WaveGetTruncationHint().
SDL_strdup()
char * SDL_strdup (const char * str)
Allocate a copy of a string.
This allocates enough space for a null-terminated copy of str, using SDL_malloc, and then makes a copy of the string into this space.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
str the string to copy.
Returns
a pointer to the newly-allocated string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t len = SDL_strlen(string) + 1;
    char *newstr = (char *)SDL_malloc(len);
    if (newstr) {
        SDL_memcpy(newstr, string, len);
    }
    return newstr;
}
References SDL_malloc(), SDL_memcpy, and SDL_strlen().
Referenced by clear_filt_names(), convert_filter(), convert_filters(), CopyHIDDeviceInfo(), CopyOneProperty(), CreatePhysicalAudioDevice(), FcitxClientCreateIC(), GENERIC_EnumerateDirectory(), GENERIC_OpenFileStorage(), GENERIC_Title_Create(), GetAppName(), IgnoredDevicesChanged(), SDL_AddCamera(), SDL_AddKeyboard(), SDL_AddMouse(), SDL_AddPenDevice(), SDL_AddTouch(), SDL_AddVideoDisplay(), SDL_CameraInit(), SDL_CreateDeviceName(), SDL_CreateDirectory(), SDL_CreateEnvironment(), SDL_CreateJoystickName(), SDL_CreateTemporaryString(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateWindowTexture(), SDL_GetClipboardText(), SDL_GetPersistentString(), SDL_GetPrimarySelectionText(), SDL_InitAudio(), SDL_InitSteamVirtualGamepadInfo(), SDL_InternalGlobDirectory(), SDL_LoadGamepadHints(), SDL_OpenHaptic(), SDL_OpenJoystick(), SDL_OpenSensor(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_PrivateSetProperty(), SDL_SaveClipboardMimeTypes(), SDL_SetClipboardText(), SDL_SetHintWithPriority(), SDL_SetLogPriorityPrefix(), SDL_SetPrimarySelectionText(), SDL_SetStringProperty(), SDL_SetWindowTitle(), SDL_SYS_GetBasePath(), SDL_SYS_GetPrefPath(), SDL_SYS_GetUserFolder(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UpdateSteamVirtualGamepadInfo(), ShowFileDialog(), ShowFolderDialog(), windows_ShowFileDialog(), and zenity_clean_name().
SDL_strlcat()
size_t SDL_strlcat (SDL_INOUT_Z_CAP(maxlen) char * dst, const char * src, size_t maxlen)
{
#ifdef HAVE_STRLCAT
    return strlcat(dst, src, maxlen);
#else
    size_t dstlen = SDL_strlen(dst);
    size_t srclen = SDL_strlen(src);
    if (dstlen < maxlen) {
        SDL_strlcpy(dst + dstlen, src, maxlen - dstlen);
    }
    return dstlen + srclen;
#endif // HAVE_STRLCAT
}
References SDL_strlcpy(), and SDL_strlen().
SDL_strlcpy()
size_t SDL_strlcpy (SDL_OUT_Z_CAP(maxlen) char * dst, const char * src, size_t maxlen)
{
#ifdef HAVE_STRLCPY
    return strlcpy(dst, src, maxlen);
#else
    size_t srclen = SDL_strlen(src);
    if (maxlen > 0) {
        size_t len = SDL_min(srclen, maxlen - 1);
        SDL_memcpy(dst, src, len);
        dst[len] = '\0';
    }
    return srclen;
#endif // HAVE_STRLCPY
}
References SDL_memcpy, SDL_min, and SDL_strlen().
Referenced by SDL_PrintString(), and SDL_strlcat().
SDL_strlen()
size_t SDL_strlen (const char * str)
This works exactly like strlen() but doesn't require access to a C runtime.
Counts the bytes in str, excluding the null terminator.
If you need the length of a UTF-8 string, consider using SDL_utf8strlen().
Parameters
str The null-terminated string to read. Must not be NULL.
Returns
the length (in bytes, excluding the null terminator) of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strnlen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_STRLEN
    return strlen(string);
#else
    size_t len = 0;
    while (*string++) {
        ++len;
    }
    return len;
#endif // HAVE_STRLEN
}
Referenced by CaseFoldUtf8String(), convert_ext_list(), convert_filter(), convert_filters(), CopyEnvStrings(), CountEnvStrings(), CreateCandidatesForEvent(), CreateMappingString(), escape_label(), Fcitx_GetPreeditString(), GENERIC_EnumerateDirectory(), GENERIC_EnumerateStorageDirectory(), GENERIC_OpenFileStorage(), GENERIC_Title_Create(), GetControllerTypeOverride(), GlobDirectoryCallback(), HasPrefix(), HIDAPI_UpdateDiscovery(), IOS_GetAppleSFSymbolsNameForButton(), ParseLogPriorities(), SDL_ClipboardTextCallback(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_CopyClipboardMimeTypes(), SDL_CPUFeatureMaskFromHint(), SDL_CreateDeviceName(), SDL_CreateDirectory(), SDL_CreateJoystickGUID(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_endswith(), SDL_GetClipboardData(), SDL_getenv_unsafe(), SDL_GetGamepadMappings(), SDL_GetKeyFromName(), SDL_GL_ExtensionSupported(), SDL_HashString(), SDL_InternalGlobDirectory(), SDL_IntPrecisionAdjust(), SDL_LogOutput(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_PrintString(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_PrivateParseGamepadElement(), SDL_setenv_unsafe(), SDL_SetEnvironmentVariable(), SDL_ShowMessageBox(), SDL_startswith(), SDL_strcasestr(), SDL_strdup(), SDL_StringToGUID(), SDL_strlcat(), SDL_strlcpy(), SDL_strnstr(), SDL_strrchr(), SDL_strrev(), SDL_strstr(), SDL_SYS_GetPreferredLocales(), SDL_SYS_OpenURL(), SDL_unsetenv_unsafe(), SDL_URIDecode(), SDL_URIToLocal(), SDL_utf8strlcpy(), SDL_VideoInit(), validate_list(), win_get_filters(), and windows_ShowFileDialog().
SDL_strlwr()
char * SDL_strlwr (char * str)
Convert a string to lowercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'A' through 'Z' to lowercase.
This function operates on a null-terminated string of bytes–even if it is malformed UTF-8!–and converts ASCII characters 'A' through 'Z' to their lowercase equivalents in-place, returning the original str pointer.
Parameters
str the string to convert in-place. Can not be NULL.
Returns
the str pointer passed into this function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strupr
{
    char *bufp = string;
    while (*bufp) {
        *bufp = (char)SDL_tolower((unsigned char)*bufp);
        ++bufp;
    }
    return string;
}
References SDL_tolower().
Referenced by SDL_PrintString().
SDL_strncasecmp()
int SDL_strncasecmp (const char * str1, const char * str2, size_t maxlen)
Compare two UTF-8 strings, case-insensitively, up to a number of bytes.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Since this handles Unicode, it expects the string to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Note that while this function is intended to be used with UTF-8, maxlen specifies a byte limit! If the limit lands in the middle of a multi-byte UTF-8 sequence, it may convert a portion of the final character to one or more Unicode character U+FFFD (REPLACEMENT CHARACTER) so as not to overflow a buffer.
maxlen specifies a maximum number of bytes to compare; if the strings match to this number of bytes (or both have matched to a null-terminator character before this number of bytes), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of bytes to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t slen1 = maxlen;
    size_t slen2 = maxlen;
    UNICODE_STRCASECMP(8, slen1, slen2, slen1 -= (size_t) (str1 - ((const char *) str1start)), slen2 -= (size_t) (str2 - ((const char *) str2start)));
}
References UNICODE_STRCASECMP.
Referenced by GuessControllerType(), ParseLogCategory(), ParseLogPriority(), SDL_AddGamepadMappingsFromIO(), SDL_CreateDeviceName(), SDL_CreateRendererWithProperties(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_ShowMessageBox(), SDL_strcasestr(), SDL_URIToLocal(), and SDL_VideoInit().
SDL_strncmp()
int SDL_strncmp (const char * str1, const char * str2, size_t maxlen)
Compare two UTF-8 strings up to a number of bytes.
Due to the nature of UTF-8 encoding, this will work with Unicode strings, since effectively this function just compares bytes until it hits a null-terminating character. Also due to the nature of UTF-8, this can be used with SDL_qsort() to put strings in (roughly) alphabetical order.
Note that while this function is intended to be used with UTF-8, it is doing a bytewise comparison, and maxlen specifies a byte limit! If the limit lands in the middle of a multi-byte UTF-8 sequence, it will only compare a portion of the final character.
maxlen specifies a maximum number of bytes to compare; if the strings match to this number of bytes (or both have matched to a null-terminator character before this number of bytes), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of bytes to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRNCMP
    return strncmp(str1, str2, maxlen);
#else
    int result = 0;
    while (maxlen) {
        result = (int)(unsigned char)*str1 - (unsigned char)*str2;
        if (result != 0 || *str1 == '\0' /* && *str2 == '\0'*/) {
            break;
        }
        ++str1;
        ++str2;
        --maxlen;
    }
    return result;
#endif // HAVE_STRNCMP
}
Referenced by GetControllerTypeOverride(), HasPrefix(), PrefixMatch(), ref_string_equals(), SDL_Blit_Slow_Float(), SDL_getenv_unsafe(), SDL_IOFromFile(), SDL_IsTextMimeType(), SDL_LoadBMP_IO(), SDL_PromptAssertion(), SDL_setenv_unsafe(), SDL_ShouldIgnoreGamepad(), SDL_startswith(), SDL_strnstr(), SDL_unsetenv_unsafe(), SDL_vsnprintf(), SDL_vsscanf(), ShouldAttemptSensorFusion(), and ValidateStoragePath().
SDL_strndup()
char * SDL_strndup (const char * str, size_t maxlen)
Allocate a copy of a string, up to n characters.
This allocates enough space for a null-terminated copy of str, up to maxlen bytes, using SDL_malloc, and then makes a copy of the string into this space.
If the string is longer than maxlen bytes, the returned string will be maxlen bytes long, plus a null-terminator character that isn't included in the count.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
str the string to copy.
maxlen the maximum length of the copied string, not counting the null-terminator character.
Returns
a pointer to the newly-allocated string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t len = SDL_strnlen(string, maxlen);
    char *newstr = (char *)SDL_malloc(len + 1);
    if (newstr) {
        SDL_memcpy(newstr, string, len);
        newstr[len] = '\0';
    }
    return newstr;
}
References SDL_malloc(), SDL_memcpy, and SDL_strnlen().
SDL_strnlen()
size_t SDL_strnlen (const char * str, size_t maxlen)
This works exactly like strnlen() but doesn't require access to a C runtime.
Counts up to a maximum of maxlen bytes in str, excluding the null terminator.
If you need the length of a UTF-8 string, consider using SDL_utf8strnlen().
Parameters
str The null-terminated string to read. Must not be NULL.
maxlen The maximum amount of bytes to count.
Returns
the length (in bytes, excluding the null terminator) of src but never more than maxlen.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strlen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_STRNLEN
    return strnlen(string, maxlen);
#else
    size_t len = 0;
    while (len < maxlen && *string++) {
        ++len;
    }
    return len;
#endif // HAVE_STRNLEN
}
Referenced by SDL_strndup().
SDL_strnstr()
char * SDL_strnstr (const char * haystack, const char * needle, size_t maxlen)
Search a string, up to n bytes, for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator byte to end the string, or maxlen bytes have been examined. It is possible to use this function on a string without a null terminator.
Note that this looks for strings of bytes, not characters, so it's legal to search for malformed and incomplete UTF-8 sequences.
Parameters
haystack the string to search. Must not be NULL.
needle the string to search for. Must not be NULL.
maxlen the maximum number of bytes to search in haystack.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRNSTR
    return SDL_const_cast(char *, strnstr(haystack, needle, maxlen));
#else
    size_t length = SDL_strlen(needle);
    if (length == 0) {
        return (char *)haystack;
    }
    while (maxlen >= length && *haystack) {
        if (SDL_strncmp(haystack, needle, length) == 0) {
            return (char *)haystack;
        }
        ++haystack;
        --maxlen;
    }
    return NULL;
#endif // HAVE_STRSTR
}
References NULL, SDL_const_cast, SDL_strlen(), and SDL_strncmp().
Referenced by SDL_strstr().
SDL_strpbrk()
char * SDL_strpbrk (const char * str, const char * breakset)
Searches a string for the first occurence of any character contained in a breakset, and returns a pointer from the string to that character.
Parameters
str The null-terminated string to be searched. Must not be NULL, and must not overlap with breakset.
breakset A null-terminated string containing the list of characters to look for. Must not be NULL, and must not overlap with str.
Returns
A pointer to the location, in str, of the first occurence of a character present in the breakset, or NULL if none is found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRPBRK
    return strpbrk(str, breakset);
#else
    for (; *str; str++) {
        const char *b;
        for (b = breakset; *b; b++) {
            if (*str == *b) {
                return (char *) str;
            }
        }
    }
    return NULL;
#endif
}
References NULL.
SDL_strrchr()
char * SDL_strrchr (const char * str, int c)
Search a string for the last instance of a specific byte.
The search must go until it finds a null terminator byte to end the string.
Note that this looks for bytes, not characters, so you cannot match against a Unicode codepoint > 255, regardless of character encoding.
Parameters
str the string to search. Must not be NULL.
c the byte value to search for.
Returns
a pointer to the last instance of c in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRRCHR
    return SDL_const_cast(char *, strrchr(string, c));
#elif defined(HAVE_RINDEX)
    return SDL_const_cast(char *, rindex(string, c));
#else
    const char *bufp = string + SDL_strlen(string);
    while (bufp >= string) {
        if (*bufp == c) {
            return (char *)bufp;
        }
        --bufp;
    }
    return NULL;
#endif // HAVE_STRRCHR
}
References NULL, SDL_const_cast, and SDL_strlen().
Referenced by GetAppName(), SDL_GetExeName(), and SDL_SYS_GetPreferredLocales().
SDL_strrev()
char * SDL_strrev (char * str)
Reverse a string's contents.
This reverses a null-terminated string in-place. Only the content of the string is reversed; the null-terminator character remains at the end of the reversed string.
WARNING: This function reverses the bytes of the string, not the codepoints. If str is a UTF-8 string with Unicode codepoints > 127, this will ruin the string data. You should only use this function on strings that are completely comprised of low ASCII characters.
Parameters
str the string to reverse.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE__STRREV
    return _strrev(string);
#else
    size_t len = SDL_strlen(string);
    char *a = &string[0];
    char *b = &string[len - 1];
    len /= 2;
    while (len--) {
        const char c = *a; // NOLINT(clang-analyzer-core.uninitialized.Assign)
        *a++ = *b;
        *b-- = c;
    }
    return string;
#endif // HAVE__STRREV
}
References SDL_strlen().
Referenced by SDL_ulltoa(), and SDL_ultoa().
SDL_strstr()
char * SDL_strstr (const char * haystack, const char * needle)
Search a string for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator byte to end the string.
Note that this looks for strings of bytes, not characters, so it's legal to search for malformed and incomplete UTF-8 sequences.
Parameters
haystack the string to search. Must not be NULL.
needle the string to search for. Must not be NULL.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_STRSTR
    return SDL_const_cast(char *, strstr(haystack, needle));
#else
    return SDL_strnstr(haystack, needle, SDL_strlen(haystack));
#endif // HAVE_STRSTR
}
References SDL_const_cast, SDL_strlen(), and SDL_strnstr().
Referenced by CreateMappingString(), Fcitx_SetCapabilities(), GetControllerTypeOverride(), InitIME(), SDL_AddGamepadMappingsFromIO(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_GetGamepadTypeForID(), SDL_GetGamepadTypeFromVIDPID(), SDL_GL_ExtensionSupported(), SDL_KeycodeOptionsChanged(), SDL_LoadVIDPIDListFromHint(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadMappingForNameAndGUID(), SDL_PrivateMatchGamepadMappingForGUID(), SDL_PrivateParseGamepadElement(), SDL_ShouldIgnoreGamepad(), SDL_UpdateGamepadFaceStyle(), SDL_UpdateGamepadType(), SDL_URIToLocal(), and ShouldAttemptSensorFusion().
SDL_strtod()
double SDL_strtod (const char * str, char ** endp)
Parse a double from a string.
This function makes fewer guarantees than the C runtime strtod:
Only decimal notation is guaranteed to be supported. The handling of scientific and hexadecimal notation is unspecified.
Whether or not INF and NAN can be parsed is unspecified.
The precision of the result is unspecified.
Parameters
str the null-terminated string to read. Must not be NULL.
endp if not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
Returns
the parsed double, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoll
SDL_strtoul
SDL_strtoull
{
#ifdef HAVE_STRTOD
    return strtod(string, endp);
#else
    double value;
    size_t len = SDL_ScanFloat(string, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOD
}
References SDL_ScanFloat().
Referenced by SDL_atof().
SDL_strtol()
long SDL_strtol (const char * str, char ** endp, int base)
Parse a long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside a long, the result is clamped to the minimum and maximum representable long values.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtoul
SDL_strtoll
SDL_strtoull
SDL_strtod
SDL_ltoa
SDL_wcstol
{
#ifdef HAVE_STRTOL
    return strtol(string, endp, base);
#else
    long value = 0;
    size_t len = SDL_ScanLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOL
}
References SDL_ScanLong().
Referenced by SDL_atoi(), SDL_LoadVIDPIDListFromHint(), SDL_PrivateAddMappingForGUID(), SDL_PrivateMatchGamepadMappingForGUID(), and SDL_vsnprintf().
SDL_strtoll()
long long SDL_strtoll (const char * str, char ** endp, int base)
Parse a long long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside a long long, the result is clamped to the minimum and maximum representable long long values.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed long long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoul
SDL_strtoull
SDL_strtod
SDL_lltoa
{
#ifdef HAVE_STRTOLL
    return strtoll(string, endp, base);
#else
    long long value = 0;
    size_t len = SDL_ScanLongLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOLL
}
References SDL_ScanLongLong().
Referenced by SDL_GetNumberProperty().
SDL_strtoul()
unsigned long SDL_strtoul (const char * str, char ** endp, int base)
Parse an unsigned long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside an unsigned long, the result is clamped to the maximum representable unsigned long value.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed unsigned long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoll
SDL_strtoull
SDL_strtod
SDL_ultoa
{
#ifdef HAVE_STRTOUL
    return strtoul(string, endp, base);
#else
    unsigned long value = 0;
    size_t len = SDL_ScanUnsignedLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOUL
}
References SDL_ScanUnsignedLong().
Referenced by SDL_UpdateSteamVirtualGamepadInfo().
SDL_strtoull()
unsigned long long SDL_strtoull (const char * str, char ** endp, int base)
Parse an unsigned long long from a string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside an unsigned long long, the result is clamped to the maximum representable unsigned long long value.
Parameters
str The null-terminated string to read. Must not be NULL.
endp If not NULL, the address of the first invalid character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed unsigned long long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_atoi
SDL_atof
SDL_strtol
SDL_strtoll
SDL_strtoul
SDL_strtod
SDL_ulltoa
{
#ifdef HAVE_STRTOULL
    return strtoull(string, endp, base);
#else
    unsigned long long value = 0;
    size_t len = SDL_ScanUnsignedLongLong(string, 0, base, &value);
    if (endp) {
        *endp = (char *)string + len;
    }
    return value;
#endif // HAVE_STRTOULL
}
References SDL_ScanUnsignedLongLong().
Referenced by SDL_ScanFloat(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_strupr()
char * SDL_strupr (char * str)
Convert a string to uppercase.
WARNING: Regardless of system locale, this will only convert ASCII values 'A' through 'Z' to uppercase.
This function operates on a null-terminated string of bytes–even if it is malformed UTF-8!–and converts ASCII characters 'a' through 'z' to their uppercase equivalents in-place, returning the original str pointer.
Parameters
str the string to convert in-place. Can not be NULL.
Returns
the str pointer passed into this function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strlwr
{
    char *bufp = string;
    while (*bufp) {
        *bufp = (char)SDL_toupper((unsigned char)*bufp);
        ++bufp;
    }
    return string;
}
References SDL_toupper().
Referenced by SDL_PrintString().
SDL_swprintf()
int SDL_swprintf (SDL_OUT_Z_CAP(maxlen) wchar_t * text, size_t maxlen, SDL_PRINTF_FORMAT_STRING const wchar_t * fmt, ...)
{
    va_list ap;
    int result;
    va_start(ap, fmt);
    result = SDL_vswprintf(text, maxlen, fmt, ap);
    va_end(ap);
    return result;
}
References SDL_PRINTF_FORMAT_STRING, and SDL_vswprintf().
SDL_UCS4ToUTF8()
char * SDL_UCS4ToUTF8 (Uint32 codepoint, char * dst)
Convert a single Unicode codepoint to UTF-8.
The buffer pointed to by dst must be at least 4 bytes long, as this function may generate between 1 and 4 bytes of output.
This function returns the first byte after the newly-written UTF-8 sequence, which is useful for encoding multiple codepoints in a loop, or knowing where to write a NULL-terminator character to end the string (in either case, plan to have a buffer of more than 4 bytes!).
If codepoint is an invalid value (outside the Unicode range, or a UTF-16 surrogate value, etc), this will use U+FFFD (REPLACEMENT CHARACTER) for the codepoint instead, and not set an error.
If dst is NULL, this returns NULL immediately without writing to the pointer and without setting an error.
Parameters
codepoint a Unicode codepoint to convert to UTF-8.
dst the location to write the encoded UTF-8. Must point to at least 4 bytes!
Returns
the first byte past the newly-written UTF-8 sequence.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!dst) {
        return NULL;  // I guess...?
    } else if (codepoint > 0x10FFFF) {  // Outside the range of Unicode codepoints (also, larger than can be encoded in 4 bytes of UTF-8!).
        codepoint = SDL_INVALID_UNICODE_CODEPOINT;
    } else if ((codepoint >= 0xD800) && (codepoint <= 0xDFFF)) {  // UTF-16 surrogate values are illegal in UTF-8.
        codepoint = SDL_INVALID_UNICODE_CODEPOINT;
    }
    Uint8 *p = (Uint8 *)dst;
    if (codepoint <= 0x7F) {
        *p = (Uint8)codepoint;
        ++dst;
    } else if (codepoint <= 0x7FF) {
        p[0] = 0xC0 | (Uint8)((codepoint >> 6) & 0x1F);
        p[1] = 0x80 | (Uint8)(codepoint & 0x3F);
        dst += 2;
    } else if (codepoint <= 0xFFFF) {
        p[0] = 0xE0 | (Uint8)((codepoint >> 12) & 0x0F);
        p[1] = 0x80 | (Uint8)((codepoint >> 6) & 0x3F);
        p[2] = 0x80 | (Uint8)(codepoint & 0x3F);
        dst += 3;
    } else {
        SDL_assert(codepoint <= 0x10FFFF);
        p[0] = 0xF0 | (Uint8)((codepoint >> 18) & 0x07);
        p[1] = 0x80 | (Uint8)((codepoint >> 12) & 0x3F);
        p[2] = 0x80 | (Uint8)((codepoint >> 6) & 0x3F);
        p[3] = 0x80 | (Uint8)(codepoint & 0x3F);
        dst += 4;
    }
    return dst;
}
References NULL, SDL_assert, and SDL_INVALID_UNICODE_CODEPOINT.
Referenced by SDL_GetKeyName().
SDL_uitoa()
char * SDL_uitoa (unsigned int value, char * str, int radix)
Convert an unsigned integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget null terminator bytes, etc).
Parameters
value the unsigned integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_itoa
SDL_ultoa
SDL_ulltoa
{
#ifdef HAVE__UITOA
    return _uitoa(value, string, radix);
#else
    return SDL_ultoa((unsigned long)value, string, radix);
#endif // HAVE__UITOA
}
References SDL_ultoa().
SDL_ulltoa()
char * SDL_ulltoa (unsigned long long value, char * str, int radix)
Convert an unsigned long long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget null terminator bytes, etc).
Parameters
value the unsigned long long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_lltoa
SDL_uitoa
SDL_ultoa
{
#ifdef HAVE__UI64TOA
    return _ui64toa(value, string, radix);
#else
    char *bufp = string;
    if (value) {
        while (value > 0) {
            *bufp++ = ntoa_table[value % radix];
            value /= radix;
        }
    } else {
        *bufp++ = '0';
    }
    *bufp = '\0';
    // The numbers went into the string backwards. :)
    SDL_strrev(string);
    return string;
#endif // HAVE__UI64TOA
}
References ntoa_table, and SDL_strrev().
Referenced by SDL_lltoa(), SDL_PrintPointer(), and SDL_PrintUnsignedLongLong().
SDL_ultoa()
char * SDL_ultoa (unsigned long value, char * str, int radix)
Convert an unsigned long integer into a string.
This requires a radix to specified for string format. Specifying 10 produces a decimal number, 16 hexidecimal, etc. Must be in the range of 2 to 36.
Note that this function will overflow a buffer if str is not large enough to hold the output! It may be safer to use SDL_snprintf to clamp output, or SDL_asprintf to allocate a buffer. Otherwise, it doesn't hurt to allocate much more space than you expect to use (and don't forget null terminator bytes, etc).
Parameters
value the unsigned long integer to convert.
str the buffer to write the string into.
radix the radix to use for string generation.
Returns
str.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ltoa
SDL_uitoa
SDL_ulltoa
{
#ifdef HAVE__ULTOA
    return _ultoa(value, string, radix);
#else
    char *bufp = string;
    if (value) {
        while (value > 0) {
            *bufp++ = ntoa_table[value % radix];
            value /= radix;
        }
    } else {
        *bufp++ = '0';
    }
    *bufp = '\0';
    // The numbers went into the string backwards. :)
    SDL_strrev(string);
    return string;
#endif // HAVE__ULTOA
}
References ntoa_table, and SDL_strrev().
Referenced by SDL_ltoa(), SDL_PrintUnsignedLong(), and SDL_uitoa().
SDL_utf8strlcpy()
size_t SDL_utf8strlcpy (SDL_OUT_Z_CAP(dst_bytes) char * dst, const char * src, size_t dst_bytes)
{
    size_t bytes = 0;
    if (dst_bytes > 0) {
        size_t src_bytes = SDL_strlen(src);
        size_t i = 0;
        size_t trailing_bytes = 0;
        bytes = SDL_min(src_bytes, dst_bytes - 1);
        if (bytes) {
            unsigned char c = (unsigned char)src[bytes - 1];
            if (UTF8_IsLeadByte(c)) {
                --bytes;
            } else if (UTF8_IsTrailingByte(c)) {
                for (i = bytes - 1; i != 0; --i) {
                    c = (unsigned char)src[i];
                    trailing_bytes = UTF8_GetTrailingBytes(c);
                    if (trailing_bytes) {
                        if ((bytes - i) != (trailing_bytes + 1)) {
                            bytes = i;
                        }
                        break;
                    }
                }
            }
            SDL_memcpy(dst, src, bytes);
        }
        dst[bytes] = '\0';
    }
    return bytes;
}
References SDL_memcpy, SDL_min, SDL_strlen(), UTF8_GetTrailingBytes(), UTF8_IsLeadByte, and UTF8_IsTrailingByte.
SDL_utf8strlen()
size_t SDL_utf8strlen (const char * str)
Count the number of codepoints in a UTF-8 string.
Counts the codepoints, not bytes, in str, excluding the null terminator.
If you need to count the bytes in a string instead, consider using SDL_strlen().
Since this handles Unicode, it expects the strings to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), so a malformed or incomplete UTF-8 sequence might increase the count by several replacement characters.
Parameters
str The null-terminated UTF-8 string to read. Must not be NULL.
Returns
The length (in codepoints, excluding the null terminator) of src.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_utf8strnlen
SDL_strlen
{
    size_t result = 0;
    while (SDL_StepUTF8(&str, NULL)) {
        result++;
    }
    return result;
}
References NULL, and SDL_StepUTF8().
Referenced by Fcitx_GetPreeditString().
SDL_utf8strnlen()
size_t SDL_utf8strnlen (const char * str, size_t bytes)
Count the number of codepoints in a UTF-8 string, up to n bytes.
Counts the codepoints, not bytes, in str, excluding the null terminator.
If you need to count the bytes in a string instead, consider using SDL_strnlen().
The counting stops at bytes bytes (not codepoints!). This seems counterintuitive, but makes it easy to express the total size of the string's buffer.
Since this handles Unicode, it expects the strings to be well-formed UTF-8 and not a null-terminated string of arbitrary bytes. Bytes that are not valid UTF-8 are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), so a malformed or incomplete UTF-8 sequence might increase the count by several replacement characters.
Parameters
str The null-terminated UTF-8 string to read. Must not be NULL.
bytes The maximum amount of bytes to count.
Returns
The length (in codepoints, excluding the null terminator) of src but never more than maxlen.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_utf8strlen
SDL_strnlen
{
    size_t result = 0;
    while (SDL_StepUTF8(&str, &bytes)) {
        result++;
    }
    return result;
}
References SDL_StepUTF8().
Referenced by DBus_MessageFilter().
SDL_vasprintf()
int SDL_vasprintf (char ** strp, SDL_PRINTF_FORMAT_STRING const char * fmt, va_list ap)
{
    int result;
    int size = 100; // Guess we need no more than 100 bytes
    char *p, *np;
    va_list aq;
    *strp = NULL;
    p = (char *)SDL_malloc(size);
    if (!p) {
        return -1;
    }
    while (1) {
        // Try to print in the allocated space
        va_copy(aq, ap);
        result = SDL_vsnprintf(p, size, fmt, aq);
        va_end(aq);
        // Check error code
        if (result < 0) {
            SDL_free(p);
            return result;
        }
        // If that worked, return the string
        if (result < size) {
            *strp = p;
            return result;
        }
        // Else try again with more space
        size = result + 1; // Precisely what is needed
        np = (char *)SDL_realloc(p, size);
        if (!np) {
            SDL_free(p);
            return -1;
        } else {
            p = np;
        }
    }
}
References NULL, SDL_free(), SDL_malloc(), SDL_PRINTF_FORMAT_STRING, SDL_realloc(), and SDL_vsnprintf().
Referenced by SDL_asprintf().
SDL_vsnprintf()
int SDL_vsnprintf (SDL_OUT_Z_CAP(maxlen) char * text, size_t maxlen, SDL_PRINTF_FORMAT_STRING const char * fmt, va_list ap)
{
    size_t length = 0;
    if (!text) {
        maxlen = 0;
    }
    if (!fmt) {
        fmt = "";
    }
    while (*fmt) {
        if (*fmt == '%') {
            bool done = false;
            bool check_flag;
            SDL_FormatInfo info;
            enum
            {
                DO_INT,
                DO_LONG,
                DO_LONGLONG,
                DO_SIZE_T
            } inttype = DO_INT;
            SDL_zero(info);
            info.radix = 10;
            info.precision = -1;
            check_flag = true;
            while (check_flag) {
                ++fmt;
                switch (*fmt) {
                case '-':
                    info.left_justify = true;
                    break;
                case '+':
                    info.force_sign = true;
                    break;
                case '#':
                    info.force_type = true;
                    break;
                case '0':
                    info.pad_zeroes = true;
                    break;
                default:
                    check_flag = false;
                    break;
                }
            }
            if (*fmt >= '0' && *fmt <= '9') {
                info.width = SDL_strtol(fmt, (char **)&fmt, 0);
            } else if (*fmt == '*') {
                ++fmt;
                info.width = va_arg(ap, int);
            }
            if (*fmt == '.') {
                ++fmt;
                if (*fmt >= '0' && *fmt <= '9') {
                    info.precision = SDL_strtol(fmt, (char **)&fmt, 0);
                } else if (*fmt == '*') {
                    ++fmt;
                    info.precision = va_arg(ap, int);
                } else {
                    info.precision = 0;
                }
                if (info.precision < 0) {
                    info.precision = 0;
                }
            }
            while (!done) {
                switch (*fmt) {
                case '%':
                    if (length < maxlen) {
                        text[length] = '%';
                    }
                    ++length;
                    done = true;
                    break;
                case 'c':
                    // char is promoted to int when passed through (...)
                    if (length < maxlen) {
                        text[length] = (char)va_arg(ap, int);
                    }
                    ++length;
                    done = true;
                    break;
                case 'h':
                    // short is promoted to int when passed through (...)
                    break;
                case 'l':
                    if (inttype < DO_LONGLONG) {
                        ++inttype;
                    }
                    break;
                case 'I':
                    if (SDL_strncmp(fmt, "I64", 3) == 0) {
                        fmt += 2;
                        inttype = DO_LONGLONG;
                    }
                    break;
                case 'z':
                    inttype = DO_SIZE_T;
                    break;
                case 'i':
                case 'd':
                    if (info.precision >= 0) {
                        info.pad_zeroes = false;
                    }
                    switch (inttype) {
                    case DO_INT:
                        length += SDL_PrintLong(TEXT_AND_LEN_ARGS, &info,
                                                (long)va_arg(ap, int));
                        break;
                    case DO_LONG:
                        length += SDL_PrintLong(TEXT_AND_LEN_ARGS, &info,
                                                va_arg(ap, long));
                        break;
                    case DO_LONGLONG:
                        length += SDL_PrintLongLong(TEXT_AND_LEN_ARGS, &info,
                                                    va_arg(ap, long long));
                        break;
                    case DO_SIZE_T:
                        length += SDL_PrintLongLong(TEXT_AND_LEN_ARGS, &info,
                                                    va_arg(ap, size_t));
                        break;
                    }
                    done = true;
                    break;
                case 'p':
                    info.force_case = SDL_CASE_LOWER;
                    length += SDL_PrintPointer(TEXT_AND_LEN_ARGS, &info, va_arg(ap, void *));
                    done = true;
                    break;
                case 'x':
                    info.force_case = SDL_CASE_LOWER;
                    SDL_FALLTHROUGH;
                case 'X':
                    if (info.force_case == SDL_CASE_NOCHANGE) {
                        info.force_case = SDL_CASE_UPPER;
                    }
                    if (info.radix == 10) {
                        info.radix = 16;
                    }
                    SDL_FALLTHROUGH;
                case 'o':
                    if (info.radix == 10) {
                        info.radix = 8;
                    }
                    SDL_FALLTHROUGH;
                case 'u':
                    info.force_sign = false;
                    if (info.precision >= 0) {
                        info.pad_zeroes = false;
                    }
                    switch (inttype) {
                    case DO_INT:
                        length += SDL_PrintUnsignedLong(TEXT_AND_LEN_ARGS, &info,
                                                        va_arg(ap, unsigned int));
                        break;
                    case DO_LONG:
                        length += SDL_PrintUnsignedLong(TEXT_AND_LEN_ARGS, &info,
                                                        va_arg(ap, unsigned long));
                        break;
                    case DO_LONGLONG:
                        length += SDL_PrintUnsignedLongLong(TEXT_AND_LEN_ARGS, &info,
                                                            va_arg(ap, unsigned long long));
                        break;
                    case DO_SIZE_T:
                        length += SDL_PrintUnsignedLongLong(TEXT_AND_LEN_ARGS, &info,
                                                            va_arg(ap, size_t));
                        break;
                    }
                    done = true;
                    break;
                case 'f':
                    length += SDL_PrintFloat(TEXT_AND_LEN_ARGS, &info, va_arg(ap, double), false);
                    done = true;
                    break;
                case 'g':
                    length += SDL_PrintFloat(TEXT_AND_LEN_ARGS, &info, va_arg(ap, double), true);
                    done = true;
                    break;
                case 'S':
                    info.pad_zeroes = false;
                    length += SDL_PrintStringW(TEXT_AND_LEN_ARGS, &info, va_arg(ap, wchar_t *));
                    done = true;
                    break;
                case 's':
                    info.pad_zeroes = false;
                    if (inttype > DO_INT) {
                        length += SDL_PrintStringW(TEXT_AND_LEN_ARGS, &info, va_arg(ap, wchar_t *));
                    } else {
                        length += SDL_PrintString(TEXT_AND_LEN_ARGS, &info, va_arg(ap, char *));
                    }
                    done = true;
                    break;
                default:
                    done = true;
                    break;
                }
                ++fmt;
            }
        } else {
            if (length < maxlen) {
                text[length] = *fmt;
            }
            ++fmt;
            ++length;
        }
    }
    if (length < maxlen) {
        text[length] = '\0';
    } else if (maxlen > 0) {
        text[maxlen - 1] = '\0';
    }
    return (int)length;
}
References SDL_FormatInfo::force_case, SDL_FormatInfo::force_sign, SDL_FormatInfo::force_type, SDL_FormatInfo::left_justify, SDL_FormatInfo::pad_zeroes, SDL_FormatInfo::precision, SDL_FormatInfo::radix, SDL_CASE_LOWER, SDL_CASE_NOCHANGE, SDL_CASE_UPPER, SDL_FALLTHROUGH, SDL_PRINTF_FORMAT_STRING, SDL_PrintFloat(), SDL_PrintLong(), SDL_PrintLongLong(), SDL_PrintPointer(), SDL_PrintString(), SDL_PrintStringW(), SDL_PrintUnsignedLong(), SDL_PrintUnsignedLongLong(), SDL_strncmp(), SDL_strtol(), SDL_zero, TEXT_AND_LEN_ARGS, and SDL_FormatInfo::width.
Referenced by SDL_snprintf(), SDL_vasprintf(), and SDL_vswprintf().
SDL_vsscanf()
int SDL_vsscanf (const char * text, SDL_SCANF_FORMAT_STRING const char * fmt, va_list ap)
{
    const char *start = text;
    int result = 0;
    if (!text || !*text) {
        return -1;
    }
    while (*fmt) {
        if (*fmt == ' ') {
            while (SDL_isspace((unsigned char)*text)) {
                ++text;
            }
            ++fmt;
            continue;
        }
        if (*fmt == '%') {
            bool done = false;
            long count = 0;
            int radix = 10;
            enum
            {
                DO_SHORT,
                DO_INT,
                DO_LONG,
                DO_LONGLONG,
                DO_SIZE_T
            } inttype = DO_INT;
            size_t advance;
            bool suppress = false;
            ++fmt;
            if (*fmt == '%') {
                if (*text == '%') {
                    ++text;
                    ++fmt;
                    continue;
                }
                break;
            }
            if (*fmt == '*') {
                suppress = true;
                ++fmt;
            }
            fmt += SDL_ScanLong(fmt, 0, 10, &count);
            if (*fmt == 'c') {
                if (!count) {
                    count = 1;
                }
                if (suppress) {
                    while (count--) {
                        ++text;
                    }
                } else {
                    char *valuep = va_arg(ap, char *);
                    while (count--) {
                        *valuep++ = *text++;
                    }
                    ++result;
                }
                continue;
            }
            while (SDL_isspace((unsigned char)*text)) {
                ++text;
            }
            // FIXME: implement more of the format specifiers
            while (!done) {
                switch (*fmt) {
                case '*':
                    suppress = true;
                    break;
                case 'h':
                    if (inttype == DO_INT) {
                        inttype = DO_SHORT;
                    } else if (inttype > DO_SHORT) {
                        ++inttype;
                    }
                    break;
                case 'l':
                    if (inttype < DO_LONGLONG) {
                        ++inttype;
                    }
                    break;
                case 'I':
                    if (SDL_strncmp(fmt, "I64", 3) == 0) {
                        fmt += 2;
                        inttype = DO_LONGLONG;
                    }
                    break;
                case 'z':
                    inttype = DO_SIZE_T;
                    break;
                case 'i':
                {
                    int index = 0;
                    if (text[index] == '-') {
                        ++index;
                    }
                    if (text[index] == '0') {
                        if (SDL_tolower((unsigned char)text[index + 1]) == 'x') {
                            radix = 16;
                        } else {
                            radix = 8;
                        }
                    }
                }
                    SDL_FALLTHROUGH;
                case 'd':
                    if (inttype == DO_LONGLONG) {
                        long long value = 0;
                        advance = SDL_ScanLongLong(text, count, radix, &value);
                        text += advance;
                        if (advance && !suppress) {
                            Sint64 *valuep = va_arg(ap, Sint64 *);
                            *valuep = value;
                            ++result;
                        }
                    } else if (inttype == DO_SIZE_T) {
                        long long value = 0;
                        advance = SDL_ScanLongLong(text, count, radix, &value);
                        text += advance;
                        if (advance && !suppress) {
                            size_t *valuep = va_arg(ap, size_t *);
                            *valuep = (size_t)value;
                            ++result;
                        }
                    } else {
                        long value = 0;
                        advance = SDL_ScanLong(text, count, radix, &value);
                        text += advance;
                        if (advance && !suppress) {
                            switch (inttype) {
                            case DO_SHORT:
{
                                short *valuep = va_arg(ap, short *);
                                *valuep = (short)value;
                            } break;
                            case DO_INT:
{
                                int *valuep = va_arg(ap, int *);
                                *valuep = (int)value;
                            } break;
                            case DO_LONG:
{
                                long *valuep = va_arg(ap, long *);
                                *valuep = value;
                            } break;
                            case DO_LONGLONG:
                            case DO_SIZE_T:
                                // Handled above
                                break;
                            }
                            ++result;
                        }
                    }
                    done = true;
                    break;
                case 'o':
                    if (radix == 10) {
                        radix = 8;
                    }
                    SDL_FALLTHROUGH;
                case 'x':
                case 'X':
                    if (radix == 10) {
                        radix = 16;
                    }
                    SDL_FALLTHROUGH;
                case 'u':
                    if (inttype == DO_LONGLONG) {
                        unsigned long long value = 0;
                        advance = SDL_ScanUnsignedLongLong(text, count, radix, &value);
                        text += advance;
                        if (advance && !suppress) {
                            Uint64 *valuep = va_arg(ap, Uint64 *);
                            *valuep = value;
                            ++result;
                        }
                    } else if (inttype == DO_SIZE_T) {
                        unsigned long long value = 0;
                        advance = SDL_ScanUnsignedLongLong(text, count, radix, &value);
                        text += advance;
                        if (advance && !suppress) {
                            size_t *valuep = va_arg(ap, size_t *);
                            *valuep = (size_t)value;
                            ++result;
                        }
                    } else {
                        unsigned long value = 0;
                        advance = SDL_ScanUnsignedLong(text, count, radix, &value);
                        text += advance;
                        if (advance && !suppress) {
                            switch (inttype) {
                            case DO_SHORT:
{
                                short *valuep = va_arg(ap, short *);
                                *valuep = (short)value;
                            } break;
                            case DO_INT:
{
                                int *valuep = va_arg(ap, int *);
                                *valuep = (int)value;
                            } break;
                            case DO_LONG:
{
                                long *valuep = va_arg(ap, long *);
                                *valuep = value;
                            } break;
                            case DO_LONGLONG:
                            case DO_SIZE_T:
                                // Handled above
                                break;
                            }
                            ++result;
                        }
                    }
                    done = true;
                    break;
                case 'p':
                {
                    uintptr_t value = 0;
                    advance = SDL_ScanUintPtrT(text, &value);
                    text += advance;
                    if (advance && !suppress) {
                        void **valuep = va_arg(ap, void **);
                        *valuep = (void *)value;
                        ++result;
                    }
                }
                    done = true;
                    break;
                case 'f':
                {
                    double value = 0.0;
                    advance = SDL_ScanFloat(text, &value);
                    text += advance;
                    if (advance && !suppress) {
                        float *valuep = va_arg(ap, float *);
                        *valuep = (float)value;
                        ++result;
                    }
                }
                    done = true;
                    break;
                case 's':
                    if (suppress) {
                        while (!SDL_isspace((unsigned char)*text)) {
                            ++text;
                            if (count) {
                                if (--count == 0) {
                                    break;
                                }
                            }
                        }
                    } else {
                        char *valuep = va_arg(ap, char *);
                        while (!SDL_isspace((unsigned char)*text)) {
                            *valuep++ = *text++;
                            if (count) {
                                if (--count == 0) {
                                    break;
                                }
                            }
                        }
                        *valuep = '\0';
                        ++result;
                    }
                    done = true;
                    break;
                case 'n':
                    switch (inttype) {
                    case DO_SHORT:
                    {
                        short *valuep = va_arg(ap, short *);
                        *valuep = (short)(text - start);
                    } break;
                    case DO_INT:
                    {
                        int *valuep = va_arg(ap, int *);
                        *valuep = (int)(text - start);
                    } break;
                    case DO_LONG:
                    {
                        long *valuep = va_arg(ap, long *);
                        *valuep = (long)(text - start);
                    } break;
                    case DO_LONGLONG:
                    {
                        long long *valuep = va_arg(ap, long long *);
                        *valuep = (long long)(text - start);
                    } break;
                    case DO_SIZE_T:
                    {
                        size_t *valuep = va_arg(ap, size_t *);
                        *valuep = (size_t)(text - start);
                    } break;
                    }
                    done = true;
                    break;
                case '[':
                {
                    const char *set = fmt + 1;
                    while (*fmt && *fmt != ']') {
                        ++fmt;
                    }
                    if (*fmt) {
                        size_t set_len = (fmt - set);
                        if (suppress) {
                            while (CharacterMatchesSet(*text, set, set_len)) {
                                ++text;
                                if (count) {
                                    if (--count == 0) {
                                        break;
                                    }
                                }
                            }
                        } else {
                            bool had_match = false;
                            char *valuep = va_arg(ap, char *);
                            while (CharacterMatchesSet(*text, set, set_len)) {
                                had_match = true;
                                *valuep++ = *text++;
                                if (count) {
                                    if (--count == 0) {
                                        break;
                                    }
                                }
                            }
                            *valuep = '\0';
                            if (had_match) {
                                ++result;
                            }
                        }
                    }
                }
                    done = true;
                    break;
                default:
                    done = true;
                    break;
                }
                ++fmt;
            }
            continue;
        }
        if (*text == *fmt) {
            ++text;
            ++fmt;
            continue;
        }
        // Text didn't match format specifier
        break;
    }
    return result;
}
References CharacterMatchesSet(), count, SDL_FALLTHROUGH, SDL_isspace(), SDL_SCANF_FORMAT_STRING, SDL_ScanFloat(), SDL_ScanLong(), SDL_ScanLongLong(), SDL_ScanUintPtrT(), SDL_ScanUnsignedLong(), SDL_ScanUnsignedLongLong(), SDL_strncmp(), and SDL_tolower().
Referenced by SDL_sscanf().
SDL_vswprintf()
int SDL_vswprintf (SDL_OUT_Z_CAP(maxlen) wchar_t * text, size_t maxlen, const wchar_t * fmt, va_list ap)
{
    char *fmt_utf8 = NULL;
    if (fmt) {
        fmt_utf8 = SDL_iconv_string("UTF-8", "WCHAR_T", (const char *)fmt, (SDL_wcslen(fmt) + 1) * sizeof(wchar_t));
        if (!fmt_utf8) {
            return -1;
        }
    }
    char tinybuf[64];  // for really small strings, calculate it once.
    // generate the text to find the final text length
    va_list aq;
    va_copy(aq, ap);
    const int utf8len = SDL_vsnprintf(tinybuf, sizeof (tinybuf), fmt_utf8, aq);
    va_end(aq);
    if (utf8len < 0) {
        SDL_free(fmt_utf8);
        return -1;
    }
    bool isstack = false;
    char *smallbuf = NULL;
    char *utf8buf;
    int result;
    if (utf8len < sizeof (tinybuf)) {   // whole thing fit in the stack buffer, just use that copy.
        utf8buf = tinybuf;
    } else {  // didn't fit in the stack buffer, allocate the needed space and run it again.
        utf8buf = smallbuf = SDL_small_alloc(char, utf8len + 1, &isstack);
        if (!smallbuf) {
            SDL_free(fmt_utf8);
            return -1;  // oh well.
        }
        const int utf8len2 = SDL_vsnprintf(smallbuf, utf8len + 1, fmt_utf8, ap);
        if (utf8len2 > utf8len) {
            SDL_free(fmt_utf8);
            return SDL_SetError("Formatted output changed between two runs");  // race condition on the parameters, and we no longer have room...yikes.
        }
    }
    SDL_free(fmt_utf8);
    wchar_t *wbuf = (wchar_t *)SDL_iconv_string("WCHAR_T", "UTF-8", utf8buf, utf8len + 1);
    if (wbuf) {
        if (text) {
            SDL_wcslcpy(text, wbuf, maxlen);
        }
        result = (int)SDL_wcslen(wbuf);
        SDL_free(wbuf);
    } else {
        result = -1;
    }
    if (smallbuf != NULL) {
        SDL_small_free(smallbuf, isstack);
    }
    return result;
}
References NULL, SDL_free(), SDL_iconv_string(), SDL_SetError(), SDL_small_alloc, SDL_small_free, SDL_vsnprintf(), SDL_wcslcpy(), and SDL_wcslen().
Referenced by SDL_swprintf().
SDL_wcscasecmp()
int SDL_wcscasecmp (const wchar_t * str1, const wchar_t * str2)
Compare two null-terminated wide strings, case-insensitively.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Depending on your platform, "wchar_t" might be 2 bytes, and expected to be UTF-16 encoded (like Windows), or 4 bytes in UTF-32 format. Since this handles Unicode, it expects the string to be well-formed and not a null-terminated string of arbitrary bytes. Characters that are not valid UTF-16 (or UTF-32) are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#if (SDL_SIZEOF_WCHAR_T == 2)
    const Uint16 *str1 = (const Uint16 *) wstr1;
    const Uint16 *str2 = (const Uint16 *) wstr2;
    UNICODE_STRCASECMP(16, 2, 2, (void) str1start, (void) str2start);  // always NULL-terminated, no need to adjust lengths.
#elif (SDL_SIZEOF_WCHAR_T == 4)
    const Uint32 *str1 = (const Uint32 *) wstr1;
    const Uint32 *str2 = (const Uint32 *) wstr2;
    UNICODE_STRCASECMP(32, 1, 1, (void) str1start, (void) str2start);  // always NULL-terminated, no need to adjust lengths.
#else
    #error Unexpected wchar_t size
    return -1;
#endif
}
References UNICODE_STRCASECMP.
SDL_wcscmp()
int SDL_wcscmp (const wchar_t * str1, const wchar_t * str2)
Compare two null-terminated wide strings.
This only compares wchar_t values until it hits a null-terminating character; it does not care if the string is well-formed UTF-16 (or UTF-32, depending on your platform's wchar_t size), or uses valid Unicode values.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_WCSCMP
    return wcscmp(str1, str2);
#else
    while (*str1 && *str2) {
        if (*str1 != *str2) {
            break;
        }
        ++str1;
        ++str2;
    }
    return *str1 - *str2;
#endif // HAVE_WCSCMP
}
References wcscmp.
Referenced by TrayWindowProc().
SDL_wcsdup()
wchar_t * SDL_wcsdup (const wchar_t * wstr)
Allocate a copy of a wide string.
This allocates enough space for a null-terminated copy of wstr, using SDL_malloc, and then makes a copy of the string into this space.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
wstr the string to copy.
Returns
a pointer to the newly-allocated wide string.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t len = ((SDL_wcslen(string) + 1) * sizeof(wchar_t));
    wchar_t *newstr = (wchar_t *)SDL_malloc(len);
    if (newstr) {
        SDL_memcpy(newstr, string, len);
    }
    return newstr;
}
References SDL_malloc(), SDL_memcpy, and SDL_wcslen().
SDL_wcslcat()
size_t SDL_wcslcat (SDL_INOUT_Z_CAP(maxlen) wchar_t * dst, const wchar_t * src, size_t maxlen)
{
#ifdef HAVE_WCSLCAT
    return wcslcat(dst, src, maxlen);
#else
    size_t dstlen = SDL_wcslen(dst);
    size_t srclen = SDL_wcslen(src);
    if (dstlen < maxlen) {
        SDL_wcslcpy(dst + dstlen, src, maxlen - dstlen);
    }
    return dstlen + srclen;
#endif // HAVE_WCSLCAT
}
References SDL_wcslcpy(), and SDL_wcslen().
SDL_wcslcpy()
size_t SDL_wcslcpy (SDL_OUT_Z_CAP(maxlen) wchar_t * dst, const wchar_t * src, size_t maxlen)
{
#ifdef HAVE_WCSLCPY
    return wcslcpy(dst, src, maxlen);
#else
    size_t srclen = SDL_wcslen(src);
    if (maxlen > 0) {
        size_t len = SDL_min(srclen, maxlen - 1);
        SDL_memcpy(dst, src, len * sizeof(wchar_t));
        dst[len] = '\0';
    }
    return srclen;
#endif // HAVE_WCSLCPY
}
References SDL_memcpy, SDL_min, and SDL_wcslen().
Referenced by SDL_vswprintf(), and SDL_wcslcat().
SDL_wcslen()
size_t SDL_wcslen (const wchar_t * wstr)
This works exactly like wcslen() but doesn't require access to a C runtime.
Counts the number of wchar_t values in wstr, excluding the null terminator.
Like SDL_strlen only counts bytes and not codepoints in a UTF-8 string, this counts wchar_t values in a string, even if the string's encoding is of variable width, like UTF-16.
Also be aware that wchar_t is different sizes on different platforms (4 bytes on Linux, 2 on Windows, etc).
Parameters
wstr The null-terminated wide string to read. Must not be NULL.
Returns
the length (in wchar_t values, excluding the null terminator) of wstr.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_wcsnlen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_WCSLEN
    return wcslen(string);
#else
    size_t len = 0;
    while (*string++) {
        ++len;
    }
    return len;
#endif // HAVE_WCSLEN
}
References wcslen.
Referenced by CreateWStringFromWString(), SDL_CreateEnvironment(), SDL_PrintStringW(), SDL_SetTrayEntryLabel(), SDL_vswprintf(), SDL_wcsdup(), SDL_wcslcat(), SDL_wcslcpy(), SDL_wcsnstr(), SDL_wcsstr(), and windows_ShowFileDialog().
SDL_wcsncasecmp()
int SDL_wcsncasecmp (const wchar_t * str1, const wchar_t * str2, size_t maxlen)
Compare two wide strings, case-insensitively, up to a number of wchar_t.
This will work with Unicode strings, using a technique called "case-folding" to handle the vast majority of case-sensitive human languages regardless of system locale. It can deal with expanding values: a German Eszett character can compare against two ASCII 's' chars and be considered a match, for example. A notable exception: it does not handle the Turkish 'i' character; human language is complicated!
Depending on your platform, "wchar_t" might be 2 bytes, and expected to be UTF-16 encoded (like Windows), or 4 bytes in UTF-32 format. Since this handles Unicode, it expects the string to be well-formed and not a null-terminated string of arbitrary bytes. Characters that are not valid UTF-16 (or UTF-32) are treated as Unicode character U+FFFD (REPLACEMENT CHARACTER), which is to say two strings of random bits may turn out to match if they convert to the same amount of replacement characters.
Note that while this function might deal with variable-sized characters, maxlen specifies a wchar limit! If the limit lands in the middle of a multi-byte UTF-16 sequence, it may convert a portion of the final character to one or more Unicode character U+FFFD (REPLACEMENT CHARACTER) so as not to overflow a buffer.
maxlen specifies a maximum number of wchar_t values to compare; if the strings match to this number of wchar_t (or both have matched to a null-terminator character before this number of bytes), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of wchar_t values to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t slen1 = maxlen;
    size_t slen2 = maxlen;
#if (SDL_SIZEOF_WCHAR_T == 2)
    const Uint16 *str1 = (const Uint16 *) wstr1;
    const Uint16 *str2 = (const Uint16 *) wstr2;
    UNICODE_STRCASECMP(16, slen1, slen2, slen1 -= (size_t) (str1 - str1start), slen2 -= (size_t) (str2 - str2start));
#elif (SDL_SIZEOF_WCHAR_T == 4)
    const Uint32 *str1 = (const Uint32 *) wstr1;
    const Uint32 *str2 = (const Uint32 *) wstr2;
    UNICODE_STRCASECMP(32, slen1, slen2, slen1 -= (size_t) (str1 - str1start), slen2 -= (size_t) (str2 - str2start));
#else
    #error Unexpected wchar_t size
    return -1;
#endif
}
References UNICODE_STRCASECMP.
SDL_wcsncmp()
int SDL_wcsncmp (const wchar_t * str1, const wchar_t * str2, size_t maxlen)
Compare two wide strings up to a number of wchar_t values.
This only compares wchar_t values; it does not care if the string is well-formed UTF-16 (or UTF-32, depending on your platform's wchar_t size), or uses valid Unicode values.
Note that while this function is intended to be used with UTF-16 (or UTF-32, depending on your platform's definition of wchar_t), it is comparing raw wchar_t values and not Unicode codepoints: maxlen specifies a wchar_t limit! If the limit lands in the middle of a multi-wchar UTF-16 sequence, it will only compare a portion of the final character.
maxlen specifies a maximum number of wchar_t to compare; if the strings match to this number of wide chars (or both have matched to a null-terminator character before this count), they will be considered equal.
Parameters
str1 the first string to compare. NULL is not permitted!
str2 the second string to compare. NULL is not permitted!
maxlen the maximum number of wchar_t to compare.
Returns
less than zero if str1 is "less than" str2, greater than zero if str1 is "greater than" str2, and zero if the strings match exactly.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_WCSNCMP
    return wcsncmp(str1, str2, maxlen);
#else
    while (*str1 && *str2 && maxlen) {
        if (*str1 != *str2) {
            break;
        }
        ++str1;
        ++str2;
        --maxlen;
    }
    if (!maxlen) {
        return 0;
    }
    return *str1 - *str2;
#endif // HAVE_WCSNCMP
}
Referenced by SDL_wcsnstr().
SDL_wcsnlen()
size_t SDL_wcsnlen (const wchar_t * wstr, size_t maxlen)
This works exactly like wcsnlen() but doesn't require access to a C runtime.
Counts up to a maximum of maxlen wchar_t values in wstr, excluding the null terminator.
Like SDL_strnlen only counts bytes and not codepoints in a UTF-8 string, this counts wchar_t values in a string, even if the string's encoding is of variable width, like UTF-16.
Also be aware that wchar_t is different sizes on different platforms (4 bytes on Linux, 2 on Windows, etc).
Also, maxlen is a count of wide characters, not bytes!
Parameters
wstr The null-terminated wide string to read. Must not be NULL.
maxlen The maximum amount of wide characters to count.
Returns
the length (in wide characters, excluding the null terminator) of wstr but never more than maxlen.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_wcslen
SDL_utf8strlen
SDL_utf8strnlen
{
#ifdef HAVE_WCSNLEN
    return wcsnlen(string, maxlen);
#else
    size_t len = 0;
    while (len < maxlen && *string++) {
        ++len;
    }
    return len;
#endif // HAVE_WCSNLEN
}
SDL_wcsnstr()
wchar_t * SDL_wcsnstr (const wchar_t * haystack, const wchar_t * needle, size_t maxlen)
Search a wide string, up to n wide chars, for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator value to end the string, or maxlen wide character have been examined. It is possible to use this function on a wide string without a null terminator.
Note that this looks for strings of wide characters, not codepoints, so it's legal to search for malformed and incomplete UTF-16 sequences.
Parameters
haystack the wide string to search. Must not be NULL.
needle the wide string to search for. Must not be NULL.
maxlen the maximum number of wide characters to search in haystack.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    size_t length = SDL_wcslen(needle);
    if (length == 0) {
        return (wchar_t *)haystack;
    }
    while (maxlen >= length && *haystack) {
        if (maxlen >= length && SDL_wcsncmp(haystack, needle, length) == 0) {
            return (wchar_t *)haystack;
        }
        ++haystack;
        --maxlen;
    }
    return NULL;
}
References NULL, SDL_wcslen(), and SDL_wcsncmp().
Referenced by SDL_wcsstr().
SDL_wcsstr()
wchar_t * SDL_wcsstr (const wchar_t * haystack, const wchar_t * needle)
Search a wide string for the first instance of a specific substring.
The search ends once it finds the requested substring, or a null terminator byte to end the string.
Note that this looks for strings of wide characters, not codepoints, so it's legal to search for malformed and incomplete UTF-16 sequences.
Parameters
haystack the wide string to search. Must not be NULL.
needle the wide string to search for. Must not be NULL.
Returns
a pointer to the first instance of needle in the string, or NULL if not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef HAVE_WCSSTR
    return SDL_const_cast(wchar_t *, wcsstr(haystack, needle));
#else
    return SDL_wcsnstr(haystack, needle, SDL_wcslen(haystack));
#endif // HAVE_WCSSTR
}
References SDL_const_cast, SDL_wcslen(), SDL_wcsnstr(), and wcsstr.
SDL_wcstol()
long SDL_wcstol (const wchar_t * str, wchar_t ** endp, int base)
Parse a long from a wide string.
If str starts with whitespace, then those whitespace characters are skipped before attempting to parse the number.
If the parsed number does not fit inside a long, the result is clamped to the minimum and maximum representable long values.
Parameters
str The null-terminated wide string to read. Must not be NULL.
endp If not NULL, the address of the first invalid wide character (i.e. the next character after the parsed number) will be written to this pointer.
base The base of the integer to read. Supported values are 0 and 2 to 36 inclusive. If 0, the base will be inferred from the number's prefix (0x for hexadecimal, 0 for octal, decimal otherwise).
Returns
the parsed long, or 0 if no number could be parsed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_strtol
{
#ifdef HAVE_WCSTOL
    return wcstol(string, endp, base);
#else
    long value = 0;
    size_t len = SDL_ScanLongW(string, 0, base, &value);
    if (endp) {
        *endp = (wchar_t *)string + len;
    }
    return value;
#endif // HAVE_WCSTOL
}
References SDL_ScanLongW(), and wcstol.
StepUTF32()
Uint32 StepUTF32 (const Uint32 ** _str, const size_t slen) static
{
    if (!slen) {
        return 0;
    }
    const Uint32 *str = *_str;
    const Uint32 cp = *str;
    if (cp == 0) {
        return 0;  // don't advance string pointer.
    }
    (*_str)++;
    return (cp > 0x10FFFF) ? SDL_INVALID_UNICODE_CODEPOINT : cp;
}
References cp, and SDL_INVALID_UNICODE_CODEPOINT.
StepUTF8()
Uint32 StepUTF8 (const char ** _str, const size_t slen) static
{
    /*
     * From rfc3629, the UTF-8 spec:
     *  https://www.ietf.org/rfc/rfc3629.txt
     *
     *   Char. number range  |        UTF-8 octet sequence
     *      (hexadecimal)    |              (binary)
     *   --------------------+---------------------------------------------
     *   0000 0000-0000 007F | 0xxxxxxx
     *   0000 0080-0000 07FF | 110xxxxx 10xxxxxx
     *   0000 0800-0000 FFFF | 1110xxxx 10xxxxxx 10xxxxxx
     *   0001 0000-0010 FFFF | 11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
     */
    const Uint8 *str = (const Uint8 *) *_str;
    const Uint32 octet = (Uint32) (slen ? *str : 0);
    if (octet == 0) {  // null terminator, end of string.
        return 0;  // don't advance `*_str`.
    } else if ((octet & 0x80) == 0) {  // 0xxxxxxx: one byte codepoint.
        (*_str)++;
        return octet;
    } else if (((octet & 0xE0) == 0xC0) && (slen >= 2)) {  // 110xxxxx 10xxxxxx: two byte codepoint.
        const Uint8 str1 = str[1];
        if ((str1 & 0xC0) == 0x80) {  // If trailing bytes aren't 10xxxxxx, sequence is bogus.
            const Uint32 result = ((octet & 0x1F) << 6) | (str1 & 0x3F);
            if (result >= 0x0080) {  // rfc3629 says you can't use overlong sequences for smaller values.
                *_str += 2;
                return result;
            }
        }
    } else if (((octet & 0xF0) == 0xE0) && (slen >= 3)) {  // 1110xxxx 10xxxxxx 10xxxxxx: three byte codepoint.
        const Uint8 str1 = str[1];
        const Uint8 str2 = str[2];
        if (((str1 & 0xC0) == 0x80) && ((str2 & 0xC0) == 0x80)) {  // If trailing bytes aren't 10xxxxxx, sequence is bogus.
            const Uint32 octet2 = ((Uint32) (str1 & 0x3F)) << 6;
            const Uint32 octet3 = ((Uint32) (str2 & 0x3F));
            const Uint32 result = ((octet & 0x0F) << 12) | octet2 | octet3;
            if (result >= 0x800) {  // rfc3629 says you can't use overlong sequences for smaller values.
                if ((result < 0xD800) || (result > 0xDFFF)) {  // UTF-16 surrogate values are illegal in UTF-8.
                    *_str += 3;
                    return result;
                }
            }
        }
    } else if (((octet & 0xF8) == 0xF0) && (slen >= 4)) {  // 11110xxxx 10xxxxxx 10xxxxxx 10xxxxxx: four byte codepoint.
        const Uint8 str1 = str[1];
        const Uint8 str2 = str[2];
        const Uint8 str3 = str[3];
        if (((str1 & 0xC0) == 0x80) && ((str2 & 0xC0) == 0x80) && ((str3 & 0xC0) == 0x80)) {  // If trailing bytes aren't 10xxxxxx, sequence is bogus.
            const Uint32 octet2 = ((Uint32) (str1 & 0x1F)) << 12;
            const Uint32 octet3 = ((Uint32) (str2 & 0x3F)) << 6;
            const Uint32 octet4 = ((Uint32) (str3 & 0x3F));
            const Uint32 result = ((octet & 0x07) << 18) | octet2 | octet3 | octet4;
            if (result >= 0x10000) {  // rfc3629 says you can't use overlong sequences for smaller values.
                *_str += 4;
                return result;
            }
        }
    }
    // bogus byte, skip ahead, return a REPLACEMENT CHARACTER.
    (*_str)++;
    return SDL_INVALID_UNICODE_CODEPOINT;
}
References SDL_INVALID_UNICODE_CODEPOINT.
Referenced by SDL_StepBackUTF8(), and SDL_StepUTF8().
UTF8_GetTrailingBytes()
size_t UTF8_GetTrailingBytes (unsigned char c) static
{
    if (c >= 0xC0 && c <= 0xDF) {
        return 1;
    } else if (c >= 0xE0 && c <= 0xEF) {
        return 2;
    } else if (c >= 0xF0 && c <= 0xF4) {
        return 3;
    }
    return 0;
}
Referenced by SDL_utf8strlcpy().
Variable Documentation
ntoa_table
const char ntoa_table[] static
Initial value:
= {
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
    'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U', 'V', 'W', 'X', 'Y', 'Z'
}
{
    '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
    'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U', 'V', 'W', 'X', 'Y', 'Z'
};
Referenced by SDL_ulltoa(), and SDL_ultoa().