SDL3: SDL-main/include/SDL3/SDL_gamepad.h File Reference
SDL_gamepad.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_guid.h>
#include <SDL3/SDL_iostream.h>
#include <SDL3/SDL_joystick.h>
#include <SDL3/SDL_power.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_sensor.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_GamepadBinding
Macros
#define SDL_PROP_GAMEPAD_CAP_MONO_LED_BOOLEAN SDL_PROP_JOYSTICK_CAP_MONO_LED_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_PLAYER_LED_BOOLEAN SDL_PROP_JOYSTICK_CAP_PLAYER_LED_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_RGB_LED_BOOLEAN SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_RUMBLE_BOOLEAN SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_TRIGGER_RUMBLE_BOOLEAN SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN
Typedefs
typedef struct SDL_Gamepad SDL_Gamepad
typedef enum SDL_GamepadAxis SDL_GamepadAxis
typedef struct SDL_GamepadBinding SDL_GamepadBinding
typedef enum SDL_GamepadBindingType SDL_GamepadBindingType
typedef enum SDL_GamepadButton SDL_GamepadButton
typedef enum SDL_GamepadButtonLabel SDL_GamepadButtonLabel
typedef enum SDL_GamepadType SDL_GamepadType
Enumerations
enum SDL_GamepadAxis {
SDL_GAMEPAD_AXIS_INVALID = -1 , SDL_GAMEPAD_AXIS_LEFTX , SDL_GAMEPAD_AXIS_LEFTY , SDL_GAMEPAD_AXIS_RIGHTX ,
SDL_GAMEPAD_AXIS_RIGHTY , SDL_GAMEPAD_AXIS_LEFT_TRIGGER , SDL_GAMEPAD_AXIS_RIGHT_TRIGGER , SDL_GAMEPAD_AXIS_COUNT
}
enum SDL_GamepadBindingType { SDL_GAMEPAD_BINDTYPE_NONE = 0 , SDL_GAMEPAD_BINDTYPE_BUTTON , SDL_GAMEPAD_BINDTYPE_AXIS , SDL_GAMEPAD_BINDTYPE_HAT }
enum SDL_GamepadButton {
SDL_GAMEPAD_BUTTON_INVALID = -1 , SDL_GAMEPAD_BUTTON_SOUTH , SDL_GAMEPAD_BUTTON_EAST , SDL_GAMEPAD_BUTTON_WEST ,
SDL_GAMEPAD_BUTTON_NORTH , SDL_GAMEPAD_BUTTON_BACK , SDL_GAMEPAD_BUTTON_GUIDE , SDL_GAMEPAD_BUTTON_START ,
SDL_GAMEPAD_BUTTON_LEFT_STICK , SDL_GAMEPAD_BUTTON_RIGHT_STICK , SDL_GAMEPAD_BUTTON_LEFT_SHOULDER , SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER ,
SDL_GAMEPAD_BUTTON_DPAD_UP , SDL_GAMEPAD_BUTTON_DPAD_DOWN , SDL_GAMEPAD_BUTTON_DPAD_LEFT , SDL_GAMEPAD_BUTTON_DPAD_RIGHT ,
SDL_GAMEPAD_BUTTON_MISC1 , SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1 , SDL_GAMEPAD_BUTTON_LEFT_PADDLE1 , SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2 ,
SDL_GAMEPAD_BUTTON_LEFT_PADDLE2 , SDL_GAMEPAD_BUTTON_TOUCHPAD , SDL_GAMEPAD_BUTTON_MISC2 , SDL_GAMEPAD_BUTTON_MISC3 ,
SDL_GAMEPAD_BUTTON_MISC4 , SDL_GAMEPAD_BUTTON_MISC5 , SDL_GAMEPAD_BUTTON_MISC6 , SDL_GAMEPAD_BUTTON_COUNT
}
enum SDL_GamepadButtonLabel {
SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN , SDL_GAMEPAD_BUTTON_LABEL_A , SDL_GAMEPAD_BUTTON_LABEL_B , SDL_GAMEPAD_BUTTON_LABEL_X ,
SDL_GAMEPAD_BUTTON_LABEL_Y , SDL_GAMEPAD_BUTTON_LABEL_CROSS , SDL_GAMEPAD_BUTTON_LABEL_CIRCLE , SDL_GAMEPAD_BUTTON_LABEL_SQUARE ,
SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE
}
enum SDL_GamepadType {
SDL_GAMEPAD_TYPE_UNKNOWN = 0 , SDL_GAMEPAD_TYPE_STANDARD , SDL_GAMEPAD_TYPE_XBOX360 , SDL_GAMEPAD_TYPE_XBOXONE ,
SDL_GAMEPAD_TYPE_PS3 , SDL_GAMEPAD_TYPE_PS4 , SDL_GAMEPAD_TYPE_PS5 , SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO ,
SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT , SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT , SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR , SDL_GAMEPAD_TYPE_GAMECUBE ,
SDL_GAMEPAD_TYPE_COUNT
}
Functions
SDL_DECLSPEC int SDLCALL SDL_AddGamepadMapping (const char *mapping)
SDL_DECLSPEC int SDLCALL SDL_AddGamepadMappingsFromFile (const char *file)
SDL_DECLSPEC int SDLCALL SDL_AddGamepadMappingsFromIO (SDL_IOStream *src, bool closeio)
SDL_DECLSPEC void SDLCALL SDL_CloseGamepad (SDL_Gamepad *gamepad)
SDL_DECLSPEC bool SDLCALL SDL_GamepadConnected (SDL_Gamepad *gamepad)
SDL_DECLSPEC bool SDLCALL SDL_GamepadEventsEnabled (void)
SDL_DECLSPEC bool SDLCALL SDL_GamepadHasAxis (SDL_Gamepad *gamepad, SDL_GamepadAxis axis)
SDL_DECLSPEC bool SDLCALL SDL_GamepadHasButton (SDL_Gamepad *gamepad, SDL_GamepadButton button)
SDL_DECLSPEC bool SDLCALL SDL_GamepadHasSensor (SDL_Gamepad *gamepad, SDL_SensorType type)
SDL_DECLSPEC bool SDLCALL SDL_GamepadSensorEnabled (SDL_Gamepad *gamepad, SDL_SensorType type)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadAppleSFSymbolsNameForAxis (SDL_Gamepad *gamepad, SDL_GamepadAxis axis)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadAppleSFSymbolsNameForButton (SDL_Gamepad *gamepad, SDL_GamepadButton button)
SDL_DECLSPEC Sint16 SDLCALL SDL_GetGamepadAxis (SDL_Gamepad *gamepad, SDL_GamepadAxis axis)
SDL_DECLSPEC SDL_GamepadAxis SDLCALL SDL_GetGamepadAxisFromString (const char *str)
SDL_DECLSPEC SDL_GamepadBinding **SDLCALL SDL_GetGamepadBindings (SDL_Gamepad *gamepad, int *count)
SDL_DECLSPEC bool SDLCALL SDL_GetGamepadButton (SDL_Gamepad *gamepad, SDL_GamepadButton button)
SDL_DECLSPEC SDL_GamepadButton SDLCALL SDL_GetGamepadButtonFromString (const char *str)
SDL_DECLSPEC SDL_GamepadButtonLabel SDLCALL SDL_GetGamepadButtonLabel (SDL_Gamepad *gamepad, SDL_GamepadButton button)
SDL_DECLSPEC SDL_GamepadButtonLabel SDLCALL SDL_GetGamepadButtonLabelForType (SDL_GamepadType type, SDL_GamepadButton button)
SDL_DECLSPEC SDL_JoystickConnectionState SDLCALL SDL_GetGamepadConnectionState (SDL_Gamepad *gamepad)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadFirmwareVersion (SDL_Gamepad *gamepad)
SDL_DECLSPEC SDL_Gamepad *SDLCALL SDL_GetGamepadFromID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_Gamepad *SDLCALL SDL_GetGamepadFromPlayerIndex (int player_index)
SDL_DECLSPEC SDL_GUID SDLCALL SDL_GetGamepadGUIDForID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_JoystickID SDLCALL SDL_GetGamepadID (SDL_Gamepad *gamepad)
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_GetGamepadJoystick (SDL_Gamepad *gamepad)
SDL_DECLSPEC char *SDLCALL SDL_GetGamepadMapping (SDL_Gamepad *gamepad)
SDL_DECLSPEC char *SDLCALL SDL_GetGamepadMappingForGUID (SDL_GUID guid)
SDL_DECLSPEC char *SDLCALL SDL_GetGamepadMappingForID (SDL_JoystickID instance_id)
SDL_DECLSPEC char **SDLCALL SDL_GetGamepadMappings (int *count)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadName (SDL_Gamepad *gamepad)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadNameForID (SDL_JoystickID instance_id)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadPath (SDL_Gamepad *gamepad)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadPathForID (SDL_JoystickID instance_id)
SDL_DECLSPEC int SDLCALL SDL_GetGamepadPlayerIndex (SDL_Gamepad *gamepad)
SDL_DECLSPEC int SDLCALL SDL_GetGamepadPlayerIndexForID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_PowerState SDLCALL SDL_GetGamepadPowerInfo (SDL_Gamepad *gamepad, int *percent)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProduct (SDL_Gamepad *gamepad)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProductForID (SDL_JoystickID instance_id)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProductVersion (SDL_Gamepad *gamepad)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProductVersionForID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetGamepadProperties (SDL_Gamepad *gamepad)
SDL_DECLSPEC SDL_JoystickID *SDLCALL SDL_GetGamepads (int *count)
SDL_DECLSPEC bool SDLCALL SDL_GetGamepadSensorData (SDL_Gamepad *gamepad, SDL_SensorType type, float *data, int num_values)
SDL_DECLSPEC float SDLCALL SDL_GetGamepadSensorDataRate (SDL_Gamepad *gamepad, SDL_SensorType type)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadSerial (SDL_Gamepad *gamepad)
SDL_DECLSPEC Uint64 SDLCALL SDL_GetGamepadSteamHandle (SDL_Gamepad *gamepad)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadStringForAxis (SDL_GamepadAxis axis)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadStringForButton (SDL_GamepadButton button)
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadStringForType (SDL_GamepadType type)
SDL_DECLSPEC bool SDLCALL SDL_GetGamepadTouchpadFinger (SDL_Gamepad *gamepad, int touchpad, int finger, bool *down, float *x, float *y, float *pressure)
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetGamepadType (SDL_Gamepad *gamepad)
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetGamepadTypeForID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetGamepadTypeFromString (const char *str)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadVendor (SDL_Gamepad *gamepad)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadVendorForID (SDL_JoystickID instance_id)
SDL_DECLSPEC int SDLCALL SDL_GetNumGamepadTouchpadFingers (SDL_Gamepad *gamepad, int touchpad)
SDL_DECLSPEC int SDLCALL SDL_GetNumGamepadTouchpads (SDL_Gamepad *gamepad)
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetRealGamepadType (SDL_Gamepad *gamepad)
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetRealGamepadTypeForID (SDL_JoystickID instance_id)
SDL_DECLSPEC bool SDLCALL SDL_HasGamepad (void)
SDL_DECLSPEC bool SDLCALL SDL_IsGamepad (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_Gamepad *SDLCALL SDL_OpenGamepad (SDL_JoystickID instance_id)
SDL_DECLSPEC bool SDLCALL SDL_ReloadGamepadMappings (void)
SDL_DECLSPEC bool SDLCALL SDL_RumbleGamepad (SDL_Gamepad *gamepad, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms)
SDL_DECLSPEC bool SDLCALL SDL_RumbleGamepadTriggers (SDL_Gamepad *gamepad, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms)
SDL_DECLSPEC bool SDLCALL SDL_SendGamepadEffect (SDL_Gamepad *gamepad, const void *data, int size)
SDL_DECLSPEC void SDLCALL SDL_SetGamepadEventsEnabled (bool enabled)
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadLED (SDL_Gamepad *gamepad, Uint8 red, Uint8 green, Uint8 blue)
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadMapping (SDL_JoystickID instance_id, const char *mapping)
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadPlayerIndex (SDL_Gamepad *gamepad, int player_index)
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadSensorEnabled (SDL_Gamepad *gamepad, SDL_SensorType type, bool enabled)
SDL_DECLSPEC void SDLCALL SDL_UpdateGamepads (void)
Macro Definition Documentation
SDL_PROP_GAMEPAD_CAP_MONO_LED_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_MONO_LED_BOOLEAN SDL_PROP_JOYSTICK_CAP_MONO_LED_BOOLEAN
SDL_PROP_GAMEPAD_CAP_PLAYER_LED_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_PLAYER_LED_BOOLEAN SDL_PROP_JOYSTICK_CAP_PLAYER_LED_BOOLEAN
SDL_PROP_GAMEPAD_CAP_RGB_LED_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_RGB_LED_BOOLEAN SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN
SDL_PROP_GAMEPAD_CAP_RUMBLE_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_RUMBLE_BOOLEAN SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN
SDL_PROP_GAMEPAD_CAP_TRIGGER_RUMBLE_BOOLEAN
#define SDL_PROP_GAMEPAD_CAP_TRIGGER_RUMBLE_BOOLEAN SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN
Typedef Documentation
SDL_Gamepad
typedef struct SDL_Gamepad SDL_Gamepad
CategoryGamepad
SDL provides a low-level joystick API, which just treats joysticks as an arbitrary pile of buttons, axes, and hat switches. If you're planning to write your own control configuration screen, this can give you a lot of flexibility, but that's a lot of work, and most things that we consider "joysticks" now are actually console-style gamepads. So SDL provides the gamepad API on top of the lower-level joystick functionality.
The difference between a joystick and a gamepad is that a gamepad tells you where a button or axis is on the device. You don't speak to gamepads in terms of arbitrary numbers like "button 3" or "axis 2" but in standard locations: the d-pad, the shoulder buttons, triggers, A/B/X/Y (or X/O/Square/Triangle, if you will).
One turns a joystick into a gamepad by providing a magic configuration string, which tells SDL the details of a specific device: when you see this specific hardware, if button 2 gets pressed, this is actually D-Pad Up, etc.
SDL has many popular controllers configured out of the box, and users can add their own controller details through an environment variable if it's otherwise unknown to SDL.
In order to use these functions, SDL_Init() must have been called with the SDL_INIT_GAMEPAD flag. This causes SDL to scan the system for gamepads, and load appropriate drivers.
If you would like to receive gamepad updates while the application is in the background, you should set the following hint before calling SDL_Init(): SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS
Gamepads support various optional features such as rumble, color LEDs, touchpad, gyro, etc. The support for these features varies depending on the controller and OS support available. You can check for LED and rumble capabilities at runtime by calling SDL_GetGamepadProperties() and checking the various capability properties. You can check for touchpad by calling SDL_GetNumGamepadTouchpads() and check for gyro and accelerometer by calling SDL_GamepadHasSensor().
By default SDL will try to use the most capable driver available, but you can tune which OS drivers to use with the various joystick hints in SDL_hints.h.
Your application should always support gamepad hotplugging. On some platforms like Xbox, Steam Deck, etc., this is a requirement for certification. On other platforms, like macOS and Windows when using Windows.Gaming.Input, controllers may not be available at startup and will come in at some point after you've started processing events. The structure used to identify an SDL gamepad
Since
This struct is available since SDL 3.2.0.
SDL_GamepadAxis
typedef enum SDL_GamepadAxis SDL_GamepadAxis
The list of axes available on a gamepad
Thumbstick axis values range from SDL_JOYSTICK_AXIS_MIN to SDL_JOYSTICK_AXIS_MAX, and are centered within ~8000 of zero, though advanced UI will allow users to set or autodetect the dead zone, which varies between gamepads.
Trigger axis values range from 0 (released) to SDL_JOYSTICK_AXIS_MAX (fully pressed) when reported by SDL_GetGamepadAxis(). Note that this is not the same range that will be reported by the lower-level SDL_GetJoystickAxis().
Since
This enum is available since SDL 3.2.0.
SDL_GamepadBinding
typedef struct SDL_GamepadBinding SDL_GamepadBinding
A mapping between one joystick input to a gamepad control.
A gamepad has a collection of several bindings, to say, for example, when joystick button number 5 is pressed, that should be treated like the gamepad's "start" button.
SDL has these bindings built-in for many popular controllers, and can add more with a simple text string. Those strings are parsed into a collection of these structs to make it easier to operate on the data.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GetGamepadBindings
SDL_GamepadBindingType
typedef enum SDL_GamepadBindingType SDL_GamepadBindingType
Types of gamepad control bindings.
A gamepad is a collection of bindings that map arbitrary joystick buttons, axes and hat switches to specific positions on a generic console-style gamepad. This enum is used as part of SDL_GamepadBinding to specify those mappings.
Since
This enum is available since SDL 3.2.0.
SDL_GamepadButton
typedef enum SDL_GamepadButton SDL_GamepadButton
The list of buttons available on a gamepad
For controllers that use a diamond pattern for the face buttons, the south/east/west/north buttons below correspond to the locations in the diamond pattern. For Xbox controllers, this would be A/B/X/Y, for Nintendo Switch controllers, this would be B/A/Y/X, for GameCube controllers this would be A/X/B/Y, for PlayStation controllers this would be Cross/Circle/Square/Triangle.
For controllers that don't use a diamond pattern for the face buttons, the south/east/west/north buttons indicate the buttons labeled A, B, C, D, or 1, 2, 3, 4, or for controllers that aren't labeled, they are the primary, secondary, etc. buttons.
The activate action is often the south button and the cancel action is often the east button, but in some regions this is reversed, so your game should allow remapping actions based on user preferences.
You can query the labels for the face buttons using SDL_GetGamepadButtonLabel()
Since
This enum is available since SDL 3.2.0.
SDL_GamepadButtonLabel
typedef enum SDL_GamepadButtonLabel SDL_GamepadButtonLabel
The set of gamepad button labels
This isn't a complete set, just the face buttons to make it easy to show button prompts.
For a complete set, you should look at the button and gamepad type and have a set of symbols that work well with your art style.
Since
This enum is available since SDL 3.2.0.
SDL_GamepadType
typedef enum SDL_GamepadType SDL_GamepadType
Standard gamepad types.
This type does not necessarily map to first-party controllers from Microsoft/Sony/Nintendo; in many cases, third-party controllers can report as these, either because they were designed for a specific console, or they simply most closely match that console's controllers (does it have A/B/X/Y buttons or X/O/Square/Triangle? Does it have a touchpad? etc).
Enumeration Type Documentation
SDL_GamepadAxis
enum SDL_GamepadAxis
The list of axes available on a gamepad
Thumbstick axis values range from SDL_JOYSTICK_AXIS_MIN to SDL_JOYSTICK_AXIS_MAX, and are centered within ~8000 of zero, though advanced UI will allow users to set or autodetect the dead zone, which varies between gamepads.
Trigger axis values range from 0 (released) to SDL_JOYSTICK_AXIS_MAX (fully pressed) when reported by SDL_GetGamepadAxis(). Note that this is not the same range that will be reported by the lower-level SDL_GetJoystickAxis().
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_GAMEPAD_AXIS_INVALID
SDL_GAMEPAD_AXIS_LEFTX
SDL_GAMEPAD_AXIS_LEFTY
SDL_GAMEPAD_AXIS_RIGHTX
SDL_GAMEPAD_AXIS_RIGHTY
SDL_GAMEPAD_AXIS_LEFT_TRIGGER
SDL_GAMEPAD_AXIS_RIGHT_TRIGGER
SDL_GAMEPAD_AXIS_COUNT
{
    SDL_GAMEPAD_AXIS_INVALID = -1,
    SDL_GAMEPAD_AXIS_LEFTX,
    SDL_GAMEPAD_AXIS_LEFTY,
    SDL_GAMEPAD_AXIS_RIGHTX,
    SDL_GAMEPAD_AXIS_RIGHTY,
    SDL_GAMEPAD_AXIS_LEFT_TRIGGER,
    SDL_GAMEPAD_AXIS_RIGHT_TRIGGER,
    SDL_GAMEPAD_AXIS_COUNT
} SDL_GamepadAxis;
SDL_GamepadBindingType
enum SDL_GamepadBindingType
Types of gamepad control bindings.
A gamepad is a collection of bindings that map arbitrary joystick buttons, axes and hat switches to specific positions on a generic console-style gamepad. This enum is used as part of SDL_GamepadBinding to specify those mappings.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_GAMEPAD_BINDTYPE_NONE
SDL_GAMEPAD_BINDTYPE_BUTTON
SDL_GAMEPAD_BINDTYPE_AXIS
SDL_GAMEPAD_BINDTYPE_HAT
{
    SDL_GAMEPAD_BINDTYPE_NONE = 0,
    SDL_GAMEPAD_BINDTYPE_BUTTON,
    SDL_GAMEPAD_BINDTYPE_AXIS,
    SDL_GAMEPAD_BINDTYPE_HAT
} SDL_GamepadBindingType;
SDL_GamepadButton
enum SDL_GamepadButton
The list of buttons available on a gamepad
For controllers that use a diamond pattern for the face buttons, the south/east/west/north buttons below correspond to the locations in the diamond pattern. For Xbox controllers, this would be A/B/X/Y, for Nintendo Switch controllers, this would be B/A/Y/X, for GameCube controllers this would be A/X/B/Y, for PlayStation controllers this would be Cross/Circle/Square/Triangle.
For controllers that don't use a diamond pattern for the face buttons, the south/east/west/north buttons indicate the buttons labeled A, B, C, D, or 1, 2, 3, 4, or for controllers that aren't labeled, they are the primary, secondary, etc. buttons.
The activate action is often the south button and the cancel action is often the east button, but in some regions this is reversed, so your game should allow remapping actions based on user preferences.
You can query the labels for the face buttons using SDL_GetGamepadButtonLabel()
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_GAMEPAD_BUTTON_INVALID
SDL_GAMEPAD_BUTTON_SOUTH
Bottom face button (e.g. Xbox A button)
SDL_GAMEPAD_BUTTON_EAST
Right face button (e.g. Xbox B button)
SDL_GAMEPAD_BUTTON_WEST
Left face button (e.g. Xbox X button)
SDL_GAMEPAD_BUTTON_NORTH
Top face button (e.g. Xbox Y button)
SDL_GAMEPAD_BUTTON_BACK
SDL_GAMEPAD_BUTTON_GUIDE
SDL_GAMEPAD_BUTTON_START
SDL_GAMEPAD_BUTTON_LEFT_STICK
SDL_GAMEPAD_BUTTON_RIGHT_STICK
SDL_GAMEPAD_BUTTON_LEFT_SHOULDER
SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER
SDL_GAMEPAD_BUTTON_DPAD_UP
SDL_GAMEPAD_BUTTON_DPAD_DOWN
SDL_GAMEPAD_BUTTON_DPAD_LEFT
SDL_GAMEPAD_BUTTON_DPAD_RIGHT
SDL_GAMEPAD_BUTTON_MISC1
Additional button (e.g. Xbox Series X share button, PS5 microphone button, Nintendo Switch Pro capture button, Amazon Luna microphone button, Google Stadia capture button)
SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1
Upper or primary paddle, under your right hand (e.g. Xbox Elite paddle P1)
SDL_GAMEPAD_BUTTON_LEFT_PADDLE1
Upper or primary paddle, under your left hand (e.g. Xbox Elite paddle P3)
SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2
Lower or secondary paddle, under your right hand (e.g. Xbox Elite paddle P2)
SDL_GAMEPAD_BUTTON_LEFT_PADDLE2
Lower or secondary paddle, under your left hand (e.g. Xbox Elite paddle P4)
SDL_GAMEPAD_BUTTON_TOUCHPAD
PS4/PS5 touchpad button
SDL_GAMEPAD_BUTTON_MISC2
Additional button
SDL_GAMEPAD_BUTTON_MISC3
Additional button
SDL_GAMEPAD_BUTTON_MISC4
Additional button
SDL_GAMEPAD_BUTTON_MISC5
Additional button
SDL_GAMEPAD_BUTTON_MISC6
Additional button
SDL_GAMEPAD_BUTTON_COUNT
{
    SDL_GAMEPAD_BUTTON_INVALID = -1,
    SDL_GAMEPAD_BUTTON_SOUTH,           /**< Bottom face button (e.g. Xbox A button) */
    SDL_GAMEPAD_BUTTON_EAST,            /**< Right face button (e.g. Xbox B button) */
    SDL_GAMEPAD_BUTTON_WEST,            /**< Left face button (e.g. Xbox X button) */
    SDL_GAMEPAD_BUTTON_NORTH,           /**< Top face button (e.g. Xbox Y button) */
    SDL_GAMEPAD_BUTTON_BACK,
    SDL_GAMEPAD_BUTTON_GUIDE,
    SDL_GAMEPAD_BUTTON_START,
    SDL_GAMEPAD_BUTTON_LEFT_STICK,
    SDL_GAMEPAD_BUTTON_RIGHT_STICK,
    SDL_GAMEPAD_BUTTON_LEFT_SHOULDER,
    SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER,
    SDL_GAMEPAD_BUTTON_DPAD_UP,
    SDL_GAMEPAD_BUTTON_DPAD_DOWN,
    SDL_GAMEPAD_BUTTON_DPAD_LEFT,
    SDL_GAMEPAD_BUTTON_DPAD_RIGHT,
    SDL_GAMEPAD_BUTTON_MISC1,           /**< Additional button (e.g. Xbox Series X share button, PS5 microphone button, Nintendo Switch Pro capture button, Amazon Luna microphone button, Google Stadia capture button) */
    SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1,   /**< Upper or primary paddle, under your right hand (e.g. Xbox Elite paddle P1) */
    SDL_GAMEPAD_BUTTON_LEFT_PADDLE1,    /**< Upper or primary paddle, under your left hand (e.g. Xbox Elite paddle P3) */
    SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2,   /**< Lower or secondary paddle, under your right hand (e.g. Xbox Elite paddle P2) */
    SDL_GAMEPAD_BUTTON_LEFT_PADDLE2,    /**< Lower or secondary paddle, under your left hand (e.g. Xbox Elite paddle P4) */
    SDL_GAMEPAD_BUTTON_TOUCHPAD,        /**< PS4/PS5 touchpad button */
    SDL_GAMEPAD_BUTTON_MISC2,           /**< Additional button */
    SDL_GAMEPAD_BUTTON_MISC3,           /**< Additional button */
    SDL_GAMEPAD_BUTTON_MISC4,           /**< Additional button */
    SDL_GAMEPAD_BUTTON_MISC5,           /**< Additional button */
    SDL_GAMEPAD_BUTTON_MISC6,           /**< Additional button */
    SDL_GAMEPAD_BUTTON_COUNT
} SDL_GamepadButton;
SDL_GamepadButtonLabel
enum SDL_GamepadButtonLabel
The set of gamepad button labels
This isn't a complete set, just the face buttons to make it easy to show button prompts.
For a complete set, you should look at the button and gamepad type and have a set of symbols that work well with your art style.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN
SDL_GAMEPAD_BUTTON_LABEL_A
SDL_GAMEPAD_BUTTON_LABEL_B
SDL_GAMEPAD_BUTTON_LABEL_X
SDL_GAMEPAD_BUTTON_LABEL_Y
SDL_GAMEPAD_BUTTON_LABEL_CROSS
SDL_GAMEPAD_BUTTON_LABEL_CIRCLE
SDL_GAMEPAD_BUTTON_LABEL_SQUARE
SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE
{
    SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN,
    SDL_GAMEPAD_BUTTON_LABEL_A,
    SDL_GAMEPAD_BUTTON_LABEL_B,
    SDL_GAMEPAD_BUTTON_LABEL_X,
    SDL_GAMEPAD_BUTTON_LABEL_Y,
    SDL_GAMEPAD_BUTTON_LABEL_CROSS,
    SDL_GAMEPAD_BUTTON_LABEL_CIRCLE,
    SDL_GAMEPAD_BUTTON_LABEL_SQUARE,
    SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE
} SDL_GamepadButtonLabel;
SDL_GamepadType
enum SDL_GamepadType
Standard gamepad types.
This type does not necessarily map to first-party controllers from Microsoft/Sony/Nintendo; in many cases, third-party controllers can report as these, either because they were designed for a specific console, or they simply most closely match that console's controllers (does it have A/B/X/Y buttons or X/O/Square/Triangle? Does it have a touchpad? etc).
Enumerator
SDL_GAMEPAD_TYPE_UNKNOWN
SDL_GAMEPAD_TYPE_STANDARD
SDL_GAMEPAD_TYPE_XBOX360
SDL_GAMEPAD_TYPE_XBOXONE
SDL_GAMEPAD_TYPE_PS3
SDL_GAMEPAD_TYPE_PS4
SDL_GAMEPAD_TYPE_PS5
SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO
SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT
SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT
SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR
SDL_GAMEPAD_TYPE_GAMECUBE
SDL_GAMEPAD_TYPE_COUNT
{
    SDL_GAMEPAD_TYPE_UNKNOWN = 0,
    SDL_GAMEPAD_TYPE_STANDARD,
    SDL_GAMEPAD_TYPE_XBOX360,
    SDL_GAMEPAD_TYPE_XBOXONE,
    SDL_GAMEPAD_TYPE_PS3,
    SDL_GAMEPAD_TYPE_PS4,
    SDL_GAMEPAD_TYPE_PS5,
    SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO,
    SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT,
    SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT,
    SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR,
    SDL_GAMEPAD_TYPE_GAMECUBE,
    SDL_GAMEPAD_TYPE_COUNT
} SDL_GamepadType;
Function Documentation
SDL_AddGamepadMapping()
SDL_DECLSPEC int SDLCALL SDL_AddGamepadMapping (const char * mapping) extern
Add support for gamepads that SDL is unaware of or change the binding of an existing gamepad.
The mapping string has the format "GUID,name,mapping", where GUID is the string value from SDL_GUIDToString(), name is the human readable string for the device and mappings are gamepad mappings to joystick ones. Under Windows there is a reserved GUID of "xinput" that covers all XInput devices. The mapping format for joystick is:
bX: a joystick button, index X
hX.Y: hat X with value Y
aX: axis X of the joystick
Buttons can be used as a gamepad axes and vice versa.
If a device with this GUID is already plugged in, SDL will generate an SDL_EVENT_GAMEPAD_ADDED event.
This string shows an example of a valid mapping for a gamepad:
"341a3608000000000000504944564944,Afterglow PS3 Controller,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b8,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7"
Parameters
mapping the mapping string.
Returns
1 if a new mapping is added, 0 if an existing mapping is updated, -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMappingsFromFile
SDL_AddGamepadMappingsFromIO
SDL_GetGamepadMapping
SDL_GetGamepadMappingForGUID
SDL_HINT_GAMECONTROLLERCONFIG
SDL_HINT_GAMECONTROLLERCONFIG_FILE
SDL_EVENT_GAMEPAD_ADDED
{
    int result;
    SDL_LockJoysticks();
    {
        result = SDL_PrivateAddGamepadMapping(mapping, SDL_GAMEPAD_MAPPING_PRIORITY_API);
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GAMEPAD_MAPPING_PRIORITY_API, SDL_LockJoysticks(), SDL_PrivateAddGamepadMapping(), and SDL_UnlockJoysticks().
Referenced by SDL_AddGamepadMappingsFromIO().
SDL_AddGamepadMappingsFromFile()
SDL_DECLSPEC int SDLCALL SDL_AddGamepadMappingsFromFile (const char * file) extern
Load a set of gamepad mappings from a file.
You can call this function several times, if needed, to load different database files.
If a new mapping is loaded for an already known gamepad GUID, the later version will overwrite the one currently loaded.
Any new mappings for already plugged in controllers will generate SDL_EVENT_GAMEPAD_ADDED events.
Mappings not belonging to the current platform or with no platform field specified will be ignored (i.e. mappings for Linux will be ignored in Windows, etc).
Parameters
file the mappings file to load.
Returns
the number of mappings added or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_AddGamepadMappingsFromIO
SDL_GetGamepadMapping
SDL_GetGamepadMappingForGUID
SDL_HINT_GAMECONTROLLERCONFIG
SDL_HINT_GAMECONTROLLERCONFIG_FILE
SDL_EVENT_GAMEPAD_ADDED
{
    return SDL_AddGamepadMappingsFromIO(SDL_IOFromFile(file, "rb"), true);
}
References SDL_AddGamepadMappingsFromIO(), and SDL_IOFromFile().
Referenced by SDL_InitGamepadMappings().
SDL_AddGamepadMappingsFromIO()
SDL_DECLSPEC int SDLCALL SDL_AddGamepadMappingsFromIO (SDL_IOStream * src, bool closeio) extern
Load a set of gamepad mappings from an SDL_IOStream.
You can call this function several times, if needed, to load different database files.
If a new mapping is loaded for an already known gamepad GUID, the later version will overwrite the one currently loaded.
Any new mappings for already plugged in controllers will generate SDL_EVENT_GAMEPAD_ADDED events.
Mappings not belonging to the current platform or with no platform field specified will be ignored (i.e. mappings for Linux will be ignored in Windows, etc).
This function will load the text database entirely in memory before processing it, so take this into consideration if you are in a memory constrained environment.
Parameters
src the data stream for the mappings to be added.
closeio if true, calls SDL_CloseIO() on src before returning, even in the case of an error.
Returns
the number of mappings added or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_AddGamepadMappingsFromFile
SDL_GetGamepadMapping
SDL_GetGamepadMappingForGUID
SDL_HINT_GAMECONTROLLERCONFIG
SDL_HINT_GAMECONTROLLERCONFIG_FILE
SDL_EVENT_GAMEPAD_ADDED
{
    const char *platform = SDL_GetPlatform();
    int gamepads = 0;
    char *buf, *line, *line_end, *tmp, *comma, line_platform[64];
    size_t db_size;
    size_t platform_len;
    buf = (char *)SDL_LoadFile_IO(src, &db_size, closeio);
    if (!buf) {
        SDL_SetError("Could not allocate space to read DB into memory");
        return -1;
    }
    line = buf;
    SDL_LockJoysticks();
    PushMappingChangeTracking();
    while (line < buf + db_size) {
        line_end = SDL_strchr(line, '\n');
        if (line_end) {
            *line_end = '\0';
        } else {
            line_end = buf + db_size;
        }
        // Extract and verify the platform
        tmp = SDL_strstr(line, SDL_GAMEPAD_PLATFORM_FIELD);
        if (tmp) {
            tmp += SDL_GAMEPAD_PLATFORM_FIELD_SIZE;
            comma = SDL_strchr(tmp, ',');
            if (comma) {
                platform_len = comma - tmp + 1;
                if (platform_len + 1 < SDL_arraysize(line_platform)) {
                    SDL_strlcpy(line_platform, tmp, platform_len);
                    if (SDL_strncasecmp(line_platform, platform, platform_len) == 0 &&
                        SDL_AddGamepadMapping(line) > 0) {
                        gamepads++;
                    }
                }
            }
        }
        line = line_end + 1;
    }
    PopMappingChangeTracking();
    SDL_UnlockJoysticks();
    SDL_free(buf);
    return gamepads;
}
References PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_AddGamepadMapping(), SDL_arraysize, SDL_free(), SDL_GAMEPAD_PLATFORM_FIELD, SDL_GAMEPAD_PLATFORM_FIELD_SIZE, SDL_GetPlatform(), SDL_LoadFile_IO(), SDL_LockJoysticks(), SDL_SetError(), SDL_strchr(), SDL_strlcpy(), SDL_strncasecmp(), SDL_strstr(), and SDL_UnlockJoysticks().
Referenced by SDL_AddGamepadMappingsFromFile().
SDL_CloseGamepad()
SDL_DECLSPEC void SDLCALL SDL_CloseGamepad (SDL_Gamepad * gamepad) extern
Close a gamepad previously opened with SDL_OpenGamepad().
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenGamepad
{
    SDL_Gamepad *gamepadlist, *gamepadlistprev;
    SDL_LockJoysticks();
    if (!SDL_ObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD)) {
        SDL_UnlockJoysticks();
        return;
    }
    // First decrement ref count
    if (--gamepad->ref_count > 0) {
        SDL_UnlockJoysticks();
        return;
    }
    SDL_CloseJoystick(gamepad->joystick);
    gamepadlist = SDL_gamepads;
    gamepadlistprev = NULL;
    while (gamepadlist) {
        if (gamepad == gamepadlist) {
            if (gamepadlistprev) {
                // unlink this entry
                gamepadlistprev->next = gamepadlist->next;
            } else {
                SDL_gamepads = gamepad->next;
            }
            break;
        }
        gamepadlistprev = gamepadlist;
        gamepadlist = gamepadlist->next;
    }
    SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
    SDL_free(gamepad->bindings);
    SDL_free(gamepad->last_match_axis);
    SDL_free(gamepad->last_hat_mask);
    SDL_free(gamepad);
    SDL_UnlockJoysticks();
}
References NULL, SDL_CloseJoystick(), SDL_free(), SDL_LockJoysticks(), SDL_OBJECT_TYPE_GAMEPAD, SDL_ObjectValid(), SDL_SetObjectValid(), and SDL_UnlockJoysticks().
Referenced by SDL_QuitGamepads().
SDL_GamepadConnected()
SDL_DECLSPEC bool SDLCALL SDL_GamepadConnected (SDL_Gamepad * gamepad) extern
Check if a gamepad has been opened and is currently connected.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
true if the gamepad has been opened and is currently connected, or false if not.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_JoystickConnected(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_JoystickConnected().
SDL_GamepadEventsEnabled()
SDL_DECLSPEC bool SDLCALL SDL_GamepadEventsEnabled (void) extern
Query the state of gamepad event processing.
If gamepad events are disabled, you must call SDL_UpdateGamepads() yourself and check the state of the gamepad when you want gamepad information.
Returns
true if gamepad events are being processed, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetGamepadEventsEnabled
{
    bool enabled = false;
    unsigned int i;
    for (i = 0; i < SDL_arraysize(SDL_gamepad_event_list); ++i) {
        enabled = SDL_EventEnabled(SDL_gamepad_event_list[i]);
        if (enabled) {
            break;
        }
    }
    return enabled;
}
References SDL_arraysize, SDL_EventEnabled(), and SDL_gamepad_event_list.
SDL_GamepadHasAxis()
SDL_DECLSPEC bool SDLCALL SDL_GamepadHasAxis (SDL_Gamepad * gamepad, SDL_GamepadAxis axis) extern
Query whether a gamepad has a given axis.
This merely reports whether the gamepad's mapping defined this axis, as that is all the information SDL has about the physical device.
Parameters
gamepad a gamepad.
axis an axis enum value (an SDL_GamepadAxis value).
Returns
true if the gamepad has this axis, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasButton
SDL_GetGamepadAxis
Return whether a gamepad has a given axis
{
    bool result = false;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, false);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_AXIS && binding->output.axis.axis == axis) {
                result = true;
                break;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::axis, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GamepadHasButton()
SDL_DECLSPEC bool SDLCALL SDL_GamepadHasButton (SDL_Gamepad * gamepad, SDL_GamepadButton button) extern
Query whether a gamepad has a given button.
This merely reports whether the gamepad's mapping defined this button, as that is all the information SDL has about the physical device.
Parameters
gamepad a gamepad.
button a button enum value (an SDL_GamepadButton value).
Returns
true if the gamepad has this button, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasAxis
Return whether a gamepad has a given button
{
    bool result = false;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, false);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON && binding->output.button == button) {
                result = true;
                break;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::button, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GamepadHasSensor()
SDL_DECLSPEC bool SDLCALL SDL_GamepadHasSensor (SDL_Gamepad * gamepad, SDL_SensorType type) extern
Return whether a gamepad has a particular sensor.
Parameters
gamepad the gamepad to query.
type the type of sensor to query.
Returns
true if the sensor exists, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadSensorData
SDL_GetGamepadSensorDataRate
SDL_SetGamepadSensorEnabled
Return whether a gamepad has a particular sensor.
{
    bool result = false;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                if (joystick->sensors[i].type == type) {
                    result = true;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GamepadSensorEnabled()
SDL_DECLSPEC bool SDLCALL SDL_GamepadSensorEnabled (SDL_Gamepad * gamepad, SDL_SensorType type) extern
Query whether sensor data reporting is enabled for a gamepad.
Parameters
gamepad the gamepad to query.
type the type of sensor to query.
Returns
true if the sensor is enabled, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetGamepadSensorEnabled
{
    bool result = false;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                if (joystick->sensors[i].type == type) {
                    result = joystick->sensors[i].enabled;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadAppleSFSymbolsNameForAxis()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadAppleSFSymbolsNameForAxis (SDL_Gamepad * gamepad, SDL_GamepadAxis axis) extern
Return the sfSymbolsName for a given axis on a gamepad on Apple platforms.
Parameters
gamepad the gamepad to query.
axis an axis on the gamepad.
Returns
the sfSymbolsName or NULL if the name can't be found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadAppleSFSymbolsNameForButton
{
    const char *result = NULL;
#ifdef SDL_JOYSTICK_MFI
    const char *IOS_GetAppleSFSymbolsNameForAxis(SDL_Gamepad *gamepad, SDL_GamepadAxis axis);
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        result = IOS_GetAppleSFSymbolsNameForAxis(gamepad, axis);
    }
    SDL_UnlockJoysticks();
#endif
    return result;
}
References CHECK_GAMEPAD_MAGIC, IOS_GetAppleSFSymbolsNameForAxis(), NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadAppleSFSymbolsNameForButton()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadAppleSFSymbolsNameForButton (SDL_Gamepad * gamepad, SDL_GamepadButton button) extern
Return the sfSymbolsName for a given button on a gamepad on Apple platforms.
Parameters
gamepad the gamepad to query.
button a button on the gamepad.
Returns
the sfSymbolsName or NULL if the name can't be found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadAppleSFSymbolsNameForAxis
{
    const char *result = NULL;
#ifdef SDL_JOYSTICK_MFI
    const char *IOS_GetAppleSFSymbolsNameForButton(SDL_Gamepad *gamepad, SDL_GamepadButton button);
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        result = IOS_GetAppleSFSymbolsNameForButton(gamepad, button);
    }
    SDL_UnlockJoysticks();
#endif
    return result;
}
References CHECK_GAMEPAD_MAGIC, IOS_GetAppleSFSymbolsNameForButton(), NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadAxis()
SDL_DECLSPEC Sint16 SDLCALL SDL_GetGamepadAxis (SDL_Gamepad * gamepad, SDL_GamepadAxis axis) extern
Get the current state of an axis control on a gamepad.
The axis indices start at index 0.
For thumbsticks, the state is a value ranging from -32768 (up/left) to 32767 (down/right).
Triggers range from 0 when released to 32767 when fully pressed, and never return a negative value. Note that this differs from the value reported by the lower-level SDL_GetJoystickAxis(), which normally uses the full range.
Note that for invalid gamepads or axes, this will return 0. Zero is also a valid value in normal operation; usually it means a centered axis.
Parameters
gamepad a gamepad.
axis an axis index (one of the SDL_GamepadAxis values).
Returns
axis state.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasAxis
SDL_GetGamepadButton
{
    Sint16 result = 0;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, 0);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_AXIS && binding->output.axis.axis == axis) {
                int value = 0;
                bool valid_input_range;
                bool valid_output_range;
                if (binding->input_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
                    value = SDL_GetJoystickAxis(gamepad->joystick, binding->input.axis.axis);
                    if (binding->input.axis.axis_min < binding->input.axis.axis_max) {
                        valid_input_range = (value >= binding->input.axis.axis_min && value <= binding->input.axis.axis_max);
                    } else {
                        valid_input_range = (value >= binding->input.axis.axis_max && value <= binding->input.axis.axis_min);
                    }
                    if (valid_input_range) {
                        if (binding->input.axis.axis_min != binding->output.axis.axis_min || binding->input.axis.axis_max != binding->output.axis.axis_max) {
                            float normalized_value = (float)(value - binding->input.axis.axis_min) / (binding->input.axis.axis_max - binding->input.axis.axis_min);
                            value = binding->output.axis.axis_min + (int)(normalized_value * (binding->output.axis.axis_max - binding->output.axis.axis_min));
                        }
                    } else {
                        value = 0;
                    }
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON) {
                    if (SDL_GetJoystickButton(gamepad->joystick, binding->input.button)) {
                        value = binding->output.axis.axis_max;
                    }
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_HAT) {
                    int hat_mask = SDL_GetJoystickHat(gamepad->joystick, binding->input.hat.hat);
                    if (hat_mask & binding->input.hat.hat_mask) {
                        value = binding->output.axis.axis_max;
                    }
                }
                if (binding->output.axis.axis_min < binding->output.axis.axis_max) {
                    valid_output_range = (value >= binding->output.axis.axis_min && value <= binding->output.axis.axis_max);
                } else {
                    valid_output_range = (value >= binding->output.axis.axis_max && value <= binding->output.axis.axis_min);
                }
                // If the value is zero, there might be another binding that makes it non-zero
                if (value != 0 && valid_output_range) {
                    result = (Sint16)value;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::hat, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_GAMEPAD_BINDTYPE_HAT, SDL_GetJoystickAxis(), SDL_GetJoystickButton(), SDL_GetJoystickHat(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by RecenterGamepad().
SDL_GetGamepadAxisFromString()
SDL_DECLSPEC SDL_GamepadAxis SDLCALL SDL_GetGamepadAxisFromString (const char * str) extern
Convert a string into SDL_GamepadAxis enum.
This function is called internally to translate SDL_Gamepad mapping strings for the underlying joystick device into the consistent SDL_Gamepad mapping. You do not normally need to call this function unless you are parsing SDL_Gamepad mappings in your own code.
Note specially that "righttrigger" and "lefttrigger" map to SDL_GAMEPAD_AXIS_RIGHT_TRIGGER and SDL_GAMEPAD_AXIS_LEFT_TRIGGER, respectively.
Parameters
str string representing a SDL_Gamepad axis.
Returns
the SDL_GamepadAxis enum corresponding to the input string, or SDL_GAMEPAD_AXIS_INVALID if no match was found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadStringForAxis
{
    int i;
    if (!str || str[0] == '\0') {
        return SDL_GAMEPAD_AXIS_INVALID;
    }
    if (*str == '+' || *str == '-') {
        ++str;
    }
    for (i = 0; i < SDL_arraysize(map_StringForGamepadAxis); ++i) {
        if (SDL_strcasecmp(str, map_StringForGamepadAxis[i]) == 0) {
            return (SDL_GamepadAxis)i;
        }
    }
    return SDL_GAMEPAD_AXIS_INVALID;
}
References map_StringForGamepadAxis, SDL_arraysize, SDL_GAMEPAD_AXIS_INVALID, and SDL_strcasecmp().
Referenced by SDL_PrivateParseGamepadElement().
SDL_GetGamepadBindings()
SDL_DECLSPEC SDL_GamepadBinding **SDLCALL SDL_GetGamepadBindings (SDL_Gamepad * gamepad, int * count) extern
Get the SDL joystick layer bindings for a gamepad.
Parameters
gamepad a gamepad.
count a pointer filled in with the number of bindings returned.
Returns
a NULL terminated array of pointers to bindings or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    SDL_GamepadBinding **bindings = NULL;
    if (count) {
        *count = 0;
    }
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        size_t pointers_size = ((gamepad->num_bindings + 1) * sizeof(SDL_GamepadBinding *));
        size_t elements_size = (gamepad->num_bindings * sizeof(SDL_GamepadBinding));
        bindings = (SDL_GamepadBinding **)SDL_malloc(pointers_size + elements_size);
        if (bindings) {
            SDL_GamepadBinding *binding = (SDL_GamepadBinding *)((Uint8 *)bindings + pointers_size);
            int i;
            for (i = 0; i < gamepad->num_bindings; ++i, ++binding) {
                bindings[i] = binding;
                SDL_copyp(binding, &gamepad->bindings[i]);
            }
            bindings[i] = NULL;
            if (count) {
                *count = gamepad->num_bindings;
            }
        }
    }
    SDL_UnlockJoysticks();
    return bindings;
}
References CHECK_GAMEPAD_MAGIC, count, NULL, SDL_copyp, SDL_LockJoysticks(), SDL_malloc(), and SDL_UnlockJoysticks().
SDL_GetGamepadButton()
SDL_DECLSPEC bool SDLCALL SDL_GetGamepadButton (SDL_Gamepad * gamepad, SDL_GamepadButton button) extern
Get the current state of a button on a gamepad.
Parameters
gamepad a gamepad.
button a button index (one of the SDL_GamepadButton values).
Returns
true if the button is pressed, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasButton
SDL_GetGamepadAxis
{
    bool result = false;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, false);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON && binding->output.button == button) {
                if (binding->input_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
                    bool valid_input_range;
                    int value = SDL_GetJoystickAxis(gamepad->joystick, binding->input.axis.axis);
                    int threshold = binding->input.axis.axis_min + (binding->input.axis.axis_max - binding->input.axis.axis_min) / 2;
                    if (binding->input.axis.axis_min < binding->input.axis.axis_max) {
                        valid_input_range = (value >= binding->input.axis.axis_min && value <= binding->input.axis.axis_max);
                        if (valid_input_range) {
                            result |= (value >= threshold);
                        }
                    } else {
                        valid_input_range = (value >= binding->input.axis.axis_max && value <= binding->input.axis.axis_min);
                        if (valid_input_range) {
                            result |= (value <= threshold);
                        }
                    }
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON) {
                    result |= SDL_GetJoystickButton(gamepad->joystick, binding->input.button);
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_HAT) {
                    int hat_mask = SDL_GetJoystickHat(gamepad->joystick, binding->input.hat.hat);
                    result |= ((hat_mask & binding->input.hat.hat_mask) != 0);
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::hat, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_GAMEPAD_BINDTYPE_HAT, SDL_GetJoystickAxis(), SDL_GetJoystickButton(), SDL_GetJoystickHat(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by RecenterGamepad().
SDL_GetGamepadButtonFromString()
SDL_DECLSPEC SDL_GamepadButton SDLCALL SDL_GetGamepadButtonFromString (const char * str) extern
Convert a string into an SDL_GamepadButton enum.
This function is called internally to translate SDL_Gamepad mapping strings for the underlying joystick device into the consistent SDL_Gamepad mapping. You do not normally need to call this function unless you are parsing SDL_Gamepad mappings in your own code.
Parameters
str string representing a SDL_Gamepad axis.
Returns
the SDL_GamepadButton enum corresponding to the input string, or SDL_GAMEPAD_BUTTON_INVALID if no match was found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadStringForButton
{
    return SDL_PrivateGetGamepadButtonFromString(str, false, false);
}
References SDL_PrivateGetGamepadButtonFromString().
SDL_GetGamepadButtonLabel()
SDL_DECLSPEC SDL_GamepadButtonLabel SDLCALL SDL_GetGamepadButtonLabel (SDL_Gamepad * gamepad, SDL_GamepadButton button) extern
Get the label of a button on a gamepad.
Parameters
gamepad a gamepad.
button a button index (one of the SDL_GamepadButton values).
Returns
the SDL_GamepadButtonLabel enum corresponding to the button label.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadButtonLabelForType
Get the label of a button on a gamepad.
{
    SDL_GamepadFaceStyle face_style;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN);
        face_style = gamepad->face_style;
    }
    SDL_UnlockJoysticks();
    return SDL_GetGamepadButtonLabelForFaceStyle(face_style, button);
}
References CHECK_GAMEPAD_MAGIC, SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN, SDL_GetGamepadButtonLabelForFaceStyle(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadButtonLabelForType()
SDL_DECLSPEC SDL_GamepadButtonLabel SDLCALL SDL_GetGamepadButtonLabelForType (SDL_GamepadType type, SDL_GamepadButton button) extern
Get the label of a button on a gamepad.
Parameters
type the type of gamepad to check.
button a button index (one of the SDL_GamepadButton values).
Returns
the SDL_GamepadButtonLabel enum corresponding to the button label.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadButtonLabel
Get the label of a button on a gamepad.
{
    return SDL_GetGamepadButtonLabelForFaceStyle(SDL_GetGamepadFaceStyleForGamepadType(type), button);
}
References SDL_GetGamepadButtonLabelForFaceStyle(), and SDL_GetGamepadFaceStyleForGamepadType().
SDL_GetGamepadConnectionState()
SDL_DECLSPEC SDL_JoystickConnectionState SDLCALL SDL_GetGamepadConnectionState (SDL_Gamepad * gamepad) extern
Get the connection state of a gamepad.
Parameters
gamepad the gamepad object to query.
Returns
the connection state on success or SDL_JOYSTICK_CONNECTION_INVALID on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return SDL_JOYSTICK_CONNECTION_INVALID;
    }
    return SDL_GetJoystickConnectionState(joystick);
}
References SDL_GetGamepadJoystick(), SDL_GetJoystickConnectionState(), and SDL_JOYSTICK_CONNECTION_INVALID.
SDL_GetGamepadFirmwareVersion()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadFirmwareVersion (SDL_Gamepad * gamepad) extern
Get the firmware version of an opened gamepad, if available.
If the firmware version isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the gamepad firmware version, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickFirmwareVersion(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickFirmwareVersion().
SDL_GetGamepadFromID()
SDL_DECLSPEC SDL_Gamepad *SDLCALL SDL_GetGamepadFromID (SDL_JoystickID instance_id) extern
Get the SDL_Gamepad associated with a joystick instance ID, if it has been opened.
Parameters
instance_id the joystick instance ID of the gamepad.
Returns
an SDL_Gamepad on success or NULL on failure or if it hasn't been opened yet; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    gamepad = SDL_gamepads;
    while (gamepad) {
        if (gamepad->joystick->instance_id == joyid) {
            SDL_UnlockJoysticks();
            return gamepad;
        }
        gamepad = gamepad->next;
    }
    SDL_UnlockJoysticks();
    return NULL;
}
References NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by PopMappingChangeTracking(), and SDL_GetGamepadFromPlayerIndex().
SDL_GetGamepadFromPlayerIndex()
SDL_DECLSPEC SDL_Gamepad *SDLCALL SDL_GetGamepadFromPlayerIndex (int player_index) extern
Get the SDL_Gamepad associated with a player index.
Parameters
player_index the player index, which different from the instance ID.
Returns
the SDL_Gamepad associated with a player index.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPlayerIndex
SDL_SetGamepadPlayerIndex
Return the SDL_Gamepad associated with a player index.
{
    SDL_Gamepad *result = NULL;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetJoystickFromPlayerIndex(player_index);
        if (joystick) {
            result = SDL_GetGamepadFromID(joystick->instance_id);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_GetGamepadFromID(), SDL_GetJoystickFromPlayerIndex(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadGUIDForID()
SDL_DECLSPEC SDL_GUID SDLCALL SDL_GetGamepadGUIDForID (SDL_JoystickID instance_id) extern
Get the implementation-dependent GUID of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the GUID of the selected gamepad. If called on an invalid index, this function returns a zero GUID.
Since
This function is available since SDL 3.2.0.
See also
SDL_GUIDToString
SDL_GetGamepads
{
    return SDL_GetJoystickGUIDForID(instance_id);
}
References SDL_GetJoystickGUIDForID().
SDL_GetGamepadID()
SDL_DECLSPEC SDL_JoystickID SDLCALL SDL_GetGamepadID (SDL_Gamepad * gamepad) extern
Get the instance ID of an opened gamepad.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
the instance ID of the specified gamepad on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickID(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickID().
SDL_GetGamepadJoystick()
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_GetGamepadJoystick (SDL_Gamepad * gamepad) extern
Get the underlying joystick from a gamepad.
This function will give you a SDL_Joystick object, which allows you to use the SDL_Joystick functions with a SDL_Gamepad object. This would be useful for getting a joystick's position at any given time, even if it hasn't moved (moving it would produce an event, which would have the axis' value).
The pointer returned is owned by the SDL_Gamepad. You should not call SDL_CloseJoystick() on it, for example, since doing so will likely cause SDL to crash.
Parameters
gamepad the gamepad object that you want to get a joystick from.
Returns
an SDL_Joystick object, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        joystick = gamepad->joystick;
    }
    SDL_UnlockJoysticks();
    return joystick;
}
References CHECK_GAMEPAD_MAGIC, NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by IOS_GetAppleSFSymbolsNameForAxis(), IOS_GetAppleSFSymbolsNameForButton(), SDL_GamepadConnected(), SDL_GamepadHasSensor(), SDL_GamepadSensorEnabled(), SDL_GetGamepadConnectionState(), SDL_GetGamepadFirmwareVersion(), SDL_GetGamepadID(), SDL_GetGamepadPath(), SDL_GetGamepadPlayerIndex(), SDL_GetGamepadPowerInfo(), SDL_GetGamepadProduct(), SDL_GetGamepadProductVersion(), SDL_GetGamepadSensorData(), SDL_GetGamepadSensorDataRate(), SDL_GetGamepadSerial(), SDL_GetGamepadTouchpadFinger(), SDL_GetGamepadVendor(), SDL_GetNumGamepadTouchpadFingers(), SDL_GetNumGamepadTouchpads(), SDL_GetRealGamepadType(), SDL_RumbleGamepad(), SDL_RumbleGamepadTriggers(), SDL_SendGamepadEffect(), SDL_SetGamepadLED(), SDL_SetGamepadPlayerIndex(), and SDL_SetGamepadSensorEnabled().
SDL_GetGamepadMapping()
SDL_DECLSPEC char *SDLCALL SDL_GetGamepadMapping (SDL_Gamepad * gamepad) extern
Get the current mapping of a gamepad.
Details about mappings are discussed with SDL_AddGamepadMapping().
Parameters
gamepad the gamepad you want to get the current mapping for.
Returns
a string that has the gamepad's mapping or NULL if no mapping is available; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_GetGamepadMappingForID
SDL_GetGamepadMappingForGUID
SDL_SetGamepadMapping
{
    char *result;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        result = CreateMappingString(gamepad->mapping, gamepad->joystick->guid);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_GAMEPAD_MAGIC, CreateMappingString(), NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadMappingForGUID()
SDL_DECLSPEC char *SDLCALL SDL_GetGamepadMappingForGUID (SDL_GUID guid) extern
Get the gamepad mapping string for a given GUID.
Parameters
guid a structure containing the GUID for which a mapping is desired.
Returns
a mapping string or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickGUIDForID
SDL_GetJoystickGUID
{
    char *result;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMappingForGUID(guid, false);
        if (mapping) {
            result = CreateMappingString(mapping, guid);
        } else {
            SDL_SetError("Mapping not available");
            result = NULL;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CreateMappingString(), NULL, SDL_LockJoysticks(), SDL_PrivateGetGamepadMappingForGUID(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_GetGamepadMappingForID()
SDL_DECLSPEC char *SDLCALL SDL_GetGamepadMappingForID (SDL_JoystickID instance_id) extern
Get the mapping of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the mapping string. Returns NULL if no mapping is available. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepads
SDL_GetGamepadMapping
{
    char *result = NULL;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMapping(instance_id, true);
        if (mapping) {
            char pchGUID[33];
            SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
            SDL_GUIDToString(guid, pchGUID, sizeof(pchGUID));
            SDL_asprintf(&result, "%s,%s,%s", pchGUID, mapping->name, mapping->mapping);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_asprintf(), SDL_GetJoystickGUIDForID(), SDL_GUIDToString(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), and SDL_UnlockJoysticks().
SDL_GetGamepadMappings()
SDL_DECLSPEC char **SDLCALL SDL_GetGamepadMappings (int * count) extern
Get the current gamepad mappings.
Parameters
count a pointer filled in with the number of mappings returned, can be NULL.
Returns
an array of the mapping strings, NULL-terminated, or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    int num_mappings = 0;
    char **result = NULL;
    char **mappings = NULL;
    if (count) {
        *count = 0;
    }
    SDL_LockJoysticks();
    for (GamepadMapping_t *mapping = s_pSupportedGamepads; mapping; mapping = mapping->next) {
        if (SDL_memcmp(&mapping->guid, &s_zeroGUID, sizeof(mapping->guid)) == 0) {
            continue;
        }
        num_mappings++;
    }
    size_t final_allocation = sizeof (char *);  // for the NULL terminator element.
    bool failed = false;
    mappings = (char **) SDL_calloc(num_mappings + 1, sizeof (char *));
    if (!mappings) {
        failed = true;
    } else {
        int i = 0;
        for (GamepadMapping_t *mapping = s_pSupportedGamepads; mapping; mapping = mapping->next) {
            if (SDL_memcmp(&mapping->guid, &s_zeroGUID, sizeof(mapping->guid)) == 0) {
                continue;
            }
            char *mappingstr = CreateMappingString(mapping, mapping->guid);
            if (!mappingstr) {
                failed = true;
                break;  // error string is already set.
            }
            SDL_assert(i < num_mappings);
            mappings[i++] = mappingstr;
            final_allocation += SDL_strlen(mappingstr) + 1 + sizeof (char *);
        }
    }
    SDL_UnlockJoysticks();
    if (!failed) {
        result = (char **) SDL_malloc(final_allocation);
        if (result) {
            final_allocation -= (sizeof (char *) * num_mappings + 1);
            char *strptr = (char *) (result + (num_mappings + 1));
            for (int i = 0; i < num_mappings; i++) {
                result[i] = strptr;
                const size_t slen = SDL_strlcpy(strptr, mappings[i], final_allocation) + 1;
                SDL_assert(final_allocation >= slen);
                final_allocation -= slen;
                strptr += slen;
            }
            result[num_mappings] = NULL;
            if (count) {
                *count = num_mappings;
            }
        }
    }
    if (mappings) {
        for (int i = 0; i < num_mappings; i++) {
            SDL_free(mappings[i]);
        }
        SDL_free(mappings);
    }
    return result;
}
References count, CreateMappingString(), NULL, s_zeroGUID, SDL_assert, SDL_calloc(), SDL_free(), SDL_LockJoysticks(), SDL_malloc(), SDL_memcmp(), SDL_strlcpy(), SDL_strlen(), and SDL_UnlockJoysticks().
SDL_GetGamepadName()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadName (SDL_Gamepad * gamepad) extern
Get the implementation-dependent name for an opened gamepad.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
the implementation dependent name for the gamepad, or NULL if there is no name or the identifier passed is invalid.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadNameForID
{
    const char *result = NULL;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        if (SDL_strcmp(gamepad->name, "*") == 0 ||
            gamepad->joystick->steam_handle != 0) {
            result = SDL_GetJoystickName(gamepad->joystick);
        } else {
            result = SDL_GetPersistentString(gamepad->name);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_GAMEPAD_MAGIC, NULL, SDL_GetJoystickName(), SDL_GetPersistentString(), SDL_LockJoysticks(), SDL_strcmp(), and SDL_UnlockJoysticks().
SDL_GetGamepadNameForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadNameForID (SDL_JoystickID instance_id) extern
Get the implementation dependent name of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the name of the selected gamepad. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadName
SDL_GetGamepads
{
    const char *result = NULL;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMapping(instance_id, true);
        if (mapping) {
            if (SDL_strcmp(mapping->name, "*") == 0) {
                result = SDL_GetJoystickNameForID(instance_id);
            } else {
                result = SDL_GetPersistentString(mapping->name);
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_GetJoystickNameForID(), SDL_GetPersistentString(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), SDL_strcmp(), and SDL_UnlockJoysticks().
SDL_GetGamepadPath()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadPath (SDL_Gamepad * gamepad) extern
Get the implementation-dependent path for an opened gamepad.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
the implementation dependent path for the gamepad, or NULL if there is no path or the identifier passed is invalid.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPathForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return NULL;
    }
    return SDL_GetJoystickPath(joystick);
}
References NULL, SDL_GetGamepadJoystick(), and SDL_GetJoystickPath().
SDL_GetGamepadPathForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadPathForID (SDL_JoystickID instance_id) extern
Get the implementation dependent path of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the path of the selected gamepad. If no path can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPath
SDL_GetGamepads
{
    return SDL_GetJoystickPathForID(instance_id);
}
References SDL_GetJoystickPathForID().
SDL_GetGamepadPlayerIndex()
SDL_DECLSPEC int SDLCALL SDL_GetGamepadPlayerIndex (SDL_Gamepad * gamepad) extern
Get the player index of an opened gamepad.
For XInput gamepads this returns the XInput user index.
Parameters
gamepad the gamepad object to query.
Returns
the player index for gamepad, or -1 if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetGamepadPlayerIndex
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return -1;
    }
    return SDL_GetJoystickPlayerIndex(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickPlayerIndex().
SDL_GetGamepadPlayerIndexForID()
SDL_DECLSPEC int SDLCALL SDL_GetGamepadPlayerIndexForID (SDL_JoystickID instance_id) extern
Get the player index of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the player index of a gamepad, or -1 if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPlayerIndex
SDL_GetGamepads
{
    return SDL_GetJoystickPlayerIndexForID(instance_id);
}
References SDL_GetJoystickPlayerIndexForID().
SDL_GetGamepadPowerInfo()
SDL_DECLSPEC SDL_PowerState SDLCALL SDL_GetGamepadPowerInfo (SDL_Gamepad * gamepad, int * percent) extern
Get the battery state of a gamepad.
You should never take a battery status as absolute truth. Batteries (especially failing batteries) are delicate hardware, and the values reported here are best estimates based on what that hardware reports. It's not uncommon for older batteries to lose stored power much faster than it reports, or completely drain when reporting it has 20 percent left, etc.
Parameters
gamepad the gamepad object to query.
percent a pointer filled in with the percentage of battery life left, between 0 and 100, or NULL to ignore. This will be filled in with -1 we can't determine a value or there is no battery.
Returns
the current battery state.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (percent) {
        *percent = -1;
    }
    if (!joystick) {
        return SDL_POWERSTATE_ERROR;
    }
    return SDL_GetJoystickPowerInfo(joystick, percent);
}
References SDL_GetGamepadJoystick(), SDL_GetJoystickPowerInfo(), and SDL_POWERSTATE_ERROR.
SDL_GetGamepadProduct()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProduct (SDL_Gamepad * gamepad) extern
Get the USB product ID of an opened gamepad, if available.
If the product ID isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the USB product ID, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProductForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickProduct(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickProduct().
SDL_GetGamepadProductForID()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProductForID (SDL_JoystickID instance_id) extern
Get the USB product ID of a gamepad, if available.
This can be called before any gamepads are opened. If the product ID isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the USB product ID of the selected gamepad. If called on an invalid index, this function returns zero.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProduct
SDL_GetGamepads
{
    return SDL_GetJoystickProductForID(instance_id);
}
References SDL_GetJoystickProductForID().
SDL_GetGamepadProductVersion()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProductVersion (SDL_Gamepad * gamepad) extern
Get the product version of an opened gamepad, if available.
If the product version isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the USB product version, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProductVersionForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickProductVersion(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickProductVersion().
SDL_GetGamepadProductVersionForID()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadProductVersionForID (SDL_JoystickID instance_id) extern
Get the product version of a gamepad, if available.
This can be called before any gamepads are opened. If the product version isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the product version of the selected gamepad. If called on an invalid index, this function returns zero.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProductVersion
SDL_GetGamepads
{
    return SDL_GetJoystickProductVersionForID(instance_id);
}
References SDL_GetJoystickProductVersionForID().
SDL_GetGamepadProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetGamepadProperties (SDL_Gamepad * gamepad) extern
Get the properties associated with an opened gamepad.
These properties are shared with the underlying joystick object.
The following read-only properties are provided by SDL:
SDL_PROP_GAMEPAD_CAP_MONO_LED_BOOLEAN: true if this gamepad has an LED that has adjustable brightness
SDL_PROP_GAMEPAD_CAP_RGB_LED_BOOLEAN: true if this gamepad has an LED that has adjustable color
SDL_PROP_GAMEPAD_CAP_PLAYER_LED_BOOLEAN: true if this gamepad has a player LED
SDL_PROP_GAMEPAD_CAP_RUMBLE_BOOLEAN: true if this gamepad has left/right rumble
SDL_PROP_GAMEPAD_CAP_TRIGGER_RUMBLE_BOOLEAN: true if this gamepad has simple trigger rumble
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID result = 0;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, 0);
        result = SDL_GetJoystickProperties(gamepad->joystick);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_GAMEPAD_MAGIC, SDL_GetJoystickProperties(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepads()
SDL_DECLSPEC SDL_JoystickID *SDLCALL SDL_GetGamepads (int * count) extern
Get a list of currently connected gamepads.
Parameters
count a pointer filled in with the number of gamepads returned, may be NULL.
Returns
a 0 terminated array of joystick instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasGamepad
SDL_OpenGamepad
{
    int num_joysticks = 0;
    int num_gamepads = 0;
    SDL_JoystickID *joysticks = SDL_GetJoysticks(&num_joysticks);
    if (joysticks) {
        int i;
        for (i = num_joysticks - 1; i >= 0; --i) {
            if (SDL_IsGamepad(joysticks[i])) {
                ++num_gamepads;
            } else {
                SDL_memmove(&joysticks[i], &joysticks[i+1], (num_gamepads + 1) * sizeof(joysticks[i]));
            }
        }
    }
    if (count) {
        *count = num_gamepads;
    }
    return joysticks;
}
References count, SDL_GetJoysticks(), SDL_IsGamepad(), and SDL_memmove.
SDL_GetGamepadSensorData()
SDL_DECLSPEC bool SDLCALL SDL_GetGamepadSensorData (SDL_Gamepad * gamepad, SDL_SensorType type, float * data, int num_values) extern
Get the current state of a gamepad sensor.
The number of values and interpretation of the data is sensor dependent. See SDL_sensor.h for the details for each type of sensor.
Parameters
gamepad the gamepad to query.
type the type of sensor to query.
data a pointer filled with the current sensor state.
num_values the number of values to write to data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                SDL_JoystickSensorInfo *sensor = &joystick->sensors[i];
                if (sensor->type == type) {
                    num_values = SDL_min(num_values, SDL_arraysize(sensor->data));
                    SDL_memcpy(data, sensor->data, num_values * sizeof(*data));
                    SDL_UnlockJoysticks();
                    return true;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return SDL_Unsupported();
}
References SDL_JoystickSensorInfo::data, SDL_arraysize, SDL_GetGamepadJoystick(), SDL_LockJoysticks(), SDL_memcpy, SDL_min, SDL_UnlockJoysticks(), SDL_Unsupported, and SDL_JoystickSensorInfo::type.
SDL_GetGamepadSensorDataRate()
SDL_DECLSPEC float SDLCALL SDL_GetGamepadSensorDataRate (SDL_Gamepad * gamepad, SDL_SensorType type) extern
Get the data rate (number of events per second) of a gamepad sensor.
Parameters
gamepad the gamepad to query.
type the type of sensor to query.
Returns
the data rate, or 0.0f if the data rate is not available.
Since
This function is available since SDL 3.2.0.
{
    float result = 0.0f;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                SDL_JoystickSensorInfo *sensor = &joystick->sensors[i];
                if (sensor->type == type) {
                    result = sensor->rate;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_JoystickSensorInfo::rate, SDL_GetGamepadJoystick(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_JoystickSensorInfo::type.
SDL_GetGamepadSerial()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadSerial (SDL_Gamepad * gamepad) extern
Get the serial number of an opened gamepad, if available.
Returns the serial number of the gamepad, or NULL if it is not available.
Parameters
gamepad the gamepad object to query.
Returns
the serial number, or NULL if unavailable.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return NULL;
    }
    return SDL_GetJoystickSerial(joystick);
}
References NULL, SDL_GetGamepadJoystick(), and SDL_GetJoystickSerial().
SDL_GetGamepadSteamHandle()
SDL_DECLSPEC Uint64 SDLCALL SDL_GetGamepadSteamHandle (SDL_Gamepad * gamepad) extern
Get the Steam Input handle of an opened gamepad, if available.
Returns an InputHandle_t for the gamepad that can be used with Steam Input API: https://partner.steamgames.com/doc/api/ISteamInput
Parameters
gamepad the gamepad object to query.
Returns
the gamepad handle, or 0 if unavailable.
Since
This function is available since SDL 3.2.0.
{
    Uint64 handle = 0;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, 0);
        handle = gamepad->joystick->steam_handle;
    }
    SDL_UnlockJoysticks();
    return handle;
}
References CHECK_GAMEPAD_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadStringForAxis()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadStringForAxis (SDL_GamepadAxis axis) extern
Convert from an SDL_GamepadAxis enum to a string.
Parameters
axis an enum value for a given SDL_GamepadAxis.
Returns
a string for the given axis, or NULL if an invalid axis is specified. The string returned is of the format used by SDL_Gamepad mapping strings.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadAxisFromString
{
    if (axis > SDL_GAMEPAD_AXIS_INVALID && axis < SDL_GAMEPAD_AXIS_COUNT) {
        return map_StringForGamepadAxis[axis];
    }
    return NULL;
}
References map_StringForGamepadAxis, NULL, SDL_GAMEPAD_AXIS_COUNT, and SDL_GAMEPAD_AXIS_INVALID.
SDL_GetGamepadStringForButton()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadStringForButton (SDL_GamepadButton button) extern
Convert from an SDL_GamepadButton enum to a string.
Parameters
button an enum value for a given SDL_GamepadButton.
Returns
a string for the given button, or NULL if an invalid button is specified. The string returned is of the format used by SDL_Gamepad mapping strings.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadButtonFromString
{
    if (button > SDL_GAMEPAD_BUTTON_INVALID && button < SDL_GAMEPAD_BUTTON_COUNT) {
        return map_StringForGamepadButton[button];
    }
    return NULL;
}
References map_StringForGamepadButton, NULL, SDL_GAMEPAD_BUTTON_COUNT, and SDL_GAMEPAD_BUTTON_INVALID.
SDL_GetGamepadStringForType()
SDL_DECLSPEC const char *SDLCALL SDL_GetGamepadStringForType (SDL_GamepadType type) extern
Convert from an SDL_GamepadType enum to a string.
Parameters
type an enum value for a given SDL_GamepadType.
Returns
a string for the given type, or NULL if an invalid type is specified. The string returned is of the format used by SDL_Gamepad mapping strings.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadTypeFromString
{
    if (type >= SDL_GAMEPAD_TYPE_STANDARD && type < SDL_GAMEPAD_TYPE_COUNT) {
        return map_StringForGamepadType[type];
    }
    return NULL;
}
References map_StringForGamepadType, NULL, SDL_GAMEPAD_TYPE_COUNT, and SDL_GAMEPAD_TYPE_STANDARD.
SDL_GetGamepadTouchpadFinger()
SDL_DECLSPEC bool SDLCALL SDL_GetGamepadTouchpadFinger (SDL_Gamepad * gamepad, int touchpad, int finger, bool * down, float * x, float * y, float * pressure) extern
Get the current state of a finger on a touchpad on a gamepad.
Parameters
gamepad a gamepad.
touchpad a touchpad.
finger a finger.
down a pointer filled with true if the finger is down, false otherwise, may be NULL.
x a pointer filled with the x position, normalized 0 to 1, with the origin in the upper left, may be NULL.
y a pointer filled with the y position, normalized 0 to 1, with the origin in the upper left, may be NULL.
pressure a pointer filled with pressure value, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumGamepadTouchpadFingers
Get the current state of a finger on a touchpad on a gamepad.
{
    bool result = false;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            if (touchpad >= 0 && touchpad < joystick->ntouchpads) {
                SDL_JoystickTouchpadInfo *touchpad_info = &joystick->touchpads[touchpad];
                if (finger >= 0 && finger < touchpad_info->nfingers) {
                    SDL_JoystickTouchpadFingerInfo *info = &touchpad_info->fingers[finger];
                    if (down) {
                        *down = info->down;
                    }
                    if (x) {
                        *x = info->x;
                    }
                    if (y) {
                        *y = info->y;
                    }
                    if (pressure) {
                        *pressure = info->pressure;
                    }
                    result = true;
                } else {
                    result = SDL_InvalidParamError("finger");
                }
            } else {
                result = SDL_InvalidParamError("touchpad");
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_JoystickTouchpadFingerInfo::down, SDL_JoystickTouchpadInfo::fingers, SDL_JoystickTouchpadFingerInfo::pressure, SDL_GetGamepadJoystick(), SDL_InvalidParamError, SDL_LockJoysticks(), SDL_UnlockJoysticks(), SDL_JoystickTouchpadFingerInfo::x, and SDL_JoystickTouchpadFingerInfo::y.
SDL_GetGamepadType()
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetGamepadType (SDL_Gamepad * gamepad) extern
Get the type of an opened gamepad.
Parameters
gamepad the gamepad object to query.
Returns
the gamepad type, or SDL_GAMEPAD_TYPE_UNKNOWN if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadTypeForID
{
    SDL_GamepadType type;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, SDL_GAMEPAD_TYPE_UNKNOWN);
        info = SDL_GetJoystickVirtualGamepadInfoForID(gamepad->joystick->instance_id);
        if (info) {
            type = info->type;
        } else {
            type = gamepad->type;
        }
    }
    SDL_UnlockJoysticks();
    return type;
}
References CHECK_GAMEPAD_MAGIC, SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_SteamVirtualGamepadInfo::type.
SDL_GetGamepadTypeForID()
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetGamepadTypeForID (SDL_JoystickID instance_id) extern
Get the type of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the gamepad type.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadType
SDL_GetGamepads
SDL_GetRealGamepadTypeForID
{
    SDL_GamepadType type = SDL_GAMEPAD_TYPE_UNKNOWN;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMapping(instance_id, true);
        if (mapping) {
            char *type_string, *comma;
            type_string = SDL_strstr(mapping->mapping, SDL_GAMEPAD_TYPE_FIELD);
            if (type_string) {
                type_string += SDL_GAMEPAD_TYPE_FIELD_SIZE;
                comma = SDL_strchr(type_string, ',');
                if (comma) {
                    *comma = '\0';
                    type = SDL_GetGamepadTypeFromString(type_string);
                    *comma = ',';
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    if (type != SDL_GAMEPAD_TYPE_UNKNOWN) {
        return type;
    }
    return SDL_GetRealGamepadTypeForID(instance_id);
}
References SDL_GAMEPAD_TYPE_FIELD, SDL_GAMEPAD_TYPE_FIELD_SIZE, SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetGamepadTypeFromString(), SDL_GetRealGamepadTypeForID(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), SDL_strchr(), SDL_strstr(), and SDL_UnlockJoysticks().
SDL_GetGamepadTypeFromString()
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetGamepadTypeFromString (const char * str) extern
Convert a string into SDL_GamepadType enum.
This function is called internally to translate SDL_Gamepad mapping strings for the underlying joystick device into the consistent SDL_Gamepad mapping. You do not normally need to call this function unless you are parsing SDL_Gamepad mappings in your own code.
Parameters
str string representing a SDL_GamepadType type.
Returns
the SDL_GamepadType enum corresponding to the input string, or SDL_GAMEPAD_TYPE_UNKNOWN if no match was found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadStringForType
{
    int i;
    if (!str || str[0] == '\0') {
        return SDL_GAMEPAD_TYPE_UNKNOWN;
    }
    if (*str == '+' || *str == '-') {
        ++str;
    }
    for (i = 0; i < SDL_arraysize(map_StringForGamepadType); ++i) {
        if (SDL_strcasecmp(str, map_StringForGamepadType[i]) == 0) {
            return (SDL_GamepadType)i;
        }
    }
    return SDL_GAMEPAD_TYPE_UNKNOWN;
}
References map_StringForGamepadType, SDL_arraysize, SDL_GAMEPAD_TYPE_UNKNOWN, and SDL_strcasecmp().
Referenced by SDL_GetGamepadTypeForID(), SDL_UpdateGamepadType(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_GetGamepadVendor()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadVendor (SDL_Gamepad * gamepad) extern
Get the USB vendor ID of an opened gamepad, if available.
If the vendor ID isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the USB vendor ID, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadVendorForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickVendor(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickVendor().
SDL_GetGamepadVendorForID()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetGamepadVendorForID (SDL_JoystickID instance_id) extern
Get the USB vendor ID of a gamepad, if available.
This can be called before any gamepads are opened. If the vendor ID isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the USB vendor ID of the selected gamepad. If called on an invalid index, this function returns zero.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadVendor
SDL_GetGamepads
{
    return SDL_GetJoystickVendorForID(instance_id);
}
References SDL_GetJoystickVendorForID().
SDL_GetNumGamepadTouchpadFingers()
SDL_DECLSPEC int SDLCALL SDL_GetNumGamepadTouchpadFingers (SDL_Gamepad * gamepad, int touchpad) extern
Get the number of supported simultaneous fingers on a touchpad on a game gamepad.
Parameters
gamepad a gamepad.
touchpad a touchpad.
Returns
number of supported simultaneous fingers.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadTouchpadFinger
SDL_GetNumGamepadTouchpads
Get the number of supported simultaneous fingers on a touchpad on a gamepad.
{
    int result = 0;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            if (touchpad >= 0 && touchpad < joystick->ntouchpads) {
                result = joystick->touchpads[touchpad].nfingers;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetNumGamepadTouchpads()
SDL_DECLSPEC int SDLCALL SDL_GetNumGamepadTouchpads (SDL_Gamepad * gamepad) extern
Get the number of touchpads on a gamepad.
Parameters
gamepad a gamepad.
Returns
number of touchpads.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumGamepadTouchpadFingers
Get the number of touchpads on a gamepad.
{
    int result = 0;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            result = joystick->ntouchpads;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetRealGamepadType()
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetRealGamepadType (SDL_Gamepad * gamepad) extern
Get the type of an opened gamepad, ignoring any mapping override.
Parameters
gamepad the gamepad object to query.
Returns
the gamepad type, or SDL_GAMEPAD_TYPE_UNKNOWN if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRealGamepadTypeForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return SDL_GAMEPAD_TYPE_UNKNOWN;
    }
    return SDL_GetGamepadTypeFromGUID(SDL_GetJoystickGUID(joystick), SDL_GetJoystickName(joystick));
}
References SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetGamepadJoystick(), SDL_GetGamepadTypeFromGUID(), SDL_GetJoystickGUID(), and SDL_GetJoystickName().
SDL_GetRealGamepadTypeForID()
SDL_DECLSPEC SDL_GamepadType SDLCALL SDL_GetRealGamepadTypeForID (SDL_JoystickID instance_id) extern
Get the type of a gamepad, ignoring any mapping override.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the gamepad type.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadTypeForID
SDL_GetGamepads
SDL_GetRealGamepadType
{
    SDL_GamepadType type = SDL_GAMEPAD_TYPE_UNKNOWN;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    {
        info = SDL_GetJoystickVirtualGamepadInfoForID(instance_id);
        if (info) {
            type = info->type;
        } else {
            type = SDL_GetGamepadTypeFromGUID(SDL_GetJoystickGUIDForID(instance_id), SDL_GetJoystickNameForID(instance_id));
        }
    }
    SDL_UnlockJoysticks();
    return type;
}
References SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetGamepadTypeFromGUID(), SDL_GetJoystickGUIDForID(), SDL_GetJoystickNameForID(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_SteamVirtualGamepadInfo::type.
Referenced by SDL_GetGamepadTypeForID(), and SDL_UpdateGamepadType().
SDL_HasGamepad()
SDL_DECLSPEC bool SDLCALL SDL_HasGamepad (void) extern
Return whether a gamepad is currently connected.
Returns
true if a gamepad is connected, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepads
{
    int num_joysticks = 0;
    int num_gamepads = 0;
    SDL_JoystickID *joysticks = SDL_GetJoysticks(&num_joysticks);
    if (joysticks) {
        int i;
        for (i = num_joysticks - 1; i >= 0 && num_gamepads == 0; --i) {
            if (SDL_IsGamepad(joysticks[i])) {
                ++num_gamepads;
            }
        }
        SDL_free(joysticks);
    }
    if (num_gamepads > 0) {
        return true;
    }
    return false;
}
References SDL_free(), SDL_GetJoysticks(), and SDL_IsGamepad().
SDL_IsGamepad()
SDL_DECLSPEC bool SDLCALL SDL_IsGamepad (SDL_JoystickID instance_id) extern
Check if the given joystick is supported by the gamepad interface.
Parameters
instance_id the joystick instance ID.
Returns
true if the given joystick is supported by the gamepad interface, false if it isn't or it's an invalid index.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoysticks
SDL_OpenGamepad
{
    bool result;
    SDL_LockJoysticks();
    {
        const void *value;
        if (SDL_FindInHashTable(s_gamepadInstanceIDs, (void *)(uintptr_t)instance_id, &value)) {
            result = (bool)(uintptr_t)value;
        } else {
            if (SDL_PrivateGetGamepadMapping(instance_id, true) != NULL) {
                result = true;
            } else {
                result = false;
            }
            if (!s_gamepadInstanceIDs) {
                s_gamepadInstanceIDs = SDL_CreateHashTable(0, false, SDL_HashID, SDL_KeyMatchID, NULL, NULL);
            }
            SDL_InsertIntoHashTable(s_gamepadInstanceIDs, (void *)(uintptr_t)instance_id, (void *)(uintptr_t)result, true);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References bool, NULL, SDL_CreateHashTable(), SDL_FindInHashTable(), SDL_HashID(), SDL_InsertIntoHashTable(), SDL_KeyMatchID(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepads(), SDL_GetJoystickType(), SDL_GetJoystickTypeForID(), SDL_HasGamepad(), SDL_InitGamepads(), SDL_IsJoystickHaptic(), SDL_PrivateJoystickAdded(), SDL_PrivateJoystickRemoved(), SendSteamHandleUpdateEvents(), and ShouldAttemptSensorFusion().
SDL_OpenGamepad()
SDL_DECLSPEC SDL_Gamepad *SDLCALL SDL_OpenGamepad (SDL_JoystickID instance_id) extern
Open a gamepad for use.
Parameters
instance_id the joystick instance ID.
Returns
a gamepad identifier or NULL if an error occurred; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseGamepad
SDL_IsGamepad
{
    SDL_Gamepad *gamepad;
    SDL_Gamepad *gamepadlist;
    GamepadMapping_t *pSupportedGamepad = NULL;
    SDL_LockJoysticks();
    gamepadlist = SDL_gamepads;
    // If the gamepad is already open, return it
    while (gamepadlist) {
        if (instance_id == gamepadlist->joystick->instance_id) {
            gamepad = gamepadlist;
            ++gamepad->ref_count;
            SDL_UnlockJoysticks();
            return gamepad;
        }
        gamepadlist = gamepadlist->next;
    }
    // Find a gamepad mapping
    pSupportedGamepad = SDL_PrivateGetGamepadMapping(instance_id, true);
    if (!pSupportedGamepad) {
        SDL_SetError("Couldn't find mapping for device (%" SDL_PRIu32 ")", instance_id);
        SDL_UnlockJoysticks();
        return NULL;
    }
    // Create and initialize the gamepad
    gamepad = (SDL_Gamepad *)SDL_calloc(1, sizeof(*gamepad));
    if (!gamepad) {
        SDL_UnlockJoysticks();
        return NULL;
    }
    SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, true);
    gamepad->joystick = SDL_OpenJoystick(instance_id);
    if (!gamepad->joystick) {
        SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
        SDL_free(gamepad);
        SDL_UnlockJoysticks();
        return NULL;
    }
    if (gamepad->joystick->naxes) {
        gamepad->last_match_axis = (SDL_GamepadBinding **)SDL_calloc(gamepad->joystick->naxes, sizeof(*gamepad->last_match_axis));
        if (!gamepad->last_match_axis) {
            SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
            SDL_CloseJoystick(gamepad->joystick);
            SDL_free(gamepad);
            SDL_UnlockJoysticks();
            return NULL;
        }
    }
    if (gamepad->joystick->nhats) {
        gamepad->last_hat_mask = (Uint8 *)SDL_calloc(gamepad->joystick->nhats, sizeof(*gamepad->last_hat_mask));
        if (!gamepad->last_hat_mask) {
            SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
            SDL_CloseJoystick(gamepad->joystick);
            SDL_free(gamepad->last_match_axis);
            SDL_free(gamepad);
            SDL_UnlockJoysticks();
            return NULL;
        }
    }
    SDL_PrivateLoadButtonMapping(gamepad, pSupportedGamepad);
    // Add the gamepad to list
    ++gamepad->ref_count;
    // Link the gamepad in the list
    gamepad->next = SDL_gamepads;
    SDL_gamepads = gamepad;
    SDL_UnlockJoysticks();
    return gamepad;
}
References NULL, SDL_calloc(), SDL_CloseJoystick(), SDL_free(), SDL_LockJoysticks(), SDL_OBJECT_TYPE_GAMEPAD, SDL_OpenJoystick(), SDL_PRIu32, SDL_PrivateGetGamepadMapping(), SDL_PrivateLoadButtonMapping(), SDL_SetError(), SDL_SetObjectValid(), and SDL_UnlockJoysticks().
SDL_ReloadGamepadMappings()
SDL_DECLSPEC bool SDLCALL SDL_ReloadGamepadMappings (void) extern
Reinitialize the SDL mapping database to its initial state.
This will generate gamepad events as needed if device mappings change.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    PushMappingChangeTracking();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        AddMappingChangeTracking(gamepad->mapping);
    }
    SDL_QuitGamepadMappings();
    SDL_InitGamepadMappings();
    PopMappingChangeTracking();
    SDL_UnlockJoysticks();
    return true;
}
References AddMappingChangeTracking(), PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_InitGamepadMappings(), SDL_LockJoysticks(), SDL_QuitGamepadMappings(), and SDL_UnlockJoysticks().
SDL_RumbleGamepad()
SDL_DECLSPEC bool SDLCALL SDL_RumbleGamepad (SDL_Gamepad * gamepad, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms) extern
Start a rumble effect on a gamepad.
Each call to this function cancels any previous rumble effect, and calling it with 0 intensity stops any rumbling.
This function requires you to process SDL events or call SDL_UpdateJoysticks() to update rumble state.
Parameters
gamepad the gamepad to vibrate.
low_frequency_rumble the intensity of the low frequency (left) rumble motor, from 0 to 0xFFFF.
high_frequency_rumble the intensity of the high frequency (right) rumble motor, from 0 to 0xFFFF.
duration_ms the duration of the rumble effect, in milliseconds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_RumbleJoystick(joystick, low_frequency_rumble, high_frequency_rumble, duration_ms);
}
References SDL_GetGamepadJoystick(), and SDL_RumbleJoystick().
SDL_RumbleGamepadTriggers()
SDL_DECLSPEC bool SDLCALL SDL_RumbleGamepadTriggers (SDL_Gamepad * gamepad, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms) extern
Start a rumble effect in the gamepad's triggers.
Each call to this function cancels any previous trigger rumble effect, and calling it with 0 intensity stops any rumbling.
Note that this is rumbling of the triggers and not the gamepad as a whole. This is currently only supported on Xbox One gamepads. If you want the (more common) whole-gamepad rumble, use SDL_RumbleGamepad() instead.
This function requires you to process SDL events or call SDL_UpdateJoysticks() to update rumble state.
Parameters
gamepad the gamepad to vibrate.
left_rumble the intensity of the left trigger rumble motor, from 0 to 0xFFFF.
right_rumble the intensity of the right trigger rumble motor, from 0 to 0xFFFF.
duration_ms the duration of the rumble effect, in milliseconds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_RumbleGamepad
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_RumbleJoystickTriggers(joystick, left_rumble, right_rumble, duration_ms);
}
References SDL_GetGamepadJoystick(), and SDL_RumbleJoystickTriggers().
SDL_SendGamepadEffect()
SDL_DECLSPEC bool SDLCALL SDL_SendGamepadEffect (SDL_Gamepad * gamepad, const void * data, int size) extern
Send a gamepad specific effect packet.
Parameters
gamepad the gamepad to affect.
data the data to send to the gamepad.
size the size of the data to send to the gamepad.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_SendJoystickEffect(joystick, data, size);
}
References SDL_GetGamepadJoystick(), and SDL_SendJoystickEffect().
SDL_SetGamepadEventsEnabled()
SDL_DECLSPEC void SDLCALL SDL_SetGamepadEventsEnabled (bool enabled) extern
Set the state of gamepad event processing.
If gamepad events are disabled, you must call SDL_UpdateGamepads() yourself and check the state of the gamepad when you want gamepad information.
Parameters
enabled whether to process gamepad events or not.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadEventsEnabled
SDL_UpdateGamepads
{
    unsigned int i;
    for (i = 0; i < SDL_arraysize(SDL_gamepad_event_list); ++i) {
        SDL_SetEventEnabled(SDL_gamepad_event_list[i], enabled);
    }
}
References SDL_arraysize, SDL_gamepad_event_list, and SDL_SetEventEnabled().
SDL_SetGamepadLED()
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadLED (SDL_Gamepad * gamepad, Uint8 red, Uint8 green, Uint8 blue) extern
Update a gamepad's LED color.
An example of a joystick LED is the light on the back of a PlayStation 4's DualShock 4 controller.
For gamepads with a single color LED, the maximum of the RGB values will be used as the LED brightness.
Parameters
gamepad the gamepad to update.
red the intensity of the red LED.
green the intensity of the green LED.
blue the intensity of the blue LED.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_SetJoystickLED(joystick, red, green, blue);
}
References SDL_GetGamepadJoystick(), and SDL_SetJoystickLED().
SDL_SetGamepadMapping()
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadMapping (SDL_JoystickID instance_id, const char * mapping) extern
Set the current mapping of a joystick or gamepad.
Details about mappings are discussed with SDL_AddGamepadMapping().
Parameters
instance_id the joystick instance ID.
mapping the mapping to use for this device, or NULL to clear the mapping.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_GetGamepadMapping
{
    SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
    bool result = false;
    if (SDL_memcmp(&guid, &s_zeroGUID, sizeof(guid)) == 0) {
        return SDL_InvalidParamError("instance_id");
    }
    if (!mapping) {
        mapping = "*,*,";
    }
    SDL_LockJoysticks();
    {
        if (SDL_PrivateAddMappingForGUID(guid, mapping, NULL, SDL_GAMEPAD_MAPPING_PRIORITY_API)) {
            result = true;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, s_zeroGUID, SDL_GAMEPAD_MAPPING_PRIORITY_API, SDL_GetJoystickGUIDForID(), SDL_InvalidParamError, SDL_LockJoysticks(), SDL_memcmp(), SDL_PrivateAddMappingForGUID(), and SDL_UnlockJoysticks().
SDL_SetGamepadPlayerIndex()
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadPlayerIndex (SDL_Gamepad * gamepad, int player_index) extern
Set the player index of an opened gamepad.
Parameters
gamepad the gamepad object to adjust.
player_index player index to assign to this gamepad, or -1 to clear the player index and turn off player LEDs.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPlayerIndex
Set the player index of an opened gamepad
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        // SDL_SetError() will have been called already by SDL_GetGamepadJoystick()
        return false;
    }
    return SDL_SetJoystickPlayerIndex(joystick, player_index);
}
References SDL_GetGamepadJoystick(), and SDL_SetJoystickPlayerIndex().
SDL_SetGamepadSensorEnabled()
SDL_DECLSPEC bool SDLCALL SDL_SetGamepadSensorEnabled (SDL_Gamepad * gamepad, SDL_SensorType type, bool enabled) extern
Set whether data reporting for a gamepad sensor is enabled.
Parameters
gamepad the gamepad to update.
type the type of sensor to enable/disable.
enabled whether data reporting should be enabled.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasSensor
SDL_GamepadSensorEnabled
{
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                SDL_JoystickSensorInfo *sensor = &joystick->sensors[i];
                if (sensor->type == type) {
                    if (sensor->enabled == (enabled != false)) {
                        SDL_UnlockJoysticks();
                        return true;
                    }
                    if (type == SDL_SENSOR_ACCEL && joystick->accel_sensor) {
                        if (enabled) {
                            joystick->accel = SDL_OpenSensor(joystick->accel_sensor);
                            if (!joystick->accel) {
                                SDL_UnlockJoysticks();
                                return false;
                            }
                        } else {
                            if (joystick->accel) {
                                SDL_CloseSensor(joystick->accel);
                                joystick->accel = NULL;
                            }
                        }
                    } else if (type == SDL_SENSOR_GYRO && joystick->gyro_sensor) {
                        if (enabled) {
                            joystick->gyro = SDL_OpenSensor(joystick->gyro_sensor);
                            if (!joystick->gyro) {
                                SDL_UnlockJoysticks();
                                return false;
                            }
                        } else {
                            if (joystick->gyro) {
                                SDL_CloseSensor(joystick->gyro);
                                joystick->gyro = NULL;
                            }
                        }
                    } else {
                        if (enabled) {
                            if (joystick->nsensors_enabled == 0) {
                                if (!joystick->driver->SetSensorsEnabled(joystick, true)) {
                                    SDL_UnlockJoysticks();
                                    return false;
                                }
                            }
                            ++joystick->nsensors_enabled;
                        } else {
                            if (joystick->nsensors_enabled == 1) {
                                if (!joystick->driver->SetSensorsEnabled(joystick, false)) {
                                    SDL_UnlockJoysticks();
                                    return false;
                                }
                            }
                            --joystick->nsensors_enabled;
                        }
                    }
                    sensor->enabled = enabled;
                    SDL_UnlockJoysticks();
                    return true;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return SDL_Unsupported();
}
References SDL_JoystickSensorInfo::enabled, NULL, SDL_CloseSensor(), SDL_GetGamepadJoystick(), SDL_LockJoysticks(), SDL_OpenSensor(), SDL_SENSOR_ACCEL, SDL_SENSOR_GYRO, SDL_UnlockJoysticks(), SDL_Unsupported, and SDL_JoystickSensorInfo::type.
SDL_UpdateGamepads()
SDL_DECLSPEC void SDLCALL SDL_UpdateGamepads (void) extern
Manually pump gamepad updates if not using the loop.
This function is called automatically by the event loop if events are enabled. Under such circumstances, it will not be necessary to call this function.
Since
This function is available since SDL 3.2.0.
{
    // Just for API completeness; the joystick API does all the work.
    SDL_UpdateJoysticks();
}
References SDL_UpdateJoysticks().