SDL3: SDL-main/src/events/SDL_displayevents.c File Reference
SDL_displayevents.c File Reference
#include "SDL_internal.h"
#include "SDL_events_c.h"
Functions
void SDL_SendDisplayEvent (SDL_VideoDisplay *display, SDL_EventType displayevent, int data1, int data2)
Function Documentation
SDL_SendDisplayEvent()
void SDL_SendDisplayEvent (SDL_VideoDisplay * display, SDL_EventType displayevent, int data1, int data2)
{
    if (!display || display->id == 0) {
        return;
    }
    switch (displayevent) {
    case SDL_EVENT_DISPLAY_ORIENTATION:
        if (data1 == SDL_ORIENTATION_UNKNOWN || data1 == display->current_orientation) {
            return;
        }
        display->current_orientation = (SDL_DisplayOrientation)data1;
        break;
    default:
        break;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(displayevent)) {
        SDL_Event event;
        event.type = displayevent;
        event.common.timestamp = 0;
        event.display.displayID = display->id;
        event.display.data1 = data1;
        event.display.data2 = data2;
        SDL_PushEvent(&event);
    }
    switch (displayevent) {
    case SDL_EVENT_DISPLAY_ADDED:
        SDL_OnDisplayAdded(display);
        break;
    case SDL_EVENT_DISPLAY_MOVED:
        SDL_OnDisplayMoved(display);
        break;
    default:
        break;
    }
}
References SDL_EVENT_DISPLAY_ADDED, SDL_EVENT_DISPLAY_MOVED, SDL_EVENT_DISPLAY_ORIENTATION, SDL_EventEnabled(), SDL_OnDisplayAdded(), SDL_OnDisplayMoved(), SDL_ORIENTATION_UNKNOWN, and SDL_PushEvent().
Referenced by SDL_AddVideoDisplay(), SDL_DelVideoDisplay(), SDL_SetCurrentDisplayMode(), SDL_SetDesktopDisplayMode(), and SDL_SetDisplayContentScale().