SDL3: SDL-main/src/SDL_log_c.h File Reference
SDL_log_c.h File Reference
#include "SDL_internal.h"
Functions
void SDL_InitLog (void)
void SDL_QuitLog (void)
Function Documentation
SDL_InitLog()
void SDL_InitLog (void) extern
{
    if (!SDL_ShouldInit(&SDL_log_init)) {
        return;
    }
    // If these fail we'll continue without them.
    SDL_log_lock = SDL_CreateMutex();
    SDL_log_function_lock = SDL_CreateMutex();
    SDL_AddHintCallback(SDL_HINT_LOGGING, SDL_LoggingChanged, NULL);
    SDL_SetInitialized(&SDL_log_init, true);
}
References NULL, SDL_AddHintCallback(), SDL_CreateMutex(), SDL_HINT_LOGGING, SDL_log_function_lock, SDL_log_init, SDL_log_lock, SDL_LoggingChanged(), SDL_SetInitialized(), and SDL_ShouldInit().
Referenced by SDL_CheckInitLog().
SDL_QuitLog()
void SDL_QuitLog (void) extern
{
    if (!SDL_ShouldQuit(&SDL_log_init)) {
        return;
    }
    SDL_RemoveHintCallback(SDL_HINT_LOGGING, SDL_LoggingChanged, NULL);
    CleanupLogPriorities();
    CleanupLogPrefixes();
    if (SDL_log_lock) {
        SDL_DestroyMutex(SDL_log_lock);
        SDL_log_lock = NULL;
    }
    if (SDL_log_function_lock) {
        SDL_DestroyMutex(SDL_log_function_lock);
        SDL_log_function_lock = NULL;
    }
    SDL_SetInitialized(&SDL_log_init, false);
}
References CleanupLogPrefixes(), CleanupLogPriorities(), NULL, SDL_DestroyMutex(), SDL_HINT_LOGGING, SDL_log_function_lock, SDL_log_init, SDL_log_lock, SDL_LoggingChanged(), SDL_RemoveHintCallback(), SDL_SetInitialized(), and SDL_ShouldQuit().
Referenced by SDL_Quit().