SDL3: SDL_GPUDevice Struct Reference
SDL_GPUDevice Struct Reference
#include <SDL_sysgpu.h>
Data Fields
SDL_GPUCommandBuffer *(* AcquireCommandBuffer)(SDL_GPURenderer *driverData)
bool(* AcquireSwapchainTexture)(SDL_GPUCommandBuffer *commandBuffer, SDL_Window *window, SDL_GPUTexture **swapchainTexture, Uint32 *swapchainTextureWidth, Uint32 *swapchainTextureHeight)
const char * backend
void(* BeginComputePass)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUStorageTextureReadWriteBinding *storageTextureBindings, Uint32 numStorageTextureBindings, const SDL_GPUStorageBufferReadWriteBinding *storageBufferBindings, Uint32 numStorageBufferBindings)
void(* BeginCopyPass)(SDL_GPUCommandBuffer *commandBuffer)
void(* BeginRenderPass)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUColorTargetInfo *colorTargetInfos, Uint32 numColorTargets, const SDL_GPUDepthStencilTargetInfo *depthStencilTargetInfo)
void(* BindComputePipeline)(SDL_GPUCommandBuffer *commandBuffer, SDL_GPUComputePipeline *computePipeline)
void(* BindComputeSamplers)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUTextureSamplerBinding *textureSamplerBindings, Uint32 numBindings)
void(* BindComputeStorageBuffers)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUBuffer *const *storageBuffers, Uint32 numBindings)
void(* BindComputeStorageTextures)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUTexture *const *storageTextures, Uint32 numBindings)
void(* BindFragmentSamplers)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUTextureSamplerBinding *textureSamplerBindings, Uint32 numBindings)
void(* BindFragmentStorageBuffers)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUBuffer *const *storageBuffers, Uint32 numBindings)
void(* BindFragmentStorageTextures)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUTexture *const *storageTextures, Uint32 numBindings)
void(* BindGraphicsPipeline)(SDL_GPUCommandBuffer *commandBuffer, SDL_GPUGraphicsPipeline *graphicsPipeline)
void(* BindIndexBuffer)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBufferBinding *binding, SDL_GPUIndexElementSize indexElementSize)
void(* BindVertexBuffers)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUBufferBinding *bindings, Uint32 numBindings)
void(* BindVertexSamplers)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUTextureSamplerBinding *textureSamplerBindings, Uint32 numBindings)
void(* BindVertexStorageBuffers)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUBuffer *const *storageBuffers, Uint32 numBindings)
void(* BindVertexStorageTextures)(SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUTexture *const *storageTextures, Uint32 numBindings)
void(* Blit)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBlitInfo *info)
bool(* Cancel)(SDL_GPUCommandBuffer *commandBuffer)
bool(* ClaimWindow)(SDL_GPURenderer *driverData, SDL_Window *window)
void(* CopyBufferToBuffer)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBufferLocation *source, const SDL_GPUBufferLocation *destination, Uint32 size, bool cycle)
void(* CopyTextureToTexture)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTextureLocation *source, const SDL_GPUTextureLocation *destination, Uint32 w, Uint32 h, Uint32 d, bool cycle)
SDL_GPUBuffer *(* CreateBuffer)(SDL_GPURenderer *driverData, SDL_GPUBufferUsageFlags usageFlags, Uint32 size, const char *debugName)
SDL_GPUComputePipeline *(* CreateComputePipeline)(SDL_GPURenderer *driverData, const SDL_GPUComputePipelineCreateInfo *createinfo)
SDL_GPUGraphicsPipeline *(* CreateGraphicsPipeline)(SDL_GPURenderer *driverData, const SDL_GPUGraphicsPipelineCreateInfo *createinfo)
SDL_GPUSampler *(* CreateSampler)(SDL_GPURenderer *driverData, const SDL_GPUSamplerCreateInfo *createinfo)
SDL_GPUShader *(* CreateShader)(SDL_GPURenderer *driverData, const SDL_GPUShaderCreateInfo *createinfo)
SDL_GPUTexture *(* CreateTexture)(SDL_GPURenderer *driverData, const SDL_GPUTextureCreateInfo *createinfo)
SDL_GPUTransferBuffer *(* CreateTransferBuffer)(SDL_GPURenderer *driverData, SDL_GPUTransferBufferUsage usage, Uint32 size, const char *debugName)
bool debug_mode
void(* DestroyDevice)(SDL_GPUDevice *device)
void(* DispatchCompute)(SDL_GPUCommandBuffer *commandBuffer, Uint32 groupcountX, Uint32 groupcountY, Uint32 groupcountZ)
void(* DispatchComputeIndirect)(SDL_GPUCommandBuffer *commandBuffer, SDL_GPUBuffer *buffer, Uint32 offset)
void(* DownloadFromBuffer)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBufferRegion *source, const SDL_GPUTransferBufferLocation *destination)
void(* DownloadFromTexture)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTextureRegion *source, const SDL_GPUTextureTransferInfo *destination)
void(* DrawIndexedPrimitives)(SDL_GPUCommandBuffer *commandBuffer, Uint32 numIndices, Uint32 numInstances, Uint32 firstIndex, Sint32 vertexOffset, Uint32 firstInstance)
void(* DrawIndexedPrimitivesIndirect)(SDL_GPUCommandBuffer *commandBuffer, SDL_GPUBuffer *buffer, Uint32 offset, Uint32 drawCount)
void(* DrawPrimitives)(SDL_GPUCommandBuffer *commandBuffer, Uint32 numVertices, Uint32 numInstances, Uint32 firstVertex, Uint32 firstInstance)
void(* DrawPrimitivesIndirect)(SDL_GPUCommandBuffer *commandBuffer, SDL_GPUBuffer *buffer, Uint32 offset, Uint32 drawCount)
SDL_GPURenderer * driverData
void(* EndComputePass)(SDL_GPUCommandBuffer *commandBuffer)
void(* EndCopyPass)(SDL_GPUCommandBuffer *commandBuffer)
void(* EndRenderPass)(SDL_GPUCommandBuffer *commandBuffer)
void(* GenerateMipmaps)(SDL_GPUCommandBuffer *commandBuffer, SDL_GPUTexture *texture)
SDL_PropertiesID(* GetDeviceProperties)(SDL_GPUDevice *device)
SDL_GPUTextureFormat(* GetSwapchainTextureFormat)(SDL_GPURenderer *driverData, SDL_Window *window)
void(* InsertDebugLabel)(SDL_GPUCommandBuffer *commandBuffer, const char *text)
void *(* MapTransferBuffer)(SDL_GPURenderer *device, SDL_GPUTransferBuffer *transferBuffer, bool cycle)
void(* PopDebugGroup)(SDL_GPUCommandBuffer *commandBuffer)
void(* PushComputeUniformData)(SDL_GPUCommandBuffer *commandBuffer, Uint32 slotIndex, const void *data, Uint32 length)
void(* PushDebugGroup)(SDL_GPUCommandBuffer *commandBuffer, const char *name)
void(* PushFragmentUniformData)(SDL_GPUCommandBuffer *commandBuffer, Uint32 slotIndex, const void *data, Uint32 length)
void(* PushVertexUniformData)(SDL_GPUCommandBuffer *commandBuffer, Uint32 slotIndex, const void *data, Uint32 length)
bool(* QueryFence)(SDL_GPURenderer *driverData, SDL_GPUFence *fence)
void(* ReleaseBuffer)(SDL_GPURenderer *driverData, SDL_GPUBuffer *buffer)
void(* ReleaseComputePipeline)(SDL_GPURenderer *driverData, SDL_GPUComputePipeline *computePipeline)
void(* ReleaseFence)(SDL_GPURenderer *driverData, SDL_GPUFence *fence)
void(* ReleaseGraphicsPipeline)(SDL_GPURenderer *driverData, SDL_GPUGraphicsPipeline *graphicsPipeline)
void(* ReleaseSampler)(SDL_GPURenderer *driverData, SDL_GPUSampler *sampler)
void(* ReleaseShader)(SDL_GPURenderer *driverData, SDL_GPUShader *shader)
void(* ReleaseTexture)(SDL_GPURenderer *driverData, SDL_GPUTexture *texture)
void(* ReleaseTransferBuffer)(SDL_GPURenderer *driverData, SDL_GPUTransferBuffer *transferBuffer)
void(* ReleaseWindow)(SDL_GPURenderer *driverData, SDL_Window *window)
bool(* SetAllowedFramesInFlight)(SDL_GPURenderer *driverData, Uint32 allowedFramesInFlight)
void(* SetBlendConstants)(SDL_GPUCommandBuffer *commandBuffer, SDL_FColor blendConstants)
void(* SetBufferName)(SDL_GPURenderer *driverData, SDL_GPUBuffer *buffer, const char *text)
void(* SetScissor)(SDL_GPUCommandBuffer *commandBuffer, const SDL_Rect *scissor)
void(* SetStencilReference)(SDL_GPUCommandBuffer *commandBuffer, Uint8 reference)
bool(* SetSwapchainParameters)(SDL_GPURenderer *driverData, SDL_Window *window, SDL_GPUSwapchainComposition swapchainComposition, SDL_GPUPresentMode presentMode)
void(* SetTextureName)(SDL_GPURenderer *driverData, SDL_GPUTexture *texture, const char *text)
void(* SetViewport)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUViewport *viewport)
SDL_GPUShaderFormat shader_formats
bool(* Submit)(SDL_GPUCommandBuffer *commandBuffer)
SDL_GPUFence *(* SubmitAndAcquireFence)(SDL_GPUCommandBuffer *commandBuffer)
bool(* SupportsPresentMode)(SDL_GPURenderer *driverData, SDL_Window *window, SDL_GPUPresentMode presentMode)
bool(* SupportsSampleCount)(SDL_GPURenderer *driverData, SDL_GPUTextureFormat format, SDL_GPUSampleCount desiredSampleCount)
bool(* SupportsSwapchainComposition)(SDL_GPURenderer *driverData, SDL_Window *window, SDL_GPUSwapchainComposition swapchainComposition)
bool(* SupportsTextureFormat)(SDL_GPURenderer *driverData, SDL_GPUTextureFormat format, SDL_GPUTextureType type, SDL_GPUTextureUsageFlags usage)
void(* UnmapTransferBuffer)(SDL_GPURenderer *device, SDL_GPUTransferBuffer *transferBuffer)
void(* UploadToBuffer)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTransferBufferLocation *source, const SDL_GPUBufferRegion *destination, bool cycle)
void(* UploadToTexture)(SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTextureTransferInfo *source, const SDL_GPUTextureRegion *destination, bool cycle)
bool(* Wait)(SDL_GPURenderer *driverData)
bool(* WaitAndAcquireSwapchainTexture)(SDL_GPUCommandBuffer *commandBuffer, SDL_Window *window, SDL_GPUTexture **swapchainTexture, Uint32 *swapchainTextureWidth, Uint32 *swapchainTextureHeight)
bool(* WaitForFences)(SDL_GPURenderer *driverData, bool waitAll, SDL_GPUFence *const *fences, Uint32 numFences)
bool(* WaitForSwapchain)(SDL_GPURenderer *driverData, SDL_Window *window)
Field Documentation
AcquireCommandBuffer
SDL_GPUCommandBuffer *(* SDL_GPUDevice::AcquireCommandBuffer) (SDL_GPURenderer *driverData)
Referenced by SDL_AcquireGPUCommandBuffer().
AcquireSwapchainTexture
bool(* SDL_GPUDevice::AcquireSwapchainTexture) (SDL_GPUCommandBuffer *commandBuffer, SDL_Window *window, SDL_GPUTexture **swapchainTexture, Uint32 *swapchainTextureWidth, Uint32 *swapchainTextureHeight)
backend
const char* SDL_GPUDevice::backend
Referenced by SDL_CreateGPUDeviceWithProperties(), and SDL_GetGPUDeviceDriver().
BeginComputePass
void(* SDL_GPUDevice::BeginComputePass) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUStorageTextureReadWriteBinding *storageTextureBindings, Uint32 numStorageTextureBindings, const SDL_GPUStorageBufferReadWriteBinding *storageBufferBindings, Uint32 numStorageBufferBindings)
BeginCopyPass
void(* SDL_GPUDevice::BeginCopyPass) (SDL_GPUCommandBuffer *commandBuffer)
BeginRenderPass
void(* SDL_GPUDevice::BeginRenderPass) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUColorTargetInfo *colorTargetInfos, Uint32 numColorTargets, const SDL_GPUDepthStencilTargetInfo *depthStencilTargetInfo)
BindComputePipeline
void(* SDL_GPUDevice::BindComputePipeline) (SDL_GPUCommandBuffer *commandBuffer, SDL_GPUComputePipeline *computePipeline)
BindComputeSamplers
void(* SDL_GPUDevice::BindComputeSamplers) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUTextureSamplerBinding *textureSamplerBindings, Uint32 numBindings)
BindComputeStorageBuffers
void(* SDL_GPUDevice::BindComputeStorageBuffers) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUBuffer *const *storageBuffers, Uint32 numBindings)
BindComputeStorageTextures
void(* SDL_GPUDevice::BindComputeStorageTextures) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUTexture *const *storageTextures, Uint32 numBindings)
BindFragmentSamplers
void(* SDL_GPUDevice::BindFragmentSamplers) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUTextureSamplerBinding *textureSamplerBindings, Uint32 numBindings)
BindFragmentStorageBuffers
void(* SDL_GPUDevice::BindFragmentStorageBuffers) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUBuffer *const *storageBuffers, Uint32 numBindings)
BindFragmentStorageTextures
void(* SDL_GPUDevice::BindFragmentStorageTextures) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUTexture *const *storageTextures, Uint32 numBindings)
BindGraphicsPipeline
void(* SDL_GPUDevice::BindGraphicsPipeline) (SDL_GPUCommandBuffer *commandBuffer, SDL_GPUGraphicsPipeline *graphicsPipeline)
BindIndexBuffer
void(* SDL_GPUDevice::BindIndexBuffer) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBufferBinding *binding, SDL_GPUIndexElementSize indexElementSize)
BindVertexBuffers
void(* SDL_GPUDevice::BindVertexBuffers) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUBufferBinding *bindings, Uint32 numBindings)
BindVertexSamplers
void(* SDL_GPUDevice::BindVertexSamplers) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, const SDL_GPUTextureSamplerBinding *textureSamplerBindings, Uint32 numBindings)
BindVertexStorageBuffers
void(* SDL_GPUDevice::BindVertexStorageBuffers) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUBuffer *const *storageBuffers, Uint32 numBindings)
BindVertexStorageTextures
void(* SDL_GPUDevice::BindVertexStorageTextures) (SDL_GPUCommandBuffer *commandBuffer, Uint32 firstSlot, SDL_GPUTexture *const *storageTextures, Uint32 numBindings)
Blit
void(* SDL_GPUDevice::Blit) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBlitInfo *info)
Cancel
bool(* SDL_GPUDevice::Cancel) (SDL_GPUCommandBuffer *commandBuffer)
ClaimWindow
bool(* SDL_GPUDevice::ClaimWindow) (SDL_GPURenderer *driverData, SDL_Window *window)
Referenced by SDL_ClaimWindowForGPUDevice().
CopyBufferToBuffer
void(* SDL_GPUDevice::CopyBufferToBuffer) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBufferLocation *source, const SDL_GPUBufferLocation *destination, Uint32 size, bool cycle)
CopyTextureToTexture
void(* SDL_GPUDevice::CopyTextureToTexture) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTextureLocation *source, const SDL_GPUTextureLocation *destination, Uint32 w, Uint32 h, Uint32 d, bool cycle)
CreateBuffer
SDL_GPUBuffer *(* SDL_GPUDevice::CreateBuffer) (SDL_GPURenderer *driverData, SDL_GPUBufferUsageFlags usageFlags, Uint32 size, const char *debugName)
Referenced by SDL_CreateGPUBuffer().
CreateComputePipeline
SDL_GPUComputePipeline *(* SDL_GPUDevice::CreateComputePipeline) (SDL_GPURenderer *driverData, const SDL_GPUComputePipelineCreateInfo *createinfo)
Referenced by SDL_CreateGPUComputePipeline().
CreateGraphicsPipeline
SDL_GPUGraphicsPipeline *(* SDL_GPUDevice::CreateGraphicsPipeline) (SDL_GPURenderer *driverData, const SDL_GPUGraphicsPipelineCreateInfo *createinfo)
Referenced by SDL_CreateGPUGraphicsPipeline().
CreateSampler
SDL_GPUSampler *(* SDL_GPUDevice::CreateSampler) (SDL_GPURenderer *driverData, const SDL_GPUSamplerCreateInfo *createinfo)
Referenced by SDL_CreateGPUSampler().
CreateShader
SDL_GPUShader *(* SDL_GPUDevice::CreateShader) (SDL_GPURenderer *driverData, const SDL_GPUShaderCreateInfo *createinfo)
Referenced by SDL_CreateGPUShader().
CreateTexture
SDL_GPUTexture *(* SDL_GPUDevice::CreateTexture) (SDL_GPURenderer *driverData, const SDL_GPUTextureCreateInfo *createinfo)
Referenced by SDL_CreateGPUTexture().
CreateTransferBuffer
SDL_GPUTransferBuffer *(* SDL_GPUDevice::CreateTransferBuffer) (SDL_GPURenderer *driverData, SDL_GPUTransferBufferUsage usage, Uint32 size, const char *debugName)
Referenced by SDL_CreateGPUTransferBuffer().
debug_mode
bool SDL_GPUDevice::debug_mode
Referenced by SDL_AcquireGPUCommandBuffer(), SDL_CreateGPUComputePipeline(), SDL_CreateGPUDeviceWithProperties(), SDL_CreateGPUGraphicsPipeline(), SDL_CreateGPUShader(), SDL_CreateGPUTexture(), SDL_GPUTextureSupportsFormat(), SDL_GPUTextureSupportsSampleCount(), SDL_SetGPUAllowedFramesInFlight(), SDL_SetGPUSwapchainParameters(), SDL_WindowSupportsGPUPresentMode(), and SDL_WindowSupportsGPUSwapchainComposition().
DestroyDevice
void(* SDL_GPUDevice::DestroyDevice) (SDL_GPUDevice *device)
Referenced by SDL_DestroyGPUDevice().
DispatchCompute
void(* SDL_GPUDevice::DispatchCompute) (SDL_GPUCommandBuffer *commandBuffer, Uint32 groupcountX, Uint32 groupcountY, Uint32 groupcountZ)
DispatchComputeIndirect
void(* SDL_GPUDevice::DispatchComputeIndirect) (SDL_GPUCommandBuffer *commandBuffer, SDL_GPUBuffer *buffer, Uint32 offset)
DownloadFromBuffer
void(* SDL_GPUDevice::DownloadFromBuffer) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUBufferRegion *source, const SDL_GPUTransferBufferLocation *destination)
DownloadFromTexture
void(* SDL_GPUDevice::DownloadFromTexture) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTextureRegion *source, const SDL_GPUTextureTransferInfo *destination)
DrawIndexedPrimitives
void(* SDL_GPUDevice::DrawIndexedPrimitives) (SDL_GPUCommandBuffer *commandBuffer, Uint32 numIndices, Uint32 numInstances, Uint32 firstIndex, Sint32 vertexOffset, Uint32 firstInstance)
DrawIndexedPrimitivesIndirect
void(* SDL_GPUDevice::DrawIndexedPrimitivesIndirect) (SDL_GPUCommandBuffer *commandBuffer, SDL_GPUBuffer *buffer, Uint32 offset, Uint32 drawCount)
DrawPrimitives
void(* SDL_GPUDevice::DrawPrimitives) (SDL_GPUCommandBuffer *commandBuffer, Uint32 numVertices, Uint32 numInstances, Uint32 firstVertex, Uint32 firstInstance)
DrawPrimitivesIndirect
void(* SDL_GPUDevice::DrawPrimitivesIndirect) (SDL_GPUCommandBuffer *commandBuffer, SDL_GPUBuffer *buffer, Uint32 offset, Uint32 drawCount)
driverData
SDL_GPURenderer* SDL_GPUDevice::driverData
Referenced by SDL_AcquireGPUCommandBuffer(), SDL_ClaimWindowForGPUDevice(), SDL_CreateGPUBuffer(), SDL_CreateGPUComputePipeline(), SDL_CreateGPUGraphicsPipeline(), SDL_CreateGPUSampler(), SDL_CreateGPUShader(), SDL_CreateGPUTexture(), SDL_CreateGPUTransferBuffer(), SDL_GetGPUSwapchainTextureFormat(), SDL_GPUTextureSupportsFormat(), SDL_GPUTextureSupportsSampleCount(), SDL_MapGPUTransferBuffer(), SDL_QueryGPUFence(), SDL_ReleaseGPUBuffer(), SDL_ReleaseGPUComputePipeline(), SDL_ReleaseGPUFence(), SDL_ReleaseGPUGraphicsPipeline(), SDL_ReleaseGPUSampler(), SDL_ReleaseGPUShader(), SDL_ReleaseGPUTexture(), SDL_ReleaseGPUTransferBuffer(), SDL_ReleaseWindowFromGPUDevice(), SDL_SetGPUAllowedFramesInFlight(), SDL_SetGPUBufferName(), SDL_SetGPUSwapchainParameters(), SDL_SetGPUTextureName(), SDL_UnmapGPUTransferBuffer(), SDL_WaitForGPUFences(), SDL_WaitForGPUIdle(), SDL_WaitForGPUSwapchain(), SDL_WindowSupportsGPUPresentMode(), and SDL_WindowSupportsGPUSwapchainComposition().
EndComputePass
void(* SDL_GPUDevice::EndComputePass) (SDL_GPUCommandBuffer *commandBuffer)
EndCopyPass
void(* SDL_GPUDevice::EndCopyPass) (SDL_GPUCommandBuffer *commandBuffer)
EndRenderPass
void(* SDL_GPUDevice::EndRenderPass) (SDL_GPUCommandBuffer *commandBuffer)
GenerateMipmaps
void(* SDL_GPUDevice::GenerateMipmaps) (SDL_GPUCommandBuffer *commandBuffer, SDL_GPUTexture *texture)
GetDeviceProperties
SDL_PropertiesID(* SDL_GPUDevice::GetDeviceProperties) (SDL_GPUDevice *device)
Referenced by SDL_GetGPUDeviceProperties().
GetSwapchainTextureFormat
SDL_GPUTextureFormat(* SDL_GPUDevice::GetSwapchainTextureFormat) (SDL_GPURenderer *driverData, SDL_Window *window)
Referenced by SDL_GetGPUSwapchainTextureFormat().
InsertDebugLabel
void(* SDL_GPUDevice::InsertDebugLabel) (SDL_GPUCommandBuffer *commandBuffer, const char *text)
MapTransferBuffer
void *(* SDL_GPUDevice::MapTransferBuffer) (SDL_GPURenderer *device, SDL_GPUTransferBuffer *transferBuffer, bool cycle)
Referenced by SDL_MapGPUTransferBuffer().
PopDebugGroup
void(* SDL_GPUDevice::PopDebugGroup) (SDL_GPUCommandBuffer *commandBuffer)
PushComputeUniformData
void(* SDL_GPUDevice::PushComputeUniformData) (SDL_GPUCommandBuffer *commandBuffer, Uint32 slotIndex, const void *data, Uint32 length)
PushDebugGroup
void(* SDL_GPUDevice::PushDebugGroup) (SDL_GPUCommandBuffer *commandBuffer, const char *name)
PushFragmentUniformData
void(* SDL_GPUDevice::PushFragmentUniformData) (SDL_GPUCommandBuffer *commandBuffer, Uint32 slotIndex, const void *data, Uint32 length)
PushVertexUniformData
void(* SDL_GPUDevice::PushVertexUniformData) (SDL_GPUCommandBuffer *commandBuffer, Uint32 slotIndex, const void *data, Uint32 length)
QueryFence
bool(* SDL_GPUDevice::QueryFence) (SDL_GPURenderer *driverData, SDL_GPUFence *fence)
Referenced by SDL_QueryGPUFence().
ReleaseBuffer
void(* SDL_GPUDevice::ReleaseBuffer) (SDL_GPURenderer *driverData, SDL_GPUBuffer *buffer)
Referenced by SDL_ReleaseGPUBuffer().
ReleaseComputePipeline
void(* SDL_GPUDevice::ReleaseComputePipeline) (SDL_GPURenderer *driverData, SDL_GPUComputePipeline *computePipeline)
Referenced by SDL_ReleaseGPUComputePipeline().
ReleaseFence
void(* SDL_GPUDevice::ReleaseFence) (SDL_GPURenderer *driverData, SDL_GPUFence *fence)
Referenced by SDL_ReleaseGPUFence().
ReleaseGraphicsPipeline
void(* SDL_GPUDevice::ReleaseGraphicsPipeline) (SDL_GPURenderer *driverData, SDL_GPUGraphicsPipeline *graphicsPipeline)
Referenced by SDL_ReleaseGPUGraphicsPipeline().
ReleaseSampler
void(* SDL_GPUDevice::ReleaseSampler) (SDL_GPURenderer *driverData, SDL_GPUSampler *sampler)
Referenced by SDL_ReleaseGPUSampler().
ReleaseShader
void(* SDL_GPUDevice::ReleaseShader) (SDL_GPURenderer *driverData, SDL_GPUShader *shader)
Referenced by SDL_ReleaseGPUShader().
ReleaseTexture
void(* SDL_GPUDevice::ReleaseTexture) (SDL_GPURenderer *driverData, SDL_GPUTexture *texture)
Referenced by SDL_ReleaseGPUTexture().
ReleaseTransferBuffer
void(* SDL_GPUDevice::ReleaseTransferBuffer) (SDL_GPURenderer *driverData, SDL_GPUTransferBuffer *transferBuffer)
Referenced by SDL_ReleaseGPUTransferBuffer().
ReleaseWindow
void(* SDL_GPUDevice::ReleaseWindow) (SDL_GPURenderer *driverData, SDL_Window *window)
Referenced by SDL_ReleaseWindowFromGPUDevice().
SetAllowedFramesInFlight
bool(* SDL_GPUDevice::SetAllowedFramesInFlight) (SDL_GPURenderer *driverData, Uint32 allowedFramesInFlight)
Referenced by SDL_SetGPUAllowedFramesInFlight().
SetBlendConstants
void(* SDL_GPUDevice::SetBlendConstants) (SDL_GPUCommandBuffer *commandBuffer, SDL_FColor blendConstants)
SetBufferName
void(* SDL_GPUDevice::SetBufferName) (SDL_GPURenderer *driverData, SDL_GPUBuffer *buffer, const char *text)
Referenced by SDL_SetGPUBufferName().
SetScissor
void(* SDL_GPUDevice::SetScissor) (SDL_GPUCommandBuffer *commandBuffer, const SDL_Rect *scissor)
SetStencilReference
void(* SDL_GPUDevice::SetStencilReference) (SDL_GPUCommandBuffer *commandBuffer, Uint8 reference)
SetSwapchainParameters
bool(* SDL_GPUDevice::SetSwapchainParameters) (SDL_GPURenderer *driverData, SDL_Window *window, SDL_GPUSwapchainComposition swapchainComposition, SDL_GPUPresentMode presentMode)
Referenced by SDL_SetGPUSwapchainParameters().
SetTextureName
void(* SDL_GPUDevice::SetTextureName) (SDL_GPURenderer *driverData, SDL_GPUTexture *texture, const char *text)
Referenced by SDL_SetGPUTextureName().
SetViewport
void(* SDL_GPUDevice::SetViewport) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUViewport *viewport)
shader_formats
SDL_GPUShaderFormat SDL_GPUDevice::shader_formats
Referenced by SDL_CreateGPUComputePipeline(), SDL_CreateGPUShader(), and SDL_GetGPUShaderFormats().
Submit
bool(* SDL_GPUDevice::Submit) (SDL_GPUCommandBuffer *commandBuffer)
SubmitAndAcquireFence
SDL_GPUFence *(* SDL_GPUDevice::SubmitAndAcquireFence) (SDL_GPUCommandBuffer *commandBuffer)
SupportsPresentMode
bool(* SDL_GPUDevice::SupportsPresentMode) (SDL_GPURenderer *driverData, SDL_Window *window, SDL_GPUPresentMode presentMode)
Referenced by SDL_WindowSupportsGPUPresentMode().
SupportsSampleCount
bool(* SDL_GPUDevice::SupportsSampleCount) (SDL_GPURenderer *driverData, SDL_GPUTextureFormat format, SDL_GPUSampleCount desiredSampleCount)
Referenced by SDL_GPUTextureSupportsSampleCount().
SupportsSwapchainComposition
bool(* SDL_GPUDevice::SupportsSwapchainComposition) (SDL_GPURenderer *driverData, SDL_Window *window, SDL_GPUSwapchainComposition swapchainComposition)
Referenced by SDL_WindowSupportsGPUSwapchainComposition().
SupportsTextureFormat
bool(* SDL_GPUDevice::SupportsTextureFormat) (SDL_GPURenderer *driverData, SDL_GPUTextureFormat format, SDL_GPUTextureType type, SDL_GPUTextureUsageFlags usage)
Referenced by SDL_GPUTextureSupportsFormat().
UnmapTransferBuffer
void(* SDL_GPUDevice::UnmapTransferBuffer) (SDL_GPURenderer *device, SDL_GPUTransferBuffer *transferBuffer)
Referenced by SDL_UnmapGPUTransferBuffer().
UploadToBuffer
void(* SDL_GPUDevice::UploadToBuffer) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTransferBufferLocation *source, const SDL_GPUBufferRegion *destination, bool cycle)
UploadToTexture
void(* SDL_GPUDevice::UploadToTexture) (SDL_GPUCommandBuffer *commandBuffer, const SDL_GPUTextureTransferInfo *source, const SDL_GPUTextureRegion *destination, bool cycle)
Wait
bool(* SDL_GPUDevice::Wait) (SDL_GPURenderer *driverData)
Referenced by SDL_WaitForGPUIdle().
WaitAndAcquireSwapchainTexture
bool(* SDL_GPUDevice::WaitAndAcquireSwapchainTexture) (SDL_GPUCommandBuffer *commandBuffer, SDL_Window *window, SDL_GPUTexture **swapchainTexture, Uint32 *swapchainTextureWidth, Uint32 *swapchainTextureHeight)
WaitForFences
bool(* SDL_GPUDevice::WaitForFences) (SDL_GPURenderer *driverData, bool waitAll, SDL_GPUFence *const *fences, Uint32 numFences)
Referenced by SDL_WaitForGPUFences().
WaitForSwapchain
bool(* SDL_GPUDevice::WaitForSwapchain) (SDL_GPURenderer *driverData, SDL_Window *window)
Referenced by SDL_WaitForGPUSwapchain().
The documentation for this struct was generated from the following file:
SDL-main/src/gpu/SDL_sysgpu.h