SDL3: SDL-main/src/stdlib/SDL_getenv.c File Reference
SDL_getenv.c File Reference
#include "SDL_internal.h"
#include "SDL_getenv_c.h"
Data Structures
struct CopyEnvStringsData
struct CountEnvStringsData
struct SDL_Environment
Macros
#define HAVE_LOCAL_ENVIRONMENT
Typedefs
typedef struct CopyEnvStringsData CopyEnvStringsData
typedef struct CountEnvStringsData CountEnvStringsData
Functions
static bool SDLCALL CopyEnvStrings (void *userdata, const SDL_HashTable *table, const void *vkey, const void *vvalue)
static bool SDLCALL CountEnvStrings (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
SDL_Environment * SDL_CreateEnvironment (bool populated)
void SDL_DestroyEnvironment (SDL_Environment *env)
const char * SDL_getenv (const char *name)
const char * SDL_getenv_unsafe (const char *name)
SDL_Environment * SDL_GetEnvironment (void)
const char * SDL_GetEnvironmentVariable (SDL_Environment *env, const char *name)
char ** SDL_GetEnvironmentVariables (SDL_Environment *env)
bool SDL_InitEnvironment (void)
void SDL_QuitEnvironment (void)
int SDL_setenv_unsafe (const char *name, const char *value, int overwrite)
bool SDL_SetEnvironmentVariable (SDL_Environment *env, const char *name, const char *value, bool overwrite)
int SDL_unsetenv_unsafe (const char *name)
bool SDL_UnsetEnvironmentVariable (SDL_Environment *env, const char *name)
Variables
static char ** environ
static SDL_Environment * SDL_environment
Macro Definition Documentation
HAVE_LOCAL_ENVIRONMENT
#define HAVE_LOCAL_ENVIRONMENT
Typedef Documentation
CopyEnvStringsData
typedef struct CopyEnvStringsData CopyEnvStringsData
CountEnvStringsData
typedef struct CountEnvStringsData CountEnvStringsData
Function Documentation
CopyEnvStrings()
bool SDLCALL CopyEnvStrings (void * userdata, const SDL_HashTable * table, const void * vkey, const void * vvalue) static
{
    CopyEnvStringsData *data = (CopyEnvStringsData *) userdata;
    const char *key = (const char *) vkey;
    const char *value = (const char *) vvalue;
    size_t len;
    len = SDL_strlen(key);
    data->result[data->count] = data->string;
    SDL_memcpy(data->string, key, len);
    data->string += len;
    *(data->string++) = '=';
    len = SDL_strlen(value);
    SDL_memcpy(data->string, value, len);
    data->string += len;
    *(data->string++) = '\0';
    data->count++;
    return true;  // keep iterating.
}
References SDL_memcpy, SDL_strlen(), and SDLCALL.
Referenced by SDL_GetEnvironmentVariables().
CountEnvStrings()
bool SDLCALL CountEnvStrings (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    CountEnvStringsData *data = (CountEnvStringsData *) userdata;
    data->length += SDL_strlen((const char *) key) + 1 + SDL_strlen((const char *) value) + 1;
    data->count++;
    return true;  // keep iterating.
}
References SDL_strlen(), and SDLCALL.
Referenced by SDL_GetEnvironmentVariables().
SDL_CreateEnvironment()
SDL_Environment * SDL_CreateEnvironment (bool populated)
{
    SDL_Environment *env = SDL_calloc(1, sizeof(*env));
    if (!env) {
        return NULL;
    }
    env->strings = SDL_CreateHashTable(0, false, SDL_HashString, SDL_KeyMatchString, SDL_DestroyHashKey, NULL);
    if (!env->strings) {
        SDL_free(env);
        return NULL;
    }
    // Don't fail if we can't create a mutex (e.g. on a single-thread environment)  // !!! FIXME: single-threaded environments should still return a non-NULL, do-nothing object here. Check for failure!
    env->lock = SDL_CreateMutex();
    if (populated) {
#ifdef SDL_PLATFORM_WINDOWS
        LPWCH strings = GetEnvironmentStringsW();
        if (strings) {
            for (LPWCH string = strings; *string; string += SDL_wcslen(string) + 1) {
                char *variable = WIN_StringToUTF8W(string);
                if (!variable) {
                    continue;
                }
                char *value = SDL_strchr(variable, '=');
                if (!value || value == variable) {
                    SDL_free(variable);
                    continue;
                }
                *value++ = '\0';
                SDL_InsertIntoHashTable(env->strings, variable, value, true);
            }
            FreeEnvironmentStringsW(strings);
        }
#else
#ifdef SDL_PLATFORM_ANDROID
        // Make sure variables from the application manifest are available
        Android_JNI_GetManifestEnvironmentVariables();
#endif
        char **strings = environ;
        if (strings) {
            for (int i = 0; strings[i]; ++i) {
                char *variable = SDL_strdup(strings[i]);
                if (!variable) {
                    continue;
                }
                char *value = SDL_strchr(variable, '=');
                if (!value || value == variable) {
                    SDL_free(variable);
                    continue;
                }
                *value++ = '\0';
                SDL_InsertIntoHashTable(env->strings, variable, value, true);
            }
        }
#endif // SDL_PLATFORM_WINDOWS
    }
    return env;
}
References Android_JNI_GetManifestEnvironmentVariables(), environ, SDL_Environment::lock, NULL, SDL_calloc(), SDL_CreateHashTable(), SDL_CreateMutex(), SDL_DestroyHashKey(), SDL_free(), SDL_HashString(), SDL_InsertIntoHashTable(), SDL_KeyMatchString(), SDL_strchr(), SDL_strdup(), SDL_wcslen(), SDL_Environment::strings, and WIN_StringToUTF8W.
Referenced by SDL_GetEnvironment().
SDL_DestroyEnvironment()
void SDL_DestroyEnvironment (SDL_Environment * env)
Destroy a set of environment variables.
Parameters
env the environment to destroy.
Thread Safety
It is safe to call this function from any thread, as long as the environment is no longer in use.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateEnvironment
{
    if (!env || env == SDL_environment) {
        return;
    }
    SDL_DestroyMutex(env->lock);
    SDL_DestroyHashTable(env->strings);
    SDL_free(env);
}
References SDL_Environment::lock, SDL_DestroyHashTable(), SDL_DestroyMutex(), SDL_environment, SDL_free(), and SDL_Environment::strings.
Referenced by run_zenity(), SDL_QuitEnvironment(), SDL_SetEnvironmentVariable(), and SDL_SYS_OpenURL().
SDL_getenv()
const char * SDL_getenv (const char * name)
Get the value of a variable in the environment.
This function uses SDL's cached copy of the environment and is thread-safe.
Parameters
name the name of the variable to get.
Returns
a pointer to the value of the variable or NULL if it can't be found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return SDL_GetEnvironmentVariable(SDL_GetEnvironment(), name);
}
References SDL_GetEnvironment(), and SDL_GetEnvironmentVariable().
Referenced by GetHintEnvironmentVariable(), getlocale(), InitIME(), SDL_DetectSandbox(), SDL_SetEnvironmentVariable(), SDL_SetHapticGain(), and SDL_SYS_GetPreferredLocales().
SDL_getenv_unsafe()
const char * SDL_getenv_unsafe (const char * name)
Get the value of a variable in the environment.
This function bypasses SDL's cached copy of the environment and is not thread-safe.
Parameters
name the name of the variable to get.
Returns
a pointer to the value of the variable or NULL if it can't be found.
Thread Safety
This function is not thread safe, consider using SDL_getenv() instead.
Since
This function is available since SDL 3.2.0.
See also
SDL_getenv
{
    size_t len, i;
    const char *value = NULL;
    // Input validation
    if (!name || *name == '\0') {
        return NULL;
    }
    if (environ) {
        len = SDL_strlen(name);
        for (i = 0; environ[i]; ++i) {
            if ((SDL_strncmp(environ[i], name, len) == 0) &&
                (environ[i][len] == '=')) {
                value = &environ[i][len + 1];
                break;
            }
        }
    }
    return value;
}
References environ, NULL, SDL_strlen(), and SDL_strncmp().
Referenced by SDL_setenv_unsafe(), and SDL_SetEnvironmentVariable().
SDL_GetEnvironment()
SDL_Environment * SDL_GetEnvironment (void)
Get the process environment.
This is initialized at application start and is not affected by setenv() and unsetenv() calls after that point. Use SDL_SetEnvironmentVariable() and SDL_UnsetEnvironmentVariable() if you want to modify this environment, or SDL_setenv_unsafe() or SDL_unsetenv_unsafe() if you want changes to persist in the C runtime environment after SDL_Quit().
Returns
a pointer to the environment for the process or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironmentVariable
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    if (!SDL_environment) {
        SDL_environment = SDL_CreateEnvironment(true);
    }
    return SDL_environment;
}
References SDL_CreateEnvironment(), and SDL_environment.
Referenced by SDL_getenv(), SDL_InitEnvironment(), SDL_setenv_unsafe(), and SDL_unsetenv_unsafe().
SDL_GetEnvironmentVariable()
const char * SDL_GetEnvironmentVariable (SDL_Environment * env, const char * name)
Get the value of a variable in the environment.
Parameters
env the environment to query.
name the name of the variable to get.
Returns
a pointer to the value of the variable or NULL if it can't be found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    const char *result = NULL;
    if (!env) {
        return NULL;
    } else if (!name || *name == '\0') {
        return NULL;
    }
    SDL_LockMutex(env->lock);
    {
        const char *value;
        if (SDL_FindInHashTable(env->strings, name, (const void **)&value)) {
            result = SDL_GetPersistentString(value);
        }
    }
    SDL_UnlockMutex(env->lock);
    return result;
}
References SDL_Environment::lock, NULL, SDL_FindInHashTable(), SDL_GetPersistentString(), SDL_LockMutex(), SDL_UnlockMutex(), and SDL_Environment::strings.
Referenced by SDL_CreateEnvironment(), and SDL_getenv().
SDL_GetEnvironmentVariables()
char ** SDL_GetEnvironmentVariables (SDL_Environment * env)
Get all variables in the environment.
Parameters
env the environment to query.
Returns
a NULL terminated array of pointers to environment variables in the form "variable=value" or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    char **result = NULL;
    if (!env) {
        SDL_InvalidParamError("env");
        return NULL;
    }
    SDL_LockMutex(env->lock);
    {
        // First pass, get the size we need for all the strings
        CountEnvStringsData countdata = { 0, 0 };
        SDL_IterateHashTable(env->strings, CountEnvStrings, &countdata);
        // Allocate memory for the strings
        result = (char **)SDL_malloc((countdata.count + 1) * sizeof(*result) + countdata.length);
        if (result) {
            // Second pass, copy the strings
            char *string = (char *)(result + countdata.count + 1);
            CopyEnvStringsData cpydata = { result, string, 0 };
            SDL_IterateHashTable(env->strings, CopyEnvStrings, &cpydata);
            SDL_assert(countdata.count == cpydata.count);
            result[cpydata.count] = NULL;
        }
    }
    SDL_UnlockMutex(env->lock);
    return result;
}
References CopyEnvStrings(), CopyEnvStringsData::count, CountEnvStringsData::count, CountEnvStrings(), CountEnvStringsData::length, SDL_Environment::lock, NULL, SDL_assert, SDL_InvalidParamError, SDL_IterateHashTable(), SDL_LockMutex(), SDL_malloc(), SDL_UnlockMutex(), and SDL_Environment::strings.
Referenced by SDL_CreateEnvironment().
SDL_InitEnvironment()
bool SDL_InitEnvironment (void)
{
    return (SDL_GetEnvironment() != NULL);
}
References NULL, and SDL_GetEnvironment().
Referenced by SDL_InitMainThread().
SDL_QuitEnvironment()
void SDL_QuitEnvironment (void)
{
    SDL_Environment *env = SDL_environment;
    if (env) {
        SDL_environment = NULL;
        SDL_DestroyEnvironment(env);
    }
}
References NULL, SDL_DestroyEnvironment(), and SDL_environment.
Referenced by SDL_QuitMainThread().
SDL_setenv_unsafe()
int SDL_setenv_unsafe (const char * name, const char * value, int overwrite)
Set the value of a variable in the environment.
Parameters
name the name of the variable to set.
value the value of the variable to set.
overwrite 1 to overwrite the variable if it exists, 0 to return success without setting the variable if it already exists.
Returns
0 on success, -1 on error.
Thread Safety
This function is not thread safe, consider using SDL_SetEnvironmentVariable() instead.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetEnvironmentVariable
{
    int added;
    size_t len, i;
    char **new_env;
    char *new_variable;
    // Input validation
    if (!name || *name == '\0' || SDL_strchr(name, '=') != NULL || !value) {
        return -1;
    }
    // See if it already exists
    if (!overwrite && SDL_getenv_unsafe(name)) {
        return 0;
    }
    SDL_SetEnvironmentVariable(SDL_GetEnvironment(), name, value, (overwrite != 0));
    // Allocate memory for the variable
    len = SDL_strlen(name) + SDL_strlen(value) + 2;
    new_variable = (char *)SDL_malloc(len);
    if (!new_variable) {
        return -1;
    }
    SDL_snprintf(new_variable, len, "%s=%s", name, value);
    value = new_variable + SDL_strlen(name) + 1;
    name = new_variable;
    // Actually put it into the environment
    added = 0;
    i = 0;
    if (environ) {
        // Check to see if it's already there...
        len = (value - name);
        for (; environ[i]; ++i) {
            if (SDL_strncmp(environ[i], name, len) == 0) {
                // If we found it, just replace the entry
                SDL_free(environ[i]);
                environ[i] = new_variable;
                added = 1;
                break;
            }
        }
    }
    // Didn't find it in the environment, expand and add
    if (!added) {
        new_env = SDL_realloc(environ, (i + 2) * sizeof(char *));
        if (new_env) {
            environ = new_env;
            environ[i++] = new_variable;
            environ[i++] = (char *)0;
            added = 1;
        } else {
            SDL_free(new_variable);
        }
    }
    return added ? 0 : -1;
}
References environ, NULL, SDL_free(), SDL_getenv_unsafe(), SDL_GetEnvironment(), SDL_malloc(), SDL_realloc(), SDL_SetEnvironmentVariable(), SDL_snprintf(), SDL_strchr(), SDL_strlen(), and SDL_strncmp().
Referenced by SDL_SetEnvironmentVariable().
SDL_SetEnvironmentVariable()
bool SDL_SetEnvironmentVariable (SDL_Environment * env, const char * name, const char * value, bool overwrite)
{
    bool result = false;
    if (!env) {
        return SDL_InvalidParamError("env");
    } else if (!name || *name == '\0' || SDL_strchr(name, '=') != NULL) {
        return SDL_InvalidParamError("name");
    } else if (!value) {
        return SDL_InvalidParamError("value");
    }
    SDL_LockMutex(env->lock);
    {
        char *string = NULL;
        if (SDL_asprintf(&string, "%s=%s", name, value) > 0) {
            const size_t len = SDL_strlen(name);
            string[len] = '\0';
            const char *origname = name;
            name = string;
            value = string + len + 1;
            result = SDL_InsertIntoHashTable(env->strings, name, value, overwrite);
            if (!result) {
                SDL_free(string);
                if (!overwrite) {
                    const void *existing_value = NULL;
                    // !!! FIXME: InsertIntoHashTable does this lookup too, maybe we should have a means to report that, to avoid duplicate work?
                    if (SDL_FindInHashTable(env->strings, origname, &existing_value)) {
                        result = true;  // it already existed, and we refused to overwrite it. Call it success.
                    }
                }
            }
        }
    }
    SDL_UnlockMutex(env->lock);
    return result;
}
References SDL_Environment::lock, NULL, SDL_asprintf(), SDL_FindInHashTable(), SDL_free(), SDL_InsertIntoHashTable(), SDL_InvalidParamError, SDL_LockMutex(), SDL_strchr(), SDL_strlen(), SDL_UnlockMutex(), and SDL_Environment::strings.
Referenced by SDL_setenv_unsafe().
SDL_unsetenv_unsafe()
int SDL_unsetenv_unsafe (const char * name)
Clear a variable from the environment.
Parameters
name the name of the variable to unset.
Returns
0 on success, -1 on error.
Thread Safety
This function is not thread safe, consider using SDL_UnsetEnvironmentVariable() instead.
Since
This function is available since SDL 3.2.0.
See also
SDL_UnsetEnvironmentVariable
{
    size_t len, i;
    // Input validation
    if (!name || *name == '\0' || SDL_strchr(name, '=') != NULL) {
        return -1;
    }
    SDL_UnsetEnvironmentVariable(SDL_GetEnvironment(), name);
    if (environ) {
        len = SDL_strlen(name);
        for (i = 0; environ[i]; ++i) {
            if ((SDL_strncmp(environ[i], name, len) == 0) &&
                (environ[i][len] == '=')) {
                // Just clear out this entry for now
                *environ[i] = '\0';
                break;
            }
        }
    }
    return 0;
}
References environ, NULL, SDL_GetEnvironment(), SDL_strchr(), SDL_strlen(), SDL_strncmp(), and SDL_UnsetEnvironmentVariable().
Referenced by SDL_SetEnvironmentVariable().
SDL_UnsetEnvironmentVariable()
bool SDL_UnsetEnvironmentVariable (SDL_Environment * env, const char * name)
Clear a variable from the environment.
Parameters
env the environment to modify.
name the name of the variable to unset.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEnvironment
SDL_CreateEnvironment
SDL_GetEnvironmentVariable
SDL_GetEnvironmentVariables
SDL_SetEnvironmentVariable
SDL_UnsetEnvironmentVariable
{
    bool result = false;
    if (!env) {
        return SDL_InvalidParamError("env");
    } else if (!name || *name == '\0' || SDL_strchr(name, '=') != NULL) {
        return SDL_InvalidParamError("name");
    }
    SDL_LockMutex(env->lock);
    {
        const void *value;
        if (SDL_FindInHashTable(env->strings, name, &value)) {
            result = SDL_RemoveFromHashTable(env->strings, name);
        } else {
            result = true;
        }
    }
    SDL_UnlockMutex(env->lock);
    return result;
}
References SDL_Environment::lock, NULL, SDL_FindInHashTable(), SDL_InvalidParamError, SDL_LockMutex(), SDL_RemoveFromHashTable(), SDL_strchr(), SDL_UnlockMutex(), and SDL_Environment::strings.
Referenced by SDL_SetEnvironmentVariable(), SDL_SYS_OpenURL(), and SDL_unsetenv_unsafe().
Variable Documentation
environ
char** environ static
Referenced by SDL_CreateEnvironment(), SDL_getenv_unsafe(), SDL_setenv_unsafe(), and SDL_unsetenv_unsafe().
SDL_environment
SDL_Environment* SDL_environment static
Referenced by SDL_DestroyEnvironment(), SDL_GetEnvironment(), and SDL_QuitEnvironment().