SDL3: SDL-main/src/video/qnx/SDL_qnxvideo.c File Reference
SDL_qnxvideo.c File Reference
#include "../../SDL_internal.h"
#include "../SDL_sysvideo.h"
#include "../../events/SDL_keyboard_c.h"
#include "../../events/SDL_mouse_c.h"
#include "SDL_qnx.h"
Functions
static SDL_VideoDevice * createDevice (void)
static bool createWindow (SDL_VideoDevice *_this, SDL_Window *window)
static bool createWindowFramebuffer (SDL_VideoDevice *_this, SDL_Window *window, SDL_PixelFormat *format, void **pixels, int *pitch)
static void deleteDevice (SDL_VideoDevice *device)
static void destroyWindow (SDL_VideoDevice *_this, SDL_Window *window)
static void hideWindow (SDL_VideoDevice *_this, SDL_Window *window)
static void pumpEvents (SDL_VideoDevice *_this)
static void setWindowSize (SDL_VideoDevice *_this, SDL_Window *window)
static void showWindow (SDL_VideoDevice *_this, SDL_Window *window)
static bool updateWindowFramebuffer (SDL_VideoDevice *_this, SDL_Window *window, const SDL_Rect *rects, int numrects)
static bool videoInit (SDL_VideoDevice *_this)
static void videoQuit (SDL_VideoDevice *_this)
Variables
static screen_context_t context
static screen_event_t event
VideoBootStrap QNX_bootstrap
Function Documentation
createDevice()
SDL_VideoDevice * createDevice (void) static
Creates the QNX video plugin used by SDL.
Returns
Initialized device if successful, NULL otherwise
{
    SDL_VideoDevice *device;
    device = (SDL_VideoDevice *)SDL_calloc(1, sizeof(SDL_VideoDevice));
    if (!device) {
        return NULL;
    }
    device->internal = NULL;
    device->VideoInit = videoInit;
    device->VideoQuit = videoQuit;
    device->CreateSDLWindow = createWindow;
    device->CreateWindowFramebuffer = createWindowFramebuffer;
    device->UpdateWindowFramebuffer = updateWindowFramebuffer;
    device->SetWindowSize = setWindowSize;
    device->ShowWindow = showWindow;
    device->HideWindow = hideWindow;
    device->PumpEvents = pumpEvents;
    device->DestroyWindow = destroyWindow;
    device->GL_LoadLibrary = glLoadLibrary;
    device->GL_GetProcAddress = glGetProcAddress;
    device->GL_CreateContext = glCreateContext;
    device->GL_SetSwapInterval = glSetSwapInterval;
    device->GL_SwapWindow = glSwapWindow;
    device->GL_MakeCurrent = glMakeCurrent;
    device->GL_DestroyContext = glDeleteContext;
    device->GL_UnloadLibrary = glUnloadLibrary;
    device->free = deleteDevice;
    return device;
}
References SDL_VideoDevice::CreateSDLWindow, createWindow(), SDL_VideoDevice::CreateWindowFramebuffer, createWindowFramebuffer(), deleteDevice(), SDL_VideoDevice::DestroyWindow, destroyWindow(), SDL_VideoDevice::free, SDL_VideoDevice::GL_CreateContext, SDL_VideoDevice::GL_DestroyContext, SDL_VideoDevice::GL_GetProcAddress, SDL_VideoDevice::GL_LoadLibrary, SDL_VideoDevice::GL_MakeCurrent, SDL_VideoDevice::GL_SetSwapInterval, SDL_VideoDevice::GL_SwapWindow, SDL_VideoDevice::GL_UnloadLibrary, glCreateContext(), glDeleteContext(), glGetProcAddress(), glLoadLibrary(), glMakeCurrent(), glSetSwapInterval(), glSwapWindow(), glUnloadLibrary(), SDL_VideoDevice::HideWindow, hideWindow(), SDL_VideoDevice::internal, NULL, SDL_VideoDevice::PumpEvents, pumpEvents(), SDL_calloc(), SDL_VideoDevice::SetWindowSize, setWindowSize(), SDL_VideoDevice::ShowWindow, showWindow(), SDL_VideoDevice::UpdateWindowFramebuffer, updateWindowFramebuffer(), SDL_VideoDevice::VideoInit, videoInit(), SDL_VideoDevice::VideoQuit, and videoQuit().
createWindow()
bool createWindow (SDL_VideoDevice * _this, SDL_Window * window) static
Creates a new native Screen window and associates it with the given SDL window.
Parameters
SDL_VideoDevice *_this
window SDL window to initialize
Returns
0 if successful, -1 on error
{
    window_impl_t   *impl;
    int             size[2];
    int             numbufs;
    int             format;
    int             usage;
    impl = SDL_calloc(1, sizeof(*impl));
    if (!impl) {
        return false;
    }
    // Create a native window.
    if (screen_create_window(&impl->window, context) < 0) {
        goto fail;
    }
    // Set the native window's size to match the SDL window.
    size[0] = window->w;
    size[1] = window->h;
    if (screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_SIZE,
                                      size) < 0) {
        goto fail;
    }
    if (screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_SOURCE_SIZE,
                                      size) < 0) {
        goto fail;
    }
    // Create window buffer(s).
    if (window->flags & SDL_WINDOW_OPENGL) {
        if (glGetConfig(&impl->conf, &format) < 0) {
            goto fail;
        }
        numbufs = 2;
        usage = SCREEN_USAGE_OPENGL_ES2;
        if (screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_USAGE,
                                          &usage) < 0) {
            return false;
        }
    } else {
        format = SCREEN_FORMAT_RGBX8888;
        numbufs = 1;
    }
    // Set pixel format.
    if (screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_FORMAT,
                                      &format) < 0) {
        goto fail;
    }
    // Create buffer(s).
    if (screen_create_window_buffers(impl->window, numbufs) < 0) {
        goto fail;
    }
    window->internal = impl;
    return true;
fail:
    if (impl->window) {
        screen_destroy_window(impl->window);
    }
    SDL_free(impl);
    return false;
}
References _this, window_impl_t::conf, context, glGetConfig(), SDL_calloc(), SDL_free(), SDL_WINDOW_OPENGL, and window_impl_t::window.
Referenced by createDevice().
createWindowFramebuffer()
bool createWindowFramebuffer (SDL_VideoDevice * _this, SDL_Window * window, SDL_PixelFormat * format, void ** pixels, int * pitch) static
Gets a pointer to the Screen buffer associated with the given window. Note that the buffer is actually created in createWindow().
Parameters
SDL_VideoDevice *_this
window SDL window to get the buffer for
[out] pixles Holds a pointer to the window's buffer
[out] format Holds the pixel format for the buffer
[out] pitch Holds the number of bytes per line
Returns
0 if successful, -1 on error
{
    window_impl_t   *impl = (window_impl_t *)window->internal;
    screen_buffer_t buffer;
    // Get a pointer to the buffer's memory.
    if (screen_get_window_property_pv(impl->window, SCREEN_PROPERTY_BUFFERS,
                                      (void **)&buffer) < 0) {
        return false;
    }
    if (screen_get_buffer_property_pv(buffer, SCREEN_PROPERTY_POINTER,
                                      pixels) < 0) {
        return false;
    }
    // Set format and pitch.
    if (screen_get_buffer_property_iv(buffer, SCREEN_PROPERTY_STRIDE,
                                      pitch) < 0) {
        return false;
    }
    *format = SDL_PIXELFORMAT_XRGB8888;
    return true;
}
References _this, SDL_PIXELFORMAT_XRGB8888, and window_impl_t::window.
Referenced by createDevice().
deleteDevice()
void deleteDevice (SDL_VideoDevice * device) static
Frees the plugin object created by createDevice().
Parameters
device Plugin object to free
{
    SDL_free(device);
}
References SDL_free().
Referenced by createDevice().
destroyWindow()
void destroyWindow (SDL_VideoDevice * _this, SDL_Window * window) static
Destroys the native window associated with the given SDL window.
Parameters
SDL_VideoDevice *_this
window SDL window that is being destroyed
{
    window_impl_t   *impl = (window_impl_t *)window->internal;
    if (impl) {
        screen_destroy_window(impl->window);
        window->internal = NULL;
    }
}
References _this, NULL, and window_impl_t::window.
Referenced by createDevice().
hideWindow()
void hideWindow (SDL_VideoDevice * _this, SDL_Window * window) static
Makes the native window associated with the given SDL window invisible.
Parameters
SDL_VideoDevice *_this
window SDL window to update
{
    window_impl_t   *impl = (window_impl_t *)window->internal;
    const int       visible = 0;
    screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_VISIBLE,
        &visible);
}
References _this, and window_impl_t::window.
Referenced by createDevice().
pumpEvents()
void pumpEvents (SDL_VideoDevice * _this) static
Runs the main event loop.
Parameters
SDL_VideoDevice *_this
{
    int             type;
    for (;;) {
        if (screen_get_event(context, event, 0) < 0) {
            break;
        }
        if (screen_get_event_property_iv(event, SCREEN_PROPERTY_TYPE, &type)
            < 0) {
            break;
        }
        if (type == SCREEN_EVENT_NONE) {
            break;
        }
        switch (type) {
        case SCREEN_EVENT_KEYBOARD:
            handleKeyboardEvent(event);
            break;
        default:
            break;
        }
    }
}
References _this, context, and handleKeyboardEvent().
Referenced by createDevice().
setWindowSize()
void setWindowSize (SDL_VideoDevice * _this, SDL_Window * window) static
Updates the size of the native window using the geometry of the SDL window.
Parameters
SDL_VideoDevice *_this
window SDL window to update
{
    window_impl_t   *impl = (window_impl_t *)window->internal;
    int             size[2];
    size[0] = window->pending.w;
    size[1] = window->pending.h;
    screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_SIZE, size);
    screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_SOURCE_SIZE, size);
}
References _this, and window_impl_t::window.
Referenced by createDevice().
showWindow()
void showWindow (SDL_VideoDevice * _this, SDL_Window * window) static
Makes the native window associated with the given SDL window visible.
Parameters
SDL_VideoDevice *_this
window SDL window to update
{
    window_impl_t   *impl = (window_impl_t *)window->internal;
    const int       visible = 1;
    screen_set_window_property_iv(impl->window, SCREEN_PROPERTY_VISIBLE,
                                  &visible);
}
References _this, and window_impl_t::window.
Referenced by createDevice().
updateWindowFramebuffer()
bool updateWindowFramebuffer (SDL_VideoDevice * _this, SDL_Window * window, const SDL_Rect * rects, int numrects) static
Informs the window manager that the window needs to be updated.
Parameters
SDL_VideoDevice *_this
window The window to update
rects An array of reectangular areas to update
numrects Rect array length
Returns
0 if successful, -1 on error
{
    window_impl_t   *impl = (window_impl_t *)window->internal;
    screen_buffer_t buffer;
    if (screen_get_window_property_pv(impl->window, SCREEN_PROPERTY_BUFFERS,
                                      (void **)&buffer) < 0) {
        return false;
    }
    screen_post_window(impl->window, buffer, numrects, (int *)rects, 0);
    screen_flush_context(context, 0);
    return true;
}
References _this, context, and window_impl_t::window.
Referenced by createDevice().
videoInit()
bool videoInit (SDL_VideoDevice * _this) static
Initializes the QNX video plugin. Creates the Screen context and event handles used for all window operations by the plugin.
Parameters
SDL_VideoDevice *_this
Returns
0 if successful, -1 on error
{
    SDL_VideoDisplay display;
    if (screen_create_context(&context, 0) < 0) {
        return false;
    }
    if (screen_create_event(&event) < 0) {
        return false;
    }
    SDL_zero(display);
    if (SDL_AddVideoDisplay(&display, false) == 0) {
        return false;
    }
    // Assume we have a mouse and keyboard
    SDL_AddKeyboard(SDL_DEFAULT_KEYBOARD_ID, NULL, false);
    SDL_AddMouse(SDL_DEFAULT_MOUSE_ID, NULL, false);
    return true;
}
References _this, context, NULL, SDL_AddKeyboard(), SDL_AddMouse(), SDL_AddVideoDisplay(), SDL_DEFAULT_KEYBOARD_ID, SDL_DEFAULT_MOUSE_ID, and SDL_zero.
Referenced by createDevice().
videoQuit()
void videoQuit (SDL_VideoDevice * _this) static
{
}
References _this.
Referenced by createDevice().
Variable Documentation
context
screen_context_t context static
Referenced by Android_GLES_MakeCurrent(), createWindow(), SDL_VideoData::EGLNativeDisplayType(), GDK_RegisterChangeNotifications(), glCreateContext(), glDeleteContext(), glMakeCurrent(), hid_device_removal_callback(), hid_report_callback(), KMSDRM_GLES_MakeCurrent(), perform_signal_callback(), PSP_GL_DestroyContext(), PSP_GL_MakeCurrent(), pumpEvents(), RPI_GLES_DestroyContext(), RPI_GLES_MakeCurrent(), SDL_DeviceNotificationFunc(), SDL_FlushIO(), SDL_GetIOProperties(), SDL_GetIOSize(), SDL_GetIOStatus(), SDL_GL_DestroyContext(), SDL_GL_MakeCurrent(), SDL_IOprintf(), SDL_IOvprintf(), SDL_ReadIO(), SDL_SeekIO(), SDL_TellIO(), SDL_WriteIO(), updateWindowFramebuffer(), videoInit(), VITA_DestroyWindow(), Wayland_GLES_DestroyContext(), and Wayland_GLES_MakeCurrent().
event
screen_event_t event static
QNX_bootstrap
VideoBootStrap QNX_bootstrap
Initial value:
= {
    "qnx", "QNX Screen",
    createDevice,
    NULL,
    false
}
{
    "qnx", "QNX Screen",
    createDevice,
    NULL, // no ShowMessageBox implementation
    false
};