SDL3: SDL-main/include/SDL3/SDL_log.h File Reference
SDL_log.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Typedefs
typedef enum SDL_LogCategory SDL_LogCategory
typedef void(SDLCALL * SDL_LogOutputFunction) (void *userdata, int category, SDL_LogPriority priority, const char *message)
typedef enum SDL_LogPriority SDL_LogPriority
Enumerations
enum SDL_LogCategory {
SDL_LOG_CATEGORY_APPLICATION , SDL_LOG_CATEGORY_ERROR , SDL_LOG_CATEGORY_ASSERT , SDL_LOG_CATEGORY_SYSTEM ,
SDL_LOG_CATEGORY_AUDIO , SDL_LOG_CATEGORY_VIDEO , SDL_LOG_CATEGORY_RENDER , SDL_LOG_CATEGORY_INPUT ,
SDL_LOG_CATEGORY_TEST , SDL_LOG_CATEGORY_GPU , SDL_LOG_CATEGORY_RESERVED2 , SDL_LOG_CATEGORY_RESERVED3 ,
SDL_LOG_CATEGORY_RESERVED4 , SDL_LOG_CATEGORY_RESERVED5 , SDL_LOG_CATEGORY_RESERVED6 , SDL_LOG_CATEGORY_RESERVED7 ,
SDL_LOG_CATEGORY_RESERVED8 , SDL_LOG_CATEGORY_RESERVED9 , SDL_LOG_CATEGORY_RESERVED10 , SDL_LOG_CATEGORY_CUSTOM
}
enum SDL_LogPriority {
SDL_LOG_PRIORITY_INVALID , SDL_LOG_PRIORITY_TRACE , SDL_LOG_PRIORITY_VERBOSE , SDL_LOG_PRIORITY_DEBUG ,
SDL_LOG_PRIORITY_INFO , SDL_LOG_PRIORITY_WARN , SDL_LOG_PRIORITY_ERROR , SDL_LOG_PRIORITY_CRITICAL ,
SDL_LOG_PRIORITY_COUNT
}
Functions
SDL_DECLSPEC SDL_LogOutputFunction SDLCALL SDL_GetDefaultLogOutputFunction (void)
SDL_DECLSPEC void SDLCALL SDL_GetLogOutputFunction (SDL_LogOutputFunction *callback, void **userdata)
SDL_DECLSPEC SDL_LogPriority SDLCALL SDL_GetLogPriority (int category)
SDL_DECLSPEC void SDLCALL SDL_Log (SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(1)
SDL_DECLSPEC void SDLCALL SDL_LogCritical (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC void SDLCALL SDL_LogDebug (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC void SDLCALL SDL_LogError (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC void SDLCALL SDL_LogInfo (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC void SDLCALL SDL_LogMessage (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(3)
SDL_DECLSPEC void SDLCALL SDL_LogMessageV (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap) SDL_PRINTF_VARARG_FUNCV(3)
SDL_DECLSPEC void SDLCALL SDL_LogTrace (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC void SDLCALL SDL_LogVerbose (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC void SDLCALL SDL_LogWarn (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC void SDLCALL SDL_ResetLogPriorities (void)
SDL_DECLSPEC void SDLCALL SDL_SetLogOutputFunction (SDL_LogOutputFunction callback, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_SetLogPriorities (SDL_LogPriority priority)
SDL_DECLSPEC void SDLCALL SDL_SetLogPriority (int category, SDL_LogPriority priority)
SDL_DECLSPEC bool SDLCALL SDL_SetLogPriorityPrefix (SDL_LogPriority priority, const char *prefix)
Typedef Documentation
SDL_LogCategory
typedef enum SDL_LogCategory SDL_LogCategory
CategoryLog
Simple log messages with priorities and categories. A message's SDL_LogPriority signifies how important the message is. A message's SDL_LogCategory signifies from what domain it belongs to. Every category has a minimum priority specified: when a message belongs to that category, it will only be sent out if it has that minimum priority or higher.
SDL's own logs are sent below the default priority threshold, so they are quiet by default.
You can change the log verbosity programmatically using SDL_SetLogPriority() or with SDL_SetHint(SDL_HINT_LOGGING, ...), or with the "SDL_LOGGING" environment variable. This variable is a comma separated set of category=level tokens that define the default logging levels for SDL applications.
The category can be a numeric category, one of "app", "error", "assert", "system", "audio", "video", "render", "input", "test", or * for any unspecified category.
The level can be a numeric level, one of "trace", "verbose", "debug", "info", "warn", "error", "critical", or "quiet" to disable that category.
You can omit the category if you want to set the logging level for all categories.
If this hint isn't set, the default log levels are equivalent to:
app=info,assert=warn,test=verbose,*=error
Here's where the messages go on different platforms:
Windows: debug output stream
Android: log output
Others: standard error output (stderr)
You don't need to have a newline (\n) on the end of messages, the functions will do that for you. For consistent behavior cross-platform, you shouldn't have any newlines in messages, such as to log multiple lines in one call; unusual platform-specific behavior can be observed in such usage. Do one log call per line instead, with no newlines in messages.
Each log call is atomic, so you won't see log messages cut off one another when logging from multiple threads. The predefined log categories
By default the application and gpu categories are enabled at the INFO level, the assert category is enabled at the WARN level, test is enabled at the VERBOSE level and all other categories are enabled at the ERROR level.
Since
This enum is available since SDL 3.2.0.
SDL_LogOutputFunction
typedef void(SDLCALL * SDL_LogOutputFunction) (void *userdata, int category, SDL_LogPriority priority, const char *message)
The prototype for the log output callback function.
This function is called by SDL when there is new text to be logged. A mutex is held so that this function is never called by more than one thread at once.
Parameters
userdata what was passed as userdata to SDL_SetLogOutputFunction().
category the category of the message.
priority the priority of the message.
message the message being output.
Since
This datatype is available since SDL 3.2.0.
SDL_LogPriority
typedef enum SDL_LogPriority SDL_LogPriority
The predefined log priorities
Since
This enum is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_LogCategory
enum SDL_LogCategory
CategoryLog
Simple log messages with priorities and categories. A message's SDL_LogPriority signifies how important the message is. A message's SDL_LogCategory signifies from what domain it belongs to. Every category has a minimum priority specified: when a message belongs to that category, it will only be sent out if it has that minimum priority or higher.
SDL's own logs are sent below the default priority threshold, so they are quiet by default.
You can change the log verbosity programmatically using SDL_SetLogPriority() or with SDL_SetHint(SDL_HINT_LOGGING, ...), or with the "SDL_LOGGING" environment variable. This variable is a comma separated set of category=level tokens that define the default logging levels for SDL applications.
The category can be a numeric category, one of "app", "error", "assert", "system", "audio", "video", "render", "input", "test", or * for any unspecified category.
The level can be a numeric level, one of "trace", "verbose", "debug", "info", "warn", "error", "critical", or "quiet" to disable that category.
You can omit the category if you want to set the logging level for all categories.
If this hint isn't set, the default log levels are equivalent to:
app=info,assert=warn,test=verbose,*=error
Here's where the messages go on different platforms:
Windows: debug output stream
Android: log output
Others: standard error output (stderr)
You don't need to have a newline (\n) on the end of messages, the functions will do that for you. For consistent behavior cross-platform, you shouldn't have any newlines in messages, such as to log multiple lines in one call; unusual platform-specific behavior can be observed in such usage. Do one log call per line instead, with no newlines in messages.
Each log call is atomic, so you won't see log messages cut off one another when logging from multiple threads. The predefined log categories
By default the application and gpu categories are enabled at the INFO level, the assert category is enabled at the WARN level, test is enabled at the VERBOSE level and all other categories are enabled at the ERROR level.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_LOG_CATEGORY_APPLICATION
SDL_LOG_CATEGORY_ERROR
SDL_LOG_CATEGORY_ASSERT
SDL_LOG_CATEGORY_SYSTEM
SDL_LOG_CATEGORY_AUDIO
SDL_LOG_CATEGORY_VIDEO
SDL_LOG_CATEGORY_RENDER
SDL_LOG_CATEGORY_INPUT
SDL_LOG_CATEGORY_TEST
SDL_LOG_CATEGORY_GPU
SDL_LOG_CATEGORY_RESERVED2
SDL_LOG_CATEGORY_RESERVED3
SDL_LOG_CATEGORY_RESERVED4
SDL_LOG_CATEGORY_RESERVED5
SDL_LOG_CATEGORY_RESERVED6
SDL_LOG_CATEGORY_RESERVED7
SDL_LOG_CATEGORY_RESERVED8
SDL_LOG_CATEGORY_RESERVED9
SDL_LOG_CATEGORY_RESERVED10
SDL_LOG_CATEGORY_CUSTOM
{
    SDL_LOG_CATEGORY_APPLICATION,
    SDL_LOG_CATEGORY_ERROR,
    SDL_LOG_CATEGORY_ASSERT,
    SDL_LOG_CATEGORY_SYSTEM,
    SDL_LOG_CATEGORY_AUDIO,
    SDL_LOG_CATEGORY_VIDEO,
    SDL_LOG_CATEGORY_RENDER,
    SDL_LOG_CATEGORY_INPUT,
    SDL_LOG_CATEGORY_TEST,
    SDL_LOG_CATEGORY_GPU,
    /* Reserved for future SDL library use */
    SDL_LOG_CATEGORY_RESERVED2,
    SDL_LOG_CATEGORY_RESERVED3,
    SDL_LOG_CATEGORY_RESERVED4,
    SDL_LOG_CATEGORY_RESERVED5,
    SDL_LOG_CATEGORY_RESERVED6,
    SDL_LOG_CATEGORY_RESERVED7,
    SDL_LOG_CATEGORY_RESERVED8,
    SDL_LOG_CATEGORY_RESERVED9,
    SDL_LOG_CATEGORY_RESERVED10,
    /* Beyond this point is reserved for application use, e.g.
       enum {
           MYAPP_CATEGORY_AWESOME1 = SDL_LOG_CATEGORY_CUSTOM,
           MYAPP_CATEGORY_AWESOME2,
           MYAPP_CATEGORY_AWESOME3,
           ...
       };
     */
    SDL_LOG_CATEGORY_CUSTOM
} SDL_LogCategory;
SDL_LogPriority
enum SDL_LogPriority
The predefined log priorities
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_LOG_PRIORITY_INVALID
SDL_LOG_PRIORITY_TRACE
SDL_LOG_PRIORITY_VERBOSE
SDL_LOG_PRIORITY_DEBUG
SDL_LOG_PRIORITY_INFO
SDL_LOG_PRIORITY_WARN
SDL_LOG_PRIORITY_ERROR
SDL_LOG_PRIORITY_CRITICAL
SDL_LOG_PRIORITY_COUNT
{
    SDL_LOG_PRIORITY_INVALID,
    SDL_LOG_PRIORITY_TRACE,
    SDL_LOG_PRIORITY_VERBOSE,
    SDL_LOG_PRIORITY_DEBUG,
    SDL_LOG_PRIORITY_INFO,
    SDL_LOG_PRIORITY_WARN,
    SDL_LOG_PRIORITY_ERROR,
    SDL_LOG_PRIORITY_CRITICAL,
    SDL_LOG_PRIORITY_COUNT
} SDL_LogPriority;
Function Documentation
SDL_GetDefaultLogOutputFunction()
SDL_DECLSPEC SDL_LogOutputFunction SDLCALL SDL_GetDefaultLogOutputFunction (void) extern
Get the default log output function.
Returns
the default log output callback.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogOutputFunction
SDL_GetLogOutputFunction
{
    return SDL_LogOutput;
}
References SDL_LogOutput().
SDL_GetLogOutputFunction()
SDL_DECLSPEC void SDLCALL SDL_GetLogOutputFunction (SDL_LogOutputFunction * callback, void ** userdata) extern
Get the current log output function.
Parameters
callback an SDL_LogOutputFunction filled in with the current log callback.
userdata a pointer filled in with the pointer that is passed to callback.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDefaultLogOutputFunction
SDL_SetLogOutputFunction
{
    SDL_LockMutex(SDL_log_function_lock);
    {
        if (callback) {
            *callback = SDL_log_function;
        }
        if (userdata) {
            *userdata = SDL_log_userdata;
        }
    }
    SDL_UnlockMutex(SDL_log_function_lock);
}
References SDL_LockMutex(), SDL_log_function_lock, and SDL_UnlockMutex().
SDL_GetLogPriority()
SDL_DECLSPEC SDL_LogPriority SDLCALL SDL_GetLogPriority (int category) extern
Get the priority of a particular log category.
Parameters
category the category to query.
Returns
the SDL_LogPriority for the requested category.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogPriority
{
    SDL_LogLevel *entry;
    SDL_LogPriority priority = SDL_LOG_PRIORITY_INVALID;
    SDL_CheckInitLog();
    // Bypass the lock for known categories
    // Technically if the priority was set on a different CPU the value might not
    // be visible on this CPU for a while, but in practice it's fast enough that
    // this performance improvement is worthwhile.
    if (category >= 0 && category < SDL_arraysize(SDL_log_priorities)) {
        return SDL_log_priorities[category];
    }
    SDL_LockMutex(SDL_log_lock);
    {
        if (category >= 0 && category < SDL_arraysize(SDL_log_priorities)) {
            priority = SDL_log_priorities[category];
        } else {
            for (entry = SDL_loglevels; entry; entry = entry->next) {
                if (entry->category == category) {
                    priority = entry->priority;
                    break;
                }
            }
            if (priority == SDL_LOG_PRIORITY_INVALID) {
                priority = SDL_log_default_priority;
            }
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
    return priority;
}
References SDL_LogLevel::category, SDL_LogLevel::next, SDL_LogLevel::priority, SDL_arraysize, SDL_CheckInitLog(), SDL_LockMutex(), SDL_log_lock, SDL_LOG_PRIORITY_INVALID, and SDL_UnlockMutex().
Referenced by SDL_LogMessageV().
SDL_Log()
SDL_DECLSPEC void SDLCALL SDL_Log (SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_CATEGORY_APPLICATION and SDL_LOG_PRIORITY_INFO.
Parameters
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_PRIORITY_INFO, fmt, ap);
    va_end(ap);
}
References SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_PRIORITY_INFO, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by AddDeviceToEnumeration(), CameraThread(), ConvertAudio(), DebugLogRenderCommands(), E32Main(), GetAudioStreamDataInternal(), LogOneLeakedObject(), PLATFORM_hid_init(), PutAudioStreamBuffer(), RequestBluetoothPermissionCallback(), SDL_AddCamera(), SDL_CameraDisconnected(), SDL_CameraThreadIterate(), SDL_DebugLogBackend(), SDL_DumpPropertiesCallback(), SDL_GetAudioStreamDataAdjustGain(), SDL_LogEvent(), SDL_OpenCamera(), SDL_PrivateSendMouseMotion(), SDL_PutAudioStreamPlanarData(), SDL_ResetKeyboard(), SDL_SendKeyboardKeyInternal(), SDL_StopEventLoop(), SDL_UpdateMouseFocus(), and ZombieAcquireFrame().
SDL_LogCritical()
SDL_DECLSPEC void SDLCALL SDL_LogCritical (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_PRIORITY_CRITICAL.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_CRITICAL, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_CRITICAL, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogDebug()
SDL_DECLSPEC void SDLCALL SDL_LogDebug (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_PRIORITY_DEBUG.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_DEBUG, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_DEBUG, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by GDK_RegisterChangeNotifications(), and SDL_hid_init().
SDL_LogError()
SDL_DECLSPEC void SDLCALL SDL_LogError (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_PRIORITY_ERROR.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_ERROR, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_ERROR, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by SDL_SetErrorV().
SDL_LogInfo()
SDL_DECLSPEC void SDLCALL SDL_LogInfo (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_PRIORITY_INFO.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_INFO, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_INFO, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by SDL_CreateRendererWithProperties(), and SDL_InitMainThread().
SDL_LogMessage()
SDL_DECLSPEC void SDLCALL SDL_LogMessage (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with the specified category and priority.
Parameters
category the category of the message.
priority the priority of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, priority, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LogLevel::priority, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogMessageV()
SDL_DECLSPEC void SDLCALL SDL_LogMessageV (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char * fmt, va_list ap) extern
Log a message with the specified category and priority.
Parameters
category the category of the message.
priority the priority of the message.
fmt a printf() style message format string.
ap a variable argument list.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    char *message = NULL;
    char stack_buf[SDL_MAX_LOG_MESSAGE_STACK];
    size_t len_plus_term;
    int len;
    va_list aq;
    // Nothing to do if we don't have an output function
    if (!SDL_log_function) {
        return;
    }
    // See if we want to do anything with this message
    if (priority < SDL_GetLogPriority(category)) {
        return;
    }
#if defined(SDL_PLATFORM_NGAGE)
    extern void NGAGE_vnprintf(char *buf, size_t size, const char *fmt, va_list ap);
    char buf[1024];
    NGAGE_vnprintf(buf, sizeof(buf), fmt, ap);
#ifdef ENABLE_FILE_LOG
    FILE* file;
    file = fopen("E:/SDL_Log.txt", "a");
    if (file)
    {
        vfprintf(file, fmt, ap);
        fprintf(file, "\n");
        (void)fclose(file);
    }
#endif
    return;
#endif
    // Render into stack buffer
    va_copy(aq, ap);
    len = SDL_vsnprintf(stack_buf, sizeof(stack_buf), fmt, aq);
    va_end(aq);
    if (len < 0) {
        return;
    }
    // If message truncated, allocate and re-render
    if (len >= sizeof(stack_buf) && SDL_size_add_check_overflow(len, 1, &len_plus_term)) {
        // Allocate exactly what we need, including the zero-terminator
        message = (char *)SDL_malloc(len_plus_term);
        if (!message) {
            return;
        }
        va_copy(aq, ap);
        len = SDL_vsnprintf(message, len_plus_term, fmt, aq);
        va_end(aq);
    } else {
        message = stack_buf;
    }
    // Chop off final endline.
    if ((len > 0) && (message[len - 1] == '\n')) {
        message[--len] = '\0';
        if ((len > 0) && (message[len - 1] == '\r')) { // catch "\r\n", too.
            message[--len] = '\0';
        }
    }
    SDL_LockMutex(SDL_log_function_lock);
    {
        SDL_log_function(SDL_log_userdata, category, priority, message);
    }
    SDL_UnlockMutex(SDL_log_function_lock);
    // Free only if dynamically allocated
    if (message != stack_buf) {
        SDL_free(message);
    }
}
References SDL_LogLevel::category, NGAGE_vnprintf(), NULL, SDL_LogLevel::priority, SDL_free(), SDL_GetLogPriority(), SDL_LockMutex(), SDL_log_function_lock, SDL_malloc(), SDL_MAX_LOG_MESSAGE_STACK, SDL_PRINTF_FORMAT_STRING, SDL_size_add_check_overflow(), SDL_UnlockMutex(), SDL_vsnprintf(), and void().
Referenced by debug_print(), SDL_Log(), SDL_LogCritical(), SDL_LogDebug(), SDL_LogError(), SDL_LogInfo(), SDL_LogMessage(), SDL_LogTrace(), SDL_LogVerbose(), and SDL_LogWarn().
SDL_LogTrace()
SDL_DECLSPEC void SDLCALL SDL_LogTrace (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_PRIORITY_TRACE.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_TRACE, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_TRACE, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogVerbose()
SDL_DECLSPEC void SDLCALL SDL_LogVerbose (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_PRIORITY_VERBOSE.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_VERBOSE, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_VERBOSE, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogWarn()
SDL_DECLSPEC void SDLCALL SDL_LogWarn (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Log a message with SDL_LOG_PRIORITY_WARN.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_WARN, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_WARN, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by HIDAPI_InitializeDiscovery(), and SDL_SYS_GetPrefPath().
SDL_ResetLogPriorities()
SDL_DECLSPEC void SDLCALL SDL_ResetLogPriorities (void) extern
Reset all priorities to default.
This is called by SDL_Quit().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogPriorities
SDL_SetLogPriority
{
    SDL_CheckInitLog();
    SDL_LockMutex(SDL_log_lock);
    {
        CleanupLogPriorities();
        SDL_log_default_priority = SDL_LOG_PRIORITY_INVALID;
        for (int i = 0; i < SDL_arraysize(SDL_log_priorities); ++i) {
            SDL_log_priorities[i] = SDL_LOG_PRIORITY_INVALID;
        }
        const char *hint = SDL_GetHint(SDL_HINT_LOGGING);
        if (hint) {
            ParseLogPriorities(hint);
        }
        if (SDL_log_default_priority == SDL_LOG_PRIORITY_INVALID) {
            SDL_log_default_priority = SDL_LOG_PRIORITY_ERROR;
        }
        for (int i = 0; i < SDL_arraysize(SDL_log_priorities); ++i) {
            if (SDL_log_priorities[i] != SDL_LOG_PRIORITY_INVALID) {
                continue;
            }
            switch (i) {
            case SDL_LOG_CATEGORY_APPLICATION:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_INFO;
                break;
            case SDL_LOG_CATEGORY_ASSERT:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_WARN;
                break;
            case SDL_LOG_CATEGORY_TEST:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_VERBOSE;
                break;
            default:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_ERROR;
                break;
            }
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
}
References CleanupLogPriorities(), ParseLogPriorities(), SDL_arraysize, SDL_CheckInitLog(), SDL_GetHint(), SDL_HINT_LOGGING, SDL_LockMutex(), SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_CATEGORY_ASSERT, SDL_LOG_CATEGORY_TEST, SDL_log_lock, SDL_LOG_PRIORITY_ERROR, SDL_LOG_PRIORITY_INFO, SDL_LOG_PRIORITY_INVALID, SDL_LOG_PRIORITY_VERBOSE, SDL_LOG_PRIORITY_WARN, and SDL_UnlockMutex().
Referenced by SDL_LoggingChanged().
SDL_SetLogOutputFunction()
SDL_DECLSPEC void SDLCALL SDL_SetLogOutputFunction (SDL_LogOutputFunction callback, void * userdata) extern
Replace the default log output function with one of your own.
Parameters
callback an SDL_LogOutputFunction to call instead of the default.
userdata a pointer that is passed to callback.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDefaultLogOutputFunction
SDL_GetLogOutputFunction
{
    SDL_LockMutex(SDL_log_function_lock);
    {
        SDL_log_function = callback;
        SDL_log_userdata = userdata;
    }
    SDL_UnlockMutex(SDL_log_function_lock);
}
References SDL_LockMutex(), SDL_log_function_lock, and SDL_UnlockMutex().
SDL_SetLogPriorities()
SDL_DECLSPEC void SDLCALL SDL_SetLogPriorities (SDL_LogPriority priority) extern
Set the priority of all log categories.
Parameters
priority the SDL_LogPriority to assign.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResetLogPriorities
SDL_SetLogPriority
{
    SDL_CheckInitLog();
    SDL_LockMutex(SDL_log_lock);
    {
        CleanupLogPriorities();
        SDL_log_default_priority = priority;
        for (int i = 0; i < SDL_arraysize(SDL_log_priorities); ++i) {
            SDL_log_priorities[i] = priority;
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
}
References CleanupLogPriorities(), SDL_LogLevel::priority, SDL_arraysize, SDL_CheckInitLog(), SDL_LockMutex(), SDL_log_lock, and SDL_UnlockMutex().
Referenced by ParseLogPriorities().
SDL_SetLogPriority()
SDL_DECLSPEC void SDLCALL SDL_SetLogPriority (int category, SDL_LogPriority priority) extern
Set the priority of a particular log category.
Parameters
category the category to assign a priority to.
priority the SDL_LogPriority to assign.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetLogPriority
SDL_ResetLogPriorities
SDL_SetLogPriorities
{
    SDL_LogLevel *entry;
    SDL_CheckInitLog();
    SDL_LockMutex(SDL_log_lock);
    {
        if (category >= 0 && category < SDL_arraysize(SDL_log_priorities)) {
            SDL_log_priorities[category] = priority;
        } else {
            for (entry = SDL_loglevels; entry; entry = entry->next) {
                if (entry->category == category) {
                    entry->priority = priority;
                    break;
                }
            }
            if (!entry) {
                entry = (SDL_LogLevel *)SDL_malloc(sizeof(*entry));
                if (entry) {
                    entry->category = category;
                    entry->priority = priority;
                    entry->next = SDL_loglevels;
                    SDL_loglevels = entry;
                }
            }
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
}
References SDL_LogLevel::category, SDL_LogLevel::next, SDL_LogLevel::priority, SDL_arraysize, SDL_CheckInitLog(), SDL_LockMutex(), SDL_log_lock, SDL_malloc(), and SDL_UnlockMutex().
Referenced by ParseLogPriorities().
SDL_SetLogPriorityPrefix()
SDL_DECLSPEC bool SDLCALL SDL_SetLogPriorityPrefix (SDL_LogPriority priority, const char * prefix) extern
Set the text prepended to log messages of a given priority.
By default SDL_LOG_PRIORITY_INFO and below have no prefix, and SDL_LOG_PRIORITY_WARN and higher have a prefix showing their priority, e.g. "WARNING: ".
This function makes a copy of its string argument, prefix, so it is not necessary to keep the value of prefix alive after the call returns.
Parameters
priority the SDL_LogPriority to modify.
prefix the prefix to use for that log priority, or NULL to use no prefix.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogPriorities
SDL_SetLogPriority
{
    char *prefix_copy;
    if (priority <= SDL_LOG_PRIORITY_INVALID || priority >= SDL_LOG_PRIORITY_COUNT) {
        return SDL_InvalidParamError("priority");
    }
    if (!prefix || !*prefix) {
        prefix_copy = SDL_strdup("");
    } else {
        prefix_copy = SDL_strdup(prefix);
    }
    if (!prefix_copy) {
        return false;
    }
    SDL_LockMutex(SDL_log_function_lock);
    {
        if (SDL_priority_prefixes[priority]) {
            SDL_free(SDL_priority_prefixes[priority]);
        }
        SDL_priority_prefixes[priority] = prefix_copy;
    }
    SDL_UnlockMutex(SDL_log_function_lock);
    return true;
}
References SDL_LogLevel::priority, SDL_free(), SDL_InvalidParamError, SDL_LockMutex(), SDL_log_function_lock, SDL_LOG_PRIORITY_COUNT, SDL_strdup(), and SDL_UnlockMutex().