SDL3: SDL-main/src/stdlib/SDL_getenv_c.h File Reference
SDL_getenv_c.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_InitEnvironment (void)
void SDL_QuitEnvironment (void)
Function Documentation
SDL_InitEnvironment()
bool SDL_InitEnvironment (void) extern
{
    return (SDL_GetEnvironment() != NULL);
}
References NULL, and SDL_GetEnvironment().
Referenced by SDL_InitMainThread().
SDL_QuitEnvironment()
void SDL_QuitEnvironment (void) extern
{
    SDL_Environment *env = SDL_environment;
    if (env) {
        SDL_environment = NULL;
        SDL_DestroyEnvironment(env);
    }
}
References NULL, SDL_DestroyEnvironment(), and SDL_environment.
Referenced by SDL_QuitMainThread().