SDL3: SDL-main/include/SDL3/SDL_time.h File Reference
SDL_time.h File Reference
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_DateTime
Typedefs
typedef enum SDL_DateFormat SDL_DateFormat
typedef struct SDL_DateTime SDL_DateTime
typedef enum SDL_TimeFormat SDL_TimeFormat
Enumerations
enum SDL_DateFormat { SDL_DATE_FORMAT_YYYYMMDD = 0 , SDL_DATE_FORMAT_DDMMYYYY = 1 , SDL_DATE_FORMAT_MMDDYYYY = 2 }
enum SDL_TimeFormat { SDL_TIME_FORMAT_24HR = 0 , SDL_TIME_FORMAT_12HR = 1 }
Functions
SDL_DECLSPEC bool SDLCALL SDL_DateTimeToTime (const SDL_DateTime *dt, SDL_Time *ticks)
SDL_DECLSPEC bool SDLCALL SDL_GetCurrentTime (SDL_Time *ticks)
SDL_DECLSPEC bool SDLCALL SDL_GetDateTimeLocalePreferences (SDL_DateFormat *dateFormat, SDL_TimeFormat *timeFormat)
SDL_DECLSPEC int SDLCALL SDL_GetDayOfWeek (int year, int month, int day)
SDL_DECLSPEC int SDLCALL SDL_GetDayOfYear (int year, int month, int day)
SDL_DECLSPEC int SDLCALL SDL_GetDaysInMonth (int year, int month)
SDL_DECLSPEC SDL_Time SDLCALL SDL_TimeFromWindows (Uint32 dwLowDateTime, Uint32 dwHighDateTime)
SDL_DECLSPEC bool SDLCALL SDL_TimeToDateTime (SDL_Time ticks, SDL_DateTime *dt, bool localTime)
SDL_DECLSPEC void SDLCALL SDL_TimeToWindows (SDL_Time ticks, Uint32 *dwLowDateTime, Uint32 *dwHighDateTime)
Typedef Documentation
SDL_DateFormat
typedef enum SDL_DateFormat SDL_DateFormat
The preferred date format of the current system locale.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetDateTimeLocalePreferences
SDL_DateTime
typedef struct SDL_DateTime SDL_DateTime
CategoryTime
SDL realtime clock and date/time routines.
There are two data types that are used in this category: SDL_Time, which represents the nanoseconds since a specific moment (an "epoch"), and SDL_DateTime, which breaks time down into human-understandable components: years, months, days, hours, etc.
Much of the functionality is involved in converting those two types to other useful forms. A structure holding a calendar date and time broken down into its components.
Since
This struct is available since SDL 3.2.0.
SDL_TimeFormat
typedef enum SDL_TimeFormat SDL_TimeFormat
The preferred time format of the current system locale.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetDateTimeLocalePreferences
Enumeration Type Documentation
SDL_DateFormat
enum SDL_DateFormat
The preferred date format of the current system locale.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetDateTimeLocalePreferences
Enumerator
SDL_DATE_FORMAT_YYYYMMDD
Year/Month/Day
SDL_DATE_FORMAT_DDMMYYYY
Day/Month/Year
SDL_DATE_FORMAT_MMDDYYYY
Month/Day/Year
{
    SDL_DATE_FORMAT_YYYYMMDD = 0, /**< Year/Month/Day */
    SDL_DATE_FORMAT_DDMMYYYY = 1, /**< Day/Month/Year */
    SDL_DATE_FORMAT_MMDDYYYY = 2  /**< Month/Day/Year */
} SDL_DateFormat;
SDL_TimeFormat
enum SDL_TimeFormat
The preferred time format of the current system locale.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetDateTimeLocalePreferences
Enumerator
SDL_TIME_FORMAT_24HR
24 hour time
SDL_TIME_FORMAT_12HR
12 hour time
{
    SDL_TIME_FORMAT_24HR = 0, /**< 24 hour time */
    SDL_TIME_FORMAT_12HR = 1  /**< 12 hour time */
} SDL_TimeFormat;
Function Documentation
SDL_DateTimeToTime()
SDL_DECLSPEC bool SDLCALL SDL_DateTimeToTime (const SDL_DateTime * dt, SDL_Time * ticks) extern
Converts a calendar time to an SDL_Time in nanoseconds since the epoch.
This function ignores the day_of_week member of the SDL_DateTime struct, so it may remain unset.
Parameters
dt the source SDL_DateTime.
ticks the resulting SDL_Time.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    static const Sint64 max_seconds = SDL_NS_TO_SECONDS(SDL_MAX_TIME) - 1;
    static const Sint64 min_seconds = SDL_NS_TO_SECONDS(SDL_MIN_TIME) + 1;
    bool result = true;
    if (!dt) {
        return SDL_InvalidParamError("dt");
    }
    if (!ticks) {
        return SDL_InvalidParamError("ticks");
    }
    if (!SDL_DateTimeIsValid(dt)) {
        // The validation function sets the error string.
        return false;
    }
    *ticks = SDL_CivilToDays(dt->year, dt->month, dt->day, NULL, NULL) * SDL_SECONDS_PER_DAY;
    *ticks += (((dt->hour * 60) + dt->minute) * 60) + dt->second - dt->utc_offset;
    if (*ticks > max_seconds || *ticks < min_seconds) {
        *ticks = SDL_clamp(*ticks, min_seconds, max_seconds);
        result = SDL_SetError("Date out of range for SDL_Time representation; SDL_Time value clamped");
    }
    *ticks = SDL_SECONDS_TO_NS(*ticks) + dt->nanosecond;
    return result;
}
References SDL_DateTime::day, SDL_DateTime::hour, SDL_DateTime::minute, SDL_DateTime::month, SDL_DateTime::nanosecond, NULL, SDL_CivilToDays(), SDL_clamp, SDL_DateTimeIsValid(), SDL_InvalidParamError, SDL_MAX_TIME, SDL_MIN_TIME, SDL_NS_TO_SECONDS, SDL_SECONDS_PER_DAY, SDL_SECONDS_TO_NS, SDL_SetError(), SDL_DateTime::second, SDL_DateTime::utc_offset, and SDL_DateTime::year.
SDL_GetCurrentTime()
SDL_DECLSPEC bool SDLCALL SDL_GetCurrentTime (SDL_Time * ticks) extern
Gets the current value of the system realtime clock in nanoseconds since Jan 1, 1970 in Universal Coordinated Time (UTC).
Parameters
ticks the SDL_Time to hold the returned tick count.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, and SDLCALL.
SDL_GetDateTimeLocalePreferences()
SDL_DECLSPEC bool SDLCALL SDL_GetDateTimeLocalePreferences (SDL_DateFormat * dateFormat, SDL_TimeFormat * timeFormat) extern
Gets the current preferred date and time format for the system locale.
This might be a "slow" call that has to query the operating system. It's best to ask for this once and save the results. However, the preferred formats can change, usually because the user has changed a system preference outside of your program.
Parameters
dateFormat a pointer to the SDL_DateFormat to hold the returned date format, may be NULL.
timeFormat a pointer to the SDL_TimeFormat to hold the returned time format, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    // Default to ISO 8061 date format, as it is unambiguous, and 24 hour time.
    if (dateFormat) {
        *dateFormat = SDL_DATE_FORMAT_YYYYMMDD;
    }
    if (timeFormat) {
        *timeFormat = SDL_TIME_FORMAT_24HR;
    }
    SDL_GetSystemTimeLocalePreferences(dateFormat, timeFormat);
    return true;
}
References SDL_DATE_FORMAT_YYYYMMDD, SDL_GetSystemTimeLocalePreferences(), and SDL_TIME_FORMAT_24HR.
SDL_GetDayOfWeek()
SDL_DECLSPEC int SDLCALL SDL_GetDayOfWeek (int year, int month, int day) extern
Get the day of week for a calendar date.
Parameters
year the year component of the date.
month the month component of the date.
day the day component of the date.
Returns
a value between 0 and 6 (0 being Sunday) if the date is valid or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    int dayOfWeek;
    if (month < 1 || month > 12) {
        SDL_SetError("Month out of range [1-12], requested: %i", month);
        return -1;
    }
    if (day < 1 || day > SDL_GetDaysInMonth(year, month)) {
        SDL_SetError("Day out of range [1-%i], requested: %i", SDL_GetDaysInMonth(year, month), month);
        return -1;
    }
    SDL_CivilToDays(year, month, day, &dayOfWeek, NULL);
    return dayOfWeek;
}
References NULL, SDL_CivilToDays(), SDL_GetDaysInMonth(), and SDL_SetError().
SDL_GetDayOfYear()
SDL_DECLSPEC int SDLCALL SDL_GetDayOfYear (int year, int month, int day) extern
Get the day of year for a calendar date.
Parameters
year the year component of the date.
month the month component of the date.
day the day component of the date.
Returns
the day of year [0-365] if the date is valid or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    int dayOfYear;
    if (month < 1 || month > 12) {
        SDL_SetError("Month out of range [1-12], requested: %i", month);
        return -1;
    }
    if (day < 1 || day > SDL_GetDaysInMonth(year, month)) {
        SDL_SetError("Day out of range [1-%i], requested: %i", SDL_GetDaysInMonth(year, month), month);
        return -1;
    }
    SDL_CivilToDays(year, month, day, NULL, &dayOfYear);
    return dayOfYear;
}
References NULL, SDL_CivilToDays(), SDL_GetDaysInMonth(), and SDL_SetError().
SDL_GetDaysInMonth()
SDL_DECLSPEC int SDLCALL SDL_GetDaysInMonth (int year, int month) extern
Get the number of days in a month for a given year.
Parameters
year the year.
month the month [1-12].
Returns
the number of days in the requested month or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    static const int DAYS_IN_MONTH[] = {
        31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
    };
    if (month < 1 || month > 12) {
        SDL_SetError("Month out of range [1-12], requested: %i", month);
        return -1;
    }
    int days = DAYS_IN_MONTH[month - 1];
    /* A leap year occurs every 4 years...
     * but not every 100 years...
     * except for every 400 years.
     */
    if (month == 2 && (!(year % 4) && ((year % 100) || !(year % 400)))) {
        ++days;
    }
    return days;
}
References SDL_SetError().
Referenced by SDL_DateTimeIsValid(), SDL_GetDayOfWeek(), and SDL_GetDayOfYear().
SDL_TimeFromWindows()
SDL_DECLSPEC SDL_Time SDLCALL SDL_TimeFromWindows (Uint32 dwLowDateTime, Uint32 dwHighDateTime) extern
Converts a Windows FILETIME (100-nanosecond intervals since January 1, 1601) to an SDL time.
This function takes the two 32-bit values of the FILETIME structure as parameters.
Parameters
dwLowDateTime the low portion of the Windows FILETIME value.
dwHighDateTime the high portion of the Windows FILETIME value.
Returns
the converted SDL time.
Since
This function is available since SDL 3.2.0.
{
    static const Uint64 wintime_min = (Uint64)((SDL_MIN_TIME / 100) + DELTA_EPOCH_1601_100NS);
    static const Uint64 wintime_max = (Uint64)((SDL_MAX_TIME / 100) + DELTA_EPOCH_1601_100NS);
    Uint64 wtime = (((Uint64)dwHighDateTime << 32) | dwLowDateTime);
    // Clamp the windows time range to the SDL_Time min/max
    wtime = SDL_clamp(wtime, wintime_min, wintime_max);
    return (SDL_Time)(wtime - DELTA_EPOCH_1601_100NS) * 100;
}
References DELTA_EPOCH_1601_100NS, SDL_clamp, SDL_MAX_TIME, and SDL_MIN_TIME.
SDL_TimeToDateTime()
SDL_DECLSPEC bool SDLCALL SDL_TimeToDateTime (SDL_Time ticks, SDL_DateTime * dt, bool localTime) extern
Converts an SDL_Time in nanoseconds since the epoch to a calendar time in the SDL_DateTime format.
Parameters
ticks the SDL_Time to be converted.
dt the resulting SDL_DateTime.
localTime the resulting SDL_DateTime will be expressed in local time if true, otherwise it will be in Universal Coordinated Time (UTC).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, and SDLCALL.
SDL_TimeToWindows()
SDL_DECLSPEC void SDLCALL SDL_TimeToWindows (SDL_Time ticks, Uint32 * dwLowDateTime, Uint32 * dwHighDateTime) extern
Converts an SDL time into a Windows FILETIME (100-nanosecond intervals since January 1, 1601).
This function fills in the two 32-bit values of the FILETIME structure.
Parameters
ticks the time to convert.
dwLowDateTime a pointer filled in with the low portion of the Windows FILETIME value.
dwHighDateTime a pointer filled in with the high portion of the Windows FILETIME value.
Since
This function is available since SDL 3.2.0.
{
    /* Convert nanoseconds to Win32 ticks.
     * SDL_Time has a range of roughly 292 years, so even SDL_MIN_TIME can't underflow the Win32 epoch.
     */
    const Uint64 wtime = (Uint64)((ticks / 100) + DELTA_EPOCH_1601_100NS);
    if (dwLowDateTime) {
        *dwLowDateTime = (Uint32)wtime;
    }
    if (dwHighDateTime) {
        *dwHighDateTime = (Uint32)(wtime >> 32);
    }
}
References DELTA_EPOCH_1601_100NS.