SDL3: SDL-main/src/video/SDL_clipboard_c.h File Reference
SDL_clipboard_c.h File Reference
#include "SDL_internal.h"
#include "SDL_sysvideo.h"
Functions
void SDL_CancelClipboardData (Uint32 sequence)
const void *SDLCALL SDL_ClipboardTextCallback (void *userdata, const char *mime_type, size_t *size)
char ** SDL_CopyClipboardMimeTypes (const char **clipboard_mime_types, size_t num_mime_types, bool temporary)
void SDL_FreeClipboardMimeTypes (SDL_VideoDevice *_this)
void * SDL_GetInternalClipboardData (SDL_VideoDevice *_this, const char *mime_type, size_t *size)
bool SDL_HasInternalClipboardData (SDL_VideoDevice *_this, const char *mime_type)
bool SDL_IsTextMimeType (const char *mime_type)
bool SDL_SaveClipboardMimeTypes (const char **mime_types, size_t num_mime_types)
Function Documentation
SDL_CancelClipboardData()
void SDL_CancelClipboardData (Uint32 sequence) extern
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return;
    }
    if (sequence && sequence != _this->clipboard_sequence) {
        // This clipboard data was already canceled
        return;
    }
    if (_this->clipboard_cleanup) {
        _this->clipboard_cleanup(_this->clipboard_userdata);
    }
    SDL_FreeClipboardMimeTypes(_this);
    _this->clipboard_callback = NULL;
    _this->clipboard_cleanup = NULL;
    _this->clipboard_userdata = NULL;
}
References _this, NULL, SDL_FreeClipboardMimeTypes(), and SDL_GetVideoDevice().
Referenced by SDL_SendClipboardUpdate(), SDL_SetClipboardData(), and SDL_VideoQuit().
SDL_ClipboardTextCallback()
const void *SDLCALL SDL_ClipboardTextCallback (void * userdata, const char * mime_type, size_t * size)
{
    char *text = (char *)userdata;
    if (text) {
        *size = SDL_strlen(text);
    } else {
        *size = 0;
    }
    return text;
}
References SDL_strlen(), and SDLCALL.
Referenced by SDL_SetClipboardText().
SDL_CopyClipboardMimeTypes()
char ** SDL_CopyClipboardMimeTypes (const char ** clipboard_mime_types, size_t num_mime_types, bool temporary)
{
    size_t allocSize = sizeof(char *);
    for (size_t i = 0; i < num_mime_types; i++) {
        allocSize += sizeof(char *) + SDL_strlen(clipboard_mime_types[i]) + 1;
    }
    char *ret;
    if (temporary)
        ret = (char *)SDL_AllocateTemporaryMemory(allocSize);
    else
        ret = (char *)SDL_malloc(allocSize);
    if (!ret) {
        return NULL;
    }
    char **result = (char **)ret;
    ret += sizeof(char *) * (num_mime_types + 1);
    for (size_t i = 0; i < num_mime_types; i++) {
        result[i] = ret;
        const char *mime_type = clipboard_mime_types[i];
        // Copy the whole string including the terminating null char
        char c;
        do {
            c = *ret++ = *mime_type++;
        } while (c != '\0');
    }
    result[num_mime_types] = NULL;
    return result;
}
References NULL, SDL_AllocateTemporaryMemory(), SDL_malloc(), and SDL_strlen().
Referenced by SDL_GetClipboardMimeTypes(), SDL_SetClipboardData(), and SDL_SetPrimarySelectionText().
SDL_FreeClipboardMimeTypes()
void SDL_FreeClipboardMimeTypes (SDL_VideoDevice * _this)
{
    if (_this->clipboard_mime_types) {
        for (size_t i = 0; i < _this->num_clipboard_mime_types; ++i) {
            SDL_free(_this->clipboard_mime_types[i]);
        }
        SDL_free(_this->clipboard_mime_types);
        _this->clipboard_mime_types = NULL;
        _this->num_clipboard_mime_types = 0;
    }
}
References _this, NULL, and SDL_free().
Referenced by SDL_CancelClipboardData(), and SDL_SaveClipboardMimeTypes().
SDL_GetInternalClipboardData()
void * SDL_GetInternalClipboardData (SDL_VideoDevice * _this, const char * mime_type, size_t * size) extern
{
    void *data = NULL;
    if (_this->clipboard_callback) {
        const void *provided_data = _this->clipboard_callback(_this->clipboard_userdata, mime_type, size);
        if (provided_data) {
            // Make a copy of it for the caller and guarantee null termination
            data = SDL_malloc(*size + sizeof(Uint32));
            if (data) {
                SDL_memcpy(data, provided_data, *size);
                SDL_memset((Uint8 *)data + *size, 0, sizeof(Uint32));
            }
        }
    }
    return data;
}
References _this, NULL, SDL_malloc(), SDL_memcpy, and SDL_memset.
Referenced by SDL_GetClipboardData().
SDL_HasInternalClipboardData()
bool SDL_HasInternalClipboardData (SDL_VideoDevice * _this, const char * mime_type) extern
{
    size_t i;
    for (i = 0; i < _this->num_clipboard_mime_types; ++i) {
        if (SDL_strcmp(mime_type, _this->clipboard_mime_types[i]) == 0) {
            return true;
        }
    }
    return false;
}
References _this, and SDL_strcmp().
Referenced by SDL_HasClipboardData().
SDL_IsTextMimeType()
bool SDL_IsTextMimeType (const char * mime_type) extern
{
    return (SDL_strncmp(mime_type, "text", 4) == 0);
}
References SDL_strncmp().
Referenced by SDL_GetClipboardData(), SDL_HasClipboardData(), and SDL_SetClipboardData().
SDL_SaveClipboardMimeTypes()
bool SDL_SaveClipboardMimeTypes (const char ** mime_types, size_t num_mime_types)
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    SDL_FreeClipboardMimeTypes(_this);
    if (mime_types && num_mime_types > 0) {
        size_t num_allocated = 0;
        _this->clipboard_mime_types = (char **)SDL_malloc(num_mime_types * sizeof(char *));
        if (_this->clipboard_mime_types) {
            for (size_t i = 0; i < num_mime_types; ++i) {
                _this->clipboard_mime_types[i] = SDL_strdup(mime_types[i]);
                if (_this->clipboard_mime_types[i]) {
                    ++num_allocated;
                }
            }
        }
        if (num_allocated < num_mime_types) {
            SDL_FreeClipboardMimeTypes(_this);
            return false;
        }
        _this->num_clipboard_mime_types = num_mime_types;
    }
    return true;
}
References _this, SDL_FreeClipboardMimeTypes(), SDL_GetVideoDevice(), SDL_malloc(), SDL_strdup(), and SDL_UninitializedVideo().
Referenced by SDL_SendClipboardUpdate(), and SDL_SetClipboardData().