SDL3: SDL-main/src/hidapi/libusb/hidapi_thread_sdl.h File Reference
hidapi_thread_sdl.h File Reference
#include "../../thread/SDL_systhread.h"
Data Structures
struct _SDL_ThreadBarrier
struct hidapi_thread_state
struct RunInputThreadParam
Macros
#define HIDAPI_THREAD_TIMED_OUT 1
Typedefs
typedef Uint64 hidapi_timespec
typedef struct _SDL_ThreadBarrier SDL_ThreadBarrier
Functions
static void hidapi_thread_addtime (hidapi_timespec *ts, int milliseconds)
static void hidapi_thread_barrier_wait (hidapi_thread_state *state)
static void hidapi_thread_cleanup_pop (int execute)
static void hidapi_thread_cleanup_push (void(*routine)(void *), void *arg)
static void hidapi_thread_cond_broadcast (hidapi_thread_state *state)
static void hidapi_thread_cond_signal (hidapi_thread_state *state)
static int hidapi_thread_cond_timedwait (hidapi_thread_state *state, hidapi_timespec *ts)
static void hidapi_thread_cond_wait (hidapi_thread_state *state)
static void hidapi_thread_create (hidapi_thread_state *state, void *(*func)(void *), void *func_arg)
static void hidapi_thread_gettime (hidapi_timespec *ts)
static void hidapi_thread_join (hidapi_thread_state *state)
static void hidapi_thread_mutex_lock (hidapi_thread_state *state)
static void hidapi_thread_mutex_unlock (hidapi_thread_state *state)
static void hidapi_thread_state_destroy (hidapi_thread_state *state)
static void hidapi_thread_state_init (hidapi_thread_state *state)
static int RunInputThread (void *param)
static int SDL_CreateThreadBarrier (SDL_ThreadBarrier *barrier, Uint32 count)
static void SDL_DestroyThreadBarrier (SDL_ThreadBarrier *barrier)
static int SDL_WaitThreadBarrier (SDL_ThreadBarrier *barrier)
Macro Definition Documentation
HIDAPI_THREAD_TIMED_OUT
#define HIDAPI_THREAD_TIMED_OUT 1
Typedef Documentation
hidapi_timespec
typedef Uint64 hidapi_timespec
SDL_ThreadBarrier
typedef struct _SDL_ThreadBarrier SDL_ThreadBarrier
Function Documentation
hidapi_thread_addtime()
void hidapi_thread_addtime (hidapi_timespec * ts, int milliseconds) static
{
    *ts += SDL_MS_TO_NS(milliseconds);
}
References SDL_MS_TO_NS.
hidapi_thread_barrier_wait()
void hidapi_thread_barrier_wait (hidapi_thread_state * state) static
{
    SDL_WaitThreadBarrier(&state->barrier);
}
References hidapi_thread_state::barrier, and SDL_WaitThreadBarrier().
hidapi_thread_cleanup_pop()
void hidapi_thread_cleanup_pop (int execute) static
{
}
hidapi_thread_cleanup_push()
void hidapi_thread_cleanup_push (void(* routine)(void *), void * arg) static
{
    /* There isn't an equivalent in SDL, and it's only useful for threads calling hid_read_timeout() */
}
hidapi_thread_cond_broadcast()
void hidapi_thread_cond_broadcast (hidapi_thread_state * state) static
{
    SDL_BroadcastCondition(state->condition);
}
References hidapi_thread_state::condition, and SDL_BroadcastCondition().
hidapi_thread_cond_signal()
void hidapi_thread_cond_signal (hidapi_thread_state * state) static
{
    SDL_SignalCondition(state->condition);
}
References hidapi_thread_state::condition, and SDL_SignalCondition().
hidapi_thread_cond_timedwait()
int hidapi_thread_cond_timedwait (hidapi_thread_state * state, hidapi_timespec * ts) static
{
    Sint64 timeout_ns;
    Sint32 timeout_ms;
    timeout_ns = (Sint64)(*ts - SDL_GetTicksNS());
    if (timeout_ns <= 0) {
        timeout_ms = 0;
    } else {
        timeout_ms = (Sint32)SDL_NS_TO_MS(timeout_ns);
    }
    if (SDL_WaitConditionTimeout(state->condition, state->mutex, timeout_ms)) {
        return 0;
    } else {
        return HIDAPI_THREAD_TIMED_OUT;
    }
}
References hidapi_thread_state::condition, HIDAPI_THREAD_TIMED_OUT, hidapi_thread_state::mutex, SDL_GetTicksNS(), SDL_NS_TO_MS, and SDL_WaitConditionTimeout().
hidapi_thread_cond_wait()
void hidapi_thread_cond_wait (hidapi_thread_state * state) static
{
    SDL_WaitCondition(state->condition, state->mutex);
}
References hidapi_thread_state::condition, hidapi_thread_state::mutex, and SDL_WaitCondition().
hidapi_thread_create()
void hidapi_thread_create (hidapi_thread_state * state, void *(* func)(void *), void * func_arg) static
{
    RunInputThreadParam *param = (RunInputThreadParam *)malloc(sizeof(*param));
    /* Note that the hidapi code didn't check for thread creation failure.
     * We'll crash if malloc() fails
     */
    param->func = func;
    param->func_arg = func_arg;
    state->thread = SDL_CreateThread(RunInputThread, "libusb", param);
}
References RunInputThreadParam::func, RunInputThreadParam::func_arg, malloc, RunInputThread(), SDL_CreateThread, and hidapi_thread_state::thread.
hidapi_thread_gettime()
void hidapi_thread_gettime (hidapi_timespec * ts) static
{
    *ts = SDL_GetTicksNS();
}
References SDL_GetTicksNS().
hidapi_thread_join()
void hidapi_thread_join (hidapi_thread_state * state) static
{
    SDL_WaitThread(state->thread, NULL);
}
References NULL, SDL_WaitThread(), and hidapi_thread_state::thread.
hidapi_thread_mutex_lock()
void hidapi_thread_mutex_lock (hidapi_thread_state * state) static
{
    SDL_LockMutex(state->mutex);
}
References hidapi_thread_state::mutex, and SDL_LockMutex().
hidapi_thread_mutex_unlock()
void hidapi_thread_mutex_unlock (hidapi_thread_state * state) static
{
    SDL_UnlockMutex(state->mutex);
}
References hidapi_thread_state::mutex, and SDL_UnlockMutex().
hidapi_thread_state_destroy()
void hidapi_thread_state_destroy (hidapi_thread_state * state) static
{
    SDL_DestroyThreadBarrier(&state->barrier);
    SDL_DestroyCondition(state->condition);
    SDL_DestroyMutex(state->mutex);
}
References hidapi_thread_state::barrier, hidapi_thread_state::condition, hidapi_thread_state::mutex, SDL_DestroyCondition(), SDL_DestroyMutex(), and SDL_DestroyThreadBarrier().
hidapi_thread_state_init()
void hidapi_thread_state_init (hidapi_thread_state * state) static
{
    state->mutex = SDL_CreateMutex();
    state->condition = SDL_CreateCondition();
    SDL_CreateThreadBarrier(&state->barrier, 2);
}
References hidapi_thread_state::barrier, hidapi_thread_state::condition, hidapi_thread_state::mutex, SDL_CreateCondition(), SDL_CreateMutex(), and SDL_CreateThreadBarrier().
RunInputThread()
int RunInputThread (void * param) static
{
    RunInputThreadParam *data = (RunInputThreadParam *)param;
    void *(*func)(void*) = data->func;
    void *func_arg = data->func_arg;
    SDL_free(data);
    func(func_arg);
    return 0;
}
References SDL_free().
Referenced by hidapi_thread_create().
SDL_CreateThreadBarrier()
int SDL_CreateThreadBarrier (SDL_ThreadBarrier * barrier, Uint32 count) static
{
    SDL_assert(barrier != NULL);
    SDL_assert(count != 0);
    barrier->mutex = SDL_CreateMutex();
    if (barrier->mutex == NULL) {
        return -1; /* Error set by CreateMutex */
    }
    barrier->cond = SDL_CreateCondition();
    if (barrier->cond == NULL) {
        return -1; /* Error set by CreateCond */
    }
    barrier->trip_count = count;
    barrier->count = 0;
    return 0;
}
References _SDL_ThreadBarrier::cond, _SDL_ThreadBarrier::count, count, _SDL_ThreadBarrier::mutex, NULL, SDL_assert, SDL_CreateCondition(), SDL_CreateMutex(), and _SDL_ThreadBarrier::trip_count.
Referenced by hidapi_thread_state_init().
SDL_DestroyThreadBarrier()
void SDL_DestroyThreadBarrier (SDL_ThreadBarrier * barrier) static
{
    SDL_DestroyCondition(barrier->cond);
    SDL_DestroyMutex(barrier->mutex);
}
References _SDL_ThreadBarrier::cond, _SDL_ThreadBarrier::mutex, SDL_DestroyCondition(), and SDL_DestroyMutex().
Referenced by hidapi_thread_state_destroy().
SDL_WaitThreadBarrier()
int SDL_WaitThreadBarrier (SDL_ThreadBarrier * barrier) static
{
    SDL_LockMutex(barrier->mutex);
    barrier->count += 1;
    if (barrier->count >= barrier->trip_count) {
        barrier->count = 0;
        SDL_BroadcastCondition(barrier->cond);
        SDL_UnlockMutex(barrier->mutex);
        return 1;
    }
    SDL_WaitCondition(barrier->cond, barrier->mutex);
    SDL_UnlockMutex(barrier->mutex);
    return 0;
}
References _SDL_ThreadBarrier::cond, _SDL_ThreadBarrier::count, _SDL_ThreadBarrier::mutex, SDL_BroadcastCondition(), SDL_LockMutex(), SDL_UnlockMutex(), SDL_WaitCondition(), and _SDL_ThreadBarrier::trip_count.
Referenced by hidapi_thread_barrier_wait().