SDL3: SDL-main/src/SDL_log.c File Reference
SDL_log.c File Reference
#include "SDL_internal.h"
#include "SDL_log_c.h"
#include "stdlib/SDL_vacopy.h"
Data Structures
struct SDL_LogLevel
Macros
#define DEFAULT_CATEGORY -1
#define SDL_MAX_LOG_MESSAGE_STACK 256
Typedefs
typedef struct SDL_LogLevel SDL_LogLevel
Functions
static void CleanupLogPrefixes (void)
static void CleanupLogPriorities (void)
static const char * GetLogPriorityPrefix (SDL_LogPriority priority)
static bool ParseLogCategory (const char *string, size_t length, int *category)
static void ParseLogPriorities (const char *hint)
static bool ParseLogPriority (const char *string, size_t length, SDL_LogPriority *priority)
static void SDL_CheckInitLog (void)
SDL_COMPILE_TIME_ASSERT (category_names, SDL_arraysize(SDL_category_names)==SDL_LOG_CATEGORY_RESERVED2)
SDL_COMPILE_TIME_ASSERT (priority_names, SDL_arraysize(SDL_priority_names)==SDL_LOG_PRIORITY_COUNT)
SDL_LogOutputFunction SDL_GetDefaultLogOutputFunction (void)
void SDL_GetLogOutputFunction (SDL_LogOutputFunction *callback, void **userdata)
SDL_LogPriority SDL_GetLogPriority (int category)
static SDL_LogOutputFunction SDL_log_function SDL_GUARDED_BY (SDL_log_function_lock) = NULL
static SDL_LogLevel *SDL_loglevels SDL_GUARDED_BY (SDL_log_lock)
void SDL_InitLog (void)
void SDL_Log (SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_LogCritical (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_LogDebug (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_LogError (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
static void SDLCALL SDL_LoggingChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
void SDL_LogInfo (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_LogMessage (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_LogMessageV (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap)
static void SDLCALL SDL_LogOutput (void *userdata, int category, SDL_LogPriority priority, const char *message)
void SDL_LogTrace (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_LogVerbose (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_LogWarn (int category, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
void SDL_QuitLog (void)
void SDL_ResetLogPriorities (void)
void SDL_SetLogOutputFunction (SDL_LogOutputFunction callback, void *userdata)
void SDL_SetLogPriorities (SDL_LogPriority priority)
void SDL_SetLogPriority (int category, SDL_LogPriority priority)
bool SDL_SetLogPriorityPrefix (SDL_LogPriority priority, const char *prefix)
Variables
static const char *const SDL_category_names []
static SDL_Mutex * SDL_log_function_lock
static SDL_InitState SDL_log_init
static SDL_Mutex * SDL_log_lock
static const char *const SDL_priority_names []
Macro Definition Documentation
DEFAULT_CATEGORY
#define DEFAULT_CATEGORY -1
Referenced by ParseLogCategory(), and ParseLogPriorities().
SDL_MAX_LOG_MESSAGE_STACK
#define SDL_MAX_LOG_MESSAGE_STACK 256
Referenced by SDL_LogMessageV().
Typedef Documentation
SDL_LogLevel
typedef struct SDL_LogLevel SDL_LogLevel
Function Documentation
CleanupLogPrefixes()
void CleanupLogPrefixes (void) static
{
    for (int i = 0; i < SDL_arraysize(SDL_priority_prefixes); ++i) {
        if (SDL_priority_prefixes[i]) {
            SDL_free(SDL_priority_prefixes[i]);
            SDL_priority_prefixes[i] = NULL;
        }
    }
}
References NULL, SDL_arraysize, and SDL_free().
Referenced by SDL_QuitLog().
CleanupLogPriorities()
void CleanupLogPriorities (void) static
{
    while (SDL_loglevels) {
        SDL_LogLevel *entry = SDL_loglevels;
        SDL_loglevels = entry->next;
        SDL_free(entry);
    }
}
References SDL_LogLevel::next, and SDL_free().
Referenced by SDL_QuitLog(), SDL_ResetLogPriorities(), and SDL_SetLogPriorities().
GetLogPriorityPrefix()
const char * GetLogPriorityPrefix (SDL_LogPriority priority) static
{
    if (priority <= SDL_LOG_PRIORITY_INVALID || priority >= SDL_LOG_PRIORITY_COUNT) {
        return "";
    }
    if (SDL_priority_prefixes[priority]) {
        return SDL_priority_prefixes[priority];
    }
    switch (priority) {
    case SDL_LOG_PRIORITY_WARN:
        return "WARNING: ";
    case SDL_LOG_PRIORITY_ERROR:
        return "ERROR: ";
    case SDL_LOG_PRIORITY_CRITICAL:
        return "ERROR: ";
    default:
        return "";
    }
}
References SDL_LogLevel::priority, SDL_LOG_PRIORITY_COUNT, SDL_LOG_PRIORITY_CRITICAL, SDL_LOG_PRIORITY_ERROR, and SDL_LOG_PRIORITY_WARN.
Referenced by SDL_LogOutput().
ParseLogCategory()
bool ParseLogCategory (const char * string, size_t length, int * category) static
{
    int i;
    if (SDL_isdigit(*string)) {
        *category = SDL_atoi(string);
        return true;
    }
    if (*string == '*') {
        *category = DEFAULT_CATEGORY;
        return true;
    }
    for (i = 0; i < SDL_arraysize(SDL_category_names); ++i) {
        if (SDL_strncasecmp(string, SDL_category_names[i], length) == 0) {
            *category = i;
            return true;
        }
    }
    return false;
}
References SDL_LogLevel::category, DEFAULT_CATEGORY, SDL_arraysize, SDL_atoi(), SDL_category_names, SDL_isdigit(), and SDL_strncasecmp().
Referenced by ParseLogPriorities().
ParseLogPriorities()
void ParseLogPriorities (const char * hint) static
{
    const char *name, *next;
    int category = DEFAULT_CATEGORY;
    SDL_LogPriority priority = SDL_LOG_PRIORITY_INVALID;
    if (SDL_strchr(hint, '=') == NULL) {
        if (ParseLogPriority(hint, SDL_strlen(hint), &priority)) {
            SDL_SetLogPriorities(priority);
        }
        return;
    }
    for (name = hint; name; name = next) {
        const char *sep = SDL_strchr(name, '=');
        if (!sep) {
            break;
        }
        next = SDL_strchr(sep, ',');
        if (next) {
            ++next;
        }
        if (ParseLogCategory(name, (sep - name), &category)) {
            const char *value = sep + 1;
            size_t len;
            if (next) {
                len = (next - value - 1);
            } else {
                len = SDL_strlen(value);
            }
            if (ParseLogPriority(value, len, &priority)) {
                if (category == DEFAULT_CATEGORY) {
                    for (int i = 0; i < SDL_arraysize(SDL_log_priorities); ++i) {
                        if (SDL_log_priorities[i] == SDL_LOG_PRIORITY_INVALID) {
                            SDL_log_priorities[i] = priority;
                        }
                    }
                    SDL_log_default_priority = priority;
                } else {
                    SDL_SetLogPriority(category, priority);
                }
            }
        }
    }
}
References SDL_LogLevel::category, DEFAULT_CATEGORY, SDL_LogLevel::next, NULL, ParseLogCategory(), ParseLogPriority(), SDL_LogLevel::priority, SDL_arraysize, SDL_LOG_PRIORITY_INVALID, SDL_SetLogPriorities(), SDL_SetLogPriority(), SDL_strchr(), and SDL_strlen().
Referenced by SDL_ResetLogPriorities().
ParseLogPriority()
bool ParseLogPriority (const char * string, size_t length, SDL_LogPriority * priority) static
{
    int i;
    if (SDL_isdigit(*string)) {
        i = SDL_atoi(string);
        if (i == 0) {
            // 0 has a special meaning of "disable this category"
            *priority = SDL_LOG_PRIORITY_COUNT;
            return true;
        }
        if (i > SDL_LOG_PRIORITY_INVALID && i < SDL_LOG_PRIORITY_COUNT) {
            *priority = (SDL_LogPriority)i;
            return true;
        }
        return false;
    }
    if (SDL_strncasecmp(string, "quiet", length) == 0) {
        *priority = SDL_LOG_PRIORITY_COUNT;
        return true;
    }
    for (i = SDL_LOG_PRIORITY_INVALID + 1; i < SDL_LOG_PRIORITY_COUNT; ++i) {
        if (SDL_strncasecmp(string, SDL_priority_names[i], length) == 0) {
            *priority = (SDL_LogPriority)i;
            return true;
        }
    }
    return false;
}
References SDL_LogLevel::priority, SDL_atoi(), SDL_isdigit(), SDL_LOG_PRIORITY_COUNT, SDL_LOG_PRIORITY_INVALID, SDL_priority_names, and SDL_strncasecmp().
Referenced by ParseLogPriorities().
SDL_CheckInitLog()
void SDL_CheckInitLog (void) static
{
    int status = SDL_GetAtomicInt(&SDL_log_init.status);
    if (status == SDL_INIT_STATUS_INITIALIZED ||
        (status == SDL_INIT_STATUS_INITIALIZING && SDL_log_init.thread == SDL_GetCurrentThreadID())) {
        return;
    }
    SDL_InitLog();
}
References SDL_GetAtomicInt(), SDL_GetCurrentThreadID(), SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_INITIALIZING, SDL_InitLog(), and SDL_log_init.
Referenced by SDL_GetLogPriority(), SDL_ResetLogPriorities(), SDL_SetLogPriorities(), and SDL_SetLogPriority().
SDL_COMPILE_TIME_ASSERT() [1/2]
SDL_COMPILE_TIME_ASSERT (category_names , SDL_arraysize(SDL_category_names) = =SDL_LOG_CATEGORY_RESERVED2)
References SDL_category_names, and SDL_LOG_CATEGORY_RESERVED2.
SDL_COMPILE_TIME_ASSERT() [2/2]
SDL_COMPILE_TIME_ASSERT (priority_names , SDL_arraysize(SDL_priority_names) = =SDL_LOG_PRIORITY_COUNT)
References SDL_log_function_lock, SDL_LOG_PRIORITY_COUNT, and SDL_priority_names.
SDL_GetDefaultLogOutputFunction()
SDL_LogOutputFunction SDL_GetDefaultLogOutputFunction (void)
Get the default log output function.
Returns
the default log output callback.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogOutputFunction
SDL_GetLogOutputFunction
{
    return SDL_LogOutput;
}
References SDL_LogOutput().
SDL_GetLogOutputFunction()
void SDL_GetLogOutputFunction (SDL_LogOutputFunction * callback, void ** userdata)
Get the current log output function.
Parameters
callback an SDL_LogOutputFunction filled in with the current log callback.
userdata a pointer filled in with the pointer that is passed to callback.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDefaultLogOutputFunction
SDL_SetLogOutputFunction
{
    SDL_LockMutex(SDL_log_function_lock);
    {
        if (callback) {
            *callback = SDL_log_function;
        }
        if (userdata) {
            *userdata = SDL_log_userdata;
        }
    }
    SDL_UnlockMutex(SDL_log_function_lock);
}
References SDL_LockMutex(), SDL_log_function_lock, and SDL_UnlockMutex().
SDL_GetLogPriority()
SDL_LogPriority SDL_GetLogPriority (int category)
Get the priority of a particular log category.
Parameters
category the category to query.
Returns
the SDL_LogPriority for the requested category.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogPriority
{
    SDL_LogLevel *entry;
    SDL_LogPriority priority = SDL_LOG_PRIORITY_INVALID;
    SDL_CheckInitLog();
    // Bypass the lock for known categories
    // Technically if the priority was set on a different CPU the value might not
    // be visible on this CPU for a while, but in practice it's fast enough that
    // this performance improvement is worthwhile.
    if (category >= 0 && category < SDL_arraysize(SDL_log_priorities)) {
        return SDL_log_priorities[category];
    }
    SDL_LockMutex(SDL_log_lock);
    {
        if (category >= 0 && category < SDL_arraysize(SDL_log_priorities)) {
            priority = SDL_log_priorities[category];
        } else {
            for (entry = SDL_loglevels; entry; entry = entry->next) {
                if (entry->category == category) {
                    priority = entry->priority;
                    break;
                }
            }
            if (priority == SDL_LOG_PRIORITY_INVALID) {
                priority = SDL_log_default_priority;
            }
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
    return priority;
}
References SDL_LogLevel::category, SDL_LogLevel::next, SDL_LogLevel::priority, SDL_arraysize, SDL_CheckInitLog(), SDL_LockMutex(), SDL_log_lock, SDL_LOG_PRIORITY_INVALID, and SDL_UnlockMutex().
Referenced by SDL_LogMessageV().
SDL_GUARDED_BY() [1/2]
void *SDL_log_userdata SDL_GUARDED_BY (SDL_log_function_lock) = NULL static
References NULL, SDL_log_function_lock, and SDL_LogOutput().
SDL_GUARDED_BY() [2/2]
SDL_LogPriority SDL_log_default_priority SDL_GUARDED_BY (SDL_log_lock) static
References SDL_LOG_CATEGORY_CUSTOM, and SDL_log_lock.
SDL_InitLog()
void SDL_InitLog (void)
{
    if (!SDL_ShouldInit(&SDL_log_init)) {
        return;
    }
    // If these fail we'll continue without them.
    SDL_log_lock = SDL_CreateMutex();
    SDL_log_function_lock = SDL_CreateMutex();
    SDL_AddHintCallback(SDL_HINT_LOGGING, SDL_LoggingChanged, NULL);
    SDL_SetInitialized(&SDL_log_init, true);
}
References NULL, SDL_AddHintCallback(), SDL_CreateMutex(), SDL_HINT_LOGGING, SDL_log_function_lock, SDL_log_init, SDL_log_lock, SDL_LoggingChanged(), SDL_SetInitialized(), and SDL_ShouldInit().
Referenced by SDL_CheckInitLog().
SDL_Log()
void SDL_Log (SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_CATEGORY_APPLICATION and SDL_LOG_PRIORITY_INFO.
Parameters
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_PRIORITY_INFO, fmt, ap);
    va_end(ap);
}
References SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_PRIORITY_INFO, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by AddDeviceToEnumeration(), CameraThread(), ConvertAudio(), DebugLogRenderCommands(), E32Main(), GetAudioStreamDataInternal(), LogOneLeakedObject(), PLATFORM_hid_init(), PutAudioStreamBuffer(), RequestBluetoothPermissionCallback(), SDL_AddCamera(), SDL_CameraDisconnected(), SDL_CameraThreadIterate(), SDL_DebugLogBackend(), SDL_DumpPropertiesCallback(), SDL_GetAudioStreamDataAdjustGain(), SDL_LogEvent(), SDL_OpenCamera(), SDL_PrivateSendMouseMotion(), SDL_PutAudioStreamPlanarData(), SDL_ResetKeyboard(), SDL_SendKeyboardKeyInternal(), SDL_StopEventLoop(), SDL_UpdateMouseFocus(), and ZombieAcquireFrame().
SDL_LogCritical()
void SDL_LogCritical (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_PRIORITY_CRITICAL.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_CRITICAL, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_CRITICAL, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogDebug()
void SDL_LogDebug (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_PRIORITY_DEBUG.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_DEBUG, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_DEBUG, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by GDK_RegisterChangeNotifications(), and SDL_hid_init().
SDL_LogError()
void SDL_LogError (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_PRIORITY_ERROR.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_ERROR, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_ERROR, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by SDL_SetErrorV().
SDL_LoggingChanged()
void SDLCALL SDL_LoggingChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    SDL_ResetLogPriorities();
}
References SDL_ResetLogPriorities(), and SDLCALL.
Referenced by SDL_InitLog(), and SDL_QuitLog().
SDL_LogInfo()
void SDL_LogInfo (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_PRIORITY_INFO.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_INFO, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_INFO, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by SDL_CreateRendererWithProperties(), and SDL_InitMainThread().
SDL_LogMessage()
void SDL_LogMessage (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with the specified category and priority.
Parameters
category the category of the message.
priority the priority of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, priority, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LogLevel::priority, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogMessageV()
void SDL_LogMessageV (int category, SDL_LogPriority priority, SDL_PRINTF_FORMAT_STRING const char * fmt, va_list ap)
Log a message with the specified category and priority.
Parameters
category the category of the message.
priority the priority of the message.
fmt a printf() style message format string.
ap a variable argument list.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    char *message = NULL;
    char stack_buf[SDL_MAX_LOG_MESSAGE_STACK];
    size_t len_plus_term;
    int len;
    va_list aq;
    // Nothing to do if we don't have an output function
    if (!SDL_log_function) {
        return;
    }
    // See if we want to do anything with this message
    if (priority < SDL_GetLogPriority(category)) {
        return;
    }
#if defined(SDL_PLATFORM_NGAGE)
    extern void NGAGE_vnprintf(char *buf, size_t size, const char *fmt, va_list ap);
    char buf[1024];
    NGAGE_vnprintf(buf, sizeof(buf), fmt, ap);
#ifdef ENABLE_FILE_LOG
    FILE* file;
    file = fopen("E:/SDL_Log.txt", "a");
    if (file)
    {
        vfprintf(file, fmt, ap);
        fprintf(file, "\n");
        (void)fclose(file);
    }
#endif
    return;
#endif
    // Render into stack buffer
    va_copy(aq, ap);
    len = SDL_vsnprintf(stack_buf, sizeof(stack_buf), fmt, aq);
    va_end(aq);
    if (len < 0) {
        return;
    }
    // If message truncated, allocate and re-render
    if (len >= sizeof(stack_buf) && SDL_size_add_check_overflow(len, 1, &len_plus_term)) {
        // Allocate exactly what we need, including the zero-terminator
        message = (char *)SDL_malloc(len_plus_term);
        if (!message) {
            return;
        }
        va_copy(aq, ap);
        len = SDL_vsnprintf(message, len_plus_term, fmt, aq);
        va_end(aq);
    } else {
        message = stack_buf;
    }
    // Chop off final endline.
    if ((len > 0) && (message[len - 1] == '\n')) {
        message[--len] = '\0';
        if ((len > 0) && (message[len - 1] == '\r')) { // catch "\r\n", too.
            message[--len] = '\0';
        }
    }
    SDL_LockMutex(SDL_log_function_lock);
    {
        SDL_log_function(SDL_log_userdata, category, priority, message);
    }
    SDL_UnlockMutex(SDL_log_function_lock);
    // Free only if dynamically allocated
    if (message != stack_buf) {
        SDL_free(message);
    }
}
References SDL_LogLevel::category, NGAGE_vnprintf(), NULL, SDL_LogLevel::priority, SDL_free(), SDL_GetLogPriority(), SDL_LockMutex(), SDL_log_function_lock, SDL_malloc(), SDL_MAX_LOG_MESSAGE_STACK, SDL_PRINTF_FORMAT_STRING, SDL_size_add_check_overflow(), SDL_UnlockMutex(), SDL_vsnprintf(), and void().
Referenced by debug_print(), SDL_Log(), SDL_LogCritical(), SDL_LogDebug(), SDL_LogError(), SDL_LogInfo(), SDL_LogMessage(), SDL_LogTrace(), SDL_LogVerbose(), and SDL_LogWarn().
SDL_LogOutput()
void SDLCALL SDL_LogOutput (void * userdata, int category, SDL_LogPriority priority, const char * message) static
{
#if defined(SDL_PLATFORM_WINDOWS)
    // Way too many allocations here, urgh
    // Note: One can't call SDL_SetError here, since that function itself logs.
    {
        char *output;
        size_t length;
        LPTSTR tstr;
        bool isstack;
#if !defined(SDL_PLATFORM_GDK)
        BOOL attachResult;
        DWORD attachError;
        DWORD consoleMode;
        DWORD charsWritten;
        // Maybe attach console and get stderr handle
        if (consoleAttached == CONSOLE_UNATTACHED) {
            attachResult = AttachConsole(ATTACH_PARENT_PROCESS);
            if (!attachResult) {
                attachError = GetLastError();
                if (attachError == ERROR_INVALID_HANDLE) {
                    // This is expected when running from Visual Studio
                    // OutputDebugString(TEXT("Parent process has no console\r\n"));
                    consoleAttached = CONSOLE_ATTACHED_ERROR;
                } else if (attachError == ERROR_GEN_FAILURE) {
                    OutputDebugString(TEXT("Could not attach to console of parent process\r\n"));
                    consoleAttached = CONSOLE_ATTACHED_ERROR;
                } else if (attachError == ERROR_ACCESS_DENIED) {
                    // Already attached
                    consoleAttached = CONSOLE_ATTACHED_CONSOLE;
                } else {
                    OutputDebugString(TEXT("Error attaching console\r\n"));
                    consoleAttached = CONSOLE_ATTACHED_ERROR;
                }
            } else {
                // Newly attached
                consoleAttached = CONSOLE_ATTACHED_CONSOLE;
            }
            if (consoleAttached == CONSOLE_ATTACHED_CONSOLE) {
                stderrHandle = GetStdHandle(STD_ERROR_HANDLE);
                if (GetConsoleMode(stderrHandle, &consoleMode) == 0) {
                    // WriteConsole fails if the output is redirected to a file. Must use WriteFile instead.
                    consoleAttached = CONSOLE_ATTACHED_FILE;
                }
            }
        }
#endif // !defined(SDL_PLATFORM_GDK)
        length = SDL_strlen(GetLogPriorityPrefix(priority)) + SDL_strlen(message) + 1 + 1 + 1;
        output = SDL_small_alloc(char, length, &isstack);
        if (!output) {
            return;
        }
        (void)SDL_snprintf(output, length, "%s%s\r\n", GetLogPriorityPrefix(priority), message);
        tstr = WIN_UTF8ToString(output);
        // Output to debugger
        OutputDebugString(tstr);
#if !defined(SDL_PLATFORM_GDK)
        // Screen output to stderr, if console was attached.
        if (consoleAttached == CONSOLE_ATTACHED_CONSOLE) {
            if (!WriteConsole(stderrHandle, tstr, (DWORD)SDL_tcslen(tstr), &charsWritten, NULL)) {
                OutputDebugString(TEXT("Error calling WriteConsole\r\n"));
                if (GetLastError() == ERROR_NOT_ENOUGH_MEMORY) {
                    OutputDebugString(TEXT("Insufficient heap memory to write message\r\n"));
                }
            }
        } else if (consoleAttached == CONSOLE_ATTACHED_FILE) {
            if (!WriteFile(stderrHandle, output, (DWORD)SDL_strlen(output), &charsWritten, NULL)) {
                OutputDebugString(TEXT("Error calling WriteFile\r\n"));
            }
        }
#endif // !defined(SDL_PLATFORM_GDK)
        SDL_free(tstr);
        SDL_small_free(output, isstack);
    }
#elif defined(SDL_PLATFORM_ANDROID)
    {
        char tag[32];
        SDL_snprintf(tag, SDL_arraysize(tag), "SDL/%s", GetCategoryPrefix(category));
        __android_log_write(SDL_android_priority[priority], tag, message);
    }
#elif defined(SDL_PLATFORM_APPLE) && (defined(SDL_VIDEO_DRIVER_COCOA) || defined(SDL_VIDEO_DRIVER_UIKIT))
    /* Technically we don't need Cocoa/UIKit, but that's where this function is defined for now.
     */
    extern void SDL_NSLog(const char *prefix, const char *text);
    {
        SDL_NSLog(GetLogPriorityPrefix(priority), message);
        return;
    }
#elif defined(SDL_PLATFORM_PSP) || defined(SDL_PLATFORM_PS2)
    {
        FILE *pFile;
        pFile = fopen("SDL_Log.txt", "a");
        if (pFile) {
            (void)fprintf(pFile, "%s%s\n", GetLogPriorityPrefix(priority), message);
            (void)fclose(pFile);
        }
    }
#elif defined(SDL_PLATFORM_VITA)
    {
        FILE *pFile;
        pFile = fopen("ux0:/data/SDL_Log.txt", "a");
        if (pFile) {
            (void)fprintf(pFile, "%s%s\n", GetLogPriorityPrefix(priority), message);
            (void)fclose(pFile);
        }
    }
#elif defined(SDL_PLATFORM_3DS)
    {
        FILE *pFile;
        pFile = fopen("sdmc:/3ds/SDL_Log.txt", "a");
        if (pFile) {
            (void)fprintf(pFile, "%s%s\n", GetLogPriorityPrefix(priority), message);
            (void)fclose(pFile);
        }
    }
#elif defined(SDL_PLATFORM_NGAGE)
    {
        /* Nothing to do here. */
    }
#endif
#if defined(HAVE_STDIO_H) && \
    !(defined(SDL_PLATFORM_APPLE) && (defined(SDL_VIDEO_DRIVER_COCOA) || defined(SDL_VIDEO_DRIVER_UIKIT))) && \
    !(defined(SDL_PLATFORM_NGAGE)) && \
    !(defined(SDL_PLATFORM_WIN32))
    (void)fprintf(stderr, "%s%s\n", GetLogPriorityPrefix(priority), message);
#endif
}
References SDL_LogLevel::category, GetLogPriorityPrefix(), NULL, SDL_LogLevel::priority, SDL_arraysize, SDL_free(), SDL_small_alloc, SDL_small_free, SDL_snprintf(), SDL_strlen(), SDL_tcslen, SDLCALL, void(), and WIN_UTF8ToString.
Referenced by SDL_GetDefaultLogOutputFunction(), and SDL_GUARDED_BY().
SDL_LogTrace()
void SDL_LogTrace (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_PRIORITY_TRACE.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_TRACE, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_TRACE, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogVerbose()
void SDL_LogVerbose (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_PRIORITY_VERBOSE.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogWarn
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_VERBOSE, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_VERBOSE, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
SDL_LogWarn()
void SDL_LogWarn (int category, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Log a message with SDL_LOG_PRIORITY_WARN.
Parameters
category the category of the message.
fmt a printf() style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Log
SDL_LogCritical
SDL_LogDebug
SDL_LogError
SDL_LogInfo
SDL_LogMessage
SDL_LogMessageV
SDL_LogTrace
SDL_LogVerbose
{
    va_list ap;
    va_start(ap, fmt);
    SDL_LogMessageV(category, SDL_LOG_PRIORITY_WARN, fmt, ap);
    va_end(ap);
}
References SDL_LogLevel::category, SDL_LOG_PRIORITY_WARN, SDL_LogMessageV(), and SDL_PRINTF_FORMAT_STRING.
Referenced by HIDAPI_InitializeDiscovery(), and SDL_SYS_GetPrefPath().
SDL_QuitLog()
void SDL_QuitLog (void)
{
    if (!SDL_ShouldQuit(&SDL_log_init)) {
        return;
    }
    SDL_RemoveHintCallback(SDL_HINT_LOGGING, SDL_LoggingChanged, NULL);
    CleanupLogPriorities();
    CleanupLogPrefixes();
    if (SDL_log_lock) {
        SDL_DestroyMutex(SDL_log_lock);
        SDL_log_lock = NULL;
    }
    if (SDL_log_function_lock) {
        SDL_DestroyMutex(SDL_log_function_lock);
        SDL_log_function_lock = NULL;
    }
    SDL_SetInitialized(&SDL_log_init, false);
}
References CleanupLogPrefixes(), CleanupLogPriorities(), NULL, SDL_DestroyMutex(), SDL_HINT_LOGGING, SDL_log_function_lock, SDL_log_init, SDL_log_lock, SDL_LoggingChanged(), SDL_RemoveHintCallback(), SDL_SetInitialized(), and SDL_ShouldQuit().
Referenced by SDL_Quit().
SDL_ResetLogPriorities()
void SDL_ResetLogPriorities (void)
Reset all priorities to default.
This is called by SDL_Quit().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogPriorities
SDL_SetLogPriority
{
    SDL_CheckInitLog();
    SDL_LockMutex(SDL_log_lock);
    {
        CleanupLogPriorities();
        SDL_log_default_priority = SDL_LOG_PRIORITY_INVALID;
        for (int i = 0; i < SDL_arraysize(SDL_log_priorities); ++i) {
            SDL_log_priorities[i] = SDL_LOG_PRIORITY_INVALID;
        }
        const char *hint = SDL_GetHint(SDL_HINT_LOGGING);
        if (hint) {
            ParseLogPriorities(hint);
        }
        if (SDL_log_default_priority == SDL_LOG_PRIORITY_INVALID) {
            SDL_log_default_priority = SDL_LOG_PRIORITY_ERROR;
        }
        for (int i = 0; i < SDL_arraysize(SDL_log_priorities); ++i) {
            if (SDL_log_priorities[i] != SDL_LOG_PRIORITY_INVALID) {
                continue;
            }
            switch (i) {
            case SDL_LOG_CATEGORY_APPLICATION:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_INFO;
                break;
            case SDL_LOG_CATEGORY_ASSERT:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_WARN;
                break;
            case SDL_LOG_CATEGORY_TEST:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_VERBOSE;
                break;
            default:
                SDL_log_priorities[i] = SDL_LOG_PRIORITY_ERROR;
                break;
            }
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
}
References CleanupLogPriorities(), ParseLogPriorities(), SDL_arraysize, SDL_CheckInitLog(), SDL_GetHint(), SDL_HINT_LOGGING, SDL_LockMutex(), SDL_LOG_CATEGORY_APPLICATION, SDL_LOG_CATEGORY_ASSERT, SDL_LOG_CATEGORY_TEST, SDL_log_lock, SDL_LOG_PRIORITY_ERROR, SDL_LOG_PRIORITY_INFO, SDL_LOG_PRIORITY_INVALID, SDL_LOG_PRIORITY_VERBOSE, SDL_LOG_PRIORITY_WARN, and SDL_UnlockMutex().
Referenced by SDL_LoggingChanged().
SDL_SetLogOutputFunction()
void SDL_SetLogOutputFunction (SDL_LogOutputFunction callback, void * userdata)
Replace the default log output function with one of your own.
Parameters
callback an SDL_LogOutputFunction to call instead of the default.
userdata a pointer that is passed to callback.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDefaultLogOutputFunction
SDL_GetLogOutputFunction
{
    SDL_LockMutex(SDL_log_function_lock);
    {
        SDL_log_function = callback;
        SDL_log_userdata = userdata;
    }
    SDL_UnlockMutex(SDL_log_function_lock);
}
References SDL_LockMutex(), SDL_log_function_lock, and SDL_UnlockMutex().
SDL_SetLogPriorities()
void SDL_SetLogPriorities (SDL_LogPriority priority)
Set the priority of all log categories.
Parameters
priority the SDL_LogPriority to assign.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResetLogPriorities
SDL_SetLogPriority
{
    SDL_CheckInitLog();
    SDL_LockMutex(SDL_log_lock);
    {
        CleanupLogPriorities();
        SDL_log_default_priority = priority;
        for (int i = 0; i < SDL_arraysize(SDL_log_priorities); ++i) {
            SDL_log_priorities[i] = priority;
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
}
References CleanupLogPriorities(), SDL_LogLevel::priority, SDL_arraysize, SDL_CheckInitLog(), SDL_LockMutex(), SDL_log_lock, and SDL_UnlockMutex().
Referenced by ParseLogPriorities().
SDL_SetLogPriority()
void SDL_SetLogPriority (int category, SDL_LogPriority priority)
Set the priority of a particular log category.
Parameters
category the category to assign a priority to.
priority the SDL_LogPriority to assign.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetLogPriority
SDL_ResetLogPriorities
SDL_SetLogPriorities
{
    SDL_LogLevel *entry;
    SDL_CheckInitLog();
    SDL_LockMutex(SDL_log_lock);
    {
        if (category >= 0 && category < SDL_arraysize(SDL_log_priorities)) {
            SDL_log_priorities[category] = priority;
        } else {
            for (entry = SDL_loglevels; entry; entry = entry->next) {
                if (entry->category == category) {
                    entry->priority = priority;
                    break;
                }
            }
            if (!entry) {
                entry = (SDL_LogLevel *)SDL_malloc(sizeof(*entry));
                if (entry) {
                    entry->category = category;
                    entry->priority = priority;
                    entry->next = SDL_loglevels;
                    SDL_loglevels = entry;
                }
            }
        }
    }
    SDL_UnlockMutex(SDL_log_lock);
}
References SDL_LogLevel::category, SDL_LogLevel::next, SDL_LogLevel::priority, SDL_arraysize, SDL_CheckInitLog(), SDL_LockMutex(), SDL_log_lock, SDL_malloc(), and SDL_UnlockMutex().
Referenced by ParseLogPriorities().
SDL_SetLogPriorityPrefix()
bool SDL_SetLogPriorityPrefix (SDL_LogPriority priority, const char * prefix)
Set the text prepended to log messages of a given priority.
By default SDL_LOG_PRIORITY_INFO and below have no prefix, and SDL_LOG_PRIORITY_WARN and higher have a prefix showing their priority, e.g. "WARNING: ".
This function makes a copy of its string argument, prefix, so it is not necessary to keep the value of prefix alive after the call returns.
Parameters
priority the SDL_LogPriority to modify.
prefix the prefix to use for that log priority, or NULL to use no prefix.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetLogPriorities
SDL_SetLogPriority
{
    char *prefix_copy;
    if (priority <= SDL_LOG_PRIORITY_INVALID || priority >= SDL_LOG_PRIORITY_COUNT) {
        return SDL_InvalidParamError("priority");
    }
    if (!prefix || !*prefix) {
        prefix_copy = SDL_strdup("");
    } else {
        prefix_copy = SDL_strdup(prefix);
    }
    if (!prefix_copy) {
        return false;
    }
    SDL_LockMutex(SDL_log_function_lock);
    {
        if (SDL_priority_prefixes[priority]) {
            SDL_free(SDL_priority_prefixes[priority]);
        }
        SDL_priority_prefixes[priority] = prefix_copy;
    }
    SDL_UnlockMutex(SDL_log_function_lock);
    return true;
}
References SDL_LogLevel::priority, SDL_free(), SDL_InvalidParamError, SDL_LockMutex(), SDL_log_function_lock, SDL_LOG_PRIORITY_COUNT, SDL_strdup(), and SDL_UnlockMutex().
Variable Documentation
SDL_category_names
const char* const SDL_category_names[] static
Initial value:
= {
    "APP",
    "ERROR",
    "ASSERT",
    "SYSTEM",
    "AUDIO",
    "VIDEO",
    "RENDER",
    "INPUT",
    "TEST",
    "GPU"
}
{
    "APP",
    "ERROR",
    "ASSERT",
    "SYSTEM",
    "AUDIO",
    "VIDEO",
    "RENDER",
    "INPUT",
    "TEST",
    "GPU"
};
Referenced by ParseLogCategory(), and SDL_COMPILE_TIME_ASSERT().
SDL_log_function_lock
SDL_Mutex* SDL_log_function_lock static
Referenced by SDL_COMPILE_TIME_ASSERT(), SDL_GetLogOutputFunction(), SDL_GUARDED_BY(), SDL_InitLog(), SDL_LogMessageV(), SDL_QuitLog(), SDL_SetLogOutputFunction(), and SDL_SetLogPriorityPrefix().
SDL_log_init
SDL_InitState SDL_log_init static
Referenced by SDL_CheckInitLog(), SDL_InitLog(), and SDL_QuitLog().
SDL_log_lock
SDL_Mutex* SDL_log_lock static
Referenced by SDL_GetLogPriority(), SDL_GUARDED_BY(), SDL_InitLog(), SDL_QuitLog(), SDL_ResetLogPriorities(), SDL_SetLogPriorities(), and SDL_SetLogPriority().
SDL_priority_names
const char* const SDL_priority_names[] static
Initial value:
= {
    NULL,
    "TRACE",
    "VERBOSE",
    "DEBUG",
    "INFO",
    "WARN",
    "ERROR",
    "CRITICAL"
}
{
    NULL,
    "TRACE",
    "VERBOSE",
    "DEBUG",
    "INFO",
    "WARN",
    "ERROR",
    "CRITICAL"
};
Referenced by ParseLogPriority(), and SDL_COMPILE_TIME_ASSERT().