SDL3: SDL-main/src/SDL_hints_c.h File Reference
SDL_hints_c.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_GetStringBoolean (const char *value, bool default_value)
int SDL_GetStringInteger (const char *value, int default_value)
void SDL_InitHints (void)
void SDL_QuitHints (void)
Function Documentation
SDL_GetStringBoolean()
bool SDL_GetStringBoolean (const char * value, bool default_value) extern
{
    if (!value || !*value) {
        return default_value;
    }
    if (*value == '0' || SDL_strcasecmp(value, "false") == 0) {
        return false;
    }
    return true;
}
References SDL_strcasecmp().
Referenced by AutoShowingScreenKeyboard(), OnlyControllersChanged(), ResetHintsCallback(), SDL_AutoUpdateJoysticksChanged(), SDL_AutoUpdateSensorsChanged(), SDL_GetBooleanProperty(), SDL_GetHintBoolean(), SDL_JoystickAllowBackgroundEventsChanged(), SDL_MouseAutoCaptureChanged(), SDL_MouseRelativeCursorVisibleChanged(), SDL_MouseRelativeModeCenterChanged(), SDL_MouseRelativeSystemScaleChanged(), SDL_MouseRelativeWarpMotionChanged(), SDL_MouseTouchEventsChanged(), SDL_MouseWarpEmulationChanged(), SDL_PenMouseEventsChanged(), SDL_PenTouchEventsChanged(), SDL_PollSentinelChanged(), SDL_ResetHint(), SDL_SetHintWithPriority(), SDL_SyncHintWatcher(), SDL_TouchMouseEventsChanged(), and ShouldAttemptSensorFusion().
SDL_GetStringInteger()
int SDL_GetStringInteger (const char * value, int default_value) extern
{
    if (!value || !*value) {
        return default_value;
    }
    if (SDL_strcasecmp(value, "false") == 0) {
        return 0;
    }
    if (SDL_strcasecmp(value, "true") == 0) {
        return 1;
    }
    if (*value == '-' || SDL_isdigit(*value)) {
        return SDL_atoi(value);
    }
    return default_value;
}
References SDL_atoi(), SDL_isdigit(), and SDL_strcasecmp().
SDL_InitHints()
void SDL_InitHints (void) extern
{
}
SDL_QuitHints()
void SDL_QuitHints (void) extern
{
    SDL_PropertiesID props;
    do {
        props = SDL_GetAtomicU32(&SDL_hint_props);
    } while (!SDL_CompareAndSwapAtomicU32(&SDL_hint_props, props, 0));
    if (props) {
        SDL_DestroyProperties(props);
    }
}
References SDL_CompareAndSwapAtomicU32(), SDL_DestroyProperties(), SDL_GetAtomicU32(), and SDL_hint_props.
Referenced by SDL_Quit().