SDL3: SDL-main/src/dialog/haiku/SDL_haikudialog.cc File Reference
SDL_haikudialog.cc File Reference
#include "SDL_internal.h"
#include "../SDL_dialog.h"
#include "../SDL_dialog_utils.h"
#include "../../core/haiku/SDL_BeApp.h"
#include "../../video/haiku/SDL_BWin.h"
#include <string>
#include <vector>
#include <sys/stat.h>
#include <FilePanel.h>
#include <Entry.h>
#include <Looper.h>
#include <Messenger.h>
#include <Path.h>
#include <TypeConstants.h>
Data Structures
class CallbackLooper
class SDLBRefFilter
Functions
void SDL_SYS_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props)
bool StringEndsWith (const std::string &str, const std::string &end)
std::vector< std::string > StringSplit (const std::string &str, const std::string &split)
Function Documentation
SDL_SYS_ShowFileDialogWithProperties()
void SDL_SYS_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void * userdata, SDL_PropertiesID props)
{
    SDL_Window *window = (SDL_Window *)SDL_GetPointerProperty(props, SDL_PROP_FILE_DIALOG_WINDOW_POINTER, NULL);
    SDL_DialogFileFilter *filters = (SDL_DialogFileFilter *)SDL_GetPointerProperty(props, SDL_PROP_FILE_DIALOG_FILTERS_POINTER, NULL);
    int nfilters = (int) SDL_GetNumberProperty(props, SDL_PROP_FILE_DIALOG_NFILTERS_NUMBER, 0);
    bool many = SDL_GetBooleanProperty(props, SDL_PROP_FILE_DIALOG_MANY_BOOLEAN, false);
    const char *location = SDL_GetStringProperty(props, SDL_PROP_FILE_DIALOG_LOCATION_STRING, NULL);
    const char *title = SDL_GetStringProperty(props, SDL_PROP_FILE_DIALOG_TITLE_STRING, NULL);
    const char *accept = SDL_GetStringProperty(props, SDL_PROP_FILE_DIALOG_ACCEPT_STRING, NULL);
    const char *cancel = SDL_GetStringProperty(props, SDL_PROP_FILE_DIALOG_CANCEL_STRING, NULL);
    bool modal = !!window;
    bool save = false;
    bool folder = false;
    switch (type) {
    case SDL_FILEDIALOG_SAVEFILE:
        save = true;
        break;
    case SDL_FILEDIALOG_OPENFILE:
        break;
    case SDL_FILEDIALOG_OPENFOLDER:
        folder = true;
        break;
    };
    if (!SDL_InitBeApp()) {
        char *err = SDL_strdup(SDL_GetError());
        SDL_SetError("Couldn't init Be app: %s", err);
        SDL_free(err);
        callback(userdata, NULL, -1);
        return;
    }
    if (filters) {
        const char *msg = validate_filters(filters, nfilters);
        if (msg) {
            SDL_SetError("%s", msg);
            callback(userdata, NULL, -1);
            return;
        }
    }
    if (SDL_GetHint(SDL_HINT_FILE_DIALOG_DRIVER) != NULL) {
        SDL_SetError("File dialog driver unsupported");
        callback(userdata, NULL, -1);
        return;
    }
    // No unique_ptr's because they need to survive the end of the function
    CallbackLooper *looper = new(std::nothrow) CallbackLooper(callback, userdata);
    BMessenger *messenger = new(std::nothrow) BMessenger(NULL, looper);
    SDLBRefFilter *filter = new(std::nothrow) SDLBRefFilter(filters, nfilters);
    if (looper == NULL || messenger == NULL || filter == NULL) {
        delete looper;
        delete messenger;
        delete filter;
        SDL_OutOfMemory();
        callback(userdata, NULL, -1);
        return;
    }
    BEntry entry;
    entry_ref entryref;
    if (location) {
        entry.SetTo(location);
        entry.GetRef(&entryref);
    }
    BFilePanel *panel = new BFilePanel(save ? B_SAVE_PANEL : B_OPEN_PANEL, messenger, location ? &entryref : NULL, folder ? B_DIRECTORY_NODE : B_FILE_NODE, many, NULL, filter, modal);
    if (title) {
        panel->Window()->SetTitle(title);
    }
    if (accept) {
        panel->SetButtonLabel(B_DEFAULT_BUTTON, accept);
    }
    if (cancel) {
        panel->SetButtonLabel(B_CANCEL_BUTTON, cancel);
    }
    if (window) {
        SDL_BWin *bwin = (SDL_BWin *)(window->internal);
        panel->Window()->SetLook(B_MODAL_WINDOW_LOOK);
        panel->Window()->SetFeel(B_MODAL_SUBSET_WINDOW_FEEL);
        panel->Window()->AddToSubset(bwin);
    }
    looper->SetToBeFreed(messenger, panel, filter);
    looper->Run();
    panel->Show();
}
References NULL, SDL_FILEDIALOG_OPENFILE, SDL_FILEDIALOG_OPENFOLDER, SDL_FILEDIALOG_SAVEFILE, SDL_free(), SDL_GetBooleanProperty(), SDL_GetError(), SDL_GetHint(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetStringProperty(), SDL_HINT_FILE_DIALOG_DRIVER, SDL_InitBeApp(), SDL_OutOfMemory(), SDL_PROP_FILE_DIALOG_ACCEPT_STRING, SDL_PROP_FILE_DIALOG_CANCEL_STRING, SDL_PROP_FILE_DIALOG_FILTERS_POINTER, SDL_PROP_FILE_DIALOG_LOCATION_STRING, SDL_PROP_FILE_DIALOG_MANY_BOOLEAN, SDL_PROP_FILE_DIALOG_NFILTERS_NUMBER, SDL_PROP_FILE_DIALOG_TITLE_STRING, SDL_PROP_FILE_DIALOG_WINDOW_POINTER, SDL_SetError(), SDL_strdup(), CallbackLooper::SetToBeFreed(), and validate_filters().
StringEndsWith()
bool StringEndsWith (const std::string & str, const std::string & end)
{
    return str.size() >= end.size() && !str.compare(str.size() - end.size(), end.size(), end);
}
Referenced by SDLBRefFilter::Filter().
StringSplit()
std::vector< std::string > StringSplit (const std::string & str, const std::string & split)
{
    std::vector<std::string> result;
    std::string s = str;
    size_t pos = 0;
    while ((pos = s.find(split)) != std::string::npos) {
        result.push_back(s.substr(0, pos));
        s = s.substr(pos + split.size());
    }
    result.push_back(s);
    return result;
}
Referenced by SDLBRefFilter::Filter().