SDL3: SDL-main/src/camera/SDL_camera_c.h File Reference
SDL_camera_c.h File Reference
#include "../SDL_internal.h"
Functions
bool SDL_CameraInit (const char *driver_name)
void SDL_QuitCamera (void)
void SDL_UpdateCamera (void)
Function Documentation
SDL_CameraInit()
bool SDL_CameraInit (const char * driver_name) extern
{
    if (SDL_GetCurrentCameraDriver()) {
        SDL_QuitCamera(); // shutdown driver if already running.
    }
    SDL_RWLock *device_hash_lock = SDL_CreateRWLock();  // create this early, so if it fails we don't have to tear down the whole camera subsystem.
    if (!device_hash_lock) {
        return false;
    }
    SDL_HashTable *device_hash = SDL_CreateHashTable(0, false, SDL_HashID, SDL_KeyMatchID, DestroyCameraHashItem, NULL);
    if (!device_hash) {
        SDL_DestroyRWLock(device_hash_lock);
        return false;
    }
    // Select the proper camera driver
    if (!driver_name) {
        driver_name = SDL_GetHint(SDL_HINT_CAMERA_DRIVER);
    }
    bool initialized = false;
    bool tried_to_init = false;
    if (driver_name && (*driver_name != 0)) {
        char *driver_name_copy = SDL_strdup(driver_name);
        const char *driver_attempt = driver_name_copy;
        if (!driver_name_copy) {
            SDL_DestroyRWLock(device_hash_lock);
            SDL_DestroyHashTable(device_hash);
            return false;
        }
        while (driver_attempt && (*driver_attempt != 0) && !initialized) {
            char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            if (driver_attempt_end) {
                *driver_attempt_end = '\0';
            }
            for (int i = 0; bootstrap[i]; i++) {
                if (SDL_strcasecmp(bootstrap[i]->name, driver_attempt) == 0) {
                    tried_to_init = true;
                    SDL_zero(camera_driver);
                    camera_driver.pending_events_tail = &camera_driver.pending_events;
                    camera_driver.device_hash_lock = device_hash_lock;
                    camera_driver.device_hash = device_hash;
                    if (bootstrap[i]->init(&camera_driver.impl)) {
                        camera_driver.name = bootstrap[i]->name;
                        camera_driver.desc = bootstrap[i]->desc;
                        initialized = true;
                    }
                    break;
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
        SDL_free(driver_name_copy);
    } else {
        for (int i = 0; !initialized && bootstrap[i]; i++) {
            if (bootstrap[i]->demand_only) {
                continue;
            }
            tried_to_init = true;
            SDL_zero(camera_driver);
            camera_driver.pending_events_tail = &camera_driver.pending_events;
            camera_driver.device_hash_lock = device_hash_lock;
            camera_driver.device_hash = device_hash;
            if (bootstrap[i]->init(&camera_driver.impl)) {
                camera_driver.name = bootstrap[i]->name;
                camera_driver.desc = bootstrap[i]->desc;
                initialized = true;
            }
        }
    }
    if (initialized) {
        SDL_DebugLogBackend("camera", camera_driver.name);
    } else {
        // specific drivers will set the error message if they fail, but otherwise we do it here.
        if (!tried_to_init) {
            if (driver_name) {
                SDL_SetError("Camera driver '%s' not available", driver_name);
            } else {
                SDL_SetError("No available camera driver");
            }
        }
        SDL_zero(camera_driver);
        SDL_DestroyRWLock(device_hash_lock);
        SDL_DestroyHashTable(device_hash);
        return false;  // No driver was available, so fail.
    }
    CompleteCameraEntryPoints();
    // Make sure we have a list of devices available at startup...
    camera_driver.impl.DetectDevices();
    return true;
}
References bootstrap, camera_driver, CompleteCameraEntryPoints(), DestroyCameraHashItem(), NULL, SDL_CreateHashTable(), SDL_CreateRWLock(), SDL_DebugLogBackend(), SDL_DestroyHashTable(), SDL_DestroyRWLock(), SDL_free(), SDL_GetCurrentCameraDriver(), SDL_GetHint(), SDL_HashID(), SDL_HINT_CAMERA_DRIVER, SDL_KeyMatchID(), SDL_QuitCamera(), SDL_SetError(), SDL_strcasecmp(), SDL_strchr(), SDL_strdup(), and SDL_zero.
Referenced by SDL_InitSubSystem().
SDL_QuitCamera()
void SDL_QuitCamera (void) extern
{
    if (!camera_driver.name) {  // not initialized?!
        return;
    }
    SDL_LockRWLockForWriting(camera_driver.device_hash_lock);
    SDL_SetAtomicInt(&camera_driver.shutting_down, 1);
    SDL_HashTable *device_hash = camera_driver.device_hash;
    camera_driver.device_hash = NULL;
    SDL_PendingCameraEvent *pending_events = camera_driver.pending_events.next;
    camera_driver.pending_events.next = NULL;
    SDL_SetAtomicInt(&camera_driver.device_count, 0);
    SDL_UnlockRWLock(camera_driver.device_hash_lock);
    SDL_PendingCameraEvent *pending_next = NULL;
    for (SDL_PendingCameraEvent *i = pending_events; i; i = pending_next) {
        pending_next = i->next;
        SDL_free(i);
    }
    SDL_DestroyHashTable(device_hash);
    // Free the driver data
    camera_driver.impl.Deinitialize();
    SDL_DestroyRWLock(camera_driver.device_hash_lock);
    SDL_zero(camera_driver);
}
References camera_driver, SDL_PendingCameraEvent::next, NULL, SDL_DestroyHashTable(), SDL_DestroyRWLock(), SDL_free(), SDL_LockRWLockForWriting(), SDL_SetAtomicInt(), SDL_UnlockRWLock(), and SDL_zero.
Referenced by SDL_CameraInit(), and SDL_QuitSubSystem().
SDL_UpdateCamera()
void SDL_UpdateCamera (void) extern
{
    SDL_LockRWLockForReading(camera_driver.device_hash_lock);
    SDL_PendingCameraEvent *pending_events = camera_driver.pending_events.next;
    SDL_UnlockRWLock(camera_driver.device_hash_lock);
    if (!pending_events) {
        return;  // nothing to do, check next time.
    }
    // okay, let's take this whole list of events so we can dump the lock, and new ones can queue up for a later update.
    SDL_LockRWLockForWriting(camera_driver.device_hash_lock);
    pending_events = camera_driver.pending_events.next;  // in case this changed...
    camera_driver.pending_events.next = NULL;
    camera_driver.pending_events_tail = &camera_driver.pending_events;
    SDL_UnlockRWLock(camera_driver.device_hash_lock);
    SDL_PendingCameraEvent *pending_next = NULL;
    for (SDL_PendingCameraEvent *i = pending_events; i; i = pending_next) {
        pending_next = i->next;
        if (SDL_EventEnabled(i->type)) {
            SDL_Event event;
            SDL_zero(event);
            event.type = i->type;
            event.cdevice.which = (Uint32) i->devid;
            SDL_PushEvent(&event);
        }
        SDL_free(i);
    }
}
References camera_driver, SDL_PendingCameraEvent::next, NULL, SDL_EventEnabled(), SDL_free(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_PushEvent(), SDL_UnlockRWLock(), and SDL_zero.
Referenced by SDL_PumpEventMaintenance().