SDL3: SDL-main/src/thread/generic/SDL_systls.c File Reference
SDL_systls.c File Reference
#include "SDL_internal.h"
#include "../SDL_thread_c.h"
Functions
SDL_TLSData * SDL_SYS_GetTLSData (void)
void SDL_SYS_InitTLSData (void)
void SDL_SYS_QuitTLSData (void)
bool SDL_SYS_SetTLSData (SDL_TLSData *data)
Function Documentation
SDL_SYS_GetTLSData()
SDL_TLSData * SDL_SYS_GetTLSData (void)
{
    return SDL_Generic_GetTLSData();
}
References SDL_Generic_GetTLSData().
Referenced by SDL_CleanupTLS(), SDL_GetTLS(), and SDL_SetTLS().
SDL_SYS_InitTLSData()
void SDL_SYS_InitTLSData (void)
{
    SDL_Generic_InitTLSData();
}
References SDL_Generic_InitTLSData().
Referenced by SDL_InitTLSData().
SDL_SYS_QuitTLSData()
void SDL_SYS_QuitTLSData (void)
{
    SDL_Generic_QuitTLSData();
}
References SDL_Generic_QuitTLSData().
Referenced by SDL_QuitTLSData().
SDL_SYS_SetTLSData()
bool SDL_SYS_SetTLSData (SDL_TLSData * data)
{
    return SDL_Generic_SetTLSData(data);
}
References SDL_Generic_SetTLSData().
Referenced by SDL_CleanupTLS(), and SDL_SetTLS().