SDL3: SDL-main/src/joystick/SDL_gamepad_c.h File Reference
SDL_gamepad_c.h File Reference
#include "SDL_internal.h"
Functions
void SDL_GamepadHandleDelayedGuideButton (SDL_Joystick *joystick)
void SDL_GamepadSensorWatcher (Uint64 timestamp, SDL_SensorID sensor, Uint64 sensor_timestamp, float *data, int num_values)
bool SDL_InitGamepadMappings (void)
bool SDL_InitGamepads (void)
bool SDL_IsGamepadNameAndGUID (const char *name, SDL_GUID guid)
void SDL_PrivateGamepadAdded (SDL_JoystickID instance_id)
void SDL_PrivateGamepadRemoved (SDL_JoystickID instance_id)
void SDL_QuitGamepadMappings (void)
void SDL_QuitGamepads (void)
bool SDL_ShouldIgnoreGamepad (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
Function Documentation
SDL_GamepadHandleDelayedGuideButton()
void SDL_GamepadHandleDelayedGuideButton (SDL_Joystick * joystick) extern
{
    SDL_Gamepad *gamepad;
    SDL_AssertJoysticksLocked();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        if (gamepad->joystick == joystick) {
            SDL_SendGamepadButton(0, gamepad, SDL_GAMEPAD_BUTTON_GUIDE, false);
            // Make sure we send an update complete event for this change
            if (!gamepad->joystick->update_complete) {
                gamepad->joystick->update_complete = SDL_GetTicksNS();
            }
            break;
        }
    }
}
References SDL_AssertJoysticksLocked(), SDL_GAMEPAD_BUTTON_GUIDE, SDL_GetTicksNS(), and SDL_SendGamepadButton().
Referenced by SDL_UpdateJoysticks().
SDL_GamepadSensorWatcher()
void SDL_GamepadSensorWatcher (Uint64 timestamp, SDL_SensorID sensor, Uint64 sensor_timestamp, float * data, int num_values) extern
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        if (gamepad->joystick->accel && gamepad->joystick->accel_sensor == sensor) {
            float gamepad_data[3];
            AdjustSensorOrientation(gamepad->joystick, data, gamepad_data);
            SDL_SendJoystickSensor(timestamp, gamepad->joystick, SDL_SENSOR_ACCEL, sensor_timestamp, gamepad_data, SDL_arraysize(gamepad_data));
        }
        if (gamepad->joystick->gyro && gamepad->joystick->gyro_sensor == sensor) {
            float gamepad_data[3];
            AdjustSensorOrientation(gamepad->joystick, data, gamepad_data);
            SDL_SendJoystickSensor(timestamp, gamepad->joystick, SDL_SENSOR_GYRO, sensor_timestamp, gamepad_data, SDL_arraysize(gamepad_data));
        }
    }
    SDL_UnlockJoysticks();
}
References AdjustSensorOrientation(), SDL_arraysize, SDL_LockJoysticks(), SDL_SendJoystickSensor(), SDL_SENSOR_ACCEL, SDL_SENSOR_GYRO, and SDL_UnlockJoysticks().
Referenced by SDL_SendSensorUpdate().
SDL_InitGamepadMappings()
bool SDL_InitGamepadMappings (void) extern
{
    char szGamepadMapPath[1024];
    int i = 0;
    const char *pMappingString = NULL;
    SDL_AssertJoysticksLocked();
    PushMappingChangeTracking();
    pMappingString = s_GamepadMappings[i];
    while (pMappingString) {
        SDL_PrivateAddGamepadMapping(pMappingString, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT);
        i++;
        pMappingString = s_GamepadMappings[i];
    }
    if (SDL_GetGamepadMappingFilePath(szGamepadMapPath, sizeof(szGamepadMapPath))) {
        SDL_AddGamepadMappingsFromFile(szGamepadMapPath);
    }
    // load in any user supplied config
    SDL_LoadGamepadHints();
    SDL_LoadVIDPIDList(&SDL_allowed_gamepads);
    SDL_LoadVIDPIDList(&SDL_ignored_gamepads);
    PopMappingChangeTracking();
    return true;
}
References NULL, PopMappingChangeTracking(), PushMappingChangeTracking(), s_GamepadMappings, SDL_AddGamepadMappingsFromFile(), SDL_allowed_gamepads, SDL_AssertJoysticksLocked(), SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT, SDL_GetGamepadMappingFilePath(), SDL_ignored_gamepads, SDL_LoadGamepadHints(), SDL_LoadVIDPIDList(), and SDL_PrivateAddGamepadMapping().
Referenced by SDL_InitJoysticks(), and SDL_ReloadGamepadMappings().
SDL_InitGamepads()
bool SDL_InitGamepads (void) extern
{
    int i;
    SDL_JoystickID *joysticks;
    SDL_gamepads_initialized = true;
    // Watch for joystick events and fire gamepad ones if needed
    SDL_AddEventWatch(SDL_GamepadEventWatcher, NULL);
    // Send added events for gamepads currently attached
    joysticks = SDL_GetJoysticks(NULL);
    if (joysticks) {
        for (i = 0; joysticks[i]; ++i) {
            if (SDL_IsGamepad(joysticks[i])) {
                SDL_PrivateGamepadAdded(joysticks[i]);
            }
        }
        SDL_free(joysticks);
    }
    return true;
}
References NULL, SDL_AddEventWatch(), SDL_free(), SDL_GamepadEventWatcher(), SDL_gamepads_initialized, SDL_GetJoysticks(), SDL_IsGamepad(), and SDL_PrivateGamepadAdded().
Referenced by SDL_InitSubSystem().
SDL_IsGamepadNameAndGUID()
bool SDL_IsGamepadNameAndGUID (const char * name, SDL_GUID guid) extern
{
    bool result;
    SDL_LockJoysticks();
    {
        if (s_pDefaultMapping || SDL_PrivateGetGamepadMappingForNameAndGUID(name, guid) != NULL) {
            result = true;
        } else {
            result = false;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_LockJoysticks(), SDL_PrivateGetGamepadMappingForNameAndGUID(), and SDL_UnlockJoysticks().
SDL_PrivateGamepadAdded()
void SDL_PrivateGamepadAdded (SDL_JoystickID instance_id) extern
{
    SDL_Event event;
    if (!SDL_gamepads_initialized || SDL_IsJoystickBeingAdded()) {
        return;
    }
    event.type = SDL_EVENT_GAMEPAD_ADDED;
    event.common.timestamp = 0;
    event.gdevice.which = instance_id;
    SDL_PushEvent(&event);
}
References SDL_EVENT_GAMEPAD_ADDED, SDL_gamepads_initialized, SDL_IsJoystickBeingAdded(), and SDL_PushEvent().
Referenced by PopMappingChangeTracking(), SDL_InitGamepads(), and SDL_PrivateJoystickAdded().
SDL_PrivateGamepadRemoved()
void SDL_PrivateGamepadRemoved (SDL_JoystickID instance_id) extern
{
    SDL_Event event;
    SDL_Gamepad *gamepad;
    SDL_AssertJoysticksLocked();
    if (!SDL_gamepads_initialized) {
        return;
    }
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        if (gamepad->joystick->instance_id == instance_id) {
            RecenterGamepad(gamepad);
            break;
        }
    }
    event.type = SDL_EVENT_GAMEPAD_REMOVED;
    event.common.timestamp = 0;
    event.gdevice.which = instance_id;
    SDL_PushEvent(&event);
}
References RecenterGamepad(), SDL_AssertJoysticksLocked(), SDL_EVENT_GAMEPAD_REMOVED, SDL_gamepads_initialized, and SDL_PushEvent().
Referenced by PopMappingChangeTracking(), SDL_PrivateJoystickRemoved(), and SDL_QuitGamepads().
SDL_QuitGamepadMappings()
void SDL_QuitGamepadMappings (void) extern
{
    GamepadMapping_t *pGamepadMap;
    SDL_AssertJoysticksLocked();
    while (s_pSupportedGamepads) {
        pGamepadMap = s_pSupportedGamepads;
        s_pSupportedGamepads = s_pSupportedGamepads->next;
        SDL_free(pGamepadMap->name);
        SDL_free(pGamepadMap->mapping);
        SDL_free(pGamepadMap);
    }
    SDL_FreeVIDPIDList(&SDL_allowed_gamepads);
    SDL_FreeVIDPIDList(&SDL_ignored_gamepads);
    if (s_gamepadInstanceIDs) {
        SDL_DestroyHashTable(s_gamepadInstanceIDs);
        s_gamepadInstanceIDs = NULL;
    }
}
References NULL, SDL_allowed_gamepads, SDL_AssertJoysticksLocked(), SDL_DestroyHashTable(), SDL_free(), SDL_FreeVIDPIDList(), and SDL_ignored_gamepads.
Referenced by SDL_QuitJoysticks(), and SDL_ReloadGamepadMappings().
SDL_QuitGamepads()
void SDL_QuitGamepads (void) extern
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        SDL_PrivateGamepadRemoved(gamepad->joystick->instance_id);
    }
    SDL_gamepads_initialized = false;
    SDL_RemoveEventWatch(SDL_GamepadEventWatcher, NULL);
    while (SDL_gamepads) {
        SDL_gamepads->ref_count = 1;
        SDL_CloseGamepad(SDL_gamepads);
    }
    SDL_UnlockJoysticks();
}
References NULL, SDL_CloseGamepad(), SDL_GamepadEventWatcher(), SDL_gamepads_initialized, SDL_LockJoysticks(), SDL_PrivateGamepadRemoved(), SDL_RemoveEventWatch(), and SDL_UnlockJoysticks().
Referenced by SDL_QuitSubSystem().
SDL_ShouldIgnoreGamepad()
bool SDL_ShouldIgnoreGamepad (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char * name) extern
{
#ifdef SDL_PLATFORM_LINUX
    if (SDL_endswith(name, " Motion Sensors")) {
        // Don't treat the PS3 and PS4 motion controls as a separate gamepad
        return true;
    }
    if (SDL_strncmp(name, "Nintendo ", 9) == 0 && SDL_strstr(name, " IMU") != NULL) {
        // Don't treat the Nintendo IMU as a separate gamepad
        return true;
    }
    if (SDL_endswith(name, " Accelerometer") ||
        SDL_endswith(name, " IR") ||
        SDL_endswith(name, " Motion Plus") ||
        SDL_endswith(name, " Nunchuk")) {
        // Don't treat the Wii extension controls as a separate gamepad
        return true;
    }
#endif
    if (name && SDL_strcmp(name, "uinput-fpc") == 0) {
        // The Google Pixel fingerprint sensor reports itself as a joystick
        return true;
    }
#ifdef SDL_PLATFORM_WIN32
    if (SDL_GetHintBoolean("SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD", false) &&
        SDL_GetHintBoolean("STEAM_COMPAT_PROTON", false)) {
        // We are launched by Steam and running under Proton
        // We can't tell whether this controller is a Steam Virtual Gamepad,
        // so assume that Proton is doing the appropriate filtering of controllers
        // and anything we see here is fine to use.
        return false;
    }
#endif // SDL_PLATFORM_WIN32
    if (SDL_IsJoystickSteamVirtualGamepad(vendor_id, product_id, version)) {
        return !SDL_GetHintBoolean("SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD", false);
    }
    if (SDL_allowed_gamepads.num_included_entries > 0) {
        if (SDL_VIDPIDInList(vendor_id, product_id, &SDL_allowed_gamepads)) {
            return false;
        }
        return true;
    } else {
        if (SDL_VIDPIDInList(vendor_id, product_id, &SDL_ignored_gamepads)) {
            return true;
        }
        return false;
    }
}
References NULL, SDL_allowed_gamepads, SDL_endswith(), SDL_GetHintBoolean(), SDL_ignored_gamepads, SDL_IsJoystickSteamVirtualGamepad(), SDL_strcmp(), SDL_strncmp(), SDL_strstr(), and SDL_VIDPIDInList().
Referenced by SDL_ShouldIgnoreJoystick().