SDL3: SDL-main/src/SDL_list.h File Reference
SDL_list.h File Reference
Data Structures
struct SDL_ListNode
Typedefs
typedef struct SDL_ListNode SDL_ListNode
Functions
bool SDL_ListAdd (SDL_ListNode **head, void *ent)
void SDL_ListClear (SDL_ListNode **head)
void SDL_ListPop (SDL_ListNode **head, void **ent)
void SDL_ListRemove (SDL_ListNode **head, void *ent)
Typedef Documentation
SDL_ListNode
typedef struct SDL_ListNode SDL_ListNode
Function Documentation
SDL_ListAdd()
bool SDL_ListAdd (SDL_ListNode ** head, void * ent)
{
    SDL_ListNode *node = (SDL_ListNode *)SDL_malloc(sizeof(*node));
    if (!node) {
        return false;
    }
    node->entry = ent;
    node->next = *head;
    *head = node;
    return true;
}
References SDL_ListNode::entry, head, SDL_ListNode::next, and SDL_malloc().
SDL_ListClear()
void SDL_ListClear (SDL_ListNode ** head)
{
    SDL_ListNode *l = *head;
    *head = NULL;
    while (l) {
        SDL_ListNode *tmp = l;
        l = l->next;
        SDL_free(tmp);
    }
}
References head, SDL_ListNode::next, NULL, and SDL_free().
SDL_ListPop()
void SDL_ListPop (SDL_ListNode ** head, void ** ent)
{
    SDL_ListNode **ptr = head;
    // Invalid or empty
    if (!head || !*head) {
        return;
    }
    while ((*ptr)->next) {
        ptr = &(*ptr)->next;
    }
    if (ent) {
        *ent = (*ptr)->entry;
    }
    SDL_free(*ptr);
    *ptr = NULL;
}
References head, SDL_ListNode::next, NULL, and SDL_free().
SDL_ListRemove()
void SDL_ListRemove (SDL_ListNode ** head, void * ent)
{
    SDL_ListNode **ptr = head;
    while (*ptr) {
        if ((*ptr)->entry == ent) {
            SDL_ListNode *tmp = *ptr;
            *ptr = (*ptr)->next;
            SDL_free(tmp);
            return;
        }
        ptr = &(*ptr)->next;
    }
}
References head, SDL_ListNode::next, and SDL_free().