SDL3: SDL-main/src/video/SDL_pixels_c.h File Reference
SDL_pixels_c.h File Reference
#include "SDL_internal.h"
#include "SDL_blit.h"
Functions
void SDL_ConvertColorPrimaries (float *fR, float *fG, float *fB, const float *matrix)
void SDL_DetectPalette (const SDL_Palette *pal, bool *is_opaque, bool *has_alpha_channel)
void SDL_DitherPalette (SDL_Palette *palette)
SDL_Surface * SDL_DuplicatePixels (int width, int height, SDL_PixelFormat format, SDL_Colorspace colorspace, void *pixels, int pitch)
Uint8 SDL_FindColor (const SDL_Palette *pal, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
void SDL_Get8888AlphaMaskAndShift (const SDL_PixelFormatDetails *fmt, Uint32 *mask, Uint32 *shift)
const float * SDL_GetColorPrimariesConversionMatrix (SDL_ColorPrimaries src, SDL_ColorPrimaries dst)
SDL_Colorspace SDL_GetDefaultColorspaceForFormat (SDL_PixelFormat pixel_format)
const float * SDL_GetYCbCRtoRGBConversionMatrix (SDL_Colorspace colorspace, int w, int h, int bits_per_pixel)
void SDL_InvalidateMap (SDL_BlitMap *map)
Uint8 SDL_LookupRGBAColor (SDL_HashTable *palette_map, Uint32 pixelvalue, const SDL_Palette *pal)
bool SDL_MapSurface (SDL_Surface *src, SDL_Surface *dst)
float SDL_PQfromNits (float v)
float SDL_PQtoNits (float v)
void SDL_QuitPixelFormatDetails (void)
float SDL_sRGBfromLinear (float v)
float SDL_sRGBtoLinear (float v)
bool SDL_ValidateMap (SDL_Surface *src, SDL_Surface *dst)
Function Documentation
SDL_ConvertColorPrimaries()
void SDL_ConvertColorPrimaries (float * fR, float * fG, float * fB, const float * matrix) extern
{
    float v[3];
    v[0] = *fR;
    v[1] = *fG;
    v[2] = *fB;
    *fR = matrix[0 * 3 + 0] * v[0] + matrix[0 * 3 + 1] * v[1] + matrix[0 * 3 + 2] * v[2];
    *fG = matrix[1 * 3 + 0] * v[0] + matrix[1 * 3 + 1] * v[1] + matrix[1 * 3 + 2] * v[2];
    *fB = matrix[2 * 3 + 0] * v[0] + matrix[2 * 3 + 1] * v[1] + matrix[2 * 3 + 2] * v[2];
}
Referenced by ApplyTonemap(), and SDL_Blit_Slow_Float().
SDL_DetectPalette()
void SDL_DetectPalette (const SDL_Palette * pal, bool * is_opaque, bool * has_alpha_channel) extern
{
    int i;
    {
        bool all_opaque = true;
        for (i = 0; i < pal->ncolors; i++) {
            Uint8 alpha_value = pal->colors[i].a;
            if (alpha_value != SDL_ALPHA_OPAQUE) {
                all_opaque = false;
                break;
            }
        }
        if (all_opaque) {
            // Palette is opaque, with an alpha channel
            *is_opaque = true;
            *has_alpha_channel = true;
            return;
        }
    }
    {
        bool all_transparent = true;
        for (i = 0; i < pal->ncolors; i++) {
            Uint8 alpha_value = pal->colors[i].a;
            if (alpha_value != SDL_ALPHA_TRANSPARENT) {
                all_transparent = false;
                break;
            }
        }
        if (all_transparent) {
            // Palette is opaque, without an alpha channel
            *is_opaque = true;
            *has_alpha_channel = false;
            return;
        }
    }
    // Palette has alpha values
    *is_opaque = false;
    *has_alpha_channel = true;
}
References SDL_Color::a, SDL_Palette::colors, SDL_Palette::ncolors, SDL_ALPHA_OPAQUE, and SDL_ALPHA_TRANSPARENT.
Referenced by SDL_ConvertSurfaceAndColorspace(), and SDL_CreateTextureFromSurface().
SDL_DitherPalette()
void SDL_DitherPalette (SDL_Palette * palette) extern
{
    int i;
    if (palette->ncolors != 256) {
        return; // only 8bpp supported right now
    }
    for (i = 0; i < palette->ncolors; i++) {
        int r, g, b;
        /* map each bit field to the full [0, 255] interval,
           so 0 is mapped to (0, 0, 0) and 255 to (255, 255, 255) */
        r = i & 0xe0;
        r |= r >> 3 | r >> 6;
        palette->colors[i].r = (Uint8)r;
        g = (i << 3) & 0xe0;
        g |= g >> 3 | g >> 6;
        palette->colors[i].g = (Uint8)g;
        b = i & 0x3;
        b |= b << 2;
        b |= b << 4;
        palette->colors[i].b = (Uint8)b;
        palette->colors[i].a = SDL_ALPHA_OPAQUE;
    }
}
References SDL_Color::a, SDL_Color::b, SDL_Palette::colors, SDL_Color::g, SDL_Palette::ncolors, SDL_Color::r, and SDL_ALPHA_OPAQUE.
Referenced by SDL_ConvertSurfaceAndColorspace().
SDL_DuplicatePixels()
SDL_Surface * SDL_DuplicatePixels (int width, int height, SDL_PixelFormat format, SDL_Colorspace colorspace, void * pixels, int pitch) extern
{
    SDL_Surface *surface = SDL_CreateSurface(width, height, format);
    if (surface) {
        int length = width * SDL_BYTESPERPIXEL(format);
        Uint8 *src = (Uint8 *)pixels;
        Uint8 *dst = (Uint8 *)surface->pixels;
        int rows = height;
        while (rows--) {
            SDL_memcpy(dst, src, length);
            dst += surface->pitch;
            src += pitch;
        }
        SDL_SetSurfaceColorspace(surface, colorspace);
    }
    return surface;
}
References SDL_BYTESPERPIXEL, SDL_CreateSurface(), SDL_memcpy, and SDL_SetSurfaceColorspace().
SDL_FindColor()
Uint8 SDL_FindColor (const SDL_Palette * pal, Uint8 r, Uint8 g, Uint8 b, Uint8 a) extern
{
    // Do colorspace distance matching
    unsigned int smallest;
    unsigned int distance;
    int rd, gd, bd, ad;
    int i;
    Uint8 pixelvalue = 0;
    smallest = ~0U;
    for (i = 0; i < pal->ncolors; ++i) {
        rd = pal->colors[i].r - r;
        gd = pal->colors[i].g - g;
        bd = pal->colors[i].b - b;
        ad = pal->colors[i].a - a;
        distance = (rd * rd) + (gd * gd) + (bd * bd) + (ad * ad);
        if (distance < smallest) {
            pixelvalue = (Uint8)i;
            if (distance == 0) { // Perfect match!
                break;
            }
            smallest = distance;
        }
    }
    return pixelvalue;
}
References SDL_Color::a, SDL_Color::b, SDL_Palette::colors, SDL_Color::g, SDL_Palette::ncolors, SDL_Color::r, and U.
Referenced by Map1to1(), SDL_LookupRGBAColor(), SDL_MapRGB(), and SDL_MapRGBA().
SDL_Get8888AlphaMaskAndShift()
void SDL_Get8888AlphaMaskAndShift (const SDL_PixelFormatDetails * fmt, Uint32 * mask, Uint32 * shift) extern
{
    if (fmt->Amask) {
        *mask = fmt->Amask;
        *shift = fmt->Ashift;
    } else {
        *mask = ~(fmt->Rmask | fmt->Gmask | fmt->Bmask);
        switch (*mask) {
        case 0x000000FF:
            *shift = 0;
            break;
        case 0x0000FF00:
            *shift = 8;
            break;
        case 0x00FF0000:
            *shift = 16;
            break;
        case 0xFF000000:
            *shift = 24;
            break;
        default:
            // Should never happen
            *shift = 0;
            break;
        }
    }
}
References SDL_PixelFormatDetails::Amask, SDL_PixelFormatDetails::Ashift, SDL_PixelFormatDetails::Bmask, SDL_PixelFormatDetails::Gmask, and SDL_PixelFormatDetails::Rmask.
SDL_GetColorPrimariesConversionMatrix()
const float * SDL_GetColorPrimariesConversionMatrix (SDL_ColorPrimaries src, SDL_ColorPrimaries dst) extern
{
    /* Conversion matrices generated using gamescope color helpers and the primaries definitions at:
     * https://www.itu.int/rec/T-REC-H.273-201612-S/en
     *
     * You can also generate these online using the RGB-XYZ matrix calculator, and then multiplying
     * XYZ_to_dst * src_to_XYZ to get the combined conversion matrix:
     * https://www.russellcottrell.com/photo/matrixCalculator.htm
     */
    static const float mat601to709[] = {
        0.939542f, 0.050181f, 0.010277f,
        0.017772f, 0.965793f, 0.016435f,
        -0.001622f, -0.004370f, 1.005991f,
    };
    static const float mat601to2020[] = {
        0.595254f, 0.349314f, 0.055432f,
        0.081244f, 0.891503f, 0.027253f,
        0.015512f, 0.081912f, 0.902576f,
    };
    static const float mat709to601[] = {
        1.065379f, -0.055401f, -0.009978f,
        -0.019633f, 1.036363f, -0.016731f,
        0.001632f, 0.004412f, 0.993956f,
    };
    static const float mat709to2020[] = {
        0.627404f, 0.329283f, 0.043313f,
        0.069097f, 0.919541f, 0.011362f,
        0.016391f, 0.088013f, 0.895595f,
    };
    static const float mat2020to601[] = {
        1.776133f, -0.687820f, -0.088313f,
        -0.161376f, 1.187315f, -0.025940f,
        -0.015881f, -0.095931f, 1.111812f,
    };
    static const float mat2020to709[] = {
        1.660496f, -0.587656f, -0.072840f,
        -0.124547f, 1.132895f, -0.008348f,
        -0.018154f, -0.100597f, 1.118751f
    };
    static const float matSMPTE431to709[] = {
        1.120713f, -0.234649f, 0.000000f,
        -0.038478f, 1.087034f, 0.000000f,
        -0.017967f, -0.082030f, 0.954576f,
    };
    static const float matSMPTE431to2020[] = {
        0.689691f, 0.207169f, 0.041346f,
        0.041852f, 0.982426f, 0.010846f,
        -0.001107f, 0.018362f, 0.854914f,
    };
    static const float matSMPTE432to709[] = {
        1.224940f, -0.224940f, -0.000000f,
        -0.042057f, 1.042057f, 0.000000f,
        -0.019638f, -0.078636f, 1.098273f,
    };
    static const float matSMPTE432to2020[] = {
        0.753833f, 0.198597f, 0.047570f,
        0.045744f, 0.941777f, 0.012479f,
        -0.001210f, 0.017602f, 0.983609f,
    };
    switch (dst) {
    case SDL_COLOR_PRIMARIES_BT601:
    case SDL_COLOR_PRIMARIES_SMPTE240:
        switch (src) {
        case SDL_COLOR_PRIMARIES_BT709:
            return mat709to601;
        case SDL_COLOR_PRIMARIES_BT2020:
            return mat2020to601;
        default:
            break;
        }
        break;
    case SDL_COLOR_PRIMARIES_BT709:
        switch (src) {
        case SDL_COLOR_PRIMARIES_BT601:
        case SDL_COLOR_PRIMARIES_SMPTE240:
            return mat601to709;
        case SDL_COLOR_PRIMARIES_BT2020:
            return mat2020to709;
        case SDL_COLOR_PRIMARIES_SMPTE431:
            return matSMPTE431to709;
        case SDL_COLOR_PRIMARIES_SMPTE432:
            return matSMPTE432to709;
        default:
            break;
        }
        break;
    case SDL_COLOR_PRIMARIES_BT2020:
        switch (src) {
        case SDL_COLOR_PRIMARIES_BT601:
        case SDL_COLOR_PRIMARIES_SMPTE240:
            return mat601to2020;
        case SDL_COLOR_PRIMARIES_BT709:
            return mat709to2020;
        case SDL_COLOR_PRIMARIES_SMPTE431:
            return matSMPTE431to2020;
        case SDL_COLOR_PRIMARIES_SMPTE432:
            return matSMPTE432to2020;
        default:
            break;
        }
        break;
    default:
        break;
    }
    return NULL;
}
References NULL, SDL_COLOR_PRIMARIES_BT2020, SDL_COLOR_PRIMARIES_BT601, SDL_COLOR_PRIMARIES_BT709, SDL_COLOR_PRIMARIES_SMPTE240, SDL_COLOR_PRIMARIES_SMPTE431, and SDL_COLOR_PRIMARIES_SMPTE432.
Referenced by SDL_Blit_Slow_Float().
SDL_GetDefaultColorspaceForFormat()
SDL_Colorspace SDL_GetDefaultColorspaceForFormat (SDL_PixelFormat pixel_format) extern
{
    if (SDL_ISPIXELFORMAT_FOURCC(format)) {
        if (format == SDL_PIXELFORMAT_MJPG) {
            return SDL_COLORSPACE_SRGB;
        } else if (format == SDL_PIXELFORMAT_P010) {
            return SDL_COLORSPACE_HDR10;
        } else {
            return SDL_COLORSPACE_YUV_DEFAULT;
        }
    } else if (SDL_ISPIXELFORMAT_FLOAT(format)) {
        return SDL_COLORSPACE_SRGB_LINEAR;
    } else if (SDL_ISPIXELFORMAT_10BIT(format)) {
        return SDL_COLORSPACE_HDR10;
    } else {
        return SDL_COLORSPACE_RGB_DEFAULT;
    }
}
References SDL_COLORSPACE_HDR10, SDL_COLORSPACE_RGB_DEFAULT, SDL_COLORSPACE_SRGB, SDL_COLORSPACE_SRGB_LINEAR, SDL_COLORSPACE_YUV_DEFAULT, SDL_ISPIXELFORMAT_10BIT, SDL_ISPIXELFORMAT_FLOAT, SDL_ISPIXELFORMAT_FOURCC, SDL_PIXELFORMAT_MJPG, and SDL_PIXELFORMAT_P010.
Referenced by SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurface(), SDL_CreateTextureWithProperties(), SDL_InitializeSurface(), and SDL_PremultiplyAlpha().
SDL_GetYCbCRtoRGBConversionMatrix()
const float * SDL_GetYCbCRtoRGBConversionMatrix (SDL_Colorspace colorspace, int w, int h, int bits_per_pixel) extern
{
    const int YUV_SD_THRESHOLD = 576;
    switch (SDL_COLORSPACEMATRIX(colorspace)) {
    case SDL_MATRIX_COEFFICIENTS_BT601:
    case SDL_MATRIX_COEFFICIENTS_BT470BG:
        return SDL_GetBT601ConversionMatrix(colorspace);
    case SDL_MATRIX_COEFFICIENTS_BT709:
        return SDL_GetBT709ConversionMatrix(colorspace);
    case SDL_MATRIX_COEFFICIENTS_BT2020_NCL:
        return SDL_GetBT2020ConversionMatrix(colorspace);
    case SDL_MATRIX_COEFFICIENTS_UNSPECIFIED:
        switch (bits_per_pixel) {
        case 8:
            if (h <= YUV_SD_THRESHOLD) {
                return SDL_GetBT601ConversionMatrix(colorspace);
            } else {
                return SDL_GetBT709ConversionMatrix(colorspace);
            }
        case 10:
        case 16:
            return SDL_GetBT2020ConversionMatrix(colorspace);
        default:
            break;
        }
        break;
    default:
        break;
    }
    return NULL;
}
References NULL, SDL_COLORSPACEMATRIX, SDL_GetBT2020ConversionMatrix(), SDL_GetBT601ConversionMatrix(), SDL_GetBT709ConversionMatrix(), SDL_MATRIX_COEFFICIENTS_BT2020_NCL, SDL_MATRIX_COEFFICIENTS_BT470BG, SDL_MATRIX_COEFFICIENTS_BT601, SDL_MATRIX_COEFFICIENTS_BT709, and SDL_MATRIX_COEFFICIENTS_UNSPECIFIED.
SDL_InvalidateMap()
void SDL_InvalidateMap (SDL_BlitMap * map) extern
{
    map->info.dst_fmt = NULL;
    map->info.dst_pal = NULL;
    map->src_palette_version = 0;
    map->dst_palette_version = 0;
    if (map->info.table) {
        SDL_free(map->info.table);
        map->info.table = NULL;
    }
    if (map->info.palette_map) {
        SDL_DestroyHashTable(map->info.palette_map);
        map->info.palette_map = NULL;
    }
}
References SDL_BlitInfo::dst_fmt, SDL_BlitInfo::dst_pal, SDL_BlitMap::dst_palette_version, SDL_BlitMap::info, NULL, SDL_BlitInfo::palette_map, SDL_DestroyHashTable(), SDL_free(), SDL_BlitMap::src_palette_version, and SDL_BlitInfo::table.
Referenced by SDL_BlitSurface(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_BlitSurfaceUncheckedScaled(), SDL_CalculateBlit(), SDL_ConvertSurfaceAndColorspace(), SDL_DestroySurface(), SDL_MapSurface(), SDL_ScaleSurface(), SDL_SetSurfaceAlphaMod(), SDL_SetSurfaceBlendMode(), SDL_SetSurfaceColorKey(), SDL_SetSurfaceColorMod(), SDL_SetSurfacePalette(), and SDL_SetSurfaceRLE().
SDL_LookupRGBAColor()
Uint8 SDL_LookupRGBAColor (SDL_HashTable * palette_map, Uint32 pixelvalue, const SDL_Palette * pal) extern
{
    Uint8 color_index = 0;
    const void *value;
    if (SDL_FindInHashTable(palette_map, (const void *)(uintptr_t)pixelvalue, &value)) {
        color_index = (Uint8)(uintptr_t)value;
    } else {
        Uint8 r = (Uint8)((pixelvalue >> 24) & 0xFF);
        Uint8 g = (Uint8)((pixelvalue >> 16) & 0xFF);
        Uint8 b = (Uint8)((pixelvalue >>  8) & 0xFF);
        Uint8 a = (Uint8)((pixelvalue >>  0) & 0xFF);
        color_index = SDL_FindColor(pal, r, g, b, a);
        SDL_InsertIntoHashTable(palette_map, (const void *)(uintptr_t)pixelvalue, (const void *)(uintptr_t)color_index, true);
    }
    return color_index;
}
References SDL_FindColor(), SDL_FindInHashTable(), and SDL_InsertIntoHashTable().
Referenced by SDL_Blit_Slow(), and SDL_Blit_Slow_Float().
SDL_MapSurface()
bool SDL_MapSurface (SDL_Surface * src, SDL_Surface * dst) extern
{
    const SDL_PixelFormatDetails *srcfmt;
    const SDL_Palette *srcpal;
    const SDL_PixelFormatDetails *dstfmt;
    const SDL_Palette *dstpal;
    SDL_BlitMap *map;
    // Clear out any previous mapping
    map = &src->map;
#ifdef SDL_HAVE_RLE
    if (src->internal_flags & SDL_INTERNAL_SURFACE_RLEACCEL) {
        SDL_UnRLESurface(src, true);
    }
#endif
    SDL_InvalidateMap(map);
    // Figure out what kind of mapping we're doing
    map->identity = 0;
    srcfmt = src->fmt;
    srcpal = src->palette;
    dstfmt = dst->fmt;
    dstpal = dst->palette;
    if (SDL_ISPIXELFORMAT_INDEXED(srcfmt->format)) {
        if (SDL_ISPIXELFORMAT_INDEXED(dstfmt->format)) {
            // Palette --> Palette
            if (srcpal && dstpal) {
                map->info.table = Map1to1(srcpal, dstpal, &map->identity);
            } else {
                map->identity = 1;
            }
            if (!map->identity) {
                if (!map->info.table) {
                    return false;
                }
            }
            if (srcfmt->bits_per_pixel != dstfmt->bits_per_pixel) {
                map->identity = 0;
            }
        } else {
            // Palette --> BitField
            map->info.table =
                Map1toN(srcpal, src->map.info.r, src->map.info.g,
                        src->map.info.b, src->map.info.a, dstfmt);
            if (!map->info.table) {
                return false;
            }
        }
    } else {
        if (SDL_ISPIXELFORMAT_INDEXED(dstfmt->format)) {
            // BitField --> Palette
            map->info.palette_map = SDL_CreateHashTable(0, false, SDL_HashID, SDL_KeyMatchID, NULL, NULL);
        } else {
            // BitField --> BitField
            if (srcfmt == dstfmt) {
                map->identity = 1;
            }
        }
    }
    if (dstpal) {
        map->dst_palette_version = dstpal->version;
    } else {
        map->dst_palette_version = 0;
    }
    if (srcpal) {
        map->src_palette_version = srcpal->version;
    } else {
        map->src_palette_version = 0;
    }
    // Choose your blitters wisely
    return SDL_CalculateBlit(src, dst);
}
References SDL_BlitInfo::a, SDL_BlitInfo::b, SDL_PixelFormatDetails::bits_per_pixel, SDL_BlitMap::dst_palette_version, SDL_Surface::fmt, SDL_PixelFormatDetails::format, SDL_BlitInfo::g, SDL_BlitMap::identity, SDL_BlitMap::info, SDL_Surface::internal_flags, SDL_Surface::map, Map1to1(), Map1toN(), NULL, SDL_Surface::palette, SDL_BlitInfo::palette_map, SDL_BlitInfo::r, SDL_CalculateBlit(), SDL_CreateHashTable(), SDL_HashID(), SDL_INTERNAL_SURFACE_RLEACCEL, SDL_InvalidateMap(), SDL_ISPIXELFORMAT_INDEXED, SDL_KeyMatchID(), SDL_UnRLESurface(), SDL_BlitMap::src_palette_version, SDL_BlitInfo::table, and SDL_Palette::version.
Referenced by SDL_ValidateMap().
SDL_PQfromNits()
float SDL_PQfromNits (float v) extern
{
    const float c1 = 0.8359375f;
    const float c2 = 18.8515625f;
    const float c3 = 18.6875f;
    const float m1 = 0.1593017578125f;
    const float m2 = 78.84375f;
    float y = SDL_clamp(v / 10000.0f, 0.0f, 1.0f);
    float num = c1 + c2 * SDL_powf(y, m1);
    float den = 1.0f + c3 * SDL_powf(y, m1);
    return SDL_powf(num / den, m2);
}
References SDL_clamp, and SDL_powf().
Referenced by WriteFloatPixel().
SDL_PQtoNits()
float SDL_PQtoNits (float v) extern
{
    const float c1 = 0.8359375f;
    const float c2 = 18.8515625f;
    const float c3 = 18.6875f;
    const float oo_m1 = 1.0f / 0.1593017578125f;
    const float oo_m2 = 1.0f / 78.84375f;
    float num = SDL_max(SDL_powf(v, oo_m2) - c1, 0.0f);
    float den = c2 - c3 * SDL_powf(v, oo_m2);
    return 10000.0f * SDL_powf(num / den, oo_m1);
}
References SDL_max, and SDL_powf().
Referenced by ReadFloatPixel().
SDL_QuitPixelFormatDetails()
void SDL_QuitPixelFormatDetails (void) extern
{
    if (SDL_ShouldQuit(&SDL_format_details_init)) {
        SDL_DestroyHashTable(SDL_format_details);
        SDL_format_details = NULL;
        SDL_SetInitialized(&SDL_format_details_init, false);
    }
}
References NULL, SDL_DestroyHashTable(), SDL_format_details, SDL_format_details_init, SDL_SetInitialized(), and SDL_ShouldQuit().
Referenced by SDL_Quit().
SDL_sRGBfromLinear()
float SDL_sRGBfromLinear (float v) extern
{
    if (v <= 0.0031308f) {
        v = (v * 12.92f);
    } else {
        v = (SDL_powf(v, 1.0f / 2.4f) * 1.055f - 0.055f);
    }
    return v;
}
References SDL_powf().
Referenced by SDL_Blit_Slow_Float(), SDL_ConvertFromLinear(), and WriteFloatPixel().
SDL_sRGBtoLinear()
float SDL_sRGBtoLinear (float v) extern
{
    if (v <= 0.04045f) {
        v = (v / 12.92f);
    } else {
        v = SDL_powf((v + 0.055f) / 1.055f, 2.4f);
    }
    return v;
}
References SDL_powf().
Referenced by ReadFloatPixel(), and SDL_ConvertToLinear().
SDL_ValidateMap()
bool SDL_ValidateMap (SDL_Surface * src, SDL_Surface * dst) extern
{
    SDL_BlitMap *map = &src->map;
    if (map->info.dst_fmt != dst->fmt ||
        map->info.dst_pal != dst->palette ||
        (dst->palette &&
         map->dst_palette_version != dst->palette->version) ||
        (src->palette &&
         map->src_palette_version != src->palette->version)) {
        if (!SDL_MapSurface(src, dst)) {
            return false;
        }
        // just here for debugging
        // printf
        // ("src = 0x%08X src->flags = %08X map->info.flags = %08x\ndst = 0x%08X dst->flags = %08X dst->map.info.flags = %08X\nmap->blit = 0x%08x\n",
        // src, dst->flags, map->info.flags, dst, dst->flags,
        // dst->map.info.flags, map->blit);
    } else {
        map->info.dst_surface = dst;
    }
    return true;
}
References SDL_BlitInfo::dst_fmt, SDL_BlitInfo::dst_pal, SDL_BlitMap::dst_palette_version, SDL_BlitInfo::dst_surface, SDL_Surface::fmt, SDL_BlitMap::info, SDL_Surface::map, SDL_Surface::palette, SDL_MapSurface(), SDL_BlitMap::src_palette_version, and SDL_Palette::version.
Referenced by SDL_BlitSurfaceUnchecked().