SDL3: SDL-main/include/SDL3/SDL_messagebox.h File Reference
SDL_messagebox.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_MessageBoxButtonData
struct SDL_MessageBoxColor
struct SDL_MessageBoxColorScheme
struct SDL_MessageBoxData
Macros
#define SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT 0x00000002u
#define SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT 0x00000001u
#define SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT 0x00000080u
#define SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT 0x00000100u
#define SDL_MESSAGEBOX_ERROR 0x00000010u
#define SDL_MESSAGEBOX_INFORMATION 0x00000040u
#define SDL_MESSAGEBOX_WARNING 0x00000020u
Typedefs
typedef struct SDL_MessageBoxButtonData SDL_MessageBoxButtonData
typedef Uint32 SDL_MessageBoxButtonFlags
typedef struct SDL_MessageBoxColor SDL_MessageBoxColor
typedef struct SDL_MessageBoxColorScheme SDL_MessageBoxColorScheme
typedef enum SDL_MessageBoxColorType SDL_MessageBoxColorType
typedef struct SDL_MessageBoxData SDL_MessageBoxData
typedef Uint32 SDL_MessageBoxFlags
Enumerations
enum SDL_MessageBoxColorType {
SDL_MESSAGEBOX_COLOR_BACKGROUND , SDL_MESSAGEBOX_COLOR_TEXT , SDL_MESSAGEBOX_COLOR_BUTTON_BORDER , SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND ,
SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED , SDL_MESSAGEBOX_COLOR_COUNT
}
Functions
SDL_DECLSPEC bool SDLCALL SDL_ShowMessageBox (const SDL_MessageBoxData *messageboxdata, int *buttonid)
SDL_DECLSPEC bool SDLCALL SDL_ShowSimpleMessageBox (SDL_MessageBoxFlags flags, const char *title, const char *message, SDL_Window *window)
Macro Definition Documentation
SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT
#define SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT 0x00000002u
Marks the default button when escape is hit
Referenced by SDL_PromptAssertion(), and SDL_ShowSimpleMessageBox().
SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT
#define SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT 0x00000001u
Marks the default button when return is hit
Referenced by SDL_PromptAssertion(), and SDL_ShowSimpleMessageBox().
SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT
#define SDL_MESSAGEBOX_BUTTONS_LEFT_TO_RIGHT 0x00000080u
buttons placed left to right
SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT
#define SDL_MESSAGEBOX_BUTTONS_RIGHT_TO_LEFT 0x00000100u
buttons placed right to left
SDL_MESSAGEBOX_ERROR
#define SDL_MESSAGEBOX_ERROR 0x00000010u
error dialog
Referenced by OutOfMemory(), and SDL_RunApp().
SDL_MESSAGEBOX_INFORMATION
#define SDL_MESSAGEBOX_INFORMATION 0x00000040u
informational dialog
SDL_MESSAGEBOX_WARNING
#define SDL_MESSAGEBOX_WARNING 0x00000020u
warning dialog
Referenced by SDL_PromptAssertion().
Typedef Documentation
SDL_MessageBoxButtonData
typedef struct SDL_MessageBoxButtonData SDL_MessageBoxButtonData
Individual button data.
Since
This struct is available since SDL 3.2.0.
SDL_MessageBoxButtonFlags
typedef Uint32 SDL_MessageBoxButtonFlags
SDL_MessageBoxButtonData flags.
Since
This datatype is available since SDL 3.2.0.
SDL_MessageBoxColor
typedef struct SDL_MessageBoxColor SDL_MessageBoxColor
RGB value used in a message box color scheme
Since
This struct is available since SDL 3.2.0.
SDL_MessageBoxColorScheme
typedef struct SDL_MessageBoxColorScheme SDL_MessageBoxColorScheme
A set of colors to use for message box dialogs
Since
This struct is available since SDL 3.2.0.
SDL_MessageBoxColorType
typedef enum SDL_MessageBoxColorType SDL_MessageBoxColorType
An enumeration of indices inside the colors array of SDL_MessageBoxColorScheme.
SDL_MessageBoxData
typedef struct SDL_MessageBoxData SDL_MessageBoxData
MessageBox structure containing title, text, window, etc.
Since
This struct is available since SDL 3.2.0.
SDL_MessageBoxFlags
typedef Uint32 SDL_MessageBoxFlags
CategoryMessagebox
SDL offers a simple message box API, which is useful for simple alerts, such as informing the user when something fatal happens at startup without the need to build a UI for it (or informing the user before your UI is ready).
These message boxes are native system dialogs where possible.
There is both a customizable function (SDL_ShowMessageBox()) that offers lots of options for what to display and reports on what choice the user made, and also a much-simplified version (SDL_ShowSimpleMessageBox()), merely takes a text message and title, and waits until the user presses a single "OK" UI button. Often, this is all that is necessary. Message box flags.
If supported will display warning icon, etc.
Since
This datatype is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_MessageBoxColorType
enum SDL_MessageBoxColorType
An enumeration of indices inside the colors array of SDL_MessageBoxColorScheme.
Enumerator
SDL_MESSAGEBOX_COLOR_BACKGROUND
SDL_MESSAGEBOX_COLOR_TEXT
SDL_MESSAGEBOX_COLOR_BUTTON_BORDER
SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND
SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED
SDL_MESSAGEBOX_COLOR_COUNT
Size of the colors array of SDL_MessageBoxColorScheme.
{
    SDL_MESSAGEBOX_COLOR_BACKGROUND,
    SDL_MESSAGEBOX_COLOR_TEXT,
    SDL_MESSAGEBOX_COLOR_BUTTON_BORDER,
    SDL_MESSAGEBOX_COLOR_BUTTON_BACKGROUND,
    SDL_MESSAGEBOX_COLOR_BUTTON_SELECTED,
    SDL_MESSAGEBOX_COLOR_COUNT                    /**< Size of the colors array of SDL_MessageBoxColorScheme. */
} SDL_MessageBoxColorType;
Function Documentation
SDL_ShowMessageBox()
SDL_DECLSPEC bool SDLCALL SDL_ShowMessageBox (const SDL_MessageBoxData * messageboxdata, int * buttonid) extern
Create a modal message box.
If your needs aren't complex, it might be easier to use SDL_ShowSimpleMessageBox.
This function should be called on the thread that created the parent window, or on the main thread if the messagebox has no parent. It will block execution of that thread until the user clicks a button or closes the messagebox.
This function may be called at any time, even before SDL_Init(). This makes it useful for reporting errors like a failure to create a renderer or OpenGL context.
On X11, SDL rolls its own dialog box with X11 primitives instead of a formal toolkit like GTK+ or Qt.
Note that if SDL_Init() would fail because there isn't any available video target, this function is likely to fail for the same reasons. If this is a concern, check the return value from this function and fall back to writing to stderr if you can.
Parameters
messageboxdata the SDL_MessageBoxData structure with title, text and other options.
buttonid the pointer to which user id of hit button should be copied.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShowSimpleMessageBox
{
    int dummybutton;
    bool result = false;
    bool show_cursor_prev;
    SDL_Window *current_window;
    SDL_MessageBoxData mbdata;
    if (!messageboxdata) {
        return SDL_InvalidParamError("messageboxdata");
    } else if (messageboxdata->numbuttons < 0) {
        return SDL_SetError("Invalid number of buttons");
    }
    // in case either the title or message was a pointer from SDL_GetError(), make a copy
    // now, as we'll likely overwrite error state in here.
    bool titleisstack = false, msgisstack = false;
    char *titlecpy = NULL;
    char *msgcpy = NULL;
    if (messageboxdata->title) {
        const size_t slen = SDL_strlen(messageboxdata->title) + 1;
        titlecpy = SDL_small_alloc(char, slen, &titleisstack);
        if (!titlecpy) {
            return false;
        }
        SDL_memcpy(titlecpy, messageboxdata->title, slen);
    }
    if (messageboxdata->message) {
        const size_t slen = SDL_strlen(messageboxdata->message) + 1;
        msgcpy = SDL_small_alloc(char, slen, &msgisstack);
        if (!msgcpy) {
            SDL_small_free(titlecpy, titleisstack);
            return false;
        }
        SDL_memcpy(msgcpy, messageboxdata->message, slen);
    }
    (void)SDL_AtomicIncRef(&SDL_messagebox_count);
    current_window = SDL_GetKeyboardFocus();
    SDL_UpdateMouseCapture(false);
    SDL_SetRelativeMouseMode(false);
    show_cursor_prev = SDL_CursorVisible();
    SDL_ShowCursor();
    SDL_ResetKeyboard();
    if (!buttonID) {
        buttonID = &dummybutton;
    }
    SDL_memcpy(&mbdata, messageboxdata, sizeof(*messageboxdata));
    mbdata.title = titlecpy;
    if (!mbdata.title) {
        mbdata.title = "";
    }
    mbdata.message = msgcpy;
    if (!mbdata.message) {
        mbdata.message = "";
    }
    messageboxdata = &mbdata;
    SDL_ClearError();
    if (_this && _this->ShowMessageBox) {
        result = _this->ShowMessageBox(_this, messageboxdata, buttonID);
    } else {
        // It's completely fine to call this function before video is initialized
        const char *driver_name = SDL_GetHint(SDL_HINT_VIDEO_DRIVER);
        if (driver_name && *driver_name != 0) {
            const char *driver_attempt = driver_name;
            while (driver_attempt && (*driver_attempt != 0) && !result) {
                const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
                size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
                for (int i = 0; bootstrap[i]; ++i) {
                    if (bootstrap[i]->ShowMessageBox && (driver_attempt_len == SDL_strlen(bootstrap[i]->name)) &&
                        (SDL_strncasecmp(bootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                        if (bootstrap[i]->ShowMessageBox(messageboxdata, buttonID)) {
                            result = true;
                        }
                        break;
                    }
                }
                driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
            }
        } else {
            for (int i = 0; bootstrap[i]; ++i) {
                if (bootstrap[i]->ShowMessageBox && bootstrap[i]->ShowMessageBox(messageboxdata, buttonID)) {
                    result = true;
                    break;
                }
            }
        }
    }
    if (!result) {
        const char *error = SDL_GetError();
        if (!*error) {
            SDL_SetError("No message system available");
        }
    } else {
        SDL_ClearError();
    }
    (void)SDL_AtomicDecRef(&SDL_messagebox_count);
    if (current_window) {
        SDL_RaiseWindow(current_window);
    }
    if (!show_cursor_prev) {
        SDL_HideCursor();
    }
    SDL_UpdateRelativeMouseMode();
    SDL_UpdateMouseCapture(false);
    SDL_small_free(msgcpy, msgisstack);
    SDL_small_free(titlecpy, titleisstack);
    return result;
}
References _this, bootstrap, SDL_MessageBoxData::message, NULL, SDL_MessageBoxData::numbuttons, SDL_AtomicDecRef, SDL_AtomicIncRef, SDL_ClearError(), SDL_CursorVisible(), SDL_GetError(), SDL_GetHint(), SDL_GetKeyboardFocus(), SDL_HideCursor(), SDL_HINT_VIDEO_DRIVER, SDL_InvalidParamError, SDL_memcpy, SDL_messagebox_count, SDL_RaiseWindow(), SDL_ResetKeyboard(), SDL_SetError(), SDL_SetRelativeMouseMode(), SDL_ShowCursor(), SDL_small_alloc, SDL_small_free, SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), SDL_UpdateMouseCapture(), SDL_UpdateRelativeMouseMode(), SDL_MessageBoxData::title, and void().
Referenced by SDL_PromptAssertion(), and SDL_ShowSimpleMessageBox().
SDL_ShowSimpleMessageBox()
SDL_DECLSPEC bool SDLCALL SDL_ShowSimpleMessageBox (SDL_MessageBoxFlags flags, const char * title, const char * message, SDL_Window * window) extern
Display a simple modal message box.
If your needs aren't complex, this function is preferred over SDL_ShowMessageBox.
flags may be any of the following:
SDL_MESSAGEBOX_ERROR: error dialog
SDL_MESSAGEBOX_WARNING: warning dialog
SDL_MESSAGEBOX_INFORMATION: informational dialog
This function should be called on the thread that created the parent window, or on the main thread if the messagebox has no parent. It will block execution of that thread until the user clicks a button or closes the messagebox.
This function may be called at any time, even before SDL_Init(). This makes it useful for reporting errors like a failure to create a renderer or OpenGL context.
On X11, SDL rolls its own dialog box with X11 primitives instead of a formal toolkit like GTK+ or Qt.
Note that if SDL_Init() would fail because there isn't any available video target, this function is likely to fail for the same reasons. If this is a concern, check the return value from this function and fall back to writing to stderr if you can.
Parameters
flags an SDL_MessageBoxFlags value.
title UTF-8 title text.
message UTF-8 message text.
window the parent window, or NULL for no parent.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShowMessageBox
{
#if defined(SDL_PLATFORM_3DS)
    errorConf errCnf;
    bool hasGpuRight;
    // If the video subsystem has not been initialised, set up graphics temporarily
    hasGpuRight = gspHasGpuRight();
    if (!hasGpuRight)
        gfxInitDefault();
    errorInit(&errCnf, ERROR_TEXT_WORD_WRAP, CFG_LANGUAGE_EN);
    errorText(&errCnf, message);
    errorDisp(&errCnf);
    if (!hasGpuRight)
        gfxExit();
    return true;
#else
    SDL_MessageBoxData data;
    SDL_MessageBoxButtonData button;
    SDL_zero(data);
    data.flags = flags;
    data.title = title;
    data.message = message;
    data.numbuttons = 1;
    data.buttons = &button;
    data.window = window;
    SDL_zero(button);
    button.flags |= SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT;
    button.flags |= SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT;
    button.text = "OK";
    return SDL_ShowMessageBox(&data, NULL);
#endif
}
References SDL_MessageBoxButtonData::flags, NULL, SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT, SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT, SDL_ShowMessageBox(), SDL_zero, and SDL_MessageBoxButtonData::text.
Referenced by OutOfMemory(), SDL_PromptAssertion(), and SDL_RunApp().