SDL3: SDL-main/src/joystick/SDL_gamepad.c File Reference
SDL_gamepad.c File Reference
#include "SDL_internal.h"
#include "SDL_sysjoystick.h"
#include "SDL_joystick_c.h"
#include "SDL_steam_virtual_gamepad.h"
#include "SDL_gamepad_c.h"
#include "SDL_gamepad_db.h"
#include "controller_type.h"
#include "usb_ids.h"
#include "hidapi/SDL_hidapi_nintendo.h"
#include "../events/SDL_events_c.h"
Data Structures
struct GamepadMapping_t
struct MappingChangeTracker
struct SDL_Gamepad
Macros
#define _guarded SDL_GUARDED_BY(SDL_joystick_lock)
#define _guarded SDL_GUARDED_BY(SDL_joystick_lock)
#define CHECK_GAMEPAD_MAGIC(gamepad, result)
#define SDL_GAMEPAD_CRC_FIELD "crc:"
#define SDL_GAMEPAD_CRC_FIELD_SIZE 4
#define SDL_GAMEPAD_FACE_FIELD "face:"
#define SDL_GAMEPAD_FACE_FIELD_SIZE 5
#define SDL_GAMEPAD_HINT_FIELD "hint:"
#define SDL_GAMEPAD_HINT_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_HINT_FIELD)
#define SDL_GAMEPAD_PLATFORM_FIELD "platform:"
#define SDL_GAMEPAD_PLATFORM_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_PLATFORM_FIELD)
#define SDL_GAMEPAD_SDKGE_FIELD "sdk>=:"
#define SDL_GAMEPAD_SDKGE_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_SDKGE_FIELD)
#define SDL_GAMEPAD_SDKLE_FIELD "sdk<=:"
#define SDL_GAMEPAD_SDKLE_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_SDKLE_FIELD)
#define SDL_GAMEPAD_TYPE_FIELD "type:"
#define SDL_GAMEPAD_TYPE_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_TYPE_FIELD)
#define SDL_MINIMUM_GUIDE_BUTTON_DELAY_MS 250
Typedefs
typedef struct GamepadMapping_t GamepadMapping_t
Enumerations
enum SDL_GamepadFaceStyle {
SDL_GAMEPAD_FACE_STYLE_UNKNOWN , SDL_GAMEPAD_FACE_STYLE_ABXY , SDL_GAMEPAD_FACE_STYLE_AXBY , SDL_GAMEPAD_FACE_STYLE_BAYX ,
SDL_GAMEPAD_FACE_STYLE_SONY
}
enum SDL_GamepadMappingPriority { SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT , SDL_GAMEPAD_MAPPING_PRIORITY_API , SDL_GAMEPAD_MAPPING_PRIORITY_USER }
Functions
static void AddMappingChangeTracking (GamepadMapping_t *mapping)
static void AdjustSensorOrientation (const SDL_Joystick *joystick, const float *src, float *dst)
static char * CreateMappingString (GamepadMapping_t *mapping, SDL_GUID guid)
static void HandleJoystickAxis (Uint64 timestamp, SDL_Gamepad *gamepad, int axis, int value)
static void HandleJoystickButton (Uint64 timestamp, SDL_Gamepad *gamepad, int button, bool down)
static void HandleJoystickHat (Uint64 timestamp, SDL_Gamepad *gamepad, int hat, Uint8 value)
static bool HasMappingChangeTracking (MappingChangeTracker *tracker, GamepadMapping_t *mapping)
static bool HasSameOutput (SDL_GamepadBinding *a, SDL_GamepadBinding *b)
static void PopMappingChangeTracking (void)
static void PushMappingChangeTracking (void)
static void RecenterGamepad (SDL_Gamepad *gamepad)
static void ResetOutput (Uint64 timestamp, SDL_Gamepad *gamepad, SDL_GamepadBinding *bind)
int SDL_AddGamepadMapping (const char *mapping)
int SDL_AddGamepadMappingsFromFile (const char *file)
int SDL_AddGamepadMappingsFromIO (SDL_IOStream *src, bool closeio)
void SDL_CloseGamepad (SDL_Gamepad *gamepad)
SDL_COMPILE_TIME_ASSERT (map_StringForGamepadAxis, SDL_arraysize(map_StringForGamepadAxis)==SDL_GAMEPAD_AXIS_COUNT)
SDL_COMPILE_TIME_ASSERT (map_StringForGamepadButton, SDL_arraysize(map_StringForGamepadButton)==SDL_GAMEPAD_BUTTON_COUNT)
SDL_COMPILE_TIME_ASSERT (map_StringForGamepadType, SDL_arraysize(map_StringForGamepadType)==SDL_GAMEPAD_TYPE_COUNT)
static char * SDL_ConvertMappingToPositionalAXBY (const char *mapping)
static char * SDL_ConvertMappingToPositionalBAXY (const char *mapping)
static GamepadMapping_t * SDL_CreateMappingForHIDAPIGamepad (SDL_GUID guid)
static GamepadMapping_t * SDL_CreateMappingForRAWINPUTGamepad (SDL_GUID guid)
static GamepadMapping_t * SDL_CreateMappingForWGIGamepad (SDL_GUID guid)
static void SDL_FixupHIDAPIMapping (SDL_Gamepad *gamepad)
bool SDL_GamepadConnected (SDL_Gamepad *gamepad)
bool SDL_GamepadEventsEnabled (void)
static bool SDLCALL SDL_GamepadEventWatcher (void *userdata, SDL_Event *event)
void SDL_GamepadHandleDelayedGuideButton (SDL_Joystick *joystick)
bool SDL_GamepadHasAxis (SDL_Gamepad *gamepad, SDL_GamepadAxis axis)
bool SDL_GamepadHasButton (SDL_Gamepad *gamepad, SDL_GamepadButton button)
bool SDL_GamepadHasSensor (SDL_Gamepad *gamepad, SDL_SensorType type)
bool SDL_GamepadSensorEnabled (SDL_Gamepad *gamepad, SDL_SensorType type)
void SDL_GamepadSensorWatcher (Uint64 timestamp, SDL_SensorID sensor, Uint64 sensor_timestamp, float *data, int num_values)
const char * SDL_GetGamepadAppleSFSymbolsNameForAxis (SDL_Gamepad *gamepad, SDL_GamepadAxis axis)
const char * SDL_GetGamepadAppleSFSymbolsNameForButton (SDL_Gamepad *gamepad, SDL_GamepadButton button)
Sint16 SDL_GetGamepadAxis (SDL_Gamepad *gamepad, SDL_GamepadAxis axis)
SDL_GamepadAxis SDL_GetGamepadAxisFromString (const char *str)
SDL_GamepadBinding ** SDL_GetGamepadBindings (SDL_Gamepad *gamepad, int *count)
bool SDL_GetGamepadButton (SDL_Gamepad *gamepad, SDL_GamepadButton button)
SDL_GamepadButton SDL_GetGamepadButtonFromString (const char *str)
SDL_GamepadButtonLabel SDL_GetGamepadButtonLabel (SDL_Gamepad *gamepad, SDL_GamepadButton button)
static SDL_GamepadButtonLabel SDL_GetGamepadButtonLabelForFaceStyle (SDL_GamepadFaceStyle face_style, SDL_GamepadButton button)
SDL_GamepadButtonLabel SDL_GetGamepadButtonLabelForType (SDL_GamepadType type, SDL_GamepadButton button)
SDL_JoystickConnectionState SDL_GetGamepadConnectionState (SDL_Gamepad *gamepad)
static SDL_GamepadFaceStyle SDL_GetGamepadFaceStyleForGamepadType (SDL_GamepadType type)
static SDL_GamepadFaceStyle SDL_GetGamepadFaceStyleFromString (const char *string)
Uint16 SDL_GetGamepadFirmwareVersion (SDL_Gamepad *gamepad)
SDL_Gamepad * SDL_GetGamepadFromID (SDL_JoystickID joyid)
SDL_Gamepad * SDL_GetGamepadFromPlayerIndex (int player_index)
SDL_GUID SDL_GetGamepadGUIDForID (SDL_JoystickID instance_id)
SDL_JoystickID SDL_GetGamepadID (SDL_Gamepad *gamepad)
SDL_Joystick * SDL_GetGamepadJoystick (SDL_Gamepad *gamepad)
char * SDL_GetGamepadMapping (SDL_Gamepad *gamepad)
static bool SDL_GetGamepadMappingFilePath (char *path, size_t size)
char * SDL_GetGamepadMappingForGUID (SDL_GUID guid)
char * SDL_GetGamepadMappingForID (SDL_JoystickID instance_id)
char ** SDL_GetGamepadMappings (int *count)
const char * SDL_GetGamepadName (SDL_Gamepad *gamepad)
const char * SDL_GetGamepadNameForID (SDL_JoystickID instance_id)
const char * SDL_GetGamepadPath (SDL_Gamepad *gamepad)
const char * SDL_GetGamepadPathForID (SDL_JoystickID instance_id)
int SDL_GetGamepadPlayerIndex (SDL_Gamepad *gamepad)
int SDL_GetGamepadPlayerIndexForID (SDL_JoystickID instance_id)
SDL_PowerState SDL_GetGamepadPowerInfo (SDL_Gamepad *gamepad, int *percent)
Uint16 SDL_GetGamepadProduct (SDL_Gamepad *gamepad)
Uint16 SDL_GetGamepadProductForID (SDL_JoystickID instance_id)
Uint16 SDL_GetGamepadProductVersion (SDL_Gamepad *gamepad)
Uint16 SDL_GetGamepadProductVersionForID (SDL_JoystickID instance_id)
SDL_PropertiesID SDL_GetGamepadProperties (SDL_Gamepad *gamepad)
SDL_JoystickID * SDL_GetGamepads (int *count)
bool SDL_GetGamepadSensorData (SDL_Gamepad *gamepad, SDL_SensorType type, float *data, int num_values)
float SDL_GetGamepadSensorDataRate (SDL_Gamepad *gamepad, SDL_SensorType type)
const char * SDL_GetGamepadSerial (SDL_Gamepad *gamepad)
Uint64 SDL_GetGamepadSteamHandle (SDL_Gamepad *gamepad)
const char * SDL_GetGamepadStringForAxis (SDL_GamepadAxis axis)
const char * SDL_GetGamepadStringForButton (SDL_GamepadButton button)
const char * SDL_GetGamepadStringForType (SDL_GamepadType type)
bool SDL_GetGamepadTouchpadFinger (SDL_Gamepad *gamepad, int touchpad, int finger, bool *down, float *x, float *y, float *pressure)
SDL_GamepadType SDL_GetGamepadType (SDL_Gamepad *gamepad)
SDL_GamepadType SDL_GetGamepadTypeForID (SDL_JoystickID instance_id)
SDL_GamepadType SDL_GetGamepadTypeFromString (const char *str)
Uint16 SDL_GetGamepadVendor (SDL_Gamepad *gamepad)
Uint16 SDL_GetGamepadVendorForID (SDL_JoystickID instance_id)
int SDL_GetNumGamepadTouchpadFingers (SDL_Gamepad *gamepad, int touchpad)
int SDL_GetNumGamepadTouchpads (SDL_Gamepad *gamepad)
SDL_GamepadType SDL_GetRealGamepadType (SDL_Gamepad *gamepad)
SDL_GamepadType SDL_GetRealGamepadTypeForID (SDL_JoystickID instance_id)
static SDL_Gamepad *SDL_gamepads SDL_GUARDED_BY (SDL_joystick_lock) = NULL
bool SDL_HasGamepad (void)
bool SDL_InitGamepadMappings (void)
bool SDL_InitGamepads (void)
bool SDL_IsGamepad (SDL_JoystickID instance_id)
bool SDL_IsGamepadNameAndGUID (const char *name, SDL_GUID guid)
static void SDL_LoadGamepadHints (void)
SDL_Gamepad * SDL_OpenGamepad (SDL_JoystickID instance_id)
static int SDL_PrivateAddGamepadMapping (const char *mappingString, SDL_GamepadMappingPriority priority)
static GamepadMapping_t * SDL_PrivateAddMappingForGUID (SDL_GUID jGUID, const char *mappingString, bool *existing, SDL_GamepadMappingPriority priority)
static void SDL_PrivateAppendToMappingString (char *mapping_string, size_t mapping_string_len, const char *input_name, SDL_InputMapping *mapping)
void SDL_PrivateGamepadAdded (SDL_JoystickID instance_id)
static void SDL_PrivateGamepadRemapped (SDL_JoystickID instance_id)
void SDL_PrivateGamepadRemoved (SDL_JoystickID instance_id)
static GamepadMapping_t * SDL_PrivateGenerateAutomaticGamepadMapping (const char *name, SDL_GUID guid, SDL_GamepadMapping *raw_map)
static SDL_GamepadButton SDL_PrivateGetGamepadButtonFromString (const char *str, bool axby, bool baxy)
static char * SDL_PrivateGetGamepadGUIDFromMappingString (const char *pMapping)
static GamepadMapping_t * SDL_PrivateGetGamepadMapping (SDL_JoystickID instance_id, bool create_mapping)
static GamepadMapping_t * SDL_PrivateGetGamepadMappingForGUID (SDL_GUID guid, bool adding_mapping)
static GamepadMapping_t * SDL_PrivateGetGamepadMappingForNameAndGUID (const char *name, SDL_GUID guid)
static char * SDL_PrivateGetGamepadMappingFromMappingString (const char *pMapping)
static char * SDL_PrivateGetGamepadNameFromMappingString (const char *pMapping)
static void SDL_PrivateLoadButtonMapping (SDL_Gamepad *gamepad, GamepadMapping_t *pGamepadMapping)
static GamepadMapping_t * SDL_PrivateMatchGamepadMappingForGUID (SDL_GUID guid, bool match_version, bool exact_match_crc)
static bool SDL_PrivateParseGamepadConfigString (SDL_Gamepad *gamepad, const char *pchString)
static bool SDL_PrivateParseGamepadElement (SDL_Gamepad *gamepad, const char *szGameButton, const char *szJoystickButton)
void SDL_QuitGamepadMappings (void)
void SDL_QuitGamepads (void)
bool SDL_ReloadGamepadMappings (void)
bool SDL_RumbleGamepad (SDL_Gamepad *gamepad, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms)
bool SDL_RumbleGamepadTriggers (SDL_Gamepad *gamepad, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms)
static void SDL_SendGamepadAxis (Uint64 timestamp, SDL_Gamepad *gamepad, SDL_GamepadAxis axis, Sint16 value)
static void SDL_SendGamepadButton (Uint64 timestamp, SDL_Gamepad *gamepad, SDL_GamepadButton button, bool down)
bool SDL_SendGamepadEffect (SDL_Gamepad *gamepad, const void *data, int size)
void SDL_SetGamepadEventsEnabled (bool enabled)
bool SDL_SetGamepadLED (SDL_Gamepad *gamepad, Uint8 red, Uint8 green, Uint8 blue)
bool SDL_SetGamepadMapping (SDL_JoystickID instance_id, const char *mapping)
bool SDL_SetGamepadPlayerIndex (SDL_Gamepad *gamepad, int player_index)
bool SDL_SetGamepadSensorEnabled (SDL_Gamepad *gamepad, SDL_SensorType type, bool enabled)
bool SDL_ShouldIgnoreGamepad (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
static void SDL_UpdateGamepadFaceStyle (SDL_Gamepad *gamepad)
void SDL_UpdateGamepads (void)
static void SDL_UpdateGamepadType (SDL_Gamepad *gamepad)
Variables
static const char * map_StringForGamepadAxis []
static const char * map_StringForGamepadButton []
static const char * map_StringForGamepadType []
static SDL_GUID s_zeroGUID
static SDL_vidpid_list SDL_allowed_gamepads
static const Uint32 SDL_gamepad_event_list []
static bool SDL_gamepads_initialized
static SDL_vidpid_list SDL_ignored_gamepads
Macro Definition Documentation
_guarded [1/2]
#define _guarded SDL_GUARDED_BY(SDL_joystick_lock)
Referenced by GamepadMapping_t::SDL_GUARDED_BY(), MappingChangeTracker::SDL_GUARDED_BY(), and SDL_Gamepad::SDL_GUARDED_BY().
_guarded [2/2]
#define _guarded SDL_GUARDED_BY(SDL_joystick_lock)
CHECK_GAMEPAD_MAGIC
#define CHECK_GAMEPAD_MAGIC (gamepad, result)
Value:
    if (!SDL_ObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD) ||   \
        !SDL_IsJoystickValid(gamepad->joystick)) {              \
        SDL_InvalidParamError("gamepad");                       \
        SDL_UnlockJoysticks();                                  \
        return result;                                          \
    }
#define CHECK_GAMEPAD_MAGIC(gamepad, result)                    \
    if (!SDL_ObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD) ||   \
        !SDL_IsJoystickValid(gamepad->joystick)) {              \
        SDL_InvalidParamError("gamepad");                       \
        SDL_UnlockJoysticks();                                  \
        return result;                                          \
    }
Referenced by SDL_GamepadHasAxis(), SDL_GamepadHasButton(), SDL_GetGamepadAppleSFSymbolsNameForAxis(), SDL_GetGamepadAppleSFSymbolsNameForButton(), SDL_GetGamepadAxis(), SDL_GetGamepadBindings(), SDL_GetGamepadButton(), SDL_GetGamepadButtonLabel(), SDL_GetGamepadJoystick(), SDL_GetGamepadMapping(), SDL_GetGamepadName(), SDL_GetGamepadProperties(), SDL_GetGamepadSteamHandle(), and SDL_GetGamepadType().
SDL_GAMEPAD_CRC_FIELD
#define SDL_GAMEPAD_CRC_FIELD "crc:"
Referenced by SDL_PrivateAddMappingForGUID(), and SDL_PrivateMatchGamepadMappingForGUID().
SDL_GAMEPAD_CRC_FIELD_SIZE
#define SDL_GAMEPAD_CRC_FIELD_SIZE 4
Referenced by SDL_PrivateAddMappingForGUID(), and SDL_PrivateMatchGamepadMappingForGUID().
SDL_GAMEPAD_FACE_FIELD
#define SDL_GAMEPAD_FACE_FIELD "face:"
Referenced by SDL_UpdateGamepadFaceStyle().
SDL_GAMEPAD_FACE_FIELD_SIZE
#define SDL_GAMEPAD_FACE_FIELD_SIZE 5
SDL_GAMEPAD_HINT_FIELD
#define SDL_GAMEPAD_HINT_FIELD "hint:"
Referenced by SDL_PrivateAddGamepadMapping().
SDL_GAMEPAD_HINT_FIELD_SIZE
#define SDL_GAMEPAD_HINT_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_HINT_FIELD)
Referenced by SDL_PrivateAddGamepadMapping().
SDL_GAMEPAD_PLATFORM_FIELD
#define SDL_GAMEPAD_PLATFORM_FIELD "platform:"
Referenced by CreateMappingString(), and SDL_AddGamepadMappingsFromIO().
SDL_GAMEPAD_PLATFORM_FIELD_SIZE
#define SDL_GAMEPAD_PLATFORM_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_PLATFORM_FIELD)
Referenced by CreateMappingString(), and SDL_AddGamepadMappingsFromIO().
SDL_GAMEPAD_SDKGE_FIELD
#define SDL_GAMEPAD_SDKGE_FIELD "sdk>=:"
Referenced by SDL_PrivateAddGamepadMapping().
SDL_GAMEPAD_SDKGE_FIELD_SIZE
#define SDL_GAMEPAD_SDKGE_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_SDKGE_FIELD)
Referenced by SDL_PrivateAddGamepadMapping().
SDL_GAMEPAD_SDKLE_FIELD
#define SDL_GAMEPAD_SDKLE_FIELD "sdk<=:"
Referenced by SDL_PrivateAddGamepadMapping().
SDL_GAMEPAD_SDKLE_FIELD_SIZE
#define SDL_GAMEPAD_SDKLE_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_SDKLE_FIELD)
Referenced by SDL_PrivateAddGamepadMapping().
SDL_GAMEPAD_TYPE_FIELD
#define SDL_GAMEPAD_TYPE_FIELD "type:"
Referenced by SDL_GetGamepadTypeForID(), and SDL_UpdateGamepadType().
SDL_GAMEPAD_TYPE_FIELD_SIZE
#define SDL_GAMEPAD_TYPE_FIELD_SIZE SDL_strlen(SDL_GAMEPAD_TYPE_FIELD)
Referenced by SDL_GetGamepadTypeForID(), SDL_UpdateGamepadFaceStyle(), and SDL_UpdateGamepadType().
SDL_MINIMUM_GUIDE_BUTTON_DELAY_MS
#define SDL_MINIMUM_GUIDE_BUTTON_DELAY_MS 250
Referenced by SDL_SendGamepadButton().
Typedef Documentation
GamepadMapping_t
typedef struct GamepadMapping_t GamepadMapping_t
Enumeration Type Documentation
SDL_GamepadFaceStyle
enum SDL_GamepadFaceStyle
Enumerator
SDL_GAMEPAD_FACE_STYLE_UNKNOWN
SDL_GAMEPAD_FACE_STYLE_ABXY
SDL_GAMEPAD_FACE_STYLE_AXBY
SDL_GAMEPAD_FACE_STYLE_BAYX
SDL_GAMEPAD_FACE_STYLE_SONY
{
    SDL_GAMEPAD_FACE_STYLE_UNKNOWN,
    SDL_GAMEPAD_FACE_STYLE_ABXY,
    SDL_GAMEPAD_FACE_STYLE_AXBY,
    SDL_GAMEPAD_FACE_STYLE_BAYX,
    SDL_GAMEPAD_FACE_STYLE_SONY,
} SDL_GamepadFaceStyle;
SDL_GamepadMappingPriority
enum SDL_GamepadMappingPriority
Enumerator
SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT
SDL_GAMEPAD_MAPPING_PRIORITY_API
SDL_GAMEPAD_MAPPING_PRIORITY_USER
{
    SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT,
    SDL_GAMEPAD_MAPPING_PRIORITY_API,
    SDL_GAMEPAD_MAPPING_PRIORITY_USER,
} SDL_GamepadMappingPriority;
Function Documentation
AddMappingChangeTracking()
void AddMappingChangeTracking (GamepadMapping_t * mapping) static
{
    MappingChangeTracker *tracker;
    int num_mappings;
    GamepadMapping_t **new_mappings;
    SDL_AssertJoysticksLocked();
    SDL_assert(s_mappingChangeTracker != NULL);
    tracker = s_mappingChangeTracker;
    num_mappings = tracker->num_changed_mappings;
    new_mappings = (GamepadMapping_t **)SDL_realloc(tracker->changed_mappings, (num_mappings + 1) * sizeof(*new_mappings));
    if (new_mappings) {
        tracker->changed_mappings = new_mappings;
        tracker->changed_mappings[num_mappings] = mapping;
        tracker->num_changed_mappings = (num_mappings + 1);
    }
}
References NULL, SDL_assert, SDL_AssertJoysticksLocked(), and SDL_realloc().
Referenced by SDL_PrivateAddMappingForGUID(), and SDL_ReloadGamepadMappings().
AdjustSensorOrientation()
void AdjustSensorOrientation (const SDL_Joystick * joystick, const float * src, float * dst) static
{
    unsigned int i, j;
    SDL_AssertJoysticksLocked();
    for (i = 0; i < 3; ++i) {
        dst[i] = 0.0f;
        for (j = 0; j < 3; ++j) {
            dst[i] += joystick->sensor_transform[i][j] * src[j];
        }
    }
}
References SDL_AssertJoysticksLocked().
Referenced by SDL_GamepadSensorWatcher().
CreateMappingString()
char * CreateMappingString (GamepadMapping_t * mapping, SDL_GUID guid) static
{
    char *pMappingString, *pPlatformString;
    char pchGUID[33];
    size_t needed;
    bool need_platform = false;
    const char *platform = NULL;
    SDL_AssertJoysticksLocked();
    SDL_GUIDToString(guid, pchGUID, sizeof(pchGUID));
    // allocate enough memory for GUID + ',' + name + ',' + mapping + \0
    needed = SDL_strlen(pchGUID) + 1 + SDL_strlen(mapping->name) + 1 + SDL_strlen(mapping->mapping) + 1;
    if (!SDL_strstr(mapping->mapping, SDL_GAMEPAD_PLATFORM_FIELD)) {
        // add memory for ',' + platform:PLATFORM
        need_platform = true;
        if (mapping->mapping[SDL_strlen(mapping->mapping) - 1] != ',') {
            needed += 1;
        }
        platform = SDL_GetPlatform();
        needed += SDL_GAMEPAD_PLATFORM_FIELD_SIZE + SDL_strlen(platform) + 1;
    }
    pMappingString = (char *)SDL_malloc(needed);
    if (!pMappingString) {
        return NULL;
    }
    (void)SDL_snprintf(pMappingString, needed, "%s,%s,%s", pchGUID, mapping->name, mapping->mapping);
    if (need_platform) {
        if (mapping->mapping[SDL_strlen(mapping->mapping) - 1] != ',') {
            SDL_strlcat(pMappingString, ",", needed);
        }
        SDL_strlcat(pMappingString, SDL_GAMEPAD_PLATFORM_FIELD, needed);
        SDL_strlcat(pMappingString, platform, needed);
        SDL_strlcat(pMappingString, ",", needed);
    }
    // Make sure multiple platform strings haven't made their way into the mapping
    pPlatformString = SDL_strstr(pMappingString, SDL_GAMEPAD_PLATFORM_FIELD);
    if (pPlatformString) {
        pPlatformString = SDL_strstr(pPlatformString + 1, SDL_GAMEPAD_PLATFORM_FIELD);
        if (pPlatformString) {
            *pPlatformString = '\0';
        }
    }
    return pMappingString;
}
References NULL, SDL_AssertJoysticksLocked(), SDL_GAMEPAD_PLATFORM_FIELD, SDL_GAMEPAD_PLATFORM_FIELD_SIZE, SDL_GetPlatform(), SDL_GUIDToString(), SDL_malloc(), SDL_snprintf(), SDL_strlcat(), SDL_strlen(), SDL_strstr(), and void().
Referenced by SDL_GetGamepadMapping(), SDL_GetGamepadMappingForGUID(), and SDL_GetGamepadMappings().
HandleJoystickAxis()
void HandleJoystickAxis (Uint64 timestamp, SDL_Gamepad * gamepad, int axis, int value) static
{
    int i;
    SDL_GamepadBinding *last_match;
    SDL_GamepadBinding *match = NULL;
    SDL_AssertJoysticksLocked();
    last_match = gamepad->last_match_axis[axis];
    for (i = 0; i < gamepad->num_bindings; ++i) {
        SDL_GamepadBinding *binding = &gamepad->bindings[i];
        if (binding->input_type == SDL_GAMEPAD_BINDTYPE_AXIS &&
            axis == binding->input.axis.axis) {
            if (binding->input.axis.axis_min < binding->input.axis.axis_max) {
                if (value >= binding->input.axis.axis_min &&
                    value <= binding->input.axis.axis_max) {
                    match = binding;
                    break;
                }
            } else {
                if (value >= binding->input.axis.axis_max &&
                    value <= binding->input.axis.axis_min) {
                    match = binding;
                    break;
                }
            }
        }
    }
    if (last_match && (!match || !HasSameOutput(last_match, match))) {
        // Clear the last input that this axis generated
        ResetOutput(timestamp, gamepad, last_match);
    }
    if (match) {
        if (match->output_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
            if (match->input.axis.axis_min != match->output.axis.axis_min || match->input.axis.axis_max != match->output.axis.axis_max) {
                float normalized_value = (float)(value - match->input.axis.axis_min) / (match->input.axis.axis_max - match->input.axis.axis_min);
                value = match->output.axis.axis_min + (int)(normalized_value * (match->output.axis.axis_max - match->output.axis.axis_min));
            }
            SDL_SendGamepadAxis(timestamp, gamepad, match->output.axis.axis, (Sint16)value);
        } else {
            bool down;
            int threshold = match->input.axis.axis_min + (match->input.axis.axis_max - match->input.axis.axis_min) / 2;
            if (match->input.axis.axis_max < match->input.axis.axis_min) {
                down = (value <= threshold);
            } else {
                down = (value >= threshold);
            }
            SDL_SendGamepadButton(timestamp, gamepad, match->output.button, down);
        }
    }
    gamepad->last_match_axis[axis] = match;
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, HasSameOutput(), SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, NULL, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, ResetOutput(), SDL_AssertJoysticksLocked(), SDL_GAMEPAD_BINDTYPE_AXIS, SDL_SendGamepadAxis(), and SDL_SendGamepadButton().
Referenced by SDL_GamepadEventWatcher().
HandleJoystickButton()
void HandleJoystickButton (Uint64 timestamp, SDL_Gamepad * gamepad, int button, bool down) static
{
    int i;
    SDL_AssertJoysticksLocked();
    for (i = 0; i < gamepad->num_bindings; ++i) {
        SDL_GamepadBinding *binding = &gamepad->bindings[i];
        if (binding->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON &&
            button == binding->input.button) {
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
                int value = down ? binding->output.axis.axis_max : binding->output.axis.axis_min;
                SDL_SendGamepadAxis(timestamp, gamepad, binding->output.axis.axis, (Sint16)value);
            } else {
                SDL_SendGamepadButton(timestamp, gamepad, binding->output.button, down);
            }
            break;
        }
    }
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_AssertJoysticksLocked(), SDL_GAMEPAD_BINDTYPE_AXIS, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_SendGamepadAxis(), and SDL_SendGamepadButton().
Referenced by SDL_GamepadEventWatcher().
HandleJoystickHat()
void HandleJoystickHat (Uint64 timestamp, SDL_Gamepad * gamepad, int hat, Uint8 value) static
{
    int i;
    Uint8 last_mask, changed_mask;
    SDL_AssertJoysticksLocked();
    last_mask = gamepad->last_hat_mask[hat];
    changed_mask = (last_mask ^ value);
    for (i = 0; i < gamepad->num_bindings; ++i) {
        SDL_GamepadBinding *binding = &gamepad->bindings[i];
        if (binding->input_type == SDL_GAMEPAD_BINDTYPE_HAT && hat == binding->input.hat.hat) {
            if ((changed_mask & binding->input.hat.hat_mask) != 0) {
                if (value & binding->input.hat.hat_mask) {
                    if (binding->output_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
                        SDL_SendGamepadAxis(timestamp, gamepad, binding->output.axis.axis, (Sint16)binding->output.axis.axis_max);
                    } else {
                        SDL_SendGamepadButton(timestamp, gamepad, binding->output.button, true);
                    }
                } else {
                    ResetOutput(timestamp, gamepad, binding);
                }
            }
        }
    }
    gamepad->last_hat_mask[hat] = value;
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, SDL_GamepadBinding::hat, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, ResetOutput(), SDL_AssertJoysticksLocked(), SDL_GAMEPAD_BINDTYPE_AXIS, SDL_GAMEPAD_BINDTYPE_HAT, SDL_SendGamepadAxis(), and SDL_SendGamepadButton().
Referenced by SDL_GamepadEventWatcher().
HasMappingChangeTracking()
bool HasMappingChangeTracking (MappingChangeTracker * tracker, GamepadMapping_t * mapping) static
{
    int i;
    SDL_AssertJoysticksLocked();
    for (i = 0; i < tracker->num_changed_mappings; ++i) {
        if (tracker->changed_mappings[i] == mapping) {
            return true;
        }
    }
    return false;
}
References SDL_AssertJoysticksLocked().
Referenced by PopMappingChangeTracking().
HasSameOutput()
bool HasSameOutput (SDL_GamepadBinding * a, SDL_GamepadBinding * b) static
{
    if (a->output_type != b->output_type) {
        return false;
    }
    if (a->output_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
        return a->output.axis.axis == b->output.axis.axis;
    } else {
        return a->output.button == b->output.button;
    }
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, and SDL_GAMEPAD_BINDTYPE_AXIS.
Referenced by HandleJoystickAxis().
PopMappingChangeTracking()
void PopMappingChangeTracking (void) static
{
    int i;
    MappingChangeTracker *tracker;
    SDL_AssertJoysticksLocked();
    SDL_assert(s_mappingChangeTracker != NULL);
    tracker = s_mappingChangeTracker;
    --tracker->refcount;
    if (tracker->refcount > 0) {
        return;
    }
    s_mappingChangeTracker = NULL;
    // Now check to see what gamepads changed because of the mapping changes
    if (tracker->joysticks && tracker->joystick_mappings) {
        for (i = 0; tracker->joysticks[i]; ++i) {
            // Looking up the new mapping might create one and associate it with the gamepad (and generate events)
            SDL_JoystickID joystick = tracker->joysticks[i];
            SDL_Gamepad *gamepad = SDL_GetGamepadFromID(joystick);
            GamepadMapping_t *new_mapping = SDL_PrivateGetGamepadMapping(joystick, false);
            GamepadMapping_t *old_mapping = gamepad ? gamepad->mapping : tracker->joystick_mappings[i];
            if (new_mapping && !old_mapping) {
                SDL_InsertIntoHashTable(s_gamepadInstanceIDs, (void *)(uintptr_t)joystick, (const void *)true, true);
                SDL_PrivateGamepadAdded(joystick);
            } else if (old_mapping && !new_mapping) {
                SDL_InsertIntoHashTable(s_gamepadInstanceIDs, (void *)(uintptr_t)joystick, (const void *)false, true);
                SDL_PrivateGamepadRemoved(joystick);
            } else if (old_mapping != new_mapping || HasMappingChangeTracking(tracker, new_mapping)) {
                if (gamepad) {
                    SDL_PrivateLoadButtonMapping(gamepad, new_mapping);
                }
                SDL_PrivateGamepadRemapped(joystick);
            }
        }
    }
    SDL_free(tracker->joysticks);
    SDL_free(tracker->joystick_mappings);
    SDL_free(tracker->changed_mappings);
    SDL_free(tracker);
}
References HasMappingChangeTracking(), NULL, SDL_assert, SDL_AssertJoysticksLocked(), SDL_free(), SDL_GetGamepadFromID(), SDL_InsertIntoHashTable(), SDL_PrivateGamepadAdded(), SDL_PrivateGamepadRemapped(), SDL_PrivateGamepadRemoved(), SDL_PrivateGetGamepadMapping(), and SDL_PrivateLoadButtonMapping().
Referenced by SDL_AddGamepadMappingsFromIO(), SDL_InitGamepadMappings(), SDL_LoadGamepadHints(), SDL_PrivateAddMappingForGUID(), and SDL_ReloadGamepadMappings().
PushMappingChangeTracking()
void PushMappingChangeTracking (void) static
{
    MappingChangeTracker *tracker;
    int i, num_joysticks;
    SDL_AssertJoysticksLocked();
    if (s_mappingChangeTracker) {
        ++s_mappingChangeTracker->refcount;
        return;
    }
    s_mappingChangeTracker = (MappingChangeTracker *)SDL_calloc(1, sizeof(*tracker));
    s_mappingChangeTracker->refcount = 1;
    // Save the list of joysticks and associated mappings
    tracker = s_mappingChangeTracker;
    tracker->joysticks = SDL_GetJoysticks(&num_joysticks);
    if (!tracker->joysticks) {
        return;
    }
    if (num_joysticks == 0) {
        return;
    }
    tracker->joystick_mappings = (GamepadMapping_t **)SDL_malloc(num_joysticks * sizeof(*tracker->joystick_mappings));
    if (!tracker->joystick_mappings) {
        return;
    }
    for (i = 0; i < num_joysticks; ++i) {
        tracker->joystick_mappings[i] = SDL_PrivateGetGamepadMapping(tracker->joysticks[i], false);
    }
}
References SDL_AssertJoysticksLocked(), SDL_calloc(), SDL_GetJoysticks(), SDL_malloc(), and SDL_PrivateGetGamepadMapping().
Referenced by SDL_AddGamepadMappingsFromIO(), SDL_InitGamepadMappings(), SDL_LoadGamepadHints(), SDL_PrivateAddMappingForGUID(), and SDL_ReloadGamepadMappings().
RecenterGamepad()
void RecenterGamepad (SDL_Gamepad * gamepad) static
{
    int i;
    Uint64 timestamp = SDL_GetTicksNS();
    for (i = 0; i < SDL_GAMEPAD_BUTTON_COUNT; ++i) {
        SDL_GamepadButton button = (SDL_GamepadButton)i;
        if (SDL_GetGamepadButton(gamepad, button)) {
            SDL_SendGamepadButton(timestamp, gamepad, button, false);
        }
    }
    for (i = 0; i < SDL_GAMEPAD_AXIS_COUNT; ++i) {
        SDL_GamepadAxis axis = (SDL_GamepadAxis)i;
        if (SDL_GetGamepadAxis(gamepad, axis) != 0) {
            SDL_SendGamepadAxis(timestamp, gamepad, axis, 0);
        }
    }
}
References SDL_GAMEPAD_AXIS_COUNT, SDL_GAMEPAD_BUTTON_COUNT, SDL_GetGamepadAxis(), SDL_GetGamepadButton(), SDL_GetTicksNS(), SDL_SendGamepadAxis(), and SDL_SendGamepadButton().
Referenced by SDL_PrivateGamepadRemoved().
ResetOutput()
void ResetOutput (Uint64 timestamp, SDL_Gamepad * gamepad, SDL_GamepadBinding * bind) static
{
    if (bind->output_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
        SDL_SendGamepadAxis(timestamp, gamepad, bind->output.axis.axis, 0);
    } else {
        SDL_SendGamepadButton(timestamp, gamepad, bind->output.button, false);
    }
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_SendGamepadAxis(), and SDL_SendGamepadButton().
Referenced by HandleJoystickAxis(), and HandleJoystickHat().
SDL_AddGamepadMapping()
int SDL_AddGamepadMapping (const char * mapping)
Add support for gamepads that SDL is unaware of or change the binding of an existing gamepad.
The mapping string has the format "GUID,name,mapping", where GUID is the string value from SDL_GUIDToString(), name is the human readable string for the device and mappings are gamepad mappings to joystick ones. Under Windows there is a reserved GUID of "xinput" that covers all XInput devices. The mapping format for joystick is:
bX: a joystick button, index X
hX.Y: hat X with value Y
aX: axis X of the joystick
Buttons can be used as a gamepad axes and vice versa.
If a device with this GUID is already plugged in, SDL will generate an SDL_EVENT_GAMEPAD_ADDED event.
This string shows an example of a valid mapping for a gamepad:
"341a3608000000000000504944564944,Afterglow PS3 Controller,a:b1,b:b2,y:b3,x:b0,start:b9,guide:b12,back:b8,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7"
Parameters
mapping the mapping string.
Returns
1 if a new mapping is added, 0 if an existing mapping is updated, -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMappingsFromFile
SDL_AddGamepadMappingsFromIO
SDL_GetGamepadMapping
SDL_GetGamepadMappingForGUID
SDL_HINT_GAMECONTROLLERCONFIG
SDL_HINT_GAMECONTROLLERCONFIG_FILE
SDL_EVENT_GAMEPAD_ADDED
{
    int result;
    SDL_LockJoysticks();
    {
        result = SDL_PrivateAddGamepadMapping(mapping, SDL_GAMEPAD_MAPPING_PRIORITY_API);
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GAMEPAD_MAPPING_PRIORITY_API, SDL_LockJoysticks(), SDL_PrivateAddGamepadMapping(), and SDL_UnlockJoysticks().
Referenced by SDL_AddGamepadMappingsFromIO().
SDL_AddGamepadMappingsFromFile()
int SDL_AddGamepadMappingsFromFile (const char * file)
Load a set of gamepad mappings from a file.
You can call this function several times, if needed, to load different database files.
If a new mapping is loaded for an already known gamepad GUID, the later version will overwrite the one currently loaded.
Any new mappings for already plugged in controllers will generate SDL_EVENT_GAMEPAD_ADDED events.
Mappings not belonging to the current platform or with no platform field specified will be ignored (i.e. mappings for Linux will be ignored in Windows, etc).
Parameters
file the mappings file to load.
Returns
the number of mappings added or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_AddGamepadMappingsFromIO
SDL_GetGamepadMapping
SDL_GetGamepadMappingForGUID
SDL_HINT_GAMECONTROLLERCONFIG
SDL_HINT_GAMECONTROLLERCONFIG_FILE
SDL_EVENT_GAMEPAD_ADDED
{
    return SDL_AddGamepadMappingsFromIO(SDL_IOFromFile(file, "rb"), true);
}
References SDL_AddGamepadMappingsFromIO(), and SDL_IOFromFile().
Referenced by SDL_InitGamepadMappings().
SDL_AddGamepadMappingsFromIO()
int SDL_AddGamepadMappingsFromIO (SDL_IOStream * src, bool closeio)
Load a set of gamepad mappings from an SDL_IOStream.
You can call this function several times, if needed, to load different database files.
If a new mapping is loaded for an already known gamepad GUID, the later version will overwrite the one currently loaded.
Any new mappings for already plugged in controllers will generate SDL_EVENT_GAMEPAD_ADDED events.
Mappings not belonging to the current platform or with no platform field specified will be ignored (i.e. mappings for Linux will be ignored in Windows, etc).
This function will load the text database entirely in memory before processing it, so take this into consideration if you are in a memory constrained environment.
Parameters
src the data stream for the mappings to be added.
closeio if true, calls SDL_CloseIO() on src before returning, even in the case of an error.
Returns
the number of mappings added or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_AddGamepadMappingsFromFile
SDL_GetGamepadMapping
SDL_GetGamepadMappingForGUID
SDL_HINT_GAMECONTROLLERCONFIG
SDL_HINT_GAMECONTROLLERCONFIG_FILE
SDL_EVENT_GAMEPAD_ADDED
{
    const char *platform = SDL_GetPlatform();
    int gamepads = 0;
    char *buf, *line, *line_end, *tmp, *comma, line_platform[64];
    size_t db_size;
    size_t platform_len;
    buf = (char *)SDL_LoadFile_IO(src, &db_size, closeio);
    if (!buf) {
        SDL_SetError("Could not allocate space to read DB into memory");
        return -1;
    }
    line = buf;
    SDL_LockJoysticks();
    PushMappingChangeTracking();
    while (line < buf + db_size) {
        line_end = SDL_strchr(line, '\n');
        if (line_end) {
            *line_end = '\0';
        } else {
            line_end = buf + db_size;
        }
        // Extract and verify the platform
        tmp = SDL_strstr(line, SDL_GAMEPAD_PLATFORM_FIELD);
        if (tmp) {
            tmp += SDL_GAMEPAD_PLATFORM_FIELD_SIZE;
            comma = SDL_strchr(tmp, ',');
            if (comma) {
                platform_len = comma - tmp + 1;
                if (platform_len + 1 < SDL_arraysize(line_platform)) {
                    SDL_strlcpy(line_platform, tmp, platform_len);
                    if (SDL_strncasecmp(line_platform, platform, platform_len) == 0 &&
                        SDL_AddGamepadMapping(line) > 0) {
                        gamepads++;
                    }
                }
            }
        }
        line = line_end + 1;
    }
    PopMappingChangeTracking();
    SDL_UnlockJoysticks();
    SDL_free(buf);
    return gamepads;
}
References PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_AddGamepadMapping(), SDL_arraysize, SDL_free(), SDL_GAMEPAD_PLATFORM_FIELD, SDL_GAMEPAD_PLATFORM_FIELD_SIZE, SDL_GetPlatform(), SDL_LoadFile_IO(), SDL_LockJoysticks(), SDL_SetError(), SDL_strchr(), SDL_strlcpy(), SDL_strncasecmp(), SDL_strstr(), and SDL_UnlockJoysticks().
Referenced by SDL_AddGamepadMappingsFromFile().
SDL_CloseGamepad()
void SDL_CloseGamepad (SDL_Gamepad * gamepad)
Close a gamepad previously opened with SDL_OpenGamepad().
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenGamepad
{
    SDL_Gamepad *gamepadlist, *gamepadlistprev;
    SDL_LockJoysticks();
    if (!SDL_ObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD)) {
        SDL_UnlockJoysticks();
        return;
    }
    // First decrement ref count
    if (--gamepad->ref_count > 0) {
        SDL_UnlockJoysticks();
        return;
    }
    SDL_CloseJoystick(gamepad->joystick);
    gamepadlist = SDL_gamepads;
    gamepadlistprev = NULL;
    while (gamepadlist) {
        if (gamepad == gamepadlist) {
            if (gamepadlistprev) {
                // unlink this entry
                gamepadlistprev->next = gamepadlist->next;
            } else {
                SDL_gamepads = gamepad->next;
            }
            break;
        }
        gamepadlistprev = gamepadlist;
        gamepadlist = gamepadlist->next;
    }
    SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
    SDL_free(gamepad->bindings);
    SDL_free(gamepad->last_match_axis);
    SDL_free(gamepad->last_hat_mask);
    SDL_free(gamepad);
    SDL_UnlockJoysticks();
}
References NULL, SDL_CloseJoystick(), SDL_free(), SDL_LockJoysticks(), SDL_OBJECT_TYPE_GAMEPAD, SDL_ObjectValid(), SDL_SetObjectValid(), and SDL_UnlockJoysticks().
Referenced by SDL_QuitGamepads().
SDL_COMPILE_TIME_ASSERT() [1/3]
SDL_COMPILE_TIME_ASSERT (map_StringForGamepadAxis , SDL_arraysize(map_StringForGamepadAxis) = =SDL_GAMEPAD_AXIS_COUNT)
References map_StringForGamepadAxis, and SDL_GAMEPAD_AXIS_COUNT.
SDL_COMPILE_TIME_ASSERT() [2/3]
SDL_COMPILE_TIME_ASSERT (map_StringForGamepadButton , SDL_arraysize(map_StringForGamepadButton) = =SDL_GAMEPAD_BUTTON_COUNT)
References map_StringForGamepadButton, and SDL_GAMEPAD_BUTTON_COUNT.
SDL_COMPILE_TIME_ASSERT() [3/3]
SDL_COMPILE_TIME_ASSERT (map_StringForGamepadType , SDL_arraysize(map_StringForGamepadType) = =SDL_GAMEPAD_TYPE_COUNT)
References map_StringForGamepadType, and SDL_GAMEPAD_TYPE_COUNT.
SDL_ConvertMappingToPositionalAXBY()
char * SDL_ConvertMappingToPositionalAXBY (const char * mapping) static
{
    // Add space for '!' and null terminator
    size_t length = SDL_strlen(mapping) + 1 + 1;
    char *remapped = (char *)SDL_malloc(length);
    if (remapped) {
        char *button_B;
        char *button_X;
        char *hint;
        SDL_strlcpy(remapped, mapping, length);
        button_B = SDL_strstr(remapped, ",b:");
        button_X = SDL_strstr(remapped, ",x:");
        hint = SDL_strstr(remapped, "hint:SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS");
        if (button_B) {
            button_B[1] = 'x';
        }
        if (button_X) {
            button_X[1] = 'b';
        }
        if (hint) {
            hint += 5;
            SDL_memmove(hint + 1, hint, SDL_strlen(hint) + 1);
            *hint = '!';
        }
    }
    return remapped;
}
References SDL_malloc(), SDL_memmove, SDL_strlcpy(), SDL_strlen(), and SDL_strstr().
Referenced by SDL_PrivateAddGamepadMapping().
SDL_ConvertMappingToPositionalBAXY()
char * SDL_ConvertMappingToPositionalBAXY (const char * mapping) static
{
    // Add space for '!' and null terminator
    size_t length = SDL_strlen(mapping) + 1 + 1;
    char *remapped = (char *)SDL_malloc(length);
    if (remapped) {
        char *button_A;
        char *button_B;
        char *button_X;
        char *button_Y;
        char *hint;
        SDL_strlcpy(remapped, mapping, length);
        button_A = SDL_strstr(remapped, ",a:");
        button_B = SDL_strstr(remapped, ",b:");
        button_X = SDL_strstr(remapped, ",x:");
        button_Y = SDL_strstr(remapped, ",y:");
        hint = SDL_strstr(remapped, "hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS");
        if (button_A) {
            button_A[1] = 'b';
        }
        if (button_B) {
            button_B[1] = 'a';
        }
        if (button_X) {
            button_X[1] = 'y';
        }
        if (button_Y) {
            button_Y[1] = 'x';
        }
        if (hint) {
            hint += 5;
            SDL_memmove(hint + 1, hint, SDL_strlen(hint) + 1);
            *hint = '!';
        }
    }
    return remapped;
}
References SDL_malloc(), SDL_memmove, SDL_strlcpy(), SDL_strlen(), and SDL_strstr().
Referenced by SDL_PrivateAddGamepadMapping().
SDL_CreateMappingForHIDAPIGamepad()
GamepadMapping_t * SDL_CreateMappingForHIDAPIGamepad (SDL_GUID guid) static
{
    bool existing;
    char mapping_string[1024];
    Uint16 vendor;
    Uint16 product;
    SDL_strlcpy(mapping_string, "none,*,", sizeof(mapping_string));
    SDL_GetJoystickGUIDInfo(guid, &vendor, &product, NULL, NULL);
    if (SDL_IsJoystickWheel(vendor, product)) {
        // We don't want to pick up Logitech FFB wheels here
        // Some versions of WINE will also not treat devices that show up as gamepads as wheels
        return NULL;
    }
    if ((vendor == USB_VENDOR_NINTENDO && product == USB_PRODUCT_NINTENDO_GAMECUBE_ADAPTER) ||
        (vendor == USB_VENDOR_DRAGONRISE &&
         (product == USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER1 ||
          product == USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER2 ||
          product == USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER3))) {
        // GameCube driver has 12 buttons and 6 axes
        SDL_strlcat(mapping_string, "a:b0,b:b2,dpdown:b6,dpleft:b4,dpright:b5,dpup:b7,lefttrigger:a4,leftx:a0,lefty:a1~,rightshoulder:b9,righttrigger:a5,rightx:a2,righty:a3~,start:b8,x:b1,y:b3,hint:!SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS:=1,", sizeof(mapping_string));
    } else if (vendor == USB_VENDOR_NINTENDO &&
               (guid.data[15] == k_eSwitchDeviceInfoControllerType_HVCLeft ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_HVCRight ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_NESLeft ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_NESRight ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_SNES ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_N64 ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_SEGA_Genesis ||
                guid.data[15] == k_eWiiExtensionControllerType_None ||
                guid.data[15] == k_eWiiExtensionControllerType_Nunchuk ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_JoyConLeft ||
                guid.data[15] == k_eSwitchDeviceInfoControllerType_JoyConRight)) {
        switch (guid.data[15]) {
        case k_eSwitchDeviceInfoControllerType_HVCLeft:
            SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b9,rightshoulder:b10,start:b6,", sizeof(mapping_string));
            break;
        case k_eSwitchDeviceInfoControllerType_HVCRight:
            SDL_strlcat(mapping_string, "a:b0,b:b1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b9,rightshoulder:b10,", sizeof(mapping_string));
            break;
        case k_eSwitchDeviceInfoControllerType_NESLeft:
        case k_eSwitchDeviceInfoControllerType_NESRight:
            SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b9,rightshoulder:b10,start:b6,", sizeof(mapping_string));
            break;
        case k_eSwitchDeviceInfoControllerType_SNES:
            SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b9,lefttrigger:a4,rightshoulder:b10,righttrigger:a5,start:b6,x:b2,y:b3,hint:!SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,", sizeof(mapping_string));
            break;
        case k_eSwitchDeviceInfoControllerType_N64:
            SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,righttrigger:a5,start:b6,x:b2,y:b3,misc1:b11,", sizeof(mapping_string));
            break;
        case k_eSwitchDeviceInfoControllerType_SEGA_Genesis:
            SDL_strlcat(mapping_string, "a:b0,b:b1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b5,leftshoulder:b9,rightshoulder:b10,righttrigger:a5,start:b6,x:b2,y:b3,misc1:b11,", sizeof(mapping_string));
            break;
        case k_eWiiExtensionControllerType_None:
            SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b5,start:b6,x:b2,y:b3,", sizeof(mapping_string));
            break;
        case k_eWiiExtensionControllerType_Nunchuk:
        {
            // FIXME: Should we map this to the left or right side?
            const bool map_nunchuck_left_side = true;
            if (map_nunchuck_left_side) {
                SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,leftshoulder:b9,lefttrigger:a4,leftx:a0,lefty:a1,start:b6,x:b2,y:b3,", sizeof(mapping_string));
            } else {
                SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,dpup:b11,guide:b5,rightshoulder:b9,righttrigger:a4,rightx:a0,righty:a1,start:b6,x:b2,y:b3,", sizeof(mapping_string));
            }
        } break;
        default:
            if (SDL_GetHintBoolean(SDL_HINT_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS, false)) {
                // Vertical mode
                if (guid.data[15] == k_eSwitchDeviceInfoControllerType_JoyConLeft) {
                    SDL_strlcat(mapping_string, "back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,misc1:b11,paddle2:b13,paddle4:b15,", sizeof(mapping_string));
                } else {
                    SDL_strlcat(mapping_string, "a:b0,b:b1,guide:b5,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,paddle1:b12,paddle3:b14,", sizeof(mapping_string));
                }
            } else {
                // Mini gamepad mode
                if (guid.data[15] == k_eSwitchDeviceInfoControllerType_JoyConLeft) {
                    SDL_strlcat(mapping_string, "a:b0,b:b1,guide:b5,leftshoulder:b9,leftstick:b7,leftx:a0,lefty:a1,rightshoulder:b10,start:b6,x:b2,y:b3,paddle2:b13,paddle4:b15,", sizeof(mapping_string));
                } else {
                    SDL_strlcat(mapping_string, "a:b0,b:b1,guide:b5,leftshoulder:b9,leftstick:b7,leftx:a0,lefty:a1,rightshoulder:b10,start:b6,x:b2,y:b3,paddle1:b12,paddle3:b14,", sizeof(mapping_string));
                }
            }
            break;
        }
    } else if (vendor == USB_VENDOR_8BITDO &&
               (product == USB_PRODUCT_8BITDO_SF30_PRO ||
                product == USB_PRODUCT_8BITDO_SF30_PRO_BT ||
                product == USB_PRODUCT_8BITDO_SN30_PRO ||
                product == USB_PRODUCT_8BITDO_SN30_PRO_BT ||
                product == USB_PRODUCT_8BITDO_PRO_2 ||
                product == USB_PRODUCT_8BITDO_PRO_2_BT ||
                product == USB_PRODUCT_8BITDO_PRO_3)) {
            SDL_strlcat(mapping_string, "a:b1,b:b0,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b3,y:b2,hint:!SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,", sizeof(mapping_string));
            if (product == USB_PRODUCT_8BITDO_PRO_2 || product == USB_PRODUCT_8BITDO_PRO_2_BT) {
                SDL_strlcat(mapping_string, "paddle1:b14,paddle2:b13,", sizeof(mapping_string));
            } else if (product == USB_PRODUCT_8BITDO_PRO_3) {
                SDL_strlcat(mapping_string, "paddle1:b12,paddle2:b11,paddle3:b14,paddle4:b13,", sizeof(mapping_string));
            }
    } else if (vendor == USB_VENDOR_8BITDO &&
               (product == USB_PRODUCT_8BITDO_SF30_PRO ||
                product == USB_PRODUCT_8BITDO_SF30_PRO_BT)) {
            // This controller has no guide button
            SDL_strlcat(mapping_string, "a:b1,b:b0,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b3,y:b2,hint:!SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,", sizeof(mapping_string));
    } else if (SDL_IsJoystickSInputController(vendor, product)) {
        Uint8 face_style = (guid.data[15] & 0xF0) >> 4;
        Uint8 u_id = guid.data[15] & 0x0F;
        switch (product) {
        case USB_PRODUCT_HANDHELDLEGEND_PROGCC:
            // ProGCC Mapping
            SDL_strlcat(mapping_string, "a:b1,b:b0,back:b11,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b4,lefttrigger:b8,leftx:a0,lefty:a1,misc1:b13,rightshoulder:b7,rightstick:b5,righttrigger:b9,rightx:a2,righty:a3,start:b10,x:b3,y:b2,hint:!SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1,", sizeof(mapping_string));
            break;
        case USB_PRODUCT_HANDHELDLEGEND_GCULTIMATE:
            // GC Ultimate Map
            SDL_strlcat(mapping_string, "a:b0,b:b2,back:b11,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b6,leftstick:b4,lefttrigger:a4,leftx:a0,lefty:a1,misc1:b13,misc2:b14,rightshoulder:b7,rightstick:b5,righttrigger:a5,rightx:a2,righty:a3,start:b10,x:b1,y:b3,misc3:b8,misc4:b9,hint:!SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS:=1,", sizeof(mapping_string));
            break;
        case USB_PRODUCT_HANDHELDLEGEND_SINPUT_GENERIC:
            switch (u_id) {
            case 1:
                // SuperGamepad+ Map
                SDL_strlcat(mapping_string, "a:b1,b:b0,back:b7,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,rightshoulder:b5,start:b6,x:b3,y:b2,", sizeof(mapping_string));
                break;
            default:
                // Unknown mapping
                return NULL;
            }
            // Apply face style
            switch (face_style) {
            default:
            case 1:
                SDL_strlcat(mapping_string, "face:abxy,", sizeof(mapping_string));
                break;
            case 2:
                SDL_strlcat(mapping_string, "face:axby,", sizeof(mapping_string));
                break;
            case 3:
                SDL_strlcat(mapping_string, "face:bayx,", sizeof(mapping_string));
                break;
            case 4:
                SDL_strlcat(mapping_string, "face:sony,", sizeof(mapping_string));
                break;
            }
            break;
        default:
        case USB_PRODUCT_BONJIRICHANNEL_FIREBIRD:
            // Unmapped devices
            return NULL;
        }
    } else {
        // All other gamepads have the standard set of 19 buttons and 6 axes
        if (SDL_IsJoystickGameCube(vendor, product)) {
            SDL_strlcat(mapping_string, "a:b0,b:b2,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b1,y:b3,hint:!SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS:=1,", sizeof(mapping_string));
        } else {
            SDL_strlcat(mapping_string, "a:b0,b:b1,back:b4,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b5,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,", sizeof(mapping_string));
        }
        if (SDL_IsJoystickSteamController(vendor, product)) {
            // Steam controllers have 2 back paddle buttons
            SDL_strlcat(mapping_string, "paddle1:b12,paddle2:b11,", sizeof(mapping_string));
        } else if (SDL_IsJoystickNintendoSwitchPro(vendor, product) ||
                   SDL_IsJoystickNintendoSwitchProInputOnly(vendor, product)) {
            // Nintendo Switch Pro controllers have a screenshot button
            SDL_strlcat(mapping_string, "misc1:b11,", sizeof(mapping_string));
        } else if (SDL_IsJoystickNintendoSwitchJoyConPair(vendor, product)) {
            // The Nintendo Switch Joy-Con combined controllers has a share button and paddles
            SDL_strlcat(mapping_string, "misc1:b11,paddle1:b12,paddle2:b13,paddle3:b14,paddle4:b15,", sizeof(mapping_string));
        } else if (SDL_IsJoystickAmazonLunaController(vendor, product)) {
            // Amazon Luna Controller has a mic button under the guide button
            SDL_strlcat(mapping_string, "misc1:b11,", sizeof(mapping_string));
        } else if (SDL_IsJoystickGoogleStadiaController(vendor, product)) {
            // The Google Stadia controller has a share button and a Google Assistant button
            SDL_strlcat(mapping_string, "misc1:b11,misc2:b12,", sizeof(mapping_string));
        } else if (SDL_IsJoystickNVIDIASHIELDController(vendor, product)) {
            // The NVIDIA SHIELD controller has a share button between back and start buttons
            SDL_strlcat(mapping_string, "misc1:b11,", sizeof(mapping_string));
            if (product == USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V103) {
                // The original SHIELD controller has a touchpad and plus/minus buttons as well
                SDL_strlcat(mapping_string, "touchpad:b12,misc2:b13,misc3:b14,", sizeof(mapping_string));
            }
        } else if (SDL_IsJoystickHoriSteamController(vendor, product)) {
            /* The Wireless HORIPad for Steam has QAM, Steam, Capsense L/R Sticks, 2 rear buttons, and 2 misc buttons */
            SDL_strlcat(mapping_string, "paddle1:b13,paddle2:b12,paddle3:b15,paddle4:b14,misc2:b11,misc3:b16,misc4:b17", sizeof(mapping_string));
        } else if (SDL_IsJoystickFlydigiController(vendor, product)) {
            SDL_strlcat(mapping_string, "paddle1:b11,paddle2:b12,paddle3:b13,paddle4:b14,", sizeof(mapping_string));
            switch (guid.data[15]) {
            case 20:
            case 21:
            case 22:
            case 23:
            case 28:
            case 80:
            case 81:
            case 85:
            case 105:
                // Vader series of controllers have C/Z buttons
                SDL_strlcat(mapping_string, "misc2:b15,misc3:b16,", sizeof(mapping_string));
                break;
            }
        } else if (vendor == USB_VENDOR_8BITDO && product == USB_PRODUCT_8BITDO_ULTIMATE2_WIRELESS) {
            SDL_strlcat(mapping_string, "paddle1:b12,paddle2:b11,paddle3:b14,paddle4:b13,", sizeof(mapping_string));
        } else {
            switch (SDL_GetGamepadTypeFromGUID(guid, NULL)) {
            case SDL_GAMEPAD_TYPE_PS4:
                // PS4 controllers have an additional touchpad button
                SDL_strlcat(mapping_string, "touchpad:b11,", sizeof(mapping_string));
                break;
            case SDL_GAMEPAD_TYPE_PS5:
                // PS5 controllers have a microphone button and an additional touchpad button
                SDL_strlcat(mapping_string, "touchpad:b11,misc1:b12,", sizeof(mapping_string));
                // DualSense Edge controllers have paddles
                if (SDL_IsJoystickDualSenseEdge(vendor, product)) {
                    SDL_strlcat(mapping_string, "paddle1:b16,paddle2:b15,paddle3:b14,paddle4:b13,", sizeof(mapping_string));
                }
                break;
            case SDL_GAMEPAD_TYPE_XBOXONE:
                if (SDL_IsJoystickXboxOneElite(vendor, product)) {
                    // XBox One Elite Controllers have 4 back paddle buttons
                    SDL_strlcat(mapping_string, "paddle1:b11,paddle2:b13,paddle3:b12,paddle4:b14,", sizeof(mapping_string));
                } else if (SDL_IsJoystickXboxSeriesX(vendor, product)) {
                    // XBox Series X Controllers have a share button under the guide button
                    SDL_strlcat(mapping_string, "misc1:b11,", sizeof(mapping_string));
                }
                break;
            default:
                if (vendor == 0 && product == 0) {
                    // This is a Bluetooth Nintendo Switch Pro controller
                    SDL_strlcat(mapping_string, "misc1:b11,", sizeof(mapping_string));
                }
                break;
            }
        }
    }
    return SDL_PrivateAddMappingForGUID(guid, mapping_string, &existing, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT);
}
References SDL_GUID::data, k_eSwitchDeviceInfoControllerType_HVCLeft, k_eSwitchDeviceInfoControllerType_HVCRight, k_eSwitchDeviceInfoControllerType_JoyConLeft, k_eSwitchDeviceInfoControllerType_JoyConRight, k_eSwitchDeviceInfoControllerType_N64, k_eSwitchDeviceInfoControllerType_NESLeft, k_eSwitchDeviceInfoControllerType_NESRight, k_eSwitchDeviceInfoControllerType_SEGA_Genesis, k_eSwitchDeviceInfoControllerType_SNES, k_eWiiExtensionControllerType_None, k_eWiiExtensionControllerType_Nunchuk, NULL, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT, SDL_GAMEPAD_TYPE_PS4, SDL_GAMEPAD_TYPE_PS5, SDL_GAMEPAD_TYPE_XBOXONE, SDL_GetGamepadTypeFromGUID(), SDL_GetHintBoolean(), SDL_GetJoystickGUIDInfo(), SDL_HINT_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS, SDL_IsJoystickAmazonLunaController(), SDL_IsJoystickDualSenseEdge(), SDL_IsJoystickFlydigiController(), SDL_IsJoystickGameCube(), SDL_IsJoystickGoogleStadiaController(), SDL_IsJoystickHoriSteamController(), SDL_IsJoystickNintendoSwitchJoyConPair(), SDL_IsJoystickNintendoSwitchPro(), SDL_IsJoystickNintendoSwitchProInputOnly(), SDL_IsJoystickNVIDIASHIELDController(), SDL_IsJoystickSInputController(), SDL_IsJoystickSteamController(), SDL_IsJoystickWheel(), SDL_IsJoystickXboxOneElite(), SDL_IsJoystickXboxSeriesX(), SDL_PrivateAddMappingForGUID(), SDL_strlcat(), SDL_strlcpy(), USB_PRODUCT_8BITDO_PRO_2, USB_PRODUCT_8BITDO_PRO_2_BT, USB_PRODUCT_8BITDO_PRO_3, USB_PRODUCT_8BITDO_SF30_PRO, USB_PRODUCT_8BITDO_SF30_PRO_BT, USB_PRODUCT_8BITDO_SN30_PRO, USB_PRODUCT_8BITDO_SN30_PRO_BT, USB_PRODUCT_8BITDO_ULTIMATE2_WIRELESS, USB_PRODUCT_BONJIRICHANNEL_FIREBIRD, USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER1, USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER2, USB_PRODUCT_EVORETRO_GAMECUBE_ADAPTER3, USB_PRODUCT_HANDHELDLEGEND_GCULTIMATE, USB_PRODUCT_HANDHELDLEGEND_PROGCC, USB_PRODUCT_HANDHELDLEGEND_SINPUT_GENERIC, USB_PRODUCT_NINTENDO_GAMECUBE_ADAPTER, USB_PRODUCT_NVIDIA_SHIELD_CONTROLLER_V103, USB_VENDOR_8BITDO, USB_VENDOR_DRAGONRISE, and USB_VENDOR_NINTENDO.
Referenced by SDL_PrivateGetGamepadMappingForGUID().
SDL_CreateMappingForRAWINPUTGamepad()
GamepadMapping_t * SDL_CreateMappingForRAWINPUTGamepad (SDL_GUID guid) static
{
    bool existing;
    char mapping_string[1024];
    SDL_strlcpy(mapping_string, "none,*,", sizeof(mapping_string));
    SDL_strlcat(mapping_string, "a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,", sizeof(mapping_string));
    return SDL_PrivateAddMappingForGUID(guid, mapping_string, &existing, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT);
}
References SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT, SDL_PrivateAddMappingForGUID(), SDL_strlcat(), and SDL_strlcpy().
Referenced by SDL_PrivateGetGamepadMappingForGUID().
SDL_CreateMappingForWGIGamepad()
GamepadMapping_t * SDL_CreateMappingForWGIGamepad (SDL_GUID guid) static
{
    bool existing;
    char mapping_string[1024];
    if (guid.data[15] != SDL_JOYSTICK_TYPE_GAMEPAD) {
        return NULL;
    }
    SDL_strlcpy(mapping_string, "none,*,", sizeof(mapping_string));
    SDL_strlcat(mapping_string, "a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:b10,dpdown:b12,dpleft:b13,dpright:b11,leftx:a1,lefty:a0~,rightx:a3,righty:a2~,lefttrigger:a4,righttrigger:a5,", sizeof(mapping_string));
    return SDL_PrivateAddMappingForGUID(guid, mapping_string, &existing, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT);
}
References SDL_GUID::data, NULL, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT, SDL_JOYSTICK_TYPE_GAMEPAD, SDL_PrivateAddMappingForGUID(), SDL_strlcat(), and SDL_strlcpy().
Referenced by SDL_PrivateGetGamepadMappingForGUID().
SDL_FixupHIDAPIMapping()
void SDL_FixupHIDAPIMapping (SDL_Gamepad * gamepad) static
{
    // Check to see if we need fixup
    bool need_fixup = false;
    for (int i = 0; i < gamepad->num_bindings; ++i) {
        SDL_GamepadBinding *binding = &gamepad->bindings[i];
        if (binding->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON &&
            binding->output.button >= SDL_GAMEPAD_BUTTON_DPAD_UP) {
            if (binding->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON &&
                binding->input.button == binding->output.button) {
                // Old style binding
                need_fixup = true;
            }
            break;
        }
    }
    if (!need_fixup) {
        return;
    }
    for (int i = 0; i < gamepad->num_bindings; ++i) {
        SDL_GamepadBinding *binding = &gamepad->bindings[i];
        if (binding->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON &&
            binding->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON) {
            switch (binding->output.button) {
            case SDL_GAMEPAD_BUTTON_DPAD_UP:
                binding->input_type = SDL_GAMEPAD_BINDTYPE_HAT;
                binding->input.hat.hat = 0;
                binding->input.hat.hat_mask = SDL_HAT_UP;
                break;
            case SDL_GAMEPAD_BUTTON_DPAD_DOWN:
                binding->input_type = SDL_GAMEPAD_BINDTYPE_HAT;
                binding->input.hat.hat = 0;
                binding->input.hat.hat_mask = SDL_HAT_DOWN;
                break;
            case SDL_GAMEPAD_BUTTON_DPAD_LEFT:
                binding->input_type = SDL_GAMEPAD_BINDTYPE_HAT;
                binding->input.hat.hat = 0;
                binding->input.hat.hat_mask = SDL_HAT_LEFT;
                break;
            case SDL_GAMEPAD_BUTTON_DPAD_RIGHT:
                binding->input_type = SDL_GAMEPAD_BINDTYPE_HAT;
                binding->input.hat.hat = 0;
                binding->input.hat.hat_mask = SDL_HAT_RIGHT;
                break;
            default:
                if (binding->output.button > SDL_GAMEPAD_BUTTON_DPAD_RIGHT) {
                    binding->input.button -= 4;
                }
                break;
            }
        }
    }
}
References SDL_GamepadBinding::button, SDL_GamepadBinding::hat, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_GAMEPAD_BINDTYPE_HAT, SDL_GAMEPAD_BUTTON_DPAD_DOWN, SDL_GAMEPAD_BUTTON_DPAD_LEFT, SDL_GAMEPAD_BUTTON_DPAD_RIGHT, SDL_GAMEPAD_BUTTON_DPAD_UP, SDL_HAT_DOWN, SDL_HAT_LEFT, SDL_HAT_RIGHT, and SDL_HAT_UP.
Referenced by SDL_PrivateLoadButtonMapping().
SDL_GamepadConnected()
bool SDL_GamepadConnected (SDL_Gamepad * gamepad)
Check if a gamepad has been opened and is currently connected.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
true if the gamepad has been opened and is currently connected, or false if not.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_JoystickConnected(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_JoystickConnected().
SDL_GamepadEventsEnabled()
bool SDL_GamepadEventsEnabled (void)
Query the state of gamepad event processing.
If gamepad events are disabled, you must call SDL_UpdateGamepads() yourself and check the state of the gamepad when you want gamepad information.
Returns
true if gamepad events are being processed, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetGamepadEventsEnabled
{
    bool enabled = false;
    unsigned int i;
    for (i = 0; i < SDL_arraysize(SDL_gamepad_event_list); ++i) {
        enabled = SDL_EventEnabled(SDL_gamepad_event_list[i]);
        if (enabled) {
            break;
        }
    }
    return enabled;
}
References SDL_arraysize, SDL_EventEnabled(), and SDL_gamepad_event_list.
SDL_GamepadEventWatcher()
bool SDLCALL SDL_GamepadEventWatcher (void * userdata, SDL_Event * event) static
{
    SDL_Gamepad *gamepad;
    switch (event->type) {
    case SDL_EVENT_JOYSTICK_AXIS_MOTION:
    {
        SDL_AssertJoysticksLocked();
        for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
            if (gamepad->joystick->instance_id == event->jaxis.which) {
                HandleJoystickAxis(event->common.timestamp, gamepad, event->jaxis.axis, event->jaxis.value);
                break;
            }
        }
    } break;
    case SDL_EVENT_JOYSTICK_BUTTON_DOWN:
    case SDL_EVENT_JOYSTICK_BUTTON_UP:
    {
        SDL_AssertJoysticksLocked();
        for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
            if (gamepad->joystick->instance_id == event->jbutton.which) {
                HandleJoystickButton(event->common.timestamp, gamepad, event->jbutton.button, event->jbutton.down);
                break;
            }
        }
    } break;
    case SDL_EVENT_JOYSTICK_HAT_MOTION:
    {
        SDL_AssertJoysticksLocked();
        for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
            if (gamepad->joystick->instance_id == event->jhat.which) {
                HandleJoystickHat(event->common.timestamp, gamepad, event->jhat.hat, event->jhat.value);
                break;
            }
        }
    } break;
    case SDL_EVENT_JOYSTICK_UPDATE_COMPLETE:
    {
        SDL_AssertJoysticksLocked();
        if (SDL_EventEnabled(SDL_EVENT_GAMEPAD_UPDATE_COMPLETE)) {
            for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
                if (gamepad->joystick->instance_id == event->jdevice.which) {
                    SDL_Event deviceevent;
                    deviceevent.type = SDL_EVENT_GAMEPAD_UPDATE_COMPLETE;
                    deviceevent.common.timestamp = event->jdevice.timestamp;
                    deviceevent.gdevice.which = event->jdevice.which;
                    SDL_PushEvent(&deviceevent);
                    break;
                }
            }
        }
    } break;
    default:
        break;
    }
    return true;
}
References SDL_Event::common, SDL_Event::gdevice, HandleJoystickAxis(), HandleJoystickButton(), HandleJoystickHat(), SDL_AssertJoysticksLocked(), SDL_EVENT_GAMEPAD_UPDATE_COMPLETE, SDL_EVENT_JOYSTICK_AXIS_MOTION, SDL_EVENT_JOYSTICK_BUTTON_DOWN, SDL_EVENT_JOYSTICK_BUTTON_UP, SDL_EVENT_JOYSTICK_HAT_MOTION, SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_EventEnabled(), SDL_PushEvent(), SDLCALL, SDL_CommonEvent::timestamp, SDL_Event::type, and SDL_GamepadDeviceEvent::which.
Referenced by SDL_InitGamepads(), and SDL_QuitGamepads().
SDL_GamepadHandleDelayedGuideButton()
void SDL_GamepadHandleDelayedGuideButton (SDL_Joystick * joystick)
{
    SDL_Gamepad *gamepad;
    SDL_AssertJoysticksLocked();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        if (gamepad->joystick == joystick) {
            SDL_SendGamepadButton(0, gamepad, SDL_GAMEPAD_BUTTON_GUIDE, false);
            // Make sure we send an update complete event for this change
            if (!gamepad->joystick->update_complete) {
                gamepad->joystick->update_complete = SDL_GetTicksNS();
            }
            break;
        }
    }
}
References SDL_AssertJoysticksLocked(), SDL_GAMEPAD_BUTTON_GUIDE, SDL_GetTicksNS(), and SDL_SendGamepadButton().
Referenced by SDL_UpdateJoysticks().
SDL_GamepadHasAxis()
bool SDL_GamepadHasAxis (SDL_Gamepad * gamepad, SDL_GamepadAxis axis)
Return whether a gamepad has a given axis
{
    bool result = false;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, false);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_AXIS && binding->output.axis.axis == axis) {
                result = true;
                break;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::axis, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GamepadHasButton()
bool SDL_GamepadHasButton (SDL_Gamepad * gamepad, SDL_GamepadButton button)
Return whether a gamepad has a given button
{
    bool result = false;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, false);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON && binding->output.button == button) {
                result = true;
                break;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::button, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GamepadHasSensor()
bool SDL_GamepadHasSensor (SDL_Gamepad * gamepad, SDL_SensorType type)
Return whether a gamepad has a particular sensor.
{
    bool result = false;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                if (joystick->sensors[i].type == type) {
                    result = true;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GamepadSensorEnabled()
bool SDL_GamepadSensorEnabled (SDL_Gamepad * gamepad, SDL_SensorType type)
Query whether sensor data reporting is enabled for a gamepad.
Parameters
gamepad the gamepad to query.
type the type of sensor to query.
Returns
true if the sensor is enabled, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetGamepadSensorEnabled
{
    bool result = false;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                if (joystick->sensors[i].type == type) {
                    result = joystick->sensors[i].enabled;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GamepadSensorWatcher()
void SDL_GamepadSensorWatcher (Uint64 timestamp, SDL_SensorID sensor, Uint64 sensor_timestamp, float * data, int num_values)
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        if (gamepad->joystick->accel && gamepad->joystick->accel_sensor == sensor) {
            float gamepad_data[3];
            AdjustSensorOrientation(gamepad->joystick, data, gamepad_data);
            SDL_SendJoystickSensor(timestamp, gamepad->joystick, SDL_SENSOR_ACCEL, sensor_timestamp, gamepad_data, SDL_arraysize(gamepad_data));
        }
        if (gamepad->joystick->gyro && gamepad->joystick->gyro_sensor == sensor) {
            float gamepad_data[3];
            AdjustSensorOrientation(gamepad->joystick, data, gamepad_data);
            SDL_SendJoystickSensor(timestamp, gamepad->joystick, SDL_SENSOR_GYRO, sensor_timestamp, gamepad_data, SDL_arraysize(gamepad_data));
        }
    }
    SDL_UnlockJoysticks();
}
References AdjustSensorOrientation(), SDL_arraysize, SDL_LockJoysticks(), SDL_SendJoystickSensor(), SDL_SENSOR_ACCEL, SDL_SENSOR_GYRO, and SDL_UnlockJoysticks().
Referenced by SDL_SendSensorUpdate().
SDL_GetGamepadAppleSFSymbolsNameForAxis()
const char * SDL_GetGamepadAppleSFSymbolsNameForAxis (SDL_Gamepad * gamepad, SDL_GamepadAxis axis)
Return the sfSymbolsName for a given axis on a gamepad on Apple platforms.
Parameters
gamepad the gamepad to query.
axis an axis on the gamepad.
Returns
the sfSymbolsName or NULL if the name can't be found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadAppleSFSymbolsNameForButton
{
    const char *result = NULL;
#ifdef SDL_JOYSTICK_MFI
    const char *IOS_GetAppleSFSymbolsNameForAxis(SDL_Gamepad *gamepad, SDL_GamepadAxis axis);
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        result = IOS_GetAppleSFSymbolsNameForAxis(gamepad, axis);
    }
    SDL_UnlockJoysticks();
#endif
    return result;
}
References CHECK_GAMEPAD_MAGIC, IOS_GetAppleSFSymbolsNameForAxis(), NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadAppleSFSymbolsNameForButton()
const char * SDL_GetGamepadAppleSFSymbolsNameForButton (SDL_Gamepad * gamepad, SDL_GamepadButton button)
Return the sfSymbolsName for a given button on a gamepad on Apple platforms.
Parameters
gamepad the gamepad to query.
button a button on the gamepad.
Returns
the sfSymbolsName or NULL if the name can't be found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadAppleSFSymbolsNameForAxis
{
    const char *result = NULL;
#ifdef SDL_JOYSTICK_MFI
    const char *IOS_GetAppleSFSymbolsNameForButton(SDL_Gamepad *gamepad, SDL_GamepadButton button);
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        result = IOS_GetAppleSFSymbolsNameForButton(gamepad, button);
    }
    SDL_UnlockJoysticks();
#endif
    return result;
}
References CHECK_GAMEPAD_MAGIC, IOS_GetAppleSFSymbolsNameForButton(), NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadAxis()
Sint16 SDL_GetGamepadAxis (SDL_Gamepad * gamepad, SDL_GamepadAxis axis)
Get the current state of an axis control on a gamepad.
The axis indices start at index 0.
For thumbsticks, the state is a value ranging from -32768 (up/left) to 32767 (down/right).
Triggers range from 0 when released to 32767 when fully pressed, and never return a negative value. Note that this differs from the value reported by the lower-level SDL_GetJoystickAxis(), which normally uses the full range.
Note that for invalid gamepads or axes, this will return 0. Zero is also a valid value in normal operation; usually it means a centered axis.
Parameters
gamepad a gamepad.
axis an axis index (one of the SDL_GamepadAxis values).
Returns
axis state.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasAxis
SDL_GetGamepadButton
{
    Sint16 result = 0;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, 0);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_AXIS && binding->output.axis.axis == axis) {
                int value = 0;
                bool valid_input_range;
                bool valid_output_range;
                if (binding->input_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
                    value = SDL_GetJoystickAxis(gamepad->joystick, binding->input.axis.axis);
                    if (binding->input.axis.axis_min < binding->input.axis.axis_max) {
                        valid_input_range = (value >= binding->input.axis.axis_min && value <= binding->input.axis.axis_max);
                    } else {
                        valid_input_range = (value >= binding->input.axis.axis_max && value <= binding->input.axis.axis_min);
                    }
                    if (valid_input_range) {
                        if (binding->input.axis.axis_min != binding->output.axis.axis_min || binding->input.axis.axis_max != binding->output.axis.axis_max) {
                            float normalized_value = (float)(value - binding->input.axis.axis_min) / (binding->input.axis.axis_max - binding->input.axis.axis_min);
                            value = binding->output.axis.axis_min + (int)(normalized_value * (binding->output.axis.axis_max - binding->output.axis.axis_min));
                        }
                    } else {
                        value = 0;
                    }
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON) {
                    if (SDL_GetJoystickButton(gamepad->joystick, binding->input.button)) {
                        value = binding->output.axis.axis_max;
                    }
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_HAT) {
                    int hat_mask = SDL_GetJoystickHat(gamepad->joystick, binding->input.hat.hat);
                    if (hat_mask & binding->input.hat.hat_mask) {
                        value = binding->output.axis.axis_max;
                    }
                }
                if (binding->output.axis.axis_min < binding->output.axis.axis_max) {
                    valid_output_range = (value >= binding->output.axis.axis_min && value <= binding->output.axis.axis_max);
                } else {
                    valid_output_range = (value >= binding->output.axis.axis_max && value <= binding->output.axis.axis_min);
                }
                // If the value is zero, there might be another binding that makes it non-zero
                if (value != 0 && valid_output_range) {
                    result = (Sint16)value;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::hat, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_GAMEPAD_BINDTYPE_HAT, SDL_GetJoystickAxis(), SDL_GetJoystickButton(), SDL_GetJoystickHat(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by RecenterGamepad().
SDL_GetGamepadAxisFromString()
SDL_GamepadAxis SDL_GetGamepadAxisFromString (const char * str)
Convert a string into SDL_GamepadAxis enum.
This function is called internally to translate SDL_Gamepad mapping strings for the underlying joystick device into the consistent SDL_Gamepad mapping. You do not normally need to call this function unless you are parsing SDL_Gamepad mappings in your own code.
Note specially that "righttrigger" and "lefttrigger" map to SDL_GAMEPAD_AXIS_RIGHT_TRIGGER and SDL_GAMEPAD_AXIS_LEFT_TRIGGER, respectively.
Parameters
str string representing a SDL_Gamepad axis.
Returns
the SDL_GamepadAxis enum corresponding to the input string, or SDL_GAMEPAD_AXIS_INVALID if no match was found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadStringForAxis
{
    int i;
    if (!str || str[0] == '\0') {
        return SDL_GAMEPAD_AXIS_INVALID;
    }
    if (*str == '+' || *str == '-') {
        ++str;
    }
    for (i = 0; i < SDL_arraysize(map_StringForGamepadAxis); ++i) {
        if (SDL_strcasecmp(str, map_StringForGamepadAxis[i]) == 0) {
            return (SDL_GamepadAxis)i;
        }
    }
    return SDL_GAMEPAD_AXIS_INVALID;
}
References map_StringForGamepadAxis, SDL_arraysize, SDL_GAMEPAD_AXIS_INVALID, and SDL_strcasecmp().
Referenced by SDL_PrivateParseGamepadElement().
SDL_GetGamepadBindings()
SDL_GamepadBinding ** SDL_GetGamepadBindings (SDL_Gamepad * gamepad, int * count)
Get the SDL joystick layer bindings for a gamepad.
Parameters
gamepad a gamepad.
count a pointer filled in with the number of bindings returned.
Returns
a NULL terminated array of pointers to bindings or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    SDL_GamepadBinding **bindings = NULL;
    if (count) {
        *count = 0;
    }
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        size_t pointers_size = ((gamepad->num_bindings + 1) * sizeof(SDL_GamepadBinding *));
        size_t elements_size = (gamepad->num_bindings * sizeof(SDL_GamepadBinding));
        bindings = (SDL_GamepadBinding **)SDL_malloc(pointers_size + elements_size);
        if (bindings) {
            SDL_GamepadBinding *binding = (SDL_GamepadBinding *)((Uint8 *)bindings + pointers_size);
            int i;
            for (i = 0; i < gamepad->num_bindings; ++i, ++binding) {
                bindings[i] = binding;
                SDL_copyp(binding, &gamepad->bindings[i]);
            }
            bindings[i] = NULL;
            if (count) {
                *count = gamepad->num_bindings;
            }
        }
    }
    SDL_UnlockJoysticks();
    return bindings;
}
References CHECK_GAMEPAD_MAGIC, count, NULL, SDL_copyp, SDL_LockJoysticks(), SDL_malloc(), and SDL_UnlockJoysticks().
SDL_GetGamepadButton()
bool SDL_GetGamepadButton (SDL_Gamepad * gamepad, SDL_GamepadButton button)
Get the current state of a button on a gamepad.
Parameters
gamepad a gamepad.
button a button index (one of the SDL_GamepadButton values).
Returns
true if the button is pressed, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasButton
SDL_GetGamepadAxis
{
    bool result = false;
    SDL_LockJoysticks();
    {
        int i;
        CHECK_GAMEPAD_MAGIC(gamepad, false);
        for (i = 0; i < gamepad->num_bindings; ++i) {
            const SDL_GamepadBinding *binding = &gamepad->bindings[i];
            if (binding->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON && binding->output.button == button) {
                if (binding->input_type == SDL_GAMEPAD_BINDTYPE_AXIS) {
                    bool valid_input_range;
                    int value = SDL_GetJoystickAxis(gamepad->joystick, binding->input.axis.axis);
                    int threshold = binding->input.axis.axis_min + (binding->input.axis.axis_max - binding->input.axis.axis_min) / 2;
                    if (binding->input.axis.axis_min < binding->input.axis.axis_max) {
                        valid_input_range = (value >= binding->input.axis.axis_min && value <= binding->input.axis.axis_max);
                        if (valid_input_range) {
                            result |= (value >= threshold);
                        }
                    } else {
                        valid_input_range = (value >= binding->input.axis.axis_max && value <= binding->input.axis.axis_min);
                        if (valid_input_range) {
                            result |= (value <= threshold);
                        }
                    }
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON) {
                    result |= SDL_GetJoystickButton(gamepad->joystick, binding->input.button);
                } else if (binding->input_type == SDL_GAMEPAD_BINDTYPE_HAT) {
                    int hat_mask = SDL_GetJoystickHat(gamepad->joystick, binding->input.hat.hat);
                    result |= ((hat_mask & binding->input.hat.hat_mask) != 0);
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, CHECK_GAMEPAD_MAGIC, SDL_GamepadBinding::hat, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_GAMEPAD_BINDTYPE_HAT, SDL_GetJoystickAxis(), SDL_GetJoystickButton(), SDL_GetJoystickHat(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by RecenterGamepad().
SDL_GetGamepadButtonFromString()
SDL_GamepadButton SDL_GetGamepadButtonFromString (const char * str)
Convert a string into an SDL_GamepadButton enum.
This function is called internally to translate SDL_Gamepad mapping strings for the underlying joystick device into the consistent SDL_Gamepad mapping. You do not normally need to call this function unless you are parsing SDL_Gamepad mappings in your own code.
Parameters
str string representing a SDL_Gamepad axis.
Returns
the SDL_GamepadButton enum corresponding to the input string, or SDL_GAMEPAD_BUTTON_INVALID if no match was found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadStringForButton
{
    return SDL_PrivateGetGamepadButtonFromString(str, false, false);
}
References SDL_PrivateGetGamepadButtonFromString().
SDL_GetGamepadButtonLabel()
SDL_GamepadButtonLabel SDL_GetGamepadButtonLabel (SDL_Gamepad * gamepad, SDL_GamepadButton button)
Get the label of a button on a gamepad.
{
    SDL_GamepadFaceStyle face_style;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN);
        face_style = gamepad->face_style;
    }
    SDL_UnlockJoysticks();
    return SDL_GetGamepadButtonLabelForFaceStyle(face_style, button);
}
References CHECK_GAMEPAD_MAGIC, SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN, SDL_GetGamepadButtonLabelForFaceStyle(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadButtonLabelForFaceStyle()
SDL_GamepadButtonLabel SDL_GetGamepadButtonLabelForFaceStyle (SDL_GamepadFaceStyle face_style, SDL_GamepadButton button) static
Get the label of a button on a gamepad.
{
    SDL_GamepadButtonLabel label = SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN;
    switch (face_style) {
    case SDL_GAMEPAD_FACE_STYLE_ABXY:
        switch (button) {
        case SDL_GAMEPAD_BUTTON_SOUTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_A;
            break;
        case SDL_GAMEPAD_BUTTON_EAST:
            label = SDL_GAMEPAD_BUTTON_LABEL_B;
            break;
        case SDL_GAMEPAD_BUTTON_WEST:
            label = SDL_GAMEPAD_BUTTON_LABEL_X;
            break;
        case SDL_GAMEPAD_BUTTON_NORTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_Y;
            break;
        default:
            break;
        }
        break;
    case SDL_GAMEPAD_FACE_STYLE_AXBY:
        switch (button) {
        case SDL_GAMEPAD_BUTTON_SOUTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_A;
            break;
        case SDL_GAMEPAD_BUTTON_EAST:
            label = SDL_GAMEPAD_BUTTON_LABEL_X;
            break;
        case SDL_GAMEPAD_BUTTON_WEST:
            label = SDL_GAMEPAD_BUTTON_LABEL_B;
            break;
        case SDL_GAMEPAD_BUTTON_NORTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_Y;
            break;
        default:
            break;
        }
        break;
    case SDL_GAMEPAD_FACE_STYLE_BAYX:
        switch (button) {
        case SDL_GAMEPAD_BUTTON_SOUTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_B;
            break;
        case SDL_GAMEPAD_BUTTON_EAST:
            label = SDL_GAMEPAD_BUTTON_LABEL_A;
            break;
        case SDL_GAMEPAD_BUTTON_WEST:
            label = SDL_GAMEPAD_BUTTON_LABEL_Y;
            break;
        case SDL_GAMEPAD_BUTTON_NORTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_X;
            break;
        default:
            break;
        }
        break;
    case SDL_GAMEPAD_FACE_STYLE_SONY:
        switch (button) {
        case SDL_GAMEPAD_BUTTON_SOUTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_CROSS;
            break;
        case SDL_GAMEPAD_BUTTON_EAST:
            label = SDL_GAMEPAD_BUTTON_LABEL_CIRCLE;
            break;
        case SDL_GAMEPAD_BUTTON_WEST:
            label = SDL_GAMEPAD_BUTTON_LABEL_SQUARE;
            break;
        case SDL_GAMEPAD_BUTTON_NORTH:
            label = SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE;
            break;
        default:
            break;
        }
        break;
    default:
        break;
    }
    return label;
}
References SDL_GAMEPAD_BUTTON_EAST, SDL_GAMEPAD_BUTTON_LABEL_A, SDL_GAMEPAD_BUTTON_LABEL_B, SDL_GAMEPAD_BUTTON_LABEL_CIRCLE, SDL_GAMEPAD_BUTTON_LABEL_CROSS, SDL_GAMEPAD_BUTTON_LABEL_SQUARE, SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE, SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN, SDL_GAMEPAD_BUTTON_LABEL_X, SDL_GAMEPAD_BUTTON_LABEL_Y, SDL_GAMEPAD_BUTTON_NORTH, SDL_GAMEPAD_BUTTON_SOUTH, SDL_GAMEPAD_BUTTON_WEST, SDL_GAMEPAD_FACE_STYLE_ABXY, SDL_GAMEPAD_FACE_STYLE_AXBY, SDL_GAMEPAD_FACE_STYLE_BAYX, and SDL_GAMEPAD_FACE_STYLE_SONY.
Referenced by SDL_GetGamepadButtonLabel(), and SDL_GetGamepadButtonLabelForType().
SDL_GetGamepadButtonLabelForType()
SDL_GamepadButtonLabel SDL_GetGamepadButtonLabelForType (SDL_GamepadType type, SDL_GamepadButton button)
Get the label of a button on a gamepad.
{
    return SDL_GetGamepadButtonLabelForFaceStyle(SDL_GetGamepadFaceStyleForGamepadType(type), button);
}
References SDL_GetGamepadButtonLabelForFaceStyle(), and SDL_GetGamepadFaceStyleForGamepadType().
SDL_GetGamepadConnectionState()
SDL_JoystickConnectionState SDL_GetGamepadConnectionState (SDL_Gamepad * gamepad)
Get the connection state of a gamepad.
Parameters
gamepad the gamepad object to query.
Returns
the connection state on success or SDL_JOYSTICK_CONNECTION_INVALID on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return SDL_JOYSTICK_CONNECTION_INVALID;
    }
    return SDL_GetJoystickConnectionState(joystick);
}
References SDL_GetGamepadJoystick(), SDL_GetJoystickConnectionState(), and SDL_JOYSTICK_CONNECTION_INVALID.
SDL_GetGamepadFaceStyleForGamepadType()
SDL_GamepadFaceStyle SDL_GetGamepadFaceStyleForGamepadType (SDL_GamepadType type) static
{
    switch (type) {
    case SDL_GAMEPAD_TYPE_PS3:
    case SDL_GAMEPAD_TYPE_PS4:
    case SDL_GAMEPAD_TYPE_PS5:
        return SDL_GAMEPAD_FACE_STYLE_SONY;
    case SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO:
    case SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT:
    case SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT:
    case SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR:
        return SDL_GAMEPAD_FACE_STYLE_BAYX;
    case SDL_GAMEPAD_TYPE_GAMECUBE:
        return SDL_GAMEPAD_FACE_STYLE_AXBY;
    default:
        return SDL_GAMEPAD_FACE_STYLE_ABXY;
    }
}
References SDL_GAMEPAD_FACE_STYLE_ABXY, SDL_GAMEPAD_FACE_STYLE_AXBY, SDL_GAMEPAD_FACE_STYLE_BAYX, SDL_GAMEPAD_FACE_STYLE_SONY, SDL_GAMEPAD_TYPE_GAMECUBE, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT, SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO, SDL_GAMEPAD_TYPE_PS3, SDL_GAMEPAD_TYPE_PS4, and SDL_GAMEPAD_TYPE_PS5.
Referenced by SDL_GetGamepadButtonLabelForType(), and SDL_UpdateGamepadFaceStyle().
SDL_GetGamepadFaceStyleFromString()
SDL_GamepadFaceStyle SDL_GetGamepadFaceStyleFromString (const char * string) static
{
    if (SDL_strcmp(string, "abxy") == 0) {
        return SDL_GAMEPAD_FACE_STYLE_ABXY;
    } else if (SDL_strcmp(string, "axby") == 0) {
        return SDL_GAMEPAD_FACE_STYLE_AXBY;
    } else if (SDL_strcmp(string, "bayx") == 0) {
        return SDL_GAMEPAD_FACE_STYLE_BAYX;
    } else if (SDL_strcmp(string, "sony") == 0) {
        return SDL_GAMEPAD_FACE_STYLE_SONY;
    } else {
        return SDL_GAMEPAD_FACE_STYLE_UNKNOWN;
    }
}
References SDL_GAMEPAD_FACE_STYLE_ABXY, SDL_GAMEPAD_FACE_STYLE_AXBY, SDL_GAMEPAD_FACE_STYLE_BAYX, SDL_GAMEPAD_FACE_STYLE_SONY, SDL_GAMEPAD_FACE_STYLE_UNKNOWN, and SDL_strcmp().
Referenced by SDL_UpdateGamepadFaceStyle().
SDL_GetGamepadFirmwareVersion()
Uint16 SDL_GetGamepadFirmwareVersion (SDL_Gamepad * gamepad)
Get the firmware version of an opened gamepad, if available.
If the firmware version isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the gamepad firmware version, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickFirmwareVersion(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickFirmwareVersion().
SDL_GetGamepadFromID()
SDL_Gamepad * SDL_GetGamepadFromID (SDL_JoystickID instance_id)
Get the SDL_Gamepad associated with a joystick instance ID, if it has been opened.
Parameters
instance_id the joystick instance ID of the gamepad.
Returns
an SDL_Gamepad on success or NULL on failure or if it hasn't been opened yet; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    gamepad = SDL_gamepads;
    while (gamepad) {
        if (gamepad->joystick->instance_id == joyid) {
            SDL_UnlockJoysticks();
            return gamepad;
        }
        gamepad = gamepad->next;
    }
    SDL_UnlockJoysticks();
    return NULL;
}
References NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by PopMappingChangeTracking(), and SDL_GetGamepadFromPlayerIndex().
SDL_GetGamepadFromPlayerIndex()
SDL_Gamepad * SDL_GetGamepadFromPlayerIndex (int player_index)
Return the SDL_Gamepad associated with a player index.
{
    SDL_Gamepad *result = NULL;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetJoystickFromPlayerIndex(player_index);
        if (joystick) {
            result = SDL_GetGamepadFromID(joystick->instance_id);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_GetGamepadFromID(), SDL_GetJoystickFromPlayerIndex(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadGUIDForID()
SDL_GUID SDL_GetGamepadGUIDForID (SDL_JoystickID instance_id)
Get the implementation-dependent GUID of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the GUID of the selected gamepad. If called on an invalid index, this function returns a zero GUID.
Since
This function is available since SDL 3.2.0.
See also
SDL_GUIDToString
SDL_GetGamepads
{
    return SDL_GetJoystickGUIDForID(instance_id);
}
References SDL_GetJoystickGUIDForID().
SDL_GetGamepadID()
SDL_JoystickID SDL_GetGamepadID (SDL_Gamepad * gamepad)
Get the instance ID of an opened gamepad.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
the instance ID of the specified gamepad on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickID(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickID().
SDL_GetGamepadJoystick()
SDL_Joystick * SDL_GetGamepadJoystick (SDL_Gamepad * gamepad)
Get the underlying joystick from a gamepad.
This function will give you a SDL_Joystick object, which allows you to use the SDL_Joystick functions with a SDL_Gamepad object. This would be useful for getting a joystick's position at any given time, even if it hasn't moved (moving it would produce an event, which would have the axis' value).
The pointer returned is owned by the SDL_Gamepad. You should not call SDL_CloseJoystick() on it, for example, since doing so will likely cause SDL to crash.
Parameters
gamepad the gamepad object that you want to get a joystick from.
Returns
an SDL_Joystick object, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        joystick = gamepad->joystick;
    }
    SDL_UnlockJoysticks();
    return joystick;
}
References CHECK_GAMEPAD_MAGIC, NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by IOS_GetAppleSFSymbolsNameForAxis(), IOS_GetAppleSFSymbolsNameForButton(), SDL_GamepadConnected(), SDL_GamepadHasSensor(), SDL_GamepadSensorEnabled(), SDL_GetGamepadConnectionState(), SDL_GetGamepadFirmwareVersion(), SDL_GetGamepadID(), SDL_GetGamepadPath(), SDL_GetGamepadPlayerIndex(), SDL_GetGamepadPowerInfo(), SDL_GetGamepadProduct(), SDL_GetGamepadProductVersion(), SDL_GetGamepadSensorData(), SDL_GetGamepadSensorDataRate(), SDL_GetGamepadSerial(), SDL_GetGamepadTouchpadFinger(), SDL_GetGamepadVendor(), SDL_GetNumGamepadTouchpadFingers(), SDL_GetNumGamepadTouchpads(), SDL_GetRealGamepadType(), SDL_RumbleGamepad(), SDL_RumbleGamepadTriggers(), SDL_SendGamepadEffect(), SDL_SetGamepadLED(), SDL_SetGamepadPlayerIndex(), and SDL_SetGamepadSensorEnabled().
SDL_GetGamepadMapping()
char * SDL_GetGamepadMapping (SDL_Gamepad * gamepad)
Get the current mapping of a gamepad.
Details about mappings are discussed with SDL_AddGamepadMapping().
Parameters
gamepad the gamepad you want to get the current mapping for.
Returns
a string that has the gamepad's mapping or NULL if no mapping is available; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_GetGamepadMappingForID
SDL_GetGamepadMappingForGUID
SDL_SetGamepadMapping
{
    char *result;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        result = CreateMappingString(gamepad->mapping, gamepad->joystick->guid);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_GAMEPAD_MAGIC, CreateMappingString(), NULL, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadMappingFilePath()
bool SDL_GetGamepadMappingFilePath (char * path, size_t size) static
{
    const char *hint = SDL_GetHint(SDL_HINT_GAMECONTROLLERCONFIG_FILE);
    if (hint && *hint) {
        return SDL_strlcpy(path, hint, size) < size;
    }
#ifdef SDL_PLATFORM_ANDROID
    return SDL_snprintf(path, size, "%s/gamepad_map.txt", SDL_GetAndroidInternalStoragePath()) < size;
#else
    return false;
#endif
}
References SDL_GetAndroidInternalStoragePath(), SDL_GetHint(), SDL_HINT_GAMECONTROLLERCONFIG_FILE, SDL_snprintf(), and SDL_strlcpy().
Referenced by SDL_InitGamepadMappings().
SDL_GetGamepadMappingForGUID()
char * SDL_GetGamepadMappingForGUID (SDL_GUID guid)
Get the gamepad mapping string for a given GUID.
Parameters
guid a structure containing the GUID for which a mapping is desired.
Returns
a mapping string or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickGUIDForID
SDL_GetJoystickGUID
{
    char *result;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMappingForGUID(guid, false);
        if (mapping) {
            result = CreateMappingString(mapping, guid);
        } else {
            SDL_SetError("Mapping not available");
            result = NULL;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CreateMappingString(), NULL, SDL_LockJoysticks(), SDL_PrivateGetGamepadMappingForGUID(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_GetGamepadMappingForID()
char * SDL_GetGamepadMappingForID (SDL_JoystickID instance_id)
Get the mapping of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the mapping string. Returns NULL if no mapping is available. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepads
SDL_GetGamepadMapping
{
    char *result = NULL;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMapping(instance_id, true);
        if (mapping) {
            char pchGUID[33];
            SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
            SDL_GUIDToString(guid, pchGUID, sizeof(pchGUID));
            SDL_asprintf(&result, "%s,%s,%s", pchGUID, mapping->name, mapping->mapping);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_asprintf(), SDL_GetJoystickGUIDForID(), SDL_GUIDToString(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), and SDL_UnlockJoysticks().
SDL_GetGamepadMappings()
char ** SDL_GetGamepadMappings (int * count)
Get the current gamepad mappings.
Parameters
count a pointer filled in with the number of mappings returned, can be NULL.
Returns
an array of the mapping strings, NULL-terminated, or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    int num_mappings = 0;
    char **result = NULL;
    char **mappings = NULL;
    if (count) {
        *count = 0;
    }
    SDL_LockJoysticks();
    for (GamepadMapping_t *mapping = s_pSupportedGamepads; mapping; mapping = mapping->next) {
        if (SDL_memcmp(&mapping->guid, &s_zeroGUID, sizeof(mapping->guid)) == 0) {
            continue;
        }
        num_mappings++;
    }
    size_t final_allocation = sizeof (char *);  // for the NULL terminator element.
    bool failed = false;
    mappings = (char **) SDL_calloc(num_mappings + 1, sizeof (char *));
    if (!mappings) {
        failed = true;
    } else {
        int i = 0;
        for (GamepadMapping_t *mapping = s_pSupportedGamepads; mapping; mapping = mapping->next) {
            if (SDL_memcmp(&mapping->guid, &s_zeroGUID, sizeof(mapping->guid)) == 0) {
                continue;
            }
            char *mappingstr = CreateMappingString(mapping, mapping->guid);
            if (!mappingstr) {
                failed = true;
                break;  // error string is already set.
            }
            SDL_assert(i < num_mappings);
            mappings[i++] = mappingstr;
            final_allocation += SDL_strlen(mappingstr) + 1 + sizeof (char *);
        }
    }
    SDL_UnlockJoysticks();
    if (!failed) {
        result = (char **) SDL_malloc(final_allocation);
        if (result) {
            final_allocation -= (sizeof (char *) * num_mappings + 1);
            char *strptr = (char *) (result + (num_mappings + 1));
            for (int i = 0; i < num_mappings; i++) {
                result[i] = strptr;
                const size_t slen = SDL_strlcpy(strptr, mappings[i], final_allocation) + 1;
                SDL_assert(final_allocation >= slen);
                final_allocation -= slen;
                strptr += slen;
            }
            result[num_mappings] = NULL;
            if (count) {
                *count = num_mappings;
            }
        }
    }
    if (mappings) {
        for (int i = 0; i < num_mappings; i++) {
            SDL_free(mappings[i]);
        }
        SDL_free(mappings);
    }
    return result;
}
References count, CreateMappingString(), NULL, s_zeroGUID, SDL_assert, SDL_calloc(), SDL_free(), SDL_LockJoysticks(), SDL_malloc(), SDL_memcmp(), SDL_strlcpy(), SDL_strlen(), and SDL_UnlockJoysticks().
SDL_GetGamepadName()
const char * SDL_GetGamepadName (SDL_Gamepad * gamepad)
Get the implementation-dependent name for an opened gamepad.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
the implementation dependent name for the gamepad, or NULL if there is no name or the identifier passed is invalid.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadNameForID
{
    const char *result = NULL;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, NULL);
        if (SDL_strcmp(gamepad->name, "*") == 0 ||
            gamepad->joystick->steam_handle != 0) {
            result = SDL_GetJoystickName(gamepad->joystick);
        } else {
            result = SDL_GetPersistentString(gamepad->name);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_GAMEPAD_MAGIC, NULL, SDL_GetJoystickName(), SDL_GetPersistentString(), SDL_LockJoysticks(), SDL_strcmp(), and SDL_UnlockJoysticks().
SDL_GetGamepadNameForID()
const char * SDL_GetGamepadNameForID (SDL_JoystickID instance_id)
Get the implementation dependent name of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the name of the selected gamepad. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadName
SDL_GetGamepads
{
    const char *result = NULL;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMapping(instance_id, true);
        if (mapping) {
            if (SDL_strcmp(mapping->name, "*") == 0) {
                result = SDL_GetJoystickNameForID(instance_id);
            } else {
                result = SDL_GetPersistentString(mapping->name);
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_GetJoystickNameForID(), SDL_GetPersistentString(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), SDL_strcmp(), and SDL_UnlockJoysticks().
SDL_GetGamepadPath()
const char * SDL_GetGamepadPath (SDL_Gamepad * gamepad)
Get the implementation-dependent path for an opened gamepad.
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
the implementation dependent path for the gamepad, or NULL if there is no path or the identifier passed is invalid.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPathForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return NULL;
    }
    return SDL_GetJoystickPath(joystick);
}
References NULL, SDL_GetGamepadJoystick(), and SDL_GetJoystickPath().
SDL_GetGamepadPathForID()
const char * SDL_GetGamepadPathForID (SDL_JoystickID instance_id)
Get the implementation dependent path of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the path of the selected gamepad. If no path can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPath
SDL_GetGamepads
{
    return SDL_GetJoystickPathForID(instance_id);
}
References SDL_GetJoystickPathForID().
SDL_GetGamepadPlayerIndex()
int SDL_GetGamepadPlayerIndex (SDL_Gamepad * gamepad)
Get the player index of an opened gamepad.
For XInput gamepads this returns the XInput user index.
Parameters
gamepad the gamepad object to query.
Returns
the player index for gamepad, or -1 if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetGamepadPlayerIndex
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return -1;
    }
    return SDL_GetJoystickPlayerIndex(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickPlayerIndex().
SDL_GetGamepadPlayerIndexForID()
int SDL_GetGamepadPlayerIndexForID (SDL_JoystickID instance_id)
Get the player index of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the player index of a gamepad, or -1 if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadPlayerIndex
SDL_GetGamepads
{
    return SDL_GetJoystickPlayerIndexForID(instance_id);
}
References SDL_GetJoystickPlayerIndexForID().
SDL_GetGamepadPowerInfo()
SDL_PowerState SDL_GetGamepadPowerInfo (SDL_Gamepad * gamepad, int * percent)
Get the battery state of a gamepad.
You should never take a battery status as absolute truth. Batteries (especially failing batteries) are delicate hardware, and the values reported here are best estimates based on what that hardware reports. It's not uncommon for older batteries to lose stored power much faster than it reports, or completely drain when reporting it has 20 percent left, etc.
Parameters
gamepad the gamepad object to query.
percent a pointer filled in with the percentage of battery life left, between 0 and 100, or NULL to ignore. This will be filled in with -1 we can't determine a value or there is no battery.
Returns
the current battery state.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (percent) {
        *percent = -1;
    }
    if (!joystick) {
        return SDL_POWERSTATE_ERROR;
    }
    return SDL_GetJoystickPowerInfo(joystick, percent);
}
References SDL_GetGamepadJoystick(), SDL_GetJoystickPowerInfo(), and SDL_POWERSTATE_ERROR.
SDL_GetGamepadProduct()
Uint16 SDL_GetGamepadProduct (SDL_Gamepad * gamepad)
Get the USB product ID of an opened gamepad, if available.
If the product ID isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the USB product ID, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProductForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickProduct(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickProduct().
SDL_GetGamepadProductForID()
Uint16 SDL_GetGamepadProductForID (SDL_JoystickID instance_id)
Get the USB product ID of a gamepad, if available.
This can be called before any gamepads are opened. If the product ID isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the USB product ID of the selected gamepad. If called on an invalid index, this function returns zero.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProduct
SDL_GetGamepads
{
    return SDL_GetJoystickProductForID(instance_id);
}
References SDL_GetJoystickProductForID().
SDL_GetGamepadProductVersion()
Uint16 SDL_GetGamepadProductVersion (SDL_Gamepad * gamepad)
Get the product version of an opened gamepad, if available.
If the product version isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the USB product version, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProductVersionForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickProductVersion(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickProductVersion().
SDL_GetGamepadProductVersionForID()
Uint16 SDL_GetGamepadProductVersionForID (SDL_JoystickID instance_id)
Get the product version of a gamepad, if available.
This can be called before any gamepads are opened. If the product version isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the product version of the selected gamepad. If called on an invalid index, this function returns zero.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadProductVersion
SDL_GetGamepads
{
    return SDL_GetJoystickProductVersionForID(instance_id);
}
References SDL_GetJoystickProductVersionForID().
SDL_GetGamepadProperties()
SDL_PropertiesID SDL_GetGamepadProperties (SDL_Gamepad * gamepad)
Get the properties associated with an opened gamepad.
These properties are shared with the underlying joystick object.
The following read-only properties are provided by SDL:
SDL_PROP_GAMEPAD_CAP_MONO_LED_BOOLEAN: true if this gamepad has an LED that has adjustable brightness
SDL_PROP_GAMEPAD_CAP_RGB_LED_BOOLEAN: true if this gamepad has an LED that has adjustable color
SDL_PROP_GAMEPAD_CAP_PLAYER_LED_BOOLEAN: true if this gamepad has a player LED
SDL_PROP_GAMEPAD_CAP_RUMBLE_BOOLEAN: true if this gamepad has left/right rumble
SDL_PROP_GAMEPAD_CAP_TRIGGER_RUMBLE_BOOLEAN: true if this gamepad has simple trigger rumble
Parameters
gamepad a gamepad identifier previously returned by SDL_OpenGamepad().
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID result = 0;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, 0);
        result = SDL_GetJoystickProperties(gamepad->joystick);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_GAMEPAD_MAGIC, SDL_GetJoystickProperties(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepads()
SDL_JoystickID * SDL_GetGamepads (int * count)
Get a list of currently connected gamepads.
Parameters
count a pointer filled in with the number of gamepads returned, may be NULL.
Returns
a 0 terminated array of joystick instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasGamepad
SDL_OpenGamepad
{
    int num_joysticks = 0;
    int num_gamepads = 0;
    SDL_JoystickID *joysticks = SDL_GetJoysticks(&num_joysticks);
    if (joysticks) {
        int i;
        for (i = num_joysticks - 1; i >= 0; --i) {
            if (SDL_IsGamepad(joysticks[i])) {
                ++num_gamepads;
            } else {
                SDL_memmove(&joysticks[i], &joysticks[i+1], (num_gamepads + 1) * sizeof(joysticks[i]));
            }
        }
    }
    if (count) {
        *count = num_gamepads;
    }
    return joysticks;
}
References count, SDL_GetJoysticks(), SDL_IsGamepad(), and SDL_memmove.
SDL_GetGamepadSensorData()
bool SDL_GetGamepadSensorData (SDL_Gamepad * gamepad, SDL_SensorType type, float * data, int num_values)
Get the current state of a gamepad sensor.
The number of values and interpretation of the data is sensor dependent. See SDL_sensor.h for the details for each type of sensor.
Parameters
gamepad the gamepad to query.
type the type of sensor to query.
data a pointer filled with the current sensor state.
num_values the number of values to write to data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                SDL_JoystickSensorInfo *sensor = &joystick->sensors[i];
                if (sensor->type == type) {
                    num_values = SDL_min(num_values, SDL_arraysize(sensor->data));
                    SDL_memcpy(data, sensor->data, num_values * sizeof(*data));
                    SDL_UnlockJoysticks();
                    return true;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return SDL_Unsupported();
}
References SDL_JoystickSensorInfo::data, SDL_arraysize, SDL_GetGamepadJoystick(), SDL_LockJoysticks(), SDL_memcpy, SDL_min, SDL_UnlockJoysticks(), SDL_Unsupported, and SDL_JoystickSensorInfo::type.
SDL_GetGamepadSensorDataRate()
float SDL_GetGamepadSensorDataRate (SDL_Gamepad * gamepad, SDL_SensorType type)
Get the data rate (number of events per second) of a gamepad sensor.
Parameters
gamepad the gamepad to query.
type the type of sensor to query.
Returns
the data rate, or 0.0f if the data rate is not available.
Since
This function is available since SDL 3.2.0.
{
    float result = 0.0f;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                SDL_JoystickSensorInfo *sensor = &joystick->sensors[i];
                if (sensor->type == type) {
                    result = sensor->rate;
                    break;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_JoystickSensorInfo::rate, SDL_GetGamepadJoystick(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_JoystickSensorInfo::type.
SDL_GetGamepadSerial()
const char * SDL_GetGamepadSerial (SDL_Gamepad * gamepad)
Get the serial number of an opened gamepad, if available.
Returns the serial number of the gamepad, or NULL if it is not available.
Parameters
gamepad the gamepad object to query.
Returns
the serial number, or NULL if unavailable.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return NULL;
    }
    return SDL_GetJoystickSerial(joystick);
}
References NULL, SDL_GetGamepadJoystick(), and SDL_GetJoystickSerial().
SDL_GetGamepadSteamHandle()
Uint64 SDL_GetGamepadSteamHandle (SDL_Gamepad * gamepad)
Get the Steam Input handle of an opened gamepad, if available.
Returns an InputHandle_t for the gamepad that can be used with Steam Input API: https://partner.steamgames.com/doc/api/ISteamInput
Parameters
gamepad the gamepad object to query.
Returns
the gamepad handle, or 0 if unavailable.
Since
This function is available since SDL 3.2.0.
{
    Uint64 handle = 0;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, 0);
        handle = gamepad->joystick->steam_handle;
    }
    SDL_UnlockJoysticks();
    return handle;
}
References CHECK_GAMEPAD_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetGamepadStringForAxis()
const char * SDL_GetGamepadStringForAxis (SDL_GamepadAxis axis)
Convert from an SDL_GamepadAxis enum to a string.
Parameters
axis an enum value for a given SDL_GamepadAxis.
Returns
a string for the given axis, or NULL if an invalid axis is specified. The string returned is of the format used by SDL_Gamepad mapping strings.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadAxisFromString
{
    if (axis > SDL_GAMEPAD_AXIS_INVALID && axis < SDL_GAMEPAD_AXIS_COUNT) {
        return map_StringForGamepadAxis[axis];
    }
    return NULL;
}
References map_StringForGamepadAxis, NULL, SDL_GAMEPAD_AXIS_COUNT, and SDL_GAMEPAD_AXIS_INVALID.
SDL_GetGamepadStringForButton()
const char * SDL_GetGamepadStringForButton (SDL_GamepadButton button)
Convert from an SDL_GamepadButton enum to a string.
Parameters
button an enum value for a given SDL_GamepadButton.
Returns
a string for the given button, or NULL if an invalid button is specified. The string returned is of the format used by SDL_Gamepad mapping strings.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadButtonFromString
{
    if (button > SDL_GAMEPAD_BUTTON_INVALID && button < SDL_GAMEPAD_BUTTON_COUNT) {
        return map_StringForGamepadButton[button];
    }
    return NULL;
}
References map_StringForGamepadButton, NULL, SDL_GAMEPAD_BUTTON_COUNT, and SDL_GAMEPAD_BUTTON_INVALID.
SDL_GetGamepadStringForType()
const char * SDL_GetGamepadStringForType (SDL_GamepadType type)
Convert from an SDL_GamepadType enum to a string.
Parameters
type an enum value for a given SDL_GamepadType.
Returns
a string for the given type, or NULL if an invalid type is specified. The string returned is of the format used by SDL_Gamepad mapping strings.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadTypeFromString
{
    if (type >= SDL_GAMEPAD_TYPE_STANDARD && type < SDL_GAMEPAD_TYPE_COUNT) {
        return map_StringForGamepadType[type];
    }
    return NULL;
}
References map_StringForGamepadType, NULL, SDL_GAMEPAD_TYPE_COUNT, and SDL_GAMEPAD_TYPE_STANDARD.
SDL_GetGamepadTouchpadFinger()
bool SDL_GetGamepadTouchpadFinger (SDL_Gamepad * gamepad, int touchpad, int finger, bool * down, float * x, float * y, float * pressure)
Get the current state of a finger on a touchpad on a gamepad.
{
    bool result = false;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            if (touchpad >= 0 && touchpad < joystick->ntouchpads) {
                SDL_JoystickTouchpadInfo *touchpad_info = &joystick->touchpads[touchpad];
                if (finger >= 0 && finger < touchpad_info->nfingers) {
                    SDL_JoystickTouchpadFingerInfo *info = &touchpad_info->fingers[finger];
                    if (down) {
                        *down = info->down;
                    }
                    if (x) {
                        *x = info->x;
                    }
                    if (y) {
                        *y = info->y;
                    }
                    if (pressure) {
                        *pressure = info->pressure;
                    }
                    result = true;
                } else {
                    result = SDL_InvalidParamError("finger");
                }
            } else {
                result = SDL_InvalidParamError("touchpad");
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_JoystickTouchpadFingerInfo::down, SDL_JoystickTouchpadInfo::fingers, SDL_JoystickTouchpadFingerInfo::pressure, SDL_GetGamepadJoystick(), SDL_InvalidParamError, SDL_LockJoysticks(), SDL_UnlockJoysticks(), SDL_JoystickTouchpadFingerInfo::x, and SDL_JoystickTouchpadFingerInfo::y.
SDL_GetGamepadType()
SDL_GamepadType SDL_GetGamepadType (SDL_Gamepad * gamepad)
Get the type of an opened gamepad.
Parameters
gamepad the gamepad object to query.
Returns
the gamepad type, or SDL_GAMEPAD_TYPE_UNKNOWN if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadTypeForID
{
    SDL_GamepadType type;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    {
        CHECK_GAMEPAD_MAGIC(gamepad, SDL_GAMEPAD_TYPE_UNKNOWN);
        info = SDL_GetJoystickVirtualGamepadInfoForID(gamepad->joystick->instance_id);
        if (info) {
            type = info->type;
        } else {
            type = gamepad->type;
        }
    }
    SDL_UnlockJoysticks();
    return type;
}
References CHECK_GAMEPAD_MAGIC, SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_SteamVirtualGamepadInfo::type.
SDL_GetGamepadTypeForID()
SDL_GamepadType SDL_GetGamepadTypeForID (SDL_JoystickID instance_id)
Get the type of a gamepad.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the gamepad type.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadType
SDL_GetGamepads
SDL_GetRealGamepadTypeForID
{
    SDL_GamepadType type = SDL_GAMEPAD_TYPE_UNKNOWN;
    SDL_LockJoysticks();
    {
        GamepadMapping_t *mapping = SDL_PrivateGetGamepadMapping(instance_id, true);
        if (mapping) {
            char *type_string, *comma;
            type_string = SDL_strstr(mapping->mapping, SDL_GAMEPAD_TYPE_FIELD);
            if (type_string) {
                type_string += SDL_GAMEPAD_TYPE_FIELD_SIZE;
                comma = SDL_strchr(type_string, ',');
                if (comma) {
                    *comma = '\0';
                    type = SDL_GetGamepadTypeFromString(type_string);
                    *comma = ',';
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    if (type != SDL_GAMEPAD_TYPE_UNKNOWN) {
        return type;
    }
    return SDL_GetRealGamepadTypeForID(instance_id);
}
References SDL_GAMEPAD_TYPE_FIELD, SDL_GAMEPAD_TYPE_FIELD_SIZE, SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetGamepadTypeFromString(), SDL_GetRealGamepadTypeForID(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), SDL_strchr(), SDL_strstr(), and SDL_UnlockJoysticks().
SDL_GetGamepadTypeFromString()
SDL_GamepadType SDL_GetGamepadTypeFromString (const char * str)
Convert a string into SDL_GamepadType enum.
This function is called internally to translate SDL_Gamepad mapping strings for the underlying joystick device into the consistent SDL_Gamepad mapping. You do not normally need to call this function unless you are parsing SDL_Gamepad mappings in your own code.
Parameters
str string representing a SDL_GamepadType type.
Returns
the SDL_GamepadType enum corresponding to the input string, or SDL_GAMEPAD_TYPE_UNKNOWN if no match was found.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadStringForType
{
    int i;
    if (!str || str[0] == '\0') {
        return SDL_GAMEPAD_TYPE_UNKNOWN;
    }
    if (*str == '+' || *str == '-') {
        ++str;
    }
    for (i = 0; i < SDL_arraysize(map_StringForGamepadType); ++i) {
        if (SDL_strcasecmp(str, map_StringForGamepadType[i]) == 0) {
            return (SDL_GamepadType)i;
        }
    }
    return SDL_GAMEPAD_TYPE_UNKNOWN;
}
References map_StringForGamepadType, SDL_arraysize, SDL_GAMEPAD_TYPE_UNKNOWN, and SDL_strcasecmp().
Referenced by SDL_GetGamepadTypeForID(), SDL_UpdateGamepadType(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_GetGamepadVendor()
Uint16 SDL_GetGamepadVendor (SDL_Gamepad * gamepad)
Get the USB vendor ID of an opened gamepad, if available.
If the vendor ID isn't available this function returns 0.
Parameters
gamepad the gamepad object to query.
Returns
the USB vendor ID, or zero if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadVendorForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return 0;
    }
    return SDL_GetJoystickVendor(joystick);
}
References SDL_GetGamepadJoystick(), and SDL_GetJoystickVendor().
SDL_GetGamepadVendorForID()
Uint16 SDL_GetGamepadVendorForID (SDL_JoystickID instance_id)
Get the USB vendor ID of a gamepad, if available.
This can be called before any gamepads are opened. If the vendor ID isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the USB vendor ID of the selected gamepad. If called on an invalid index, this function returns zero.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadVendor
SDL_GetGamepads
{
    return SDL_GetJoystickVendorForID(instance_id);
}
References SDL_GetJoystickVendorForID().
SDL_GetNumGamepadTouchpadFingers()
int SDL_GetNumGamepadTouchpadFingers (SDL_Gamepad * gamepad, int touchpad)
Get the number of supported simultaneous fingers on a touchpad on a gamepad.
{
    int result = 0;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            if (touchpad >= 0 && touchpad < joystick->ntouchpads) {
                result = joystick->touchpads[touchpad].nfingers;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetNumGamepadTouchpads()
int SDL_GetNumGamepadTouchpads (SDL_Gamepad * gamepad)
Get the number of touchpads on a gamepad.
{
    int result = 0;
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            result = joystick->ntouchpads;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetGamepadJoystick(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetRealGamepadType()
SDL_GamepadType SDL_GetRealGamepadType (SDL_Gamepad * gamepad)
Get the type of an opened gamepad, ignoring any mapping override.
Parameters
gamepad the gamepad object to query.
Returns
the gamepad type, or SDL_GAMEPAD_TYPE_UNKNOWN if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRealGamepadTypeForID
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return SDL_GAMEPAD_TYPE_UNKNOWN;
    }
    return SDL_GetGamepadTypeFromGUID(SDL_GetJoystickGUID(joystick), SDL_GetJoystickName(joystick));
}
References SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetGamepadJoystick(), SDL_GetGamepadTypeFromGUID(), SDL_GetJoystickGUID(), and SDL_GetJoystickName().
SDL_GetRealGamepadTypeForID()
SDL_GamepadType SDL_GetRealGamepadTypeForID (SDL_JoystickID instance_id)
Get the type of a gamepad, ignoring any mapping override.
This can be called before any gamepads are opened.
Parameters
instance_id the joystick instance ID.
Returns
the gamepad type.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepadTypeForID
SDL_GetGamepads
SDL_GetRealGamepadType
{
    SDL_GamepadType type = SDL_GAMEPAD_TYPE_UNKNOWN;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    {
        info = SDL_GetJoystickVirtualGamepadInfoForID(instance_id);
        if (info) {
            type = info->type;
        } else {
            type = SDL_GetGamepadTypeFromGUID(SDL_GetJoystickGUIDForID(instance_id), SDL_GetJoystickNameForID(instance_id));
        }
    }
    SDL_UnlockJoysticks();
    return type;
}
References SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetGamepadTypeFromGUID(), SDL_GetJoystickGUIDForID(), SDL_GetJoystickNameForID(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_SteamVirtualGamepadInfo::type.
Referenced by SDL_GetGamepadTypeForID(), and SDL_UpdateGamepadType().
SDL_GUARDED_BY()
SDL_HashTable *s_gamepadInstanceIDs SDL_GUARDED_BY (SDL_joystick_lock) = NULL static
References NULL, and SDL_joystick_lock.
SDL_HasGamepad()
bool SDL_HasGamepad (void)
Return whether a gamepad is currently connected.
Returns
true if a gamepad is connected, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGamepads
{
    int num_joysticks = 0;
    int num_gamepads = 0;
    SDL_JoystickID *joysticks = SDL_GetJoysticks(&num_joysticks);
    if (joysticks) {
        int i;
        for (i = num_joysticks - 1; i >= 0 && num_gamepads == 0; --i) {
            if (SDL_IsGamepad(joysticks[i])) {
                ++num_gamepads;
            }
        }
        SDL_free(joysticks);
    }
    if (num_gamepads > 0) {
        return true;
    }
    return false;
}
References SDL_free(), SDL_GetJoysticks(), and SDL_IsGamepad().
SDL_InitGamepadMappings()
bool SDL_InitGamepadMappings (void)
{
    char szGamepadMapPath[1024];
    int i = 0;
    const char *pMappingString = NULL;
    SDL_AssertJoysticksLocked();
    PushMappingChangeTracking();
    pMappingString = s_GamepadMappings[i];
    while (pMappingString) {
        SDL_PrivateAddGamepadMapping(pMappingString, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT);
        i++;
        pMappingString = s_GamepadMappings[i];
    }
    if (SDL_GetGamepadMappingFilePath(szGamepadMapPath, sizeof(szGamepadMapPath))) {
        SDL_AddGamepadMappingsFromFile(szGamepadMapPath);
    }
    // load in any user supplied config
    SDL_LoadGamepadHints();
    SDL_LoadVIDPIDList(&SDL_allowed_gamepads);
    SDL_LoadVIDPIDList(&SDL_ignored_gamepads);
    PopMappingChangeTracking();
    return true;
}
References NULL, PopMappingChangeTracking(), PushMappingChangeTracking(), s_GamepadMappings, SDL_AddGamepadMappingsFromFile(), SDL_allowed_gamepads, SDL_AssertJoysticksLocked(), SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT, SDL_GetGamepadMappingFilePath(), SDL_ignored_gamepads, SDL_LoadGamepadHints(), SDL_LoadVIDPIDList(), and SDL_PrivateAddGamepadMapping().
Referenced by SDL_InitJoysticks(), and SDL_ReloadGamepadMappings().
SDL_InitGamepads()
bool SDL_InitGamepads (void)
{
    int i;
    SDL_JoystickID *joysticks;
    SDL_gamepads_initialized = true;
    // Watch for joystick events and fire gamepad ones if needed
    SDL_AddEventWatch(SDL_GamepadEventWatcher, NULL);
    // Send added events for gamepads currently attached
    joysticks = SDL_GetJoysticks(NULL);
    if (joysticks) {
        for (i = 0; joysticks[i]; ++i) {
            if (SDL_IsGamepad(joysticks[i])) {
                SDL_PrivateGamepadAdded(joysticks[i]);
            }
        }
        SDL_free(joysticks);
    }
    return true;
}
References NULL, SDL_AddEventWatch(), SDL_free(), SDL_GamepadEventWatcher(), SDL_gamepads_initialized, SDL_GetJoysticks(), SDL_IsGamepad(), and SDL_PrivateGamepadAdded().
Referenced by SDL_InitSubSystem().
SDL_IsGamepad()
bool SDL_IsGamepad (SDL_JoystickID instance_id)
Check if the given joystick is supported by the gamepad interface.
Parameters
instance_id the joystick instance ID.
Returns
true if the given joystick is supported by the gamepad interface, false if it isn't or it's an invalid index.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoysticks
SDL_OpenGamepad
{
    bool result;
    SDL_LockJoysticks();
    {
        const void *value;
        if (SDL_FindInHashTable(s_gamepadInstanceIDs, (void *)(uintptr_t)instance_id, &value)) {
            result = (bool)(uintptr_t)value;
        } else {
            if (SDL_PrivateGetGamepadMapping(instance_id, true) != NULL) {
                result = true;
            } else {
                result = false;
            }
            if (!s_gamepadInstanceIDs) {
                s_gamepadInstanceIDs = SDL_CreateHashTable(0, false, SDL_HashID, SDL_KeyMatchID, NULL, NULL);
            }
            SDL_InsertIntoHashTable(s_gamepadInstanceIDs, (void *)(uintptr_t)instance_id, (void *)(uintptr_t)result, true);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References bool, NULL, SDL_CreateHashTable(), SDL_FindInHashTable(), SDL_HashID(), SDL_InsertIntoHashTable(), SDL_KeyMatchID(), SDL_LockJoysticks(), SDL_PrivateGetGamepadMapping(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepads(), SDL_GetJoystickType(), SDL_GetJoystickTypeForID(), SDL_HasGamepad(), SDL_InitGamepads(), SDL_IsJoystickHaptic(), SDL_PrivateJoystickAdded(), SDL_PrivateJoystickRemoved(), SendSteamHandleUpdateEvents(), and ShouldAttemptSensorFusion().
SDL_IsGamepadNameAndGUID()
bool SDL_IsGamepadNameAndGUID (const char * name, SDL_GUID guid)
{
    bool result;
    SDL_LockJoysticks();
    {
        if (s_pDefaultMapping || SDL_PrivateGetGamepadMappingForNameAndGUID(name, guid) != NULL) {
            result = true;
        } else {
            result = false;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, SDL_LockJoysticks(), SDL_PrivateGetGamepadMappingForNameAndGUID(), and SDL_UnlockJoysticks().
SDL_LoadGamepadHints()
void SDL_LoadGamepadHints (void) static
{
    const char *hint = SDL_GetHint(SDL_HINT_GAMECONTROLLERCONFIG);
    if (hint && hint[0]) {
        char *pTempMappings = SDL_strdup(hint);
        char *pUserMappings = pTempMappings;
        PushMappingChangeTracking();
        while (pUserMappings) {
            char *pchNewLine = NULL;
            pchNewLine = SDL_strchr(pUserMappings, '\n');
            if (pchNewLine) {
                *pchNewLine = '\0';
            }
            SDL_PrivateAddGamepadMapping(pUserMappings, SDL_GAMEPAD_MAPPING_PRIORITY_USER);
            if (pchNewLine) {
                pUserMappings = pchNewLine + 1;
            } else {
                pUserMappings = NULL;
            }
        }
        PopMappingChangeTracking();
        SDL_free(pTempMappings);
    }
}
References NULL, PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_free(), SDL_GAMEPAD_MAPPING_PRIORITY_USER, SDL_GetHint(), SDL_HINT_GAMECONTROLLERCONFIG, SDL_PrivateAddGamepadMapping(), SDL_strchr(), and SDL_strdup().
Referenced by SDL_InitGamepadMappings().
SDL_OpenGamepad()
SDL_Gamepad * SDL_OpenGamepad (SDL_JoystickID instance_id)
Open a gamepad for use.
Parameters
instance_id the joystick instance ID.
Returns
a gamepad identifier or NULL if an error occurred; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseGamepad
SDL_IsGamepad
{
    SDL_Gamepad *gamepad;
    SDL_Gamepad *gamepadlist;
    GamepadMapping_t *pSupportedGamepad = NULL;
    SDL_LockJoysticks();
    gamepadlist = SDL_gamepads;
    // If the gamepad is already open, return it
    while (gamepadlist) {
        if (instance_id == gamepadlist->joystick->instance_id) {
            gamepad = gamepadlist;
            ++gamepad->ref_count;
            SDL_UnlockJoysticks();
            return gamepad;
        }
        gamepadlist = gamepadlist->next;
    }
    // Find a gamepad mapping
    pSupportedGamepad = SDL_PrivateGetGamepadMapping(instance_id, true);
    if (!pSupportedGamepad) {
        SDL_SetError("Couldn't find mapping for device (%" SDL_PRIu32 ")", instance_id);
        SDL_UnlockJoysticks();
        return NULL;
    }
    // Create and initialize the gamepad
    gamepad = (SDL_Gamepad *)SDL_calloc(1, sizeof(*gamepad));
    if (!gamepad) {
        SDL_UnlockJoysticks();
        return NULL;
    }
    SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, true);
    gamepad->joystick = SDL_OpenJoystick(instance_id);
    if (!gamepad->joystick) {
        SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
        SDL_free(gamepad);
        SDL_UnlockJoysticks();
        return NULL;
    }
    if (gamepad->joystick->naxes) {
        gamepad->last_match_axis = (SDL_GamepadBinding **)SDL_calloc(gamepad->joystick->naxes, sizeof(*gamepad->last_match_axis));
        if (!gamepad->last_match_axis) {
            SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
            SDL_CloseJoystick(gamepad->joystick);
            SDL_free(gamepad);
            SDL_UnlockJoysticks();
            return NULL;
        }
    }
    if (gamepad->joystick->nhats) {
        gamepad->last_hat_mask = (Uint8 *)SDL_calloc(gamepad->joystick->nhats, sizeof(*gamepad->last_hat_mask));
        if (!gamepad->last_hat_mask) {
            SDL_SetObjectValid(gamepad, SDL_OBJECT_TYPE_GAMEPAD, false);
            SDL_CloseJoystick(gamepad->joystick);
            SDL_free(gamepad->last_match_axis);
            SDL_free(gamepad);
            SDL_UnlockJoysticks();
            return NULL;
        }
    }
    SDL_PrivateLoadButtonMapping(gamepad, pSupportedGamepad);
    // Add the gamepad to list
    ++gamepad->ref_count;
    // Link the gamepad in the list
    gamepad->next = SDL_gamepads;
    SDL_gamepads = gamepad;
    SDL_UnlockJoysticks();
    return gamepad;
}
References NULL, SDL_calloc(), SDL_CloseJoystick(), SDL_free(), SDL_LockJoysticks(), SDL_OBJECT_TYPE_GAMEPAD, SDL_OpenJoystick(), SDL_PRIu32, SDL_PrivateGetGamepadMapping(), SDL_PrivateLoadButtonMapping(), SDL_SetError(), SDL_SetObjectValid(), and SDL_UnlockJoysticks().
SDL_PrivateAddGamepadMapping()
int SDL_PrivateAddGamepadMapping (const char * mappingString, SDL_GamepadMappingPriority priority) static
{
    char *appended = NULL;
    char *remapped = NULL;
    char *pchGUID;
    SDL_GUID guid;
    Uint16 vendor, product;
    bool is_default_mapping = false;
    bool is_xinput_mapping = false;
    bool existing = false;
    GamepadMapping_t *pGamepadMapping;
    int result = -1;
    SDL_AssertJoysticksLocked();
    if (!mappingString) {
        SDL_InvalidParamError("mappingString");
        return -1;
    }
    pchGUID = SDL_PrivateGetGamepadGUIDFromMappingString(mappingString);
    if (!pchGUID) {
        SDL_SetError("Couldn't parse GUID from %s", mappingString);
        return -1;
    }
    if (!SDL_strcasecmp(pchGUID, "default")) {
        is_default_mapping = true;
    } else if (!SDL_strcasecmp(pchGUID, "xinput")) {
        is_xinput_mapping = true;
    }
    guid = SDL_StringToGUID(pchGUID);
    SDL_free(pchGUID);
    SDL_GetJoystickGUIDInfo(guid, &vendor, &product, NULL, NULL);
    if (SDL_IsJoystickGameCube(vendor, product) &&
        SDL_strstr(mappingString, "SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS") == NULL) {
        SDL_asprintf(&appended, "%shint:SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS:=1,", mappingString);
        if (appended) {
            mappingString = appended;
        }
    }
    { // Extract and verify the hint field
        const char *tmp;
        tmp = SDL_strstr(mappingString, SDL_GAMEPAD_HINT_FIELD);
        if (tmp) {
            bool default_value, value, negate;
            int len;
            char hint[128];
            tmp += SDL_GAMEPAD_HINT_FIELD_SIZE;
            if (*tmp == '!') {
                negate = true;
                ++tmp;
            } else {
                negate = false;
            }
            len = 0;
            while (*tmp && *tmp != ',' && *tmp != ':' && len < (sizeof(hint) - 1)) {
                hint[len++] = *tmp++;
            }
            hint[len] = '\0';
            if (tmp[0] == ':' && tmp[1] == '=') {
                tmp += 2;
                default_value = SDL_atoi(tmp);
            } else {
                default_value = false;
            }
            if (SDL_strcmp(hint, "SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS") == 0) {
                // This hint is used to signal whether the mapping uses positional buttons or not
                if (negate) {
                    // This mapping uses positional buttons, we can use it as-is
                } else {
                    // This mapping uses labeled buttons, we need to swap them to positional
                    remapped = SDL_ConvertMappingToPositionalAXBY(mappingString);
                    if (!remapped) {
                        goto done;
                    }
                    mappingString = remapped;
                }
            } else if (SDL_strcmp(hint, "SDL_GAMECONTROLLER_USE_BUTTON_LABELS") == 0) {
                // This hint is used to signal whether the mapping uses positional buttons or not
                if (negate) {
                    // This mapping uses positional buttons, we can use it as-is
                } else {
                    // This mapping uses labeled buttons, we need to swap them to positional
                    remapped = SDL_ConvertMappingToPositionalBAXY(mappingString);
                    if (!remapped) {
                        goto done;
                    }
                    mappingString = remapped;
                }
            } else {
                value = SDL_GetHintBoolean(hint, default_value);
                if (negate) {
                    value = !value;
                }
                if (!value) {
                    result = 0;
                    goto done;
                }
            }
        }
    }
#ifdef ANDROID
    { // Extract and verify the SDK version
        const char *tmp;
        tmp = SDL_strstr(mappingString, SDL_GAMEPAD_SDKGE_FIELD);
        if (tmp) {
            tmp += SDL_GAMEPAD_SDKGE_FIELD_SIZE;
            if (!(SDL_GetAndroidSDKVersion() >= SDL_atoi(tmp))) {
                SDL_SetError("SDK version %d < minimum version %d", SDL_GetAndroidSDKVersion(), SDL_atoi(tmp));
                goto done;
            }
        }
        tmp = SDL_strstr(mappingString, SDL_GAMEPAD_SDKLE_FIELD);
        if (tmp) {
            tmp += SDL_GAMEPAD_SDKLE_FIELD_SIZE;
            if (!(SDL_GetAndroidSDKVersion() <= SDL_atoi(tmp))) {
                SDL_SetError("SDK version %d > maximum version %d", SDL_GetAndroidSDKVersion(), SDL_atoi(tmp));
                goto done;
            }
        }
    }
#endif
    pGamepadMapping = SDL_PrivateAddMappingForGUID(guid, mappingString, &existing, priority);
    if (!pGamepadMapping) {
        goto done;
    }
    if (existing) {
        result = 0;
    } else {
        if (is_default_mapping) {
            s_pDefaultMapping = pGamepadMapping;
        } else if (is_xinput_mapping) {
            s_pXInputMapping = pGamepadMapping;
        }
        result = 1;
    }
done:
    SDL_free(appended);
    SDL_free(remapped);
    return result;
}
References NULL, SDL_asprintf(), SDL_AssertJoysticksLocked(), SDL_atoi(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_free(), SDL_GAMEPAD_HINT_FIELD, SDL_GAMEPAD_HINT_FIELD_SIZE, SDL_GAMEPAD_SDKGE_FIELD, SDL_GAMEPAD_SDKGE_FIELD_SIZE, SDL_GAMEPAD_SDKLE_FIELD, SDL_GAMEPAD_SDKLE_FIELD_SIZE, SDL_GetAndroidSDKVersion(), SDL_GetHintBoolean(), SDL_GetJoystickGUIDInfo(), SDL_InvalidParamError, SDL_IsJoystickGameCube(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_SetError(), SDL_strcasecmp(), SDL_strcmp(), SDL_StringToGUID(), and SDL_strstr().
Referenced by SDL_AddGamepadMapping(), SDL_InitGamepadMappings(), and SDL_LoadGamepadHints().
SDL_PrivateAddMappingForGUID()
GamepadMapping_t * SDL_PrivateAddMappingForGUID (SDL_GUID jGUID, const char * mappingString, bool * existing, SDL_GamepadMappingPriority priority) static
{
    char *pchName;
    char *pchMapping;
    GamepadMapping_t *pGamepadMapping;
    Uint16 crc;
    SDL_AssertJoysticksLocked();
    pchName = SDL_PrivateGetGamepadNameFromMappingString(mappingString);
    if (!pchName) {
        SDL_SetError("Couldn't parse name from %s", mappingString);
        return NULL;
    }
    pchMapping = SDL_PrivateGetGamepadMappingFromMappingString(mappingString);
    if (!pchMapping) {
        SDL_free(pchName);
        SDL_SetError("Couldn't parse %s", mappingString);
        return NULL;
    }
    // Fix up the GUID and the mapping with the CRC, if needed
    SDL_GetJoystickGUIDInfo(jGUID, NULL, NULL, NULL, &crc);
    if (crc) {
        // Make sure the mapping has the CRC
        char *new_mapping;
        const char *optional_comma;
        size_t mapping_length;
        char *crc_end = "";
        char *crc_string = SDL_strstr(pchMapping, SDL_GAMEPAD_CRC_FIELD);
        if (crc_string) {
            crc_end = SDL_strchr(crc_string, ',');
            if (crc_end) {
                ++crc_end;
            } else {
                crc_end = "";
            }
            *crc_string = '\0';
        }
        // Make sure there's a comma before the CRC
        mapping_length = SDL_strlen(pchMapping);
        if (mapping_length == 0 || pchMapping[mapping_length - 1] == ',') {
            optional_comma = "";
        } else {
            optional_comma = ",";
        }
        if (SDL_asprintf(&new_mapping, "%s%s%s%.4x,%s", pchMapping, optional_comma, SDL_GAMEPAD_CRC_FIELD, crc, crc_end) >= 0) {
            SDL_free(pchMapping);
            pchMapping = new_mapping;
        }
    } else {
        // Make sure the GUID has the CRC, for matching purposes
        char *crc_string = SDL_strstr(pchMapping, SDL_GAMEPAD_CRC_FIELD);
        if (crc_string) {
            crc = (Uint16)SDL_strtol(crc_string + SDL_GAMEPAD_CRC_FIELD_SIZE, NULL, 16);
            if (crc) {
                SDL_SetJoystickGUIDCRC(&jGUID, crc);
            }
        }
    }
    PushMappingChangeTracking();
    pGamepadMapping = SDL_PrivateGetGamepadMappingForGUID(jGUID, true);
    if (pGamepadMapping) {
        // Only overwrite the mapping if the priority is the same or higher.
        if (pGamepadMapping->priority <= priority) {
            // Update existing mapping
            SDL_free(pGamepadMapping->name);
            pGamepadMapping->name = pchName;
            SDL_free(pGamepadMapping->mapping);
            pGamepadMapping->mapping = pchMapping;
            pGamepadMapping->priority = priority;
        } else {
            SDL_free(pchName);
            SDL_free(pchMapping);
        }
        if (existing) {
            *existing = true;
        }
        AddMappingChangeTracking(pGamepadMapping);
    } else {
        pGamepadMapping = (GamepadMapping_t *)SDL_malloc(sizeof(*pGamepadMapping));
        if (!pGamepadMapping) {
            PopMappingChangeTracking();
            SDL_free(pchName);
            SDL_free(pchMapping);
            return NULL;
        }
        // Clear the CRC, we've already added it to the mapping
        if (crc) {
            SDL_SetJoystickGUIDCRC(&jGUID, 0);
        }
        pGamepadMapping->guid = jGUID;
        pGamepadMapping->name = pchName;
        pGamepadMapping->mapping = pchMapping;
        pGamepadMapping->next = NULL;
        pGamepadMapping->priority = priority;
        if (s_pSupportedGamepads) {
            // Add the mapping to the end of the list
            GamepadMapping_t *pCurrMapping, *pPrevMapping;
            for (pPrevMapping = s_pSupportedGamepads, pCurrMapping = pPrevMapping->next;
                 pCurrMapping;
                 pPrevMapping = pCurrMapping, pCurrMapping = pCurrMapping->next) {
                // continue;
            }
            pPrevMapping->next = pGamepadMapping;
        } else {
            s_pSupportedGamepads = pGamepadMapping;
        }
        if (existing) {
            *existing = false;
        }
    }
    PopMappingChangeTracking();
    return pGamepadMapping;
}
References AddMappingChangeTracking(), NULL, PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_asprintf(), SDL_AssertJoysticksLocked(), SDL_free(), SDL_GAMEPAD_CRC_FIELD, SDL_GAMEPAD_CRC_FIELD_SIZE, SDL_GetJoystickGUIDInfo(), SDL_malloc(), SDL_PrivateGetGamepadMappingForGUID(), SDL_PrivateGetGamepadMappingFromMappingString(), SDL_PrivateGetGamepadNameFromMappingString(), SDL_SetError(), SDL_SetJoystickGUIDCRC(), SDL_strchr(), SDL_strlen(), SDL_strstr(), and SDL_strtol().
Referenced by SDL_CreateMappingForHIDAPIGamepad(), SDL_CreateMappingForRAWINPUTGamepad(), SDL_CreateMappingForWGIGamepad(), SDL_PrivateAddGamepadMapping(), SDL_PrivateGenerateAutomaticGamepadMapping(), SDL_PrivateGetGamepadMappingForNameAndGUID(), and SDL_SetGamepadMapping().
SDL_PrivateAppendToMappingString()
void SDL_PrivateAppendToMappingString (char * mapping_string, size_t mapping_string_len, const char * input_name, SDL_InputMapping * mapping) static
{
    char buffer[16];
    if (mapping->kind == EMappingKind_None) {
        return;
    }
    SDL_strlcat(mapping_string, input_name, mapping_string_len);
    SDL_strlcat(mapping_string, ":", mapping_string_len);
    switch (mapping->kind) {
    case EMappingKind_Button:
        (void)SDL_snprintf(buffer, sizeof(buffer), "b%u", mapping->target);
        break;
    case EMappingKind_Axis:
        (void)SDL_snprintf(buffer, sizeof(buffer), "%sa%u%s",
            mapping->half_axis_positive ? "+" :
            mapping->half_axis_negative ? "-" : "",
            mapping->target,
            mapping->axis_reversed ? "~" : "");
        break;
    case EMappingKind_Hat:
        (void)SDL_snprintf(buffer, sizeof(buffer), "h%i.%i", mapping->target >> 4, mapping->target & 0x0F);
        break;
    default:
        SDL_assert(false);
    }
    SDL_strlcat(mapping_string, buffer, mapping_string_len);
    SDL_strlcat(mapping_string, ",", mapping_string_len);
}
References SDL_InputMapping::axis_reversed, EMappingKind_Axis, EMappingKind_Button, EMappingKind_Hat, EMappingKind_None, SDL_InputMapping::half_axis_negative, SDL_InputMapping::half_axis_positive, SDL_InputMapping::kind, SDL_assert, SDL_snprintf(), SDL_strlcat(), SDL_InputMapping::target, and void().
Referenced by SDL_PrivateGenerateAutomaticGamepadMapping().
SDL_PrivateGamepadAdded()
void SDL_PrivateGamepadAdded (SDL_JoystickID instance_id)
{
    SDL_Event event;
    if (!SDL_gamepads_initialized || SDL_IsJoystickBeingAdded()) {
        return;
    }
    event.type = SDL_EVENT_GAMEPAD_ADDED;
    event.common.timestamp = 0;
    event.gdevice.which = instance_id;
    SDL_PushEvent(&event);
}
References SDL_EVENT_GAMEPAD_ADDED, SDL_gamepads_initialized, SDL_IsJoystickBeingAdded(), and SDL_PushEvent().
Referenced by PopMappingChangeTracking(), SDL_InitGamepads(), and SDL_PrivateJoystickAdded().
SDL_PrivateGamepadRemapped()
void SDL_PrivateGamepadRemapped (SDL_JoystickID instance_id) static
{
    SDL_Event event;
    if (!SDL_gamepads_initialized || SDL_IsJoystickBeingAdded()) {
        return;
    }
    event.type = SDL_EVENT_GAMEPAD_REMAPPED;
    event.common.timestamp = 0;
    event.gdevice.which = instance_id;
    SDL_PushEvent(&event);
}
References SDL_EVENT_GAMEPAD_REMAPPED, SDL_gamepads_initialized, SDL_IsJoystickBeingAdded(), and SDL_PushEvent().
Referenced by PopMappingChangeTracking().
SDL_PrivateGamepadRemoved()
void SDL_PrivateGamepadRemoved (SDL_JoystickID instance_id)
{
    SDL_Event event;
    SDL_Gamepad *gamepad;
    SDL_AssertJoysticksLocked();
    if (!SDL_gamepads_initialized) {
        return;
    }
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        if (gamepad->joystick->instance_id == instance_id) {
            RecenterGamepad(gamepad);
            break;
        }
    }
    event.type = SDL_EVENT_GAMEPAD_REMOVED;
    event.common.timestamp = 0;
    event.gdevice.which = instance_id;
    SDL_PushEvent(&event);
}
References RecenterGamepad(), SDL_AssertJoysticksLocked(), SDL_EVENT_GAMEPAD_REMOVED, SDL_gamepads_initialized, and SDL_PushEvent().
Referenced by PopMappingChangeTracking(), SDL_PrivateJoystickRemoved(), and SDL_QuitGamepads().
SDL_PrivateGenerateAutomaticGamepadMapping()
GamepadMapping_t * SDL_PrivateGenerateAutomaticGamepadMapping (const char * name, SDL_GUID guid, SDL_GamepadMapping * raw_map) static
{
    bool existing;
    char name_string[128];
    char mapping[1024];
    // Remove the CRC from the GUID
    // We already know that this GUID doesn't have a mapping without the CRC, and we want newly
    // added mappings without a CRC to override this mapping.
    SDL_SetJoystickGUIDCRC(&guid, 0);
    // Remove any commas in the name
    SDL_strlcpy(name_string, name, sizeof(name_string));
    {
        char *spot;
        for (spot = name_string; *spot; ++spot) {
            if (*spot == ',') {
                *spot = ' ';
            }
        }
    }
    (void)SDL_snprintf(mapping, sizeof(mapping), "none,%s,", name_string);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "a", &raw_map->a);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "b", &raw_map->b);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "x", &raw_map->x);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "y", &raw_map->y);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "back", &raw_map->back);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "guide", &raw_map->guide);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "start", &raw_map->start);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "leftstick", &raw_map->leftstick);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "rightstick", &raw_map->rightstick);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "leftshoulder", &raw_map->leftshoulder);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "rightshoulder", &raw_map->rightshoulder);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "dpup", &raw_map->dpup);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "dpdown", &raw_map->dpdown);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "dpleft", &raw_map->dpleft);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "dpright", &raw_map->dpright);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "misc1", &raw_map->misc1);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "misc2", &raw_map->misc2);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "misc3", &raw_map->misc3);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "misc4", &raw_map->misc4);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "misc5", &raw_map->misc5);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "misc6", &raw_map->misc6);
    /* Keep using paddle1-4 in the generated mapping so that it can be
     * reused with SDL2 */
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "paddle1", &raw_map->right_paddle1);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "paddle2", &raw_map->left_paddle1);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "paddle3", &raw_map->right_paddle2);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "paddle4", &raw_map->left_paddle2);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "leftx", &raw_map->leftx);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "lefty", &raw_map->lefty);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "rightx", &raw_map->rightx);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "righty", &raw_map->righty);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "lefttrigger", &raw_map->lefttrigger);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "righttrigger", &raw_map->righttrigger);
    SDL_PrivateAppendToMappingString(mapping, sizeof(mapping), "touchpad", &raw_map->touchpad);
    return SDL_PrivateAddMappingForGUID(guid, mapping, &existing, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT);
}
References SDL_GamepadMapping::a, SDL_GamepadMapping::b, SDL_GamepadMapping::back, SDL_GamepadMapping::dpdown, SDL_GamepadMapping::dpleft, SDL_GamepadMapping::dpright, SDL_GamepadMapping::dpup, SDL_GamepadMapping::guide, SDL_GamepadMapping::left_paddle1, SDL_GamepadMapping::left_paddle2, SDL_GamepadMapping::leftshoulder, SDL_GamepadMapping::leftstick, SDL_GamepadMapping::lefttrigger, SDL_GamepadMapping::leftx, SDL_GamepadMapping::lefty, SDL_GamepadMapping::misc1, SDL_GamepadMapping::misc2, SDL_GamepadMapping::misc3, SDL_GamepadMapping::misc4, SDL_GamepadMapping::misc5, SDL_GamepadMapping::misc6, SDL_GamepadMapping::right_paddle1, SDL_GamepadMapping::right_paddle2, SDL_GamepadMapping::rightshoulder, SDL_GamepadMapping::rightstick, SDL_GamepadMapping::righttrigger, SDL_GamepadMapping::rightx, SDL_GamepadMapping::righty, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT, SDL_PrivateAddMappingForGUID(), SDL_PrivateAppendToMappingString(), SDL_SetJoystickGUIDCRC(), SDL_snprintf(), SDL_strlcpy(), SDL_GamepadMapping::start, SDL_GamepadMapping::touchpad, void(), SDL_GamepadMapping::x, and SDL_GamepadMapping::y.
Referenced by SDL_PrivateGetGamepadMapping().
SDL_PrivateGetGamepadButtonFromString()
SDL_GamepadButton SDL_PrivateGetGamepadButtonFromString (const char * str, bool axby, bool baxy) static
{
    int i;
    if (!str || str[0] == '\0') {
        return SDL_GAMEPAD_BUTTON_INVALID;
    }
    for (i = 0; i < SDL_arraysize(map_StringForGamepadButton); ++i) {
        if (SDL_strcasecmp(str, map_StringForGamepadButton[i]) == 0) {
            if (axby) {
                // Need to swap face buttons
                switch (i) {
                case SDL_GAMEPAD_BUTTON_EAST:
                    return SDL_GAMEPAD_BUTTON_WEST;
                case SDL_GAMEPAD_BUTTON_WEST:
                    return SDL_GAMEPAD_BUTTON_EAST;
                default:
                    break;
                }
            } else if (baxy) {
                // Need to swap face buttons
                switch (i) {
                case SDL_GAMEPAD_BUTTON_SOUTH:
                    return SDL_GAMEPAD_BUTTON_EAST;
                case SDL_GAMEPAD_BUTTON_EAST:
                    return SDL_GAMEPAD_BUTTON_SOUTH;
                case SDL_GAMEPAD_BUTTON_WEST:
                    return SDL_GAMEPAD_BUTTON_NORTH;
                case SDL_GAMEPAD_BUTTON_NORTH:
                    return SDL_GAMEPAD_BUTTON_WEST;
                default:
                    break;
                }
            }
            return (SDL_GamepadButton)i;
        }
    }
    return SDL_GAMEPAD_BUTTON_INVALID;
}
References map_StringForGamepadButton, SDL_arraysize, SDL_GAMEPAD_BUTTON_EAST, SDL_GAMEPAD_BUTTON_INVALID, SDL_GAMEPAD_BUTTON_NORTH, SDL_GAMEPAD_BUTTON_SOUTH, SDL_GAMEPAD_BUTTON_WEST, and SDL_strcasecmp().
Referenced by SDL_GetGamepadButtonFromString(), and SDL_PrivateParseGamepadElement().
SDL_PrivateGetGamepadGUIDFromMappingString()
char * SDL_PrivateGetGamepadGUIDFromMappingString (const char * pMapping) static
{
    const char *pFirstComma = SDL_strchr(pMapping, ',');
    if (pFirstComma) {
        char *pchGUID = (char *)SDL_malloc(pFirstComma - pMapping + 1);
        if (!pchGUID) {
            return NULL;
        }
        SDL_memcpy(pchGUID, pMapping, pFirstComma - pMapping);
        pchGUID[pFirstComma - pMapping] = '\0';
        // Convert old style GUIDs to the new style in 2.0.5
#if defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
        if (SDL_strlen(pchGUID) == 32 &&
            SDL_memcmp(&pchGUID[20], "504944564944", 12) == 0) {
            SDL_memcpy(&pchGUID[20], "000000000000", 12);
            SDL_memcpy(&pchGUID[16], &pchGUID[4], 4);
            SDL_memcpy(&pchGUID[8], &pchGUID[0], 4);
            SDL_memcpy(&pchGUID[0], "03000000", 8);
        }
#elif defined(SDL_PLATFORM_MACOS)
        if (SDL_strlen(pchGUID) == 32 &&
            SDL_memcmp(&pchGUID[4], "000000000000", 12) == 0 &&
            SDL_memcmp(&pchGUID[20], "000000000000", 12) == 0) {
            SDL_memcpy(&pchGUID[20], "000000000000", 12);
            SDL_memcpy(&pchGUID[8], &pchGUID[0], 4);
            SDL_memcpy(&pchGUID[0], "03000000", 8);
        }
#endif
        return pchGUID;
    }
    return NULL;
}
References NULL, SDL_malloc(), SDL_memcmp(), SDL_memcpy, SDL_strchr(), and SDL_strlen().
Referenced by SDL_PrivateAddGamepadMapping().
SDL_PrivateGetGamepadMapping()
GamepadMapping_t * SDL_PrivateGetGamepadMapping (SDL_JoystickID instance_id, bool create_mapping) static
{
    const char *name;
    SDL_GUID guid;
    GamepadMapping_t *mapping;
    SDL_AssertJoysticksLocked();
    name = SDL_GetJoystickNameForID(instance_id);
    guid = SDL_GetJoystickGUIDForID(instance_id);
    mapping = SDL_PrivateGetGamepadMappingForNameAndGUID(name, guid);
    if (!mapping && create_mapping) {
        SDL_GamepadMapping raw_map;
        SDL_zero(raw_map);
        if (SDL_PrivateJoystickGetAutoGamepadMapping(instance_id, &raw_map)) {
            mapping = SDL_PrivateGenerateAutomaticGamepadMapping(name, guid, &raw_map);
        }
    }
    if (!mapping) {
        mapping = s_pDefaultMapping;
    }
    return mapping;
}
References SDL_AssertJoysticksLocked(), SDL_GetJoystickGUIDForID(), SDL_GetJoystickNameForID(), SDL_PrivateGenerateAutomaticGamepadMapping(), SDL_PrivateGetGamepadMappingForNameAndGUID(), SDL_PrivateJoystickGetAutoGamepadMapping(), and SDL_zero.
Referenced by PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_GetGamepadMappingForID(), SDL_GetGamepadNameForID(), SDL_GetGamepadTypeForID(), SDL_IsGamepad(), and SDL_OpenGamepad().
SDL_PrivateGetGamepadMappingForGUID()
GamepadMapping_t * SDL_PrivateGetGamepadMappingForGUID (SDL_GUID guid, bool adding_mapping) static
{
    GamepadMapping_t *mapping;
    mapping = SDL_PrivateMatchGamepadMappingForGUID(guid, true, adding_mapping);
    if (mapping) {
        return mapping;
    }
    if (adding_mapping) {
        // We didn't find an existing mapping
        return NULL;
    }
    // Try harder to get the best match, or create a mapping
    if (SDL_JoystickGUIDUsesVersion(guid)) {
        // Try again, ignoring the version
        mapping = SDL_PrivateMatchGamepadMappingForGUID(guid, false, false);
        if (mapping) {
            return mapping;
        }
    }
#ifdef SDL_JOYSTICK_XINPUT
    if (SDL_IsJoystickXInput(guid)) {
        // This is an XInput device
        return s_pXInputMapping;
    }
#endif
    if (SDL_IsJoystickHIDAPI(guid)) {
        mapping = SDL_CreateMappingForHIDAPIGamepad(guid);
    } else if (SDL_IsJoystickRAWINPUT(guid)) {
        mapping = SDL_CreateMappingForRAWINPUTGamepad(guid);
    } else if (SDL_IsJoystickWGI(guid)) {
        mapping = SDL_CreateMappingForWGIGamepad(guid);
    } else if (SDL_IsJoystickVIRTUAL(guid)) {
        // We'll pick up a robust mapping in VIRTUAL_JoystickGetGamepadMapping
#ifdef SDL_PLATFORM_ANDROID
    } else {
        mapping = SDL_CreateMappingForAndroidGamepad(guid);
#endif
    }
    return mapping;
}
References NULL, SDL_CreateMappingForHIDAPIGamepad(), SDL_CreateMappingForRAWINPUTGamepad(), SDL_CreateMappingForWGIGamepad(), SDL_IsJoystickHIDAPI(), SDL_IsJoystickRAWINPUT(), SDL_IsJoystickVIRTUAL(), SDL_IsJoystickWGI(), SDL_IsJoystickXInput(), SDL_JoystickGUIDUsesVersion(), and SDL_PrivateMatchGamepadMappingForGUID().
Referenced by SDL_GetGamepadMappingForGUID(), SDL_PrivateAddMappingForGUID(), and SDL_PrivateGetGamepadMappingForNameAndGUID().
SDL_PrivateGetGamepadMappingForNameAndGUID()
GamepadMapping_t * SDL_PrivateGetGamepadMappingForNameAndGUID (const char * name, SDL_GUID guid) static
{
    GamepadMapping_t *mapping;
    SDL_AssertJoysticksLocked();
    mapping = SDL_PrivateGetGamepadMappingForGUID(guid, false);
#ifdef SDL_PLATFORM_LINUX
    if (!mapping && name) {
        if (SDL_strstr(name, "Xbox 360 Wireless Receiver")) {
            // The Linux driver xpad.c maps the wireless dpad to buttons
            bool existing;
            mapping = SDL_PrivateAddMappingForGUID(guid,
                                                   "none,X360 Wireless Controller,a:b0,b:b1,back:b6,dpdown:b14,dpleft:b11,dpright:b12,dpup:b13,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,",
                                                   &existing, SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT);
        }
    }
#endif // SDL_PLATFORM_LINUX
    return mapping;
}
References SDL_AssertJoysticksLocked(), SDL_GAMEPAD_MAPPING_PRIORITY_DEFAULT, SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadMappingForGUID(), and SDL_strstr().
Referenced by SDL_IsGamepadNameAndGUID(), and SDL_PrivateGetGamepadMapping().
SDL_PrivateGetGamepadMappingFromMappingString()
char * SDL_PrivateGetGamepadMappingFromMappingString (const char * pMapping) static
{
    const char *pFirstComma, *pSecondComma;
    char *result;
    size_t length;
    pFirstComma = SDL_strchr(pMapping, ',');
    if (!pFirstComma) {
        return NULL;
    }
    pSecondComma = SDL_strchr(pFirstComma + 1, ',');
    if (!pSecondComma) {
        return NULL;
    }
    // Skip whitespace
    while (SDL_isspace(pSecondComma[1])) {
        ++pSecondComma;
    }
    result = SDL_strdup(pSecondComma + 1); // mapping is everything after the 3rd comma
    // Trim whitespace
    length = SDL_strlen(result);
    while (length > 0 && SDL_isspace(result[length - 1])) {
        --length;
    }
    result[length] = '\0';
    return result;
}
References NULL, SDL_isspace(), SDL_strchr(), SDL_strdup(), and SDL_strlen().
Referenced by SDL_PrivateAddMappingForGUID().
SDL_PrivateGetGamepadNameFromMappingString()
char * SDL_PrivateGetGamepadNameFromMappingString (const char * pMapping) static
{
    const char *pFirstComma, *pSecondComma;
    char *pchName;
    pFirstComma = SDL_strchr(pMapping, ',');
    if (!pFirstComma) {
        return NULL;
    }
    pSecondComma = SDL_strchr(pFirstComma + 1, ',');
    if (!pSecondComma) {
        return NULL;
    }
    pchName = (char *)SDL_malloc(pSecondComma - pFirstComma);
    if (!pchName) {
        return NULL;
    }
    SDL_memcpy(pchName, pFirstComma + 1, pSecondComma - pFirstComma);
    pchName[pSecondComma - pFirstComma - 1] = 0;
    return pchName;
}
References NULL, SDL_malloc(), SDL_memcpy, and SDL_strchr().
Referenced by SDL_PrivateAddMappingForGUID().
SDL_PrivateLoadButtonMapping()
void SDL_PrivateLoadButtonMapping (SDL_Gamepad * gamepad, GamepadMapping_t * pGamepadMapping) static
{
    int i;
    SDL_AssertJoysticksLocked();
    gamepad->name = pGamepadMapping->name;
    gamepad->num_bindings = 0;
    gamepad->mapping = pGamepadMapping;
    if (gamepad->joystick->naxes != 0 && gamepad->last_match_axis) {
        SDL_memset(gamepad->last_match_axis, 0, gamepad->joystick->naxes * sizeof(*gamepad->last_match_axis));
    }
    SDL_UpdateGamepadType(gamepad);
    SDL_UpdateGamepadFaceStyle(gamepad);
    SDL_PrivateParseGamepadConfigString(gamepad, pGamepadMapping->mapping);
    if (SDL_IsJoystickHIDAPI(pGamepadMapping->guid)) {
        SDL_FixupHIDAPIMapping(gamepad);
    }
    // Set the zero point for triggers
    for (i = 0; i < gamepad->num_bindings; ++i) {
        SDL_GamepadBinding *binding = &gamepad->bindings[i];
        if (binding->input_type == SDL_GAMEPAD_BINDTYPE_AXIS &&
            binding->output_type == SDL_GAMEPAD_BINDTYPE_AXIS &&
            (binding->output.axis.axis == SDL_GAMEPAD_AXIS_LEFT_TRIGGER ||
             binding->output.axis.axis == SDL_GAMEPAD_AXIS_RIGHT_TRIGGER)) {
            if (binding->input.axis.axis < gamepad->joystick->naxes) {
                gamepad->joystick->axes[binding->input.axis.axis].value =
                    gamepad->joystick->axes[binding->input.axis.axis].zero = (Sint16)binding->input.axis.axis_min;
            }
        }
    }
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_AssertJoysticksLocked(), SDL_FixupHIDAPIMapping(), SDL_GAMEPAD_AXIS_LEFT_TRIGGER, SDL_GAMEPAD_AXIS_RIGHT_TRIGGER, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_IsJoystickHIDAPI(), SDL_memset, SDL_PrivateParseGamepadConfigString(), SDL_UpdateGamepadFaceStyle(), and SDL_UpdateGamepadType().
Referenced by PopMappingChangeTracking(), and SDL_OpenGamepad().
SDL_PrivateMatchGamepadMappingForGUID()
GamepadMapping_t * SDL_PrivateMatchGamepadMappingForGUID (SDL_GUID guid, bool match_version, bool exact_match_crc) static
{
    GamepadMapping_t *mapping, *best_match = NULL;
    Uint16 crc = 0;
    SDL_AssertJoysticksLocked();
    SDL_GetJoystickGUIDInfo(guid, NULL, NULL, NULL, &crc);
    // Clear the CRC from the GUID for matching, the mappings never include it in the GUID
    SDL_SetJoystickGUIDCRC(&guid, 0);
    if (!match_version) {
        SDL_SetJoystickGUIDVersion(&guid, 0);
    }
    for (mapping = s_pSupportedGamepads; mapping; mapping = mapping->next) {
        SDL_GUID mapping_guid;
        if (SDL_memcmp(&mapping->guid, &s_zeroGUID, sizeof(mapping->guid)) == 0) {
            continue;
        }
        SDL_memcpy(&mapping_guid, &mapping->guid, sizeof(mapping_guid));
        if (!match_version) {
            SDL_SetJoystickGUIDVersion(&mapping_guid, 0);
        }
        if (SDL_memcmp(&guid, &mapping_guid, sizeof(guid)) == 0) {
            const char *crc_string = SDL_strstr(mapping->mapping, SDL_GAMEPAD_CRC_FIELD);
            if (crc_string) {
                Uint16 mapping_crc = (Uint16)SDL_strtol(crc_string + SDL_GAMEPAD_CRC_FIELD_SIZE, NULL, 16);
                if (mapping_crc != crc) {
                    // This mapping specified a CRC and they don't match
                    continue;
                }
                // An exact match, including CRC
                return mapping;
            } else if (crc && exact_match_crc) {
                continue;
            }
            if (!best_match) {
                best_match = mapping;
            }
        }
    }
    return best_match;
}
References NULL, s_zeroGUID, SDL_AssertJoysticksLocked(), SDL_GAMEPAD_CRC_FIELD, SDL_GAMEPAD_CRC_FIELD_SIZE, SDL_GetJoystickGUIDInfo(), SDL_memcmp(), SDL_memcpy, SDL_SetJoystickGUIDCRC(), SDL_SetJoystickGUIDVersion(), SDL_strstr(), and SDL_strtol().
Referenced by SDL_PrivateGetGamepadMappingForGUID().
SDL_PrivateParseGamepadConfigString()
bool SDL_PrivateParseGamepadConfigString (SDL_Gamepad * gamepad, const char * pchString) static
{
    char szGameButton[20];
    char szJoystickButton[128];
    bool bGameButton = true;
    int i = 0;
    const char *pchPos = pchString;
    SDL_zeroa(szGameButton);
    SDL_zeroa(szJoystickButton);
    while (pchPos && *pchPos) {
        if (*pchPos == ':') {
            i = 0;
            bGameButton = false;
        } else if (*pchPos == ' ') {
        } else if (*pchPos == ',') {
            i = 0;
            bGameButton = true;
            SDL_PrivateParseGamepadElement(gamepad, szGameButton, szJoystickButton);
            SDL_zeroa(szGameButton);
            SDL_zeroa(szJoystickButton);
        } else if (bGameButton) {
            if (i >= sizeof(szGameButton)) {
                szGameButton[sizeof(szGameButton) - 1] = '\0';
                return SDL_SetError("Button name too large: %s", szGameButton);
            }
            szGameButton[i] = *pchPos;
            i++;
        } else {
            if (i >= sizeof(szJoystickButton)) {
                szJoystickButton[sizeof(szJoystickButton) - 1] = '\0';
                return SDL_SetError("Joystick button name too large: %s", szJoystickButton);
            }
            szJoystickButton[i] = *pchPos;
            i++;
        }
        pchPos++;
    }
    // No more values if the string was terminated by a comma. Don't report an error.
    if (szGameButton[0] != '\0' || szJoystickButton[0] != '\0') {
        SDL_PrivateParseGamepadElement(gamepad, szGameButton, szJoystickButton);
    }
    return true;
}
References SDL_PrivateParseGamepadElement(), SDL_SetError(), and SDL_zeroa.
Referenced by SDL_PrivateLoadButtonMapping().
SDL_PrivateParseGamepadElement()
bool SDL_PrivateParseGamepadElement (SDL_Gamepad * gamepad, const char * szGameButton, const char * szJoystickButton) static
{
    SDL_GamepadBinding bind;
    SDL_GamepadButton button;
    SDL_GamepadAxis axis;
    bool invert_input = false;
    char half_axis_input = 0;
    char half_axis_output = 0;
    int i;
    SDL_GamepadBinding *new_bindings;
    bool axby_mapping = false;
    bool baxy_mapping = false;
    SDL_AssertJoysticksLocked();
    SDL_zero(bind);
    if (*szGameButton == '+' || *szGameButton == '-') {
        half_axis_output = *szGameButton++;
    }
    if (SDL_strstr(gamepad->mapping->mapping, ",hint:SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS:=1") != NULL) {
        axby_mapping = true;
    }
    if (SDL_strstr(gamepad->mapping->mapping, ",hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1") != NULL) {
        baxy_mapping = true;
    }
    // FIXME: We fix these up when loading the mapping, does this ever get hit?
    //SDL_assert(!axby_mapping && !baxy_mapping);
    axis = SDL_GetGamepadAxisFromString(szGameButton);
    button = SDL_PrivateGetGamepadButtonFromString(szGameButton, axby_mapping, baxy_mapping);
    if (axis != SDL_GAMEPAD_AXIS_INVALID) {
        bind.output_type = SDL_GAMEPAD_BINDTYPE_AXIS;
        bind.output.axis.axis = axis;
        if (axis == SDL_GAMEPAD_AXIS_LEFT_TRIGGER || axis == SDL_GAMEPAD_AXIS_RIGHT_TRIGGER) {
            bind.output.axis.axis_min = 0;
            bind.output.axis.axis_max = SDL_JOYSTICK_AXIS_MAX;
        } else {
            if (half_axis_output == '+') {
                bind.output.axis.axis_min = 0;
                bind.output.axis.axis_max = SDL_JOYSTICK_AXIS_MAX;
            } else if (half_axis_output == '-') {
                bind.output.axis.axis_min = 0;
                bind.output.axis.axis_max = SDL_JOYSTICK_AXIS_MIN;
            } else {
                bind.output.axis.axis_min = SDL_JOYSTICK_AXIS_MIN;
                bind.output.axis.axis_max = SDL_JOYSTICK_AXIS_MAX;
            }
        }
    } else if (button != SDL_GAMEPAD_BUTTON_INVALID) {
        bind.output_type = SDL_GAMEPAD_BINDTYPE_BUTTON;
        bind.output.button = button;
    } else {
        return false;
    }
    if (*szJoystickButton == '+' || *szJoystickButton == '-') {
        half_axis_input = *szJoystickButton++;
    }
    if (szJoystickButton[SDL_strlen(szJoystickButton) - 1] == '~') {
        invert_input = true;
    }
    if (szJoystickButton[0] == 'a' && SDL_isdigit((unsigned char)szJoystickButton[1])) {
        bind.input_type = SDL_GAMEPAD_BINDTYPE_AXIS;
        bind.input.axis.axis = SDL_atoi(&szJoystickButton[1]);
        if (half_axis_input == '+') {
            bind.input.axis.axis_min = 0;
            bind.input.axis.axis_max = SDL_JOYSTICK_AXIS_MAX;
        } else if (half_axis_input == '-') {
            bind.input.axis.axis_min = 0;
            bind.input.axis.axis_max = SDL_JOYSTICK_AXIS_MIN;
        } else {
            bind.input.axis.axis_min = SDL_JOYSTICK_AXIS_MIN;
            bind.input.axis.axis_max = SDL_JOYSTICK_AXIS_MAX;
        }
        if (invert_input) {
            int tmp = bind.input.axis.axis_min;
            bind.input.axis.axis_min = bind.input.axis.axis_max;
            bind.input.axis.axis_max = tmp;
        }
    } else if (szJoystickButton[0] == 'b' && SDL_isdigit((unsigned char)szJoystickButton[1])) {
        bind.input_type = SDL_GAMEPAD_BINDTYPE_BUTTON;
        bind.input.button = SDL_atoi(&szJoystickButton[1]);
    } else if (szJoystickButton[0] == 'h' && SDL_isdigit((unsigned char)szJoystickButton[1]) &&
               szJoystickButton[2] == '.' && SDL_isdigit((unsigned char)szJoystickButton[3])) {
        int hat = SDL_atoi(&szJoystickButton[1]);
        int mask = SDL_atoi(&szJoystickButton[3]);
        bind.input_type = SDL_GAMEPAD_BINDTYPE_HAT;
        bind.input.hat.hat = hat;
        bind.input.hat.hat_mask = mask;
    } else {
        return false;
    }
    for (i = 0; i < gamepad->num_bindings; ++i) {
        if (SDL_memcmp(&gamepad->bindings[i], &bind, sizeof(bind)) == 0) {
            // We already have this binding, could be different face button names?
            return true;
        }
    }
    ++gamepad->num_bindings;
    new_bindings = (SDL_GamepadBinding *)SDL_realloc(gamepad->bindings, gamepad->num_bindings * sizeof(*gamepad->bindings));
    if (!new_bindings) {
        SDL_free(gamepad->bindings);
        gamepad->num_bindings = 0;
        gamepad->bindings = NULL;
        return false;
    }
    gamepad->bindings = new_bindings;
    gamepad->bindings[gamepad->num_bindings - 1] = bind;
    return true;
}
References SDL_GamepadBinding::axis, SDL_GamepadBinding::button, SDL_GamepadBinding::hat, SDL_GamepadBinding::input, SDL_GamepadBinding::input_type, NULL, SDL_GamepadBinding::output, SDL_GamepadBinding::output_type, SDL_AssertJoysticksLocked(), SDL_atoi(), SDL_free(), SDL_GAMEPAD_AXIS_INVALID, SDL_GAMEPAD_AXIS_LEFT_TRIGGER, SDL_GAMEPAD_AXIS_RIGHT_TRIGGER, SDL_GAMEPAD_BINDTYPE_AXIS, SDL_GAMEPAD_BINDTYPE_BUTTON, SDL_GAMEPAD_BINDTYPE_HAT, SDL_GAMEPAD_BUTTON_INVALID, SDL_GetGamepadAxisFromString(), SDL_isdigit(), SDL_JOYSTICK_AXIS_MAX, SDL_JOYSTICK_AXIS_MIN, SDL_memcmp(), SDL_PrivateGetGamepadButtonFromString(), SDL_realloc(), SDL_strlen(), SDL_strstr(), and SDL_zero.
Referenced by SDL_PrivateParseGamepadConfigString().
SDL_QuitGamepadMappings()
void SDL_QuitGamepadMappings (void)
{
    GamepadMapping_t *pGamepadMap;
    SDL_AssertJoysticksLocked();
    while (s_pSupportedGamepads) {
        pGamepadMap = s_pSupportedGamepads;
        s_pSupportedGamepads = s_pSupportedGamepads->next;
        SDL_free(pGamepadMap->name);
        SDL_free(pGamepadMap->mapping);
        SDL_free(pGamepadMap);
    }
    SDL_FreeVIDPIDList(&SDL_allowed_gamepads);
    SDL_FreeVIDPIDList(&SDL_ignored_gamepads);
    if (s_gamepadInstanceIDs) {
        SDL_DestroyHashTable(s_gamepadInstanceIDs);
        s_gamepadInstanceIDs = NULL;
    }
}
References NULL, SDL_allowed_gamepads, SDL_AssertJoysticksLocked(), SDL_DestroyHashTable(), SDL_free(), SDL_FreeVIDPIDList(), and SDL_ignored_gamepads.
Referenced by SDL_QuitJoysticks(), and SDL_ReloadGamepadMappings().
SDL_QuitGamepads()
void SDL_QuitGamepads (void)
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        SDL_PrivateGamepadRemoved(gamepad->joystick->instance_id);
    }
    SDL_gamepads_initialized = false;
    SDL_RemoveEventWatch(SDL_GamepadEventWatcher, NULL);
    while (SDL_gamepads) {
        SDL_gamepads->ref_count = 1;
        SDL_CloseGamepad(SDL_gamepads);
    }
    SDL_UnlockJoysticks();
}
References NULL, SDL_CloseGamepad(), SDL_GamepadEventWatcher(), SDL_gamepads_initialized, SDL_LockJoysticks(), SDL_PrivateGamepadRemoved(), SDL_RemoveEventWatch(), and SDL_UnlockJoysticks().
Referenced by SDL_QuitSubSystem().
SDL_ReloadGamepadMappings()
bool SDL_ReloadGamepadMappings (void)
Reinitialize the SDL mapping database to its initial state.
This will generate gamepad events as needed if device mappings change.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Gamepad *gamepad;
    SDL_LockJoysticks();
    PushMappingChangeTracking();
    for (gamepad = SDL_gamepads; gamepad; gamepad = gamepad->next) {
        AddMappingChangeTracking(gamepad->mapping);
    }
    SDL_QuitGamepadMappings();
    SDL_InitGamepadMappings();
    PopMappingChangeTracking();
    SDL_UnlockJoysticks();
    return true;
}
References AddMappingChangeTracking(), PopMappingChangeTracking(), PushMappingChangeTracking(), SDL_InitGamepadMappings(), SDL_LockJoysticks(), SDL_QuitGamepadMappings(), and SDL_UnlockJoysticks().
SDL_RumbleGamepad()
bool SDL_RumbleGamepad (SDL_Gamepad * gamepad, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms)
Start a rumble effect on a gamepad.
Each call to this function cancels any previous rumble effect, and calling it with 0 intensity stops any rumbling.
This function requires you to process SDL events or call SDL_UpdateJoysticks() to update rumble state.
Parameters
gamepad the gamepad to vibrate.
low_frequency_rumble the intensity of the low frequency (left) rumble motor, from 0 to 0xFFFF.
high_frequency_rumble the intensity of the high frequency (right) rumble motor, from 0 to 0xFFFF.
duration_ms the duration of the rumble effect, in milliseconds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_RumbleJoystick(joystick, low_frequency_rumble, high_frequency_rumble, duration_ms);
}
References SDL_GetGamepadJoystick(), and SDL_RumbleJoystick().
SDL_RumbleGamepadTriggers()
bool SDL_RumbleGamepadTriggers (SDL_Gamepad * gamepad, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms)
Start a rumble effect in the gamepad's triggers.
Each call to this function cancels any previous trigger rumble effect, and calling it with 0 intensity stops any rumbling.
Note that this is rumbling of the triggers and not the gamepad as a whole. This is currently only supported on Xbox One gamepads. If you want the (more common) whole-gamepad rumble, use SDL_RumbleGamepad() instead.
This function requires you to process SDL events or call SDL_UpdateJoysticks() to update rumble state.
Parameters
gamepad the gamepad to vibrate.
left_rumble the intensity of the left trigger rumble motor, from 0 to 0xFFFF.
right_rumble the intensity of the right trigger rumble motor, from 0 to 0xFFFF.
duration_ms the duration of the rumble effect, in milliseconds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_RumbleGamepad
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_RumbleJoystickTriggers(joystick, left_rumble, right_rumble, duration_ms);
}
References SDL_GetGamepadJoystick(), and SDL_RumbleJoystickTriggers().
SDL_SendGamepadAxis()
void SDL_SendGamepadAxis (Uint64 timestamp, SDL_Gamepad * gamepad, SDL_GamepadAxis axis, Sint16 value) static
{
    SDL_AssertJoysticksLocked();
    // translate the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_GAMEPAD_AXIS_MOTION)) {
        SDL_Event event;
        event.type = SDL_EVENT_GAMEPAD_AXIS_MOTION;
        event.common.timestamp = timestamp;
        event.gaxis.which = gamepad->joystick->instance_id;
        event.gaxis.axis = axis;
        event.gaxis.value = value;
        SDL_PushEvent(&event);
    }
}
References SDL_AssertJoysticksLocked(), SDL_EVENT_GAMEPAD_AXIS_MOTION, SDL_EventEnabled(), and SDL_PushEvent().
Referenced by HandleJoystickAxis(), HandleJoystickButton(), HandleJoystickHat(), RecenterGamepad(), and ResetOutput().
SDL_SendGamepadButton()
void SDL_SendGamepadButton (Uint64 timestamp, SDL_Gamepad * gamepad, SDL_GamepadButton button, bool down) static
{
    SDL_Event event;
    SDL_AssertJoysticksLocked();
    if (button == SDL_GAMEPAD_BUTTON_INVALID) {
        return;
    }
    if (down) {
        event.type = SDL_EVENT_GAMEPAD_BUTTON_DOWN;
    } else {
        event.type = SDL_EVENT_GAMEPAD_BUTTON_UP;
    }
    if (button == SDL_GAMEPAD_BUTTON_GUIDE) {
        Uint64 now = SDL_GetTicks();
        if (down) {
            gamepad->guide_button_down = now;
            if (gamepad->joystick->delayed_guide_button) {
                // Skip duplicate press
                return;
            }
        } else {
            if (now < (gamepad->guide_button_down + SDL_MINIMUM_GUIDE_BUTTON_DELAY_MS)) {
                gamepad->joystick->delayed_guide_button = true;
                return;
            }
            gamepad->joystick->delayed_guide_button = false;
        }
    }
    // translate the event, if desired
    if (SDL_EventEnabled(event.type)) {
        event.common.timestamp = timestamp;
        event.gbutton.which = gamepad->joystick->instance_id;
        event.gbutton.button = button;
        event.gbutton.down = down;
        SDL_PushEvent(&event);
    }
}
References SDL_AssertJoysticksLocked(), SDL_EVENT_GAMEPAD_BUTTON_DOWN, SDL_EVENT_GAMEPAD_BUTTON_UP, SDL_EventEnabled(), SDL_GAMEPAD_BUTTON_GUIDE, SDL_GAMEPAD_BUTTON_INVALID, SDL_GetTicks(), SDL_MINIMUM_GUIDE_BUTTON_DELAY_MS, and SDL_PushEvent().
Referenced by HandleJoystickAxis(), HandleJoystickButton(), HandleJoystickHat(), RecenterGamepad(), ResetOutput(), and SDL_GamepadHandleDelayedGuideButton().
SDL_SendGamepadEffect()
bool SDL_SendGamepadEffect (SDL_Gamepad * gamepad, const void * data, int size)
Send a gamepad specific effect packet.
Parameters
gamepad the gamepad to affect.
data the data to send to the gamepad.
size the size of the data to send to the gamepad.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_SendJoystickEffect(joystick, data, size);
}
References SDL_GetGamepadJoystick(), and SDL_SendJoystickEffect().
SDL_SetGamepadEventsEnabled()
void SDL_SetGamepadEventsEnabled (bool enabled)
Set the state of gamepad event processing.
If gamepad events are disabled, you must call SDL_UpdateGamepads() yourself and check the state of the gamepad when you want gamepad information.
Parameters
enabled whether to process gamepad events or not.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadEventsEnabled
SDL_UpdateGamepads
{
    unsigned int i;
    for (i = 0; i < SDL_arraysize(SDL_gamepad_event_list); ++i) {
        SDL_SetEventEnabled(SDL_gamepad_event_list[i], enabled);
    }
}
References SDL_arraysize, SDL_gamepad_event_list, and SDL_SetEventEnabled().
SDL_SetGamepadLED()
bool SDL_SetGamepadLED (SDL_Gamepad * gamepad, Uint8 red, Uint8 green, Uint8 blue)
Update a gamepad's LED color.
An example of a joystick LED is the light on the back of a PlayStation 4's DualShock 4 controller.
For gamepads with a single color LED, the maximum of the RGB values will be used as the LED brightness.
Parameters
gamepad the gamepad to update.
red the intensity of the red LED.
green the intensity of the green LED.
blue the intensity of the blue LED.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        return false;
    }
    return SDL_SetJoystickLED(joystick, red, green, blue);
}
References SDL_GetGamepadJoystick(), and SDL_SetJoystickLED().
SDL_SetGamepadMapping()
bool SDL_SetGamepadMapping (SDL_JoystickID instance_id, const char * mapping)
Set the current mapping of a joystick or gamepad.
Details about mappings are discussed with SDL_AddGamepadMapping().
Parameters
instance_id the joystick instance ID.
mapping the mapping to use for this device, or NULL to clear the mapping.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddGamepadMapping
SDL_GetGamepadMapping
{
    SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
    bool result = false;
    if (SDL_memcmp(&guid, &s_zeroGUID, sizeof(guid)) == 0) {
        return SDL_InvalidParamError("instance_id");
    }
    if (!mapping) {
        mapping = "*,*,";
    }
    SDL_LockJoysticks();
    {
        if (SDL_PrivateAddMappingForGUID(guid, mapping, NULL, SDL_GAMEPAD_MAPPING_PRIORITY_API)) {
            result = true;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References NULL, s_zeroGUID, SDL_GAMEPAD_MAPPING_PRIORITY_API, SDL_GetJoystickGUIDForID(), SDL_InvalidParamError, SDL_LockJoysticks(), SDL_memcmp(), SDL_PrivateAddMappingForGUID(), and SDL_UnlockJoysticks().
SDL_SetGamepadPlayerIndex()
bool SDL_SetGamepadPlayerIndex (SDL_Gamepad * gamepad, int player_index)
Set the player index of an opened gamepad
{
    SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
    if (!joystick) {
        // SDL_SetError() will have been called already by SDL_GetGamepadJoystick()
        return false;
    }
    return SDL_SetJoystickPlayerIndex(joystick, player_index);
}
References SDL_GetGamepadJoystick(), and SDL_SetJoystickPlayerIndex().
SDL_SetGamepadSensorEnabled()
bool SDL_SetGamepadSensorEnabled (SDL_Gamepad * gamepad, SDL_SensorType type, bool enabled)
Set whether data reporting for a gamepad sensor is enabled.
Parameters
gamepad the gamepad to update.
type the type of sensor to enable/disable.
enabled whether data reporting should be enabled.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GamepadHasSensor
SDL_GamepadSensorEnabled
{
    SDL_LockJoysticks();
    {
        SDL_Joystick *joystick = SDL_GetGamepadJoystick(gamepad);
        if (joystick) {
            int i;
            for (i = 0; i < joystick->nsensors; ++i) {
                SDL_JoystickSensorInfo *sensor = &joystick->sensors[i];
                if (sensor->type == type) {
                    if (sensor->enabled == (enabled != false)) {
                        SDL_UnlockJoysticks();
                        return true;
                    }
                    if (type == SDL_SENSOR_ACCEL && joystick->accel_sensor) {
                        if (enabled) {
                            joystick->accel = SDL_OpenSensor(joystick->accel_sensor);
                            if (!joystick->accel) {
                                SDL_UnlockJoysticks();
                                return false;
                            }
                        } else {
                            if (joystick->accel) {
                                SDL_CloseSensor(joystick->accel);
                                joystick->accel = NULL;
                            }
                        }
                    } else if (type == SDL_SENSOR_GYRO && joystick->gyro_sensor) {
                        if (enabled) {
                            joystick->gyro = SDL_OpenSensor(joystick->gyro_sensor);
                            if (!joystick->gyro) {
                                SDL_UnlockJoysticks();
                                return false;
                            }
                        } else {
                            if (joystick->gyro) {
                                SDL_CloseSensor(joystick->gyro);
                                joystick->gyro = NULL;
                            }
                        }
                    } else {
                        if (enabled) {
                            if (joystick->nsensors_enabled == 0) {
                                if (!joystick->driver->SetSensorsEnabled(joystick, true)) {
                                    SDL_UnlockJoysticks();
                                    return false;
                                }
                            }
                            ++joystick->nsensors_enabled;
                        } else {
                            if (joystick->nsensors_enabled == 1) {
                                if (!joystick->driver->SetSensorsEnabled(joystick, false)) {
                                    SDL_UnlockJoysticks();
                                    return false;
                                }
                            }
                            --joystick->nsensors_enabled;
                        }
                    }
                    sensor->enabled = enabled;
                    SDL_UnlockJoysticks();
                    return true;
                }
            }
        }
    }
    SDL_UnlockJoysticks();
    return SDL_Unsupported();
}
References SDL_JoystickSensorInfo::enabled, NULL, SDL_CloseSensor(), SDL_GetGamepadJoystick(), SDL_LockJoysticks(), SDL_OpenSensor(), SDL_SENSOR_ACCEL, SDL_SENSOR_GYRO, SDL_UnlockJoysticks(), SDL_Unsupported, and SDL_JoystickSensorInfo::type.
SDL_ShouldIgnoreGamepad()
bool SDL_ShouldIgnoreGamepad (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char * name)
{
#ifdef SDL_PLATFORM_LINUX
    if (SDL_endswith(name, " Motion Sensors")) {
        // Don't treat the PS3 and PS4 motion controls as a separate gamepad
        return true;
    }
    if (SDL_strncmp(name, "Nintendo ", 9) == 0 && SDL_strstr(name, " IMU") != NULL) {
        // Don't treat the Nintendo IMU as a separate gamepad
        return true;
    }
    if (SDL_endswith(name, " Accelerometer") ||
        SDL_endswith(name, " IR") ||
        SDL_endswith(name, " Motion Plus") ||
        SDL_endswith(name, " Nunchuk")) {
        // Don't treat the Wii extension controls as a separate gamepad
        return true;
    }
#endif
    if (name && SDL_strcmp(name, "uinput-fpc") == 0) {
        // The Google Pixel fingerprint sensor reports itself as a joystick
        return true;
    }
#ifdef SDL_PLATFORM_WIN32
    if (SDL_GetHintBoolean("SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD", false) &&
        SDL_GetHintBoolean("STEAM_COMPAT_PROTON", false)) {
        // We are launched by Steam and running under Proton
        // We can't tell whether this controller is a Steam Virtual Gamepad,
        // so assume that Proton is doing the appropriate filtering of controllers
        // and anything we see here is fine to use.
        return false;
    }
#endif // SDL_PLATFORM_WIN32
    if (SDL_IsJoystickSteamVirtualGamepad(vendor_id, product_id, version)) {
        return !SDL_GetHintBoolean("SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD", false);
    }
    if (SDL_allowed_gamepads.num_included_entries > 0) {
        if (SDL_VIDPIDInList(vendor_id, product_id, &SDL_allowed_gamepads)) {
            return false;
        }
        return true;
    } else {
        if (SDL_VIDPIDInList(vendor_id, product_id, &SDL_ignored_gamepads)) {
            return true;
        }
        return false;
    }
}
References NULL, SDL_allowed_gamepads, SDL_endswith(), SDL_GetHintBoolean(), SDL_ignored_gamepads, SDL_IsJoystickSteamVirtualGamepad(), SDL_strcmp(), SDL_strncmp(), SDL_strstr(), and SDL_VIDPIDInList().
Referenced by SDL_ShouldIgnoreJoystick().
SDL_UpdateGamepadFaceStyle()
void SDL_UpdateGamepadFaceStyle (SDL_Gamepad * gamepad) static
{
    char *face_string, *comma;
    SDL_AssertJoysticksLocked();
    gamepad->face_style = SDL_GAMEPAD_FACE_STYLE_UNKNOWN;
    face_string = SDL_strstr(gamepad->mapping->mapping, SDL_GAMEPAD_FACE_FIELD);
    if (face_string) {
        face_string += SDL_GAMEPAD_TYPE_FIELD_SIZE;
        comma = SDL_strchr(face_string, ',');
        if (comma) {
            *comma = '\0';
            gamepad->face_style = SDL_GetGamepadFaceStyleFromString(face_string);
            *comma = ',';
        } else {
            gamepad->face_style = SDL_GetGamepadFaceStyleFromString(face_string);
        }
    }
    if (gamepad->face_style == SDL_GAMEPAD_FACE_STYLE_UNKNOWN &&
        SDL_strstr(gamepad->mapping->mapping, "SDL_GAMECONTROLLER_USE_GAMECUBE_LABELS") != NULL) {
        // This controller uses GameCube button style
        gamepad->face_style = SDL_GAMEPAD_FACE_STYLE_AXBY;
    }
    if (gamepad->face_style == SDL_GAMEPAD_FACE_STYLE_UNKNOWN &&
        SDL_strstr(gamepad->mapping->mapping, "SDL_GAMECONTROLLER_USE_BUTTON_LABELS") != NULL) {
        // This controller uses Nintendo button style
        gamepad->face_style = SDL_GAMEPAD_FACE_STYLE_BAYX;
    }
    if (gamepad->face_style == SDL_GAMEPAD_FACE_STYLE_UNKNOWN) {
        gamepad->face_style = SDL_GetGamepadFaceStyleForGamepadType(gamepad->type);
    }
}
References NULL, SDL_AssertJoysticksLocked(), SDL_GAMEPAD_FACE_FIELD, SDL_GAMEPAD_FACE_STYLE_AXBY, SDL_GAMEPAD_FACE_STYLE_BAYX, SDL_GAMEPAD_FACE_STYLE_UNKNOWN, SDL_GAMEPAD_TYPE_FIELD_SIZE, SDL_GetGamepadFaceStyleForGamepadType(), SDL_GetGamepadFaceStyleFromString(), SDL_strchr(), and SDL_strstr().
Referenced by SDL_PrivateLoadButtonMapping().
SDL_UpdateGamepads()
void SDL_UpdateGamepads (void)
Manually pump gamepad updates if not using the loop.
This function is called automatically by the event loop if events are enabled. Under such circumstances, it will not be necessary to call this function.
Since
This function is available since SDL 3.2.0.
{
    // Just for API completeness; the joystick API does all the work.
    SDL_UpdateJoysticks();
}
References SDL_UpdateJoysticks().
SDL_UpdateGamepadType()
void SDL_UpdateGamepadType (SDL_Gamepad * gamepad) static
{
    char *type_string, *comma;
    SDL_AssertJoysticksLocked();
    gamepad->type = SDL_GAMEPAD_TYPE_UNKNOWN;
    type_string = SDL_strstr(gamepad->mapping->mapping, SDL_GAMEPAD_TYPE_FIELD);
    if (type_string) {
        type_string += SDL_GAMEPAD_TYPE_FIELD_SIZE;
        comma = SDL_strchr(type_string, ',');
        if (comma) {
            *comma = '\0';
            gamepad->type = SDL_GetGamepadTypeFromString(type_string);
            *comma = ',';
        } else {
            gamepad->type = SDL_GetGamepadTypeFromString(type_string);
        }
    }
    if (gamepad->type == SDL_GAMEPAD_TYPE_UNKNOWN) {
        gamepad->type = SDL_GetRealGamepadTypeForID(gamepad->joystick->instance_id);
    }
}
References SDL_AssertJoysticksLocked(), SDL_GAMEPAD_TYPE_FIELD, SDL_GAMEPAD_TYPE_FIELD_SIZE, SDL_GAMEPAD_TYPE_UNKNOWN, SDL_GetGamepadTypeFromString(), SDL_GetRealGamepadTypeForID(), SDL_strchr(), and SDL_strstr().
Referenced by SDL_PrivateLoadButtonMapping().
Variable Documentation
map_StringForGamepadAxis
const char* map_StringForGamepadAxis[] static
Initial value:
= {
    "leftx",
    "lefty",
    "rightx",
    "righty",
    "lefttrigger",
    "righttrigger"
}
{
    "leftx",
    "lefty",
    "rightx",
    "righty",
    "lefttrigger",
    "righttrigger"
};
Referenced by SDL_COMPILE_TIME_ASSERT(), SDL_GetGamepadAxisFromString(), and SDL_GetGamepadStringForAxis().
map_StringForGamepadButton
const char* map_StringForGamepadButton[] static
Initial value:
= {
    "a",
    "b",
    "x",
    "y",
    "back",
    "guide",
    "start",
    "leftstick",
    "rightstick",
    "leftshoulder",
    "rightshoulder",
    "dpup",
    "dpdown",
    "dpleft",
    "dpright",
    "misc1",
    "paddle1",
    "paddle2",
    "paddle3",
    "paddle4",
    "touchpad",
    "misc2",
    "misc3",
    "misc4",
    "misc5",
    "misc6"
}
{
    "a",
    "b",
    "x",
    "y",
    "back",
    "guide",
    "start",
    "leftstick",
    "rightstick",
    "leftshoulder",
    "rightshoulder",
    "dpup",
    "dpdown",
    "dpleft",
    "dpright",
    "misc1",
    "paddle1",
    "paddle2",
    "paddle3",
    "paddle4",
    "touchpad",
    "misc2",
    "misc3",
    "misc4",
    "misc5",
    "misc6"
};
Referenced by SDL_COMPILE_TIME_ASSERT(), SDL_GetGamepadStringForButton(), and SDL_PrivateGetGamepadButtonFromString().
map_StringForGamepadType
const char* map_StringForGamepadType[] static
Initial value:
= {
    "unknown",
    "standard",
    "xbox360",
    "xboxone",
    "ps3",
    "ps4",
    "ps5",
    "switchpro",
    "joyconleft",
    "joyconright",
    "joyconpair",
    "gamecube"
}
{
    "unknown",
    "standard",
    "xbox360",
    "xboxone",
    "ps3",
    "ps4",
    "ps5",
    "switchpro",
    "joyconleft",
    "joyconright",
    "joyconpair",
    "gamecube"
};
Referenced by SDL_COMPILE_TIME_ASSERT(), SDL_GetGamepadStringForType(), and SDL_GetGamepadTypeFromString().
s_zeroGUID
SDL_GUID s_zeroGUID static
Referenced by SDL_GetGamepadMappings(), SDL_PrivateMatchGamepadMappingForGUID(), and SDL_SetGamepadMapping().
SDL_allowed_gamepads
SDL_vidpid_list SDL_allowed_gamepads static
Initial value:
= {
    SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT, 0, 0, NULL,
    NULL, 0, 0, NULL,
    0, NULL,
    false
}
{
    SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT, 0, 0, NULL,
    NULL, 0, 0, NULL,
    0, NULL,
    false
};
Referenced by SDL_InitGamepadMappings(), SDL_QuitGamepadMappings(), and SDL_ShouldIgnoreGamepad().
SDL_gamepad_event_list
const Uint32 SDL_gamepad_event_list[] static
Initial value:
= {
    SDL_EVENT_GAMEPAD_AXIS_MOTION,
    SDL_EVENT_GAMEPAD_BUTTON_DOWN,
    SDL_EVENT_GAMEPAD_BUTTON_UP,
    SDL_EVENT_GAMEPAD_ADDED,
    SDL_EVENT_GAMEPAD_REMOVED,
    SDL_EVENT_GAMEPAD_REMAPPED,
    SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN,
    SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION,
    SDL_EVENT_GAMEPAD_TOUCHPAD_UP,
    SDL_EVENT_GAMEPAD_SENSOR_UPDATE,
}
{
    SDL_EVENT_GAMEPAD_AXIS_MOTION,
    SDL_EVENT_GAMEPAD_BUTTON_DOWN,
    SDL_EVENT_GAMEPAD_BUTTON_UP,
    SDL_EVENT_GAMEPAD_ADDED,
    SDL_EVENT_GAMEPAD_REMOVED,
    SDL_EVENT_GAMEPAD_REMAPPED,
    SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN,
    SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION,
    SDL_EVENT_GAMEPAD_TOUCHPAD_UP,
    SDL_EVENT_GAMEPAD_SENSOR_UPDATE,
};
Referenced by SDL_GamepadEventsEnabled(), and SDL_SetGamepadEventsEnabled().
SDL_gamepads_initialized
bool SDL_gamepads_initialized static
Referenced by SDL_InitGamepads(), SDL_PrivateGamepadAdded(), SDL_PrivateGamepadRemapped(), SDL_PrivateGamepadRemoved(), and SDL_QuitGamepads().
SDL_ignored_gamepads
SDL_vidpid_list SDL_ignored_gamepads static
Initial value:
= {
    SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES, 0, 0, NULL,
    NULL, 0, 0, NULL,
    0, NULL,
    false
}
{
    SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES, 0, 0, NULL,
    NULL, 0, 0, NULL,
    0, NULL,
    false
};
Referenced by SDL_InitGamepadMappings(), SDL_QuitGamepadMappings(), and SDL_ShouldIgnoreGamepad().