SDL3: SDL-main/src/core/unix/SDL_appid.c File Reference
SDL_appid.c File Reference
#include "SDL_internal.h"
#include "SDL_appid.h"
#include <unistd.h>
Functions
const char * SDL_GetAppID (void)
const char * SDL_GetExeName (void)
Function Documentation
SDL_GetAppID()
const char * SDL_GetAppID (void)
{
    const char *id_str = SDL_GetAppMetadataProperty(SDL_PROP_APP_METADATA_IDENTIFIER_STRING);
    if (!id_str) {
        // If the hint isn't set, try to use the application's executable name
        id_str = SDL_GetExeName();
    }
    if (!id_str) {
        // Finally, use the default we've used forever
        id_str = "SDL_App";
    }
    return id_str;
}
References SDL_GetAppMetadataProperty(), SDL_GetExeName(), and SDL_PROP_APP_METADATA_IDENTIFIER_STRING.
SDL_GetExeName()
const char * SDL_GetExeName (void)
{
    static const char *proc_name = NULL;
    // TODO: Use a fallback if BSD has no mounted procfs (OpenBSD has no procfs at all)
    if (!proc_name) {
#if defined(SDL_PLATFORM_LINUX) || defined(SDL_PLATFORM_FREEBSD) || defined (SDL_PLATFORM_NETBSD)
        static char linkfile[1024];
        int linksize;
#if defined(SDL_PLATFORM_LINUX)
        const char *proc_path = "/proc/self/exe";
#elif defined(SDL_PLATFORM_FREEBSD)
        const char *proc_path = "/proc/curproc/file";
#elif defined(SDL_PLATFORM_NETBSD)
        const char *proc_path = "/proc/curproc/exe";
#endif
        linksize = readlink(proc_path, linkfile, sizeof(linkfile) - 1);
        if (linksize > 0) {
            linkfile[linksize] = '\0';
            proc_name = SDL_strrchr(linkfile, '/');
            if (proc_name) {
                ++proc_name;
            } else {
                proc_name = linkfile;
            }
        }
#endif
    }
    return proc_name;
}
References NULL, and SDL_strrchr().
Referenced by SDL_GetAppID().