SDL3: SDL-main/src/audio/SDL_audio_c.h File Reference
SDL_audio_c.h File Reference
Functions
void SDL_UpdateAudio (void)
Function Documentation
SDL_UpdateAudio()
void SDL_UpdateAudio (void) extern
{
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    SDL_PendingAudioDeviceEvent *pending_events = current_audio.pending_events.next;
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    if (!pending_events) {
        return;  // nothing to do, check next time.
    }
    // okay, let's take this whole list of events so we can dump the lock, and new ones can queue up for a later update.
    SDL_LockRWLockForWriting(current_audio.device_hash_lock);
    pending_events = current_audio.pending_events.next;  // in case this changed...
    current_audio.pending_events.next = NULL;
    current_audio.pending_events_tail = &current_audio.pending_events;
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    SDL_PendingAudioDeviceEvent *pending_next = NULL;
    for (SDL_PendingAudioDeviceEvent *i = pending_events; i; i = pending_next) {
        pending_next = i->next;
        if (SDL_EventEnabled(i->type)) {
            SDL_Event event;
            SDL_zero(event);
            event.type = i->type;
            event.adevice.which = (Uint32) i->devid;
            event.adevice.recording = ((i->devid & (1<<0)) == 0);  // bit #0 of devid is set for playback devices and unset for recording.
            SDL_PushEvent(&event);
        }
        SDL_free(i);
    }
}
References current_audio, SDL_PendingAudioDeviceEvent::next, NULL, SDL_EventEnabled(), SDL_free(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_PushEvent(), SDL_UnlockRWLock(), and SDL_zero.
Referenced by SDL_PumpEventMaintenance().