SDL3: SDL-main/include/SDL3/SDL_metal.h File Reference
SDL_metal.h File Reference
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Typedefs
typedef void * SDL_MetalView
Functions
Metal support functions
SDL_DECLSPEC SDL_MetalView SDLCALL SDL_Metal_CreateView (SDL_Window *window)
SDL_DECLSPEC void SDLCALL SDL_Metal_DestroyView (SDL_MetalView view)
SDL_DECLSPEC void *SDLCALL SDL_Metal_GetLayer (SDL_MetalView view)
Typedef Documentation
SDL_MetalView
typedef void* SDL_MetalView
CategoryMetal
Functions to creating Metal layers and views on SDL windows.
This provides some platform-specific glue for Apple platforms. Most macOS and iOS apps can use SDL without these functions, but this API they can be useful for specific OS-level integration tasks. A handle to a CAMetalLayer-backed NSView (macOS) or UIView (iOS/tvOS).
Since
This datatype is available since SDL 3.2.0.
Function Documentation
SDL_Metal_CreateView()
SDL_DECLSPEC SDL_MetalView SDLCALL SDL_Metal_CreateView (SDL_Window * window) extern
Create a CAMetalLayer-backed NSView/UIView and attach it to the specified window.
On macOS, this does not associate a MTLDevice with the CAMetalLayer on its own. It is up to user code to do that.
The returned handle can be casted directly to a NSView or UIView. To access the backing CAMetalLayer, call SDL_Metal_GetLayer().
Parameters
window the window.
Returns
handle NSView or UIView.
Since
This function is available since SDL 3.2.0.
See also
SDL_Metal_DestroyView
SDL_Metal_GetLayer
{
    CHECK_WINDOW_MAGIC(window, NULL);
    if (!_this->Metal_CreateView) {
        SDL_Unsupported();
        return NULL;
    }
    if (!(window->flags & SDL_WINDOW_METAL)) {
        // No problem, we can convert to Metal
        if (window->flags & SDL_WINDOW_OPENGL) {
            window->flags &= ~SDL_WINDOW_OPENGL;
            SDL_GL_UnloadLibrary();
        }
        if (window->flags & SDL_WINDOW_VULKAN) {
            window->flags &= ~SDL_WINDOW_VULKAN;
            SDL_Vulkan_UnloadLibrary();
        }
        window->flags |= SDL_WINDOW_METAL;
    }
    return _this->Metal_CreateView(_this, window);
}
References _this, CHECK_WINDOW_MAGIC, NULL, SDL_GL_UnloadLibrary(), SDL_Unsupported, SDL_Vulkan_UnloadLibrary(), SDL_WINDOW_METAL, SDL_WINDOW_OPENGL, and SDL_WINDOW_VULKAN.
SDL_Metal_DestroyView()
SDL_DECLSPEC void SDLCALL SDL_Metal_DestroyView (SDL_MetalView view) extern
Destroy an existing SDL_MetalView object.
This should be called before SDL_DestroyWindow, if SDL_Metal_CreateView was called after SDL_CreateWindow.
Parameters
view the SDL_MetalView object.
Since
This function is available since SDL 3.2.0.
See also
SDL_Metal_CreateView
{
    if (_this && view && _this->Metal_DestroyView) {
        _this->Metal_DestroyView(_this, view);
    }
}
References _this.
SDL_Metal_GetLayer()
SDL_DECLSPEC void *SDLCALL SDL_Metal_GetLayer (SDL_MetalView view) extern
Get a pointer to the backing CAMetalLayer for the given view.
Parameters
view the SDL_MetalView object.
Returns
a pointer.
Since
This function is available since SDL 3.2.0.
{
    if (_this && _this->Metal_GetLayer) {
        if (view) {
            return _this->Metal_GetLayer(_this, view);
        } else {
            SDL_InvalidParamError("view");
            return NULL;
        }
    } else {
        SDL_SetError("Metal is not supported.");
        return NULL;
    }
}
References _this, NULL, SDL_InvalidParamError, and SDL_SetError().