SDL3: SDL-main/src/io/SDL_iostream_c.h File Reference
SDL_iostream_c.h File Reference
#include "SDL_internal.h"
Functions
SDL_IOStream * SDL_IOFromFD (int fd, bool autoclose)
Function Documentation
SDL_IOFromFD()
SDL_IOStream * SDL_IOFromFD (int fd, bool autoclose) extern
{
    IOStreamFDData *iodata = (IOStreamFDData *) SDL_calloc(1, sizeof (*iodata));
    if (!iodata) {
        if (autoclose) {
           close(fd);
        }
        return NULL;
    }
    SDL_IOStreamInterface iface;
    SDL_INIT_INTERFACE(&iface);
    // There's no fd_size because SDL_GetIOSize emulates it the same way we'd do it for fd anyhow.
    iface.seek = fd_seek;
    iface.read = fd_read;
    iface.write = fd_write;
    iface.flush = fd_flush;
    iface.close = fd_close;
    iodata->fd = fd;
    iodata->autoclose = autoclose;
    struct stat st;
    iodata->regular_file = ((fstat(fd, &st) == 0) && S_ISREG(st.st_mode));
    SDL_IOStream *iostr = SDL_OpenIO(&iface, iodata);
    if (!iostr) {
        iface.close(iodata);
    } else {
        const SDL_PropertiesID props = SDL_GetIOProperties(iostr);
        if (props) {
            SDL_SetNumberProperty(props, SDL_PROP_IOSTREAM_FILE_DESCRIPTOR_NUMBER, fd);
        }
    }
    return iostr;
}
References IOStreamFDData::autoclose, IOStreamFDData::fd, fd_close(), fd_flush(), fd_read(), fd_seek(), fd_write(), NULL, IOStreamFDData::regular_file, SDL_calloc(), SDL_GetIOProperties(), SDL_INIT_INTERFACE, SDL_OpenIO(), SDL_PROP_IOSTREAM_FILE_DESCRIPTOR_NUMBER, and SDL_SetNumberProperty().