SDL3: SDL-main/src/events/SDL_windowevents_c.h File Reference
SDL_windowevents_c.h File Reference
#include "SDL_internal.h"
Enumerations
enum SDL_WindowEventWatchPriority { SDL_WINDOW_EVENT_WATCH_EARLY , SDL_WINDOW_EVENT_WATCH_NORMAL }
Functions
void SDL_AddWindowEventWatch (SDL_WindowEventWatchPriority priority, SDL_EventFilter filter, void *userdata)
void SDL_InitWindowEventWatch (void)
void SDL_QuitWindowEventWatch (void)
void SDL_RemoveWindowEventWatch (SDL_WindowEventWatchPriority priority, SDL_EventFilter filter, void *userdata)
bool SDL_SendWindowEvent (SDL_Window *window, SDL_EventType windowevent, int data1, int data2)
Enumeration Type Documentation
SDL_WindowEventWatchPriority
enum SDL_WindowEventWatchPriority
Enumerator
SDL_WINDOW_EVENT_WATCH_EARLY
SDL_WINDOW_EVENT_WATCH_NORMAL
{
    SDL_WINDOW_EVENT_WATCH_EARLY,
    SDL_WINDOW_EVENT_WATCH_NORMAL
} SDL_WindowEventWatchPriority;
Function Documentation
SDL_AddWindowEventWatch()
void SDL_AddWindowEventWatch (SDL_WindowEventWatchPriority priority, SDL_EventFilter filter, void * userdata) extern
{
    SDL_AddEventWatchList(&SDL_window_event_watchers[priority], filter, userdata);
}
References SDL_AddEventWatchList(), and SDL_window_event_watchers.
Referenced by SDL_CreateRendererWithProperties().
SDL_InitWindowEventWatch()
void SDL_InitWindowEventWatch (void) extern
{
    for (int i = 0; i < SDL_arraysize(SDL_window_event_watchers); ++i) {
        SDL_InitEventWatchList(&SDL_window_event_watchers[i]);
    }
}
References SDL_arraysize, SDL_InitEventWatchList(), and SDL_window_event_watchers.
Referenced by SDL_StartEventLoop().
SDL_QuitWindowEventWatch()
void SDL_QuitWindowEventWatch (void) extern
{
    for (int i = 0; i < SDL_arraysize(SDL_window_event_watchers); ++i) {
        SDL_QuitEventWatchList(&SDL_window_event_watchers[i]);
    }
}
References SDL_arraysize, SDL_QuitEventWatchList(), and SDL_window_event_watchers.
Referenced by SDL_StopEventLoop().
SDL_RemoveWindowEventWatch()
void SDL_RemoveWindowEventWatch (SDL_WindowEventWatchPriority priority, SDL_EventFilter filter, void * userdata) extern
{
    SDL_RemoveEventWatchList(&SDL_window_event_watchers[priority], filter, userdata);
}
References SDL_RemoveEventWatchList(), and SDL_window_event_watchers.
Referenced by SDL_DestroyRendererWithoutFreeing().
SDL_SendWindowEvent()
bool SDL_SendWindowEvent (SDL_Window * window, SDL_EventType windowevent, int data1, int data2) extern
{
    bool posted = false;
    if (!window) {
        return false;
    }
    SDL_assert(SDL_ObjectValid(window, SDL_OBJECT_TYPE_WINDOW));
    if (window->is_destroying && windowevent != SDL_EVENT_WINDOW_DESTROYED) {
        return false;
    }
    switch (windowevent) {
    case SDL_EVENT_WINDOW_SHOWN:
        if (!(window->flags & SDL_WINDOW_HIDDEN)) {
            return false;
        }
        window->flags &= ~(SDL_WINDOW_HIDDEN | SDL_WINDOW_MINIMIZED);
        break;
    case SDL_EVENT_WINDOW_HIDDEN:
        if (window->flags & SDL_WINDOW_HIDDEN) {
            return false;
        }
        window->flags |= SDL_WINDOW_HIDDEN;
        break;
    case SDL_EVENT_WINDOW_EXPOSED:
        window->flags &= ~SDL_WINDOW_OCCLUDED;
        break;
    case SDL_EVENT_WINDOW_MOVED:
        window->undefined_x = false;
        window->undefined_y = false;
        window->last_position_pending = false;
        if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
            window->windowed.x = data1;
            window->windowed.y = data2;
            if (!(window->flags & SDL_WINDOW_MAXIMIZED) && !window->tiled) {
                window->floating.x = data1;
                window->floating.y = data2;
            }
        }
        if (data1 == window->x && data2 == window->y) {
            return false;
        }
        window->x = data1;
        window->y = data2;
        break;
    case SDL_EVENT_WINDOW_RESIZED:
        window->last_size_pending = false;
        if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
            window->windowed.w = data1;
            window->windowed.h = data2;
            if (!(window->flags & SDL_WINDOW_MAXIMIZED) && !window->tiled) {
                window->floating.w = data1;
                window->floating.h = data2;
            }
        }
        if (data1 == window->w && data2 == window->h) {
            SDL_CheckWindowPixelSizeChanged(window);
            return false;
        }
        window->w = data1;
        window->h = data2;
        break;
    case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
        if (data1 == window->last_pixel_w && data2 == window->last_pixel_h) {
            return false;
        }
        window->last_pixel_w = data1;
        window->last_pixel_h = data2;
        break;
    case SDL_EVENT_WINDOW_MINIMIZED:
        if (window->flags & SDL_WINDOW_MINIMIZED) {
            return false;
        }
        window->flags &= ~SDL_WINDOW_MAXIMIZED;
        window->flags |= SDL_WINDOW_MINIMIZED;
        break;
    case SDL_EVENT_WINDOW_MAXIMIZED:
        if (window->flags & SDL_WINDOW_MAXIMIZED) {
            return false;
        }
        window->flags &= ~SDL_WINDOW_MINIMIZED;
        window->flags |= SDL_WINDOW_MAXIMIZED;
        break;
    case SDL_EVENT_WINDOW_RESTORED:
        if (!(window->flags & (SDL_WINDOW_MINIMIZED | SDL_WINDOW_MAXIMIZED))) {
            return false;
        }
        window->flags &= ~(SDL_WINDOW_MINIMIZED | SDL_WINDOW_MAXIMIZED);
        break;
    case SDL_EVENT_WINDOW_MOUSE_ENTER:
        if (window->flags & SDL_WINDOW_MOUSE_FOCUS) {
            return false;
        }
        window->flags |= SDL_WINDOW_MOUSE_FOCUS;
        break;
    case SDL_EVENT_WINDOW_MOUSE_LEAVE:
        if (!(window->flags & SDL_WINDOW_MOUSE_FOCUS)) {
            return false;
        }
        window->flags &= ~SDL_WINDOW_MOUSE_FOCUS;
        break;
    case SDL_EVENT_WINDOW_FOCUS_GAINED:
        if (window->flags & SDL_WINDOW_INPUT_FOCUS) {
            return false;
        }
        window->flags |= SDL_WINDOW_INPUT_FOCUS;
        break;
    case SDL_EVENT_WINDOW_FOCUS_LOST:
        if (!(window->flags & SDL_WINDOW_INPUT_FOCUS)) {
            return false;
        }
        window->flags &= ~SDL_WINDOW_INPUT_FOCUS;
        break;
    case SDL_EVENT_WINDOW_DISPLAY_CHANGED:
        if (data1 == 0 || (SDL_DisplayID)data1 == window->last_displayID) {
            return false;
        }
        window->update_fullscreen_on_display_changed = true;
        window->last_displayID = (SDL_DisplayID)data1;
        break;
    case SDL_EVENT_WINDOW_OCCLUDED:
        if (window->flags & SDL_WINDOW_OCCLUDED) {
            return false;
        }
        window->flags |= SDL_WINDOW_OCCLUDED;
        break;
    case SDL_EVENT_WINDOW_ENTER_FULLSCREEN:
        if (window->flags & SDL_WINDOW_FULLSCREEN) {
            return false;
        }
        window->flags |= SDL_WINDOW_FULLSCREEN;
        break;
    case SDL_EVENT_WINDOW_LEAVE_FULLSCREEN:
        if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
            return false;
        }
        window->flags &= ~SDL_WINDOW_FULLSCREEN;
        break;
    default:
        break;
    }
    // Post the event, if desired
    SDL_Event event;
    event.type = windowevent;
    event.common.timestamp = 0;
    event.window.data1 = data1;
    event.window.data2 = data2;
    event.window.windowID = window->id;
    SDL_DispatchEventWatchList(&SDL_window_event_watchers[SDL_WINDOW_EVENT_WATCH_EARLY], &event);
    SDL_DispatchEventWatchList(&SDL_window_event_watchers[SDL_WINDOW_EVENT_WATCH_NORMAL], &event);
    if (SDL_EventEnabled(windowevent)) {
        // Fixes queue overflow with move/resize events that aren't processed
        if (windowevent == SDL_EVENT_WINDOW_MOVED ||
            windowevent == SDL_EVENT_WINDOW_RESIZED ||
            windowevent == SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED ||
            windowevent == SDL_EVENT_WINDOW_SAFE_AREA_CHANGED ||
            windowevent == SDL_EVENT_WINDOW_EXPOSED ||
            windowevent == SDL_EVENT_WINDOW_OCCLUDED) {
            SDL_FilterEvents(RemoveSupercededWindowEvents, &event);
        }
        posted = SDL_PushEvent(&event);
    }
    switch (windowevent) {
    case SDL_EVENT_WINDOW_SHOWN:
        SDL_OnWindowShown(window);
        break;
    case SDL_EVENT_WINDOW_HIDDEN:
        SDL_OnWindowHidden(window);
        break;
    case SDL_EVENT_WINDOW_MOVED:
        SDL_OnWindowMoved(window);
        break;
    case SDL_EVENT_WINDOW_RESIZED:
        SDL_OnWindowResized(window);
        break;
    case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
        SDL_OnWindowPixelSizeChanged(window);
        break;
    case SDL_EVENT_WINDOW_MINIMIZED:
        SDL_OnWindowMinimized(window);
        break;
    case SDL_EVENT_WINDOW_MAXIMIZED:
        SDL_OnWindowMaximized(window);
        break;
    case SDL_EVENT_WINDOW_RESTORED:
        SDL_OnWindowRestored(window);
        break;
    case SDL_EVENT_WINDOW_MOUSE_ENTER:
        SDL_OnWindowEnter(window);
        break;
    case SDL_EVENT_WINDOW_MOUSE_LEAVE:
        SDL_OnWindowLeave(window);
        break;
    case SDL_EVENT_WINDOW_FOCUS_GAINED:
        SDL_OnWindowFocusGained(window);
        break;
    case SDL_EVENT_WINDOW_FOCUS_LOST:
        SDL_OnWindowFocusLost(window);
        break;
    case SDL_EVENT_WINDOW_DISPLAY_CHANGED:
        SDL_OnWindowDisplayChanged(window);
        break;
    default:
        break;
    }
    if (windowevent == SDL_EVENT_WINDOW_CLOSE_REQUESTED && !window->parent && !SDL_HasActiveTrays()) {
        int toplevel_count = 0;
        SDL_Window *n;
        for (n = SDL_GetVideoDevice()->windows; n; n = n->next) {
            if (!n->parent && !(n->flags & SDL_WINDOW_HIDDEN)) {
                ++toplevel_count;
            }
        }
        if (toplevel_count <= 1) {
            if (SDL_GetHintBoolean(SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE, true)) {
                SDL_SendQuit(); // This is the last toplevel window in the list so send the SDL_EVENT_QUIT event
            }
        }
    }
    return posted;
}
References RemoveSupercededWindowEvents(), SDL_assert, SDL_CheckWindowPixelSizeChanged(), SDL_DispatchEventWatchList(), SDL_EVENT_WINDOW_CLOSE_REQUESTED, SDL_EVENT_WINDOW_DESTROYED, SDL_EVENT_WINDOW_DISPLAY_CHANGED, SDL_EVENT_WINDOW_ENTER_FULLSCREEN, SDL_EVENT_WINDOW_EXPOSED, SDL_EVENT_WINDOW_FOCUS_GAINED, SDL_EVENT_WINDOW_FOCUS_LOST, SDL_EVENT_WINDOW_HIDDEN, SDL_EVENT_WINDOW_LEAVE_FULLSCREEN, SDL_EVENT_WINDOW_MAXIMIZED, SDL_EVENT_WINDOW_MINIMIZED, SDL_EVENT_WINDOW_MOUSE_ENTER, SDL_EVENT_WINDOW_MOUSE_LEAVE, SDL_EVENT_WINDOW_MOVED, SDL_EVENT_WINDOW_OCCLUDED, SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, SDL_EVENT_WINDOW_RESIZED, SDL_EVENT_WINDOW_RESTORED, SDL_EVENT_WINDOW_SAFE_AREA_CHANGED, SDL_EVENT_WINDOW_SHOWN, SDL_EventEnabled(), SDL_FilterEvents(), SDL_GetHintBoolean(), SDL_GetVideoDevice(), SDL_HasActiveTrays(), SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE, SDL_OBJECT_TYPE_WINDOW, SDL_ObjectValid(), SDL_OnWindowDisplayChanged(), SDL_OnWindowEnter(), SDL_OnWindowFocusGained(), SDL_OnWindowFocusLost(), SDL_OnWindowHidden(), SDL_OnWindowLeave(), SDL_OnWindowMaximized(), SDL_OnWindowMinimized(), SDL_OnWindowMoved(), SDL_OnWindowPixelSizeChanged(), SDL_OnWindowResized(), SDL_OnWindowRestored(), SDL_OnWindowShown(), SDL_PushEvent(), SDL_SendQuit(), SDL_WINDOW_EVENT_WATCH_EARLY, SDL_WINDOW_EVENT_WATCH_NORMAL, SDL_window_event_watchers, SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, SDL_WINDOW_INPUT_FOCUS, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_MINIMIZED, SDL_WINDOW_MOUSE_FOCUS, and SDL_WINDOW_OCCLUDED.
Referenced by SDL_BLooper::_HandleBasicWindowEvent(), SDL_BLooper::_HandleWindowMoved(), SDL_BLooper::_HandleWindowResized(), SDL_CheckWindowDisplayChanged(), SDL_CheckWindowDisplayScaleChanged(), SDL_CheckWindowPixelSizeChanged(), SDL_CheckWindowSafeAreaChanged(), SDL_DestroyWindow(), SDL_HideWindow(), SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationWillEnterBackground(), SDL_OnWindowLiveResizeUpdate(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_SetWindowHDRProperties(), SDL_ShowWindow(), and SDL_UpdateFullscreenMode().