SDL3: SDL-main/src/atomic/SDL_atomic.c File Reference
SDL_atomic.c File Reference
#include "SDL_internal.h"
Macros
#define EMULATE_CAS 1
Functions
static SDL_INLINE void enterLock (void *a)
static SDL_INLINE void leaveLock (void *a)
int SDL_AddAtomicInt (SDL_AtomicInt *a, int v)
bool SDL_CompareAndSwapAtomicInt (SDL_AtomicInt *a, int oldval, int newval)
bool SDL_CompareAndSwapAtomicPointer (void **a, void *oldval, void *newval)
bool SDL_CompareAndSwapAtomicU32 (SDL_AtomicU32 *a, Uint32 oldval, Uint32 newval)
int SDL_GetAtomicInt (SDL_AtomicInt *a)
void * SDL_GetAtomicPointer (void **a)
Uint32 SDL_GetAtomicU32 (SDL_AtomicU32 *a)
void SDL_MemoryBarrierAcquireFunction (void)
void SDL_MemoryBarrierReleaseFunction (void)
int SDL_SetAtomicInt (SDL_AtomicInt *a, int v)
void * SDL_SetAtomicPointer (void **a, void *v)
Uint32 SDL_SetAtomicU32 (SDL_AtomicU32 *a, Uint32 v)
Variables
static SDL_SpinLock locks [32]
Macro Definition Documentation
EMULATE_CAS
#define EMULATE_CAS 1
Function Documentation
enterLock()
SDL_INLINE void enterLock (void * a) static
{
    uintptr_t index = ((((uintptr_t)a) >> 3) & 0x1f);
    SDL_LockSpinlock(&locks[index]);
}
References locks, SDL_INLINE, and SDL_LockSpinlock().
Referenced by SDL_CompareAndSwapAtomicInt(), SDL_CompareAndSwapAtomicPointer(), and SDL_CompareAndSwapAtomicU32().
leaveLock()
SDL_INLINE void leaveLock (void * a) static
{
    uintptr_t index = ((((uintptr_t)a) >> 3) & 0x1f);
    SDL_UnlockSpinlock(&locks[index]);
}
References locks, SDL_INLINE, and SDL_UnlockSpinlock().
Referenced by SDL_CompareAndSwapAtomicInt(), SDL_CompareAndSwapAtomicPointer(), and SDL_CompareAndSwapAtomicU32().
SDL_AddAtomicInt()
int SDL_AddAtomicInt (SDL_AtomicInt * a, int v)
Add to an atomic variable.
This function also acts as a full memory barrier.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable to be modified.
v the desired value to add.
Returns
the previous value of the atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AtomicDecRef
SDL_AtomicIncRef
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_add, sizeof(long) == sizeof(a->value));
    return _InterlockedExchangeAdd((long *)&a->value, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_add, sizeof(int) == sizeof(a->value));
    return _SDL_xadd_watcom((volatile int *)&a->value, v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_fetch_and_add(&a->value, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    int pv = a->value;
    membar_consumer();
    atomic_add_int((volatile uint_t *)&a->value, v);
    return pv;
#else
    int value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicInt(a, value, (value + v)));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicInt(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by CreatePhysicalAudioDevice(), GetAsyncIOTaskOutcome(), RequestAsyncIO(), SDL_AddCamera(), SDL_AddEvent(), SDL_CloseAsyncIO(), SDL_CutEvent(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_RegisterEvents(), SDL_TryLockRWLockForReading_generic(), SDL_TryLockRWLockForWriting_generic(), SDL_UnlockRWLock(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().
SDL_CompareAndSwapAtomicInt()
bool SDL_CompareAndSwapAtomicInt (SDL_AtomicInt * a, int oldval, int newval)
Set an atomic variable to a new value if it is currently an old value.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable to be modified.
oldval the old value.
newval the new value.
Returns
true if the atomic variable was set, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicInt
SDL_SetAtomicInt
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(long) == sizeof(a->value));
    return _InterlockedCompareExchange((long *)&a->value, (long)newval, (long)oldval) == (long)oldval;
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_cmpxchg_watcom((volatile int *)&a->value, newval, oldval);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_bool_compare_and_swap(&a->value, oldval, newval);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap32Barrier(oldval, newval, &a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(uint_t) == sizeof(a->value));
    return ((int)atomic_cas_uint((volatile uint_t *)&a->value, (uint_t)oldval, (uint_t)newval) == oldval);
#elif defined(EMULATE_CAS)
    bool result = false;
    enterLock(a);
    if (a->value == oldval) {
        a->value = newval;
        result = true;
    }
    leaveLock(a);
    return result;
#else
#error Please define your platform.
#endif
}
References enterLock(), leaveLock(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by SDL_AddAtomicInt(), SDL_AudioDeviceDisconnected(), SDL_CameraDisconnected(), SDL_DetachThread(), SDL_DispatchMainCallbackEvent(), SDL_GetAtomicInt(), SDL_InitAudio(), SDL_InitMainCallbacks(), SDL_IterateMainCallbacks(), SDL_MainCallbackEventWatcher(), SDL_RunThread(), SDL_SetAtomicInt(), SDL_SetTLS(), SDL_ShouldInit(), and SDL_ShouldQuit().
SDL_CompareAndSwapAtomicPointer()
bool SDL_CompareAndSwapAtomicPointer (void ** a, void * oldval, void * newval)
Set a pointer to a new value if it is currently an old value.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to a pointer.
oldval the old pointer value.
newval the new pointer value.
Returns
true if the pointer was set, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicInt
SDL_GetAtomicPointer
SDL_SetAtomicPointer
{
#ifdef HAVE_MSC_ATOMICS
    return _InterlockedCompareExchangePointer(a, newval, oldval) == oldval;
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_cmpxchg_watcom((int *)a, (long)newval, (long)oldval);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_bool_compare_and_swap(a, oldval, newval);
#elif defined(SDL_PLATFORM_MACOS) && defined(__LP64__)  // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap64Barrier((int64_t)oldval, (int64_t)newval, (int64_t *)a);
#elif defined(SDL_PLATFORM_MACOS) && !defined(__LP64__) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap32Barrier((int32_t)oldval, (int32_t)newval, (int32_t *)a);
#elif defined(SDL_PLATFORM_SOLARIS)
    return (atomic_cas_ptr(a, oldval, newval) == oldval);
#elif defined(EMULATE_CAS)
    bool result = false;
    enterLock(a);
    if (*a == oldval) {
        *a = newval;
        result = true;
    }
    leaveLock(a);
    return result;
#else
#error Please define your platform.
#endif
}
References enterLock(), and leaveLock().
Referenced by SDL_DestroyWindow(), SDL_GetAtomicPointer(), and SDL_SetAtomicPointer().
SDL_CompareAndSwapAtomicU32()
bool SDL_CompareAndSwapAtomicU32 (SDL_AtomicU32 * a, Uint32 oldval, Uint32 newval)
Set an atomic variable to a new value if it is currently an old value.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicU32 variable to be modified.
oldval the old value.
newval the new value.
Returns
true if the atomic variable was set, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicU32
SDL_SetAtomicU32
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(long) == sizeof(a->value));
    return _InterlockedCompareExchange((long *)&a->value, (long)newval, (long)oldval) == (long)oldval;
#elif defined(HAVE_WATCOM_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(int) == sizeof(a->value));
    return _SDL_cmpxchg_watcom((volatile int *)&a->value, (int)newval, (int)oldval);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_bool_compare_and_swap(&a->value, oldval, newval);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap32Barrier((int32_t)oldval, (int32_t)newval, (int32_t *)&a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(uint_t) == sizeof(a->value));
    return ((Uint32)atomic_cas_uint((volatile uint_t *)&a->value, (uint_t)oldval, (uint_t)newval) == oldval);
#elif defined(EMULATE_CAS)
    bool result = false;
    enterLock(a);
    if (a->value == oldval) {
        a->value = newval;
        result = true;
    }
    leaveLock(a);
    return result;
#else
#error Please define your platform.
#endif
}
References enterLock(), leaveLock(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicU32::value.
Referenced by GetHintProperties(), SDL_CreateProperties(), SDL_GetAtomicU32(), SDL_GetGlobalProperties(), SDL_QuitHints(), SDL_QuitProperties(), and SDL_SetAtomicU32().
SDL_GetAtomicInt()
int SDL_GetAtomicInt (SDL_AtomicInt * a)
Get the value of an atomic variable.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable.
Returns
the current value of an atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAtomicInt
{
#ifdef HAVE_ATOMIC_LOAD_N
    return __atomic_load_n(&a->value, __ATOMIC_SEQ_CST);
#elif defined(HAVE_MSC_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(long) == sizeof(a->value));
    return _InterlockedOr((long *)&a->value, 0);
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_xadd_watcom(&a->value, 0);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_or_and_fetch(&a->value, 0);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return sizeof(a->value) == sizeof(uint32_t) ? OSAtomicOr32Barrier(0, (volatile uint32_t *)&a->value) : OSAtomicAdd64Barrier(0, (volatile int64_t *)&a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    return atomic_or_uint_nv((volatile uint_t *)&a->value, 0);
#else
    int value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicInt(a, value, value));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicInt(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by CountAudioDevices(), CreatePhysicalAudioDevice(), GetAudioDevices(), OpenPhysicalAudioDevice(), SDL_AddCamera(), SDL_AddEvent(), SDL_AudioDevicePaused(), SDL_CameraThreadIterate(), SDL_CheckInitLog(), SDL_CutEvent(), SDL_DefaultAudioDeviceChanged(), SDL_DestroyAsyncIOQueue(), SDL_DispatchMainCallbackEvent(), SDL_GetCameras(), SDL_GetMessageBoxCount(), SDL_GetNumAllocations(), SDL_GetThreadState(), SDL_GetTLS(), SDL_InitMainCallbacks(), SDL_IterateMainCallbacks(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_OpenAudioDevice(), SDL_PeepEventsInternal(), SDL_PlaybackAudioThreadIterate(), SDL_PlaybackAudioThreadShutdown(), SDL_PumpEventsInternal(), SDL_QuitTLSData(), SDL_RecordingAudioThreadIterate(), SDL_RemoveTimer(), SDL_RunOnMainThread(), SDL_SetTLS(), SDL_ShouldInit(), SDL_ShouldQuit(), SDL_TimerThread(), SDL_TryLockRWLockForReading_generic(), SDL_TryLockRWLockForWriting_generic(), SDL_UnlockJoysticks(), SDL_UnlockRWLock(), SDL_UnlockSensors(), SDL_WaitEventTimeoutNS(), SerializePhysicalDeviceClose(), ZombieWaitDevice(), and ZombieWaitDevice().
SDL_GetAtomicPointer()
void * SDL_GetAtomicPointer (void ** a)
Get the value of a pointer atomically.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to a pointer.
Returns
the current value of a pointer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicPointer
SDL_SetAtomicPointer
{
#ifdef HAVE_ATOMIC_LOAD_N
    return __atomic_load_n(a, __ATOMIC_SEQ_CST);
#elif defined(HAVE_MSC_ATOMICS)
    return _InterlockedCompareExchangePointer(a, NULL, NULL);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_val_compare_and_swap(a, (void *)0, (void *)0);
#elif defined(SDL_PLATFORM_SOLARIS)
    return atomic_cas_ptr(a, (void *)0, (void *)0);
#else
    void *value;
    do {
        value = *a;
    } while (!SDL_CompareAndSwapAtomicPointer(a, value, value));
    return value;
#endif
}
References NULL, and SDL_CompareAndSwapAtomicPointer().
Referenced by ObtainLogicalAudioDevice().
SDL_GetAtomicU32()
Uint32 SDL_GetAtomicU32 (SDL_AtomicU32 * a)
Get the value of an atomic variable.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicU32 variable.
Returns
the current value of an atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAtomicU32
{
#ifdef HAVE_ATOMIC_LOAD_N
    return __atomic_load_n(&a->value, __ATOMIC_SEQ_CST);
#elif defined(HAVE_MSC_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(long) == sizeof(a->value));
    return (Uint32)_InterlockedOr((long *)&a->value, 0);
#elif defined(HAVE_WATCOM_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(int) == sizeof(a->value));
    return (Uint32)_SDL_xadd_watcom((volatile int *)&a->value, 0);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_or_and_fetch(&a->value, 0);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicOr32Barrier(0, (volatile uint32_t *)&a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(uint_t) == sizeof(a->value));
    return (Uint32)atomic_or_uint_nv((volatile uint_t *)&a->value, 0);
#else
    Uint32 value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicU32(a, value, value));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicU32(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicU32::value.
Referenced by GetHintProperties(), SDL_CreateProperties(), SDL_GetGlobalProperties(), SDL_QuitHints(), and SDL_QuitProperties().
SDL_MemoryBarrierAcquireFunction()
void SDL_MemoryBarrierAcquireFunction (void)
Insert a memory acquire barrier (function version).
Please refer to SDL_MemoryBarrierRelease for details. This is a function version, which might be useful if you need to use this functionality from a scripting language, etc. Also, some of the macro versions call this function behind the scenes, where more heavy lifting can happen inside of SDL. Generally, though, an app written in C/C++/etc should use the macro version, as it will be more efficient.
Thread Safety
Obviously this function is safe to use from any thread at any time, but if you find yourself needing this, you are probably dealing with some very sensitive code; be careful!
Since
This function is available since SDL 3.2.0.
See also
SDL_MemoryBarrierAcquire
{
    SDL_MemoryBarrierAcquire();
}
References SDL_MemoryBarrierAcquire.
SDL_MemoryBarrierReleaseFunction()
void SDL_MemoryBarrierReleaseFunction (void)
Insert a memory release barrier (function version).
Please refer to SDL_MemoryBarrierRelease for details. This is a function version, which might be useful if you need to use this functionality from a scripting language, etc. Also, some of the macro versions call this function behind the scenes, where more heavy lifting can happen inside of SDL. Generally, though, an app written in C/C++/etc should use the macro version, as it will be more efficient.
Thread Safety
Obviously this function is safe to use from any thread at any time, but if you find yourself needing this, you are probably dealing with some very sensitive code; be careful!
Since
This function is available since SDL 3.2.0.
See also
SDL_MemoryBarrierRelease
{
    SDL_MemoryBarrierRelease();
}
References SDL_MemoryBarrierRelease.
SDL_SetAtomicInt()
int SDL_SetAtomicInt (SDL_AtomicInt * a, int v)
Set an atomic variable to a value.
This function also acts as a full memory barrier.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable to be modified.
v the desired value.
Returns
the previous value of the atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicInt
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(long) == sizeof(a->value));
    return _InterlockedExchange((long *)&a->value, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_xchg_watcom(&a->value, v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_lock_test_and_set(&a->value, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(uint_t) == sizeof(a->value));
    return (int)atomic_swap_uint((volatile uint_t *)&a->value, v);
#else
    int value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicInt(a, value, v));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicInt(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by ClosePhysicalAudioDevice(), ClosePhysicalCamera(), CreatePhysicalAudioDevice(), SDL_AddCamera(), SDL_CreateAsyncIOQueue(), SDL_CreateMainThreadCallback(), SDL_CreateRWLock(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateTimer(), SDL_InitMainCallbacks(), SDL_InitTimers(), SDL_OpenAudioDevice(), SDL_OpenAudioDeviceStream(), SDL_OpenCamera(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitMainThreadCallbacks(), SDL_QuitTimers(), SDL_RemoveTimer(), SDL_RunMainThreadCallbacks(), SDL_SetInitialized(), SDL_StopEventLoop(), SDL_TimerThread(), and SetLogicalAudioDevicePauseState().
SDL_SetAtomicPointer()
void * SDL_SetAtomicPointer (void ** a, void * v)
Set a pointer to a value atomically.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to a pointer.
v the desired pointer value.
Returns
the previous value of the pointer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicPointer
SDL_GetAtomicPointer
{
#ifdef HAVE_MSC_ATOMICS
    return _InterlockedExchangePointer(a, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    return (void *)_SDL_xchg_watcom((int *)a, (long)v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_lock_test_and_set(a, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    return atomic_swap_ptr(a, v);
#else
    void *value;
    do {
        value = *a;
    } while (!SDL_CompareAndSwapAtomicPointer(a, value, v));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicPointer().
Referenced by SDL_SendWakeupEvent(), and SDL_WaitEventTimeout_Device().
SDL_SetAtomicU32()
Uint32 SDL_SetAtomicU32 (SDL_AtomicU32 * a, Uint32 v)
Set an atomic variable to a value.
This function also acts as a full memory barrier.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicU32 variable to be modified.
v the desired value.
Returns
the previous value of the atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicU32
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(long) == sizeof(a->value));
    return _InterlockedExchange((long *)&a->value, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_xchg_watcom(&a->value, v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_lock_test_and_set(&a->value, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(uint_t) == sizeof(a->value));
    return (Uint32)atomic_swap_uint((volatile uint_t *)&a->value, v);
#else
    Uint32 value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicU32(a, value, v));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicU32(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicU32::value.
Variable Documentation
locks
SDL_SpinLock locks[32] static
Referenced by enterLock(), and leaveLock().