SDL3: SDL-main/src/video/khronos/EGL/eglext.h File Reference
eglext.h File Reference
#include <EGL/eglplatform.h>
Data Structures
struct EGLClientPixmapHI
Macros
#define EGL_ANDROID_blob_cache 1
#define EGL_ANDROID_create_native_client_buffer 1
#define EGL_ANDROID_framebuffer_target 1
#define EGL_ANDROID_front_buffer_auto_refresh 1
#define EGL_ANDROID_get_frame_timestamps 1
#define EGL_ANDROID_get_native_client_buffer 1
#define EGL_ANDROID_GLES_layers 1
#define EGL_ANDROID_image_native_buffer 1
#define EGL_ANDROID_native_fence_sync 1
#define EGL_ANDROID_presentation_time 1
#define EGL_ANDROID_recordable 1
#define EGL_ANGLE_d3d_share_handle_client_buffer 1
#define EGL_ANGLE_device_d3d 1
#define EGL_ANGLE_query_surface_pointer 1
#define EGL_ANGLE_surface_d3d_texture_2d_share_handle 1
#define EGL_ANGLE_sync_control_rate 1
#define EGL_ANGLE_window_fixed_size 1
#define EGL_ARM_image_format 1
#define EGL_ARM_implicit_external_sync 1
#define EGL_ARM_pixmap_multisample_discard 1
#define EGL_AUTO_STEREO_NV 0x3136
#define EGL_BAD_DEVICE_EXT 0x322B
#define EGL_BAD_OUTPUT_LAYER_EXT 0x322D
#define EGL_BAD_OUTPUT_PORT_EXT 0x322E
#define EGL_BITMAP_ORIGIN_KHR 0x30C8
#define EGL_BITMAP_PITCH_KHR 0x30C7
#define EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR 0x30CC
#define EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR 0x30CB
#define EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR 0x30CA
#define EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR 0x30CD
#define EGL_BITMAP_PIXEL_RED_OFFSET_KHR 0x30C9
#define EGL_BITMAP_PIXEL_SIZE_KHR 0x3110
#define EGL_BITMAP_POINTER_KHR 0x30C6
#define EGL_BOTTOM_NV 0x336E
#define EGL_BUFFER_AGE_EXT 0x313D
#define EGL_BUFFER_AGE_KHR 0x313D
#define EGL_CL_EVENT_HANDLE_KHR 0x309C
#define EGL_CLIENT_PIXMAP_POINTER_HI 0x8F74
#define EGL_COLOR_ARGB_HI 0x8F73
#define EGL_COLOR_COMPONENT_TYPE_EXT 0x3339
#define EGL_COLOR_COMPONENT_TYPE_FIXED_EXT 0x333A
#define EGL_COLOR_COMPONENT_TYPE_FLOAT_EXT 0x333B
#define EGL_COLOR_COMPONENT_TYPE_INTEGER_ARM 0x3288
#define EGL_COLOR_COMPONENT_TYPE_UNSIGNED_INTEGER_ARM 0x3287
#define EGL_COLOR_FORMAT_HI 0x8F70
#define EGL_COLOR_RGB_HI 0x8F71
#define EGL_COLOR_RGBA_HI 0x8F72
#define EGL_COMPOSITE_DEADLINE_ANDROID 0x3431
#define EGL_COMPOSITE_INTERVAL_ANDROID 0x3432
#define EGL_COMPOSITE_TO_PRESENT_LATENCY_ANDROID 0x3433
#define EGL_COMPOSITION_LATCH_TIME_ANDROID 0x3436
#define EGL_COMPOSITOR_DROP_NEWEST_FRAME_EXT 0x3462
#define EGL_COMPOSITOR_KEEP_NEWEST_FRAME_EXT 0x3463
#define EGL_CONFIG_SELECT_GROUP_EXT 0x34C0
#define EGL_CONFORMANT_KHR 0x3042
#define EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR 0x321E
#define EGL_CONSUMER_AUTO_ORIENTATION_NV 0x3369
#define EGL_CONSUMER_MAX_FRAME_HINT_NV 0x3338
#define EGL_CONSUMER_METADATA_NV 0x3254
#define EGL_CONTEXT_FLAGS_KHR 0x30FC
#define EGL_CONTEXT_MAJOR_VERSION_KHR 0x3098
#define EGL_CONTEXT_MINOR_VERSION_KHR 0x30FB
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR 0x00000002
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR 0x00000001
#define EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR 0x00000001
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR 0x00000002
#define EGL_CONTEXT_OPENGL_NO_ERROR_KHR 0x31B3
#define EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR 0x30FD
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT 0x3138
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR 0x31BD
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR 0x00000004
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT 0x30BF
#define EGL_CONTEXT_PRIORITY_HIGH_IMG 0x3101
#define EGL_CONTEXT_PRIORITY_LEVEL_IMG 0x3100
#define EGL_CONTEXT_PRIORITY_LOW_IMG 0x3103
#define EGL_CONTEXT_PRIORITY_MEDIUM_IMG 0x3102
#define EGL_CONTEXT_PRIORITY_REALTIME_NV 0x3357
#define EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR 0x2098
#define EGL_CONTEXT_RELEASE_BEHAVIOR_KHR 0x2097
#define EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR 0
#define EGL_COVERAGE_BUFFERS_NV 0x30E0
#define EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV 0x3132
#define EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV 0x3133
#define EGL_COVERAGE_SAMPLE_RESOLVE_NV 0x3131
#define EGL_COVERAGE_SAMPLES_NV 0x30E1
#define EGL_CTA861_3_MAX_CONTENT_LIGHT_LEVEL_EXT 0x3360
#define EGL_CTA861_3_MAX_FRAME_AVERAGE_LEVEL_EXT 0x3361
#define EGL_CUDA_DEVICE_NV 0x323A
#define EGL_CUDA_EVENT_HANDLE_NV 0x323B
#define EGL_D3D11_DEVICE_ANGLE 0x33A1
#define EGL_D3D9_DEVICE_ANGLE 0x33A0
#define EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE 0x3200
#define EGL_DEBUG_CALLBACK_KHR 0x33B8
#define EGL_DEBUG_MSG_CRITICAL_KHR 0x33B9
#define EGL_DEBUG_MSG_ERROR_KHR 0x33BA
#define EGL_DEBUG_MSG_INFO_KHR 0x33BC
#define EGL_DEBUG_MSG_WARN_KHR 0x33BB
#define EGL_DEPTH_ENCODING_NONE_NV 0
#define EGL_DEPTH_ENCODING_NONLINEAR_NV 0x30E3
#define EGL_DEPTH_ENCODING_NV 0x30E2
#define EGL_DEQUEUE_READY_TIME_ANDROID 0x343B
#define EGL_DEVICE_EXT 0x322C
#define EGL_DEVICE_UUID_EXT 0x335C
#define EGL_DISCARD_SAMPLES_ARM 0x3286
#define EGL_DISPLAY_PRESENT_TIME_ANDROID 0x343A
#define EGL_DMA_BUF_PLANE0_FD_EXT 0x3272
#define EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT 0x3444
#define EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT 0x3443
#define EGL_DMA_BUF_PLANE0_OFFSET_EXT 0x3273
#define EGL_DMA_BUF_PLANE0_PITCH_EXT 0x3274
#define EGL_DMA_BUF_PLANE1_FD_EXT 0x3275
#define EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT 0x3446
#define EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT 0x3445
#define EGL_DMA_BUF_PLANE1_OFFSET_EXT 0x3276
#define EGL_DMA_BUF_PLANE1_PITCH_EXT 0x3277
#define EGL_DMA_BUF_PLANE2_FD_EXT 0x3278
#define EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT 0x3448
#define EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT 0x3447
#define EGL_DMA_BUF_PLANE2_OFFSET_EXT 0x3279
#define EGL_DMA_BUF_PLANE2_PITCH_EXT 0x327A
#define EGL_DMA_BUF_PLANE3_FD_EXT 0x3440
#define EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT 0x344A
#define EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT 0x3449
#define EGL_DMA_BUF_PLANE3_OFFSET_EXT 0x3441
#define EGL_DMA_BUF_PLANE3_PITCH_EXT 0x3442
#define EGL_DRIVER_NAME_EXT 0x335E
#define EGL_DRIVER_UUID_EXT 0x335D
#define EGL_DRM_BUFFER_FORMAT_ARGB32_MESA 0x31D2
#define EGL_DRM_BUFFER_FORMAT_MESA 0x31D0
#define EGL_DRM_BUFFER_MESA 0x31D3
#define EGL_DRM_BUFFER_STRIDE_MESA 0x31D4
#define EGL_DRM_BUFFER_USE_CURSOR_MESA 0x00000004
#define EGL_DRM_BUFFER_USE_MESA 0x31D1
#define EGL_DRM_BUFFER_USE_SCANOUT_MESA 0x00000001
#define EGL_DRM_BUFFER_USE_SHARE_MESA 0x00000002
#define EGL_DRM_CONNECTOR_EXT 0x3236
#define EGL_DRM_CRTC_EXT 0x3234
#define EGL_DRM_DEVICE_FILE_EXT 0x3233
#define EGL_DRM_MASTER_FD_EXT 0x333C
#define EGL_DRM_PLANE_EXT 0x3235
#define EGL_DRM_RENDER_NODE_FILE_EXT 0x3377
#define EGL_EGLEXT_VERSION 20231215
#define EGL_EXT_bind_to_front 1
#define EGL_EXT_buffer_age 1
#define EGL_EXT_client_extensions 1
#define EGL_EXT_client_sync 1
#define EGL_EXT_compositor 1
#define EGL_EXT_config_select_group 1
#define EGL_EXT_create_context_robustness 1
#define EGL_EXT_device_base 1
#define EGL_EXT_device_drm 1
#define EGL_EXT_device_drm_render_node 1
#define EGL_EXT_device_enumeration 1
#define EGL_EXT_device_openwf 1
#define EGL_EXT_device_persistent_id 1
#define EGL_EXT_device_query 1
#define EGL_EXT_device_query_name 1
#define EGL_EXT_explicit_device 1
#define EGL_EXT_gl_colorspace_bt2020_hlg 1
#define EGL_EXT_gl_colorspace_bt2020_linear 1
#define EGL_EXT_gl_colorspace_bt2020_pq 1
#define EGL_EXT_gl_colorspace_display_p3 1
#define EGL_EXT_gl_colorspace_display_p3_linear 1
#define EGL_EXT_gl_colorspace_display_p3_passthrough 1
#define EGL_EXT_gl_colorspace_scrgb 1
#define EGL_EXT_gl_colorspace_scrgb_linear 1
#define EGL_EXT_image_dma_buf_import 1
#define EGL_EXT_image_dma_buf_import_modifiers 1
#define EGL_EXT_image_gl_colorspace 1
#define EGL_EXT_image_implicit_sync_control 1
#define EGL_EXT_multiview_window 1
#define EGL_EXT_output_base 1
#define EGL_EXT_output_drm 1
#define EGL_EXT_output_openwf 1
#define EGL_EXT_pixel_format_float 1
#define EGL_EXT_platform_base 1
#define EGL_EXT_platform_device 1
#define EGL_EXT_platform_wayland 1
#define EGL_EXT_platform_x11 1
#define EGL_EXT_platform_xcb 1
#define EGL_EXT_present_opaque 1
#define EGL_EXT_protected_content 1
#define EGL_EXT_protected_surface 1
#define EGL_EXT_query_reset_notification_strategy 1
#define EGL_EXT_stream_consumer_egloutput 1
#define EGL_EXT_surface_compression 1
#define EGL_EXT_surface_CTA861_3_metadata 1
#define EGL_EXT_surface_SMPTE2086_metadata 1
#define EGL_EXT_swap_buffers_with_damage 1
#define EGL_EXT_sync_reuse 1
#define EGL_EXT_yuv_surface 1
#define EGL_EXTERNAL_REF_ID_EXT 0x3461
#define EGL_FIRST_COMPOSITION_GPU_FINISHED_TIME_ANDROID 0x3439
#define EGL_FIRST_COMPOSITION_START_TIME_ANDROID 0x3437
#define EGL_FIXED_SIZE_ANGLE 0x3201
#define EGL_FORMAT_RGB_565_EXACT_KHR 0x30C0
#define EGL_FORMAT_RGB_565_KHR 0x30C1
#define EGL_FORMAT_RGBA_8888_EXACT_KHR 0x30C2
#define EGL_FORMAT_RGBA_8888_KHR 0x30C3
#define EGL_FRAMEBUFFER_TARGET_ANDROID 0x3147
#define EGL_FRONT_BUFFER_AUTO_REFRESH_ANDROID 0x314C
#define EGL_FRONT_BUFFER_EXT 0x3464
#define EGL_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV 0x334C
#define EGL_GL_COLORSPACE_BT2020_HLG_EXT 0x3540
#define EGL_GL_COLORSPACE_BT2020_LINEAR_EXT 0x333F
#define EGL_GL_COLORSPACE_BT2020_PQ_EXT 0x3340
#define EGL_GL_COLORSPACE_DEFAULT_EXT 0x314D
#define EGL_GL_COLORSPACE_DISPLAY_P3_EXT 0x3363
#define EGL_GL_COLORSPACE_DISPLAY_P3_LINEAR_EXT 0x3362
#define EGL_GL_COLORSPACE_DISPLAY_P3_PASSTHROUGH_EXT 0x3490
#define EGL_GL_COLORSPACE_KHR 0x309D
#define EGL_GL_COLORSPACE_LINEAR_KHR 0x308A
#define EGL_GL_COLORSPACE_SCRGB_EXT 0x3351
#define EGL_GL_COLORSPACE_SCRGB_LINEAR_EXT 0x3350
#define EGL_GL_COLORSPACE_SRGB_KHR 0x3089
#define EGL_GL_RENDERBUFFER_KHR 0x30B9
#define EGL_GL_TEXTURE_2D_KHR 0x30B1
#define EGL_GL_TEXTURE_3D_KHR 0x30B2
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR 0x30B4
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR 0x30B6
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR 0x30B8
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR 0x30B3
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR 0x30B5
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR 0x30B7
#define EGL_GL_TEXTURE_LEVEL_KHR 0x30BC
#define EGL_GL_TEXTURE_ZOFFSET_KHR 0x30BD
#define EGL_HI_clientpixmap 1
#define EGL_HI_colorformats 1
#define EGL_IMAGE_PRESERVED_KHR 0x30D2
#define EGL_IMG_context_priority 1
#define EGL_IMG_image_plane_attribs 1
#define EGL_IMPORT_EXPLICIT_SYNC_EXT 0x3472
#define EGL_IMPORT_IMPLICIT_SYNC_EXT 0x3471
#define EGL_IMPORT_SYNC_TYPE_EXT 0x3470
#define EGL_ITU_REC2020_EXT 0x3281
#define EGL_ITU_REC601_EXT 0x327F
#define EGL_ITU_REC709_EXT 0x3280
#define EGL_KHR_cl_event 1
#define EGL_KHR_cl_event2 1
#define EGL_KHR_client_get_all_proc_addresses 1
#define EGL_KHR_config_attribs 1
#define EGL_KHR_context_flush_control 1
#define EGL_KHR_create_context 1
#define EGL_KHR_create_context_no_error 1
#define EGL_KHR_debug 1
#define EGL_KHR_display_reference 1
#define EGL_KHR_fence_sync 1
#define EGL_KHR_get_all_proc_addresses 1
#define EGL_KHR_gl_colorspace 1
#define EGL_KHR_gl_renderbuffer_image 1
#define EGL_KHR_gl_texture_2D_image 1
#define EGL_KHR_gl_texture_3D_image 1
#define EGL_KHR_gl_texture_cubemap_image 1
#define EGL_KHR_image 1
#define EGL_KHR_image_base 1
#define EGL_KHR_image_pixmap 1
#define EGL_KHR_lock_surface 1
#define EGL_KHR_lock_surface2 1
#define EGL_KHR_lock_surface3 1
#define EGL_KHR_mutable_render_buffer 1
#define EGL_KHR_no_config_context 1
#define EGL_KHR_partial_update 1
#define EGL_KHR_platform_android 1
#define EGL_KHR_platform_gbm 1
#define EGL_KHR_platform_wayland 1
#define EGL_KHR_platform_x11 1
#define EGL_KHR_reusable_sync 1
#define EGL_KHR_stream 1
#define EGL_KHR_stream_attrib 1
#define EGL_KHR_stream_consumer_gltexture 1
#define EGL_KHR_stream_cross_process_fd 1
#define EGL_KHR_stream_fifo 1
#define EGL_KHR_stream_producer_aldatalocator 1
#define EGL_KHR_stream_producer_eglsurface 1
#define EGL_KHR_surfaceless_context 1
#define EGL_KHR_swap_buffers_with_damage 1
#define EGL_KHR_vg_parent_image 1
#define EGL_KHR_wait_sync 1
#define EGL_LAST_COMPOSITION_START_TIME_ANDROID 0x3438
#define EGL_LEFT_NV 0x336B
#define EGL_LINUX_DMA_BUF_EXT 0x3270
#define EGL_LINUX_DRM_FOURCC_EXT 0x3271
#define EGL_LOCK_SURFACE_BIT_KHR 0x0080
#define EGL_LOCK_USAGE_HINT_KHR 0x30C5
#define EGL_LOSE_CONTEXT_ON_RESET_EXT 0x31BF
#define EGL_LOSE_CONTEXT_ON_RESET_KHR 0x31BF
#define EGL_LOWER_LEFT_KHR 0x30CE
#define EGL_MAP_PRESERVE_PIXELS_KHR 0x30C4
#define EGL_MATCH_FORMAT_KHR 0x3043
#define EGL_MAX_STREAM_METADATA_BLOCK_SIZE_NV 0x3251
#define EGL_MAX_STREAM_METADATA_BLOCKS_NV 0x3250
#define EGL_MAX_STREAM_METADATA_TOTAL_SIZE_NV 0x3252
#define EGL_MESA_drm_image 1
#define EGL_MESA_image_dma_buf_export 1
#define EGL_MESA_platform_gbm 1
#define EGL_MESA_platform_surfaceless 1
#define EGL_MESA_query_driver 1
#define EGL_METADATA0_SIZE_NV 0x3255
#define EGL_METADATA0_TYPE_NV 0x3259
#define EGL_METADATA1_SIZE_NV 0x3256
#define EGL_METADATA1_TYPE_NV 0x325A
#define EGL_METADATA2_SIZE_NV 0x3257
#define EGL_METADATA2_TYPE_NV 0x325B
#define EGL_METADATA3_SIZE_NV 0x3258
#define EGL_METADATA3_TYPE_NV 0x325C
#define EGL_METADATA_SCALING_EXT 50000
#define EGL_MULTIVIEW_VIEW_COUNT_EXT 0x3134
#define EGL_MUTABLE_RENDER_BUFFER_BIT_KHR 0x1000
#define EGL_NATIVE_BUFFER_ANDROID 0x3140
#define EGL_NATIVE_BUFFER_MULTIPLANE_SEPARATE_IMG 0x3105
#define EGL_NATIVE_BUFFER_PLANE_OFFSET_IMG 0x3106
#define EGL_NATIVE_BUFFER_QNX 0x3551
#define EGL_NATIVE_BUFFER_TIZEN 0x32A0
#define EGL_NATIVE_BUFFER_USAGE_ANDROID 0x3143
#define EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID 0x00000001
#define EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID 0x00000002
#define EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID 0x00000004
#define EGL_NATIVE_PIXMAP_KHR 0x30B0
#define EGL_NATIVE_SURFACE_TIZEN 0x32A1
#define EGL_NO_CONFIG_KHR EGL_CAST(EGLConfig,0)
#define EGL_NO_DEVICE_EXT EGL_CAST(EGLDeviceEXT,0)
#define EGL_NO_FILE_DESCRIPTOR_KHR EGL_CAST(EGLNativeFileDescriptorKHR,-1)
#define EGL_NO_IMAGE_KHR EGL_CAST(EGLImageKHR,0)
#define EGL_NO_NATIVE_FENCE_FD_ANDROID -1
#define EGL_NO_OUTPUT_LAYER_EXT EGL_CAST(EGLOutputLayerEXT,0)
#define EGL_NO_OUTPUT_PORT_EXT EGL_CAST(EGLOutputPortEXT,0)
#define EGL_NO_RESET_NOTIFICATION_EXT 0x31BE
#define EGL_NO_RESET_NOTIFICATION_KHR 0x31BE
#define EGL_NOK_swap_region 1
#define EGL_NOK_swap_region2 1
#define EGL_NOK_texture_from_pixmap 1
#define EGL_NV_3dvision_surface 1
#define EGL_NV_context_priority_realtime 1
#define EGL_NV_coverage_sample 1
#define EGL_NV_coverage_sample_resolve 1
#define EGL_NV_cuda_event 1
#define EGL_NV_depth_nonlinear 1
#define EGL_NV_device_cuda 1
#define EGL_NV_native_query 1
#define EGL_NV_post_convert_rounding 1
#define EGL_NV_post_sub_buffer 1
#define EGL_NV_quadruple_buffer 1
#define EGL_NV_robustness_video_memory_purge 1
#define EGL_NV_stream_consumer_eglimage 1
#define EGL_NV_stream_consumer_eglimage_use_scanout_attrib 1
#define EGL_NV_stream_consumer_gltexture_yuv 1
#define EGL_NV_stream_cross_display 1
#define EGL_NV_stream_cross_object 1
#define EGL_NV_stream_cross_partition 1
#define EGL_NV_stream_cross_process 1
#define EGL_NV_stream_cross_system 1
#define EGL_NV_stream_dma 1
#define EGL_NV_stream_fifo_next 1
#define EGL_NV_stream_fifo_synchronous 1
#define EGL_NV_stream_flush 1
#define EGL_NV_stream_frame_limits 1
#define EGL_NV_stream_metadata 1
#define EGL_NV_stream_origin 1
#define EGL_NV_stream_remote 1
#define EGL_NV_stream_reset 1
#define EGL_NV_stream_socket 1
#define EGL_NV_stream_socket_inet 1
#define EGL_NV_stream_socket_unix 1
#define EGL_NV_stream_sync 1
#define EGL_NV_sync 1
#define EGL_NV_system_time 1
#define EGL_NV_triple_buffer 1
#define EGL_OBJECT_CONTEXT_KHR 0x33B2
#define EGL_OBJECT_DISPLAY_KHR 0x33B1
#define EGL_OBJECT_IMAGE_KHR 0x33B4
#define EGL_OBJECT_STREAM_KHR 0x33B6
#define EGL_OBJECT_SURFACE_KHR 0x33B3
#define EGL_OBJECT_SYNC_KHR 0x33B5
#define EGL_OBJECT_THREAD_KHR 0x33B0
#define EGL_OPENGL_ES3_BIT_KHR 0x00000040
#define EGL_OPENWF_DEVICE_EXT 0x333D
#define EGL_OPENWF_DEVICE_ID_EXT 0x3237
#define EGL_OPENWF_PIPELINE_ID_EXT 0x3238
#define EGL_OPENWF_PORT_ID_EXT 0x3239
#define EGL_OPTIMAL_FORMAT_BIT_KHR 0x0100
#define EGL_PENDING_FRAME_NV 0x3329
#define EGL_PENDING_METADATA_NV 0x3328
#define EGL_PLATFORM_ANDROID_KHR 0x3141
#define EGL_PLATFORM_DEVICE_EXT 0x313F
#define EGL_PLATFORM_GBM_KHR 0x31D7
#define EGL_PLATFORM_GBM_MESA 0x31D7
#define EGL_PLATFORM_SCREEN_QNX 0x3550
#define EGL_PLATFORM_SURFACELESS_MESA 0x31DD
#define EGL_PLATFORM_WAYLAND_EXT 0x31D8
#define EGL_PLATFORM_WAYLAND_KHR 0x31D8
#define EGL_PLATFORM_X11_EXT 0x31D5
#define EGL_PLATFORM_X11_KHR 0x31D5
#define EGL_PLATFORM_X11_SCREEN_EXT 0x31D6
#define EGL_PLATFORM_X11_SCREEN_KHR 0x31D6
#define EGL_PLATFORM_XCB_EXT 0x31DC
#define EGL_PLATFORM_XCB_SCREEN_EXT 0x31DE
#define EGL_POST_SUB_BUFFER_SUPPORTED_NV 0x30BE
#define EGL_PRESENT_OPAQUE_EXT 0x31DF
#define EGL_PRIMARY_COMPOSITOR_CONTEXT_EXT 0x3460
#define EGL_PRODUCER_AUTO_ORIENTATION_NV 0x336A
#define EGL_PRODUCER_MAX_FRAME_HINT_NV 0x3337
#define EGL_PRODUCER_METADATA_NV 0x3253
#define EGL_PROTECTED_CONTENT_EXT 0x32C0
#define EGL_QNX_image_native_buffer 1
#define EGL_QNX_platform_screen 1
#define EGL_QUADRUPLE_BUFFER_NV 0x3231
#define EGL_READ_SURFACE_BIT_KHR 0x0001
#define EGL_READS_DONE_TIME_ANDROID 0x343C
#define EGL_RECORDABLE_ANDROID 0x3142
#define EGL_RENDERER_EXT 0x335F
#define EGL_RENDERING_COMPLETE_TIME_ANDROID 0x3435
#define EGL_REQUESTED_PRESENT_TIME_ANDROID 0x3434
#define EGL_RIGHT_NV 0x336C
#define EGL_SAMPLE_RANGE_HINT_EXT 0x327C
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BX_EXT 0x3345
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BY_EXT 0x3346
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GX_EXT 0x3343
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GY_EXT 0x3344
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RX_EXT 0x3341
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RY_EXT 0x3342
#define EGL_SMPTE2086_MAX_LUMINANCE_EXT 0x3349
#define EGL_SMPTE2086_MIN_LUMINANCE_EXT 0x334A
#define EGL_SMPTE2086_WHITE_POINT_X_EXT 0x3347
#define EGL_SMPTE2086_WHITE_POINT_Y_EXT 0x3348
#define EGL_SOCKET_HANDLE_NV 0x324C
#define EGL_SOCKET_TYPE_INET_NV 0x324F
#define EGL_SOCKET_TYPE_NV 0x324D
#define EGL_SOCKET_TYPE_UNIX_NV 0x324E
#define EGL_STREAM_BIT_KHR 0x0800
#define EGL_STREAM_CONSUMER_IMAGE_NV 0x3373
#define EGL_STREAM_CONSUMER_IMAGE_USE_SCANOUT_NV 0x3378
#define EGL_STREAM_CONSUMER_NV 0x3248
#define EGL_STREAM_CROSS_DISPLAY_NV 0x334E
#define EGL_STREAM_CROSS_OBJECT_NV 0x334D
#define EGL_STREAM_CROSS_PARTITION_NV 0x323F
#define EGL_STREAM_CROSS_PROCESS_NV 0x3245
#define EGL_STREAM_CROSS_SYSTEM_NV 0x334F
#define EGL_STREAM_DMA_NV 0x3371
#define EGL_STREAM_DMA_SERVER_NV 0x3372
#define EGL_STREAM_ENDPOINT_NV 0x3243
#define EGL_STREAM_FIFO_LENGTH_KHR 0x31FC
#define EGL_STREAM_FIFO_SYNCHRONOUS_NV 0x3336
#define EGL_STREAM_FRAME_MAJOR_AXIS_NV 0x3368
#define EGL_STREAM_FRAME_ORIGIN_X_NV 0x3366
#define EGL_STREAM_FRAME_ORIGIN_Y_NV 0x3367
#define EGL_STREAM_IMAGE_ADD_NV 0x3374
#define EGL_STREAM_IMAGE_AVAILABLE_NV 0x3376
#define EGL_STREAM_IMAGE_REMOVE_NV 0x3375
#define EGL_STREAM_LOCAL_NV 0x3244
#define EGL_STREAM_PRODUCER_NV 0x3247
#define EGL_STREAM_PROTOCOL_FD_NV 0x3246
#define EGL_STREAM_PROTOCOL_NV 0x3242
#define EGL_STREAM_PROTOCOL_SOCKET_NV 0x324B
#define EGL_STREAM_STATE_INITIALIZING_NV 0x3240
#define EGL_STREAM_TIME_CONSUMER_KHR 0x31FE
#define EGL_STREAM_TIME_NOW_KHR 0x31FD
#define EGL_STREAM_TIME_PENDING_NV 0x332A
#define EGL_STREAM_TIME_PRODUCER_KHR 0x31FF
#define EGL_STREAM_TYPE_NV 0x3241
#define EGL_SUPPORT_RESET_NV 0x3334
#define EGL_SUPPORT_REUSE_NV 0x3335
#define EGL_SURFACE_COMPRESSION_EXT 0x34B0
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT 0x34BD
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT 0x34BE
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT 0x34BF
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT 0x34B4
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT 0x34B5
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT 0x34B6
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT 0x34B7
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT 0x34B8
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT 0x34B9
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT 0x34BA
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT 0x34BB
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT 0x34BC
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT 0x34B2
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT 0x34B1
#define EGL_SURFACE_COMPRESSION_PLANE1_EXT 0x328E
#define EGL_SURFACE_COMPRESSION_PLANE2_EXT 0x328F
#define EGL_SWAP_INTERVAL_EXT 0x322F
#define EGL_SYNC_CL_EVENT_COMPLETE_KHR 0x30FF
#define EGL_SYNC_CL_EVENT_KHR 0x30FE
#define EGL_SYNC_CLIENT_EXT 0x3364
#define EGL_SYNC_CLIENT_SIGNAL_EXT 0x3365
#define EGL_SYNC_CUDA_EVENT_COMPLETE_NV 0x323D
#define EGL_SYNC_CUDA_EVENT_NV 0x323C
#define EGL_SYNC_NATIVE_FENCE_ANDROID 0x3144
#define EGL_SYNC_NATIVE_FENCE_FD_ANDROID 0x3145
#define EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID 0x3146
#define EGL_SYNC_NEW_FRAME_NV 0x321F
#define EGL_SYNC_PRIOR_COMMANDS_IMPLICIT_EXTERNAL_ARM 0x328A
#define EGL_TEXTURE_EXTERNAL_WL 0x31DA
#define EGL_TEXTURE_Y_U_V_WL 0x31D7
#define EGL_TEXTURE_Y_UV_WL 0x31D8
#define EGL_TEXTURE_Y_XUXV_WL 0x31D9
#define EGL_TIMESTAMP_INVALID_ANDROID EGL_CAST(EGLnsecsANDROID,-1)
#define EGL_TIMESTAMP_PENDING_ANDROID EGL_CAST(EGLnsecsANDROID,-2)
#define EGL_TIMESTAMPS_ANDROID 0x3430
#define EGL_TIZEN_image_native_buffer 1
#define EGL_TIZEN_image_native_surface 1
#define EGL_TOP_NV 0x336D
#define EGL_TRACK_REFERENCES_KHR 0x3352
#define EGL_TRIPLE_BUFFER_NV 0x3230
#define EGL_UPPER_LEFT_KHR 0x30CF
#define EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR 0x0040
#define EGL_VG_COLORSPACE_LINEAR_BIT_KHR 0x0020
#define EGL_VG_PARENT_IMAGE_KHR 0x30BA
#define EGL_WAYLAND_BUFFER_WL 0x31D5
#define EGL_WAYLAND_PLANE_WL 0x31D6
#define EGL_WAYLAND_Y_INVERTED_WL 0x31DB
#define EGL_WL_bind_wayland_display 1
#define EGL_WL_create_wayland_buffer_from_image 1
#define EGL_WRITE_SURFACE_BIT_KHR 0x0002
#define EGL_X_AXIS_NV 0x336F
#define EGL_Y_AXIS_NV 0x3370
#define EGL_Y_INVERTED_NOK 0x307F
#define EGL_YUV_BUFFER_EXT 0x3300
#define EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT 0x327D
#define EGL_YUV_CHROMA_SITING_0_5_EXT 0x3285
#define EGL_YUV_CHROMA_SITING_0_EXT 0x3284
#define EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT 0x327E
#define EGL_YUV_COLOR_SPACE_HINT_EXT 0x327B
#define EGL_YUV_CSC_STANDARD_2020_EXT 0x330D
#define EGL_YUV_CSC_STANDARD_601_EXT 0x330B
#define EGL_YUV_CSC_STANDARD_709_EXT 0x330C
#define EGL_YUV_CSC_STANDARD_EXT 0x330A
#define EGL_YUV_DEPTH_RANGE_EXT 0x3317
#define EGL_YUV_DEPTH_RANGE_FULL_EXT 0x3319
#define EGL_YUV_DEPTH_RANGE_LIMITED_EXT 0x3318
#define EGL_YUV_FULL_RANGE_EXT 0x3282
#define EGL_YUV_NARROW_RANGE_EXT 0x3283
#define EGL_YUV_NUMBER_OF_PLANES_EXT 0x3311
#define EGL_YUV_ORDER_AYUV_EXT 0x3308
#define EGL_YUV_ORDER_EXT 0x3301
#define EGL_YUV_ORDER_UYVY_EXT 0x3305
#define EGL_YUV_ORDER_VYUY_EXT 0x3307
#define EGL_YUV_ORDER_YUV_EXT 0x3302
#define EGL_YUV_ORDER_YUYV_EXT 0x3304
#define EGL_YUV_ORDER_YVU_EXT 0x3303
#define EGL_YUV_ORDER_YVYU_EXT 0x3306
#define EGL_YUV_PLANE0_TEXTURE_UNIT_NV 0x332C
#define EGL_YUV_PLANE1_TEXTURE_UNIT_NV 0x332D
#define EGL_YUV_PLANE2_TEXTURE_UNIT_NV 0x332E
#define EGL_YUV_PLANE_BPP_0_EXT 0x331B
#define EGL_YUV_PLANE_BPP_10_EXT 0x331D
#define EGL_YUV_PLANE_BPP_8_EXT 0x331C
#define EGL_YUV_PLANE_BPP_EXT 0x331A
#define EGL_YUV_SUBSAMPLE_4_2_0_EXT 0x3313
#define EGL_YUV_SUBSAMPLE_4_2_2_EXT 0x3314
#define EGL_YUV_SUBSAMPLE_4_4_4_EXT 0x3315
#define EGL_YUV_SUBSAMPLE_EXT 0x3312
#define PFNEGLBINDWAYLANDDISPLAYWL PFNEGLBINDWAYLANDDISPLAYWLPROC
#define PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWL PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC
#define PFNEGLQUERYWAYLANDBUFFERWL PFNEGLQUERYWAYLANDBUFFERWLPROC
#define PFNEGLUNBINDWAYLANDDISPLAYWL PFNEGLUNBINDWAYLANDDISPLAYWLPROC
Typedefs
typedef EGLenum const EGLAttribKHR * attrib_list
typedef EGLSurface EGLint attribute
typedef EGLStreamKHR EGLTime EGLenum EGLAttrib * aux
typedef EGLContext EGLenum EGLClientBuffer buffer
typedef const EGLint * context_attributes
typedef EGLStreamKHR EGLint EGLint EGLint const void * data
typedef EGLSurface EGLint EGLint * denominator
typedef EGLDeviceEXT * devices
typedef struct wl_display * display
typedef EGLNativeDisplayType * display_id
typedef intptr_t EGLAttribKHR
typedef void(EGLAPIENTRY * EGLDEBUGPROCKHR) (EGLenum error, const char *command, EGLint messageType, EGLLabelKHR threadLabel, EGLLabelKHR objectLabel, const char *message)
typedef void * EGLDeviceEXT
typedef EGLsizeiANDROID(* EGLGetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, void *value, EGLsizeiANDROID valueSize)
typedef void * EGLImageKHR
typedef void * EGLLabelKHR
typedef int EGLNativeFileDescriptorKHR
typedef khronos_stime_nanoseconds_t EGLnsecsANDROID
typedef void * EGLObjectKHR
typedef void * EGLOutputLayerEXT
typedef void * EGLOutputPortEXT
typedef void(* EGLSetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, const void *value, EGLsizeiANDROID valueSize)
typedef khronos_ssize_t EGLsizeiANDROID
typedef void * EGLStreamKHR
typedef void * EGLSyncKHR
typedef void * EGLSyncNV
typedef khronos_utime_nanoseconds_t EGLTimeKHR
typedef khronos_utime_nanoseconds_t EGLTimeNV
typedef khronos_uint64_t EGLuint64KHR
typedef khronos_utime_nanoseconds_t EGLuint64NV
typedef EGLStreamKHR EGLTime EGLenum * event
typedef EGLint EGLint EGLuint64KHR EGLBoolean * external_only
typedef const EGLint * external_win_ids
typedef EGLImageKHR int * fds
typedef EGLNativeFileDescriptorKHR file_descriptor
typedef EGLSyncKHR EGLint flags
typedef EGLint format
typedef EGLint EGLint * formats
typedef EGLImageKHR int * fourcc
typedef EGLSurface EGLuint64KHR * frameId
typedef EGLSetBlobFuncANDROID EGLGetBlobFuncANDROID get
typedef EGLImageKHR EGLint EGLint * handle
typedef EGLint EGLint height
typedef EGLImageKHR image
typedef EGLenum EGLObjectKHR EGLLabelKHR label
typedef EGLOutputLayerEXT layer
typedef const EGLAttrib EGLOutputLayerEXT * layers
typedef EGLint max_formats
typedef const EGLAttrib EGLOutputLayerEXT EGLint max_layers
typedef EGLint EGLint max_modifiers
typedef const EGLAttrib EGLOutputPortEXT EGLint max_ports
typedef EGLint EGLint max_size
typedef EGLint EGLint EGLuint64KHR * modifiers
typedef EGLStreamKHR EGLint n
typedef EGLSurface EGLint EGLint n_rects
typedef EGLint name
typedef EGLSurface EGLint const EGLint * names
typedef void * native_display
typedef EGLConfig void * native_pixmap
typedef EGLConfig void * native_window
typedef EGLDeviceEXT EGLint * num_devices
typedef EGLint num_entries
typedef EGLint EGLint EGLint * num_formats
typedef const EGLAttrib EGLOutputLayerEXT EGLint EGLint * num_layers
typedef EGLint EGLint EGLuint64KHR EGLBoolean EGLint * num_modifiers
typedef EGLImageKHR int int * num_planes
typedef const EGLAttrib EGLOutputPortEXT EGLint EGLint * num_ports
typedef EGLConfig const EGLAttrib EGLint EGLint EGLint * num_rates
typedef EGLSurface EGLint * numerator
typedef EGLSurface EGLint numRects
typedef EGLSurface EGLint numTimestamps
typedef EGLenum EGLObjectKHR object
typedef EGLenum objectType
typedef EGLStreamKHR EGLint EGLint offset
typedef EGLImageKHR int EGLint EGLint * offsets
typedef struct wl_buffer *EGLAPIENTRYP PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC(EGLDisplay dpy, EGLImageKHR image)
typedef char *EGLAPIENTRYP PFNEGLGETDISPLAYDRIVERCONFIGPROC(EGLDisplay dpy)
typedef const char *EGLAPIENTRYP PFNEGLGETDISPLAYDRIVERNAMEPROC(EGLDisplay dpy)
typedef const char *EGLAPIENTRYP PFNEGLQUERYDEVICESTRINGEXTPROC(EGLDeviceEXT device, EGLint name)
typedef const char *EGLAPIENTRYP PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint name)
typedef const char *EGLAPIENTRYP PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC(EGLDisplay dpy, EGLOutputPortEXT port, EGLint name)
typedef EGLStreamKHR EGLImage * pImage
typedef EGLConfig struct EGLClientPixmapHI * pixmap
typedef EGLint policy
typedef EGLOutputPortEXT port
typedef const EGLAttrib EGLOutputPortEXT * ports
typedef EGLConfig const EGLAttrib EGLint EGLint rate_size
typedef EGLConfig const EGLAttrib EGLint * rates
typedef EGLSurface EGLint * rects
typedef EGLSetBlobFuncANDROID set
typedef EGLStreamKHR stream
typedef EGLImageKHR EGLint EGLint EGLint * stride
typedef EGLImageKHR int EGLint * strides
typedef EGLSurface surf
typedef EGLSyncKHR sync
typedef EGLContext EGLenum target
typedef EGLSurface EGLnsecsANDROID time
typedef EGLStreamKHR EGLTime timeout
typedef EGLSurface EGLint timestamp
typedef EGLSurface EGLuint64KHR EGLint const EGLint * timestamps
typedef EGLStreamKHR EGLenum type
typedef EGLAttrib * value
typedef EGLSurface EGLint const EGLint EGLnsecsANDROID * values
typedef EGLint width
typedef EGLSurface EGLNativeWindowType * window
typedef const EGLint * window_attributes
typedef EGLSurface EGLint x
typedef EGLSurface EGLint EGLint y
Floating-point constants
typedef EGLint EGLint void EGLint * size
Functions
typedef EGLBoolean (EGLAPIENTRYP PFNEGLQUERYDEBUGKHRPROC)(EGLint attribute
typedef EGLClientBuffer (EGLAPIENTRYP PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC)(const EGLint *attrib_list)
typedef EGLDisplay (EGLAPIENTRYP PFNEGLGETPLATFORMDISPLAYEXTPROC)(EGLenum platform
typedef EGLImageKHR (EGLAPIENTRYP PFNEGLCREATEIMAGEKHRPROC)(EGLDisplay dpy
typedef EGLint (EGLAPIENTRYP PFNEGLDEBUGMESSAGECONTROLKHRPROC)(EGLDEBUGPROCKHR callback
typedef EGLNativeFileDescriptorKHR (EGLAPIENTRYP PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC)(EGLDisplay dpy
typedef EGLStreamKHR (EGLAPIENTRYP PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC)(EGLDisplay dpy
typedef EGLSurface (EGLAPIENTRYP PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC)(EGLDisplay dpy
typedef EGLSyncKHR (EGLAPIENTRYP PFNEGLCREATESYNC64KHRPROC)(EGLDisplay dpy
typedef void (EGLAPIENTRYP PFNEGLSETBLOBCACHEFUNCSANDROIDPROC)(EGLDisplay dpy
Macro Definition Documentation
EGL_ANDROID_blob_cache
#define EGL_ANDROID_blob_cache 1
EGL_ANDROID_create_native_client_buffer
#define EGL_ANDROID_create_native_client_buffer 1
EGL_ANDROID_framebuffer_target
#define EGL_ANDROID_framebuffer_target 1
EGL_ANDROID_front_buffer_auto_refresh
#define EGL_ANDROID_front_buffer_auto_refresh 1
EGL_ANDROID_get_frame_timestamps
#define EGL_ANDROID_get_frame_timestamps 1
EGL_ANDROID_get_native_client_buffer
#define EGL_ANDROID_get_native_client_buffer 1
EGL_ANDROID_GLES_layers
#define EGL_ANDROID_GLES_layers 1
EGL_ANDROID_image_native_buffer
#define EGL_ANDROID_image_native_buffer 1
EGL_ANDROID_native_fence_sync
#define EGL_ANDROID_native_fence_sync 1
EGL_ANDROID_presentation_time
#define EGL_ANDROID_presentation_time 1
EGL_ANDROID_recordable
#define EGL_ANDROID_recordable 1
EGL_ANGLE_d3d_share_handle_client_buffer
#define EGL_ANGLE_d3d_share_handle_client_buffer 1
EGL_ANGLE_device_d3d
#define EGL_ANGLE_device_d3d 1
EGL_ANGLE_query_surface_pointer
#define EGL_ANGLE_query_surface_pointer 1
EGL_ANGLE_surface_d3d_texture_2d_share_handle
#define EGL_ANGLE_surface_d3d_texture_2d_share_handle 1
EGL_ANGLE_sync_control_rate
#define EGL_ANGLE_sync_control_rate 1
EGL_ANGLE_window_fixed_size
#define EGL_ANGLE_window_fixed_size 1
EGL_ARM_image_format
#define EGL_ARM_image_format 1
EGL_ARM_implicit_external_sync
#define EGL_ARM_implicit_external_sync 1
EGL_ARM_pixmap_multisample_discard
#define EGL_ARM_pixmap_multisample_discard 1
EGL_AUTO_STEREO_NV
#define EGL_AUTO_STEREO_NV 0x3136
EGL_BAD_DEVICE_EXT
#define EGL_BAD_DEVICE_EXT 0x322B
EGL_BAD_OUTPUT_LAYER_EXT
#define EGL_BAD_OUTPUT_LAYER_EXT 0x322D
EGL_BAD_OUTPUT_PORT_EXT
#define EGL_BAD_OUTPUT_PORT_EXT 0x322E
EGL_BITMAP_ORIGIN_KHR
#define EGL_BITMAP_ORIGIN_KHR 0x30C8
EGL_BITMAP_PITCH_KHR
#define EGL_BITMAP_PITCH_KHR 0x30C7
EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR
#define EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR 0x30CC
EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR
#define EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR 0x30CB
EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR
#define EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR 0x30CA
EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR
#define EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR 0x30CD
EGL_BITMAP_PIXEL_RED_OFFSET_KHR
#define EGL_BITMAP_PIXEL_RED_OFFSET_KHR 0x30C9
EGL_BITMAP_PIXEL_SIZE_KHR
#define EGL_BITMAP_PIXEL_SIZE_KHR 0x3110
EGL_BITMAP_POINTER_KHR
#define EGL_BITMAP_POINTER_KHR 0x30C6
EGL_BOTTOM_NV
#define EGL_BOTTOM_NV 0x336E
EGL_BUFFER_AGE_EXT
#define EGL_BUFFER_AGE_EXT 0x313D
EGL_BUFFER_AGE_KHR
#define EGL_BUFFER_AGE_KHR 0x313D
EGL_CL_EVENT_HANDLE_KHR
#define EGL_CL_EVENT_HANDLE_KHR 0x309C
EGL_CLIENT_PIXMAP_POINTER_HI
#define EGL_CLIENT_PIXMAP_POINTER_HI 0x8F74
EGL_COLOR_ARGB_HI
#define EGL_COLOR_ARGB_HI 0x8F73
EGL_COLOR_COMPONENT_TYPE_EXT
#define EGL_COLOR_COMPONENT_TYPE_EXT 0x3339
EGL_COLOR_COMPONENT_TYPE_FIXED_EXT
#define EGL_COLOR_COMPONENT_TYPE_FIXED_EXT 0x333A
EGL_COLOR_COMPONENT_TYPE_FLOAT_EXT
#define EGL_COLOR_COMPONENT_TYPE_FLOAT_EXT 0x333B
EGL_COLOR_COMPONENT_TYPE_INTEGER_ARM
#define EGL_COLOR_COMPONENT_TYPE_INTEGER_ARM 0x3288
EGL_COLOR_COMPONENT_TYPE_UNSIGNED_INTEGER_ARM
#define EGL_COLOR_COMPONENT_TYPE_UNSIGNED_INTEGER_ARM 0x3287
EGL_COLOR_FORMAT_HI
#define EGL_COLOR_FORMAT_HI 0x8F70
EGL_COLOR_RGB_HI
#define EGL_COLOR_RGB_HI 0x8F71
EGL_COLOR_RGBA_HI
#define EGL_COLOR_RGBA_HI 0x8F72
EGL_COMPOSITE_DEADLINE_ANDROID
#define EGL_COMPOSITE_DEADLINE_ANDROID 0x3431
EGL_COMPOSITE_INTERVAL_ANDROID
#define EGL_COMPOSITE_INTERVAL_ANDROID 0x3432
EGL_COMPOSITE_TO_PRESENT_LATENCY_ANDROID
#define EGL_COMPOSITE_TO_PRESENT_LATENCY_ANDROID 0x3433
EGL_COMPOSITION_LATCH_TIME_ANDROID
#define EGL_COMPOSITION_LATCH_TIME_ANDROID 0x3436
EGL_COMPOSITOR_DROP_NEWEST_FRAME_EXT
#define EGL_COMPOSITOR_DROP_NEWEST_FRAME_EXT 0x3462
EGL_COMPOSITOR_KEEP_NEWEST_FRAME_EXT
#define EGL_COMPOSITOR_KEEP_NEWEST_FRAME_EXT 0x3463
EGL_CONFIG_SELECT_GROUP_EXT
#define EGL_CONFIG_SELECT_GROUP_EXT 0x34C0
EGL_CONFORMANT_KHR
#define EGL_CONFORMANT_KHR 0x3042
EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR
#define EGL_CONSUMER_ACQUIRE_TIMEOUT_USEC_KHR 0x321E
EGL_CONSUMER_AUTO_ORIENTATION_NV
#define EGL_CONSUMER_AUTO_ORIENTATION_NV 0x3369
EGL_CONSUMER_MAX_FRAME_HINT_NV
#define EGL_CONSUMER_MAX_FRAME_HINT_NV 0x3338
EGL_CONSUMER_METADATA_NV
#define EGL_CONSUMER_METADATA_NV 0x3254
EGL_CONTEXT_FLAGS_KHR
#define EGL_CONTEXT_FLAGS_KHR 0x30FC
EGL_CONTEXT_MAJOR_VERSION_KHR
#define EGL_CONTEXT_MAJOR_VERSION_KHR 0x3098
EGL_CONTEXT_MINOR_VERSION_KHR
#define EGL_CONTEXT_MINOR_VERSION_KHR 0x30FB
EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR 0x00000002
EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR 0x00000001
EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR
#define EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR 0x00000001
EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR 0x00000002
EGL_CONTEXT_OPENGL_NO_ERROR_KHR
#define EGL_CONTEXT_OPENGL_NO_ERROR_KHR 0x31B3
EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR
#define EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR 0x30FD
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_EXT 0x3138
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR 0x31BD
EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR 0x00000004
EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS_EXT 0x30BF
EGL_CONTEXT_PRIORITY_HIGH_IMG
#define EGL_CONTEXT_PRIORITY_HIGH_IMG 0x3101
EGL_CONTEXT_PRIORITY_LEVEL_IMG
#define EGL_CONTEXT_PRIORITY_LEVEL_IMG 0x3100
EGL_CONTEXT_PRIORITY_LOW_IMG
#define EGL_CONTEXT_PRIORITY_LOW_IMG 0x3103
EGL_CONTEXT_PRIORITY_MEDIUM_IMG
#define EGL_CONTEXT_PRIORITY_MEDIUM_IMG 0x3102
EGL_CONTEXT_PRIORITY_REALTIME_NV
#define EGL_CONTEXT_PRIORITY_REALTIME_NV 0x3357
EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR
#define EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR 0x2098
EGL_CONTEXT_RELEASE_BEHAVIOR_KHR
#define EGL_CONTEXT_RELEASE_BEHAVIOR_KHR 0x2097
EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR
#define EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR 0
EGL_COVERAGE_BUFFERS_NV
#define EGL_COVERAGE_BUFFERS_NV 0x30E0
EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV
#define EGL_COVERAGE_SAMPLE_RESOLVE_DEFAULT_NV 0x3132
EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV
#define EGL_COVERAGE_SAMPLE_RESOLVE_NONE_NV 0x3133
EGL_COVERAGE_SAMPLE_RESOLVE_NV
#define EGL_COVERAGE_SAMPLE_RESOLVE_NV 0x3131
EGL_COVERAGE_SAMPLES_NV
#define EGL_COVERAGE_SAMPLES_NV 0x30E1
EGL_CTA861_3_MAX_CONTENT_LIGHT_LEVEL_EXT
#define EGL_CTA861_3_MAX_CONTENT_LIGHT_LEVEL_EXT 0x3360
EGL_CTA861_3_MAX_FRAME_AVERAGE_LEVEL_EXT
#define EGL_CTA861_3_MAX_FRAME_AVERAGE_LEVEL_EXT 0x3361
EGL_CUDA_DEVICE_NV
#define EGL_CUDA_DEVICE_NV 0x323A
EGL_CUDA_EVENT_HANDLE_NV
#define EGL_CUDA_EVENT_HANDLE_NV 0x323B
EGL_D3D11_DEVICE_ANGLE
#define EGL_D3D11_DEVICE_ANGLE 0x33A1
EGL_D3D9_DEVICE_ANGLE
#define EGL_D3D9_DEVICE_ANGLE 0x33A0
EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE
#define EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE 0x3200
EGL_DEBUG_CALLBACK_KHR
#define EGL_DEBUG_CALLBACK_KHR 0x33B8
EGL_DEBUG_MSG_CRITICAL_KHR
#define EGL_DEBUG_MSG_CRITICAL_KHR 0x33B9
EGL_DEBUG_MSG_ERROR_KHR
#define EGL_DEBUG_MSG_ERROR_KHR 0x33BA
EGL_DEBUG_MSG_INFO_KHR
#define EGL_DEBUG_MSG_INFO_KHR 0x33BC
EGL_DEBUG_MSG_WARN_KHR
#define EGL_DEBUG_MSG_WARN_KHR 0x33BB
EGL_DEPTH_ENCODING_NONE_NV
#define EGL_DEPTH_ENCODING_NONE_NV 0
EGL_DEPTH_ENCODING_NONLINEAR_NV
#define EGL_DEPTH_ENCODING_NONLINEAR_NV 0x30E3
EGL_DEPTH_ENCODING_NV
#define EGL_DEPTH_ENCODING_NV 0x30E2
EGL_DEQUEUE_READY_TIME_ANDROID
#define EGL_DEQUEUE_READY_TIME_ANDROID 0x343B
EGL_DEVICE_EXT
#define EGL_DEVICE_EXT 0x322C
EGL_DEVICE_UUID_EXT
#define EGL_DEVICE_UUID_EXT 0x335C
EGL_DISCARD_SAMPLES_ARM
#define EGL_DISCARD_SAMPLES_ARM 0x3286
EGL_DISPLAY_PRESENT_TIME_ANDROID
#define EGL_DISPLAY_PRESENT_TIME_ANDROID 0x343A
EGL_DMA_BUF_PLANE0_FD_EXT
#define EGL_DMA_BUF_PLANE0_FD_EXT 0x3272
EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT
#define EGL_DMA_BUF_PLANE0_MODIFIER_HI_EXT 0x3444
EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT
#define EGL_DMA_BUF_PLANE0_MODIFIER_LO_EXT 0x3443
EGL_DMA_BUF_PLANE0_OFFSET_EXT
#define EGL_DMA_BUF_PLANE0_OFFSET_EXT 0x3273
EGL_DMA_BUF_PLANE0_PITCH_EXT
#define EGL_DMA_BUF_PLANE0_PITCH_EXT 0x3274
EGL_DMA_BUF_PLANE1_FD_EXT
#define EGL_DMA_BUF_PLANE1_FD_EXT 0x3275
EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT
#define EGL_DMA_BUF_PLANE1_MODIFIER_HI_EXT 0x3446
EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT
#define EGL_DMA_BUF_PLANE1_MODIFIER_LO_EXT 0x3445
EGL_DMA_BUF_PLANE1_OFFSET_EXT
#define EGL_DMA_BUF_PLANE1_OFFSET_EXT 0x3276
EGL_DMA_BUF_PLANE1_PITCH_EXT
#define EGL_DMA_BUF_PLANE1_PITCH_EXT 0x3277
EGL_DMA_BUF_PLANE2_FD_EXT
#define EGL_DMA_BUF_PLANE2_FD_EXT 0x3278
EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT
#define EGL_DMA_BUF_PLANE2_MODIFIER_HI_EXT 0x3448
EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT
#define EGL_DMA_BUF_PLANE2_MODIFIER_LO_EXT 0x3447
EGL_DMA_BUF_PLANE2_OFFSET_EXT
#define EGL_DMA_BUF_PLANE2_OFFSET_EXT 0x3279
EGL_DMA_BUF_PLANE2_PITCH_EXT
#define EGL_DMA_BUF_PLANE2_PITCH_EXT 0x327A
EGL_DMA_BUF_PLANE3_FD_EXT
#define EGL_DMA_BUF_PLANE3_FD_EXT 0x3440
EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT
#define EGL_DMA_BUF_PLANE3_MODIFIER_HI_EXT 0x344A
EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT
#define EGL_DMA_BUF_PLANE3_MODIFIER_LO_EXT 0x3449
EGL_DMA_BUF_PLANE3_OFFSET_EXT
#define EGL_DMA_BUF_PLANE3_OFFSET_EXT 0x3441
EGL_DMA_BUF_PLANE3_PITCH_EXT
#define EGL_DMA_BUF_PLANE3_PITCH_EXT 0x3442
EGL_DRIVER_NAME_EXT
#define EGL_DRIVER_NAME_EXT 0x335E
EGL_DRIVER_UUID_EXT
#define EGL_DRIVER_UUID_EXT 0x335D
EGL_DRM_BUFFER_FORMAT_ARGB32_MESA
#define EGL_DRM_BUFFER_FORMAT_ARGB32_MESA 0x31D2
EGL_DRM_BUFFER_FORMAT_MESA
#define EGL_DRM_BUFFER_FORMAT_MESA 0x31D0
EGL_DRM_BUFFER_MESA
#define EGL_DRM_BUFFER_MESA 0x31D3
EGL_DRM_BUFFER_STRIDE_MESA
#define EGL_DRM_BUFFER_STRIDE_MESA 0x31D4
EGL_DRM_BUFFER_USE_CURSOR_MESA
#define EGL_DRM_BUFFER_USE_CURSOR_MESA 0x00000004
EGL_DRM_BUFFER_USE_MESA
#define EGL_DRM_BUFFER_USE_MESA 0x31D1
EGL_DRM_BUFFER_USE_SCANOUT_MESA
#define EGL_DRM_BUFFER_USE_SCANOUT_MESA 0x00000001
EGL_DRM_BUFFER_USE_SHARE_MESA
#define EGL_DRM_BUFFER_USE_SHARE_MESA 0x00000002
EGL_DRM_CONNECTOR_EXT
#define EGL_DRM_CONNECTOR_EXT 0x3236
EGL_DRM_CRTC_EXT
#define EGL_DRM_CRTC_EXT 0x3234
EGL_DRM_DEVICE_FILE_EXT
#define EGL_DRM_DEVICE_FILE_EXT 0x3233
EGL_DRM_MASTER_FD_EXT
#define EGL_DRM_MASTER_FD_EXT 0x333C
EGL_DRM_PLANE_EXT
#define EGL_DRM_PLANE_EXT 0x3235
EGL_DRM_RENDER_NODE_FILE_EXT
#define EGL_DRM_RENDER_NODE_FILE_EXT 0x3377
EGL_EGLEXT_VERSION
#define EGL_EGLEXT_VERSION 20231215
EGL_EXT_bind_to_front
#define EGL_EXT_bind_to_front 1
EGL_EXT_buffer_age
#define EGL_EXT_buffer_age 1
EGL_EXT_client_extensions
#define EGL_EXT_client_extensions 1
EGL_EXT_client_sync
#define EGL_EXT_client_sync 1
EGL_EXT_compositor
#define EGL_EXT_compositor 1
EGL_EXT_config_select_group
#define EGL_EXT_config_select_group 1
EGL_EXT_create_context_robustness
#define EGL_EXT_create_context_robustness 1
EGL_EXT_device_base
#define EGL_EXT_device_base 1
EGL_EXT_device_drm
#define EGL_EXT_device_drm 1
EGL_EXT_device_drm_render_node
#define EGL_EXT_device_drm_render_node 1
EGL_EXT_device_enumeration
#define EGL_EXT_device_enumeration 1
EGL_EXT_device_openwf
#define EGL_EXT_device_openwf 1
EGL_EXT_device_persistent_id
#define EGL_EXT_device_persistent_id 1
EGL_EXT_device_query
#define EGL_EXT_device_query 1
EGL_EXT_device_query_name
#define EGL_EXT_device_query_name 1
EGL_EXT_explicit_device
#define EGL_EXT_explicit_device 1
EGL_EXT_gl_colorspace_bt2020_hlg
#define EGL_EXT_gl_colorspace_bt2020_hlg 1
EGL_EXT_gl_colorspace_bt2020_linear
#define EGL_EXT_gl_colorspace_bt2020_linear 1
EGL_EXT_gl_colorspace_bt2020_pq
#define EGL_EXT_gl_colorspace_bt2020_pq 1
EGL_EXT_gl_colorspace_display_p3
#define EGL_EXT_gl_colorspace_display_p3 1
EGL_EXT_gl_colorspace_display_p3_linear
#define EGL_EXT_gl_colorspace_display_p3_linear 1
EGL_EXT_gl_colorspace_display_p3_passthrough
#define EGL_EXT_gl_colorspace_display_p3_passthrough 1
EGL_EXT_gl_colorspace_scrgb
#define EGL_EXT_gl_colorspace_scrgb 1
EGL_EXT_gl_colorspace_scrgb_linear
#define EGL_EXT_gl_colorspace_scrgb_linear 1
EGL_EXT_image_dma_buf_import
#define EGL_EXT_image_dma_buf_import 1
EGL_EXT_image_dma_buf_import_modifiers
#define EGL_EXT_image_dma_buf_import_modifiers 1
EGL_EXT_image_gl_colorspace
#define EGL_EXT_image_gl_colorspace 1
EGL_EXT_image_implicit_sync_control
#define EGL_EXT_image_implicit_sync_control 1
EGL_EXT_multiview_window
#define EGL_EXT_multiview_window 1
EGL_EXT_output_base
#define EGL_EXT_output_base 1
EGL_EXT_output_drm
#define EGL_EXT_output_drm 1
EGL_EXT_output_openwf
#define EGL_EXT_output_openwf 1
EGL_EXT_pixel_format_float
#define EGL_EXT_pixel_format_float 1
EGL_EXT_platform_base
#define EGL_EXT_platform_base 1
EGL_EXT_platform_device
#define EGL_EXT_platform_device 1
EGL_EXT_platform_wayland
#define EGL_EXT_platform_wayland 1
EGL_EXT_platform_x11
#define EGL_EXT_platform_x11 1
EGL_EXT_platform_xcb
#define EGL_EXT_platform_xcb 1
EGL_EXT_present_opaque
#define EGL_EXT_present_opaque 1
EGL_EXT_protected_content
#define EGL_EXT_protected_content 1
EGL_EXT_protected_surface
#define EGL_EXT_protected_surface 1
EGL_EXT_query_reset_notification_strategy
#define EGL_EXT_query_reset_notification_strategy 1
EGL_EXT_stream_consumer_egloutput
#define EGL_EXT_stream_consumer_egloutput 1
EGL_EXT_surface_compression
#define EGL_EXT_surface_compression 1
EGL_EXT_surface_CTA861_3_metadata
#define EGL_EXT_surface_CTA861_3_metadata 1
EGL_EXT_surface_SMPTE2086_metadata
#define EGL_EXT_surface_SMPTE2086_metadata 1
EGL_EXT_swap_buffers_with_damage
#define EGL_EXT_swap_buffers_with_damage 1
EGL_EXT_sync_reuse
#define EGL_EXT_sync_reuse 1
EGL_EXT_yuv_surface
#define EGL_EXT_yuv_surface 1
EGL_EXTERNAL_REF_ID_EXT
#define EGL_EXTERNAL_REF_ID_EXT 0x3461
EGL_FIRST_COMPOSITION_GPU_FINISHED_TIME_ANDROID
#define EGL_FIRST_COMPOSITION_GPU_FINISHED_TIME_ANDROID 0x3439
EGL_FIRST_COMPOSITION_START_TIME_ANDROID
#define EGL_FIRST_COMPOSITION_START_TIME_ANDROID 0x3437
EGL_FIXED_SIZE_ANGLE
#define EGL_FIXED_SIZE_ANGLE 0x3201
EGL_FORMAT_RGB_565_EXACT_KHR
#define EGL_FORMAT_RGB_565_EXACT_KHR 0x30C0
EGL_FORMAT_RGB_565_KHR
#define EGL_FORMAT_RGB_565_KHR 0x30C1
EGL_FORMAT_RGBA_8888_EXACT_KHR
#define EGL_FORMAT_RGBA_8888_EXACT_KHR 0x30C2
EGL_FORMAT_RGBA_8888_KHR
#define EGL_FORMAT_RGBA_8888_KHR 0x30C3
EGL_FRAMEBUFFER_TARGET_ANDROID
#define EGL_FRAMEBUFFER_TARGET_ANDROID 0x3147
EGL_FRONT_BUFFER_AUTO_REFRESH_ANDROID
#define EGL_FRONT_BUFFER_AUTO_REFRESH_ANDROID 0x314C
EGL_FRONT_BUFFER_EXT
#define EGL_FRONT_BUFFER_EXT 0x3464
EGL_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV
#define EGL_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV 0x334C
EGL_GL_COLORSPACE_BT2020_HLG_EXT
#define EGL_GL_COLORSPACE_BT2020_HLG_EXT 0x3540
EGL_GL_COLORSPACE_BT2020_LINEAR_EXT
#define EGL_GL_COLORSPACE_BT2020_LINEAR_EXT 0x333F
EGL_GL_COLORSPACE_BT2020_PQ_EXT
#define EGL_GL_COLORSPACE_BT2020_PQ_EXT 0x3340
EGL_GL_COLORSPACE_DEFAULT_EXT
#define EGL_GL_COLORSPACE_DEFAULT_EXT 0x314D
EGL_GL_COLORSPACE_DISPLAY_P3_EXT
#define EGL_GL_COLORSPACE_DISPLAY_P3_EXT 0x3363
EGL_GL_COLORSPACE_DISPLAY_P3_LINEAR_EXT
#define EGL_GL_COLORSPACE_DISPLAY_P3_LINEAR_EXT 0x3362
EGL_GL_COLORSPACE_DISPLAY_P3_PASSTHROUGH_EXT
#define EGL_GL_COLORSPACE_DISPLAY_P3_PASSTHROUGH_EXT 0x3490
EGL_GL_COLORSPACE_KHR
#define EGL_GL_COLORSPACE_KHR 0x309D
EGL_GL_COLORSPACE_LINEAR_KHR
#define EGL_GL_COLORSPACE_LINEAR_KHR 0x308A
EGL_GL_COLORSPACE_SCRGB_EXT
#define EGL_GL_COLORSPACE_SCRGB_EXT 0x3351
EGL_GL_COLORSPACE_SCRGB_LINEAR_EXT
#define EGL_GL_COLORSPACE_SCRGB_LINEAR_EXT 0x3350
EGL_GL_COLORSPACE_SRGB_KHR
#define EGL_GL_COLORSPACE_SRGB_KHR 0x3089
EGL_GL_RENDERBUFFER_KHR
#define EGL_GL_RENDERBUFFER_KHR 0x30B9
EGL_GL_TEXTURE_2D_KHR
#define EGL_GL_TEXTURE_2D_KHR 0x30B1
EGL_GL_TEXTURE_3D_KHR
#define EGL_GL_TEXTURE_3D_KHR 0x30B2
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X_KHR 0x30B4
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_KHR 0x30B6
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_KHR 0x30B8
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X_KHR 0x30B3
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y_KHR 0x30B5
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z_KHR 0x30B7
EGL_GL_TEXTURE_LEVEL_KHR
#define EGL_GL_TEXTURE_LEVEL_KHR 0x30BC
EGL_GL_TEXTURE_ZOFFSET_KHR
#define EGL_GL_TEXTURE_ZOFFSET_KHR 0x30BD
EGL_HI_clientpixmap
#define EGL_HI_clientpixmap 1
EGL_HI_colorformats
#define EGL_HI_colorformats 1
EGL_IMAGE_PRESERVED_KHR
#define EGL_IMAGE_PRESERVED_KHR 0x30D2
EGL_IMG_context_priority
#define EGL_IMG_context_priority 1
EGL_IMG_image_plane_attribs
#define EGL_IMG_image_plane_attribs 1
EGL_IMPORT_EXPLICIT_SYNC_EXT
#define EGL_IMPORT_EXPLICIT_SYNC_EXT 0x3472
EGL_IMPORT_IMPLICIT_SYNC_EXT
#define EGL_IMPORT_IMPLICIT_SYNC_EXT 0x3471
EGL_IMPORT_SYNC_TYPE_EXT
#define EGL_IMPORT_SYNC_TYPE_EXT 0x3470
EGL_ITU_REC2020_EXT
#define EGL_ITU_REC2020_EXT 0x3281
EGL_ITU_REC601_EXT
#define EGL_ITU_REC601_EXT 0x327F
EGL_ITU_REC709_EXT
#define EGL_ITU_REC709_EXT 0x3280
EGL_KHR_cl_event
#define EGL_KHR_cl_event 1
EGL_KHR_cl_event2
#define EGL_KHR_cl_event2 1
EGL_KHR_client_get_all_proc_addresses
#define EGL_KHR_client_get_all_proc_addresses 1
EGL_KHR_config_attribs
#define EGL_KHR_config_attribs 1
EGL_KHR_context_flush_control
#define EGL_KHR_context_flush_control 1
EGL_KHR_create_context
#define EGL_KHR_create_context 1
EGL_KHR_create_context_no_error
#define EGL_KHR_create_context_no_error 1
EGL_KHR_debug
#define EGL_KHR_debug 1
EGL_KHR_display_reference
#define EGL_KHR_display_reference 1
EGL_KHR_fence_sync
#define EGL_KHR_fence_sync 1
EGL_KHR_get_all_proc_addresses
#define EGL_KHR_get_all_proc_addresses 1
EGL_KHR_gl_colorspace
#define EGL_KHR_gl_colorspace 1
EGL_KHR_gl_renderbuffer_image
#define EGL_KHR_gl_renderbuffer_image 1
EGL_KHR_gl_texture_2D_image
#define EGL_KHR_gl_texture_2D_image 1
EGL_KHR_gl_texture_3D_image
#define EGL_KHR_gl_texture_3D_image 1
EGL_KHR_gl_texture_cubemap_image
#define EGL_KHR_gl_texture_cubemap_image 1
EGL_KHR_image
#define EGL_KHR_image 1
EGL_KHR_image_base
#define EGL_KHR_image_base 1
EGL_KHR_image_pixmap
#define EGL_KHR_image_pixmap 1
EGL_KHR_lock_surface
#define EGL_KHR_lock_surface 1
EGL_KHR_lock_surface2
#define EGL_KHR_lock_surface2 1
EGL_KHR_lock_surface3
#define EGL_KHR_lock_surface3 1
EGL_KHR_mutable_render_buffer
#define EGL_KHR_mutable_render_buffer 1
EGL_KHR_no_config_context
#define EGL_KHR_no_config_context 1
EGL_KHR_partial_update
#define EGL_KHR_partial_update 1
EGL_KHR_platform_android
#define EGL_KHR_platform_android 1
EGL_KHR_platform_gbm
#define EGL_KHR_platform_gbm 1
EGL_KHR_platform_wayland
#define EGL_KHR_platform_wayland 1
EGL_KHR_platform_x11
#define EGL_KHR_platform_x11 1
EGL_KHR_reusable_sync
#define EGL_KHR_reusable_sync 1
EGL_KHR_stream
#define EGL_KHR_stream 1
EGL_KHR_stream_attrib
#define EGL_KHR_stream_attrib 1
EGL_KHR_stream_consumer_gltexture
#define EGL_KHR_stream_consumer_gltexture 1
EGL_KHR_stream_cross_process_fd
#define EGL_KHR_stream_cross_process_fd 1
EGL_KHR_stream_fifo
#define EGL_KHR_stream_fifo 1
EGL_KHR_stream_producer_aldatalocator
#define EGL_KHR_stream_producer_aldatalocator 1
EGL_KHR_stream_producer_eglsurface
#define EGL_KHR_stream_producer_eglsurface 1
EGL_KHR_surfaceless_context
#define EGL_KHR_surfaceless_context 1
EGL_KHR_swap_buffers_with_damage
#define EGL_KHR_swap_buffers_with_damage 1
EGL_KHR_vg_parent_image
#define EGL_KHR_vg_parent_image 1
EGL_KHR_wait_sync
#define EGL_KHR_wait_sync 1
EGL_LAST_COMPOSITION_START_TIME_ANDROID
#define EGL_LAST_COMPOSITION_START_TIME_ANDROID 0x3438
EGL_LEFT_NV
#define EGL_LEFT_NV 0x336B
EGL_LINUX_DMA_BUF_EXT
#define EGL_LINUX_DMA_BUF_EXT 0x3270
EGL_LINUX_DRM_FOURCC_EXT
#define EGL_LINUX_DRM_FOURCC_EXT 0x3271
EGL_LOCK_SURFACE_BIT_KHR
#define EGL_LOCK_SURFACE_BIT_KHR 0x0080
EGL_LOCK_USAGE_HINT_KHR
#define EGL_LOCK_USAGE_HINT_KHR 0x30C5
EGL_LOSE_CONTEXT_ON_RESET_EXT
#define EGL_LOSE_CONTEXT_ON_RESET_EXT 0x31BF
EGL_LOSE_CONTEXT_ON_RESET_KHR
#define EGL_LOSE_CONTEXT_ON_RESET_KHR 0x31BF
EGL_LOWER_LEFT_KHR
#define EGL_LOWER_LEFT_KHR 0x30CE
EGL_MAP_PRESERVE_PIXELS_KHR
#define EGL_MAP_PRESERVE_PIXELS_KHR 0x30C4
EGL_MATCH_FORMAT_KHR
#define EGL_MATCH_FORMAT_KHR 0x3043
EGL_MAX_STREAM_METADATA_BLOCK_SIZE_NV
#define EGL_MAX_STREAM_METADATA_BLOCK_SIZE_NV 0x3251
EGL_MAX_STREAM_METADATA_BLOCKS_NV
#define EGL_MAX_STREAM_METADATA_BLOCKS_NV 0x3250
EGL_MAX_STREAM_METADATA_TOTAL_SIZE_NV
#define EGL_MAX_STREAM_METADATA_TOTAL_SIZE_NV 0x3252
EGL_MESA_drm_image
#define EGL_MESA_drm_image 1
EGL_MESA_image_dma_buf_export
#define EGL_MESA_image_dma_buf_export 1
EGL_MESA_platform_gbm
#define EGL_MESA_platform_gbm 1
EGL_MESA_platform_surfaceless
#define EGL_MESA_platform_surfaceless 1
EGL_MESA_query_driver
#define EGL_MESA_query_driver 1
EGL_METADATA0_SIZE_NV
#define EGL_METADATA0_SIZE_NV 0x3255
EGL_METADATA0_TYPE_NV
#define EGL_METADATA0_TYPE_NV 0x3259
EGL_METADATA1_SIZE_NV
#define EGL_METADATA1_SIZE_NV 0x3256
EGL_METADATA1_TYPE_NV
#define EGL_METADATA1_TYPE_NV 0x325A
EGL_METADATA2_SIZE_NV
#define EGL_METADATA2_SIZE_NV 0x3257
EGL_METADATA2_TYPE_NV
#define EGL_METADATA2_TYPE_NV 0x325B
EGL_METADATA3_SIZE_NV
#define EGL_METADATA3_SIZE_NV 0x3258
EGL_METADATA3_TYPE_NV
#define EGL_METADATA3_TYPE_NV 0x325C
EGL_METADATA_SCALING_EXT
#define EGL_METADATA_SCALING_EXT 50000
EGL_MULTIVIEW_VIEW_COUNT_EXT
#define EGL_MULTIVIEW_VIEW_COUNT_EXT 0x3134
EGL_MUTABLE_RENDER_BUFFER_BIT_KHR
#define EGL_MUTABLE_RENDER_BUFFER_BIT_KHR 0x1000
EGL_NATIVE_BUFFER_ANDROID
#define EGL_NATIVE_BUFFER_ANDROID 0x3140
EGL_NATIVE_BUFFER_MULTIPLANE_SEPARATE_IMG
#define EGL_NATIVE_BUFFER_MULTIPLANE_SEPARATE_IMG 0x3105
EGL_NATIVE_BUFFER_PLANE_OFFSET_IMG
#define EGL_NATIVE_BUFFER_PLANE_OFFSET_IMG 0x3106
EGL_NATIVE_BUFFER_QNX
#define EGL_NATIVE_BUFFER_QNX 0x3551
EGL_NATIVE_BUFFER_TIZEN
#define EGL_NATIVE_BUFFER_TIZEN 0x32A0
EGL_NATIVE_BUFFER_USAGE_ANDROID
#define EGL_NATIVE_BUFFER_USAGE_ANDROID 0x3143
EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID
#define EGL_NATIVE_BUFFER_USAGE_PROTECTED_BIT_ANDROID 0x00000001
EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID
#define EGL_NATIVE_BUFFER_USAGE_RENDERBUFFER_BIT_ANDROID 0x00000002
EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID
#define EGL_NATIVE_BUFFER_USAGE_TEXTURE_BIT_ANDROID 0x00000004
EGL_NATIVE_PIXMAP_KHR
#define EGL_NATIVE_PIXMAP_KHR 0x30B0
EGL_NATIVE_SURFACE_TIZEN
#define EGL_NATIVE_SURFACE_TIZEN 0x32A1
EGL_NO_CONFIG_KHR
#define EGL_NO_CONFIG_KHR EGL_CAST(EGLConfig,0)
EGL_NO_DEVICE_EXT
#define EGL_NO_DEVICE_EXT EGL_CAST(EGLDeviceEXT,0)
EGL_NO_FILE_DESCRIPTOR_KHR
#define EGL_NO_FILE_DESCRIPTOR_KHR EGL_CAST(EGLNativeFileDescriptorKHR,-1)
EGL_NO_IMAGE_KHR
#define EGL_NO_IMAGE_KHR EGL_CAST(EGLImageKHR,0)
EGL_NO_NATIVE_FENCE_FD_ANDROID
#define EGL_NO_NATIVE_FENCE_FD_ANDROID -1
EGL_NO_OUTPUT_LAYER_EXT
#define EGL_NO_OUTPUT_LAYER_EXT EGL_CAST(EGLOutputLayerEXT,0)
EGL_NO_OUTPUT_PORT_EXT
#define EGL_NO_OUTPUT_PORT_EXT EGL_CAST(EGLOutputPortEXT,0)
EGL_NO_RESET_NOTIFICATION_EXT
#define EGL_NO_RESET_NOTIFICATION_EXT 0x31BE
EGL_NO_RESET_NOTIFICATION_KHR
#define EGL_NO_RESET_NOTIFICATION_KHR 0x31BE
EGL_NOK_swap_region
#define EGL_NOK_swap_region 1
EGL_NOK_swap_region2
#define EGL_NOK_swap_region2 1
EGL_NOK_texture_from_pixmap
#define EGL_NOK_texture_from_pixmap 1
EGL_NV_3dvision_surface
#define EGL_NV_3dvision_surface 1
EGL_NV_context_priority_realtime
#define EGL_NV_context_priority_realtime 1
EGL_NV_coverage_sample
#define EGL_NV_coverage_sample 1
EGL_NV_coverage_sample_resolve
#define EGL_NV_coverage_sample_resolve 1
EGL_NV_cuda_event
#define EGL_NV_cuda_event 1
EGL_NV_depth_nonlinear
#define EGL_NV_depth_nonlinear 1
EGL_NV_device_cuda
#define EGL_NV_device_cuda 1
EGL_NV_native_query
#define EGL_NV_native_query 1
EGL_NV_post_convert_rounding
#define EGL_NV_post_convert_rounding 1
EGL_NV_post_sub_buffer
#define EGL_NV_post_sub_buffer 1
EGL_NV_quadruple_buffer
#define EGL_NV_quadruple_buffer 1
EGL_NV_robustness_video_memory_purge
#define EGL_NV_robustness_video_memory_purge 1
EGL_NV_stream_consumer_eglimage
#define EGL_NV_stream_consumer_eglimage 1
EGL_NV_stream_consumer_eglimage_use_scanout_attrib
#define EGL_NV_stream_consumer_eglimage_use_scanout_attrib 1
EGL_NV_stream_consumer_gltexture_yuv
#define EGL_NV_stream_consumer_gltexture_yuv 1
EGL_NV_stream_cross_display
#define EGL_NV_stream_cross_display 1
EGL_NV_stream_cross_object
#define EGL_NV_stream_cross_object 1
EGL_NV_stream_cross_partition
#define EGL_NV_stream_cross_partition 1
EGL_NV_stream_cross_process
#define EGL_NV_stream_cross_process 1
EGL_NV_stream_cross_system
#define EGL_NV_stream_cross_system 1
EGL_NV_stream_dma
#define EGL_NV_stream_dma 1
EGL_NV_stream_fifo_next
#define EGL_NV_stream_fifo_next 1
EGL_NV_stream_fifo_synchronous
#define EGL_NV_stream_fifo_synchronous 1
EGL_NV_stream_flush
#define EGL_NV_stream_flush 1
EGL_NV_stream_frame_limits
#define EGL_NV_stream_frame_limits 1
EGL_NV_stream_metadata
#define EGL_NV_stream_metadata 1
EGL_NV_stream_origin
#define EGL_NV_stream_origin 1
EGL_NV_stream_remote
#define EGL_NV_stream_remote 1
EGL_NV_stream_reset
#define EGL_NV_stream_reset 1
EGL_NV_stream_socket
#define EGL_NV_stream_socket 1
EGL_NV_stream_socket_inet
#define EGL_NV_stream_socket_inet 1
EGL_NV_stream_socket_unix
#define EGL_NV_stream_socket_unix 1
EGL_NV_stream_sync
#define EGL_NV_stream_sync 1
EGL_NV_sync
#define EGL_NV_sync 1
EGL_NV_system_time
#define EGL_NV_system_time 1
EGL_NV_triple_buffer
#define EGL_NV_triple_buffer 1
EGL_OBJECT_CONTEXT_KHR
#define EGL_OBJECT_CONTEXT_KHR 0x33B2
EGL_OBJECT_DISPLAY_KHR
#define EGL_OBJECT_DISPLAY_KHR 0x33B1
EGL_OBJECT_IMAGE_KHR
#define EGL_OBJECT_IMAGE_KHR 0x33B4
EGL_OBJECT_STREAM_KHR
#define EGL_OBJECT_STREAM_KHR 0x33B6
EGL_OBJECT_SURFACE_KHR
#define EGL_OBJECT_SURFACE_KHR 0x33B3
EGL_OBJECT_SYNC_KHR
#define EGL_OBJECT_SYNC_KHR 0x33B5
EGL_OBJECT_THREAD_KHR
#define EGL_OBJECT_THREAD_KHR 0x33B0
EGL_OPENGL_ES3_BIT_KHR
#define EGL_OPENGL_ES3_BIT_KHR 0x00000040
EGL_OPENWF_DEVICE_EXT
#define EGL_OPENWF_DEVICE_EXT 0x333D
EGL_OPENWF_DEVICE_ID_EXT
#define EGL_OPENWF_DEVICE_ID_EXT 0x3237
EGL_OPENWF_PIPELINE_ID_EXT
#define EGL_OPENWF_PIPELINE_ID_EXT 0x3238
EGL_OPENWF_PORT_ID_EXT
#define EGL_OPENWF_PORT_ID_EXT 0x3239
EGL_OPTIMAL_FORMAT_BIT_KHR
#define EGL_OPTIMAL_FORMAT_BIT_KHR 0x0100
EGL_PENDING_FRAME_NV
#define EGL_PENDING_FRAME_NV 0x3329
EGL_PENDING_METADATA_NV
#define EGL_PENDING_METADATA_NV 0x3328
EGL_PLATFORM_ANDROID_KHR
#define EGL_PLATFORM_ANDROID_KHR 0x3141
EGL_PLATFORM_DEVICE_EXT
#define EGL_PLATFORM_DEVICE_EXT 0x313F
EGL_PLATFORM_GBM_KHR
#define EGL_PLATFORM_GBM_KHR 0x31D7
EGL_PLATFORM_GBM_MESA
#define EGL_PLATFORM_GBM_MESA 0x31D7
EGL_PLATFORM_SCREEN_QNX
#define EGL_PLATFORM_SCREEN_QNX 0x3550
EGL_PLATFORM_SURFACELESS_MESA
#define EGL_PLATFORM_SURFACELESS_MESA 0x31DD
EGL_PLATFORM_WAYLAND_EXT
#define EGL_PLATFORM_WAYLAND_EXT 0x31D8
EGL_PLATFORM_WAYLAND_KHR
#define EGL_PLATFORM_WAYLAND_KHR 0x31D8
EGL_PLATFORM_X11_EXT
#define EGL_PLATFORM_X11_EXT 0x31D5
EGL_PLATFORM_X11_KHR
#define EGL_PLATFORM_X11_KHR 0x31D5
EGL_PLATFORM_X11_SCREEN_EXT
#define EGL_PLATFORM_X11_SCREEN_EXT 0x31D6
EGL_PLATFORM_X11_SCREEN_KHR
#define EGL_PLATFORM_X11_SCREEN_KHR 0x31D6
EGL_PLATFORM_XCB_EXT
#define EGL_PLATFORM_XCB_EXT 0x31DC
EGL_PLATFORM_XCB_SCREEN_EXT
#define EGL_PLATFORM_XCB_SCREEN_EXT 0x31DE
EGL_POST_SUB_BUFFER_SUPPORTED_NV
#define EGL_POST_SUB_BUFFER_SUPPORTED_NV 0x30BE
EGL_PRESENT_OPAQUE_EXT
#define EGL_PRESENT_OPAQUE_EXT 0x31DF
EGL_PRIMARY_COMPOSITOR_CONTEXT_EXT
#define EGL_PRIMARY_COMPOSITOR_CONTEXT_EXT 0x3460
EGL_PRODUCER_AUTO_ORIENTATION_NV
#define EGL_PRODUCER_AUTO_ORIENTATION_NV 0x336A
EGL_PRODUCER_MAX_FRAME_HINT_NV
#define EGL_PRODUCER_MAX_FRAME_HINT_NV 0x3337
EGL_PRODUCER_METADATA_NV
#define EGL_PRODUCER_METADATA_NV 0x3253
EGL_PROTECTED_CONTENT_EXT
#define EGL_PROTECTED_CONTENT_EXT 0x32C0
EGL_QNX_image_native_buffer
#define EGL_QNX_image_native_buffer 1
EGL_QNX_platform_screen
#define EGL_QNX_platform_screen 1
EGL_QUADRUPLE_BUFFER_NV
#define EGL_QUADRUPLE_BUFFER_NV 0x3231
EGL_READ_SURFACE_BIT_KHR
#define EGL_READ_SURFACE_BIT_KHR 0x0001
EGL_READS_DONE_TIME_ANDROID
#define EGL_READS_DONE_TIME_ANDROID 0x343C
EGL_RECORDABLE_ANDROID
#define EGL_RECORDABLE_ANDROID 0x3142
EGL_RENDERER_EXT
#define EGL_RENDERER_EXT 0x335F
EGL_RENDERING_COMPLETE_TIME_ANDROID
#define EGL_RENDERING_COMPLETE_TIME_ANDROID 0x3435
EGL_REQUESTED_PRESENT_TIME_ANDROID
#define EGL_REQUESTED_PRESENT_TIME_ANDROID 0x3434
EGL_RIGHT_NV
#define EGL_RIGHT_NV 0x336C
EGL_SAMPLE_RANGE_HINT_EXT
#define EGL_SAMPLE_RANGE_HINT_EXT 0x327C
EGL_SMPTE2086_DISPLAY_PRIMARY_BX_EXT
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BX_EXT 0x3345
EGL_SMPTE2086_DISPLAY_PRIMARY_BY_EXT
#define EGL_SMPTE2086_DISPLAY_PRIMARY_BY_EXT 0x3346
EGL_SMPTE2086_DISPLAY_PRIMARY_GX_EXT
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GX_EXT 0x3343
EGL_SMPTE2086_DISPLAY_PRIMARY_GY_EXT
#define EGL_SMPTE2086_DISPLAY_PRIMARY_GY_EXT 0x3344
EGL_SMPTE2086_DISPLAY_PRIMARY_RX_EXT
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RX_EXT 0x3341
EGL_SMPTE2086_DISPLAY_PRIMARY_RY_EXT
#define EGL_SMPTE2086_DISPLAY_PRIMARY_RY_EXT 0x3342
EGL_SMPTE2086_MAX_LUMINANCE_EXT
#define EGL_SMPTE2086_MAX_LUMINANCE_EXT 0x3349
EGL_SMPTE2086_MIN_LUMINANCE_EXT
#define EGL_SMPTE2086_MIN_LUMINANCE_EXT 0x334A
EGL_SMPTE2086_WHITE_POINT_X_EXT
#define EGL_SMPTE2086_WHITE_POINT_X_EXT 0x3347
EGL_SMPTE2086_WHITE_POINT_Y_EXT
#define EGL_SMPTE2086_WHITE_POINT_Y_EXT 0x3348
EGL_SOCKET_HANDLE_NV
#define EGL_SOCKET_HANDLE_NV 0x324C
EGL_SOCKET_TYPE_INET_NV
#define EGL_SOCKET_TYPE_INET_NV 0x324F
EGL_SOCKET_TYPE_NV
#define EGL_SOCKET_TYPE_NV 0x324D
EGL_SOCKET_TYPE_UNIX_NV
#define EGL_SOCKET_TYPE_UNIX_NV 0x324E
EGL_STREAM_BIT_KHR
#define EGL_STREAM_BIT_KHR 0x0800
EGL_STREAM_CONSUMER_IMAGE_NV
#define EGL_STREAM_CONSUMER_IMAGE_NV 0x3373
EGL_STREAM_CONSUMER_IMAGE_USE_SCANOUT_NV
#define EGL_STREAM_CONSUMER_IMAGE_USE_SCANOUT_NV 0x3378
EGL_STREAM_CONSUMER_NV
#define EGL_STREAM_CONSUMER_NV 0x3248
EGL_STREAM_CROSS_DISPLAY_NV
#define EGL_STREAM_CROSS_DISPLAY_NV 0x334E
EGL_STREAM_CROSS_OBJECT_NV
#define EGL_STREAM_CROSS_OBJECT_NV 0x334D
EGL_STREAM_CROSS_PARTITION_NV
#define EGL_STREAM_CROSS_PARTITION_NV 0x323F
EGL_STREAM_CROSS_PROCESS_NV
#define EGL_STREAM_CROSS_PROCESS_NV 0x3245
EGL_STREAM_CROSS_SYSTEM_NV
#define EGL_STREAM_CROSS_SYSTEM_NV 0x334F
EGL_STREAM_DMA_NV
#define EGL_STREAM_DMA_NV 0x3371
EGL_STREAM_DMA_SERVER_NV
#define EGL_STREAM_DMA_SERVER_NV 0x3372
EGL_STREAM_ENDPOINT_NV
#define EGL_STREAM_ENDPOINT_NV 0x3243
EGL_STREAM_FIFO_LENGTH_KHR
#define EGL_STREAM_FIFO_LENGTH_KHR 0x31FC
EGL_STREAM_FIFO_SYNCHRONOUS_NV
#define EGL_STREAM_FIFO_SYNCHRONOUS_NV 0x3336
EGL_STREAM_FRAME_MAJOR_AXIS_NV
#define EGL_STREAM_FRAME_MAJOR_AXIS_NV 0x3368
EGL_STREAM_FRAME_ORIGIN_X_NV
#define EGL_STREAM_FRAME_ORIGIN_X_NV 0x3366
EGL_STREAM_FRAME_ORIGIN_Y_NV
#define EGL_STREAM_FRAME_ORIGIN_Y_NV 0x3367
EGL_STREAM_IMAGE_ADD_NV
#define EGL_STREAM_IMAGE_ADD_NV 0x3374
EGL_STREAM_IMAGE_AVAILABLE_NV
#define EGL_STREAM_IMAGE_AVAILABLE_NV 0x3376
EGL_STREAM_IMAGE_REMOVE_NV
#define EGL_STREAM_IMAGE_REMOVE_NV 0x3375
EGL_STREAM_LOCAL_NV
#define EGL_STREAM_LOCAL_NV 0x3244
EGL_STREAM_PRODUCER_NV
#define EGL_STREAM_PRODUCER_NV 0x3247
EGL_STREAM_PROTOCOL_FD_NV
#define EGL_STREAM_PROTOCOL_FD_NV 0x3246
EGL_STREAM_PROTOCOL_NV
#define EGL_STREAM_PROTOCOL_NV 0x3242
EGL_STREAM_PROTOCOL_SOCKET_NV
#define EGL_STREAM_PROTOCOL_SOCKET_NV 0x324B
EGL_STREAM_STATE_INITIALIZING_NV
#define EGL_STREAM_STATE_INITIALIZING_NV 0x3240
EGL_STREAM_TIME_CONSUMER_KHR
#define EGL_STREAM_TIME_CONSUMER_KHR 0x31FE
EGL_STREAM_TIME_NOW_KHR
#define EGL_STREAM_TIME_NOW_KHR 0x31FD
EGL_STREAM_TIME_PENDING_NV
#define EGL_STREAM_TIME_PENDING_NV 0x332A
EGL_STREAM_TIME_PRODUCER_KHR
#define EGL_STREAM_TIME_PRODUCER_KHR 0x31FF
EGL_STREAM_TYPE_NV
#define EGL_STREAM_TYPE_NV 0x3241
EGL_SUPPORT_RESET_NV
#define EGL_SUPPORT_RESET_NV 0x3334
EGL_SUPPORT_REUSE_NV
#define EGL_SUPPORT_REUSE_NV 0x3335
EGL_SURFACE_COMPRESSION_EXT
#define EGL_SURFACE_COMPRESSION_EXT 0x34B0
EGL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_10BPC_EXT 0x34BD
EGL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_11BPC_EXT 0x34BE
EGL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_12BPC_EXT 0x34BF
EGL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_1BPC_EXT 0x34B4
EGL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_2BPC_EXT 0x34B5
EGL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_3BPC_EXT 0x34B6
EGL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_4BPC_EXT 0x34B7
EGL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_5BPC_EXT 0x34B8
EGL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_6BPC_EXT 0x34B9
EGL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_7BPC_EXT 0x34BA
EGL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_8BPC_EXT 0x34BB
EGL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_9BPC_EXT 0x34BC
EGL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_DEFAULT_EXT 0x34B2
EGL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT
#define EGL_SURFACE_COMPRESSION_FIXED_RATE_NONE_EXT 0x34B1
EGL_SURFACE_COMPRESSION_PLANE1_EXT
#define EGL_SURFACE_COMPRESSION_PLANE1_EXT 0x328E
EGL_SURFACE_COMPRESSION_PLANE2_EXT
#define EGL_SURFACE_COMPRESSION_PLANE2_EXT 0x328F
EGL_SWAP_INTERVAL_EXT
#define EGL_SWAP_INTERVAL_EXT 0x322F
EGL_SYNC_CL_EVENT_COMPLETE_KHR
#define EGL_SYNC_CL_EVENT_COMPLETE_KHR 0x30FF
EGL_SYNC_CL_EVENT_KHR
#define EGL_SYNC_CL_EVENT_KHR 0x30FE
EGL_SYNC_CLIENT_EXT
#define EGL_SYNC_CLIENT_EXT 0x3364
EGL_SYNC_CLIENT_SIGNAL_EXT
#define EGL_SYNC_CLIENT_SIGNAL_EXT 0x3365
EGL_SYNC_CUDA_EVENT_COMPLETE_NV
#define EGL_SYNC_CUDA_EVENT_COMPLETE_NV 0x323D
EGL_SYNC_CUDA_EVENT_NV
#define EGL_SYNC_CUDA_EVENT_NV 0x323C
EGL_SYNC_NATIVE_FENCE_ANDROID
#define EGL_SYNC_NATIVE_FENCE_ANDROID 0x3144
EGL_SYNC_NATIVE_FENCE_FD_ANDROID
#define EGL_SYNC_NATIVE_FENCE_FD_ANDROID 0x3145
EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID
#define EGL_SYNC_NATIVE_FENCE_SIGNALED_ANDROID 0x3146
EGL_SYNC_NEW_FRAME_NV
#define EGL_SYNC_NEW_FRAME_NV 0x321F
EGL_SYNC_PRIOR_COMMANDS_IMPLICIT_EXTERNAL_ARM
#define EGL_SYNC_PRIOR_COMMANDS_IMPLICIT_EXTERNAL_ARM 0x328A
EGL_TEXTURE_EXTERNAL_WL
#define EGL_TEXTURE_EXTERNAL_WL 0x31DA
EGL_TEXTURE_Y_U_V_WL
#define EGL_TEXTURE_Y_U_V_WL 0x31D7
EGL_TEXTURE_Y_UV_WL
#define EGL_TEXTURE_Y_UV_WL 0x31D8
EGL_TEXTURE_Y_XUXV_WL
#define EGL_TEXTURE_Y_XUXV_WL 0x31D9
EGL_TIMESTAMP_INVALID_ANDROID
#define EGL_TIMESTAMP_INVALID_ANDROID EGL_CAST(EGLnsecsANDROID,-1)
EGL_TIMESTAMP_PENDING_ANDROID
#define EGL_TIMESTAMP_PENDING_ANDROID EGL_CAST(EGLnsecsANDROID,-2)
EGL_TIMESTAMPS_ANDROID
#define EGL_TIMESTAMPS_ANDROID 0x3430
EGL_TIZEN_image_native_buffer
#define EGL_TIZEN_image_native_buffer 1
EGL_TIZEN_image_native_surface
#define EGL_TIZEN_image_native_surface 1
EGL_TOP_NV
#define EGL_TOP_NV 0x336D
EGL_TRACK_REFERENCES_KHR
#define EGL_TRACK_REFERENCES_KHR 0x3352
EGL_TRIPLE_BUFFER_NV
#define EGL_TRIPLE_BUFFER_NV 0x3230
EGL_UPPER_LEFT_KHR
#define EGL_UPPER_LEFT_KHR 0x30CF
EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR
#define EGL_VG_ALPHA_FORMAT_PRE_BIT_KHR 0x0040
EGL_VG_COLORSPACE_LINEAR_BIT_KHR
#define EGL_VG_COLORSPACE_LINEAR_BIT_KHR 0x0020
EGL_VG_PARENT_IMAGE_KHR
#define EGL_VG_PARENT_IMAGE_KHR 0x30BA
EGL_WAYLAND_BUFFER_WL
#define EGL_WAYLAND_BUFFER_WL 0x31D5
EGL_WAYLAND_PLANE_WL
#define EGL_WAYLAND_PLANE_WL 0x31D6
EGL_WAYLAND_Y_INVERTED_WL
#define EGL_WAYLAND_Y_INVERTED_WL 0x31DB
EGL_WL_bind_wayland_display
#define EGL_WL_bind_wayland_display 1
EGL_WL_create_wayland_buffer_from_image
#define EGL_WL_create_wayland_buffer_from_image 1
EGL_WRITE_SURFACE_BIT_KHR
#define EGL_WRITE_SURFACE_BIT_KHR 0x0002
EGL_X_AXIS_NV
#define EGL_X_AXIS_NV 0x336F
EGL_Y_AXIS_NV
#define EGL_Y_AXIS_NV 0x3370
EGL_Y_INVERTED_NOK
#define EGL_Y_INVERTED_NOK 0x307F
EGL_YUV_BUFFER_EXT
#define EGL_YUV_BUFFER_EXT 0x3300
EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT
#define EGL_YUV_CHROMA_HORIZONTAL_SITING_HINT_EXT 0x327D
EGL_YUV_CHROMA_SITING_0_5_EXT
#define EGL_YUV_CHROMA_SITING_0_5_EXT 0x3285
EGL_YUV_CHROMA_SITING_0_EXT
#define EGL_YUV_CHROMA_SITING_0_EXT 0x3284
EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT
#define EGL_YUV_CHROMA_VERTICAL_SITING_HINT_EXT 0x327E
EGL_YUV_COLOR_SPACE_HINT_EXT
#define EGL_YUV_COLOR_SPACE_HINT_EXT 0x327B
EGL_YUV_CSC_STANDARD_2020_EXT
#define EGL_YUV_CSC_STANDARD_2020_EXT 0x330D
EGL_YUV_CSC_STANDARD_601_EXT
#define EGL_YUV_CSC_STANDARD_601_EXT 0x330B
EGL_YUV_CSC_STANDARD_709_EXT
#define EGL_YUV_CSC_STANDARD_709_EXT 0x330C
EGL_YUV_CSC_STANDARD_EXT
#define EGL_YUV_CSC_STANDARD_EXT 0x330A
EGL_YUV_DEPTH_RANGE_EXT
#define EGL_YUV_DEPTH_RANGE_EXT 0x3317
EGL_YUV_DEPTH_RANGE_FULL_EXT
#define EGL_YUV_DEPTH_RANGE_FULL_EXT 0x3319
EGL_YUV_DEPTH_RANGE_LIMITED_EXT
#define EGL_YUV_DEPTH_RANGE_LIMITED_EXT 0x3318
EGL_YUV_FULL_RANGE_EXT
#define EGL_YUV_FULL_RANGE_EXT 0x3282
EGL_YUV_NARROW_RANGE_EXT
#define EGL_YUV_NARROW_RANGE_EXT 0x3283
EGL_YUV_NUMBER_OF_PLANES_EXT
#define EGL_YUV_NUMBER_OF_PLANES_EXT 0x3311
EGL_YUV_ORDER_AYUV_EXT
#define EGL_YUV_ORDER_AYUV_EXT 0x3308
EGL_YUV_ORDER_EXT
#define EGL_YUV_ORDER_EXT 0x3301
EGL_YUV_ORDER_UYVY_EXT
#define EGL_YUV_ORDER_UYVY_EXT 0x3305
EGL_YUV_ORDER_VYUY_EXT
#define EGL_YUV_ORDER_VYUY_EXT 0x3307
EGL_YUV_ORDER_YUV_EXT
#define EGL_YUV_ORDER_YUV_EXT 0x3302
EGL_YUV_ORDER_YUYV_EXT
#define EGL_YUV_ORDER_YUYV_EXT 0x3304
EGL_YUV_ORDER_YVU_EXT
#define EGL_YUV_ORDER_YVU_EXT 0x3303
EGL_YUV_ORDER_YVYU_EXT
#define EGL_YUV_ORDER_YVYU_EXT 0x3306
EGL_YUV_PLANE0_TEXTURE_UNIT_NV
#define EGL_YUV_PLANE0_TEXTURE_UNIT_NV 0x332C
EGL_YUV_PLANE1_TEXTURE_UNIT_NV
#define EGL_YUV_PLANE1_TEXTURE_UNIT_NV 0x332D
EGL_YUV_PLANE2_TEXTURE_UNIT_NV
#define EGL_YUV_PLANE2_TEXTURE_UNIT_NV 0x332E
EGL_YUV_PLANE_BPP_0_EXT
#define EGL_YUV_PLANE_BPP_0_EXT 0x331B
EGL_YUV_PLANE_BPP_10_EXT
#define EGL_YUV_PLANE_BPP_10_EXT 0x331D
EGL_YUV_PLANE_BPP_8_EXT
#define EGL_YUV_PLANE_BPP_8_EXT 0x331C
EGL_YUV_PLANE_BPP_EXT
#define EGL_YUV_PLANE_BPP_EXT 0x331A
EGL_YUV_SUBSAMPLE_4_2_0_EXT
#define EGL_YUV_SUBSAMPLE_4_2_0_EXT 0x3313
EGL_YUV_SUBSAMPLE_4_2_2_EXT
#define EGL_YUV_SUBSAMPLE_4_2_2_EXT 0x3314
EGL_YUV_SUBSAMPLE_4_4_4_EXT
#define EGL_YUV_SUBSAMPLE_4_4_4_EXT 0x3315
EGL_YUV_SUBSAMPLE_EXT
#define EGL_YUV_SUBSAMPLE_EXT 0x3312
PFNEGLBINDWAYLANDDISPLAYWL
#define PFNEGLBINDWAYLANDDISPLAYWL PFNEGLBINDWAYLANDDISPLAYWLPROC
PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWL
#define PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWL PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC
PFNEGLQUERYWAYLANDBUFFERWL
#define PFNEGLQUERYWAYLANDBUFFERWL PFNEGLQUERYWAYLANDBUFFERWLPROC
PFNEGLUNBINDWAYLANDDISPLAYWL
#define PFNEGLUNBINDWAYLANDDISPLAYWL PFNEGLUNBINDWAYLANDDISPLAYWLPROC
Typedef Documentation
attrib_list
typedef EGLStreamKHR EGLenum const EGLint* attrib_list
attribute
typedef struct wl_resource EGLint attribute
aux
typedef EGLStreamKHR EGLTime EGLenum EGLAttrib* aux
buffer
typedef struct wl_resource* buffer
context_attributes
typedef const EGLint* context_attributes
data
typedef EGLStreamKHR EGLenum EGLint EGLint EGLint void * data
denominator
typedef EGLSurface EGLint EGLint* denominator
devices
typedef EGLDeviceEXT* devices
display
typedef struct wl_display * display
display_id
typedef EGLNativeDisplayType* display_id
EGLAttribKHR
typedef intptr_t EGLAttribKHR
EGLDEBUGPROCKHR
typedef void(EGLAPIENTRY * EGLDEBUGPROCKHR) (EGLenum error, const char *command, EGLint messageType, EGLLabelKHR threadLabel, EGLLabelKHR objectLabel, const char *message)
EGLDeviceEXT
typedef void* EGLDeviceEXT
EGLGetBlobFuncANDROID
typedef EGLsizeiANDROID(* EGLGetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, void *value, EGLsizeiANDROID valueSize)
EGLImageKHR
typedef EGLImageKHR
EGLLabelKHR
typedef void* EGLLabelKHR
EGLNativeFileDescriptorKHR
typedef int EGLNativeFileDescriptorKHR
EGLnsecsANDROID
typedef khronos_stime_nanoseconds_t EGLnsecsANDROID
EGLObjectKHR
typedef void* EGLObjectKHR
EGLOutputLayerEXT
typedef void* EGLOutputLayerEXT
EGLOutputPortEXT
typedef void* EGLOutputPortEXT
EGLSetBlobFuncANDROID
typedef void(* EGLSetBlobFuncANDROID) (const void *key, EGLsizeiANDROID keySize, const void *value, EGLsizeiANDROID valueSize)
EGLsizeiANDROID
typedef khronos_ssize_t EGLsizeiANDROID
EGLStreamKHR
typedef void* EGLStreamKHR
EGLSyncKHR
typedef EGLSyncKHR
EGLSyncNV
typedef void* EGLSyncNV
EGLTimeKHR
typedef khronos_utime_nanoseconds_t EGLTimeKHR
EGLTimeNV
typedef khronos_utime_nanoseconds_t EGLTimeNV
EGLuint64KHR
typedef khronos_uint64_t EGLuint64KHR
EGLuint64NV
typedef khronos_utime_nanoseconds_t EGLuint64NV
event
typedef EGLStreamKHR EGLTime EGLenum* event
external_only
typedef EGLint EGLint EGLuint64KHR EGLBoolean* external_only
external_win_ids
typedef const EGLint* external_win_ids
fds
typedef EGLImageKHR int* fds
file_descriptor
typedef EGLNativeFileDescriptorKHR file_descriptor
flags
typedef EGLSyncKHR EGLint flags
format
typedef EGLint format
formats
typedef EGLint EGLint* formats
fourcc
typedef EGLImageKHR int* fourcc
frameId
typedef EGLSurface EGLuint64KHR frameId
get
typedef EGLSetBlobFuncANDROID EGLGetBlobFuncANDROID get
handle
typedef EGLImageKHR EGLint EGLint* handle
height
typedef EGLSurface EGLint EGLint EGLint EGLint height
image
typedef EGLStreamKHR EGLImage image
label
typedef EGLenum EGLObjectKHR EGLLabelKHR label
layer
typedef EGLStreamKHR EGLOutputLayerEXT layer
layers
typedef const EGLAttrib EGLOutputLayerEXT* layers
max_formats
typedef EGLint max_formats
max_layers
typedef const EGLAttrib EGLOutputLayerEXT EGLint max_layers
max_modifiers
typedef EGLint EGLint max_modifiers
max_ports
typedef const EGLAttrib EGLOutputPortEXT EGLint max_ports
max_size
typedef EGLint EGLint max_size
modifiers
typedef EGLStreamKHR EGLint const EGLuint64KHR * modifiers
n
typedef EGLStreamKHR EGLenum EGLint n
n_rects
typedef EGLSurface const EGLint EGLint n_rects
name
typedef EGLStreamKHR EGLenum name
names
typedef EGLSurface EGLint const EGLint* names
native_display
typedef void* native_display
native_pixmap
typedef EGLConfig void* native_pixmap
native_window
typedef EGLConfig void* native_window
num_devices
typedef EGLDeviceEXT EGLint* num_devices
num_entries
typedef const EGLint EGLint num_entries
num_formats
typedef EGLint EGLint EGLint* num_formats
num_layers
typedef const EGLAttrib EGLOutputLayerEXT EGLint EGLint* num_layers
num_modifiers
typedef EGLStreamKHR EGLint num_modifiers
num_planes
typedef EGLImageKHR int int* num_planes
num_ports
typedef const EGLAttrib EGLOutputPortEXT EGLint EGLint* num_ports
num_rates
typedef EGLConfig const EGLAttrib EGLint EGLint EGLint* num_rates
numerator
typedef EGLSurface EGLint* numerator
numRects
typedef EGLSurface EGLint numRects
numTimestamps
typedef EGLSurface EGLuint64KHR EGLint numTimestamps
object
typedef EGLenum EGLObjectKHR object
objectType
typedef EGLenum objectType
offset
typedef EGLStreamKHR EGLenum EGLint EGLint offset
offsets
typedef EGLImageKHR int EGLint EGLint* offsets
PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC
typedef struct wl_buffer *EGLAPIENTRYP PFNEGLCREATEWAYLANDBUFFERFROMIMAGEWLPROC(EGLDisplay dpy, EGLImageKHR image)
PFNEGLGETDISPLAYDRIVERCONFIGPROC
typedef char *EGLAPIENTRYP PFNEGLGETDISPLAYDRIVERCONFIGPROC(EGLDisplay dpy)
PFNEGLGETDISPLAYDRIVERNAMEPROC
typedef const char *EGLAPIENTRYP PFNEGLGETDISPLAYDRIVERNAMEPROC(EGLDisplay dpy)
PFNEGLQUERYDEVICESTRINGEXTPROC
typedef const char *EGLAPIENTRYP PFNEGLQUERYDEVICESTRINGEXTPROC(EGLDeviceEXT device, EGLint name)
PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC
typedef const char *EGLAPIENTRYP PFNEGLQUERYOUTPUTLAYERSTRINGEXTPROC(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint name)
PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC
typedef const char *EGLAPIENTRYP PFNEGLQUERYOUTPUTPORTSTRINGEXTPROC(EGLDisplay dpy, EGLOutputPortEXT port, EGLint name)
pImage
typedef EGLStreamKHR EGLImage* pImage
pixmap
typedef EGLSurface EGLNativePixmapType* pixmap
policy
typedef EGLint policy
port
typedef EGLOutputPortEXT port
ports
typedef const EGLAttrib EGLOutputPortEXT* ports
rate_size
typedef EGLConfig const EGLAttrib EGLint EGLint rate_size
rates
typedef EGLConfig const EGLAttrib EGLint* rates
rects
typedef EGLSurface EGLint const EGLint * rects
set
typedef EGLSetBlobFuncANDROID set
size
typedef EGLStreamKHR EGLenum EGLint EGLint EGLint size
stream
typedef EGLConfig EGLStreamKHR stream
stride
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei stride
strides
typedef EGLImageKHR int EGLint* strides
surf
typedef EGLSurface surf
sync
typedef EGLStreamKHR EGLImage EGLSync sync
target
typedef EGLContext EGLenum target
time
typedef EGLSurface EGLnsecsANDROID time
timeout
typedef EGLStreamKHR EGLTime timeout
timestamp
typedef EGLSurface EGLint timestamp
timestamps
typedef EGLSurface EGLuint64KHR EGLint const EGLint* timestamps
type
typedef EGLStreamKHR EGLenum type
value
typedef struct wl_resource EGLint EGLint* value
values
typedef EGLSurface EGLuint64KHR EGLint const EGLint EGLnsecsANDROID * values
width
typedef EGLSurface EGLint EGLint EGLint width
window
typedef EGLSurface EGLNativeWindowType* window
window_attributes
typedef const EGLint* window_attributes
x
typedef EGLSurface EGLint x
y
typedef EGLSurface EGLint EGLint y
Function Documentation
EGLBoolean()
typedef EGLBoolean (EGLAPIENTRYP PFNEGLQUERYDEBUGKHRPROC)
References EGLAPIENTRYP.
EGLClientBuffer()
typedef EGLClientBuffer (EGLAPIENTRYP PFNEGLCREATENATIVECLIENTBUFFERANDROIDPROC) const
References EGLAPI, EGLAPIENTRY, and EGLAPIENTRYP.
EGLDisplay()
typedef EGLDisplay (EGLAPIENTRYP PFNEGLGETPLATFORMDISPLAYEXTPROC)
References EGLAPIENTRYP.
EGLImageKHR()
typedef EGLImageKHR (EGLAPIENTRYP PFNEGLCREATEIMAGEKHRPROC)
EGLint()
typedef EGLint (EGLAPIENTRYP PFNEGLDEBUGMESSAGECONTROLKHRPROC)
References EGLAPIENTRYP.
EGLNativeFileDescriptorKHR()
typedef EGLNativeFileDescriptorKHR (EGLAPIENTRYP PFNEGLGETSTREAMFILEDESCRIPTORKHRPROC)
References EGLAPIENTRYP.
EGLStreamKHR()
typedef EGLStreamKHR (EGLAPIENTRYP PFNEGLCREATESTREAMFROMFILEDESCRIPTORKHRPROC)
References EGLAPI, EGLAPIENTRY, and EGLAPIENTRYP.
EGLSurface()
typedef EGLSurface (EGLAPIENTRYP PFNEGLCREATESTREAMPRODUCERSURFACEKHRPROC)
References EGLAPI, EGLAPIENTRY, and EGLAPIENTRYP.
EGLSyncKHR()
typedef EGLSyncKHR (EGLAPIENTRYP PFNEGLCREATESYNC64KHRPROC)
void()
typedef void (EGLAPIENTRYP PFNEGLSETBLOBCACHEFUNCSANDROIDPROC)
Referenced by add_segment(), AddDeviceToEnumeration(), SDL3Cocoa_WindowListener::addPendingWindowOperation:, SDL3Cocoa_WindowListener::clearFocusClickPending:, CPU_haveAltiVec(), CPU_haveAVX2(), CPU_haveAVX512F(), CreateMappingString(), dlmallinfo(), SDL_uikitviewcontroller::doLoop:, EGLDisplay(), EGLenum(), EGLint(), EnumerateOneProperty(), GDK_RegisterChangeNotifications(), GetAppName(), glPopName(), SDL3Cocoa_WindowListener::handleTouches:withEvent:, hid_device_removal_callback(), hid_libusb_wrap_sys_device(), hid_report_callback(), SDLUIKitDelegate::hideLaunchScreen, SDL_uikitview::indirectPointerHovering:, init_mparams(), init_xbox360(), init_xboxone(), SDL3Cocoa_WindowListener::isInFullscreenSpaceTransition, SDL3Cocoa_WindowListener::isMovingOrFocusClickPending, SDL3Cocoa_WindowListener::isTouchFromTrackpad:, JNI_OnLoad(), SDL3Cocoa_WindowListener::listen:, SDL_uikitviewcontroller::loadView, SDLLaunchScreenController::loadView, main(), mmap_resize(), SDL3Cocoa_WindowListener::mouseDown:, SDL3Cocoa_WindowListener::mouseDragged:, SDL3Cocoa_WindowListener::mouseMoved:, SDL3Cocoa_WindowListener::mouseUp:, SDL3Cocoa_WindowListener::otherMouseDown:, SDL3Cocoa_WindowListener::otherMouseDragged:, SDL3Cocoa_WindowListener::otherMouseUp:, SDL3Cocoa_WindowListener::pauseVisibleObservation, SDL_uikitview::pencilHovering:, PLATFORM_hid_error(), PLATFORM_hid_get_indexed_string(), PLATFORM_hid_init(), SDL3Cocoa_WindowListener::processHitTest:, pthread_barrier_init(), SDL3Cocoa_WindowListener::rightMouseDown:, SDL3Cocoa_WindowListener::rightMouseDragged:, SDL3Cocoa_WindowListener::rightMouseUp:, SDL_uikitview::safeAreaInsetsDidChange, SDL3Cocoa_WindowListener::scrollWheel:, SDL_ALLOC_SIZE2(), SDL_CleanupTLS(), SDL_CreateDeviceName(), SDL_DestroyHashKey(), SDL_DestroyHashKeyAndValue(), SDL_DestroyHashValue(), SDL_FillSurfaceRects(), SDL_GetAudioThreadName(), SDL_GetCameraThreadName(), SDL_GetCPUCacheLineSize(), SDL_GetCPUType(), SDL_GetDirect3D9AdapterIndex(), SDL_GetDXGIOutputInfo(), SDL_GetEventDescription(), SDL_GetGDKTaskQueue(), SDL_HashID(), SDL_HashPointer(), SDL_HashString(), SDL_InitSubSystem(), SDL_KeyMatchID(), SDL_KeyMatchPointer(), SDL_KeyMatchString(), SDL_LockJoysticks(), SDL_LockSensors(), SDL_LogMessageV(), SDL_LogOutput(), SDL_PrivateAppendToMappingString(), SDL_PrivateGenerateAutomaticGamepadMapping(), SDL_PromptAssertion(), SDL_RegisterApp(), SDL_RequestAndroidPermission(), SDL_RunApp(), SDL_SendAndroidMessage(), SDL_SetErrorV(), SDL_SetiOSAnimationCallback(), SDL_SetiOSEventPump(), SDL_SetLinuxThreadPriority(), SDL_SetLinuxThreadPriorityAndPolicy(), SDL_SetWindowsMessageHook(), SDL_ShowAndroidToast(), SDL_ShowMessageBox(), SDL_SYS_GetPreferredLocales_winxp(), SDL_uikitviewcontroller::setAnimationCallback:callback:callbackParam:, SDL3Cocoa_WindowListener::setFocusClickPending:, SDL3Cocoa_WindowListener::setPendingMoveX:Y:, SDL_uikitview::setSDLWindow:, SDL_uikitviewcontroller::startAnimation, SDL_uikitviewcontroller::stopAnimation, sys_alloc(), sys_trim(), SDL3Cocoa_WindowListener::tabletProximity:, SDL_uikitview::touchesBegan:withEvent:, SDL3Cocoa_WindowListener::touchesBeganWithEvent:, SDL3Cocoa_WindowListener::touchesCancelledWithEvent:, SDL_uikitview::touchesEnded:withEvent:, SDL3Cocoa_WindowListener::touchesEndedWithEvent:, SDL_uikitview::touchesMoved:withEvent:, SDL3Cocoa_WindowListener::touchesMovedWithEvent:, SDL_uikitviewcontroller::traitCollectionDidChange:, SDL3Cocoa_WindowListener::updateIgnoreMouseState:, SDL_uikitviewcontroller::viewDidLayoutSubviews, SDL3Cocoa_WindowListener::window:willUseFullScreenPresentationOptions:, SDL3Cocoa_WindowListener::windowDidBecomeKey:, SDL3Cocoa_WindowListener::windowDidChangeBackingProperties:, SDL3Cocoa_WindowListener::windowDidChangeOcclusionState:, SDL3Cocoa_WindowListener::windowDidChangeScreen:, SDL3Cocoa_WindowListener::windowDidChangeScreenProfile:, SDL3Cocoa_WindowListener::windowDidDeminiaturize:, SDL3Cocoa_WindowListener::windowDidEndLiveResize:, SDL3Cocoa_WindowListener::windowDidEnterFullScreen:, SDL3Cocoa_WindowListener::windowDidExpose:, SDL3Cocoa_WindowListener::windowDidFinishMoving, SDL3Cocoa_WindowListener::windowDidMiniaturize:, SDL3Cocoa_WindowListener::windowDidMove:, SDL3Cocoa_WindowListener::windowDidResignKey:, SDL3Cocoa_WindowListener::windowDidResize:, windows_ShowFileDialog(), SDL3Cocoa_WindowListener::windowShouldClose:, SDL3Cocoa_WindowListener::windowWillEnterFullScreen:, SDL3Cocoa_WindowListener::windowWillExitFullScreen:, SDL3Cocoa_WindowListener::windowWillStartLiveResize:, X11_InitPen(), and X11_QuitPen().