SDL3: SDL-main/src/core/gdk/SDL_gdk.h File Reference
SDL_gdk.h File Reference
#include "SDL_internal.h"
Functions
void GDK_DispatchTaskQueue (void)
bool GDK_RegisterChangeNotifications (void)
void GDK_UnregisterChangeNotifications (void)
Function Documentation
GDK_DispatchTaskQueue()
void GDK_DispatchTaskQueue (void) extern
{
    /* If there is no global task queue, don't do anything.
     * This gives the option to opt-out for those who want to handle everything themselves.
     */
    if (GDK_GlobalTaskQueue) {
        // Dispatch any callbacks which are ready.
        while (XTaskQueueDispatch(GDK_GlobalTaskQueue, XTaskQueuePort::Completion, 0))
            ;
    }
}
References GDK_GlobalTaskQueue.
GDK_RegisterChangeNotifications()
bool GDK_RegisterChangeNotifications (void) extern
{
    // Register suspend/resume handling
    plmSuspendComplete = CreateEventEx(nullptr, nullptr, 0, EVENT_MODIFY_STATE | SYNCHRONIZE);
    if (!plmSuspendComplete) {
        return SDL_SetError("[GDK] Unable to create plmSuspendComplete event");
    }
    auto rascn = [](BOOLEAN quiesced, PVOID context) {
        SDL_LogDebug(SDL_LOG_CATEGORY_APPLICATION, "[GDK] in RegisterAppStateChangeNotification handler");
        if (quiesced) {
            ResetEvent(plmSuspendComplete);
            SDL_SendAppEvent(SDL_EVENT_DID_ENTER_BACKGROUND);
            // To defer suspension, we must wait to exit this callback.
            // IMPORTANT: The app must call SDL_GDKSuspendComplete() to release this lock.
            (void)WaitForSingleObject(plmSuspendComplete, INFINITE);
            SDL_LogDebug(SDL_LOG_CATEGORY_APPLICATION, "[GDK] in RegisterAppStateChangeNotification handler: plmSuspendComplete event signaled.");
        } else {
            SDL_SendAppEvent(SDL_EVENT_WILL_ENTER_FOREGROUND);
        }
    };
    if (RegisterAppStateChangeNotification(rascn, NULL, &hPLM)) {
        return SDL_SetError("[GDK] Unable to call RegisterAppStateChangeNotification");
    }
    // Register constrain/unconstrain handling
    auto raccn = [](BOOLEAN constrained, PVOID context) {
        SDL_LogDebug(SDL_LOG_CATEGORY_APPLICATION, "[GDK] in RegisterAppConstrainedChangeNotification handler");
        SDL_VideoDevice *_this = SDL_GetVideoDevice();
        if (_this) {
            if (constrained && !((_this->windows) && _this->windows->text_input_active)) {
                SDL_SetKeyboardFocus(NULL);
            } else {
                SDL_SetKeyboardFocus(_this->windows);
            }
        }
    };
    if (RegisterAppConstrainedChangeNotification(raccn, NULL, &hCPLM)) {
        return SDL_SetError("[GDK] Unable to call RegisterAppConstrainedChangeNotification");
    }
    return true;
}
References _this, context, hCPLM, hPLM, NULL, plmSuspendComplete, SDL_EVENT_DID_ENTER_BACKGROUND, SDL_EVENT_WILL_ENTER_FOREGROUND, SDL_GetVideoDevice(), SDL_LOG_CATEGORY_APPLICATION, SDL_LogDebug(), SDL_SendAppEvent(), SDL_SetError(), SDL_SetKeyboardFocus(), and void().
Referenced by SDL_RunApp().
GDK_UnregisterChangeNotifications()
void GDK_UnregisterChangeNotifications (void) extern
{
    // Unregister suspend/resume handling
    UnregisterAppStateChangeNotification(hPLM);
    CloseHandle(plmSuspendComplete);
    // Unregister constrain/unconstrain handling
    UnregisterAppConstrainedChangeNotification(hCPLM);
}
References hCPLM, hPLM, and plmSuspendComplete.
Referenced by SDL_RunApp().