SDL3: SDL_BWin Class Reference
SDL_BWin Class Reference
#include <SDL_BWin.h>
Inherits BWindow.
Public Member Functions
SDL_BView * CreateView ()
void DispatchMessage (BMessage *msg, BHandler *target)
virtual void FrameMoved (BPoint origin)
void FrameResized (float width, float height)
BBitmap * GetBitmap ()
BView * GetCurView ()
int32 GetID ()
SDL_BView * GetView ()
void Hide ()
bool IsShown ()
void LockBuffer ()
void MessageReceived (BMessage *message)
void Minimize (bool minimize)
bool QuitRequested ()
void RemoveView ()
void ScreenChanged (BRect screenFrame, color_space depth)
SDL_BWin (BRect bounds, window_look look, uint32 flags)
void SetBitmap (BBitmap *bitmap)
void SetCurrentView (BView *view)
void SetID (int32 id)
void Show ()
void UnlockBuffer ()
void UpdateCurrentView ()
void WindowActivated (bool active)
void Zoom (BPoint origin, float width, float height)
virtual ~SDL_BWin ()
Private Member Functions
void _KeyEvent (int32 keyCode, const int8 *keyUtf8, const ssize_t &len, bool down)
void _MouseButtonEvent (int32 buttons, bool down)
void _MouseFocusEvent (bool focusGained)
void _MouseMotionEvent (BPoint &where, int32 transit)
void _MouseWheelEvent (int32 x, int32 y)
void _MoveTo (BMessage *msg)
void _PostWindowEvent (BMessage &msg)
void _RepaintEvent ()
void _ResizeTo (BMessage *msg)
void _Restore ()
void _SendMouseButton (int32 button, bool down)
void _SetBordered (bool bEnabled)
void _SetFullScreen (bool fullscreen)
void _SetMinimumSize (BMessage *msg)
void _SetResizable (bool bEnabled)
void _SetTitle (BMessage *msg)
Private Attributes
BBitmap * _bitmap
bool _bordered
BLocker * _buffer_locker
BView * _cur_view
bool _fullscreen
int32 _id
bool _inhibit_resize
int32 _last_buttons
bool _mouse_focused
BRect _non_fullscreen_frame
BRect * _prev_frame
bool _resizable
SDL_BView * _SDL_View
bool _shown
Constructor & Destructor Documentation
SDL_BWin()
SDL_BWin::SDL_BWin (BRect bounds, window_look look, uint32 flags) inline
        : BWindow(bounds, "Untitled", look, B_NORMAL_WINDOW_FEEL, flags)
    {
        _last_buttons = 0;
        _cur_view = NULL;
        _SDL_View = NULL;
#ifdef SDL_VIDEO_OPENGL
        _SDL_GLView = NULL;
        _gl_type = 0;
#endif
        _shown = false;
        _inhibit_resize = false;
        _mouse_focused = false;
        _prev_frame = NULL;
        _fullscreen = NULL;
        // Handle framebuffer stuff
        _buffer_locker = new BLocker();
        _bitmap = NULL;
    }
References _bitmap, _buffer_locker, _cur_view, _fullscreen, _inhibit_resize, _last_buttons, _mouse_focused, _prev_frame, _SDL_View, _shown, and NULL.
~SDL_BWin()
virtual SDL_BWin::~SDL_BWin () inline virtual
    {
        Lock();
        if (_SDL_View != NULL && _SDL_View != _cur_view) {
            delete _SDL_View;
            _SDL_View = NULL;
        }
#ifdef SDL_VIDEO_OPENGL
        if (_SDL_GLView) {
            if (SDL_Looper->GetCurrentContext() == _SDL_GLView)
                SDL_Looper->SetCurrentContext(NULL);
            if (_SDL_GLView == _cur_view)
                RemoveChild(_SDL_GLView);
            _SDL_GLView = NULL;
            // _SDL_GLView deleted by HAIKU_GL_DestroyContext
        }
#endif
        Unlock();
        delete _prev_frame;
        // Clean up framebuffer stuff
        _buffer_locker->Lock();
        delete _buffer_locker;
    }
References _buffer_locker, _cur_view, _prev_frame, _SDL_View, NULL, and SDL_Looper.
Member Function Documentation
_KeyEvent()
void SDL_BWin::_KeyEvent (int32 keyCode, const int8 * keyUtf8, const ssize_t & len, bool down) inline private
    {
        // Create a message to pass along to the BeApp thread
        BMessage msg(BAPP_KEY);
        msg.AddInt32("key-scancode", keyCode);
        if (keyUtf8 != NULL) {
            msg.AddData("key-utf8", B_INT8_TYPE, (const void *)keyUtf8, len);
        }
        msg.AddBool("key-down", down);
        SDL_Looper->PostMessage(&msg);
    }
References BAPP_KEY, NULL, and SDL_Looper.
Referenced by DispatchMessage().
_MouseButtonEvent()
void SDL_BWin::_MouseButtonEvent (int32 buttons, bool down) inline private
    {
        int32 buttonStateChange = buttons ^ _last_buttons;
        if (buttonStateChange & B_PRIMARY_MOUSE_BUTTON) {
            _SendMouseButton(SDL_BUTTON_LEFT, down);
        }
        if (buttonStateChange & B_SECONDARY_MOUSE_BUTTON) {
            _SendMouseButton(SDL_BUTTON_RIGHT, down);
        }
        if (buttonStateChange & B_TERTIARY_MOUSE_BUTTON) {
            _SendMouseButton(SDL_BUTTON_MIDDLE, down);
        }
        _last_buttons = buttons;
    }
References _last_buttons, _SendMouseButton(), SDL_BUTTON_LEFT, SDL_BUTTON_MIDDLE, and SDL_BUTTON_RIGHT.
Referenced by DispatchMessage().
_MouseFocusEvent()
void SDL_BWin::_MouseFocusEvent (bool focusGained) inline private
    {
        _mouse_focused = focusGained;
        BMessage msg(BAPP_MOUSE_FOCUS);
        msg.AddBool("focusGained", focusGained);
        _PostWindowEvent(msg);
        /* FIXME: Why were these here?
         if false: be_app->SetCursor(B_HAND_CURSOR);
         if true:  SDL_SetCursor(NULL); */
    }
References _mouse_focused, _PostWindowEvent(), and BAPP_MOUSE_FOCUS.
Referenced by _MouseMotionEvent().
_MouseMotionEvent()
void SDL_BWin::_MouseMotionEvent (BPoint & where, int32 transit) inline private
    {
        if (transit == B_EXITED_VIEW) {
            // Change mouse focus
            if (_mouse_focused) {
                _MouseFocusEvent(false);
            }
        } else {
            // Change mouse focus
            if (!_mouse_focused) {
                _MouseFocusEvent(true);
            }
            BMessage msg(BAPP_MOUSE_MOVED);
            msg.AddInt32("x", (int)where.x);
            msg.AddInt32("y", (int)where.y);
            _PostWindowEvent(msg);
        }
    }
References _mouse_focused, _MouseFocusEvent(), _PostWindowEvent(), and BAPP_MOUSE_MOVED.
Referenced by DispatchMessage().
_MouseWheelEvent()
void SDL_BWin::_MouseWheelEvent (int32 x, int32 y) inline private
    {
        // Create a message to pass along to the BeApp thread
        BMessage msg(BAPP_MOUSE_WHEEL);
        msg.AddInt32("xticks", x);
        msg.AddInt32("yticks", y);
        _PostWindowEvent(msg);
    }
References _PostWindowEvent(), and BAPP_MOUSE_WHEEL.
Referenced by DispatchMessage().
_MoveTo()
void SDL_BWin::_MoveTo (BMessage * msg) inline private
    {
        int32 x, y;
        if (
            msg->FindInt32("window-x", &x) != B_OK ||
            msg->FindInt32("window-y", &y) != B_OK) {
            return;
        }
        if (_fullscreen)
            _non_fullscreen_frame.OffsetTo(x, y);
        else
            MoveTo(x, y);
    }
References _fullscreen, and _non_fullscreen_frame.
Referenced by MessageReceived().
_PostWindowEvent()
void SDL_BWin::_PostWindowEvent (BMessage & msg) inline private
    {
        msg.AddInt32("window-id", _id);
        SDL_Looper->PostMessage(&msg);
    }
References _id, and SDL_Looper.
Referenced by _MouseFocusEvent(), _MouseMotionEvent(), _MouseWheelEvent(), _RepaintEvent(), _SendMouseButton(), FrameMoved(), FrameResized(), Hide(), Minimize(), QuitRequested(), Show(), WindowActivated(), and Zoom().
_RepaintEvent()
void SDL_BWin::_RepaintEvent () inline private
    {
        // Force a repaint: Call the SDL exposed event
        BMessage msg(BAPP_REPAINT);
        _PostWindowEvent(msg);
    }
References _PostWindowEvent(), and BAPP_REPAINT.
_ResizeTo()
void SDL_BWin::_ResizeTo (BMessage * msg) inline private
    {
        int32 w, h;
        if (
            msg->FindInt32("window-w", &w) != B_OK ||
            msg->FindInt32("window-h", &h) != B_OK) {
            return;
        }
        if (_fullscreen) {
            _non_fullscreen_frame.right = _non_fullscreen_frame.left + w;
            _non_fullscreen_frame.bottom = _non_fullscreen_frame.top + h;
        } else
            ResizeTo(w, h);
    }
References _fullscreen, and _non_fullscreen_frame.
Referenced by MessageReceived().
_Restore()
void SDL_BWin::_Restore () inline private
    {
        if (IsMinimized()) {
            Minimize(false);
        } else if (IsHidden()) {
            Show();
        } else if (_fullscreen) {
        } else if (_prev_frame != NULL) { // Zoomed
            MoveTo(_prev_frame->left, _prev_frame->top);
            ResizeTo(_prev_frame->Width(), _prev_frame->Height());
        }
    }
References _fullscreen, _prev_frame, Minimize(), NULL, and Show().
Referenced by MessageReceived().
_SendMouseButton()
void SDL_BWin::_SendMouseButton (int32 button, bool down) inline private
    {
        BMessage msg(BAPP_MOUSE_BUTTON);
        msg.AddInt32("button-id", button);
        msg.AddBool("button-down", down);
        _PostWindowEvent(msg);
    }
References _PostWindowEvent(), and BAPP_MOUSE_BUTTON.
Referenced by _MouseButtonEvent().
_SetBordered()
void SDL_BWin::_SetBordered (bool bEnabled) inline private
    {
        if (_fullscreen)
            _bordered = bEnabled;
        else
            SetLook(bEnabled ? B_TITLED_WINDOW_LOOK : B_NO_BORDER_WINDOW_LOOK);
    }
References _bordered, and _fullscreen.
Referenced by _SetFullScreen(), and MessageReceived().
_SetFullScreen()
void SDL_BWin::_SetFullScreen (bool fullscreen) inline private
    {
        if (fullscreen != _fullscreen) {
            if (fullscreen) {
                BScreen screen(this);
                BRect screenFrame = screen.Frame();
                printf("screen frame: ");
                screenFrame.PrintToStream();
                printf("\n");
                _bordered = Look() != B_NO_BORDER_WINDOW_LOOK;
                _resizable = !(Flags() & B_NOT_RESIZABLE);
                _non_fullscreen_frame = Frame();
                _SetBordered(false);
                _SetResizable(false);
                MoveTo(screenFrame.left, screenFrame.top);
                ResizeTo(screenFrame.Width(), screenFrame.Height());
                _fullscreen = fullscreen;
            } else {
                _fullscreen = fullscreen;
                MoveTo(_non_fullscreen_frame.left, _non_fullscreen_frame.top);
                ResizeTo(_non_fullscreen_frame.Width(), _non_fullscreen_frame.Height());
                _SetBordered(_bordered);
                _SetResizable(_resizable);
            }
        }
    }
References _bordered, _fullscreen, _non_fullscreen_frame, _resizable, _SetBordered(), and _SetResizable().
Referenced by MessageReceived().
_SetMinimumSize()
void SDL_BWin::_SetMinimumSize (BMessage * msg) inline private
    {
        float maxHeight;
        float maxWidth;
        float _;
        int32 minHeight;
        int32 minWidth;
        // This is a bit convoluted, we only want to set the minimum not the maximum
        // But there is no direct call to do that, so store the maximum size beforehand
        GetSizeLimits(&_, &maxWidth, &_, &maxHeight);
        if (msg->FindInt32("window-w", &minWidth) != B_OK)
            return;
        if (msg->FindInt32("window-h", &minHeight) != B_OK)
            return;
        SetSizeLimits((float)minWidth, maxWidth, (float)minHeight, maxHeight);
        UpdateSizeLimits();
    }
Referenced by MessageReceived().
_SetResizable()
void SDL_BWin::_SetResizable (bool bEnabled) inline private
    {
        if (_fullscreen)
            _resizable = bEnabled;
        else {
            if (bEnabled) {
                SetFlags(Flags() & ~(B_NOT_RESIZABLE | B_NOT_ZOOMABLE));
            } else {
                SetFlags(Flags() | (B_NOT_RESIZABLE | B_NOT_ZOOMABLE));
            }
        }
    }
References _fullscreen, and _resizable.
Referenced by _SetFullScreen(), and MessageReceived().
_SetTitle()
void SDL_BWin::_SetTitle (BMessage * msg) inline private
    {
        const char *title;
        if (
            msg->FindString("window-title", &title) != B_OK) {
            return;
        }
        SetTitle(title);
    }
Referenced by MessageReceived().
CreateView()
SDL_BView * SDL_BWin::CreateView () inline
    {
        Lock();
        if (_SDL_View == NULL) {
            _SDL_View = new SDL_BView(Bounds(), "SDL View", B_FOLLOW_ALL_SIDES);
            UpdateCurrentView();
        }
        Unlock();
        return _SDL_View;
    }
References _SDL_View, NULL, and UpdateCurrentView().
DispatchMessage()
void SDL_BWin::DispatchMessage (BMessage * msg, BHandler * target) inline
    {
        BPoint where;  // Used by mouse moved
        int32 buttons; // Used for mouse button events
        int32 key;     // Used for key events
        switch (msg->what) {
        case B_MOUSE_MOVED:
            int32 transit;
            if (msg->FindPoint("where", &where) == B_OK && msg->FindInt32("be:transit", &transit) == B_OK) {
                _MouseMotionEvent(where, transit);
            }
            break;
        case B_MOUSE_DOWN:
            if (msg->FindInt32("buttons", &buttons) == B_OK) {
                _MouseButtonEvent(buttons, true);
            }
            break;
        case B_MOUSE_UP:
            if (msg->FindInt32("buttons", &buttons) == B_OK) {
                _MouseButtonEvent(buttons, false);
            }
            break;
        case B_MOUSE_WHEEL_CHANGED:
            float x, y;
            if (msg->FindFloat("be:wheel_delta_x", &x) == B_OK && msg->FindFloat("be:wheel_delta_y", &y) == B_OK) {
                _MouseWheelEvent((int)x, (int)y);
            }
            break;
        case B_KEY_DOWN:
        {
            int32 i = 0;
            int8 byte;
            int8 bytes[4] = { 0, 0, 0, 0 };
            while (i < 4 && msg->FindInt8("byte", i, &byte) == B_OK) {
                bytes[i] = byte;
                i++;
            }
            if (msg->FindInt32("key", &key) == B_OK) {
                _KeyEvent((SDL_Scancode)key, &bytes[0], i, true);
            }
        } break;
        case B_UNMAPPED_KEY_DOWN: // modifier keys are unmapped
            if (msg->FindInt32("key", &key) == B_OK) {
                _KeyEvent((SDL_Scancode)key, NULL, 0, true);
            }
            break;
        case B_KEY_UP:
        case B_UNMAPPED_KEY_UP: // modifier keys are unmapped
            if (msg->FindInt32("key", &key) == B_OK) {
                _KeyEvent(key, NULL, 0, false);
            }
            break;
        default:
            /* move it after switch{} so it's always handled
               that way we keep Haiku features like:
               - CTRL+Q to close window (and other shortcuts)
               - PrintScreen to make screenshot into /boot/home
               - etc.. */
            // BWindow::DispatchMessage(msg, target);
            break;
        }
        BWindow::DispatchMessage(msg, target);
    }
References _KeyEvent(), _MouseButtonEvent(), _MouseMotionEvent(), _MouseWheelEvent(), and NULL.
FrameMoved()
virtual void SDL_BWin::FrameMoved (BPoint origin) inline virtual
    {
        // Post a message to the BApp so that it can handle the window event
        BMessage msg(BAPP_WINDOW_MOVED);
        msg.AddInt32("window-x", (int)origin.x);
        msg.AddInt32("window-y", (int)origin.y);
        _PostWindowEvent(msg);
        // Perform normal hook operations
        BWindow::FrameMoved(origin);
    }
References _PostWindowEvent(), and BAPP_WINDOW_MOVED.
FrameResized()
void SDL_BWin::FrameResized (float width, float height) inline
    {
        // Post a message to the BApp so that it can handle the window event
        BMessage msg(BAPP_WINDOW_RESIZED);
        msg.AddInt32("window-w", (int)width + 1);
        msg.AddInt32("window-h", (int)height + 1);
        _PostWindowEvent(msg);
        // Perform normal hook operations
        BWindow::FrameResized(width, height);
    }
References _PostWindowEvent(), and BAPP_WINDOW_RESIZED.
GetBitmap()
BBitmap * SDL_BWin::GetBitmap () inline
{ return _bitmap; }
References _bitmap.
GetCurView()
BView * SDL_BWin::GetCurView () inline
{ return _cur_view; }
References _cur_view.
GetID()
int32 SDL_BWin::GetID () inline
{ return _id; }
References _id.
GetView()
SDL_BView * SDL_BWin::GetView () inline
{ return _SDL_View; }
References _SDL_View.
Hide()
void SDL_BWin::Hide () inline
    {
        BWindow::Hide();
        _shown = false;
        BMessage msg(BAPP_HIDE);
        _PostWindowEvent(msg);
    }
References _PostWindowEvent(), _shown, and BAPP_HIDE.
Referenced by MessageReceived().
IsShown()
bool SDL_BWin::IsShown () inline
{ return _shown; }
References _shown.
LockBuffer()
void SDL_BWin::LockBuffer () inline
{ _buffer_locker->Lock(); }
References _buffer_locker.
MessageReceived()
void SDL_BWin::MessageReceived (BMessage * message) inline
    {
        switch (message->what) {
        // Handle commands from SDL
        case BWIN_SET_TITLE:
            _SetTitle(message);
            break;
        case BWIN_MOVE_WINDOW:
            _MoveTo(message);
            break;
        case BWIN_RESIZE_WINDOW:
            _ResizeTo(message);
            break;
        case BWIN_SET_BORDERED:
        {
            bool bEnabled;
            if (message->FindBool("window-border", &bEnabled) == B_OK)
                _SetBordered(bEnabled);
            break;
        }
        case BWIN_SET_RESIZABLE:
        {
            bool bEnabled;
            if (message->FindBool("window-resizable", &bEnabled) == B_OK)
                _SetResizable(bEnabled);
            break;
        }
        case BWIN_SHOW_WINDOW:
            Show();
            break;
        case BWIN_HIDE_WINDOW:
            Hide();
            break;
        case BWIN_MAXIMIZE_WINDOW:
            BWindow::Zoom();
            break;
        case BWIN_MINIMIZE_WINDOW:
            Minimize(true);
            break;
        case BWIN_RESTORE_WINDOW:
            _Restore();
            break;
        case BWIN_FULLSCREEN:
        {
            bool fullscreen;
            if (message->FindBool("fullscreen", &fullscreen) == B_OK)
                _SetFullScreen(fullscreen);
            break;
        }
        case BWIN_MINIMUM_SIZE_WINDOW:
            _SetMinimumSize(message);
            break;
        case BWIN_UPDATE_FRAMEBUFFER:
        {
            BMessage *pendingMessage;
            while ((pendingMessage = MessageQueue()->FindMessage(BWIN_UPDATE_FRAMEBUFFER, 0))) {
                MessageQueue()->RemoveMessage(pendingMessage);
                delete pendingMessage;
            }
            if (_bitmap != NULL) {
#ifdef SDL_VIDEO_OPENGL
                if (_SDL_GLView != NULL && _cur_view == _SDL_GLView) {
                    _SDL_GLView->CopyPixelsIn(_bitmap, B_ORIGIN);
                } else
#endif
                if (_SDL_View != NULL && _cur_view == _SDL_View) {
                    _SDL_View->Draw(Bounds());
                }
            }
            break;
        }
        default:
            // Perform normal message handling
            BWindow::MessageReceived(message);
            break;
        }
    }
References _bitmap, _cur_view, _MoveTo(), _ResizeTo(), _Restore(), _SDL_View, _SetBordered(), _SetFullScreen(), _SetMinimumSize(), _SetResizable(), _SetTitle(), BWIN_FULLSCREEN, BWIN_HIDE_WINDOW, BWIN_MAXIMIZE_WINDOW, BWIN_MINIMIZE_WINDOW, BWIN_MINIMUM_SIZE_WINDOW, BWIN_MOVE_WINDOW, BWIN_RESIZE_WINDOW, BWIN_RESTORE_WINDOW, BWIN_SET_BORDERED, BWIN_SET_RESIZABLE, BWIN_SET_TITLE, BWIN_SHOW_WINDOW, BWIN_UPDATE_FRAMEBUFFER, Hide(), Minimize(), NULL, and Show().
Minimize()
void SDL_BWin::Minimize (bool minimize) inline
    {
        BWindow::Minimize(minimize);
        int32 minState = (minimize ? BAPP_MINIMIZE : BAPP_RESTORE);
        BMessage msg(minState);
        _PostWindowEvent(msg);
    }
References _PostWindowEvent(), BAPP_MINIMIZE, and BAPP_RESTORE.
Referenced by _Restore(), and MessageReceived().
QuitRequested()
bool SDL_BWin::QuitRequested () inline
    {
        BMessage msg(BAPP_WINDOW_CLOSE_REQUESTED);
        _PostWindowEvent(msg);
        // We won't allow a quit unless asked by DestroyWindow()
        return false;
    }
References _PostWindowEvent(), and BAPP_WINDOW_CLOSE_REQUESTED.
RemoveView()
void SDL_BWin::RemoveView () inline
    {
        Lock();
        if (_SDL_View != NULL) {
            SDL_BView *oldView = _SDL_View;
            _SDL_View = NULL;
            UpdateCurrentView();
            delete oldView;
        }
        Unlock();
    }
References _SDL_View, NULL, and UpdateCurrentView().
ScreenChanged()
void SDL_BWin::ScreenChanged (BRect screenFrame, color_space depth) inline
    {
        if (_fullscreen) {
            MoveTo(screenFrame.left, screenFrame.top);
            ResizeTo(screenFrame.Width(), screenFrame.Height());
        }
    }
References _fullscreen.
SetBitmap()
void SDL_BWin::SetBitmap (BBitmap * bitmap) inline
    {
        _bitmap = bitmap;
        if (_SDL_View != NULL)
            _SDL_View->SetBitmap(bitmap);
    }
References _bitmap, _SDL_View, and NULL.
SetCurrentView()
void SDL_BWin::SetCurrentView (BView * view) inline
    {
        if (_cur_view != view) {
            if (_cur_view != NULL)
                RemoveChild(_cur_view);
            _cur_view = view;
            if (_cur_view != NULL)
                AddChild(_cur_view);
        }
    }
References _cur_view, and NULL.
Referenced by UpdateCurrentView().
SetID()
void SDL_BWin::SetID (int32 id) inline
{ _id = id; }
References _id.
Show()
void SDL_BWin::Show () inline
    {
        while (IsHidden()) {
            BWindow::Show();
        }
        _shown = true;
        BMessage msg(BAPP_SHOW);
        _PostWindowEvent(msg);
    }
References _PostWindowEvent(), _shown, and BAPP_SHOW.
Referenced by _Restore(), and MessageReceived().
UnlockBuffer()
void SDL_BWin::UnlockBuffer () inline
{ _buffer_locker->Unlock(); }
References _buffer_locker.
UpdateCurrentView()
void SDL_BWin::UpdateCurrentView () inline
    {
#ifdef SDL_VIDEO_OPENGL
        if (_SDL_GLView != NULL) {
            SetCurrentView(_SDL_GLView);
        } else
#endif
        if (_SDL_View != NULL) {
            SetCurrentView(_SDL_View);
        } else {
            SetCurrentView(NULL);
        }
    }
References _SDL_View, NULL, and SetCurrentView().
Referenced by CreateView(), and RemoveView().
WindowActivated()
void SDL_BWin::WindowActivated (bool active) inline
    {
        BMessage msg(BAPP_KEYBOARD_FOCUS); // Mouse focus sold separately
        msg.AddBool("focusGained", active);
        _PostWindowEvent(msg);
    }
References _PostWindowEvent(), active, and BAPP_KEYBOARD_FOCUS.
Zoom()
void SDL_BWin::Zoom (BPoint origin, float width, float height) inline
    {
        BMessage msg(BAPP_MAXIMIZE); // Closest thing to maximization Haiku has
        _PostWindowEvent(msg);
        // Before the window zooms, record its size
        if (!_prev_frame)
            _prev_frame = new BRect(Frame());
        // Perform normal hook operations
        BWindow::Zoom(origin, width, height);
    }
References _PostWindowEvent(), _prev_frame, and BAPP_MAXIMIZE.
Field Documentation
_bitmap
BBitmap* SDL_BWin::_bitmap private
Referenced by GetBitmap(), MessageReceived(), SDL_BWin(), and SetBitmap().
_bordered
bool SDL_BWin::_bordered private
Referenced by _SetBordered(), and _SetFullScreen().
_buffer_locker
BLocker* SDL_BWin::_buffer_locker private
Referenced by LockBuffer(), SDL_BWin(), UnlockBuffer(), and ~SDL_BWin().
_cur_view
BView* SDL_BWin::_cur_view private
Referenced by GetCurView(), MessageReceived(), SDL_BWin(), SetCurrentView(), and ~SDL_BWin().
_fullscreen
bool SDL_BWin::_fullscreen private
Referenced by _MoveTo(), _ResizeTo(), _Restore(), _SetBordered(), _SetFullScreen(), _SetResizable(), ScreenChanged(), and SDL_BWin().
_id
int32 SDL_BWin::_id private
Referenced by _PostWindowEvent(), GetID(), and SetID().
_inhibit_resize
bool SDL_BWin::_inhibit_resize private
Referenced by SDL_BWin().
_last_buttons
int32 SDL_BWin::_last_buttons private
Referenced by _MouseButtonEvent(), and SDL_BWin().
_mouse_focused
bool SDL_BWin::_mouse_focused private
Referenced by _MouseFocusEvent(), _MouseMotionEvent(), and SDL_BWin().
_non_fullscreen_frame
BRect SDL_BWin::_non_fullscreen_frame private
Referenced by _MoveTo(), _ResizeTo(), and _SetFullScreen().
_prev_frame
BRect* SDL_BWin::_prev_frame private
Referenced by _Restore(), SDL_BWin(), Zoom(), and ~SDL_BWin().
_resizable
bool SDL_BWin::_resizable private
Referenced by _SetFullScreen(), and _SetResizable().
_SDL_View
SDL_BView* SDL_BWin::_SDL_View private
Referenced by CreateView(), GetView(), MessageReceived(), RemoveView(), SDL_BWin(), SetBitmap(), UpdateCurrentView(), and ~SDL_BWin().
_shown
bool SDL_BWin::_shown private
Referenced by Hide(), IsShown(), SDL_BWin(), and Show().
The documentation for this class was generated from the following file:
SDL-main/src/video/haiku/SDL_BWin.h