SDL3: SDL-main/src/core/gdk/SDL_gdk.cpp File Reference
SDL_gdk.cpp File Reference
#include "SDL_internal.h"
#include "../windows/SDL_windows.h"
#include "../../events/SDL_events_c.h"
#include <XGameRuntime.h>
#include <xsapi-c/services_c.h>
#include <appnotify.h>
Functions
void GDK_DispatchTaskQueue (void)
bool GDK_RegisterChangeNotifications (void)
void GDK_UnregisterChangeNotifications (void)
void SDL_GDKSuspendComplete ()
bool SDL_GetGDKDefaultUser (XUserHandle *outUserHandle)
bool SDL_GetGDKTaskQueue (XTaskQueueHandle *outTaskQueue)
Variables
static XTaskQueueHandle GDK_GlobalTaskQueue
PAPPCONSTRAIN_REGISTRATION hCPLM = {}
PAPPSTATE_REGISTRATION hPLM = {}
HANDLE plmSuspendComplete = nullptr
Function Documentation
GDK_DispatchTaskQueue()
void GDK_DispatchTaskQueue (void)
{
    /* If there is no global task queue, don't do anything.
     * This gives the option to opt-out for those who want to handle everything themselves.
     */
    if (GDK_GlobalTaskQueue) {
        // Dispatch any callbacks which are ready.
        while (XTaskQueueDispatch(GDK_GlobalTaskQueue, XTaskQueuePort::Completion, 0))
            ;
    }
}
References GDK_GlobalTaskQueue.
GDK_RegisterChangeNotifications()
bool GDK_RegisterChangeNotifications (void)
{
    // Register suspend/resume handling
    plmSuspendComplete = CreateEventEx(nullptr, nullptr, 0, EVENT_MODIFY_STATE | SYNCHRONIZE);
    if (!plmSuspendComplete) {
        return SDL_SetError("[GDK] Unable to create plmSuspendComplete event");
    }
    auto rascn = [](BOOLEAN quiesced, PVOID context) {
        SDL_LogDebug(SDL_LOG_CATEGORY_APPLICATION, "[GDK] in RegisterAppStateChangeNotification handler");
        if (quiesced) {
            ResetEvent(plmSuspendComplete);
            SDL_SendAppEvent(SDL_EVENT_DID_ENTER_BACKGROUND);
            // To defer suspension, we must wait to exit this callback.
            // IMPORTANT: The app must call SDL_GDKSuspendComplete() to release this lock.
            (void)WaitForSingleObject(plmSuspendComplete, INFINITE);
            SDL_LogDebug(SDL_LOG_CATEGORY_APPLICATION, "[GDK] in RegisterAppStateChangeNotification handler: plmSuspendComplete event signaled.");
        } else {
            SDL_SendAppEvent(SDL_EVENT_WILL_ENTER_FOREGROUND);
        }
    };
    if (RegisterAppStateChangeNotification(rascn, NULL, &hPLM)) {
        return SDL_SetError("[GDK] Unable to call RegisterAppStateChangeNotification");
    }
    // Register constrain/unconstrain handling
    auto raccn = [](BOOLEAN constrained, PVOID context) {
        SDL_LogDebug(SDL_LOG_CATEGORY_APPLICATION, "[GDK] in RegisterAppConstrainedChangeNotification handler");
        SDL_VideoDevice *_this = SDL_GetVideoDevice();
        if (_this) {
            if (constrained && !((_this->windows) && _this->windows->text_input_active)) {
                SDL_SetKeyboardFocus(NULL);
            } else {
                SDL_SetKeyboardFocus(_this->windows);
            }
        }
    };
    if (RegisterAppConstrainedChangeNotification(raccn, NULL, &hCPLM)) {
        return SDL_SetError("[GDK] Unable to call RegisterAppConstrainedChangeNotification");
    }
    return true;
}
References _this, context, hCPLM, hPLM, NULL, plmSuspendComplete, SDL_EVENT_DID_ENTER_BACKGROUND, SDL_EVENT_WILL_ENTER_FOREGROUND, SDL_GetVideoDevice(), SDL_LOG_CATEGORY_APPLICATION, SDL_LogDebug(), SDL_SendAppEvent(), SDL_SetError(), SDL_SetKeyboardFocus(), and void().
Referenced by SDL_RunApp().
GDK_UnregisterChangeNotifications()
void GDK_UnregisterChangeNotifications (void)
{
    // Unregister suspend/resume handling
    UnregisterAppStateChangeNotification(hPLM);
    CloseHandle(plmSuspendComplete);
    // Unregister constrain/unconstrain handling
    UnregisterAppConstrainedChangeNotification(hCPLM);
}
References hCPLM, hPLM, and plmSuspendComplete.
Referenced by SDL_RunApp().
SDL_GDKSuspendComplete()
void SDL_GDKSuspendComplete (void)
Callback from the application to let the suspend continue.
This function is only needed for Xbox GDK support; all other platforms will do nothing and set an "unsupported" error message.
Since
This function is available since SDL 3.2.0.
{
    if (plmSuspendComplete) {
        SetEvent(plmSuspendComplete);
    }
}
References plmSuspendComplete.
SDL_GetGDKDefaultUser()
bool SDL_GetGDKDefaultUser (XUserHandle * outUserHandle)
{
    XAsyncBlock block = { 0 };
    HRESULT result;
    if (FAILED(result = XUserAddAsync(XUserAddOptions::AddDefaultUserAllowingUI, &block))) {
        return WIN_SetErrorFromHRESULT("XUserAddAsync", result);
    }
    do {
        result = XUserAddResult(&block, outUserHandle);
    } while (result == E_PENDING);
    if (FAILED(result)) {
        return WIN_SetErrorFromHRESULT("XUserAddResult", result);
    }
    return true;
}
References FAILED, and WIN_SetErrorFromHRESULT().
Referenced by SDL_SYS_GetPrefPath().
SDL_GetGDKTaskQueue()
bool SDL_GetGDKTaskQueue (XTaskQueueHandle * outTaskQueue)
{
    // If this is the first call, first create the global task queue.
    if (!GDK_GlobalTaskQueue) {
        HRESULT hr;
        hr = XTaskQueueCreate(XTaskQueueDispatchMode::ThreadPool,
                              XTaskQueueDispatchMode::Manual,
                              &GDK_GlobalTaskQueue);
        if (FAILED(hr)) {
            return SDL_SetError("[GDK] Could not create global task queue");
        }
        // The initial call gets the non-duplicated handle so they can clean it up
        *outTaskQueue = GDK_GlobalTaskQueue;
    } else {
        // Duplicate the global task queue handle into outTaskQueue
        if (FAILED(XTaskQueueDuplicateHandle(GDK_GlobalTaskQueue, outTaskQueue))) {
            return SDL_SetError("[GDK] Unable to acquire global task queue");
        }
    }
    return true;
}
References FAILED, GDK_GlobalTaskQueue, and SDL_SetError().
Referenced by SDL_RunApp().
Variable Documentation
GDK_GlobalTaskQueue
XTaskQueueHandle GDK_GlobalTaskQueue static
Referenced by GDK_DispatchTaskQueue(), and SDL_GetGDKTaskQueue().
hCPLM
PAPPCONSTRAIN_REGISTRATION hCPLM = {}
{};
Referenced by GDK_RegisterChangeNotifications(), and GDK_UnregisterChangeNotifications().
hPLM
PAPPSTATE_REGISTRATION hPLM = {}
{};
Referenced by GDK_RegisterChangeNotifications(), and GDK_UnregisterChangeNotifications().
plmSuspendComplete
HANDLE plmSuspendComplete = nullptr
Referenced by GDK_RegisterChangeNotifications(), GDK_UnregisterChangeNotifications(), and SDL_GDKSuspendComplete().