SDL3: SDL-main/src/core/openbsd/SDL_wscons.h File Reference
SDL_wscons.h File Reference
Functions
void SDL_WSCONS_Init (void)
void SDL_WSCONS_PumpEvents (void)
void SDL_WSCONS_Quit (void)
Function Documentation
SDL_WSCONS_Init()
void SDL_WSCONS_Init (void)
{
    inputs[0] = SDL_WSCONS_Init_Keyboard("/dev/wskbd0");
    inputs[1] = SDL_WSCONS_Init_Keyboard("/dev/wskbd1");
    inputs[2] = SDL_WSCONS_Init_Keyboard("/dev/wskbd2");
    inputs[3] = SDL_WSCONS_Init_Keyboard("/dev/wskbd3");
    mouseInputData = SDL_WSCONS_Init_Mouse();
    return;
}
References inputs, mouseInputData, SDL_WSCONS_Init_Keyboard(), and SDL_WSCONS_Init_Mouse().
SDL_WSCONS_PumpEvents()
void SDL_WSCONS_PumpEvents (void)
{
    int i = 0;
    for (i = 0; i < 4; i++) {
        updateKeyboard(inputs[i]);
    }
    if (mouseInputData) {
        updateMouse(mouseInputData);
    }
}
References inputs, mouseInputData, updateKeyboard(), and updateMouse().
SDL_WSCONS_Quit()
void SDL_WSCONS_Quit (void)
{
    int i = 0;
    SDL_WSCONS_input_data *input = NULL;
    SDL_WSCONS_Quit_Mouse(mouseInputData);
    mouseInputData = NULL;
    for (i = 0; i < 4; i++) {
        input = inputs[i];
        if (input) {
            if (input->fd != -1 && input->fd != 0) {
                ioctl(input->fd, WSKBDIO_SETLEDS, &input->origledstate);
                close(input->fd);
                input->fd = -1;
            }
            SDL_free(input);
            input = NULL;
        }
        inputs[i] = NULL;
    }
}
References inputs, mouseInputData, NULL, SDL_free(), and SDL_WSCONS_Quit_Mouse().