SDL3: SDL-main/src/tray/dummy/SDL_tray.c File Reference
SDL_tray.c File Reference
#include "SDL_internal.h"
#include "../SDL_tray_utils.h"
Functions
void SDL_ClickTrayEntry (SDL_TrayEntry *entry)
SDL_Tray * SDL_CreateTray (SDL_Surface *icon, const char *tooltip)
SDL_TrayMenu * SDL_CreateTrayMenu (SDL_Tray *tray)
SDL_TrayMenu * SDL_CreateTraySubmenu (SDL_TrayEntry *entry)
void SDL_DestroyTray (SDL_Tray *tray)
const SDL_TrayEntry ** SDL_GetTrayEntries (SDL_TrayMenu *menu, int *count)
bool SDL_GetTrayEntryChecked (SDL_TrayEntry *entry)
bool SDL_GetTrayEntryEnabled (SDL_TrayEntry *entry)
const char * SDL_GetTrayEntryLabel (SDL_TrayEntry *entry)
SDL_TrayMenu * SDL_GetTrayEntryParent (SDL_TrayEntry *entry)
SDL_TrayMenu * SDL_GetTrayMenu (SDL_Tray *tray)
SDL_TrayEntry * SDL_GetTrayMenuParentEntry (SDL_TrayMenu *menu)
SDL_Tray * SDL_GetTrayMenuParentTray (SDL_TrayMenu *menu)
SDL_TrayMenu * SDL_GetTraySubmenu (SDL_TrayEntry *entry)
SDL_TrayEntry * SDL_InsertTrayEntryAt (SDL_TrayMenu *menu, int pos, const char *label, SDL_TrayEntryFlags flags)
bool SDL_IsTraySupported (void)
void SDL_RemoveTrayEntry (SDL_TrayEntry *entry)
void SDL_SetTrayEntryCallback (SDL_TrayEntry *entry, SDL_TrayCallback callback, void *userdata)
void SDL_SetTrayEntryChecked (SDL_TrayEntry *entry, bool checked)
void SDL_SetTrayEntryEnabled (SDL_TrayEntry *entry, bool enabled)
void SDL_SetTrayEntryLabel (SDL_TrayEntry *entry, const char *label)
void SDL_SetTrayIcon (SDL_Tray *tray, SDL_Surface *icon)
void SDL_SetTrayTooltip (SDL_Tray *tray, const char *tooltip)
void SDL_UpdateTrays (void)
Function Documentation
SDL_ClickTrayEntry()
void SDL_ClickTrayEntry (SDL_TrayEntry * entry)
Simulate a click on a tray entry.
Parameters
entry The entry to activate.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
{
}
SDL_CreateTray()
SDL_Tray * SDL_CreateTray (SDL_Surface * icon, const char * tooltip)
Create an icon to be placed in the operating system's tray, or equivalent.
Many platforms advise not using a system tray unless persistence is a necessary feature. Avoid needlessly creating a tray icon, as the user may feel like it clutters their interface.
Using tray icons require the video subsystem.
Parameters
icon a surface to be used as icon. May be NULL.
tooltip a tooltip to be displayed when the mouse hovers the icon in UTF-8 encoding. Not supported on all platforms. May be NULL.
Returns
The newly created system tray icon.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenu
SDL_DestroyTray
{
    SDL_Unsupported();
    return NULL;
}
SDL_CreateTrayMenu()
SDL_TrayMenu * SDL_CreateTrayMenu (SDL_Tray * tray)
Create a menu for a system tray.
This should be called at most once per tray icon.
This function does the same thing as SDL_CreateTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_GetTrayMenu
SDL_GetTrayMenuParentTray
{
    SDL_InvalidParamError("tray");
    return NULL;
}
SDL_CreateTraySubmenu()
SDL_TrayMenu * SDL_CreateTraySubmenu (SDL_TrayEntry * entry)
Create a submenu for a system tray entry.
This should be called at most once per tray entry.
This function does the same thing as SDL_CreateTrayMenu, except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_GetTraySubmenu
SDL_GetTrayMenuParentEntry
{
    SDL_InvalidParamError("entry");
    return NULL;
}
SDL_DestroyTray()
void SDL_DestroyTray (SDL_Tray * tray)
Destroys a tray object.
This also destroys all associated menus and entries.
Parameters
tray the tray icon to be destroyed.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
}
SDL_GetTrayEntries()
const SDL_TrayEntry ** SDL_GetTrayEntries (SDL_TrayMenu * menu, int * count)
Returns a list of entries in the menu, in order.
Parameters
menu The menu to get entries from.
count An optional pointer to obtain the number of entries in the menu.
Returns
a NULL-terminated list of entries within the given menu. The pointer becomes invalid when any function that inserts or deletes entries in the menu is called.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveTrayEntry
SDL_InsertTrayEntryAt
{
    SDL_InvalidParamError("menu");
    return NULL;
}
SDL_GetTrayEntryChecked()
bool SDL_GetTrayEntryChecked (SDL_TrayEntry * entry)
Gets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be read.
Returns
true if the entry is checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryChecked
{
    return SDL_InvalidParamError("entry");
}
Referenced by SDL_ClickTrayEntry(), and TrayWindowProc().
SDL_GetTrayEntryEnabled()
bool SDL_GetTrayEntryEnabled (SDL_TrayEntry * entry)
Gets whether or not an entry is enabled.
Parameters
entry the entry to be read.
Returns
true if the entry is enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryEnabled
{
    return SDL_InvalidParamError("entry");
}
SDL_GetTrayEntryLabel()
const char * SDL_GetTrayEntryLabel (SDL_TrayEntry * entry)
Gets the label of an entry.
If the returned value is NULL, the entry is a separator.
Parameters
entry the entry to be read.
Returns
the label of the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryLabel
{
    SDL_InvalidParamError("entry");
    return NULL;
}
SDL_GetTrayEntryParent()
SDL_TrayMenu * SDL_GetTrayEntryParent (SDL_TrayEntry * entry)
Gets the menu containing a certain tray entry.
Parameters
entry the entry for which to get the parent menu.
Returns
the parent menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
{
    SDL_InvalidParamError("entry");
    return NULL;
}
SDL_GetTrayMenu()
SDL_TrayMenu * SDL_GetTrayMenu (SDL_Tray * tray)
Gets a previously created tray menu.
You should have called SDL_CreateTrayMenu() on the tray object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_CreateTrayMenu
{
    SDL_InvalidParamError("tray");
    return NULL;
}
SDL_GetTrayMenuParentEntry()
SDL_TrayEntry * SDL_GetTrayMenuParentEntry (SDL_TrayMenu * menu)
Gets the entry for which the menu is a submenu, if the current menu is a submenu.
Either this function or SDL_GetTrayMenuParentTray() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent entry.
Returns
the parent entry, or NULL if this menu is not a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTraySubmenu
SDL_GetTrayMenuParentTray
{
    SDL_InvalidParamError("menu");
    return NULL;
}
SDL_GetTrayMenuParentTray()
SDL_Tray * SDL_GetTrayMenuParentTray (SDL_TrayMenu * menu)
Gets the tray for which this menu is the first-level menu, if the current menu isn't a submenu.
Either this function or SDL_GetTrayMenuParentEntry() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent enttrayry.
Returns
the parent tray, or NULL if this menu is a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenuParentEntry
{
    SDL_InvalidParamError("menu");
    return NULL;
}
SDL_GetTraySubmenu()
SDL_TrayMenu * SDL_GetTraySubmenu (SDL_TrayEntry * entry)
Gets a previously created tray entry submenu.
You should have called SDL_CreateTraySubmenu() on the entry object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTrayMenu(), except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_CreateTraySubmenu
{
    return NULL;
}
SDL_InsertTrayEntryAt()
SDL_TrayEntry * SDL_InsertTrayEntryAt (SDL_TrayMenu * menu, int pos, const char * label, SDL_TrayEntryFlags flags)
Insert a tray entry at a given position.
If label is NULL, the entry will be a separator. Many functions won't work for an entry that is a separator.
An entry does not need to be destroyed; it will be destroyed with the tray.
Parameters
menu the menu to append the entry to.
pos the desired position for the new entry. Entries at or following this place will be moved. If pos is -1, the entry is appended.
label the text to be displayed on the entry, in UTF-8 encoding, or NULL for a separator.
flags a combination of flags, some of which are mandatory.
Returns
the newly created entry, or NULL if pos is out of bounds.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_TrayEntryFlags
SDL_GetTrayEntries
SDL_RemoveTrayEntry
SDL_GetTrayEntryParent
{
    SDL_InvalidParamError("menu");
    return NULL;
}
SDL_IsTraySupported()
bool SDL_IsTraySupported (void)
Check whether or not tray icons can be created.
Note that this function does not guarantee that SDL_CreateTray() will or will not work; you should still check SDL_CreateTray() for errors.
Using tray icons require the video subsystem.
Returns
true if trays are available, false otherwise.
Thread Safety
This function should only be called on the main thread. It will return false if not called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateTray
{
    return false;
}
SDL_RemoveTrayEntry()
void SDL_RemoveTrayEntry (SDL_TrayEntry * entry)
Removes a tray entry.
Parameters
entry The entry to be deleted.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
}
SDL_SetTrayEntryCallback()
void SDL_SetTrayEntryCallback (SDL_TrayEntry * entry, SDL_TrayCallback callback, void * userdata)
Sets a callback to be invoked when the entry is selected.
Parameters
entry the entry to be updated.
callback a callback to be invoked when the entry is selected.
userdata an optional pointer to pass extra data to the callback when it will be invoked.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
}
SDL_SetTrayEntryChecked()
void SDL_SetTrayEntryChecked (SDL_TrayEntry * entry, bool checked)
Sets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be updated.
checked true if the entry should be checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryChecked
{
}
Referenced by SDL_ClickTrayEntry(), and TrayWindowProc().
SDL_SetTrayEntryEnabled()
void SDL_SetTrayEntryEnabled (SDL_TrayEntry * entry, bool enabled)
Sets whether or not an entry is enabled.
Parameters
entry the entry to be updated.
enabled true if the entry should be enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryEnabled
{
}
SDL_SetTrayEntryLabel()
void SDL_SetTrayEntryLabel (SDL_TrayEntry * entry, const char * label)
Sets the label of an entry.
An entry cannot change between a separator and an ordinary entry; that is, it is not possible to set a non-NULL label on an entry that has a NULL label (separators), or to set a NULL label to an entry that has a non-NULL label. The function will silently fail if that happens.
Parameters
entry the entry to be updated.
label the new label for the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryLabel
{
}
SDL_SetTrayIcon()
void SDL_SetTrayIcon (SDL_Tray * tray, SDL_Surface * icon)
Updates the system tray icon's icon.
Parameters
tray the tray icon to be updated.
icon the new icon. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
}
SDL_SetTrayTooltip()
void SDL_SetTrayTooltip (SDL_Tray * tray, const char * tooltip)
Updates the system tray icon's tooltip.
Parameters
tray the tray icon to be updated.
tooltip the new tooltip in UTF-8 encoding. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
}
SDL_UpdateTrays()
void SDL_UpdateTrays (void)
Update the trays.
This is called automatically by the event loop and is only needed if you're using trays but aren't handling SDL events.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
}