SDL3: SDL-main/src/haptic/SDL_haptic_c.h File Reference
SDL_haptic_c.h File Reference
Functions
bool SDL_InitHaptics (void)
void SDL_QuitHaptics (void)
Function Documentation
SDL_InitHaptics()
bool SDL_InitHaptics (void) extern
{
    if (!SDL_SYS_HapticInit()) {
        return false;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (!SDL_HIDAPI_HapticInit()) {
        SDL_SYS_HapticQuit();
        return false;
    }
    #endif
    return true;
}
References SDL_HIDAPI_HapticInit(), SDL_SYS_HapticInit(), and SDL_SYS_HapticQuit().
Referenced by SDL_InitSubSystem().
SDL_QuitHaptics()
void SDL_QuitHaptics (void) extern
{
    while (SDL_haptics) {
        SDL_CloseHaptic(SDL_haptics);
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    SDL_HIDAPI_HapticQuit();
    #endif
    SDL_SYS_HapticQuit();
}
References SDL_CloseHaptic(), SDL_haptics, SDL_HIDAPI_HapticQuit(), and SDL_SYS_HapticQuit().
Referenced by SDL_QuitSubSystem().