SDL3: SDL-main/src/locale/windows/SDL_syslocale.c File Reference
SDL_syslocale.c File Reference
#include "SDL_internal.h"
#include "../../core/windows/SDL_windows.h"
#include "../SDL_syslocale.h"
Macros
#define MUI_LANGUAGE_NAME 0x8
Typedefs
typedef BOOL(WINAPI * pfnGetUserPreferredUILanguages) (DWORD, PULONG, WCHAR *, PULONG)
Functions
bool SDL_SYS_GetPreferredLocales (char *buf, size_t buflen)
static bool SDL_SYS_GetPreferredLocales_vista (char *buf, size_t buflen)
static bool SDL_SYS_GetPreferredLocales_winxp (char *buf, size_t buflen)
Variables
static HMODULE kernel32 = 0
static pfnGetUserPreferredUILanguages pGetUserPreferredUILanguages = NULL
Macro Definition Documentation
MUI_LANGUAGE_NAME
#define MUI_LANGUAGE_NAME 0x8
Referenced by SDL_SYS_GetPreferredLocales_vista().
Typedef Documentation
pfnGetUserPreferredUILanguages
typedef BOOL(WINAPI * pfnGetUserPreferredUILanguages) (DWORD, PULONG, WCHAR *, PULONG)
Function Documentation
SDL_SYS_GetPreferredLocales()
bool SDL_SYS_GetPreferredLocales (char * buf, size_t buflen)
{
    if (!kernel32) {
        kernel32 = GetModuleHandle(TEXT("kernel32.dll"));
        if (kernel32) {
            pGetUserPreferredUILanguages = (pfnGetUserPreferredUILanguages)GetProcAddress(kernel32, "GetUserPreferredUILanguages");
        }
    }
    if (!pGetUserPreferredUILanguages) {
        return SDL_SYS_GetPreferredLocales_winxp(buf, buflen); // this is always available
    } else {
        return SDL_SYS_GetPreferredLocales_vista(buf, buflen); // available on Vista and later.
    }
}
References kernel32, pGetUserPreferredUILanguages, SDL_SYS_GetPreferredLocales_vista(), and SDL_SYS_GetPreferredLocales_winxp().
SDL_SYS_GetPreferredLocales_vista()
bool SDL_SYS_GetPreferredLocales_vista (char * buf, size_t buflen) static
{
    ULONG numlangs = 0;
    WCHAR *wbuf = NULL;
    ULONG wbuflen = 0;
    bool isstack;
    SDL_assert(pGetUserPreferredUILanguages != NULL);
    pGetUserPreferredUILanguages(MUI_LANGUAGE_NAME, &numlangs, NULL, &wbuflen);
    wbuf = SDL_small_alloc(WCHAR, wbuflen, &isstack);
    if (!wbuf) {
        return false;
    }
    if (!pGetUserPreferredUILanguages(MUI_LANGUAGE_NAME, &numlangs, wbuf, &wbuflen)) {
        SDL_SYS_GetPreferredLocales_winxp(buf, buflen); // oh well, try the fallback.
    } else {
        const ULONG endidx = (ULONG)SDL_min(buflen, wbuflen - 1);
        ULONG str_start = 0;
        ULONG i;
        for (i = 0; i < endidx; i++) {
            const char ch = (char)wbuf[i]; // these should all be low-ASCII, safe to cast
            if (ch == '\0') {
                buf[i] = ','; // change null separators to commas
                str_start = i;
            } else if (ch == '-') {
                buf[i] = '_'; // change '-' to '_'
            } else {
                buf[i] = ch; // copy through as-is.
            }
        }
        buf[str_start] = '\0'; // terminate string, chop off final ','
    }
    SDL_small_free(wbuf, isstack);
    return true;
}
References MUI_LANGUAGE_NAME, NULL, pGetUserPreferredUILanguages, SDL_assert, SDL_min, SDL_small_alloc, SDL_small_free, and SDL_SYS_GetPreferredLocales_winxp().
Referenced by SDL_SYS_GetPreferredLocales().
SDL_SYS_GetPreferredLocales_winxp()
bool SDL_SYS_GetPreferredLocales_winxp (char * buf, size_t buflen) static
{
    char lang[16];
    char country[16];
    const int langrc = GetLocaleInfoA(LOCALE_USER_DEFAULT,
                                      LOCALE_SISO639LANGNAME,
                                      lang, sizeof(lang));
    const int ctryrc = GetLocaleInfoA(LOCALE_USER_DEFAULT,
                                      LOCALE_SISO3166CTRYNAME,
                                      country, sizeof(country));
    /* Win95 systems will fail, because they don't have LOCALE_SISO*NAME ... */
    if (langrc == 0) {
        return SDL_SetError("Couldn't obtain language info");
    } else {
        (void)SDL_snprintf(buf, buflen, "%s%s%s", lang, ctryrc ? "_" : "", ctryrc ? country : "");
        return true;
    }
}
References SDL_SetError(), SDL_snprintf(), and void().
Referenced by SDL_SYS_GetPreferredLocales(), and SDL_SYS_GetPreferredLocales_vista().
Variable Documentation
kernel32
HMODULE kernel32 = 0 static
Referenced by SDL_CreateCondition(), SDL_CreateRWLock(), and SDL_SYS_GetPreferredLocales().
pGetUserPreferredUILanguages
pfnGetUserPreferredUILanguages pGetUserPreferredUILanguages = NULL static
Referenced by SDL_SYS_GetPreferredLocales(), and SDL_SYS_GetPreferredLocales_vista().