SDL3: SDL-main/src/dialog/unix/SDL_zenitydialog.h File Reference
SDL_zenitydialog.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_Zenity_detect (void)
void SDL_Zenity_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props)
Function Documentation
SDL_Zenity_detect()
bool SDL_Zenity_detect (void) extern
Returns
non-zero if available, zero if unavailable
{
    const char *args[] = {
        "zenity", "--version", NULL
    };
    int status = -1;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, args);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROCESS_STDIO_NULL);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_PROCESS_STDIO_NULL);
    SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDERR_NUMBER, SDL_PROCESS_STDIO_NULL);
    SDL_Process *process = SDL_CreateProcessWithProperties(props);
    SDL_DestroyProperties(props);
    if (process) {
        SDL_WaitProcess(process, true, &status);
        SDL_DestroyProcess(process);
    }
    return (status == 0);
}
References NULL, SDL_CreateProcessWithProperties(), SDL_CreateProperties(), SDL_DestroyProcess(), SDL_DestroyProperties(), SDL_PROCESS_STDIO_NULL, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, SDL_PROP_PROCESS_CREATE_STDERR_NUMBER, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_SetNumberProperty(), SDL_SetPointerProperty(), and SDL_WaitProcess().
Referenced by detect_available_methods().
SDL_Zenity_ShowFileDialogWithProperties()
void SDL_Zenity_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void * userdata, SDL_PropertiesID props) extern
{
    zenityArgs *args = create_zenity_args(type, callback, userdata, props);
    if (!args) {
        callback(userdata, NULL, -1);
        return;
    }
    SDL_Thread *thread = SDL_CreateThread(run_zenity_thread, "SDL_ZenityFileDialog", (void *)args);
    if (!thread) {
        free_zenity_args(args);
        callback(userdata, NULL, -1);
        return;
    }
    SDL_DetachThread(thread);
}
References create_zenity_args(), free_zenity_args(), NULL, run_zenity_thread(), SDL_CreateThread, and SDL_DetachThread().
Referenced by detect_available_methods().