SDL3: SDL-main/src/stdlib/SDL_murmur3.c File Reference
SDL_murmur3.c File Reference
#include "SDL_internal.h"
Functions
static SDL_INLINE Uint32 murmur_32_scramble (Uint32 k)
Uint32 SDLCALL SDL_murmur3_32 (const void *data, size_t len, Uint32 seed)
Function Documentation
murmur_32_scramble()
SDL_INLINE Uint32 murmur_32_scramble (Uint32 k) static
{
    k *= 0xcc9e2d51;
    k = (k << 15) | (k >> 17);
    k *= 0x1b873593;
    return k;
}
References SDL_INLINE.
Referenced by SDL_murmur3_32().
SDL_murmur3_32()
Uint32 SDLCALL SDL_murmur3_32 (const void * data, size_t len, Uint32 seed)
Calculate a 32-bit MurmurHash3 value for a block of data.
https://en.wikipedia.org/wiki/MurmurHash
A seed may be specified, which changes the final results consistently, but this does not work like SDL_crc16 and SDL_crc32: you can't feed a previous result from this function back into itself as the next seed value to calculate a hash in chunks; it won't produce the same hash as it would if the same data was provided in a single call.
If you aren't sure what to provide for a seed, zero is fine. Murmur3 is not cryptographically secure, so it shouldn't be used for hashing top-secret data.
Parameters
data the data to be hashed.
len the size of data, in bytes.
seed a value that alters the final hash value.
Returns
a Murmur3 32-bit hash value.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    const Uint8 *bytes = (const Uint8 *)data;
    Uint32 hash = seed;
    Uint32 k;
    // Read in groups of 4.
    if ((((uintptr_t)bytes) & 3) == 0) {
        // We can do aligned 32-bit reads
        for (size_t i = len >> 2; i--; ) {
            k = *(const Uint32 *)bytes;
            k = SDL_Swap32LE(k);
            bytes += sizeof(Uint32);
            hash ^= murmur_32_scramble(k);
            hash = (hash << 13) | (hash >> 19);
            hash = hash * 5 + 0xe6546b64;
        }
    } else {
        for (size_t i = len >> 2; i--; ) {
            SDL_memcpy(&k, bytes, sizeof(Uint32));
            k = SDL_Swap32LE(k);
            bytes += sizeof(Uint32);
            hash ^= murmur_32_scramble(k);
            hash = (hash << 13) | (hash >> 19);
            hash = hash * 5 + 0xe6546b64;
        }
    }
    // Read the rest.
    size_t left = (len & 3);
    if (left) {
        k = 0;
        for (size_t i = left; i--; ) {
            k <<= 8;
            k |= bytes[i];
        }
        // A swap is *not* necessary here because the preceding loop already
        // places the low bytes in the low places according to whatever endianness
        // we use. Swaps only apply when the memory is copied in a chunk.
        hash ^= murmur_32_scramble(k);
    }
    /* Finalize. */
    hash ^= len;
    hash ^= hash >> 16;
    hash *= 0x85ebca6b;
    hash ^= hash >> 13;
    hash *= 0xc2b2ae35;
    hash ^= hash >> 16;
    return hash;
}
References left, murmur_32_scramble(), SDL_memcpy, SDL_Swap32LE, and SDLCALL.
Referenced by SDL_HashPointer().