SDL3: SDL-main/include/SDL3/SDL_guid.h File Reference
SDL_guid.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_GUID
Typedefs
typedef struct SDL_GUID SDL_GUID
Functions
SDL_DECLSPEC void SDLCALL SDL_GUIDToString (SDL_GUID guid, char *pszGUID, int cbGUID)
SDL_DECLSPEC SDL_GUID SDLCALL SDL_StringToGUID (const char *pchGUID)
Typedef Documentation
SDL_GUID
typedef struct SDL_GUID SDL_GUID
CategoryGUID
A GUID is a 128-bit value that represents something that is uniquely identifiable by this value: "globally unique."
SDL provides functions to convert a GUID to/from a string. An SDL_GUID is a 128-bit identifier for an input device that identifies that device across runs of SDL programs on the same platform.
If the device is detached and then re-attached to a different port, or if the base system is rebooted, the device should still report the same GUID.
GUIDs are as precise as possible but are not guaranteed to distinguish physically distinct but equivalent devices. For example, two game controllers from the same vendor with the same product ID and revision may have the same GUID.
GUIDs may be platform-dependent (i.e., the same device may report different GUIDs on different operating systems).
Since
This struct is available since SDL 3.2.0.
Function Documentation
SDL_GUIDToString()
SDL_DECLSPEC void SDLCALL SDL_GUIDToString (SDL_GUID guid, char * pszGUID, int cbGUID) extern
Get an ASCII string representation for a given SDL_GUID.
Parameters
guid the SDL_GUID you wish to convert to string.
pszGUID buffer in which to write the ASCII string.
cbGUID the size of pszGUID, should be at least 33 bytes.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StringToGUID
{
    static const char k_rgchHexToASCII[] = "0123456789abcdef";
    int i;
    if ((!pszGUID) || (cbGUID <= 0)) {
        return;
    }
    for (i = 0; i < sizeof(guid.data) && i < (cbGUID - 1) / 2; i++) {
        // each input byte writes 2 ascii chars, and might write a null byte.
        // If we don't have room for next input byte, stop
        unsigned char c = guid.data[i];
        *pszGUID++ = k_rgchHexToASCII[c >> 4];
        *pszGUID++ = k_rgchHexToASCII[c & 0x0F];
    }
    *pszGUID = '\0';
}
References SDL_GUID::data.
Referenced by CreateMappingString(), and SDL_GetGamepadMappingForID().
SDL_StringToGUID()
SDL_DECLSPEC SDL_GUID SDLCALL SDL_StringToGUID (const char * pchGUID) extern
Convert a GUID string into a SDL_GUID structure.
Performs no error checking. If this function is given a string containing an invalid GUID, the function will silently succeed, but the GUID generated will not be useful.
Parameters
pchGUID string containing an ASCII representation of a GUID.
Returns
a SDL_GUID structure.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GUIDToString
{
    SDL_GUID guid;
    int maxoutputbytes = sizeof(guid);
    size_t len = SDL_strlen(pchGUID);
    Uint8 *p;
    size_t i;
    // Make sure it's even
    len = (len) & ~0x1;
    SDL_memset(&guid, 0x00, sizeof(guid));
    p = (Uint8 *)&guid;
    for (i = 0; (i < len) && ((p - (Uint8 *)&guid) < maxoutputbytes); i += 2, p++) {
        *p = (nibble((unsigned char)pchGUID[i]) << 4) | nibble((unsigned char)pchGUID[i + 1]);
    }
    return guid;
}
References nibble(), SDL_memset, and SDL_strlen().
Referenced by SDL_PrivateAddGamepadMapping().