SDL3: SDL-main/src/process/SDL_sysprocess.h File Reference
SDL_sysprocess.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_Process
Typedefs
typedef struct SDL_ProcessData SDL_ProcessData
Functions
bool SDL_SYS_CreateProcessWithProperties (SDL_Process *process, SDL_PropertiesID props)
void SDL_SYS_DestroyProcess (SDL_Process *process)
bool SDL_SYS_KillProcess (SDL_Process *process, bool force)
bool SDL_SYS_WaitProcess (SDL_Process *process, bool block, int *exitcode)
Typedef Documentation
SDL_ProcessData
typedef struct SDL_ProcessData SDL_ProcessData
Function Documentation
SDL_SYS_CreateProcessWithProperties()
bool SDL_SYS_CreateProcessWithProperties (SDL_Process * process, SDL_PropertiesID props)
Referenced by SDL_CreateProcessWithProperties().
SDL_SYS_DestroyProcess()
void SDL_SYS_DestroyProcess (SDL_Process * process)
Referenced by SDL_DestroyProcess().
SDL_SYS_KillProcess()
bool SDL_SYS_KillProcess (SDL_Process * process, bool force)
Referenced by SDL_KillProcess().
SDL_SYS_WaitProcess()
bool SDL_SYS_WaitProcess (SDL_Process * process, bool block, int * exitcode)
Referenced by SDL_WaitProcess().