SDL3: SDL-main/include/SDL3/SDL_surface.h File Reference
SDL_surface.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_blendmode.h>
#include <SDL3/SDL_pixels.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_rect.h>
#include <SDL3/SDL_iostream.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_Surface
Macros
#define SDL_MUSTLOCK(S)
#define SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT "SDL.surface.HDR_headroom"
#define SDL_PROP_SURFACE_HOTSPOT_X_NUMBER "SDL.surface.hotspot.x"
#define SDL_PROP_SURFACE_HOTSPOT_Y_NUMBER "SDL.surface.hotspot.y"
#define SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT "SDL.surface.SDR_white_point"
#define SDL_PROP_SURFACE_TONEMAP_OPERATOR_STRING "SDL.surface.tonemap"
#define SDL_SURFACE_LOCK_NEEDED 0x00000002u
#define SDL_SURFACE_LOCKED 0x00000004u
#define SDL_SURFACE_PREALLOCATED 0x00000001u
#define SDL_SURFACE_SIMD_ALIGNED 0x00000008u
Typedefs
typedef enum SDL_FlipMode SDL_FlipMode
typedef enum SDL_ScaleMode SDL_ScaleMode
typedef struct SDL_Surface SDL_Surface
typedef Uint32 SDL_SurfaceFlags
Enumerations
enum SDL_FlipMode { SDL_FLIP_NONE , SDL_FLIP_HORIZONTAL , SDL_FLIP_VERTICAL }
enum SDL_ScaleMode { SDL_SCALEMODE_INVALID = -1 , SDL_SCALEMODE_NEAREST , SDL_SCALEMODE_LINEAR , SDL_SCALEMODE_PIXELART }
Functions
SDL_DECLSPEC bool SDLCALL SDL_AddSurfaceAlternateImage (SDL_Surface *surface, SDL_Surface *image)
SDL_DECLSPEC bool SDLCALL SDL_BlitSurface (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
SDL_DECLSPEC bool SDLCALL SDL_BlitSurface9Grid (SDL_Surface *src, const SDL_Rect *srcrect, int left_width, int right_width, int top_height, int bottom_height, float scale, SDL_ScaleMode scaleMode, SDL_Surface *dst, const SDL_Rect *dstrect)
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceScaled (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect, SDL_ScaleMode scaleMode)
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceTiled (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceTiledWithScale (SDL_Surface *src, const SDL_Rect *srcrect, float scale, SDL_ScaleMode scaleMode, SDL_Surface *dst, const SDL_Rect *dstrect)
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceUnchecked (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceUncheckedScaled (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect, SDL_ScaleMode scaleMode)
SDL_DECLSPEC bool SDLCALL SDL_ClearSurface (SDL_Surface *surface, float r, float g, float b, float a)
SDL_DECLSPEC bool SDLCALL SDL_ConvertPixels (int width, int height, SDL_PixelFormat src_format, const void *src, int src_pitch, SDL_PixelFormat dst_format, void *dst, int dst_pitch)
SDL_DECLSPEC bool SDLCALL SDL_ConvertPixelsAndColorspace (int width, int height, SDL_PixelFormat src_format, SDL_Colorspace src_colorspace, SDL_PropertiesID src_properties, const void *src, int src_pitch, SDL_PixelFormat dst_format, SDL_Colorspace dst_colorspace, SDL_PropertiesID dst_properties, void *dst, int dst_pitch)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_ConvertSurface (SDL_Surface *surface, SDL_PixelFormat format)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_ConvertSurfaceAndColorspace (SDL_Surface *surface, SDL_PixelFormat format, SDL_Palette *palette, SDL_Colorspace colorspace, SDL_PropertiesID props)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_CreateSurface (int width, int height, SDL_PixelFormat format)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_CreateSurfaceFrom (int width, int height, SDL_PixelFormat format, void *pixels, int pitch)
SDL_DECLSPEC SDL_Palette *SDLCALL SDL_CreateSurfacePalette (SDL_Surface *surface)
SDL_DECLSPEC void SDLCALL SDL_DestroySurface (SDL_Surface *surface)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_DuplicateSurface (SDL_Surface *surface)
SDL_DECLSPEC bool SDLCALL SDL_FillSurfaceRect (SDL_Surface *dst, const SDL_Rect *rect, Uint32 color)
SDL_DECLSPEC bool SDLCALL SDL_FillSurfaceRects (SDL_Surface *dst, const SDL_Rect *rects, int count, Uint32 color)
SDL_DECLSPEC bool SDLCALL SDL_FlipSurface (SDL_Surface *surface, SDL_FlipMode flip)
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceAlphaMod (SDL_Surface *surface, Uint8 *alpha)
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceBlendMode (SDL_Surface *surface, SDL_BlendMode *blendMode)
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceClipRect (SDL_Surface *surface, SDL_Rect *rect)
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceColorKey (SDL_Surface *surface, Uint32 *key)
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceColorMod (SDL_Surface *surface, Uint8 *r, Uint8 *g, Uint8 *b)
SDL_DECLSPEC SDL_Colorspace SDLCALL SDL_GetSurfaceColorspace (SDL_Surface *surface)
SDL_DECLSPEC SDL_Surface **SDLCALL SDL_GetSurfaceImages (SDL_Surface *surface, int *count)
SDL_DECLSPEC SDL_Palette *SDLCALL SDL_GetSurfacePalette (SDL_Surface *surface)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetSurfaceProperties (SDL_Surface *surface)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_LoadBMP (const char *file)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_LoadBMP_IO (SDL_IOStream *src, bool closeio)
SDL_DECLSPEC bool SDLCALL SDL_LockSurface (SDL_Surface *surface)
SDL_DECLSPEC Uint32 SDLCALL SDL_MapSurfaceRGB (SDL_Surface *surface, Uint8 r, Uint8 g, Uint8 b)
SDL_DECLSPEC Uint32 SDLCALL SDL_MapSurfaceRGBA (SDL_Surface *surface, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
SDL_DECLSPEC bool SDLCALL SDL_PremultiplyAlpha (int width, int height, SDL_PixelFormat src_format, const void *src, int src_pitch, SDL_PixelFormat dst_format, void *dst, int dst_pitch, bool linear)
SDL_DECLSPEC bool SDLCALL SDL_PremultiplySurfaceAlpha (SDL_Surface *surface, bool linear)
SDL_DECLSPEC bool SDLCALL SDL_ReadSurfacePixel (SDL_Surface *surface, int x, int y, Uint8 *r, Uint8 *g, Uint8 *b, Uint8 *a)
SDL_DECLSPEC bool SDLCALL SDL_ReadSurfacePixelFloat (SDL_Surface *surface, int x, int y, float *r, float *g, float *b, float *a)
SDL_DECLSPEC void SDLCALL SDL_RemoveSurfaceAlternateImages (SDL_Surface *surface)
SDL_DECLSPEC bool SDLCALL SDL_SaveBMP (SDL_Surface *surface, const char *file)
SDL_DECLSPEC bool SDLCALL SDL_SaveBMP_IO (SDL_Surface *surface, SDL_IOStream *dst, bool closeio)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_ScaleSurface (SDL_Surface *surface, int width, int height, SDL_ScaleMode scaleMode)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceAlphaMod (SDL_Surface *surface, Uint8 alpha)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceBlendMode (SDL_Surface *surface, SDL_BlendMode blendMode)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceClipRect (SDL_Surface *surface, const SDL_Rect *rect)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceColorKey (SDL_Surface *surface, bool enabled, Uint32 key)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceColorMod (SDL_Surface *surface, Uint8 r, Uint8 g, Uint8 b)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceColorspace (SDL_Surface *surface, SDL_Colorspace colorspace)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfacePalette (SDL_Surface *surface, SDL_Palette *palette)
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceRLE (SDL_Surface *surface, bool enabled)
SDL_DECLSPEC bool SDLCALL SDL_StretchSurface (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect, SDL_ScaleMode scaleMode)
SDL_DECLSPEC bool SDLCALL SDL_SurfaceHasAlternateImages (SDL_Surface *surface)
SDL_DECLSPEC bool SDLCALL SDL_SurfaceHasColorKey (SDL_Surface *surface)
SDL_DECLSPEC bool SDLCALL SDL_SurfaceHasRLE (SDL_Surface *surface)
SDL_DECLSPEC void SDLCALL SDL_UnlockSurface (SDL_Surface *surface)
SDL_DECLSPEC bool SDLCALL SDL_WriteSurfacePixel (SDL_Surface *surface, int x, int y, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
SDL_DECLSPEC bool SDLCALL SDL_WriteSurfacePixelFloat (SDL_Surface *surface, int x, int y, float r, float g, float b, float a)
Macro Definition Documentation
SDL_MUSTLOCK
#define SDL_MUSTLOCK (S)
Value:
(((S)->flags & SDL_SURFACE_LOCK_NEEDED) == SDL_SURFACE_LOCK_NEEDED)
Evaluates to true if the surface needs to be locked before access.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_SoftBlit(), SDL_StretchSurface(), SDL_UpdateTextureFromSurface(), SDL_WriteSurfacePixel(), and SDL_WriteSurfacePixelFloat().
SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT
#define SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT "SDL.surface.HDR_headroom"
Referenced by SDL_Blit_Slow_Float(), SDL_GetSurfaceHDRHeadroom(), and SDL_RenderReadPixels().
SDL_PROP_SURFACE_HOTSPOT_X_NUMBER
#define SDL_PROP_SURFACE_HOTSPOT_X_NUMBER "SDL.surface.hotspot.x"
Referenced by SDL_CreateColorCursor().
SDL_PROP_SURFACE_HOTSPOT_Y_NUMBER
#define SDL_PROP_SURFACE_HOTSPOT_Y_NUMBER "SDL.surface.hotspot.y"
Referenced by SDL_CreateColorCursor().
SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT
#define SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT "SDL.surface.SDR_white_point"
Referenced by SDL_GetSurfaceSDRWhitePoint(), and SDL_RenderReadPixels().
SDL_PROP_SURFACE_TONEMAP_OPERATOR_STRING
#define SDL_PROP_SURFACE_TONEMAP_OPERATOR_STRING "SDL.surface.tonemap"
Referenced by SDL_Blit_Slow_Float().
SDL_SURFACE_LOCK_NEEDED
#define SDL_SURFACE_LOCK_NEEDED 0x00000002u
Surface needs to be locked to access pixels
Referenced by SDL_UpdateSurfaceLockFlag().
SDL_SURFACE_LOCKED
#define SDL_SURFACE_LOCKED 0x00000004u
Surface is currently locked
Referenced by SDL_BlitSurface(), SDL_BlitSurfaceScaled(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_LockSurface(), and SDL_UnlockSurface().
SDL_SURFACE_PREALLOCATED
#define SDL_SURFACE_PREALLOCATED 0x00000001u
Surface uses preallocated pixel memory
Referenced by SDL_ConvertSurfaceAndColorspace(), SDL_CreateSurface(), SDL_DestroySurface(), and SDL_InitializeSurface().
SDL_SURFACE_SIMD_ALIGNED
#define SDL_SURFACE_SIMD_ALIGNED 0x00000008u
Surface uses pixel memory allocated with SDL_aligned_alloc()
Referenced by SDL_CreateSurface(), and SDL_DestroySurface().
Typedef Documentation
SDL_FlipMode
typedef enum SDL_FlipMode SDL_FlipMode
The flip mode.
Since
This enum is available since SDL 3.2.0.
SDL_ScaleMode
typedef enum SDL_ScaleMode SDL_ScaleMode
The scaling mode.
Since
This enum is available since SDL 3.2.0.
SDL_Surface
typedef struct SDL_Surface SDL_Surface
SDL_SurfaceFlags
typedef Uint32 SDL_SurfaceFlags
CategorySurface
SDL surfaces are buffers of pixels in system RAM. These are useful for passing around and manipulating images that are not stored in GPU memory.
SDL_Surface makes serious efforts to manage images in various formats, and provides a reasonable toolbox for transforming the data, including copying between surfaces, filling rectangles in the image data, etc.
There is also a simple .bmp loader, SDL_LoadBMP(). SDL itself does not provide loaders for various other file formats, but there are several excellent external libraries that do, including its own satellite library, SDL_image :
https://github.com/libsdl-org/SDL_image The flags on an SDL_Surface.
These are generally considered read-only.
Since
This datatype is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_FlipMode
enum SDL_FlipMode
The flip mode.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_FLIP_NONE
Do not flip
SDL_FLIP_HORIZONTAL
flip horizontally
SDL_FLIP_VERTICAL
flip vertically
{
    SDL_FLIP_NONE,          /**< Do not flip */
    SDL_FLIP_HORIZONTAL,    /**< flip horizontally */
    SDL_FLIP_VERTICAL       /**< flip vertically */
} SDL_FlipMode;
SDL_ScaleMode
enum SDL_ScaleMode
The scaling mode.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_SCALEMODE_INVALID
SDL_SCALEMODE_NEAREST
nearest pixel sampling
SDL_SCALEMODE_LINEAR
linear filtering
SDL_SCALEMODE_PIXELART
nearest pixel sampling with improved scaling for pixel art
{
    SDL_SCALEMODE_INVALID = -1,
    SDL_SCALEMODE_NEAREST,  /**< nearest pixel sampling */
    SDL_SCALEMODE_LINEAR,   /**< linear filtering */
    SDL_SCALEMODE_PIXELART  /**< nearest pixel sampling with improved scaling for pixel art */
} SDL_ScaleMode;
Function Documentation
SDL_AddSurfaceAlternateImage()
SDL_DECLSPEC bool SDLCALL SDL_AddSurfaceAlternateImage (SDL_Surface * surface, SDL_Surface * image) extern
Add an alternate version of a surface.
This function adds an alternate version of this surface, usually used for content with high DPI representations like cursors or icons. The size, format, and content do not need to match the original surface, and these alternate versions will not be updated when the original surface changes.
This function adds a reference to the alternate version, so you should call SDL_DestroySurface() on the image after this call.
Parameters
surface the SDL_Surface structure to update.
image a pointer to an alternate SDL_Surface to associate with this surface.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveSurfaceAlternateImages
SDL_GetSurfaceImages
SDL_SurfaceHasAlternateImages
{
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (!SDL_SurfaceValid(image)) {
        return SDL_InvalidParamError("image");
    }
    SDL_Surface **images = (SDL_Surface **)SDL_realloc(surface->images, (surface->num_images + 1) * sizeof(*images));
    if (!images) {
        return false;
    }
    images[surface->num_images] = image;
    surface->images = images;
    ++surface->num_images;
    ++image->refcount;
    return true;
}
References SDL_InvalidParamError, SDL_realloc(), and SDL_SurfaceValid().
Referenced by SDL_ConvertSurfaceAndColorspace().
SDL_BlitSurface()
SDL_DECLSPEC bool SDLCALL SDL_BlitSurface (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect) extern
Performs a fast blit from the source surface to the destination surface with clipping.
If either srcrect or dstrect are NULL, the entire surface (src or dst) is copied while ensuring clipping to dst->clip_rect.
The blit function should not be called on a locked surface.
The blit semantics for surfaces with and without blending and colorkey are defined as follows:
 RGBA->RGB:
   Source surface blend mode set to SDL_BLENDMODE_BLEND:
    alpha-blend (using the source alpha-channel and per-surface alpha)
    SDL_SRCCOLORKEY ignored.
  Source surface blend mode set to SDL_BLENDMODE_NONE:
    copy RGB.
    if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
    RGB values of the source color key, ignoring alpha in the
    comparison.
RGB->RGBA:
  Source surface blend mode set to SDL_BLENDMODE_BLEND:
    alpha-blend (using the source per-surface alpha)
  Source surface blend mode set to SDL_BLENDMODE_NONE:
    copy RGB, set destination alpha to source per-surface alpha value.
  both:
    if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
    source color key.
RGBA->RGBA:
  Source surface blend mode set to SDL_BLENDMODE_BLEND:
    alpha-blend (using the source alpha-channel and per-surface alpha)
    SDL_SRCCOLORKEY ignored.
  Source surface blend mode set to SDL_BLENDMODE_NONE:
    copy all of RGBA to the destination.
    if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
    RGB values of the source color key, ignoring alpha in the
    comparison.
RGB->RGB:
  Source surface blend mode set to SDL_BLENDMODE_BLEND:
    alpha-blend (using the source per-surface alpha)
  Source surface blend mode set to SDL_BLENDMODE_NONE:
    copy RGB.
  both:
    if SDL_SRCCOLORKEY set, only copy the pixels that do not match the
    source color key.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, or NULL to copy the entire surface.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the x and y position in the destination surface, or NULL for (0,0). The width and height are ignored, and are copied from srcrect. If you want a specific width and height, you should use SDL_BlitSurfaceScaled().
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurfaceScaled
{
    SDL_Rect r_src, r_dst;
    // Make sure the surfaces aren't locked
    if (!SDL_SurfaceValid(src)) {
        return SDL_InvalidParamError("src");
    } else if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("dst");
    } else if ((src->flags & SDL_SURFACE_LOCKED) || (dst->flags & SDL_SURFACE_LOCKED)) {
        return SDL_SetError("Surfaces must not be locked during blit");
    }
    // Full src surface
    r_src.x = 0;
    r_src.y = 0;
    r_src.w = src->w;
    r_src.h = src->h;
    if (dstrect) {
        r_dst.x = dstrect->x;
        r_dst.y = dstrect->y;
    } else {
        r_dst.x = 0;
        r_dst.y = 0;
    }
    // clip the source rectangle to the source surface
    if (srcrect) {
        SDL_Rect tmp;
        if (SDL_GetRectIntersection(srcrect, &r_src, &tmp) == false) {
            return true;
        }
        // Shift dstrect, if srcrect origin has changed
        r_dst.x += tmp.x - srcrect->x;
        r_dst.y += tmp.y - srcrect->y;
        // Update srcrect
        r_src = tmp;
    }
    // There're no dstrect.w/h parameters. It's the same as srcrect
    r_dst.w = r_src.w;
    r_dst.h = r_src.h;
    // clip the destination rectangle against the clip rectangle
    {
        SDL_Rect tmp;
        if (SDL_GetRectIntersection(&r_dst, &dst->clip_rect, &tmp) == false) {
            return true;
        }
        // Shift srcrect, if dstrect has changed
        r_src.x += tmp.x - r_dst.x;
        r_src.y += tmp.y - r_dst.y;
        r_src.w = tmp.w;
        r_src.h = tmp.h;
        // Update dstrect
        r_dst = tmp;
    }
    if (r_dst.w <= 0 || r_dst.h <= 0) {
        // No-op.
        return true;
    }
    // Switch back to a fast blit if we were previously stretching
    if (src->map.info.flags & SDL_COPY_NEAREST) {
        src->map.info.flags &= ~SDL_COPY_NEAREST;
        SDL_InvalidateMap(&src->map);
    }
    return SDL_BlitSurfaceUnchecked(src, &r_src, dst, &r_dst);
}
References SDL_Surface::clip_rect, SDL_BlitInfo::flags, SDL_Surface::flags, SDL_Rect::h, SDL_Surface::h, SDL_BlitMap::info, SDL_Surface::map, SDL_BlitSurfaceUnchecked(), SDL_COPY_NEAREST, SDL_GetRectIntersection(), SDL_InvalidateMap(), SDL_InvalidParamError, SDL_SetError(), SDL_SURFACE_LOCKED, SDL_SurfaceValid(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_BlitSurfaceScaled().
SDL_BlitSurface9Grid()
SDL_DECLSPEC bool SDLCALL SDL_BlitSurface9Grid (SDL_Surface * src, const SDL_Rect * srcrect, int left_width, int right_width, int top_height, int bottom_height, float scale, SDL_ScaleMode scaleMode, SDL_Surface * dst, const SDL_Rect * dstrect) extern
Perform a scaled blit using the 9-grid algorithm to a destination surface, which may be of a different format.
The pixels in the source surface are split into a 3x3 grid, using the different corner sizes for each corner, and the sides and center making up the remaining pixels. The corners are then scaled using scale and fit into the corners of the destination rectangle. The sides and center are then stretched into place to cover the remaining destination rectangle.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be used for the 9-grid, or NULL to use the entire surface.
left_width the width, in pixels, of the left corners in srcrect.
right_width the width, in pixels, of the right corners in srcrect.
top_height the height, in pixels, of the top corners in srcrect.
bottom_height the height, in pixels, of the bottom corners in srcrect.
scale the scale used to transform the corner of srcrect into the corner of dstrect, or 0.0f for an unscaled blit.
scaleMode scale algorithm to be used.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, or NULL to fill the entire surface.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurface
{
    SDL_Rect full_src, full_dst;
    SDL_Rect curr_src, curr_dst;
    int dst_left_width;
    int dst_right_width;
    int dst_top_height;
    int dst_bottom_height;
    // Make sure the surfaces aren't locked
    if (!SDL_SurfaceValid(src)) {
        return SDL_InvalidParamError("src");
    } else if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("dst");
    }
    if (!srcrect) {
        full_src.x = 0;
        full_src.y = 0;
        full_src.w = src->w;
        full_src.h = src->h;
        srcrect = &full_src;
    }
    if (!dstrect) {
        full_dst.x = 0;
        full_dst.y = 0;
        full_dst.w = dst->w;
        full_dst.h = dst->h;
        dstrect = &full_dst;
    }
    if (scale <= 0.0f || scale == 1.0f) {
        dst_left_width = left_width;
        dst_right_width = right_width;
        dst_top_height = top_height;
        dst_bottom_height = bottom_height;
    } else {
        dst_left_width = (int)SDL_roundf(left_width * scale);
        dst_right_width = (int)SDL_roundf(right_width * scale);
        dst_top_height = (int)SDL_roundf(top_height * scale);
        dst_bottom_height = (int)SDL_roundf(bottom_height * scale);
    }
    // Upper-left corner
    curr_src.x = srcrect->x;
    curr_src.y = srcrect->y;
    curr_src.w = left_width;
    curr_src.h = top_height;
    curr_dst.x = dstrect->x;
    curr_dst.y = dstrect->y;
    curr_dst.w = dst_left_width;
    curr_dst.h = dst_top_height;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Upper-right corner
    curr_src.x = srcrect->x + srcrect->w - right_width;
    curr_src.w = right_width;
    curr_dst.x = dstrect->x + dstrect->w - dst_right_width;
    curr_dst.w = dst_right_width;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Lower-right corner
    curr_src.y = srcrect->y + srcrect->h - bottom_height;
    curr_dst.y = dstrect->y + dstrect->h - dst_bottom_height;
    curr_dst.h = dst_bottom_height;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Lower-left corner
    curr_src.x = srcrect->x;
    curr_src.w = left_width;
    curr_dst.x = dstrect->x;
    curr_dst.w = dst_left_width;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Left
    curr_src.y = srcrect->y + top_height;
    curr_src.h = srcrect->h - top_height - bottom_height;
    curr_dst.y = dstrect->y + dst_top_height;
    curr_dst.h = dstrect->h - dst_top_height - dst_bottom_height;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Right
    curr_src.x = srcrect->x + srcrect->w - right_width;
    curr_src.w = right_width;
    curr_dst.x = dstrect->x + dstrect->w - dst_right_width;
    curr_dst.w = dst_right_width;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Top
    curr_src.x = srcrect->x + left_width;
    curr_src.y = srcrect->y;
    curr_src.w = srcrect->w - left_width - right_width;
    curr_src.h = top_height;
    curr_dst.x = dstrect->x + dst_left_width;
    curr_dst.y = dstrect->y;
    curr_dst.w = dstrect->w - dst_left_width - dst_right_width;
    curr_dst.h = dst_top_height;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Bottom
    curr_src.y = srcrect->y + srcrect->h - bottom_height;
    curr_dst.y = dstrect->y + dstrect->h - dst_bottom_height;
    curr_dst.h = dst_bottom_height;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    // Center
    curr_src.x = srcrect->x + left_width;
    curr_src.y = srcrect->y + top_height;
    curr_src.w = srcrect->w - left_width - right_width;
    curr_src.h = srcrect->h - top_height - bottom_height;
    curr_dst.x = dstrect->x + dst_left_width;
    curr_dst.y = dstrect->y + dst_top_height;
    curr_dst.w = dstrect->w - dst_left_width - dst_right_width;
    curr_dst.h = dstrect->h - dst_top_height - dst_bottom_height;
    if (!SDL_BlitSurfaceScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
        return false;
    }
    return true;
}
References SDL_Rect::h, SDL_Surface::h, SDL_BlitSurfaceScaled(), SDL_InvalidParamError, SDL_roundf(), SDL_SurfaceValid(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
SDL_BlitSurfaceScaled()
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceScaled (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect, SDL_ScaleMode scaleMode) extern
Perform a scaled blit to a destination surface, which may be of a different format.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, or NULL to copy the entire surface.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, or NULL to fill the entire destination surface.
scaleMode the SDL_ScaleMode to be used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurface
{
    SDL_Rect *clip_rect;
    double src_x0, src_y0, src_x1, src_y1;
    double dst_x0, dst_y0, dst_x1, dst_y1;
    SDL_Rect final_src, final_dst;
    double scaling_w, scaling_h;
    int src_w, src_h;
    int dst_w, dst_h;
    // Make sure the surfaces aren't locked
    if (!SDL_SurfaceValid(src) || !src->pixels) {
        return SDL_InvalidParamError("src");
    } else if (!SDL_SurfaceValid(dst) || !dst->pixels) {
        return SDL_InvalidParamError("dst");
    } else if ((src->flags & SDL_SURFACE_LOCKED) || (dst->flags & SDL_SURFACE_LOCKED)) {
        return SDL_SetError("Surfaces must not be locked during blit");
    }
    switch (scaleMode) {
    case SDL_SCALEMODE_NEAREST:
        break;
    case SDL_SCALEMODE_LINEAR:
        break;
    case SDL_SCALEMODE_PIXELART:
        scaleMode = SDL_SCALEMODE_NEAREST;
        break;
    default:
        return SDL_InvalidParamError("scaleMode");
    }
    if (!srcrect) {
        src_w = src->w;
        src_h = src->h;
    } else {
        src_w = srcrect->w;
        src_h = srcrect->h;
    }
    if (!dstrect) {
        dst_w = dst->w;
        dst_h = dst->h;
    } else {
        dst_w = dstrect->w;
        dst_h = dstrect->h;
    }
    if (dst_w == src_w && dst_h == src_h) {
        // No scaling, defer to regular blit
        return SDL_BlitSurface(src, srcrect, dst, dstrect);
    }
    if (src_w == 0) {
        src_w = 1;
    }
    if (src_h == 0) {
        src_h = 1;
    }
    scaling_w = (double)dst_w / src_w;
    scaling_h = (double)dst_h / src_h;
    if (!dstrect) {
        dst_x0 = 0;
        dst_y0 = 0;
        dst_x1 = dst_w;
        dst_y1 = dst_h;
    } else {
        dst_x0 = dstrect->x;
        dst_y0 = dstrect->y;
        dst_x1 = dst_x0 + dst_w;
        dst_y1 = dst_y0 + dst_h;
    }
    if (!srcrect) {
        src_x0 = 0;
        src_y0 = 0;
        src_x1 = src_w;
        src_y1 = src_h;
    } else {
        src_x0 = srcrect->x;
        src_y0 = srcrect->y;
        src_x1 = src_x0 + src_w;
        src_y1 = src_y0 + src_h;
        // Clip source rectangle to the source surface
        if (src_x0 < 0) {
            dst_x0 -= src_x0 * scaling_w;
            src_x0 = 0;
        }
        if (src_x1 > src->w) {
            dst_x1 -= (src_x1 - src->w) * scaling_w;
            src_x1 = src->w;
        }
        if (src_y0 < 0) {
            dst_y0 -= src_y0 * scaling_h;
            src_y0 = 0;
        }
        if (src_y1 > src->h) {
            dst_y1 -= (src_y1 - src->h) * scaling_h;
            src_y1 = src->h;
        }
    }
    // Clip destination rectangle to the clip rectangle
    clip_rect = &dst->clip_rect;
    // Translate to clip space for easier calculations
    dst_x0 -= clip_rect->x;
    dst_x1 -= clip_rect->x;
    dst_y0 -= clip_rect->y;
    dst_y1 -= clip_rect->y;
    if (dst_x0 < 0) {
        src_x0 -= dst_x0 / scaling_w;
        dst_x0 = 0;
    }
    if (dst_x1 > clip_rect->w) {
        src_x1 -= (dst_x1 - clip_rect->w) / scaling_w;
        dst_x1 = clip_rect->w;
    }
    if (dst_y0 < 0) {
        src_y0 -= dst_y0 / scaling_h;
        dst_y0 = 0;
    }
    if (dst_y1 > clip_rect->h) {
        src_y1 -= (dst_y1 - clip_rect->h) / scaling_h;
        dst_y1 = clip_rect->h;
    }
    // Translate back to surface coordinates
    dst_x0 += clip_rect->x;
    dst_x1 += clip_rect->x;
    dst_y0 += clip_rect->y;
    dst_y1 += clip_rect->y;
    final_src.x = (int)SDL_round(src_x0);
    final_src.y = (int)SDL_round(src_y0);
    final_src.w = (int)SDL_round(src_x1 - src_x0);
    final_src.h = (int)SDL_round(src_y1 - src_y0);
    final_dst.x = (int)SDL_round(dst_x0);
    final_dst.y = (int)SDL_round(dst_y0);
    final_dst.w = (int)SDL_round(dst_x1 - dst_x0);
    final_dst.h = (int)SDL_round(dst_y1 - dst_y0);
    // Clip again
    {
        SDL_Rect tmp;
        tmp.x = 0;
        tmp.y = 0;
        tmp.w = src->w;
        tmp.h = src->h;
        SDL_GetRectIntersection(&tmp, &final_src, &final_src);
    }
    // Clip again
    SDL_GetRectIntersection(clip_rect, &final_dst, &final_dst);
    if (final_dst.w == 0 || final_dst.h == 0 ||
        final_src.w < 0 || final_src.h < 0) {
        // No-op.
        return true;
    }
    return SDL_BlitSurfaceUncheckedScaled(src, &final_src, dst, &final_dst, scaleMode);
}
References SDL_Surface::clip_rect, SDL_Surface::flags, SDL_Rect::h, SDL_Surface::h, SDL_Surface::pixels, SDL_BlitSurface(), SDL_BlitSurfaceUncheckedScaled(), SDL_GetRectIntersection(), SDL_InvalidParamError, SDL_round(), SDL_SCALEMODE_LINEAR, SDL_SCALEMODE_NEAREST, SDL_SCALEMODE_PIXELART, SDL_SetError(), SDL_SURFACE_LOCKED, SDL_SurfaceValid(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_BlitSurface9Grid(), SDL_ClearSurface(), and SDL_ScaleSurface().
SDL_BlitSurfaceTiled()
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceTiled (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect) extern
Perform a tiled blit to a destination surface, which may be of a different format.
The pixels in srcrect will be repeated as many times as needed to completely fill dstrect.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, or NULL to copy the entire surface.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, or NULL to fill the entire surface.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurface
{
    SDL_Rect r_src, r_dst;
    // Make sure the surfaces aren't locked
    if (!SDL_SurfaceValid(src)) {
        return SDL_InvalidParamError("src");
    } else if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("dst");
    } else if ((src->flags & SDL_SURFACE_LOCKED) || (dst->flags & SDL_SURFACE_LOCKED)) {
        return SDL_SetError("Surfaces must not be locked during blit");
    }
    // Full src surface
    r_src.x = 0;
    r_src.y = 0;
    r_src.w = src->w;
    r_src.h = src->h;
    if (dstrect) {
        r_dst.x = dstrect->x;
        r_dst.y = dstrect->y;
        r_dst.w = dstrect->w;
        r_dst.h = dstrect->h;
    } else {
        r_dst.x = 0;
        r_dst.y = 0;
        r_dst.w = dst->w;
        r_dst.h = dst->h;
    }
    // clip the source rectangle to the source surface
    if (srcrect) {
        if (SDL_GetRectIntersection(srcrect, &r_src, &r_src) == false) {
            return true;
        }
        // For tiling we don't adjust the destination rectangle
    }
    // clip the destination rectangle against the clip rectangle
    {
        if (SDL_GetRectIntersection(&r_dst, &dst->clip_rect, &r_dst) == false) {
            return true;
        }
        // For tiling we don't adjust the source rectangle
    }
    // Switch back to a fast blit if we were previously stretching
    if (src->map.info.flags & SDL_COPY_NEAREST) {
        src->map.info.flags &= ~SDL_COPY_NEAREST;
        SDL_InvalidateMap(&src->map);
    }
    int rows = r_dst.h / r_src.h;
    int cols = r_dst.w / r_src.w;
    int remaining_w = r_dst.w % r_src.w;
    int remaining_h = r_dst.h % r_src.h;
    SDL_Rect curr_src, curr_dst;
    SDL_copyp(&curr_src, &r_src);
    curr_dst.y = r_dst.y;
    curr_dst.w = r_src.w;
    curr_dst.h = r_src.h;
    for (int y = 0; y < rows; ++y) {
        curr_dst.x = r_dst.x;
        for (int x = 0; x < cols; ++x) {
            if (!SDL_BlitSurfaceUnchecked(src, &curr_src, dst, &curr_dst)) {
                return false;
            }
            curr_dst.x += curr_dst.w;
        }
        if (remaining_w) {
            curr_src.w = remaining_w;
            curr_dst.w = remaining_w;
            if (!SDL_BlitSurfaceUnchecked(src, &curr_src, dst, &curr_dst)) {
                return false;
            }
            curr_src.w = r_src.w;
            curr_dst.w = r_src.w;
        }
        curr_dst.y += curr_dst.h;
    }
    if (remaining_h) {
        curr_src.h = remaining_h;
        curr_dst.h = remaining_h;
        curr_dst.x = r_dst.x;
        for (int x = 0; x < cols; ++x) {
            if (!SDL_BlitSurfaceUnchecked(src, &curr_src, dst, &curr_dst)) {
                return false;
            }
            curr_dst.x += curr_dst.w;
        }
        if (remaining_w) {
            curr_src.w = remaining_w;
            curr_dst.w = remaining_w;
            if (!SDL_BlitSurfaceUnchecked(src, &curr_src, dst, &curr_dst)) {
                return false;
            }
        }
    }
    return true;
}
References SDL_Surface::clip_rect, SDL_BlitInfo::flags, SDL_Surface::flags, SDL_Rect::h, SDL_Surface::h, SDL_BlitMap::info, SDL_Surface::map, SDL_BlitSurfaceUnchecked(), SDL_COPY_NEAREST, SDL_copyp, SDL_GetRectIntersection(), SDL_InvalidateMap(), SDL_InvalidParamError, SDL_SetError(), SDL_SURFACE_LOCKED, SDL_SurfaceValid(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
SDL_BlitSurfaceTiledWithScale()
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceTiledWithScale (SDL_Surface * src, const SDL_Rect * srcrect, float scale, SDL_ScaleMode scaleMode, SDL_Surface * dst, const SDL_Rect * dstrect) extern
Perform a scaled and tiled blit to a destination surface, which may be of a different format.
The pixels in srcrect will be scaled and repeated as many times as needed to completely fill dstrect.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, or NULL to copy the entire surface.
scale the scale used to transform srcrect into the destination rectangle, e.g. a 32x32 texture with a scale of 2 would fill 64x64 tiles.
scaleMode scale algorithm to be used.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, or NULL to fill the entire surface.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurface
{
    SDL_Rect r_src, r_dst;
    // Make sure the surfaces aren't locked
    if (!SDL_SurfaceValid(src)) {
        return SDL_InvalidParamError("src");
    } else if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("dst");
    } else if ((src->flags & SDL_SURFACE_LOCKED) || (dst->flags & SDL_SURFACE_LOCKED)) {
        return SDL_SetError("Surfaces must not be locked during blit");
    }
    if (scale <= 0.0f) {
        return SDL_InvalidParamError("scale");
    }
    // Full src surface
    r_src.x = 0;
    r_src.y = 0;
    r_src.w = src->w;
    r_src.h = src->h;
    if (dstrect) {
        r_dst.x = dstrect->x;
        r_dst.y = dstrect->y;
        r_dst.w = dstrect->w;
        r_dst.h = dstrect->h;
    } else {
        r_dst.x = 0;
        r_dst.y = 0;
        r_dst.w = dst->w;
        r_dst.h = dst->h;
    }
    // clip the source rectangle to the source surface
    if (srcrect) {
        if (SDL_GetRectIntersection(srcrect, &r_src, &r_src) == false) {
            return true;
        }
        // For tiling we don't adjust the destination rectangle
    }
    // clip the destination rectangle against the clip rectangle
    {
        if (SDL_GetRectIntersection(&r_dst, &dst->clip_rect, &r_dst) == false) {
            return true;
        }
        // For tiling we don't adjust the source rectangle
    }
    // Switch back to a fast blit if we were previously stretching
    if (src->map.info.flags & SDL_COPY_NEAREST) {
        src->map.info.flags &= ~SDL_COPY_NEAREST;
        SDL_InvalidateMap(&src->map);
    }
    int tile_width = (int)(r_src.w * scale);
    int tile_height = (int)(r_src.h * scale);
    int rows = r_dst.h / tile_height;
    int cols = r_dst.w / tile_width;
    int remaining_dst_w = (r_dst.w - cols * tile_width);
    int remaining_dst_h = (r_dst.h - rows * tile_height);
    int remaining_src_w = (int)(remaining_dst_w / scale);
    int remaining_src_h = (int)(remaining_dst_h / scale);
    SDL_Rect curr_src, curr_dst;
    SDL_copyp(&curr_src, &r_src);
    curr_dst.y = r_dst.y;
    curr_dst.w = tile_width;
    curr_dst.h = tile_height;
    for (int y = 0; y < rows; ++y) {
        curr_dst.x = r_dst.x;
        for (int x = 0; x < cols; ++x) {
            if (!SDL_BlitSurfaceUncheckedScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
                return false;
            }
            curr_dst.x += curr_dst.w;
        }
        if (remaining_dst_w > 0) {
            curr_src.w = remaining_src_w;
            curr_dst.w = remaining_dst_w;
            if (!SDL_BlitSurfaceUncheckedScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
                return false;
            }
            curr_src.w = r_src.w;
            curr_dst.w = tile_width;
        }
        curr_dst.y += curr_dst.h;
    }
    if (remaining_dst_h > 0) {
        curr_src.h = remaining_src_h;
        curr_dst.h = remaining_dst_h;
        curr_dst.x = r_dst.x;
        for (int x = 0; x < cols; ++x) {
            if (!SDL_BlitSurfaceUncheckedScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
                return false;
            }
            curr_dst.x += curr_dst.w;
        }
        if (remaining_dst_w > 0) {
            curr_src.w = remaining_src_w;
            curr_dst.w = remaining_dst_w;
            if (!SDL_BlitSurfaceUncheckedScaled(src, &curr_src, dst, &curr_dst, scaleMode)) {
                return false;
            }
        }
    }
    return true;
}
References SDL_Surface::clip_rect, SDL_BlitInfo::flags, SDL_Surface::flags, SDL_Rect::h, SDL_Surface::h, SDL_BlitMap::info, SDL_Surface::map, SDL_BlitSurfaceUncheckedScaled(), SDL_COPY_NEAREST, SDL_copyp, SDL_GetRectIntersection(), SDL_InvalidateMap(), SDL_InvalidParamError, SDL_SetError(), SDL_SURFACE_LOCKED, SDL_SurfaceValid(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
SDL_BlitSurfaceUnchecked()
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceUnchecked (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect) extern
Perform low-level surface blitting only.
This is a semi-private blit function and it performs low-level surface blitting, assuming the input rectangles have already been clipped.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, may not be NULL.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, may not be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurface
{
    // Check to make sure the blit mapping is valid
    if (!SDL_ValidateMap(src, dst)) {
        return false;
    }
    return src->map.blit(src, srcrect, dst, dstrect);
}
References SDL_BlitMap::blit, SDL_Surface::map, and SDL_ValidateMap().
Referenced by SDL_BlitSurface(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceUncheckedScaled(), SDL_ConvertPixelsAndColorspace(), and SDL_ConvertSurfaceAndColorspace().
SDL_BlitSurfaceUncheckedScaled()
SDL_DECLSPEC bool SDLCALL SDL_BlitSurfaceUncheckedScaled (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect, SDL_ScaleMode scaleMode) extern
Perform low-level surface scaled blitting only.
This is a semi-private function and it performs low-level surface blitting, assuming the input rectangles have already been clipped.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, may not be NULL.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, may not be NULL.
scaleMode the SDL_ScaleMode to be used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurfaceScaled
This is a semi-private blit function and it performs low-level surface scaled blitting only.
{
    static const Uint32 complex_copy_flags = (SDL_COPY_MODULATE_MASK | SDL_COPY_BLEND_MASK | SDL_COPY_COLORKEY);
    if (srcrect->w > SDL_MAX_UINT16 || srcrect->h > SDL_MAX_UINT16 ||
        dstrect->w > SDL_MAX_UINT16 || dstrect->h > SDL_MAX_UINT16) {
        return SDL_SetError("Size too large for scaling");
    }
    if (!(src->map.info.flags & SDL_COPY_NEAREST)) {
        src->map.info.flags |= SDL_COPY_NEAREST;
        SDL_InvalidateMap(&src->map);
    }
    if (scaleMode == SDL_SCALEMODE_NEAREST || scaleMode == SDL_SCALEMODE_PIXELART) {
        if (!(src->map.info.flags & complex_copy_flags) &&
            src->format == dst->format &&
            !SDL_ISPIXELFORMAT_INDEXED(src->format) &&
            SDL_BYTESPERPIXEL(src->format) <= 4) {
            return SDL_StretchSurface(src, srcrect, dst, dstrect, SDL_SCALEMODE_NEAREST);
        } else if (SDL_BITSPERPIXEL(src->format) < 8) {
            // Scaling bitmap not yet supported, convert to RGBA for blit
            bool result = false;
            SDL_Surface *tmp = SDL_ConvertSurface(src, SDL_PIXELFORMAT_ARGB8888);
            if (tmp) {
                result = SDL_BlitSurfaceUncheckedScaled(tmp, srcrect, dst, dstrect, SDL_SCALEMODE_NEAREST);
                SDL_DestroySurface(tmp);
            }
            return result;
        } else {
            return SDL_BlitSurfaceUnchecked(src, srcrect, dst, dstrect);
        }
    } else {
        if (!(src->map.info.flags & complex_copy_flags) &&
            src->format == dst->format &&
            !SDL_ISPIXELFORMAT_INDEXED(src->format) &&
            SDL_BYTESPERPIXEL(src->format) == 4 &&
            src->format != SDL_PIXELFORMAT_ARGB2101010) {
            // fast path
            return SDL_StretchSurface(src, srcrect, dst, dstrect, SDL_SCALEMODE_LINEAR);
        } else if (SDL_BITSPERPIXEL(src->format) < 8) {
            // Scaling bitmap not yet supported, convert to RGBA for blit
            bool result = false;
            SDL_Surface *tmp = SDL_ConvertSurface(src, SDL_PIXELFORMAT_ARGB8888);
            if (tmp) {
                result = SDL_BlitSurfaceUncheckedScaled(tmp, srcrect, dst, dstrect, scaleMode);
                SDL_DestroySurface(tmp);
            }
            return result;
        } else {
            // Use intermediate surface(s)
            SDL_Surface *tmp1 = NULL;
            bool result;
            SDL_Rect srcrect2;
            int is_complex_copy_flags = (src->map.info.flags & complex_copy_flags);
            Uint8 r, g, b;
            Uint8 alpha;
            SDL_BlendMode blendMode;
            // Save source infos
            SDL_GetSurfaceColorMod(src, &r, &g, &b);
            SDL_GetSurfaceAlphaMod(src, &alpha);
            SDL_GetSurfaceBlendMode(src, &blendMode);
            srcrect2.x = srcrect->x;
            srcrect2.y = srcrect->y;
            srcrect2.w = srcrect->w;
            srcrect2.h = srcrect->h;
            // Change source format if not appropriate for scaling
            if (SDL_BYTESPERPIXEL(src->format) != 4 || src->format == SDL_PIXELFORMAT_ARGB2101010) {
                SDL_Rect tmprect;
                SDL_PixelFormat fmt;
                tmprect.x = 0;
                tmprect.y = 0;
                tmprect.w = src->w;
                tmprect.h = src->h;
                if (SDL_BYTESPERPIXEL(dst->format) == 4 && dst->format != SDL_PIXELFORMAT_ARGB2101010) {
                    fmt = dst->format;
                } else {
                    fmt = SDL_PIXELFORMAT_ARGB8888;
                }
                tmp1 = SDL_CreateSurface(src->w, src->h, fmt);
                SDL_BlitSurfaceUnchecked(src, srcrect, tmp1, &tmprect);
                srcrect2.x = 0;
                srcrect2.y = 0;
                SDL_SetSurfaceColorMod(tmp1, r, g, b);
                SDL_SetSurfaceAlphaMod(tmp1, alpha);
                SDL_SetSurfaceBlendMode(tmp1, blendMode);
                src = tmp1;
            }
            // Intermediate scaling
            if (is_complex_copy_flags || src->format != dst->format) {
                SDL_Rect tmprect;
                SDL_Surface *tmp2 = SDL_CreateSurface(dstrect->w, dstrect->h, src->format);
                SDL_StretchSurface(src, &srcrect2, tmp2, NULL, SDL_SCALEMODE_LINEAR);
                SDL_SetSurfaceColorMod(tmp2, r, g, b);
                SDL_SetSurfaceAlphaMod(tmp2, alpha);
                SDL_SetSurfaceBlendMode(tmp2, blendMode);
                tmprect.x = 0;
                tmprect.y = 0;
                tmprect.w = dstrect->w;
                tmprect.h = dstrect->h;
                result = SDL_BlitSurfaceUnchecked(tmp2, &tmprect, dst, dstrect);
                SDL_DestroySurface(tmp2);
            } else {
                result = SDL_StretchSurface(src, &srcrect2, dst, dstrect, SDL_SCALEMODE_LINEAR);
            }
            SDL_DestroySurface(tmp1);
            return result;
        }
    }
}
References SDL_BlitInfo::flags, SDL_Surface::format, SDL_Rect::h, SDL_Surface::h, SDL_BlitMap::info, SDL_Surface::map, NULL, SDL_BITSPERPIXEL, SDL_BlitSurfaceUnchecked(), SDL_BlitSurfaceUncheckedScaled(), SDL_BYTESPERPIXEL, SDL_ConvertSurface(), SDL_COPY_BLEND_MASK, SDL_COPY_COLORKEY, SDL_COPY_MODULATE_MASK, SDL_COPY_NEAREST, SDL_CreateSurface(), SDL_DestroySurface(), SDL_GetSurfaceAlphaMod(), SDL_GetSurfaceBlendMode(), SDL_GetSurfaceColorMod(), SDL_InvalidateMap(), SDL_ISPIXELFORMAT_INDEXED, SDL_MAX_UINT16, SDL_PIXELFORMAT_ARGB2101010, SDL_PIXELFORMAT_ARGB8888, SDL_SCALEMODE_LINEAR, SDL_SCALEMODE_NEAREST, SDL_SCALEMODE_PIXELART, SDL_SetError(), SDL_SetSurfaceAlphaMod(), SDL_SetSurfaceBlendMode(), SDL_SetSurfaceColorMod(), SDL_StretchSurface(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_BlitSurfaceScaled(), SDL_BlitSurfaceTiledWithScale(), and SDL_BlitSurfaceUncheckedScaled().
SDL_ClearSurface()
SDL_DECLSPEC bool SDLCALL SDL_ClearSurface (SDL_Surface * surface, float r, float g, float b, float a) extern
Clear a surface with a specific color, with floating point precision.
This function handles all surface formats, and ignores any clip rectangle.
If the surface is YUV, the color is assumed to be in the sRGB colorspace, otherwise the color is assumed to be in the colorspace of the suface.
Parameters
surface the SDL_Surface to clear.
r the red component of the pixel, normally in the range 0-1.
g the green component of the pixel, normally in the range 0-1.
b the blue component of the pixel, normally in the range 0-1.
a the alpha component of the pixel, normally in the range 0-1.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    SDL_Rect clip_rect;
    bool result = false;
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    SDL_GetSurfaceClipRect(surface, &clip_rect);
    SDL_SetSurfaceClipRect(surface, NULL);
    if (!SDL_ISPIXELFORMAT_FOURCC(surface->format) &&
        SDL_BYTESPERPIXEL(surface->format) <= sizeof(Uint32)) {
        Uint32 color;
        color = SDL_MapSurfaceRGBA(surface,
                    (Uint8)SDL_roundf(SDL_clamp(r, 0.0f, 1.0f) * 255.0f),
                    (Uint8)SDL_roundf(SDL_clamp(g, 0.0f, 1.0f) * 255.0f),
                    (Uint8)SDL_roundf(SDL_clamp(b, 0.0f, 1.0f) * 255.0f),
                    (Uint8)SDL_roundf(SDL_clamp(a, 0.0f, 1.0f) * 255.0f));
        result = SDL_FillSurfaceRect(surface, NULL, color);
    } else if (SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        // We can't directly set an RGB value on a YUV surface
        SDL_Surface *tmp = SDL_CreateSurface(surface->w, surface->h, SDL_PIXELFORMAT_ARGB8888);
        if (!tmp) {
            goto done;
        }
        if (SDL_ClearSurface(tmp, r, g, b, a)) {
            result = SDL_ConvertPixelsAndColorspace(surface->w, surface->h, tmp->format, tmp->colorspace, tmp->props, tmp->pixels, tmp->pitch, surface->format, surface->colorspace, surface->props, surface->pixels, surface->pitch);
        }
        SDL_DestroySurface(tmp);
    } else {
        // Take advantage of blit color conversion
        SDL_Surface *tmp = SDL_CreateSurface(1, 1, SDL_PIXELFORMAT_RGBA128_FLOAT);
        if (!tmp) {
            goto done;
        }
        SDL_SetSurfaceColorspace(tmp, surface->colorspace);
        SDL_SetSurfaceBlendMode(tmp, SDL_BLENDMODE_NONE);
        float *pixels = (float *)tmp->pixels;
        pixels[0] = r;
        pixels[1] = g;
        pixels[2] = b;
        pixels[3] = a;
        result = SDL_BlitSurfaceScaled(tmp, NULL, surface, NULL, SDL_SCALEMODE_NEAREST);
        SDL_DestroySurface(tmp);
    }
done:
    SDL_SetSurfaceClipRect(surface, &clip_rect);
    return result;
}
References SDL_Surface::colorspace, SDL_Surface::format, NULL, SDL_Surface::pitch, SDL_Surface::pixels, SDL_Surface::props, SDL_BLENDMODE_NONE, SDL_BlitSurfaceScaled(), SDL_BYTESPERPIXEL, SDL_clamp, SDL_ClearSurface(), SDL_ConvertPixelsAndColorspace(), SDL_CreateSurface(), SDL_DestroySurface(), SDL_FillSurfaceRect(), SDL_GetSurfaceClipRect(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_MapSurfaceRGBA(), SDL_PIXELFORMAT_ARGB8888, SDL_PIXELFORMAT_RGBA128_FLOAT, SDL_roundf(), SDL_SCALEMODE_NEAREST, SDL_SetSurfaceBlendMode(), SDL_SetSurfaceClipRect(), SDL_SetSurfaceColorspace(), and SDL_SurfaceValid().
Referenced by SDL_ClearSurface().
SDL_ConvertPixels()
SDL_DECLSPEC bool SDLCALL SDL_ConvertPixels (int width, int height, SDL_PixelFormat src_format, const void * src, int src_pitch, SDL_PixelFormat dst_format, void * dst, int dst_pitch) extern
Copy a block of pixels of one format to another format.
Parameters
width the width of the block to copy, in pixels.
height the height of the block to copy, in pixels.
src_format an SDL_PixelFormat value of the src pixels format.
src a pointer to the source pixels.
src_pitch the pitch of the source pixels, in bytes.
dst_format an SDL_PixelFormat value of the dst pixels format.
dst a pointer to be filled in with new pixel data.
dst_pitch the pitch of the destination pixels, in bytes.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
The same destination pixels should not be used from two threads at once. It is safe to use the same source pixels from multiple threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_ConvertPixelsAndColorspace
{
    return SDL_ConvertPixelsAndColorspace(width, height,
                      src_format, SDL_COLORSPACE_UNKNOWN, 0, src, src_pitch,
                      dst_format, SDL_COLORSPACE_UNKNOWN, 0, dst, dst_pitch);
}
References SDL_COLORSPACE_UNKNOWN, and SDL_ConvertPixelsAndColorspace().
Referenced by SDL_CameraThreadIterate(), and SDL_UnlockTextureNative().
SDL_ConvertPixelsAndColorspace()
SDL_DECLSPEC bool SDLCALL SDL_ConvertPixelsAndColorspace (int width, int height, SDL_PixelFormat src_format, SDL_Colorspace src_colorspace, SDL_PropertiesID src_properties, const void * src, int src_pitch, SDL_PixelFormat dst_format, SDL_Colorspace dst_colorspace, SDL_PropertiesID dst_properties, void * dst, int dst_pitch) extern
Copy a block of pixels of one format and colorspace to another format and colorspace.
Parameters
width the width of the block to copy, in pixels.
height the height of the block to copy, in pixels.
src_format an SDL_PixelFormat value of the src pixels format.
src_colorspace an SDL_Colorspace value describing the colorspace of the src pixels.
src_properties an SDL_PropertiesID with additional source color properties, or 0.
src a pointer to the source pixels.
src_pitch the pitch of the source pixels, in bytes.
dst_format an SDL_PixelFormat value of the dst pixels format.
dst_colorspace an SDL_Colorspace value describing the colorspace of the dst pixels.
dst_properties an SDL_PropertiesID with additional destination color properties, or 0.
dst a pointer to be filled in with new pixel data.
dst_pitch the pitch of the destination pixels, in bytes.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
The same destination pixels should not be used from two threads at once. It is safe to use the same source pixels from multiple threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_ConvertPixels
{
    SDL_Surface src_surface;
    SDL_Surface dst_surface;
    SDL_Rect rect;
    void *nonconst_src = (void *)src;
    bool result;
    if (!src) {
        return SDL_InvalidParamError("src");
    }
    if (!src_pitch) {
        return SDL_InvalidParamError("src_pitch");
    }
    if (!dst) {
        return SDL_InvalidParamError("dst");
    }
    if (!dst_pitch) {
        return SDL_InvalidParamError("dst_pitch");
    }
    if (src_colorspace == SDL_COLORSPACE_UNKNOWN) {
        src_colorspace = SDL_GetDefaultColorspaceForFormat(src_format);
    }
    if (dst_colorspace == SDL_COLORSPACE_UNKNOWN) {
        dst_colorspace = SDL_GetDefaultColorspaceForFormat(dst_format);
    }
    if (src_format == SDL_PIXELFORMAT_MJPG) {
        return SDL_ConvertPixels_STB(width, height, src_format, src_colorspace, src_properties, src, src_pitch, dst_format, dst_colorspace, dst_properties, dst, dst_pitch);
    }
#ifdef SDL_HAVE_YUV
    if (SDL_ISPIXELFORMAT_FOURCC(src_format) && SDL_ISPIXELFORMAT_FOURCC(dst_format)) {
        return SDL_ConvertPixels_YUV_to_YUV(width, height, src_format, src_colorspace, src_properties, src, src_pitch, dst_format, dst_colorspace, dst_properties, dst, dst_pitch);
    } else if (SDL_ISPIXELFORMAT_FOURCC(src_format)) {
        return SDL_ConvertPixels_YUV_to_RGB(width, height, src_format, src_colorspace, src_properties, src, src_pitch, dst_format, dst_colorspace, dst_properties, dst, dst_pitch);
    } else if (SDL_ISPIXELFORMAT_FOURCC(dst_format)) {
        return SDL_ConvertPixels_RGB_to_YUV(width, height, src_format, src_colorspace, src_properties, src, src_pitch, dst_format, dst_colorspace, dst_properties, dst, dst_pitch);
    }
#else
    if (SDL_ISPIXELFORMAT_FOURCC(src_format) || SDL_ISPIXELFORMAT_FOURCC(dst_format)) {
        return SDL_SetError("SDL not built with YUV support");
    }
#endif
    // Fast path for same format copy
    if (src_format == dst_format && src_colorspace == dst_colorspace) {
        if (src_pitch == dst_pitch) {
            SDL_memcpy(dst, src, height * src_pitch);
        } else {
            int i;
            const int bpp = SDL_BYTESPERPIXEL(src_format);
            width *= bpp;
            for (i = height; i--;) {
                SDL_memcpy(dst, src, width);
                src = (const Uint8 *)src + src_pitch;
                dst = (Uint8 *)dst + dst_pitch;
            }
        }
        return true;
    }
    if (!SDL_InitializeSurface(&src_surface, width, height, src_format, src_colorspace, src_properties, nonconst_src, src_pitch, true)) {
        return false;
    }
    SDL_SetSurfaceBlendMode(&src_surface, SDL_BLENDMODE_NONE);
    if (!SDL_InitializeSurface(&dst_surface, width, height, dst_format, dst_colorspace, dst_properties, dst, dst_pitch, true)) {
        return false;
    }
    // Set up the rect and go!
    rect.x = 0;
    rect.y = 0;
    rect.w = width;
    rect.h = height;
    result = SDL_BlitSurfaceUnchecked(&src_surface, &rect, &dst_surface, &rect);
    SDL_DestroySurface(&src_surface);
    SDL_DestroySurface(&dst_surface);
    return result;
}
References SDL_Rect::h, SDL_BLENDMODE_NONE, SDL_BlitSurfaceUnchecked(), SDL_BYTESPERPIXEL, SDL_COLORSPACE_UNKNOWN, SDL_ConvertPixels_RGB_to_YUV(), SDL_ConvertPixels_STB(), SDL_ConvertPixels_YUV_to_RGB(), SDL_ConvertPixels_YUV_to_YUV(), SDL_DestroySurface(), SDL_GetDefaultColorspaceForFormat(), SDL_InitializeSurface(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_memcpy, SDL_PIXELFORMAT_MJPG, SDL_SetError(), SDL_SetSurfaceBlendMode(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_ClearSurface(), SDL_ConvertPixels(), SDL_ConvertPixels_STB(), SDL_ConvertSurfaceAndColorspace(), SDL_PremultiplyAlphaPixelsAndColorspace(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_StretchSurface(), SDL_UpdateTextureNative(), SDL_WriteSurfacePixel(), and SDL_WriteSurfacePixelFloat().
SDL_ConvertSurface()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_ConvertSurface (SDL_Surface * surface, SDL_PixelFormat format) extern
Copy an existing surface to a new surface of the specified format.
This function is used to optimize images for faster repeat blitting. This is accomplished by converting the original and storing the result as a new surface. The new, optimized surface can then be used as the source for future blits, making them faster.
If you are converting to an indexed surface and want to map colors to a palette, you can use SDL_ConvertSurfaceAndColorspace() instead.
If the original surface has alternate images, the new surface will have a reference to them as well.
Parameters
surface the existing SDL_Surface structure to convert.
format the new pixel format.
Returns
the new SDL_Surface structure that is created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_ConvertSurfaceAndColorspace
SDL_DestroySurface
{
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        return NULL;
    }
    return SDL_ConvertSurfaceAndColorspace(surface, format, NULL, SDL_GetDefaultColorspaceForFormat(format), surface->props);
}
References NULL, SDL_ConvertSurfaceAndColorspace(), SDL_GetDefaultColorspaceForFormat(), SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by CreateIconFromSurface(), SDL_BlitSurfaceUncheckedScaled(), SDL_CreateColorCursor(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_SaveBMP_IO(), SDL_SetWindowIcon(), SDL_SetWindowShape(), and SDL_StretchSurface().
SDL_ConvertSurfaceAndColorspace()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_ConvertSurfaceAndColorspace (SDL_Surface * surface, SDL_PixelFormat format, SDL_Palette * palette, SDL_Colorspace colorspace, SDL_PropertiesID props) extern
Copy an existing surface to a new surface of the specified format and colorspace.
This function converts an existing surface to a new format and colorspace and returns the new surface. This will perform any pixel format and colorspace conversion needed.
If the original surface has alternate images, the new surface will have a reference to them as well.
Parameters
surface the existing SDL_Surface structure to convert.
format the new pixel format.
palette an optional palette to use for indexed formats, may be NULL.
colorspace the new colorspace.
props an SDL_PropertiesID with additional color properties, or 0.
Returns
the new SDL_Surface structure that is created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_ConvertSurface
SDL_DestroySurface
{
    SDL_Palette *temp_palette = NULL;
    SDL_Surface *convert = NULL;
    SDL_Colorspace src_colorspace;
    SDL_PropertiesID src_properties;
    Uint32 copy_flags;
    SDL_Color copy_color;
    SDL_Rect bounds;
    bool result;
    bool palette_ck_transform = false;
    Uint8 palette_ck_value = 0;
    Uint8 *palette_saved_alpha = NULL;
    int palette_saved_alpha_ncolors = 0;
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        goto error;
    }
    if (format == SDL_PIXELFORMAT_UNKNOWN) {
        SDL_InvalidParamError("format");
        goto error;
    }
    // Check for empty destination palette! (results in empty image)
    if (palette) {
        int i;
        for (i = 0; i < palette->ncolors; ++i) {
            if ((palette->colors[i].r != 0xFF) || (palette->colors[i].g != 0xFF) || (palette->colors[i].b != 0xFF)) {
                break;
            }
        }
        if (i == palette->ncolors) {
            SDL_SetError("Empty destination palette");
            goto error;
        }
    } else if (SDL_ISPIXELFORMAT_INDEXED(format)) {
        // Create a dither palette for conversion
        temp_palette = SDL_CreatePalette(1 << SDL_BITSPERPIXEL(format));
        if (temp_palette) {
            SDL_DitherPalette(temp_palette);
            palette = temp_palette;
        }
    }
    src_colorspace = surface->colorspace;
    src_properties = surface->props;
    // Create a new surface with the desired format
    convert = SDL_CreateSurface(surface->w, surface->h, format);
    if (!convert) {
        goto error;
    }
    if (SDL_ISPIXELFORMAT_INDEXED(format)) {
        SDL_SetSurfacePalette(convert, palette);
    }
    if (colorspace == SDL_COLORSPACE_UNKNOWN) {
        colorspace = src_colorspace;
    }
    SDL_SetSurfaceColorspace(convert, colorspace);
    if (SDL_ISPIXELFORMAT_FOURCC(format) || SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        if (surface->format == SDL_PIXELFORMAT_MJPG && format == SDL_PIXELFORMAT_MJPG) {
            // Just do a straight pixel copy of the JPEG image
            size_t size = (size_t)surface->pitch;
            convert->pixels = SDL_malloc(size);
            if (!convert->pixels) {
                goto error;
            }
            convert->flags &= ~SDL_SURFACE_PREALLOCATED;
            convert->pitch = surface->pitch;
            SDL_memcpy(convert->pixels, surface->pixels, size);
        } else if (!SDL_ConvertPixelsAndColorspace(surface->w, surface->h, surface->format, src_colorspace, src_properties, surface->pixels, surface->pitch, convert->format, colorspace, props, convert->pixels, convert->pitch)) {
            goto error;
        }
        // Save the original copy flags
        copy_flags = surface->map.info.flags;
        goto end;
    }
    // Save the original copy flags
    copy_flags = surface->map.info.flags;
    copy_color.r = surface->map.info.r;
    copy_color.g = surface->map.info.g;
    copy_color.b = surface->map.info.b;
    copy_color.a = surface->map.info.a;
    surface->map.info.r = 0xFF;
    surface->map.info.g = 0xFF;
    surface->map.info.b = 0xFF;
    surface->map.info.a = 0xFF;
    surface->map.info.flags = (copy_flags & (SDL_COPY_RLE_COLORKEY | SDL_COPY_RLE_ALPHAKEY));
    SDL_InvalidateMap(&surface->map);
    // Copy over the image data
    bounds.x = 0;
    bounds.y = 0;
    bounds.w = surface->w;
    bounds.h = surface->h;
    /* Source surface has a palette with no real alpha (0 or OPAQUE).
     * Destination format has alpha.
     * -> set alpha channel to be opaque */
    if (surface->palette && SDL_ISPIXELFORMAT_ALPHA(format)) {
        bool set_opaque = false;
        bool is_opaque, has_alpha_channel;
        SDL_DetectPalette(surface->palette, &is_opaque, &has_alpha_channel);
        if (is_opaque) {
            if (!has_alpha_channel) {
                set_opaque = true;
            }
        }
        // Set opaque and backup palette alpha values
        if (set_opaque) {
            int i;
            palette_saved_alpha_ncolors = surface->palette->ncolors;
            if (palette_saved_alpha_ncolors > 0) {
                palette_saved_alpha = SDL_stack_alloc(Uint8, palette_saved_alpha_ncolors);
                for (i = 0; i < palette_saved_alpha_ncolors; i++) {
                    palette_saved_alpha[i] = surface->palette->colors[i].a;
                    surface->palette->colors[i].a = SDL_ALPHA_OPAQUE;
                }
            }
        }
    }
    // Transform colorkey to alpha. for cases where source palette has duplicate values, and colorkey is one of them
    if (copy_flags & SDL_COPY_COLORKEY) {
        if (surface->palette && !palette) {
            palette_ck_transform = true;
            palette_ck_value = surface->palette->colors[surface->map.info.colorkey].a;
            surface->palette->colors[surface->map.info.colorkey].a = SDL_ALPHA_TRANSPARENT;
        }
    }
    result = SDL_BlitSurfaceUnchecked(surface, &bounds, convert, &bounds);
    // Restore colorkey alpha value
    if (palette_ck_transform) {
        surface->palette->colors[surface->map.info.colorkey].a = palette_ck_value;
    }
    // Restore palette alpha values
    if (palette_saved_alpha) {
        int i;
        for (i = 0; i < palette_saved_alpha_ncolors; i++) {
            surface->palette->colors[i].a = palette_saved_alpha[i];
        }
        SDL_stack_free(palette_saved_alpha);
    }
    // Clean up the original surface, and update converted surface
    convert->map.info.r = copy_color.r;
    convert->map.info.g = copy_color.g;
    convert->map.info.b = copy_color.b;
    convert->map.info.a = copy_color.a;
    convert->map.info.flags =
        (copy_flags &
         ~(SDL_COPY_COLORKEY | SDL_COPY_BLEND | SDL_COPY_RLE_DESIRED | SDL_COPY_RLE_COLORKEY |
           SDL_COPY_RLE_ALPHAKEY));
    surface->map.info.r = copy_color.r;
    surface->map.info.g = copy_color.g;
    surface->map.info.b = copy_color.b;
    surface->map.info.a = copy_color.a;
    surface->map.info.flags = copy_flags;
    SDL_InvalidateMap(&surface->map);
    // SDL_BlitSurfaceUnchecked failed, and so the conversion
    if (!result) {
        goto error;
    }
    if (copy_flags & SDL_COPY_COLORKEY) {
        bool set_colorkey_by_color = false;
        bool convert_colorkey = true;
        if (surface->palette) {
            if (palette &&
                surface->palette->ncolors <= palette->ncolors &&
                (SDL_memcmp(surface->palette->colors, palette->colors,
                            surface->palette->ncolors * sizeof(SDL_Color)) == 0)) {
                // The palette is identical, just set the same colorkey
                SDL_SetSurfaceColorKey(convert, true, surface->map.info.colorkey);
            } else if (!palette) {
                if (SDL_ISPIXELFORMAT_ALPHA(format)) {
                    // No need to add the colorkey, transparency is in the alpha channel
                } else {
                    // Only set the colorkey information
                    set_colorkey_by_color = true;
                    convert_colorkey = false;
                }
            } else {
                set_colorkey_by_color = true;
            }
        } else {
            set_colorkey_by_color = true;
        }
        if (set_colorkey_by_color) {
            SDL_Surface *tmp;
            SDL_Surface *tmp2;
            int converted_colorkey = 0;
            // Create a dummy surface to get the colorkey converted
            tmp = SDL_CreateSurface(1, 1, surface->format);
            if (!tmp) {
                goto error;
            }
            // Share the palette, if any
            if (surface->palette) {
                SDL_SetSurfacePalette(tmp, surface->palette);
            }
            SDL_FillSurfaceRect(tmp, NULL, surface->map.info.colorkey);
            tmp->map.info.flags &= ~SDL_COPY_COLORKEY;
            // Conversion of the colorkey
            tmp2 = SDL_ConvertSurfaceAndColorspace(tmp, format, palette, colorspace, props);
            if (!tmp2) {
                SDL_DestroySurface(tmp);
                goto error;
            }
            // Get the converted colorkey
            SDL_memcpy(&converted_colorkey, tmp2->pixels, tmp2->fmt->bytes_per_pixel);
            SDL_DestroySurface(tmp);
            SDL_DestroySurface(tmp2);
            // Set the converted colorkey on the new surface
            SDL_SetSurfaceColorKey(convert, true, converted_colorkey);
            // This is needed when converting for 3D texture upload
            if (convert_colorkey) {
                SDL_ConvertColorkeyToAlpha(convert, true);
            }
        }
    }
end:
    if (temp_palette) {
        SDL_DestroyPalette(temp_palette);
    }
    SDL_SetSurfaceClipRect(convert, &surface->clip_rect);
    /* Enable alpha blending by default if the new surface has an
     * alpha channel or alpha modulation */
    if (SDL_ISPIXELFORMAT_ALPHA(format) ||
        (copy_flags & SDL_COPY_MODULATE_ALPHA)) {
        SDL_SetSurfaceBlendMode(convert, SDL_BLENDMODE_BLEND);
    }
    if (copy_flags & SDL_COPY_RLE_DESIRED) {
        SDL_SetSurfaceRLE(convert, true);
    }
    // Copy alternate images
    for (int i = 0; i < surface->num_images; ++i) {
        if (!SDL_AddSurfaceAlternateImage(convert, surface->images[i])) {
            goto error;
        }
    }
    // We're ready to go!
    return convert;
error:
    if (temp_palette) {
        SDL_DestroyPalette(temp_palette);
    }
    if (convert) {
        SDL_DestroySurface(convert);
    }
    return NULL;
}
References SDL_BlitInfo::a, SDL_Color::a, SDL_BlitInfo::b, SDL_Color::b, SDL_PixelFormatDetails::bytes_per_pixel, SDL_Palette::colors, SDL_BlitInfo::flags, SDL_Surface::flags, SDL_Surface::fmt, SDL_Surface::format, SDL_BlitInfo::g, SDL_Color::g, SDL_Rect::h, SDL_BlitMap::info, SDL_Surface::map, SDL_Palette::ncolors, NULL, SDL_Surface::pitch, SDL_Surface::pixels, SDL_BlitInfo::r, SDL_Color::r, SDL_AddSurfaceAlternateImage(), SDL_ALPHA_OPAQUE, SDL_ALPHA_TRANSPARENT, SDL_BITSPERPIXEL, SDL_BLENDMODE_BLEND, SDL_BlitSurfaceUnchecked(), SDL_COLORSPACE_UNKNOWN, SDL_ConvertColorkeyToAlpha(), SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurfaceAndColorspace(), SDL_COPY_BLEND, SDL_COPY_COLORKEY, SDL_COPY_MODULATE_ALPHA, SDL_COPY_RLE_ALPHAKEY, SDL_COPY_RLE_COLORKEY, SDL_COPY_RLE_DESIRED, SDL_CreatePalette(), SDL_CreateSurface(), SDL_DestroyPalette(), SDL_DestroySurface(), SDL_DetectPalette(), SDL_DitherPalette(), SDL_FillSurfaceRect(), SDL_InvalidateMap(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_ALPHA, SDL_ISPIXELFORMAT_FOURCC, SDL_ISPIXELFORMAT_INDEXED, SDL_malloc(), SDL_memcmp(), SDL_memcpy, SDL_PIXELFORMAT_MJPG, SDL_PIXELFORMAT_UNKNOWN, SDL_SetError(), SDL_SetSurfaceBlendMode(), SDL_SetSurfaceClipRect(), SDL_SetSurfaceColorKey(), SDL_SetSurfaceColorspace(), SDL_SetSurfacePalette(), SDL_SetSurfaceRLE(), SDL_stack_alloc, SDL_stack_free, SDL_SURFACE_PREALLOCATED, SDL_SurfaceValid(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_ConvertSurface(), SDL_ConvertSurfaceAndColorspace(), SDL_DuplicateSurface(), SDL_ScaleSurface(), SDL_StretchSurface(), and SDL_UpdateTextureFromSurface().
SDL_CreateSurface()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_CreateSurface (int width, int height, SDL_PixelFormat format) extern
Allocate a new surface with a specific pixel format.
The pixels of the new surface are initialized to zero.
Parameters
width the width of the surface.
height the height of the surface.
format the SDL_PixelFormat for the new surface's pixel format.
Returns
the new SDL_Surface structure that is created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateSurfaceFrom
SDL_DestroySurface
{
    size_t pitch, size;
    SDL_Surface *surface;
    if (width < 0) {
        SDL_InvalidParamError("width");
        return NULL;
    }
    if (height < 0) {
        SDL_InvalidParamError("height");
        return NULL;
    }
    if (format == SDL_PIXELFORMAT_UNKNOWN) {
        SDL_InvalidParamError("format");
        return NULL;
    }
    if (!SDL_CalculateSurfaceSize(format, width, height, &size, &pitch, false /* not minimal pitch */)) {
        // Overflow...
        return NULL;
    }
    // Allocate and initialize the surface
    surface = (SDL_Surface *)SDL_malloc(sizeof(*surface));
    if (!surface) {
        return NULL;
    }
    if (!SDL_InitializeSurface(surface, width, height, format, SDL_COLORSPACE_UNKNOWN, 0, NULL, (int)pitch, false)) {
        return NULL;
    }
    if (surface->w && surface->h && format != SDL_PIXELFORMAT_MJPG) {
        surface->flags &= ~SDL_SURFACE_PREALLOCATED;
        surface->pixels = SDL_aligned_alloc(SDL_GetSIMDAlignment(), size);
        if (!surface->pixels) {
            SDL_DestroySurface(surface);
            return NULL;
        }
        surface->flags |= SDL_SURFACE_SIMD_ALIGNED;
        // This is important for bitmaps
        SDL_memset(surface->pixels, 0, size);
    }
    return surface;
}
References NULL, SDL_aligned_alloc(), SDL_CalculateSurfaceSize(), SDL_COLORSPACE_UNKNOWN, SDL_DestroySurface(), SDL_GetSIMDAlignment(), SDL_InitializeSurface(), SDL_InvalidParamError, SDL_malloc(), SDL_memset, SDL_PIXELFORMAT_MJPG, SDL_PIXELFORMAT_UNKNOWN, SDL_SURFACE_PREALLOCATED, and SDL_SURFACE_SIMD_ALIGNED.
Referenced by CreateDebugTextAtlas(), SDL_BlitSurfaceUncheckedScaled(), SDL_ClearSurface(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateCursor(), SDL_DuplicatePixels(), SDL_LoadBMP_IO(), SDL_PostInitMouse(), SDL_PremultiplyAlphaPixelsAndColorspace(), SDL_PrepareCameraSurfaces(), SDL_ScaleSurface(), and SDL_StretchSurface().
SDL_CreateSurfaceFrom()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_CreateSurfaceFrom (int width, int height, SDL_PixelFormat format, void * pixels, int pitch) extern
Allocate a new surface with a specific pixel format and existing pixel data.
No copy is made of the pixel data. Pixel data is not managed automatically; you must free the surface before you free the pixel data.
Pitch is the offset in bytes from one row of pixels to the next, e.g. width*4 for SDL_PIXELFORMAT_RGBA8888.
You may pass NULL for pixels and 0 for pitch to create a surface that you will fill in with valid values later.
Parameters
width the width of the surface.
height the height of the surface.
format the SDL_PixelFormat for the new surface's pixel format.
pixels a pointer to existing pixel data.
pitch the number of bytes between each row, including padding.
Returns
the new SDL_Surface structure that is created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateSurface
SDL_DestroySurface
{
    if (width < 0) {
        SDL_InvalidParamError("width");
        return NULL;
    }
    if (height < 0) {
        SDL_InvalidParamError("height");
        return NULL;
    }
    if (format == SDL_PIXELFORMAT_UNKNOWN) {
        SDL_InvalidParamError("format");
        return NULL;
    }
    if (pitch == 0 && !pixels) {
        // The application will fill these in later with valid values
    } else {
        size_t minimalPitch;
        if (!SDL_CalculateSurfaceSize(format, width, height, NULL, &minimalPitch, true /* minimal pitch */)) {
            // Overflow...
            return NULL;
        }
        if (pitch < 0 || (size_t)pitch < minimalPitch) {
            SDL_InvalidParamError("pitch");
            return NULL;
        }
    }
    // Allocate and initialize the surface
    SDL_Surface *surface = (SDL_Surface *)SDL_malloc(sizeof(*surface));
    if (!surface ||
        !SDL_InitializeSurface(surface, width, height, format, SDL_COLORSPACE_UNKNOWN, 0, pixels, pitch, false)) {
        return NULL;
    }
    return surface;
}
References NULL, SDL_CalculateSurfaceSize(), SDL_COLORSPACE_UNKNOWN, SDL_InitializeSurface(), SDL_InvalidParamError, SDL_malloc(), and SDL_PIXELFORMAT_UNKNOWN.
Referenced by SDL_CreateWindowFramebuffer(), SDL_LockTextureToSurface(), and SDL_PrepareCameraSurfaces().
SDL_CreateSurfacePalette()
SDL_DECLSPEC SDL_Palette *SDLCALL SDL_CreateSurfacePalette (SDL_Surface * surface) extern
Create a palette and associate it with a surface.
This function creates a palette compatible with the provided surface. The palette is then returned for you to modify, and the surface will automatically use the new palette in future operations. You do not need to destroy the returned palette, it will be freed when the reference count reaches 0, usually when the surface is destroyed.
Bitmap surfaces (with format SDL_PIXELFORMAT_INDEX1LSB or SDL_PIXELFORMAT_INDEX1MSB) will have the palette initialized with 0 as white and 1 as black. Other surfaces will get a palette initialized with white in every entry.
If this function is called for a surface that already has a palette, a new palette will be created to replace it.
Parameters
surface the SDL_Surface structure to update.
Returns
a new SDL_Palette structure on success or NULL on failure (e.g. if the surface didn't have an index format); call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetPaletteColors
{
    SDL_Palette *palette;
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        return NULL;
    }
    if (!SDL_ISPIXELFORMAT_INDEXED(surface->format)) {
        SDL_SetError("The surface is not indexed format");
        return NULL;
    }
    palette = SDL_CreatePalette((1 << SDL_BITSPERPIXEL(surface->format)));
    if (!palette) {
        return NULL;
    }
    if (palette->ncolors == 2) {
        // Create a black and white bitmap palette
        palette->colors[0].r = 0xFF;
        palette->colors[0].g = 0xFF;
        palette->colors[0].b = 0xFF;
        palette->colors[1].r = 0x00;
        palette->colors[1].g = 0x00;
        palette->colors[1].b = 0x00;
    }
    if (!SDL_SetSurfacePalette(surface, palette)) {
        SDL_DestroyPalette(palette);
        return NULL;
    }
    // The surface has retained the palette, we can remove the reference here
    SDL_assert(palette->refcount == 2);
    SDL_DestroyPalette(palette);
    return palette;
}
References SDL_Color::b, SDL_Palette::colors, SDL_Color::g, SDL_Palette::ncolors, NULL, SDL_Color::r, SDL_Palette::refcount, SDL_assert, SDL_BITSPERPIXEL, SDL_CreatePalette(), SDL_DestroyPalette(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_INDEXED, SDL_SetError(), SDL_SetSurfacePalette(), and SDL_SurfaceValid().
Referenced by SDL_LoadBMP_IO().
SDL_DestroySurface()
SDL_DECLSPEC void SDLCALL SDL_DestroySurface (SDL_Surface * surface) extern
Free a surface.
It is safe to pass NULL to this function.
Parameters
surface the SDL_Surface to free.
Thread Safety
No other thread should be using the surface when it is freed.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateSurface
SDL_CreateSurfaceFrom
< Surface is referenced internally
< Surface is allocated on the stack
{
    if (!SDL_SurfaceValid(surface)) {
        return;
    }
    if (surface->internal_flags & SDL_INTERNAL_SURFACE_DONTFREE) {
        return;
    }
    if (--surface->refcount > 0) {
        return;
    }
    SDL_RemoveSurfaceAlternateImages(surface);
    SDL_DestroyProperties(surface->props);
    SDL_InvalidateMap(&surface->map);
    while (surface->locked > 0) {
        SDL_UnlockSurface(surface);
    }
#ifdef SDL_HAVE_RLE
    if (surface->internal_flags & SDL_INTERNAL_SURFACE_RLEACCEL) {
        SDL_UnRLESurface(surface, false);
    }
#endif
    SDL_SetSurfacePalette(surface, NULL);
    if (surface->flags & SDL_SURFACE_PREALLOCATED) {
        // Don't free
    } else if (surface->flags & SDL_SURFACE_SIMD_ALIGNED) {
        // Free aligned
        SDL_aligned_free(surface->pixels);
    } else {
        // Normal
        SDL_free(surface->pixels);
    }
    surface->reserved = NULL;
    if (!(surface->internal_flags & SDL_INTERNAL_SURFACE_STACK)) {
        SDL_free(surface);
    }
}
References NULL, SDL_aligned_free(), SDL_DestroyProperties(), SDL_free(), SDL_INTERNAL_SURFACE_DONTFREE, SDL_INTERNAL_SURFACE_RLEACCEL, SDL_INTERNAL_SURFACE_STACK, SDL_InvalidateMap(), SDL_RemoveSurfaceAlternateImages(), SDL_SetSurfacePalette(), SDL_SURFACE_PREALLOCATED, SDL_SURFACE_SIMD_ALIGNED, SDL_SurfaceValid(), SDL_UnlockSurface(), and SDL_UnRLESurface().
Referenced by CleanupSurface(), ClosePhysicalCamera(), CreateDebugTextAtlas(), CreateIconFromSurface(), SDL_BlitSurfaceUncheckedScaled(), SDL_ClearSurface(), SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateColorCursor(), SDL_CreateCursor(), SDL_CreateSurface(), SDL_DestroyTextureInternal(), SDL_DestroyWindow(), SDL_DestroyWindowSurface(), SDL_GetSurfaceImage(), SDL_GetWindowSurface(), SDL_InitializeSurface(), SDL_LoadBMP_IO(), SDL_PostInitMouse(), SDL_PremultiplyAlphaPixelsAndColorspace(), SDL_PrepareCameraSurfaces(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_RemoveSurfaceAlternateImages(), SDL_SaveBMP_IO(), SDL_ScaleSurface(), SDL_SetWindowIcon(), SDL_StretchSurface(), SDL_UnlockTexture(), and SDL_UpdateTextureFromSurface().
SDL_DuplicateSurface()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_DuplicateSurface (SDL_Surface * surface) extern
Creates a new surface identical to the existing surface.
If the original surface has alternate images, the new surface will have a reference to them as well.
The returned surface should be freed with SDL_DestroySurface().
Parameters
surface the surface to duplicate.
Returns
a copy of the surface or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroySurface
{
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        return NULL;
    }
    return SDL_ConvertSurfaceAndColorspace(surface, surface->format, surface->palette, surface->colorspace, surface->props);
}
References NULL, SDL_ConvertSurfaceAndColorspace(), SDL_InvalidParamError, and SDL_SurfaceValid().
SDL_FillSurfaceRect()
SDL_DECLSPEC bool SDLCALL SDL_FillSurfaceRect (SDL_Surface * dst, const SDL_Rect * rect, Uint32 color) extern
Perform a fast fill of a rectangle with a specific color.
color should be a pixel of the format used by the surface, and can be generated by SDL_MapRGB() or SDL_MapRGBA(). If the color value contains an alpha component then the destination is simply filled with that alpha information, no blending takes place.
If there is a clip rectangle set on the destination (set via SDL_SetSurfaceClipRect()), then this function will fill based on the intersection of the clip rectangle and rect.
Parameters
dst the SDL_Surface structure that is the drawing target.
rect the SDL_Rect structure representing the rectangle to fill, or NULL to fill the entire surface.
color the color to fill with.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_FillSurfaceRects
{
    if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("SDL_FillSurfaceRect(): dst");
    }
    // If 'rect' == NULL, then fill the whole surface
    if (!rect) {
        rect = &dst->clip_rect;
        // Don't attempt to fill if the surface's clip_rect is empty
        if (SDL_RectEmpty(rect)) {
            return true;
        }
    }
    return SDL_FillSurfaceRects(dst, rect, 1, color);
}
References SDL_Surface::clip_rect, SDL_FillSurfaceRects(), SDL_InvalidParamError, SDL_RectEmpty(), and SDL_SurfaceValid().
Referenced by SDL_ClearSurface(), and SDL_ConvertSurfaceAndColorspace().
SDL_FillSurfaceRects()
SDL_DECLSPEC bool SDLCALL SDL_FillSurfaceRects (SDL_Surface * dst, const SDL_Rect * rects, int count, Uint32 color) extern
Perform a fast fill of a set of rectangles with a specific color.
color should be a pixel of the format used by the surface, and can be generated by SDL_MapRGB() or SDL_MapRGBA(). If the color value contains an alpha component then the destination is simply filled with that alpha information, no blending takes place.
If there is a clip rectangle set on the destination (set via SDL_SetSurfaceClipRect()), then this function will fill based on the intersection of the clip rectangle and rect.
Parameters
dst the SDL_Surface structure that is the drawing target.
rects an array of SDL_Rects representing the rectangles to fill.
count the number of rectangles in the array.
color the color to fill with.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_FillSurfaceRect
{
    SDL_Rect clipped;
    Uint8 *pixels;
    const SDL_Rect *rect;
    void (*fill_function)(Uint8 * pixels, int pitch, Uint32 color, int w, int h) = NULL;
    int i;
    if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("SDL_FillSurfaceRects(): dst");
    }
    // Nothing to do
    if (dst->w == 0 || dst->h == 0) {
        return true;
    }
    // Perform software fill
    if (!dst->pixels) {
        return SDL_SetError("SDL_FillSurfaceRects(): You must lock the surface");
    }
    if (!rects) {
        return SDL_InvalidParamError("SDL_FillSurfaceRects(): rects");
    }
    /* This function doesn't usually work on surfaces < 8 bpp
     * Except: support for 4bits, when filling full size.
     */
    if (SDL_BITSPERPIXEL(dst->format) < 8) {
        if (count == 1) {
            const SDL_Rect *r = &rects[0];
            if (r->x == 0 && r->y == 0 && r->w == dst->w && r->h == dst->h) {
                if (SDL_BITSPERPIXEL(dst->format) == 4) {
                    Uint8 b = (((Uint8)color << 4) | (Uint8)color);
                    SDL_memset(dst->pixels, b, (size_t)dst->h * dst->pitch);
                    return true;
                }
            }
        }
        return SDL_SetError("SDL_FillSurfaceRects(): Unsupported surface format");
    }
    if (fill_function == NULL) {
        switch (SDL_BYTESPERPIXEL(dst->format)) {
        case 1:
        {
            color |= (color << 8);
            color |= (color << 16);
#ifdef SDL_SSE_INTRINSICS
            if (SDL_HasSSE()) {
                fill_function = SDL_FillSurfaceRect1SSE;
                break;
            }
#endif
            fill_function = SDL_FillSurfaceRect1;
            break;
        }
        case 2:
        {
            color |= (color << 16);
#ifdef SDL_SSE_INTRINSICS
            if (SDL_HasSSE()) {
                fill_function = SDL_FillSurfaceRect2SSE;
                break;
            }
#endif
            fill_function = SDL_FillSurfaceRect2;
            break;
        }
        case 3:
            // 24-bit RGB is a slow path, at least for now.
            {
                fill_function = SDL_FillSurfaceRect3;
                break;
            }
        case 4:
        {
#ifdef SDL_SSE_INTRINSICS
            if (SDL_HasSSE()) {
                fill_function = SDL_FillSurfaceRect4SSE;
                break;
            }
#endif
            fill_function = SDL_FillSurfaceRect4;
            break;
        }
        default:
            return SDL_SetError("Unsupported pixel format");
        }
    }
    for (i = 0; i < count; ++i) {
        rect = &rects[i];
        // Perform clipping
        if (!SDL_GetRectIntersection(rect, &dst->clip_rect, &clipped)) {
            continue;
        }
        rect = &clipped;
        pixels = (Uint8 *)dst->pixels + rect->y * dst->pitch +
                 rect->x * SDL_BYTESPERPIXEL(dst->format);
        fill_function(pixels, dst->pitch, color, rect->w, rect->h);
    }
    // We're done!
    return true;
}
References SDL_Surface::clip_rect, count, SDL_Surface::format, SDL_Rect::h, SDL_Surface::h, NULL, SDL_Surface::pitch, SDL_Surface::pixels, SDL_BITSPERPIXEL, SDL_BYTESPERPIXEL, SDL_FillSurfaceRect1(), SDL_FillSurfaceRect2(), SDL_FillSurfaceRect3(), SDL_FillSurfaceRect4(), SDL_GetRectIntersection(), SDL_HasSSE(), SDL_InvalidParamError, SDL_memset, SDL_SetError(), SDL_SurfaceValid(), void(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_FillSurfaceRect().
SDL_FlipSurface()
SDL_DECLSPEC bool SDLCALL SDL_FlipSurface (SDL_Surface * surface, SDL_FlipMode flip) extern
Flip a surface vertically or horizontally.
Parameters
surface the surface to flip.
flip the direction to flip.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (!surface->pixels) {
        return true;
    }
    switch (flip) {
    case SDL_FLIP_HORIZONTAL:
        return SDL_FlipSurfaceHorizontal(surface);
    case SDL_FLIP_VERTICAL:
        return SDL_FlipSurfaceVertical(surface);
    default:
        return SDL_InvalidParamError("flip");
    }
}
References SDL_FLIP_HORIZONTAL, SDL_FLIP_VERTICAL, SDL_FlipSurfaceHorizontal(), SDL_FlipSurfaceVertical(), SDL_InvalidParamError, and SDL_SurfaceValid().
SDL_GetSurfaceAlphaMod()
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceAlphaMod (SDL_Surface * surface, Uint8 * alpha) extern
Get the additional alpha value used in blit operations.
Parameters
surface the SDL_Surface structure to query.
alpha a pointer filled in with the current alpha value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceColorMod
SDL_SetSurfaceAlphaMod
{
    if (!SDL_SurfaceValid(surface)) {
        if (alpha) {
            *alpha = 255;
        }
        return SDL_InvalidParamError("surface");
    }
    if (alpha) {
        *alpha = surface->map.info.a;
    }
    return true;
}
References SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_BlitSurfaceUncheckedScaled(), and SDL_UpdateTextureFromSurface().
SDL_GetSurfaceBlendMode()
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceBlendMode (SDL_Surface * surface, SDL_BlendMode * blendMode) extern
Get the blend mode used for blit operations.
Parameters
surface the SDL_Surface structure to query.
blendMode a pointer filled in with the current SDL_BlendMode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetSurfaceBlendMode
{
    if (blendMode) {
        *blendMode = SDL_BLENDMODE_INVALID;
    }
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (!blendMode) {
        return true;
    }
    switch (surface->map.info.flags & SDL_COPY_BLEND_MASK) {
    case SDL_COPY_BLEND:
        *blendMode = SDL_BLENDMODE_BLEND;
        break;
    case SDL_COPY_BLEND_PREMULTIPLIED:
        *blendMode = SDL_BLENDMODE_BLEND_PREMULTIPLIED;
        break;
    case SDL_COPY_ADD:
        *blendMode = SDL_BLENDMODE_ADD;
        break;
    case SDL_COPY_ADD_PREMULTIPLIED:
        *blendMode = SDL_BLENDMODE_ADD_PREMULTIPLIED;
        break;
    case SDL_COPY_MOD:
        *blendMode = SDL_BLENDMODE_MOD;
        break;
    case SDL_COPY_MUL:
        *blendMode = SDL_BLENDMODE_MUL;
        break;
    default:
        *blendMode = SDL_BLENDMODE_NONE;
        break;
    }
    return true;
}
References SDL_BLENDMODE_ADD, SDL_BLENDMODE_ADD_PREMULTIPLIED, SDL_BLENDMODE_BLEND, SDL_BLENDMODE_BLEND_PREMULTIPLIED, SDL_BLENDMODE_INVALID, SDL_BLENDMODE_MOD, SDL_BLENDMODE_MUL, SDL_BLENDMODE_NONE, SDL_COPY_ADD, SDL_COPY_ADD_PREMULTIPLIED, SDL_COPY_BLEND, SDL_COPY_BLEND_MASK, SDL_COPY_BLEND_PREMULTIPLIED, SDL_COPY_MOD, SDL_COPY_MUL, SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_BlitSurfaceUncheckedScaled(), and SDL_UpdateTextureFromSurface().
SDL_GetSurfaceClipRect()
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceClipRect (SDL_Surface * surface, SDL_Rect * rect) extern
Get the clipping rectangle for a surface.
When surface is the destination of a blit, only the area within the clip rectangle is drawn into.
Parameters
surface the SDL_Surface structure representing the surface to be clipped.
rect an SDL_Rect structure filled in with the clipping rectangle for the surface.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetSurfaceClipRect
{
    if (!SDL_SurfaceValid(surface)) {
        if (rect) {
            SDL_zerop(rect);
        }
        return SDL_InvalidParamError("surface");
    }
    if (!rect) {
        return SDL_InvalidParamError("rect");
    }
    *rect = surface->clip_rect;
    return true;
}
References SDL_InvalidParamError, SDL_SurfaceValid(), and SDL_zerop.
Referenced by SDL_ClearSurface().
SDL_GetSurfaceColorKey()
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceColorKey (SDL_Surface * surface, Uint32 * key) extern
Get the color key (transparent pixel) for a surface.
The color key is a pixel of the format used by the surface, as generated by SDL_MapRGB().
If the surface doesn't have color key enabled this function returns false.
Parameters
surface the SDL_Surface structure to query.
key a pointer filled in with the transparent pixel.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetSurfaceColorKey
SDL_SurfaceHasColorKey
{
    if (key) {
        *key = 0;
    }
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (!(surface->map.info.flags & SDL_COPY_COLORKEY)) {
        return SDL_SetError("Surface doesn't have a colorkey");
    }
    if (key) {
        *key = surface->map.info.colorkey;
    }
    return true;
}
References SDL_COPY_COLORKEY, SDL_InvalidParamError, SDL_SetError(), and SDL_SurfaceValid().
SDL_GetSurfaceColorMod()
SDL_DECLSPEC bool SDLCALL SDL_GetSurfaceColorMod (SDL_Surface * surface, Uint8 * r, Uint8 * g, Uint8 * b) extern
Get the additional color value multiplied into blit operations.
Parameters
surface the SDL_Surface structure to query.
r a pointer filled in with the current red color value.
g a pointer filled in with the current green color value.
b a pointer filled in with the current blue color value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceAlphaMod
SDL_SetSurfaceColorMod
{
    if (!SDL_SurfaceValid(surface)) {
        if (r) {
            *r = 255;
        }
        if (g) {
            *g = 255;
        }
        if (b) {
            *b = 255;
        }
        return SDL_InvalidParamError("surface");
    }
    if (r) {
        *r = surface->map.info.r;
    }
    if (g) {
        *g = surface->map.info.g;
    }
    if (b) {
        *b = surface->map.info.b;
    }
    return true;
}
References SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_BlitSurfaceUncheckedScaled(), and SDL_UpdateTextureFromSurface().
SDL_GetSurfaceColorspace()
SDL_DECLSPEC SDL_Colorspace SDLCALL SDL_GetSurfaceColorspace (SDL_Surface * surface) extern
Get the colorspace used by a surface.
The colorspace defaults to SDL_COLORSPACE_SRGB_LINEAR for floating point formats, SDL_COLORSPACE_HDR10 for 10-bit formats, SDL_COLORSPACE_SRGB for other RGB surfaces and SDL_COLORSPACE_BT709_FULL for YUV textures.
Parameters
surface the SDL_Surface structure to query.
Returns
the colorspace used by the surface, or SDL_COLORSPACE_UNKNOWN if the surface is NULL.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetSurfaceColorspace
{
    if (!SDL_SurfaceValid(surface)) {
        return SDL_COLORSPACE_UNKNOWN;
    }
    return surface->colorspace;
}
References SDL_COLORSPACE_UNKNOWN, and SDL_SurfaceValid().
Referenced by SDL_CreateTextureFromSurface(), and SDL_UpdateTextureFromSurface().
SDL_GetSurfaceImages()
SDL_DECLSPEC SDL_Surface **SDLCALL SDL_GetSurfaceImages (SDL_Surface * surface, int * count) extern
Get an array including all versions of a surface.
This returns all versions of a surface, with the surface being queried as the first element in the returned array.
Freeing the array of surfaces does not affect the surfaces in the array. They are still referenced by the surface being queried and will be cleaned up normally.
Parameters
surface the SDL_Surface structure to query.
count a pointer filled in with the number of surface pointers returned, may be NULL.
Returns
a NULL terminated array of SDL_Surface pointers or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddSurfaceAlternateImage
SDL_RemoveSurfaceAlternateImages
SDL_SurfaceHasAlternateImages
{
    if (count) {
        *count = 0;
    }
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        return NULL;
    }
    int num_images = 1 + surface->num_images;
    SDL_Surface **images = (SDL_Surface **)SDL_malloc((num_images + 1) * sizeof(*images));
    if (!images) {
        return NULL;
    }
    images[0] = surface;
    if (surface->num_images > 0) {
        SDL_memcpy(&images[1], surface->images, (surface->num_images * sizeof(images[1])));
    }
    images[num_images] = NULL;
    if (count) {
        *count = num_images;
    }
    return images;
}
References count, NULL, SDL_InvalidParamError, SDL_malloc(), SDL_memcpy, and SDL_SurfaceValid().
Referenced by SDL_GetSurfaceImage().
SDL_GetSurfacePalette()
SDL_DECLSPEC SDL_Palette *SDLCALL SDL_GetSurfacePalette (SDL_Surface * surface) extern
Get the palette used by a surface.
Parameters
surface the SDL_Surface structure to query.
Returns
a pointer to the palette used by the surface, or NULL if there is no palette used.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetSurfacePalette
{
    if (!SDL_SurfaceValid(surface)) {
        return NULL;
    }
    return surface->palette;
}
References NULL, and SDL_SurfaceValid().
Referenced by SDL_CreateTextureFromSurface().
SDL_GetSurfaceProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetSurfaceProperties (SDL_Surface * surface) extern
Get the properties associated with a surface.
The following properties are understood by SDL:
SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT: for HDR10 and floating point surfaces, this defines the value of 100% diffuse white, with higher values being displayed in the High Dynamic Range headroom. This defaults to 203 for HDR10 surfaces and 1.0 for floating point surfaces.
SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT: for HDR10 and floating point surfaces, this defines the maximum dynamic range used by the content, in terms of the SDR white point. This defaults to 0.0, which disables tone mapping.
SDL_PROP_SURFACE_TONEMAP_OPERATOR_STRING: the tone mapping operator used when compressing from a surface with high dynamic range to another with lower dynamic range. Currently this supports "chrome", which uses the same tone mapping that Chrome uses for HDR content, the form "*=N", where N is a floating point scale factor applied in linear space, and "none", which disables tone mapping. This defaults to "chrome".
SDL_PROP_SURFACE_HOTSPOT_X_NUMBER: the hotspot pixel offset from the left edge of the image, if this surface is being used as a cursor.
SDL_PROP_SURFACE_HOTSPOT_Y_NUMBER: the hotspot pixel offset from the top edge of the image, if this surface is being used as a cursor.
Parameters
surface the SDL_Surface structure to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        return 0;
    }
    if (!surface->props) {
        surface->props = SDL_CreateProperties();
    }
    return surface->props;
}
References SDL_CreateProperties(), SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_Blit_Slow_Float(), SDL_CreateColorCursor(), SDL_InitializeSurface(), SDL_RenderReadPixels(), SDL_StretchSurface(), and SDL_UpdateTextureFromSurface().
SDL_LoadBMP()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_LoadBMP (const char * file) extern
Load a BMP image from a file.
The new surface should be freed with SDL_DestroySurface(). Not doing so will result in a memory leak.
Parameters
file the BMP file to load.
Returns
a pointer to a new SDL_Surface structure or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroySurface
SDL_LoadBMP_IO
SDL_SaveBMP
{
    SDL_IOStream *stream = SDL_IOFromFile(file, "rb");
    if (!stream) {
        return NULL;
    }
    return SDL_LoadBMP_IO(stream, true);
}
References NULL, SDL_IOFromFile(), and SDL_LoadBMP_IO().
SDL_LoadBMP_IO()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_LoadBMP_IO (SDL_IOStream * src, bool closeio) extern
Load a BMP image from a seekable SDL data stream.
The new surface should be freed with SDL_DestroySurface(). Not doing so will result in a memory leak.
Parameters
src the data stream for the surface.
closeio if true, calls SDL_CloseIO() on src before returning, even in the case of an error.
Returns
a pointer to a new SDL_Surface structure or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroySurface
SDL_LoadBMP
SDL_SaveBMP_IO
{
    bool was_error = true;
    Sint64 fp_offset = 0;
    int i, pad;
    SDL_Surface *surface;
    Uint32 Rmask = 0;
    Uint32 Gmask = 0;
    Uint32 Bmask = 0;
    Uint32 Amask = 0;
    Uint8 *bits;
    Uint8 *top, *end;
    bool topDown;
    bool haveRGBMasks = false;
    bool haveAlphaMask = false;
    bool correctAlpha = false;
    // The Win32 BMP file header (14 bytes)
    char magic[2];
    // Uint32 bfSize;
    // Uint16 bfReserved1;
    // Uint16 bfReserved2;
    Uint32 bfOffBits;
    // The Win32 BITMAPINFOHEADER struct (40 bytes)
    Uint32 biSize;
    Sint32 biWidth = 0;
    Sint32 biHeight = 0;
    // Uint16 biPlanes;
    Uint16 biBitCount = 0;
    Uint32 biCompression = 0;
    // Uint32 biSizeImage;
    // Sint32 biXPelsPerMeter;
    // Sint32 biYPelsPerMeter;
    Uint32 biClrUsed = 0;
    // Uint32 biClrImportant;
    // Make sure we are passed a valid data source
    surface = NULL;
    if (!src) {
        SDL_InvalidParamError("src");
        goto done;
    }
    // Read in the BMP file header
    fp_offset = SDL_TellIO(src);
    if (fp_offset < 0) {
        goto done;
    }
    SDL_ClearError();
    if (SDL_ReadIO(src, magic, 2) != 2) {
        goto done;
    }
    if (SDL_strncmp(magic, "BM", 2) != 0) {
        SDL_SetError("File is not a Windows BMP file");
        goto done;
    }
    if (!SDL_ReadU32LE(src, NULL /* bfSize */) ||
        !SDL_ReadU16LE(src, NULL /* bfReserved1 */) ||
        !SDL_ReadU16LE(src, NULL /* bfReserved2 */) ||
        !SDL_ReadU32LE(src, &bfOffBits)) {
        goto done;
    }
    // Read the Win32 BITMAPINFOHEADER
    if (!SDL_ReadU32LE(src, &biSize)) {
        goto done;
    }
    if (biSize == 12) { // really old BITMAPCOREHEADER
        Uint16 biWidth16, biHeight16;
        if (!SDL_ReadU16LE(src, &biWidth16) ||
            !SDL_ReadU16LE(src, &biHeight16) ||
            !SDL_ReadU16LE(src, NULL /* biPlanes */) ||
            !SDL_ReadU16LE(src, &biBitCount)) {
            goto done;
        }
        biWidth = biWidth16;
        biHeight = biHeight16;
        biCompression = BI_RGB;
        // biSizeImage = 0;
        // biXPelsPerMeter = 0;
        // biYPelsPerMeter = 0;
        biClrUsed = 0;
        // biClrImportant = 0;
    } else if (biSize >= 40) { // some version of BITMAPINFOHEADER
        Uint32 headerSize;
        if (!SDL_ReadS32LE(src, &biWidth) ||
            !SDL_ReadS32LE(src, &biHeight) ||
            !SDL_ReadU16LE(src, NULL /* biPlanes */) ||
            !SDL_ReadU16LE(src, &biBitCount) ||
            !SDL_ReadU32LE(src, &biCompression) ||
            !SDL_ReadU32LE(src, NULL /* biSizeImage */) ||
            !SDL_ReadU32LE(src, NULL /* biXPelsPerMeter */) ||
            !SDL_ReadU32LE(src, NULL /* biYPelsPerMeter */) ||
            !SDL_ReadU32LE(src, &biClrUsed) ||
            !SDL_ReadU32LE(src, NULL /* biClrImportant */)) {
            goto done;
        }
        // 64 == BITMAPCOREHEADER2, an incompatible OS/2 2.x extension. Skip this stuff for now.
        if (biSize != 64) {
            /* This is complicated. If compression is BI_BITFIELDS, then
               we have 3 DWORDS that specify the RGB masks. This is either
               stored here in an BITMAPV2INFOHEADER (which only differs in
               that it adds these RGB masks) and biSize >= 52, or we've got
               these masks stored in the exact same place, but strictly
               speaking, this is the bmiColors field in BITMAPINFO immediately
               following the legacy v1 info header, just past biSize. */
            if (biCompression == BI_BITFIELDS) {
                haveRGBMasks = true;
                if (!SDL_ReadU32LE(src, &Rmask) ||
                    !SDL_ReadU32LE(src, &Gmask) ||
                    !SDL_ReadU32LE(src, &Bmask)) {
                    goto done;
                }
                // ...v3 adds an alpha mask.
                if (biSize >= 56) { // BITMAPV3INFOHEADER; adds alpha mask
                    haveAlphaMask = true;
                    if (!SDL_ReadU32LE(src, &Amask)) {
                        goto done;
                    }
                }
            } else {
                // the mask fields are ignored for v2+ headers if not BI_BITFIELD.
                if (biSize >= 52) { // BITMAPV2INFOHEADER; adds RGB masks
                    if (!SDL_ReadU32LE(src, NULL /* Rmask */) ||
                        !SDL_ReadU32LE(src, NULL /* Gmask */) ||
                        !SDL_ReadU32LE(src, NULL /* Bmask */)) {
                        goto done;
                    }
                }
                if (biSize >= 56) { // BITMAPV3INFOHEADER; adds alpha mask
                    if (!SDL_ReadU32LE(src, NULL /* Amask */)) {
                        goto done;
                    }
                }
            }
            /* Insert other fields here; Wikipedia and MSDN say we're up to
               v5 of this header, but we ignore those for now (they add gamma,
               color spaces, etc). Ignoring the weird OS/2 2.x format, we
               currently parse up to v3 correctly (hopefully!). */
        }
        // skip any header bytes we didn't handle...
        headerSize = (Uint32)(SDL_TellIO(src) - (fp_offset + 14));
        if (biSize > headerSize) {
            if (SDL_SeekIO(src, (biSize - headerSize), SDL_IO_SEEK_CUR) < 0) {
                goto done;
            }
        }
    }
    if (biWidth <= 0 || biHeight == 0) {
        SDL_SetError("BMP file with bad dimensions (%" SDL_PRIs32 "x%" SDL_PRIs32 ")", biWidth, biHeight);
        goto done;
    }
    if (biHeight < 0) {
        topDown = true;
        biHeight = -biHeight;
    } else {
        topDown = false;
    }
    // Check for read error
    if (SDL_strcmp(SDL_GetError(), "") != 0) {
        goto done;
    }
    // Reject invalid bit depths
    switch (biBitCount) {
    case 0:
    case 3:
    case 5:
    case 6:
    case 7:
        SDL_SetError("%u bpp BMP images are not supported", biBitCount);
        goto done;
    default:
        break;
    }
    // RLE4 and RLE8 BMP compression is supported
    switch (biCompression) {
    case BI_RGB:
        // If there are no masks, use the defaults
        SDL_assert(!haveRGBMasks);
        SDL_assert(!haveAlphaMask);
        // Default values for the BMP format
        switch (biBitCount) {
        case 15:
        case 16:
            // SDL_PIXELFORMAT_XRGB1555 or SDL_PIXELFORMAT_ARGB1555 if Amask
            Rmask = 0x7C00;
            Gmask = 0x03E0;
            Bmask = 0x001F;
            break;
        case 24:
#if SDL_BYTEORDER == SDL_BIG_ENDIAN
            // SDL_PIXELFORMAT_RGB24
            Rmask = 0x000000FF;
            Gmask = 0x0000FF00;
            Bmask = 0x00FF0000;
#else
            // SDL_PIXELFORMAT_BGR24
            Rmask = 0x00FF0000;
            Gmask = 0x0000FF00;
            Bmask = 0x000000FF;
#endif
            break;
        case 32:
            // We don't know if this has alpha channel or not
            correctAlpha = true;
            // SDL_PIXELFORMAT_RGBA8888
            Amask = 0xFF000000;
            Rmask = 0x00FF0000;
            Gmask = 0x0000FF00;
            Bmask = 0x000000FF;
            break;
        default:
            break;
        }
        break;
    case BI_BITFIELDS:
        break; // we handled this in the info header.
    default:
        break;
    }
    // Create a compatible surface, note that the colors are RGB ordered
    {
        SDL_PixelFormat format;
        // Get the pixel format
        format = SDL_GetPixelFormatForMasks(biBitCount, Rmask, Gmask, Bmask, Amask);
        surface = SDL_CreateSurface(biWidth, biHeight, format);
        if (!surface) {
            goto done;
        }
    }
    // Load the palette, if any
    if (SDL_ISPIXELFORMAT_INDEXED(surface->format)) {
        SDL_Palette *palette = SDL_CreateSurfacePalette(surface);
        if (!palette) {
            goto done;
        }
        if (SDL_SeekIO(src, fp_offset + 14 + biSize, SDL_IO_SEEK_SET) < 0) {
            SDL_SetError("Error seeking in datastream");
            goto done;
        }
        if (biBitCount >= 32) { // we shift biClrUsed by this value later.
            SDL_SetError("Unsupported or incorrect biBitCount field");
            goto done;
        }
        if (biClrUsed == 0) {
            biClrUsed = 1 << biBitCount;
        }
        if (biClrUsed > (Uint32)palette->ncolors) {
            biClrUsed = 1 << biBitCount; // try forcing it?
            if (biClrUsed > (Uint32)palette->ncolors) {
                SDL_SetError("Unsupported or incorrect biClrUsed field");
                goto done;
            }
        }
        palette->ncolors = biClrUsed;
        if (biSize == 12) {
            for (i = 0; i < palette->ncolors; ++i) {
                if (!SDL_ReadU8(src, &palette->colors[i].b) ||
                    !SDL_ReadU8(src, &palette->colors[i].g) ||
                    !SDL_ReadU8(src, &palette->colors[i].r)) {
                    goto done;
                }
                palette->colors[i].a = SDL_ALPHA_OPAQUE;
            }
        } else {
            for (i = 0; i < palette->ncolors; ++i) {
                if (!SDL_ReadU8(src, &palette->colors[i].b) ||
                    !SDL_ReadU8(src, &palette->colors[i].g) ||
                    !SDL_ReadU8(src, &palette->colors[i].r) ||
                    !SDL_ReadU8(src, &palette->colors[i].a)) {
                    goto done;
                }
                /* According to Microsoft documentation, the fourth element
                   is reserved and must be zero, so we shouldn't treat it as
                   alpha.
                */
                palette->colors[i].a = SDL_ALPHA_OPAQUE;
            }
        }
    }
    // Read the surface pixels.  Note that the bmp image is upside down
    if (SDL_SeekIO(src, fp_offset + bfOffBits, SDL_IO_SEEK_SET) < 0) {
        SDL_SetError("Error seeking in datastream");
        goto done;
    }
    if ((biCompression == BI_RLE4) || (biCompression == BI_RLE8)) {
        if (!readRlePixels(surface, src, biCompression == BI_RLE8)) {
            SDL_SetError("Error reading from datastream");
            goto done;
        }
        // Success!
        was_error = false;
        goto done;
    }
    top = (Uint8 *)surface->pixels;
    end = (Uint8 *)surface->pixels + (surface->h * surface->pitch);
    pad = ((surface->pitch % 4) ? (4 - (surface->pitch % 4)) : 0);
    if (topDown) {
        bits = top;
    } else {
        bits = end - surface->pitch;
    }
    while (bits >= top && bits < end) {
        if (SDL_ReadIO(src, bits, surface->pitch) != (size_t)surface->pitch) {
            goto done;
        }
        if (biBitCount == 8 && surface->palette && biClrUsed < (1u << biBitCount)) {
            for (i = 0; i < surface->w; ++i) {
                if (bits[i] >= biClrUsed) {
                    SDL_SetError("A BMP image contains a pixel with a color out of the palette");
                    goto done;
                }
            }
        }
#if SDL_BYTEORDER == SDL_BIG_ENDIAN
        /* Byte-swap the pixels if needed. Note that the 24bpp
           case has already been taken care of above. */
        switch (biBitCount) {
        case 15:
        case 16:
        {
            Uint16 *pix = (Uint16 *)bits;
            for (i = 0; i < surface->w; i++) {
                pix[i] = SDL_Swap16(pix[i]);
            }
            break;
        }
        case 32:
        {
            Uint32 *pix = (Uint32 *)bits;
            for (i = 0; i < surface->w; i++) {
                pix[i] = SDL_Swap32(pix[i]);
            }
            break;
        }
        }
#endif
        // Skip padding bytes, ugh
        if (pad) {
            Uint8 padbyte;
            for (i = 0; i < pad; ++i) {
                if (!SDL_ReadU8(src, &padbyte)) {
                    goto done;
                }
            }
        }
        if (topDown) {
            bits += surface->pitch;
        } else {
            bits -= surface->pitch;
        }
    }
    if (correctAlpha) {
        CorrectAlphaChannel(surface);
    }
    was_error = false;
done:
    if (was_error) {
        if (src) {
            SDL_SeekIO(src, fp_offset, SDL_IO_SEEK_SET);
        }
        SDL_DestroySurface(surface);
        surface = NULL;
    }
    if (closeio && src) {
        SDL_CloseIO(src);
    }
    return surface;
}
References SDL_Color::a, SDL_Color::b, BI_BITFIELDS, BI_RGB, BI_RLE4, BI_RLE8, SDL_Palette::colors, CorrectAlphaChannel(), SDL_Color::g, SDL_Palette::ncolors, NULL, SDL_Color::r, readRlePixels(), SDL_ALPHA_OPAQUE, SDL_assert, SDL_ClearError(), SDL_CloseIO(), SDL_CreateSurface(), SDL_CreateSurfacePalette(), SDL_DestroySurface(), SDL_GetError(), SDL_GetPixelFormatForMasks(), SDL_InvalidParamError, SDL_IO_SEEK_CUR, SDL_IO_SEEK_SET, SDL_ISPIXELFORMAT_INDEXED, SDL_PRIs32, SDL_ReadIO(), SDL_ReadS32LE(), SDL_ReadU16LE(), SDL_ReadU32LE(), SDL_ReadU8(), SDL_SeekIO(), SDL_SetError(), SDL_strcmp(), SDL_strncmp(), SDL_Swap16(), SDL_Swap32(), SDL_TellIO(), and top.
Referenced by SDL_LoadBMP().
SDL_LockSurface()
SDL_DECLSPEC bool SDLCALL SDL_LockSurface (SDL_Surface * surface) extern
Set up a surface for directly accessing the pixels.
Between calls to SDL_LockSurface() / SDL_UnlockSurface(), you can write to and read from surface->pixels, using the pixel format stored in surface->format. Once you are done accessing the surface, you should use SDL_UnlockSurface() to release it.
Not all surfaces require locking. If SDL_MUSTLOCK(surface) evaluates to 0, then you can read and write to the surface at any time, and the pixel format of the surface will not change.
Parameters
surface the SDL_Surface structure to be locked.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe. The locking referred to by this function is making the pixels available for direct access, not thread-safe locking.
Since
This function is available since SDL 3.2.0.
See also
SDL_MUSTLOCK
SDL_UnlockSurface
{
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (!surface->locked) {
#ifdef SDL_HAVE_RLE
        // Perform the lock
        if (surface->internal_flags & SDL_INTERNAL_SURFACE_RLEACCEL) {
            SDL_UnRLESurface(surface, true);
            surface->internal_flags |= SDL_INTERNAL_SURFACE_RLEACCEL; // save accel'd state
        }
#endif
    }
    // Increment the surface lock count, for recursive locks
    ++surface->locked;
    surface->flags |= SDL_SURFACE_LOCKED;
    // Ready to go..
    return true;
}
References SDL_INTERNAL_SURFACE_RLEACCEL, SDL_InvalidParamError, SDL_SURFACE_LOCKED, SDL_SurfaceValid(), and SDL_UnRLESurface().
Referenced by SDL_ConvertColorkeyToAlpha(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_SaveBMP_IO(), SDL_SoftBlit(), SDL_StretchSurface(), SDL_UpdateTextureFromSurface(), SDL_WriteSurfacePixel(), and SDL_WriteSurfacePixelFloat().
SDL_MapSurfaceRGB()
SDL_DECLSPEC Uint32 SDLCALL SDL_MapSurfaceRGB (SDL_Surface * surface, Uint8 r, Uint8 g, Uint8 b) extern
Map an RGB triple to an opaque pixel value for a surface.
This function maps the RGB color value to the specified pixel format and returns the pixel value best approximating the given RGB color value for the given pixel format.
If the surface has a palette, the index of the closest matching color in the palette will be returned.
If the surface pixel format has an alpha component it will be returned as all 1 bits (fully opaque).
If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e.g., with a 16-bpp format the return value can be assigned to a Uint16, and similarly a Uint8 for an 8-bpp format).
Parameters
surface the surface to use for the pixel format and palette.
r the red component of the pixel in the range 0-255.
g the green component of the pixel in the range 0-255.
b the blue component of the pixel in the range 0-255.
Returns
a pixel value.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MapSurfaceRGBA
{
    return SDL_MapSurfaceRGBA(surface, r, g, b, SDL_ALPHA_OPAQUE);
}
References SDL_ALPHA_OPAQUE, and SDL_MapSurfaceRGBA().
SDL_MapSurfaceRGBA()
SDL_DECLSPEC Uint32 SDLCALL SDL_MapSurfaceRGBA (SDL_Surface * surface, Uint8 r, Uint8 g, Uint8 b, Uint8 a) extern
Map an RGBA quadruple to a pixel value for a surface.
This function maps the RGBA color value to the specified pixel format and returns the pixel value best approximating the given RGBA color value for the given pixel format.
If the surface pixel format has no alpha component the alpha value will be ignored (as it will be in formats with a palette).
If the surface has a palette, the index of the closest matching color in the palette will be returned.
If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e.g., with a 16-bpp format the return value can be assigned to a Uint16, and similarly a Uint8 for an 8-bpp format).
Parameters
surface the surface to use for the pixel format and palette.
r the red component of the pixel in the range 0-255.
g the green component of the pixel in the range 0-255.
b the blue component of the pixel in the range 0-255.
a the alpha component of the pixel in the range 0-255.
Returns
a pixel value.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MapSurfaceRGB
{
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        return true;
    }
    return SDL_MapRGBA(surface->fmt, surface->palette, r, g, b, a);
}
References SDL_InvalidParamError, SDL_MapRGBA(), and SDL_SurfaceValid().
Referenced by SDL_ClearSurface(), and SDL_MapSurfaceRGB().
SDL_PremultiplyAlpha()
SDL_DECLSPEC bool SDLCALL SDL_PremultiplyAlpha (int width, int height, SDL_PixelFormat src_format, const void * src, int src_pitch, SDL_PixelFormat dst_format, void * dst, int dst_pitch, bool linear) extern
Premultiply the alpha on a block of pixels.
This is safe to use with src == dst, but not for other overlapping areas.
Parameters
width the width of the block to convert, in pixels.
height the height of the block to convert, in pixels.
src_format an SDL_PixelFormat value of the src pixels format.
src a pointer to the source pixels.
src_pitch the pitch of the source pixels, in bytes.
dst_format an SDL_PixelFormat value of the dst pixels format.
dst a pointer to be filled in with premultiplied pixel data.
dst_pitch the pitch of the destination pixels, in bytes.
linear true to convert from sRGB to linear space for the alpha multiplication, false to do multiplication in sRGB space.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
The same destination pixels should not be used from two threads at once. It is safe to use the same source pixels from multiple threads.
Since
This function is available since SDL 3.2.0.
{
    SDL_Colorspace src_colorspace = SDL_GetDefaultColorspaceForFormat(src_format);
    SDL_Colorspace dst_colorspace = SDL_GetDefaultColorspaceForFormat(dst_format);
    return SDL_PremultiplyAlphaPixelsAndColorspace(width, height, src_format, src_colorspace, 0, src, src_pitch, dst_format, dst_colorspace, 0, dst, dst_pitch, linear);
}
References SDL_GetDefaultColorspaceForFormat(), and SDL_PremultiplyAlphaPixelsAndColorspace().
SDL_PremultiplySurfaceAlpha()
SDL_DECLSPEC bool SDLCALL SDL_PremultiplySurfaceAlpha (SDL_Surface * surface, bool linear) extern
Premultiply the alpha in a surface.
This is safe to use with src == dst, but not for other overlapping areas.
Parameters
surface the surface to modify.
linear true to convert from sRGB to linear space for the alpha multiplication, false to do multiplication in sRGB space.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    SDL_Colorspace colorspace;
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    colorspace = surface->colorspace;
    return SDL_PremultiplyAlphaPixelsAndColorspace(surface->w, surface->h, surface->format, colorspace, surface->props, surface->pixels, surface->pitch, surface->format, colorspace, surface->props, surface->pixels, surface->pitch, linear);
}
References SDL_InvalidParamError, SDL_PremultiplyAlphaPixelsAndColorspace(), and SDL_SurfaceValid().
SDL_ReadSurfacePixel()
SDL_DECLSPEC bool SDLCALL SDL_ReadSurfacePixel (SDL_Surface * surface, int x, int y, Uint8 * r, Uint8 * g, Uint8 * b, Uint8 * a) extern
Retrieves a single pixel from a surface.
This function prioritizes correctness over speed: it is suitable for unit tests, but is not intended for use in a game engine.
Like SDL_GetRGBA, this uses the entire 0..255 range when converting color components from pixel formats with less than 8 bits per RGB component.
Parameters
surface the surface to read.
x the horizontal coordinate, 0 <= x < width.
y the vertical coordinate, 0 <= y < height.
r a pointer filled in with the red channel, 0-255, or NULL to ignore this channel.
g a pointer filled in with the green channel, 0-255, or NULL to ignore this channel.
b a pointer filled in with the blue channel, 0-255, or NULL to ignore this channel.
a a pointer filled in with the alpha channel, 0-255, or NULL to ignore this channel.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint32 pixel = 0;
    size_t bytes_per_pixel;
    Uint8 unused;
    Uint8 *p;
    bool result = false;
    if (r) {
        *r = 0;
    } else {
        r = &unused;
    }
    if (g) {
        *g = 0;
    } else {
        g = &unused;
    }
    if (b) {
        *b = 0;
    } else {
        b = &unused;
    }
    if (a) {
        *a = 0;
    } else {
        a = &unused;
    }
    if (!SDL_SurfaceValid(surface) || !surface->format || !surface->pixels) {
        return SDL_InvalidParamError("surface");
    }
    if (x < 0 || x >= surface->w) {
        return SDL_InvalidParamError("x");
    }
    if (y < 0 || y >= surface->h) {
        return SDL_InvalidParamError("y");
    }
    bytes_per_pixel = SDL_BYTESPERPIXEL(surface->format);
    if (SDL_MUSTLOCK(surface)) {
        if (!SDL_LockSurface(surface)) {
            return false;
        }
    }
    p = (Uint8 *)surface->pixels + y * surface->pitch + x * bytes_per_pixel;
    if (bytes_per_pixel <= sizeof(pixel) && !SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        /* Fill the appropriate number of least-significant bytes of pixel,
         * leaving the most-significant bytes set to zero */
#if SDL_BYTEORDER == SDL_BIG_ENDIAN
        SDL_memcpy(((Uint8 *)&pixel) + (sizeof(pixel) - bytes_per_pixel), p, bytes_per_pixel);
#else
        SDL_memcpy(&pixel, p, bytes_per_pixel);
#endif
        SDL_GetRGBA(pixel, surface->fmt, surface->palette, r, g, b, a);
        result = true;
    } else if (SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        // FIXME: We need code to extract a single macroblock from a YUV surface
        SDL_Surface *converted = SDL_ConvertSurface(surface, SDL_PIXELFORMAT_ARGB8888);
        if (converted) {
            result = SDL_ReadSurfacePixel(converted, x, y, r, g, b, a);
            SDL_DestroySurface(converted);
        }
    } else {
        // This is really slow, but it gets the job done
        Uint8 rgba[4];
        if (SDL_ConvertPixelsAndColorspace(1, 1, surface->format, surface->colorspace, surface->props, p, surface->pitch, SDL_PIXELFORMAT_RGBA32, SDL_COLORSPACE_SRGB, 0, rgba, sizeof(rgba))) {
            *r = rgba[0];
            *g = rgba[1];
            *b = rgba[2];
            *a = rgba[3];
            result = true;
        }
    }
    if (SDL_MUSTLOCK(surface)) {
        SDL_UnlockSurface(surface);
    }
    return result;
}
References SDL_BYTESPERPIXEL, SDL_COLORSPACE_SRGB, SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurface(), SDL_DestroySurface(), SDL_GetRGBA(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_LockSurface(), SDL_memcpy, SDL_MUSTLOCK, SDL_PIXELFORMAT_ARGB8888, SDL_PIXELFORMAT_RGBA32, SDL_ReadSurfacePixel(), SDL_SurfaceValid(), and SDL_UnlockSurface().
Referenced by SDL_ReadSurfacePixel(), and SDL_ReadSurfacePixelFloat().
SDL_ReadSurfacePixelFloat()
SDL_DECLSPEC bool SDLCALL SDL_ReadSurfacePixelFloat (SDL_Surface * surface, int x, int y, float * r, float * g, float * b, float * a) extern
Retrieves a single pixel from a surface.
This function prioritizes correctness over speed: it is suitable for unit tests, but is not intended for use in a game engine.
Parameters
surface the surface to read.
x the horizontal coordinate, 0 <= x < width.
y the vertical coordinate, 0 <= y < height.
r a pointer filled in with the red channel, normally in the range 0-1, or NULL to ignore this channel.
g a pointer filled in with the green channel, normally in the range 0-1, or NULL to ignore this channel.
b a pointer filled in with the blue channel, normally in the range 0-1, or NULL to ignore this channel.
a a pointer filled in with the alpha channel, normally in the range 0-1, or NULL to ignore this channel.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    float unused;
    bool result = false;
    if (r) {
        *r = 0.0f;
    } else {
        r = &unused;
    }
    if (g) {
        *g = 0.0f;
    } else {
        g = &unused;
    }
    if (b) {
        *b = 0.0f;
    } else {
        b = &unused;
    }
    if (a) {
        *a = 0.0f;
    } else {
        a = &unused;
    }
    if (!SDL_SurfaceValid(surface) || !surface->format || !surface->pixels) {
        return SDL_InvalidParamError("surface");
    }
    if (x < 0 || x >= surface->w) {
        return SDL_InvalidParamError("x");
    }
    if (y < 0 || y >= surface->h) {
        return SDL_InvalidParamError("y");
    }
    if (SDL_BYTESPERPIXEL(surface->format) <= sizeof(Uint32) && !SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        Uint8 r8, g8, b8, a8;
        if (SDL_ReadSurfacePixel(surface, x, y, &r8, &g8, &b8, &a8)) {
            *r = (float)r8 / 255.0f;
            *g = (float)g8 / 255.0f;
            *b = (float)b8 / 255.0f;
            *a = (float)a8 / 255.0f;
            result = true;
        }
    } else if (SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        // FIXME: We need code to extract a single macroblock from a YUV surface
        SDL_Surface *converted = SDL_ConvertSurface(surface, SDL_PIXELFORMAT_ARGB8888);
        if (converted) {
            result = SDL_ReadSurfacePixelFloat(converted, x, y, r, g, b, a);
            SDL_DestroySurface(converted);
        }
    } else {
        // This is really slow, but it gets the job done
        float rgba[4];
        Uint8 *p;
        if (SDL_MUSTLOCK(surface)) {
            if (!SDL_LockSurface(surface)) {
                return false;
            }
        }
        p = (Uint8 *)surface->pixels + y * surface->pitch + x * SDL_BYTESPERPIXEL(surface->format);
        if (surface->format == SDL_PIXELFORMAT_RGBA128_FLOAT) {
            SDL_memcpy(rgba, p, sizeof(rgba));
            result = true;
        } else {
            SDL_Colorspace src_colorspace = surface->colorspace;
            SDL_Colorspace dst_colorspace = (src_colorspace == SDL_COLORSPACE_SRGB_LINEAR ? SDL_COLORSPACE_SRGB_LINEAR : SDL_COLORSPACE_SRGB);
            if (SDL_ConvertPixelsAndColorspace(1, 1, surface->format, src_colorspace, surface->props, p, surface->pitch, SDL_PIXELFORMAT_RGBA128_FLOAT, dst_colorspace, 0, rgba, sizeof(rgba))) {
                result = true;
            }
        }
        if (result) {
            *r = rgba[0];
            *g = rgba[1];
            *b = rgba[2];
            *a = rgba[3];
        }
        if (SDL_MUSTLOCK(surface)) {
            SDL_UnlockSurface(surface);
        }
    }
    return result;
}
References SDL_BYTESPERPIXEL, SDL_COLORSPACE_SRGB, SDL_COLORSPACE_SRGB_LINEAR, SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurface(), SDL_DestroySurface(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_LockSurface(), SDL_memcpy, SDL_MUSTLOCK, SDL_PIXELFORMAT_ARGB8888, SDL_PIXELFORMAT_RGBA128_FLOAT, SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_SurfaceValid(), and SDL_UnlockSurface().
Referenced by SDL_ReadSurfacePixelFloat().
SDL_RemoveSurfaceAlternateImages()
SDL_DECLSPEC void SDLCALL SDL_RemoveSurfaceAlternateImages (SDL_Surface * surface) extern
Remove all alternate versions of a surface.
This function removes a reference from all the alternative versions, destroying them if this is the last reference to them.
Parameters
surface the SDL_Surface structure to update.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddSurfaceAlternateImage
SDL_GetSurfaceImages
SDL_SurfaceHasAlternateImages
{
    if (!SDL_SurfaceValid(surface)) {
        return;
    }
    if (surface->num_images > 0) {
        for (int i = 0; i < surface->num_images; ++i) {
            SDL_DestroySurface(surface->images[i]);
        }
        SDL_free(surface->images);
        surface->images = NULL;
        surface->num_images = 0;
    }
}
References NULL, SDL_DestroySurface(), SDL_free(), and SDL_SurfaceValid().
Referenced by SDL_DestroySurface().
SDL_SaveBMP()
SDL_DECLSPEC bool SDLCALL SDL_SaveBMP (SDL_Surface * surface, const char * file) extern
Save a surface to a file.
Surfaces with a 24-bit, 32-bit and paletted 8-bit format get saved in the BMP directly. Other RGB formats with 8-bit or higher get converted to a 24-bit surface or, if they have an alpha mask or a colorkey, to a 32-bit surface before they are saved. YUV and paletted 1-bit and 4-bit formats are not supported.
Parameters
surface the SDL_Surface structure containing the image to be saved.
file a file to save to.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_LoadBMP
SDL_SaveBMP_IO
{
    SDL_IOStream *stream = SDL_IOFromFile(file, "wb");
    if (!stream) {
        return false;
    }
    return SDL_SaveBMP_IO(surface, stream, true);
}
References SDL_IOFromFile(), and SDL_SaveBMP_IO().
Referenced by SDL_CreateTray(), and SDL_SetTrayIcon().
SDL_SaveBMP_IO()
SDL_DECLSPEC bool SDLCALL SDL_SaveBMP_IO (SDL_Surface * surface, SDL_IOStream * dst, bool closeio) extern
Save a surface to a seekable SDL data stream in BMP format.
Surfaces with a 24-bit, 32-bit and paletted 8-bit format get saved in the BMP directly. Other RGB formats with 8-bit or higher get converted to a 24-bit surface or, if they have an alpha mask or a colorkey, to a 32-bit surface before they are saved. YUV and paletted 1-bit and 4-bit formats are not supported.
Parameters
surface the SDL_Surface structure containing the image to be saved.
dst a data stream to save to.
closeio if true, calls SDL_CloseIO() on dst before returning, even in the case of an error.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_LoadBMP_IO
SDL_SaveBMP
{
    bool was_error = true;
    Sint64 fp_offset, new_offset;
    int i, pad;
    SDL_Surface *intermediate_surface = NULL;
    Uint8 *bits;
    bool save32bit = false;
    bool saveLegacyBMP = false;
    // The Win32 BMP file header (14 bytes)
    char magic[2] = { 'B', 'M' };
    Uint32 bfSize;
    Uint16 bfReserved1;
    Uint16 bfReserved2;
    Uint32 bfOffBits;
    // The Win32 BITMAPINFOHEADER struct (40 bytes)
    Uint32 biSize;
    Sint32 biWidth;
    Sint32 biHeight;
    Uint16 biPlanes;
    Uint16 biBitCount;
    Uint32 biCompression;
    Uint32 biSizeImage;
    Sint32 biXPelsPerMeter;
    Sint32 biYPelsPerMeter;
    Uint32 biClrUsed;
    Uint32 biClrImportant;
    // The additional header members from the Win32 BITMAPV4HEADER struct (108 bytes in total)
    Uint32 bV4RedMask = 0;
    Uint32 bV4GreenMask = 0;
    Uint32 bV4BlueMask = 0;
    Uint32 bV4AlphaMask = 0;
    Uint32 bV4CSType = 0;
    Sint32 bV4Endpoints[3 * 3] = { 0 };
    Uint32 bV4GammaRed = 0;
    Uint32 bV4GammaGreen = 0;
    Uint32 bV4GammaBlue = 0;
    // The additional header members from the Win32 BITMAPV5HEADER struct (124 bytes in total)
    Uint32 bV5Intent = 0;
    Uint32 bV5ProfileData = 0;
    Uint32 bV5ProfileSize = 0;
    Uint32 bV5Reserved = 0;
    // Make sure we have somewhere to save
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        goto done;
    }
    if (!dst) {
        SDL_InvalidParamError("dst");
        goto done;
    }
#ifdef SAVE_32BIT_BMP
    // We can save alpha information in a 32-bit BMP
    if (SDL_BITSPERPIXEL(surface->format) >= 8 &&
        (SDL_ISPIXELFORMAT_ALPHA(surface->format) ||
         surface->map.info.flags & SDL_COPY_COLORKEY)) {
        save32bit = true;
    }
#endif // SAVE_32BIT_BMP
    if (surface->palette && !save32bit) {
        if (SDL_BITSPERPIXEL(surface->format) == 8) {
            intermediate_surface = surface;
        } else {
            SDL_SetError("%u bpp BMP files not supported",
                         SDL_BITSPERPIXEL(surface->format));
            goto done;
        }
    } else if ((surface->format == SDL_PIXELFORMAT_BGR24 && !save32bit) ||
               (surface->format == SDL_PIXELFORMAT_BGRA32 && save32bit)) {
        intermediate_surface = surface;
    } else {
        SDL_PixelFormat pixel_format;
        /* If the surface has a colorkey or alpha channel we'll save a
           32-bit BMP with alpha channel, otherwise save a 24-bit BMP. */
        if (save32bit) {
            pixel_format = SDL_PIXELFORMAT_BGRA32;
        } else {
            pixel_format = SDL_PIXELFORMAT_BGR24;
        }
        intermediate_surface = SDL_ConvertSurface(surface, pixel_format);
        if (!intermediate_surface) {
            SDL_SetError("Couldn't convert image to %d bpp",
                         (int)SDL_BITSPERPIXEL(pixel_format));
            goto done;
        }
    }
    if (save32bit) {
        saveLegacyBMP = SDL_GetHintBoolean(SDL_HINT_BMP_SAVE_LEGACY_FORMAT, false);
    }
    if (SDL_LockSurface(intermediate_surface)) {
        const size_t bw = intermediate_surface->w * intermediate_surface->fmt->bytes_per_pixel;
        // Set the BMP file header values
        bfSize = 0; // We'll write this when we're done
        bfReserved1 = 0;
        bfReserved2 = 0;
        bfOffBits = 0; // We'll write this when we're done
        // Write the BMP file header values
        fp_offset = SDL_TellIO(dst);
        if (fp_offset < 0) {
            goto done;
        }
        if (SDL_WriteIO(dst, magic, 2) != 2 ||
            !SDL_WriteU32LE(dst, bfSize) ||
            !SDL_WriteU16LE(dst, bfReserved1) ||
            !SDL_WriteU16LE(dst, bfReserved2) ||
            !SDL_WriteU32LE(dst, bfOffBits)) {
            goto done;
        }
        // Set the BMP info values
        biSize = 40;
        biWidth = intermediate_surface->w;
        biHeight = intermediate_surface->h;
        biPlanes = 1;
        biBitCount = intermediate_surface->fmt->bits_per_pixel;
        biCompression = BI_RGB;
        biSizeImage = intermediate_surface->h * intermediate_surface->pitch;
        biXPelsPerMeter = 0;
        biYPelsPerMeter = 0;
        if (intermediate_surface->palette) {
            biClrUsed = intermediate_surface->palette->ncolors;
        } else {
            biClrUsed = 0;
        }
        biClrImportant = 0;
        // Set the BMP info values
        if (save32bit && !saveLegacyBMP) {
            biSize = 124;
            // Version 4 values
            biCompression = BI_BITFIELDS;
            // The BMP format is always little endian, these masks stay the same
            bV4RedMask = 0x00ff0000;
            bV4GreenMask = 0x0000ff00;
            bV4BlueMask = 0x000000ff;
            bV4AlphaMask = 0xff000000;
            bV4CSType = LCS_sRGB;
            bV4GammaRed = 0;
            bV4GammaGreen = 0;
            bV4GammaBlue = 0;
            // Version 5 values
            bV5Intent = LCS_GM_GRAPHICS;
            bV5ProfileData = 0;
            bV5ProfileSize = 0;
            bV5Reserved = 0;
        }
        // Write the BMP info values
        if (!SDL_WriteU32LE(dst, biSize) ||
            !SDL_WriteS32LE(dst, biWidth) ||
            !SDL_WriteS32LE(dst, biHeight) ||
            !SDL_WriteU16LE(dst, biPlanes) ||
            !SDL_WriteU16LE(dst, biBitCount) ||
            !SDL_WriteU32LE(dst, biCompression) ||
            !SDL_WriteU32LE(dst, biSizeImage) ||
            !SDL_WriteU32LE(dst, biXPelsPerMeter) ||
            !SDL_WriteU32LE(dst, biYPelsPerMeter) ||
            !SDL_WriteU32LE(dst, biClrUsed) ||
            !SDL_WriteU32LE(dst, biClrImportant)) {
            goto done;
        }
        // Write the BMP info values
        if (save32bit && !saveLegacyBMP) {
            // Version 4 values
            if (!SDL_WriteU32LE(dst, bV4RedMask) ||
                !SDL_WriteU32LE(dst, bV4GreenMask) ||
                !SDL_WriteU32LE(dst, bV4BlueMask) ||
                !SDL_WriteU32LE(dst, bV4AlphaMask) ||
                !SDL_WriteU32LE(dst, bV4CSType)) {
                goto done;
            }
            for (i = 0; i < 3 * 3; i++) {
                if (!SDL_WriteU32LE(dst, bV4Endpoints[i])) {
                    goto done;
                }
            }
            if (!SDL_WriteU32LE(dst, bV4GammaRed) ||
                !SDL_WriteU32LE(dst, bV4GammaGreen) ||
                !SDL_WriteU32LE(dst, bV4GammaBlue)) {
                goto done;
            }
            // Version 5 values
            if (!SDL_WriteU32LE(dst, bV5Intent) ||
                !SDL_WriteU32LE(dst, bV5ProfileData) ||
                !SDL_WriteU32LE(dst, bV5ProfileSize) ||
                !SDL_WriteU32LE(dst, bV5Reserved)) {
                goto done;
            }
        }
        // Write the palette (in BGR color order)
        if (intermediate_surface->palette) {
            SDL_Color *colors;
            int ncolors;
            colors = intermediate_surface->palette->colors;
            ncolors = intermediate_surface->palette->ncolors;
            for (i = 0; i < ncolors; ++i) {
                if (!SDL_WriteU8(dst, colors[i].b) ||
                    !SDL_WriteU8(dst, colors[i].g) ||
                    !SDL_WriteU8(dst, colors[i].r) ||
                    !SDL_WriteU8(dst, colors[i].a)) {
                    goto done;
                }
            }
        }
        // Write the bitmap offset
        bfOffBits = (Uint32)(SDL_TellIO(dst) - fp_offset);
        if (SDL_SeekIO(dst, fp_offset + 10, SDL_IO_SEEK_SET) < 0) {
            goto done;
        }
        if (!SDL_WriteU32LE(dst, bfOffBits)) {
            goto done;
        }
        if (SDL_SeekIO(dst, fp_offset + bfOffBits, SDL_IO_SEEK_SET) < 0) {
            goto done;
        }
        // Write the bitmap image upside down
        bits = (Uint8 *)intermediate_surface->pixels + (intermediate_surface->h * intermediate_surface->pitch);
        pad = ((bw % 4) ? (4 - (bw % 4)) : 0);
        while (bits > (Uint8 *)intermediate_surface->pixels) {
            bits -= intermediate_surface->pitch;
            if (SDL_WriteIO(dst, bits, bw) != bw) {
                goto done;
            }
            if (pad) {
                const Uint8 padbyte = 0;
                for (i = 0; i < pad; ++i) {
                    if (!SDL_WriteU8(dst, padbyte)) {
                        goto done;
                    }
                }
            }
        }
        // Write the BMP file size
        new_offset = SDL_TellIO(dst);
        if (new_offset < 0) {
            goto done;
        }
        bfSize = (Uint32)(new_offset - fp_offset);
        if (SDL_SeekIO(dst, fp_offset + 2, SDL_IO_SEEK_SET) < 0) {
            goto done;
        }
        if (!SDL_WriteU32LE(dst, bfSize)) {
            goto done;
        }
        if (SDL_SeekIO(dst, fp_offset + bfSize, SDL_IO_SEEK_SET) < 0) {
            goto done;
        }
        // Close it up..
        SDL_UnlockSurface(intermediate_surface);
        was_error = false;
    }
done:
    if (intermediate_surface && intermediate_surface != surface) {
        SDL_DestroySurface(intermediate_surface);
    }
    if (closeio && dst) {
        if (!SDL_CloseIO(dst)) {
            was_error = true;
        }
    }
    if (was_error) {
        return false;
    }
    return true;
}
References BI_BITFIELDS, BI_RGB, SDL_PixelFormatDetails::bits_per_pixel, SDL_PixelFormatDetails::bytes_per_pixel, SDL_Palette::colors, SDL_Surface::fmt, SDL_Surface::h, LCS_GM_GRAPHICS, LCS_sRGB, SDL_Palette::ncolors, NULL, SDL_Surface::palette, SDL_Surface::pitch, SDL_Surface::pixels, SDL_BITSPERPIXEL, SDL_CloseIO(), SDL_ConvertSurface(), SDL_COPY_COLORKEY, SDL_DestroySurface(), SDL_GetHintBoolean(), SDL_HINT_BMP_SAVE_LEGACY_FORMAT, SDL_InvalidParamError, SDL_IO_SEEK_SET, SDL_ISPIXELFORMAT_ALPHA, SDL_LockSurface(), SDL_PIXELFORMAT_BGR24, SDL_PIXELFORMAT_BGRA32, SDL_SeekIO(), SDL_SetError(), SDL_SurfaceValid(), SDL_TellIO(), SDL_UnlockSurface(), SDL_WriteIO(), SDL_WriteS32LE(), SDL_WriteU16LE(), SDL_WriteU32LE(), SDL_WriteU8(), and SDL_Surface::w.
Referenced by SDL_SaveBMP().
SDL_ScaleSurface()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_ScaleSurface (SDL_Surface * surface, int width, int height, SDL_ScaleMode scaleMode) extern
Creates a new surface identical to the existing surface, scaled to the desired size.
The returned surface should be freed with SDL_DestroySurface().
Parameters
surface the surface to duplicate and scale.
width the width of the new surface.
height the height of the new surface.
scaleMode the SDL_ScaleMode to be used.
Returns
a copy of the surface or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroySurface
{
    SDL_Surface *convert = NULL;
    Uint32 copy_flags;
    SDL_Color copy_color;
    bool rc;
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        goto error;
    }
    if (SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        // We can't directly scale a YUV surface (yet!)
        SDL_Surface *tmp = SDL_CreateSurface(surface->w, surface->h, SDL_PIXELFORMAT_ARGB8888);
        if (!tmp) {
            return NULL;
        }
        SDL_Surface *scaled = SDL_ScaleSurface(tmp, width, height, scaleMode);
        SDL_DestroySurface(tmp);
        if (!scaled) {
            return NULL;
        }
        tmp = scaled;
        SDL_Surface *result = SDL_ConvertSurfaceAndColorspace(tmp, surface->format, NULL, surface->colorspace, surface->props);
        SDL_DestroySurface(tmp);
        return result;
    }
    // Create a new surface with the desired size
    convert = SDL_CreateSurface(width, height, surface->format);
    if (!convert) {
        goto error;
    }
    SDL_SetSurfacePalette(convert, surface->palette);
    SDL_SetSurfaceColorspace(convert, surface->colorspace);
    // Save the original copy flags
    copy_flags = surface->map.info.flags;
    copy_color.r = surface->map.info.r;
    copy_color.g = surface->map.info.g;
    copy_color.b = surface->map.info.b;
    copy_color.a = surface->map.info.a;
    surface->map.info.r = 0xFF;
    surface->map.info.g = 0xFF;
    surface->map.info.b = 0xFF;
    surface->map.info.a = 0xFF;
    surface->map.info.flags = (copy_flags & (SDL_COPY_RLE_COLORKEY | SDL_COPY_RLE_ALPHAKEY));
    SDL_InvalidateMap(&surface->map);
    rc = SDL_BlitSurfaceScaled(surface, NULL, convert, NULL, scaleMode);
    // Clean up the original surface, and update converted surface
    convert->map.info.r = copy_color.r;
    convert->map.info.g = copy_color.g;
    convert->map.info.b = copy_color.b;
    convert->map.info.a = copy_color.a;
    convert->map.info.flags = (copy_flags & ~(SDL_COPY_RLE_COLORKEY | SDL_COPY_RLE_ALPHAKEY));
    surface->map.info.r = copy_color.r;
    surface->map.info.g = copy_color.g;
    surface->map.info.b = copy_color.b;
    surface->map.info.a = copy_color.a;
    surface->map.info.flags = copy_flags;
    SDL_InvalidateMap(&surface->map);
    // SDL_BlitSurfaceScaled failed, and so the conversion
    if (!rc) {
        goto error;
    }
    // We're ready to go!
    return convert;
error:
    if (convert) {
        SDL_DestroySurface(convert);
    }
    return NULL;
}
References SDL_BlitInfo::a, SDL_Color::a, SDL_BlitInfo::b, SDL_Color::b, SDL_BlitInfo::flags, SDL_BlitInfo::g, SDL_Color::g, SDL_BlitMap::info, SDL_Surface::map, NULL, SDL_BlitInfo::r, SDL_Color::r, SDL_BlitSurfaceScaled(), SDL_ConvertSurfaceAndColorspace(), SDL_COPY_RLE_ALPHAKEY, SDL_COPY_RLE_COLORKEY, SDL_CreateSurface(), SDL_DestroySurface(), SDL_InvalidateMap(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_PIXELFORMAT_ARGB8888, SDL_ScaleSurface(), SDL_SetSurfaceColorspace(), SDL_SetSurfacePalette(), and SDL_SurfaceValid().
Referenced by SDL_GetSurfaceImage(), and SDL_ScaleSurface().
SDL_SetSurfaceAlphaMod()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceAlphaMod (SDL_Surface * surface, Uint8 alpha) extern
Set an additional alpha value used in blit operations.
When this surface is blitted, during the blit operation the source alpha value is modulated by this alpha value according to the following formula:
srcA = srcA * (alpha / 255)
Parameters
surface the SDL_Surface structure to update.
alpha the alpha value multiplied into blit operations.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceAlphaMod
SDL_SetSurfaceColorMod
{
    int flags;
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    surface->map.info.a = alpha;
    flags = surface->map.info.flags;
    if (alpha != 0xFF) {
        surface->map.info.flags |= SDL_COPY_MODULATE_ALPHA;
    } else {
        surface->map.info.flags &= ~SDL_COPY_MODULATE_ALPHA;
    }
    if (surface->map.info.flags != flags) {
        SDL_InvalidateMap(&surface->map);
    }
    return true;
}
References SDL_COPY_MODULATE_ALPHA, SDL_InvalidateMap(), SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_BlitSurfaceUncheckedScaled().
SDL_SetSurfaceBlendMode()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceBlendMode (SDL_Surface * surface, SDL_BlendMode blendMode) extern
Set the blend mode used for blit operations.
To copy a surface to another surface (or texture) without blending with the existing data, the blendmode of the SOURCE surface should be set to SDL_BLENDMODE_NONE.
Parameters
surface the SDL_Surface structure to update.
blendMode the SDL_BlendMode to use for blit blending.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceBlendMode
{
    int flags;
    bool result = true;
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (blendMode == SDL_BLENDMODE_INVALID) {
        return SDL_InvalidParamError("blendMode");
    }
    flags = surface->map.info.flags;
    surface->map.info.flags &= ~SDL_COPY_BLEND_MASK;
    switch (blendMode) {
    case SDL_BLENDMODE_NONE:
        break;
    case SDL_BLENDMODE_BLEND:
        surface->map.info.flags |= SDL_COPY_BLEND;
        break;
    case SDL_BLENDMODE_BLEND_PREMULTIPLIED:
        surface->map.info.flags |= SDL_COPY_BLEND_PREMULTIPLIED;
        break;
    case SDL_BLENDMODE_ADD:
        surface->map.info.flags |= SDL_COPY_ADD;
        break;
    case SDL_BLENDMODE_ADD_PREMULTIPLIED:
        surface->map.info.flags |= SDL_COPY_ADD_PREMULTIPLIED;
        break;
    case SDL_BLENDMODE_MOD:
        surface->map.info.flags |= SDL_COPY_MOD;
        break;
    case SDL_BLENDMODE_MUL:
        surface->map.info.flags |= SDL_COPY_MUL;
        break;
    default:
        result = SDL_Unsupported();
        break;
    }
    if (surface->map.info.flags != flags) {
        SDL_InvalidateMap(&surface->map);
    }
    return result;
}
References SDL_BLENDMODE_ADD, SDL_BLENDMODE_ADD_PREMULTIPLIED, SDL_BLENDMODE_BLEND, SDL_BLENDMODE_BLEND_PREMULTIPLIED, SDL_BLENDMODE_INVALID, SDL_BLENDMODE_MOD, SDL_BLENDMODE_MUL, SDL_BLENDMODE_NONE, SDL_COPY_ADD, SDL_COPY_ADD_PREMULTIPLIED, SDL_COPY_BLEND, SDL_COPY_BLEND_MASK, SDL_COPY_BLEND_PREMULTIPLIED, SDL_COPY_MOD, SDL_COPY_MUL, SDL_InvalidateMap(), SDL_InvalidParamError, SDL_SurfaceValid(), and SDL_Unsupported.
Referenced by SDL_BlitSurfaceUncheckedScaled(), SDL_ClearSurface(), SDL_ConvertColorkeyToAlpha(), SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurfaceAndColorspace(), and SDL_InitializeSurface().
SDL_SetSurfaceClipRect()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceClipRect (SDL_Surface * surface, const SDL_Rect * rect) extern
Set the clipping rectangle for a surface.
When surface is the destination of a blit, only the area within the clip rectangle is drawn into.
Note that blits are automatically clipped to the edges of the source and destination surfaces.
Parameters
surface the SDL_Surface structure to be clipped.
rect the SDL_Rect structure representing the clipping rectangle, or NULL to disable clipping.
Returns
true if the rectangle intersects the surface, otherwise false and blits will be completely clipped.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceClipRect
{
    SDL_Rect full_rect;
    // Don't do anything if there's no surface to act on
    if (!SDL_SurfaceValid(surface)) {
        return false;
    }
    // Set up the full surface rectangle
    full_rect.x = 0;
    full_rect.y = 0;
    full_rect.w = surface->w;
    full_rect.h = surface->h;
    // Set the clipping rectangle
    if (!rect) {
        surface->clip_rect = full_rect;
        return true;
    }
    return SDL_GetRectIntersection(rect, &full_rect, &surface->clip_rect);
}
References SDL_Rect::h, SDL_GetRectIntersection(), SDL_SurfaceValid(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_ClearSurface(), and SDL_ConvertSurfaceAndColorspace().
SDL_SetSurfaceColorKey()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceColorKey (SDL_Surface * surface, bool enabled, Uint32 key) extern
Set the color key (transparent pixel) in a surface.
The color key defines a pixel value that will be treated as transparent in a blit. For example, one can use this to specify that cyan pixels should be considered transparent, and therefore not rendered.
It is a pixel of the format used by the surface, as generated by SDL_MapRGB().
Parameters
surface the SDL_Surface structure to update.
enabled true to enable color key, false to disable color key.
key the transparent pixel.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceColorKey
SDL_SetSurfaceRLE
SDL_SurfaceHasColorKey
{
    int flags;
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (surface->palette && key >= ((Uint32)surface->palette->ncolors)) {
        return SDL_InvalidParamError("key");
    }
    flags = surface->map.info.flags;
    if (enabled) {
        surface->map.info.flags |= SDL_COPY_COLORKEY;
        surface->map.info.colorkey = key;
    } else {
        surface->map.info.flags &= ~SDL_COPY_COLORKEY;
    }
    if (surface->map.info.flags != flags) {
        SDL_InvalidateMap(&surface->map);
    }
    return true;
}
References SDL_COPY_COLORKEY, SDL_InvalidateMap(), SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_ConvertColorkeyToAlpha(), and SDL_ConvertSurfaceAndColorspace().
SDL_SetSurfaceColorMod()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceColorMod (SDL_Surface * surface, Uint8 r, Uint8 g, Uint8 b) extern
Set an additional color value multiplied into blit operations.
When this surface is blitted, during the blit operation each source color channel is modulated by the appropriate color value according to the following formula:
srcC = srcC * (color / 255)
Parameters
surface the SDL_Surface structure to update.
r the red color value multiplied into blit operations.
g the green color value multiplied into blit operations.
b the blue color value multiplied into blit operations.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceColorMod
SDL_SetSurfaceAlphaMod
{
    int flags;
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    surface->map.info.r = r;
    surface->map.info.g = g;
    surface->map.info.b = b;
    flags = surface->map.info.flags;
    if (r != 0xFF || g != 0xFF || b != 0xFF) {
        surface->map.info.flags |= SDL_COPY_MODULATE_COLOR;
    } else {
        surface->map.info.flags &= ~SDL_COPY_MODULATE_COLOR;
    }
    if (surface->map.info.flags != flags) {
        SDL_InvalidateMap(&surface->map);
    }
    return true;
}
References SDL_COPY_MODULATE_COLOR, SDL_InvalidateMap(), SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_BlitSurfaceUncheckedScaled().
SDL_SetSurfaceColorspace()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceColorspace (SDL_Surface * surface, SDL_Colorspace colorspace) extern
Set the colorspace used by a surface.
Setting the colorspace doesn't change the pixels, only how they are interpreted in color operations.
Parameters
surface the SDL_Surface structure to update.
colorspace an SDL_Colorspace value describing the surface colorspace.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetSurfaceColorspace
{
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    surface->colorspace = colorspace;
    return true;
}
References SDL_InvalidParamError, and SDL_SurfaceValid().
Referenced by SDL_ClearSurface(), SDL_ConvertSurfaceAndColorspace(), SDL_DuplicatePixels(), SDL_PrepareCameraSurfaces(), and SDL_ScaleSurface().
SDL_SetSurfacePalette()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfacePalette (SDL_Surface * surface, SDL_Palette * palette) extern
Set the palette used by a surface.
A single palette can be shared with many surfaces.
Parameters
surface the SDL_Surface structure to update.
palette the SDL_Palette structure to use.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreatePalette
SDL_GetSurfacePalette
{
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    if (palette && palette->ncolors > (1 << SDL_BITSPERPIXEL(surface->format))) {
        return SDL_SetError("SDL_SetSurfacePalette() passed a palette that doesn't match the surface format");
    }
    if (palette != surface->palette) {
        if (surface->palette) {
            SDL_DestroyPalette(surface->palette);
        }
        surface->palette = palette;
        if (surface->palette) {
            ++surface->palette->refcount;
        }
    }
    SDL_InvalidateMap(&surface->map);
    return true;
}
References SDL_Palette::ncolors, SDL_BITSPERPIXEL, SDL_DestroyPalette(), SDL_InvalidateMap(), SDL_InvalidParamError, SDL_SetError(), and SDL_SurfaceValid().
Referenced by SDL_ConvertSurfaceAndColorspace(), SDL_CreateSurfacePalette(), SDL_DestroySurface(), and SDL_ScaleSurface().
SDL_SetSurfaceRLE()
SDL_DECLSPEC bool SDLCALL SDL_SetSurfaceRLE (SDL_Surface * surface, bool enabled) extern
Set the RLE acceleration hint for a surface.
If RLE is enabled, color key and alpha blending blits are much faster, but the surface must be locked before directly accessing the pixels.
Parameters
surface the SDL_Surface structure to optimize.
enabled true to enable RLE acceleration, false to disable it.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_BlitSurface
SDL_LockSurface
SDL_UnlockSurface
{
    int flags;
    if (!SDL_SurfaceValid(surface)) {
        return SDL_InvalidParamError("surface");
    }
    flags = surface->map.info.flags;
    if (enabled) {
        surface->map.info.flags |= SDL_COPY_RLE_DESIRED;
    } else {
        surface->map.info.flags &= ~SDL_COPY_RLE_DESIRED;
    }
    if (surface->map.info.flags != flags) {
        SDL_InvalidateMap(&surface->map);
    }
    SDL_UpdateSurfaceLockFlag(surface);
    return true;
}
References SDL_COPY_RLE_DESIRED, SDL_InvalidateMap(), SDL_InvalidParamError, SDL_SurfaceValid(), and SDL_UpdateSurfaceLockFlag().
Referenced by SDL_ConvertSurfaceAndColorspace().
SDL_StretchSurface()
SDL_DECLSPEC bool SDLCALL SDL_StretchSurface (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect, SDL_ScaleMode scaleMode) extern
Perform a stretched pixel copy from one surface to another.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, or NULL to copy the entire surface.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, or NULL to fill the entire destination surface.
scaleMode the SDL_ScaleMode to be used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.4.0.
See also
SDL_BlitSurfaceScaled
{
    bool result;
    int src_locked;
    int dst_locked;
    SDL_Rect full_src;
    SDL_Rect full_dst;
    if (!src) {
        return SDL_InvalidParamError("src");
    }
    if (!dst) {
        return SDL_InvalidParamError("dst");
    }
    if (src->format != dst->format) {
        // Slow!
        SDL_Surface *src_tmp = SDL_ConvertSurfaceAndColorspace(src, dst->format, dst->palette, dst->colorspace, dst->props);
        if (!src_tmp) {
            return false;
        }
        result = SDL_StretchSurface(src_tmp, srcrect, dst, dstrect, scaleMode);
        SDL_DestroySurface(src_tmp);
        return result;
    }
    if (SDL_ISPIXELFORMAT_FOURCC(src->format)) {
        // Slow!
        if (!dstrect) {
            full_dst.x = 0;
            full_dst.y = 0;
            full_dst.w = dst->w;
            full_dst.h = dst->h;
            dstrect = &full_dst;
        }
        SDL_Surface *src_tmp = SDL_ConvertSurface(src, SDL_PIXELFORMAT_XRGB8888);
        SDL_Surface *dst_tmp = SDL_CreateSurface(dstrect->w, dstrect->h, SDL_PIXELFORMAT_XRGB8888);
        if (src_tmp && dst_tmp) {
            result = SDL_StretchSurface(src_tmp, srcrect, dst_tmp, NULL, scaleMode);
            if (result) {
                result = SDL_ConvertPixelsAndColorspace(dstrect->w, dstrect->h,
                            dst_tmp->format, SDL_COLORSPACE_SRGB, 0,
                            dst_tmp->pixels, dst_tmp->pitch,
                            dst->format, dst->colorspace, SDL_GetSurfaceProperties(dst),
                            (Uint8 *)dst->pixels + dstrect->y * dst->pitch + dstrect->x * SDL_BYTESPERPIXEL(dst->format), dst->pitch);
            }
        } else {
            result = false;
        }
        SDL_DestroySurface(src_tmp);
        SDL_DestroySurface(dst_tmp);
        return result;
    }
    switch (scaleMode) {
    case SDL_SCALEMODE_NEAREST:
        break;
    case SDL_SCALEMODE_LINEAR:
        break;
    case SDL_SCALEMODE_PIXELART:
        scaleMode = SDL_SCALEMODE_NEAREST;
        break;
    default:
        return SDL_InvalidParamError("scaleMode");
    }
    if (scaleMode == SDL_SCALEMODE_LINEAR) {
        if (SDL_BYTESPERPIXEL(src->format) != 4 || src->format == SDL_PIXELFORMAT_ARGB2101010) {
            return SDL_SetError("Wrong format");
        }
    }
    // Verify the blit rectangles
    if (srcrect) {
        if ((srcrect->x < 0) || (srcrect->y < 0) ||
            ((srcrect->x + srcrect->w) > src->w) ||
            ((srcrect->y + srcrect->h) > src->h)) {
            return SDL_SetError("Invalid source blit rectangle");
        }
    } else {
        full_src.x = 0;
        full_src.y = 0;
        full_src.w = src->w;
        full_src.h = src->h;
        srcrect = &full_src;
    }
    if (dstrect) {
        if ((dstrect->x < 0) || (dstrect->y < 0) ||
            ((dstrect->x + dstrect->w) > dst->w) ||
            ((dstrect->y + dstrect->h) > dst->h)) {
            return SDL_SetError("Invalid destination blit rectangle");
        }
    } else {
        full_dst.x = 0;
        full_dst.y = 0;
        full_dst.w = dst->w;
        full_dst.h = dst->h;
        dstrect = &full_dst;
    }
    if (dstrect->w <= 0 || dstrect->h <= 0) {
        return true;
    }
    if (srcrect->w > SDL_MAX_UINT16 || srcrect->h > SDL_MAX_UINT16 ||
        dstrect->w > SDL_MAX_UINT16 || dstrect->h > SDL_MAX_UINT16) {
        return SDL_SetError("Size too large for scaling");
    }
    // Lock the destination if it's in hardware
    dst_locked = 0;
    if (SDL_MUSTLOCK(dst)) {
        if (!SDL_LockSurface(dst)) {
            return SDL_SetError("Unable to lock destination surface");
        }
        dst_locked = 1;
    }
    // Lock the source if it's in hardware
    src_locked = 0;
    if (SDL_MUSTLOCK(src)) {
        if (!SDL_LockSurface(src)) {
            if (dst_locked) {
                SDL_UnlockSurface(dst);
            }
            return SDL_SetError("Unable to lock source surface");
        }
        src_locked = 1;
    }
    if (scaleMode == SDL_SCALEMODE_NEAREST) {
        result = SDL_StretchSurfaceUncheckedNearest(src, srcrect, dst, dstrect);
    } else {
        result = SDL_StretchSurfaceUncheckedLinear(src, srcrect, dst, dstrect);
    }
    // We need to unlock the surfaces if they're locked
    if (dst_locked) {
        SDL_UnlockSurface(dst);
    }
    if (src_locked) {
        SDL_UnlockSurface(src);
    }
    return result;
}
References SDL_Surface::colorspace, SDL_Surface::format, SDL_Rect::h, SDL_Surface::h, NULL, SDL_Surface::palette, SDL_Surface::pitch, SDL_Surface::pixels, SDL_Surface::props, SDL_BYTESPERPIXEL, SDL_COLORSPACE_SRGB, SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurface(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateSurface(), SDL_DestroySurface(), SDL_GetSurfaceProperties(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_LockSurface(), SDL_MAX_UINT16, SDL_MUSTLOCK, SDL_PIXELFORMAT_ARGB2101010, SDL_PIXELFORMAT_XRGB8888, SDL_SCALEMODE_LINEAR, SDL_SCALEMODE_NEAREST, SDL_SCALEMODE_PIXELART, SDL_SetError(), SDL_StretchSurface(), SDL_StretchSurfaceUncheckedLinear(), SDL_StretchSurfaceUncheckedNearest(), SDL_UnlockSurface(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_BlitSurfaceUncheckedScaled(), SDL_CameraThreadIterate(), and SDL_StretchSurface().
SDL_SurfaceHasAlternateImages()
SDL_DECLSPEC bool SDLCALL SDL_SurfaceHasAlternateImages (SDL_Surface * surface) extern
Return whether a surface has alternate versions available.
Parameters
surface the SDL_Surface structure to query.
Returns
true if alternate versions are available or false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddSurfaceAlternateImage
SDL_RemoveSurfaceAlternateImages
SDL_GetSurfaceImages
{
    if (!SDL_SurfaceValid(surface)) {
        return false;
    }
    return (surface->num_images > 0);
}
References SDL_SurfaceValid().
Referenced by SDL_GetSurfaceImage().
SDL_SurfaceHasColorKey()
SDL_DECLSPEC bool SDLCALL SDL_SurfaceHasColorKey (SDL_Surface * surface) extern
Returns whether the surface has a color key.
It is safe to pass a NULL surface here; it will return false.
Parameters
surface the SDL_Surface structure to query.
Returns
true if the surface has a color key, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetSurfaceColorKey
SDL_GetSurfaceColorKey
{
    if (!SDL_SurfaceValid(surface)) {
        return false;
    }
    if (!(surface->map.info.flags & SDL_COPY_COLORKEY)) {
        return false;
    }
    return true;
}
References SDL_COPY_COLORKEY, and SDL_SurfaceValid().
Referenced by SDL_CreateTextureFromSurface(), and SDL_UpdateTextureFromSurface().
SDL_SurfaceHasRLE()
SDL_DECLSPEC bool SDLCALL SDL_SurfaceHasRLE (SDL_Surface * surface) extern
Returns whether the surface is RLE enabled.
It is safe to pass a NULL surface here; it will return false.
Parameters
surface the SDL_Surface structure to query.
Returns
true if the surface is RLE enabled, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetSurfaceRLE
{
    if (!SDL_SurfaceValid(surface)) {
        return false;
    }
    if (!(surface->map.info.flags & SDL_COPY_RLE_DESIRED)) {
        return false;
    }
    return true;
}
References SDL_COPY_RLE_DESIRED, and SDL_SurfaceValid().
Referenced by SDL_UpdateSurfaceLockFlag().
SDL_UnlockSurface()
SDL_DECLSPEC void SDLCALL SDL_UnlockSurface (SDL_Surface * surface) extern
Release a surface after directly accessing the pixels.
Parameters
surface the SDL_Surface structure to be unlocked.
Thread Safety
This function is not thread safe. The locking referred to by this function is making the pixels available for direct access, not thread-safe locking.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockSurface
{
    if (!SDL_SurfaceValid(surface)) {
        return;
    }
    // Only perform an unlock if we are locked
    if (!surface->locked || (--surface->locked > 0)) {
        return;
    }
#ifdef SDL_HAVE_RLE
    // Update RLE encoded surface with new data
    if (surface->internal_flags & SDL_INTERNAL_SURFACE_RLEACCEL) {
        surface->internal_flags &= ~SDL_INTERNAL_SURFACE_RLEACCEL; // stop lying
        SDL_RLESurface(surface);
    }
#endif
    surface->flags &= ~SDL_SURFACE_LOCKED;
}
References SDL_INTERNAL_SURFACE_RLEACCEL, SDL_RLESurface(), SDL_SURFACE_LOCKED, and SDL_SurfaceValid().
Referenced by SDL_ConvertColorkeyToAlpha(), SDL_DestroySurface(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_SaveBMP_IO(), SDL_SoftBlit(), SDL_StretchSurface(), SDL_UpdateTextureFromSurface(), SDL_WriteSurfacePixel(), and SDL_WriteSurfacePixelFloat().
SDL_WriteSurfacePixel()
SDL_DECLSPEC bool SDLCALL SDL_WriteSurfacePixel (SDL_Surface * surface, int x, int y, Uint8 r, Uint8 g, Uint8 b, Uint8 a) extern
Writes a single pixel to a surface.
This function prioritizes correctness over speed: it is suitable for unit tests, but is not intended for use in a game engine.
Like SDL_MapRGBA, this uses the entire 0..255 range when converting color components from pixel formats with less than 8 bits per RGB component.
Parameters
surface the surface to write.
x the horizontal coordinate, 0 <= x < width.
y the vertical coordinate, 0 <= y < height.
r the red channel value, 0-255.
g the green channel value, 0-255.
b the blue channel value, 0-255.
a the alpha channel value, 0-255.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint32 pixel = 0;
    size_t bytes_per_pixel;
    Uint8 *p;
    bool result = false;
    if (!SDL_SurfaceValid(surface) || !surface->format || !surface->pixels) {
        return SDL_InvalidParamError("surface");
    }
    if (x < 0 || x >= surface->w) {
        return SDL_InvalidParamError("x");
    }
    if (y < 0 || y >= surface->h) {
        return SDL_InvalidParamError("y");
    }
    bytes_per_pixel = SDL_BYTESPERPIXEL(surface->format);
    if (SDL_MUSTLOCK(surface)) {
        if (!SDL_LockSurface(surface)) {
            return false;
        }
    }
    p = (Uint8 *)surface->pixels + y * surface->pitch + x * bytes_per_pixel;
    if (bytes_per_pixel <= sizeof(pixel) && !SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        pixel = SDL_MapRGBA(surface->fmt, surface->palette, r, g, b, a);
#if SDL_BYTEORDER == SDL_BIG_ENDIAN
        SDL_memcpy(p, ((Uint8 *)&pixel) + (sizeof(pixel) - bytes_per_pixel), bytes_per_pixel);
#else
        SDL_memcpy(p, &pixel, bytes_per_pixel);
#endif
        result = true;
    } else if (SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        result = SDL_Unsupported();
    } else {
        // This is really slow, but it gets the job done
        Uint8 rgba[4];
        rgba[0] = r;
        rgba[1] = g;
        rgba[2] = b;
        rgba[3] = a;
        result = SDL_ConvertPixelsAndColorspace(1, 1, SDL_PIXELFORMAT_RGBA32, SDL_COLORSPACE_SRGB, 0, rgba, sizeof(rgba), surface->format, surface->colorspace, surface->props, p, surface->pitch);
    }
    if (SDL_MUSTLOCK(surface)) {
        SDL_UnlockSurface(surface);
    }
    return result;
}
References SDL_BYTESPERPIXEL, SDL_COLORSPACE_SRGB, SDL_ConvertPixelsAndColorspace(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_LockSurface(), SDL_MapRGBA(), SDL_memcpy, SDL_MUSTLOCK, SDL_PIXELFORMAT_RGBA32, SDL_SurfaceValid(), SDL_UnlockSurface(), and SDL_Unsupported.
Referenced by SDL_WriteSurfacePixelFloat().
SDL_WriteSurfacePixelFloat()
SDL_DECLSPEC bool SDLCALL SDL_WriteSurfacePixelFloat (SDL_Surface * surface, int x, int y, float r, float g, float b, float a) extern
Writes a single pixel to a surface.
This function prioritizes correctness over speed: it is suitable for unit tests, but is not intended for use in a game engine.
Parameters
surface the surface to write.
x the horizontal coordinate, 0 <= x < width.
y the vertical coordinate, 0 <= y < height.
r the red channel value, normally in the range 0-1.
g the green channel value, normally in the range 0-1.
b the blue channel value, normally in the range 0-1.
a the alpha channel value, normally in the range 0-1.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    bool result = false;
    if (!SDL_SurfaceValid(surface) || !surface->format || !surface->pixels) {
        return SDL_InvalidParamError("surface");
    }
    if (x < 0 || x >= surface->w) {
        return SDL_InvalidParamError("x");
    }
    if (y < 0 || y >= surface->h) {
        return SDL_InvalidParamError("y");
    }
    if (SDL_BYTESPERPIXEL(surface->format) <= sizeof(Uint32) && !SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        Uint8 r8, g8, b8, a8;
        r8 = (Uint8)SDL_round(SDL_clamp(r, 0.0f, 1.0f) * 255.0f);
        g8 = (Uint8)SDL_round(SDL_clamp(g, 0.0f, 1.0f) * 255.0f);
        b8 = (Uint8)SDL_round(SDL_clamp(b, 0.0f, 1.0f) * 255.0f);
        a8 = (Uint8)SDL_round(SDL_clamp(a, 0.0f, 1.0f) * 255.0f);
        if (SDL_WriteSurfacePixel(surface, x, y, r8, g8, b8, a8)) {
            result = true;
        }
    } else if (SDL_ISPIXELFORMAT_FOURCC(surface->format)) {
        result = SDL_Unsupported();
    } else {
        // This is really slow, but it gets the job done
        float rgba[4];
        Uint8 *p;
        if (SDL_MUSTLOCK(surface)) {
            if (!SDL_LockSurface(surface)) {
                return false;
            }
        }
        p = (Uint8 *)surface->pixels + y * surface->pitch + x * SDL_BYTESPERPIXEL(surface->format);
        rgba[0] = r;
        rgba[1] = g;
        rgba[2] = b;
        rgba[3] = a;
        if (surface->format == SDL_PIXELFORMAT_RGBA128_FLOAT) {
            SDL_memcpy(p, rgba, sizeof(rgba));
            result = true;
        } else {
            SDL_Colorspace dst_colorspace = surface->colorspace;
            SDL_Colorspace src_colorspace = (dst_colorspace == SDL_COLORSPACE_SRGB_LINEAR ? SDL_COLORSPACE_SRGB_LINEAR : SDL_COLORSPACE_SRGB);
            result = SDL_ConvertPixelsAndColorspace(1, 1, SDL_PIXELFORMAT_RGBA128_FLOAT, src_colorspace, 0, rgba, sizeof(rgba), surface->format, dst_colorspace, surface->props, p, surface->pitch);
        }
        if (SDL_MUSTLOCK(surface)) {
            SDL_UnlockSurface(surface);
        }
    }
    return result;
}
References SDL_BYTESPERPIXEL, SDL_clamp, SDL_COLORSPACE_SRGB, SDL_COLORSPACE_SRGB_LINEAR, SDL_ConvertPixelsAndColorspace(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_LockSurface(), SDL_memcpy, SDL_MUSTLOCK, SDL_PIXELFORMAT_RGBA128_FLOAT, SDL_round(), SDL_SurfaceValid(), SDL_UnlockSurface(), SDL_Unsupported, and SDL_WriteSurfacePixel().