SDL3: SDL-main/include/SDL3/SDL_joystick.h File Reference
SDL_joystick.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_guid.h>
#include <SDL3/SDL_mutex.h>
#include <SDL3/SDL_power.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_sensor.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_VirtualJoystickDesc
struct SDL_VirtualJoystickSensorDesc
struct SDL_VirtualJoystickTouchpadDesc
Macros
#define SDL_HAT_CENTERED 0x00u
#define SDL_HAT_DOWN 0x04u
#define SDL_HAT_LEFT 0x08u
#define SDL_HAT_LEFTDOWN (SDL_HAT_LEFT|SDL_HAT_DOWN)
#define SDL_HAT_LEFTUP (SDL_HAT_LEFT|SDL_HAT_UP)
#define SDL_HAT_RIGHT 0x02u
#define SDL_HAT_RIGHTDOWN (SDL_HAT_RIGHT|SDL_HAT_DOWN)
#define SDL_HAT_RIGHTUP (SDL_HAT_RIGHT|SDL_HAT_UP)
#define SDL_HAT_UP 0x01u
#define SDL_JOYSTICK_AXIS_MAX 32767
#define SDL_JOYSTICK_AXIS_MIN -32768
#define SDL_PROP_JOYSTICK_CAP_MONO_LED_BOOLEAN "SDL.joystick.cap.mono_led"
#define SDL_PROP_JOYSTICK_CAP_PLAYER_LED_BOOLEAN "SDL.joystick.cap.player_led"
#define SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN "SDL.joystick.cap.rgb_led"
#define SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN "SDL.joystick.cap.rumble"
#define SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN "SDL.joystick.cap.trigger_rumble"
Typedefs
typedef struct SDL_Joystick SDL_Joystick
typedef enum SDL_JoystickConnectionState SDL_JoystickConnectionState
typedef Uint32 SDL_JoystickID
typedef enum SDL_JoystickType SDL_JoystickType
typedef struct SDL_VirtualJoystickDesc SDL_VirtualJoystickDesc
typedef struct SDL_VirtualJoystickSensorDesc SDL_VirtualJoystickSensorDesc
typedef struct SDL_VirtualJoystickTouchpadDesc SDL_VirtualJoystickTouchpadDesc
Enumerations
enum SDL_JoystickConnectionState { SDL_JOYSTICK_CONNECTION_INVALID = -1 , SDL_JOYSTICK_CONNECTION_UNKNOWN , SDL_JOYSTICK_CONNECTION_WIRED , SDL_JOYSTICK_CONNECTION_WIRELESS }
enum SDL_JoystickType {
SDL_JOYSTICK_TYPE_UNKNOWN , SDL_JOYSTICK_TYPE_GAMEPAD , SDL_JOYSTICK_TYPE_WHEEL , SDL_JOYSTICK_TYPE_ARCADE_STICK ,
SDL_JOYSTICK_TYPE_FLIGHT_STICK , SDL_JOYSTICK_TYPE_DANCE_PAD , SDL_JOYSTICK_TYPE_GUITAR , SDL_JOYSTICK_TYPE_DRUM_KIT ,
SDL_JOYSTICK_TYPE_ARCADE_PAD , SDL_JOYSTICK_TYPE_THROTTLE , SDL_JOYSTICK_TYPE_COUNT
}
Functions
SDL_DECLSPEC SDL_JoystickID SDLCALL SDL_AttachVirtualJoystick (const SDL_VirtualJoystickDesc *desc)
SDL_DECLSPEC void SDLCALL SDL_CloseJoystick (SDL_Joystick *joystick)
SDL_COMPILE_TIME_ASSERT (SDL_VirtualJoystickDesc_SIZE,(sizeof(void *)==4 &&sizeof(SDL_VirtualJoystickDesc)==84)||(sizeof(void *)==8 &&sizeof(SDL_VirtualJoystickDesc)==136))
SDL_DECLSPEC bool SDLCALL SDL_DetachVirtualJoystick (SDL_JoystickID instance_id)
SDL_DECLSPEC Sint16 SDLCALL SDL_GetJoystickAxis (SDL_Joystick *joystick, int axis)
SDL_DECLSPEC bool SDLCALL SDL_GetJoystickAxisInitialState (SDL_Joystick *joystick, int axis, Sint16 *state)
SDL_DECLSPEC bool SDLCALL SDL_GetJoystickBall (SDL_Joystick *joystick, int ball, int *dx, int *dy)
SDL_DECLSPEC bool SDLCALL SDL_GetJoystickButton (SDL_Joystick *joystick, int button)
SDL_DECLSPEC SDL_JoystickConnectionState SDLCALL SDL_GetJoystickConnectionState (SDL_Joystick *joystick)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickFirmwareVersion (SDL_Joystick *joystick)
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_GetJoystickFromID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_GetJoystickFromPlayerIndex (int player_index)
SDL_DECLSPEC SDL_GUID SDLCALL SDL_GetJoystickGUID (SDL_Joystick *joystick)
SDL_DECLSPEC SDL_GUID SDLCALL SDL_GetJoystickGUIDForID (SDL_JoystickID instance_id)
SDL_DECLSPEC void SDLCALL SDL_GetJoystickGUIDInfo (SDL_GUID guid, Uint16 *vendor, Uint16 *product, Uint16 *version, Uint16 *crc16)
SDL_DECLSPEC Uint8 SDLCALL SDL_GetJoystickHat (SDL_Joystick *joystick, int hat)
SDL_DECLSPEC SDL_JoystickID SDLCALL SDL_GetJoystickID (SDL_Joystick *joystick)
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickName (SDL_Joystick *joystick)
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickNameForID (SDL_JoystickID instance_id)
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickPath (SDL_Joystick *joystick)
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickPathForID (SDL_JoystickID instance_id)
SDL_DECLSPEC int SDLCALL SDL_GetJoystickPlayerIndex (SDL_Joystick *joystick)
SDL_DECLSPEC int SDLCALL SDL_GetJoystickPlayerIndexForID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_PowerState SDLCALL SDL_GetJoystickPowerInfo (SDL_Joystick *joystick, int *percent)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProduct (SDL_Joystick *joystick)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProductForID (SDL_JoystickID instance_id)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProductVersion (SDL_Joystick *joystick)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProductVersionForID (SDL_JoystickID instance_id)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetJoystickProperties (SDL_Joystick *joystick)
SDL_DECLSPEC SDL_JoystickID *SDLCALL SDL_GetJoysticks (int *count)
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickSerial (SDL_Joystick *joystick)
SDL_DECLSPEC SDL_JoystickType SDLCALL SDL_GetJoystickType (SDL_Joystick *joystick)
SDL_DECLSPEC SDL_JoystickType SDLCALL SDL_GetJoystickTypeForID (SDL_JoystickID instance_id)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickVendor (SDL_Joystick *joystick)
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickVendorForID (SDL_JoystickID instance_id)
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickAxes (SDL_Joystick *joystick)
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickBalls (SDL_Joystick *joystick)
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickButtons (SDL_Joystick *joystick)
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickHats (SDL_Joystick *joystick)
SDL_DECLSPEC bool SDLCALL SDL_HasJoystick (void)
SDL_DECLSPEC bool SDLCALL SDL_IsJoystickVirtual (SDL_JoystickID instance_id)
SDL_DECLSPEC bool SDLCALL SDL_JoystickConnected (SDL_Joystick *joystick)
SDL_DECLSPEC bool SDLCALL SDL_JoystickEventsEnabled (void)
SDL_DECLSPEC void SDLCALL SDL_LockJoysticks (void) SDL_ACQUIRE(SDL_joystick_lock)
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_OpenJoystick (SDL_JoystickID instance_id)
SDL_DECLSPEC bool SDLCALL SDL_RumbleJoystick (SDL_Joystick *joystick, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms)
SDL_DECLSPEC bool SDLCALL SDL_RumbleJoystickTriggers (SDL_Joystick *joystick, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms)
SDL_DECLSPEC bool SDLCALL SDL_SendJoystickEffect (SDL_Joystick *joystick, const void *data, int size)
SDL_DECLSPEC bool SDLCALL SDL_SendJoystickVirtualSensorData (SDL_Joystick *joystick, SDL_SensorType type, Uint64 sensor_timestamp, const float *data, int num_values)
SDL_DECLSPEC void SDLCALL SDL_SetJoystickEventsEnabled (bool enabled)
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickLED (SDL_Joystick *joystick, Uint8 red, Uint8 green, Uint8 blue)
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickPlayerIndex (SDL_Joystick *joystick, int player_index)
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualAxis (SDL_Joystick *joystick, int axis, Sint16 value)
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualBall (SDL_Joystick *joystick, int ball, Sint16 xrel, Sint16 yrel)
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualButton (SDL_Joystick *joystick, int button, bool down)
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualHat (SDL_Joystick *joystick, int hat, Uint8 value)
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualTouchpad (SDL_Joystick *joystick, int touchpad, int finger, bool down, float x, float y, float pressure)
SDL_DECLSPEC void SDLCALL SDL_UnlockJoysticks (void) SDL_RELEASE(SDL_joystick_lock)
SDL_DECLSPEC void SDLCALL SDL_UpdateJoysticks (void)
Macro Definition Documentation
SDL_HAT_CENTERED
#define SDL_HAT_CENTERED 0x00u
Referenced by IOS_MFIJoystickUpdate(), SDL_PrivateJoystickForceRecentering(), and SDL_SendJoystickHat().
SDL_HAT_DOWN
#define SDL_HAT_DOWN 0x04u
Referenced by SDL_FixupHIDAPIMapping().
SDL_HAT_LEFT
#define SDL_HAT_LEFT 0x08u
Referenced by SDL_FixupHIDAPIMapping().
SDL_HAT_LEFTDOWN
#define SDL_HAT_LEFTDOWN (SDL_HAT_LEFT|SDL_HAT_DOWN)
SDL_HAT_LEFTUP
#define SDL_HAT_LEFTUP (SDL_HAT_LEFT|SDL_HAT_UP)
SDL_HAT_RIGHT
#define SDL_HAT_RIGHT 0x02u
Referenced by SDL_FixupHIDAPIMapping().
SDL_HAT_RIGHTDOWN
#define SDL_HAT_RIGHTDOWN (SDL_HAT_RIGHT|SDL_HAT_DOWN)
SDL_HAT_RIGHTUP
#define SDL_HAT_RIGHTUP (SDL_HAT_RIGHT|SDL_HAT_UP)
SDL_HAT_UP
#define SDL_HAT_UP 0x01u
Referenced by SDL_FixupHIDAPIMapping().
SDL_JOYSTICK_AXIS_MAX
#define SDL_JOYSTICK_AXIS_MAX 32767
The largest value an SDL_Joystick's axis can report.
Since
This macro is available since SDL 3.2.0.
See also
SDL_JOYSTICK_AXIS_MIN
Referenced by SDL_PrivateParseGamepadElement(), and SDL_SendJoystickAxis().
SDL_JOYSTICK_AXIS_MIN
#define SDL_JOYSTICK_AXIS_MIN -32768
The smallest value an SDL_Joystick's axis can report.
This is a negative number!
Since
This macro is available since SDL 3.2.0.
See also
SDL_JOYSTICK_AXIS_MAX
Referenced by SDL_PrivateParseGamepadElement().
SDL_PROP_JOYSTICK_CAP_MONO_LED_BOOLEAN
#define SDL_PROP_JOYSTICK_CAP_MONO_LED_BOOLEAN "SDL.joystick.cap.mono_led"
SDL_PROP_JOYSTICK_CAP_PLAYER_LED_BOOLEAN
#define SDL_PROP_JOYSTICK_CAP_PLAYER_LED_BOOLEAN "SDL.joystick.cap.player_led"
SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN
#define SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN "SDL.joystick.cap.rgb_led"
Referenced by IOS_JoystickOpen().
SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN
#define SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN "SDL.joystick.cap.rumble"
Referenced by IOS_JoystickOpen().
SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN
#define SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN "SDL.joystick.cap.trigger_rumble"
Referenced by IOS_JoystickOpen().
Typedef Documentation
SDL_Joystick
typedef struct SDL_Joystick SDL_Joystick
CategoryJoystick
SDL joystick support.
This is the lower-level joystick handling. If you want the simpler option, where what each button does is well-defined, you should use the gamepad API instead.
The term "instance_id" is the current instantiation of a joystick device in the system, if the joystick is removed and then re-inserted then it will get a new instance_id, instance_id's are monotonically increasing identifiers of a joystick plugged in.
The term "player_index" is the number assigned to a player on a specific controller. For XInput controllers this returns the XInput user index. Many joysticks will not be able to supply this information.
SDL_GUID is used as a stable 128-bit identifier for a joystick device that does not change over time. It identifies class of the device (a X360 wired controller for example). This identifier is platform dependent.
In order to use these functions, SDL_Init() must have been called with the SDL_INIT_JOYSTICK flag. This causes SDL to scan the system for joysticks, and load appropriate drivers.
If you would like to receive joystick updates while the application is in the background, you should set the following hint before calling SDL_Init(): SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS The joystick structure used to identify an SDL joystick.
This is opaque data.
Since
This struct is available since SDL 3.2.0.
SDL_JoystickConnectionState
typedef enum SDL_JoystickConnectionState SDL_JoystickConnectionState
Possible connection states for a joystick device.
This is used by SDL_GetJoystickConnectionState to report how a device is connected to the system.
Since
This enum is available since SDL 3.2.0.
SDL_JoystickID
typedef Uint32 SDL_JoystickID
This is a unique ID for a joystick for the time it is connected to the system, and is never reused for the lifetime of the application.
If the joystick is disconnected and reconnected, it will get a new ID.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
SDL_JoystickType
typedef enum SDL_JoystickType SDL_JoystickType
An enum of some common joystick types.
In some cases, SDL can identify a low-level joystick as being a certain type of device, and will report it through SDL_GetJoystickType (or SDL_GetJoystickTypeForID).
This is by no means a complete list of everything that can be plugged into a computer.
You may refer to XInput Controller Types table for a general understanding of each joystick type.
Since
This enum is available since SDL 3.2.0.
SDL_VirtualJoystickDesc
typedef struct SDL_VirtualJoystickDesc SDL_VirtualJoystickDesc
The structure that describes a virtual joystick.
This structure should be initialized using SDL_INIT_INTERFACE(). All elements of this structure are optional.
Since
This struct is available since SDL 3.2.0.
See also
SDL_AttachVirtualJoystick
SDL_INIT_INTERFACE
SDL_VirtualJoystickSensorDesc
SDL_VirtualJoystickTouchpadDesc
SDL_VirtualJoystickSensorDesc
typedef struct SDL_VirtualJoystickSensorDesc SDL_VirtualJoystickSensorDesc
The structure that describes a virtual joystick sensor.
Since
This struct is available since SDL 3.2.0.
See also
SDL_VirtualJoystickDesc
SDL_VirtualJoystickTouchpadDesc
typedef struct SDL_VirtualJoystickTouchpadDesc SDL_VirtualJoystickTouchpadDesc
The structure that describes a virtual joystick touchpad.
Since
This struct is available since SDL 3.2.0.
See also
SDL_VirtualJoystickDesc
Enumeration Type Documentation
SDL_JoystickConnectionState
enum SDL_JoystickConnectionState
Possible connection states for a joystick device.
This is used by SDL_GetJoystickConnectionState to report how a device is connected to the system.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_JOYSTICK_CONNECTION_INVALID
SDL_JOYSTICK_CONNECTION_UNKNOWN
SDL_JOYSTICK_CONNECTION_WIRED
SDL_JOYSTICK_CONNECTION_WIRELESS
{
    SDL_JOYSTICK_CONNECTION_INVALID = -1,
    SDL_JOYSTICK_CONNECTION_UNKNOWN,
    SDL_JOYSTICK_CONNECTION_WIRED,
    SDL_JOYSTICK_CONNECTION_WIRELESS
} SDL_JoystickConnectionState;
SDL_JoystickType
enum SDL_JoystickType
An enum of some common joystick types.
In some cases, SDL can identify a low-level joystick as being a certain type of device, and will report it through SDL_GetJoystickType (or SDL_GetJoystickTypeForID).
This is by no means a complete list of everything that can be plugged into a computer.
You may refer to XInput Controller Types table for a general understanding of each joystick type.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_JOYSTICK_TYPE_UNKNOWN
SDL_JOYSTICK_TYPE_GAMEPAD
SDL_JOYSTICK_TYPE_WHEEL
SDL_JOYSTICK_TYPE_ARCADE_STICK
SDL_JOYSTICK_TYPE_FLIGHT_STICK
SDL_JOYSTICK_TYPE_DANCE_PAD
SDL_JOYSTICK_TYPE_GUITAR
SDL_JOYSTICK_TYPE_DRUM_KIT
SDL_JOYSTICK_TYPE_ARCADE_PAD
SDL_JOYSTICK_TYPE_THROTTLE
SDL_JOYSTICK_TYPE_COUNT
{
    SDL_JOYSTICK_TYPE_UNKNOWN,
    SDL_JOYSTICK_TYPE_GAMEPAD,
    SDL_JOYSTICK_TYPE_WHEEL,
    SDL_JOYSTICK_TYPE_ARCADE_STICK,
    SDL_JOYSTICK_TYPE_FLIGHT_STICK,
    SDL_JOYSTICK_TYPE_DANCE_PAD,
    SDL_JOYSTICK_TYPE_GUITAR,
    SDL_JOYSTICK_TYPE_DRUM_KIT,
    SDL_JOYSTICK_TYPE_ARCADE_PAD,
    SDL_JOYSTICK_TYPE_THROTTLE,
    SDL_JOYSTICK_TYPE_COUNT
} SDL_JoystickType;
Function Documentation
SDL_AttachVirtualJoystick()
SDL_DECLSPEC SDL_JoystickID SDLCALL SDL_AttachVirtualJoystick (const SDL_VirtualJoystickDesc * desc) extern
Attach a new virtual joystick.
Parameters
desc joystick description, initialized using SDL_INIT_INTERFACE().
Returns
the joystick instance ID, or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DetachVirtualJoystick
{
#ifdef SDL_JOYSTICK_VIRTUAL
    SDL_JoystickID result;
    SDL_LockJoysticks();
    result = SDL_JoystickAttachVirtualInner(desc);
    SDL_UnlockJoysticks();
    return result;
#else
    SDL_SetError("SDL not built with virtual-joystick support");
    return 0;
#endif
}
References SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_CloseJoystick()
SDL_DECLSPEC void SDLCALL SDL_CloseJoystick (SDL_Joystick * joystick) extern
Close a joystick previously opened with SDL_OpenJoystick().
Parameters
joystick the joystick device to close.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenJoystick
{
    SDL_Joystick *joysticklist;
    SDL_Joystick *joysticklistprev;
    int i;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick,);
        // First decrement ref count
        if (--joystick->ref_count > 0) {
            SDL_UnlockJoysticks();
            return;
        }
        SDL_DestroyProperties(joystick->props);
        if (joystick->rumble_expiration) {
            SDL_RumbleJoystick(joystick, 0, 0, 0);
        }
        if (joystick->trigger_rumble_expiration) {
            SDL_RumbleJoystickTriggers(joystick, 0, 0, 0);
        }
        CleanupSensorFusion(joystick);
        joystick->driver->Close(joystick);
        joystick->hwdata = NULL;
        SDL_SetObjectValid(joystick, SDL_OBJECT_TYPE_JOYSTICK, false);
        joysticklist = SDL_joysticks;
        joysticklistprev = NULL;
        while (joysticklist) {
            if (joystick == joysticklist) {
                if (joysticklistprev) {
                    // unlink this entry
                    joysticklistprev->next = joysticklist->next;
                } else {
                    SDL_joysticks = joystick->next;
                }
                break;
            }
            joysticklistprev = joysticklist;
            joysticklist = joysticklist->next;
        }
        // Free the data associated with this joystick
        SDL_free(joystick->name);
        SDL_free(joystick->path);
        SDL_free(joystick->serial);
        SDL_free(joystick->axes);
        SDL_free(joystick->balls);
        SDL_free(joystick->hats);
        SDL_free(joystick->buttons);
        for (i = 0; i < joystick->ntouchpads; i++) {
            SDL_JoystickTouchpadInfo *touchpad = &joystick->touchpads[i];
            SDL_free(touchpad->fingers);
        }
        SDL_free(joystick->touchpads);
        SDL_free(joystick->sensors);
        SDL_free(joystick);
    }
    SDL_UnlockJoysticks();
}
References CHECK_JOYSTICK_MAGIC, CleanupSensorFusion(), SDL_JoystickTouchpadInfo::fingers, NULL, SDL_DestroyProperties(), SDL_free(), SDL_LockJoysticks(), SDL_OBJECT_TYPE_JOYSTICK, SDL_RumbleJoystick(), SDL_RumbleJoystickTriggers(), SDL_SetObjectValid(), and SDL_UnlockJoysticks().
Referenced by SDL_CloseGamepad(), SDL_OpenGamepad(), SDL_OpenJoystick(), and SDL_QuitJoysticks().
SDL_COMPILE_TIME_ASSERT()
SDL_COMPILE_TIME_ASSERT (SDL_VirtualJoystickDesc_SIZE , (sizeof(void *)==4 &&sizeof(SDL_VirtualJoystickDesc)==84)||(sizeof(void *)==8 &&sizeof(SDL_VirtualJoystickDesc)==136))
References SDL_DECLSPEC, and SDLCALL.
SDL_DetachVirtualJoystick()
SDL_DECLSPEC bool SDLCALL SDL_DetachVirtualJoystick (SDL_JoystickID instance_id) extern
Detach a virtual joystick.
Parameters
instance_id the joystick instance ID, previously returned from SDL_AttachVirtualJoystick().
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_AttachVirtualJoystick
{
#ifdef SDL_JOYSTICK_VIRTUAL
    bool result;
    SDL_LockJoysticks();
    result = SDL_JoystickDetachVirtualInner(instance_id);
    SDL_UnlockJoysticks();
    return result;
#else
    return SDL_SetError("SDL not built with virtual-joystick support");
#endif
}
References SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_GetJoystickAxis()
SDL_DECLSPEC Sint16 SDLCALL SDL_GetJoystickAxis (SDL_Joystick * joystick, int axis) extern
Get the current state of an axis control on a joystick.
SDL makes no promises about what part of the joystick any given axis refers to. Your game should have some sort of configuration UI to let users specify what each axis should be bound to. Alternately, SDL's higher-level Game Controller API makes a great effort to apply order to this lower-level interface, so you know that a specific axis is the "left thumb stick," etc.
The value returned by SDL_GetJoystickAxis() is a signed integer (-32768 to 32767) representing the current position of the axis. It may be necessary to impose certain tolerances on these values to account for jitter.
Parameters
joystick an SDL_Joystick structure containing joystick information.
axis the axis to query; the axis indices start at index 0.
Returns
a 16-bit signed integer representing the current position of the axis or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumJoystickAxes
{
    Sint16 state;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, 0);
        if (axis < joystick->naxes) {
            state = joystick->axes[axis].value;
        } else {
            SDL_SetError("Joystick only has %d axes", joystick->naxes);
            state = 0;
        }
    }
    SDL_UnlockJoysticks();
    return state;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadAxis(), and SDL_GetGamepadButton().
SDL_GetJoystickAxisInitialState()
SDL_DECLSPEC bool SDLCALL SDL_GetJoystickAxisInitialState (SDL_Joystick * joystick, int axis, Sint16 * state) extern
Get the initial state of an axis control on a joystick.
The state is a value ranging from -32768 to 32767.
The axis indices start at index 0.
Parameters
joystick an SDL_Joystick structure containing joystick information.
axis the axis to query; the axis indices start at index 0.
state upon return, the initial value is supplied here.
Returns
true if this axis has any initial value, or false if not.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        if (axis >= joystick->naxes) {
            SDL_SetError("Joystick only has %d axes", joystick->naxes);
            result = false;
        } else {
            if (state) {
                *state = joystick->axes[axis].initial_value;
            }
            result = joystick->axes[axis].has_initial_value;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_GetJoystickBall()
SDL_DECLSPEC bool SDLCALL SDL_GetJoystickBall (SDL_Joystick * joystick, int ball, int * dx, int * dy) extern
Get the ball axis change since the last poll.
Trackballs can only return relative motion since the last call to SDL_GetJoystickBall(), these motion deltas are placed into dx and dy.
Most joysticks do not have trackballs.
Parameters
joystick the SDL_Joystick to query.
ball the ball index to query; ball indices start at index 0.
dx stores the difference in the x axis position since the last poll.
dy stores the difference in the y axis position since the last poll.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumJoystickBalls
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        if (ball < joystick->nballs) {
            if (dx) {
                *dx = joystick->balls[ball].dx;
            }
            if (dy) {
                *dy = joystick->balls[ball].dy;
            }
            joystick->balls[ball].dx = 0;
            joystick->balls[ball].dy = 0;
            result = true;
        } else {
            result = SDL_SetError("Joystick only has %d balls", joystick->nballs);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_GetJoystickButton()
SDL_DECLSPEC bool SDLCALL SDL_GetJoystickButton (SDL_Joystick * joystick, int button) extern
Get the current state of a button on a joystick.
Parameters
joystick an SDL_Joystick structure containing joystick information.
button the button index to get the state from; indices start at index 0.
Returns
true if the button is pressed, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumJoystickButtons
{
    bool down = false;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        if (button < joystick->nbuttons) {
            down = joystick->buttons[button];
        } else {
            SDL_SetError("Joystick only has %d buttons", joystick->nbuttons);
        }
    }
    SDL_UnlockJoysticks();
    return down;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadAxis(), and SDL_GetGamepadButton().
SDL_GetJoystickConnectionState()
SDL_DECLSPEC SDL_JoystickConnectionState SDLCALL SDL_GetJoystickConnectionState (SDL_Joystick * joystick) extern
Get the connection state of a joystick.
Parameters
joystick the joystick to query.
Returns
the connection state on success or SDL_JOYSTICK_CONNECTION_INVALID on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_JoystickConnectionState result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, SDL_JOYSTICK_CONNECTION_INVALID);
        result = joystick->connection_state;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_JOYSTICK_CONNECTION_INVALID, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadConnectionState().
SDL_GetJoystickFirmwareVersion()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickFirmwareVersion (SDL_Joystick * joystick) extern
Get the firmware version of an opened joystick, if available.
If the firmware version isn't available this function returns 0.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the firmware version of the selected joystick, or 0 if unavailable.
Since
This function is available since SDL 3.2.0.
{
    Uint16 result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, 0);
        result = joystick->firmware_version;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadFirmwareVersion().
SDL_GetJoystickFromID()
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_GetJoystickFromID (SDL_JoystickID instance_id) extern
Get the SDL_Joystick associated with an instance ID, if it has been opened.
Parameters
instance_id the instance ID to get the SDL_Joystick for.
Returns
an SDL_Joystick on success or NULL on failure or if it hasn't been opened yet; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Joystick *joystick;
    SDL_LockJoysticks();
    for (joystick = SDL_joysticks; joystick; joystick = joystick->next) {
        if (joystick->instance_id == instance_id) {
            break;
        }
    }
    SDL_UnlockJoysticks();
    return joystick;
}
References SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetJoystickFromPlayerIndex()
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_GetJoystickFromPlayerIndex (int player_index) extern
Get the SDL_Joystick associated with a player index.
Parameters
player_index the player index to get the SDL_Joystick for.
Returns
an SDL_Joystick on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickPlayerIndex
SDL_SetJoystickPlayerIndex
Return the SDL_Joystick associated with a player index.
{
    SDL_JoystickID instance_id;
    SDL_Joystick *joystick;
    SDL_LockJoysticks();
    instance_id = SDL_GetJoystickIDForPlayerIndex(player_index);
    for (joystick = SDL_joysticks; joystick; joystick = joystick->next) {
        if (joystick->instance_id == instance_id) {
            break;
        }
    }
    SDL_UnlockJoysticks();
    return joystick;
}
References SDL_GetJoystickIDForPlayerIndex(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadFromPlayerIndex().
SDL_GetJoystickGUID()
SDL_DECLSPEC SDL_GUID SDLCALL SDL_GetJoystickGUID (SDL_Joystick * joystick) extern
Get the implementation-dependent GUID for the joystick.
This function requires an open joystick.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the GUID of the given joystick. If called on an invalid index, this function returns a zero GUID; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickGUIDForID
SDL_GUIDToString
{
    SDL_GUID result;
    SDL_LockJoysticks();
    {
        static SDL_GUID emptyGUID;
        CHECK_JOYSTICK_MAGIC(joystick, emptyGUID);
        result = joystick->guid;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by IsROGAlly(), SDL_GetJoystickProduct(), SDL_GetJoystickProductVersion(), SDL_GetJoystickType(), SDL_GetJoystickVendor(), SDL_GetRealGamepadType(), and ShouldAttemptSensorFusion().
SDL_GetJoystickGUIDForID()
SDL_DECLSPEC SDL_GUID SDLCALL SDL_GetJoystickGUIDForID (SDL_JoystickID instance_id) extern
Get the implementation-dependent GUID of a joystick.
This can be called before any joysticks are opened.
Parameters
instance_id the joystick instance ID.
Returns
the GUID of the selected joystick. If called with an invalid instance_id, this function returns a zero GUID.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickGUID
SDL_GUIDToString
{
    SDL_JoystickDriver *driver;
    int device_index;
    SDL_GUID guid;
    SDL_LockJoysticks();
    if (SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        guid = driver->GetDeviceGUID(device_index);
    } else {
        SDL_zero(guid);
    }
    SDL_UnlockJoysticks();
    return guid;
}
References SDL_JoystickDriver::GetDeviceGUID, SDL_GetDriverAndJoystickIndex(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_zero.
Referenced by SDL_GetGamepadGUIDForID(), SDL_GetGamepadMappingForID(), SDL_GetJoystickProductForID(), SDL_GetJoystickProductVersionForID(), SDL_GetJoystickTypeForID(), SDL_GetJoystickVendorForID(), SDL_GetRealGamepadTypeForID(), SDL_PrivateGetGamepadMapping(), and SDL_SetGamepadMapping().
SDL_GetJoystickGUIDInfo()
SDL_DECLSPEC void SDLCALL SDL_GetJoystickGUIDInfo (SDL_GUID guid, Uint16 * vendor, Uint16 * product, Uint16 * version, Uint16 * crc16) extern
Get the device information encoded in a SDL_GUID structure.
Parameters
guid the SDL_GUID you wish to get info about.
vendor a pointer filled in with the device VID, or 0 if not available.
product a pointer filled in with the device PID, or 0 if not available.
version a pointer filled in with the device version, or 0 if not available.
crc16 a pointer filled in with a CRC used to distinguish different products with the same VID/PID, or 0 if not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickGUIDForID
{
    Uint16 *guid16 = (Uint16 *)guid.data;
    Uint16 bus = SDL_Swap16LE(guid16[0]);
    if ((bus < ' ' || bus == SDL_HARDWARE_BUS_VIRTUAL) && guid16[3] == 0x0000 && guid16[5] == 0x0000) {
        /* This GUID fits the standard form:
         * 16-bit bus
         * 16-bit CRC16 of the joystick name (can be zero)
         * 16-bit vendor ID
         * 16-bit zero
         * 16-bit product ID
         * 16-bit zero
         * 16-bit version
         * 8-bit driver identifier ('h' for HIDAPI, 'x' for XInput, etc.)
         * 8-bit driver-dependent type info
         */
        if (vendor) {
            *vendor = SDL_Swap16LE(guid16[2]);
        }
        if (product) {
            *product = SDL_Swap16LE(guid16[4]);
        }
        if (version) {
            *version = SDL_Swap16LE(guid16[6]);
        }
        if (crc16) {
            *crc16 = SDL_Swap16LE(guid16[1]);
        }
    } else if (bus < ' ' || bus == SDL_HARDWARE_BUS_VIRTUAL) {
        /* This GUID fits the unknown VID/PID form:
         * 16-bit bus
         * 16-bit CRC16 of the joystick name (can be zero)
         * 11 characters of the joystick name, null terminated
         */
        if (vendor) {
            *vendor = 0;
        }
        if (product) {
            *product = 0;
        }
        if (version) {
            *version = 0;
        }
        if (crc16) {
            *crc16 = SDL_Swap16LE(guid16[1]);
        }
    } else {
        if (vendor) {
            *vendor = 0;
        }
        if (product) {
            *product = 0;
        }
        if (version) {
            *version = 0;
        }
        if (crc16) {
            *crc16 = 0;
        }
    }
}
References SDL_GUID::data, SDL_HARDWARE_BUS_VIRTUAL, and SDL_Swap16LE.
Referenced by IsROGAlly(), SDL_CreateMappingForHIDAPIGamepad(), SDL_GetGamepadTypeFromGUID(), SDL_GetJoystickGUIDType(), SDL_GetJoystickProduct(), SDL_GetJoystickProductForID(), SDL_GetJoystickProductVersion(), SDL_GetJoystickProductVersionForID(), SDL_GetJoystickVendor(), SDL_GetJoystickVendorForID(), SDL_JoystickGUIDUsesVersion(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateMatchGamepadMappingForGUID(), and ShouldAttemptSensorFusion().
SDL_GetJoystickHat()
SDL_DECLSPEC Uint8 SDLCALL SDL_GetJoystickHat (SDL_Joystick * joystick, int hat) extern
Get the current state of a POV hat on a joystick.
The returned value will be one of the SDL_HAT_* values.
Parameters
joystick an SDL_Joystick structure containing joystick information.
hat the hat index to get the state from; indices start at index 0.
Returns
the current hat position.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumJoystickHats
{
    Uint8 state;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, 0);
        if (hat < joystick->nhats) {
            state = joystick->hats[hat];
        } else {
            SDL_SetError("Joystick only has %d hats", joystick->nhats);
            state = 0;
        }
    }
    SDL_UnlockJoysticks();
    return state;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadAxis(), and SDL_GetGamepadButton().
SDL_GetJoystickID()
SDL_DECLSPEC SDL_JoystickID SDLCALL SDL_GetJoystickID (SDL_Joystick * joystick) extern
Get the instance ID of an opened joystick.
Parameters
joystick an SDL_Joystick structure containing joystick information.
Returns
the instance ID of the specified joystick on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_JoystickID result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, 0);
        result = joystick->instance_id;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadID(), and SDL_IsJoystickHaptic().
SDL_GetJoystickName()
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickName (SDL_Joystick * joystick) extern
Get the implementation dependent name of a joystick.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the name of the selected joystick. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickNameForID
{
    const char *result;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, NULL);
        info = SDL_GetJoystickVirtualGamepadInfoForID(joystick->instance_id);
        if (info) {
            result = SDL_GetPersistentString(info->name);
        } else {
            result = SDL_GetPersistentString(joystick->name);
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_SteamVirtualGamepadInfo::name, NULL, SDL_GetJoystickVirtualGamepadInfoForID(), SDL_GetPersistentString(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadName(), and SDL_GetRealGamepadType().
SDL_GetJoystickNameForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickNameForID (SDL_JoystickID instance_id) extern
Get the implementation dependent name of a joystick.
This can be called before any joysticks are opened.
Parameters
instance_id the joystick instance ID.
Returns
the name of the selected joystick. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickName
SDL_GetJoysticks
{
    SDL_JoystickDriver *driver;
    int device_index;
    const char *name = NULL;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    info = SDL_GetJoystickVirtualGamepadInfoForID(instance_id);
    if (info) {
        name = SDL_GetPersistentString(info->name);
    } else if (SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        name = SDL_GetPersistentString(driver->GetDeviceName(device_index));
    }
    SDL_UnlockJoysticks();
    return name;
}
References SDL_JoystickDriver::GetDeviceName, SDL_SteamVirtualGamepadInfo::name, NULL, SDL_GetDriverAndJoystickIndex(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_GetPersistentString(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadNameForID(), SDL_GetRealGamepadTypeForID(), and SDL_PrivateGetGamepadMapping().
SDL_GetJoystickPath()
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickPath (SDL_Joystick * joystick) extern
Get the implementation dependent path of a joystick.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the path of the selected joystick. If no path can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickPathForID
{
    const char *result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, NULL);
        if (joystick->path) {
            result = SDL_GetPersistentString(joystick->path);
        } else {
            SDL_Unsupported();
            result = NULL;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, NULL, SDL_GetPersistentString(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_Unsupported.
Referenced by SDL_GetGamepadPath().
SDL_GetJoystickPathForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickPathForID (SDL_JoystickID instance_id) extern
Get the implementation dependent path of a joystick.
This can be called before any joysticks are opened.
Parameters
instance_id the joystick instance ID.
Returns
the path of the selected joystick. If no path can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickPath
SDL_GetJoysticks
{
    SDL_JoystickDriver *driver;
    int device_index;
    const char *path = NULL;
    SDL_LockJoysticks();
    if (SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        path = SDL_GetPersistentString(driver->GetDevicePath(device_index));
    }
    SDL_UnlockJoysticks();
    if (!path) {
        SDL_Unsupported();
    }
    return path;
}
References SDL_JoystickDriver::GetDevicePath, NULL, SDL_GetDriverAndJoystickIndex(), SDL_GetPersistentString(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_Unsupported.
Referenced by SDL_GetGamepadPathForID().
SDL_GetJoystickPlayerIndex()
SDL_DECLSPEC int SDLCALL SDL_GetJoystickPlayerIndex (SDL_Joystick * joystick) extern
Get the player index of an opened joystick.
For XInput controllers this returns the XInput user index. Many joysticks will not be able to supply this information.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the player index, or -1 if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetJoystickPlayerIndex
Get the player index of an opened joystick, or -1 if it's not available
{
    int result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, -1);
        result = SDL_GetPlayerIndexForJoystickID(joystick->instance_id);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_GetPlayerIndexForJoystickID(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadPlayerIndex().
SDL_GetJoystickPlayerIndexForID()
SDL_DECLSPEC int SDLCALL SDL_GetJoystickPlayerIndexForID (SDL_JoystickID instance_id) extern
Get the player index of a joystick.
This can be called before any joysticks are opened.
Parameters
instance_id the joystick instance ID.
Returns
the player index of a joystick, or -1 if it's not available.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickPlayerIndex
SDL_GetJoysticks
{
    int player_index;
    SDL_LockJoysticks();
    player_index = SDL_GetPlayerIndexForJoystickID(instance_id);
    SDL_UnlockJoysticks();
    return player_index;
}
References SDL_GetPlayerIndexForJoystickID(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadPlayerIndexForID().
SDL_GetJoystickPowerInfo()
SDL_DECLSPEC SDL_PowerState SDLCALL SDL_GetJoystickPowerInfo (SDL_Joystick * joystick, int * percent) extern
Get the battery state of a joystick.
You should never take a battery status as absolute truth. Batteries (especially failing batteries) are delicate hardware, and the values reported here are best estimates based on what that hardware reports. It's not uncommon for older batteries to lose stored power much faster than it reports, or completely drain when reporting it has 20 percent left, etc.
Parameters
joystick the joystick to query.
percent a pointer filled in with the percentage of battery life left, between 0 and 100, or NULL to ignore. This will be filled in with -1 we can't determine a value or there is no battery.
Returns
the current battery state or SDL_POWERSTATE_ERROR on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PowerState result;
    if (percent) {
        *percent = -1;
    }
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, SDL_POWERSTATE_ERROR);
        result = joystick->battery_state;
        if (percent) {
            *percent = joystick->battery_percent;
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), SDL_POWERSTATE_ERROR, and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadPowerInfo().
SDL_GetJoystickProduct()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProduct (SDL_Joystick * joystick) extern
Get the USB product ID of an opened joystick, if available.
If the product ID isn't available this function returns 0.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the USB product ID of the selected joystick, or 0 if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickProductForID
{
    Uint16 product;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, 0);
        info = SDL_GetJoystickVirtualGamepadInfoForID(joystick->instance_id);
        if (info) {
            product = info->product_id;
        } else {
            SDL_GUID guid = SDL_GetJoystickGUID(joystick);
            SDL_GetJoystickGUIDInfo(guid, NULL, &product, NULL, NULL);
        }
    }
    SDL_UnlockJoysticks();
    return product;
}
References CHECK_JOYSTICK_MAGIC, NULL, SDL_SteamVirtualGamepadInfo::product_id, SDL_GetJoystickGUID(), SDL_GetJoystickGUIDInfo(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadProduct(), SDL_JoystickAxesCenteredAtZero(), and SDL_OpenHapticFromJoystick().
SDL_GetJoystickProductForID()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProductForID (SDL_JoystickID instance_id) extern
Get the USB product ID of a joystick, if available.
This can be called before any joysticks are opened. If the product ID isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the USB product ID of the selected joystick. If called with an invalid instance_id, this function returns 0.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickProduct
SDL_GetJoysticks
{
    Uint16 product;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    info = SDL_GetJoystickVirtualGamepadInfoForID(instance_id);
    if (info) {
        product = info->product_id;
    } else {
        SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
        SDL_GetJoystickGUIDInfo(guid, NULL, &product, NULL, NULL);
    }
    SDL_UnlockJoysticks();
    return product;
}
References NULL, SDL_SteamVirtualGamepadInfo::product_id, SDL_GetJoystickGUIDForID(), SDL_GetJoystickGUIDInfo(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadProductForID().
SDL_GetJoystickProductVersion()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProductVersion (SDL_Joystick * joystick) extern
Get the product version of an opened joystick, if available.
If the product version isn't available this function returns 0.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the product version of the selected joystick, or 0 if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickProductVersionForID
{
    Uint16 version;
    SDL_GUID guid = SDL_GetJoystickGUID(joystick);
    SDL_GetJoystickGUIDInfo(guid, NULL, NULL, &version, NULL);
    return version;
}
References NULL, SDL_GetJoystickGUID(), and SDL_GetJoystickGUIDInfo().
Referenced by SDL_GetGamepadProductVersion().
SDL_GetJoystickProductVersionForID()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickProductVersionForID (SDL_JoystickID instance_id) extern
Get the product version of a joystick, if available.
This can be called before any joysticks are opened. If the product version isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the product version of the selected joystick. If called with an invalid instance_id, this function returns 0.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickProductVersion
SDL_GetJoysticks
{
    Uint16 version;
    SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
    SDL_GetJoystickGUIDInfo(guid, NULL, NULL, &version, NULL);
    return version;
}
References NULL, SDL_GetJoystickGUIDForID(), and SDL_GetJoystickGUIDInfo().
Referenced by SDL_GetGamepadProductVersionForID().
SDL_GetJoystickProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetJoystickProperties (SDL_Joystick * joystick) extern
Get the properties associated with a joystick.
The following read-only properties are provided by SDL:
SDL_PROP_JOYSTICK_CAP_MONO_LED_BOOLEAN: true if this joystick has an LED that has adjustable brightness
SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN: true if this joystick has an LED that has adjustable color
SDL_PROP_JOYSTICK_CAP_PLAYER_LED_BOOLEAN: true if this joystick has a player LED
SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN: true if this joystick has left/right rumble
SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN: true if this joystick has simple trigger rumble
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, 0);
        if (joystick->props == 0) {
            joystick->props = SDL_CreateProperties();
        }
        result = joystick->props;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_CreateProperties(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by IOS_JoystickOpen(), and SDL_GetGamepadProperties().
SDL_GetJoysticks()
SDL_DECLSPEC SDL_JoystickID *SDLCALL SDL_GetJoysticks (int * count) extern
Get a list of currently connected joysticks.
Parameters
count a pointer filled in with the number of joysticks returned, may be NULL.
Returns
a 0 terminated array of joystick instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasJoystick
SDL_OpenJoystick
{
    int i, num_joysticks, device_index;
    int joystick_index = 0, total_joysticks = 0;
    SDL_JoystickID *joysticks;
    SDL_LockJoysticks();
    {
        for (i = 0; i < SDL_arraysize(SDL_joystick_drivers); ++i) {
            total_joysticks += SDL_joystick_drivers[i]->GetCount();
        }
        joysticks = (SDL_JoystickID *)SDL_malloc((total_joysticks + 1) * sizeof(*joysticks));
        if (joysticks) {
            if (count) {
                *count = total_joysticks;
            }
            for (i = 0; i < SDL_arraysize(SDL_joystick_drivers); ++i) {
                num_joysticks = SDL_joystick_drivers[i]->GetCount();
                for (device_index = 0; device_index < num_joysticks; ++device_index) {
                    SDL_assert(joystick_index < total_joysticks);
                    joysticks[joystick_index] = SDL_joystick_drivers[i]->GetDeviceInstanceID(device_index);
                    SDL_assert(joysticks[joystick_index] > 0);
                    ++joystick_index;
                }
            }
            SDL_assert(joystick_index == total_joysticks);
            joysticks[joystick_index] = 0;
        } else {
            if (count) {
                *count = 0;
            }
        }
    }
    SDL_UnlockJoysticks();
    return joysticks;
}
References count, SDL_arraysize, SDL_assert, SDL_joystick_drivers, SDL_LockJoysticks(), SDL_malloc(), and SDL_UnlockJoysticks().
Referenced by PushMappingChangeTracking(), SDL_GetGamepads(), SDL_HasGamepad(), SDL_InitGamepads(), and SDL_QuitJoysticks().
SDL_GetJoystickSerial()
SDL_DECLSPEC const char *SDLCALL SDL_GetJoystickSerial (SDL_Joystick * joystick) extern
Get the serial number of an opened joystick, if available.
Returns the serial number of the joystick, or NULL if it is not available.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the serial number of the selected joystick, or NULL if unavailable.
Since
This function is available since SDL 3.2.0.
{
    const char *result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, NULL);
        result = SDL_GetPersistentString(joystick->serial);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, NULL, SDL_GetPersistentString(), SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GetGamepadSerial().
SDL_GetJoystickType()
SDL_DECLSPEC SDL_JoystickType SDLCALL SDL_GetJoystickType (SDL_Joystick * joystick) extern
Get the type of an opened joystick.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the SDL_JoystickType of the selected joystick.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickTypeForID
{
    SDL_JoystickType type;
    SDL_GUID guid = SDL_GetJoystickGUID(joystick);
    type = SDL_GetJoystickGUIDType(guid);
    if (type == SDL_JOYSTICK_TYPE_UNKNOWN) {
        SDL_LockJoysticks();
        {
            CHECK_JOYSTICK_MAGIC(joystick, SDL_JOYSTICK_TYPE_UNKNOWN);
            if (SDL_IsGamepad(joystick->instance_id)) {
                type = SDL_JOYSTICK_TYPE_GAMEPAD;
            }
        }
        SDL_UnlockJoysticks();
    }
    return type;
}
References CHECK_JOYSTICK_MAGIC, SDL_GetJoystickGUID(), SDL_GetJoystickGUIDType(), SDL_IsGamepad(), SDL_JOYSTICK_TYPE_GAMEPAD, SDL_JOYSTICK_TYPE_UNKNOWN, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetJoystickTypeForID()
SDL_DECLSPEC SDL_JoystickType SDLCALL SDL_GetJoystickTypeForID (SDL_JoystickID instance_id) extern
Get the type of a joystick, if available.
This can be called before any joysticks are opened.
Parameters
instance_id the joystick instance ID.
Returns
the SDL_JoystickType of the selected joystick. If called with an invalid instance_id, this function returns SDL_JOYSTICK_TYPE_UNKNOWN.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickType
SDL_GetJoysticks
{
    SDL_JoystickType type;
    SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
    type = SDL_GetJoystickGUIDType(guid);
    if (type == SDL_JOYSTICK_TYPE_UNKNOWN) {
        if (SDL_IsGamepad(instance_id)) {
            type = SDL_JOYSTICK_TYPE_GAMEPAD;
        }
    }
    return type;
}
References SDL_GetJoystickGUIDForID(), SDL_GetJoystickGUIDType(), SDL_IsGamepad(), SDL_JOYSTICK_TYPE_GAMEPAD, and SDL_JOYSTICK_TYPE_UNKNOWN.
SDL_GetJoystickVendor()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickVendor (SDL_Joystick * joystick) extern
Get the USB vendor ID of an opened joystick, if available.
If the vendor ID isn't available this function returns 0.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
Returns
the USB vendor ID of the selected joystick, or 0 if unavailable.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickVendorForID
{
    Uint16 vendor;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, 0);
        info = SDL_GetJoystickVirtualGamepadInfoForID(joystick->instance_id);
        if (info) {
            vendor = info->vendor_id;
        } else {
            SDL_GUID guid = SDL_GetJoystickGUID(joystick);
            SDL_GetJoystickGUIDInfo(guid, &vendor, NULL, NULL, NULL);
        }
    }
    SDL_UnlockJoysticks();
    return vendor;
}
References CHECK_JOYSTICK_MAGIC, NULL, SDL_GetJoystickGUID(), SDL_GetJoystickGUIDInfo(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_SteamVirtualGamepadInfo::vendor_id.
Referenced by SDL_GetGamepadVendor(), SDL_JoystickAxesCenteredAtZero(), and SDL_OpenHapticFromJoystick().
SDL_GetJoystickVendorForID()
SDL_DECLSPEC Uint16 SDLCALL SDL_GetJoystickVendorForID (SDL_JoystickID instance_id) extern
Get the USB vendor ID of a joystick, if available.
This can be called before any joysticks are opened. If the vendor ID isn't available this function returns 0.
Parameters
instance_id the joystick instance ID.
Returns
the USB vendor ID of the selected joystick. If called with an invalid instance_id, this function returns 0.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickVendor
SDL_GetJoysticks
{
    Uint16 vendor;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    info = SDL_GetJoystickVirtualGamepadInfoForID(instance_id);
    if (info) {
        vendor = info->vendor_id;
    } else {
        SDL_GUID guid = SDL_GetJoystickGUIDForID(instance_id);
        SDL_GetJoystickGUIDInfo(guid, &vendor, NULL, NULL, NULL);
    }
    SDL_UnlockJoysticks();
    return vendor;
}
References NULL, SDL_GetJoystickGUIDForID(), SDL_GetJoystickGUIDInfo(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_SteamVirtualGamepadInfo::vendor_id.
Referenced by SDL_GetGamepadVendorForID().
SDL_GetNumJoystickAxes()
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickAxes (SDL_Joystick * joystick) extern
Get the number of general axis controls on a joystick.
Often, the directional pad on a game controller will either look like 4 separate buttons or a POV hat, and not axes, but all of this is up to the device and platform.
Parameters
joystick an SDL_Joystick structure containing joystick information.
Returns
the number of axis controls/number of axes on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickAxis
SDL_GetNumJoystickBalls
SDL_GetNumJoystickButtons
SDL_GetNumJoystickHats
{
    int result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, -1);
        result = joystick->naxes;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_OpenHapticFromJoystick().
SDL_GetNumJoystickBalls()
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickBalls (SDL_Joystick * joystick) extern
Get the number of trackballs on a joystick.
Joystick trackballs have only relative motion events associated with them and their state cannot be polled.
Most joysticks do not have trackballs.
Parameters
joystick an SDL_Joystick structure containing joystick information.
Returns
the number of trackballs on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickBall
SDL_GetNumJoystickAxes
SDL_GetNumJoystickButtons
SDL_GetNumJoystickHats
{
    CHECK_JOYSTICK_MAGIC(joystick, -1);
    return joystick->nballs;
}
References CHECK_JOYSTICK_MAGIC.
SDL_GetNumJoystickButtons()
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickButtons (SDL_Joystick * joystick) extern
Get the number of buttons on a joystick.
Parameters
joystick an SDL_Joystick structure containing joystick information.
Returns
the number of buttons on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickButton
SDL_GetNumJoystickAxes
SDL_GetNumJoystickBalls
SDL_GetNumJoystickHats
{
    int result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, -1);
        result = joystick->nbuttons;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_GetNumJoystickHats()
SDL_DECLSPEC int SDLCALL SDL_GetNumJoystickHats (SDL_Joystick * joystick) extern
Get the number of POV hats on a joystick.
Parameters
joystick an SDL_Joystick structure containing joystick information.
Returns
the number of POV hats on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickHat
SDL_GetNumJoystickAxes
SDL_GetNumJoystickBalls
SDL_GetNumJoystickButtons
{
    int result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, -1);
        result = joystick->nhats;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_HasJoystick()
SDL_DECLSPEC bool SDLCALL SDL_HasJoystick (void) extern
Return whether a joystick is currently connected.
Returns
true if a joystick is connected, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoysticks
{
    int i;
    int total_joysticks = 0;
    SDL_LockJoysticks();
    {
        for (i = 0; i < SDL_arraysize(SDL_joystick_drivers); ++i) {
            total_joysticks += SDL_joystick_drivers[i]->GetCount();
        }
    }
    SDL_UnlockJoysticks();
    if (total_joysticks > 0) {
        return true;
    }
    return false;
}
References SDL_arraysize, SDL_joystick_drivers, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
SDL_IsJoystickVirtual()
SDL_DECLSPEC bool SDLCALL SDL_IsJoystickVirtual (SDL_JoystickID instance_id) extern
Query whether or not a joystick is virtual.
Parameters
instance_id the joystick instance ID.
Returns
true if the joystick is virtual, false otherwise.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_JOYSTICK_VIRTUAL
    SDL_JoystickDriver *driver;
    int device_index;
    bool is_virtual = false;
    SDL_LockJoysticks();
    if (SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        if (driver == &SDL_VIRTUAL_JoystickDriver) {
            is_virtual = true;
        }
    }
    SDL_UnlockJoysticks();
    return is_virtual;
#else
    return false;
#endif
}
References SDL_GetDriverAndJoystickIndex(), SDL_LockJoysticks(), SDL_UnlockJoysticks(), and SDL_VIRTUAL_JoystickDriver.
SDL_JoystickConnected()
SDL_DECLSPEC bool SDLCALL SDL_JoystickConnected (SDL_Joystick * joystick) extern
Get the status of a specified joystick.
Parameters
joystick the joystick to query.
Returns
true if the joystick has been opened, false if it has not; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        result = joystick->attached;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_GamepadConnected().
SDL_JoystickEventsEnabled()
SDL_DECLSPEC bool SDLCALL SDL_JoystickEventsEnabled (void) extern
Query the state of joystick event processing.
If joystick events are disabled, you must call SDL_UpdateJoysticks() yourself and check the state of the joystick when you want joystick information.
Returns
true if joystick events are being processed, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetJoystickEventsEnabled
{
    bool enabled = false;
    unsigned int i;
    for (i = 0; i < SDL_arraysize(SDL_joystick_event_list); ++i) {
        enabled = SDL_EventEnabled(SDL_joystick_event_list[i]);
        if (enabled) {
            break;
        }
    }
    return enabled;
}
References SDL_arraysize, SDL_EventEnabled(), and SDL_joystick_event_list.
SDL_LockJoysticks()
SDL_DECLSPEC void SDLCALL SDL_LockJoysticks (void) extern
Locking for atomic access to the joystick API.
The SDL joystick functions are thread-safe, however you can lock the joysticks while processing to guarantee that the joystick list won't change and joystick and gamepad events will not be delivered.
Since
This function is available since SDL 3.2.0.
{
    (void)SDL_AtomicIncRef(&SDL_joystick_lock_pending);
    SDL_LockMutex(SDL_joystick_lock);
    (void)SDL_AtomicDecRef(&SDL_joystick_lock_pending);
    ++SDL_joysticks_locked;
}
References SDL_AtomicDecRef, SDL_AtomicIncRef, SDL_joystick_lock, SDL_joystick_lock_pending, SDL_joysticks_locked, SDL_LockMutex(), and void().
Referenced by SDL_AddGamepadMapping(), SDL_AddGamepadMappingsFromIO(), SDL_AttachVirtualJoystick(), SDL_CloseGamepad(), SDL_CloseJoystick(), SDL_DetachVirtualJoystick(), SDL_GamepadHasAxis(), SDL_GamepadHasButton(), SDL_GamepadHasSensor(), SDL_GamepadSensorEnabled(), SDL_GamepadSensorWatcher(), SDL_GetGamepadAppleSFSymbolsNameForAxis(), SDL_GetGamepadAppleSFSymbolsNameForButton(), SDL_GetGamepadAxis(), SDL_GetGamepadBindings(), SDL_GetGamepadButton(), SDL_GetGamepadButtonLabel(), SDL_GetGamepadFromID(), SDL_GetGamepadFromPlayerIndex(), SDL_GetGamepadJoystick(), SDL_GetGamepadMapping(), SDL_GetGamepadMappingForGUID(), SDL_GetGamepadMappingForID(), SDL_GetGamepadMappings(), SDL_GetGamepadName(), SDL_GetGamepadNameForID(), SDL_GetGamepadProperties(), SDL_GetGamepadSensorData(), SDL_GetGamepadSensorDataRate(), SDL_GetGamepadSteamHandle(), SDL_GetGamepadTouchpadFinger(), SDL_GetGamepadType(), SDL_GetGamepadTypeForID(), SDL_GetJoystickAxis(), SDL_GetJoystickAxisInitialState(), SDL_GetJoystickBall(), SDL_GetJoystickButton(), SDL_GetJoystickConnectionState(), SDL_GetJoystickFirmwareVersion(), SDL_GetJoystickFromID(), SDL_GetJoystickFromPlayerIndex(), SDL_GetJoystickGUID(), SDL_GetJoystickGUIDForID(), SDL_GetJoystickHat(), SDL_GetJoystickID(), SDL_GetJoystickName(), SDL_GetJoystickNameForID(), SDL_GetJoystickPath(), SDL_GetJoystickPathForID(), SDL_GetJoystickPlayerIndex(), SDL_GetJoystickPlayerIndexForID(), SDL_GetJoystickPowerInfo(), SDL_GetJoystickProduct(), SDL_GetJoystickProductForID(), SDL_GetJoystickProperties(), SDL_GetJoysticks(), SDL_GetJoystickSerial(), SDL_GetJoystickType(), SDL_GetJoystickVendor(), SDL_GetJoystickVendorForID(), SDL_GetNumGamepadTouchpadFingers(), SDL_GetNumGamepadTouchpads(), SDL_GetNumJoystickAxes(), SDL_GetNumJoystickButtons(), SDL_GetNumJoystickHats(), SDL_GetRealGamepadTypeForID(), SDL_HasJoystick(), SDL_InitJoysticks(), SDL_IsGamepad(), SDL_IsGamepadNameAndGUID(), SDL_IsJoystickHaptic(), SDL_IsJoystickVirtual(), SDL_JoystickConnected(), SDL_JoystickHandledByAnotherDriver(), SDL_JoysticksOpened(), SDL_OpenGamepad(), SDL_OpenHapticFromJoystick(), SDL_OpenJoystick(), SDL_PrivateJoystickGetAutoGamepadMapping(), SDL_QuitGamepads(), SDL_QuitJoysticks(), SDL_ReloadGamepadMappings(), SDL_RumbleJoystick(), SDL_RumbleJoystickTriggers(), SDL_SendJoystickEffect(), SDL_SendJoystickVirtualSensorData(), SDL_SetGamepadMapping(), SDL_SetGamepadSensorEnabled(), SDL_SetJoystickLED(), SDL_SetJoystickPlayerIndex(), SDL_SetJoystickVirtualAxis(), SDL_SetJoystickVirtualBall(), SDL_SetJoystickVirtualButton(), SDL_SetJoystickVirtualHat(), SDL_SetJoystickVirtualTouchpad(), and SDL_UpdateJoysticks().
SDL_OpenJoystick()
SDL_DECLSPEC SDL_Joystick *SDLCALL SDL_OpenJoystick (SDL_JoystickID instance_id) extern
Open a joystick for use.
The joystick subsystem must be initialized before a joystick can be opened for use.
Parameters
instance_id the joystick instance ID.
Returns
a joystick identifier or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseJoystick
{
    SDL_JoystickDriver *driver;
    int device_index;
    SDL_Joystick *joystick;
    SDL_Joystick *joysticklist;
    const char *joystickname = NULL;
    const char *joystickpath = NULL;
    bool invert_sensors = false;
    const SDL_SteamVirtualGamepadInfo *info;
    SDL_LockJoysticks();
    if (!SDL_GetDriverAndJoystickIndex(instance_id, &driver, &device_index)) {
        SDL_UnlockJoysticks();
        return NULL;
    }
    joysticklist = SDL_joysticks;
    /* If the joystick is already open, return it
     * it is important that we have a single joystick for each instance id
     */
    while (joysticklist) {
        if (instance_id == joysticklist->instance_id) {
            joystick = joysticklist;
            ++joystick->ref_count;
            SDL_UnlockJoysticks();
            return joystick;
        }
        joysticklist = joysticklist->next;
    }
    // Create and initialize the joystick
    joystick = (SDL_Joystick *)SDL_calloc(1, sizeof(*joystick));
    if (!joystick) {
        SDL_UnlockJoysticks();
        return NULL;
    }
    SDL_SetObjectValid(joystick, SDL_OBJECT_TYPE_JOYSTICK, true);
    joystick->driver = driver;
    joystick->instance_id = instance_id;
    joystick->attached = true;
    joystick->led_expiration = SDL_GetTicks();
    joystick->battery_percent = -1;
#ifdef SDL_JOYSTICK_VIRTUAL
    joystick->is_virtual = (driver == &SDL_VIRTUAL_JoystickDriver);
#endif
    if (!driver->Open(joystick, device_index)) {
        SDL_SetObjectValid(joystick, SDL_OBJECT_TYPE_JOYSTICK, false);
        SDL_free(joystick);
        SDL_UnlockJoysticks();
        return NULL;
    }
    joystickname = driver->GetDeviceName(device_index);
    if (joystickname) {
        joystick->name = SDL_strdup(joystickname);
    }
    joystickpath = driver->GetDevicePath(device_index);
    if (joystickpath) {
        joystick->path = SDL_strdup(joystickpath);
    }
    joystick->guid = driver->GetDeviceGUID(device_index);
    if (joystick->naxes > 0) {
        joystick->axes = (SDL_JoystickAxisInfo *)SDL_calloc(joystick->naxes, sizeof(*joystick->axes));
    }
    if (joystick->nballs > 0) {
        joystick->balls = (SDL_JoystickBallData *)SDL_calloc(joystick->nballs, sizeof(*joystick->balls));
    }
    if (joystick->nhats > 0) {
        joystick->hats = (Uint8 *)SDL_calloc(joystick->nhats, sizeof(*joystick->hats));
    }
    if (joystick->nbuttons > 0) {
        joystick->buttons = (bool *)SDL_calloc(joystick->nbuttons, sizeof(*joystick->buttons));
    }
    if (((joystick->naxes > 0) && !joystick->axes) ||
        ((joystick->nballs > 0) && !joystick->balls) ||
        ((joystick->nhats > 0) && !joystick->hats) ||
        ((joystick->nbuttons > 0) && !joystick->buttons)) {
        SDL_CloseJoystick(joystick);
        SDL_UnlockJoysticks();
        return NULL;
    }
    // If this joystick is known to have all zero centered axes, skip the auto-centering code
    if (SDL_JoystickAxesCenteredAtZero(joystick)) {
        for (int i = 0; i < joystick->naxes; ++i) {
            joystick->axes[i].has_initial_value = true;
        }
    }
    // We know the initial values for HIDAPI and XInput joysticks
    if ((SDL_IsJoystickHIDAPI(joystick->guid) ||
         SDL_IsJoystickXInput(joystick->guid) ||
         SDL_IsJoystickRAWINPUT(joystick->guid) ||
         SDL_IsJoystickWGI(joystick->guid)) &&
        joystick->naxes >= SDL_GAMEPAD_AXIS_COUNT) {
        int left_trigger, right_trigger;
        if (SDL_IsJoystickXInput(joystick->guid)) {
            left_trigger = 2;
            right_trigger = 5;
        } else {
            left_trigger = SDL_GAMEPAD_AXIS_LEFT_TRIGGER;
            right_trigger = SDL_GAMEPAD_AXIS_RIGHT_TRIGGER;
        }
        for (int i = 0; i < SDL_GAMEPAD_AXIS_COUNT; ++i) {
            int initial_value;
            if (i == left_trigger || i == right_trigger) {
                initial_value = SDL_MIN_SINT16;
            } else {
                initial_value = 0;
            }
            joystick->axes[i].value = initial_value;
            joystick->axes[i].zero = initial_value;
            joystick->axes[i].initial_value = initial_value;
            joystick->axes[i].has_initial_value = true;
        }
    }
    // Get the Steam Input API handle
    info = SDL_GetJoystickVirtualGamepadInfoForID(instance_id);
    if (info) {
        joystick->steam_handle = info->handle;
        joystick->swap_face_buttons = ShouldSwapFaceButtons(info);
    }
    // Use system gyro and accelerometer if the gamepad doesn't have built-in sensors
    if (ShouldAttemptSensorFusion(joystick, &invert_sensors)) {
        AttemptSensorFusion(joystick, invert_sensors);
    }
    // Add joystick to list
    ++joystick->ref_count;
    // Link the joystick in the list
    joystick->next = SDL_joysticks;
    SDL_joysticks = joystick;
    driver->Update(joystick);
    SDL_UnlockJoysticks();
    return joystick;
}
References AttemptSensorFusion(), SDL_JoystickDriver::GetDeviceGUID, SDL_JoystickDriver::GetDeviceName, SDL_JoystickDriver::GetDevicePath, SDL_SteamVirtualGamepadInfo::handle, NULL, SDL_JoystickDriver::Open, SDL_calloc(), SDL_CloseJoystick(), SDL_free(), SDL_GAMEPAD_AXIS_COUNT, SDL_GAMEPAD_AXIS_LEFT_TRIGGER, SDL_GAMEPAD_AXIS_RIGHT_TRIGGER, SDL_GetDriverAndJoystickIndex(), SDL_GetJoystickVirtualGamepadInfoForID(), SDL_GetTicks(), SDL_IsJoystickHIDAPI(), SDL_IsJoystickRAWINPUT(), SDL_IsJoystickWGI(), SDL_IsJoystickXInput(), SDL_JoystickAxesCenteredAtZero(), SDL_LockJoysticks(), SDL_MIN_SINT16, SDL_OBJECT_TYPE_JOYSTICK, SDL_SetObjectValid(), SDL_strdup(), SDL_UnlockJoysticks(), SDL_VIRTUAL_JoystickDriver, ShouldAttemptSensorFusion(), ShouldSwapFaceButtons(), and SDL_JoystickDriver::Update.
Referenced by SDL_OpenGamepad().
SDL_RumbleJoystick()
SDL_DECLSPEC bool SDLCALL SDL_RumbleJoystick (SDL_Joystick * joystick, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms) extern
Start a rumble effect.
Each call to this function cancels any previous rumble effect, and calling it with 0 intensity stops any rumbling.
This function requires you to process SDL events or call SDL_UpdateJoysticks() to update rumble state.
Parameters
joystick the joystick to vibrate.
low_frequency_rumble the intensity of the low frequency (left) rumble motor, from 0 to 0xFFFF.
high_frequency_rumble the intensity of the high frequency (right) rumble motor, from 0 to 0xFFFF.
duration_ms the duration of the rumble effect, in milliseconds.
Returns
true, or false if rumble isn't supported on this joystick.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        if (low_frequency_rumble == joystick->low_frequency_rumble &&
            high_frequency_rumble == joystick->high_frequency_rumble) {
            // Just update the expiration
            result = true;
        } else {
            result = joystick->driver->Rumble(joystick, low_frequency_rumble, high_frequency_rumble);
            if (result) {
                joystick->rumble_resend = SDL_GetTicks() + SDL_RUMBLE_RESEND_MS;
                if (joystick->rumble_resend == 0) {
                    joystick->rumble_resend = 1;
                }
            } else {
                joystick->rumble_resend = 0;
            }
        }
        if (result) {
            joystick->low_frequency_rumble = low_frequency_rumble;
            joystick->high_frequency_rumble = high_frequency_rumble;
            if ((low_frequency_rumble || high_frequency_rumble) && duration_ms) {
                joystick->rumble_expiration = SDL_GetTicks() + SDL_min(duration_ms, SDL_MAX_RUMBLE_DURATION_MS);
                if (!joystick->rumble_expiration) {
                    joystick->rumble_expiration = 1;
                }
            } else {
                joystick->rumble_expiration = 0;
                joystick->rumble_resend = 0;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_GetTicks(), SDL_LockJoysticks(), SDL_MAX_RUMBLE_DURATION_MS, SDL_min, SDL_RUMBLE_RESEND_MS, and SDL_UnlockJoysticks().
Referenced by SDL_CloseJoystick(), SDL_RumbleGamepad(), and SDL_UpdateJoysticks().
SDL_RumbleJoystickTriggers()
SDL_DECLSPEC bool SDLCALL SDL_RumbleJoystickTriggers (SDL_Joystick * joystick, Uint16 left_rumble, Uint16 right_rumble, Uint32 duration_ms) extern
Start a rumble effect in the joystick's triggers.
Each call to this function cancels any previous trigger rumble effect, and calling it with 0 intensity stops any rumbling.
Note that this is rumbling of the triggers and not the game controller as a whole. This is currently only supported on Xbox One controllers. If you want the (more common) whole-controller rumble, use SDL_RumbleJoystick() instead.
This function requires you to process SDL events or call SDL_UpdateJoysticks() to update rumble state.
Parameters
joystick the joystick to vibrate.
left_rumble the intensity of the left trigger rumble motor, from 0 to 0xFFFF.
right_rumble the intensity of the right trigger rumble motor, from 0 to 0xFFFF.
duration_ms the duration of the rumble effect, in milliseconds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_RumbleJoystick
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        if (left_rumble == joystick->left_trigger_rumble && right_rumble == joystick->right_trigger_rumble) {
            // Just update the expiration
            result = true;
        } else {
            result = joystick->driver->RumbleTriggers(joystick, left_rumble, right_rumble);
            if (result) {
                joystick->trigger_rumble_resend = SDL_GetTicks() + SDL_RUMBLE_RESEND_MS;
                if (joystick->trigger_rumble_resend == 0) {
                    joystick->trigger_rumble_resend = 1;
                }
            } else {
                joystick->trigger_rumble_resend = 0;
            }
        }
        if (result) {
            joystick->left_trigger_rumble = left_rumble;
            joystick->right_trigger_rumble = right_rumble;
            if ((left_rumble || right_rumble) && duration_ms) {
                joystick->trigger_rumble_expiration = SDL_GetTicks() + SDL_min(duration_ms, SDL_MAX_RUMBLE_DURATION_MS);
            } else {
                joystick->trigger_rumble_expiration = 0;
                joystick->trigger_rumble_resend = 0;
            }
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_GetTicks(), SDL_LockJoysticks(), SDL_MAX_RUMBLE_DURATION_MS, SDL_min, SDL_RUMBLE_RESEND_MS, and SDL_UnlockJoysticks().
Referenced by SDL_CloseJoystick(), SDL_RumbleGamepadTriggers(), and SDL_UpdateJoysticks().
SDL_SendJoystickEffect()
SDL_DECLSPEC bool SDLCALL SDL_SendJoystickEffect (SDL_Joystick * joystick, const void * data, int size) extern
Send a joystick specific effect packet.
Parameters
joystick the joystick to affect.
data the data to send to the joystick.
size the size of the data to send to the joystick.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        result = joystick->driver->SendEffect(joystick, data, size);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_SendGamepadEffect().
SDL_SendJoystickVirtualSensorData()
SDL_DECLSPEC bool SDLCALL SDL_SendJoystickVirtualSensorData (SDL_Joystick * joystick, SDL_SensorType type, Uint64 sensor_timestamp, const float * data, int num_values) extern
Send a sensor update for an opened virtual joystick.
Please note that values set here will not be applied until the next call to SDL_UpdateJoysticks, which can either be called directly, or can be called indirectly through various other SDL APIs, including, but not limited to the following: SDL_PollEvent, SDL_PumpEvents, SDL_WaitEventTimeout, SDL_WaitEvent.
Parameters
joystick the virtual joystick on which to set state.
type the type of the sensor on the virtual joystick to update.
sensor_timestamp a 64-bit timestamp in nanoseconds associated with the sensor reading.
data the data associated with the sensor reading.
num_values the number of values pointed to by data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        CHECK_JOYSTICK_VIRTUAL(joystick, false);
#ifdef SDL_JOYSTICK_VIRTUAL
        result = SDL_SendJoystickVirtualSensorDataInner(joystick, type, sensor_timestamp, data, num_values);
#else
        result = SDL_SetError("SDL not built with virtual-joystick support");
#endif
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, CHECK_JOYSTICK_VIRTUAL, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_SetJoystickEventsEnabled()
SDL_DECLSPEC void SDLCALL SDL_SetJoystickEventsEnabled (bool enabled) extern
Set the state of joystick event processing.
If joystick events are disabled, you must call SDL_UpdateJoysticks() yourself and check the state of the joystick when you want joystick information.
Parameters
enabled whether to process joystick events or not.
Since
This function is available since SDL 3.2.0.
See also
SDL_JoystickEventsEnabled
SDL_UpdateJoysticks
{
    unsigned int i;
    for (i = 0; i < SDL_arraysize(SDL_joystick_event_list); ++i) {
        SDL_SetEventEnabled(SDL_joystick_event_list[i], enabled);
    }
}
References SDL_arraysize, SDL_joystick_event_list, and SDL_SetEventEnabled().
SDL_SetJoystickLED()
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickLED (SDL_Joystick * joystick, Uint8 red, Uint8 green, Uint8 blue) extern
Update a joystick's LED color.
An example of a joystick LED is the light on the back of a PlayStation 4's DualShock 4 controller.
For joysticks with a single color LED, the maximum of the RGB values will be used as the LED brightness.
Parameters
joystick the joystick to update.
red the intensity of the red LED.
green the intensity of the green LED.
blue the intensity of the blue LED.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    bool isfreshvalue;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        isfreshvalue = red != joystick->led_red ||
                       green != joystick->led_green ||
                       blue != joystick->led_blue;
        if (isfreshvalue || SDL_GetTicks() >= joystick->led_expiration) {
            result = joystick->driver->SetLED(joystick, red, green, blue);
            joystick->led_expiration = SDL_GetTicks() + SDL_LED_MIN_REPEAT_MS;
        } else {
            // Avoid spamming the driver
            result = true;
        }
        // Save the LED value regardless of success, so we don't spam the driver
        joystick->led_red = red;
        joystick->led_green = green;
        joystick->led_blue = blue;
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_GetTicks(), SDL_LED_MIN_REPEAT_MS, SDL_LockJoysticks(), and SDL_UnlockJoysticks().
Referenced by SDL_SetGamepadLED().
SDL_SetJoystickPlayerIndex()
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickPlayerIndex (SDL_Joystick * joystick, int player_index) extern
Set the player index of an opened joystick.
Parameters
joystick the SDL_Joystick obtained from SDL_OpenJoystick().
player_index player index to assign to this joystick, or -1 to clear the player index and turn off player LEDs.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetJoystickPlayerIndex
Set the player index of an opened joystick
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        result = SDL_SetJoystickIDForPlayerIndex(player_index, joystick->instance_id);
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, SDL_LockJoysticks(), SDL_SetJoystickIDForPlayerIndex(), and SDL_UnlockJoysticks().
Referenced by SDL_SetGamepadPlayerIndex().
SDL_SetJoystickVirtualAxis()
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualAxis (SDL_Joystick * joystick, int axis, Sint16 value) extern
Set the state of an axis on an opened virtual joystick.
Please note that values set here will not be applied until the next call to SDL_UpdateJoysticks, which can either be called directly, or can be called indirectly through various other SDL APIs, including, but not limited to the following: SDL_PollEvent, SDL_PumpEvents, SDL_WaitEventTimeout, SDL_WaitEvent.
Note that when sending trigger axes, you should scale the value to the full range of Sint16. For example, a trigger at rest would have the value of SDL_JOYSTICK_AXIS_MIN.
Parameters
joystick the virtual joystick on which to set state.
axis the index of the axis on the virtual joystick to update.
value the new value for the specified axis.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        CHECK_JOYSTICK_VIRTUAL(joystick, false);
#ifdef SDL_JOYSTICK_VIRTUAL
        result = SDL_SetJoystickVirtualAxisInner(joystick, axis, value);
#else
        result = SDL_SetError("SDL not built with virtual-joystick support");
#endif
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, CHECK_JOYSTICK_VIRTUAL, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_SetJoystickVirtualBall()
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualBall (SDL_Joystick * joystick, int ball, Sint16 xrel, Sint16 yrel) extern
Generate ball motion on an opened virtual joystick.
Please note that values set here will not be applied until the next call to SDL_UpdateJoysticks, which can either be called directly, or can be called indirectly through various other SDL APIs, including, but not limited to the following: SDL_PollEvent, SDL_PumpEvents, SDL_WaitEventTimeout, SDL_WaitEvent.
Parameters
joystick the virtual joystick on which to set state.
ball the index of the ball on the virtual joystick to update.
xrel the relative motion on the X axis.
yrel the relative motion on the Y axis.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        CHECK_JOYSTICK_VIRTUAL(joystick, false);
#ifdef SDL_JOYSTICK_VIRTUAL
        result = SDL_SetJoystickVirtualBallInner(joystick, ball, xrel, yrel);
#else
        result = SDL_SetError("SDL not built with virtual-joystick support");
#endif
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, CHECK_JOYSTICK_VIRTUAL, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_SetJoystickVirtualButton()
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualButton (SDL_Joystick * joystick, int button, bool down) extern
Set the state of a button on an opened virtual joystick.
Please note that values set here will not be applied until the next call to SDL_UpdateJoysticks, which can either be called directly, or can be called indirectly through various other SDL APIs, including, but not limited to the following: SDL_PollEvent, SDL_PumpEvents, SDL_WaitEventTimeout, SDL_WaitEvent.
Parameters
joystick the virtual joystick on which to set state.
button the index of the button on the virtual joystick to update.
down true if the button is pressed, false otherwise.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        CHECK_JOYSTICK_VIRTUAL(joystick, false);
#ifdef SDL_JOYSTICK_VIRTUAL
        result = SDL_SetJoystickVirtualButtonInner(joystick, button, down);
#else
        result = SDL_SetError("SDL not built with virtual-joystick support");
#endif
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, CHECK_JOYSTICK_VIRTUAL, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_SetJoystickVirtualHat()
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualHat (SDL_Joystick * joystick, int hat, Uint8 value) extern
Set the state of a hat on an opened virtual joystick.
Please note that values set here will not be applied until the next call to SDL_UpdateJoysticks, which can either be called directly, or can be called indirectly through various other SDL APIs, including, but not limited to the following: SDL_PollEvent, SDL_PumpEvents, SDL_WaitEventTimeout, SDL_WaitEvent.
Parameters
joystick the virtual joystick on which to set state.
hat the index of the hat on the virtual joystick to update.
value the new value for the specified hat.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        CHECK_JOYSTICK_VIRTUAL(joystick, false);
#ifdef SDL_JOYSTICK_VIRTUAL
        result = SDL_SetJoystickVirtualHatInner(joystick, hat, value);
#else
        result = SDL_SetError("SDL not built with virtual-joystick support");
#endif
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, CHECK_JOYSTICK_VIRTUAL, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_SetJoystickVirtualTouchpad()
SDL_DECLSPEC bool SDLCALL SDL_SetJoystickVirtualTouchpad (SDL_Joystick * joystick, int touchpad, int finger, bool down, float x, float y, float pressure) extern
Set touchpad finger state on an opened virtual joystick.
Please note that values set here will not be applied until the next call to SDL_UpdateJoysticks, which can either be called directly, or can be called indirectly through various other SDL APIs, including, but not limited to the following: SDL_PollEvent, SDL_PumpEvents, SDL_WaitEventTimeout, SDL_WaitEvent.
Parameters
joystick the virtual joystick on which to set state.
touchpad the index of the touchpad on the virtual joystick to update.
finger the index of the finger on the touchpad to set.
down true if the finger is pressed, false if the finger is released.
x the x coordinate of the finger on the touchpad, normalized 0 to 1, with the origin in the upper left.
y the y coordinate of the finger on the touchpad, normalized 0 to 1, with the origin in the upper left.
pressure the pressure of the finger.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    bool result;
    SDL_LockJoysticks();
    {
        CHECK_JOYSTICK_MAGIC(joystick, false);
        CHECK_JOYSTICK_VIRTUAL(joystick, false);
#ifdef SDL_JOYSTICK_VIRTUAL
        result = SDL_SetJoystickVirtualTouchpadInner(joystick, touchpad, finger, down, x, y, pressure);
#else
        result = SDL_SetError("SDL not built with virtual-joystick support");
#endif
    }
    SDL_UnlockJoysticks();
    return result;
}
References CHECK_JOYSTICK_MAGIC, CHECK_JOYSTICK_VIRTUAL, SDL_LockJoysticks(), SDL_SetError(), and SDL_UnlockJoysticks().
SDL_UnlockJoysticks()
SDL_DECLSPEC void SDLCALL SDL_UnlockJoysticks (void) extern
Unlocking for atomic access to the joystick API.
Since
This function is available since SDL 3.2.0.
{
    bool last_unlock = false;
    --SDL_joysticks_locked;
    if (!SDL_joysticks_initialized) {
        // NOTE: There's a small window here where another thread could lock the mutex after we've checked for pending locks
        if (!SDL_joysticks_locked && SDL_GetAtomicInt(&SDL_joystick_lock_pending) == 0) {
            last_unlock = true;
        }
    }
    /* The last unlock after joysticks are uninitialized will cleanup the mutex,
     * allowing applications to lock joysticks while reinitializing the system.
     */
    if (last_unlock) {
        SDL_Mutex *joystick_lock = SDL_joystick_lock;
        SDL_LockMutex(joystick_lock);
        {
            SDL_UnlockMutex(SDL_joystick_lock);
            SDL_joystick_lock = NULL;
        }
        SDL_UnlockMutex(joystick_lock);
        SDL_DestroyMutex(joystick_lock);
    } else {
        SDL_UnlockMutex(SDL_joystick_lock);
    }
}
References NULL, SDL_DestroyMutex(), SDL_GetAtomicInt(), SDL_joystick_lock, SDL_joystick_lock_pending, SDL_joysticks_initialized, SDL_joysticks_locked, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_AddGamepadMapping(), SDL_AddGamepadMappingsFromIO(), SDL_AttachVirtualJoystick(), SDL_CloseGamepad(), SDL_CloseJoystick(), SDL_DetachVirtualJoystick(), SDL_GamepadHasAxis(), SDL_GamepadHasButton(), SDL_GamepadHasSensor(), SDL_GamepadSensorEnabled(), SDL_GamepadSensorWatcher(), SDL_GetGamepadAppleSFSymbolsNameForAxis(), SDL_GetGamepadAppleSFSymbolsNameForButton(), SDL_GetGamepadAxis(), SDL_GetGamepadBindings(), SDL_GetGamepadButton(), SDL_GetGamepadButtonLabel(), SDL_GetGamepadFromID(), SDL_GetGamepadFromPlayerIndex(), SDL_GetGamepadJoystick(), SDL_GetGamepadMapping(), SDL_GetGamepadMappingForGUID(), SDL_GetGamepadMappingForID(), SDL_GetGamepadMappings(), SDL_GetGamepadName(), SDL_GetGamepadNameForID(), SDL_GetGamepadProperties(), SDL_GetGamepadSensorData(), SDL_GetGamepadSensorDataRate(), SDL_GetGamepadSteamHandle(), SDL_GetGamepadTouchpadFinger(), SDL_GetGamepadType(), SDL_GetGamepadTypeForID(), SDL_GetJoystickAxis(), SDL_GetJoystickAxisInitialState(), SDL_GetJoystickBall(), SDL_GetJoystickButton(), SDL_GetJoystickConnectionState(), SDL_GetJoystickFirmwareVersion(), SDL_GetJoystickFromID(), SDL_GetJoystickFromPlayerIndex(), SDL_GetJoystickGUID(), SDL_GetJoystickGUIDForID(), SDL_GetJoystickHat(), SDL_GetJoystickID(), SDL_GetJoystickName(), SDL_GetJoystickNameForID(), SDL_GetJoystickPath(), SDL_GetJoystickPathForID(), SDL_GetJoystickPlayerIndex(), SDL_GetJoystickPlayerIndexForID(), SDL_GetJoystickPowerInfo(), SDL_GetJoystickProduct(), SDL_GetJoystickProductForID(), SDL_GetJoystickProperties(), SDL_GetJoysticks(), SDL_GetJoystickSerial(), SDL_GetJoystickType(), SDL_GetJoystickVendor(), SDL_GetJoystickVendorForID(), SDL_GetNumGamepadTouchpadFingers(), SDL_GetNumGamepadTouchpads(), SDL_GetNumJoystickAxes(), SDL_GetNumJoystickButtons(), SDL_GetNumJoystickHats(), SDL_GetRealGamepadTypeForID(), SDL_HasJoystick(), SDL_InitJoysticks(), SDL_IsGamepad(), SDL_IsGamepadNameAndGUID(), SDL_IsJoystickHaptic(), SDL_IsJoystickVirtual(), SDL_JoystickConnected(), SDL_JoystickHandledByAnotherDriver(), SDL_JoysticksOpened(), SDL_OpenGamepad(), SDL_OpenHapticFromJoystick(), SDL_OpenJoystick(), SDL_PrivateJoystickGetAutoGamepadMapping(), SDL_QuitGamepads(), SDL_QuitJoysticks(), SDL_ReloadGamepadMappings(), SDL_RumbleJoystick(), SDL_RumbleJoystickTriggers(), SDL_SendJoystickEffect(), SDL_SendJoystickVirtualSensorData(), SDL_SetGamepadMapping(), SDL_SetGamepadSensorEnabled(), SDL_SetJoystickLED(), SDL_SetJoystickPlayerIndex(), SDL_SetJoystickVirtualAxis(), SDL_SetJoystickVirtualBall(), SDL_SetJoystickVirtualButton(), SDL_SetJoystickVirtualHat(), SDL_SetJoystickVirtualTouchpad(), and SDL_UpdateJoysticks().
SDL_UpdateJoysticks()
SDL_DECLSPEC void SDLCALL SDL_UpdateJoysticks (void) extern
Update the current state of the open joysticks.
This is called automatically by the event loop if any joystick events are enabled.
Since
This function is available since SDL 3.2.0.
{
    int i;
    Uint64 now;
    SDL_Joystick *joystick;
    if (!SDL_WasInit(SDL_INIT_JOYSTICK)) {
        return;
    }
    SDL_LockJoysticks();
    if (SDL_UpdateSteamVirtualGamepadInfo()) {
        SendSteamHandleUpdateEvents();
    }
#ifdef SDL_JOYSTICK_HIDAPI
    // Special function for HIDAPI devices, as a single device can provide multiple SDL_Joysticks
    HIDAPI_UpdateDevices();
#endif // SDL_JOYSTICK_HIDAPI
    for (joystick = SDL_joysticks; joystick; joystick = joystick->next) {
        if (!joystick->attached) {
            continue;
        }
        joystick->driver->Update(joystick);
        if (joystick->delayed_guide_button) {
            SDL_GamepadHandleDelayedGuideButton(joystick);
        }
        now = SDL_GetTicks();
        if (joystick->rumble_expiration && now >= joystick->rumble_expiration) {
            SDL_RumbleJoystick(joystick, 0, 0, 0);
            joystick->rumble_resend = 0;
        }
        if (joystick->rumble_resend && now >= joystick->rumble_resend) {
            joystick->driver->Rumble(joystick, joystick->low_frequency_rumble, joystick->high_frequency_rumble);
            joystick->rumble_resend = now + SDL_RUMBLE_RESEND_MS;
            if (joystick->rumble_resend == 0) {
                joystick->rumble_resend = 1;
            }
        }
        if (joystick->trigger_rumble_expiration && now >= joystick->trigger_rumble_expiration) {
            SDL_RumbleJoystickTriggers(joystick, 0, 0, 0);
            joystick->trigger_rumble_resend = 0;
        }
        if (joystick->trigger_rumble_resend && now >= joystick->trigger_rumble_resend) {
            joystick->driver->RumbleTriggers(joystick, joystick->left_trigger_rumble, joystick->right_trigger_rumble);
            joystick->trigger_rumble_resend = now + SDL_RUMBLE_RESEND_MS;
            if (joystick->trigger_rumble_resend == 0) {
                joystick->trigger_rumble_resend = 1;
            }
        }
    }
    if (SDL_EventEnabled(SDL_EVENT_JOYSTICK_UPDATE_COMPLETE)) {
        for (joystick = SDL_joysticks; joystick; joystick = joystick->next) {
            if (joystick->update_complete) {
                SDL_Event event;
                event.type = SDL_EVENT_JOYSTICK_UPDATE_COMPLETE;
                event.common.timestamp = joystick->update_complete;
                event.jdevice.which = joystick->instance_id;
                SDL_PushEvent(&event);
                joystick->update_complete = 0;
            }
        }
    }
    /* this needs to happen AFTER walking the joystick list above, so that any
       dangling hardware data from removed devices can be free'd
     */
    for (i = 0; i < SDL_arraysize(SDL_joystick_drivers); ++i) {
        SDL_joystick_drivers[i]->Detect();
    }
    SDL_UnlockJoysticks();
}
References HIDAPI_UpdateDevices(), SDL_arraysize, SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_EventEnabled(), SDL_GamepadHandleDelayedGuideButton(), SDL_GetTicks(), SDL_INIT_JOYSTICK, SDL_joystick_drivers, SDL_LockJoysticks(), SDL_PushEvent(), SDL_RUMBLE_RESEND_MS, SDL_RumbleJoystick(), SDL_RumbleJoystickTriggers(), SDL_UnlockJoysticks(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_WasInit(), and SendSteamHandleUpdateEvents().
Referenced by SDL_PumpEventMaintenance(), and SDL_UpdateGamepads().