SDL3: SDL-main/include/SDL3/SDL_thread.h File Reference
SDL_thread.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_atomic.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDL_BeginThreadFunction NULL
#define SDL_CreateThread(fn, name, data)
#define SDL_CreateThreadWithProperties(props)
#define SDL_EndThreadFunction NULL
#define SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER "SDL.thread.create.entry_function"
#define SDL_PROP_THREAD_CREATE_NAME_STRING "SDL.thread.create.name"
#define SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER "SDL.thread.create.stacksize"
#define SDL_PROP_THREAD_CREATE_USERDATA_POINTER "SDL.thread.create.userdata"
Typedefs
typedef struct SDL_Thread SDL_Thread
typedef int(SDLCALL * SDL_ThreadFunction) (void *data)
typedef Uint64 SDL_ThreadID
typedef enum SDL_ThreadPriority SDL_ThreadPriority
typedef enum SDL_ThreadState SDL_ThreadState
typedef void(SDLCALL * SDL_TLSDestructorCallback) (void *value)
typedef SDL_AtomicInt SDL_TLSID
Enumerations
enum SDL_ThreadPriority { SDL_THREAD_PRIORITY_LOW , SDL_THREAD_PRIORITY_NORMAL , SDL_THREAD_PRIORITY_HIGH , SDL_THREAD_PRIORITY_TIME_CRITICAL }
enum SDL_ThreadState { SDL_THREAD_UNKNOWN , SDL_THREAD_ALIVE , SDL_THREAD_DETACHED , SDL_THREAD_COMPLETE }
Functions
SDL_DECLSPEC void SDLCALL SDL_CleanupTLS (void)
SDL_DECLSPEC SDL_Thread *SDLCALL SDL_CreateThreadRuntime (SDL_ThreadFunction fn, const char *name, void *data, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
SDL_DECLSPEC SDL_Thread *SDLCALL SDL_CreateThreadWithPropertiesRuntime (SDL_PropertiesID props, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
SDL_DECLSPEC void SDLCALL SDL_DetachThread (SDL_Thread *thread)
SDL_DECLSPEC SDL_ThreadID SDLCALL SDL_GetCurrentThreadID (void)
SDL_DECLSPEC SDL_ThreadID SDLCALL SDL_GetThreadID (SDL_Thread *thread)
SDL_DECLSPEC const char *SDLCALL SDL_GetThreadName (SDL_Thread *thread)
SDL_DECLSPEC SDL_ThreadState SDLCALL SDL_GetThreadState (SDL_Thread *thread)
SDL_DECLSPEC void *SDLCALL SDL_GetTLS (SDL_TLSID *id)
SDL_DECLSPEC bool SDLCALL SDL_SetCurrentThreadPriority (SDL_ThreadPriority priority)
SDL_DECLSPEC bool SDLCALL SDL_SetTLS (SDL_TLSID *id, const void *value, SDL_TLSDestructorCallback destructor)
SDL_DECLSPEC void SDLCALL SDL_WaitThread (SDL_Thread *thread, int *status)
Macro Definition Documentation
SDL_BeginThreadFunction
#define SDL_BeginThreadFunction NULL
SDL_CreateThread
#define SDL_CreateThread (fn, name, data)
Value:
SDL_CreateThreadRuntime((fn), (name), (data), (SDL_FunctionPointer) (SDL_BeginThreadFunction), (SDL_FunctionPointer) (SDL_EndThreadFunction))
Referenced by hidapi_thread_create(), MaybeSpinNewWorkerThread(), OpenPhysicalAudioDevice(), SDL_InitTimers(), SDL_OpenCamera(), SDL_Zenity_ShowFileDialogWithProperties(), ShowFileDialog(), and ShowFolderDialog().
SDL_CreateThreadWithProperties
#define SDL_CreateThreadWithProperties (props)
Value:
SDL_CreateThreadWithPropertiesRuntime((props), (SDL_FunctionPointer) (SDL_BeginThreadFunction), (SDL_FunctionPointer) (SDL_EndThreadFunction))
Referenced by SDL_CreateThreadWithStackSize().
SDL_EndThreadFunction
#define SDL_EndThreadFunction NULL
SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER
#define SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER "SDL.thread.create.entry_function"
Referenced by SDL_CreateThreadRuntime(), SDL_CreateThreadWithPropertiesRuntime(), and SDL_CreateThreadWithStackSize().
SDL_PROP_THREAD_CREATE_NAME_STRING
#define SDL_PROP_THREAD_CREATE_NAME_STRING "SDL.thread.create.name"
Referenced by SDL_CreateThreadRuntime(), SDL_CreateThreadWithPropertiesRuntime(), and SDL_CreateThreadWithStackSize().
SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER
#define SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER "SDL.thread.create.stacksize"
Referenced by SDL_CreateThreadWithPropertiesRuntime(), and SDL_CreateThreadWithStackSize().
SDL_PROP_THREAD_CREATE_USERDATA_POINTER
#define SDL_PROP_THREAD_CREATE_USERDATA_POINTER "SDL.thread.create.userdata"
Referenced by SDL_CreateThreadRuntime(), SDL_CreateThreadWithPropertiesRuntime(), and SDL_CreateThreadWithStackSize().
Typedef Documentation
SDL_Thread
typedef struct SDL_Thread SDL_Thread
CategoryThread
SDL offers cross-platform thread management functions. These are mostly concerned with starting threads, setting their priority, and dealing with their termination.
In addition, there is support for Thread Local Storage (data that is unique to each thread, but accessed from a single key).
On platforms without thread support (such as Emscripten when built without pthreads), these functions still exist, but things like SDL_CreateThread() will report failure without doing anything.
If you're going to work with threads, you almost certainly need to have a good understanding of [CategoryMutex](CategoryMutex) as well. The SDL thread object.
These are opaque data.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_CreateThread
SDL_WaitThread
SDL_ThreadFunction
typedef int(SDLCALL * SDL_ThreadFunction) (void *data)
The function passed to SDL_CreateThread() as the new thread's entry point.
Parameters
data what was passed as data to SDL_CreateThread().
Returns
a value that can be reported through SDL_WaitThread().
Since
This datatype is available since SDL 3.2.0.
SDL_ThreadID
typedef Uint64 SDL_ThreadID
A unique numeric ID that identifies a thread.
These are different from SDL_Thread objects, which are generally what an application will operate on, but having a way to uniquely identify a thread can be useful at times.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_GetThreadID
SDL_GetCurrentThreadID
SDL_ThreadPriority
typedef enum SDL_ThreadPriority SDL_ThreadPriority
The SDL thread priority.
SDL will make system changes as necessary in order to apply the thread priority. Code which attempts to control thread state related to priority should be aware that calling SDL_SetCurrentThreadPriority may alter such state. SDL_HINT_THREAD_PRIORITY_POLICY can be used to control aspects of this behavior.
Since
This enum is available since SDL 3.2.0.
SDL_ThreadState
typedef enum SDL_ThreadState SDL_ThreadState
The SDL thread state.
The current state of a thread can be checked by calling SDL_GetThreadState.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetThreadState
SDL_TLSDestructorCallback
typedef void(SDLCALL * SDL_TLSDestructorCallback) (void *value)
The callback used to cleanup data passed to SDL_SetTLS.
This is called when a thread exits, to allow an app to free any resources.
Parameters
value a pointer previously handed to SDL_SetTLS.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_SetTLS
SDL_TLSID
typedef SDL_AtomicInt SDL_TLSID
Thread local storage ID.
0 is the invalid ID. An app can create these and then set data for these IDs that is unique to each thread.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_GetTLS
SDL_SetTLS
Enumeration Type Documentation
SDL_ThreadPriority
enum SDL_ThreadPriority
The SDL thread priority.
SDL will make system changes as necessary in order to apply the thread priority. Code which attempts to control thread state related to priority should be aware that calling SDL_SetCurrentThreadPriority may alter such state. SDL_HINT_THREAD_PRIORITY_POLICY can be used to control aspects of this behavior.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_THREAD_PRIORITY_LOW
SDL_THREAD_PRIORITY_NORMAL
SDL_THREAD_PRIORITY_HIGH
SDL_THREAD_PRIORITY_TIME_CRITICAL
{
    SDL_THREAD_PRIORITY_LOW,
    SDL_THREAD_PRIORITY_NORMAL,
    SDL_THREAD_PRIORITY_HIGH,
    SDL_THREAD_PRIORITY_TIME_CRITICAL
} SDL_ThreadPriority;
SDL_ThreadState
enum SDL_ThreadState
The SDL thread state.
The current state of a thread can be checked by calling SDL_GetThreadState.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetThreadState
Enumerator
SDL_THREAD_UNKNOWN
The thread is not valid
SDL_THREAD_ALIVE
The thread is currently running
SDL_THREAD_DETACHED
The thread is detached and can't be waited on
SDL_THREAD_COMPLETE
The thread has finished and should be cleaned up with SDL_WaitThread()
{
    SDL_THREAD_UNKNOWN,     /**< The thread is not valid */
    SDL_THREAD_ALIVE,       /**< The thread is currently running */
    SDL_THREAD_DETACHED,    /**< The thread is detached and can't be waited on */
    SDL_THREAD_COMPLETE     /**< The thread has finished and should be cleaned up with SDL_WaitThread() */
} SDL_ThreadState;
Function Documentation
SDL_CleanupTLS()
SDL_DECLSPEC void SDLCALL SDL_CleanupTLS (void) extern
Cleanup all TLS data for this thread.
If you are creating your threads outside of SDL and then calling SDL functions, you should call this function before your thread exits, to properly clean up SDL memory.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_TLSData *storage;
    // Cleanup the storage for the current thread
    storage = SDL_SYS_GetTLSData();
    if (storage) {
        int i;
        for (i = 0; i < storage->limit; ++i) {
            if (storage->array[i].destructor) {
                storage->array[i].destructor(storage->array[i].data);
            }
        }
        SDL_SYS_SetTLSData(NULL);
        SDL_free(storage);
        (void)SDL_AtomicDecRef(&SDL_tls_allocated);
    }
}
References SDL_TLSData::array, SDL_TLSData::data, SDL_TLSData::limit, NULL, SDL_AtomicDecRef, SDL_free(), SDL_SYS_GetTLSData(), SDL_SYS_SetTLSData(), SDL_tls_allocated, and void().
Referenced by SDL_QuitTLSData(), and SDL_RunThread().
SDL_CreateThreadRuntime()
SDL_DECLSPEC SDL_Thread *SDLCALL SDL_CreateThreadRuntime (SDL_ThreadFunction fn, const char * name, void * data, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread) extern
The actual entry point for SDL_CreateThread.
Parameters
fn the SDL_ThreadFunction function to call in the new thread
name the name of the thread
data a pointer that is passed to fn
pfnBeginThread the C runtime's _beginthreadex (or whatnot). Can be NULL.
pfnEndThread the C runtime's _endthreadex (or whatnot). Can be NULL.
Returns
an opaque pointer to the new thread object on success, NULL if the new thread could not be created; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    const SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, (void *) fn);
    SDL_SetStringProperty(props, SDL_PROP_THREAD_CREATE_NAME_STRING, name);
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, userdata);
    SDL_Thread *thread = SDL_CreateThreadWithPropertiesRuntime(props, pfnBeginThread, pfnEndThread);
    SDL_DestroyProperties(props);
    return thread;
}
References SDL_CreateProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_DestroyProperties(), SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, SDL_PROP_THREAD_CREATE_NAME_STRING, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, SDL_SetPointerProperty(), SDL_SetStringProperty(), and SDL_TLSEntry::thread.
SDL_CreateThreadWithPropertiesRuntime()
SDL_DECLSPEC SDL_Thread *SDLCALL SDL_CreateThreadWithPropertiesRuntime (SDL_PropertiesID props, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread) extern
The actual entry point for SDL_CreateThreadWithProperties.
Parameters
props the properties to use
pfnBeginThread the C runtime's _beginthreadex (or whatnot). Can be NULL.
pfnEndThread the C runtime's _endthreadex (or whatnot). Can be NULL.
Returns
an opaque pointer to the new thread object on success, NULL if the new thread could not be created; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    // rather than check this in every backend, just make sure it's correct upfront. Only allow non-NULL if Windows, or Microsoft GDK.
    #if !defined(SDL_PLATFORM_WINDOWS)
    if (pfnBeginThread || pfnEndThread) {
        SDL_SetError("_beginthreadex/_endthreadex not supported on this platform");
        return NULL;
    }
    #endif
    SDL_ThreadFunction fn = (SDL_ThreadFunction) SDL_GetPointerProperty(props, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, NULL);
    const char *name = SDL_GetStringProperty(props, SDL_PROP_THREAD_CREATE_NAME_STRING, NULL);
    const size_t stacksize = (size_t) SDL_GetNumberProperty(props, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, 0);
    void *userdata = SDL_GetPointerProperty(props, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, NULL);
    if (!fn) {
        SDL_SetError("Thread entry function is NULL");
        return NULL;
    }
    SDL_InitMainThread();
    SDL_Thread *thread = (SDL_Thread *)SDL_calloc(1, sizeof(*thread));
    if (!thread) {
        return NULL;
    }
    thread->status = -1;
    SDL_SetAtomicInt(&thread->state, SDL_THREAD_ALIVE);
    // Set up the arguments for the thread
    if (name) {
        thread->name = SDL_strdup(name);
        if (!thread->name) {
            SDL_free(thread);
            return NULL;
        }
    }
    thread->userfunc = fn;
    thread->userdata = userdata;
    thread->stacksize = stacksize;
    SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, true);
    // Create the thread and go!
    if (!SDL_SYS_CreateThread(thread, pfnBeginThread, pfnEndThread)) {
        // Oops, failed.  Gotta free everything
        SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, false);
        SDL_free(thread->name);
        SDL_free(thread);
        thread = NULL;
    }
    // Everything is running now
    return thread;
}
References NULL, SDL_calloc(), SDL_free(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetStringProperty(), SDL_InitMainThread(), SDL_OBJECT_TYPE_THREAD, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, SDL_PROP_THREAD_CREATE_NAME_STRING, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, SDL_SetAtomicInt(), SDL_SetError(), SDL_SetObjectValid(), SDL_strdup(), SDL_SYS_CreateThread(), SDL_THREAD_ALIVE, SDL_Thread::status, and SDL_TLSEntry::thread.
Referenced by SDL_CreateThreadRuntime().
SDL_DetachThread()
SDL_DECLSPEC void SDLCALL SDL_DetachThread (SDL_Thread * thread) extern
Let a thread clean up on exit without intervention.
A thread may be "detached" to signify that it should not remain until another thread has called SDL_WaitThread() on it. Detaching a thread is useful for long-running threads that nothing needs to synchronize with or further manage. When a detached thread is done, it simply goes away.
There is no way to recover the return code of a detached thread. If you need this, don't detach the thread and instead use SDL_WaitThread().
Once a thread is detached, you should usually assume the SDL_Thread isn't safe to reference again, as it will become invalid immediately upon the detached thread's exit, instead of remaining until someone has called SDL_WaitThread() to finally clean it up. As such, don't detach the same thread more than once.
If a thread has already exited when passed to SDL_DetachThread(), it will stop waiting for a call to SDL_WaitThread() and clean up immediately. It is not safe to detach a thread that might be used with SDL_WaitThread().
You may not call SDL_WaitThread() on a thread that has been detached. Use either that function or this one, but not both, or behavior is undefined.
It is safe to pass NULL to this function; it is a no-op.
Parameters
thread the SDL_Thread pointer that was returned from the SDL_CreateThread() call that started this thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateThread
SDL_WaitThread
{
    if (!ThreadValid(thread)) {
        return;
    }
    // The thread may vanish at any time, it's no longer valid
    SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, false);
    // Grab dibs if the state is alive+joinable.
    if (SDL_CompareAndSwapAtomicInt(&thread->state, SDL_THREAD_ALIVE, SDL_THREAD_DETACHED)) {
        SDL_SYS_DetachThread(thread);
    } else {
        // all other states are pretty final, see where we landed.
        SDL_ThreadState thread_state = SDL_GetThreadState(thread);
        if (thread_state == SDL_THREAD_DETACHED) {
            return; // already detached (you shouldn't call this twice!)
        } else if (thread_state == SDL_THREAD_COMPLETE) {
            SDL_WaitThread(thread, NULL); // already done, clean it up.
        }
    }
}
References NULL, SDL_CompareAndSwapAtomicInt(), SDL_GetThreadState(), SDL_OBJECT_TYPE_THREAD, SDL_SetObjectValid(), SDL_SYS_DetachThread(), SDL_THREAD_ALIVE, SDL_THREAD_COMPLETE, SDL_THREAD_DETACHED, SDL_WaitThread(), SDL_TLSEntry::thread, and ThreadValid().
Referenced by MaybeSpinNewWorkerThread(), SDL_Zenity_ShowFileDialogWithProperties(), ShowFileDialog(), and ShowFolderDialog().
SDL_GetCurrentThreadID()
SDL_DECLSPEC SDL_ThreadID SDLCALL SDL_GetCurrentThreadID (void) extern
Get the thread identifier for the current thread.
This thread identifier is as reported by the underlying operating system. If SDL is running on a platform that does not support threads the return value will always be zero.
This function also returns a valid thread ID when called from the main thread.
Returns
the ID of the current thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetThreadID
{
    return 0;
}
Referenced by HIDAPI_InitializeDiscovery(), HIDAPI_UpdateDiscovery(), SDL_CheckInitLog(), SDL_Generic_GetTLSData(), SDL_Generic_SetTLSData(), SDL_GetThreadID(), SDL_InitSubSystem(), SDL_IsMainThread(), SDL_LockMutex(), SDL_LockRWLockForWriting_srw(), SDL_OnVideoThread(), SDL_RunThread(), SDL_SetInitialized(), SDL_SetMainReady(), SDL_ShouldInit(), SDL_ShouldQuit(), SDL_TryLockMutex(), SDL_TryLockRWLockForWriting_srw(), SDL_UnlockMutex(), SDL_UnlockRWLock_srw(), and SDL_VideoInit().
SDL_GetThreadID()
SDL_DECLSPEC SDL_ThreadID SDLCALL SDL_GetThreadID (SDL_Thread * thread) extern
Get the thread identifier for the specified thread.
This thread identifier is as reported by the underlying operating system. If SDL is running on a platform that does not support threads the return value will always be zero.
Parameters
thread the thread to query.
Returns
the ID of the specified thread, or the ID of the current thread if thread is NULL.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCurrentThreadID
{
    SDL_ThreadID id = 0;
    if (thread) {
        if (ThreadValid(thread)) {
            id = thread->threadid;
        }
    } else {
        id = SDL_GetCurrentThreadID();
    }
    return id;
}
References SDL_GetCurrentThreadID(), SDL_TLSEntry::thread, and ThreadValid().
SDL_GetThreadName()
SDL_DECLSPEC const char *SDLCALL SDL_GetThreadName (SDL_Thread * thread) extern
Get the thread name as it was specified in SDL_CreateThread().
Parameters
thread the thread to query.
Returns
a pointer to a UTF-8 string that names the specified thread, or NULL if it doesn't have a name.
Since
This function is available since SDL 3.2.0.
{
    if (ThreadValid(thread)) {
        return SDL_GetPersistentString(thread->name);
    } else {
        return NULL;
    }
}
References NULL, SDL_GetPersistentString(), SDL_TLSEntry::thread, and ThreadValid().
SDL_GetThreadState()
SDL_DECLSPEC SDL_ThreadState SDLCALL SDL_GetThreadState (SDL_Thread * thread) extern
Get the current state of a thread.
Parameters
thread the thread to query.
Returns
the current state of a thread, or SDL_THREAD_UNKNOWN if the thread isn't valid.
Since
This function is available since SDL 3.2.0.
See also
SDL_ThreadState
{
    if (!ThreadValid(thread)) {
        return SDL_THREAD_UNKNOWN;
    }
    return (SDL_ThreadState)SDL_GetAtomicInt(&thread->state);
}
References SDL_GetAtomicInt(), SDL_THREAD_UNKNOWN, SDL_TLSEntry::thread, and ThreadValid().
Referenced by SDL_DetachThread(), and SDL_RunThread().
SDL_GetTLS()
SDL_DECLSPEC void *SDLCALL SDL_GetTLS (SDL_TLSID * id) extern
Get the current thread's value associated with a thread local storage ID.
Parameters
id a pointer to the thread local storage ID, may not be NULL.
Returns
the value associated with the ID for the current thread or NULL if no value has been set; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTLS
{
    SDL_TLSData *storage;
    int storage_index;
    if (id == NULL) {
        SDL_InvalidParamError("id");
        return NULL;
    }
    storage_index = SDL_GetAtomicInt(id) - 1;
    storage = SDL_SYS_GetTLSData();
    if (!storage || storage_index < 0 || storage_index >= storage->limit) {
        return NULL;
    }
    return storage->array[storage_index].data;
}
References SDL_TLSData::array, SDL_TLSData::data, SDL_TLSData::limit, NULL, SDL_GetAtomicInt(), SDL_InvalidParamError, and SDL_SYS_GetTLSData().
Referenced by SDL_GetErrBuf(), SDL_GetPersistentString(), SDL_GetTemporaryMemoryState(), SDL_GL_GetCurrentContext(), and SDL_GL_GetCurrentWindow().
SDL_SetCurrentThreadPriority()
SDL_DECLSPEC bool SDLCALL SDL_SetCurrentThreadPriority (SDL_ThreadPriority priority) extern
Set the priority for the current thread.
Note that some platforms will not let you alter the priority (or at least, promote the thread to a higher priority) at all, and some require you to be an administrator account. Be prepared for this to fail.
Parameters
priority the SDL_ThreadPriority to set.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    return SDL_SYS_SetThreadPriority(priority);
}
References SDL_SYS_SetThreadPriority().
Referenced by SDL_AudioThreadInit_Default(), and SDL_CameraThreadSetup().
SDL_SetTLS()
SDL_DECLSPEC bool SDLCALL SDL_SetTLS (SDL_TLSID * id, const void * value, SDL_TLSDestructorCallback destructor) extern
Set the current thread's value associated with a thread local storage ID.
If the thread local storage ID is not initialized (the value is 0), a new ID will be created in a thread-safe way, so all calls using a pointer to the same ID will refer to the same local storage.
Note that replacing a value from a previous call to this function on the same thread does not call the previous value's destructor!
destructor can be NULL; it is assumed that value does not need to be cleaned up if so.
Parameters
id a pointer to the thread local storage ID, may not be NULL.
value the value to associate with the ID for the current thread.
destructor a function called when the thread exits, to free the value, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTLS
{
    SDL_TLSData *storage;
    int storage_index;
    if (id == NULL) {
        return SDL_InvalidParamError("id");
    }
    /* Make sure TLS is initialized.
     * There's a race condition here if you are calling this from non-SDL threads
     * and haven't called SDL_Init() on your main thread, but such is life.
     */
    SDL_InitTLSData();
    // Get the storage index associated with the ID in a thread-safe way
    storage_index = SDL_GetAtomicInt(id) - 1;
    if (storage_index < 0) {
        int new_id = (SDL_AtomicIncRef(&SDL_tls_id) + 1);
        SDL_CompareAndSwapAtomicInt(id, 0, new_id);
        /* If there was a race condition we'll have wasted an ID, but every thread
         * will have the same storage index for this id.
         */
        storage_index = SDL_GetAtomicInt(id) - 1;
    }
    // Get the storage for the current thread
    storage = SDL_SYS_GetTLSData();
    if (!storage || storage_index >= storage->limit) {
        unsigned int i, oldlimit, newlimit;
        SDL_TLSData *new_storage;
        oldlimit = storage ? storage->limit : 0;
        newlimit = (storage_index + TLS_ALLOC_CHUNKSIZE);
        new_storage = (SDL_TLSData *)SDL_realloc(storage, sizeof(*storage) + (newlimit - 1) * sizeof(storage->array[0]));
        if (!new_storage) {
            return false;
        }
        storage = new_storage;
        storage->limit = newlimit;
        for (i = oldlimit; i < newlimit; ++i) {
            storage->array[i].data = NULL;
            storage->array[i].destructor = NULL;
        }
        if (!SDL_SYS_SetTLSData(storage)) {
            SDL_free(storage);
            return false;
        }
        SDL_AtomicIncRef(&SDL_tls_allocated);
    }
    storage->array[storage_index].data = SDL_const_cast(void *, value);
    storage->array[storage_index].destructor = destructor;
    return true;
}
References SDL_TLSData::array, SDL_TLSData::data, SDL_TLSData::limit, NULL, SDL_AtomicIncRef, SDL_CompareAndSwapAtomicInt(), SDL_const_cast, SDL_free(), SDL_GetAtomicInt(), SDL_InitTLSData(), SDL_InvalidParamError, SDL_realloc(), SDL_SYS_GetTLSData(), SDL_SYS_SetTLSData(), SDL_tls_allocated, SDL_tls_id, and TLS_ALLOC_CHUNKSIZE.
Referenced by SDL_GetErrBuf(), SDL_GetPersistentString(), SDL_GetTemporaryMemoryState(), SDL_GL_CreateContext(), and SDL_GL_MakeCurrent().
SDL_WaitThread()
SDL_DECLSPEC void SDLCALL SDL_WaitThread (SDL_Thread * thread, int * status) extern
Wait for a thread to finish.
Threads that haven't been detached will remain until this function cleans them up. Not doing so is a resource leak.
Once a thread has been cleaned up through this function, the SDL_Thread that references it becomes invalid and should not be referenced again. As such, only one thread may call SDL_WaitThread() on another.
The return code from the thread function is placed in the area pointed to by status, if status is not NULL.
You may not wait on a thread that has been used in a call to SDL_DetachThread(). Use either that function or this one, but not both, or behavior is undefined.
It is safe to pass a NULL thread to this function; it is a no-op.
Note that the thread pointer is freed by this function and is not valid afterward.
Parameters
thread the SDL_Thread pointer that was returned from the SDL_CreateThread() call that started this thread.
status a pointer filled in with the value returned from the thread function by its 'return', or -1 if the thread has been detached or isn't valid, may be NULL.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateThread
SDL_DetachThread
{
    if (!ThreadValid(thread)) {
        if (status) {
            *status = -1;
        }
        return;
    }
    SDL_SYS_WaitThread(thread);
    if (status) {
        *status = thread->status;
    }
    SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, false);
    SDL_free(thread->name);
    SDL_free(thread);
}
References SDL_free(), SDL_OBJECT_TYPE_THREAD, SDL_SetObjectValid(), SDL_SYS_WaitThread(), SDL_TLSEntry::thread, and ThreadValid().
Referenced by ClosePhysicalAudioDevice(), ClosePhysicalCamera(), hidapi_thread_join(), SDL_DetachThread(), and SDL_QuitTimers().