SDL3: SDL-main/src/SDL_hints.c File Reference
SDL_hints.c File Reference
#include "SDL_internal.h"
#include "SDL_hints_c.h"
Data Structures
struct SDL_Hint
struct SDL_HintWatch
Typedefs
typedef struct SDL_Hint SDL_Hint
typedef struct SDL_HintWatch SDL_HintWatch
Functions
static void SDLCALL CleanupHintProperty (void *userdata, void *value)
static const char * GetHintEnvironmentVariable (const char *name)
static SDL_PropertiesID GetHintProperties (bool create)
static void SDLCALL ResetHintsCallback (void *userdata, SDL_PropertiesID hints, const char *name)
bool SDL_AddHintCallback (const char *name, SDL_HintCallback callback, void *userdata)
const char * SDL_GetHint (const char *name)
bool SDL_GetHintBoolean (const char *name, bool default_value)
bool SDL_GetStringBoolean (const char *value, bool default_value)
int SDL_GetStringInteger (const char *value, int default_value)
void SDL_InitHints (void)
void SDL_QuitHints (void)
void SDL_RemoveHintCallback (const char *name, SDL_HintCallback callback, void *userdata)
bool SDL_ResetHint (const char *name)
void SDL_ResetHints (void)
bool SDL_SetHint (const char *name, const char *value)
bool SDL_SetHintWithPriority (const char *name, const char *value, SDL_HintPriority priority)
Variables
static SDL_AtomicU32 SDL_hint_props
Typedef Documentation
SDL_Hint
typedef struct SDL_Hint SDL_Hint
SDL_HintWatch
typedef struct SDL_HintWatch SDL_HintWatch
Function Documentation
CleanupHintProperty()
void SDLCALL CleanupHintProperty (void * userdata, void * value) static
{
    SDL_Hint *hint = (SDL_Hint *) value;
    SDL_free(hint->value);
    SDL_HintWatch *entry = hint->callbacks;
    while (entry) {
        SDL_HintWatch *freeable = entry;
        entry = entry->next;
        SDL_free(freeable);
    }
    SDL_free(hint);
}
References SDL_Hint::callbacks, SDL_HintWatch::next, SDL_free(), SDLCALL, and SDL_Hint::value.
Referenced by SDL_AddHintCallback(), and SDL_SetHintWithPriority().
GetHintEnvironmentVariable()
const char * GetHintEnvironmentVariable (const char * name) static
{
    const char *result = SDL_getenv(name);
    if (!result && name && *name) {
        // fall back to old (SDL2) names of environment variables that
        // are important to users (e.g. many use SDL_VIDEODRIVER=wayland)
        if (SDL_strcmp(name, SDL_HINT_VIDEO_DRIVER) == 0) {
            result = SDL_getenv("SDL_VIDEODRIVER");
        } else if (SDL_strcmp(name, SDL_HINT_AUDIO_DRIVER) == 0) {
            result = SDL_getenv("SDL_AUDIODRIVER");
        }
    }
    return result;
}
References SDL_getenv(), SDL_HINT_AUDIO_DRIVER, SDL_HINT_VIDEO_DRIVER, and SDL_strcmp().
Referenced by ResetHintsCallback(), SDL_GetHint(), SDL_ResetHint(), and SDL_SetHintWithPriority().
GetHintProperties()
SDL_PropertiesID GetHintProperties (bool create) static
{
    SDL_PropertiesID props = SDL_GetAtomicU32(&SDL_hint_props);
    if (!props && create) {
        props = SDL_CreateProperties();
        if (!SDL_CompareAndSwapAtomicU32(&SDL_hint_props, 0, props)) {
            // Somebody else created hint properties before us, just use those
            SDL_DestroyProperties(props);
            props = SDL_GetAtomicU32(&SDL_hint_props);
        }
    }
    return props;
}
References SDL_CompareAndSwapAtomicU32(), SDL_CreateProperties(), SDL_DestroyProperties(), SDL_GetAtomicU32(), and SDL_hint_props.
Referenced by SDL_AddHintCallback(), SDL_GetHint(), SDL_RemoveHintCallback(), SDL_ResetHint(), SDL_ResetHints(), and SDL_SetHintWithPriority().
ResetHintsCallback()
void SDLCALL ResetHintsCallback (void * userdata, SDL_PropertiesID hints, const char * name) static
{
    SDL_Hint *hint = (SDL_Hint *)SDL_GetPointerProperty(hints, name, NULL);
    if (!hint) {
        return;  // uh...okay.
    }
    const char *env = GetHintEnvironmentVariable(name);
    if ((!env && hint->value) || (env && !hint->value) || (env && SDL_strcmp(env, hint->value) != 0)) {
        SDL_HintWatch *entry = hint->callbacks;
        while (entry) {
            // Save the next entry in case this one is deleted
            SDL_HintWatch *next = entry->next;
            entry->callback(entry->userdata, name, hint->value, env);
            entry = next;
        }
    }
    SDL_free(hint->value);
    hint->value = NULL;
    hint->priority = SDL_HINT_DEFAULT;
#ifdef SDL_PLATFORM_ANDROID
    if (SDL_strcmp(name, SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY) == 0) {
        // Special handling for this hint, which needs to persist outside the normal application flow
        if (env) {
            Android_SetAllowRecreateActivity(SDL_GetStringBoolean(env, false));
        } else {
            Android_SetAllowRecreateActivity(false);
        }
    }
#endif // SDL_PLATFORM_ANDROID
}
References Android_SetAllowRecreateActivity(), SDL_HintWatch::callback, SDL_Hint::callbacks, GetHintEnvironmentVariable(), SDL_HintWatch::next, NULL, SDL_Hint::priority, SDL_free(), SDL_GetPointerProperty(), SDL_GetStringBoolean(), SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY, SDL_HINT_DEFAULT, SDL_strcmp(), SDLCALL, SDL_HintWatch::userdata, and SDL_Hint::value.
Referenced by SDL_ResetHints().
SDL_AddHintCallback()
bool SDL_AddHintCallback (const char * name, SDL_HintCallback callback, void * userdata)
Add a function to watch a particular hint.
The callback function is called during this function, to provide it an initial value, and again each time the hint's value changes.
Parameters
name the hint to watch.
callback An SDL_HintCallback function that will be called when the hint value changes.
userdata a pointer to pass to the callback function.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveHintCallback
{
    if (!name || !*name) {
        return SDL_InvalidParamError("name");
    } else if (!callback) {
        return SDL_InvalidParamError("callback");
    }
    const SDL_PropertiesID hints = GetHintProperties(true);
    if (!hints) {
        return false;
    }
    SDL_HintWatch *entry = (SDL_HintWatch *)SDL_malloc(sizeof(*entry));
    if (!entry) {
        return false;
    }
    entry->callback = callback;
    entry->userdata = userdata;
    bool result = false;
    SDL_LockProperties(hints);
    SDL_RemoveHintCallback(name, callback, userdata);
    SDL_Hint *hint = (SDL_Hint *)SDL_GetPointerProperty(hints, name, NULL);
    if (hint) {
        result = true;
    } else {  // Need to add a hint entry for this watcher
        hint = (SDL_Hint *)SDL_malloc(sizeof(*hint));
        if (!hint) {
            SDL_free(entry);
            SDL_UnlockProperties(hints);
            return false;
        } else {
            hint->value = NULL;
            hint->priority = SDL_HINT_DEFAULT;
            hint->callbacks = NULL;
            result = SDL_SetPointerPropertyWithCleanup(hints, name, hint, CleanupHintProperty, NULL);
        }
    }
    // Add it to the callbacks for this hint
    entry->next = hint->callbacks;
    hint->callbacks = entry;
    // Now call it with the current value
    const char *value = SDL_GetHint(name);
    callback(userdata, name, value, value);
    SDL_UnlockProperties(hints);
    return result;
}
References SDL_HintWatch::callback, SDL_Hint::callbacks, CleanupHintProperty(), GetHintProperties(), SDL_HintWatch::next, NULL, SDL_Hint::priority, SDL_free(), SDL_GetHint(), SDL_GetPointerProperty(), SDL_HINT_DEFAULT, SDL_InvalidParamError, SDL_LockProperties(), SDL_malloc(), SDL_RemoveHintCallback(), SDL_SetPointerPropertyWithCleanup(), SDL_UnlockProperties(), SDL_HintWatch::userdata, and SDL_Hint::value.
Referenced by FcitxClientCreateIC(), IOS_JoystickInit(), SDL_EnterAppMainCallbacks(), SDL_hid_init(), SDL_InitEvents(), SDL_InitJoysticks(), SDL_InitKeyboard(), SDL_InitLog(), SDL_InitTicks(), SDL_LoadVIDPIDList(), SDL_PreInitMouse(), SDL_VideoInit(), and set_callback().
SDL_GetHint()
const char * SDL_GetHint (const char * name)
Get the value of a hint.
Parameters
name the hint to query.
Returns
the string value of a hint or NULL if the hint isn't set.
Thread Safety
It is safe to call this function from any thread, however the return value only remains valid until the hint is changed; if another thread might do so, the app should supply locks and/or make a copy of the string. Note that using a hint callback instead is always thread-safe, as SDL holds a lock on the thread subsystem during the callback.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetHint
SDL_SetHintWithPriority
{
    if (!name) {
        return NULL;
    }
    const char *result = GetHintEnvironmentVariable(name);
    const SDL_PropertiesID hints = GetHintProperties(false);
    if (hints) {
        SDL_LockProperties(hints);
        SDL_Hint *hint = (SDL_Hint *)SDL_GetPointerProperty(hints, name, NULL);
        if (hint) {
            if (!result || hint->priority == SDL_HINT_OVERRIDE) {
                result = SDL_GetPersistentString(hint->value);
            }
        }
        SDL_UnlockProperties(hints);
    }
    return result;
}
References GetHintEnvironmentVariable(), GetHintProperties(), NULL, SDL_Hint::priority, SDL_GetPersistentString(), SDL_GetPointerProperty(), SDL_HINT_OVERRIDE, SDL_LockProperties(), SDL_UnlockProperties(), and SDL_Hint::value.
Referenced by AutoShowingScreenKeyboard(), detect_available_methods(), DUMMYAUDIO_OpenDevice(), GetControllerTypeOverride(), load_default_icon(), ParseDisplayUsableBoundsHint(), PrepareAudioFormat(), SDL_AddHintCallback(), SDL_CameraInit(), SDL_CPUFeatureMaskFromHint(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_GetAppMetadataProperty(), SDL_GetDefaultSampleFramesFromFreq(), SDL_GetDefaultSystemCursor(), SDL_GetGamepadMappingFilePath(), SDL_GetHintBoolean(), SDL_GetPreferredLocales(), SDL_GetRenderLineMethod(), SDL_GL_ExtensionSupported(), SDL_GPUSelectBackend(), SDL_Haptic_Load_Axes_List(), SDL_InitAudio(), SDL_InitSteamVirtualGamepadInfo(), SDL_LoadGamepadHints(), SDL_LoadVIDPIDList(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_PromptAssertion(), SDL_ResetLogPriorities(), SDL_ShouldMinimizeOnFocusLoss(), SDL_ShowMessageBox(), SDL_StopEventLoop(), SDL_SYS_GetPrefPath(), SDL_SYS_SetThreadPriority(), SDL_SYS_ShowFileDialogWithProperties(), SDL_VideoInit(), SDL_VIDPIDExcludedHintChanged(), SDL_VIDPIDIncludedHintChanged(), ShouldAttemptSensorFusion(), ShouldAttemptTextureFramebuffer(), ShowFileDialog(), ShowFolderDialog(), WaveGetFactChunkHint(), WaveGetRiffSizeHint(), WaveGetTruncationHint(), and WaveLoad().
SDL_GetHintBoolean()
bool SDL_GetHintBoolean (const char * name, bool default_value)
Get the boolean value of a hint variable.
Parameters
name the name of the hint to get the boolean value from.
default_value the value to return if the hint does not exist.
Returns
the boolean value of a hint or the provided default value if the hint does not exist.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHint
SDL_SetHint
{
    const char *hint = SDL_GetHint(name);
    return SDL_GetStringBoolean(hint, default_value);
}
References SDL_GetHint(), and SDL_GetStringBoolean().
Referenced by IOS_JoystickInit(), PLATFORM_hid_init(), SDL_CreateMappingForHIDAPIGamepad(), SDL_CreateRendererWithProperties(), SDL_DebugLogBackend(), SDL_GetTextInputMultiline(), SDL_hid_init(), SDL_InitQuit(), SDL_OnWindowDisplayChanged(), SDL_PrivateAddGamepadMapping(), SDL_SaveBMP_IO(), SDL_SendKeyboardKeyInternal(), SDL_SendWindowEvent(), SDL_ShouldAllowTopmost(), SDL_ShouldIgnoreGamepad(), SDL_ShouldIgnoreJoystick(), SDL_ShouldMinimizeOnFocusLoss(), SDL_SYS_SetThreadPriority(), SDL_UnregisterTray(), and SDL_VideoInit().
SDL_GetStringBoolean()
bool SDL_GetStringBoolean (const char * value, bool default_value)
{
    if (!value || !*value) {
        return default_value;
    }
    if (*value == '0' || SDL_strcasecmp(value, "false") == 0) {
        return false;
    }
    return true;
}
References SDL_strcasecmp().
Referenced by AutoShowingScreenKeyboard(), OnlyControllersChanged(), ResetHintsCallback(), SDL_AutoUpdateJoysticksChanged(), SDL_AutoUpdateSensorsChanged(), SDL_GetBooleanProperty(), SDL_GetHintBoolean(), SDL_JoystickAllowBackgroundEventsChanged(), SDL_MouseAutoCaptureChanged(), SDL_MouseRelativeCursorVisibleChanged(), SDL_MouseRelativeModeCenterChanged(), SDL_MouseRelativeSystemScaleChanged(), SDL_MouseRelativeWarpMotionChanged(), SDL_MouseTouchEventsChanged(), SDL_MouseWarpEmulationChanged(), SDL_PenMouseEventsChanged(), SDL_PenTouchEventsChanged(), SDL_PollSentinelChanged(), SDL_ResetHint(), SDL_SetHintWithPriority(), SDL_SyncHintWatcher(), SDL_TouchMouseEventsChanged(), and ShouldAttemptSensorFusion().
SDL_GetStringInteger()
int SDL_GetStringInteger (const char * value, int default_value)
{
    if (!value || !*value) {
        return default_value;
    }
    if (SDL_strcasecmp(value, "false") == 0) {
        return 0;
    }
    if (SDL_strcasecmp(value, "true") == 0) {
        return 1;
    }
    if (*value == '-' || SDL_isdigit(*value)) {
        return SDL_atoi(value);
    }
    return default_value;
}
References SDL_atoi(), SDL_isdigit(), and SDL_strcasecmp().
SDL_InitHints()
void SDL_InitHints (void)
{
}
SDL_QuitHints()
void SDL_QuitHints (void)
{
    SDL_PropertiesID props;
    do {
        props = SDL_GetAtomicU32(&SDL_hint_props);
    } while (!SDL_CompareAndSwapAtomicU32(&SDL_hint_props, props, 0));
    if (props) {
        SDL_DestroyProperties(props);
    }
}
References SDL_CompareAndSwapAtomicU32(), SDL_DestroyProperties(), SDL_GetAtomicU32(), and SDL_hint_props.
Referenced by SDL_Quit().
SDL_RemoveHintCallback()
void SDL_RemoveHintCallback (const char * name, SDL_HintCallback callback, void * userdata)
Remove a function watching a particular hint.
Parameters
name the hint being watched.
callback an SDL_HintCallback function that will be called when the hint value changes.
userdata a pointer being passed to the callback function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddHintCallback
{
    if (!name || !*name) {
        return;
    }
    const SDL_PropertiesID hints = GetHintProperties(false);
    if (!hints) {
        return;
    }
    SDL_LockProperties(hints);
    SDL_Hint *hint = (SDL_Hint *)SDL_GetPointerProperty(hints, name, NULL);
    if (hint) {
        SDL_HintWatch *prev = NULL;
        for (SDL_HintWatch *entry = hint->callbacks; entry; entry = entry->next) {
            if ((callback == entry->callback) && (userdata == entry->userdata)) {
                if (prev) {
                    prev->next = entry->next;
                } else {
                    hint->callbacks = entry->next;
                }
                SDL_free(entry);
                break;
            }
            prev = entry;
        }
    }
    SDL_UnlockProperties(hints);
}
References SDL_Hint::callbacks, GetHintProperties(), SDL_HintWatch::next, NULL, SDL_free(), SDL_GetPointerProperty(), SDL_LockProperties(), and SDL_UnlockProperties().
Referenced by IOS_JoystickQuit(), SDL_AddHintCallback(), SDL_EnterAppMainCallbacks(), SDL_FreeVIDPIDList(), SDL_hid_exit(), SDL_InitEvents(), SDL_QuitEvents(), SDL_QuitJoysticks(), SDL_QuitKeyboard(), SDL_QuitLog(), SDL_QuitMouse(), and SDL_QuitTicks().
SDL_ResetHint()
bool SDL_ResetHint (const char * name)
Reset a hint to the default value.
This will reset a hint to the value of the environment variable, or NULL if the environment isn't set. Callbacks will be called normally with this change.
Parameters
name the hint to set.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetHint
SDL_ResetHints
{
    if (!name || !*name) {
        return SDL_InvalidParamError("name");
    }
    const char *env = GetHintEnvironmentVariable(name);
    const SDL_PropertiesID hints = GetHintProperties(false);
    if (!hints) {
        return false;
    }
    bool result = false;
    SDL_LockProperties(hints);
    SDL_Hint *hint = (SDL_Hint *)SDL_GetPointerProperty(hints, name, NULL);
    if (hint) {
        if ((!env && hint->value) || (env && !hint->value) || (env && SDL_strcmp(env, hint->value) != 0)) {
            for (SDL_HintWatch *entry = hint->callbacks; entry;) {
                // Save the next entry in case this one is deleted
                SDL_HintWatch *next = entry->next;
                entry->callback(entry->userdata, name, hint->value, env);
                entry = next;
            }
        }
        SDL_free(hint->value);
        hint->value = NULL;
        hint->priority = SDL_HINT_DEFAULT;
        result = true;
    }
#ifdef SDL_PLATFORM_ANDROID
    if (SDL_strcmp(name, SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY) == 0) {
        // Special handling for this hint, which needs to persist outside the normal application flow
        if (env) {
            Android_SetAllowRecreateActivity(SDL_GetStringBoolean(env, false));
        } else {
            Android_SetAllowRecreateActivity(false);
        }
    }
#endif // SDL_PLATFORM_ANDROID
    SDL_UnlockProperties(hints);
    return result;
}
References Android_SetAllowRecreateActivity(), SDL_HintWatch::callback, SDL_Hint::callbacks, GetHintEnvironmentVariable(), GetHintProperties(), SDL_HintWatch::next, NULL, SDL_Hint::priority, SDL_free(), SDL_GetPointerProperty(), SDL_GetStringBoolean(), SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY, SDL_HINT_DEFAULT, SDL_InvalidParamError, SDL_LockProperties(), SDL_strcmp(), SDL_UnlockProperties(), and SDL_Hint::value.
SDL_ResetHints()
void SDL_ResetHints (void)
Reset all hints to the default values.
This will reset all hints to the value of the associated environment variable, or NULL if the environment isn't set. Callbacks will be called normally with this change.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResetHint
{
    SDL_EnumerateProperties(GetHintProperties(false), ResetHintsCallback, NULL);
}
References GetHintProperties(), NULL, ResetHintsCallback(), and SDL_EnumerateProperties().
SDL_SetHint()
bool SDL_SetHint (const char * name, const char * value)
Set a hint with normal priority.
Hints will not be set if there is an existing override hint or environment variable that takes precedence. You can use SDL_SetHintWithPriority() to set the hint with override priority instead.
Parameters
name the hint to set.
value the value of the hint variable.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHint
SDL_ResetHint
SDL_SetHintWithPriority
{
    return SDL_SetHintWithPriority(name, value, SDL_HINT_NORMAL);
}
References SDL_HINT_NORMAL, and SDL_SetHintWithPriority().
SDL_SetHintWithPriority()
bool SDL_SetHintWithPriority (const char * name, const char * value, SDL_HintPriority priority)
Set a hint with a specific priority.
The priority controls the behavior when setting a hint that already has a value. Hints will replace existing hints of their priority and lower. Environment variables are considered to have override priority.
Parameters
name the hint to set.
value the value of the hint variable.
priority the SDL_HintPriority level for the hint.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHint
SDL_ResetHint
SDL_SetHint
{
    if (!name || !*name) {
        return SDL_InvalidParamError("name");
    }
    const char *env = GetHintEnvironmentVariable(name);
    if (env && (priority < SDL_HINT_OVERRIDE)) {
        return SDL_SetError("An environment variable is taking priority");
    }
    const SDL_PropertiesID hints = GetHintProperties(true);
    if (!hints) {
        return false;
    }
    bool result = false;
    SDL_LockProperties(hints);
    SDL_Hint *hint = (SDL_Hint *)SDL_GetPointerProperty(hints, name, NULL);
    if (hint) {
        if (priority >= hint->priority) {
            if (hint->value != value && (!value || !hint->value || SDL_strcmp(hint->value, value) != 0)) {
                char *old_value = hint->value;
                hint->value = value ? SDL_strdup(value) : NULL;
                SDL_HintWatch *entry = hint->callbacks;
                while (entry) {
                    // Save the next entry in case this one is deleted
                    SDL_HintWatch *next = entry->next;
                    entry->callback(entry->userdata, name, old_value, value);
                    entry = next;
                }
                SDL_free(old_value);
            }
            hint->priority = priority;
            result = true;
        }
    } else {  // Couldn't find the hint? Add a new one.
        hint = (SDL_Hint *)SDL_malloc(sizeof(*hint));
        if (hint) {
            hint->value = value ? SDL_strdup(value) : NULL;
            hint->priority = priority;
            hint->callbacks = NULL;
            result = SDL_SetPointerPropertyWithCleanup(hints, name, hint, CleanupHintProperty, NULL);
        }
    }
#ifdef SDL_PLATFORM_ANDROID
    if (SDL_strcmp(name, SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY) == 0) {
        // Special handling for this hint, which needs to persist outside the normal application flow
        Android_SetAllowRecreateActivity(SDL_GetStringBoolean(value, false));
    }
#endif // SDL_PLATFORM_ANDROID
    SDL_UnlockProperties(hints);
    return result;
}
References Android_SetAllowRecreateActivity(), SDL_HintWatch::callback, SDL_Hint::callbacks, CleanupHintProperty(), GetHintEnvironmentVariable(), GetHintProperties(), SDL_HintWatch::next, NULL, SDL_Hint::priority, SDL_free(), SDL_GetPointerProperty(), SDL_GetStringBoolean(), SDL_HINT_ANDROID_ALLOW_RECREATE_ACTIVITY, SDL_HINT_OVERRIDE, SDL_InvalidParamError, SDL_LockProperties(), SDL_malloc(), SDL_SetError(), SDL_SetPointerPropertyWithCleanup(), SDL_strcmp(), SDL_strdup(), SDL_UnlockProperties(), SDL_HintWatch::userdata, and SDL_Hint::value.
Referenced by SDL_SetHint().
Variable Documentation
SDL_hint_props
SDL_AtomicU32 SDL_hint_props static
Referenced by GetHintProperties(), and SDL_QuitHints().