SDL3: SDL-main/src/video/SDL_video.c File Reference
SDL_video.c File Reference
#include "SDL_internal.h"
#include "SDL_sysvideo.h"
#include "SDL_clipboard_c.h"
#include "SDL_egl_c.h"
#include "SDL_surface_c.h"
#include "SDL_pixels_c.h"
#include "SDL_rect_c.h"
#include "SDL_video_c.h"
#include "../events/SDL_events_c.h"
#include "../SDL_hints_c.h"
#include "../SDL_properties_c.h"
#include "../timer/SDL_timer_c.h"
#include "../camera/SDL_camera_c.h"
#include "../render/SDL_sysrender.h"
#include "../main/SDL_main_callbacks.h"
Data Structures
struct SDL_WindowTextureData
Macros
#define CHECK_DISPLAY_MAGIC(display, result)
#define CHECK_WINDOW_MAGIC(window, result)
#define CHECK_WINDOW_NOT_POPUP(window, result)
#define CREATE_FLAGS (SDL_WINDOW_OPENGL | SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY | SDL_WINDOW_ALWAYS_ON_TOP | SDL_WINDOW_POPUP_MENU | SDL_WINDOW_UTILITY | SDL_WINDOW_TOOLTIP | SDL_WINDOW_VULKAN | SDL_WINDOW_MINIMIZED | SDL_WINDOW_METAL | SDL_WINDOW_TRANSPARENT | SDL_WINDOW_NOT_FOCUSABLE)
#define GL_CONTEXT_RELEASE_BEHAVIOR 0x82FB
#define GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH 0x82FC
#define NOT_A_VULKAN_WINDOW "The specified window isn't a Vulkan window"
#define NOT_AN_OPENGL_WINDOW "The specified window isn't an OpenGL window"
#define SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY "sdl2-compat.window.preferred_fullscreen_display"
#define SDL_PROP_WINDOW_TEXTUREDATA_POINTER "SDL.internal.window.texturedata"
Functions
static void ApplyWindowFlags (SDL_Window *window, SDL_WindowFlags flags)
static bool AutoShowingScreenKeyboard (void)
static int SDLCALL cmpmodes (const void *A, const void *B)
static bool DisplayModeChanged (const SDL_DisplayMode *old_mode, const SDL_DisplayMode *new_mode)
static SDL_DisplayID GetDisplayForRect (int x, int y, int w, int h)
static SDL_INLINE bool IsAcceptingDragAndDrop (void)
static bool IsFullscreenOnly (SDL_VideoDevice *_this)
static int ParseDisplayUsableBoundsHint (SDL_Rect *rect)
static SDL_INLINE void PrepareDragAndDropSupport (SDL_Window *window)
SDL_DisplayID SDL_AddBasicVideoDisplay (const SDL_DisplayMode *desktop_mode)
bool SDL_AddFullscreenDisplayMode (SDL_VideoDisplay *display, const SDL_DisplayMode *mode)
SDL_DisplayID SDL_AddVideoDisplay (const SDL_VideoDisplay *display, bool send_event)
bool SDL_AddWindowRenderer (SDL_Window *window, SDL_Renderer *renderer)
static void SDL_CheckWindowDisplayChanged (SDL_Window *window)
static void SDL_CheckWindowDisplayScaleChanged (SDL_Window *window)
void SDL_CheckWindowPixelSizeChanged (SDL_Window *window)
static void SDL_CheckWindowSafeAreaChanged (SDL_Window *window)
static void SDLCALL SDL_CleanupWindowTextureData (void *userdata, void *value)
bool SDL_ClearComposition (SDL_Window *window)
static bool SDL_ContextNotSupported (const char *name)
SDL_Window * SDL_CreatePopupWindow (SDL_Window *parent, int offset_x, int offset_y, int w, int h, SDL_WindowFlags flags)
SDL_Window * SDL_CreateWindow (const char *title, int w, int h, SDL_WindowFlags flags)
static SDL_Surface * SDL_CreateWindowFramebuffer (SDL_Window *window)
static bool SDL_CreateWindowTexture (SDL_VideoDevice *_this, SDL_Window *window, SDL_PixelFormat *format, void **pixels, int *pitch)
SDL_Window * SDL_CreateWindowWithProperties (SDL_PropertiesID props)
static Uint32 SDL_DefaultGraphicsBackends (SDL_VideoDevice *_this)
void SDL_DelVideoDisplay (SDL_DisplayID displayID, bool send_event)
void SDL_DestroyWindow (SDL_Window *window)
bool SDL_DestroyWindowSurface (SDL_Window *window)
static void SDL_DestroyWindowTexture (SDL_VideoDevice *_this, SDL_Window *window)
static bool SDL_DisableMouseWarpOnFullscreenTransitions (SDL_VideoDevice *_this)
bool SDL_DisableScreenSaver (void)
static bool SDL_DllNotSupported (const char *name)
static bool SDL_DriverSendsHDRChanges (SDL_VideoDevice *_this)
SDL_EGLConfig SDL_EGL_GetCurrentConfig (void)
SDL_EGLDisplay SDL_EGL_GetCurrentDisplay (void)
SDL_FunctionPointer SDL_EGL_GetProcAddress (const char *proc)
SDL_EGLConfig SDL_EGL_GetWindowSurface (SDL_Window *window)
void SDL_EGL_SetAttributeCallbacks (SDL_EGLAttribArrayCallback platformAttribCallback, SDL_EGLIntArrayCallback surfaceAttribCallback, SDL_EGLIntArrayCallback contextAttribCallback, void *userdata)
bool SDL_EnableScreenSaver (void)
static void SDL_FinalizeDisplayMode (SDL_DisplayMode *mode)
static void SDL_FinishWindowCreation (SDL_Window *window, SDL_WindowFlags flags)
bool SDL_FlashWindow (SDL_Window *window, SDL_FlashOperation operation)
bool SDL_GetClosestFullscreenDisplayMode (SDL_DisplayID displayID, int w, int h, float refresh_rate, bool include_high_density_modes, SDL_DisplayMode *result)
static void SDL_GetClosestPointOnRect (const SDL_Rect *rect, SDL_Point *point)
const SDL_DisplayMode * SDL_GetCurrentDisplayMode (SDL_DisplayID displayID)
SDL_DisplayOrientation SDL_GetCurrentDisplayOrientation (SDL_DisplayID displayID)
const char * SDL_GetCurrentVideoDriver (void)
const SDL_DisplayMode * SDL_GetDesktopDisplayMode (SDL_DisplayID displayID)
bool SDL_GetDisplayBounds (SDL_DisplayID displayID, SDL_Rect *rect)
float SDL_GetDisplayContentScale (SDL_DisplayID displayID)
SDL_DisplayData * SDL_GetDisplayDriverData (SDL_DisplayID displayID)
SDL_DisplayData * SDL_GetDisplayDriverDataForWindow (SDL_Window *window)
SDL_DisplayID SDL_GetDisplayForPoint (const SDL_Point *point)
SDL_DisplayID SDL_GetDisplayForRect (const SDL_Rect *rect)
SDL_DisplayID SDL_GetDisplayForWindow (SDL_Window *window)
SDL_DisplayID SDL_GetDisplayForWindowPosition (SDL_Window *window)
int SDL_GetDisplayIndex (SDL_DisplayID displayID)
const char * SDL_GetDisplayName (SDL_DisplayID displayID)
SDL_PropertiesID SDL_GetDisplayProperties (SDL_DisplayID displayID)
SDL_DisplayID * SDL_GetDisplays (int *count)
bool SDL_GetDisplayUsableBounds (SDL_DisplayID displayID, SDL_Rect *rect)
SDL_DisplayMode ** SDL_GetFullscreenDisplayModes (SDL_DisplayID displayID, int *count)
static const SDL_DisplayMode * SDL_GetFullscreenModeMatch (const SDL_DisplayMode *mode)
SDL_Window * SDL_GetGrabbedWindow (void)
int SDL_GetMessageBoxCount (void)
SDL_DisplayOrientation SDL_GetNaturalDisplayOrientation (SDL_DisplayID displayID)
int SDL_GetNumVideoDrivers (void)
SDL_DisplayID SDL_GetPrimaryDisplay (void)
SDL_SystemTheme SDL_GetSystemTheme (void)
bool SDL_GetTextInputArea (SDL_Window *window, SDL_Rect *rect, int *cursor)
bool SDL_GetTextInputAutocorrect (SDL_PropertiesID props)
SDL_Capitalization SDL_GetTextInputCapitalization (SDL_PropertiesID props)
bool SDL_GetTextInputMultiline (SDL_PropertiesID props)
SDL_TextInputType SDL_GetTextInputType (SDL_PropertiesID props)
SDL_Window * SDL_GetToplevelForKeyboardFocus (void)
SDL_VideoDevice * SDL_GetVideoDevice (void)
SDL_VideoDisplay * SDL_GetVideoDisplay (SDL_DisplayID displayID)
SDL_VideoDisplay * SDL_GetVideoDisplayForFullscreenWindow (SDL_Window *window)
SDL_VideoDisplay * SDL_GetVideoDisplayForWindow (SDL_Window *window)
const char * SDL_GetVideoDriver (int index)
bool SDL_GetWindowAspectRatio (SDL_Window *window, float *min_aspect, float *max_aspect)
bool SDL_GetWindowBordersSize (SDL_Window *window, int *top, int *left, int *bottom, int *right)
float SDL_GetWindowDisplayScale (SDL_Window *window)
static SDL_WindowFlags SDL_GetWindowFlagProperties (SDL_PropertiesID props)
SDL_WindowFlags SDL_GetWindowFlags (SDL_Window *window)
SDL_Window * SDL_GetWindowFromID (SDL_WindowID id)
const SDL_DisplayMode * SDL_GetWindowFullscreenMode (SDL_Window *window)
void * SDL_GetWindowICCProfile (SDL_Window *window, size_t *size)
SDL_WindowID SDL_GetWindowID (SDL_Window *window)
bool SDL_GetWindowKeyboardGrab (SDL_Window *window)
bool SDL_GetWindowMaximumSize (SDL_Window *window, int *max_w, int *max_h)
bool SDL_GetWindowMinimumSize (SDL_Window *window, int *min_w, int *min_h)
bool SDL_GetWindowMouseGrab (SDL_Window *window)
const SDL_Rect * SDL_GetWindowMouseRect (SDL_Window *window)
float SDL_GetWindowOpacity (SDL_Window *window)
SDL_Window * SDL_GetWindowParent (SDL_Window *window)
float SDL_GetWindowPixelDensity (SDL_Window *window)
SDL_PixelFormat SDL_GetWindowPixelFormat (SDL_Window *window)
bool SDL_GetWindowPosition (SDL_Window *window, int *x, int *y)
SDL_ProgressState SDL_GetWindowProgressState (SDL_Window *window)
float SDL_GetWindowProgressValue (SDL_Window *window)
SDL_PropertiesID SDL_GetWindowProperties (SDL_Window *window)
bool SDL_GetWindowRelativeMouseMode (SDL_Window *window)
SDL_Window **SDLCALL SDL_GetWindows (int *count)
bool SDL_GetWindowSafeArea (SDL_Window *window, SDL_Rect *rect)
bool SDL_GetWindowSize (SDL_Window *window, int *w, int *h)
bool SDL_GetWindowSizeInPixels (SDL_Window *window, int *w, int *h)
SDL_Surface * SDL_GetWindowSurface (SDL_Window *window)
bool SDL_GetWindowSurfaceVSync (SDL_Window *window, int *vsync)
static bool SDL_GetWindowTextureVSync (SDL_VideoDevice *_this, SDL_Window *window, int *vsync)
const char * SDL_GetWindowTitle (SDL_Window *window)
SDL_GLContext SDL_GL_CreateContext (SDL_Window *window)
void SDL_GL_DeduceMaxSupportedESProfile (int *major, int *minor)
bool SDL_GL_DestroyContext (SDL_GLContext context)
bool SDL_GL_ExtensionSupported (const char *extension)
bool SDL_GL_GetAttribute (SDL_GLAttr attr, int *value)
SDL_GLContext SDL_GL_GetCurrentContext (void)
SDL_Window * SDL_GL_GetCurrentWindow (void)
SDL_FunctionPointer SDL_GL_GetProcAddress (const char *proc)
bool SDL_GL_GetSwapInterval (int *interval)
bool SDL_GL_LoadLibrary (const char *path)
bool SDL_GL_MakeCurrent (SDL_Window *window, SDL_GLContext context)
void SDL_GL_ResetAttributes (void)
bool SDL_GL_SetAttribute (SDL_GLAttr attr, int value)
bool SDL_GL_SetSwapInterval (int interval)
bool SDL_GL_SwapWindow (SDL_Window *window)
void SDL_GL_UnloadLibrary (void)
void SDL_GlobalToRelativeForWindow (SDL_Window *window, int abs_x, int abs_y, int *rel_x, int *rel_y)
bool SDL_HasScreenKeyboardSupport (void)
bool SDL_HasWindows (void)
bool SDL_HideWindow (SDL_Window *window)
bool SDL_MaximizeWindow (SDL_Window *window)
SDL_MetalView SDL_Metal_CreateView (SDL_Window *window)
void SDL_Metal_DestroyView (SDL_MetalView view)
void * SDL_Metal_GetLayer (SDL_MetalView view)
bool SDL_MinimizeWindow (SDL_Window *window)
static bool SDL_ModeSwitchingEmulated (SDL_VideoDevice *_this)
void SDL_OnApplicationDidEnterBackground (void)
void SDL_OnApplicationDidEnterForeground (void)
void SDL_OnApplicationDidReceiveMemoryWarning (void)
void SDL_OnApplicationWillEnterBackground (void)
void SDL_OnApplicationWillEnterForeground (void)
void SDL_OnApplicationWillTerminate (void)
void SDL_OnDisplayAdded (SDL_VideoDisplay *display)
void SDL_OnDisplayMoved (SDL_VideoDisplay *display)
bool SDL_OnVideoThread (void)
void SDL_OnWindowDisplayChanged (SDL_Window *window)
void SDL_OnWindowEnter (SDL_Window *window)
void SDL_OnWindowFocusGained (SDL_Window *window)
void SDL_OnWindowFocusLost (SDL_Window *window)
void SDL_OnWindowHidden (SDL_Window *window)
void SDL_OnWindowLeave (SDL_Window *window)
void SDL_OnWindowLiveResizeUpdate (SDL_Window *window)
void SDL_OnWindowMaximized (SDL_Window *window)
void SDL_OnWindowMinimized (SDL_Window *window)
void SDL_OnWindowMoved (SDL_Window *window)
void SDL_OnWindowPixelSizeChanged (SDL_Window *window)
void SDL_OnWindowResized (SDL_Window *window)
void SDL_OnWindowRestored (SDL_Window *window)
void SDL_OnWindowShown (SDL_Window *window)
bool SDL_RaiseWindow (SDL_Window *window)
bool SDL_RecreateWindow (SDL_Window *window, SDL_WindowFlags flags)
void SDL_RelativeToGlobalForWindow (SDL_Window *window, int rel_x, int rel_y, int *abs_x, int *abs_y)
void SDL_RemoveWindowRenderer (SDL_Window *window, SDL_Renderer *renderer)
void SDL_ResetFullscreenDisplayModes (SDL_VideoDisplay *display)
static void SDL_RestoreMousePosition (SDL_Window *window)
bool SDL_RestoreWindow (SDL_Window *window)
bool SDL_ScreenKeyboardShown (SDL_Window *window)
bool SDL_ScreenSaverEnabled (void)
static bool SDL_SendsDisplayChanges (SDL_VideoDevice *_this)
static bool SDL_SendsFullscreenDimensions (SDL_VideoDevice *_this)
void SDL_SetCurrentDisplayMode (SDL_VideoDisplay *display, const SDL_DisplayMode *mode)
void SDL_SetDesktopDisplayMode (SDL_VideoDisplay *display, const SDL_DisplayMode *mode)
void SDL_SetDisplayContentScale (SDL_VideoDisplay *display, float scale)
void SDL_SetDisplayHDRProperties (SDL_VideoDisplay *display, const SDL_HDROutputProperties *HDR)
bool SDL_SetDisplayModeForDisplay (SDL_VideoDisplay *display, SDL_DisplayMode *mode)
void SDL_SetSystemTheme (SDL_SystemTheme theme)
bool SDL_SetTextInputArea (SDL_Window *window, const SDL_Rect *rect, int cursor)
bool SDL_SetWindowAlwaysOnTop (SDL_Window *window, bool on_top)
bool SDL_SetWindowAspectRatio (SDL_Window *window, float min_aspect, float max_aspect)
bool SDL_SetWindowBordered (SDL_Window *window, bool bordered)
bool SDL_SetWindowFocusable (SDL_Window *window, bool focusable)
bool SDL_SetWindowFullscreen (SDL_Window *window, bool fullscreen)
bool SDL_SetWindowFullscreenMode (SDL_Window *window, const SDL_DisplayMode *mode)
void SDL_SetWindowHDRProperties (SDL_Window *window, const SDL_HDROutputProperties *HDR, bool send_event)
bool SDL_SetWindowHitTest (SDL_Window *window, SDL_HitTest callback, void *callback_data)
bool SDL_SetWindowIcon (SDL_Window *window, SDL_Surface *icon)
bool SDL_SetWindowKeyboardGrab (SDL_Window *window, bool grabbed)
bool SDL_SetWindowMaximumSize (SDL_Window *window, int max_w, int max_h)
bool SDL_SetWindowMinimumSize (SDL_Window *window, int min_w, int min_h)
bool SDL_SetWindowModal (SDL_Window *window, bool modal)
bool SDL_SetWindowMouseGrab (SDL_Window *window, bool grabbed)
bool SDL_SetWindowMouseRect (SDL_Window *window, const SDL_Rect *rect)
bool SDL_SetWindowOpacity (SDL_Window *window, float opacity)
bool SDL_SetWindowParent (SDL_Window *window, SDL_Window *parent)
bool SDL_SetWindowPosition (SDL_Window *window, int x, int y)
bool SDL_SetWindowProgressState (SDL_Window *window, SDL_ProgressState state)
bool SDL_SetWindowProgressValue (SDL_Window *window, float value)
bool SDL_SetWindowRelativeMouseMode (SDL_Window *window, bool enabled)
bool SDL_SetWindowResizable (SDL_Window *window, bool resizable)
void SDL_SetWindowSafeAreaInsets (SDL_Window *window, int left, int right, int top, int bottom)
bool SDL_SetWindowShape (SDL_Window *window, SDL_Surface *shape)
bool SDL_SetWindowSize (SDL_Window *window, int w, int h)
bool SDL_SetWindowSurfaceVSync (SDL_Window *window, int vsync)
bool SDL_SetWindowTextureVSync (SDL_VideoDevice *_this, SDL_Window *window, int vsync)
bool SDL_SetWindowTitle (SDL_Window *window, const char *title)
bool SDL_ShouldAllowTopmost (void)
bool SDL_ShouldFocusPopup (SDL_Window *window)
static bool SDL_ShouldMinimizeOnFocusLoss (SDL_Window *window)
bool SDL_ShouldRelinquishPopupFocus (SDL_Window *window, SDL_Window **new_focus)
bool SDL_ShowMessageBox (const SDL_MessageBoxData *messageboxdata, int *buttonID)
bool SDL_ShowSimpleMessageBox (SDL_MessageBoxFlags flags, const char *title, const char *message, SDL_Window *window)
bool SDL_ShowWindow (SDL_Window *window)
bool SDL_ShowWindowSystemMenu (SDL_Window *window, int x, int y)
bool SDL_StartTextInput (SDL_Window *window)
bool SDL_StartTextInputWithProperties (SDL_Window *window, SDL_PropertiesID props)
bool SDL_StopTextInput (SDL_Window *window)
static void SDL_SyncHintWatcher (void *userdata, const char *name, const char *oldValue, const char *newValue)
static void SDL_SyncIfRequired (SDL_Window *window)
bool SDL_SyncWindow (SDL_Window *window)
bool SDL_TextInputActive (SDL_Window *window)
void SDL_ToggleDragAndDropSupport (void)
bool SDL_UninitializedVideo (void)
void SDL_UpdateDesktopBounds (void)
static void SDL_UpdateFullscreenDisplayModes (SDL_VideoDisplay *display)
bool SDL_UpdateFullscreenMode (SDL_Window *window, SDL_FullscreenOp fullscreen, bool commit)
void SDL_UpdateWindowGrab (SDL_Window *window)
static void SDL_UpdateWindowHierarchy (SDL_Window *window, SDL_Window *parent)
bool SDL_UpdateWindowSurface (SDL_Window *window)
bool SDL_UpdateWindowSurfaceRects (SDL_Window *window, const SDL_Rect *rects, int numrects)
static bool SDL_UpdateWindowTexture (SDL_VideoDevice *_this, SDL_Window *window, const SDL_Rect *rects, int numrects)
bool SDL_VideoInit (const char *driver_name)
void SDL_VideoQuit (void)
bool SDL_Vulkan_CreateSurface (SDL_Window *window, VkInstance instance, const struct VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void SDL_Vulkan_DestroySurface (VkInstance instance, VkSurfaceKHR surface, const struct VkAllocationCallbacks *allocator)
char const *const * SDL_Vulkan_GetInstanceExtensions (Uint32 *count)
bool SDL_Vulkan_GetPresentationSupport (VkInstance instance, VkPhysicalDevice physicalDevice, Uint32 queueFamilyIndex)
SDL_FunctionPointer SDL_Vulkan_GetVkGetInstanceProcAddr (void)
bool SDL_Vulkan_LoadLibrary (const char *path)
void SDL_Vulkan_UnloadLibrary (void)
bool SDL_WindowHasSurface (SDL_Window *window)
static bool ShouldAttemptTextureFramebuffer (void)
Variables
static SDL_VideoDevice * _this = NULL
static VideoBootStrap * bootstrap []
static const VideoBootStrap * deduped_bootstrap [SDL_arraysize(bootstrap) - 1]
static SDL_AtomicInt SDL_messagebox_count
struct {
SDL_WindowFlags flag
bool invert_value
const char * property_name
} SDL_WindowFlagProperties []
static bool syncHint
Macro Definition Documentation
CHECK_DISPLAY_MAGIC
#define CHECK_DISPLAY_MAGIC (display, result)
Value:
    if (!display) {                                                     \
        return result;                                                  \
    }                                                                   \
#define CHECK_DISPLAY_MAGIC(display, result)                            \
    if (!display) {                                                     \
        return result;                                                  \
    }                                                                   \
Referenced by SDL_GetClosestFullscreenDisplayMode(), SDL_GetCurrentDisplayMode(), SDL_GetCurrentDisplayOrientation(), SDL_GetDesktopDisplayMode(), SDL_GetDisplayBounds(), SDL_GetDisplayContentScale(), SDL_GetDisplayDriverData(), SDL_GetDisplayName(), SDL_GetDisplayProperties(), SDL_GetDisplayUsableBounds(), SDL_GetFullscreenDisplayModes(), and SDL_GetNaturalDisplayOrientation().
CHECK_WINDOW_MAGIC
#define CHECK_WINDOW_MAGIC (window, result)
Value:
    if (!_this) {                                                       \
        SDL_UninitializedVideo();                                       \
        return result;                                                  \
    }                                                                   \
    if (!SDL_ObjectValid(window, SDL_OBJECT_TYPE_WINDOW)) {             \
        SDL_SetError("Invalid window");                                 \
        return result;                                                  \
    }
#define CHECK_WINDOW_MAGIC(window, result)                              \
    if (!_this) {                                                       \
        SDL_UninitializedVideo();                                       \
        return result;                                                  \
    }                                                                   \
    if (!SDL_ObjectValid(window, SDL_OBJECT_TYPE_WINDOW)) {             \
        SDL_SetError("Invalid window");                                 \
        return result;                                                  \
    }
Referenced by SDL_ClearComposition(), SDL_DestroyWindow(), SDL_DestroyWindowSurface(), SDL_FlashWindow(), SDL_GetDisplayForWindow(), SDL_GetDisplayForWindowPosition(), SDL_GetTextInputArea(), SDL_GetVideoDisplayForFullscreenWindow(), SDL_GetWindowAspectRatio(), SDL_GetWindowBordersSize(), SDL_GetWindowDisplayScale(), SDL_GetWindowFlags(), SDL_GetWindowFullscreenMode(), SDL_GetWindowID(), SDL_GetWindowKeyboardGrab(), SDL_GetWindowMaximumSize(), SDL_GetWindowMinimumSize(), SDL_GetWindowMouseGrab(), SDL_GetWindowMouseRect(), SDL_GetWindowOpacity(), SDL_GetWindowParent(), SDL_GetWindowPixelDensity(), SDL_GetWindowPixelFormat(), SDL_GetWindowPosition(), SDL_GetWindowProgressState(), SDL_GetWindowProgressValue(), SDL_GetWindowProperties(), SDL_GetWindowRelativeMouseMode(), SDL_GetWindowSafeArea(), SDL_GetWindowSize(), SDL_GetWindowSizeInPixels(), SDL_GetWindowSurface(), SDL_GetWindowSurfaceVSync(), SDL_GetWindowTitle(), SDL_GL_CreateContext(), SDL_GL_MakeCurrent(), SDL_GL_SwapWindow(), SDL_HideWindow(), SDL_MaximizeWindow(), SDL_Metal_CreateView(), SDL_MinimizeWindow(), SDL_RaiseWindow(), SDL_RestoreWindow(), SDL_ScreenKeyboardShown(), SDL_SetTextInputArea(), SDL_SetWindowAlwaysOnTop(), SDL_SetWindowAspectRatio(), SDL_SetWindowBordered(), SDL_SetWindowFocusable(), SDL_SetWindowFullscreen(), SDL_SetWindowFullscreenMode(), SDL_SetWindowHitTest(), SDL_SetWindowIcon(), SDL_SetWindowKeyboardGrab(), SDL_SetWindowMaximumSize(), SDL_SetWindowMinimumSize(), SDL_SetWindowModal(), SDL_SetWindowMouseGrab(), SDL_SetWindowMouseRect(), SDL_SetWindowOpacity(), SDL_SetWindowParent(), SDL_SetWindowPosition(), SDL_SetWindowProgressState(), SDL_SetWindowProgressValue(), SDL_SetWindowRelativeMouseMode(), SDL_SetWindowResizable(), SDL_SetWindowShape(), SDL_SetWindowSize(), SDL_SetWindowSurfaceVSync(), SDL_SetWindowTitle(), SDL_ShowWindow(), SDL_ShowWindowSystemMenu(), SDL_StartTextInputWithProperties(), SDL_StopTextInput(), SDL_SyncWindow(), SDL_TextInputActive(), SDL_UpdateFullscreenMode(), SDL_UpdateWindowSurface(), SDL_UpdateWindowSurfaceRects(), SDL_Vulkan_CreateSurface(), and SDL_WindowHasSurface().
CHECK_WINDOW_NOT_POPUP
#define CHECK_WINDOW_NOT_POPUP (window, result)
Value:
    if (SDL_WINDOW_IS_POPUP(window)) {                                  \
        SDL_SetError("Operation invalid on popup windows");             \
        return result;                                                  \
    }
#define CHECK_WINDOW_NOT_POPUP(window, result)                          \
    if (SDL_WINDOW_IS_POPUP(window)) {                                  \
        SDL_SetError("Operation invalid on popup windows");             \
        return result;                                                  \
    }
Referenced by SDL_FlashWindow(), SDL_GetWindowFullscreenMode(), SDL_GetWindowProgressState(), SDL_GetWindowProgressValue(), SDL_MaximizeWindow(), SDL_MinimizeWindow(), SDL_RestoreWindow(), SDL_SetWindowAlwaysOnTop(), SDL_SetWindowBordered(), SDL_SetWindowFullscreen(), SDL_SetWindowFullscreenMode(), SDL_SetWindowKeyboardGrab(), SDL_SetWindowModal(), SDL_SetWindowMouseGrab(), SDL_SetWindowParent(), SDL_SetWindowProgressState(), SDL_SetWindowProgressValue(), SDL_SetWindowResizable(), SDL_SetWindowTitle(), and SDL_ShowWindowSystemMenu().
CREATE_FLAGS
#define CREATE_FLAGS (SDL_WINDOW_OPENGL | SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY | SDL_WINDOW_ALWAYS_ON_TOP | SDL_WINDOW_POPUP_MENU | SDL_WINDOW_UTILITY | SDL_WINDOW_TOOLTIP | SDL_WINDOW_VULKAN | SDL_WINDOW_MINIMIZED | SDL_WINDOW_METAL | SDL_WINDOW_TRANSPARENT | SDL_WINDOW_NOT_FOCUSABLE)
#define CREATE_FLAGS \
    (SDL_WINDOW_OPENGL | SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE | SDL_WINDOW_HIGH_PIXEL_DENSITY | SDL_WINDOW_ALWAYS_ON_TOP | SDL_WINDOW_POPUP_MENU | SDL_WINDOW_UTILITY | SDL_WINDOW_TOOLTIP | SDL_WINDOW_VULKAN | SDL_WINDOW_MINIMIZED | SDL_WINDOW_METAL | SDL_WINDOW_TRANSPARENT | SDL_WINDOW_NOT_FOCUSABLE)
Referenced by SDL_CreateWindowWithProperties(), and SDL_RecreateWindow().
GL_CONTEXT_RELEASE_BEHAVIOR
#define GL_CONTEXT_RELEASE_BEHAVIOR 0x82FB
GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH
#define GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH 0x82FC
NOT_A_VULKAN_WINDOW
#define NOT_A_VULKAN_WINDOW "The specified window isn't a Vulkan window"
Referenced by SDL_Vulkan_CreateSurface().
NOT_AN_OPENGL_WINDOW
#define NOT_AN_OPENGL_WINDOW "The specified window isn't an OpenGL window"
Referenced by SDL_GL_CreateContext(), SDL_GL_MakeCurrent(), and SDL_GL_SwapWindow().
SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY
#define SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY "sdl2-compat.window.preferred_fullscreen_display"
Referenced by SDL_GetDisplayForWindow().
SDL_PROP_WINDOW_TEXTUREDATA_POINTER
#define SDL_PROP_WINDOW_TEXTUREDATA_POINTER "SDL.internal.window.texturedata"
Referenced by SDL_CreateWindowTexture(), SDL_DestroyWindowTexture(), SDL_GetWindowTextureVSync(), SDL_SetWindowTextureVSync(), and SDL_UpdateWindowTexture().
Function Documentation
ApplyWindowFlags()
void ApplyWindowFlags (SDL_Window * window, SDL_WindowFlags flags) static
{
    if (!SDL_WINDOW_IS_POPUP(window)) {
        if (!(flags & (SDL_WINDOW_MINIMIZED | SDL_WINDOW_MAXIMIZED))) {
            SDL_RestoreWindow(window);
        }
        if (flags & SDL_WINDOW_MAXIMIZED) {
            SDL_MaximizeWindow(window);
        }
        SDL_SetWindowFullscreen(window, (flags & SDL_WINDOW_FULLSCREEN) != 0);
        if (flags & SDL_WINDOW_MINIMIZED) {
            SDL_MinimizeWindow(window);
        }
        if (flags & SDL_WINDOW_MODAL) {
            SDL_SetWindowModal(window, true);
        }
        if (flags & SDL_WINDOW_MOUSE_GRABBED) {
            SDL_SetWindowMouseGrab(window, true);
        }
        if (flags & SDL_WINDOW_KEYBOARD_GRABBED) {
            SDL_SetWindowKeyboardGrab(window, true);
        }
    }
}
References SDL_MaximizeWindow(), SDL_MinimizeWindow(), SDL_RestoreWindow(), SDL_SetWindowFullscreen(), SDL_SetWindowKeyboardGrab(), SDL_SetWindowModal(), SDL_SetWindowMouseGrab(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_IS_POPUP, SDL_WINDOW_KEYBOARD_GRABBED, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_MINIMIZED, SDL_WINDOW_MODAL, and SDL_WINDOW_MOUSE_GRABBED.
Referenced by SDL_FinishWindowCreation(), and SDL_OnWindowShown().
AutoShowingScreenKeyboard()
bool AutoShowingScreenKeyboard (void) static
{
    const char *hint = SDL_GetHint(SDL_HINT_ENABLE_SCREEN_KEYBOARD);
    if (!hint) {
        // Steam will eventually have smarts about whether a keyboard is active, so always request the on-screen keyboard on Steam Deck
        hint = SDL_GetHint("SteamDeck");
    }
    if (((!hint || SDL_strcasecmp(hint, "auto") == 0) && !SDL_HasKeyboard()) ||
        SDL_GetStringBoolean(hint, false)) {
        return true;
    } else {
        return false;
    }
}
References SDL_GetHint(), SDL_GetStringBoolean(), SDL_HasKeyboard(), SDL_HINT_ENABLE_SCREEN_KEYBOARD, and SDL_strcasecmp().
Referenced by SDL_StartTextInputWithProperties(), and SDL_StopTextInput().
cmpmodes()
int SDLCALL cmpmodes (const void * A, const void * B) static
{
    const SDL_DisplayMode *a = (const SDL_DisplayMode *)A;
    const SDL_DisplayMode *b = (const SDL_DisplayMode *)B;
    int a_refresh_rate = (int)(a->refresh_rate * 100);
    int b_refresh_rate = (int)(b->refresh_rate * 100);
    int a_pixel_density = (int)(a->pixel_density * 100);
    int b_pixel_density = (int)(b->pixel_density * 100);
    if (a->w != b->w) {
        return b->w - a->w;
    } else if (a->h != b->h) {
        return b->h - a->h;
    } else if (SDL_BITSPERPIXEL(a->format) != SDL_BITSPERPIXEL(b->format)) {
        return SDL_BITSPERPIXEL(b->format) - SDL_BITSPERPIXEL(a->format);
    } else if (SDL_PIXELLAYOUT(a->format) != SDL_PIXELLAYOUT(b->format)) {
        return SDL_PIXELLAYOUT(b->format) - SDL_PIXELLAYOUT(a->format);
    } else if (a_refresh_rate != b_refresh_rate) {
        return b_refresh_rate - a_refresh_rate;
    } else if (a_pixel_density != b_pixel_density) {
        return a_pixel_density - b_pixel_density;
    }
    return 0;
}
References SDL_DisplayMode::format, SDL_DisplayMode::h, SDL_DisplayMode::pixel_density, SDL_DisplayMode::refresh_rate, SDL_BITSPERPIXEL, SDL_PIXELLAYOUT, SDLCALL, and SDL_DisplayMode::w.
Referenced by SDL_AddFullscreenDisplayMode(), and SDL_GetFullscreenModeMatch().
DisplayModeChanged()
bool DisplayModeChanged (const SDL_DisplayMode * old_mode, const SDL_DisplayMode * new_mode) static
{
    return ((old_mode->displayID && old_mode->displayID != new_mode->displayID) ||
            (old_mode->format && old_mode->format != new_mode->format) ||
            (old_mode->w && old_mode->h && (old_mode->w != new_mode->w ||old_mode->h != new_mode->h)) ||
            (old_mode->pixel_density != 0.0f && old_mode->pixel_density != new_mode->pixel_density) ||
            (old_mode->refresh_rate != 0.0f && old_mode->refresh_rate != new_mode->refresh_rate));
}
References SDL_DisplayMode::displayID, SDL_DisplayMode::format, SDL_DisplayMode::h, SDL_DisplayMode::pixel_density, SDL_DisplayMode::refresh_rate, and SDL_DisplayMode::w.
Referenced by SDL_SetCurrentDisplayMode(), and SDL_SetDesktopDisplayMode().
GetDisplayForRect()
SDL_DisplayID GetDisplayForRect (int x, int y, int w, int h) static
{
    int i, dist;
    SDL_DisplayID closest = 0;
    int closest_dist = 0x7FFFFFFF;
    SDL_Point closest_point_on_display;
    SDL_Point delta;
    SDL_Point center;
    center.x = x + w / 2;
    center.y = y + h / 2;
    if (_this) {
        for (i = 0; i < _this->num_displays; ++i) {
            SDL_VideoDisplay *display = _this->displays[i];
            SDL_Rect display_rect;
            SDL_GetDisplayBounds(display->id, &display_rect);
            // Check if the window is fully enclosed
            if (SDL_GetRectEnclosingPoints(&center, 1, &display_rect, NULL)) {
                return display->id;
            }
            // Snap window center to the display rect
            closest_point_on_display = center;
            SDL_GetClosestPointOnRect(&display_rect, &closest_point_on_display);
            delta.x = center.x - closest_point_on_display.x;
            delta.y = center.y - closest_point_on_display.y;
            dist = (delta.x * delta.x + delta.y * delta.y);
            if (dist < closest_dist) {
                closest = display->id;
                closest_dist = dist;
            }
        }
    }
    if (closest == 0) {
        SDL_SetError("Couldn't find any displays");
    }
    return closest;
}
References _this, NULL, SDL_GetClosestPointOnRect(), SDL_GetDisplayBounds(), SDL_GetRectEnclosingPoints(), SDL_SetError(), SDL_Point::x, and SDL_Point::y.
Referenced by SDL_GetDisplayForPoint(), SDL_GetDisplayForRect(), SDL_GetDisplayForWindowPosition(), and SDL_GetVideoDisplayForFullscreenWindow().
IsAcceptingDragAndDrop()
SDL_INLINE bool IsAcceptingDragAndDrop (void) static
{
    if (SDL_EventEnabled(SDL_EVENT_DROP_FILE) || SDL_EventEnabled(SDL_EVENT_DROP_TEXT)) {
        return true;
    }
    return false;
}
References SDL_EVENT_DROP_FILE, SDL_EVENT_DROP_TEXT, SDL_EventEnabled(), and SDL_INLINE.
Referenced by PrepareDragAndDropSupport(), and SDL_ToggleDragAndDropSupport().
IsFullscreenOnly()
bool IsFullscreenOnly (SDL_VideoDevice * _this) static
{
    return !!(_this->device_caps & VIDEO_DEVICE_CAPS_FULLSCREEN_ONLY);
}
References _this, and VIDEO_DEVICE_CAPS_FULLSCREEN_ONLY.
Referenced by SDL_CreateWindowWithProperties().
ParseDisplayUsableBoundsHint()
int ParseDisplayUsableBoundsHint (SDL_Rect * rect) static
{
    const char *hint = SDL_GetHint(SDL_HINT_DISPLAY_USABLE_BOUNDS);
    return hint && (SDL_sscanf(hint, "%d,%d,%d,%d", &rect->x, &rect->y, &rect->w, &rect->h) == 4);
}
References SDL_Rect::h, SDL_GetHint(), SDL_HINT_DISPLAY_USABLE_BOUNDS, SDL_sscanf(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_GetDisplayUsableBounds().
PrepareDragAndDropSupport()
SDL_INLINE void PrepareDragAndDropSupport (SDL_Window * window) static
{
    if (_this->AcceptDragAndDrop) {
        _this->AcceptDragAndDrop(window, IsAcceptingDragAndDrop());
    }
}
References _this, IsAcceptingDragAndDrop(), and SDL_INLINE.
Referenced by SDL_FinishWindowCreation().
SDL_AddBasicVideoDisplay()
SDL_DisplayID SDL_AddBasicVideoDisplay (const SDL_DisplayMode * desktop_mode)
{
    SDL_VideoDisplay display;
    SDL_zero(display);
    if (desktop_mode) {
        SDL_memcpy(&display.desktop_mode, desktop_mode, sizeof(display.desktop_mode));
    }
    return SDL_AddVideoDisplay(&display, false);
}
References SDL_AddVideoDisplay(), SDL_memcpy, and SDL_zero.
SDL_AddFullscreenDisplayMode()
bool SDL_AddFullscreenDisplayMode (SDL_VideoDisplay * display, const SDL_DisplayMode * mode)
{
    SDL_DisplayMode *modes;
    SDL_DisplayMode new_mode;
    int i, nmodes;
    // Finalize the mode for the display
    SDL_memcpy(&new_mode, mode, sizeof(new_mode));
    new_mode.displayID = display->id;
    SDL_FinalizeDisplayMode(&new_mode);
    // Make sure we don't already have the mode in the list
    modes = display->fullscreen_modes;
    nmodes = display->num_fullscreen_modes;
    for (i = 0; i < nmodes; ++i) {
        if (cmpmodes(&new_mode, &modes[i]) == 0) {
            return false;
        }
    }
    // Go ahead and add the new mode
    if (nmodes == display->max_fullscreen_modes) {
        modes = (SDL_DisplayMode *)SDL_malloc((display->max_fullscreen_modes + 32) * sizeof(*modes));
        if (!modes) {
            return false;
        }
        if (display->fullscreen_modes) {
            // Copy the list and update the current mode pointer, if necessary.
            SDL_memcpy(modes, display->fullscreen_modes, nmodes * sizeof(*modes));
            for (i = 0; i < nmodes; ++i) {
                if (display->current_mode == &display->fullscreen_modes[i]) {
                    display->current_mode = &modes[i];
                }
            }
            SDL_free(display->fullscreen_modes);
        }
        display->fullscreen_modes = modes;
        display->max_fullscreen_modes += 32;
    }
    SDL_memcpy(&modes[display->num_fullscreen_modes++], &new_mode, sizeof(new_mode));
    // Re-sort video modes
    SDL_qsort(display->fullscreen_modes, display->num_fullscreen_modes,
              sizeof(SDL_DisplayMode), cmpmodes);
    return true;
}
References cmpmodes(), SDL_DisplayMode::displayID, SDL_FinalizeDisplayMode(), SDL_free(), SDL_malloc(), SDL_memcpy, and SDL_qsort().
SDL_AddVideoDisplay()
SDL_DisplayID SDL_AddVideoDisplay (const SDL_VideoDisplay * display, bool send_event)
{
    SDL_VideoDisplay **displays, *new_display;
    SDL_DisplayID id;
    SDL_PropertiesID props;
    int i;
    new_display = (SDL_VideoDisplay *)SDL_malloc(sizeof(*new_display));
    if (!new_display) {
        return 0;
    }
    displays = (SDL_VideoDisplay **)SDL_realloc(_this->displays, (_this->num_displays + 1) * sizeof(*displays));
    if (!displays) {
        SDL_free(new_display);
        return 0;
    }
    _this->displays = displays;
    _this->displays[_this->num_displays++] = new_display;
    id = SDL_GetNextObjectID();
    SDL_copyp(new_display, display);
    new_display->id = id;
    new_display->device = _this;
    if (display->name) {
        new_display->name = SDL_strdup(display->name);
    } else {
        char name[32];
        SDL_itoa(id, name, 10);
        new_display->name = SDL_strdup(name);
    }
    if (new_display->content_scale == 0.0f) {
        new_display->content_scale = 1.0f;
    }
    new_display->desktop_mode.displayID = id;
    new_display->current_mode = &new_display->desktop_mode;
    SDL_FinalizeDisplayMode(&new_display->desktop_mode);
    for (i = 0; i < new_display->num_fullscreen_modes; ++i) {
        new_display->fullscreen_modes[i].displayID = id;
    }
    new_display->HDR.HDR_headroom = SDL_max(display->HDR.HDR_headroom, 1.0f);
    new_display->HDR.SDR_white_level = SDL_max(display->HDR.SDR_white_level, 1.0f);
    props = SDL_GetDisplayProperties(id);
    SDL_SetBooleanProperty(props, SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN, new_display->HDR.HDR_headroom > 1.0f);
    SDL_UpdateDesktopBounds();
    if (send_event) {
        SDL_SendDisplayEvent(new_display, SDL_EVENT_DISPLAY_ADDED, 0, 0);
    }
    return id;
}
References _this, SDL_VideoDisplay::content_scale, SDL_VideoDisplay::current_mode, SDL_VideoDisplay::desktop_mode, SDL_VideoDisplay::device, SDL_DisplayMode::displayID, SDL_VideoDisplay::fullscreen_modes, SDL_VideoDisplay::HDR, SDL_HDROutputProperties::HDR_headroom, SDL_VideoDisplay::id, SDL_VideoDisplay::name, SDL_VideoDisplay::num_fullscreen_modes, SDL_copyp, SDL_EVENT_DISPLAY_ADDED, SDL_FinalizeDisplayMode(), SDL_free(), SDL_GetDisplayProperties(), SDL_GetNextObjectID(), SDL_itoa(), SDL_malloc(), SDL_max, SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN, SDL_realloc(), SDL_SendDisplayEvent(), SDL_SetBooleanProperty(), SDL_strdup(), SDL_UpdateDesktopBounds(), and SDL_HDROutputProperties::SDR_white_level.
Referenced by SDL_AddBasicVideoDisplay(), and videoInit().
SDL_AddWindowRenderer()
bool SDL_AddWindowRenderer (SDL_Window * window, SDL_Renderer * renderer)
{
    SDL_Renderer **renderers = (SDL_Renderer **)SDL_realloc(window->renderers, (window->num_renderers + 1) * sizeof(*renderers));
    if (!renderers) {
        return false;
    }
    window->renderers = renderers;
    window->renderers[window->num_renderers++] = renderer;
    return true;
}
References SDL_realloc().
Referenced by SDL_CreateRendererWithProperties().
SDL_CheckWindowDisplayChanged()
void SDL_CheckWindowDisplayChanged (SDL_Window * window) static
{
    if (SDL_SendsDisplayChanges(_this)) {
        return;
    }
    SDL_DisplayID displayID = SDL_GetDisplayForWindowPosition(window);
    if (displayID != window->last_displayID) {
        int i, display_index;
        // Sanity check our fullscreen windows
        display_index = SDL_GetDisplayIndex(displayID);
        for (i = 0; i < _this->num_displays; ++i) {
            SDL_VideoDisplay *display = _this->displays[i];
            if (display->fullscreen_window == window) {
                if (display_index != i) {
                    if (display_index < 0) {
                        display_index = i;
                    } else {
                        SDL_VideoDisplay *new_display = _this->displays[display_index];
                        // The window was moved to a different display
                        if (new_display->fullscreen_window &&
                            new_display->fullscreen_window != window) {
                            // Uh oh, there's already a fullscreen window here; minimize it
                            SDL_MinimizeWindow(new_display->fullscreen_window);
                        }
                        new_display->fullscreen_window = window;
                        display->fullscreen_window = NULL;
                    }
                }
                break;
            }
        }
        SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_DISPLAY_CHANGED, (int)displayID, 0);
    }
}
References _this, SDL_VideoDisplay::fullscreen_window, NULL, SDL_EVENT_WINDOW_DISPLAY_CHANGED, SDL_GetDisplayForWindowPosition(), SDL_GetDisplayIndex(), SDL_MinimizeWindow(), SDL_SendsDisplayChanges(), and SDL_SendWindowEvent().
Referenced by SDL_OnDisplayAdded(), SDL_OnWindowMoved(), and SDL_OnWindowResized().
SDL_CheckWindowDisplayScaleChanged()
void SDL_CheckWindowDisplayScaleChanged (SDL_Window * window) static
{
    float display_scale;
    if (_this->GetWindowContentScale) {
        display_scale = _this->GetWindowContentScale(_this, window);
    } else {
        const float pixel_density = SDL_GetWindowPixelDensity(window);
        const float content_scale = SDL_GetDisplayContentScale(SDL_GetDisplayForWindowPosition(window));
        display_scale = pixel_density * content_scale;
    }
    if (display_scale != window->display_scale) {
        window->display_scale = display_scale;
        SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED, 0, 0);
    }
}
References _this, SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED, SDL_GetDisplayContentScale(), SDL_GetDisplayForWindowPosition(), SDL_GetWindowPixelDensity(), and SDL_SendWindowEvent().
Referenced by SDL_CheckWindowPixelSizeChanged(), and SDL_SetDisplayContentScale().
SDL_CheckWindowPixelSizeChanged()
void SDL_CheckWindowPixelSizeChanged (SDL_Window * window)
{
    int pixel_w = 0, pixel_h = 0;
    SDL_GetWindowSizeInPixels(window, &pixel_w, &pixel_h);
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, pixel_w, pixel_h);
    SDL_CheckWindowDisplayScaleChanged(window);
}
References SDL_CheckWindowDisplayScaleChanged(), SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, SDL_GetWindowSizeInPixels(), and SDL_SendWindowEvent().
Referenced by SDL_CreateWindowWithProperties(), SDL_OnWindowDisplayChanged(), SDL_OnWindowResized(), and SDL_SendWindowEvent().
SDL_CheckWindowSafeAreaChanged()
void SDL_CheckWindowSafeAreaChanged (SDL_Window * window) static
{
    SDL_Rect rect;
    rect.x = window->safe_inset_left;
    rect.y = window->safe_inset_top;
    rect.w = window->w - (window->safe_inset_right + window->safe_inset_left);
    rect.h = window->h - (window->safe_inset_top + window->safe_inset_bottom);
    if (SDL_memcmp(&rect, &window->safe_rect, sizeof(rect)) != 0) {
        SDL_copyp(&window->safe_rect, &rect);
        SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_SAFE_AREA_CHANGED, 0, 0);
    }
}
References SDL_Rect::h, SDL_copyp, SDL_EVENT_WINDOW_SAFE_AREA_CHANGED, SDL_memcmp(), SDL_SendWindowEvent(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_OnWindowResized(), and SDL_SetWindowSafeAreaInsets().
SDL_CleanupWindowTextureData()
void SDLCALL SDL_CleanupWindowTextureData (void * userdata, void * value) static
{
    SDL_WindowTextureData *data = (SDL_WindowTextureData *)value;
    if (data->texture) {
        SDL_DestroyTexture(data->texture);
    }
    if (data->renderer) {
        SDL_DestroyRenderer(data->renderer);
    }
    SDL_free(data->pixels);
    SDL_free(data);
}
References SDL_DestroyRenderer(), SDL_DestroyTexture(), SDL_free(), and SDLCALL.
Referenced by SDL_CreateWindowTexture().
SDL_ClearComposition()
bool SDL_ClearComposition (SDL_Window * window)
Dismiss the composition window/IME without disabling the subsystem.
Parameters
window the window to affect.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
SDL_StopTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    if (_this->ClearComposition) {
        return _this->ClearComposition(_this, window);
    }
    return true;
}
References _this, and CHECK_WINDOW_MAGIC.
SDL_ContextNotSupported()
bool SDL_ContextNotSupported (const char * name) static
{
    return SDL_SetError("%s support is either not configured in SDL "
                        "or not available in current SDL video driver "
                        "(%s) or platform",
                        name,
                        _this->name);
}
References _this, and SDL_SetError().
Referenced by SDL_CreateWindowWithProperties(), and SDL_RecreateWindow().
SDL_CreatePopupWindow()
SDL_Window * SDL_CreatePopupWindow (SDL_Window * parent, int offset_x, int offset_y, int w, int h, SDL_WindowFlags flags)
Create a child popup window of the specified parent window.
The window size is a request and may be different than expected based on the desktop layout and window manager policies. Your application should be prepared to handle a window of any size.
The flags parameter must contain at least one of the following:
SDL_WINDOW_TOOLTIP: The popup window is a tooltip and will not pass any input events.
SDL_WINDOW_POPUP_MENU: The popup window is a popup menu. The topmost popup menu will implicitly gain the keyboard focus.
The following flags are not relevant to popup window creation and will be ignored:
SDL_WINDOW_MINIMIZED
SDL_WINDOW_MAXIMIZED
SDL_WINDOW_FULLSCREEN
SDL_WINDOW_BORDERLESS
The following flags are incompatible with popup window creation and will cause it to fail:
SDL_WINDOW_UTILITY
SDL_WINDOW_MODAL
The parent parameter must be non-null and a valid window. The parent of a popup window can be either a regular, toplevel window, or another popup window.
Popup windows cannot be minimized, maximized, made fullscreen, raised, flash, be made a modal window, be the parent of a toplevel window, or grab the mouse and/or keyboard. Attempts to do so will fail.
Popup windows implicitly do not have a border/decorations and do not appear on the taskbar/dock or in lists of windows such as alt-tab menus.
By default, popup window positions will automatically be constrained to keep the entire window within display bounds. This can be overridden with the SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN property.
By default, popup menus will automatically grab keyboard focus from the parent when shown. This behavior can be overridden by setting the SDL_WINDOW_NOT_FOCUSABLE flag, setting the SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN property to false, or toggling it after creation via the SDL_SetWindowFocusable() function.
If a parent window is hidden or destroyed, any child popup windows will be recursively hidden or destroyed as well. Child popup windows not explicitly hidden will be restored when the parent is shown.
Parameters
parent the parent of the window, must not be NULL.
offset_x the x position of the popup window relative to the origin of the parent.
offset_y the y position of the popup window relative to the origin of the parent window.
w the width of the window.
h the height of the window.
flags SDL_WINDOW_TOOLTIP or SDL_WINDOW_POPUP_MENU, and zero or more additional SDL_WindowFlags OR'd together.
Returns
the window that was created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindow
SDL_CreateWindowWithProperties
SDL_DestroyWindow
SDL_GetWindowParent
{
    SDL_Window *window;
    SDL_PropertiesID props = SDL_CreateProperties();
    // Popups must specify either the tooltip or popup menu window flags
    if (!(flags & (SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU))) {
        SDL_SetError("Popup windows must specify either the 'SDL_WINDOW_TOOLTIP' or the 'SDL_WINDOW_POPUP_MENU' flag");
        return NULL;
    }
    SDL_SetPointerProperty(props, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, parent);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_X_NUMBER, offset_x);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_Y_NUMBER, offset_y);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, w);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, h);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, flags);
    window = SDL_CreateWindowWithProperties(props);
    SDL_DestroyProperties(props);
    return window;
}
References NULL, SDL_CreateProperties(), SDL_CreateWindowWithProperties(), SDL_DestroyProperties(), SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, SDL_PROP_WINDOW_CREATE_X_NUMBER, SDL_PROP_WINDOW_CREATE_Y_NUMBER, SDL_SetError(), SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_WINDOW_POPUP_MENU, and SDL_WINDOW_TOOLTIP.
SDL_CreateWindow()
SDL_Window * SDL_CreateWindow (const char * title, int w, int h, SDL_WindowFlags flags)
Create a window with the specified dimensions and flags.
The window size is a request and may be different than expected based on the desktop layout and window manager policies. Your application should be prepared to handle a window of any size.
flags may be any of the following OR'd together:
SDL_WINDOW_FULLSCREEN: fullscreen window at desktop resolution
SDL_WINDOW_OPENGL: window usable with an OpenGL context
SDL_WINDOW_OCCLUDED: window partially or completely obscured by another window
SDL_WINDOW_HIDDEN: window is not visible
SDL_WINDOW_BORDERLESS: no window decoration
SDL_WINDOW_RESIZABLE: window can be resized
SDL_WINDOW_MINIMIZED: window is minimized
SDL_WINDOW_MAXIMIZED: window is maximized
SDL_WINDOW_MOUSE_GRABBED: window has grabbed mouse focus
SDL_WINDOW_INPUT_FOCUS: window has input focus
SDL_WINDOW_MOUSE_FOCUS: window has mouse focus
SDL_WINDOW_EXTERNAL: window not created by SDL
SDL_WINDOW_MODAL: window is modal
SDL_WINDOW_HIGH_PIXEL_DENSITY: window uses high pixel density back buffer if possible
SDL_WINDOW_MOUSE_CAPTURE: window has mouse captured (unrelated to MOUSE_GRABBED)
SDL_WINDOW_ALWAYS_ON_TOP: window should always be above others
SDL_WINDOW_UTILITY: window should be treated as a utility window, not showing in the task bar and window list
SDL_WINDOW_TOOLTIP: window should be treated as a tooltip and does not get mouse or keyboard focus, requires a parent window
SDL_WINDOW_POPUP_MENU: window should be treated as a popup menu, requires a parent window
SDL_WINDOW_KEYBOARD_GRABBED: window has grabbed keyboard input
SDL_WINDOW_VULKAN: window usable with a Vulkan instance
SDL_WINDOW_METAL: window usable with a Metal instance
SDL_WINDOW_TRANSPARENT: window with transparent buffer
SDL_WINDOW_NOT_FOCUSABLE: window should not be focusable
The SDL_Window is implicitly shown if SDL_WINDOW_HIDDEN is not set.
On Apple's macOS, you must set the NSHighResolutionCapable Info.plist property to YES, otherwise you will not receive a High-DPI OpenGL canvas.
The window pixel size may differ from its window coordinate size if the window is on a high pixel density display. Use SDL_GetWindowSize() to query the client area's size in window coordinates, and SDL_GetWindowSizeInPixels() or SDL_GetRenderOutputSize() to query the drawable size in pixels. Note that the drawable size can vary after the window is created and should be queried again if you get an SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED event.
If the window is created with any of the SDL_WINDOW_OPENGL or SDL_WINDOW_VULKAN flags, then the corresponding LoadLibrary function (SDL_GL_LoadLibrary or SDL_Vulkan_LoadLibrary) is called and the corresponding UnloadLibrary function is called by SDL_DestroyWindow().
If SDL_WINDOW_VULKAN is specified and there isn't a working Vulkan driver, SDL_CreateWindow() will fail, because SDL_Vulkan_LoadLibrary() will fail.
If SDL_WINDOW_METAL is specified on an OS that does not support Metal, SDL_CreateWindow() will fail.
If you intend to use this window with an SDL_Renderer, you should use SDL_CreateWindowAndRenderer() instead of this function, to avoid window flicker.
On non-Apple devices, SDL requires you to either not link to the Vulkan loader or link to a dynamic library version. This limitation may be removed in a future version of SDL.
Parameters
title the title of the window, in UTF-8 encoding.
w the width of the window.
h the height of the window.
flags 0, or one or more SDL_WindowFlags OR'd together.
Returns
the window that was created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindowAndRenderer
SDL_CreatePopupWindow
SDL_CreateWindowWithProperties
SDL_DestroyWindow
{
    SDL_Window *window;
    SDL_PropertiesID props = SDL_CreateProperties();
    if (title && *title) {
        SDL_SetStringProperty(props, SDL_PROP_WINDOW_CREATE_TITLE_STRING, title);
    }
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, w);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, h);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, flags);
    window = SDL_CreateWindowWithProperties(props);
    SDL_DestroyProperties(props);
    return window;
}
References SDL_CreateProperties(), SDL_CreateWindowWithProperties(), SDL_DestroyProperties(), SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, SDL_PROP_WINDOW_CREATE_TITLE_STRING, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, SDL_SetNumberProperty(), and SDL_SetStringProperty().
Referenced by SDL_CreateWindowAndRenderer().
SDL_CreateWindowFramebuffer()
SDL_Surface * SDL_CreateWindowFramebuffer (SDL_Window * window) static
{
    SDL_PixelFormat format = SDL_PIXELFORMAT_UNKNOWN;
    void *pixels = NULL;
    int pitch = 0;
    bool created_framebuffer = false;
    int w, h;
    SDL_GetWindowSizeInPixels(window, &w, &h);
    /* This will switch the video backend from using a software surface to
       using a GPU texture through the 2D render API, if we think this would
       be more efficient. This only checks once, on demand. */
    if (!_this->checked_texture_framebuffer) {
        if (ShouldAttemptTextureFramebuffer()) {
            if (!SDL_CreateWindowTexture(_this, window, &format, &pixels, &pitch)) {
                /* !!! FIXME: if this failed halfway (made renderer, failed to make texture, etc),
                   !!! FIXME:  we probably need to clean this up so it doesn't interfere with
                   !!! FIXME:  a software fallback at the system level (can we blit to an
                   !!! FIXME:  OpenGL window? etc). */
            } else {
                // future attempts will just try to use a texture framebuffer.
                /* !!! FIXME:  maybe we shouldn't override these but check if we used a texture
                   !!! FIXME:  framebuffer at the right places; is it feasible we could have an
                   !!! FIXME:  accelerated OpenGL window and a second ends up in software? */
                _this->CreateWindowFramebuffer = SDL_CreateWindowTexture;
                _this->SetWindowFramebufferVSync = SDL_SetWindowTextureVSync;
                _this->GetWindowFramebufferVSync = SDL_GetWindowTextureVSync;
                _this->UpdateWindowFramebuffer = SDL_UpdateWindowTexture;
                _this->DestroyWindowFramebuffer = SDL_DestroyWindowTexture;
                created_framebuffer = true;
            }
        }
        _this->checked_texture_framebuffer = true; // don't check this again.
    }
    if (!created_framebuffer) {
        if (!_this->CreateWindowFramebuffer || !_this->UpdateWindowFramebuffer) {
            SDL_SetError("Window framebuffer support not available");
            return NULL;
        }
        if (!_this->CreateWindowFramebuffer(_this, window, &format, &pixels, &pitch)) {
            return NULL;
        }
    }
    if (window->surface) {
        // We may have gone recursive and already created the surface
        return window->surface;
    }
    return SDL_CreateSurfaceFrom(w, h, format, pixels, pitch);
}
References _this, NULL, SDL_CreateSurfaceFrom(), SDL_CreateWindowTexture(), SDL_DestroyWindowTexture(), SDL_GetWindowSizeInPixels(), SDL_GetWindowTextureVSync(), SDL_PIXELFORMAT_UNKNOWN, SDL_SetError(), SDL_SetWindowTextureVSync(), SDL_UpdateWindowTexture(), and ShouldAttemptTextureFramebuffer().
Referenced by SDL_GetWindowSurface().
SDL_CreateWindowTexture()
bool SDL_CreateWindowTexture (SDL_VideoDevice * _this, SDL_Window * window, SDL_PixelFormat * format, void ** pixels, int * pitch) static
{
    SDL_PropertiesID props = SDL_GetWindowProperties(window);
    SDL_WindowTextureData *data = (SDL_WindowTextureData *)SDL_GetPointerProperty(props, SDL_PROP_WINDOW_TEXTUREDATA_POINTER, NULL);
    const bool transparent = (window->flags & SDL_WINDOW_TRANSPARENT) ? true : false;
    int i;
    int w, h;
    const SDL_PixelFormat *texture_formats;
    SDL_GetWindowSizeInPixels(window, &w, &h);
    if (!data) {
        SDL_Renderer *renderer = NULL;
        const char *render_driver = NULL;
        // See if there's a render driver being requested
        const char *hint = SDL_GetHint(SDL_HINT_FRAMEBUFFER_ACCELERATION);
        if (hint && *hint != '0' && *hint != '1' &&
            SDL_strcasecmp(hint, "true") != 0 &&
            SDL_strcasecmp(hint, "false") != 0 &&
            SDL_strcasecmp(hint, SDL_SOFTWARE_RENDERER) != 0) {
            render_driver = hint;
        }
        if (!render_driver) {
            render_driver = SDL_GetHint(SDL_HINT_RENDER_DRIVER);
        }
        if (render_driver && SDL_strcasecmp(render_driver, SDL_SOFTWARE_RENDERER) == 0) {
            render_driver = NULL;
        }
        char *render_driver_copy = NULL;
        if (render_driver && *render_driver) {
            render_driver_copy = SDL_strdup(render_driver);
            render_driver = render_driver_copy;
            if (render_driver_copy) {  // turn any "software" requests into "xxxxxxxx" so we don't end up in infinite recursion.
                char *prev = render_driver_copy;
                char *ptr = prev;
                while ((ptr = SDL_strchr(ptr, ',')) != NULL) {
                    *ptr = '\0';
                    const bool is_sw = (SDL_strcasecmp(prev, SDL_SOFTWARE_RENDERER) == 0);
                    *ptr = ',';
                    if (is_sw) {
                        SDL_memset(prev, 'x', SDL_strlen(SDL_SOFTWARE_RENDERER));
                        ptr = prev;
                    } else {
                        ptr++;
                        prev = ptr;
                    }
                }
                if (SDL_strcasecmp(prev, SDL_SOFTWARE_RENDERER) == 0) {
                    SDL_memset(prev, 'x', SDL_strlen(SDL_SOFTWARE_RENDERER));
                }
            }
        }
        // Check to see if there's a specific driver requested
        if (render_driver) {
            renderer = SDL_CreateRenderer(window, render_driver);
            SDL_free(render_driver_copy);
            if (!renderer) {
                // The error for this specific renderer has already been set
                return false;
            }
        } else {
            SDL_assert(render_driver_copy == NULL);
            const int total = SDL_GetNumRenderDrivers();
            for (i = 0; i < total; ++i) {
                const char *name = SDL_GetRenderDriver(i);
                if (name && SDL_strcmp(name, SDL_SOFTWARE_RENDERER) != 0) {
                    renderer = SDL_CreateRenderer(window, name);
                    if (renderer) {
                        break; // this will work.
                    }
                }
            }
            if (!renderer) {
                return SDL_SetError("No hardware accelerated renderers available");
            }
        }
        SDL_assert(renderer != NULL); // should have explicitly checked this above.
        // Create the data after we successfully create the renderer (bug #1116)
        data = (SDL_WindowTextureData *)SDL_calloc(1, sizeof(*data));
        if (!data) {
            SDL_DestroyRenderer(renderer);
            return false;
        }
        if (!SDL_SetPointerPropertyWithCleanup(props, SDL_PROP_WINDOW_TEXTUREDATA_POINTER, data, SDL_CleanupWindowTextureData, NULL)) {
            SDL_DestroyRenderer(renderer);
            return false;
        }
        data->renderer = renderer;
    }
    texture_formats = (const SDL_PixelFormat *)SDL_GetPointerProperty(SDL_GetRendererProperties(data->renderer), SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER, NULL);
    if (!texture_formats) {
        return false;
    }
    // Free any old texture and pixel data
    if (data->texture) {
        SDL_DestroyTexture(data->texture);
        data->texture = NULL;
    }
    SDL_free(data->pixels);
    data->pixels = NULL;
    // Find the first format with or without an alpha channel
    *format = texture_formats[0];
    for (i = 0; texture_formats[i] != SDL_PIXELFORMAT_UNKNOWN; ++i) {
        SDL_PixelFormat texture_format = texture_formats[i];
        if (!SDL_ISPIXELFORMAT_FOURCC(texture_format) &&
            !SDL_ISPIXELFORMAT_10BIT(texture_format) &&
            !SDL_ISPIXELFORMAT_FLOAT(texture_format) &&
            transparent == SDL_ISPIXELFORMAT_ALPHA(texture_format)) {
            *format = texture_format;
            break;
        }
    }
    data->texture = SDL_CreateTexture(data->renderer, *format,
                                      SDL_TEXTUREACCESS_STREAMING,
                                      w, h);
    if (!data->texture) {
        // codechecker_false_positive [Malloc] Static analyzer doesn't realize allocated `data` is saved to SDL_PROP_WINDOW_TEXTUREDATA_POINTER and not leaked here.
        return false; // NOLINT(clang-analyzer-unix.Malloc)
    }
    // Create framebuffer data
    data->bytes_per_pixel = SDL_BYTESPERPIXEL(*format);
    data->pitch = (((w * data->bytes_per_pixel) + 3) & ~3);
    {
        // Make static analysis happy about potential SDL_malloc(0) calls.
        const size_t allocsize = (size_t)h * data->pitch;
        data->pixels = SDL_malloc((allocsize > 0) ? allocsize : 1);
        if (!data->pixels) {
            return false;
        }
    }
    *pixels = data->pixels;
    *pitch = data->pitch;
    // Make sure we're not double-scaling the viewport
    SDL_SetRenderViewport(data->renderer, NULL);
    return true;
}
References _this, NULL, SDL_assert, SDL_BYTESPERPIXEL, SDL_calloc(), SDL_CleanupWindowTextureData(), SDL_CreateRenderer(), SDL_CreateTexture(), SDL_DestroyRenderer(), SDL_DestroyTexture(), SDL_free(), SDL_GetHint(), SDL_GetNumRenderDrivers(), SDL_GetPointerProperty(), SDL_GetRenderDriver(), SDL_GetRendererProperties(), SDL_GetWindowProperties(), SDL_GetWindowSizeInPixels(), SDL_HINT_FRAMEBUFFER_ACCELERATION, SDL_HINT_RENDER_DRIVER, SDL_ISPIXELFORMAT_10BIT, SDL_ISPIXELFORMAT_ALPHA, SDL_ISPIXELFORMAT_FLOAT, SDL_ISPIXELFORMAT_FOURCC, SDL_malloc(), SDL_memset, SDL_PIXELFORMAT_UNKNOWN, SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER, SDL_PROP_WINDOW_TEXTUREDATA_POINTER, SDL_SetError(), SDL_SetPointerPropertyWithCleanup(), SDL_SetRenderViewport(), SDL_SOFTWARE_RENDERER, SDL_strcasecmp(), SDL_strchr(), SDL_strcmp(), SDL_strdup(), SDL_strlen(), SDL_TEXTUREACCESS_STREAMING, and SDL_WINDOW_TRANSPARENT.
Referenced by SDL_CreateWindowFramebuffer().
SDL_CreateWindowWithProperties()
SDL_Window * SDL_CreateWindowWithProperties (SDL_PropertiesID props)
Create a window with the specified properties.
The window size is a request and may be different than expected based on the desktop layout and window manager policies. Your application should be prepared to handle a window of any size.
These are the supported properties:
SDL_PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN: true if the window should be always on top
SDL_PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN: true if the window has no window decoration
SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN: true if the "tooltip" and "menu" window types should be automatically constrained to be entirely within display bounds (default), false if no constraints on the position are desired.
SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN: true if the window will be used with an externally managed graphics context.
SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN: true if the window should accept keyboard input (defaults true)
SDL_PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN: true if the window should start in fullscreen mode at desktop resolution
SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER: the height of the window
SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN: true if the window should start hidden
SDL_PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN: true if the window uses a high pixel density buffer if possible
SDL_PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN: true if the window should start maximized
SDL_PROP_WINDOW_CREATE_MENU_BOOLEAN: true if the window is a popup menu
SDL_PROP_WINDOW_CREATE_METAL_BOOLEAN: true if the window will be used with Metal rendering
SDL_PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN: true if the window should start minimized
SDL_PROP_WINDOW_CREATE_MODAL_BOOLEAN: true if the window is modal to its parent
SDL_PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN: true if the window starts with grabbed mouse focus
SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN: true if the window will be used with OpenGL rendering
SDL_PROP_WINDOW_CREATE_PARENT_POINTER: an SDL_Window that will be the parent of this window, required for windows with the "tooltip", "menu", and "modal" properties
SDL_PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN: true if the window should be resizable
SDL_PROP_WINDOW_CREATE_TITLE_STRING: the title of the window, in UTF-8 encoding
SDL_PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN: true if the window show transparent in the areas with alpha of 0
SDL_PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN: true if the window is a tooltip
SDL_PROP_WINDOW_CREATE_UTILITY_BOOLEAN: true if the window is a utility window, not showing in the task bar and window list
SDL_PROP_WINDOW_CREATE_VULKAN_BOOLEAN: true if the window will be used with Vulkan rendering
SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER: the width of the window
SDL_PROP_WINDOW_CREATE_X_NUMBER: the x position of the window, or SDL_WINDOWPOS_CENTERED, defaults to SDL_WINDOWPOS_UNDEFINED. This is relative to the parent for windows with the "tooltip" or "menu" property set.
SDL_PROP_WINDOW_CREATE_Y_NUMBER: the y position of the window, or SDL_WINDOWPOS_CENTERED, defaults to SDL_WINDOWPOS_UNDEFINED. This is relative to the parent for windows with the "tooltip" or "menu" property set.
These are additional supported properties on macOS:
SDL_PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER: the (__unsafe_unretained) NSWindow associated with the window, if you want to wrap an existing window.
SDL_PROP_WINDOW_CREATE_COCOA_VIEW_POINTER: the (__unsafe_unretained) NSView associated with the window, defaults to [window contentView]
These are additional supported properties on Wayland:
SDL_PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN - true if the application wants to use the Wayland surface for a custom role and does not want it attached to an XDG toplevel window. See [README-wayland](README-wayland) for more information on using custom surfaces.
SDL_PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN - true if the application wants an associated wl_egl_window object to be created and attached to the window, even if the window does not have the OpenGL property or SDL_WINDOW_OPENGL flag set.
SDL_PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER - the wl_surface associated with the window, if you want to wrap an existing window. See [README-wayland](README-wayland) for more information.
These are additional supported properties on Windows:
SDL_PROP_WINDOW_CREATE_WIN32_HWND_POINTER: the HWND associated with the window, if you want to wrap an existing window.
SDL_PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER: optional, another window to share pixel format with, useful for OpenGL windows
These are additional supported properties with X11:
SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER: the X11 Window associated with the window, if you want to wrap an existing window.
The window is implicitly shown if the "hidden" property is not set.
These are additional supported properties with Emscripten:
SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID_STRING: the id given to the canvas element. This should start with a '#' sign
SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING: override the binding element for keyboard inputs for this canvas. The variable can be one of:
"#window": the javascript window object (default)
"#document": the javascript document object
"#screen": the javascript window.screen object
"#canvas": the WebGL canvas element
"#none": Don't bind anything at all
any other string without a leading # sign applies to the element on the page with that ID. Windows with the "tooltip" and "menu" properties are popup windows and have the behaviors and guidelines outlined in SDL_CreatePopupWindow().
If this window is being created to be used with an SDL_Renderer, you should not add a graphics API specific property (SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN, etc), as SDL will handle that internally when it chooses a renderer. However, SDL might need to recreate your window at that point, which may cause the window to appear briefly, and then flicker as it is recreated. The correct approach to this is to create the window with the SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN property set to true, then create the renderer, then show the window with SDL_ShowWindow().
Parameters
props the properties to use.
Returns
the window that was created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProperties
SDL_CreateWindow
SDL_DestroyWindow
{
    SDL_Window *window;
    const char *title = SDL_GetStringProperty(props, SDL_PROP_WINDOW_CREATE_TITLE_STRING, NULL);
    int x = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_X_NUMBER, SDL_WINDOWPOS_UNDEFINED);
    int y = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_Y_NUMBER, SDL_WINDOWPOS_UNDEFINED);
    int w = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, 0);
    int h = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, 0);
    SDL_Window *parent = (SDL_Window *)SDL_GetPointerProperty(props, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, NULL);
    SDL_WindowFlags flags = SDL_GetWindowFlagProperties(props);
    SDL_WindowFlags type_flags, graphics_flags;
    bool undefined_x = false;
    bool undefined_y = false;
    bool external_graphics_context = SDL_GetBooleanProperty(props, SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN, false);
    if (!_this) {
        // Initialize the video system if needed
        if (!SDL_Init(SDL_INIT_VIDEO)) {
            return NULL;
        }
        // Make clang-tidy happy
        if (!_this) {
            return NULL;
        }
    }
    if ((flags & SDL_WINDOW_MODAL) && !SDL_ObjectValid(parent, SDL_OBJECT_TYPE_WINDOW)) {
        SDL_SetError("Modal windows must specify a parent window");
        return NULL;
    }
    if ((flags & (SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU)) != 0) {
        if (!(_this->device_caps & VIDEO_DEVICE_CAPS_HAS_POPUP_WINDOW_SUPPORT)) {
            SDL_Unsupported();
            return NULL;
        }
        // Tooltip and popup menu window must specify a parent window
        if (!SDL_ObjectValid(parent, SDL_OBJECT_TYPE_WINDOW)) {
            SDL_SetError("Tooltip and popup menu windows must specify a parent window");
            return NULL;
        }
        // Remove invalid flags
        flags &= ~(SDL_WINDOW_MINIMIZED | SDL_WINDOW_MAXIMIZED | SDL_WINDOW_FULLSCREEN | SDL_WINDOW_BORDERLESS);
    }
    // Ensure no more than one of these flags is set
    type_flags = flags & (SDL_WINDOW_UTILITY | SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU | SDL_WINDOW_MODAL);
    if (type_flags & (type_flags - 1)) {
        SDL_SetError("Conflicting window type flags specified: 0x%.8x", (unsigned int)type_flags);
        return NULL;
    }
    // Make sure the display list is up to date for window placement
    if (_this->RefreshDisplays) {
        _this->RefreshDisplays(_this);
    }
    // Some platforms can't create zero-sized windows
    if (w < 1) {
        w = 1;
    }
    if (h < 1) {
        h = 1;
    }
    if (SDL_WINDOWPOS_ISUNDEFINED(x) || SDL_WINDOWPOS_ISUNDEFINED(y) ||
        SDL_WINDOWPOS_ISCENTERED(x) || SDL_WINDOWPOS_ISCENTERED(y)) {
        SDL_DisplayID displayID = 0;
        SDL_Rect bounds;
        if ((SDL_WINDOWPOS_ISUNDEFINED(x) || SDL_WINDOWPOS_ISCENTERED(x)) && (x & 0xFFFF)) {
            displayID = (x & 0xFFFF);
        } else if ((SDL_WINDOWPOS_ISUNDEFINED(y) || SDL_WINDOWPOS_ISCENTERED(y)) && (y & 0xFFFF)) {
            displayID = (y & 0xFFFF);
        }
        if (displayID == 0 || SDL_GetDisplayIndex(displayID) < 0) {
            displayID = SDL_GetPrimaryDisplay();
        }
        SDL_zero(bounds);
        SDL_GetDisplayUsableBounds(displayID, &bounds);
        if (w > bounds.w || h > bounds.h) {
            // This window is larger than the usable bounds, just center on the display
            SDL_GetDisplayBounds(displayID, &bounds);
        }
        if (SDL_WINDOWPOS_ISCENTERED(x) || SDL_WINDOWPOS_ISUNDEFINED(x)) {
            if (SDL_WINDOWPOS_ISUNDEFINED(x)) {
                undefined_x = true;
            }
            x = bounds.x + (bounds.w - w) / 2;
        }
        if (SDL_WINDOWPOS_ISCENTERED(y) || SDL_WINDOWPOS_ISUNDEFINED(y)) {
            if (SDL_WINDOWPOS_ISUNDEFINED(y)) {
                undefined_y = true;
            }
            y = bounds.y + (bounds.h - h) / 2;
        }
    }
    // ensure no more than one of these flags is set
    graphics_flags = flags & (SDL_WINDOW_OPENGL | SDL_WINDOW_METAL | SDL_WINDOW_VULKAN);
    if (graphics_flags & (graphics_flags - 1)) {
        SDL_SetError("Conflicting window graphics flags specified: 0x%.8x", (unsigned int)graphics_flags);
        return NULL;
    }
    // Some platforms have certain graphics backends enabled by default
    if (!graphics_flags && !external_graphics_context) {
        flags |= SDL_DefaultGraphicsBackends(_this);
    }
    if (flags & SDL_WINDOW_OPENGL) {
        if (!_this->GL_CreateContext) {
            SDL_ContextNotSupported("OpenGL");
            return NULL;
        }
        if (!SDL_GL_LoadLibrary(NULL)) {
            return NULL;
        }
    }
    if (flags & SDL_WINDOW_VULKAN) {
        if (!_this->Vulkan_CreateSurface) {
            SDL_ContextNotSupported("Vulkan");
            return NULL;
        }
        if (!SDL_Vulkan_LoadLibrary(NULL)) {
            return NULL;
        }
    }
    if (flags & SDL_WINDOW_METAL) {
        if (!_this->Metal_CreateView) {
            SDL_ContextNotSupported("Metal");
            return NULL;
        }
    }
    window = (SDL_Window *)SDL_calloc(1, sizeof(*window));
    if (!window) {
        return NULL;
    }
    SDL_SetObjectValid(window, SDL_OBJECT_TYPE_WINDOW, true);
    window->id = SDL_GetNextObjectID();
    window->floating.x = window->windowed.x = window->x = x;
    window->floating.y = window->windowed.y = window->y = y;
    window->floating.w = window->windowed.w = window->w = w;
    window->floating.h = window->windowed.h = window->h = h;
    window->undefined_x = undefined_x;
    window->undefined_y = undefined_y;
    SDL_VideoDisplay *display = SDL_GetVideoDisplayForWindow(window);
    if (display) {
        SDL_SetWindowHDRProperties(window, &display->HDR, false);
    }
    if (flags & SDL_WINDOW_FULLSCREEN || IsFullscreenOnly(_this)) {
        SDL_Rect bounds;
        SDL_GetDisplayBounds(display ? display->id : SDL_GetPrimaryDisplay(), &bounds);
        window->x = bounds.x;
        window->y = bounds.y;
        window->w = bounds.w;
        window->h = bounds.h;
        window->pending_flags |= SDL_WINDOW_FULLSCREEN;
        flags |= SDL_WINDOW_FULLSCREEN;
    }
    window->flags = ((flags & CREATE_FLAGS) | SDL_WINDOW_HIDDEN);
    window->display_scale = 1.0f;
    window->opacity = 1.0f;
    window->next = _this->windows;
    window->is_destroying = false;
    window->last_displayID = SDL_GetDisplayForWindow(window);
    window->external_graphics_context = external_graphics_context;
    window->constrain_popup = SDL_GetBooleanProperty(props, SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN, true);
    if (_this->windows) {
        _this->windows->prev = window;
    }
    _this->windows = window;
    // Set the parent before creation.
    SDL_UpdateWindowHierarchy(window, parent);
    if (_this->CreateSDLWindow && !_this->CreateSDLWindow(_this, window, props)) {
        PUSH_SDL_ERROR()
        SDL_DestroyWindow(window);
        POP_SDL_ERROR()
        return NULL;
    }
    /* Clear minimized if not on windows, only windows handles it at create rather than FinishWindowCreation,
     * but it's important or window focus will get broken on windows!
     */
#if !defined(SDL_PLATFORM_WINDOWS)
    if (window->flags & SDL_WINDOW_MINIMIZED) {
        window->flags &= ~SDL_WINDOW_MINIMIZED;
    }
#endif
    if (title) {
        SDL_SetWindowTitle(window, title);
    }
    SDL_FinishWindowCreation(window, flags);
    // Make sure window pixel size is up to date
    SDL_CheckWindowPixelSizeChanged(window);
#ifdef SDL_VIDEO_DRIVER_UIKIT
    SDL_UpdateLifecycleObserver();
#endif
    SDL_ClearError();
    return window;
}
References _this, CREATE_FLAGS, SDL_Rect::h, IsFullscreenOnly(), NULL, POP_SDL_ERROR, PUSH_SDL_ERROR, SDL_calloc(), SDL_CheckWindowPixelSizeChanged(), SDL_ClearError(), SDL_ContextNotSupported(), SDL_DefaultGraphicsBackends(), SDL_DestroyWindow(), SDL_FinishWindowCreation(), SDL_GetBooleanProperty(), SDL_GetDisplayBounds(), SDL_GetDisplayForWindow(), SDL_GetDisplayIndex(), SDL_GetDisplayUsableBounds(), SDL_GetNextObjectID(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPrimaryDisplay(), SDL_GetStringProperty(), SDL_GetVideoDisplayForWindow(), SDL_GetWindowFlagProperties(), SDL_GL_LoadLibrary(), SDL_Init(), SDL_INIT_VIDEO, SDL_OBJECT_TYPE_WINDOW, SDL_ObjectValid(), SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN, SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, SDL_PROP_WINDOW_CREATE_TITLE_STRING, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, SDL_PROP_WINDOW_CREATE_X_NUMBER, SDL_PROP_WINDOW_CREATE_Y_NUMBER, SDL_SetError(), SDL_SetObjectValid(), SDL_SetWindowHDRProperties(), SDL_SetWindowTitle(), SDL_Unsupported, SDL_UpdateLifecycleObserver(), SDL_UpdateWindowHierarchy(), SDL_Vulkan_LoadLibrary(), SDL_WINDOW_BORDERLESS, SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_METAL, SDL_WINDOW_MINIMIZED, SDL_WINDOW_MODAL, SDL_WINDOW_OPENGL, SDL_WINDOW_POPUP_MENU, SDL_WINDOW_TOOLTIP, SDL_WINDOW_UTILITY, SDL_WINDOW_VULKAN, SDL_WINDOWPOS_ISCENTERED, SDL_WINDOWPOS_ISUNDEFINED, SDL_WINDOWPOS_UNDEFINED, SDL_zero, VIDEO_DEVICE_CAPS_HAS_POPUP_WINDOW_SUPPORT, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_CreatePopupWindow(), and SDL_CreateWindow().
SDL_DefaultGraphicsBackends()
Uint32 SDL_DefaultGraphicsBackends (SDL_VideoDevice * _this) static
{
#if (defined(SDL_VIDEO_OPENGL) && defined(SDL_PLATFORM_MACOS)) || (defined(SDL_PLATFORM_IOS) && !TARGET_OS_MACCATALYST)
    if (_this->GL_CreateContext) {
        return SDL_WINDOW_OPENGL;
    }
#endif
#if defined(SDL_VIDEO_METAL) && (TARGET_OS_MACCATALYST || defined(SDL_PLATFORM_MACOS) || defined(SDL_PLATFORM_IOS))
    if (_this->Metal_CreateView) {
        return SDL_WINDOW_METAL;
    }
#endif
#if defined(SDL_VIDEO_OPENGL) && defined(SDL_VIDEO_DRIVER_OPENVR)
    if (SDL_strcmp(_this->name, "openvr") == 0) {
        return SDL_WINDOW_OPENGL;
    }
#endif
    return 0;
}
References _this, SDL_strcmp(), SDL_WINDOW_METAL, and SDL_WINDOW_OPENGL.
Referenced by SDL_CreateWindowWithProperties().
SDL_DelVideoDisplay()
void SDL_DelVideoDisplay (SDL_DisplayID displayID, bool send_event)
{
    SDL_VideoDisplay *display;
    int display_index = SDL_GetDisplayIndex(displayID);
    if (display_index < 0) {
        return;
    }
    display = _this->displays[display_index];
    if (send_event) {
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_REMOVED, 0, 0);
    }
    SDL_DestroyProperties(display->props);
    SDL_free(display->name);
    SDL_ResetFullscreenDisplayModes(display);
    SDL_free(display->desktop_mode.internal);
    display->desktop_mode.internal = NULL;
    SDL_free(display->internal);
    display->internal = NULL;
    SDL_free(display);
    if (display_index < (_this->num_displays - 1)) {
        SDL_memmove(&_this->displays[display_index], &_this->displays[display_index + 1], (_this->num_displays - display_index - 1) * sizeof(_this->displays[display_index]));
    }
    --_this->num_displays;
    SDL_UpdateDesktopBounds();
}
References _this, NULL, SDL_DestroyProperties(), SDL_EVENT_DISPLAY_REMOVED, SDL_free(), SDL_GetDisplayIndex(), SDL_memmove, SDL_ResetFullscreenDisplayModes(), SDL_SendDisplayEvent(), and SDL_UpdateDesktopBounds().
Referenced by SDL_VideoQuit().
SDL_DestroyWindow()
void SDL_DestroyWindow (SDL_Window * window)
Destroy a window.
Any child windows owned by the window will be recursively destroyed as well.
Note that on some platforms, the visible window may not actually be removed from the screen until the SDL event loop is pumped again, even though the SDL_Window is no longer valid after this call.
Parameters
window the window to destroy.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreatePopupWindow
SDL_CreateWindow
SDL_CreateWindowWithProperties
{
    CHECK_WINDOW_MAGIC(window,);
    window->is_destroying = true;
    // Destroy any child windows of this window
    while (window->first_child) {
        SDL_DestroyWindow(window->first_child);
    }
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_DESTROYED, 0, 0);
    SDL_Renderer *renderer = SDL_GetRenderer(window);
    if (renderer) {
        SDL_DestroyRendererWithoutFreeing(renderer);
    }
    // Restore video mode, etc.
    SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, true);
    if (!(window->flags & SDL_WINDOW_EXTERNAL)) {
        SDL_HideWindow(window);
    }
    SDL_DestroyProperties(window->text_input_props);
    SDL_DestroyProperties(window->props);
    /* Clear the modal status, but don't unset the parent just yet, as it
     * may be needed later in the destruction process if a backend needs
     * to update the input focus.
     */
    if (_this->SetWindowModal && (window->flags & SDL_WINDOW_MODAL)) {
        _this->SetWindowModal(_this, window, false);
    }
    // Make sure the destroyed window isn't referenced by any display as a fullscreen window.
    for (int i = 0; i < _this->num_displays; ++i) {
        if (_this->displays[i]->fullscreen_window == window) {
            _this->displays[i]->fullscreen_window = NULL;
        }
    }
    // Make sure this window no longer has focus
    if (SDL_GetKeyboardFocus() == window) {
        SDL_SetKeyboardFocus(NULL);
    }
    if ((window->flags & SDL_WINDOW_MOUSE_CAPTURE)) {
        SDL_UpdateMouseCapture(true);
    }
    if (SDL_GetMouseFocus() == window) {
        SDL_SetMouseFocus(NULL);
    }
    SDL_DestroyWindowSurface(window);
    // Make no context current if this is the current context window
    if (window->flags & SDL_WINDOW_OPENGL) {
        if (_this->current_glwin == window) {
            SDL_GL_MakeCurrent(window, NULL);
        }
    }
    if (_this->DestroyWindow) {
        _this->DestroyWindow(_this, window);
    }
    // Unload the graphics libraries after the window is destroyed, which may clean up EGL surfaces
    if (window->flags & SDL_WINDOW_OPENGL) {
        SDL_GL_UnloadLibrary();
    }
    if (window->flags & SDL_WINDOW_VULKAN) {
        SDL_Vulkan_UnloadLibrary();
    }
    if (_this->grabbed_window == window) {
        _this->grabbed_window = NULL; // ungrabbing input.
    }
    if (_this->current_glwin == window) {
        _this->current_glwin = NULL;
    }
    SDL_CompareAndSwapAtomicPointer(&_this->wakeup_window, window, NULL);
    // Now invalidate magic
    SDL_SetObjectValid(window, SDL_OBJECT_TYPE_WINDOW, false);
    // Free memory associated with the window
    SDL_free(window->title);
    SDL_DestroySurface(window->icon);
    // Unlink the window from its siblings.
    SDL_UpdateWindowHierarchy(window, NULL);
    // Unlink the window from the global window list
    if (window->next) {
        window->next->prev = window->prev;
    }
    if (window->prev) {
        window->prev->next = window->next;
    } else {
        _this->windows = window->next;
    }
    SDL_free(window->renderers);
    SDL_free(window);
#ifdef SDL_VIDEO_DRIVER_UIKIT
    SDL_UpdateLifecycleObserver();
#endif
}
References _this, CHECK_WINDOW_MAGIC, NULL, SDL_CompareAndSwapAtomicPointer(), SDL_DestroyProperties(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroySurface(), SDL_DestroyWindow(), SDL_DestroyWindowSurface(), SDL_EVENT_WINDOW_DESTROYED, SDL_free(), SDL_FULLSCREEN_OP_LEAVE, SDL_GetKeyboardFocus(), SDL_GetMouseFocus(), SDL_GetRenderer(), SDL_GL_MakeCurrent(), SDL_GL_UnloadLibrary(), SDL_HideWindow(), SDL_OBJECT_TYPE_WINDOW, SDL_SendWindowEvent(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_SetObjectValid(), SDL_UpdateFullscreenMode(), SDL_UpdateLifecycleObserver(), SDL_UpdateMouseCapture(), SDL_UpdateWindowHierarchy(), SDL_Vulkan_UnloadLibrary(), SDL_WINDOW_EXTERNAL, SDL_WINDOW_MODAL, SDL_WINDOW_MOUSE_CAPTURE, SDL_WINDOW_OPENGL, and SDL_WINDOW_VULKAN.
Referenced by SDL_CreateWindowAndRenderer(), SDL_CreateWindowWithProperties(), SDL_DestroyWindow(), and SDL_VideoQuit().
SDL_DestroyWindowSurface()
bool SDL_DestroyWindowSurface (SDL_Window * window)
Destroy the surface associated with the window.
Parameters
window the window to update.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
SDL_WindowHasSurface
< Surface is referenced internally
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->surface) {
        window->surface->internal_flags &= ~SDL_INTERNAL_SURFACE_DONTFREE;
        SDL_DestroySurface(window->surface);
        window->surface = NULL;
        window->surface_valid = false;
    }
    if (_this->checked_texture_framebuffer) { // never checked? No framebuffer to destroy. Don't risk calling the wrong implementation.
        if (_this->DestroyWindowFramebuffer) {
            _this->DestroyWindowFramebuffer(_this, window);
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, NULL, SDL_DestroySurface(), and SDL_INTERNAL_SURFACE_DONTFREE.
Referenced by SDL_DestroyWindow(), and SDL_RecreateWindow().
SDL_DestroyWindowTexture()
void SDL_DestroyWindowTexture (SDL_VideoDevice * _this, SDL_Window * window) static
{
    SDL_ClearProperty(SDL_GetWindowProperties(window), SDL_PROP_WINDOW_TEXTUREDATA_POINTER);
}
References _this, SDL_ClearProperty(), SDL_GetWindowProperties(), and SDL_PROP_WINDOW_TEXTUREDATA_POINTER.
Referenced by SDL_CreateWindowFramebuffer().
SDL_DisableMouseWarpOnFullscreenTransitions()
bool SDL_DisableMouseWarpOnFullscreenTransitions (SDL_VideoDevice * _this) static
{
    return !!(_this->device_caps & VIDEO_DEVICE_CAPS_DISABLE_MOUSE_WARP_ON_FULLSCREEN_TRANSITIONS);
}
References _this, and VIDEO_DEVICE_CAPS_DISABLE_MOUSE_WARP_ON_FULLSCREEN_TRANSITIONS.
Referenced by SDL_UpdateFullscreenMode().
SDL_DisableScreenSaver()
bool SDL_DisableScreenSaver (void)
Prevent the screen from being blanked by a screen saver.
If you disable the screensaver, it is automatically re-enabled when SDL quits.
The screensaver is disabled by default, but this may by changed by SDL_HINT_VIDEO_ALLOW_SCREENSAVER.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_EnableScreenSaver
SDL_ScreenSaverEnabled
{
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (_this->suspend_screensaver) {
        return true;
    }
    _this->suspend_screensaver = true;
    if (_this->SuspendScreenSaver) {
        return _this->SuspendScreenSaver(_this);
    }
    return SDL_Unsupported();
}
References _this, SDL_UninitializedVideo(), and SDL_Unsupported.
Referenced by SDL_VideoInit().
SDL_DllNotSupported()
bool SDL_DllNotSupported (const char * name) static
{
    return SDL_SetError("No dynamic %s support in current SDL video driver (%s)", name, _this->name);
}
References _this, and SDL_SetError().
Referenced by SDL_GL_LoadLibrary(), and SDL_Vulkan_LoadLibrary().
SDL_DriverSendsHDRChanges()
bool SDL_DriverSendsHDRChanges (SDL_VideoDevice * _this) static
{
    return !!(_this->device_caps & VIDEO_DEVICE_CAPS_SENDS_HDR_CHANGES);
}
References _this, and VIDEO_DEVICE_CAPS_SENDS_HDR_CHANGES.
Referenced by SDL_SetDisplayHDRProperties().
SDL_EGL_GetCurrentConfig()
SDL_EGLConfig SDL_EGL_GetCurrentConfig (void)
Get the currently active EGL config.
Returns
the currently active EGL config or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_VIDEO_OPENGL_EGL
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (!_this->egl_data) {
        SDL_SetError("There is no current EGL display");
        return NULL;
    }
    return _this->egl_data->egl_config;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_GetCurrentDisplay()
SDL_EGLDisplay SDL_EGL_GetCurrentDisplay (void)
Get the currently active EGL display.
Returns
the currently active EGL display or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_VIDEO_OPENGL_EGL
    if (!_this) {
        SDL_UninitializedVideo();
        return EGL_NO_DISPLAY;
    }
    if (!_this->egl_data) {
        SDL_SetError("There is no current EGL display");
        return EGL_NO_DISPLAY;
    }
    return _this->egl_data->egl_display;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, EGL_NO_DISPLAY, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_GetProcAddress()
SDL_FunctionPointer SDL_EGL_GetProcAddress (const char * proc)
Get an EGL library function by name.
If an EGL library is loaded, this function allows applications to get entry points for EGL functions. This is useful to provide to an EGL API and extension loader.
Parameters
proc the name of an EGL function.
Returns
a pointer to the named EGL function. The returned pointer should be cast to the appropriate function signature.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_EGL_GetCurrentDisplay
{
#ifdef SDL_VIDEO_OPENGL_EGL
    SDL_FunctionPointer func;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    func = NULL;
    if (_this->egl_data) {
        func = SDL_EGL_GetProcAddressInternal(_this, proc);
    } else {
        SDL_SetError("No EGL library has been loaded");
    }
    return func;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_GetWindowSurface()
SDL_EGLConfig SDL_EGL_GetWindowSurface (SDL_Window * window)
Get the EGL surface associated with the window.
Parameters
window the window to query.
Returns
the EGLSurface pointer associated with the window, or NULL on failure.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_VIDEO_OPENGL_EGL
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (!_this->egl_data) {
        SDL_SetError("There is no current EGL display");
        return NULL;
    }
    if (_this->GL_GetEGLSurface) {
        return _this->GL_GetEGLSurface(_this, window);
    }
    return NULL;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_SetAttributeCallbacks()
void SDL_EGL_SetAttributeCallbacks (SDL_EGLAttribArrayCallback platformAttribCallback, SDL_EGLIntArrayCallback surfaceAttribCallback, SDL_EGLIntArrayCallback contextAttribCallback, void * userdata)
Sets the callbacks for defining custom EGLAttrib arrays for EGL initialization.
Callbacks that aren't needed can be set to NULL.
NOTE: These callback pointers will be reset after SDL_GL_ResetAttributes.
Parameters
platformAttribCallback callback for attributes to pass to eglGetPlatformDisplay. May be NULL.
surfaceAttribCallback callback for attributes to pass to eglCreateSurface. May be NULL.
contextAttribCallback callback for attributes to pass to eglCreateContext. May be NULL.
userdata a pointer that is passed to the callbacks.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (!_this) {
        return;
    }
    _this->egl_platformattrib_callback = platformAttribCallback;
    _this->egl_surfaceattrib_callback = surfaceAttribCallback;
    _this->egl_contextattrib_callback = contextAttribCallback;
    _this->egl_attrib_callback_userdata = userdata;
}
References _this.
SDL_EnableScreenSaver()
bool SDL_EnableScreenSaver (void)
Allow the screen to be blanked by a screen saver.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DisableScreenSaver
SDL_ScreenSaverEnabled
{
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!_this->suspend_screensaver) {
        return true;
    }
    _this->suspend_screensaver = false;
    if (_this->SuspendScreenSaver) {
        return _this->SuspendScreenSaver(_this);
    }
    return SDL_Unsupported();
}
References _this, SDL_UninitializedVideo(), and SDL_Unsupported.
Referenced by SDL_VideoQuit().
SDL_FinalizeDisplayMode()
void SDL_FinalizeDisplayMode (SDL_DisplayMode * mode) static
{
    // Make sure all the fields are set up correctly
    if (mode->pixel_density <= 0.0f) {
        mode->pixel_density = 1.0f;
    }
    if (mode->refresh_rate_numerator > 0) {
        if (mode->refresh_rate_denominator <= 0) {
            mode->refresh_rate_denominator = 1;
        }
        mode->refresh_rate = ((100 * (Sint64)mode->refresh_rate_numerator) / mode->refresh_rate_denominator) / 100.0f;
    } else {
        SDL_CalculateFraction(mode->refresh_rate, &mode->refresh_rate_numerator, &mode->refresh_rate_denominator);
        mode->refresh_rate = (int)(mode->refresh_rate * 100) / 100.0f;
    }
}
References SDL_DisplayMode::pixel_density, SDL_DisplayMode::refresh_rate, SDL_DisplayMode::refresh_rate_denominator, SDL_DisplayMode::refresh_rate_numerator, and SDL_CalculateFraction().
Referenced by SDL_AddFullscreenDisplayMode(), SDL_AddVideoDisplay(), SDL_GetFullscreenModeMatch(), and SDL_SetDesktopDisplayMode().
SDL_FinishWindowCreation()
void SDL_FinishWindowCreation (SDL_Window * window, SDL_WindowFlags flags) static
{
    PrepareDragAndDropSupport(window);
    if (window->flags & SDL_WINDOW_EXTERNAL) {
        // Whoever has created the window has already applied whatever flags are needed
    } else {
        ApplyWindowFlags(window, flags);
        if (!(flags & SDL_WINDOW_HIDDEN)) {
            SDL_ShowWindow(window);
        }
    }
#if defined(SDL_PLATFORM_LINUX)
    // On Linux the progress state is persisted throughout multiple program runs, so reset state on window creation
    SDL_SetWindowProgressState(window, SDL_PROGRESS_STATE_NONE);
    SDL_SetWindowProgressValue(window, 0.0f);
#endif
}
References ApplyWindowFlags(), PrepareDragAndDropSupport(), SDL_PROGRESS_STATE_NONE, SDL_SetWindowProgressState(), SDL_SetWindowProgressValue(), SDL_ShowWindow(), SDL_WINDOW_EXTERNAL, and SDL_WINDOW_HIDDEN.
Referenced by SDL_CreateWindowWithProperties(), and SDL_RecreateWindow().
SDL_FlashWindow()
bool SDL_FlashWindow (SDL_Window * window, SDL_FlashOperation operation)
Request a window to demand attention from the user.
Parameters
window the window to be flashed.
operation the operation to perform.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (_this->FlashWindow) {
        return _this->FlashWindow(_this, window, operation);
    }
    return SDL_Unsupported();
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_Unsupported.
SDL_GetClosestFullscreenDisplayMode()
bool SDL_GetClosestFullscreenDisplayMode (SDL_DisplayID displayID, int w, int h, float refresh_rate, bool include_high_density_modes, SDL_DisplayMode * closest)
Get the closest match to the requested display mode.
The available display modes are scanned and closest is filled in with the closest mode matching the requested mode and returned. The mode format and refresh rate default to the desktop mode if they are set to 0. The modes are scanned with size being first priority, format being second priority, and finally checking the refresh rate. If all the available modes are too small, then false is returned.
Parameters
displayID the instance ID of the display to query.
w the width in pixels of the desired display mode.
h the height in pixels of the desired display mode.
refresh_rate the refresh rate of the desired display mode, or 0.0f for the desktop refresh rate.
include_high_density_modes boolean to include high density modes in the search.
closest a pointer filled in with the closest display mode equal to or larger than the desired mode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
SDL_GetFullscreenDisplayModes
{
    if (!result) {
        return SDL_InvalidParamError("closest"); // Parameter `result` is called `closest` in the header.
    }
    const SDL_DisplayMode *mode, *closest = NULL;
    float aspect_ratio;
    int i;
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    SDL_zerop(result);
    CHECK_DISPLAY_MAGIC(display, false);
    if (h > 0) {
        aspect_ratio = (float)w / h;
    } else {
        aspect_ratio = 1.0f;
    }
    if (refresh_rate == 0.0f) {
        refresh_rate = display->desktop_mode.refresh_rate;
    }
    SDL_UpdateFullscreenDisplayModes(display);
    for (i = 0; i < display->num_fullscreen_modes; ++i) {
        mode = &display->fullscreen_modes[i];
        if (w > mode->w) {
            // Out of sorted modes large enough here
            break;
        }
        if (h > mode->h) {
            /* Wider, but not tall enough, due to a different aspect ratio.
             * This mode must be skipped, but closer modes may still follow */
            continue;
        }
        if (mode->pixel_density > 1.0f && !include_high_density_modes) {
            continue;
        }
        if (closest) {
            float current_aspect_ratio = (float)mode->w / mode->h;
            float closest_aspect_ratio = (float)closest->w / closest->h;
            if (SDL_fabsf(aspect_ratio - closest_aspect_ratio) < SDL_fabsf(aspect_ratio - current_aspect_ratio)) {
                // The mode we already found has a better aspect ratio match
                continue;
            }
            if (mode->w == closest->w && mode->h == closest->h &&
                SDL_fabsf(closest->refresh_rate - refresh_rate) < SDL_fabsf(mode->refresh_rate - refresh_rate)) {
                /* We already found a mode and the new mode is further from our
                 * refresh rate target */
                continue;
            }
        }
        closest = mode;
    }
    if (!closest) {
        return SDL_SetError("Couldn't find any matching video modes");
    }
    SDL_copyp(result, closest);
    return true;
}
References CHECK_DISPLAY_MAGIC, SDL_DisplayMode::h, NULL, SDL_DisplayMode::pixel_density, SDL_DisplayMode::refresh_rate, SDL_copyp, SDL_fabsf(), SDL_GetVideoDisplay(), SDL_InvalidParamError, SDL_SetError(), SDL_UpdateFullscreenDisplayModes(), SDL_zerop, and SDL_DisplayMode::w.
Referenced by SDL_OnWindowDisplayChanged().
SDL_GetClosestPointOnRect()
void SDL_GetClosestPointOnRect (const SDL_Rect * rect, SDL_Point * point) static
If x, y are outside of rect, snaps them to the closest point inside rect (between rect->x, rect->y, inclusive, and rect->x + w, rect->y + h, exclusive)
{
    const int right = rect->x + rect->w - 1;
    const int bottom = rect->y + rect->h - 1;
    if (point->x < rect->x) {
        point->x = rect->x;
    } else if (point->x > right) {
        point->x = right;
    }
    if (point->y < rect->y) {
        point->y = rect->y;
    } else if (point->y > bottom) {
        point->y = bottom;
    }
}
References bottom, SDL_Rect::h, right, SDL_Rect::w, SDL_Point::x, SDL_Rect::x, SDL_Point::y, and SDL_Rect::y.
Referenced by GetDisplayForRect().
SDL_GetCurrentDisplayMode()
const SDL_DisplayMode * SDL_GetCurrentDisplayMode (SDL_DisplayID displayID)
Get information about the current display mode.
There's a difference between this function and SDL_GetDesktopDisplayMode() when SDL runs fullscreen and has changed the resolution. In that case this function will return the current display mode, and not the previous native display mode.
Parameters
displayID the instance ID of the display to query.
Returns
a pointer to the desktop display mode or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDesktopDisplayMode
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    // Make sure our mode list is updated
    SDL_UpdateFullscreenDisplayModes(display);
    return display->current_mode;
}
References CHECK_DISPLAY_MAGIC, NULL, SDL_GetVideoDisplay(), and SDL_UpdateFullscreenDisplayModes().
Referenced by SDL_GetWindowPixelFormat(), and SDL_GetWindowSizeInPixels().
SDL_GetCurrentDisplayOrientation()
SDL_DisplayOrientation SDL_GetCurrentDisplayOrientation (SDL_DisplayID displayID)
Get the orientation of a display.
Parameters
displayID the instance ID of the display to query.
Returns
the SDL_DisplayOrientation enum value of the display, or SDL_ORIENTATION_UNKNOWN if it isn't available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, SDL_ORIENTATION_UNKNOWN);
    if (display->current_orientation != SDL_ORIENTATION_UNKNOWN) {
        return display->current_orientation;
    } else {
        // Default to landscape if the driver hasn't set it
        return SDL_ORIENTATION_LANDSCAPE;
    }
}
References CHECK_DISPLAY_MAGIC, SDL_GetVideoDisplay(), SDL_ORIENTATION_LANDSCAPE, and SDL_ORIENTATION_UNKNOWN.
SDL_GetCurrentVideoDriver()
const char * SDL_GetCurrentVideoDriver (void)
Get the name of the currently initialized video driver.
The names of drivers are all simple, low-ASCII identifiers, like "cocoa", "x11" or "windows". These never have Unicode characters, and are not meant to be proper names.
Returns
the name of the current video driver or NULL if no driver has been initialized.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumVideoDrivers
SDL_GetVideoDriver
{
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    return _this->name;
}
References _this, NULL, and SDL_UninitializedVideo().
SDL_GetDesktopDisplayMode()
const SDL_DisplayMode * SDL_GetDesktopDisplayMode (SDL_DisplayID displayID)
Get information about the desktop's display mode.
There's a difference between this function and SDL_GetCurrentDisplayMode() when SDL runs fullscreen and has changed the resolution. In that case this function will return the previous native display mode, and not the current display mode.
Parameters
displayID the instance ID of the display to query.
Returns
a pointer to the desktop display mode or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCurrentDisplayMode
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    return &display->desktop_mode;
}
References CHECK_DISPLAY_MAGIC, NULL, and SDL_GetVideoDisplay().
Referenced by SDL_CalculateSimulatedVSyncInterval(), and SDL_GetWindowSizeInPixels().
SDL_GetDisplayBounds()
bool SDL_GetDisplayBounds (SDL_DisplayID displayID, SDL_Rect * rect)
Get the desktop area represented by a display.
The primary display is often located at (0,0), but may be placed at a different location depending on monitor layout.
Parameters
displayID the instance ID of the display to query.
rect the SDL_Rect structure filled in with the display bounds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayUsableBounds
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, false);
    if (!rect) {
        return SDL_InvalidParamError("rect");
    }
    if (_this->GetDisplayBounds) {
        if (_this->GetDisplayBounds(_this, display, rect)) {
            return true;
        }
    }
    // Assume that the displays are left to right
    if (displayID == SDL_GetPrimaryDisplay()) {
        rect->x = 0;
        rect->y = 0;
    } else {
        SDL_GetDisplayBounds(_this->displays[SDL_GetDisplayIndex(displayID) - 1]->id, rect);
        rect->x += rect->w;
    }
    rect->w = display->current_mode->w;
    rect->h = display->current_mode->h;
    return true;
}
References _this, CHECK_DISPLAY_MAGIC, SDL_Rect::h, SDL_GetDisplayBounds(), SDL_GetDisplayIndex(), SDL_GetPrimaryDisplay(), SDL_GetVideoDisplay(), SDL_InvalidParamError, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by GetDisplayForRect(), SDL_CreateWindowWithProperties(), SDL_GetDisplayBounds(), SDL_GetDisplayUsableBounds(), SDL_GetWindowPosition(), SDL_SetWindowPosition(), SDL_UpdateDesktopBounds(), and SDL_UpdateFullscreenMode().
SDL_GetDisplayContentScale()
float SDL_GetDisplayContentScale (SDL_DisplayID displayID)
Get the content scale of a display.
The content scale is the expected scale for content based on the DPI settings of the display. For example, a 4K display might have a 2.0 (200%) display scale, which means that the user expects UI elements to be twice as big on this display, to aid in readability.
After window creation, SDL_GetWindowDisplayScale() should be used to query the content scale factor for individual windows instead of querying the display for a window and calling this function, as the per-window content scale factor may differ from the base value of the display it is on, particularly on high-DPI and/or multi-monitor desktop configurations.
Parameters
displayID the instance ID of the display to query.
Returns
the content scale of the display, or 0.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowDisplayScale
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, 0.0f);
    return display->content_scale;
}
References CHECK_DISPLAY_MAGIC, and SDL_GetVideoDisplay().
Referenced by SDL_CheckWindowDisplayScaleChanged().
SDL_GetDisplayDriverData()
SDL_DisplayData * SDL_GetDisplayDriverData (SDL_DisplayID displayID)
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    return display->internal;
}
References CHECK_DISPLAY_MAGIC, NULL, and SDL_GetVideoDisplay().
Referenced by SDL_GetDisplayDriverDataForWindow().
SDL_GetDisplayDriverDataForWindow()
SDL_DisplayData * SDL_GetDisplayDriverDataForWindow (SDL_Window * window)
{
    return SDL_GetDisplayDriverData(SDL_GetDisplayForWindow(window));
}
References SDL_GetDisplayDriverData(), and SDL_GetDisplayForWindow().
SDL_GetDisplayForPoint()
SDL_DisplayID SDL_GetDisplayForPoint (const SDL_Point * point)
Get the display containing a point.
Parameters
point the point to query.
Returns
the instance ID of the display containing the point or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    if (!point) {
        SDL_InvalidParamError("point");
        return 0;
    }
    return GetDisplayForRect(point->x, point->y, 1, 1);
}
References GetDisplayForRect(), SDL_InvalidParamError, SDL_Point::x, and SDL_Point::y.
SDL_GetDisplayForRect()
SDL_DisplayID SDL_GetDisplayForRect (const SDL_Rect * rect)
Get the display primarily containing a rect.
Parameters
rect the rect to query.
Returns
the instance ID of the display entirely containing the rect or closest to the center of the rect on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    if (!rect) {
        SDL_InvalidParamError("rect");
        return 0;
    }
    return GetDisplayForRect(rect->x, rect->y, rect->w, rect->h);
}
References GetDisplayForRect(), SDL_Rect::h, SDL_InvalidParamError, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
SDL_GetDisplayForWindow()
SDL_DisplayID SDL_GetDisplayForWindow (SDL_Window * window)
Get the display associated with a window.
Parameters
window the window to query.
Returns
the instance ID of the display containing the center of the window on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    SDL_DisplayID displayID = 0;
    CHECK_WINDOW_MAGIC(window, 0);
    /* sdl2-compat calls this function to get a display on which to make the window fullscreen,
     * so pass it the preferred fullscreen display ID in a property.
     */
    SDL_PropertiesID window_props = SDL_GetWindowProperties(window);
    SDL_VideoDisplay *fs_display = SDL_GetVideoDisplayForFullscreenWindow(window);
    if (fs_display) {
        SDL_SetNumberProperty(window_props, SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY, fs_display->id);
    } else {
        SDL_ClearProperty(window_props, SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY);
    }
    // An explicit fullscreen display overrides all
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        displayID = window->current_fullscreen_mode.displayID;
    }
    if (!displayID) {
        displayID = SDL_GetDisplayForWindowPosition(window);
    }
    return displayID;
}
References CHECK_WINDOW_MAGIC, SDL_VideoDisplay::id, SDL_ClearProperty(), SDL_GetDisplayForWindowPosition(), SDL_GetVideoDisplayForFullscreenWindow(), SDL_GetWindowProperties(), SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY, SDL_SetNumberProperty(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_CalculateSimulatedVSyncInterval(), SDL_CreateWindowWithProperties(), SDL_GetDisplayDriverDataForWindow(), SDL_GetVideoDisplayForWindow(), SDL_GetWindowPixelFormat(), SDL_GetWindowPosition(), SDL_GetWindowSizeInPixels(), SDL_SetDisplayHDRProperties(), and SDL_SetWindowPosition().
SDL_GetDisplayForWindowPosition()
SDL_DisplayID SDL_GetDisplayForWindowPosition (SDL_Window * window)
{
    int x, y;
    SDL_DisplayID displayID = 0;
    CHECK_WINDOW_MAGIC(window, 0);
    if (_this->GetDisplayForWindow) {
        displayID = _this->GetDisplayForWindow(_this, window);
    }
    /* A backend implementation may fail to get a display for the window
     * (for example if the window is off-screen), but other code may expect it
     * to succeed in that situation, so we fall back to a generic position-
     * based implementation in that case. */
    SDL_RelativeToGlobalForWindow(window, window->x, window->y, &x, &y);
    if (!displayID) {
        /* Fullscreen windows may be larger than the display if they were moved between differently sized
         * displays and the new position was received before the new size or vice versa. Using the center
         * of the window rect in this case can report the wrong display, so use the origin.
         */
        if (window->flags & SDL_WINDOW_FULLSCREEN) {
            displayID = GetDisplayForRect(x, y, 1, 1);
        } else {
            displayID = GetDisplayForRect(x, y, window->w, window->h);
        }
    }
    if (!displayID) {
        // Use the primary display for a window if we can't find it anywhere else
        displayID = SDL_GetPrimaryDisplay();
    }
    return displayID;
}
References _this, CHECK_WINDOW_MAGIC, GetDisplayForRect(), SDL_GetPrimaryDisplay(), SDL_RelativeToGlobalForWindow(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_CheckWindowDisplayChanged(), SDL_CheckWindowDisplayScaleChanged(), SDL_GetDisplayForWindow(), and SDL_OnWindowDisplayChanged().
SDL_GetDisplayIndex()
int SDL_GetDisplayIndex (SDL_DisplayID displayID)
{
    int display_index;
    if (!_this) {
        SDL_UninitializedVideo();
        return -1;
    }
    for (display_index = 0; display_index < _this->num_displays; ++display_index) {
        if (displayID == _this->displays[display_index]->id) {
            return display_index;
        }
    }
    SDL_SetError("Invalid display");
    return -1;
}
References _this, SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_CheckWindowDisplayChanged(), SDL_CreateWindowWithProperties(), SDL_DelVideoDisplay(), SDL_GetDisplayBounds(), SDL_GetVideoDisplay(), and SDL_SetWindowPosition().
SDL_GetDisplayName()
const char * SDL_GetDisplayName (SDL_DisplayID displayID)
Get the name of a display in UTF-8 encoding.
Parameters
displayID the instance ID of the display to query.
Returns
the name of a display or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    return display->name;
}
References CHECK_DISPLAY_MAGIC, NULL, and SDL_GetVideoDisplay().
SDL_GetDisplayProperties()
SDL_PropertiesID SDL_GetDisplayProperties (SDL_DisplayID displayID)
Get the properties associated with a display.
The following read-only properties are provided by SDL:
SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN: true if the display has HDR headroom above the SDR white point. This is for informational and diagnostic purposes only, as not all platforms provide this information at the display level.
On KMS/DRM:
SDL_PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER: the "panel orientation" property for the display in degrees of clockwise rotation. Note that this is provided only as a hint, and the application is responsible for any coordinate transformations needed to conform to the requested display orientation.
On Wayland:
SDL_PROP_DISPLAY_WAYLAND_WL_OUTPUT_POINTER: the wl_output associated with the display
Parameters
displayID the instance ID of the display to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, 0);
    if (display->props == 0) {
        display->props = SDL_CreateProperties();
    }
    return display->props;
}
References CHECK_DISPLAY_MAGIC, SDL_CreateProperties(), and SDL_GetVideoDisplay().
Referenced by SDL_AddVideoDisplay().
SDL_GetDisplays()
SDL_DisplayID * SDL_GetDisplays (int * count)
Get a list of currently connected displays.
Parameters
count a pointer filled in with the number of displays returned, may be NULL.
Returns
a 0 terminated array of display instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    int i;
    SDL_DisplayID *displays;
    if (!_this) {
        if (count) {
            *count = 0;
        }
        SDL_UninitializedVideo();
        return NULL;
    }
    displays = (SDL_DisplayID *)SDL_malloc((_this->num_displays + 1) * sizeof(*displays));
    if (displays) {
        if (count) {
            *count = _this->num_displays;
        }
        for (i = 0; i < _this->num_displays; ++i) {
            displays[i] = _this->displays[i]->id;
        }
        displays[i] = 0;
    } else {
        if (count) {
            *count = 0;
        }
    }
    return displays;
}
References _this, count, NULL, SDL_malloc(), and SDL_UninitializedVideo().
Referenced by SDL_UpdateDesktopBounds().
SDL_GetDisplayUsableBounds()
bool SDL_GetDisplayUsableBounds (SDL_DisplayID displayID, SDL_Rect * rect)
Get the usable desktop area represented by a display, in screen coordinates.
This is the same area as SDL_GetDisplayBounds() reports, but with portions reserved by the system removed. For example, on Apple's macOS, this subtracts the area occupied by the menu bar and dock.
Setting a window to be fullscreen generally bypasses these unusable areas, so these are good guidelines for the maximum space available to a non-fullscreen window.
Parameters
displayID the instance ID of the display to query.
rect the SDL_Rect structure filled in with the display bounds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, false);
    if (!rect) {
        return SDL_InvalidParamError("rect");
    }
    if (displayID == SDL_GetPrimaryDisplay() && ParseDisplayUsableBoundsHint(rect)) {
        return true;
    }
    if (_this->GetDisplayUsableBounds) {
        if (_this->GetDisplayUsableBounds(_this, display, rect)) {
            return true;
        }
    }
    // Oh well, just give the entire display bounds.
    return SDL_GetDisplayBounds(displayID, rect);
}
References _this, CHECK_DISPLAY_MAGIC, ParseDisplayUsableBoundsHint(), SDL_GetDisplayBounds(), SDL_GetPrimaryDisplay(), SDL_GetVideoDisplay(), and SDL_InvalidParamError.
Referenced by SDL_CreateWindowWithProperties(), and SDL_SetWindowPosition().
SDL_GetFullscreenDisplayModes()
SDL_DisplayMode ** SDL_GetFullscreenDisplayModes (SDL_DisplayID displayID, int * count)
Get a list of fullscreen display modes available on a display.
The display modes are sorted in this priority:
w -> largest to smallest
h -> largest to smallest
bits per pixel -> more colors to fewer colors
packed pixel layout -> largest to smallest
refresh rate -> highest to lowest
pixel density -> lowest to highest
Parameters
displayID the instance ID of the display to query.
count a pointer filled in with the number of display modes returned, may be NULL.
Returns
a NULL terminated array of display mode pointers or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    int i;
    int num_modes;
    SDL_DisplayMode **result;
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    if (count) {
        *count = 0;
    }
    CHECK_DISPLAY_MAGIC(display, NULL);
    SDL_UpdateFullscreenDisplayModes(display);
    num_modes = display->num_fullscreen_modes;
    result = (SDL_DisplayMode **)SDL_malloc((num_modes + 1) * sizeof(*result) + num_modes * sizeof(**result));
    if (result) {
        SDL_DisplayMode *modes = (SDL_DisplayMode *)((Uint8 *)result + ((num_modes + 1) * sizeof(*result)));
        SDL_memcpy(modes, display->fullscreen_modes, num_modes * sizeof(*modes));
        for (i = 0; i < num_modes; ++i) {
            result[i] = modes++;
        }
        result[i] = NULL;
        if (count) {
            *count = num_modes;
        }
    } else {
        if (count) {
            *count = 0;
        }
    }
    return result;
}
References CHECK_DISPLAY_MAGIC, count, NULL, SDL_GetVideoDisplay(), SDL_malloc(), SDL_memcpy, and SDL_UpdateFullscreenDisplayModes().
SDL_GetFullscreenModeMatch()
const SDL_DisplayMode * SDL_GetFullscreenModeMatch (const SDL_DisplayMode * mode) static
{
    SDL_VideoDisplay *display;
    SDL_DisplayMode fullscreen_mode;
    if (mode->w <= 0 || mode->h <= 0) {
        // Use the desktop mode
        return NULL;
    }
    SDL_memcpy(&fullscreen_mode, mode, sizeof(fullscreen_mode));
    if (fullscreen_mode.displayID == 0) {
        fullscreen_mode.displayID = SDL_GetPrimaryDisplay();
    }
    SDL_FinalizeDisplayMode(&fullscreen_mode);
    mode = NULL;
    display = SDL_GetVideoDisplay(fullscreen_mode.displayID);
    if (display) {
        SDL_UpdateFullscreenDisplayModes(display);
        // Search for an exact match
        if (!mode) {
            for (int i = 0; i < display->num_fullscreen_modes; ++i) {
                if (SDL_memcmp(&fullscreen_mode, &display->fullscreen_modes[i], sizeof(fullscreen_mode)) == 0) {
                    mode = &display->fullscreen_modes[i];
                    break;
                }
            }
        }
        // Search for a mode with the same characteristics
        if (!mode) {
            for (int i = 0; i < display->num_fullscreen_modes; ++i) {
                if (cmpmodes(&fullscreen_mode, &display->fullscreen_modes[i]) == 0) {
                    mode = &display->fullscreen_modes[i];
                    break;
                }
            }
        }
    }
    return mode;
}
References cmpmodes(), SDL_DisplayMode::displayID, SDL_DisplayMode::h, NULL, SDL_FinalizeDisplayMode(), SDL_GetPrimaryDisplay(), SDL_GetVideoDisplay(), SDL_memcmp(), SDL_memcpy, SDL_UpdateFullscreenDisplayModes(), and SDL_DisplayMode::w.
Referenced by SDL_GetWindowFullscreenMode(), and SDL_SetWindowFullscreenMode().
SDL_GetGrabbedWindow()
SDL_Window * SDL_GetGrabbedWindow (void)
Get the window that currently has an input grab enabled.
Returns
the window if input is grabbed or NULL otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowMouseGrab
SDL_SetWindowKeyboardGrab
{
    if (_this->grabbed_window &&
        (_this->grabbed_window->flags & (SDL_WINDOW_MOUSE_GRABBED | SDL_WINDOW_KEYBOARD_GRABBED)) != 0) {
        return _this->grabbed_window;
    } else {
        return NULL;
    }
}
References _this, NULL, SDL_WINDOW_KEYBOARD_GRABBED, and SDL_WINDOW_MOUSE_GRABBED.
SDL_GetMessageBoxCount()
int SDL_GetMessageBoxCount (void)
{
    return SDL_GetAtomicInt(&SDL_messagebox_count);
}
References SDL_GetAtomicInt(), and SDL_messagebox_count.
Referenced by SDL_UpdateMouseCapture().
SDL_GetNaturalDisplayOrientation()
SDL_DisplayOrientation SDL_GetNaturalDisplayOrientation (SDL_DisplayID displayID)
Get the orientation of a display when it is unrotated.
Parameters
displayID the instance ID of the display to query.
Returns
the SDL_DisplayOrientation enum value of the display, or SDL_ORIENTATION_UNKNOWN if it isn't available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, SDL_ORIENTATION_UNKNOWN);
    if (display->natural_orientation != SDL_ORIENTATION_UNKNOWN) {
        return display->natural_orientation;
    } else {
        // Default to landscape if the driver hasn't set it
        return SDL_ORIENTATION_LANDSCAPE;
    }
}
References CHECK_DISPLAY_MAGIC, SDL_GetVideoDisplay(), SDL_ORIENTATION_LANDSCAPE, and SDL_ORIENTATION_UNKNOWN.
Referenced by AttemptSensorFusion().
SDL_GetNumVideoDrivers()
int SDL_GetNumVideoDrivers (void)
Get the number of video drivers compiled into SDL.
Returns
the number of built in video drivers.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetVideoDriver
{
    static int num_drivers = -1;
    if (num_drivers >= 0) {
        return num_drivers;
    }
    num_drivers = 0;
    // Build a list of unique video drivers.
    for (int i = 0; bootstrap[i] != NULL; ++i) {
        bool duplicate = false;
        for (int j = 0; j < i; ++j) {
            if (SDL_strcmp(bootstrap[i]->name, bootstrap[j]->name) == 0) {
                duplicate = true;
                break;
            }
        }
        if (!duplicate) {
            deduped_bootstrap[num_drivers++] = bootstrap[i];
        }
    }
    return num_drivers;
}
References bootstrap, deduped_bootstrap, NULL, and SDL_strcmp().
Referenced by SDL_GetVideoDriver().
SDL_GetPrimaryDisplay()
SDL_DisplayID SDL_GetPrimaryDisplay (void)
Return the primary display.
Returns
the instance ID of the primary display on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    if (!_this || _this->num_displays == 0) {
        SDL_UninitializedVideo();
        return 0;
    }
    return _this->displays[0]->id;
}
References _this, and SDL_UninitializedVideo().
Referenced by AttemptSensorFusion(), SDL_CalculateSimulatedVSyncInterval(), SDL_CreateWindowWithProperties(), SDL_GetDisplayBounds(), SDL_GetDisplayForWindowPosition(), SDL_GetDisplayUsableBounds(), SDL_GetFullscreenModeMatch(), SDL_GetVideoDisplayForFullscreenWindow(), and SDL_SetWindowPosition().
SDL_GetSystemTheme()
SDL_SystemTheme SDL_GetSystemTheme (void)
Get the current system theme.
Returns
the current system theme, light, dark, or unknown.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (_this) {
        return _this->system_theme;
    } else {
        return SDL_SYSTEM_THEME_UNKNOWN;
    }
}
References _this, and SDL_SYSTEM_THEME_UNKNOWN.
SDL_GetTextInputArea()
bool SDL_GetTextInputArea (SDL_Window * window, SDL_Rect * rect, int * cursor)
Get the area used to type Unicode text input.
This returns the values previously set by SDL_SetTextInputArea().
Parameters
window the window for which to query the text input area.
rect a pointer to an SDL_Rect filled in with the text input area, may be NULL.
cursor a pointer to the offset of the current cursor location relative to rect->x, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextInputArea
{
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        SDL_copyp(rect, &window->text_input_rect);
    }
    if (cursor) {
        *cursor = window->text_input_cursor;
    }
    return true;
}
References CHECK_WINDOW_MAGIC, and SDL_copyp.
SDL_GetTextInputAutocorrect()
bool SDL_GetTextInputAutocorrect (SDL_PropertiesID props)
{
    return SDL_GetBooleanProperty(props, SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN, true);
}
References SDL_GetBooleanProperty(), and SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN.
SDL_GetTextInputCapitalization()
SDL_Capitalization SDL_GetTextInputCapitalization (SDL_PropertiesID props)
{
    if (SDL_HasProperty(props, SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER)) {
        return (SDL_Capitalization)SDL_GetNumberProperty(props, SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER, SDL_CAPITALIZE_NONE);
    }
    switch (SDL_GetTextInputType(props)) {
    case SDL_TEXTINPUT_TYPE_TEXT:
        return SDL_CAPITALIZE_SENTENCES;
    case SDL_TEXTINPUT_TYPE_TEXT_NAME:
        return SDL_CAPITALIZE_WORDS;
    default:
        return SDL_CAPITALIZE_NONE;
    }
}
References SDL_CAPITALIZE_NONE, SDL_CAPITALIZE_SENTENCES, SDL_CAPITALIZE_WORDS, SDL_GetNumberProperty(), SDL_GetTextInputType(), SDL_HasProperty(), SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER, SDL_TEXTINPUT_TYPE_TEXT, and SDL_TEXTINPUT_TYPE_TEXT_NAME.
SDL_GetTextInputMultiline()
bool SDL_GetTextInputMultiline (SDL_PropertiesID props)
{
    if (SDL_HasProperty(props, SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN)) {
        return SDL_GetBooleanProperty(props, SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN, false);
    }
    if (SDL_GetHintBoolean(SDL_HINT_RETURN_KEY_HIDES_IME, false)) {
        return false;
    } else {
        return true;
    }
}
References SDL_GetBooleanProperty(), SDL_GetHintBoolean(), SDL_HasProperty(), SDL_HINT_RETURN_KEY_HIDES_IME, and SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN.
SDL_GetTextInputType()
SDL_TextInputType SDL_GetTextInputType (SDL_PropertiesID props)
{
    return (SDL_TextInputType)SDL_GetNumberProperty(props, SDL_PROP_TEXTINPUT_TYPE_NUMBER, SDL_TEXTINPUT_TYPE_TEXT);
}
References SDL_GetNumberProperty(), SDL_PROP_TEXTINPUT_TYPE_NUMBER, and SDL_TEXTINPUT_TYPE_TEXT.
Referenced by SDL_GetTextInputCapitalization().
SDL_GetToplevelForKeyboardFocus()
SDL_Window * SDL_GetToplevelForKeyboardFocus (void)
{
    SDL_Window *focus = SDL_GetKeyboardFocus();
    if (focus) {
        // Get the toplevel parent window.
        while (focus->parent) {
            focus = focus->parent;
        }
    }
    return focus;
}
References SDL_Window::parent, and SDL_GetKeyboardFocus().
Referenced by SDL_PromptAssertion().
SDL_GetVideoDevice()
SDL_VideoDevice * SDL_GetVideoDevice (void)
{
    return _this;
}
References _this.
Referenced by GDK_RegisterChangeNotifications(), SDL_CancelClipboardData(), SDL_GetClipboardData(), SDL_GetClipboardMimeTypes(), SDL_GetClipboardText(), SDL_GetPrimarySelectionText(), SDL_GetTouch(), SDL_GPUSelectBackend(), SDL_HasClipboardData(), SDL_HasClipboardText(), SDL_HasPrimarySelectionText(), SDL_PumpEventsInternal(), SDL_SaveClipboardMimeTypes(), SDL_SendWakeupEvent(), SDL_SendWindowEvent(), SDL_SetClipboardData(), SDL_SetClipboardText(), SDL_SetKeyboardFocus(), SDL_SetPrimarySelectionText(), and SDL_WaitEventTimeoutNS().
SDL_GetVideoDisplay()
SDL_VideoDisplay * SDL_GetVideoDisplay (SDL_DisplayID displayID)
{
    int display_index;
    display_index = SDL_GetDisplayIndex(displayID);
    if (display_index < 0) {
        return NULL;
    }
    return _this->displays[display_index];
}
References _this, NULL, and SDL_GetDisplayIndex().
Referenced by SDL_GetClosestFullscreenDisplayMode(), SDL_GetCurrentDisplayMode(), SDL_GetCurrentDisplayOrientation(), SDL_GetDesktopDisplayMode(), SDL_GetDisplayBounds(), SDL_GetDisplayContentScale(), SDL_GetDisplayDriverData(), SDL_GetDisplayName(), SDL_GetDisplayProperties(), SDL_GetDisplayUsableBounds(), SDL_GetFullscreenDisplayModes(), SDL_GetFullscreenModeMatch(), SDL_GetNaturalDisplayOrientation(), SDL_GetVideoDisplayForFullscreenWindow(), and SDL_GetVideoDisplayForWindow().
SDL_GetVideoDisplayForFullscreenWindow()
SDL_VideoDisplay * SDL_GetVideoDisplayForFullscreenWindow (SDL_Window * window)
{
    SDL_DisplayID displayID = 0;
    CHECK_WINDOW_MAGIC(window, 0);
    // An explicit fullscreen display overrides all
    if (window->current_fullscreen_mode.displayID) {
        displayID = window->current_fullscreen_mode.displayID;
    }
    /* This is used to handle the very common pattern of SDL_SetWindowPosition()
     * followed immediately by SDL_SetWindowFullscreen() to make the window fullscreen
     * desktop on a specific display. If the backend doesn't support changing the
     * window position, or an async window manager hasn't yet actually moved the window,
     * the current position won't be updated at the time of the fullscreen call.
     */
    if (!displayID) {
        // Use the pending position and dimensions, if available, otherwise, use the current.
        const int x = window->last_position_pending ? window->pending.x : window->x;
        const int y = window->last_position_pending ? window->pending.y : window->y;
        const int w = window->last_size_pending ? window->pending.w : window->w;
        const int h = window->last_size_pending ? window->pending.h : window->h;
        displayID = GetDisplayForRect(x, y, w, h);
    }
    if (!displayID) {
        // Use the primary display for a window if we can't find it anywhere else
        displayID = SDL_GetPrimaryDisplay();
    }
    return SDL_GetVideoDisplay(displayID);
}
References CHECK_WINDOW_MAGIC, GetDisplayForRect(), SDL_GetPrimaryDisplay(), and SDL_GetVideoDisplay().
Referenced by SDL_GetDisplayForWindow(), and SDL_UpdateFullscreenMode().
SDL_GetVideoDisplayForWindow()
SDL_VideoDisplay * SDL_GetVideoDisplayForWindow (SDL_Window * window)
{
    return SDL_GetVideoDisplay(SDL_GetDisplayForWindow(window));
}
References SDL_GetDisplayForWindow(), and SDL_GetVideoDisplay().
Referenced by SDL_CreateWindowWithProperties().
SDL_GetVideoDriver()
const char * SDL_GetVideoDriver (int index)
Get the name of a built in video driver.
The video drivers are presented in the order in which they are normally checked during initialization.
The names of drivers are all simple, low-ASCII identifiers, like "cocoa", "x11" or "windows". These never have Unicode characters, and are not meant to be proper names.
Parameters
index the index of a video driver.
Returns
the name of the video driver with the given index, or NULL if index is out of bounds.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumVideoDrivers
{
    if (index >= 0 && index < SDL_GetNumVideoDrivers()) {
        return deduped_bootstrap[index]->name;
    }
    SDL_InvalidParamError("index");
    return NULL;
}
References deduped_bootstrap, NULL, SDL_GetNumVideoDrivers(), and SDL_InvalidParamError.
SDL_GetWindowAspectRatio()
bool SDL_GetWindowAspectRatio (SDL_Window * window, float * min_aspect, float * max_aspect)
Get the aspect ratio of a window's client area.
Parameters
window the window to query the width and height from.
min_aspect a pointer filled in with the minimum aspect ratio of the window, may be NULL.
max_aspect a pointer filled in with the maximum aspect ratio of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowAspectRatio
{
    CHECK_WINDOW_MAGIC(window, false);
    if (min_aspect) {
        *min_aspect = window->min_aspect;
    }
    if (max_aspect) {
        *max_aspect = window->max_aspect;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowBordersSize()
bool SDL_GetWindowBordersSize (SDL_Window * window, int * top, int * left, int * bottom, int * right)
Get the size of a window's borders (decorations) around the client area.
Note: If this function fails (returns false), the size values will be initialized to 0, 0, 0, 0 (if a non-NULL pointer is provided), as if the window in question was borderless.
Note: This function may fail on systems where the window has not yet been decorated by the display server (for example, immediately after calling SDL_CreateWindow). It is recommended that you wait at least until the window has been presented and composited, so that the window system has a chance to decorate the window and provide the border dimensions to SDL.
This function also returns false if getting the information is not supported.
Parameters
window the window to query the size values of the border (decorations) from.
top pointer to variable for storing the size of the top border; NULL is permitted.
left pointer to variable for storing the size of the left border; NULL is permitted.
bottom pointer to variable for storing the size of the bottom border; NULL is permitted.
right pointer to variable for storing the size of the right border; NULL is permitted.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSize
{
    int dummy = 0;
    if (!top) {
        top = &dummy;
    }
    if (!left) {
        left = &dummy;
    }
    if (!right) {
        right = &dummy;
    }
    if (!bottom) {
        bottom = &dummy;
    }
    // Always initialize, so applications don't have to care
    *top = *left = *bottom = *right = 0;
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->GetWindowBordersSize) {
        return SDL_Unsupported();
    }
    return _this->GetWindowBordersSize(_this, window, top, left, bottom, right);
}
References _this, bottom, CHECK_WINDOW_MAGIC, left, right, SDL_Unsupported, and top.
SDL_GetWindowDisplayScale()
float SDL_GetWindowDisplayScale (SDL_Window * window)
Get the content display scale relative to a window's pixel size.
This is a combination of the window pixel density and the display content scale, and is the expected scale for displaying content in this window. For example, if a 3840x2160 window had a display scale of 2.0, the user expects the content to take twice as many pixels and be the same physical size as if it were being displayed in a 1920x1080 window with a display scale of 1.0.
Conceptually this value corresponds to the scale display setting, and is updated when that setting is changed, or the window moves to a display with a different scale setting.
Parameters
window the window to query.
Returns
the display scale, or 0.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, 0.0f);
    return window->display_scale;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowFlagProperties()
SDL_WindowFlags SDL_GetWindowFlagProperties (SDL_PropertiesID props) static
{
    unsigned i;
    SDL_WindowFlags flags = (SDL_WindowFlags)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, 0);
    for (i = 0; i < SDL_arraysize(SDL_WindowFlagProperties); ++i) {
        if (SDL_WindowFlagProperties[i].invert_value) {
            if (!SDL_GetBooleanProperty(props, SDL_WindowFlagProperties[i].property_name, true)) {
                flags |= SDL_WindowFlagProperties[i].flag;
            }
        } else {
            if (SDL_GetBooleanProperty(props, SDL_WindowFlagProperties[i].property_name, false)) {
                flags |= SDL_WindowFlagProperties[i].flag;
            }
        }
    }
    return flags;
}
References invert_value, property_name, SDL_arraysize, SDL_GetBooleanProperty(), SDL_GetNumberProperty(), SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, and SDL_WindowFlagProperties.
Referenced by SDL_CreateWindowWithProperties().
SDL_GetWindowFlags()
SDL_WindowFlags SDL_GetWindowFlags (SDL_Window * window)
Get the window flags.
Parameters
window the window to query.
Returns
a mask of the SDL_WindowFlags associated with window.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindow
SDL_HideWindow
SDL_MaximizeWindow
SDL_MinimizeWindow
SDL_SetWindowFullscreen
SDL_SetWindowMouseGrab
SDL_ShowWindow
{
    CHECK_WINDOW_MAGIC(window, 0);
    return window->flags | window->pending_flags;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_CreateRendererWithProperties(), and SDL_RendererEventWatch().
SDL_GetWindowFromID()
SDL_Window * SDL_GetWindowFromID (SDL_WindowID id)
Get a window from a stored ID.
The numeric ID is what SDL_WindowEvent references, and is necessary to map these events to specific SDL_Window objects.
Parameters
id the ID of the window.
Returns
the window associated with id or NULL if it doesn't exist; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowID
{
    SDL_Window *window;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (id) {
        for (window = _this->windows; window; window = window->next) {
            if (window->id == id) {
                return window;
            }
        }
    }
    SDL_SetError("Invalid window ID");
    return NULL;
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_ConvertEventToRenderCoordinates(), and SDL_GetWindowFromEvent().
SDL_GetWindowFullscreenMode()
const SDL_DisplayMode * SDL_GetWindowFullscreenMode (SDL_Window * window)
Query the display mode to use when a window is visible at fullscreen.
Parameters
window the window to query.
Returns
a pointer to the exclusive fullscreen mode to use or NULL for borderless fullscreen desktop mode.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowFullscreenMode
SDL_SetWindowFullscreen
{
    CHECK_WINDOW_MAGIC(window, NULL);
    CHECK_WINDOW_NOT_POPUP(window, NULL);
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        return SDL_GetFullscreenModeMatch(&window->current_fullscreen_mode);
    } else {
        return SDL_GetFullscreenModeMatch(&window->requested_fullscreen_mode);
    }
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, NULL, SDL_GetFullscreenModeMatch(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_GetWindowSizeInPixels(), and SDL_UpdateFullscreenMode().
SDL_GetWindowICCProfile()
void * SDL_GetWindowICCProfile (SDL_Window * window, size_t * size)
Get the raw ICC profile data for the screen the window is currently on.
Parameters
window the window to query.
size the size of the ICC profile.
Returns
the raw ICC profile data on success or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (!_this->GetWindowICCProfile) {
        SDL_Unsupported();
        return NULL;
    }
    return _this->GetWindowICCProfile(_this, window, size);
}
References _this, NULL, and SDL_Unsupported.
SDL_GetWindowID()
SDL_WindowID SDL_GetWindowID (SDL_Window * window)
Get the numeric ID of a window.
The numeric ID is what SDL_WindowEvent references, and is necessary to map these events to specific SDL_Window objects.
Parameters
window the window to query.
Returns
the ID of the window on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFromID
{
    CHECK_WINDOW_MAGIC(window, 0);
    return window->id;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_RendererEventWatch(), SDL_SendTouch(), and SDL_SendTouchMotion().
SDL_GetWindowKeyboardGrab()
bool SDL_GetWindowKeyboardGrab (SDL_Window * window)
Get a window's keyboard grab mode.
Parameters
window the window to query.
Returns
true if keyboard is grabbed, and false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowKeyboardGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    return window == _this->grabbed_window && (_this->grabbed_window->flags & SDL_WINDOW_KEYBOARD_GRABBED);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_KEYBOARD_GRABBED.
SDL_GetWindowMaximumSize()
bool SDL_GetWindowMaximumSize (SDL_Window * window, int * w, int * h)
Get the maximum size of a window's client area.
Parameters
window the window to query.
w a pointer filled in with the maximum width of the window, may be NULL.
h a pointer filled in with the maximum height of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMinimumSize
SDL_SetWindowMaximumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (max_w) {
        *max_w = window->max_w;
    }
    if (max_h) {
        *max_h = window->max_h;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowMinimumSize()
bool SDL_GetWindowMinimumSize (SDL_Window * window, int * w, int * h)
Get the minimum size of a window's client area.
Parameters
window the window to query.
w a pointer filled in with the minimum width of the window, may be NULL.
h a pointer filled in with the minimum height of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMaximumSize
SDL_SetWindowMinimumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (min_w) {
        *min_w = window->min_w;
    }
    if (min_h) {
        *min_h = window->min_h;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowMouseGrab()
bool SDL_GetWindowMouseGrab (SDL_Window * window)
Get a window's mouse grab mode.
Parameters
window the window to query.
Returns
true if mouse is grabbed, and false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMouseRect
SDL_SetWindowMouseRect
SDL_SetWindowMouseGrab
SDL_SetWindowKeyboardGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    return window == _this->grabbed_window && (_this->grabbed_window->flags & SDL_WINDOW_MOUSE_GRABBED);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_MOUSE_GRABBED.
SDL_GetWindowMouseRect()
const SDL_Rect * SDL_GetWindowMouseRect (SDL_Window * window)
Get the mouse confinement rectangle of a window.
Parameters
window the window to query.
Returns
a pointer to the mouse confinement rectangle of a window, or NULL if there isn't one.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowMouseRect
SDL_GetWindowMouseGrab
SDL_SetWindowMouseGrab
{
    CHECK_WINDOW_MAGIC(window, NULL);
    if (SDL_RectEmpty(&window->mouse_rect)) {
        return NULL;
    } else {
        return &window->mouse_rect;
    }
}
References CHECK_WINDOW_MAGIC, NULL, and SDL_RectEmpty().
Referenced by ConstrainMousePosition().
SDL_GetWindowOpacity()
float SDL_GetWindowOpacity (SDL_Window * window)
Get the opacity of a window.
If transparency isn't supported on this platform, opacity will be returned as 1.0f without error.
Parameters
window the window to get the current opacity value from.
Returns
the opacity, (0.0f - transparent, 1.0f - opaque), or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowOpacity
{
    CHECK_WINDOW_MAGIC(window, -1.0f);
    return window->opacity;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowParent()
SDL_Window * SDL_GetWindowParent (SDL_Window * window)
Get parent of a window.
Parameters
window the window to query.
Returns
the parent of the window on success or NULL if the window has no parent.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreatePopupWindow
{
    CHECK_WINDOW_MAGIC(window, NULL);
    return window->parent;
}
References CHECK_WINDOW_MAGIC, and NULL.
SDL_GetWindowPixelDensity()
float SDL_GetWindowPixelDensity (SDL_Window * window)
Get the pixel density of a window.
This is a ratio of pixel size to window size. For example, if the window is 1920x1080 and it has a high density back buffer of 3840x2160 pixels, it would have a pixel density of 2.0.
Parameters
window the window to query.
Returns
the pixel density or 0.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowDisplayScale
{
    int window_w, window_h, pixel_w, pixel_h;
    float pixel_density = 1.0f;
    CHECK_WINDOW_MAGIC(window, 0.0f);
    if (SDL_GetWindowSize(window, &window_w, &window_h) &&
        SDL_GetWindowSizeInPixels(window, &pixel_w, &pixel_h)) {
        pixel_density = (float)pixel_w / window_w;
    }
    return pixel_density;
}
References CHECK_WINDOW_MAGIC, SDL_GetWindowSize(), and SDL_GetWindowSizeInPixels().
Referenced by SDL_CheckWindowDisplayScaleChanged().
SDL_GetWindowPixelFormat()
SDL_PixelFormat SDL_GetWindowPixelFormat (SDL_Window * window)
Get the pixel format associated with the window.
Parameters
window the window to query.
Returns
the pixel format of the window on success or SDL_PIXELFORMAT_UNKNOWN on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_DisplayID displayID;
    const SDL_DisplayMode *mode;
    CHECK_WINDOW_MAGIC(window, SDL_PIXELFORMAT_UNKNOWN);
    displayID = SDL_GetDisplayForWindow(window);
    mode = SDL_GetCurrentDisplayMode(displayID);
    if (mode) {
        return mode->format;
    } else {
        return SDL_PIXELFORMAT_UNKNOWN;
    }
}
References CHECK_WINDOW_MAGIC, SDL_DisplayMode::format, SDL_GetCurrentDisplayMode(), SDL_GetDisplayForWindow(), and SDL_PIXELFORMAT_UNKNOWN.
SDL_GetWindowPosition()
bool SDL_GetWindowPosition (SDL_Window * window, int * x, int * y)
Get the position of a window.
This is the current position of the window as last reported by the windowing system.
If you do not need the value for one of the positions a NULL may be passed in the x or y parameter.
Parameters
window the window to query.
x a pointer filled in with the x position of the window, may be NULL.
y a pointer filled in with the y position of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowPosition
{
    CHECK_WINDOW_MAGIC(window, false);
    // Fullscreen windows are always at their display's origin
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        SDL_DisplayID displayID;
        if (x) {
            *x = 0;
        }
        if (y) {
            *y = 0;
        }
        /* Find the window's monitor and update to the
           monitor offset. */
        displayID = SDL_GetDisplayForWindow(window);
        if (displayID != 0) {
            SDL_Rect bounds;
            SDL_zero(bounds);
            SDL_GetDisplayBounds(displayID, &bounds);
            if (x) {
                *x = bounds.x;
            }
            if (y) {
                *y = bounds.y;
            }
        }
    } else {
        const bool use_pending = (window->flags & SDL_WINDOW_HIDDEN) && window->last_position_pending;
        if (x) {
            *x = use_pending ? window->pending.x : window->x;
        }
        if (y) {
            *y = use_pending ? window->pending.y : window->y;
        }
    }
    return true;
}
References CHECK_WINDOW_MAGIC, SDL_GetDisplayBounds(), SDL_GetDisplayForWindow(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, SDL_zero, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_BLooper::_HandleMouseMove(), and SDL_Fcitx_UpdateTextInputArea().
SDL_GetWindowProgressState()
SDL_ProgressState SDL_GetWindowProgressState (SDL_Window * window)
Get the state of the progress bar for the given windows taskbar icon.
Parameters
window the window to get the current progress state from.
Returns
the progress state, or SDL_PROGRESS_STATE_INVALID on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, SDL_PROGRESS_STATE_INVALID);
    CHECK_WINDOW_NOT_POPUP(window, SDL_PROGRESS_STATE_INVALID);
    return window->progress_state;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_PROGRESS_STATE_INVALID.
SDL_GetWindowProgressValue()
float SDL_GetWindowProgressValue (SDL_Window * window)
Get the value of the progress bar for the given windows taskbar icon.
Parameters
window the window to get the current progress value from.
Returns
the progress value in the range of [0.0f - 1.0f], or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, -1.0f);
    CHECK_WINDOW_NOT_POPUP(window, -1.0f);
    return window->progress_value;
}
References CHECK_WINDOW_MAGIC, and CHECK_WINDOW_NOT_POPUP.
SDL_GetWindowProperties()
SDL_PropertiesID SDL_GetWindowProperties (SDL_Window * window)
Get the properties associated with a window.
The following read-only properties are provided by SDL:
SDL_PROP_WINDOW_SHAPE_POINTER: the surface associated with a shaped window
SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN: true if the window has HDR headroom above the SDR white point. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT: the value of SDR white in the SDL_COLORSPACE_SRGB_LINEAR colorspace. On Windows this corresponds to the SDR white level in scRGB colorspace, and on Apple platforms this is always 1.0 for EDR content. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT: the additional high dynamic range that can be displayed, in terms of the SDR white point. When HDR is not enabled, this will be 1.0. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
On Android:
SDL_PROP_WINDOW_ANDROID_WINDOW_POINTER: the ANativeWindow associated with the window
SDL_PROP_WINDOW_ANDROID_SURFACE_POINTER: the EGLSurface associated with the window
On iOS:
SDL_PROP_WINDOW_UIKIT_WINDOW_POINTER: the (__unsafe_unretained) UIWindow associated with the window
SDL_PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER: the NSInteger tag associated with metal views on the window
SDL_PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER: the OpenGL view's framebuffer object. It must be bound when rendering to the screen using OpenGL.
SDL_PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER: the OpenGL view's renderbuffer object. It must be bound when SDL_GL_SwapWindow is called.
SDL_PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER: the OpenGL view's resolve framebuffer, when MSAA is used.
On KMS/DRM:
SDL_PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER: the device index associated with the window (e.g. the X in /dev/dri/cardX)
SDL_PROP_WINDOW_KMSDRM_DRM_FD_NUMBER: the DRM FD associated with the window
SDL_PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER: the GBM device associated with the window
On macOS:
SDL_PROP_WINDOW_COCOA_WINDOW_POINTER: the (__unsafe_unretained) NSWindow associated with the window
SDL_PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER: the NSInteger tag assocated with metal views on the window
On OpenVR:
SDL_PROP_WINDOW_OPENVR_OVERLAY_ID_NUMBER: the OpenVR Overlay Handle ID for the associated overlay window.
On Vivante:
SDL_PROP_WINDOW_VIVANTE_DISPLAY_POINTER: the EGLNativeDisplayType associated with the window
SDL_PROP_WINDOW_VIVANTE_WINDOW_POINTER: the EGLNativeWindowType associated with the window
SDL_PROP_WINDOW_VIVANTE_SURFACE_POINTER: the EGLSurface associated with the window
On Windows:
SDL_PROP_WINDOW_WIN32_HWND_POINTER: the HWND associated with the window
SDL_PROP_WINDOW_WIN32_HDC_POINTER: the HDC associated with the window
SDL_PROP_WINDOW_WIN32_INSTANCE_POINTER: the HINSTANCE associated with the window
On Wayland:
Note: The xdg_* window objects do not internally persist across window show/hide calls. They will be null if the window is hidden and must be queried each time it is shown.
SDL_PROP_WINDOW_WAYLAND_DISPLAY_POINTER: the wl_display associated with the window
SDL_PROP_WINDOW_WAYLAND_SURFACE_POINTER: the wl_surface associated with the window
SDL_PROP_WINDOW_WAYLAND_VIEWPORT_POINTER: the wp_viewport associated with the window
SDL_PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER: the wl_egl_window associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER: the xdg_surface associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER: the xdg_toplevel role associated with the window
'SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING': the export handle associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER: the xdg_popup role associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER: the xdg_positioner associated with the window, in popup mode
On X11:
SDL_PROP_WINDOW_X11_DISPLAY_POINTER: the X11 Display associated with the window
SDL_PROP_WINDOW_X11_SCREEN_NUMBER: the screen number associated with the window
SDL_PROP_WINDOW_X11_WINDOW_NUMBER: the X11 Window associated with the window
On Emscripten:
SDL_PROP_WINDOW_EMSCRIPTEN_CANVAS_ID_STRING: the id the canvas element will have
SDL_PROP_WINDOW_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING: the keyboard element that associates keyboard events to this window
Parameters
window the window to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, 0);
    if (window->props == 0) {
        window->props = SDL_CreateProperties();
    }
    return window->props;
}
References CHECK_WINDOW_MAGIC, and SDL_CreateProperties().
Referenced by get_x11_window_handle(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroyWindowTexture(), SDL_Fcitx_UpdateTextInputArea(), SDL_GetDisplayForWindow(), SDL_GetRenderer(), SDL_GetWindowTextureVSync(), SDL_RenderApplyWindowShape(), SDL_SetWindowHDRProperties(), SDL_SetWindowShape(), SDL_SetWindowTextureVSync(), SDL_UpdateWindowTexture(), UpdateHDRProperties(), windows_ShowFileDialog(), and windows_ShowFolderDialog().
SDL_GetWindowRelativeMouseMode()
bool SDL_GetWindowRelativeMouseMode (SDL_Window * window)
Query whether relative mouse mode is enabled for a window.
Parameters
window the window to query.
Returns
true if relative mode is enabled for a window or false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowRelativeMouseMode
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->flags & SDL_WINDOW_MOUSE_RELATIVE_MODE) {
        return true;
    } else {
        return false;
    }
}
References CHECK_WINDOW_MAGIC, and SDL_WINDOW_MOUSE_RELATIVE_MODE.
Referenced by SDL_SetWindowRelativeMouseMode().
SDL_GetWindows()
SDL_Window **SDLCALL SDL_GetWindows (int * count)
Get a list of valid windows.
Parameters
count a pointer filled in with the number of windows returned, may be NULL.
Returns
a NULL terminated array of SDL_Window pointers or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (count) {
        *count = 0;
    }
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    SDL_Window *window;
    int num_added = 0;
    int num_windows = 0;
    for (window = _this->windows; window; window = window->next) {
        ++num_windows;
    }
    SDL_Window **windows = (SDL_Window **)SDL_malloc((num_windows + 1) * sizeof(*windows));
    if (!windows) {
        return NULL;
    }
    for (window = _this->windows; window; window = window->next) {
        windows[num_added++] = window;
        if (num_added == num_windows) {
            // Race condition? Multi-threading not supported, ignore it
            break;
        }
    }
    windows[num_added] = NULL;
    if (count) {
        *count = num_added;
    }
    return windows;
}
References _this, count, NULL, SDL_malloc(), SDL_UninitializedVideo(), and SDLCALL.
Referenced by SDL_UnregisterTray().
SDL_GetWindowSafeArea()
bool SDL_GetWindowSafeArea (SDL_Window * window, SDL_Rect * rect)
Get the safe area for this window.
Some devices have portions of the screen which are partially obscured or not interactive, possibly due to on-screen controls, curved edges, camera notches, TV overscan, etc. This function provides the area of the window which is safe to have interactable content. You should continue rendering into the rest of the window, but it should not contain visually important or interactible content.
Parameters
window the window to query.
rect a pointer filled in with the client area that is safe for interactive content.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (rect) {
        SDL_zerop(rect);
    }
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        if (SDL_RectEmpty(&window->safe_rect)) {
            rect->w = window->w;
            rect->h = window->h;
        } else {
            SDL_copyp(rect, &window->safe_rect);
        }
    }
    return true;
}
References CHECK_WINDOW_MAGIC, SDL_Rect::h, SDL_copyp, SDL_RectEmpty(), SDL_zerop, and SDL_Rect::w.
Referenced by SDL_GetRenderSafeArea().
SDL_GetWindowSize()
bool SDL_GetWindowSize (SDL_Window * window, int * w, int * h)
Get the size of a window's client area.
The window pixel size may differ from its window coordinate size if the window is on a high pixel density display. Use SDL_GetWindowSizeInPixels() or SDL_GetRenderOutputSize() to get the real client area size in pixels.
Parameters
window the window to query the width and height from.
w a pointer filled in with the width of the window, may be NULL.
h a pointer filled in with the height of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderOutputSize
SDL_GetWindowSizeInPixels
SDL_SetWindowSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (w) {
        *w = window->w;
    }
    if (h) {
        *h = window->h;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_BLooper::_HandleMouseMove(), SDL_ConvertEventToRenderCoordinates(), SDL_Fcitx_UpdateTextInputArea(), SDL_GetWindowPixelDensity(), SDL_GetWindowSizeInPixels(), and UpdateMainViewDimensions().
SDL_GetWindowSizeInPixels()
bool SDL_GetWindowSizeInPixels (SDL_Window * window, int * w, int * h)
Get the size of a window's client area, in pixels.
Parameters
window the window from which the drawable size should be queried.
w a pointer to variable for storing the width in pixels, may be NULL.
h a pointer to variable for storing the height in pixels, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindow
SDL_GetWindowSize
{
    int filter;
    CHECK_WINDOW_MAGIC(window, false);
    if (!w) {
        w = &filter;
    }
    if (!h) {
        h = &filter;
    }
    if (_this->GetWindowSizeInPixels) {
        _this->GetWindowSizeInPixels(_this, window, w, h);
    } else {
        SDL_DisplayID displayID = SDL_GetDisplayForWindow(window);
        const SDL_DisplayMode *mode;
        SDL_GetWindowSize(window, w, h);
        if ((window->flags & SDL_WINDOW_FULLSCREEN) && SDL_GetWindowFullscreenMode(window)) {
            mode = SDL_GetCurrentDisplayMode(displayID);
        } else {
            mode = SDL_GetDesktopDisplayMode(displayID);
        }
        if (mode) {
            *w = (int)SDL_ceilf(*w * mode->pixel_density);
            *h = (int)SDL_ceilf(*h * mode->pixel_density);
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_DisplayMode::pixel_density, SDL_ceilf(), SDL_GetCurrentDisplayMode(), SDL_GetDesktopDisplayMode(), SDL_GetDisplayForWindow(), SDL_GetWindowFullscreenMode(), SDL_GetWindowSize(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_CheckWindowPixelSizeChanged(), SDL_CreateWindowFramebuffer(), SDL_CreateWindowTexture(), SDL_GetRenderOutputSize(), SDL_GetWindowPixelDensity(), SDL_UpdateWindowSurface(), and SDL_UpdateWindowTexture().
SDL_GetWindowSurface()
SDL_Surface * SDL_GetWindowSurface (SDL_Window * window)
Get the SDL surface associated with the window.
A new surface will be created with the optimal format for the window, if necessary. This surface will be freed when the window is destroyed. Do not free this surface.
This surface will be invalidated if the window is resized. After resizing a window this function must be called again to return a valid surface.
You may not combine this with 3D or the rendering API on this window.
This function is affected by SDL_HINT_FRAMEBUFFER_ACCELERATION.
Parameters
window the window to query.
Returns
the surface associated with the window, or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyWindowSurface
SDL_WindowHasSurface
SDL_UpdateWindowSurface
SDL_UpdateWindowSurfaceRects
< Surface is referenced internally
< Surface is referenced internally
{
    CHECK_WINDOW_MAGIC(window, NULL);
    if (!window->surface_valid) {
        if (window->surface) {
            window->surface->internal_flags &= ~SDL_INTERNAL_SURFACE_DONTFREE;
            SDL_DestroySurface(window->surface);
            window->surface = NULL;
        }
        window->surface = SDL_CreateWindowFramebuffer(window);
        if (window->surface) {
            window->surface_valid = true;
            window->surface->internal_flags |= SDL_INTERNAL_SURFACE_DONTFREE;
        }
    }
    return window->surface;
}
References CHECK_WINDOW_MAGIC, NULL, SDL_CreateWindowFramebuffer(), SDL_DestroySurface(), and SDL_INTERNAL_SURFACE_DONTFREE.
SDL_GetWindowSurfaceVSync()
bool SDL_GetWindowSurfaceVSync (SDL_Window * window, int * vsync)
Get VSync for the window surface.
Parameters
window the window to query.
vsync an int filled with the current vertical refresh sync interval. See SDL_SetWindowSurfaceVSync() for the meaning of the value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowSurfaceVSync
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->GetWindowFramebufferVSync) {
        return SDL_Unsupported();
    }
    return _this->GetWindowFramebufferVSync(_this, window, vsync);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_Unsupported.
SDL_GetWindowTextureVSync()
bool SDL_GetWindowTextureVSync (SDL_VideoDevice * _this, SDL_Window * window, int * vsync) static
{
    SDL_WindowTextureData *data;
    data = (SDL_WindowTextureData *)SDL_GetPointerProperty(SDL_GetWindowProperties(window), SDL_PROP_WINDOW_TEXTUREDATA_POINTER, NULL);
    if (!data) {
        return false;
    }
    if (!data->renderer) {
        return false;
    }
    return SDL_GetRenderVSync(data->renderer, vsync);
}
References _this, NULL, SDL_GetPointerProperty(), SDL_GetRenderVSync(), SDL_GetWindowProperties(), and SDL_PROP_WINDOW_TEXTUREDATA_POINTER.
Referenced by SDL_CreateWindowFramebuffer().
SDL_GetWindowTitle()
const char * SDL_GetWindowTitle (SDL_Window * window)
Get the title of a window.
Parameters
window the window to query.
Returns
the title of the window in UTF-8 format or "" if there is no title.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowTitle
{
    CHECK_WINDOW_MAGIC(window, "");
    return window->title ? window->title : "";
}
References CHECK_WINDOW_MAGIC.
SDL_GL_CreateContext()
SDL_GLContext SDL_GL_CreateContext (SDL_Window * window)
Create an OpenGL context for an OpenGL window, and make it current.
Windows users new to OpenGL should note that, for historical reasons, GL functions added after OpenGL version 1.1 are not available by default. Those functions must be loaded at run-time, either with an OpenGL extension-handling library or with SDL_GL_GetProcAddress() and its related functions.
SDL_GLContext is opaque to the application.
Parameters
window the window to associate with the context.
Returns
the OpenGL context associated with window or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_DestroyContext
SDL_GL_MakeCurrent
{
    SDL_GLContext ctx = NULL;
    CHECK_WINDOW_MAGIC(window, NULL);
    if (!(window->flags & SDL_WINDOW_OPENGL)) {
        SDL_SetError(NOT_AN_OPENGL_WINDOW);
        return NULL;
    }
    ctx = _this->GL_CreateContext(_this, window);
    // Creating a context is assumed to make it current in the SDL driver.
    if (ctx) {
        _this->current_glwin = window;
        _this->current_glctx = ctx;
        SDL_SetTLS(&_this->current_glwin_tls, window, NULL);
        SDL_SetTLS(&_this->current_glctx_tls, ctx, NULL);
    }
    return ctx;
}
References _this, CHECK_WINDOW_MAGIC, NOT_AN_OPENGL_WINDOW, NULL, SDL_SetError(), SDL_SetTLS(), and SDL_WINDOW_OPENGL.
SDL_GL_DeduceMaxSupportedESProfile()
void SDL_GL_DeduceMaxSupportedESProfile (int * major, int * minor)
{
// THIS REQUIRES AN EXISTING GL CONTEXT THAT HAS BEEN MADE CURRENT.
// Please refer to https://bugzilla.libsdl.org/show_bug.cgi?id=3725 for discussion.
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    /* XXX This is fragile; it will break in the event of release of
     * new versions of OpenGL ES.
     */
    if (SDL_GL_ExtensionSupported("GL_ARB_ES3_2_compatibility")) {
        *major = 3;
        *minor = 2;
    } else if (SDL_GL_ExtensionSupported("GL_ARB_ES3_1_compatibility")) {
        *major = 3;
        *minor = 1;
    } else if (SDL_GL_ExtensionSupported("GL_ARB_ES3_compatibility")) {
        *major = 3;
        *minor = 0;
    } else {
        *major = 2;
        *minor = 0;
    }
#endif
}
References SDL_GL_ExtensionSupported().
SDL_GL_DestroyContext()
bool SDL_GL_DestroyContext (SDL_GLContext context)
Delete an OpenGL context.
Parameters
context the OpenGL context to be deleted.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_CreateContext
{
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!context) {
        return SDL_InvalidParamError("context");
    }
    if (SDL_GL_GetCurrentContext() == context) {
        SDL_GL_MakeCurrent(NULL, NULL);
    }
    return _this->GL_DestroyContext(_this, context);
}
References _this, context, NULL, SDL_GL_GetCurrentContext(), SDL_GL_MakeCurrent(), SDL_InvalidParamError, and SDL_UninitializedVideo().
SDL_GL_ExtensionSupported()
bool SDL_GL_ExtensionSupported (const char * extension)
Check if an OpenGL extension is supported for the current context.
This function operates on the current GL context; you must have created a context and it must be current before calling this function. Do not assume that all contexts you create will have the same set of extensions available, or that recreating an existing context will offer the same extensions again.
While it's probably not a massive overhead, this function is not an O(1) operation. Check the extensions you care about after creating the GL context and save that information somewhere instead of calling the function every time you need to know.
Parameters
extension the name of the extension to check.
Returns
true if the extension is supported, false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    PFNGLGETSTRINGPROC glGetStringFunc;
    const char *extensions;
    const char *start;
    const char *where, *terminator;
    // Extension names should not have spaces.
    where = SDL_strchr(extension, ' ');
    if (where || *extension == '\0') {
        return false;
    }
    // See if there's a hint or environment variable override
    start = SDL_GetHint(extension);
    if (start && *start == '0') {
        return false;
    }
    // Lookup the available extensions
    glGetStringFunc = (PFNGLGETSTRINGPROC)SDL_GL_GetProcAddress("glGetString");
    if (!glGetStringFunc) {
        return false;
    }
    if (isAtLeastGL3((const char *)glGetStringFunc(GL_VERSION))) {
        PFNGLGETSTRINGIPROC glGetStringiFunc;
        PFNGLGETINTEGERVPROC glGetIntegervFunc;
        GLint num_exts = 0;
        GLint i;
        glGetStringiFunc = (PFNGLGETSTRINGIPROC)SDL_GL_GetProcAddress("glGetStringi");
        glGetIntegervFunc = (PFNGLGETINTEGERVPROC)SDL_GL_GetProcAddress("glGetIntegerv");
        if ((!glGetStringiFunc) || (!glGetIntegervFunc)) {
            return false;
        }
#ifndef GL_NUM_EXTENSIONS
#define GL_NUM_EXTENSIONS 0x821D
#endif
        glGetIntegervFunc(GL_NUM_EXTENSIONS, &num_exts);
        for (i = 0; i < num_exts; i++) {
            const char *thisext = (const char *)glGetStringiFunc(GL_EXTENSIONS, i);
            if (SDL_strcmp(thisext, extension) == 0) {
                return true;
            }
        }
        return false;
    }
    // Try the old way with glGetString(GL_EXTENSIONS) ...
    extensions = (const char *)glGetStringFunc(GL_EXTENSIONS);
    if (!extensions) {
        return false;
    }
    /*
     * It takes a bit of care to be fool-proof about parsing the OpenGL
     * extensions string. Don't be fooled by sub-strings, etc.
     */
    start = extensions;
    for (;;) {
        where = SDL_strstr(start, extension);
        if (!where) {
            break;
        }
        terminator = where + SDL_strlen(extension);
        if (where == extensions || *(where - 1) == ' ') {
            if (*terminator == ' ' || *terminator == '\0') {
                return true;
            }
        }
        start = terminator;
    }
    return false;
#else
    return false;
#endif
}
References GL_EXTENSIONS, GL_NUM_EXTENSIONS, GL_VERSION, SDL_GetHint(), SDL_GL_GetProcAddress(), SDL_strchr(), SDL_strcmp(), SDL_strlen(), and SDL_strstr().
Referenced by SDL_GL_DeduceMaxSupportedESProfile().
SDL_GL_GetAttribute()
bool SDL_GL_GetAttribute (SDL_GLAttr attr, int * value)
Get the actual value for an attribute from the current context.
Parameters
attr an SDL_GLAttr enum value specifying the OpenGL attribute to get.
value a pointer filled in with the current value of attr.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_ResetAttributes
SDL_GL_SetAttribute
{
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    PFNGLGETERRORPROC glGetErrorFunc;
    GLenum attrib = 0;
    GLenum error = 0;
    /*
     * Some queries in Core Profile desktop OpenGL 3+ contexts require
     * glGetFramebufferAttachmentParameteriv instead of glGetIntegerv. Note that
     * the enums we use for the former function don't exist in OpenGL ES 2, and
     * the function itself doesn't exist prior to OpenGL 3 and OpenGL ES 2.
     */
#ifdef SDL_VIDEO_OPENGL
    PFNGLGETSTRINGPROC glGetStringFunc;
    PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameterivFunc;
    GLenum attachment = GL_BACK_LEFT;
    GLenum attachmentattrib = 0;
#endif
    if (!value) {
        return SDL_InvalidParamError("value");
    }
    // Clear value in any case
    *value = 0;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    switch (attr) {
    case SDL_GL_RED_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE;
#endif
        attrib = GL_RED_BITS;
        break;
    case SDL_GL_BLUE_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE;
#endif
        attrib = GL_BLUE_BITS;
        break;
    case SDL_GL_GREEN_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE;
#endif
        attrib = GL_GREEN_BITS;
        break;
    case SDL_GL_ALPHA_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE;
#endif
        attrib = GL_ALPHA_BITS;
        break;
    case SDL_GL_DOUBLEBUFFER:
#ifdef SDL_VIDEO_OPENGL
        attrib = GL_DOUBLEBUFFER;
        break;
#else
        // OpenGL ES 1.0 and above specifications have EGL_SINGLE_BUFFER
        // parameter which switches double buffer to single buffer. OpenGL ES
        // SDL driver must set proper value after initialization
        *value = _this->gl_config.double_buffer;
        return true;
#endif
    case SDL_GL_DEPTH_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachment = GL_DEPTH;
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE;
#endif
        attrib = GL_DEPTH_BITS;
        break;
    case SDL_GL_STENCIL_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachment = GL_STENCIL;
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE;
#endif
        attrib = GL_STENCIL_BITS;
        break;
#ifdef SDL_VIDEO_OPENGL
    case SDL_GL_ACCUM_RED_SIZE:
        attrib = GL_ACCUM_RED_BITS;
        break;
    case SDL_GL_ACCUM_GREEN_SIZE:
        attrib = GL_ACCUM_GREEN_BITS;
        break;
    case SDL_GL_ACCUM_BLUE_SIZE:
        attrib = GL_ACCUM_BLUE_BITS;
        break;
    case SDL_GL_ACCUM_ALPHA_SIZE:
        attrib = GL_ACCUM_ALPHA_BITS;
        break;
    case SDL_GL_STEREO:
        attrib = GL_STEREO;
        break;
#else
    case SDL_GL_ACCUM_RED_SIZE:
    case SDL_GL_ACCUM_GREEN_SIZE:
    case SDL_GL_ACCUM_BLUE_SIZE:
    case SDL_GL_ACCUM_ALPHA_SIZE:
    case SDL_GL_STEREO:
        // none of these are supported in OpenGL ES
        *value = 0;
        return true;
#endif
    case SDL_GL_MULTISAMPLEBUFFERS:
        attrib = GL_SAMPLE_BUFFERS;
        break;
    case SDL_GL_MULTISAMPLESAMPLES:
        attrib = GL_SAMPLES;
        break;
    case SDL_GL_CONTEXT_RELEASE_BEHAVIOR:
        attrib = GL_CONTEXT_RELEASE_BEHAVIOR;
        break;
    case SDL_GL_BUFFER_SIZE:
    {
        int rsize = 0, gsize = 0, bsize = 0, asize = 0;
        // There doesn't seem to be a single flag in OpenGL for this!
        if (!SDL_GL_GetAttribute(SDL_GL_RED_SIZE, &rsize)) {
            return false;
        }
        if (!SDL_GL_GetAttribute(SDL_GL_GREEN_SIZE, &gsize)) {
            return false;
        }
        if (!SDL_GL_GetAttribute(SDL_GL_BLUE_SIZE, &bsize)) {
            return false;
        }
        if (!SDL_GL_GetAttribute(SDL_GL_ALPHA_SIZE, &asize)) {
            return false;
        }
        *value = rsize + gsize + bsize + asize;
        return true;
    }
    case SDL_GL_ACCELERATED_VISUAL:
    {
        // FIXME: How do we get this information?
        *value = (_this->gl_config.accelerated != 0);
        return true;
    }
    case SDL_GL_RETAINED_BACKING:
    {
        *value = _this->gl_config.retained_backing;
        return true;
    }
    case SDL_GL_CONTEXT_MAJOR_VERSION:
    {
        *value = _this->gl_config.major_version;
        return true;
    }
    case SDL_GL_CONTEXT_MINOR_VERSION:
    {
        *value = _this->gl_config.minor_version;
        return true;
    }
    case SDL_GL_CONTEXT_FLAGS:
    {
        *value = _this->gl_config.flags;
        return true;
    }
    case SDL_GL_CONTEXT_PROFILE_MASK:
    {
        *value = _this->gl_config.profile_mask;
        return true;
    }
    case SDL_GL_SHARE_WITH_CURRENT_CONTEXT:
    {
        *value = _this->gl_config.share_with_current_context;
        return true;
    }
    case SDL_GL_FRAMEBUFFER_SRGB_CAPABLE:
    {
        *value = _this->gl_config.framebuffer_srgb_capable;
        return true;
    }
    case SDL_GL_CONTEXT_NO_ERROR:
    {
        *value = _this->gl_config.no_error;
        return true;
    }
    case SDL_GL_EGL_PLATFORM:
    {
        *value = _this->gl_config.egl_platform;
        return true;
    }
    default:
        return SDL_SetError("Unknown OpenGL attribute");
    }
#ifdef SDL_VIDEO_OPENGL
    glGetStringFunc = (PFNGLGETSTRINGPROC)SDL_GL_GetProcAddress("glGetString");
    if (!glGetStringFunc) {
        return false;
    }
    if (attachmentattrib && isAtLeastGL3((const char *)glGetStringFunc(GL_VERSION))) {
        // glGetFramebufferAttachmentParameteriv needs to operate on the window framebuffer for this, so bind FBO 0 if necessary.
        GLint current_fbo = 0;
        PFNGLGETINTEGERVPROC glGetIntegervFunc = (PFNGLGETINTEGERVPROC) SDL_GL_GetProcAddress("glGetIntegerv");
        PFNGLBINDFRAMEBUFFERPROC glBindFramebufferFunc = (PFNGLBINDFRAMEBUFFERPROC)SDL_GL_GetProcAddress("glBindFramebuffer");
        if (glGetIntegervFunc && glBindFramebufferFunc) {
            glGetIntegervFunc(GL_DRAW_FRAMEBUFFER_BINDING, &current_fbo);
        }
        glGetFramebufferAttachmentParameterivFunc = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)SDL_GL_GetProcAddress("glGetFramebufferAttachmentParameteriv");
        if (glGetFramebufferAttachmentParameterivFunc) {
            if (glBindFramebufferFunc && (current_fbo != 0)) {
                glBindFramebufferFunc(GL_DRAW_FRAMEBUFFER, 0);
            }
            // glGetFramebufferAttachmentParameterivFunc may cause GL_INVALID_OPERATION when querying depth/stencil size if the
            // bits is 0. From the GL docs:
            //      If the value of GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE is GL_NONE, then either no framebuffer is bound to target;
            //      or a default framebuffer is queried, attachment is GL_DEPTH or GL_STENCIL, and the number of depth or stencil bits,
            //      respectively, is zero. In this case querying pname GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME will return zero, and all
            //      other queries will generate an error.
            GLint fbo_type = GL_FRAMEBUFFER_DEFAULT;
            if (attachment == GL_DEPTH || attachment == GL_STENCIL) {
                glGetFramebufferAttachmentParameterivFunc(GL_FRAMEBUFFER, attachment, GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, &fbo_type);
            }
            if (fbo_type != GL_NONE) {
                glGetFramebufferAttachmentParameterivFunc(GL_FRAMEBUFFER, attachment, attachmentattrib, (GLint *)value);
            } else {
                *value = 0;
            }
            if (glBindFramebufferFunc && (current_fbo != 0)) {
                glBindFramebufferFunc(GL_DRAW_FRAMEBUFFER, current_fbo);
            }
        } else {
            return false;
        }
    } else
#endif
    {
        PFNGLGETINTEGERVPROC glGetIntegervFunc = (PFNGLGETINTEGERVPROC)SDL_GL_GetProcAddress("glGetIntegerv");
        if (glGetIntegervFunc) {
            glGetIntegervFunc(attrib, (GLint *)value);
        } else {
            return false;
        }
    }
    glGetErrorFunc = (PFNGLGETERRORPROC)SDL_GL_GetProcAddress("glGetError");
    if (!glGetErrorFunc) {
        return false;
    }
    error = glGetErrorFunc();
    if (error != GL_NO_ERROR) {
        if (error == GL_INVALID_ENUM) {
            return SDL_SetError("OpenGL error: GL_INVALID_ENUM");
        } else if (error == GL_INVALID_VALUE) {
            return SDL_SetError("OpenGL error: GL_INVALID_VALUE");
        }
        return SDL_SetError("OpenGL error: %08X", error);
    }
    // convert GL_CONTEXT_RELEASE_BEHAVIOR values back to SDL_GL_CONTEXT_RELEASE_BEHAVIOR values
    if (attr == SDL_GL_CONTEXT_RELEASE_BEHAVIOR) {
        *value = (*value == GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH) ? SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH : SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE;
    }
    return true;
#else
    return SDL_Unsupported();
#endif // SDL_VIDEO_OPENGL
}
References _this, GL_ACCUM_ALPHA_BITS, GL_ACCUM_BLUE_BITS, GL_ACCUM_GREEN_BITS, GL_ACCUM_RED_BITS, GL_ALPHA_BITS, GL_BACK_LEFT, GL_BLUE_BITS, GL_CONTEXT_RELEASE_BEHAVIOR, GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, GL_DEPTH, GL_DEPTH_BITS, GL_DOUBLEBUFFER, GL_DRAW_FRAMEBUFFER, GL_DRAW_FRAMEBUFFER_BINDING, GL_FRAMEBUFFER, GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE, GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE, GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE, GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE, GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE, GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE, GL_FRAMEBUFFER_DEFAULT, GL_GREEN_BITS, GL_INVALID_ENUM, GL_INVALID_VALUE, GL_NO_ERROR, GL_NONE, GL_RED_BITS, GL_SAMPLE_BUFFERS, GL_SAMPLES, GL_STENCIL, GL_STENCIL_BITS, GL_STEREO, GL_VERSION, SDL_GL_ACCELERATED_VISUAL, SDL_GL_ACCUM_ALPHA_SIZE, SDL_GL_ACCUM_BLUE_SIZE, SDL_GL_ACCUM_GREEN_SIZE, SDL_GL_ACCUM_RED_SIZE, SDL_GL_ALPHA_SIZE, SDL_GL_BLUE_SIZE, SDL_GL_BUFFER_SIZE, SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_MAJOR_VERSION, SDL_GL_CONTEXT_MINOR_VERSION, SDL_GL_CONTEXT_NO_ERROR, SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_RELEASE_BEHAVIOR, SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE, SDL_GL_DEPTH_SIZE, SDL_GL_DOUBLEBUFFER, SDL_GL_EGL_PLATFORM, SDL_GL_FRAMEBUFFER_SRGB_CAPABLE, SDL_GL_GetAttribute(), SDL_GL_GetProcAddress(), SDL_GL_GREEN_SIZE, SDL_GL_MULTISAMPLEBUFFERS, SDL_GL_MULTISAMPLESAMPLES, SDL_GL_RED_SIZE, SDL_GL_RETAINED_BACKING, SDL_GL_SHARE_WITH_CURRENT_CONTEXT, SDL_GL_STENCIL_SIZE, SDL_GL_STEREO, SDL_InvalidParamError, SDL_SetError(), SDL_UninitializedVideo(), and SDL_Unsupported.
Referenced by SDL_GL_GetAttribute().
SDL_GL_GetCurrentContext()
SDL_GLContext SDL_GL_GetCurrentContext (void)
Get the currently active OpenGL context.
Returns
the currently active OpenGL context or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_MakeCurrent
{
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    return (SDL_GLContext)SDL_GetTLS(&_this->current_glctx_tls);
}
References _this, NULL, SDL_GetTLS(), and SDL_UninitializedVideo().
Referenced by SDL_GL_DestroyContext(), SDL_GL_GetSwapInterval(), SDL_GL_MakeCurrent(), and SDL_GL_SetSwapInterval().
SDL_GL_GetCurrentWindow()
SDL_Window * SDL_GL_GetCurrentWindow (void)
Get the currently active OpenGL window.
Returns
the currently active OpenGL window on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    return (SDL_Window *)SDL_GetTLS(&_this->current_glwin_tls);
}
References _this, NULL, SDL_GetTLS(), and SDL_UninitializedVideo().
Referenced by SDL_GL_MakeCurrent(), and SDL_GL_SwapWindow().
SDL_GL_GetProcAddress()
SDL_FunctionPointer SDL_GL_GetProcAddress (const char * proc)
Get an OpenGL function by name.
If the GL library is loaded at runtime with SDL_GL_LoadLibrary(), then all GL functions must be retrieved this way. Usually this is used to retrieve function pointers to OpenGL extensions.
There are some quirks to looking up OpenGL functions that require some extra care from the application. If you code carefully, you can handle these quirks without any platform-specific code, though:
On Windows, function pointers are specific to the current GL context; this means you need to have created a GL context and made it current before calling SDL_GL_GetProcAddress(). If you recreate your context or create a second context, you should assume that any existing function pointers aren't valid to use with it. This is (currently) a Windows-specific limitation, and in practice lots of drivers don't suffer this limitation, but it is still the way the wgl API is documented to work and you should expect crashes if you don't respect it. Store a copy of the function pointers that comes and goes with context lifespan.
On X11, function pointers returned by this function are valid for any context, and can even be looked up before a context is created at all. This means that, for at least some common OpenGL implementations, if you look up a function that doesn't exist, you'll get a non-NULL result that is NOT safe to call. You must always make sure the function is actually available for a given GL context before calling it, by checking for the existence of the appropriate extension with SDL_GL_ExtensionSupported(), or verifying that the version of OpenGL you're using offers the function as core functionality.
Some OpenGL drivers, on all platforms, will return NULL if a function isn't supported, but you can't count on this behavior. Check for extensions you use, and if you get a NULL anyway, act as if that extension wasn't available. This is probably a bug in the driver, but you can code defensively for this scenario anyhow.
Just because you're on Linux/Unix, don't assume you'll be using X11. Next-gen display servers are waiting to replace it, and may or may not make the same promises about function pointers.
OpenGL function pointers must be declared APIENTRY as in the example code. This will ensure the proper calling convention is followed on platforms where this matters (Win32) thereby avoiding stack corruption.
Parameters
proc the name of an OpenGL function.
Returns
a pointer to the named OpenGL function. The returned pointer should be cast to the appropriate function signature.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_ExtensionSupported
SDL_GL_LoadLibrary
SDL_GL_UnloadLibrary
{
    SDL_FunctionPointer func;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    func = NULL;
    if (_this->GL_GetProcAddress) {
        if (_this->gl_config.driver_loaded) {
            func = _this->GL_GetProcAddress(_this, proc);
        } else {
            SDL_SetError("No GL driver has been loaded");
        }
    } else {
        SDL_SetError("No dynamic GL support in current SDL video driver (%s)", _this->name);
    }
    return func;
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_GL_ExtensionSupported(), and SDL_GL_GetAttribute().
SDL_GL_GetSwapInterval()
bool SDL_GL_GetSwapInterval (int * interval)
Get the swap interval for the current OpenGL context.
If the system can't determine the swap interval, or there isn't a valid current context, this function will set *interval to 0 as a safe default.
Parameters
interval output interval value. 0 if there is no vertical retrace synchronization, 1 if the buffer swap is synchronized with the vertical retrace, and -1 if late swaps happen immediately instead of waiting for the next retrace.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_SetSwapInterval
{
    if (!interval) {
       return SDL_InvalidParamError("interval");
    }
    *interval = 0;
    if (!_this) {
        return SDL_SetError("no video driver");
    } else if (SDL_GL_GetCurrentContext() == NULL) {
        return SDL_SetError("no current context");
    } else if (_this->GL_GetSwapInterval) {
        return _this->GL_GetSwapInterval(_this, interval);
    } else {
        return SDL_SetError("not implemented");
    }
}
References _this, NULL, SDL_GL_GetCurrentContext(), SDL_InvalidParamError, and SDL_SetError().
SDL_GL_LoadLibrary()
bool SDL_GL_LoadLibrary (const char * path)
Dynamically load an OpenGL library.
This should be done after initializing the video driver, but before creating any OpenGL windows. If no OpenGL library is loaded, the default library will be loaded upon creation of the first OpenGL window.
If you do this, you need to retrieve all of the GL functions used in your program from the dynamic library using SDL_GL_GetProcAddress().
Parameters
path the platform dependent OpenGL library name, or NULL to open the default OpenGL library.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetProcAddress
SDL_GL_UnloadLibrary
{
    bool result;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (_this->gl_config.driver_loaded) {
        if (path && SDL_strcmp(path, _this->gl_config.driver_path) != 0) {
            return SDL_SetError("OpenGL library already loaded");
        }
        result = true;
    } else {
        if (!_this->GL_LoadLibrary) {
            return SDL_DllNotSupported("OpenGL");
        }
        result = _this->GL_LoadLibrary(_this, path);
    }
    if (result) {
        ++_this->gl_config.driver_loaded;
    } else {
        if (_this->GL_UnloadLibrary) {
            _this->GL_UnloadLibrary(_this);
        }
    }
    return result;
}
References _this, SDL_DllNotSupported(), SDL_SetError(), SDL_strcmp(), and SDL_UninitializedVideo().
Referenced by SDL_CreateWindowWithProperties(), and SDL_RecreateWindow().
SDL_GL_MakeCurrent()
bool SDL_GL_MakeCurrent (SDL_Window * window, SDL_GLContext context)
Set up an OpenGL context for rendering into an OpenGL window.
The context must have been created with a compatible window.
Parameters
window the window to associate with the context.
context the OpenGL context to associate with the window.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_CreateContext
{
    bool result;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (window == SDL_GL_GetCurrentWindow() &&
        context == SDL_GL_GetCurrentContext()) {
        // We're already current.
        return true;
    }
    if (!context) {
        window = NULL;
    } else if (window) {
        CHECK_WINDOW_MAGIC(window, false);
        if (!(window->flags & SDL_WINDOW_OPENGL)) {
            return SDL_SetError(NOT_AN_OPENGL_WINDOW);
        }
    } else if (!_this->gl_allow_no_surface) {
        return SDL_SetError("Use of OpenGL without a window is not supported on this platform");
    }
    result = _this->GL_MakeCurrent(_this, window, context);
    if (result) {
        _this->current_glwin = window;
        _this->current_glctx = context;
        SDL_SetTLS(&_this->current_glwin_tls, window, NULL);
        SDL_SetTLS(&_this->current_glctx_tls, context, NULL);
    }
    return result;
}
References _this, CHECK_WINDOW_MAGIC, context, NOT_AN_OPENGL_WINDOW, NULL, SDL_GL_GetCurrentContext(), SDL_GL_GetCurrentWindow(), SDL_SetError(), SDL_SetTLS(), SDL_UninitializedVideo(), and SDL_WINDOW_OPENGL.
Referenced by SDL_DestroyWindow(), and SDL_GL_DestroyContext().
SDL_GL_ResetAttributes()
void SDL_GL_ResetAttributes (void)
Reset all previously set OpenGL context attributes to their default values.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetAttribute
SDL_GL_SetAttribute
{
    if (!_this) {
        return;
    }
    _this->egl_platformattrib_callback = NULL;
    _this->egl_surfaceattrib_callback = NULL;
    _this->egl_contextattrib_callback = NULL;
    _this->egl_attrib_callback_userdata = NULL;
    _this->gl_config.red_size = 8;
    _this->gl_config.green_size = 8;
    _this->gl_config.blue_size = 8;
    _this->gl_config.alpha_size = 8;
    _this->gl_config.buffer_size = 0;
    _this->gl_config.depth_size = 16;
    _this->gl_config.stencil_size = 0;
    _this->gl_config.double_buffer = 1;
    _this->gl_config.accum_red_size = 0;
    _this->gl_config.accum_green_size = 0;
    _this->gl_config.accum_blue_size = 0;
    _this->gl_config.accum_alpha_size = 0;
    _this->gl_config.stereo = 0;
    _this->gl_config.multisamplebuffers = 0;
    _this->gl_config.multisamplesamples = 0;
    _this->gl_config.floatbuffers = 0;
    _this->gl_config.retained_backing = 1;
    _this->gl_config.accelerated = -1; // accelerated or not, both are fine
#ifdef SDL_VIDEO_OPENGL
    _this->gl_config.major_version = 2;
    _this->gl_config.minor_version = 1;
    _this->gl_config.profile_mask = 0;
#elif defined(SDL_VIDEO_OPENGL_ES2)
    _this->gl_config.major_version = 2;
    _this->gl_config.minor_version = 0;
    _this->gl_config.profile_mask = SDL_GL_CONTEXT_PROFILE_ES;
#elif defined(SDL_VIDEO_OPENGL_ES)
    _this->gl_config.major_version = 1;
    _this->gl_config.minor_version = 1;
    _this->gl_config.profile_mask = SDL_GL_CONTEXT_PROFILE_ES;
#endif
    if (_this->GL_DefaultProfileConfig) {
        _this->GL_DefaultProfileConfig(_this, &_this->gl_config.profile_mask,
                                       &_this->gl_config.major_version,
                                       &_this->gl_config.minor_version);
    }
    _this->gl_config.flags = 0;
    _this->gl_config.framebuffer_srgb_capable = 0;
    _this->gl_config.no_error = 0;
    _this->gl_config.release_behavior = SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH;
    _this->gl_config.reset_notification = SDL_GL_CONTEXT_RESET_NO_NOTIFICATION;
    _this->gl_config.share_with_current_context = 0;
    _this->gl_config.egl_platform = 0;
}
References _this, NULL, SDL_GL_CONTEXT_PROFILE_ES, SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, and SDL_GL_CONTEXT_RESET_NO_NOTIFICATION.
Referenced by SDL_VideoInit().
SDL_GL_SetAttribute()
bool SDL_GL_SetAttribute (SDL_GLAttr attr, int value)
Set an OpenGL window attribute before window creation.
This function sets the OpenGL attribute attr to value. The requested attributes should be set before creating an OpenGL window. You should use SDL_GL_GetAttribute() to check the values after creating the OpenGL context, since the values obtained can differ from the requested ones.
Parameters
attr an SDL_GLAttr enum value specifying the OpenGL attribute to set.
value the desired value for the attribute.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetAttribute
SDL_GL_ResetAttributes
{
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    bool result;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    result = true;
    switch (attr) {
    case SDL_GL_RED_SIZE:
        _this->gl_config.red_size = value;
        break;
    case SDL_GL_GREEN_SIZE:
        _this->gl_config.green_size = value;
        break;
    case SDL_GL_BLUE_SIZE:
        _this->gl_config.blue_size = value;
        break;
    case SDL_GL_ALPHA_SIZE:
        _this->gl_config.alpha_size = value;
        break;
    case SDL_GL_DOUBLEBUFFER:
        _this->gl_config.double_buffer = value;
        break;
    case SDL_GL_BUFFER_SIZE:
        _this->gl_config.buffer_size = value;
        break;
    case SDL_GL_DEPTH_SIZE:
        _this->gl_config.depth_size = value;
        break;
    case SDL_GL_STENCIL_SIZE:
        _this->gl_config.stencil_size = value;
        break;
    case SDL_GL_ACCUM_RED_SIZE:
        _this->gl_config.accum_red_size = value;
        break;
    case SDL_GL_ACCUM_GREEN_SIZE:
        _this->gl_config.accum_green_size = value;
        break;
    case SDL_GL_ACCUM_BLUE_SIZE:
        _this->gl_config.accum_blue_size = value;
        break;
    case SDL_GL_ACCUM_ALPHA_SIZE:
        _this->gl_config.accum_alpha_size = value;
        break;
    case SDL_GL_STEREO:
        _this->gl_config.stereo = value;
        break;
    case SDL_GL_MULTISAMPLEBUFFERS:
        _this->gl_config.multisamplebuffers = value;
        break;
    case SDL_GL_MULTISAMPLESAMPLES:
        _this->gl_config.multisamplesamples = value;
        break;
    case SDL_GL_FLOATBUFFERS:
        _this->gl_config.floatbuffers = value;
        break;
    case SDL_GL_ACCELERATED_VISUAL:
        _this->gl_config.accelerated = value;
        break;
    case SDL_GL_RETAINED_BACKING:
        _this->gl_config.retained_backing = value;
        break;
    case SDL_GL_CONTEXT_MAJOR_VERSION:
        _this->gl_config.major_version = value;
        break;
    case SDL_GL_CONTEXT_MINOR_VERSION:
        _this->gl_config.minor_version = value;
        break;
    case SDL_GL_CONTEXT_FLAGS:
        if (value & ~(SDL_GL_CONTEXT_DEBUG_FLAG |
                      SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG |
                      SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG |
                      SDL_GL_CONTEXT_RESET_ISOLATION_FLAG)) {
            result = SDL_SetError("Unknown OpenGL context flag %d", value);
            break;
        }
        _this->gl_config.flags = value;
        break;
    case SDL_GL_CONTEXT_PROFILE_MASK:
        if (value != 0 &&
            value != SDL_GL_CONTEXT_PROFILE_CORE &&
            value != SDL_GL_CONTEXT_PROFILE_COMPATIBILITY &&
            value != SDL_GL_CONTEXT_PROFILE_ES) {
            result = SDL_SetError("Unknown OpenGL context profile %d", value);
            break;
        }
        _this->gl_config.profile_mask = value;
        break;
    case SDL_GL_SHARE_WITH_CURRENT_CONTEXT:
        _this->gl_config.share_with_current_context = value;
        break;
    case SDL_GL_FRAMEBUFFER_SRGB_CAPABLE:
        _this->gl_config.framebuffer_srgb_capable = value;
        break;
    case SDL_GL_CONTEXT_RELEASE_BEHAVIOR:
        _this->gl_config.release_behavior = value;
        break;
    case SDL_GL_CONTEXT_RESET_NOTIFICATION:
        _this->gl_config.reset_notification = value;
        break;
    case SDL_GL_CONTEXT_NO_ERROR:
        _this->gl_config.no_error = value;
        break;
    case SDL_GL_EGL_PLATFORM:
        _this->gl_config.egl_platform = value;
        break;
    default:
        result = SDL_SetError("Unknown OpenGL attribute");
        break;
    }
    return result;
#else
    return SDL_Unsupported();
#endif // SDL_VIDEO_OPENGL
}
References _this, SDL_GL_ACCELERATED_VISUAL, SDL_GL_ACCUM_ALPHA_SIZE, SDL_GL_ACCUM_BLUE_SIZE, SDL_GL_ACCUM_GREEN_SIZE, SDL_GL_ACCUM_RED_SIZE, SDL_GL_ALPHA_SIZE, SDL_GL_BLUE_SIZE, SDL_GL_BUFFER_SIZE, SDL_GL_CONTEXT_DEBUG_FLAG, SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG, SDL_GL_CONTEXT_MAJOR_VERSION, SDL_GL_CONTEXT_MINOR_VERSION, SDL_GL_CONTEXT_NO_ERROR, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY, SDL_GL_CONTEXT_PROFILE_CORE, SDL_GL_CONTEXT_PROFILE_ES, SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_RELEASE_BEHAVIOR, SDL_GL_CONTEXT_RESET_ISOLATION_FLAG, SDL_GL_CONTEXT_RESET_NOTIFICATION, SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG, SDL_GL_DEPTH_SIZE, SDL_GL_DOUBLEBUFFER, SDL_GL_EGL_PLATFORM, SDL_GL_FLOATBUFFERS, SDL_GL_FRAMEBUFFER_SRGB_CAPABLE, SDL_GL_GREEN_SIZE, SDL_GL_MULTISAMPLEBUFFERS, SDL_GL_MULTISAMPLESAMPLES, SDL_GL_RED_SIZE, SDL_GL_RETAINED_BACKING, SDL_GL_SHARE_WITH_CURRENT_CONTEXT, SDL_GL_STENCIL_SIZE, SDL_GL_STEREO, SDL_SetError(), SDL_UninitializedVideo(), and SDL_Unsupported.
SDL_GL_SetSwapInterval()
bool SDL_GL_SetSwapInterval (int interval)
Set the swap interval for the current OpenGL context.
Some systems allow specifying -1 for the interval, to enable adaptive vsync. Adaptive vsync works the same as vsync, but if you've already missed the vertical retrace for a given frame, it swaps buffers immediately, which might be less jarring for the user during occasional framerate drops. If an application requests adaptive vsync and the system does not support it, this function will fail and return false. In such a case, you should probably retry the call with 1 for the interval.
Adaptive vsync is implemented for some glX drivers with GLX_EXT_swap_control_tear, and for some Windows drivers with WGL_EXT_swap_control_tear.
Read more on the Khronos wiki: https://www.khronos.org/opengl/wiki/Swap_Interval#Adaptive_Vsync
Parameters
interval 0 for immediate updates, 1 for updates synchronized with the vertical retrace, -1 for adaptive vsync.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetSwapInterval
{
    if (!_this) {
        return SDL_UninitializedVideo();
    } else if (SDL_GL_GetCurrentContext() == NULL) {
        return SDL_SetError("No OpenGL context has been made current");
    } else if (_this->GL_SetSwapInterval) {
        return _this->GL_SetSwapInterval(_this, interval);
    } else {
        return SDL_SetError("Setting the swap interval is not supported");
    }
}
References _this, NULL, SDL_GL_GetCurrentContext(), SDL_SetError(), and SDL_UninitializedVideo().
SDL_GL_SwapWindow()
bool SDL_GL_SwapWindow (SDL_Window * window)
Update a window with OpenGL rendering.
This is used with double-buffered OpenGL contexts, which are the default.
On macOS, make sure you bind 0 to the draw framebuffer before swapping the window, otherwise nothing will happen. If you aren't using glBindFramebuffer(), this is the default and you won't have to do anything extra.
Parameters
window the window to change.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!(window->flags & SDL_WINDOW_OPENGL)) {
        return SDL_SetError(NOT_AN_OPENGL_WINDOW);
    }
    if (SDL_GL_GetCurrentWindow() != window) {
        return SDL_SetError("The specified window has not been made current");
    }
    return _this->GL_SwapWindow(_this, window);
}
References _this, CHECK_WINDOW_MAGIC, NOT_AN_OPENGL_WINDOW, SDL_GL_GetCurrentWindow(), SDL_SetError(), and SDL_WINDOW_OPENGL.
SDL_GL_UnloadLibrary()
void SDL_GL_UnloadLibrary (void)
Unload the OpenGL library previously loaded by SDL_GL_LoadLibrary().
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_LoadLibrary
{
    if (!_this) {
        SDL_UninitializedVideo();
        return;
    }
    if (_this->gl_config.driver_loaded > 0) {
        if (--_this->gl_config.driver_loaded > 0) {
            return;
        }
        if (_this->GL_UnloadLibrary) {
            _this->GL_UnloadLibrary(_this);
        }
    }
}
References _this, and SDL_UninitializedVideo().
Referenced by SDL_DestroyWindow(), SDL_Metal_CreateView(), and SDL_RecreateWindow().
SDL_GlobalToRelativeForWindow()
void SDL_GlobalToRelativeForWindow (SDL_Window * window, int abs_x, int abs_y, int * rel_x, int * rel_y)
{
    SDL_Window *w;
    if (SDL_WINDOW_IS_POPUP(window)) {
        // Convert absolute window coordinates to relative for a popup
        for (w = window->parent; w; w = w->parent) {
            abs_x -= w->x;
            abs_y -= w->y;
            if (!SDL_WINDOW_IS_POPUP(w)) {
                break;
            }
        }
    }
    if (rel_x) {
        *rel_x = abs_x;
    }
    if (rel_y) {
        *rel_y = abs_y;
    }
}
References SDL_Window::parent, SDL_WINDOW_IS_POPUP, SDL_Window::x, and SDL_Window::y.
SDL_HasScreenKeyboardSupport()
bool SDL_HasScreenKeyboardSupport (void)
Check whether the platform has screen keyboard support.
Returns
true if the platform has some screen keyboard support or false if not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
SDL_ScreenKeyboardShown
{
    if (_this && _this->HasScreenKeyboardSupport) {
        return _this->HasScreenKeyboardSupport(_this);
    }
    return false;
}
References _this.
SDL_HasWindows()
bool SDL_HasWindows (void)
{
    return _this && _this->windows;
}
References _this.
Referenced by SDL_PrivateJoystickShouldIgnoreEvent().
SDL_HideWindow()
bool SDL_HideWindow (SDL_Window * window)
Hide a window.
Parameters
window the window to hide.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShowWindow
SDL_WINDOW_HIDDEN
{
    SDL_Window *child;
    CHECK_WINDOW_MAGIC(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->restore_on_show = false;
        return true;
    }
    // Hide all child windows
    for (child = window->first_child; child; child = child->next_sibling) {
        if (child->flags & SDL_WINDOW_HIDDEN) {
            break;
        }
        SDL_HideWindow(child);
        child->restore_on_show = true;
    }
    // Store the flags for restoration later.
    const SDL_WindowFlags pending_mask = (SDL_WINDOW_MAXIMIZED | SDL_WINDOW_MINIMIZED | SDL_WINDOW_FULLSCREEN | SDL_WINDOW_KEYBOARD_GRABBED | SDL_WINDOW_MOUSE_GRABBED);
    window->pending_flags = (window->flags & pending_mask);
    window->is_hiding = true;
    if (_this->HideWindow) {
        _this->HideWindow(_this, window);
    } else {
        SDL_SetMouseFocus(NULL);
        SDL_SetKeyboardFocus(NULL);
    }
    window->is_hiding = false;
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_HIDDEN, 0, 0);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_Window::flags, SDL_Window::next_sibling, NULL, SDL_Window::restore_on_show, SDL_EVENT_WINDOW_HIDDEN, SDL_HideWindow(), SDL_SendWindowEvent(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, SDL_WINDOW_KEYBOARD_GRABBED, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_MINIMIZED, and SDL_WINDOW_MOUSE_GRABBED.
Referenced by SDL_DestroyWindow(), SDL_HideWindow(), and SDL_RecreateWindow().
SDL_MaximizeWindow()
bool SDL_MaximizeWindow (SDL_Window * window)
Request that the window be made as large as possible.
Non-resizable windows can't be maximized. The window must have the SDL_WINDOW_RESIZABLE flag set, or this will have no effect.
On some windowing systems this request is asynchronous and the new window state may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_MAXIMIZED event will be emitted. Note that, as this is just a request, the windowing system can deny the state change.
When maximizing a window, whether the constraints set via SDL_SetWindowMaximumSize() are honored depends on the policy of the window manager. Win32 and macOS enforce the constraints when maximizing, while X11 and Wayland window managers may vary.
Parameters
window the window to maximize.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MinimizeWindow
SDL_RestoreWindow
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->MaximizeWindow) {
        return SDL_Unsupported();
    }
    if (!(window->flags & SDL_WINDOW_RESIZABLE)) {
        return SDL_SetError("A window without the 'SDL_WINDOW_RESIZABLE' flag can't be maximized");
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->pending_flags |= SDL_WINDOW_MAXIMIZED;
        return true;
    }
    _this->MaximizeWindow(_this, window);
    SDL_SyncIfRequired(window);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SetError(), SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOW_HIDDEN, SDL_WINDOW_MAXIMIZED, and SDL_WINDOW_RESIZABLE.
Referenced by ApplyWindowFlags().
SDL_Metal_CreateView()
SDL_MetalView SDL_Metal_CreateView (SDL_Window * window)
Create a CAMetalLayer-backed NSView/UIView and attach it to the specified window.
On macOS, this does not associate a MTLDevice with the CAMetalLayer on its own. It is up to user code to do that.
The returned handle can be casted directly to a NSView or UIView. To access the backing CAMetalLayer, call SDL_Metal_GetLayer().
Parameters
window the window.
Returns
handle NSView or UIView.
Since
This function is available since SDL 3.2.0.
See also
SDL_Metal_DestroyView
SDL_Metal_GetLayer
{
    CHECK_WINDOW_MAGIC(window, NULL);
    if (!_this->Metal_CreateView) {
        SDL_Unsupported();
        return NULL;
    }
    if (!(window->flags & SDL_WINDOW_METAL)) {
        // No problem, we can convert to Metal
        if (window->flags & SDL_WINDOW_OPENGL) {
            window->flags &= ~SDL_WINDOW_OPENGL;
            SDL_GL_UnloadLibrary();
        }
        if (window->flags & SDL_WINDOW_VULKAN) {
            window->flags &= ~SDL_WINDOW_VULKAN;
            SDL_Vulkan_UnloadLibrary();
        }
        window->flags |= SDL_WINDOW_METAL;
    }
    return _this->Metal_CreateView(_this, window);
}
References _this, CHECK_WINDOW_MAGIC, NULL, SDL_GL_UnloadLibrary(), SDL_Unsupported, SDL_Vulkan_UnloadLibrary(), SDL_WINDOW_METAL, SDL_WINDOW_OPENGL, and SDL_WINDOW_VULKAN.
SDL_Metal_DestroyView()
void SDL_Metal_DestroyView (SDL_MetalView view)
Destroy an existing SDL_MetalView object.
This should be called before SDL_DestroyWindow, if SDL_Metal_CreateView was called after SDL_CreateWindow.
Parameters
view the SDL_MetalView object.
Since
This function is available since SDL 3.2.0.
See also
SDL_Metal_CreateView
{
    if (_this && view && _this->Metal_DestroyView) {
        _this->Metal_DestroyView(_this, view);
    }
}
References _this.
SDL_Metal_GetLayer()
void * SDL_Metal_GetLayer (SDL_MetalView view)
Get a pointer to the backing CAMetalLayer for the given view.
Parameters
view the SDL_MetalView object.
Returns
a pointer.
Since
This function is available since SDL 3.2.0.
{
    if (_this && _this->Metal_GetLayer) {
        if (view) {
            return _this->Metal_GetLayer(_this, view);
        } else {
            SDL_InvalidParamError("view");
            return NULL;
        }
    } else {
        SDL_SetError("Metal is not supported.");
        return NULL;
    }
}
References _this, NULL, SDL_InvalidParamError, and SDL_SetError().
SDL_MinimizeWindow()
bool SDL_MinimizeWindow (SDL_Window * window)
Request that the window be minimized to an iconic representation.
If the window is in a fullscreen state, this request has no direct effect. It may alter the state the window is returned to when leaving fullscreen.
On some windowing systems this request is asynchronous and the new window state may not have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_MINIMIZED event will be emitted. Note that, as this is just a request, the windowing system can deny the state change.
Parameters
window the window to minimize.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MaximizeWindow
SDL_RestoreWindow
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->MinimizeWindow) {
        return SDL_Unsupported();
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->pending_flags |= SDL_WINDOW_MINIMIZED;
        return true;
    }
    _this->MinimizeWindow(_this, window);
    SDL_SyncIfRequired(window);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOW_HIDDEN, and SDL_WINDOW_MINIMIZED.
Referenced by ApplyWindowFlags(), SDL_CheckWindowDisplayChanged(), SDL_OnWindowFocusLost(), SDL_PromptAssertion(), SDL_SendKeyboardKeyInternal(), and SDL_UpdateFullscreenMode().
SDL_ModeSwitchingEmulated()
bool SDL_ModeSwitchingEmulated (SDL_VideoDevice * _this) static
{
    if (_this->device_caps & VIDEO_DEVICE_CAPS_MODE_SWITCHING_EMULATED) {
        return true;
    }
    return false;
}
References _this, and VIDEO_DEVICE_CAPS_MODE_SWITCHING_EMULATED.
Referenced by SDL_SetDisplayModeForDisplay(), and SDL_ShouldMinimizeOnFocusLoss().
SDL_OnApplicationDidEnterBackground()
void SDL_OnApplicationDidEnterBackground (void)
Let iOS apps with external event handling report onApplicationDidEnterBackground.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_DID_ENTER_BACKGROUND);
}
References SDL_EVENT_DID_ENTER_BACKGROUND, and SDL_SendAppEvent().
SDL_OnApplicationDidEnterForeground()
void SDL_OnApplicationDidEnterForeground (void)
Let iOS apps with external event handling report onApplicationDidBecomeActive.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_DID_ENTER_FOREGROUND);
    if (_this) {
        SDL_Window *window;
        for (window = _this->windows; window; window = window->next) {
            SDL_SetKeyboardFocus(window);
            SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_RESTORED, 0, 0);
        }
    }
}
References _this, SDL_EVENT_DID_ENTER_FOREGROUND, SDL_EVENT_WINDOW_RESTORED, SDL_SendAppEvent(), SDL_SendWindowEvent(), and SDL_SetKeyboardFocus().
Referenced by SDL_SendPendingSignalEvents().
SDL_OnApplicationDidReceiveMemoryWarning()
void SDL_OnApplicationDidReceiveMemoryWarning (void)
Let iOS apps with external event handling report onApplicationDidReceiveMemoryWarning.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_LOW_MEMORY);
}
References SDL_EVENT_LOW_MEMORY, and SDL_SendAppEvent().
SDL_OnApplicationWillEnterBackground()
void SDL_OnApplicationWillEnterBackground (void)
Let iOS apps with external event handling report onApplicationWillResignActive.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (_this) {
        SDL_Window *window;
        for (window = _this->windows; window; window = window->next) {
            SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_MINIMIZED, 0, 0);
        }
        SDL_SetKeyboardFocus(NULL);
    }
    SDL_SendAppEvent(SDL_EVENT_WILL_ENTER_BACKGROUND);
}
References _this, NULL, SDL_EVENT_WILL_ENTER_BACKGROUND, SDL_EVENT_WINDOW_MINIMIZED, SDL_SendAppEvent(), SDL_SendWindowEvent(), and SDL_SetKeyboardFocus().
Referenced by SDL_SendPendingSignalEvents().
SDL_OnApplicationWillEnterForeground()
void SDL_OnApplicationWillEnterForeground (void)
Let iOS apps with external event handling report onApplicationWillEnterForeground.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_WILL_ENTER_FOREGROUND);
}
References SDL_EVENT_WILL_ENTER_FOREGROUND, and SDL_SendAppEvent().
SDL_OnApplicationWillTerminate()
void SDL_OnApplicationWillTerminate (void)
Let iOS apps with external event handling report onApplicationWillTerminate.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_TERMINATING);
}
References SDL_EVENT_TERMINATING, and SDL_SendAppEvent().
SDL_OnDisplayAdded()
void SDL_OnDisplayAdded (SDL_VideoDisplay * display)
{
    SDL_Window *window;
    // See if any windows have changed to the new display
    for (window = _this->windows; window; window = window->next) {
        SDL_CheckWindowDisplayChanged(window);
    }
}
References _this, and SDL_CheckWindowDisplayChanged().
Referenced by SDL_SendDisplayEvent().
SDL_OnDisplayMoved()
void SDL_OnDisplayMoved (SDL_VideoDisplay * display)
{
    SDL_UpdateDesktopBounds();
}
References SDL_UpdateDesktopBounds().
Referenced by SDL_SendDisplayEvent().
SDL_OnVideoThread()
bool SDL_OnVideoThread (void)
{
    return (_this && SDL_GetCurrentThreadID() == _this->thread);
}
References _this, and SDL_GetCurrentThreadID().
Referenced by SDL_CaptureMouse().
SDL_OnWindowDisplayChanged()
void SDL_OnWindowDisplayChanged (SDL_Window * window)
{
    // Don't run this if a fullscreen change was made in an event watcher callback in response to a display changed event.
    if (window->update_fullscreen_on_display_changed && (window->flags & SDL_WINDOW_FULLSCREEN)) {
        const bool auto_mode_switch = SDL_GetHintBoolean(SDL_HINT_VIDEO_MATCH_EXCLUSIVE_MODE_ON_MOVE, true);
        if (auto_mode_switch && (window->requested_fullscreen_mode.w != 0 || window->requested_fullscreen_mode.h != 0)) {
            SDL_DisplayID displayID = SDL_GetDisplayForWindowPosition(window);
            bool include_high_density_modes = false;
            if (window->requested_fullscreen_mode.pixel_density > 1.0f) {
                include_high_density_modes = true;
            }
            const bool found_match = SDL_GetClosestFullscreenDisplayMode(displayID, window->requested_fullscreen_mode.w, window->requested_fullscreen_mode.h,
                                                                         window->requested_fullscreen_mode.refresh_rate, include_high_density_modes, &window->current_fullscreen_mode);
            // If a mode without matching dimensions was not found, just go to fullscreen desktop.
            if (!found_match ||
                window->requested_fullscreen_mode.w != window->current_fullscreen_mode.w ||
                window->requested_fullscreen_mode.h != window->current_fullscreen_mode.h) {
                SDL_zero(window->current_fullscreen_mode);
            }
        } else {
            SDL_zero(window->current_fullscreen_mode);
        }
        if (SDL_WINDOW_FULLSCREEN_VISIBLE(window)) {
            SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_UPDATE, true);
        }
    }
    SDL_CheckWindowPixelSizeChanged(window);
}
References SDL_CheckWindowPixelSizeChanged(), SDL_FULLSCREEN_OP_UPDATE, SDL_GetClosestFullscreenDisplayMode(), SDL_GetDisplayForWindowPosition(), SDL_GetHintBoolean(), SDL_HINT_VIDEO_MATCH_EXCLUSIVE_MODE_ON_MOVE, SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_FULLSCREEN_VISIBLE, and SDL_zero.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowEnter()
void SDL_OnWindowEnter (SDL_Window * window)
{
    if (_this->OnWindowEnter) {
        _this->OnWindowEnter(_this, window);
    }
}
References _this.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowFocusGained()
void SDL_OnWindowFocusGained (SDL_Window * window)
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse && mouse->relative_mode) {
        SDL_SetMouseFocus(window);
    }
    SDL_UpdateWindowGrab(window);
}
References SDL_Mouse::relative_mode, SDL_GetMouse(), SDL_SetMouseFocus(), and SDL_UpdateWindowGrab().
Referenced by SDL_SendWindowEvent().
SDL_OnWindowFocusLost()
void SDL_OnWindowFocusLost (SDL_Window * window)
{
    SDL_UpdateWindowGrab(window);
    if (SDL_ShouldMinimizeOnFocusLoss(window)) {
        SDL_MinimizeWindow(window);
    }
}
References SDL_MinimizeWindow(), SDL_ShouldMinimizeOnFocusLoss(), and SDL_UpdateWindowGrab().
Referenced by SDL_SendWindowEvent().
SDL_OnWindowHidden()
void SDL_OnWindowHidden (SDL_Window * window)
{
    /* Store the maximized and fullscreen flags for restoration later, in case
     * this was initiated by the window manager due to the window being unmapped
     * when minimized.
     */
    window->pending_flags |= (window->flags & (SDL_WINDOW_FULLSCREEN | SDL_WINDOW_MAXIMIZED));
    // The window is already hidden at this point, so just change the mode back if necessary.
    SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, false);
}
References SDL_FULLSCREEN_OP_LEAVE, SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, and SDL_WINDOW_MAXIMIZED.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowLeave()
void SDL_OnWindowLeave (SDL_Window * window)
{
}
Referenced by SDL_SendWindowEvent().
SDL_OnWindowLiveResizeUpdate()
void SDL_OnWindowLiveResizeUpdate (SDL_Window * window)
{
    if (SDL_HasMainCallbacks()) {
        SDL_IterateMainCallbacks(false);
    } else {
        // Send an expose event so the application can redraw
        SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_EXPOSED, 1, 0);
    }
    SDL_PumpEventMaintenance();
}
References SDL_EVENT_WINDOW_EXPOSED, SDL_HasMainCallbacks(), SDL_IterateMainCallbacks(), SDL_PumpEventMaintenance(), and SDL_SendWindowEvent().
SDL_OnWindowMaximized()
void SDL_OnWindowMaximized (SDL_Window * window)
{
}
Referenced by SDL_SendWindowEvent().
SDL_OnWindowMinimized()
void SDL_OnWindowMinimized (SDL_Window * window)
{
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, false);
    }
}
References SDL_FULLSCREEN_OP_LEAVE, SDL_UpdateFullscreenMode(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowMoved()
void SDL_OnWindowMoved (SDL_Window * window)
{
    SDL_CheckWindowDisplayChanged(window);
}
References SDL_CheckWindowDisplayChanged().
Referenced by SDL_SendWindowEvent().
SDL_OnWindowPixelSizeChanged()
void SDL_OnWindowPixelSizeChanged (SDL_Window * window)
{
    window->surface_valid = false;
}
Referenced by SDL_SendWindowEvent().
SDL_OnWindowResized()
void SDL_OnWindowResized (SDL_Window * window)
{
    SDL_CheckWindowDisplayChanged(window);
    SDL_CheckWindowPixelSizeChanged(window);
    SDL_CheckWindowSafeAreaChanged(window);
    if ((window->flags & SDL_WINDOW_TRANSPARENT) && _this->UpdateWindowShape) {
        SDL_Surface *surface = (SDL_Surface *)SDL_GetPointerProperty(window->props, SDL_PROP_WINDOW_SHAPE_POINTER, NULL);
        if (surface) {
            _this->UpdateWindowShape(_this, window, surface);
        }
    }
}
References _this, NULL, SDL_CheckWindowDisplayChanged(), SDL_CheckWindowPixelSizeChanged(), SDL_CheckWindowSafeAreaChanged(), SDL_GetPointerProperty(), SDL_PROP_WINDOW_SHAPE_POINTER, and SDL_WINDOW_TRANSPARENT.
Referenced by SDL_SendWindowEvent(), and SDL_UpdateFullscreenMode().
SDL_OnWindowRestored()
void SDL_OnWindowRestored (SDL_Window * window)
{
    /*
     * FIXME: Is this fine to just remove this, or should it be preserved just
     * for the fullscreen case? In principle it seems like just hiding/showing
     * windows shouldn't affect the stacking order; maybe the right fix is to
     * re-decouple OnWindowShown and OnWindowRestored.
     */
    // SDL_RaiseWindow(window);
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_ENTER, false);
    }
}
References SDL_FULLSCREEN_OP_ENTER, SDL_UpdateFullscreenMode(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowShown()
void SDL_OnWindowShown (SDL_Window * window)
{
    // Set window state if we have pending window flags cached
    ApplyWindowFlags(window, window->pending_flags);
    window->pending_flags = 0;
}
References ApplyWindowFlags().
Referenced by SDL_SendWindowEvent().
SDL_RaiseWindow()
bool SDL_RaiseWindow (SDL_Window * window)
Request that a window be raised above other windows and gain the input focus.
The result of this request is subject to desktop window manager policy, particularly if raising the requested window would result in stealing focus from another application. If the window is successfully raised and gains input focus, an SDL_EVENT_WINDOW_FOCUS_GAINED event will be emitted, and the window will have the SDL_WINDOW_INPUT_FOCUS flag set.
Parameters
window the window to raise.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        return true;
    }
    if (_this->RaiseWindow) {
        _this->RaiseWindow(_this, window);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_HIDDEN.
Referenced by SDL_ShowMessageBox().
SDL_RecreateWindow()
bool SDL_RecreateWindow (SDL_Window * window, SDL_WindowFlags flags)
{
    bool loaded_opengl = false;
    bool need_gl_unload = false;
    bool need_gl_load = false;
    bool loaded_vulkan = false;
    bool need_vulkan_unload = false;
    bool need_vulkan_load = false;
    SDL_WindowFlags graphics_flags;
    // ensure no more than one of these flags is set
    graphics_flags = flags & (SDL_WINDOW_OPENGL | SDL_WINDOW_METAL | SDL_WINDOW_VULKAN);
    if (graphics_flags & (graphics_flags - 1)) {
        return SDL_SetError("Conflicting window flags specified");
    }
    if ((flags & SDL_WINDOW_OPENGL) && !_this->GL_CreateContext) {
        return SDL_ContextNotSupported("OpenGL");
    }
    if ((flags & SDL_WINDOW_VULKAN) && !_this->Vulkan_CreateSurface) {
        return SDL_ContextNotSupported("Vulkan");
    }
    if ((flags & SDL_WINDOW_METAL) && !_this->Metal_CreateView) {
        return SDL_ContextNotSupported("Metal");
    }
    if (window->flags & SDL_WINDOW_EXTERNAL) {
        // Can't destroy and re-create external windows, hrm
        flags |= SDL_WINDOW_EXTERNAL;
    } else {
        flags &= ~SDL_WINDOW_EXTERNAL;
    }
    // If this is a modal dialog, clear the modal status.
    if (window->flags & SDL_WINDOW_MODAL) {
        SDL_SetWindowModal(window, false);
    }
    // Restore video mode, etc.
    if (!(window->flags & SDL_WINDOW_EXTERNAL)) {
        const bool restore_on_show = window->restore_on_show;
        SDL_HideWindow(window);
        window->restore_on_show = restore_on_show;
    }
    // Tear down the old native window
    SDL_DestroyWindowSurface(window);
    if ((window->flags & SDL_WINDOW_OPENGL) != (flags & SDL_WINDOW_OPENGL)) {
        if (flags & SDL_WINDOW_OPENGL) {
            need_gl_load = true;
        } else {
            need_gl_unload = true;
        }
    } else if (window->flags & SDL_WINDOW_OPENGL) {
        need_gl_unload = true;
        need_gl_load = true;
    }
    if ((window->flags & SDL_WINDOW_VULKAN) != (flags & SDL_WINDOW_VULKAN)) {
        if (flags & SDL_WINDOW_VULKAN) {
            need_vulkan_load = true;
        } else {
            need_vulkan_unload = true;
        }
    } else if (window->flags & SDL_WINDOW_VULKAN) {
        need_vulkan_unload = true;
        need_vulkan_load = true;
    }
    if (need_gl_unload) {
        SDL_GL_UnloadLibrary();
    }
    if (need_vulkan_unload) {
        SDL_Vulkan_UnloadLibrary();
    }
    if (_this->DestroyWindow && !(flags & SDL_WINDOW_EXTERNAL)) {
        _this->DestroyWindow(_this, window);
    }
    if (need_gl_load) {
        if (!SDL_GL_LoadLibrary(NULL)) {
            return false;
        }
        loaded_opengl = true;
    }
    if (need_vulkan_load) {
        if (!SDL_Vulkan_LoadLibrary(NULL)) {
            return false;
        }
        loaded_vulkan = true;
    }
    window->flags = ((flags & CREATE_FLAGS) | SDL_WINDOW_HIDDEN);
    window->is_destroying = false;
    if (_this->CreateSDLWindow && !(flags & SDL_WINDOW_EXTERNAL)) {
        /* Reset the window size to the original floating value, so the
         * recreated window has the proper base size.
         */
        window->x = window->windowed.x = window->floating.x;
        window->y = window->windowed.y = window->floating.y;
        window->w = window->windowed.w = window->floating.w;
        window->h = window->windowed.h = window->floating.h;
        if (!_this->CreateSDLWindow(_this, window, 0)) {
            if (loaded_opengl) {
                SDL_GL_UnloadLibrary();
                window->flags &= ~SDL_WINDOW_OPENGL;
            }
            if (loaded_vulkan) {
                SDL_Vulkan_UnloadLibrary();
                window->flags &= ~SDL_WINDOW_VULKAN;
            }
            return false;
        }
    }
    if (flags & SDL_WINDOW_EXTERNAL) {
        window->flags |= SDL_WINDOW_EXTERNAL;
    }
    if (_this->SetWindowTitle && window->title) {
        _this->SetWindowTitle(_this, window);
    }
    if (_this->SetWindowIcon && window->icon) {
        _this->SetWindowIcon(_this, window, window->icon);
    }
    if (_this->SetWindowMinimumSize && (window->min_w || window->min_h)) {
        _this->SetWindowMinimumSize(_this, window);
    }
    if (_this->SetWindowMaximumSize && (window->max_w || window->max_h)) {
        _this->SetWindowMaximumSize(_this, window);
    }
    if (_this->SetWindowAspectRatio && (window->min_aspect > 0.0f || window->max_aspect > 0.0f)) {
        _this->SetWindowAspectRatio(_this, window);
    }
    if (window->hit_test) {
        _this->SetWindowHitTest(window, true);
    }
    SDL_FinishWindowCreation(window, flags);
    return true;
}
References _this, CREATE_FLAGS, NULL, SDL_ContextNotSupported(), SDL_DestroyWindowSurface(), SDL_FinishWindowCreation(), SDL_GL_LoadLibrary(), SDL_GL_UnloadLibrary(), SDL_HideWindow(), SDL_SetError(), SDL_SetWindowModal(), SDL_Vulkan_LoadLibrary(), SDL_Vulkan_UnloadLibrary(), SDL_WINDOW_EXTERNAL, SDL_WINDOW_HIDDEN, SDL_WINDOW_METAL, SDL_WINDOW_MODAL, SDL_WINDOW_OPENGL, and SDL_WINDOW_VULKAN.
SDL_RelativeToGlobalForWindow()
void SDL_RelativeToGlobalForWindow (SDL_Window * window, int rel_x, int rel_y, int * abs_x, int * abs_y)
{
    SDL_Window *w;
    if (SDL_WINDOW_IS_POPUP(window)) {
        // Calculate the total offset of the popup from the parents
        for (w = window->parent; w; w = w->parent) {
            rel_x += w->x;
            rel_y += w->y;
            if (!SDL_WINDOW_IS_POPUP(w)) {
                break;
            }
        }
    }
    if (abs_x) {
        *abs_x = rel_x;
    }
    if (abs_y) {
        *abs_y = rel_y;
    }
}
References SDL_Window::parent, SDL_WINDOW_IS_POPUP, SDL_Window::x, and SDL_Window::y.
Referenced by SDL_GetDisplayForWindowPosition().
SDL_RemoveWindowRenderer()
void SDL_RemoveWindowRenderer (SDL_Window * window, SDL_Renderer * renderer)
{
    for (int i = 0; i < window->num_renderers; ++i) {
        if (window->renderers[i] == renderer) {
            if (i < (window->num_renderers - 1)) {
                SDL_memmove(&window->renderers[i], &window->renderers[i + 1], (window->num_renderers - i - 1) * sizeof(window->renderers[i]));
            }
            --window->num_renderers;
            break;
        }
    }
}
References SDL_memmove.
Referenced by SDL_DestroyRendererWithoutFreeing().
SDL_ResetFullscreenDisplayModes()
void SDL_ResetFullscreenDisplayModes (SDL_VideoDisplay * display)
{
    int i;
    for (i = display->num_fullscreen_modes; i--;) {
        SDL_free(display->fullscreen_modes[i].internal);
        display->fullscreen_modes[i].internal = NULL;
    }
    SDL_free(display->fullscreen_modes);
    display->fullscreen_modes = NULL;
    display->num_fullscreen_modes = 0;
    display->max_fullscreen_modes = 0;
    display->current_mode = &display->desktop_mode;
}
References NULL, and SDL_free().
Referenced by SDL_DelVideoDisplay().
SDL_RestoreMousePosition()
void SDL_RestoreMousePosition (SDL_Window * window) static
{
    float x, y;
    SDL_Mouse *mouse = SDL_GetMouse();
    if (window == SDL_GetMouseFocus()) {
        const bool prev_warp_val = mouse->warp_emulation_prohibited;
        SDL_GetMouseState(&x, &y);
        // Disable the warp emulation so it isn't accidentally activated on a fullscreen transitions.
        mouse->warp_emulation_prohibited = true;
        SDL_WarpMouseInWindow(window, x, y);
        mouse->warp_emulation_prohibited = prev_warp_val;
    }
}
References SDL_GetMouse(), SDL_GetMouseFocus(), SDL_GetMouseState(), SDL_WarpMouseInWindow(), and SDL_Mouse::warp_emulation_prohibited.
Referenced by SDL_UpdateFullscreenMode().
SDL_RestoreWindow()
bool SDL_RestoreWindow (SDL_Window * window)
Request that the size and position of a minimized or maximized window be restored.
If the window is in a fullscreen state, this request has no direct effect. It may alter the state the window is returned to when leaving fullscreen.
On some windowing systems this request is asynchronous and the new window state may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_RESTORED event will be emitted. Note that, as this is just a request, the windowing system can deny the state change.
Parameters
window the window to restore.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MaximizeWindow
SDL_MinimizeWindow
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->RestoreWindow) {
        return SDL_Unsupported();
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->pending_flags &= ~(SDL_WINDOW_MAXIMIZED | SDL_WINDOW_MINIMIZED);
        return true;
    }
    _this->RestoreWindow(_this, window);
    SDL_SyncIfRequired(window);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOW_HIDDEN, SDL_WINDOW_MAXIMIZED, and SDL_WINDOW_MINIMIZED.
Referenced by ApplyWindowFlags(), and SDL_PromptAssertion().
SDL_ScreenKeyboardShown()
bool SDL_ScreenKeyboardShown (SDL_Window * window)
Check whether the screen keyboard is shown for given window.
Parameters
window the window for which screen keyboard should be queried.
Returns
true if screen keyboard is shown or false if not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasScreenKeyboardSupport
{
    CHECK_WINDOW_MAGIC(window, false);
    if (_this->IsScreenKeyboardShown) {
        return _this->IsScreenKeyboardShown(_this, window);
    }
    return false;
}
References _this, and CHECK_WINDOW_MAGIC.
Referenced by SDL_StartTextInputWithProperties(), and SDL_StopTextInput().
SDL_ScreenSaverEnabled()
bool SDL_ScreenSaverEnabled (void)
Check whether the screensaver is currently enabled.
The screensaver is disabled by default.
The default can also be changed using SDL_HINT_VIDEO_ALLOW_SCREENSAVER.
Returns
true if the screensaver is enabled, false if it is disabled.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DisableScreenSaver
SDL_EnableScreenSaver
{
    if (!_this) {
        return true;
    }
    return !_this->suspend_screensaver;
}
References _this.
SDL_SendsDisplayChanges()
bool SDL_SendsDisplayChanges (SDL_VideoDevice * _this) static
{
    return !!(_this->device_caps & VIDEO_DEVICE_CAPS_SENDS_DISPLAY_CHANGES);
}
References _this, and VIDEO_DEVICE_CAPS_SENDS_DISPLAY_CHANGES.
Referenced by SDL_CheckWindowDisplayChanged().
SDL_SendsFullscreenDimensions()
bool SDL_SendsFullscreenDimensions (SDL_VideoDevice * _this) static
{
    return !!(_this->device_caps & VIDEO_DEVICE_CAPS_SENDS_FULLSCREEN_DIMENSIONS);
}
References _this, and VIDEO_DEVICE_CAPS_SENDS_FULLSCREEN_DIMENSIONS.
Referenced by SDL_UpdateFullscreenMode().
SDL_SetCurrentDisplayMode()
void SDL_SetCurrentDisplayMode (SDL_VideoDisplay * display, const SDL_DisplayMode * mode)
{
    SDL_DisplayMode last_mode;
    if (display->current_mode) {
        SDL_copyp(&last_mode, display->current_mode);
    } else {
        SDL_zero(last_mode);
    }
    display->current_mode = mode;
    if (DisplayModeChanged(&last_mode, mode)) {
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, mode->w, mode->h);
    }
}
References DisplayModeChanged(), SDL_DisplayMode::h, SDL_copyp, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, SDL_SendDisplayEvent(), SDL_zero, and SDL_DisplayMode::w.
Referenced by SDL_SetDisplayModeForDisplay().
SDL_SetDesktopDisplayMode()
void SDL_SetDesktopDisplayMode (SDL_VideoDisplay * display, const SDL_DisplayMode * mode)
{
    SDL_DisplayMode last_mode;
    if (display->fullscreen_active) {
        // This is a temporary mode change, don't save the desktop mode
        return;
    }
    SDL_copyp(&last_mode, &display->desktop_mode);
    if (display->desktop_mode.internal) {
        SDL_free(display->desktop_mode.internal);
    }
    SDL_copyp(&display->desktop_mode, mode);
    display->desktop_mode.displayID = display->id;
    SDL_FinalizeDisplayMode(&display->desktop_mode);
    if (DisplayModeChanged(&last_mode, &display->desktop_mode)) {
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED, mode->w, mode->h);
        if (display->current_mode == &display->desktop_mode) {
            SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, mode->w, mode->h);
        }
    }
}
References DisplayModeChanged(), SDL_DisplayMode::h, SDL_copyp, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED, SDL_FinalizeDisplayMode(), SDL_free(), SDL_SendDisplayEvent(), and SDL_DisplayMode::w.
SDL_SetDisplayContentScale()
void SDL_SetDisplayContentScale (SDL_VideoDisplay * display, float scale)
{
    if (scale != display->content_scale) {
        SDL_Window *window;
        display->content_scale = scale;
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED, 0, 0);
        // Check the windows on this display
        for (window = _this->windows; window; window = window->next) {
            if (display->id == window->last_displayID) {
                SDL_CheckWindowDisplayScaleChanged(window);
            }
        }
    }
}
References _this, SDL_CheckWindowDisplayScaleChanged(), SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED, and SDL_SendDisplayEvent().
SDL_SetDisplayHDRProperties()
void SDL_SetDisplayHDRProperties (SDL_VideoDisplay * display, const SDL_HDROutputProperties * HDR)
{
    bool changed = false;
    if (HDR->SDR_white_level != display->HDR.SDR_white_level) {
        display->HDR.SDR_white_level = SDL_max(HDR->SDR_white_level, 1.0f);
        changed = true;
    }
    if (HDR->HDR_headroom != display->HDR.HDR_headroom) {
        display->HDR.HDR_headroom = SDL_max(HDR->HDR_headroom, 1.0f);
        changed = true;
    }
    SDL_copyp(&display->HDR, HDR);
    if (changed && !SDL_DriverSendsHDRChanges(_this)) {
        for (SDL_Window *w = display->device->windows; w; w = w->next) {
            if (SDL_GetDisplayForWindow(w) == display->id) {
                SDL_SetWindowHDRProperties(w, &display->HDR, true);
            }
        }
    }
}
References _this, SDL_HDROutputProperties::HDR_headroom, SDL_copyp, SDL_DriverSendsHDRChanges(), SDL_GetDisplayForWindow(), SDL_max, SDL_SetWindowHDRProperties(), and SDL_HDROutputProperties::SDR_white_level.
SDL_SetDisplayModeForDisplay()
bool SDL_SetDisplayModeForDisplay (SDL_VideoDisplay * display, SDL_DisplayMode * mode)
{
    /* Mode switching is being emulated per-window; nothing to do and cannot fail,
     * except for XWayland, which still needs the actual mode setting call since
     * it's emulated via the XRandR interface.
     */
    if (SDL_ModeSwitchingEmulated(_this) && SDL_strcmp(_this->name, "x11") != 0) {
        return true;
    }
    if (!mode) {
        mode = &display->desktop_mode;
    }
    if (mode == display->current_mode) {
        return true;
    }
    // Actually change the display mode
    if (_this->SetDisplayMode) {
        bool result;
        _this->setting_display_mode = true;
        result = _this->SetDisplayMode(_this, display, mode);
        _this->setting_display_mode = false;
        if (!result) {
            return false;
        }
    }
    SDL_SetCurrentDisplayMode(display, mode);
    return true;
}
References _this, SDL_ModeSwitchingEmulated(), SDL_SetCurrentDisplayMode(), and SDL_strcmp().
Referenced by SDL_UpdateFullscreenMode().
SDL_SetSystemTheme()
void SDL_SetSystemTheme (SDL_SystemTheme theme)
{
    if (_this && theme != _this->system_theme) {
        _this->system_theme = theme;
        SDL_SendSystemThemeChangedEvent();
    }
}
References _this, and SDL_SendSystemThemeChangedEvent().
Referenced by DBus_MessageFilter().
SDL_SetTextInputArea()
bool SDL_SetTextInputArea (SDL_Window * window, const SDL_Rect * rect, int cursor)
Set the area used to type Unicode text input.
Native input methods may place a window with word suggestions near the cursor, without covering the text being entered.
Parameters
window the window for which to set the text input area.
rect the SDL_Rect representing the text input area, in window coordinates, or NULL to clear it.
cursor the offset of the current cursor location relative to rect->x, in window coordinates.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextInputArea
SDL_StartTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        SDL_copyp(&window->text_input_rect, rect);
        window->text_input_cursor = cursor;
    } else {
        SDL_zero(window->text_input_rect);
        window->text_input_cursor = 0;
    }
    if (_this && _this->UpdateTextInputArea) {
        if (!_this->UpdateTextInputArea(_this, window)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_copyp, and SDL_zero.
SDL_SetWindowAlwaysOnTop()
bool SDL_SetWindowAlwaysOnTop (SDL_Window * window, bool on_top)
Set the window to always be above the others.
This will add or remove the window's SDL_WINDOW_ALWAYS_ON_TOP flag. This will bring the window to the front and keep the window above the rest.
Parameters
window the window of which to change the always on top state.
on_top true to set the window always on top, false to disable.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFlags
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    const bool want = (on_top != false); // normalize the flag.
    const bool have = ((window->flags & SDL_WINDOW_ALWAYS_ON_TOP) != 0);
    if ((want != have) && (_this->SetWindowAlwaysOnTop)) {
        if (want) {
            window->flags |= SDL_WINDOW_ALWAYS_ON_TOP;
        } else {
            window->flags &= ~SDL_WINDOW_ALWAYS_ON_TOP;
        }
        _this->SetWindowAlwaysOnTop(_this, window, want);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_WINDOW_ALWAYS_ON_TOP.
SDL_SetWindowAspectRatio()
bool SDL_SetWindowAspectRatio (SDL_Window * window, float min_aspect, float max_aspect)
Request that the aspect ratio of a window's client area be set.
The aspect ratio is the ratio of width divided by height, e.g. 2560x1600 would be 1.6. Larger aspect ratios are wider and smaller aspect ratios are narrower.
If, at the time of this request, the window in a fixed-size state, such as maximized or fullscreen, the request will be deferred until the window exits this state and becomes resizable again.
On some windowing systems, this request is asynchronous and the new window aspect ratio may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window size changes, an SDL_EVENT_WINDOW_RESIZED event will be emitted with the new window dimensions. Note that the new dimensions may not match the exact aspect ratio requested, as some windowing systems can restrict the window size in certain scenarios (e.g. constraining the size of the content area to remain within the usable desktop bounds). Additionally, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to change.
min_aspect the minimum aspect ratio of the window, or 0.0f for no limit.
max_aspect the maximum aspect ratio of the window, or 0.0f for no limit.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowAspectRatio
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    window->min_aspect = min_aspect;
    window->max_aspect = max_aspect;
    if (_this->SetWindowAspectRatio) {
        _this->SetWindowAspectRatio(_this, window);
    }
    return SDL_SetWindowSize(window, window->floating.w, window->floating.h);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_SetWindowSize().
SDL_SetWindowBordered()
bool SDL_SetWindowBordered (SDL_Window * window, bool bordered)
Set the border state of a window.
This will add or remove the window's SDL_WINDOW_BORDERLESS flag and add or remove the border from the actual window. This is a no-op if the window's border already matches the requested state.
You can't change the border state of a fullscreen window.
Parameters
window the window of which to change the border state.
bordered false to remove border, true to add border.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFlags
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    const bool want = (bordered != false); // normalize the flag.
    const bool have = !(window->flags & SDL_WINDOW_BORDERLESS);
    if ((want != have) && (_this->SetWindowBordered)) {
        if (want) {
            window->flags &= ~SDL_WINDOW_BORDERLESS;
        } else {
            window->flags |= SDL_WINDOW_BORDERLESS;
        }
        _this->SetWindowBordered(_this, window, want);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_WINDOW_BORDERLESS.
SDL_SetWindowFocusable()
bool SDL_SetWindowFocusable (SDL_Window * window, bool focusable)
Set whether the window may have input focus.
Parameters
window the window to set focusable state.
focusable true to allow input focus, false to not allow input focus.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    const bool want = (focusable != false); // normalize the flag.
    const bool have = !(window->flags & SDL_WINDOW_NOT_FOCUSABLE);
    if ((want != have) && (_this->SetWindowFocusable)) {
        if (want) {
            window->flags &= ~SDL_WINDOW_NOT_FOCUSABLE;
        } else {
            window->flags |= SDL_WINDOW_NOT_FOCUSABLE;
        }
        if (!_this->SetWindowFocusable(_this, window, want)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_NOT_FOCUSABLE.
SDL_SetWindowFullscreen()
bool SDL_SetWindowFullscreen (SDL_Window * window, bool fullscreen)
Request that the window's fullscreen state be changed.
By default a window in fullscreen state uses borderless fullscreen desktop mode, but a specific exclusive display mode can be set using SDL_SetWindowFullscreenMode().
On some windowing systems this request is asynchronous and the new fullscreen state may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_ENTER_FULLSCREEN or SDL_EVENT_WINDOW_LEAVE_FULLSCREEN event will be emitted. Note that, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to change.
fullscreen true for fullscreen mode, false for windowed mode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFullscreenMode
SDL_SetWindowFullscreenMode
SDL_SyncWindow
SDL_WINDOW_FULLSCREEN
{
    bool result;
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        if (fullscreen) {
            window->pending_flags |= SDL_WINDOW_FULLSCREEN;
        } else {
            window->pending_flags &= ~SDL_WINDOW_FULLSCREEN;
        }
        return true;
    }
    if (fullscreen) {
        // Set the current fullscreen mode to the desired mode
        SDL_copyp(&window->current_fullscreen_mode, &window->requested_fullscreen_mode);
    }
    result = SDL_UpdateFullscreenMode(window, fullscreen ? SDL_FULLSCREEN_OP_ENTER : SDL_FULLSCREEN_OP_LEAVE, true);
    if (!fullscreen || !result) {
        // Clear the current fullscreen mode.
        SDL_zero(window->current_fullscreen_mode);
    }
    if (result) {
        SDL_SyncIfRequired(window);
    }
    return result;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_copyp, SDL_FULLSCREEN_OP_ENTER, SDL_FULLSCREEN_OP_LEAVE, SDL_SyncIfRequired(), SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, and SDL_zero.
Referenced by ApplyWindowFlags().
SDL_SetWindowFullscreenMode()
bool SDL_SetWindowFullscreenMode (SDL_Window * window, const SDL_DisplayMode * mode)
Set the display mode to use when a window is visible and fullscreen.
This only affects the display mode used when the window is fullscreen. To change the window size when the window is not fullscreen, use SDL_SetWindowSize().
If the window is currently in the fullscreen state, this request is asynchronous on some windowing systems and the new mode dimensions may not be applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the new mode takes effect, an SDL_EVENT_WINDOW_RESIZED and/or an SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED event will be emitted with the new mode dimensions.
Parameters
window the window to affect.
mode a pointer to the display mode to use, which can be NULL for borderless fullscreen desktop mode, or one of the fullscreen modes returned by SDL_GetFullscreenDisplayModes() to set an exclusive fullscreen mode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFullscreenMode
SDL_SetWindowFullscreen
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (mode) {
        if (!SDL_GetFullscreenModeMatch(mode)) {
            return SDL_SetError("Invalid fullscreen display mode");
        }
        // Save the mode so we can look up the closest match later
        SDL_copyp(&window->requested_fullscreen_mode, mode);
    } else {
        SDL_zero(window->requested_fullscreen_mode);
    }
    /* Copy to the current mode now, in case an asynchronous fullscreen window request
     * is in progress. It will be overwritten if a new request is made.
     */
    SDL_copyp(&window->current_fullscreen_mode, &window->requested_fullscreen_mode);
    if (SDL_WINDOW_FULLSCREEN_VISIBLE(window)) {
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_UPDATE, true);
        SDL_SyncIfRequired(window);
    }
    return true;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_copyp, SDL_FULLSCREEN_OP_UPDATE, SDL_GetFullscreenModeMatch(), SDL_SetError(), SDL_SyncIfRequired(), SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN_VISIBLE, and SDL_zero.
SDL_SetWindowHDRProperties()
void SDL_SetWindowHDRProperties (SDL_Window * window, const SDL_HDROutputProperties * HDR, bool send_event)
{
    if (window->HDR.HDR_headroom != HDR->HDR_headroom || window->HDR.SDR_white_level != window->HDR.SDR_white_level) {
        SDL_PropertiesID window_props = SDL_GetWindowProperties(window);
        SDL_SetFloatProperty(window_props, SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT, SDL_max(HDR->HDR_headroom, 1.0f));
        SDL_SetFloatProperty(window_props, SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT, SDL_max(HDR->SDR_white_level, 1.0f));
        SDL_SetBooleanProperty(window_props, SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN, HDR->HDR_headroom > 1.0f);
        SDL_copyp(&window->HDR, HDR);
        if (send_event) {
            SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_HDR_STATE_CHANGED, HDR->HDR_headroom > 1.0f, 0);
        }
    }
}
References SDL_HDROutputProperties::HDR_headroom, SDL_copyp, SDL_EVENT_WINDOW_HDR_STATE_CHANGED, SDL_GetWindowProperties(), SDL_max, SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN, SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT, SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT, SDL_SendWindowEvent(), SDL_SetBooleanProperty(), SDL_SetFloatProperty(), and SDL_HDROutputProperties::SDR_white_level.
Referenced by SDL_CreateWindowWithProperties(), and SDL_SetDisplayHDRProperties().
SDL_SetWindowHitTest()
bool SDL_SetWindowHitTest (SDL_Window * window, SDL_HitTest callback, void * callback_data)
Provide a callback that decides if a window region has special properties.
Normally windows are dragged and resized by decorations provided by the system window manager (a title bar, borders, etc), but for some apps, it makes sense to drag them from somewhere else inside the window itself; for example, one might have a borderless window that wants to be draggable from any part, or simulate its own title bar, etc.
This function lets the app provide a callback that designates pieces of a given window as special. This callback is run during event processing if we need to tell the OS to treat a region of the window specially; the use of this callback is known as "hit testing."
Mouse input may not be delivered to your application if it is within a special area; the OS will often apply that input to moving the window or resizing the window and not deliver it to the application.
Specifying NULL for a callback disables hit-testing. Hit-testing is disabled by default.
Platforms that don't support this functionality will return false unconditionally, even if you're attempting to disable hit-testing.
Your callback may fire at any time, and its firing does not indicate any specific behavior (for example, on Windows, this certainly might fire when the OS is deciding whether to drag your window, but it fires for lots of other reasons, too, some unrelated to anything you probably care about and when the mouse isn't actually at the location it is testing). Since this can fire at any time, you should try to keep your callback efficient, devoid of allocations, etc.
Parameters
window the window to set hit-testing on.
callback the function to call when doing a hit-test.
callback_data an app-defined void pointer passed to callback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->SetWindowHitTest) {
        return SDL_Unsupported();
    }
    window->hit_test = callback;
    window->hit_test_data = callback_data;
    return _this->SetWindowHitTest(window, callback != NULL);
}
References _this, CHECK_WINDOW_MAGIC, NULL, and SDL_Unsupported.
SDL_SetWindowIcon()
bool SDL_SetWindowIcon (SDL_Window * window, SDL_Surface * icon)
Set the icon for a window.
If this function is passed a surface with alternate representations added using SDL_AddSurfaceAlternateImage(), the surface will be interpreted as the content to be used for 100% display scale, and the alternate representations will be used for high DPI situations. For example, if the original surface is 32x32, then on a 2x macOS display or 200% display scale on Windows, a 64x64 version of the image will be used, if available. If a matching version of the image isn't available, the closest larger size image will be downscaled to the appropriate size and be used instead, if available. Otherwise, the closest smaller image will be upscaled and be used instead.
Parameters
window the window to change.
icon an SDL_Surface structure containing the icon for the window.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddSurfaceAlternateImage
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!icon) {
        return SDL_InvalidParamError("icon");
    }
    SDL_DestroySurface(window->icon);
    // Convert the icon into ARGB8888
    window->icon = SDL_ConvertSurface(icon, SDL_PIXELFORMAT_ARGB8888);
    if (!window->icon) {
        return false;
    }
    if (!_this->SetWindowIcon) {
        return SDL_Unsupported();
    }
    return _this->SetWindowIcon(_this, window, window->icon);
}
References _this, CHECK_WINDOW_MAGIC, SDL_ConvertSurface(), SDL_DestroySurface(), SDL_InvalidParamError, SDL_PIXELFORMAT_ARGB8888, and SDL_Unsupported.
SDL_SetWindowKeyboardGrab()
bool SDL_SetWindowKeyboardGrab (SDL_Window * window, bool grabbed)
Set a window's keyboard grab mode.
Keyboard grab enables capture of system keyboard shortcuts like Alt+Tab or the Meta/Super key. Note that not all system keyboard shortcuts can be captured by applications (one example is Ctrl+Alt+Del on Windows).
This is primarily intended for specialized applications such as VNC clients or VM frontends. Normal games should not use keyboard grab.
When keyboard grab is enabled, SDL will continue to handle Alt+Tab when the window is full-screen to ensure the user is not trapped in your application. If you have a custom keyboard shortcut to exit fullscreen mode, you may suppress this behavior with SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED.
If the caller enables a grab while another window is currently grabbed, the other window loses its grab in favor of the caller's window.
Parameters
window the window for which the keyboard grab mode should be set.
grabbed this is true to grab keyboard, and false to release.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowKeyboardGrab
SDL_SetWindowMouseGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        if (grabbed) {
            window->pending_flags |= SDL_WINDOW_KEYBOARD_GRABBED;
        } else {
            window->pending_flags &= ~SDL_WINDOW_KEYBOARD_GRABBED;
        }
        return true;
    }
    if (!!grabbed == !!(window->flags & SDL_WINDOW_KEYBOARD_GRABBED)) {
        return true;
    }
    if (grabbed) {
        window->flags |= SDL_WINDOW_KEYBOARD_GRABBED;
    } else {
        window->flags &= ~SDL_WINDOW_KEYBOARD_GRABBED;
    }
    SDL_UpdateWindowGrab(window);
    if (grabbed && !(window->flags & SDL_WINDOW_KEYBOARD_GRABBED)) {
        return false;
    }
    return true;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_UpdateWindowGrab(), SDL_WINDOW_HIDDEN, and SDL_WINDOW_KEYBOARD_GRABBED.
Referenced by ApplyWindowFlags().
SDL_SetWindowMaximumSize()
bool SDL_SetWindowMaximumSize (SDL_Window * window, int max_w, int max_h)
Set the maximum size of a window's client area.
Parameters
window the window to change.
max_w the maximum width of the window, or 0 for no limit.
max_h the maximum height of the window, or 0 for no limit.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMaximumSize
SDL_SetWindowMinimumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (max_w < 0) {
        return SDL_InvalidParamError("max_w");
    }
    if (max_h < 0) {
        return SDL_InvalidParamError("max_h");
    }
    if ((max_w && max_w < window->min_w) ||
        (max_h && max_h < window->min_h)) {
        return SDL_SetError("SDL_SetWindowMaximumSize(): Tried to set maximum size smaller than minimum size");
    }
    window->max_w = max_w;
    window->max_h = max_h;
    if (_this->SetWindowMaximumSize) {
        _this->SetWindowMaximumSize(_this, window);
    }
    // Ensure that window is not larger than maximal size
    int w = window->last_size_pending ? window->pending.w : window->floating.w;
    int h = window->last_size_pending ? window->pending.h : window->floating.h;
    w = window->max_w ? SDL_min(w, window->max_w) : w;
    h = window->max_h ? SDL_min(h, window->max_h) : h;
    return SDL_SetWindowSize(window, w, h);
}
References _this, CHECK_WINDOW_MAGIC, SDL_InvalidParamError, SDL_min, SDL_SetError(), and SDL_SetWindowSize().
SDL_SetWindowMinimumSize()
bool SDL_SetWindowMinimumSize (SDL_Window * window, int min_w, int min_h)
Set the minimum size of a window's client area.
Parameters
window the window to change.
min_w the minimum width of the window, or 0 for no limit.
min_h the minimum height of the window, or 0 for no limit.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMinimumSize
SDL_SetWindowMaximumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (min_w < 0) {
        return SDL_InvalidParamError("min_w");
    }
    if (min_h < 0) {
        return SDL_InvalidParamError("min_h");
    }
    if ((window->max_w && min_w > window->max_w) ||
        (window->max_h && min_h > window->max_h)) {
        return SDL_SetError("SDL_SetWindowMinimumSize(): Tried to set minimum size larger than maximum size");
    }
    window->min_w = min_w;
    window->min_h = min_h;
    if (_this->SetWindowMinimumSize) {
        _this->SetWindowMinimumSize(_this, window);
    }
    // Ensure that window is not smaller than minimal size
    int w = window->last_size_pending ? window->pending.w : window->floating.w;
    int h = window->last_size_pending ? window->pending.h : window->floating.h;
    w = window->min_w ? SDL_max(w, window->min_w) : w;
    h = window->min_h ? SDL_max(h, window->min_h) : h;
    return SDL_SetWindowSize(window, w, h);
}
References _this, CHECK_WINDOW_MAGIC, SDL_InvalidParamError, SDL_max, SDL_SetError(), and SDL_SetWindowSize().
SDL_SetWindowModal()
bool SDL_SetWindowModal (SDL_Window * window, bool modal)
Toggle the state of the window as modal.
To enable modal status on a window, the window must currently be the child window of a parent, or toggling modal status on will fail.
Parameters
window the window on which to set the modal state.
modal true to toggle modal status on, false to toggle it off.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowParent
SDL_WINDOW_MODAL
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->SetWindowModal) {
        return SDL_Unsupported();
    }
    if (modal) {
        if (!window->parent) {
            return SDL_SetError("Window must have a parent to enable the modal state; use SDL_SetWindowParent() to set the parent first.");
        }
        window->flags |= SDL_WINDOW_MODAL;
    } else if (window->flags & SDL_WINDOW_MODAL) {
        window->flags &= ~SDL_WINDOW_MODAL;
    } else {
        return true; // Already not modal, so nothing to do.
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        return true;
    }
    return _this->SetWindowModal(_this, window, modal);
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SetError(), SDL_Unsupported, SDL_WINDOW_HIDDEN, and SDL_WINDOW_MODAL.
Referenced by ApplyWindowFlags(), and SDL_RecreateWindow().
SDL_SetWindowMouseGrab()
bool SDL_SetWindowMouseGrab (SDL_Window * window, bool grabbed)
Set a window's mouse grab mode.
Mouse grab confines the mouse cursor to the window.
Parameters
window the window for which the mouse grab mode should be set.
grabbed this is true to grab mouse, and false to release.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMouseRect
SDL_SetWindowMouseRect
SDL_SetWindowKeyboardGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        if (grabbed) {
            window->pending_flags |= SDL_WINDOW_MOUSE_GRABBED;
        } else {
            window->pending_flags &= ~SDL_WINDOW_MOUSE_GRABBED;
        }
        return true;
    }
    if (!!grabbed == !!(window->flags & SDL_WINDOW_MOUSE_GRABBED)) {
        return true;
    }
    if (grabbed) {
        window->flags |= SDL_WINDOW_MOUSE_GRABBED;
    } else {
        window->flags &= ~SDL_WINDOW_MOUSE_GRABBED;
    }
    SDL_UpdateWindowGrab(window);
    if (grabbed && !(window->flags & SDL_WINDOW_MOUSE_GRABBED)) {
        return false;
    }
    return true;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_UpdateWindowGrab(), SDL_WINDOW_HIDDEN, and SDL_WINDOW_MOUSE_GRABBED.
Referenced by ApplyWindowFlags().
SDL_SetWindowMouseRect()
bool SDL_SetWindowMouseRect (SDL_Window * window, const SDL_Rect * rect)
Confines the cursor to the specified area of a window.
Note that this does NOT grab the cursor, it only defines the area a cursor is restricted to when the window has mouse focus.
Parameters
window the window that will be associated with the barrier.
rect a rectangle area in window-relative coordinates. If NULL the barrier for the specified window will be destroyed.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMouseRect
SDL_GetWindowMouseGrab
SDL_SetWindowMouseGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        SDL_memcpy(&window->mouse_rect, rect, sizeof(*rect));
    } else {
        SDL_zero(window->mouse_rect);
    }
    if (_this->SetWindowMouseRect) {
        return _this->SetWindowMouseRect(_this, window);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_memcpy, and SDL_zero.
SDL_SetWindowOpacity()
bool SDL_SetWindowOpacity (SDL_Window * window, float opacity)
Set the opacity for a window.
The parameter opacity will be clamped internally between 0.0f (transparent) and 1.0f (opaque).
This function also returns false if setting the opacity isn't supported.
Parameters
window the window which will be made transparent or opaque.
opacity the opacity value (0.0f - transparent, 1.0f - opaque).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowOpacity
{
    bool result;
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->SetWindowOpacity) {
        return SDL_Unsupported();
    }
    if (opacity < 0.0f) {
        opacity = 0.0f;
    } else if (opacity > 1.0f) {
        opacity = 1.0f;
    }
    result = _this->SetWindowOpacity(_this, window, opacity);
    if (result) {
        window->opacity = opacity;
    }
    return result;
}
References _this, CHECK_WINDOW_MAGIC, and SDL_Unsupported.
SDL_SetWindowParent()
bool SDL_SetWindowParent (SDL_Window * window, SDL_Window * parent)
Set the window as a child of a parent window.
If the window is already the child of an existing window, it will be reparented to the new owner. Setting the parent window to NULL unparents the window and removes child window status.
If a parent window is hidden or destroyed, the operation will be recursively applied to child windows. Child windows hidden with the parent that did not have their hidden status explicitly set will be restored when the parent is shown.
Attempting to set the parent of a window that is currently in the modal state will fail. Use SDL_SetWindowModal() to cancel the modal status before attempting to change the parent.
Popup windows cannot change parents and attempts to do so will fail.
Setting a parent window that is currently the sibling or descendent of the child window results in undefined behavior.
Parameters
window the window that should become the child of a parent.
parent the new parent window for the child window.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowModal
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (parent) {
        CHECK_WINDOW_MAGIC(parent, false);
        CHECK_WINDOW_NOT_POPUP(parent, false);
    }
    if (window == parent) {
        return SDL_SetError("Cannot set the parent of a window to itself.");
    }
    if (!_this->SetWindowParent) {
        return SDL_Unsupported();
    }
    if (window->flags & SDL_WINDOW_MODAL) {
        return SDL_SetError("Modal windows cannot change parents; call SDL_SetWindowModal() to clear modal status first.");
    }
    if (window->parent == parent) {
        return true;
    }
    const bool ret = _this->SetWindowParent(_this, window, parent);
    SDL_UpdateWindowHierarchy(window, ret ? parent : NULL);
    return ret;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, NULL, SDL_SetError(), SDL_Unsupported, SDL_UpdateWindowHierarchy(), and SDL_WINDOW_MODAL.
SDL_SetWindowPosition()
bool SDL_SetWindowPosition (SDL_Window * window, int x, int y)
Request that the window's position be set.
If the window is in an exclusive fullscreen or maximized state, this request has no effect.
This can be used to reposition fullscreen-desktop windows onto a different display, however, as exclusive fullscreen windows are locked to a specific display, they can only be repositioned programmatically via SDL_SetWindowFullscreenMode().
On some windowing systems this request is asynchronous and the new coordinates may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window position changes, an SDL_EVENT_WINDOW_MOVED event will be emitted with the window's new coordinates. Note that the new coordinates may not match the exact coordinates requested, as some windowing systems can restrict the position of the window in certain scenarios (e.g. constraining the position so the window is always within desktop bounds). Additionally, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to reposition.
x the x coordinate of the window, or SDL_WINDOWPOS_CENTERED or SDL_WINDOWPOS_UNDEFINED.
y the y coordinate of the window, or SDL_WINDOWPOS_CENTERED or SDL_WINDOWPOS_UNDEFINED.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowPosition
SDL_SyncWindow
{
    SDL_DisplayID original_displayID;
    CHECK_WINDOW_MAGIC(window, false);
    const int w = window->last_size_pending ? window->pending.w : window->windowed.w;
    const int h = window->last_size_pending ? window->pending.h : window->windowed.h;
    original_displayID = SDL_GetDisplayForWindow(window);
    if (SDL_WINDOWPOS_ISUNDEFINED(x)) {
        x = window->windowed.x;
    }
    if (SDL_WINDOWPOS_ISUNDEFINED(y)) {
        y = window->windowed.y;
    }
    if (SDL_WINDOWPOS_ISCENTERED(x) || SDL_WINDOWPOS_ISCENTERED(y)) {
        SDL_DisplayID displayID = original_displayID;
        SDL_Rect bounds;
        if (SDL_WINDOWPOS_ISCENTERED(x) && (x & 0xFFFF)) {
            displayID = (x & 0xFFFF);
        } else if (SDL_WINDOWPOS_ISCENTERED(y) && (y & 0xFFFF)) {
            displayID = (y & 0xFFFF);
        }
        if (displayID == 0 || SDL_GetDisplayIndex(displayID) < 0) {
            displayID = SDL_GetPrimaryDisplay();
        }
        SDL_zero(bounds);
        if (!SDL_GetDisplayUsableBounds(displayID, &bounds) || w > bounds.w || h > bounds.h) {
            if (!SDL_GetDisplayBounds(displayID, &bounds)) {
                return false;
            }
        }
        if (SDL_WINDOWPOS_ISCENTERED(x)) {
            x = bounds.x + (bounds.w - w) / 2;
        }
        if (SDL_WINDOWPOS_ISCENTERED(y)) {
            y = bounds.y + (bounds.h - h) / 2;
        }
    }
    window->pending.x = x;
    window->pending.y = y;
    window->undefined_x = false;
    window->undefined_y = false;
    window->last_position_pending = true;
    if (_this->SetWindowPosition) {
        const bool result = _this->SetWindowPosition(_this, window);
        if (result) {
            SDL_SyncIfRequired(window);
        }
        return result;
    }
    return SDL_Unsupported();
}
References _this, CHECK_WINDOW_MAGIC, SDL_Rect::h, SDL_GetDisplayBounds(), SDL_GetDisplayForWindow(), SDL_GetDisplayIndex(), SDL_GetDisplayUsableBounds(), SDL_GetPrimaryDisplay(), SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOWPOS_ISCENTERED, SDL_WINDOWPOS_ISUNDEFINED, SDL_zero, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
SDL_SetWindowProgressState()
bool SDL_SetWindowProgressState (SDL_Window * window, SDL_ProgressState state)
Sets the state of the progress bar for the given windows taskbar icon.
Parameters
window the window whose progress state is to be modified.
state the progress state. SDL_PROGRESS_STATE_NONE stops displaying the progress bar.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (state < SDL_PROGRESS_STATE_NONE || state > SDL_PROGRESS_STATE_ERROR) {
        return SDL_InvalidParamError("state");
    }
    window->progress_state = state;
    if (_this->ApplyWindowProgress) {
        if (!_this->ApplyWindowProgress(_this, window)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_InvalidParamError, and SDL_PROGRESS_STATE_ERROR.
Referenced by SDL_FinishWindowCreation().
SDL_SetWindowProgressValue()
bool SDL_SetWindowProgressValue (SDL_Window * window, float value)
Sets the value of the progress bar for the given windows taskbar icon.
Parameters
window the window whose progress value is to be modified.
value the progress value in the range of [0.0f - 1.0f]. If the value is outside the valid range, it gets clamped.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    value = SDL_clamp(value, 0.0f, 1.f);
    window->progress_value = value;
    if (_this->ApplyWindowProgress) {
        if (!_this->ApplyWindowProgress(_this, window)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_clamp.
Referenced by SDL_FinishWindowCreation().
SDL_SetWindowRelativeMouseMode()
bool SDL_SetWindowRelativeMouseMode (SDL_Window * window, bool enabled)
Set relative mouse mode for a window.
While the window has focus and relative mouse mode is enabled, the cursor is hidden, the mouse position is constrained to the window, and SDL will report continuous relative mouse motion even if the mouse is at the edge of the window.
If you'd like to keep the mouse position fixed while in relative mode you can use SDL_SetWindowMouseRect(). If you'd like the cursor to be at a specific location when relative mode ends, you should use SDL_WarpMouseInWindow() before disabling relative mode.
This function will flush any pending mouse motion for this window.
Parameters
window the window to change.
enabled true to enable relative mode, false to disable.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowRelativeMouseMode
{
    CHECK_WINDOW_MAGIC(window, false);
    /* If the app toggles relative mode directly, it probably shouldn't
     * also be emulating it using repeated mouse warps, so disable
     * mouse warp emulation by default.
     */
    SDL_DisableMouseWarpEmulation();
    if (enabled == SDL_GetWindowRelativeMouseMode(window)) {
        return true;
    }
    if (enabled) {
        window->flags |= SDL_WINDOW_MOUSE_RELATIVE_MODE;
    } else {
        window->flags &= ~SDL_WINDOW_MOUSE_RELATIVE_MODE;
    }
    SDL_UpdateRelativeMouseMode();
    return true;
}
References CHECK_WINDOW_MAGIC, SDL_DisableMouseWarpEmulation(), SDL_GetWindowRelativeMouseMode(), SDL_UpdateRelativeMouseMode(), and SDL_WINDOW_MOUSE_RELATIVE_MODE.
SDL_SetWindowResizable()
bool SDL_SetWindowResizable (SDL_Window * window, bool resizable)
Set the user-resizable state of a window.
This will add or remove the window's SDL_WINDOW_RESIZABLE flag and allow/disallow user resizing of the window. This is a no-op if the window's resizable state already matches the requested state.
You can't change the resizable state of a fullscreen window.
Parameters
window the window of which to change the resizable state.
resizable true to allow resizing, false to disallow.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFlags
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    const bool want = (resizable != false); // normalize the flag.
    const bool have = ((window->flags & SDL_WINDOW_RESIZABLE) != 0);
    if ((want != have) && (_this->SetWindowResizable)) {
        if (want) {
            window->flags |= SDL_WINDOW_RESIZABLE;
        } else {
            window->flags &= ~SDL_WINDOW_RESIZABLE;
            SDL_copyp(&window->windowed, &window->floating);
        }
        _this->SetWindowResizable(_this, window, want);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_copyp, and SDL_WINDOW_RESIZABLE.
SDL_SetWindowSafeAreaInsets()
void SDL_SetWindowSafeAreaInsets (SDL_Window * window, int left, int right, int top, int bottom)
{
    window->safe_inset_left = left;
    window->safe_inset_right = right;
    window->safe_inset_top = top;
    window->safe_inset_bottom = bottom;
    SDL_CheckWindowSafeAreaChanged(window);
}
References bottom, left, right, SDL_CheckWindowSafeAreaChanged(), and top.
SDL_SetWindowShape()
bool SDL_SetWindowShape (SDL_Window * window, SDL_Surface * shape)
Set the shape of a transparent window.
This sets the alpha channel of a transparent window and any fully transparent areas are also transparent to mouse clicks. If you are using something besides the SDL render API, then you are responsible for drawing the alpha channel of the window to match the shape alpha channel to get consistent cross-platform results.
The shape is copied inside this function, so you can free it afterwards. If your shape surface changes, you should call SDL_SetWindowShape() again to update the window. This is an expensive operation, so should be done sparingly.
The window must have been created with the SDL_WINDOW_TRANSPARENT flag.
Parameters
window the window.
shape the surface representing the shape of the window, or NULL to remove any current shape.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID props;
    SDL_Surface *surface;
    CHECK_WINDOW_MAGIC(window, false);
    if (!(window->flags & SDL_WINDOW_TRANSPARENT)) {
        return SDL_SetError("Window must be created with SDL_WINDOW_TRANSPARENT");
    }
    props = SDL_GetWindowProperties(window);
    if (!props) {
        return false;
    }
    surface = SDL_ConvertSurface(shape, SDL_PIXELFORMAT_ARGB32);
    if (!surface) {
        return false;
    }
    if (!SDL_SetSurfaceProperty(props, SDL_PROP_WINDOW_SHAPE_POINTER, surface)) {
        return false;
    }
    if (_this->UpdateWindowShape) {
        if (!_this->UpdateWindowShape(_this, window, surface)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_ConvertSurface(), SDL_GetWindowProperties(), SDL_PIXELFORMAT_ARGB32, SDL_PROP_WINDOW_SHAPE_POINTER, SDL_SetError(), SDL_SetSurfaceProperty(), and SDL_WINDOW_TRANSPARENT.
SDL_SetWindowSize()
bool SDL_SetWindowSize (SDL_Window * window, int w, int h)
Request that the size of a window's client area be set.
If the window is in a fullscreen or maximized state, this request has no effect.
To change the exclusive fullscreen mode of a window, use SDL_SetWindowFullscreenMode().
On some windowing systems, this request is asynchronous and the new window size may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window size changes, an SDL_EVENT_WINDOW_RESIZED event will be emitted with the new window dimensions. Note that the new dimensions may not match the exact size requested, as some windowing systems can restrict the window size in certain scenarios (e.g. constraining the size of the content area to remain within the usable desktop bounds). Additionally, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to change.
w the width of the window, must be > 0.
h the height of the window, must be > 0.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSize
SDL_SetWindowFullscreenMode
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    if (w <= 0) {
        return SDL_InvalidParamError("w");
    }
    if (h <= 0) {
        return SDL_InvalidParamError("h");
    }
    // It is possible for the aspect ratio constraints to not satisfy the size constraints.
    // The size constraints will override the aspect ratio constraints so we will apply the
    // the aspect ratio constraints first
    float new_aspect = w / (float)h;
    if (window->max_aspect > 0.0f && new_aspect > window->max_aspect) {
        w = (int)SDL_roundf(h * window->max_aspect);
    } else if (window->min_aspect > 0.0f && new_aspect < window->min_aspect) {
        h = (int)SDL_roundf(w / window->min_aspect);
    }
    // Make sure we don't exceed any window size limits
    if (window->min_w && w < window->min_w) {
        w = window->min_w;
    }
    if (window->max_w && w > window->max_w) {
        w = window->max_w;
    }
    if (window->min_h && h < window->min_h) {
        h = window->min_h;
    }
    if (window->max_h && h > window->max_h) {
        h = window->max_h;
    }
    window->last_size_pending = true;
    window->pending.w = w;
    window->pending.h = h;
    if (_this->SetWindowSize) {
        _this->SetWindowSize(_this, window);
        SDL_SyncIfRequired(window);
    } else {
        return SDL_Unsupported();
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_InvalidParamError, SDL_roundf(), SDL_SyncIfRequired(), and SDL_Unsupported.
Referenced by SDL_SetWindowAspectRatio(), SDL_SetWindowMaximumSize(), and SDL_SetWindowMinimumSize().
SDL_SetWindowSurfaceVSync()
bool SDL_SetWindowSurfaceVSync (SDL_Window * window, int vsync)
Toggle VSync for the window surface.
When a window surface is created, vsync defaults to SDL_WINDOW_SURFACE_VSYNC_DISABLED.
The vsync parameter can be 1 to synchronize present with every vertical refresh, 2 to synchronize present with every second vertical refresh, etc., SDL_WINDOW_SURFACE_VSYNC_ADAPTIVE for late swap tearing (adaptive vsync), or SDL_WINDOW_SURFACE_VSYNC_DISABLED to disable. Not every value is supported by every driver, so you should check the return value to see whether the requested setting is supported.
Parameters
window the window.
vsync the vertical refresh sync interval.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurfaceVSync
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->SetWindowFramebufferVSync) {
        return SDL_Unsupported();
    }
    return _this->SetWindowFramebufferVSync(_this, window, vsync);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_Unsupported.
SDL_SetWindowTextureVSync()
bool SDL_SetWindowTextureVSync (SDL_VideoDevice * _this, SDL_Window * window, int vsync)
{
    SDL_WindowTextureData *data;
    data = (SDL_WindowTextureData *)SDL_GetPointerProperty(SDL_GetWindowProperties(window), SDL_PROP_WINDOW_TEXTUREDATA_POINTER, NULL);
    if (!data) {
        return false;
    }
    if (!data->renderer) {
        return false;
    }
    return SDL_SetRenderVSync(data->renderer, vsync);
}
References _this, NULL, SDL_GetPointerProperty(), SDL_GetWindowProperties(), SDL_PROP_WINDOW_TEXTUREDATA_POINTER, and SDL_SetRenderVSync().
Referenced by SDL_CreateWindowFramebuffer(), and SDL_SetRenderVSync().
SDL_SetWindowTitle()
bool SDL_SetWindowTitle (SDL_Window * window, const char * title)
Set the title of a window.
This string is expected to be in UTF-8 encoding.
Parameters
window the window to change.
title the desired window title in UTF-8 format.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowTitle
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (title == window->title) {
        return true;
    }
    if (!title) {
        title = "";
    }
    if (window->title && SDL_strcmp(title, window->title) == 0) {
        return true;
    }
    SDL_free(window->title);
    window->title = SDL_strdup(title);
    if (_this->SetWindowTitle) {
        _this->SetWindowTitle(_this, window);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_free(), SDL_strcmp(), and SDL_strdup().
Referenced by SDL_CreateWindowWithProperties().
SDL_ShouldAllowTopmost()
bool SDL_ShouldAllowTopmost (void)
{
    return SDL_GetHintBoolean(SDL_HINT_WINDOW_ALLOW_TOPMOST, true);
}
References SDL_GetHintBoolean(), and SDL_HINT_WINDOW_ALLOW_TOPMOST.
SDL_ShouldFocusPopup()
bool SDL_ShouldFocusPopup (SDL_Window * window)
{
    SDL_Window *toplevel_parent;
    for (toplevel_parent = window->parent; SDL_WINDOW_IS_POPUP(toplevel_parent); toplevel_parent = toplevel_parent->parent) {
    }
    SDL_Window *current_focus = toplevel_parent->keyboard_focus;
    bool found_higher_focus = false;
    /* Traverse the window tree from the currently focused window to the toplevel parent and see if we encounter
     * the new focus request. If the new window is found, a higher-level window already has focus.
     */
    SDL_Window *w;
    for (w = current_focus; w != toplevel_parent; w = w->parent) {
        if (w == window) {
            found_higher_focus = true;
            break;
        }
    }
    return !found_higher_focus || w == toplevel_parent;
}
References SDL_Window::keyboard_focus, SDL_Window::parent, and SDL_WINDOW_IS_POPUP.
SDL_ShouldMinimizeOnFocusLoss()
bool SDL_ShouldMinimizeOnFocusLoss (SDL_Window * window) static
{
    const char *hint;
    if (!(window->flags & SDL_WINDOW_FULLSCREEN) || window->is_destroying) {
        return false;
    }
#if defined(SDL_PLATFORM_MACOS) && defined(SDL_VIDEO_DRIVER_COCOA)
    if (SDL_strcmp(_this->name, "cocoa") == 0) { // don't do this for X11, etc
        if (Cocoa_IsShowingModalDialog(window)) {
            return false;  // modal system dialogs can live over fullscreen windows, don't minimize.
        } else if (Cocoa_IsWindowInFullscreenSpace(window)) {
            return false;
        }
    }
#endif
#ifdef SDL_PLATFORM_ANDROID
    {
        extern bool Android_JNI_ShouldMinimizeOnFocusLoss(void);
        if (!Android_JNI_ShouldMinimizeOnFocusLoss()) {
            return false;
        }
    }
#endif
    // Real fullscreen windows should minimize on focus loss so the desktop video mode is restored
    hint = SDL_GetHint(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS);
    if (!hint || !*hint || SDL_strcasecmp(hint, "auto") == 0) {
        if (window->fullscreen_exclusive && !SDL_ModeSwitchingEmulated(_this)) {
            return true;
        } else {
            return false;
        }
    }
    return SDL_GetHintBoolean(SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, false);
}
References _this, Android_JNI_ShouldMinimizeOnFocusLoss(), SDL_GetHint(), SDL_GetHintBoolean(), SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS, SDL_ModeSwitchingEmulated(), SDL_strcasecmp(), SDL_strcmp(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_OnWindowFocusLost().
SDL_ShouldRelinquishPopupFocus()
bool SDL_ShouldRelinquishPopupFocus (SDL_Window * window, SDL_Window ** new_focus)
{
    SDL_Window *focus = window->parent;
    bool set_focus = !!(window->flags & SDL_WINDOW_INPUT_FOCUS);
    // Find the highest level window, up to the toplevel parent, that isn't being hidden or destroyed, and can grab the keyboard focus.
    while (SDL_WINDOW_IS_POPUP(focus) && ((focus->flags & SDL_WINDOW_NOT_FOCUSABLE) || focus->is_hiding || focus->is_destroying)) {
        focus = focus->parent;
        // If some window in the chain currently had focus, set it to the new lowest-level window.
        if (!set_focus) {
            set_focus = !!(focus->flags & SDL_WINDOW_INPUT_FOCUS);
        }
    }
    *new_focus = focus;
    return set_focus;
}
References SDL_Window::flags, SDL_Window::is_destroying, SDL_Window::is_hiding, SDL_Window::parent, SDL_WINDOW_INPUT_FOCUS, SDL_WINDOW_IS_POPUP, and SDL_WINDOW_NOT_FOCUSABLE.
SDL_ShowMessageBox()
bool SDL_ShowMessageBox (const SDL_MessageBoxData * messageboxdata, int * buttonid)
Create a modal message box.
If your needs aren't complex, it might be easier to use SDL_ShowSimpleMessageBox.
This function should be called on the thread that created the parent window, or on the main thread if the messagebox has no parent. It will block execution of that thread until the user clicks a button or closes the messagebox.
This function may be called at any time, even before SDL_Init(). This makes it useful for reporting errors like a failure to create a renderer or OpenGL context.
On X11, SDL rolls its own dialog box with X11 primitives instead of a formal toolkit like GTK+ or Qt.
Note that if SDL_Init() would fail because there isn't any available video target, this function is likely to fail for the same reasons. If this is a concern, check the return value from this function and fall back to writing to stderr if you can.
Parameters
messageboxdata the SDL_MessageBoxData structure with title, text and other options.
buttonid the pointer to which user id of hit button should be copied.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShowSimpleMessageBox
{
    int dummybutton;
    bool result = false;
    bool show_cursor_prev;
    SDL_Window *current_window;
    SDL_MessageBoxData mbdata;
    if (!messageboxdata) {
        return SDL_InvalidParamError("messageboxdata");
    } else if (messageboxdata->numbuttons < 0) {
        return SDL_SetError("Invalid number of buttons");
    }
    // in case either the title or message was a pointer from SDL_GetError(), make a copy
    // now, as we'll likely overwrite error state in here.
    bool titleisstack = false, msgisstack = false;
    char *titlecpy = NULL;
    char *msgcpy = NULL;
    if (messageboxdata->title) {
        const size_t slen = SDL_strlen(messageboxdata->title) + 1;
        titlecpy = SDL_small_alloc(char, slen, &titleisstack);
        if (!titlecpy) {
            return false;
        }
        SDL_memcpy(titlecpy, messageboxdata->title, slen);
    }
    if (messageboxdata->message) {
        const size_t slen = SDL_strlen(messageboxdata->message) + 1;
        msgcpy = SDL_small_alloc(char, slen, &msgisstack);
        if (!msgcpy) {
            SDL_small_free(titlecpy, titleisstack);
            return false;
        }
        SDL_memcpy(msgcpy, messageboxdata->message, slen);
    }
    (void)SDL_AtomicIncRef(&SDL_messagebox_count);
    current_window = SDL_GetKeyboardFocus();
    SDL_UpdateMouseCapture(false);
    SDL_SetRelativeMouseMode(false);
    show_cursor_prev = SDL_CursorVisible();
    SDL_ShowCursor();
    SDL_ResetKeyboard();
    if (!buttonID) {
        buttonID = &dummybutton;
    }
    SDL_memcpy(&mbdata, messageboxdata, sizeof(*messageboxdata));
    mbdata.title = titlecpy;
    if (!mbdata.title) {
        mbdata.title = "";
    }
    mbdata.message = msgcpy;
    if (!mbdata.message) {
        mbdata.message = "";
    }
    messageboxdata = &mbdata;
    SDL_ClearError();
    if (_this && _this->ShowMessageBox) {
        result = _this->ShowMessageBox(_this, messageboxdata, buttonID);
    } else {
        // It's completely fine to call this function before video is initialized
        const char *driver_name = SDL_GetHint(SDL_HINT_VIDEO_DRIVER);
        if (driver_name && *driver_name != 0) {
            const char *driver_attempt = driver_name;
            while (driver_attempt && (*driver_attempt != 0) && !result) {
                const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
                size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
                for (int i = 0; bootstrap[i]; ++i) {
                    if (bootstrap[i]->ShowMessageBox && (driver_attempt_len == SDL_strlen(bootstrap[i]->name)) &&
                        (SDL_strncasecmp(bootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                        if (bootstrap[i]->ShowMessageBox(messageboxdata, buttonID)) {
                            result = true;
                        }
                        break;
                    }
                }
                driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
            }
        } else {
            for (int i = 0; bootstrap[i]; ++i) {
                if (bootstrap[i]->ShowMessageBox && bootstrap[i]->ShowMessageBox(messageboxdata, buttonID)) {
                    result = true;
                    break;
                }
            }
        }
    }
    if (!result) {
        const char *error = SDL_GetError();
        if (!*error) {
            SDL_SetError("No message system available");
        }
    } else {
        SDL_ClearError();
    }
    (void)SDL_AtomicDecRef(&SDL_messagebox_count);
    if (current_window) {
        SDL_RaiseWindow(current_window);
    }
    if (!show_cursor_prev) {
        SDL_HideCursor();
    }
    SDL_UpdateRelativeMouseMode();
    SDL_UpdateMouseCapture(false);
    SDL_small_free(msgcpy, msgisstack);
    SDL_small_free(titlecpy, titleisstack);
    return result;
}
References _this, bootstrap, SDL_MessageBoxData::message, NULL, SDL_MessageBoxData::numbuttons, SDL_AtomicDecRef, SDL_AtomicIncRef, SDL_ClearError(), SDL_CursorVisible(), SDL_GetError(), SDL_GetHint(), SDL_GetKeyboardFocus(), SDL_HideCursor(), SDL_HINT_VIDEO_DRIVER, SDL_InvalidParamError, SDL_memcpy, SDL_messagebox_count, SDL_RaiseWindow(), SDL_ResetKeyboard(), SDL_SetError(), SDL_SetRelativeMouseMode(), SDL_ShowCursor(), SDL_small_alloc, SDL_small_free, SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), SDL_UpdateMouseCapture(), SDL_UpdateRelativeMouseMode(), SDL_MessageBoxData::title, and void().
Referenced by SDL_PromptAssertion(), and SDL_ShowSimpleMessageBox().
SDL_ShowSimpleMessageBox()
bool SDL_ShowSimpleMessageBox (SDL_MessageBoxFlags flags, const char * title, const char * message, SDL_Window * window)
Display a simple modal message box.
If your needs aren't complex, this function is preferred over SDL_ShowMessageBox.
flags may be any of the following:
SDL_MESSAGEBOX_ERROR: error dialog
SDL_MESSAGEBOX_WARNING: warning dialog
SDL_MESSAGEBOX_INFORMATION: informational dialog
This function should be called on the thread that created the parent window, or on the main thread if the messagebox has no parent. It will block execution of that thread until the user clicks a button or closes the messagebox.
This function may be called at any time, even before SDL_Init(). This makes it useful for reporting errors like a failure to create a renderer or OpenGL context.
On X11, SDL rolls its own dialog box with X11 primitives instead of a formal toolkit like GTK+ or Qt.
Note that if SDL_Init() would fail because there isn't any available video target, this function is likely to fail for the same reasons. If this is a concern, check the return value from this function and fall back to writing to stderr if you can.
Parameters
flags an SDL_MessageBoxFlags value.
title UTF-8 title text.
message UTF-8 message text.
window the parent window, or NULL for no parent.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShowMessageBox
{
#if defined(SDL_PLATFORM_3DS)
    errorConf errCnf;
    bool hasGpuRight;
    // If the video subsystem has not been initialised, set up graphics temporarily
    hasGpuRight = gspHasGpuRight();
    if (!hasGpuRight)
        gfxInitDefault();
    errorInit(&errCnf, ERROR_TEXT_WORD_WRAP, CFG_LANGUAGE_EN);
    errorText(&errCnf, message);
    errorDisp(&errCnf);
    if (!hasGpuRight)
        gfxExit();
    return true;
#else
    SDL_MessageBoxData data;
    SDL_MessageBoxButtonData button;
    SDL_zero(data);
    data.flags = flags;
    data.title = title;
    data.message = message;
    data.numbuttons = 1;
    data.buttons = &button;
    data.window = window;
    SDL_zero(button);
    button.flags |= SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT;
    button.flags |= SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT;
    button.text = "OK";
    return SDL_ShowMessageBox(&data, NULL);
#endif
}
References SDL_MessageBoxButtonData::flags, NULL, SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT, SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT, SDL_ShowMessageBox(), SDL_zero, and SDL_MessageBoxButtonData::text.
Referenced by OutOfMemory(), SDL_PromptAssertion(), and SDL_RunApp().
SDL_ShowWindow()
bool SDL_ShowWindow (SDL_Window * window)
Show a window.
Parameters
window the window to show.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HideWindow
SDL_RaiseWindow
{
    SDL_Window *child;
    CHECK_WINDOW_MAGIC(window, false);
    if (!(window->flags & SDL_WINDOW_HIDDEN)) {
        return true;
    }
    // If the parent is hidden, set the flag to restore this when the parent is shown
    if (window->parent && (window->parent->flags & SDL_WINDOW_HIDDEN)) {
        window->restore_on_show = true;
        return true;
    }
    if (_this->ShowWindow) {
        _this->ShowWindow(_this, window);
    } else {
        SDL_SetMouseFocus(window);
        SDL_SetKeyboardFocus(window);
    }
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_SHOWN, 0, 0);
    // Restore child windows
    for (child = window->first_child; child; child = child->next_sibling) {
        if (!child->restore_on_show && (child->flags & SDL_WINDOW_HIDDEN)) {
            break;
        }
        SDL_ShowWindow(child);
        child->restore_on_show = false;
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_Window::flags, SDL_Window::next_sibling, SDL_Window::restore_on_show, SDL_EVENT_WINDOW_SHOWN, SDL_SendWindowEvent(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_ShowWindow(), and SDL_WINDOW_HIDDEN.
Referenced by SDL_CreateWindowAndRenderer(), SDL_FinishWindowCreation(), and SDL_ShowWindow().
SDL_ShowWindowSystemMenu()
bool SDL_ShowWindowSystemMenu (SDL_Window * window, int x, int y)
Display the system-level window menu.
This default window menu is provided by the system and on some platforms provides functionality for setting or changing privileged state on the window, such as moving it between workspaces or displays, or toggling the always-on-top property.
On platforms or desktops where this is unsupported, this function does nothing.
Parameters
window the window for which the menu will be displayed.
x the x coordinate of the menu, relative to the origin (top-left) of the client area.
y the y coordinate of the menu, relative to the origin (top-left) of the client area.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false)
    CHECK_WINDOW_NOT_POPUP(window, false)
    if (_this->ShowWindowSystemMenu) {
        _this->ShowWindowSystemMenu(window, x, y);
        return true;
    }
    return SDL_Unsupported();
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_Unsupported.
SDL_StartTextInput()
bool SDL_StartTextInput (SDL_Window * window)
Start accepting Unicode text input events in a window.
This function will enable text input (SDL_EVENT_TEXT_INPUT and SDL_EVENT_TEXT_EDITING events) in the specified window. Please use this function paired with SDL_StopTextInput().
Text input events are not received by default.
On some platforms using this function shows the screen keyboard and/or activates an IME, which can prevent some key press events from being passed through.
Parameters
window the window to enable text input.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextInputArea
SDL_StartTextInputWithProperties
SDL_StopTextInput
SDL_TextInputActive
{
    return SDL_StartTextInputWithProperties(window, 0);
}
References SDL_StartTextInputWithProperties().
SDL_StartTextInputWithProperties()
bool SDL_StartTextInputWithProperties (SDL_Window * window, SDL_PropertiesID props)
Start accepting Unicode text input events in a window, with properties describing the input.
This function will enable text input (SDL_EVENT_TEXT_INPUT and SDL_EVENT_TEXT_EDITING events) in the specified window. Please use this function paired with SDL_StopTextInput().
Text input events are not received by default.
On some platforms using this function shows the screen keyboard and/or activates an IME, which can prevent some key press events from being passed through.
These are the supported properties:
SDL_PROP_TEXTINPUT_TYPE_NUMBER - an SDL_TextInputType value that describes text being input, defaults to SDL_TEXTINPUT_TYPE_TEXT.
SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER - an SDL_Capitalization value that describes how text should be capitalized, defaults to SDL_CAPITALIZE_SENTENCES for normal text entry, SDL_CAPITALIZE_WORDS for SDL_TEXTINPUT_TYPE_TEXT_NAME, and SDL_CAPITALIZE_NONE for e-mail addresses, usernames, and passwords.
SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN - true to enable auto completion and auto correction, defaults to true.
SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN - true if multiple lines of text are allowed. This defaults to true if SDL_HINT_RETURN_KEY_HIDES_IME is "0" or is not set, and defaults to false if SDL_HINT_RETURN_KEY_HIDES_IME is "1".
On Android you can directly specify the input type:
SDL_PROP_TEXTINPUT_ANDROID_INPUTTYPE_NUMBER - the text input type to use, overriding other properties. This is documented at https://developer.android.com/reference/android/text/InputType
Parameters
window the window to enable text input.
props the properties to use.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextInputArea
SDL_StartTextInput
SDL_StopTextInput
SDL_TextInputActive
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->text_input_props) {
        SDL_DestroyProperties(window->text_input_props);
        window->text_input_props = 0;
    }
    if (props) {
        window->text_input_props = SDL_CreateProperties();
        if (!window->text_input_props) {
            return false;
        }
        if (!SDL_CopyProperties(props, window->text_input_props)) {
            return false;
        }
    }
    if (_this->SetTextInputProperties) {
        _this->SetTextInputProperties(_this, window, props);
    }
    // Show the on-screen keyboard, if desired
    if (AutoShowingScreenKeyboard() && !SDL_ScreenKeyboardShown(window)) {
        if (_this->ShowScreenKeyboard) {
            _this->ShowScreenKeyboard(_this, window, props);
        }
    }
    if (!window->text_input_active) {
        // Finally start the text input system
        if (_this->StartTextInput) {
            if (!_this->StartTextInput(_this, window, props)) {
                return false;
            }
        }
        window->text_input_active = true;
    }
    return true;
}
References _this, AutoShowingScreenKeyboard(), CHECK_WINDOW_MAGIC, SDL_CopyProperties(), SDL_CreateProperties(), SDL_DestroyProperties(), and SDL_ScreenKeyboardShown().
Referenced by SDL_StartTextInput().
SDL_StopTextInput()
bool SDL_StopTextInput (SDL_Window * window)
Stop receiving any text input events in a window.
If SDL_StartTextInput() showed the screen keyboard, this function will hide it.
Parameters
window the window to disable text input.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->text_input_active) {
        // Stop the text input system
        if (_this->StopTextInput) {
            _this->StopTextInput(_this, window);
        }
        window->text_input_active = false;
    }
    // Hide the on-screen keyboard, if desired
    if (AutoShowingScreenKeyboard() && SDL_ScreenKeyboardShown(window)) {
        if (_this->HideScreenKeyboard) {
            _this->HideScreenKeyboard(_this, window);
        }
    }
    return true;
}
References _this, AutoShowingScreenKeyboard(), CHECK_WINDOW_MAGIC, and SDL_ScreenKeyboardShown().
SDL_SyncHintWatcher()
void SDL_SyncHintWatcher (void * userdata, const char * name, const char * oldValue, const char * newValue) static
{
    syncHint = SDL_GetStringBoolean(newValue, false);
}
References SDL_GetStringBoolean(), and syncHint.
Referenced by SDL_VideoInit().
SDL_SyncIfRequired()
void SDL_SyncIfRequired (SDL_Window * window) static
{
    if (syncHint) {
        SDL_SyncWindow(window);
    }
}
References SDL_SyncWindow(), and syncHint.
Referenced by SDL_MaximizeWindow(), SDL_MinimizeWindow(), SDL_RestoreWindow(), SDL_SetWindowFullscreen(), SDL_SetWindowFullscreenMode(), SDL_SetWindowPosition(), and SDL_SetWindowSize().
SDL_SyncWindow()
bool SDL_SyncWindow (SDL_Window * window)
Block until any pending window state is finalized.
On asynchronous windowing systems, this acts as a synchronization barrier for pending window state. It will attempt to wait until any pending window state has been applied and is guaranteed to return within finite time. Note that for how long it can potentially block depends on the underlying window system, as window state changes may involve somewhat lengthy animations that must complete before the window is in its final requested state.
On windowing systems where changes are immediate, this does nothing.
Parameters
window the window for which to wait for the pending state to be applied.
Returns
true on success or false if the operation timed out before the window was in the requested state.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowSize
SDL_SetWindowPosition
SDL_SetWindowFullscreen
SDL_MinimizeWindow
SDL_MaximizeWindow
SDL_RestoreWindow
SDL_HINT_VIDEO_SYNC_WINDOW_OPERATIONS
{
    CHECK_WINDOW_MAGIC(window, false)
    if (_this->SyncWindow) {
        return _this->SyncWindow(_this, window);
    } else {
        return true;
    }
}
References _this, and CHECK_WINDOW_MAGIC.
Referenced by SDL_SyncIfRequired().
SDL_TextInputActive()
bool SDL_TextInputActive (SDL_Window * window)
Check whether or not Unicode text input events are enabled for a window.
Parameters
window the window to check.
Returns
true if text input events are enabled else false.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StartTextInput
{
    CHECK_WINDOW_MAGIC(window, false);
    return window->text_input_active;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_BLooper::_HandleKey(), SDL_SendEditingText(), SDL_SendEditingTextCandidates(), SDL_SendKeyboardText(), and SDL_SetKeyboardFocus().
SDL_ToggleDragAndDropSupport()
void SDL_ToggleDragAndDropSupport (void)
{
    if (_this && _this->AcceptDragAndDrop) {
        const bool enable = IsAcceptingDragAndDrop();
        SDL_Window *window;
        for (window = _this->windows; window; window = window->next) {
            _this->AcceptDragAndDrop(window, enable);
        }
    }
}
References _this, and IsAcceptingDragAndDrop().
Referenced by SDL_SetEventEnabled().
SDL_UninitializedVideo()
bool SDL_UninitializedVideo (void)
{
    return SDL_SetError("Video subsystem has not been initialized");
}
References SDL_SetError().
Referenced by SDL_DisableScreenSaver(), SDL_EGL_GetCurrentConfig(), SDL_EGL_GetCurrentDisplay(), SDL_EGL_GetProcAddress(), SDL_EGL_GetWindowSurface(), SDL_EnableScreenSaver(), SDL_GetClipboardData(), SDL_GetClipboardMimeTypes(), SDL_GetClipboardText(), SDL_GetCurrentVideoDriver(), SDL_GetDisplayIndex(), SDL_GetDisplays(), SDL_GetPrimaryDisplay(), SDL_GetPrimarySelectionText(), SDL_GetWindowFromID(), SDL_GetWindows(), SDL_GL_DestroyContext(), SDL_GL_GetAttribute(), SDL_GL_GetCurrentContext(), SDL_GL_GetCurrentWindow(), SDL_GL_GetProcAddress(), SDL_GL_LoadLibrary(), SDL_GL_MakeCurrent(), SDL_GL_SetAttribute(), SDL_GL_SetSwapInterval(), SDL_GL_UnloadLibrary(), SDL_HasClipboardData(), SDL_HasClipboardText(), SDL_HasPrimarySelectionText(), SDL_SaveClipboardMimeTypes(), SDL_SetClipboardData(), SDL_SetClipboardText(), SDL_SetPrimarySelectionText(), SDL_Vulkan_GetPresentationSupport(), SDL_Vulkan_GetVkGetInstanceProcAddr(), SDL_Vulkan_LoadLibrary(), and SDL_Vulkan_UnloadLibrary().
SDL_UpdateDesktopBounds()
void SDL_UpdateDesktopBounds (void)
{
    SDL_Rect rect;
    SDL_zero(rect);
    SDL_DisplayID *displays = SDL_GetDisplays(NULL);
    if (displays) {
        for (int i = 0; displays[i]; ++i) {
            SDL_Rect bounds;
            if (SDL_GetDisplayBounds(displays[i], &bounds)) {
                if (i == 0) {
                    SDL_copyp(&rect, &bounds);
                } else {
                    SDL_GetRectUnion(&rect, &bounds, &rect);
                }
            }
        }
        SDL_free(displays);
    }
    SDL_copyp(&_this->desktop_bounds, &rect);
}
References _this, NULL, SDL_copyp, SDL_free(), SDL_GetDisplayBounds(), SDL_GetDisplays(), SDL_GetRectUnion(), and SDL_zero.
Referenced by SDL_AddVideoDisplay(), SDL_DelVideoDisplay(), and SDL_OnDisplayMoved().
SDL_UpdateFullscreenDisplayModes()
void SDL_UpdateFullscreenDisplayModes (SDL_VideoDisplay * display) static
{
    if (display->num_fullscreen_modes == 0 && _this->GetDisplayModes) {
        _this->GetDisplayModes(_this, display);
    }
}
References _this.
Referenced by SDL_GetClosestFullscreenDisplayMode(), SDL_GetCurrentDisplayMode(), SDL_GetFullscreenDisplayModes(), and SDL_GetFullscreenModeMatch().
SDL_UpdateFullscreenMode()
bool SDL_UpdateFullscreenMode (SDL_Window * window, SDL_FullscreenOp fullscreen, bool commit)
{
    SDL_VideoDisplay *display = NULL;
    SDL_DisplayMode *mode = NULL;
    int i;
    CHECK_WINDOW_MAGIC(window, false);
    window->fullscreen_exclusive = false;
    window->update_fullscreen_on_display_changed = false;
    // If we are in the process of hiding don't go back to fullscreen
    if (window->is_destroying || window->is_hiding) {
        fullscreen = SDL_FULLSCREEN_OP_LEAVE;
    }
    // Get the correct display for this operation
    if (fullscreen) {
        display = SDL_GetVideoDisplayForFullscreenWindow(window);
        if (!display) {
            // This should never happen, but it did...
            goto done;
        }
    } else {
        for (i = 0; i < _this->num_displays; ++i) {
            display = _this->displays[i];
            if (display->fullscreen_window == window) {
                break;
            }
        }
        if (!display || i == _this->num_displays) {
            // Already not fullscreen on any display
            display = NULL;
        }
    }
    if (fullscreen) {
        mode = (SDL_DisplayMode *)SDL_GetWindowFullscreenMode(window);
        if (mode) {
            window->fullscreen_exclusive = true;
        } else {
            // Make sure the current mode is zeroed for fullscreen desktop.
            SDL_zero(window->current_fullscreen_mode);
        }
    }
#if defined(SDL_PLATFORM_MACOS) && defined(SDL_VIDEO_DRIVER_COCOA)
    /* if the window is going away and no resolution change is necessary,
       do nothing, or else we may trigger an ugly double-transition
     */
    if (SDL_strcmp(_this->name, "cocoa") == 0) { // don't do this for X11, etc
        if (window->is_destroying && !window->last_fullscreen_exclusive_display) {
            window->fullscreen_exclusive = false;
            if (display) {
                display->fullscreen_window = NULL;
            }
            goto done;
        }
        if (commit) {
            // If we're switching between a fullscreen Space and exclusive fullscreen, we need to get back to normal first.
            if (fullscreen && Cocoa_IsWindowInFullscreenSpace(window) && !window->last_fullscreen_exclusive_display && window->fullscreen_exclusive) {
                if (!Cocoa_SetWindowFullscreenSpace(window, false, true)) {
                    goto error;
                }
            } else if (fullscreen && window->last_fullscreen_exclusive_display && !window->fullscreen_exclusive) {
                for (i = 0; i < _this->num_displays; ++i) {
                    SDL_VideoDisplay *last_display = _this->displays[i];
                    if (last_display->fullscreen_window == window) {
                        SDL_SetDisplayModeForDisplay(last_display, NULL);
                        if (_this->SetWindowFullscreen) {
                            _this->SetWindowFullscreen(_this, window, last_display, false);
                        }
                        last_display->fullscreen_window = NULL;
                    }
                }
            }
            if (Cocoa_SetWindowFullscreenSpace(window, !!fullscreen, syncHint)) {
                goto done;
            }
        }
    }
#endif
    if (display) {
        // Restore the video mode on other displays if needed
        for (i = 0; i < _this->num_displays; ++i) {
            SDL_VideoDisplay *other = _this->displays[i];
            if (other != display && other->fullscreen_window == window) {
                SDL_SetDisplayModeForDisplay(other, NULL);
                other->fullscreen_window = NULL;
            }
        }
    }
    if (fullscreen) {
        int mode_w = 0, mode_h = 0;
        bool resized = false;
        // Hide any other fullscreen window on this display
        if (display->fullscreen_window &&
            display->fullscreen_window != window) {
            SDL_MinimizeWindow(display->fullscreen_window);
        }
        display->fullscreen_active = window->fullscreen_exclusive;
        if (!SDL_SetDisplayModeForDisplay(display, mode)) {
            goto error;
        }
        if (commit) {
            SDL_FullscreenResult ret = SDL_FULLSCREEN_SUCCEEDED;
            if (_this->SetWindowFullscreen) {
                ret = _this->SetWindowFullscreen(_this, window, display, fullscreen);
            } else {
                resized = true;
            }
            if (ret == SDL_FULLSCREEN_SUCCEEDED) {
                // Window is fullscreen immediately upon return. If the driver hasn't already sent the event, do so now.
                if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_ENTER_FULLSCREEN, 0, 0);
                }
            } else if (ret == SDL_FULLSCREEN_FAILED) {
                display->fullscreen_active = false;
                goto error;
            }
        }
        if (window->flags & SDL_WINDOW_FULLSCREEN) {
            display->fullscreen_window = window;
            /* Android may not resize the window to exactly what our fullscreen mode is,
             * especially on windowed Android environments like the Chromebook or Samsung DeX.
             * Given this, we shouldn't use the mode size. Android's SetWindowFullscreen
             * will generate the window event for us with the proper final size.
             *
             * This is also unnecessary on Cocoa, Wayland, Win32, and X11 (will send SDL_EVENT_WINDOW_RESIZED).
             */
            if (!SDL_SendsFullscreenDimensions(_this)) {
                SDL_Rect displayRect;
                if (mode) {
                    mode_w = mode->w;
                    mode_h = mode->h;
                    SDL_GetDisplayBounds(mode->displayID, &displayRect);
                } else {
                    mode_w = display->desktop_mode.w;
                    mode_h = display->desktop_mode.h;
                    SDL_GetDisplayBounds(display->id, &displayRect);
                }
                if (window->w != mode_w || window->h != mode_h) {
                    resized = true;
                }
                SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_MOVED, displayRect.x, displayRect.y);
                if (resized) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_RESIZED, mode_w, mode_h);
                } else {
                    SDL_OnWindowResized(window);
                }
            }
            // Restore the cursor position
            if (!SDL_DisableMouseWarpOnFullscreenTransitions(_this)) {
                SDL_RestoreMousePosition(window);
            }
        }
    } else {
        bool resized = false;
        // Restore the desktop mode
        if (display) {
            display->fullscreen_active = false;
            SDL_SetDisplayModeForDisplay(display, NULL);
        }
        if (commit) {
            SDL_FullscreenResult ret = SDL_FULLSCREEN_SUCCEEDED;
            if (_this->SetWindowFullscreen) {
                SDL_VideoDisplay *full_screen_display = display ? display : SDL_GetVideoDisplayForFullscreenWindow(window);
                if (full_screen_display) {
                    ret = _this->SetWindowFullscreen(_this, window, full_screen_display, SDL_FULLSCREEN_OP_LEAVE);
                }
            } else {
                resized = true;
            }
            if (ret == SDL_FULLSCREEN_SUCCEEDED) {
                // Window left fullscreen immediately upon return. If the driver hasn't already sent the event, do so now.
                if (window->flags & SDL_WINDOW_FULLSCREEN) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_LEAVE_FULLSCREEN, 0, 0);
                }
            } else if (ret == SDL_FULLSCREEN_FAILED) {
                goto error;
            }
        }
        if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
            if (display) {
                display->fullscreen_window = NULL;
            }
            if (!SDL_SendsFullscreenDimensions(_this)) {
                SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_MOVED, window->windowed.x, window->windowed.y);
                if (resized) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_RESIZED, window->windowed.w, window->windowed.h);
                } else {
                    SDL_OnWindowResized(window);
                }
            }
            // Restore the cursor position if we've exited fullscreen on a display
            if (display && !SDL_DisableMouseWarpOnFullscreenTransitions(_this)) {
                SDL_RestoreMousePosition(window);
            }
        }
    }
done:
    window->last_fullscreen_exclusive_display = display && (window->flags & SDL_WINDOW_FULLSCREEN) && window->fullscreen_exclusive ? display->id : 0;
    return true;
error:
    if (fullscreen) {
        // Something went wrong and the window is no longer fullscreen.
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, commit);
    }
    return false;
}
References _this, CHECK_WINDOW_MAGIC, SDL_DisplayMode::displayID, SDL_VideoDisplay::fullscreen_window, SDL_DisplayMode::h, NULL, SDL_DisableMouseWarpOnFullscreenTransitions(), SDL_EVENT_WINDOW_ENTER_FULLSCREEN, SDL_EVENT_WINDOW_LEAVE_FULLSCREEN, SDL_EVENT_WINDOW_MOVED, SDL_EVENT_WINDOW_RESIZED, SDL_FULLSCREEN_FAILED, SDL_FULLSCREEN_OP_LEAVE, SDL_FULLSCREEN_SUCCEEDED, SDL_GetDisplayBounds(), SDL_GetVideoDisplayForFullscreenWindow(), SDL_GetWindowFullscreenMode(), SDL_MinimizeWindow(), SDL_OnWindowResized(), SDL_RestoreMousePosition(), SDL_SendsFullscreenDimensions(), SDL_SendWindowEvent(), SDL_SetDisplayModeForDisplay(), SDL_strcmp(), SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, SDL_zero, syncHint, SDL_DisplayMode::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_DestroyWindow(), SDL_OnWindowDisplayChanged(), SDL_OnWindowHidden(), SDL_OnWindowMinimized(), SDL_OnWindowRestored(), SDL_SetWindowFullscreen(), SDL_SetWindowFullscreenMode(), and SDL_UpdateFullscreenMode().
SDL_UpdateWindowGrab()
void SDL_UpdateWindowGrab (SDL_Window * window)
{
    bool keyboard_grabbed, mouse_grabbed;
    if (window->flags & SDL_WINDOW_INPUT_FOCUS) {
        if (SDL_GetMouse()->relative_mode || (window->flags & SDL_WINDOW_MOUSE_GRABBED)) {
            mouse_grabbed = true;
        } else {
            mouse_grabbed = false;
        }
        if (window->flags & SDL_WINDOW_KEYBOARD_GRABBED) {
            keyboard_grabbed = true;
        } else {
            keyboard_grabbed = false;
        }
    } else {
        mouse_grabbed = false;
        keyboard_grabbed = false;
    }
    if (mouse_grabbed || keyboard_grabbed) {
        if (_this->grabbed_window && (_this->grabbed_window != window)) {
            // stealing a grab from another window!
            _this->grabbed_window->flags &= ~(SDL_WINDOW_MOUSE_GRABBED | SDL_WINDOW_KEYBOARD_GRABBED);
            if (_this->SetWindowMouseGrab) {
                _this->SetWindowMouseGrab(_this, _this->grabbed_window, false);
            }
            if (_this->SetWindowKeyboardGrab) {
                _this->SetWindowKeyboardGrab(_this, _this->grabbed_window, false);
            }
        }
        _this->grabbed_window = window;
    } else if (_this->grabbed_window == window) {
        _this->grabbed_window = NULL; // ungrabbing input.
    }
    if (_this->SetWindowMouseGrab) {
        if (!_this->SetWindowMouseGrab(_this, window, mouse_grabbed)) {
            window->flags &= ~SDL_WINDOW_MOUSE_GRABBED;
        }
    }
    if (_this->SetWindowKeyboardGrab) {
        if (!_this->SetWindowKeyboardGrab(_this, window, keyboard_grabbed)) {
            window->flags &= ~SDL_WINDOW_KEYBOARD_GRABBED;
        }
    }
    if (_this->grabbed_window && !(_this->grabbed_window->flags & (SDL_WINDOW_MOUSE_GRABBED | SDL_WINDOW_KEYBOARD_GRABBED))) {
        _this->grabbed_window = NULL;
    }
}
References _this, NULL, SDL_GetMouse(), SDL_WINDOW_INPUT_FOCUS, SDL_WINDOW_KEYBOARD_GRABBED, and SDL_WINDOW_MOUSE_GRABBED.
Referenced by SDL_OnWindowFocusGained(), SDL_OnWindowFocusLost(), SDL_SetRelativeMouseMode(), SDL_SetWindowKeyboardGrab(), and SDL_SetWindowMouseGrab().
SDL_UpdateWindowHierarchy()
void SDL_UpdateWindowHierarchy (SDL_Window * window, SDL_Window * parent) static
{
    // Unlink the window from the existing parent.
    if (window->parent) {
        if (window->next_sibling) {
            window->next_sibling->prev_sibling = window->prev_sibling;
        }
        if (window->prev_sibling) {
            window->prev_sibling->next_sibling = window->next_sibling;
        } else {
            window->parent->first_child = window->next_sibling;
        }
        window->parent = NULL;
    }
    if (parent) {
        window->parent = parent;
        window->next_sibling = parent->first_child;
        if (parent->first_child) {
            parent->first_child->prev_sibling = window;
        }
        parent->first_child = window;
    }
}
References SDL_Window::first_child, NULL, and SDL_Window::prev_sibling.
Referenced by SDL_CreateWindowWithProperties(), SDL_DestroyWindow(), and SDL_SetWindowParent().
SDL_UpdateWindowSurface()
bool SDL_UpdateWindowSurface (SDL_Window * window)
Copy the window surface to the screen.
This is the function you use to reflect any changes to the surface on the screen.
This function is equivalent to the SDL 1.2 API SDL_Flip().
Parameters
window the window to update.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
SDL_UpdateWindowSurfaceRects
{
    SDL_Rect full_rect;
    CHECK_WINDOW_MAGIC(window, false);
    full_rect.x = 0;
    full_rect.y = 0;
    SDL_GetWindowSizeInPixels(window, &full_rect.w, &full_rect.h);
    return SDL_UpdateWindowSurfaceRects(window, &full_rect, 1);
}
References CHECK_WINDOW_MAGIC, SDL_Rect::h, SDL_GetWindowSizeInPixels(), SDL_UpdateWindowSurfaceRects(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
SDL_UpdateWindowSurfaceRects()
bool SDL_UpdateWindowSurfaceRects (SDL_Window * window, const SDL_Rect * rects, int numrects)
Copy areas of the window surface to the screen.
This is the function you use to reflect changes to portions of the surface on the screen.
This function is equivalent to the SDL 1.2 API SDL_UpdateRects().
Note that this function will update at least the rectangles specified, but this is only intended as an optimization; in practice, this might update more of the screen (or all of the screen!), depending on what method SDL uses to send pixels to the system.
Parameters
window the window to update.
rects an array of SDL_Rect structures representing areas of the surface to copy, in pixels.
numrects the number of rectangles.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
SDL_UpdateWindowSurface
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!window->surface_valid) {
        return SDL_SetError("Window surface is invalid, please call SDL_GetWindowSurface() to get a new surface");
    }
    SDL_assert(_this->checked_texture_framebuffer); // we should have done this before we had a valid surface.
    return _this->UpdateWindowFramebuffer(_this, window, rects, numrects);
}
References _this, CHECK_WINDOW_MAGIC, SDL_assert, and SDL_SetError().
Referenced by SDL_UpdateWindowSurface().
SDL_UpdateWindowTexture()
bool SDL_UpdateWindowTexture (SDL_VideoDevice * _this, SDL_Window * window, const SDL_Rect * rects, int numrects) static
{
    SDL_WindowTextureData *data;
    SDL_Rect rect;
    void *src;
    int w, h;
    SDL_GetWindowSizeInPixels(window, &w, &h);
    data = (SDL_WindowTextureData *)SDL_GetPointerProperty(SDL_GetWindowProperties(window), SDL_PROP_WINDOW_TEXTUREDATA_POINTER, NULL);
    if (!data || !data->texture) {
        return SDL_SetError("No window texture data");
    }
    // Update a single rect that contains subrects for best DMA performance
    if (SDL_GetSpanEnclosingRect(w, h, numrects, rects, &rect)) {
        src = (void *)((Uint8 *)data->pixels +
                       rect.y * data->pitch +
                       rect.x * data->bytes_per_pixel);
        if (!SDL_UpdateTexture(data->texture, &rect, src, data->pitch)) {
            return false;
        }
        if (!SDL_RenderTexture(data->renderer, data->texture, NULL, NULL)) {
            return false;
        }
        SDL_RenderPresent(data->renderer);
    }
    return true;
}
References _this, NULL, SDL_GetPointerProperty(), SDL_GetSpanEnclosingRect(), SDL_GetWindowProperties(), SDL_GetWindowSizeInPixels(), SDL_PROP_WINDOW_TEXTUREDATA_POINTER, SDL_RenderPresent(), SDL_RenderTexture(), SDL_SetError(), SDL_UpdateTexture(), SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_CreateWindowFramebuffer().
SDL_VideoInit()
bool SDL_VideoInit (const char * driver_name)
Initialize the video subsystem, optionally specifying a video driver.
This function initializes the video subsystem, setting up a connection to the window manager, etc, and determines the available display modes and pixel formats, but does not initialize a window or graphics mode.
If you use this function and you haven't used the SDL_INIT_VIDEO flag with either SDL_Init() or SDL_InitSubSystem(), you should call SDL_VideoQuit() before calling SDL_Quit().
It is safe to call this function multiple times. SDL_VideoInit() will call SDL_VideoQuit() itself if the video subsystem has already been initialized.
You can use SDL_GetNumVideoDrivers() and SDL_GetVideoDriver() to find a specific driver_name.
Parameters
driver_name the name of a video driver to initialize, or NULL for the default driver
Returns
true on success or false on failure; call SDL_GetError() for more information.
{
    SDL_VideoDevice *video;
    bool init_events = false;
    bool init_keyboard = false;
    bool init_mouse = false;
    bool init_touch = false;
    bool init_pen = false;
    int i = 0;
    // Check to make sure we don't overwrite '_this'
    if (_this) {
        SDL_VideoQuit();
    }
    SDL_InitTicks();
    // Start the event loop
    if (!SDL_InitSubSystem(SDL_INIT_EVENTS)) {
        goto pre_driver_error;
    }
    init_events = true;
    if (!SDL_InitKeyboard()) {
        goto pre_driver_error;
    }
    init_keyboard = true;
    if (!SDL_PreInitMouse()) {
        goto pre_driver_error;
    }
    init_mouse = true;
    if (!SDL_InitTouch()) {
        goto pre_driver_error;
    }
    init_touch = true;
    if (!SDL_InitPen()) {
        goto pre_driver_error;
    }
    init_pen = true;
    // Select the proper video driver
    video = NULL;
    if (!driver_name) {
        driver_name = SDL_GetHint(SDL_HINT_VIDEO_DRIVER);
    }
    if (driver_name && *driver_name != 0) {
        const char *driver_attempt = driver_name;
        while (driver_attempt && *driver_attempt != 0 && !video) {
            const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
            for (i = 0; bootstrap[i]; ++i) {
                if (!bootstrap[i]->is_preferred &&
                    (driver_attempt_len == SDL_strlen(bootstrap[i]->name)) &&
                    (SDL_strncasecmp(bootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                    video = bootstrap[i]->create();
                    if (video) {
                        break;
                    }
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
    } else {
        for (i = 0; bootstrap[i]; ++i) {
            video = bootstrap[i]->create();
            if (video) {
                break;
            }
        }
    }
    if (video) {
        SDL_DebugLogBackend("video", bootstrap[i]->name);
    } else {
        if (driver_name) {
            SDL_SetError("%s not available", driver_name);
            goto pre_driver_error;
        }
        SDL_SetError("No available video device");
        goto pre_driver_error;
    }
    /* From this point on, use SDL_VideoQuit to cleanup on error, rather than
    pre_driver_error. */
    _this = video;
    _this->name = bootstrap[i]->name;
    _this->thread = SDL_GetCurrentThreadID();
    // Set some very sane GL defaults
    _this->gl_config.driver_loaded = 0;
    _this->gl_config.dll_handle = NULL;
    SDL_GL_ResetAttributes();
    // Initialize the video subsystem
    if (!_this->VideoInit(_this)) {
        SDL_VideoQuit();
        return false;
    }
    // Make sure some displays were added
    if (_this->num_displays == 0) {
        SDL_VideoQuit();
        return SDL_SetError("The video driver did not add any displays");
    }
    SDL_AddHintCallback(SDL_HINT_VIDEO_SYNC_WINDOW_OPERATIONS, SDL_SyncHintWatcher, NULL);
    /* Disable the screen saver by default. This is a change from <= 2.0.1,
       but most things using SDL are games or media players; you wouldn't
       want a screensaver to trigger if you're playing exclusively with a
       joystick, or passively watching a movie. Things that use SDL but
       function more like a normal desktop app should explicitly reenable the
       screensaver. */
    if (!SDL_GetHintBoolean(SDL_HINT_VIDEO_ALLOW_SCREENSAVER, false)) {
        SDL_DisableScreenSaver();
    }
    SDL_PostInitMouse();
    // We're ready to go!
    return true;
pre_driver_error:
    SDL_assert(_this == NULL);
    if (init_pen) {
        SDL_QuitPen();
    }
    if (init_touch) {
        SDL_QuitTouch();
    }
    if (init_mouse) {
        SDL_QuitMouse();
    }
    if (init_keyboard) {
        SDL_QuitKeyboard();
    }
    if (init_events) {
        SDL_QuitSubSystem(SDL_INIT_EVENTS);
    }
    return false;
}
References _this, bootstrap, NULL, SDL_AddHintCallback(), SDL_assert, SDL_DebugLogBackend(), SDL_DisableScreenSaver(), SDL_GetCurrentThreadID(), SDL_GetHint(), SDL_GetHintBoolean(), SDL_GL_ResetAttributes(), SDL_HINT_VIDEO_ALLOW_SCREENSAVER, SDL_HINT_VIDEO_DRIVER, SDL_HINT_VIDEO_SYNC_WINDOW_OPERATIONS, SDL_INIT_EVENTS, SDL_InitKeyboard(), SDL_InitPen(), SDL_InitSubSystem(), SDL_InitTicks(), SDL_InitTouch(), SDL_PostInitMouse(), SDL_PreInitMouse(), SDL_QuitKeyboard(), SDL_QuitMouse(), SDL_QuitPen(), SDL_QuitSubSystem(), SDL_QuitTouch(), SDL_SetError(), SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), SDL_SyncHintWatcher(), and SDL_VideoQuit().
Referenced by SDL_InitSubSystem().
SDL_VideoQuit()
void SDL_VideoQuit (void)
Shut down the video subsystem, if initialized with SDL_VideoInit().
This function closes all windows, and restores the original video mode.
{
    int i;
    if (!_this) {
        return;
    }
    // Halt event processing before doing anything else
#if 0 // This was moved to the end to fix a memory leak
    SDL_QuitPen();
#endif
    SDL_QuitTouch();
    SDL_QuitMouse();
    SDL_QuitKeyboard();
    SDL_QuitSubSystem(SDL_INIT_EVENTS);
    SDL_EnableScreenSaver();
    // Clean up the system video
    while (_this->windows) {
        SDL_DestroyWindow(_this->windows);
    }
    _this->VideoQuit(_this);
    for (i = _this->num_displays; i--; ) {
        SDL_VideoDisplay *display = _this->displays[i];
        SDL_DelVideoDisplay(display->id, false);
    }
    SDL_assert(_this->num_displays == 0);
    SDL_free(_this->displays);
    _this->displays = NULL;
    SDL_CancelClipboardData(0);
    if (_this->primary_selection_text) {
        SDL_free(_this->primary_selection_text);
        _this->primary_selection_text = NULL;
    }
    _this->free(_this);
    _this = NULL;
    // This needs to happen after the video subsystem has removed pen data
    SDL_QuitPen();
}
References _this, NULL, SDL_assert, SDL_CancelClipboardData(), SDL_DelVideoDisplay(), SDL_DestroyWindow(), SDL_EnableScreenSaver(), SDL_free(), SDL_INIT_EVENTS, SDL_QuitKeyboard(), SDL_QuitMouse(), SDL_QuitPen(), SDL_QuitSubSystem(), and SDL_QuitTouch().
Referenced by SDL_QuitSubSystem(), and SDL_VideoInit().
SDL_Vulkan_CreateSurface()
bool SDL_Vulkan_CreateSurface (SDL_Window * window, VkInstance instance, const struct VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
Create a Vulkan rendering surface for a window.
The window must have been created with the SDL_WINDOW_VULKAN flag and instance must have been created with extensions returned by SDL_Vulkan_GetInstanceExtensions() enabled.
If allocator is NULL, Vulkan will use the system default allocator. This argument is passed directly to Vulkan and isn't used by SDL itself.
Parameters
window the window to which to attach the Vulkan surface.
instance the Vulkan instance handle.
allocator a VkAllocationCallbacks struct, which lets the app set the allocator that creates the surface. Can be NULL.
surface a pointer to a VkSurfaceKHR handle to output the newly created surface.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_Vulkan_GetInstanceExtensions
SDL_Vulkan_DestroySurface
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!(window->flags & SDL_WINDOW_VULKAN)) {
        return SDL_SetError(NOT_A_VULKAN_WINDOW);
    }
    if (!instance) {
        return SDL_InvalidParamError("instance");
    }
    if (!surface) {
        return SDL_InvalidParamError("surface");
    }
    return _this->Vulkan_CreateSurface(_this, window, instance, allocator, surface);
}
References _this, CHECK_WINDOW_MAGIC, NOT_A_VULKAN_WINDOW, SDL_InvalidParamError, SDL_SetError(), and SDL_WINDOW_VULKAN.
SDL_Vulkan_DestroySurface()
void SDL_Vulkan_DestroySurface (VkInstance instance, VkSurfaceKHR surface, const struct VkAllocationCallbacks * allocator)
Destroy the Vulkan rendering surface of a window.
This should be called before SDL_DestroyWindow, if SDL_Vulkan_CreateSurface was called after SDL_CreateWindow.
The instance must have been created with extensions returned by SDL_Vulkan_GetInstanceExtensions() enabled and surface must have been created successfully by an SDL_Vulkan_CreateSurface() call.
If allocator is NULL, Vulkan will use the system default allocator. This argument is passed directly to Vulkan and isn't used by SDL itself.
Parameters
instance the Vulkan instance handle.
surface vkSurfaceKHR handle to destroy.
allocator a VkAllocationCallbacks struct, which lets the app set the allocator that destroys the surface. Can be NULL.
Since
This function is available since SDL 3.2.0.
See also
SDL_Vulkan_GetInstanceExtensions
SDL_Vulkan_CreateSurface
{
    if (_this && instance && surface && _this->Vulkan_DestroySurface) {
        _this->Vulkan_DestroySurface(_this, instance, surface, allocator);
    }
}
References _this.
SDL_Vulkan_GetInstanceExtensions()
char const *const * SDL_Vulkan_GetInstanceExtensions (Uint32 * count)
Get the Vulkan instance extensions needed for vkCreateInstance.
This should be called after either calling SDL_Vulkan_LoadLibrary() or creating an SDL_Window with the SDL_WINDOW_VULKAN flag.
On return, the variable pointed to by count will be set to the number of elements returned, suitable for using with VkInstanceCreateInfo::enabledExtensionCount, and the returned array can be used with VkInstanceCreateInfo::ppEnabledExtensionNames, for calling Vulkan's vkCreateInstance API.
You should not free the returned array; it is owned by SDL.
Parameters
count a pointer filled in with the number of extensions returned.
Returns
an array of extension name strings on success, NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_Vulkan_CreateSurface
{
    return _this->Vulkan_GetInstanceExtensions(_this, count);
}
References _this, and count.
SDL_Vulkan_GetPresentationSupport()
bool SDL_Vulkan_GetPresentationSupport (VkInstance instance, VkPhysicalDevice physicalDevice, Uint32 queueFamilyIndex)
Query support for presentation via a given physical device and queue family.
The instance must have been created with extensions returned by SDL_Vulkan_GetInstanceExtensions() enabled.
Parameters
instance the Vulkan instance handle.
physicalDevice a valid Vulkan physical device handle.
queueFamilyIndex a valid queue family index for the given physical device.
Returns
true if supported, false if unsupported or an error occurred.
Since
This function is available since SDL 3.2.0.
See also
SDL_Vulkan_GetInstanceExtensions
{
    if (!_this) {
        SDL_UninitializedVideo();
        return false;
    }
    if (!instance) {
        SDL_InvalidParamError("instance");
        return false;
    }
    if (!physicalDevice) {
        SDL_InvalidParamError("physicalDevice");
        return false;
    }
    if (_this->Vulkan_GetPresentationSupport) {
        return _this->Vulkan_GetPresentationSupport(_this, instance, physicalDevice, queueFamilyIndex);
    }
    /* If the backend does not have this function then it does not have a
     * WSI function to query it; in other words it's not necessary to check
     * as it is always supported.
     */
    return true;
}
References _this, SDL_InvalidParamError, and SDL_UninitializedVideo().
SDL_Vulkan_GetVkGetInstanceProcAddr()
SDL_FunctionPointer SDL_Vulkan_GetVkGetInstanceProcAddr (void)
Get the address of the vkGetInstanceProcAddr function.
This should be called after either calling SDL_Vulkan_LoadLibrary() or creating an SDL_Window with the SDL_WINDOW_VULKAN flag.
The actual type of the returned function pointer is PFN_vkGetInstanceProcAddr, but that isn't available because the Vulkan headers are not included here. You should cast the return value of this function to that type, e.g.
vkGetInstanceProcAddr = (PFN_vkGetInstanceProcAddr)SDL_Vulkan_GetVkGetInstanceProcAddr();
Returns
the function pointer for vkGetInstanceProcAddr or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (!_this->vulkan_config.loader_loaded) {
        SDL_SetError("No Vulkan loader has been loaded");
        return NULL;
    }
    return (SDL_FunctionPointer)_this->vulkan_config.vkGetInstanceProcAddr;
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_Vulkan_LoadLibrary()
bool SDL_Vulkan_LoadLibrary (const char * path)
Dynamically load the Vulkan loader library.
This should be called after initializing the video driver, but before creating any Vulkan windows. If no Vulkan loader library is loaded, the default library will be loaded upon creation of the first Vulkan window.
SDL keeps a counter of how many times this function has been successfully called, so it is safe to call this function multiple times, so long as it is eventually paired with an equivalent number of calls to SDL_Vulkan_UnloadLibrary. The path argument is ignored unless there is no library currently loaded, and and the library isn't actually unloaded until there have been an equivalent number of calls to SDL_Vulkan_UnloadLibrary.
It is fairly common for Vulkan applications to link with libvulkan instead of explicitly loading it at run time. This will work with SDL provided the application links to a dynamic library and both it and SDL use the same search path.
If you specify a non-NULL path, an application should retrieve all of the Vulkan functions it uses from the dynamic library using SDL_Vulkan_GetVkGetInstanceProcAddr unless you can guarantee path points to the same vulkan loader library the application linked to.
On Apple devices, if path is NULL, SDL will attempt to find the vkGetInstanceProcAddr address within all the Mach-O images of the current process. This is because it is fairly common for Vulkan applications to link with libvulkan (and historically MoltenVK was provided as a static library). If it is not found, on macOS, SDL will attempt to load vulkan.framework/vulkan, libvulkan.1.dylib, MoltenVK.framework/MoltenVK, and libMoltenVK.dylib, in that order. On iOS, SDL will attempt to load libMoltenVK.dylib. Applications using a dynamic framework or .dylib must ensure it is included in its application bundle.
On non-Apple devices, application linking with a static libvulkan is not supported. Either do not link to the Vulkan loader or link to a dynamic library version.
Parameters
path the platform dependent Vulkan loader library name or NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_Vulkan_GetVkGetInstanceProcAddr
SDL_Vulkan_UnloadLibrary
{
    bool result;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (_this->vulkan_config.loader_loaded) {
        if (path && SDL_strcmp(path, _this->vulkan_config.loader_path) != 0) {
            return SDL_SetError("Vulkan loader library already loaded");
        }
        result = true;
    } else {
        if (!_this->Vulkan_LoadLibrary) {
            return SDL_DllNotSupported("Vulkan");
        }
        result = _this->Vulkan_LoadLibrary(_this, path);
    }
    if (result) {
        _this->vulkan_config.loader_loaded++;
    }
    return result;
}
References _this, SDL_DllNotSupported(), SDL_SetError(), SDL_strcmp(), and SDL_UninitializedVideo().
Referenced by SDL_CreateWindowWithProperties(), and SDL_RecreateWindow().
SDL_Vulkan_UnloadLibrary()
void SDL_Vulkan_UnloadLibrary (void)
Unload the Vulkan library previously loaded by SDL_Vulkan_LoadLibrary().
SDL keeps a counter of how many times this function has been called, so it is safe to call this function multiple times, so long as it is paired with an equivalent number of calls to SDL_Vulkan_LoadLibrary. The library isn't actually unloaded until there have been an equivalent number of calls to SDL_Vulkan_UnloadLibrary.
Once the library has actually been unloaded, if any Vulkan instances remain, they will likely crash the program. Clean up any existing Vulkan resources, and destroy appropriate windows, renderers and GPU devices before calling this function.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_Vulkan_LoadLibrary
{
    if (!_this) {
        SDL_UninitializedVideo();
        return;
    }
    if (_this->vulkan_config.loader_loaded > 0) {
        if (--_this->vulkan_config.loader_loaded > 0) {
            return;
        }
        if (_this->Vulkan_UnloadLibrary) {
            _this->Vulkan_UnloadLibrary(_this);
        }
    }
}
References _this, and SDL_UninitializedVideo().
Referenced by SDL_DestroyWindow(), SDL_Metal_CreateView(), and SDL_RecreateWindow().
SDL_WindowHasSurface()
bool SDL_WindowHasSurface (SDL_Window * window)
Return whether the window has a surface associated with it.
Parameters
window the window to query.
Returns
true if there is a surface associated with the window, or false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
{
    CHECK_WINDOW_MAGIC(window, false);
    return window->surface ? true : false;
}
References CHECK_WINDOW_MAGIC, and true.
Referenced by SDL_CreateRendererWithProperties().
ShouldAttemptTextureFramebuffer()
bool ShouldAttemptTextureFramebuffer (void) static
{
    const char *hint;
    bool attempt_texture_framebuffer = true;
    // The dummy driver never has GPU support, of course.
    if (_this->is_dummy) {
        return false;
    }
    // See if there's a hint override
    hint = SDL_GetHint(SDL_HINT_FRAMEBUFFER_ACCELERATION);
    if (hint && *hint) {
        if (*hint == '0' || SDL_strcasecmp(hint, "false") == 0 || SDL_strcasecmp(hint, SDL_SOFTWARE_RENDERER) == 0) {
            attempt_texture_framebuffer = false;
        } else {
            attempt_texture_framebuffer = true;
        }
    } else {
        // Check for platform specific defaults
#ifdef SDL_PLATFORM_LINUX
        // On WSL, direct X11 is faster than using OpenGL for window framebuffers, so try to detect WSL and avoid texture framebuffer.
        if ((_this->CreateWindowFramebuffer) && (SDL_strcmp(_this->name, "x11") == 0)) {
            struct stat sb;
            if ((stat("/proc/sys/fs/binfmt_misc/WSLInterop", &sb) == 0) || (stat("/run/WSL", &sb) == 0)) { // if either of these exist, we're on WSL.
                attempt_texture_framebuffer = false;
            }
        }
#endif
#if defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK) // GDI BitBlt() is way faster than Direct3D dynamic textures right now. (!!! FIXME: is this still true?)
        if (_this->CreateWindowFramebuffer && (SDL_strcmp(_this->name, "windows") == 0)) {
            attempt_texture_framebuffer = false;
        }
#endif
#ifdef SDL_PLATFORM_EMSCRIPTEN
        attempt_texture_framebuffer = false;
#endif
    }
    return attempt_texture_framebuffer;
}
References _this, SDL_GetHint(), SDL_HINT_FRAMEBUFFER_ACCELERATION, SDL_SOFTWARE_RENDERER, SDL_strcasecmp(), and SDL_strcmp().
Referenced by SDL_CreateWindowFramebuffer().
Variable Documentation
_this
SDL_VideoDevice* _this = NULL static
Referenced by Android_CreateWindow(), Android_DestroyWindow(), Android_GetClipboardText(), Android_GLES_CreateContext(), Android_GLES_LoadLibrary(), Android_GLES_MakeCurrent(), Android_GLES_SwapWindow(), Android_HasClipboardText(), Android_HasScreenKeyboardSupport(), Android_HideScreenKeyboard(), Android_IsScreenKeyboardShown(), Android_MinimizeWindow(), Android_RestoreScreenKeyboardOnResume(), Android_SetClipboardText(), Android_SetWindowFullscreen(), Android_SetWindowResizable(), Android_SetWindowTitle(), Android_ShowScreenKeyboard(), Cocoa_AcceptDragAndDrop(), Cocoa_CreateWindow(), Cocoa_FindSDLDisplayByCGDirectDisplayID(), Cocoa_FlashWindow(), Cocoa_GetClipboardData(), Cocoa_GetDisplayBounds(), Cocoa_GetDisplayForWindow(), Cocoa_GetDisplayModes(), Cocoa_GetDisplayUsableBounds(), Cocoa_GetWindowICCProfile(), Cocoa_GetWindowSizeInPixels(), Cocoa_HandleKeyEvent(), Cocoa_HandleMouseEvent(), Cocoa_HasClipboardData(), Cocoa_HideWindow(), Cocoa_InitKeyboard(), Cocoa_InitModes(), Cocoa_InitMouse(), Cocoa_InitPen(), Cocoa_MaximizeWindow(), Cocoa_MinimizeWindow(), Cocoa_PumpEvents(), Cocoa_QuitKeyboard(), Cocoa_QuitModes(), Cocoa_QuitMouse(), Cocoa_QuitPen(), Cocoa_RaiseWindow(), Cocoa_RestoreWindow(), Cocoa_SendWakeupEvent(), Cocoa_SetClipboardData(), Cocoa_SetDisplayMode(), Cocoa_SetWindowAlwaysOnTop(), Cocoa_SetWindowAspectRatio(), Cocoa_SetWindowBordered(), Cocoa_SetWindowFocusable(), Cocoa_SetWindowFullscreen(), Cocoa_SetWindowIcon(), Cocoa_SetWindowKeyboardGrab(), Cocoa_SetWindowMaximumSize(), Cocoa_SetWindowMinimumSize(), Cocoa_SetWindowModal(), Cocoa_SetWindowMouseGrab(), Cocoa_SetWindowMouseRect(), Cocoa_SetWindowOpacity(), Cocoa_SetWindowParent(), Cocoa_SetWindowPosition(), Cocoa_SetWindowResizable(), Cocoa_SetWindowSize(), Cocoa_SetWindowTitle(), Cocoa_ShowWindow(), Cocoa_StartTextInput(), Cocoa_StopTextInput(), Cocoa_SuspendScreenSaver(), Cocoa_UpdateDisplays(), Cocoa_UpdateTextInputArea(), Cocoa_UpdateWindowShape(), Cocoa_WaitEventTimeout(), createWindow(), createWindowFramebuffer(), DBUS_ApplyWindowProgress(), destroyWindow(), DUMMY_PumpEvents(), Emscripten_CreateWindowFramebuffer(), Emscripten_DestroyWindowFramebuffer(), Emscripten_UpdateWindowFramebuffer(), GDK_RegisterChangeNotifications(), GetDisplayForRect(), GetWindow(), glCreateContext(), glDeleteContext(), glGetProcAddress(), glLoadLibrary(), glMakeCurrent(), glSetSwapInterval(), glSwapWindow(), glUnloadLibrary(), HAIKU_CreateWindow(), HAIKU_CreateWindowFramebuffer(), HAIKU_DeleteDevice(), HAIKU_DestroyWindow(), HAIKU_DestroyWindowFramebuffer(), HAIKU_GetClipboardText(), HAIKU_GetDisplayBounds(), HAIKU_GetDisplayModes(), HAIKU_HasClipboardText(), HAIKU_HideWindow(), HAIKU_InitModes(), HAIKU_MaximizeWindow(), HAIKU_MinimizeWindow(), HAIKU_PumpEvents(), HAIKU_QuitModes(), HAIKU_RaiseWindow(), HAIKU_RestoreWindow(), HAIKU_SetClipboardText(), HAIKU_SetDisplayMode(), HAIKU_SetWindowBordered(), HAIKU_SetWindowFullscreen(), HAIKU_SetWindowMinimumSize(), HAIKU_SetWindowModal(), HAIKU_SetWindowMouseGrab(), HAIKU_SetWindowParent(), HAIKU_SetWindowPosition(), HAIKU_SetWindowResizable(), HAIKU_SetWindowSize(), HAIKU_SetWindowTitle(), HAIKU_ShowWindow(), HAIKU_UpdateWindowFramebuffer(), HAIKU_VideoInit(), HAIKU_VideoQuit(), hideWindow(), IsFullscreenOnly(), KMSDRM_CreateSurfaces(), KMSDRM_CreateWindow(), KMSDRM_DestroyCursorBO(), KMSDRM_DestroyWindow(), KMSDRM_FBFromBO(), KMSDRM_FBFromBO2(), KMSDRM_GetDisplayModes(), KMSDRM_GLES_CreateContext(), KMSDRM_GLES_DefaultProfileConfig(), KMSDRM_GLES_LoadLibrary(), KMSDRM_GLES_MakeCurrent(), KMSDRM_GLES_SetSwapInterval(), KMSDRM_GLES_SwapWindow(), KMSDRM_GLES_UnloadLibrary(), KMSDRM_HideWindow(), KMSDRM_InitMouse(), KMSDRM_MaximizeWindow(), KMSDRM_MinimizeWindow(), KMSDRM_PumpEvents(), KMSDRM_QuitMouse(), KMSDRM_RaiseWindow(), KMSDRM_RestoreWindow(), KMSDRM_SetDisplayMode(), KMSDRM_SetWindowFullscreen(), KMSDRM_SetWindowPosition(), KMSDRM_SetWindowSize(), KMSDRM_SetWindowTitle(), KMSDRM_ShowWindow(), KMSDRM_VideoInit(), KMSDRM_VideoQuit(), KMSDRM_WaitPageflip(), N3DS_HasScreenKeyboardSupport(), N3DS_PollTouch(), N3DS_PumpEvents(), N3DS_StartTextInput(), N3DS_StopTextInput(), OFFSCREEN_CreateWindow(), OFFSCREEN_DestroyWindow(), OFFSCREEN_PumpEvents(), OFFSCREEN_SetWindowSize(), PrepareDragAndDropSupport(), PSP_CreateWindow(), PSP_DestroyWindow(), PSP_EventInit(), PSP_EventQuit(), PSP_GetDisplayModes(), PSP_GL_CreateContext(), PSP_GL_DestroyContext(), PSP_GL_GetProcAddress(), PSP_GL_GetSwapInterval(), PSP_GL_LoadLibrary(), PSP_GL_MakeCurrent(), PSP_GL_SetSwapInterval(), PSP_GL_SwapBuffers(), PSP_GL_SwapWindow(), PSP_GL_UnloadLibrary(), PSP_HasScreenKeyboardSupport(), PSP_HideScreenKeyboard(), PSP_HideWindow(), PSP_InitOSKeymap(), PSP_IsScreenKeyboardShown(), PSP_MaximizeWindow(), PSP_MinimizeWindow(), PSP_PumpEvents(), PSP_RaiseWindow(), PSP_RestoreWindow(), PSP_SetDisplayMode(), PSP_SetWindowPosition(), PSP_SetWindowSize(), PSP_SetWindowTitle(), PSP_ShowScreenKeyboard(), PSP_ShowWindow(), PSP_VideoInit(), PSP_VideoQuit(), pumpEvents(), RISCOS_CreateWindow(), RISCOS_CreateWindowFramebuffer(), RISCOS_DestroyWindow(), RISCOS_DestroyWindowFramebuffer(), RISCOS_GetDisplayModes(), RISCOS_InitEvents(), RISCOS_InitModes(), RISCOS_InitMouse(), RISCOS_PumpEvents(), RISCOS_QuitEvents(), RISCOS_SetDisplayMode(), RISCOS_UpdateWindowFramebuffer(), RPI_CreateWindow(), RPI_DestroyWindow(), RPI_GetDisplayModes(), RPI_GLES_CreateContext(), RPI_GLES_DestroyContext(), RPI_GLES_GetProcAddress(), RPI_GLES_GetSwapInterval(), RPI_GLES_LoadLibrary(), RPI_GLES_MakeCurrent(), RPI_GLES_SetSwapInterval(), RPI_GLES_SwapWindow(), RPI_GLES_UnloadLibrary(), RPI_HideWindow(), RPI_InitMouse(), RPI_MaximizeWindow(), RPI_MinimizeWindow(), RPI_PumpEvents(), RPI_QuitMouse(), RPI_RaiseWindow(), RPI_RestoreWindow(), RPI_SetDisplayMode(), RPI_SetWindowPosition(), RPI_SetWindowSize(), RPI_SetWindowTitle(), RPI_ShowWindow(), RPI_VideoInit(), RPI_VideoQuit(), SDL_AddVideoDisplay(), SDL_CancelClipboardData(), SDL_CheckWindowDisplayChanged(), SDL_CheckWindowDisplayScaleChanged(), SDL_ClearComposition(), SDL_ContextNotSupported(), SDL_CreateWindowFramebuffer(), SDL_CreateWindowTexture(), SDL_CreateWindowWithProperties(), SDL_DefaultGraphicsBackends(), SDL_DelVideoDisplay(), SDL_DestroyWindow(), SDL_DestroyWindowSurface(), SDL_DestroyWindowTexture(), SDL_DisableMouseWarpOnFullscreenTransitions(), SDL_DisableScreenSaver(), SDL_DllNotSupported(), SDL_DriverSendsHDRChanges(), SDL_DUMMY_CreateWindowFramebuffer(), SDL_DUMMY_DestroyWindowFramebuffer(), SDL_DUMMY_UpdateWindowFramebuffer(), SDL_EGL_GetCurrentConfig(), SDL_EGL_GetCurrentDisplay(), SDL_EGL_GetProcAddress(), SDL_EGL_GetWindowSurface(), SDL_EGL_SetAttributeCallbacks(), SDL_EnableScreenSaver(), SDL_find_active_window(), SDL_FlashWindow(), SDL_FreeClipboardMimeTypes(), SDL_GetClipboardData(), SDL_GetClipboardMimeTypes(), SDL_GetClipboardText(), SDL_GetCurrentVideoDriver(), SDL_GetDisplayBounds(), SDL_GetDisplayForWindowPosition(), SDL_GetDisplayIndex(), SDL_GetDisplays(), SDL_GetDisplayUsableBounds(), SDL_GetGrabbedWindow(), SDL_GetInternalClipboardData(), SDL_GetPrimaryDisplay(), SDL_GetPrimarySelectionText(), SDL_GetSystemTheme(), SDL_GetTextMimeTypes(), SDL_GetVideoDevice(), SDL_GetVideoDisplay(), SDL_GetWindowBordersSize(), SDL_GetWindowFromID(), SDL_GetWindowICCProfile(), SDL_GetWindowKeyboardGrab(), SDL_GetWindowMouseGrab(), SDL_GetWindows(), SDL_GetWindowSizeInPixels(), SDL_GetWindowSurfaceVSync(), SDL_GetWindowTextureVSync(), SDL_GL_CreateContext(), SDL_GL_DestroyContext(), SDL_GL_GetAttribute(), SDL_GL_GetCurrentContext(), SDL_GL_GetCurrentWindow(), SDL_GL_GetProcAddress(), SDL_GL_GetSwapInterval(), SDL_GL_LoadLibrary(), SDL_GL_MakeCurrent(), SDL_GL_ResetAttributes(), SDL_GL_SetAttribute(), SDL_GL_SetSwapInterval(), SDL_GL_SwapWindow(), SDL_GL_UnloadLibrary(), SDL_GPUSelectBackend(), SDL_HasClipboardData(), SDL_HasClipboardText(), SDL_HasInternalClipboardData(), SDL_HasPrimarySelectionText(), SDL_HasScreenKeyboardSupport(), SDL_HasWindows(), SDL_HideWindow(), SDL_MaximizeWindow(), SDL_Metal_CreateView(), SDL_Metal_DestroyView(), SDL_Metal_GetLayer(), SDL_MinimizeWindow(), SDL_ModeSwitchingEmulated(), SDL_N3DS_CreateWindowFramebuffer(), SDL_N3DS_DestroyWindowFramebuffer(), SDL_N3DS_UpdateWindowFramebuffer(), SDL_OFFSCREEN_CreateWindowFramebuffer(), SDL_OFFSCREEN_DestroyWindowFramebuffer(), SDL_OFFSCREEN_UpdateWindowFramebuffer(), SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationWillEnterBackground(), SDL_OnDisplayAdded(), SDL_OnVideoThread(), SDL_OnWindowEnter(), SDL_OnWindowResized(), SDL_PumpEventsInternal(), SDL_RaiseWindow(), SDL_RecreateWindow(), SDL_RestoreWindow(), SDL_SaveClipboardMimeTypes(), SDL_ScreenKeyboardShown(), SDL_ScreenSaverEnabled(), SDL_SendsDisplayChanges(), SDL_SendsFullscreenDimensions(), SDL_SendWakeupEvent(), SDL_SetClipboardData(), SDL_SetClipboardText(), SDL_SetDisplayContentScale(), SDL_SetDisplayHDRProperties(), SDL_SetDisplayModeForDisplay(), SDL_SetPrimarySelectionText(), SDL_SetSystemTheme(), SDL_SetTextInputArea(), SDL_SetWindowAlwaysOnTop(), SDL_SetWindowAspectRatio(), SDL_SetWindowBordered(), SDL_SetWindowFocusable(), SDL_SetWindowHitTest(), SDL_SetWindowIcon(), SDL_SetWindowMaximumSize(), SDL_SetWindowMinimumSize(), SDL_SetWindowModal(), SDL_SetWindowMouseRect(), SDL_SetWindowOpacity(), SDL_SetWindowParent(), SDL_SetWindowPosition(), SDL_SetWindowProgressState(), SDL_SetWindowProgressValue(), SDL_SetWindowResizable(), SDL_SetWindowShape(), SDL_SetWindowSize(), SDL_SetWindowSurfaceVSync(), SDL_SetWindowTextureVSync(), SDL_SetWindowTitle(), SDL_ShouldMinimizeOnFocusLoss(), SDL_ShowMessageBox(), SDL_ShowWindow(), SDL_ShowWindowSystemMenu(), SDL_StartTextInputWithProperties(), SDL_StopTextInput(), SDL_SyncWindow(), SDL_ToggleDragAndDropSupport(), SDL_UpdateDesktopBounds(), SDL_UpdateFullscreenDisplayModes(), SDL_UpdateFullscreenMode(), SDL_UpdateWindowGrab(), SDL_UpdateWindowSurfaceRects(), SDL_UpdateWindowTexture(), SDL_VideoInit(), SDL_VideoQuit(), SDL_Vulkan_CreateSurface(), SDL_Vulkan_DestroySurface(), SDL_Vulkan_GetInstanceExtensions(), SDL_Vulkan_GetPresentationSupport(), SDL_Vulkan_GetVkGetInstanceProcAddr(), SDL_Vulkan_LoadLibrary(), SDL_Vulkan_UnloadLibrary(), SDL_WaitEventTimeout_Device(), SDL_WaitEventTimeoutNS(), setWindowSize(), ShouldAttemptTextureFramebuffer(), showWindow(), UIKit_CreateWindow(), UIKit_DestroyWindow(), UIKit_GetClipboardText(), UIKit_GetDisplayModes(), UIKit_GetDisplayUsableBounds(), UIKit_GetWindowSizeInPixels(), UIKit_HasClipboardText(), UIKit_HideWindow(), UIKit_InitClipboard(), UIKit_InitModes(), UIKit_InitPen(), UIKit_PumpEvents(), UIKit_QuitClipboard(), UIKit_QuitModes(), UIKit_QuitPen(), UIKit_RaiseWindow(), UIKit_SetClipboardText(), UIKit_SetDisplayMode(), UIKit_SetWindowBordered(), UIKit_SetWindowFullscreen(), UIKit_SetWindowTitle(), UIKit_ShowWindow(), UIKit_SuspendScreenSaver(), UIKit_UpdatePointerLock(), updateWindowFramebuffer(), videoInit(), videoQuit(), VITA_CreateWindow(), VITA_CreateWindowFramebuffer(), VITA_DestroyWindow(), VITA_DestroyWindowFramebuffer(), VITA_HasScreenKeyboardSupport(), VITA_HideScreenKeyboard(), VITA_HideWindow(), VITA_IsScreenKeyboardShown(), VITA_MaximizeWindow(), VITA_MinimizeWindow(), VITA_PumpEvents(), VITA_RaiseWindow(), VITA_RestoreWindow(), VITA_SetWindowGrab(), VITA_SetWindowPosition(), VITA_SetWindowSize(), VITA_SetWindowTitle(), VITA_ShowScreenKeyboard(), VITA_ShowWindow(), VITA_UpdateWindowFramebuffer(), VITA_VideoInit(), VITA_VideoQuit(), VIVANTE_CreateWindow(), VIVANTE_DestroyWindow(), VIVANTE_GetDisplayModes(), VIVANTE_HideWindow(), VIVANTE_PumpEvents(), VIVANTE_SetDisplayMode(), VIVANTE_SetWindowPosition(), VIVANTE_SetWindowSize(), VIVANTE_SetWindowTitle(), VIVANTE_ShowWindow(), VIVANTE_VideoInit(), VIVANTE_VideoQuit(), Wayland_CreateWindow(), Wayland_data_source_create(), Wayland_DestroyWindow(), Wayland_FlashWindow(), Wayland_GetClipboardData(), Wayland_GetDisplayForWindow(), Wayland_GetPrimarySelectionText(), Wayland_GetTextMimeTypes(), Wayland_GetWindowContentScale(), Wayland_GetWindowICCProfile(), Wayland_GetWindowSizeInPixels(), Wayland_GLES_CreateContext(), Wayland_GLES_DestroyContext(), Wayland_GLES_GetEGLSurface(), Wayland_GLES_GetSwapInterval(), Wayland_GLES_LoadLibrary(), Wayland_GLES_MakeCurrent(), Wayland_GLES_SetSwapInterval(), Wayland_GLES_SwapWindow(), Wayland_HasClipboardData(), Wayland_HasPrimarySelectionText(), Wayland_HasScreenKeyboardSupport(), Wayland_HideWindow(), Wayland_InitKeyboard(), Wayland_MaximizeWindow(), Wayland_MinimizeWindow(), Wayland_primary_selection_source_create(), Wayland_PumpEvents(), Wayland_QuitKeyboard(), Wayland_RaiseWindow(), Wayland_RestoreWindow(), Wayland_SendWakeupEvent(), Wayland_SetClipboardData(), Wayland_SetPrimarySelectionText(), Wayland_SetWindowBordered(), Wayland_SetWindowFocusable(), Wayland_SetWindowFullscreen(), Wayland_SetWindowIcon(), Wayland_SetWindowKeyboardGrab(), Wayland_SetWindowMaximumSize(), Wayland_SetWindowMinimumSize(), Wayland_SetWindowModal(), Wayland_SetWindowMouseGrab(), Wayland_SetWindowMouseRect(), Wayland_SetWindowOpacity(), Wayland_SetWindowParent(), Wayland_SetWindowPosition(), Wayland_SetWindowResizable(), Wayland_SetWindowSize(), Wayland_SetWindowTitle(), Wayland_ShowWindow(), Wayland_StartTextInput(), Wayland_StopTextInput(), Wayland_SuspendScreenSaver(), Wayland_SyncWindow(), Wayland_UpdateTextInputArea(), Wayland_VideoReconnect(), Wayland_WaitEventTimeout(), WIN_ApplyWindowProgress(), WIN_CheckKeyboardAndMouseHotplug(), WIN_ClearComposition(), WIN_CreateWindow(), WIN_CreateWindowFramebuffer(), WIN_DestroyWindow(), WIN_DestroyWindowFramebuffer(), WIN_FlashWindow(), WIN_GetClipboardData(), WIN_GetDisplayBounds(), WIN_GetDisplayModes(), WIN_GetDisplayUsableBounds(), WIN_GetWindowBordersSize(), WIN_GetWindowICCProfile(), WIN_GetWindowSizeInPixels(), WIN_HasClipboardData(), WIN_HideWindow(), WIN_InitGameInput(), WIN_InitKeyboard(), WIN_InitModes(), WIN_InitMouse(), WIN_IsPerMonitorV2DPIAware(), WIN_MaximizeWindow(), WIN_MinimizeWindow(), WIN_OnWindowEnter(), WIN_PollRawInput(), WIN_PumpEvents(), WIN_QuitGameInput(), WIN_QuitKeyboard(), WIN_QuitModes(), WIN_QuitMouse(), WIN_RaiseWindow(), WIN_RefreshDisplays(), WIN_RefreshRawInputEnabled(), WIN_RestoreWindow(), WIN_SendWakeupEvent(), WIN_SetClipboardData(), WIN_SetDisplayMode(), WIN_SetRawKeyboardEnabled(), WIN_SetRawMouseEnabled(), WIN_SetWindowAlwaysOnTop(), WIN_SetWindowBordered(), WIN_SetWindowFocusable(), WIN_SetWindowFullscreen(), WIN_SetWindowIcon(), WIN_SetWindowKeyboardGrab(), WIN_SetWindowModal(), WIN_SetWindowMouseGrab(), WIN_SetWindowMouseRect(), WIN_SetWindowOpacity(), WIN_SetWindowParent(), WIN_SetWindowPosition(), WIN_SetWindowResizable(), WIN_SetWindowSize(), WIN_SetWindowTitle(), WIN_ShowWindow(), WIN_StartTextInput(), WIN_StopTextInput(), WIN_UpdateGameInput(), WIN_UpdateGameInputEnabled(), WIN_UpdateIMECandidates(), WIN_UpdateTextInputArea(), WIN_UpdateWindowFramebuffer(), WIN_UpdateWindowShape(), WIN_WaitEventTimeout(), X11_CreateWindow(), X11_CreateWindowFramebuffer(), X11_DestroyWindow(), X11_DestroyWindowFramebuffer(), X11_FindWindow(), X11_FlashWindow(), X11_GetClipboardData(), X11_GetDisplayBounds(), X11_GetDisplayModes(), X11_GetDisplayUsableBounds(), X11_GetNetWMState(), X11_GetPrimarySelectionText(), X11_GetTextMimeTypes(), X11_GetWindowBordersSize(), X11_GetWindowICCProfile(), X11_GetWindowTitle(), X11_GetXsettingsIntKey(), X11_HandleButtonPress(), X11_HandleButtonRelease(), X11_HandleKeyEvent(), X11_HandleXinput2Event(), X11_HandleXsettings(), X11_HasClipboardData(), X11_HasPrimarySelectionText(), X11_HasScreenKeyboardSupport(), X11_HideScreenKeyboard(), X11_HideWindow(), X11_InitKeyboard(), X11_InitModes(), X11_InitMouse(), X11_InitPen(), X11_InitTouch(), X11_InitXinput2(), X11_InitXinput2Multitouch(), X11_InitXsettings(), X11_InitXTest(), X11_IsScreenKeyboardShown(), X11_KeyCodeToSym(), X11_MaximizeWindow(), X11_MinimizeWindow(), X11_ProcessHitTest(), X11_PumpEvents(), X11_QuitClipboard(), X11_QuitKeyboard(), X11_QuitModes(), X11_QuitMouse(), X11_QuitPen(), X11_QuitTouch(), X11_QuitXsettings(), X11_RaiseWindow(), X11_ReconcileKeyboardState(), X11_ResetTouch(), X11_RestoreWindow(), X11_SendWakeupEvent(), X11_SetClipboardData(), X11_SetDisplayMode(), X11_SetNetWMState(), X11_SetPrimarySelectionText(), X11_SetWindowAlwaysOnTop(), X11_SetWindowAspectRatio(), X11_SetWindowBordered(), X11_SetWindowFocusable(), X11_SetWindowFullscreen(), X11_SetWindowIcon(), X11_SetWindowKeyboardGrab(), X11_SetWindowMaximumSize(), X11_SetWindowMinimumSize(), X11_SetWindowModal(), X11_SetWindowMouseGrab(), X11_SetWindowOpacity(), X11_SetWindowParent(), X11_SetWindowPosition(), X11_SetWindowResizable(), X11_SetWindowSize(), X11_SetWindowTitle(), X11_ShowScreenKeyboard(), X11_ShowWindow(), X11_StartTextInput(), X11_StopTextInput(), X11_SuspendScreenSaver(), X11_SyncWindow(), X11_TriggerHitTestAction(), X11_UpdateKeymap(), X11_UpdateTextInputArea(), X11_UpdateWindowFramebuffer(), X11_UpdateWindowShape(), X11_WaitEventTimeout(), X11_WarpMouseXTest(), X11_Xinput2GrabTouch(), X11_Xinput2SelectMouseAndKeyboard(), X11_Xinput2SelectTouch(), X11_Xinput2UngrabTouch(), and X11_Xinput2UpdateDevices().
bootstrap
VideoBootStrap* bootstrap[] static
{
#ifdef SDL_VIDEO_DRIVER_PRIVATE
    &PRIVATE_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_COCOA
    &COCOA_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_X11
#ifdef SDL_VIDEO_DRIVER_WAYLAND
    &Wayland_preferred_bootstrap,
#endif
    &X11_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_WAYLAND
    &Wayland_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_VIVANTE
    &VIVANTE_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_WINDOWS
    &WINDOWS_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_HAIKU
    &HAIKU_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_UIKIT
    &UIKIT_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_ANDROID
    &Android_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_PS2
    &PS2_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_PSP
    &PSP_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_VITA
    &VITA_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_N3DS
    &N3DS_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_NGAGE
    &NGAGE_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_KMSDRM
    &KMSDRM_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_RISCOS
    &RISCOS_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_RPI
    &RPI_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_EMSCRIPTEN
    &Emscripten_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_QNX
    &QNX_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_OFFSCREEN
    &OFFSCREEN_bootstrap,
#endif
#ifdef SDL_VIDEO_DRIVER_DUMMY
    &DUMMY_bootstrap,
#ifdef SDL_INPUT_LINUXEV
    &DUMMY_evdev_bootstrap,
#endif
#endif
#ifdef SDL_VIDEO_DRIVER_OPENVR
    &OPENVR_bootstrap,
#endif
    NULL
};
deduped_bootstrap
const VideoBootStrap* deduped_bootstrap[SDL_arraysize(bootstrap) - 1] static
flag
SDL_WindowFlags flag
Referenced by glDepthMask(), glEdgeFlag(), glEdgeFlagv(), glPopName(), SDL_PROC(), and SDL_SendPenButton().
invert_value
bool invert_value
Referenced by SDL_GetWindowFlagProperties().
property_name
const char* property_name
Referenced by SDL_GetWindowFlagProperties().
SDL_messagebox_count
SDL_AtomicInt SDL_messagebox_count static
Referenced by SDL_GetMessageBoxCount(), and SDL_ShowMessageBox().
[struct]
struct { ... } SDL_WindowFlagProperties[]
Initial value:
= {
    { SDL_PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN,      SDL_WINDOW_ALWAYS_ON_TOP,       false },
    { SDL_PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN,         SDL_WINDOW_BORDERLESS,          false },
    { SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN,          SDL_WINDOW_NOT_FOCUSABLE,       true },
    { SDL_PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN,         SDL_WINDOW_FULLSCREEN,          false },
    { SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN,             SDL_WINDOW_HIDDEN,              false },
    { SDL_PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN, SDL_WINDOW_HIGH_PIXEL_DENSITY,  false },
    { SDL_PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN,          SDL_WINDOW_MAXIMIZED,           false },
    { SDL_PROP_WINDOW_CREATE_MENU_BOOLEAN,               SDL_WINDOW_POPUP_MENU,          false },
    { SDL_PROP_WINDOW_CREATE_METAL_BOOLEAN,              SDL_WINDOW_METAL,               false },
    { SDL_PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN,          SDL_WINDOW_MINIMIZED,           false },
    { SDL_PROP_WINDOW_CREATE_MODAL_BOOLEAN,              SDL_WINDOW_MODAL,               false },
    { SDL_PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN,      SDL_WINDOW_MOUSE_GRABBED,       false },
    { SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN,             SDL_WINDOW_OPENGL,              false },
    { SDL_PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN,          SDL_WINDOW_RESIZABLE,           false },
    { SDL_PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN,        SDL_WINDOW_TRANSPARENT,         false },
    { SDL_PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN,            SDL_WINDOW_TOOLTIP,             false },
    { SDL_PROP_WINDOW_CREATE_UTILITY_BOOLEAN,            SDL_WINDOW_UTILITY,             false },
    { SDL_PROP_WINDOW_CREATE_VULKAN_BOOLEAN,             SDL_WINDOW_VULKAN,              false }
}
Referenced by SDL_GetWindowFlagProperties().
syncHint
bool syncHint static
Referenced by SDL_SyncHintWatcher(), SDL_SyncIfRequired(), and SDL_UpdateFullscreenMode().