SDL3: SDL-main/src/hidapi/libusb/hidapi_thread_pthread.h File Reference
hidapi_thread_pthread.h File Reference
#include <pthread.h>
Data Structures
struct hidapi_thread_state
Macros
#define hidapi_thread_cleanup_pop pthread_cleanup_pop
#define hidapi_thread_cleanup_push pthread_cleanup_push
#define HIDAPI_THREAD_TIMED_OUT ETIMEDOUT
Typedefs
typedef struct timespec hidapi_timespec
Functions
static void hidapi_thread_addtime (hidapi_timespec *ts, int milliseconds)
static void hidapi_thread_barrier_wait (hidapi_thread_state *state)
static void hidapi_thread_cond_broadcast (hidapi_thread_state *state)
static void hidapi_thread_cond_signal (hidapi_thread_state *state)
static int hidapi_thread_cond_timedwait (hidapi_thread_state *state, hidapi_timespec *ts)
static void hidapi_thread_cond_wait (hidapi_thread_state *state)
static void hidapi_thread_create (hidapi_thread_state *state, void *(*func)(void *), void *func_arg)
static void hidapi_thread_gettime (hidapi_timespec *ts)
static void hidapi_thread_join (hidapi_thread_state *state)
static void hidapi_thread_mutex_lock (hidapi_thread_state *state)
static void hidapi_thread_mutex_unlock (hidapi_thread_state *state)
static void hidapi_thread_state_destroy (hidapi_thread_state *state)
static void hidapi_thread_state_init (hidapi_thread_state *state)
Macro Definition Documentation
hidapi_thread_cleanup_pop
#define hidapi_thread_cleanup_pop pthread_cleanup_pop
Referenced by PLATFORM_hid_read_timeout().
hidapi_thread_cleanup_push
#define hidapi_thread_cleanup_push pthread_cleanup_push
Referenced by PLATFORM_hid_read_timeout().
HIDAPI_THREAD_TIMED_OUT
#define HIDAPI_THREAD_TIMED_OUT ETIMEDOUT
Referenced by hidapi_thread_cond_timedwait(), and PLATFORM_hid_read_timeout().
Typedef Documentation
hidapi_timespec
typedef struct timespec hidapi_timespec
Function Documentation
hidapi_thread_addtime()
void hidapi_thread_addtime (hidapi_timespec * ts, int milliseconds) static
{
    ts->tv_sec += milliseconds / 1000;
    ts->tv_nsec += (milliseconds % 1000) * 1000000;
    if (ts->tv_nsec >= 1000000000L) {
        ts->tv_sec++;
        ts->tv_nsec -= 1000000000L;
    }
}
Referenced by PLATFORM_hid_read_timeout().
hidapi_thread_barrier_wait()
void hidapi_thread_barrier_wait (hidapi_thread_state * state) static
{
    pthread_barrier_wait(&state->barrier);
}
References hidapi_thread_state::barrier, and pthread_barrier_wait().
Referenced by hidapi_initialize_device(), and read_thread().
hidapi_thread_cond_broadcast()
void hidapi_thread_cond_broadcast (hidapi_thread_state * state) static
{
    pthread_cond_broadcast(&state->condition);
}
References hidapi_thread_state::condition.
Referenced by read_thread().
hidapi_thread_cond_signal()
void hidapi_thread_cond_signal (hidapi_thread_state * state) static
{
    pthread_cond_signal(&state->condition);
}
References hidapi_thread_state::condition.
Referenced by read_callback().
hidapi_thread_cond_timedwait()
int hidapi_thread_cond_timedwait (hidapi_thread_state * state, hidapi_timespec * ts) static
{
    return pthread_cond_timedwait(&state->condition, &state->mutex, ts);
}
References hidapi_thread_state::condition, and hidapi_thread_state::mutex.
Referenced by PLATFORM_hid_read_timeout().
hidapi_thread_cond_wait()
void hidapi_thread_cond_wait (hidapi_thread_state * state) static
{
    pthread_cond_wait(&state->condition, &state->mutex);
}
References hidapi_thread_state::condition, and hidapi_thread_state::mutex.
Referenced by PLATFORM_hid_read_timeout().
hidapi_thread_create()
void hidapi_thread_create (hidapi_thread_state * state, void *(* func)(void *), void * func_arg) static
{
    pthread_create(&state->thread, NULL, func, func_arg);
}
References NULL, and hidapi_thread_state::thread.
Referenced by hidapi_initialize_device().
hidapi_thread_gettime()
void hidapi_thread_gettime (hidapi_timespec * ts) static
{
    clock_gettime(CLOCK_REALTIME, ts);
}
Referenced by PLATFORM_hid_read_timeout().
hidapi_thread_join()
void hidapi_thread_join (hidapi_thread_state * state) static
{
    pthread_join(state->thread, NULL);
}
References NULL, and hidapi_thread_state::thread.
Referenced by PLATFORM_hid_close().
hidapi_thread_mutex_lock()
void hidapi_thread_mutex_lock (hidapi_thread_state * state) static
{
    pthread_mutex_lock(&state->mutex);
}
References hidapi_thread_state::mutex.
Referenced by PLATFORM_hid_close(), PLATFORM_hid_read_timeout(), read_callback(), and read_thread().
hidapi_thread_mutex_unlock()
void hidapi_thread_mutex_unlock (hidapi_thread_state * state) static
{
    pthread_mutex_unlock(&state->mutex);
}
References hidapi_thread_state::mutex.
Referenced by cleanup_mutex(), PLATFORM_hid_close(), PLATFORM_hid_read_timeout(), read_callback(), and read_thread().
hidapi_thread_state_destroy()
void hidapi_thread_state_destroy (hidapi_thread_state * state) static
{
    pthread_barrier_destroy(&state->barrier);
    pthread_cond_destroy(&state->condition);
    pthread_mutex_destroy(&state->mutex);
}
References hidapi_thread_state::barrier, hidapi_thread_state::condition, hidapi_thread_state::mutex, and pthread_barrier_destroy().
Referenced by free_hid_device().
hidapi_thread_state_init()
void hidapi_thread_state_init (hidapi_thread_state * state) static
{
    pthread_mutex_init(&state->mutex, NULL);
    pthread_cond_init(&state->condition, NULL);
    pthread_barrier_init(&state->barrier, NULL, 2);
}
References hidapi_thread_state::barrier, hidapi_thread_state::condition, hidapi_thread_state::mutex, NULL, and pthread_barrier_init().
Referenced by new_hid_device().