SDL3: SDL-main/src/stdlib/SDL_random.c File Reference
SDL_random.c File Reference
#include "SDL_internal.h"
Functions
Sint32 SDL_rand (Sint32 n)
Uint32 SDL_rand_bits (void)
Uint32 SDL_rand_bits_r (Uint64 *state)
Sint32 SDL_rand_r (Uint64 *state, Sint32 n)
float SDL_randf (void)
float SDL_randf_r (Uint64 *state)
void SDL_srand (Uint64 seed)
Variables
static bool SDL_rand_initialized = false
static Uint64 SDL_rand_state
Function Documentation
SDL_rand()
Sint32 SDL_rand (Sint32 n)
Generate a pseudo-random number less than n for positive n
The method used is faster and of better quality than rand() % n. Odds are roughly 99.9% even for n = 1 million. Evenness is better for smaller n, and much worse as n gets bigger.
Example: to simulate a d6 use SDL_rand(6) + 1 The +1 converts 0..5 to 1..6
If you want to generate a pseudo-random number in the full range of Sint32, you should use: (Sint32)SDL_rand_bits()
If you want reproducible output, be sure to initialize with SDL_srand() first.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
n the number of possible outcomes. n must be positive.
Returns
a random value in the range of [0 .. n-1].
Thread Safety
All calls should be made from a single thread
Since
This function is available since SDL 3.2.0.
See also
SDL_srand
SDL_randf
{
    if (!SDL_rand_initialized) {
        SDL_srand(0);
    }
    return SDL_rand_r(&SDL_rand_state, n);
}
References SDL_rand_initialized, SDL_rand_r(), SDL_rand_state, and SDL_srand().
Referenced by SDL_vasprintf().
SDL_rand_bits()
Uint32 SDL_rand_bits (void)
Generate 32 pseudo-random bits.
You likely want to use SDL_rand() to get a psuedo-random number instead.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Returns
a random value in the range of [0-SDL_MAX_UINT32].
Thread Safety
All calls should be made from a single thread
Since
This function is available since SDL 3.2.0.
See also
SDL_rand
SDL_randf
SDL_srand
{
    if (!SDL_rand_initialized) {
        SDL_srand(0);
    }
    return SDL_rand_bits_r(&SDL_rand_state);
}
References SDL_rand_bits_r(), SDL_rand_initialized, SDL_rand_state, and SDL_srand().
Referenced by SDL_vasprintf().
SDL_rand_bits_r()
Uint32 SDL_rand_bits_r (Uint64 * state)
Generate 32 pseudo-random bits.
You likely want to use SDL_rand_r() to get a psuedo-random number instead.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
state a pointer to the current random number state, this may not be NULL.
Returns
a random value in the range of [0-SDL_MAX_UINT32].
Thread Safety
This function is thread-safe, as long as the state pointer isn't shared between threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_rand_r
SDL_randf_r
{
    if (!state) {
        return 0;
    }
    // The C and A parameters of this LCG have been chosen based on hundreds
    // of core-hours of testing with PractRand and TestU01's Crush.
    // Using a 32-bit A improves performance on 32-bit architectures.
    // C can be any odd number, but < 256 generates smaller code on ARM32
    // These values perform as well as a full 64-bit implementation against
    // Crush and PractRand. Plus, their worst-case performance is better
    // than common 64-bit constants when tested against PractRand using seeds
    // with only a single bit set.
    // We tested all 32-bit and 33-bit A with all C < 256 from a v2 of:
    // Steele GL, Vigna S. Computationally easy, spectrally good multipliers
    // for congruential pseudorandom number generators.
    // Softw Pract Exper. 2022;52(2):443-458. doi: 10.1002/spe.3030
    // https://arxiv.org/abs/2001.05304v2
    *state = *state * 0xff1cd035ul + 0x05;
    // Only return top 32 bits because they have a longer period
    return (Uint32)(*state >> 32);
}
Referenced by SDL_rand_bits(), SDL_rand_r(), SDL_randf_r(), and SDL_vasprintf().
SDL_rand_r()
Sint32 SDL_rand_r (Uint64 * state, Sint32 n)
Generate a pseudo-random number less than n for positive n
The method used is faster and of better quality than rand() % n. Odds are roughly 99.9% even for n = 1 million. Evenness is better for smaller n, and much worse as n gets bigger.
Example: to simulate a d6 use SDL_rand_r(state, 6) + 1 The +1 converts 0..5 to 1..6
If you want to generate a pseudo-random number in the full range of Sint32, you should use: (Sint32)SDL_rand_bits_r(state)
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
state a pointer to the current random number state, this may not be NULL.
n the number of possible outcomes. n must be positive.
Returns
a random value in the range of [0 .. n-1].
Thread Safety
This function is thread-safe, as long as the state pointer isn't shared between threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_rand
SDL_rand_bits_r
SDL_randf_r
{
    // Algorithm: get 32 bits from SDL_rand_bits() and treat it as a 0.32 bit
    // fixed point number. Multiply by the 31.0 bit n to get a 31.32 bit
    // result. Shift right by 32 to get the 31 bit integer that we want.
    if (n < 0) {
        // The algorithm looks like it works for numbers < 0 but it has an
        // infinitesimal chance of returning a value out of range.
        // Returning -SDL_rand(abs(n)) blows up at INT_MIN instead.
        // It's easier to just say no.
        return 0;
    }
    // On 32-bit arch, the compiler will optimize to a single 32-bit multiply
    Uint64 val = (Uint64)SDL_rand_bits_r(state) * n;
    return (Sint32)(val >> 32);
}
References SDL_rand_bits_r().
Referenced by SDL_rand(), and SDL_vasprintf().
SDL_randf()
float SDL_randf (void)
Generate a uniform pseudo-random floating point number less than 1.0
If you want reproducible output, be sure to initialize with SDL_srand() first.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Returns
a random value in the range of [0.0, 1.0).
Thread Safety
All calls should be made from a single thread
Since
This function is available since SDL 3.2.0.
See also
SDL_srand
SDL_rand
{
    if (!SDL_rand_initialized) {
        SDL_srand(0);
    }
    return SDL_randf_r(&SDL_rand_state);
}
References SDL_rand_initialized, SDL_rand_state, SDL_randf_r(), and SDL_srand().
Referenced by SDL_vasprintf().
SDL_randf_r()
float SDL_randf_r (Uint64 * state)
Generate a uniform pseudo-random floating point number less than 1.0
If you want reproducible output, be sure to initialize with SDL_srand() first.
There are no guarantees as to the quality of the random sequence produced, and this should not be used for security (cryptography, passwords) or where money is on the line (loot-boxes, casinos). There are many random number libraries available with different characteristics and you should pick one of those to meet any serious needs.
Parameters
state a pointer to the current random number state, this may not be NULL.
Returns
a random value in the range of [0.0, 1.0).
Thread Safety
This function is thread-safe, as long as the state pointer isn't shared between threads.
Since
This function is available since SDL 3.2.0.
See also
SDL_rand_bits_r
SDL_rand_r
SDL_randf
{
    // Note: its using 24 bits because float has 23 bits significand + 1 implicit bit
    return (SDL_rand_bits_r(state) >> (32 - 24)) * 0x1p-24f;
}
References SDL_rand_bits_r().
Referenced by SDL_randf(), and SDL_vasprintf().
SDL_srand()
void SDL_srand (Uint64 seed)
Seeds the pseudo-random number generator.
Reusing the seed number will cause SDL_rand() to repeat the same stream of 'random' numbers.
Parameters
seed the value to use as a random number seed, or 0 to use SDL_GetPerformanceCounter().
Thread Safety
This should be called on the same thread that calls SDL_rand()
Since
This function is available since SDL 3.2.0.
See also
SDL_rand
SDL_rand_bits
SDL_randf
{
    if (!seed) {
        seed = SDL_GetPerformanceCounter();
    }
    SDL_rand_state = seed;
    SDL_rand_initialized = true;
}
References SDL_GetPerformanceCounter(), SDL_rand_initialized, and SDL_rand_state.
Referenced by SDL_rand(), SDL_rand_bits(), SDL_randf(), and SDL_vasprintf().
Variable Documentation
SDL_rand_initialized
bool SDL_rand_initialized = false static
Referenced by SDL_rand(), SDL_rand_bits(), SDL_randf(), and SDL_srand().
SDL_rand_state
Uint64 SDL_rand_state static
Referenced by SDL_rand(), SDL_rand_bits(), SDL_randf(), and SDL_srand().