SDL3: SDL-main/src/stdlib/SDL_iconv.c File Reference
SDL_iconv.c File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_iconv_data_t
Macros
#define ENCODING_UCS2NATIVE ENCODING_UCS2BE
#define ENCODING_UCS4NATIVE ENCODING_UCS4BE
#define ENCODING_UTF16NATIVE ENCODING_UTF16BE
#define ENCODING_UTF32NATIVE ENCODING_UTF32BE
#define UNICODE_BOM 0xFEFF
#define UNKNOWN_ASCII '?'
#define UNKNOWN_UNICODE 0xFFFD
Enumerations
enum {
ENCODING_UNKNOWN , ENCODING_ASCII , ENCODING_LATIN1 , ENCODING_UTF8 ,
ENCODING_UTF16 , ENCODING_UTF16BE , ENCODING_UTF16LE , ENCODING_UTF32 ,
ENCODING_UTF32BE , ENCODING_UTF32LE , ENCODING_UCS2BE , ENCODING_UCS2LE ,
ENCODING_UCS4BE , ENCODING_UCS4LE
}
Functions
static const char * getlocale (char *buffer, size_t bufsize)
size_t SDL_iconv (SDL_iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft)
int SDL_iconv_close (SDL_iconv_t cd)
SDL_iconv_t SDL_iconv_open (const char *tocode, const char *fromcode)
char * SDL_iconv_string (const char *tocode, const char *fromcode, const char *inbuf, size_t inbytesleft)
Variables
struct {
int format
const char * name
} encodings []
Macro Definition Documentation
ENCODING_UCS2NATIVE
#define ENCODING_UCS2NATIVE ENCODING_UCS2BE
ENCODING_UCS4NATIVE
#define ENCODING_UCS4NATIVE ENCODING_UCS4BE
ENCODING_UTF16NATIVE
#define ENCODING_UTF16NATIVE ENCODING_UTF16BE
Referenced by SDL_iconv().
ENCODING_UTF32NATIVE
#define ENCODING_UTF32NATIVE ENCODING_UTF32BE
Referenced by SDL_iconv().
UNICODE_BOM
#define UNICODE_BOM 0xFEFF
Referenced by SDL_iconv().
UNKNOWN_ASCII
#define UNKNOWN_ASCII '?'
Referenced by SDL_iconv().
UNKNOWN_UNICODE
#define UNKNOWN_UNICODE 0xFFFD
Referenced by SDL_iconv().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ENCODING_UNKNOWN
ENCODING_ASCII
ENCODING_LATIN1
ENCODING_UTF8
ENCODING_UTF16
ENCODING_UTF16BE
ENCODING_UTF16LE
ENCODING_UTF32
ENCODING_UTF32BE
ENCODING_UTF32LE
ENCODING_UCS2BE
ENCODING_UCS2LE
ENCODING_UCS4BE
ENCODING_UCS4LE
{
    ENCODING_UNKNOWN,
    ENCODING_ASCII,
    ENCODING_LATIN1,
    ENCODING_UTF8,
    ENCODING_UTF16, // Needs byte order marker
    ENCODING_UTF16BE,
    ENCODING_UTF16LE,
    ENCODING_UTF32, // Needs byte order marker
    ENCODING_UTF32BE,
    ENCODING_UTF32LE,
    ENCODING_UCS2BE,
    ENCODING_UCS2LE,
    ENCODING_UCS4BE,
    ENCODING_UCS4LE,
};
Function Documentation
getlocale()
const char * getlocale (char * buffer, size_t bufsize) static
{
    const char *lang;
    char *ptr;
    lang = SDL_getenv("LC_ALL");
    if (!lang) {
        lang = SDL_getenv("LC_CTYPE");
    }
    if (!lang) {
        lang = SDL_getenv("LC_MESSAGES");
    }
    if (!lang) {
        lang = SDL_getenv("LANG");
    }
    if (!lang || !*lang || SDL_strcmp(lang, "C") == 0) {
        lang = "ASCII";
    }
    // We need to trim down strings like "en_US.UTF-8@blah" to "UTF-8"
    ptr = SDL_strchr(lang, '.');
    if (ptr) {
        lang = ptr + 1;
    }
    SDL_strlcpy(buffer, lang, bufsize);
    ptr = SDL_strchr(buffer, '@');
    if (ptr) {
        *ptr = '\0'; // chop end of string.
    }
    return buffer;
}
References SDL_getenv(), SDL_strchr(), SDL_strcmp(), and SDL_strlcpy().
Referenced by SDL_iconv_open().
SDL_iconv()
size_t SDL_iconv (SDL_iconv_t cd, const char ** inbuf, size_t * inbytesleft, char ** outbuf, size_t * outbytesleft)
This function converts text between encodings, reading from and writing to a buffer.
It returns the number of succesful conversions on success. On error, SDL_ICONV_E2BIG is returned when the output buffer is too small, or SDL_ICONV_EILSEQ is returned when an invalid input sequence is encountered, or SDL_ICONV_EINVAL is returned when an incomplete input sequence is encountered.
On exit:
inbuf will point to the beginning of the next multibyte sequence. On error, this is the location of the problematic input sequence. On success, this is the end of the input sequence.
inbytesleft will be set to the number of bytes left to convert, which will be 0 on success.
outbuf will point to the location where to store the next output byte.
outbytesleft will be set to the number of bytes left in the output buffer.
Parameters
cd The character set conversion context, created in SDL_iconv_open().
inbuf Address of variable that points to the first character of the input sequence.
inbytesleft The number of bytes in the input buffer.
outbuf Address of variable that points to the output buffer.
outbytesleft The number of bytes in the output buffer.
Returns
the number of conversions on success, or a negative error code.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv_open
SDL_iconv_close
SDL_iconv_string
{
    // For simplicity, we'll convert everything to and from UCS-4
    const char *src;
    char *dst;
    size_t srclen, dstlen;
    Uint32 ch = 0;
    size_t total;
    if ((size_t)cd == SDL_ICONV_ERROR) {
        return SDL_ICONV_ERROR;
    }
    if (!inbuf || !*inbuf) {
        // Reset the context
        return 0;
    }
    if (!outbuf || !*outbuf || !outbytesleft || !*outbytesleft) {
        return SDL_ICONV_E2BIG;
    }
    src = *inbuf;
    srclen = (inbytesleft ? *inbytesleft : 0);
    dst = *outbuf;
    dstlen = *outbytesleft;
    switch (cd->src_fmt) {
    case ENCODING_UTF16:
        // Scan for a byte order marker
        {
            Uint8 *p = (Uint8 *)src;
            size_t n = srclen / 2;
            while (n) {
                if (p[0] == 0xFF && p[1] == 0xFE) {
                    cd->src_fmt = ENCODING_UTF16BE;
                    break;
                } else if (p[0] == 0xFE && p[1] == 0xFF) {
                    cd->src_fmt = ENCODING_UTF16LE;
                    break;
                }
                p += 2;
                --n;
            }
            if (n == 0) {
                // We can't tell, default to host order
                cd->src_fmt = ENCODING_UTF16NATIVE;
            }
        }
        break;
    case ENCODING_UTF32:
        // Scan for a byte order marker
        {
            Uint8 *p = (Uint8 *)src;
            size_t n = srclen / 4;
            while (n) {
                if (p[0] == 0xFF && p[1] == 0xFE &&
                    p[2] == 0x00 && p[3] == 0x00) {
                    cd->src_fmt = ENCODING_UTF32BE;
                    break;
                } else if (p[0] == 0x00 && p[1] == 0x00 &&
                           p[2] == 0xFE && p[3] == 0xFF) {
                    cd->src_fmt = ENCODING_UTF32LE;
                    break;
                }
                p += 4;
                --n;
            }
            if (n == 0) {
                // We can't tell, default to host order
                cd->src_fmt = ENCODING_UTF32NATIVE;
            }
        }
        break;
    }
    switch (cd->dst_fmt) {
    case ENCODING_UTF16:
        // Default to host order, need to add byte order marker
        if (dstlen < 2) {
            return SDL_ICONV_E2BIG;
        }
        *(Uint16 *)dst = UNICODE_BOM;
        dst += 2;
        dstlen -= 2;
        cd->dst_fmt = ENCODING_UTF16NATIVE;
        break;
    case ENCODING_UTF32:
        // Default to host order, need to add byte order marker
        if (dstlen < 4) {
            return SDL_ICONV_E2BIG;
        }
        *(Uint32 *)dst = UNICODE_BOM;
        dst += 4;
        dstlen -= 4;
        cd->dst_fmt = ENCODING_UTF32NATIVE;
        break;
    }
    total = 0;
    while (srclen > 0) {
        // Decode a character
        switch (cd->src_fmt) {
        case ENCODING_ASCII:
        {
            Uint8 *p = (Uint8 *)src;
            ch = (Uint32)(p[0] & 0x7F);
            ++src;
            --srclen;
        } break;
        case ENCODING_LATIN1:
        {
            Uint8 *p = (Uint8 *)src;
            ch = (Uint32)p[0];
            ++src;
            --srclen;
        } break;
        case ENCODING_UTF8: // RFC 3629
        {
            Uint8 *p = (Uint8 *)src;
            size_t left = 0;
            bool overlong = false;
            if (p[0] >= 0xF0) {
                if ((p[0] & 0xF8) != 0xF0) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    if (p[0] == 0xF0 && srclen > 1 && (p[1] & 0xF0) == 0x80) {
                        overlong = true;
                    }
                    ch = (Uint32)(p[0] & 0x07);
                    left = 3;
                }
            } else if (p[0] >= 0xE0) {
                if ((p[0] & 0xF0) != 0xE0) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    if (p[0] == 0xE0 && srclen > 1 && (p[1] & 0xE0) == 0x80) {
                        overlong = true;
                    }
                    ch = (Uint32)(p[0] & 0x0F);
                    left = 2;
                }
            } else if (p[0] >= 0xC0) {
                if ((p[0] & 0xE0) != 0xC0) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    if ((p[0] & 0xDE) == 0xC0) {
                        overlong = true;
                    }
                    ch = (Uint32)(p[0] & 0x1F);
                    left = 1;
                }
            } else {
                if (p[0] & 0x80) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                } else {
                    ch = (Uint32)p[0];
                }
            }
            ++src;
            --srclen;
            if (srclen < left) {
                return SDL_ICONV_EINVAL;
            }
            while (left--) {
                ++p;
                if ((p[0] & 0xC0) != 0x80) {
                    /* Skip illegal sequences
                       return SDL_ICONV_EILSEQ;
                     */
                    ch = UNKNOWN_UNICODE;
                    break;
                }
                ch <<= 6;
                ch |= (p[0] & 0x3F);
                ++src;
                --srclen;
            }
            if (overlong) {
                /* Potential security risk
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
            }
            if ((ch >= 0xD800 && ch <= 0xDFFF) ||
                (ch == 0xFFFE || ch == 0xFFFF) || ch > 0x10FFFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
            }
        } break;
        case ENCODING_UTF16BE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)src;
            Uint16 W1, W2;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            W1 = ((Uint16)p[0] << 8) | (Uint16)p[1];
            src += 2;
            srclen -= 2;
            if (W1 < 0xD800 || W1 > 0xDFFF) {
                ch = (Uint32)W1;
                break;
            }
            if (W1 > 0xDBFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            p = (Uint8 *)src;
            W2 = ((Uint16)p[0] << 8) | (Uint16)p[1];
            src += 2;
            srclen -= 2;
            if (W2 < 0xDC00 || W2 > 0xDFFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            ch = (((Uint32)(W1 & 0x3FF) << 10) |
                  (Uint32)(W2 & 0x3FF)) +
                 0x10000;
        } break;
        case ENCODING_UTF16LE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)src;
            Uint16 W1, W2;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            W1 = ((Uint16)p[1] << 8) | (Uint16)p[0];
            src += 2;
            srclen -= 2;
            if (W1 < 0xD800 || W1 > 0xDFFF) {
                ch = (Uint32)W1;
                break;
            }
            if (W1 > 0xDBFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            p = (Uint8 *)src;
            W2 = ((Uint16)p[1] << 8) | (Uint16)p[0];
            src += 2;
            srclen -= 2;
            if (W2 < 0xDC00 || W2 > 0xDFFF) {
                /* Skip illegal sequences
                   return SDL_ICONV_EILSEQ;
                 */
                ch = UNKNOWN_UNICODE;
                break;
            }
            ch = (((Uint32)(W1 & 0x3FF) << 10) |
                  (Uint32)(W2 & 0x3FF)) +
                 0x10000;
        } break;
        case ENCODING_UCS2LE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[1] << 8) | (Uint32)p[0];
            src += 2;
            srclen -= 2;
        } break;
        case ENCODING_UCS2BE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 2) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[0] << 8) | (Uint32)p[1];
            src += 2;
            srclen -= 2;
        } break;
        case ENCODING_UCS4BE:
        case ENCODING_UTF32BE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 4) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[0] << 24) |
                 ((Uint32)p[1] << 16) |
                 ((Uint32)p[2] << 8) | (Uint32)p[3];
            src += 4;
            srclen -= 4;
        } break;
        case ENCODING_UCS4LE:
        case ENCODING_UTF32LE:
        {
            Uint8 *p = (Uint8 *)src;
            if (srclen < 4) {
                return SDL_ICONV_EINVAL;
            }
            ch = ((Uint32)p[3] << 24) |
                 ((Uint32)p[2] << 16) |
                 ((Uint32)p[1] << 8) | (Uint32)p[0];
            src += 4;
            srclen -= 4;
        } break;
        }
        // Encode a character
        switch (cd->dst_fmt) {
        case ENCODING_ASCII:
        {
            Uint8 *p = (Uint8 *)dst;
            if (dstlen < 1) {
                return SDL_ICONV_E2BIG;
            }
            if (ch > 0x7F) {
                *p = UNKNOWN_ASCII;
            } else {
                *p = (Uint8)ch;
            }
            ++dst;
            --dstlen;
        } break;
        case ENCODING_LATIN1:
        {
            Uint8 *p = (Uint8 *)dst;
            if (dstlen < 1) {
                return SDL_ICONV_E2BIG;
            }
            if (ch > 0xFF) {
                *p = UNKNOWN_ASCII;
            } else {
                *p = (Uint8)ch;
            }
            ++dst;
            --dstlen;
        } break;
        case ENCODING_UTF8: // RFC 3629
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (ch <= 0x7F) {
                if (dstlen < 1) {
                    return SDL_ICONV_E2BIG;
                }
                *p = (Uint8)ch;
                ++dst;
                --dstlen;
            } else if (ch <= 0x7FF) {
                if (dstlen < 2) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = 0xC0 | (Uint8)((ch >> 6) & 0x1F);
                p[1] = 0x80 | (Uint8)(ch & 0x3F);
                dst += 2;
                dstlen -= 2;
            } else if (ch <= 0xFFFF) {
                if (dstlen < 3) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = 0xE0 | (Uint8)((ch >> 12) & 0x0F);
                p[1] = 0x80 | (Uint8)((ch >> 6) & 0x3F);
                p[2] = 0x80 | (Uint8)(ch & 0x3F);
                dst += 3;
                dstlen -= 3;
            } else {
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = 0xF0 | (Uint8)((ch >> 18) & 0x07);
                p[1] = 0x80 | (Uint8)((ch >> 12) & 0x3F);
                p[2] = 0x80 | (Uint8)((ch >> 6) & 0x3F);
                p[3] = 0x80 | (Uint8)(ch & 0x3F);
                dst += 4;
                dstlen -= 4;
            }
        } break;
        case ENCODING_UTF16BE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (ch < 0x10000) {
                if (dstlen < 2) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = (Uint8)(ch >> 8);
                p[1] = (Uint8)ch;
                dst += 2;
                dstlen -= 2;
            } else {
                Uint16 W1, W2;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                ch = ch - 0x10000;
                W1 = 0xD800 | (Uint16)((ch >> 10) & 0x3FF);
                W2 = 0xDC00 | (Uint16)(ch & 0x3FF);
                p[0] = (Uint8)(W1 >> 8);
                p[1] = (Uint8)W1;
                p[2] = (Uint8)(W2 >> 8);
                p[3] = (Uint8)W2;
                dst += 4;
                dstlen -= 4;
            }
        } break;
        case ENCODING_UTF16LE: // RFC 2781
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (ch < 0x10000) {
                if (dstlen < 2) {
                    return SDL_ICONV_E2BIG;
                }
                p[1] = (Uint8)(ch >> 8);
                p[0] = (Uint8)ch;
                dst += 2;
                dstlen -= 2;
            } else {
                Uint16 W1, W2;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                ch = ch - 0x10000;
                W1 = 0xD800 | (Uint16)((ch >> 10) & 0x3FF);
                W2 = 0xDC00 | (Uint16)(ch & 0x3FF);
                p[1] = (Uint8)(W1 >> 8);
                p[0] = (Uint8)W1;
                p[3] = (Uint8)(W2 >> 8);
                p[2] = (Uint8)W2;
                dst += 4;
                dstlen -= 4;
            }
        } break;
        case ENCODING_UCS2BE:
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0xFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (dstlen < 2) {
                return SDL_ICONV_E2BIG;
            }
            p[0] = (Uint8)(ch >> 8);
            p[1] = (Uint8)ch;
            dst += 2;
            dstlen -= 2;
        } break;
        case ENCODING_UCS2LE:
        {
            Uint8 *p = (Uint8 *)dst;
            if (ch > 0xFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            if (dstlen < 2) {
                return SDL_ICONV_E2BIG;
            }
            p[1] = (Uint8)(ch >> 8);
            p[0] = (Uint8)ch;
            dst += 2;
            dstlen -= 2;
        } break;
        case ENCODING_UTF32BE:
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            SDL_FALLTHROUGH;
        case ENCODING_UCS4BE:
            if (ch > 0x7FFFFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            {
                Uint8 *p = (Uint8 *)dst;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                p[0] = (Uint8)(ch >> 24);
                p[1] = (Uint8)(ch >> 16);
                p[2] = (Uint8)(ch >> 8);
                p[3] = (Uint8)ch;
                dst += 4;
                dstlen -= 4;
            }
            break;
        case ENCODING_UTF32LE:
            if (ch > 0x10FFFF) {
                ch = UNKNOWN_UNICODE;
            }
            SDL_FALLTHROUGH;
        case ENCODING_UCS4LE:
            if (ch > 0x7FFFFFFF) {
                ch = UNKNOWN_UNICODE;
            }
            {
                Uint8 *p = (Uint8 *)dst;
                if (dstlen < 4) {
                    return SDL_ICONV_E2BIG;
                }
                p[3] = (Uint8)(ch >> 24);
                p[2] = (Uint8)(ch >> 16);
                p[1] = (Uint8)(ch >> 8);
                p[0] = (Uint8)ch;
                dst += 4;
                dstlen -= 4;
            }
            break;
        }
        // Update state
        *inbuf = src;
        *inbytesleft = srclen;
        *outbuf = dst;
        *outbytesleft = dstlen;
        ++total;
    }
    return total;
}
References SDL_iconv_data_t::dst_fmt, ENCODING_ASCII, ENCODING_LATIN1, ENCODING_UCS2BE, ENCODING_UCS2LE, ENCODING_UCS4BE, ENCODING_UCS4LE, ENCODING_UTF16, ENCODING_UTF16BE, ENCODING_UTF16LE, ENCODING_UTF16NATIVE, ENCODING_UTF32, ENCODING_UTF32BE, ENCODING_UTF32LE, ENCODING_UTF32NATIVE, ENCODING_UTF8, left, SDL_FALLTHROUGH, SDL_ICONV_E2BIG, SDL_ICONV_EINVAL, SDL_ICONV_ERROR, SDL_iconv_data_t::src_fmt, UNICODE_BOM, UNKNOWN_ASCII, and UNKNOWN_UNICODE.
Referenced by SDL_iconv_string().
SDL_iconv_close()
int SDL_iconv_close (SDL_iconv_t cd)
This function frees a context used for character set conversion.
Parameters
cd The character set conversion handle.
Returns
0 on success, or -1 on failure.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv
SDL_iconv_open
SDL_iconv_string
{
    if (cd == (SDL_iconv_t)-1) {
        return -1;
    }
    SDL_free(cd);
    return 0;
}
References SDL_free().
Referenced by SDL_iconv_string().
SDL_iconv_open()
SDL_iconv_t SDL_iconv_open (const char * tocode, const char * fromcode)
This function allocates a context for the specified character set conversion.
Parameters
tocode The target character encoding, must not be NULL.
fromcode The source character encoding, must not be NULL.
Returns
a handle that must be freed with SDL_iconv_close, or SDL_ICONV_ERROR on failure.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv
SDL_iconv_close
SDL_iconv_string
{
    int src_fmt = ENCODING_UNKNOWN;
    int dst_fmt = ENCODING_UNKNOWN;
    int i;
    char fromcode_buffer[64];
    char tocode_buffer[64];
    if (!fromcode || !*fromcode) {
        fromcode = getlocale(fromcode_buffer, sizeof(fromcode_buffer));
    }
    if (!tocode || !*tocode) {
        tocode = getlocale(tocode_buffer, sizeof(tocode_buffer));
    }
    for (i = 0; i < SDL_arraysize(encodings); ++i) {
        if (SDL_strcasecmp(fromcode, encodings[i].name) == 0) {
            src_fmt = encodings[i].format;
            if (dst_fmt != ENCODING_UNKNOWN) {
                break;
            }
        }
        if (SDL_strcasecmp(tocode, encodings[i].name) == 0) {
            dst_fmt = encodings[i].format;
            if (src_fmt != ENCODING_UNKNOWN) {
                break;
            }
        }
    }
    if (src_fmt != ENCODING_UNKNOWN && dst_fmt != ENCODING_UNKNOWN) {
        SDL_iconv_t cd = (SDL_iconv_t)SDL_malloc(sizeof(*cd));
        if (cd) {
            cd->src_fmt = src_fmt;
            cd->dst_fmt = dst_fmt;
            return cd;
        }
    }
    return (SDL_iconv_t)-1;
}
References SDL_iconv_data_t::dst_fmt, ENCODING_UNKNOWN, encodings, getlocale(), SDL_arraysize, SDL_malloc(), SDL_strcasecmp(), and SDL_iconv_data_t::src_fmt.
Referenced by SDL_iconv_string().
SDL_iconv_string()
char * SDL_iconv_string (const char * tocode, const char * fromcode, const char * inbuf, size_t inbytesleft)
Helper function to convert a string's encoding in one call.
This function converts a buffer or string between encodings in one pass.
The string does not need to be NULL-terminated; this function operates on the number of bytes specified in inbytesleft whether there is a NULL character anywhere in the buffer.
The returned string is owned by the caller, and should be passed to SDL_free when no longer needed.
Parameters
tocode the character encoding of the output string. Examples are "UTF-8", "UCS-4", etc.
fromcode the character encoding of data in inbuf.
inbuf the string to convert to a different encoding.
inbytesleft the size of the input string in bytes.
Returns
a new string, converted to the new encoding, or NULL on error.
Since
This function is available since SDL 3.2.0.
See also
SDL_iconv_open
SDL_iconv_close
SDL_iconv
{
    SDL_iconv_t cd;
    char *string;
    size_t stringsize;
    char *outbuf;
    size_t outbytesleft;
    size_t retCode = 0;
    if (!tocode || !*tocode) {
        tocode = "UTF-8";
    }
    if (!fromcode || !*fromcode) {
        fromcode = "UTF-8";
    }
    cd = SDL_iconv_open(tocode, fromcode);
    if (cd == (SDL_iconv_t)-1) {
        return NULL;
    }
    stringsize = inbytesleft;
    string = (char *)SDL_malloc(stringsize + sizeof(Uint32));
    if (!string) {
        SDL_iconv_close(cd);
        return NULL;
    }
    outbuf = string;
    outbytesleft = stringsize;
    SDL_memset(outbuf, 0, sizeof(Uint32));
    while (inbytesleft > 0) {
        const size_t oldinbytesleft = inbytesleft;
        retCode = SDL_iconv(cd, &inbuf, &inbytesleft, &outbuf, &outbytesleft);
        switch (retCode) {
        case SDL_ICONV_E2BIG:
        {
            const ptrdiff_t diff = (ptrdiff_t) (outbuf - string);
            char *oldstring = string;
            stringsize *= 2;
            string = (char *)SDL_realloc(string, stringsize + sizeof(Uint32));
            if (!string) {
                SDL_free(oldstring);
                SDL_iconv_close(cd);
                return NULL;
            }
            outbuf = string + diff;
            outbytesleft = stringsize - diff;
            SDL_memset(outbuf, 0, sizeof(Uint32));
            continue;
        }
        case SDL_ICONV_EILSEQ:
            // Try skipping some input data - not perfect, but...
            ++inbuf;
            --inbytesleft;
            break;
        case SDL_ICONV_EINVAL:
        case SDL_ICONV_ERROR:
            // We can't continue...
            inbytesleft = 0;
            break;
        }
        // Avoid infinite loops when nothing gets converted
        if (oldinbytesleft == inbytesleft) {
            break;
        }
    }
    SDL_memset(outbuf, 0, sizeof(Uint32));
    SDL_iconv_close(cd);
    return string;
}
References NULL, SDL_free(), SDL_iconv(), SDL_iconv_close(), SDL_ICONV_E2BIG, SDL_ICONV_EILSEQ, SDL_ICONV_EINVAL, SDL_ICONV_ERROR, SDL_iconv_open(), SDL_malloc(), SDL_memset, and SDL_realloc().
Referenced by SDL_PrintStringW(), and SDL_vswprintf().
Variable Documentation
[struct]
struct { ... } encodings[]
Referenced by SDL_iconv_open().
format
int format
name
const char* name