SDL3: SDL-main/src/libm/math_libm.h File Reference
math_libm.h File Reference
#include "SDL_internal.h"
Functions
double SDL_uclibc_atan (double x)
double SDL_uclibc_atan2 (double y, double x)
double SDL_uclibc_copysign (double x, double y)
double SDL_uclibc_cos (double x)
double SDL_uclibc_exp (double x)
double SDL_uclibc_fabs (double x)
double SDL_uclibc_floor (double x)
double SDL_uclibc_fmod (double x, double y)
int SDL_uclibc_isinf (double x)
int SDL_uclibc_isinff (float x)
int SDL_uclibc_isnan (double x)
int SDL_uclibc_isnanf (float x)
double SDL_uclibc_log (double x)
double SDL_uclibc_log10 (double x)
double SDL_uclibc_modf (double x, double *y)
double SDL_uclibc_pow (double x, double y)
double SDL_uclibc_scalbn (double x, int n)
double SDL_uclibc_sin (double x)
double SDL_uclibc_sqrt (double x)
double SDL_uclibc_tan (double x)
Function Documentation
SDL_uclibc_atan()
double SDL_uclibc_atan (double x) extern
{
    double w,s1,s2,z;
    int32_t ix,hx,id;
    GET_HIGH_WORD(hx,x);
    ix = hx&0x7fffffff;
    if(ix>=0x44100000) {    /* if |x| >= 2^66 */
        u_int32_t low;
        GET_LOW_WORD(low,x);
        if(ix>0x7ff00000||
        (ix==0x7ff00000&&(low!=0)))
        return x+x;       /* NaN */
        if(hx>0) return  atanhi[3]+atanlo[3];
        else     return -atanhi[3]-atanlo[3];
    } if (ix < 0x3fdc0000) {    /* |x| < 0.4375 */
        if (ix < 0x3e200000) {  /* |x| < 2^-29 */
        if(huge+x>one) return x;   /* raise inexact */
        }
        id = -1;
    } else {
    x = fabs(x);
    if (ix < 0x3ff30000) {      /* |x| < 1.1875 */
        if (ix < 0x3fe60000) {  /* 7/16 <=|x|<11/16 */
        id = 0; x = (2.0*x-one)/(2.0+x);
        } else {            /* 11/16<=|x|< 19/16 */
        id = 1; x  = (x-one)/(x+one);
        }
    } else {
        if (ix < 0x40038000) {  /* |x| < 2.4375 */
        id = 2; x  = (x-1.5)/(one+1.5*x);
        } else {            /* 2.4375 <= |x| < 2^66 */
        id = 3; x  = -1.0/x;
        }
    }}
    /* end of argument reduction */
    z = x*x;
    w = z*z;
    /* break sum from i=0 to 10 aT[i]z**(i+1) into odd and even poly */
    s1 = z*(aT[0]+w*(aT[2]+w*(aT[4]+w*(aT[6]+w*(aT[8]+w*aT[10])))));
    s2 = w*(aT[1]+w*(aT[3]+w*(aT[5]+w*(aT[7]+w*aT[9]))));
    if (id<0) return x - x*(s1+s2);
    else {
        z = atanhi[id] - ((x*(s1+s2) - atanlo[id]) - x);
        return (hx<0)? -z:z;
    }
}
References aT, atanhi, atanlo, fabs, GET_HIGH_WORD, GET_LOW_WORD, huge, and one.
Referenced by SDL_atan().
SDL_uclibc_atan2()
double SDL_uclibc_atan2 (double y, double x) extern
{
    double z;
    int32_t k,m,hx,hy,ix,iy;
    u_int32_t lx,ly;
    EXTRACT_WORDS(hx,lx,x);
    ix = hx&0x7fffffff;
    EXTRACT_WORDS(hy,ly,y);
    iy = hy&0x7fffffff;
    if(((ix|((lx|-(int32_t)lx)>>31))>0x7ff00000)||
       ((iy|((ly|-(int32_t)ly)>>31))>0x7ff00000))   /* x or y is NaN */
       return x+y;
    if(((hx-0x3ff00000)|lx)==0) return atan(y);   /* x=1.0 */
    m = ((hy>>31)&1)|((hx>>30)&2);  /* 2*sign(x)+sign(y) */
    /* when y = 0 */
    if((iy|ly)==0) {
        switch(m) {
        case 0:
        case 1: return y;  /* atan(+-0,+anything)=+-0 */
        case 2: return  pi+tiny;/* atan(+0,-anything) = pi */
        case 3: return -pi-tiny;/* atan(-0,-anything) =-pi */
        }
    }
    /* when x = 0 */
    if((ix|lx)==0) return (hy<0)?  -pi_o_2-tiny: pi_o_2+tiny;
    /* when x is INF */
    if(ix==0x7ff00000) {
        if(iy==0x7ff00000) {
        switch(m) {
            case 0: return  pi_o_4+tiny;/* atan(+INF,+INF) */
            case 1: return -pi_o_4-tiny;/* atan(-INF,+INF) */
            case 2: return  3.0*pi_o_4+tiny;/*atan(+INF,-INF)*/
            case 3: return -3.0*pi_o_4-tiny;/*atan(-INF,-INF)*/
        }
        } else {
        switch(m) {
            case 0: return  zero  ; /* atan(+...,+INF) */
            case 1: return -zero  ; /* atan(-...,+INF) */
            case 2: return  pi+tiny  ;    /* atan(+...,-INF) */
            case 3: return -pi-tiny  ;    /* atan(-...,-INF) */
        }
        }
    }
    /* when y is INF */
    if(iy==0x7ff00000) return (hy<0)? -pi_o_2-tiny: pi_o_2+tiny;
    /* compute y/x */
    k = (iy-ix)>>20;
    if(k > 60) z=pi_o_2+0.5*pi_lo;   /* |y/x| >  2**60 */
    else if(hx<0&&k<-60) z=0.0;     /* |y|/x < -2**60 */
    else z=atan(fabs(y/x));       /* safe to do y/x */
    switch (m) {
        case 0: return       z  ;   /* atan(+,+) */
        case 1: {
                  u_int32_t zh;
              GET_HIGH_WORD(zh,z);
              SET_HIGH_WORD(z,zh ^ 0x80000000);
            }
            return       z  ;   /* atan(-,+) */
        case 2: return  pi-(z-pi_lo);/* atan(+,-) */
        default: /* case 3 */
                return  (z-pi_lo)-pi;/* atan(-,-) */
    }
}
SDL_uclibc_copysign()
double SDL_uclibc_copysign (double x, double y) extern
{
    u_int32_t hx,hy;
    GET_HIGH_WORD(hx,x);
    GET_HIGH_WORD(hy,y);
    SET_HIGH_WORD(x,(hx&0x7fffffff)|(hy&0x80000000));
        return x;
}
References GET_HIGH_WORD, and SET_HIGH_WORD.
Referenced by SDL_copysign().
SDL_uclibc_cos()
double SDL_uclibc_cos (double x) extern
{
    double y[2],z=0.0;
    int32_t n, ix;
    /* High word of x. */
    GET_HIGH_WORD(ix,x);
    /* |x| ~< pi/4 */
    ix &= 0x7fffffff;
    if(ix <= 0x3fe921fb) return __kernel_cos(x,z);
    /* cos(Inf or NaN) is NaN */
    else if (ix>=0x7ff00000) return x-x;
    /* argument reduction needed */
    else {
        n = __ieee754_rem_pio2(x,y);
        switch(n&3) {
        case 0: return  __kernel_cos(y[0],y[1]);
        case 1: return -__kernel_sin(y[0],y[1],1);
        case 2: return -__kernel_cos(y[0],y[1]);
        default:
                return  __kernel_sin(y[0],y[1],1);
        }
    }
}
References __ieee754_rem_pio2(), __kernel_cos(), __kernel_sin(), and GET_HIGH_WORD.
Referenced by SDL_cos().
SDL_uclibc_exp()
double SDL_uclibc_exp (double x) extern
{
    double y;
    double hi = 0.0;
    double lo = 0.0;
    double c;
    double t;
    int32_t k=0;
    int32_t xsb;
    u_int32_t hx;
    GET_HIGH_WORD(hx,x);
    xsb = (hx>>31)&1;       /* sign bit of x */
    hx &= 0x7fffffff;       /* high word of |x| */
    /* filter out non-finite argument */
    if(hx >= 0x40862E42) {          /* if |x|>=709.78... */
            if(hx>=0x7ff00000) {
            u_int32_t lx;
        GET_LOW_WORD(lx,x);
        if(((hx&0xfffff)|lx)!=0)
             return x+x;      /* NaN */
        else return (xsb==0)? x:0.0;   /* exp(+-inf)={inf,0} */
        }
        #if 1
        if(x > o_threshold) return inf_union.d; /* overflow */
        #elif 1
        if(x > o_threshold) return huge*huge; /* overflow */
        #else  /* !!! FIXME: check this: "huge * huge" is a compiler warning, maybe they wanted +Inf? */
        if(x > o_threshold) return INFINITY; /* overflow */
        #endif
        if(x < u_threshold) return twom1000*twom1000; /* underflow */
    }
    /* argument reduction */
    if(hx > 0x3fd62e42) {       /* if  |x| > 0.5 ln2 */
        if(hx < 0x3FF0A2B2) {   /* and |x| < 1.5 ln2 */
        hi = x-ln2HI[xsb]; lo=ln2LO[xsb]; k = 1-xsb-xsb;
        } else {
        k  = (int32_t) (invln2*x+halF[xsb]);
        t  = k;
        hi = x - t*ln2HI[0];  /* t*ln2HI is exact here */
        lo = t*ln2LO[0];
        }
        x  = hi - lo;
    }
    else if(hx < 0x3e300000)  { /* when |x|<2**-28 */
        if(huge+x>one) return one+x;/* trigger inexact */
    }
    else k = 0;
    /* x is now in primary range */
    t  = x*x;
    c  = x - t*(P1+t*(P2+t*(P3+t*(P4+t*P5))));
    if(k==0)    return one-((x*c)/(c-2.0)-x);
    else        y = one-((lo-(x*c)/(2.0-c))-hi);
    if(k >= -1021) {
        u_int32_t hy;
        GET_HIGH_WORD(hy,y);
        SET_HIGH_WORD(y,hy+(k<<20));  /* add k to y's exponent */
        return y;
    } else {
        u_int32_t hy;
        GET_HIGH_WORD(hy,y);
        SET_HIGH_WORD(y,hy+((k+1000)<<20));   /* add k to y's exponent */
        return y*twom1000;
    }
}
SDL_uclibc_fabs()
double SDL_uclibc_fabs (double x) extern
{
    u_int32_t high;
    GET_HIGH_WORD(high,x);
    SET_HIGH_WORD(x,high&0x7fffffff);
        return x;
}
References GET_HIGH_WORD, and SET_HIGH_WORD.
Referenced by SDL_fabs().
SDL_uclibc_floor()
double SDL_uclibc_floor (double x) extern
{
    int32_t i0,i1,j0;
    u_int32_t i,j;
    EXTRACT_WORDS(i0,i1,x);
    j0 = ((i0>>20)&0x7ff)-0x3ff;
    if(j0<20) {
        if(j0<0) {  /* raise inexact if x != 0 */
        if(huge+x>0.0) {/* return 0*sign(x) if |x|<1 */
            if(i0>=0) {i0=i1=0;}
            else if(((i0&0x7fffffff)|i1)!=0)
            { i0=0xbff00000;i1=0;}
        }
        } else {
        i = (0x000fffff)>>j0;
        if(((i0&i)|i1)==0) return x; /* x is integral */
        if(huge+x>0.0) {   /* raise inexact flag */
            if(i0<0) i0 += (0x00100000)>>j0;
            i0 &= (~i); i1=0;
        }
        }
    } else if (j0>51) {
        if(j0==0x400) return x+x; /* inf or NaN */
        else return x;     /* x is integral */
    } else {
        i = ((u_int32_t)(0xffffffff))>>(j0-20);
        if((i1&i)==0) return x;    /* x is integral */
        if(huge+x>0.0) {       /* raise inexact flag */
        if(i0<0) {
            if(j0==20) i0+=1;
            else {
            j = i1+(1<<(52-j0));
            if(j<(u_int32_t)i1) i0 +=1 ;   /* got a carry */
            i1=j;
            }
        }
        i1 &= (~i);
        }
    }
    INSERT_WORDS(x,i0,i1);
    return x;
}
References EXTRACT_WORDS, huge, and INSERT_WORDS.
Referenced by SDL_floor().
SDL_uclibc_fmod()
double SDL_uclibc_fmod (double x, double y) extern
{
    int32_t n,hx,hy,hz,ix,iy,sx,i;
    u_int32_t lx,ly,lz;
    EXTRACT_WORDS(hx,lx,x);
    EXTRACT_WORDS(hy,ly,y);
    sx = hx&0x80000000;     /* sign of x */
    hx ^=sx;        /* |x| */
    hy &= 0x7fffffff;   /* |y| */
    /* purge off exception values */
    if((hy|ly)==0||(hx>=0x7ff00000)||   /* y=0,or x not finite */
      ((hy|((ly|-(int32_t)ly)>>31))>0x7ff00000))    /* or y is NaN */
        return (x*y)/(x*y);
    if(hx<=hy) {
        if((hx<hy)||(lx<ly)) return x; /* |x|<|y| return x */
        if(lx==ly)
        return Zero[(u_int32_t)sx>>31];    /* |x|=|y| return x*0*/
    }
    /* determine ix = ilogb(x) */
    if(hx<0x00100000) { /* subnormal x */
        if(hx==0) {
        for (ix = -1043, i=lx; i>0; i<<=1) ix -=1;
        } else {
        for (ix = -1022,i=(hx<<11); i>0; i<<=1) ix -=1;
        }
    } else ix = (hx>>20)-1023;
    /* determine iy = ilogb(y) */
    if(hy<0x00100000) { /* subnormal y */
        if(hy==0) {
        for (iy = -1043, i=ly; i>0; i<<=1) iy -=1;
        } else {
        for (iy = -1022,i=(hy<<11); i>0; i<<=1) iy -=1;
        }
    } else iy = (hy>>20)-1023;
    /* set up {hx,lx}, {hy,ly} and align y to x */
    if(ix >= -1022)
        hx = 0x00100000|(0x000fffff&hx);
    else {      /* subnormal x, shift x to normal */
        n = -1022-ix;
        if(n<=31) {
            hx = (hx<<n)|(lx>>(32-n));
            lx <<= n;
        } else {
        hx = lx<<(n-32);
        lx = 0;
        }
    }
    if(iy >= -1022)
        hy = 0x00100000|(0x000fffff&hy);
    else {      /* subnormal y, shift y to normal */
        n = -1022-iy;
        if(n<=31) {
            hy = (hy<<n)|(ly>>(32-n));
            ly <<= n;
        } else {
        hy = ly<<(n-32);
        ly = 0;
        }
    }
    /* fix point fmod */
    n = ix - iy;
    while(n--) {
        hz=hx-hy;lz=lx-ly; if(lx<ly) hz -= 1;
        if(hz<0){hx = hx+hx+(lx>>31); lx = lx+lx;}
        else {
            if((hz|lz)==0)      /* return sign(x)*0 */
            return Zero[(u_int32_t)sx>>31];
            hx = hz+hz+(lz>>31); lx = lz+lz;
        }
    }
    hz=hx-hy;lz=lx-ly; if(lx<ly) hz -= 1;
    if(hz>=0) {hx=hz;lx=lz;}
    /* convert back to floating value and restore the sign */
    if((hx|lx)==0)          /* return sign(x)*0 */
        return Zero[(u_int32_t)sx>>31];
    while(hx<0x00100000) {      /* normalize x */
        hx = hx+hx+(lx>>31); lx = lx+lx;
        iy -= 1;
    }
    if(iy>= -1022) {    /* normalize output */
        hx = ((hx-0x00100000)|((iy+1023)<<20));
        INSERT_WORDS(x,hx|sx,lx);
    } else {        /* subnormal output */
        n = -1022 - iy;
        if(n<=20) {
        lx = (lx>>n)|((u_int32_t)hx<<(32-n));
        hx >>= n;
        } else if (n<=31) {
        lx = (hx<<(32-n))|(lx>>n); hx = sx;
        } else {
        lx = hx>>(n-32); hx = sx;
        }
        INSERT_WORDS(x,hx|sx,lx);
        x *= one;       /* create necessary signal */
    }
    return x;      /* exact output */
}
SDL_uclibc_isinf()
int SDL_uclibc_isinf (double x) extern
{
    int32_t hx,lx;
    EXTRACT_WORDS(hx,lx,x);
    lx |= (hx & 0x7fffffff) ^ 0x7ff00000;
    lx |= -lx;
    return ~(lx >> 31) & (hx >> 30);
}
References EXTRACT_WORDS.
Referenced by SDL_isinf().
SDL_uclibc_isinff()
int SDL_uclibc_isinff (float x) extern
{
    int32_t ix,t;
    GET_FLOAT_WORD(ix,x);
    t = ix & 0x7fffffff;
    t ^= 0x7f800000;
    t |= -t;
    return ~(t >> 31) & (ix >> 30);
}
References GET_FLOAT_WORD.
Referenced by SDL_isinff().
SDL_uclibc_isnan()
int SDL_uclibc_isnan (double x) extern
{
    int32_t hx,lx;
    EXTRACT_WORDS(hx,lx,x);
    hx &= 0x7fffffff;
    hx |= (u_int32_t)(lx|(-lx))>>31;
    hx = 0x7ff00000 - hx;
    return (int)(((u_int32_t)hx)>>31);
}
References EXTRACT_WORDS.
Referenced by SDL_isnan().
SDL_uclibc_isnanf()
int SDL_uclibc_isnanf (float x) extern
{
    int32_t ix;
    GET_FLOAT_WORD(ix,x);
    ix &= 0x7fffffff;
    ix = 0x7f800000 - ix;
    return (int)(((u_int32_t)(ix))>>31);
}
References GET_FLOAT_WORD.
Referenced by SDL_isnanf().
SDL_uclibc_log()
double SDL_uclibc_log (double x) extern
{
    double hfsq,f,s,z,R,w,t1,t2,dk;
    int32_t k,hx,i,j;
    u_int32_t lx;
    EXTRACT_WORDS(hx,lx,x);
    k=0;
    if (hx < 0x00100000) {          /* x < 2**-1022  */
        if (((hx&0x7fffffff)|lx)==0)
        return -two54/zero;        /* log(+-0)=-inf */
        if (hx<0) return (x-x)/zero;  /* log(-#) = NaN */
        k -= 54; x *= two54; /* subnormal number, scale up x */
        GET_HIGH_WORD(hx,x);
    }
    if (hx >= 0x7ff00000) return x+x;
    k += (hx>>20)-1023;
    hx &= 0x000fffff;
    i = (hx+0x95f64)&0x100000;
    SET_HIGH_WORD(x,hx|(i^0x3ff00000));   /* normalize x or x/2 */
    k += (i>>20);
    f = x-1.0;
    if((0x000fffff&(2+hx))<3) { /* |f| < 2**-20 */
        if(f==zero) {if(k==0) return zero;  else {dk=(double)k;
                 return dk*ln2_hi+dk*ln2_lo;}
        }
        R = f*f*(0.5-0.33333333333333333*f);
        if(k==0) return f-R; else {dk=(double)k;
                 return dk*ln2_hi-((R-dk*ln2_lo)-f);}
    }
    s = f/(2.0+f);
    dk = (double)k;
    z = s*s;
    i = hx-0x6147a;
    w = z*z;
    j = 0x6b851-hx;
    t1= w*(Lg2+w*(Lg4+w*Lg6));
    t2= z*(Lg1+w*(Lg3+w*(Lg5+w*Lg7)));
    i |= j;
    R = t2+t1;
    if(i>0) {
        hfsq=0.5*f*f;
        if(k==0) return f-(hfsq-s*(hfsq+R)); else
             return dk*ln2_hi-((hfsq-(s*(hfsq+R)+dk*ln2_lo))-f);
    } else {
        if(k==0) return f-s*(f-R); else
             return dk*ln2_hi-((s*(f-R)-dk*ln2_lo)-f);
    }
}
SDL_uclibc_log10()
double SDL_uclibc_log10 (double x) extern
{
    double y,z;
    int32_t i,k,hx;
    u_int32_t lx;
    EXTRACT_WORDS(hx,lx,x);
        k=0;
        if (hx < 0x00100000) {                  /* x < 2**-1022  */
            if (((hx&0x7fffffff)|lx)==0)
                return -two54/zero;             /* log(+-0)=-inf */
            if (hx<0) return (x-x)/zero;        /* log(-#) = NaN */
            k -= 54; x *= two54; /* subnormal number, scale up x */
        GET_HIGH_WORD(hx,x);
        }
    if (hx >= 0x7ff00000) return x+x;
    k += (hx>>20)-1023;
    i  = ((u_int32_t)k&0x80000000)>>31;
        hx = (hx&0x000fffff)|((0x3ff-i)<<20);
        y  = (double)(k+i);
    SET_HIGH_WORD(x,hx);
    z  = y*log10_2lo + ivln10*__ieee754_log(x);
    return  z+y*log10_2hi;
}
SDL_uclibc_modf()
double SDL_uclibc_modf (double x, double * y) extern
{
    int32_t i0,i1,_j0;
    u_int32_t i;
    EXTRACT_WORDS(i0,i1,x);
    _j0 = ((i0>>20)&0x7ff)-0x3ff;   /* exponent of x */
    if(_j0<20) {            /* integer part in high x */
        if(_j0<0) {         /* |x|<1 */
            INSERT_WORDS(*iptr,i0&0x80000000,0);    /* *iptr = +-0 */
        return x;
        } else {
        i = (0x000fffff)>>_j0;
        if(((i0&i)|i1)==0) {        /* x is integral */
            *iptr = x;
            INSERT_WORDS(x,i0&0x80000000,0);   /* return +-0 */
            return x;
        } else {
            INSERT_WORDS(*iptr,i0&(~i),0);
            return x - *iptr;
        }
        }
    } else if (_j0>51) {        /* no fraction part */
        *iptr = x*one;
        /* We must handle NaNs separately.  */
        if (_j0 == 0x400 && ((i0 & 0xfffff) | i1))
          return x*one;
        INSERT_WORDS(x,i0&0x80000000,0);   /* return +-0 */
        return x;
    } else {            /* fraction part in low x */
        i = ((u_int32_t)(0xffffffff))>>(_j0-20);
        if((i1&i)==0) {         /* x is integral */
        *iptr = x;
        INSERT_WORDS(x,i0&0x80000000,0);   /* return +-0 */
        return x;
        } else {
            INSERT_WORDS(*iptr,i0,i1&(~i));
        return x - *iptr;
        }
    }
}
References EXTRACT_WORDS, INSERT_WORDS, and one.
Referenced by SDL_modf().
SDL_uclibc_pow()
double SDL_uclibc_pow (double x, double y) extern
{
    double z,ax,z_h,z_l,p_h,p_l;
    double y1,t1,t2,r,s,t,u,v,w;
    int32_t i,j,k,yisint,n;
    int32_t hx,hy,ix,iy;
    u_int32_t lx,ly;
    EXTRACT_WORDS(hx,lx,x);
    /* x==1: 1**y = 1 (even if y is NaN) */
    if (hx==0x3ff00000 && lx==0) {
        return x;
    }
    ix = hx&0x7fffffff;
    EXTRACT_WORDS(hy,ly,y);
    iy = hy&0x7fffffff;
    /* y==zero: x**0 = 1 */
    if((iy|ly)==0) return one;
    /* +-NaN return x+y */
    if(ix > 0x7ff00000 || ((ix==0x7ff00000)&&(lx!=0)) ||
       iy > 0x7ff00000 || ((iy==0x7ff00000)&&(ly!=0)))
        return x+y;
    /* determine if y is an odd int when x < 0
     * yisint = 0   ... y is not an integer
     * yisint = 1   ... y is an odd int
     * yisint = 2   ... y is an even int
     */
    yisint  = 0;
    if(hx<0) {
        if(iy>=0x43400000) yisint = 2; /* even integer y */
        else if(iy>=0x3ff00000) {
        k = (iy>>20)-0x3ff;    /* exponent */
        if(k>20) {
            j = ly>>(52-k);
            if(((u_int32_t)j<<(52-k))==ly) yisint = 2-(j&1);
        } else if(ly==0) {
            j = iy>>(20-k);
            if((j<<(20-k))==iy) yisint = 2-(j&1);
        }
        }
    }
    /* special value of y */
    if(ly==0) {
        if (iy==0x7ff00000) {       /* y is +-inf */
            if (((ix-0x3ff00000)|lx)==0)
            return one;          /* +-1**+-inf is 1 (yes, weird rule) */
            if (ix >= 0x3ff00000)   /* (|x|>1)**+-inf = inf,0 */
            return (hy>=0) ? y : zero;
            /* (|x|<1)**-,+inf = inf,0 */
        return (hy<0) ? -y : zero;
        }
        if(iy==0x3ff00000) {    /* y is  +-1 */
        if(hy<0) return one/x; else return x;
        }
        if(hy==0x40000000) return x*x; /* y is  2 */
        if(hy==0x3fe00000) {    /* y is  0.5 */
        if(hx>=0)   /* x >= +0 */
            return __ieee754_sqrt(x);
        }
    }
    ax   = fabs(x);
    /* special value of x */
    if(lx==0) {
        if(ix==0x7ff00000||ix==0||ix==0x3ff00000){
        z = ax;         /*x is +-0,+-inf,+-1*/
        if(hy<0) z = one/z;  /* z = (1/|x|) */
        if(hx<0) {
            if(((ix-0x3ff00000)|yisint)==0) {
            z = (z-z)/(z-z); /* (-1)**non-int is NaN */
            } else if(yisint==1)
            z = -z;     /* (x<0)**odd = -(|x|**odd) */
        }
        return z;
        }
    }
    /* (x<0)**(non-int) is NaN */
    if(((((u_int32_t)hx>>31)-1)|yisint)==0) return (x-x)/(x-x);
    /* |y| is huge */
    if(iy>0x41e00000) { /* if |y| > 2**31 */
        if(iy>0x43f00000){  /* if |y| > 2**64, must o/uflow */
        if(ix<=0x3fefffff) return (hy<0)? huge*huge:tiny*tiny;
        if(ix>=0x3ff00000) return (hy>0)? huge*huge:tiny*tiny;
        }
    /* over/underflow if x is not close to one */
        if(ix<0x3fefffff) return (hy<0)? huge*huge:tiny*tiny;
        if(ix>0x3ff00000) return (hy>0)? huge*huge:tiny*tiny;
    /* now |1-x| is tiny <= 2**-20, suffice to compute
       log(x) by x-x^2/2+x^3/3-x^4/4 */
        t = x-1;       /* t has 20 trailing zeros */
        w = (t*t)*(0.5-t*(0.3333333333333333333333-t*0.25));
        u = ivln2_h*t;   /* ivln2_h has 21 sig. bits */
        v = t*ivln2_l-w*ivln2;
        t1 = u+v;
        SET_LOW_WORD(t1,0);
        t2 = v-(t1-u);
    } else {
        double s2,s_h,s_l,t_h,t_l;
        n = 0;
    /* take care subnormal number */
        if(ix<0x00100000)
        {ax *= two53; n -= 53; GET_HIGH_WORD(ix,ax); }
        n  += ((ix)>>20)-0x3ff;
        j  = ix&0x000fffff;
    /* determine interval */
        ix = j|0x3ff00000;      /* normalize ix */
        if(j<=0x3988E) k=0;     /* |x|<sqrt(3/2) */
        else if(j<0xBB67A) k=1; /* |x|<sqrt(3)   */
        else {k=0;n+=1;ix -= 0x00100000;}
        SET_HIGH_WORD(ax,ix);
    /* compute s = s_h+s_l = (x-1)/(x+1) or (x-1.5)/(x+1.5) */
        u = ax-bp[k];     /* bp[0]=1.0, bp[1]=1.5 */
        v = one/(ax+bp[k]);
        s = u*v;
        s_h = s;
        SET_LOW_WORD(s_h,0);
    /* t_h=ax+bp[k] High */
        t_h = zero;
        SET_HIGH_WORD(t_h,((ix>>1)|0x20000000)+0x00080000+(k<<18));
        t_l = ax - (t_h-bp[k]);
        s_l = v*((u-s_h*t_h)-s_h*t_l);
    /* compute log(ax) */
        s2 = s*s;
        r = s2*s2*(L1+s2*(L2+s2*(L3+s2*(L4+s2*(L5+s2*L6)))));
        r += s_l*(s_h+s);
        s2  = s_h*s_h;
        t_h = 3.0+s2+r;
        SET_LOW_WORD(t_h,0);
        t_l = r-((t_h-3.0)-s2);
    /* u+v = s*(1+...) */
        u = s_h*t_h;
        v = s_l*t_h+t_l*s;
    /* 2/(3log2)*(s+...) */
        p_h = u+v;
        SET_LOW_WORD(p_h,0);
        p_l = v-(p_h-u);
        z_h = cp_h*p_h;     /* cp_h+cp_l = 2/(3*log2) */
        z_l = cp_l*p_h+p_l*cp+dp_l[k];
    /* log2(ax) = (s+..)*2/(3*log2) = n + dp_h + z_h + z_l */
        t = (double)n;
        t1 = (((z_h+z_l)+dp_h[k])+t);
        SET_LOW_WORD(t1,0);
        t2 = z_l-(((t1-t)-dp_h[k])-z_h);
    }
    s = one; /* s (sign of result -ve**odd) = -1 else = 1 */
    if(((((u_int32_t)hx>>31)-1)|(yisint-1))==0)
        s = -one;/* (-ve)**(odd int) */
    /* split up y into y1+y2 and compute (y1+y2)*(t1+t2) */
    y1  = y;
    SET_LOW_WORD(y1,0);
    p_l = (y-y1)*t1+y*t2;
    p_h = y1*t1;
    z = p_l+p_h;
    EXTRACT_WORDS(j,i,z);
    if (j>=0x40900000) {                /* z >= 1024 */
        if(((j-0x40900000)|i)!=0)           /* if z > 1024 */
        return s*huge*huge;         /* overflow */
        else {
        if(p_l+ovt>z-p_h) return s*huge*huge;    /* overflow */
        }
    } else if((j&0x7fffffff)>=0x4090cc00 ) {    /* z <= -1075 */
        if(((j-0xc090cc00)|i)!=0)       /* z < -1075 */
        return s*tiny*tiny;     /* underflow */
        else {
        if(p_l<=z-p_h) return s*tiny*tiny;  /* underflow */
        }
    }
    /*
     * compute 2**(p_h+p_l)
     */
    i = j&0x7fffffff;
    k = (i>>20)-0x3ff;
    n = 0;
    if(i>0x3fe00000) {      /* if |z| > 0.5, set n = [z+0.5] */
        n = j+(0x00100000>>(k+1));
        k = ((n&0x7fffffff)>>20)-0x3ff;    /* new k for n */
        t = zero;
        SET_HIGH_WORD(t,n&~(0x000fffff>>k));
        n = ((n&0x000fffff)|0x00100000)>>(20-k);
        if(j<0) n = -n;
        p_h -= t;
    }
    t = p_l+p_h;
    SET_LOW_WORD(t,0);
    u = t*lg2_h;
    v = (p_l-(t-p_h))*lg2+t*lg2_l;
    z = u+v;
    w = v-(z-u);
    t  = z*z;
    t1  = z - t*(P1+t*(P2+t*(P3+t*(P4+t*P5))));
    r  = (z*t1)/(t1-two)-(w+z*w);
    z  = one-(r-z);
    GET_HIGH_WORD(j,z);
    j += (n<<20);
    if((j>>20)<=0) z = scalbn(z,n);  /* subnormal output */
    else SET_HIGH_WORD(z,j);
    return s*z;
}
SDL_uclibc_scalbn()
double SDL_uclibc_scalbn (double x, int n) extern
{
    return scalbln(x, n);
}
References scalbln, and scalbn.
Referenced by SDL_scalbn().
SDL_uclibc_sin()
double SDL_uclibc_sin (double x) extern
{
    double y[2],z=0.0;
    int32_t n, ix;
    /* High word of x. */
    GET_HIGH_WORD(ix,x);
    /* |x| ~< pi/4 */
    ix &= 0x7fffffff;
    if(ix <= 0x3fe921fb) return __kernel_sin(x,z,0);
    /* sin(Inf or NaN) is NaN */
    else if (ix>=0x7ff00000) return x-x;
    /* argument reduction needed */
    else {
        n = __ieee754_rem_pio2(x,y);
        switch(n&3) {
        case 0: return  __kernel_sin(y[0],y[1],1);
        case 1: return  __kernel_cos(y[0],y[1]);
        case 2: return -__kernel_sin(y[0],y[1],1);
        default:
            return -__kernel_cos(y[0],y[1]);
        }
    }
}
References __ieee754_rem_pio2(), __kernel_cos(), __kernel_sin(), and GET_HIGH_WORD.
Referenced by SDL_sin().
SDL_uclibc_sqrt()
double SDL_uclibc_sqrt (double x) extern
{
    double z;
    int32_t sign = (int)0x80000000;
    int32_t ix0,s0,q,m,t,i;
    u_int32_t r,t1,s1,ix1,q1;
    EXTRACT_WORDS(ix0,ix1,x);
    /* take care of Inf and NaN */
    if((ix0&0x7ff00000)==0x7ff00000) {
        return x*x+x;        /* sqrt(NaN)=NaN, sqrt(+inf)=+inf
                       sqrt(-inf)=sNaN */
    }
    /* take care of zero */
    if(ix0<=0) {
        if(((ix0&(~sign))|ix1)==0) return x;/* sqrt(+-0) = +-0 */
        else if(ix0<0)
        return (x-x)/(x-x);     /* sqrt(-ve) = sNaN */
    }
    /* normalize x */
    m = (ix0>>20);
    if(m==0) {              /* subnormal x */
        while(ix0==0) {
        m -= 21;
        ix0 |= (ix1>>11); ix1 <<= 21;
        }
        for(i=0;(ix0&0x00100000)==0;i++) ix0<<=1;
        m -= i-1;
        ix0 |= (ix1>>(32-i));
        ix1 <<= i;
    }
    m -= 1023;  /* unbias exponent */
    ix0 = (ix0&0x000fffff)|0x00100000;
    if(m&1){    /* odd m, double x to make it even */
        ix0 += ix0 + ((ix1&sign)>>31);
        ix1 += ix1;
    }
    m >>= 1;    /* m = [m/2] */
    /* generate sqrt(x) bit by bit */
    ix0 += ix0 + ((ix1&sign)>>31);
    ix1 += ix1;
    q = q1 = s0 = s1 = 0;   /* [q,q1] = sqrt(x) */
    r = 0x00200000;     /* r = moving bit from right to left */
    while(r!=0) {
        t = s0+r;
        if(t<=ix0) {
        s0   = t+r;
        ix0 -= t;
        q   += r;
        }
        ix0 += ix0 + ((ix1&sign)>>31);
        ix1 += ix1;
        r>>=1;
    }
    r = sign;
    while(r!=0) {
        t1 = s1+r;
        t  = s0;
        if((t<ix0)||((t==ix0)&&(t1<=ix1))) {
        s1  = t1+r;
        if(((t1&sign)==(u_int32_t)sign)&&(s1&sign)==0) s0 += 1;
        ix0 -= t;
        if (ix1 < t1) ix0 -= 1;
        ix1 -= t1;
        q1  += r;
        }
        ix0 += ix0 + ((ix1&sign)>>31);
        ix1 += ix1;
        r>>=1;
    }
    /* use floating add to find out rounding direction */
    if((ix0|ix1)!=0) {
        z = one-tiny; /* trigger inexact flag */
        if (z>=one) {
            z = one+tiny;
            if (q1==(u_int32_t)0xffffffff) { q1=0; q += 1;}
        else if (z>one) {
            if (q1==(u_int32_t)0xfffffffe) q+=1;
            q1+=2;
        } else
                q1 += (q1&1);
        }
    }
    ix0 = (q>>1)+0x3fe00000;
    ix1 =  q1>>1;
    if ((q&1)==1) ix1 |= sign;
    ix0 += (m <<20);
    INSERT_WORDS(z,ix0,ix1);
    return z;
}
SDL_uclibc_tan()
double SDL_uclibc_tan (double x) extern
{
    double y[2],z=0.0;
    int32_t n, ix;
    /* High word of x. */
    GET_HIGH_WORD(ix,x);
    /* |x| ~< pi/4 */
    ix &= 0x7fffffff;
    if(ix <= 0x3fe921fb) return __kernel_tan(x,z,1);
    /* tan(Inf or NaN) is NaN */
    else if (ix>=0x7ff00000) return x-x;      /* NaN */
    /* argument reduction needed */
    else {
        n = __ieee754_rem_pio2(x,y);
        return __kernel_tan(y[0],y[1],1-((n&1)<<1)); /*   1 -- n even
                            -1 -- n odd */
    }
}
References __ieee754_rem_pio2(), __kernel_tan(), and GET_HIGH_WORD.
Referenced by SDL_tan().