SDL3: SDL-main/src/time/SDL_time_c.h File Reference
SDL_time_c.h File Reference
#include "SDL_internal.h"
Macros
#define SDL_SECONDS_PER_DAY 86400
Functions
Sint64 SDL_CivilToDays (int year, int month, int day, int *day_of_week, int *day_of_year)
void SDL_GetSystemTimeLocalePreferences (SDL_DateFormat *df, SDL_TimeFormat *tf)
Macro Definition Documentation
SDL_SECONDS_PER_DAY
#define SDL_SECONDS_PER_DAY 86400
Referenced by SDL_DateTimeToTime().
Function Documentation
SDL_CivilToDays()
Sint64 SDL_CivilToDays (int year, int month, int day, int * day_of_week, int * day_of_year) extern
{
    year -= month <= 2;
    const int era = (year >= 0 ? year : year - 399) / 400;
    const unsigned yoe = (unsigned)(year - era * 400);                                  // [0, 399]
    const unsigned doy = (153 * (month > 2 ? month - 3 : month + 9) + 2) / 5 + day - 1; // [0, 365]
    const unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;                         // [0, 146096]
    const Sint64 z = (Sint64)(era) * 146097 + (Sint64)(doe)-719468;
    if (day_of_week) {
        *day_of_week = (int)(z >= -4 ? (z + 4) % 7 : (z + 5) % 7 + 6);
    }
    if (day_of_year) {
        // This algorithm considers March 1 to be the first day of the year, so offset by Jan + Feb.
        if (doy > 305) {
            // Day 0 is the first day of the year.
            *day_of_year = doy - 306;
        } else {
            const int doy_offset = 59 + (!(year % 4) && ((year % 100) || !(year % 400)));
            *day_of_year = doy + doy_offset;
        }
    }
    return z;
}
Referenced by SDL_DateTimeToTime(), SDL_GetDayOfWeek(), and SDL_GetDayOfYear().
SDL_GetSystemTimeLocalePreferences()
void SDL_GetSystemTimeLocalePreferences (SDL_DateFormat * df, SDL_TimeFormat * tf) extern
Referenced by SDL_GetDateTimeLocalePreferences().