SDL3: SDL-main/include/SDL3/SDL_gpu.h File Reference
SDL_gpu.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_pixels.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_rect.h>
#include <SDL3/SDL_surface.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_GPUBlitInfo
struct SDL_GPUBlitRegion
struct SDL_GPUBufferBinding
struct SDL_GPUBufferCreateInfo
struct SDL_GPUBufferLocation
struct SDL_GPUBufferRegion
struct SDL_GPUColorTargetBlendState
struct SDL_GPUColorTargetDescription
struct SDL_GPUColorTargetInfo
struct SDL_GPUComputePipelineCreateInfo
struct SDL_GPUDepthStencilState
struct SDL_GPUDepthStencilTargetInfo
struct SDL_GPUGraphicsPipelineCreateInfo
struct SDL_GPUGraphicsPipelineTargetInfo
struct SDL_GPUIndexedIndirectDrawCommand
struct SDL_GPUIndirectDispatchCommand
struct SDL_GPUIndirectDrawCommand
struct SDL_GPUMultisampleState
struct SDL_GPURasterizerState
struct SDL_GPUSamplerCreateInfo
struct SDL_GPUShaderCreateInfo
struct SDL_GPUStencilOpState
struct SDL_GPUStorageBufferReadWriteBinding
struct SDL_GPUStorageTextureReadWriteBinding
struct SDL_GPUTextureCreateInfo
struct SDL_GPUTextureLocation
struct SDL_GPUTextureRegion
struct SDL_GPUTextureSamplerBinding
struct SDL_GPUTextureTransferInfo
struct SDL_GPUTransferBufferCreateInfo
struct SDL_GPUTransferBufferLocation
struct SDL_GPUVertexAttribute
struct SDL_GPUVertexBufferDescription
struct SDL_GPUVertexInputState
struct SDL_GPUViewport
Macros
#define SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_READ (1u << 4)
#define SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_WRITE (1u << 5)
#define SDL_GPU_BUFFERUSAGE_GRAPHICS_STORAGE_READ (1u << 3)
#define SDL_GPU_BUFFERUSAGE_INDEX (1u << 1)
#define SDL_GPU_BUFFERUSAGE_INDIRECT (1u << 2)
#define SDL_GPU_BUFFERUSAGE_VERTEX (1u << 0)
#define SDL_GPU_COLORCOMPONENT_A (1u << 3)
#define SDL_GPU_COLORCOMPONENT_B (1u << 2)
#define SDL_GPU_COLORCOMPONENT_G (1u << 1)
#define SDL_GPU_COLORCOMPONENT_R (1u << 0)
#define SDL_GPU_SHADERFORMAT_DXBC (1u << 2)
#define SDL_GPU_SHADERFORMAT_DXIL (1u << 3)
#define SDL_GPU_SHADERFORMAT_INVALID 0
#define SDL_GPU_SHADERFORMAT_METALLIB (1u << 5)
#define SDL_GPU_SHADERFORMAT_MSL (1u << 4)
#define SDL_GPU_SHADERFORMAT_PRIVATE (1u << 0)
#define SDL_GPU_SHADERFORMAT_SPIRV (1u << 1)
#define SDL_GPU_TEXTUREUSAGE_COLOR_TARGET (1u << 1)
#define SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ (1u << 4)
#define SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE (1u << 6)
#define SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE (1u << 5)
#define SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET (1u << 2)
#define SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ (1u << 3)
#define SDL_GPU_TEXTUREUSAGE_SAMPLER (1u << 0)
#define SDL_PROP_GPU_BUFFER_CREATE_NAME_STRING "SDL.gpu.buffer.create.name"
#define SDL_PROP_GPU_COMPUTEPIPELINE_CREATE_NAME_STRING "SDL.gpu.computepipeline.create.name"
#define SDL_PROP_GPU_DEVICE_CREATE_D3D12_SEMANTIC_NAME_STRING "SDL.gpu.device.create.d3d12.semantic"
#define SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOLEAN "SDL.gpu.device.create.debugmode"
#define SDL_PROP_GPU_DEVICE_CREATE_NAME_STRING "SDL.gpu.device.create.name"
#define SDL_PROP_GPU_DEVICE_CREATE_PREFERLOWPOWER_BOOLEAN "SDL.gpu.device.create.preferlowpower"
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXBC_BOOLEAN "SDL.gpu.device.create.shaders.dxbc"
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXIL_BOOLEAN "SDL.gpu.device.create.shaders.dxil"
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_METALLIB_BOOLEAN "SDL.gpu.device.create.shaders.metallib"
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_MSL_BOOLEAN "SDL.gpu.device.create.shaders.msl"
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_PRIVATE_BOOLEAN "SDL.gpu.device.create.shaders.private"
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_SPIRV_BOOLEAN "SDL.gpu.device.create.shaders.spirv"
#define SDL_PROP_GPU_DEVICE_CREATE_VERBOSE_BOOLEAN "SDL.gpu.device.create.verbose"
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DEPTHCLAMP_BOOLEAN "SDL.gpu.device.create.vulkan.depthclamp"
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DRAWINDIRECTFIRST_BOOLEAN "SDL.gpu.device.create.vulkan.drawindirectfirstinstance"
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SAMPLERANISOTROPY_BOOLEAN "SDL.gpu.device.create.vulkan.sampleranisotropy"
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SHADERCLIPDISTANCE_BOOLEAN "SDL.gpu.device.create.vulkan.shaderclipdistance"
#define SDL_PROP_GPU_DEVICE_DRIVER_INFO_STRING "SDL.gpu.device.driver_info"
#define SDL_PROP_GPU_DEVICE_DRIVER_NAME_STRING "SDL.gpu.device.driver_name"
#define SDL_PROP_GPU_DEVICE_DRIVER_VERSION_STRING "SDL.gpu.device.driver_version"
#define SDL_PROP_GPU_DEVICE_NAME_STRING "SDL.gpu.device.name"
#define SDL_PROP_GPU_GRAPHICSPIPELINE_CREATE_NAME_STRING "SDL.gpu.graphicspipeline.create.name"
#define SDL_PROP_GPU_SAMPLER_CREATE_NAME_STRING "SDL.gpu.sampler.create.name"
#define SDL_PROP_GPU_SHADER_CREATE_NAME_STRING "SDL.gpu.shader.create.name"
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_A_FLOAT "SDL.gpu.texture.create.d3d12.clear.a"
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_B_FLOAT "SDL.gpu.texture.create.d3d12.clear.b"
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_DEPTH_FLOAT "SDL.gpu.texture.create.d3d12.clear.depth"
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_G_FLOAT "SDL.gpu.texture.create.d3d12.clear.g"
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_R_FLOAT "SDL.gpu.texture.create.d3d12.clear.r"
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_NUMBER "SDL.gpu.texture.create.d3d12.clear.stencil"
#define SDL_PROP_GPU_TEXTURE_CREATE_NAME_STRING "SDL.gpu.texture.create.name"
#define SDL_PROP_GPU_TRANSFERBUFFER_CREATE_NAME_STRING "SDL.gpu.transferbuffer.create.name"
Typedefs
typedef enum SDL_GPUBlendFactor SDL_GPUBlendFactor
typedef enum SDL_GPUBlendOp SDL_GPUBlendOp
typedef struct SDL_GPUBlitInfo SDL_GPUBlitInfo
typedef struct SDL_GPUBlitRegion SDL_GPUBlitRegion
typedef struct SDL_GPUBuffer SDL_GPUBuffer
typedef struct SDL_GPUBufferBinding SDL_GPUBufferBinding
typedef struct SDL_GPUBufferCreateInfo SDL_GPUBufferCreateInfo
typedef struct SDL_GPUBufferLocation SDL_GPUBufferLocation
typedef struct SDL_GPUBufferRegion SDL_GPUBufferRegion
typedef Uint32 SDL_GPUBufferUsageFlags
typedef Uint8 SDL_GPUColorComponentFlags
typedef struct SDL_GPUColorTargetBlendState SDL_GPUColorTargetBlendState
typedef struct SDL_GPUColorTargetDescription SDL_GPUColorTargetDescription
typedef struct SDL_GPUColorTargetInfo SDL_GPUColorTargetInfo
typedef struct SDL_GPUCommandBuffer SDL_GPUCommandBuffer
typedef enum SDL_GPUCompareOp SDL_GPUCompareOp
typedef struct SDL_GPUComputePass SDL_GPUComputePass
typedef struct SDL_GPUComputePipeline SDL_GPUComputePipeline
typedef struct SDL_GPUComputePipelineCreateInfo SDL_GPUComputePipelineCreateInfo
typedef struct SDL_GPUCopyPass SDL_GPUCopyPass
typedef enum SDL_GPUCubeMapFace SDL_GPUCubeMapFace
typedef enum SDL_GPUCullMode SDL_GPUCullMode
typedef struct SDL_GPUDepthStencilState SDL_GPUDepthStencilState
typedef struct SDL_GPUDepthStencilTargetInfo SDL_GPUDepthStencilTargetInfo
typedef struct SDL_GPUDevice SDL_GPUDevice
typedef struct SDL_GPUFence SDL_GPUFence
typedef enum SDL_GPUFillMode SDL_GPUFillMode
typedef enum SDL_GPUFilter SDL_GPUFilter
typedef enum SDL_GPUFrontFace SDL_GPUFrontFace
typedef struct SDL_GPUGraphicsPipeline SDL_GPUGraphicsPipeline
typedef struct SDL_GPUGraphicsPipelineCreateInfo SDL_GPUGraphicsPipelineCreateInfo
typedef struct SDL_GPUGraphicsPipelineTargetInfo SDL_GPUGraphicsPipelineTargetInfo
typedef struct SDL_GPUIndexedIndirectDrawCommand SDL_GPUIndexedIndirectDrawCommand
typedef enum SDL_GPUIndexElementSize SDL_GPUIndexElementSize
typedef struct SDL_GPUIndirectDispatchCommand SDL_GPUIndirectDispatchCommand
typedef struct SDL_GPUIndirectDrawCommand SDL_GPUIndirectDrawCommand
typedef enum SDL_GPULoadOp SDL_GPULoadOp
typedef struct SDL_GPUMultisampleState SDL_GPUMultisampleState
typedef enum SDL_GPUPresentMode SDL_GPUPresentMode
typedef enum SDL_GPUPrimitiveType SDL_GPUPrimitiveType
typedef struct SDL_GPURasterizerState SDL_GPURasterizerState
typedef struct SDL_GPURenderPass SDL_GPURenderPass
typedef enum SDL_GPUSampleCount SDL_GPUSampleCount
typedef struct SDL_GPUSampler SDL_GPUSampler
typedef enum SDL_GPUSamplerAddressMode SDL_GPUSamplerAddressMode
typedef struct SDL_GPUSamplerCreateInfo SDL_GPUSamplerCreateInfo
typedef enum SDL_GPUSamplerMipmapMode SDL_GPUSamplerMipmapMode
typedef struct SDL_GPUShader SDL_GPUShader
typedef struct SDL_GPUShaderCreateInfo SDL_GPUShaderCreateInfo
typedef Uint32 SDL_GPUShaderFormat
typedef enum SDL_GPUShaderStage SDL_GPUShaderStage
typedef enum SDL_GPUStencilOp SDL_GPUStencilOp
typedef struct SDL_GPUStencilOpState SDL_GPUStencilOpState
typedef struct SDL_GPUStorageBufferReadWriteBinding SDL_GPUStorageBufferReadWriteBinding
typedef struct SDL_GPUStorageTextureReadWriteBinding SDL_GPUStorageTextureReadWriteBinding
typedef enum SDL_GPUStoreOp SDL_GPUStoreOp
typedef enum SDL_GPUSwapchainComposition SDL_GPUSwapchainComposition
typedef struct SDL_GPUTexture SDL_GPUTexture
typedef struct SDL_GPUTextureCreateInfo SDL_GPUTextureCreateInfo
typedef enum SDL_GPUTextureFormat SDL_GPUTextureFormat
typedef struct SDL_GPUTextureLocation SDL_GPUTextureLocation
typedef struct SDL_GPUTextureRegion SDL_GPUTextureRegion
typedef struct SDL_GPUTextureSamplerBinding SDL_GPUTextureSamplerBinding
typedef struct SDL_GPUTextureTransferInfo SDL_GPUTextureTransferInfo
typedef enum SDL_GPUTextureType SDL_GPUTextureType
typedef Uint32 SDL_GPUTextureUsageFlags
typedef struct SDL_GPUTransferBuffer SDL_GPUTransferBuffer
typedef struct SDL_GPUTransferBufferCreateInfo SDL_GPUTransferBufferCreateInfo
typedef struct SDL_GPUTransferBufferLocation SDL_GPUTransferBufferLocation
typedef enum SDL_GPUTransferBufferUsage SDL_GPUTransferBufferUsage
typedef struct SDL_GPUVertexAttribute SDL_GPUVertexAttribute
typedef struct SDL_GPUVertexBufferDescription SDL_GPUVertexBufferDescription
typedef enum SDL_GPUVertexElementFormat SDL_GPUVertexElementFormat
typedef enum SDL_GPUVertexInputRate SDL_GPUVertexInputRate
typedef struct SDL_GPUVertexInputState SDL_GPUVertexInputState
typedef struct SDL_GPUViewport SDL_GPUViewport
Enumerations
enum SDL_GPUBlendFactor {
SDL_GPU_BLENDFACTOR_INVALID , SDL_GPU_BLENDFACTOR_ZERO , SDL_GPU_BLENDFACTOR_ONE , SDL_GPU_BLENDFACTOR_SRC_COLOR ,
SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_COLOR , SDL_GPU_BLENDFACTOR_DST_COLOR , SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_COLOR , SDL_GPU_BLENDFACTOR_SRC_ALPHA ,
SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA , SDL_GPU_BLENDFACTOR_DST_ALPHA , SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_ALPHA , SDL_GPU_BLENDFACTOR_CONSTANT_COLOR ,
SDL_GPU_BLENDFACTOR_ONE_MINUS_CONSTANT_COLOR , SDL_GPU_BLENDFACTOR_SRC_ALPHA_SATURATE
}
enum SDL_GPUBlendOp {
SDL_GPU_BLENDOP_INVALID , SDL_GPU_BLENDOP_ADD , SDL_GPU_BLENDOP_SUBTRACT , SDL_GPU_BLENDOP_REVERSE_SUBTRACT ,
SDL_GPU_BLENDOP_MIN , SDL_GPU_BLENDOP_MAX
}
enum SDL_GPUCompareOp {
SDL_GPU_COMPAREOP_INVALID , SDL_GPU_COMPAREOP_NEVER , SDL_GPU_COMPAREOP_LESS , SDL_GPU_COMPAREOP_EQUAL ,
SDL_GPU_COMPAREOP_LESS_OR_EQUAL , SDL_GPU_COMPAREOP_GREATER , SDL_GPU_COMPAREOP_NOT_EQUAL , SDL_GPU_COMPAREOP_GREATER_OR_EQUAL ,
SDL_GPU_COMPAREOP_ALWAYS
}
enum SDL_GPUCubeMapFace {
SDL_GPU_CUBEMAPFACE_POSITIVEX , SDL_GPU_CUBEMAPFACE_NEGATIVEX , SDL_GPU_CUBEMAPFACE_POSITIVEY , SDL_GPU_CUBEMAPFACE_NEGATIVEY ,
SDL_GPU_CUBEMAPFACE_POSITIVEZ , SDL_GPU_CUBEMAPFACE_NEGATIVEZ
}
enum SDL_GPUCullMode { SDL_GPU_CULLMODE_NONE , SDL_GPU_CULLMODE_FRONT , SDL_GPU_CULLMODE_BACK }
enum SDL_GPUFillMode { SDL_GPU_FILLMODE_FILL , SDL_GPU_FILLMODE_LINE }
enum SDL_GPUFilter { SDL_GPU_FILTER_NEAREST , SDL_GPU_FILTER_LINEAR }
enum SDL_GPUFrontFace { SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE , SDL_GPU_FRONTFACE_CLOCKWISE }
enum SDL_GPUIndexElementSize { SDL_GPU_INDEXELEMENTSIZE_16BIT , SDL_GPU_INDEXELEMENTSIZE_32BIT }
enum SDL_GPULoadOp { SDL_GPU_LOADOP_LOAD , SDL_GPU_LOADOP_CLEAR , SDL_GPU_LOADOP_DONT_CARE }
enum SDL_GPUPresentMode { SDL_GPU_PRESENTMODE_VSYNC , SDL_GPU_PRESENTMODE_IMMEDIATE , SDL_GPU_PRESENTMODE_MAILBOX }
enum SDL_GPUPrimitiveType {
SDL_GPU_PRIMITIVETYPE_TRIANGLELIST , SDL_GPU_PRIMITIVETYPE_TRIANGLESTRIP , SDL_GPU_PRIMITIVETYPE_LINELIST , SDL_GPU_PRIMITIVETYPE_LINESTRIP ,
SDL_GPU_PRIMITIVETYPE_POINTLIST
}
enum SDL_GPUSampleCount { SDL_GPU_SAMPLECOUNT_1 , SDL_GPU_SAMPLECOUNT_2 , SDL_GPU_SAMPLECOUNT_4 , SDL_GPU_SAMPLECOUNT_8 }
enum SDL_GPUSamplerAddressMode { SDL_GPU_SAMPLERADDRESSMODE_REPEAT , SDL_GPU_SAMPLERADDRESSMODE_MIRRORED_REPEAT , SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE }
enum SDL_GPUSamplerMipmapMode { SDL_GPU_SAMPLERMIPMAPMODE_NEAREST , SDL_GPU_SAMPLERMIPMAPMODE_LINEAR }
enum SDL_GPUShaderStage { SDL_GPU_SHADERSTAGE_VERTEX , SDL_GPU_SHADERSTAGE_FRAGMENT }
enum SDL_GPUStencilOp {
SDL_GPU_STENCILOP_INVALID , SDL_GPU_STENCILOP_KEEP , SDL_GPU_STENCILOP_ZERO , SDL_GPU_STENCILOP_REPLACE ,
SDL_GPU_STENCILOP_INCREMENT_AND_CLAMP , SDL_GPU_STENCILOP_DECREMENT_AND_CLAMP , SDL_GPU_STENCILOP_INVERT , SDL_GPU_STENCILOP_INCREMENT_AND_WRAP ,
SDL_GPU_STENCILOP_DECREMENT_AND_WRAP
}
enum SDL_GPUStoreOp { SDL_GPU_STOREOP_STORE , SDL_GPU_STOREOP_DONT_CARE , SDL_GPU_STOREOP_RESOLVE , SDL_GPU_STOREOP_RESOLVE_AND_STORE }
enum SDL_GPUSwapchainComposition { SDL_GPU_SWAPCHAINCOMPOSITION_SDR , SDL_GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR , SDL_GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR , SDL_GPU_SWAPCHAINCOMPOSITION_HDR10_ST2084 }
enum SDL_GPUTextureFormat {
SDL_GPU_TEXTUREFORMAT_INVALID , SDL_GPU_TEXTUREFORMAT_A8_UNORM , SDL_GPU_TEXTUREFORMAT_R8_UNORM , SDL_GPU_TEXTUREFORMAT_R8G8_UNORM ,
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM , SDL_GPU_TEXTUREFORMAT_R16_UNORM , SDL_GPU_TEXTUREFORMAT_R16G16_UNORM , SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM ,
SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM , SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM , SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM , SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM ,
SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM , SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM , SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM , SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM ,
SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM , SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM , SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM , SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT ,
SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT , SDL_GPU_TEXTUREFORMAT_R8_SNORM , SDL_GPU_TEXTUREFORMAT_R8G8_SNORM , SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM ,
SDL_GPU_TEXTUREFORMAT_R16_SNORM , SDL_GPU_TEXTUREFORMAT_R16G16_SNORM , SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM , SDL_GPU_TEXTUREFORMAT_R16_FLOAT ,
SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT , SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT , SDL_GPU_TEXTUREFORMAT_R32_FLOAT , SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT ,
SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT , SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT , SDL_GPU_TEXTUREFORMAT_R8_UINT , SDL_GPU_TEXTUREFORMAT_R8G8_UINT ,
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT , SDL_GPU_TEXTUREFORMAT_R16_UINT , SDL_GPU_TEXTUREFORMAT_R16G16_UINT , SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT ,
SDL_GPU_TEXTUREFORMAT_R32_UINT , SDL_GPU_TEXTUREFORMAT_R32G32_UINT , SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT , SDL_GPU_TEXTUREFORMAT_R8_INT ,
SDL_GPU_TEXTUREFORMAT_R8G8_INT , SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT , SDL_GPU_TEXTUREFORMAT_R16_INT , SDL_GPU_TEXTUREFORMAT_R16G16_INT ,
SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT , SDL_GPU_TEXTUREFORMAT_R32_INT , SDL_GPU_TEXTUREFORMAT_R32G32_INT , SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT ,
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB ,
SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_D16_UNORM , SDL_GPU_TEXTUREFORMAT_D24_UNORM ,
SDL_GPU_TEXTUREFORMAT_D32_FLOAT , SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT , SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT , SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM ,
SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM ,
SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM ,
SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM ,
SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM , SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB ,
SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB ,
SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB ,
SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB , SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT ,
SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT ,
SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT ,
SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT , SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT ,
SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT
}
enum SDL_GPUTextureType {
SDL_GPU_TEXTURETYPE_2D , SDL_GPU_TEXTURETYPE_2D_ARRAY , SDL_GPU_TEXTURETYPE_3D , SDL_GPU_TEXTURETYPE_CUBE ,
SDL_GPU_TEXTURETYPE_CUBE_ARRAY
}
enum SDL_GPUTransferBufferUsage { SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD , SDL_GPU_TRANSFERBUFFERUSAGE_DOWNLOAD }
enum SDL_GPUVertexElementFormat {
SDL_GPU_VERTEXELEMENTFORMAT_INVALID , SDL_GPU_VERTEXELEMENTFORMAT_INT , SDL_GPU_VERTEXELEMENTFORMAT_INT2 , SDL_GPU_VERTEXELEMENTFORMAT_INT3 ,
SDL_GPU_VERTEXELEMENTFORMAT_INT4 , SDL_GPU_VERTEXELEMENTFORMAT_UINT , SDL_GPU_VERTEXELEMENTFORMAT_UINT2 , SDL_GPU_VERTEXELEMENTFORMAT_UINT3 ,
SDL_GPU_VERTEXELEMENTFORMAT_UINT4 , SDL_GPU_VERTEXELEMENTFORMAT_FLOAT , SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2 , SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3 ,
SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4 , SDL_GPU_VERTEXELEMENTFORMAT_BYTE2 , SDL_GPU_VERTEXELEMENTFORMAT_BYTE4 , SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2 ,
SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4 , SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM , SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM , SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM ,
SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM , SDL_GPU_VERTEXELEMENTFORMAT_SHORT2 , SDL_GPU_VERTEXELEMENTFORMAT_SHORT4 , SDL_GPU_VERTEXELEMENTFORMAT_USHORT2 ,
SDL_GPU_VERTEXELEMENTFORMAT_USHORT4 , SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM , SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM , SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM ,
SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM , SDL_GPU_VERTEXELEMENTFORMAT_HALF2 , SDL_GPU_VERTEXELEMENTFORMAT_HALF4
}
enum SDL_GPUVertexInputRate { SDL_GPU_VERTEXINPUTRATE_VERTEX , SDL_GPU_VERTEXINPUTRATE_INSTANCE }
Functions
SDL_DECLSPEC SDL_GPUCommandBuffer *SDLCALL SDL_AcquireGPUCommandBuffer (SDL_GPUDevice *device)
SDL_DECLSPEC bool SDLCALL SDL_AcquireGPUSwapchainTexture (SDL_GPUCommandBuffer *command_buffer, SDL_Window *window, SDL_GPUTexture **swapchain_texture, Uint32 *swapchain_texture_width, Uint32 *swapchain_texture_height)
SDL_DECLSPEC SDL_GPUComputePass *SDLCALL SDL_BeginGPUComputePass (SDL_GPUCommandBuffer *command_buffer, const SDL_GPUStorageTextureReadWriteBinding *storage_texture_bindings, Uint32 num_storage_texture_bindings, const SDL_GPUStorageBufferReadWriteBinding *storage_buffer_bindings, Uint32 num_storage_buffer_bindings)
SDL_DECLSPEC SDL_GPUCopyPass *SDLCALL SDL_BeginGPUCopyPass (SDL_GPUCommandBuffer *command_buffer)
SDL_DECLSPEC SDL_GPURenderPass *SDLCALL SDL_BeginGPURenderPass (SDL_GPUCommandBuffer *command_buffer, const SDL_GPUColorTargetInfo *color_target_infos, Uint32 num_color_targets, const SDL_GPUDepthStencilTargetInfo *depth_stencil_target_info)
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputePipeline (SDL_GPUComputePass *compute_pass, SDL_GPUComputePipeline *compute_pipeline)
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputeSamplers (SDL_GPUComputePass *compute_pass, Uint32 first_slot, const SDL_GPUTextureSamplerBinding *texture_sampler_bindings, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputeStorageBuffers (SDL_GPUComputePass *compute_pass, Uint32 first_slot, SDL_GPUBuffer *const *storage_buffers, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputeStorageTextures (SDL_GPUComputePass *compute_pass, Uint32 first_slot, SDL_GPUTexture *const *storage_textures, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUFragmentSamplers (SDL_GPURenderPass *render_pass, Uint32 first_slot, const SDL_GPUTextureSamplerBinding *texture_sampler_bindings, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUFragmentStorageBuffers (SDL_GPURenderPass *render_pass, Uint32 first_slot, SDL_GPUBuffer *const *storage_buffers, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUFragmentStorageTextures (SDL_GPURenderPass *render_pass, Uint32 first_slot, SDL_GPUTexture *const *storage_textures, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUGraphicsPipeline (SDL_GPURenderPass *render_pass, SDL_GPUGraphicsPipeline *graphics_pipeline)
SDL_DECLSPEC void SDLCALL SDL_BindGPUIndexBuffer (SDL_GPURenderPass *render_pass, const SDL_GPUBufferBinding *binding, SDL_GPUIndexElementSize index_element_size)
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexBuffers (SDL_GPURenderPass *render_pass, Uint32 first_slot, const SDL_GPUBufferBinding *bindings, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexSamplers (SDL_GPURenderPass *render_pass, Uint32 first_slot, const SDL_GPUTextureSamplerBinding *texture_sampler_bindings, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexStorageBuffers (SDL_GPURenderPass *render_pass, Uint32 first_slot, SDL_GPUBuffer *const *storage_buffers, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexStorageTextures (SDL_GPURenderPass *render_pass, Uint32 first_slot, SDL_GPUTexture *const *storage_textures, Uint32 num_bindings)
SDL_DECLSPEC void SDLCALL SDL_BlitGPUTexture (SDL_GPUCommandBuffer *command_buffer, const SDL_GPUBlitInfo *info)
SDL_DECLSPEC Uint32 SDLCALL SDL_CalculateGPUTextureFormatSize (SDL_GPUTextureFormat format, Uint32 width, Uint32 height, Uint32 depth_or_layer_count)
SDL_DECLSPEC bool SDLCALL SDL_CancelGPUCommandBuffer (SDL_GPUCommandBuffer *command_buffer)
SDL_DECLSPEC bool SDLCALL SDL_ClaimWindowForGPUDevice (SDL_GPUDevice *device, SDL_Window *window)
SDL_DECLSPEC void SDLCALL SDL_CopyGPUBufferToBuffer (SDL_GPUCopyPass *copy_pass, const SDL_GPUBufferLocation *source, const SDL_GPUBufferLocation *destination, Uint32 size, bool cycle)
SDL_DECLSPEC void SDLCALL SDL_CopyGPUTextureToTexture (SDL_GPUCopyPass *copy_pass, const SDL_GPUTextureLocation *source, const SDL_GPUTextureLocation *destination, Uint32 w, Uint32 h, Uint32 d, bool cycle)
SDL_DECLSPEC SDL_GPUBuffer *SDLCALL SDL_CreateGPUBuffer (SDL_GPUDevice *device, const SDL_GPUBufferCreateInfo *createinfo)
SDL_DECLSPEC SDL_GPUComputePipeline *SDLCALL SDL_CreateGPUComputePipeline (SDL_GPUDevice *device, const SDL_GPUComputePipelineCreateInfo *createinfo)
SDL_DECLSPEC SDL_GPUDevice *SDLCALL SDL_CreateGPUDevice (SDL_GPUShaderFormat format_flags, bool debug_mode, const char *name)
SDL_DECLSPEC SDL_GPUDevice *SDLCALL SDL_CreateGPUDeviceWithProperties (SDL_PropertiesID props)
SDL_DECLSPEC SDL_GPUGraphicsPipeline *SDLCALL SDL_CreateGPUGraphicsPipeline (SDL_GPUDevice *device, const SDL_GPUGraphicsPipelineCreateInfo *createinfo)
SDL_DECLSPEC SDL_GPUSampler *SDLCALL SDL_CreateGPUSampler (SDL_GPUDevice *device, const SDL_GPUSamplerCreateInfo *createinfo)
SDL_DECLSPEC SDL_GPUShader *SDLCALL SDL_CreateGPUShader (SDL_GPUDevice *device, const SDL_GPUShaderCreateInfo *createinfo)
SDL_DECLSPEC SDL_GPUTexture *SDLCALL SDL_CreateGPUTexture (SDL_GPUDevice *device, const SDL_GPUTextureCreateInfo *createinfo)
SDL_DECLSPEC SDL_GPUTransferBuffer *SDLCALL SDL_CreateGPUTransferBuffer (SDL_GPUDevice *device, const SDL_GPUTransferBufferCreateInfo *createinfo)
SDL_DECLSPEC void SDLCALL SDL_DestroyGPUDevice (SDL_GPUDevice *device)
SDL_DECLSPEC void SDLCALL SDL_DispatchGPUCompute (SDL_GPUComputePass *compute_pass, Uint32 groupcount_x, Uint32 groupcount_y, Uint32 groupcount_z)
SDL_DECLSPEC void SDLCALL SDL_DispatchGPUComputeIndirect (SDL_GPUComputePass *compute_pass, SDL_GPUBuffer *buffer, Uint32 offset)
SDL_DECLSPEC void SDLCALL SDL_DownloadFromGPUBuffer (SDL_GPUCopyPass *copy_pass, const SDL_GPUBufferRegion *source, const SDL_GPUTransferBufferLocation *destination)
SDL_DECLSPEC void SDLCALL SDL_DownloadFromGPUTexture (SDL_GPUCopyPass *copy_pass, const SDL_GPUTextureRegion *source, const SDL_GPUTextureTransferInfo *destination)
SDL_DECLSPEC void SDLCALL SDL_DrawGPUIndexedPrimitives (SDL_GPURenderPass *render_pass, Uint32 num_indices, Uint32 num_instances, Uint32 first_index, Sint32 vertex_offset, Uint32 first_instance)
SDL_DECLSPEC void SDLCALL SDL_DrawGPUIndexedPrimitivesIndirect (SDL_GPURenderPass *render_pass, SDL_GPUBuffer *buffer, Uint32 offset, Uint32 draw_count)
SDL_DECLSPEC void SDLCALL SDL_DrawGPUPrimitives (SDL_GPURenderPass *render_pass, Uint32 num_vertices, Uint32 num_instances, Uint32 first_vertex, Uint32 first_instance)
SDL_DECLSPEC void SDLCALL SDL_DrawGPUPrimitivesIndirect (SDL_GPURenderPass *render_pass, SDL_GPUBuffer *buffer, Uint32 offset, Uint32 draw_count)
SDL_DECLSPEC void SDLCALL SDL_EndGPUComputePass (SDL_GPUComputePass *compute_pass)
SDL_DECLSPEC void SDLCALL SDL_EndGPUCopyPass (SDL_GPUCopyPass *copy_pass)
SDL_DECLSPEC void SDLCALL SDL_EndGPURenderPass (SDL_GPURenderPass *render_pass)
SDL_DECLSPEC void SDLCALL SDL_GenerateMipmapsForGPUTexture (SDL_GPUCommandBuffer *command_buffer, SDL_GPUTexture *texture)
SDL_DECLSPEC const char *SDLCALL SDL_GetGPUDeviceDriver (SDL_GPUDevice *device)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetGPUDeviceProperties (SDL_GPUDevice *device)
SDL_DECLSPEC const char *SDLCALL SDL_GetGPUDriver (int index)
SDL_DECLSPEC SDL_GPUShaderFormat SDLCALL SDL_GetGPUShaderFormats (SDL_GPUDevice *device)
SDL_DECLSPEC SDL_GPUTextureFormat SDLCALL SDL_GetGPUSwapchainTextureFormat (SDL_GPUDevice *device, SDL_Window *window)
SDL_DECLSPEC int SDLCALL SDL_GetNumGPUDrivers (void)
SDL_DECLSPEC bool SDLCALL SDL_GPUSupportsProperties (SDL_PropertiesID props)
SDL_DECLSPEC bool SDLCALL SDL_GPUSupportsShaderFormats (SDL_GPUShaderFormat format_flags, const char *name)
SDL_DECLSPEC Uint32 SDLCALL SDL_GPUTextureFormatTexelBlockSize (SDL_GPUTextureFormat format)
SDL_DECLSPEC bool SDLCALL SDL_GPUTextureSupportsFormat (SDL_GPUDevice *device, SDL_GPUTextureFormat format, SDL_GPUTextureType type, SDL_GPUTextureUsageFlags usage)
SDL_DECLSPEC bool SDLCALL SDL_GPUTextureSupportsSampleCount (SDL_GPUDevice *device, SDL_GPUTextureFormat format, SDL_GPUSampleCount sample_count)
SDL_DECLSPEC void SDLCALL SDL_InsertGPUDebugLabel (SDL_GPUCommandBuffer *command_buffer, const char *text)
SDL_DECLSPEC void *SDLCALL SDL_MapGPUTransferBuffer (SDL_GPUDevice *device, SDL_GPUTransferBuffer *transfer_buffer, bool cycle)
SDL_DECLSPEC void SDLCALL SDL_PopGPUDebugGroup (SDL_GPUCommandBuffer *command_buffer)
SDL_DECLSPEC void SDLCALL SDL_PushGPUComputeUniformData (SDL_GPUCommandBuffer *command_buffer, Uint32 slot_index, const void *data, Uint32 length)
SDL_DECLSPEC void SDLCALL SDL_PushGPUDebugGroup (SDL_GPUCommandBuffer *command_buffer, const char *name)
SDL_DECLSPEC void SDLCALL SDL_PushGPUFragmentUniformData (SDL_GPUCommandBuffer *command_buffer, Uint32 slot_index, const void *data, Uint32 length)
SDL_DECLSPEC void SDLCALL SDL_PushGPUVertexUniformData (SDL_GPUCommandBuffer *command_buffer, Uint32 slot_index, const void *data, Uint32 length)
SDL_DECLSPEC bool SDLCALL SDL_QueryGPUFence (SDL_GPUDevice *device, SDL_GPUFence *fence)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUBuffer (SDL_GPUDevice *device, SDL_GPUBuffer *buffer)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUComputePipeline (SDL_GPUDevice *device, SDL_GPUComputePipeline *compute_pipeline)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUFence (SDL_GPUDevice *device, SDL_GPUFence *fence)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUGraphicsPipeline (SDL_GPUDevice *device, SDL_GPUGraphicsPipeline *graphics_pipeline)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUSampler (SDL_GPUDevice *device, SDL_GPUSampler *sampler)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUShader (SDL_GPUDevice *device, SDL_GPUShader *shader)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUTexture (SDL_GPUDevice *device, SDL_GPUTexture *texture)
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUTransferBuffer (SDL_GPUDevice *device, SDL_GPUTransferBuffer *transfer_buffer)
SDL_DECLSPEC void SDLCALL SDL_ReleaseWindowFromGPUDevice (SDL_GPUDevice *device, SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_SetGPUAllowedFramesInFlight (SDL_GPUDevice *device, Uint32 allowed_frames_in_flight)
SDL_DECLSPEC void SDLCALL SDL_SetGPUBlendConstants (SDL_GPURenderPass *render_pass, SDL_FColor blend_constants)
SDL_DECLSPEC void SDLCALL SDL_SetGPUBufferName (SDL_GPUDevice *device, SDL_GPUBuffer *buffer, const char *text)
SDL_DECLSPEC void SDLCALL SDL_SetGPUScissor (SDL_GPURenderPass *render_pass, const SDL_Rect *scissor)
SDL_DECLSPEC void SDLCALL SDL_SetGPUStencilReference (SDL_GPURenderPass *render_pass, Uint8 reference)
SDL_DECLSPEC bool SDLCALL SDL_SetGPUSwapchainParameters (SDL_GPUDevice *device, SDL_Window *window, SDL_GPUSwapchainComposition swapchain_composition, SDL_GPUPresentMode present_mode)
SDL_DECLSPEC void SDLCALL SDL_SetGPUTextureName (SDL_GPUDevice *device, SDL_GPUTexture *texture, const char *text)
SDL_DECLSPEC void SDLCALL SDL_SetGPUViewport (SDL_GPURenderPass *render_pass, const SDL_GPUViewport *viewport)
SDL_DECLSPEC bool SDLCALL SDL_SubmitGPUCommandBuffer (SDL_GPUCommandBuffer *command_buffer)
SDL_DECLSPEC SDL_GPUFence *SDLCALL SDL_SubmitGPUCommandBufferAndAcquireFence (SDL_GPUCommandBuffer *command_buffer)
SDL_DECLSPEC void SDLCALL SDL_UnmapGPUTransferBuffer (SDL_GPUDevice *device, SDL_GPUTransferBuffer *transfer_buffer)
SDL_DECLSPEC void SDLCALL SDL_UploadToGPUBuffer (SDL_GPUCopyPass *copy_pass, const SDL_GPUTransferBufferLocation *source, const SDL_GPUBufferRegion *destination, bool cycle)
SDL_DECLSPEC void SDLCALL SDL_UploadToGPUTexture (SDL_GPUCopyPass *copy_pass, const SDL_GPUTextureTransferInfo *source, const SDL_GPUTextureRegion *destination, bool cycle)
SDL_DECLSPEC bool SDLCALL SDL_WaitAndAcquireGPUSwapchainTexture (SDL_GPUCommandBuffer *command_buffer, SDL_Window *window, SDL_GPUTexture **swapchain_texture, Uint32 *swapchain_texture_width, Uint32 *swapchain_texture_height)
SDL_DECLSPEC bool SDLCALL SDL_WaitForGPUFences (SDL_GPUDevice *device, bool wait_all, SDL_GPUFence *const *fences, Uint32 num_fences)
SDL_DECLSPEC bool SDLCALL SDL_WaitForGPUIdle (SDL_GPUDevice *device)
SDL_DECLSPEC bool SDLCALL SDL_WaitForGPUSwapchain (SDL_GPUDevice *device, SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_WindowSupportsGPUPresentMode (SDL_GPUDevice *device, SDL_Window *window, SDL_GPUPresentMode present_mode)
SDL_DECLSPEC bool SDLCALL SDL_WindowSupportsGPUSwapchainComposition (SDL_GPUDevice *device, SDL_Window *window, SDL_GPUSwapchainComposition swapchain_composition)
Macro Definition Documentation
SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_READ
#define SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_READ (1u << 4)
Buffer supports storage reads in the compute stage.
SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_WRITE
#define SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_WRITE (1u << 5)
Buffer supports storage writes in the compute stage.
SDL_GPU_BUFFERUSAGE_GRAPHICS_STORAGE_READ
#define SDL_GPU_BUFFERUSAGE_GRAPHICS_STORAGE_READ (1u << 3)
Buffer supports storage reads in graphics stages.
SDL_GPU_BUFFERUSAGE_INDEX
#define SDL_GPU_BUFFERUSAGE_INDEX (1u << 1)
Buffer is an index buffer.
SDL_GPU_BUFFERUSAGE_INDIRECT
#define SDL_GPU_BUFFERUSAGE_INDIRECT (1u << 2)
Buffer is an indirect buffer.
SDL_GPU_BUFFERUSAGE_VERTEX
#define SDL_GPU_BUFFERUSAGE_VERTEX (1u << 0)
Buffer is a vertex buffer.
SDL_GPU_COLORCOMPONENT_A
#define SDL_GPU_COLORCOMPONENT_A (1u << 3)
the alpha component
SDL_GPU_COLORCOMPONENT_B
#define SDL_GPU_COLORCOMPONENT_B (1u << 2)
the blue component
SDL_GPU_COLORCOMPONENT_G
#define SDL_GPU_COLORCOMPONENT_G (1u << 1)
the green component
SDL_GPU_COLORCOMPONENT_R
#define SDL_GPU_COLORCOMPONENT_R (1u << 0)
the red component
SDL_GPU_SHADERFORMAT_DXBC
#define SDL_GPU_SHADERFORMAT_DXBC (1u << 2)
DXBC SM5_1 shaders for D3D12.
Referenced by SDL_GPU_FillProperties().
SDL_GPU_SHADERFORMAT_DXIL
#define SDL_GPU_SHADERFORMAT_DXIL (1u << 3)
DXIL SM6_0 shaders for D3D12.
Referenced by SDL_CreateGPURenderer(), and SDL_GPU_FillProperties().
SDL_GPU_SHADERFORMAT_INVALID
#define SDL_GPU_SHADERFORMAT_INVALID 0
Referenced by SDL_CreateGPUComputePipeline(), SDL_CreateGPUShader(), and SDL_GetGPUShaderFormats().
SDL_GPU_SHADERFORMAT_METALLIB
#define SDL_GPU_SHADERFORMAT_METALLIB (1u << 5)
Precompiled metallib shaders for Metal.
Referenced by SDL_GPU_FillProperties().
SDL_GPU_SHADERFORMAT_MSL
#define SDL_GPU_SHADERFORMAT_MSL (1u << 4)
MSL shaders for Metal.
Referenced by SDL_CreateGPURenderer(), and SDL_GPU_FillProperties().
SDL_GPU_SHADERFORMAT_PRIVATE
#define SDL_GPU_SHADERFORMAT_PRIVATE (1u << 0)
Shaders for NDA'd platforms.
Referenced by SDL_GPU_FillProperties().
SDL_GPU_SHADERFORMAT_SPIRV
#define SDL_GPU_SHADERFORMAT_SPIRV (1u << 1)
SPIR-V shaders for Vulkan.
Referenced by SDL_CreateGPURenderer(), and SDL_GPU_FillProperties().
SDL_GPU_TEXTUREUSAGE_COLOR_TARGET
#define SDL_GPU_TEXTUREUSAGE_COLOR_TARGET (1u << 1)
Texture is a color render target.
Referenced by SDL_BeginGPURenderPass(), SDL_BlitGPUTexture(), SDL_CreateGPUGraphicsPipeline(), and SDL_GenerateMipmapsForGPUTexture().
SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ
#define SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ (1u << 4)
Texture supports storage reads in the compute stage.
Referenced by SDL_CreateGPUTexture().
SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE
#define SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE (1u << 6)
Texture supports reads and writes in the same compute shader. This is NOT equivalent to READ | WRITE.
Referenced by SDL_BeginGPUComputePass(), and SDL_GPUTextureSupportsFormat().
SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE
#define SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE (1u << 5)
Texture supports storage writes in the compute stage.
Referenced by SDL_BeginGPUComputePass(), SDL_CreateGPUTexture(), and SDL_GPUTextureSupportsFormat().
SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET
#define SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET (1u << 2)
Texture is a depth stencil target.
Referenced by SDL_BeginGPURenderPass(), SDL_CreateGPUGraphicsPipeline(), and SDL_CreateGPUTexture().
SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ
#define SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ (1u << 3)
Texture supports storage reads in graphics stages.
Referenced by SDL_CreateGPUTexture().
SDL_GPU_TEXTUREUSAGE_SAMPLER
#define SDL_GPU_TEXTUREUSAGE_SAMPLER (1u << 0)
Texture supports sampling.
Referenced by SDL_BlitGPUTexture(), SDL_CreateGPUTexture(), and SDL_GenerateMipmapsForGPUTexture().
SDL_PROP_GPU_BUFFER_CREATE_NAME_STRING
#define SDL_PROP_GPU_BUFFER_CREATE_NAME_STRING "SDL.gpu.buffer.create.name"
Referenced by SDL_CreateGPUBuffer().
SDL_PROP_GPU_COMPUTEPIPELINE_CREATE_NAME_STRING
#define SDL_PROP_GPU_COMPUTEPIPELINE_CREATE_NAME_STRING "SDL.gpu.computepipeline.create.name"
SDL_PROP_GPU_DEVICE_CREATE_D3D12_SEMANTIC_NAME_STRING
#define SDL_PROP_GPU_DEVICE_CREATE_D3D12_SEMANTIC_NAME_STRING "SDL.gpu.device.create.d3d12.semantic"
SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOLEAN "SDL.gpu.device.create.debugmode"
Referenced by SDL_CreateGPUDeviceWithProperties(), and SDL_GPU_FillProperties().
SDL_PROP_GPU_DEVICE_CREATE_NAME_STRING
#define SDL_PROP_GPU_DEVICE_CREATE_NAME_STRING "SDL.gpu.device.create.name"
Referenced by SDL_GPU_FillProperties(), and SDL_GPUSelectBackend().
SDL_PROP_GPU_DEVICE_CREATE_PREFERLOWPOWER_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_PREFERLOWPOWER_BOOLEAN "SDL.gpu.device.create.preferlowpower"
Referenced by SDL_CreateGPUDeviceWithProperties().
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXBC_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXBC_BOOLEAN "SDL.gpu.device.create.shaders.dxbc"
Referenced by SDL_GPU_FillProperties().
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXIL_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXIL_BOOLEAN "SDL.gpu.device.create.shaders.dxil"
Referenced by SDL_GPU_FillProperties().
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_METALLIB_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_METALLIB_BOOLEAN "SDL.gpu.device.create.shaders.metallib"
Referenced by SDL_GPU_FillProperties().
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_MSL_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_MSL_BOOLEAN "SDL.gpu.device.create.shaders.msl"
Referenced by SDL_GPU_FillProperties().
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_PRIVATE_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_PRIVATE_BOOLEAN "SDL.gpu.device.create.shaders.private"
Referenced by SDL_GPU_FillProperties().
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_SPIRV_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_SHADERS_SPIRV_BOOLEAN "SDL.gpu.device.create.shaders.spirv"
Referenced by SDL_GPU_FillProperties().
SDL_PROP_GPU_DEVICE_CREATE_VERBOSE_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_VERBOSE_BOOLEAN "SDL.gpu.device.create.verbose"
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DEPTHCLAMP_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DEPTHCLAMP_BOOLEAN "SDL.gpu.device.create.vulkan.depthclamp"
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DRAWINDIRECTFIRST_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DRAWINDIRECTFIRST_BOOLEAN "SDL.gpu.device.create.vulkan.drawindirectfirstinstance"
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SAMPLERANISOTROPY_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SAMPLERANISOTROPY_BOOLEAN "SDL.gpu.device.create.vulkan.sampleranisotropy"
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SHADERCLIPDISTANCE_BOOLEAN
#define SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SHADERCLIPDISTANCE_BOOLEAN "SDL.gpu.device.create.vulkan.shaderclipdistance"
SDL_PROP_GPU_DEVICE_DRIVER_INFO_STRING
#define SDL_PROP_GPU_DEVICE_DRIVER_INFO_STRING "SDL.gpu.device.driver_info"
SDL_PROP_GPU_DEVICE_DRIVER_NAME_STRING
#define SDL_PROP_GPU_DEVICE_DRIVER_NAME_STRING "SDL.gpu.device.driver_name"
SDL_PROP_GPU_DEVICE_DRIVER_VERSION_STRING
#define SDL_PROP_GPU_DEVICE_DRIVER_VERSION_STRING "SDL.gpu.device.driver_version"
SDL_PROP_GPU_DEVICE_NAME_STRING
#define SDL_PROP_GPU_DEVICE_NAME_STRING "SDL.gpu.device.name"
SDL_PROP_GPU_GRAPHICSPIPELINE_CREATE_NAME_STRING
#define SDL_PROP_GPU_GRAPHICSPIPELINE_CREATE_NAME_STRING "SDL.gpu.graphicspipeline.create.name"
SDL_PROP_GPU_SAMPLER_CREATE_NAME_STRING
#define SDL_PROP_GPU_SAMPLER_CREATE_NAME_STRING "SDL.gpu.sampler.create.name"
SDL_PROP_GPU_SHADER_CREATE_NAME_STRING
#define SDL_PROP_GPU_SHADER_CREATE_NAME_STRING "SDL.gpu.shader.create.name"
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_A_FLOAT
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_A_FLOAT "SDL.gpu.texture.create.d3d12.clear.a"
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_B_FLOAT
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_B_FLOAT "SDL.gpu.texture.create.d3d12.clear.b"
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_DEPTH_FLOAT
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_DEPTH_FLOAT "SDL.gpu.texture.create.d3d12.clear.depth"
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_G_FLOAT
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_G_FLOAT "SDL.gpu.texture.create.d3d12.clear.g"
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_R_FLOAT
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_R_FLOAT "SDL.gpu.texture.create.d3d12.clear.r"
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_NUMBER
#define SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_NUMBER "SDL.gpu.texture.create.d3d12.clear.stencil"
SDL_PROP_GPU_TEXTURE_CREATE_NAME_STRING
#define SDL_PROP_GPU_TEXTURE_CREATE_NAME_STRING "SDL.gpu.texture.create.name"
SDL_PROP_GPU_TRANSFERBUFFER_CREATE_NAME_STRING
#define SDL_PROP_GPU_TRANSFERBUFFER_CREATE_NAME_STRING "SDL.gpu.transferbuffer.create.name"
Referenced by SDL_CreateGPUTransferBuffer().
Typedef Documentation
SDL_GPUBlendFactor
typedef enum SDL_GPUBlendFactor SDL_GPUBlendFactor
Specifies a blending factor to be used when pixels in a render target are blended with existing pixels in the texture.
The source color is the value written by the fragment shader. The destination color is the value currently existing in the texture.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUBlendOp
typedef enum SDL_GPUBlendOp SDL_GPUBlendOp
Specifies the operator to be used when pixels in a render target are blended with existing pixels in the texture.
The source color is the value written by the fragment shader. The destination color is the value currently existing in the texture.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUBlitInfo
typedef struct SDL_GPUBlitInfo SDL_GPUBlitInfo
A structure containing parameters for a blit command.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BlitGPUTexture
SDL_GPUBlitRegion
typedef struct SDL_GPUBlitRegion SDL_GPUBlitRegion
A structure specifying a region of a texture used in the blit operation.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BlitGPUTexture
SDL_GPUBuffer
typedef struct SDL_GPUBuffer SDL_GPUBuffer
An opaque handle representing a buffer.
Used for vertices, indices, indirect draw commands, and general compute data.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUBuffer
SDL_UploadToGPUBuffer
SDL_DownloadFromGPUBuffer
SDL_CopyGPUBufferToBuffer
SDL_BindGPUVertexBuffers
SDL_BindGPUIndexBuffer
SDL_BindGPUVertexStorageBuffers
SDL_BindGPUFragmentStorageBuffers
SDL_DrawGPUPrimitivesIndirect
SDL_DrawGPUIndexedPrimitivesIndirect
SDL_BindGPUComputeStorageBuffers
SDL_DispatchGPUComputeIndirect
SDL_ReleaseGPUBuffer
SDL_GPUBufferBinding
typedef struct SDL_GPUBufferBinding SDL_GPUBufferBinding
A structure specifying parameters in a buffer binding call.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BindGPUVertexBuffers
SDL_BindGPUIndexBuffer
SDL_GPUBufferCreateInfo
typedef struct SDL_GPUBufferCreateInfo SDL_GPUBufferCreateInfo
A structure specifying the parameters of a buffer.
Usage flags can be bitwise OR'd together for combinations of usages. Note that certain combinations are invalid, for example VERTEX and INDEX.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUBuffer
SDL_GPUBufferUsageFlags
SDL_GPUBufferLocation
typedef struct SDL_GPUBufferLocation SDL_GPUBufferLocation
A structure specifying a location in a buffer.
Used when copying data between buffers.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CopyGPUBufferToBuffer
SDL_GPUBufferRegion
typedef struct SDL_GPUBufferRegion SDL_GPUBufferRegion
A structure specifying a region of a buffer.
Used when transferring data to or from buffers.
Since
This struct is available since SDL 3.2.0.
See also
SDL_UploadToGPUBuffer
SDL_DownloadFromGPUBuffer
SDL_GPUBufferUsageFlags
typedef Uint32 SDL_GPUBufferUsageFlags
Specifies how a buffer is intended to be used by the client.
A buffer must have at least one usage flag. Note that some usage flag combinations are invalid.
Unlike textures, READ | WRITE can be used for simultaneous read-write usage. The same data synchronization concerns as textures apply.
If you use a STORAGE flag, the data in the buffer must respect std140 layout conventions. In practical terms this means you must ensure that vec3 and vec4 fields are 16-byte aligned.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_CreateGPUBuffer
SDL_GPUColorComponentFlags
typedef Uint8 SDL_GPUColorComponentFlags
Specifies which color components are written in a graphics pipeline.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUColorTargetBlendState
typedef struct SDL_GPUColorTargetBlendState SDL_GPUColorTargetBlendState
A structure specifying the blend state of a color target.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUColorTargetDescription
SDL_GPUBlendFactor
SDL_GPUBlendOp
SDL_GPUColorComponentFlags
SDL_GPUColorTargetDescription
typedef struct SDL_GPUColorTargetDescription SDL_GPUColorTargetDescription
A structure specifying the parameters of color targets used in a graphics pipeline.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUGraphicsPipelineTargetInfo
SDL_GPUColorTargetInfo
typedef struct SDL_GPUColorTargetInfo SDL_GPUColorTargetInfo
A structure specifying the parameters of a color target used by a render pass.
The load_op field determines what is done with the texture at the beginning of the render pass.
LOAD: Loads the data currently in the texture. Not recommended for multisample textures as it requires significant memory bandwidth.
CLEAR: Clears the texture to a single color.
DONT_CARE: The driver will do whatever it wants with the texture memory. This is a good option if you know that every single pixel will be touched in the render pass.
The store_op field determines what is done with the color results of the render pass.
STORE: Stores the results of the render pass in the texture. Not recommended for multisample textures as it requires significant memory bandwidth.
DONT_CARE: The driver will do whatever it wants with the texture memory. This is often a good option for depth/stencil textures.
RESOLVE: Resolves a multisample texture into resolve_texture, which must have a sample count of 1. Then the driver may discard the multisample texture memory. This is the most performant method of resolving a multisample target.
RESOLVE_AND_STORE: Resolves a multisample texture into the resolve_texture, which must have a sample count of 1. Then the driver stores the multisample texture's contents. Not recommended as it requires significant memory bandwidth.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BeginGPURenderPass
SDL_GPUCommandBuffer
typedef struct SDL_GPUCommandBuffer SDL_GPUCommandBuffer
An opaque handle representing a command buffer.
Most state is managed via command buffers. When setting state using a command buffer, that state is local to the command buffer.
Commands only begin execution on the GPU once SDL_SubmitGPUCommandBuffer is called. Once the command buffer is submitted, it is no longer valid to use it.
Command buffers are executed in submission order. If you submit command buffer A and then command buffer B all commands in A will begin executing before any command in B begins executing.
In multi-threading scenarios, you should only access a command buffer on the thread you acquired it from.
Since
This struct is available since SDL 3.2.0.
See also
SDL_AcquireGPUCommandBuffer
SDL_SubmitGPUCommandBuffer
SDL_SubmitGPUCommandBufferAndAcquireFence
SDL_GPUCompareOp
typedef enum SDL_GPUCompareOp SDL_GPUCompareOp
Specifies a comparison operator for depth, stencil and sampler operations.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUComputePass
typedef struct SDL_GPUComputePass SDL_GPUComputePass
An opaque handle representing a compute pass.
This handle is transient and should not be held or referenced after SDL_EndGPUComputePass is called.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BeginGPUComputePass
SDL_EndGPUComputePass
SDL_GPUComputePipeline
typedef struct SDL_GPUComputePipeline SDL_GPUComputePipeline
An opaque handle representing a compute pipeline.
Used during compute passes.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUComputePipeline
SDL_BindGPUComputePipeline
SDL_ReleaseGPUComputePipeline
SDL_GPUComputePipelineCreateInfo
typedef struct SDL_GPUComputePipelineCreateInfo SDL_GPUComputePipelineCreateInfo
A structure specifying the parameters of a compute pipeline state.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUComputePipeline
SDL_GPUShaderFormat
SDL_GPUCopyPass
typedef struct SDL_GPUCopyPass SDL_GPUCopyPass
An opaque handle representing a copy pass.
This handle is transient and should not be held or referenced after SDL_EndGPUCopyPass is called.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BeginGPUCopyPass
SDL_EndGPUCopyPass
SDL_GPUCubeMapFace
typedef enum SDL_GPUCubeMapFace SDL_GPUCubeMapFace
Specifies the face of a cube map.
Can be passed in as the layer field in texture-related structs.
Since
This enum is available since SDL 3.2.0.
SDL_GPUCullMode
typedef enum SDL_GPUCullMode SDL_GPUCullMode
Specifies the facing direction in which triangle faces will be culled.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUDepthStencilState
typedef struct SDL_GPUDepthStencilState SDL_GPUDepthStencilState
A structure specifying the parameters of the graphics pipeline depth stencil state.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUGraphicsPipelineCreateInfo
SDL_GPUDepthStencilTargetInfo
typedef struct SDL_GPUDepthStencilTargetInfo SDL_GPUDepthStencilTargetInfo
A structure specifying the parameters of a depth-stencil target used by a render pass.
The load_op field determines what is done with the depth contents of the texture at the beginning of the render pass.
LOAD: Loads the depth values currently in the texture.
CLEAR: Clears the texture to a single depth.
DONT_CARE: The driver will do whatever it wants with the memory. This is a good option if you know that every single pixel will be touched in the render pass.
The store_op field determines what is done with the depth results of the render pass.
STORE: Stores the depth results in the texture.
DONT_CARE: The driver will do whatever it wants with the depth results. This is often a good option for depth/stencil textures that don't need to be reused again.
The stencil_load_op field determines what is done with the stencil contents of the texture at the beginning of the render pass.
LOAD: Loads the stencil values currently in the texture.
CLEAR: Clears the stencil values to a single value.
DONT_CARE: The driver will do whatever it wants with the memory. This is a good option if you know that every single pixel will be touched in the render pass.
The stencil_store_op field determines what is done with the stencil results of the render pass.
STORE: Stores the stencil results in the texture.
DONT_CARE: The driver will do whatever it wants with the stencil results. This is often a good option for depth/stencil textures that don't need to be reused again.
Note that depth/stencil targets do not support multisample resolves.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BeginGPURenderPass
SDL_GPUDevice
typedef struct SDL_GPUDevice SDL_GPUDevice
CategoryGPU
The GPU API offers a cross-platform way for apps to talk to modern graphics hardware. It offers both 3D graphics and compute support, in the style of Metal, Vulkan, and Direct3D 12.
A basic workflow might be something like this:
The app creates a GPU device with SDL_CreateGPUDevice(), and assigns it to a window with SDL_ClaimWindowForGPUDevice()–although strictly speaking you can render offscreen entirely, perhaps for image processing, and not use a window at all.
Next, the app prepares static data (things that are created once and used over and over). For example:
Shaders (programs that run on the GPU): use SDL_CreateGPUShader().
Vertex buffers (arrays of geometry data) and other rendering data: use SDL_CreateGPUBuffer() and SDL_UploadToGPUBuffer().
Textures (images): use SDL_CreateGPUTexture() and SDL_UploadToGPUTexture().
Samplers (how textures should be read from): use SDL_CreateGPUSampler().
Render pipelines (precalculated rendering state): use SDL_CreateGPUGraphicsPipeline()
To render, the app creates one or more command buffers, with SDL_AcquireGPUCommandBuffer(). Command buffers collect rendering instructions that will be submitted to the GPU in batch. Complex scenes can use multiple command buffers, maybe configured across multiple threads in parallel, as long as they are submitted in the correct order, but many apps will just need one command buffer per frame.
Rendering can happen to a texture (what other APIs call a "render target") or it can happen to the swapchain texture (which is just a special texture that represents a window's contents). The app can use SDL_WaitAndAcquireGPUSwapchainTexture() to render to the window.
Rendering actually happens in a Render Pass, which is encoded into a command buffer. One can encode multiple render passes (or alternate between render and compute passes) in a single command buffer, but many apps might simply need a single render pass in a single command buffer. Render Passes can render to up to four color textures and one depth texture simultaneously. If the set of textures being rendered to needs to change, the Render Pass must be ended and a new one must be begun.
The app calls SDL_BeginGPURenderPass(). Then it sets states it needs for each draw:
SDL_BindGPUGraphicsPipeline()
SDL_SetGPUViewport()
SDL_BindGPUVertexBuffers()
SDL_BindGPUVertexSamplers()
etc
Then, make the actual draw commands with these states:
SDL_DrawGPUPrimitives()
SDL_DrawGPUPrimitivesIndirect()
SDL_DrawGPUIndexedPrimitivesIndirect()
etc
After all the drawing commands for a pass are complete, the app should call SDL_EndGPURenderPass(). Once a render pass ends all render-related state is reset.
The app can begin new Render Passes and make new draws in the same command buffer until the entire scene is rendered.
Once all of the render commands for the scene are complete, the app calls SDL_SubmitGPUCommandBuffer() to send it to the GPU for processing.
If the app needs to read back data from texture or buffers, the API has an efficient way of doing this, provided that the app is willing to tolerate some latency. When the app uses SDL_DownloadFromGPUTexture() or SDL_DownloadFromGPUBuffer(), submitting the command buffer with SDL_SubmitGPUCommandBufferAndAcquireFence() will return a fence handle that the app can poll or wait on in a thread. Once the fence indicates that the command buffer is done processing, it is safe to read the downloaded data. Make sure to call SDL_ReleaseGPUFence() when done with the fence.
The API also has "compute" support. The app calls SDL_BeginGPUComputePass() with compute-writeable textures and/or buffers, which can be written to in a compute shader. Then it sets states it needs for the compute dispatches:
SDL_BindGPUComputePipeline()
SDL_BindGPUComputeStorageBuffers()
SDL_BindGPUComputeStorageTextures()
Then, dispatch compute work:
SDL_DispatchGPUCompute()
For advanced users, this opens up powerful GPU-driven workflows.
Graphics and compute pipelines require the use of shaders, which as mentioned above are small programs executed on the GPU. Each backend (Vulkan, Metal, D3D12) requires a different shader format. When the app creates the GPU device, the app lets the device know which shader formats the app can provide. It will then select the appropriate backend depending on the available shader formats and the backends available on the platform. When creating shaders, the app must provide the correct shader format for the selected backend. If you would like to learn more about why the API works this way, there is a detailed blog post explaining this situation.
It is optimal for apps to pre-compile the shader formats they might use, but for ease of use SDL provides a separate project, SDL_shadercross , for performing runtime shader cross-compilation. It also has a CLI interface for offline precompilation as well.
This is an extremely quick overview that leaves out several important details. Already, though, one can see that GPU programming can be quite complex! If you just need simple 2D graphics, the Render API is much easier to use but still hardware-accelerated. That said, even for 2D applications the performance benefits and expressiveness of the GPU API are significant.
The GPU API targets a feature set with a wide range of hardware support and ease of portability. It is designed so that the app won't have to branch itself by querying feature support. If you need cutting-edge features with limited hardware support, this API is probably not for you.
Examples demonstrating proper usage of this API can be found here
Performance considerations
Here are some basic tips for maximizing your rendering performance.
Beginning a new render pass is relatively expensive. Use as few render passes as you can.
Minimize the amount of state changes. For example, binding a pipeline is relatively cheap, but doing it hundreds of times when you don't need to will slow the performance significantly.
Perform your data uploads as early as possible in the frame.
Don't churn resources. Creating and releasing resources is expensive. It's better to create what you need up front and cache it.
Don't use uniform buffers for large amounts of data (more than a matrix or so). Use a storage buffer instead.
Use cycling correctly. There is a detailed explanation of cycling further below.
Use culling techniques to minimize pixel writes. The less writing the GPU has to do the better. Culling can be a very advanced topic but even simple culling techniques can boost performance significantly.
In general try to remember the golden rule of performance: doing things is more expensive than not doing things. Don't Touch The Driver!
FAQ
Question: When are you adding more advanced features, like ray tracing or mesh shaders?
Answer: We don't have immediate plans to add more bleeding-edge features, but we certainly might in the future, when these features prove worthwhile, and reasonable to implement across several platforms and underlying APIs. So while these things are not in the "never" category, they are definitely not "near future" items either.
Question: Why is my shader not working?
Answer: A common oversight when using shaders is not properly laying out the shader resources/registers correctly. The GPU API is very strict with how it wants resources to be laid out and it's difficult for the API to automatically validate shaders to see if they have a compatible layout. See the documentation for SDL_CreateGPUShader() and SDL_CreateGPUComputePipeline() for information on the expected layout.
Another common issue is not setting the correct number of samplers, textures, and buffers in SDL_GPUShaderCreateInfo. If possible use shader reflection to extract the required information from the shader automatically instead of manually filling in the struct's values.
Question: My application isn't performing very well. Is this the GPU API's fault?
Answer: No. Long answer: The GPU API is a relatively thin layer over the underlying graphics API. While it's possible that we have done something inefficiently, it's very unlikely especially if you are relatively inexperienced with GPU rendering. Please see the performance tips above and make sure you are following them. Additionally, tools like RenderDoc can be very helpful for diagnosing incorrect behavior and performance issues.
System Requirements
Vulkan
SDL driver name: "vulkan" (for use in SDL_CreateGPUDevice() and SDL_PROP_GPU_DEVICE_CREATE_NAME_STRING)
Supported on Windows, Linux, Nintendo Switch, and certain Android devices. Requires Vulkan 1.0 with the following extensions and device features:
VK_KHR_swapchain
VK_KHR_maintenance1
independentBlend
imageCubeArray
depthClamp
shaderClipDistance
drawIndirectFirstInstance
sampleRateShading
D3D12
SDL driver name: "direct3d12"
Supported on Windows 10 or newer, Xbox One (GDK), and Xbox Series X|S (GDK). Requires a GPU that supports DirectX 12 Feature Level 11_1.
Metal
SDL driver name: "metal"
Supported on macOS 10.14+ and iOS/tvOS 13.0+. Hardware requirements vary by operating system:
macOS requires an Apple Silicon or Intel Mac2 family GPU
iOS/tvOS requires an A9 GPU or newer
iOS Simulator and tvOS Simulator are unsupported
Coordinate System
The GPU API uses a left-handed coordinate system, following the convention of D3D12 and Metal. Specifically:
Normalized Device Coordinates: The lower-left corner has an x,y coordinate of (-1.0, -1.0). The upper-right corner is (1.0, 1.0). Z values range from [0.0, 1.0] where 0 is the near plane.
Viewport Coordinates: The top-left corner has an x,y coordinate of (0, 0) and extends to the bottom-right corner at (viewportWidth, viewportHeight). +Y is down.
Texture Coordinates: The top-left corner has an x,y coordinate of (0, 0) and extends to the bottom-right corner at (1.0, 1.0). +Y is down.
If the backend driver differs from this convention (e.g. Vulkan, which has an NDC that assumes +Y is down), SDL will automatically convert the coordinate system behind the scenes, so you don't need to perform any coordinate flipping logic in your shaders.
Uniform Data
Uniforms are for passing data to shaders. The uniform data will be constant across all executions of the shader.
There are 4 available uniform slots per shader stage (where the stages are vertex, fragment, and compute). Uniform data pushed to a slot on a stage keeps its value throughout the command buffer until you call the relevant Push function on that slot again.
For example, you could write your vertex shaders to read a camera matrix from uniform binding slot 0, push the camera matrix at the start of the command buffer, and that data will be used for every subsequent draw call.
It is valid to push uniform data during a render or compute pass.
Uniforms are best for pushing small amounts of data. If you are pushing more than a matrix or two per call you should consider using a storage buffer instead.
A Note On Cycling
When using a command buffer, operations do not occur immediately - they occur some time after the command buffer is submitted.
When a resource is used in a pending or active command buffer, it is considered to be "bound". When a resource is no longer used in any pending or active command buffers, it is considered to be "unbound".
If data resources are bound, it is unspecified when that data will be unbound unless you acquire a fence when submitting the command buffer and wait on it. However, this doesn't mean you need to track resource usage manually.
All of the functions and structs that involve writing to a resource have a "cycle" bool. SDL_GPUTransferBuffer, SDL_GPUBuffer, and SDL_GPUTexture all effectively function as ring buffers on internal resources. When cycle is true, if the resource is bound, the cycle rotates to the next unbound internal resource, or if none are available, a new one is created. This means you don't have to worry about complex state tracking and synchronization as long as cycling is correctly employed.
For example: you can call SDL_MapGPUTransferBuffer(), write texture data, SDL_UnmapGPUTransferBuffer(), and then SDL_UploadToGPUTexture(). The next time you write texture data to the transfer buffer, if you set the cycle param to true, you don't have to worry about overwriting any data that is not yet uploaded.
Another example: If you are using a texture in a render pass every frame, this can cause a data dependency between frames. If you set cycle to true in the SDL_GPUColorTargetInfo struct, you can prevent this data dependency.
Cycling will never undefine already bound data. When cycling, all data in the resource is considered to be undefined for subsequent commands until that data is written again. You must take care not to read undefined data.
Note that when cycling a texture, the entire texture will be cycled, even if only part of the texture is used in the call, so you must consider the entire texture to contain undefined data after cycling.
You must also take care not to overwrite a section of data that has been referenced in a command without cycling first. It is OK to overwrite unreferenced data in a bound resource without cycling, but overwriting a section of data that has already been referenced will produce unexpected results.
Debugging
At some point of your GPU journey, you will probably encounter issues that are not traceable with regular debugger - for example, your code compiles but you get an empty screen, or your shader fails in runtime.
For debugging such cases, there are tools that allow visually inspecting the whole GPU frame, every drawcall, every bound resource, memory buffers, etc. They are the following, per platform:
For Windows/Linux, use RenderDoc
For MacOS (Metal), use Xcode built-in debugger (Open XCode, go to Debug > Debug Executable..., select your application, set "GPU Frame Capture" to "Metal" in scheme "Options" window, run your app, and click the small Metal icon on the bottom to capture a frame)
Aside from that, you may want to enable additional debug layers to receive more detailed error messages, based on your GPU backend:
For D3D12, the debug layer is an optional feature that can be installed via "Windows Settings -> System -> Optional features" and adding the "Graphics Tools" optional feature.
For Vulkan, you will need to install Vulkan SDK on Windows, and on Linux, you usually have some sort of vulkan-validation-layers system package that should be installed.
For Metal, it should be enough just to run the application from XCode to receive detailed errors or warnings in the output.
Don't hesitate to use tools as RenderDoc when encountering runtime issues or unexpected output on screen, quick GPU frame inspection can usually help you fix the majority of such problems. An opaque handle representing the SDL_GPU context.
Since
This struct is available since SDL 3.2.0.
SDL_GPUFence
typedef struct SDL_GPUFence SDL_GPUFence
An opaque handle representing a fence.
Since
This struct is available since SDL 3.2.0.
See also
SDL_SubmitGPUCommandBufferAndAcquireFence
SDL_QueryGPUFence
SDL_WaitForGPUFences
SDL_ReleaseGPUFence
SDL_GPUFillMode
typedef enum SDL_GPUFillMode SDL_GPUFillMode
Specifies the fill mode of the graphics pipeline.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUFilter
typedef enum SDL_GPUFilter SDL_GPUFilter
Specifies a filter operation used by a sampler.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
SDL_GPUFrontFace
typedef enum SDL_GPUFrontFace SDL_GPUFrontFace
Specifies the vertex winding that will cause a triangle to be determined to be front-facing.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUGraphicsPipeline
typedef struct SDL_GPUGraphicsPipeline SDL_GPUGraphicsPipeline
An opaque handle representing a graphics pipeline.
Used during render passes.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_BindGPUGraphicsPipeline
SDL_ReleaseGPUGraphicsPipeline
SDL_GPUGraphicsPipelineCreateInfo
typedef struct SDL_GPUGraphicsPipelineCreateInfo SDL_GPUGraphicsPipelineCreateInfo
A structure specifying the parameters of a graphics pipeline state.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUShader
SDL_GPUVertexInputState
SDL_GPUPrimitiveType
SDL_GPURasterizerState
SDL_GPUMultisampleState
SDL_GPUDepthStencilState
SDL_GPUGraphicsPipelineTargetInfo
SDL_GPUGraphicsPipelineTargetInfo
typedef struct SDL_GPUGraphicsPipelineTargetInfo SDL_GPUGraphicsPipelineTargetInfo
A structure specifying the descriptions of render targets used in a graphics pipeline.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUGraphicsPipelineCreateInfo
SDL_GPUColorTargetDescription
SDL_GPUTextureFormat
SDL_GPUIndexedIndirectDrawCommand
typedef struct SDL_GPUIndexedIndirectDrawCommand SDL_GPUIndexedIndirectDrawCommand
A structure specifying the parameters of an indexed indirect draw command.
Note that the first_vertex and first_instance parameters are NOT compatible with built-in vertex/instance ID variables in shaders (for example, SV_VertexID); GPU APIs and shader languages do not define these built-in variables consistently, so if your shader depends on them, the only way to keep behavior consistent and portable is to always pass 0 for the correlating parameter in the draw calls.
Since
This struct is available since SDL 3.2.0.
See also
SDL_DrawGPUIndexedPrimitivesIndirect
SDL_GPUIndexElementSize
typedef enum SDL_GPUIndexElementSize SDL_GPUIndexElementSize
Specifies the size of elements in an index buffer.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUIndirectDispatchCommand
typedef struct SDL_GPUIndirectDispatchCommand SDL_GPUIndirectDispatchCommand
A structure specifying the parameters of an indexed dispatch command.
Since
This struct is available since SDL 3.2.0.
See also
SDL_DispatchGPUComputeIndirect
SDL_GPUIndirectDrawCommand
typedef struct SDL_GPUIndirectDrawCommand SDL_GPUIndirectDrawCommand
A structure specifying the parameters of an indirect draw command.
Note that the first_vertex and first_instance parameters are NOT compatible with built-in vertex/instance ID variables in shaders (for example, SV_VertexID); GPU APIs and shader languages do not define these built-in variables consistently, so if your shader depends on them, the only way to keep behavior consistent and portable is to always pass 0 for the correlating parameter in the draw calls.
Since
This struct is available since SDL 3.2.0.
See also
SDL_DrawGPUPrimitivesIndirect
SDL_GPULoadOp
typedef enum SDL_GPULoadOp SDL_GPULoadOp
Specifies how the contents of a texture attached to a render pass are treated at the beginning of the render pass.
Since
This enum is available since SDL 3.2.0.
See also
SDL_BeginGPURenderPass
SDL_GPUMultisampleState
typedef struct SDL_GPUMultisampleState SDL_GPUMultisampleState
A structure specifying the parameters of the graphics pipeline multisample state.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUGraphicsPipelineCreateInfo
SDL_GPUPresentMode
typedef enum SDL_GPUPresentMode SDL_GPUPresentMode
Specifies the timing that will be used to present swapchain textures to the OS.
VSYNC mode will always be supported. IMMEDIATE and MAILBOX modes may not be supported on certain systems.
It is recommended to query SDL_WindowSupportsGPUPresentMode after claiming the window if you wish to change the present mode to IMMEDIATE or MAILBOX.
VSYNC: Waits for vblank before presenting. No tearing is possible. If there is a pending image to present, the new image is enqueued for presentation. Disallows tearing at the cost of visual latency.
IMMEDIATE: Immediately presents. Lowest latency option, but tearing may occur.
MAILBOX: Waits for vblank before presenting. No tearing is possible. If there is a pending image to present, the pending image is replaced by the new image. Similar to VSYNC, but with reduced visual latency.
Since
This enum is available since SDL 3.2.0.
See also
SDL_SetGPUSwapchainParameters
SDL_WindowSupportsGPUPresentMode
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_GPUPrimitiveType
typedef enum SDL_GPUPrimitiveType SDL_GPUPrimitiveType
Specifies the primitive topology of a graphics pipeline.
If you are using POINTLIST you must include a point size output in the vertex shader.
For HLSL compiling to SPIRV you must decorate a float output with [[vk::builtin("PointSize")]].
For GLSL you must set the gl_PointSize builtin.
For MSL you must include a float output with the [[point_size]] decorator.
Note that sized point topology is totally unsupported on D3D12. Any size other than 1 will be ignored. In general, you should avoid using point topology for both compatibility and performance reasons. You WILL regret using it.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPURasterizerState
typedef struct SDL_GPURasterizerState SDL_GPURasterizerState
A structure specifying the parameters of the graphics pipeline rasterizer state.
Note that SDL_GPU_FILLMODE_LINE is not supported on many Android devices. For those devices, the fill mode will automatically fall back to FILL.
Also note that the D3D12 driver will enable depth clamping even if enable_depth_clip is true. If you need this clamp+clip behavior, consider enabling depth clip and then manually clamping depth in your fragment shaders on Metal and Vulkan.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUGraphicsPipelineCreateInfo
SDL_GPURenderPass
typedef struct SDL_GPURenderPass SDL_GPURenderPass
An opaque handle representing a render pass.
This handle is transient and should not be held or referenced after SDL_EndGPURenderPass is called.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BeginGPURenderPass
SDL_EndGPURenderPass
SDL_GPUSampleCount
typedef enum SDL_GPUSampleCount SDL_GPUSampleCount
Specifies the sample count of a texture.
Used in multisampling. Note that this value only applies when the texture is used as a render target.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_GPUTextureSupportsSampleCount
SDL_GPUSampler
typedef struct SDL_GPUSampler SDL_GPUSampler
An opaque handle representing a sampler.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
SDL_BindGPUVertexSamplers
SDL_BindGPUFragmentSamplers
SDL_ReleaseGPUSampler
SDL_GPUSamplerAddressMode
typedef enum SDL_GPUSamplerAddressMode SDL_GPUSamplerAddressMode
Specifies behavior of texture sampling when the coordinates exceed the 0-1 range.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
SDL_GPUSamplerCreateInfo
typedef struct SDL_GPUSamplerCreateInfo SDL_GPUSamplerCreateInfo
A structure specifying the parameters of a sampler.
Note that mip_lod_bias is a no-op for the Metal driver. For Metal, LOD bias must be applied via shader instead.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
SDL_GPUFilter
SDL_GPUSamplerMipmapMode
SDL_GPUSamplerAddressMode
SDL_GPUCompareOp
SDL_GPUSamplerMipmapMode
typedef enum SDL_GPUSamplerMipmapMode SDL_GPUSamplerMipmapMode
Specifies a mipmap mode used by a sampler.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
SDL_GPUShader
typedef struct SDL_GPUShader SDL_GPUShader
An opaque handle representing a compiled shader object.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
SDL_CreateGPUGraphicsPipeline
SDL_ReleaseGPUShader
SDL_GPUShaderCreateInfo
typedef struct SDL_GPUShaderCreateInfo SDL_GPUShaderCreateInfo
A structure specifying code and metadata for creating a shader object.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
SDL_GPUShaderFormat
SDL_GPUShaderStage
SDL_GPUShaderFormat
typedef Uint32 SDL_GPUShaderFormat
Specifies the format of shader code.
Each format corresponds to a specific backend that accepts it.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
SDL_GPUShaderStage
typedef enum SDL_GPUShaderStage SDL_GPUShaderStage
Specifies which stage a shader program corresponds to.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
SDL_GPUStencilOp
typedef enum SDL_GPUStencilOp SDL_GPUStencilOp
Specifies what happens to a stored stencil value if stencil tests fail or pass.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUStencilOpState
typedef struct SDL_GPUStencilOpState SDL_GPUStencilOpState
A structure specifying the stencil operation state of a graphics pipeline.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUDepthStencilState
SDL_GPUStorageBufferReadWriteBinding
typedef struct SDL_GPUStorageBufferReadWriteBinding SDL_GPUStorageBufferReadWriteBinding
A structure specifying parameters related to binding buffers in a compute pass.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BeginGPUComputePass
SDL_GPUStorageTextureReadWriteBinding
typedef struct SDL_GPUStorageTextureReadWriteBinding SDL_GPUStorageTextureReadWriteBinding
A structure specifying parameters related to binding textures in a compute pass.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BeginGPUComputePass
SDL_GPUStoreOp
typedef enum SDL_GPUStoreOp SDL_GPUStoreOp
Specifies how the contents of a texture attached to a render pass are treated at the end of the render pass.
Since
This enum is available since SDL 3.2.0.
See also
SDL_BeginGPURenderPass
SDL_GPUSwapchainComposition
typedef enum SDL_GPUSwapchainComposition SDL_GPUSwapchainComposition
Specifies the texture format and colorspace of the swapchain textures.
SDR will always be supported. Other compositions may not be supported on certain systems.
It is recommended to query SDL_WindowSupportsGPUSwapchainComposition after claiming the window if you wish to change the swapchain composition from SDR.
SDR: B8G8R8A8 or R8G8B8A8 swapchain. Pixel values are in sRGB encoding.
SDR_LINEAR: B8G8R8A8_SRGB or R8G8B8A8_SRGB swapchain. Pixel values are stored in memory in sRGB encoding but accessed in shaders in "linear sRGB" encoding which is sRGB but with a linear transfer function.
HDR_EXTENDED_LINEAR: R16G16B16A16_FLOAT swapchain. Pixel values are in extended linear sRGB encoding and permits values outside of the [0, 1] range.
HDR10_ST2084: A2R10G10B10 or A2B10G10R10 swapchain. Pixel values are in BT.2020 ST2084 (PQ) encoding.
Since
This enum is available since SDL 3.2.0.
See also
SDL_SetGPUSwapchainParameters
SDL_WindowSupportsGPUSwapchainComposition
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_GPUTexture
typedef struct SDL_GPUTexture SDL_GPUTexture
An opaque handle representing a texture.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_UploadToGPUTexture
SDL_DownloadFromGPUTexture
SDL_CopyGPUTextureToTexture
SDL_BindGPUVertexSamplers
SDL_BindGPUVertexStorageTextures
SDL_BindGPUFragmentSamplers
SDL_BindGPUFragmentStorageTextures
SDL_BindGPUComputeStorageTextures
SDL_GenerateMipmapsForGPUTexture
SDL_BlitGPUTexture
SDL_ReleaseGPUTexture
SDL_GPUTextureCreateInfo
typedef struct SDL_GPUTextureCreateInfo SDL_GPUTextureCreateInfo
A structure specifying the parameters of a texture.
Usage flags can be bitwise OR'd together for combinations of usages. Note that certain usage combinations are invalid, for example SAMPLER and GRAPHICS_STORAGE.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_GPUTextureType
SDL_GPUTextureFormat
SDL_GPUTextureUsageFlags
SDL_GPUSampleCount
SDL_GPUTextureFormat
typedef enum SDL_GPUTextureFormat SDL_GPUTextureFormat
Specifies the pixel format of a texture.
Texture format support varies depending on driver, hardware, and usage flags. In general, you should use SDL_GPUTextureSupportsFormat to query if a format is supported before using it. However, there are a few guaranteed formats.
FIXME: Check universal support for 32-bit component formats FIXME: Check universal support for SIMULTANEOUS_READ_WRITE
For SAMPLER usage, the following formats are universally supported:
R8G8B8A8_UNORM
B8G8R8A8_UNORM
R8_UNORM
R8_SNORM
R8G8_UNORM
R8G8_SNORM
R8G8B8A8_SNORM
R16_FLOAT
R16G16_FLOAT
R16G16B16A16_FLOAT
R32_FLOAT
R32G32_FLOAT
R32G32B32A32_FLOAT
R11G11B10_UFLOAT
R8G8B8A8_UNORM_SRGB
B8G8R8A8_UNORM_SRGB
D16_UNORM
For COLOR_TARGET usage, the following formats are universally supported:
R8G8B8A8_UNORM
B8G8R8A8_UNORM
R8_UNORM
R16_FLOAT
R16G16_FLOAT
R16G16B16A16_FLOAT
R32_FLOAT
R32G32_FLOAT
R32G32B32A32_FLOAT
R8_UINT
R8G8_UINT
R8G8B8A8_UINT
R16_UINT
R16G16_UINT
R16G16B16A16_UINT
R8_INT
R8G8_INT
R8G8B8A8_INT
R16_INT
R16G16_INT
R16G16B16A16_INT
R8G8B8A8_UNORM_SRGB
B8G8R8A8_UNORM_SRGB
For STORAGE usages, the following formats are universally supported:
R8G8B8A8_UNORM
R8G8B8A8_SNORM
R16G16B16A16_FLOAT
R32_FLOAT
R32G32_FLOAT
R32G32B32A32_FLOAT
R8G8B8A8_UINT
R16G16B16A16_UINT
R8G8B8A8_INT
R16G16B16A16_INT
For DEPTH_STENCIL_TARGET usage, the following formats are universally supported:
D16_UNORM
Either (but not necessarily both!) D24_UNORM or D32_FLOAT
Either (but not necessarily both!) D24_UNORM_S8_UINT or D32_FLOAT_S8_UINT
Unless D16_UNORM is sufficient for your purposes, always check which of D24/D32 is supported before creating a depth-stencil texture!
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_GPUTextureSupportsFormat
SDL_GPUTextureLocation
typedef struct SDL_GPUTextureLocation SDL_GPUTextureLocation
A structure specifying a location in a texture.
Used when copying data from one texture to another.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CopyGPUTextureToTexture
SDL_GPUTextureRegion
typedef struct SDL_GPUTextureRegion SDL_GPUTextureRegion
A structure specifying a region of a texture.
Used when transferring data to or from a texture.
Since
This struct is available since SDL 3.2.0.
See also
SDL_UploadToGPUTexture
SDL_DownloadFromGPUTexture
SDL_CreateGPUTexture
SDL_GPUTextureSamplerBinding
typedef struct SDL_GPUTextureSamplerBinding SDL_GPUTextureSamplerBinding
A structure specifying parameters in a sampler binding call.
Since
This struct is available since SDL 3.2.0.
See also
SDL_BindGPUVertexSamplers
SDL_BindGPUFragmentSamplers
SDL_GPUTextureTransferInfo
typedef struct SDL_GPUTextureTransferInfo SDL_GPUTextureTransferInfo
A structure specifying parameters related to transferring data to or from a texture.
If either of pixels_per_row or rows_per_layer is zero, then width and height of passed SDL_GPUTextureRegion to SDL_UploadToGPUTexture or SDL_DownloadFromGPUTexture are used as default values respectively and data is considered to be tightly packed.
WARNING: Direct3D 12 requires texture data row pitch to be 256 byte aligned, and offsets to be aligned to 512 bytes. If they are not, SDL will make a temporary copy of the data that is properly aligned, but this adds overhead to the transfer process. Apps can avoid this by aligning their data appropriately, or using a different GPU backend than Direct3D 12.
Since
This struct is available since SDL 3.2.0.
See also
SDL_UploadToGPUTexture
SDL_DownloadFromGPUTexture
SDL_GPUTextureType
typedef enum SDL_GPUTextureType SDL_GPUTextureType
Specifies the type of a texture.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_GPUTextureUsageFlags
typedef Uint32 SDL_GPUTextureUsageFlags
Specifies how a texture is intended to be used by the client.
A texture must have at least one usage flag. Note that some usage flag combinations are invalid.
With regards to compute storage usage, READ | WRITE means that you can have shader A that only writes into the texture and shader B that only reads from the texture and bind the same texture to either shader respectively. SIMULTANEOUS means that you can do reads and writes within the same shader or compute pass. It also implies that atomic ops can be used, since those are read-modify-write operations. If you use SIMULTANEOUS, you are responsible for avoiding data races, as there is no data synchronization within a compute pass. Note that SIMULTANEOUS usage is only supported by a limited number of texture formats.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_GPUTransferBuffer
typedef struct SDL_GPUTransferBuffer SDL_GPUTransferBuffer
An opaque handle representing a transfer buffer.
Used for transferring data to and from the device.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUTransferBuffer
SDL_MapGPUTransferBuffer
SDL_UnmapGPUTransferBuffer
SDL_UploadToGPUBuffer
SDL_UploadToGPUTexture
SDL_DownloadFromGPUBuffer
SDL_DownloadFromGPUTexture
SDL_ReleaseGPUTransferBuffer
SDL_GPUTransferBufferCreateInfo
typedef struct SDL_GPUTransferBufferCreateInfo SDL_GPUTransferBufferCreateInfo
A structure specifying the parameters of a transfer buffer.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateGPUTransferBuffer
SDL_GPUTransferBufferLocation
typedef struct SDL_GPUTransferBufferLocation SDL_GPUTransferBufferLocation
A structure specifying a location in a transfer buffer.
Used when transferring buffer data to or from a transfer buffer.
Since
This struct is available since SDL 3.2.0.
See also
SDL_UploadToGPUBuffer
SDL_DownloadFromGPUBuffer
SDL_GPUTransferBufferUsage
typedef enum SDL_GPUTransferBufferUsage SDL_GPUTransferBufferUsage
Specifies how a transfer buffer is intended to be used by the client.
Note that mapping and copying FROM an upload transfer buffer or TO a download transfer buffer is undefined behavior.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTransferBuffer
SDL_GPUVertexAttribute
typedef struct SDL_GPUVertexAttribute SDL_GPUVertexAttribute
A structure specifying a vertex attribute.
All vertex attribute locations provided to an SDL_GPUVertexInputState must be unique.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUVertexBufferDescription
SDL_GPUVertexInputState
SDL_GPUVertexElementFormat
SDL_GPUVertexBufferDescription
typedef struct SDL_GPUVertexBufferDescription SDL_GPUVertexBufferDescription
A structure specifying the parameters of vertex buffers used in a graphics pipeline.
When you call SDL_BindGPUVertexBuffers, you specify the binding slots of the vertex buffers. For example if you called SDL_BindGPUVertexBuffers with a first_slot of 2 and num_bindings of 3, the binding slots 2, 3, 4 would be used by the vertex buffers you pass in.
Vertex attributes are linked to buffers via the buffer_slot field of SDL_GPUVertexAttribute. For example, if an attribute has a buffer_slot of 0, then that attribute belongs to the vertex buffer bound at slot 0.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUVertexAttribute
SDL_GPUVertexInputRate
SDL_GPUVertexElementFormat
typedef enum SDL_GPUVertexElementFormat SDL_GPUVertexElementFormat
Specifies the format of a vertex attribute.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUVertexInputRate
typedef enum SDL_GPUVertexInputRate SDL_GPUVertexInputRate
Specifies the rate at which vertex attributes are pulled from buffers.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_GPUVertexInputState
typedef struct SDL_GPUVertexInputState SDL_GPUVertexInputState
A structure specifying the parameters of a graphics pipeline vertex input state.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GPUGraphicsPipelineCreateInfo
SDL_GPUVertexBufferDescription
SDL_GPUVertexAttribute
SDL_GPUViewport
typedef struct SDL_GPUViewport SDL_GPUViewport
A structure specifying a viewport.
Since
This struct is available since SDL 3.2.0.
See also
SDL_SetGPUViewport
Enumeration Type Documentation
SDL_GPUBlendFactor
enum SDL_GPUBlendFactor
Specifies a blending factor to be used when pixels in a render target are blended with existing pixels in the texture.
The source color is the value written by the fragment shader. The destination color is the value currently existing in the texture.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_BLENDFACTOR_INVALID
SDL_GPU_BLENDFACTOR_ZERO
0
SDL_GPU_BLENDFACTOR_ONE
1
SDL_GPU_BLENDFACTOR_SRC_COLOR
source color
SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_COLOR
1 - source color
SDL_GPU_BLENDFACTOR_DST_COLOR
destination color
SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_COLOR
1 - destination color
SDL_GPU_BLENDFACTOR_SRC_ALPHA
source alpha
SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA
1 - source alpha
SDL_GPU_BLENDFACTOR_DST_ALPHA
destination alpha
SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_ALPHA
1 - destination alpha
SDL_GPU_BLENDFACTOR_CONSTANT_COLOR
blend constant
SDL_GPU_BLENDFACTOR_ONE_MINUS_CONSTANT_COLOR
1 - blend constant
SDL_GPU_BLENDFACTOR_SRC_ALPHA_SATURATE
min(source alpha, 1 - destination alpha)
{
    SDL_GPU_BLENDFACTOR_INVALID,
    SDL_GPU_BLENDFACTOR_ZERO,                      /**< 0 */
    SDL_GPU_BLENDFACTOR_ONE,                       /**< 1 */
    SDL_GPU_BLENDFACTOR_SRC_COLOR,                 /**< source color */
    SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_COLOR,       /**< 1 - source color */
    SDL_GPU_BLENDFACTOR_DST_COLOR,                 /**< destination color */
    SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_COLOR,       /**< 1 - destination color */
    SDL_GPU_BLENDFACTOR_SRC_ALPHA,                 /**< source alpha */
    SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA,       /**< 1 - source alpha */
    SDL_GPU_BLENDFACTOR_DST_ALPHA,                 /**< destination alpha */
    SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_ALPHA,       /**< 1 - destination alpha */
    SDL_GPU_BLENDFACTOR_CONSTANT_COLOR,            /**< blend constant */
    SDL_GPU_BLENDFACTOR_ONE_MINUS_CONSTANT_COLOR,  /**< 1 - blend constant */
    SDL_GPU_BLENDFACTOR_SRC_ALPHA_SATURATE         /**< min(source alpha, 1 - destination alpha) */
} SDL_GPUBlendFactor;
SDL_GPUBlendOp
enum SDL_GPUBlendOp
Specifies the operator to be used when pixels in a render target are blended with existing pixels in the texture.
The source color is the value written by the fragment shader. The destination color is the value currently existing in the texture.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_BLENDOP_INVALID
SDL_GPU_BLENDOP_ADD
(source * source_factor) + (destination * destination_factor)
SDL_GPU_BLENDOP_SUBTRACT
(source * source_factor) - (destination * destination_factor)
SDL_GPU_BLENDOP_REVERSE_SUBTRACT
(destination * destination_factor) - (source * source_factor)
SDL_GPU_BLENDOP_MIN
min(source, destination)
SDL_GPU_BLENDOP_MAX
max(source, destination)
{
    SDL_GPU_BLENDOP_INVALID,
    SDL_GPU_BLENDOP_ADD,               /**< (source * source_factor) + (destination * destination_factor) */
    SDL_GPU_BLENDOP_SUBTRACT,          /**< (source * source_factor) - (destination * destination_factor) */
    SDL_GPU_BLENDOP_REVERSE_SUBTRACT,  /**< (destination * destination_factor) - (source * source_factor) */
    SDL_GPU_BLENDOP_MIN,               /**< min(source, destination) */
    SDL_GPU_BLENDOP_MAX                /**< max(source, destination) */
} SDL_GPUBlendOp;
SDL_GPUCompareOp
enum SDL_GPUCompareOp
Specifies a comparison operator for depth, stencil and sampler operations.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_COMPAREOP_INVALID
SDL_GPU_COMPAREOP_NEVER
The comparison always evaluates false.
SDL_GPU_COMPAREOP_LESS
The comparison evaluates reference < test.
SDL_GPU_COMPAREOP_EQUAL
The comparison evaluates reference == test.
SDL_GPU_COMPAREOP_LESS_OR_EQUAL
The comparison evaluates reference <= test.
SDL_GPU_COMPAREOP_GREATER
The comparison evaluates reference > test.
SDL_GPU_COMPAREOP_NOT_EQUAL
The comparison evaluates reference != test.
SDL_GPU_COMPAREOP_GREATER_OR_EQUAL
The comparison evalutes reference >= test.
SDL_GPU_COMPAREOP_ALWAYS
The comparison always evaluates true.
{
    SDL_GPU_COMPAREOP_INVALID,
    SDL_GPU_COMPAREOP_NEVER,             /**< The comparison always evaluates false. */
    SDL_GPU_COMPAREOP_LESS,              /**< The comparison evaluates reference < test. */
    SDL_GPU_COMPAREOP_EQUAL,             /**< The comparison evaluates reference == test. */
    SDL_GPU_COMPAREOP_LESS_OR_EQUAL,     /**< The comparison evaluates reference <= test. */
    SDL_GPU_COMPAREOP_GREATER,           /**< The comparison evaluates reference > test. */
    SDL_GPU_COMPAREOP_NOT_EQUAL,         /**< The comparison evaluates reference != test. */
    SDL_GPU_COMPAREOP_GREATER_OR_EQUAL,  /**< The comparison evalutes reference >= test. */
    SDL_GPU_COMPAREOP_ALWAYS             /**< The comparison always evaluates true. */
} SDL_GPUCompareOp;
SDL_GPUCubeMapFace
enum SDL_GPUCubeMapFace
Specifies the face of a cube map.
Can be passed in as the layer field in texture-related structs.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_GPU_CUBEMAPFACE_POSITIVEX
SDL_GPU_CUBEMAPFACE_NEGATIVEX
SDL_GPU_CUBEMAPFACE_POSITIVEY
SDL_GPU_CUBEMAPFACE_NEGATIVEY
SDL_GPU_CUBEMAPFACE_POSITIVEZ
SDL_GPU_CUBEMAPFACE_NEGATIVEZ
{
    SDL_GPU_CUBEMAPFACE_POSITIVEX,
    SDL_GPU_CUBEMAPFACE_NEGATIVEX,
    SDL_GPU_CUBEMAPFACE_POSITIVEY,
    SDL_GPU_CUBEMAPFACE_NEGATIVEY,
    SDL_GPU_CUBEMAPFACE_POSITIVEZ,
    SDL_GPU_CUBEMAPFACE_NEGATIVEZ
} SDL_GPUCubeMapFace;
SDL_GPUCullMode
enum SDL_GPUCullMode
Specifies the facing direction in which triangle faces will be culled.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_CULLMODE_NONE
No triangles are culled.
SDL_GPU_CULLMODE_FRONT
Front-facing triangles are culled.
SDL_GPU_CULLMODE_BACK
Back-facing triangles are culled.
{
    SDL_GPU_CULLMODE_NONE,   /**< No triangles are culled. */
    SDL_GPU_CULLMODE_FRONT,  /**< Front-facing triangles are culled. */
    SDL_GPU_CULLMODE_BACK    /**< Back-facing triangles are culled. */
} SDL_GPUCullMode;
SDL_GPUFillMode
enum SDL_GPUFillMode
Specifies the fill mode of the graphics pipeline.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_FILLMODE_FILL
Polygons will be rendered via rasterization.
SDL_GPU_FILLMODE_LINE
Polygon edges will be drawn as line segments.
{
    SDL_GPU_FILLMODE_FILL,  /**< Polygons will be rendered via rasterization. */
    SDL_GPU_FILLMODE_LINE   /**< Polygon edges will be drawn as line segments. */
} SDL_GPUFillMode;
SDL_GPUFilter
enum SDL_GPUFilter
Specifies a filter operation used by a sampler.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
Enumerator
SDL_GPU_FILTER_NEAREST
Point filtering.
SDL_GPU_FILTER_LINEAR
Linear filtering.
{
    SDL_GPU_FILTER_NEAREST,  /**< Point filtering. */
    SDL_GPU_FILTER_LINEAR    /**< Linear filtering. */
} SDL_GPUFilter;
SDL_GPUFrontFace
enum SDL_GPUFrontFace
Specifies the vertex winding that will cause a triangle to be determined to be front-facing.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE
A triangle with counter-clockwise vertex winding will be considered front-facing.
SDL_GPU_FRONTFACE_CLOCKWISE
A triangle with clockwise vertex winding will be considered front-facing.
{
    SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE,  /**< A triangle with counter-clockwise vertex winding will be considered front-facing. */
    SDL_GPU_FRONTFACE_CLOCKWISE           /**< A triangle with clockwise vertex winding will be considered front-facing. */
} SDL_GPUFrontFace;
SDL_GPUIndexElementSize
enum SDL_GPUIndexElementSize
Specifies the size of elements in an index buffer.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_INDEXELEMENTSIZE_16BIT
The index elements are 16-bit.
SDL_GPU_INDEXELEMENTSIZE_32BIT
The index elements are 32-bit.
{
    SDL_GPU_INDEXELEMENTSIZE_16BIT, /**< The index elements are 16-bit. */
    SDL_GPU_INDEXELEMENTSIZE_32BIT  /**< The index elements are 32-bit. */
} SDL_GPUIndexElementSize;
SDL_GPULoadOp
enum SDL_GPULoadOp
Specifies how the contents of a texture attached to a render pass are treated at the beginning of the render pass.
Since
This enum is available since SDL 3.2.0.
See also
SDL_BeginGPURenderPass
Enumerator
SDL_GPU_LOADOP_LOAD
The previous contents of the texture will be preserved.
SDL_GPU_LOADOP_CLEAR
The contents of the texture will be cleared to a color.
SDL_GPU_LOADOP_DONT_CARE
The previous contents of the texture need not be preserved. The contents will be undefined.
{
    SDL_GPU_LOADOP_LOAD,      /**< The previous contents of the texture will be preserved. */
    SDL_GPU_LOADOP_CLEAR,     /**< The contents of the texture will be cleared to a color. */
    SDL_GPU_LOADOP_DONT_CARE  /**< The previous contents of the texture need not be preserved. The contents will be undefined. */
} SDL_GPULoadOp;
SDL_GPUPresentMode
enum SDL_GPUPresentMode
Specifies the timing that will be used to present swapchain textures to the OS.
VSYNC mode will always be supported. IMMEDIATE and MAILBOX modes may not be supported on certain systems.
It is recommended to query SDL_WindowSupportsGPUPresentMode after claiming the window if you wish to change the present mode to IMMEDIATE or MAILBOX.
VSYNC: Waits for vblank before presenting. No tearing is possible. If there is a pending image to present, the new image is enqueued for presentation. Disallows tearing at the cost of visual latency.
IMMEDIATE: Immediately presents. Lowest latency option, but tearing may occur.
MAILBOX: Waits for vblank before presenting. No tearing is possible. If there is a pending image to present, the pending image is replaced by the new image. Similar to VSYNC, but with reduced visual latency.
Since
This enum is available since SDL 3.2.0.
See also
SDL_SetGPUSwapchainParameters
SDL_WindowSupportsGPUPresentMode
SDL_WaitAndAcquireGPUSwapchainTexture
Enumerator
SDL_GPU_PRESENTMODE_VSYNC
SDL_GPU_PRESENTMODE_IMMEDIATE
SDL_GPU_PRESENTMODE_MAILBOX
{
    SDL_GPU_PRESENTMODE_VSYNC,
    SDL_GPU_PRESENTMODE_IMMEDIATE,
    SDL_GPU_PRESENTMODE_MAILBOX
} SDL_GPUPresentMode;
SDL_GPUPrimitiveType
enum SDL_GPUPrimitiveType
Specifies the primitive topology of a graphics pipeline.
If you are using POINTLIST you must include a point size output in the vertex shader.
For HLSL compiling to SPIRV you must decorate a float output with [[vk::builtin("PointSize")]].
For GLSL you must set the gl_PointSize builtin.
For MSL you must include a float output with the [[point_size]] decorator.
Note that sized point topology is totally unsupported on D3D12. Any size other than 1 will be ignored. In general, you should avoid using point topology for both compatibility and performance reasons. You WILL regret using it.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_PRIMITIVETYPE_TRIANGLELIST
A series of separate triangles.
SDL_GPU_PRIMITIVETYPE_TRIANGLESTRIP
A series of connected triangles.
SDL_GPU_PRIMITIVETYPE_LINELIST
A series of separate lines.
SDL_GPU_PRIMITIVETYPE_LINESTRIP
A series of connected lines.
SDL_GPU_PRIMITIVETYPE_POINTLIST
A series of separate points.
{
    SDL_GPU_PRIMITIVETYPE_TRIANGLELIST,  /**< A series of separate triangles. */
    SDL_GPU_PRIMITIVETYPE_TRIANGLESTRIP, /**< A series of connected triangles. */
    SDL_GPU_PRIMITIVETYPE_LINELIST,      /**< A series of separate lines. */
    SDL_GPU_PRIMITIVETYPE_LINESTRIP,     /**< A series of connected lines. */
    SDL_GPU_PRIMITIVETYPE_POINTLIST      /**< A series of separate points. */
} SDL_GPUPrimitiveType;
SDL_GPUSampleCount
enum SDL_GPUSampleCount
Specifies the sample count of a texture.
Used in multisampling. Note that this value only applies when the texture is used as a render target.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_GPUTextureSupportsSampleCount
Enumerator
SDL_GPU_SAMPLECOUNT_1
No multisampling.
SDL_GPU_SAMPLECOUNT_2
MSAA 2x
SDL_GPU_SAMPLECOUNT_4
MSAA 4x
SDL_GPU_SAMPLECOUNT_8
MSAA 8x
{
    SDL_GPU_SAMPLECOUNT_1,  /**< No multisampling. */
    SDL_GPU_SAMPLECOUNT_2,  /**< MSAA 2x */
    SDL_GPU_SAMPLECOUNT_4,  /**< MSAA 4x */
    SDL_GPU_SAMPLECOUNT_8   /**< MSAA 8x */
} SDL_GPUSampleCount;
SDL_GPUSamplerAddressMode
enum SDL_GPUSamplerAddressMode
Specifies behavior of texture sampling when the coordinates exceed the 0-1 range.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
Enumerator
SDL_GPU_SAMPLERADDRESSMODE_REPEAT
Specifies that the coordinates will wrap around.
SDL_GPU_SAMPLERADDRESSMODE_MIRRORED_REPEAT
Specifies that the coordinates will wrap around mirrored.
SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE
Specifies that the coordinates will clamp to the 0-1 range.
{
    SDL_GPU_SAMPLERADDRESSMODE_REPEAT,           /**< Specifies that the coordinates will wrap around. */
    SDL_GPU_SAMPLERADDRESSMODE_MIRRORED_REPEAT,  /**< Specifies that the coordinates will wrap around mirrored. */
    SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE     /**< Specifies that the coordinates will clamp to the 0-1 range. */
} SDL_GPUSamplerAddressMode;
SDL_GPUSamplerMipmapMode
enum SDL_GPUSamplerMipmapMode
Specifies a mipmap mode used by a sampler.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUSampler
Enumerator
SDL_GPU_SAMPLERMIPMAPMODE_NEAREST
Point filtering.
SDL_GPU_SAMPLERMIPMAPMODE_LINEAR
Linear filtering.
{
    SDL_GPU_SAMPLERMIPMAPMODE_NEAREST,  /**< Point filtering. */
    SDL_GPU_SAMPLERMIPMAPMODE_LINEAR    /**< Linear filtering. */
} SDL_GPUSamplerMipmapMode;
SDL_GPUShaderStage
enum SDL_GPUShaderStage
Specifies which stage a shader program corresponds to.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
Enumerator
SDL_GPU_SHADERSTAGE_VERTEX
SDL_GPU_SHADERSTAGE_FRAGMENT
{
    SDL_GPU_SHADERSTAGE_VERTEX,
    SDL_GPU_SHADERSTAGE_FRAGMENT
} SDL_GPUShaderStage;
SDL_GPUStencilOp
enum SDL_GPUStencilOp
Specifies what happens to a stored stencil value if stencil tests fail or pass.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_STENCILOP_INVALID
SDL_GPU_STENCILOP_KEEP
Keeps the current value.
SDL_GPU_STENCILOP_ZERO
Sets the value to 0.
SDL_GPU_STENCILOP_REPLACE
Sets the value to reference.
SDL_GPU_STENCILOP_INCREMENT_AND_CLAMP
Increments the current value and clamps to the maximum value.
SDL_GPU_STENCILOP_DECREMENT_AND_CLAMP
Decrements the current value and clamps to 0.
SDL_GPU_STENCILOP_INVERT
Bitwise-inverts the current value.
SDL_GPU_STENCILOP_INCREMENT_AND_WRAP
Increments the current value and wraps back to 0.
SDL_GPU_STENCILOP_DECREMENT_AND_WRAP
Decrements the current value and wraps to the maximum value.
{
    SDL_GPU_STENCILOP_INVALID,
    SDL_GPU_STENCILOP_KEEP,                 /**< Keeps the current value. */
    SDL_GPU_STENCILOP_ZERO,                 /**< Sets the value to 0. */
    SDL_GPU_STENCILOP_REPLACE,              /**< Sets the value to reference. */
    SDL_GPU_STENCILOP_INCREMENT_AND_CLAMP,  /**< Increments the current value and clamps to the maximum value. */
    SDL_GPU_STENCILOP_DECREMENT_AND_CLAMP,  /**< Decrements the current value and clamps to 0. */
    SDL_GPU_STENCILOP_INVERT,               /**< Bitwise-inverts the current value. */
    SDL_GPU_STENCILOP_INCREMENT_AND_WRAP,   /**< Increments the current value and wraps back to 0. */
    SDL_GPU_STENCILOP_DECREMENT_AND_WRAP    /**< Decrements the current value and wraps to the maximum value. */
} SDL_GPUStencilOp;
SDL_GPUStoreOp
enum SDL_GPUStoreOp
Specifies how the contents of a texture attached to a render pass are treated at the end of the render pass.
Since
This enum is available since SDL 3.2.0.
See also
SDL_BeginGPURenderPass
Enumerator
SDL_GPU_STOREOP_STORE
The contents generated during the render pass will be written to memory.
SDL_GPU_STOREOP_DONT_CARE
The contents generated during the render pass are not needed and may be discarded. The contents will be undefined.
SDL_GPU_STOREOP_RESOLVE
The multisample contents generated during the render pass will be resolved to a non-multisample texture. The contents in the multisample texture may then be discarded and will be undefined.
SDL_GPU_STOREOP_RESOLVE_AND_STORE
The multisample contents generated during the render pass will be resolved to a non-multisample texture. The contents in the multisample texture will be written to memory.
{
    SDL_GPU_STOREOP_STORE,             /**< The contents generated during the render pass will be written to memory. */
    SDL_GPU_STOREOP_DONT_CARE,         /**< The contents generated during the render pass are not needed and may be discarded. The contents will be undefined. */
    SDL_GPU_STOREOP_RESOLVE,           /**< The multisample contents generated during the render pass will be resolved to a non-multisample texture. The contents in the multisample texture may then be discarded and will be undefined. */
    SDL_GPU_STOREOP_RESOLVE_AND_STORE  /**< The multisample contents generated during the render pass will be resolved to a non-multisample texture. The contents in the multisample texture will be written to memory. */
} SDL_GPUStoreOp;
SDL_GPUSwapchainComposition
enum SDL_GPUSwapchainComposition
Specifies the texture format and colorspace of the swapchain textures.
SDR will always be supported. Other compositions may not be supported on certain systems.
It is recommended to query SDL_WindowSupportsGPUSwapchainComposition after claiming the window if you wish to change the swapchain composition from SDR.
SDR: B8G8R8A8 or R8G8B8A8 swapchain. Pixel values are in sRGB encoding.
SDR_LINEAR: B8G8R8A8_SRGB or R8G8B8A8_SRGB swapchain. Pixel values are stored in memory in sRGB encoding but accessed in shaders in "linear sRGB" encoding which is sRGB but with a linear transfer function.
HDR_EXTENDED_LINEAR: R16G16B16A16_FLOAT swapchain. Pixel values are in extended linear sRGB encoding and permits values outside of the [0, 1] range.
HDR10_ST2084: A2R10G10B10 or A2B10G10R10 swapchain. Pixel values are in BT.2020 ST2084 (PQ) encoding.
Since
This enum is available since SDL 3.2.0.
See also
SDL_SetGPUSwapchainParameters
SDL_WindowSupportsGPUSwapchainComposition
SDL_WaitAndAcquireGPUSwapchainTexture
Enumerator
SDL_GPU_SWAPCHAINCOMPOSITION_SDR
SDL_GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR
SDL_GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR
SDL_GPU_SWAPCHAINCOMPOSITION_HDR10_ST2084
{
    SDL_GPU_SWAPCHAINCOMPOSITION_SDR,
    SDL_GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR,
    SDL_GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR,
    SDL_GPU_SWAPCHAINCOMPOSITION_HDR10_ST2084
} SDL_GPUSwapchainComposition;
SDL_GPUTextureFormat
enum SDL_GPUTextureFormat
Specifies the pixel format of a texture.
Texture format support varies depending on driver, hardware, and usage flags. In general, you should use SDL_GPUTextureSupportsFormat to query if a format is supported before using it. However, there are a few guaranteed formats.
FIXME: Check universal support for 32-bit component formats FIXME: Check universal support for SIMULTANEOUS_READ_WRITE
For SAMPLER usage, the following formats are universally supported:
R8G8B8A8_UNORM
B8G8R8A8_UNORM
R8_UNORM
R8_SNORM
R8G8_UNORM
R8G8_SNORM
R8G8B8A8_SNORM
R16_FLOAT
R16G16_FLOAT
R16G16B16A16_FLOAT
R32_FLOAT
R32G32_FLOAT
R32G32B32A32_FLOAT
R11G11B10_UFLOAT
R8G8B8A8_UNORM_SRGB
B8G8R8A8_UNORM_SRGB
D16_UNORM
For COLOR_TARGET usage, the following formats are universally supported:
R8G8B8A8_UNORM
B8G8R8A8_UNORM
R8_UNORM
R16_FLOAT
R16G16_FLOAT
R16G16B16A16_FLOAT
R32_FLOAT
R32G32_FLOAT
R32G32B32A32_FLOAT
R8_UINT
R8G8_UINT
R8G8B8A8_UINT
R16_UINT
R16G16_UINT
R16G16B16A16_UINT
R8_INT
R8G8_INT
R8G8B8A8_INT
R16_INT
R16G16_INT
R16G16B16A16_INT
R8G8B8A8_UNORM_SRGB
B8G8R8A8_UNORM_SRGB
For STORAGE usages, the following formats are universally supported:
R8G8B8A8_UNORM
R8G8B8A8_SNORM
R16G16B16A16_FLOAT
R32_FLOAT
R32G32_FLOAT
R32G32B32A32_FLOAT
R8G8B8A8_UINT
R16G16B16A16_UINT
R8G8B8A8_INT
R16G16B16A16_INT
For DEPTH_STENCIL_TARGET usage, the following formats are universally supported:
D16_UNORM
Either (but not necessarily both!) D24_UNORM or D32_FLOAT
Either (but not necessarily both!) D24_UNORM_S8_UINT or D32_FLOAT_S8_UINT
Unless D16_UNORM is sufficient for your purposes, always check which of D24/D32 is supported before creating a depth-stencil texture!
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
SDL_GPUTextureSupportsFormat
Enumerator
SDL_GPU_TEXTUREFORMAT_INVALID
SDL_GPU_TEXTUREFORMAT_A8_UNORM
SDL_GPU_TEXTUREFORMAT_R8_UNORM
SDL_GPU_TEXTUREFORMAT_R8G8_UNORM
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM
SDL_GPU_TEXTUREFORMAT_R16_UNORM
SDL_GPU_TEXTUREFORMAT_R16G16_UNORM
SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM
SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM
SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM
SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM
SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM
SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM
SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM
SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM
SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM
SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM
SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM
SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM
SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT
SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT
SDL_GPU_TEXTUREFORMAT_R8_SNORM
SDL_GPU_TEXTUREFORMAT_R8G8_SNORM
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM
SDL_GPU_TEXTUREFORMAT_R16_SNORM
SDL_GPU_TEXTUREFORMAT_R16G16_SNORM
SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM
SDL_GPU_TEXTUREFORMAT_R16_FLOAT
SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT
SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT
SDL_GPU_TEXTUREFORMAT_R32_FLOAT
SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT
SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT
SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT
SDL_GPU_TEXTUREFORMAT_R8_UINT
SDL_GPU_TEXTUREFORMAT_R8G8_UINT
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT
SDL_GPU_TEXTUREFORMAT_R16_UINT
SDL_GPU_TEXTUREFORMAT_R16G16_UINT
SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT
SDL_GPU_TEXTUREFORMAT_R32_UINT
SDL_GPU_TEXTUREFORMAT_R32G32_UINT
SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT
SDL_GPU_TEXTUREFORMAT_R8_INT
SDL_GPU_TEXTUREFORMAT_R8G8_INT
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT
SDL_GPU_TEXTUREFORMAT_R16_INT
SDL_GPU_TEXTUREFORMAT_R16G16_INT
SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT
SDL_GPU_TEXTUREFORMAT_R32_INT
SDL_GPU_TEXTUREFORMAT_R32G32_INT
SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT
SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_D16_UNORM
SDL_GPU_TEXTUREFORMAT_D24_UNORM
SDL_GPU_TEXTUREFORMAT_D32_FLOAT
SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT
SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT
SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM
SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB
SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT
SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT
{
    SDL_GPU_TEXTUREFORMAT_INVALID,
    /* Unsigned Normalized Float Color Formats */
    SDL_GPU_TEXTUREFORMAT_A8_UNORM,
    SDL_GPU_TEXTUREFORMAT_R8_UNORM,
    SDL_GPU_TEXTUREFORMAT_R8G8_UNORM,
    SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM,
    SDL_GPU_TEXTUREFORMAT_R16_UNORM,
    SDL_GPU_TEXTUREFORMAT_R16G16_UNORM,
    SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM,
    SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM,
    SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM,
    SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM,
    SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM,
    SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM,
    /* Compressed Unsigned Normalized Float Color Formats */
    SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM,
    SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM,
    SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM,
    SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM,
    SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM,
    SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM,
    /* Compressed Signed Float Color Formats */
    SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT,
    /* Compressed Unsigned Float Color Formats */
    SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT,
    /* Signed Normalized Float Color Formats  */
    SDL_GPU_TEXTUREFORMAT_R8_SNORM,
    SDL_GPU_TEXTUREFORMAT_R8G8_SNORM,
    SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM,
    SDL_GPU_TEXTUREFORMAT_R16_SNORM,
    SDL_GPU_TEXTUREFORMAT_R16G16_SNORM,
    SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM,
    /* Signed Float Color Formats */
    SDL_GPU_TEXTUREFORMAT_R16_FLOAT,
    SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT,
    SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT,
    SDL_GPU_TEXTUREFORMAT_R32_FLOAT,
    SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT,
    SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT,
    /* Unsigned Float Color Formats */
    SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT,
    /* Unsigned Integer Color Formats */
    SDL_GPU_TEXTUREFORMAT_R8_UINT,
    SDL_GPU_TEXTUREFORMAT_R8G8_UINT,
    SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT,
    SDL_GPU_TEXTUREFORMAT_R16_UINT,
    SDL_GPU_TEXTUREFORMAT_R16G16_UINT,
    SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT,
    SDL_GPU_TEXTUREFORMAT_R32_UINT,
    SDL_GPU_TEXTUREFORMAT_R32G32_UINT,
    SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT,
    /* Signed Integer Color Formats */
    SDL_GPU_TEXTUREFORMAT_R8_INT,
    SDL_GPU_TEXTUREFORMAT_R8G8_INT,
    SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT,
    SDL_GPU_TEXTUREFORMAT_R16_INT,
    SDL_GPU_TEXTUREFORMAT_R16G16_INT,
    SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT,
    SDL_GPU_TEXTUREFORMAT_R32_INT,
    SDL_GPU_TEXTUREFORMAT_R32G32_INT,
    SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT,
    /* SRGB Unsigned Normalized Color Formats */
    SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB,
    /* Compressed SRGB Unsigned Normalized Color Formats */
    SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB,
    /* Depth Formats */
    SDL_GPU_TEXTUREFORMAT_D16_UNORM,
    SDL_GPU_TEXTUREFORMAT_D24_UNORM,
    SDL_GPU_TEXTUREFORMAT_D32_FLOAT,
    SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT,
    SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT,
    /* Compressed ASTC Normalized Float Color Formats*/
    SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM,
    SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM,
    /* Compressed SRGB ASTC Normalized Float Color Formats*/
    SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB,
    SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB,
    /* Compressed ASTC Signed Float Color Formats*/
    SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT,
    SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT
} SDL_GPUTextureFormat;
SDL_GPUTextureType
enum SDL_GPUTextureType
Specifies the type of a texture.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
Enumerator
SDL_GPU_TEXTURETYPE_2D
The texture is a 2-dimensional image.
SDL_GPU_TEXTURETYPE_2D_ARRAY
The texture is a 2-dimensional array image.
SDL_GPU_TEXTURETYPE_3D
The texture is a 3-dimensional image.
SDL_GPU_TEXTURETYPE_CUBE
The texture is a cube image.
SDL_GPU_TEXTURETYPE_CUBE_ARRAY
The texture is a cube array image.
{
    SDL_GPU_TEXTURETYPE_2D,         /**< The texture is a 2-dimensional image. */
    SDL_GPU_TEXTURETYPE_2D_ARRAY,   /**< The texture is a 2-dimensional array image. */
    SDL_GPU_TEXTURETYPE_3D,         /**< The texture is a 3-dimensional image. */
    SDL_GPU_TEXTURETYPE_CUBE,       /**< The texture is a cube image. */
    SDL_GPU_TEXTURETYPE_CUBE_ARRAY  /**< The texture is a cube array image. */
} SDL_GPUTextureType;
SDL_GPUTransferBufferUsage
enum SDL_GPUTransferBufferUsage
Specifies how a transfer buffer is intended to be used by the client.
Note that mapping and copying FROM an upload transfer buffer or TO a download transfer buffer is undefined behavior.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUTransferBuffer
Enumerator
SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD
SDL_GPU_TRANSFERBUFFERUSAGE_DOWNLOAD
{
    SDL_GPU_TRANSFERBUFFERUSAGE_UPLOAD,
    SDL_GPU_TRANSFERBUFFERUSAGE_DOWNLOAD
} SDL_GPUTransferBufferUsage;
SDL_GPUVertexElementFormat
enum SDL_GPUVertexElementFormat
Specifies the format of a vertex attribute.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_VERTEXELEMENTFORMAT_INVALID
SDL_GPU_VERTEXELEMENTFORMAT_INT
SDL_GPU_VERTEXELEMENTFORMAT_INT2
SDL_GPU_VERTEXELEMENTFORMAT_INT3
SDL_GPU_VERTEXELEMENTFORMAT_INT4
SDL_GPU_VERTEXELEMENTFORMAT_UINT
SDL_GPU_VERTEXELEMENTFORMAT_UINT2
SDL_GPU_VERTEXELEMENTFORMAT_UINT3
SDL_GPU_VERTEXELEMENTFORMAT_UINT4
SDL_GPU_VERTEXELEMENTFORMAT_FLOAT
SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2
SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3
SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4
SDL_GPU_VERTEXELEMENTFORMAT_BYTE2
SDL_GPU_VERTEXELEMENTFORMAT_BYTE4
SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2
SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4
SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM
SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM
SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM
SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM
SDL_GPU_VERTEXELEMENTFORMAT_SHORT2
SDL_GPU_VERTEXELEMENTFORMAT_SHORT4
SDL_GPU_VERTEXELEMENTFORMAT_USHORT2
SDL_GPU_VERTEXELEMENTFORMAT_USHORT4
SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM
SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM
SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM
SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM
SDL_GPU_VERTEXELEMENTFORMAT_HALF2
SDL_GPU_VERTEXELEMENTFORMAT_HALF4
{
    SDL_GPU_VERTEXELEMENTFORMAT_INVALID,
    /* 32-bit Signed Integers */
    SDL_GPU_VERTEXELEMENTFORMAT_INT,
    SDL_GPU_VERTEXELEMENTFORMAT_INT2,
    SDL_GPU_VERTEXELEMENTFORMAT_INT3,
    SDL_GPU_VERTEXELEMENTFORMAT_INT4,
    /* 32-bit Unsigned Integers */
    SDL_GPU_VERTEXELEMENTFORMAT_UINT,
    SDL_GPU_VERTEXELEMENTFORMAT_UINT2,
    SDL_GPU_VERTEXELEMENTFORMAT_UINT3,
    SDL_GPU_VERTEXELEMENTFORMAT_UINT4,
    /* 32-bit Floats */
    SDL_GPU_VERTEXELEMENTFORMAT_FLOAT,
    SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2,
    SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3,
    SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4,
    /* 8-bit Signed Integers */
    SDL_GPU_VERTEXELEMENTFORMAT_BYTE2,
    SDL_GPU_VERTEXELEMENTFORMAT_BYTE4,
    /* 8-bit Unsigned Integers */
    SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2,
    SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4,
    /* 8-bit Signed Normalized */
    SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM,
    SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM,
    /* 8-bit Unsigned Normalized */
    SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM,
    SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM,
    /* 16-bit Signed Integers */
    SDL_GPU_VERTEXELEMENTFORMAT_SHORT2,
    SDL_GPU_VERTEXELEMENTFORMAT_SHORT4,
    /* 16-bit Unsigned Integers */
    SDL_GPU_VERTEXELEMENTFORMAT_USHORT2,
    SDL_GPU_VERTEXELEMENTFORMAT_USHORT4,
    /* 16-bit Signed Normalized */
    SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM,
    SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM,
    /* 16-bit Unsigned Normalized */
    SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM,
    SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM,
    /* 16-bit Floats */
    SDL_GPU_VERTEXELEMENTFORMAT_HALF2,
    SDL_GPU_VERTEXELEMENTFORMAT_HALF4
} SDL_GPUVertexElementFormat;
SDL_GPUVertexInputRate
enum SDL_GPUVertexInputRate
Specifies the rate at which vertex attributes are pulled from buffers.
Since
This enum is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
Enumerator
SDL_GPU_VERTEXINPUTRATE_VERTEX
Attribute addressing is a function of the vertex index.
SDL_GPU_VERTEXINPUTRATE_INSTANCE
Attribute addressing is a function of the instance index.
{
    SDL_GPU_VERTEXINPUTRATE_VERTEX,   /**< Attribute addressing is a function of the vertex index. */
    SDL_GPU_VERTEXINPUTRATE_INSTANCE  /**< Attribute addressing is a function of the instance index. */
} SDL_GPUVertexInputRate;
Function Documentation
SDL_AcquireGPUCommandBuffer()
SDL_DECLSPEC SDL_GPUCommandBuffer *SDLCALL SDL_AcquireGPUCommandBuffer (SDL_GPUDevice * device) extern
Acquire a command buffer.
This command buffer is managed by the implementation and should not be freed by the user. The command buffer may only be used on the thread it was acquired on. The command buffer should be submitted on the thread it was acquired on.
It is valid to acquire multiple command buffers on the same thread at once. In fact a common design pattern is to acquire two command buffers per frame where one is dedicated to render and compute passes and the other is dedicated to copy passes and other preparatory work such as generating mipmaps. Interleaving commands between the two command buffers reduces the total amount of passes overall which improves rendering performance.
Parameters
device a GPU context.
Returns
a command buffer, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_SubmitGPUCommandBuffer
SDL_SubmitGPUCommandBufferAndAcquireFence
{
    SDL_GPUCommandBuffer *command_buffer;
    CommandBufferCommonHeader *commandBufferHeader;
    CHECK_DEVICE_MAGIC(device, NULL);
    command_buffer = device->AcquireCommandBuffer(
        device->driverData);
    if (command_buffer == NULL) {
        return NULL;
    }
    commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    commandBufferHeader->device = device;
    commandBufferHeader->render_pass.command_buffer = command_buffer;
    commandBufferHeader->compute_pass.command_buffer = command_buffer;
    commandBufferHeader->copy_pass.command_buffer = command_buffer;
    if (device->debug_mode) {
        commandBufferHeader->render_pass.in_progress = false;
        commandBufferHeader->render_pass.graphics_pipeline = NULL;
        commandBufferHeader->compute_pass.in_progress = false;
        commandBufferHeader->compute_pass.compute_pipeline = NULL;
        commandBufferHeader->copy_pass.in_progress = false;
        commandBufferHeader->swapchain_texture_acquired = false;
        commandBufferHeader->submitted = false;
        commandBufferHeader->ignore_render_pass_texture_validation = false;
        SDL_zeroa(commandBufferHeader->render_pass.vertex_sampler_bound);
        SDL_zeroa(commandBufferHeader->render_pass.vertex_storage_texture_bound);
        SDL_zeroa(commandBufferHeader->render_pass.vertex_storage_buffer_bound);
        SDL_zeroa(commandBufferHeader->render_pass.fragment_sampler_bound);
        SDL_zeroa(commandBufferHeader->render_pass.fragment_storage_texture_bound);
        SDL_zeroa(commandBufferHeader->render_pass.fragment_storage_buffer_bound);
        SDL_zeroa(commandBufferHeader->compute_pass.sampler_bound);
        SDL_zeroa(commandBufferHeader->compute_pass.read_only_storage_texture_bound);
        SDL_zeroa(commandBufferHeader->compute_pass.read_only_storage_buffer_bound);
        SDL_zeroa(commandBufferHeader->compute_pass.read_write_storage_texture_bound);
        SDL_zeroa(commandBufferHeader->compute_pass.read_write_storage_buffer_bound);
    }
    return command_buffer;
}
References SDL_GPUDevice::AcquireCommandBuffer, CHECK_DEVICE_MAGIC, ComputePass::command_buffer, Pass::command_buffer, RenderPass::command_buffer, CommandBufferCommonHeader::compute_pass, ComputePass::compute_pipeline, CommandBufferCommonHeader::copy_pass, SDL_GPUDevice::debug_mode, CommandBufferCommonHeader::device, SDL_GPUDevice::driverData, RenderPass::fragment_sampler_bound, RenderPass::fragment_storage_buffer_bound, RenderPass::fragment_storage_texture_bound, RenderPass::graphics_pipeline, CommandBufferCommonHeader::ignore_render_pass_texture_validation, ComputePass::in_progress, Pass::in_progress, RenderPass::in_progress, NULL, ComputePass::read_only_storage_buffer_bound, ComputePass::read_only_storage_texture_bound, ComputePass::read_write_storage_buffer_bound, ComputePass::read_write_storage_texture_bound, CommandBufferCommonHeader::render_pass, ComputePass::sampler_bound, SDL_zeroa, CommandBufferCommonHeader::submitted, CommandBufferCommonHeader::swapchain_texture_acquired, RenderPass::vertex_sampler_bound, RenderPass::vertex_storage_buffer_bound, and RenderPass::vertex_storage_texture_bound.
SDL_AcquireGPUSwapchainTexture()
SDL_DECLSPEC bool SDLCALL SDL_AcquireGPUSwapchainTexture (SDL_GPUCommandBuffer * command_buffer, SDL_Window * window, SDL_GPUTexture ** swapchain_texture, Uint32 * swapchain_texture_width, Uint32 * swapchain_texture_height) extern
Acquire a texture to use in presentation.
When a swapchain texture is acquired on a command buffer, it will automatically be submitted for presentation when the command buffer is submitted. The swapchain texture should only be referenced by the command buffer used to acquire it.
This function will fill the swapchain texture handle with NULL if too many frames are in flight. This is not an error. This NULL pointer should not be passed back into SDL. Instead, it should be considered as an indication to wait until the swapchain is available.
If you use this function, it is possible to create a situation where many command buffers are allocated while the rendering context waits for the GPU to catch up, which will cause memory usage to grow. You should use SDL_WaitAndAcquireGPUSwapchainTexture() unless you know what you are doing with timing.
The swapchain texture is managed by the implementation and must not be freed by the user. You MUST NOT call this function from any thread other than the one that created the window.
Parameters
command_buffer a command buffer.
window a window that has been claimed.
swapchain_texture a pointer filled in with a swapchain texture handle.
swapchain_texture_width a pointer filled in with the swapchain texture width, may be NULL.
swapchain_texture_height a pointer filled in with the swapchain texture height, may be NULL.
Returns
true on success, false on error; call SDL_GetError() for more information.
Thread Safety
This function should only be called from the thread that created the window.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClaimWindowForGPUDevice
SDL_SubmitGPUCommandBuffer
SDL_SubmitGPUCommandBufferAndAcquireFence
SDL_CancelGPUCommandBuffer
SDL_GetWindowSizeInPixels
SDL_WaitForGPUSwapchain
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_SetGPUAllowedFramesInFlight
{
    CommandBufferCommonHeader *commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (command_buffer == NULL) {
        return SDL_InvalidParamError("command_buffer");
    }
    if (window == NULL) {
        return SDL_InvalidParamError("window");
    }
    if (swapchain_texture == NULL) {
        return SDL_InvalidParamError("swapchain_texture");
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER_RETURN_FALSE
        CHECK_ANY_PASS_IN_PROGRESS("Cannot acquire a swapchain texture during a pass!", false)
    }
    bool result = COMMAND_BUFFER_DEVICE->AcquireSwapchainTexture(
        command_buffer,
        window,
        swapchain_texture,
        swapchain_texture_width,
        swapchain_texture_height);
    if (*swapchain_texture != NULL){
        commandBufferHeader->swapchain_texture_acquired = true;
    }
    return result;
}
References CHECK_ANY_PASS_IN_PROGRESS, CHECK_COMMAND_BUFFER_RETURN_FALSE, COMMAND_BUFFER_DEVICE, NULL, SDL_InvalidParamError, and CommandBufferCommonHeader::swapchain_texture_acquired.
SDL_BeginGPUComputePass()
SDL_DECLSPEC SDL_GPUComputePass *SDLCALL SDL_BeginGPUComputePass (SDL_GPUCommandBuffer * command_buffer, const SDL_GPUStorageTextureReadWriteBinding * storage_texture_bindings, Uint32 num_storage_texture_bindings, const SDL_GPUStorageBufferReadWriteBinding * storage_buffer_bindings, Uint32 num_storage_buffer_bindings) extern
Begins a compute pass on a command buffer.
A compute pass is defined by a set of texture subresources and buffers that may be written to by compute pipelines. These textures and buffers must have been created with the COMPUTE_STORAGE_WRITE bit or the COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE bit. If you do not create a texture with COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE, you must not read from the texture in the compute pass. All operations related to compute pipelines must take place inside of a compute pass. You must not begin another compute pass, or a render pass or copy pass before ending the compute pass.
A VERY IMPORTANT NOTE - Reads and writes in compute passes are NOT implicitly synchronized. This means you may cause data races by both reading and writing a resource region in a compute pass, or by writing multiple times to a resource region. If your compute work depends on reading the completed output from a previous dispatch, you MUST end the current compute pass and begin a new one before you can safely access the data. Otherwise you will receive unexpected results. Reading and writing a texture in the same compute pass is only supported by specific texture formats. Make sure you check the format support!
Parameters
command_buffer a command buffer.
storage_texture_bindings an array of writeable storage texture binding structs.
num_storage_texture_bindings the number of storage textures to bind from the array.
storage_buffer_bindings an array of writeable storage buffer binding structs.
num_storage_buffer_bindings the number of storage buffers to bind from the array.
Returns
a compute pass handle.
Since
This function is available since SDL 3.2.0.
See also
SDL_EndGPUComputePass
{
    CommandBufferCommonHeader *commandBufferHeader;
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return NULL;
    }
    if (storage_texture_bindings == NULL && num_storage_texture_bindings > 0) {
        SDL_InvalidParamError("storage_texture_bindings");
        return NULL;
    }
    if (storage_buffer_bindings == NULL && num_storage_buffer_bindings > 0) {
        SDL_InvalidParamError("storage_buffer_bindings");
        return NULL;
    }
    if (num_storage_texture_bindings > MAX_COMPUTE_WRITE_TEXTURES) {
        SDL_InvalidParamError("num_storage_texture_bindings");
        return NULL;
    }
    if (num_storage_buffer_bindings > MAX_COMPUTE_WRITE_BUFFERS) {
        SDL_InvalidParamError("num_storage_buffer_bindings");
        return NULL;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER_RETURN_NULL
        CHECK_ANY_PASS_IN_PROGRESS("Cannot begin compute pass during another pass!", NULL)
        for (Uint32 i = 0; i < num_storage_texture_bindings; i += 1) {
            TextureCommonHeader *header = (TextureCommonHeader *)storage_texture_bindings[i].texture;
            if (!(header->info.usage & SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE) && !(header->info.usage & SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE)) {
                SDL_assert_release(!"Texture must be created with COMPUTE_STORAGE_WRITE or COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE flag");
                return NULL;
            }
            if (storage_texture_bindings[i].layer >= header->info.layer_count_or_depth) {
                SDL_assert_release(!"Storage texture layer index must be less than the texture's layer count!");
                return NULL;
            }
            if (storage_texture_bindings[i].mip_level >= header->info.num_levels) {
                SDL_assert_release(!"Storage texture mip level must be less than the texture's level count!");
                return NULL;
            }
        }
        // TODO: validate buffer usage?
    }
    COMMAND_BUFFER_DEVICE->BeginComputePass(
        command_buffer,
        storage_texture_bindings,
        num_storage_texture_bindings,
        storage_buffer_bindings,
        num_storage_buffer_bindings);
    commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        commandBufferHeader->compute_pass.in_progress = true;
        for (Uint32 i = 0; i < num_storage_texture_bindings; i += 1) {
            commandBufferHeader->compute_pass.read_write_storage_texture_bound[i] = true;
        }
        for (Uint32 i = 0; i < num_storage_buffer_bindings; i += 1) {
            commandBufferHeader->compute_pass.read_write_storage_buffer_bound[i] = true;
        }
    }
    return (SDL_GPUComputePass *)&(commandBufferHeader->compute_pass);
}
References CHECK_ANY_PASS_IN_PROGRESS, CHECK_COMMAND_BUFFER_RETURN_NULL, COMMAND_BUFFER_DEVICE, CommandBufferCommonHeader::compute_pass, ComputePass::in_progress, TextureCommonHeader::info, SDL_GPUTextureCreateInfo::layer_count_or_depth, MAX_COMPUTE_WRITE_BUFFERS, MAX_COMPUTE_WRITE_TEXTURES, NULL, SDL_GPUTextureCreateInfo::num_levels, ComputePass::read_write_storage_buffer_bound, ComputePass::read_write_storage_texture_bound, SDL_assert_release, SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE, SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE, SDL_InvalidParamError, and SDL_GPUTextureCreateInfo::usage.
SDL_BeginGPUCopyPass()
SDL_DECLSPEC SDL_GPUCopyPass *SDLCALL SDL_BeginGPUCopyPass (SDL_GPUCommandBuffer * command_buffer) extern
Begins a copy pass on a command buffer.
All operations related to copying to or from buffers or textures take place inside a copy pass. You must not begin another copy pass, or a render pass or compute pass before ending the copy pass.
Parameters
command_buffer a command buffer.
Returns
a copy pass handle.
Since
This function is available since SDL 3.2.0.
{
    CommandBufferCommonHeader *commandBufferHeader;
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return NULL;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER_RETURN_NULL
        CHECK_ANY_PASS_IN_PROGRESS("Cannot begin copy pass during another pass!", NULL)
    }
    COMMAND_BUFFER_DEVICE->BeginCopyPass(
        command_buffer);
    commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        commandBufferHeader->copy_pass.in_progress = true;
    }
    return (SDL_GPUCopyPass *)&(commandBufferHeader->copy_pass);
}
References CHECK_ANY_PASS_IN_PROGRESS, CHECK_COMMAND_BUFFER_RETURN_NULL, COMMAND_BUFFER_DEVICE, CommandBufferCommonHeader::copy_pass, Pass::in_progress, NULL, and SDL_InvalidParamError.
SDL_BeginGPURenderPass()
SDL_DECLSPEC SDL_GPURenderPass *SDLCALL SDL_BeginGPURenderPass (SDL_GPUCommandBuffer * command_buffer, const SDL_GPUColorTargetInfo * color_target_infos, Uint32 num_color_targets, const SDL_GPUDepthStencilTargetInfo * depth_stencil_target_info) extern
Begins a render pass on a command buffer.
A render pass consists of a set of texture subresources (or depth slices in the 3D texture case) which will be rendered to during the render pass, along with corresponding clear values and load/store operations. All operations related to graphics pipelines must take place inside of a render pass. A default viewport and scissor state are automatically set when this is called. You cannot begin another render pass, or begin a compute pass or copy pass until you have ended the render pass.
Using SDL_GPU_LOADOP_LOAD before any contents have been written to the texture subresource will result in undefined behavior. SDL_GPU_LOADOP_CLEAR will set the contents of the texture subresource to a single value before any rendering is performed. It's fine to do an empty render pass using SDL_GPU_STOREOP_STORE to clear a texture, but in general it's better to think of clearing not as an independent operation but as something that's done as the beginning of a render pass.
Parameters
command_buffer a command buffer.
color_target_infos an array of texture subresources with corresponding clear values and load/store ops.
num_color_targets the number of color targets in the color_target_infos array.
depth_stencil_target_info a texture subresource with corresponding clear value and load/store ops, may be NULL.
Returns
a render pass handle.
Since
This function is available since SDL 3.2.0.
See also
SDL_EndGPURenderPass
{
    CommandBufferCommonHeader *commandBufferHeader;
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return NULL;
    }
    if (color_target_infos == NULL && num_color_targets > 0) {
        SDL_InvalidParamError("color_target_infos");
        return NULL;
    }
    if (num_color_targets > MAX_COLOR_TARGET_BINDINGS) {
        SDL_SetError("num_color_targets exceeds MAX_COLOR_TARGET_BINDINGS");
        return NULL;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER_RETURN_NULL
        CHECK_ANY_PASS_IN_PROGRESS("Cannot begin render pass during another pass!", NULL)
        for (Uint32 i = 0; i < num_color_targets; i += 1) {
            TextureCommonHeader *textureHeader = (TextureCommonHeader *)color_target_infos[i].texture;
            if (color_target_infos[i].cycle && color_target_infos[i].load_op == SDL_GPU_LOADOP_LOAD) {
                SDL_assert_release(!"Cannot cycle color target when load op is LOAD!");
                return NULL;
            }
            if (color_target_infos[i].store_op == SDL_GPU_STOREOP_RESOLVE || color_target_infos[i].store_op == SDL_GPU_STOREOP_RESOLVE_AND_STORE) {
                if (color_target_infos[i].resolve_texture == NULL) {
                    SDL_assert_release(!"Store op is RESOLVE or RESOLVE_AND_STORE but resolve_texture is NULL!");
                    return NULL;
                } else {
                    TextureCommonHeader *resolveTextureHeader = (TextureCommonHeader *)color_target_infos[i].resolve_texture;
                    if (textureHeader->info.sample_count == SDL_GPU_SAMPLECOUNT_1) {
                        SDL_assert_release(!"Store op is RESOLVE or RESOLVE_AND_STORE but texture is not multisample!");
                        return NULL;
                    }
                    if (resolveTextureHeader->info.sample_count != SDL_GPU_SAMPLECOUNT_1) {
                        SDL_assert_release(!"Resolve texture must have a sample count of 1!");
                        return NULL;
                    }
                    if (resolveTextureHeader->info.format != textureHeader->info.format) {
                        SDL_assert_release(!"Resolve texture must have the same format as its corresponding color target!");
                        return NULL;
                    }
                    if (resolveTextureHeader->info.type == SDL_GPU_TEXTURETYPE_3D) {
                        SDL_assert_release(!"Resolve texture must not be of TEXTURETYPE_3D!");
                        return NULL;
                    }
                    if (!(resolveTextureHeader->info.usage & SDL_GPU_TEXTUREUSAGE_COLOR_TARGET)) {
                        SDL_assert_release(!"Resolve texture usage must include COLOR_TARGET!");
                        return NULL;
                    }
                }
            }
            if (color_target_infos[i].layer_or_depth_plane >= textureHeader->info.layer_count_or_depth) {
                SDL_assert_release(!"Color target layer index must be less than the texture's layer count!");
                return NULL;
            }
            if (color_target_infos[i].mip_level >= textureHeader->info.num_levels) {
                SDL_assert_release(!"Color target mip level must be less than the texture's level count!");
                return NULL;
            }
        }
        if (depth_stencil_target_info != NULL) {
            TextureCommonHeader *textureHeader = (TextureCommonHeader *)depth_stencil_target_info->texture;
            if (!(textureHeader->info.usage & SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET)) {
                SDL_assert_release(!"Depth target must have been created with the DEPTH_STENCIL_TARGET usage flag!");
                return NULL;
            }
            if (depth_stencil_target_info->cycle && (depth_stencil_target_info->load_op == SDL_GPU_LOADOP_LOAD || depth_stencil_target_info->stencil_load_op == SDL_GPU_LOADOP_LOAD)) {
                SDL_assert_release(!"Cannot cycle depth target when load op or stencil load op is LOAD!");
                return NULL;
            }
            if (depth_stencil_target_info->store_op == SDL_GPU_STOREOP_RESOLVE ||
                depth_stencil_target_info->stencil_store_op == SDL_GPU_STOREOP_RESOLVE ||
                depth_stencil_target_info->store_op == SDL_GPU_STOREOP_RESOLVE_AND_STORE ||
                depth_stencil_target_info->stencil_store_op == SDL_GPU_STOREOP_RESOLVE_AND_STORE) {
                SDL_assert_release(!"RESOLVE store ops are not supported for depth-stencil targets!");
                return NULL;
            }
        }
    }
    COMMAND_BUFFER_DEVICE->BeginRenderPass(
        command_buffer,
        color_target_infos,
        num_color_targets,
        depth_stencil_target_info);
    commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        commandBufferHeader->render_pass.in_progress = true;
        for (Uint32 i = 0; i < num_color_targets; i += 1) {
            commandBufferHeader->render_pass.color_targets[i] = color_target_infos[i].texture;
        }
        commandBufferHeader->render_pass.num_color_targets = num_color_targets;
        if (depth_stencil_target_info != NULL) {
            commandBufferHeader->render_pass.depth_stencil_target = depth_stencil_target_info->texture;
        }
    }
    return (SDL_GPURenderPass *)&(commandBufferHeader->render_pass);
}
References CHECK_ANY_PASS_IN_PROGRESS, CHECK_COMMAND_BUFFER_RETURN_NULL, RenderPass::color_targets, COMMAND_BUFFER_DEVICE, SDL_GPUDepthStencilTargetInfo::cycle, RenderPass::depth_stencil_target, SDL_GPUTextureCreateInfo::format, RenderPass::in_progress, TextureCommonHeader::info, SDL_GPUTextureCreateInfo::layer_count_or_depth, SDL_GPUDepthStencilTargetInfo::load_op, MAX_COLOR_TARGET_BINDINGS, NULL, RenderPass::num_color_targets, SDL_GPUTextureCreateInfo::num_levels, CommandBufferCommonHeader::render_pass, SDL_GPUTextureCreateInfo::sample_count, SDL_assert_release, SDL_GPU_LOADOP_LOAD, SDL_GPU_SAMPLECOUNT_1, SDL_GPU_STOREOP_RESOLVE, SDL_GPU_STOREOP_RESOLVE_AND_STORE, SDL_GPU_TEXTURETYPE_3D, SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET, SDL_InvalidParamError, SDL_SetError(), SDL_GPUDepthStencilTargetInfo::stencil_load_op, SDL_GPUDepthStencilTargetInfo::stencil_store_op, SDL_GPUDepthStencilTargetInfo::store_op, SDL_GPUColorTargetInfo::texture, SDL_GPUDepthStencilTargetInfo::texture, SDL_GPUTextureCreateInfo::type, and SDL_GPUTextureCreateInfo::usage.
Referenced by SDL_GPU_BlitCommon().
SDL_BindGPUComputePipeline()
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputePipeline (SDL_GPUComputePass * compute_pass, SDL_GPUComputePipeline * compute_pipeline) extern
Binds a compute pipeline on a command buffer for use in compute dispatch.
Parameters
compute_pass a compute pass handle.
compute_pipeline a compute pipeline to bind.
Since
This function is available since SDL 3.2.0.
{
    if (compute_pass == NULL) {
        SDL_InvalidParamError("compute_pass");
        return;
    }
    if (compute_pipeline == NULL) {
        SDL_InvalidParamError("compute_pipeline");
        return;
    }
    if (COMPUTEPASS_DEVICE->debug_mode) {
        CHECK_COMPUTEPASS
    }
    COMPUTEPASS_DEVICE->BindComputePipeline(
        COMPUTEPASS_COMMAND_BUFFER,
        compute_pipeline);
    if (COMPUTEPASS_DEVICE->debug_mode) {
        COMPUTEPASS_BOUND_PIPELINE = compute_pipeline;
    }
}
References CHECK_COMPUTEPASS, COMPUTEPASS_BOUND_PIPELINE, COMPUTEPASS_COMMAND_BUFFER, COMPUTEPASS_DEVICE, NULL, and SDL_InvalidParamError.
SDL_BindGPUComputeSamplers()
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputeSamplers (SDL_GPUComputePass * compute_pass, Uint32 first_slot, const SDL_GPUTextureSamplerBinding * texture_sampler_bindings, Uint32 num_bindings) extern
Binds texture-sampler pairs for use on the compute shader.
The textures must have been created with SDL_GPU_TEXTUREUSAGE_SAMPLER.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
compute_pass a compute pass handle.
first_slot the compute sampler slot to begin binding from.
texture_sampler_bindings an array of texture-sampler binding structs.
num_bindings the number of texture-sampler bindings to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (compute_pass == NULL) {
        SDL_InvalidParamError("compute_pass");
        return;
    }
    if (texture_sampler_bindings == NULL && num_bindings > 0) {
        SDL_InvalidParamError("texture_sampler_bindings");
        return;
    }
    if (COMPUTEPASS_DEVICE->debug_mode) {
        CHECK_COMPUTEPASS
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((ComputePass *)compute_pass)->sampler_bound[first_slot + i] = true;
        }
    }
    COMPUTEPASS_DEVICE->BindComputeSamplers(
        COMPUTEPASS_COMMAND_BUFFER,
        first_slot,
        texture_sampler_bindings,
        num_bindings);
}
References CHECK_COMPUTEPASS, COMPUTEPASS_COMMAND_BUFFER, COMPUTEPASS_DEVICE, NULL, and SDL_InvalidParamError.
SDL_BindGPUComputeStorageBuffers()
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputeStorageBuffers (SDL_GPUComputePass * compute_pass, Uint32 first_slot, SDL_GPUBuffer *const * storage_buffers, Uint32 num_bindings) extern
Binds storage buffers as readonly for use on the compute pipeline.
These buffers must have been created with SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_READ.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
compute_pass a compute pass handle.
first_slot the compute storage buffer slot to begin binding from.
storage_buffers an array of storage buffer binding structs.
num_bindings the number of storage buffers to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (compute_pass == NULL) {
        SDL_InvalidParamError("compute_pass");
        return;
    }
    if (storage_buffers == NULL && num_bindings > 0) {
        SDL_InvalidParamError("storage_buffers");
        return;
    }
    if (COMPUTEPASS_DEVICE->debug_mode) {
        CHECK_COMPUTEPASS
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((ComputePass *)compute_pass)->read_only_storage_buffer_bound[first_slot + i] = true;
        }
    }
    COMPUTEPASS_DEVICE->BindComputeStorageBuffers(
        COMPUTEPASS_COMMAND_BUFFER,
        first_slot,
        storage_buffers,
        num_bindings);
}
References CHECK_COMPUTEPASS, COMPUTEPASS_COMMAND_BUFFER, COMPUTEPASS_DEVICE, NULL, and SDL_InvalidParamError.
SDL_BindGPUComputeStorageTextures()
SDL_DECLSPEC void SDLCALL SDL_BindGPUComputeStorageTextures (SDL_GPUComputePass * compute_pass, Uint32 first_slot, SDL_GPUTexture *const * storage_textures, Uint32 num_bindings) extern
Binds storage textures as readonly for use on the compute pipeline.
These textures must have been created with SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
compute_pass a compute pass handle.
first_slot the compute storage texture slot to begin binding from.
storage_textures an array of storage textures.
num_bindings the number of storage textures to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (compute_pass == NULL) {
        SDL_InvalidParamError("compute_pass");
        return;
    }
    if (storage_textures == NULL && num_bindings > 0) {
        SDL_InvalidParamError("storage_textures");
        return;
    }
    if (COMPUTEPASS_DEVICE->debug_mode) {
        CHECK_COMPUTEPASS
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((ComputePass *)compute_pass)->read_only_storage_texture_bound[first_slot + i] = true;
        }
    }
    COMPUTEPASS_DEVICE->BindComputeStorageTextures(
        COMPUTEPASS_COMMAND_BUFFER,
        first_slot,
        storage_textures,
        num_bindings);
}
References CHECK_COMPUTEPASS, COMPUTEPASS_COMMAND_BUFFER, COMPUTEPASS_DEVICE, NULL, and SDL_InvalidParamError.
SDL_BindGPUFragmentSamplers()
SDL_DECLSPEC void SDLCALL SDL_BindGPUFragmentSamplers (SDL_GPURenderPass * render_pass, Uint32 first_slot, const SDL_GPUTextureSamplerBinding * texture_sampler_bindings, Uint32 num_bindings) extern
Binds texture-sampler pairs for use on the fragment shader.
The textures must have been created with SDL_GPU_TEXTUREUSAGE_SAMPLER.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
render_pass a render pass handle.
first_slot the fragment sampler slot to begin binding from.
texture_sampler_bindings an array of texture-sampler binding structs.
num_bindings the number of texture-sampler pairs to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (texture_sampler_bindings == NULL && num_bindings > 0) {
        SDL_InvalidParamError("texture_sampler_bindings");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        if (!((CommandBufferCommonHeader *)RENDERPASS_COMMAND_BUFFER)->ignore_render_pass_texture_validation) {
            CHECK_SAMPLER_TEXTURES
        }
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((RenderPass *)render_pass)->fragment_sampler_bound[first_slot + i] = true;
        }
    }
    RENDERPASS_DEVICE->BindFragmentSamplers(
        RENDERPASS_COMMAND_BUFFER,
        first_slot,
        texture_sampler_bindings,
        num_bindings);
}
References CHECK_RENDERPASS, CHECK_SAMPLER_TEXTURES, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
Referenced by SDL_GPU_BlitCommon().
SDL_BindGPUFragmentStorageBuffers()
SDL_DECLSPEC void SDLCALL SDL_BindGPUFragmentStorageBuffers (SDL_GPURenderPass * render_pass, Uint32 first_slot, SDL_GPUBuffer *const * storage_buffers, Uint32 num_bindings) extern
Binds storage buffers for use on the fragment shader.
These buffers must have been created with SDL_GPU_BUFFERUSAGE_GRAPHICS_STORAGE_READ.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
render_pass a render pass handle.
first_slot the fragment storage buffer slot to begin binding from.
storage_buffers an array of storage buffers.
num_bindings the number of storage buffers to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (storage_buffers == NULL && num_bindings > 0) {
        SDL_InvalidParamError("storage_buffers");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((RenderPass *)render_pass)->fragment_storage_buffer_bound[first_slot + i] = true;
        }
    }
    RENDERPASS_DEVICE->BindFragmentStorageBuffers(
        RENDERPASS_COMMAND_BUFFER,
        first_slot,
        storage_buffers,
        num_bindings);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_BindGPUFragmentStorageTextures()
SDL_DECLSPEC void SDLCALL SDL_BindGPUFragmentStorageTextures (SDL_GPURenderPass * render_pass, Uint32 first_slot, SDL_GPUTexture *const * storage_textures, Uint32 num_bindings) extern
Binds storage textures for use on the fragment shader.
These textures must have been created with SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
render_pass a render pass handle.
first_slot the fragment storage texture slot to begin binding from.
storage_textures an array of storage textures.
num_bindings the number of storage textures to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (storage_textures == NULL && num_bindings > 0) {
        SDL_InvalidParamError("storage_textures");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        CHECK_STORAGE_TEXTURES
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((RenderPass *)render_pass)->fragment_storage_texture_bound[first_slot + i] = true;
        }
    }
    RENDERPASS_DEVICE->BindFragmentStorageTextures(
        RENDERPASS_COMMAND_BUFFER,
        first_slot,
        storage_textures,
        num_bindings);
}
References CHECK_RENDERPASS, CHECK_STORAGE_TEXTURES, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_BindGPUGraphicsPipeline()
SDL_DECLSPEC void SDLCALL SDL_BindGPUGraphicsPipeline (SDL_GPURenderPass * render_pass, SDL_GPUGraphicsPipeline * graphics_pipeline) extern
Binds a graphics pipeline on a render pass to be used in rendering.
A graphics pipeline must be bound before making any draw calls.
Parameters
render_pass a render pass handle.
graphics_pipeline the graphics pipeline to bind.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (graphics_pipeline == NULL) {
        SDL_InvalidParamError("graphics_pipeline");
        return;
    }
    RENDERPASS_DEVICE->BindGraphicsPipeline(
        RENDERPASS_COMMAND_BUFFER,
        graphics_pipeline);
    if (RENDERPASS_DEVICE->debug_mode) {
        RENDERPASS_BOUND_PIPELINE = graphics_pipeline;
    }
}
References NULL, RENDERPASS_BOUND_PIPELINE, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
Referenced by SDL_GPU_BlitCommon().
SDL_BindGPUIndexBuffer()
SDL_DECLSPEC void SDLCALL SDL_BindGPUIndexBuffer (SDL_GPURenderPass * render_pass, const SDL_GPUBufferBinding * binding, SDL_GPUIndexElementSize index_element_size) extern
Binds an index buffer on a command buffer for use with subsequent draw calls.
Parameters
render_pass a render pass handle.
binding a pointer to a struct containing an index buffer and offset.
index_element_size whether the index values in the buffer are 16- or 32-bit.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (binding == NULL) {
        SDL_InvalidParamError("binding");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
    }
    RENDERPASS_DEVICE->BindIndexBuffer(
        RENDERPASS_COMMAND_BUFFER,
        binding,
        index_element_size);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_BindGPUVertexBuffers()
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexBuffers (SDL_GPURenderPass * render_pass, Uint32 first_slot, const SDL_GPUBufferBinding * bindings, Uint32 num_bindings) extern
Binds vertex buffers on a command buffer for use with subsequent draw calls.
Parameters
render_pass a render pass handle.
first_slot the vertex buffer slot to begin binding from.
bindings an array of SDL_GPUBufferBinding structs containing vertex buffers and offset values.
num_bindings the number of bindings in the bindings array.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (bindings == NULL && num_bindings > 0) {
        SDL_InvalidParamError("bindings");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
    }
    RENDERPASS_DEVICE->BindVertexBuffers(
        RENDERPASS_COMMAND_BUFFER,
        first_binding,
        bindings,
        num_bindings);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_BindGPUVertexSamplers()
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexSamplers (SDL_GPURenderPass * render_pass, Uint32 first_slot, const SDL_GPUTextureSamplerBinding * texture_sampler_bindings, Uint32 num_bindings) extern
Binds texture-sampler pairs for use on the vertex shader.
The textures must have been created with SDL_GPU_TEXTUREUSAGE_SAMPLER.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
render_pass a render pass handle.
first_slot the vertex sampler slot to begin binding from.
texture_sampler_bindings an array of texture-sampler binding structs.
num_bindings the number of texture-sampler pairs to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (texture_sampler_bindings == NULL && num_bindings > 0) {
        SDL_InvalidParamError("texture_sampler_bindings");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        if (!((CommandBufferCommonHeader *)RENDERPASS_COMMAND_BUFFER)->ignore_render_pass_texture_validation)
        {
            CHECK_SAMPLER_TEXTURES
        }
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((RenderPass *)render_pass)->vertex_sampler_bound[first_slot + i] = true;
        }
    }
    RENDERPASS_DEVICE->BindVertexSamplers(
        RENDERPASS_COMMAND_BUFFER,
        first_slot,
        texture_sampler_bindings,
        num_bindings);
}
References CHECK_RENDERPASS, CHECK_SAMPLER_TEXTURES, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_BindGPUVertexStorageBuffers()
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexStorageBuffers (SDL_GPURenderPass * render_pass, Uint32 first_slot, SDL_GPUBuffer *const * storage_buffers, Uint32 num_bindings) extern
Binds storage buffers for use on the vertex shader.
These buffers must have been created with SDL_GPU_BUFFERUSAGE_GRAPHICS_STORAGE_READ.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
render_pass a render pass handle.
first_slot the vertex storage buffer slot to begin binding from.
storage_buffers an array of buffers.
num_bindings the number of buffers to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (storage_buffers == NULL && num_bindings > 0) {
        SDL_InvalidParamError("storage_buffers");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((RenderPass *)render_pass)->vertex_storage_buffer_bound[first_slot + i] = true;
        }
    }
    RENDERPASS_DEVICE->BindVertexStorageBuffers(
        RENDERPASS_COMMAND_BUFFER,
        first_slot,
        storage_buffers,
        num_bindings);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_BindGPUVertexStorageTextures()
SDL_DECLSPEC void SDLCALL SDL_BindGPUVertexStorageTextures (SDL_GPURenderPass * render_pass, Uint32 first_slot, SDL_GPUTexture *const * storage_textures, Uint32 num_bindings) extern
Binds storage textures for use on the vertex shader.
These textures must have been created with SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ.
Be sure your shader is set up according to the requirements documented in SDL_CreateGPUShader().
Parameters
render_pass a render pass handle.
first_slot the vertex storage texture slot to begin binding from.
storage_textures an array of storage textures.
num_bindings the number of storage texture to bind from the array.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (storage_textures == NULL && num_bindings > 0) {
        SDL_InvalidParamError("storage_textures");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        CHECK_STORAGE_TEXTURES
        for (Uint32 i = 0; i < num_bindings; i += 1) {
            ((RenderPass *)render_pass)->vertex_storage_texture_bound[first_slot + i] = true;
        }
    }
    RENDERPASS_DEVICE->BindVertexStorageTextures(
        RENDERPASS_COMMAND_BUFFER,
        first_slot,
        storage_textures,
        num_bindings);
}
References CHECK_RENDERPASS, CHECK_STORAGE_TEXTURES, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_BlitGPUTexture()
SDL_DECLSPEC void SDLCALL SDL_BlitGPUTexture (SDL_GPUCommandBuffer * command_buffer, const SDL_GPUBlitInfo * info) extern
Blits from a source texture region to a destination texture region.
This function must not be called inside of any pass.
Parameters
command_buffer a command buffer.
info the blit info struct containing the blit parameters.
Since
This function is available since SDL 3.2.0.
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (info == NULL) {
        SDL_InvalidParamError("info");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
        CHECK_ANY_PASS_IN_PROGRESS("Cannot blit during a pass!", )
        // Validation
        bool failed = false;
        TextureCommonHeader *srcHeader = (TextureCommonHeader *)info->source.texture;
        TextureCommonHeader *dstHeader = (TextureCommonHeader *)info->destination.texture;
        if (srcHeader == NULL) {
            SDL_assert_release(!"Blit source texture must be non-NULL");
            return; // attempting to proceed will crash
        }
        if (dstHeader == NULL) {
            SDL_assert_release(!"Blit destination texture must be non-NULL");
            return; // attempting to proceed will crash
        }
        if (srcHeader->info.sample_count != SDL_GPU_SAMPLECOUNT_1) {
            SDL_assert_release(!"Blit source texture must have a sample count of 1");
            failed = true;
        }
        if ((srcHeader->info.usage & SDL_GPU_TEXTUREUSAGE_SAMPLER) == 0) {
            SDL_assert_release(!"Blit source texture must be created with the SAMPLER usage flag");
            failed = true;
        }
        if ((dstHeader->info.usage & SDL_GPU_TEXTUREUSAGE_COLOR_TARGET) == 0) {
            SDL_assert_release(!"Blit destination texture must be created with the COLOR_TARGET usage flag");
            failed = true;
        }
        if (IsDepthFormat(srcHeader->info.format)) {
            SDL_assert_release(!"Blit source texture cannot have a depth format");
            failed = true;
        }
        if (info->source.w == 0 || info->source.h == 0 || info->destination.w == 0 || info->destination.h == 0) {
            SDL_assert_release(!"Blit source/destination regions must have non-zero width, height, and depth");
            failed = true;
        }
        if (failed) {
            return;
        }
    }
    COMMAND_BUFFER_DEVICE->Blit(
        command_buffer,
        info);
}
References CHECK_ANY_PASS_IN_PROGRESS, CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, SDL_GPUBlitInfo::destination, SDL_GPUTextureCreateInfo::format, SDL_GPUBlitRegion::h, TextureCommonHeader::info, IsDepthFormat(), NULL, SDL_GPUTextureCreateInfo::sample_count, SDL_assert_release, SDL_GPU_SAMPLECOUNT_1, SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, SDL_GPU_TEXTUREUSAGE_SAMPLER, SDL_InvalidParamError, SDL_GPUBlitInfo::source, SDL_GPUBlitRegion::texture, SDL_GPUTextureCreateInfo::usage, and SDL_GPUBlitRegion::w.
SDL_CalculateGPUTextureFormatSize()
SDL_DECLSPEC Uint32 SDLCALL SDL_CalculateGPUTextureFormatSize (SDL_GPUTextureFormat format, Uint32 width, Uint32 height, Uint32 depth_or_layer_count) extern
Calculate the size in bytes of a texture format with dimensions.
Parameters
format a texture format.
width width in pixels.
height height in pixels.
depth_or_layer_count depth for 3D textures or layer count otherwise.
Returns
the size of a texture with this format and dimensions.
Since
This function is available since SDL 3.2.0.
{
    Uint32 blockWidth = SDL_max(Texture_GetBlockWidth(format), 1);
    Uint32 blockHeight = SDL_max(Texture_GetBlockHeight(format), 1);
    Uint32 blocksPerRow = (width + blockWidth - 1) / blockWidth;
    Uint32 blocksPerColumn = (height + blockHeight - 1) / blockHeight;
    return depth_or_layer_count * blocksPerRow * blocksPerColumn * SDL_GPUTextureFormatTexelBlockSize(format);
}
References SDL_GPUTextureFormatTexelBlockSize(), SDL_max, Texture_GetBlockHeight(), and Texture_GetBlockWidth().
SDL_CancelGPUCommandBuffer()
SDL_DECLSPEC bool SDLCALL SDL_CancelGPUCommandBuffer (SDL_GPUCommandBuffer * command_buffer) extern
Cancels a command buffer.
None of the enqueued commands are executed.
It is an error to call this function after a swapchain texture has been acquired.
This must be called from the thread the command buffer was acquired on.
You must not reference the command buffer after calling this function.
Parameters
command_buffer a command buffer.
Returns
true on success, false on error; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_AcquireGPUCommandBuffer
SDL_AcquireGPUSwapchainTexture
{
    CommandBufferCommonHeader *commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return false;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        if (commandBufferHeader->swapchain_texture_acquired) {
            SDL_assert_release(!"Cannot cancel command buffer after a swapchain texture has been acquired!");
            return false;
        }
    }
    return COMMAND_BUFFER_DEVICE->Cancel(
        command_buffer);
}
References COMMAND_BUFFER_DEVICE, NULL, SDL_assert_release, SDL_InvalidParamError, and CommandBufferCommonHeader::swapchain_texture_acquired.
SDL_ClaimWindowForGPUDevice()
SDL_DECLSPEC bool SDLCALL SDL_ClaimWindowForGPUDevice (SDL_GPUDevice * device, SDL_Window * window) extern
Claims a window, creating a swapchain structure for it.
This must be called before SDL_AcquireGPUSwapchainTexture is called using the window. You should only call this function from the thread that created the window.
The swapchain will be created with SDL_GPU_SWAPCHAINCOMPOSITION_SDR and SDL_GPU_PRESENTMODE_VSYNC. If you want to have different swapchain parameters, you must call SDL_SetGPUSwapchainParameters after claiming the window.
Parameters
device a GPU context.
window an SDL_Window.
Returns
true on success, or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called from the thread that created the window.
Since
This function is available since SDL 3.2.0.
See also
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_ReleaseWindowFromGPUDevice
SDL_WindowSupportsGPUPresentMode
SDL_WindowSupportsGPUSwapchainComposition
{
    CHECK_DEVICE_MAGIC(device, false);
    if (window == NULL) {
        return SDL_InvalidParamError("window");
    }
    if ((window->flags & SDL_WINDOW_TRANSPARENT) != 0) {
        return SDL_SetError("The GPU API doesn't support transparent windows");
    }
    return device->ClaimWindow(
        device->driverData,
        window);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::ClaimWindow, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, SDL_SetError(), and SDL_WINDOW_TRANSPARENT.
SDL_CopyGPUBufferToBuffer()
SDL_DECLSPEC void SDLCALL SDL_CopyGPUBufferToBuffer (SDL_GPUCopyPass * copy_pass, const SDL_GPUBufferLocation * source, const SDL_GPUBufferLocation * destination, Uint32 size, bool cycle) extern
Performs a buffer-to-buffer copy.
This copy occurs on the GPU timeline. You may assume the copy has finished in subsequent commands.
Parameters
copy_pass a copy pass handle.
source the buffer and offset to copy from.
destination the buffer and offset to copy to.
size the length of the buffer to copy.
cycle if true, cycles the destination buffer if it is already bound, otherwise overwrites the data.
Since
This function is available since SDL 3.2.0.
{
    if (copy_pass == NULL) {
        SDL_InvalidParamError("copy_pass");
        return;
    }
    if (source == NULL) {
        SDL_InvalidParamError("source");
        return;
    }
    if (destination == NULL) {
        SDL_InvalidParamError("destination");
        return;
    }
    if (COPYPASS_DEVICE->debug_mode) {
        CHECK_COPYPASS
        if (source->buffer == NULL) {
            SDL_assert_release(!"Source buffer cannot be NULL!");
            return;
        }
        if (destination->buffer == NULL) {
            SDL_assert_release(!"Destination buffer cannot be NULL!");
            return;
        }
    }
    COPYPASS_DEVICE->CopyBufferToBuffer(
        COPYPASS_COMMAND_BUFFER,
        source,
        destination,
        size,
        cycle);
}
References SDL_GPUBufferLocation::buffer, CHECK_COPYPASS, COPYPASS_COMMAND_BUFFER, COPYPASS_DEVICE, NULL, SDL_assert_release, and SDL_InvalidParamError.
SDL_CopyGPUTextureToTexture()
SDL_DECLSPEC void SDLCALL SDL_CopyGPUTextureToTexture (SDL_GPUCopyPass * copy_pass, const SDL_GPUTextureLocation * source, const SDL_GPUTextureLocation * destination, Uint32 w, Uint32 h, Uint32 d, bool cycle) extern
Performs a texture-to-texture copy.
This copy occurs on the GPU timeline. You may assume the copy has finished in subsequent commands.
Parameters
copy_pass a copy pass handle.
source a source texture region.
destination a destination texture region.
w the width of the region to copy.
h the height of the region to copy.
d the depth of the region to copy.
cycle if true, cycles the destination texture if the destination texture is bound, otherwise overwrites the data.
Since
This function is available since SDL 3.2.0.
{
    if (copy_pass == NULL) {
        SDL_InvalidParamError("copy_pass");
        return;
    }
    if (source == NULL) {
        SDL_InvalidParamError("source");
        return;
    }
    if (destination == NULL) {
        SDL_InvalidParamError("destination");
        return;
    }
    if (COPYPASS_DEVICE->debug_mode) {
        CHECK_COPYPASS
        if (source->texture == NULL) {
            SDL_assert_release(!"Source texture cannot be NULL!");
            return;
        }
        if (destination->texture == NULL) {
            SDL_assert_release(!"Destination texture cannot be NULL!");
            return;
        }
        TextureCommonHeader *srcHeader = (TextureCommonHeader *)source->texture;
        TextureCommonHeader *dstHeader = (TextureCommonHeader *)destination->texture;
        if (srcHeader->info.format != dstHeader->info.format) {
            SDL_assert_release(!"Source and destination textures must have the same format!");
            return;
        }
    }
    COPYPASS_DEVICE->CopyTextureToTexture(
        COPYPASS_COMMAND_BUFFER,
        source,
        destination,
        w,
        h,
        d,
        cycle);
}
References CHECK_COPYPASS, COPYPASS_COMMAND_BUFFER, COPYPASS_DEVICE, d, SDL_GPUTextureCreateInfo::format, TextureCommonHeader::info, NULL, SDL_assert_release, SDL_InvalidParamError, and SDL_GPUTextureLocation::texture.
SDL_CreateGPUBuffer()
SDL_DECLSPEC SDL_GPUBuffer *SDLCALL SDL_CreateGPUBuffer (SDL_GPUDevice * device, const SDL_GPUBufferCreateInfo * createinfo) extern
Creates a buffer object to be used in graphics or compute workflows.
The contents of this buffer are undefined until data is written to the buffer.
Note that certain combinations of usage flags are invalid. For example, a buffer cannot have both the VERTEX and INDEX flags.
If you use a STORAGE flag, the data in the buffer must respect std140 layout conventions. In practical terms this means you must ensure that vec3 and vec4 fields are 16-byte aligned.
For better understanding of underlying concepts and memory management with SDL GPU API, you may refer this blog post There are optional properties that can be provided through props. These are the supported properties:
SDL_PROP_GPU_BUFFER_CREATE_NAME_STRING: a name that can be displayed in debugging tools.
Parameters
device a GPU Context.
createinfo a struct describing the state of the buffer to create.
Returns
a buffer object on success, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_UploadToGPUBuffer
SDL_DownloadFromGPUBuffer
SDL_CopyGPUBufferToBuffer
SDL_BindGPUVertexBuffers
SDL_BindGPUIndexBuffer
SDL_BindGPUVertexStorageBuffers
SDL_BindGPUFragmentStorageBuffers
SDL_DrawGPUPrimitivesIndirect
SDL_DrawGPUIndexedPrimitivesIndirect
SDL_BindGPUComputeStorageBuffers
SDL_DispatchGPUComputeIndirect
SDL_ReleaseGPUBuffer
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (createinfo == NULL) {
        SDL_InvalidParamError("createinfo");
        return NULL;
    }
    const char *debugName = SDL_GetStringProperty(createinfo->props, SDL_PROP_GPU_BUFFER_CREATE_NAME_STRING, NULL);
    return device->CreateBuffer(
        device->driverData,
        createinfo->usage,
        createinfo->size,
        debugName);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::CreateBuffer, SDL_GPUDevice::driverData, NULL, SDL_GPUBufferCreateInfo::props, SDL_GetStringProperty(), SDL_InvalidParamError, SDL_PROP_GPU_BUFFER_CREATE_NAME_STRING, SDL_GPUBufferCreateInfo::size, and SDL_GPUBufferCreateInfo::usage.
SDL_CreateGPUComputePipeline()
SDL_DECLSPEC SDL_GPUComputePipeline *SDLCALL SDL_CreateGPUComputePipeline (SDL_GPUDevice * device, const SDL_GPUComputePipelineCreateInfo * createinfo) extern
Creates a pipeline object to be used in a compute workflow.
Shader resource bindings must be authored to follow a particular order depending on the shader format.
For SPIR-V shaders, use the following resource sets:
0: Sampled textures, followed by read-only storage textures, followed by read-only storage buffers
1: Read-write storage textures, followed by read-write storage buffers
2: Uniform buffers
For DXBC and DXIL shaders, use the following register order:
(t[n], space0): Sampled textures, followed by read-only storage textures, followed by read-only storage buffers
(u[n], space1): Read-write storage textures, followed by read-write storage buffers
(b[n], space2): Uniform buffers
For MSL/metallib, use the following order:
[[buffer]]: Uniform buffers, followed by read-only storage buffers, followed by read-write storage buffers
[[texture]]: Sampled textures, followed by read-only storage textures, followed by read-write storage textures
There are optional properties that can be provided through props. These are the supported properties:
SDL_PROP_GPU_COMPUTEPIPELINE_CREATE_NAME_STRING: a name that can be displayed in debugging tools.
Parameters
device a GPU Context.
createinfo a struct describing the state of the compute pipeline to create.
Returns
a compute pipeline object on success, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindGPUComputePipeline
SDL_ReleaseGPUComputePipeline
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (createinfo == NULL) {
        SDL_InvalidParamError("createinfo");
        return NULL;
    }
    if (device->debug_mode) {
        if (createinfo->format == SDL_GPU_SHADERFORMAT_INVALID) {
            SDL_assert_release(!"Shader format cannot be INVALID!");
            return NULL;
        }
        if (!(createinfo->format & device->shader_formats)) {
            SDL_assert_release(!"Incompatible shader format for GPU backend");
            return NULL;
        }
        if (createinfo->num_readwrite_storage_textures > MAX_COMPUTE_WRITE_TEXTURES) {
            SDL_assert_release(!"Compute pipeline write-only texture count cannot be higher than 8!");
            return NULL;
        }
        if (createinfo->num_readwrite_storage_buffers > MAX_COMPUTE_WRITE_BUFFERS) {
            SDL_assert_release(!"Compute pipeline write-only buffer count cannot be higher than 8!");
            return NULL;
        }
        if (createinfo->threadcount_x == 0 ||
            createinfo->threadcount_y == 0 ||
            createinfo->threadcount_z == 0) {
            SDL_assert_release(!"Compute pipeline threadCount dimensions must be at least 1!");
            return NULL;
        }
    }
    return device->CreateComputePipeline(
        device->driverData,
        createinfo);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::CreateComputePipeline, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, SDL_GPUComputePipelineCreateInfo::format, MAX_COMPUTE_WRITE_BUFFERS, MAX_COMPUTE_WRITE_TEXTURES, NULL, SDL_GPUComputePipelineCreateInfo::num_readwrite_storage_buffers, SDL_GPUComputePipelineCreateInfo::num_readwrite_storage_textures, SDL_assert_release, SDL_GPU_SHADERFORMAT_INVALID, SDL_InvalidParamError, SDL_GPUDevice::shader_formats, SDL_GPUComputePipelineCreateInfo::threadcount_x, SDL_GPUComputePipelineCreateInfo::threadcount_y, and SDL_GPUComputePipelineCreateInfo::threadcount_z.
SDL_CreateGPUDevice()
SDL_DECLSPEC SDL_GPUDevice *SDLCALL SDL_CreateGPUDevice (SDL_GPUShaderFormat format_flags, bool debug_mode, const char * name) extern
Creates a GPU context.
The GPU driver name can be one of the following:
"vulkan": Vulkan
"direct3d12": D3D12
"metal": Metal
NULL: let SDL pick the optimal driver
Parameters
format_flags a bitflag indicating which shader formats the app is able to provide.
debug_mode enable debug mode properties and validations.
name the preferred GPU driver, or NULL to let SDL pick the optimal driver.
Returns
a GPU context on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUDeviceWithProperties
SDL_GetGPUShaderFormats
SDL_GetGPUDeviceDriver
SDL_DestroyGPUDevice
SDL_GPUSupportsShaderFormats
{
#ifndef SDL_GPU_DISABLED
    SDL_GPUDevice *result;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_GPU_FillProperties(props, format_flags, debug_mode, name);
    result = SDL_CreateGPUDeviceWithProperties(props);
    SDL_DestroyProperties(props);
    return result;
#else
    SDL_SetError("SDL not built with GPU support");
    return NULL;
#endif // SDL_GPU_DISABLED
}
References NULL, SDL_CreateGPUDeviceWithProperties(), SDL_CreateProperties(), SDL_DestroyProperties(), SDL_GPU_FillProperties(), and SDL_SetError().
SDL_CreateGPUDeviceWithProperties()
SDL_DECLSPEC SDL_GPUDevice *SDLCALL SDL_CreateGPUDeviceWithProperties (SDL_PropertiesID props) extern
Creates a GPU context.
These are the supported properties:
SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOLEAN: enable debug mode properties and validations, defaults to true.
SDL_PROP_GPU_DEVICE_CREATE_PREFERLOWPOWER_BOOLEAN: enable to prefer energy efficiency over maximum GPU performance, defaults to false.
SDL_PROP_GPU_DEVICE_CREATE_VERBOSE_BOOLEAN: enable to automatically log useful debug information on device creation, defaults to true.
SDL_PROP_GPU_DEVICE_CREATE_NAME_STRING: the name of the GPU driver to use, if a specific one is desired.
These are the current shader format properties:
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_PRIVATE_BOOLEAN: The app is able to provide shaders for an NDA platform.
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_SPIRV_BOOLEAN: The app is able to provide SPIR-V shaders if applicable.
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXBC_BOOLEAN: The app is able to provide DXBC shaders if applicable
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_DXIL_BOOLEAN: The app is able to provide DXIL shaders if applicable.
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_MSL_BOOLEAN: The app is able to provide MSL shaders if applicable.
SDL_PROP_GPU_DEVICE_CREATE_SHADERS_METALLIB_BOOLEAN: The app is able to provide Metal shader libraries if applicable.
With the D3D12 renderer:
SDL_PROP_GPU_DEVICE_CREATE_D3D12_SEMANTIC_NAME_STRING: the prefix to use for all vertex semantics, default is "TEXCOORD".
With the Vulkan renderer:
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SHADERCLIPDISTANCE_BOOLEAN: Enable device feature shaderClipDistance. If disabled, clip distances are not supported in shader code: gl_ClipDistance[] built-ins of GLSL, SV_ClipDistance0/1 semantics of HLSL and [[clip_distance]] attribute of Metal. Defaults to true.
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DEPTHCLAMP_BOOLEAN: Enable device feature depthClamp. If disabled, there is no depth clamp support and enable_depth_clip in SDL_GPURasterizerState must always be set to true. Defaults to true.
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_DRAWINDIRECTFIRST_BOOLEAN: Enable device feature drawIndirectFirstInstance. If disabled, the argument first_instance of SDL_GPUIndirectDrawCommand must be set to zero. Defaults to true.
SDL_PROP_GPU_DEVICE_CREATE_VULKAN_SAMPLERANISOTROPY_BOOLEAN: Enable device feature samplerAnisotropy. If disabled, enable_anisotropy of SDL_GPUSamplerCreateInfo must be set to false. Defaults to true.
Parameters
props the properties to use.
Returns
a GPU context on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGPUShaderFormats
SDL_GetGPUDeviceDriver
SDL_DestroyGPUDevice
SDL_GPUSupportsProperties
{
#ifndef SDL_GPU_DISABLED
    bool debug_mode;
    bool preferLowPower;
    SDL_GPUDevice *result = NULL;
    const SDL_GPUBootstrap *selectedBackend;
    selectedBackend = SDL_GPUSelectBackend(props);
    if (selectedBackend != NULL) {
        SDL_DebugLogBackend("gpu", selectedBackend->name);
        debug_mode = SDL_GetBooleanProperty(props, SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOLEAN, true);
        preferLowPower = SDL_GetBooleanProperty(props, SDL_PROP_GPU_DEVICE_CREATE_PREFERLOWPOWER_BOOLEAN, false);
        result = selectedBackend->CreateDevice(debug_mode, preferLowPower, props);
        if (result != NULL) {
            result->backend = selectedBackend->name;
            result->debug_mode = debug_mode;
        }
    }
    return result;
#else
    SDL_SetError("SDL not built with GPU support");
    return NULL;
#endif // SDL_GPU_DISABLED
}
References SDL_GPUDevice::backend, SDL_GPUBootstrap::CreateDevice, SDL_GPUDevice::debug_mode, SDL_GPUBootstrap::name, NULL, SDL_DebugLogBackend(), SDL_GetBooleanProperty(), SDL_GPUSelectBackend(), SDL_PROP_GPU_DEVICE_CREATE_DEBUGMODE_BOOLEAN, SDL_PROP_GPU_DEVICE_CREATE_PREFERLOWPOWER_BOOLEAN, and SDL_SetError().
Referenced by SDL_CreateGPUDevice().
SDL_CreateGPUGraphicsPipeline()
SDL_DECLSPEC SDL_GPUGraphicsPipeline *SDLCALL SDL_CreateGPUGraphicsPipeline (SDL_GPUDevice * device, const SDL_GPUGraphicsPipelineCreateInfo * createinfo) extern
Creates a pipeline object to be used in a graphics workflow.
There are optional properties that can be provided through props. These are the supported properties:
SDL_PROP_GPU_GRAPHICSPIPELINE_CREATE_NAME_STRING: a name that can be displayed in debugging tools.
Parameters
device a GPU Context.
createinfo a struct describing the state of the graphics pipeline to create.
Returns
a graphics pipeline object on success, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUShader
SDL_BindGPUGraphicsPipeline
SDL_ReleaseGPUGraphicsPipeline
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (graphicsPipelineCreateInfo == NULL) {
        SDL_InvalidParamError("graphicsPipelineCreateInfo");
        return NULL;
    }
    if (device->debug_mode) {
        if (graphicsPipelineCreateInfo->vertex_shader == NULL) {
            SDL_assert_release(!"Vertex shader cannot be NULL!");
            return NULL;
        }
        if (graphicsPipelineCreateInfo->fragment_shader == NULL) {
            SDL_assert_release(!"Fragment shader cannot be NULL!");
            return NULL;
        }
        if (graphicsPipelineCreateInfo->target_info.num_color_targets > 0 && graphicsPipelineCreateInfo->target_info.color_target_descriptions == NULL) {
            SDL_assert_release(!"Color target descriptions array pointer cannot be NULL if num_color_targets is greater than zero!");
            return NULL;
        }
        for (Uint32 i = 0; i < graphicsPipelineCreateInfo->target_info.num_color_targets; i += 1) {
            CHECK_TEXTUREFORMAT_ENUM_INVALID(graphicsPipelineCreateInfo->target_info.color_target_descriptions[i].format, NULL);
            if (IsDepthFormat(graphicsPipelineCreateInfo->target_info.color_target_descriptions[i].format)) {
                SDL_assert_release(!"Color target formats cannot be a depth format!");
                return NULL;
            }
            if (!SDL_GPUTextureSupportsFormat(device, graphicsPipelineCreateInfo->target_info.color_target_descriptions[i].format, SDL_GPU_TEXTURETYPE_2D, SDL_GPU_TEXTUREUSAGE_COLOR_TARGET)) {
                SDL_assert_release(!"Format is not supported for color targets on this device!");
                return NULL;
            }
            if (graphicsPipelineCreateInfo->target_info.color_target_descriptions[i].blend_state.enable_blend) {
                const SDL_GPUColorTargetBlendState *blend_state = &graphicsPipelineCreateInfo->target_info.color_target_descriptions[i].blend_state;
                CHECK_BLENDFACTOR_ENUM_INVALID(blend_state->src_color_blendfactor, NULL)
                CHECK_BLENDFACTOR_ENUM_INVALID(blend_state->dst_color_blendfactor, NULL)
                CHECK_BLENDOP_ENUM_INVALID(blend_state->color_blend_op, NULL)
                CHECK_BLENDFACTOR_ENUM_INVALID(blend_state->src_alpha_blendfactor, NULL)
                CHECK_BLENDFACTOR_ENUM_INVALID(blend_state->dst_alpha_blendfactor, NULL)
                CHECK_BLENDOP_ENUM_INVALID(blend_state->alpha_blend_op, NULL)
                // TODO: validate that format support blending?
            }
        }
        if (graphicsPipelineCreateInfo->target_info.has_depth_stencil_target) {
            CHECK_TEXTUREFORMAT_ENUM_INVALID(graphicsPipelineCreateInfo->target_info.depth_stencil_format, NULL);
            if (!IsDepthFormat(graphicsPipelineCreateInfo->target_info.depth_stencil_format)) {
                SDL_assert_release(!"Depth-stencil target format must be a depth format!");
                return NULL;
            }
            if (!SDL_GPUTextureSupportsFormat(device, graphicsPipelineCreateInfo->target_info.depth_stencil_format, SDL_GPU_TEXTURETYPE_2D, SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET)) {
                SDL_assert_release(!"Format is not supported for depth targets on this device!");
                return NULL;
            }
        }
        if (graphicsPipelineCreateInfo->multisample_state.enable_alpha_to_coverage) {
            if (graphicsPipelineCreateInfo->target_info.num_color_targets < 1) {
                SDL_assert_release(!"Alpha-to-coverage enabled but no color targets present!");
                return NULL;
            }
            if (!FormatHasAlpha(graphicsPipelineCreateInfo->target_info.color_target_descriptions[0].format)) {
                SDL_assert_release(!"Format is not compatible with alpha-to-coverage!");
                return NULL;
            }
            // TODO: validate that format supports belnding? This is only required on Metal.
        }
        if (graphicsPipelineCreateInfo->vertex_input_state.num_vertex_buffers > 0 && graphicsPipelineCreateInfo->vertex_input_state.vertex_buffer_descriptions == NULL) {
            SDL_assert_release(!"Vertex buffer descriptions array pointer cannot be NULL!");
            return NULL;
        }
        if (graphicsPipelineCreateInfo->vertex_input_state.num_vertex_buffers > MAX_VERTEX_BUFFERS) {
            SDL_assert_release(!"The number of vertex buffer descriptions in a vertex input state must not exceed 16!");
            return NULL;
        }
        if (graphicsPipelineCreateInfo->vertex_input_state.num_vertex_attributes > 0 && graphicsPipelineCreateInfo->vertex_input_state.vertex_attributes == NULL) {
            SDL_assert_release(!"Vertex attributes array pointer cannot be NULL!");
            return NULL;
        }
        if (graphicsPipelineCreateInfo->vertex_input_state.num_vertex_attributes > MAX_VERTEX_ATTRIBUTES) {
            SDL_assert_release(!"The number of vertex attributes in a vertex input state must not exceed 16!");
            return NULL;
        }
        for (Uint32 i = 0; i < graphicsPipelineCreateInfo->vertex_input_state.num_vertex_buffers; i += 1) {
            if (graphicsPipelineCreateInfo->vertex_input_state.vertex_buffer_descriptions[i].instance_step_rate != 0) {
                SDL_assert_release(!"For all vertex buffer descriptions, instance_step_rate must be 0!");
                return NULL;
            }
        }
        Uint32 locations[MAX_VERTEX_ATTRIBUTES];
        for (Uint32 i = 0; i < graphicsPipelineCreateInfo->vertex_input_state.num_vertex_attributes; i += 1) {
            CHECK_VERTEXELEMENTFORMAT_ENUM_INVALID(graphicsPipelineCreateInfo->vertex_input_state.vertex_attributes[i].format, NULL);
            locations[i] = graphicsPipelineCreateInfo->vertex_input_state.vertex_attributes[i].location;
            for (Uint32 j = 0; j < i; j += 1) {
                if (locations[j] == locations[i]) {
                    SDL_assert_release(!"Each vertex attribute location in a vertex input state must be unique!");
                    return NULL;
                }
            }
        }
        if (graphicsPipelineCreateInfo->multisample_state.enable_mask) {
            SDL_assert_release(!"For multisample states, enable_mask must be false!");
            return NULL;
        }
        if (graphicsPipelineCreateInfo->multisample_state.sample_mask != 0) {
            SDL_assert_release(!"For multisample states, sample_mask must be 0!");
            return NULL;
        }
        if (graphicsPipelineCreateInfo->depth_stencil_state.enable_depth_test) {
            CHECK_COMPAREOP_ENUM_INVALID(graphicsPipelineCreateInfo->depth_stencil_state.compare_op, NULL)
        }
        if (graphicsPipelineCreateInfo->depth_stencil_state.enable_stencil_test) {
            const SDL_GPUStencilOpState *stencil_state = &graphicsPipelineCreateInfo->depth_stencil_state.back_stencil_state;
            CHECK_COMPAREOP_ENUM_INVALID(stencil_state->compare_op, NULL)
            CHECK_STENCILOP_ENUM_INVALID(stencil_state->fail_op, NULL)
            CHECK_STENCILOP_ENUM_INVALID(stencil_state->pass_op, NULL)
            CHECK_STENCILOP_ENUM_INVALID(stencil_state->depth_fail_op, NULL)
        }
    }
    return device->CreateGraphicsPipeline(
        device->driverData,
        graphicsPipelineCreateInfo);
}
References SDL_GPUColorTargetBlendState::alpha_blend_op, SDL_GPUDepthStencilState::back_stencil_state, SDL_GPUColorTargetDescription::blend_state, CHECK_BLENDFACTOR_ENUM_INVALID, CHECK_BLENDOP_ENUM_INVALID, CHECK_COMPAREOP_ENUM_INVALID, CHECK_DEVICE_MAGIC, CHECK_STENCILOP_ENUM_INVALID, CHECK_TEXTUREFORMAT_ENUM_INVALID, CHECK_VERTEXELEMENTFORMAT_ENUM_INVALID, SDL_GPUColorTargetBlendState::color_blend_op, SDL_GPUGraphicsPipelineTargetInfo::color_target_descriptions, SDL_GPUDepthStencilState::compare_op, SDL_GPUStencilOpState::compare_op, SDL_GPUDevice::CreateGraphicsPipeline, SDL_GPUDevice::debug_mode, SDL_GPUStencilOpState::depth_fail_op, SDL_GPUGraphicsPipelineTargetInfo::depth_stencil_format, SDL_GPUGraphicsPipelineCreateInfo::depth_stencil_state, SDL_GPUDevice::driverData, SDL_GPUColorTargetBlendState::dst_alpha_blendfactor, SDL_GPUColorTargetBlendState::dst_color_blendfactor, SDL_GPUMultisampleState::enable_alpha_to_coverage, SDL_GPUColorTargetBlendState::enable_blend, SDL_GPUDepthStencilState::enable_depth_test, SDL_GPUMultisampleState::enable_mask, SDL_GPUDepthStencilState::enable_stencil_test, SDL_GPUStencilOpState::fail_op, SDL_GPUColorTargetDescription::format, SDL_GPUVertexAttribute::format, FormatHasAlpha(), SDL_GPUGraphicsPipelineCreateInfo::fragment_shader, SDL_GPUGraphicsPipelineTargetInfo::has_depth_stencil_target, SDL_GPUVertexBufferDescription::instance_step_rate, IsDepthFormat(), SDL_GPUVertexAttribute::location, MAX_VERTEX_ATTRIBUTES, MAX_VERTEX_BUFFERS, SDL_GPUGraphicsPipelineCreateInfo::multisample_state, NULL, SDL_GPUGraphicsPipelineTargetInfo::num_color_targets, SDL_GPUVertexInputState::num_vertex_attributes, SDL_GPUVertexInputState::num_vertex_buffers, SDL_GPUStencilOpState::pass_op, SDL_GPUMultisampleState::sample_mask, SDL_assert_release, SDL_GPU_TEXTURETYPE_2D, SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET, SDL_GPUTextureSupportsFormat(), SDL_InvalidParamError, SDL_GPUColorTargetBlendState::src_alpha_blendfactor, SDL_GPUColorTargetBlendState::src_color_blendfactor, SDL_GPUGraphicsPipelineCreateInfo::target_info, SDL_GPUVertexInputState::vertex_attributes, SDL_GPUVertexInputState::vertex_buffer_descriptions, SDL_GPUGraphicsPipelineCreateInfo::vertex_input_state, and SDL_GPUGraphicsPipelineCreateInfo::vertex_shader.
Referenced by SDL_GPU_FetchBlitPipeline().
SDL_CreateGPUSampler()
SDL_DECLSPEC SDL_GPUSampler *SDLCALL SDL_CreateGPUSampler (SDL_GPUDevice * device, const SDL_GPUSamplerCreateInfo * createinfo) extern
Creates a sampler object to be used when binding textures in a graphics workflow.
There are optional properties that can be provided through props. These are the supported properties:
SDL_PROP_GPU_SAMPLER_CREATE_NAME_STRING: a name that can be displayed in debugging tools.
Parameters
device a GPU Context.
createinfo a struct describing the state of the sampler to create.
Returns
a sampler object on success, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindGPUVertexSamplers
SDL_BindGPUFragmentSamplers
SDL_ReleaseGPUSampler
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (createinfo == NULL) {
        SDL_InvalidParamError("createinfo");
        return NULL;
    }
    return device->CreateSampler(
        device->driverData,
        createinfo);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::CreateSampler, SDL_GPUDevice::driverData, NULL, and SDL_InvalidParamError.
SDL_CreateGPUShader()
SDL_DECLSPEC SDL_GPUShader *SDLCALL SDL_CreateGPUShader (SDL_GPUDevice * device, const SDL_GPUShaderCreateInfo * createinfo) extern
Creates a shader to be used when creating a graphics pipeline.
Shader resource bindings must be authored to follow a particular order depending on the shader format.
For SPIR-V shaders, use the following resource sets:
For vertex shaders:
0: Sampled textures, followed by storage textures, followed by storage buffers
1: Uniform buffers
For fragment shaders:
2: Sampled textures, followed by storage textures, followed by storage buffers
3: Uniform buffers
For DXBC and DXIL shaders, use the following register order:
For vertex shaders:
(t[n], space0): Sampled textures, followed by storage textures, followed by storage buffers
(s[n], space0): Samplers with indices corresponding to the sampled textures
(b[n], space1): Uniform buffers
For pixel shaders:
(t[n], space2): Sampled textures, followed by storage textures, followed by storage buffers
(s[n], space2): Samplers with indices corresponding to the sampled textures
(b[n], space3): Uniform buffers
For MSL/metallib, use the following order:
[[texture]]: Sampled textures, followed by storage textures
[[sampler]]: Samplers with indices corresponding to the sampled textures
[[buffer]]: Uniform buffers, followed by storage buffers. Vertex buffer 0 is bound at [[buffer(14)]], vertex buffer 1 at [[buffer(15)]], and so on. Rather than manually authoring vertex buffer indices, use the [[stage_in]] attribute which will automatically use the vertex input information from the SDL_GPUGraphicsPipeline.
Shader semantics other than system-value semantics do not matter in D3D12 and for ease of use the SDL implementation assumes that non system-value semantics will all be TEXCOORD. If you are using HLSL as the shader source language, your vertex semantics should start at TEXCOORD0 and increment like so: TEXCOORD1, TEXCOORD2, etc. If you wish to change the semantic prefix to something other than TEXCOORD you can use SDL_PROP_GPU_DEVICE_CREATE_D3D12_SEMANTIC_NAME_STRING with SDL_CreateGPUDeviceWithProperties().
There are optional properties that can be provided through props. These are the supported properties:
SDL_PROP_GPU_SHADER_CREATE_NAME_STRING: a name that can be displayed in debugging tools.
Parameters
device a GPU Context.
createinfo a struct describing the state of the shader to create.
Returns
a shader object on success, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUGraphicsPipeline
SDL_ReleaseGPUShader
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (createinfo == NULL) {
        SDL_InvalidParamError("createinfo");
        return NULL;
    }
    if (device->debug_mode) {
        if (createinfo->format == SDL_GPU_SHADERFORMAT_INVALID) {
            SDL_assert_release(!"Shader format cannot be INVALID!");
            return NULL;
        }
        if (!(createinfo->format & device->shader_formats)) {
            SDL_assert_release(!"Incompatible shader format for GPU backend");
            return NULL;
        }
    }
    return device->CreateShader(
        device->driverData,
        createinfo);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::CreateShader, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, SDL_GPUShaderCreateInfo::format, NULL, SDL_assert_release, SDL_GPU_SHADERFORMAT_INVALID, SDL_InvalidParamError, and SDL_GPUDevice::shader_formats.
SDL_CreateGPUTexture()
SDL_DECLSPEC SDL_GPUTexture *SDLCALL SDL_CreateGPUTexture (SDL_GPUDevice * device, const SDL_GPUTextureCreateInfo * createinfo) extern
Creates a texture object to be used in graphics or compute workflows.
The contents of this texture are undefined until data is written to the texture, either via SDL_UploadToGPUTexture or by performing a render or compute pass with this texture as a target.
Note that certain combinations of usage flags are invalid. For example, a texture cannot have both the SAMPLER and GRAPHICS_STORAGE_READ flags.
If you request a sample count higher than the hardware supports, the implementation will automatically fall back to the highest available sample count.
There are optional properties that can be provided through SDL_GPUTextureCreateInfo's props. These are the supported properties:
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_R_FLOAT: (Direct3D 12 only) if the texture usage is SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, clear the texture to a color with this red intensity. Defaults to zero.
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_G_FLOAT: (Direct3D 12 only) if the texture usage is SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, clear the texture to a color with this green intensity. Defaults to zero.
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_B_FLOAT: (Direct3D 12 only) if the texture usage is SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, clear the texture to a color with this blue intensity. Defaults to zero.
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_A_FLOAT: (Direct3D 12 only) if the texture usage is SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, clear the texture to a color with this alpha intensity. Defaults to zero.
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_DEPTH_FLOAT: (Direct3D 12 only) if the texture usage is SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET, clear the texture to a depth of this value. Defaults to zero.
SDL_PROP_GPU_TEXTURE_CREATE_D3D12_CLEAR_STENCIL_NUMBER: (Direct3D 12 only) if the texture usage is SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET, clear the texture to a stencil of this Uint8 value. Defaults to zero.
SDL_PROP_GPU_TEXTURE_CREATE_NAME_STRING: a name that can be displayed in debugging tools.
Parameters
device a GPU Context.
createinfo a struct describing the state of the texture to create.
Returns
a texture object on success, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_UploadToGPUTexture
SDL_DownloadFromGPUTexture
SDL_BeginGPURenderPass
SDL_BeginGPUComputePass
SDL_BindGPUVertexSamplers
SDL_BindGPUVertexStorageTextures
SDL_BindGPUFragmentSamplers
SDL_BindGPUFragmentStorageTextures
SDL_BindGPUComputeStorageTextures
SDL_BlitGPUTexture
SDL_ReleaseGPUTexture
SDL_GPUTextureSupportsFormat
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (createinfo == NULL) {
        SDL_InvalidParamError("createinfo");
        return NULL;
    }
    if (device->debug_mode) {
        bool failed = false;
        const Uint32 MAX_2D_DIMENSION = 16384;
        const Uint32 MAX_3D_DIMENSION = 2048;
        // Common checks for all texture types
        CHECK_TEXTUREFORMAT_ENUM_INVALID(createinfo->format, NULL)
        if (createinfo->width <= 0 || createinfo->height <= 0 || createinfo->layer_count_or_depth <= 0) {
            SDL_assert_release(!"For any texture: width, height, and layer_count_or_depth must be >= 1");
            failed = true;
        }
        if (createinfo->num_levels <= 0) {
            SDL_assert_release(!"For any texture: num_levels must be >= 1");
            failed = true;
        }
        if ((createinfo->usage & SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ) && (createinfo->usage & SDL_GPU_TEXTUREUSAGE_SAMPLER)) {
            SDL_assert_release(!"For any texture: usage cannot contain both GRAPHICS_STORAGE_READ and SAMPLER");
            failed = true;
        }
        if (createinfo->sample_count > SDL_GPU_SAMPLECOUNT_1 &&
            (createinfo->usage & (SDL_GPU_TEXTUREUSAGE_SAMPLER |
                                  SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ |
                                  SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ |
                                  SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE))) {
            SDL_assert_release(!"For multisample textures: usage cannot contain SAMPLER or STORAGE flags");
            failed = true;
        }
        if (IsDepthFormat(createinfo->format) && (createinfo->usage & ~(SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET | SDL_GPU_TEXTUREUSAGE_SAMPLER))) {
            SDL_assert_release(!"For depth textures: usage cannot contain any flags except for DEPTH_STENCIL_TARGET and SAMPLER");
            failed = true;
        }
        if (IsIntegerFormat(createinfo->format) && (createinfo->usage & SDL_GPU_TEXTUREUSAGE_SAMPLER)) {
            SDL_assert_release(!"For any texture: usage cannot contain SAMPLER for textures with an integer format");
            failed = true;
        }
        if (createinfo->type == SDL_GPU_TEXTURETYPE_CUBE) {
            // Cubemap validation
            if (createinfo->width != createinfo->height) {
                SDL_assert_release(!"For cube textures: width and height must be identical");
                failed = true;
            }
            if (createinfo->width > MAX_2D_DIMENSION || createinfo->height > MAX_2D_DIMENSION) {
                SDL_assert_release(!"For cube textures: width and height must be <= 16384");
                failed = true;
            }
            if (createinfo->layer_count_or_depth != 6) {
                SDL_assert_release(!"For cube textures: layer_count_or_depth must be 6");
                failed = true;
            }
            if (createinfo->sample_count > SDL_GPU_SAMPLECOUNT_1) {
                SDL_assert_release(!"For cube textures: sample_count must be SDL_GPU_SAMPLECOUNT_1");
                failed = true;
            }
            if (!SDL_GPUTextureSupportsFormat(device, createinfo->format, SDL_GPU_TEXTURETYPE_CUBE, createinfo->usage)) {
                SDL_assert_release(!"For cube textures: the format is unsupported for the given usage");
                failed = true;
            }
        } else if (createinfo->type == SDL_GPU_TEXTURETYPE_CUBE_ARRAY) {
            // Cubemap array validation
            if (createinfo->width != createinfo->height) {
                SDL_assert_release(!"For cube array textures: width and height must be identical");
                failed = true;
            }
            if (createinfo->width > MAX_2D_DIMENSION || createinfo->height > MAX_2D_DIMENSION) {
                SDL_assert_release(!"For cube array textures: width and height must be <= 16384");
                failed = true;
            }
            if (createinfo->layer_count_or_depth % 6 != 0) {
                SDL_assert_release(!"For cube array textures: layer_count_or_depth must be a multiple of 6");
                failed = true;
            }
            if (createinfo->sample_count > SDL_GPU_SAMPLECOUNT_1) {
                SDL_assert_release(!"For cube array textures: sample_count must be SDL_GPU_SAMPLECOUNT_1");
                failed = true;
            }
            if (!SDL_GPUTextureSupportsFormat(device, createinfo->format, SDL_GPU_TEXTURETYPE_CUBE_ARRAY, createinfo->usage)) {
                SDL_assert_release(!"For cube array textures: the format is unsupported for the given usage");
                failed = true;
            }
        } else if (createinfo->type == SDL_GPU_TEXTURETYPE_3D) {
            // 3D Texture Validation
            if (createinfo->width > MAX_3D_DIMENSION || createinfo->height > MAX_3D_DIMENSION || createinfo->layer_count_or_depth > MAX_3D_DIMENSION) {
                SDL_assert_release(!"For 3D textures: width, height, and layer_count_or_depth must be <= 2048");
                failed = true;
            }
            if (createinfo->usage & SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET) {
                SDL_assert_release(!"For 3D textures: usage must not contain DEPTH_STENCIL_TARGET");
                failed = true;
            }
            if (createinfo->sample_count > SDL_GPU_SAMPLECOUNT_1) {
                SDL_assert_release(!"For 3D textures: sample_count must be SDL_GPU_SAMPLECOUNT_1");
                failed = true;
            }
            if (!SDL_GPUTextureSupportsFormat(device, createinfo->format, SDL_GPU_TEXTURETYPE_3D, createinfo->usage)) {
                SDL_assert_release(!"For 3D textures: the format is unsupported for the given usage");
                failed = true;
            }
        } else {
            if (createinfo->type == SDL_GPU_TEXTURETYPE_2D_ARRAY) {
                // Array Texture Validation
                if (createinfo->usage & SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET) {
                    SDL_assert_release(!"For array textures: usage must not contain DEPTH_STENCIL_TARGET");
                    failed = true;
                }
                if (createinfo->sample_count > SDL_GPU_SAMPLECOUNT_1) {
                    SDL_assert_release(!"For array textures: sample_count must be SDL_GPU_SAMPLECOUNT_1");
                    failed = true;
                }
            }
            if (createinfo->sample_count > SDL_GPU_SAMPLECOUNT_1 && createinfo->num_levels > 1) {
                SDL_assert_release(!"For 2D multisample textures: num_levels must be 1");
                failed = true;
            }
            if (!SDL_GPUTextureSupportsFormat(device, createinfo->format, SDL_GPU_TEXTURETYPE_2D, createinfo->usage)) {
                SDL_assert_release(!"For 2D textures: the format is unsupported for the given usage");
                failed = true;
            }
        }
        if (failed) {
            return NULL;
        }
    }
    return device->CreateTexture(
        device->driverData,
        createinfo);
}
References CHECK_DEVICE_MAGIC, CHECK_TEXTUREFORMAT_ENUM_INVALID, SDL_GPUDevice::CreateTexture, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, SDL_GPUTextureCreateInfo::format, SDL_GPUTextureCreateInfo::height, IsDepthFormat(), IsIntegerFormat(), SDL_GPUTextureCreateInfo::layer_count_or_depth, NULL, SDL_GPUTextureCreateInfo::num_levels, SDL_GPUTextureCreateInfo::sample_count, SDL_assert_release, SDL_GPU_SAMPLECOUNT_1, SDL_GPU_TEXTURETYPE_2D, SDL_GPU_TEXTURETYPE_2D_ARRAY, SDL_GPU_TEXTURETYPE_3D, SDL_GPU_TEXTURETYPE_CUBE, SDL_GPU_TEXTURETYPE_CUBE_ARRAY, SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ, SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE, SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET, SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ, SDL_GPU_TEXTUREUSAGE_SAMPLER, SDL_GPUTextureSupportsFormat(), SDL_InvalidParamError, SDL_GPUTextureCreateInfo::type, SDL_GPUTextureCreateInfo::usage, and SDL_GPUTextureCreateInfo::width.
SDL_CreateGPUTransferBuffer()
SDL_DECLSPEC SDL_GPUTransferBuffer *SDLCALL SDL_CreateGPUTransferBuffer (SDL_GPUDevice * device, const SDL_GPUTransferBufferCreateInfo * createinfo) extern
Creates a transfer buffer to be used when uploading to or downloading from graphics resources.
Download buffers can be particularly expensive to create, so it is good practice to reuse them if data will be downloaded regularly.
There are optional properties that can be provided through props. These are the supported properties:
SDL_PROP_GPU_TRANSFERBUFFER_CREATE_NAME_STRING: a name that can be displayed in debugging tools.
Parameters
device a GPU Context.
createinfo a struct describing the state of the transfer buffer to create.
Returns
a transfer buffer on success, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_UploadToGPUBuffer
SDL_DownloadFromGPUBuffer
SDL_UploadToGPUTexture
SDL_DownloadFromGPUTexture
SDL_ReleaseGPUTransferBuffer
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (createinfo == NULL) {
        SDL_InvalidParamError("createinfo");
        return NULL;
    }
    const char *debugName = SDL_GetStringProperty(createinfo->props, SDL_PROP_GPU_TRANSFERBUFFER_CREATE_NAME_STRING, NULL);
    return device->CreateTransferBuffer(
        device->driverData,
        createinfo->usage,
        createinfo->size,
        debugName);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::CreateTransferBuffer, SDL_GPUDevice::driverData, NULL, SDL_GPUTransferBufferCreateInfo::props, SDL_GetStringProperty(), SDL_InvalidParamError, SDL_PROP_GPU_TRANSFERBUFFER_CREATE_NAME_STRING, SDL_GPUTransferBufferCreateInfo::size, and SDL_GPUTransferBufferCreateInfo::usage.
SDL_DestroyGPUDevice()
SDL_DECLSPEC void SDLCALL SDL_DestroyGPUDevice (SDL_GPUDevice * device) extern
Destroys a GPU context previously returned by SDL_CreateGPUDevice.
Parameters
device a GPU Context to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUDevice
{
    CHECK_DEVICE_MAGIC(device, );
    device->DestroyDevice(device);
}
References CHECK_DEVICE_MAGIC, and SDL_GPUDevice::DestroyDevice.
SDL_DispatchGPUCompute()
SDL_DECLSPEC void SDLCALL SDL_DispatchGPUCompute (SDL_GPUComputePass * compute_pass, Uint32 groupcount_x, Uint32 groupcount_y, Uint32 groupcount_z) extern
Dispatches compute work.
You must not call this function before binding a compute pipeline.
A VERY IMPORTANT NOTE If you dispatch multiple times in a compute pass, and the dispatches write to the same resource region as each other, there is no guarantee of which order the writes will occur. If the write order matters, you MUST end the compute pass and begin another one.
Parameters
compute_pass a compute pass handle.
groupcount_x number of local workgroups to dispatch in the X dimension.
groupcount_y number of local workgroups to dispatch in the Y dimension.
groupcount_z number of local workgroups to dispatch in the Z dimension.
Since
This function is available since SDL 3.2.0.
{
    if (compute_pass == NULL) {
        SDL_InvalidParamError("compute_pass");
        return;
    }
    if (COMPUTEPASS_DEVICE->debug_mode) {
        CHECK_COMPUTEPASS
        CHECK_COMPUTE_PIPELINE_BOUND
        SDL_GPU_CheckComputeBindings(compute_pass);
    }
    COMPUTEPASS_DEVICE->DispatchCompute(
        COMPUTEPASS_COMMAND_BUFFER,
        groupcount_x,
        groupcount_y,
        groupcount_z);
}
References CHECK_COMPUTE_PIPELINE_BOUND, CHECK_COMPUTEPASS, COMPUTEPASS_COMMAND_BUFFER, COMPUTEPASS_DEVICE, NULL, SDL_GPU_CheckComputeBindings(), and SDL_InvalidParamError.
SDL_DispatchGPUComputeIndirect()
SDL_DECLSPEC void SDLCALL SDL_DispatchGPUComputeIndirect (SDL_GPUComputePass * compute_pass, SDL_GPUBuffer * buffer, Uint32 offset) extern
Dispatches compute work with parameters set from a buffer.
The buffer layout should match the layout of SDL_GPUIndirectDispatchCommand. You must not call this function before binding a compute pipeline.
A VERY IMPORTANT NOTE If you dispatch multiple times in a compute pass, and the dispatches write to the same resource region as each other, there is no guarantee of which order the writes will occur. If the write order matters, you MUST end the compute pass and begin another one.
Parameters
compute_pass a compute pass handle.
buffer a buffer containing dispatch parameters.
offset the offset to start reading from the dispatch buffer.
Since
This function is available since SDL 3.2.0.
{
    if (compute_pass == NULL) {
        SDL_InvalidParamError("compute_pass");
        return;
    }
    if (COMPUTEPASS_DEVICE->debug_mode) {
        CHECK_COMPUTEPASS
        CHECK_COMPUTE_PIPELINE_BOUND
        SDL_GPU_CheckComputeBindings(compute_pass);
    }
    COMPUTEPASS_DEVICE->DispatchComputeIndirect(
        COMPUTEPASS_COMMAND_BUFFER,
        buffer,
        offset);
}
References CHECK_COMPUTE_PIPELINE_BOUND, CHECK_COMPUTEPASS, COMPUTEPASS_COMMAND_BUFFER, COMPUTEPASS_DEVICE, NULL, SDL_GPU_CheckComputeBindings(), and SDL_InvalidParamError.
SDL_DownloadFromGPUBuffer()
SDL_DECLSPEC void SDLCALL SDL_DownloadFromGPUBuffer (SDL_GPUCopyPass * copy_pass, const SDL_GPUBufferRegion * source, const SDL_GPUTransferBufferLocation * destination) extern
Copies data from a buffer to a transfer buffer on the GPU timeline.
This data is not guaranteed to be copied until the command buffer fence is signaled.
Parameters
copy_pass a copy pass handle.
source the source buffer with offset and size.
destination the destination transfer buffer with offset.
Since
This function is available since SDL 3.2.0.
{
    if (copy_pass == NULL) {
        SDL_InvalidParamError("copy_pass");
        return;
    }
    if (source == NULL) {
        SDL_InvalidParamError("source");
        return;
    }
    if (destination == NULL) {
        SDL_InvalidParamError("destination");
        return;
    }
    if (COPYPASS_DEVICE->debug_mode) {
        CHECK_COPYPASS
        if (source->buffer == NULL) {
            SDL_assert_release(!"Source buffer cannot be NULL!");
            return;
        }
        if (destination->transfer_buffer == NULL) {
            SDL_assert_release(!"Destination transfer buffer cannot be NULL!");
            return;
        }
    }
    COPYPASS_DEVICE->DownloadFromBuffer(
        COPYPASS_COMMAND_BUFFER,
        source,
        destination);
}
References SDL_GPUBufferRegion::buffer, CHECK_COPYPASS, COPYPASS_COMMAND_BUFFER, COPYPASS_DEVICE, NULL, SDL_assert_release, SDL_InvalidParamError, and SDL_GPUTransferBufferLocation::transfer_buffer.
SDL_DownloadFromGPUTexture()
SDL_DECLSPEC void SDLCALL SDL_DownloadFromGPUTexture (SDL_GPUCopyPass * copy_pass, const SDL_GPUTextureRegion * source, const SDL_GPUTextureTransferInfo * destination) extern
Copies data from a texture to a transfer buffer on the GPU timeline.
This data is not guaranteed to be copied until the command buffer fence is signaled.
Parameters
copy_pass a copy pass handle.
source the source texture region.
destination the destination transfer buffer with image layout information.
Since
This function is available since SDL 3.2.0.
{
    if (copy_pass == NULL) {
        SDL_InvalidParamError("copy_pass");
        return;
    }
    if (source == NULL) {
        SDL_InvalidParamError("source");
        return;
    }
    if (destination == NULL) {
        SDL_InvalidParamError("destination");
        return;
    }
    if (COPYPASS_DEVICE->debug_mode) {
        CHECK_COPYPASS
        if (source->texture == NULL) {
            SDL_assert_release(!"Source texture cannot be NULL!");
            return;
        }
        if (destination->transfer_buffer == NULL) {
            SDL_assert_release(!"Destination transfer buffer cannot be NULL!");
            return;
        }
    }
    COPYPASS_DEVICE->DownloadFromTexture(
        COPYPASS_COMMAND_BUFFER,
        source,
        destination);
}
References CHECK_COPYPASS, COPYPASS_COMMAND_BUFFER, COPYPASS_DEVICE, NULL, SDL_assert_release, SDL_InvalidParamError, SDL_GPUTextureRegion::texture, and SDL_GPUTextureTransferInfo::transfer_buffer.
SDL_DrawGPUIndexedPrimitives()
SDL_DECLSPEC void SDLCALL SDL_DrawGPUIndexedPrimitives (SDL_GPURenderPass * render_pass, Uint32 num_indices, Uint32 num_instances, Uint32 first_index, Sint32 vertex_offset, Uint32 first_instance) extern
Draws data using bound graphics state with an index buffer and instancing enabled.
You must not call this function before binding a graphics pipeline.
Note that the first_vertex and first_instance parameters are NOT compatible with built-in vertex/instance ID variables in shaders (for example, SV_VertexID); GPU APIs and shader languages do not define these built-in variables consistently, so if your shader depends on them, the only way to keep behavior consistent and portable is to always pass 0 for the correlating parameter in the draw calls.
Parameters
render_pass a render pass handle.
num_indices the number of indices to draw per instance.
num_instances the number of instances to draw.
first_index the starting index within the index buffer.
vertex_offset value added to vertex index before indexing into the vertex buffer.
first_instance the ID of the first instance to draw.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        CHECK_GRAPHICS_PIPELINE_BOUND
        SDL_GPU_CheckGraphicsBindings(render_pass);
    }
    RENDERPASS_DEVICE->DrawIndexedPrimitives(
        RENDERPASS_COMMAND_BUFFER,
        num_indices,
        num_instances,
        first_index,
        vertex_offset,
        first_instance);
}
References CHECK_GRAPHICS_PIPELINE_BOUND, CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, SDL_GPU_CheckGraphicsBindings(), and SDL_InvalidParamError.
SDL_DrawGPUIndexedPrimitivesIndirect()
SDL_DECLSPEC void SDLCALL SDL_DrawGPUIndexedPrimitivesIndirect (SDL_GPURenderPass * render_pass, SDL_GPUBuffer * buffer, Uint32 offset, Uint32 draw_count) extern
Draws data using bound graphics state with an index buffer enabled and with draw parameters set from a buffer.
The buffer must consist of tightly-packed draw parameter sets that each match the layout of SDL_GPUIndexedIndirectDrawCommand. You must not call this function before binding a graphics pipeline.
Parameters
render_pass a render pass handle.
buffer a buffer containing draw parameters.
offset the offset to start reading from the draw buffer.
draw_count the number of draw parameter sets that should be read from the draw buffer.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (buffer == NULL) {
        SDL_InvalidParamError("buffer");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        CHECK_GRAPHICS_PIPELINE_BOUND
        SDL_GPU_CheckGraphicsBindings(render_pass);
    }
    RENDERPASS_DEVICE->DrawIndexedPrimitivesIndirect(
        RENDERPASS_COMMAND_BUFFER,
        buffer,
        offset,
        draw_count);
}
References CHECK_GRAPHICS_PIPELINE_BOUND, CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, SDL_GPU_CheckGraphicsBindings(), and SDL_InvalidParamError.
SDL_DrawGPUPrimitives()
SDL_DECLSPEC void SDLCALL SDL_DrawGPUPrimitives (SDL_GPURenderPass * render_pass, Uint32 num_vertices, Uint32 num_instances, Uint32 first_vertex, Uint32 first_instance) extern
Draws data using bound graphics state.
You must not call this function before binding a graphics pipeline.
Note that the first_vertex and first_instance parameters are NOT compatible with built-in vertex/instance ID variables in shaders (for example, SV_VertexID); GPU APIs and shader languages do not define these built-in variables consistently, so if your shader depends on them, the only way to keep behavior consistent and portable is to always pass 0 for the correlating parameter in the draw calls.
Parameters
render_pass a render pass handle.
num_vertices the number of vertices to draw.
num_instances the number of instances that will be drawn.
first_vertex the index of the first vertex to draw.
first_instance the ID of the first instance to draw.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        CHECK_GRAPHICS_PIPELINE_BOUND
        SDL_GPU_CheckGraphicsBindings(render_pass);
    }
    RENDERPASS_DEVICE->DrawPrimitives(
        RENDERPASS_COMMAND_BUFFER,
        num_vertices,
        num_instances,
        first_vertex,
        first_instance);
}
References CHECK_GRAPHICS_PIPELINE_BOUND, CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, SDL_GPU_CheckGraphicsBindings(), and SDL_InvalidParamError.
Referenced by SDL_GPU_BlitCommon().
SDL_DrawGPUPrimitivesIndirect()
SDL_DECLSPEC void SDLCALL SDL_DrawGPUPrimitivesIndirect (SDL_GPURenderPass * render_pass, SDL_GPUBuffer * buffer, Uint32 offset, Uint32 draw_count) extern
Draws data using bound graphics state and with draw parameters set from a buffer.
The buffer must consist of tightly-packed draw parameter sets that each match the layout of SDL_GPUIndirectDrawCommand. You must not call this function before binding a graphics pipeline.
Parameters
render_pass a render pass handle.
buffer a buffer containing draw parameters.
offset the offset to start reading from the draw buffer.
draw_count the number of draw parameter sets that should be read from the draw buffer.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (buffer == NULL) {
        SDL_InvalidParamError("buffer");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
        CHECK_GRAPHICS_PIPELINE_BOUND
        SDL_GPU_CheckGraphicsBindings(render_pass);
    }
    RENDERPASS_DEVICE->DrawPrimitivesIndirect(
        RENDERPASS_COMMAND_BUFFER,
        buffer,
        offset,
        draw_count);
}
References CHECK_GRAPHICS_PIPELINE_BOUND, CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, SDL_GPU_CheckGraphicsBindings(), and SDL_InvalidParamError.
SDL_EndGPUComputePass()
SDL_DECLSPEC void SDLCALL SDL_EndGPUComputePass (SDL_GPUComputePass * compute_pass) extern
Ends the current compute pass.
All bound compute state on the command buffer is unset. The compute pass handle is now invalid.
Parameters
compute_pass a compute pass handle.
Since
This function is available since SDL 3.2.0.
{
    CommandBufferCommonHeader *commandBufferCommonHeader;
    if (compute_pass == NULL) {
        SDL_InvalidParamError("compute_pass");
        return;
    }
    if (COMPUTEPASS_DEVICE->debug_mode) {
        CHECK_COMPUTEPASS
    }
    COMPUTEPASS_DEVICE->EndComputePass(
        COMPUTEPASS_COMMAND_BUFFER);
    if (COMPUTEPASS_DEVICE->debug_mode) {
        commandBufferCommonHeader = (CommandBufferCommonHeader *)COMPUTEPASS_COMMAND_BUFFER;
        commandBufferCommonHeader->compute_pass.in_progress = false;
        commandBufferCommonHeader->compute_pass.compute_pipeline = NULL;
        SDL_zeroa(commandBufferCommonHeader->compute_pass.sampler_bound);
        SDL_zeroa(commandBufferCommonHeader->compute_pass.read_only_storage_texture_bound);
        SDL_zeroa(commandBufferCommonHeader->compute_pass.read_only_storage_buffer_bound);
        SDL_zeroa(commandBufferCommonHeader->compute_pass.read_write_storage_texture_bound);
        SDL_zeroa(commandBufferCommonHeader->compute_pass.read_write_storage_buffer_bound);
    }
}
References CHECK_COMPUTEPASS, CommandBufferCommonHeader::compute_pass, ComputePass::compute_pipeline, COMPUTEPASS_COMMAND_BUFFER, COMPUTEPASS_DEVICE, ComputePass::in_progress, NULL, ComputePass::read_only_storage_buffer_bound, ComputePass::read_only_storage_texture_bound, ComputePass::read_write_storage_buffer_bound, ComputePass::read_write_storage_texture_bound, ComputePass::sampler_bound, SDL_InvalidParamError, and SDL_zeroa.
SDL_EndGPUCopyPass()
SDL_DECLSPEC void SDLCALL SDL_EndGPUCopyPass (SDL_GPUCopyPass * copy_pass) extern
Ends the current copy pass.
Parameters
copy_pass a copy pass handle.
Since
This function is available since SDL 3.2.0.
{
    if (copy_pass == NULL) {
        SDL_InvalidParamError("copy_pass");
        return;
    }
    if (COPYPASS_DEVICE->debug_mode) {
        CHECK_COPYPASS
    }
    COPYPASS_DEVICE->EndCopyPass(
        COPYPASS_COMMAND_BUFFER);
    if (COPYPASS_DEVICE->debug_mode) {
        ((CommandBufferCommonHeader *)COPYPASS_COMMAND_BUFFER)->copy_pass.in_progress = false;
    }
}
References CHECK_COPYPASS, COPYPASS_COMMAND_BUFFER, COPYPASS_DEVICE, NULL, and SDL_InvalidParamError.
SDL_EndGPURenderPass()
SDL_DECLSPEC void SDLCALL SDL_EndGPURenderPass (SDL_GPURenderPass * render_pass) extern
Ends the given render pass.
All bound graphics state on the render pass command buffer is unset. The render pass handle is now invalid.
Parameters
render_pass a render pass handle.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    CommandBufferCommonHeader *commandBufferCommonHeader;
    commandBufferCommonHeader = (CommandBufferCommonHeader *)RENDERPASS_COMMAND_BUFFER;
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
    }
    RENDERPASS_DEVICE->EndRenderPass(
        RENDERPASS_COMMAND_BUFFER);
    if (RENDERPASS_DEVICE->debug_mode) {
        commandBufferCommonHeader->render_pass.in_progress = false;
        for (Uint32 i = 0; i < MAX_COLOR_TARGET_BINDINGS; i += 1)
        {
            commandBufferCommonHeader->render_pass.color_targets[i] = NULL;
        }
        commandBufferCommonHeader->render_pass.num_color_targets = 0;
        commandBufferCommonHeader->render_pass.depth_stencil_target = NULL;
        commandBufferCommonHeader->render_pass.graphics_pipeline = NULL;
        SDL_zeroa(commandBufferCommonHeader->render_pass.vertex_sampler_bound);
        SDL_zeroa(commandBufferCommonHeader->render_pass.vertex_storage_texture_bound);
        SDL_zeroa(commandBufferCommonHeader->render_pass.vertex_storage_buffer_bound);
        SDL_zeroa(commandBufferCommonHeader->render_pass.fragment_sampler_bound);
        SDL_zeroa(commandBufferCommonHeader->render_pass.fragment_storage_texture_bound);
        SDL_zeroa(commandBufferCommonHeader->render_pass.fragment_storage_buffer_bound);
    }
}
References CHECK_RENDERPASS, RenderPass::color_targets, RenderPass::depth_stencil_target, RenderPass::fragment_sampler_bound, RenderPass::fragment_storage_buffer_bound, RenderPass::fragment_storage_texture_bound, RenderPass::graphics_pipeline, RenderPass::in_progress, MAX_COLOR_TARGET_BINDINGS, NULL, RenderPass::num_color_targets, CommandBufferCommonHeader::render_pass, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, SDL_InvalidParamError, SDL_zeroa, RenderPass::vertex_sampler_bound, RenderPass::vertex_storage_buffer_bound, and RenderPass::vertex_storage_texture_bound.
Referenced by SDL_GPU_BlitCommon().
SDL_GenerateMipmapsForGPUTexture()
SDL_DECLSPEC void SDLCALL SDL_GenerateMipmapsForGPUTexture (SDL_GPUCommandBuffer * command_buffer, SDL_GPUTexture * texture) extern
Generates mipmaps for the given texture.
This function must not be called inside of any pass.
Parameters
command_buffer a command_buffer.
texture a texture with more than 1 mip level.
Since
This function is available since SDL 3.2.0.
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (texture == NULL) {
        SDL_InvalidParamError("texture");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
        CHECK_ANY_PASS_IN_PROGRESS("Cannot generate mipmaps during a pass!", )
        TextureCommonHeader *header = (TextureCommonHeader *)texture;
        if (header->info.num_levels <= 1) {
            SDL_assert_release(!"Cannot generate mipmaps for texture with num_levels <= 1!");
            return;
        }
        if (!(header->info.usage & SDL_GPU_TEXTUREUSAGE_SAMPLER) || !(header->info.usage & SDL_GPU_TEXTUREUSAGE_COLOR_TARGET)) {
            SDL_assert_release(!"GenerateMipmaps texture must be created with SAMPLER and COLOR_TARGET usage flags!");
            return;
        }
        CommandBufferCommonHeader *commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
        commandBufferHeader->ignore_render_pass_texture_validation = true;
    }
    COMMAND_BUFFER_DEVICE->GenerateMipmaps(
        command_buffer,
        texture);
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CommandBufferCommonHeader *commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
        commandBufferHeader->ignore_render_pass_texture_validation = false;
    }
}
References CHECK_ANY_PASS_IN_PROGRESS, CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, CommandBufferCommonHeader::ignore_render_pass_texture_validation, NULL, SDL_assert_release, SDL_GPU_TEXTUREUSAGE_COLOR_TARGET, SDL_GPU_TEXTUREUSAGE_SAMPLER, and SDL_InvalidParamError.
SDL_GetGPUDeviceDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetGPUDeviceDriver (SDL_GPUDevice * device) extern
Returns the name of the backend used to create this GPU context.
Parameters
device a GPU context to query.
Returns
the name of the device's driver, or NULL on error.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, NULL);
    return device->backend;
}
References SDL_GPUDevice::backend, CHECK_DEVICE_MAGIC, and NULL.
SDL_GetGPUDeviceProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetGPUDeviceProperties (SDL_GPUDevice * device) extern
Get the properties associated with a GPU device.
All properties are optional and may differ between GPU backends and SDL versions.
The following properties are provided by SDL:
SDL_PROP_GPU_DEVICE_NAME_STRING: Contains the name of the underlying device as reported by the system driver. This string has no standardized format, is highly inconsistent between hardware devices and drivers, and is able to change at any time. Do not attempt to parse this string as it is bound to fail at some point in the future when system drivers are updated, new hardware devices are introduced, or when SDL adds new GPU backends or modifies existing ones.
Strings that have been found in the wild include:
GTX 970
GeForce GTX 970
NVIDIA GeForce GTX 970
Microsoft Direct3D12 (NVIDIA GeForce GTX 970)
NVIDIA Graphics Device
GeForce GPU
P106-100
AMD 15D8:C9
AMD Custom GPU 0405
AMD Radeon (TM) Graphics
ASUS Radeon RX 470 Series
Intel(R) Arc(tm) A380 Graphics (DG2)
Virtio-GPU Venus (NVIDIA TITAN V)
SwiftShader Device (LLVM 16.0.0)
llvmpipe (LLVM 15.0.4, 256 bits)
Microsoft Basic Render Driver
unknown device
The above list shows that the same device can have different formats, the vendor name may or may not appear in the string, the included vendor name may not be the vendor of the chipset on the device, some manufacturers include pseudo-legal marks while others don't, some devices may not use a marketing name in the string, the device string may be wrapped by the name of a translation interface, the device may be emulated in software, or the string may contain generic text that does not identify the device at all.
SDL_PROP_GPU_DEVICE_DRIVER_NAME_STRING: Contains the self-reported name of the underlying system driver.
Strings that have been found in the wild include:
Intel Corporation
Intel open-source Mesa driver
Qualcomm Technologies Inc. Adreno Vulkan Driver
MoltenVK
Mali-G715
venus
SDL_PROP_GPU_DEVICE_DRIVER_VERSION_STRING: Contains the self-reported version of the underlying system driver. This is a relatively short version string in an unspecified format. If SDL_PROP_GPU_DEVICE_DRIVER_INFO_STRING is available then that property should be preferred over this one as it may contain additional information that is useful for identifying the exact driver version used.
Strings that have been found in the wild include:
53.0.0
0.405.2463
32.0.15.6614
SDL_PROP_GPU_DEVICE_DRIVER_INFO_STRING: Contains the detailed version information of the underlying system driver as reported by the driver. This is an arbitrary string with no standardized format and it may contain newlines. This property should be preferred over SDL_PROP_GPU_DEVICE_DRIVER_VERSION_STRING if it is available as it usually contains the same information but in a format that is easier to read.
Strings that have been found in the wild include:
101.6559
1.2.11
Mesa 21.2.2 (LLVM 12.0.1)
Mesa 22.2.0-devel (git-f226222 2022-04-14 impish-oibaf-ppa)
v1.r53p0-00eac0.824c4f31403fb1fbf8ee1042422c2129
This string has also been observed to be a multiline string (which has a trailing newline):
Driver Build: 85da404, I46ff5fc46f, 1606794520
Date: 11/30/20
Compiler Version: EV031.31.04.01
Driver Branch: promo490_3_Google
Parameters
device a GPU context to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_DEVICE_MAGIC(device, 0);
    return device->GetDeviceProperties(device);
}
References CHECK_DEVICE_MAGIC, and SDL_GPUDevice::GetDeviceProperties.
SDL_GetGPUDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetGPUDriver (int index) extern
Get the name of a built in GPU driver.
The GPU drivers are presented in the order in which they are normally checked during initialization.
The names of drivers are all simple, low-ASCII identifiers, like "vulkan", "metal" or "direct3d12". These never have Unicode characters, and are not meant to be proper names.
Parameters
index the index of a GPU driver.
Returns
the name of the GPU driver with the given index.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumGPUDrivers
{
    if (index < 0 || index >= SDL_GetNumGPUDrivers()) {
        SDL_InvalidParamError("index");
        return NULL;
    }
#ifndef SDL_GPU_DISABLED
    return backends[index]->name;
#else
    return NULL;
#endif
}
References backends, NULL, SDL_GetNumGPUDrivers(), and SDL_InvalidParamError.
SDL_GetGPUShaderFormats()
SDL_DECLSPEC SDL_GPUShaderFormat SDLCALL SDL_GetGPUShaderFormats (SDL_GPUDevice * device) extern
Returns the supported shader formats for this GPU context.
Parameters
device a GPU context to query.
Returns
a bitflag indicating which shader formats the driver is able to consume.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, SDL_GPU_SHADERFORMAT_INVALID);
    return device->shader_formats;
}
References CHECK_DEVICE_MAGIC, SDL_GPU_SHADERFORMAT_INVALID, and SDL_GPUDevice::shader_formats.
SDL_GetGPUSwapchainTextureFormat()
SDL_DECLSPEC SDL_GPUTextureFormat SDLCALL SDL_GetGPUSwapchainTextureFormat (SDL_GPUDevice * device, SDL_Window * window) extern
Obtains the texture format of the swapchain for the given window.
Note that this format can change if the swapchain parameters change.
Parameters
device a GPU context.
window an SDL_Window that has been claimed.
Returns
the texture format of the swapchain.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, SDL_GPU_TEXTUREFORMAT_INVALID);
    if (window == NULL) {
        SDL_InvalidParamError("window");
        return SDL_GPU_TEXTUREFORMAT_INVALID;
    }
    return device->GetSwapchainTextureFormat(
        device->driverData,
        window);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, SDL_GPUDevice::GetSwapchainTextureFormat, NULL, SDL_GPU_TEXTUREFORMAT_INVALID, and SDL_InvalidParamError.
SDL_GetNumGPUDrivers()
SDL_DECLSPEC int SDLCALL SDL_GetNumGPUDrivers (void) extern
Get the number of GPU drivers compiled into SDL.
Returns
the number of built in GPU drivers.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetGPUDriver
{
#ifndef SDL_GPU_DISABLED
    return SDL_arraysize(backends) - 1;
#else
    return 0;
#endif
}
References backends, and SDL_arraysize.
Referenced by SDL_GetGPUDriver().
SDL_GPUSupportsProperties()
SDL_DECLSPEC bool SDLCALL SDL_GPUSupportsProperties (SDL_PropertiesID props) extern
Checks for GPU runtime support.
Parameters
props the properties to use.
Returns
true if supported, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUDeviceWithProperties
{
#ifndef SDL_GPU_DISABLED
    return (SDL_GPUSelectBackend(props) != NULL);
#else
    SDL_SetError("SDL not built with GPU support");
    return false;
#endif
}
References NULL, SDL_GPUSelectBackend(), and SDL_SetError().
Referenced by SDL_GPUSupportsShaderFormats().
SDL_GPUSupportsShaderFormats()
SDL_DECLSPEC bool SDLCALL SDL_GPUSupportsShaderFormats (SDL_GPUShaderFormat format_flags, const char * name) extern
Checks for GPU runtime support.
Parameters
format_flags a bitflag indicating which shader formats the app is able to provide.
name the preferred GPU driver, or NULL to let SDL pick the optimal driver.
Returns
true if supported, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUDevice
{
#ifndef SDL_GPU_DISABLED
    bool result;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_GPU_FillProperties(props, format_flags, false, name);
    result = SDL_GPUSupportsProperties(props);
    SDL_DestroyProperties(props);
    return result;
#else
    SDL_SetError("SDL not built with GPU support");
    return false;
#endif
}
References SDL_CreateProperties(), SDL_DestroyProperties(), SDL_GPU_FillProperties(), SDL_GPUSupportsProperties(), and SDL_SetError().
SDL_GPUTextureFormatTexelBlockSize()
SDL_DECLSPEC Uint32 SDLCALL SDL_GPUTextureFormatTexelBlockSize (SDL_GPUTextureFormat format) extern
Obtains the texel block size for a texture format.
Parameters
format the texture format you want to know the texel size of.
Returns
the texel block size of the texture format.
Since
This function is available since SDL 3.2.0.
See also
SDL_UploadToGPUTexture
{
    switch (format) {
    case SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM:
    case SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM:
        return 8;
    case SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM:
    case SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM:
    case SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM:
    case SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM:
    case SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT:
    case SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB:
        return 16;
    case SDL_GPU_TEXTUREFORMAT_R8_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R8_SNORM:
    case SDL_GPU_TEXTUREFORMAT_A8_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R8_UINT:
    case SDL_GPU_TEXTUREFORMAT_R8_INT:
        return 1;
    case SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM:
    case SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM:
    case SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R16_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_R8G8_SNORM:
    case SDL_GPU_TEXTUREFORMAT_R8G8_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R8G8_UINT:
    case SDL_GPU_TEXTUREFORMAT_R8G8_INT:
    case SDL_GPU_TEXTUREFORMAT_R16_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R16_SNORM:
    case SDL_GPU_TEXTUREFORMAT_R16_UINT:
    case SDL_GPU_TEXTUREFORMAT_R16_INT:
    case SDL_GPU_TEXTUREFORMAT_D16_UNORM:
        return 2;
    case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM:
    case SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_R32_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT:
    case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM:
    case SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT:
    case SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT:
    case SDL_GPU_TEXTUREFORMAT_R16G16_UINT:
    case SDL_GPU_TEXTUREFORMAT_R16G16_INT:
    case SDL_GPU_TEXTUREFORMAT_R16G16_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R16G16_SNORM:
    case SDL_GPU_TEXTUREFORMAT_D24_UNORM:
    case SDL_GPU_TEXTUREFORMAT_D32_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_R32_UINT:
    case SDL_GPU_TEXTUREFORMAT_R32_INT:
    case SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT:
        return 4;
    case SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT:
        return 5;
    case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM:
    case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM:
    case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT:
    case SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT:
    case SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_R32G32_UINT:
    case SDL_GPU_TEXTUREFORMAT_R32G32_INT:
        return 8;
    case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT:
    case SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT:
        return 16;
    case SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM:
    case SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB:
    case SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT:
    case SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT:
        return 16;
    default:
        SDL_assert_release(!"Unrecognized TextureFormat!");
        return 0;
    }
}
References SDL_assert_release, SDL_GPU_TEXTUREFORMAT_A8_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_10x10_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_10x10_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_10x5_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_10x5_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_10x6_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_10x6_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_10x8_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_10x8_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_12x10_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_12x10_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_12x12_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_12x12_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_4x4_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_4x4_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_5x4_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_5x4_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_5x5_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_5x5_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_6x5_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_6x5_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_6x6_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_6x6_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_8x5_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_8x5_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_8x6_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_8x6_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_ASTC_8x8_FLOAT, SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM, SDL_GPU_TEXTUREFORMAT_ASTC_8x8_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_B4G4R4A4_UNORM, SDL_GPU_TEXTUREFORMAT_B5G5R5A1_UNORM, SDL_GPU_TEXTUREFORMAT_B5G6R5_UNORM, SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM, SDL_GPU_TEXTUREFORMAT_B8G8R8A8_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM, SDL_GPU_TEXTUREFORMAT_BC1_RGBA_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM, SDL_GPU_TEXTUREFORMAT_BC2_RGBA_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM, SDL_GPU_TEXTUREFORMAT_BC3_RGBA_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_BC4_R_UNORM, SDL_GPU_TEXTUREFORMAT_BC5_RG_UNORM, SDL_GPU_TEXTUREFORMAT_BC6H_RGB_FLOAT, SDL_GPU_TEXTUREFORMAT_BC6H_RGB_UFLOAT, SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM, SDL_GPU_TEXTUREFORMAT_BC7_RGBA_UNORM_SRGB, SDL_GPU_TEXTUREFORMAT_D16_UNORM, SDL_GPU_TEXTUREFORMAT_D24_UNORM, SDL_GPU_TEXTUREFORMAT_D24_UNORM_S8_UINT, SDL_GPU_TEXTUREFORMAT_D32_FLOAT, SDL_GPU_TEXTUREFORMAT_D32_FLOAT_S8_UINT, SDL_GPU_TEXTUREFORMAT_R10G10B10A2_UNORM, SDL_GPU_TEXTUREFORMAT_R11G11B10_UFLOAT, SDL_GPU_TEXTUREFORMAT_R16_FLOAT, SDL_GPU_TEXTUREFORMAT_R16_INT, SDL_GPU_TEXTUREFORMAT_R16_SNORM, SDL_GPU_TEXTUREFORMAT_R16_UINT, SDL_GPU_TEXTUREFORMAT_R16_UNORM, SDL_GPU_TEXTUREFORMAT_R16G16_FLOAT, SDL_GPU_TEXTUREFORMAT_R16G16_INT, SDL_GPU_TEXTUREFORMAT_R16G16_SNORM, SDL_GPU_TEXTUREFORMAT_R16G16_UINT, SDL_GPU_TEXTUREFORMAT_R16G16_UNORM, SDL_GPU_TEXTUREFORMAT_R16G16B16A16_FLOAT, SDL_GPU_TEXTUREFORMAT_R16G16B16A16_INT, SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SNORM, SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UINT, SDL_GPU_TEXTUREFORMAT_R16G16B16A16_UNORM, SDL_GPU_TEXTUREFORMAT_R32_FLOAT, SDL_GPU_TEXTUREFORMAT_R32_INT, SDL_GPU_TEXTUREFORMAT_R32_UINT, SDL_GPU_TEXTUREFORMAT_R32G32_FLOAT, SDL_GPU_TEXTUREFORMAT_R32G32_INT, SDL_GPU_TEXTUREFORMAT_R32G32_UINT, SDL_GPU_TEXTUREFORMAT_R32G32B32A32_FLOAT, SDL_GPU_TEXTUREFORMAT_R32G32B32A32_INT, SDL_GPU_TEXTUREFORMAT_R32G32B32A32_UINT, SDL_GPU_TEXTUREFORMAT_R8_INT, SDL_GPU_TEXTUREFORMAT_R8_SNORM, SDL_GPU_TEXTUREFORMAT_R8_UINT, SDL_GPU_TEXTUREFORMAT_R8_UNORM, SDL_GPU_TEXTUREFORMAT_R8G8_INT, SDL_GPU_TEXTUREFORMAT_R8G8_SNORM, SDL_GPU_TEXTUREFORMAT_R8G8_UINT, SDL_GPU_TEXTUREFORMAT_R8G8_UNORM, SDL_GPU_TEXTUREFORMAT_R8G8B8A8_INT, SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SNORM, SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UINT, SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM, and SDL_GPU_TEXTUREFORMAT_R8G8B8A8_UNORM_SRGB.
Referenced by BytesPerRow(), and SDL_CalculateGPUTextureFormatSize().
SDL_GPUTextureSupportsFormat()
SDL_DECLSPEC bool SDLCALL SDL_GPUTextureSupportsFormat (SDL_GPUDevice * device, SDL_GPUTextureFormat format, SDL_GPUTextureType type, SDL_GPUTextureUsageFlags usage) extern
Determines whether a texture format is supported for a given type and usage.
Parameters
device a GPU context.
format the texture format to check.
type the type of texture (2D, 3D, Cube).
usage a bitmask of all usage scenarios to check.
Returns
whether the texture format is supported for this type and usage.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, false);
    if (device->debug_mode) {
        CHECK_TEXTUREFORMAT_ENUM_INVALID(format, false)
    }
    if ((usage & SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE) ||
        (usage & SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE)) {
        if (!TextureFormatIsComputeWritable[format]) {
            return false;
        }
    }
    return device->SupportsTextureFormat(
        device->driverData,
        format,
        type,
        usage);
}
References CHECK_DEVICE_MAGIC, CHECK_TEXTUREFORMAT_ENUM_INVALID, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE, SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE, SDL_GPUDevice::SupportsTextureFormat, and TextureFormatIsComputeWritable.
Referenced by SDL_CreateGPUGraphicsPipeline(), and SDL_CreateGPUTexture().
SDL_GPUTextureSupportsSampleCount()
SDL_DECLSPEC bool SDLCALL SDL_GPUTextureSupportsSampleCount (SDL_GPUDevice * device, SDL_GPUTextureFormat format, SDL_GPUSampleCount sample_count) extern
Determines if a sample count for a texture format is supported.
Parameters
device a GPU context.
format the texture format to check.
sample_count the sample count to check.
Returns
whether the sample count is supported for this texture format.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, 0);
    if (device->debug_mode) {
        CHECK_TEXTUREFORMAT_ENUM_INVALID(format, 0)
    }
    return device->SupportsSampleCount(
        device->driverData,
        format,
        sample_count);
}
References CHECK_DEVICE_MAGIC, CHECK_TEXTUREFORMAT_ENUM_INVALID, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, and SDL_GPUDevice::SupportsSampleCount.
SDL_InsertGPUDebugLabel()
SDL_DECLSPEC void SDLCALL SDL_InsertGPUDebugLabel (SDL_GPUCommandBuffer * command_buffer, const char * text) extern
Inserts an arbitrary string label into the command buffer callstream.
Useful for debugging.
Parameters
command_buffer a command buffer.
text a UTF-8 string constant to insert as the label.
Since
This function is available since SDL 3.2.0.
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (text == NULL) {
        SDL_InvalidParamError("text");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
    }
    COMMAND_BUFFER_DEVICE->InsertDebugLabel(
        command_buffer,
        text);
}
References CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, NULL, and SDL_InvalidParamError.
SDL_MapGPUTransferBuffer()
SDL_DECLSPEC void *SDLCALL SDL_MapGPUTransferBuffer (SDL_GPUDevice * device, SDL_GPUTransferBuffer * transfer_buffer, bool cycle) extern
Maps a transfer buffer into application address space.
You must unmap the transfer buffer before encoding upload commands. The memory is owned by the graphics driver - do NOT call SDL_free() on the returned pointer.
Parameters
device a GPU context.
transfer_buffer a transfer buffer.
cycle if true, cycles the transfer buffer if it is already bound.
Returns
the address of the mapped transfer buffer memory, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, NULL);
    if (transfer_buffer == NULL) {
        SDL_InvalidParamError("transfer_buffer");
        return NULL;
    }
    return device->MapTransferBuffer(
        device->driverData,
        transfer_buffer,
        cycle);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, SDL_GPUDevice::MapTransferBuffer, NULL, and SDL_InvalidParamError.
SDL_PopGPUDebugGroup()
SDL_DECLSPEC void SDLCALL SDL_PopGPUDebugGroup (SDL_GPUCommandBuffer * command_buffer) extern
Ends the most-recently pushed debug group.
Parameters
command_buffer a command buffer.
Since
This function is available since SDL 3.2.0.
See also
SDL_PushGPUDebugGroup
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
    }
    COMMAND_BUFFER_DEVICE->PopDebugGroup(
        command_buffer);
}
References CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, NULL, and SDL_InvalidParamError.
SDL_PushGPUComputeUniformData()
SDL_DECLSPEC void SDLCALL SDL_PushGPUComputeUniformData (SDL_GPUCommandBuffer * command_buffer, Uint32 slot_index, const void * data, Uint32 length) extern
Pushes data to a uniform slot on the command buffer.
Subsequent draw calls will use this uniform data.
The data being pushed must respect std140 layout conventions. In practical terms this means you must ensure that vec3 and vec4 fields are 16-byte aligned.
Parameters
command_buffer a command buffer.
slot_index the uniform slot to push data to.
data client data to write.
length the length of the data to write.
Since
This function is available since SDL 3.2.0.
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (data == NULL) {
        SDL_InvalidParamError("data");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
    }
    COMMAND_BUFFER_DEVICE->PushComputeUniformData(
        command_buffer,
        slot_index,
        data,
        length);
}
References CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, NULL, and SDL_InvalidParamError.
SDL_PushGPUDebugGroup()
SDL_DECLSPEC void SDLCALL SDL_PushGPUDebugGroup (SDL_GPUCommandBuffer * command_buffer, const char * name) extern
Begins a debug group with an arbitary name.
Used for denoting groups of calls when viewing the command buffer callstream in a graphics debugging tool.
Each call to SDL_PushGPUDebugGroup must have a corresponding call to SDL_PopGPUDebugGroup.
On some backends (e.g. Metal), pushing a debug group during a render/blit/compute pass will create a group that is scoped to the native pass rather than the command buffer. For best results, if you push a debug group during a pass, always pop it in the same pass.
Parameters
command_buffer a command buffer.
name a UTF-8 string constant that names the group.
Since
This function is available since SDL 3.2.0.
See also
SDL_PopGPUDebugGroup
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (name == NULL) {
        SDL_InvalidParamError("name");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
    }
    COMMAND_BUFFER_DEVICE->PushDebugGroup(
        command_buffer,
        name);
}
References CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, NULL, and SDL_InvalidParamError.
SDL_PushGPUFragmentUniformData()
SDL_DECLSPEC void SDLCALL SDL_PushGPUFragmentUniformData (SDL_GPUCommandBuffer * command_buffer, Uint32 slot_index, const void * data, Uint32 length) extern
Pushes data to a fragment uniform slot on the command buffer.
Subsequent draw calls will use this uniform data.
The data being pushed must respect std140 layout conventions. In practical terms this means you must ensure that vec3 and vec4 fields are 16-byte aligned.
Parameters
command_buffer a command buffer.
slot_index the fragment uniform slot to push data to.
data client data to write.
length the length of the data to write.
Since
This function is available since SDL 3.2.0.
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (data == NULL) {
        SDL_InvalidParamError("data");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
    }
    COMMAND_BUFFER_DEVICE->PushFragmentUniformData(
        command_buffer,
        slot_index,
        data,
        length);
}
References CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, NULL, and SDL_InvalidParamError.
Referenced by SDL_GPU_BlitCommon().
SDL_PushGPUVertexUniformData()
SDL_DECLSPEC void SDLCALL SDL_PushGPUVertexUniformData (SDL_GPUCommandBuffer * command_buffer, Uint32 slot_index, const void * data, Uint32 length) extern
Pushes data to a vertex uniform slot on the command buffer.
Subsequent draw calls will use this uniform data.
The data being pushed must respect std140 layout conventions. In practical terms this means you must ensure that vec3 and vec4 fields are 16-byte aligned.
For detailed information about accessing uniform data from a shader, please refer to SDL_CreateGPUShader.
Parameters
command_buffer a command buffer.
slot_index the vertex uniform slot to push data to.
data client data to write.
length the length of the data to write.
Since
This function is available since SDL 3.2.0.
{
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return;
    }
    if (data == NULL) {
        SDL_InvalidParamError("data");
        return;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER
    }
    COMMAND_BUFFER_DEVICE->PushVertexUniformData(
        command_buffer,
        slot_index,
        data,
        length);
}
References CHECK_COMMAND_BUFFER, COMMAND_BUFFER_DEVICE, NULL, and SDL_InvalidParamError.
SDL_QueryGPUFence()
SDL_DECLSPEC bool SDLCALL SDL_QueryGPUFence (SDL_GPUDevice * device, SDL_GPUFence * fence) extern
Checks the status of a fence.
Parameters
device a GPU context.
fence a fence.
Returns
true if the fence is signaled, false if it is not.
Since
This function is available since SDL 3.2.0.
See also
SDL_SubmitGPUCommandBufferAndAcquireFence
{
    CHECK_DEVICE_MAGIC(device, false);
    if (fence == NULL) {
        SDL_InvalidParamError("fence");
        return false;
    }
    return device->QueryFence(
        device->driverData,
        fence);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, SDL_GPUDevice::QueryFence, and SDL_InvalidParamError.
SDL_ReleaseGPUBuffer()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUBuffer (SDL_GPUDevice * device, SDL_GPUBuffer * buffer) extern
Frees the given buffer as soon as it is safe to do so.
You must not reference the buffer after calling this function.
Parameters
device a GPU context.
buffer a buffer to be destroyed.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (buffer == NULL) {
        return;
    }
    device->ReleaseBuffer(
        device->driverData,
        buffer);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseBuffer.
SDL_ReleaseGPUComputePipeline()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUComputePipeline (SDL_GPUDevice * device, SDL_GPUComputePipeline * compute_pipeline) extern
Frees the given compute pipeline as soon as it is safe to do so.
You must not reference the compute pipeline after calling this function.
Parameters
device a GPU context.
compute_pipeline a compute pipeline to be destroyed.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (compute_pipeline == NULL) {
        return;
    }
    device->ReleaseComputePipeline(
        device->driverData,
        compute_pipeline);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseComputePipeline.
SDL_ReleaseGPUFence()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUFence (SDL_GPUDevice * device, SDL_GPUFence * fence) extern
Releases a fence obtained from SDL_SubmitGPUCommandBufferAndAcquireFence.
You must not reference the fence after calling this function.
Parameters
device a GPU context.
fence a fence.
Since
This function is available since SDL 3.2.0.
See also
SDL_SubmitGPUCommandBufferAndAcquireFence
{
    CHECK_DEVICE_MAGIC(device, );
    if (fence == NULL) {
        return;
    }
    device->ReleaseFence(
        device->driverData,
        fence);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseFence.
SDL_ReleaseGPUGraphicsPipeline()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUGraphicsPipeline (SDL_GPUDevice * device, SDL_GPUGraphicsPipeline * graphics_pipeline) extern
Frees the given graphics pipeline as soon as it is safe to do so.
You must not reference the graphics pipeline after calling this function.
Parameters
device a GPU context.
graphics_pipeline a graphics pipeline to be destroyed.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (graphics_pipeline == NULL) {
        return;
    }
    device->ReleaseGraphicsPipeline(
        device->driverData,
        graphics_pipeline);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseGraphicsPipeline.
SDL_ReleaseGPUSampler()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUSampler (SDL_GPUDevice * device, SDL_GPUSampler * sampler) extern
Frees the given sampler as soon as it is safe to do so.
You must not reference the sampler after calling this function.
Parameters
device a GPU context.
sampler a sampler to be destroyed.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (sampler == NULL) {
        return;
    }
    device->ReleaseSampler(
        device->driverData,
        sampler);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseSampler.
SDL_ReleaseGPUShader()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUShader (SDL_GPUDevice * device, SDL_GPUShader * shader) extern
Frees the given shader as soon as it is safe to do so.
You must not reference the shader after calling this function.
Parameters
device a GPU context.
shader a shader to be destroyed.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (shader == NULL) {
        return;
    }
    device->ReleaseShader(
        device->driverData,
        shader);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseShader.
SDL_ReleaseGPUTexture()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUTexture (SDL_GPUDevice * device, SDL_GPUTexture * texture) extern
Frees the given texture as soon as it is safe to do so.
You must not reference the texture after calling this function.
Parameters
device a GPU context.
texture a texture to be destroyed.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (texture == NULL) {
        return;
    }
    device->ReleaseTexture(
        device->driverData,
        texture);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseTexture.
SDL_ReleaseGPUTransferBuffer()
SDL_DECLSPEC void SDLCALL SDL_ReleaseGPUTransferBuffer (SDL_GPUDevice * device, SDL_GPUTransferBuffer * transfer_buffer) extern
Frees the given transfer buffer as soon as it is safe to do so.
You must not reference the transfer buffer after calling this function.
Parameters
device a GPU context.
transfer_buffer a transfer buffer to be destroyed.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (transfer_buffer == NULL) {
        return;
    }
    device->ReleaseTransferBuffer(
        device->driverData,
        transfer_buffer);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, and SDL_GPUDevice::ReleaseTransferBuffer.
SDL_ReleaseWindowFromGPUDevice()
SDL_DECLSPEC void SDLCALL SDL_ReleaseWindowFromGPUDevice (SDL_GPUDevice * device, SDL_Window * window) extern
Unclaims a window, destroying its swapchain structure.
Parameters
device a GPU context.
window an SDL_Window that has been claimed.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClaimWindowForGPUDevice
{
    CHECK_DEVICE_MAGIC(device, );
    if (window == NULL) {
        SDL_InvalidParamError("window");
        return;
    }
    device->ReleaseWindow(
        device->driverData,
        window);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, SDL_GPUDevice::ReleaseWindow, and SDL_InvalidParamError.
SDL_SetGPUAllowedFramesInFlight()
SDL_DECLSPEC bool SDLCALL SDL_SetGPUAllowedFramesInFlight (SDL_GPUDevice * device, Uint32 allowed_frames_in_flight) extern
Configures the maximum allowed number of frames in flight.
The default value when the device is created is 2. This means that after you have submitted 2 frames for presentation, if the GPU has not finished working on the first frame, SDL_AcquireGPUSwapchainTexture() will fill the swapchain texture pointer with NULL, and SDL_WaitAndAcquireGPUSwapchainTexture() will block.
Higher values increase throughput at the expense of visual latency. Lower values decrease visual latency at the expense of throughput.
Note that calling this function will stall and flush the command queue to prevent synchronization issues.
The minimum value of allowed frames in flight is 1, and the maximum is 3.
Parameters
device a GPU context.
allowed_frames_in_flight the maximum number of frames that can be pending on the GPU.
Returns
true if successful, false on error; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, false);
    if (device->debug_mode) {
        if (allowed_frames_in_flight < 1 || allowed_frames_in_flight > 3)
        {
            SDL_assert_release(!"allowed_frames_in_flight value must be between 1 and 3!");
        }
    }
    allowed_frames_in_flight = SDL_clamp(allowed_frames_in_flight, 1, 3);
    return device->SetAllowedFramesInFlight(
        device->driverData,
        allowed_frames_in_flight);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, SDL_assert_release, SDL_clamp, and SDL_GPUDevice::SetAllowedFramesInFlight.
SDL_SetGPUBlendConstants()
SDL_DECLSPEC void SDLCALL SDL_SetGPUBlendConstants (SDL_GPURenderPass * render_pass, SDL_FColor blend_constants) extern
Sets the current blend constants on a command buffer.
Parameters
render_pass a render pass handle.
blend_constants the blend constant color.
Since
This function is available since SDL 3.2.0.
See also
SDL_GPU_BLENDFACTOR_CONSTANT_COLOR
SDL_GPU_BLENDFACTOR_ONE_MINUS_CONSTANT_COLOR
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
    }
    RENDERPASS_DEVICE->SetBlendConstants(
        RENDERPASS_COMMAND_BUFFER,
        blend_constants);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_SetGPUBufferName()
SDL_DECLSPEC void SDLCALL SDL_SetGPUBufferName (SDL_GPUDevice * device, SDL_GPUBuffer * buffer, const char * text) extern
Sets an arbitrary string constant to label a buffer.
You should use SDL_PROP_GPU_BUFFER_CREATE_NAME_STRING with SDL_CreateGPUBuffer instead of this function to avoid thread safety issues.
Parameters
device a GPU Context.
buffer a buffer to attach the name to.
text a UTF-8 string constant to mark as the name of the buffer.
Thread Safety
This function is not thread safe, you must make sure the buffer is not simultaneously used by any other thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUBuffer
{
    CHECK_DEVICE_MAGIC(device, );
    if (buffer == NULL) {
        SDL_InvalidParamError("buffer");
        return;
    }
    if (text == NULL) {
        SDL_InvalidParamError("text");
    }
    device->SetBufferName(
        device->driverData,
        buffer,
        text);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::SetBufferName.
SDL_SetGPUScissor()
SDL_DECLSPEC void SDLCALL SDL_SetGPUScissor (SDL_GPURenderPass * render_pass, const SDL_Rect * scissor) extern
Sets the current scissor state on a command buffer.
Parameters
render_pass a render pass handle.
scissor the scissor area to set.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (scissor == NULL) {
        SDL_InvalidParamError("scissor");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
    }
    RENDERPASS_DEVICE->SetScissor(
        RENDERPASS_COMMAND_BUFFER,
        scissor);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_SetGPUStencilReference()
SDL_DECLSPEC void SDLCALL SDL_SetGPUStencilReference (SDL_GPURenderPass * render_pass, Uint8 reference) extern
Sets the current stencil reference value on a command buffer.
Parameters
render_pass a render pass handle.
reference the stencil reference value to set.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
    }
    RENDERPASS_DEVICE->SetStencilReference(
        RENDERPASS_COMMAND_BUFFER,
        reference);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
SDL_SetGPUSwapchainParameters()
SDL_DECLSPEC bool SDLCALL SDL_SetGPUSwapchainParameters (SDL_GPUDevice * device, SDL_Window * window, SDL_GPUSwapchainComposition swapchain_composition, SDL_GPUPresentMode present_mode) extern
Changes the swapchain parameters for the given claimed window.
This function will fail if the requested present mode or swapchain composition are unsupported by the device. Check if the parameters are supported via SDL_WindowSupportsGPUPresentMode / SDL_WindowSupportsGPUSwapchainComposition prior to calling this function.
SDL_GPU_PRESENTMODE_VSYNC with SDL_GPU_SWAPCHAINCOMPOSITION_SDR is always supported.
Parameters
device a GPU context.
window an SDL_Window that has been claimed.
swapchain_composition the desired composition of the swapchain.
present_mode the desired present mode for the swapchain.
Returns
true if successful, false on error; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_WindowSupportsGPUPresentMode
SDL_WindowSupportsGPUSwapchainComposition
{
    CHECK_DEVICE_MAGIC(device, false);
    if (window == NULL) {
        SDL_InvalidParamError("window");
        return false;
    }
    if (device->debug_mode) {
        CHECK_SWAPCHAINCOMPOSITION_ENUM_INVALID(swapchain_composition, false)
        CHECK_PRESENTMODE_ENUM_INVALID(present_mode, false)
    }
    return device->SetSwapchainParameters(
        device->driverData,
        window,
        swapchain_composition,
        present_mode);
}
References CHECK_DEVICE_MAGIC, CHECK_PRESENTMODE_ENUM_INVALID, CHECK_SWAPCHAINCOMPOSITION_ENUM_INVALID, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::SetSwapchainParameters.
SDL_SetGPUTextureName()
SDL_DECLSPEC void SDLCALL SDL_SetGPUTextureName (SDL_GPUDevice * device, SDL_GPUTexture * texture, const char * text) extern
Sets an arbitrary string constant to label a texture.
You should use SDL_PROP_GPU_TEXTURE_CREATE_NAME_STRING with SDL_CreateGPUTexture instead of this function to avoid thread safety issues.
Parameters
device a GPU Context.
texture a texture to attach the name to.
text a UTF-8 string constant to mark as the name of the texture.
Thread Safety
This function is not thread safe, you must make sure the texture is not simultaneously used by any other thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateGPUTexture
{
    CHECK_DEVICE_MAGIC(device, );
    if (texture == NULL) {
        SDL_InvalidParamError("texture");
        return;
    }
    if (text == NULL) {
        SDL_InvalidParamError("text");
    }
    device->SetTextureName(
        device->driverData,
        texture,
        text);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::SetTextureName.
SDL_SetGPUViewport()
SDL_DECLSPEC void SDLCALL SDL_SetGPUViewport (SDL_GPURenderPass * render_pass, const SDL_GPUViewport * viewport) extern
Sets the current viewport state on a command buffer.
Parameters
render_pass a render pass handle.
viewport the viewport to set.
Since
This function is available since SDL 3.2.0.
{
    if (render_pass == NULL) {
        SDL_InvalidParamError("render_pass");
        return;
    }
    if (viewport == NULL) {
        SDL_InvalidParamError("viewport");
        return;
    }
    if (RENDERPASS_DEVICE->debug_mode) {
        CHECK_RENDERPASS
    }
    RENDERPASS_DEVICE->SetViewport(
        RENDERPASS_COMMAND_BUFFER,
        viewport);
}
References CHECK_RENDERPASS, NULL, RENDERPASS_COMMAND_BUFFER, RENDERPASS_DEVICE, and SDL_InvalidParamError.
Referenced by SDL_GPU_BlitCommon().
SDL_SubmitGPUCommandBuffer()
SDL_DECLSPEC bool SDLCALL SDL_SubmitGPUCommandBuffer (SDL_GPUCommandBuffer * command_buffer) extern
Submits a command buffer so its commands can be processed on the GPU.
It is invalid to use the command buffer after this is called.
This must be called from the thread the command buffer was acquired on.
All commands in the submission are guaranteed to begin executing before any command in a subsequent submission begins executing.
Parameters
command_buffer a command buffer.
Returns
true on success, false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_AcquireGPUCommandBuffer
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_AcquireGPUSwapchainTexture
SDL_SubmitGPUCommandBufferAndAcquireFence
{
    CommandBufferCommonHeader *commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return false;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER_RETURN_FALSE
        if (
            commandBufferHeader->render_pass.in_progress ||
            commandBufferHeader->compute_pass.in_progress ||
            commandBufferHeader->copy_pass.in_progress) {
            SDL_assert_release(!"Cannot submit command buffer while a pass is in progress!");
            return false;
        }
    }
    commandBufferHeader->submitted = true;
    return COMMAND_BUFFER_DEVICE->Submit(
        command_buffer);
}
References CHECK_COMMAND_BUFFER_RETURN_FALSE, COMMAND_BUFFER_DEVICE, CommandBufferCommonHeader::compute_pass, CommandBufferCommonHeader::copy_pass, ComputePass::in_progress, Pass::in_progress, RenderPass::in_progress, NULL, CommandBufferCommonHeader::render_pass, SDL_assert_release, SDL_InvalidParamError, and CommandBufferCommonHeader::submitted.
SDL_SubmitGPUCommandBufferAndAcquireFence()
SDL_DECLSPEC SDL_GPUFence *SDLCALL SDL_SubmitGPUCommandBufferAndAcquireFence (SDL_GPUCommandBuffer * command_buffer) extern
Submits a command buffer so its commands can be processed on the GPU, and acquires a fence associated with the command buffer.
You must release this fence when it is no longer needed or it will cause a leak. It is invalid to use the command buffer after this is called.
This must be called from the thread the command buffer was acquired on.
All commands in the submission are guaranteed to begin executing before any command in a subsequent submission begins executing.
Parameters
command_buffer a command buffer.
Returns
a fence associated with the command buffer, or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_AcquireGPUCommandBuffer
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_AcquireGPUSwapchainTexture
SDL_SubmitGPUCommandBuffer
SDL_ReleaseGPUFence
{
    CommandBufferCommonHeader *commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (command_buffer == NULL) {
        SDL_InvalidParamError("command_buffer");
        return NULL;
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER_RETURN_NULL
        if (
            commandBufferHeader->render_pass.in_progress ||
            commandBufferHeader->compute_pass.in_progress ||
            commandBufferHeader->copy_pass.in_progress) {
            SDL_assert_release(!"Cannot submit command buffer while a pass is in progress!");
            return NULL;
        }
    }
    commandBufferHeader->submitted = true;
    return COMMAND_BUFFER_DEVICE->SubmitAndAcquireFence(
        command_buffer);
}
References CHECK_COMMAND_BUFFER_RETURN_NULL, COMMAND_BUFFER_DEVICE, CommandBufferCommonHeader::compute_pass, CommandBufferCommonHeader::copy_pass, ComputePass::in_progress, Pass::in_progress, RenderPass::in_progress, NULL, CommandBufferCommonHeader::render_pass, SDL_assert_release, SDL_InvalidParamError, and CommandBufferCommonHeader::submitted.
SDL_UnmapGPUTransferBuffer()
SDL_DECLSPEC void SDLCALL SDL_UnmapGPUTransferBuffer (SDL_GPUDevice * device, SDL_GPUTransferBuffer * transfer_buffer) extern
Unmaps a previously mapped transfer buffer.
Parameters
device a GPU context.
transfer_buffer a previously mapped transfer buffer.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, );
    if (transfer_buffer == NULL) {
        SDL_InvalidParamError("transfer_buffer");
        return;
    }
    device->UnmapTransferBuffer(
        device->driverData,
        transfer_buffer);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::UnmapTransferBuffer.
SDL_UploadToGPUBuffer()
SDL_DECLSPEC void SDLCALL SDL_UploadToGPUBuffer (SDL_GPUCopyPass * copy_pass, const SDL_GPUTransferBufferLocation * source, const SDL_GPUBufferRegion * destination, bool cycle) extern
Uploads data from a transfer buffer to a buffer.
The upload occurs on the GPU timeline. You may assume that the upload has finished in subsequent commands.
Parameters
copy_pass a copy pass handle.
source the source transfer buffer with offset.
destination the destination buffer with offset and size.
cycle if true, cycles the buffer if it is already bound, otherwise overwrites the data.
Since
This function is available since SDL 3.2.0.
{
    if (copy_pass == NULL) {
        SDL_InvalidParamError("copy_pass");
        return;
    }
    if (source == NULL) {
        SDL_InvalidParamError("source");
        return;
    }
    if (destination == NULL) {
        SDL_InvalidParamError("destination");
        return;
    }
    if (COPYPASS_DEVICE->debug_mode) {
        CHECK_COPYPASS
        if (source->transfer_buffer == NULL) {
            SDL_assert_release(!"Source transfer buffer cannot be NULL!");
            return;
        }
        if (destination->buffer == NULL) {
            SDL_assert_release(!"Destination buffer cannot be NULL!");
            return;
        }
    }
    COPYPASS_DEVICE->UploadToBuffer(
        COPYPASS_COMMAND_BUFFER,
        source,
        destination,
        cycle);
}
References SDL_GPUBufferRegion::buffer, CHECK_COPYPASS, COPYPASS_COMMAND_BUFFER, COPYPASS_DEVICE, NULL, SDL_assert_release, SDL_InvalidParamError, and SDL_GPUTransferBufferLocation::transfer_buffer.
SDL_UploadToGPUTexture()
SDL_DECLSPEC void SDLCALL SDL_UploadToGPUTexture (SDL_GPUCopyPass * copy_pass, const SDL_GPUTextureTransferInfo * source, const SDL_GPUTextureRegion * destination, bool cycle) extern
Uploads data from a transfer buffer to a texture.
The upload occurs on the GPU timeline. You may assume that the upload has finished in subsequent commands.
You must align the data in the transfer buffer to a multiple of the texel size of the texture format.
Parameters
copy_pass a copy pass handle.
source the source transfer buffer with image layout information.
destination the destination texture region.
cycle if true, cycles the texture if the texture is bound, otherwise overwrites the data.
Since
This function is available since SDL 3.2.0.
{
    if (copy_pass == NULL) {
        SDL_InvalidParamError("copy_pass");
        return;
    }
    if (source == NULL) {
        SDL_InvalidParamError("source");
        return;
    }
    if (destination == NULL) {
        SDL_InvalidParamError("destination");
        return;
    }
    if (COPYPASS_DEVICE->debug_mode) {
        CHECK_COPYPASS
        if (source->transfer_buffer == NULL) {
            SDL_assert_release(!"Source transfer buffer cannot be NULL!");
            return;
        }
        if (destination->texture == NULL) {
            SDL_assert_release(!"Destination texture cannot be NULL!");
            return;
        }
    }
    COPYPASS_DEVICE->UploadToTexture(
        COPYPASS_COMMAND_BUFFER,
        source,
        destination,
        cycle);
}
References CHECK_COPYPASS, COPYPASS_COMMAND_BUFFER, COPYPASS_DEVICE, NULL, SDL_assert_release, SDL_InvalidParamError, SDL_GPUTextureRegion::texture, and SDL_GPUTextureTransferInfo::transfer_buffer.
SDL_WaitAndAcquireGPUSwapchainTexture()
SDL_DECLSPEC bool SDLCALL SDL_WaitAndAcquireGPUSwapchainTexture (SDL_GPUCommandBuffer * command_buffer, SDL_Window * window, SDL_GPUTexture ** swapchain_texture, Uint32 * swapchain_texture_width, Uint32 * swapchain_texture_height) extern
Blocks the thread until a swapchain texture is available to be acquired, and then acquires it.
When a swapchain texture is acquired on a command buffer, it will automatically be submitted for presentation when the command buffer is submitted. The swapchain texture should only be referenced by the command buffer used to acquire it. It is an error to call SDL_CancelGPUCommandBuffer() after a swapchain texture is acquired.
This function can fill the swapchain texture handle with NULL in certain cases, for example if the window is minimized. This is not an error. You should always make sure to check whether the pointer is NULL before actually using it.
The swapchain texture is managed by the implementation and must not be freed by the user. You MUST NOT call this function from any thread other than the one that created the window.
The swapchain texture is write-only and cannot be used as a sampler or for another reading operation.
Parameters
command_buffer a command buffer.
window a window that has been claimed.
swapchain_texture a pointer filled in with a swapchain texture handle.
swapchain_texture_width a pointer filled in with the swapchain texture width, may be NULL.
swapchain_texture_height a pointer filled in with the swapchain texture height, may be NULL.
Returns
true on success, false on error; call SDL_GetError() for more information.
Thread Safety
This function should only be called from the thread that created the window.
Since
This function is available since SDL 3.2.0.
See also
SDL_SubmitGPUCommandBuffer
SDL_SubmitGPUCommandBufferAndAcquireFence
SDL_AcquireGPUSwapchainTexture
{
    CommandBufferCommonHeader *commandBufferHeader = (CommandBufferCommonHeader *)command_buffer;
    if (command_buffer == NULL) {
        return SDL_InvalidParamError("command_buffer");
    }
    if (window == NULL) {
        return SDL_InvalidParamError("window");
    }
    if (swapchain_texture == NULL) {
        return SDL_InvalidParamError("swapchain_texture");
    }
    if (COMMAND_BUFFER_DEVICE->debug_mode) {
        CHECK_COMMAND_BUFFER_RETURN_FALSE
        CHECK_ANY_PASS_IN_PROGRESS("Cannot acquire a swapchain texture during a pass!", false)
    }
    bool result = COMMAND_BUFFER_DEVICE->WaitAndAcquireSwapchainTexture(
        command_buffer,
        window,
        swapchain_texture,
        swapchain_texture_width,
        swapchain_texture_height);
    if (*swapchain_texture != NULL){
        commandBufferHeader->swapchain_texture_acquired = true;
    }
    return result;
}
References CHECK_ANY_PASS_IN_PROGRESS, CHECK_COMMAND_BUFFER_RETURN_FALSE, COMMAND_BUFFER_DEVICE, NULL, SDL_InvalidParamError, and CommandBufferCommonHeader::swapchain_texture_acquired.
SDL_WaitForGPUFences()
SDL_DECLSPEC bool SDLCALL SDL_WaitForGPUFences (SDL_GPUDevice * device, bool wait_all, SDL_GPUFence *const * fences, Uint32 num_fences) extern
Blocks the thread until the given fences are signaled.
Parameters
device a GPU context.
wait_all if 0, wait for any fence to be signaled, if 1, wait for all fences to be signaled.
fences an array of fences to wait on.
num_fences the number of fences in the fences array.
Returns
true on success, false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_SubmitGPUCommandBufferAndAcquireFence
SDL_WaitForGPUIdle
{
    CHECK_DEVICE_MAGIC(device, false);
    if (fences == NULL && num_fences > 0) {
        SDL_InvalidParamError("fences");
        return false;
    }
    return device->WaitForFences(
        device->driverData,
        wait_all,
        fences,
        num_fences);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::WaitForFences.
SDL_WaitForGPUIdle()
SDL_DECLSPEC bool SDLCALL SDL_WaitForGPUIdle (SDL_GPUDevice * device) extern
Blocks the thread until the GPU is completely idle.
Parameters
device a GPU context.
Returns
true on success, false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_WaitForGPUFences
{
    CHECK_DEVICE_MAGIC(device, false);
    return device->Wait(
        device->driverData);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, and SDL_GPUDevice::Wait.
SDL_WaitForGPUSwapchain()
SDL_DECLSPEC bool SDLCALL SDL_WaitForGPUSwapchain (SDL_GPUDevice * device, SDL_Window * window) extern
Blocks the thread until a swapchain texture is available to be acquired.
Parameters
device a GPU context.
window a window that has been claimed.
Returns
true on success, false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called from the thread that created the window.
Since
This function is available since SDL 3.2.0.
See also
SDL_AcquireGPUSwapchainTexture
SDL_WaitAndAcquireGPUSwapchainTexture
SDL_SetGPUAllowedFramesInFlight
{
    CHECK_DEVICE_MAGIC(device, false);
    if (window == NULL) {
        return SDL_InvalidParamError("window");
    }
    return device->WaitForSwapchain(
        device->driverData,
        window);
}
References CHECK_DEVICE_MAGIC, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::WaitForSwapchain.
SDL_WindowSupportsGPUPresentMode()
SDL_DECLSPEC bool SDLCALL SDL_WindowSupportsGPUPresentMode (SDL_GPUDevice * device, SDL_Window * window, SDL_GPUPresentMode present_mode) extern
Determines whether a presentation mode is supported by the window.
The window must be claimed before calling this function.
Parameters
device a GPU context.
window an SDL_Window.
present_mode the presentation mode to check.
Returns
true if supported, false if unsupported.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClaimWindowForGPUDevice
{
    CHECK_DEVICE_MAGIC(device, false);
    if (window == NULL) {
        SDL_InvalidParamError("window");
        return false;
    }
    if (device->debug_mode) {
        CHECK_PRESENTMODE_ENUM_INVALID(present_mode, false)
    }
    return device->SupportsPresentMode(
        device->driverData,
        window,
        present_mode);
}
References CHECK_DEVICE_MAGIC, CHECK_PRESENTMODE_ENUM_INVALID, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::SupportsPresentMode.
SDL_WindowSupportsGPUSwapchainComposition()
SDL_DECLSPEC bool SDLCALL SDL_WindowSupportsGPUSwapchainComposition (SDL_GPUDevice * device, SDL_Window * window, SDL_GPUSwapchainComposition swapchain_composition) extern
Determines whether a swapchain composition is supported by the window.
The window must be claimed before calling this function.
Parameters
device a GPU context.
window an SDL_Window.
swapchain_composition the swapchain composition to check.
Returns
true if supported, false if unsupported.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClaimWindowForGPUDevice
{
    CHECK_DEVICE_MAGIC(device, false);
    if (window == NULL) {
        SDL_InvalidParamError("window");
        return false;
    }
    if (device->debug_mode) {
        CHECK_SWAPCHAINCOMPOSITION_ENUM_INVALID(swapchain_composition, false)
    }
    return device->SupportsSwapchainComposition(
        device->driverData,
        window,
        swapchain_composition);
}
References CHECK_DEVICE_MAGIC, CHECK_SWAPCHAINCOMPOSITION_ENUM_INVALID, SDL_GPUDevice::debug_mode, SDL_GPUDevice::driverData, NULL, SDL_InvalidParamError, and SDL_GPUDevice::SupportsSwapchainComposition.