SDL3: SDL-main/src/stdlib/SDL_malloc.c File Reference
SDL_malloc.c File Reference
#include "SDL_internal.h"
#include <errno.h>
#include <time.h>
#include <sys/mman.h>
#include <fcntl.h>
#include <unistd.h>
#include <sched.h>
#include <pthread.h>
#include <sys/param.h>
Data Structures
struct mallinfo
struct malloc_chunk
struct malloc_params
struct malloc_segment
struct malloc_state
struct malloc_tree_chunk
Macros
#define _STRUCT_MALLINFO
#define ABORT
#define ABORT_ON_ASSERT_FAILURE 1
#define ACQUIRE_LOCK(lk)
#define ACQUIRE_MALLOC_GLOBAL_LOCK()
#define align_as_chunk(A)
#define align_offset(A)
#define assert(x)
#define bit_for_tree_index(i)
#define CALL_DIRECT_MMAP(s)
#define CALL_MMAP(s)
#define CALL_MORECORE(S)
#define CALL_MREMAP(addr, osz, nsz, mv)
#define CALL_MUNMAP(a, s)
#define calloc_must_clear(p)
#define check_free_chunk(M, P)
#define check_inuse_chunk(M, P)
#define check_malloc_state(M)
#define check_malloced_chunk(M, P, N)
#define check_mmapped_chunk(M, P)
#define check_top_chunk(M, P)
#define chunk2mem(p)
#define CHUNK_ALIGN_MASK (MALLOC_ALIGNMENT - SIZE_T_ONE)
#define chunk_minus_offset(p, s)
#define CHUNK_OVERHEAD (SIZE_T_SIZE)
#define chunk_plus_offset(p, s)
#define chunksize(p)
#define cinuse(p)
#define CINUSE_BIT (SIZE_T_TWO)
#define clear_flag4(p)
#define clear_pinuse(p)
#define clear_smallmap(M, i)
#define clear_treemap(M, i)
#define CMFAIL ((char*)(MFAIL)) /* defined for convenience */
#define compute_bit2idx(X, I)
#define compute_tree_index(S, I)
#define CORRUPTION_ERROR_ACTION(m)
#define DEBUG 0
#define DECREMENT_ALLOCATION_COUNT()
#define DEFAULT_GRANULARITY (0) /* 0 means to compute in init_mparams */
#define DEFAULT_MMAP_THRESHOLD ((size_t)256U * (size_t)1024U)
#define DEFAULT_TRIM_THRESHOLD ((size_t)2U * (size_t)1024U * (size_t)1024U)
#define DESTROY_LOCK(lk)
#define DIRECT_MMAP_DEFAULT(s)
#define disable_contiguous(M)
#define disable_lock(M)
#define disable_mmap(M)
#define DLMALLOC_EXPORT extern
#define DLMALLOC_VERSION 20806
#define enable_lock(M)
#define enable_mmap(M)
#define ensure_initialization()
#define EXTERN_BIT (8U)
#define FENCEPOST_HEAD (INUSE_BITS|SIZE_T_SIZE)
#define FLAG4_BIT (SIZE_T_FOUR)
#define flag4inuse(p)
#define FLAG_BITS (PINUSE_BIT|CINUSE_BIT|FLAG4_BIT)
#define fm gm
#define FOOTERS 0
#define FOUR_SIZE_T_SIZES (SIZE_T_SIZE<<2)
#define get_foot(p, s)
#define gm (&_gm_)
#define granularity_align(S)
#define HALF_MAX_SIZE_T (MAX_SIZE_T / 2U)
#define HAVE_MMAP 1
#define HAVE_MORECORE 1
#define HAVE_MREMAP 0
#define idx2bit(i)
#define INCREMENT_ALLOCATION_COUNT()
#define INITIAL_LOCK(lk)
#define INSECURE 0
#define insert_chunk(M, P, S)
#define insert_large_chunk(M, X, S)
#define insert_small_chunk(M, P, S)
#define internal_free(m, mem)
#define internal_malloc(m, b)
#define INUSE_BITS (PINUSE_BIT|CINUSE_BIT)
#define is_aligned(A)
#define is_extern_segment(S)
#define is_global(M)
#define is_granularity_aligned(S)
#define is_initialized(M)
#define is_inuse(p)
#define is_mmapped(p)
#define is_mmapped_segment(S)
#define is_page_aligned(S)
#define is_small(s)
#define LACKS_STDIO_H
#define LACKS_STDLIB_H
#define LACKS_STRING_H
#define LACKS_STRINGS_H
#define LACKS_SYS_TYPES_H
#define least_bit(x)
#define left_bits(x)
#define leftmost_child(t)
#define leftshift_for_tree_index(i)
#define LOCK_AT_FORK 0
#define M_GRANULARITY (-2)
#define M_MMAP_THRESHOLD (-3)
#define M_TRIM_THRESHOLD (-1)
#define MALLINFO_FIELD_TYPE size_t
#define MALLOC_ALIGNMENT ((size_t)(2 * sizeof(void *)))
#define MALLOC_FAILURE_ACTION errno = ENOMEM;
#define malloc_getpagesize ((size_t)4096U)
#define MALLOC_INSPECT_ALL 0
#define mark_inuse_foot(M, p, s)
#define mark_smallmap(M, i)
#define mark_treemap(M, i)
#define MAX_RELEASE_CHECK_RATE 4095
#define MAX_REQUEST ((-MIN_CHUNK_SIZE) << 2)
#define MAX_SIZE_T (~(size_t)0)
#define MAX_SMALL_REQUEST (MAX_SMALL_SIZE - CHUNK_ALIGN_MASK - CHUNK_OVERHEAD)
#define MAX_SMALL_SIZE (MIN_LARGE_SIZE - SIZE_T_ONE)
#define MCHUNK_SIZE (sizeof(mchunk))
#define mem2chunk(mem)
#define MFAIL ((void*)(MAX_SIZE_T))
#define MIN_CHUNK_SIZE ((MCHUNK_SIZE + CHUNK_ALIGN_MASK) & ~CHUNK_ALIGN_MASK)
#define MIN_LARGE_SIZE (SIZE_T_ONE << TREEBIN_SHIFT)
#define MIN_REQUEST (MIN_CHUNK_SIZE - CHUNK_OVERHEAD - SIZE_T_ONE)
#define MIN_SMALL_INDEX (small_index(MIN_CHUNK_SIZE))
#define minsize_for_tree_index(i)
#define MLOCK_T pthread_mutex_t
#define mmap_align(S)
#define MMAP_CHUNK_OVERHEAD (TWO_SIZE_T_SIZES)
#define MMAP_CLEARS 1
#define MMAP_DEFAULT(s)
#define MMAP_FLAGS (MAP_PRIVATE)
#define MMAP_FOOT_PAD (FOUR_SIZE_T_SIZES)
#define MMAP_PROT (PROT_READ|PROT_WRITE)
#define MORECORE_CONTIGUOUS 1
#define MORECORE_DEFAULT sbrk
#define MSPACES 0
#define MUNMAP_DEFAULT(a, s)
#define next_chunk(p)
#define next_pinuse(p)
#define NO_MALLINFO 0
#define NO_MALLOC_STATS 1
#define NO_SEGMENT_TRAVERSAL 0
#define NOINLINE
#define NSMALLBINS (32U)
#define NTREEBINS (32U)
#define ok_address(M, a)
#define ok_inuse(p)
#define ok_magic(M)
#define ok_next(p, n)
#define ok_pinuse(p)
#define ONLY_MSPACES 0
#define overhead_for(p)
#define pad_request(req)
#define page_align(S)
#define pinuse(p)
#define PINUSE_BIT (SIZE_T_ONE)
#define POSTACTION(M)
#define PREACTION(M)
#define prev_chunk(p)
#define PROCEED_ON_ERROR 0
#define real_calloc dlcalloc
#define real_free dlfree
#define real_malloc dlmalloc
#define real_realloc dlrealloc
#define RELEASE_LOCK(lk)
#define RELEASE_MALLOC_GLOBAL_LOCK()
#define replace_dv(M, P, S)
#define request2size(req)
#define RTCHECK(e)
#define same_or_left_bits(x)
#define segment_holds(S, A)
#define set_flag4(p)
#define set_foot(p, s)
#define set_free_with_pinuse(p, s, n)
#define set_inuse(M, p, s)
#define set_inuse_and_pinuse(M, p, s)
#define set_lock(M, L)
#define set_size_and_pinuse_of_free_chunk(p, s)
#define set_size_and_pinuse_of_inuse_chunk(M, p, s)
#define should_trim(M, s)
#define SIX_SIZE_T_SIZES (FOUR_SIZE_T_SIZES+TWO_SIZE_T_SIZES)
#define SIZE_T_BITSIZE (sizeof(size_t) << 3)
#define SIZE_T_FOUR ((size_t)4)
#define SIZE_T_ONE ((size_t)1)
#define SIZE_T_SIZE (sizeof(size_t))
#define SIZE_T_TWO ((size_t)2)
#define SIZE_T_ZERO ((size_t)0)
#define small_index(s)
#define small_index2size(i)
#define smallbin_at(M, i)
#define SMALLBIN_SHIFT (3U)
#define SMALLBIN_WIDTH (SIZE_T_ONE << SMALLBIN_SHIFT)
#define smallmap_is_marked(M, i)
#define STRUCT_MALLINFO_DECLARED 1
#define SYS_ALLOC_PADDING (TOP_FOOT_SIZE + MALLOC_ALIGNMENT)
#define TOP_FOOT_SIZE (align_offset(chunk2mem(0))+pad_request(sizeof(struct malloc_segment))+MIN_CHUNK_SIZE)
#define treebin_at(M, i)
#define TREEBIN_SHIFT (8U)
#define treemap_is_marked(M, i)
#define TRY_LOCK(lk)
#define TWO_SIZE_T_SIZES (SIZE_T_SIZE<<1)
#define unlink_chunk(M, P, S)
#define unlink_first_small_chunk(M, B, P, I)
#define unlink_large_chunk(M, X)
#define unlink_small_chunk(M, P, S)
#define USAGE_ERROR_ACTION(m, p)
#define USE_BUILTIN_FFS 0
#define USE_DEV_RANDOM 0
#define USE_DL_PREFIX
#define use_lock(M)
#define USE_LOCK_BIT (2U)
#define USE_LOCKS 1
#define use_mmap(M)
#define USE_MMAP_BIT (SIZE_T_ONE)
#define use_noncontiguous(M)
#define USE_NONCONTIGUOUS_BIT (4U)
Typedefs
typedef unsigned int bindex_t
typedef unsigned int binmap_t
typedef unsigned int flag_t
typedef struct malloc_chunk mchunk
typedef struct malloc_chunk * mchunkptr
typedef struct malloc_segment msegment
typedef struct malloc_segment * msegmentptr
typedef struct malloc_state * mstate
typedef struct malloc_chunk * sbinptr
typedef struct malloc_tree_chunk * tbinptr
typedef struct malloc_tree_chunk tchunk
typedef struct malloc_tree_chunk * tchunkptr
Functions
static void add_segment (mstate m, char *tbase, size_t tsize, flag_t mmapped)
static int change_mparam (int param_number, int value)
static void dispose_chunk (mstate m, mchunkptr p, size_t psize)
size_t dlbulk_free (void **, size_t n_elements)
size_t dlbulk_free (void *array[], size_t nelem)
void * dlcalloc (size_t, size_t)
void dlfree (void *)
void ** dlindependent_calloc (size_t n_elements, size_t elem_size, void *chunks[])
void ** dlindependent_calloc (size_t, size_t, void **)
void ** dlindependent_comalloc (size_t n_elements, size_t sizes[], void *chunks[])
void ** dlindependent_comalloc (size_t, size_t *, void **)
struct mallinfo dlmallinfo (void)
void * dlmalloc (size_t)
size_t dlmalloc_footprint (void)
size_t dlmalloc_footprint_limit ()
size_t dlmalloc_max_footprint (void)
size_t dlmalloc_set_footprint_limit (size_t bytes)
void dlmalloc_stats (void)
int dlmalloc_trim (size_t)
size_t dlmalloc_usable_size (void *)
int dlmallopt (int, int)
void * dlmemalign (size_t, size_t)
int dlposix_memalign (void **, size_t, size_t)
void * dlpvalloc (size_t)
void * dlrealloc (void *, size_t)
void * dlrealloc_in_place (void *, size_t)
void * dlvalloc (size_t)
static int has_segment_link (mstate m, msegmentptr ss)
static void ** ialloc (mstate m, size_t n_elements, size_t *sizes, int opts, void *chunks[])
static void init_bins (mstate m)
static int init_mparams (void)
static void init_top (mstate m, mchunkptr p, size_t psize)
static size_t internal_bulk_free (mstate m, void *array[], size_t nelem)
static struct mallinfo internal_mallinfo (mstate m)
static void * internal_memalign (mstate m, size_t alignment, size_t bytes)
static void * mmap_alloc (mstate m, size_t nb)
static mchunkptr mmap_resize (mstate m, mchunkptr oldp, size_t nb, int flags)
static void * prepend_alloc (mstate m, char *newbase, char *oldbase, size_t nb)
static int pthread_init_lock (pthread_mutex_t *lk)
static size_t release_unused_segments (mstate m)
void * SDL_calloc (size_t nmemb, size_t size)
void SDL_free (void *ptr)
void SDL_GetMemoryFunctions (SDL_malloc_func *malloc_func, SDL_calloc_func *calloc_func, SDL_realloc_func *realloc_func, SDL_free_func *free_func)
int SDL_GetNumAllocations (void)
void SDL_GetOriginalMemoryFunctions (SDL_malloc_func *malloc_func, SDL_calloc_func *calloc_func, SDL_realloc_func *realloc_func, SDL_free_func *free_func)
void * SDL_malloc (size_t size)
void * SDL_realloc (void *ptr, size_t size)
bool SDL_SetMemoryFunctions (SDL_malloc_func malloc_func, SDL_calloc_func calloc_func, SDL_realloc_func realloc_func, SDL_free_func free_func)
static msegmentptr segment_holding (mstate m, char *addr)
static void * sys_alloc (mstate m, size_t nb)
static int sys_trim (mstate m, size_t pad)
static void * tmalloc_large (mstate m, size_t nb)
static void * tmalloc_small (mstate m, size_t nb)
static mchunkptr try_realloc_chunk (mstate m, mchunkptr p, size_t nb, int can_move)
Variables
static struct malloc_state _gm_
static int dev_zero_fd = -1
static pthread_mutex_t malloc_global_mutex = PTHREAD_MUTEX_INITIALIZER
static struct malloc_params mparams
struct {
SDL_calloc_func calloc_func
SDL_free_func free_func
SDL_malloc_func malloc_func
SDL_AtomicInt num_allocations
SDL_realloc_func realloc_func
} s_mem
Macro Definition Documentation
_STRUCT_MALLINFO
#define _STRUCT_MALLINFO
ABORT
#define ABORT
Referenced by init_mparams().
ABORT_ON_ASSERT_FAILURE
#define ABORT_ON_ASSERT_FAILURE 1
ACQUIRE_LOCK
#define ACQUIRE_LOCK (lk)
Value:
pthread_mutex_lock(lk)
ACQUIRE_MALLOC_GLOBAL_LOCK
#define ACQUIRE_MALLOC_GLOBAL_LOCK ()
Value:
ACQUIRE_LOCK(&malloc_global_mutex);
Referenced by init_mparams(), sys_alloc(), and sys_trim().
align_as_chunk
#define align_as_chunk (A)
Value:
(mchunkptr)((A) + align_offset(chunk2mem(A)))
Referenced by internal_mallinfo(), prepend_alloc(), and release_unused_segments().
align_offset
#define align_offset (A)
Value:
 ((((size_t)(A) & CHUNK_ALIGN_MASK) == 0)? 0 :\
  ((MALLOC_ALIGNMENT - ((size_t)(A) & CHUNK_ALIGN_MASK)) & CHUNK_ALIGN_MASK))
#define align_offset(A)\
 ((((size_t)(A) & CHUNK_ALIGN_MASK) == 0)? 0 :\
  ((MALLOC_ALIGNMENT - ((size_t)(A) & CHUNK_ALIGN_MASK)) & CHUNK_ALIGN_MASK))
Referenced by add_segment(), init_top(), and mmap_alloc().
assert
#define assert (x)
Referenced by add_segment(), dlmalloc(), ialloc(), internal_memalign(), mmap_alloc(), prepend_alloc(), release_unused_segments(), tmalloc_large(), and tmalloc_small().
bit_for_tree_index
#define bit_for_tree_index (i)
Value:
   (i == NTREEBINS-1)? (SIZE_T_BITSIZE-1) : (((i) >> 1) + TREEBIN_SHIFT - 2)
#define bit_for_tree_index(i) \
   (i == NTREEBINS-1)? (SIZE_T_BITSIZE-1) : (((i) >> 1) + TREEBIN_SHIFT - 2)
CALL_DIRECT_MMAP
#define CALL_DIRECT_MMAP (s)
Value:
DIRECT_MMAP_DEFAULT(s)
Referenced by mmap_alloc().
CALL_MMAP
#define CALL_MMAP (s)
Value:
MMAP_DEFAULT(s)
Referenced by sys_alloc().
CALL_MORECORE
#define CALL_MORECORE (S)
Value:
MORECORE_DEFAULT(S)
Define CALL_MORECORE
Referenced by sys_alloc(), and sys_trim().
CALL_MREMAP
#define CALL_MREMAP (addr, osz, nsz, mv)
Value:
MFAIL
Define CALL_MREMAP
Referenced by mmap_resize(), and sys_trim().
CALL_MUNMAP
#define CALL_MUNMAP (a, s)
Value:
MUNMAP_DEFAULT((a), (s))
Referenced by dispose_chunk(), dlfree(), release_unused_segments(), and sys_trim().
calloc_must_clear
#define calloc_must_clear (p)
Value:
(!is_mmapped(p))
Referenced by dlcalloc().
check_free_chunk
#define check_free_chunk (M, P)
Referenced by dlfree(), and prepend_alloc().
check_inuse_chunk
#define check_inuse_chunk (M, P)
Referenced by dlfree(), dlrealloc(), dlrealloc_in_place(), ialloc(), internal_bulk_free(), and internal_memalign().
check_malloc_state
#define check_malloc_state (M)
Referenced by internal_mallinfo().
check_malloced_chunk
#define check_malloced_chunk (M, P, N)
Referenced by dlmalloc(), prepend_alloc(), and sys_alloc().
check_mmapped_chunk
#define check_mmapped_chunk (M, P)
Referenced by mmap_alloc(), and mmap_resize().
check_top_chunk
#define check_top_chunk (M, P)
Referenced by add_segment(), dlmalloc(), prepend_alloc(), sys_alloc(), and sys_trim().
chunk2mem
#define chunk2mem (p)
Value:
((void*)((char*)(p)       + TWO_SIZE_T_SIZES))
Referenced by add_segment(), dlmalloc(), dlrealloc(), ialloc(), init_top(), internal_bulk_free(), internal_memalign(), mmap_alloc(), prepend_alloc(), sys_alloc(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
CHUNK_ALIGN_MASK
#define CHUNK_ALIGN_MASK (MALLOC_ALIGNMENT - SIZE_T_ONE)
Referenced by add_segment(), mmap_alloc(), and mmap_resize().
chunk_minus_offset
#define chunk_minus_offset (p, s)
Value:
((mchunkptr)(((char*)(p)) - (s)))
Referenced by dispose_chunk(), and dlfree().
CHUNK_OVERHEAD
#define CHUNK_OVERHEAD (SIZE_T_SIZE)
Referenced by ialloc(), and internal_memalign().
chunk_plus_offset
#define chunk_plus_offset (p, s)
Value:
((mchunkptr)(((char*)(p)) + (s)))
Referenced by add_segment(), dispose_chunk(), dlfree(), dlmalloc(), ialloc(), init_top(), internal_memalign(), mmap_alloc(), mmap_resize(), prepend_alloc(), sys_alloc(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
chunksize
#define chunksize (p)
Value:
((p)->head & ~(FLAG_BITS))
Referenced by dispose_chunk(), dlfree(), dlmalloc(), dlmalloc_usable_size(), dlrealloc(), dynamic_mem_realloc(), ialloc(), internal_bulk_free(), internal_mallinfo(), internal_memalign(), mmap_resize(), prepend_alloc(), release_unused_segments(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
cinuse
#define cinuse (p)
Value:
((p)->head & CINUSE_BIT)
Referenced by dispose_chunk(), dlfree(), and try_realloc_chunk().
CINUSE_BIT
#define CINUSE_BIT (SIZE_T_TWO)
clear_flag4
#define clear_flag4 (p)
Value:
((p)->head &= ~FLAG4_BIT)
clear_pinuse
#define clear_pinuse (p)
Value:
((p)->head &= ~PINUSE_BIT)
Referenced by try_realloc_chunk().
clear_smallmap
#define clear_smallmap (M, i)
Value:
((M)->smallmap &= ~idx2bit(i))
clear_treemap
#define clear_treemap (M, i)
Value:
((M)->treemap  &= ~idx2bit(i))
CMFAIL
#define CMFAIL ((char*)(MFAIL)) /* defined for convenience */
Referenced by mmap_alloc(), mmap_resize(), sys_alloc(), and sys_trim().
compute_bit2idx
#define compute_bit2idx (X, I)
Value:
{\
  unsigned int Y = X - 1;\
  unsigned int K = Y >> (16-4) & 16;\
  unsigned int N = K;        Y >>= K;\
  N += K = Y >> (8-3) &  8;  Y >>= K;\
  N += K = Y >> (4-2) &  4;  Y >>= K;\
  N += K = Y >> (2-1) &  2;  Y >>= K;\
  N += K = Y >> (1-0) &  1;  Y >>= K;\
  I = (bindex_t)(N + Y);\
}
#define compute_bit2idx(X, I)\
{\
  unsigned int Y = X - 1;\
  unsigned int K = Y >> (16-4) & 16;\
  unsigned int N = K;        Y >>= K;\
  N += K = Y >> (8-3) &  8;  Y >>= K;\
  N += K = Y >> (4-2) &  4;  Y >>= K;\
  N += K = Y >> (2-1) &  2;  Y >>= K;\
  N += K = Y >> (1-0) &  1;  Y >>= K;\
  I = (bindex_t)(N + Y);\
}
Referenced by dlmalloc(), tmalloc_large(), and tmalloc_small().
compute_tree_index
#define compute_tree_index (S, I)
Value:
{\
  size_t X = S >> TREEBIN_SHIFT;\
  if (X == 0)\
    I = 0;\
  else if (X > 0xFFFF)\
    I = NTREEBINS-1;\
  else {\
    unsigned int Y = (unsigned int)X;\
    unsigned int N = ((Y - 0x100) >> 16) & 8;\
    unsigned int K = (((Y <<= N) - 0x1000) >> 16) & 4;\
    N += K;\
    N += K = (((Y <<= K) - 0x4000) >> 16) & 2;\
    K = 14 - N + ((Y <<= K) >> 15);\
    I = (K << 1) + ((S >> (K + (TREEBIN_SHIFT-1)) & 1));\
  }\
}
#define compute_tree_index(S, I)\
{\
  size_t X = S >> TREEBIN_SHIFT;\
  if (X == 0)\
    I = 0;\
  else if (X > 0xFFFF)\
    I = NTREEBINS-1;\
  else {\
    unsigned int Y = (unsigned int)X;\
    unsigned int N = ((Y - 0x100) >> 16) & 8;\
    unsigned int K = (((Y <<= N) - 0x1000) >> 16) & 4;\
    N += K;\
    N += K = (((Y <<= K) - 0x4000) >> 16) & 2;\
    K = 14 - N + ((Y <<= K) >> 15);\
    I = (K << 1) + ((S >> (K + (TREEBIN_SHIFT-1)) & 1));\
  }\
}
Referenced by tmalloc_large().
CORRUPTION_ERROR_ACTION
#define CORRUPTION_ERROR_ACTION (m)
Value:
ABORT
Referenced by dispose_chunk(), internal_bulk_free(), tmalloc_large(), and tmalloc_small().
DEBUG
#define DEBUG 0
DECREMENT_ALLOCATION_COUNT
#define DECREMENT_ALLOCATION_COUNT ()
Referenced by SDL_free().
DEFAULT_GRANULARITY
#define DEFAULT_GRANULARITY (0) /* 0 means to compute in init_mparams */
Referenced by init_mparams().
DEFAULT_MMAP_THRESHOLD
#define DEFAULT_MMAP_THRESHOLD ((size_t)256U * (size_t)1024U)
Referenced by init_mparams().
DEFAULT_TRIM_THRESHOLD
#define DEFAULT_TRIM_THRESHOLD ((size_t)2U * (size_t)1024U * (size_t)1024U)
Referenced by init_mparams().
DESTROY_LOCK
#define DESTROY_LOCK (lk)
Value:
pthread_mutex_destroy(lk)
DIRECT_MMAP_DEFAULT
#define DIRECT_MMAP_DEFAULT (s)
Value:
MMAP_DEFAULT(s)
disable_contiguous
#define disable_contiguous (M)
Value:
((M)->mflags |=  USE_NONCONTIGUOUS_BIT)
Referenced by sys_alloc().
disable_lock
#define disable_lock (M)
Value:
((M)->mflags &= ~USE_LOCK_BIT)
disable_mmap
#define disable_mmap (M)
Value:
((M)->mflags &= ~USE_MMAP_BIT)
Referenced by ialloc().
DLMALLOC_EXPORT
#define DLMALLOC_EXPORT extern
Referenced by dlbulk_free(), dlindependent_calloc(), dlindependent_comalloc(), and dlmalloc_stats().
DLMALLOC_VERSION
#define DLMALLOC_VERSION 20806
enable_lock
#define enable_lock (M)
Value:
((M)->mflags |=  USE_LOCK_BIT)
enable_mmap
#define enable_mmap (M)
Value:
((M)->mflags |=  USE_MMAP_BIT)
Referenced by ialloc().
ensure_initialization
#define ensure_initialization ()
Value:
(void)(mparams.magic != 0 || init_mparams())
Referenced by change_mparam(), dlmalloc(), dlmalloc_trim(), dlpvalloc(), dlvalloc(), ialloc(), internal_mallinfo(), sys_alloc(), and sys_trim().
EXTERN_BIT
#define EXTERN_BIT (8U)
FENCEPOST_HEAD
#define FENCEPOST_HEAD (INUSE_BITS|SIZE_T_SIZE)
Referenced by add_segment(), internal_mallinfo(), mmap_alloc(), and mmap_resize().
FLAG4_BIT
#define FLAG4_BIT (SIZE_T_FOUR)
flag4inuse
#define flag4inuse (p)
Value:
((p)->head & FLAG4_BIT)
FLAG_BITS
#define FLAG_BITS (PINUSE_BIT|CINUSE_BIT|FLAG4_BIT)
fm
#define fm gm
Referenced by dlfree().
FOOTERS
#define FOOTERS 0
FOUR_SIZE_T_SIZES
#define FOUR_SIZE_T_SIZES (SIZE_T_SIZE<<2)
Referenced by add_segment().
get_foot
#define get_foot (p, s)
Value:
(((mchunkptr)((char*)(p) + (s)))->prev_foot)
gm
#define gm (&_gm_)
Referenced by dlbulk_free(), dlindependent_calloc(), dlindependent_comalloc(), dlmallinfo(), dlmalloc(), dlmalloc_footprint(), dlmalloc_footprint_limit(), dlmalloc_max_footprint(), dlmalloc_set_footprint_limit(), dlmalloc_trim(), dlmemalign(), dlposix_memalign(), dlrealloc(), dlrealloc_in_place(), and init_mparams().
granularity_align
#define granularity_align (S)
Value:
  (((S) + (mparams.granularity - SIZE_T_ONE))\
   & ~(mparams.granularity - SIZE_T_ONE))
#define granularity_align(S)\
  (((S) + (mparams.granularity - SIZE_T_ONE))\
   & ~(mparams.granularity - SIZE_T_ONE))
Referenced by dlmalloc_set_footprint_limit(), and sys_alloc().
HALF_MAX_SIZE_T
#define HALF_MAX_SIZE_T (MAX_SIZE_T / 2U)
Referenced by sys_alloc(), and sys_trim().
HAVE_MMAP
#define HAVE_MMAP 1
Referenced by sys_alloc(), and sys_trim().
HAVE_MORECORE
#define HAVE_MORECORE 1
Referenced by sys_alloc(), and sys_trim().
HAVE_MREMAP
#define HAVE_MREMAP 0
idx2bit
#define idx2bit (i)
Value:
((binmap_t)(1) << (i))
Referenced by dlmalloc(), and tmalloc_large().
INCREMENT_ALLOCATION_COUNT
#define INCREMENT_ALLOCATION_COUNT ()
Referenced by SDL_calloc(), SDL_malloc(), and SDL_realloc().
INITIAL_LOCK
#define INITIAL_LOCK (lk)
Value:
pthread_init_lock(lk)
Referenced by init_mparams().
INSECURE
#define INSECURE 0
insert_chunk
#define insert_chunk (M, P, S)
Value:
  if (is_small(S)) insert_small_chunk(M, P, S)\
  else { tchunkptr TP = (tchunkptr)(P); insert_large_chunk(M, TP, S); }
#define insert_chunk(M, P, S)\
  if (is_small(S)) insert_small_chunk(M, P, S)\
  else { tchunkptr TP = (tchunkptr)(P); insert_large_chunk(M, TP, S); }
Referenced by add_segment(), dispose_chunk(), prepend_alloc(), and tmalloc_large().
insert_large_chunk
#define insert_large_chunk (M, X, S)
#define insert_large_chunk(M, X, S) {\
  tbinptr* H;\
  bindex_t I;\
  compute_tree_index(S, I);\
  H = treebin_at(M, I);\
  X->index = I;\
  X->child[0] = X->child[1] = 0;\
  if (!treemap_is_marked(M, I)) {\
    mark_treemap(M, I);\
    *H = X;\
    X->parent = (tchunkptr)H;\
    X->fd = X->bk = X;\
  }\
  else {\
    tchunkptr T = *H;\
    size_t K = S << leftshift_for_tree_index(I);\
    for (;;) {\
      if (chunksize(T) != S) {\
        tchunkptr* C = &(T->child[(K >> (SIZE_T_BITSIZE-SIZE_T_ONE)) & 1]);\
        K <<= 1;\
        if (*C != 0)\
          T = *C;\
        else if (RTCHECK(ok_address(M, C))) {\
          *C = X;\
          X->parent = T;\
          X->fd = X->bk = X;\
          break;\
        }\
        else {\
          CORRUPTION_ERROR_ACTION(M);\
          break;\
        }\
      }\
      else {\
        tchunkptr F = T->fd;\
        if (RTCHECK(ok_address(M, T) && ok_address(M, F))) {\
          T->fd = F->bk = X;\
          X->fd = F;\
          X->bk = T;\
          X->parent = 0;\
          break;\
        }\
        else {\
          CORRUPTION_ERROR_ACTION(M);\
          break;\
        }\
      }\
    }\
  }\
}
Referenced by dlfree(), and release_unused_segments().
insert_small_chunk
#define insert_small_chunk (M, P, S)
Value:
  {\
  bindex_t I  = small_index(S);\
  mchunkptr B = smallbin_at(M, I);\
  mchunkptr F = B;\
  assert(S >= MIN_CHUNK_SIZE);\
  if (!smallmap_is_marked(M, I))\
    mark_smallmap(M, I);\
  else if (RTCHECK(ok_address(M, B->fd)))\
    F = B->fd;\
  else {\
    CORRUPTION_ERROR_ACTION(M);\
  }\
  B->fd = P;\
  F->bk = P;\
  P->fd = F;\
  P->bk = B;\
}
#define insert_small_chunk(M, P, S) {\
  bindex_t I  = small_index(S);\
  mchunkptr B = smallbin_at(M, I);\
  mchunkptr F = B;\
  assert(S >= MIN_CHUNK_SIZE);\
  if (!smallmap_is_marked(M, I))\
    mark_smallmap(M, I);\
  else if (RTCHECK(ok_address(M, B->fd)))\
    F = B->fd;\
  else {\
    CORRUPTION_ERROR_ACTION(M);\
  }\
  B->fd = P;\
  F->bk = P;\
  P->fd = F;\
  P->bk = B;\
}
Referenced by dlfree().
internal_free
#define internal_free (m, mem)
Value:
dlfree(mem)
Referenced by dlrealloc().
internal_malloc
#define internal_malloc (m, b)
Value:
dlmalloc(b)
Referenced by dlrealloc(), ialloc(), and internal_memalign().
INUSE_BITS
#define INUSE_BITS (PINUSE_BIT|CINUSE_BIT)
Referenced by dispose_chunk(), and dlfree().
is_aligned
#define is_aligned (A)
Value:
(((size_t)((A)) & (CHUNK_ALIGN_MASK)) == 0)
Referenced by add_segment(), and mmap_alloc().
is_extern_segment
#define is_extern_segment (S)
Value:
((S)->sflags & EXTERN_BIT)
Referenced by release_unused_segments(), sys_alloc(), and sys_trim().
is_global
#define is_global (M)
Value:
((M) == &_gm_)
Referenced by sys_alloc().
is_granularity_aligned
#define is_granularity_aligned (S)
Value:
   (((size_t)(S) & (mparams.granularity - SIZE_T_ONE)) == 0)
#define is_granularity_aligned(S)\
   (((size_t)(S) & (mparams.granularity - SIZE_T_ONE)) == 0)
is_initialized
#define is_initialized (M)
Value:
((M)->top != 0)
Referenced by internal_mallinfo(), sys_alloc(), and sys_trim().
is_inuse
#define is_inuse (p)
Value:
(((p)->head & INUSE_BITS) != PINUSE_BIT)
Referenced by dlmalloc_usable_size(), internal_mallinfo(), prepend_alloc(), and release_unused_segments().
is_mmapped
#define is_mmapped (p)
Value:
(((p)->head & INUSE_BITS) == 0)
Referenced by dispose_chunk(), dlfree(), ialloc(), internal_memalign(), and try_realloc_chunk().
is_mmapped_segment
#define is_mmapped_segment (S)
Value:
((S)->sflags & USE_MMAP_BIT)
Referenced by release_unused_segments(), and sys_trim().
is_page_aligned
#define is_page_aligned (S)
Value:
   (((size_t)(S) & (mparams.page_size - SIZE_T_ONE)) == 0)
#define is_page_aligned(S)\
   (((size_t)(S) & (mparams.page_size - SIZE_T_ONE)) == 0)
Referenced by sys_alloc().
is_small
#define is_small (s)
Value:
(((s) >> SMALLBIN_SHIFT) < NSMALLBINS)
Referenced by dlfree(), and mmap_resize().
LACKS_STDIO_H
#define LACKS_STDIO_H
LACKS_STDLIB_H
#define LACKS_STDLIB_H
LACKS_STRING_H
#define LACKS_STRING_H
LACKS_STRINGS_H
#define LACKS_STRINGS_H
LACKS_SYS_TYPES_H
#define LACKS_SYS_TYPES_H
least_bit
#define least_bit (x)
Value:
((x) & -(x))
Referenced by dlmalloc(), tmalloc_large(), and tmalloc_small().
left_bits
#define left_bits (x)
Value:
((x<<1) | -(x<<1))
Referenced by dlmalloc(), and tmalloc_large().
leftmost_child
#define leftmost_child (t)
Value:
((t)->child[0] != 0? (t)->child[0] : (t)->child[1])
Referenced by tmalloc_large(), and tmalloc_small().
leftshift_for_tree_index
#define leftshift_for_tree_index (i)
Value:
   ((i == NTREEBINS-1)? 0 : \
    ((SIZE_T_BITSIZE-SIZE_T_ONE) - (((i) >> 1) + TREEBIN_SHIFT - 2)))
#define leftshift_for_tree_index(i) \
   ((i == NTREEBINS-1)? 0 : \
    ((SIZE_T_BITSIZE-SIZE_T_ONE) - (((i) >> 1) + TREEBIN_SHIFT - 2)))
Referenced by tmalloc_large().
LOCK_AT_FORK
#define LOCK_AT_FORK 0
M_GRANULARITY
#define M_GRANULARITY (-2)
Referenced by change_mparam().
M_MMAP_THRESHOLD
#define M_MMAP_THRESHOLD (-3)
Referenced by change_mparam().
M_TRIM_THRESHOLD
#define M_TRIM_THRESHOLD (-1)
Referenced by change_mparam().
MALLINFO_FIELD_TYPE
#define MALLINFO_FIELD_TYPE size_t
MALLOC_ALIGNMENT
#define MALLOC_ALIGNMENT ((size_t)(2 * sizeof(void *)))
Referenced by dlmemalign(), dlposix_memalign(), init_mparams(), and internal_memalign().
MALLOC_FAILURE_ACTION
#define MALLOC_FAILURE_ACTION errno = ENOMEM;
Referenced by dlrealloc(), dlrealloc_in_place(), internal_memalign(), and sys_alloc().
malloc_getpagesize
#define malloc_getpagesize ((size_t)4096U)
Referenced by init_mparams().
MALLOC_INSPECT_ALL
#define MALLOC_INSPECT_ALL 0
mark_inuse_foot
#define mark_inuse_foot (M, p, s)
Referenced by mmap_alloc(), and mmap_resize().
mark_smallmap
#define mark_smallmap (M, i)
Value:
((M)->smallmap |=  idx2bit(i))
mark_treemap
#define mark_treemap (M, i)
Value:
((M)->treemap  |=  idx2bit(i))
MAX_RELEASE_CHECK_RATE
#define MAX_RELEASE_CHECK_RATE 4095
Referenced by release_unused_segments(), and sys_alloc().
MAX_REQUEST
#define MAX_REQUEST ((-MIN_CHUNK_SIZE) << 2)
Referenced by dlmalloc(), dlposix_memalign(), dlrealloc(), dlrealloc_in_place(), internal_memalign(), and sys_trim().
MAX_SIZE_T
#define MAX_SIZE_T (~(size_t)0)
Referenced by change_mparam(), dlcalloc(), dlmalloc(), dlmalloc_footprint_limit(), dlmalloc_set_footprint_limit(), init_mparams(), and sys_trim().
MAX_SMALL_REQUEST
#define MAX_SMALL_REQUEST (MAX_SMALL_SIZE - CHUNK_ALIGN_MASK - CHUNK_OVERHEAD)
Referenced by dlmalloc().
MAX_SMALL_SIZE
#define MAX_SMALL_SIZE (MIN_LARGE_SIZE - SIZE_T_ONE)
MCHUNK_SIZE
#define MCHUNK_SIZE (sizeof(mchunk))
Referenced by init_mparams().
mem2chunk
#define mem2chunk (mem)
Value:
((mchunkptr)((char*)(mem) - TWO_SIZE_T_SIZES))
Referenced by dlcalloc(), dlfree(), dlmalloc_usable_size(), dlrealloc(), dlrealloc_in_place(), ialloc(), internal_bulk_free(), internal_memalign(), and sys_alloc().
MFAIL
#define MFAIL ((void*)(MAX_SIZE_T))
Referenced by sys_trim().
MIN_CHUNK_SIZE
#define MIN_CHUNK_SIZE ((MCHUNK_SIZE + CHUNK_ALIGN_MASK) & ~CHUNK_ALIGN_MASK)
#define MIN_CHUNK_SIZE\
  ((MCHUNK_SIZE + CHUNK_ALIGN_MASK) & ~CHUNK_ALIGN_MASK)
Referenced by add_segment(), dlmalloc(), dlposix_memalign(), init_mparams(), internal_memalign(), prepend_alloc(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
MIN_LARGE_SIZE
#define MIN_LARGE_SIZE (SIZE_T_ONE << TREEBIN_SHIFT)
MIN_REQUEST
#define MIN_REQUEST (MIN_CHUNK_SIZE - CHUNK_OVERHEAD - SIZE_T_ONE)
Referenced by dlmalloc().
MIN_SMALL_INDEX
#define MIN_SMALL_INDEX (small_index(MIN_CHUNK_SIZE))
minsize_for_tree_index
#define minsize_for_tree_index (i)
Value:
   ((SIZE_T_ONE << (((i) >> 1) + TREEBIN_SHIFT)) |  \
   (((size_t)((i) & SIZE_T_ONE)) << (((i) >> 1) + TREEBIN_SHIFT - 1)))
#define minsize_for_tree_index(i) \
   ((SIZE_T_ONE << (((i) >> 1) + TREEBIN_SHIFT)) |  \
   (((size_t)((i) & SIZE_T_ONE)) << (((i) >> 1) + TREEBIN_SHIFT - 1)))
MLOCK_T
#define MLOCK_T pthread_mutex_t
Referenced by pthread_init_lock().
mmap_align
#define mmap_align (S)
Value:
page_align(S)
Referenced by mmap_alloc(), and mmap_resize().
MMAP_CHUNK_OVERHEAD
#define MMAP_CHUNK_OVERHEAD (TWO_SIZE_T_SIZES)
MMAP_CLEARS
#define MMAP_CLEARS 1
MMAP_DEFAULT
#define MMAP_DEFAULT (s)
Value:
           ((dev_zero_fd < 0) ? \
           (dev_zero_fd = open("/dev/zero", O_RDWR), \
            mmap(0, (s), MMAP_PROT, MMAP_FLAGS, dev_zero_fd, 0)) : \
            mmap(0, (s), MMAP_PROT, MMAP_FLAGS, dev_zero_fd, 0))
#define MMAP_DEFAULT(s) ((dev_zero_fd < 0) ? \
           (dev_zero_fd = open("/dev/zero", O_RDWR), \
            mmap(0, (s), MMAP_PROT, MMAP_FLAGS, dev_zero_fd, 0)) : \
            mmap(0, (s), MMAP_PROT, MMAP_FLAGS, dev_zero_fd, 0))
MMAP_FLAGS
#define MMAP_FLAGS (MAP_PRIVATE)
MMAP_FOOT_PAD
#define MMAP_FOOT_PAD (FOUR_SIZE_T_SIZES)
Referenced by dispose_chunk(), dlfree(), mmap_alloc(), and mmap_resize().
MMAP_PROT
#define MMAP_PROT (PROT_READ|PROT_WRITE)
MORECORE_CONTIGUOUS
#define MORECORE_CONTIGUOUS 1
Referenced by sys_alloc().
MORECORE_DEFAULT
#define MORECORE_DEFAULT sbrk
MSPACES
#define MSPACES 0
MUNMAP_DEFAULT
#define MUNMAP_DEFAULT (a, s)
Value:
munmap((a), (s))
next_chunk
#define next_chunk (p)
Value:
((mchunkptr)(((char*)(p)) + ((p)->head & ~FLAG_BITS)))
Referenced by internal_bulk_free(), internal_mallinfo(), and sys_alloc().
next_pinuse
#define next_pinuse (p)
Value:
((next_chunk(p)->head) & PINUSE_BIT)
NO_MALLINFO
#define NO_MALLINFO 0
NO_MALLOC_STATS
#define NO_MALLOC_STATS 1
NO_SEGMENT_TRAVERSAL
#define NO_SEGMENT_TRAVERSAL 0
Referenced by release_unused_segments(), and sys_alloc().
NOINLINE
#define NOINLINE
NSMALLBINS
#define NSMALLBINS (32U)
Referenced by init_bins().
NTREEBINS
#define NTREEBINS (32U)
ok_address
#define ok_address (M, a)
Value:
((char*)(a) >= (M)->least_addr)
Referenced by dispose_chunk(), dlfree(), internal_bulk_free(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
ok_inuse
#define ok_inuse (p)
Value:
is_inuse(p)
Referenced by dlfree(), internal_bulk_free(), and try_realloc_chunk().
ok_magic
#define ok_magic (M)
Value:
(1)
Referenced by dlfree(), dlrealloc(), and dlrealloc_in_place().
ok_next
#define ok_next (p, n)
Value:
((char*)(p) < (char*)(n))
Referenced by dlfree(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
ok_pinuse
#define ok_pinuse (p)
Value:
pinuse(p)
Referenced by dlfree(), and try_realloc_chunk().
ONLY_MSPACES
#define ONLY_MSPACES 0
overhead_for
#define overhead_for (p)
Value:
 (is_mmapped(p)? MMAP_CHUNK_OVERHEAD : CHUNK_OVERHEAD)
#define overhead_for(p)\
 (is_mmapped(p)? MMAP_CHUNK_OVERHEAD : CHUNK_OVERHEAD)
Referenced by dlmalloc_usable_size(), and dlrealloc().
pad_request
#define pad_request (req)
Value:
   (((req) + CHUNK_OVERHEAD + CHUNK_ALIGN_MASK) & ~CHUNK_ALIGN_MASK)
#define pad_request(req) \
   (((req) + CHUNK_OVERHEAD + CHUNK_ALIGN_MASK) & ~CHUNK_ALIGN_MASK)
Referenced by add_segment(), and dlmalloc().
page_align
#define page_align (S)
Value:
 (((S) + (mparams.page_size - SIZE_T_ONE)) & ~(mparams.page_size - SIZE_T_ONE))
#define page_align(S)\
 (((S) + (mparams.page_size - SIZE_T_ONE)) & ~(mparams.page_size - SIZE_T_ONE))
Referenced by sys_alloc().
pinuse
#define pinuse (p)
Value:
((p)->head & PINUSE_BIT)
Referenced by dispose_chunk(), dlfree(), and prepend_alloc().
PINUSE_BIT
#define PINUSE_BIT (SIZE_T_ONE)
Referenced by dispose_chunk(), dlfree(), dlmalloc(), init_top(), prepend_alloc(), sys_alloc(), and try_realloc_chunk().
POSTACTION
#define POSTACTION (M)
Value:
{ if (use_lock(M)) RELEASE_LOCK(&(M)->mutex); }
Referenced by dlfree(), dlmalloc(), dlmalloc_trim(), dlrealloc(), dlrealloc_in_place(), ialloc(), internal_bulk_free(), internal_mallinfo(), and internal_memalign().
PREACTION
#define PREACTION (M)
Value:
((use_lock(M))? ACQUIRE_LOCK(&(M)->mutex) : 0)
Referenced by dlfree(), dlmalloc(), dlmalloc_trim(), dlrealloc(), dlrealloc_in_place(), ialloc(), internal_bulk_free(), internal_mallinfo(), and internal_memalign().
prev_chunk
#define prev_chunk (p)
Value:
((mchunkptr)(((char*)(p)) - ((p)->prev_foot)))
PROCEED_ON_ERROR
#define PROCEED_ON_ERROR 0
real_calloc
#define real_calloc dlcalloc
Referenced by SDL_GetOriginalMemoryFunctions().
real_free
#define real_free dlfree
Referenced by SDL_GetOriginalMemoryFunctions().
real_malloc
#define real_malloc dlmalloc
Referenced by SDL_GetOriginalMemoryFunctions().
real_realloc
#define real_realloc dlrealloc
Referenced by SDL_GetOriginalMemoryFunctions().
RELEASE_LOCK
#define RELEASE_LOCK (lk)
Value:
pthread_mutex_unlock(lk)
RELEASE_MALLOC_GLOBAL_LOCK
#define RELEASE_MALLOC_GLOBAL_LOCK ()
Value:
RELEASE_LOCK(&malloc_global_mutex);
Referenced by init_mparams(), sys_alloc(), and sys_trim().
replace_dv
#define replace_dv (M, P, S)
Value:
  {\
  size_t DVS = M->dvsize;\
  assert(is_small(DVS));\
  if (DVS != 0) {\
    mchunkptr DV = M->dv;\
    insert_small_chunk(M, DV, DVS);\
  }\
  M->dvsize = S;\
  M->dv = P;\
}
#define replace_dv(M, P, S) {\
  size_t DVS = M->dvsize;\
  assert(is_small(DVS));\
  if (DVS != 0) {\
    mchunkptr DV = M->dv;\
    insert_small_chunk(M, DV, DVS);\
  }\
  M->dvsize = S;\
  M->dv = P;\
}
Referenced by dlmalloc(), and tmalloc_small().
request2size
#define request2size (req)
Value:
  (((req) < MIN_REQUEST)? MIN_CHUNK_SIZE : pad_request(req))
#define request2size(req) \
  (((req) < MIN_REQUEST)? MIN_CHUNK_SIZE : pad_request(req))
Referenced by dlrealloc(), dlrealloc_in_place(), ialloc(), and internal_memalign().
RTCHECK
#define RTCHECK (e)
Value:
(e)
Referenced by dispose_chunk(), dlfree(), internal_bulk_free(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
same_or_left_bits
#define same_or_left_bits (x)
Value:
((x) | -(x))
segment_holds
#define segment_holds (S, A)
Value:
  ((char*)(A) >= S->base && (char*)(A) < S->base + S->size)
#define segment_holds(S, A)\
  ((char*)(A) >= S->base && (char*)(A) < S->base + S->size)
Referenced by internal_mallinfo(), release_unused_segments(), and sys_alloc().
set_flag4
#define set_flag4 (p)
Value:
((p)->head |= FLAG4_BIT)
set_foot
#define set_foot (p, s)
Value:
(((mchunkptr)((char*)(p) + (s)))->prev_foot = (s))
set_free_with_pinuse
#define set_free_with_pinuse (p, s, n)
Value:
  (clear_pinuse(n), set_size_and_pinuse_of_free_chunk(p, s))
#define set_free_with_pinuse(p, s, n)\
  (clear_pinuse(n), set_size_and_pinuse_of_free_chunk(p, s))
Referenced by add_segment(), dispose_chunk(), dlfree(), and prepend_alloc().
set_inuse
#define set_inuse (M, p, s)
Value:
  ((p)->head = (((p)->head & PINUSE_BIT)|s|CINUSE_BIT),\
  ((mchunkptr)(((char*)(p)) + (s)))->head |= PINUSE_BIT)
#define set_inuse(M,p,s)\
  ((p)->head = (((p)->head & PINUSE_BIT)|s|CINUSE_BIT),\
  ((mchunkptr)(((char*)(p)) + (s)))->head |= PINUSE_BIT)
Referenced by internal_bulk_free(), internal_memalign(), and try_realloc_chunk().
set_inuse_and_pinuse
#define set_inuse_and_pinuse (M, p, s)
Value:
  ((p)->head = (s|PINUSE_BIT|CINUSE_BIT),\
  ((mchunkptr)(((char*)(p)) + (s)))->head |= PINUSE_BIT)
#define set_inuse_and_pinuse(M,p,s)\
  ((p)->head = (s|PINUSE_BIT|CINUSE_BIT),\
  ((mchunkptr)(((char*)(p)) + (s)))->head |= PINUSE_BIT)
Referenced by dlmalloc(), tmalloc_large(), and tmalloc_small().
set_lock
#define set_lock (M, L)
Value:
 ((M)->mflags = (L)?\
  ((M)->mflags | USE_LOCK_BIT) :\
  ((M)->mflags & ~USE_LOCK_BIT))
#define set_lock(M,L)\
 ((M)->mflags = (L)?\
  ((M)->mflags | USE_LOCK_BIT) :\
  ((M)->mflags & ~USE_LOCK_BIT))
set_size_and_pinuse_of_free_chunk
#define set_size_and_pinuse_of_free_chunk (p, s)
Value:
  ((p)->head = (s|PINUSE_BIT), set_foot(p, s))
#define set_size_and_pinuse_of_free_chunk(p, s)\
  ((p)->head = (s|PINUSE_BIT), set_foot(p, s))
Referenced by dispose_chunk(), dlfree(), dlmalloc(), prepend_alloc(), tmalloc_large(), tmalloc_small(), and try_realloc_chunk().
set_size_and_pinuse_of_inuse_chunk
#define set_size_and_pinuse_of_inuse_chunk (M, p, s)
Value:
  ((p)->head = (s|PINUSE_BIT|CINUSE_BIT))
#define set_size_and_pinuse_of_inuse_chunk(M, p, s)\
  ((p)->head = (s|PINUSE_BIT|CINUSE_BIT))
Referenced by add_segment(), dlmalloc(), ialloc(), prepend_alloc(), sys_alloc(), tmalloc_large(), and tmalloc_small().
should_trim
#define should_trim (M, s)
Value:
((s) > (M)->trim_check)
Referenced by dlfree(), and internal_bulk_free().
SIX_SIZE_T_SIZES
#define SIX_SIZE_T_SIZES (FOUR_SIZE_T_SIZES+TWO_SIZE_T_SIZES)
Referenced by mmap_alloc(), and mmap_resize().
SIZE_T_BITSIZE
#define SIZE_T_BITSIZE (sizeof(size_t) << 3)
Referenced by tmalloc_large().
SIZE_T_FOUR
#define SIZE_T_FOUR ((size_t)4)
SIZE_T_ONE
#define SIZE_T_ONE ((size_t)1)
Referenced by dlposix_memalign(), dlpvalloc(), init_mparams(), internal_mallinfo(), internal_memalign(), sys_trim(), and tmalloc_large().
SIZE_T_SIZE
#define SIZE_T_SIZE (sizeof(size_t))
Referenced by add_segment(), dlmalloc(), ialloc(), mmap_alloc(), and mmap_resize().
SIZE_T_TWO
#define SIZE_T_TWO ((size_t)2)
SIZE_T_ZERO
#define SIZE_T_ZERO ((size_t)0)
small_index
#define small_index (s)
Value:
(bindex_t)((s)  >> SMALLBIN_SHIFT)
Referenced by dlmalloc().
small_index2size
#define small_index2size (i)
Value:
((i)  << SMALLBIN_SHIFT)
Referenced by dlmalloc().
smallbin_at
#define smallbin_at (M, i)
Value:
((sbinptr)((char*)&((M)->smallbins[(i)<<1])))
Referenced by dlmalloc(), and init_bins().
SMALLBIN_SHIFT
#define SMALLBIN_SHIFT (3U)
SMALLBIN_WIDTH
#define SMALLBIN_WIDTH (SIZE_T_ONE << SMALLBIN_SHIFT)
smallmap_is_marked
#define smallmap_is_marked (M, i)
Value:
((M)->smallmap &   idx2bit(i))
STRUCT_MALLINFO_DECLARED
#define STRUCT_MALLINFO_DECLARED 1
SYS_ALLOC_PADDING
#define SYS_ALLOC_PADDING (TOP_FOOT_SIZE + MALLOC_ALIGNMENT)
Referenced by sys_alloc().
TOP_FOOT_SIZE
#define TOP_FOOT_SIZE (align_offset(chunk2mem(0))+pad_request(sizeof(struct malloc_segment))+MIN_CHUNK_SIZE)
#define TOP_FOOT_SIZE\
  (align_offset(chunk2mem(0))+pad_request(sizeof(struct malloc_segment))+MIN_CHUNK_SIZE)
Referenced by add_segment(), init_top(), internal_mallinfo(), release_unused_segments(), sys_alloc(), and sys_trim().
treebin_at
#define treebin_at (M, i)
Value:
(&((M)->treebins[i]))
Referenced by tmalloc_large(), and tmalloc_small().
TREEBIN_SHIFT
#define TREEBIN_SHIFT (8U)
treemap_is_marked
#define treemap_is_marked (M, i)
Value:
((M)->treemap  &   idx2bit(i))
TRY_LOCK
#define TRY_LOCK (lk)
Value:
(!pthread_mutex_trylock(lk))
TWO_SIZE_T_SIZES
#define TWO_SIZE_T_SIZES (SIZE_T_SIZE<<1)
unlink_chunk
#define unlink_chunk (M, P, S)
Value:
  if (is_small(S)) unlink_small_chunk(M, P, S)\
  else { tchunkptr TP = (tchunkptr)(P); unlink_large_chunk(M, TP); }
#define unlink_chunk(M, P, S)\
  if (is_small(S)) unlink_small_chunk(M, P, S)\
  else { tchunkptr TP = (tchunkptr)(P); unlink_large_chunk(M, TP); }
Referenced by dispose_chunk(), dlfree(), prepend_alloc(), and try_realloc_chunk().
unlink_first_small_chunk
#define unlink_first_small_chunk (M, B, P, I)
Value:
  {\
  mchunkptr F = P->fd;\
  assert(P != B);\
  assert(P != F);\
  assert(chunksize(P) == small_index2size(I));\
  if (B == F) {\
    clear_smallmap(M, I);\
  }\
  else if (RTCHECK(ok_address(M, F) && F->bk == P)) {\
    F->bk = B;\
    B->fd = F;\
  }\
  else {\
    CORRUPTION_ERROR_ACTION(M);\
  }\
}
#define unlink_first_small_chunk(M, B, P, I) {\
  mchunkptr F = P->fd;\
  assert(P != B);\
  assert(P != F);\
  assert(chunksize(P) == small_index2size(I));\
  if (B == F) {\
    clear_smallmap(M, I);\
  }\
  else if (RTCHECK(ok_address(M, F) && F->bk == P)) {\
    F->bk = B;\
    B->fd = F;\
  }\
  else {\
    CORRUPTION_ERROR_ACTION(M);\
  }\
}
Referenced by dlmalloc().
unlink_large_chunk
#define unlink_large_chunk (M, X)
#define unlink_large_chunk(M, X) {\
  tchunkptr XP = X->parent;\
  tchunkptr R;\
  if (X->bk != X) {\
    tchunkptr F = X->fd;\
    R = X->bk;\
    if (RTCHECK(ok_address(M, F) && F->bk == X && R->fd == X)) {\
      F->bk = R;\
      R->fd = F;\
    }\
    else {\
      CORRUPTION_ERROR_ACTION(M);\
    }\
  }\
  else {\
    tchunkptr* RP;\
    if (((R = *(RP = &(X->child[1]))) != 0) ||\
        ((R = *(RP = &(X->child[0]))) != 0)) {\
      tchunkptr* CP;\
      while ((*(CP = &(R->child[1])) != 0) ||\
             (*(CP = &(R->child[0])) != 0)) {\
        R = *(RP = CP);\
      }\
      if (RTCHECK(ok_address(M, RP)))\
        *RP = 0;\
      else {\
        CORRUPTION_ERROR_ACTION(M);\
      }\
    }\
  }\
  if (XP != 0) {\
    tbinptr* H = treebin_at(M, X->index);\
    if (X == *H) {\
      if ((*H = R) == 0) \
        clear_treemap(M, X->index);\
    }\
    else if (RTCHECK(ok_address(M, XP))) {\
      if (XP->child[0] == X) \
        XP->child[0] = R;\
      else \
        XP->child[1] = R;\
    }\
    else\
      CORRUPTION_ERROR_ACTION(M);\
    if (R != 0) {\
      if (RTCHECK(ok_address(M, R))) {\
        tchunkptr C0, C1;\
        R->parent = XP;\
        if ((C0 = X->child[0]) != 0) {\
          if (RTCHECK(ok_address(M, C0))) {\
            R->child[0] = C0;\
            C0->parent = R;\
          }\
          else\
            CORRUPTION_ERROR_ACTION(M);\
        }\
        if ((C1 = X->child[1]) != 0) {\
          if (RTCHECK(ok_address(M, C1))) {\
            R->child[1] = C1;\
            C1->parent = R;\
          }\
          else\
            CORRUPTION_ERROR_ACTION(M);\
        }\
      }\
      else\
        CORRUPTION_ERROR_ACTION(M);\
    }\
  }\
}
Referenced by release_unused_segments(), tmalloc_large(), and tmalloc_small().
unlink_small_chunk
#define unlink_small_chunk (M, P, S)
Value:
  {\
  mchunkptr F = P->fd;\
  mchunkptr B = P->bk;\
  bindex_t I = small_index(S);\
  assert(P != B);\
  assert(P != F);\
  assert(chunksize(P) == small_index2size(I));\
  if (RTCHECK(F == smallbin_at(M,I) || (ok_address(M, F) && F->bk == P))) { \
    if (B == F) {\
      clear_smallmap(M, I);\
    }\
    else if (RTCHECK(B == smallbin_at(M,I) ||\
                     (ok_address(M, B) && B->fd == P))) {\
      F->bk = B;\
      B->fd = F;\
    }\
    else {\
      CORRUPTION_ERROR_ACTION(M);\
    }\
  }\
  else {\
    CORRUPTION_ERROR_ACTION(M);\
  }\
}
#define unlink_small_chunk(M, P, S) {\
  mchunkptr F = P->fd;\
  mchunkptr B = P->bk;\
  bindex_t I = small_index(S);\
  assert(P != B);\
  assert(P != F);\
  assert(chunksize(P) == small_index2size(I));\
  if (RTCHECK(F == smallbin_at(M,I) || (ok_address(M, F) && F->bk == P))) { \
    if (B == F) {\
      clear_smallmap(M, I);\
    }\
    else if (RTCHECK(B == smallbin_at(M,I) ||\
                     (ok_address(M, B) && B->fd == P))) {\
      F->bk = B;\
      B->fd = F;\
    }\
    else {\
      CORRUPTION_ERROR_ACTION(M);\
    }\
  }\
  else {\
    CORRUPTION_ERROR_ACTION(M);\
  }\
}
USAGE_ERROR_ACTION
#define USAGE_ERROR_ACTION (m, p)
Value:
ABORT
Referenced by dlfree(), dlrealloc(), dlrealloc_in_place(), and try_realloc_chunk().
USE_BUILTIN_FFS
#define USE_BUILTIN_FFS 0
USE_DEV_RANDOM
#define USE_DEV_RANDOM 0
USE_DL_PREFIX
#define USE_DL_PREFIX
use_lock
#define use_lock (M)
Value:
((M)->mflags &   USE_LOCK_BIT)
USE_LOCK_BIT
#define USE_LOCK_BIT (2U)
Referenced by init_mparams().
USE_LOCKS
#define USE_LOCKS 1
use_mmap
#define use_mmap (M)
Value:
((M)->mflags &   USE_MMAP_BIT)
Referenced by ialloc(), and sys_alloc().
USE_MMAP_BIT
#define USE_MMAP_BIT (SIZE_T_ONE)
Define CALL_MMAP/CALL_MUNMAP/CALL_DIRECT_MMAP
Referenced by init_mparams(), and sys_alloc().
use_noncontiguous
#define use_noncontiguous (M)
Value:
((M)->mflags &   USE_NONCONTIGUOUS_BIT)
Referenced by sys_alloc().
USE_NONCONTIGUOUS_BIT
#define USE_NONCONTIGUOUS_BIT (4U)
Referenced by init_mparams().
Typedef Documentation
bindex_t
typedef unsigned int bindex_t
binmap_t
typedef unsigned int binmap_t
flag_t
typedef unsigned int flag_t
mchunk
typedef struct malloc_chunk mchunk
mchunkptr
typedef struct malloc_chunk* mchunkptr
msegment
typedef struct malloc_segment msegment
msegmentptr
typedef struct malloc_segment* msegmentptr
mstate
typedef struct malloc_state* mstate
sbinptr
typedef struct malloc_chunk* sbinptr
tbinptr
typedef struct malloc_tree_chunk* tbinptr
tchunk
typedef struct malloc_tree_chunk tchunk
tchunkptr
typedef struct malloc_tree_chunk* tchunkptr
Function Documentation
add_segment()
void add_segment (mstate m, char * tbase, size_t tsize, flag_t mmapped) static
{
  /* Determine locations and sizes of segment, fenceposts, old top */
  char* old_top = (char*)m->top;
  msegmentptr oldsp = segment_holding(m, old_top);
  char* old_end = oldsp->base + oldsp->size;
  size_t ssize = pad_request(sizeof(struct malloc_segment));
  char* rawsp = old_end - (ssize + FOUR_SIZE_T_SIZES + CHUNK_ALIGN_MASK);
  size_t offset = align_offset(chunk2mem(rawsp));
  char* asp = rawsp + offset;
  char* csp = (asp < (old_top + MIN_CHUNK_SIZE))? old_top : asp;
  mchunkptr sp = (mchunkptr)csp;
  msegmentptr ss = (msegmentptr)(chunk2mem(sp));
  mchunkptr tnext = chunk_plus_offset(sp, ssize);
  mchunkptr p = tnext;
  int nfences = 0;
  /* reset top to new space */
  init_top(m, (mchunkptr)tbase, tsize - TOP_FOOT_SIZE);
  /* Set up segment record */
  assert(is_aligned(ss));
  set_size_and_pinuse_of_inuse_chunk(m, sp, ssize);
  *ss = m->seg; /* Push current record */
  m->seg.base = tbase;
  m->seg.size = tsize;
  m->seg.sflags = mmapped;
  m->seg.next = ss;
  /* Insert trailing fenceposts */
  for (;;) {
    mchunkptr nextp = chunk_plus_offset(p, SIZE_T_SIZE);
    p->head = FENCEPOST_HEAD;
    ++nfences;
    if ((char*)(&(nextp->head)) < old_end)
      p = nextp;
    else
      break;
  }
  (void)nfences;
  assert(nfences >= 2);
  /* Insert the rest of old top into a bin as an ordinary free chunk */
  if (csp != old_top) {
    mchunkptr q = (mchunkptr)old_top;
    size_t psize = csp - old_top;
    mchunkptr tn = chunk_plus_offset(q, psize);
    set_free_with_pinuse(q, psize, tn);
    insert_chunk(m, q, psize);
  }
  check_top_chunk(m, m->top);
}
References align_offset, assert, malloc_segment::base, check_top_chunk, chunk2mem, CHUNK_ALIGN_MASK, chunk_plus_offset, FENCEPOST_HEAD, FOUR_SIZE_T_SIZES, malloc_chunk::head, init_top(), insert_chunk, is_aligned, MIN_CHUNK_SIZE, malloc_segment::next, pad_request, malloc_state::seg, segment_holding(), set_free_with_pinuse, set_size_and_pinuse_of_inuse_chunk, malloc_segment::sflags, malloc_segment::size, SIZE_T_SIZE, malloc_state::top, TOP_FOOT_SIZE, and void().
Referenced by sys_alloc().
change_mparam()
int change_mparam (int param_number, int value) static
{
  size_t val;
  ensure_initialization();
  val = (value == -1)? MAX_SIZE_T : (size_t)value;
  switch(param_number) {
  case M_TRIM_THRESHOLD:
    mparams.trim_threshold = val;
    return 1;
  case M_GRANULARITY:
    if (val >= mparams.page_size && ((val & (val-1)) == 0)) {
      mparams.granularity = val;
      return 1;
    }
    else
      return 0;
  case M_MMAP_THRESHOLD:
    mparams.mmap_threshold = val;
    return 1;
  default:
    return 0;
  }
}
References ensure_initialization, M_GRANULARITY, M_MMAP_THRESHOLD, M_TRIM_THRESHOLD, MAX_SIZE_T, and mparams.
Referenced by dlmallopt().
dispose_chunk()
void dispose_chunk (mstate m, mchunkptr p, size_t psize) static
{
  mchunkptr next = chunk_plus_offset(p, psize);
  if (!pinuse(p)) {
    mchunkptr prev;
    size_t prevsize = p->prev_foot;
    if (is_mmapped(p)) {
      psize += prevsize + MMAP_FOOT_PAD;
      if (CALL_MUNMAP((char*)p - prevsize, psize) == 0)
        m->footprint -= psize;
      return;
    }
    prev = chunk_minus_offset(p, prevsize);
    psize += prevsize;
    p = prev;
    if (RTCHECK(ok_address(m, prev))) { /* consolidate backward */
      if (p != m->dv) {
        unlink_chunk(m, p, prevsize);
      }
      else if ((next->head & INUSE_BITS) == INUSE_BITS) {
        m->dvsize = psize;
        set_free_with_pinuse(p, psize, next);
        return;
      }
    }
    else {
      CORRUPTION_ERROR_ACTION(m);
      return;
    }
  }
  if (RTCHECK(ok_address(m, next))) {
    if (!cinuse(next)) {  /* consolidate forward */
      if (next == m->top) {
        size_t tsize = m->topsize += psize;
        m->top = p;
        p->head = tsize | PINUSE_BIT;
        if (p == m->dv) {
          m->dv = 0;
          m->dvsize = 0;
        }
        return;
      }
      else if (next == m->dv) {
        size_t dsize = m->dvsize += psize;
        m->dv = p;
        set_size_and_pinuse_of_free_chunk(p, dsize);
        return;
      }
      else {
        size_t nsize = chunksize(next);
        psize += nsize;
        unlink_chunk(m, next, nsize);
        set_size_and_pinuse_of_free_chunk(p, psize);
        if (p == m->dv) {
          m->dvsize = psize;
          return;
        }
      }
    }
    else {
      set_free_with_pinuse(p, psize, next);
    }
    insert_chunk(m, p, psize);
  }
  else {
    CORRUPTION_ERROR_ACTION(m);
  }
}
References CALL_MUNMAP, chunk_minus_offset, chunk_plus_offset, chunksize, cinuse, CORRUPTION_ERROR_ACTION, malloc_state::dv, malloc_state::dvsize, malloc_state::footprint, malloc_chunk::head, insert_chunk, INUSE_BITS, is_mmapped, MMAP_FOOT_PAD, ok_address, pinuse, PINUSE_BIT, malloc_chunk::prev_foot, RTCHECK, set_free_with_pinuse, set_size_and_pinuse_of_free_chunk, malloc_state::top, malloc_state::topsize, and unlink_chunk.
Referenced by internal_bulk_free(), internal_memalign(), and try_realloc_chunk().
dlbulk_free() [1/2]
size_t dlbulk_free (void ** , size_t n_elements) extern
References DLMALLOC_EXPORT.
dlbulk_free() [2/2]
size_t dlbulk_free (void * array[], size_t nelem)
{
  return internal_bulk_free(gm, array, nelem);
}
References gm, and internal_bulk_free().
dlcalloc()
void * dlcalloc (size_t n_elements, size_t elem_size) extern
{
  void* mem;
  size_t req = 0;
  if (n_elements != 0) {
    req = n_elements * elem_size;
    if (((n_elements | elem_size) & ~(size_t)0xffff) &&
        (req / n_elements != elem_size))
      req = MAX_SIZE_T; /* force downstream failure on overflow */
  }
  mem = dlmalloc(req);
  if (mem != 0 && calloc_must_clear(mem2chunk(mem)))
    memset(mem, 0, req);
  return mem;
}
References calloc_must_clear, dlmalloc(), MAX_SIZE_T, mem2chunk, and memset().
dlfree()
void dlfree (void * mem) extern
                       {
  /*
     Consolidate freed chunks with preceeding or succeeding bordering
     free chunks, if they exist, and then place in a bin.  Intermixed
     with special cases for top, dv, mmapped chunks, and usage errors.
  */
  if (mem != 0) {
    mchunkptr p  = mem2chunk(mem);
#if FOOTERS
    mstate fm = get_mstate_for(p);
    if (!ok_magic(fm)) {
      USAGE_ERROR_ACTION(fm, p);
      return;
    }
#else /* FOOTERS */
#define fm gm
#endif /* FOOTERS */
    if (!PREACTION(fm)) {
      check_inuse_chunk(fm, p);
      if (RTCHECK(ok_address(fm, p) && ok_inuse(p))) {
        size_t psize = chunksize(p);
        mchunkptr next = chunk_plus_offset(p, psize);
        if (!pinuse(p)) {
          size_t prevsize = p->prev_foot;
          if (is_mmapped(p)) {
            psize += prevsize + MMAP_FOOT_PAD;
            if (CALL_MUNMAP((char*)p - prevsize, psize) == 0)
              fm->footprint -= psize;
            goto postaction;
          }
          else {
            mchunkptr prev = chunk_minus_offset(p, prevsize);
            psize += prevsize;
            p = prev;
            if (RTCHECK(ok_address(fm, prev))) { /* consolidate backward */
              if (p != fm->dv) {
                unlink_chunk(fm, p, prevsize);
              }
              else if ((next->head & INUSE_BITS) == INUSE_BITS) {
                fm->dvsize = psize;
                set_free_with_pinuse(p, psize, next);
                goto postaction;
              }
            }
            else
              goto erroraction;
          }
        }
        if (RTCHECK(ok_next(p, next) && ok_pinuse(next))) {
          if (!cinuse(next)) {  /* consolidate forward */
            if (next == fm->top) {
              size_t tsize = fm->topsize += psize;
              fm->top = p;
              p->head = tsize | PINUSE_BIT;
              if (p == fm->dv) {
                fm->dv = 0;
                fm->dvsize = 0;
              }
              if (should_trim(fm, tsize))
                sys_trim(fm, 0);
              goto postaction;
            }
            else if (next == fm->dv) {
              size_t dsize = fm->dvsize += psize;
              fm->dv = p;
              set_size_and_pinuse_of_free_chunk(p, dsize);
              goto postaction;
            }
            else {
              size_t nsize = chunksize(next);
              psize += nsize;
              unlink_chunk(fm, next, nsize);
              set_size_and_pinuse_of_free_chunk(p, psize);
              if (p == fm->dv) {
                fm->dvsize = psize;
                goto postaction;
              }
            }
          }
          else
            set_free_with_pinuse(p, psize, next);
          if (is_small(psize)) {
            insert_small_chunk(fm, p, psize);
            check_free_chunk(fm, p);
          }
          else {
            tchunkptr tp = (tchunkptr)p;
            insert_large_chunk(fm, tp, psize);
            check_free_chunk(fm, p);
            if (--fm->release_checks == 0)
              release_unused_segments(fm);
          }
          goto postaction;
        }
      }
    erroraction:
      USAGE_ERROR_ACTION(fm, p);
    postaction:
      POSTACTION(fm);
    }
  }
#if !FOOTERS
#undef fm
#endif /* FOOTERS */
}
References CALL_MUNMAP, check_free_chunk, check_inuse_chunk, chunk_minus_offset, chunk_plus_offset, chunksize, cinuse, fm, malloc_chunk::head, insert_large_chunk, insert_small_chunk, INUSE_BITS, is_mmapped, is_small, mem2chunk, MMAP_FOOT_PAD, ok_address, ok_inuse, ok_magic, ok_next, ok_pinuse, pinuse, PINUSE_BIT, POSTACTION, PREACTION, malloc_chunk::prev_foot, release_unused_segments(), RTCHECK, set_free_with_pinuse, set_size_and_pinuse_of_free_chunk, should_trim, sys_trim(), unlink_chunk, and USAGE_ERROR_ACTION.
Referenced by dlrealloc().
dlindependent_calloc() [1/2]
void ** dlindependent_calloc (size_t n_elements, size_t elem_size, void * chunks[])
{
  size_t sz = elem_size; /* serves as 1-element array */
  return ialloc(gm, n_elements, &sz, 3, chunks);
}
References gm, and ialloc().
dlindependent_calloc() [2/2]
void ** dlindependent_calloc (size_t , size_t , void **) extern
References DLMALLOC_EXPORT.
dlindependent_comalloc() [1/2]
void ** dlindependent_comalloc (size_t n_elements, size_t sizes[], void * chunks[])
{
  return ialloc(gm, n_elements, sizes, 0, chunks);
}
References gm, and ialloc().
dlindependent_comalloc() [2/2]
void ** dlindependent_comalloc (size_t , size_t * , void **) extern
References DLMALLOC_EXPORT.
dlmallinfo()
struct mallinfo dlmallinfo (void) extern
{
  return internal_mallinfo(gm);
}
References dlmallinfo(), gm, internal_mallinfo(), and void().
Referenced by dlmallinfo().
dlmalloc()
void * dlmalloc (size_t bytes) extern
{
  /*
     Basic algorithm:
     If a small request (< 256 bytes minus per-chunk overhead):
       1. If one exists, use a remainderless chunk in associated smallbin.
          (Remainderless means that there are too few excess bytes to
          represent as a chunk.)
       2. If it is big enough, use the dv chunk, which is normally the
          chunk adjacent to the one used for the most recent small request.
       3. If one exists, split the smallest available chunk in a bin,
          saving remainder in dv.
       4. If it is big enough, use the top chunk.
       5. If available, get memory from system and use it
     Otherwise, for a large request:
       1. Find the smallest available binned chunk that fits, and use it
          if it is better fitting than dv chunk, splitting if necessary.
       2. If better fitting than any binned chunk, use the dv chunk.
       3. If it is big enough, use the top chunk.
       4. If request size >= mmap threshold, try to directly mmap this chunk.
       5. If available, get memory from system and use it
     The ugly goto's here ensure that postaction occurs along all paths.
  */
#if USE_LOCKS
  ensure_initialization(); /* initialize in sys_alloc if not using locks */
#endif
  if (!PREACTION(gm)) {
    void* mem;
    size_t nb;
    if (bytes <= MAX_SMALL_REQUEST) {
      bindex_t idx;
      binmap_t smallbits;
      nb = (bytes < MIN_REQUEST)? MIN_CHUNK_SIZE : pad_request(bytes);
      idx = small_index(nb);
      smallbits = gm->smallmap >> idx;
      if ((smallbits & 0x3U) != 0) { /* Remainderless fit to a smallbin. */
        mchunkptr b, p;
        idx += ~smallbits & 1;       /* Uses next bin if idx empty */
        b = smallbin_at(gm, idx);
        p = b->fd;
        assert(chunksize(p) == small_index2size(idx));
        unlink_first_small_chunk(gm, b, p, idx);
        set_inuse_and_pinuse(gm, p, small_index2size(idx));
        mem = chunk2mem(p);
        check_malloced_chunk(gm, mem, nb);
        goto postaction;
      }
      else if (nb > gm->dvsize) {
        if (smallbits != 0) { /* Use chunk in next nonempty smallbin */
          mchunkptr b, p, r;
          size_t rsize;
          bindex_t i;
          binmap_t leftbits = (smallbits << idx) & left_bits(idx2bit(idx));
          binmap_t leastbit = least_bit(leftbits);
          compute_bit2idx(leastbit, i);
          b = smallbin_at(gm, i);
          p = b->fd;
          assert(chunksize(p) == small_index2size(i));
          unlink_first_small_chunk(gm, b, p, i);
          rsize = small_index2size(i) - nb;
          /* Fit here cannot be remainderless if 4byte sizes */
          if (SIZE_T_SIZE != 4 && rsize < MIN_CHUNK_SIZE)
            set_inuse_and_pinuse(gm, p, small_index2size(i));
          else {
            set_size_and_pinuse_of_inuse_chunk(gm, p, nb);
            r = chunk_plus_offset(p, nb);
            set_size_and_pinuse_of_free_chunk(r, rsize);
            replace_dv(gm, r, rsize);
          }
          mem = chunk2mem(p);
          check_malloced_chunk(gm, mem, nb);
          goto postaction;
        }
        else if (gm->treemap != 0 && (mem = tmalloc_small(gm, nb)) != 0) {
          check_malloced_chunk(gm, mem, nb);
          goto postaction;
        }
      }
    }
    else if (bytes >= MAX_REQUEST)
      nb = MAX_SIZE_T; /* Too big to allocate. Force failure (in sys alloc) */
    else {
      nb = pad_request(bytes);
      if (gm->treemap != 0 && (mem = tmalloc_large(gm, nb)) != 0) {
        check_malloced_chunk(gm, mem, nb);
        goto postaction;
      }
    }
    if (nb <= gm->dvsize) {
      size_t rsize = gm->dvsize - nb;
      mchunkptr p = gm->dv;
      if (rsize >= MIN_CHUNK_SIZE) { /* split dv */
        mchunkptr r = gm->dv = chunk_plus_offset(p, nb);
        gm->dvsize = rsize;
        set_size_and_pinuse_of_free_chunk(r, rsize);
        set_size_and_pinuse_of_inuse_chunk(gm, p, nb);
      }
      else { /* exhaust dv */
        size_t dvs = gm->dvsize;
        gm->dvsize = 0;
        gm->dv = 0;
        set_inuse_and_pinuse(gm, p, dvs);
      }
      mem = chunk2mem(p);
      check_malloced_chunk(gm, mem, nb);
      goto postaction;
    }
    else if (nb < gm->topsize) { /* Split top */
      size_t rsize = gm->topsize -= nb;
      mchunkptr p = gm->top;
      mchunkptr r = gm->top = chunk_plus_offset(p, nb);
      r->head = rsize | PINUSE_BIT;
      set_size_and_pinuse_of_inuse_chunk(gm, p, nb);
      mem = chunk2mem(p);
      check_top_chunk(gm, gm->top);
      check_malloced_chunk(gm, mem, nb);
      goto postaction;
    }
    mem = sys_alloc(gm, nb);
  postaction:
    POSTACTION(gm);
    return mem;
  }
  return 0;
}
References assert, check_malloced_chunk, check_top_chunk, chunk2mem, chunk_plus_offset, chunksize, compute_bit2idx, ensure_initialization, malloc_chunk::fd, gm, malloc_chunk::head, idx2bit, least_bit, left_bits, MAX_REQUEST, MAX_SIZE_T, MAX_SMALL_REQUEST, MIN_CHUNK_SIZE, MIN_REQUEST, pad_request, PINUSE_BIT, POSTACTION, PREACTION, replace_dv, set_inuse_and_pinuse, set_size_and_pinuse_of_free_chunk, set_size_and_pinuse_of_inuse_chunk, SIZE_T_SIZE, small_index, small_index2size, smallbin_at, sys_alloc(), tmalloc_large(), tmalloc_small(), and unlink_first_small_chunk.
Referenced by dlcalloc(), dlmemalign(), dlposix_memalign(), and dlrealloc().
dlmalloc_footprint()
size_t dlmalloc_footprint (void) extern
{
  return gm->footprint;
}
References gm.
dlmalloc_footprint_limit()
size_t dlmalloc_footprint_limit (void) extern
{
  size_t maf = gm->footprint_limit;
  return maf == 0 ? MAX_SIZE_T : maf;
}
References gm, and MAX_SIZE_T.
dlmalloc_max_footprint()
size_t dlmalloc_max_footprint (void) extern
{
  return gm->max_footprint;
}
References gm.
dlmalloc_set_footprint_limit()
size_t dlmalloc_set_footprint_limit (size_t bytes) extern
{
  size_t result;  /* invert sense of 0 */
  if (bytes == 0)
    result = granularity_align(1); /* Use minimal size */
  if (bytes == MAX_SIZE_T)
    result = 0;                    /* disable */
  else
    result = granularity_align(bytes);
  return gm->footprint_limit = result;
}
References gm, granularity_align, and MAX_SIZE_T.
dlmalloc_stats()
void dlmalloc_stats (void) extern
References DLMALLOC_EXPORT.
dlmalloc_trim()
int dlmalloc_trim (size_t pad) extern
{
  int result = 0;
  ensure_initialization();
  if (!PREACTION(gm)) {
    result = sys_trim(gm, pad);
    POSTACTION(gm);
  }
  return result;
}
References ensure_initialization, gm, POSTACTION, PREACTION, and sys_trim().
dlmalloc_usable_size()
size_t dlmalloc_usable_size (void * mem)
{
  if (mem != 0) {
    mchunkptr p = mem2chunk(mem);
    if (is_inuse(p))
      return chunksize(p) - overhead_for(p);
  }
  return 0;
}
References chunksize, is_inuse, mem2chunk, and overhead_for.
dlmallopt()
int dlmallopt (int param_number, int value) extern
{
  return change_mparam(param_number, value);
}
References change_mparam().
dlmemalign()
void * dlmemalign (size_t alignment, size_t bytes) extern
{
  if (alignment <= MALLOC_ALIGNMENT) {
    return dlmalloc(bytes);
  }
  return internal_memalign(gm, alignment, bytes);
}
References dlmalloc(), gm, internal_memalign(), and MALLOC_ALIGNMENT.
Referenced by dlpvalloc(), and dlvalloc().
dlposix_memalign()
int dlposix_memalign (void ** pp, size_t alignment, size_t bytes) extern
{
  void* mem = 0;
  if (alignment == MALLOC_ALIGNMENT)
    mem = dlmalloc(bytes);
  else {
    size_t d = alignment / sizeof(void*);
    size_t r = alignment % sizeof(void*);
    if (r != 0 || d == 0 || (d & (d-SIZE_T_ONE)) != 0)
      return EINVAL;
    else if (bytes <= MAX_REQUEST - alignment) {
      if (alignment <  MIN_CHUNK_SIZE)
        alignment = MIN_CHUNK_SIZE;
      mem = internal_memalign(gm, alignment, bytes);
    }
  }
  if (mem == 0)
    return ENOMEM;
  else {
    *pp = mem;
    return 0;
  }
}
References d, dlmalloc(), gm, internal_memalign(), MALLOC_ALIGNMENT, MAX_REQUEST, MIN_CHUNK_SIZE, and SIZE_T_ONE.
dlpvalloc()
void * dlpvalloc (size_t bytes) extern
{
  size_t pagesz;
  ensure_initialization();
  pagesz = mparams.page_size;
  return dlmemalign(pagesz, (bytes + pagesz - SIZE_T_ONE) & ~(pagesz - SIZE_T_ONE));
}
References dlmemalign(), ensure_initialization, mparams, and SIZE_T_ONE.
dlrealloc()
void * dlrealloc (void * oldmem, size_t bytes) extern
{
  void* mem = 0;
  if (oldmem == 0) {
    mem = dlmalloc(bytes);
  }
  else if (bytes >= MAX_REQUEST) {
    MALLOC_FAILURE_ACTION;
  }
#ifdef REALLOC_ZERO_BYTES_FREES
  else if (bytes == 0) {
    dlfree(oldmem);
  }
#endif /* REALLOC_ZERO_BYTES_FREES */
  else {
    size_t nb = request2size(bytes);
    mchunkptr oldp = mem2chunk(oldmem);
#if ! FOOTERS
    mstate m = gm;
#else /* FOOTERS */
    mstate m = get_mstate_for(oldp);
    if (!ok_magic(m)) {
      USAGE_ERROR_ACTION(m, oldmem);
      return 0;
    }
#endif /* FOOTERS */
    if (!PREACTION(m)) {
      mchunkptr newp = try_realloc_chunk(m, oldp, nb, 1);
      POSTACTION(m);
      if (newp != 0) {
        check_inuse_chunk(m, newp);
        mem = chunk2mem(newp);
      }
      else {
        mem = internal_malloc(m, bytes);
        if (mem != 0) {
          size_t oc = chunksize(oldp) - overhead_for(oldp);
          memcpy(mem, oldmem, (oc < bytes)? oc : bytes);
          internal_free(m, oldmem);
        }
      }
    }
  }
  return mem;
}
References check_inuse_chunk, chunk2mem, chunksize, dlfree(), dlmalloc(), gm, internal_free, internal_malloc, MALLOC_FAILURE_ACTION, MAX_REQUEST, mem2chunk, memcpy, ok_magic, overhead_for, POSTACTION, PREACTION, request2size, try_realloc_chunk(), and USAGE_ERROR_ACTION.
dlrealloc_in_place()
void * dlrealloc_in_place (void * oldmem, size_t bytes) extern
{
  void* mem = 0;
  if (oldmem != 0) {
    if (bytes >= MAX_REQUEST) {
      MALLOC_FAILURE_ACTION;
    }
    else {
      size_t nb = request2size(bytes);
      mchunkptr oldp = mem2chunk(oldmem);
#if ! FOOTERS
      mstate m = gm;
#else /* FOOTERS */
      mstate m = get_mstate_for(oldp);
      if (!ok_magic(m)) {
        USAGE_ERROR_ACTION(m, oldmem);
        return 0;
      }
#endif /* FOOTERS */
      if (!PREACTION(m)) {
        mchunkptr newp = try_realloc_chunk(m, oldp, nb, 0);
        POSTACTION(m);
        if (newp == oldp) {
          check_inuse_chunk(m, newp);
          mem = oldmem;
        }
      }
    }
  }
  return mem;
}
References check_inuse_chunk, gm, MALLOC_FAILURE_ACTION, MAX_REQUEST, mem2chunk, ok_magic, POSTACTION, PREACTION, request2size, try_realloc_chunk(), and USAGE_ERROR_ACTION.
dlvalloc()
void * dlvalloc (size_t bytes) extern
{
  size_t pagesz;
  ensure_initialization();
  pagesz = mparams.page_size;
  return dlmemalign(pagesz, bytes);
}
References dlmemalign(), ensure_initialization, and mparams.
has_segment_link()
int has_segment_link (mstate m, msegmentptr ss) static
{
  msegmentptr sp = &m->seg;
  for (;;) {
    if ((char*)sp >= ss->base && (char*)sp < ss->base + ss->size)
      return 1;
    if ((sp = sp->next) == 0)
      return 0;
  }
}
References malloc_segment::base, malloc_segment::next, malloc_state::seg, and malloc_segment::size.
Referenced by sys_trim().
ialloc()
void ** ialloc (mstate m, size_t n_elements, size_t * sizes, int opts, void * chunks[]) static
{
  size_t    element_size;   /* chunksize of each element, if all same */
  size_t    contents_size;  /* total size of elements */
  size_t    array_size;     /* request size of pointer array */
  void*     mem;            /* malloced aggregate space */
  mchunkptr p;              /* corresponding chunk */
  size_t    remainder_size; /* remaining bytes while splitting */
  void**    marray;         /* either "chunks" or malloced ptr array */
  mchunkptr array_chunk;    /* chunk for malloced ptr array */
  flag_t    was_enabled;    /* to disable mmap */
  size_t    size;
  size_t    i;
  ensure_initialization();
  /* compute array length, if needed */
  if (chunks != 0) {
    if (n_elements == 0)
      return chunks; /* nothing to do */
    marray = chunks;
    array_size = 0;
  }
  else {
    /* if empty req, must still return chunk representing empty array */
    if (n_elements == 0)
      return (void**)internal_malloc(m, 0);
    marray = 0;
    array_size = request2size(n_elements * (sizeof(void*)));
  }
  /* compute total element size */
  if (opts & 0x1) { /* all-same-size */
    element_size = request2size(*sizes);
    contents_size = n_elements * element_size;
  }
  else { /* add up all the sizes */
    element_size = 0;
    contents_size = 0;
    for (i = 0; i != n_elements; ++i)
      contents_size += request2size(sizes[i]);
  }
  size = contents_size + array_size;
  /*
     Allocate the aggregate chunk.  First disable direct-mmapping so
     malloc won't use it, since we would not be able to later
     free/realloc space internal to a segregated mmap region.
  */
  was_enabled = use_mmap(m);
  disable_mmap(m);
  mem = internal_malloc(m, size - CHUNK_OVERHEAD);
  if (was_enabled)
    enable_mmap(m);
  if (mem == 0)
    return 0;
  if (PREACTION(m)) return 0;
  p = mem2chunk(mem);
  remainder_size = chunksize(p);
  assert(!is_mmapped(p));
  if (opts & 0x2) {       /* optionally clear the elements */
    memset((size_t*)mem, 0, remainder_size - SIZE_T_SIZE - array_size);
  }
  /* If not provided, allocate the pointer array as final part of chunk */
  if (marray == 0) {
    size_t  array_chunk_size;
    array_chunk = chunk_plus_offset(p, contents_size);
    array_chunk_size = remainder_size - contents_size;
    marray = (void**) (chunk2mem(array_chunk));
    set_size_and_pinuse_of_inuse_chunk(m, array_chunk, array_chunk_size);
    remainder_size = contents_size;
  }
  /* split out elements */
  for (i = 0; ; ++i) {
    marray[i] = chunk2mem(p);
    if (i != n_elements-1) {
      if (element_size != 0)
        size = element_size;
      else
        size = request2size(sizes[i]);
      remainder_size -= size;
      set_size_and_pinuse_of_inuse_chunk(m, p, size);
      p = chunk_plus_offset(p, size);
    }
    else { /* the final element absorbs any overallocation slop */
      set_size_and_pinuse_of_inuse_chunk(m, p, remainder_size);
      break;
    }
  }
#if DEBUG
  if (marray != chunks) {
    /* final element must have exactly exhausted chunk */
    if (element_size != 0) {
      assert(remainder_size == element_size);
    }
    else {
      assert(remainder_size == request2size(sizes[i]));
    }
    check_inuse_chunk(m, mem2chunk(marray));
  }
  for (i = 0; i != n_elements; ++i)
    check_inuse_chunk(m, mem2chunk(marray[i]));
#endif /* DEBUG */
  POSTACTION(m);
  return marray;
}
References assert, check_inuse_chunk, chunk2mem, CHUNK_OVERHEAD, chunk_plus_offset, chunksize, disable_mmap, enable_mmap, ensure_initialization, internal_malloc, is_mmapped, mem2chunk, memset(), POSTACTION, PREACTION, request2size, set_size_and_pinuse_of_inuse_chunk, SIZE_T_SIZE, and use_mmap.
Referenced by dlindependent_calloc(), and dlindependent_comalloc().
init_bins()
void init_bins (mstate m) static
{
  /* Establish circular links for smallbins */
  bindex_t i;
  for (i = 0; i < NSMALLBINS; ++i) {
    sbinptr bin = smallbin_at(m,i);
    bin->fd = bin->bk = bin;
  }
}
References malloc_chunk::bk, malloc_chunk::fd, NSMALLBINS, and smallbin_at.
Referenced by sys_alloc().
init_mparams()
int init_mparams (void) static
{
#ifdef NEED_GLOBAL_LOCK_INIT
  if (malloc_global_mutex_status <= 0)
    init_malloc_global_mutex();
#endif
  ACQUIRE_MALLOC_GLOBAL_LOCK();
  if (mparams.magic == 0) {
    size_t magic;
    size_t psize;
    size_t gsize;
#ifndef WIN32
    psize = malloc_getpagesize;
    gsize = ((DEFAULT_GRANULARITY != 0)? DEFAULT_GRANULARITY : psize);
#else /* WIN32 */
    {
      SYSTEM_INFO system_info;
      GetSystemInfo(&system_info);
      psize = system_info.dwPageSize;
      gsize = ((DEFAULT_GRANULARITY != 0)?
               DEFAULT_GRANULARITY : system_info.dwAllocationGranularity);
    }
#endif /* WIN32 */
    /* Sanity-check configuration:
       size_t must be unsigned and as wide as pointer type.
       ints must be at least 4 bytes.
       alignment must be at least 8.
       Alignment, min chunk size, and page size must all be powers of 2.
    */
    if ((sizeof(size_t) != sizeof(char*)) ||
        (MAX_SIZE_T < MIN_CHUNK_SIZE)  ||
        (sizeof(int) < 4)  ||
        (MALLOC_ALIGNMENT < (size_t)8U) ||
        ((MALLOC_ALIGNMENT & (MALLOC_ALIGNMENT-SIZE_T_ONE)) != 0) ||
        ((MCHUNK_SIZE      & (MCHUNK_SIZE-SIZE_T_ONE))      != 0) ||
        ((gsize            & (gsize-SIZE_T_ONE))            != 0) ||
        ((psize            & (psize-SIZE_T_ONE))            != 0))
      ABORT;
    mparams.granularity = gsize;
    mparams.page_size = psize;
    mparams.mmap_threshold = DEFAULT_MMAP_THRESHOLD;
    mparams.trim_threshold = DEFAULT_TRIM_THRESHOLD;
#if MORECORE_CONTIGUOUS
    mparams.default_mflags = USE_LOCK_BIT|USE_MMAP_BIT;
#else  /* MORECORE_CONTIGUOUS */
    mparams.default_mflags = USE_LOCK_BIT|USE_MMAP_BIT|USE_NONCONTIGUOUS_BIT;
#endif /* MORECORE_CONTIGUOUS */
#if !ONLY_MSPACES
    /* Set up lock for main malloc area */
    gm->mflags = mparams.default_mflags;
    (void)INITIAL_LOCK(&gm->mutex);
#endif
#if LOCK_AT_FORK
    pthread_atfork(&pre_fork, &post_fork_parent, &post_fork_child);
#endif
    {
#if USE_DEV_RANDOM
      int fd;
      unsigned char buf[sizeof(size_t)];
      /* Try to use /dev/urandom, else fall back on using time */
      if ((fd = open("/dev/urandom", O_RDONLY)) >= 0 &&
          read(fd, buf, sizeof(buf)) == sizeof(buf)) {
        magic = *((size_t *) buf);
        close(fd);
      }
      else
#endif /* USE_DEV_RANDOM */
#ifdef WIN32
      magic = (size_t)(GetTickCount() ^ (size_t)0x55555555U);
#elif defined(LACKS_TIME_H)
      magic = (size_t)&magic ^ (size_t)0x55555555U;
#else
      magic = (size_t)(time(0) ^ (size_t)0x55555555U);
#endif
      magic |= (size_t)8U;    /* ensure nonzero */
      magic &= ~(size_t)7U;   /* improve chances of fault for bad values */
      /* Until memory modes commonly available, use volatile-write */
      (*(volatile size_t *)(&(mparams.magic))) = magic;
    }
  }
  RELEASE_MALLOC_GLOBAL_LOCK();
  return 1;
}
References ABORT, ACQUIRE_MALLOC_GLOBAL_LOCK, DEFAULT_GRANULARITY, DEFAULT_MMAP_THRESHOLD, DEFAULT_TRIM_THRESHOLD, gm, INITIAL_LOCK, malloc_state::magic, MALLOC_ALIGNMENT, malloc_getpagesize, MAX_SIZE_T, MCHUNK_SIZE, MIN_CHUNK_SIZE, mparams, RELEASE_MALLOC_GLOBAL_LOCK, SIZE_T_ONE, USE_LOCK_BIT, USE_MMAP_BIT, USE_NONCONTIGUOUS_BIT, and void().
init_top()
void init_top (mstate m, mchunkptr p, size_t psize) static
{
  /* Ensure alignment */
  size_t offset = align_offset(chunk2mem(p));
  p = (mchunkptr)((char*)p + offset);
  psize -= offset;
  m->top = p;
  m->topsize = psize;
  p->head = psize | PINUSE_BIT;
  /* set size of fake trailing chunk holding overhead space only once */
  chunk_plus_offset(p, psize)->head = TOP_FOOT_SIZE;
  m->trim_check = mparams.trim_threshold; /* reset on each update */
}
References align_offset, chunk2mem, chunk_plus_offset, malloc_chunk::head, mparams, PINUSE_BIT, malloc_state::top, TOP_FOOT_SIZE, malloc_state::topsize, and malloc_state::trim_check.
Referenced by add_segment(), sys_alloc(), and sys_trim().
internal_bulk_free()
size_t internal_bulk_free (mstate m, void * array[], size_t nelem) static
{
  size_t unfreed = 0;
  if (!PREACTION(m)) {
    void** a;
    void** fence = &(array[nelem]);
    for (a = array; a != fence; ++a) {
      void* mem = *a;
      if (mem != 0) {
        mchunkptr p = mem2chunk(mem);
        size_t psize = chunksize(p);
#if FOOTERS
        if (get_mstate_for(p) != m) {
          ++unfreed;
          continue;
        }
#endif
        check_inuse_chunk(m, p);
        *a = 0;
        if (RTCHECK(ok_address(m, p) && ok_inuse(p))) {
          void ** b = a + 1; /* try to merge with next chunk */
          mchunkptr next = next_chunk(p);
          if (b != fence && *b == chunk2mem(next)) {
            size_t newsize = chunksize(next) + psize;
            set_inuse(m, p, newsize);
            *b = chunk2mem(p);
          }
          else
            dispose_chunk(m, p, psize);
        }
        else {
          CORRUPTION_ERROR_ACTION(m);
          break;
        }
      }
    }
    if (should_trim(m, m->topsize))
      sys_trim(m, 0);
    POSTACTION(m);
  }
  return unfreed;
}
References check_inuse_chunk, chunk2mem, chunksize, CORRUPTION_ERROR_ACTION, dispose_chunk(), mem2chunk, next_chunk, ok_address, ok_inuse, POSTACTION, PREACTION, RTCHECK, set_inuse, should_trim, sys_trim(), and malloc_state::topsize.
Referenced by dlbulk_free().
internal_mallinfo()
struct mallinfo internal_mallinfo (mstate m) static
{
  struct mallinfo nm = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  ensure_initialization();
  if (!PREACTION(m)) {
    check_malloc_state(m);
    if (is_initialized(m)) {
      size_t nfree = SIZE_T_ONE; /* top always free */
      size_t mfree = m->topsize + TOP_FOOT_SIZE;
      size_t sum = mfree;
      msegmentptr s = &m->seg;
      while (s != 0) {
        mchunkptr q = align_as_chunk(s->base);
        while (segment_holds(s, q) &&
               q != m->top && q->head != FENCEPOST_HEAD) {
          size_t sz = chunksize(q);
          sum += sz;
          if (!is_inuse(q)) {
            mfree += sz;
            ++nfree;
          }
          q = next_chunk(q);
        }
        s = s->next;
      }
      nm.arena    = sum;
      nm.ordblks  = nfree;
      nm.hblkhd   = m->footprint - sum;
      nm.usmblks  = m->max_footprint;
      nm.uordblks = m->footprint - mfree;
      nm.fordblks = mfree;
      nm.keepcost = m->topsize;
    }
    POSTACTION(m);
  }
  return nm;
}
References align_as_chunk, mallinfo::arena, malloc_segment::base, check_malloc_state, chunksize, ensure_initialization, FENCEPOST_HEAD, malloc_state::footprint, mallinfo::fordblks, mallinfo::hblkhd, malloc_chunk::head, internal_mallinfo(), is_initialized, is_inuse, mallinfo::keepcost, malloc_state::max_footprint, malloc_segment::next, next_chunk, mallinfo::ordblks, POSTACTION, PREACTION, malloc_state::seg, segment_holds, SIZE_T_ONE, malloc_state::top, TOP_FOOT_SIZE, malloc_state::topsize, mallinfo::uordblks, and mallinfo::usmblks.
Referenced by dlmallinfo(), and internal_mallinfo().
internal_memalign()
void * internal_memalign (mstate m, size_t alignment, size_t bytes) static
{
  void* mem = 0;
  if (alignment <  MIN_CHUNK_SIZE) /* must be at least a minimum chunk size */
    alignment = MIN_CHUNK_SIZE;
  if ((alignment & (alignment-SIZE_T_ONE)) != 0) {/* Ensure a power of 2 */
    size_t a = MALLOC_ALIGNMENT << 1;
    while (a < alignment) a <<= 1;
    alignment = a;
  }
  if (bytes >= MAX_REQUEST - alignment) {
    if (m != 0)  { /* Test isn't needed but avoids compiler warning */
      MALLOC_FAILURE_ACTION;
    }
  }
  else {
    size_t nb = request2size(bytes);
    size_t req = nb + alignment + MIN_CHUNK_SIZE - CHUNK_OVERHEAD;
    mem = internal_malloc(m, req);
    if (mem != 0) {
      mchunkptr p = mem2chunk(mem);
      if (PREACTION(m))
        return 0;
      if ((((size_t)(mem)) & (alignment - 1)) != 0) { /* misaligned */
        /*
          Find an aligned spot inside chunk.  Since we need to give
          back leading space in a chunk of at least MIN_CHUNK_SIZE, if
          the first calculation places us at a spot with less than
          MIN_CHUNK_SIZE leader, we can move to the next aligned spot.
          We've allocated enough total room so that this is always
          possible.
        */
        char* br = (char*)mem2chunk((size_t)(((size_t)((char*)mem + alignment -
                                                       SIZE_T_ONE)) &
                                             -alignment));
        char* pos = ((size_t)(br - (char*)(p)) >= MIN_CHUNK_SIZE)?
          br : br+alignment;
        mchunkptr newp = (mchunkptr)pos;
        size_t leadsize = pos - (char*)(p);
        size_t newsize = chunksize(p) - leadsize;
        if (is_mmapped(p)) { /* For mmapped chunks, just adjust offset */
          newp->prev_foot = p->prev_foot + leadsize;
          newp->head = newsize;
        }
        else { /* Otherwise, give back leader, use the rest */
          set_inuse(m, newp, newsize);
          set_inuse(m, p, leadsize);
          dispose_chunk(m, p, leadsize);
        }
        p = newp;
      }
      /* Give back spare room at the end */
      if (!is_mmapped(p)) {
        size_t size = chunksize(p);
        if (size > nb + MIN_CHUNK_SIZE) {
          size_t remainder_size = size - nb;
          mchunkptr remainder = chunk_plus_offset(p, nb);
          set_inuse(m, p, nb);
          set_inuse(m, remainder, remainder_size);
          dispose_chunk(m, remainder, remainder_size);
        }
      }
      mem = chunk2mem(p);
      assert (chunksize(p) >= nb);
      assert(((size_t)mem & (alignment - 1)) == 0);
      check_inuse_chunk(m, p);
      POSTACTION(m);
    }
  }
  return mem;
}
References assert, check_inuse_chunk, chunk2mem, CHUNK_OVERHEAD, chunk_plus_offset, chunksize, dispose_chunk(), malloc_chunk::head, internal_malloc, is_mmapped, MALLOC_ALIGNMENT, MALLOC_FAILURE_ACTION, MAX_REQUEST, mem2chunk, MIN_CHUNK_SIZE, POSTACTION, PREACTION, malloc_chunk::prev_foot, request2size, set_inuse, and SIZE_T_ONE.
Referenced by dlmemalign(), and dlposix_memalign().
mmap_alloc()
void * mmap_alloc (mstate m, size_t nb) static
{
  size_t mmsize = mmap_align(nb + SIX_SIZE_T_SIZES + CHUNK_ALIGN_MASK);
  if (m->footprint_limit != 0) {
    size_t fp = m->footprint + mmsize;
    if (fp <= m->footprint || fp > m->footprint_limit)
      return 0;
  }
  if (mmsize > nb) {     /* Check for wrap around 0 */
    char* mm = (char*)(CALL_DIRECT_MMAP(mmsize));
    if (mm != CMFAIL) {
      size_t offset = align_offset(chunk2mem(mm));
      size_t psize = mmsize - offset - MMAP_FOOT_PAD;
      mchunkptr p = (mchunkptr)(mm + offset);
      p->prev_foot = offset;
      p->head = psize;
      mark_inuse_foot(m, p, psize);
      chunk_plus_offset(p, psize)->head = FENCEPOST_HEAD;
      chunk_plus_offset(p, psize+SIZE_T_SIZE)->head = 0;
      if (m->least_addr == 0 || mm < m->least_addr)
        m->least_addr = mm;
      if ((m->footprint += mmsize) > m->max_footprint)
        m->max_footprint = m->footprint;
      assert(is_aligned(chunk2mem(p)));
      check_mmapped_chunk(m, p);
      return chunk2mem(p);
    }
  }
  return 0;
}
References align_offset, assert, CALL_DIRECT_MMAP, check_mmapped_chunk, chunk2mem, CHUNK_ALIGN_MASK, chunk_plus_offset, CMFAIL, FENCEPOST_HEAD, malloc_state::footprint, malloc_state::footprint_limit, malloc_chunk::head, is_aligned, malloc_state::least_addr, mark_inuse_foot, malloc_state::max_footprint, mmap_align, MMAP_FOOT_PAD, malloc_chunk::prev_foot, SIX_SIZE_T_SIZES, and SIZE_T_SIZE.
Referenced by sys_alloc().
mmap_resize()
mchunkptr mmap_resize (mstate m, mchunkptr oldp, size_t nb, int flags) static
{
  size_t oldsize = chunksize(oldp);
  (void)flags; /* placate people compiling -Wunused */
  if (is_small(nb)) /* Can't shrink mmap regions below small size */
    return 0;
  /* Keep old chunk if big enough but not too big */
  if (oldsize >= nb + SIZE_T_SIZE &&
      (oldsize - nb) <= (mparams.granularity << 1))
    return oldp;
  else {
    size_t offset = oldp->prev_foot;
    size_t oldmmsize = oldsize + offset + MMAP_FOOT_PAD;
    size_t newmmsize = mmap_align(nb + SIX_SIZE_T_SIZES + CHUNK_ALIGN_MASK);
    char* cp = (char*)CALL_MREMAP((char*)oldp - offset,
                                  oldmmsize, newmmsize, flags);
    if (cp != CMFAIL) {
      mchunkptr newp = (mchunkptr)(cp + offset);
      size_t psize = newmmsize - offset - MMAP_FOOT_PAD;
      newp->head = psize;
      mark_inuse_foot(m, newp, psize);
      chunk_plus_offset(newp, psize)->head = FENCEPOST_HEAD;
      chunk_plus_offset(newp, psize+SIZE_T_SIZE)->head = 0;
      if (cp < m->least_addr)
        m->least_addr = cp;
      if ((m->footprint += newmmsize - oldmmsize) > m->max_footprint)
        m->max_footprint = m->footprint;
      check_mmapped_chunk(m, newp);
      return newp;
    }
  }
  return 0;
}
References CALL_MREMAP, check_mmapped_chunk, CHUNK_ALIGN_MASK, chunk_plus_offset, chunksize, CMFAIL, cp, FENCEPOST_HEAD, malloc_state::footprint, malloc_chunk::head, is_small, malloc_state::least_addr, mark_inuse_foot, malloc_state::max_footprint, mmap_align, MMAP_FOOT_PAD, mparams, malloc_chunk::prev_foot, SIX_SIZE_T_SIZES, SIZE_T_SIZE, and void().
Referenced by try_realloc_chunk().
prepend_alloc()
void * prepend_alloc (mstate m, char * newbase, char * oldbase, size_t nb) static
{
  mchunkptr p = align_as_chunk(newbase);
  mchunkptr oldfirst = align_as_chunk(oldbase);
  size_t psize = (char*)oldfirst - (char*)p;
  mchunkptr q = chunk_plus_offset(p, nb);
  size_t qsize = psize - nb;
  set_size_and_pinuse_of_inuse_chunk(m, p, nb);
  assert((char*)oldfirst > (char*)q);
  assert(pinuse(oldfirst));
  assert(qsize >= MIN_CHUNK_SIZE);
  /* consolidate remainder with first chunk of old base */
  if (oldfirst == m->top) {
    size_t tsize = m->topsize += qsize;
    m->top = q;
    q->head = tsize | PINUSE_BIT;
    check_top_chunk(m, q);
  }
  else if (oldfirst == m->dv) {
    size_t dsize = m->dvsize += qsize;
    m->dv = q;
    set_size_and_pinuse_of_free_chunk(q, dsize);
  }
  else {
    if (!is_inuse(oldfirst)) {
      size_t nsize = chunksize(oldfirst);
      unlink_chunk(m, oldfirst, nsize);
      oldfirst = chunk_plus_offset(oldfirst, nsize);
      qsize += nsize;
    }
    set_free_with_pinuse(q, qsize, oldfirst);
    insert_chunk(m, q, qsize);
    check_free_chunk(m, q);
  }
  check_malloced_chunk(m, chunk2mem(p), nb);
  return chunk2mem(p);
}
References align_as_chunk, assert, check_free_chunk, check_malloced_chunk, check_top_chunk, chunk2mem, chunk_plus_offset, chunksize, malloc_state::dv, malloc_state::dvsize, malloc_chunk::head, insert_chunk, is_inuse, MIN_CHUNK_SIZE, pinuse, PINUSE_BIT, set_free_with_pinuse, set_size_and_pinuse_of_free_chunk, set_size_and_pinuse_of_inuse_chunk, malloc_state::top, malloc_state::topsize, and unlink_chunk.
Referenced by sys_alloc().
pthread_init_lock()
int pthread_init_lock (pthread_mutex_t * lk) static
{
  pthread_mutexattr_t attr;
  if (pthread_mutexattr_init(&attr)) return 1;
#if defined(USE_RECURSIVE_LOCKS) && USE_RECURSIVE_LOCKS != 0
  if (pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE)) return 1;
#endif
  if (pthread_mutex_init(lk, &attr)) return 1;
  if (pthread_mutexattr_destroy(&attr)) return 1;
  return 0;
}
References MLOCK_T.
release_unused_segments()
size_t release_unused_segments (mstate m) static
{
  size_t released = 0;
  int nsegs = 0;
  msegmentptr pred = &m->seg;
  msegmentptr sp = pred->next;
  while (sp != 0) {
    char* base = sp->base;
    size_t size = sp->size;
    msegmentptr next = sp->next;
    ++nsegs;
    if (is_mmapped_segment(sp) && !is_extern_segment(sp)) {
      mchunkptr p = align_as_chunk(base);
      size_t psize = chunksize(p);
      /* Can unmap if first chunk holds entire segment and not pinned */
      if (!is_inuse(p) && (char*)p + psize >= base + size - TOP_FOOT_SIZE) {
        tchunkptr tp = (tchunkptr)p;
        assert(segment_holds(sp, (char*)sp));
        if (p == m->dv) {
          m->dv = 0;
          m->dvsize = 0;
        }
        else {
          unlink_large_chunk(m, tp);
        }
        if (CALL_MUNMAP(base, size) == 0) {
          released += size;
          m->footprint -= size;
          /* unlink obsoleted record */
          sp = pred;
          sp->next = next;
        }
        else { /* back out if cannot unmap */
          insert_large_chunk(m, tp, psize);
        }
      }
    }
    if (NO_SEGMENT_TRAVERSAL) /* scan only first segment */
      break;
    pred = sp;
    sp = next;
  }
  /* Reset check counter */
  m->release_checks = (((size_t) nsegs > (size_t) MAX_RELEASE_CHECK_RATE)?
                       (size_t) nsegs : (size_t) MAX_RELEASE_CHECK_RATE);
  return released;
}
References align_as_chunk, assert, malloc_segment::base, CALL_MUNMAP, chunksize, malloc_state::dv, malloc_state::dvsize, malloc_state::footprint, insert_large_chunk, is_extern_segment, is_inuse, is_mmapped_segment, MAX_RELEASE_CHECK_RATE, malloc_segment::next, NO_SEGMENT_TRAVERSAL, malloc_state::release_checks, malloc_state::seg, segment_holds, malloc_segment::size, TOP_FOOT_SIZE, and unlink_large_chunk.
Referenced by dlfree(), and sys_trim().
SDL_calloc()
void * SDL_calloc (size_t nmemb, size_t size)
{
    void *mem;
    if (!nmemb || !size) {
        nmemb = 1;
        size = 1;
    }
    mem = s_mem.calloc_func(nmemb, size);
    if (mem) {
        INCREMENT_ALLOCATION_COUNT();
    } else {
        SDL_OutOfMemory();
    }
    return mem;
}
References INCREMENT_ALLOCATION_COUNT, s_mem, and SDL_OutOfMemory().
Referenced by AllocateRenderCommand(), build_locales_from_csv_string(), create_zenity_args(), createDevice(), CreatePhysicalAudioDevice(), createWindow(), decode_edid(), DUMMYAUDIO_OpenDevice(), IMA_ADPCM_Decode(), Map1to1(), Map1toN(), MS_ADPCM_Decode(), PS2AUDIO_OpenDevice(), PushMappingChangeTracking(), RequestAsyncIO(), resize(), SDL_AddCamera(), SDL_ALLOC_SIZE2(), SDL_AsyncIOFromFile(), SDL_CloseAsyncIO(), SDL_CreateAsyncIOQueue(), SDL_CreateAudioQueue(), SDL_CreateAudioStream(), SDL_CreateColorCursor(), SDL_CreateCondition(), SDL_CreateCondition_cv(), SDL_CreateEnvironment(), SDL_CreateGPURenderState(), SDL_CreateHashTable(), SDL_CreateKeymap(), SDL_CreateMutex(), SDL_CreateProcessWithProperties(), SDL_CreateProperties(), SDL_CreateRendererWithProperties(), SDL_CreateRWLock(), SDL_CreateRWLock_srw(), SDL_CreateTextureWithProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateTray(), SDL_CreateTrayMenu(), SDL_CreateTraySubmenu(), SDL_CreateWindowTexture(), SDL_CreateWindowWithProperties(), SDL_GetGamepadMappings(), SDL_GetTemporaryMemoryState(), SDL_InsertTrayEntryAt(), SDL_IOFromConstMem(), SDL_IOFromDynamicMem(), SDL_IOFromFD(), SDL_IOFromMem(), SDL_OpenAudioDevice(), SDL_OpenGamepad(), SDL_OpenHaptic(), SDL_OpenHapticFromJoystick(), SDL_OpenIO(), SDL_OpenJoystick(), SDL_OpenSensor(), SDL_OpenStorage(), SDL_PrivateJoystickAddTouchpad(), SDL_SetBooleanProperty(), SDL_SetEventEnabled(), SDL_SetFloatProperty(), SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_SetPointerPropertyWithCleanup(), SDL_SetStringProperty(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), SDL_WSCONS_Init_Keyboard(), and SDL_WSCONS_Init_Mouse().
SDL_free()
void SDL_free (void * mem)
Free allocated memory.
The pointer is no longer valid after this call and cannot be dereferenced anymore.
If mem is NULL, this function does nothing.
Parameters
mem a pointer to allocated memory, or NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_malloc
SDL_calloc
SDL_realloc
{
    if (!ptr) {
        return;
    }
    s_mem.free_func(ptr);
    DECREMENT_ALLOCATION_COUNT();
}
References DECREMENT_ALLOCATION_COUNT, and s_mem.
Referenced by AttemptSensorFusion(), CleanupFreeableProperty(), CleanupHintProperty(), CleanupLogPrefixes(), CleanupLogPriorities(), convert_ext_list(), convert_filter(), convert_filters(), CopyOneProperty(), create_zenity_args(), CreatePhysicalAudioDevice(), createWindow(), DBus_MessageFilter(), decode_edid(), deleteDevice(), DeleteHIDDeviceWrapper(), DestroyCameraHashItem(), DestroyLogicalAudioDevice(), DestroyMemoryPool(), DestroyPhysicalAudioDevice(), DestroySDLMenu(), DUMMYAUDIO_CloseDevice(), dynamic_mem_close(), escape_label(), FcitxClientCreateIC(), fd_close(), free_zenity_args(), FreeAllocatedAudioBuffer(), FreeMemoryPoolBlock(), freeWinArgs(), freeWinFArgs(), generic_asyncio_destroy(), generic_asyncioqueue_destroy(), GENERIC_CloseStorage(), GENERIC_CopyStorageFile(), GENERIC_CreateStorageDirectory(), GENERIC_EnumerateDirectory(), GENERIC_EnumerateStorageDirectory(), GENERIC_GetStoragePathInfo(), GENERIC_OpenFileStorage(), GENERIC_ReadStorageFile(), GENERIC_RemoveStoragePath(), GENERIC_RenameStoragePath(), GENERIC_Title_Create(), GENERIC_User_Create(), GENERIC_WriteStorageFile(), GetAsyncIOTaskOutcome(), GetFileModificationTime(), glGetConfig(), GlobDirectoryCallback(), IgnoredDevicesChanged(), IMA_ADPCM_Decode(), IOS_RemoveJoystickDevice(), IsROGAlly(), LAW_Decode(), mem_close(), MS_ADPCM_Decode(), PopMappingChangeTracking(), PS2AUDIO_CloseDevice(), register_string_error_to_buffer(), register_winapi_error_to_buffer(), RequestAsyncIO(), ResetHintsCallback(), resize(), run_zenity(), RunInputThread(), SDL_AddCamera(), SDL_AddFullscreenDisplayMode(), SDL_AddGamepadMappingsFromIO(), SDL_AddHintCallback(), SDL_AddPenDevice(), SDL_AddVideoDisplay(), SDL_aligned_free(), SDL_ALLOC_SIZE(), SDL_AsyncIOFromFile(), SDL_CameraInit(), SDL_CleanupTemporaryMemory(), SDL_CleanupTLS(), SDL_CleanupTrays(), SDL_CleanupWindowTextureData(), SDL_CloseAsyncIO(), SDL_CloseGamepad(), SDL_CloseHaptic(), SDL_CloseIO(), SDL_CloseJoystick(), SDL_CloseSensor(), SDL_CloseStorage(), SDL_ConvertAudioSamples(), SDL_CreateAsyncIOQueue(), SDL_CreateAudioStream(), SDL_CreateCondition(), SDL_CreateDirectory(), SDL_CreateEnvironment(), SDL_CreateMainThreadCallback(), SDL_CreateMutex(), SDL_CreatePalette(), SDL_CreateProperties(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateTimer(), SDL_CreateTray(), SDL_CreateWindowTexture(), SDL_DelTouch(), SDL_DelVideoDisplay(), SDL_DestroyAsyncIOQueue(), SDL_DestroyAudioQueue(), SDL_DestroyAudioStream(), SDL_DestroyCondition(), SDL_DestroyCondition_cv(), SDL_DestroyCursor(), SDL_DestroyEnvironment(), SDL_DestroyGPURenderState(), SDL_DestroyHashKey(), SDL_DestroyHashKeyAndValue(), SDL_DestroyHashTable(), SDL_DestroyHashValue(), SDL_DestroyKeymap(), SDL_DestroyMainThreadCallback(), SDL_DestroyMutex(), SDL_DestroyPalette(), SDL_DestroyProcess(), SDL_DestroyRenderer(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroyRWLock(), SDL_DestroyRWLock_srw(), SDL_DestroySemaphore(), SDL_DestroySurface(), SDL_DestroyTextureInternal(), SDL_DestroyTray(), SDL_DestroyWindow(), SDL_DiscardAllCommands(), SDL_Fcitx_Quit(), SDL_FreeClipboardMimeTypes(), SDL_FreeProperties(), SDL_FreePropertyWithCleanup(), SDL_FreeSteamVirtualGamepadInfo(), SDL_FreeTemporaryMemoryEntry(), SDL_FreeVIDPIDList(), SDL_Generic_QuitTLSData(), SDL_Generic_SetTLSData(), SDL_GetClipboardData(), SDL_GetGamepadMappings(), SDL_GetPixelFormatDetails(), SDL_GetSurfaceImage(), SDL_GetTemporaryMemoryState(), SDL_Haptic_Get_Naxes(), SDL_HasGamepad(), SDL_hid_exit(), SDL_hid_free_enumeration(), SDL_iconv_close(), SDL_iconv_string(), SDL_InitAudio(), SDL_InitGamepads(), SDL_InsertTrayEntryAt(), SDL_InternalGlobDirectory(), SDL_InvalidateMap(), SDL_IOFromConstMem(), SDL_IOFromDynamicMem(), SDL_IOFromFile(), SDL_IOFromMem(), SDL_IOprintf(), SDL_IOvprintf(), SDL_ListClear(), SDL_ListPop(), SDL_ListRemove(), SDL_LoadFile_IO(), SDL_LoadFileAsync(), SDL_LoadGamepadHints(), SDL_LoadVIDPIDListFromHint(), SDL_LoadWAV_IO(), SDL_LogMessageV(), SDL_LogOutput(), SDL_OpenAudioDevice(), SDL_OpenGamepad(), SDL_OpenHaptic(), SDL_OpenHapticFromJoystick(), SDL_OpenJoystick(), SDL_OpenSensor(), SDL_PrintStringW(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateParseGamepadElement(), SDL_PromptAssertion(), SDL_PutAudioStreamData(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitEventWatchList(), SDL_QuitFilesystem(), SDL_QuitGamepadMappings(), SDL_QuitJoysticks(), SDL_QuitKeyboard(), SDL_QuitMouse(), SDL_QuitPen(), SDL_QuitSteamVirtualGamepadInfo(), SDL_QuitTimers(), SDL_QuitTouch(), SDL_RemoveAllPenDevices(), SDL_RemoveHintCallback(), SDL_RemoveKeyboard(), SDL_RemoveMouse(), SDL_RemovePenDevice(), SDL_RemoveSurfaceAlternateImages(), SDL_RemoveTimer(), SDL_RemoveTrayEntry(), SDL_RenderDebugTextFormat(), SDL_ResetFullscreenDisplayModes(), SDL_ResetHint(), SDL_RunThread(), SDL_SetAudioStreamFormat(), SDL_SetClipboardData(), SDL_SetClipboardText(), SDL_SetDefaultCursor(), SDL_SetDesktopDisplayMode(), SDL_setenv_unsafe(), SDL_SetEnvironmentVariable(), SDL_SetGPURenderStateFragmentUniforms(), SDL_SetHintWithPriority(), SDL_SetLogPriorityPrefix(), SDL_SetPrimarySelectionText(), SDL_SetStringProperty(), SDL_SetTLS(), SDL_SetTrayEntryLabel(), SDL_SetTrayTooltip(), SDL_SetWindowTitle(), SDL_StopEventLoop(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), SDL_SYS_GetBasePath(), SDL_SYS_GetPrefPath(), SDL_SYS_OpenURL(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UnregisterTray(), SDL_UpdateAudio(), SDL_UpdateCamera(), SDL_UpdateDesktopBounds(), SDL_UpdateSteamVirtualGamepadInfo(), SDL_UpdateTextureNative(), SDL_vasprintf(), SDL_VideoQuit(), SDL_vswprintf(), SDL_WaitThread(), SDL_WSCONS_Init_Keyboard(), SDL_WSCONS_Init_Mouse(), SDL_WSCONS_Quit(), SDL_WSCONS_Quit_Mouse(), SetAudioStreamChannelMap(), ShowFileDialog(), STEAM_CloseStorage(), STEAM_User_Create(), TryOpenInRomfs(), WaveFreeChunkData(), win_get_filters(), windows_ShowFileDialog(), and windows_ShowFolderDialog().
SDL_GetMemoryFunctions()
void SDL_GetMemoryFunctions (SDL_malloc_func * malloc_func, SDL_calloc_func * calloc_func, SDL_realloc_func * realloc_func, SDL_free_func * free_func)
Get the current set of SDL memory functions.
Parameters
malloc_func filled with malloc function.
calloc_func filled with calloc function.
realloc_func filled with realloc function.
free_func filled with free function.
Thread Safety
This does not hold a lock, so do not call this in the unlikely event of a background thread calling SDL_SetMemoryFunctions simultaneously.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetMemoryFunctions
SDL_GetOriginalMemoryFunctions
{
    if (malloc_func) {
        *malloc_func = s_mem.malloc_func;
    }
    if (calloc_func) {
        *calloc_func = s_mem.calloc_func;
    }
    if (realloc_func) {
        *realloc_func = s_mem.realloc_func;
    }
    if (free_func) {
        *free_func = s_mem.free_func;
    }
}
References calloc_func, free_func, malloc_func, realloc_func, and s_mem.
SDL_GetNumAllocations()
int SDL_GetNumAllocations (void)
Get the number of outstanding (unfreed) allocations.
Returns
the number of allocations or -1 if allocation counting is disabled.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_TRACK_ALLOCATION_COUNT
    return SDL_GetAtomicInt(&s_mem.num_allocations);
#else
    return -1;
#endif
}
References s_mem, and SDL_GetAtomicInt().
SDL_GetOriginalMemoryFunctions()
void SDL_GetOriginalMemoryFunctions (SDL_malloc_func * malloc_func, SDL_calloc_func * calloc_func, SDL_realloc_func * realloc_func, SDL_free_func * free_func)
Get the original set of SDL memory functions.
This is what SDL_malloc and friends will use by default, if there has been no call to SDL_SetMemoryFunctions. This is not necessarily using the C runtime's malloc functions behind the scenes! Different platforms and build configurations might do any number of unexpected things.
Parameters
malloc_func filled with malloc function.
calloc_func filled with calloc function.
realloc_func filled with realloc function.
free_func filled with free function.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (malloc_func) {
        *malloc_func = real_malloc;
    }
    if (calloc_func) {
        *calloc_func = real_calloc;
    }
    if (realloc_func) {
        *realloc_func = real_realloc;
    }
    if (free_func) {
        *free_func = real_free;
    }
}
References calloc_func, free_func, malloc_func, real_calloc, real_free, real_malloc, real_realloc, and realloc_func.
Referenced by SDL_GetErrBuf().
SDL_malloc()
void * SDL_malloc (size_t size)
Allocate uninitialized memory.
The allocated memory returned by this function must be freed with SDL_free().
If size is 0, it will be set to 1.
If the allocation is successful, the returned pointer is guaranteed to be aligned to either the fundamental alignment (alignof(max_align_t) in C11 and later) or 2 * sizeof(void *), whichever is smaller. Use SDL_aligned_alloc() if you need to allocate memory aligned to an alignment greater than this guarantee.
Parameters
size the size to allocate.
Returns
a pointer to the allocated memory, or NULL if allocation failed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_free
SDL_calloc
SDL_realloc
SDL_aligned_alloc
{
    void *mem;
    if (!size) {
        size = 1;
    }
    mem = s_mem.malloc_func(size);
    if (mem) {
        INCREMENT_ALLOCATION_COUNT();
    } else {
        SDL_OutOfMemory();
    }
    return mem;
}
References INCREMENT_ALLOCATION_COUNT, s_mem, and SDL_OutOfMemory().
Referenced by AddDeviceToEnumeration(), AddVirtualGamepadInfo(), AllocNewMemoryPoolBlock(), CaseFoldUtf8String(), convert_ext_list(), convert_filter(), CopyOneProperty(), create_zenity_args(), CreateMappingString(), DUMMYAUDIO_OpenDevice(), escape_label(), Fcitx_GetPreeditString(), GetAudioDevices(), glGetConfig(), IMA_ADPCM_Decode(), MS_ADPCM_Init(), PushMappingChangeTracking(), run_zenity(), SDL_AddAudioDevice(), SDL_AddCamera(), SDL_AddEvent(), SDL_AddFinger(), SDL_AddFullscreenDisplayMode(), SDL_AddHintCallback(), SDL_AddTouch(), SDL_AddVideoDisplay(), SDL_aligned_alloc(), SDL_AllocateTemporaryMemory(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CameraDisconnected(), SDL_CameraPermissionOutcome(), SDL_ChannelMapDup(), SDL_CleanupTrays(), SDL_ConvertAudioSamples(), SDL_ConvertMappingToPositionalAXBY(), SDL_ConvertMappingToPositionalBAXY(), SDL_ConvertSurfaceAndColorspace(), SDL_CopyClipboardMimeTypes(), SDL_CreateCondition(), SDL_CreateDeviceName(), SDL_CreateMainThreadCallback(), SDL_CreatePalette(), SDL_CreateSemaphore(), SDL_CreateSurface(), SDL_CreateSurfaceFrom(), SDL_CreateTimer(), SDL_CreateWindowTexture(), SDL_DefaultAudioDeviceChanged(), SDL_FreeLater(), SDL_Generic_SetTLSData(), SDL_GetCameras(), SDL_GetCameraSupportedFormats(), SDL_GetDisplays(), SDL_GetEnvironmentVariables(), SDL_GetFullscreenDisplayModes(), SDL_GetGamepadBindings(), SDL_GetGamepadMappings(), SDL_GetHaptics(), SDL_GetInternalClipboardData(), SDL_GetJoysticks(), SDL_GetKeyboards(), SDL_GetMice(), SDL_GetPixelFormatDetails(), SDL_GetSensors(), SDL_GetSurfaceImages(), SDL_GetTouchDevices(), SDL_GetTouchFingers(), SDL_GetWindows(), SDL_iconv_open(), SDL_iconv_string(), SDL_InternalGlobDirectory(), SDL_ListAdd(), SDL_LoadFile_IO(), SDL_LoadFileAsync(), SDL_LoadVIDPIDListFromHints(), SDL_LogMessageV(), SDL_PrivateAddMappingForGUID(), SDL_PrivateGetGamepadGUIDFromMappingString(), SDL_PrivateGetGamepadNameFromMappingString(), SDL_PromptAssertion(), SDL_PutAudioStreamData(), SDL_PutAudioStreamPlanarData(), SDL_SaveClipboardMimeTypes(), SDL_SetClipboardData(), SDL_setenv_unsafe(), SDL_SetGPURenderStateFragmentUniforms(), SDL_SetHintWithPriority(), SDL_SetLogPriority(), SDL_strdup(), SDL_strndup(), SDL_SYS_GetPrefPath(), SDL_UpdateTextureNative(), SDL_vasprintf(), SDL_wcsdup(), ShowFileDialog(), ShowFolderDialog(), STEAM_User_Create(), WaveReadPartialChunkData(), win_get_filters(), and windows_ShowFileDialog().
SDL_realloc()
void * SDL_realloc (void * ptr, size_t size)
{
    void *mem;
    if (!size) {
        size = 1;
    }
    mem = s_mem.realloc_func(ptr, size);
    if (mem && !ptr) {
        INCREMENT_ALLOCATION_COUNT();
    } else if (!mem) {
        SDL_OutOfMemory();
    }
    return mem;
}
References INCREMENT_ALLOCATION_COUNT, s_mem, and SDL_OutOfMemory().
Referenced by AddMappingChangeTracking(), AddVirtualGamepadInfo(), CaseFoldUtf8String(), convert_filters(), dynamic_mem_realloc(), GetMouseClickState(), GetMouseInputSource(), LAW_Decode(), PCM_ConvertSint24ToSint32(), run_zenity(), SDL_AddCameraFormat(), SDL_AddEventWatchList(), SDL_AddFinger(), SDL_AddKeyboard(), SDL_AddMouse(), SDL_AddPenDevice(), SDL_AddSupportedTextureFormat(), SDL_AddSurfaceAlternateImage(), SDL_AddTouch(), SDL_AddVideoDisplay(), SDL_AddWindowRenderer(), SDL_ALLOC_SIZE(), SDL_AllocateRenderVertices(), SDL_Haptic_Load_Axes_List(), SDL_iconv_string(), SDL_InsertTrayEntryAt(), SDL_LoadFile_IO(), SDL_LoadVIDPIDListFromHint(), SDL_PrivateJoystickAddSensor(), SDL_PrivateJoystickAddTouchpad(), SDL_PrivateParseGamepadElement(), SDL_RemovePenDevice(), SDL_RemoveTrayEntry(), SDL_setenv_unsafe(), SDL_SetGPURenderStateFragmentUniforms(), SDL_SetJoystickIDForPlayerIndex(), SDL_SetTLS(), SDL_SYS_GetBasePath(), SDL_vasprintf(), and windows_ShowFileDialog().
SDL_SetMemoryFunctions()
bool SDL_SetMemoryFunctions (SDL_malloc_func malloc_func, SDL_calloc_func calloc_func, SDL_realloc_func realloc_func, SDL_free_func free_func)
Replace SDL's memory allocation functions with a custom set.
It is not safe to call this function once any allocations have been made, as future calls to SDL_free will use the new allocator, even if they came from an SDL_malloc made with the old one!
If used, usually this needs to be the first call made into the SDL library, if not the very first thing done at program startup time.
Parameters
malloc_func custom malloc function.
calloc_func custom calloc function.
realloc_func custom realloc function.
free_func custom free function.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but one should not replace the memory functions once any allocations are made!
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMemoryFunctions
SDL_GetOriginalMemoryFunctions
{
    if (!malloc_func) {
        return SDL_InvalidParamError("malloc_func");
    }
    if (!calloc_func) {
        return SDL_InvalidParamError("calloc_func");
    }
    if (!realloc_func) {
        return SDL_InvalidParamError("realloc_func");
    }
    if (!free_func) {
        return SDL_InvalidParamError("free_func");
    }
    s_mem.malloc_func = malloc_func;
    s_mem.calloc_func = calloc_func;
    s_mem.realloc_func = realloc_func;
    s_mem.free_func = free_func;
    return true;
}
References calloc_func, free_func, malloc_func, realloc_func, s_mem, and SDL_InvalidParamError.
segment_holding()
msegmentptr segment_holding (mstate m, char * addr) static
{
  msegmentptr sp = &m->seg;
  for (;;) {
    if (addr >= sp->base && addr < sp->base + sp->size)
      return sp;
    if ((sp = sp->next) == 0)
      return 0;
  }
}
References malloc_segment::base, malloc_segment::next, malloc_state::seg, and malloc_segment::size.
Referenced by add_segment(), sys_alloc(), and sys_trim().
sys_alloc()
void * sys_alloc (mstate m, size_t nb) static
{
  char* tbase = CMFAIL;
  size_t tsize = 0;
  flag_t mmap_flag = 0;
  size_t asize; /* allocation size */
  ensure_initialization();
  /* Directly map large chunks, but only if already initialized */
  if (use_mmap(m) && nb >= mparams.mmap_threshold && m->topsize != 0) {
    void* mem = mmap_alloc(m, nb);
    if (mem != 0)
      return mem;
  }
  asize = granularity_align(nb + SYS_ALLOC_PADDING);
  if (asize <= nb)
    return 0; /* wraparound */
  if (m->footprint_limit != 0) {
    size_t fp = m->footprint + asize;
    if (fp <= m->footprint || fp > m->footprint_limit)
      return 0;
  }
  /*
    Try getting memory in any of three ways (in most-preferred to
    least-preferred order):
    1. A call to MORECORE that can normally contiguously extend memory.
       (disabled if not MORECORE_CONTIGUOUS or not HAVE_MORECORE or
       or main space is mmapped or a previous contiguous call failed)
    2. A call to MMAP new space (disabled if not HAVE_MMAP).
       Note that under the default settings, if MORECORE is unable to
       fulfill a request, and HAVE_MMAP is true, then mmap is
       used as a noncontiguous system allocator. This is a useful backup
       strategy for systems with holes in address spaces -- in this case
       sbrk cannot contiguously expand the heap, but mmap may be able to
       find space.
    3. A call to MORECORE that cannot usually contiguously extend memory.
       (disabled if not HAVE_MORECORE)
   In all cases, we need to request enough bytes from system to ensure
   we can malloc nb bytes upon success, so pad with enough space for
   top_foot, plus alignment-pad to make sure we don't lose bytes if
   not on boundary, and round this up to a granularity unit.
  */
  if (MORECORE_CONTIGUOUS && !use_noncontiguous(m)) {
    char* br = CMFAIL;
    size_t ssize = asize; /* sbrk call size */
    msegmentptr ss = (m->top == 0)? 0 : segment_holding(m, (char*)m->top);
    ACQUIRE_MALLOC_GLOBAL_LOCK();
    if (ss == 0) {  /* First time through or recovery */
      char* base = (char*)CALL_MORECORE(0);
      if (base != CMFAIL) {
        size_t fp;
        /* Adjust to end on a page boundary */
        if (!is_page_aligned(base))
          ssize += (page_align((size_t)base) - (size_t)base);
        fp = m->footprint + ssize; /* recheck limits */
        if (ssize > nb && ssize < HALF_MAX_SIZE_T &&
            (m->footprint_limit == 0 ||
             (fp > m->footprint && fp <= m->footprint_limit)) &&
            (br = (char*)(CALL_MORECORE(ssize))) == base) {
          tbase = base;
          tsize = ssize;
        }
      }
    }
    else {
      /* Subtract out existing available top space from MORECORE request. */
      ssize = granularity_align(nb - m->topsize + SYS_ALLOC_PADDING);
      /* Use mem here only if it did continuously extend old space */
      if (ssize < HALF_MAX_SIZE_T &&
          (br = (char*)(CALL_MORECORE(ssize))) == ss->base+ss->size) {
        tbase = br;
        tsize = ssize;
      }
    }
    if (tbase == CMFAIL) {    /* Cope with partial failure */
      if (br != CMFAIL) {    /* Try to use/extend the space we did get */
        if (ssize < HALF_MAX_SIZE_T &&
            ssize < nb + SYS_ALLOC_PADDING) {
          size_t esize = granularity_align(nb + SYS_ALLOC_PADDING - ssize);
          if (esize < HALF_MAX_SIZE_T) {
            char* end = (char*)CALL_MORECORE(esize);
            if (end != CMFAIL)
              ssize += esize;
            else {            /* Can't use; try to release */
              (void) CALL_MORECORE(-ssize);
              br = CMFAIL;
            }
          }
        }
      }
      if (br != CMFAIL) {    /* Use the space we did get */
        tbase = br;
        tsize = ssize;
      }
      else
        disable_contiguous(m); /* Don't try contiguous path in the future */
    }
    RELEASE_MALLOC_GLOBAL_LOCK();
  }
  if (HAVE_MMAP && tbase == CMFAIL) {  /* Try MMAP */
    char* mp = (char*)(CALL_MMAP(asize));
    if (mp != CMFAIL) {
      tbase = mp;
      tsize = asize;
      mmap_flag = USE_MMAP_BIT;
    }
  }
  if (HAVE_MORECORE && tbase == CMFAIL) { /* Try noncontiguous MORECORE */
    if (asize < HALF_MAX_SIZE_T) {
      char* br = CMFAIL;
      char* end = CMFAIL;
      ACQUIRE_MALLOC_GLOBAL_LOCK();
      br = (char*)(CALL_MORECORE(asize));
      end = (char*)(CALL_MORECORE(0));
      RELEASE_MALLOC_GLOBAL_LOCK();
      if (br != CMFAIL && end != CMFAIL && br < end) {
        size_t ssize = end - br;
        if (ssize > nb + TOP_FOOT_SIZE) {
          tbase = br;
          tsize = ssize;
        }
      }
    }
  }
  if (tbase != CMFAIL) {
    if ((m->footprint += tsize) > m->max_footprint)
      m->max_footprint = m->footprint;
    if (!is_initialized(m)) { /* first-time initialization */
      if (m->least_addr == 0 || tbase < m->least_addr)
        m->least_addr = tbase;
      m->seg.base = tbase;
      m->seg.size = tsize;
      m->seg.sflags = mmap_flag;
      m->magic = mparams.magic;
      m->release_checks = MAX_RELEASE_CHECK_RATE;
      init_bins(m);
#if !ONLY_MSPACES
      if (is_global(m))
        init_top(m, (mchunkptr)tbase, tsize - TOP_FOOT_SIZE);
      else
#endif
      {
        /* Offset top by embedded malloc_state */
        mchunkptr mn = next_chunk(mem2chunk(m));
        init_top(m, mn, (size_t)((tbase + tsize) - (char*)mn) -TOP_FOOT_SIZE);
      }
    }
    else {
      /* Try to merge with an existing segment */
      msegmentptr sp = &m->seg;
      /* Only consider most recent segment if traversal suppressed */
      while (sp != 0 && tbase != sp->base + sp->size)
        sp = (NO_SEGMENT_TRAVERSAL) ? 0 : sp->next;
      if (sp != 0 &&
          !is_extern_segment(sp) &&
          (sp->sflags & USE_MMAP_BIT) == mmap_flag &&
          segment_holds(sp, m->top)) { /* append */
        sp->size += tsize;
        init_top(m, m->top, m->topsize + tsize);
      }
      else {
        if (tbase < m->least_addr)
          m->least_addr = tbase;
        sp = &m->seg;
        while (sp != 0 && sp->base != tbase + tsize)
          sp = (NO_SEGMENT_TRAVERSAL) ? 0 : sp->next;
        if (sp != 0 &&
            !is_extern_segment(sp) &&
            (sp->sflags & USE_MMAP_BIT) == mmap_flag) {
          char* oldbase = sp->base;
          sp->base = tbase;
          sp->size += tsize;
          return prepend_alloc(m, tbase, oldbase, nb);
        }
        else
          add_segment(m, tbase, tsize, mmap_flag);
      }
    }
    if (nb < m->topsize) { /* Allocate from new or extended top space */
      size_t rsize = m->topsize -= nb;
      mchunkptr p = m->top;
      mchunkptr r = m->top = chunk_plus_offset(p, nb);
      r->head = rsize | PINUSE_BIT;
      set_size_and_pinuse_of_inuse_chunk(m, p, nb);
      check_top_chunk(m, m->top);
      check_malloced_chunk(m, chunk2mem(p), nb);
      return chunk2mem(p);
    }
  }
  MALLOC_FAILURE_ACTION;
  return 0;
}
References ACQUIRE_MALLOC_GLOBAL_LOCK, add_segment(), malloc_segment::base, CALL_MMAP, CALL_MORECORE, check_malloced_chunk, check_top_chunk, chunk2mem, chunk_plus_offset, CMFAIL, disable_contiguous, ensure_initialization, malloc_state::footprint, malloc_state::footprint_limit, granularity_align, HALF_MAX_SIZE_T, HAVE_MMAP, HAVE_MORECORE, malloc_chunk::head, init_bins(), init_top(), is_extern_segment, is_global, is_initialized, is_page_aligned, malloc_state::least_addr, malloc_state::magic, MALLOC_FAILURE_ACTION, malloc_state::max_footprint, MAX_RELEASE_CHECK_RATE, mem2chunk, mmap_alloc(), MORECORE_CONTIGUOUS, mparams, malloc_segment::next, next_chunk, NO_SEGMENT_TRAVERSAL, page_align, PINUSE_BIT, prepend_alloc(), malloc_state::release_checks, RELEASE_MALLOC_GLOBAL_LOCK, malloc_state::seg, segment_holding(), segment_holds, set_size_and_pinuse_of_inuse_chunk, malloc_segment::sflags, malloc_segment::size, SYS_ALLOC_PADDING, malloc_state::top, TOP_FOOT_SIZE, malloc_state::topsize, use_mmap, USE_MMAP_BIT, use_noncontiguous, and void().
Referenced by dlmalloc().
sys_trim()
int sys_trim (mstate m, size_t pad) static
{
  size_t released = 0;
  ensure_initialization();
  if (pad < MAX_REQUEST && is_initialized(m)) {
    pad += TOP_FOOT_SIZE; /* ensure enough room for segment overhead */
    if (m->topsize > pad) {
      /* Shrink top space in granularity-size units, keeping at least one */
      size_t unit = mparams.granularity;
      size_t extra = ((m->topsize - pad + (unit - SIZE_T_ONE)) / unit -
                      SIZE_T_ONE) * unit;
      msegmentptr sp = segment_holding(m, (char*)m->top);
      if (!is_extern_segment(sp)) {
        if (is_mmapped_segment(sp)) {
          if (HAVE_MMAP &&
              sp->size >= extra &&
              !has_segment_link(m, sp)) { /* can't shrink if pinned */
            size_t newsize = sp->size - extra;
            (void)newsize; /* placate people compiling -Wunused-variable */
            /* Prefer mremap, fall back to munmap */
            if ((CALL_MREMAP(sp->base, sp->size, newsize, 0) != MFAIL) ||
                (CALL_MUNMAP(sp->base + newsize, extra) == 0)) {
              released = extra;
            }
          }
        }
        else if (HAVE_MORECORE) {
          if (extra >= HALF_MAX_SIZE_T) /* Avoid wrapping negative */
            extra = (HALF_MAX_SIZE_T) + SIZE_T_ONE - unit;
          ACQUIRE_MALLOC_GLOBAL_LOCK();
          {
            /* Make sure end of memory is where we last set it. */
            char* old_br = (char*)(CALL_MORECORE(0));
            if (old_br == sp->base + sp->size) {
              char* rel_br = (char*)(CALL_MORECORE(-extra));
              char* new_br = (char*)(CALL_MORECORE(0));
              if (rel_br != CMFAIL && new_br < old_br)
                released = old_br - new_br;
            }
          }
          RELEASE_MALLOC_GLOBAL_LOCK();
        }
      }
      if (released != 0) {
        sp->size -= released;
        m->footprint -= released;
        init_top(m, m->top, m->topsize - released);
        check_top_chunk(m, m->top);
      }
    }
    /* Unmap any unused mmapped segments */
    if (HAVE_MMAP)
      released += release_unused_segments(m);
    /* On failure, disable autotrim to avoid repeated failed future calls */
    if (released == 0 && m->topsize > m->trim_check)
      m->trim_check = MAX_SIZE_T;
  }
  return (released != 0)? 1 : 0;
}
References ACQUIRE_MALLOC_GLOBAL_LOCK, malloc_segment::base, CALL_MORECORE, CALL_MREMAP, CALL_MUNMAP, check_top_chunk, CMFAIL, ensure_initialization, malloc_state::footprint, HALF_MAX_SIZE_T, has_segment_link(), HAVE_MMAP, HAVE_MORECORE, init_top(), is_extern_segment, is_initialized, is_mmapped_segment, MAX_REQUEST, MAX_SIZE_T, MFAIL, mparams, RELEASE_MALLOC_GLOBAL_LOCK, release_unused_segments(), segment_holding(), malloc_segment::size, SIZE_T_ONE, malloc_state::top, TOP_FOOT_SIZE, malloc_state::topsize, malloc_state::trim_check, and void().
Referenced by dlfree(), dlmalloc_trim(), and internal_bulk_free().
tmalloc_large()
void * tmalloc_large (mstate m, size_t nb) static
{
  tchunkptr v = 0;
  size_t rsize = -nb; /* Unsigned negation */
  tchunkptr t;
  bindex_t idx;
  compute_tree_index(nb, idx);
  if ((t = *treebin_at(m, idx)) != 0) {
    /* Traverse tree for this bin looking for node with size == nb */
    size_t sizebits = nb << leftshift_for_tree_index(idx);
    tchunkptr rst = 0;  /* The deepest untaken right subtree */
    for (;;) {
      tchunkptr rt;
      size_t trem = chunksize(t) - nb;
      if (trem < rsize) {
        v = t;
        if ((rsize = trem) == 0)
          break;
      }
      rt = t->child[1];
      t = t->child[(sizebits >> (SIZE_T_BITSIZE-SIZE_T_ONE)) & 1];
      if (rt != 0 && rt != t)
        rst = rt;
      if (t == 0) {
        t = rst; /* set t to least subtree holding sizes > nb */
        break;
      }
      sizebits <<= 1;
    }
  }
  if (t == 0 && v == 0) { /* set t to root of next non-empty treebin */
    binmap_t leftbits = left_bits(idx2bit(idx)) & m->treemap;
    if (leftbits != 0) {
      bindex_t i;
      binmap_t leastbit = least_bit(leftbits);
      compute_bit2idx(leastbit, i);
      t = *treebin_at(m, i);
    }
  }
  while (t != 0) { /* find smallest of tree or subtree */
    size_t trem = chunksize(t) - nb;
    if (trem < rsize) {
      rsize = trem;
      v = t;
    }
    t = leftmost_child(t);
  }
  /*  If dv is a better fit, return 0 so malloc will use it */
  if (v != 0 && rsize < (size_t)(m->dvsize - nb)) {
    if (RTCHECK(ok_address(m, v))) { /* split */
      mchunkptr r = chunk_plus_offset(v, nb);
      assert(chunksize(v) == rsize + nb);
      if (RTCHECK(ok_next(v, r))) {
        unlink_large_chunk(m, v);
        if (rsize < MIN_CHUNK_SIZE)
          set_inuse_and_pinuse(m, v, (rsize + nb));
        else {
          set_size_and_pinuse_of_inuse_chunk(m, v, nb);
          set_size_and_pinuse_of_free_chunk(r, rsize);
          insert_chunk(m, r, rsize);
        }
        return chunk2mem(v);
      }
    }
    CORRUPTION_ERROR_ACTION(m);
  }
  return 0;
}
References assert, malloc_tree_chunk::child, chunk2mem, chunk_plus_offset, chunksize, compute_bit2idx, compute_tree_index, CORRUPTION_ERROR_ACTION, malloc_state::dvsize, idx2bit, insert_chunk, least_bit, left_bits, leftmost_child, leftshift_for_tree_index, MIN_CHUNK_SIZE, ok_address, ok_next, RTCHECK, set_inuse_and_pinuse, set_size_and_pinuse_of_free_chunk, set_size_and_pinuse_of_inuse_chunk, SIZE_T_BITSIZE, SIZE_T_ONE, treebin_at, malloc_state::treemap, and unlink_large_chunk.
Referenced by dlmalloc().
tmalloc_small()
void * tmalloc_small (mstate m, size_t nb) static
{
  tchunkptr t, v;
  size_t rsize;
  bindex_t i;
  binmap_t leastbit = least_bit(m->treemap);
  compute_bit2idx(leastbit, i);
  v = t = *treebin_at(m, i);
  rsize = chunksize(t) - nb;
  while ((t = leftmost_child(t)) != 0) {
    size_t trem = chunksize(t) - nb;
    if (trem < rsize) {
      rsize = trem;
      v = t;
    }
  }
  if (RTCHECK(ok_address(m, v))) {
    mchunkptr r = chunk_plus_offset(v, nb);
    assert(chunksize(v) == rsize + nb);
    if (RTCHECK(ok_next(v, r))) {
      unlink_large_chunk(m, v);
      if (rsize < MIN_CHUNK_SIZE)
        set_inuse_and_pinuse(m, v, (rsize + nb));
      else {
        set_size_and_pinuse_of_inuse_chunk(m, v, nb);
        set_size_and_pinuse_of_free_chunk(r, rsize);
        replace_dv(m, r, rsize);
      }
      return chunk2mem(v);
    }
  }
  CORRUPTION_ERROR_ACTION(m);
  return 0;
}
References assert, chunk2mem, chunk_plus_offset, chunksize, compute_bit2idx, CORRUPTION_ERROR_ACTION, least_bit, leftmost_child, MIN_CHUNK_SIZE, ok_address, ok_next, replace_dv, RTCHECK, set_inuse_and_pinuse, set_size_and_pinuse_of_free_chunk, set_size_and_pinuse_of_inuse_chunk, treebin_at, malloc_state::treemap, and unlink_large_chunk.
Referenced by dlmalloc().
try_realloc_chunk()
mchunkptr try_realloc_chunk (mstate m, mchunkptr p, size_t nb, int can_move) static
{
  mchunkptr newp = 0;
  size_t oldsize = chunksize(p);
  mchunkptr next = chunk_plus_offset(p, oldsize);
  if (RTCHECK(ok_address(m, p) && ok_inuse(p) &&
              ok_next(p, next) && ok_pinuse(next))) {
    if (is_mmapped(p)) {
      newp = mmap_resize(m, p, nb, can_move);
    }
    else if (oldsize >= nb) {             /* already big enough */
      size_t rsize = oldsize - nb;
      if (rsize >= MIN_CHUNK_SIZE) {      /* split off remainder */
        mchunkptr r = chunk_plus_offset(p, nb);
        set_inuse(m, p, nb);
        set_inuse(m, r, rsize);
        dispose_chunk(m, r, rsize);
      }
      newp = p;
    }
    else if (next == m->top) {  /* extend into top */
      if (oldsize + m->topsize > nb) {
        size_t newsize = oldsize + m->topsize;
        size_t newtopsize = newsize - nb;
        mchunkptr newtop = chunk_plus_offset(p, nb);
        set_inuse(m, p, nb);
        newtop->head = newtopsize |PINUSE_BIT;
        m->top = newtop;
        m->topsize = newtopsize;
        newp = p;
      }
    }
    else if (next == m->dv) { /* extend into dv */
      size_t dvs = m->dvsize;
      if (oldsize + dvs >= nb) {
        size_t dsize = oldsize + dvs - nb;
        if (dsize >= MIN_CHUNK_SIZE) {
          mchunkptr r = chunk_plus_offset(p, nb);
          mchunkptr n = chunk_plus_offset(r, dsize);
          set_inuse(m, p, nb);
          set_size_and_pinuse_of_free_chunk(r, dsize);
          clear_pinuse(n);
          m->dvsize = dsize;
          m->dv = r;
        }
        else { /* exhaust dv */
          size_t newsize = oldsize + dvs;
          set_inuse(m, p, newsize);
          m->dvsize = 0;
          m->dv = 0;
        }
        newp = p;
      }
    }
    else if (!cinuse(next)) { /* extend into next free chunk */
      size_t nextsize = chunksize(next);
      if (oldsize + nextsize >= nb) {
        size_t rsize = oldsize + nextsize - nb;
        unlink_chunk(m, next, nextsize);
        if (rsize < MIN_CHUNK_SIZE) {
          size_t newsize = oldsize + nextsize;
          set_inuse(m, p, newsize);
        }
        else {
          mchunkptr r = chunk_plus_offset(p, nb);
          set_inuse(m, p, nb);
          set_inuse(m, r, rsize);
          dispose_chunk(m, r, rsize);
        }
        newp = p;
      }
    }
  }
  else {
    USAGE_ERROR_ACTION(m, chunk2mem(p));
  }
  return newp;
}
References chunk2mem, chunk_plus_offset, chunksize, cinuse, clear_pinuse, dispose_chunk(), malloc_state::dv, malloc_state::dvsize, malloc_chunk::head, is_mmapped, MIN_CHUNK_SIZE, mmap_resize(), ok_address, ok_inuse, ok_next, ok_pinuse, PINUSE_BIT, RTCHECK, set_inuse, set_size_and_pinuse_of_free_chunk, malloc_state::top, malloc_state::topsize, unlink_chunk, and USAGE_ERROR_ACTION.
Referenced by dlrealloc(), and dlrealloc_in_place().
Variable Documentation
_gm_
struct malloc_state _gm_ static
calloc_func
SDL_calloc_func calloc_func
Referenced by SDL_GetMemoryFunctions(), SDL_GetOriginalMemoryFunctions(), and SDL_SetMemoryFunctions().
dev_zero_fd
int dev_zero_fd = -1 static
free_func
SDL_free_func free_func
Referenced by mem_close(), SDL_GetErrBuf(), SDL_GetMemoryFunctions(), SDL_GetOriginalMemoryFunctions(), and SDL_SetMemoryFunctions().
malloc_func
SDL_malloc_func malloc_func
Referenced by SDL_GetMemoryFunctions(), SDL_GetOriginalMemoryFunctions(), and SDL_SetMemoryFunctions().
malloc_global_mutex
pthread_mutex_t malloc_global_mutex = PTHREAD_MUTEX_INITIALIZER static
mparams
struct malloc_params mparams static
Referenced by change_mparam(), dlpvalloc(), dlvalloc(), init_mparams(), init_top(), mmap_resize(), sys_alloc(), and sys_trim().
num_allocations
SDL_AtomicInt num_allocations
realloc_func
SDL_realloc_func realloc_func
Referenced by SDL_GetErrBuf(), SDL_GetMemoryFunctions(), SDL_GetOriginalMemoryFunctions(), and SDL_SetMemoryFunctions().
[struct]
struct { ... } s_mem
Initial value:
= {
    dlmalloc , dlcalloc , dlrealloc , dlfree , { 0 }
}
Referenced by SDL_calloc(), SDL_free(), SDL_GetMemoryFunctions(), SDL_GetNumAllocations(), SDL_malloc(), SDL_realloc(), and SDL_SetMemoryFunctions().