SDL3: SDL-main/src/timer/ngage/SDL_systimer.cpp File Reference
SDL_systimer.cpp File Reference
#include "SDL_internal.h"
#include <e32hal.h>
#include <e32std.h>
Functions
Uint64 SDL_GetPerformanceCounter (void)
Uint64 SDL_GetPerformanceFrequency (void)
void SDL_SYS_DelayNS (Uint64 ns)
Function Documentation
SDL_GetPerformanceCounter()
Uint64 SDL_GetPerformanceCounter (void)
Get the current value of the high resolution counter.
This function is typically used for profiling.
The counter values are only meaningful relative to each other. Differences between values can be converted to times by using SDL_GetPerformanceFrequency().
Returns
the current counter value.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPerformanceFrequency
{
    return static_cast<Uint64>(User::TickCount());
}
Referenced by SDL_GetTicks(), SDL_GetTicksNS(), SDL_InitTicks(), and SDL_srand().
SDL_GetPerformanceFrequency()
Uint64 SDL_GetPerformanceFrequency (void)
Get the count per second of the high resolution counter.
Returns
a platform-specific count per second.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPerformanceCounter
{
    // On Symbian S60v1, tick frequency is 64 Hz => 1 tick = 15,625 microseconds.
    return 64;
}
Referenced by SDL_InitTicks().
SDL_SYS_DelayNS()
void SDL_SYS_DelayNS (Uint64 ns)
{
    User::After(SDL_NS_TO_US(ns));
}
References SDL_NS_TO_US.
Referenced by SDL_Delay(), SDL_DelayNS(), and SDL_DelayPrecise().