SDL3: SDL_JoystickDriver Struct Reference
SDL_JoystickDriver Struct Reference
#include <SDL_sysjoystick.h>
Data Fields
void(* Close)(SDL_Joystick *joystick)
void(* Detect)(void)
int(* GetCount)(void)
SDL_GUID(* GetDeviceGUID)(int device_index)
SDL_JoystickID(* GetDeviceInstanceID)(int device_index)
const char *(* GetDeviceName)(int device_index)
const char *(* GetDevicePath)(int device_index)
int(* GetDevicePlayerIndex)(int device_index)
int(* GetDeviceSteamVirtualGamepadSlot)(int device_index)
bool(* GetGamepadMapping)(int device_index, SDL_GamepadMapping *out)
bool(* Init)(void)
bool(* IsDevicePresent)(Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
bool(* Open)(SDL_Joystick *joystick, int device_index)
void(* Quit)(void)
bool(* Rumble)(SDL_Joystick *joystick, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble)
bool(* RumbleTriggers)(SDL_Joystick *joystick, Uint16 left_rumble, Uint16 right_rumble)
bool(* SendEffect)(SDL_Joystick *joystick, const void *data, int size)
void(* SetDevicePlayerIndex)(int device_index, int player_index)
bool(* SetLED)(SDL_Joystick *joystick, Uint8 red, Uint8 green, Uint8 blue)
bool(* SetSensorsEnabled)(SDL_Joystick *joystick, bool enabled)
void(* Update)(SDL_Joystick *joystick)
Field Documentation
Close
void(* SDL_JoystickDriver::Close) (SDL_Joystick *joystick)
Detect
void(* SDL_JoystickDriver::Detect) (void)
GetCount
int(* SDL_JoystickDriver::GetCount) (void)
GetDeviceGUID
SDL_GUID(* SDL_JoystickDriver::GetDeviceGUID) (int device_index)
Referenced by SDL_GetJoystickGUIDForID(), and SDL_OpenJoystick().
GetDeviceInstanceID
SDL_JoystickID(* SDL_JoystickDriver::GetDeviceInstanceID) (int device_index)
GetDeviceName
const char *(* SDL_JoystickDriver::GetDeviceName) (int device_index)
Referenced by SDL_GetJoystickNameForID(), and SDL_OpenJoystick().
GetDevicePath
const char *(* SDL_JoystickDriver::GetDevicePath) (int device_index)
Referenced by SDL_GetJoystickPathForID(), and SDL_OpenJoystick().
GetDevicePlayerIndex
int(* SDL_JoystickDriver::GetDevicePlayerIndex) (int device_index)
Referenced by SDL_PrivateJoystickAdded().
GetDeviceSteamVirtualGamepadSlot
int(* SDL_JoystickDriver::GetDeviceSteamVirtualGamepadSlot) (int device_index)
Referenced by SDL_GetJoystickVirtualGamepadInfoForID(), and SDL_PrivateJoystickAdded().
GetGamepadMapping
bool(* SDL_JoystickDriver::GetGamepadMapping) (int device_index, SDL_GamepadMapping *out)
Referenced by SDL_PrivateJoystickGetAutoGamepadMapping().
Init
bool(* SDL_JoystickDriver::Init) (void)
IsDevicePresent
bool(* SDL_JoystickDriver::IsDevicePresent) (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
Open
bool(* SDL_JoystickDriver::Open) (SDL_Joystick *joystick, int device_index)
Referenced by SDL_OpenJoystick().
Quit
void(* SDL_JoystickDriver::Quit) (void)
Rumble
bool(* SDL_JoystickDriver::Rumble) (SDL_Joystick *joystick, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble)
RumbleTriggers
bool(* SDL_JoystickDriver::RumbleTriggers) (SDL_Joystick *joystick, Uint16 left_rumble, Uint16 right_rumble)
SendEffect
bool(* SDL_JoystickDriver::SendEffect) (SDL_Joystick *joystick, const void *data, int size)
SetDevicePlayerIndex
void(* SDL_JoystickDriver::SetDevicePlayerIndex) (int device_index, int player_index)
Referenced by SDL_SetJoystickIDForPlayerIndex().
SetLED
bool(* SDL_JoystickDriver::SetLED) (SDL_Joystick *joystick, Uint8 red, Uint8 green, Uint8 blue)
SetSensorsEnabled
bool(* SDL_JoystickDriver::SetSensorsEnabled) (SDL_Joystick *joystick, bool enabled)
Update
void(* SDL_JoystickDriver::Update) (SDL_Joystick *joystick)
Referenced by SDL_OpenJoystick().
The documentation for this struct was generated from the following file:
SDL-main/src/joystick/SDL_sysjoystick.h