SDL3: SDL-main/include/SDL3/SDL_tray.h File Reference
SDL_tray.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_surface.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDL_TRAYENTRY_BUTTON 0x00000001u
#define SDL_TRAYENTRY_CHECKBOX 0x00000002u
#define SDL_TRAYENTRY_CHECKED 0x40000000u
#define SDL_TRAYENTRY_DISABLED 0x80000000u
#define SDL_TRAYENTRY_SUBMENU 0x00000004u
Typedefs
typedef struct SDL_Tray SDL_Tray
typedef void(SDLCALL * SDL_TrayCallback) (void *userdata, SDL_TrayEntry *entry)
typedef struct SDL_TrayEntry SDL_TrayEntry
typedef Uint32 SDL_TrayEntryFlags
typedef struct SDL_TrayMenu SDL_TrayMenu
Functions
SDL_DECLSPEC void SDLCALL SDL_ClickTrayEntry (SDL_TrayEntry *entry)
SDL_DECLSPEC SDL_Tray *SDLCALL SDL_CreateTray (SDL_Surface *icon, const char *tooltip)
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_CreateTrayMenu (SDL_Tray *tray)
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_CreateTraySubmenu (SDL_TrayEntry *entry)
SDL_DECLSPEC void SDLCALL SDL_DestroyTray (SDL_Tray *tray)
SDL_DECLSPEC const SDL_TrayEntry **SDLCALL SDL_GetTrayEntries (SDL_TrayMenu *menu, int *count)
SDL_DECLSPEC bool SDLCALL SDL_GetTrayEntryChecked (SDL_TrayEntry *entry)
SDL_DECLSPEC bool SDLCALL SDL_GetTrayEntryEnabled (SDL_TrayEntry *entry)
SDL_DECLSPEC const char *SDLCALL SDL_GetTrayEntryLabel (SDL_TrayEntry *entry)
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_GetTrayEntryParent (SDL_TrayEntry *entry)
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_GetTrayMenu (SDL_Tray *tray)
SDL_DECLSPEC SDL_TrayEntry *SDLCALL SDL_GetTrayMenuParentEntry (SDL_TrayMenu *menu)
SDL_DECLSPEC SDL_Tray *SDLCALL SDL_GetTrayMenuParentTray (SDL_TrayMenu *menu)
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_GetTraySubmenu (SDL_TrayEntry *entry)
SDL_DECLSPEC SDL_TrayEntry *SDLCALL SDL_InsertTrayEntryAt (SDL_TrayMenu *menu, int pos, const char *label, SDL_TrayEntryFlags flags)
SDL_DECLSPEC bool SDLCALL SDL_IsTraySupported (void)
SDL_DECLSPEC void SDLCALL SDL_RemoveTrayEntry (SDL_TrayEntry *entry)
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryCallback (SDL_TrayEntry *entry, SDL_TrayCallback callback, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryChecked (SDL_TrayEntry *entry, bool checked)
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryEnabled (SDL_TrayEntry *entry, bool enabled)
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryLabel (SDL_TrayEntry *entry, const char *label)
SDL_DECLSPEC void SDLCALL SDL_SetTrayIcon (SDL_Tray *tray, SDL_Surface *icon)
SDL_DECLSPEC void SDLCALL SDL_SetTrayTooltip (SDL_Tray *tray, const char *tooltip)
SDL_DECLSPEC void SDLCALL SDL_UpdateTrays (void)
Macro Definition Documentation
SDL_TRAYENTRY_BUTTON
#define SDL_TRAYENTRY_BUTTON 0x00000001u
Make the entry a simple button. Required.
SDL_TRAYENTRY_CHECKBOX
#define SDL_TRAYENTRY_CHECKBOX 0x00000002u
Make the entry a checkbox. Required.
Referenced by SDL_ClickTrayEntry(), SDL_GetTrayEntryChecked(), SDL_InsertTrayEntryAt(), SDL_SetTrayEntryChecked(), and TrayWindowProc().
SDL_TRAYENTRY_CHECKED
#define SDL_TRAYENTRY_CHECKED 0x40000000u
Make the entry checked. This is valid only for checkboxes. Optional.
Referenced by SDL_InsertTrayEntryAt().
SDL_TRAYENTRY_DISABLED
#define SDL_TRAYENTRY_DISABLED 0x80000000u
Make the entry disabled. Optional.
Referenced by SDL_InsertTrayEntryAt().
SDL_TRAYENTRY_SUBMENU
#define SDL_TRAYENTRY_SUBMENU 0x00000004u
Prepare the entry to have a submenu. Required
Referenced by SDL_CreateTraySubmenu(), and SDL_InsertTrayEntryAt().
Typedef Documentation
SDL_Tray
typedef struct SDL_Tray SDL_Tray
CategoryTray
SDL offers a way to add items to the "system tray" (more correctly called the "notification area" on Windows). On platforms that offer this concept, an SDL app can add a tray icon, submenus, checkboxes, and clickable entries, and register a callback that is fired when the user clicks on these pieces. An opaque handle representing a toplevel system tray object.
Since
This struct is available since SDL 3.2.0.
SDL_TrayCallback
typedef void(SDLCALL * SDL_TrayCallback) (void *userdata, SDL_TrayEntry *entry)
A callback that is invoked when a tray entry is selected.
Parameters
userdata an optional pointer to pass extra data to the callback when it will be invoked.
entry the tray entry that was selected.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_SetTrayEntryCallback
SDL_TrayEntry
typedef struct SDL_TrayEntry SDL_TrayEntry
An opaque handle representing an entry on a system tray object.
Since
This struct is available since SDL 3.2.0.
SDL_TrayEntryFlags
typedef Uint32 SDL_TrayEntryFlags
Flags that control the creation of system tray entries.
Some of these flags are required; exactly one of them must be specified at the time a tray entry is created. Other flags are optional; zero or more of those can be OR'ed together with the required flag.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_TrayMenu
typedef struct SDL_TrayMenu SDL_TrayMenu
An opaque handle representing a menu/submenu on a system tray object.
Since
This struct is available since SDL 3.2.0.
Function Documentation
SDL_ClickTrayEntry()
SDL_DECLSPEC void SDLCALL SDL_ClickTrayEntry (SDL_TrayEntry * entry) extern
Simulate a click on a tray entry.
Parameters
entry The entry to activate.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
{
}
References SDL_TrayEntry::callback, SDL_TrayEntry::flags, SDL_GetTrayEntryChecked(), SDL_SetTrayEntryChecked(), SDL_TRAYENTRY_CHECKBOX, and SDL_TrayEntry::userdata.
SDL_CreateTray()
SDL_DECLSPEC SDL_Tray *SDLCALL SDL_CreateTray (SDL_Surface * icon, const char * tooltip) extern
Create an icon to be placed in the operating system's tray, or equivalent.
Many platforms advise not using a system tray unless persistence is a necessary feature. Avoid needlessly creating a tray icon, as the user may feel like it clutters their interface.
Using tray icons require the video subsystem.
Parameters
icon a surface to be used as icon. May be NULL.
tooltip a tooltip to be displayed when the mouse hovers the icon in UTF-8 encoding. Not supported on all platforms. May be NULL.
Returns
The newly created system tray icon.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenu
SDL_DestroyTray
{
    SDL_Unsupported();
    return NULL;
}
References APP_INDICATOR_CATEGORY_APPLICATION_STATUS, app_indicator_new, app_indicator_set_menu, app_indicator_set_status, APP_INDICATOR_STATUS_ACTIVE, CreateIconFromSurface(), g_mkdtemp, g_object_ref_sink, get_appindicator_id(), get_next_id(), GTK_MENU, gtk_menu_new, SDL_Tray::hwnd, SDL_Tray::icon, SDL_Tray::icon_dir, ICON_DIR_TEMPLATE, SDL_Tray::icon_path, SDL_Tray::indicator, init_gtk(), load_default_icon(), SDL_Tray::menu, SDL_Tray::menu_cached, new_tmp_filename(), SDL_Tray::nid, NIF_SHOWTIP, NOTIFYICON_VERSION_4, NULL, SDL_calloc(), SDL_free(), SDL_IsMainThread(), SDL_RegisterTray(), SDL_SaveBMP(), SDL_SetError(), SDL_strlcpy(), SDL_Unsupported, SDL_wcslcpy(), SDL_zero, TrayWindowProc(), WIN_UpdateDarkModeForHWND(), WIN_UTF8ToStringW, and WM_TRAYICON.
SDL_CreateTrayMenu()
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_CreateTrayMenu (SDL_Tray * tray) extern
Create a menu for a system tray.
This should be called at most once per tray icon.
This function does the same thing as SDL_CreateTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_GetTrayMenu
SDL_GetTrayMenuParentTray
{
    SDL_InvalidParamError("tray");
    return NULL;
}
References SDL_TrayMenu::entries, g_object_ref, SDL_TrayMenu::hMenu, SDL_Tray::menu, SDL_TrayMenu::menu, SDL_Tray::menu_cached, SDL_TrayMenu::nEntries, NULL, SDL_TrayMenu::parent_entry, SDL_TrayMenu::parent_tray, SDL_calloc(), SDL_InvalidParamError, SDL_OBJECT_TYPE_TRAY, and SDL_ObjectValid().
SDL_CreateTraySubmenu()
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_CreateTraySubmenu (SDL_TrayEntry * entry) extern
Create a submenu for a system tray entry.
This should be called at most once per tray entry.
This function does the same thing as SDL_CreateTrayMenu, except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_GetTraySubmenu
SDL_GetTrayMenuParentEntry
{
    SDL_InvalidParamError("entry");
    return NULL;
}
References SDL_TrayMenu::entries, SDL_TrayEntry::flags, g_object_ref_sink, GTK_MENU_ITEM, gtk_menu_item_set_submenu, gtk_menu_new, GTK_WIDGET, SDL_TrayEntry::item, SDL_TrayMenu::menu, SDL_TrayMenu::nEntries, NULL, SDL_TrayMenu::parent_entry, SDL_TrayMenu::parent_tray, SDL_calloc(), SDL_InvalidParamError, SDL_SetError(), SDL_TRAYENTRY_SUBMENU, and SDL_TrayEntry::submenu.
SDL_DestroyTray()
SDL_DECLSPEC void SDLCALL SDL_DestroyTray (SDL_Tray * tray) extern
Destroys a tray object.
This also destroys all associated menus and entries.
Parameters
tray the tray icon to be destroyed.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
}
References DestroySDLMenu(), g_object_unref, SDL_Tray::hwnd, SDL_Tray::icon, SDL_Tray::icon_dir, SDL_Tray::icon_path, SDL_Tray::indicator, SDL_Tray::menu, SDL_Tray::menu_cached, SDL_Tray::nid, SDL_free(), SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), SDL_RemovePath(), and SDL_UnregisterTray().
Referenced by SDL_CleanupTrays().
SDL_GetTrayEntries()
SDL_DECLSPEC const SDL_TrayEntry **SDLCALL SDL_GetTrayEntries (SDL_TrayMenu * menu, int * count) extern
Returns a list of entries in the menu, in order.
Parameters
menu The menu to get entries from.
count An optional pointer to obtain the number of entries in the menu.
Returns
a NULL-terminated list of entries within the given menu. The pointer becomes invalid when any function that inserts or deletes entries in the menu is called.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveTrayEntry
SDL_InsertTrayEntryAt
{
    SDL_InvalidParamError("menu");
    return NULL;
}
References count, SDL_TrayMenu::entries, SDL_TrayMenu::nEntries, NULL, and SDL_InvalidParamError.
SDL_GetTrayEntryChecked()
SDL_DECLSPEC bool SDLCALL SDL_GetTrayEntryChecked (SDL_TrayEntry * entry) extern
Gets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be read.
Returns
true if the entry is checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryChecked
{
    return SDL_InvalidParamError("entry");
}
References FALSE, SDL_TrayEntry::flags, GTK_CHECK_MENU_ITEM, gtk_check_menu_item_get_active, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::item, SDL_TrayEntry::parent, SDL_InvalidParamError, and SDL_TRAYENTRY_CHECKBOX.
Referenced by SDL_ClickTrayEntry(), and TrayWindowProc().
SDL_GetTrayEntryEnabled()
SDL_DECLSPEC bool SDLCALL SDL_GetTrayEntryEnabled (SDL_TrayEntry * entry) extern
Gets whether or not an entry is enabled.
Parameters
entry the entry to be read.
Returns
true if the entry is enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryEnabled
{
    return SDL_InvalidParamError("entry");
}
References FALSE, gtk_widget_get_sensitive, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::item, SDL_TrayEntry::parent, and SDL_InvalidParamError.
SDL_GetTrayEntryLabel()
SDL_DECLSPEC const char *SDLCALL SDL_GetTrayEntryLabel (SDL_TrayEntry * entry) extern
Gets the label of an entry.
If the returned value is NULL, the entry is a separator.
Parameters
entry the entry to be read.
Returns
the label of the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryLabel
{
    SDL_InvalidParamError("entry");
    return NULL;
}
References GTK_MENU_ITEM, gtk_menu_item_get_label, SDL_TrayEntry::item, SDL_TrayEntry::label_cache, NULL, and SDL_InvalidParamError.
SDL_GetTrayEntryParent()
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_GetTrayEntryParent (SDL_TrayEntry * entry) extern
Gets the menu containing a certain tray entry.
Parameters
entry the entry for which to get the parent menu.
Returns
the parent menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
{
    SDL_InvalidParamError("entry");
    return NULL;
}
References NULL, SDL_TrayEntry::parent, and SDL_InvalidParamError.
SDL_GetTrayMenu()
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_GetTrayMenu (SDL_Tray * tray) extern
Gets a previously created tray menu.
You should have called SDL_CreateTrayMenu() on the tray object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_CreateTrayMenu
{
    SDL_InvalidParamError("tray");
    return NULL;
}
References SDL_Tray::menu, NULL, SDL_InvalidParamError, SDL_OBJECT_TYPE_TRAY, and SDL_ObjectValid().
SDL_GetTrayMenuParentEntry()
SDL_DECLSPEC SDL_TrayEntry *SDLCALL SDL_GetTrayMenuParentEntry (SDL_TrayMenu * menu) extern
Gets the entry for which the menu is a submenu, if the current menu is a submenu.
Either this function or SDL_GetTrayMenuParentTray() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent entry.
Returns
the parent entry, or NULL if this menu is not a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTraySubmenu
SDL_GetTrayMenuParentTray
{
    SDL_InvalidParamError("menu");
    return NULL;
}
References NULL, SDL_TrayMenu::parent_entry, and SDL_InvalidParamError.
SDL_GetTrayMenuParentTray()
SDL_DECLSPEC SDL_Tray *SDLCALL SDL_GetTrayMenuParentTray (SDL_TrayMenu * menu) extern
Gets the tray for which this menu is the first-level menu, if the current menu isn't a submenu.
Either this function or SDL_GetTrayMenuParentEntry() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent enttrayry.
Returns
the parent tray, or NULL if this menu is a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenuParentEntry
{
    SDL_InvalidParamError("menu");
    return NULL;
}
References NULL, SDL_TrayMenu::parent_tray, and SDL_InvalidParamError.
SDL_GetTraySubmenu()
SDL_DECLSPEC SDL_TrayMenu *SDLCALL SDL_GetTraySubmenu (SDL_TrayEntry * entry) extern
Gets a previously created tray entry submenu.
You should have called SDL_CreateTraySubmenu() on the entry object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTrayMenu(), except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_CreateTraySubmenu
{
    return NULL;
}
References NULL, SDL_InvalidParamError, and SDL_TrayEntry::submenu.
SDL_InsertTrayEntryAt()
SDL_DECLSPEC SDL_TrayEntry *SDLCALL SDL_InsertTrayEntryAt (SDL_TrayMenu * menu, int pos, const char * label, SDL_TrayEntryFlags flags) extern
Insert a tray entry at a given position.
If label is NULL, the entry will be a separator. Many functions won't work for an entry that is a separator.
An entry does not need to be destroyed; it will be destroyed with the tray.
Parameters
menu the menu to append the entry to.
pos the desired position for the new entry. Entries at or following this place will be moved. If pos is -1, the entry is appended.
label the text to be displayed on the entry, in UTF-8 encoding, or NULL for a separator.
flags a combination of flags, some of which are mandatory.
Returns
the newly created entry, or NULL if pos is out of bounds.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_TrayEntryFlags
SDL_GetTrayEntries
SDL_RemoveTrayEntry
SDL_GetTrayEntryParent
{
    SDL_InvalidParamError("menu");
    return NULL;
}
References active, call_callback(), SDL_TrayEntry::callback, SDL_TrayMenu::entries, escape_label(), SDL_TrayEntry::flags, G_CALLBACK, g_signal_connect, get_next_id(), GTK_CHECK_MENU_ITEM, gtk_check_menu_item_new_with_label, gtk_check_menu_item_set_active, gtk_menu_item_new_with_label, gtk_menu_shell_insert, gtk_separator_menu_item_new, gtk_widget_set_sensitive, gtk_widget_show, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::ignore_signal, SDL_TrayEntry::item, SDL_TrayEntry::label_cache, SDL_TrayMenu::menu, SDL_TrayMenu::nEntries, NULL, SDL_TrayEntry::parent, SDL_TrayMenu::parent_entry, SDL_TrayMenu::parent_tray, SDL_calloc(), SDL_free(), SDL_InvalidParamError, SDL_realloc(), SDL_snprintf(), SDL_TRAYENTRY_CHECKBOX, SDL_TRAYENTRY_CHECKED, SDL_TRAYENTRY_DISABLED, SDL_TRAYENTRY_SUBMENU, SDL_TrayEntry::submenu, and SDL_TrayEntry::userdata.
SDL_IsTraySupported()
SDL_DECLSPEC bool SDLCALL SDL_IsTraySupported (void) extern
Check whether or not tray icons can be created.
Note that this function does not guarantee that SDL_CreateTray() will or will not work; you should still check SDL_CreateTray() for errors.
Using tray icons require the video subsystem.
Returns
true if trays are available, false otherwise.
Thread Safety
This function should only be called on the main thread. It will return false if not called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateTray
{
    return false;
}
References init_gtk(), SDL_IsMainThread(), and SDL_SetError().
SDL_RemoveTrayEntry()
SDL_DECLSPEC void SDLCALL SDL_RemoveTrayEntry (SDL_TrayEntry * entry) extern
Removes a tray entry.
Parameters
entry The entry to be deleted.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
}
References DestroySDLMenu(), SDL_TrayMenu::entries, gtk_widget_destroy, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::item, SDL_TrayMenu::nEntries, NULL, SDL_TrayEntry::parent, SDL_free(), SDL_realloc(), SDL_SetError(), and SDL_TrayEntry::submenu.
SDL_SetTrayEntryCallback()
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryCallback (SDL_TrayEntry * entry, SDL_TrayCallback callback, void * userdata) extern
Sets a callback to be invoked when the entry is selected.
Parameters
entry the entry to be updated.
callback a callback to be invoked when the entry is selected.
userdata an optional pointer to pass extra data to the callback when it will be invoked.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
}
References SDL_TrayEntry::callback, and SDL_TrayEntry::userdata.
SDL_SetTrayEntryChecked()
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryChecked (SDL_TrayEntry * entry, bool checked) extern
Sets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be updated.
checked true if the entry should be checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryChecked
{
}
References SDL_TrayEntry::flags, GTK_CHECK_MENU_ITEM, gtk_check_menu_item_set_active, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::ignore_signal, SDL_TrayEntry::item, SDL_TrayEntry::parent, and SDL_TRAYENTRY_CHECKBOX.
Referenced by SDL_ClickTrayEntry(), and TrayWindowProc().
SDL_SetTrayEntryEnabled()
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryEnabled (SDL_TrayEntry * entry, bool enabled) extern
Sets whether or not an entry is enabled.
Parameters
entry the entry to be updated.
enabled true if the entry should be enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryEnabled
{
}
References gtk_widget_set_sensitive, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::item, and SDL_TrayEntry::parent.
SDL_SetTrayEntryLabel()
SDL_DECLSPEC void SDLCALL SDL_SetTrayEntryLabel (SDL_TrayEntry * entry, const char * label) extern
Sets the label of an entry.
An entry cannot change between a separator and an ordinary entry; that is, it is not possible to set a non-NULL label on an entry that has a NULL label (separators), or to set a NULL label to an entry that has a non-NULL label. The function will silently fail if that happens.
Parameters
entry the entry to be updated.
label the new label for the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryLabel
{
}
References escape_label(), FALSE, GTK_MENU_ITEM, gtk_menu_item_set_label, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::item, SDL_TrayEntry::label_cache, SDL_TrayEntry::parent, SDL_free(), SDL_SetError(), SDL_snprintf(), and SDL_wcslen().
SDL_SetTrayIcon()
SDL_DECLSPEC void SDLCALL SDL_SetTrayIcon (SDL_Tray * tray, SDL_Surface * icon) extern
Updates the system tray icon's icon.
Parameters
tray the tray icon to be updated.
icon the new icon. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
}
References app_indicator_set_icon, CreateIconFromSurface(), SDL_Tray::icon, SDL_Tray::icon_path, SDL_Tray::indicator, load_default_icon(), new_tmp_filename(), SDL_Tray::nid, NULL, SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), SDL_RemovePath(), and SDL_SaveBMP().
SDL_SetTrayTooltip()
SDL_DECLSPEC void SDLCALL SDL_SetTrayTooltip (SDL_Tray * tray, const char * tooltip) extern
Updates the system tray icon's tooltip.
Parameters
tray the tray icon to be updated.
tooltip the new tooltip in UTF-8 encoding. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
}
References SDL_Tray::nid, SDL_free(), SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), SDL_wcslcpy(), and WIN_UTF8ToStringW.
SDL_UpdateTrays()
SDL_DECLSPEC void SDLCALL SDL_UpdateTrays (void) extern
Update the trays.
This is called automatically by the event loop and is only needed if you're using trays but aren't handling SDL events.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
}
References FALSE, gtk_main_iteration_do, and SDL_HasActiveTrays().
Referenced by SDL_PumpEventMaintenance().