SDL3: SDL-main/src/SDL_guid.c File Reference
SDL_guid.c File Reference
#include "SDL_internal.h"
Functions
static unsigned char nibble (unsigned char c)
void SDL_GUIDToString (SDL_GUID guid, char *pszGUID, int cbGUID)
SDL_GUID SDL_StringToGUID (const char *pchGUID)
Function Documentation
nibble()
unsigned char nibble (unsigned char c) static
{
    if ((c >= '0') && (c <= '9')) {
        return c - '0';
    }
    if ((c >= 'A') && (c <= 'F')) {
        return c - 'A' + 0x0a;
    }
    if ((c >= 'a') && (c <= 'f')) {
        return c - 'a' + 0x0a;
    }
    // received an invalid character, and no real way to return an error
    // AssertMsg1(false, "Q_nibble invalid hex character '%c' ", c);
    return 0;
}
Referenced by LAW_Decode(), and SDL_StringToGUID().
SDL_GUIDToString()
void SDL_GUIDToString (SDL_GUID guid, char * pszGUID, int cbGUID)
Get an ASCII string representation for a given SDL_GUID.
Parameters
guid the SDL_GUID you wish to convert to string.
pszGUID buffer in which to write the ASCII string.
cbGUID the size of pszGUID, should be at least 33 bytes.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_StringToGUID
{
    static const char k_rgchHexToASCII[] = "0123456789abcdef";
    int i;
    if ((!pszGUID) || (cbGUID <= 0)) {
        return;
    }
    for (i = 0; i < sizeof(guid.data) && i < (cbGUID - 1) / 2; i++) {
        // each input byte writes 2 ascii chars, and might write a null byte.
        // If we don't have room for next input byte, stop
        unsigned char c = guid.data[i];
        *pszGUID++ = k_rgchHexToASCII[c >> 4];
        *pszGUID++ = k_rgchHexToASCII[c & 0x0F];
    }
    *pszGUID = '\0';
}
References SDL_GUID::data.
Referenced by CreateMappingString(), and SDL_GetGamepadMappingForID().
SDL_StringToGUID()
SDL_GUID SDL_StringToGUID (const char * pchGUID)
Convert a GUID string into a SDL_GUID structure.
Performs no error checking. If this function is given a string containing an invalid GUID, the function will silently succeed, but the GUID generated will not be useful.
Parameters
pchGUID string containing an ASCII representation of a GUID.
Returns
a SDL_GUID structure.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GUIDToString
{
    SDL_GUID guid;
    int maxoutputbytes = sizeof(guid);
    size_t len = SDL_strlen(pchGUID);
    Uint8 *p;
    size_t i;
    // Make sure it's even
    len = (len) & ~0x1;
    SDL_memset(&guid, 0x00, sizeof(guid));
    p = (Uint8 *)&guid;
    for (i = 0; (i < len) && ((p - (Uint8 *)&guid) < maxoutputbytes); i += 2, p++) {
        *p = (nibble((unsigned char)pchGUID[i]) << 4) | nibble((unsigned char)pchGUID[i + 1]);
    }
    return guid;
}
References nibble(), SDL_memset, and SDL_strlen().
Referenced by SDL_PrivateAddGamepadMapping().