SDL3: SDL-main/src/thread/generic/SDL_systhread.c File Reference
SDL_systhread.c File Reference
#include "SDL_internal.h"
#include "../SDL_systhread.h"
Functions
SDL_ThreadID SDL_GetCurrentThreadID (void)
bool SDL_SYS_CreateThread (SDL_Thread *thread, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
void SDL_SYS_DetachThread (SDL_Thread *thread)
bool SDL_SYS_SetThreadPriority (SDL_ThreadPriority priority)
void SDL_SYS_SetupThread (const char *name)
void SDL_SYS_WaitThread (SDL_Thread *thread)
Function Documentation
SDL_GetCurrentThreadID()
SDL_ThreadID SDL_GetCurrentThreadID (void)
Get the thread identifier for the current thread.
This thread identifier is as reported by the underlying operating system. If SDL is running on a platform that does not support threads the return value will always be zero.
This function also returns a valid thread ID when called from the main thread.
Returns
the ID of the current thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetThreadID
{
    return 0;
}
SDL_SYS_CreateThread()
bool SDL_SYS_CreateThread (SDL_Thread * thread, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
{
    return SDL_SetError("Threads are not supported on this platform");
}
References SDL_SetError().
Referenced by SDL_CreateThreadWithPropertiesRuntime().
SDL_SYS_DetachThread()
void SDL_SYS_DetachThread (SDL_Thread * thread)
{
    return;
}
Referenced by SDL_DetachThread().
SDL_SYS_SetThreadPriority()
bool SDL_SYS_SetThreadPriority (SDL_ThreadPriority priority)
{
    return true;
}
Referenced by SDL_SetCurrentThreadPriority().
SDL_SYS_SetupThread()
void SDL_SYS_SetupThread (const char * name)
{
    return;
}
Referenced by SDL_RunThread().
SDL_SYS_WaitThread()
void SDL_SYS_WaitThread (SDL_Thread * thread)
{
    return;
}
Referenced by SDL_WaitThread().