SDL3: SDL-main/src/video/SDL_fillrect.c File Reference
SDL_fillrect.c File Reference
#include "SDL_internal.h"
#include "SDL_surface_c.h"
Functions
bool SDL_FillSurfaceRect (SDL_Surface *dst, const SDL_Rect *rect, Uint32 color)
static void SDL_FillSurfaceRect1 (Uint8 *pixels, int pitch, Uint32 color, int w, int h)
static void SDL_FillSurfaceRect2 (Uint8 *pixels, int pitch, Uint32 color, int w, int h)
static void SDL_FillSurfaceRect3 (Uint8 *pixels, int pitch, Uint32 color, int w, int h)
static void SDL_FillSurfaceRect4 (Uint8 *pixels, int pitch, Uint32 color, int w, int h)
bool SDL_FillSurfaceRects (SDL_Surface *dst, const SDL_Rect *rects, int count, Uint32 color)
Function Documentation
SDL_FillSurfaceRect()
bool SDL_FillSurfaceRect (SDL_Surface * dst, const SDL_Rect * rect, Uint32 color)
Perform a fast fill of a rectangle with a specific color.
color should be a pixel of the format used by the surface, and can be generated by SDL_MapRGB() or SDL_MapRGBA(). If the color value contains an alpha component then the destination is simply filled with that alpha information, no blending takes place.
If there is a clip rectangle set on the destination (set via SDL_SetSurfaceClipRect()), then this function will fill based on the intersection of the clip rectangle and rect.
Parameters
dst the SDL_Surface structure that is the drawing target.
rect the SDL_Rect structure representing the rectangle to fill, or NULL to fill the entire surface.
color the color to fill with.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_FillSurfaceRects
{
    if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("SDL_FillSurfaceRect(): dst");
    }
    // If 'rect' == NULL, then fill the whole surface
    if (!rect) {
        rect = &dst->clip_rect;
        // Don't attempt to fill if the surface's clip_rect is empty
        if (SDL_RectEmpty(rect)) {
            return true;
        }
    }
    return SDL_FillSurfaceRects(dst, rect, 1, color);
}
References SDL_Surface::clip_rect, SDL_FillSurfaceRects(), SDL_InvalidParamError, SDL_RectEmpty(), and SDL_SurfaceValid().
Referenced by SDL_ClearSurface(), and SDL_ConvertSurfaceAndColorspace().
SDL_FillSurfaceRect1()
void SDL_FillSurfaceRect1 (Uint8 * pixels, int pitch, Uint32 color, int w, int h) static
{
    int n;
    Uint8 *p = NULL;
    while (h--) {
        n = w;
        p = pixels;
        if (n > 3) {
            switch ((uintptr_t)p & 3) {
            case 1:
                *p++ = (Uint8)color;
                --n;
                SDL_FALLTHROUGH;
            case 2:
                *p++ = (Uint8)color;
                --n;
                SDL_FALLTHROUGH;
            case 3:
                *p++ = (Uint8)color;
                --n;
            }
            SDL_memset4(p, color, (n >> 2));
        }
        if (n & 3) {
            p += (n & ~3);
            switch (n & 3) {
            case 3:
                *p++ = (Uint8)color;
                SDL_FALLTHROUGH;
            case 2:
                *p++ = (Uint8)color;
                SDL_FALLTHROUGH;
            case 1:
                *p++ = (Uint8)color;
            }
        }
        pixels += pitch;
    }
}
References NULL, SDL_FALLTHROUGH, and SDL_memset4().
Referenced by SDL_FillSurfaceRects().
SDL_FillSurfaceRect2()
void SDL_FillSurfaceRect2 (Uint8 * pixels, int pitch, Uint32 color, int w, int h) static
{
    int n;
    Uint16 *p = NULL;
    while (h--) {
        n = w;
        p = (Uint16 *)pixels;
        if (n > 1) {
            if ((uintptr_t)p & 2) {
                *p++ = (Uint16)color;
                --n;
            }
            SDL_memset4(p, color, (n >> 1));
        }
        if (n & 1) {
            p[n - 1] = (Uint16)color;
        }
        pixels += pitch;
    }
}
References NULL, and SDL_memset4().
Referenced by SDL_FillSurfaceRects().
SDL_FillSurfaceRect3()
void SDL_FillSurfaceRect3 (Uint8 * pixels, int pitch, Uint32 color, int w, int h) static
{
#if SDL_BYTEORDER == SDL_LIL_ENDIAN
    Uint8 b1 = (Uint8)(color & 0xFF);
    Uint8 b2 = (Uint8)((color >> 8) & 0xFF);
    Uint8 b3 = (Uint8)((color >> 16) & 0xFF);
#elif SDL_BYTEORDER == SDL_BIG_ENDIAN
    Uint8 b1 = (Uint8)((color >> 16) & 0xFF);
    Uint8 b2 = (Uint8)((color >> 8) & 0xFF);
    Uint8 b3 = (Uint8)(color & 0xFF);
#endif
    int n;
    Uint8 *p = NULL;
    while (h--) {
        n = w;
        p = pixels;
        while (n--) {
            *p++ = b1;
            *p++ = b2;
            *p++ = b3;
        }
        pixels += pitch;
    }
}
References NULL.
Referenced by SDL_FillSurfaceRects().
SDL_FillSurfaceRect4()
void SDL_FillSurfaceRect4 (Uint8 * pixels, int pitch, Uint32 color, int w, int h) static
{
    while (h--) {
        SDL_memset4(pixels, color, w);
        pixels += pitch;
    }
}
References SDL_memset4().
Referenced by SDL_FillSurfaceRects().
SDL_FillSurfaceRects()
bool SDL_FillSurfaceRects (SDL_Surface * dst, const SDL_Rect * rects, int count, Uint32 color)
Perform a fast fill of a set of rectangles with a specific color.
color should be a pixel of the format used by the surface, and can be generated by SDL_MapRGB() or SDL_MapRGBA(). If the color value contains an alpha component then the destination is simply filled with that alpha information, no blending takes place.
If there is a clip rectangle set on the destination (set via SDL_SetSurfaceClipRect()), then this function will fill based on the intersection of the clip rectangle and rect.
Parameters
dst the SDL_Surface structure that is the drawing target.
rects an array of SDL_Rects representing the rectangles to fill.
count the number of rectangles in the array.
color the color to fill with.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_FillSurfaceRect
{
    SDL_Rect clipped;
    Uint8 *pixels;
    const SDL_Rect *rect;
    void (*fill_function)(Uint8 * pixels, int pitch, Uint32 color, int w, int h) = NULL;
    int i;
    if (!SDL_SurfaceValid(dst)) {
        return SDL_InvalidParamError("SDL_FillSurfaceRects(): dst");
    }
    // Nothing to do
    if (dst->w == 0 || dst->h == 0) {
        return true;
    }
    // Perform software fill
    if (!dst->pixels) {
        return SDL_SetError("SDL_FillSurfaceRects(): You must lock the surface");
    }
    if (!rects) {
        return SDL_InvalidParamError("SDL_FillSurfaceRects(): rects");
    }
    /* This function doesn't usually work on surfaces < 8 bpp
     * Except: support for 4bits, when filling full size.
     */
    if (SDL_BITSPERPIXEL(dst->format) < 8) {
        if (count == 1) {
            const SDL_Rect *r = &rects[0];
            if (r->x == 0 && r->y == 0 && r->w == dst->w && r->h == dst->h) {
                if (SDL_BITSPERPIXEL(dst->format) == 4) {
                    Uint8 b = (((Uint8)color << 4) | (Uint8)color);
                    SDL_memset(dst->pixels, b, (size_t)dst->h * dst->pitch);
                    return true;
                }
            }
        }
        return SDL_SetError("SDL_FillSurfaceRects(): Unsupported surface format");
    }
    if (fill_function == NULL) {
        switch (SDL_BYTESPERPIXEL(dst->format)) {
        case 1:
        {
            color |= (color << 8);
            color |= (color << 16);
#ifdef SDL_SSE_INTRINSICS
            if (SDL_HasSSE()) {
                fill_function = SDL_FillSurfaceRect1SSE;
                break;
            }
#endif
            fill_function = SDL_FillSurfaceRect1;
            break;
        }
        case 2:
        {
            color |= (color << 16);
#ifdef SDL_SSE_INTRINSICS
            if (SDL_HasSSE()) {
                fill_function = SDL_FillSurfaceRect2SSE;
                break;
            }
#endif
            fill_function = SDL_FillSurfaceRect2;
            break;
        }
        case 3:
            // 24-bit RGB is a slow path, at least for now.
            {
                fill_function = SDL_FillSurfaceRect3;
                break;
            }
        case 4:
        {
#ifdef SDL_SSE_INTRINSICS
            if (SDL_HasSSE()) {
                fill_function = SDL_FillSurfaceRect4SSE;
                break;
            }
#endif
            fill_function = SDL_FillSurfaceRect4;
            break;
        }
        default:
            return SDL_SetError("Unsupported pixel format");
        }
    }
    for (i = 0; i < count; ++i) {
        rect = &rects[i];
        // Perform clipping
        if (!SDL_GetRectIntersection(rect, &dst->clip_rect, &clipped)) {
            continue;
        }
        rect = &clipped;
        pixels = (Uint8 *)dst->pixels + rect->y * dst->pitch +
                 rect->x * SDL_BYTESPERPIXEL(dst->format);
        fill_function(pixels, dst->pitch, color, rect->w, rect->h);
    }
    // We're done!
    return true;
}
References SDL_Surface::clip_rect, count, SDL_Surface::format, SDL_Rect::h, SDL_Surface::h, NULL, SDL_Surface::pitch, SDL_Surface::pixels, SDL_BITSPERPIXEL, SDL_BYTESPERPIXEL, SDL_FillSurfaceRect1(), SDL_FillSurfaceRect2(), SDL_FillSurfaceRect3(), SDL_FillSurfaceRect4(), SDL_GetRectIntersection(), SDL_HasSSE(), SDL_InvalidParamError, SDL_memset, SDL_SetError(), SDL_SurfaceValid(), void(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_FillSurfaceRect().