SDL3: SDL-main/src/events/SDL_mouse_c.h File Reference
SDL_mouse_c.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_Cursor
struct SDL_Mouse
struct SDL_MouseClickState
struct SDL_MouseInputSource
Macros
#define SDL_DEFAULT_MOUSE_ID 1
#define SDL_GLOBAL_MOUSE_ID 0
Typedefs
typedef struct SDL_CursorData SDL_CursorData
Functions
void SDL_AddMouse (SDL_MouseID mouseID, const char *name, bool send_event)
void SDL_DisableMouseWarpEmulation (void)
SDL_SystemCursor SDL_GetDefaultSystemCursor (void)
SDL_Mouse * SDL_GetMouse (void)
bool SDL_GetRelativeMouseMode (void)
bool SDL_IsMouse (Uint16 vendor, Uint16 product)
bool SDL_MousePositionInWindow (SDL_Window *window, float x, float y)
void SDL_PerformWarpMouseInWindow (SDL_Window *window, float x, float y, bool ignore_relative_mode)
void SDL_PostInitMouse (void)
bool SDL_PreInitMouse (void)
void SDL_QuitMouse (void)
void SDL_RedrawCursor (void)
void SDL_RemoveMouse (SDL_MouseID mouseID, bool send_event)
void SDL_SendMouseButton (Uint64 timestamp, SDL_Window *window, SDL_MouseID mouseID, Uint8 button, bool down)
void SDL_SendMouseButtonClicks (Uint64 timestamp, SDL_Window *window, SDL_MouseID mouseID, Uint8 button, bool down, int clicks)
void SDL_SendMouseMotion (Uint64 timestamp, SDL_Window *window, SDL_MouseID mouseID, bool relative, float x, float y)
void SDL_SendMouseWheel (Uint64 timestamp, SDL_Window *window, SDL_MouseID mouseID, float x, float y, SDL_MouseWheelDirection direction)
void SDL_SetDefaultCursor (SDL_Cursor *cursor)
void SDL_SetMouseFocus (SDL_Window *window)
bool SDL_SetRelativeMouseMode (bool enabled)
bool SDL_UpdateMouseCapture (bool force_release)
void SDL_UpdateRelativeMouseMode (void)
Macro Definition Documentation
SDL_DEFAULT_MOUSE_ID
#define SDL_DEFAULT_MOUSE_ID 1
Referenced by SDL_BLooper::_HandleMouseButton(), SDL_BLooper::_HandleMouseMove(), SDL_BLooper::_HandleMouseWheel(), and videoInit().
SDL_GLOBAL_MOUSE_ID
#define SDL_GLOBAL_MOUSE_ID 0
Referenced by SDL_GetMouseButtonState(), SDL_GetMouseState(), SDL_GetRelativeMouseState(), SDL_PerformWarpMouseInWindow(), SDL_PrivateSendMouseButton(), SDL_PrivateSendMouseMotion(), SDL_SendMouseWheel(), SDL_UpdateMouseCapture(), and SDL_UpdateMouseFocus().
Typedef Documentation
SDL_CursorData
typedef struct SDL_CursorData SDL_CursorData
Function Documentation
SDL_AddMouse()
void SDL_AddMouse (SDL_MouseID mouseID, const char * name, bool send_event) extern
{
    int mouse_index = SDL_GetMouseIndex(mouseID);
    if (mouse_index >= 0) {
        // We already know about this mouse
        return;
    }
    SDL_assert(mouseID != 0);
    SDL_MouseInstance *mice = (SDL_MouseInstance *)SDL_realloc(SDL_mice, (SDL_mouse_count + 1) * sizeof(*mice));
    if (!mice) {
        return;
    }
    SDL_MouseInstance *instance = &mice[SDL_mouse_count];
    instance->instance_id = mouseID;
    instance->name = SDL_strdup(name ? name : "");
    SDL_mice = mice;
    ++SDL_mouse_count;
    if (send_event) {
        SDL_Event event;
        SDL_zero(event);
        event.type = SDL_EVENT_MOUSE_ADDED;
        event.mdevice.which = mouseID;
        SDL_PushEvent(&event);
    }
}
References SDL_MouseInstance::instance_id, SDL_MouseInstance::name, SDL_assert, SDL_EVENT_MOUSE_ADDED, SDL_GetMouseIndex(), SDL_mice, SDL_mouse_count, SDL_PushEvent(), SDL_realloc(), SDL_strdup(), and SDL_zero.
Referenced by SDL_WSCONS_Init_Mouse(), and videoInit().
SDL_DisableMouseWarpEmulation()
void SDL_DisableMouseWarpEmulation (void) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->warp_emulation_active) {
        SDL_SetRelativeMouseMode(false);
    }
    mouse->warp_emulation_prohibited = true;
}
References SDL_GetMouse(), SDL_SetRelativeMouseMode(), SDL_Mouse::warp_emulation_active, and SDL_Mouse::warp_emulation_prohibited.
Referenced by SDL_SetWindowRelativeMouseMode().
SDL_GetDefaultSystemCursor()
SDL_SystemCursor SDL_GetDefaultSystemCursor (void) extern
{
    SDL_SystemCursor id = SDL_SYSTEM_CURSOR_DEFAULT;
    const char *value = SDL_GetHint(SDL_HINT_MOUSE_DEFAULT_SYSTEM_CURSOR);
    if (value) {
        int index = SDL_atoi(value);
        if (0 <= index && index < SDL_SYSTEM_CURSOR_COUNT) {
            id = (SDL_SystemCursor)index;
        }
    }
    return id;
}
References SDL_atoi(), SDL_GetHint(), SDL_HINT_MOUSE_DEFAULT_SYSTEM_CURSOR, SDL_SYSTEM_CURSOR_COUNT, and SDL_SYSTEM_CURSOR_DEFAULT.
SDL_GetMouse()
SDL_Mouse * SDL_GetMouse (void) extern
{
    return &SDL_mouse;
}
References SDL_mouse.
Referenced by SDL_BLooper::_HandleMouseMove(), SDL_CaptureMouse(), SDL_CreateColorCursor(), SDL_CreateSystemCursor(), SDL_CursorVisible(), SDL_DestroyCursor(), SDL_DisableMouseWarpEmulation(), SDL_GetCursor(), SDL_GetDefaultCursor(), SDL_GetGlobalMouseState(), SDL_GetMouseFocus(), SDL_GetMouseState(), SDL_GetRelativeMouseMode(), SDL_GetRelativeMouseState(), SDL_HideCursor(), SDL_MaybeEnableWarpEmulation(), SDL_OnWindowFocusGained(), SDL_PerformWarpMouseInWindow(), SDL_PostInitMouse(), SDL_PreInitMouse(), SDL_PrivateSendMouseButton(), SDL_PrivateSendMouseMotion(), SDL_QuitMouse(), SDL_RedrawCursor(), SDL_RemoveMouse(), SDL_RestoreMousePosition(), SDL_SendMouseMotion(), SDL_SendMouseWheel(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SendTouch(), SDL_SendTouchMotion(), SDL_SetCursor(), SDL_SetDefaultCursor(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_SetRelativeMouseMode(), SDL_SetRelativeMouseTransform(), SDL_ShowCursor(), SDL_UpdateMouseCapture(), SDL_UpdateMouseFocus(), SDL_UpdateRelativeMouseMode(), SDL_UpdateWindowGrab(), SDL_WarpMouseGlobal(), SDL_WarpMouseInWindow(), and updateMouse().
SDL_GetRelativeMouseMode()
bool SDL_GetRelativeMouseMode (void) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    return mouse->relative_mode;
}
References SDL_Mouse::relative_mode, and SDL_GetMouse().
SDL_IsMouse()
bool SDL_IsMouse (Uint16 vendor, Uint16 product) extern
{
    // Eventually we'll have a blacklist of devices that enumerate as mice but aren't really
    return true;
}
SDL_MousePositionInWindow()
bool SDL_MousePositionInWindow (SDL_Window * window, float x, float y) extern
{
    if (!window) {
        return false;
    }
    if (window && !(window->flags & SDL_WINDOW_MOUSE_CAPTURE)) {
        if (x < 0.0f || y < 0.0f || x >= (float)window->w || y >= (float)window->h) {
            return false;
        }
    }
    return true;
}
References SDL_WINDOW_MOUSE_CAPTURE.
Referenced by SDL_UpdateMouseFocus().
SDL_PerformWarpMouseInWindow()
void SDL_PerformWarpMouseInWindow (SDL_Window * window, float x, float y, bool ignore_relative_mode) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (!window) {
        window = mouse->focus;
    }
    if (!window) {
        return;
    }
    if ((window->flags & SDL_WINDOW_MINIMIZED) == SDL_WINDOW_MINIMIZED) {
        return;
    }
    // Ignore the previous position when we warp
    mouse->last_x = x;
    mouse->last_y = y;
    mouse->has_position = false;
    if (mouse->relative_mode && !ignore_relative_mode) {
        /* 2.0.22 made warping in relative mode actually functional, which
         * surprised many applications that weren't expecting the additional
         * mouse motion.
         *
         * So for now, warping in relative mode adjusts the absolution position
         * but doesn't generate motion events, unless SDL_HINT_MOUSE_RELATIVE_WARP_MOTION is set.
         */
        if (!mouse->relative_mode_warp_motion) {
            mouse->x = x;
            mouse->y = y;
            mouse->has_position = true;
            return;
        }
    }
    if (mouse->WarpMouse && !mouse->relative_mode) {
        mouse->WarpMouse(window, x, y);
    } else {
        SDL_PrivateSendMouseMotion(0, window, SDL_GLOBAL_MOUSE_ID, false, x, y);
    }
}
References SDL_Mouse::focus, SDL_Mouse::has_position, SDL_Mouse::last_x, SDL_Mouse::last_y, SDL_Mouse::relative_mode, SDL_Mouse::relative_mode_warp_motion, SDL_GetMouse(), SDL_GLOBAL_MOUSE_ID, SDL_PrivateSendMouseMotion(), SDL_WINDOW_MINIMIZED, SDL_Mouse::WarpMouse, SDL_Mouse::x, and SDL_Mouse::y.
Referenced by SDL_SetRelativeMouseMode(), and SDL_WarpMouseInWindow().
SDL_PostInitMouse()
void SDL_PostInitMouse (void) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    /* Create a dummy mouse cursor for video backends that don't support true cursors,
     * so that mouse grab and focus functionality will work.
     */
    if (!mouse->def_cursor) {
        SDL_Surface *surface = SDL_CreateSurface(1, 1, SDL_PIXELFORMAT_ARGB8888);
        if (surface) {
            SDL_memset(surface->pixels, 0, (size_t)surface->h * surface->pitch);
            SDL_SetDefaultCursor(SDL_CreateColorCursor(surface, 0, 0));
            SDL_DestroySurface(surface);
        }
    }
}
References SDL_Mouse::def_cursor, SDL_CreateColorCursor(), SDL_CreateSurface(), SDL_DestroySurface(), SDL_GetMouse(), SDL_memset, SDL_PIXELFORMAT_ARGB8888, and SDL_SetDefaultCursor().
Referenced by SDL_VideoInit().
SDL_PreInitMouse()
bool SDL_PreInitMouse (void) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_zerop(mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_DOUBLE_CLICK_TIME,
                        SDL_MouseDoubleClickTimeChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS,
                        SDL_MouseDoubleClickRadiusChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_NORMAL_SPEED_SCALE,
                        SDL_MouseNormalSpeedScaleChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE,
                        SDL_MouseRelativeSpeedScaleChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE,
                        SDL_MouseRelativeSystemScaleChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_RELATIVE_MODE_CENTER,
                        SDL_MouseRelativeModeCenterChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE,
                        SDL_MouseWarpEmulationChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_TOUCH_MOUSE_EVENTS,
                        SDL_TouchMouseEventsChanged, mouse);
#ifdef SDL_PLATFORM_VITA
    SDL_AddHintCallback(SDL_HINT_VITA_TOUCH_MOUSE_DEVICE,
                        SDL_VitaTouchMouseDeviceChanged, mouse);
#endif
    SDL_AddHintCallback(SDL_HINT_MOUSE_TOUCH_EVENTS,
                        SDL_MouseTouchEventsChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_PEN_MOUSE_EVENTS,
                        SDL_PenMouseEventsChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_PEN_TOUCH_EVENTS,
                        SDL_PenTouchEventsChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_AUTO_CAPTURE,
                        SDL_MouseAutoCaptureChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_RELATIVE_WARP_MOTION,
                        SDL_MouseRelativeWarpMotionChanged, mouse);
    SDL_AddHintCallback(SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE,
                        SDL_MouseRelativeCursorVisibleChanged, mouse);
    SDL_AddHintCallback("SDL_MOUSE_INTEGER_MODE",
                        SDL_MouseIntegerModeChanged, mouse);
    mouse->was_touch_mouse_events = false; // no touch to mouse movement event pending
    mouse->cursor_visible = true;
    return true;
}
References SDL_Mouse::cursor_visible, SDL_AddHintCallback(), SDL_GetMouse(), SDL_HINT_MOUSE_AUTO_CAPTURE, SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS, SDL_HINT_MOUSE_DOUBLE_CLICK_TIME, SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE, SDL_HINT_MOUSE_NORMAL_SPEED_SCALE, SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE, SDL_HINT_MOUSE_RELATIVE_MODE_CENTER, SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE, SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE, SDL_HINT_MOUSE_RELATIVE_WARP_MOTION, SDL_HINT_MOUSE_TOUCH_EVENTS, SDL_HINT_PEN_MOUSE_EVENTS, SDL_HINT_PEN_TOUCH_EVENTS, SDL_HINT_TOUCH_MOUSE_EVENTS, SDL_HINT_VITA_TOUCH_MOUSE_DEVICE, SDL_MouseAutoCaptureChanged(), SDL_MouseDoubleClickRadiusChanged(), SDL_MouseDoubleClickTimeChanged(), SDL_MouseIntegerModeChanged(), SDL_MouseNormalSpeedScaleChanged(), SDL_MouseRelativeCursorVisibleChanged(), SDL_MouseRelativeModeCenterChanged(), SDL_MouseRelativeSpeedScaleChanged(), SDL_MouseRelativeSystemScaleChanged(), SDL_MouseRelativeWarpMotionChanged(), SDL_MouseTouchEventsChanged(), SDL_MouseWarpEmulationChanged(), SDL_PenMouseEventsChanged(), SDL_PenTouchEventsChanged(), SDL_TouchMouseEventsChanged(), SDL_zerop, and SDL_Mouse::was_touch_mouse_events.
Referenced by SDL_VideoInit().
SDL_QuitMouse()
void SDL_QuitMouse (void) extern
{
    SDL_Cursor *cursor, *next;
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->added_mouse_touch_device) {
        SDL_DelTouch(SDL_MOUSE_TOUCHID);
        mouse->added_mouse_touch_device = false;
    }
    if (mouse->added_pen_touch_device) {
        SDL_DelTouch(SDL_PEN_TOUCHID);
        mouse->added_pen_touch_device = false;
    }
    if (mouse->CaptureMouse) {
        SDL_CaptureMouse(false);
        SDL_UpdateMouseCapture(true);
    }
    SDL_SetRelativeMouseMode(false);
    SDL_ShowCursor();
    if (mouse->def_cursor) {
        SDL_SetDefaultCursor(NULL);
    }
    cursor = mouse->cursors;
    while (cursor) {
        next = cursor->next;
        SDL_DestroyCursor(cursor);
        cursor = next;
    }
    mouse->cursors = NULL;
    mouse->cur_cursor = NULL;
    if (mouse->sources) {
        for (int i = 0; i < mouse->num_sources; ++i) {
            SDL_MouseInputSource *source = &mouse->sources[i];
            SDL_free(source->clickstate);
        }
        SDL_free(mouse->sources);
        mouse->sources = NULL;
    }
    mouse->num_sources = 0;
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_DOUBLE_CLICK_TIME,
                        SDL_MouseDoubleClickTimeChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS,
                        SDL_MouseDoubleClickRadiusChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_NORMAL_SPEED_SCALE,
                        SDL_MouseNormalSpeedScaleChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE,
                        SDL_MouseRelativeSpeedScaleChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE,
                        SDL_MouseRelativeSystemScaleChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_RELATIVE_MODE_CENTER,
                        SDL_MouseRelativeModeCenterChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE,
                        SDL_MouseWarpEmulationChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_TOUCH_MOUSE_EVENTS,
                        SDL_TouchMouseEventsChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_TOUCH_EVENTS,
                        SDL_MouseTouchEventsChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_PEN_MOUSE_EVENTS,
                        SDL_PenMouseEventsChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_PEN_TOUCH_EVENTS,
                        SDL_PenTouchEventsChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_AUTO_CAPTURE,
                        SDL_MouseAutoCaptureChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_RELATIVE_WARP_MOTION,
                        SDL_MouseRelativeWarpMotionChanged, mouse);
    SDL_RemoveHintCallback(SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE,
                        SDL_MouseRelativeCursorVisibleChanged, mouse);
    SDL_RemoveHintCallback("SDL_MOUSE_INTEGER_MODE",
                        SDL_MouseIntegerModeChanged, mouse);
    for (int i = SDL_mouse_count; i--; ) {
        SDL_RemoveMouse(SDL_mice[i].instance_id, false);
    }
    SDL_free(SDL_mice);
    SDL_mice = NULL;
}
References SDL_Mouse::added_mouse_touch_device, SDL_Mouse::added_pen_touch_device, SDL_Mouse::CaptureMouse, SDL_MouseInputSource::clickstate, SDL_Mouse::cur_cursor, SDL_Mouse::cursors, SDL_Mouse::def_cursor, SDL_Cursor::next, NULL, SDL_Mouse::num_sources, SDL_CaptureMouse(), SDL_DelTouch(), SDL_DestroyCursor(), SDL_free(), SDL_GetMouse(), SDL_HINT_MOUSE_AUTO_CAPTURE, SDL_HINT_MOUSE_DOUBLE_CLICK_RADIUS, SDL_HINT_MOUSE_DOUBLE_CLICK_TIME, SDL_HINT_MOUSE_EMULATE_WARP_WITH_RELATIVE, SDL_HINT_MOUSE_NORMAL_SPEED_SCALE, SDL_HINT_MOUSE_RELATIVE_CURSOR_VISIBLE, SDL_HINT_MOUSE_RELATIVE_MODE_CENTER, SDL_HINT_MOUSE_RELATIVE_SPEED_SCALE, SDL_HINT_MOUSE_RELATIVE_SYSTEM_SCALE, SDL_HINT_MOUSE_RELATIVE_WARP_MOTION, SDL_HINT_MOUSE_TOUCH_EVENTS, SDL_HINT_PEN_MOUSE_EVENTS, SDL_HINT_PEN_TOUCH_EVENTS, SDL_HINT_TOUCH_MOUSE_EVENTS, SDL_mice, SDL_mouse_count, SDL_MOUSE_TOUCHID, SDL_MouseAutoCaptureChanged(), SDL_MouseDoubleClickRadiusChanged(), SDL_MouseDoubleClickTimeChanged(), SDL_MouseIntegerModeChanged(), SDL_MouseNormalSpeedScaleChanged(), SDL_MouseRelativeCursorVisibleChanged(), SDL_MouseRelativeModeCenterChanged(), SDL_MouseRelativeSpeedScaleChanged(), SDL_MouseRelativeSystemScaleChanged(), SDL_MouseRelativeWarpMotionChanged(), SDL_MouseTouchEventsChanged(), SDL_MouseWarpEmulationChanged(), SDL_PEN_TOUCHID, SDL_PenMouseEventsChanged(), SDL_PenTouchEventsChanged(), SDL_RemoveHintCallback(), SDL_RemoveMouse(), SDL_SetDefaultCursor(), SDL_SetRelativeMouseMode(), SDL_ShowCursor(), SDL_TouchMouseEventsChanged(), SDL_UpdateMouseCapture(), and SDL_Mouse::sources.
Referenced by SDL_VideoInit(), and SDL_VideoQuit().
SDL_RedrawCursor()
void SDL_RedrawCursor (void) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_Cursor *cursor;
    if (mouse->focus) {
        cursor = mouse->cur_cursor;
    } else {
        cursor = mouse->def_cursor;
    }
    if (mouse->focus && (!mouse->cursor_visible || (mouse->relative_mode && mouse->relative_mode_hide_cursor))) {
        cursor = NULL;
    }
    if (mouse->ShowCursor) {
        mouse->ShowCursor(cursor);
    }
}
References SDL_Mouse::cur_cursor, SDL_Mouse::cursor_visible, SDL_Mouse::def_cursor, SDL_Mouse::focus, NULL, SDL_Mouse::relative_mode, SDL_Mouse::relative_mode_hide_cursor, SDL_GetMouse(), and SDL_Mouse::ShowCursor.
Referenced by SDL_HideCursor(), SDL_MouseRelativeCursorVisibleChanged(), SDL_SetCursor(), SDL_SetMouseFocus(), SDL_SetRelativeMouseMode(), and SDL_ShowCursor().
SDL_RemoveMouse()
void SDL_RemoveMouse (SDL_MouseID mouseID, bool send_event) extern
{
    int mouse_index = SDL_GetMouseIndex(mouseID);
    if (mouse_index < 0) {
        // We don't know about this mouse
        return;
    }
    SDL_free(SDL_mice[mouse_index].name);
    if (mouse_index != SDL_mouse_count - 1) {
        SDL_memmove(&SDL_mice[mouse_index], &SDL_mice[mouse_index + 1], (SDL_mouse_count - mouse_index - 1) * sizeof(SDL_mice[mouse_index]));
    }
    --SDL_mouse_count;
    // Remove any mouse input sources for this mouseID
    SDL_Mouse *mouse = SDL_GetMouse();
    for (int i = 0; i < mouse->num_sources; ++i) {
        SDL_MouseInputSource *source = &mouse->sources[i];
        if (source->mouseID == mouseID) {
            SDL_free(source->clickstate);
            if (i != mouse->num_sources - 1) {
                SDL_memmove(&mouse->sources[i], &mouse->sources[i + 1], (mouse->num_sources - i - 1) * sizeof(mouse->sources[i]));
            }
            --mouse->num_sources;
            break;
        }
    }
    if (send_event) {
        SDL_Event event;
        SDL_zero(event);
        event.type = SDL_EVENT_MOUSE_REMOVED;
        event.mdevice.which = mouseID;
        SDL_PushEvent(&event);
    }
}
References SDL_MouseInputSource::clickstate, SDL_MouseInputSource::mouseID, SDL_Mouse::num_sources, SDL_EVENT_MOUSE_REMOVED, SDL_free(), SDL_GetMouse(), SDL_GetMouseIndex(), SDL_memmove, SDL_mice, SDL_mouse_count, SDL_PushEvent(), SDL_zero, and SDL_Mouse::sources.
Referenced by SDL_QuitMouse().
SDL_SendMouseButton()
void SDL_SendMouseButton (Uint64 timestamp, SDL_Window * window, SDL_MouseID mouseID, Uint8 button, bool down) extern
{
    SDL_PrivateSendMouseButton(timestamp, window, mouseID, button, down, -1);
}
References SDL_PrivateSendMouseButton().
Referenced by SDL_BLooper::_HandleMouseButton(), SDL_SendPenButton(), SDL_SendPenTouch(), SDL_SendTouch(), and updateMouse().
SDL_SendMouseButtonClicks()
void SDL_SendMouseButtonClicks (Uint64 timestamp, SDL_Window * window, SDL_MouseID mouseID, Uint8 button, bool down, int clicks) extern
{
    clicks = SDL_max(clicks, 0);
    SDL_PrivateSendMouseButton(timestamp, window, mouseID, button, down, clicks);
}
References SDL_max, and SDL_PrivateSendMouseButton().
SDL_SendMouseMotion()
void SDL_SendMouseMotion (Uint64 timestamp, SDL_Window * window, SDL_MouseID mouseID, bool relative, float x, float y) extern
{
    if (window && !relative) {
        SDL_Mouse *mouse = SDL_GetMouse();
        if (!SDL_UpdateMouseFocus(window, x, y, SDL_GetMouseButtonState(mouse, mouseID, true), (mouseID != SDL_TOUCH_MOUSEID && mouseID != SDL_PEN_MOUSEID))) {
            return;
        }
    }
    SDL_PrivateSendMouseMotion(timestamp, window, mouseID, relative, x, y);
}
References SDL_GetMouse(), SDL_GetMouseButtonState(), SDL_PEN_MOUSEID, SDL_PrivateSendMouseMotion(), SDL_TOUCH_MOUSEID, and SDL_UpdateMouseFocus().
Referenced by SDL_BLooper::_HandleMouseMove(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SendTouch(), SDL_SendTouchMotion(), and updateMouse().
SDL_SendMouseWheel()
void SDL_SendMouseWheel (Uint64 timestamp, SDL_Window * window, SDL_MouseID mouseID, float x, float y, SDL_MouseWheelDirection direction) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (window) {
        SDL_SetMouseFocus(window);
    }
    if (x == 0.0f && y == 0.0f) {
        return;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_MOUSE_WHEEL)) {
        float integer_x, integer_y;
        if (!mouse->relative_mode || mouse->warp_emulation_active) {
            // We're not in relative mode, so all mouse events are global mouse events
            mouseID = SDL_GLOBAL_MOUSE_ID;
        }
        SDL_Event event;
        event.type = SDL_EVENT_MOUSE_WHEEL;
        event.common.timestamp = timestamp;
        event.wheel.windowID = mouse->focus ? mouse->focus->id : 0;
        event.wheel.which = mouseID;
        event.wheel.direction = direction;
        event.wheel.mouse_x = mouse->x;
        event.wheel.mouse_y = mouse->y;
        mouse->residual_scroll_x = SDL_modff(mouse->residual_scroll_x + x, &integer_x);
        event.wheel.integer_x = (Sint32)integer_x;
        mouse->residual_scroll_y = SDL_modff(mouse->residual_scroll_y + y, &integer_y);
        event.wheel.integer_y = (Sint32)integer_y;
        // Return the accumulated values in x/y when integer wheel mode is enabled.
        // This is necessary for compatibility with sdl2-compat 2.32.54.
        if (mouse->integer_mode_flags & 2) {
            event.wheel.x = integer_x;
            event.wheel.y = integer_y;
        } else {
            event.wheel.x = x;
            event.wheel.y = y;
        }
        SDL_PushEvent(&event);
    }
}
References SDL_Mouse::focus, SDL_Window::id, SDL_Mouse::integer_mode_flags, SDL_Mouse::relative_mode, SDL_Mouse::residual_scroll_x, SDL_Mouse::residual_scroll_y, SDL_EVENT_MOUSE_WHEEL, SDL_EventEnabled(), SDL_GetMouse(), SDL_GLOBAL_MOUSE_ID, SDL_modff(), SDL_PushEvent(), SDL_SetMouseFocus(), SDL_Mouse::warp_emulation_active, SDL_Mouse::x, and SDL_Mouse::y.
Referenced by SDL_BLooper::_HandleMouseWheel(), and updateMouse().
SDL_SetDefaultCursor()
void SDL_SetDefaultCursor (SDL_Cursor * cursor) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (cursor == mouse->def_cursor) {
        return;
    }
    if (mouse->def_cursor) {
        SDL_Cursor *default_cursor = mouse->def_cursor;
        SDL_Cursor *prev, *curr;
        if (mouse->cur_cursor == mouse->def_cursor) {
            mouse->cur_cursor = NULL;
        }
        mouse->def_cursor = NULL;
        for (prev = NULL, curr = mouse->cursors; curr;
             prev = curr, curr = curr->next) {
            if (curr == default_cursor) {
                if (prev) {
                    prev->next = curr->next;
                } else {
                    mouse->cursors = curr->next;
                }
                break;
            }
        }
        if (mouse->FreeCursor && default_cursor->internal) {
            mouse->FreeCursor(default_cursor);
        } else {
            SDL_free(default_cursor);
        }
    }
    mouse->def_cursor = cursor;
    if (!mouse->cur_cursor) {
        SDL_SetCursor(cursor);
    }
}
References SDL_Mouse::cur_cursor, SDL_Mouse::cursors, SDL_Mouse::def_cursor, SDL_Mouse::FreeCursor, SDL_Cursor::internal, SDL_Cursor::next, NULL, SDL_free(), SDL_GetMouse(), and SDL_SetCursor().
Referenced by SDL_PostInitMouse(), and SDL_QuitMouse().
SDL_SetMouseFocus()
void SDL_SetMouseFocus (SDL_Window * window) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse->focus == window) {
        return;
    }
    /* Actually, this ends up being a bad idea, because most operating
       systems have an implicit grab when you press the mouse button down
       so you can drag things out of the window and then get the mouse up
       when it happens.  So, #if 0...
    */
#if 0
    if (mouse->focus && !window) {
        // We won't get anymore mouse messages, so reset mouse state
        SDL_ResetMouse();
    }
#endif
    // See if the current window has lost focus
    if (mouse->focus) {
        SDL_SendWindowEvent(mouse->focus, SDL_EVENT_WINDOW_MOUSE_LEAVE, 0, 0);
    }
    mouse->focus = window;
    mouse->has_position = false;
    if (mouse->focus) {
        SDL_SendWindowEvent(mouse->focus, SDL_EVENT_WINDOW_MOUSE_ENTER, 0, 0);
    }
    // Update cursor visibility
    SDL_RedrawCursor();
}
References SDL_Mouse::focus, SDL_Mouse::has_position, SDL_EVENT_WINDOW_MOUSE_ENTER, SDL_EVENT_WINDOW_MOUSE_LEAVE, SDL_GetMouse(), SDL_RedrawCursor(), and SDL_SendWindowEvent().
Referenced by SDL_BLooper::_HandleMouseFocus(), SDL_DestroyWindow(), SDL_HideWindow(), SDL_OnWindowFocusGained(), SDL_SendMouseWheel(), SDL_SetRelativeMouseMode(), SDL_ShowWindow(), and SDL_UpdateMouseFocus().
SDL_SetRelativeMouseMode()
bool SDL_SetRelativeMouseMode (bool enabled) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_Window *focusWindow = SDL_GetKeyboardFocus();
    if (!enabled) {
        // If warps were being emulated, reset the flag.
        mouse->warp_emulation_active = false;
    }
    if (enabled == mouse->relative_mode) {
        return true;
    }
    // Set the relative mode
    if (!mouse->SetRelativeMouseMode || !mouse->SetRelativeMouseMode(enabled)) {
        if (enabled) {
            return SDL_SetError("No relative mode implementation available");
        }
    }
    mouse->relative_mode = enabled;
    if (enabled) {
        // Update cursor visibility before we potentially warp the mouse
        SDL_RedrawCursor();
    }
    if (enabled && focusWindow) {
        SDL_SetMouseFocus(focusWindow);
    }
    if (focusWindow) {
        SDL_UpdateWindowGrab(focusWindow);
        // Put the cursor back to where the application expects it
        if (!enabled) {
            SDL_PerformWarpMouseInWindow(focusWindow, mouse->x, mouse->y, true);
        }
        SDL_UpdateMouseCapture(false);
    }
    if (!enabled) {
        // Update cursor visibility after we restore the mouse position
        SDL_RedrawCursor();
    }
    // Flush pending mouse motion - ideally we would pump events, but that's not always safe
    SDL_FlushEvent(SDL_EVENT_MOUSE_MOTION);
    return true;
}
References SDL_Mouse::relative_mode, SDL_EVENT_MOUSE_MOTION, SDL_FlushEvent(), SDL_GetKeyboardFocus(), SDL_GetMouse(), SDL_PerformWarpMouseInWindow(), SDL_RedrawCursor(), SDL_SetError(), SDL_SetMouseFocus(), SDL_UpdateMouseCapture(), SDL_UpdateWindowGrab(), SDL_Mouse::SetRelativeMouseMode, SDL_Mouse::warp_emulation_active, SDL_Mouse::x, and SDL_Mouse::y.
Referenced by SDL_DisableMouseWarpEmulation(), SDL_MaybeEnableWarpEmulation(), SDL_MouseWarpEmulationChanged(), SDL_QuitMouse(), SDL_SetKeyboardFocus(), SDL_ShowCursor(), SDL_ShowMessageBox(), and SDL_UpdateRelativeMouseMode().
SDL_UpdateMouseCapture()
bool SDL_UpdateMouseCapture (bool force_release) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_Window *capture_window = NULL;
    if (!mouse->CaptureMouse) {
        return true;
    }
    if (!force_release) {
        if (SDL_GetMessageBoxCount() == 0 &&
            (mouse->capture_desired || (mouse->auto_capture && SDL_GetMouseButtonState(mouse, SDL_GLOBAL_MOUSE_ID, false) != 0))) {
            if (!mouse->relative_mode) {
                capture_window = mouse->focus;
            }
        }
    }
    if (capture_window != mouse->capture_window) {
        /* We can get here recursively on Windows, so make sure we complete
         * all of the window state operations before we change the capture state
         * (e.g. https://github.com/libsdl-org/SDL/pull/5608)
         */
        SDL_Window *previous_capture = mouse->capture_window;
        if (previous_capture) {
            previous_capture->flags &= ~SDL_WINDOW_MOUSE_CAPTURE;
        }
        if (capture_window) {
            capture_window->flags |= SDL_WINDOW_MOUSE_CAPTURE;
        }
        mouse->capture_window = capture_window;
        if (!mouse->CaptureMouse(capture_window)) {
            // CaptureMouse() will have set an error, just restore the state
            if (previous_capture) {
                previous_capture->flags |= SDL_WINDOW_MOUSE_CAPTURE;
            }
            if (capture_window) {
                capture_window->flags &= ~SDL_WINDOW_MOUSE_CAPTURE;
            }
            mouse->capture_window = previous_capture;
            return false;
        }
    }
    return true;
}
References SDL_Mouse::auto_capture, SDL_Mouse::capture_desired, SDL_Mouse::capture_window, SDL_Mouse::CaptureMouse, SDL_Window::flags, SDL_Mouse::focus, NULL, SDL_Mouse::relative_mode, SDL_GetMessageBoxCount(), SDL_GetMouse(), SDL_GetMouseButtonState(), SDL_GLOBAL_MOUSE_ID, and SDL_WINDOW_MOUSE_CAPTURE.
Referenced by SDL_CaptureMouse(), SDL_DestroyWindow(), SDL_MouseAutoCaptureChanged(), SDL_PrivateSendMouseButton(), SDL_QuitMouse(), SDL_SetRelativeMouseMode(), and SDL_ShowMessageBox().
SDL_UpdateRelativeMouseMode()
void SDL_UpdateRelativeMouseMode (void) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    SDL_Window *focus = SDL_GetKeyboardFocus();
    bool relative_mode = (focus && (focus->flags & SDL_WINDOW_MOUSE_RELATIVE_MODE));
    if (relative_mode != mouse->relative_mode) {
        SDL_SetRelativeMouseMode(relative_mode);
    }
}
References SDL_Window::flags, SDL_Mouse::relative_mode, SDL_GetKeyboardFocus(), SDL_GetMouse(), SDL_SetRelativeMouseMode(), and SDL_WINDOW_MOUSE_RELATIVE_MODE.
Referenced by SDL_SetKeyboardFocus(), SDL_SetWindowRelativeMouseMode(), and SDL_ShowMessageBox().