SDL3: SDL-main/src/dialog/unix/SDL_unixdialog.c File Reference
SDL_unixdialog.c File Reference
#include "SDL_internal.h"
#include "../SDL_dialog.h"
#include "./SDL_portaldialog.h"
#include "./SDL_zenitydialog.h"
Functions
static int detect_available_methods (const char *value)
void SDLCALL hint_callback (void *userdata, const char *name, const char *oldValue, const char *newValue)
void SDL_SYS_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props)
static void set_callback (void)
Variables
static void(* detected_function)(SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props) = NULL
Function Documentation
detect_available_methods()
int detect_available_methods (const char * value) static
{
    const char *driver = value ? value : SDL_GetHint(SDL_HINT_FILE_DIALOG_DRIVER);
    set_callback();
    if (driver == NULL || SDL_strcmp(driver, "portal") == 0) {
        if (SDL_Portal_detect()) {
            detected_function = SDL_Portal_ShowFileDialogWithProperties;
            return 1;
        }
    }
    if (driver == NULL || SDL_strcmp(driver, "zenity") == 0) {
        if (SDL_Zenity_detect()) {
            detected_function = SDL_Zenity_ShowFileDialogWithProperties;
            return 2;
        }
    }
    SDL_SetError("File dialog driver unsupported (supported values for SDL_HINT_FILE_DIALOG_DRIVER are 'zenity' and 'portal')");
    return 0;
}
References detected_function, NULL, SDL_GetHint(), SDL_HINT_FILE_DIALOG_DRIVER, SDL_Portal_detect(), SDL_Portal_ShowFileDialogWithProperties(), SDL_SetError(), SDL_strcmp(), SDL_Zenity_detect(), SDL_Zenity_ShowFileDialogWithProperties(), and set_callback().
Referenced by hint_callback(), and SDL_SYS_ShowFileDialogWithProperties().
hint_callback()
void SDLCALL hint_callback (void * userdata, const char * name, const char * oldValue, const char * newValue)
{
    detect_available_methods(newValue);
}
References detect_available_methods(), and SDLCALL.
Referenced by set_callback().
SDL_SYS_ShowFileDialogWithProperties()
void SDL_SYS_ShowFileDialogWithProperties (SDL_FileDialogType type, SDL_DialogFileCallback callback, void * userdata, SDL_PropertiesID props)
{
    // Call detect_available_methods() again each time in case the situation changed
    if (!detected_function && !detect_available_methods(NULL)) {
        // SetError() done by detect_available_methods()
        callback(userdata, NULL, -1);
        return;
    }
    detected_function(type, callback, userdata, props);
}
References detect_available_methods(), detected_function, and NULL.
set_callback()
void set_callback (void) static
{
    static bool is_set = false;
    if (is_set == false) {
        is_set = true;
        SDL_AddHintCallback(SDL_HINT_FILE_DIALOG_DRIVER, hint_callback, NULL);
    }
}
References hint_callback(), NULL, SDL_AddHintCallback(), and SDL_HINT_FILE_DIALOG_DRIVER.
Referenced by detect_available_methods().
Variable Documentation
detected_function
void(* detected_function) (SDL_FileDialogType type, SDL_DialogFileCallback callback, void *userdata, SDL_PropertiesID props) (SDL_FileDialogType type, SDL_DialogFileCallback callback, void * userdata, SDL_PropertiesID props) = NULL static
Referenced by detect_available_methods(), and SDL_SYS_ShowFileDialogWithProperties().