SDL3: SDL-main/src/video/SDL_video_c.h File Reference
SDL_video_c.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_AddWindowRenderer (SDL_Window *window, SDL_Renderer *renderer)
void SDL_RemoveWindowRenderer (SDL_Window *window, SDL_Renderer *renderer)
bool SDL_SetWindowTextureVSync (struct SDL_VideoDevice *_this, SDL_Window *window, int vsync)
bool SDL_VideoInit (const char *driver_name)
void SDL_VideoQuit (void)
Function Documentation
SDL_AddWindowRenderer()
bool SDL_AddWindowRenderer (SDL_Window * window, SDL_Renderer * renderer) extern
{
    SDL_Renderer **renderers = (SDL_Renderer **)SDL_realloc(window->renderers, (window->num_renderers + 1) * sizeof(*renderers));
    if (!renderers) {
        return false;
    }
    window->renderers = renderers;
    window->renderers[window->num_renderers++] = renderer;
    return true;
}
References SDL_realloc().
Referenced by SDL_CreateRendererWithProperties().
SDL_RemoveWindowRenderer()
void SDL_RemoveWindowRenderer (SDL_Window * window, SDL_Renderer * renderer) extern
{
    for (int i = 0; i < window->num_renderers; ++i) {
        if (window->renderers[i] == renderer) {
            if (i < (window->num_renderers - 1)) {
                SDL_memmove(&window->renderers[i], &window->renderers[i + 1], (window->num_renderers - i - 1) * sizeof(window->renderers[i]));
            }
            --window->num_renderers;
            break;
        }
    }
}
References SDL_memmove.
Referenced by SDL_DestroyRendererWithoutFreeing().
SDL_SetWindowTextureVSync()
bool SDL_SetWindowTextureVSync (struct SDL_VideoDevice * _this, SDL_Window * window, int vsync) extern
{
    SDL_WindowTextureData *data;
    data = (SDL_WindowTextureData *)SDL_GetPointerProperty(SDL_GetWindowProperties(window), SDL_PROP_WINDOW_TEXTUREDATA_POINTER, NULL);
    if (!data) {
        return false;
    }
    if (!data->renderer) {
        return false;
    }
    return SDL_SetRenderVSync(data->renderer, vsync);
}
References _this, NULL, SDL_GetPointerProperty(), SDL_GetWindowProperties(), SDL_PROP_WINDOW_TEXTUREDATA_POINTER, and SDL_SetRenderVSync().
Referenced by SDL_CreateWindowFramebuffer(), and SDL_SetRenderVSync().
SDL_VideoInit()
bool SDL_VideoInit (const char * driver_name) extern
Initialize the video subsystem, optionally specifying a video driver.
This function initializes the video subsystem, setting up a connection to the window manager, etc, and determines the available display modes and pixel formats, but does not initialize a window or graphics mode.
If you use this function and you haven't used the SDL_INIT_VIDEO flag with either SDL_Init() or SDL_InitSubSystem(), you should call SDL_VideoQuit() before calling SDL_Quit().
It is safe to call this function multiple times. SDL_VideoInit() will call SDL_VideoQuit() itself if the video subsystem has already been initialized.
You can use SDL_GetNumVideoDrivers() and SDL_GetVideoDriver() to find a specific driver_name.
Parameters
driver_name the name of a video driver to initialize, or NULL for the default driver
Returns
true on success or false on failure; call SDL_GetError() for more information.
{
    SDL_VideoDevice *video;
    bool init_events = false;
    bool init_keyboard = false;
    bool init_mouse = false;
    bool init_touch = false;
    bool init_pen = false;
    int i = 0;
    // Check to make sure we don't overwrite '_this'
    if (_this) {
        SDL_VideoQuit();
    }
    SDL_InitTicks();
    // Start the event loop
    if (!SDL_InitSubSystem(SDL_INIT_EVENTS)) {
        goto pre_driver_error;
    }
    init_events = true;
    if (!SDL_InitKeyboard()) {
        goto pre_driver_error;
    }
    init_keyboard = true;
    if (!SDL_PreInitMouse()) {
        goto pre_driver_error;
    }
    init_mouse = true;
    if (!SDL_InitTouch()) {
        goto pre_driver_error;
    }
    init_touch = true;
    if (!SDL_InitPen()) {
        goto pre_driver_error;
    }
    init_pen = true;
    // Select the proper video driver
    video = NULL;
    if (!driver_name) {
        driver_name = SDL_GetHint(SDL_HINT_VIDEO_DRIVER);
    }
    if (driver_name && *driver_name != 0) {
        const char *driver_attempt = driver_name;
        while (driver_attempt && *driver_attempt != 0 && !video) {
            const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
            for (i = 0; bootstrap[i]; ++i) {
                if (!bootstrap[i]->is_preferred &&
                    (driver_attempt_len == SDL_strlen(bootstrap[i]->name)) &&
                    (SDL_strncasecmp(bootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                    video = bootstrap[i]->create();
                    if (video) {
                        break;
                    }
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
    } else {
        for (i = 0; bootstrap[i]; ++i) {
            video = bootstrap[i]->create();
            if (video) {
                break;
            }
        }
    }
    if (video) {
        SDL_DebugLogBackend("video", bootstrap[i]->name);
    } else {
        if (driver_name) {
            SDL_SetError("%s not available", driver_name);
            goto pre_driver_error;
        }
        SDL_SetError("No available video device");
        goto pre_driver_error;
    }
    /* From this point on, use SDL_VideoQuit to cleanup on error, rather than
    pre_driver_error. */
    _this = video;
    _this->name = bootstrap[i]->name;
    _this->thread = SDL_GetCurrentThreadID();
    // Set some very sane GL defaults
    _this->gl_config.driver_loaded = 0;
    _this->gl_config.dll_handle = NULL;
    SDL_GL_ResetAttributes();
    // Initialize the video subsystem
    if (!_this->VideoInit(_this)) {
        SDL_VideoQuit();
        return false;
    }
    // Make sure some displays were added
    if (_this->num_displays == 0) {
        SDL_VideoQuit();
        return SDL_SetError("The video driver did not add any displays");
    }
    SDL_AddHintCallback(SDL_HINT_VIDEO_SYNC_WINDOW_OPERATIONS, SDL_SyncHintWatcher, NULL);
    /* Disable the screen saver by default. This is a change from <= 2.0.1,
       but most things using SDL are games or media players; you wouldn't
       want a screensaver to trigger if you're playing exclusively with a
       joystick, or passively watching a movie. Things that use SDL but
       function more like a normal desktop app should explicitly reenable the
       screensaver. */
    if (!SDL_GetHintBoolean(SDL_HINT_VIDEO_ALLOW_SCREENSAVER, false)) {
        SDL_DisableScreenSaver();
    }
    SDL_PostInitMouse();
    // We're ready to go!
    return true;
pre_driver_error:
    SDL_assert(_this == NULL);
    if (init_pen) {
        SDL_QuitPen();
    }
    if (init_touch) {
        SDL_QuitTouch();
    }
    if (init_mouse) {
        SDL_QuitMouse();
    }
    if (init_keyboard) {
        SDL_QuitKeyboard();
    }
    if (init_events) {
        SDL_QuitSubSystem(SDL_INIT_EVENTS);
    }
    return false;
}
References _this, bootstrap, NULL, SDL_AddHintCallback(), SDL_assert, SDL_DebugLogBackend(), SDL_DisableScreenSaver(), SDL_GetCurrentThreadID(), SDL_GetHint(), SDL_GetHintBoolean(), SDL_GL_ResetAttributes(), SDL_HINT_VIDEO_ALLOW_SCREENSAVER, SDL_HINT_VIDEO_DRIVER, SDL_HINT_VIDEO_SYNC_WINDOW_OPERATIONS, SDL_INIT_EVENTS, SDL_InitKeyboard(), SDL_InitPen(), SDL_InitSubSystem(), SDL_InitTicks(), SDL_InitTouch(), SDL_PostInitMouse(), SDL_PreInitMouse(), SDL_QuitKeyboard(), SDL_QuitMouse(), SDL_QuitPen(), SDL_QuitSubSystem(), SDL_QuitTouch(), SDL_SetError(), SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), SDL_SyncHintWatcher(), and SDL_VideoQuit().
Referenced by SDL_InitSubSystem().
SDL_VideoQuit()
void SDL_VideoQuit (void) extern
Shut down the video subsystem, if initialized with SDL_VideoInit().
This function closes all windows, and restores the original video mode.
{
    int i;
    if (!_this) {
        return;
    }
    // Halt event processing before doing anything else
#if 0 // This was moved to the end to fix a memory leak
    SDL_QuitPen();
#endif
    SDL_QuitTouch();
    SDL_QuitMouse();
    SDL_QuitKeyboard();
    SDL_QuitSubSystem(SDL_INIT_EVENTS);
    SDL_EnableScreenSaver();
    // Clean up the system video
    while (_this->windows) {
        SDL_DestroyWindow(_this->windows);
    }
    _this->VideoQuit(_this);
    for (i = _this->num_displays; i--; ) {
        SDL_VideoDisplay *display = _this->displays[i];
        SDL_DelVideoDisplay(display->id, false);
    }
    SDL_assert(_this->num_displays == 0);
    SDL_free(_this->displays);
    _this->displays = NULL;
    SDL_CancelClipboardData(0);
    if (_this->primary_selection_text) {
        SDL_free(_this->primary_selection_text);
        _this->primary_selection_text = NULL;
    }
    _this->free(_this);
    _this = NULL;
    // This needs to happen after the video subsystem has removed pen data
    SDL_QuitPen();
}
References _this, NULL, SDL_assert, SDL_CancelClipboardData(), SDL_DelVideoDisplay(), SDL_DestroyWindow(), SDL_EnableScreenSaver(), SDL_free(), SDL_INIT_EVENTS, SDL_QuitKeyboard(), SDL_QuitMouse(), SDL_QuitPen(), SDL_QuitSubSystem(), and SDL_QuitTouch().
Referenced by SDL_QuitSubSystem(), and SDL_VideoInit().