SDL3: SDL-main/src/audio/SDL_audioresample.c File Reference
SDL_audioresample.c File Reference
#include "SDL_internal.h"
#include "SDL_sysaudio.h"
#include "SDL_audioresample.h"
Data Structures
union Cubic
Macros
#define RESAMPLER_BITS_PER_ZERO_CROSSING 3
#define RESAMPLER_FILTER_INTERP_BITS (32 - RESAMPLER_BITS_PER_ZERO_CROSSING)
#define RESAMPLER_FILTER_INTERP_RANGE (1 << RESAMPLER_FILTER_INTERP_BITS)
#define RESAMPLER_MAX_PADDING_FRAMES (RESAMPLER_ZERO_CROSSINGS + 1)
#define RESAMPLER_SAMPLES_PER_FRAME (RESAMPLER_ZERO_CROSSINGS * 2)
#define RESAMPLER_SAMPLES_PER_ZERO_CROSSING (1 << RESAMPLER_BITS_PER_ZERO_CROSSING)
#define RESAMPLER_ZERO_CROSSINGS 5
Typedefs
typedef union Cubic Cubic
typedef void(* ResampleFrameFunc) (const float *src, float *dst, const Cubic *filter, float frac, int chans)
Functions
static float BesselI0 (float x)
static void CubicLeastSquares (Cubic *coeffs, float y0, float y1, float y2, float y3)
static void GenerateResamplerFilter (void)
static void ResampleFrame_Generic (const float *src, float *dst, const Cubic *filter, float frac, int chans)
static void ResampleFrame_Mono (const float *src, float *dst, const Cubic *filter, float frac, int chans)
static void ResampleFrame_Stereo (const float *src, float *dst, const Cubic *filter, float frac, int chans)
SDL_FORCE_INLINE bool ResamplerAdd (Sint64 a, Sint64 b, Sint64 *ret)
SDL_FORCE_INLINE bool ResamplerMul (Sint64 a, Sint64 b, Sint64 *ret)
Sint64 SDL_GetResampleRate (int src_rate, int dst_rate)
int SDL_GetResamplerHistoryFrames (void)
Sint64 SDL_GetResamplerInputFrames (Sint64 output_frames, Sint64 resample_rate, Sint64 resample_offset)
Sint64 SDL_GetResamplerOutputFrames (Sint64 input_frames, Sint64 resample_rate, Sint64 *inout_resample_offset)
int SDL_GetResamplerPaddingFrames (Sint64 resample_rate)
void SDL_ResampleAudio (int chans, const float *src, int inframes, float *dst, int outframes, Sint64 resample_rate, Sint64 *inout_resample_offset)
void SDL_SetupAudioResampler (void)
static void SetupAudioResampler (void)
static float Sinc (const float *table, int x, int y)
static void SincTable (float *table, int len)
static void Transpose4x4 (Cubic *data)
Variables
static ResampleFrameFunc ResampleFrame [8]
static Cubic ResamplerFilter [(1<< 3)][(5 *2)]
Macro Definition Documentation
RESAMPLER_BITS_PER_ZERO_CROSSING
#define RESAMPLER_BITS_PER_ZERO_CROSSING 3
RESAMPLER_FILTER_INTERP_BITS
#define RESAMPLER_FILTER_INTERP_BITS (32 - RESAMPLER_BITS_PER_ZERO_CROSSING)
Referenced by SDL_ResampleAudio().
RESAMPLER_FILTER_INTERP_RANGE
#define RESAMPLER_FILTER_INTERP_RANGE (1 << RESAMPLER_FILTER_INTERP_BITS)
Referenced by SDL_ResampleAudio().
RESAMPLER_MAX_PADDING_FRAMES
#define RESAMPLER_MAX_PADDING_FRAMES (RESAMPLER_ZERO_CROSSINGS + 1)
Referenced by SDL_GetResamplerHistoryFrames(), and SDL_GetResamplerPaddingFrames().
RESAMPLER_SAMPLES_PER_FRAME
#define RESAMPLER_SAMPLES_PER_FRAME (RESAMPLER_ZERO_CROSSINGS * 2)
Referenced by ResampleFrame_Generic(), ResampleFrame_Mono(), ResampleFrame_Stereo(), and SetupAudioResampler().
RESAMPLER_SAMPLES_PER_ZERO_CROSSING
#define RESAMPLER_SAMPLES_PER_ZERO_CROSSING (1 << RESAMPLER_BITS_PER_ZERO_CROSSING)
Referenced by GenerateResamplerFilter(), and SetupAudioResampler().
RESAMPLER_ZERO_CROSSINGS
#define RESAMPLER_ZERO_CROSSINGS 5
Referenced by GenerateResamplerFilter(), and SDL_ResampleAudio().
Typedef Documentation
Cubic
typedef union Cubic Cubic
ResampleFrameFunc
typedef void(* ResampleFrameFunc) (const float *src, float *dst, const Cubic *filter, float frac, int chans)
Function Documentation
BesselI0()
float BesselI0 (float x) static
{
    float sum = 0.0f;
    float i = 1.0f;
    float t = 1.0f;
    x *= x * 0.25f;
    while (t >= sum * SDL_FLT_EPSILON) {
        sum += t;
        t *= x / (i * i);
        ++i;
    }
    return sum;
}
References SDL_FLT_EPSILON.
Referenced by GenerateResamplerFilter().
CubicLeastSquares()
void CubicLeastSquares (Cubic * coeffs, float y0, float y1, float y2, float y3) static
{
    // Least squares matrix for xs = [0, 1/3, 2/3, 1]
    // [  1.0   0.0   0.0  0.0 ]
    // [ -5.5   9.0  -4.5  1.0 ]
    // [  9.0 -22.5  18.0 -4.5 ]
    // [ -4.5  13.5 -13.5  4.5 ]
    coeffs->v[0] = y0;
    coeffs->v[1] = -5.5f * y0 + 9.0f * y1 - 4.5f * y2 + y3;
    coeffs->v[2] = 9.0f * y0 - 22.5f * y1 + 18.0f * y2 - 4.5f * y3;
    coeffs->v[3] = -4.5f * y0 + 13.5f * y1 - 13.5f * y2 + 4.5f * y3;
}
References Cubic::v, and y1.
Referenced by GenerateResamplerFilter().
GenerateResamplerFilter()
void GenerateResamplerFilter (void) static
{
    enum
    {
        // Generate samples at 3x the target resolution, so that we have samples at [0, 1/3, 2/3, 1] of each position
        TABLE_SAMPLES_PER_ZERO_CROSSING = RESAMPLER_SAMPLES_PER_ZERO_CROSSING * 3,
        TABLE_SIZE = RESAMPLER_ZERO_CROSSINGS * TABLE_SAMPLES_PER_ZERO_CROSSING,
    };
    // if dB > 50, beta=(0.1102 * (dB - 8.7)), according to Matlab.
    const float dB = 80.0f;
    const float beta = 0.1102f * (dB - 8.7f);
    const float bessel_beta = BesselI0(beta);
    const float lensqr = TABLE_SIZE * TABLE_SIZE;
    int i, j;
    float sinc[TABLE_SAMPLES_PER_ZERO_CROSSING];
    SincTable(sinc, TABLE_SAMPLES_PER_ZERO_CROSSING);
    // Generate one wing of the filter
    // https://en.wikipedia.org/wiki/Kaiser_window
    // https://en.wikipedia.org/wiki/Whittaker%E2%80%93Shannon_interpolation_formula
    float filter[TABLE_SIZE + 1];
    filter[0] = 1.0f;
    for (i = 1; i <= TABLE_SIZE; ++i) {
        float b = BesselI0(beta * SDL_sqrtf((lensqr - (i * i)) / lensqr)) / bessel_beta;
        float s = Sinc(sinc, i, TABLE_SAMPLES_PER_ZERO_CROSSING);
        filter[i] = b * s;
    }
    // Generate the coefficients for each point
    // When interpolating, the fraction represents how far we are between input samples,
    // so we need to align the filter by "moving" it to the right.
    //
    // For the left wing, this means interpolating "forwards" (away from the center)
    // For the right wing, this means interpolating "backwards" (towards the center)
    //
    // The center of the filter is at the end of the left wing (RESAMPLER_ZERO_CROSSINGS - 1)
    // The left wing is the filter, but reversed
    // The right wing is the filter, but offset by 1
    //
    // Since the right wing is offset by 1, this just means we interpolate backwards
    // between the same points, instead of forwards
    // interp(p[n], p[n+1], t) = interp(p[n+1], p[n+1-1], 1 - t) = interp(p[n+1], p[n], 1 - t)
    for (i = 0; i < RESAMPLER_SAMPLES_PER_ZERO_CROSSING; ++i) {
        for (j = 0; j < RESAMPLER_ZERO_CROSSINGS; ++j) {
            const float *ys = &filter[((j * RESAMPLER_SAMPLES_PER_ZERO_CROSSING) + i) * 3];
            Cubic *fwd = &ResamplerFilter[i][RESAMPLER_ZERO_CROSSINGS - j - 1];
            Cubic *rev = &ResamplerFilter[RESAMPLER_SAMPLES_PER_ZERO_CROSSING - i - 1][RESAMPLER_ZERO_CROSSINGS + j];
            // Calculate the cubic equation of the 4 points
            CubicLeastSquares(fwd, ys[0], ys[1], ys[2], ys[3]);
            CubicLeastSquares(rev, ys[3], ys[2], ys[1], ys[0]);
        }
    }
}
References BesselI0(), CubicLeastSquares(), RESAMPLER_SAMPLES_PER_ZERO_CROSSING, RESAMPLER_ZERO_CROSSINGS, ResamplerFilter, SDL_sqrtf(), Sinc(), and SincTable().
Referenced by SetupAudioResampler().
ResampleFrame_Generic()
void ResampleFrame_Generic (const float * src, float * dst, const Cubic * filter, float frac, int chans) static
{
    const float frac2 = frac * frac;
    const float frac3 = frac * frac2;
    int i, chan;
    float scales[RESAMPLER_SAMPLES_PER_FRAME];
    for (i = 0; i < RESAMPLER_SAMPLES_PER_FRAME; ++i, ++filter) {
        scales[i] = filter->v[0] + (filter->v[1] * frac) + (filter->v[2] * frac2) + (filter->v[3] * frac3);
    }
    for (chan = 0; chan < chans; ++chan) {
        float out = 0.0f;
        for (i = 0; i < RESAMPLER_SAMPLES_PER_FRAME; ++i) {
            out += src[i * chans + chan] * scales[i];
        }
        dst[chan] = out;
    }
}
References RESAMPLER_SAMPLES_PER_FRAME, and Cubic::v.
Referenced by SetupAudioResampler().
ResampleFrame_Mono()
void ResampleFrame_Mono (const float * src, float * dst, const Cubic * filter, float frac, int chans) static
{
    const float frac2 = frac * frac;
    const float frac3 = frac * frac2;
    int i;
    float out = 0.0f;
    for (i = 0; i < RESAMPLER_SAMPLES_PER_FRAME; ++i, ++filter) {
        // Interpolate between the nearest two filters
        const float scale = filter->v[0] + (filter->v[1] * frac) + (filter->v[2] * frac2) + (filter->v[3] * frac3);
        out += src[i] * scale;
    }
    dst[0] = out;
}
References RESAMPLER_SAMPLES_PER_FRAME, and Cubic::v.
Referenced by SetupAudioResampler().
ResampleFrame_Stereo()
void ResampleFrame_Stereo (const float * src, float * dst, const Cubic * filter, float frac, int chans) static
{
    const float frac2 = frac * frac;
    const float frac3 = frac * frac2;
    int i;
    float out0 = 0.0f;
    float out1 = 0.0f;
    for (i = 0; i < RESAMPLER_SAMPLES_PER_FRAME; ++i, ++filter) {
        // Interpolate between the nearest two filters
        const float scale = filter->v[0] + (filter->v[1] * frac) + (filter->v[2] * frac2) + (filter->v[3] * frac3);
        out0 += src[i * 2 + 0] * scale;
        out1 += src[i * 2 + 1] * scale;
    }
    dst[0] = out0;
    dst[1] = out1;
}
References RESAMPLER_SAMPLES_PER_FRAME, and Cubic::v.
Referenced by SetupAudioResampler().
ResamplerAdd()
SDL_FORCE_INLINE bool ResamplerAdd (Sint64 a, Sint64 b, Sint64 * ret)
{
    if ((b > 0) && (a > SDL_MAX_SINT64 - b)) {
        return false;
    }
    *ret = a + b;
    return true;
}
References SDL_FORCE_INLINE, and SDL_MAX_SINT64.
Referenced by SDL_GetResamplerInputFrames(), and SDL_GetResamplerOutputFrames().
ResamplerMul()
SDL_FORCE_INLINE bool ResamplerMul (Sint64 a, Sint64 b, Sint64 * ret)
{
    if ((b > 0) && (a > SDL_MAX_SINT64 / b)) {
        return false;
    }
    *ret = a * b;
    return true;
}
References SDL_FORCE_INLINE, and SDL_MAX_SINT64.
Referenced by SDL_GetResamplerInputFrames(), and SDL_GetResamplerOutputFrames().
SDL_GetResampleRate()
Sint64 SDL_GetResampleRate (int src_rate, int dst_rate)
{
    SDL_assert(src_rate > 0);
    SDL_assert(dst_rate > 0);
    Sint64 numerator = (Sint64)src_rate << 32;
    Sint64 denominator = (Sint64)dst_rate;
    // Generally it's expected that `dst_frames = (src_frames * dst_rate) / src_rate`
    // To match this as closely as possible without infinite precision, always round up the resample rate.
    // For example, without rounding up, a sample ratio of 2:3 would have `sample_rate = 0xAAAAAAAA`
    // After 3 frames, the position would be 0x1.FFFFFFFE, meaning we haven't fully consumed the second input frame.
    // By rounding up to 0xAAAAAAAB, we would instead reach 0x2.00000001, fulling consuming the second frame.
    // Technically you could say this is kicking the can 0x100000000 steps down the road, but I'm fine with that :)
    // sample_rate = div_ceil(numerator, denominator)
    Sint64 sample_rate = ((numerator - 1) / denominator) + 1;
    SDL_assert(sample_rate > 0);
    return sample_rate;
}
References SDL_assert.
Referenced by GetAudioStreamResampleRate().
SDL_GetResamplerHistoryFrames()
int SDL_GetResamplerHistoryFrames (void)
{
    // Even if we aren't currently resampling, make sure to keep enough history in case we need to later.
    return RESAMPLER_MAX_PADDING_FRAMES;
}
References RESAMPLER_MAX_PADDING_FRAMES.
Referenced by UpdateAudioStreamInputSpec().
SDL_GetResamplerInputFrames()
Sint64 SDL_GetResamplerInputFrames (Sint64 output_frames, Sint64 resample_rate, Sint64 resample_offset)
{
    // Calculate the index of the last input frame, then add 1.
    // ((((output_frames - 1) * resample_rate) + resample_offset) >> 32) + 1
    Sint64 output_offset;
    if (!ResamplerMul(output_frames, resample_rate, &output_offset) ||
        !ResamplerAdd(output_offset, -resample_rate + resample_offset + 0x100000000, &output_offset)) {
        output_offset = SDL_MAX_SINT64;
    }
    Sint64 input_frames = (Sint64)(Sint32)(output_offset >> 32);
    input_frames = SDL_max(input_frames, 0);
    return input_frames;
}
References ResamplerAdd(), ResamplerMul(), SDL_max, and SDL_MAX_SINT64.
Referenced by GetAudioStreamDataInternal(), and SDL_GetAudioStreamDataAdjustGain().
SDL_GetResamplerOutputFrames()
Sint64 SDL_GetResamplerOutputFrames (Sint64 input_frames, Sint64 resample_rate, Sint64 * inout_resample_offset)
{
    Sint64 resample_offset = *inout_resample_offset;
    // input_offset = (input_frames << 32) - resample_offset;
    Sint64 input_offset;
    if (!ResamplerMul(input_frames, 0x100000000, &input_offset) ||
        !ResamplerAdd(input_offset, -resample_offset, &input_offset)) {
        input_offset = SDL_MAX_SINT64;
    }
    // output_frames = div_ceil(input_offset, resample_rate)
    Sint64 output_frames = (input_offset > 0) ? ((input_offset - 1) / resample_rate) + 1 : 0;
    *inout_resample_offset = (output_frames * resample_rate) - input_offset;
    return output_frames;
}
References ResamplerAdd(), ResamplerMul(), and SDL_MAX_SINT64.
Referenced by NextAudioStreamIter().
SDL_GetResamplerPaddingFrames()
int SDL_GetResamplerPaddingFrames (Sint64 resample_rate)
{
    // This must always be <= SDL_GetResamplerHistoryFrames()
    return resample_rate ? RESAMPLER_MAX_PADDING_FRAMES : 0;
}
References RESAMPLER_MAX_PADDING_FRAMES.
Referenced by GetAudioStreamDataInternal(), and NextAudioStreamIter().
SDL_ResampleAudio()
void SDL_ResampleAudio (int chans, const float * src, int inframes, float * dst, int outframes, Sint64 resample_rate, Sint64 * inout_resample_offset)
{
    int i;
    Sint64 srcpos = *inout_resample_offset;
    ResampleFrameFunc resample_frame = ResampleFrame[chans - 1];
    SDL_assert(resample_rate > 0);
    src -= (RESAMPLER_ZERO_CROSSINGS - 1) * chans;
    for (i = 0; i < outframes; ++i) {
        int srcindex = (int)(Sint32)(srcpos >> 32);
        Uint32 srcfraction = (Uint32)(srcpos & 0xFFFFFFFF);
        srcpos += resample_rate;
        SDL_assert(srcindex >= -1 && srcindex < inframes);
        const Cubic *filter = ResamplerFilter[srcfraction >> RESAMPLER_FILTER_INTERP_BITS];
        const float frac = (float)(srcfraction & (RESAMPLER_FILTER_INTERP_RANGE - 1)) * (1.0f / RESAMPLER_FILTER_INTERP_RANGE);
        const float *frame = &src[srcindex * chans];
        resample_frame(frame, dst, filter, frac, chans);
        dst += chans;
    }
    *inout_resample_offset = srcpos - ((Sint64)inframes << 32);
}
References ResampleFrame, RESAMPLER_FILTER_INTERP_BITS, RESAMPLER_FILTER_INTERP_RANGE, RESAMPLER_ZERO_CROSSINGS, ResamplerFilter, and SDL_assert.
Referenced by GetAudioStreamDataInternal().
SDL_SetupAudioResampler()
void SDL_SetupAudioResampler (void)
{
    static SDL_InitState init;
    if (SDL_ShouldInit(&init)) {
        SetupAudioResampler();
        SDL_SetInitialized(&init, true);
    }
}
References SDL_SetInitialized(), SDL_ShouldInit(), and SetupAudioResampler().
Referenced by SDL_CreateAudioStream(), and SDL_InitAudio().
SetupAudioResampler()
void SetupAudioResampler (void) static
{
    int i, j;
    bool transpose = false;
    GenerateResamplerFilter();
#ifdef SDL_SSE_INTRINSICS
    if (SDL_HasSSE()) {
        for (i = 0; i < 8; ++i) {
            ResampleFrame[i] = ResampleFrame_Generic_SSE;
        }
        transpose = true;
    } else
#endif
#ifdef SDL_NEON_INTRINSICS
    if (SDL_HasNEON()) {
        for (i = 0; i < 8; ++i) {
            ResampleFrame[i] = ResampleFrame_Generic_NEON;
        }
        transpose = true;
    } else
#endif
    {
        for (i = 0; i < 8; ++i) {
            ResampleFrame[i] = ResampleFrame_Generic;
        }
        ResampleFrame[0] = ResampleFrame_Mono;
        ResampleFrame[1] = ResampleFrame_Stereo;
    }
    if (transpose) {
        // Transpose each set of 4 coefficients, to reduce work when resampling
        for (i = 0; i < RESAMPLER_SAMPLES_PER_ZERO_CROSSING; ++i) {
            for (j = 0; j + 4 <= RESAMPLER_SAMPLES_PER_FRAME; j += 4) {
                Transpose4x4(&ResamplerFilter[i][j]);
            }
        }
    }
}
References GenerateResamplerFilter(), ResampleFrame, ResampleFrame_Generic(), ResampleFrame_Mono(), ResampleFrame_Stereo(), RESAMPLER_SAMPLES_PER_FRAME, RESAMPLER_SAMPLES_PER_ZERO_CROSSING, ResamplerFilter, SDL_HasNEON(), SDL_HasSSE(), and Transpose4x4().
Referenced by SDL_SetupAudioResampler().
Sinc()
float Sinc (const float * table, int x, int y) static
{
    float s = table[x % y];
    s = ((x / y) & 1) ? -s : s;
    return (s * y) / x;
}
Referenced by GenerateResamplerFilter().
SincTable()
void SincTable (float * table, int len) static
{
    int i;
    for (i = 0; i < len; ++i) {
        table[i] = SDL_sinf(i * (SDL_PI_F / len)) / SDL_PI_F;
    }
}
References SDL_PI_F, and SDL_sinf().
Referenced by GenerateResamplerFilter().
Transpose4x4()
void Transpose4x4 (Cubic * data) static
{
    int i, j;
    Cubic temp[4] = { data[0], data[1], data[2], data[3] };
    for (i = 0; i < 4; ++i) {
        for (j = 0; j < 4; ++j) {
            data[i].v[j] = temp[j].v[i];
        }
    }
}
References Cubic::v.
Referenced by SetupAudioResampler().
Variable Documentation
ResampleFrame
ResampleFrameFunc ResampleFrame[8] static
Referenced by SDL_ResampleAudio(), and SetupAudioResampler().
ResamplerFilter
Cubic ResamplerFilter[(1<< 3)][(5 *2)] static
Referenced by GenerateResamplerFilter(), SDL_ResampleAudio(), and SetupAudioResampler().