SDL3: SDL-main/src/tray/windows/SDL_tray.c File Reference
SDL_tray.c File Reference
#include "SDL_internal.h"
#include "../SDL_tray_utils.h"
#include "../../core/windows/SDL_windows.h"
#include "../../video/windows/SDL_windowswindow.h"
#include <windowsx.h>
#include <shellapi.h>
#include "../../video/windows/SDL_surface_utils.h"
Data Structures
struct SDL_Tray
struct SDL_TrayEntry
struct SDL_TrayMenu
Macros
#define NIF_SHOWTIP 0x00000080
#define NOTIFYICON_VERSION_4 4
#define WM_TRAYICON (WM_USER + 1)
Functions
static void DestroySDLMenu (SDL_TrayMenu *menu)
static wchar_t * escape_label (const char *in)
static SDL_TrayEntry * find_entry_in_menu (SDL_TrayMenu *menu, UINT_PTR id)
static SDL_TrayEntry * find_entry_with_id (SDL_Tray *tray, UINT_PTR id)
static UINT_PTR get_next_id (void)
static HICON load_default_icon ()
void SDL_ClickTrayEntry (SDL_TrayEntry *entry)
SDL_Tray * SDL_CreateTray (SDL_Surface *icon, const char *tooltip)
SDL_TrayMenu * SDL_CreateTrayMenu (SDL_Tray *tray)
SDL_TrayMenu * SDL_CreateTraySubmenu (SDL_TrayEntry *entry)
void SDL_DestroyTray (SDL_Tray *tray)
const SDL_TrayEntry ** SDL_GetTrayEntries (SDL_TrayMenu *menu, int *count)
bool SDL_GetTrayEntryChecked (SDL_TrayEntry *entry)
bool SDL_GetTrayEntryEnabled (SDL_TrayEntry *entry)
const char * SDL_GetTrayEntryLabel (SDL_TrayEntry *entry)
SDL_TrayMenu * SDL_GetTrayEntryParent (SDL_TrayEntry *entry)
SDL_TrayMenu * SDL_GetTrayMenu (SDL_Tray *tray)
SDL_TrayEntry * SDL_GetTrayMenuParentEntry (SDL_TrayMenu *menu)
SDL_Tray * SDL_GetTrayMenuParentTray (SDL_TrayMenu *menu)
SDL_TrayMenu * SDL_GetTraySubmenu (SDL_TrayEntry *entry)
SDL_TrayEntry * SDL_InsertTrayEntryAt (SDL_TrayMenu *menu, int pos, const char *label, SDL_TrayEntryFlags flags)
bool SDL_IsTraySupported (void)
void SDL_RemoveTrayEntry (SDL_TrayEntry *entry)
void SDL_SetTrayEntryCallback (SDL_TrayEntry *entry, SDL_TrayCallback callback, void *userdata)
void SDL_SetTrayEntryChecked (SDL_TrayEntry *entry, bool checked)
void SDL_SetTrayEntryEnabled (SDL_TrayEntry *entry, bool enabled)
void SDL_SetTrayEntryLabel (SDL_TrayEntry *entry, const char *label)
void SDL_SetTrayIcon (SDL_Tray *tray, SDL_Surface *icon)
void SDL_SetTrayTooltip (SDL_Tray *tray, const char *tooltip)
void SDL_UpdateTrays (void)
LRESULT CALLBACK TrayWindowProc (HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
Macro Definition Documentation
NIF_SHOWTIP
#define NIF_SHOWTIP 0x00000080
Referenced by SDL_CreateTray().
NOTIFYICON_VERSION_4
#define NOTIFYICON_VERSION_4 4
Referenced by SDL_CreateTray().
WM_TRAYICON
#define WM_TRAYICON (WM_USER + 1)
Referenced by SDL_CreateTray(), and TrayWindowProc().
Function Documentation
DestroySDLMenu()
void DestroySDLMenu (SDL_TrayMenu * menu) static
{
    for (int i = 0; i < menu->nEntries; i++) {
        if (menu->entries[i] && menu->entries[i]->submenu) {
            DestroySDLMenu(menu->entries[i]->submenu);
        }
        SDL_free(menu->entries[i]);
    }
    SDL_free(menu->entries);
    DestroyMenu(menu->hMenu);
    SDL_free(menu);
}
References DestroySDLMenu(), SDL_TrayMenu::entries, SDL_TrayMenu::hMenu, SDL_TrayMenu::nEntries, SDL_free(), and SDL_TrayEntry::submenu.
escape_label()
wchar_t * escape_label (const char * in) static
{
    const char *c;
    char *c2;
    int len = 0;
    for (c = in; *c; c++) {
        len += (*c == '&') ? 2 : 1;
    }
    char *escaped = (char *)SDL_malloc(SDL_strlen(in) + len + 1);
    if (!escaped) {
        return NULL;
    }
    for (c = in, c2 = escaped; *c;) {
        if (*c == '&') {
            *c2++ = *c;
        }
        *c2++ = *c++;
    }
    *c2 = '\0';
    wchar_t *out = WIN_UTF8ToStringW(escaped);
    SDL_free(escaped);
    return out;
}
References NULL, SDL_free(), SDL_malloc(), SDL_strlen(), and WIN_UTF8ToStringW.
Referenced by SDL_InsertTrayEntryAt(), and SDL_SetTrayEntryLabel().
find_entry_in_menu()
SDL_TrayEntry * find_entry_in_menu (SDL_TrayMenu * menu, UINT_PTR id) static
{
    for (int i = 0; i < menu->nEntries; i++) {
        SDL_TrayEntry *entry = menu->entries[i];
        if (entry->id == id) {
            return entry;
        }
        if (entry->submenu) {
            SDL_TrayEntry *e = find_entry_in_menu(entry->submenu, id);
            if (e) {
                return e;
            }
        }
    }
    return NULL;
}
References SDL_TrayMenu::entries, find_entry_in_menu(), SDL_TrayEntry::id, SDL_TrayMenu::nEntries, NULL, and SDL_TrayEntry::submenu.
Referenced by find_entry_in_menu(), and find_entry_with_id().
find_entry_with_id()
SDL_TrayEntry * find_entry_with_id (SDL_Tray * tray, UINT_PTR id) static
{
    if (!tray->menu) {
        return NULL;
    }
    return find_entry_in_menu(tray->menu, id);
}
References find_entry_in_menu(), SDL_Tray::menu, and NULL.
Referenced by TrayWindowProc().
get_next_id()
UINT_PTR get_next_id (void) static
{
    static UINT_PTR next_id = 0;
    return ++next_id;
}
Referenced by SDL_CreateTray(), and SDL_InsertTrayEntryAt().
load_default_icon()
HICON load_default_icon () static
{
    HINSTANCE hInstance = GetModuleHandle(NULL);
    if (!hInstance) {
        return LoadIcon(NULL, IDI_APPLICATION);
    }
    const char *hint = SDL_GetHint(SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL);
    if (hint && *hint) {
        HICON icon = LoadIcon(hInstance, MAKEINTRESOURCE(SDL_atoi(hint)));
        return icon ? icon : LoadIcon(NULL, IDI_APPLICATION);
    }
    hint = SDL_GetHint(SDL_HINT_WINDOWS_INTRESOURCE_ICON);
    if (hint && *hint) {
        HICON icon = LoadIcon(hInstance, MAKEINTRESOURCE(SDL_atoi(hint)));
        return icon ? icon : LoadIcon(NULL, IDI_APPLICATION);
    }
    return LoadIcon(NULL, IDI_APPLICATION);
}
References NULL, SDL_atoi(), SDL_GetHint(), SDL_HINT_WINDOWS_INTRESOURCE_ICON, and SDL_HINT_WINDOWS_INTRESOURCE_ICON_SMALL.
Referenced by SDL_CreateTray(), and SDL_SetTrayIcon().
SDL_ClickTrayEntry()
void SDL_ClickTrayEntry (SDL_TrayEntry * entry)
Simulate a click on a tray entry.
Parameters
entry The entry to activate.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
{
    if (!entry) {
        return;
    }
    if (entry->flags & SDL_TRAYENTRY_CHECKBOX) {
        SDL_SetTrayEntryChecked(entry, !SDL_GetTrayEntryChecked(entry));
    }
    if (entry->callback) {
        entry->callback(entry->userdata, entry);
    }
}
References SDL_TrayEntry::callback, SDL_TrayEntry::flags, SDL_GetTrayEntryChecked(), SDL_SetTrayEntryChecked(), SDL_TRAYENTRY_CHECKBOX, and SDL_TrayEntry::userdata.
SDL_CreateTray()
SDL_Tray * SDL_CreateTray (SDL_Surface * icon, const char * tooltip)
Create an icon to be placed in the operating system's tray, or equivalent.
Many platforms advise not using a system tray unless persistence is a necessary feature. Avoid needlessly creating a tray icon, as the user may feel like it clutters their interface.
Using tray icons require the video subsystem.
Parameters
icon a surface to be used as icon. May be NULL.
tooltip a tooltip to be displayed when the mouse hovers the icon in UTF-8 encoding. Not supported on all platforms. May be NULL.
Returns
The newly created system tray icon.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenu
SDL_DestroyTray
{
    if (!SDL_IsMainThread()) {
        SDL_SetError("This function should be called on the main thread");
        return NULL;
    }
    SDL_Tray *tray = (SDL_Tray *)SDL_calloc(1, sizeof(*tray));
    if (!tray) {
        return NULL;
    }
    tray->menu = NULL;
    tray->hwnd = CreateWindowEx(0, TEXT("Message"), NULL, 0, 0, 0, 0, 0, HWND_MESSAGE, NULL, NULL, NULL);
    SetWindowLongPtr(tray->hwnd, GWLP_WNDPROC, (LONG_PTR) TrayWindowProc);
    WIN_UpdateDarkModeForHWND(tray->hwnd);
    SDL_zero(tray->nid);
    tray->nid.cbSize = sizeof(NOTIFYICONDATAW);
    tray->nid.hWnd = tray->hwnd;
    tray->nid.uID = (UINT) get_next_id();
    tray->nid.uFlags = NIF_ICON | NIF_MESSAGE | NIF_TIP | NIF_SHOWTIP;
    tray->nid.uCallbackMessage = WM_TRAYICON;
    tray->nid.uVersion = NOTIFYICON_VERSION_4;
    wchar_t *tooltipw = WIN_UTF8ToStringW(tooltip);
    SDL_wcslcpy(tray->nid.szTip, tooltipw, sizeof(tray->nid.szTip) / sizeof(*tray->nid.szTip));
    SDL_free(tooltipw);
    if (icon) {
        tray->nid.hIcon = CreateIconFromSurface(icon);
        if (!tray->nid.hIcon) {
            tray->nid.hIcon = load_default_icon();
        }
        tray->icon = tray->nid.hIcon;
    } else {
        tray->nid.hIcon = load_default_icon();
        tray->icon = tray->nid.hIcon;
    }
    Shell_NotifyIconW(NIM_ADD, &tray->nid);
    Shell_NotifyIconW(NIM_SETVERSION, &tray->nid);
    SetWindowLongPtr(tray->hwnd, GWLP_USERDATA, (LONG_PTR) tray);
    SDL_RegisterTray(tray);
    return tray;
}
References CreateIconFromSurface(), get_next_id(), SDL_Tray::hwnd, SDL_Tray::icon, load_default_icon(), SDL_Tray::menu, SDL_Tray::nid, NIF_SHOWTIP, NOTIFYICON_VERSION_4, NULL, SDL_calloc(), SDL_free(), SDL_IsMainThread(), SDL_RegisterTray(), SDL_SetError(), SDL_Unsupported, SDL_wcslcpy(), SDL_zero, TrayWindowProc(), WIN_UpdateDarkModeForHWND(), WIN_UTF8ToStringW, and WM_TRAYICON.
SDL_CreateTrayMenu()
SDL_TrayMenu * SDL_CreateTrayMenu (SDL_Tray * tray)
Create a menu for a system tray.
This should be called at most once per tray icon.
This function does the same thing as SDL_CreateTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_GetTrayMenu
SDL_GetTrayMenuParentTray
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        SDL_InvalidParamError("tray");
        return NULL;
    }
    tray->menu = (SDL_TrayMenu *)SDL_calloc(1, sizeof(*tray->menu));
    if (!tray->menu) {
        return NULL;
    }
    tray->menu->hMenu = CreatePopupMenu();
    tray->menu->parent_tray = tray;
    tray->menu->parent_entry = NULL;
    return tray->menu;
}
References SDL_TrayMenu::hMenu, SDL_Tray::menu, NULL, SDL_TrayMenu::parent_entry, SDL_TrayMenu::parent_tray, SDL_calloc(), SDL_InvalidParamError, SDL_OBJECT_TYPE_TRAY, and SDL_ObjectValid().
SDL_CreateTraySubmenu()
SDL_TrayMenu * SDL_CreateTraySubmenu (SDL_TrayEntry * entry)
Create a submenu for a system tray entry.
This should be called at most once per tray entry.
This function does the same thing as SDL_CreateTrayMenu, except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_GetTraySubmenu
SDL_GetTrayMenuParentEntry
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    if (!entry->submenu) {
        SDL_SetError("Cannot create submenu for entry not created with SDL_TRAYENTRY_SUBMENU");
        return NULL;
    }
    return entry->submenu;
}
References NULL, SDL_InvalidParamError, SDL_SetError(), and SDL_TrayEntry::submenu.
SDL_DestroyTray()
void SDL_DestroyTray (SDL_Tray * tray)
Destroys a tray object.
This also destroys all associated menus and entries.
Parameters
tray the tray icon to be destroyed.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        return;
    }
    SDL_UnregisterTray(tray);
    Shell_NotifyIconW(NIM_DELETE, &tray->nid);
    if (tray->menu) {
        DestroySDLMenu(tray->menu);
    }
    if (tray->icon) {
        DestroyIcon(tray->icon);
    }
    if (tray->hwnd) {
        DestroyWindow(tray->hwnd);
    }
    SDL_free(tray);
}
References DestroySDLMenu(), SDL_Tray::hwnd, SDL_Tray::icon, SDL_Tray::menu, SDL_Tray::nid, SDL_free(), SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), and SDL_UnregisterTray().
Referenced by SDL_CleanupTrays().
SDL_GetTrayEntries()
const SDL_TrayEntry ** SDL_GetTrayEntries (SDL_TrayMenu * menu, int * count)
Returns a list of entries in the menu, in order.
Parameters
menu The menu to get entries from.
count An optional pointer to obtain the number of entries in the menu.
Returns
a NULL-terminated list of entries within the given menu. The pointer becomes invalid when any function that inserts or deletes entries in the menu is called.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveTrayEntry
SDL_InsertTrayEntryAt
{
    if (!menu) {
        SDL_InvalidParamError("menu");
        return NULL;
    }
    if (count) {
        *count = menu->nEntries;
    }
    return (const SDL_TrayEntry **)menu->entries;
}
References count, SDL_TrayMenu::entries, SDL_TrayMenu::nEntries, NULL, and SDL_InvalidParamError.
SDL_GetTrayEntryChecked()
bool SDL_GetTrayEntryChecked (SDL_TrayEntry * entry)
Gets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be read.
Returns
true if the entry is checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryChecked
{
    if (!entry || !(entry->flags & SDL_TRAYENTRY_CHECKBOX)) {
        return false;
    }
    MENUITEMINFOW mii;
    mii.cbSize = sizeof(MENUITEMINFOW);
    mii.fMask = MIIM_STATE;
    GetMenuItemInfoW(entry->parent->hMenu, (UINT) entry->id, FALSE, &mii);
    return ((mii.fState & MFS_CHECKED) != 0);
}
References FALSE, SDL_TrayEntry::flags, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::parent, SDL_InvalidParamError, and SDL_TRAYENTRY_CHECKBOX.
SDL_GetTrayEntryEnabled()
bool SDL_GetTrayEntryEnabled (SDL_TrayEntry * entry)
Gets whether or not an entry is enabled.
Parameters
entry the entry to be read.
Returns
true if the entry is enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryEnabled
{
    if (!entry) {
        return false;
    }
    MENUITEMINFOW mii;
    mii.cbSize = sizeof(MENUITEMINFOW);
    mii.fMask = MIIM_STATE;
    GetMenuItemInfoW(entry->parent->hMenu, (UINT) entry->id, FALSE, &mii);
    return ((mii.fState & MFS_ENABLED) != 0);
}
References FALSE, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::parent, and SDL_InvalidParamError.
SDL_GetTrayEntryLabel()
const char * SDL_GetTrayEntryLabel (SDL_TrayEntry * entry)
Gets the label of an entry.
If the returned value is NULL, the entry is a separator.
Parameters
entry the entry to be read.
Returns
the label of the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryLabel
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    return entry->label_cache;
}
References SDL_TrayEntry::label_cache, NULL, and SDL_InvalidParamError.
SDL_GetTrayEntryParent()
SDL_TrayMenu * SDL_GetTrayEntryParent (SDL_TrayEntry * entry)
Gets the menu containing a certain tray entry.
Parameters
entry the entry for which to get the parent menu.
Returns
the parent menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    return entry->parent;
}
References NULL, SDL_TrayEntry::parent, and SDL_InvalidParamError.
SDL_GetTrayMenu()
SDL_TrayMenu * SDL_GetTrayMenu (SDL_Tray * tray)
Gets a previously created tray menu.
You should have called SDL_CreateTrayMenu() on the tray object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_CreateTrayMenu
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        SDL_InvalidParamError("tray");
        return NULL;
    }
    return tray->menu;
}
References SDL_Tray::menu, NULL, SDL_InvalidParamError, SDL_OBJECT_TYPE_TRAY, and SDL_ObjectValid().
SDL_GetTrayMenuParentEntry()
SDL_TrayEntry * SDL_GetTrayMenuParentEntry (SDL_TrayMenu * menu)
Gets the entry for which the menu is a submenu, if the current menu is a submenu.
Either this function or SDL_GetTrayMenuParentTray() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent entry.
Returns
the parent entry, or NULL if this menu is not a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTraySubmenu
SDL_GetTrayMenuParentTray
{
    if (!menu) {
        SDL_InvalidParamError("menu");
        return NULL;
    }
    return menu->parent_entry;
}
References NULL, SDL_TrayMenu::parent_entry, and SDL_InvalidParamError.
SDL_GetTrayMenuParentTray()
SDL_Tray * SDL_GetTrayMenuParentTray (SDL_TrayMenu * menu)
Gets the tray for which this menu is the first-level menu, if the current menu isn't a submenu.
Either this function or SDL_GetTrayMenuParentEntry() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent enttrayry.
Returns
the parent tray, or NULL if this menu is a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenuParentEntry
{
    if (!menu) {
        SDL_InvalidParamError("menu");
        return NULL;
    }
    return menu->parent_tray;
}
References NULL, SDL_TrayMenu::parent_tray, and SDL_InvalidParamError.
SDL_GetTraySubmenu()
SDL_TrayMenu * SDL_GetTraySubmenu (SDL_TrayEntry * entry)
Gets a previously created tray entry submenu.
You should have called SDL_CreateTraySubmenu() on the entry object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTrayMenu(), except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_CreateTraySubmenu
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    return entry->submenu;
}
References NULL, SDL_InvalidParamError, and SDL_TrayEntry::submenu.
SDL_InsertTrayEntryAt()
SDL_TrayEntry * SDL_InsertTrayEntryAt (SDL_TrayMenu * menu, int pos, const char * label, SDL_TrayEntryFlags flags)
Insert a tray entry at a given position.
If label is NULL, the entry will be a separator. Many functions won't work for an entry that is a separator.
An entry does not need to be destroyed; it will be destroyed with the tray.
Parameters
menu the menu to append the entry to.
pos the desired position for the new entry. Entries at or following this place will be moved. If pos is -1, the entry is appended.
label the text to be displayed on the entry, in UTF-8 encoding, or NULL for a separator.
flags a combination of flags, some of which are mandatory.
Returns
the newly created entry, or NULL if pos is out of bounds.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_TrayEntryFlags
SDL_GetTrayEntries
SDL_RemoveTrayEntry
SDL_GetTrayEntryParent
{
    if (!menu) {
        SDL_InvalidParamError("menu");
        return NULL;
    }
    if (pos < -1 || pos > menu->nEntries) {
        SDL_InvalidParamError("pos");
        return NULL;
    }
    int windows_compatible_pos = pos;
    if (pos == -1) {
        pos = menu->nEntries;
    } else if (pos == menu->nEntries) {
        windows_compatible_pos = -1;
    }
    SDL_TrayEntry *entry = (SDL_TrayEntry *)SDL_calloc(1, sizeof(*entry));
    if (!entry) {
        return NULL;
    }
    wchar_t *label_w = NULL;
    if (label && (label_w = escape_label(label)) == NULL) {
        SDL_free(entry);
        return NULL;
    }
    entry->parent = menu;
    entry->flags = flags;
    entry->callback = NULL;
    entry->userdata = NULL;
    entry->submenu = NULL;
    SDL_snprintf(entry->label_cache, sizeof(entry->label_cache), "%s", label ? label : "");
    if (label != NULL && flags & SDL_TRAYENTRY_SUBMENU) {
        entry->submenu = (SDL_TrayMenu *)SDL_calloc(1, sizeof(*entry->submenu));
        if (!entry->submenu) {
            SDL_free(entry);
            SDL_free(label_w);
            return NULL;
        }
        entry->submenu->hMenu = CreatePopupMenu();
        entry->submenu->nEntries = 0;
        entry->submenu->entries = NULL;
        entry->submenu->parent_entry = entry;
        entry->submenu->parent_tray = NULL;
        entry->id = (UINT_PTR) entry->submenu->hMenu;
    } else {
        entry->id = get_next_id();
    }
    SDL_TrayEntry **new_entries = (SDL_TrayEntry **)SDL_realloc(menu->entries, (menu->nEntries + 2) * sizeof(*new_entries));
    if (!new_entries) {
        SDL_free(entry);
        SDL_free(label_w);
        if (entry->submenu) {
            DestroyMenu(entry->submenu->hMenu);
            SDL_free(entry->submenu);
        }
        return NULL;
    }
    menu->entries = new_entries;
    menu->nEntries++;
    for (int i = menu->nEntries - 1; i > pos; i--) {
        menu->entries[i] = menu->entries[i - 1];
    }
    new_entries[pos] = entry;
    new_entries[menu->nEntries] = NULL;
    if (label == NULL) {
        InsertMenuW(menu->hMenu, windows_compatible_pos, MF_SEPARATOR | MF_BYPOSITION, entry->id, NULL);
    } else {
        UINT mf = MF_STRING | MF_BYPOSITION;
        if (flags & SDL_TRAYENTRY_SUBMENU) {
            mf = MF_POPUP;
        }
        if (flags & SDL_TRAYENTRY_DISABLED) {
            mf |= MF_DISABLED | MF_GRAYED;
        }
        if (flags & SDL_TRAYENTRY_CHECKED) {
            mf |= MF_CHECKED;
        }
        InsertMenuW(menu->hMenu, windows_compatible_pos, mf, entry->id, label_w);
        SDL_free(label_w);
    }
    return entry;
}
References SDL_TrayEntry::callback, SDL_TrayMenu::entries, escape_label(), SDL_TrayEntry::flags, get_next_id(), SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::label_cache, SDL_TrayMenu::nEntries, NULL, SDL_TrayEntry::parent, SDL_TrayMenu::parent_entry, SDL_TrayMenu::parent_tray, SDL_calloc(), SDL_free(), SDL_InvalidParamError, SDL_realloc(), SDL_snprintf(), SDL_TRAYENTRY_CHECKED, SDL_TRAYENTRY_DISABLED, SDL_TRAYENTRY_SUBMENU, SDL_TrayEntry::submenu, and SDL_TrayEntry::userdata.
SDL_IsTraySupported()
bool SDL_IsTraySupported (void)
Check whether or not tray icons can be created.
Note that this function does not guarantee that SDL_CreateTray() will or will not work; you should still check SDL_CreateTray() for errors.
Using tray icons require the video subsystem.
Returns
true if trays are available, false otherwise.
Thread Safety
This function should only be called on the main thread. It will return false if not called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateTray
{
    if (!SDL_IsMainThread()) {
        SDL_SetError("This function should be called on the main thread");
        return false;
    }
    return true;
}
References SDL_IsMainThread(), and SDL_SetError().
SDL_RemoveTrayEntry()
void SDL_RemoveTrayEntry (SDL_TrayEntry * entry)
Removes a tray entry.
Parameters
entry The entry to be deleted.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
    if (!entry) {
        return;
    }
    SDL_TrayMenu *menu = entry->parent;
    bool found = false;
    for (int i = 0; i < menu->nEntries - 1; i++) {
        if (menu->entries[i] == entry) {
            found = true;
        }
        if (found) {
            menu->entries[i] = menu->entries[i + 1];
        }
    }
    if (entry->submenu) {
        DestroySDLMenu(entry->submenu);
    }
    menu->nEntries--;
    SDL_TrayEntry **new_entries = (SDL_TrayEntry **)SDL_realloc(menu->entries, (menu->nEntries + 1) * sizeof(*new_entries));
    /* Not sure why shrinking would fail, but even if it does, we can live with a "too big" array */
    if (new_entries) {
        menu->entries = new_entries;
        menu->entries[menu->nEntries] = NULL;
    }
    if (!DeleteMenu(menu->hMenu, (UINT) entry->id, MF_BYCOMMAND)) {
        /* This is somewhat useless since we don't return anything, but might help with eventual bugs */
        SDL_SetError("Couldn't destroy tray entry");
    }
    SDL_free(entry);
}
References DestroySDLMenu(), SDL_TrayMenu::entries, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayMenu::nEntries, NULL, SDL_TrayEntry::parent, SDL_free(), SDL_realloc(), SDL_SetError(), and SDL_TrayEntry::submenu.
SDL_SetTrayEntryCallback()
void SDL_SetTrayEntryCallback (SDL_TrayEntry * entry, SDL_TrayCallback callback, void * userdata)
Sets a callback to be invoked when the entry is selected.
Parameters
entry the entry to be updated.
callback a callback to be invoked when the entry is selected.
userdata an optional pointer to pass extra data to the callback when it will be invoked.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
    if (!entry) {
        return;
    }
    entry->callback = callback;
    entry->userdata = userdata;
}
References SDL_TrayEntry::callback, and SDL_TrayEntry::userdata.
SDL_SetTrayEntryChecked()
void SDL_SetTrayEntryChecked (SDL_TrayEntry * entry, bool checked)
Sets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be updated.
checked true if the entry should be checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryChecked
{
    if (!entry || !(entry->flags & SDL_TRAYENTRY_CHECKBOX)) {
        return;
    }
    CheckMenuItem(entry->parent->hMenu, (UINT) entry->id, checked ? MF_CHECKED : MF_UNCHECKED);
}
References SDL_TrayEntry::flags, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::parent, and SDL_TRAYENTRY_CHECKBOX.
SDL_SetTrayEntryEnabled()
void SDL_SetTrayEntryEnabled (SDL_TrayEntry * entry, bool enabled)
Sets whether or not an entry is enabled.
Parameters
entry the entry to be updated.
enabled true if the entry should be enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryEnabled
{
    if (!entry) {
        return;
    }
    EnableMenuItem(entry->parent->hMenu, (UINT) entry->id, MF_BYCOMMAND | (enabled ? MF_ENABLED : (MF_DISABLED | MF_GRAYED)));
}
References SDL_TrayMenu::hMenu, SDL_TrayEntry::id, and SDL_TrayEntry::parent.
SDL_SetTrayEntryLabel()
void SDL_SetTrayEntryLabel (SDL_TrayEntry * entry, const char * label)
Sets the label of an entry.
An entry cannot change between a separator and an ordinary entry; that is, it is not possible to set a non-NULL label on an entry that has a NULL label (separators), or to set a NULL label to an entry that has a non-NULL label. The function will silently fail if that happens.
Parameters
entry the entry to be updated.
label the new label for the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryLabel
{
    if (!entry) {
        return;
    }
    SDL_snprintf(entry->label_cache, sizeof(entry->label_cache), "%s", label);
    wchar_t *label_w = escape_label(label);
    if (!label_w) {
        return;
    }
    MENUITEMINFOW mii;
    mii.cbSize = sizeof(MENUITEMINFOW);
    mii.fMask = MIIM_STRING;
    mii.dwTypeData = label_w;
    mii.cch = (UINT) SDL_wcslen(label_w);
    if (!SetMenuItemInfoW(entry->parent->hMenu, (UINT) entry->id, FALSE, &mii)) {
        SDL_SetError("Couldn't update tray entry label");
    }
    SDL_free(label_w);
}
References escape_label(), FALSE, SDL_TrayMenu::hMenu, SDL_TrayEntry::id, SDL_TrayEntry::label_cache, SDL_TrayEntry::parent, SDL_free(), SDL_SetError(), SDL_snprintf(), and SDL_wcslen().
SDL_SetTrayIcon()
void SDL_SetTrayIcon (SDL_Tray * tray, SDL_Surface * icon)
Updates the system tray icon's icon.
Parameters
tray the tray icon to be updated.
icon the new icon. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        return;
    }
    if (tray->icon) {
        DestroyIcon(tray->icon);
    }
    if (icon) {
        tray->nid.hIcon = CreateIconFromSurface(icon);
        if (!tray->nid.hIcon) {
            tray->nid.hIcon = load_default_icon();
        }
        tray->icon = tray->nid.hIcon;
    } else {
        tray->nid.hIcon = load_default_icon();
        tray->icon = tray->nid.hIcon;
    }
    Shell_NotifyIconW(NIM_MODIFY, &tray->nid);
}
References CreateIconFromSurface(), SDL_Tray::icon, load_default_icon(), SDL_Tray::nid, SDL_OBJECT_TYPE_TRAY, and SDL_ObjectValid().
SDL_SetTrayTooltip()
void SDL_SetTrayTooltip (SDL_Tray * tray, const char * tooltip)
Updates the system tray icon's tooltip.
Parameters
tray the tray icon to be updated.
tooltip the new tooltip in UTF-8 encoding. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        return;
    }
    if (tooltip) {
        wchar_t *tooltipw = WIN_UTF8ToStringW(tooltip);
        SDL_wcslcpy(tray->nid.szTip, tooltipw, sizeof(tray->nid.szTip) / sizeof(*tray->nid.szTip));
        SDL_free(tooltipw);
    } else {
        tray->nid.szTip[0] = '\0';
    }
    Shell_NotifyIconW(NIM_MODIFY, &tray->nid);
}
References SDL_Tray::nid, SDL_free(), SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), SDL_wcslcpy(), and WIN_UTF8ToStringW.
SDL_UpdateTrays()
void SDL_UpdateTrays (void)
Update the trays.
This is called automatically by the event loop and is only needed if you're using trays but aren't handling SDL events.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
}
Referenced by SDL_PumpEventMaintenance().
TrayWindowProc()
LRESULT CALLBACK TrayWindowProc (HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
    SDL_Tray *tray = (SDL_Tray *) GetWindowLongPtr(hwnd, GWLP_USERDATA);
    SDL_TrayEntry *entry = NULL;
    if (!tray) {
        return DefWindowProc(hwnd, uMsg, wParam, lParam);
    }
    switch (uMsg) {
        case WM_TRAYICON:
            if (LOWORD(lParam) == WM_CONTEXTMENU || LOWORD(lParam) == WM_LBUTTONUP) {
                SetForegroundWindow(hwnd);
                if (tray->menu) {
                    TrackPopupMenu(tray->menu->hMenu, TPM_BOTTOMALIGN | TPM_RIGHTALIGN, GET_X_LPARAM(wParam), GET_Y_LPARAM(wParam), 0, hwnd, NULL);
                }
            }
            break;
        case WM_COMMAND:
            entry = find_entry_with_id(tray, LOWORD(wParam));
            if (entry && (entry->flags & SDL_TRAYENTRY_CHECKBOX)) {
                SDL_SetTrayEntryChecked(entry, !SDL_GetTrayEntryChecked(entry));
            }
            if (entry && entry->callback) {
                entry->callback(entry->userdata, entry);
            }
            break;
        case WM_SETTINGCHANGE:
            if (wParam == 0 && lParam != 0 && SDL_wcscmp((wchar_t *)lParam, L"ImmersiveColorSet") == 0) {
                WIN_UpdateDarkModeForHWND(hwnd);
            }
            break;
        default:
            return DefWindowProc(hwnd, uMsg, wParam, lParam);
    }
    return 0;
}
References SDL_TrayEntry::callback, find_entry_with_id(), SDL_TrayEntry::flags, SDL_TrayMenu::hMenu, SDL_Tray::menu, NULL, SDL_GetTrayEntryChecked(), SDL_SetTrayEntryChecked(), SDL_TRAYENTRY_CHECKBOX, SDL_wcscmp(), SDL_TrayEntry::userdata, WIN_UpdateDarkModeForHWND(), and WM_TRAYICON.
Referenced by SDL_CreateTray().