SDL3: SDL-main/src/main/SDL_main_callbacks.c File Reference
SDL_main_callbacks.c File Reference
#include "SDL_internal.h"
#include "SDL_main_callbacks.h"
Functions
static void SDL_DispatchMainCallbackEvent (SDL_Event *event)
static void SDL_DispatchMainCallbackEvents (void)
bool SDL_HasMainCallbacks (void)
SDL_AppResult SDL_InitMainCallbacks (int argc, char *argv[], SDL_AppInit_func appinit, SDL_AppIterate_func appiter, SDL_AppEvent_func appevent, SDL_AppQuit_func appquit)
SDL_AppResult SDL_IterateMainCallbacks (bool pump_events)
static bool SDLCALL SDL_MainCallbackEventWatcher (void *userdata, SDL_Event *event)
void SDL_QuitMainCallbacks (SDL_AppResult result)
static bool ShouldDispatchImmediately (SDL_Event *event)
Variables
static SDL_AtomicInt apprc
static void * SDL_main_appstate = NULL
static SDL_AppEvent_func SDL_main_event_callback
static SDL_AppIterate_func SDL_main_iteration_callback
static SDL_AppQuit_func SDL_main_quit_callback
Function Documentation
SDL_DispatchMainCallbackEvent()
void SDL_DispatchMainCallbackEvent (SDL_Event * event) static
{
    if (SDL_GetAtomicInt(&apprc) == SDL_APP_CONTINUE) { // if already quitting, don't send the event to the app.
        SDL_CompareAndSwapAtomicInt(&apprc, SDL_APP_CONTINUE, SDL_main_event_callback(SDL_main_appstate, event));
    }
}
References apprc, SDL_APP_CONTINUE, SDL_CompareAndSwapAtomicInt(), SDL_GetAtomicInt(), SDL_main_appstate, and SDL_main_event_callback.
Referenced by SDL_DispatchMainCallbackEvents(), and SDL_MainCallbackEventWatcher().
SDL_DispatchMainCallbackEvents()
void SDL_DispatchMainCallbackEvents (void) static
{
    SDL_Event events[16];
    for (;;) {
        int count = SDL_PeepEvents(events, SDL_arraysize(events), SDL_GETEVENT, SDL_EVENT_FIRST, SDL_EVENT_LAST);
        if (count <= 0) {
            break;
        }
        for (int i = 0; i < count; ++i) {
            SDL_Event *event = &events[i];
            if (!ShouldDispatchImmediately(event)) {
                SDL_DispatchMainCallbackEvent(event);
            }
        }
    }
}
References count, SDL_arraysize, SDL_DispatchMainCallbackEvent(), SDL_EVENT_FIRST, SDL_EVENT_LAST, SDL_GETEVENT, SDL_PeepEvents(), and ShouldDispatchImmediately().
Referenced by SDL_IterateMainCallbacks(), and SDL_MainCallbackEventWatcher().
SDL_HasMainCallbacks()
bool SDL_HasMainCallbacks (void)
{
    if (SDL_main_iteration_callback) {
        return true;
    }
    return false;
}
References SDL_main_iteration_callback.
Referenced by SDL_OnWindowLiveResizeUpdate().
SDL_InitMainCallbacks()
SDL_AppResult SDL_InitMainCallbacks (int argc, char * argv[], SDL_AppInit_func appinit, SDL_AppIterate_func appiter, SDL_AppEvent_func appevent, SDL_AppQuit_func appquit)
{
    SDL_main_iteration_callback = appiter;
    SDL_main_event_callback = appevent;
    SDL_main_quit_callback = appquit;
    SDL_SetAtomicInt(&apprc, SDL_APP_CONTINUE);
    const SDL_AppResult rc = appinit(&SDL_main_appstate, argc, argv);
    if (SDL_CompareAndSwapAtomicInt(&apprc, SDL_APP_CONTINUE, rc) && (rc == SDL_APP_CONTINUE)) { // bounce if SDL_AppInit already said abort, otherwise...
        // make sure we definitely have events initialized, even if the app didn't do it.
        if (!SDL_InitSubSystem(SDL_INIT_EVENTS)) {
            SDL_SetAtomicInt(&apprc, SDL_APP_FAILURE);
            return SDL_APP_FAILURE;
        }
        if (!SDL_AddEventWatch(SDL_MainCallbackEventWatcher, NULL)) {
            SDL_SetAtomicInt(&apprc, SDL_APP_FAILURE);
            return SDL_APP_FAILURE;
        }
    }
    return (SDL_AppResult)SDL_GetAtomicInt(&apprc);
}
References apprc, NULL, SDL_AddEventWatch(), SDL_APP_CONTINUE, SDL_APP_FAILURE, SDL_CompareAndSwapAtomicInt(), SDL_GetAtomicInt(), SDL_INIT_EVENTS, SDL_InitSubSystem(), SDL_main_appstate, SDL_main_event_callback, SDL_main_iteration_callback, SDL_main_quit_callback, SDL_MainCallbackEventWatcher(), and SDL_SetAtomicInt().
Referenced by SDL_EnterAppMainCallbacks().
SDL_IterateMainCallbacks()
SDL_AppResult SDL_IterateMainCallbacks (bool pump_events)
{
    if (pump_events) {
        SDL_PumpEvents();
    }
    SDL_DispatchMainCallbackEvents();
    SDL_AppResult rc = (SDL_AppResult)SDL_GetAtomicInt(&apprc);
    if (rc == SDL_APP_CONTINUE) {
        rc = SDL_main_iteration_callback(SDL_main_appstate);
        if (!SDL_CompareAndSwapAtomicInt(&apprc, SDL_APP_CONTINUE, rc)) {
            rc = (SDL_AppResult)SDL_GetAtomicInt(&apprc); // something else already set a quit result, keep that.
        }
    }
    return rc;
}
References apprc, SDL_APP_CONTINUE, SDL_CompareAndSwapAtomicInt(), SDL_DispatchMainCallbackEvents(), SDL_GetAtomicInt(), SDL_main_appstate, SDL_main_iteration_callback, and SDL_PumpEvents().
Referenced by EmscriptenInternalMainloop(), GenericIterateMainCallbacks(), and SDL_OnWindowLiveResizeUpdate().
SDL_MainCallbackEventWatcher()
bool SDLCALL SDL_MainCallbackEventWatcher (void * userdata, SDL_Event * event) static
{
    if (ShouldDispatchImmediately(event)) {
        // Make sure any currently queued events are processed then dispatch this before continuing
        SDL_DispatchMainCallbackEvents();
        SDL_DispatchMainCallbackEvent(event);
        // Make sure that we quit if we get a terminating event
        if (event->type == SDL_EVENT_TERMINATING) {
            SDL_CompareAndSwapAtomicInt(&apprc, SDL_APP_CONTINUE, SDL_APP_SUCCESS);
        }
    } else {
        // We'll process this event later from the main event queue
    }
    return true;
}
References apprc, SDL_APP_CONTINUE, SDL_APP_SUCCESS, SDL_CompareAndSwapAtomicInt(), SDL_DispatchMainCallbackEvent(), SDL_DispatchMainCallbackEvents(), SDL_EVENT_TERMINATING, SDLCALL, and ShouldDispatchImmediately().
Referenced by SDL_InitMainCallbacks(), and SDL_QuitMainCallbacks().
SDL_QuitMainCallbacks()
void SDL_QuitMainCallbacks (SDL_AppResult result)
{
    SDL_RemoveEventWatch(SDL_MainCallbackEventWatcher, NULL);
    SDL_main_quit_callback(SDL_main_appstate, result);
    SDL_main_appstate = NULL;  // just in case.
    // for symmetry, you should explicitly Quit what you Init, but we might come through here uninitialized and SDL_Quit() will clear everything anyhow.
    //SDL_QuitSubSystem(SDL_INIT_EVENTS);
    SDL_Quit();
}
References NULL, SDL_main_appstate, SDL_main_quit_callback, SDL_MainCallbackEventWatcher(), SDL_Quit(), and SDL_RemoveEventWatch().
Referenced by EmscriptenInternalMainloop(), and SDL_EnterAppMainCallbacks().
ShouldDispatchImmediately()
bool ShouldDispatchImmediately (SDL_Event * event) static
{
    switch (event->type) {
    case SDL_EVENT_TERMINATING:
    case SDL_EVENT_LOW_MEMORY:
    case SDL_EVENT_WILL_ENTER_BACKGROUND:
    case SDL_EVENT_DID_ENTER_BACKGROUND:
    case SDL_EVENT_WILL_ENTER_FOREGROUND:
    case SDL_EVENT_DID_ENTER_FOREGROUND:
        return true;
    default:
        return false;
    }
}
References SDL_EVENT_DID_ENTER_BACKGROUND, SDL_EVENT_DID_ENTER_FOREGROUND, SDL_EVENT_LOW_MEMORY, SDL_EVENT_TERMINATING, SDL_EVENT_WILL_ENTER_BACKGROUND, and SDL_EVENT_WILL_ENTER_FOREGROUND.
Referenced by SDL_DispatchMainCallbackEvents(), and SDL_MainCallbackEventWatcher().
Variable Documentation
apprc
SDL_AtomicInt apprc static
Referenced by SDL_DispatchMainCallbackEvent(), SDL_InitMainCallbacks(), SDL_IterateMainCallbacks(), and SDL_MainCallbackEventWatcher().
SDL_main_appstate
void* SDL_main_appstate = NULL static
Referenced by SDL_DispatchMainCallbackEvent(), SDL_InitMainCallbacks(), SDL_IterateMainCallbacks(), and SDL_QuitMainCallbacks().
SDL_main_event_callback
SDL_AppEvent_func SDL_main_event_callback static
Referenced by SDL_DispatchMainCallbackEvent(), and SDL_InitMainCallbacks().
SDL_main_iteration_callback
SDL_AppIterate_func SDL_main_iteration_callback static
Referenced by SDL_HasMainCallbacks(), SDL_InitMainCallbacks(), and SDL_IterateMainCallbacks().
SDL_main_quit_callback
SDL_AppQuit_func SDL_main_quit_callback static
Referenced by SDL_InitMainCallbacks(), and SDL_QuitMainCallbacks().