SDL3: SDL-main/src/sensor/SDL_sensor.c File Reference
SDL_sensor.c File Reference
#include "SDL_internal.h"
#include "SDL_syssensor.h"
#include "../events/SDL_events_c.h"
#include "../joystick/SDL_gamepad_c.h"
Macros
#define CHECK_SENSOR_MAGIC(sensor, result)
Functions
void SDL_AssertSensorsLocked (void)
void SDL_CloseSensor (SDL_Sensor *sensor)
static bool SDL_GetDriverAndSensorIndex (SDL_SensorID instance_id, SDL_SensorDriver **driver, int *driver_index)
bool SDL_GetSensorData (SDL_Sensor *sensor, float *data, int num_values)
SDL_Sensor * SDL_GetSensorFromID (SDL_SensorID instance_id)
SDL_SensorID SDL_GetSensorID (SDL_Sensor *sensor)
const char * SDL_GetSensorName (SDL_Sensor *sensor)
const char * SDL_GetSensorNameForID (SDL_SensorID instance_id)
int SDL_GetSensorNonPortableType (SDL_Sensor *sensor)
int SDL_GetSensorNonPortableTypeForID (SDL_SensorID instance_id)
SDL_PropertiesID SDL_GetSensorProperties (SDL_Sensor *sensor)
SDL_SensorID * SDL_GetSensors (int *count)
SDL_SensorType SDL_GetSensorType (SDL_Sensor *sensor)
SDL_SensorType SDL_GetSensorTypeForID (SDL_SensorID instance_id)
static SDL_Sensor *SDL_sensors SDL_GUARDED_BY (SDL_sensor_lock)
bool SDL_InitSensors (void)
void SDL_LockSensors (void)
SDL_Sensor * SDL_OpenSensor (SDL_SensorID instance_id)
void SDL_QuitSensors (void)
void SDL_SendSensorUpdate (Uint64 timestamp, SDL_Sensor *sensor, Uint64 sensor_timestamp, float *data, int num_values)
bool SDL_SensorsInitialized (void)
bool SDL_SensorsLocked (void)
bool SDL_SensorsOpened (void)
void SDL_UnlockSensors (void)
void SDL_UpdateSensor (SDL_Sensor *sensor)
void SDL_UpdateSensors (void)
Variables
static SDL_SensorDriver * SDL_sensor_drivers []
static SDL_Mutex * SDL_sensor_lock = NULL
static SDL_AtomicInt SDL_sensor_lock_pending
static bool SDL_sensors_initialized
static int SDL_sensors_locked
Macro Definition Documentation
CHECK_SENSOR_MAGIC
#define CHECK_SENSOR_MAGIC (sensor, result)
Value:
    if (!SDL_ObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR)) { \
        SDL_InvalidParamError("sensor");                    \
        SDL_UnlockSensors();                                \
        return result;                                      \
    }
#define CHECK_SENSOR_MAGIC(sensor, result)                  \
    if (!SDL_ObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR)) { \
        SDL_InvalidParamError("sensor");                    \
        SDL_UnlockSensors();                                \
        return result;                                      \
    }
Referenced by SDL_CloseSensor(), SDL_GetSensorData(), SDL_GetSensorID(), SDL_GetSensorName(), SDL_GetSensorNonPortableType(), SDL_GetSensorProperties(), SDL_GetSensorType(), and SDL_UpdateSensor().
Function Documentation
SDL_AssertSensorsLocked()
void SDL_AssertSensorsLocked (void)
{
    SDL_assert(SDL_SensorsLocked());
}
References SDL_assert, and SDL_SensorsLocked().
Referenced by SDL_SendSensorUpdate().
SDL_CloseSensor()
void SDL_CloseSensor (SDL_Sensor * sensor)
Close a sensor previously opened with SDL_OpenSensor().
Parameters
sensor the SDL_Sensor object to close.
Since
This function is available since SDL 3.2.0.
{
    SDL_Sensor *sensorlist;
    SDL_Sensor *sensorlistprev;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor,);
        // First decrement ref count
        if (--sensor->ref_count > 0) {
            SDL_UnlockSensors();
            return;
        }
        SDL_DestroyProperties(sensor->props);
        sensor->driver->Close(sensor);
        sensor->hwdata = NULL;
        SDL_SetObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR, false);
        sensorlist = SDL_sensors;
        sensorlistprev = NULL;
        while (sensorlist) {
            if (sensor == sensorlist) {
                if (sensorlistprev) {
                    // unlink this entry
                    sensorlistprev->next = sensorlist->next;
                } else {
                    SDL_sensors = sensor->next;
                }
                break;
            }
            sensorlistprev = sensorlist;
            sensorlist = sensorlist->next;
        }
        // Free the data associated with this sensor
        SDL_free(sensor->name);
        SDL_free(sensor);
    }
    SDL_UnlockSensors();
}
References CHECK_SENSOR_MAGIC, NULL, SDL_DestroyProperties(), SDL_free(), SDL_LockSensors(), SDL_OBJECT_TYPE_SENSOR, SDL_SetObjectValid(), and SDL_UnlockSensors().
Referenced by CleanupSensorFusion(), SDL_QuitSensors(), and SDL_SetGamepadSensorEnabled().
SDL_GetDriverAndSensorIndex()
bool SDL_GetDriverAndSensorIndex (SDL_SensorID instance_id, SDL_SensorDriver ** driver, int * driver_index) static
{
    int i, num_sensors, device_index;
    if (instance_id > 0) {
        for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
            num_sensors = SDL_sensor_drivers[i]->GetCount();
            for (device_index = 0; device_index < num_sensors; ++device_index) {
                SDL_SensorID sensor_id = SDL_sensor_drivers[i]->GetDeviceInstanceID(device_index);
                if (sensor_id == instance_id) {
                    *driver = SDL_sensor_drivers[i];
                    *driver_index = device_index;
                    return true;
                }
            }
        }
    }
    SDL_SetError("Sensor %" SDL_PRIu32 " not found", instance_id);
    return false;
}
References SDL_arraysize, SDL_PRIu32, SDL_sensor_drivers, and SDL_SetError().
Referenced by SDL_GetSensorNameForID(), SDL_GetSensorNonPortableTypeForID(), SDL_GetSensorTypeForID(), and SDL_OpenSensor().
SDL_GetSensorData()
bool SDL_GetSensorData (SDL_Sensor * sensor, float * data, int num_values)
Get the current state of an opened sensor.
The number of values and interpretation of the data is sensor dependent.
Parameters
sensor the SDL_Sensor object to query.
data a pointer filled with the current sensor state.
num_values the number of values to write to data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, false);
        num_values = SDL_min(num_values, SDL_arraysize(sensor->data));
        SDL_memcpy(data, sensor->data, num_values * sizeof(*data));
    }
    SDL_UnlockSensors();
    return true;
}
References CHECK_SENSOR_MAGIC, SDL_arraysize, SDL_LockSensors(), SDL_memcpy, SDL_min, and SDL_UnlockSensors().
SDL_GetSensorFromID()
SDL_Sensor * SDL_GetSensorFromID (SDL_SensorID instance_id)
Return the SDL_Sensor associated with an instance ID.
Parameters
instance_id the sensor instance ID.
Returns
an SDL_Sensor object or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Sensor *sensor;
    SDL_LockSensors();
    for (sensor = SDL_sensors; sensor; sensor = sensor->next) {
        if (sensor->instance_id == instance_id) {
            break;
        }
    }
    SDL_UnlockSensors();
    return sensor;
}
References SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorID()
SDL_SensorID SDL_GetSensorID (SDL_Sensor * sensor)
Get the instance ID of a sensor.
Parameters
sensor the SDL_Sensor object to inspect.
Returns
the sensor instance ID, or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorID result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, 0);
        result = sensor->instance_id;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorName()
const char * SDL_GetSensorName (SDL_Sensor * sensor)
Get the implementation dependent name of a sensor.
Parameters
sensor the SDL_Sensor object.
Returns
the sensor name or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    const char *result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, NULL);
        result = SDL_GetPersistentString(sensor->name);
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, NULL, SDL_GetPersistentString(), SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorNameForID()
const char * SDL_GetSensorNameForID (SDL_SensorID instance_id)
Get the implementation dependent name of a sensor.
This can be called before any sensors are opened.
Parameters
instance_id the sensor instance ID.
Returns
the sensor name, or NULL if instance_id is not valid.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    const char *name = NULL;
    SDL_LockSensors();
    if (SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        name = SDL_GetPersistentString(driver->GetDeviceName(device_index));
    }
    SDL_UnlockSensors();
    return name;
}
References SDL_SensorDriver::GetDeviceName, NULL, SDL_GetDriverAndSensorIndex(), SDL_GetPersistentString(), SDL_LockSensors(), and SDL_UnlockSensors().
Referenced by IsROGAlly().
SDL_GetSensorNonPortableType()
int SDL_GetSensorNonPortableType (SDL_Sensor * sensor)
Get the platform dependent type of a sensor.
Parameters
sensor the SDL_Sensor object to inspect.
Returns
the sensor platform dependent type, or -1 if sensor is NULL.
Since
This function is available since SDL 3.2.0.
{
    int result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, -1);
        result = sensor->non_portable_type;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorNonPortableTypeForID()
int SDL_GetSensorNonPortableTypeForID (SDL_SensorID instance_id)
Get the platform dependent type of a sensor.
This can be called before any sensors are opened.
Parameters
instance_id the sensor instance ID.
Returns
the sensor platform dependent type, or -1 if instance_id is not valid.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    int type = -1;
    SDL_LockSensors();
    if (SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        type = driver->GetDeviceNonPortableType(device_index);
    }
    SDL_UnlockSensors();
    return type;
}
References SDL_SensorDriver::GetDeviceNonPortableType, SDL_GetDriverAndSensorIndex(), SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorProperties()
SDL_PropertiesID SDL_GetSensorProperties (SDL_Sensor * sensor)
Get the properties associated with a sensor.
Parameters
sensor the SDL_Sensor object.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, 0);
        if (sensor->props == 0) {
            sensor->props = SDL_CreateProperties();
        }
        result = sensor->props;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_CreateProperties(), SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensors()
SDL_SensorID * SDL_GetSensors (int * count)
Get a list of currently connected sensors.
Parameters
count a pointer filled in with the number of sensors returned, may be NULL.
Returns
a 0 terminated array of sensor instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    int i, num_sensors, device_index;
    int sensor_index = 0, total_sensors = 0;
    SDL_SensorID *sensors;
    SDL_LockSensors();
    {
        for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
            total_sensors += SDL_sensor_drivers[i]->GetCount();
        }
        sensors = (SDL_SensorID *)SDL_malloc((total_sensors + 1) * sizeof(*sensors));
        if (sensors) {
            if (count) {
                *count = total_sensors;
            }
            for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
                num_sensors = SDL_sensor_drivers[i]->GetCount();
                for (device_index = 0; device_index < num_sensors; ++device_index) {
                    SDL_assert(sensor_index < total_sensors);
                    sensors[sensor_index] = SDL_sensor_drivers[i]->GetDeviceInstanceID(device_index);
                    SDL_assert(sensors[sensor_index] > 0);
                    ++sensor_index;
                }
            }
            SDL_assert(sensor_index == total_sensors);
            sensors[sensor_index] = 0;
        } else {
            if (count) {
                *count = 0;
            }
        }
    }
    SDL_UnlockSensors();
    return sensors;
}
References count, SDL_arraysize, SDL_assert, SDL_LockSensors(), SDL_malloc(), SDL_sensor_drivers, and SDL_UnlockSensors().
Referenced by AttemptSensorFusion(), and IsROGAlly().
SDL_GetSensorType()
SDL_SensorType SDL_GetSensorType (SDL_Sensor * sensor)
Get the type of a sensor.
Parameters
sensor the SDL_Sensor object to inspect.
Returns
the SDL_SensorType type, or SDL_SENSOR_INVALID if sensor is NULL.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorType result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, SDL_SENSOR_INVALID);
        result = sensor->type;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), SDL_SENSOR_INVALID, and SDL_UnlockSensors().
SDL_GetSensorTypeForID()
SDL_SensorType SDL_GetSensorTypeForID (SDL_SensorID instance_id)
Get the type of a sensor.
This can be called before any sensors are opened.
Parameters
instance_id the sensor instance ID.
Returns
the SDL_SensorType, or SDL_SENSOR_INVALID if instance_id is not valid.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    SDL_SensorType type = SDL_SENSOR_INVALID;
    SDL_LockSensors();
    if (SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        type = driver->GetDeviceType(device_index);
    }
    SDL_UnlockSensors();
    return type;
}
References SDL_SensorDriver::GetDeviceType, SDL_GetDriverAndSensorIndex(), SDL_LockSensors(), SDL_SENSOR_INVALID, and SDL_UnlockSensors().
Referenced by AttemptSensorFusion(), and IsROGAlly().
SDL_GUARDED_BY()
SDL_Sensor *SDL_sensors SDL_GUARDED_BY (SDL_sensor_lock) static
References NULL, and SDL_sensor_lock.
SDL_InitSensors()
bool SDL_InitSensors (void)
{
    int i;
    bool status;
    // Create the sensor list lock
    if (SDL_sensor_lock == NULL) {
        SDL_sensor_lock = SDL_CreateMutex();
    }
    if (!SDL_InitSubSystem(SDL_INIT_EVENTS)) {
        return false;
    }
    SDL_LockSensors();
    SDL_sensors_initialized = true;
    status = false;
    for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
        if (SDL_sensor_drivers[i]->Init()) {
            status = true;
        }
    }
    SDL_UnlockSensors();
    if (!status) {
        SDL_QuitSensors();
    }
    return status;
}
References NULL, SDL_arraysize, SDL_CreateMutex(), SDL_INIT_EVENTS, SDL_InitSubSystem(), SDL_LockSensors(), SDL_QuitSensors(), SDL_sensor_drivers, SDL_sensor_lock, SDL_sensors_initialized, and SDL_UnlockSensors().
Referenced by SDL_InitSubSystem().
SDL_LockSensors()
void SDL_LockSensors (void)
{
    (void)SDL_AtomicIncRef(&SDL_sensor_lock_pending);
    SDL_LockMutex(SDL_sensor_lock);
    (void)SDL_AtomicDecRef(&SDL_sensor_lock_pending);
    ++SDL_sensors_locked;
}
References SDL_AtomicDecRef, SDL_AtomicIncRef, SDL_LockMutex(), SDL_sensor_lock, SDL_sensor_lock_pending, SDL_sensors_locked, and void().
Referenced by SDL_CloseSensor(), SDL_GetSensorData(), SDL_GetSensorFromID(), SDL_GetSensorID(), SDL_GetSensorName(), SDL_GetSensorNameForID(), SDL_GetSensorNonPortableType(), SDL_GetSensorNonPortableTypeForID(), SDL_GetSensorProperties(), SDL_GetSensors(), SDL_GetSensorType(), SDL_GetSensorTypeForID(), SDL_InitSensors(), SDL_OpenSensor(), SDL_QuitSensors(), SDL_SensorsOpened(), SDL_UpdateSensor(), and SDL_UpdateSensors().
SDL_OpenSensor()
SDL_Sensor * SDL_OpenSensor (SDL_SensorID instance_id)
Open a sensor for use.
Parameters
instance_id the sensor instance ID.
Returns
an SDL_Sensor object or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    SDL_Sensor *sensor;
    SDL_Sensor *sensorlist;
    const char *sensorname = NULL;
    SDL_LockSensors();
    if (!SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        SDL_UnlockSensors();
        return NULL;
    }
    sensorlist = SDL_sensors;
    /* If the sensor is already open, return it
     * it is important that we have a single sensor * for each instance id
     */
    while (sensorlist) {
        if (instance_id == sensorlist->instance_id) {
            sensor = sensorlist;
            ++sensor->ref_count;
            SDL_UnlockSensors();
            return sensor;
        }
        sensorlist = sensorlist->next;
    }
    // Create and initialize the sensor
    sensor = (SDL_Sensor *)SDL_calloc(1, sizeof(*sensor));
    if (!sensor) {
        SDL_UnlockSensors();
        return NULL;
    }
    SDL_SetObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR, true);
    sensor->driver = driver;
    sensor->instance_id = instance_id;
    sensor->type = driver->GetDeviceType(device_index);
    sensor->non_portable_type = driver->GetDeviceNonPortableType(device_index);
    if (!driver->Open(sensor, device_index)) {
        SDL_SetObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR, false);
        SDL_free(sensor);
        SDL_UnlockSensors();
        return NULL;
    }
    sensorname = driver->GetDeviceName(device_index);
    if (sensorname) {
        sensor->name = SDL_strdup(sensorname);
    } else {
        sensor->name = NULL;
    }
    // Add sensor to list
    ++sensor->ref_count;
    // Link the sensor in the list
    sensor->next = SDL_sensors;
    SDL_sensors = sensor;
    driver->Update(sensor);
    SDL_UnlockSensors();
    return sensor;
}
References SDL_SensorDriver::GetDeviceName, SDL_SensorDriver::GetDeviceNonPortableType, SDL_SensorDriver::GetDeviceType, NULL, SDL_SensorDriver::Open, SDL_calloc(), SDL_free(), SDL_GetDriverAndSensorIndex(), SDL_LockSensors(), SDL_OBJECT_TYPE_SENSOR, SDL_SetObjectValid(), SDL_strdup(), SDL_UnlockSensors(), and SDL_SensorDriver::Update.
Referenced by SDL_SetGamepadSensorEnabled().
SDL_QuitSensors()
void SDL_QuitSensors (void)
{
    int i;
    SDL_LockSensors();
    // Stop the event polling
    while (SDL_sensors) {
        SDL_sensors->ref_count = 1;
        SDL_CloseSensor(SDL_sensors);
    }
    // Quit the sensor setup
    for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
        SDL_sensor_drivers[i]->Quit();
    }
    SDL_QuitSubSystem(SDL_INIT_EVENTS);
    SDL_sensors_initialized = false;
    SDL_UnlockSensors();
}
References SDL_arraysize, SDL_CloseSensor(), SDL_INIT_EVENTS, SDL_LockSensors(), SDL_QuitSubSystem(), SDL_sensor_drivers, SDL_sensors_initialized, and SDL_UnlockSensors().
Referenced by SDL_InitSensors(), and SDL_QuitSubSystem().
SDL_SendSensorUpdate()
void SDL_SendSensorUpdate (Uint64 timestamp, SDL_Sensor * sensor, Uint64 sensor_timestamp, float * data, int num_values)
{
    SDL_AssertSensorsLocked();
    // Allow duplicate events, for things like steps and heartbeats
    // Update internal sensor state
    num_values = SDL_min(num_values, SDL_arraysize(sensor->data));
    SDL_memcpy(sensor->data, data, num_values * sizeof(*data));
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_SENSOR_UPDATE)) {
        SDL_Event event;
        event.type = SDL_EVENT_SENSOR_UPDATE;
        event.common.timestamp = timestamp;
        event.sensor.which = sensor->instance_id;
        num_values = SDL_min(num_values, SDL_arraysize(event.sensor.data));
        SDL_memset(event.sensor.data, 0, sizeof(event.sensor.data));
        SDL_memcpy(event.sensor.data, data, num_values * sizeof(*data));
        event.sensor.sensor_timestamp = sensor_timestamp;
        SDL_PushEvent(&event);
    }
    SDL_GamepadSensorWatcher(timestamp, sensor->instance_id, sensor_timestamp, data, num_values);
}
References SDL_arraysize, SDL_AssertSensorsLocked(), SDL_EVENT_SENSOR_UPDATE, SDL_EventEnabled(), SDL_GamepadSensorWatcher(), SDL_memcpy, SDL_memset, SDL_min, and SDL_PushEvent().
SDL_SensorsInitialized()
bool SDL_SensorsInitialized (void)
{
    return SDL_sensors_initialized;
}
References SDL_sensors_initialized.
SDL_SensorsLocked()
bool SDL_SensorsLocked (void)
{
    return (SDL_sensors_locked > 0);
}
References SDL_sensors_locked.
Referenced by SDL_AssertSensorsLocked().
SDL_SensorsOpened()
bool SDL_SensorsOpened (void)
{
    bool opened;
    SDL_LockSensors();
    {
        if (SDL_sensors != NULL) {
            opened = true;
        } else {
            opened = false;
        }
    }
    SDL_UnlockSensors();
    return opened;
}
References NULL, SDL_LockSensors(), and SDL_UnlockSensors().
Referenced by SDL_events_get_polling_interval().
SDL_UnlockSensors()
void SDL_UnlockSensors (void)
{
    bool last_unlock = false;
    --SDL_sensors_locked;
    if (!SDL_sensors_initialized) {
        // NOTE: There's a small window here where another thread could lock the mutex after we've checked for pending locks
        if (!SDL_sensors_locked && SDL_GetAtomicInt(&SDL_sensor_lock_pending) == 0) {
            last_unlock = true;
        }
    }
    /* The last unlock after sensors are uninitialized will cleanup the mutex,
     * allowing applications to lock sensors while reinitializing the system.
     */
    if (last_unlock) {
        SDL_Mutex *sensor_lock = SDL_sensor_lock;
        SDL_LockMutex(sensor_lock);
        {
            SDL_UnlockMutex(SDL_sensor_lock);
            SDL_sensor_lock = NULL;
        }
        SDL_UnlockMutex(sensor_lock);
        SDL_DestroyMutex(sensor_lock);
    } else {
        SDL_UnlockMutex(SDL_sensor_lock);
    }
}
References NULL, SDL_DestroyMutex(), SDL_GetAtomicInt(), SDL_LockMutex(), SDL_sensor_lock, SDL_sensor_lock_pending, SDL_sensors_initialized, SDL_sensors_locked, and SDL_UnlockMutex().
Referenced by SDL_CloseSensor(), SDL_GetSensorData(), SDL_GetSensorFromID(), SDL_GetSensorID(), SDL_GetSensorName(), SDL_GetSensorNameForID(), SDL_GetSensorNonPortableType(), SDL_GetSensorNonPortableTypeForID(), SDL_GetSensorProperties(), SDL_GetSensors(), SDL_GetSensorType(), SDL_GetSensorTypeForID(), SDL_InitSensors(), SDL_OpenSensor(), SDL_QuitSensors(), SDL_SensorsOpened(), SDL_UpdateSensor(), and SDL_UpdateSensors().
SDL_UpdateSensor()
void SDL_UpdateSensor (SDL_Sensor * sensor)
{
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor,);
        sensor->driver->Update(sensor);
    }
    SDL_UnlockSensors();
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), and SDL_UnlockSensors().
SDL_UpdateSensors()
void SDL_UpdateSensors (void)
Update the current state of the open sensors.
This is called automatically by the event loop if sensor events are enabled.
This needs to be called from the thread that initialized the sensor subsystem.
Since
This function is available since SDL 3.2.0.
{
    int i;
    SDL_Sensor *sensor;
    if (!SDL_WasInit(SDL_INIT_SENSOR)) {
        return;
    }
    SDL_LockSensors();
    for (sensor = SDL_sensors; sensor; sensor = sensor->next) {
        sensor->driver->Update(sensor);
    }
    /* this needs to happen AFTER walking the sensor list above, so that any
       dangling hardware data from removed devices can be free'd
     */
    for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
        SDL_sensor_drivers[i]->Detect();
    }
    SDL_UnlockSensors();
}
References SDL_arraysize, SDL_INIT_SENSOR, SDL_LockSensors(), SDL_sensor_drivers, SDL_UnlockSensors(), and SDL_WasInit().
Referenced by SDL_PumpEventMaintenance().
Variable Documentation
SDL_sensor_drivers
SDL_SensorDriver* SDL_sensor_drivers[] static
Initial value:
= {
}
{
#ifdef SDL_SENSOR_ANDROID
    &SDL_ANDROID_SensorDriver,
#endif
#ifdef SDL_SENSOR_COREMOTION
    &SDL_COREMOTION_SensorDriver,
#endif
#ifdef SDL_SENSOR_WINDOWS
    &SDL_WINDOWS_SensorDriver,
#endif
#ifdef SDL_SENSOR_VITA
    &SDL_VITA_SensorDriver,
#endif
#ifdef SDL_SENSOR_N3DS
    &SDL_N3DS_SensorDriver,
#endif
#if defined(SDL_SENSOR_DUMMY) || defined(SDL_SENSOR_DISABLED)
    &SDL_DUMMY_SensorDriver
#endif
};
Referenced by SDL_GetDriverAndSensorIndex(), SDL_GetSensors(), SDL_InitSensors(), SDL_QuitSensors(), and SDL_UpdateSensors().
SDL_sensor_lock
SDL_Mutex* SDL_sensor_lock = NULL static
Referenced by SDL_GUARDED_BY(), SDL_InitSensors(), SDL_LockSensors(), and SDL_UnlockSensors().
SDL_sensor_lock_pending
SDL_AtomicInt SDL_sensor_lock_pending static
Referenced by SDL_LockSensors(), and SDL_UnlockSensors().
SDL_sensors_initialized
bool SDL_sensors_initialized static
Referenced by SDL_InitSensors(), SDL_QuitSensors(), SDL_SensorsInitialized(), and SDL_UnlockSensors().
SDL_sensors_locked
int SDL_sensors_locked static
Referenced by SDL_LockSensors(), SDL_SensorsLocked(), and SDL_UnlockSensors().