SDL3: SDL_uikitviewcontroller Class Reference
SDL_uikitviewcontroller Class Reference
#include <SDL_uikitviewcontroller.h>
Inherits UIViewController.
Instance Methods
(void) - doLoop:
(instancetype) - initWithSDLWindow:
(void) - loadView
(UIRectEdge) - preferredScreenEdgesDeferringSystemGestures
(BOOL) - prefersHomeIndicatorAutoHidden
(BOOL) - prefersStatusBarHidden
(void) - setAnimationCallback:callback:callbackParam:
(void) - startAnimation
(void) - stopAnimation
(NSUInteger) - supportedInterfaceOrientations
(void) - traitCollectionDidChange:
(void) - viewDidLayoutSubviews
Properties
int homeIndicatorHidden
SDL_Window * window
Method Documentation
doLoop:
- (void) doLoop: (CADisplayLink *) sender
References void().
initWithSDLWindow:
- (instancetype) initWithSDLWindow: (SDL_Window *) _window
loadView
- (void) loadView
References loadView, and void().
Referenced by loadView.
preferredScreenEdgesDeferringSystemGestures
- (UIRectEdge) preferredScreenEdgesDeferringSystemGestures
References preferredScreenEdgesDeferringSystemGestures.
Referenced by preferredScreenEdgesDeferringSystemGestures.
prefersHomeIndicatorAutoHidden
- (BOOL) prefersHomeIndicatorAutoHidden
References prefersHomeIndicatorAutoHidden.
Referenced by prefersHomeIndicatorAutoHidden.
prefersStatusBarHidden
- (BOOL) prefersStatusBarHidden
References prefersStatusBarHidden.
Referenced by prefersStatusBarHidden.
setAnimationCallback:callback:callbackParam:
- (void) setAnimationCallback: (int) interval callback: (void(* callback)(void *)) callbackParam: (void *) callbackParam
References void().
startAnimation
- (void) startAnimation
References startAnimation, and void().
Referenced by startAnimation.
stopAnimation
- (void) stopAnimation
References stopAnimation, and void().
Referenced by stopAnimation.
supportedInterfaceOrientations
- (NSUInteger) supportedInterfaceOrientations
References supportedInterfaceOrientations.
Referenced by supportedInterfaceOrientations.
traitCollectionDidChange:
- (void) traitCollectionDidChange: (UITraitCollection *) previousTraitCollection
References void().
viewDidLayoutSubviews
- (void) viewDidLayoutSubviews
References viewDidLayoutSubviews, and void().
Referenced by viewDidLayoutSubviews.
Property Documentation
homeIndicatorHidden
- (int) homeIndicatorHidden read write nonatomic assign
window
- (SDL_Window*) window read write nonatomic assign
The documentation for this class was generated from the following file:
SDL-main/src/video/uikit/SDL_uikitviewcontroller.h