SDL3: SDL-main/src/time/SDL_time.c File Reference
SDL_time.c File Reference
#include "SDL_internal.h"
#include "SDL_time_c.h"
Macros
#define DELTA_EPOCH_1601_100NS (11644473600ll * 10000000ll)
Functions
Sint64 SDL_CivilToDays (int year, int month, int day, int *day_of_week, int *day_of_year)
static bool SDL_DateTimeIsValid (const SDL_DateTime *dt)
bool SDL_DateTimeToTime (const SDL_DateTime *dt, SDL_Time *ticks)
bool SDL_GetDateTimeLocalePreferences (SDL_DateFormat *dateFormat, SDL_TimeFormat *timeFormat)
int SDL_GetDayOfWeek (int year, int month, int day)
int SDL_GetDayOfYear (int year, int month, int day)
int SDL_GetDaysInMonth (int year, int month)
SDL_Time SDL_TimeFromWindows (Uint32 dwLowDateTime, Uint32 dwHighDateTime)
void SDL_TimeToWindows (SDL_Time ticks, Uint32 *dwLowDateTime, Uint32 *dwHighDateTime)
Macro Definition Documentation
DELTA_EPOCH_1601_100NS
#define DELTA_EPOCH_1601_100NS (11644473600ll * 10000000ll)
Referenced by SDL_TimeFromWindows(), and SDL_TimeToWindows().
Function Documentation
SDL_CivilToDays()
Sint64 SDL_CivilToDays (int year, int month, int day, int * day_of_week, int * day_of_year)
{
    year -= month <= 2;
    const int era = (year >= 0 ? year : year - 399) / 400;
    const unsigned yoe = (unsigned)(year - era * 400);                                  // [0, 399]
    const unsigned doy = (153 * (month > 2 ? month - 3 : month + 9) + 2) / 5 + day - 1; // [0, 365]
    const unsigned doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;                         // [0, 146096]
    const Sint64 z = (Sint64)(era) * 146097 + (Sint64)(doe)-719468;
    if (day_of_week) {
        *day_of_week = (int)(z >= -4 ? (z + 4) % 7 : (z + 5) % 7 + 6);
    }
    if (day_of_year) {
        // This algorithm considers March 1 to be the first day of the year, so offset by Jan + Feb.
        if (doy > 305) {
            // Day 0 is the first day of the year.
            *day_of_year = doy - 306;
        } else {
            const int doy_offset = 59 + (!(year % 4) && ((year % 100) || !(year % 400)));
            *day_of_year = doy + doy_offset;
        }
    }
    return z;
}
Referenced by SDL_DateTimeToTime(), SDL_GetDayOfWeek(), and SDL_GetDayOfYear().
SDL_DateTimeIsValid()
bool SDL_DateTimeIsValid (const SDL_DateTime * dt) static
{
    if (dt->month < 1 || dt->month > 12) {
        SDL_SetError("Malformed SDL_DateTime: month out of range [1-12], current: %i", dt->month);
        return false;
    }
    const int daysInMonth = SDL_GetDaysInMonth(dt->year, dt->month);
    if (dt->day < 1 || dt->day > daysInMonth) {
        SDL_SetError("Malformed SDL_DateTime: day of month out of range [1-%i], current: %i", daysInMonth, dt->month);
        return false;
    }
    if (dt->hour < 0 || dt->hour > 23) {
        SDL_SetError("Malformed SDL_DateTime: hour out of range [0-23], current: %i", dt->hour);
        return false;
    }
    if (dt->minute < 0 || dt->minute > 59) {
        SDL_SetError("Malformed SDL_DateTime: minute out of range [0-59], current: %i", dt->minute);
        return false;
    }
    if (dt->second < 0 || dt->second > 60) {
        SDL_SetError("Malformed SDL_DateTime: second out of range [0-60], current: %i", dt->second);
        return false; // 60 accounts for a possible leap second.
    }
    if (dt->nanosecond < 0 || dt->nanosecond >= SDL_NS_PER_SECOND) {
        SDL_SetError("Malformed SDL_DateTime: nanosecond out of range [0-999999999], current: %i", dt->nanosecond);
        return false;
    }
    return true;
}
References SDL_DateTime::day, SDL_DateTime::hour, SDL_DateTime::minute, SDL_DateTime::month, SDL_DateTime::nanosecond, SDL_GetDaysInMonth(), SDL_NS_PER_SECOND, SDL_SetError(), SDL_DateTime::second, and SDL_DateTime::year.
Referenced by SDL_DateTimeToTime().
SDL_DateTimeToTime()
bool SDL_DateTimeToTime (const SDL_DateTime * dt, SDL_Time * ticks)
Converts a calendar time to an SDL_Time in nanoseconds since the epoch.
This function ignores the day_of_week member of the SDL_DateTime struct, so it may remain unset.
Parameters
dt the source SDL_DateTime.
ticks the resulting SDL_Time.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    static const Sint64 max_seconds = SDL_NS_TO_SECONDS(SDL_MAX_TIME) - 1;
    static const Sint64 min_seconds = SDL_NS_TO_SECONDS(SDL_MIN_TIME) + 1;
    bool result = true;
    if (!dt) {
        return SDL_InvalidParamError("dt");
    }
    if (!ticks) {
        return SDL_InvalidParamError("ticks");
    }
    if (!SDL_DateTimeIsValid(dt)) {
        // The validation function sets the error string.
        return false;
    }
    *ticks = SDL_CivilToDays(dt->year, dt->month, dt->day, NULL, NULL) * SDL_SECONDS_PER_DAY;
    *ticks += (((dt->hour * 60) + dt->minute) * 60) + dt->second - dt->utc_offset;
    if (*ticks > max_seconds || *ticks < min_seconds) {
        *ticks = SDL_clamp(*ticks, min_seconds, max_seconds);
        result = SDL_SetError("Date out of range for SDL_Time representation; SDL_Time value clamped");
    }
    *ticks = SDL_SECONDS_TO_NS(*ticks) + dt->nanosecond;
    return result;
}
References SDL_DateTime::day, SDL_DateTime::hour, SDL_DateTime::minute, SDL_DateTime::month, SDL_DateTime::nanosecond, NULL, SDL_CivilToDays(), SDL_clamp, SDL_DateTimeIsValid(), SDL_InvalidParamError, SDL_MAX_TIME, SDL_MIN_TIME, SDL_NS_TO_SECONDS, SDL_SECONDS_PER_DAY, SDL_SECONDS_TO_NS, SDL_SetError(), SDL_DateTime::second, SDL_DateTime::utc_offset, and SDL_DateTime::year.
SDL_GetDateTimeLocalePreferences()
bool SDL_GetDateTimeLocalePreferences (SDL_DateFormat * dateFormat, SDL_TimeFormat * timeFormat)
Gets the current preferred date and time format for the system locale.
This might be a "slow" call that has to query the operating system. It's best to ask for this once and save the results. However, the preferred formats can change, usually because the user has changed a system preference outside of your program.
Parameters
dateFormat a pointer to the SDL_DateFormat to hold the returned date format, may be NULL.
timeFormat a pointer to the SDL_TimeFormat to hold the returned time format, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    // Default to ISO 8061 date format, as it is unambiguous, and 24 hour time.
    if (dateFormat) {
        *dateFormat = SDL_DATE_FORMAT_YYYYMMDD;
    }
    if (timeFormat) {
        *timeFormat = SDL_TIME_FORMAT_24HR;
    }
    SDL_GetSystemTimeLocalePreferences(dateFormat, timeFormat);
    return true;
}
References SDL_DATE_FORMAT_YYYYMMDD, SDL_GetSystemTimeLocalePreferences(), and SDL_TIME_FORMAT_24HR.
SDL_GetDayOfWeek()
int SDL_GetDayOfWeek (int year, int month, int day)
Get the day of week for a calendar date.
Parameters
year the year component of the date.
month the month component of the date.
day the day component of the date.
Returns
a value between 0 and 6 (0 being Sunday) if the date is valid or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    int dayOfWeek;
    if (month < 1 || month > 12) {
        SDL_SetError("Month out of range [1-12], requested: %i", month);
        return -1;
    }
    if (day < 1 || day > SDL_GetDaysInMonth(year, month)) {
        SDL_SetError("Day out of range [1-%i], requested: %i", SDL_GetDaysInMonth(year, month), month);
        return -1;
    }
    SDL_CivilToDays(year, month, day, &dayOfWeek, NULL);
    return dayOfWeek;
}
References NULL, SDL_CivilToDays(), SDL_GetDaysInMonth(), and SDL_SetError().
SDL_GetDayOfYear()
int SDL_GetDayOfYear (int year, int month, int day)
Get the day of year for a calendar date.
Parameters
year the year component of the date.
month the month component of the date.
day the day component of the date.
Returns
the day of year [0-365] if the date is valid or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    int dayOfYear;
    if (month < 1 || month > 12) {
        SDL_SetError("Month out of range [1-12], requested: %i", month);
        return -1;
    }
    if (day < 1 || day > SDL_GetDaysInMonth(year, month)) {
        SDL_SetError("Day out of range [1-%i], requested: %i", SDL_GetDaysInMonth(year, month), month);
        return -1;
    }
    SDL_CivilToDays(year, month, day, NULL, &dayOfYear);
    return dayOfYear;
}
References NULL, SDL_CivilToDays(), SDL_GetDaysInMonth(), and SDL_SetError().
SDL_GetDaysInMonth()
int SDL_GetDaysInMonth (int year, int month)
Get the number of days in a month for a given year.
Parameters
year the year.
month the month [1-12].
Returns
the number of days in the requested month or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    static const int DAYS_IN_MONTH[] = {
        31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31
    };
    if (month < 1 || month > 12) {
        SDL_SetError("Month out of range [1-12], requested: %i", month);
        return -1;
    }
    int days = DAYS_IN_MONTH[month - 1];
    /* A leap year occurs every 4 years...
     * but not every 100 years...
     * except for every 400 years.
     */
    if (month == 2 && (!(year % 4) && ((year % 100) || !(year % 400)))) {
        ++days;
    }
    return days;
}
References SDL_SetError().
Referenced by SDL_DateTimeIsValid(), SDL_GetDayOfWeek(), and SDL_GetDayOfYear().
SDL_TimeFromWindows()
SDL_Time SDL_TimeFromWindows (Uint32 dwLowDateTime, Uint32 dwHighDateTime)
Converts a Windows FILETIME (100-nanosecond intervals since January 1, 1601) to an SDL time.
This function takes the two 32-bit values of the FILETIME structure as parameters.
Parameters
dwLowDateTime the low portion of the Windows FILETIME value.
dwHighDateTime the high portion of the Windows FILETIME value.
Returns
the converted SDL time.
Since
This function is available since SDL 3.2.0.
{
    static const Uint64 wintime_min = (Uint64)((SDL_MIN_TIME / 100) + DELTA_EPOCH_1601_100NS);
    static const Uint64 wintime_max = (Uint64)((SDL_MAX_TIME / 100) + DELTA_EPOCH_1601_100NS);
    Uint64 wtime = (((Uint64)dwHighDateTime << 32) | dwLowDateTime);
    // Clamp the windows time range to the SDL_Time min/max
    wtime = SDL_clamp(wtime, wintime_min, wintime_max);
    return (SDL_Time)(wtime - DELTA_EPOCH_1601_100NS) * 100;
}
References DELTA_EPOCH_1601_100NS, SDL_clamp, SDL_MAX_TIME, and SDL_MIN_TIME.
SDL_TimeToWindows()
void SDL_TimeToWindows (SDL_Time ticks, Uint32 * dwLowDateTime, Uint32 * dwHighDateTime)
Converts an SDL time into a Windows FILETIME (100-nanosecond intervals since January 1, 1601).
This function fills in the two 32-bit values of the FILETIME structure.
Parameters
ticks the time to convert.
dwLowDateTime a pointer filled in with the low portion of the Windows FILETIME value.
dwHighDateTime a pointer filled in with the high portion of the Windows FILETIME value.
Since
This function is available since SDL 3.2.0.
{
    /* Convert nanoseconds to Win32 ticks.
     * SDL_Time has a range of roughly 292 years, so even SDL_MIN_TIME can't underflow the Win32 epoch.
     */
    const Uint64 wtime = (Uint64)((ticks / 100) + DELTA_EPOCH_1601_100NS);
    if (dwLowDateTime) {
        *dwLowDateTime = (Uint32)wtime;
    }
    if (dwHighDateTime) {
        *dwHighDateTime = (Uint32)(wtime >> 32);
    }
}
References DELTA_EPOCH_1601_100NS.