SDL3: SDL_VideoData Struct Reference
SDL_VideoData Struct Reference
#include <SDL_x11video.h>
Public Member Functions
BOOL (WINAPI *AdjustWindowRectExForDpi)(LPRECT
BOOL (WINAPI *AreDpiAwarenessContextsEqual)(DPI_AWARENESS_CONTEXT
BOOL (WINAPI *CloseTouchInputHandle)(HTOUCHINPUT)
BOOL (WINAPI *EnableNonClientDpiScaling)(HWND)
BOOL (WINAPI *GetPointerPenInfo)(UINT32 pointerId
BOOL (WINAPI *GetPointerType)(UINT32 pointerId
BOOL (WINAPI *GetTouchInputInfo)(HTOUCHINPUT
BOOL (WINAPI *ImmUnlockIMC)(HIMC himc)
BOOL (WINAPI *ImmUnlockIMCC)(HIMCC himcc)
BOOL (WINAPI *IsValidDpiAwarenessContext)(DPI_AWARENESS_CONTEXT)
BOOL (WINAPI *RegisterTouchWindow)(HWND
BOOL (WINAPI *SetProcessDPIAware)(void)
BOOL (WINAPI *SetProcessDpiAwarenessContext)(DPI_AWARENESS_CONTEXT)
BOOL (WINAPI *ShowReadingWindow)(HIMC himc
DPI_AWARENESS (WINAPI *GetAwarenessFromDpiAwarenessContext)(DPI_AWARENESS_CONTEXT)
DPI_AWARENESS_CONTEXT (WINAPI *GetThreadDpiAwarenessContext)(void)
DPI_AWARENESS_CONTEXT (WINAPI *SetThreadDpiAwarenessContext)(DPI_AWARENESS_CONTEXT)
EGLNativeDisplayType (EGLAPIENTRY *fbGetDisplay)(void *context)
EGLNativeDisplayType (EGLAPIENTRY *fbGetDisplayByIndex)(int DisplayIndex)
EGLNativeWindowType (EGLAPIENTRY *fbCreateWindow)(EGLNativeDisplayType Display
HRESULT (WINAPI *DwmEnableBlurBehindWindow)(HWND hwnd
HRESULT (WINAPI *DwmFlush)(void)
HRESULT (WINAPI *DwmSetWindowAttribute)(HWND hwnd
HRESULT (WINAPI *GetDpiForMonitor)(HMONITOR hmonitor
HRESULT (WINAPI *SetProcessDpiAwareness)(PROCESS_DPI_AWARENESS dpiAwareness)
UINT32 UINT32 UINT32 DISPLAYCONFIG_PATH_INFO UINT32 DISPLAYCONFIG_MODE_INFO DISPLAYCONFIG_TOPOLOGY_ID * LONG (WINAPI *DisplayConfigGetDeviceInfo)(DISPLAYCONFIG_DEVICE_INFO_HEADER *)
LONG (WINAPI *GetDisplayConfigBufferSizes)(UINT32
UINT32 UINT32 * LONG (WINAPI *QueryDisplayConfig)(UINT32
LPINPUTCONTEXT2 (WINAPI *ImmLockIMC)(HIMC himc)
LPVOID (WINAPI *ImmLockIMCC)(HIMCC himcc)
UINT (WINAPI *GetDpiForWindow)(HWND)
UINT (WINAPI *GetReadingString)(HIMC himc
void (EGLAPIENTRY *fbDestroyDisplay)(EGLNativeDisplayType Display)
void (EGLAPIENTRY *fbDestroyWindow)(EGLNativeWindowType Window)
void (EGLAPIENTRY *fbGetDisplayGeometry)(EGLNativeDisplayType Display
void (EGLAPIENTRY *fbGetDisplayInfo)(EGLNativeDisplayType Display
void (EGLAPIENTRY *fbGetWindowGeometry)(EGLNativeWindowType Window
void (EGLAPIENTRY *fbGetWindowInfo)(EGLNativeWindowType Window
Data Fields
UINT _SDL_WAKEUP
struct xdg_activation_v1 * activation_manager
bool async_pageflip_support
struct {
Atom _NET_ACTIVE_WINDOW
Atom _NET_FRAME_EXTENTS
Atom _NET_WM_ACTION_FULLSCREEN
Atom _NET_WM_ALLOWED_ACTIONS
Atom _NET_WM_ICON
Atom _NET_WM_ICON_NAME
Atom _NET_WM_MOVERESIZE
Atom _NET_WM_NAME
Atom _NET_WM_PING
Atom _NET_WM_STATE
Atom _NET_WM_STATE_ABOVE
Atom _NET_WM_STATE_FOCUSED
Atom _NET_WM_STATE_FULLSCREEN
Atom _NET_WM_STATE_HIDDEN
Atom _NET_WM_STATE_MAXIMIZED_HORZ
Atom _NET_WM_STATE_MAXIMIZED_VERT
Atom _NET_WM_STATE_MODAL
Atom _NET_WM_STATE_SKIP_PAGER
Atom _NET_WM_STATE_SKIP_TASKBAR
Atom _NET_WM_SYNC_REQUEST
Atom _NET_WM_SYNC_REQUEST_COUNTER
Atom _NET_WM_USER_TIME
Atom _NET_WM_WINDOW_OPACITY
Atom _SDL_WAKEUP
Atom CLIPBOARD
Atom INCR
Atom pen_atom_abs_pressure
Atom pen_atom_abs_tilt_x
Atom pen_atom_abs_tilt_y
Atom pen_atom_device_product_id
Atom pen_atom_wacom_serial_ids
Atom pen_atom_wacom_tool_type
Atom PRIMARY
Atom SDL_FORMATS
Atom SDL_SELECTION
Atom TARGETS
Atom UTF8_STRING
Atom WM_DELETE_WINDOW
Atom WM_NAME
Atom WM_PROTOCOLS
Atom WM_TAKE_FOCUS
Atom WM_TRANSIENT_FOR
Atom XdndActionCopy
Atom XdndAware
Atom XdndDrop
Atom XdndEnter
Atom XdndFinished
Atom XdndLeave
Atom XdndPosition
Atom XdndSelection
Atom XdndStatus
Atom XdndTypeList
Atom XKLAVIER_STATE
} atoms
bool bDidCreateOverlay
bool bHasShownOverlay
bool bIconOverridden
int int unsigned long int int * bits_per_pixel
int int int int int * bits_per_pixel
bool bKeyboardShown
BOOL
bool broken_pointer_grab
BOOL bShow
DWORD LPCVOID DWORD cbAttribute
bool cleared
SDLX11_ClipboardData clipboard
DWORD clipboard_count
Window clipboard_window
bool coinitialized
struct wl_compositor * compositor
struct wp_cursor_shape_manager_v1 * cursor_shape_manager
SDL_WaylandCursorTheme * cursor_themes
VROverlayHandle_t cursorID
struct wl_data_device_manager * data_device_manager
struct zxdg_decoration_manager_v1 * decoration_manager
int devindex
char devpath [32]
struct wl_display * display
Display * display
int display_disconnected
bool display_externally_owned
DPI_AWARENESS_CONTEXT
MONITOR_DPI_TYPE dpiType
MONITOR_DPI_TYPE UINT * dpiX
MONITOR_DPI_TYPE UINT UINT * dpiY
int drm_fd
DWORD dwAttribute
SDL_SharedObject * dwmapiDLL
DWORD
SDL_SharedObject * egl_handle
bool egl_initialized
uint32_t egl_refcount
EGLContext eglCtx
EGLDisplay eglDpy
unsigned int fbo
KeyCode filter_code
Time filter_time
intptr_t(* FN_VR_GetGenericInterface)(const char *pchInterfaceVersion, EVRInitError *peError)
const char *(* FN_VR_GetVRInitErrorAsEnglishDescription)(EVRInitError error)
intptr_t(* FN_VR_InitInternal)(EVRInitError *peError, EVRApplicationType eType)
struct wp_fractional_scale_manager_v1 * fractional_scale_manager
struct frog_color_management_factory_v1 * frog_color_management_factory_v1
WIN_GameInputData * gameinput_context
struct gbm_device * gbm_dev
bool gbm_init
Uint32 global_mouse_buttons
bool global_mouse_changed
SDL_Point global_mouse_position
int int * Height
int int int int Height
int int int int * Height
struct zwp_idle_inhibit_manager_v1 * idle_inhibit_manager
XIM im
bool ime_active
bool ime_available
SceWChar16 ime_buffer [SCE_IME_DIALOG_MAX_TEXT_LENGTH]
int ime_candcount
CANDIDATEFORM ime_candidate_area
char * ime_candidates [10]
bool ime_candidates_open
int ime_candlistindexbase
DWORD ime_candref
DWORD ime_candsel
WCHAR * ime_composition
COMPOSITIONFORM ime_composition_area
int ime_composition_length
int ime_cursor
bool ime_enabled
HIMC ime_himc
SDL_SharedObject * ime_himm32
HKL ime_hkl
bool ime_horizontal_candidates
HWND ime_hwnd_current
HWND ime_hwnd_main
bool ime_initialized
bool ime_internal_candidates
bool ime_internal_composition
bool ime_needs_clear_composition
WCHAR ime_readingstring [16]
int ime_selected_length
int ime_selected_start
bool ime_update_candidates
bool initializing
VRActionHandle_t * input_action_handles_axes
int input_action_handles_axes_count
VRActionHandle_t * input_action_handles_buttons
int input_action_handles_buttons_count
VRActionHandle_t input_action_handles_haptics [2]
VRActionSetHandle_t input_action_set
struct zwp_input_timestamps_manager_v1 * input_timestamps_manager
int
int is_buffer_rendering
bool is_steam_deck
bool is_xwayland
int isPaused
int isPausing
struct zwp_keyboard_shortcuts_inhibit_manager_v1 * key_inhibitor_manager
SDL_Scancode key_layout [256]
Uint8 key_pressed [6]
struct SDL_WaylandSeat * last_implicit_grab_seat
struct SDL_WaylandSeat * last_incoming_data_offer_seat
struct SDL_WaylandSeat * last_incoming_primary_selection_seat
Uint64 last_mode_change_deadline
int last_mouse_buttons
SDL_Point last_raw_mouse_position
Uint64 last_rawinput_poll
int last_targh
int last_targw
UINT LPWSTR lpwReadingBuf
int max_windows
SDL_XInput2DeviceInfo * mouse_device_info
bool net_wm
int num_cursor_themes
int num_windows
int numwindows
int int int int int unsigned int * Offset
struct VR_IVRInput_FnTable * oInput
bool oleinitialized
struct VR_IVROverlay_FnTable * oOverlay
void * openVRLIB
struct VR_IVRSystem_FnTable * oSystem
int output_count
SDL_DisplayData ** output_list
int output_max
VROverlayHandle_t overlayID
unsigned int overlaytexture
const DWM_BLURBEHIND * pBlurBehind
bool pending_E1_key_sequence
POINTER_PEN_INFO * penInfo
UINT LPWSTR PINT BOOL * pfIsVertical
int int unsigned long * Physical
pid_t pid
UINT LPWSTR PINT pnErrorIndex
struct zwp_pointer_constraints_v1 * pointer_constraints
POINTER_INPUT_TYPE * pointerType
BYTE pre_hook_key_state [256]
SDLX11_ClipboardData primary_selection
struct zwp_primary_selection_device_manager_v1 * primary_selection_device_manager
PTOUCHINPUT
UINT LPWSTR PINT BOOL PUINT puMaxReadingLen
DWORD LPCVOID pvAttribute
Uint32 raw_input_enabled
bool raw_keyboard_enabled
bool raw_mouse_enabled
BYTE * rawinput
UINT rawinput_count
UINT rawinput_offset
UINT rawinput_size
unsigned int rbo
struct wl_registry * registry
struct zwp_relative_pointer_manager_v1 * relative_pointer_manager
int render
bool renderdoc_debugmarker_frame_end
Display * request_display
int saved_texture_state
bool scale_to_display_enabled
Uint64 screensaver_activity
struct wl_list seat_list
bool selection_incr_waiting
bool selection_waiting
SDL_SharedObject * shcoreDLL
struct {
struct xdg_wm_base * xdg
} shell
struct wl_shm * shm
char * sOverlayName
bool steam_keyboard_open
int int unsigned long int * Stride
int swap_interval
struct zwp_tablet_manager_v2 * tablet_manager
int targh
int targw
struct zwp_text_input_manager_v3 * text_input_manager
VROverlayHandle_t thumbID
int top_display
int touch_display
UINT
ULONG
UINT uReadingBufLen
SDL_SharedObject * userDLL
bool video_init
struct wp_viewporter * viewporter
SDL_Joystick * virtual_joystick
intptr_t vrtoken
bool vulkan_mode
int * Width
int int int Width
int int int * Width
SDL_Window * window
XID window_group
SDL_WindowData ** windowlist
int windowlistlength
SDL_Window ** windows
struct wl_fixes * wl_fixes
struct wp_alpha_modifier_v1 * wp_alpha_modifier_v1
struct wp_color_manager_v1 * wp_color_manager_v1
struct wp_pointer_warp_v1 * wp_pointer_warp_v1
int X
int * X
struct zxdg_output_manager_v1 * xdg_output_manager
struct xdg_toplevel_icon_manager_v1 * xdg_toplevel_icon_manager_v1
struct xdg_wm_dialog_v1 * xdg_wm_dialog_v1
bool xinput_hierarchy_changed
int xinput_master_pointer_device
struct {
unsigned int current_group
int event
Uint32 numlock_mask
Uint32 scrolllock_mask
SDL_Keymod sdl_modifiers
unsigned int xkb_modifiers
} xkb
struct xkb_context * xkb_context
int xrandr_event_base
SDLX11_SettingsData xsettings_data
Window xsettings_window
int int Y
int int * Y
struct zxdg_exporter_v2 * zxdg_exporter_v2
Member Function Documentation
BOOL() [1/14]
SDL_VideoData::BOOL (WINAPI * AdjustWindowRectExForDpi)
BOOL() [2/14]
SDL_VideoData::BOOL (WINAPI * AreDpiAwarenessContextsEqual)
References DPI_AWARENESS_CONTEXT.
BOOL() [3/14]
SDL_VideoData::BOOL (WINAPI * CloseTouchInputHandle)
BOOL() [4/14]
SDL_VideoData::BOOL (WINAPI * EnableNonClientDpiScaling)
BOOL() [5/14]
SDL_VideoData::BOOL (WINAPI * GetPointerPenInfo)
References penInfo.
BOOL() [6/14]
SDL_VideoData::BOOL (WINAPI * GetPointerType)
References pointerType.
BOOL() [7/14]
SDL_VideoData::BOOL (WINAPI * GetTouchInputInfo)
References int, PTOUCHINPUT, and UINT.
BOOL() [8/14]
SDL_VideoData::BOOL (WINAPI * ImmUnlockIMC)
BOOL() [9/14]
SDL_VideoData::BOOL (WINAPI * ImmUnlockIMCC)
BOOL() [10/14]
SDL_VideoData::BOOL (WINAPI * IsValidDpiAwarenessContext)
References DPI_AWARENESS_CONTEXT.
BOOL() [11/14]
SDL_VideoData::BOOL (WINAPI * RegisterTouchWindow)
References ULONG.
BOOL() [12/14]
SDL_VideoData::BOOL (WINAPI * SetProcessDPIAware)
References void().
BOOL() [13/14]
SDL_VideoData::BOOL (WINAPI * SetProcessDpiAwarenessContext)
References DPI_AWARENESS_CONTEXT.
BOOL() [14/14]
SDL_VideoData::BOOL (WINAPI * ShowReadingWindow)
References BOOL, and bShow.
DPI_AWARENESS()
SDL_VideoData::DPI_AWARENESS (WINAPI * GetAwarenessFromDpiAwarenessContext)
References DPI_AWARENESS_CONTEXT.
DPI_AWARENESS_CONTEXT() [1/2]
SDL_VideoData::DPI_AWARENESS_CONTEXT (WINAPI * GetThreadDpiAwarenessContext)
References void().
DPI_AWARENESS_CONTEXT() [2/2]
SDL_VideoData::DPI_AWARENESS_CONTEXT (WINAPI * SetThreadDpiAwarenessContext)
References DPI_AWARENESS_CONTEXT.
EGLNativeDisplayType() [1/2]
SDL_VideoData::EGLNativeDisplayType (EGLAPIENTRY * fbGetDisplay)
References context, and EGLAPIENTRY.
Referenced by EGLNativeWindowType(), and void().
EGLNativeDisplayType() [2/2]
SDL_VideoData::EGLNativeDisplayType (EGLAPIENTRY * fbGetDisplayByIndex)
References EGLAPIENTRY.
EGLNativeWindowType()
SDL_VideoData::EGLNativeWindowType (EGLAPIENTRY * fbCreateWindow)
References EGLAPIENTRY, EGLNativeDisplayType(), Height, Width, X, and Y.
Referenced by void().
HRESULT() [1/5]
SDL_VideoData::HRESULT (WINAPI * DwmEnableBlurBehindWindow)
References pBlurBehind.
HRESULT() [2/5]
SDL_VideoData::HRESULT (WINAPI * DwmFlush)
References void().
HRESULT() [3/5]
SDL_VideoData::HRESULT (WINAPI * DwmSetWindowAttribute)
HRESULT() [4/5]
SDL_VideoData::HRESULT (WINAPI * GetDpiForMonitor)
HRESULT() [5/5]
SDL_VideoData::HRESULT (WINAPI * SetProcessDpiAwareness)
LONG() [1/3]
UINT32 UINT32 UINT32 DISPLAYCONFIG_PATH_INFO UINT32 DISPLAYCONFIG_MODE_INFO DISPLAYCONFIG_TOPOLOGY_ID * SDL_VideoData::LONG (WINAPI * DisplayConfigGetDeviceInfo)
LONG() [2/3]
SDL_VideoData::LONG (WINAPI * GetDisplayConfigBufferSizes)
LONG() [3/3]
UINT32 UINT32 * SDL_VideoData::LONG (WINAPI * QueryDisplayConfig)
LPINPUTCONTEXT2()
SDL_VideoData::LPINPUTCONTEXT2 (WINAPI * ImmLockIMC)
LPVOID()
SDL_VideoData::LPVOID (WINAPI * ImmLockIMCC)
UINT() [1/2]
SDL_VideoData::UINT (WINAPI * GetDpiForWindow)
UINT() [2/2]
SDL_VideoData::UINT (WINAPI * GetReadingString)
void() [1/6]
SDL_VideoData::void (EGLAPIENTRY * fbDestroyDisplay)
References EGLAPIENTRY, and EGLNativeDisplayType().
void() [2/6]
SDL_VideoData::void (EGLAPIENTRY * fbDestroyWindow)
References EGLAPIENTRY, and EGLNativeWindowType().
void() [3/6]
SDL_VideoData::void (EGLAPIENTRY * fbGetDisplayGeometry)
Referenced by BOOL(), DPI_AWARENESS_CONTEXT(), and HRESULT().
void() [4/6]
SDL_VideoData::void (EGLAPIENTRY * fbGetDisplayInfo)
void() [5/6]
SDL_VideoData::void (EGLAPIENTRY * fbGetWindowGeometry)
void() [6/6]
SDL_VideoData::void (EGLAPIENTRY * fbGetWindowInfo)
Field Documentation
_NET_ACTIVE_WINDOW
Atom SDL_VideoData::_NET_ACTIVE_WINDOW
_NET_FRAME_EXTENTS
Atom SDL_VideoData::_NET_FRAME_EXTENTS
_NET_WM_ACTION_FULLSCREEN
Atom SDL_VideoData::_NET_WM_ACTION_FULLSCREEN
_NET_WM_ALLOWED_ACTIONS
Atom SDL_VideoData::_NET_WM_ALLOWED_ACTIONS
_NET_WM_ICON
Atom SDL_VideoData::_NET_WM_ICON
_NET_WM_ICON_NAME
Atom SDL_VideoData::_NET_WM_ICON_NAME
_NET_WM_MOVERESIZE
Atom SDL_VideoData::_NET_WM_MOVERESIZE
_NET_WM_NAME
Atom SDL_VideoData::_NET_WM_NAME
_NET_WM_PING
Atom SDL_VideoData::_NET_WM_PING
_NET_WM_STATE
Atom SDL_VideoData::_NET_WM_STATE
_NET_WM_STATE_ABOVE
Atom SDL_VideoData::_NET_WM_STATE_ABOVE
_NET_WM_STATE_FOCUSED
Atom SDL_VideoData::_NET_WM_STATE_FOCUSED
_NET_WM_STATE_FULLSCREEN
Atom SDL_VideoData::_NET_WM_STATE_FULLSCREEN
_NET_WM_STATE_HIDDEN
Atom SDL_VideoData::_NET_WM_STATE_HIDDEN
_NET_WM_STATE_MAXIMIZED_HORZ
Atom SDL_VideoData::_NET_WM_STATE_MAXIMIZED_HORZ
_NET_WM_STATE_MAXIMIZED_VERT
Atom SDL_VideoData::_NET_WM_STATE_MAXIMIZED_VERT
_NET_WM_STATE_MODAL
Atom SDL_VideoData::_NET_WM_STATE_MODAL
_NET_WM_STATE_SKIP_PAGER
Atom SDL_VideoData::_NET_WM_STATE_SKIP_PAGER
_NET_WM_STATE_SKIP_TASKBAR
Atom SDL_VideoData::_NET_WM_STATE_SKIP_TASKBAR
_NET_WM_SYNC_REQUEST
Atom SDL_VideoData::_NET_WM_SYNC_REQUEST
_NET_WM_SYNC_REQUEST_COUNTER
Atom SDL_VideoData::_NET_WM_SYNC_REQUEST_COUNTER
_NET_WM_USER_TIME
Atom SDL_VideoData::_NET_WM_USER_TIME
_NET_WM_WINDOW_OPACITY
Atom SDL_VideoData::_NET_WM_WINDOW_OPACITY
_SDL_WAKEUP [1/2]
UINT SDL_VideoData::_SDL_WAKEUP
_SDL_WAKEUP [2/2]
Atom SDL_VideoData::_SDL_WAKEUP
activation_manager
struct xdg_activation_v1* SDL_VideoData::activation_manager
async_pageflip_support
bool SDL_VideoData::async_pageflip_support
[struct]
struct { ... } SDL_VideoData::atoms
bDidCreateOverlay
bool SDL_VideoData::bDidCreateOverlay
bHasShownOverlay
bool SDL_VideoData::bHasShownOverlay
bIconOverridden
bool SDL_VideoData::bIconOverridden
bits_per_pixel [1/2]
int int unsigned long int int* SDL_VideoData::bits_per_pixel
bits_per_pixel [2/2]
int int int int int* SDL_VideoData::bits_per_pixel
bKeyboardShown
bool SDL_VideoData::bKeyboardShown
BOOL
SDL_VideoData::BOOL
Referenced by BOOL().
broken_pointer_grab
bool SDL_VideoData::broken_pointer_grab
bShow
BOOL SDL_VideoData::bShow
Referenced by BOOL().
cbAttribute
DWORD LPCVOID DWORD SDL_VideoData::cbAttribute
cleared
bool SDL_VideoData::cleared
CLIPBOARD
Atom SDL_VideoData::CLIPBOARD
clipboard
SDLX11_ClipboardData SDL_VideoData::clipboard
clipboard_count
DWORD SDL_VideoData::clipboard_count
clipboard_window
Window SDL_VideoData::clipboard_window
coinitialized
bool SDL_VideoData::coinitialized
compositor
struct wl_compositor* SDL_VideoData::compositor
current_group
unsigned int SDL_VideoData::current_group
cursor_shape_manager
struct wp_cursor_shape_manager_v1* SDL_VideoData::cursor_shape_manager
cursor_themes
SDL_WaylandCursorTheme* SDL_VideoData::cursor_themes
cursorID
VROverlayHandle_t SDL_VideoData::cursorID
data_device_manager
struct wl_data_device_manager* SDL_VideoData::data_device_manager
decoration_manager
struct zxdg_decoration_manager_v1* SDL_VideoData::decoration_manager
devindex
int SDL_VideoData::devindex
devpath
char SDL_VideoData::devpath[32]
display [1/2]
struct wl_display* SDL_VideoData::display
display [2/2]
Display* SDL_VideoData::display
display_disconnected
int SDL_VideoData::display_disconnected
display_externally_owned
bool SDL_VideoData::display_externally_owned
DPI_AWARENESS_CONTEXT
SDL_VideoData::DPI_AWARENESS_CONTEXT
Referenced by BOOL(), BOOL(), BOOL(), DPI_AWARENESS(), and DPI_AWARENESS_CONTEXT().
dpiType
MONITOR_DPI_TYPE SDL_VideoData::dpiType
dpiX
MONITOR_DPI_TYPE UINT* SDL_VideoData::dpiX
dpiY
MONITOR_DPI_TYPE UINT UINT* SDL_VideoData::dpiY
drm_fd
int SDL_VideoData::drm_fd
dwAttribute
DWORD SDL_VideoData::dwAttribute
dwmapiDLL
SDL_SharedObject* SDL_VideoData::dwmapiDLL
DWORD
SDL_VideoData::DWORD
egl_handle
SDL_SharedObject* SDL_VideoData::egl_handle
egl_initialized
bool SDL_VideoData::egl_initialized
egl_refcount
uint32_t SDL_VideoData::egl_refcount
eglCtx
EGLContext SDL_VideoData::eglCtx
eglDpy
EGLDisplay SDL_VideoData::eglDpy
event
int SDL_VideoData::event
fbo
unsigned int SDL_VideoData::fbo
filter_code
KeyCode SDL_VideoData::filter_code
filter_time
Time SDL_VideoData::filter_time
FN_VR_GetGenericInterface
intptr_t(* SDL_VideoData::FN_VR_GetGenericInterface) (const char *pchInterfaceVersion, EVRInitError *peError)
FN_VR_GetVRInitErrorAsEnglishDescription
const char *(* SDL_VideoData::FN_VR_GetVRInitErrorAsEnglishDescription) (EVRInitError error)
FN_VR_InitInternal
intptr_t(* SDL_VideoData::FN_VR_InitInternal) (EVRInitError *peError, EVRApplicationType eType)
fractional_scale_manager
struct wp_fractional_scale_manager_v1* SDL_VideoData::fractional_scale_manager
frog_color_management_factory_v1
struct frog_color_management_factory_v1* SDL_VideoData::frog_color_management_factory_v1
gameinput_context
WIN_GameInputData* SDL_VideoData::gameinput_context
gbm_dev
struct gbm_device* SDL_VideoData::gbm_dev
gbm_init
bool SDL_VideoData::gbm_init
global_mouse_buttons
Uint32 SDL_VideoData::global_mouse_buttons
global_mouse_changed
bool SDL_VideoData::global_mouse_changed
global_mouse_position
SDL_Point SDL_VideoData::global_mouse_position
Height [1/3]
int int int int * SDL_VideoData::Height
Referenced by EGLNativeWindowType().
Height [2/3]
int int int int SDL_VideoData::Height
Height [3/3]
int int int int* SDL_VideoData::Height
idle_inhibit_manager
struct zwp_idle_inhibit_manager_v1* SDL_VideoData::idle_inhibit_manager
im
XIM SDL_VideoData::im
ime_active
bool SDL_VideoData::ime_active
ime_available
bool SDL_VideoData::ime_available
ime_buffer
SceWChar16 SDL_VideoData::ime_buffer[SCE_IME_DIALOG_MAX_TEXT_LENGTH]
ime_candcount
int SDL_VideoData::ime_candcount
ime_candidate_area
CANDIDATEFORM SDL_VideoData::ime_candidate_area
ime_candidates
char* SDL_VideoData::ime_candidates[10]
ime_candidates_open
bool SDL_VideoData::ime_candidates_open
ime_candlistindexbase
int SDL_VideoData::ime_candlistindexbase
ime_candref
DWORD SDL_VideoData::ime_candref
ime_candsel
DWORD SDL_VideoData::ime_candsel
ime_composition
WCHAR* SDL_VideoData::ime_composition
ime_composition_area
COMPOSITIONFORM SDL_VideoData::ime_composition_area
ime_composition_length
int SDL_VideoData::ime_composition_length
ime_cursor
int SDL_VideoData::ime_cursor
ime_enabled
bool SDL_VideoData::ime_enabled
ime_himc
HIMC SDL_VideoData::ime_himc
ime_himm32
SDL_SharedObject* SDL_VideoData::ime_himm32
ime_hkl
HKL SDL_VideoData::ime_hkl
ime_horizontal_candidates
bool SDL_VideoData::ime_horizontal_candidates
ime_hwnd_current
HWND SDL_VideoData::ime_hwnd_current
ime_hwnd_main
HWND SDL_VideoData::ime_hwnd_main
ime_initialized
bool SDL_VideoData::ime_initialized
ime_internal_candidates
bool SDL_VideoData::ime_internal_candidates
ime_internal_composition
bool SDL_VideoData::ime_internal_composition
ime_needs_clear_composition
bool SDL_VideoData::ime_needs_clear_composition
ime_readingstring
WCHAR SDL_VideoData::ime_readingstring[16]
ime_selected_length
int SDL_VideoData::ime_selected_length
ime_selected_start
int SDL_VideoData::ime_selected_start
ime_update_candidates
bool SDL_VideoData::ime_update_candidates
INCR
Atom SDL_VideoData::INCR
initializing
bool SDL_VideoData::initializing
input_action_handles_axes
VRActionHandle_t* SDL_VideoData::input_action_handles_axes
input_action_handles_axes_count
int SDL_VideoData::input_action_handles_axes_count
input_action_handles_buttons
VRActionHandle_t* SDL_VideoData::input_action_handles_buttons
input_action_handles_buttons_count
int SDL_VideoData::input_action_handles_buttons_count
input_action_handles_haptics
VRActionHandle_t SDL_VideoData::input_action_handles_haptics[2]
input_action_set
VRActionSetHandle_t SDL_VideoData::input_action_set
input_timestamps_manager
struct zwp_input_timestamps_manager_v1* SDL_VideoData::input_timestamps_manager
int
SDL_VideoData::int
Referenced by BOOL().
is_buffer_rendering
int SDL_VideoData::is_buffer_rendering
is_steam_deck
bool SDL_VideoData::is_steam_deck
is_xwayland
bool SDL_VideoData::is_xwayland
isPaused
int SDL_VideoData::isPaused
isPausing
int SDL_VideoData::isPausing
key_inhibitor_manager
struct zwp_keyboard_shortcuts_inhibit_manager_v1* SDL_VideoData::key_inhibitor_manager
key_layout
SDL_Scancode SDL_VideoData::key_layout[256]
key_pressed
Uint8 SDL_VideoData::key_pressed[6]
last_implicit_grab_seat
struct SDL_WaylandSeat* SDL_VideoData::last_implicit_grab_seat
last_incoming_data_offer_seat
struct SDL_WaylandSeat* SDL_VideoData::last_incoming_data_offer_seat
last_incoming_primary_selection_seat
struct SDL_WaylandSeat* SDL_VideoData::last_incoming_primary_selection_seat
last_mode_change_deadline
Uint64 SDL_VideoData::last_mode_change_deadline
last_mouse_buttons
int SDL_VideoData::last_mouse_buttons
last_raw_mouse_position
SDL_Point SDL_VideoData::last_raw_mouse_position
last_rawinput_poll
Uint64 SDL_VideoData::last_rawinput_poll
last_targh
int SDL_VideoData::last_targh
last_targw
int SDL_VideoData::last_targw
lpwReadingBuf
UINT LPWSTR SDL_VideoData::lpwReadingBuf
max_windows
int SDL_VideoData::max_windows
mouse_device_info
SDL_XInput2DeviceInfo* SDL_VideoData::mouse_device_info
net_wm
bool SDL_VideoData::net_wm
num_cursor_themes
int SDL_VideoData::num_cursor_themes
num_windows
int SDL_VideoData::num_windows
numlock_mask
Uint32 SDL_VideoData::numlock_mask
numwindows
int SDL_VideoData::numwindows
Offset
int int int int int unsigned int* SDL_VideoData::Offset
oInput
struct VR_IVRInput_FnTable* SDL_VideoData::oInput
oleinitialized
bool SDL_VideoData::oleinitialized
oOverlay
struct VR_IVROverlay_FnTable* SDL_VideoData::oOverlay
openVRLIB
void* SDL_VideoData::openVRLIB
oSystem
struct VR_IVRSystem_FnTable* SDL_VideoData::oSystem
output_count
int SDL_VideoData::output_count
output_list
SDL_DisplayData** SDL_VideoData::output_list
output_max
int SDL_VideoData::output_max
overlayID
VROverlayHandle_t SDL_VideoData::overlayID
overlaytexture
unsigned int SDL_VideoData::overlaytexture
pBlurBehind
const DWM_BLURBEHIND* SDL_VideoData::pBlurBehind
Referenced by HRESULT().
pen_atom_abs_pressure
Atom SDL_VideoData::pen_atom_abs_pressure
pen_atom_abs_tilt_x
Atom SDL_VideoData::pen_atom_abs_tilt_x
pen_atom_abs_tilt_y
Atom SDL_VideoData::pen_atom_abs_tilt_y
pen_atom_device_product_id
Atom SDL_VideoData::pen_atom_device_product_id
pen_atom_wacom_serial_ids
Atom SDL_VideoData::pen_atom_wacom_serial_ids
pen_atom_wacom_tool_type
Atom SDL_VideoData::pen_atom_wacom_tool_type
pending_E1_key_sequence
bool SDL_VideoData::pending_E1_key_sequence
penInfo
POINTER_PEN_INFO* SDL_VideoData::penInfo
Referenced by BOOL().
pfIsVertical
UINT LPWSTR PINT BOOL* SDL_VideoData::pfIsVertical
Physical
int int unsigned long* SDL_VideoData::Physical
pid
pid_t SDL_VideoData::pid
pnErrorIndex
UINT LPWSTR PINT SDL_VideoData::pnErrorIndex
pointer_constraints
struct zwp_pointer_constraints_v1* SDL_VideoData::pointer_constraints
pointerType
POINTER_INPUT_TYPE* SDL_VideoData::pointerType
Referenced by BOOL().
pre_hook_key_state
BYTE SDL_VideoData::pre_hook_key_state[256]
PRIMARY
Atom SDL_VideoData::PRIMARY
primary_selection
SDLX11_ClipboardData SDL_VideoData::primary_selection
primary_selection_device_manager
struct zwp_primary_selection_device_manager_v1* SDL_VideoData::primary_selection_device_manager
PTOUCHINPUT
SDL_VideoData::PTOUCHINPUT
Referenced by BOOL().
puMaxReadingLen
UINT LPWSTR PINT BOOL PUINT SDL_VideoData::puMaxReadingLen
pvAttribute
DWORD LPCVOID SDL_VideoData::pvAttribute
raw_input_enabled
Uint32 SDL_VideoData::raw_input_enabled
raw_keyboard_enabled
bool SDL_VideoData::raw_keyboard_enabled
raw_mouse_enabled
bool SDL_VideoData::raw_mouse_enabled
rawinput
BYTE* SDL_VideoData::rawinput
rawinput_count
UINT SDL_VideoData::rawinput_count
rawinput_offset
UINT SDL_VideoData::rawinput_offset
rawinput_size
UINT SDL_VideoData::rawinput_size
rbo
unsigned int SDL_VideoData::rbo
registry
struct wl_registry* SDL_VideoData::registry
relative_pointer_manager
struct zwp_relative_pointer_manager_v1* SDL_VideoData::relative_pointer_manager
render
int SDL_VideoData::render
renderdoc_debugmarker_frame_end
bool SDL_VideoData::renderdoc_debugmarker_frame_end
request_display
Display* SDL_VideoData::request_display
saved_texture_state
int SDL_VideoData::saved_texture_state
scale_to_display_enabled
bool SDL_VideoData::scale_to_display_enabled
screensaver_activity
Uint64 SDL_VideoData::screensaver_activity
scrolllock_mask
Uint32 SDL_VideoData::scrolllock_mask
SDL_FORMATS
Atom SDL_VideoData::SDL_FORMATS
sdl_modifiers
SDL_Keymod SDL_VideoData::sdl_modifiers
SDL_SELECTION
Atom SDL_VideoData::SDL_SELECTION
seat_list
struct wl_list SDL_VideoData::seat_list
selection_incr_waiting
bool SDL_VideoData::selection_incr_waiting
selection_waiting
bool SDL_VideoData::selection_waiting
shcoreDLL
SDL_SharedObject* SDL_VideoData::shcoreDLL
[struct]
struct { ... } SDL_VideoData::shell
shm
struct wl_shm* SDL_VideoData::shm
sOverlayName
char* SDL_VideoData::sOverlayName
steam_keyboard_open
bool SDL_VideoData::steam_keyboard_open
Stride
int int unsigned long int* SDL_VideoData::Stride
swap_interval
int SDL_VideoData::swap_interval
tablet_manager
struct zwp_tablet_manager_v2* SDL_VideoData::tablet_manager
TARGETS
Atom SDL_VideoData::TARGETS
targh
int SDL_VideoData::targh
targw
int SDL_VideoData::targw
text_input_manager
struct zwp_text_input_manager_v3* SDL_VideoData::text_input_manager
thumbID
VROverlayHandle_t SDL_VideoData::thumbID
top_display
int SDL_VideoData::top_display
touch_display
int SDL_VideoData::touch_display
UINT
SDL_VideoData::UINT
Referenced by BOOL().
ULONG
SDL_VideoData::ULONG
Referenced by BOOL().
uReadingBufLen
UINT SDL_VideoData::uReadingBufLen
userDLL
SDL_SharedObject* SDL_VideoData::userDLL
UTF8_STRING
Atom SDL_VideoData::UTF8_STRING
video_init
bool SDL_VideoData::video_init
viewporter
struct wp_viewporter* SDL_VideoData::viewporter
virtual_joystick
SDL_Joystick* SDL_VideoData::virtual_joystick
vrtoken
intptr_t SDL_VideoData::vrtoken
vulkan_mode
bool SDL_VideoData::vulkan_mode
Width [1/3]
int int int * SDL_VideoData::Width
Referenced by EGLNativeWindowType().
Width [2/3]
int int int SDL_VideoData::Width
Width [3/3]
int int int* SDL_VideoData::Width
window
SDL_Window* SDL_VideoData::window
window_group
XID SDL_VideoData::window_group
windowlist
SDL_WindowData** SDL_VideoData::windowlist
windowlistlength
int SDL_VideoData::windowlistlength
windows
SDL_Window** SDL_VideoData::windows
wl_fixes
struct wl_fixes* SDL_VideoData::wl_fixes
WM_DELETE_WINDOW
Atom SDL_VideoData::WM_DELETE_WINDOW
WM_NAME
Atom SDL_VideoData::WM_NAME
WM_PROTOCOLS
Atom SDL_VideoData::WM_PROTOCOLS
WM_TAKE_FOCUS
Atom SDL_VideoData::WM_TAKE_FOCUS
WM_TRANSIENT_FOR
Atom SDL_VideoData::WM_TRANSIENT_FOR
wp_alpha_modifier_v1
struct wp_alpha_modifier_v1* SDL_VideoData::wp_alpha_modifier_v1
wp_color_manager_v1
struct wp_color_manager_v1* SDL_VideoData::wp_color_manager_v1
wp_pointer_warp_v1
struct wp_pointer_warp_v1* SDL_VideoData::wp_pointer_warp_v1
X [1/2]
int * SDL_VideoData::X
Referenced by EGLNativeWindowType().
X [2/2]
int* SDL_VideoData::X
xdg
struct xdg_wm_base* SDL_VideoData::xdg
xdg_output_manager
struct zxdg_output_manager_v1* SDL_VideoData::xdg_output_manager
xdg_toplevel_icon_manager_v1
struct xdg_toplevel_icon_manager_v1* SDL_VideoData::xdg_toplevel_icon_manager_v1
xdg_wm_dialog_v1
struct xdg_wm_dialog_v1* SDL_VideoData::xdg_wm_dialog_v1
XdndActionCopy
Atom SDL_VideoData::XdndActionCopy
XdndAware
Atom SDL_VideoData::XdndAware
XdndDrop
Atom SDL_VideoData::XdndDrop
XdndEnter
Atom SDL_VideoData::XdndEnter
XdndFinished
Atom SDL_VideoData::XdndFinished
XdndLeave
Atom SDL_VideoData::XdndLeave
XdndPosition
Atom SDL_VideoData::XdndPosition
XdndSelection
Atom SDL_VideoData::XdndSelection
XdndStatus
Atom SDL_VideoData::XdndStatus
XdndTypeList
Atom SDL_VideoData::XdndTypeList
xinput_hierarchy_changed
bool SDL_VideoData::xinput_hierarchy_changed
xinput_master_pointer_device
int SDL_VideoData::xinput_master_pointer_device
[struct]
struct { ... } SDL_VideoData::xkb
xkb_context
struct xkb_context* SDL_VideoData::xkb_context
xkb_modifiers
unsigned int SDL_VideoData::xkb_modifiers
XKLAVIER_STATE
Atom SDL_VideoData::XKLAVIER_STATE
xrandr_event_base
int SDL_VideoData::xrandr_event_base
xsettings_data
SDLX11_SettingsData SDL_VideoData::xsettings_data
xsettings_window
Window SDL_VideoData::xsettings_window
Y [1/2]
int int * SDL_VideoData::Y
Referenced by EGLNativeWindowType().
Y [2/2]
int int* SDL_VideoData::Y
zxdg_exporter_v2
struct zxdg_exporter_v2* SDL_VideoData::zxdg_exporter_v2
The documentation for this struct was generated from the following files:
SDL-main/src/video/android/SDL_androidvideo.h
SDL-main/src/video/kmsdrm/SDL_kmsdrmvideo.h
SDL-main/src/video/n3ds/SDL_n3dsvideo.h
SDL-main/src/video/openvr/SDL_openvrvideo.h
SDL-main/src/video/psp/SDL_pspvideo.h
SDL-main/src/video/raspberry/SDL_rpivideo.h
SDL-main/src/video/riscos/SDL_riscosvideo.h
SDL-main/src/video/vita/SDL_vitavideo.h
SDL-main/src/video/vivante/SDL_vivantevideo.h
SDL-main/src/video/wayland/SDL_waylandvideo.h
SDL-main/src/video/windows/SDL_windowsvideo.h
SDL-main/src/video/x11/SDL_x11video.h