SDL3: SDL-main/src/video/SDL_surface_c.h File Reference
SDL_surface_c.h File Reference
#include "SDL_internal.h"
#include "SDL_blit.h"
Data Structures
struct SDL_Surface
Macros
#define SDL_INTERNAL_SURFACE_DONTFREE 0x00000001u
#define SDL_INTERNAL_SURFACE_RLEACCEL 0x00000004u
#define SDL_INTERNAL_SURFACE_STACK 0x00000002u
Typedefs
typedef Uint32 SDL_SurfaceDataFlags
Functions
bool SDL_CalculateSurfaceSize (SDL_PixelFormat format, int width, int height, size_t *size, size_t *pitch, bool minimalPitch)
float SDL_GetDefaultHDRHeadroom (SDL_Colorspace colorspace)
float SDL_GetDefaultSDRWhitePoint (SDL_Colorspace colorspace)
float SDL_GetSurfaceHDRHeadroom (SDL_Surface *surface, SDL_Colorspace colorspace)
SDL_Surface * SDL_GetSurfaceImage (SDL_Surface *surface, float display_scale)
float SDL_GetSurfaceSDRWhitePoint (SDL_Surface *surface, SDL_Colorspace colorspace)
bool SDL_SurfaceValid (SDL_Surface *surface)
void SDL_UpdateSurfaceLockFlag (SDL_Surface *surface)
Macro Definition Documentation
SDL_INTERNAL_SURFACE_DONTFREE
#define SDL_INTERNAL_SURFACE_DONTFREE 0x00000001u
Surface is referenced internally
Referenced by SDL_DestroySurface(), SDL_DestroyWindowSurface(), and SDL_GetWindowSurface().
SDL_INTERNAL_SURFACE_RLEACCEL
#define SDL_INTERNAL_SURFACE_RLEACCEL 0x00000004u
Surface is RLE encoded
Referenced by SDL_CalculateBlit(), SDL_DestroySurface(), SDL_LockSurface(), SDL_MapSurface(), and SDL_UnlockSurface().
SDL_INTERNAL_SURFACE_STACK
#define SDL_INTERNAL_SURFACE_STACK 0x00000002u
Surface is allocated on the stack
Referenced by SDL_DestroySurface(), and SDL_InitializeSurface().
Typedef Documentation
SDL_SurfaceDataFlags
typedef Uint32 SDL_SurfaceDataFlags
Function Documentation
SDL_CalculateSurfaceSize()
bool SDL_CalculateSurfaceSize (SDL_PixelFormat format, int width, int height, size_t * size, size_t * pitch, bool minimalPitch) extern
{
    size_t p = 0, sz = 0;
    if (size) {
        *size = 0;
    }
    if (pitch) {
        *pitch = 0;
    }
    if (SDL_ISPIXELFORMAT_FOURCC(format)) {
        if (format == SDL_PIXELFORMAT_MJPG) {
            // We don't know in advance what it will be, we'll figure it out later.
            return true;
        }
        if (!SDL_CalculateYUVSize(format, width, height, &sz, &p)) {
            // Overflow...
            return false;
        }
    } else {
        if (!SDL_CalculateRGBSize(format, width, height, &sz, &p, minimalPitch)) {
            // Overflow...
            return false;
        }
    }
    if (size) {
        *size = sz;
    }
    if (pitch) {
        *pitch = p;
    }
    return true;
}
References SDL_CalculateRGBSize(), SDL_CalculateYUVSize(), SDL_ISPIXELFORMAT_FOURCC, and SDL_PIXELFORMAT_MJPG.
Referenced by SDL_CreateSurface(), and SDL_CreateSurfaceFrom().
SDL_GetDefaultHDRHeadroom()
float SDL_GetDefaultHDRHeadroom (SDL_Colorspace colorspace) extern
{
    return SDL_GetSurfaceHDRHeadroom(NULL, colorspace);
}
References NULL, and SDL_GetSurfaceHDRHeadroom().
Referenced by SDL_CreateTextureWithProperties().
SDL_GetDefaultSDRWhitePoint()
float SDL_GetDefaultSDRWhitePoint (SDL_Colorspace colorspace) extern
{
    return SDL_GetSurfaceSDRWhitePoint(NULL, colorspace);
}
References NULL, and SDL_GetSurfaceSDRWhitePoint().
Referenced by SDL_CreateTextureWithProperties().
SDL_GetSurfaceHDRHeadroom()
float SDL_GetSurfaceHDRHeadroom (SDL_Surface * surface, SDL_Colorspace colorspace) extern
{
    SDL_TransferCharacteristics transfer = SDL_COLORSPACETRANSFER(colorspace);
    if (transfer == SDL_TRANSFER_CHARACTERISTICS_LINEAR ||
        transfer == SDL_TRANSFER_CHARACTERISTICS_PQ) {
        SDL_PropertiesID props;
        float default_value = 0.0f;
        if (SDL_SurfaceValid(surface)) {
            props = surface->props;
        } else {
            props = 0;
        }
        return SDL_GetFloatProperty(props, SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT, default_value);
    }
    return 1.0f;
}
References SDL_COLORSPACETRANSFER, SDL_GetFloatProperty(), SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT, SDL_SurfaceValid(), SDL_TRANSFER_CHARACTERISTICS_LINEAR, and SDL_TRANSFER_CHARACTERISTICS_PQ.
Referenced by SDL_Blit_Slow_Float(), SDL_CreateTextureFromSurface(), and SDL_GetDefaultHDRHeadroom().
SDL_GetSurfaceImage()
SDL_Surface * SDL_GetSurfaceImage (SDL_Surface * surface, float display_scale) extern
{
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("surface");
        return NULL;
    }
    if (!SDL_SurfaceHasAlternateImages(surface)) {
        ++surface->refcount;
        return surface;
    }
    // This surface has high DPI images, pick the best one available, or scale one to the correct size
    SDL_Surface **images = SDL_GetSurfaceImages(surface, NULL);
    if (!images) {
        // Failure, fall back to the existing surface
        ++surface->refcount;
        return surface;
    }
    // Find closest image. Images that are larger than the
    // desired size are preferred over images that are smaller.
    SDL_Surface *closest = NULL;
    int desired_w = (int)SDL_round(surface->w * display_scale);
    int desired_h = (int)SDL_round(surface->h * display_scale);
    int desired_size = desired_w * desired_h;
    int closest_distance = -1;
    int closest_size = -1;
    for (int i = 0; images[i]; ++i) {
        SDL_Surface *candidate = images[i];
        int size = candidate->w * candidate->h;
        int delta_w = (candidate->w - desired_w);
        int delta_h = (candidate->h - desired_h);
        int distance = (delta_w * delta_w) + (delta_h * delta_h);
        if (closest_distance < 0 || distance < closest_distance ||
            (size > desired_size && closest_size < desired_size)) {
            closest = candidate;
            closest_distance = distance;
            closest_size = size;
        }
    }
    SDL_free(images);
    SDL_assert(closest != NULL);    // We should always have at least one surface
    if (closest->w == desired_w && closest->h == desired_h) {
        ++closest->refcount;
        return closest;
    }
    // We need to scale the image to the correct size. To maintain good image quality, downscaling
    // is done in steps, never reducing the width and height by more than half each time.
    SDL_Surface *scaled = closest;
    do {
        int next_scaled_w = SDL_max(desired_w, (scaled->w + 1) / 2);
        int next_scaled_h = SDL_max(desired_h, (scaled->h + 1) / 2);
        SDL_Surface *next_scaled = SDL_ScaleSurface(scaled, next_scaled_w, next_scaled_h, SDL_SCALEMODE_LINEAR);
        if (scaled != closest) {
            SDL_DestroySurface(scaled);
        }
        scaled = next_scaled;
        if (!scaled) {
            // Failure, fall back to the closest surface
            ++closest->refcount;
            return closest;
        }
    } while (scaled->w != desired_w || scaled->h != desired_h);
    return scaled;
}
References SDL_Surface::h, NULL, SDL_Surface::refcount, SDL_assert, SDL_DestroySurface(), SDL_free(), SDL_GetSurfaceImages(), SDL_InvalidParamError, SDL_max, SDL_round(), SDL_SCALEMODE_LINEAR, SDL_ScaleSurface(), SDL_SurfaceHasAlternateImages(), SDL_SurfaceValid(), and SDL_Surface::w.
SDL_GetSurfaceSDRWhitePoint()
float SDL_GetSurfaceSDRWhitePoint (SDL_Surface * surface, SDL_Colorspace colorspace) extern
{
    SDL_TransferCharacteristics transfer = SDL_COLORSPACETRANSFER(colorspace);
    if (transfer == SDL_TRANSFER_CHARACTERISTICS_LINEAR ||
        transfer == SDL_TRANSFER_CHARACTERISTICS_PQ) {
        SDL_PropertiesID props;
        float default_value = 1.0f;
        if (SDL_SurfaceValid(surface)) {
            props = surface->props;
        } else {
            props = 0;
        }
        if (transfer == SDL_TRANSFER_CHARACTERISTICS_PQ) {
            /* The older standards use an SDR white point of 100 nits.
             * ITU-R BT.2408-6 recommends using an SDR white point of 203 nits.
             * This is the default Chrome uses, and what a lot of game content
             * assumes, so we'll go with that.
             */
            const float DEFAULT_PQ_SDR_WHITE_POINT = 203.0f;
            default_value = DEFAULT_PQ_SDR_WHITE_POINT;
        }
        return SDL_GetFloatProperty(props, SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT, default_value);
    }
    return 1.0f;
}
References SDL_COLORSPACETRANSFER, SDL_GetFloatProperty(), SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT, SDL_SurfaceValid(), SDL_TRANSFER_CHARACTERISTICS_LINEAR, and SDL_TRANSFER_CHARACTERISTICS_PQ.
Referenced by SDL_Blit_Slow_Float(), SDL_CreateTextureFromSurface(), and SDL_GetDefaultSDRWhitePoint().
SDL_SurfaceValid()
bool SDL_SurfaceValid (SDL_Surface * surface) extern
{
    return (surface && surface->reserved == &SDL_surface_magic);
}
References SDL_surface_magic.
Referenced by SDL_AddSurfaceAlternateImage(), SDL_BlitSurface(), SDL_BlitSurface9Grid(), SDL_BlitSurfaceScaled(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_ClearSurface(), SDL_ConvertColorkeyToAlpha(), SDL_ConvertSurface(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateSurfacePalette(), SDL_CreateTextureFromSurface(), SDL_DestroySurface(), SDL_DuplicateSurface(), SDL_FillSurfaceRect(), SDL_FillSurfaceRects(), SDL_FlipSurface(), SDL_GetSurfaceAlphaMod(), SDL_GetSurfaceBlendMode(), SDL_GetSurfaceClipRect(), SDL_GetSurfaceColorKey(), SDL_GetSurfaceColorMod(), SDL_GetSurfaceColorspace(), SDL_GetSurfaceHDRHeadroom(), SDL_GetSurfaceImage(), SDL_GetSurfaceImages(), SDL_GetSurfacePalette(), SDL_GetSurfaceProperties(), SDL_GetSurfaceSDRWhitePoint(), SDL_LockSurface(), SDL_MapSurfaceRGBA(), SDL_PremultiplySurfaceAlpha(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_RemoveSurfaceAlternateImages(), SDL_SaveBMP_IO(), SDL_ScaleSurface(), SDL_SetSurfaceAlphaMod(), SDL_SetSurfaceBlendMode(), SDL_SetSurfaceClipRect(), SDL_SetSurfaceColorKey(), SDL_SetSurfaceColorMod(), SDL_SetSurfaceColorspace(), SDL_SetSurfacePalette(), SDL_SetSurfaceRLE(), SDL_SurfaceHasAlternateImages(), SDL_SurfaceHasColorKey(), SDL_SurfaceHasRLE(), SDL_UnlockSurface(), SDL_WriteSurfacePixel(), and SDL_WriteSurfacePixelFloat().
SDL_UpdateSurfaceLockFlag()
void SDL_UpdateSurfaceLockFlag (SDL_Surface * surface) extern
{
    if (SDL_SurfaceHasRLE(surface)) {
        surface->flags |= SDL_SURFACE_LOCK_NEEDED;
    } else {
        surface->flags &= ~SDL_SURFACE_LOCK_NEEDED;
    }
}
References SDL_SURFACE_LOCK_NEEDED, and SDL_SurfaceHasRLE().
Referenced by SDL_SetSurfaceRLE().