SDL3: MainWindow Class Reference
MainWindow Class Reference
Inherits FXMainWindow.
Public Types
enum {
ID_FIRST = FXMainWindow::ID_LAST , ID_CONNECT , ID_DISCONNECT , ID_RESCAN ,
ID_SEND_OUTPUT_REPORT , ID_SEND_FEATURE_REPORT , ID_GET_FEATURE_REPORT , ID_CLEAR ,
ID_TIMER , ID_MAC_TIMER , ID_LAST
}
Public Member Functions
virtual void create ()
MainWindow (FXApp *a)
long onClear (FXObject *sender, FXSelector sel, void *ptr)
long onConnect (FXObject *sender, FXSelector sel, void *ptr)
long onDisconnect (FXObject *sender, FXSelector sel, void *ptr)
long onGetFeatureReport (FXObject *sender, FXSelector sel, void *ptr)
long onMacTimeout (FXObject *sender, FXSelector sel, void *ptr)
long onRescan (FXObject *sender, FXSelector sel, void *ptr)
long onSendFeatureReport (FXObject *sender, FXSelector sel, void *ptr)
long onSendOutputReport (FXObject *sender, FXSelector sel, void *ptr)
long onTimeout (FXObject *sender, FXSelector sel, void *ptr)
~MainWindow ()
Protected Member Functions
MainWindow ()
Private Member Functions
size_t getDataFromTextField (FXTextField *tf, char *buf, size_t len)
int getLengthFromTextField (FXTextField *tf)
Private Attributes
FXButton * connect_button
hid_device * connected_device
FXLabel * connected_label
FXList * device_list
struct hid_device_info * devices
FXButton * disconnect_button
FXButton * feature_button
FXTextField * feature_len
FXTextField * feature_text
FXButton * get_feature_button
FXTextField * get_feature_text
FXText * input_text
FXButton * output_button
FXTextField * output_len
FXTextField * output_text
FXButton * rescan_button
FXFont * title_font
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ID_FIRST
ID_CONNECT
ID_DISCONNECT
ID_RESCAN
ID_SEND_OUTPUT_REPORT
ID_SEND_FEATURE_REPORT
ID_GET_FEATURE_REPORT
ID_CLEAR
ID_TIMER
ID_MAC_TIMER
ID_LAST
         {
        ID_FIRST = FXMainWindow::ID_LAST,
        ID_CONNECT,
        ID_DISCONNECT,
        ID_RESCAN,
        ID_SEND_OUTPUT_REPORT,
        ID_SEND_FEATURE_REPORT,
        ID_GET_FEATURE_REPORT,
        ID_CLEAR,
        ID_TIMER,
        ID_MAC_TIMER,
        ID_LAST,
    };
Constructor & Destructor Documentation
MainWindow() [1/2]
MainWindow::MainWindow () inline protected
{};
MainWindow() [2/2]
MainWindow::MainWindow (FXApp * a)
    : FXMainWindow(app, "HIDAPI Test Application", NULL, NULL, DECOR_ALL, 200,100, 425,700)
{
    devices = NULL;
    connected_device = NULL;
    FXVerticalFrame *vf = new FXVerticalFrame(this, LAYOUT_FILL_Y|LAYOUT_FILL_X);
    FXLabel *label = new FXLabel(vf, "HIDAPI Test Tool");
    title_font = new FXFont(getApp(), "Arial", 14, FXFont::Bold);
    label->setFont(title_font);
    new FXLabel(vf,
        "Select a device and press Connect.", NULL, JUSTIFY_LEFT);
    new FXLabel(vf,
        "Output data bytes can be entered in the Output section, \n"
        "separated by space, comma or brackets. Data starting with 0x\n"
        "is treated as hex. Data beginning with a 0 is treated as \n"
        "octal. All other data is treated as decimal.", NULL, JUSTIFY_LEFT);
    new FXLabel(vf,
        "Data received from the device appears in the Input section.",
        NULL, JUSTIFY_LEFT);
    new FXLabel(vf,
        "Optionally, a report length may be specified. Extra bytes are\n"
        "padded with zeros. If no length is specified, the length is \n"
        "inferred from the data.",
        NULL, JUSTIFY_LEFT);
    new FXLabel(vf, "");
    // Device List and Connect/Disconnect buttons
    FXHorizontalFrame *hf = new FXHorizontalFrame(vf, LAYOUT_FILL_X);
    //device_list = new FXList(new FXHorizontalFrame(hf,FRAME_SUNKEN|FRAME_THICK, 0,0,0,0, 0,0,0,0), NULL, 0, LISTBOX_NORMAL|LAYOUT_FILL_X|LAYOUT_FILL_Y|LAYOUT_FIX_WIDTH|LAYOUT_FIX_HEIGHT, 0,0,300,200);
    device_list = new FXList(new FXHorizontalFrame(hf,FRAME_SUNKEN|FRAME_THICK|LAYOUT_FILL_X|LAYOUT_FILL_Y, 0,0,0,0, 0,0,0,0), NULL, 0, LISTBOX_NORMAL|LAYOUT_FILL_X|LAYOUT_FILL_Y, 0,0,300,200);
    FXVerticalFrame *buttonVF = new FXVerticalFrame(hf);
    connect_button = new FXButton(buttonVF, "Connect", NULL, this, ID_CONNECT, BUTTON_NORMAL|LAYOUT_FILL_X);
    disconnect_button = new FXButton(buttonVF, "Disconnect", NULL, this, ID_DISCONNECT, BUTTON_NORMAL|LAYOUT_FILL_X);
    disconnect_button->disable();
    rescan_button = new FXButton(buttonVF, "Re-Scan devices", NULL, this, ID_RESCAN, BUTTON_NORMAL|LAYOUT_FILL_X);
    new FXHorizontalFrame(buttonVF, 0, 0,0,0,0, 0,0,50,0);
    connected_label = new FXLabel(vf, "Disconnected");
    new FXHorizontalFrame(vf);
    // Output Group Box
    FXGroupBox *gb = new FXGroupBox(vf, "Output", FRAME_GROOVE|LAYOUT_FILL_X);
    FXMatrix *matrix = new FXMatrix(gb, 3, MATRIX_BY_COLUMNS|LAYOUT_FILL_X);
    new FXLabel(matrix, "Data");
    new FXLabel(matrix, "Length");
    new FXLabel(matrix, "");
    //hf = new FXHorizontalFrame(gb, LAYOUT_FILL_X);
    output_text = new FXTextField(matrix, 30, NULL, 0, TEXTFIELD_NORMAL|LAYOUT_FILL_X|LAYOUT_FILL_COLUMN);
    output_text->setText("1 0x81 0");
    output_len = new FXTextField(matrix, 5, NULL, 0, TEXTFIELD_NORMAL|LAYOUT_FILL_X|LAYOUT_FILL_COLUMN);
    output_button = new FXButton(matrix, "Send Output Report", NULL, this, ID_SEND_OUTPUT_REPORT, BUTTON_NORMAL|LAYOUT_FILL_X);
    output_button->disable();
    //new FXHorizontalFrame(matrix, LAYOUT_FILL_X);
    //hf = new FXHorizontalFrame(gb, LAYOUT_FILL_X);
    feature_text = new FXTextField(matrix, 30, NULL, 0, TEXTFIELD_NORMAL|LAYOUT_FILL_X|LAYOUT_FILL_COLUMN);
    feature_len = new FXTextField(matrix, 5, NULL, 0, TEXTFIELD_NORMAL|LAYOUT_FILL_X|LAYOUT_FILL_COLUMN);
    feature_button = new FXButton(matrix, "Send Feature Report", NULL, this, ID_SEND_FEATURE_REPORT, BUTTON_NORMAL|LAYOUT_FILL_X);
    feature_button->disable();
    get_feature_text = new FXTextField(matrix, 30, NULL, 0, TEXTFIELD_NORMAL|LAYOUT_FILL_X|LAYOUT_FILL_COLUMN);
    new FXWindow(matrix);
    get_feature_button = new FXButton(matrix, "Get Feature Report", NULL, this, ID_GET_FEATURE_REPORT, BUTTON_NORMAL|LAYOUT_FILL_X);
    get_feature_button->disable();
    // Input Group Box
    gb = new FXGroupBox(vf, "Input", FRAME_GROOVE|LAYOUT_FILL_X|LAYOUT_FILL_Y);
    FXVerticalFrame *innerVF = new FXVerticalFrame(gb, LAYOUT_FILL_X|LAYOUT_FILL_Y);
    input_text = new FXText(new FXHorizontalFrame(innerVF,LAYOUT_FILL_X|LAYOUT_FILL_Y|FRAME_SUNKEN|FRAME_THICK, 0,0,0,0, 0,0,0,0), NULL, 0, LAYOUT_FILL_X|LAYOUT_FILL_Y);
    input_text->setEditable(false);
    new FXButton(innerVF, "Clear", NULL, this, ID_CLEAR, BUTTON_NORMAL|LAYOUT_RIGHT);
}
References connect_button, connected_device, connected_label, device_list, devices, disconnect_button, feature_button, feature_len, feature_text, get_feature_button, get_feature_text, ID_CLEAR, ID_CONNECT, ID_DISCONNECT, ID_GET_FEATURE_REPORT, ID_RESCAN, ID_SEND_FEATURE_REPORT, ID_SEND_OUTPUT_REPORT, input_text, NULL, output_button, output_len, output_text, rescan_button, and title_font.
~MainWindow()
MainWindow::~MainWindow ()
{
    if (connected_device)
        hid_close(connected_device);
    hid_exit();
    delete title_font;
}
References connected_device, hid_close, hid_exit, and title_font.
Member Function Documentation
create()
void MainWindow::create () virtual
{
    FXMainWindow::create();
    show();
    onRescan(NULL, 0, NULL);
#ifdef __APPLE__
    init_apple_message_system();
#endif
    getApp()->addTimeout(this, ID_MAC_TIMER,
        50 * timeout_scalar /*50ms*/);
}
References ID_MAC_TIMER, init_apple_message_system(), NULL, onRescan(), and timeout_scalar.
getDataFromTextField()
size_t MainWindow::getDataFromTextField (FXTextField * tf, char * buf, size_t len) private
{
    const char *delim = " ,{}\t\r\n";
    FXString data = tf->getText();
    const FXchar *d = data.text();
    size_t i = 0;
    // Copy the string from the GUI.
    size_t sz = strlen(d);
    char *str = (char*) malloc(sz+1);
    strcpy(str, d);
    // For each token in the string, parse and store in buf[].
    char *token = strtok(str, delim);
    while (token) {
        char *endptr;
        long int val = strtol(token, &endptr, 0);
        buf[i++] = val;
        token = strtok(NULL, delim);
    }
    free(str);
    return i;
}
References d, free, malloc, and NULL.
Referenced by onGetFeatureReport(), onSendFeatureReport(), and onSendOutputReport().
getLengthFromTextField()
int MainWindow::getLengthFromTextField (FXTextField * tf) private
{
    long int len;
    FXString str = tf->getText();
    size_t sz = str.length();
    if (sz > 0) {
        char *endptr;
        len = strtol(str.text(), &endptr, 0);
        if (endptr != str.text() && *endptr == '\0') {
            if (len <= 0) {
                FXMessageBox::error(this, MBOX_OK, "Invalid length", "Enter a length greater than zero.");
                return -1;
            }
            return len;
        }
        else
            return -1;
    }
    return 0;
}
Referenced by onSendFeatureReport(), and onSendOutputReport().
onClear()
long MainWindow::onClear (FXObject * sender, FXSelector sel, void * ptr)
{
    input_text->setText("");
    return 1;
}
References input_text.
Referenced by FXDEFMAP().
onConnect()
long MainWindow::onConnect (FXObject * sender, FXSelector sel, void * ptr)
{
    if (connected_device != NULL)
        return 1;
    FXint cur_item = device_list->getCurrentItem();
    if (cur_item < 0)
        return -1;
    FXListItem *item = device_list->getItem(cur_item);
    if (!item)
        return -1;
    struct hid_device_info *device_info = (struct hid_device_info*) item->getData();
    if (!device_info)
        return -1;
    connected_device =  hid_open_path(device_info->path);
    if (!connected_device) {
        FXMessageBox::error(this, MBOX_OK, "Device Error", "Unable To Connect to Device");
        return -1;
    }
    hid_set_nonblocking(connected_device, 1);
    getApp()->addTimeout(this, ID_TIMER,
        5 * timeout_scalar /*5ms*/);
    FXString s;
    s.format("Connected to: %04hx:%04hx -", device_info->vendor_id, device_info->product_id);
    s += FXString(" ") + device_info->manufacturer_string;
    s += FXString(" ") + device_info->product_string;
    connected_label->setText(s);
    output_button->enable();
    feature_button->enable();
    get_feature_button->enable();
    connect_button->disable();
    disconnect_button->enable();
    input_text->setText("");
    return 1;
}
References connect_button, connected_device, connected_label, device_list, disconnect_button, feature_button, get_feature_button, hid_open_path, hid_set_nonblocking, ID_TIMER, input_text, hid_device_info::manufacturer_string, NULL, output_button, hid_device_info::path, hid_device_info::product_id, hid_device_info::product_string, timeout_scalar, and hid_device_info::vendor_id.
Referenced by FXDEFMAP().
onDisconnect()
long MainWindow::onDisconnect (FXObject * sender, FXSelector sel, void * ptr)
{
    hid_close(connected_device);
    connected_device = NULL;
    connected_label->setText("Disconnected");
    output_button->disable();
    feature_button->disable();
    get_feature_button->disable();
    connect_button->enable();
    disconnect_button->disable();
    getApp()->removeTimeout(this, ID_TIMER);
    return 1;
}
References connect_button, connected_device, connected_label, disconnect_button, feature_button, get_feature_button, hid_close, ID_TIMER, NULL, and output_button.
Referenced by FXDEFMAP().
onGetFeatureReport()
long MainWindow::onGetFeatureReport (FXObject * sender, FXSelector sel, void * ptr)
{
    char buf[256];
    size_t len;
    memset(buf, 0x0, sizeof(buf));
    len = getDataFromTextField(get_feature_text, buf, sizeof(buf));
    if (len != 1) {
        FXMessageBox::error(this, MBOX_OK, "Too many numbers", "Enter only a single report number in the text field");
    }
    int res = hid_get_feature_report(connected_device, (unsigned char*)buf, sizeof(buf));
    if (res < 0) {
        FXMessageBox::error(this, MBOX_OK, "Error Getting Report", "Could not get feature report from device. Error reported was: %ls", hid_error(connected_device));
    }
    if (res > 0) {
        FXString s;
        s.format("Returned Feature Report. %d bytes:\n", res);
        for (int i = 0; i < res; i++) {
            FXString t;
            t.format("%02hhx ", buf[i]);
            s += t;
            if ((i+1) % 4 == 0)
                s += " ";
            if ((i+1) % 16 == 0)
                s += "\n";
        }
        s += "\n";
        input_text->appendText(s);
        input_text->setBottomLine(INT_MAX);
    }
    return 1;
}
References connected_device, get_feature_text, getDataFromTextField(), hid_error, hid_get_feature_report, input_text, INT_MAX, and memset().
Referenced by FXDEFMAP().
onMacTimeout()
long MainWindow::onMacTimeout (FXObject * sender, FXSelector sel, void * ptr)
{
#ifdef __APPLE__
    check_apple_events();
    getApp()->addTimeout(this, ID_MAC_TIMER,
        50 * timeout_scalar /*50ms*/);
#endif
    return 1;
}
References check_apple_events(), ID_MAC_TIMER, and timeout_scalar.
Referenced by FXDEFMAP().
onRescan()
long MainWindow::onRescan (FXObject * sender, FXSelector sel, void * ptr)
{
    struct hid_device_info *cur_dev;
    device_list->clearItems();
    // List the Devices
    hid_free_enumeration(devices);
    devices = hid_enumerate(0x0, 0x0);
    cur_dev = devices;
    while (cur_dev) {
        // Add it to the List Box.
        FXString s;
        FXString usage_str;
        s.format("%04hx:%04hx -", cur_dev->vendor_id, cur_dev->product_id);
        s += FXString(" ") + cur_dev->manufacturer_string;
        s += FXString(" ") + cur_dev->product_string;
        usage_str.format(" (usage: %04hx:%04hx) ", cur_dev->usage_page, cur_dev->usage);
        s += usage_str;
        FXListItem *li = new FXListItem(s, NULL, cur_dev);
        device_list->appendItem(li);
        cur_dev = cur_dev->next;
    }
    if (device_list->getNumItems() == 0)
        device_list->appendItem("*** No Devices Connected ***");
    else {
        device_list->selectItem(0);
    }
    return 1;
}
References device_list, devices, hid_enumerate, hid_free_enumeration, hid_device_info::manufacturer_string, hid_device_info::next, NULL, hid_device_info::product_id, hid_device_info::product_string, hid_device_info::usage, hid_device_info::usage_page, and hid_device_info::vendor_id.
Referenced by create(), and FXDEFMAP().
onSendFeatureReport()
long MainWindow::onSendFeatureReport (FXObject * sender, FXSelector sel, void * ptr)
{
    char buf[256];
    size_t data_len, len;
    int textfield_len;
    memset(buf, 0x0, sizeof(buf));
    textfield_len = getLengthFromTextField(feature_len);
    data_len = getDataFromTextField(feature_text, buf, sizeof(buf));
    if (textfield_len < 0) {
        FXMessageBox::error(this, MBOX_OK, "Invalid length", "Length field is invalid. Please enter a number in hex, octal, or decimal.");
        return 1;
    }
    if (textfield_len > sizeof(buf)) {
        FXMessageBox::error(this, MBOX_OK, "Invalid length", "Length field is too long.");
        return 1;
    }
    len = (textfield_len)? textfield_len: data_len;
    int res = hid_send_feature_report(connected_device, (const unsigned char*)buf, len);
    if (res < 0) {
        FXMessageBox::error(this, MBOX_OK, "Error Writing", "Could not send feature report to device. Error reported was: %ls", hid_error(connected_device));
    }
    return 1;
}
References connected_device, feature_len, feature_text, getDataFromTextField(), getLengthFromTextField(), hid_error, hid_send_feature_report, and memset().
Referenced by FXDEFMAP().
onSendOutputReport()
long MainWindow::onSendOutputReport (FXObject * sender, FXSelector sel, void * ptr)
{
    char buf[256];
    size_t data_len, len;
    int textfield_len;
    memset(buf, 0x0, sizeof(buf));
    textfield_len = getLengthFromTextField(output_len);
    data_len = getDataFromTextField(output_text, buf, sizeof(buf));
    if (textfield_len < 0) {
        FXMessageBox::error(this, MBOX_OK, "Invalid length", "Length field is invalid. Please enter a number in hex, octal, or decimal.");
        return 1;
    }
    if (textfield_len > sizeof(buf)) {
        FXMessageBox::error(this, MBOX_OK, "Invalid length", "Length field is too long.");
        return 1;
    }
    len = (textfield_len)? textfield_len: data_len;
    int res = hid_write(connected_device, (const unsigned char*)buf, len);
    if (res < 0) {
        FXMessageBox::error(this, MBOX_OK, "Error Writing", "Could not write to device. Error reported was: %ls", hid_error(connected_device));
    }
    return 1;
}
References connected_device, getDataFromTextField(), getLengthFromTextField(), hid_error, hid_write, memset(), output_len, and output_text.
Referenced by FXDEFMAP().
onTimeout()
long MainWindow::onTimeout (FXObject * sender, FXSelector sel, void * ptr)
{
    unsigned char buf[256];
    int res = hid_read(connected_device, buf, sizeof(buf));
    if (res > 0) {
        FXString s;
        s.format("Received %d bytes:\n", res);
        for (int i = 0; i < res; i++) {
            FXString t;
            t.format("%02hhx ", buf[i]);
            s += t;
            if ((i+1) % 4 == 0)
                s += " ";
            if ((i+1) % 16 == 0)
                s += "\n";
        }
        s += "\n";
        input_text->appendText(s);
        input_text->setBottomLine(INT_MAX);
    }
    if (res < 0) {
        input_text->appendText("hid_read() returned error\n");
        input_text->setBottomLine(INT_MAX);
    }
    getApp()->addTimeout(this, ID_TIMER,
        5 * timeout_scalar /*5ms*/);
    return 1;
}
References connected_device, hid_read, ID_TIMER, input_text, INT_MAX, and timeout_scalar.
Referenced by FXDEFMAP().
Field Documentation
connect_button
FXButton* MainWindow::connect_button private
Referenced by MainWindow(), onConnect(), and onDisconnect().
connected_device
hid_device* MainWindow::connected_device private
Referenced by MainWindow(), onConnect(), onDisconnect(), onGetFeatureReport(), onSendFeatureReport(), onSendOutputReport(), onTimeout(), and ~MainWindow().
connected_label
FXLabel* MainWindow::connected_label private
Referenced by MainWindow(), onConnect(), and onDisconnect().
device_list
FXList* MainWindow::device_list private
Referenced by MainWindow(), onConnect(), and onRescan().
devices
struct hid_device_info* MainWindow::devices private
Referenced by MainWindow(), and onRescan().
disconnect_button
FXButton* MainWindow::disconnect_button private
Referenced by MainWindow(), onConnect(), and onDisconnect().
feature_button
FXButton* MainWindow::feature_button private
Referenced by MainWindow(), onConnect(), and onDisconnect().
feature_len
FXTextField* MainWindow::feature_len private
Referenced by MainWindow(), and onSendFeatureReport().
feature_text
FXTextField* MainWindow::feature_text private
Referenced by MainWindow(), and onSendFeatureReport().
get_feature_button
FXButton* MainWindow::get_feature_button private
Referenced by MainWindow(), onConnect(), and onDisconnect().
get_feature_text
FXTextField* MainWindow::get_feature_text private
Referenced by MainWindow(), and onGetFeatureReport().
input_text
FXText* MainWindow::input_text private
Referenced by MainWindow(), onClear(), onConnect(), onGetFeatureReport(), and onTimeout().
output_button
FXButton* MainWindow::output_button private
Referenced by MainWindow(), onConnect(), and onDisconnect().
output_len
FXTextField* MainWindow::output_len private
Referenced by MainWindow(), and onSendOutputReport().
output_text
FXTextField* MainWindow::output_text private
Referenced by MainWindow(), and onSendOutputReport().
rescan_button
FXButton* MainWindow::rescan_button private
Referenced by MainWindow().
title_font
FXFont* MainWindow::title_font private
Referenced by MainWindow(), and ~MainWindow().
The documentation for this class was generated from the following file:
SDL-main/src/hidapi/testgui/test.cpp