SDL3: SDL-main/src/core/linux/SDL_fcitx.h File Reference
SDL_fcitx.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_Fcitx_Init (void)
bool SDL_Fcitx_ProcessKeyEvent (Uint32 keysym, Uint32 keycode, bool down)
void SDL_Fcitx_PumpEvents (void)
void SDL_Fcitx_Quit (void)
void SDL_Fcitx_Reset (void)
void SDL_Fcitx_SetFocus (bool focused)
void SDL_Fcitx_UpdateTextInputArea (SDL_Window *window)
Function Documentation
SDL_Fcitx_Init()
bool SDL_Fcitx_Init (void) extern
{
    fcitx_client.dbus = SDL_DBus_GetContext();
    fcitx_client.cursor_rect.x = -1;
    fcitx_client.cursor_rect.y = -1;
    fcitx_client.cursor_rect.w = 0;
    fcitx_client.cursor_rect.h = 0;
    return FcitxClientCreateIC(&fcitx_client);
}
References fcitx_client, and FcitxClientCreateIC().
Referenced by InitIME().
SDL_Fcitx_ProcessKeyEvent()
bool SDL_Fcitx_ProcessKeyEvent (Uint32 keysym, Uint32 keycode, bool down) extern
{
    Uint32 mod_state = Fcitx_ModState();
    Uint32 handled = false;
    Uint32 is_release = !down;
    Uint32 event_time = 0;
    if (!fcitx_client.ic_path) {
        return false;
    }
    if (SDL_DBus_CallMethod(FCITX_DBUS_SERVICE, fcitx_client.ic_path, FCITX_IC_DBUS_INTERFACE, "ProcessKeyEvent",
                            DBUS_TYPE_UINT32, &keysym, DBUS_TYPE_UINT32, &keycode, DBUS_TYPE_UINT32, &mod_state, DBUS_TYPE_BOOLEAN, &is_release, DBUS_TYPE_UINT32, &event_time, DBUS_TYPE_INVALID,
                            DBUS_TYPE_BOOLEAN, &handled, DBUS_TYPE_INVALID)) {
        if (handled) {
            SDL_Fcitx_UpdateTextInputArea(SDL_GetKeyboardFocus());
            return true;
        }
    }
    return false;
}
References fcitx_client, FCITX_DBUS_SERVICE, FCITX_IC_DBUS_INTERFACE, Fcitx_ModState(), keycode, SDL_Fcitx_UpdateTextInputArea(), and SDL_GetKeyboardFocus().
Referenced by InitIME().
SDL_Fcitx_PumpEvents()
void SDL_Fcitx_PumpEvents (void) extern
{
    SDL_DBusContext *dbus = fcitx_client.dbus;
    DBusConnection *conn = dbus->session_conn;
    dbus->connection_read_write(conn, 0);
    while (dbus->connection_dispatch(conn) == DBUS_DISPATCH_DATA_REMAINS) {
        // Do nothing, actual work happens in DBus_MessageFilter
    }
}
References fcitx_client.
Referenced by InitIME().
SDL_Fcitx_Quit()
void SDL_Fcitx_Quit (void) extern
{
    FcitxClientICCallMethod(&fcitx_client, "DestroyIC");
    if (fcitx_client.ic_path) {
        SDL_free(fcitx_client.ic_path);
        fcitx_client.ic_path = NULL;
    }
}
References fcitx_client, FcitxClientICCallMethod(), NULL, and SDL_free().
Referenced by InitIME().
SDL_Fcitx_Reset()
void SDL_Fcitx_Reset (void) extern
{
    FcitxClientICCallMethod(&fcitx_client, "Reset");
}
References fcitx_client, and FcitxClientICCallMethod().
Referenced by InitIME().
SDL_Fcitx_SetFocus()
void SDL_Fcitx_SetFocus (bool focused) extern
{
    if (focused) {
        FcitxClientICCallMethod(&fcitx_client, "FocusIn");
    } else {
        FcitxClientICCallMethod(&fcitx_client, "FocusOut");
    }
}
References fcitx_client, and FcitxClientICCallMethod().
Referenced by InitIME().
SDL_Fcitx_UpdateTextInputArea()
void SDL_Fcitx_UpdateTextInputArea (SDL_Window * window) extern
{
    int x = 0, y = 0;
    SDL_Rect *cursor = &fcitx_client.cursor_rect;
    if (!window) {
        return;
    }
    // We'll use a square at the text input cursor location for the cursor_rect
    cursor->x = window->text_input_rect.x + window->text_input_cursor;
    cursor->y = window->text_input_rect.y;
    cursor->w = window->text_input_rect.h;
    cursor->h = window->text_input_rect.h;
    SDL_GetWindowPosition(window, &x, &y);
#ifdef SDL_VIDEO_DRIVER_X11
    {
        SDL_PropertiesID props = SDL_GetWindowProperties(window);
        Display *x_disp = (Display *)SDL_GetPointerProperty(props, SDL_PROP_WINDOW_X11_DISPLAY_POINTER, NULL);
        int x_screen = SDL_GetNumberProperty(props, SDL_PROP_WINDOW_X11_SCREEN_NUMBER, 0);
        Window x_win = SDL_GetNumberProperty(props, SDL_PROP_WINDOW_X11_WINDOW_NUMBER, 0);
        Window unused;
        if (x_disp && x_win) {
            X11_XTranslateCoordinates(x_disp, x_win, RootWindow(x_disp, x_screen), 0, 0, &x, &y, &unused);
        }
    }
#endif
    if (cursor->x == -1 && cursor->y == -1 && cursor->w == 0 && cursor->h == 0) {
        // move to bottom left
        int w = 0, h = 0;
        SDL_GetWindowSize(window, &w, &h);
        cursor->x = 0;
        cursor->y = h;
    }
    x += cursor->x;
    y += cursor->y;
    SDL_DBus_CallVoidMethod(FCITX_DBUS_SERVICE, fcitx_client.ic_path, FCITX_IC_DBUS_INTERFACE, "SetCursorRect",
                            DBUS_TYPE_INT32, &x, DBUS_TYPE_INT32, &y, DBUS_TYPE_INT32, &cursor->w, DBUS_TYPE_INT32, &cursor->h, DBUS_TYPE_INVALID);
}
References fcitx_client, FCITX_DBUS_SERVICE, FCITX_IC_DBUS_INTERFACE, SDL_Rect::h, NULL, SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetWindowPosition(), SDL_GetWindowProperties(), SDL_GetWindowSize(), SDL_PROP_WINDOW_X11_DISPLAY_POINTER, SDL_PROP_WINDOW_X11_SCREEN_NUMBER, SDL_PROP_WINDOW_X11_WINDOW_NUMBER, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by DBus_MessageFilter(), InitIME(), and SDL_Fcitx_ProcessKeyEvent().