SDL3: SDL-main/include/SDL3/SDL_audio.h File Reference
SDL_audio.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_endian.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_mutex.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_iostream.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_AudioSpec
Macros
#define SDL_AUDIO_BITSIZE(x)
#define SDL_AUDIO_BYTESIZE(x)
#define SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK ((SDL_AudioDeviceID) 0xFFFFFFFFu)
#define SDL_AUDIO_DEVICE_DEFAULT_RECORDING ((SDL_AudioDeviceID) 0xFFFFFFFEu)
#define SDL_AUDIO_FRAMESIZE(x)
#define SDL_AUDIO_ISBIGENDIAN(x)
#define SDL_AUDIO_ISFLOAT(x)
#define SDL_AUDIO_ISINT(x)
#define SDL_AUDIO_ISLITTLEENDIAN(x)
#define SDL_AUDIO_ISSIGNED(x)
#define SDL_AUDIO_ISUNSIGNED(x)
#define SDL_AUDIO_MASK_BIG_ENDIAN (1u<<12)
#define SDL_AUDIO_MASK_BITSIZE (0xFFu)
#define SDL_AUDIO_MASK_FLOAT (1u<<8)
#define SDL_AUDIO_MASK_SIGNED (1u<<15)
#define SDL_DEFINE_AUDIO_FORMAT(signed, bigendian, flt, size)
#define SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN "SDL.audiostream.auto_cleanup"
Typedefs
typedef Uint32 SDL_AudioDeviceID
typedef enum SDL_AudioFormat SDL_AudioFormat
typedef void(SDLCALL * SDL_AudioPostmixCallback) (void *userdata, const SDL_AudioSpec *spec, float *buffer, int buflen)
typedef struct SDL_AudioSpec SDL_AudioSpec
typedef struct SDL_AudioStream SDL_AudioStream
typedef void(SDLCALL * SDL_AudioStreamCallback) (void *userdata, SDL_AudioStream *stream, int additional_amount, int total_amount)
typedef void(SDLCALL * SDL_AudioStreamDataCompleteCallback) (void *userdata, const void *buf, int buflen)
Enumerations
enum SDL_AudioFormat {
SDL_AUDIO_UNKNOWN = 0x0000u , SDL_AUDIO_U8 = 0x0008u , SDL_AUDIO_S8 = 0x8008u , SDL_AUDIO_S16LE = 0x8010u ,
SDL_AUDIO_S16BE = 0x9010u , SDL_AUDIO_S32LE = 0x8020u , SDL_AUDIO_S32BE = 0x9020u , SDL_AUDIO_F32LE = 0x8120u ,
SDL_AUDIO_F32BE = 0x9120u , SDL_AUDIO_S16 = SDL_AUDIO_S16LE , SDL_AUDIO_S32 = SDL_AUDIO_S32LE , SDL_AUDIO_F32 = SDL_AUDIO_F32LE
}
Functions
SDL_DECLSPEC bool SDLCALL SDL_AudioDevicePaused (SDL_AudioDeviceID devid)
SDL_DECLSPEC bool SDLCALL SDL_AudioStreamDevicePaused (SDL_AudioStream *stream)
SDL_DECLSPEC bool SDLCALL SDL_BindAudioStream (SDL_AudioDeviceID devid, SDL_AudioStream *stream)
SDL_DECLSPEC bool SDLCALL SDL_BindAudioStreams (SDL_AudioDeviceID devid, SDL_AudioStream *const *streams, int num_streams)
SDL_DECLSPEC bool SDLCALL SDL_ClearAudioStream (SDL_AudioStream *stream)
SDL_DECLSPEC void SDLCALL SDL_CloseAudioDevice (SDL_AudioDeviceID devid)
SDL_DECLSPEC bool SDLCALL SDL_ConvertAudioSamples (const SDL_AudioSpec *src_spec, const Uint8 *src_data, int src_len, const SDL_AudioSpec *dst_spec, Uint8 **dst_data, int *dst_len)
SDL_DECLSPEC SDL_AudioStream *SDLCALL SDL_CreateAudioStream (const SDL_AudioSpec *src_spec, const SDL_AudioSpec *dst_spec)
SDL_DECLSPEC void SDLCALL SDL_DestroyAudioStream (SDL_AudioStream *stream)
SDL_DECLSPEC bool SDLCALL SDL_FlushAudioStream (SDL_AudioStream *stream)
SDL_DECLSPEC int *SDLCALL SDL_GetAudioDeviceChannelMap (SDL_AudioDeviceID devid, int *count)
SDL_DECLSPEC bool SDLCALL SDL_GetAudioDeviceFormat (SDL_AudioDeviceID devid, SDL_AudioSpec *spec, int *sample_frames)
SDL_DECLSPEC float SDLCALL SDL_GetAudioDeviceGain (SDL_AudioDeviceID devid)
SDL_DECLSPEC const char *SDLCALL SDL_GetAudioDeviceName (SDL_AudioDeviceID devid)
SDL_DECLSPEC const char *SDLCALL SDL_GetAudioDriver (int index)
SDL_DECLSPEC const char *SDLCALL SDL_GetAudioFormatName (SDL_AudioFormat format)
SDL_DECLSPEC SDL_AudioDeviceID *SDLCALL SDL_GetAudioPlaybackDevices (int *count)
SDL_DECLSPEC SDL_AudioDeviceID *SDLCALL SDL_GetAudioRecordingDevices (int *count)
SDL_DECLSPEC int SDLCALL SDL_GetAudioStreamAvailable (SDL_AudioStream *stream)
SDL_DECLSPEC int SDLCALL SDL_GetAudioStreamData (SDL_AudioStream *stream, void *buf, int len)
SDL_DECLSPEC SDL_AudioDeviceID SDLCALL SDL_GetAudioStreamDevice (SDL_AudioStream *stream)
SDL_DECLSPEC bool SDLCALL SDL_GetAudioStreamFormat (SDL_AudioStream *stream, SDL_AudioSpec *src_spec, SDL_AudioSpec *dst_spec)
SDL_DECLSPEC float SDLCALL SDL_GetAudioStreamFrequencyRatio (SDL_AudioStream *stream)
SDL_DECLSPEC float SDLCALL SDL_GetAudioStreamGain (SDL_AudioStream *stream)
SDL_DECLSPEC int *SDLCALL SDL_GetAudioStreamInputChannelMap (SDL_AudioStream *stream, int *count)
SDL_DECLSPEC int *SDLCALL SDL_GetAudioStreamOutputChannelMap (SDL_AudioStream *stream, int *count)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetAudioStreamProperties (SDL_AudioStream *stream)
SDL_DECLSPEC int SDLCALL SDL_GetAudioStreamQueued (SDL_AudioStream *stream)
SDL_DECLSPEC const char *SDLCALL SDL_GetCurrentAudioDriver (void)
SDL_DECLSPEC int SDLCALL SDL_GetNumAudioDrivers (void)
SDL_DECLSPEC int SDLCALL SDL_GetSilenceValueForFormat (SDL_AudioFormat format)
SDL_DECLSPEC bool SDLCALL SDL_IsAudioDevicePhysical (SDL_AudioDeviceID devid)
SDL_DECLSPEC bool SDLCALL SDL_IsAudioDevicePlayback (SDL_AudioDeviceID devid)
SDL_DECLSPEC bool SDLCALL SDL_LoadWAV (const char *path, SDL_AudioSpec *spec, Uint8 **audio_buf, Uint32 *audio_len)
SDL_DECLSPEC bool SDLCALL SDL_LoadWAV_IO (SDL_IOStream *src, bool closeio, SDL_AudioSpec *spec, Uint8 **audio_buf, Uint32 *audio_len)
SDL_DECLSPEC bool SDLCALL SDL_LockAudioStream (SDL_AudioStream *stream)
SDL_DECLSPEC bool SDLCALL SDL_MixAudio (Uint8 *dst, const Uint8 *src, SDL_AudioFormat format, Uint32 len, float volume)
SDL_DECLSPEC SDL_AudioDeviceID SDLCALL SDL_OpenAudioDevice (SDL_AudioDeviceID devid, const SDL_AudioSpec *spec)
SDL_DECLSPEC SDL_AudioStream *SDLCALL SDL_OpenAudioDeviceStream (SDL_AudioDeviceID devid, const SDL_AudioSpec *spec, SDL_AudioStreamCallback callback, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_PauseAudioDevice (SDL_AudioDeviceID devid)
SDL_DECLSPEC bool SDLCALL SDL_PauseAudioStreamDevice (SDL_AudioStream *stream)
SDL_DECLSPEC bool SDLCALL SDL_PutAudioStreamData (SDL_AudioStream *stream, const void *buf, int len)
SDL_DECLSPEC bool SDLCALL SDL_PutAudioStreamDataNoCopy (SDL_AudioStream *stream, const void *buf, int len, SDL_AudioStreamDataCompleteCallback callback, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_PutAudioStreamPlanarData (SDL_AudioStream *stream, const void *const *channel_buffers, int num_channels, int num_samples)
SDL_DECLSPEC bool SDLCALL SDL_ResumeAudioDevice (SDL_AudioDeviceID devid)
SDL_DECLSPEC bool SDLCALL SDL_ResumeAudioStreamDevice (SDL_AudioStream *stream)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioDeviceGain (SDL_AudioDeviceID devid, float gain)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioPostmixCallback (SDL_AudioDeviceID devid, SDL_AudioPostmixCallback callback, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamFormat (SDL_AudioStream *stream, const SDL_AudioSpec *src_spec, const SDL_AudioSpec *dst_spec)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamFrequencyRatio (SDL_AudioStream *stream, float ratio)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamGain (SDL_AudioStream *stream, float gain)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamGetCallback (SDL_AudioStream *stream, SDL_AudioStreamCallback callback, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamInputChannelMap (SDL_AudioStream *stream, const int *chmap, int count)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamOutputChannelMap (SDL_AudioStream *stream, const int *chmap, int count)
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamPutCallback (SDL_AudioStream *stream, SDL_AudioStreamCallback callback, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_UnbindAudioStream (SDL_AudioStream *stream)
SDL_DECLSPEC void SDLCALL SDL_UnbindAudioStreams (SDL_AudioStream *const *streams, int num_streams)
SDL_DECLSPEC bool SDLCALL SDL_UnlockAudioStream (SDL_AudioStream *stream)
Macro Definition Documentation
SDL_AUDIO_BITSIZE
#define SDL_AUDIO_BITSIZE (x)
Value:
((x) & SDL_AUDIO_MASK_BITSIZE)
Retrieve the size, in bits, from an SDL_AudioFormat.
For example, SDL_AUDIO_BITSIZE(SDL_AUDIO_S16) returns 16.
Parameters
x an SDL_AudioFormat value.
Returns
data size in bits.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by ConvertAudio(), InterleaveAudioChannels(), OpenPhysicalAudioDevice(), SDL_DefaultAudioDeviceChanged(), and SwizzleAudio().
SDL_AUDIO_BYTESIZE
#define SDL_AUDIO_BYTESIZE (x)
Value:
(SDL_AUDIO_BITSIZE(x) / 8)
Retrieve the size, in bytes, from an SDL_AudioFormat.
For example, SDL_AUDIO_BYTESIZE(SDL_AUDIO_S16) returns 2.
Parameters
x an SDL_AudioFormat value.
Returns
data size in bytes.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by CalculateMaxFrameSize(), GetAudioStreamDataInternal(), SDL_PlaybackAudioThreadIterate(), and SDL_ReadFromAudioQueue().
SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK
#define SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK ((SDL_AudioDeviceID) 0xFFFFFFFFu)
A value used to request a default playback audio device.
Several functions that require an SDL_AudioDeviceID will accept this value to signify the app just wants the system to choose a default device instead of the app providing a specific one.
Since
This macro is available since SDL 3.2.0.
Referenced by GetFirstAddedAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), SDL_COMPILE_TIME_ASSERT(), and SDL_OpenAudioDevice().
SDL_AUDIO_DEVICE_DEFAULT_RECORDING
#define SDL_AUDIO_DEVICE_DEFAULT_RECORDING ((SDL_AudioDeviceID) 0xFFFFFFFEu)
A value used to request a default recording audio device.
Several functions that require an SDL_AudioDeviceID will accept this value to signify the app just wants the system to choose a default device instead of the app providing a specific one.
Since
This macro is available since SDL 3.2.0.
Referenced by AssignAudioDeviceInstanceId(), ObtainPhysicalAudioDeviceDefaultAllowed(), SDL_COMPILE_TIME_ASSERT(), and SDL_OpenAudioDevice().
SDL_AUDIO_FRAMESIZE
#define SDL_AUDIO_FRAMESIZE (x)
Value:
(SDL_AUDIO_BYTESIZE((x).format) * (x).channels)
Calculate the size of each audio frame (in bytes) from an SDL_AudioSpec.
This reports on the size of an audio sample frame: stereo Sint16 data (2 channels of 2 bytes each) would be 4 bytes per frame, for example.
Parameters
x an SDL_AudioSpec to query.
Returns
the number of bytes used per sample frame.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by CreateChunkedAudioTrack(), InterleaveAudioChannels(), NextAudioStreamIter(), PutAudioStreamBuffer(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), SDL_PlaybackAudioThreadIterate(), SDL_PlaybackAudioThreadShutdown(), SDL_PutAudioStreamPlanarData(), SDL_RecordingAudioThreadIterate(), SDL_ResetAudioQueueHistory(), SDL_UpdatedAudioDeviceFormat(), and ZombieWaitDevice().
SDL_AUDIO_ISBIGENDIAN
#define SDL_AUDIO_ISBIGENDIAN (x)
Value:
((x) & SDL_AUDIO_MASK_BIG_ENDIAN)
Determine if an SDL_AudioFormat represents bigendian data.
For example, SDL_AUDIO_ISBIGENDIAN(SDL_AUDIO_S16LE) returns 0.
Parameters
x an SDL_AudioFormat value.
Returns
non-zero if format is bigendian, zero otherwise.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_ISFLOAT
#define SDL_AUDIO_ISFLOAT (x)
Value:
((x) & SDL_AUDIO_MASK_FLOAT)
Determine if an SDL_AudioFormat represents floating point data.
For example, SDL_AUDIO_ISFLOAT(SDL_AUDIO_S16) returns 0.
Parameters
x an SDL_AudioFormat value.
Returns
non-zero if format is floating point, zero otherwise.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_ISINT
#define SDL_AUDIO_ISINT (x)
Value:
(!SDL_AUDIO_ISFLOAT(x))
Determine if an SDL_AudioFormat represents integer data.
For example, SDL_AUDIO_ISINT(SDL_AUDIO_F32) returns 0.
Parameters
x an SDL_AudioFormat value.
Returns
non-zero if format is integer, zero otherwise.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_ISLITTLEENDIAN
#define SDL_AUDIO_ISLITTLEENDIAN (x)
Value:
(!SDL_AUDIO_ISBIGENDIAN(x))
Determine if an SDL_AudioFormat represents littleendian data.
For example, SDL_AUDIO_ISLITTLEENDIAN(SDL_AUDIO_S16BE) returns 0.
Parameters
x an SDL_AudioFormat value.
Returns
non-zero if format is littleendian, zero otherwise.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_ISSIGNED
#define SDL_AUDIO_ISSIGNED (x)
Value:
((x) & SDL_AUDIO_MASK_SIGNED)
Determine if an SDL_AudioFormat represents signed data.
For example, SDL_AUDIO_ISSIGNED(SDL_AUDIO_U8) returns 0.
Parameters
x an SDL_AudioFormat value.
Returns
non-zero if format is signed, zero otherwise.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_ISUNSIGNED
#define SDL_AUDIO_ISUNSIGNED (x)
Value:
(!SDL_AUDIO_ISSIGNED(x))
Determine if an SDL_AudioFormat represents unsigned data.
For example, SDL_AUDIO_ISUNSIGNED(SDL_AUDIO_S16) returns 0.
Parameters
x an SDL_AudioFormat value.
Returns
non-zero if format is unsigned, zero otherwise.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_MASK_BIG_ENDIAN
#define SDL_AUDIO_MASK_BIG_ENDIAN (1u<<12)
Mask of bits in an SDL_AudioFormat that contain the bigendian flag.
Generally one should use SDL_AUDIO_ISBIGENDIAN or SDL_AUDIO_ISLITTLEENDIAN instead of this macro directly.
Since
This macro is available since SDL 3.2.0.
Referenced by ConvertAudio(), ConvertAudioFromFloat(), and ConvertAudioToFloat().
SDL_AUDIO_MASK_BITSIZE
#define SDL_AUDIO_MASK_BITSIZE (0xFFu)
CategoryAudio
Audio functionality for the SDL library.
All audio in SDL3 revolves around SDL_AudioStream. Whether you want to play or record audio, convert it, stream it, buffer it, or mix it, you're going to be passing it through an audio stream.
Audio streams are quite flexible; they can accept any amount of data at a time, in any supported format, and output it as needed in any other format, even if the data format changes on either side halfway through.
An app opens an audio device and binds any number of audio streams to it, feeding more data to the streams as available. When the device needs more data, it will pull it from all bound streams and mix them together for playback.
Audio streams can also use an app-provided callback to supply data on-demand, which maps pretty closely to the SDL2 audio model.
SDL also provides a simple .WAV loader in SDL_LoadWAV (and SDL_LoadWAV_IO if you aren't reading from a file) as a basic means to load sound data into your program.
Logical audio devices
In SDL3, opening a physical device (like a SoundBlaster 16 Pro) gives you a logical device ID that you can bind audio streams to. In almost all cases, logical devices can be used anywhere in the API that a physical device is normally used. However, since each device opening generates a new logical device, different parts of the program (say, a VoIP library, or text-to-speech framework, or maybe some other sort of mixer on top of SDL) can have their own device opens that do not interfere with each other; each logical device will mix its separate audio down to a single buffer, fed to the physical device, behind the scenes. As many logical devices as you like can come and go; SDL will only have to open the physical device at the OS level once, and will manage all the logical devices on top of it internally.
One other benefit of logical devices: if you don't open a specific physical device, instead opting for the default, SDL can automatically migrate those logical devices to different hardware as circumstances change: a user plugged in headphones? The system default changed? SDL can transparently migrate the logical devices to the correct physical device seamlessly and keep playing; the app doesn't even have to know it happened if it doesn't want to.
Simplified audio
As a simplified model for when a single source of audio is all that's needed, an app can use SDL_OpenAudioDeviceStream, which is a single function to open an audio device, create an audio stream, bind that stream to the newly-opened device, and (optionally) provide a callback for obtaining audio data. When using this function, the primary interface is the SDL_AudioStream and the device handle is mostly hidden away; destroying a stream created through this function will also close the device, stream bindings cannot be changed, etc. One other quirk of this is that the device is started in a paused state and must be explicitly resumed; this is partially to offer a clean migration for SDL2 apps and partially because the app might have to do more setup before playback begins; in the non-simplified form, nothing will play until a stream is bound to a device, so they start unpaused.
Channel layouts
Audio data passing through SDL is uncompressed PCM data, interleaved. One can provide their own decompression through an MP3, etc, decoder, but SDL does not provide this directly. Each interleaved channel of data is meant to be in a specific order.
Abbreviations:
FRONT = single mono speaker
FL = front left speaker
FR = front right speaker
FC = front center speaker
BL = back left speaker
BR = back right speaker
SR = surround right speaker
SL = surround left speaker
BC = back center speaker
LFE = low-frequency speaker
These are listed in the order they are laid out in memory, so "FL, FR" means "the front left speaker is laid out in memory first, then the front right, then it repeats for the next audio frame".
1 channel (mono) layout: FRONT
2 channels (stereo) layout: FL, FR
3 channels (2.1) layout: FL, FR, LFE
4 channels (quad) layout: FL, FR, BL, BR
5 channels (4.1) layout: FL, FR, LFE, BL, BR
6 channels (5.1) layout: FL, FR, FC, LFE, BL, BR (last two can also be SL, SR)
7 channels (6.1) layout: FL, FR, FC, LFE, BC, SL, SR
8 channels (7.1) layout: FL, FR, FC, LFE, BL, BR, SL, SR
This is the same order as DirectSound expects, but applied to all platforms; SDL will swizzle the channels as necessary if a platform expects something different.
SDL_AudioStream can also be provided channel maps to change this ordering to whatever is necessary, in other audio processing scenarios. Mask of bits in an SDL_AudioFormat that contains the format bit size.
Generally one should use SDL_AUDIO_BITSIZE instead of this macro directly.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_MASK_FLOAT
#define SDL_AUDIO_MASK_FLOAT (1u<<8)
Mask of bits in an SDL_AudioFormat that contain the floating point flag.
Generally one should use SDL_AUDIO_ISFLOAT instead of this macro directly.
Since
This macro is available since SDL 3.2.0.
SDL_AUDIO_MASK_SIGNED
#define SDL_AUDIO_MASK_SIGNED (1u<<15)
Mask of bits in an SDL_AudioFormat that contain the signed data flag.
Generally one should use SDL_AUDIO_ISSIGNED instead of this macro directly.
Since
This macro is available since SDL 3.2.0.
SDL_DEFINE_AUDIO_FORMAT
#define SDL_DEFINE_AUDIO_FORMAT (signed, bigendian, flt, size)
Value:
    (((Uint16)(signed) << 15) | ((Uint16)(bigendian) << 12) | ((Uint16)(flt) << 8) | ((size) & SDL_AUDIO_MASK_BITSIZE))
Define an SDL_AudioFormat value.
SDL does not support custom audio formats, so this macro is not of much use externally, but it can be illustrative as to what the various bits of an SDL_AudioFormat mean.
For example, SDL_AUDIO_S32LE looks like this:
SDL_DEFINE_AUDIO_FORMAT(1, 0, 0, 32)
Parameters
signed 1 for signed data, 0 for unsigned data.
bigendian 1 for bigendian data, 0 for littleendian data.
flt 1 for floating point data, 0 for integer data.
size number of bits per sample.
Returns
a format value in the style of SDL_AudioFormat.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
#define SDL_DEFINE_AUDIO_FORMAT(signed, bigendian, flt, size) \
    (((Uint16)(signed) << 15) | ((Uint16)(bigendian) << 12) | ((Uint16)(flt) << 8) | ((size) & SDL_AUDIO_MASK_BITSIZE))
SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN
#define SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN "SDL.audiostream.auto_cleanup"
Referenced by SDL_QuitAudio().
Typedef Documentation
SDL_AudioDeviceID
typedef Uint32 SDL_AudioDeviceID
SDL Audio Device instance IDs.
Zero is used to signify an invalid/null device.
Since
This datatype is available since SDL 3.2.0.
SDL_AudioFormat
typedef enum SDL_AudioFormat SDL_AudioFormat
Audio format.
Since
This enum is available since SDL 3.2.0.
See also
SDL_AUDIO_BITSIZE
SDL_AUDIO_BYTESIZE
SDL_AUDIO_ISINT
SDL_AUDIO_ISFLOAT
SDL_AUDIO_ISBIGENDIAN
SDL_AUDIO_ISLITTLEENDIAN
SDL_AUDIO_ISSIGNED
SDL_AUDIO_ISUNSIGNED
SDL_AudioPostmixCallback
typedef void(SDLCALL * SDL_AudioPostmixCallback) (void *userdata, const SDL_AudioSpec *spec, float *buffer, int buflen)
A callback that fires when data is about to be fed to an audio device.
This is useful for accessing the final mix, perhaps for writing a visualizer or applying a final effect to the audio data before playback.
This callback should run as quickly as possible and not block for any significant time, as this callback delays submission of data to the audio device, which can cause audio playback problems.
The postmix callback must be able to handle any audio data format specified in spec, which can change between callbacks if the audio device changed. However, this only covers frequency and channel count; data is always provided here in SDL_AUDIO_F32 format.
The postmix callback runs after logical device gain and audiostream gain have been applied, which is to say you can make the output data louder at this point than the gain settings would suggest.
Parameters
userdata a pointer provided by the app through SDL_SetAudioPostmixCallback, for its own use.
spec the current format of audio that is to be submitted to the audio device.
buffer the buffer of audio samples to be submitted. The callback can inspect and/or modify this data.
buflen the size of buffer in bytes.
Thread Safety
This will run from a background thread owned by SDL. The application is responsible for locking resources the callback touches that need to be protected.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_SetAudioPostmixCallback
SDL_AudioSpec
typedef struct SDL_AudioSpec SDL_AudioSpec
Format specifier for audio data.
Since
This struct is available since SDL 3.2.0.
See also
SDL_AudioFormat
SDL_AudioStream
typedef struct SDL_AudioStream SDL_AudioStream
The opaque handle that represents an audio stream.
SDL_AudioStream is an audio conversion interface.
It can handle resampling data in chunks without generating artifacts, when it doesn't have the complete buffer available.
It can handle incoming data in any variable size.
It can handle input/output format changes on the fly.
It can remap audio channels between inputs and outputs.
You push data as you have it, and pull it when you need it
It can also function as a basic audio data queue even if you just have sound that needs to pass from one place to another.
You can hook callbacks up to them when more data is added or requested, to manage data on-the-fly.
Audio streams are the core of the SDL3 audio interface. You create one or more of them, bind them to an opened audio device, and feed data to them (or for recording, consume data from them).
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateAudioStream
SDL_AudioStreamCallback
typedef void(SDLCALL * SDL_AudioStreamCallback) (void *userdata, SDL_AudioStream *stream, int additional_amount, int total_amount)
A callback that fires when data passes through an SDL_AudioStream.
Apps can (optionally) register a callback with an audio stream that is called when data is added with SDL_PutAudioStreamData, or requested with SDL_GetAudioStreamData.
Two values are offered here: one is the amount of additional data needed to satisfy the immediate request (which might be zero if the stream already has enough data queued) and the other is the total amount being requested. In a Get call triggering a Put callback, these values can be different. In a Put call triggering a Get callback, these values are always the same.
Byte counts might be slightly overestimated due to buffering or resampling, and may change from call to call.
This callback is not required to do anything. Generally this is useful for adding/reading data on demand, and the app will often put/get data as appropriate, but the system goes on with the data currently available to it if this callback does nothing.
Parameters
stream the SDL audio stream associated with this callback.
additional_amount the amount of data, in bytes, that is needed right now.
total_amount the total amount of data requested, in bytes, that is requested or available.
userdata an opaque pointer provided by the app for their personal use.
Thread Safety
This callbacks may run from any thread, so if you need to protect shared data, you should use SDL_LockAudioStream to serialize access; this lock will be held before your callback is called, so your callback does not need to manage the lock explicitly.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_SetAudioStreamGetCallback
SDL_SetAudioStreamPutCallback
SDL_AudioStreamDataCompleteCallback
typedef void(SDLCALL * SDL_AudioStreamDataCompleteCallback) (void *userdata, const void *buf, int buflen)
A callback that fires for completed SDL_PutAudioStreamDataNoCopy() data.
When using SDL_PutAudioStreamDataNoCopy() to provide data to an SDL_AudioStream, it's not safe to dispose of the data until the stream has completely consumed it. Often times it's difficult to know exactly when this has happened.
This callback fires once when the stream no longer needs the buffer, allowing the app to easily free or reuse it.
Parameters
userdata an opaque pointer provided by the app for their personal use.
buf the pointer provided to SDL_PutAudioStreamDataNoCopy().
buflen the size of buffer, in bytes, provided to SDL_PutAudioStreamDataNoCopy().
Thread Safety
This callbacks may run from any thread, so if you need to protect shared data, you should use SDL_LockAudioStream to serialize access; this lock will be held before your callback is called, so your callback does not need to manage the lock explicitly.
Since
This datatype is available since SDL 3.4.0.
See also
SDL_SetAudioStreamGetCallback
SDL_SetAudioStreamPutCallback
Enumeration Type Documentation
SDL_AudioFormat
enum SDL_AudioFormat
Audio format.
Since
This enum is available since SDL 3.2.0.
See also
SDL_AUDIO_BITSIZE
SDL_AUDIO_BYTESIZE
SDL_AUDIO_ISINT
SDL_AUDIO_ISFLOAT
SDL_AUDIO_ISBIGENDIAN
SDL_AUDIO_ISLITTLEENDIAN
SDL_AUDIO_ISSIGNED
SDL_AUDIO_ISUNSIGNED
Enumerator
SDL_AUDIO_UNKNOWN
Unspecified audio format
SDL_AUDIO_U8
Unsigned 8-bit samples
SDL_AUDIO_S8
Signed 8-bit samples
SDL_AUDIO_S16LE
Signed 16-bit samples
SDL_AUDIO_S16BE
As above, but big-endian byte order
SDL_AUDIO_S32LE
32-bit integer samples
SDL_AUDIO_S32BE
As above, but big-endian byte order
SDL_AUDIO_F32LE
32-bit floating point samples
SDL_AUDIO_F32BE
As above, but big-endian byte order
SDL_AUDIO_S16
SDL_AUDIO_S32
SDL_AUDIO_F32
{
    SDL_AUDIO_UNKNOWN   = 0x0000u,  /**< Unspecified audio format */
    SDL_AUDIO_U8        = 0x0008u,  /**< Unsigned 8-bit samples */
        /* SDL_DEFINE_AUDIO_FORMAT(0, 0, 0, 8), */
    SDL_AUDIO_S8        = 0x8008u,  /**< Signed 8-bit samples */
        /* SDL_DEFINE_AUDIO_FORMAT(1, 0, 0, 8), */
    SDL_AUDIO_S16LE     = 0x8010u,  /**< Signed 16-bit samples */
        /* SDL_DEFINE_AUDIO_FORMAT(1, 0, 0, 16), */
    SDL_AUDIO_S16BE     = 0x9010u,  /**< As above, but big-endian byte order */
        /* SDL_DEFINE_AUDIO_FORMAT(1, 1, 0, 16), */
    SDL_AUDIO_S32LE     = 0x8020u,  /**< 32-bit integer samples */
        /* SDL_DEFINE_AUDIO_FORMAT(1, 0, 0, 32), */
    SDL_AUDIO_S32BE     = 0x9020u,  /**< As above, but big-endian byte order */
        /* SDL_DEFINE_AUDIO_FORMAT(1, 1, 0, 32), */
    SDL_AUDIO_F32LE     = 0x8120u,  /**< 32-bit floating point samples */
        /* SDL_DEFINE_AUDIO_FORMAT(1, 0, 1, 32), */
    SDL_AUDIO_F32BE     = 0x9120u,  /**< As above, but big-endian byte order */
        /* SDL_DEFINE_AUDIO_FORMAT(1, 1, 1, 32), */
    /* These represent the current system's byteorder. */
    #if SDL_BYTEORDER == SDL_LIL_ENDIAN
    SDL_AUDIO_S16 = SDL_AUDIO_S16LE,
    SDL_AUDIO_S32 = SDL_AUDIO_S32LE,
    SDL_AUDIO_F32 = SDL_AUDIO_F32LE
    #else
    SDL_AUDIO_S16 = SDL_AUDIO_S16BE,
    SDL_AUDIO_S32 = SDL_AUDIO_S32BE,
    SDL_AUDIO_F32 = SDL_AUDIO_F32BE
    #endif
} SDL_AudioFormat;
Function Documentation
SDL_AudioDevicePaused()
SDL_DECLSPEC bool SDLCALL SDL_AudioDevicePaused (SDL_AudioDeviceID devid) extern
Use this function to query if an audio device is paused.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow.
Physical devices can not be paused or unpaused, only logical devices created through SDL_OpenAudioDevice() can be. Physical and invalid device IDs will report themselves as unpaused here.
Parameters
devid a device opened by SDL_OpenAudioDevice().
Returns
true if device is valid and paused, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseAudioDevice
SDL_ResumeAudioDevice
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    bool result = false;
    if (logdev && SDL_GetAtomicInt(&logdev->paused)) {
        result = true;
    }
    ReleaseAudioDevice(device);
    return result;
}
References NULL, ObtainLogicalAudioDevice(), SDL_LogicalAudioDevice::paused, ReleaseAudioDevice(), and SDL_GetAtomicInt().
Referenced by SDL_AudioStreamDevicePaused().
SDL_AudioStreamDevicePaused()
SDL_DECLSPEC bool SDLCALL SDL_AudioStreamDevicePaused (SDL_AudioStream * stream) extern
Use this function to query if an audio device associated with a stream is paused.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow.
Parameters
stream the audio stream associated with the audio device to query.
Returns
true if device is valid and paused, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseAudioStreamDevice
SDL_ResumeAudioStreamDevice
{
    SDL_AudioDeviceID devid = SDL_GetAudioStreamDevice(stream);
    if (!devid) {
        return false;
    }
    return SDL_AudioDevicePaused(devid);
}
References SDL_AudioDevicePaused(), and SDL_GetAudioStreamDevice().
SDL_BindAudioStream()
SDL_DECLSPEC bool SDLCALL SDL_BindAudioStream (SDL_AudioDeviceID devid, SDL_AudioStream * stream) extern
Bind a single audio stream to an audio device.
This is a convenience function, equivalent to calling SDL_BindAudioStreams(devid, &stream, 1).
Parameters
devid an audio device to bind a stream to.
stream an audio stream to bind to a device.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStreams
SDL_UnbindAudioStream
SDL_GetAudioStreamDevice
{
    return SDL_BindAudioStreams(devid, &stream, 1);
}
References SDL_BindAudioStreams().
SDL_BindAudioStreams()
SDL_DECLSPEC bool SDLCALL SDL_BindAudioStreams (SDL_AudioDeviceID devid, SDL_AudioStream *const * streams, int num_streams) extern
Bind a list of audio streams to an audio device.
Audio data will flow through any bound streams. For a playback device, data for all bound streams will be mixed together and fed to the device. For a recording device, a copy of recorded data will be provided to each bound stream.
Audio streams can only be bound to an open device. This operation is atomic–all streams bound in the same call will start processing at the same time, so they can stay in sync. Also: either all streams will be bound or none of them will be.
It is an error to bind an already-bound stream; it must be explicitly unbound first.
Binding a stream to a device will set its output format for playback devices, and its input format for recording devices, so they match the device's settings. The caller is welcome to change the other end of the stream's format at any time with SDL_SetAudioStreamFormat(). If the other end of the stream's format has never been set (the audio stream was created with a NULL audio spec), this function will set it to match the device end's format.
Parameters
devid an audio device to bind a stream to.
streams an array of audio streams to bind.
num_streams number streams listed in the streams array.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStreams
SDL_UnbindAudioStream
SDL_GetAudioStreamDevice
{
    const bool islogical = !(devid & (1<<1));
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = NULL;
    bool result = true;
    if (num_streams == 0) {
        return true;  // nothing to do
    } else if (num_streams < 0) {
        return SDL_InvalidParamError("num_streams");
    } else if (!streams) {
        return SDL_InvalidParamError("streams");
    } else if (!islogical) {
        return SDL_SetError("Audio streams are bound to device ids from SDL_OpenAudioDevice, not raw physical devices");
    }
    logdev = ObtainLogicalAudioDevice(devid, &device);
    if (!logdev) {
        result = false;  // ObtainLogicalAudioDevice set the error string.
    } else if (logdev->simplified) {
        result = SDL_SetError("Cannot change stream bindings on device opened with SDL_OpenAudioDeviceStream");
    } else {
        // make sure start of list is sane.
        SDL_assert(!logdev->bound_streams || (logdev->bound_streams->prev_binding == NULL));
        // lock all the streams upfront, so we can verify they aren't bound elsewhere and add them all in one block, as this is intended to add everything or nothing.
        for (int i = 0; i < num_streams; i++) {
            SDL_AudioStream *stream = streams[i];
            if (!stream) {
                SDL_SetError("Stream #%d is NULL", i);
                result = false;  // to pacify the static analyzer, that doesn't realize SDL_SetError() always returns false.
            } else {
                SDL_LockMutex(stream->lock);
                SDL_assert((stream->bound_device == NULL) == ((stream->prev_binding == NULL) || (stream->next_binding == NULL)));
                if (stream->bound_device) {
                    result = SDL_SetError("Stream #%d is already bound to a device", i);
                } else if (stream->simplified) {  // You can get here if you closed the device instead of destroying the stream.
                    result = SDL_SetError("Cannot change binding on a stream created with SDL_OpenAudioDeviceStream");
                }
            }
            if (!result) {
                int j;
                for (j = 0; j < i; j++) {
                    SDL_UnlockMutex(streams[j]->lock);
                }
                if (stream) {
                    SDL_UnlockMutex(stream->lock);
                }
                break;
            }
        }
    }
    if (result) {
        // Now that everything is verified, chain everything together.
        const bool recording = device->recording;
        for (int i = 0; i < num_streams; i++) {
            SDL_AudioStream *stream = streams[i];
            if (stream) {  // shouldn't be NULL, but just in case...
                // if the stream never had its non-device-end format set, just set it to the device end's format.
                if (recording && (stream->dst_spec.format == SDL_AUDIO_UNKNOWN)) {
                    SDL_copyp(&stream->dst_spec, &device->spec);
                } else if (!recording && (stream->src_spec.format == SDL_AUDIO_UNKNOWN)) {
                    SDL_copyp(&stream->src_spec, &device->spec);
                }
                stream->bound_device = logdev;
                stream->prev_binding = NULL;
                stream->next_binding = logdev->bound_streams;
                if (logdev->bound_streams) {
                    logdev->bound_streams->prev_binding = stream;
                }
                logdev->bound_streams = stream;
                SDL_UnlockMutex(stream->lock);
            }
        }
    }
    UpdateAudioStreamFormatsPhysical(device);
    ReleaseAudioDevice(device);
    return result;
}
References SDL_LogicalAudioDevice::bound_streams, lock, NULL, ObtainLogicalAudioDevice(), SDL_AudioStream::prev_binding, SDL_AudioDevice::recording, ReleaseAudioDevice(), SDL_assert, SDL_AUDIO_UNKNOWN, SDL_copyp, SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), SDL_UnlockMutex(), SDL_LogicalAudioDevice::simplified, SDL_AudioDevice::spec, and UpdateAudioStreamFormatsPhysical().
Referenced by SDL_BindAudioStream().
SDL_ClearAudioStream()
SDL_DECLSPEC bool SDLCALL SDL_ClearAudioStream (SDL_AudioStream * stream) extern
Clear any pending data in the stream.
This drops any queued data, so there will be nothing to read from the stream until more is added.
Parameters
stream the audio stream to clear.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamAvailable
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
SDL_PutAudioStreamData
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    SDL_ClearAudioQueue(stream->queue);
    SDL_zero(stream->input_spec);
    stream->input_chmap = NULL;
    stream->resample_offset = 0;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References NULL, SDL_ClearAudioQueue(), SDL_InvalidParamError, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_zero.
SDL_CloseAudioDevice()
SDL_DECLSPEC void SDLCALL SDL_CloseAudioDevice (SDL_AudioDeviceID devid) extern
Close a previously-opened audio device.
The application should close open audio devices once they are no longer needed.
This function may block briefly while pending audio data is played by the hardware, so that applications don't drop the last buffer of data they supplied if terminating immediately afterwards.
Parameters
devid an audio device id previously returned by SDL_OpenAudioDevice().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenAudioDevice
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    if (logdev) {
        DestroyLogicalAudioDevice(logdev);
    }
    if (device) {
        if (!device->logical_devices) {  // no more logical devices? Close the physical device, too.
            ClosePhysicalAudioDevice(device);
        }
        UnrefPhysicalAudioDevice(device);  // one reference for each logical device.
    }
    ReleaseAudioDevice(device);
}
References ClosePhysicalAudioDevice(), DestroyLogicalAudioDevice(), SDL_AudioDevice::logical_devices, NULL, ObtainLogicalAudioDevice(), ReleaseAudioDevice(), and UnrefPhysicalAudioDevice().
Referenced by SDL_DestroyAudioStream(), SDL_OpenAudioDevice(), and SDL_OpenAudioDeviceStream().
SDL_ConvertAudioSamples()
SDL_DECLSPEC bool SDLCALL SDL_ConvertAudioSamples (const SDL_AudioSpec * src_spec, const Uint8 * src_data, int src_len, const SDL_AudioSpec * dst_spec, Uint8 ** dst_data, int * dst_len) extern
Convert some audio data of one format to another format.
Please note that this function is for convenience, but should not be used to resample audio in blocks, as it will introduce audio artifacts on the boundaries. You should only use this function if you are converting audio data in its entirety in one call. If you want to convert audio in smaller chunks, use an SDL_AudioStream, which is designed for this situation.
Internally, this function creates and destroys an SDL_AudioStream on each use, so it's also less efficient than using one directly, if you need to convert multiple times.
Parameters
src_spec the format details of the input audio.
src_data the audio data to be converted.
src_len the len of src_data.
dst_spec the format details of the output audio.
dst_data will be filled with a pointer to converted audio data, which should be freed with SDL_free(). On error, it will be NULL.
dst_len will be filled with the len of dst_data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (dst_data) {
        *dst_data = NULL;
    }
    if (dst_len) {
        *dst_len = 0;
    }
    if (!src_data) {
        return SDL_InvalidParamError("src_data");
    } else if (src_len < 0) {
        return SDL_InvalidParamError("src_len");
    } else if (!dst_data) {
        return SDL_InvalidParamError("dst_data");
    } else if (!dst_len) {
        return SDL_InvalidParamError("dst_len");
    }
    bool result = false;
    Uint8 *dst = NULL;
    int dstlen = 0;
    SDL_AudioStream *stream = SDL_CreateAudioStream(src_spec, dst_spec);
    if (stream) {
        if (SDL_PutAudioStreamDataNoCopy(stream, src_data, src_len, NULL, NULL) && SDL_FlushAudioStream(stream)) {
            dstlen = SDL_GetAudioStreamAvailable(stream);
            if (dstlen >= 0) {
                dst = (Uint8 *)SDL_malloc(dstlen);
                if (dst) {
                    result = (SDL_GetAudioStreamData(stream, dst, dstlen) == dstlen);
                }
            }
        }
    }
    if (result) {
        *dst_data = dst;
        *dst_len = dstlen;
    } else {
        SDL_free(dst);
    }
    SDL_DestroyAudioStream(stream);
    return result;
}
References NULL, SDL_CreateAudioStream(), SDL_DestroyAudioStream(), SDL_FlushAudioStream(), SDL_free(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamData(), SDL_InvalidParamError, SDL_malloc(), and SDL_PutAudioStreamDataNoCopy().
SDL_CreateAudioStream()
SDL_DECLSPEC SDL_AudioStream *SDLCALL SDL_CreateAudioStream (const SDL_AudioSpec * src_spec, const SDL_AudioSpec * dst_spec) extern
Create a new audio stream.
Parameters
src_spec the format details of the input audio.
dst_spec the format details of the output audio.
Returns
a new audio stream on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PutAudioStreamData
SDL_GetAudioStreamData
SDL_GetAudioStreamAvailable
SDL_FlushAudioStream
SDL_ClearAudioStream
SDL_SetAudioStreamFormat
SDL_DestroyAudioStream
{
    SDL_ChooseAudioConverters();
    SDL_SetupAudioResampler();
    SDL_AudioStream *result = (SDL_AudioStream *)SDL_calloc(1, sizeof(SDL_AudioStream));
    if (!result) {
        return NULL;
    }
    result->freq_ratio = 1.0f;
    result->gain = 1.0f;
    result->queue = SDL_CreateAudioQueue(8192);
    if (!result->queue) {
        SDL_free(result);
        return NULL;
    }
    result->lock = SDL_CreateMutex();
    if (!result->lock) {
        SDL_free(result->queue);
        SDL_free(result);
        return NULL;
    }
    OnAudioStreamCreated(result);
    if (!SDL_SetAudioStreamFormat(result, src_spec, dst_spec)) {
        SDL_DestroyAudioStream(result);
        return NULL;
    }
    return result;
}
References SDL_AudioStream::freq_ratio, SDL_AudioStream::gain, SDL_AudioStream::lock, NULL, OnAudioStreamCreated(), SDL_AudioStream::queue, SDL_calloc(), SDL_ChooseAudioConverters(), SDL_CreateAudioQueue(), SDL_CreateMutex(), SDL_DestroyAudioStream(), SDL_free(), SDL_SetAudioStreamFormat(), and SDL_SetupAudioResampler().
Referenced by SDL_ConvertAudioSamples(), and SDL_OpenAudioDeviceStream().
SDL_DestroyAudioStream()
SDL_DECLSPEC void SDLCALL SDL_DestroyAudioStream (SDL_AudioStream * stream) extern
Free an audio stream.
This will release all allocated data, including any audio that is still queued. You do not need to manually clear the stream first.
If this stream was bound to an audio device, it is unbound during this call. If this stream was created with SDL_OpenAudioDeviceStream, the audio device that was opened alongside this stream's creation will be closed, too.
Parameters
stream the audio stream to destroy.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateAudioStream
{
    if (!stream) {
        return;
    }
    SDL_DestroyProperties(stream->props);
    OnAudioStreamDestroy(stream);
    const bool simplified = stream->simplified;
    if (simplified) {
        if (stream->bound_device) {
            SDL_assert(stream->bound_device->simplified);
            SDL_CloseAudioDevice(stream->bound_device->instance_id);  // this will unbind the stream.
        }
    } else {
        SDL_UnbindAudioStream(stream);
    }
    SDL_aligned_free(stream->work_buffer);
    SDL_DestroyAudioQueue(stream->queue);
    SDL_DestroyMutex(stream->lock);
    SDL_free(stream);
}
References OnAudioStreamDestroy(), SDL_aligned_free(), SDL_assert, SDL_CloseAudioDevice(), SDL_DestroyAudioQueue(), SDL_DestroyMutex(), SDL_DestroyProperties(), SDL_free(), and SDL_UnbindAudioStream().
Referenced by SDL_ConvertAudioSamples(), SDL_CreateAudioStream(), SDL_OpenAudioDeviceStream(), and SDL_QuitAudio().
SDL_FlushAudioStream()
SDL_DECLSPEC bool SDLCALL SDL_FlushAudioStream (SDL_AudioStream * stream) extern
Tell the stream that you're done sending data, and anything being buffered should be converted/resampled and made available immediately.
It is legal to add more data to a stream after flushing, but there may be audio gaps in the output. Generally this is intended to signal the end of input, so the complete output becomes available.
Parameters
stream the audio stream to flush.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PutAudioStreamData
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    SDL_FlushAudioQueue(stream->queue);
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_FlushAudioQueue(), SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_ConvertAudioSamples().
SDL_GetAudioDeviceChannelMap()
SDL_DECLSPEC int *SDLCALL SDL_GetAudioDeviceChannelMap (SDL_AudioDeviceID devid, int * count) extern
Get the current channel map of an audio device.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
Audio devices usually have no remapping applied. This is represented by returning NULL, and does not signify an error.
Parameters
devid the instance ID of the device to query.
count On output, set to number of channels in the map. Can be NULL.
Returns
an array of the current channel mapping, with as many elements as the current output spec's channels, or NULL if default. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    int *result = NULL;
    int channels = 0;
    SDL_AudioDevice *device = ObtainPhysicalAudioDeviceDefaultAllowed(devid);
    if (device) {
        channels = device->spec.channels;
        if (channels > 0 && device->chmap) {
            result = SDL_ChannelMapDup(device->chmap, channels);
        }
    }
    ReleaseAudioDevice(device);
    if (count) {
        *count = channels;
    }
    return result;
}
References SDL_AudioSpec::channels, SDL_AudioDevice::chmap, count, NULL, ObtainPhysicalAudioDeviceDefaultAllowed(), ReleaseAudioDevice(), SDL_ChannelMapDup(), and SDL_AudioDevice::spec.
SDL_GetAudioDeviceFormat()
SDL_DECLSPEC bool SDLCALL SDL_GetAudioDeviceFormat (SDL_AudioDeviceID devid, SDL_AudioSpec * spec, int * sample_frames) extern
Get the current audio format of a specific audio device.
For an opened device, this will report the format the device is currently using. If the device isn't yet opened, this will report the device's preferred format (or a reasonable default if this can't be determined).
You may also specify SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING here, which is useful for getting a reasonable recommendation before opening the system-recommended default device.
You can also use this to request the current device buffer size. This is specified in sample frames and represents the amount of data SDL will feed to the physical hardware in each chunk. This can be converted to milliseconds of audio with the following equation:
ms = (int) ((((Sint64) frames) * 1000) / spec.freq);
Buffer size is only important if you need low-level control over the audio playback timing. Most apps do not need this.
Parameters
devid the instance ID of the device to query.
spec on return, will be filled with device details.
sample_frames pointer to store device buffer size, in sample frames. Can be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!spec) {
        return SDL_InvalidParamError("spec");
    }
    bool result = false;
    SDL_AudioDevice *device = ObtainPhysicalAudioDeviceDefaultAllowed(devid);
    if (device) {
        SDL_copyp(spec, &device->spec);
        if (sample_frames) {
            *sample_frames = device->sample_frames;
        }
        result = true;
    }
    ReleaseAudioDevice(device);
    return result;
}
References ObtainPhysicalAudioDeviceDefaultAllowed(), ReleaseAudioDevice(), SDL_AudioDevice::sample_frames, SDL_copyp, SDL_InvalidParamError, and SDL_AudioDevice::spec.
SDL_GetAudioDeviceGain()
SDL_DECLSPEC float SDLCALL SDL_GetAudioDeviceGain (SDL_AudioDeviceID devid) extern
Get the gain of an audio device.
The gain of a device is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio devices default to a gain of 1.0f (no change in output).
Physical devices may not have their gain changed, only logical devices, and this function will always return -1.0f when used on physical devices.
Parameters
devid the audio device to query.
Returns
the gain of the device or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioDeviceGain
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    const float result = logdev ? logdev->gain : -1.0f;
    ReleaseAudioDevice(device);
    return result;
}
References SDL_LogicalAudioDevice::gain, NULL, ObtainLogicalAudioDevice(), and ReleaseAudioDevice().
SDL_GetAudioDeviceName()
SDL_DECLSPEC const char *SDLCALL SDL_GetAudioDeviceName (SDL_AudioDeviceID devid) extern
Get the human-readable name of a specific audio device.
Parameters
devid the instance ID of the device to query.
Returns
the name of the audio device, or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioPlaybackDevices
SDL_GetAudioRecordingDevices
{
    // bit #1 of devid is set for physical devices and unset for logical.
    const bool islogical = !(devid & (1<<1));
    const char *result = NULL;
    const void *vdev = NULL;
    if (!SDL_GetCurrentAudioDriver()) {
        SDL_SetError("Audio subsystem is not initialized");
    } else {
        // This does not call ObtainPhysicalAudioDevice() because the device's name never changes, so
        // it doesn't have to lock the whole device. However, just to make sure the device pointer itself
        // remains valid (in case the device is unplugged at the wrong moment), we hold the
        // device_hash_lock while we copy the string.
        SDL_LockRWLockForReading(current_audio.device_hash_lock);
        SDL_FindInHashTable(current_audio.device_hash, (const void *) (uintptr_t) devid, &vdev);
        if (!vdev) {
            SDL_SetError("Invalid audio device instance ID");
        } else if (islogical) {
            const SDL_LogicalAudioDevice *logdev = (const SDL_LogicalAudioDevice *) vdev;
            SDL_assert(logdev->instance_id == devid);
            result = SDL_GetPersistentString(logdev->physical_device->name);
        } else {
            const SDL_AudioDevice *device = (const SDL_AudioDevice *) vdev;
            SDL_assert(device->instance_id == devid);
            result = SDL_GetPersistentString(device->name);
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
    return result;
}
References current_audio, SDL_AudioDevice::instance_id, SDL_LogicalAudioDevice::instance_id, SDL_AudioDevice::name, NULL, SDL_LogicalAudioDevice::physical_device, SDL_assert, SDL_FindInHashTable(), SDL_GetCurrentAudioDriver(), SDL_GetPersistentString(), SDL_LockRWLockForReading(), SDL_SetError(), and SDL_UnlockRWLock().
SDL_GetAudioDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetAudioDriver (int index) extern
Use this function to get the name of a built in audio driver.
The list of audio drivers is given in the order that they are normally initialized by default; the drivers that seem more reasonable to choose first (as far as the SDL developers believe) are earlier in the list.
The names of drivers are all simple, low-ASCII identifiers, like "alsa", "coreaudio" or "wasapi". These never have Unicode characters, and are not meant to be proper names.
Parameters
index the index of the audio driver; the value ranges from 0 to SDL_GetNumAudioDrivers() - 1.
Returns
the name of the audio driver at the requested index, or NULL if an invalid index was specified.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumAudioDrivers
{
    if (index >= 0 && index < SDL_GetNumAudioDrivers()) {
        return deduped_bootstrap[index]->name;
    }
    SDL_InvalidParamError("index");
    return NULL;
}
References deduped_bootstrap, NULL, SDL_GetNumAudioDrivers(), and SDL_InvalidParamError.
SDL_GetAudioFormatName()
SDL_DECLSPEC const char *SDLCALL SDL_GetAudioFormatName (SDL_AudioFormat format) extern
Get the human readable name of an audio format.
Parameters
format the audio format to query.
Returns
the human readable name of the specified audio format or "SDL_AUDIO_UNKNOWN" if the format isn't recognized.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    switch (format) {
#define CASE(X) \
    case X: return #X;
    CASE(SDL_AUDIO_U8)
    CASE(SDL_AUDIO_S8)
    CASE(SDL_AUDIO_S16LE)
    CASE(SDL_AUDIO_S16BE)
    CASE(SDL_AUDIO_S32LE)
    CASE(SDL_AUDIO_S32BE)
    CASE(SDL_AUDIO_F32LE)
    CASE(SDL_AUDIO_F32BE)
#undef CASE
    default:
        return "SDL_AUDIO_UNKNOWN";
    }
}
References CASE, SDL_AUDIO_F32BE, SDL_AUDIO_F32LE, SDL_AUDIO_S16BE, SDL_AUDIO_S16LE, SDL_AUDIO_S32BE, SDL_AUDIO_S32LE, SDL_AUDIO_S8, and SDL_AUDIO_U8.
SDL_GetAudioPlaybackDevices()
SDL_DECLSPEC SDL_AudioDeviceID *SDLCALL SDL_GetAudioPlaybackDevices (int * count) extern
Get a list of currently-connected audio playback devices.
This returns of list of available devices that play sound, perhaps to speakers or headphones ("playback" devices). If you want devices that record audio, like a microphone ("recording" devices), use SDL_GetAudioRecordingDevices() instead.
This only returns a list of physical devices; it will not have any device IDs returned by SDL_OpenAudioDevice().
If this function returns NULL, to signify an error, *count will be set to zero.
Parameters
count a pointer filled in with the number of devices returned, may be NULL.
Returns
a 0 terminated array of device instance IDs or NULL on error; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenAudioDevice
SDL_GetAudioRecordingDevices
{
    return GetAudioDevices(count, false);
}
References count, and GetAudioDevices().
SDL_GetAudioRecordingDevices()
SDL_DECLSPEC SDL_AudioDeviceID *SDLCALL SDL_GetAudioRecordingDevices (int * count) extern
Get a list of currently-connected audio recording devices.
This returns of list of available devices that record audio, like a microphone ("recording" devices). If you want devices that play sound, perhaps to speakers or headphones ("playback" devices), use SDL_GetAudioPlaybackDevices() instead.
This only returns a list of physical devices; it will not have any device IDs returned by SDL_OpenAudioDevice().
If this function returns NULL, to signify an error, *count will be set to zero.
Parameters
count a pointer filled in with the number of devices returned, may be NULL.
Returns
a 0 terminated array of device instance IDs, or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenAudioDevice
SDL_GetAudioPlaybackDevices
{
    return GetAudioDevices(count, true);
}
References count, and GetAudioDevices().
SDL_GetAudioStreamAvailable()
SDL_DECLSPEC int SDLCALL SDL_GetAudioStreamAvailable (SDL_AudioStream * stream) extern
Get the number of converted/resampled bytes available.
The stream may be buffering data behind the scenes until it has enough to resample correctly, so this number might be lower than what you expect, or even be zero. Add more data or flush the stream if you need the data now.
If the stream has so much data that it would overflow an int, the return value is clamped to a maximum value, but no queued data is lost; if there are gigabytes of data queued, the app might need to read some of it with SDL_GetAudioStreamData before this function's return value is no longer clamped.
Parameters
stream the audio stream to query.
Returns
the number of converted/resampled bytes available or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamData
SDL_PutAudioStreamData
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1;
    }
    SDL_LockMutex(stream->lock);
    if (!CheckAudioStreamIsFullySetup(stream)) {
        SDL_UnlockMutex(stream->lock);
        return 0;
    }
    Sint64 count = GetAudioStreamAvailableFrames(stream, NULL);
    // convert from sample frames to bytes in destination format.
    count *= SDL_AUDIO_FRAMESIZE(stream->dst_spec);
    SDL_UnlockMutex(stream->lock);
    // if this overflows an int, just clamp it to a maximum.
    return (int) SDL_min(count, SDL_INT_MAX);
}
References CheckAudioStreamIsFullySetup(), count, GetAudioStreamAvailableFrames(), NULL, SDL_AUDIO_FRAMESIZE, SDL_INT_MAX, SDL_InvalidParamError, SDL_LockMutex(), SDL_min, and SDL_UnlockMutex().
Referenced by PutAudioStreamBufferInternal(), and SDL_ConvertAudioSamples().
SDL_GetAudioStreamData()
SDL_DECLSPEC int SDLCALL SDL_GetAudioStreamData (SDL_AudioStream * stream, void * buf, int len) extern
Get converted/resampled data from the stream.
The input/output data format/channels/samplerate is specified when creating the stream, and can be changed after creation by calling SDL_SetAudioStreamFormat.
Note that any conversion and resampling necessary is done during this call, and SDL_PutAudioStreamData simply queues unconverted data for later. This is different than SDL2, where that work was done while inputting new data to the stream and requesting the output just copied the converted data.
Parameters
stream the stream the audio is being requested from.
buf a buffer to fill with audio data.
len the maximum number of bytes to fill.
Returns
the number of bytes read from the stream or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearAudioStream
SDL_GetAudioStreamAvailable
SDL_PutAudioStreamData
{
    return SDL_GetAudioStreamDataAdjustGain(stream, voidbuf, len, 1.0f);
}
References SDL_GetAudioStreamDataAdjustGain().
Referenced by SDL_ConvertAudioSamples().
SDL_GetAudioStreamDevice()
SDL_DECLSPEC SDL_AudioDeviceID SDLCALL SDL_GetAudioStreamDevice (SDL_AudioStream * stream) extern
Query an audio stream for its currently-bound device.
This reports the logical audio device that an audio stream is currently bound to.
If not bound, or invalid, this returns zero, which is not a valid device ID.
Parameters
stream the audio stream to query.
Returns
the bound audio device, or 0 if not bound or invalid.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStream
SDL_BindAudioStreams
{
    SDL_AudioDeviceID result = 0;
    if (!stream) {
        SDL_InvalidParamError("stream");
        return 0;
    }
    SDL_LockMutex(stream->lock);
    if (stream->bound_device) {
        result = stream->bound_device->instance_id;
    } else {
        SDL_SetError("Audio stream not bound to an audio device");
    }
    SDL_UnlockMutex(stream->lock);
    return result;
}
References SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), and SDL_UnlockMutex().
Referenced by SDL_AudioStreamDevicePaused(), SDL_PauseAudioStreamDevice(), and SDL_ResumeAudioStreamDevice().
SDL_GetAudioStreamFormat()
SDL_DECLSPEC bool SDLCALL SDL_GetAudioStreamFormat (SDL_AudioStream * stream, SDL_AudioSpec * src_spec, SDL_AudioSpec * dst_spec) extern
Query the current format of an audio stream.
Parameters
stream the SDL_AudioStream to query.
src_spec where to store the input audio format; ignored if NULL.
dst_spec where to store the output audio format; ignored if NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamFormat
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    if (src_spec) {
        SDL_copyp(src_spec, &stream->src_spec);
    }
    if (dst_spec) {
        SDL_copyp(dst_spec, &stream->dst_spec);
    }
    SDL_UnlockMutex(stream->lock);
    if (src_spec && src_spec->format == 0) {
        return SDL_SetError("Stream has no source format");
    } else if (dst_spec && dst_spec->format == 0) {
        return SDL_SetError("Stream has no destination format");
    }
    return true;
}
References SDL_AudioSpec::format, SDL_copyp, SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), and SDL_UnlockMutex().
SDL_GetAudioStreamFrequencyRatio()
SDL_DECLSPEC float SDLCALL SDL_GetAudioStreamFrequencyRatio (SDL_AudioStream * stream) extern
Get the frequency ratio of an audio stream.
Parameters
stream the SDL_AudioStream to query.
Returns
the frequency ratio of the stream or 0.0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamFrequencyRatio
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return 0.0f;
    }
    SDL_LockMutex(stream->lock);
    const float freq_ratio = stream->freq_ratio;
    SDL_UnlockMutex(stream->lock);
    return freq_ratio;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamGain()
SDL_DECLSPEC float SDLCALL SDL_GetAudioStreamGain (SDL_AudioStream * stream) extern
Get the gain of an audio stream.
The gain of a stream is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio streams default to a gain of 1.0f (no change in output).
Parameters
stream the SDL_AudioStream to query.
Returns
the gain of the stream or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamGain
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1.0f;
    }
    SDL_LockMutex(stream->lock);
    const float gain = stream->gain;
    SDL_UnlockMutex(stream->lock);
    return gain;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamInputChannelMap()
SDL_DECLSPEC int *SDLCALL SDL_GetAudioStreamInputChannelMap (SDL_AudioStream * stream, int * count) extern
Get the current input channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
Audio streams default to no remapping applied. This is represented by returning NULL, and does not signify an error.
Parameters
stream the SDL_AudioStream to query.
count On output, set to number of channels in the map. Can be NULL.
Returns
an array of the current channel mapping, with as many elements as the current output spec's channels, or NULL if default. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    int *result = NULL;
    int channels = 0;
    if (stream) {
        SDL_LockMutex(stream->lock);
        channels = stream->src_spec.channels;
        result = SDL_ChannelMapDup(stream->src_chmap, channels);
        SDL_UnlockMutex(stream->lock);
    }
    if (count) {
        *count = channels;
    }
    return result;
}
References count, NULL, SDL_ChannelMapDup(), SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamOutputChannelMap()
SDL_DECLSPEC int *SDLCALL SDL_GetAudioStreamOutputChannelMap (SDL_AudioStream * stream, int * count) extern
Get the current output channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
Audio streams default to no remapping applied. This is represented by returning NULL, and does not signify an error.
Parameters
stream the SDL_AudioStream to query.
count On output, set to number of channels in the map. Can be NULL.
Returns
an array of the current channel mapping, with as many elements as the current output spec's channels, or NULL if default. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    int *result = NULL;
    int channels = 0;
    if (stream) {
        SDL_LockMutex(stream->lock);
        channels = stream->dst_spec.channels;
        result = SDL_ChannelMapDup(stream->dst_chmap, channels);
        SDL_UnlockMutex(stream->lock);
    }
    if (count) {
        *count = channels;
    }
    return result;
}
References count, NULL, SDL_ChannelMapDup(), SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetAudioStreamProperties (SDL_AudioStream * stream) extern
Get the properties associated with an audio stream.
The application can hang any data it wants here, but the following properties are understood by SDL:
SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN: if true (the default), the stream be automatically cleaned up when the audio subsystem quits. If set to false, the streams will persist beyond that. This property is ignored for streams created through SDL_OpenAudioDeviceStream(), and will always be cleaned up. Streams that are not cleaned up will still be unbound from devices when the audio subsystem quits. This property was added in SDL 3.4.0.
Parameters
stream the SDL_AudioStream to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return 0;
    }
    SDL_LockMutex(stream->lock);
    if (stream->props == 0) {
        stream->props = SDL_CreateProperties();
    }
    SDL_UnlockMutex(stream->lock);
    return stream->props;
}
References SDL_CreateProperties(), SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamQueued()
SDL_DECLSPEC int SDLCALL SDL_GetAudioStreamQueued (SDL_AudioStream * stream) extern
Get the number of bytes currently queued.
This is the number of bytes put into a stream as input, not the number that can be retrieved as output. Because of several details, it's not possible to calculate one number directly from the other. If you need to know how much usable data can be retrieved right now, you should use SDL_GetAudioStreamAvailable() and not this function.
Note that audio streams can change their input format at any time, even if there is still data queued in a different format, so the returned byte count will not necessarily match the number of sample frames available. Users of this API should be aware of format changes they make when feeding a stream and plan accordingly.
Queued data is not converted until it is consumed by SDL_GetAudioStreamData, so this value should be representative of the exact data that was put into the stream.
If the stream has so much data that it would overflow an int, the return value is clamped to a maximum value, but no queued data is lost; if there are gigabytes of data queued, the app might need to read some of it with SDL_GetAudioStreamData before this function's return value is no longer clamped.
Parameters
stream the audio stream to query.
Returns
the number of bytes queued or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PutAudioStreamData
SDL_ClearAudioStream
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1;
    }
    SDL_LockMutex(stream->lock);
    size_t total = SDL_GetAudioQueueQueued(stream->queue);
    SDL_UnlockMutex(stream->lock);
    // if this overflows an int, just clamp it to a maximum.
    return (int) SDL_min(total, SDL_INT_MAX);
}
References SDL_GetAudioQueueQueued(), SDL_INT_MAX, SDL_InvalidParamError, SDL_LockMutex(), SDL_min, and SDL_UnlockMutex().
SDL_GetCurrentAudioDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetCurrentAudioDriver (void) extern
Get the name of the current audio driver.
The names of drivers are all simple, low-ASCII identifiers, like "alsa", "coreaudio" or "wasapi". These never have Unicode characters, and are not meant to be proper names.
Returns
the name of the current audio driver or NULL if no driver has been initialized.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return current_audio.name;
}
References current_audio.
Referenced by GetAudioDevices(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_GetAudioDeviceName(), SDL_InitAudio(), and SDL_OpenAudioDevice().
SDL_GetNumAudioDrivers()
SDL_DECLSPEC int SDLCALL SDL_GetNumAudioDrivers (void) extern
Use this function to get the number of built-in audio drivers.
This function returns a hardcoded number. This never returns a negative value; if there are no drivers compiled into this build of SDL, this function returns zero. The presence of a driver in this list does not mean it will function, it just means SDL is capable of interacting with that interface. For example, a build of SDL might have esound support, but if there's no esound server available, SDL's esound driver would fail if used.
By default, SDL tries all drivers, in its preferred order, until one is found to be usable.
Returns
the number of built-in audio drivers.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioDriver
{
    static int num_drivers = -1;
    if (num_drivers >= 0) {
        return num_drivers;
    }
    num_drivers = 0;
    // Build a list of unique audio drivers.
    for (int i = 0; bootstrap[i] != NULL; ++i) {
        bool duplicate = false;
        for (int j = 0; j < i; ++j) {
            if (SDL_strcmp(bootstrap[i]->name, bootstrap[j]->name) == 0) {
                duplicate = true;
                break;
            }
        }
        if (!duplicate) {
            deduped_bootstrap[num_drivers++] = bootstrap[i];
        }
    }
    return num_drivers;
}
References bootstrap, deduped_bootstrap, NULL, and SDL_strcmp().
Referenced by SDL_GetAudioDriver().
SDL_GetSilenceValueForFormat()
SDL_DECLSPEC int SDLCALL SDL_GetSilenceValueForFormat (SDL_AudioFormat format) extern
Get the appropriate memset value for silencing an audio format.
The value returned by this function can be used as the second argument to memset (or SDL_memset) to set an audio buffer in a specific format to silence.
Parameters
format the audio data format to query.
Returns
a byte value that can be passed to memset.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (format == SDL_AUDIO_U8) ? 0x80 : 0x00;
}
References SDL_AUDIO_U8.
Referenced by ClosePhysicalAudioDevice(), CreatePhysicalAudioDevice(), InterleaveAudioChannels(), PeekIntoAudioQueueFuture(), SDL_ResetAudioQueueHistory(), and SDL_UpdatedAudioDeviceFormat().
SDL_IsAudioDevicePhysical()
SDL_DECLSPEC bool SDLCALL SDL_IsAudioDevicePhysical (SDL_AudioDeviceID devid) extern
Determine if an audio device is physical (instead of logical).
An SDL_AudioDeviceID that represents physical hardware is a physical device; there is one for each piece of hardware that SDL can see. Logical devices are created by calling SDL_OpenAudioDevice or SDL_OpenAudioDeviceStream, and while each is associated with a physical device, there can be any number of logical devices on one physical device.
For the most part, logical and physical IDs are interchangeable–if you try to open a logical device, SDL understands to assign that effort to the underlying physical device, etc. However, it might be useful to know if an arbitrary device ID is physical or logical. This function reports which.
This function may return either true or false for invalid device IDs.
Parameters
devid the device ID to query.
Returns
true if devid is a physical device, false if it is logical.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (devid & (1 << 1)) != 0;
}
SDL_IsAudioDevicePlayback()
SDL_DECLSPEC bool SDLCALL SDL_IsAudioDevicePlayback (SDL_AudioDeviceID devid) extern
Determine if an audio device is a playback device (instead of recording).
This function may return either true or false for invalid device IDs.
Parameters
devid the device ID to query.
Returns
true if devid is a playback device, false if it is recording.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (devid & (1 << 0)) != 0;
}
SDL_LoadWAV()
SDL_DECLSPEC bool SDLCALL SDL_LoadWAV (const char * path, SDL_AudioSpec * spec, Uint8 ** audio_buf, Uint32 * audio_len) extern
Loads a WAV from a file path.
This is a convenience function that is effectively the same as:
SDL_LoadWAV_IO(SDL_IOFromFile(path, "rb"), true, spec, audio_buf, audio_len);
Parameters
path the file path of the WAV file to open.
spec a pointer to an SDL_AudioSpec that will be set to the WAVE data's format details on successful return.
audio_buf a pointer filled with the audio data, allocated by the function.
audio_len a pointer filled with the length of the audio data buffer in bytes.
Returns
true on success. audio_buf will be filled with a pointer to an allocated buffer containing the audio data, and audio_len is filled with the length of that audio buffer in bytes.
This function returns false if the .WAV file cannot be opened, uses an unknown data format, or is corrupt; call SDL_GetError() for more information.
When the application is done with the data returned in audio_buf, it should call SDL_free() to dispose of it.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_free
SDL_LoadWAV_IO
{
    SDL_IOStream *stream = SDL_IOFromFile(path, "rb");
    if (!stream) {
        if (spec) {
            SDL_zerop(spec);
        }
        if (audio_buf) {
            *audio_buf = NULL;
        }
        if (audio_len) {
            *audio_len = 0;
        }
        return false;
    }
    return SDL_LoadWAV_IO(stream, true, spec, audio_buf, audio_len);
}
References NULL, SDL_IOFromFile(), SDL_LoadWAV_IO(), and SDL_zerop.
SDL_LoadWAV_IO()
SDL_DECLSPEC bool SDLCALL SDL_LoadWAV_IO (SDL_IOStream * src, bool closeio, SDL_AudioSpec * spec, Uint8 ** audio_buf, Uint32 * audio_len) extern
Load the audio data of a WAVE file into memory.
Loading a WAVE file requires src, spec, audio_buf and audio_len to be valid pointers. The entire data portion of the file is then loaded into memory and decoded if necessary.
Supported formats are RIFF WAVE files with the formats PCM (8, 16, 24, and 32 bits), IEEE Float (32 bits), Microsoft ADPCM and IMA ADPCM (4 bits), and A-law and mu-law (8 bits). Other formats are currently unsupported and cause an error.
If this function succeeds, the return value is zero and the pointer to the audio data allocated by the function is written to audio_buf and its length in bytes to audio_len. The SDL_AudioSpec members freq, channels, and format are set to the values of the audio data in the buffer.
It's necessary to use SDL_free() to free the audio data returned in audio_buf when it is no longer used.
Because of the underspecification of the .WAV format, there are many problematic files in the wild that cause issues with strict decoders. To provide compatibility with these files, this decoder is lenient in regards to the truncation of the file, the fact chunk, and the size of the RIFF chunk. The hints SDL_HINT_WAVE_RIFF_CHUNK_SIZE, SDL_HINT_WAVE_TRUNCATION, and SDL_HINT_WAVE_FACT_CHUNK can be used to tune the behavior of the loading process.
Any file that is invalid (due to truncation, corruption, or wrong values in the headers), too big, or unsupported causes an error. Additionally, any critical I/O error from the data source will terminate the loading process with an error. The function returns NULL on error and in all cases (with the exception of src being NULL), an appropriate error message will be set.
It is required that the data source supports seeking.
Example:
SDL_LoadWAV_IO(SDL_IOFromFile("sample.wav", "rb"), true, &spec, &buf, &len);
Note that the SDL_LoadWAV function does this same thing for you, but in a less messy way:
SDL_LoadWAV("sample.wav", &spec, &buf, &len);
Parameters
src the data source for the WAVE data.
closeio if true, calls SDL_CloseIO() on src before returning, even in the case of an error.
spec a pointer to an SDL_AudioSpec that will be set to the WAVE data's format details on successful return.
audio_buf a pointer filled with the audio data, allocated by the function.
audio_len a pointer filled with the length of the audio data buffer in bytes.
Returns
true on success. audio_buf will be filled with a pointer to an allocated buffer containing the audio data, and audio_len is filled with the length of that audio buffer in bytes.
This function returns false if the .WAV file cannot be opened, uses an unknown data format, or is corrupt; call SDL_GetError() for more information.
When the application is done with the data returned in audio_buf, it should call SDL_free() to dispose of it.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_free
SDL_LoadWAV
{
    bool result = false;
    WaveFile file;
    if (spec) {
        SDL_zerop(spec);
    }
    if (audio_buf) {
        *audio_buf = NULL;
    }
    if (audio_len) {
        *audio_len = 0;
    }
    // Make sure we are passed a valid data source
    if (!src) {
        SDL_InvalidParamError("src");
        goto done;
    } else if (!spec) {
        SDL_InvalidParamError("spec");
        goto done;
    } else if (!audio_buf) {
        SDL_InvalidParamError("audio_buf");
        goto done;
    } else if (!audio_len) {
        SDL_InvalidParamError("audio_len");
        goto done;
    }
    SDL_zero(file);
    file.riffhint = WaveGetRiffSizeHint();
    file.trunchint = WaveGetTruncationHint();
    file.facthint = WaveGetFactChunkHint();
    result = WaveLoad(src, &file, spec, audio_buf, audio_len);
    if (!result) {
        SDL_free(*audio_buf);
        audio_buf = NULL;
        audio_len = 0;
    }
    // Cleanup
    if (!closeio) {
        SDL_SeekIO(src, file.chunk.position, SDL_IO_SEEK_SET);
    }
    WaveFreeChunkData(&file.chunk);
    SDL_free(file.decoderdata);
done:
    if (closeio && src) {
        SDL_CloseIO(src);
    }
    return result;
}
References WaveFile::chunk, WaveFile::decoderdata, WaveFile::facthint, NULL, WaveChunk::position, WaveFile::riffhint, SDL_CloseIO(), SDL_free(), SDL_InvalidParamError, SDL_IO_SEEK_SET, SDL_SeekIO(), SDL_zero, SDL_zerop, WaveFile::trunchint, WaveFreeChunkData(), WaveGetFactChunkHint(), WaveGetRiffSizeHint(), WaveGetTruncationHint(), and WaveLoad().
Referenced by SDL_LoadWAV().
SDL_LockAudioStream()
SDL_DECLSPEC bool SDLCALL SDL_LockAudioStream (SDL_AudioStream * stream) extern
Lock an audio stream for serialized access.
Each SDL_AudioStream has an internal mutex it uses to protect its data structures from threading conflicts. This function allows an app to lock that mutex, which could be useful if registering callbacks on this stream.
One does not need to lock a stream to use in it most cases, as the stream manages this lock internally. However, this lock is held during callbacks, which may run from arbitrary threads at any time, so if an app needs to protect shared data during those callbacks, locking the stream guarantees that the callback is not running while the lock is held.
As this is just a wrapper over SDL_LockMutex for an internal lock; it has all the same attributes (recursive locks are allowed, etc).
Parameters
stream the audio stream to lock.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_UnlockAudioStream
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, and SDL_LockMutex().
SDL_MixAudio()
SDL_DECLSPEC bool SDLCALL SDL_MixAudio (Uint8 * dst, const Uint8 * src, SDL_AudioFormat format, Uint32 len, float volume) extern
Mix audio data in a specified format.
This takes an audio buffer src of len bytes of format data and mixes it into dst, performing addition, volume adjustment, and overflow clipping. The buffer pointed to by dst must also be len bytes of format data.
This is provided for convenience – you can mix your own audio data.
Do not use this function for mixing together more than two streams of sample data. The output from repeated application of this function may be distorted by clipping, because there is no accumulator with greater range than the input (not to mention this being an inefficient way of doing it).
It is a common misconception that this function is required to write audio data to an output stream in an audio callback. While you can do that, SDL_MixAudio() is really only needed when you're mixing a single audio stream with a volume adjustment.
Parameters
dst the destination for the mixed audio.
src the source audio buffer to be mixed.
format the SDL_AudioFormat structure representing the desired audio format.
len the length of the audio buffer in bytes.
volume ranges from 0.0 - 1.0, and should be set to 1.0 for full audio volume.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    int volume = (int)SDL_roundf(fvolume * MIX_MAXVOLUME);
    if (volume == 0) {
        return true;
    }
    switch (format) {
    case SDL_AUDIO_U8:
    {
        Uint8 src_sample;
        while (len--) {
            src_sample = *src;
            ADJUST_VOLUME_U8(src_sample, volume);
            *dst = mix8[*dst + src_sample];
            ++dst;
            ++src;
        }
    } break;
    case SDL_AUDIO_S8:
    {
        Sint8 *dst8, *src8;
        Sint8 src_sample;
        int dst_sample;
        const int max_audioval = SDL_MAX_SINT8;
        const int min_audioval = SDL_MIN_SINT8;
        src8 = (Sint8 *)src;
        dst8 = (Sint8 *)dst;
        while (len--) {
            src_sample = *src8;
            ADJUST_VOLUME(Sint8, src_sample, volume);
            dst_sample = *dst8 + src_sample;
            if (dst_sample > max_audioval) {
                dst_sample = max_audioval;
            } else if (dst_sample < min_audioval) {
                dst_sample = min_audioval;
            }
            *dst8 = (Sint8)dst_sample;
            ++dst8;
            ++src8;
        }
    } break;
    case SDL_AUDIO_S16LE:
    {
        Sint16 src1, src2;
        int dst_sample;
        const int max_audioval = SDL_MAX_SINT16;
        const int min_audioval = SDL_MIN_SINT16;
        len /= 2;
        while (len--) {
            src1 = SDL_Swap16LE(*(Sint16 *)src);
            ADJUST_VOLUME(Sint16, src1, volume);
            src2 = SDL_Swap16LE(*(Sint16 *)dst);
            src += 2;
            dst_sample = src1 + src2;
            if (dst_sample > max_audioval) {
                dst_sample = max_audioval;
            } else if (dst_sample < min_audioval) {
                dst_sample = min_audioval;
            }
            *(Sint16 *)dst = SDL_Swap16LE((Sint16)dst_sample);
            dst += 2;
        }
    } break;
    case SDL_AUDIO_S16BE:
    {
        Sint16 src1, src2;
        int dst_sample;
        const int max_audioval = SDL_MAX_SINT16;
        const int min_audioval = SDL_MIN_SINT16;
        len /= 2;
        while (len--) {
            src1 = SDL_Swap16BE(*(Sint16 *)src);
            ADJUST_VOLUME(Sint16, src1, volume);
            src2 = SDL_Swap16BE(*(Sint16 *)dst);
            src += 2;
            dst_sample = src1 + src2;
            if (dst_sample > max_audioval) {
                dst_sample = max_audioval;
            } else if (dst_sample < min_audioval) {
                dst_sample = min_audioval;
            }
            *(Sint16 *)dst = SDL_Swap16BE((Sint16)dst_sample);
            dst += 2;
        }
    } break;
    case SDL_AUDIO_S32LE:
    {
        const Uint32 *src32 = (Uint32 *)src;
        Uint32 *dst32 = (Uint32 *)dst;
        Sint64 src1, src2;
        Sint64 dst_sample;
        const Sint64 max_audioval = SDL_MAX_SINT32;
        const Sint64 min_audioval = SDL_MIN_SINT32;
        len /= 4;
        while (len--) {
            src1 = (Sint64)((Sint32)SDL_Swap32LE(*src32));
            src32++;
            ADJUST_VOLUME(Sint64, src1, volume);
            src2 = (Sint64)((Sint32)SDL_Swap32LE(*dst32));
            dst_sample = src1 + src2;
            if (dst_sample > max_audioval) {
                dst_sample = max_audioval;
            } else if (dst_sample < min_audioval) {
                dst_sample = min_audioval;
            }
            *(dst32++) = SDL_Swap32LE((Uint32)((Sint32)dst_sample));
        }
    } break;
    case SDL_AUDIO_S32BE:
    {
        const Uint32 *src32 = (Uint32 *)src;
        Uint32 *dst32 = (Uint32 *)dst;
        Sint64 src1, src2;
        Sint64 dst_sample;
        const Sint64 max_audioval = SDL_MAX_SINT32;
        const Sint64 min_audioval = SDL_MIN_SINT32;
        len /= 4;
        while (len--) {
            src1 = (Sint64)((Sint32)SDL_Swap32BE(*src32));
            src32++;
            ADJUST_VOLUME(Sint64, src1, volume);
            src2 = (Sint64)((Sint32)SDL_Swap32BE(*dst32));
            dst_sample = src1 + src2;
            if (dst_sample > max_audioval) {
                dst_sample = max_audioval;
            } else if (dst_sample < min_audioval) {
                dst_sample = min_audioval;
            }
            *(dst32++) = SDL_Swap32BE((Uint32)((Sint32)dst_sample));
        }
    } break;
    case SDL_AUDIO_F32LE:
    {
        const float *src32 = (float *)src;
        float *dst32 = (float *)dst;
        float src1, src2;
        float dst_sample;
        const float max_audioval = 1.0f;
        const float min_audioval = -1.0f;
        len /= 4;
        while (len--) {
            src1 = SDL_SwapFloatLE(*src32) * fvolume;
            src2 = SDL_SwapFloatLE(*dst32);
            src32++;
            dst_sample = src1 + src2;
            if (dst_sample > max_audioval) {
                dst_sample = max_audioval;
            } else if (dst_sample < min_audioval) {
                dst_sample = min_audioval;
            }
            *(dst32++) = SDL_SwapFloatLE(dst_sample);
        }
    } break;
    case SDL_AUDIO_F32BE:
    {
        const float *src32 = (float *)src;
        float *dst32 = (float *)dst;
        float src1, src2;
        float dst_sample;
        const float max_audioval = 1.0f;
        const float min_audioval = -1.0f;
        len /= 4;
        while (len--) {
            src1 = SDL_SwapFloatBE(*src32) * fvolume;
            src2 = SDL_SwapFloatBE(*dst32);
            src32++;
            dst_sample = src1 + src2;
            if (dst_sample > max_audioval) {
                dst_sample = max_audioval;
            } else if (dst_sample < min_audioval) {
                dst_sample = min_audioval;
            }
            *(dst32++) = SDL_SwapFloatBE(dst_sample);
        }
    } break;
    default: // If this happens... FIXME!
        return SDL_SetError("SDL_MixAudio(): unknown audio format");
    }
    return true;
}
References ADJUST_VOLUME, ADJUST_VOLUME_U8, mix8, MIX_MAXVOLUME, SDL_AUDIO_F32BE, SDL_AUDIO_F32LE, SDL_AUDIO_S16BE, SDL_AUDIO_S16LE, SDL_AUDIO_S32BE, SDL_AUDIO_S32LE, SDL_AUDIO_S8, SDL_AUDIO_U8, SDL_MAX_SINT16, SDL_MAX_SINT32, SDL_MAX_SINT8, SDL_MIN_SINT16, SDL_MIN_SINT32, SDL_MIN_SINT8, SDL_roundf(), SDL_SetError(), SDL_Swap16BE, SDL_Swap16LE, SDL_Swap32BE, SDL_Swap32LE, SDL_SwapFloatBE, and SDL_SwapFloatLE.
Referenced by MixFloat32Audio().
SDL_OpenAudioDevice()
SDL_DECLSPEC SDL_AudioDeviceID SDLCALL SDL_OpenAudioDevice (SDL_AudioDeviceID devid, const SDL_AudioSpec * spec) extern
Open a specific audio device.
You can open both playback and recording devices through this function. Playback devices will take data from bound audio streams, mix it, and send it to the hardware. Recording devices will feed any bound audio streams with a copy of any incoming data.
An opened audio device starts out with no audio streams bound. To start audio playing, bind a stream and supply audio data to it. Unlike SDL2, there is no audio callback; you only bind audio streams and make sure they have data flowing into them (however, you can simulate SDL2's semantics fairly closely by using SDL_OpenAudioDeviceStream instead of this function).
If you don't care about opening a specific device, pass a devid of either SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING. In this case, SDL will try to pick the most reasonable default, and may also switch between physical devices seamlessly later, if the most reasonable default changes during the lifetime of this opened device (user changed the default in the OS's system preferences, the default got unplugged so the system jumped to a new default, the user plugged in headphones on a mobile device, etc). Unless you have a good reason to choose a specific device, this is probably what you want.
You may request a specific format for the audio device, but there is no promise the device will honor that request for several reasons. As such, it's only meant to be a hint as to what data your app will provide. Audio streams will accept data in whatever format you specify and manage conversion for you as appropriate. SDL_GetAudioDeviceFormat can tell you the preferred format for the device before opening and the actual format the device is using after opening.
It's legal to open the same device ID more than once; each successful open will generate a new logical SDL_AudioDeviceID that is managed separately from others on the same physical device. This allows libraries to open a device separately from the main app and bind its own streams without conflicting.
It is also legal to open a device ID returned by a previous call to this function; doing so just creates another logical device on the same physical device. This may be useful for making logical groupings of audio streams.
This function returns the opened device ID on success. This is a new, unique SDL_AudioDeviceID that represents a logical device.
Some backends might offer arbitrary devices (for example, a networked audio protocol that can connect to an arbitrary server). For these, as a change from SDL2, you should open a default device ID and use an SDL hint to specify the target if you care, or otherwise let the backend figure out a reasonable default. Most backends don't offer anything like this, and often this would be an end user setting an environment variable for their custom need, and not something an application should specifically manage.
When done with an audio device, possibly at the end of the app's life, one should call SDL_CloseAudioDevice() on the returned device id.
Parameters
devid the device instance id to open, or SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING for the most reasonable default device.
spec the requested device configuration. Can be NULL to use reasonable defaults.
Returns
the device ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseAudioDevice
SDL_GetAudioDeviceFormat
{
    if (!SDL_GetCurrentAudioDriver()) {
        SDL_SetError("Audio subsystem is not initialized");
        return 0;
    }
    bool wants_default = ((devid == SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK) || (devid == SDL_AUDIO_DEVICE_DEFAULT_RECORDING));
    // this will let you use a logical device to make a new logical device on the parent physical device. Could be useful?
    SDL_AudioDevice *device = NULL;
    const bool islogical = (!wants_default && !(devid & (1<<1)));
    if (!islogical) {
        device = ObtainPhysicalAudioDeviceDefaultAllowed(devid);
    } else {
        SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
        if (logdev) {
            wants_default = logdev->opened_as_default;  // was the original logical device meant to be a default? Make this one, too.
        }
    }
    SDL_AudioDeviceID result = 0;
    if (device) {
        SDL_LogicalAudioDevice *logdev = NULL;
        if (!wants_default && SDL_GetAtomicInt(&device->zombie)) {
            // uhoh, this device is undead, and just waiting to be cleaned up. Refuse explicit opens.
            SDL_SetError("Device was already lost and can't accept new opens");
        } else if ((logdev = (SDL_LogicalAudioDevice *) SDL_calloc(1, sizeof (SDL_LogicalAudioDevice))) == NULL) {
            // SDL_calloc already called SDL_OutOfMemory
        } else if (!OpenPhysicalAudioDevice(device, spec)) {  // if this is the first thing using this physical device, open at the OS level if necessary...
            SDL_free(logdev);
        } else {
            RefPhysicalAudioDevice(device);  // unref'd on successful SDL_CloseAudioDevice
            SDL_SetAtomicInt(&logdev->paused, 0);
            result = logdev->instance_id = AssignAudioDeviceInstanceId(device->recording, /*islogical=*/true);
            logdev->physical_device = device;
            logdev->gain = 1.0f;
            logdev->opened_as_default = wants_default;
            logdev->next = device->logical_devices;
            if (device->logical_devices) {
                device->logical_devices->prev = logdev;
            }
            device->logical_devices = logdev;
            UpdateAudioStreamFormatsPhysical(device);
        }
        ReleaseAudioDevice(device);
        if (result) {
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            const bool inserted = SDL_InsertIntoHashTable(current_audio.device_hash, (const void *) (uintptr_t) result, logdev, false);
            SDL_UnlockRWLock(current_audio.device_hash_lock);
            if (!inserted) {
                SDL_CloseAudioDevice(result);
                result = 0;
            }
        }
    }
    return result;
}
References AssignAudioDeviceInstanceId(), current_audio, SDL_LogicalAudioDevice::gain, SDL_LogicalAudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, NULL, ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), SDL_LogicalAudioDevice::opened_as_default, OpenPhysicalAudioDevice(), SDL_LogicalAudioDevice::paused, SDL_LogicalAudioDevice::physical_device, SDL_LogicalAudioDevice::prev, SDL_AudioDevice::recording, RefPhysicalAudioDevice(), ReleaseAudioDevice(), SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, SDL_AUDIO_DEVICE_DEFAULT_RECORDING, SDL_calloc(), SDL_CloseAudioDevice(), SDL_free(), SDL_GetAtomicInt(), SDL_GetCurrentAudioDriver(), SDL_InsertIntoHashTable(), SDL_LockRWLockForWriting(), SDL_SetAtomicInt(), SDL_SetError(), SDL_UnlockRWLock(), UpdateAudioStreamFormatsPhysical(), and SDL_AudioDevice::zombie.
Referenced by SDL_OpenAudioDeviceStream().
SDL_OpenAudioDeviceStream()
SDL_DECLSPEC SDL_AudioStream *SDLCALL SDL_OpenAudioDeviceStream (SDL_AudioDeviceID devid, const SDL_AudioSpec * spec, SDL_AudioStreamCallback callback, void * userdata) extern
Convenience function for straightforward audio init for the common case.
If all your app intends to do is provide a single source of PCM audio, this function allows you to do all your audio setup in a single call.
This is also intended to be a clean means to migrate apps from SDL2.
This function will open an audio device, create a stream and bind it. Unlike other methods of setup, the audio device will be closed when this stream is destroyed, so the app can treat the returned SDL_AudioStream as the only object needed to manage audio playback.
Also unlike other functions, the audio device begins paused. This is to map more closely to SDL2-style behavior, since there is no extra step here to bind a stream to begin audio flowing. The audio device should be resumed with SDL_ResumeAudioStreamDevice().
This function works with both playback and recording devices.
The spec parameter represents the app's side of the audio stream. That is, for recording audio, this will be the output format, and for playing audio, this will be the input format. If spec is NULL, the system will choose the format, and the app can use SDL_GetAudioStreamFormat() to obtain this information later.
If you don't care about opening a specific audio device, you can (and probably should), use SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK for playback and SDL_AUDIO_DEVICE_DEFAULT_RECORDING for recording.
One can optionally provide a callback function; if NULL, the app is expected to queue audio data for playback (or unqueue audio data if capturing). Otherwise, the callback will begin to fire once the device is unpaused.
Destroying the returned stream with SDL_DestroyAudioStream will also close the audio device associated with this stream.
Parameters
devid an audio device to open, or SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING.
spec the audio stream's data format. Can be NULL.
callback a callback where the app will provide new data for playback, or receive new data for recording. Can be NULL, in which case the app will need to call SDL_PutAudioStreamData or SDL_GetAudioStreamData as necessary.
userdata app-controlled pointer passed to callback. Can be NULL. Ignored if callback is NULL.
Returns
an audio stream on success, ready to use, or NULL on failure; call SDL_GetError() for more information. When done with this stream, call SDL_DestroyAudioStream to free resources and close the device.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamDevice
SDL_ResumeAudioStreamDevice
{
    SDL_AudioDeviceID logdevid = SDL_OpenAudioDevice(devid, spec);
    if (!logdevid) {
        return NULL;  // error string should already be set.
    }
    bool failed = false;
    SDL_AudioStream *stream = NULL;
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(logdevid, &device);
    if (!logdev) { // this shouldn't happen, but just in case.
        failed = true;
    } else {
        SDL_SetAtomicInt(&logdev->paused, 1);   // start the device paused, to match SDL2.
        SDL_assert(device != NULL);
        const bool recording = device->recording;
        // if the app didn't request a format _at all_, just make a stream that does no conversion; they can query for it later.
        SDL_AudioSpec tmpspec;
        if (!spec) {
            SDL_copyp(&tmpspec, &device->spec);
            spec = &tmpspec;
        }
        if (recording) {
            stream = SDL_CreateAudioStream(&device->spec, spec);
        } else {
            stream = SDL_CreateAudioStream(spec, &device->spec);
        }
        if (!stream) {
            failed = true;
        } else {
            // don't do all the complicated validation and locking of SDL_BindAudioStream just to set a few fields here.
            logdev->bound_streams = stream;
            logdev->simplified = true;  // forbid further binding changes on this logical device.
            stream->bound_device = logdev;
            stream->simplified = true;  // so we know to close the audio device when this is destroyed.
            UpdateAudioStreamFormatsPhysical(device);
            if (callback) {
                bool rc;
                if (recording) {
                    rc = SDL_SetAudioStreamPutCallback(stream, callback, userdata);
                } else {
                    rc = SDL_SetAudioStreamGetCallback(stream, callback, userdata);
                }
                SDL_assert(rc);  // should only fail if stream==NULL atm.
            }
        }
    }
    ReleaseAudioDevice(device);
    if (failed) {
        SDL_DestroyAudioStream(stream);
        SDL_CloseAudioDevice(logdevid);
        stream = NULL;
    }
    return stream;
}
References SDL_LogicalAudioDevice::bound_streams, NULL, ObtainLogicalAudioDevice(), SDL_LogicalAudioDevice::paused, SDL_AudioDevice::recording, ReleaseAudioDevice(), SDL_assert, SDL_CloseAudioDevice(), SDL_copyp, SDL_CreateAudioStream(), SDL_DestroyAudioStream(), SDL_OpenAudioDevice(), SDL_SetAtomicInt(), SDL_SetAudioStreamGetCallback(), SDL_SetAudioStreamPutCallback(), SDL_LogicalAudioDevice::simplified, SDL_AudioDevice::spec, and UpdateAudioStreamFormatsPhysical().
SDL_PauseAudioDevice()
SDL_DECLSPEC bool SDLCALL SDL_PauseAudioDevice (SDL_AudioDeviceID devid) extern
Use this function to pause audio playback on a specified device.
This function pauses audio processing for a given device. Any bound audio streams will not progress, and no audio will be generated. Pausing one device does not prevent other unpaused devices from running.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow. Pausing a paused device is a legal no-op.
Pausing a device can be useful to halt all audio without unbinding all the audio streams. This might be useful while a game is paused, or a level is loading, etc.
Physical devices can not be paused or unpaused, only logical devices created through SDL_OpenAudioDevice() can be.
Parameters
devid a device opened by SDL_OpenAudioDevice().
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResumeAudioDevice
SDL_AudioDevicePaused
{
    return SetLogicalAudioDevicePauseState(devid, 1);
}
References SetLogicalAudioDevicePauseState().
Referenced by SDL_PauseAudioStreamDevice().
SDL_PauseAudioStreamDevice()
SDL_DECLSPEC bool SDLCALL SDL_PauseAudioStreamDevice (SDL_AudioStream * stream) extern
Use this function to pause audio playback on the audio device associated with an audio stream.
This function pauses audio processing for a given device. Any bound audio streams will not progress, and no audio will be generated. Pausing one device does not prevent other unpaused devices from running.
Pausing a device can be useful to halt all audio without unbinding all the audio streams. This might be useful while a game is paused, or a level is loading, etc.
Parameters
stream the audio stream associated with the audio device to pause.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResumeAudioStreamDevice
{
    SDL_AudioDeviceID devid = SDL_GetAudioStreamDevice(stream);
    if (!devid) {
        return false;
    }
    return SDL_PauseAudioDevice(devid);
}
References SDL_GetAudioStreamDevice(), and SDL_PauseAudioDevice().
SDL_PutAudioStreamData()
SDL_DECLSPEC bool SDLCALL SDL_PutAudioStreamData (SDL_AudioStream * stream, const void * buf, int len) extern
Add data to the stream.
This data must match the format/channels/samplerate specified in the latest call to SDL_SetAudioStreamFormat, or the format specified when creating the stream if it hasn't been changed.
Note that this call simply copies the unconverted data for later. This is different than SDL2, where data was converted during the Put call and the Get call would just dequeue the previously-converted data.
Parameters
stream the stream the audio data is being added to.
buf a pointer to the audio data to add.
len the number of bytes to write to the stream.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearAudioStream
SDL_FlushAudioStream
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (!buf) {
        return SDL_InvalidParamError("buf");
    } else if (len < 0) {
        return SDL_InvalidParamError("len");
    } else if (len == 0) {
        return true; // nothing to do.
    }
    // When copying in large amounts of data, try and do as much work as possible
    // outside of the stream lock, otherwise the output device is likely to be starved.
    const int large_input_thresh = 64 * 1024;
    if (len >= large_input_thresh) {
        void *data = SDL_malloc(len);
        if (!data) {
            return false;
        }
        SDL_memcpy(data, buf, len);
        bool ret = PutAudioStreamBuffer(stream, data, len, FreeAllocatedAudioBuffer, NULL);
        if (!ret) {
            SDL_free(data);
        }
        return ret;
    }
    return PutAudioStreamBuffer(stream, buf, len, NULL, NULL);
}
References FreeAllocatedAudioBuffer(), NULL, PutAudioStreamBuffer(), SDL_free(), SDL_InvalidParamError, SDL_malloc(), and SDL_memcpy.
Referenced by SDL_PutAudioStreamPlanarData(), and SDL_RecordingAudioThreadIterate().
SDL_PutAudioStreamDataNoCopy()
SDL_DECLSPEC bool SDLCALL SDL_PutAudioStreamDataNoCopy (SDL_AudioStream * stream, const void * buf, int len, SDL_AudioStreamDataCompleteCallback callback, void * userdata) extern
Add external data to an audio stream without copying it.
Unlike SDL_PutAudioStreamData(), this function does not make a copy of the provided data, instead storing the provided pointer. This means that the put operation does not need to allocate and copy the data, but the original data must remain available until the stream is done with it, either by being read from the stream in its entirety, or a call to SDL_ClearAudioStream() or SDL_DestroyAudioStream().
The data must match the format/channels/samplerate specified in the latest call to SDL_SetAudioStreamFormat, or the format specified when creating the stream if it hasn't been changed.
An optional callback may be provided, which is called when the stream no longer needs the data. Once this callback fires, the stream will not access the data again. This callback will fire for any reason the data is no longer needed, including clearing or destroying the stream.
Note that there is still an allocation to store tracking information, so this function is more efficient for larger blocks of data. If you're planning to put a few samples at a time, it will be more efficient to use SDL_PutAudioStreamData(), which allocates and buffers in blocks.
Parameters
stream the stream the audio data is being added to.
buf a pointer to the audio data to add.
len the number of bytes to add to the stream.
callback the callback function to call when the data is no longer needed by the stream. May be NULL.
userdata an opaque pointer provided to the callback for its own personal use.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.4.0.
See also
SDL_ClearAudioStream
SDL_FlushAudioStream
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (!buf) {
        return SDL_InvalidParamError("buf");
    } else if (len < 0) {
        return SDL_InvalidParamError("len");
    } else if (len == 0) {
        if (callback) {
            callback(userdata, buf, len);
        }
        return true; // nothing to do.
    }
    return PutAudioStreamBuffer(stream, buf, len, callback ? callback : DontFreeThisAudioBuffer, userdata);
}
References DontFreeThisAudioBuffer(), PutAudioStreamBuffer(), and SDL_InvalidParamError.
Referenced by SDL_ConvertAudioSamples().
SDL_PutAudioStreamPlanarData()
SDL_DECLSPEC bool SDLCALL SDL_PutAudioStreamPlanarData (SDL_AudioStream * stream, const void *const * channel_buffers, int num_channels, int num_samples) extern
Add data to the stream with each channel in a separate array.
This data must match the format/channels/samplerate specified in the latest call to SDL_SetAudioStreamFormat, or the format specified when creating the stream if it hasn't been changed.
The data will be interleaved and queued. Note that SDL_AudioStream only operates on interleaved data, so this is simply a convenience function for easily queueing data from sources that provide separate arrays. There is no equivalent function to retrieve planar data.
The arrays in channel_buffers are ordered as they are to be interleaved; the first array will be the first sample in the interleaved data. Any individual array may be NULL; in this case, silence will be interleaved for that channel.
num_channels specifies how many arrays are in channel_buffers. This can be used as a safety to prevent overflow, in case the stream format has changed elsewhere. If more channels are specified than the current input spec, they are ignored. If less channels are specified, the missing arrays are treated as if they are NULL (silence is written to those channels). If the count is -1, SDL will assume the array count matches the current input spec.
Note that num_samples is the number of samples per array. This can also be thought of as the number of sample frames to be queued. A value of 1 with stereo arrays will queue two samples to the stream. This is different than SDL_PutAudioStreamData, which wants the size of a single array in bytes.
Parameters
stream the stream the audio data is being added to.
channel_buffers a pointer to an array of arrays, one array per channel.
num_channels the number of arrays in channel_buffers or -1.
num_samples the number of samples per array to write to the stream.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.4.0.
See also
SDL_ClearAudioStream
SDL_FlushAudioStream
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (!channel_buffers) {
        return SDL_InvalidParamError("channel_buffers");
    } else if (num_samples < 0) {
        return SDL_InvalidParamError("num_samples");
    } else if (num_samples == 0) {
        return true; // nothing to do.
    }
    // we do the interleaving up front without the lock held, so the audio device doesn't starve while we work.
    //  but we _do_ need to know the current input spec.
    SDL_AudioSpec spec;
    int chmap_copy[SDL_MAX_CHANNELMAP_CHANNELS];
    int *chmap = NULL;
    SDL_LockMutex(stream->lock);
    if (!CheckAudioStreamIsFullySetup(stream)) {
        SDL_UnlockMutex(stream->lock);
        return false;
    }
    SDL_copyp(&spec, &stream->src_spec);
    if (stream->src_chmap) {
        chmap = chmap_copy;
        SDL_memcpy(chmap, stream->src_chmap, sizeof (*chmap) * spec.channels);
    }
    SDL_UnlockMutex(stream->lock);
    if (spec.channels == 1) {  // nothing to interleave, just use the usual function.
        return SDL_PutAudioStreamData(stream, channel_buffers[0], SDL_AUDIO_FRAMESIZE(spec) * num_samples);
    }
    bool retval = false;
    const int len = SDL_AUDIO_FRAMESIZE(spec) * num_samples;
    #if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: wants to put %d bytes of planar data", len);
    #endif
    // Is the data small enough to just interleave it on the stack and put it through the normal interface?
    #define INTERLEAVE_STACK_SIZE 1024
    Uint8 stackbuf[INTERLEAVE_STACK_SIZE];
    void *data = stackbuf;
    SDL_ReleaseAudioBufferCallback callback = NULL;
    if (len > INTERLEAVE_STACK_SIZE) {
        // too big for the stack? Just SDL_malloc a block and interleave into that. To avoid the extra copy, we'll just set it as a
        //  new track in the queue (the distinction is specifying a callback to PutAudioStreamBufferInternal, to release the buffer).
        data = SDL_malloc(len);
        if (!data) {
            return false;
        }
        callback = FreeAllocatedAudioBuffer;
    }
    InterleaveAudioChannels(data, channel_buffers, num_channels, num_samples, &spec);
    // it's okay if the stream format changed on another thread while we didn't hold the lock; PutAudioStreamBufferInternal will notice
    //  and set up a new track with the right format, and the next SDL_PutAudioStreamData will notice that stream->src_spec doesn't
    //  match the new track and set up a new one again. It's a bad idea to change the format on another thread while putting here,
    //  but everything _will_ work out with the format that was (presumably) expected.
    SDL_LockMutex(stream->lock);
    retval = PutAudioStreamBufferInternal(stream, &spec, chmap, data, len, callback, NULL);
    SDL_UnlockMutex(stream->lock);
    return retval;
}
References SDL_AudioSpec::channels, CheckAudioStreamIsFullySetup(), FreeAllocatedAudioBuffer(), INTERLEAVE_STACK_SIZE, InterleaveAudioChannels(), NULL, PutAudioStreamBufferInternal(), SDL_AUDIO_FRAMESIZE, SDL_copyp, SDL_InvalidParamError, SDL_LockMutex(), SDL_Log(), SDL_malloc(), SDL_MAX_CHANNELMAP_CHANNELS, SDL_memcpy, SDL_PutAudioStreamData(), and SDL_UnlockMutex().
SDL_ResumeAudioDevice()
SDL_DECLSPEC bool SDLCALL SDL_ResumeAudioDevice (SDL_AudioDeviceID devid) extern
Use this function to unpause audio playback on a specified device.
This function unpauses audio processing for a given device that has previously been paused with SDL_PauseAudioDevice(). Once unpaused, any bound audio streams will begin to progress again, and audio can be generated.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow. Unpausing an unpaused device is a legal no-op.
Physical devices can not be paused or unpaused, only logical devices created through SDL_OpenAudioDevice() can be.
Parameters
devid a device opened by SDL_OpenAudioDevice().
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AudioDevicePaused
SDL_PauseAudioDevice
{
    return SetLogicalAudioDevicePauseState(devid, 0);
}
References SDLCALL, and SetLogicalAudioDevicePauseState().
Referenced by SDL_ResumeAudioStreamDevice().
SDL_ResumeAudioStreamDevice()
SDL_DECLSPEC bool SDLCALL SDL_ResumeAudioStreamDevice (SDL_AudioStream * stream) extern
Use this function to unpause audio playback on the audio device associated with an audio stream.
This function unpauses audio processing for a given device that has previously been paused. Once unpaused, any bound audio streams will begin to progress again, and audio can be generated.
SDL_OpenAudioDeviceStream opens audio devices in a paused state, so this function call is required for audio playback to begin on such devices.
Parameters
stream the audio stream associated with the audio device to resume.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseAudioStreamDevice
{
    SDL_AudioDeviceID devid = SDL_GetAudioStreamDevice(stream);
    if (!devid) {
        return false;
    }
    return SDL_ResumeAudioDevice(devid);
}
References SDL_GetAudioStreamDevice(), and SDL_ResumeAudioDevice().
SDL_SetAudioDeviceGain()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioDeviceGain (SDL_AudioDeviceID devid, float gain) extern
Change the gain of an audio device.
The gain of a device is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio devices default to a gain of 1.0f (no change in output).
Physical devices may not have their gain changed, only logical devices, and this function will always return false when used on physical devices. While it might seem attractive to adjust several logical devices at once in this way, it would allow an app or library to interfere with another portion of the program's otherwise-isolated devices.
This is applied, along with any per-audiostream gain, during playback to the hardware, and can be continuously changed to create various effects. On recording devices, this will adjust the gain before passing the data into an audiostream; that recording audiostream can then adjust its gain further when outputting the data elsewhere, if it likes, but that second gain is not applied until the data leaves the audiostream again.
Parameters
devid the audio device on which to change gain.
gain the gain. 1.0f is no change, 0.0f is silence.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioDeviceGain
{
    if (gain < 0.0f) {
        return SDL_InvalidParamError("gain");
    }
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    bool result = false;
    if (logdev) {
        logdev->gain = gain;
        UpdateAudioStreamFormatsPhysical(device);
        result = true;
    }
    ReleaseAudioDevice(device);
    return result;
}
References SDL_LogicalAudioDevice::gain, NULL, ObtainLogicalAudioDevice(), ReleaseAudioDevice(), SDL_InvalidParamError, and UpdateAudioStreamFormatsPhysical().
SDL_SetAudioPostmixCallback()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioPostmixCallback (SDL_AudioDeviceID devid, SDL_AudioPostmixCallback callback, void * userdata) extern
Set a callback that fires when data is about to be fed to an audio device.
This is useful for accessing the final mix, perhaps for writing a visualizer or applying a final effect to the audio data before playback.
The buffer is the final mix of all bound audio streams on an opened device; this callback will fire regularly for any device that is both opened and unpaused. If there is no new data to mix, either because no streams are bound to the device or all the streams are empty, this callback will still fire with the entire buffer set to silence.
This callback is allowed to make changes to the data; the contents of the buffer after this call is what is ultimately passed along to the hardware.
The callback is always provided the data in float format (values from -1.0f to 1.0f), but the number of channels or sample rate may be different than the format the app requested when opening the device; SDL might have had to manage a conversion behind the scenes, or the playback might have jumped to new physical hardware when a system default changed, etc. These details may change between calls. Accordingly, the size of the buffer might change between calls as well.
This callback can run at any time, and from any thread; if you need to serialize access to your app's data, you should provide and use a mutex or other synchronization device.
All of this to say: there are specific needs this callback can fulfill, but it is not the simplest interface. Apps should generally provide audio in their preferred format through an SDL_AudioStream and let SDL handle the difference.
This function is extremely time-sensitive; the callback should do the least amount of work possible and return as quickly as it can. The longer the callback runs, the higher the risk of audio dropouts or other problems.
This function will block until the audio device is in between iterations, so any existing callback that might be running will finish before this function sets the new callback and returns.
Setting a NULL callback function disables any previously-set callback.
Parameters
devid the ID of an opened audio device.
callback a callback function to be called. Can be NULL.
userdata app-controlled pointer passed to callback. Can be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    bool result = false;
    if (logdev) {
        result = true;
        if (callback && !device->postmix_buffer) {
            device->postmix_buffer = (float *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
            if (!device->postmix_buffer) {
                result = false;
            }
        }
        if (result) {
            logdev->postmix = callback;
            logdev->postmix_userdata = userdata;
        }
        UpdateAudioStreamFormatsPhysical(device);
    }
    ReleaseAudioDevice(device);
    return result;
}
References NULL, ObtainLogicalAudioDevice(), SDL_LogicalAudioDevice::postmix, SDL_AudioDevice::postmix_buffer, SDL_LogicalAudioDevice::postmix_userdata, ReleaseAudioDevice(), SDL_aligned_alloc(), SDL_GetSIMDAlignment(), UpdateAudioStreamFormatsPhysical(), and SDL_AudioDevice::work_buffer_size.
Referenced by SDL_DefaultAudioDeviceChanged().
SDL_SetAudioStreamFormat()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamFormat (SDL_AudioStream * stream, const SDL_AudioSpec * src_spec, const SDL_AudioSpec * dst_spec) extern
Change the input and output formats of an audio stream.
Future calls to and SDL_GetAudioStreamAvailable and SDL_GetAudioStreamData will reflect the new format, and future calls to SDL_PutAudioStreamData must provide data in the new input formats.
Data that was previously queued in the stream will still be operated on in the format that was current when it was added, which is to say you can put the end of a sound file in one format to a stream, change formats for the next sound file, and start putting that new data while the previous sound file is still queued, and everything will still play back correctly.
If a stream is bound to a device, then the format of the side of the stream bound to a device cannot be changed (src_spec for recording devices, dst_spec for playback devices). Attempts to make a change to this side will be ignored, but this will not report an error. The other side's format can be changed.
Parameters
stream the stream the format is being changed.
src_spec the new format of the audio input; if NULL, it is not changed.
dst_spec the new format of the audio output; if NULL, it is not changed.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamFormat
SDL_SetAudioStreamFrequencyRatio
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    // note that while we've removed the maximum frequency checks, SDL _will_
    // fail to resample to extremely high sample rates correctly. Really high,
    // like 196608000Hz. File a bug.  :P
    if (src_spec) {
        if (!SDL_IsSupportedAudioFormat(src_spec->format)) {
            return SDL_InvalidParamError("src_spec->format");
        } else if (!SDL_IsSupportedChannelCount(src_spec->channels)) {
            return SDL_InvalidParamError("src_spec->channels");
        } else if (src_spec->freq <= 0) {
            return SDL_InvalidParamError("src_spec->freq");
        }
    }
    if (dst_spec) {
        if (!SDL_IsSupportedAudioFormat(dst_spec->format)) {
            return SDL_InvalidParamError("dst_spec->format");
        } else if (!SDL_IsSupportedChannelCount(dst_spec->channels)) {
            return SDL_InvalidParamError("dst_spec->channels");
        } else if (dst_spec->freq <= 0) {
            return SDL_InvalidParamError("dst_spec->freq");
        }
    }
    SDL_LockMutex(stream->lock);
    // quietly refuse to change the format of the end currently bound to a device.
    if (stream->bound_device) {
        if (stream->bound_device->physical_device->recording) {
            src_spec = NULL;
        } else {
            dst_spec = NULL;
        }
    }
    if (src_spec) {
        if (src_spec->channels != stream->src_spec.channels) {
            SDL_free(stream->src_chmap);
            stream->src_chmap = NULL;
        }
        SDL_copyp(&stream->src_spec, src_spec);
    }
    if (dst_spec) {
        if (dst_spec->channels != stream->dst_spec.channels) {
            SDL_free(stream->dst_chmap);
            stream->dst_chmap = NULL;
        }
        SDL_copyp(&stream->dst_spec, dst_spec);
    }
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_AudioSpec::channels, SDL_AudioSpec::format, SDL_AudioSpec::freq, NULL, SDL_copyp, SDL_free(), SDL_InvalidParamError, SDL_IsSupportedAudioFormat(), SDL_IsSupportedChannelCount(), SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_CreateAudioStream().
SDL_SetAudioStreamFrequencyRatio()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamFrequencyRatio (SDL_AudioStream * stream, float ratio) extern
Change the frequency ratio of an audio stream.
The frequency ratio is used to adjust the rate at which input data is consumed. Changing this effectively modifies the speed and pitch of the audio. A value greater than 1.0f will play the audio faster, and at a higher pitch. A value less than 1.0f will play the audio slower, and at a lower pitch. 1.0f means play at normal speed.
This is applied during SDL_GetAudioStreamData, and can be continuously changed to create various effects.
Parameters
stream the stream on which the frequency ratio is being changed.
ratio the frequency ratio. 1.0 is normal speed. Must be between 0.01 and 100.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamFrequencyRatio
SDL_SetAudioStreamFormat
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    // Picked mostly arbitrarily.
    const float min_freq_ratio = 0.01f;
    const float max_freq_ratio = 100.0f;
    if (freq_ratio < min_freq_ratio) {
        return SDL_SetError("Frequency ratio is too low");
    } else if (freq_ratio > max_freq_ratio) {
        return SDL_SetError("Frequency ratio is too high");
    }
    SDL_LockMutex(stream->lock);
    stream->freq_ratio = freq_ratio;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), and SDL_UnlockMutex().
SDL_SetAudioStreamGain()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamGain (SDL_AudioStream * stream, float gain) extern
Change the gain of an audio stream.
The gain of a stream is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio streams default to a gain of 1.0f (no change in output).
This is applied during SDL_GetAudioStreamData, and can be continuously changed to create various effects.
Parameters
stream the stream on which the gain is being changed.
gain the gain. 1.0f is no change, 0.0f is silence.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamGain
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (gain < 0.0f) {
        return SDL_InvalidParamError("gain");
    }
    SDL_LockMutex(stream->lock);
    stream->gain = gain;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_SetAudioStreamGetCallback()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamGetCallback (SDL_AudioStream * stream, SDL_AudioStreamCallback callback, void * userdata) extern
Set a callback that runs when data is requested from an audio stream.
This callback is called before data is obtained from the stream, giving the callback the chance to add more on-demand.
The callback can (optionally) call SDL_PutAudioStreamData() to add more audio to the stream during this call; if needed, the request that triggered this callback will obtain the new data immediately.
The callback's additional_amount argument is roughly how many bytes of unconverted data (in the stream's input format) is needed by the caller, although this may overestimate a little for safety. This takes into account how much is already in the stream and only asks for any extra necessary to resolve the request, which means the callback may be asked for zero bytes, and a different amount on each call.
The callback is not required to supply exact amounts; it is allowed to supply too much or too little or none at all. The caller will get what's available, up to the amount they requested, regardless of this callback's outcome.
Clearing or flushing an audio stream does not call this callback.
This function obtains the stream's lock, which means any existing callback (get or put) in progress will finish running before setting the new callback.
Setting a NULL function turns off the callback.
Parameters
stream the audio stream to set the new callback on.
callback the new callback function to call when data is requested from the stream.
userdata an opaque pointer provided to the callback for its own personal use.
Returns
true on success or false on failure; call SDL_GetError() for more information. This only fails if stream is NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamPutCallback
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    stream->get_callback = callback;
    stream->get_callback_userdata = userdata;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_OpenAudioDeviceStream().
SDL_SetAudioStreamInputChannelMap()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamInputChannelMap (SDL_AudioStream * stream, const int * chmap, int count) extern
Set the current input channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
The input channel map reorders data that is added to a stream via SDL_PutAudioStreamData. Future calls to SDL_PutAudioStreamData must provide data in the new channel order.
Each item in the array represents an input channel, and its value is the channel that it should be remapped to. To reverse a stereo signal's left and right values, you'd have an array of { 1, 0 }. It is legal to remap multiple channels to the same thing, so { 1, 1 } would duplicate the right channel to both channels of a stereo signal. An element in the channel map set to -1 instead of a valid channel will mute that channel, setting it to a silence value.
You cannot change the number of channels through a channel map, just reorder/mute them.
Data that was previously queued in the stream will still be operated on in the order that was current when it was added, which is to say you can put the end of a sound file in one order to a stream, change orders for the next sound file, and start putting that new data while the previous sound file is still queued, and everything will still play back correctly.
Audio streams default to no remapping applied. Passing a NULL channel map is legal, and turns off remapping.
SDL will copy the channel map; the caller does not have to save this array after this call.
If count is not equal to the current number of channels in the audio stream's format, this will fail. This is a safety measure to make sure a race condition hasn't changed the format while this call is setting the channel map.
Unlike attempting to change the stream's format, the input channel map on a stream bound to a recording device is permitted to change at any time; any data added to the stream from the device after this call will have the new mapping, but previously-added data will still have the prior mapping.
Parameters
stream the SDL_AudioStream to change.
chmap the new channel map, NULL to reset to default.
count The number of channels in the map.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running. Don't change the stream's format to have a different number of channels from a a different thread at the same time, though!
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    return SetAudioStreamChannelMap(stream, &stream->src_spec, &stream->src_chmap, chmap, channels, 1);
}
References SetAudioStreamChannelMap().
SDL_SetAudioStreamOutputChannelMap()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamOutputChannelMap (SDL_AudioStream * stream, const int * chmap, int count) extern
Set the current output channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
The output channel map reorders data that is leaving a stream via SDL_GetAudioStreamData.
Each item in the array represents an input channel, and its value is the channel that it should be remapped to. To reverse a stereo signal's left and right values, you'd have an array of { 1, 0 }. It is legal to remap multiple channels to the same thing, so { 1, 1 } would duplicate the right channel to both channels of a stereo signal. An element in the channel map set to -1 instead of a valid channel will mute that channel, setting it to a silence value.
You cannot change the number of channels through a channel map, just reorder/mute them.
The output channel map can be changed at any time, as output remapping is applied during SDL_GetAudioStreamData.
Audio streams default to no remapping applied. Passing a NULL channel map is legal, and turns off remapping.
SDL will copy the channel map; the caller does not have to save this array after this call.
If count is not equal to the current number of channels in the audio stream's format, this will fail. This is a safety measure to make sure a race condition hasn't changed the format while this call is setting the channel map.
Unlike attempting to change the stream's format, the output channel map on a stream bound to a recording device is permitted to change at any time; any data added to the stream after this call will have the new mapping, but previously-added data will still have the prior mapping. When the channel map doesn't match the hardware's channel layout, SDL will convert the data before feeding it to the device for playback.
Parameters
stream the SDL_AudioStream to change.
chmap the new channel map, NULL to reset to default.
count The number of channels in the map.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running. Don't change the stream's format to have a different number of channels from a a different thread at the same time, though!
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    return SetAudioStreamChannelMap(stream, &stream->dst_spec, &stream->dst_chmap, chmap, channels, 0);
}
References SetAudioStreamChannelMap().
SDL_SetAudioStreamPutCallback()
SDL_DECLSPEC bool SDLCALL SDL_SetAudioStreamPutCallback (SDL_AudioStream * stream, SDL_AudioStreamCallback callback, void * userdata) extern
Set a callback that runs when data is added to an audio stream.
This callback is called after the data is added to the stream, giving the callback the chance to obtain it immediately.
The callback can (optionally) call SDL_GetAudioStreamData() to obtain audio from the stream during this call.
The callback's additional_amount argument is how many bytes of converted data (in the stream's output format) was provided by the caller, although this may underestimate a little for safety. This value might be less than what is currently available in the stream, if data was already there, and might be less than the caller provided if the stream needs to keep a buffer to aid in resampling. Which means the callback may be provided with zero bytes, and a different amount on each call.
The callback may call SDL_GetAudioStreamAvailable to see the total amount currently available to read from the stream, instead of the total provided by the current call.
The callback is not required to obtain all data. It is allowed to read less or none at all. Anything not read now simply remains in the stream for later access.
Clearing or flushing an audio stream does not call this callback.
This function obtains the stream's lock, which means any existing callback (get or put) in progress will finish running before setting the new callback.
Setting a NULL function turns off the callback.
Parameters
stream the audio stream to set the new callback on.
callback the new callback function to call when data is added to the stream.
userdata an opaque pointer provided to the callback for its own personal use.
Returns
true on success or false on failure; call SDL_GetError() for more information. This only fails if stream is NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamGetCallback
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    stream->put_callback = callback;
    stream->put_callback_userdata = userdata;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_OpenAudioDeviceStream().
SDL_UnbindAudioStream()
SDL_DECLSPEC void SDLCALL SDL_UnbindAudioStream (SDL_AudioStream * stream) extern
Unbind a single audio stream from its audio device.
This is a convenience function, equivalent to calling SDL_UnbindAudioStreams(&stream, 1).
Parameters
stream an audio stream to unbind from a device. Can be NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStream
{
    SDL_UnbindAudioStreams(&stream, 1);
}
References SDL_UnbindAudioStreams().
Referenced by SDL_DestroyAudioStream().
SDL_UnbindAudioStreams()
SDL_DECLSPEC void SDLCALL SDL_UnbindAudioStreams (SDL_AudioStream *const * streams, int num_streams) extern
Unbind a list of audio streams from their audio devices.
The streams being unbound do not all have to be on the same device. All streams on the same device will be unbound atomically (data will stop flowing through all unbound streams on the same device at the same time).
Unbinding a stream that isn't bound to a device is a legal no-op.
Parameters
streams an array of audio streams to unbind. Can be NULL or contain NULL.
num_streams number streams listed in the streams array.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStreams
{
    if (num_streams <= 0 || !streams) {
        return; // nothing to do
    }
    /* to prevent deadlock when holding both locks, we _must_ lock the device first, and the stream second, as that is the order the audio thread will do it.
       But this means we have an unlikely, pathological case where a stream could change its binding between when we lookup its bound device and when we lock everything,
       so we double-check here. */
    for (int i = 0; i < num_streams; i++) {
        SDL_AudioStream *stream = streams[i];
        if (!stream) {
            continue;  // nothing to do, it's a NULL stream.
        }
        while (true) {
            SDL_LockMutex(stream->lock);   // lock to check this and then release it, in case the device isn't locked yet.
            SDL_LogicalAudioDevice *bounddev = stream->bound_device;
            SDL_UnlockMutex(stream->lock);
            // lock in correct order.
            if (bounddev) {
                SDL_LockMutex(bounddev->physical_device->lock);  // this requires recursive mutexes, since we're likely locking the same device multiple times.
            }
            SDL_LockMutex(stream->lock);
            if (bounddev == stream->bound_device) {
                break;  // the binding didn't change in the small window where it could, so we're good.
            } else {
                SDL_UnlockMutex(stream->lock);  // it changed bindings! Try again.
                if (bounddev) {
                    SDL_UnlockMutex(bounddev->physical_device->lock);
                }
            }
        }
    }
    // everything is locked, start unbinding streams.
    for (int i = 0; i < num_streams; i++) {
        SDL_AudioStream *stream = streams[i];
        // don't allow unbinding from "simplified" devices (opened with SDL_OpenAudioDeviceStream). Just ignore them.
        if (stream && stream->bound_device && !stream->bound_device->simplified) {
            if (stream->bound_device->bound_streams == stream) {
                SDL_assert(!stream->prev_binding);
                stream->bound_device->bound_streams = stream->next_binding;
            }
            if (stream->prev_binding) {
                stream->prev_binding->next_binding = stream->next_binding;
            }
            if (stream->next_binding) {
                stream->next_binding->prev_binding = stream->prev_binding;
            }
            stream->prev_binding = stream->next_binding = NULL;
        }
    }
    // Finalize and unlock everything.
    for (int i = 0; i < num_streams; i++) {
        SDL_AudioStream *stream = streams[i];
        if (stream) {
            SDL_LogicalAudioDevice *logdev = stream->bound_device;
            stream->bound_device = NULL;
            SDL_UnlockMutex(stream->lock);
            if (logdev) {
                UpdateAudioStreamFormatsPhysical(logdev->physical_device);
                SDL_UnlockMutex(logdev->physical_device->lock);
            }
        }
    }
}
References SDL_AudioDevice::lock, NULL, SDL_LogicalAudioDevice::physical_device, SDL_assert, SDL_LockMutex(), SDL_UnlockMutex(), and UpdateAudioStreamFormatsPhysical().
Referenced by SDL_UnbindAudioStream().
SDL_UnlockAudioStream()
SDL_DECLSPEC bool SDLCALL SDL_UnlockAudioStream (SDL_AudioStream * stream) extern
Unlock an audio stream for serialized access.
This unlocks an audio stream after a call to SDL_LockAudioStream.
Parameters
stream the audio stream to unlock.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
You should only call this from the same thread that previously called SDL_LockAudioStream.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockAudioStream
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, and SDL_UnlockMutex().