SDL3: SDL-main/include/SDL3/SDL_test_assert.h File Reference
SDL_test_assert.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define ASSERT_FAIL 0
#define ASSERT_PASS 1
Functions
void SDLCALL SDLTest_Assert (int assertCondition, SDL_PRINTF_FORMAT_STRING const char *assertDescription,...) SDL_PRINTF_VARARG_FUNC(2)
int SDLCALL SDLTest_AssertCheck (int assertCondition, SDL_PRINTF_FORMAT_STRING const char *assertDescription,...) SDL_PRINTF_VARARG_FUNC(2)
void SDLCALL SDLTest_AssertPass (SDL_PRINTF_FORMAT_STRING const char *assertDescription,...) SDL_PRINTF_VARARG_FUNC(1)
int SDLCALL SDLTest_AssertSummaryToTestResult (void)
void SDLCALL SDLTest_LogAssertSummary (void)
void SDLCALL SDLTest_ResetAssertSummary (void)
Macro Definition Documentation
ASSERT_FAIL
#define ASSERT_FAIL 0
Assertion functions of SDL test framework.
This code is a part of the SDL test library, not the main SDL library.
ASSERT_PASS
#define ASSERT_PASS 1
Function Documentation
SDLTest_Assert()
void SDLCALL SDLTest_Assert (int assertCondition, SDL_PRINTF_FORMAT_STRING const char * assertDescription, ...)
References SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNC, and SDLCALL.
SDLTest_AssertCheck()
int SDLCALL SDLTest_AssertCheck (int assertCondition, SDL_PRINTF_FORMAT_STRING const char * assertDescription, ...)
References SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNC, SDLCALL, and SDLTest_AssertCheck().
Referenced by SDLTest_AssertCheck().
SDLTest_AssertPass()
void SDLCALL SDLTest_AssertPass (SDL_PRINTF_FORMAT_STRING const char * assertDescription, ...)
References SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNC, SDLCALL, and SDLTest_AssertPass().
Referenced by SDLTest_AssertPass().
SDLTest_AssertSummaryToTestResult()
int SDLCALL SDLTest_AssertSummaryToTestResult (void)
References SDLCALL, and SDLTest_AssertSummaryToTestResult().
Referenced by SDLTest_AssertSummaryToTestResult().
SDLTest_LogAssertSummary()
void SDLCALL SDLTest_LogAssertSummary (void)
References SDLCALL, and SDLTest_LogAssertSummary().
Referenced by SDLTest_LogAssertSummary().
SDLTest_ResetAssertSummary()
void SDLCALL SDLTest_ResetAssertSummary (void)
References SDLCALL, and SDLTest_ResetAssertSummary().
Referenced by SDLTest_ResetAssertSummary().