SDL3: SDL-main/src/video/x11/edid.h File Reference
edid.h File Reference
Data Structures
struct DetailedTiming
struct MonitorInfo
struct Timing
Typedefs
typedef struct DetailedTiming DetailedTiming
typedef struct MonitorInfo MonitorInfo
typedef struct Timing Timing
typedef unsigned char uchar
Enumerations
enum ColorType { UNDEFINED_COLOR , MONOCHROME , RGB , OTHER_COLOR }
enum Interface {
UNDEFINED , DVI , HDMI_A , HDMI_B ,
MDDI , DISPLAY_PORT
}
enum StereoType {
NO_STEREO , FIELD_RIGHT , FIELD_LEFT , TWO_WAY_RIGHT_ON_EVEN ,
TWO_WAY_LEFT_ON_EVEN , FOUR_WAY_INTERLEAVED , SIDE_BY_SIDE
}
Functions
MonitorInfo * decode_edid (const uchar *data)
void dump_monitor_info (MonitorInfo *info)
char * make_display_name (const char *output_name, const MonitorInfo *info)
Typedef Documentation
DetailedTiming
typedef struct DetailedTiming DetailedTiming
MonitorInfo
typedef struct MonitorInfo MonitorInfo
Timing
typedef struct Timing Timing
uchar
typedef unsigned char uchar
Enumeration Type Documentation
ColorType
enum ColorType
Enumerator
UNDEFINED_COLOR
MONOCHROME
RGB
OTHER_COLOR
{
    UNDEFINED_COLOR,
    MONOCHROME,
    RGB,
    OTHER_COLOR
} ColorType;
Interface
enum Interface
Enumerator
UNDEFINED
DVI
HDMI_A
HDMI_B
MDDI
DISPLAY_PORT
{
    UNDEFINED,
    DVI,
    HDMI_A,
    HDMI_B,
    MDDI,
    DISPLAY_PORT
} Interface;
StereoType
enum StereoType
Enumerator
NO_STEREO
FIELD_RIGHT
FIELD_LEFT
TWO_WAY_RIGHT_ON_EVEN
TWO_WAY_LEFT_ON_EVEN
FOUR_WAY_INTERLEAVED
SIDE_BY_SIDE
{
    NO_STEREO,
    FIELD_RIGHT,
    FIELD_LEFT,
    TWO_WAY_RIGHT_ON_EVEN,
    TWO_WAY_LEFT_ON_EVEN,
    FOUR_WAY_INTERLEAVED,
    SIDE_BY_SIDE
} StereoType;
Function Documentation
decode_edid()
MonitorInfo * decode_edid (const uchar * data)
{
    MonitorInfo *info = SDL_calloc (1, sizeof (MonitorInfo));
    decode_check_sum (edid, info);
    if (!decode_header (edid) ||
        !decode_vendor_and_product_identification (edid, info) ||
        !decode_edid_version (edid, info) ||
        !decode_display_parameters (edid, info) ||
        !decode_color_characteristics (edid, info) ||
        !decode_established_timings (edid, info) ||
        !decode_standard_timings (edid, info) ||
        !decode_descriptors (edid, info)) {
        SDL_free(info);
        return NULL;
    }
    return info;
}
References decode_check_sum(), decode_color_characteristics(), decode_descriptors(), decode_display_parameters(), decode_edid_version(), decode_established_timings(), decode_header(), decode_standard_timings(), decode_vendor_and_product_identification(), NULL, SDL_calloc(), and SDL_free().
dump_monitor_info()
void dump_monitor_info (MonitorInfo * info)
{
    int i;
    printf ("Checksum: %d (%s)\n",
        info->checksum, info->checksum? "incorrect" : "correct");
    printf ("Manufacturer Code: %s\n", info->manufacturer_code);
    printf ("Product Code: 0x%x\n", info->product_code);
    printf ("Serial Number: %u\n", info->serial_number);
    if (info->production_week != -1)
    printf ("Production Week: %d\n", info->production_week);
    else
    printf ("Production Week: unspecified\n");
    if (info->production_year != -1)
    printf ("Production Year: %d\n", info->production_year);
    else
    printf ("Production Year: unspecified\n");
    if (info->model_year != -1)
    printf ("Model Year: %d\n", info->model_year);
    else
    printf ("Model Year: unspecified\n");
    printf ("EDID revision: %d.%d\n", info->major_version, info->minor_version);
    printf ("Display is %s\n", info->is_digital? "digital" : "analog");
    if (info->is_digital)
    {
    const char *interface;
    if (info->ad.digital.bits_per_primary != -1)
        printf ("Bits Per Primary: %d\n", info->ad.digital.bits_per_primary);
    else
        printf ("Bits Per Primary: undefined\n");
    switch (info->ad.digital.interface)
    {
    case DVI: interface = "DVI"; break;
    case HDMI_A: interface = "HDMI-a"; break;
    case HDMI_B: interface = "HDMI-b"; break;
    case MDDI: interface = "MDDI"; break;
    case DISPLAY_PORT: interface = "DisplayPort"; break;
    case UNDEFINED: interface = "undefined"; break;
    default: interface = "unknown"; break;
    }
    printf ("Interface: %s\n", interface);
    printf ("RGB 4:4:4: %s\n", yesno (info->ad.digital.rgb444));
    printf ("YCrCb 4:4:4: %s\n", yesno (info->ad.digital.ycrcb444));
    printf ("YCrCb 4:2:2: %s\n", yesno (info->ad.digital.ycrcb422));
    }
    else
    {
       const char *s;
    printf ("Video Signal Level: %f\n", info->ad.analog.video_signal_level);
    printf ("Sync Signal Level: %f\n", info->ad.analog.sync_signal_level);
    printf ("Total Signal Level: %f\n", info->ad.analog.total_signal_level);
    printf ("Blank to Black: %s\n",
        yesno (info->ad.analog.blank_to_black));
    printf ("Separate HV Sync: %s\n",
        yesno (info->ad.analog.separate_hv_sync));
    printf ("Composite Sync on H: %s\n",
        yesno (info->ad.analog.composite_sync_on_h));
    printf ("Serration on VSync: %s\n",
        yesno (info->ad.analog.serration_on_vsync));
    switch (info->ad.analog.color_type)
    {
    case UNDEFINED_COLOR: s = "undefined"; break;
    case MONOCHROME: s = "monochrome"; break;
    case RGB: s = "rgb"; break;
    case OTHER_COLOR: s = "other color"; break;
    default: s = "unknown"; break;
    }
    printf ("Color: %s\n", s);
    }
    if (info->width_mm == -1)
    printf ("Width: undefined\n");
    else
    printf ("Width: %d mm\n", info->width_mm);
    if (info->height_mm == -1)
    printf ("Height: undefined\n");
    else
    printf ("Height: %d mm\n", info->height_mm);
    if (info->aspect_ratio > 0)
    printf ("Aspect Ratio: %f\n", info->aspect_ratio);
    else
    printf ("Aspect Ratio: undefined\n");
    if (info->gamma >= 0)
    printf ("Gamma: %f\n", info->gamma);
    else
    printf ("Gamma: undefined\n");
    printf ("Standby: %s\n", yesno (info->standby));
    printf ("Suspend: %s\n", yesno (info->suspend));
    printf ("Active Off: %s\n", yesno (info->active_off));
    printf ("SRGB is Standard: %s\n", yesno (info->srgb_is_standard));
    printf ("Preferred Timing Includes Native: %s\n",
        yesno (info->preferred_timing_includes_native));
    printf ("Continuous Frequency: %s\n", yesno (info->continuous_frequency));
    printf ("Red X: %f\n", info->red_x);
    printf ("Red Y: %f\n", info->red_y);
    printf ("Green X: %f\n", info->green_x);
    printf ("Green Y: %f\n", info->green_y);
    printf ("Blue X: %f\n", info->blue_x);
    printf ("Blue Y: %f\n", info->blue_y);
    printf ("White X: %f\n", info->white_x);
    printf ("White Y: %f\n", info->white_y);
    printf ("Established Timings:\n");
    for (i = 0; i < 24; ++i)
    {
    Timing *timing = &(info->established[i]);
    if (timing->frequency == 0)
        break;
    printf ("  %d x %d @ %d Hz\n",
        timing->width, timing->height, timing->frequency);
    }
    printf ("Standard Timings:\n");
    for (i = 0; i < 8; ++i)
    {
    Timing *timing = &(info->standard[i]);
    if (timing->frequency == 0)
        break;
    printf ("  %d x %d @ %d Hz\n",
        timing->width, timing->height, timing->frequency);
    }
    for (i = 0; i < info->n_detailed_timings; ++i)
    {
    DetailedTiming *timing = &(info->detailed_timings[i]);
    const char *s;
    printf ("Timing%s: \n",
        (i == 0 && info->preferred_timing_includes_native)?
        " (Preferred)" : "");
    printf ("  Pixel Clock: %d\n", timing->pixel_clock);
    printf ("  H Addressable: %d\n", timing->h_addr);
    printf ("  H Blank: %d\n", timing->h_blank);
    printf ("  H Front Porch: %d\n", timing->h_front_porch);
    printf ("  H Sync: %d\n", timing->h_sync);
    printf ("  V Addressable: %d\n", timing->v_addr);
    printf ("  V Blank: %d\n", timing->v_blank);
    printf ("  V Front Porch: %d\n", timing->v_front_porch);
    printf ("  V Sync: %d\n", timing->v_sync);
    printf ("  Width: %d mm\n", timing->width_mm);
    printf ("  Height: %d mm\n", timing->height_mm);
    printf ("  Right Border: %d\n", timing->right_border);
    printf ("  Top Border: %d\n", timing->top_border);
    switch (timing->stereo)
    {
    default:
    case NO_STEREO:   s = "No Stereo"; break;
    case FIELD_RIGHT: s = "Field Sequential, Right on Sync"; break;
    case FIELD_LEFT:  s = "Field Sequential, Left on Sync"; break;
    case TWO_WAY_RIGHT_ON_EVEN: s = "Two-way, Right on Even"; break;
    case TWO_WAY_LEFT_ON_EVEN:  s = "Two-way, Left on Even"; break;
    case FOUR_WAY_INTERLEAVED:  s = "Four-way Interleaved"; break;
    case SIDE_BY_SIDE:          s = "Side-by-Side"; break;
    }
    printf ("  Stereo: %s\n", s);
    if (timing->digital_sync)
    {
        printf ("  Digital Sync:\n");
        printf ("    composite: %s\n", yesno (timing->ad.digital.composite));
        printf ("    serrations: %s\n", yesno (timing->ad.digital.serrations));
        printf ("    negative vsync: %s\n",
            yesno (timing->ad.digital.negative_vsync));
        printf ("    negative hsync: %s\n",
            yesno (timing->ad.digital.negative_hsync));
    }
    else
    {
        printf ("  Analog Sync:\n");
        printf ("    bipolar: %s\n", yesno (timing->ad.analog.bipolar));
        printf ("    serrations: %s\n", yesno (timing->ad.analog.serrations));
        printf ("    sync on green: %s\n", yesno (
            timing->ad.analog.sync_on_green));
    }
    }
    printf ("Detailed Product information:\n");
    printf ("  Product Name: %s\n", info->dsc_product_name);
    printf ("  Serial Number: %s\n", info->dsc_serial_number);
    printf ("  Unspecified String: %s\n", info->dsc_string);
}
References MonitorInfo::active_off, DetailedTiming::ad, MonitorInfo::ad, DetailedTiming::analog, MonitorInfo::analog, MonitorInfo::aspect_ratio, DetailedTiming::bipolar, MonitorInfo::bits_per_primary, MonitorInfo::blank_to_black, MonitorInfo::blue_x, MonitorInfo::blue_y, MonitorInfo::checksum, MonitorInfo::color_type, DetailedTiming::composite, MonitorInfo::composite_sync_on_h, MonitorInfo::continuous_frequency, MonitorInfo::detailed_timings, DetailedTiming::digital, MonitorInfo::digital, DetailedTiming::digital_sync, MonitorInfo::dsc_product_name, MonitorInfo::dsc_serial_number, MonitorInfo::dsc_string, DVI, MonitorInfo::established, FIELD_LEFT, FIELD_RIGHT, FOUR_WAY_INTERLEAVED, Timing::frequency, MonitorInfo::gamma, MonitorInfo::green_x, MonitorInfo::green_y, DetailedTiming::h_addr, DetailedTiming::h_blank, DetailedTiming::h_front_porch, DetailedTiming::h_sync, Timing::height, DetailedTiming::height_mm, MonitorInfo::height_mm, MonitorInfo::interface, MonitorInfo::is_digital, MonitorInfo::major_version, MonitorInfo::manufacturer_code, MDDI, MonitorInfo::minor_version, MonitorInfo::model_year, MONOCHROME, MonitorInfo::n_detailed_timings, DetailedTiming::negative_hsync, DetailedTiming::negative_vsync, NO_STEREO, OTHER_COLOR, DetailedTiming::pixel_clock, MonitorInfo::preferred_timing_includes_native, MonitorInfo::product_code, MonitorInfo::production_week, MonitorInfo::production_year, MonitorInfo::red_x, MonitorInfo::red_y, RGB, DetailedTiming::right_border, MonitorInfo::separate_hv_sync, MonitorInfo::serial_number, MonitorInfo::serration_on_vsync, DetailedTiming::serrations, SIDE_BY_SIDE, MonitorInfo::srgb_is_standard, MonitorInfo::standard, MonitorInfo::standby, DetailedTiming::stereo, MonitorInfo::suspend, DetailedTiming::sync_on_green, MonitorInfo::sync_signal_level, DetailedTiming::top_border, MonitorInfo::total_signal_level, TWO_WAY_LEFT_ON_EVEN, TWO_WAY_RIGHT_ON_EVEN, UNDEFINED_COLOR, DetailedTiming::v_addr, DetailedTiming::v_blank, DetailedTiming::v_front_porch, DetailedTiming::v_sync, MonitorInfo::video_signal_level, MonitorInfo::white_x, MonitorInfo::white_y, Timing::width, DetailedTiming::width_mm, MonitorInfo::width_mm, and yesno().
make_display_name()
char * make_display_name (const char * output_name, const MonitorInfo * info)