SDL3: SDL-main/src/audio/SDL_audioqueue.c File Reference
SDL_audioqueue.c File Reference
#include "SDL_internal.h"
#include "SDL_audioqueue.h"
#include "SDL_sysaudio.h"
Data Structures
struct SDL_AudioQueue
struct SDL_AudioTrack
struct SDL_MemoryPool
Typedefs
typedef struct SDL_MemoryPool SDL_MemoryPool
Functions
static void * AllocMemoryPoolBlock (SDL_MemoryPool *pool)
static void * AllocNewMemoryPoolBlock (const SDL_MemoryPool *pool)
static SDL_AudioTrack * CreateChunkedAudioTrack (SDL_AudioQueue *queue, const SDL_AudioSpec *spec, const int *chmap)
static void DestroyAudioTrack (SDL_AudioQueue *queue, SDL_AudioTrack *track)
static void DestroyMemoryPool (SDL_MemoryPool *pool)
static void FlushAudioTrack (SDL_AudioTrack *track)
static void SDLCALL FreeChunkedAudioBuffer (void *userdata, const void *buf, int len)
static void FreeMemoryPoolBlock (SDL_MemoryPool *pool, void *block)
static void InitMemoryPool (SDL_MemoryPool *pool, size_t block_size, size_t max_free)
static const Uint8 * PeekIntoAudioQueueFuture (SDL_AudioQueue *queue, Uint8 *data, size_t len)
static const Uint8 * PeekIntoAudioQueuePast (SDL_AudioQueue *queue, Uint8 *data, size_t len)
static const Uint8 * ReadFromAudioQueue (SDL_AudioQueue *queue, Uint8 *data, size_t len)
static bool ReserveMemoryPoolBlocks (SDL_MemoryPool *pool, size_t num_blocks)
void SDL_AddTrackToAudioQueue (SDL_AudioQueue *queue, SDL_AudioTrack *track)
void * SDL_BeginAudioQueueIter (SDL_AudioQueue *queue)
void SDL_ClearAudioQueue (SDL_AudioQueue *queue)
SDL_AudioQueue * SDL_CreateAudioQueue (size_t chunk_size)
SDL_AudioTrack * SDL_CreateAudioTrack (SDL_AudioQueue *queue, const SDL_AudioSpec *spec, const int *chmap, Uint8 *data, size_t len, size_t capacity, SDL_ReleaseAudioBufferCallback callback, void *userdata)
void SDL_DestroyAudioQueue (SDL_AudioQueue *queue)
void SDL_FlushAudioQueue (SDL_AudioQueue *queue)
size_t SDL_GetAudioQueueQueued (SDL_AudioQueue *queue)
size_t SDL_NextAudioQueueIter (SDL_AudioQueue *queue, void **inout_iter, SDL_AudioSpec *out_spec, int **out_chmap, bool *out_flushed)
void SDL_PopAudioQueueHead (SDL_AudioQueue *queue)
const Uint8 * SDL_ReadFromAudioQueue (SDL_AudioQueue *queue, Uint8 *dst, SDL_AudioFormat dst_format, int dst_channels, const int *dst_map, int past_frames, int present_frames, int future_frames, Uint8 *scratch, float gain)
bool SDL_ResetAudioQueueHistory (SDL_AudioQueue *queue, int num_frames)
bool SDL_WriteToAudioQueue (SDL_AudioQueue *queue, const SDL_AudioSpec *spec, const int *chmap, const Uint8 *data, size_t len)
static void UpdateAudioQueueHistory (SDL_AudioQueue *queue, const Uint8 *data, size_t len)
static size_t WriteToAudioTrack (SDL_AudioTrack *track, const Uint8 *data, size_t len)
Typedef Documentation
SDL_MemoryPool
typedef struct SDL_MemoryPool SDL_MemoryPool
Function Documentation
AllocMemoryPoolBlock()
void * AllocMemoryPoolBlock (SDL_MemoryPool * pool) static
{
    if (pool->num_free == 0) {
        return AllocNewMemoryPoolBlock(pool);
    }
    void *block = pool->free_blocks;
    pool->free_blocks = *(void **)block;
    --pool->num_free;
    return block;
}
References AllocNewMemoryPoolBlock(), SDL_MemoryPool::free_blocks, and SDL_MemoryPool::num_free.
Referenced by CreateChunkedAudioTrack(), and SDL_CreateAudioTrack().
AllocNewMemoryPoolBlock()
void * AllocNewMemoryPoolBlock (const SDL_MemoryPool * pool) static
{
    return SDL_malloc(pool->block_size);
}
References SDL_MemoryPool::block_size, and SDL_malloc().
Referenced by AllocMemoryPoolBlock(), and ReserveMemoryPoolBlocks().
CreateChunkedAudioTrack()
SDL_AudioTrack * CreateChunkedAudioTrack (SDL_AudioQueue * queue, const SDL_AudioSpec * spec, const int * chmap) static
{
    Uint8 *chunk = (Uint8 *)AllocMemoryPoolBlock(&queue->chunk_pool);
    if (!chunk) {
        return NULL;
    }
    size_t capacity = queue->chunk_pool.block_size;
    capacity -= capacity % SDL_AUDIO_FRAMESIZE(*spec);
    SDL_AudioTrack *track = SDL_CreateAudioTrack(queue, spec, chmap, chunk, 0, capacity, FreeChunkedAudioBuffer, queue);
    if (!track) {
        FreeMemoryPoolBlock(&queue->chunk_pool, chunk);
        return NULL;
    }
    return track;
}
References AllocMemoryPoolBlock(), SDL_MemoryPool::block_size, SDL_AudioQueue::chunk_pool, FreeChunkedAudioBuffer(), FreeMemoryPoolBlock(), NULL, SDL_AUDIO_FRAMESIZE, and SDL_CreateAudioTrack().
Referenced by SDL_WriteToAudioQueue().
DestroyAudioTrack()
void DestroyAudioTrack (SDL_AudioQueue * queue, SDL_AudioTrack * track) static
{
    track->callback(track->userdata, track->data, (int)track->capacity);
    FreeMemoryPoolBlock(&queue->track_pool, track);
}
References SDL_AudioTrack::callback, SDL_AudioTrack::capacity, SDL_AudioTrack::data, FreeMemoryPoolBlock(), SDL_AudioQueue::track_pool, and SDL_AudioTrack::userdata.
Referenced by ReadFromAudioQueue(), SDL_ClearAudioQueue(), and SDL_PopAudioQueueHead().
DestroyMemoryPool()
void DestroyMemoryPool (SDL_MemoryPool * pool) static
{
    void *block = pool->free_blocks;
    pool->free_blocks = NULL;
    pool->num_free = 0;
    while (block) {
        void *next = *(void **)block;
        SDL_free(block);
        block = next;
    }
}
References SDL_MemoryPool::free_blocks, NULL, SDL_MemoryPool::num_free, and SDL_free().
Referenced by SDL_DestroyAudioQueue().
FlushAudioTrack()
void FlushAudioTrack (SDL_AudioTrack * track) static
{
    track->flushed = true;
}
References SDL_AudioTrack::flushed.
Referenced by SDL_AddTrackToAudioQueue(), SDL_FlushAudioQueue(), and SDL_WriteToAudioQueue().
FreeChunkedAudioBuffer()
void SDLCALL FreeChunkedAudioBuffer (void * userdata, const void * buf, int len) static
{
    SDL_AudioQueue *queue = (SDL_AudioQueue *)userdata;
    FreeMemoryPoolBlock(&queue->chunk_pool, (void *)buf);
}
References SDL_AudioQueue::chunk_pool, FreeMemoryPoolBlock(), and SDLCALL.
Referenced by CreateChunkedAudioTrack().
FreeMemoryPoolBlock()
void FreeMemoryPoolBlock (SDL_MemoryPool * pool, void * block) static
{
    if (pool->num_free < pool->max_free) {
        *(void **)block = pool->free_blocks;
        pool->free_blocks = block;
        ++pool->num_free;
    } else {
        SDL_free(block);
    }
}
References SDL_MemoryPool::free_blocks, SDL_MemoryPool::max_free, SDL_MemoryPool::num_free, and SDL_free().
Referenced by CreateChunkedAudioTrack(), DestroyAudioTrack(), and FreeChunkedAudioBuffer().
InitMemoryPool()
void InitMemoryPool (SDL_MemoryPool * pool, size_t block_size, size_t max_free) static
{
    SDL_zerop(pool);
    SDL_assert(block_size >= sizeof(void *));
    pool->block_size = block_size;
    pool->max_free = max_free;
}
References SDL_MemoryPool::block_size, SDL_MemoryPool::max_free, SDL_assert, and SDL_zerop.
Referenced by SDL_CreateAudioQueue().
PeekIntoAudioQueueFuture()
const Uint8 * PeekIntoAudioQueueFuture (SDL_AudioQueue * queue, Uint8 * data, size_t len) static
{
    SDL_AudioTrack *track = queue->head;
    if (track->tail - track->head >= len) {
        return &track->data[track->head];
    }
    size_t total = 0;
    for (;;) {
        size_t avail = SDL_min(len - total, track->tail - track->head);
        SDL_memcpy(&data[total], &track->data[track->head], avail);
        total += avail;
        if (total == len) {
            break;
        }
        if (track->flushed) {
            // If we have run out of data, fill the rest with silence.
            SDL_memset(&data[total], SDL_GetSilenceValueForFormat(track->spec.format), len - total);
            break;
        }
        track = track->next;
        if (!track) {
            SDL_SetError("Peeking past end of incomplete track");
            return NULL;
        }
    }
    return data;
}
References SDL_AudioTrack::data, SDL_AudioTrack::flushed, SDL_AudioSpec::format, SDL_AudioQueue::head, SDL_AudioTrack::head, SDL_AudioTrack::next, NULL, SDL_GetSilenceValueForFormat(), SDL_memcpy, SDL_memset, SDL_min, SDL_SetError(), SDL_AudioTrack::spec, and SDL_AudioTrack::tail.
Referenced by SDL_ReadFromAudioQueue().
PeekIntoAudioQueuePast()
const Uint8 * PeekIntoAudioQueuePast (SDL_AudioQueue * queue, Uint8 * data, size_t len) static
{
    SDL_AudioTrack *track = queue->head;
    if (track->head >= len) {
        return &track->data[track->head - len];
    }
    size_t past = len - track->head;
    if (past > queue->history_length) {
        return NULL;
    }
    SDL_memcpy(data, &queue->history_buffer[queue->history_length - past], past);
    SDL_memcpy(&data[past], track->data, track->head);
    return data;
}
References SDL_AudioTrack::data, SDL_AudioQueue::head, SDL_AudioTrack::head, SDL_AudioQueue::history_buffer, SDL_AudioQueue::history_length, NULL, and SDL_memcpy.
Referenced by SDL_ReadFromAudioQueue().
ReadFromAudioQueue()
const Uint8 * ReadFromAudioQueue (SDL_AudioQueue * queue, Uint8 * data, size_t len) static
{
    SDL_AudioTrack *track = queue->head;
    if (track->tail - track->head >= len) {
        const Uint8 *ptr = &track->data[track->head];
        track->head += len;
        return ptr;
    }
    size_t total = 0;
    for (;;) {
        size_t avail = SDL_min(len - total, track->tail - track->head);
        SDL_memcpy(&data[total], &track->data[track->head], avail);
        track->head += avail;
        total += avail;
        if (total == len) {
            break;
        }
        if (track->flushed) {
            SDL_SetError("Reading past end of flushed track");
            return NULL;
        }
        SDL_AudioTrack *next = track->next;
        if (!next) {
            SDL_SetError("Reading past end of incomplete track");
            return NULL;
        }
        UpdateAudioQueueHistory(queue, track->data, track->tail);
        queue->head = next;
        DestroyAudioTrack(queue, track);
        track = next;
    }
    return data;
}
References SDL_AudioTrack::data, DestroyAudioTrack(), SDL_AudioTrack::flushed, SDL_AudioQueue::head, SDL_AudioTrack::head, SDL_AudioTrack::next, NULL, SDL_memcpy, SDL_min, SDL_SetError(), SDL_AudioTrack::tail, and UpdateAudioQueueHistory().
Referenced by SDL_ReadFromAudioQueue().
ReserveMemoryPoolBlocks()
bool ReserveMemoryPoolBlocks (SDL_MemoryPool * pool, size_t num_blocks) static
{
    for (; num_blocks; --num_blocks) {
        void *block = AllocNewMemoryPoolBlock(pool);
        if (block == NULL) {
            return false;
        }
        *(void **)block = pool->free_blocks;
        pool->free_blocks = block;
        ++pool->num_free;
    }
    return true;
}
References AllocNewMemoryPoolBlock(), SDL_MemoryPool::free_blocks, NULL, and SDL_MemoryPool::num_free.
Referenced by SDL_CreateAudioQueue().
SDL_AddTrackToAudioQueue()
void SDL_AddTrackToAudioQueue (SDL_AudioQueue * queue, SDL_AudioTrack * track)
{
    SDL_AudioTrack *tail = queue->tail;
    if (tail) {
        // If the spec has changed, make sure to flush the previous track
        if (!SDL_AudioSpecsEqual(&tail->spec, &track->spec, tail->chmap, track->chmap)) {
            FlushAudioTrack(tail);
        }
        tail->next = track;
    } else {
        queue->head = track;
    }
    queue->tail = track;
}
References SDL_AudioTrack::chmap, FlushAudioTrack(), SDL_AudioQueue::head, SDL_AudioSpecsEqual(), SDL_AudioTrack::spec, SDL_AudioQueue::tail, and tail.
Referenced by PutAudioStreamBufferInternal().
SDL_BeginAudioQueueIter()
void * SDL_BeginAudioQueueIter (SDL_AudioQueue * queue)
{
    return queue->head;
}
References SDL_AudioQueue::head.
Referenced by GetAudioStreamAvailableFrames(), GetAudioStreamHead(), and SDL_GetAudioQueueQueued().
SDL_ClearAudioQueue()
void SDL_ClearAudioQueue (SDL_AudioQueue * queue)
{
    SDL_AudioTrack *track = queue->head;
    queue->head = NULL;
    queue->tail = NULL;
    queue->history_length = 0;
    while (track) {
        SDL_AudioTrack *next = track->next;
        DestroyAudioTrack(queue, track);
        track = next;
    }
}
References DestroyAudioTrack(), SDL_AudioQueue::head, SDL_AudioQueue::history_length, SDL_AudioTrack::next, NULL, and SDL_AudioQueue::tail.
Referenced by SDL_ClearAudioStream(), and SDL_DestroyAudioQueue().
SDL_CreateAudioQueue()
SDL_AudioQueue * SDL_CreateAudioQueue (size_t chunk_size)
{
    SDL_AudioQueue *queue = (SDL_AudioQueue *)SDL_calloc(1, sizeof(*queue));
    if (!queue) {
        return NULL;
    }
    InitMemoryPool(&queue->track_pool, sizeof(SDL_AudioTrack), 8);
    InitMemoryPool(&queue->chunk_pool, chunk_size, 4);
    if (!ReserveMemoryPoolBlocks(&queue->track_pool, 2)) {
        SDL_DestroyAudioQueue(queue);
        return NULL;
    }
    return queue;
}
References SDL_AudioQueue::chunk_pool, InitMemoryPool(), NULL, ReserveMemoryPoolBlocks(), SDL_calloc(), SDL_DestroyAudioQueue(), and SDL_AudioQueue::track_pool.
Referenced by SDL_CreateAudioStream().
SDL_CreateAudioTrack()
SDL_AudioTrack * SDL_CreateAudioTrack (SDL_AudioQueue * queue, const SDL_AudioSpec * spec, const int * chmap, Uint8 * data, size_t len, size_t capacity, SDL_ReleaseAudioBufferCallback callback, void * userdata)
{
    SDL_AudioTrack *track = (SDL_AudioTrack *)AllocMemoryPoolBlock(&queue->track_pool);
    if (!track) {
        return NULL;
    }
    SDL_zerop(track);
    if (chmap) {
        SDL_assert(SDL_arraysize(track->chmap_storage) >= spec->channels);
        SDL_memcpy(track->chmap_storage, chmap, sizeof (*chmap) * spec->channels);
        track->chmap = track->chmap_storage;
    }
    SDL_copyp(&track->spec, spec);
    track->userdata = userdata;
    track->callback = callback;
    track->data = data;
    track->head = 0;
    track->tail = len;
    track->capacity = capacity;
    return track;
}
References AllocMemoryPoolBlock(), SDL_AudioTrack::callback, SDL_AudioTrack::capacity, SDL_AudioSpec::channels, SDL_AudioTrack::chmap, SDL_AudioTrack::chmap_storage, SDL_AudioTrack::data, SDL_AudioTrack::head, NULL, SDL_arraysize, SDL_assert, SDL_copyp, SDL_memcpy, SDL_zerop, SDL_AudioTrack::spec, SDL_AudioTrack::tail, SDL_AudioQueue::track_pool, and SDL_AudioTrack::userdata.
Referenced by CreateChunkedAudioTrack(), and PutAudioStreamBufferInternal().
SDL_DestroyAudioQueue()
void SDL_DestroyAudioQueue (SDL_AudioQueue * queue)
{
    SDL_ClearAudioQueue(queue);
    DestroyMemoryPool(&queue->track_pool);
    DestroyMemoryPool(&queue->chunk_pool);
    SDL_aligned_free(queue->history_buffer);
    SDL_free(queue);
}
References SDL_AudioQueue::chunk_pool, DestroyMemoryPool(), SDL_AudioQueue::history_buffer, SDL_aligned_free(), SDL_ClearAudioQueue(), SDL_free(), and SDL_AudioQueue::track_pool.
Referenced by SDL_CreateAudioQueue(), and SDL_DestroyAudioStream().
SDL_FlushAudioQueue()
void SDL_FlushAudioQueue (SDL_AudioQueue * queue)
{
    SDL_AudioTrack *track = queue->tail;
    if (track) {
        FlushAudioTrack(track);
    }
}
References FlushAudioTrack(), and SDL_AudioQueue::tail.
Referenced by SDL_FlushAudioStream().
SDL_GetAudioQueueQueued()
size_t SDL_GetAudioQueueQueued (SDL_AudioQueue * queue)
{
    size_t total = 0;
    void *iter = SDL_BeginAudioQueueIter(queue);
    while (iter) {
        SDL_AudioSpec src_spec;
        int *src_chmap;
        bool flushed;
        size_t avail = SDL_NextAudioQueueIter(queue, &iter, &src_spec, &src_chmap, &flushed);
        if (avail >= SDL_SIZE_MAX - total) {
            total = SDL_SIZE_MAX;
            break;
        }
        total += avail;
    }
    return total;
}
References SDL_BeginAudioQueueIter(), SDL_NextAudioQueueIter(), and SDL_SIZE_MAX.
Referenced by SDL_GetAudioStreamQueued().
SDL_NextAudioQueueIter()
size_t SDL_NextAudioQueueIter (SDL_AudioQueue * queue, void ** inout_iter, SDL_AudioSpec * out_spec, int ** out_chmap, bool * out_flushed)
{
    SDL_AudioTrack *iter = (SDL_AudioTrack *)(*inout_iter);
    SDL_assert(iter != NULL);
    SDL_copyp(out_spec, &iter->spec);
    *out_chmap = iter->chmap;
    bool flushed = false;
    size_t queued_bytes = 0;
    while (iter) {
        SDL_AudioTrack *track = iter;
        iter = iter->next;
        size_t avail = track->tail - track->head;
        if (avail >= SDL_SIZE_MAX - queued_bytes) {
            queued_bytes = SDL_SIZE_MAX;
            flushed = false;
            break;
        }
        queued_bytes += avail;
        flushed = track->flushed;
        if (flushed) {
            break;
        }
    }
    *inout_iter = iter;
    *out_flushed = flushed;
    return queued_bytes;
}
References SDL_AudioTrack::chmap, SDL_AudioTrack::flushed, SDL_AudioTrack::head, SDL_AudioTrack::next, NULL, SDL_assert, SDL_copyp, SDL_SIZE_MAX, SDL_AudioTrack::spec, and SDL_AudioTrack::tail.
Referenced by NextAudioStreamIter(), and SDL_GetAudioQueueQueued().
SDL_PopAudioQueueHead()
void SDL_PopAudioQueueHead (SDL_AudioQueue * queue)
{
    SDL_AudioTrack *track = queue->head;
    for (;;) {
        bool flushed = track->flushed;
        SDL_AudioTrack *next = track->next;
        DestroyAudioTrack(queue, track);
        track = next;
        if (flushed) {
            break;
        }
    }
    queue->head = track;
    queue->history_length = 0;
    if (!track) {
        queue->tail = NULL;
    }
}
References DestroyAudioTrack(), SDL_AudioTrack::flushed, SDL_AudioQueue::head, SDL_AudioQueue::history_length, SDL_AudioTrack::next, NULL, and SDL_AudioQueue::tail.
Referenced by SDL_GetAudioStreamDataAdjustGain().
SDL_ReadFromAudioQueue()
const Uint8 * SDL_ReadFromAudioQueue (SDL_AudioQueue * queue, Uint8 * dst, SDL_AudioFormat dst_format, int dst_channels, const int * dst_map, int past_frames, int present_frames, int future_frames, Uint8 * scratch, float gain)
{
    SDL_AudioTrack *track = queue->head;
    if (!track) {
        return NULL;
    }
    SDL_AudioFormat src_format = track->spec.format;
    int src_channels = track->spec.channels;
    const int *src_map = track->chmap;
    size_t src_frame_size = SDL_AUDIO_BYTESIZE(src_format) * src_channels;
    size_t dst_frame_size = SDL_AUDIO_BYTESIZE(dst_format) * dst_channels;
    size_t src_past_bytes = past_frames * src_frame_size;
    size_t src_present_bytes = present_frames * src_frame_size;
    size_t src_future_bytes = future_frames * src_frame_size;
    size_t dst_past_bytes = past_frames * dst_frame_size;
    size_t dst_present_bytes = present_frames * dst_frame_size;
    size_t dst_future_bytes = future_frames * dst_frame_size;
    const bool convert = (src_format != dst_format) || (src_channels != dst_channels) || (gain != 1.0f);
    if (convert && !dst) {
        // The user didn't ask for the data to be copied, but we need to convert it, so store it in the scratch buffer
        dst = scratch;
    }
    // Can we get all of the data straight from this track?
    if ((track->head >= src_past_bytes) && ((track->tail - track->head) >= (src_present_bytes + src_future_bytes))) {
        const Uint8 *ptr = &track->data[track->head - src_past_bytes];
        track->head += src_present_bytes;
        // Do we still need to copy/convert the data?
        if (dst) {
            ConvertAudio(past_frames + present_frames + future_frames, ptr,
                         src_format, src_channels, src_map, dst, dst_format, dst_channels, dst_map, scratch, gain);
            ptr = dst;
        }
        return ptr;
    }
    if (!dst) {
        // The user didn't ask for the data to be copied, but we need to, so store it in the scratch buffer
        dst = scratch;
    } else if (!convert) {
        // We are only copying, not converting, so copy straight into the dst buffer
        scratch = dst;
    }
    Uint8 *ptr = dst;
    if (src_past_bytes) {
        ConvertAudio(past_frames, PeekIntoAudioQueuePast(queue, scratch, src_past_bytes), src_format, src_channels, src_map, dst, dst_format, dst_channels, dst_map, scratch, gain);
        dst += dst_past_bytes;
        scratch += dst_past_bytes;
    }
    if (src_present_bytes) {
        ConvertAudio(present_frames, ReadFromAudioQueue(queue, scratch, src_present_bytes), src_format, src_channels, src_map, dst, dst_format, dst_channels, dst_map, scratch, gain);
        dst += dst_present_bytes;
        scratch += dst_present_bytes;
    }
    if (src_future_bytes) {
        ConvertAudio(future_frames, PeekIntoAudioQueueFuture(queue, scratch, src_future_bytes), src_format, src_channels, src_map, dst, dst_format, dst_channels, dst_map, scratch, gain);
        dst += dst_future_bytes;
        scratch += dst_future_bytes;
    }
    return ptr;
}
References SDL_AudioSpec::channels, SDL_AudioTrack::chmap, ConvertAudio(), SDL_AudioTrack::data, SDL_AudioSpec::format, SDL_AudioQueue::head, SDL_AudioTrack::head, NULL, PeekIntoAudioQueueFuture(), PeekIntoAudioQueuePast(), ReadFromAudioQueue(), SDL_AUDIO_BYTESIZE, SDL_AudioTrack::spec, and SDL_AudioTrack::tail.
Referenced by GetAudioStreamDataInternal().
SDL_ResetAudioQueueHistory()
bool SDL_ResetAudioQueueHistory (SDL_AudioQueue * queue, int num_frames)
{
    SDL_AudioTrack *track = queue->head;
    if (!track) {
        return false;
    }
    size_t length = num_frames * SDL_AUDIO_FRAMESIZE(track->spec);
    Uint8 *history_buffer = queue->history_buffer;
    if (queue->history_capacity < length) {
        history_buffer = (Uint8 *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), length);
        if (!history_buffer) {
            return false;
        }
        SDL_aligned_free(queue->history_buffer);
        queue->history_buffer = history_buffer;
        queue->history_capacity = length;
    }
    queue->history_length = length;
    SDL_memset(history_buffer, SDL_GetSilenceValueForFormat(track->spec.format), length);
    return true;
}
References SDL_AudioSpec::format, SDL_AudioQueue::head, SDL_AudioQueue::history_buffer, SDL_AudioQueue::history_capacity, SDL_AudioQueue::history_length, SDL_aligned_alloc(), SDL_aligned_free(), SDL_AUDIO_FRAMESIZE, SDL_GetSilenceValueForFormat(), SDL_GetSIMDAlignment(), SDL_memset, and SDL_AudioTrack::spec.
Referenced by UpdateAudioStreamInputSpec().
SDL_WriteToAudioQueue()
bool SDL_WriteToAudioQueue (SDL_AudioQueue * queue, const SDL_AudioSpec * spec, const int * chmap, const Uint8 * data, size_t len)
{
    if (len == 0) {
        return true;
    }
    SDL_AudioTrack *track = queue->tail;
    if (track) {
        if (!SDL_AudioSpecsEqual(&track->spec, spec, track->chmap, chmap)) {
            FlushAudioTrack(track);
        }
    } else {
        SDL_assert(!queue->head);
        track = CreateChunkedAudioTrack(queue, spec, chmap);
        if (!track) {
            return false;
        }
        queue->head = track;
        queue->tail = track;
    }
    for (;;) {
        const size_t written = WriteToAudioTrack(track, data, len);
        data += written;
        len -= written;
        if (len == 0) {
            break;
        }
        SDL_AudioTrack *new_track = CreateChunkedAudioTrack(queue, spec, chmap);
        if (!new_track) {
            return false;
        }
        track->next = new_track;
        queue->tail = new_track;
        track = new_track;
    }
    return true;
}
References SDL_AudioTrack::chmap, CreateChunkedAudioTrack(), FlushAudioTrack(), SDL_AudioQueue::head, SDL_AudioTrack::next, SDL_assert, SDL_AudioSpecsEqual(), SDL_AudioTrack::spec, SDL_AudioQueue::tail, and WriteToAudioTrack().
Referenced by PutAudioStreamBufferInternal().
UpdateAudioQueueHistory()
void UpdateAudioQueueHistory (SDL_AudioQueue * queue, const Uint8 * data, size_t len) static
{
    Uint8 *history_buffer = queue->history_buffer;
    size_t history_bytes = queue->history_length;
    if (len >= history_bytes) {
        SDL_memcpy(history_buffer, &data[len - history_bytes], history_bytes);
    } else {
        size_t preserve = history_bytes - len;
        SDL_memmove(history_buffer, &history_buffer[len], preserve);
        SDL_memcpy(&history_buffer[preserve], data, len);
    }
}
References SDL_AudioQueue::history_buffer, SDL_AudioQueue::history_length, SDL_memcpy, and SDL_memmove.
Referenced by ReadFromAudioQueue().
WriteToAudioTrack()
size_t WriteToAudioTrack (SDL_AudioTrack * track, const Uint8 * data, size_t len) static
{
    if (track->flushed || track->tail >= track->capacity) {
        return 0;
    }
    len = SDL_min(len, track->capacity - track->tail);
    SDL_memcpy(&track->data[track->tail], data, len);
    track->tail += len;
    return len;
}
References SDL_AudioTrack::capacity, SDL_AudioTrack::data, SDL_AudioTrack::flushed, SDL_memcpy, SDL_min, and SDL_AudioTrack::tail.
Referenced by SDL_WriteToAudioQueue().