SDL3: SDL_SensorDriver Struct Reference
SDL_SensorDriver Struct Reference
#include <SDL_syssensor.h>
Data Fields
void(* Close)(SDL_Sensor *sensor)
void(* Detect)(void)
int(* GetCount)(void)
SDL_SensorID(* GetDeviceInstanceID)(int device_index)
const char *(* GetDeviceName)(int device_index)
int(* GetDeviceNonPortableType)(int device_index)
SDL_SensorType(* GetDeviceType)(int device_index)
bool(* Init)(void)
bool(* Open)(SDL_Sensor *sensor, int device_index)
void(* Quit)(void)
void(* Update)(SDL_Sensor *sensor)
Field Documentation
Close
void(* SDL_SensorDriver::Close) (SDL_Sensor *sensor)
Detect
void(* SDL_SensorDriver::Detect) (void)
GetCount
int(* SDL_SensorDriver::GetCount) (void)
GetDeviceInstanceID
SDL_SensorID(* SDL_SensorDriver::GetDeviceInstanceID) (int device_index)
GetDeviceName
const char *(* SDL_SensorDriver::GetDeviceName) (int device_index)
Referenced by SDL_GetSensorNameForID(), and SDL_OpenSensor().
GetDeviceNonPortableType
int(* SDL_SensorDriver::GetDeviceNonPortableType) (int device_index)
Referenced by SDL_GetSensorNonPortableTypeForID(), and SDL_OpenSensor().
GetDeviceType
SDL_SensorType(* SDL_SensorDriver::GetDeviceType) (int device_index)
Referenced by SDL_GetSensorTypeForID(), and SDL_OpenSensor().
Init
bool(* SDL_SensorDriver::Init) (void)
Open
bool(* SDL_SensorDriver::Open) (SDL_Sensor *sensor, int device_index)
Referenced by SDL_OpenSensor().
Quit
void(* SDL_SensorDriver::Quit) (void)
Update
void(* SDL_SensorDriver::Update) (SDL_Sensor *sensor)
Referenced by SDL_OpenSensor().
The documentation for this struct was generated from the following file:
SDL-main/src/sensor/SDL_syssensor.h