SDL3: SDL-main/src/misc/SDL_sysurl.h File Reference
SDL_sysurl.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_SYS_OpenURL (const char *url)
Function Documentation
SDL_SYS_OpenURL()
bool SDL_SYS_OpenURL (const char * url) extern
{
    return Android_JNI_OpenURL(url);
}
References Android_JNI_OpenURL(), FAILED, NULL, SDL_CreateEnvironment(), SDL_CreateProcessWithProperties(), SDL_CreateProperties(), SDL_DestroyEnvironment(), SDL_DestroyProcess(), SDL_DestroyProperties(), SDL_free(), SDL_PROP_PROCESS_CREATE_ARGS_POINTER, SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN, SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER, SDL_SetBooleanProperty(), SDL_SetError(), SDL_SetPointerProperty(), SDL_strlen(), SDL_UnsetEnvironmentVariable(), SDL_Unsupported, SDL_zero, URI_Dispatch, WIN_CoInitialize(), WIN_CoUninitialize(), WIN_SetError(), WIN_SetErrorFromHRESULT(), and WIN_UTF8ToStringW.
Referenced by SDL_OpenURL().