SDL3: SDL-main/src/SDL.c File Reference
SDL.c File Reference
#include "SDL_internal.h"
#include "SDL3/SDL_revision.h"
#include <unistd.h>
#include "core/linux/SDL_dbus.h"
#include "SDL_assert_c.h"
#include "SDL_hints_c.h"
#include "SDL_log_c.h"
#include "SDL_properties_c.h"
#include "audio/SDL_sysaudio.h"
#include "camera/SDL_camera_c.h"
#include "cpuinfo/SDL_cpuinfo_c.h"
#include "events/SDL_events_c.h"
#include "haptic/SDL_haptic_c.h"
#include "joystick/SDL_gamepad_c.h"
#include "joystick/SDL_joystick_c.h"
#include "render/SDL_sysrender.h"
#include "sensor/SDL_sensor_c.h"
#include "stdlib/SDL_getenv_c.h"
#include "thread/SDL_thread_c.h"
#include "tray/SDL_tray_utils.h"
#include "video/SDL_pixels_c.h"
#include "video/SDL_surface_c.h"
#include "video/SDL_video_c.h"
#include "filesystem/SDL_filesystem_c.h"
#include "io/SDL_asyncio_c.h"
#include "timer/SDL_timer_c.h"
Macros
#define SDL_INIT_EVERYTHING ~0U
Functions
SDL_COMPILE_TIME_ASSERT (SDL_MAJOR_VERSION_max, SDL_MAJOR_VERSION<=10)
SDL_COMPILE_TIME_ASSERT (SDL_MAJOR_VERSION_min, SDL_MAJOR_VERSION >=0)
SDL_COMPILE_TIME_ASSERT (SDL_MICRO_VERSION_max, SDL_MICRO_VERSION<=999)
SDL_COMPILE_TIME_ASSERT (SDL_MICRO_VERSION_min, SDL_MICRO_VERSION >=0)
SDL_COMPILE_TIME_ASSERT (SDL_MINOR_VERSION_max, SDL_MINOR_VERSION<=999)
SDL_COMPILE_TIME_ASSERT (SDL_MINOR_VERSION_min, SDL_MINOR_VERSION >=0)
static void SDL_DecrementSubsystemRefCount (Uint32 subsystem)
static SDL_Sandbox SDL_DetectSandbox (void)
SDL_NORETURN void SDL_ExitProcess (int exitcode)
const char * SDL_GetAppMetadataProperty (const char *name)
const char * SDL_GetPlatform (void)
const char * SDL_GetRevision (void)
SDL_Sandbox SDL_GetSandbox (void)
int SDL_GetVersion (void)
static void SDL_IncrementSubsystemRefCount (Uint32 subsystem)
bool SDL_Init (SDL_InitFlags flags)
void SDL_InitMainThread (void)
static bool SDL_InitOrIncrementSubsystem (Uint32 subsystem)
bool SDL_InitSubSystem (SDL_InitFlags flags)
bool SDL_IsMainThread (void)
bool SDL_IsTablet (void)
bool SDL_IsTV (void)
void SDL_Quit (void)
static void SDL_QuitMainThread (void)
void SDL_QuitSubSystem (SDL_InitFlags flags)
bool SDL_SetAppMetadata (const char *appname, const char *appversion, const char *appidentifier)
bool SDL_SetAppMetadataProperty (const char *name, const char *value)
void SDL_SetMainReady (void)
static bool SDL_ShouldInitSubsystem (Uint32 subsystem)
static bool SDL_ShouldQuitSubsystem (Uint32 subsystem)
static bool SDL_ValidMetadataProperty (const char *name)
Uint32 SDL_WasInit (SDL_InitFlags flags)
Variables
static bool SDL_bInMainQuit = false
static bool SDL_MainIsReady = true
static SDL_ThreadID SDL_MainThreadID = 0
static Uint8 SDL_SubsystemRefCount [32]
Macro Definition Documentation
SDL_INIT_EVERYTHING
#define SDL_INIT_EVERYTHING ~0U
Referenced by SDL_Quit(), and SDL_WasInit().
Function Documentation
SDL_COMPILE_TIME_ASSERT() [1/6]
SDL_COMPILE_TIME_ASSERT (SDL_MAJOR_VERSION_max , SDL_MAJOR_VERSION<= 10)
References SDL_MAJOR_VERSION.
SDL_COMPILE_TIME_ASSERT() [2/6]
SDL_COMPILE_TIME_ASSERT (SDL_MAJOR_VERSION_min , SDL_MAJOR_VERSION >= 0)
References SDL_MAJOR_VERSION.
SDL_COMPILE_TIME_ASSERT() [3/6]
SDL_COMPILE_TIME_ASSERT (SDL_MICRO_VERSION_max , SDL_MICRO_VERSION<= 999)
References SDL_MICRO_VERSION, and SDL_NORETURN.
SDL_COMPILE_TIME_ASSERT() [4/6]
SDL_COMPILE_TIME_ASSERT (SDL_MICRO_VERSION_min , SDL_MICRO_VERSION >= 0)
References SDL_MICRO_VERSION.
SDL_COMPILE_TIME_ASSERT() [5/6]
SDL_COMPILE_TIME_ASSERT (SDL_MINOR_VERSION_max , SDL_MINOR_VERSION<= 999)
References SDL_MINOR_VERSION.
SDL_COMPILE_TIME_ASSERT() [6/6]
SDL_COMPILE_TIME_ASSERT (SDL_MINOR_VERSION_min , SDL_MINOR_VERSION >= 0)
References SDL_MINOR_VERSION.
SDL_DecrementSubsystemRefCount()
void SDL_DecrementSubsystemRefCount (Uint32 subsystem) static
{
    const int subsystem_index = SDL_MostSignificantBitIndex32(subsystem);
    if ((subsystem_index >= 0) && (SDL_SubsystemRefCount[subsystem_index] > 0)) {
        if (SDL_bInMainQuit) {
            SDL_SubsystemRefCount[subsystem_index] = 0;
        } else {
            --SDL_SubsystemRefCount[subsystem_index];
        }
    }
}
References SDL_bInMainQuit, SDL_MostSignificantBitIndex32(), and SDL_SubsystemRefCount.
Referenced by SDL_InitSubSystem(), and SDL_QuitSubSystem().
SDL_DetectSandbox()
SDL_Sandbox SDL_DetectSandbox (void) static
{
#if defined(SDL_PLATFORM_LINUX)
    if (access("/.flatpak-info", F_OK) == 0) {
        return SDL_SANDBOX_FLATPAK;
    }
    /* For Snap, we check multiple variables because they might be set for
     * unrelated reasons. This is the same thing WebKitGTK does. */
    if (SDL_getenv("SNAP") && SDL_getenv("SNAP_NAME") && SDL_getenv("SNAP_REVISION")) {
        return SDL_SANDBOX_SNAP;
    }
    if (access("/run/host/container-manager", F_OK) == 0) {
        return SDL_SANDBOX_UNKNOWN_CONTAINER;
    }
#elif defined(SDL_PLATFORM_MACOS)
    if (SDL_getenv("APP_SANDBOX_CONTAINER_ID")) {
        return SDL_SANDBOX_MACOS;
    }
#endif
    return SDL_SANDBOX_NONE;
}
References SDL_getenv(), SDL_SANDBOX_FLATPAK, SDL_SANDBOX_MACOS, SDL_SANDBOX_NONE, SDL_SANDBOX_SNAP, and SDL_SANDBOX_UNKNOWN_CONTAINER.
Referenced by SDL_GetSandbox().
SDL_ExitProcess()
SDL_NORETURN void SDL_ExitProcess (int exitcode) extern
{
#if defined(SDL_PLATFORM_WINDOWS)
    /* "if you do not know the state of all threads in your process, it is
       better to call TerminateProcess than ExitProcess"
       https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx */
    TerminateProcess(GetCurrentProcess(), exitcode);
    /* MingW doesn't have TerminateProcess marked as noreturn, so add an
       ExitProcess here that will never be reached but make MingW happy. */
    ExitProcess(exitcode);
#elif defined(SDL_PLATFORM_EMSCRIPTEN)
    emscripten_cancel_main_loop();   // this should "kill" the app.
    emscripten_force_exit(exitcode); // this should "kill" the app.
    exit(exitcode);
#elif defined(SDL_PLATFORM_HAIKU)  // Haiku has _Exit, but it's not marked noreturn.
    _exit(exitcode);
#elif defined(HAVE__EXIT) // Upper case _Exit()
    _Exit(exitcode);
#else
    _exit(exitcode);
#endif
}
References SDL_NORETURN.
Referenced by SDL_AbortAssertion(), and SDL_ReportAssertion().
SDL_GetAppMetadataProperty()
const char * SDL_GetAppMetadataProperty (const char * name)
Get metadata about your app.
This returns metadata previously set using SDL_SetAppMetadata() or SDL_SetAppMetadataProperty(). See SDL_SetAppMetadataProperty() for the list of available properties and their meanings.
Parameters
name the name of the metadata property to get.
Returns
the current value of the metadata property, or the default if it is not set, NULL for properties with no default.
Thread Safety
It is safe to call this function from any thread, although the string returned is not protected and could potentially be freed if you call SDL_SetAppMetadataProperty() to set that property from another thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAppMetadata
SDL_SetAppMetadataProperty
{
    if (!SDL_ValidMetadataProperty(name)) {
        SDL_InvalidParamError("name");
        return NULL;
    }
    const char *value = NULL;
    if (SDL_strcmp(name, SDL_PROP_APP_METADATA_NAME_STRING) == 0) {
        value = SDL_GetHint(SDL_HINT_APP_NAME);
    } else if (SDL_strcmp(name, SDL_PROP_APP_METADATA_IDENTIFIER_STRING) == 0) {
        value = SDL_GetHint(SDL_HINT_APP_ID);
    }
    if (!value || !*value) {
        value = SDL_GetStringProperty(SDL_GetGlobalProperties(), name, NULL);
    }
    if (!value || !*value) {
        if (SDL_strcmp(name, SDL_PROP_APP_METADATA_NAME_STRING) == 0) {
            value = "SDL Application";
        } else if (SDL_strcmp(name, SDL_PROP_APP_METADATA_TYPE_STRING) == 0) {
            value = "application";
        }
    }
    return value;
}
References NULL, SDL_GetGlobalProperties(), SDL_GetHint(), SDL_GetStringProperty(), SDL_HINT_APP_ID, SDL_HINT_APP_NAME, SDL_InvalidParamError, SDL_PROP_APP_METADATA_IDENTIFIER_STRING, SDL_PROP_APP_METADATA_NAME_STRING, SDL_PROP_APP_METADATA_TYPE_STRING, SDL_strcmp(), and SDL_ValidMetadataProperty().
Referenced by SDL_GetAppID(), and SDL_InitMainThread().
SDL_GetPlatform()
const char * SDL_GetPlatform (void)
CategoryPlatform
SDL provides a means to identify the app's platform, both at compile time and runtime. Get the name of the platform.
Here are the names returned for some (but not all) supported platforms:
"Windows"
"macOS"
"Linux"
"iOS"
"Android"
Returns
the name of the platform. If the correct platform name is not available, returns a string beginning with the text "Unknown".
Since
This function is available since SDL 3.2.0.
{
#if defined(SDL_PLATFORM_PRIVATE)
    return SDL_PLATFORM_PRIVATE_NAME;
#elif defined(SDL_PLATFORM_AIX)
    return "AIX";
#elif defined(SDL_PLATFORM_ANDROID)
    return "Android";
#elif defined(SDL_PLATFORM_BSDI)
    return "BSDI";
#elif defined(SDL_PLATFORM_EMSCRIPTEN)
    return "Emscripten";
#elif defined(SDL_PLATFORM_FREEBSD)
    return "FreeBSD";
#elif defined(SDL_PLATFORM_HAIKU)
    return "Haiku";
#elif defined(SDL_PLATFORM_HPUX)
    return "HP-UX";
#elif defined(SDL_PLATFORM_IRIX)
    return "Irix";
#elif defined(SDL_PLATFORM_LINUX)
    return "Linux";
#elif defined(__MINT__)
    return "Atari MiNT";
#elif defined(SDL_PLATFORM_MACOS)
    return "macOS";
#elif defined(SDL_PLATFORM_NETBSD)
    return "NetBSD";
#elif defined(SDL_PLATFORM_NGAGE)
    return "Nokia N-Gage";
#elif defined(SDL_PLATFORM_OPENBSD)
    return "OpenBSD";
#elif defined(SDL_PLATFORM_OS2)
    return "OS/2";
#elif defined(SDL_PLATFORM_OSF)
    return "OSF/1";
#elif defined(SDL_PLATFORM_QNXNTO)
    return "QNX Neutrino";
#elif defined(SDL_PLATFORM_RISCOS)
    return "RISC OS";
#elif defined(SDL_PLATFORM_SOLARIS)
    return "Solaris";
#elif defined(SDL_PLATFORM_WIN32)
    return "Windows";
#elif defined(SDL_PLATFORM_WINGDK)
    return "WinGDK";
#elif defined(SDL_PLATFORM_XBOXONE)
    return "Xbox One";
#elif defined(SDL_PLATFORM_XBOXSERIES)
    return "Xbox Series X|S";
#elif defined(SDL_PLATFORM_IOS)
    return "iOS";
#elif defined(SDL_PLATFORM_TVOS)
    return "tvOS";
#elif defined(SDL_PLATFORM_PS2)
    return "PlayStation 2";
#elif defined(SDL_PLATFORM_PSP)
    return "PlayStation Portable";
#elif defined(SDL_PLATFORM_VITA)
    return "PlayStation Vita";
#elif defined(SDL_PLATFORM_3DS)
    return "Nintendo 3DS";
#elif defined(__managarm__)
    return "Managarm";
#else
    return "Unknown (see SDL_platform.h)";
#endif
}
Referenced by CreateMappingString(), and SDL_AddGamepadMappingsFromIO().
SDL_GetRevision()
const char * SDL_GetRevision (void)
Get the code revision of the SDL library that is linked against your program.
This value is the revision of the code you are linking against and may be different from the code you are compiling with, which is found in the constant SDL_REVISION.
The revision is an arbitrary string (a hash value) uniquely identifying the exact revision of the SDL library in use, and is only useful in comparing against other revisions. It is NOT an incrementing number.
If SDL wasn't built from a git repository with the appropriate tools, this will return an empty string.
You shouldn't use this function for anything but logging it for debugging purposes. The string is not intended to be reliable in any way.
Returns
an arbitrary string, uniquely identifying the exact revision of the SDL library in use.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetVersion
{
    return SDL_REVISION;
}
References SDL_REVISION.
SDL_GetSandbox()
SDL_Sandbox SDL_GetSandbox (void)
Get the application sandbox environment, if any.
Returns
the application sandbox environment or SDL_SANDBOX_NONE if the application is not running in a sandbox environment.
Since
This function is available since SDL 3.2.0.
{
    static SDL_Sandbox sandbox;
    static bool sandbox_initialized;
    if (!sandbox_initialized) {
        sandbox = SDL_DetectSandbox();
        sandbox_initialized = true;
    }
    return sandbox;
}
References SDL_DetectSandbox().
Referenced by SDL_hid_init(), and SDL_InitSteamVirtualGamepadInfo().
SDL_GetVersion()
int SDL_GetVersion (void)
Get the version of SDL that is linked against your program.
If you are linking to SDL dynamically, then it is possible that the current version will be different than the version you compiled against. This function returns the current version, while SDL_VERSION is the version you compiled with.
This function may be called safely at any time, even before SDL_Init().
Returns
the version of the linked library.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRevision
{
    return SDL_VERSION;
}
References SDL_VERSION.
SDL_IncrementSubsystemRefCount()
void SDL_IncrementSubsystemRefCount (Uint32 subsystem) static
{
    const int subsystem_index = SDL_MostSignificantBitIndex32(subsystem);
    SDL_assert((subsystem_index < 0) || (SDL_SubsystemRefCount[subsystem_index] < 255));
    if (subsystem_index >= 0) {
        ++SDL_SubsystemRefCount[subsystem_index];
    }
}
References SDL_assert, SDL_MostSignificantBitIndex32(), and SDL_SubsystemRefCount.
Referenced by SDL_InitSubSystem().
SDL_Init()
bool SDL_Init (SDL_InitFlags flags)
Initialize the SDL library.
SDL_Init() simply forwards to calling SDL_InitSubSystem(). Therefore, the two may be used interchangeably. Though for readability of your code SDL_InitSubSystem() might be preferred.
The file I/O (for example: SDL_IOFromFile) and threading (SDL_CreateThread) subsystems are initialized by default. Message boxes (SDL_ShowSimpleMessageBox) also attempt to work without initializing the video subsystem, in hopes of being useful in showing an error dialog when SDL_Init fails. You must specifically initialize other subsystems if you use them in your application.
Logging (such as SDL_Log) works without initialization, too.
flags may be any of the following OR'd together:
SDL_INIT_AUDIO: audio subsystem; automatically initializes the events subsystem
SDL_INIT_VIDEO: video subsystem; automatically initializes the events subsystem, should be initialized on the main thread.
SDL_INIT_JOYSTICK: joystick subsystem; automatically initializes the events subsystem
SDL_INIT_HAPTIC: haptic (force feedback) subsystem
SDL_INIT_GAMEPAD: gamepad subsystem; automatically initializes the joystick subsystem
SDL_INIT_EVENTS: events subsystem
SDL_INIT_SENSOR: sensor subsystem; automatically initializes the events subsystem
SDL_INIT_CAMERA: camera subsystem; automatically initializes the events subsystem
Subsystem initialization is ref-counted, you must call SDL_QuitSubSystem() for each SDL_InitSubSystem() to correctly shutdown a subsystem manually (or call SDL_Quit() to force shutdown). If a subsystem is already loaded then this call will increase the ref-count and return.
Consider reporting some basic metadata about your application before calling SDL_Init, using either SDL_SetAppMetadata() or SDL_SetAppMetadataProperty().
Parameters
flags subsystem initialization flags.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAppMetadata
SDL_SetAppMetadataProperty
SDL_InitSubSystem
SDL_Quit
SDL_SetMainReady
SDL_WasInit
{
    return SDL_InitSubSystem(flags);
}
References SDL_InitSubSystem().
Referenced by SDL_CreateWindowWithProperties().
SDL_InitMainThread()
void SDL_InitMainThread (void)
{
    static bool done_info = false;
    SDL_InitTLSData();
    SDL_InitEnvironment();
    SDL_InitTicks();
    SDL_InitFilesystem();
    if (!done_info) {
        const char *value;
        value = SDL_GetAppMetadataProperty(SDL_PROP_APP_METADATA_NAME_STRING);
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "App name: %s", value ? value : "<unspecified>");
        value = SDL_GetAppMetadataProperty(SDL_PROP_APP_METADATA_VERSION_STRING);
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "App version: %s", value ? value : "<unspecified>");
        value = SDL_GetAppMetadataProperty(SDL_PROP_APP_METADATA_IDENTIFIER_STRING);
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "App ID: %s", value ? value : "<unspecified>");
        SDL_LogInfo(SDL_LOG_CATEGORY_SYSTEM, "SDL revision: %s", SDL_REVISION);
        done_info = true;
    }
}
References SDL_GetAppMetadataProperty(), SDL_InitEnvironment(), SDL_InitFilesystem(), SDL_InitTicks(), SDL_InitTLSData(), SDL_LOG_CATEGORY_SYSTEM, SDL_LogInfo(), SDL_PROP_APP_METADATA_IDENTIFIER_STRING, SDL_PROP_APP_METADATA_NAME_STRING, SDL_PROP_APP_METADATA_VERSION_STRING, and SDL_REVISION.
Referenced by SDL_CreateThreadWithPropertiesRuntime(), and SDL_InitSubSystem().
SDL_InitOrIncrementSubsystem()
bool SDL_InitOrIncrementSubsystem (Uint32 subsystem) static
{
    int subsystem_index = SDL_MostSignificantBitIndex32(subsystem);
    SDL_assert((subsystem_index < 0) || (SDL_SubsystemRefCount[subsystem_index] < 255));
    if (subsystem_index < 0) {
        return false;
    }
    if (SDL_SubsystemRefCount[subsystem_index] > 0) {
        ++SDL_SubsystemRefCount[subsystem_index];
        return true;
    }
    return SDL_InitSubSystem(subsystem);
}
References SDL_assert, SDL_InitSubSystem(), SDL_MostSignificantBitIndex32(), and SDL_SubsystemRefCount.
Referenced by SDL_InitSubSystem().
SDL_InitSubSystem()
bool SDL_InitSubSystem (SDL_InitFlags flags)
Compatibility function to initialize the SDL library.
This function and SDL_Init() are interchangeable.
Parameters
flags any of the flags used by SDL_Init(); see SDL_Init for details.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_Init
SDL_Quit
SDL_QuitSubSystem
{
    Uint32 flags_initialized = 0;
    if (!SDL_MainIsReady) {
        return SDL_SetError("Application didn't initialize properly, did you include SDL_main.h in the file containing your main() function?");
    }
    SDL_InitMainThread();
#ifdef SDL_USE_LIBDBUS
    SDL_DBus_Init();
#endif
#ifdef SDL_PLATFORM_WINDOWS
    if (flags & (SDL_INIT_HAPTIC | SDL_INIT_JOYSTICK)) {
        if (!SDL_HelperWindowCreate()) {
            goto quit_and_error;
        }
    }
#endif
    // Initialize the event subsystem
    if (flags & SDL_INIT_EVENTS) {
        if (SDL_ShouldInitSubsystem(SDL_INIT_EVENTS)) {
            SDL_IncrementSubsystemRefCount(SDL_INIT_EVENTS);
            if (!SDL_InitEvents()) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_EVENTS);
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_EVENTS);
        }
        flags_initialized |= SDL_INIT_EVENTS;
    }
    // Initialize the video subsystem
    if (flags & SDL_INIT_VIDEO) {
#ifndef SDL_VIDEO_DISABLED
        if (SDL_ShouldInitSubsystem(SDL_INIT_VIDEO)) {
            // video implies events
            if (!SDL_InitOrIncrementSubsystem(SDL_INIT_EVENTS)) {
                goto quit_and_error;
            }
            // We initialize video on the main thread
            // On Apple platforms this is a requirement.
            // On other platforms, this is the definition.
            SDL_MainThreadID = SDL_GetCurrentThreadID();
            SDL_IncrementSubsystemRefCount(SDL_INIT_VIDEO);
            if (!SDL_VideoInit(NULL)) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_VIDEO);
                SDL_PushError();
                SDL_QuitSubSystem(SDL_INIT_EVENTS);
                SDL_PopError();
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_VIDEO);
        }
        flags_initialized |= SDL_INIT_VIDEO;
#else
        SDL_SetError("SDL not built with video support");
        goto quit_and_error;
#endif
    }
    // Initialize the audio subsystem
    if (flags & SDL_INIT_AUDIO) {
#ifndef SDL_AUDIO_DISABLED
        if (SDL_ShouldInitSubsystem(SDL_INIT_AUDIO)) {
            // audio implies events
            if (!SDL_InitOrIncrementSubsystem(SDL_INIT_EVENTS)) {
                goto quit_and_error;
            }
            SDL_IncrementSubsystemRefCount(SDL_INIT_AUDIO);
            if (!SDL_InitAudio(NULL)) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_AUDIO);
                SDL_PushError();
                SDL_QuitSubSystem(SDL_INIT_EVENTS);
                SDL_PopError();
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_AUDIO);
        }
        flags_initialized |= SDL_INIT_AUDIO;
#else
        SDL_SetError("SDL not built with audio support");
        goto quit_and_error;
#endif
    }
    // Initialize the joystick subsystem
    if (flags & SDL_INIT_JOYSTICK) {
#ifndef SDL_JOYSTICK_DISABLED
        if (SDL_ShouldInitSubsystem(SDL_INIT_JOYSTICK)) {
            // joystick implies events
            if (!SDL_InitOrIncrementSubsystem(SDL_INIT_EVENTS)) {
                goto quit_and_error;
            }
            SDL_IncrementSubsystemRefCount(SDL_INIT_JOYSTICK);
            if (!SDL_InitJoysticks()) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_JOYSTICK);
                SDL_PushError();
                SDL_QuitSubSystem(SDL_INIT_EVENTS);
                SDL_PopError();
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_JOYSTICK);
        }
        flags_initialized |= SDL_INIT_JOYSTICK;
#else
        SDL_SetError("SDL not built with joystick support");
        goto quit_and_error;
#endif
    }
    if (flags & SDL_INIT_GAMEPAD) {
#ifndef SDL_JOYSTICK_DISABLED
        if (SDL_ShouldInitSubsystem(SDL_INIT_GAMEPAD)) {
            // game controller implies joystick
            if (!SDL_InitOrIncrementSubsystem(SDL_INIT_JOYSTICK)) {
                goto quit_and_error;
            }
            SDL_IncrementSubsystemRefCount(SDL_INIT_GAMEPAD);
            if (!SDL_InitGamepads()) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_GAMEPAD);
                SDL_PushError();
                SDL_QuitSubSystem(SDL_INIT_JOYSTICK);
                SDL_PopError();
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_GAMEPAD);
        }
        flags_initialized |= SDL_INIT_GAMEPAD;
#else
        SDL_SetError("SDL not built with joystick support");
        goto quit_and_error;
#endif
    }
    // Initialize the haptic subsystem
    if (flags & SDL_INIT_HAPTIC) {
#ifndef SDL_HAPTIC_DISABLED
        if (SDL_ShouldInitSubsystem(SDL_INIT_HAPTIC)) {
            SDL_IncrementSubsystemRefCount(SDL_INIT_HAPTIC);
            if (!SDL_InitHaptics()) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_HAPTIC);
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_HAPTIC);
        }
        flags_initialized |= SDL_INIT_HAPTIC;
#else
        SDL_SetError("SDL not built with haptic (force feedback) support");
        goto quit_and_error;
#endif
    }
    // Initialize the sensor subsystem
    if (flags & SDL_INIT_SENSOR) {
#ifndef SDL_SENSOR_DISABLED
        if (SDL_ShouldInitSubsystem(SDL_INIT_SENSOR)) {
            SDL_IncrementSubsystemRefCount(SDL_INIT_SENSOR);
            if (!SDL_InitSensors()) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_SENSOR);
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_SENSOR);
        }
        flags_initialized |= SDL_INIT_SENSOR;
#else
        SDL_SetError("SDL not built with sensor support");
        goto quit_and_error;
#endif
    }
    // Initialize the camera subsystem
    if (flags & SDL_INIT_CAMERA) {
#ifndef SDL_CAMERA_DISABLED
        if (SDL_ShouldInitSubsystem(SDL_INIT_CAMERA)) {
            // camera implies events
            if (!SDL_InitOrIncrementSubsystem(SDL_INIT_EVENTS)) {
                goto quit_and_error;
            }
            SDL_IncrementSubsystemRefCount(SDL_INIT_CAMERA);
            if (!SDL_CameraInit(NULL)) {
                SDL_DecrementSubsystemRefCount(SDL_INIT_CAMERA);
                SDL_PushError();
                SDL_QuitSubSystem(SDL_INIT_EVENTS);
                SDL_PopError();
                goto quit_and_error;
            }
        } else {
            SDL_IncrementSubsystemRefCount(SDL_INIT_CAMERA);
        }
        flags_initialized |= SDL_INIT_CAMERA;
#else
        SDL_SetError("SDL not built with camera support");
        goto quit_and_error;
#endif
    }
    (void)flags_initialized; // make static analysis happy, since this only gets used in error cases.
    return SDL_ClearError();
quit_and_error:
    {
        SDL_PushError();
        SDL_QuitSubSystem(flags_initialized);
        SDL_PopError();
    }
    return false;
}
References NULL, SDL_CameraInit(), SDL_ClearError(), SDL_DecrementSubsystemRefCount(), SDL_GetCurrentThreadID(), SDL_IncrementSubsystemRefCount(), SDL_INIT_AUDIO, SDL_INIT_CAMERA, SDL_INIT_EVENTS, SDL_INIT_GAMEPAD, SDL_INIT_HAPTIC, SDL_INIT_JOYSTICK, SDL_INIT_SENSOR, SDL_INIT_VIDEO, SDL_InitAudio(), SDL_InitEvents(), SDL_InitGamepads(), SDL_InitHaptics(), SDL_InitJoysticks(), SDL_InitMainThread(), SDL_InitOrIncrementSubsystem(), SDL_InitSensors(), SDL_MainIsReady, SDL_MainThreadID, SDL_PopError, SDL_PushError, SDL_QuitSubSystem(), SDL_SetError(), SDL_ShouldInitSubsystem(), SDL_VideoInit(), and void().
Referenced by AttemptSensorFusion(), IsROGAlly(), SDL_Init(), SDL_InitJoysticks(), SDL_InitMainCallbacks(), SDL_InitOrIncrementSubsystem(), SDL_InitSensors(), and SDL_VideoInit().
SDL_IsMainThread()
bool SDL_IsMainThread (void)
Return whether this is the main thread.
On Apple platforms, the main thread is the thread that runs your program's main() entry point. On other platforms, the main thread is the one that calls SDL_Init(SDL_INIT_VIDEO), which should usually be the one that runs your program's main() entry point. If you are using the main callbacks, SDL_AppInit(), SDL_AppIterate(), and SDL_AppQuit() are all called on the main thread.
Returns
true if this thread is the main thread, or false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RunOnMainThread
{
    if (SDL_MainThreadID == 0) {
        // Not initialized yet?
        return true;
    }
    if (SDL_MainThreadID == SDL_GetCurrentThreadID()) {
        return true;
    }
    return false;
}
References SDL_GetCurrentThreadID(), and SDL_MainThreadID.
Referenced by SDL_CreateTray(), SDL_IsTraySupported(), and SDL_RunOnMainThread().
SDL_IsTablet()
bool SDL_IsTablet (void)
Query if the current device is a tablet.
If SDL can't determine this, it will return false.
Returns
true if the device is a tablet, false otherwise.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_PLATFORM_ANDROID
    return SDL_IsAndroidTablet();
#elif defined(SDL_PLATFORM_IOS)
    extern bool SDL_IsIPad(void);
    return SDL_IsIPad();
#else
    return false;
#endif
}
References SDL_IsAndroidTablet().
SDL_IsTV()
bool SDL_IsTV (void)
Query if the current device is a TV.
If SDL can't determine this, it will return false.
Returns
true if the device is a TV, false otherwise.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_PLATFORM_ANDROID
    return SDL_IsAndroidTV();
#elif defined(SDL_PLATFORM_IOS)
    extern bool SDL_IsAppleTV(void);
    return SDL_IsAppleTV();
#else
    return false;
#endif
}
References SDL_IsAndroidTV().
SDL_Quit()
void SDL_Quit (void)
Clean up all initialized subsystems.
You should call this function even if you have already shutdown each initialized subsystem with SDL_QuitSubSystem(). It is safe to call this function even in the case of errors in initialization.
You can use this function with atexit() to ensure that it is run when your application is shutdown, but it is not wise to do this from a library or other dynamically loaded code.
Since
This function is available since SDL 3.2.0.
See also
SDL_Init
SDL_QuitSubSystem
{
    SDL_bInMainQuit = true;
    // Quit all subsystems
#ifdef SDL_PLATFORM_WINDOWS
    SDL_HelperWindowDestroy();
#endif
    SDL_QuitSubSystem(SDL_INIT_EVERYTHING);
    SDL_CleanupTrays();
#ifdef SDL_USE_LIBDBUS
    SDL_DBus_Quit();
#endif
    SDL_QuitTimers();
    SDL_QuitAsyncIO();
    SDL_SetObjectsInvalid();
    SDL_AssertionsQuit();
    SDL_QuitPixelFormatDetails();
    SDL_QuitCPUInfo();
    /* Now that every subsystem has been quit, we reset the subsystem refcount
     * and the list of initialized subsystems.
     */
    SDL_memset(SDL_SubsystemRefCount, 0x0, sizeof(SDL_SubsystemRefCount));
    SDL_QuitLog();
    SDL_QuitHints();
    SDL_QuitProperties();
    SDL_QuitMainThread();
    SDL_bInMainQuit = false;
}
References SDL_AssertionsQuit(), SDL_bInMainQuit, SDL_CleanupTrays(), SDL_INIT_EVERYTHING, SDL_memset, SDL_QuitAsyncIO(), SDL_QuitCPUInfo(), SDL_QuitHints(), SDL_QuitLog(), SDL_QuitMainThread(), SDL_QuitPixelFormatDetails(), SDL_QuitProperties(), SDL_QuitSubSystem(), SDL_QuitTimers(), SDL_SetObjectsInvalid(), and SDL_SubsystemRefCount.
Referenced by CSDLmain::RunL(), SDL_AbortAssertion(), and SDL_QuitMainCallbacks().
SDL_QuitMainThread()
void SDL_QuitMainThread (void) static
{
    SDL_QuitFilesystem();
    SDL_QuitTicks();
    SDL_QuitEnvironment();
    SDL_QuitTLSData();
}
References SDL_QuitEnvironment(), SDL_QuitFilesystem(), SDL_QuitTicks(), and SDL_QuitTLSData().
Referenced by SDL_Quit().
SDL_QuitSubSystem()
void SDL_QuitSubSystem (SDL_InitFlags flags)
Shut down specific SDL subsystems.
You still need to call SDL_Quit() even if you close all open subsystems with SDL_QuitSubSystem().
Parameters
flags any of the flags used by SDL_Init(); see SDL_Init for details.
Since
This function is available since SDL 3.2.0.
See also
SDL_InitSubSystem
SDL_Quit
{
    // Shut down requested initialized subsystems
#ifndef SDL_CAMERA_DISABLED
    if (flags & SDL_INIT_CAMERA) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_CAMERA)) {
            SDL_QuitCamera();
            // camera implies events
            SDL_QuitSubSystem(SDL_INIT_EVENTS);
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_CAMERA);
    }
#endif
#ifndef SDL_SENSOR_DISABLED
    if (flags & SDL_INIT_SENSOR) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_SENSOR)) {
            SDL_QuitSensors();
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_SENSOR);
    }
#endif
#ifndef SDL_JOYSTICK_DISABLED
    if (flags & SDL_INIT_GAMEPAD) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_GAMEPAD)) {
            SDL_QuitGamepads();
            // game controller implies joystick
            SDL_QuitSubSystem(SDL_INIT_JOYSTICK);
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_GAMEPAD);
    }
    if (flags & SDL_INIT_JOYSTICK) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_JOYSTICK)) {
            SDL_QuitJoysticks();
            // joystick implies events
            SDL_QuitSubSystem(SDL_INIT_EVENTS);
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_JOYSTICK);
    }
#endif
#ifndef SDL_HAPTIC_DISABLED
    if (flags & SDL_INIT_HAPTIC) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_HAPTIC)) {
            SDL_QuitHaptics();
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_HAPTIC);
    }
#endif
#ifndef SDL_AUDIO_DISABLED
    if (flags & SDL_INIT_AUDIO) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_AUDIO)) {
            SDL_QuitAudio();
            // audio implies events
            SDL_QuitSubSystem(SDL_INIT_EVENTS);
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_AUDIO);
    }
#endif
#ifndef SDL_VIDEO_DISABLED
    if (flags & SDL_INIT_VIDEO) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_VIDEO)) {
            SDL_QuitRender();
            SDL_VideoQuit();
            // video implies events
            SDL_QuitSubSystem(SDL_INIT_EVENTS);
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_VIDEO);
    }
#endif
    if (flags & SDL_INIT_EVENTS) {
        if (SDL_ShouldQuitSubsystem(SDL_INIT_EVENTS)) {
            SDL_QuitEvents();
        }
        SDL_DecrementSubsystemRefCount(SDL_INIT_EVENTS);
    }
}
References SDL_DecrementSubsystemRefCount(), SDL_INIT_AUDIO, SDL_INIT_CAMERA, SDL_INIT_EVENTS, SDL_INIT_GAMEPAD, SDL_INIT_HAPTIC, SDL_INIT_JOYSTICK, SDL_INIT_SENSOR, SDL_INIT_VIDEO, SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitEvents(), SDL_QuitGamepads(), SDL_QuitHaptics(), SDL_QuitJoysticks(), SDL_QuitRender(), SDL_QuitSensors(), SDL_QuitSubSystem(), SDL_ShouldQuitSubsystem(), and SDL_VideoQuit().
Referenced by AttemptSensorFusion(), CleanupSensorFusion(), IsROGAlly(), SDL_InitSubSystem(), SDL_Quit(), SDL_QuitJoysticks(), SDL_QuitSensors(), SDL_QuitSubSystem(), SDL_VideoInit(), and SDL_VideoQuit().
SDL_SetAppMetadata()
bool SDL_SetAppMetadata (const char * appname, const char * appversion, const char * appidentifier)
Specify basic metadata about your app.
You can optionally provide metadata about your app to SDL. This is not required, but strongly encouraged.
There are several locations where SDL can make use of metadata (an "About" box in the macOS menu bar, the name of the app can be shown on some audio mixers, etc). Any piece of metadata can be left as NULL, if a specific detail doesn't make sense for the app.
This function should be called as early as possible, before SDL_Init. Multiple calls to this function are allowed, but various state might not change once it has been set up with a previous call to this function.
Passing a NULL removes any previous metadata.
This is a simplified interface for the most important information. You can supply significantly more detailed metadata with SDL_SetAppMetadataProperty().
Parameters
appname The name of the application ("My Game 2: Bad Guy's Revenge!").
appversion The version of the application ("1.0.0beta5" or a git hash, or whatever makes sense).
appidentifier A unique string in reverse-domain format that identifies this app ("com.example.mygame2").
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAppMetadataProperty
{
    SDL_SetAppMetadataProperty(SDL_PROP_APP_METADATA_NAME_STRING, appname);
    SDL_SetAppMetadataProperty(SDL_PROP_APP_METADATA_VERSION_STRING, appversion);
    SDL_SetAppMetadataProperty(SDL_PROP_APP_METADATA_IDENTIFIER_STRING, appidentifier);
    return true;
}
References SDL_PROP_APP_METADATA_IDENTIFIER_STRING, SDL_PROP_APP_METADATA_NAME_STRING, SDL_PROP_APP_METADATA_VERSION_STRING, and SDL_SetAppMetadataProperty().
SDL_SetAppMetadataProperty()
bool SDL_SetAppMetadataProperty (const char * name, const char * value)
Specify metadata about your app through a set of properties.
You can optionally provide metadata about your app to SDL. This is not required, but strongly encouraged.
There are several locations where SDL can make use of metadata (an "About" box in the macOS menu bar, the name of the app can be shown on some audio mixers, etc). Any piece of metadata can be left out, if a specific detail doesn't make sense for the app.
This function should be called as early as possible, before SDL_Init. Multiple calls to this function are allowed, but various state might not change once it has been set up with a previous call to this function.
Once set, this metadata can be read using SDL_GetAppMetadataProperty().
These are the supported properties:
SDL_PROP_APP_METADATA_NAME_STRING: The human-readable name of the application, like "My Game 2: Bad Guy's Revenge!". This will show up anywhere the OS shows the name of the application separately from window titles, such as volume control applets, etc. This defaults to "SDL Application".
SDL_PROP_APP_METADATA_VERSION_STRING: The version of the app that is running; there are no rules on format, so "1.0.3beta2" and "April 22nd, 2024" and a git hash are all valid options. This has no default.
SDL_PROP_APP_METADATA_IDENTIFIER_STRING: A unique string that identifies this app. This must be in reverse-domain format, like "com.example.mygame2". This string is used by desktop compositors to identify and group windows together, as well as match applications with associated desktop settings and icons. If you plan to package your application in a container such as Flatpak, the app ID should match the name of your Flatpak container as well. This has no default.
SDL_PROP_APP_METADATA_CREATOR_STRING: The human-readable name of the creator/developer/maker of this app, like "MojoWorkshop, LLC"
SDL_PROP_APP_METADATA_COPYRIGHT_STRING: The human-readable copyright notice, like "Copyright (c) 2024 MojoWorkshop, LLC" or whatnot. Keep this to one line, don't paste a copy of a whole software license in here. This has no default.
SDL_PROP_APP_METADATA_URL_STRING: A URL to the app on the web. Maybe a product page, or a storefront, or even a GitHub repository, for user's further information This has no default.
SDL_PROP_APP_METADATA_TYPE_STRING: The type of application this is. Currently this string can be "game" for a video game, "mediaplayer" for a media player, or generically "application" if nothing else applies. Future versions of SDL might add new types. This defaults to "application".
Parameters
name the name of the metadata property to set.
value the value of the property, or NULL to remove that property.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAppMetadataProperty
SDL_SetAppMetadata
{
    if (!SDL_ValidMetadataProperty(name)) {
        return SDL_InvalidParamError("name");
    }
    return SDL_SetStringProperty(SDL_GetGlobalProperties(), name, value);
}
References SDL_GetGlobalProperties(), SDL_InvalidParamError, SDL_SetStringProperty(), and SDL_ValidMetadataProperty().
Referenced by SDL_SetAppMetadata().
SDL_SetMainReady()
void SDL_SetMainReady (void)
Circumvent failure of SDL_Init() when not using SDL_main() as an entry point.
This function is defined in SDL_main.h, along with the preprocessor rule to redefine main() as SDL_main(). Thus to ensure that your main() function will not be changed it is necessary to define SDL_MAIN_HANDLED before including SDL.h.
Since
This function is available since SDL 3.2.0.
See also
SDL_Init
{
    SDL_MainIsReady = true;
    if (SDL_MainThreadID == 0) {
        SDL_MainThreadID = SDL_GetCurrentThreadID();
    }
}
References SDL_GetCurrentThreadID(), SDL_MainIsReady, and SDL_MainThreadID.
Referenced by CSDLmain::RunL(), and SDL_RunApp().
SDL_ShouldInitSubsystem()
bool SDL_ShouldInitSubsystem (Uint32 subsystem) static
{
    const int subsystem_index = SDL_MostSignificantBitIndex32(subsystem);
    SDL_assert((subsystem_index < 0) || (SDL_SubsystemRefCount[subsystem_index] < 255));
    return ((subsystem_index >= 0) && (SDL_SubsystemRefCount[subsystem_index] == 0));
}
References SDL_assert, SDL_MostSignificantBitIndex32(), and SDL_SubsystemRefCount.
Referenced by SDL_InitSubSystem().
SDL_ShouldQuitSubsystem()
bool SDL_ShouldQuitSubsystem (Uint32 subsystem) static
{
    const int subsystem_index = SDL_MostSignificantBitIndex32(subsystem);
    if ((subsystem_index >= 0) && (SDL_SubsystemRefCount[subsystem_index] == 0)) {
        return false;
    }
    /* If we're in SDL_Quit, we shut down every subsystem, even if refcount
     * isn't zero.
     */
    return (((subsystem_index >= 0) && (SDL_SubsystemRefCount[subsystem_index] == 1)) || SDL_bInMainQuit);
}
References SDL_bInMainQuit, SDL_MostSignificantBitIndex32(), and SDL_SubsystemRefCount.
Referenced by SDL_QuitSubSystem().
SDL_ValidMetadataProperty()
bool SDL_ValidMetadataProperty (const char * name) static
{
    if (!name || !*name) {
        return false;
    }
    if (SDL_strcmp(name, SDL_PROP_APP_METADATA_NAME_STRING) == 0 ||
        SDL_strcmp(name, SDL_PROP_APP_METADATA_VERSION_STRING) == 0 ||
        SDL_strcmp(name, SDL_PROP_APP_METADATA_IDENTIFIER_STRING) == 0 ||
        SDL_strcmp(name, SDL_PROP_APP_METADATA_CREATOR_STRING) == 0 ||
        SDL_strcmp(name, SDL_PROP_APP_METADATA_COPYRIGHT_STRING) == 0 ||
        SDL_strcmp(name, SDL_PROP_APP_METADATA_URL_STRING) == 0 ||
        SDL_strcmp(name, SDL_PROP_APP_METADATA_TYPE_STRING) == 0) {
        return true;
    }
    return false;
}
References SDL_PROP_APP_METADATA_COPYRIGHT_STRING, SDL_PROP_APP_METADATA_CREATOR_STRING, SDL_PROP_APP_METADATA_IDENTIFIER_STRING, SDL_PROP_APP_METADATA_NAME_STRING, SDL_PROP_APP_METADATA_TYPE_STRING, SDL_PROP_APP_METADATA_URL_STRING, SDL_PROP_APP_METADATA_VERSION_STRING, and SDL_strcmp().
Referenced by SDL_GetAppMetadataProperty(), and SDL_SetAppMetadataProperty().
SDL_WasInit()
Uint32 SDL_WasInit (SDL_InitFlags flags)
Get a mask of the specified subsystems which are currently initialized.
Parameters
flags any of the flags used by SDL_Init(); see SDL_Init for details.
Returns
a mask of all initialized subsystems if flags is 0, otherwise it returns the initialization status of the specified subsystems.
Since
This function is available since SDL 3.2.0.
See also
SDL_Init
SDL_InitSubSystem
{
    int i;
    int num_subsystems = SDL_arraysize(SDL_SubsystemRefCount);
    Uint32 initialized = 0;
    // Fast path for checking one flag
    if (SDL_HasExactlyOneBitSet32(flags)) {
        int subsystem_index = SDL_MostSignificantBitIndex32(flags);
        return SDL_SubsystemRefCount[subsystem_index] ? flags : 0;
    }
    if (!flags) {
        flags = SDL_INIT_EVERYTHING;
    }
    num_subsystems = SDL_min(num_subsystems, SDL_MostSignificantBitIndex32(flags) + 1);
    // Iterate over each bit in flags, and check the matching subsystem.
    for (i = 0; i < num_subsystems; ++i) {
        if ((flags & 1) && SDL_SubsystemRefCount[i] > 0) {
            initialized |= (1 << i);
        }
        flags >>= 1;
    }
    return initialized;
}
References SDL_arraysize, SDL_HasExactlyOneBitSet32(), SDL_INIT_EVERYTHING, SDL_min, SDL_MostSignificantBitIndex32(), and SDL_SubsystemRefCount.
Referenced by SDL_events_get_polling_interval(), SDL_RunOnMainThread(), SDL_UpdateJoysticks(), and SDL_UpdateSensors().
Variable Documentation
SDL_bInMainQuit
bool SDL_bInMainQuit = false static
Referenced by SDL_DecrementSubsystemRefCount(), SDL_Quit(), and SDL_ShouldQuitSubsystem().
SDL_MainIsReady
bool SDL_MainIsReady = true static
Referenced by SDL_InitSubSystem(), and SDL_SetMainReady().
SDL_MainThreadID
SDL_ThreadID SDL_MainThreadID = 0 static
Referenced by SDL_InitSubSystem(), SDL_IsMainThread(), and SDL_SetMainReady().
SDL_SubsystemRefCount
Uint8 SDL_SubsystemRefCount[32] static
Referenced by SDL_DecrementSubsystemRefCount(), SDL_IncrementSubsystemRefCount(), SDL_InitOrIncrementSubsystem(), SDL_Quit(), SDL_ShouldInitSubsystem(), SDL_ShouldQuitSubsystem(), and SDL_WasInit().