SDL3: SDL-main/src/events/SDL_keymap_c.h File Reference
SDL_keymap_c.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_Keymap
Typedefs
typedef struct SDL_Keymap SDL_Keymap
Functions
SDL_Keymap * SDL_CreateKeymap (bool auto_release)
void SDL_DestroyKeymap (SDL_Keymap *keymap)
SDL_Keymap * SDL_GetCurrentKeymap (bool ignore_options)
SDL_Keycode SDL_GetKeymapKeycode (SDL_Keymap *keymap, SDL_Scancode scancode, SDL_Keymod modstate)
SDL_Scancode SDL_GetKeymapNextReservedScancode (SDL_Keymap *keymap)
SDL_Scancode SDL_GetKeymapScancode (SDL_Keymap *keymap, SDL_Keycode keycode, SDL_Keymod *modstate)
void SDL_SetKeymapEntry (SDL_Keymap *keymap, SDL_Scancode scancode, SDL_Keymod modstate, SDL_Keycode keycode)
Typedef Documentation
SDL_Keymap
typedef struct SDL_Keymap SDL_Keymap
Function Documentation
SDL_CreateKeymap()
SDL_Keymap * SDL_CreateKeymap (bool auto_release)
{
    SDL_Keymap *keymap = (SDL_Keymap *)SDL_calloc(1, sizeof(*keymap));
    if (!keymap) {
        return NULL;
    }
    keymap->auto_release = auto_release;
    keymap->scancode_to_keycode = SDL_CreateHashTable(256, false, SDL_HashID, SDL_KeyMatchID, NULL, NULL);
    keymap->keycode_to_scancode = SDL_CreateHashTable(256, false, SDL_HashID, SDL_KeyMatchID, NULL, NULL);
    if (!keymap->scancode_to_keycode || !keymap->keycode_to_scancode) {
        SDL_DestroyKeymap(keymap);
        return NULL;
    }
    return keymap;
}
References SDL_Keymap::auto_release, SDL_Keymap::keycode_to_scancode, NULL, SDL_Keymap::scancode_to_keycode, SDL_calloc(), SDL_CreateHashTable(), SDL_DestroyKeymap(), SDL_HashID(), and SDL_KeyMatchID().
Referenced by GetNextReservedScancode(), and SetKeymapEntry().
SDL_DestroyKeymap()
void SDL_DestroyKeymap (SDL_Keymap * keymap)
{
    if (!keymap) {
        return;
    }
    SDL_DestroyHashTable(keymap->scancode_to_keycode);
    SDL_DestroyHashTable(keymap->keycode_to_scancode);
    SDL_free(keymap);
}
References SDL_Keymap::keycode_to_scancode, SDL_Keymap::scancode_to_keycode, SDL_DestroyHashTable(), and SDL_free().
Referenced by SDL_CreateKeymap(), SDL_QuitKeyboard(), and SDL_SetKeymap().
SDL_GetCurrentKeymap()
SDL_Keymap * SDL_GetCurrentKeymap (bool ignore_options)
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    SDL_Keymap *keymap = SDL_keyboard.keymap;
    if (!ignore_options) {
        if (keymap && keymap->thai_keyboard) {
            // Thai keyboards are QWERTY plus Thai characters, use the default QWERTY keymap
            return NULL;
        }
        if ((keyboard->keycode_options & KEYCODE_OPTION_LATIN_LETTERS) &&
            keymap && !keymap->latin_letters) {
            // We'll use the default QWERTY keymap
            return NULL;
        }
    }
    return keyboard->keymap;
}
References KEYCODE_OPTION_LATIN_LETTERS, SDL_Keyboard::keycode_options, SDL_Keyboard::keymap, SDL_Keymap::latin_letters, NULL, SDL_keyboard, and SDL_Keymap::thai_keyboard.
Referenced by SDL_GetKeyFromName(), SDL_GetKeyFromScancode(), and SDL_GetKeyName().
SDL_GetKeymapKeycode()
SDL_Keycode SDL_GetKeymapKeycode (SDL_Keymap * keymap, SDL_Scancode scancode, SDL_Keymod modstate)
{
    if (keymap) {
        const void *value;
        const SDL_Keymod normalized_modstate = NormalizeModifierStateForKeymap(modstate);
        Uint32 key = ((Uint32)normalized_modstate << 16) | scancode;
        // First, try the requested set of modifiers.
        if (SDL_FindInHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, &value)) {
            return (SDL_Keycode)(uintptr_t)value;
        }
        // If the requested set of modifiers was not found, search for the key from the highest to lowest modifier levels.
        if (normalized_modstate) {
            SDL_Keymod caps_mask = normalized_modstate & SDL_KMOD_CAPS;
            for (int i = caps_mask ? 2 : 1; i; --i) {
                // Shift level 5
                if (normalized_modstate & SDL_KMOD_LEVEL5) {
                    const SDL_Keymod shifted_modstate = SDL_KMOD_LEVEL5 | caps_mask;
                    key = ((Uint32)shifted_modstate << 16) | scancode;
                    if (shifted_modstate != normalized_modstate && SDL_FindInHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, &value)) {
                        return (SDL_Keycode)(uintptr_t)value;
                    }
                }
                // Shift level 4 (Level 3 + Shift)
                if ((normalized_modstate & (SDL_KMOD_MODE | SDL_KMOD_SHIFT)) == (SDL_KMOD_MODE | SDL_KMOD_SHIFT)) {
                    const SDL_Keymod shifted_modstate = SDL_KMOD_MODE | SDL_KMOD_SHIFT | caps_mask;
                    key = ((Uint32)shifted_modstate << 16) | scancode;
                    if (shifted_modstate != normalized_modstate && SDL_FindInHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, &value)) {
                        return (SDL_Keycode)(uintptr_t)value;
                    }
                }
                // Shift level 3
                if (normalized_modstate & SDL_KMOD_MODE) {
                    const SDL_Keymod shifted_modstate = SDL_KMOD_MODE | caps_mask;
                    key = ((Uint32)shifted_modstate << 16) | scancode;
                    if (shifted_modstate != normalized_modstate && SDL_FindInHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, &value)) {
                        return (SDL_Keycode)(uintptr_t)value;
                    }
                }
                // Shift level 2
                if (normalized_modstate & SDL_KMOD_SHIFT) {
                    const SDL_Keymod shifted_modstate = SDL_KMOD_SHIFT | caps_mask;
                    key = ((Uint32)shifted_modstate << 16) | scancode;
                    if (shifted_modstate != normalized_modstate && SDL_FindInHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, &value)) {
                        return (SDL_Keycode)(uintptr_t)value;
                    }
                }
                // Shift Level 1 (unmodified)
                key = ((Uint32)caps_mask << 16) | scancode;
                if (SDL_FindInHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, &value)) {
                    return (SDL_Keycode)(uintptr_t)value;
                }
                // Clear the capslock mask, if set.
                caps_mask = SDL_KMOD_NONE;
            }
        }
    }
    return SDL_GetDefaultKeyFromScancode(scancode, modstate);
}
References NormalizeModifierStateForKeymap(), scancode, SDL_Keymap::scancode_to_keycode, SDL_FindInHashTable(), SDL_GetDefaultKeyFromScancode(), SDL_KMOD_CAPS, SDL_KMOD_LEVEL5, SDL_KMOD_MODE, SDL_KMOD_NONE, and SDL_KMOD_SHIFT.
Referenced by SDL_GetKeyFromName(), SDL_GetKeyFromScancode(), SDL_GetKeyName(), and SDL_SetKeymap().
SDL_GetKeymapNextReservedScancode()
SDL_Scancode SDL_GetKeymapNextReservedScancode (SDL_Keymap * keymap)
{
    SDL_Scancode scancode;
    if (!keymap) {
        return SDL_SCANCODE_UNKNOWN;
    }
    if (keymap->next_reserved_scancode && keymap->next_reserved_scancode < SDL_SCANCODE_RESERVED + 100) {
        scancode = keymap->next_reserved_scancode;
    } else {
        scancode = SDL_SCANCODE_RESERVED;
    }
    keymap->next_reserved_scancode = scancode + 1;
    return scancode;
}
References SDL_Keymap::next_reserved_scancode, scancode, SDL_SCANCODE_RESERVED, and SDL_SCANCODE_UNKNOWN.
Referenced by GetNextReservedScancode().
SDL_GetKeymapScancode()
SDL_Scancode SDL_GetKeymapScancode (SDL_Keymap * keymap, SDL_Keycode keycode, SDL_Keymod * modstate)
{
    SDL_Scancode scancode;
    const void *value;
    if (keymap && SDL_FindInHashTable(keymap->keycode_to_scancode, (void *)(uintptr_t)keycode, &value)) {
        scancode = (SDL_Scancode)((uintptr_t)value & 0xFFFF);
        if (modstate) {
            *modstate = (SDL_Keymod)((uintptr_t)value >> 16);
        }
    } else {
        scancode = SDL_GetDefaultScancodeFromKey(keycode, modstate);
    }
    return scancode;
}
References keycode, SDL_Keymap::keycode_to_scancode, scancode, SDL_FindInHashTable(), and SDL_GetDefaultScancodeFromKey().
Referenced by SDL_GetKeyFromName(), SDL_GetKeyName(), SDL_GetScancodeFromKey(), and SDL_SendKeyboardUnicodeKey().
SDL_SetKeymapEntry()
void SDL_SetKeymapEntry (SDL_Keymap * keymap, SDL_Scancode scancode, SDL_Keymod modstate, SDL_Keycode keycode)
{
    if (!keymap) {
        return;
    }
    modstate = NormalizeModifierStateForKeymap(modstate);
    Uint32 key = ((Uint32)modstate << 16) | scancode;
    const void *value;
    if (SDL_FindInHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, &value)) {
        const SDL_Keycode existing_keycode = (SDL_Keycode)(uintptr_t)value;
        if (existing_keycode == keycode) {
            // We already have this mapping
            return;
        }
        // InsertIntoHashTable will replace the existing entry in the keymap atomically.
    }
    SDL_InsertIntoHashTable(keymap->scancode_to_keycode, (void *)(uintptr_t)key, (void *)(uintptr_t)keycode, true);
    bool update_keycode = true;
    if (SDL_FindInHashTable(keymap->keycode_to_scancode, (void *)(uintptr_t)keycode, &value)) {
        const Uint32 existing_value = (Uint32)(uintptr_t)value;
        const SDL_Keymod existing_modstate = (SDL_Keymod)(existing_value >> 16);
        // Keep the simplest combination of scancode and modifiers to generate this keycode
        if (existing_modstate <= modstate) {
            update_keycode = false;
        }
    }
    if (update_keycode) {
        SDL_InsertIntoHashTable(keymap->keycode_to_scancode, (void *)(uintptr_t)keycode, (void *)(uintptr_t)key, true);
    }
}
References keycode, SDL_Keymap::keycode_to_scancode, NormalizeModifierStateForKeymap(), scancode, SDL_Keymap::scancode_to_keycode, SDL_FindInHashTable(), and SDL_InsertIntoHashTable().
Referenced by SetKeymapEntry().