SDL3: SDL-main/include/SDL3/SDL_cpuinfo.h File Reference
SDL_cpuinfo.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDL_CACHELINE_SIZE 128
Functions
SDL_DECLSPEC int SDLCALL SDL_GetCPUCacheLineSize (void)
SDL_DECLSPEC int SDLCALL SDL_GetNumLogicalCPUCores (void)
SDL_DECLSPEC size_t SDLCALL SDL_GetSIMDAlignment (void)
SDL_DECLSPEC int SDLCALL SDL_GetSystemRAM (void)
SDL_DECLSPEC bool SDLCALL SDL_HasAltiVec (void)
SDL_DECLSPEC bool SDLCALL SDL_HasARMSIMD (void)
SDL_DECLSPEC bool SDLCALL SDL_HasAVX (void)
SDL_DECLSPEC bool SDLCALL SDL_HasAVX2 (void)
SDL_DECLSPEC bool SDLCALL SDL_HasAVX512F (void)
SDL_DECLSPEC bool SDLCALL SDL_HasLASX (void)
SDL_DECLSPEC bool SDLCALL SDL_HasLSX (void)
SDL_DECLSPEC bool SDLCALL SDL_HasMMX (void)
SDL_DECLSPEC bool SDLCALL SDL_HasNEON (void)
SDL_DECLSPEC bool SDLCALL SDL_HasSSE (void)
SDL_DECLSPEC bool SDLCALL SDL_HasSSE2 (void)
SDL_DECLSPEC bool SDLCALL SDL_HasSSE3 (void)
SDL_DECLSPEC bool SDLCALL SDL_HasSSE41 (void)
SDL_DECLSPEC bool SDLCALL SDL_HasSSE42 (void)
Macro Definition Documentation
SDL_CACHELINE_SIZE
#define SDL_CACHELINE_SIZE 128
CategoryCPUInfo
CPU feature detection for SDL.
These functions are largely concerned with reporting if the system has access to various SIMD instruction sets, but also has other important info to share, such as system RAM size and number of logical CPU cores.
CPU instruction set checks, like SDL_HasSSE() and SDL_HasNEON(), are available on all platforms, even if they don't make sense (an ARM processor will never have SSE and an x86 processor will never have NEON, for example, but these functions still exist and will simply return false in these cases). A guess for the cacheline size used for padding.
Most x86 processors have a 64 byte cache line. The 64-bit PowerPC processors have a 128 byte cache line. We use the larger value to be generally safe.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_GetCPUCacheLineSize().
Function Documentation
SDL_GetCPUCacheLineSize()
SDL_DECLSPEC int SDLCALL SDL_GetCPUCacheLineSize (void) extern
Determine the L1 cache line size of the CPU.
This is useful for determining multi-threaded structure padding or SIMD prefetch sizes.
Returns
the L1 cache line size of the CPU, in bytes.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    const char *cpuType = SDL_GetCPUType();
    int cacheline_size = SDL_CACHELINE_SIZE; // initial guess
    int a, b, c, d;
    (void)a;
    (void)b;
    (void)c;
    (void)d;
    if (SDL_strcmp(cpuType, "GenuineIntel") == 0 || SDL_strcmp(cpuType, "CentaurHauls") == 0 || SDL_strcmp(cpuType, "  Shanghai  ") == 0) {
        cpuid(0x00000001, a, b, c, d);
        cacheline_size = ((b >> 8) & 0xff) * 8;
    } else if (SDL_strcmp(cpuType, "AuthenticAMD") == 0 || SDL_strcmp(cpuType, "HygonGenuine") == 0) {
        cpuid(0x80000005, a, b, c, d);
        cacheline_size = c & 0xff;
    } else {
#if defined(HAVE_SYSCONF) && defined(_SC_LEVEL1_DCACHE_LINESIZE)
        if ((cacheline_size = (int)sysconf(_SC_LEVEL1_DCACHE_LINESIZE)) > 0) {
            return cacheline_size;
        } else {
            cacheline_size = SDL_CACHELINE_SIZE;
        }
#endif
#if defined(SDL_PLATFORM_LINUX)
        {
            FILE *f = fopen("/sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size", "r");
            if (f) {
                int size;
                if (fscanf(f, "%d", &size) == 1) {
                    cacheline_size = size;
                }
                fclose(f);
            }
        }
#elif defined(__FREEBSD__) && defined(CACHE_LINE_SIZE)
        cacheline_size = CACHE_LINE_SIZE;
#endif
    }
    return cacheline_size;
}
References cpuid, d, SDL_CACHELINE_SIZE, SDL_GetCPUType(), SDL_strcmp(), and void().
SDL_GetNumLogicalCPUCores()
SDL_DECLSPEC int SDLCALL SDL_GetNumLogicalCPUCores (void) extern
Get the number of logical CPU cores available.
Returns
the total number of logical CPU cores. On CPUs that include technologies such as hyperthreading, the number of logical cores may be more than the number of physical cores.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!SDL_NumLogicalCPUCores) {
#if defined(HAVE_SYSCONF) && defined(_SC_NPROCESSORS_ONLN)
        if (SDL_NumLogicalCPUCores <= 0) {
            SDL_NumLogicalCPUCores = (int)sysconf(_SC_NPROCESSORS_ONLN);
        }
#endif
#ifdef HAVE_SYSCTLBYNAME
        if (SDL_NumLogicalCPUCores <= 0) {
            size_t size = sizeof(SDL_NumLogicalCPUCores);
            sysctlbyname("hw.ncpu", &SDL_NumLogicalCPUCores, &size, NULL, 0);
        }
#endif
#if defined(SDL_PLATFORM_WINDOWS)
        if (SDL_NumLogicalCPUCores <= 0) {
            SYSTEM_INFO info;
            GetSystemInfo(&info);
            SDL_NumLogicalCPUCores = info.dwNumberOfProcessors;
        }
#endif
#ifdef SDL_PLATFORM_3DS
        if (SDL_NumLogicalCPUCores <= 0) {
            bool isNew3DS = false;
            APT_CheckNew3DS(&isNew3DS);
            // 1 core is always dedicated to the OS
            // Meaning that the New3DS has 3 available core, and the Old3DS only one.
            SDL_NumLogicalCPUCores = isNew3DS ? 4 : 2;
        }
#endif
        // There has to be at least 1, right? :)
        if (SDL_NumLogicalCPUCores <= 0) {
            SDL_NumLogicalCPUCores = 1;
        }
    }
    return SDL_NumLogicalCPUCores;
}
References NULL, and SDL_NumLogicalCPUCores.
Referenced by PrepareThreadpool().
SDL_GetSIMDAlignment()
SDL_DECLSPEC size_t SDLCALL SDL_GetSIMDAlignment (void) extern
Report the alignment this system needs for SIMD allocations.
This will return the minimum number of bytes to which a pointer must be aligned to be compatible with SIMD instructions on the current machine. For example, if the machine supports SSE only, it will return 16, but if it supports AVX-512F, it'll return 64 (etc). This only reports values for instruction sets SDL knows about, so if your SDL build doesn't have SDL_HasAVX512F(), then it might return 16 for the SSE support it sees and not 64 for the AVX-512 instructions that exist but SDL doesn't know about. Plan accordingly.
Returns
the alignment in bytes needed for available, known SIMD instructions.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_aligned_alloc
SDL_aligned_free
{
    if (SDL_SIMDAlignment == 0xFFFFFFFF) {
        SDL_GetCPUFeatures(); // make sure this has been calculated
    }
    SDL_assert(SDL_SIMDAlignment != 0);
    return SDL_SIMDAlignment;
}
References SDL_assert, SDL_GetCPUFeatures(), and SDL_SIMDAlignment.
Referenced by EnsureAudioStreamWorkBufferSize(), GetAudioStreamDataInternal(), OpenPhysicalAudioDevice(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CreateSurface(), SDL_ResetAudioQueueHistory(), SDL_SetAudioPostmixCallback(), and ZombieAcquireFrame().
SDL_GetSystemRAM()
SDL_DECLSPEC int SDLCALL SDL_GetSystemRAM (void) extern
Get the amount of RAM configured in the system.
Returns
the amount of RAM configured in the system in MiB.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!SDL_SystemRAM) {
#if defined(HAVE_SYSCONF) && defined(_SC_PHYS_PAGES) && defined(_SC_PAGESIZE)
        if (SDL_SystemRAM <= 0) {
            SDL_SystemRAM = (int)((Sint64)sysconf(_SC_PHYS_PAGES) * sysconf(_SC_PAGESIZE) / (1024 * 1024));
        }
#endif
#ifdef HAVE_SYSCTLBYNAME
        if (SDL_SystemRAM <= 0) {
#ifdef HW_PHYSMEM64
            // (64-bit): NetBSD since 2003, OpenBSD
            int mib[2] = { CTL_HW, HW_PHYSMEM64 };
#elif defined(HW_REALMEM)
            // (64-bit): FreeBSD since 2005, DragonFly
            int mib[2] = { CTL_HW, HW_REALMEM };
#elif defined(HW_MEMSIZE)
            // (64-bit): Darwin
            int mib[2] = { CTL_HW, HW_MEMSIZE };
#else
            // (32-bit): very old BSD, might only report up to 2 GiB
            int mib[2] = { CTL_HW, HW_PHYSMEM };
#endif // HW_PHYSMEM64
            Uint64 memsize = 0;
            size_t len = sizeof(memsize);
            if (sysctl(mib, 2, &memsize, &len, NULL, 0) == 0) {
                SDL_SystemRAM = (int)(memsize / (1024 * 1024));
            }
        }
#endif
#if defined(SDL_PLATFORM_WINDOWS)
        if (SDL_SystemRAM <= 0) {
            MEMORYSTATUSEX stat;
            stat.dwLength = sizeof(stat);
            if (GlobalMemoryStatusEx(&stat)) {
                SDL_SystemRAM = (int)(stat.ullTotalPhys / (1024 * 1024));
            }
        }
#endif
#ifdef SDL_PLATFORM_RISCOS
        if (SDL_SystemRAM <= 0) {
            _kernel_swi_regs regs;
            regs.r[0] = 0x108;
            if (_kernel_swi(OS_Memory, &regs, &regs) == NULL) {
                SDL_SystemRAM = (int)(regs.r[1] * regs.r[2] / (1024 * 1024));
            }
        }
#endif
#ifdef SDL_PLATFORM_3DS
        if (SDL_SystemRAM <= 0) {
            // The New3DS has 255MiB, the Old3DS 127MiB
            SDL_SystemRAM = (int)(osGetMemRegionSize(MEMREGION_ALL) / (1024 * 1024));
        }
#endif
#ifdef SDL_PLATFORM_VITA
        if (SDL_SystemRAM <= 0) {
            /* Vita has 512MiB on SoC, that's split into 256MiB(+109MiB in extended memory mode) for app
               +26MiB of physically continuous memory, +112MiB of CDRAM(VRAM) + system reserved memory. */
            SDL_SystemRAM = 536870912;
        }
#endif
#ifdef SDL_PLATFORM_PS2
        if (SDL_SystemRAM <= 0) {
            // PlayStation 2 has 32MiB however there are some special models with 64 and 128
            SDL_SystemRAM = GetMemorySize();
        }
#endif
#ifdef SDL_PLATFORM_HAIKU
        if (SDL_SystemRAM <= 0) {
            system_info info;
            if (get_system_info(&info) == B_OK) {
                /* To have an accurate amount, we also take in account the inaccessible pages (aka ignored)
                  which is a bit handier compared to the legacy system's api (i.e. used_pages).*/
                SDL_SystemRAM = (int)SDL_round((info.max_pages + info.ignored_pages > 0 ? info.ignored_pages : 0) * B_PAGE_SIZE / 1048576.0);
            }
        }
#endif
    }
    return SDL_SystemRAM;
}
References NULL, SDL_round(), and SDL_SystemRAM.
SDL_HasAltiVec()
SDL_DECLSPEC bool SDLCALL SDL_HasAltiVec (void) extern
Determine whether the CPU has AltiVec features.
This always returns false on CPUs that aren't using PowerPC instruction sets.
Returns
true if the CPU has AltiVec features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_ALTIVEC);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_ALTIVEC.
SDL_HasARMSIMD()
SDL_DECLSPEC bool SDLCALL SDL_HasARMSIMD (void) extern
Determine whether the CPU has ARM SIMD (ARMv6) features.
This is different from ARM NEON, which is a different instruction set.
This always returns false on CPUs that aren't using ARM instruction sets.
Returns
true if the CPU has ARM SIMD features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasNEON
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_ARM_SIMD);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_ARM_SIMD.
SDL_HasAVX()
SDL_DECLSPEC bool SDLCALL SDL_HasAVX (void) extern
Determine whether the CPU has AVX features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has AVX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasAVX2
SDL_HasAVX512F
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_AVX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_AVX.
SDL_HasAVX2()
SDL_DECLSPEC bool SDLCALL SDL_HasAVX2 (void) extern
Determine whether the CPU has AVX2 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has AVX2 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasAVX
SDL_HasAVX512F
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_AVX2);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_AVX2.
SDL_HasAVX512F()
SDL_DECLSPEC bool SDLCALL SDL_HasAVX512F (void) extern
Determine whether the CPU has AVX-512F (foundation) features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has AVX-512F features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasAVX
SDL_HasAVX2
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_AVX512F);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_AVX512F.
SDL_HasLASX()
SDL_DECLSPEC bool SDLCALL SDL_HasLASX (void) extern
Determine whether the CPU has LASX (LOONGARCH SIMD) features.
This always returns false on CPUs that aren't using LOONGARCH instruction sets.
Returns
true if the CPU has LOONGARCH LASX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_LASX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_LASX.
SDL_HasLSX()
SDL_DECLSPEC bool SDLCALL SDL_HasLSX (void) extern
Determine whether the CPU has LSX (LOONGARCH SIMD) features.
This always returns false on CPUs that aren't using LOONGARCH instruction sets.
Returns
true if the CPU has LOONGARCH LSX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_LSX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_LSX.
SDL_HasMMX()
SDL_DECLSPEC bool SDLCALL SDL_HasMMX (void) extern
Determine whether the CPU has MMX features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has MMX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_MMX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_MMX.
SDL_HasNEON()
SDL_DECLSPEC bool SDLCALL SDL_HasNEON (void) extern
Determine whether the CPU has NEON (ARM SIMD) features.
This always returns false on CPUs that aren't using ARM instruction sets.
Returns
true if the CPU has ARM NEON features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_NEON);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_NEON.
Referenced by SDL_ChooseAudioConverters(), and SetupAudioResampler().
SDL_HasSSE()
SDL_DECLSPEC bool SDLCALL SDL_HasSSE (void) extern
Determine whether the CPU has SSE features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE2
SDL_HasSSE3
SDL_HasSSE41
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE.
Referenced by ConvertAudio(), SDL_BlitCopy(), SDL_FillSurfaceRects(), and SetupAudioResampler().
SDL_HasSSE2()
SDL_DECLSPEC bool SDLCALL SDL_HasSSE2 (void) extern
Determine whether the CPU has SSE2 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE2 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE3
SDL_HasSSE41
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE2);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE2.
Referenced by SDL_ChooseAudioConverters().
SDL_HasSSE3()
SDL_DECLSPEC bool SDLCALL SDL_HasSSE3 (void) extern
Determine whether the CPU has SSE3 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE3 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE2
SDL_HasSSE41
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE3);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE3.
Referenced by ConvertAudio().
SDL_HasSSE41()
SDL_DECLSPEC bool SDLCALL SDL_HasSSE41 (void) extern
Determine whether the CPU has SSE4.1 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE4.1 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE2
SDL_HasSSE3
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE41);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE41.
Referenced by SDL_ChooseAudioConverters().
SDL_HasSSE42()
SDL_DECLSPEC bool SDLCALL SDL_HasSSE42 (void) extern
Determine whether the CPU has SSE4.2 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE4.2 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE2
SDL_HasSSE3
SDL_HasSSE41
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE42);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE42.