SDL3: SDL-main/src/haptic/hidapi/SDL_hidapihaptic.h File Reference
SDL_hidapihaptic.h File Reference
Functions
void SDL_HIDAPI_HapticClose (SDL_Haptic *haptic)
void SDL_HIDAPI_HapticDestroyEffect (SDL_Haptic *haptic, SDL_HapticEffectID id)
bool SDL_HIDAPI_HapticGetEffectStatus (SDL_Haptic *haptic, SDL_HapticEffectID id)
bool SDL_HIDAPI_HapticInit (void)
bool SDL_HIDAPI_HapticIsHidapi (SDL_Haptic *haptic)
SDL_HapticEffectID SDL_HIDAPI_HapticNewEffect (SDL_Haptic *haptic, const SDL_HapticEffect *base)
bool SDL_HIDAPI_HapticOpenFromJoystick (SDL_Haptic *haptic, SDL_Joystick *joystick)
bool SDL_HIDAPI_HapticPause (SDL_Haptic *haptic)
void SDL_HIDAPI_HapticQuit (void)
bool SDL_HIDAPI_HapticResume (SDL_Haptic *haptic)
bool SDL_HIDAPI_HapticRunEffect (SDL_Haptic *haptic, SDL_HapticEffectID id, Uint32 iterations)
bool SDL_HIDAPI_HapticSetAutocenter (SDL_Haptic *haptic, int autocenter)
bool SDL_HIDAPI_HapticSetGain (SDL_Haptic *haptic, int gain)
bool SDL_HIDAPI_HapticStopAll (SDL_Haptic *haptic)
bool SDL_HIDAPI_HapticStopEffect (SDL_Haptic *haptic, SDL_HapticEffectID id)
bool SDL_HIDAPI_HapticUpdateEffect (SDL_Haptic *haptic, SDL_HapticEffectID id, const SDL_HapticEffect *data)
bool SDL_HIDAPI_JoystickIsHaptic (SDL_Joystick *joystick)
bool SDL_HIDAPI_JoystickSameHaptic (SDL_Haptic *haptic, SDL_Joystick *joystick)
Function Documentation
SDL_HIDAPI_HapticClose()
void SDL_HIDAPI_HapticClose (SDL_Haptic * haptic)
Referenced by SDL_CloseHaptic().
SDL_HIDAPI_HapticDestroyEffect()
void SDL_HIDAPI_HapticDestroyEffect (SDL_Haptic * haptic, SDL_HapticEffectID id)
Referenced by SDL_DestroyHapticEffect().
SDL_HIDAPI_HapticGetEffectStatus()
bool SDL_HIDAPI_HapticGetEffectStatus (SDL_Haptic * haptic, SDL_HapticEffectID id)
Referenced by SDL_GetHapticEffectStatus().
SDL_HIDAPI_HapticInit()
bool SDL_HIDAPI_HapticInit (void)
Referenced by SDL_InitHaptics().
SDL_HIDAPI_HapticIsHidapi()
bool SDL_HIDAPI_HapticIsHidapi (SDL_Haptic * haptic)
Referenced by SDL_CloseHaptic(), SDL_CreateHapticEffect(), SDL_DestroyHapticEffect(), SDL_GetHapticEffectStatus(), SDL_PauseHaptic(), SDL_ResumeHaptic(), SDL_RunHapticEffect(), SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_StopHapticEffect(), SDL_StopHapticEffects(), and SDL_UpdateHapticEffect().
SDL_HIDAPI_HapticNewEffect()
SDL_HapticEffectID SDL_HIDAPI_HapticNewEffect (SDL_Haptic * haptic, const SDL_HapticEffect * base)
Referenced by SDL_CreateHapticEffect().
SDL_HIDAPI_HapticOpenFromJoystick()
bool SDL_HIDAPI_HapticOpenFromJoystick (SDL_Haptic * haptic, SDL_Joystick * joystick)
Referenced by SDL_OpenHapticFromJoystick().
SDL_HIDAPI_HapticPause()
bool SDL_HIDAPI_HapticPause (SDL_Haptic * haptic)
Referenced by SDL_PauseHaptic().
SDL_HIDAPI_HapticQuit()
void SDL_HIDAPI_HapticQuit (void)
Referenced by SDL_QuitHaptics().
SDL_HIDAPI_HapticResume()
bool SDL_HIDAPI_HapticResume (SDL_Haptic * haptic)
Referenced by SDL_ResumeHaptic().
SDL_HIDAPI_HapticRunEffect()
bool SDL_HIDAPI_HapticRunEffect (SDL_Haptic * haptic, SDL_HapticEffectID id, Uint32 iterations)
Referenced by SDL_RunHapticEffect().
SDL_HIDAPI_HapticSetAutocenter()
bool SDL_HIDAPI_HapticSetAutocenter (SDL_Haptic * haptic, int autocenter)
Referenced by SDL_SetHapticAutocenter().
SDL_HIDAPI_HapticSetGain()
bool SDL_HIDAPI_HapticSetGain (SDL_Haptic * haptic, int gain)
Referenced by SDL_SetHapticGain().
SDL_HIDAPI_HapticStopAll()
bool SDL_HIDAPI_HapticStopAll (SDL_Haptic * haptic)
Referenced by SDL_StopHapticEffects().
SDL_HIDAPI_HapticStopEffect()
bool SDL_HIDAPI_HapticStopEffect (SDL_Haptic * haptic, SDL_HapticEffectID id)
Referenced by SDL_StopHapticEffect().
SDL_HIDAPI_HapticUpdateEffect()
bool SDL_HIDAPI_HapticUpdateEffect (SDL_Haptic * haptic, SDL_HapticEffectID id, const SDL_HapticEffect * data)
Referenced by SDL_UpdateHapticEffect().
SDL_HIDAPI_JoystickIsHaptic()
bool SDL_HIDAPI_JoystickIsHaptic (SDL_Joystick * joystick)
Referenced by SDL_IsJoystickHaptic(), and SDL_OpenHapticFromJoystick().
SDL_HIDAPI_JoystickSameHaptic()
bool SDL_HIDAPI_JoystickSameHaptic (SDL_Haptic * haptic, SDL_Joystick * joystick)
Referenced by SDL_OpenHapticFromJoystick().