SDL3: SDL-main/src/haptic/SDL_syshaptic.h File Reference
SDL_syshaptic.h File Reference
#include "SDL_internal.h"
Data Structures
struct haptic_effect
struct SDL_Haptic
Functions
void SDL_SYS_HapticClose (SDL_Haptic *haptic)
void SDL_SYS_HapticDestroyEffect (SDL_Haptic *haptic, struct haptic_effect *effect)
int SDL_SYS_HapticGetEffectStatus (SDL_Haptic *haptic, struct haptic_effect *effect)
bool SDL_SYS_HapticInit (void)
SDL_HapticID SDL_SYS_HapticInstanceID (int index)
int SDL_SYS_HapticMouse (void)
const char * SDL_SYS_HapticName (int index)
bool SDL_SYS_HapticNewEffect (SDL_Haptic *haptic, struct haptic_effect *effect, const SDL_HapticEffect *base)
bool SDL_SYS_HapticOpen (SDL_Haptic *haptic)
bool SDL_SYS_HapticOpenFromJoystick (SDL_Haptic *haptic, SDL_Joystick *joystick)
bool SDL_SYS_HapticPause (SDL_Haptic *haptic)
void SDL_SYS_HapticQuit (void)
bool SDL_SYS_HapticResume (SDL_Haptic *haptic)
bool SDL_SYS_HapticRunEffect (SDL_Haptic *haptic, struct haptic_effect *effect, Uint32 iterations)
bool SDL_SYS_HapticSetAutocenter (SDL_Haptic *haptic, int autocenter)
bool SDL_SYS_HapticSetGain (SDL_Haptic *haptic, int gain)
bool SDL_SYS_HapticStopAll (SDL_Haptic *haptic)
bool SDL_SYS_HapticStopEffect (SDL_Haptic *haptic, struct haptic_effect *effect)
bool SDL_SYS_HapticUpdateEffect (SDL_Haptic *haptic, struct haptic_effect *effect, const SDL_HapticEffect *data)
bool SDL_SYS_JoystickIsHaptic (SDL_Joystick *joystick)
bool SDL_SYS_JoystickSameHaptic (SDL_Haptic *haptic, SDL_Joystick *joystick)
int SDL_SYS_NumHaptics (void)
Function Documentation
SDL_SYS_HapticClose()
void SDL_SYS_HapticClose (SDL_Haptic * haptic) extern
Referenced by SDL_CloseHaptic().
SDL_SYS_HapticDestroyEffect()
void SDL_SYS_HapticDestroyEffect (SDL_Haptic * haptic, struct haptic_effect * effect) extern
Referenced by SDL_DestroyHapticEffect().
SDL_SYS_HapticGetEffectStatus()
int SDL_SYS_HapticGetEffectStatus (SDL_Haptic * haptic, struct haptic_effect * effect) extern
Referenced by SDL_GetHapticEffectStatus().
SDL_SYS_HapticInit()
bool SDL_SYS_HapticInit (void) extern
Referenced by SDL_InitHaptics().
SDL_SYS_HapticInstanceID()
SDL_HapticID SDL_SYS_HapticInstanceID (int index) extern
Referenced by SDL_GetHapticIndex(), and SDL_GetHaptics().
SDL_SYS_HapticMouse()
int SDL_SYS_HapticMouse (void) extern
Referenced by SDL_IsMouseHaptic(), and SDL_OpenHapticFromMouse().
SDL_SYS_HapticName()
const char * SDL_SYS_HapticName (int index) extern
Referenced by SDL_GetHapticNameForID(), and SDL_OpenHaptic().
SDL_SYS_HapticNewEffect()
bool SDL_SYS_HapticNewEffect (SDL_Haptic * haptic, struct haptic_effect * effect, const SDL_HapticEffect * base) extern
Referenced by SDL_CreateHapticEffect().
SDL_SYS_HapticOpen()
bool SDL_SYS_HapticOpen (SDL_Haptic * haptic) extern
Referenced by SDL_OpenHaptic().
SDL_SYS_HapticOpenFromJoystick()
bool SDL_SYS_HapticOpenFromJoystick (SDL_Haptic * haptic, SDL_Joystick * joystick) extern
Referenced by SDL_OpenHapticFromJoystick().
SDL_SYS_HapticPause()
bool SDL_SYS_HapticPause (SDL_Haptic * haptic) extern
Referenced by SDL_PauseHaptic().
SDL_SYS_HapticQuit()
void SDL_SYS_HapticQuit (void) extern
Referenced by SDL_InitHaptics(), and SDL_QuitHaptics().
SDL_SYS_HapticResume()
bool SDL_SYS_HapticResume (SDL_Haptic * haptic) extern
Referenced by SDL_ResumeHaptic().
SDL_SYS_HapticRunEffect()
bool SDL_SYS_HapticRunEffect (SDL_Haptic * haptic, struct haptic_effect * effect, Uint32 iterations) extern
Referenced by SDL_RunHapticEffect().
SDL_SYS_HapticSetAutocenter()
bool SDL_SYS_HapticSetAutocenter (SDL_Haptic * haptic, int autocenter) extern
Referenced by SDL_SetHapticAutocenter().
SDL_SYS_HapticSetGain()
bool SDL_SYS_HapticSetGain (SDL_Haptic * haptic, int gain) extern
Referenced by SDL_SetHapticGain().
SDL_SYS_HapticStopAll()
bool SDL_SYS_HapticStopAll (SDL_Haptic * haptic) extern
Referenced by SDL_StopHapticEffects().
SDL_SYS_HapticStopEffect()
bool SDL_SYS_HapticStopEffect (SDL_Haptic * haptic, struct haptic_effect * effect) extern
Referenced by SDL_StopHapticEffect().
SDL_SYS_HapticUpdateEffect()
bool SDL_SYS_HapticUpdateEffect (SDL_Haptic * haptic, struct haptic_effect * effect, const SDL_HapticEffect * data) extern
Referenced by SDL_UpdateHapticEffect().
SDL_SYS_JoystickIsHaptic()
bool SDL_SYS_JoystickIsHaptic (SDL_Joystick * joystick) extern
Referenced by SDL_IsJoystickHaptic().
SDL_SYS_JoystickSameHaptic()
bool SDL_SYS_JoystickSameHaptic (SDL_Haptic * haptic, SDL_Joystick * joystick) extern
Referenced by SDL_OpenHapticFromJoystick().
SDL_SYS_NumHaptics()
int SDL_SYS_NumHaptics (void) extern
Referenced by SDL_GetHapticIndex(), and SDL_GetHaptics().