SDL3: SDL-main/src/joystick/apple/SDL_mfijoystick.m File Reference
SDL_mfijoystick.m File Reference
#include "SDL_internal.h"
#include "../SDL_sysjoystick.h"
#include "../SDL_joystick_c.h"
#include "../hidapi/SDL_hidapijoystick_c.h"
#include "../usb_ids.h"
#include "../../events/SDL_events_c.h"
#include "SDL_mfijoystick_c.h"
import <GameController/GameController.h>
Functions
static SDL_JoystickDeviceItem * GetDeviceForIndex (int device_index)
const char * IOS_GetAppleSFSymbolsNameForAxis (SDL_Gamepad *gamepad, SDL_GamepadAxis axis)
const char * IOS_GetAppleSFSymbolsNameForButton (SDL_Gamepad *gamepad, SDL_GamepadButton button)
static void IOS_JoystickClose (SDL_Joystick *joystick)
static void IOS_JoystickDetect (void)
static int IOS_JoystickGetCount (void)
static SDL_GUID IOS_JoystickGetDeviceGUID (int device_index)
static SDL_JoystickID IOS_JoystickGetDeviceInstanceID (int device_index)
static const char * IOS_JoystickGetDeviceName (int device_index)
static const char * IOS_JoystickGetDevicePath (int device_index)
static int IOS_JoystickGetDevicePlayerIndex (int device_index)
static int IOS_JoystickGetDeviceSteamVirtualGamepadSlot (int device_index)
static bool IOS_JoystickGetGamepadMapping (int device_index, SDL_GamepadMapping *out)
static bool IOS_JoystickInit (void)
static bool IOS_JoystickIsDevicePresent (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
static bool IOS_JoystickOpen (SDL_Joystick *joystick, int device_index)
static void IOS_JoystickQuit (void)
static bool IOS_JoystickRumble (SDL_Joystick *joystick, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble)
static bool IOS_JoystickRumbleTriggers (SDL_Joystick *joystick, Uint16 left_rumble, Uint16 right_rumble)
static bool IOS_JoystickSendEffect (SDL_Joystick *joystick, const void *data, int size)
static void IOS_JoystickSetDevicePlayerIndex (int device_index, int player_index)
static bool IOS_JoystickSetLED (SDL_Joystick *joystick, Uint8 red, Uint8 green, Uint8 blue)
static bool IOS_JoystickSetSensorsEnabled (SDL_Joystick *joystick, bool enabled)
static void IOS_JoystickUpdate (SDL_Joystick *joystick)
static void IOS_MFIJoystickUpdate (SDL_Joystick *joystick)
static SDL_JoystickDeviceItem * IOS_RemoveJoystickDevice (SDL_JoystickDeviceItem *device)
Variables
static SDL_JoystickDeviceItem * deviceList = NULL
static int numjoysticks = 0
int SDL_AppleTVRemoteOpenedAsJoystick = 0
SDL_JoystickDriver SDL_IOS_JoystickDriver
Function Documentation
GetDeviceForIndex()
SDL_JoystickDeviceItem * GetDeviceForIndex (int device_index) static
{
    SDL_JoystickDeviceItem *device = deviceList;
    int i = 0;
    while (i < device_index) {
        if (device == NULL) {
            return NULL;
        }
        device = device->next;
        i++;
    }
    return device;
}
References deviceList, joystick_hwdata::next, and NULL.
Referenced by IOS_JoystickGetDeviceGUID(), IOS_JoystickGetDeviceInstanceID(), IOS_JoystickGetDeviceName(), IOS_JoystickGetDevicePlayerIndex(), IOS_JoystickGetGamepadMapping(), IOS_JoystickOpen(), and IOS_JoystickSetDevicePlayerIndex().
IOS_GetAppleSFSymbolsNameForAxis()
const char * IOS_GetAppleSFSymbolsNameForAxis (SDL_Gamepad * gamepad, SDL_GamepadAxis axis)
{
    char elementName[256];
    elementName[0] = '\0';
#ifdef SDL_JOYSTICK_MFI
    if (gamepad && SDL_GetGamepadJoystick(gamepad)->driver == &SDL_IOS_JoystickDriver) {
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCController *controller = SDL_GetGamepadJoystick(gamepad)->hwdata->controller;
            NSDictionary<NSString *, GCControllerElement *> *elements = controller.physicalInputProfile.elements;
            switch (axis) {
            case SDL_GAMEPAD_AXIS_LEFTX:
                GetAppleSFSymbolsNameForElement(elements[GCInputLeftThumbstick], elementName);
                break;
            case SDL_GAMEPAD_AXIS_LEFTY:
                GetAppleSFSymbolsNameForElement(elements[GCInputLeftThumbstick], elementName);
                break;
            case SDL_GAMEPAD_AXIS_RIGHTX:
                GetAppleSFSymbolsNameForElement(elements[GCInputRightThumbstick], elementName);
                break;
            case SDL_GAMEPAD_AXIS_RIGHTY:
                GetAppleSFSymbolsNameForElement(elements[GCInputRightThumbstick], elementName);
                break;
            case SDL_GAMEPAD_AXIS_LEFT_TRIGGER:
                GetAppleSFSymbolsNameForElement(elements[GCInputLeftTrigger], elementName);
                break;
            case SDL_GAMEPAD_AXIS_RIGHT_TRIGGER:
                GetAppleSFSymbolsNameForElement(elements[GCInputRightTrigger], elementName);
                break;
            default:
                break;
            }
        }
    }
#endif // SDL_JOYSTICK_MFI
    return *elementName ? SDL_GetPersistentString(elementName) : NULL;
}
References NULL, SDL_GAMEPAD_AXIS_LEFT_TRIGGER, SDL_GAMEPAD_AXIS_LEFTX, SDL_GAMEPAD_AXIS_LEFTY, SDL_GAMEPAD_AXIS_RIGHT_TRIGGER, SDL_GAMEPAD_AXIS_RIGHTX, SDL_GAMEPAD_AXIS_RIGHTY, SDL_GetGamepadJoystick(), SDL_GetPersistentString(), and SDL_IOS_JoystickDriver.
Referenced by SDL_GetGamepadAppleSFSymbolsNameForAxis().
IOS_GetAppleSFSymbolsNameForButton()
const char * IOS_GetAppleSFSymbolsNameForButton (SDL_Gamepad * gamepad, SDL_GamepadButton button)
{
    char elementName[256];
    elementName[0] = '\0';
#ifdef SDL_JOYSTICK_MFI
    if (gamepad && SDL_GetGamepadJoystick(gamepad)->driver == &SDL_IOS_JoystickDriver) {
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCController *controller = SDL_GetGamepadJoystick(gamepad)->hwdata->controller;
            NSDictionary<NSString *, GCControllerElement *> *elements = controller.physicalInputProfile.elements;
            switch (button) {
            case SDL_GAMEPAD_BUTTON_SOUTH:
                GetAppleSFSymbolsNameForElement(elements[GCInputButtonA], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_EAST:
                GetAppleSFSymbolsNameForElement(elements[GCInputButtonB], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_WEST:
                GetAppleSFSymbolsNameForElement(elements[GCInputButtonX], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_NORTH:
                GetAppleSFSymbolsNameForElement(elements[GCInputButtonY], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_BACK:
                GetAppleSFSymbolsNameForElement(elements[GCInputButtonOptions], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_GUIDE:
                GetAppleSFSymbolsNameForElement(elements[@"Button Home"], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_START:
                GetAppleSFSymbolsNameForElement(elements[GCInputButtonMenu], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_LEFT_STICK:
                GetAppleSFSymbolsNameForElement(elements[GCInputLeftThumbstickButton], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_RIGHT_STICK:
                GetAppleSFSymbolsNameForElement(elements[GCInputRightThumbstickButton], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_LEFT_SHOULDER:
                GetAppleSFSymbolsNameForElement(elements[GCInputLeftShoulder], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER:
                GetAppleSFSymbolsNameForElement(elements[GCInputRightShoulder], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_DPAD_UP:
            {
                GCControllerDirectionPad *dpad = GetDirectionalPadForController(controller);
                if (dpad) {
                    GetAppleSFSymbolsNameForElement(dpad.up, elementName);
                    if (SDL_strlen(elementName) == 0) {
                        SDL_strlcpy(elementName, "dpad.up.fill", sizeof(elementName));
                    }
                }
                break;
            }
            case SDL_GAMEPAD_BUTTON_DPAD_DOWN:
            {
                GCControllerDirectionPad *dpad = GetDirectionalPadForController(controller);
                if (dpad) {
                    GetAppleSFSymbolsNameForElement(dpad.down, elementName);
                    if (SDL_strlen(elementName) == 0) {
                        SDL_strlcpy(elementName, "dpad.down.fill", sizeof(elementName));
                    }
                }
                break;
            }
            case SDL_GAMEPAD_BUTTON_DPAD_LEFT:
            {
                GCControllerDirectionPad *dpad = GetDirectionalPadForController(controller);
                if (dpad) {
                    GetAppleSFSymbolsNameForElement(dpad.left, elementName);
                    if (SDL_strlen(elementName) == 0) {
                        SDL_strlcpy(elementName, "dpad.left.fill", sizeof(elementName));
                    }
                }
                break;
            }
            case SDL_GAMEPAD_BUTTON_DPAD_RIGHT:
            {
                GCControllerDirectionPad *dpad = GetDirectionalPadForController(controller);
                if (dpad) {
                    GetAppleSFSymbolsNameForElement(dpad.right, elementName);
                    if (SDL_strlen(elementName) == 0) {
                        SDL_strlcpy(elementName, "dpad.right.fill", sizeof(elementName));
                    }
                }
                break;
            }
            case SDL_GAMEPAD_BUTTON_MISC1:
                GetAppleSFSymbolsNameForElement(elements[GCInputDualShockTouchpadButton], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1:
                GetAppleSFSymbolsNameForElement(elements[GCInputXboxPaddleOne], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_LEFT_PADDLE1:
                GetAppleSFSymbolsNameForElement(elements[GCInputXboxPaddleThree], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2:
                GetAppleSFSymbolsNameForElement(elements[GCInputXboxPaddleTwo], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_LEFT_PADDLE2:
                GetAppleSFSymbolsNameForElement(elements[GCInputXboxPaddleFour], elementName);
                break;
            case SDL_GAMEPAD_BUTTON_TOUCHPAD:
                GetAppleSFSymbolsNameForElement(elements[GCInputDualShockTouchpadButton], elementName);
                break;
            default:
                break;
            }
        }
    }
#endif // SDL_JOYSTICK_MFI
    return *elementName ? SDL_GetPersistentString(elementName) : NULL;
}
References NULL, SDL_GAMEPAD_BUTTON_BACK, SDL_GAMEPAD_BUTTON_DPAD_DOWN, SDL_GAMEPAD_BUTTON_DPAD_LEFT, SDL_GAMEPAD_BUTTON_DPAD_RIGHT, SDL_GAMEPAD_BUTTON_DPAD_UP, SDL_GAMEPAD_BUTTON_EAST, SDL_GAMEPAD_BUTTON_GUIDE, SDL_GAMEPAD_BUTTON_LEFT_PADDLE1, SDL_GAMEPAD_BUTTON_LEFT_PADDLE2, SDL_GAMEPAD_BUTTON_LEFT_SHOULDER, SDL_GAMEPAD_BUTTON_LEFT_STICK, SDL_GAMEPAD_BUTTON_MISC1, SDL_GAMEPAD_BUTTON_NORTH, SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1, SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2, SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER, SDL_GAMEPAD_BUTTON_RIGHT_STICK, SDL_GAMEPAD_BUTTON_SOUTH, SDL_GAMEPAD_BUTTON_START, SDL_GAMEPAD_BUTTON_TOUCHPAD, SDL_GAMEPAD_BUTTON_WEST, SDL_GetGamepadJoystick(), SDL_GetPersistentString(), SDL_IOS_JoystickDriver, SDL_strlcpy(), and SDL_strlen().
Referenced by SDL_GetGamepadAppleSFSymbolsNameForButton().
IOS_JoystickClose()
void IOS_JoystickClose (SDL_Joystick * joystick) static
{
    SDL_JoystickDeviceItem *device = joystick->hwdata;
    if (device == NULL) {
        return;
    }
    device->joystick = NULL;
#ifdef SDL_JOYSTICK_MFI
    @autoreleasepool {
        if (device->rumble) {
            SDL3_RumbleContext *rumble = (__bridge SDL3_RumbleContext *)device->rumble;
            [rumble cleanup];
            CFRelease(device->rumble);
            device->rumble = NULL;
        }
        if (device->controller) {
            GCController *controller = device->controller;
            controller.controllerPausedHandler = nil;
            controller.playerIndex = -1;
            if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
                for (id key in controller.physicalInputProfile.buttons) {
                    GCControllerButtonInput *button = controller.physicalInputProfile.buttons[key];
                    if ([button isBoundToSystemGesture]) {
                        button.preferredSystemGestureState = GCSystemGestureStateEnabled;
                    }
                }
            }
        }
    }
#endif // SDL_JOYSTICK_MFI
    if (device->is_siri_remote) {
        --SDL_AppleTVRemoteOpenedAsJoystick;
    }
}
References joystick_hwdata::controller, joystick_hwdata::is_siri_remote, joystick_hwdata::joystick, NULL, joystick_hwdata::rumble, and SDL_AppleTVRemoteOpenedAsJoystick.
IOS_JoystickDetect()
void IOS_JoystickDetect (void) static
{
}
IOS_JoystickGetCount()
int IOS_JoystickGetCount (void) static
{
    return numjoysticks;
}
References numjoysticks.
IOS_JoystickGetDeviceGUID()
SDL_GUID IOS_JoystickGetDeviceGUID (int device_index) static
{
    SDL_JoystickDeviceItem *device = GetDeviceForIndex(device_index);
    SDL_GUID guid;
    if (device) {
        guid = device->guid;
    } else {
        SDL_zero(guid);
    }
    return guid;
}
References GetDeviceForIndex(), joystick_hwdata::guid, and SDL_zero.
IOS_JoystickGetDeviceInstanceID()
SDL_JoystickID IOS_JoystickGetDeviceInstanceID (int device_index) static
{
    SDL_JoystickDeviceItem *device = GetDeviceForIndex(device_index);
    return device ? device->instance_id : 0;
}
References GetDeviceForIndex(), and joystick_hwdata::instance_id.
IOS_JoystickGetDeviceName()
const char * IOS_JoystickGetDeviceName (int device_index) static
{
    SDL_JoystickDeviceItem *device = GetDeviceForIndex(device_index);
    return device ? device->name : "Unknown";
}
References GetDeviceForIndex(), and joystick_hwdata::name.
IOS_JoystickGetDevicePath()
const char * IOS_JoystickGetDevicePath (int device_index) static
{
    return NULL;
}
References NULL.
IOS_JoystickGetDevicePlayerIndex()
int IOS_JoystickGetDevicePlayerIndex (int device_index) static
{
#ifdef SDL_JOYSTICK_MFI
    SDL_JoystickDeviceItem *device = GetDeviceForIndex(device_index);
    if (device && device->controller) {
        return (int)device->controller.playerIndex;
    }
#endif
    return -1;
}
References joystick_hwdata::controller, and GetDeviceForIndex().
IOS_JoystickGetDeviceSteamVirtualGamepadSlot()
int IOS_JoystickGetDeviceSteamVirtualGamepadSlot (int device_index) static
{
    return -1;
}
IOS_JoystickGetGamepadMapping()
bool IOS_JoystickGetGamepadMapping (int device_index, SDL_GamepadMapping * out) static
{
    SDL_JoystickDeviceItem *device = GetDeviceForIndex(device_index);
    if (device == NULL) {
        return false;
    }
    if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
        int axis = 0;
        for (id key in device->axes) {
            if ([(NSString *)key isEqualToString:@"Left Thumbstick X Axis"] ||
                [(NSString *)key isEqualToString:@"Direction Pad X Axis"]) {
                out->leftx.kind = EMappingKind_Axis;
                out->leftx.target = axis;
            } else if ([(NSString *)key isEqualToString:@"Left Thumbstick Y Axis"] ||
                       [(NSString *)key isEqualToString:@"Direction Pad Y Axis"]) {
                out->lefty.kind = EMappingKind_Axis;
                out->lefty.target = axis;
                out->lefty.axis_reversed = true;
            } else if ([(NSString *)key isEqualToString:@"Right Thumbstick X Axis"]) {
                out->rightx.kind = EMappingKind_Axis;
                out->rightx.target = axis;
            } else if ([(NSString *)key isEqualToString:@"Right Thumbstick Y Axis"]) {
                out->righty.kind = EMappingKind_Axis;
                out->righty.target = axis;
                out->righty.axis_reversed = true;
            } else if ([(NSString *)key isEqualToString:GCInputLeftTrigger]) {
                out->lefttrigger.kind = EMappingKind_Axis;
                out->lefttrigger.target = axis;
                out->lefttrigger.half_axis_positive = true;
            } else if ([(NSString *)key isEqualToString:GCInputRightTrigger]) {
                out->righttrigger.kind = EMappingKind_Axis;
                out->righttrigger.target = axis;
                out->righttrigger.half_axis_positive = true;
            }
            ++axis;
        }
        int button = 0;
        for (id key in device->buttons) {
            SDL_InputMapping *mapping = NULL;
            if ([(NSString *)key isEqualToString:GCInputButtonA]) {
                if (device->is_siri_remote > 1) {
                    // GCInputButtonA is triggered for any D-Pad press, ignore it in favor of "Button Center"
                } else if (device->has_nintendo_buttons) {
                    mapping = &out->b;
                } else {
                    mapping = &out->a;
                }
            } else if ([(NSString *)key isEqualToString:GCInputButtonB]) {
                if (device->has_nintendo_buttons) {
                    mapping = &out->a;
                } else if (device->is_switch_joyconL || device->is_switch_joyconR) {
                    mapping = &out->x;
                } else {
                    mapping = &out->b;
                }
            } else if ([(NSString *)key isEqualToString:GCInputButtonX]) {
                if (device->has_nintendo_buttons) {
                    mapping = &out->y;
                } else if (device->is_switch_joyconL || device->is_switch_joyconR) {
                    mapping = &out->b;
                } else {
                    mapping = &out->x;
                }
            } else if ([(NSString *)key isEqualToString:GCInputButtonY]) {
                if (device->has_nintendo_buttons) {
                    mapping = &out->x;
                } else {
                    mapping = &out->y;
                }
            } else if ([(NSString *)key isEqualToString:@"Direction Pad Left"]) {
                mapping = &out->dpleft;
            } else if ([(NSString *)key isEqualToString:@"Direction Pad Right"]) {
                mapping = &out->dpright;
            } else if ([(NSString *)key isEqualToString:@"Direction Pad Up"]) {
                mapping = &out->dpup;
            } else if ([(NSString *)key isEqualToString:@"Direction Pad Down"]) {
                mapping = &out->dpdown;
            } else if ([(NSString *)key isEqualToString:@"Cardinal Direction Pad Left"]) {
                mapping = &out->dpleft;
            } else if ([(NSString *)key isEqualToString:@"Cardinal Direction Pad Right"]) {
                mapping = &out->dpright;
            } else if ([(NSString *)key isEqualToString:@"Cardinal Direction Pad Up"]) {
                mapping = &out->dpup;
            } else if ([(NSString *)key isEqualToString:@"Cardinal Direction Pad Down"]) {
                mapping = &out->dpdown;
            } else if ([(NSString *)key isEqualToString:GCInputLeftShoulder]) {
                mapping = &out->leftshoulder;
            } else if ([(NSString *)key isEqualToString:GCInputRightShoulder]) {
                mapping = &out->rightshoulder;
            } else if ([(NSString *)key isEqualToString:GCInputLeftThumbstickButton]) {
                mapping = &out->leftstick;
            } else if ([(NSString *)key isEqualToString:GCInputRightThumbstickButton]) {
                mapping = &out->rightstick;
            } else if ([(NSString *)key isEqualToString:@"Button Home"]) {
                mapping = &out->guide;
            } else if ([(NSString *)key isEqualToString:GCInputButtonMenu]) {
                if (device->is_siri_remote) {
                    mapping = &out->b;
                } else {
                    mapping = &out->start;
                }
            } else if ([(NSString *)key isEqualToString:GCInputButtonOptions]) {
                mapping = &out->back;
            } else if ([(NSString *)key isEqualToString:@"Button Share"]) {
                mapping = &out->misc1;
            } else if ([(NSString *)key isEqualToString:GCInputXboxPaddleOne]) {
                mapping = &out->right_paddle1;
            } else if ([(NSString *)key isEqualToString:GCInputXboxPaddleTwo]) {
                mapping = &out->right_paddle2;
            } else if ([(NSString *)key isEqualToString:GCInputXboxPaddleThree]) {
                mapping = &out->left_paddle1;
            } else if ([(NSString *)key isEqualToString:GCInputXboxPaddleFour]) {
                mapping = &out->left_paddle2;
            } else if ([(NSString *)key isEqualToString:GCInputLeftTrigger]) {
                mapping = &out->lefttrigger;
            } else if ([(NSString *)key isEqualToString:GCInputRightTrigger]) {
                mapping = &out->righttrigger;
            } else if ([(NSString *)key isEqualToString:GCInputDualShockTouchpadButton]) {
                mapping = &out->touchpad;
            } else if ([(NSString *)key isEqualToString:@"Button Center"]) {
                mapping = &out->a;
            }
            if (mapping && mapping->kind == EMappingKind_None) {
                mapping->kind = EMappingKind_Button;
                mapping->target = button;
            }
            ++button;
        }
        return true;
    }
    return false;
}
References SDL_GamepadMapping::a, joystick_hwdata::axes, SDL_InputMapping::axis_reversed, SDL_GamepadMapping::b, SDL_GamepadMapping::back, joystick_hwdata::buttons, SDL_GamepadMapping::dpdown, SDL_GamepadMapping::dpleft, SDL_GamepadMapping::dpright, SDL_GamepadMapping::dpup, EMappingKind_Axis, EMappingKind_Button, EMappingKind_None, GetDeviceForIndex(), SDL_GamepadMapping::guide, SDL_InputMapping::half_axis_positive, joystick_hwdata::has_nintendo_buttons, joystick_hwdata::is_siri_remote, joystick_hwdata::is_switch_joyconL, joystick_hwdata::is_switch_joyconR, SDL_InputMapping::kind, SDL_GamepadMapping::left_paddle1, SDL_GamepadMapping::left_paddle2, SDL_GamepadMapping::leftshoulder, SDL_GamepadMapping::leftstick, SDL_GamepadMapping::lefttrigger, SDL_GamepadMapping::leftx, SDL_GamepadMapping::lefty, SDL_GamepadMapping::misc1, NULL, SDL_GamepadMapping::right_paddle1, SDL_GamepadMapping::right_paddle2, SDL_GamepadMapping::rightshoulder, SDL_GamepadMapping::rightstick, SDL_GamepadMapping::righttrigger, SDL_GamepadMapping::rightx, SDL_GamepadMapping::righty, SDL_GamepadMapping::start, SDL_InputMapping::target, SDL_GamepadMapping::touchpad, SDL_GamepadMapping::x, and SDL_GamepadMapping::y.
IOS_JoystickInit()
bool IOS_JoystickInit (void) static
{
    if (!SDL_GetHintBoolean(SDL_HINT_JOYSTICK_MFI, true)) {
        return true;
    }
#ifdef SDL_PLATFORM_MACOS
    if (@available(macOS 10.16, *)) {
        // Continue with initialization on macOS 11+
    } else {
        return true;
    }
#endif
    @autoreleasepool {
#ifdef SDL_JOYSTICK_MFI
        NSNotificationCenter *center;
#endif
#ifdef SDL_JOYSTICK_MFI
        // GameController.framework was added in iOS 7.
        if (![GCController class]) {
            return true;
        }
        /* For whatever reason, this always returns an empty array on
         macOS 11.0.1 */
        for (GCController *controller in [GCController controllers]) {
            IOS_AddJoystickDevice(controller);
        }
#ifdef SDL_PLATFORM_TVOS
        SDL_AddHintCallback(SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION,
                            SDL_AppleTVRemoteRotationHintChanged, NULL);
#endif // SDL_PLATFORM_TVOS
        center = [NSNotificationCenter defaultCenter];
        connectObserver = [center addObserverForName:GCControllerDidConnectNotification
                                              object:nil
                                               queue:nil
                                          usingBlock:^(NSNotification *note) {
                                            GCController *controller = note.object;
                                            SDL_LockJoysticks();
                                            IOS_AddJoystickDevice(controller);
                                            SDL_UnlockJoysticks();
                                          }];
        disconnectObserver = [center addObserverForName:GCControllerDidDisconnectNotification
                                                 object:nil
                                                  queue:nil
                                             usingBlock:^(NSNotification *note) {
                                               GCController *controller = note.object;
                                               SDL_JoystickDeviceItem *device;
                                               SDL_LockJoysticks();
                                               for (device = deviceList; device != NULL; device = device->next) {
                                                   if (device->controller == controller) {
                                                       IOS_RemoveJoystickDevice(device);
                                                       break;
                                                   }
                                               }
                                               SDL_UnlockJoysticks();
                                             }];
#endif // SDL_JOYSTICK_MFI
    }
    return true;
}
References NULL, SDL_AddHintCallback(), SDL_GetHintBoolean(), SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION, and SDL_HINT_JOYSTICK_MFI.
IOS_JoystickIsDevicePresent()
bool IOS_JoystickIsDevicePresent (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char * name) static
{
    // We don't override any other drivers through this method
    return false;
}
IOS_JoystickOpen()
bool IOS_JoystickOpen (SDL_Joystick * joystick, int device_index) static
{
    SDL_JoystickDeviceItem *device = GetDeviceForIndex(device_index);
    if (device == NULL) {
        return SDL_SetError("Could not open Joystick: no hardware device for the specified index");
    }
    joystick->hwdata = device;
    joystick->naxes = device->naxes;
    joystick->nhats = device->nhats;
    joystick->nbuttons = device->nbuttons;
    if (device->has_dualshock_touchpad) {
        SDL_PrivateJoystickAddTouchpad(joystick, 2);
    }
    device->joystick = joystick;
    @autoreleasepool {
#ifdef SDL_JOYSTICK_MFI
        if (device->pause_button_index >= 0) {
            GCController *controller = device->controller;
            controller.controllerPausedHandler = ^(GCController *c) {
              if (joystick->hwdata) {
                  joystick->hwdata->pause_button_pressed = SDL_GetTicks();
              }
            };
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCController *controller = joystick->hwdata->controller;
            GCMotion *motion = controller.motion;
            if (motion && motion.hasRotationRate) {
                SDL_PrivateJoystickAddSensor(joystick, SDL_SENSOR_GYRO, 0.0f);
            }
            if (motion && motion.hasGravityAndUserAcceleration) {
                SDL_PrivateJoystickAddSensor(joystick, SDL_SENSOR_ACCEL, 0.0f);
            }
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCController *controller = joystick->hwdata->controller;
            for (id key in controller.physicalInputProfile.buttons) {
                GCControllerButtonInput *button = controller.physicalInputProfile.buttons[key];
                if ([button isBoundToSystemGesture]) {
                    button.preferredSystemGestureState = GCSystemGestureStateDisabled;
                }
            }
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCController *controller = device->controller;
            if (controller.light) {
                SDL_SetBooleanProperty(SDL_GetJoystickProperties(joystick), SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN, true);
            }
            if (controller.haptics) {
                for (GCHapticsLocality locality in controller.haptics.supportedLocalities) {
                    if ([locality isEqualToString:GCHapticsLocalityHandles]) {
                        SDL_SetBooleanProperty(SDL_GetJoystickProperties(joystick), SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN, true);
                    } else if ([locality isEqualToString:GCHapticsLocalityTriggers]) {
                        SDL_SetBooleanProperty(SDL_GetJoystickProperties(joystick), SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN, true);
                    }
                }
            }
        }
#endif // SDL_JOYSTICK_MFI
    }
    if (device->is_siri_remote) {
        ++SDL_AppleTVRemoteOpenedAsJoystick;
    }
    return true;
}
References joystick_hwdata::controller, GetDeviceForIndex(), joystick_hwdata::has_dualshock_touchpad, joystick_hwdata::is_siri_remote, joystick_hwdata::joystick, joystick_hwdata::naxes, joystick_hwdata::nbuttons, joystick_hwdata::nhats, NULL, joystick_hwdata::pause_button_index, SDL_AppleTVRemoteOpenedAsJoystick, SDL_GetJoystickProperties(), SDL_GetTicks(), SDL_PrivateJoystickAddSensor(), SDL_PrivateJoystickAddTouchpad(), SDL_PROP_JOYSTICK_CAP_RGB_LED_BOOLEAN, SDL_PROP_JOYSTICK_CAP_RUMBLE_BOOLEAN, SDL_PROP_JOYSTICK_CAP_TRIGGER_RUMBLE_BOOLEAN, SDL_SENSOR_ACCEL, SDL_SENSOR_GYRO, SDL_SetBooleanProperty(), and SDL_SetError().
IOS_JoystickQuit()
void IOS_JoystickQuit (void) static
{
    @autoreleasepool {
#ifdef SDL_JOYSTICK_MFI
        NSNotificationCenter *center = [NSNotificationCenter defaultCenter];
        if (connectObserver) {
            [center removeObserver:connectObserver name:GCControllerDidConnectNotification object:nil];
            connectObserver = nil;
        }
        if (disconnectObserver) {
            [center removeObserver:disconnectObserver name:GCControllerDidDisconnectNotification object:nil];
            disconnectObserver = nil;
        }
#ifdef SDL_PLATFORM_TVOS
        SDL_RemoveHintCallback(SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION,
                            SDL_AppleTVRemoteRotationHintChanged, NULL);
#endif // SDL_PLATFORM_TVOS
#endif // SDL_JOYSTICK_MFI
        while (deviceList != NULL) {
            IOS_RemoveJoystickDevice(deviceList);
        }
    }
    numjoysticks = 0;
}
References deviceList, IOS_RemoveJoystickDevice(), NULL, numjoysticks, SDL_HINT_APPLE_TV_REMOTE_ALLOW_ROTATION, and SDL_RemoveHintCallback().
IOS_JoystickRumble()
bool IOS_JoystickRumble (SDL_Joystick * joystick, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble) static
{
#ifdef SDL_JOYSTICK_MFI
    SDL_JoystickDeviceItem *device = joystick->hwdata;
    if (device == NULL) {
        return SDL_SetError("Controller is no longer connected");
    }
    if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
        if (!device->rumble && device->controller && device->controller.haptics) {
            SDL3_RumbleContext *rumble = IOS_JoystickInitRumble(device->controller);
            if (rumble) {
                device->rumble = (void *)CFBridgingRetain(rumble);
            }
        }
    }
    if (device->rumble) {
        SDL3_RumbleContext *rumble = (__bridge SDL3_RumbleContext *)device->rumble;
        return [rumble rumbleWithLowFrequency:low_frequency_rumble andHighFrequency:high_frequency_rumble];
    }
#endif
    return SDL_Unsupported();
}
References joystick_hwdata::controller, NULL, joystick_hwdata::rumble, SDL_SetError(), and SDL_Unsupported.
IOS_JoystickRumbleTriggers()
bool IOS_JoystickRumbleTriggers (SDL_Joystick * joystick, Uint16 left_rumble, Uint16 right_rumble) static
{
#ifdef SDL_JOYSTICK_MFI
    SDL_JoystickDeviceItem *device = joystick->hwdata;
    if (device == NULL) {
        return SDL_SetError("Controller is no longer connected");
    }
    if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
        if (!device->rumble && device->controller && device->controller.haptics) {
            SDL3_RumbleContext *rumble = IOS_JoystickInitRumble(device->controller);
            if (rumble) {
                device->rumble = (void *)CFBridgingRetain(rumble);
            }
        }
    }
    if (device->rumble) {
        SDL3_RumbleContext *rumble = (__bridge SDL3_RumbleContext *)device->rumble;
        return [rumble rumbleLeftTrigger:left_rumble andRightTrigger:right_rumble];
    }
#endif
    return SDL_Unsupported();
}
References joystick_hwdata::controller, NULL, joystick_hwdata::rumble, SDL_SetError(), and SDL_Unsupported.
IOS_JoystickSendEffect()
bool IOS_JoystickSendEffect (SDL_Joystick * joystick, const void * data, int size) static
{
    return SDL_Unsupported();
}
References SDL_Unsupported.
IOS_JoystickSetDevicePlayerIndex()
void IOS_JoystickSetDevicePlayerIndex (int device_index, int player_index) static
{
#ifdef SDL_JOYSTICK_MFI
    SDL_JoystickDeviceItem *device = GetDeviceForIndex(device_index);
    if (device && device->controller) {
        device->controller.playerIndex = player_index;
    }
#endif
}
References joystick_hwdata::controller, and GetDeviceForIndex().
IOS_JoystickSetLED()
bool IOS_JoystickSetLED (SDL_Joystick * joystick, Uint8 red, Uint8 green, Uint8 blue) static
{
    @autoreleasepool {
        SDL_JoystickDeviceItem *device = joystick->hwdata;
        if (device == NULL) {
            return SDL_SetError("Controller is no longer connected");
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCController *controller = device->controller;
            GCDeviceLight *light = controller.light;
            if (light) {
                light.color = [[GCColor alloc] initWithRed:(float)red / 255.0f
                                                     green:(float)green / 255.0f
                                                      blue:(float)blue / 255.0f];
                return true;
            }
        }
    }
    return SDL_Unsupported();
}
References joystick_hwdata::controller, NULL, SDL_SetError(), and SDL_Unsupported.
IOS_JoystickSetSensorsEnabled()
bool IOS_JoystickSetSensorsEnabled (SDL_Joystick * joystick, bool enabled) static
{
    @autoreleasepool {
        SDL_JoystickDeviceItem *device = joystick->hwdata;
        if (device == NULL) {
            return SDL_SetError("Controller is no longer connected");
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCController *controller = device->controller;
            GCMotion *motion = controller.motion;
            if (motion) {
                motion.sensorsActive = enabled ? YES : NO;
                return true;
            }
        }
    }
    return SDL_Unsupported();
}
References joystick_hwdata::controller, NULL, SDL_SetError(), and SDL_Unsupported.
IOS_JoystickUpdate()
void IOS_JoystickUpdate (SDL_Joystick * joystick) static
{
    SDL_JoystickDeviceItem *device = joystick->hwdata;
    if (device == NULL) {
        return;
    }
    if (device->controller) {
        IOS_MFIJoystickUpdate(joystick);
    }
}
References joystick_hwdata::controller, IOS_MFIJoystickUpdate(), and NULL.
IOS_MFIJoystickUpdate()
void IOS_MFIJoystickUpdate (SDL_Joystick * joystick) static
{
#ifdef SDL_JOYSTICK_MFI
    @autoreleasepool {
        SDL_JoystickDeviceItem *device = joystick->hwdata;
        GCController *controller = device->controller;
        Uint8 hatstate = SDL_HAT_CENTERED;
        int i;
        Uint64 timestamp = SDL_GetTicksNS();
#ifdef DEBUG_CONTROLLER_STATE
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            if (controller.physicalInputProfile) {
                for (id key in controller.physicalInputProfile.buttons) {
                    GCControllerButtonInput *button = controller.physicalInputProfile.buttons[key];
                    if (button.isPressed)
                        NSLog(@"Button %@ = %s\n", key, button.isPressed ? "pressed" : "released");
                }
                for (id key in controller.physicalInputProfile.axes) {
                    GCControllerAxisInput *axis = controller.physicalInputProfile.axes[key];
                    if (axis.value != 0.0f)
                        NSLog(@"Axis %@ = %g\n", key, axis.value);
                }
                for (id key in controller.physicalInputProfile.dpads) {
                    GCControllerDirectionPad *dpad = controller.physicalInputProfile.dpads[key];
                    if (dpad.up.isPressed || dpad.down.isPressed || dpad.left.isPressed || dpad.right.isPressed) {
                        NSLog(@"Hat %@ =%s%s%s%s\n", key,
                            dpad.up.isPressed ? " UP" : "",
                            dpad.down.isPressed ? " DOWN" : "",
                            dpad.left.isPressed ? " LEFT" : "",
                            dpad.right.isPressed ? " RIGHT" : "");
                    }
                }
            }
        }
#endif // DEBUG_CONTROLLER_STATE
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            NSDictionary<NSString *, GCControllerElement *> *elements = controller.physicalInputProfile.elements;
            NSDictionary<NSString *, GCControllerButtonInput *> *buttons = controller.physicalInputProfile.buttons;
            int axis = 0;
            for (id key in device->axes) {
                Sint16 value;
                GCControllerElement *element = elements[key];
                if ([element isKindOfClass:[GCControllerAxisInput class]]) {
                    value = (Sint16)([(GCControllerAxisInput *)element value] * 32767);
                } else {
                    value = (Sint16)([(GCControllerButtonInput *)element value] * 32767);
                }
                SDL_SendJoystickAxis(timestamp, joystick, axis++, value);
            }
            int button = 0;
            for (id key in device->buttons) {
                bool down;
                if (button == device->pause_button_index) {
                    down = (device->pause_button_pressed > 0);
                } else {
                    down = buttons[key].isPressed;
                }
                SDL_SendJoystickButton(timestamp, joystick, button++, down);
            }
        } else if (controller.extendedGamepad) {
            bool isstack;
            GCExtendedGamepad *gamepad = controller.extendedGamepad;
            // Axis order matches the XInput Windows mappings.
            Sint16 axes[] = {
                (Sint16)(gamepad.leftThumbstick.xAxis.value * 32767),
                (Sint16)(gamepad.leftThumbstick.yAxis.value * -32767),
                (Sint16)((gamepad.leftTrigger.value * 65535) - 32768),
                (Sint16)(gamepad.rightThumbstick.xAxis.value * 32767),
                (Sint16)(gamepad.rightThumbstick.yAxis.value * -32767),
                (Sint16)((gamepad.rightTrigger.value * 65535) - 32768),
            };
            // Button order matches the XInput Windows mappings.
            bool *buttons = SDL_small_alloc(bool, joystick->nbuttons, &isstack);
            int button_count = 0;
            if (buttons == NULL) {
                return;
            }
            // These buttons are part of the original MFi spec
            buttons[button_count++] = gamepad.buttonA.isPressed;
            buttons[button_count++] = gamepad.buttonB.isPressed;
            buttons[button_count++] = gamepad.buttonX.isPressed;
            buttons[button_count++] = gamepad.buttonY.isPressed;
            buttons[button_count++] = gamepad.leftShoulder.isPressed;
            buttons[button_count++] = gamepad.rightShoulder.isPressed;
            // These buttons are available on some newer controllers
            if (@available(macOS 10.14.1, iOS 12.1, tvOS 12.1, *)) {
                if (device->button_mask & (1 << SDL_GAMEPAD_BUTTON_LEFT_STICK)) {
                    buttons[button_count++] = gamepad.leftThumbstickButton.isPressed;
                }
                if (device->button_mask & (1 << SDL_GAMEPAD_BUTTON_RIGHT_STICK)) {
                    buttons[button_count++] = gamepad.rightThumbstickButton.isPressed;
                }
            }
            if (@available(macOS 10.15, iOS 13.0, tvOS 13.0, *)) {
                if (device->button_mask & (1 << SDL_GAMEPAD_BUTTON_BACK)) {
                    buttons[button_count++] = gamepad.buttonOptions.isPressed;
                }
            }
            if (device->button_mask & (1 << SDL_GAMEPAD_BUTTON_START)) {
                if (device->pause_button_index >= 0) {
                    // Guaranteed if buttonMenu is not supported on this OS
                    buttons[button_count++] = (device->pause_button_pressed > 0);
                } else {
                    if (@available(macOS 10.15, iOS 13.0, tvOS 13.0, *)) {
                        buttons[button_count++] = gamepad.buttonMenu.isPressed;
                    }
                }
            }
            hatstate = IOS_MFIJoystickHatStateForDPad(gamepad.dpad);
            for (i = 0; i < SDL_arraysize(axes); i++) {
                SDL_SendJoystickAxis(timestamp, joystick, i, axes[i]);
            }
            for (i = 0; i < button_count; i++) {
                SDL_SendJoystickButton(timestamp, joystick, i, buttons[i]);
            }
            SDL_small_free(buttons, isstack);
        }
#ifdef SDL_PLATFORM_TVOS
        else if (controller.microGamepad) {
            GCMicroGamepad *gamepad = controller.microGamepad;
            Sint16 axes[] = {
                (Sint16)(gamepad.dpad.xAxis.value * 32767),
                (Sint16)(gamepad.dpad.yAxis.value * -32767),
            };
            for (i = 0; i < SDL_arraysize(axes); i++) {
                SDL_SendJoystickAxis(timestamp, joystick, i, axes[i]);
            }
            bool buttons[joystick->nbuttons];
            int button_count = 0;
            buttons[button_count++] = gamepad.buttonA.isPressed;
            buttons[button_count++] = gamepad.buttonX.isPressed;
            buttons[button_count++] = (device->pause_button_pressed > 0);
            for (i = 0; i < button_count; i++) {
                SDL_SendJoystickButton(timestamp, joystick, i, buttons[i]);
            }
        }
#endif // SDL_PLATFORM_TVOS
        if (joystick->nhats > 0) {
            SDL_SendJoystickHat(timestamp, joystick, 0, hatstate);
        }
        if (device->pause_button_pressed) {
            // The pause callback is instantaneous, so we extend the duration to allow "holding down" by pressing it repeatedly
            const int PAUSE_BUTTON_PRESS_DURATION_MS = 250;
            if (SDL_GetTicks() >= device->pause_button_pressed + PAUSE_BUTTON_PRESS_DURATION_MS) {
                device->pause_button_pressed = 0;
            }
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            if (device->has_dualshock_touchpad) {
                GCControllerDirectionPad *dpad;
                dpad = controller.physicalInputProfile.dpads[GCInputDualShockTouchpadOne];
                if (dpad.xAxis.value != 0.f || dpad.yAxis.value != 0.f) {
                    SDL_SendJoystickTouchpad(timestamp, joystick, 0, 0, true, (1.0f + dpad.xAxis.value) * 0.5f, 1.0f - (1.0f + dpad.yAxis.value) * 0.5f, 1.0f);
                } else {
                    SDL_SendJoystickTouchpad(timestamp, joystick, 0, 0, false, 0.0f, 0.0f, 1.0f);
                }
                dpad = controller.physicalInputProfile.dpads[GCInputDualShockTouchpadTwo];
                if (dpad.xAxis.value != 0.f || dpad.yAxis.value != 0.f) {
                    SDL_SendJoystickTouchpad(timestamp, joystick, 0, 1, true, (1.0f + dpad.xAxis.value) * 0.5f, 1.0f - (1.0f + dpad.yAxis.value) * 0.5f, 1.0f);
                } else {
                    SDL_SendJoystickTouchpad(timestamp, joystick, 0, 1, false, 0.0f, 0.0f, 1.0f);
                }
            }
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCMotion *motion = controller.motion;
            if (motion && motion.sensorsActive) {
                float data[3];
                if (motion.hasRotationRate) {
                    GCRotationRate rate = motion.rotationRate;
                    data[0] = rate.x;
                    data[1] = rate.z;
                    data[2] = -rate.y;
                    SDL_SendJoystickSensor(timestamp, joystick, SDL_SENSOR_GYRO, timestamp, data, 3);
                }
                if (motion.hasGravityAndUserAcceleration) {
                    GCAcceleration accel = motion.acceleration;
                    data[0] = -accel.x * SDL_STANDARD_GRAVITY;
                    data[1] = -accel.y * SDL_STANDARD_GRAVITY;
                    data[2] = -accel.z * SDL_STANDARD_GRAVITY;
                    SDL_SendJoystickSensor(timestamp, joystick, SDL_SENSOR_ACCEL, timestamp, data, 3);
                }
            }
        }
        if (@available(macOS 10.16, iOS 14.0, tvOS 14.0, *)) {
            GCDeviceBattery *battery = controller.battery;
            if (battery) {
                SDL_PowerState state = SDL_POWERSTATE_UNKNOWN;
                int percent = (int)SDL_roundf(battery.batteryLevel * 100.0f);
                switch (battery.batteryState) {
                case GCDeviceBatteryStateDischarging:
                    state = SDL_POWERSTATE_ON_BATTERY;
                    break;
                case GCDeviceBatteryStateCharging:
                    state = SDL_POWERSTATE_CHARGING;
                    break;
                case GCDeviceBatteryStateFull:
                    state = SDL_POWERSTATE_CHARGED;
                    break;
                default:
                    break;
                }
                SDL_SendJoystickPowerInfo(joystick, state, percent);
            }
        }
    }
#endif // SDL_JOYSTICK_MFI
}
References joystick_hwdata::axes, joystick_hwdata::button_mask, joystick_hwdata::buttons, joystick_hwdata::controller, joystick_hwdata::has_dualshock_touchpad, NULL, joystick_hwdata::pause_button_index, joystick_hwdata::pause_button_pressed, SDL_arraysize, SDL_GAMEPAD_BUTTON_BACK, SDL_GAMEPAD_BUTTON_LEFT_STICK, SDL_GAMEPAD_BUTTON_RIGHT_STICK, SDL_GAMEPAD_BUTTON_START, SDL_GetTicks(), SDL_GetTicksNS(), SDL_HAT_CENTERED, SDL_POWERSTATE_CHARGED, SDL_POWERSTATE_CHARGING, SDL_POWERSTATE_ON_BATTERY, SDL_POWERSTATE_UNKNOWN, SDL_roundf(), SDL_SendJoystickAxis(), SDL_SendJoystickButton(), SDL_SendJoystickHat(), SDL_SendJoystickPowerInfo(), SDL_SendJoystickSensor(), SDL_SendJoystickTouchpad(), SDL_SENSOR_ACCEL, SDL_SENSOR_GYRO, SDL_small_alloc, SDL_small_free, and SDL_STANDARD_GRAVITY.
Referenced by IOS_JoystickUpdate().
IOS_RemoveJoystickDevice()
SDL_JoystickDeviceItem * IOS_RemoveJoystickDevice (SDL_JoystickDeviceItem * device) static
{
    SDL_JoystickDeviceItem *prev = NULL;
    SDL_JoystickDeviceItem *next = NULL;
    SDL_JoystickDeviceItem *item = deviceList;
    if (device == NULL) {
        return NULL;
    }
    next = device->next;
    while (item != NULL) {
        if (item == device) {
            break;
        }
        prev = item;
        item = item->next;
    }
    // Unlink the device item from the device list.
    if (prev) {
        prev->next = device->next;
    } else if (device == deviceList) {
        deviceList = device->next;
    }
    if (device->joystick) {
        device->joystick->hwdata = NULL;
    }
#ifdef SDL_JOYSTICK_MFI
    @autoreleasepool {
        // These were explicitly retained in the struct, so they should be explicitly released before freeing the struct.
        if (device->controller) {
            GCController *controller = CFBridgingRelease((__bridge CFTypeRef)(device->controller));
            controller.controllerPausedHandler = nil;
            device->controller = nil;
        }
        if (device->axes) {
            CFRelease((__bridge CFTypeRef)device->axes);
            device->axes = nil;
        }
        if (device->buttons) {
            CFRelease((__bridge CFTypeRef)device->buttons);
            device->buttons = nil;
        }
    }
#endif // SDL_JOYSTICK_MFI
    --numjoysticks;
    SDL_PrivateJoystickRemoved(device->instance_id);
    SDL_free(device->name);
    SDL_free(device);
    return next;
}
References joystick_hwdata::axes, joystick_hwdata::buttons, joystick_hwdata::controller, deviceList, joystick_hwdata::instance_id, joystick_hwdata::joystick, joystick_hwdata::name, joystick_hwdata::next, NULL, numjoysticks, SDL_free(), and SDL_PrivateJoystickRemoved().
Referenced by IOS_JoystickQuit().
Variable Documentation
deviceList
SDL_JoystickDeviceItem* deviceList = NULL static
Referenced by GetDeviceForIndex(), IOS_JoystickQuit(), and IOS_RemoveJoystickDevice().
numjoysticks
int numjoysticks = 0 static
Referenced by IOS_JoystickGetCount(), IOS_JoystickQuit(), and IOS_RemoveJoystickDevice().
SDL_AppleTVRemoteOpenedAsJoystick
int SDL_AppleTVRemoteOpenedAsJoystick = 0
Referenced by IOS_JoystickClose(), and IOS_JoystickOpen().
SDL_IOS_JoystickDriver
SDL_JoystickDriver SDL_IOS_JoystickDriver
Initial value:
= {
    IOS_JoystickInit,
    IOS_JoystickGetCount,
    IOS_JoystickDetect,
    IOS_JoystickIsDevicePresent,
    IOS_JoystickGetDeviceName,
    IOS_JoystickGetDevicePath,
    IOS_JoystickGetDeviceSteamVirtualGamepadSlot,
    IOS_JoystickGetDevicePlayerIndex,
    IOS_JoystickSetDevicePlayerIndex,
    IOS_JoystickGetDeviceGUID,
    IOS_JoystickGetDeviceInstanceID,
    IOS_JoystickOpen,
    IOS_JoystickRumble,
    IOS_JoystickRumbleTriggers,
    IOS_JoystickSetLED,
    IOS_JoystickSendEffect,
    IOS_JoystickSetSensorsEnabled,
    IOS_JoystickUpdate,
    IOS_JoystickClose,
    IOS_JoystickQuit,
    IOS_JoystickGetGamepadMapping
}
{
    IOS_JoystickInit,
    IOS_JoystickGetCount,
    IOS_JoystickDetect,
    IOS_JoystickIsDevicePresent,
    IOS_JoystickGetDeviceName,
    IOS_JoystickGetDevicePath,
    IOS_JoystickGetDeviceSteamVirtualGamepadSlot,
    IOS_JoystickGetDevicePlayerIndex,
    IOS_JoystickSetDevicePlayerIndex,
    IOS_JoystickGetDeviceGUID,
    IOS_JoystickGetDeviceInstanceID,
    IOS_JoystickOpen,
    IOS_JoystickRumble,
    IOS_JoystickRumbleTriggers,
    IOS_JoystickSetLED,
    IOS_JoystickSendEffect,
    IOS_JoystickSetSensorsEnabled,
    IOS_JoystickUpdate,
    IOS_JoystickClose,
    IOS_JoystickQuit,
    IOS_JoystickGetGamepadMapping
};
Referenced by IOS_GetAppleSFSymbolsNameForAxis(), and IOS_GetAppleSFSymbolsNameForButton().