SDL3: SDL-main/src/filesystem/ngage/SDL_sysfilesystem.c File Reference
SDL_sysfilesystem.c File Reference
#include "SDL_internal.h"
Functions
void NGAGE_GetAppPath (char *path)
char * SDL_SYS_GetBasePath (void)
char * SDL_SYS_GetPrefPath (const char *org, const char *app)
char * SDL_SYS_GetUserFolder (SDL_Folder folder)
Function Documentation
NGAGE_GetAppPath()
void NGAGE_GetAppPath (char * path) extern
{
    TBuf<512> aPath;
    TFileName fullExePath = RProcess().FileName();
    TParsePtrC parser(fullExePath);
    aPath.Copy(parser.DriveAndPath());
    TBuf8<512> utf8Path; // Temporary buffer for UTF-8 data.
    CnvUtfConverter::ConvertFromUnicodeToUtf8(utf8Path, aPath);
    // Copy UTF-8 data to the provided char* buffer.
    strncpy(path, (const char *)utf8Path.Ptr(), utf8Path.Length());
    path[utf8Path.Length()] = '\0';
    // Replace backslashes with forward slashes.
    for (int i = 0; i < utf8Path.Length(); i++)
    {
        if (path[i] == '\\')
        {
            path[i] = '/';
        }
    }
}
References strncpy.
Referenced by SDL_SYS_GetBasePath().
SDL_SYS_GetBasePath()
char * SDL_SYS_GetBasePath (void)
{
    char app_path[512];
    NGAGE_GetAppPath(app_path);
    char *base_path = SDL_strdup(app_path);
    return base_path;
}
References NGAGE_GetAppPath(), and SDL_strdup().
SDL_SYS_GetPrefPath()
char * SDL_SYS_GetPrefPath (const char * org, const char * app)
{
    char *pref_path = NULL;
    if (SDL_asprintf(&pref_path, "C:/System/Apps/%s/%s/", org ? org : "SDL_App", app) < 0) {
        return NULL;
    }
    return pref_path;
}
References NULL, and SDL_asprintf().
SDL_SYS_GetUserFolder()
char * SDL_SYS_GetUserFolder (SDL_Folder folder)
{
    const char *folder_path = NULL;
    switch (folder)
    {
        case SDL_FOLDER_HOME:
            folder_path = "C:/";
            break;
        case SDL_FOLDER_PICTURES:
            folder_path = "C:/Nokia/Pictures/";
            break;
        case SDL_FOLDER_SAVEDGAMES:
            folder_path = "C:/";
            break;
        case SDL_FOLDER_SCREENSHOTS:
            folder_path = "C:/Nokia/Pictures/";
            break;
        case SDL_FOLDER_VIDEOS:
            folder_path = "C:/Nokia/Videos/";
            break;
        default:
            folder_path = "C:/Nokia/Others/";
            break;
    }
    return SDL_strdup(folder_path);
}
References NULL, SDL_FOLDER_HOME, SDL_FOLDER_PICTURES, SDL_FOLDER_SAVEDGAMES, SDL_FOLDER_SCREENSHOTS, SDL_FOLDER_VIDEOS, and SDL_strdup().