SDL3: SDL-main/src/thread/pthread/SDL_syssem.c File Reference
SDL_syssem.c File Reference
#include "SDL_internal.h"
#include <errno.h>
#include <pthread.h>
#include <semaphore.h>
#include <sys/time.h>
#include <time.h>
Data Structures
struct SDL_Semaphore
Functions
SDL_Semaphore * SDL_CreateSemaphore (Uint32 initial_value)
void SDL_DestroySemaphore (SDL_Semaphore *sem)
Uint32 SDL_GetSemaphoreValue (SDL_Semaphore *sem)
void SDL_SignalSemaphore (SDL_Semaphore *sem)
bool SDL_WaitSemaphoreTimeoutNS (SDL_Semaphore *sem, Sint64 timeoutNS)
Function Documentation
SDL_CreateSemaphore()
SDL_Semaphore * SDL_CreateSemaphore (Uint32 initial_value)
Create a semaphore.
This function creates a new semaphore and initializes it with the value initial_value. Each wait operation on the semaphore will atomically decrement the semaphore value and potentially block if the semaphore value is 0. Each post operation will atomically increment the semaphore value and wake waiting threads and allow them to retry the wait operation.
Parameters
initial_value the starting value of the semaphore.
Returns
a new semaphore or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroySemaphore
SDL_SignalSemaphore
SDL_TryWaitSemaphore
SDL_GetSemaphoreValue
SDL_WaitSemaphore
SDL_WaitSemaphoreTimeout
{
    SDL_Semaphore *sem = (SDL_Semaphore *)SDL_malloc(sizeof(SDL_Semaphore));
    if (sem) {
        if (sem_init(&sem->sem, 0, initial_value) < 0) {
            SDL_SetError("sem_init() failed");
            SDL_free(sem);
            sem = NULL;
        }
    }
    return sem;
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, NULL, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroySemaphore(), SDL_free(), SDL_malloc(), SDL_SetError(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_CreateCondition(), SDL_CreateMainThreadCallback(), SDL_CreateMutex(), and SDL_InitTimers().
SDL_DestroySemaphore()
void SDL_DestroySemaphore (SDL_Semaphore * sem)
Destroy a semaphore.
It is not safe to destroy a semaphore if there are threads currently waiting on it.
Parameters
sem the semaphore to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateSemaphore
{
    if (sem) {
        sem_destroy(&sem->sem);
        SDL_free(sem);
    }
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, SDL_Delay(), SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_free(), SDL_LockMutex(), SDL_SignalCondition(), SDL_UnlockMutex(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_DestroyCondition(), SDL_DestroyMainThreadCallback(), SDL_DestroyMutex(), and SDL_QuitTimers().
SDL_GetSemaphoreValue()
Uint32 SDL_GetSemaphoreValue (SDL_Semaphore * sem)
Get the current value of a semaphore.
Parameters
sem the semaphore to query.
Returns
the current value of the semaphore.
Since
This function is available since SDL 3.2.0.
{
    int ret = 0;
    if (!sem) {
        return 0;
    }
    sem_getvalue(&sem->sem, &ret);
    if (ret < 0) {
        ret = 0;
    }
    return (Uint32)ret;
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_Semaphore::sem.
SDL_SignalSemaphore()
void SDL_SignalSemaphore (SDL_Semaphore * sem)
Atomically increment a semaphore's value and wake waiting threads.
Parameters
sem the semaphore to increment.
Since
This function is available since SDL 3.2.0.
See also
SDL_TryWaitSemaphore
SDL_WaitSemaphore
SDL_WaitSemaphoreTimeout
{
    if (!sem) {
        return;
    }
    sem_post(&sem->sem);
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, SDL_LockMutex(), SDL_SignalCondition(), SDL_UnlockMutex(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_BroadcastCondition(), SDL_CreateTimer(), SDL_QuitMainThreadCallbacks(), SDL_QuitTimers(), SDL_RunMainThreadCallbacks(), SDL_SignalCondition(), SDL_UnlockMutex(), and SDL_WaitConditionTimeoutNS_generic().
SDL_WaitSemaphoreTimeoutNS()
bool SDL_WaitSemaphoreTimeoutNS (SDL_Semaphore * sem, Sint64 timeoutNS)
{
#ifdef HAVE_SEM_TIMEDWAIT
#ifndef HAVE_CLOCK_GETTIME
    struct timeval now;
#endif
    struct timespec ts_timeout;
#else
    Uint64 stop_time;
#endif
    if (!sem) {
        return true;
    }
    // Try the easy cases first
    if (timeoutNS == 0) {
        return (sem_trywait(&sem->sem) == 0);
    }
    if (timeoutNS < 0) {
        int rc;
        do {
            rc = sem_wait(&sem->sem);
        } while (rc < 0 && errno == EINTR);
        return (rc == 0);
    }
#ifdef HAVE_SEM_TIMEDWAIT
    /* Setup the timeout. sem_timedwait doesn't wait for
     * a lapse of time, but until we reach a certain time.
     * This time is now plus the timeout.
     */
#ifdef HAVE_CLOCK_GETTIME
    clock_gettime(CLOCK_REALTIME, &ts_timeout);
    // Add our timeout to current time
    ts_timeout.tv_sec += (timeoutNS / SDL_NS_PER_SECOND);
    ts_timeout.tv_nsec += (timeoutNS % SDL_NS_PER_SECOND);
#else
    gettimeofday(&now, NULL);
    // Add our timeout to current time
    ts_timeout.tv_sec = now.tv_sec + (timeoutNS / SDL_NS_PER_SECOND);
    ts_timeout.tv_nsec = SDL_US_TO_NS(now.tv_usec) + (timeoutNS % SDL_NS_PER_SECOND);
#endif
    // Wrap the second if needed
    while (ts_timeout.tv_nsec >= 1000000000) {
        ts_timeout.tv_sec += 1;
        ts_timeout.tv_nsec -= 1000000000;
    }
    // Wait.
    int rc;
    do {
        rc = sem_timedwait(&sem->sem, &ts_timeout);
    } while (rc < 0 && errno == EINTR);
    return (rc == 0);
#else
    stop_time = SDL_GetTicksNS() + timeoutNS;
    while (sem_trywait(&sem->sem) != 0) {
        if (SDL_GetTicksNS() >= stop_time) {
            return false;
        }
        SDL_DelayNS(100);
    }
    return true;
#endif // HAVE_SEM_TIMEDWAIT
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, NULL, SDL_DelayNS(), SDL_GetTicksNS(), SDL_LockMutex(), SDL_NS_PER_SECOND, SDL_UnlockMutex(), SDL_US_TO_NS, SDL_WaitConditionTimeoutNS(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_TimerThread(), SDL_TryWaitSemaphore(), SDL_WaitConditionTimeoutNS_generic(), SDL_WaitSemaphore(), and SDL_WaitSemaphoreTimeout().