SDL3: SDL-main/src/timer/SDL_timer.c File Reference
SDL_timer.c File Reference
#include "SDL_internal.h"
#include "SDL_timer_c.h"
#include "../thread/SDL_systhread.h"
Data Structures
struct SDL_Timer
struct SDL_TimerData
struct SDL_TimerMap
Typedefs
typedef struct SDL_Timer SDL_Timer
typedef struct SDL_TimerMap SDL_TimerMap
Functions
SDL_TimerID SDL_AddTimer (Uint32 interval, SDL_TimerCallback callback, void *userdata)
static void SDL_AddTimerInternal (SDL_TimerData *data, SDL_Timer *timer)
SDL_TimerID SDL_AddTimerNS (Uint64 interval, SDL_NSTimerCallback callback, void *userdata)
static bool SDL_CheckInitTimers (void)
static SDL_TimerID SDL_CreateTimer (Uint64 interval, SDL_TimerCallback callback_ms, SDL_NSTimerCallback callback_ns, void *userdata)
void SDL_Delay (Uint32 ms)
void SDL_DelayNS (Uint64 ns)
void SDL_DelayPrecise (Uint64 ns)
Uint64 SDL_GetTicks (void)
Uint64 SDL_GetTicksNS (void)
void SDL_InitTicks (void)
bool SDL_InitTimers (void)
void SDL_QuitTicks (void)
void SDL_QuitTimers (void)
bool SDL_RemoveTimer (SDL_TimerID id)
static void SDL_SetSystemTimerResolutionMS (int period)
static void SDLCALL SDL_TimerResolutionChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
static int SDLCALL SDL_TimerThread (void *_data)
Variables
static SDL_TimerData SDL_timer_data
static Uint32 tick_denominator_ms
static Uint32 tick_denominator_ns
static Uint32 tick_numerator_ms
static Uint32 tick_numerator_ns
static Uint64 tick_start
Typedef Documentation
SDL_Timer
typedef struct SDL_Timer SDL_Timer
SDL_TimerMap
typedef struct SDL_TimerMap SDL_TimerMap
Function Documentation
SDL_AddTimer()
SDL_TimerID SDL_AddTimer (Uint32 interval, SDL_TimerCallback callback, void * userdata)
Call a callback function at a future time.
The callback function is passed the current timer interval and the user supplied parameter from the SDL_AddTimer() call and should return the next timer interval. If the value returned from the callback is 0, the timer is canceled and will be removed.
The callback is run on a separate thread, and for short timeouts can potentially be called before this function returns.
Timers take into account the amount of time it took to execute the callback. For example, if the callback took 250 ms to execute and returned 1000 (ms), the timer would only wait another 750 ms before its next iteration.
Timing may be inexact due to OS scheduling. Be sure to note the current time with SDL_GetTicksNS() or SDL_GetPerformanceCounter() in case your callback needs to adjust for variances.
Parameters
interval the timer delay, in milliseconds, passed to callback.
callback the SDL_TimerCallback function to call when the specified interval elapses.
userdata a pointer that is passed to callback.
Returns
a timer ID or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddTimerNS
SDL_RemoveTimer
{
    return SDL_CreateTimer(SDL_MS_TO_NS(interval), callback, NULL, userdata);
}
References NULL, SDL_CreateTimer(), and SDL_MS_TO_NS.
SDL_AddTimerInternal()
void SDL_AddTimerInternal (SDL_TimerData * data, SDL_Timer * timer) static
{
    SDL_Timer *prev, *curr;
    prev = NULL;
    for (curr = data->timers; curr; prev = curr, curr = curr->next) {
        if (curr->scheduled > timer->scheduled) {
            break;
        }
    }
    // Insert the timer here!
    if (prev) {
        prev->next = timer;
    } else {
        data->timers = timer;
    }
    timer->next = curr;
}
References SDL_Timer::next, NULL, SDL_Timer::scheduled, and SDL_TimerMap::timer.
Referenced by SDL_TimerThread().
SDL_AddTimerNS()
SDL_TimerID SDL_AddTimerNS (Uint64 interval, SDL_NSTimerCallback callback, void * userdata)
Call a callback function at a future time.
The callback function is passed the current timer interval and the user supplied parameter from the SDL_AddTimerNS() call and should return the next timer interval. If the value returned from the callback is 0, the timer is canceled and will be removed.
The callback is run on a separate thread, and for short timeouts can potentially be called before this function returns.
Timers take into account the amount of time it took to execute the callback. For example, if the callback took 250 ns to execute and returned 1000 (ns), the timer would only wait another 750 ns before its next iteration.
Timing may be inexact due to OS scheduling. Be sure to note the current time with SDL_GetTicksNS() or SDL_GetPerformanceCounter() in case your callback needs to adjust for variances.
Parameters
interval the timer delay, in nanoseconds, passed to callback.
callback the SDL_TimerCallback function to call when the specified interval elapses.
userdata a pointer that is passed to callback.
Returns
a timer ID or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddTimer
SDL_RemoveTimer
{
    return SDL_CreateTimer(interval, NULL, callback, userdata);
}
References NULL, and SDL_CreateTimer().
SDL_CheckInitTimers()
bool SDL_CheckInitTimers (void) static
{
    return SDL_InitTimers();
}
References SDL_InitTimers().
Referenced by SDL_CreateTimer().
SDL_CreateTimer()
SDL_TimerID SDL_CreateTimer (Uint64 interval, SDL_TimerCallback callback_ms, SDL_NSTimerCallback callback_ns, void * userdata) static
{
    SDL_TimerData *data = &SDL_timer_data;
    SDL_Timer *timer;
    SDL_TimerMap *entry;
    if (!callback_ms && !callback_ns) {
        SDL_InvalidParamError("callback");
        return 0;
    }
    if (!SDL_CheckInitTimers()) {
        return 0;
    }
    SDL_LockSpinlock(&data->lock);
    timer = data->freelist;
    if (timer) {
        data->freelist = timer->next;
    }
    SDL_UnlockSpinlock(&data->lock);
    if (timer) {
        SDL_RemoveTimer(timer->timerID);
    } else {
        timer = (SDL_Timer *)SDL_malloc(sizeof(*timer));
        if (!timer) {
            return 0;
        }
    }
    timer->timerID = SDL_GetNextObjectID();
    timer->callback_ms = callback_ms;
    timer->callback_ns = callback_ns;
    timer->userdata = userdata;
    timer->interval = interval;
    timer->scheduled = SDL_GetTicksNS() + timer->interval;
    SDL_SetAtomicInt(&timer->canceled, 0);
    entry = (SDL_TimerMap *)SDL_malloc(sizeof(*entry));
    if (!entry) {
        SDL_free(timer);
        return 0;
    }
    entry->timer = timer;
    entry->timerID = timer->timerID;
    SDL_LockMutex(data->timermap_lock);
    entry->next = data->timermap;
    data->timermap = entry;
    SDL_UnlockMutex(data->timermap_lock);
    // Add the timer to the pending list for the timer thread
    SDL_LockSpinlock(&data->lock);
    timer->next = data->pending;
    data->pending = timer;
    SDL_UnlockSpinlock(&data->lock);
    // Wake up the timer thread if necessary
    SDL_SignalSemaphore(data->sem);
    return entry->timerID;
}
References SDL_Timer::callback_ms, SDL_Timer::callback_ns, SDL_Timer::canceled, SDL_Timer::interval, SDL_Timer::next, SDL_TimerMap::next, SDL_Timer::scheduled, SDL_CheckInitTimers(), SDL_free(), SDL_GetNextObjectID(), SDL_GetTicksNS(), SDL_InvalidParamError, SDL_LockMutex(), SDL_LockSpinlock(), SDL_malloc(), SDL_RemoveTimer(), SDL_SetAtomicInt(), SDL_SignalSemaphore(), SDL_timer_data, SDL_UnlockMutex(), SDL_UnlockSpinlock(), SDL_TimerMap::timer, SDL_Timer::timerID, SDL_TimerMap::timerID, and SDL_Timer::userdata.
Referenced by SDL_AddTimer(), and SDL_AddTimerNS().
SDL_Delay()
void SDL_Delay (Uint32 ms)
Wait a specified number of milliseconds before returning.
This function waits a specified number of milliseconds before returning. It waits at least the specified time, but possibly longer due to OS scheduling.
Parameters
ms the number of milliseconds to delay.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DelayNS
SDL_DelayPrecise
{
    SDL_SYS_DelayNS(SDL_MS_TO_NS(ms));
}
References SDL_MS_TO_NS, and SDL_SYS_DelayNS().
Referenced by DUMMYAUDIO_WaitDevice(), SDL_DestroySemaphore(), SDL_LoadFile_IO(), SDL_LockSpinlock(), SDL_PlaybackAudioThreadShutdown(), SDL_SaveFile_IO(), SDL_ShouldInit(), SDL_ShouldQuit(), ZombieWaitDevice(), and ZombieWaitDevice().
SDL_DelayNS()
void SDL_DelayNS (Uint64 ns)
Wait a specified number of nanoseconds before returning.
This function waits a specified number of nanoseconds before returning. It waits at least the specified time, but possibly longer due to OS scheduling.
Parameters
ns the number of nanoseconds to delay.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Delay
SDL_DelayPrecise
{
    SDL_SYS_DelayNS(ns);
}
References SDL_SYS_DelayNS().
Referenced by SDL_WaitEventTimeoutNS(), and SDL_WaitSemaphoreTimeoutNS().
SDL_DelayPrecise()
void SDL_DelayPrecise (Uint64 ns)
Wait a specified number of nanoseconds before returning.
This function waits a specified number of nanoseconds before returning. It will attempt to wait as close to the requested time as possible, busy waiting if necessary, but could return later due to OS scheduling.
Parameters
ns the number of nanoseconds to delay.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_Delay
SDL_DelayNS
{
    Uint64 current_value = SDL_GetTicksNS();
    const Uint64 target_value = current_value + ns;
    // Sleep for a short number of cycles when real sleeps are desired.
    // We'll use 1 ms, it's the minimum guaranteed to produce real sleeps across
    // all platforms.
    const Uint64 SHORT_SLEEP_NS = 1 * SDL_NS_PER_MS;
    // Try to sleep short of target_value. If for some crazy reason
    // a particular platform sleeps for less than 1 ms when 1 ms was requested,
    // that's fine, the code below can cope with that, but in practice no
    // platforms behave that way.
    Uint64 max_sleep_ns = SHORT_SLEEP_NS;
    while (current_value + max_sleep_ns < target_value) {
        // Sleep for a short time
        SDL_SYS_DelayNS(SHORT_SLEEP_NS);
        const Uint64 now = SDL_GetTicksNS();
        const Uint64 next_sleep_ns = (now - current_value);
        if (next_sleep_ns > max_sleep_ns) {
            max_sleep_ns = next_sleep_ns;
        }
        current_value = now;
    }
    // Do a shorter sleep of the remaining time here, less the max overshoot in
    // the first loop. Due to maintaining max_sleep_ns as
    // greater-than-or-equal-to-1 ms, we can always subtract off 1 ms to get
    // the duration overshot beyond a 1 ms sleep request; if the system never
    // overshot, great, it's zero duration. By choosing the max overshoot
    // amount, we're likely to not overshoot here. If the sleep here ends up
    // functioning like SDL_DelayNS(0) internally, that's fine, we just don't
    // get to do a more-precise-than-1 ms-resolution sleep to undershoot by a
    // small amount on the current system, but SDL_DelayNS(0) does at least
    // introduce a small, yielding delay on many platforms, better than an
    // unyielding busyloop.
    //
    // Note that we'll always do at least one sleep in this function, so the
    // minimum resolution will be that of SDL_SYS_DelayNS()
    if (current_value < target_value && (target_value - current_value) > (max_sleep_ns - SHORT_SLEEP_NS)) {
        const Uint64 delay_ns = (target_value - current_value) - (max_sleep_ns - SHORT_SLEEP_NS);
        SDL_SYS_DelayNS(delay_ns);
        current_value = SDL_GetTicksNS();
    }
    // We've likely undershot target_value at this point by a pretty small
    // amount, but maybe not. The footgun case if not handled here is where
    // we've undershot by a large amount, like several ms, but still smaller
    // than the amount max_sleep_ns overshot by; in such a situation, the above
    // shorter-sleep block didn't do any delay, the if-block wasn't entered.
    // Also, maybe the shorter-sleep undershot by several ms, so we still don't
    // want to spin a lot then. In such a case, we accept the possibility of
    // overshooting to not spin much, or if overshot here, not at all, keeping
    // CPU/power usage down in any case. Due to scheduler sloppiness, it's
    // entirely possible to end up undershooting/overshooting here by much less
    // than 1 ms even if the current system's sleep function is only 1
    // ms-resolution, as SDL_GetTicksNS() generally is better resolution than 1
    // ms on the systems SDL supports.
    while (current_value + SHORT_SLEEP_NS < target_value) {
        SDL_SYS_DelayNS(SHORT_SLEEP_NS);
        current_value = SDL_GetTicksNS();
    }
    // Spin for any remaining time
    while (current_value < target_value) {
        SDL_CPUPauseInstruction();
        current_value = SDL_GetTicksNS();
    }
}
References SDL_CPUPauseInstruction, SDL_GetTicksNS(), SDL_NS_PER_MS, and SDL_SYS_DelayNS().
Referenced by SDL_EnterAppMainCallbacks(), and SDL_SimulateRenderVSync().
SDL_GetTicks()
Uint64 SDL_GetTicks (void)
Get the number of milliseconds that have elapsed since the SDL library initialization.
Returns
an unsigned 64bit integer that represents the number of milliseconds that have elapsed since the SDL library was initialized (typically via a call to SDL_Init).
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTicksNS
{
    Uint64 starting_value, value;
    if (!tick_start) {
        SDL_InitTicks();
    }
    starting_value = (SDL_GetPerformanceCounter() - tick_start);
    value = (starting_value * tick_numerator_ms);
    SDL_assert(value >= starting_value);
    value /= tick_denominator_ms;
    return value;
}
References SDL_assert, SDL_GetPerformanceCounter(), SDL_InitTicks(), tick_denominator_ms, tick_numerator_ms, and tick_start.
Referenced by HIDAPI_UpdateDiscovery(), IOS_JoystickOpen(), IOS_MFIJoystickUpdate(), SDL_OpenJoystick(), SDL_PrivateSendMouseButton(), SDL_ReleaseAutoReleaseKeys(), SDL_RumbleJoystick(), SDL_RumbleJoystickTriggers(), SDL_SendGamepadButton(), SDL_SendKeyboardKeyInternal(), SDL_SetJoystickLED(), SDL_UpdateJoysticks(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_GetTicksNS()
Uint64 SDL_GetTicksNS (void)
Get the number of nanoseconds since SDL library initialization.
Returns
an unsigned 64-bit value representing the number of nanoseconds since the SDL library initialized.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    Uint64 starting_value, value;
    if (!tick_start) {
        SDL_InitTicks();
    }
    starting_value = (SDL_GetPerformanceCounter() - tick_start);
    value = (starting_value * tick_numerator_ns);
    SDL_assert(value >= starting_value);
    value /= tick_denominator_ns;
    return value;
}
References SDL_assert, SDL_GetPerformanceCounter(), SDL_InitTicks(), tick_denominator_ns, tick_numerator_ns, and tick_start.
Referenced by GetEventTimestamp(), GetEventTimestamp(), hidapi_thread_cond_timedwait(), hidapi_thread_gettime(), IOS_MFIJoystickUpdate(), RecenterGamepad(), SDL_CameraThreadIterate(), SDL_CreateTimer(), SDL_DelayPrecise(), SDL_DeviceNotificationFunc(), SDL_EnterAppMainCallbacks(), SDL_GamepadHandleDelayedGuideButton(), SDL_MaybeEnableWarpEmulation(), SDL_PrivateJoystickForceRecentering(), SDL_PushEvent(), SDL_SimulateRenderVSync(), SDL_TimerThread(), SDL_WaitEventTimeout_Device(), SDL_WaitEventTimeoutNS(), SDL_WaitSemaphoreTimeoutNS(), and ZombieAcquireFrame().
SDL_InitTicks()
void SDL_InitTicks (void)
{
    Uint64 tick_freq;
    Uint32 gcd;
    if (tick_start) {
        return;
    }
    /* If we didn't set a precision, set it high. This affects lots of things
       on Windows besides the SDL timers, like audio callbacks, etc. */
    SDL_AddHintCallback(SDL_HINT_TIMER_RESOLUTION,
                        SDL_TimerResolutionChanged, NULL);
    tick_freq = SDL_GetPerformanceFrequency();
    SDL_assert(tick_freq > 0 && tick_freq <= (Uint64)SDL_MAX_UINT32);
    gcd = SDL_CalculateGCD(SDL_NS_PER_SECOND, (Uint32)tick_freq);
    tick_numerator_ns = (SDL_NS_PER_SECOND / gcd);
    tick_denominator_ns = (Uint32)(tick_freq / gcd);
    gcd = SDL_CalculateGCD(SDL_MS_PER_SECOND, (Uint32)tick_freq);
    tick_numerator_ms = (SDL_MS_PER_SECOND / gcd);
    tick_denominator_ms = (Uint32)(tick_freq / gcd);
    tick_start = SDL_GetPerformanceCounter();
    if (!tick_start) {
        --tick_start;
    }
}
References NULL, SDL_AddHintCallback(), SDL_assert, SDL_CalculateGCD(), SDL_GetPerformanceCounter(), SDL_GetPerformanceFrequency(), SDL_HINT_TIMER_RESOLUTION, SDL_MAX_UINT32, SDL_MS_PER_SECOND, SDL_NS_PER_SECOND, SDL_TimerResolutionChanged(), tick_denominator_ms, tick_denominator_ns, tick_numerator_ms, tick_numerator_ns, and tick_start.
Referenced by SDL_GetTicks(), SDL_GetTicksNS(), SDL_InitMainThread(), and SDL_VideoInit().
SDL_InitTimers()
bool SDL_InitTimers (void)
{
    SDL_TimerData *data = &SDL_timer_data;
    if (!SDL_ShouldInit(&data->init)) {
        return true;
    }
    data->timermap_lock = SDL_CreateMutex();
    if (!data->timermap_lock) {
        goto error;
    }
    data->sem = SDL_CreateSemaphore(0);
    if (!data->sem) {
        goto error;
    }
    SDL_SetAtomicInt(&data->active, true);
    // Timer threads use a callback into the app, so we can't set a limited stack size here.
    data->thread = SDL_CreateThread(SDL_TimerThread, "SDLTimer", data);
    if (!data->thread) {
        goto error;
    }
    SDL_SetInitialized(&data->init, true);
    return true;
error:
    SDL_SetInitialized(&data->init, true);
    SDL_QuitTimers();
    return false;
}
References SDL_CreateMutex(), SDL_CreateSemaphore(), SDL_CreateThread, SDL_QuitTimers(), SDL_SetAtomicInt(), SDL_SetInitialized(), SDL_ShouldInit(), SDL_timer_data, and SDL_TimerThread().
Referenced by SDL_CheckInitTimers().
SDL_QuitTicks()
void SDL_QuitTicks (void)
{
    SDL_RemoveHintCallback(SDL_HINT_TIMER_RESOLUTION,
                        SDL_TimerResolutionChanged, NULL);
    SDL_SetSystemTimerResolutionMS(0); // always release our timer resolution request.
    tick_start = 0;
}
References NULL, SDL_HINT_TIMER_RESOLUTION, SDL_RemoveHintCallback(), SDL_SetSystemTimerResolutionMS(), SDL_TimerResolutionChanged(), and tick_start.
Referenced by SDL_QuitMainThread().
SDL_QuitTimers()
void SDL_QuitTimers (void)
{
    SDL_TimerData *data = &SDL_timer_data;
    SDL_Timer *timer;
    SDL_TimerMap *entry;
    if (!SDL_ShouldQuit(&data->init)) {
        return;
    }
    SDL_SetAtomicInt(&data->active, false);
    // Shutdown the timer thread
    if (data->thread) {
        SDL_SignalSemaphore(data->sem);
        SDL_WaitThread(data->thread, NULL);
        data->thread = NULL;
    }
    if (data->sem) {
        SDL_DestroySemaphore(data->sem);
        data->sem = NULL;
    }
    // Clean up the timer entries
    while (data->timers) {
        timer = data->timers;
        data->timers = timer->next;
        SDL_free(timer);
    }
    while (data->freelist) {
        timer = data->freelist;
        data->freelist = timer->next;
        SDL_free(timer);
    }
    while (data->timermap) {
        entry = data->timermap;
        data->timermap = entry->next;
        SDL_free(entry);
    }
    if (data->timermap_lock) {
        SDL_DestroyMutex(data->timermap_lock);
        data->timermap_lock = NULL;
    }
    SDL_SetInitialized(&data->init, false);
}
References SDL_Timer::next, SDL_TimerMap::next, NULL, SDL_DestroyMutex(), SDL_DestroySemaphore(), SDL_free(), SDL_SetAtomicInt(), SDL_SetInitialized(), SDL_ShouldQuit(), SDL_SignalSemaphore(), SDL_timer_data, SDL_WaitThread(), and SDL_TimerMap::timer.
Referenced by SDL_InitTimers(), and SDL_Quit().
SDL_RemoveTimer()
bool SDL_RemoveTimer (SDL_TimerID id)
Remove a timer created with SDL_AddTimer().
Parameters
id the ID of the timer to remove.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddTimer
{
    SDL_TimerData *data = &SDL_timer_data;
    SDL_TimerMap *prev, *entry;
    bool canceled = false;
    if (!id) {
        return SDL_InvalidParamError("id");
    }
    // Find the timer
    SDL_LockMutex(data->timermap_lock);
    prev = NULL;
    for (entry = data->timermap; entry; prev = entry, entry = entry->next) {
        if (entry->timerID == id) {
            if (prev) {
                prev->next = entry->next;
            } else {
                data->timermap = entry->next;
            }
            break;
        }
    }
    SDL_UnlockMutex(data->timermap_lock);
    if (entry) {
        if (!SDL_GetAtomicInt(&entry->timer->canceled)) {
            SDL_SetAtomicInt(&entry->timer->canceled, 1);
            canceled = true;
        }
        SDL_free(entry);
    }
    if (canceled) {
        return true;
    } else {
        return SDL_SetError("Timer not found");
    }
}
References SDL_Timer::canceled, SDL_TimerMap::next, NULL, SDL_free(), SDL_GetAtomicInt(), SDL_InvalidParamError, SDL_LockMutex(), SDL_SetAtomicInt(), SDL_SetError(), SDL_timer_data, SDL_UnlockMutex(), SDL_TimerMap::timer, and SDL_TimerMap::timerID.
Referenced by SDL_CreateTimer().
SDL_SetSystemTimerResolutionMS()
void SDL_SetSystemTimerResolutionMS (int period) static
{
#ifdef HAVE_TIME_BEGIN_PERIOD
    static int timer_period = 0;
    if (period != timer_period) {
        if (timer_period) {
            timeEndPeriod((UINT)timer_period);
        }
        timer_period = period;
        if (timer_period) {
            timeBeginPeriod((UINT)timer_period);
        }
    }
#endif // HAVE_TIME_BEGIN_PERIOD
}
Referenced by SDL_QuitTicks(), and SDL_TimerResolutionChanged().
SDL_TimerResolutionChanged()
void SDLCALL SDL_TimerResolutionChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    int period;
    // Unless the hint says otherwise, let's have good sleep precision
    if (hint && *hint) {
        period = SDL_atoi(hint);
    } else {
        period = 1;
    }
    if (period || oldValue != hint) {
        SDL_SetSystemTimerResolutionMS(period);
    }
}
References SDL_atoi(), SDL_SetSystemTimerResolutionMS(), and SDLCALL.
Referenced by SDL_InitTicks(), and SDL_QuitTicks().
SDL_TimerThread()
int SDLCALL SDL_TimerThread (void * _data) static
{
    SDL_TimerData *data = (SDL_TimerData *)_data;
    SDL_Timer *pending;
    SDL_Timer *current;
    SDL_Timer *freelist_head = NULL;
    SDL_Timer *freelist_tail = NULL;
    Uint64 tick, now, interval, delay;
    /* Threaded timer loop:
     *  1. Queue timers added by other threads
     *  2. Handle any timers that should dispatch this cycle
     *  3. Wait until next dispatch time or new timer arrives
     */
    for (;;) {
        // Pending and freelist maintenance
        SDL_LockSpinlock(&data->lock);
        {
            // Get any timers ready to be queued
            pending = data->pending;
            data->pending = NULL;
            // Make any unused timer structures available
            if (freelist_head) {
                freelist_tail->next = data->freelist;
                data->freelist = freelist_head;
            }
        }
        SDL_UnlockSpinlock(&data->lock);
        // Sort the pending timers into our list
        while (pending) {
            current = pending;
            pending = pending->next;
            SDL_AddTimerInternal(data, current);
        }
        freelist_head = NULL;
        freelist_tail = NULL;
        // Check to see if we're still running, after maintenance
        if (!SDL_GetAtomicInt(&data->active)) {
            break;
        }
        // Initial delay if there are no timers
        delay = (Uint64)-1;
        tick = SDL_GetTicksNS();
        // Process all the pending timers for this tick
        while (data->timers) {
            current = data->timers;
            if (tick < current->scheduled) {
                // Scheduled for the future, wait a bit
                delay = (current->scheduled - tick);
                break;
            }
            // We're going to do something with this timer
            data->timers = current->next;
            if (SDL_GetAtomicInt(&current->canceled)) {
                interval = 0;
            } else {
                if (current->callback_ms) {
                    interval = SDL_MS_TO_NS(current->callback_ms(current->userdata, current->timerID, (Uint32)SDL_NS_TO_MS(current->interval)));
                } else {
                    interval = current->callback_ns(current->userdata, current->timerID, current->interval);
                }
            }
            if (interval > 0) {
                // Reschedule this timer
                current->interval = interval;
                current->scheduled = tick + interval;
                SDL_AddTimerInternal(data, current);
            } else {
                if (!freelist_head) {
                    freelist_head = current;
                }
                if (freelist_tail) {
                    freelist_tail->next = current;
                }
                freelist_tail = current;
                SDL_SetAtomicInt(&current->canceled, 1);
            }
        }
        // Adjust the delay based on processing time
        now = SDL_GetTicksNS();
        interval = (now - tick);
        if (interval > delay) {
            delay = 0;
        } else {
            delay -= interval;
        }
        /* Note that each time a timer is added, this will return
           immediately, but we process the timers added all at once.
           That's okay, it just means we run through the loop a few
           extra times.
         */
        SDL_WaitSemaphoreTimeoutNS(data->sem, delay);
    }
    return 0;
}
References SDL_Timer::callback_ms, SDL_Timer::callback_ns, SDL_Timer::canceled, SDL_Timer::interval, SDL_Timer::next, NULL, SDL_Timer::scheduled, SDL_AddTimerInternal(), SDL_GetAtomicInt(), SDL_GetTicksNS(), SDL_LockSpinlock(), SDL_MS_TO_NS, SDL_NS_TO_MS, SDL_SetAtomicInt(), SDL_UnlockSpinlock(), SDL_WaitSemaphoreTimeoutNS(), SDLCALL, SDL_Timer::timerID, and SDL_Timer::userdata.
Referenced by SDL_InitTimers().
Variable Documentation
SDL_timer_data
SDL_TimerData SDL_timer_data static
Referenced by SDL_CreateTimer(), SDL_InitTimers(), SDL_QuitTimers(), and SDL_RemoveTimer().
tick_denominator_ms
Uint32 tick_denominator_ms static
Referenced by SDL_GetTicks(), and SDL_InitTicks().
tick_denominator_ns
Uint32 tick_denominator_ns static
Referenced by SDL_GetTicksNS(), and SDL_InitTicks().
tick_numerator_ms
Uint32 tick_numerator_ms static
Referenced by SDL_GetTicks(), and SDL_InitTicks().
tick_numerator_ns
Uint32 tick_numerator_ns static
Referenced by SDL_GetTicksNS(), and SDL_InitTicks().
tick_start
Uint64 tick_start static
Referenced by SDL_GetTicks(), SDL_GetTicksNS(), SDL_InitTicks(), and SDL_QuitTicks().