SDL3: SDL-main/src/events/SDL_eventwatch_c.h File Reference
SDL_eventwatch_c.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_EventWatcher
struct SDL_EventWatchList
Typedefs
typedef struct SDL_EventWatcher SDL_EventWatcher
typedef struct SDL_EventWatchList SDL_EventWatchList
Functions
bool SDL_AddEventWatchList (SDL_EventWatchList *list, SDL_EventFilter filter, void *userdata)
bool SDL_DispatchEventWatchList (SDL_EventWatchList *list, SDL_Event *event)
bool SDL_InitEventWatchList (SDL_EventWatchList *list)
void SDL_QuitEventWatchList (SDL_EventWatchList *list)
void SDL_RemoveEventWatchList (SDL_EventWatchList *list, SDL_EventFilter filter, void *userdata)
Typedef Documentation
SDL_EventWatcher
typedef struct SDL_EventWatcher SDL_EventWatcher
SDL_EventWatchList
typedef struct SDL_EventWatchList SDL_EventWatchList
Function Documentation
SDL_AddEventWatchList()
bool SDL_AddEventWatchList (SDL_EventWatchList * list, SDL_EventFilter filter, void * userdata) extern
{
    bool result = true;
    SDL_LockMutex(list->lock);
    {
        SDL_EventWatcher *watchers;
        watchers = (SDL_EventWatcher *)SDL_realloc(list->watchers, (list->count + 1) * sizeof(*watchers));
        if (watchers) {
            SDL_EventWatcher *watcher;
            list->watchers = watchers;
            watcher = &list->watchers[list->count];
            watcher->callback = filter;
            watcher->userdata = userdata;
            watcher->removed = false;
            ++list->count;
        } else {
            result = false;
        }
    }
    SDL_UnlockMutex(list->lock);
    return result;
}
References SDL_EventWatcher::callback, SDL_EventWatchList::count, SDL_EventWatchList::lock, SDL_EventWatcher::removed, SDL_LockMutex(), SDL_realloc(), SDL_UnlockMutex(), SDL_EventWatcher::userdata, and SDL_EventWatchList::watchers.
Referenced by SDL_AddEventWatch(), and SDL_AddWindowEventWatch().
SDL_DispatchEventWatchList()
bool SDL_DispatchEventWatchList (SDL_EventWatchList * list, SDL_Event * event) extern
{
    SDL_EventWatcher *filter = &list->filter;
    if (!filter->callback && list->count == 0) {
        return true;
    }
    SDL_LockMutex(list->lock);
    {
        // Make sure we only dispatch the current watcher list
        int i, count = list->count;
        if (filter->callback && !filter->callback(filter->userdata, event)) {
            SDL_UnlockMutex(list->lock);
            return false;
        }
        list->dispatching = true;
        for (i = 0; i < count; ++i) {
            if (!list->watchers[i].removed) {
                list->watchers[i].callback(list->watchers[i].userdata, event);
            }
        }
        list->dispatching = false;
        if (list->removed) {
            for (i = list->count; i--;) {
                if (list->watchers[i].removed) {
                    --list->count;
                    if (i < list->count) {
                        SDL_memmove(&list->watchers[i], &list->watchers[i + 1], (list->count - i) * sizeof(list->watchers[i]));
                    }
                }
            }
            list->removed = false;
        }
    }
    SDL_UnlockMutex(list->lock);
    return true;
}
References SDL_EventWatcher::callback, count, SDL_EventWatchList::count, SDL_EventWatchList::dispatching, SDL_EventWatchList::filter, SDL_EventWatchList::lock, SDL_EventWatcher::removed, SDL_EventWatchList::removed, SDL_LockMutex(), SDL_memmove, SDL_UnlockMutex(), SDL_EventWatcher::userdata, and SDL_EventWatchList::watchers.
Referenced by SDL_CallEventWatchers(), and SDL_SendWindowEvent().
SDL_InitEventWatchList()
bool SDL_InitEventWatchList (SDL_EventWatchList * list) extern
{
    if (list->lock == NULL) {
        list->lock = SDL_CreateMutex();
        if (list->lock == NULL) {
            return false;
        }
    }
    return true;
}
References SDL_EventWatchList::lock, NULL, and SDL_CreateMutex().
Referenced by SDL_InitWindowEventWatch(), and SDL_StartEventLoop().
SDL_QuitEventWatchList()
void SDL_QuitEventWatchList (SDL_EventWatchList * list) extern
{
    if (list->lock) {
        SDL_DestroyMutex(list->lock);
        list->lock = NULL;
    }
    if (list->watchers) {
        SDL_free(list->watchers);
        list->watchers = NULL;
        list->count = 0;
    }
    SDL_zero(list->filter);
}
References SDL_EventWatchList::count, SDL_EventWatchList::filter, SDL_EventWatchList::lock, NULL, SDL_DestroyMutex(), SDL_free(), SDL_zero, and SDL_EventWatchList::watchers.
Referenced by SDL_QuitWindowEventWatch(), and SDL_StopEventLoop().
SDL_RemoveEventWatchList()
void SDL_RemoveEventWatchList (SDL_EventWatchList * list, SDL_EventFilter filter, void * userdata) extern
{
    SDL_LockMutex(list->lock);
    {
        int i;
        for (i = 0; i < list->count; ++i) {
            if (list->watchers[i].callback == filter && list->watchers[i].userdata == userdata) {
                if (list->dispatching) {
                    list->watchers[i].removed = true;
                    list->removed = true;
                } else {
                    --list->count;
                    if (i < list->count) {
                        SDL_memmove(&list->watchers[i], &list->watchers[i + 1], (list->count - i) * sizeof(list->watchers[i]));
                    }
                }
                break;
            }
        }
    }
    SDL_UnlockMutex(list->lock);
}
References SDL_EventWatcher::callback, count, SDL_EventWatchList::count, SDL_EventWatchList::dispatching, SDL_EventWatchList::lock, SDL_EventWatcher::removed, SDL_EventWatchList::removed, SDL_LockMutex(), SDL_memmove, SDL_UnlockMutex(), SDL_EventWatcher::userdata, and SDL_EventWatchList::watchers.
Referenced by SDL_RemoveEventWatch(), and SDL_RemoveWindowEventWatch().