SDL3: SDL-main/src/video/SDL_stretch.c File Reference
SDL_stretch.c File Reference
#include "SDL_internal.h"
#include "SDL_surface_c.h"
Data Structures
struct color_t
Macros
#define BILINEAR___HEIGHT
#define BILINEAR___START
#define FIXED_POINT(i)
#define FP_ONE FIXED_POINT(1)
#define FRAC(fp)
#define FRAC_ONE (1 << PRECISION)
#define FRAC_ZERO 0
#define INTEGER(fp)
#define PRECISION 7
#define SDL_SCALE_NEAREST__HEIGHT
#define SDL_SCALE_NEAREST__START
#define SRC_INDEX(fp)
Typedefs
typedef struct color_t color_t
Functions
static void get_scaler_datas (int src_nb, int dst_nb, Sint64 *fp_start, int *fp_step, int *left_pad, int *right_pad)
static SDL_INLINE void INTERPOL (const Uint32 *src_x0, const Uint32 *src_x1, int frac0, int frac1, Uint32 *dst)
static SDL_INLINE void INTERPOL_BILINEAR (const Uint32 *s0, const Uint32 *s1, int frac_w0, int frac_h0, int frac_h1, Uint32 *dst)
static bool scale_mat (const Uint32 *src, int src_w, int src_h, int src_pitch, Uint32 *dst, int dst_w, int dst_h, int dst_pitch)
static bool scale_mat_nearest_1 (const Uint32 *src_ptr, int src_w, int src_h, int src_pitch, Uint32 *dst, int dst_w, int dst_h, int dst_pitch)
static bool scale_mat_nearest_2 (const Uint32 *src_ptr, int src_w, int src_h, int src_pitch, Uint32 *dst, int dst_w, int dst_h, int dst_pitch)
static bool scale_mat_nearest_3 (const Uint32 *src_ptr, int src_w, int src_h, int src_pitch, Uint32 *dst, int dst_w, int dst_h, int dst_pitch)
static bool scale_mat_nearest_4 (const Uint32 *src_ptr, int src_w, int src_h, int src_pitch, Uint32 *dst, int dst_w, int dst_h, int dst_pitch)
bool SDL_StretchSurface (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect, SDL_ScaleMode scaleMode)
static bool SDL_StretchSurfaceUncheckedLinear (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
static bool SDL_StretchSurfaceUncheckedNearest (SDL_Surface *src, const SDL_Rect *srcrect, SDL_Surface *dst, const SDL_Rect *dstrect)
Macro Definition Documentation
BILINEAR___HEIGHT
#define BILINEAR___HEIGHT
Value:
    int index_h, frac_h0, frac_h1, middle;                             \
    const Uint32 *src_h0, *src_h1;                                     \
    int no_padding;                                                    \
    Uint64 incr_h0, incr_h1;                                           \
                                                                       \
    no_padding = !(i < left_pad_h || i > dst_h - 1 - right_pad_h);     \
    index_h = SRC_INDEX(fp_sum_h);                                     \
    frac_h0 = FRAC(fp_sum_h);                                          \
                                                                       \
    index_h = no_padding ? index_h : (i < left_pad_h ? 0 : src_h - 1); \
    frac_h0 = no_padding ? frac_h0 : 0;                                \
    incr_h1 = no_padding ? src_pitch : 0;                              \
    incr_h0 = (Uint64)index_h * src_pitch;                             \
                                                                       \
    src_h0 = (const Uint32 *)((const Uint8 *)src + incr_h0);           \
    src_h1 = (const Uint32 *)((const Uint8 *)src_h0 + incr_h1);        \
                                                                       \
    fp_sum_h += fp_step_h;                                             \
                                                                       \
    frac_h1 = FRAC_ONE - frac_h0;                                      \
    fp_sum_w = fp_sum_w_init;                                          \
    right_pad_w = right_pad_w_init;                                    \
    left_pad_w = left_pad_w_init;                                      \
    middle = middle_init;
#define BILINEAR___HEIGHT                                              \
    int index_h, frac_h0, frac_h1, middle;                             \
    const Uint32 *src_h0, *src_h1;                                     \
    int no_padding;                                                    \
    Uint64 incr_h0, incr_h1;                                           \
                                                                       \
    no_padding = !(i < left_pad_h || i > dst_h - 1 - right_pad_h);     \
    index_h = SRC_INDEX(fp_sum_h);                                     \
    frac_h0 = FRAC(fp_sum_h);                                          \
                                                                       \
    index_h = no_padding ? index_h : (i < left_pad_h ? 0 : src_h - 1); \
    frac_h0 = no_padding ? frac_h0 : 0;                                \
    incr_h1 = no_padding ? src_pitch : 0;                              \
    incr_h0 = (Uint64)index_h * src_pitch;                             \
                                                                       \
    src_h0 = (const Uint32 *)((const Uint8 *)src + incr_h0);           \
    src_h1 = (const Uint32 *)((const Uint8 *)src_h0 + incr_h1);        \
                                                                       \
    fp_sum_h += fp_step_h;                                             \
                                                                       \
    frac_h1 = FRAC_ONE - frac_h0;                                      \
    fp_sum_w = fp_sum_w_init;                                          \
    right_pad_w = right_pad_w_init;                                    \
    left_pad_w = left_pad_w_init;                                      \
    middle = middle_init;
Referenced by scale_mat().
BILINEAR___START
#define BILINEAR___START
Value:
    int i;                                                                            \
    Sint64 fp_sum_h;                                                                  \
    int fp_step_h, left_pad_h, right_pad_h;                                           \
    Sint64 fp_sum_w;                                                                  \
    int fp_step_w, left_pad_w, right_pad_w;                                           \
    Sint64 fp_sum_w_init;                                                             \
    int left_pad_w_init, right_pad_w_init, dst_gap, middle_init;                      \
    get_scaler_datas(src_h, dst_h, &fp_sum_h, &fp_step_h, &left_pad_h, &right_pad_h); \
    get_scaler_datas(src_w, dst_w, &fp_sum_w, &fp_step_w, &left_pad_w, &right_pad_w); \
    fp_sum_w_init = fp_sum_w + left_pad_w * fp_step_w;                                \
    left_pad_w_init = left_pad_w;                                                     \
    right_pad_w_init = right_pad_w;                                                   \
    dst_gap = dst_pitch - 4 * dst_w;                                                  \
    middle_init = dst_w - left_pad_w - right_pad_w;
#define BILINEAR___START                                                              \
    int i;                                                                            \
    Sint64 fp_sum_h;                                                                  \
    int fp_step_h, left_pad_h, right_pad_h;                                           \
    Sint64 fp_sum_w;                                                                  \
    int fp_step_w, left_pad_w, right_pad_w;                                           \
    Sint64 fp_sum_w_init;                                                             \
    int left_pad_w_init, right_pad_w_init, dst_gap, middle_init;                      \
    get_scaler_datas(src_h, dst_h, &fp_sum_h, &fp_step_h, &left_pad_h, &right_pad_h); \
    get_scaler_datas(src_w, dst_w, &fp_sum_w, &fp_step_w, &left_pad_w, &right_pad_w); \
    fp_sum_w_init = fp_sum_w + left_pad_w * fp_step_w;                                \
    left_pad_w_init = left_pad_w;                                                     \
    right_pad_w_init = right_pad_w;                                                   \
    dst_gap = dst_pitch - 4 * dst_w;                                                  \
    middle_init = dst_w - left_pad_w - right_pad_w;
Referenced by scale_mat().
FIXED_POINT
#define FIXED_POINT (i)
Value:
((Uint32)(i) << 16)
Referenced by get_scaler_datas().
FP_ONE
#define FP_ONE FIXED_POINT(1)
Referenced by get_scaler_datas().
FRAC
#define FRAC (fp)
Value:
((Uint32)((fp) >> (16 - PRECISION)) & ((1 << PRECISION) - 1))
Referenced by scale_mat().
FRAC_ONE
#define FRAC_ONE (1 << PRECISION)
Referenced by INTERPOL_BILINEAR(), and scale_mat().
FRAC_ZERO
#define FRAC_ZERO 0
Referenced by scale_mat().
INTEGER
#define INTEGER (fp)
Value:
((Uint32)(fp) >> PRECISION)
Referenced by INTERPOL().
PRECISION
#define PRECISION 7
SDL_SCALE_NEAREST__HEIGHT
#define SDL_SCALE_NEAREST__HEIGHT
Value:
    srcy = (posy >> 16);                                                  \
    src_h0 = (const Uint32 *)((const Uint8 *)src_ptr + srcy * src_pitch); \
    posy += incy;                                                         \
    posx = incx / 2;                                                      \
    n = dst_w;
#define SDL_SCALE_NEAREST__HEIGHT                                         \
    srcy = (posy >> 16);                                                  \
    src_h0 = (const Uint32 *)((const Uint8 *)src_ptr + srcy * src_pitch); \
    posy += incy;                                                         \
    posx = incx / 2;                                                      \
    n = dst_w;
Referenced by scale_mat_nearest_1(), scale_mat_nearest_2(), scale_mat_nearest_3(), and scale_mat_nearest_4().
SDL_SCALE_NEAREST__START
#define SDL_SCALE_NEAREST__START
Value:
    int i;                                \
    Uint64 posy, incy;                    \
    Uint64 posx, incx;                    \
    Uint64 srcy, srcx;                    \
    int dst_gap, n;                       \
    const Uint32 *src_h0;                 \
    incy = ((Uint64)src_h << 16) / dst_h; \
    incx = ((Uint64)src_w << 16) / dst_w; \
    dst_gap = dst_pitch - bpp * dst_w;    \
    posy = incy / 2;
#define SDL_SCALE_NEAREST__START          \
    int i;                                \
    Uint64 posy, incy;                    \
    Uint64 posx, incx;                    \
    Uint64 srcy, srcx;                    \
    int dst_gap, n;                       \
    const Uint32 *src_h0;                 \
    incy = ((Uint64)src_h << 16) / dst_h; \
    incx = ((Uint64)src_w << 16) / dst_w; \
    dst_gap = dst_pitch - bpp * dst_w;    \
    posy = incy / 2;
Referenced by scale_mat_nearest_1(), scale_mat_nearest_2(), scale_mat_nearest_3(), and scale_mat_nearest_4().
SRC_INDEX
#define SRC_INDEX (fp)
Value:
((Uint32)(fp) >> 16)
Referenced by get_scaler_datas(), and scale_mat().
Typedef Documentation
color_t
typedef struct color_t color_t
Function Documentation
get_scaler_datas()
void get_scaler_datas (int src_nb, int dst_nb, Sint64 * fp_start, int * fp_step, int * left_pad, int * right_pad) static
{
    int step = FIXED_POINT(src_nb) / (dst_nb); // source step in fixed point
    int x0 = FP_ONE / 2;                       // dst first pixel center at 0.5 in fixed point
    Sint64 fp_sum;
    int i;
#if 0
    // scale to source coordinates
    x0 *= src_nb;
    x0 /= dst_nb; // x0 == step / 2
#else
    // Use this code for perfect match with pixman
    Sint64 tmp[2];
    tmp[0] = (Sint64)step * (x0 >> 16);
    tmp[1] = (Sint64)step * (x0 & 0xFFFF);
    x0 = (int)(tmp[0] + ((tmp[1] + 0x8000) >> 16)); // x0 == (step + 1) / 2
#endif
    // -= 0.5, get back the pixel origin, in source coordinates
    x0 -= FP_ONE / 2;
    *fp_start = x0;
    *fp_step = step;
    *left_pad = 0;
    *right_pad = 0;
    fp_sum = x0;
    for (i = 0; i < dst_nb; i++) {
        if (fp_sum < 0) {
            *left_pad += 1;
        } else {
            int index = SRC_INDEX(fp_sum);
            if (index > src_nb - 2) {
                *right_pad += 1;
            }
        }
        fp_sum += step;
    }
    //    SDL_Log("%d -> %d  x0=%d step=%d left_pad=%d right_pad=%d", src_nb, dst_nb, *fp_start, *fp_step, *left_pad, *right_pad);
}
References FIXED_POINT, FP_ONE, and SRC_INDEX.
INTERPOL()
SDL_INLINE void INTERPOL (const Uint32 * src_x0, const Uint32 * src_x1, int frac0, int frac1, Uint32 * dst) static
{
    const color_t *c0 = (const color_t *)src_x0;
    const color_t *c1 = (const color_t *)src_x1;
    color_t *cx = (color_t *)dst;
#if 0
    cx->a = c0->a + INTEGER(frac0 * (c1->a - c0->a));
    cx->b = c0->b + INTEGER(frac0 * (c1->b - c0->b));
    cx->c = c0->c + INTEGER(frac0 * (c1->c - c0->c));
    cx->d = c0->d + INTEGER(frac0 * (c1->d - c0->d));
#else
    cx->a = (Uint8)INTEGER(frac1 * c0->a + frac0 * c1->a);
    cx->b = (Uint8)INTEGER(frac1 * c0->b + frac0 * c1->b);
    cx->c = (Uint8)INTEGER(frac1 * c0->c + frac0 * c1->c);
    cx->d = (Uint8)INTEGER(frac1 * c0->d + frac0 * c1->d);
#endif
}
References color_t::a, color_t::b, color_t::c, color_t::d, INTEGER, and SDL_INLINE.
Referenced by INTERPOL_BILINEAR().
INTERPOL_BILINEAR()
SDL_INLINE void INTERPOL_BILINEAR (const Uint32 * s0, const Uint32 * s1, int frac_w0, int frac_h0, int frac_h1, Uint32 * dst) static
{
    Uint32 tmp[2];
    unsigned int frac_w1 = FRAC_ONE - frac_w0;
    // Vertical first, store to 'tmp'
    INTERPOL(s0, s1, frac_h0, frac_h1, tmp);
    INTERPOL(s0 + 1, s1 + 1, frac_h0, frac_h1, tmp + 1);
    // Horizontal, store to 'dst'
    INTERPOL(tmp, tmp + 1, frac_w0, frac_w1, dst);
}
References FRAC_ONE, INTERPOL(), and SDL_INLINE.
Referenced by scale_mat().
scale_mat()
bool scale_mat (const Uint32 * src, int src_w, int src_h, int src_pitch, Uint32 * dst, int dst_w, int dst_h, int dst_pitch) static
{
    BILINEAR___START
    for (i = 0; i < dst_h; i++) {
        BILINEAR___HEIGHT
        while (left_pad_w--) {
            INTERPOL_BILINEAR(src_h0, src_h1, FRAC_ZERO, frac_h0, frac_h1, dst);
            dst += 1;
        }
        while (middle--) {
            const Uint32 *s_00_01;
            const Uint32 *s_10_11;
            int index_w = 4 * SRC_INDEX(fp_sum_w);
            int frac_w = FRAC(fp_sum_w);
            fp_sum_w += fp_step_w;
            /*
                        x00 ... x0_ ..... x01
                        .       .         .
                        .       x         .
                        .       .         .
                        .       .         .
                        x10 ... x1_ ..... x11
            */
            s_00_01 = (const Uint32 *)((const Uint8 *)src_h0 + index_w);
            s_10_11 = (const Uint32 *)((const Uint8 *)src_h1 + index_w);
            INTERPOL_BILINEAR(s_00_01, s_10_11, frac_w, frac_h0, frac_h1, dst);
            dst += 1;
        }
        while (right_pad_w--) {
            int index_w = 4 * (src_w - 2);
            const Uint32 *s_00_01 = (const Uint32 *)((const Uint8 *)src_h0 + index_w);
            const Uint32 *s_10_11 = (const Uint32 *)((const Uint8 *)src_h1 + index_w);
            INTERPOL_BILINEAR(s_00_01, s_10_11, FRAC_ONE, frac_h0, frac_h1, dst);
            dst += 1;
        }
        dst = (Uint32 *)((Uint8 *)dst + dst_gap);
    }
    return true;
}
References BILINEAR___HEIGHT, BILINEAR___START, FRAC, FRAC_ONE, FRAC_ZERO, INTERPOL_BILINEAR(), and SRC_INDEX.
Referenced by SDL_StretchSurfaceUncheckedLinear().
scale_mat_nearest_1()
bool scale_mat_nearest_1 (const Uint32 * src_ptr, int src_w, int src_h, int src_pitch, Uint32 * dst, int dst_w, int dst_h, int dst_pitch) static
{
    Uint32 bpp = 1;
    SDL_SCALE_NEAREST__START
    for (i = 0; i < dst_h; i++) {
        SDL_SCALE_NEAREST__HEIGHT
        while (n--) {
            const Uint8 *src;
            srcx = bpp * (posx >> 16);
            posx += incx;
            src = (const Uint8 *)src_h0 + srcx;
            *(Uint8 *)dst = *src;
            dst = (Uint32 *)((Uint8 *)dst + bpp);
        }
        dst = (Uint32 *)((Uint8 *)dst + dst_gap);
    }
    return true;
}
References SDL_SCALE_NEAREST__HEIGHT, and SDL_SCALE_NEAREST__START.
Referenced by SDL_StretchSurfaceUncheckedNearest().
scale_mat_nearest_2()
bool scale_mat_nearest_2 (const Uint32 * src_ptr, int src_w, int src_h, int src_pitch, Uint32 * dst, int dst_w, int dst_h, int dst_pitch) static
{
    Uint32 bpp = 2;
    SDL_SCALE_NEAREST__START
    for (i = 0; i < dst_h; i++) {
        SDL_SCALE_NEAREST__HEIGHT
        while (n--) {
            const Uint16 *src;
            srcx = bpp * (posx >> 16);
            posx += incx;
            src = (const Uint16 *)((const Uint8 *)src_h0 + srcx);
            *(Uint16 *)dst = *src;
            dst = (Uint32 *)((Uint8 *)dst + bpp);
        }
        dst = (Uint32 *)((Uint8 *)dst + dst_gap);
    }
    return true;
}
References SDL_SCALE_NEAREST__HEIGHT, and SDL_SCALE_NEAREST__START.
Referenced by SDL_StretchSurfaceUncheckedNearest().
scale_mat_nearest_3()
bool scale_mat_nearest_3 (const Uint32 * src_ptr, int src_w, int src_h, int src_pitch, Uint32 * dst, int dst_w, int dst_h, int dst_pitch) static
{
    Uint32 bpp = 3;
    SDL_SCALE_NEAREST__START
    for (i = 0; i < dst_h; i++) {
        SDL_SCALE_NEAREST__HEIGHT
        while (n--) {
            const Uint8 *src;
            srcx = bpp * (posx >> 16);
            posx += incx;
            src = (const Uint8 *)src_h0 + srcx;
            ((Uint8 *)dst)[0] = src[0];
            ((Uint8 *)dst)[1] = src[1];
            ((Uint8 *)dst)[2] = src[2];
            dst = (Uint32 *)((Uint8 *)dst + bpp);
        }
        dst = (Uint32 *)((Uint8 *)dst + dst_gap);
    }
    return true;
}
References SDL_SCALE_NEAREST__HEIGHT, and SDL_SCALE_NEAREST__START.
Referenced by SDL_StretchSurfaceUncheckedNearest().
scale_mat_nearest_4()
bool scale_mat_nearest_4 (const Uint32 * src_ptr, int src_w, int src_h, int src_pitch, Uint32 * dst, int dst_w, int dst_h, int dst_pitch) static
{
    Uint32 bpp = 4;
    SDL_SCALE_NEAREST__START
    for (i = 0; i < dst_h; i++) {
        SDL_SCALE_NEAREST__HEIGHT
        while (n--) {
            const Uint32 *src;
            srcx = bpp * (posx >> 16);
            posx += incx;
            src = (const Uint32 *)((const Uint8 *)src_h0 + srcx);
            *dst = *src;
            dst = (Uint32 *)((Uint8 *)dst + bpp);
        }
        dst = (Uint32 *)((Uint8 *)dst + dst_gap);
    }
    return true;
}
References SDL_SCALE_NEAREST__HEIGHT, and SDL_SCALE_NEAREST__START.
Referenced by SDL_StretchSurfaceUncheckedNearest().
SDL_StretchSurface()
bool SDL_StretchSurface (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect, SDL_ScaleMode scaleMode)
Perform a stretched pixel copy from one surface to another.
Parameters
src the SDL_Surface structure to be copied from.
srcrect the SDL_Rect structure representing the rectangle to be copied, or NULL to copy the entire surface.
dst the SDL_Surface structure that is the blit target.
dstrect the SDL_Rect structure representing the target rectangle in the destination surface, or NULL to fill the entire destination surface.
scaleMode the SDL_ScaleMode to be used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
Only one thread should be using the src and dst surfaces at any given time.
Since
This function is available since SDL 3.4.0.
See also
SDL_BlitSurfaceScaled
{
    bool result;
    int src_locked;
    int dst_locked;
    SDL_Rect full_src;
    SDL_Rect full_dst;
    if (!src) {
        return SDL_InvalidParamError("src");
    }
    if (!dst) {
        return SDL_InvalidParamError("dst");
    }
    if (src->format != dst->format) {
        // Slow!
        SDL_Surface *src_tmp = SDL_ConvertSurfaceAndColorspace(src, dst->format, dst->palette, dst->colorspace, dst->props);
        if (!src_tmp) {
            return false;
        }
        result = SDL_StretchSurface(src_tmp, srcrect, dst, dstrect, scaleMode);
        SDL_DestroySurface(src_tmp);
        return result;
    }
    if (SDL_ISPIXELFORMAT_FOURCC(src->format)) {
        // Slow!
        if (!dstrect) {
            full_dst.x = 0;
            full_dst.y = 0;
            full_dst.w = dst->w;
            full_dst.h = dst->h;
            dstrect = &full_dst;
        }
        SDL_Surface *src_tmp = SDL_ConvertSurface(src, SDL_PIXELFORMAT_XRGB8888);
        SDL_Surface *dst_tmp = SDL_CreateSurface(dstrect->w, dstrect->h, SDL_PIXELFORMAT_XRGB8888);
        if (src_tmp && dst_tmp) {
            result = SDL_StretchSurface(src_tmp, srcrect, dst_tmp, NULL, scaleMode);
            if (result) {
                result = SDL_ConvertPixelsAndColorspace(dstrect->w, dstrect->h,
                            dst_tmp->format, SDL_COLORSPACE_SRGB, 0,
                            dst_tmp->pixels, dst_tmp->pitch,
                            dst->format, dst->colorspace, SDL_GetSurfaceProperties(dst),
                            (Uint8 *)dst->pixels + dstrect->y * dst->pitch + dstrect->x * SDL_BYTESPERPIXEL(dst->format), dst->pitch);
            }
        } else {
            result = false;
        }
        SDL_DestroySurface(src_tmp);
        SDL_DestroySurface(dst_tmp);
        return result;
    }
    switch (scaleMode) {
    case SDL_SCALEMODE_NEAREST:
        break;
    case SDL_SCALEMODE_LINEAR:
        break;
    case SDL_SCALEMODE_PIXELART:
        scaleMode = SDL_SCALEMODE_NEAREST;
        break;
    default:
        return SDL_InvalidParamError("scaleMode");
    }
    if (scaleMode == SDL_SCALEMODE_LINEAR) {
        if (SDL_BYTESPERPIXEL(src->format) != 4 || src->format == SDL_PIXELFORMAT_ARGB2101010) {
            return SDL_SetError("Wrong format");
        }
    }
    // Verify the blit rectangles
    if (srcrect) {
        if ((srcrect->x < 0) || (srcrect->y < 0) ||
            ((srcrect->x + srcrect->w) > src->w) ||
            ((srcrect->y + srcrect->h) > src->h)) {
            return SDL_SetError("Invalid source blit rectangle");
        }
    } else {
        full_src.x = 0;
        full_src.y = 0;
        full_src.w = src->w;
        full_src.h = src->h;
        srcrect = &full_src;
    }
    if (dstrect) {
        if ((dstrect->x < 0) || (dstrect->y < 0) ||
            ((dstrect->x + dstrect->w) > dst->w) ||
            ((dstrect->y + dstrect->h) > dst->h)) {
            return SDL_SetError("Invalid destination blit rectangle");
        }
    } else {
        full_dst.x = 0;
        full_dst.y = 0;
        full_dst.w = dst->w;
        full_dst.h = dst->h;
        dstrect = &full_dst;
    }
    if (dstrect->w <= 0 || dstrect->h <= 0) {
        return true;
    }
    if (srcrect->w > SDL_MAX_UINT16 || srcrect->h > SDL_MAX_UINT16 ||
        dstrect->w > SDL_MAX_UINT16 || dstrect->h > SDL_MAX_UINT16) {
        return SDL_SetError("Size too large for scaling");
    }
    // Lock the destination if it's in hardware
    dst_locked = 0;
    if (SDL_MUSTLOCK(dst)) {
        if (!SDL_LockSurface(dst)) {
            return SDL_SetError("Unable to lock destination surface");
        }
        dst_locked = 1;
    }
    // Lock the source if it's in hardware
    src_locked = 0;
    if (SDL_MUSTLOCK(src)) {
        if (!SDL_LockSurface(src)) {
            if (dst_locked) {
                SDL_UnlockSurface(dst);
            }
            return SDL_SetError("Unable to lock source surface");
        }
        src_locked = 1;
    }
    if (scaleMode == SDL_SCALEMODE_NEAREST) {
        result = SDL_StretchSurfaceUncheckedNearest(src, srcrect, dst, dstrect);
    } else {
        result = SDL_StretchSurfaceUncheckedLinear(src, srcrect, dst, dstrect);
    }
    // We need to unlock the surfaces if they're locked
    if (dst_locked) {
        SDL_UnlockSurface(dst);
    }
    if (src_locked) {
        SDL_UnlockSurface(src);
    }
    return result;
}
References SDL_Surface::colorspace, SDL_Surface::format, SDL_Rect::h, SDL_Surface::h, NULL, SDL_Surface::palette, SDL_Surface::pitch, SDL_Surface::pixels, SDL_Surface::props, SDL_BYTESPERPIXEL, SDL_COLORSPACE_SRGB, SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurface(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateSurface(), SDL_DestroySurface(), SDL_GetSurfaceProperties(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_FOURCC, SDL_LockSurface(), SDL_MAX_UINT16, SDL_MUSTLOCK, SDL_PIXELFORMAT_ARGB2101010, SDL_PIXELFORMAT_XRGB8888, SDL_SCALEMODE_LINEAR, SDL_SCALEMODE_NEAREST, SDL_SCALEMODE_PIXELART, SDL_SetError(), SDL_StretchSurface(), SDL_StretchSurfaceUncheckedLinear(), SDL_StretchSurfaceUncheckedNearest(), SDL_UnlockSurface(), SDL_Rect::w, SDL_Surface::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_BlitSurfaceUncheckedScaled(), SDL_CameraThreadIterate(), and SDL_StretchSurface().
SDL_StretchSurfaceUncheckedLinear()
bool SDL_StretchSurfaceUncheckedLinear (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect) static
{
    bool result = false;
    int src_w = srcrect->w;
    int src_h = srcrect->h;
    int dst_w = dstrect->w;
    int dst_h = dstrect->h;
    int src_pitch = s->pitch;
    int dst_pitch = d->pitch;
    Uint32 *src = (Uint32 *)((Uint8 *)s->pixels + srcrect->x * 4 + srcrect->y * src_pitch);
    Uint32 *dst = (Uint32 *)((Uint8 *)d->pixels + dstrect->x * 4 + dstrect->y * dst_pitch);
#ifdef SDL_NEON_INTRINSICS
    if (!result && hasNEON()) {
        result = scale_mat_NEON(src, src_w, src_h, src_pitch, dst, dst_w, dst_h, dst_pitch);
    }
#endif
#ifdef SDL_SSE2_INTRINSICS
    if (!result && hasSSE2()) {
        result = scale_mat_SSE(src, src_w, src_h, src_pitch, dst, dst_w, dst_h, dst_pitch);
    }
#endif
    if (!result) {
        result = scale_mat(src, src_w, src_h, src_pitch, dst, dst_w, dst_h, dst_pitch);
    }
    return result;
}
References d, SDL_Rect::h, SDL_Surface::pitch, SDL_Surface::pixels, scale_mat(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_StretchSurface().
SDL_StretchSurfaceUncheckedNearest()
bool SDL_StretchSurfaceUncheckedNearest (SDL_Surface * src, const SDL_Rect * srcrect, SDL_Surface * dst, const SDL_Rect * dstrect) static
{
    int src_w = srcrect->w;
    int src_h = srcrect->h;
    int dst_w = dstrect->w;
    int dst_h = dstrect->h;
    int src_pitch = s->pitch;
    int dst_pitch = d->pitch;
    int bpp = SDL_BYTESPERPIXEL(d->format);
    Uint32 *src = (Uint32 *)((Uint8 *)s->pixels + srcrect->x * bpp + srcrect->y * src_pitch);
    Uint32 *dst = (Uint32 *)((Uint8 *)d->pixels + dstrect->x * bpp + dstrect->y * dst_pitch);
    if (bpp == 4) {
        return scale_mat_nearest_4(src, src_w, src_h, src_pitch, dst, dst_w, dst_h, dst_pitch);
    } else if (bpp == 3) {
        return scale_mat_nearest_3(src, src_w, src_h, src_pitch, dst, dst_w, dst_h, dst_pitch);
    } else if (bpp == 2) {
        return scale_mat_nearest_2(src, src_w, src_h, src_pitch, dst, dst_w, dst_h, dst_pitch);
    } else {
        return scale_mat_nearest_1(src, src_w, src_h, src_pitch, dst, dst_w, dst_h, dst_pitch);
    }
}
References d, SDL_Rect::h, SDL_Surface::pitch, SDL_Surface::pixels, scale_mat_nearest_1(), scale_mat_nearest_2(), scale_mat_nearest_3(), scale_mat_nearest_4(), SDL_BYTESPERPIXEL, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_StretchSurface().