SDL3: SDL-main/src/hidapi/mac/hid.c File Reference
hid.c File Reference
#include <IOKit/hid/IOHIDManager.h>
#include <IOKit/hid/IOHIDKeys.h>
#include <IOKit/IOKitLib.h>
#include <IOKit/usb/USBSpec.h>
#include <CoreFoundation/CoreFoundation.h>
#include <mach/mach_error.h>
#include <stdbool.h>
#include <wchar.h>
#include <locale.h>
#include <pthread.h>
#include <sys/time.h>
#include <unistd.h>
#include <dlfcn.h>
#include "hidapi_darwin.h"
Data Structures
struct input_report
struct PLATFORM_hid_device_
struct pthread_barrier
Typedefs
typedef struct pthread_barrier pthread_barrier_t
typedef int pthread_barrierattr_t
Functions
static int cond_timedwait (PLATFORM_hid_device *dev, pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abstime)
static int cond_wait (PLATFORM_hid_device *dev, pthread_cond_t *cond, pthread_mutex_t *mutex)
static struct hid_device_info * create_device_info (IOHIDDeviceRef device)
static struct hid_device_info * create_device_info_with_usage (IOHIDDeviceRef dev, int32_t usage_page, int32_t usage)
static wchar_t * dup_wcs (const wchar_t *s)
static void free_hid_device (PLATFORM_hid_device *dev)
static CFArrayRef get_array_property (IOHIDDeviceRef device, CFStringRef key)
static int32_t get_int_property (IOHIDDeviceRef device, CFStringRef key)
static int get_manufacturer_string (IOHIDDeviceRef device, wchar_t *buf, size_t len)
static int32_t get_max_report_length (IOHIDDeviceRef device)
static unsigned short get_product_id (IOHIDDeviceRef device)
static int get_product_string (IOHIDDeviceRef device, wchar_t *buf, size_t len)
static int get_report (PLATFORM_hid_device *dev, IOHIDReportType type, unsigned char *data, size_t length)
static int get_serial_number (IOHIDDeviceRef device, wchar_t *buf, size_t len)
static int get_string_property (IOHIDDeviceRef device, CFStringRef prop, wchar_t *buf, size_t len)
static CFArrayRef get_usage_pairs (IOHIDDeviceRef device)
static unsigned short get_vendor_id (IOHIDDeviceRef device)
int hid_darwin_get_location_id (PLATFORM_hid_device *dev, uint32_t *location_id)
Get the location ID for a HID device.
int hid_darwin_get_open_exclusive (void)
Getter for option set by hid_darwin_set_open_exclusive.
int hid_darwin_is_device_open_exclusive (PLATFORM_hid_device *dev)
Check how the device was opened.
void hid_darwin_set_open_exclusive (int open_exclusive)
Changes the behavior of all further calls to hid_open or hid_open_path.
static void hid_device_removal_callback (void *context, IOReturn result, void *sender)
static io_registry_entry_t hid_open_service_registry_from_path (const char *path)
static void hid_report_callback (void *context, IOReturn result, void *sender, IOHIDReportType report_type, uint32_t report_id, uint8_t *report, CFIndex report_length)
static int init_hid_manager (void)
static PLATFORM_hid_device * new_hid_device (void)
static void perform_signal_callback (void *context)
void PLATFORM_hid_close (PLATFORM_hid_device *dev)
struct hid_device_info * PLATFORM_hid_enumerate (unsigned short vendor_id, unsigned short product_id)
const wchar_t * PLATFORM_hid_error (PLATFORM_hid_device *dev)
int PLATFORM_hid_exit (void)
void PLATFORM_hid_free_enumeration (struct hid_device_info *devs)
struct hid_device_info * PLATFORM_hid_get_device_info (PLATFORM_hid_device *dev)
int PLATFORM_hid_get_feature_report (PLATFORM_hid_device *dev, unsigned char *data, size_t length)
int PLATFORM_hid_get_indexed_string (PLATFORM_hid_device *dev, int string_index, wchar_t *string, size_t maxlen)
int PLATFORM_hid_get_input_report (PLATFORM_hid_device *dev, unsigned char *data, size_t length)
int PLATFORM_hid_get_manufacturer_string (PLATFORM_hid_device *dev, wchar_t *string, size_t maxlen)
int PLATFORM_hid_get_product_string (PLATFORM_hid_device *dev, wchar_t *string, size_t maxlen)
int PLATFORM_hid_get_report_descriptor (PLATFORM_hid_device *dev, unsigned char *buf, size_t buf_size)
int PLATFORM_hid_get_serial_number_string (PLATFORM_hid_device *dev, wchar_t *string, size_t maxlen)
int PLATFORM_hid_init (void)
PLATFORM_hid_device * PLATFORM_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
PLATFORM_hid_device * PLATFORM_hid_open_path (const char *path)
int PLATFORM_hid_read (PLATFORM_hid_device *dev, unsigned char *data, size_t length)
int PLATFORM_hid_read_timeout (PLATFORM_hid_device *dev, unsigned char *data, size_t length, int milliseconds)
int PLATFORM_hid_send_feature_report (PLATFORM_hid_device *dev, const unsigned char *data, size_t length)
int PLATFORM_hid_set_nonblocking (PLATFORM_hid_device *dev, int nonblock)
const struct hid_api_version * PLATFORM_hid_version (void)
const char * PLATFORM_hid_version_str (void)
int PLATFORM_hid_write (PLATFORM_hid_device *dev, const unsigned char *data, size_t length)
static void process_pending_events (void)
static int pthread_barrier_destroy (pthread_barrier_t *barrier)
static int pthread_barrier_init (pthread_barrier_t *barrier, const pthread_barrierattr_t *attr, unsigned int count)
static int pthread_barrier_wait (pthread_barrier_t *barrier)
static void * read_thread (void *param)
static int read_usb_interface_from_hid_service_parent (io_service_t hid_service)
static void register_device_error (PLATFORM_hid_device *dev, const char *msg)
static void register_device_error_format (PLATFORM_hid_device *dev, const char *format,...)
static void register_error_str (wchar_t **error_str, const char *msg)
static void register_error_str_vformat (wchar_t **error_str, const char *format, va_list args)
static void register_global_error (const char *msg)
static void register_global_error_format (const char *format,...)
static int return_data (PLATFORM_hid_device *dev, unsigned char *data, size_t length)
static int set_report (PLATFORM_hid_device *dev, IOHIDReportType type, const unsigned char *data, size_t length)
static bool try_get_int_property (IOHIDDeviceRef device, CFStringRef key, int32_t *out_val)
static bool try_get_ioregistry_int_property (io_service_t service, CFStringRef property, int32_t *out_val)
static wchar_t * utf8_to_wchar_t (const char *utf8)
Variables
static struct hid_api_version api_version
static IOOptionBits device_open_options = 0
static IOHIDManagerRef hid_mgr = 0x0
static int is_macos_10_10_or_greater = 0
static wchar_t * last_global_error_str = NULL
Typedef Documentation
pthread_barrier_t
typedef struct pthread_barrier pthread_barrier_t
pthread_barrierattr_t
typedef int pthread_barrierattr_t
Function Documentation
cond_timedwait()
int cond_timedwait (PLATFORM_hid_device * dev, pthread_cond_t * cond, pthread_mutex_t * mutex, const struct timespec * abstime) static
{
    while (!dev->input_reports) {
        int res = pthread_cond_timedwait(cond, mutex, abstime);
        if (res != 0)
            return res;
        /* A res of 0 means we may have been signaled or it may
           be a spurious wakeup. Check to see that there's actually
           data in the queue before returning, and if not, go back
           to sleep. See the pthread_cond_timedwait() man page for
           details. */
        if (dev->shutdown_thread || dev->disconnected) {
            return -1;
        }
    }
    return 0;
}
References hid_device.
Referenced by PLATFORM_hid_read_timeout().
cond_wait()
int cond_wait (PLATFORM_hid_device * dev, pthread_cond_t * cond, pthread_mutex_t * mutex) static
{
    while (!dev->input_reports) {
        int res = pthread_cond_wait(cond, mutex);
        if (res != 0)
            return res;
        /* A res of 0 means we may have been signaled or it may
           be a spurious wakeup. Check to see that there's actually
           data in the queue before returning, and if not, go back
           to sleep. See the pthread_cond_timedwait() man page for
           details. */
        if (dev->shutdown_thread || dev->disconnected) {
            return -1;
        }
    }
    return 0;
}
References hid_device.
Referenced by PLATFORM_hid_read_timeout().
create_device_info()
struct hid_device_info * create_device_info (IOHIDDeviceRef device) static
{
    const int32_t primary_usage_page = get_int_property(device, CFSTR(kIOHIDPrimaryUsagePageKey));
    const int32_t primary_usage = get_int_property(device, CFSTR(kIOHIDPrimaryUsageKey));
    /* Primary should always be first, to match previous behavior. */
    struct hid_device_info *root = create_device_info_with_usage(device, primary_usage_page, primary_usage);
    struct hid_device_info *cur = root;
    CFArrayRef usage_pairs = get_usage_pairs(device);
    if (usage_pairs != NULL) {
        struct hid_device_info *next = NULL;
        for (CFIndex i = 0; i < CFArrayGetCount(usage_pairs); i++) {
            CFTypeRef dict = CFArrayGetValueAtIndex(usage_pairs, i);
            if (CFGetTypeID(dict) != CFDictionaryGetTypeID()) {
                continue;
            }
            CFTypeRef usage_page_ref, usage_ref;
            int32_t usage_page, usage;
            if (!CFDictionaryGetValueIfPresent((CFDictionaryRef)dict, CFSTR(kIOHIDDeviceUsagePageKey), &usage_page_ref) ||
                !CFDictionaryGetValueIfPresent((CFDictionaryRef)dict, CFSTR(kIOHIDDeviceUsageKey), &usage_ref) ||
                    CFGetTypeID(usage_page_ref) != CFNumberGetTypeID() ||
                    CFGetTypeID(usage_ref) != CFNumberGetTypeID() ||
                    !CFNumberGetValue((CFNumberRef)usage_page_ref, kCFNumberSInt32Type, &usage_page) ||
                    !CFNumberGetValue((CFNumberRef)usage_ref, kCFNumberSInt32Type, &usage)) {
                    continue;
            }
            if (usage_page == primary_usage_page && usage == primary_usage)
                continue; /* Already added. */
            next = create_device_info_with_usage(device, usage_page, usage);
            if (cur) {
                if (next != NULL) {
                    cur->next = next;
                    cur = next;
                }
            } else {
                root = cur = next;
            }
        }
    }
    return root;
}
References create_device_info_with_usage(), get_int_property(), get_usage_pairs(), hid_device_info::next, NULL, hid_device_info::usage, and hid_device_info::usage_page.
Referenced by hid_enumerate_callback(), PLATFORM_hid_enumerate(), and PLATFORM_hid_get_device_info().
create_device_info_with_usage()
struct hid_device_info * create_device_info_with_usage (IOHIDDeviceRef dev, int32_t usage_page, int32_t usage) static
{
    unsigned short dev_vid;
    unsigned short dev_pid;
    int BUF_LEN = 256;
    wchar_t buf[BUF_LEN];
    CFTypeRef transport_prop;
    struct hid_device_info *cur_dev;
    io_service_t hid_service;
    kern_return_t res;
    uint64_t entry_id = 0;
    if (dev == NULL) {
        return NULL;
    }
    cur_dev = (struct hid_device_info *)calloc(1, sizeof(struct hid_device_info));
    if (cur_dev == NULL) {
        return NULL;
    }
    dev_vid = get_vendor_id(dev);
    dev_pid = get_product_id(dev);
#ifdef HIDAPI_IGNORE_DEVICE
    /* See if there are any devices we should skip in enumeration */
    if (HIDAPI_IGNORE_DEVICE(get_bus_type(dev), dev_vid, dev_pid, usage_page, usage)) {
        free(cur_dev);
        return NULL;
    }
#endif
    cur_dev->usage_page = usage_page;
    cur_dev->usage = usage;
    /* Fill out the record */
    cur_dev->next = NULL;
    /* Fill in the path (as a unique ID of the service entry) */
    cur_dev->path = NULL;
    hid_service = IOHIDDeviceGetService(dev);
    if (hid_service != MACH_PORT_NULL) {
        res = IORegistryEntryGetRegistryEntryID(hid_service, &entry_id);
    }
    else {
        res = KERN_INVALID_ARGUMENT;
    }
    if (res == KERN_SUCCESS) {
        /* max value of entry_id(uint64_t) is 18446744073709551615 which is 20 characters long,
           so for (max) "path" string 'DevSrvsID:18446744073709551615' we would need
           9+1+20+1=31 bytes buffer, but allocate 32 for simple alignment */
        const size_t path_len = 32;
        cur_dev->path = calloc(1, path_len);
        if (cur_dev->path != NULL) {
            snprintf(cur_dev->path, path_len, "DevSrvsID:%llu", entry_id);
        }
    }
    if (cur_dev->path == NULL) {
        /* for whatever reason, trying to keep it a non-NULL string */
        cur_dev->path = strdup("");
    }
    /* Serial Number */
    get_serial_number(dev, buf, BUF_LEN);
    cur_dev->serial_number = dup_wcs(buf);
    /* Manufacturer and Product strings */
    get_manufacturer_string(dev, buf, BUF_LEN);
    cur_dev->manufacturer_string = dup_wcs(buf);
    get_product_string(dev, buf, BUF_LEN);
    cur_dev->product_string = dup_wcs(buf);
    /* VID/PID */
    cur_dev->vendor_id = dev_vid;
    cur_dev->product_id = dev_pid;
    /* Release Number */
    cur_dev->release_number = get_int_property(dev, CFSTR(kIOHIDVersionNumberKey));
    /* Interface Number.
     * We can only retrieve the interface number for USB HID devices.
     * See below */
    cur_dev->interface_number = -1;
    /* Bus Type */
    transport_prop = IOHIDDeviceGetProperty(dev, CFSTR(kIOHIDTransportKey));
    if (transport_prop != NULL && CFGetTypeID(transport_prop) == CFStringGetTypeID()) {
        if (CFStringCompare((CFStringRef)transport_prop, CFSTR(kIOHIDTransportUSBValue), 0) == kCFCompareEqualTo) {
            int32_t interface_number = -1;
            cur_dev->bus_type = HID_API_BUS_USB;
            /* A IOHIDDeviceRef used to have this simple property,
             * until macOS 13.3 - we will try to use it. */
            if (try_get_int_property(dev, CFSTR(kUSBInterfaceNumber), &interface_number)) {
                cur_dev->interface_number = interface_number;
            } else {
                /* Otherwise fallback to io_service_t property.
                 * (of one of the parent services). */
                cur_dev->interface_number = read_usb_interface_from_hid_service_parent(hid_service);
                /* If the above doesn't work -
                 * no (known) fallback exists at this point. */
            }
        /* Match "Bluetooth", "BluetoothLowEnergy" and "Bluetooth Low Energy" strings */
        } else if (CFStringHasPrefix((CFStringRef)transport_prop, CFSTR(kIOHIDTransportBluetoothValue))) {
            cur_dev->bus_type = HID_API_BUS_BLUETOOTH;
        } else if (CFStringCompare((CFStringRef)transport_prop, CFSTR(kIOHIDTransportI2CValue), 0) == kCFCompareEqualTo) {
            cur_dev->bus_type = HID_API_BUS_I2C;
        } else  if (CFStringCompare((CFStringRef)transport_prop, CFSTR(kIOHIDTransportSPIValue), 0) == kCFCompareEqualTo) {
            cur_dev->bus_type = HID_API_BUS_SPI;
        }
    }
    return cur_dev;
}
References hid_device_info::bus_type, calloc, dup_wcs(), free, get_int_property(), get_manufacturer_string(), get_product_id(), get_product_string(), get_serial_number(), get_vendor_id(), HID_API_BUS_BLUETOOTH, HID_API_BUS_I2C, HID_API_BUS_SPI, HID_API_BUS_USB, HIDAPI_IGNORE_DEVICE, hid_device_info::interface_number, hid_device_info::manufacturer_string, hid_device_info::next, NULL, hid_device_info::path, hid_device_info::product_id, hid_device_info::product_string, read_usb_interface_from_hid_service_parent(), hid_device_info::release_number, hid_device_info::serial_number, snprintf, strdup, try_get_int_property(), hid_device_info::usage, hid_device_info::usage_page, and hid_device_info::vendor_id.
Referenced by create_device_info().
dup_wcs()
wchar_t * dup_wcs (const wchar_t * s) static
{
    size_t len = wcslen(s);
    wchar_t *ret = (wchar_t*) malloc((len+1)*sizeof(wchar_t));
    wcscpy(ret, s);
    return ret;
}
References malloc, and wcslen.
Referenced by create_device_info_with_usage().
free_hid_device()
void free_hid_device (PLATFORM_hid_device * dev) static
{
    if (!dev)
        return;
    /* Delete any input reports still left over. */
    struct input_report *rpt = dev->input_reports;
    while (rpt) {
        struct input_report *next = rpt->next;
        free(rpt->data);
        free(rpt);
        rpt = next;
    }
    /* Free the string and the report buffer. The check for NULL
       is necessary here as CFRelease() doesn't handle NULL like
       free() and others do. */
    if (dev->run_loop_mode)
        CFRelease(dev->run_loop_mode);
    if (dev->source)
        CFRelease(dev->source);
    free(dev->input_report_buf);
    hid_free_enumeration(dev->device_info);
    /* Clean up the thread objects */
    pthread_barrier_destroy(&dev->shutdown_barrier);
    pthread_barrier_destroy(&dev->barrier);
    pthread_cond_destroy(&dev->condition);
    pthread_mutex_destroy(&dev->mutex);
    /* Free the structure itself. */
    free(dev);
}
References input_report::data, free, hid_device, hid_free_enumeration, input_report, input_report::next, and pthread_barrier_destroy().
get_array_property()
CFArrayRef get_array_property (IOHIDDeviceRef device, CFStringRef key) static
{
    CFTypeRef ref = IOHIDDeviceGetProperty(device, key);
    if (ref != NULL && CFGetTypeID(ref) == CFArrayGetTypeID()) {
        return (CFArrayRef)ref;
    } else {
        return NULL;
    }
}
References NULL.
Referenced by get_usage_pairs().
get_int_property()
int32_t get_int_property (IOHIDDeviceRef device, CFStringRef key) static
{
    CFTypeRef ref;
    int32_t value = 0;
    ref = IOHIDDeviceGetProperty(device, key);
    if (ref) {
        if (CFGetTypeID(ref) == CFNumberGetTypeID()) {
            CFNumberGetValue((CFNumberRef) ref, kCFNumberSInt32Type, &value);
            return value;
        }
    }
    return 0;
}
Referenced by create_device_info(), create_device_info_with_usage(), get_max_report_length(), get_product_id(), get_vendor_id(), and hid_darwin_get_location_id().
get_manufacturer_string()
int get_manufacturer_string (IOHIDDeviceRef device, wchar_t * buf, size_t len) static
{
    return get_string_property(device, CFSTR(kIOHIDManufacturerKey), buf, len);
}
References get_string_property().
Referenced by create_device_info_with_usage().
get_max_report_length()
int32_t get_max_report_length (IOHIDDeviceRef device) static
{
    return get_int_property(device, CFSTR(kIOHIDMaxInputReportSizeKey));
}
References get_int_property().
Referenced by PLATFORM_hid_open_path().
get_product_id()
unsigned short get_product_id (IOHIDDeviceRef device) static
{
    return get_int_property(device, CFSTR(kIOHIDProductIDKey));
}
References get_int_property().
Referenced by create_device_info_with_usage().
get_product_string()
int get_product_string (IOHIDDeviceRef device, wchar_t * buf, size_t len) static
{
    return get_string_property(device, CFSTR(kIOHIDProductKey), buf, len);
}
References get_string_property().
Referenced by create_device_info_with_usage().
get_report()
int get_report (PLATFORM_hid_device * dev, IOHIDReportType type, unsigned char * data, size_t length) static
{
    unsigned char *report = data;
    CFIndex report_length = length;
    IOReturn res = kIOReturnSuccess;
    const unsigned char report_id = data[0];
    register_device_error(dev, NULL);
    if (report_id == 0x0) {
        /* Not using numbered Reports.
           Don't send the report number. */
        report = data+1;
        report_length = length-1;
    }
    /* Avoid crash if the device has been unplugged. */
    if (dev->disconnected) {
        register_device_error(dev, "Device is disconnected");
        return -1;
    }
    res = IOHIDDeviceGetReport(dev->device_handle,
                               type,
                               report_id,
                               report, &report_length);
    if (res != kIOReturnSuccess) {
        register_device_error_format(dev, "IOHIDDeviceGetReport failed: (0x%08X) %s", res, mach_error_string(res));
        return -1;
    }
    if (report_id == 0x0) { /* 0 report number still present at the beginning */
        report_length++;
    }
    return (int) report_length;
}
References hid_device, NULL, register_device_error(), and register_device_error_format().
Referenced by PLATFORM_hid_get_feature_report(), and PLATFORM_hid_get_input_report().
get_serial_number()
int get_serial_number (IOHIDDeviceRef device, wchar_t * buf, size_t len) static
{
    return get_string_property(device, CFSTR(kIOHIDSerialNumberKey), buf, len);
}
References get_string_property().
Referenced by create_device_info_with_usage().
get_string_property()
int get_string_property (IOHIDDeviceRef device, CFStringRef prop, wchar_t * buf, size_t len) static
{
    CFStringRef str;
    if (!len)
        return 0;
    str = (CFStringRef) IOHIDDeviceGetProperty(device, prop);
    buf[0] = 0;
    if (str && CFGetTypeID(str) == CFStringGetTypeID()) {
        CFIndex str_len = CFStringGetLength(str);
        CFRange range;
        CFIndex used_buf_len;
        CFIndex chars_copied;
        len --;
        range.location = 0;
        range.length = ((size_t) str_len > len)? len: (size_t) str_len;
        chars_copied = CFStringGetBytes(str,
            range,
            kCFStringEncodingUTF32LE,
            (char) '?',
            FALSE,
            (UInt8*)buf,
            len * sizeof(wchar_t),
            &used_buf_len);
        if (chars_copied <= 0)
            buf[0] = 0;
        else
            buf[chars_copied] = 0;
        return 0;
    }
    else
        return -1;
}
References FALSE.
Referenced by get_manufacturer_string(), get_product_string(), and get_serial_number().
get_usage_pairs()
CFArrayRef get_usage_pairs (IOHIDDeviceRef device) static
{
    return get_array_property(device, CFSTR(kIOHIDDeviceUsagePairsKey));
}
References get_array_property().
Referenced by create_device_info().
get_vendor_id()
unsigned short get_vendor_id (IOHIDDeviceRef device) static
{
    return get_int_property(device, CFSTR(kIOHIDVendorIDKey));
}
References get_int_property().
Referenced by create_device_info_with_usage().
hid_device_removal_callback()
void hid_device_removal_callback (void * context, IOReturn result, void * sender) static
{
    (void) result;
    (void) sender;
    /* Stop the Run Loop for this device. */
    hid_device *d = (hid_device*) context;
    d->disconnected = 1;
    CFRunLoopStop(d->run_loop);
}
References context, d, hid_device, and void().
Referenced by PLATFORM_hid_open_path().
hid_open_service_registry_from_path()
io_registry_entry_t hid_open_service_registry_from_path (const char * path) static
{
    if (path == NULL)
        return MACH_PORT_NULL;
    /* Get the IORegistry entry for the given path */
    if (strncmp("DevSrvsID:", path, 10) == 0) {
        char *endptr;
        uint64_t entry_id = strtoull(path + 10, &endptr, 10);
        if (*endptr == '\0') {
            return IOServiceGetMatchingService((mach_port_t) 0, IORegistryEntryIDMatching(entry_id));
        }
    }
    else {
        /* Fallback to older format of the path */
        return IORegistryEntryFromPath((mach_port_t) 0, path);
    }
    return MACH_PORT_NULL;
}
References NULL.
Referenced by PLATFORM_hid_open_path().
hid_report_callback()
void hid_report_callback (void * context, IOReturn result, void * sender, IOHIDReportType report_type, uint32_t report_id, uint8_t * report, CFIndex report_length) static
{
    (void) result;
    (void) sender;
    (void) report_type;
    (void) report_id;
    struct input_report *rpt;
    hid_device *dev = (hid_device*) context;
    /* Make a new Input Report object */
    rpt = (struct input_report*) calloc(1, sizeof(struct input_report));
    rpt->data = (uint8_t*) calloc(1, report_length);
    memcpy(rpt->data, report, report_length);
    rpt->len = report_length;
    rpt->next = NULL;
    /* Lock this section */
    pthread_mutex_lock(&dev->mutex);
    /* Attach the new report object to the end of the list. */
    if (dev->input_reports == NULL) {
        /* The list is empty. Put it at the root. */
        dev->input_reports = rpt;
    }
    else {
        /* Find the end of the list and attach. */
        struct input_report *cur = dev->input_reports;
        int num_queued = 0;
        while (cur->next != NULL) {
            cur = cur->next;
            num_queued++;
        }
        cur->next = rpt;
        /* Pop one off if we've reached 30 in the queue. This
           way we don't grow forever if the user never reads
           anything from the device. */
        if (num_queued > 30) {
            return_data(dev, NULL, 0);
        }
    }
    /* Signal a waiting thread that there is data. */
    pthread_cond_signal(&dev->condition);
    /* Unlock */
    pthread_mutex_unlock(&dev->mutex);
}
References calloc, context, input_report::data, hid_device, input_report, input_report::len, memcpy, input_report::next, NULL, return_data, and void().
Referenced by PLATFORM_hid_open_path().
init_hid_manager()
int init_hid_manager (void) static
API export macro
References hid_mgr, NULL, and register_global_error().
Referenced by PLATFORM_hid_init().
new_hid_device()
PLATFORM_hid_device * new_hid_device (void) static
{
    hid_device *dev = (hid_device*) calloc(1, sizeof(hid_device));
    if (dev == NULL) {
        return NULL;
    }
    dev->device_handle = NULL;
    dev->open_options = device_open_options;
    dev->blocking = 1;
    dev->disconnected = 0;
    dev->run_loop_mode = NULL;
    dev->run_loop = NULL;
    dev->source = NULL;
    dev->input_report_buf = NULL;
    dev->input_reports = NULL;
    dev->device_info = NULL;
    dev->shutdown_thread = 0;
    dev->last_error_str = NULL;
    /* Thread objects */
    pthread_mutex_init(&dev->mutex, NULL);
    pthread_cond_init(&dev->condition, NULL);
    pthread_barrier_init(&dev->barrier, NULL, 2);
    pthread_barrier_init(&dev->shutdown_barrier, NULL, 2);
    return dev;
}
References calloc, device_open_options, hid_device, NULL, and pthread_barrier_init().
perform_signal_callback()
void perform_signal_callback (void * context) static
{
    hid_device *dev = (hid_device*) context;
    CFRunLoopStop(dev->run_loop); /*TODO: CFRunLoopGetCurrent()*/
}
References context, and hid_device.
Referenced by read_thread().
PLATFORM_hid_close()
void PLATFORM_hid_close (PLATFORM_hid_device * dev)
< API export macro
{
    if (!dev)
        return;
    /* Disconnect the report callback before close.
       See comment below.
    */
    if (is_macos_10_10_or_greater || !dev->disconnected) {
        IOHIDDeviceRegisterInputReportCallback(
            dev->device_handle, dev->input_report_buf, dev->max_input_report_len,
            NULL, dev);
        IOHIDDeviceRegisterRemovalCallback(dev->device_handle, NULL, dev);
        IOHIDDeviceUnscheduleFromRunLoop(dev->device_handle, dev->run_loop, dev->run_loop_mode);
        IOHIDDeviceScheduleWithRunLoop(dev->device_handle, CFRunLoopGetMain(), kCFRunLoopDefaultMode);
    }
    /* Cause read_thread() to stop. */
    dev->shutdown_thread = 1;
    /* Wake up the run thread's event loop so that the thread can exit. */
    CFRunLoopSourceSignal(dev->source);
    CFRunLoopWakeUp(dev->run_loop);
    /* Notify the read thread that it can shut down now. */
    pthread_barrier_wait(&dev->shutdown_barrier);
    /* Wait for read_thread() to end. */
    pthread_join(dev->thread, NULL);
    /* Close the OS handle to the device, but only if it's not
       been unplugged. If it's been unplugged, then calling
       IOHIDDeviceClose() will crash.
       UPD: The crash part was true in/until some version of macOS.
       Starting with macOS 10.15, there is an opposite effect in some environments:
       crash happenes if IOHIDDeviceClose() is not called.
       Not leaking a resource in all tested environments.
    */
    if (is_macos_10_10_or_greater || !dev->disconnected) {
        IOHIDDeviceClose(dev->device_handle, dev->open_options);
    }
    /* Clear out the queue of received reports. */
    pthread_mutex_lock(&dev->mutex);
    while (dev->input_reports) {
        return_data(dev, NULL, 0);
    }
    pthread_mutex_unlock(&dev->mutex);
    CFRelease(dev->device_handle);
    free_hid_device(dev);
}
References free_hid_device, HID_API_EXPORT, hid_device, is_macos_10_10_or_greater, NULL, pthread_barrier_wait(), and return_data.
PLATFORM_hid_enumerate()
struct hid_device_info * PLATFORM_hid_enumerate (unsigned short vendor_id, unsigned short product_id)
< API export macro
{
    struct hid_device_info *root = NULL; /* return object */
    struct hid_device_info *cur_dev = NULL;
    CFIndex num_devices;
    int i;
    /* Set up the HID Manager if it hasn't been done */
    if (hid_init() < 0) {
        return NULL;
    }
    /* register_global_error: global error is set/reset by hid_init */
    /* give the IOHIDManager a chance to update itself */
    process_pending_events();
    /* Get a list of the Devices */
    CFMutableDictionaryRef matching = NULL;
    if (vendor_id != 0 || product_id != 0) {
        matching = CFDictionaryCreateMutable(kCFAllocatorDefault, kIOHIDOptionsTypeNone, &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
        if (matching && vendor_id != 0) {
            CFNumberRef v = CFNumberCreate(kCFAllocatorDefault, kCFNumberShortType, &vendor_id);
            CFDictionarySetValue(matching, CFSTR(kIOHIDVendorIDKey), v);
            CFRelease(v);
        }
        if (matching && product_id != 0) {
            CFNumberRef p = CFNumberCreate(kCFAllocatorDefault, kCFNumberShortType, &product_id);
            CFDictionarySetValue(matching, CFSTR(kIOHIDProductIDKey), p);
            CFRelease(p);
        }
    }
    IOHIDManagerSetDeviceMatching(hid_mgr, matching);
    if (matching != NULL) {
        CFRelease(matching);
    }
    CFSetRef device_set = IOHIDManagerCopyDevices(hid_mgr);
    IOHIDDeviceRef *device_array = NULL;
    if (device_set != NULL) {
        /* Convert the list into a C array so we can iterate easily. */
        num_devices = CFSetGetCount(device_set);
        device_array = (IOHIDDeviceRef*) calloc(num_devices, sizeof(IOHIDDeviceRef));
        CFSetGetValues(device_set, (const void **) device_array);
    } else {
        num_devices = 0;
    }
    /* Iterate over each device, making an entry for it. */
    for (i = 0; i < num_devices; i++) {
        IOHIDDeviceRef dev = device_array[i];
        if (!dev) {
            continue;
        }
        struct hid_device_info *tmp = create_device_info(dev);
        if (tmp == NULL) {
            continue;
        }
        if (cur_dev) {
            cur_dev->next = tmp;
        }
        else {
            root = tmp;
        }
        cur_dev = tmp;
        /* move the pointer to the tail of returned list */
        while (cur_dev->next != NULL) {
            cur_dev = cur_dev->next;
        }
    }
    free(device_array);
    if (device_set != NULL)
        CFRelease(device_set);
    if (root == NULL) {
        if (vendor_id == 0 && product_id == 0) {
            register_global_error("No HID devices found in the system.");
        } else {
            register_global_error("No HID devices with requested VID/PID found in the system.");
        }
    }
    return root;
}
References calloc, create_device_info(), free, HID_API_EXPORT, hid_init, hid_mgr, hid_device_info::next, NULL, process_pending_events(), hid_device_info::product_id, register_global_error(), and hid_device_info::vendor_id.
PLATFORM_hid_error()
const wchar_t * PLATFORM_hid_error (PLATFORM_hid_device * dev)
< API call macro
{
    if (dev) {
        if (dev->last_error_str == NULL)
            return L"Success";
        return dev->last_error_str;
    }
    if (last_global_error_str == NULL)
        return L"Success";
    return last_global_error_str;
}
References HID_API_CALL, HID_API_EXPORT, hid_device, last_global_error_str, and NULL.
PLATFORM_hid_exit()
int PLATFORM_hid_exit (void)
< API export macro
{
    if (hid_mgr) {
        /* Close the HID manager. */
        IOHIDManagerClose(hid_mgr, kIOHIDOptionsTypeNone);
        CFRelease(hid_mgr);
        hid_mgr = NULL;
    }
    /* Free global error message */
    register_global_error(NULL);
    return 0;
}
References HID_API_EXPORT, hid_mgr, NULL, and register_global_error().
PLATFORM_hid_free_enumeration()
void PLATFORM_hid_free_enumeration (struct hid_device_info * devs)
< API export macro
{
    /* This function is identical to the Linux version. Platform independent. */
    struct hid_device_info *d = devs;
    while (d) {
        struct hid_device_info *next = d->next;
        free(d->path);
        free(d->serial_number);
        free(d->manufacturer_string);
        free(d->product_string);
        free(d);
        d = next;
    }
}
References d, free, HID_API_EXPORT, and hid_device_info::next.
PLATFORM_hid_get_device_info()
struct hid_device_info * PLATFORM_hid_get_device_info (PLATFORM_hid_device * dev)
< API call macro
{
    if (!dev->device_info) {
        dev->device_info = create_device_info(dev->device_handle);
        if (!dev->device_info) {
            register_device_error(dev, "Failed to create hid_device_info");
        }
    }
    return dev->device_info;
}
References create_device_info(), HID_API_CALL, HID_API_EXPORT, hid_device, and register_device_error().
PLATFORM_hid_get_feature_report()
int PLATFORM_hid_get_feature_report (PLATFORM_hid_device * dev, unsigned char * data, size_t length)
< API export macro
{
    return get_report(dev, kIOHIDReportTypeFeature, data, length);
}
References get_report(), HID_API_EXPORT, and hid_device.
PLATFORM_hid_get_indexed_string()
int PLATFORM_hid_get_indexed_string (PLATFORM_hid_device * dev, int string_index, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro
{
    (void) dev;
    (void) string_index;
    (void) string;
    (void) maxlen;
    register_device_error(dev, "hid_get_indexed_string: not available on this platform");
    return -1;
}
References HID_API_EXPORT_CALL, hid_device, register_device_error(), and void().
PLATFORM_hid_get_input_report()
int PLATFORM_hid_get_input_report (PLATFORM_hid_device * dev, unsigned char * data, size_t length)
< API export macro < API call macro
{
    return get_report(dev, kIOHIDReportTypeInput, data, length);
}
References get_report(), HID_API_CALL, HID_API_EXPORT, and hid_device.
PLATFORM_hid_get_manufacturer_string()
int PLATFORM_hid_get_manufacturer_string (PLATFORM_hid_device * dev, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro
{
    if (!string || !maxlen)
    {
        register_device_error(dev, "Zero buffer/length");
        return -1;
    }
    struct hid_device_info *info = hid_get_device_info(dev);
    if (!info)
    {
        // hid_get_device_info will have set an error already
        return -1;
    }
    wcsncpy(string, info->manufacturer_string, maxlen);
    string[maxlen - 1] = L'\0';
    return 0;
}
References HID_API_EXPORT_CALL, hid_device, hid_get_device_info, hid_device_info::manufacturer_string, register_device_error(), and wcsncpy.
PLATFORM_hid_get_product_string()
int PLATFORM_hid_get_product_string (PLATFORM_hid_device * dev, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro
{
    if (!string || !maxlen) {
        register_device_error(dev, "Zero buffer/length");
        return -1;
    }
    struct hid_device_info *info = hid_get_device_info(dev);
    if (!info) {
        // hid_get_device_info will have set an error already
        return -1;
    }
    wcsncpy(string, info->product_string, maxlen);
    string[maxlen - 1] = L'\0';
    return 0;
}
References HID_API_EXPORT_CALL, hid_device, hid_get_device_info, hid_device_info::product_string, register_device_error(), and wcsncpy.
PLATFORM_hid_get_report_descriptor()
int PLATFORM_hid_get_report_descriptor (PLATFORM_hid_device * dev, unsigned char * buf, size_t buf_size)
< API export macro < API call macro < API export and call macro API export macro
References HID_API_EXPORT_CALL, hid_device, memcpy, NULL, and register_device_error().
PLATFORM_hid_get_serial_number_string()
int PLATFORM_hid_get_serial_number_string (PLATFORM_hid_device * dev, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro API export macro
References HID_API_EXPORT_CALL, hid_device, hid_get_device_info, register_device_error(), hid_device_info::serial_number, and wcsncpy.
PLATFORM_hid_init()
int PLATFORM_hid_init (void)
< API export macro
{
    register_global_error(NULL);
    if (!hid_mgr) {
        is_macos_10_10_or_greater = (kCFCoreFoundationVersionNumber >= 1151.16); /* kCFCoreFoundationVersionNumber10_10 */
        hid_darwin_set_open_exclusive(1); /* Backward compatibility */
        return init_hid_manager();
    }
    /* Already initialized. */
    return 0;
}
References HID_API_EXPORT, hid_darwin_set_open_exclusive(), hid_mgr, init_hid_manager(), is_macos_10_10_or_greater, NULL, and register_global_error().
PLATFORM_hid_open()
PLATFORM_hid_device * PLATFORM_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)
< API export macro
{
    /* This function is identical to the Linux version. Platform independent. */
    struct hid_device_info *devs, *cur_dev;
    const char *path_to_open = NULL;
    hid_device * handle = NULL;
    /* register_global_error: global error is reset by hid_enumerate/hid_init */
    devs = hid_enumerate(vendor_id, product_id);
    if (devs == NULL) {
        /* register_global_error: global error is already set by hid_enumerate */
        return NULL;
    }
    cur_dev = devs;
    while (cur_dev) {
        if (cur_dev->vendor_id == vendor_id &&
            cur_dev->product_id == product_id) {
            if (serial_number) {
                if (wcscmp(serial_number, cur_dev->serial_number) == 0) {
                    path_to_open = cur_dev->path;
                    break;
                }
            }
            else {
                path_to_open = cur_dev->path;
                break;
            }
        }
        cur_dev = cur_dev->next;
    }
    if (path_to_open) {
        handle = hid_open_path(path_to_open);
    } else {
        register_global_error("Device with requested VID/PID/(SerialNumber) not found");
    }
    hid_free_enumeration(devs);
    return handle;
}
References HID_API_EXPORT, hid_device, hid_enumerate, hid_free_enumeration, hid_open_path, hid_device_info::next, NULL, hid_device_info::path, hid_device_info::product_id, register_global_error(), hid_device_info::serial_number, hid_device_info::vendor_id, and wcscmp.
PLATFORM_hid_open_path()
PLATFORM_hid_device * PLATFORM_hid_open_path (const char * path)
< API export macro
{
    hid_device *dev = NULL;
    io_registry_entry_t entry = MACH_PORT_NULL;
    IOReturn ret = kIOReturnInvalid;
    char str[32];
    /* Set up the HID Manager if it hasn't been done */
    if (hid_init() < 0) {
        return NULL;
    }
    /* register_global_error: global error is set/reset by hid_init */
    dev = new_hid_device();
    if (!dev) {
        register_global_error("Couldn't allocate memory");
        return NULL;
    }
    /* Get the IORegistry entry for the given path */
    entry = hid_open_service_registry_from_path(path);
    if (entry == MACH_PORT_NULL) {
        /* Path wasn't valid (maybe device was removed?) */
        register_global_error("hid_open_path: device mach entry not found with the given path");
        goto return_error;
    }
    /* Create an IOHIDDevice for the entry */
    dev->device_handle = IOHIDDeviceCreate(kCFAllocatorDefault, entry);
    if (dev->device_handle == NULL) {
        /* Error creating the HID device */
        register_global_error("hid_open_path: failed to create IOHIDDevice from the mach entry");
        goto return_error;
    }
    /* Open the IOHIDDevice */
    ret = IOHIDDeviceOpen(dev->device_handle, dev->open_options);
    if (ret != kIOReturnSuccess) {
        register_global_error_format("hid_open_path: failed to open IOHIDDevice from mach entry: (0x%08X) %s", ret, mach_error_string(ret));
        goto return_error;
    }
    /* Create the buffers for receiving data */
    dev->max_input_report_len = (CFIndex) get_max_report_length(dev->device_handle);
    dev->input_report_buf = (uint8_t*) calloc(dev->max_input_report_len, sizeof(uint8_t));
    /* Create the Run Loop Mode for this device.
       printing the reference seems to work. */
    snprintf(str, sizeof(str), "HIDAPI_%p", (void*) dev->device_handle);
    dev->run_loop_mode =
        CFStringCreateWithCString(NULL, str, kCFStringEncodingASCII);
    /* Attach the device to a Run Loop */
    IOHIDDeviceRegisterInputReportCallback(
        dev->device_handle, dev->input_report_buf, dev->max_input_report_len,
        &hid_report_callback, dev);
    IOHIDDeviceRegisterRemovalCallback(dev->device_handle, hid_device_removal_callback, dev);
    /* Start the read thread */
    pthread_create(&dev->thread, NULL, read_thread, dev);
    /* Wait here for the read thread to be initialized. */
    pthread_barrier_wait(&dev->barrier);
    IOObjectRelease(entry);
    return dev;
return_error:
    if (dev->device_handle != NULL)
        CFRelease(dev->device_handle);
    if (entry != MACH_PORT_NULL)
        IOObjectRelease(entry);
    free_hid_device(dev);
    return NULL;
}
References calloc, free_hid_device, get_max_report_length(), HID_API_EXPORT, hid_device, hid_device_removal_callback(), hid_init, hid_open_service_registry_from_path(), hid_report_callback(), new_hid_device(), NULL, pthread_barrier_wait(), read_thread, register_global_error(), register_global_error_format(), and snprintf.
PLATFORM_hid_read()
int PLATFORM_hid_read (PLATFORM_hid_device * dev, unsigned char * data, size_t length)
< API export macro
{
    return hid_read_timeout(dev, data, length, (dev->blocking)? -1: 0);
}
References HID_API_EXPORT, hid_device, and hid_read_timeout.
PLATFORM_hid_read_timeout()
int PLATFORM_hid_read_timeout (PLATFORM_hid_device * dev, unsigned char * data, size_t length, int milliseconds)
< API export macro
{
    int bytes_read = -1;
    /* Lock the access to the report list. */
    pthread_mutex_lock(&dev->mutex);
    /* There's an input report queued up. Return it. */
    if (dev->input_reports) {
        /* Return the first one */
        bytes_read = return_data(dev, data, length);
        goto ret;
    }
    /* Return if the device has been disconnected. */
    if (dev->disconnected) {
        bytes_read = -1;
        register_device_error(dev, "hid_read_timeout: device disconnected");
        goto ret;
    }
    if (dev->shutdown_thread) {
        /* This means the device has been closed (or there
           has been an error. An error code of -1 should
           be returned. */
        bytes_read = -1;
        register_device_error(dev, "hid_read_timeout: thread shutdown");
        goto ret;
    }
    /* There is no data. Go to sleep and wait for data. */
    if (milliseconds == -1) {
        /* Blocking */
        int res;
        res = cond_wait(dev, &dev->condition, &dev->mutex);
        if (res == 0)
            bytes_read = return_data(dev, data, length);
        else {
            /* There was an error, or a device disconnection. */
            register_device_error(dev, "hid_read_timeout: error waiting for more data");
            bytes_read = -1;
        }
    }
    else if (milliseconds > 0) {
        /* Non-blocking, but called with timeout. */
        int res;
        struct timespec ts;
        struct timeval tv;
        gettimeofday(&tv, NULL);
        TIMEVAL_TO_TIMESPEC(&tv, &ts);
        ts.tv_sec += milliseconds / 1000;
        ts.tv_nsec += (milliseconds % 1000) * 1000000;
        if (ts.tv_nsec >= 1000000000L) {
            ts.tv_sec++;
            ts.tv_nsec -= 1000000000L;
        }
        res = cond_timedwait(dev, &dev->condition, &dev->mutex, &ts);
        if (res == 0) {
            bytes_read = return_data(dev, data, length);
        } else if (res == ETIMEDOUT) {
            bytes_read = 0;
        } else {
            register_device_error(dev, "hid_read_timeout:  error waiting for more data");
            bytes_read = -1;
        }
    }
    else {
        /* Purely non-blocking */
        bytes_read = 0;
    }
ret:
    /* Unlock */
    pthread_mutex_unlock(&dev->mutex);
    return bytes_read;
}
References cond_timedwait(), cond_wait(), HID_API_EXPORT, hid_device, NULL, register_device_error(), and return_data.
PLATFORM_hid_send_feature_report()
int PLATFORM_hid_send_feature_report (PLATFORM_hid_device * dev, const unsigned char * data, size_t length)
< API export macro
{
    return set_report(dev, kIOHIDReportTypeFeature, data, length);
}
References HID_API_EXPORT, hid_device, and set_report().
PLATFORM_hid_set_nonblocking()
int PLATFORM_hid_set_nonblocking (PLATFORM_hid_device * dev, int nonblock)
< API export macro
{
    /* All Nonblocking operation is handled by the library. */
    dev->blocking = !nonblock;
    return 0;
}
References HID_API_EXPORT, and hid_device.
PLATFORM_hid_version()
const struct hid_api_version * PLATFORM_hid_version (void)
< API call macro API export macro
References api_version, HID_API_CALL, and HID_API_EXPORT.
PLATFORM_hid_version_str()
const char * PLATFORM_hid_version_str (void)
< API call macro
{
    return HID_API_VERSION_STR;
}
References HID_API_CALL, HID_API_EXPORT, and HID_API_VERSION_STR.
PLATFORM_hid_write()
int PLATFORM_hid_write (PLATFORM_hid_device * dev, const unsigned char * data, size_t length)
< API export macro
{
    return set_report(dev, kIOHIDReportTypeOutput, data, length);
}
References HID_API_EXPORT, hid_device, and set_report().
process_pending_events()
void process_pending_events (void) static
{
    SInt32 res;
    do {
        res = CFRunLoopRunInMode(kCFRunLoopDefaultMode, 0.001, FALSE);
    } while(res != kCFRunLoopRunFinished && res != kCFRunLoopRunTimedOut);
}
References FALSE.
Referenced by PLATFORM_hid_enumerate().
pthread_barrier_destroy()
int pthread_barrier_destroy (pthread_barrier_t * barrier) static
{
    pthread_cond_destroy(&barrier->cond);
    pthread_mutex_destroy(&barrier->mutex);
    return 0;
}
References pthread_barrier::cond, and pthread_barrier::mutex.
Referenced by free_hid_device(), and hidapi_thread_state_destroy().
pthread_barrier_init()
int pthread_barrier_init (pthread_barrier_t * barrier, const pthread_barrierattr_t * attr, unsigned int count) static
{
    (void) attr;
    if (count == 0) {
        errno = EINVAL;
        return -1;
    }
    if (pthread_mutex_init(&barrier->mutex, 0) < 0) {
        return -1;
    }
    if (pthread_cond_init(&barrier->cond, 0) < 0) {
        pthread_mutex_destroy(&barrier->mutex);
        return -1;
    }
    barrier->trip_count = count;
    barrier->count = 0;
    return 0;
}
References pthread_barrier::cond, count, pthread_barrier::count, pthread_barrier::mutex, pthread_barrier::trip_count, and void().
Referenced by hidapi_thread_state_init(), and new_hid_device().
pthread_barrier_wait()
int pthread_barrier_wait (pthread_barrier_t * barrier) static
{
    pthread_mutex_lock(&barrier->mutex);
    ++(barrier->count);
    if (barrier->count >= barrier->trip_count) {
        barrier->count = 0;
        pthread_mutex_unlock(&barrier->mutex);
        pthread_cond_broadcast(&barrier->cond);
        return 1;
    }
    else {
        do {
            pthread_cond_wait(&barrier->cond, &(barrier->mutex));
        }
        while (barrier->count != 0);
        pthread_mutex_unlock(&barrier->mutex);
        return 0;
    }
}
References pthread_barrier::cond, pthread_barrier::count, pthread_barrier::mutex, and pthread_barrier::trip_count.
Referenced by hidapi_thread_barrier_wait(), PLATFORM_hid_close(), PLATFORM_hid_open_path(), and read_thread().
read_thread()
void * read_thread (void * param) static
{
    hid_device *dev = (hid_device*) param;
    SInt32 code;
    /* Move the device's run loop to this thread. */
    IOHIDDeviceScheduleWithRunLoop(dev->device_handle, CFRunLoopGetCurrent(), dev->run_loop_mode);
    /* Create the RunLoopSource which is used to signal the
       event loop to stop when hid_close() is called. */
    CFRunLoopSourceContext ctx;
    memset(&ctx, 0, sizeof(ctx));
    ctx.version = 0;
    ctx.info = dev;
    ctx.perform = &perform_signal_callback;
    dev->source = CFRunLoopSourceCreate(kCFAllocatorDefault, 0/*order*/, &ctx);
    CFRunLoopAddSource(CFRunLoopGetCurrent(), dev->source, dev->run_loop_mode);
    /* Store off the Run Loop so it can be stopped from hid_close()
       and on device disconnection. */
    dev->run_loop = CFRunLoopGetCurrent();
    /* Notify the main thread that the read thread is up and running. */
    pthread_barrier_wait(&dev->barrier);
    /* Run the Event Loop. CFRunLoopRunInMode() will dispatch HID input
       reports into the hid_report_callback(). */
    while (!dev->shutdown_thread && !dev->disconnected) {
        code = CFRunLoopRunInMode(dev->run_loop_mode, 1000/*sec*/, FALSE);
        /* Return if the device has been disconnected */
        if (code == kCFRunLoopRunFinished || code == kCFRunLoopRunStopped) {
            dev->disconnected = 1;
            break;
        }
        /* Break if The Run Loop returns Finished or Stopped. */
        if (code != kCFRunLoopRunTimedOut &&
            code != kCFRunLoopRunHandledSource) {
            /* There was some kind of error. Setting
               shutdown seems to make sense, but
               there may be something else more appropriate */
            dev->shutdown_thread = 1;
            break;
        }
    }
    /* Now that the read thread is stopping, Wake any threads which are
       waiting on data (in hid_read_timeout()). Do this under a mutex to
       make sure that a thread which is about to go to sleep waiting on
       the condition actually will go to sleep before the condition is
       signaled. */
    pthread_mutex_lock(&dev->mutex);
    pthread_cond_broadcast(&dev->condition);
    pthread_mutex_unlock(&dev->mutex);
    /* Wait here until hid_close() is called and makes it past
       the call to CFRunLoopWakeUp(). This thread still needs to
       be valid when that function is called on the other thread. */
    pthread_barrier_wait(&dev->shutdown_barrier);
    return NULL;
}
References FALSE, hid_device, memset(), NULL, perform_signal_callback(), and pthread_barrier_wait().
read_usb_interface_from_hid_service_parent()
int read_usb_interface_from_hid_service_parent (io_service_t hid_service) static
{
    int32_t result = -1;
    bool success = false;
    io_registry_entry_t current = IO_OBJECT_NULL;
    kern_return_t res;
    int parent_number = 0;
    res = IORegistryEntryGetParentEntry(hid_service, kIOServicePlane, &current);
    while (KERN_SUCCESS == res
            /* Only search up to 3 parent entries.
             * With the default driver - the parent-of-interest supposed to be the first one,
             * but lets assume some custom drivers or so, with deeper tree. */
            && parent_number < 3) {
        io_registry_entry_t parent = IO_OBJECT_NULL;
        int32_t interface_number = -1;
        parent_number++;
        success = try_get_ioregistry_int_property(current, CFSTR(kUSBInterfaceNumber), &interface_number);
        if (success) {
            result = interface_number;
            break;
        }
        res = IORegistryEntryGetParentEntry(current, kIOServicePlane, &parent);
        if (parent) {
            IOObjectRelease(current);
            current = parent;
        }
    }
    if (current) {
        IOObjectRelease(current);
        current = IO_OBJECT_NULL;
    }
    return result;
}
References try_get_ioregistry_int_property().
Referenced by create_device_info_with_usage().
register_device_error()
void register_device_error (PLATFORM_hid_device * dev, const char * msg) static
{
    register_error_str(&dev->last_error_str, msg);
}
References hid_device, and register_error_str().
register_device_error_format()
void register_device_error_format (PLATFORM_hid_device * dev, const char * format, ...) static
{
    va_list args;
    va_start(args, format);
    register_error_str_vformat(&dev->last_error_str, format, args);
    va_end(args);
}
References hid_device, and register_error_str_vformat().
register_error_str()
void register_error_str (wchar_t ** error_str, const char * msg) static
{
    free(*error_str);
#ifdef HIDAPI_USING_SDL_RUNTIME
    /* Thread-safe error handling */
    if (msg) {
        SDL_SetError("%s", msg);
    } else {
        SDL_ClearError();
    }
#else
    *error_str = utf8_to_wchar_t(msg);
#endif
}
References free, SDL_ClearError(), SDL_SetError(), and utf8_to_wchar_t().
register_error_str_vformat()
void register_error_str_vformat (wchar_t ** error_str, const char * format, va_list args) static
{
    char msg[1024];
    vsnprintf(msg, sizeof(msg), format, args);
    register_error_str(error_str, msg);
}
References register_error_str().
register_global_error()
void register_global_error (const char * msg) static
{
    register_error_str(&last_global_error_str, msg);
}
References last_global_error_str, and register_error_str().
register_global_error_format()
void register_global_error_format (const char * format, ...) static
{
    va_list args;
    va_start(args, format);
    register_error_str_vformat(&last_global_error_str, format, args);
    va_end(args);
}
References last_global_error_str, and register_error_str_vformat().
return_data()
int return_data (PLATFORM_hid_device * dev, unsigned char * data, size_t length) static
{
    /* Copy the data out of the linked list item (rpt) into the
       return buffer (data), and delete the liked list item. */
    struct input_report *rpt = dev->input_reports;
    size_t len = (length < rpt->len)? length: rpt->len;
    if (data != NULL) {
        memcpy(data, rpt->data, len);
    }
    dev->input_reports = rpt->next;
    free(rpt->data);
    free(rpt);
    return (int) len;
}
References input_report::data, free, hid_device, input_report, input_report::len, memcpy, input_report::next, and NULL.
set_report()
int set_report (PLATFORM_hid_device * dev, IOHIDReportType type, const unsigned char * data, size_t length) static
{
    const unsigned char *data_to_send = data;
    CFIndex length_to_send = length;
    IOReturn res;
    unsigned char report_id;
    register_device_error(dev, NULL);
    if (!data || (length == 0)) {
        register_device_error(dev, strerror(EINVAL));
        return -1;
    }
    report_id = data[0];
    if (report_id == 0x0) {
        /* Not using numbered Reports.
           Don't send the report number. */
        data_to_send = data+1;
        length_to_send = length-1;
    }
    /* Avoid crash if the device has been unplugged. */
    if (dev->disconnected) {
        register_device_error(dev, "Device is disconnected");
        return -1;
    }
    res = IOHIDDeviceSetReport(dev->device_handle,
                               type,
                               report_id,
                               data_to_send, length_to_send);
    if (res != kIOReturnSuccess) {
        register_device_error_format(dev, "IOHIDDeviceSetReport failed: (0x%08X) %s", res, mach_error_string(res));
        return -1;
    }
    return (int) length;
}
References hid_device, NULL, register_device_error(), and register_device_error_format().
Referenced by PLATFORM_hid_send_feature_report(), and PLATFORM_hid_write().
try_get_int_property()
bool try_get_int_property (IOHIDDeviceRef device, CFStringRef key, int32_t * out_val) static
{
    bool result = false;
    CFTypeRef ref;
    ref = IOHIDDeviceGetProperty(device, key);
    if (ref) {
        if (CFGetTypeID(ref) == CFNumberGetTypeID()) {
            result = CFNumberGetValue((CFNumberRef) ref, kCFNumberSInt32Type, out_val);
        }
    }
    return result;
}
Referenced by create_device_info_with_usage().
try_get_ioregistry_int_property()
bool try_get_ioregistry_int_property (io_service_t service, CFStringRef property, int32_t * out_val) static
{
    bool result = false;
    CFTypeRef ref = IORegistryEntryCreateCFProperty(service, property, kCFAllocatorDefault, 0);
    if (ref) {
        if (CFGetTypeID(ref) == CFNumberGetTypeID()) {
            result = CFNumberGetValue(ref, kCFNumberSInt32Type, out_val);
        }
        CFRelease(ref);
    }
    return result;
}
Referenced by read_usb_interface_from_hid_service_parent().
utf8_to_wchar_t()
wchar_t * utf8_to_wchar_t (const char * utf8) static
{
    wchar_t *ret = NULL;
    if (utf8) {
        size_t wlen = mbstowcs(NULL, utf8, 0);
        if ((size_t) -1 == wlen) {
            return wcsdup(L"");
        }
        ret = (wchar_t*) calloc(wlen+1, sizeof(wchar_t));
        if (ret == NULL) {
            /* as much as we can do at this point */
            return NULL;
        }
        mbstowcs(ret, utf8, wlen+1);
        ret[wlen] = 0x0000;
    }
    return ret;
}
References calloc, NULL, and wcsdup.
Variable Documentation
api_version
struct hid_api_version api_version static
Initial value:
= {
    .major = 0 ,
    .minor = 14 ,
    .patch = 0
}
{
    .major = HID_API_VERSION_MAJOR,
    .minor = HID_API_VERSION_MINOR,
    .patch = HID_API_VERSION_PATCH
};
device_open_options
IOOptionBits device_open_options = 0 static
Referenced by hid_darwin_get_open_exclusive(), hid_darwin_set_open_exclusive(), and new_hid_device().
hid_mgr
IOHIDManagerRef hid_mgr = 0x0 static
Referenced by init_hid_manager(), PLATFORM_hid_enumerate(), PLATFORM_hid_exit(), and PLATFORM_hid_init().
is_macos_10_10_or_greater
int is_macos_10_10_or_greater = 0 static
Referenced by PLATFORM_hid_close(), and PLATFORM_hid_init().
last_global_error_str
wchar_t* last_global_error_str = NULL static