SDL3: SDL-main/src/SDL_hashtable.h File Reference
SDL_hashtable.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Typedefs
typedef Uint32(SDLCALL * SDL_HashCallback) (void *userdata, const void *key)
typedef void(SDLCALL * SDL_HashDestroyCallback) (void *userdata, const void *key, const void *value)
typedef bool(SDLCALL * SDL_HashKeyMatchCallback) (void *userdata, const void *a, const void *b)
typedef struct SDL_HashTable SDL_HashTable
typedef bool(SDLCALL * SDL_HashTableIterateCallback) (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
Functions
void SDL_ClearHashTable (SDL_HashTable *table)
SDL_HashTable * SDL_CreateHashTable (int estimated_capacity, bool threadsafe, SDL_HashCallback hash, SDL_HashKeyMatchCallback keymatch, SDL_HashDestroyCallback destroy, void *userdata)
void SDL_DestroyHashKey (void *unused, const void *key, const void *value)
void SDL_DestroyHashKeyAndValue (void *unused, const void *key, const void *value)
void SDL_DestroyHashTable (SDL_HashTable *table)
void SDL_DestroyHashValue (void *unused, const void *key, const void *value)
bool SDL_FindInHashTable (const SDL_HashTable *table, const void *key, const void **value)
Uint32 SDL_HashID (void *unused, const void *key)
Uint32 SDL_HashPointer (void *unused, const void *key)
Uint32 SDL_HashString (void *unused, const void *key)
bool SDL_HashTableEmpty (SDL_HashTable *table)
bool SDL_InsertIntoHashTable (SDL_HashTable *table, const void *key, const void *value, bool replace)
bool SDL_IterateHashTable (const SDL_HashTable *table, SDL_HashTableIterateCallback callback, void *userdata)
bool SDL_KeyMatchID (void *unused, const void *a, const void *b)
bool SDL_KeyMatchPointer (void *unused, const void *a, const void *b)
bool SDL_KeyMatchString (void *unused, const void *a, const void *b)
bool SDL_RemoveFromHashTable (SDL_HashTable *table, const void *key)
Typedef Documentation
SDL_HashCallback
typedef Uint32(SDLCALL * SDL_HashCallback) (void *userdata, const void *key)
A function pointer representing a hash table hashing callback.
This is called by SDL_HashTable when it needs to look up a key in its dataset. It generates a hash value from that key, and then uses that value as a basis for an index into an internal array.
There are no rules on what hashing algorithm is used, so long as it can produce a reliable 32-bit value from key, and ideally distributes those values well across the 32-bit value space. The quality of a hashing algorithm is directly related to how well a hash table performs.
Hashing can be a complicated subject, and often times what works best for one dataset will be suboptimal for another. There is a good discussion of the field on Wikipedia.
Also: do you need to write a hashing function? SDL provides generic functions for strings (SDL_HashString), generic integer IDs (SDL_HashID), and generic pointers (SDL_HashPointer). Often you should use one of these before writing your own.
Parameters
userdata what was passed as userdata to SDL_CreateHashTable().
key the key to be hashed.
Returns
a 32-bit value that represents a hash of key.
Thread Safety
This function must be thread safe if the hash table is used from multiple threads at the same time.
Since
This datatype is available since SDL 3.4.0.
See also
SDL_CreateHashTable
SDL_HashString
SDL_HashID
SDL_HashPointer
SDL_HashDestroyCallback
typedef void(SDLCALL * SDL_HashDestroyCallback) (void *userdata, const void *key, const void *value)
A function pointer representing a hash table cleanup callback.
This is called by SDL_HashTable when removing items from the hash, or destroying the hash table. It is used to optionally deallocate the key/value pairs.
This is not required to do anything, if all the data in the table is static or POD data, but it can also do more than a simple free: for example, if the hash table is storing open files, it can close them here. It can also free only the key or only the value; it depends on what the hash table contains.
Parameters
userdata what was passed as userdata to SDL_CreateHashTable().
key the key to deallocate.
value the value to deallocate.
Thread Safety
This function must be thread safe if the hash table is used from multiple threads at the same time.
Since
This datatype is available since SDL 3.4.0.
See also
SDL_CreateHashTable
SDL_HashKeyMatchCallback
typedef bool(SDLCALL * SDL_HashKeyMatchCallback) (void *userdata, const void *a, const void *b)
A function pointer representing a hash table matching callback.
This is called by SDL_HashTable when it needs to look up a key in its dataset. After hashing the key, it looks for items stored in relation to that hash value. Since there can be more than one item found through the same hash value, this function verifies a specific value is actually correct before choosing it.
So this function needs to compare the keys at a and b and decide if they are actually the same.
For example, if the keys are C strings, this function might just be:
return (SDL_strcmp((const char *) a, const char *b) == 0);`
Also: do you need to write a matching function? SDL provides generic functions for strings (SDL_KeyMatchString), generic integer IDs (SDL_KeyMatchID), and generic pointers (SDL_KeyMatchPointer). Often you should use one of these before writing your own.
Parameters
userdata what was passed as userdata to SDL_CreateHashTable().
a the first key to be compared.
b the second key to be compared.
Returns
true if two keys are identical, false otherwise.
Thread Safety
This function must be thread safe if the hash table is used from multiple threads at the same time.
Since
This datatype is available since SDL 3.4.0.
See also
SDL_CreateHashTable
SDL_HashTable
typedef struct SDL_HashTable SDL_HashTable
CategoryHashTable
SDL offers a hash table implementation, as a convenience for C code that needs efficient organization and access of arbitrary data.
Hash tables are a popular data structure, designed to make it quick to store and look up arbitrary data. Data is stored with an associated "key." While one would look up an element of an array with an index, a hash table uses a unique key to find an element later.
A key can be anything, as long as its unique and in a format that the table understands. For example, it's popular to use strings as keys: the key might be a username, and it is used to lookup account information for that user, etc.
Hash tables are named because they "hash" their keys down into simple integers that can be used to efficiently organize and access the associated data.
As this is a C API, there is one generic interface that is intended to work with different data types. This can be a little awkward to set up, but is easy to use after that.
Hashtables are generated by a call to SDL_CreateHashTable(). This function requires several callbacks to be provided (for hashing keys, comparing entries, and cleaning up entries when removed). These are necessary to allow the hash to manage any arbitrary data type.
Once a hash table is created, the common tasks are inserting data into the table, (SDL_InsertIntoHashTable), looking up previously inserted data (SDL_FindInHashTable), and removing data (SDL_RemoveFromHashTable and SDL_ClearHashTable). Less common but still useful is the ability to iterate through all the items in the table (SDL_IterateHashTable).
The underlying hash table implementation is always subject to change, but at the time of writing, it uses open addressing and Robin Hood hashing. The technical details are explained here.
Hashtables keep an SDL_RWLock internally, so multiple threads can perform hash lookups in parallel, while changes to the table will safely serialize access between threads.
SDL provides a layer on top of this hash table implementation that might be more pleasant to use. SDL_PropertiesID maps a string to arbitrary data of various types in the same table, which could be both easier to use and more flexible. Refer to [CategoryProperties](CategoryProperties) for details. The opaque type that represents a hash table.
This is hidden behind an opaque pointer because not only does the table need to store arbitrary data types, but the hash table implementation may change in the future.
Since
This struct is available since SDL 3.4.0.
See also
SDL_CreateHashTable
SDL_HashTableIterateCallback
typedef bool(SDLCALL * SDL_HashTableIterateCallback) (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
A function pointer representing a hash table iterator callback.
This function is called once for each key/value pair to be considered when iterating a hash table.
Iteration continues as long as there are more items to examine and this callback continues to return true.
Do not attempt to modify the hash table during this callback, as it will cause incorrect behavior and possibly crashes.
Parameters
userdata what was passed as userdata to an iterator function.
table the hash table being iterated.
key the current key being iterated.
value the current value being iterated.
Returns
true to keep iterating, false to stop iteration.
Thread Safety
A read lock is held during iteration, so other threads can still access the hash table, but threads attempting to make changes will be blocked until iteration completes. If this is a concern, do as little in the callback as possible and finish iteration quickly.
Since
This datatype is available since SDL 3.4.0.
See also
SDL_IterateHashTable
Function Documentation
SDL_ClearHashTable()
void SDL_ClearHashTable (SDL_HashTable * table) extern
Remove all items in a hash table.
This will call the hash table's SDL_HashDestroyCallback for each item in the table, removing all inserted items.
When this function returns, the hash table will be empty.
Parameters
table the hash table to clear.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (table) {
        SDL_LockRWLockForWriting(table->lock);
        {
            destroy_all(table);
            SDL_memset(table->table, 0, sizeof(*table->table) * (table->hash_mask + 1));
            table->num_occupied_slots = 0;
        }
        SDL_UnlockRWLock(table->lock);
    }
}
References destroy_all(), SDL_HashTable::hash_mask, SDL_HashTable::lock, SDL_HashTable::num_occupied_slots, SDL_LockRWLockForWriting(), SDL_memset, SDL_UnlockRWLock(), and SDL_HashTable::table.
SDL_CreateHashTable()
SDL_HashTable * SDL_CreateHashTable (int estimated_capacity, bool threadsafe, SDL_HashCallback hash, SDL_HashKeyMatchCallback keymatch, SDL_HashDestroyCallback destroy, void * userdata) extern
Create a new hash table.
To deal with different datatypes and needs of the caller, hash tables require several callbacks that deal with some specifics: how to hash a key, how to compare a key for equality, and how to clean up keys and values. SDL provides a few generic functions that can be used for these callbacks:
SDL_HashString and SDL_KeyMatchString for C strings.
SDL_HashPointer and SDL_KeyMatchPointer for generic pointers.
SDL_HashID and SDL_KeyMatchID for generic (possibly small) integers.
Oftentimes, these are all you need for any hash table, but depending on your dataset, custom implementations might make more sense.
You can specify an estimate of the number of items expected to be stored in the table, which can help make the table run more efficiently. The table will preallocate resources to accommodate this number of items, which is most useful if you intend to fill the table with a lot of data right after creating it. Otherwise, it might make more sense to specify the minimum you expect the table to hold and let it grow as necessary from there. This number is only a hint, and the table will be able to handle any amount of data–as long as the system doesn't run out of resources–so a perfect answer is not required. A value of 0 signifies no guess at all, and the table will start small and reallocate as necessary; often this is the correct thing to do.
!!! FIXME: add note about threadsafe here. And update threadsafety tags. !!! FIXME: note that threadsafe tables can't be recursively locked, so !!! FIXME: you can't use destroy callbacks that might end up relocking.
Note that SDL provides a higher-level option built on its hash tables: SDL_PropertiesID lets you map strings to various datatypes, and this might be easier to use. It only allows strings for keys, however. Those are created with SDL_CreateProperties().
The returned hash table should be destroyed with SDL_DestroyHashTable() when no longer needed.
Parameters
estimated_capacity the approximate maximum number of items to be held in the hash table, or 0 for no estimate.
threadsafe true to create an internal rwlock for this table.
hash the function to use to hash keys.
keymatch the function to use to compare keys.
destroy the function to use to clean up keys and values, may be NULL.
userdata a pointer that is passed to the callbacks.
Returns
a newly-created hash table, or NULL if there was an error; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_DestroyHashTable
{
    const Uint32 num_buckets = CalculateHashBucketsFromEstimate(estimated_capacity);
    SDL_HashTable *table = (SDL_HashTable *)SDL_calloc(1, sizeof(SDL_HashTable));
    if (!table) {
        return NULL;
    }
    if (threadsafe) {
        table->lock = SDL_CreateRWLock();
        if (!table->lock) {
            SDL_DestroyHashTable(table);
            return NULL;
        }
    }
    table->table = (SDL_HashItem *)SDL_calloc(num_buckets, sizeof(SDL_HashItem));
    if (!table->table) {
        SDL_DestroyHashTable(table);
        return NULL;
    }
    table->hash_mask = num_buckets - 1;
    table->userdata = userdata;
    table->hash = hash;
    table->keymatch = keymatch;
    table->destroy = destroy;
    return table;
}
References CalculateHashBucketsFromEstimate(), SDL_HashTable::destroy, SDL_HashTable::hash, SDL_HashTable::hash_mask, SDL_HashTable::keymatch, SDL_HashTable::lock, NULL, SDL_calloc(), SDL_CreateRWLock(), SDL_DestroyHashTable(), SDL_HashTable::table, and SDL_HashTable::userdata.
Referenced by SDL_CameraInit(), SDL_CreateEnvironment(), SDL_CreateKeymap(), SDL_CreateProperties(), SDL_GetPersistentString(), SDL_GetPixelFormatDetails(), SDL_InitAudio(), SDL_InitProperties(), SDL_IsGamepad(), SDL_MapSurface(), and SDL_SetObjectValid().
SDL_DestroyHashKey()
void SDL_DestroyHashKey (void * unused, const void * key, const void * value) extern
Free just the value pointer of a hash table item.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of data to be used with the hash table.
This literally calls SDL_free(key); and leaves value alone.
Parameters
unused this parameter is ignored.
key the key to be destroyed.
value the value to be destroyed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)value;
    (void)unused;
    SDL_free((void *)key);
}
References SDL_free(), and void().
Referenced by SDL_CreateEnvironment().
SDL_DestroyHashKeyAndValue()
void SDL_DestroyHashKeyAndValue (void * unused, const void * key, const void * value) extern
Free both the key and value pointers of a hash table item.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of data to be used with the hash table.
This literally calls SDL_free(key); and SDL_free(value);.
Parameters
unused this parameter is ignored.
key the key to be destroyed.
value the value to be destroyed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    SDL_free((void *)key);
    SDL_free((void *)value);
}
References SDL_free(), and void().
SDL_DestroyHashTable()
void SDL_DestroyHashTable (SDL_HashTable * table) extern
Destroy a hash table.
This will call the hash table's SDL_HashDestroyCallback for each item in the table, removing all inserted items, before deallocating the table itself.
The table becomes invalid once this function is called, and no other thread should be accessing this table once this function has started.
Parameters
table the hash table to destroy.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (table) {
        destroy_all(table);
        if (table->lock) {
            SDL_DestroyRWLock(table->lock);
        }
        SDL_free(table->table);
        SDL_free(table);
    }
}
References destroy_all(), SDL_HashTable::lock, SDL_DestroyRWLock(), SDL_free(), and SDL_HashTable::table.
Referenced by SDL_CameraInit(), SDL_CreateHashTable(), SDL_DestroyEnvironment(), SDL_DestroyKeymap(), SDL_FreePersistentStrings(), SDL_FreeProperties(), SDL_InitAudio(), SDL_InvalidateMap(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitGamepadMappings(), SDL_QuitPixelFormatDetails(), SDL_QuitProperties(), and SDL_SetObjectsInvalid().
SDL_DestroyHashValue()
void SDL_DestroyHashValue (void * unused, const void * key, const void * value) extern
Free just the value pointer of a hash table item.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of data to be used with the hash table.
This literally calls SDL_free(value); and leaves key alone.
Parameters
unused this parameter is ignored.
key the key to be destroyed.
value the value to be destroyed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)key;
    (void)unused;
    SDL_free((void *)value);
}
References SDL_free(), and void().
Referenced by SDL_GetPersistentString(), and SDL_GetPixelFormatDetails().
SDL_FindInHashTable()
bool SDL_FindInHashTable (const SDL_HashTable * table, const void * key, const void ** value) extern
Look up an item in a hash table.
On return, the value associated with key is stored to *value. If the key does not exist in the table, *value will be set to NULL.
It is legal for value to be NULL, to not retrieve the key's value. In this case, the return value is still useful for reporting if the key exists in the table at all.
Parameters
table the hash table to search.
key the key to search for in the table.
value the found value will be stored here. Can be NULL.
Returns
true if key exists in the table, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_InsertIntoHashTable
{
    if (!table) {
        if (value) {
            *value = NULL;
        }
        return SDL_InvalidParamError("table");
    }
    SDL_LockRWLockForReading(table->lock);
    bool result = false;
    const Uint32 hash = calc_hash(table, key);
    SDL_HashItem *i = find_first_item(table, key, hash);
    if (i) {
        if (value) {
            *value = i->value;
        }
        result = true;
    }
    SDL_UnlockRWLock(table->lock);
    return result;
}
References calc_hash(), find_first_item(), SDL_HashTable::lock, NULL, SDL_InvalidParamError, SDL_LockRWLockForReading(), SDL_UnlockRWLock(), and SDL_HashItem::value.
Referenced by ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalCamera(), SDL_CopyProperties(), SDL_CreateProperties(), SDL_DestroyProperties(), SDL_EnumerateProperties(), SDL_GetAudioDeviceName(), SDL_GetBooleanProperty(), SDL_GetEnvironmentVariable(), SDL_GetFloatProperty(), SDL_GetKeymapKeycode(), SDL_GetKeymapScancode(), SDL_GetNumberProperty(), SDL_GetPersistentString(), SDL_GetPixelFormatDetails(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetStringProperty(), SDL_IsGamepad(), SDL_LockProperties(), SDL_LookupRGBAColor(), SDL_ObjectValid(), SDL_PrivateSetProperty(), SDL_SetEnvironmentVariable(), SDL_SetKeymapEntry(), SDL_UnlockProperties(), and SDL_UnsetEnvironmentVariable().
SDL_HashID()
Uint32 SDL_HashID (void * unused, const void * key) extern
Generate a hash from an integer ID.
The key is intended to a unique integer, possibly within a small range.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Note that the implementation may change in the future; do not expect the results to be stable vs future SDL releases. Use this in a hash table in the current process and don't store them to disk for the future.
Parameters
unused this parameter is ignored.
key the key to hash as a generic pointer.
Returns
a 32-bit hash of the key.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return (Uint32)(uintptr_t)key;
}
References void().
Referenced by SDL_CameraInit(), SDL_CreateKeymap(), SDL_GetPixelFormatDetails(), SDL_InitProperties(), SDL_IsGamepad(), and SDL_MapSurface().
SDL_HashPointer()
Uint32 SDL_HashPointer (void * unused, const void * key) extern
Generate a hash from a generic pointer.
The key is intended to be a unique pointer to any datatype.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Note that the implementation may change in the future; do not expect the results to be stable vs future SDL releases. Use this in a hash table in the current process and don't store them to disk for the future.
Parameters
unused this parameter is ignored.
key the key to hash as a generic pointer.
Returns
a 32-bit hash of the key.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return SDL_murmur3_32(&key, sizeof(key), 0);
}
References SDL_murmur3_32(), and void().
SDL_HashString()
Uint32 SDL_HashString (void * unused, const void * key) extern
Generate a hash from a C string.
The key is intended to be a NULL-terminated string, in UTF-8 format.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Note that the implementation may change in the future; do not expect the results to be stable vs future SDL releases. Use this in a hash table in the current process and don't store them to disk for the future.
Parameters
unused this parameter is ignored.
key the key to hash as a generic pointer.
Returns
a 32-bit hash of the key.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    const char *str = (const char *)key;
    return hash_string_djbxor(str, SDL_strlen(str));
}
References hash_string_djbxor(), SDL_strlen(), and void().
Referenced by SDL_CreateEnvironment(), SDL_CreateProperties(), and SDL_GetPersistentString().
SDL_HashTableEmpty()
bool SDL_HashTableEmpty (SDL_HashTable * table) extern
Check if any items are currently stored in a hash table.
If there are no items stored (the table is completely empty), this will return true.
Parameters
table the hash table to check.
Returns
true if the table is completely empty, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_ClearHashTable
{
    if (!table) {
        return SDL_InvalidParamError("table");
    }
    SDL_LockRWLockForReading(table->lock);
    const bool retval = (table->num_occupied_slots == 0);
    SDL_UnlockRWLock(table->lock);
    return retval;
}
References SDL_HashTable::lock, SDL_HashTable::num_occupied_slots, SDL_InvalidParamError, SDL_LockRWLockForReading(), and SDL_UnlockRWLock().
Referenced by SDL_SetObjectsInvalid().
SDL_InsertIntoHashTable()
bool SDL_InsertIntoHashTable (SDL_HashTable * table, const void * key, const void * value, bool replace) extern
Add an item to a hash table.
All keys in the table must be unique. If attempting to insert a key that already exists in the hash table, what will be done depends on the replace value:
If replace is false, this function will return false without modifying the table.
If replace is true, SDL will remove the previous item first, so the new value is the only one associated with that key. This will call the hash table's SDL_HashDestroyCallback for the previous item.
Parameters
table the hash table to insert into.
key the key of the new item to insert.
value the value of the new item to insert.
replace true if a duplicate key should replace the previous value.
Returns
true if the new item was inserted, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (!table) {
        return SDL_InvalidParamError("table");
    }
    bool result = false;
    SDL_LockRWLockForWriting(table->lock);
    const Uint32 hash = calc_hash(table, key);
    SDL_HashItem *item = find_first_item(table, key, hash);
    bool do_insert = true;
    if (item) {
        if (replace) {
            delete_item(table, item);
        } else {
            SDL_SetError("key already exists and replace is disabled");
            do_insert = false;
        }
    }
    if (do_insert) {
        SDL_HashItem new_item;
        new_item.key = key;
        new_item.value = value;
        new_item.hash = hash;
        new_item.live = true;
        new_item.probe_len = 0;
        table->num_occupied_slots++;
        if (!maybe_resize(table)) {
            table->num_occupied_slots--;
        } else {
            // This never returns NULL
            insert_item(&new_item, table->table, table->hash_mask, &table->max_probe_len);
            result = true;
        }
    }
    SDL_UnlockRWLock(table->lock);
    return result;
}
References calc_hash(), delete_item(), find_first_item(), SDL_HashItem::hash, SDL_HashTable::hash_mask, insert_item(), SDL_HashItem::key, SDL_HashItem::live, SDL_HashTable::lock, SDL_HashTable::max_probe_len, maybe_resize(), SDL_HashTable::num_occupied_slots, SDL_HashItem::probe_len, SDL_InvalidParamError, SDL_LockRWLockForWriting(), SDL_SetError(), SDL_UnlockRWLock(), SDL_HashTable::table, and SDL_HashItem::value.
Referenced by CopyOneProperty(), CreatePhysicalAudioDevice(), PopMappingChangeTracking(), SDL_AddCamera(), SDL_CreateEnvironment(), SDL_CreateProperties(), SDL_GetPersistentString(), SDL_GetPixelFormatDetails(), SDL_IsGamepad(), SDL_LookupRGBAColor(), SDL_OpenAudioDevice(), SDL_PrivateSetProperty(), SDL_SetEnvironmentVariable(), SDL_SetKeymapEntry(), and SDL_SetObjectValid().
SDL_IterateHashTable()
bool SDL_IterateHashTable (const SDL_HashTable * table, SDL_HashTableIterateCallback callback, void * userdata) extern
Iterate all key/value pairs in a hash table.
This function will call callback once for each key/value pair in the table, until either all pairs have been presented to the callback, or the callback has returned false to signal it is done.
There is no guarantee what order results will be returned in.
Parameters
table the hash table to iterate.
callback the function pointer to call for each value.
userdata a pointer that is passed to callback.
Returns
true if iteration happened, false if not (bogus parameter, etc.).
Since
This function is available since SDL 3.4.0.
{
    if (!table) {
        return SDL_InvalidParamError("table");
    } else if (!callback) {
        return SDL_InvalidParamError("callback");
    }
    SDL_LockRWLockForReading(table->lock);
    SDL_HashItem *end = table->table + (table->hash_mask + 1);
    Uint32 num_iterated = 0;
    for (SDL_HashItem *item = table->table; item < end; item++) {
        if (item->live) {
            if (!callback(userdata, table, item->key, item->value)) {
                break;  // callback requested iteration stop.
            } else if (++num_iterated >= table->num_occupied_slots) {
                break;  // we can drop out early because we've seen all the live items.
            }
        }
    }
    SDL_UnlockRWLock(table->lock);
    return true;
}
References SDL_HashTable::hash_mask, SDL_HashTable::lock, SDL_HashTable::num_occupied_slots, SDL_InvalidParamError, SDL_LockRWLockForReading(), SDL_UnlockRWLock(), and SDL_HashTable::table.
Referenced by GetAudioDevices(), GetFirstAddedAudioDevice(), SDL_CopyProperties(), SDL_EnumerateProperties(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetCameras(), SDL_GetEnvironmentVariables(), SDL_GetObjects(), SDL_QuitAudio(), SDL_QuitProperties(), and SDL_SetObjectsInvalid().
SDL_KeyMatchID()
bool SDL_KeyMatchID (void * unused, const void * a, const void * b) extern
Compare two integer IDs as hash table keys.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Parameters
unused this parameter is ignored.
a the first ID to compare.
b the second ID to compare.
Returns
true if the IDs are the same, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return (a == b);
}
References void().
Referenced by SDL_CameraInit(), SDL_CreateKeymap(), SDL_GetPixelFormatDetails(), SDL_InitAudio(), SDL_InitProperties(), SDL_IsGamepad(), and SDL_MapSurface().
SDL_KeyMatchPointer()
bool SDL_KeyMatchPointer (void * unused, const void * a, const void * b) extern
Compare two generic pointers as hash table keys.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Parameters
unused this parameter is ignored.
a the first generic pointer to compare.
b the second generic pointer to compare.
Returns
true if the pointers are the same, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    (void)unused;
    return (a == b);
}
References void().
SDL_KeyMatchString()
bool SDL_KeyMatchString (void * unused, const void * a, const void * b) extern
Compare two C strings as hash table keys.
Strings will be compared in a case-sensitive manner. More specifically, they'll be compared as NULL-terminated arrays of bytes.
This is intended to be used as one of the callbacks to SDL_CreateHashTable, if this is useful to the type of keys to be used with the hash table.
Parameters
unused this parameter is ignored.
a the first string to compare.
b the second string to compare.
Returns
true if the strings are the same, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateHashTable
{
    const char *a_string = (const char *)a;
    const char *b_string = (const char *)b;
    (void)unused;
    if (a == b) {
        return true; // same pointer, must match.
    } else if (!a || !b) {
        return false; // one pointer is NULL (and first test shows they aren't the same pointer), must not match.
    } else if (a_string[0] != b_string[0]) {
        return false; // we know they don't match
    }
    return (SDL_strcmp(a_string, b_string) == 0); // Check against actual string contents.
}
References SDL_strcmp(), and void().
Referenced by SDL_CreateEnvironment(), SDL_CreateProperties(), and SDL_GetPersistentString().
SDL_RemoveFromHashTable()
bool SDL_RemoveFromHashTable (SDL_HashTable * table, const void * key) extern
Remove an item from a hash table.
If there is an item that matches key, it is removed from the table. This will call the hash table's SDL_HashDestroyCallback for the item to be removed.
Parameters
table the hash table to remove from.
key the key of the item to remove from the table.
Returns
true if a key was removed, false if the key was not found.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (!table) {
        return SDL_InvalidParamError("table");
    }
    SDL_LockRWLockForWriting(table->lock);
    bool result = false;
    const Uint32 hash = calc_hash(table, key);
    SDL_HashItem *item = find_first_item(table, key, hash);
    if (item) {
        delete_item(table, item);
        result = true;
    }
    SDL_UnlockRWLock(table->lock);
    return result;
}
References calc_hash(), delete_item(), find_first_item(), SDL_HashTable::lock, SDL_InvalidParamError, SDL_LockRWLockForWriting(), and SDL_UnlockRWLock().
Referenced by DestroyLogicalAudioDevice(), SDL_DestroyProperties(), SDL_PrivateSetProperty(), SDL_SetObjectValid(), SDL_UnsetEnvironmentVariable(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().