SDL3: SDL-main/include/SDL3/SDL_rect.h File Reference
SDL_rect.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_FPoint
struct SDL_FRect
struct SDL_Point
struct SDL_Rect
Typedefs
typedef struct SDL_FPoint SDL_FPoint
typedef struct SDL_FRect SDL_FRect
typedef struct SDL_Point SDL_Point
typedef struct SDL_Rect SDL_Rect
Functions
SDL_DECLSPEC bool SDLCALL SDL_GetRectAndLineIntersection (const SDL_Rect *rect, int *X1, int *Y1, int *X2, int *Y2)
SDL_DECLSPEC bool SDLCALL SDL_GetRectAndLineIntersectionFloat (const SDL_FRect *rect, float *X1, float *Y1, float *X2, float *Y2)
SDL_DECLSPEC bool SDLCALL SDL_GetRectEnclosingPoints (const SDL_Point *points, int count, const SDL_Rect *clip, SDL_Rect *result)
SDL_DECLSPEC bool SDLCALL SDL_GetRectEnclosingPointsFloat (const SDL_FPoint *points, int count, const SDL_FRect *clip, SDL_FRect *result)
SDL_DECLSPEC bool SDLCALL SDL_GetRectIntersection (const SDL_Rect *A, const SDL_Rect *B, SDL_Rect *result)
SDL_DECLSPEC bool SDLCALL SDL_GetRectIntersectionFloat (const SDL_FRect *A, const SDL_FRect *B, SDL_FRect *result)
SDL_DECLSPEC bool SDLCALL SDL_GetRectUnion (const SDL_Rect *A, const SDL_Rect *B, SDL_Rect *result)
SDL_DECLSPEC bool SDLCALL SDL_GetRectUnionFloat (const SDL_FRect *A, const SDL_FRect *B, SDL_FRect *result)
SDL_DECLSPEC bool SDLCALL SDL_HasRectIntersection (const SDL_Rect *A, const SDL_Rect *B)
SDL_DECLSPEC bool SDLCALL SDL_HasRectIntersectionFloat (const SDL_FRect *A, const SDL_FRect *B)
SDL_FORCE_INLINE bool SDL_PointInRect (const SDL_Point *p, const SDL_Rect *r)
SDL_FORCE_INLINE bool SDL_PointInRectFloat (const SDL_FPoint *p, const SDL_FRect *r)
SDL_FORCE_INLINE bool SDL_RectEmpty (const SDL_Rect *r)
SDL_FORCE_INLINE bool SDL_RectEmptyFloat (const SDL_FRect *r)
SDL_FORCE_INLINE bool SDL_RectsEqual (const SDL_Rect *a, const SDL_Rect *b)
SDL_FORCE_INLINE bool SDL_RectsEqualEpsilon (const SDL_FRect *a, const SDL_FRect *b, float epsilon)
SDL_FORCE_INLINE bool SDL_RectsEqualFloat (const SDL_FRect *a, const SDL_FRect *b)
SDL_FORCE_INLINE void SDL_RectToFRect (const SDL_Rect *rect, SDL_FRect *frect)
Typedef Documentation
SDL_FPoint
typedef struct SDL_FPoint SDL_FPoint
The structure that defines a point (using floating point values).
Since
This struct is available since SDL 3.2.0.
See also
SDL_GetRectEnclosingPointsFloat
SDL_PointInRectFloat
SDL_FRect
typedef struct SDL_FRect SDL_FRect
A rectangle, with the origin at the upper left (using floating point values).
Since
This struct is available since SDL 3.2.0.
See also
SDL_RectEmptyFloat
SDL_RectsEqualFloat
SDL_RectsEqualEpsilon
SDL_HasRectIntersectionFloat
SDL_GetRectIntersectionFloat
SDL_GetRectAndLineIntersectionFloat
SDL_GetRectUnionFloat
SDL_GetRectEnclosingPointsFloat
SDL_PointInRectFloat
SDL_Point
typedef struct SDL_Point SDL_Point
CategoryRect
Some helper functions for managing rectangles and 2D points, in both integer and floating point versions. The structure that defines a point (using integers).
Since
This struct is available since SDL 3.2.0.
See also
SDL_GetRectEnclosingPoints
SDL_PointInRect
SDL_Rect
typedef struct SDL_Rect SDL_Rect
A rectangle, with the origin at the upper left (using integers).
Since
This struct is available since SDL 3.2.0.
See also
SDL_RectEmpty
SDL_RectsEqual
SDL_HasRectIntersection
SDL_GetRectIntersection
SDL_GetRectAndLineIntersection
SDL_GetRectUnion
SDL_GetRectEnclosingPoints
Function Documentation
SDL_GetRectAndLineIntersection()
SDL_DECLSPEC bool SDLCALL SDL_GetRectAndLineIntersection (const SDL_Rect * rect, int * X1, int * Y1, int * X2, int * Y2) extern
Calculate the intersection of a rectangle and line segment.
This function is used to clip a line segment to a rectangle. A line segment contained entirely within the rectangle or that does not intersect will remain unchanged. A line segment that crosses the rectangle at either or both ends will be clipped to the boundary of the rectangle and the new coordinates saved in X1, Y1, X2, and/or Y2 as necessary.
Parameters
rect an SDL_Rect structure representing the rectangle to intersect.
X1 a pointer to the starting X-coordinate of the line.
Y1 a pointer to the starting Y-coordinate of the line.
X2 a pointer to the ending X-coordinate of the line.
Y2 a pointer to the ending Y-coordinate of the line.
Returns
true if there is an intersection, false otherwise.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, and SDLCALL.
Referenced by RenderLineBresenham().
SDL_GetRectAndLineIntersectionFloat()
SDL_DECLSPEC bool SDLCALL SDL_GetRectAndLineIntersectionFloat (const SDL_FRect * rect, float * X1, float * Y1, float * X2, float * Y2) extern
Calculate the intersection of a rectangle and line segment with float precision.
This function is used to clip a line segment to a rectangle. A line segment contained entirely within the rectangle or that does not intersect will remain unchanged. A line segment that crosses the rectangle at either or both ends will be clipped to the boundary of the rectangle and the new coordinates saved in X1, Y1, X2, and/or Y2 as necessary.
Parameters
rect an SDL_FRect structure representing the rectangle to intersect.
X1 a pointer to the starting X-coordinate of the line.
Y1 a pointer to the starting Y-coordinate of the line.
X2 a pointer to the ending X-coordinate of the line.
Y2 a pointer to the ending Y-coordinate of the line.
Returns
true if there is an intersection, false otherwise.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, and SDLCALL.
SDL_GetRectEnclosingPoints()
SDL_DECLSPEC bool SDLCALL SDL_GetRectEnclosingPoints (const SDL_Point * points, int count, const SDL_Rect * clip, SDL_Rect * result) extern
Calculate a minimal rectangle enclosing a set of points.
If clip is not NULL then only points inside of the clipping rectangle are considered.
Parameters
points an array of SDL_Point structures representing points to be enclosed.
count the number of structures in the points array.
clip an SDL_Rect used for clipping or NULL to enclose all points.
result an SDL_Rect structure filled in with the minimal enclosing rectangle.
Returns
true if any points were enclosed or false if all the points were outside of the clipping rectangle.
Since
This function is available since SDL 3.2.0.
References count, SDL_DECLSPEC, and SDLCALL.
Referenced by GetDisplayForRect().
SDL_GetRectEnclosingPointsFloat()
SDL_DECLSPEC bool SDLCALL SDL_GetRectEnclosingPointsFloat (const SDL_FPoint * points, int count, const SDL_FRect * clip, SDL_FRect * result) extern
Calculate a minimal rectangle enclosing a set of points with float precision.
If clip is not NULL then only points inside of the clipping rectangle are considered.
Parameters
points an array of SDL_FPoint structures representing points to be enclosed.
count the number of structures in the points array.
clip an SDL_FRect used for clipping or NULL to enclose all points.
result an SDL_FRect structure filled in with the minimal enclosing rectangle.
Returns
true if any points were enclosed or false if all the points were outside of the clipping rectangle.
Since
This function is available since SDL 3.2.0.
References count, SDL_DECLSPEC, and SDLCALL.
SDL_GetRectIntersection()
SDL_DECLSPEC bool SDLCALL SDL_GetRectIntersection (const SDL_Rect * A, const SDL_Rect * B, SDL_Rect * result) extern
Calculate the intersection of two rectangles.
If result is NULL then this function will return false.
Parameters
A an SDL_Rect structure representing the first rectangle.
B an SDL_Rect structure representing the second rectangle.
result an SDL_Rect structure filled in with the intersection of rectangles A and B.
Returns
true if there is an intersection, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasRectIntersection
References SDL_DECLSPEC, and SDLCALL.
Referenced by ConstrainMousePosition(), SDL_BlitSurface(), SDL_BlitSurfaceScaled(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_FillSurfaceRects(), SDL_GetRenderSafeArea(), SDL_LockTextureToSurface(), SDL_RenderReadPixels(), SDL_SetSurfaceClipRect(), SDL_UpdateNVTexture(), SDL_UpdateTexture(), and SDL_UpdateYUVTexture().
SDL_GetRectIntersectionFloat()
SDL_DECLSPEC bool SDLCALL SDL_GetRectIntersectionFloat (const SDL_FRect * A, const SDL_FRect * B, SDL_FRect * result) extern
Calculate the intersection of two rectangles with float precision.
If result is NULL then this function will return false.
Parameters
A an SDL_FRect structure representing the first rectangle.
B an SDL_FRect structure representing the second rectangle.
result an SDL_FRect structure filled in with the intersection of rectangles A and B.
Returns
true if there is an intersection, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasRectIntersectionFloat
References SDL_DECLSPEC, and SDLCALL.
Referenced by SDL_RenderTexture(), SDL_RenderTextureAffine(), SDL_RenderTextureRotated(), and SDL_RenderTextureTiled().
SDL_GetRectUnion()
SDL_DECLSPEC bool SDLCALL SDL_GetRectUnion (const SDL_Rect * A, const SDL_Rect * B, SDL_Rect * result) extern
Calculate the union of two rectangles.
Parameters
A an SDL_Rect structure representing the first rectangle.
B an SDL_Rect structure representing the second rectangle.
result an SDL_Rect structure filled in with the union of rectangles A and B.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, and SDLCALL.
Referenced by SDL_UpdateDesktopBounds().
SDL_GetRectUnionFloat()
SDL_DECLSPEC bool SDLCALL SDL_GetRectUnionFloat (const SDL_FRect * A, const SDL_FRect * B, SDL_FRect * result) extern
Calculate the union of two rectangles with float precision.
Parameters
A an SDL_FRect structure representing the first rectangle.
B an SDL_FRect structure representing the second rectangle.
result an SDL_FRect structure filled in with the union of rectangles A and B.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, and SDLCALL.
SDL_HasRectIntersection()
SDL_DECLSPEC bool SDLCALL SDL_HasRectIntersection (const SDL_Rect * A, const SDL_Rect * B) extern
Determine whether two rectangles intersect.
If either pointer is NULL the function will return false.
Parameters
A an SDL_Rect structure representing the first rectangle.
B an SDL_Rect structure representing the second rectangle.
Returns
true if there is an intersection, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRectIntersection
References SDL_DECLSPEC, and SDLCALL.
SDL_HasRectIntersectionFloat()
SDL_DECLSPEC bool SDLCALL SDL_HasRectIntersectionFloat (const SDL_FRect * A, const SDL_FRect * B) extern
Determine whether two rectangles intersect with float precision.
If either pointer is NULL the function will return false.
Parameters
A an SDL_FRect structure representing the first rectangle.
B an SDL_FRect structure representing the second rectangle.
Returns
true if there is an intersection, false otherwise.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRectIntersection
References SDL_DECLSPEC, and SDLCALL.
SDL_PointInRect()
SDL_FORCE_INLINE bool SDL_PointInRect (const SDL_Point * p, const SDL_Rect * r)
Determine whether a point resides inside a rectangle.
A point is considered part of a rectangle if both p and r are not NULL, and p's x and y coordinates are >= to the rectangle's top left corner, and < the rectangle's x+w and y+h. So a 1x1 rectangle considers point (0,0) as "inside" and (0,1) as not.
Note that this is a forced-inline function in a header, and not a public API function available in the SDL library (which is to say, the code is embedded in the calling program and the linker and dynamic loader will not be able to find this function inside SDL itself).
Parameters
p the point to test.
r the rectangle to test.
Returns
true if p is contained by r, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return ( p && r && (p->x >= r->x) && (p->x < (r->x + r->w)) &&
             (p->y >= r->y) && (p->y < (r->y + r->h)) ) ? true : false;
}
References SDL_Rect::h, SDL_FORCE_INLINE, true, SDL_Rect::w, SDL_Point::x, SDL_Rect::x, SDL_Point::y, and SDL_Rect::y.
SDL_PointInRectFloat()
SDL_FORCE_INLINE bool SDL_PointInRectFloat (const SDL_FPoint * p, const SDL_FRect * r)
Determine whether a point resides inside a floating point rectangle.
A point is considered part of a rectangle if both p and r are not NULL, and p's x and y coordinates are >= to the rectangle's top left corner, and <= the rectangle's x+w and y+h. So a 1x1 rectangle considers point (0,0) and (0,1) as "inside" and (0,2) as not.
Note that this is a forced-inline function in a header, and not a public API function available in the SDL library (which is to say, the code is embedded in the calling program and the linker and dynamic loader will not be able to find this function inside SDL itself).
Parameters
p the point to test.
r the rectangle to test.
Returns
true if p is contained by r, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return ( p && r && (p->x >= r->x) && (p->x <= (r->x + r->w)) &&
             (p->y >= r->y) && (p->y <= (r->y + r->h)) ) ? true : false;
}
References SDL_FRect::h, SDL_FORCE_INLINE, true, SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
SDL_RectEmpty()
SDL_FORCE_INLINE bool SDL_RectEmpty (const SDL_Rect * r)
Determine whether a rectangle has no area.
A rectangle is considered "empty" for this function if r is NULL, or if r's width and/or height are <= 0.
Note that this is a forced-inline function in a header, and not a public API function available in the SDL library (which is to say, the code is embedded in the calling program and the linker and dynamic loader will not be able to find this function inside SDL itself).
Parameters
r the rectangle to test.
Returns
true if the rectangle is "empty", false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return ((!r) || (r->w <= 0) || (r->h <= 0)) ? true : false;
}
References SDL_Rect::h, SDL_FORCE_INLINE, true, and SDL_Rect::w.
Referenced by SDL_FillSurfaceRect(), SDL_GetWindowMouseRect(), and SDL_GetWindowSafeArea().
SDL_RectEmptyFloat()
SDL_FORCE_INLINE bool SDL_RectEmptyFloat (const SDL_FRect * r)
Determine whether a floating point rectangle takes no space.
A rectangle is considered "empty" for this function if r is NULL, or if r's width and/or height are < 0.0f.
Note that this is a forced-inline function in a header, and not a public API function available in the SDL library (which is to say, the code is embedded in the calling program and the linker and dynamic loader will not be able to find this function inside SDL itself).
Parameters
r the rectangle to test.
Returns
true if the rectangle is "empty", false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return ((!r) || (r->w < 0.0f) || (r->h < 0.0f)) ? true : false;
}
References SDL_FRect::h, SDL_FORCE_INLINE, true, and SDL_FRect::w.
SDL_RectsEqual()
SDL_FORCE_INLINE bool SDL_RectsEqual (const SDL_Rect * a, const SDL_Rect * b)
Determine whether two rectangles are equal.
Rectangles are considered equal if both are not NULL and each of their x, y, width and height match.
Note that this is a forced-inline function in a header, and not a public API function available in the SDL library (which is to say, the code is embedded in the calling program and the linker and dynamic loader will not be able to find this function inside SDL itself).
Parameters
a the first rectangle to test.
b the second rectangle to test.
Returns
true if the rectangles are equal, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (a && b && (a->x == b->x) && (a->y == b->y) &&
            (a->w == b->w) && (a->h == b->h)) ? true : false;
}
References SDL_Rect::h, SDL_FORCE_INLINE, true, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
SDL_RectsEqualEpsilon()
SDL_FORCE_INLINE bool SDL_RectsEqualEpsilon (const SDL_FRect * a, const SDL_FRect * b, float epsilon)
Determine whether two floating point rectangles are equal, within some given epsilon.
Rectangles are considered equal if both are not NULL and each of their x, y, width and height are within epsilon of each other. If you don't know what value to use for epsilon, you should call the SDL_RectsEqualFloat function instead.
Note that this is a forced-inline function in a header, and not a public API function available in the SDL library (which is to say, the code is embedded in the calling program and the linker and dynamic loader will not be able to find this function inside SDL itself).
Parameters
a the first rectangle to test.
b the second rectangle to test.
epsilon the epsilon value for comparison.
Returns
true if the rectangles are equal, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RectsEqualFloat
{
    return (a && b && ((a == b) ||
            ((SDL_fabsf(a->x - b->x) <= epsilon) &&
            (SDL_fabsf(a->y - b->y) <= epsilon) &&
            (SDL_fabsf(a->w - b->w) <= epsilon) &&
            (SDL_fabsf(a->h - b->h) <= epsilon))))
            ? true : false;
}
References SDL_FRect::h, SDL_fabsf(), SDL_FORCE_INLINE, true, SDL_FRect::w, SDL_FRect::x, and SDL_FRect::y.
Referenced by SDL_RectsEqualFloat().
SDL_RectsEqualFloat()
SDL_FORCE_INLINE bool SDL_RectsEqualFloat (const SDL_FRect * a, const SDL_FRect * b)
Determine whether two floating point rectangles are equal, within a default epsilon.
Rectangles are considered equal if both are not NULL and each of their x, y, width and height are within SDL_FLT_EPSILON of each other. This is often a reasonable way to compare two floating point rectangles and deal with the slight precision variations in floating point calculations that tend to pop up.
Note that this is a forced-inline function in a header, and not a public API function available in the SDL library (which is to say, the code is embedded in the calling program and the linker and dynamic loader will not be able to find this function inside SDL itself).
Parameters
a the first rectangle to test.
b the second rectangle to test.
Returns
true if the rectangles are equal, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RectsEqualEpsilon
{
    return SDL_RectsEqualEpsilon(a, b, SDL_FLT_EPSILON);
}
References SDL_FLT_EPSILON, SDL_FORCE_INLINE, and SDL_RectsEqualEpsilon().
SDL_RectToFRect()
SDL_FORCE_INLINE void SDL_RectToFRect (const SDL_Rect * rect, SDL_FRect * frect)
Convert an SDL_Rect to SDL_FRect
Parameters
rect a pointer to an SDL_Rect.
frect a pointer filled in with the floating point representation of rect.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    frect->x = (float)rect->x;
    frect->y = (float)rect->y;
    frect->w = (float)rect->w;
    frect->h = (float)rect->h;
}
References SDL_FRect::h, SDL_Rect::h, SDL_FORCE_INLINE, SDL_FRect::w, SDL_Rect::w, SDL_FRect::x, SDL_Rect::x, SDL_FRect::y, and SDL_Rect::y.