SDL3: SDL-main/src/video/android/SDL_androidevents.h File Reference
SDL_androidevents.h File Reference
#include "SDL_internal.h"
Functions
void Android_InitEvents (void)
void Android_PumpEvents (Sint64 timeoutNS)
void Android_QuitEvents (void)
bool Android_WaitActiveAndLockActivity (void)
Function Documentation
Android_InitEvents()
void Android_InitEvents (void) extern
Referenced by SDL_InitEvents().
Android_PumpEvents()
void Android_PumpEvents (Sint64 timeoutNS) extern
Referenced by SDL_PumpEventsInternal(), and SDL_WaitEventTimeoutNS().
Android_QuitEvents()
void Android_QuitEvents (void) extern
Referenced by SDL_QuitEvents().
Android_WaitActiveAndLockActivity()
bool Android_WaitActiveAndLockActivity (void) extern
Referenced by SDL_CreateRendererWithProperties().