SDL3: SDL-main/src/video/SDL_stb_c.h File Reference
SDL_stb_c.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_ConvertPixels_STB (int width, int height, SDL_PixelFormat src_format, SDL_Colorspace src_colorspace, SDL_PropertiesID src_properties, const void *src, int src_pitch, SDL_PixelFormat dst_format, SDL_Colorspace dst_colorspace, SDL_PropertiesID dst_properties, void *dst, int dst_pitch)
Function Documentation
SDL_ConvertPixels_STB()
bool SDL_ConvertPixels_STB (int width, int height, SDL_PixelFormat src_format, SDL_Colorspace src_colorspace, SDL_PropertiesID src_properties, const void * src, int src_pitch, SDL_PixelFormat dst_format, SDL_Colorspace dst_colorspace, SDL_PropertiesID dst_properties, void * dst, int dst_pitch) extern
{
#ifdef SDL_HAVE_STB
    if (src_format == SDL_PIXELFORMAT_MJPG && dst_format == SDL_PIXELFORMAT_NV12) {
        return SDL_ConvertPixels_MJPG_to_NV12(width, height, src, src_pitch, dst, dst_pitch);
    }
    bool result;
    int w = 0, h = 0, format = 0;
    int len = (src_format == SDL_PIXELFORMAT_MJPG) ? src_pitch : (height * src_pitch);
    void *pixels = stbi_load_from_memory(src, len, &w, &h, &format, 4);
    if (!pixels) {
        return false;
    }
    if (w == width && h == height) {
        result = SDL_ConvertPixelsAndColorspace(w, h, SDL_PIXELFORMAT_RGBA32, SDL_COLORSPACE_SRGB, 0, pixels, width * 4, dst_format, dst_colorspace, dst_properties, dst, dst_pitch);
    } else {
        result = SDL_SetError("Expected image size %dx%d, actual size %dx%d", width, height, w, h);
    }
    stbi_image_free(pixels);
    return result;
#else
    return SDL_SetError("SDL not built with STB image support");
#endif
}
References SDL_COLORSPACE_SRGB, SDL_ConvertPixelsAndColorspace(), SDL_PIXELFORMAT_MJPG, SDL_PIXELFORMAT_NV12, SDL_PIXELFORMAT_RGBA32, SDL_SetError(), stbi_image_free(), and stbi_load_from_memory().
Referenced by SDL_ConvertPixelsAndColorspace().