SDL3: SDL-main/src/video/windows/SDL_surface_utils.h File Reference
SDL_surface_utils.h File Reference
#include "SDL_internal.h"
#include "../../core/windows/SDL_windows.h"
Functions
HICON CreateIconFromSurface (SDL_Surface *surface)
Function Documentation
CreateIconFromSurface()
HICON CreateIconFromSurface (SDL_Surface * surface) extern
{
    SDL_Surface *s = SDL_ConvertSurface(surface, SDL_PIXELFORMAT_ARGB8888);
    if (!s) {
        return NULL;
    }
    /* The dimensions will be needed after s is freed */
    const int width = s->w;
    const int height = s->h;
    BITMAPINFO bmpInfo;
    SDL_zero(bmpInfo);
    bmpInfo.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
    bmpInfo.bmiHeader.biWidth = width;
    bmpInfo.bmiHeader.biHeight = -height; /* Top-down bitmap */
    bmpInfo.bmiHeader.biPlanes = 1;
    bmpInfo.bmiHeader.biBitCount = 32;
    bmpInfo.bmiHeader.biCompression = BI_RGB;
    HDC hdc = GetDC(NULL);
    void *pBits = NULL;
    HBITMAP hBitmap = CreateDIBSection(hdc, &bmpInfo, DIB_RGB_COLORS, &pBits, NULL, 0);
    if (!hBitmap) {
        ReleaseDC(NULL, hdc);
        SDL_DestroySurface(s);
        return NULL;
    }
    SDL_memcpy(pBits, s->pixels, width * height * 4);
    SDL_DestroySurface(s);
    HBITMAP hMask = CreateBitmap(width, height, 1, 1, NULL);
    if (!hMask) {
        DeleteObject(hBitmap);
        ReleaseDC(NULL, hdc);
        return NULL;
    }
    HDC hdcMem = CreateCompatibleDC(hdc);
    HGDIOBJ oldBitmap = SelectObject(hdcMem, hMask);
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            BYTE* pixel = (BYTE*)pBits + (y * width + x) * 4;
            BYTE alpha = pixel[3];
            COLORREF maskColor = (alpha == 0) ? RGB(0, 0, 0) : RGB(255, 255, 255);
            SetPixel(hdcMem, x, y, maskColor);
        }
    }
    ICONINFO iconInfo;
    iconInfo.fIcon = TRUE;
    iconInfo.xHotspot = 0;
    iconInfo.yHotspot = 0;
    iconInfo.hbmMask = hMask;
    iconInfo.hbmColor = hBitmap;
    HICON hIcon = CreateIconIndirect(&iconInfo);
    SelectObject(hdcMem, oldBitmap);
    DeleteDC(hdcMem);
    DeleteObject(hBitmap);
    DeleteObject(hMask);
    ReleaseDC(NULL, hdc);
    return hIcon;
}
References BI_RGB, SDL_Surface::h, NULL, SDL_Surface::pixels, RGB, SDL_ConvertSurface(), SDL_DestroySurface(), SDL_memcpy, SDL_PIXELFORMAT_ARGB8888, SDL_zero, TRUE, and SDL_Surface::w.
Referenced by SDL_CreateTray(), and SDL_SetTrayIcon().