SDL3: SDL-main/src/hidapi/SDL_hidapi.c File Reference
SDL_hidapi.c File Reference
#include "SDL_internal.h"
#include "SDL_hidapi_c.h"
#include "../joystick/usb_ids.h"
#include "../SDL_hints_c.h"
#include "hidapi/hidapi.h"
#include "../core/linux/SDL_udev.h"
Data Structures
struct hidapi_backend
struct SDL_hid_device
Macros
#define api_version PLATFORM_api_version
#define CHECK_DEVICE_MAGIC(device, result)
#define COPY_IF_EXISTS(var)
#define create_device_info_for_device PLATFORM_create_device_info_for_device
#define free_hid_device PLATFORM_free_hid_device
#define HID_API_NO_EXPORT_DEFINE
#define hid_close PLATFORM_hid_close
#define hid_device PLATFORM_hid_device
#define hid_device_ PLATFORM_hid_device_
#define hid_enumerate PLATFORM_hid_enumerate
#define hid_error PLATFORM_hid_error
#define hid_exit
#define hid_free_enumeration PLATFORM_hid_free_enumeration
#define hid_get_device_info PLATFORM_hid_get_device_info
#define hid_get_feature_report PLATFORM_hid_get_feature_report
#define hid_get_indexed_string PLATFORM_hid_get_indexed_string
#define hid_get_input_report PLATFORM_hid_get_input_report
#define hid_get_manufacturer_string PLATFORM_hid_get_manufacturer_string
#define hid_get_product_string PLATFORM_hid_get_product_string
#define hid_get_report_descriptor PLATFORM_hid_get_report_descriptor
#define hid_get_serial_number_string PLATFORM_hid_get_serial_number_string
#define hid_init
#define hid_open PLATFORM_hid_open
#define hid_open_path PLATFORM_hid_open_path
#define hid_read PLATFORM_hid_read
#define hid_read_timeout PLATFORM_hid_read_timeout
#define hid_send_feature_report PLATFORM_hid_send_feature_report
#define hid_set_nonblocking PLATFORM_hid_set_nonblocking
#define hid_version
#define hid_version_str
#define hid_write PLATFORM_hid_write
#define HIDAPI_IGNORE_DEVICE(BUS, VID, PID, USAGE_PAGE, USAGE)
#define HIDAPI_USING_SDL_RUNTIME
#define input_report PLATFORM_input_report
#define make_path PLATFORM_make_path
#define new_hid_device
#define read_thread PLATFORM_read_thread
#define return_data PLATFORM_return_data
#define SDL_HINT_HIDAPI_LIBUSB_WHITELIST_DEFAULT false
#define WCOPY_IF_EXISTS(var)
Typedefs
typedef struct PLATFORM_hid_device_ PLATFORM_hid_device
Functions
static void AddDeviceToEnumeration (const char *driver_name, struct hid_device_info *dev, struct SDL_hid_device_info **devs, struct SDL_hid_device_info **last)
static void CopyHIDDeviceInfo (struct hid_device_info *pSrc, struct SDL_hid_device_info *pDst)
static void DeleteHIDDeviceWrapper (SDL_hid_device *wrapper)
static void HIDAPI_InitializeDiscovery (void)
static void HIDAPI_ShutdownDiscovery (void)
static void HIDAPI_UpdateDiscovery (void)
static void SDLCALL IgnoredDevicesChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
static void SDLCALL OnlyControllersChanged (void *userdata, const char *name, const char *oldValue, const char *hint)
void SDL_hid_ble_scan (bool active)
int SDL_hid_close (SDL_hid_device *device)
Uint32 SDL_hid_device_change_count (void)
struct SDL_hid_device_info * SDL_hid_enumerate (unsigned short vendor_id, unsigned short product_id)
int SDL_hid_exit (void)
void SDL_hid_free_enumeration (struct SDL_hid_device_info *devs)
SDL_hid_device_info * SDL_hid_get_device_info (SDL_hid_device *device)
int SDL_hid_get_feature_report (SDL_hid_device *device, unsigned char *data, size_t length)
int SDL_hid_get_indexed_string (SDL_hid_device *device, int string_index, wchar_t *string, size_t maxlen)
int SDL_hid_get_input_report (SDL_hid_device *device, unsigned char *data, size_t length)
int SDL_hid_get_manufacturer_string (SDL_hid_device *device, wchar_t *string, size_t maxlen)
int SDL_hid_get_product_string (SDL_hid_device *device, wchar_t *string, size_t maxlen)
int SDL_hid_get_report_descriptor (SDL_hid_device *device, unsigned char *buf, size_t buf_size)
int SDL_hid_get_serial_number_string (SDL_hid_device *device, wchar_t *string, size_t maxlen)
int SDL_hid_init (void)
SDL_hid_device * SDL_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
SDL_hid_device * SDL_hid_open_path (const char *path)
int SDL_hid_read (SDL_hid_device *device, unsigned char *data, size_t length)
int SDL_hid_read_timeout (SDL_hid_device *device, unsigned char *data, size_t length, int milliseconds)
int SDL_hid_send_feature_report (SDL_hid_device *device, const unsigned char *data, size_t length)
int SDL_hid_set_nonblocking (SDL_hid_device *device, int nonblock)
int SDL_hid_write (SDL_hid_device *device, const unsigned char *data, size_t length)
bool SDL_HIDAPI_ShouldIgnoreDevice (int bus, Uint16 vendor_id, Uint16 product_id, Uint16 usage_page, Uint16 usage)
Variables
struct {
bool m_bCanGetNotifications
bool m_bInitialized
Uint32 m_unDeviceChangeCounter
Uint64 m_unLastDetect
} SDL_HIDAPI_discovery
static char * SDL_hidapi_ignored_devices = NULL
static bool SDL_hidapi_only_controllers
static int SDL_hidapi_refcount = 0
static bool use_libusb_whitelist = false
Macro Definition Documentation
api_version
#define api_version PLATFORM_api_version
Referenced by PLATFORM_hid_version().
CHECK_DEVICE_MAGIC
#define CHECK_DEVICE_MAGIC (device, result)
Value:
    if (!SDL_ObjectValid(device, SDL_OBJECT_TYPE_HIDAPI_DEVICE)) {  \
        SDL_SetError("Invalid device");                             \
        return result;                                              \
    }
#define CHECK_DEVICE_MAGIC(device, result)                          \
    if (!SDL_ObjectValid(device, SDL_OBJECT_TYPE_HIDAPI_DEVICE)) {  \
        SDL_SetError("Invalid device");                             \
        return result;                                              \
    }
Referenced by SDL_hid_close(), SDL_hid_get_device_info(), SDL_hid_get_feature_report(), SDL_hid_get_indexed_string(), SDL_hid_get_input_report(), SDL_hid_get_manufacturer_string(), SDL_hid_get_product_string(), SDL_hid_get_report_descriptor(), SDL_hid_get_serial_number_string(), SDL_hid_read(), SDL_hid_read_timeout(), SDL_hid_send_feature_report(), SDL_hid_set_nonblocking(), and SDL_hid_write().
COPY_IF_EXISTS
#define COPY_IF_EXISTS (var)
Value:
    if (pSrc->var != NULL) {               \
        pDst->var = SDL_strdup(pSrc->var); \
    } else {                               \
        pDst->var = NULL;                  \
    }
#define COPY_IF_EXISTS(var)                \
    if (pSrc->var != NULL) {               \
        pDst->var = SDL_strdup(pSrc->var); \
    } else {                               \
        pDst->var = NULL;                  \
    }
Referenced by CopyHIDDeviceInfo().
create_device_info_for_device
#define create_device_info_for_device PLATFORM_create_device_info_for_device
Referenced by create_device_info_for_hid_device(), PLATFORM_hid_enumerate(), and PLATFORM_hid_get_device_info().
free_hid_device
#define free_hid_device PLATFORM_free_hid_device
Referenced by hid_libusb_wrap_sys_device(), PLATFORM_hid_close(), and PLATFORM_hid_open_path().
HID_API_NO_EXPORT_DEFINE
#define HID_API_NO_EXPORT_DEFINE
hid_close
#define hid_close PLATFORM_hid_close
hid_device
#define hid_device PLATFORM_hid_device
hid_device_
#define hid_device_ PLATFORM_hid_device_
hid_enumerate
#define hid_enumerate PLATFORM_hid_enumerate
hid_error
#define hid_error PLATFORM_hid_error
hid_exit
#define hid_exit (void)
Value:
PLATFORM_hid_exit
hid_free_enumeration
#define hid_free_enumeration PLATFORM_hid_free_enumeration
hid_get_device_info
#define hid_get_device_info PLATFORM_hid_get_device_info
hid_get_feature_report
#define hid_get_feature_report PLATFORM_hid_get_feature_report
hid_get_indexed_string
#define hid_get_indexed_string PLATFORM_hid_get_indexed_string
hid_get_input_report
#define hid_get_input_report PLATFORM_hid_get_input_report
hid_get_manufacturer_string
#define hid_get_manufacturer_string PLATFORM_hid_get_manufacturer_string
hid_get_product_string
#define hid_get_product_string PLATFORM_hid_get_product_string
hid_get_report_descriptor
#define hid_get_report_descriptor PLATFORM_hid_get_report_descriptor
hid_get_serial_number_string
#define hid_get_serial_number_string PLATFORM_hid_get_serial_number_string
hid_init
#define hid_init (void)
Value:
PLATFORM_hid_init
hid_open
#define hid_open PLATFORM_hid_open
hid_open_path
#define hid_open_path PLATFORM_hid_open_path
hid_read
#define hid_read PLATFORM_hid_read
hid_read_timeout
#define hid_read_timeout PLATFORM_hid_read_timeout
hid_send_feature_report
#define hid_send_feature_report PLATFORM_hid_send_feature_report
hid_set_nonblocking
#define hid_set_nonblocking PLATFORM_hid_set_nonblocking
hid_version
#define hid_version (void)
Value:
PLATFORM_hid_version
hid_version_str
#define hid_version_str (void)
Value:
PLATFORM_hid_version_str
hid_write
#define hid_write PLATFORM_hid_write
HIDAPI_IGNORE_DEVICE
#define HIDAPI_IGNORE_DEVICE (BUS, VID, PID, USAGE_PAGE, USAGE)
Value:
        SDL_HIDAPI_ShouldIgnoreDevice(BUS, VID, PID, USAGE_PAGE, USAGE)
#define HIDAPI_IGNORE_DEVICE(BUS, VID, PID, USAGE_PAGE, USAGE) \
        SDL_HIDAPI_ShouldIgnoreDevice(BUS, VID, PID, USAGE_PAGE, USAGE)
Referenced by create_device_info_for_device(), create_device_info_with_usage(), and PLATFORM_hid_enumerate().
HIDAPI_USING_SDL_RUNTIME
#define HIDAPI_USING_SDL_RUNTIME
input_report
#define input_report PLATFORM_input_report
Referenced by free_hid_device(), hid_report_callback(), read_callback(), and return_data().
make_path
#define make_path PLATFORM_make_path
Referenced by create_device_info_for_device().
new_hid_device
#define new_hid_device (void)
Value:
PLATFORM_new_hid_device
read_thread
#define read_thread PLATFORM_read_thread
Referenced by hidapi_initialize_device(), and PLATFORM_hid_open_path().
return_data
#define return_data PLATFORM_return_data
Referenced by hid_report_callback(), PLATFORM_hid_close(), PLATFORM_hid_read_timeout(), and read_callback().
SDL_HINT_HIDAPI_LIBUSB_WHITELIST_DEFAULT
#define SDL_HINT_HIDAPI_LIBUSB_WHITELIST_DEFAULT false
Referenced by SDL_hid_init().
WCOPY_IF_EXISTS
#define WCOPY_IF_EXISTS (var)
Value:
    if (pSrc->var != NULL) {               \
        pDst->var = SDL_wcsdup(pSrc->var); \
    } else {                               \
        pDst->var = NULL;                  \
    }
#define WCOPY_IF_EXISTS(var)               \
    if (pSrc->var != NULL) {               \
        pDst->var = SDL_wcsdup(pSrc->var); \
    } else {                               \
        pDst->var = NULL;                  \
    }
Referenced by CopyHIDDeviceInfo().
Typedef Documentation
PLATFORM_hid_device
typedef struct PLATFORM_hid_device_ PLATFORM_hid_device
Function Documentation
AddDeviceToEnumeration()
void AddDeviceToEnumeration (const char * driver_name, struct hid_device_info * dev, struct SDL_hid_device_info ** devs, struct SDL_hid_device_info ** last) static
{
    struct SDL_hid_device_info *new_dev;
#ifdef DEBUG_HIDAPI
    SDL_Log("Adding %s device to enumeration: %ls %ls 0x%.4hx/0x%.4hx/%d",
            driver_name, dev->manufacturer_string, dev->product_string, dev->vendor_id, dev->product_id, dev->interface_number);
#else
    (void)driver_name;
#endif
    new_dev = (struct SDL_hid_device_info *)SDL_malloc(sizeof(struct SDL_hid_device_info));
    if (new_dev == NULL) {
        // Don't bother returning an error, get as many devices as possible
        return;
    }
    CopyHIDDeviceInfo(dev, new_dev);
    if ((*last) != NULL) {
        (*last)->next = new_dev;
    } else {
        *devs = new_dev;
    }
    *last = new_dev;
}
References CopyHIDDeviceInfo(), hid_device_info::interface_number, hid_device_info::manufacturer_string, NULL, hid_device_info::product_id, hid_device_info::product_string, SDL_Log(), SDL_malloc(), hid_device_info::vendor_id, and void().
Referenced by SDL_hid_enumerate().
CopyHIDDeviceInfo()
void CopyHIDDeviceInfo (struct hid_device_info * pSrc, struct SDL_hid_device_info * pDst) static
{
    COPY_IF_EXISTS(path)
    pDst->vendor_id = pSrc->vendor_id;
    pDst->product_id = pSrc->product_id;
    WCOPY_IF_EXISTS(serial_number)
    pDst->release_number = pSrc->release_number;
    WCOPY_IF_EXISTS(manufacturer_string)
    WCOPY_IF_EXISTS(product_string)
    pDst->usage_page = pSrc->usage_page;
    pDst->usage = pSrc->usage;
    pDst->interface_number = pSrc->interface_number;
    pDst->interface_class = pSrc->interface_class;
    pDst->interface_subclass = pSrc->interface_subclass;
    pDst->interface_protocol = pSrc->interface_protocol;
    pDst->bus_type = (SDL_hid_bus_type)pSrc->bus_type;
    pDst->next = NULL;
}
References hid_device_info::bus_type, SDL_hid_device_info::bus_type, COPY_IF_EXISTS, hid_device_info::interface_class, SDL_hid_device_info::interface_class, hid_device_info::interface_number, SDL_hid_device_info::interface_number, hid_device_info::interface_protocol, SDL_hid_device_info::interface_protocol, hid_device_info::interface_subclass, SDL_hid_device_info::interface_subclass, SDL_hid_device_info::next, NULL, hid_device_info::product_id, SDL_hid_device_info::product_id, hid_device_info::release_number, SDL_hid_device_info::release_number, hid_device_info::usage, SDL_hid_device_info::usage, hid_device_info::usage_page, SDL_hid_device_info::usage_page, hid_device_info::vendor_id, SDL_hid_device_info::vendor_id, and WCOPY_IF_EXISTS.
Referenced by AddDeviceToEnumeration(), and SDL_hid_get_device_info().
DeleteHIDDeviceWrapper()
void DeleteHIDDeviceWrapper (SDL_hid_device * wrapper) static
{
    SDL_SetObjectValid(wrapper, SDL_OBJECT_TYPE_HIDAPI_DEVICE, false);
    SDL_free(wrapper->info.path);
    SDL_free(wrapper->info.serial_number);
    SDL_free(wrapper->info.manufacturer_string);
    SDL_free(wrapper->info.product_string);
    SDL_free(wrapper);
}
References SDL_hid_device::info, SDL_hid_device_info::manufacturer_string, SDL_hid_device_info::path, SDL_hid_device_info::product_string, SDL_free(), SDL_OBJECT_TYPE_HIDAPI_DEVICE, SDL_SetObjectValid(), and SDL_hid_device_info::serial_number.
Referenced by SDL_hid_close().
HIDAPI_InitializeDiscovery()
void HIDAPI_InitializeDiscovery (void) static
{
    SDL_HIDAPI_discovery.m_bInitialized = true;
    SDL_HIDAPI_discovery.m_unDeviceChangeCounter = 1;
    SDL_HIDAPI_discovery.m_bCanGetNotifications = false;
    SDL_HIDAPI_discovery.m_unLastDetect = 0;
#if defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
    SDL_HIDAPI_discovery.m_nThreadID = SDL_GetCurrentThreadID();
    SDL_zero(SDL_HIDAPI_discovery.m_wndClass);
    SDL_HIDAPI_discovery.m_wndClass.hInstance = GetModuleHandle(NULL);
    SDL_HIDAPI_discovery.m_wndClass.lpszClassName = "SDL_HIDAPI_DEVICE_DETECTION";
    SDL_HIDAPI_discovery.m_wndClass.lpfnWndProc = ControllerWndProc; // This function is called by windows
    SDL_HIDAPI_discovery.m_wndClass.cbSize = sizeof(WNDCLASSEX);
    RegisterClassExA(&SDL_HIDAPI_discovery.m_wndClass);
    SDL_HIDAPI_discovery.m_hwndMsg = CreateWindowExA(0, "SDL_HIDAPI_DEVICE_DETECTION", NULL, 0, 0, 0, 0, 0, HWND_MESSAGE, NULL, NULL, NULL);
    {
        DEV_BROADCAST_DEVICEINTERFACE_A devBroadcast;
        SDL_zero(devBroadcast);
        devBroadcast.dbcc_size = sizeof(devBroadcast);
        devBroadcast.dbcc_devicetype = DBT_DEVTYP_DEVICEINTERFACE;
        devBroadcast.dbcc_classguid = GUID_DEVINTERFACE_USB_DEVICE;
        /* DEVICE_NOTIFY_ALL_INTERFACE_CLASSES is important, makes GUID_DEVINTERFACE_USB_DEVICE ignored,
         * but that seems to be necessary to get a notice after each individual usb input device actually
         * installs, rather than just as the composite device is seen.
         */
        SDL_HIDAPI_discovery.m_hNotify = RegisterDeviceNotification(SDL_HIDAPI_discovery.m_hwndMsg, &devBroadcast, DEVICE_NOTIFY_WINDOW_HANDLE | DEVICE_NOTIFY_ALL_INTERFACE_CLASSES);
        SDL_HIDAPI_discovery.m_bCanGetNotifications = (SDL_HIDAPI_discovery.m_hNotify != 0);
    }
#endif // defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
#ifdef SDL_PLATFORM_MACOS
    SDL_HIDAPI_discovery.m_notificationPort = IONotificationPortCreate(kIOMainPortDefault);
    if (SDL_HIDAPI_discovery.m_notificationPort) {
        {
            io_iterator_t portIterator = 0;
            io_object_t entry;
            IOReturn result = IOServiceAddMatchingNotification(
                SDL_HIDAPI_discovery.m_notificationPort,
                kIOFirstMatchNotification,
                IOServiceMatching(kIOHIDDeviceKey),
                CallbackIOServiceFunc, NULL, &portIterator);
            if (result == 0) {
                // Must drain the existing iterator, or we won't receive new notifications
                while ((entry = IOIteratorNext(portIterator)) != 0) {
                    IOObjectRelease(entry);
                }
            } else {
                IONotificationPortDestroy(SDL_HIDAPI_discovery.m_notificationPort);
                SDL_HIDAPI_discovery.m_notificationPort = nil;
            }
        }
        {
            io_iterator_t portIterator = 0;
            io_object_t entry;
            IOReturn result = IOServiceAddMatchingNotification(
                SDL_HIDAPI_discovery.m_notificationPort,
                kIOTerminatedNotification,
                IOServiceMatching(kIOHIDDeviceKey),
                CallbackIOServiceFunc, NULL, &portIterator);
            if (result == 0) {
                // Must drain the existing iterator, or we won't receive new notifications
                while ((entry = IOIteratorNext(portIterator)) != 0) {
                    IOObjectRelease(entry);
                }
            } else {
                IONotificationPortDestroy(SDL_HIDAPI_discovery.m_notificationPort);
                SDL_HIDAPI_discovery.m_notificationPort = nil;
            }
        }
    }
    SDL_HIDAPI_discovery.m_notificationMach = MACH_PORT_NULL;
    if (SDL_HIDAPI_discovery.m_notificationPort) {
        SDL_HIDAPI_discovery.m_notificationMach = IONotificationPortGetMachPort(SDL_HIDAPI_discovery.m_notificationPort);
    }
    SDL_HIDAPI_discovery.m_bCanGetNotifications = (SDL_HIDAPI_discovery.m_notificationMach != MACH_PORT_NULL);
#endif // SDL_PLATFORM_MACOS
#ifdef SDL_USE_LIBUDEV
    if (linux_enumeration_method == ENUMERATION_LIBUDEV) {
        SDL_HIDAPI_discovery.m_pUdev = NULL;
        SDL_HIDAPI_discovery.m_pUdevMonitor = NULL;
        SDL_HIDAPI_discovery.m_nUdevFd = -1;
        usyms = SDL_UDEV_GetUdevSyms();
        if (usyms != NULL) {
            SDL_HIDAPI_discovery.m_pUdev = usyms->udev_new();
            if (SDL_HIDAPI_discovery.m_pUdev != NULL) {
                SDL_HIDAPI_discovery.m_pUdevMonitor = usyms->udev_monitor_new_from_netlink(SDL_HIDAPI_discovery.m_pUdev, "udev");
                if (SDL_HIDAPI_discovery.m_pUdevMonitor != NULL) {
                    usyms->udev_monitor_enable_receiving(SDL_HIDAPI_discovery.m_pUdevMonitor);
                    SDL_HIDAPI_discovery.m_nUdevFd = usyms->udev_monitor_get_fd(SDL_HIDAPI_discovery.m_pUdevMonitor);
                    SDL_HIDAPI_discovery.m_bCanGetNotifications = true;
                }
            }
        }
    } else
#endif // SDL_USE_LIBUDEV
    {
#ifdef HAVE_INOTIFY
        inotify_fd = SDL_inotify_init1();
        if (inotify_fd < 0) {
            SDL_LogWarn(SDL_LOG_CATEGORY_INPUT,
                        "Unable to initialize inotify, falling back to polling: %s",
                        strerror(errno));
            return;
        }
        /* We need to watch for attribute changes in addition to
         * creation, because when a device is first created, it has
         * permissions that we can't read. When udev chmods it to
         * something that we maybe *can* read, we'll get an
         * IN_ATTRIB event to tell us. */
        if (inotify_add_watch(inotify_fd, "/dev",
                              IN_CREATE | IN_DELETE | IN_MOVE | IN_ATTRIB) < 0) {
            close(inotify_fd);
            inotify_fd = -1;
            SDL_LogWarn(SDL_LOG_CATEGORY_INPUT,
                        "Unable to add inotify watch, falling back to polling: %s",
                        strerror(errno));
            return;
        }
        SDL_HIDAPI_discovery.m_bCanGetNotifications = true;
#endif // HAVE_INOTIFY
    }
}
References kIOMainPortDefault, NULL, SDL_GetCurrentThreadID(), SDL_HIDAPI_discovery, SDL_LOG_CATEGORY_INPUT, SDL_LogWarn(), and SDL_zero.
Referenced by HIDAPI_UpdateDiscovery().
HIDAPI_ShutdownDiscovery()
void HIDAPI_ShutdownDiscovery (void) static
{
    if (!SDL_HIDAPI_discovery.m_bInitialized) {
        return;
    }
#if defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
    if (SDL_HIDAPI_discovery.m_hNotify) {
        UnregisterDeviceNotification(SDL_HIDAPI_discovery.m_hNotify);
    }
    if (SDL_HIDAPI_discovery.m_hwndMsg) {
        DestroyWindow(SDL_HIDAPI_discovery.m_hwndMsg);
    }
    UnregisterClassA(SDL_HIDAPI_discovery.m_wndClass.lpszClassName, SDL_HIDAPI_discovery.m_wndClass.hInstance);
#endif
#ifdef SDL_PLATFORM_MACOS
    if (SDL_HIDAPI_discovery.m_notificationPort) {
        IONotificationPortDestroy(SDL_HIDAPI_discovery.m_notificationPort);
    }
#endif
#ifdef SDL_USE_LIBUDEV
    if (linux_enumeration_method == ENUMERATION_LIBUDEV) {
        if (usyms) {
            if (SDL_HIDAPI_discovery.m_pUdevMonitor) {
                usyms->udev_monitor_unref(SDL_HIDAPI_discovery.m_pUdevMonitor);
            }
            if (SDL_HIDAPI_discovery.m_pUdev) {
                usyms->udev_unref(SDL_HIDAPI_discovery.m_pUdev);
            }
            SDL_UDEV_ReleaseUdevSyms();
            usyms = NULL;
        }
    } else
#endif // SDL_USE_LIBUDEV
    {
#ifdef HAVE_INOTIFY
        if (inotify_fd >= 0) {
            close(inotify_fd);
            inotify_fd = -1;
        }
#endif
    }
    SDL_HIDAPI_discovery.m_bInitialized = false;
}
References NULL, and SDL_HIDAPI_discovery.
Referenced by SDL_hid_exit().
HIDAPI_UpdateDiscovery()
void HIDAPI_UpdateDiscovery (void) static
{
    if (!SDL_HIDAPI_discovery.m_bInitialized) {
        HIDAPI_InitializeDiscovery();
    }
    if (!SDL_HIDAPI_discovery.m_bCanGetNotifications) {
        const Uint32 SDL_HIDAPI_DETECT_INTERVAL_MS = 3000; // Update every 3 seconds
        Uint64 now = SDL_GetTicks();
        if (!SDL_HIDAPI_discovery.m_unLastDetect || now >= (SDL_HIDAPI_discovery.m_unLastDetect + SDL_HIDAPI_DETECT_INTERVAL_MS)) {
            ++SDL_HIDAPI_discovery.m_unDeviceChangeCounter;
            SDL_HIDAPI_discovery.m_unLastDetect = now;
        }
        return;
    }
#if defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
#if 0 // just let the usual SDL_PumpEvents loop dispatch these, fixing bug 4286. --ryan.
    // We'll only get messages on the same thread that created the window
    if (SDL_GetCurrentThreadID() == SDL_HIDAPI_discovery.m_nThreadID) {
        MSG msg;
        while (PeekMessage(&msg, SDL_HIDAPI_discovery.m_hwndMsg, 0, 0, PM_NOREMOVE)) {
            if (GetMessageA(&msg, SDL_HIDAPI_discovery.m_hwndMsg, 0, 0) != 0) {
                TranslateMessage(&msg);
                DispatchMessage(&msg);
            }
        }
    }
#endif
#endif // defined(SDL_PLATFORM_WIN32) || defined(SDL_PLATFORM_WINGDK)
#ifdef SDL_PLATFORM_MACOS
    if (SDL_HIDAPI_discovery.m_notificationPort) {
        struct
        {
            mach_msg_header_t hdr;
            char payload[4096];
        } msg;
        while (mach_msg(&msg.hdr, MACH_RCV_MSG | MACH_RCV_TIMEOUT, 0, sizeof(msg), SDL_HIDAPI_discovery.m_notificationMach, 0, MACH_PORT_NULL) == KERN_SUCCESS) {
            IODispatchCalloutFromMessage(NULL, &msg.hdr, SDL_HIDAPI_discovery.m_notificationPort);
        }
    }
#endif
#ifdef SDL_USE_LIBUDEV
    if (linux_enumeration_method == ENUMERATION_LIBUDEV) {
        if (SDL_HIDAPI_discovery.m_nUdevFd >= 0) {
            /* Drain all notification events.
             * We don't expect a lot of device notifications so just
             * do a new discovery on any kind or number of notifications.
             * This could be made more restrictive if necessary.
             */
            for (;;) {
                struct pollfd PollUdev;
                struct udev_device *pUdevDevice;
                PollUdev.fd = SDL_HIDAPI_discovery.m_nUdevFd;
                PollUdev.events = POLLIN;
                if (poll(&PollUdev, 1, 0) != 1) {
                    break;
                }
                pUdevDevice = usyms->udev_monitor_receive_device(SDL_HIDAPI_discovery.m_pUdevMonitor);
                if (pUdevDevice) {
                    const char *action = NULL;
                    action = usyms->udev_device_get_action(pUdevDevice);
                    if (action == NULL || SDL_strcmp(action, "add") == 0 || SDL_strcmp(action, "remove") == 0) {
                        ++SDL_HIDAPI_discovery.m_unDeviceChangeCounter;
                    }
                    usyms->udev_device_unref(pUdevDevice);
                }
            }
        }
    } else
#endif // SDL_USE_LIBUDEV
    {
#ifdef HAVE_INOTIFY
        if (inotify_fd >= 0) {
            union
            {
                struct inotify_event event;
                char storage[4096];
                char enough_for_inotify[sizeof(struct inotify_event) + NAME_MAX + 1];
            } buf;
            ssize_t bytes;
            size_t remain = 0;
            size_t len;
            bytes = read(inotify_fd, &buf, sizeof(buf));
            if (bytes > 0) {
                remain = (size_t)bytes;
            }
            while (remain > 0) {
                if (buf.event.len > 0) {
                    if (StrHasPrefix(buf.event.name, "hidraw") &&
                        StrIsInteger(buf.event.name + SDL_strlen("hidraw"))) {
                        ++SDL_HIDAPI_discovery.m_unDeviceChangeCounter;
                        /* We found an hidraw change. We still continue to
                         * drain the inotify fd to avoid leaving old
                         * notifications in the queue. */
                    }
                }
                len = sizeof(struct inotify_event) + buf.event.len;
                remain -= len;
                if (remain != 0) {
                    SDL_memmove(&buf.storage[0], &buf.storage[len], remain);
                }
            }
        }
#endif // HAVE_INOTIFY
    }
}
References HIDAPI_InitializeDiscovery(), NULL, SDL_GetCurrentThreadID(), SDL_GetTicks(), SDL_HIDAPI_discovery, SDL_memmove, SDL_strcmp(), and SDL_strlen().
Referenced by SDL_hid_device_change_count().
IgnoredDevicesChanged()
void SDLCALL IgnoredDevicesChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    if (SDL_hidapi_ignored_devices) {
        SDL_free(SDL_hidapi_ignored_devices);
    }
    if (hint && *hint) {
        SDL_hidapi_ignored_devices = SDL_strdup(hint);
    } else {
        SDL_hidapi_ignored_devices = NULL;
    }
}
References NULL, SDL_free(), SDL_hidapi_ignored_devices, SDL_strdup(), and SDLCALL.
Referenced by SDL_hid_exit(), and SDL_hid_init().
OnlyControllersChanged()
void SDLCALL OnlyControllersChanged (void * userdata, const char * name, const char * oldValue, const char * hint) static
{
    SDL_hidapi_only_controllers = SDL_GetStringBoolean(hint, true);
}
References SDL_GetStringBoolean(), SDL_hidapi_only_controllers, and SDLCALL.
Referenced by SDL_hid_exit(), and SDL_hid_init().
SDL_hid_ble_scan()
void SDL_hid_ble_scan (bool active)
Start or stop a BLE scan on iOS and tvOS to pair Steam Controllers.
Parameters
active true to start the scan, false to stop the scan.
Since
This function is available since SDL 3.2.0.
{
#if !defined(SDL_HIDAPI_DISABLED) && (defined(SDL_PLATFORM_IOS) || defined(SDL_PLATFORM_TVOS))
    extern void hid_ble_scan(int bStart);
    hid_ble_scan(active);
#endif
}
References active.
SDL_hid_close()
int SDL_hid_close (SDL_hid_device * dev)
Close a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    device->backend->hid_close(device->device);
    DeleteHIDDeviceWrapper(device);
    return 0;
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, DeleteHIDDeviceWrapper(), SDL_hid_device::device, and hidapi_backend::hid_close.
SDL_hid_device_change_count()
Uint32 SDL_hid_device_change_count (void)
Check to see if devices may have been added or removed.
Enumerating the HID devices is an expensive operation, so you can call this to see if there have been any system device changes since the last call to this function. A change in the counter returned doesn't necessarily mean that anything has changed, but you can call SDL_hid_enumerate() to get an updated device list.
Calling this function for the first time may cause a thread or other system resource to be allocated to track device change notifications.
Returns
a change counter that is incremented with each potential device change, or 0 if device change detection isn't available.
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_enumerate
{
    Uint32 counter = 0;
#ifndef SDL_HIDAPI_DISABLED
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return 0;
    }
    HIDAPI_UpdateDiscovery();
    if (SDL_HIDAPI_discovery.m_unDeviceChangeCounter == 0) {
        // Counter wrapped!
        ++SDL_HIDAPI_discovery.m_unDeviceChangeCounter;
    }
    counter = SDL_HIDAPI_discovery.m_unDeviceChangeCounter;
#endif // !SDL_HIDAPI_DISABLED
    return counter;
}
References HIDAPI_UpdateDiscovery(), SDL_hid_init(), SDL_HIDAPI_discovery, and SDL_hidapi_refcount.
SDL_hid_enumerate()
struct SDL_hid_device_info * SDL_hid_enumerate (unsigned short vendor_id, unsigned short product_id)
Enumerate the HID Devices.
This function returns a linked list of all the HID devices attached to the system which match vendor_id and product_id. If vendor_id is set to 0 then any vendor matches. If product_id is set to 0 then any product matches. If vendor_id and product_id are both set to 0, then all HID devices will be returned.
By default SDL will only enumerate controllers, to reduce risk of hanging or crashing on bad drivers, but SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS can be set to "0" to enumerate all HID devices.
Parameters
vendor_id the Vendor ID (VID) of the types of device to open, or 0 to match any vendor.
product_id the Product ID (PID) of the types of device to open, or 0 to match any product.
Returns
a pointer to a linked list of type SDL_hid_device_info, containing information about the HID devices attached to the system, or NULL in the case of failure. Free this linked list by calling SDL_hid_free_enumeration().
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_device_change_count
{
    struct hid_device_info *driver_devs = NULL;
    struct hid_device_info *usb_devs = NULL;
    struct hid_device_info *raw_devs = NULL;
    struct hid_device_info *dev;
    struct SDL_hid_device_info *devs = NULL, *last = NULL;
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return NULL;
    }
    // Collect the available devices
#ifdef HAVE_DRIVER_BACKEND
    driver_devs = DRIVER_hid_enumerate(vendor_id, product_id);
#endif
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle) {
        usb_devs = LIBUSB_hid_enumerate(vendor_id, product_id);
        if (use_libusb_whitelist) {
            RemoveNonWhitelistedDevicesFromEnumeration(&usb_devs,  LIBUSB_hid_free_enumeration);
        }
    }
#endif // HAVE_LIBUSB
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        raw_devs = PLATFORM_hid_enumerate(vendor_id, product_id);
    }
#endif
    // Highest priority are custom driver devices
    for (dev = driver_devs; dev; dev = dev->next) {
        AddDeviceToEnumeration("driver", dev, &devs, &last);
#ifdef HAVE_LIBUSB
        RemoveDeviceFromEnumeration("libusb", dev, &usb_devs, LIBUSB_hid_free_enumeration);
#endif
#ifdef HAVE_PLATFORM_BACKEND
        RemoveDeviceFromEnumeration("raw", dev, &raw_devs, PLATFORM_hid_free_enumeration);
#endif
    }
    // If whitelist is in effect, libusb has priority, otherwise raw devices do
    if (use_libusb_whitelist) {
        for (dev = usb_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("libusb", dev, &devs, &last);
#ifdef HAVE_PLATFORM_BACKEND
            RemoveDeviceFromEnumeration("raw", dev, &raw_devs, PLATFORM_hid_free_enumeration);
#endif
        }
        for (dev = raw_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("platform", dev, &devs, &last);
        }
    } else {
        for (dev = raw_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("raw", dev, &devs, &last);
#ifdef HAVE_LIBUSB
            RemoveDeviceFromEnumeration("libusb", dev, &usb_devs, LIBUSB_hid_free_enumeration);
#endif
        }
        for (dev = usb_devs; dev; dev = dev->next) {
            AddDeviceToEnumeration("libusb", dev, &devs, &last);
        }
    }
#ifdef HAVE_DRIVER_BACKEND
    DRIVER_hid_free_enumeration(driver_devs);
#endif
#ifdef HAVE_LIBUSB
    LIBUSB_hid_free_enumeration(usb_devs);
#endif
#ifdef HAVE_PLATFORM_BACKEND
    PLATFORM_hid_free_enumeration(raw_devs);
#endif
    return devs;
}
References AddDeviceToEnumeration(), hid_device_info::next, NULL, PLATFORM_hid_enumerate(), PLATFORM_hid_free_enumeration(), SDL_hid_device_info::product_id, SDL_hid_init(), SDL_hidapi_refcount, udev_ctx, use_libusb_whitelist, and SDL_hid_device_info::vendor_id.
SDL_hid_exit()
int SDL_hid_exit (void)
Finalize the HIDAPI library.
This function frees all of the static data associated with HIDAPI. It should be called at the end of execution to avoid memory leaks.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_init
{
    int result = 0;
    if (SDL_hidapi_refcount == 0) {
        return 0;
    }
    --SDL_hidapi_refcount;
    if (SDL_hidapi_refcount > 0) {
        return 0;
    }
    SDL_hidapi_refcount = 0;
#ifndef SDL_HIDAPI_DISABLED
    HIDAPI_ShutdownDiscovery();
#endif
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        result |= PLATFORM_hid_exit();
    }
#ifdef SDL_PLATFORM_LINUX
    SDL_UDEV_ReleaseUdevSyms();
#endif // __LINUX __
#endif // HAVE_PLATFORM_BACKEND
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle) {
        result |= LIBUSB_hid_exit();
#ifdef SDL_LIBUSB_DYNAMIC
        SDL_UnloadObject(libusb_ctx.libhandle);
#endif
        libusb_ctx.libhandle = NULL;
    }
#endif // HAVE_LIBUSB
    SDL_RemoveHintCallback(SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, OnlyControllersChanged, NULL);
    SDL_RemoveHintCallback(SDL_HINT_HIDAPI_IGNORE_DEVICES, IgnoredDevicesChanged, NULL);
    if (SDL_hidapi_ignored_devices) {
        SDL_free(SDL_hidapi_ignored_devices);
        SDL_hidapi_ignored_devices = NULL;
    }
    return result;
}
References HIDAPI_ShutdownDiscovery(), IgnoredDevicesChanged(), NULL, OnlyControllersChanged(), PLATFORM_hid_exit(), SDL_free(), SDL_hidapi_ignored_devices, SDL_hidapi_refcount, SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, SDL_HINT_HIDAPI_IGNORE_DEVICES, SDL_RemoveHintCallback(), SDL_UnloadObject(), and udev_ctx.
SDL_hid_free_enumeration()
void SDL_hid_free_enumeration (SDL_hid_device_info * devs)
Free an enumeration linked list.
This function frees a linked list created by SDL_hid_enumerate().
Parameters
devs pointer to a list of struct_device returned from SDL_hid_enumerate().
Since
This function is available since SDL 3.2.0.
{
    while (devs) {
        struct SDL_hid_device_info *next = devs->next;
        SDL_free(devs->path);
        SDL_free(devs->serial_number);
        SDL_free(devs->manufacturer_string);
        SDL_free(devs->product_string);
        SDL_free(devs);
        devs = next;
    }
}
References SDL_hid_device_info::manufacturer_string, SDL_hid_device_info::next, SDL_hid_device_info::path, SDL_hid_device_info::product_string, SDL_free(), and SDL_hid_device_info::serial_number.
SDL_hid_get_device_info()
SDL_hid_device_info * SDL_hid_get_device_info (SDL_hid_device * dev)
Get the device info from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
Returns
a pointer to the SDL_hid_device_info for this hid_device or NULL on failure; call SDL_GetError() for more information. This struct is valid until the device is closed with SDL_hid_close().
Since
This function is available since SDL 3.2.0.
{
    struct hid_device_info *info;
    CHECK_DEVICE_MAGIC(device, NULL);
    info = device->backend->hid_get_device_info(device->device);
    if (info) {
        CopyHIDDeviceInfo(info, &device->info);
        return &device->info;
    } else {
        return NULL;
    }
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, CopyHIDDeviceInfo(), SDL_hid_device::device, hidapi_backend::hid_get_device_info, SDL_hid_device::info, and NULL.
SDL_hid_get_feature_report()
int SDL_hid_get_feature_report (SDL_hid_device * dev, unsigned char * data, size_t length)
Get a feature report from a HID device.
Set the first byte of data to the Report ID of the report to be read. Make sure to allow space for this extra byte in data. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into, including the Report ID. Set the first byte of data to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length the number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_feature_report(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_feature_report.
SDL_hid_get_indexed_string()
int SDL_hid_get_indexed_string (SDL_hid_device * dev, int string_index, wchar_t * string, size_t maxlen)
Get a string from a HID device, based on its string index.
Parameters
dev a device handle returned from SDL_hid_open().
string_index the index of the string to get.
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_indexed_string(device->device, string_index, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_indexed_string.
SDL_hid_get_input_report()
int SDL_hid_get_input_report (SDL_hid_device * dev, unsigned char * data, size_t length)
Get an input report from a HID device.
Set the first byte of data to the Report ID of the report to be read. Make sure to allow space for this extra byte in data. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into, including the Report ID. Set the first byte of data to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length the number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_input_report(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_input_report.
SDL_hid_get_manufacturer_string()
int SDL_hid_get_manufacturer_string (SDL_hid_device * dev, wchar_t * string, size_t maxlen)
Get The Manufacturer String from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_manufacturer_string(device->device, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_manufacturer_string.
SDL_hid_get_product_string()
int SDL_hid_get_product_string (SDL_hid_device * dev, wchar_t * string, size_t maxlen)
Get The Product String from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_product_string(device->device, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_product_string.
SDL_hid_get_report_descriptor()
int SDL_hid_get_report_descriptor (SDL_hid_device * dev, unsigned char * buf, size_t buf_size)
Get a report descriptor from a HID device.
User has to provide a preallocated buffer where descriptor will be copied to. The recommended size for a preallocated buffer is 4096 bytes.
Parameters
dev a device handle returned from SDL_hid_open().
buf the buffer to copy descriptor into.
buf_size the size of the buffer in bytes.
Returns
the number of bytes actually copied or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_report_descriptor(device->device, buf, buf_size);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_report_descriptor.
SDL_hid_get_serial_number_string()
int SDL_hid_get_serial_number_string (SDL_hid_device * dev, wchar_t * string, size_t maxlen)
Get The Serial Number String from a HID device.
Parameters
dev a device handle returned from SDL_hid_open().
string a wide string buffer to put the data into.
maxlen the length of the buffer in multiples of wchar_t.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_get_serial_number_string(device->device, string, maxlen);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_get_serial_number_string.
SDL_hid_init()
int SDL_hid_init (void)
Initialize the HIDAPI library.
This function initializes the HIDAPI library. Calling it is not strictly necessary, as it will be called automatically by SDL_hid_enumerate() and any of the SDL_hid_open_*() functions if it is needed. This function should be called at the beginning of execution however, if there is a chance of HIDAPI handles being opened by different threads simultaneously.
Each call to this function should have a matching call to SDL_hid_exit()
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_hid_exit
{
    int attempts = 0, success = 0;
    if (SDL_hidapi_refcount > 0) {
        ++SDL_hidapi_refcount;
        return 0;
    }
    SDL_AddHintCallback(SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, OnlyControllersChanged, NULL);
    SDL_AddHintCallback(SDL_HINT_HIDAPI_IGNORE_DEVICES, IgnoredDevicesChanged, NULL);
#ifdef SDL_USE_LIBUDEV
    if (!SDL_GetHintBoolean(SDL_HINT_HIDAPI_UDEV, true)) {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "udev disabled by SDL_HINT_HIDAPI_UDEV");
        linux_enumeration_method = ENUMERATION_FALLBACK;
    } else if (SDL_GetSandbox() != SDL_SANDBOX_NONE) {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "Container detected, disabling HIDAPI udev integration");
        linux_enumeration_method = ENUMERATION_FALLBACK;
    } else {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "Using udev for HIDAPI joystick device discovery");
        linux_enumeration_method = ENUMERATION_LIBUDEV;
    }
#endif
    use_libusb_whitelist = SDL_GetHintBoolean(SDL_HINT_HIDAPI_LIBUSB_WHITELIST,
                                              SDL_HINT_HIDAPI_LIBUSB_WHITELIST_DEFAULT);
#ifdef HAVE_LIBUSB
    if (!SDL_GetHintBoolean(SDL_HINT_HIDAPI_LIBUSB, true)) {
        SDL_LogDebug(SDL_LOG_CATEGORY_INPUT,
                     "libusb disabled with SDL_HINT_HIDAPI_LIBUSB");
        libusb_ctx.libhandle = NULL;
    } else {
        ++attempts;
#ifdef SDL_LIBUSB_DYNAMIC
        libusb_ctx.libhandle = SDL_LoadObject(SDL_LIBUSB_DYNAMIC);
#else
        libusb_ctx.libhandle = (void *)1;
#endif
        if (libusb_ctx.libhandle != NULL) {
            bool loaded = true;
#ifdef SDL_LIBUSB_DYNAMIC
#define LOAD_LIBUSB_SYMBOL(type, func)                                                                  \
    if ((libusb_ctx.func = (type)SDL_LoadFunction(libusb_ctx.libhandle, "libusb_" #func)) == NULL) {    \
        loaded = false;                                                                                 \
    }
#else
#define LOAD_LIBUSB_SYMBOL(type, func) \
    libusb_ctx.func = libusb_##func;
#endif
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_context **), init)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(libusb_context *), exit)
            LOAD_LIBUSB_SYMBOL(ssize_t (LIBUSB_CALL *)(libusb_context *, libusb_device ***), get_device_list)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(libusb_device **, int), free_device_list)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, struct libusb_device_descriptor *), get_device_descriptor)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, struct libusb_config_descriptor **), get_active_config_descriptor)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, uint8_t, struct libusb_config_descriptor **), get_config_descriptor)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(struct libusb_config_descriptor *), free_config_descriptor)
            LOAD_LIBUSB_SYMBOL(uint8_t (LIBUSB_CALL *)(libusb_device *), get_bus_number)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *dev, uint8_t *port_numbers, int port_numbers_len), get_port_numbers)
            LOAD_LIBUSB_SYMBOL(uint8_t (LIBUSB_CALL *)(libusb_device *), get_device_address)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device *, libusb_device_handle **), open)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(libusb_device_handle *), close)
            LOAD_LIBUSB_SYMBOL(libusb_device * (LIBUSB_CALL *)(libusb_device_handle *dev_handle), get_device)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), claim_interface)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), release_interface)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), kernel_driver_active)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), detach_kernel_driver)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int), attach_kernel_driver)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, int, int), set_interface_alt_setting)
            LOAD_LIBUSB_SYMBOL(struct libusb_transfer * (LIBUSB_CALL *)(int), alloc_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(struct libusb_transfer *), submit_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(struct libusb_transfer *), cancel_transfer)
            LOAD_LIBUSB_SYMBOL(void (LIBUSB_CALL *)(struct libusb_transfer *), free_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, uint8_t, uint8_t, uint16_t, uint16_t, unsigned char *, uint16_t, unsigned int), control_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_device_handle *, unsigned char, unsigned char *, int, int *, unsigned int), interrupt_transfer)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_context *), handle_events)
            LOAD_LIBUSB_SYMBOL(int (LIBUSB_CALL *)(libusb_context *, int *), handle_events_completed)
            LOAD_LIBUSB_SYMBOL(const char * (LIBUSB_CALL *)(int), error_name)
#undef LOAD_LIBUSB_SYMBOL
            if (!loaded) {
#ifdef SDL_LIBUSB_DYNAMIC
                SDL_UnloadObject(libusb_ctx.libhandle);
#endif
                libusb_ctx.libhandle = NULL;
                // SDL_LogWarn(SDL_LOG_CATEGORY_INPUT, SDL_LIBUSB_DYNAMIC " found but could not load function");
            } else if (LIBUSB_hid_init() < 0) {
#ifdef SDL_LIBUSB_DYNAMIC
                SDL_UnloadObject(libusb_ctx.libhandle);
#endif
                libusb_ctx.libhandle = NULL;
            } else {
                ++success;
            }
        }
    }
#endif // HAVE_LIBUSB
#ifdef HAVE_PLATFORM_BACKEND
    ++attempts;
#ifdef SDL_PLATFORM_LINUX
    udev_ctx = SDL_UDEV_GetUdevSyms();
#endif // __LINUX __
    if (udev_ctx && PLATFORM_hid_init() == 0) {
        ++success;
    }
#endif // HAVE_PLATFORM_BACKEND
    if (attempts > 0 && success == 0) {
        return -1;
    }
#if defined(SDL_PLATFORM_MACOS) && !defined(SDL_HIDAPI_DISABLED)
    hid_darwin_set_open_exclusive(0);
#endif
    ++SDL_hidapi_refcount;
    return 0;
}
References hid_darwin_set_open_exclusive(), IgnoredDevicesChanged(), NULL, OnlyControllersChanged(), PLATFORM_hid_init(), SDL_AddHintCallback(), SDL_GetHintBoolean(), SDL_GetSandbox(), SDL_hidapi_refcount, SDL_HINT_HIDAPI_ENUMERATE_ONLY_CONTROLLERS, SDL_HINT_HIDAPI_IGNORE_DEVICES, SDL_HINT_HIDAPI_LIBUSB, SDL_HINT_HIDAPI_LIBUSB_WHITELIST, SDL_HINT_HIDAPI_LIBUSB_WHITELIST_DEFAULT, SDL_HINT_HIDAPI_UDEV, SDL_LoadObject(), SDL_LOG_CATEGORY_INPUT, SDL_LogDebug(), SDL_SANDBOX_NONE, SDL_UnloadObject(), udev_ctx, and use_libusb_whitelist.
Referenced by SDL_hid_device_change_count(), SDL_hid_enumerate(), SDL_hid_open(), and SDL_hid_open_path().
SDL_hid_open()
SDL_hid_device * SDL_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
If serial_number is NULL, the first device with the specified VID and PID is opened.
Parameters
vendor_id the Vendor ID (VID) of the device to open.
product_id the Product ID (PID) of the device to open.
serial_number the Serial Number of the device to open (Optionally NULL).
Returns
a pointer to a SDL_hid_device object on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
#if defined(HAVE_PLATFORM_BACKEND) || defined(HAVE_DRIVER_BACKEND) || defined(HAVE_LIBUSB)
    void *pDevice = NULL;
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return NULL;
    }
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        pDevice = PLATFORM_hid_open(vendor_id, product_id, serial_number);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &PLATFORM_Backend);
        }
    }
#endif // HAVE_PLATFORM_BACKEND
#ifdef HAVE_DRIVER_BACKEND
    pDevice = DRIVER_hid_open(vendor_id, product_id, serial_number);
    if (pDevice != NULL) {
        return CreateHIDDeviceWrapper(pDevice, &DRIVER_Backend);
    }
#endif // HAVE_DRIVER_BACKEND
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle != NULL) {
        pDevice = LIBUSB_hid_open(vendor_id, product_id, serial_number);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &LIBUSB_Backend);
        }
    }
#endif // HAVE_LIBUSB
#endif // HAVE_PLATFORM_BACKEND || HAVE_DRIVER_BACKEND || HAVE_LIBUSB
    return NULL;
}
References NULL, PLATFORM_hid_open(), SDL_hid_device_info::product_id, SDL_hid_init(), SDL_hidapi_refcount, SDL_hid_device_info::serial_number, udev_ctx, and SDL_hid_device_info::vendor_id.
SDL_hid_open_path()
SDL_hid_device * SDL_hid_open_path (const char * path)
Open a HID device by its path name.
The path name be determined by calling SDL_hid_enumerate(), or a platform-specific path name can be used (eg: /dev/hidraw0 on Linux).
Parameters
path the path name of the device to open.
Returns
a pointer to a SDL_hid_device object on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
#if defined(HAVE_PLATFORM_BACKEND) || defined(HAVE_DRIVER_BACKEND) || defined(HAVE_LIBUSB)
    void *pDevice = NULL;
    if (SDL_hidapi_refcount == 0 && SDL_hid_init() < 0) {
        return NULL;
    }
#ifdef HAVE_PLATFORM_BACKEND
    if (udev_ctx) {
        pDevice = PLATFORM_hid_open_path(path);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &PLATFORM_Backend);
        }
    }
#endif // HAVE_PLATFORM_BACKEND
#ifdef HAVE_DRIVER_BACKEND
    pDevice = DRIVER_hid_open_path(path);
    if (pDevice != NULL) {
        return CreateHIDDeviceWrapper(pDevice, &DRIVER_Backend);
    }
#endif // HAVE_DRIVER_BACKEND
#ifdef HAVE_LIBUSB
    if (libusb_ctx.libhandle != NULL) {
        pDevice = LIBUSB_hid_open_path(path);
        if (pDevice != NULL) {
            return CreateHIDDeviceWrapper(pDevice, &LIBUSB_Backend);
        }
    }
#endif // HAVE_LIBUSB
#endif // HAVE_PLATFORM_BACKEND || HAVE_DRIVER_BACKEND || HAVE_LIBUSB
    return NULL;
}
References NULL, SDL_hid_device_info::path, PLATFORM_hid_open_path(), SDL_hid_init(), SDL_hidapi_refcount, and udev_ctx.
SDL_hid_read()
int SDL_hid_read (SDL_hid_device * dev, unsigned char * data, size_t length)
Read an Input report from a HID device.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into.
length the number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
Returns
the actual number of bytes read and -1 on failure; call SDL_GetError() for more information. If no packet was available to be read and the handle is in non-blocking mode, this function returns 0.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_read(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_read.
SDL_hid_read_timeout()
int SDL_hid_read_timeout (SDL_hid_device * dev, unsigned char * data, size_t length, int milliseconds)
Read an Input report from a HID device with timeout.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev a device handle returned from SDL_hid_open().
data a buffer to put the read data into.
length the number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
milliseconds timeout in milliseconds or -1 for blocking wait.
Returns
the actual number of bytes read and -1 on on failure; call SDL_GetError() for more information. If no packet was available to be read within the timeout period, this function returns 0.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_read_timeout(device->device, data, length, milliseconds);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_read_timeout.
SDL_hid_send_feature_report()
int SDL_hid_send_feature_report (SDL_hid_device * dev, const unsigned char * data, size_t length)
Send a Feature report to the device.
Feature reports are sent over the Control endpoint as a Set_Report transfer. The first byte of data must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to SDL_hid_send_feature_report() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to SDL_hid_send_feature_report(): the Report ID (or 0x0, for devices which do not use numbered reports), followed by the report data (16 bytes). In this example, the length passed in would be 17.
Parameters
dev a device handle returned from SDL_hid_open().
data the data to send, including the report number as the first byte.
length the length in bytes of the data to send, including the report number.
Returns
the actual number of bytes written and -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_send_feature_report(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_send_feature_report.
SDL_hid_set_nonblocking()
int SDL_hid_set_nonblocking (SDL_hid_device * dev, int nonblock)
Set the device handle to be non-blocking.
In non-blocking mode calls to SDL_hid_read() will return immediately with a value of 0 if there is no data to be read. In blocking mode, SDL_hid_read() will wait (block) until there is data to read before returning.
Nonblocking can be turned on and off at any time.
Parameters
dev a device handle returned from SDL_hid_open().
nonblock enable or not the nonblocking reads - 1 to enable nonblocking - 0 to disable nonblocking.
Returns
0 on success or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_set_nonblocking(device->device, nonblock);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_set_nonblocking.
SDL_hid_write()
int SDL_hid_write (SDL_hid_device * dev, const unsigned char * data, size_t length)
Write an Output report to a HID device.
The first byte of data must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to SDL_hid_write() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to SDL_hid_write(), the Report ID (or 0x0, for devices with a single report), followed by the report data (16 bytes). In this example, the length passed in would be 17.
SDL_hid_write() will send the data on the first OUT endpoint, if one exists. If it does not, it will send the data through the Control Endpoint (Endpoint 0).
Parameters
dev a device handle returned from SDL_hid_open().
data the data to send, including the report number as the first byte.
length the length in bytes of the data to send.
Returns
the actual number of bytes written and -1 on on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_DEVICE_MAGIC(device, -1);
    return device->backend->hid_write(device->device, data, length);
}
References SDL_hid_device::backend, CHECK_DEVICE_MAGIC, SDL_hid_device::device, and hidapi_backend::hid_write.
SDL_HIDAPI_ShouldIgnoreDevice()
bool SDL_HIDAPI_ShouldIgnoreDevice (int bus, Uint16 vendor_id, Uint16 product_id, Uint16 usage_page, Uint16 usage)
{
    // See if there are any devices we should skip in enumeration
    if (SDL_hidapi_only_controllers && usage_page) {
        if (vendor_id == USB_VENDOR_VALVE) {
            // Ignore the mouse/keyboard interface on Steam Controllers
            if (
#ifdef SDL_PLATFORM_WIN32
                // Check the usage page and usage on both USB and Bluetooth
#else
                // Only check the usage page and usage on USB
                bus == HID_API_BUS_USB &&
#endif
                usage_page == USB_USAGEPAGE_GENERIC_DESKTOP &&
                (usage == USB_USAGE_GENERIC_KEYBOARD || usage == USB_USAGE_GENERIC_MOUSE)) {
                return true;
            }
        } else if (vendor_id == USB_VENDOR_FLYDIGI && product_id == USB_PRODUCT_FLYDIGI_GAMEPAD) {
            if (usage_page == USB_USAGEPAGE_VENDOR_FLYDIGI) {
                return false;
            }
            return true;
        } else if (usage_page == USB_USAGEPAGE_GENERIC_DESKTOP &&
                   (usage == USB_USAGE_GENERIC_JOYSTICK || usage == USB_USAGE_GENERIC_GAMEPAD || usage == USB_USAGE_GENERIC_MULTIAXISCONTROLLER)) {
            // This is a controller
        } else {
            return true;
        }
    }
    if (SDL_hidapi_ignored_devices) {
        char vendor_match[16], product_match[16];
        SDL_snprintf(vendor_match, sizeof(vendor_match), "0x%.4x/0x0000", vendor_id);
        SDL_snprintf(product_match, sizeof(product_match), "0x%.4x/0x%.4x", vendor_id, product_id);
        if (SDL_strcasestr(SDL_hidapi_ignored_devices, vendor_match) ||
            SDL_strcasestr(SDL_hidapi_ignored_devices, product_match)) {
            return true;
        }
    }
    return false;
}
References HID_API_BUS_USB, SDL_hidapi_ignored_devices, SDL_hidapi_only_controllers, SDL_snprintf(), SDL_strcasestr(), USB_PRODUCT_FLYDIGI_GAMEPAD, USB_USAGE_GENERIC_GAMEPAD, USB_USAGE_GENERIC_JOYSTICK, USB_USAGE_GENERIC_KEYBOARD, USB_USAGE_GENERIC_MOUSE, USB_USAGE_GENERIC_MULTIAXISCONTROLLER, USB_USAGEPAGE_GENERIC_DESKTOP, USB_USAGEPAGE_VENDOR_FLYDIGI, USB_VENDOR_FLYDIGI, and USB_VENDOR_VALVE.
Referenced by PLATFORM_hid_enumerate().
Variable Documentation
m_bCanGetNotifications
bool m_bCanGetNotifications
m_bInitialized
bool m_bInitialized
m_unDeviceChangeCounter
Uint32 m_unDeviceChangeCounter
m_unLastDetect
Uint64 m_unLastDetect
[struct]
struct { ... } SDL_HIDAPI_discovery
Referenced by HIDAPI_InitializeDiscovery(), HIDAPI_ShutdownDiscovery(), HIDAPI_UpdateDiscovery(), and SDL_hid_device_change_count().
SDL_hidapi_ignored_devices
char* SDL_hidapi_ignored_devices = NULL static
Referenced by IgnoredDevicesChanged(), SDL_hid_exit(), and SDL_HIDAPI_ShouldIgnoreDevice().
SDL_hidapi_only_controllers
bool SDL_hidapi_only_controllers static
Referenced by OnlyControllersChanged(), and SDL_HIDAPI_ShouldIgnoreDevice().
SDL_hidapi_refcount
int SDL_hidapi_refcount = 0 static
Referenced by SDL_hid_device_change_count(), SDL_hid_enumerate(), SDL_hid_exit(), SDL_hid_init(), SDL_hid_open(), and SDL_hid_open_path().
use_libusb_whitelist
bool use_libusb_whitelist = false static
Referenced by SDL_hid_enumerate(), and SDL_hid_init().