SDL3: SDL-main/include/SDL3/SDL_sensor.h File Reference
SDL_sensor.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDL_STANDARD_GRAVITY 9.80665f
Typedefs
typedef struct SDL_Sensor SDL_Sensor
typedef Uint32 SDL_SensorID
typedef enum SDL_SensorType SDL_SensorType
Enumerations
enum SDL_SensorType {
SDL_SENSOR_INVALID = -1 , SDL_SENSOR_UNKNOWN , SDL_SENSOR_ACCEL , SDL_SENSOR_GYRO ,
SDL_SENSOR_ACCEL_L , SDL_SENSOR_GYRO_L , SDL_SENSOR_ACCEL_R , SDL_SENSOR_GYRO_R
}
Functions
SDL_DECLSPEC void SDLCALL SDL_CloseSensor (SDL_Sensor *sensor)
SDL_DECLSPEC bool SDLCALL SDL_GetSensorData (SDL_Sensor *sensor, float *data, int num_values)
SDL_DECLSPEC SDL_Sensor *SDLCALL SDL_GetSensorFromID (SDL_SensorID instance_id)
SDL_DECLSPEC SDL_SensorID SDLCALL SDL_GetSensorID (SDL_Sensor *sensor)
SDL_DECLSPEC const char *SDLCALL SDL_GetSensorName (SDL_Sensor *sensor)
SDL_DECLSPEC const char *SDLCALL SDL_GetSensorNameForID (SDL_SensorID instance_id)
SDL_DECLSPEC int SDLCALL SDL_GetSensorNonPortableType (SDL_Sensor *sensor)
SDL_DECLSPEC int SDLCALL SDL_GetSensorNonPortableTypeForID (SDL_SensorID instance_id)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetSensorProperties (SDL_Sensor *sensor)
SDL_DECLSPEC SDL_SensorID *SDLCALL SDL_GetSensors (int *count)
SDL_DECLSPEC SDL_SensorType SDLCALL SDL_GetSensorType (SDL_Sensor *sensor)
SDL_DECLSPEC SDL_SensorType SDLCALL SDL_GetSensorTypeForID (SDL_SensorID instance_id)
SDL_DECLSPEC SDL_Sensor *SDLCALL SDL_OpenSensor (SDL_SensorID instance_id)
SDL_DECLSPEC void SDLCALL SDL_UpdateSensors (void)
Macro Definition Documentation
SDL_STANDARD_GRAVITY
#define SDL_STANDARD_GRAVITY 9.80665f
A constant to represent standard gravity for accelerometer sensors.
The accelerometer returns the current acceleration in SI meters per second squared. This measurement includes the force of gravity, so a device at rest will have an value of SDL_STANDARD_GRAVITY away from the center of the earth, which is a positive Y value.
Since
This macro is available since SDL 3.2.0.
Referenced by IOS_MFIJoystickUpdate().
Typedef Documentation
SDL_Sensor
typedef struct SDL_Sensor SDL_Sensor
CategorySensor
SDL sensor management.
These APIs grant access to gyros and accelerometers on various platforms.
In order to use these functions, SDL_Init() must have been called with the SDL_INIT_SENSOR flag. This causes SDL to scan the system for sensors, and load appropriate drivers. The opaque structure used to identify an opened SDL sensor.
Since
This struct is available since SDL 3.2.0.
SDL_SensorID
typedef Uint32 SDL_SensorID
This is a unique ID for a sensor for the time it is connected to the system, and is never reused for the lifetime of the application.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
SDL_SensorType
typedef enum SDL_SensorType SDL_SensorType
The different sensors defined by SDL.
Additional sensors may be available, using platform dependent semantics.
Here are the additional Android sensors:
https://developer.android.com/reference/android/hardware/SensorEvent.html#values
Accelerometer sensor notes:
The accelerometer returns the current acceleration in SI meters per second squared. This measurement includes the force of gravity, so a device at rest will have an value of SDL_STANDARD_GRAVITY away from the center of the earth, which is a positive Y value.
values[0]: Acceleration on the x axis
values[1]: Acceleration on the y axis
values[2]: Acceleration on the z axis
For phones and tablets held in natural orientation and game controllers held in front of you, the axes are defined as follows:
-X ... +X : left ... right
-Y ... +Y : bottom ... top
-Z ... +Z : farther ... closer
The accelerometer axis data is not changed when the device is rotated.
Gyroscope sensor notes:
The gyroscope returns the current rate of rotation in radians per second. The rotation is positive in the counter-clockwise direction. That is, an observer looking from a positive location on one of the axes would see positive rotation on that axis when it appeared to be rotating counter-clockwise.
values[0]: Angular speed around the x axis (pitch)
values[1]: Angular speed around the y axis (yaw)
values[2]: Angular speed around the z axis (roll)
For phones and tablets held in natural orientation and game controllers held in front of you, the axes are defined as follows:
-X ... +X : left ... right
-Y ... +Y : bottom ... top
-Z ... +Z : farther ... closer
The gyroscope axis data is not changed when the device is rotated.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetCurrentDisplayOrientation
Enumeration Type Documentation
SDL_SensorType
enum SDL_SensorType
The different sensors defined by SDL.
Additional sensors may be available, using platform dependent semantics.
Here are the additional Android sensors:
https://developer.android.com/reference/android/hardware/SensorEvent.html#values
Accelerometer sensor notes:
The accelerometer returns the current acceleration in SI meters per second squared. This measurement includes the force of gravity, so a device at rest will have an value of SDL_STANDARD_GRAVITY away from the center of the earth, which is a positive Y value.
values[0]: Acceleration on the x axis
values[1]: Acceleration on the y axis
values[2]: Acceleration on the z axis
For phones and tablets held in natural orientation and game controllers held in front of you, the axes are defined as follows:
-X ... +X : left ... right
-Y ... +Y : bottom ... top
-Z ... +Z : farther ... closer
The accelerometer axis data is not changed when the device is rotated.
Gyroscope sensor notes:
The gyroscope returns the current rate of rotation in radians per second. The rotation is positive in the counter-clockwise direction. That is, an observer looking from a positive location on one of the axes would see positive rotation on that axis when it appeared to be rotating counter-clockwise.
values[0]: Angular speed around the x axis (pitch)
values[1]: Angular speed around the y axis (yaw)
values[2]: Angular speed around the z axis (roll)
For phones and tablets held in natural orientation and game controllers held in front of you, the axes are defined as follows:
-X ... +X : left ... right
-Y ... +Y : bottom ... top
-Z ... +Z : farther ... closer
The gyroscope axis data is not changed when the device is rotated.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetCurrentDisplayOrientation
Enumerator
SDL_SENSOR_INVALID
Returned for an invalid sensor
SDL_SENSOR_UNKNOWN
Unknown sensor type
SDL_SENSOR_ACCEL
Accelerometer
SDL_SENSOR_GYRO
Gyroscope
SDL_SENSOR_ACCEL_L
Accelerometer for left Joy-Con controller and Wii nunchuk
SDL_SENSOR_GYRO_L
Gyroscope for left Joy-Con controller
SDL_SENSOR_ACCEL_R
Accelerometer for right Joy-Con controller
SDL_SENSOR_GYRO_R
Gyroscope for right Joy-Con controller
{
    SDL_SENSOR_INVALID = -1,    /**< Returned for an invalid sensor */
    SDL_SENSOR_UNKNOWN,         /**< Unknown sensor type */
    SDL_SENSOR_ACCEL,           /**< Accelerometer */
    SDL_SENSOR_GYRO,            /**< Gyroscope */
    SDL_SENSOR_ACCEL_L,         /**< Accelerometer for left Joy-Con controller and Wii nunchuk */
    SDL_SENSOR_GYRO_L,          /**< Gyroscope for left Joy-Con controller */
    SDL_SENSOR_ACCEL_R,         /**< Accelerometer for right Joy-Con controller */
    SDL_SENSOR_GYRO_R           /**< Gyroscope for right Joy-Con controller */
} SDL_SensorType;
Function Documentation
SDL_CloseSensor()
SDL_DECLSPEC void SDLCALL SDL_CloseSensor (SDL_Sensor * sensor) extern
Close a sensor previously opened with SDL_OpenSensor().
Parameters
sensor the SDL_Sensor object to close.
Since
This function is available since SDL 3.2.0.
{
    SDL_Sensor *sensorlist;
    SDL_Sensor *sensorlistprev;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor,);
        // First decrement ref count
        if (--sensor->ref_count > 0) {
            SDL_UnlockSensors();
            return;
        }
        SDL_DestroyProperties(sensor->props);
        sensor->driver->Close(sensor);
        sensor->hwdata = NULL;
        SDL_SetObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR, false);
        sensorlist = SDL_sensors;
        sensorlistprev = NULL;
        while (sensorlist) {
            if (sensor == sensorlist) {
                if (sensorlistprev) {
                    // unlink this entry
                    sensorlistprev->next = sensorlist->next;
                } else {
                    SDL_sensors = sensor->next;
                }
                break;
            }
            sensorlistprev = sensorlist;
            sensorlist = sensorlist->next;
        }
        // Free the data associated with this sensor
        SDL_free(sensor->name);
        SDL_free(sensor);
    }
    SDL_UnlockSensors();
}
References CHECK_SENSOR_MAGIC, NULL, SDL_DestroyProperties(), SDL_free(), SDL_LockSensors(), SDL_OBJECT_TYPE_SENSOR, SDL_SetObjectValid(), and SDL_UnlockSensors().
Referenced by CleanupSensorFusion(), SDL_QuitSensors(), and SDL_SetGamepadSensorEnabled().
SDL_GetSensorData()
SDL_DECLSPEC bool SDLCALL SDL_GetSensorData (SDL_Sensor * sensor, float * data, int num_values) extern
Get the current state of an opened sensor.
The number of values and interpretation of the data is sensor dependent.
Parameters
sensor the SDL_Sensor object to query.
data a pointer filled with the current sensor state.
num_values the number of values to write to data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, false);
        num_values = SDL_min(num_values, SDL_arraysize(sensor->data));
        SDL_memcpy(data, sensor->data, num_values * sizeof(*data));
    }
    SDL_UnlockSensors();
    return true;
}
References CHECK_SENSOR_MAGIC, SDL_arraysize, SDL_LockSensors(), SDL_memcpy, SDL_min, and SDL_UnlockSensors().
SDL_GetSensorFromID()
SDL_DECLSPEC SDL_Sensor *SDLCALL SDL_GetSensorFromID (SDL_SensorID instance_id) extern
Return the SDL_Sensor associated with an instance ID.
Parameters
instance_id the sensor instance ID.
Returns
an SDL_Sensor object or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Sensor *sensor;
    SDL_LockSensors();
    for (sensor = SDL_sensors; sensor; sensor = sensor->next) {
        if (sensor->instance_id == instance_id) {
            break;
        }
    }
    SDL_UnlockSensors();
    return sensor;
}
References SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorID()
SDL_DECLSPEC SDL_SensorID SDLCALL SDL_GetSensorID (SDL_Sensor * sensor) extern
Get the instance ID of a sensor.
Parameters
sensor the SDL_Sensor object to inspect.
Returns
the sensor instance ID, or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorID result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, 0);
        result = sensor->instance_id;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorName()
SDL_DECLSPEC const char *SDLCALL SDL_GetSensorName (SDL_Sensor * sensor) extern
Get the implementation dependent name of a sensor.
Parameters
sensor the SDL_Sensor object.
Returns
the sensor name or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    const char *result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, NULL);
        result = SDL_GetPersistentString(sensor->name);
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, NULL, SDL_GetPersistentString(), SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorNameForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetSensorNameForID (SDL_SensorID instance_id) extern
Get the implementation dependent name of a sensor.
This can be called before any sensors are opened.
Parameters
instance_id the sensor instance ID.
Returns
the sensor name, or NULL if instance_id is not valid.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    const char *name = NULL;
    SDL_LockSensors();
    if (SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        name = SDL_GetPersistentString(driver->GetDeviceName(device_index));
    }
    SDL_UnlockSensors();
    return name;
}
References SDL_SensorDriver::GetDeviceName, NULL, SDL_GetDriverAndSensorIndex(), SDL_GetPersistentString(), SDL_LockSensors(), and SDL_UnlockSensors().
Referenced by IsROGAlly().
SDL_GetSensorNonPortableType()
SDL_DECLSPEC int SDLCALL SDL_GetSensorNonPortableType (SDL_Sensor * sensor) extern
Get the platform dependent type of a sensor.
Parameters
sensor the SDL_Sensor object to inspect.
Returns
the sensor platform dependent type, or -1 if sensor is NULL.
Since
This function is available since SDL 3.2.0.
{
    int result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, -1);
        result = sensor->non_portable_type;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorNonPortableTypeForID()
SDL_DECLSPEC int SDLCALL SDL_GetSensorNonPortableTypeForID (SDL_SensorID instance_id) extern
Get the platform dependent type of a sensor.
This can be called before any sensors are opened.
Parameters
instance_id the sensor instance ID.
Returns
the sensor platform dependent type, or -1 if instance_id is not valid.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    int type = -1;
    SDL_LockSensors();
    if (SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        type = driver->GetDeviceNonPortableType(device_index);
    }
    SDL_UnlockSensors();
    return type;
}
References SDL_SensorDriver::GetDeviceNonPortableType, SDL_GetDriverAndSensorIndex(), SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensorProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetSensorProperties (SDL_Sensor * sensor) extern
Get the properties associated with a sensor.
Parameters
sensor the SDL_Sensor object.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, 0);
        if (sensor->props == 0) {
            sensor->props = SDL_CreateProperties();
        }
        result = sensor->props;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_CreateProperties(), SDL_LockSensors(), and SDL_UnlockSensors().
SDL_GetSensors()
SDL_DECLSPEC SDL_SensorID *SDLCALL SDL_GetSensors (int * count) extern
Get a list of currently connected sensors.
Parameters
count a pointer filled in with the number of sensors returned, may be NULL.
Returns
a 0 terminated array of sensor instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    int i, num_sensors, device_index;
    int sensor_index = 0, total_sensors = 0;
    SDL_SensorID *sensors;
    SDL_LockSensors();
    {
        for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
            total_sensors += SDL_sensor_drivers[i]->GetCount();
        }
        sensors = (SDL_SensorID *)SDL_malloc((total_sensors + 1) * sizeof(*sensors));
        if (sensors) {
            if (count) {
                *count = total_sensors;
            }
            for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
                num_sensors = SDL_sensor_drivers[i]->GetCount();
                for (device_index = 0; device_index < num_sensors; ++device_index) {
                    SDL_assert(sensor_index < total_sensors);
                    sensors[sensor_index] = SDL_sensor_drivers[i]->GetDeviceInstanceID(device_index);
                    SDL_assert(sensors[sensor_index] > 0);
                    ++sensor_index;
                }
            }
            SDL_assert(sensor_index == total_sensors);
            sensors[sensor_index] = 0;
        } else {
            if (count) {
                *count = 0;
            }
        }
    }
    SDL_UnlockSensors();
    return sensors;
}
References count, SDL_arraysize, SDL_assert, SDL_LockSensors(), SDL_malloc(), SDL_sensor_drivers, and SDL_UnlockSensors().
Referenced by AttemptSensorFusion(), and IsROGAlly().
SDL_GetSensorType()
SDL_DECLSPEC SDL_SensorType SDLCALL SDL_GetSensorType (SDL_Sensor * sensor) extern
Get the type of a sensor.
Parameters
sensor the SDL_Sensor object to inspect.
Returns
the SDL_SensorType type, or SDL_SENSOR_INVALID if sensor is NULL.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorType result;
    SDL_LockSensors();
    {
        CHECK_SENSOR_MAGIC(sensor, SDL_SENSOR_INVALID);
        result = sensor->type;
    }
    SDL_UnlockSensors();
    return result;
}
References CHECK_SENSOR_MAGIC, SDL_LockSensors(), SDL_SENSOR_INVALID, and SDL_UnlockSensors().
SDL_GetSensorTypeForID()
SDL_DECLSPEC SDL_SensorType SDLCALL SDL_GetSensorTypeForID (SDL_SensorID instance_id) extern
Get the type of a sensor.
This can be called before any sensors are opened.
Parameters
instance_id the sensor instance ID.
Returns
the SDL_SensorType, or SDL_SENSOR_INVALID if instance_id is not valid.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    SDL_SensorType type = SDL_SENSOR_INVALID;
    SDL_LockSensors();
    if (SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        type = driver->GetDeviceType(device_index);
    }
    SDL_UnlockSensors();
    return type;
}
References SDL_SensorDriver::GetDeviceType, SDL_GetDriverAndSensorIndex(), SDL_LockSensors(), SDL_SENSOR_INVALID, and SDL_UnlockSensors().
Referenced by AttemptSensorFusion(), and IsROGAlly().
SDL_OpenSensor()
SDL_DECLSPEC SDL_Sensor *SDLCALL SDL_OpenSensor (SDL_SensorID instance_id) extern
Open a sensor for use.
Parameters
instance_id the sensor instance ID.
Returns
an SDL_Sensor object or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_SensorDriver *driver;
    int device_index;
    SDL_Sensor *sensor;
    SDL_Sensor *sensorlist;
    const char *sensorname = NULL;
    SDL_LockSensors();
    if (!SDL_GetDriverAndSensorIndex(instance_id, &driver, &device_index)) {
        SDL_UnlockSensors();
        return NULL;
    }
    sensorlist = SDL_sensors;
    /* If the sensor is already open, return it
     * it is important that we have a single sensor * for each instance id
     */
    while (sensorlist) {
        if (instance_id == sensorlist->instance_id) {
            sensor = sensorlist;
            ++sensor->ref_count;
            SDL_UnlockSensors();
            return sensor;
        }
        sensorlist = sensorlist->next;
    }
    // Create and initialize the sensor
    sensor = (SDL_Sensor *)SDL_calloc(1, sizeof(*sensor));
    if (!sensor) {
        SDL_UnlockSensors();
        return NULL;
    }
    SDL_SetObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR, true);
    sensor->driver = driver;
    sensor->instance_id = instance_id;
    sensor->type = driver->GetDeviceType(device_index);
    sensor->non_portable_type = driver->GetDeviceNonPortableType(device_index);
    if (!driver->Open(sensor, device_index)) {
        SDL_SetObjectValid(sensor, SDL_OBJECT_TYPE_SENSOR, false);
        SDL_free(sensor);
        SDL_UnlockSensors();
        return NULL;
    }
    sensorname = driver->GetDeviceName(device_index);
    if (sensorname) {
        sensor->name = SDL_strdup(sensorname);
    } else {
        sensor->name = NULL;
    }
    // Add sensor to list
    ++sensor->ref_count;
    // Link the sensor in the list
    sensor->next = SDL_sensors;
    SDL_sensors = sensor;
    driver->Update(sensor);
    SDL_UnlockSensors();
    return sensor;
}
References SDL_SensorDriver::GetDeviceName, SDL_SensorDriver::GetDeviceNonPortableType, SDL_SensorDriver::GetDeviceType, NULL, SDL_SensorDriver::Open, SDL_calloc(), SDL_free(), SDL_GetDriverAndSensorIndex(), SDL_LockSensors(), SDL_OBJECT_TYPE_SENSOR, SDL_SetObjectValid(), SDL_strdup(), SDL_UnlockSensors(), and SDL_SensorDriver::Update.
Referenced by SDL_SetGamepadSensorEnabled().
SDL_UpdateSensors()
SDL_DECLSPEC void SDLCALL SDL_UpdateSensors (void) extern
Update the current state of the open sensors.
This is called automatically by the event loop if sensor events are enabled.
This needs to be called from the thread that initialized the sensor subsystem.
Since
This function is available since SDL 3.2.0.
{
    int i;
    SDL_Sensor *sensor;
    if (!SDL_WasInit(SDL_INIT_SENSOR)) {
        return;
    }
    SDL_LockSensors();
    for (sensor = SDL_sensors; sensor; sensor = sensor->next) {
        sensor->driver->Update(sensor);
    }
    /* this needs to happen AFTER walking the sensor list above, so that any
       dangling hardware data from removed devices can be free'd
     */
    for (i = 0; i < SDL_arraysize(SDL_sensor_drivers); ++i) {
        SDL_sensor_drivers[i]->Detect();
    }
    SDL_UnlockSensors();
}
References SDL_arraysize, SDL_INIT_SENSOR, SDL_LockSensors(), SDL_sensor_drivers, SDL_UnlockSensors(), and SDL_WasInit().
Referenced by SDL_PumpEventMaintenance().