SDL3: SDL-main/include/SDL3/SDL_camera.h File Reference
SDL_camera.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_pixels.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_surface.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_CameraSpec
Typedefs
typedef struct SDL_Camera SDL_Camera
typedef Uint32 SDL_CameraID
typedef enum SDL_CameraPosition SDL_CameraPosition
typedef struct SDL_CameraSpec SDL_CameraSpec
Enumerations
enum SDL_CameraPosition { SDL_CAMERA_POSITION_UNKNOWN , SDL_CAMERA_POSITION_FRONT_FACING , SDL_CAMERA_POSITION_BACK_FACING }
Functions
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_AcquireCameraFrame (SDL_Camera *camera, Uint64 *timestampNS)
SDL_DECLSPEC void SDLCALL SDL_CloseCamera (SDL_Camera *camera)
SDL_DECLSPEC const char *SDLCALL SDL_GetCameraDriver (int index)
SDL_DECLSPEC bool SDLCALL SDL_GetCameraFormat (SDL_Camera *camera, SDL_CameraSpec *spec)
SDL_DECLSPEC SDL_CameraID SDLCALL SDL_GetCameraID (SDL_Camera *camera)
SDL_DECLSPEC const char *SDLCALL SDL_GetCameraName (SDL_CameraID instance_id)
SDL_DECLSPEC int SDLCALL SDL_GetCameraPermissionState (SDL_Camera *camera)
SDL_DECLSPEC SDL_CameraPosition SDLCALL SDL_GetCameraPosition (SDL_CameraID instance_id)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetCameraProperties (SDL_Camera *camera)
SDL_DECLSPEC SDL_CameraID *SDLCALL SDL_GetCameras (int *count)
SDL_DECLSPEC SDL_CameraSpec **SDLCALL SDL_GetCameraSupportedFormats (SDL_CameraID instance_id, int *count)
SDL_DECLSPEC const char *SDLCALL SDL_GetCurrentCameraDriver (void)
SDL_DECLSPEC int SDLCALL SDL_GetNumCameraDrivers (void)
SDL_DECLSPEC SDL_Camera *SDLCALL SDL_OpenCamera (SDL_CameraID instance_id, const SDL_CameraSpec *spec)
SDL_DECLSPEC void SDLCALL SDL_ReleaseCameraFrame (SDL_Camera *camera, SDL_Surface *frame)
Typedef Documentation
SDL_Camera
typedef struct SDL_Camera SDL_Camera
The opaque structure used to identify an opened SDL camera.
Since
This struct is available since SDL 3.2.0.
SDL_CameraID
typedef Uint32 SDL_CameraID
CategoryCamera
Video capture for the SDL library.
This API lets apps read input from video sources, like webcams. Camera devices can be enumerated, queried, and opened. Once opened, it will provide SDL_Surface objects as new frames of video come in. These surfaces can be uploaded to an SDL_Texture or processed as pixels in memory.
Several platforms will alert the user if an app tries to access a camera, and some will present a UI asking the user if your application should be allowed to obtain images at all, which they can deny. A successfully opened camera will not provide images until permission is granted. Applications, after opening a camera device, can see if they were granted access by either polling with the SDL_GetCameraPermissionState() function, or waiting for an SDL_EVENT_CAMERA_DEVICE_APPROVED or SDL_EVENT_CAMERA_DEVICE_DENIED event. Platforms that don't have any user approval process will report approval immediately.
Note that SDL cameras only provide video as individual frames; they will not provide full-motion video encoded in a movie file format, although an app is free to encode the acquired frames into any format it likes. It also does not provide audio from the camera hardware through this API; not only do many webcams not have microphones at all, many people–from streamers to people on Zoom calls–will want to use a separate microphone regardless of the camera. In any case, recorded audio will be available through SDL's audio API no matter what hardware provides the microphone.
Camera gotchas
Consumer-level camera hardware tends to take a little while to warm up, once the device has been opened. Generally most camera apps have some sort of UI to take a picture (a button to snap a pic while a preview is showing, some sort of multi-second countdown for the user to pose, like a photo booth), which puts control in the users' hands, or they are intended to stay on for long times (Pokemon Go, etc).
It's not uncommon that a newly-opened camera will provide a couple of completely black frames, maybe followed by some under-exposed images. If taking a single frame automatically, or recording video from a camera's input without the user initiating it from a preview, it could be wise to drop the first several frames (if not the first several seconds worth of frames!) before using images from a camera. This is a unique ID for a camera device for the time it is connected to the system, and is never reused for the lifetime of the application.
If the device is disconnected and reconnected, it will get a new ID.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_GetCameras
SDL_CameraPosition
typedef enum SDL_CameraPosition SDL_CameraPosition
The position of camera in relation to system device.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetCameraPosition
SDL_CameraSpec
typedef struct SDL_CameraSpec SDL_CameraSpec
The details of an output format for a camera device.
Cameras often support multiple formats; each one will be encapsulated in this struct.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GetCameraSupportedFormats
SDL_GetCameraFormat
Enumeration Type Documentation
SDL_CameraPosition
enum SDL_CameraPosition
The position of camera in relation to system device.
Since
This enum is available since SDL 3.2.0.
See also
SDL_GetCameraPosition
Enumerator
SDL_CAMERA_POSITION_UNKNOWN
SDL_CAMERA_POSITION_FRONT_FACING
SDL_CAMERA_POSITION_BACK_FACING
{
    SDL_CAMERA_POSITION_UNKNOWN,
    SDL_CAMERA_POSITION_FRONT_FACING,
    SDL_CAMERA_POSITION_BACK_FACING
} SDL_CameraPosition;
Function Documentation
SDL_AcquireCameraFrame()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_AcquireCameraFrame (SDL_Camera * camera, Uint64 * timestampNS) extern
Acquire a frame.
The frame is a memory pointer to the image data, whose size and format are given by the spec requested when opening the device.
This is a non blocking API. If there is a frame available, a non-NULL surface is returned, and timestampNS will be filled with a non-zero value.
Note that an error case can also return NULL, but a NULL by itself is normal and just signifies that a new frame is not yet available. Note that even if a camera device fails outright (a USB camera is unplugged while in use, etc), SDL will send an event separately to notify the app, but continue to provide blank frames at ongoing intervals until SDL_CloseCamera() is called, so real failure here is almost always an out of memory condition.
After use, the frame should be released with SDL_ReleaseCameraFrame(). If you don't do this, the system may stop providing more video!
Do not call SDL_DestroySurface() on the returned surface! It must be given back to the camera subsystem with SDL_ReleaseCameraFrame!
If the system is waiting for the user to approve access to the camera, as some platforms require, this will return NULL (no frames available); you should either wait for an SDL_EVENT_CAMERA_DEVICE_APPROVED (or SDL_EVENT_CAMERA_DEVICE_DENIED) event, or poll SDL_GetCameraPermissionState() occasionally until it returns non-zero.
Parameters
camera opened camera device.
timestampNS a pointer filled in with the frame's timestamp, or 0 on error. Can be NULL.
Returns
a new frame of video on success, NULL if none is currently available.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ReleaseCameraFrame
{
    if (timestampNS) {
        *timestampNS = 0;
    }
    if (!camera) {
        SDL_InvalidParamError("camera");
        return NULL;
    }
    SDL_Camera *device = camera;  // currently there's no separation between physical and logical device.
    ObtainPhysicalCameraObj(device);
    if (device->permission <= 0) {
        ReleaseCamera(device);
        SDL_SetError("Camera permission has not been granted");
        return NULL;
    }
    SDL_Surface *result = NULL;
    // frames are in this list from newest to oldest, so find the end of the list...
    SurfaceList *slistprev = &device->filled_output_surfaces;
    SurfaceList *slist = slistprev;
    while (slist->next) {
        slistprev = slist;
        slist = slist->next;
    }
    const bool list_is_empty = (slist == slistprev);
    if (!list_is_empty) { // report the oldest frame.
        if (timestampNS) {
            *timestampNS = slist->timestampNS;
        }
        result = slist->surface;
        slistprev->next = slist->next;  // remove from filled list.
        slist->next = device->app_held_output_surfaces.next;  // add to app_held list.
        device->app_held_output_surfaces.next = slist;
    }
    ReleaseCamera(device);
    return result;
}
References SDL_Camera::app_held_output_surfaces, SDL_Camera::filled_output_surfaces, SurfaceList::next, NULL, ObtainPhysicalCameraObj(), SDL_Camera::permission, ReleaseCamera(), SDL_InvalidParamError, SDL_SetError(), SurfaceList::surface, and SurfaceList::timestampNS.
SDL_CloseCamera()
SDL_DECLSPEC void SDLCALL SDL_CloseCamera (SDL_Camera * camera) extern
Use this function to shut down camera processing and close the camera device.
Parameters
camera opened camera device.
Thread Safety
It is safe to call this function from any thread, but no thread may reference device once this function is called.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenCamera
{
    SDL_Camera *device = camera;  // currently there's no separation between physical and logical device.
    ClosePhysicalCamera(device);
}
References ClosePhysicalCamera().
SDL_GetCameraDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetCameraDriver (int index) extern
Use this function to get the name of a built in camera driver.
The list of camera drivers is given in the order that they are normally initialized by default; the drivers that seem more reasonable to choose first (as far as the SDL developers believe) are earlier in the list.
The names of drivers are all simple, low-ASCII identifiers, like "v4l2", "coremedia" or "android". These never have Unicode characters, and are not meant to be proper names.
Parameters
index the index of the camera driver; the value ranges from 0 to SDL_GetNumCameraDrivers() - 1.
Returns
the name of the camera driver at the requested index, or NULL if an invalid index was specified.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumCameraDrivers
{
    if (index >= 0 && index < SDL_GetNumCameraDrivers()) {
        return bootstrap[index]->name;
    }
    SDL_InvalidParamError("index");
    return NULL;
}
References bootstrap, NULL, SDL_GetNumCameraDrivers(), and SDL_InvalidParamError.
SDL_GetCameraFormat()
SDL_DECLSPEC bool SDLCALL SDL_GetCameraFormat (SDL_Camera * camera, SDL_CameraSpec * spec) extern
Get the spec that a camera is using when generating images.
Note that this might not be the native format of the hardware, as SDL might be converting to this format behind the scenes.
If the system is waiting for the user to approve access to the camera, as some platforms require, this will return false, but this isn't necessarily a fatal error; you should either wait for an SDL_EVENT_CAMERA_DEVICE_APPROVED (or SDL_EVENT_CAMERA_DEVICE_DENIED) event, or poll SDL_GetCameraPermissionState() occasionally until it returns non-zero.
Parameters
camera opened camera device.
spec the SDL_CameraSpec to be initialized by this function.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenCamera
{
    bool result;
    if (!camera) {
        return SDL_InvalidParamError("camera");
    } else if (!spec) {
        return SDL_InvalidParamError("spec");
    }
    SDL_Camera *device = camera;  // currently there's no separation between physical and logical device.
    ObtainPhysicalCameraObj(device);
    if (device->permission > 0) {
        SDL_copyp(spec, &device->spec);
        result = true;
    } else {
        SDL_zerop(spec);
        result = SDL_SetError("Camera permission has not been granted");
    }
    ReleaseCamera(device);
    return result;
}
References ObtainPhysicalCameraObj(), SDL_Camera::permission, ReleaseCamera(), SDL_copyp, SDL_InvalidParamError, SDL_SetError(), SDL_zerop, and SDL_Camera::spec.
SDL_GetCameraID()
SDL_DECLSPEC SDL_CameraID SDLCALL SDL_GetCameraID (SDL_Camera * camera) extern
Get the instance ID of an opened camera.
Parameters
camera an SDL_Camera to query.
Returns
the instance ID of the specified camera on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenCamera
{
    SDL_CameraID result = 0;
    if (!camera) {
        SDL_InvalidParamError("camera");
    } else {
        SDL_Camera *device = camera;  // currently there's no separation between physical and logical device.
        ObtainPhysicalCameraObj(device);
        result = device->instance_id;
        ReleaseCamera(device);
    }
    return result;
}
References SDL_Camera::instance_id, ObtainPhysicalCameraObj(), ReleaseCamera(), and SDL_InvalidParamError.
SDL_GetCameraName()
SDL_DECLSPEC const char *SDLCALL SDL_GetCameraName (SDL_CameraID instance_id) extern
Get the human-readable device name for a camera.
Parameters
instance_id the camera device instance ID.
Returns
a human-readable device name or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCameras
{
    const char *result = NULL;
    SDL_Camera *device = ObtainPhysicalCamera(instance_id);
    if (device) {
        result = SDL_GetPersistentString(device->name);
        ReleaseCamera(device);
    }
    return result;
}
References SDL_Camera::name, NULL, ObtainPhysicalCamera(), ReleaseCamera(), and SDL_GetPersistentString().
SDL_GetCameraPermissionState()
SDL_DECLSPEC int SDLCALL SDL_GetCameraPermissionState (SDL_Camera * camera) extern
Query if camera access has been approved by the user.
Cameras will not function between when the device is opened by the app and when the user permits access to the hardware. On some platforms, this presents as a popup dialog where the user has to explicitly approve access; on others the approval might be implicit and not alert the user at all.
This function can be used to check the status of that approval. It will return 0 if still waiting for user response, 1 if the camera is approved for use, and -1 if the user denied access.
Instead of polling with this function, you can wait for a SDL_EVENT_CAMERA_DEVICE_APPROVED (or SDL_EVENT_CAMERA_DEVICE_DENIED) event in the standard SDL event loop, which is guaranteed to be sent once when permission to use the camera is decided.
If a camera is declined, there's nothing to be done but call SDL_CloseCamera() to dispose of it.
Parameters
camera the opened camera device to query.
Returns
-1 if user denied access to the camera, 1 if user approved access, 0 if no decision has been made yet.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenCamera
SDL_CloseCamera
{
    int result;
    if (!camera) {
        SDL_InvalidParamError("camera");
        result = -1;
    } else {
        SDL_Camera *device = camera;  // currently there's no separation between physical and logical device.
        ObtainPhysicalCameraObj(device);
        result = device->permission;
        ReleaseCamera(device);
    }
    return result;
}
References ObtainPhysicalCameraObj(), SDL_Camera::permission, ReleaseCamera(), and SDL_InvalidParamError.
SDL_GetCameraPosition()
SDL_DECLSPEC SDL_CameraPosition SDLCALL SDL_GetCameraPosition (SDL_CameraID instance_id) extern
Get the position of the camera in relation to the system.
Most platforms will report UNKNOWN, but mobile devices, like phones, can often make a distinction between cameras on the front of the device (that points towards the user, for taking "selfies") and cameras on the back (for filming in the direction the user is facing).
Parameters
instance_id the camera device instance ID.
Returns
the position of the camera on the system hardware.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCameras
{
    SDL_CameraPosition result = SDL_CAMERA_POSITION_UNKNOWN;
    SDL_Camera *device = ObtainPhysicalCamera(instance_id);
    if (device) {
        result = device->position;
        ReleaseCamera(device);
    }
    return result;
}
References ObtainPhysicalCamera(), SDL_Camera::position, ReleaseCamera(), and SDL_CAMERA_POSITION_UNKNOWN.
SDL_GetCameraProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetCameraProperties (SDL_Camera * camera) extern
Get the properties associated with an opened camera.
Parameters
camera the SDL_Camera obtained from SDL_OpenCamera().
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID result = 0;
    if (!camera) {
        SDL_InvalidParamError("camera");
    } else {
        SDL_Camera *device = camera;  // currently there's no separation between physical and logical device.
        ObtainPhysicalCameraObj(device);
        if (device->props == 0) {
            device->props = SDL_CreateProperties();
        }
        result = device->props;
        ReleaseCamera(device);
    }
    return result;
}
References ObtainPhysicalCameraObj(), SDL_Camera::props, ReleaseCamera(), SDL_CreateProperties(), and SDL_InvalidParamError.
SDL_GetCameras()
SDL_DECLSPEC SDL_CameraID *SDLCALL SDL_GetCameras (int * count) extern
Get a list of currently connected camera devices.
Parameters
count a pointer filled in with the number of cameras returned, may be NULL.
Returns
a 0 terminated array of camera instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenCamera
{
    int dummy_count;
    if (!count) {
        count = &dummy_count;
    }
    if (!SDL_GetCurrentCameraDriver()) {
        *count = 0;
        SDL_SetError("Camera subsystem is not initialized");
        return NULL;
    }
    SDL_CameraID *result = NULL;
    SDL_LockRWLockForReading(camera_driver.device_hash_lock);
    int num_devices = SDL_GetAtomicInt(&camera_driver.device_count);
    result = (SDL_CameraID *) SDL_malloc((num_devices + 1) * sizeof (SDL_CameraID));
    if (!result) {
        num_devices = 0;
    } else {
        GetOneCameraData data = { result, 0 };
        SDL_IterateHashTable(camera_driver.device_hash, GetOneCamera, &data);
        SDL_assert(data.devs_seen == num_devices);
        result[num_devices] = 0;  // null-terminated.
    }
    SDL_UnlockRWLock(camera_driver.device_hash_lock);
    *count = num_devices;
    return result;
}
References camera_driver, count, GetOneCamera(), NULL, SDL_assert, SDL_GetAtomicInt(), SDL_GetCurrentCameraDriver(), SDL_IterateHashTable(), SDL_LockRWLockForReading(), SDL_malloc(), SDL_SetError(), and SDL_UnlockRWLock().
SDL_GetCameraSupportedFormats()
SDL_DECLSPEC SDL_CameraSpec **SDLCALL SDL_GetCameraSupportedFormats (SDL_CameraID instance_id, int * count) extern
Get the list of native formats/sizes a camera supports.
This returns a list of all formats and frame sizes that a specific camera can offer. This is useful if your app can accept a variety of image formats and sizes and so want to find the optimal spec that doesn't require conversion.
This function isn't strictly required; if you call SDL_OpenCamera with a NULL spec, SDL will choose a native format for you, and if you instead specify a desired format, it will transparently convert to the requested format on your behalf.
If count is not NULL, it will be filled with the number of elements in the returned array.
Note that it's legal for a camera to supply an empty list. This is what will happen on Emscripten builds, since that platform won't tell anything about available cameras until you've opened one, and won't even tell if there is a camera until the user has given you permission to check through a scary warning popup.
Parameters
instance_id the camera device instance ID.
count a pointer filled in with the number of elements in the list, may be NULL.
Returns
a NULL terminated array of pointers to SDL_CameraSpec or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCameras
SDL_OpenCamera
{
    if (count) {
        *count = 0;
    }
    SDL_Camera *device = ObtainPhysicalCamera(instance_id);
    if (!device) {
        return NULL;
    }
    int i;
    int num_specs = device->num_specs;
    SDL_CameraSpec **result = (SDL_CameraSpec **) SDL_malloc(((num_specs + 1) * sizeof(*result)) + (num_specs * sizeof (**result)));
    if (result) {
        SDL_CameraSpec *specs = (SDL_CameraSpec *)(result + (num_specs + 1));
        SDL_memcpy(specs, device->all_specs, num_specs * sizeof(*specs));
        for (i = 0; i < num_specs; ++i) {
            result[i] = specs++;
        }
        result[i] = NULL;
        if (count) {
            *count = num_specs;
        }
    }
    ReleaseCamera(device);
    return result;
}
References SDL_Camera::all_specs, count, NULL, SDL_Camera::num_specs, ObtainPhysicalCamera(), ReleaseCamera(), SDL_malloc(), and SDL_memcpy.
SDL_GetCurrentCameraDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetCurrentCameraDriver (void) extern
Get the name of the current camera driver.
The names of drivers are all simple, low-ASCII identifiers, like "v4l2", "coremedia" or "android". These never have Unicode characters, and are not meant to be proper names.
Returns
the name of the current camera driver or NULL if no driver has been initialized.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return camera_driver.name;
}
References camera_driver.
Referenced by ObtainPhysicalCamera(), SDL_CameraInit(), SDL_FindPhysicalCameraByCallback(), and SDL_GetCameras().
SDL_GetNumCameraDrivers()
SDL_DECLSPEC int SDLCALL SDL_GetNumCameraDrivers (void) extern
Use this function to get the number of built-in camera drivers.
This function returns a hardcoded number. This never returns a negative value; if there are no drivers compiled into this build of SDL, this function returns zero. The presence of a driver in this list does not mean it will function, it just means SDL is capable of interacting with that interface. For example, a build of SDL might have v4l2 support, but if there's no kernel support available, SDL's v4l2 driver would fail if used.
By default, SDL tries all drivers, in its preferred order, until one is found to be usable.
Returns
the number of built-in camera drivers.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCameraDriver
{
    return SDL_arraysize(bootstrap) - 1;
}
References bootstrap, and SDL_arraysize.
Referenced by SDL_GetCameraDriver().
SDL_OpenCamera()
SDL_DECLSPEC SDL_Camera *SDLCALL SDL_OpenCamera (SDL_CameraID instance_id, const SDL_CameraSpec * spec) extern
Open a video recording device (a "camera").
You can open the device with any reasonable spec, and if the hardware can't directly support it, it will convert data seamlessly to the requested format. This might incur overhead, including scaling of image data.
If you would rather accept whatever format the device offers, you can pass a NULL spec here and it will choose one for you (and you can use SDL_Surface's conversion/scaling functions directly if necessary).
You can call SDL_GetCameraFormat() to get the actual data format if passing a NULL spec here. You can see the exact specs a device can support without conversion with SDL_GetCameraSupportedFormats().
SDL will not attempt to emulate framerate; it will try to set the hardware to the rate closest to the requested speed, but it won't attempt to limit or duplicate frames artificially; call SDL_GetCameraFormat() to see the actual framerate of the opened the device, and check your timestamps if this is crucial to your app!
Note that the camera is not usable until the user approves its use! On some platforms, the operating system will prompt the user to permit access to the camera, and they can choose Yes or No at that point. Until they do, the camera will not be usable. The app should either wait for an SDL_EVENT_CAMERA_DEVICE_APPROVED (or SDL_EVENT_CAMERA_DEVICE_DENIED) event, or poll SDL_GetCameraPermissionState() occasionally until it returns non-zero. On platforms that don't require explicit user approval (and perhaps in places where the user previously permitted access), the approval event might come immediately, but it might come seconds, minutes, or hours later!
Parameters
instance_id the camera device instance ID.
spec the desired format for data the device will provide. Can be NULL.
Returns
an SDL_Camera object or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCameras
SDL_GetCameraFormat
{
    SDL_Camera *device = ObtainPhysicalCamera(instance_id);
    if (!device) {
        return NULL;
    }
    if (device->hidden != NULL) {
        ReleaseCamera(device);
        SDL_SetError("Camera already opened");  // we may remove this limitation at some point.
        return NULL;
    }
    SDL_SetAtomicInt(&device->shutdown, 0);
    // These start with the backend's implementation, but we might swap them out with zombie versions later.
    device->WaitDevice = camera_driver.impl.WaitDevice;
    device->AcquireFrame = camera_driver.impl.AcquireFrame;
    device->ReleaseFrame = camera_driver.impl.ReleaseFrame;
    SDL_CameraSpec closest;
    ChooseBestCameraSpec(device, spec, &closest);
    #if DEBUG_CAMERA
    SDL_Log("CAMERA: App wanted [(%dx%d) fmt=%s framerate=%d/%d], chose [(%dx%d) fmt=%s framerate=%d/%d]",
            spec ? spec->width : -1, spec ? spec->height : -1, spec ? SDL_GetPixelFormatName(spec->format) : "(null)", spec ? spec->framerate_numerator : -1, spec ? spec->framerate_denominator : -1,
            closest.width, closest.height, SDL_GetPixelFormatName(closest.format), closest.framerate_numerator, closest.framerate_denominator);
    #endif
    if (!camera_driver.impl.OpenDevice(device, &closest)) {
        ClosePhysicalCamera(device);  // in case anything is half-initialized.
        ReleaseCamera(device);
        return NULL;
    }
    SDL_copyp(&device->spec, spec ? spec : &closest);
    SDL_copyp(&device->actual_spec, &closest);
    // SDL_PIXELFORMAT_UNKNOWN here is taken as a signal that the backend
    //  doesn't know its format yet (Emscripten waiting for user permission,
    //  in this case), and the backend will call SDL_PrepareCameraSurfaces()
    //  itself, later but before the app is allowed to acquire images.
    if (closest.format != SDL_PIXELFORMAT_UNKNOWN) {
        if (!SDL_PrepareCameraSurfaces(device)) {
            ClosePhysicalCamera(device);
            ReleaseCamera(device);
            return NULL;
        }
    }
    device->drop_frames = 1;
    // Start the camera thread if necessary
    if (!camera_driver.impl.ProvidesOwnCallbackThread) {
        char threadname[64];
        SDL_GetCameraThreadName(device, threadname, sizeof (threadname));
        device->thread = SDL_CreateThread(CameraThread, threadname, device);
        if (!device->thread) {
            ClosePhysicalCamera(device);
            ReleaseCamera(device);
            SDL_SetError("Couldn't create camera thread");
            return NULL;
        }
    }
    ReleaseCamera(device);  // unlock, we're good to go!
    return device;  // currently there's no separation between physical and logical device.
}
References SDL_Camera::AcquireFrame, SDL_Camera::actual_spec, camera_driver, CameraThread(), ChooseBestCameraSpec(), ClosePhysicalCamera(), SDL_Camera::drop_frames, SDL_CameraSpec::format, SDL_CameraSpec::framerate_denominator, SDL_CameraSpec::framerate_numerator, SDL_CameraSpec::height, SDL_Camera::hidden, NULL, ObtainPhysicalCamera(), ReleaseCamera(), SDL_Camera::ReleaseFrame, SDL_copyp, SDL_CreateThread, SDL_GetCameraThreadName(), SDL_GetPixelFormatName(), SDL_Log(), SDL_PIXELFORMAT_UNKNOWN, SDL_PrepareCameraSurfaces(), SDL_SetAtomicInt(), SDL_SetError(), SDL_Camera::shutdown, SDL_Camera::spec, SDL_Camera::thread, SDL_Camera::WaitDevice, and SDL_CameraSpec::width.
SDL_ReleaseCameraFrame()
SDL_DECLSPEC void SDLCALL SDL_ReleaseCameraFrame (SDL_Camera * camera, SDL_Surface * frame) extern
Release a frame of video acquired from a camera.
Let the back-end re-use the internal buffer for camera.
This function must be called only on surface objects returned by SDL_AcquireCameraFrame(). This function should be called as quickly as possible after acquisition, as SDL keeps a small FIFO queue of surfaces for video frames; if surfaces aren't released in a timely manner, SDL may drop upcoming video frames from the camera.
If the app needs to keep the surface for a significant time, they should make a copy of it and release the original.
The app should not use the surface again after calling this function; assume the surface is freed and the pointer is invalid.
Parameters
camera opened camera device.
frame the video frame surface to release.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AcquireCameraFrame
{
    if (!camera || !frame) {
        return;
    }
    SDL_Camera *device = camera;  // currently there's no separation between physical and logical device.
    ObtainPhysicalCameraObj(device);
    SurfaceList *slistprev = &device->app_held_output_surfaces;
    SurfaceList *slist;
    for (slist = slistprev->next; slist != NULL; slist = slist->next) {
        if (slist->surface == frame) {
            break;
        }
        slistprev = slist;
    }
    if (!slist) {
        ReleaseCamera(device);
        return;
    }
    // this pointer was owned by the backend (DMA memory or whatever), clear it out.
    if (!device->needs_conversion && !device->needs_scaling) {
        device->ReleaseFrame(device, frame);
        frame->pixels = NULL;
        frame->pitch = 0;
    }
    slist->timestampNS = 0;
    // remove from app_held list...
    slistprev->next = slist->next;
    // insert at front of empty list (and we'll use it first when we need to fill a new frame).
    slist->next = device->empty_output_surfaces.next;
    device->empty_output_surfaces.next = slist;
    ReleaseCamera(device);
}
References SDL_Camera::app_held_output_surfaces, SDL_Camera::empty_output_surfaces, SDL_Camera::needs_conversion, SDL_Camera::needs_scaling, SurfaceList::next, NULL, ObtainPhysicalCameraObj(), SDL_Surface::pitch, SDL_Surface::pixels, ReleaseCamera(), SDL_Camera::ReleaseFrame, SurfaceList::surface, and SurfaceList::timestampNS.