SDL3: SDL-main/src/audio/SDL_sysaudio.h File Reference
SDL_sysaudio.h File Reference
#include "SDL_internal.h"
Data Structures
struct AudioBootStrap
struct SDL_AudioDevice
struct SDL_AudioDriver
struct SDL_AudioDriverImpl
struct SDL_AudioStream
struct SDL_LogicalAudioDevice
struct SDL_PendingAudioDeviceEvent
Macros
#define DEBUG_AUDIO_CONVERT 0
#define DEBUG_AUDIOSTREAM 0
#define DEFAULT_AUDIO_PLAYBACK_CHANNELS 2
#define DEFAULT_AUDIO_PLAYBACK_FORMAT SDL_AUDIO_S16
#define DEFAULT_AUDIO_PLAYBACK_FREQUENCY 44100
#define DEFAULT_AUDIO_RECORDING_CHANNELS 1
#define DEFAULT_AUDIO_RECORDING_FORMAT SDL_AUDIO_S16
#define DEFAULT_AUDIO_RECORDING_FREQUENCY 44100
#define DEFAULT_PLAYBACK_DEVNAME "System audio playback device"
#define DEFAULT_RECORDING_DEVNAME "System audio recording device"
#define LOG_DEBUG_AUDIO_CONVERT(from, to)
#define SDL_MAX_CHANNELMAP_CHANNELS 8
Typedefs
typedef struct AudioBootStrap AudioBootStrap
typedef struct SDL_AudioDevice SDL_AudioDevice
typedef struct SDL_AudioDriver SDL_AudioDriver
typedef struct SDL_AudioDriverImpl SDL_AudioDriverImpl
typedef struct SDL_LogicalAudioDevice SDL_LogicalAudioDevice
typedef struct SDL_PendingAudioDeviceEvent SDL_PendingAudioDeviceEvent
Functions
void ConvertAudio (int num_frames, const void *src, SDL_AudioFormat src_format, int src_channels, const int *src_map, void *dst, SDL_AudioFormat dst_format, int dst_channels, const int *dst_map, void *scratch, float gain)
void ConvertAudioFromFloat (void *dst, const float *src, int num_samples, SDL_AudioFormat dst_fmt)
void ConvertAudioSwapEndian (void *dst, const void *src, int num_samples, int bitsize)
void ConvertAudioToFloat (float *dst, const void *src, int num_samples, SDL_AudioFormat src_fmt)
void OnAudioStreamCreated (SDL_AudioStream *stream)
void OnAudioStreamDestroy (SDL_AudioStream *stream)
void RefPhysicalAudioDevice (SDL_AudioDevice *device)
SDL_AudioDevice * SDL_AddAudioDevice (bool recording, const char *name, const SDL_AudioSpec *spec, void *handle)
bool SDL_AudioChannelMapsEqual (int channels, const int *channel_map_a, const int *channel_map_b)
void SDL_AudioDeviceDisconnected (SDL_AudioDevice *device)
bool SDL_AudioDeviceFormatChanged (SDL_AudioDevice *device, const SDL_AudioSpec *newspec, int new_sample_frames)
bool SDL_AudioDeviceFormatChangedAlreadyLocked (SDL_AudioDevice *device, const SDL_AudioSpec *newspec, int new_sample_frames)
bool SDL_AudioSpecsEqual (const SDL_AudioSpec *a, const SDL_AudioSpec *b, const int *channel_map_a, const int *channel_map_b)
void SDL_AudioThreadFinalize (SDL_AudioDevice *device)
int * SDL_ChannelMapDup (const int *origchmap, int channels)
bool SDL_ChannelMapIsBogus (const int *map, int channels)
bool SDL_ChannelMapIsDefault (const int *map, int channels)
void SDL_ChooseAudioConverters (void)
const SDL_AudioFormat * SDL_ClosestAudioFormats (SDL_AudioFormat format)
void SDL_DefaultAudioDeviceChanged (SDL_AudioDevice *new_default_device)
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByCallback (bool(*callback)(SDL_AudioDevice *device, void *userdata), void *userdata)
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByHandle (void *handle)
int SDL_GetAudioStreamDataAdjustGain (SDL_AudioStream *stream, void *voidbuf, int len, float extra_gain)
char * SDL_GetAudioThreadName (SDL_AudioDevice *device, char *buf, size_t buflen)
int SDL_GetDefaultSampleFramesFromFreq (const int freq)
bool SDL_InitAudio (const char *driver_name)
bool SDL_PlaybackAudioThreadIterate (SDL_AudioDevice *device)
void SDL_PlaybackAudioThreadSetup (SDL_AudioDevice *device)
void SDL_PlaybackAudioThreadShutdown (SDL_AudioDevice *device)
void SDL_QuitAudio (void)
bool SDL_RecordingAudioThreadIterate (SDL_AudioDevice *device)
void SDL_RecordingAudioThreadSetup (SDL_AudioDevice *device)
void SDL_RecordingAudioThreadShutdown (SDL_AudioDevice *device)
void SDL_SetupAudioResampler (void)
void SDL_UpdatedAudioDeviceFormat (SDL_AudioDevice *device)
bool SetAudioStreamChannelMap (SDL_AudioStream *stream, const SDL_AudioSpec *spec, int **stream_chmap, const int *chmap, int channels, int isinput)
void UnrefPhysicalAudioDevice (SDL_AudioDevice *device)
Variables
AudioBootStrap AAUDIO_bootstrap
AudioBootStrap ALSA_bootstrap
AudioBootStrap COREAUDIO_bootstrap
AudioBootStrap DISKAUDIO_bootstrap
AudioBootStrap DSOUND_bootstrap
AudioBootStrap DSP_bootstrap
AudioBootStrap DUMMYAUDIO_bootstrap
AudioBootStrap EMSCRIPTENAUDIO_bootstrap
AudioBootStrap HAIKUAUDIO_bootstrap
AudioBootStrap JACK_bootstrap
AudioBootStrap N3DSAUDIO_bootstrap
AudioBootStrap NETBSDAUDIO_bootstrap
AudioBootStrap NGAGEAUDIO_bootstrap
AudioBootStrap OPENSLES_bootstrap
AudioBootStrap PIPEWIRE_bootstrap
AudioBootStrap PIPEWIRE_PREFERRED_bootstrap
AudioBootStrap PRIVATEAUDIO_bootstrap
AudioBootStrap PS2AUDIO_bootstrap
AudioBootStrap PSPAUDIO_bootstrap
AudioBootStrap PULSEAUDIO_bootstrap
AudioBootStrap QSAAUDIO_bootstrap
AudioBootStrap SNDIO_bootstrap
AudioBootStrap VITAAUD_bootstrap
AudioBootStrap WASAPI_bootstrap
AudioBootStrap WINMM_bootstrap
Macro Definition Documentation
DEBUG_AUDIO_CONVERT
#define DEBUG_AUDIO_CONVERT 0
DEBUG_AUDIOSTREAM
#define DEBUG_AUDIOSTREAM 0
DEFAULT_AUDIO_PLAYBACK_CHANNELS
#define DEFAULT_AUDIO_PLAYBACK_CHANNELS 2
Referenced by OpenPhysicalAudioDevice(), PrepareAudioFormat(), and SDL_AddAudioDevice().
DEFAULT_AUDIO_PLAYBACK_FORMAT
#define DEFAULT_AUDIO_PLAYBACK_FORMAT SDL_AUDIO_S16
Referenced by OpenPhysicalAudioDevice(), PrepareAudioFormat(), and SDL_AddAudioDevice().
DEFAULT_AUDIO_PLAYBACK_FREQUENCY
#define DEFAULT_AUDIO_PLAYBACK_FREQUENCY 44100
Referenced by OpenPhysicalAudioDevice(), PrepareAudioFormat(), and SDL_AddAudioDevice().
DEFAULT_AUDIO_RECORDING_CHANNELS
#define DEFAULT_AUDIO_RECORDING_CHANNELS 1
Referenced by OpenPhysicalAudioDevice(), PrepareAudioFormat(), and SDL_AddAudioDevice().
DEFAULT_AUDIO_RECORDING_FORMAT
#define DEFAULT_AUDIO_RECORDING_FORMAT SDL_AUDIO_S16
Referenced by OpenPhysicalAudioDevice(), PrepareAudioFormat(), and SDL_AddAudioDevice().
DEFAULT_AUDIO_RECORDING_FREQUENCY
#define DEFAULT_AUDIO_RECORDING_FREQUENCY 44100
Referenced by OpenPhysicalAudioDevice(), PrepareAudioFormat(), and SDL_AddAudioDevice().
DEFAULT_PLAYBACK_DEVNAME
#define DEFAULT_PLAYBACK_DEVNAME "System audio playback device"
Referenced by SDL_AudioDetectDevices_Default().
DEFAULT_RECORDING_DEVNAME
#define DEFAULT_RECORDING_DEVNAME "System audio recording device"
Referenced by SDL_AudioDetectDevices_Default().
LOG_DEBUG_AUDIO_CONVERT
#define LOG_DEBUG_AUDIO_CONVERT (from, to)
Referenced by SDL_Convert21To41(), SDL_Convert21To51(), SDL_Convert21To61(), SDL_Convert21To71(), SDL_Convert21ToMono(), SDL_Convert21ToQuad(), SDL_Convert21ToStereo(), SDL_Convert41To21(), SDL_Convert41To51(), SDL_Convert41To61(), SDL_Convert41To71(), SDL_Convert41ToMono(), SDL_Convert41ToQuad(), SDL_Convert41ToStereo(), SDL_Convert51To21(), SDL_Convert51To41(), SDL_Convert51To61(), SDL_Convert51To71(), SDL_Convert51ToMono(), SDL_Convert51ToQuad(), SDL_Convert51ToStereo(), SDL_Convert61To21(), SDL_Convert61To41(), SDL_Convert61To51(), SDL_Convert61To71(), SDL_Convert61ToMono(), SDL_Convert61ToQuad(), SDL_Convert61ToStereo(), SDL_Convert71To21(), SDL_Convert71To41(), SDL_Convert71To51(), SDL_Convert71To61(), SDL_Convert71ToMono(), SDL_Convert71ToQuad(), SDL_Convert71ToStereo(), SDL_Convert_F32_to_S16_Scalar(), SDL_Convert_F32_to_S32_Scalar(), SDL_Convert_F32_to_S8_Scalar(), SDL_Convert_F32_to_U8_Scalar(), SDL_Convert_S16_to_F32_Scalar(), SDL_Convert_S32_to_F32_Scalar(), SDL_Convert_S8_to_F32_Scalar(), SDL_Convert_U8_to_F32_Scalar(), SDL_ConvertMonoTo21(), SDL_ConvertMonoTo41(), SDL_ConvertMonoTo51(), SDL_ConvertMonoTo61(), SDL_ConvertMonoTo71(), SDL_ConvertMonoToQuad(), SDL_ConvertMonoToStereo(), SDL_ConvertQuadTo21(), SDL_ConvertQuadTo41(), SDL_ConvertQuadTo51(), SDL_ConvertQuadTo61(), SDL_ConvertQuadTo71(), SDL_ConvertQuadToMono(), SDL_ConvertQuadToStereo(), SDL_ConvertStereoTo21(), SDL_ConvertStereoTo41(), SDL_ConvertStereoTo51(), SDL_ConvertStereoTo61(), SDL_ConvertStereoTo71(), SDL_ConvertStereoToMono(), and SDL_ConvertStereoToQuad().
SDL_MAX_CHANNELMAP_CHANNELS
#define SDL_MAX_CHANNELMAP_CHANNELS 8
Referenced by SDL_PutAudioStreamPlanarData().
Typedef Documentation
AudioBootStrap
typedef struct AudioBootStrap AudioBootStrap
SDL_AudioDevice
typedef struct SDL_AudioDevice SDL_AudioDevice
SDL_AudioDriver
typedef struct SDL_AudioDriver SDL_AudioDriver
SDL_AudioDriverImpl
typedef struct SDL_AudioDriverImpl SDL_AudioDriverImpl
SDL_LogicalAudioDevice
typedef struct SDL_LogicalAudioDevice SDL_LogicalAudioDevice
SDL_PendingAudioDeviceEvent
typedef struct SDL_PendingAudioDeviceEvent SDL_PendingAudioDeviceEvent
Function Documentation
ConvertAudio()
void ConvertAudio (int num_frames, const void * src, SDL_AudioFormat src_format, int src_channels, const int * src_map, void * dst, SDL_AudioFormat dst_format, int dst_channels, const int * dst_map, void * scratch, float gain) extern
{
    SDL_assert(src != NULL);
    SDL_assert(dst != NULL);
    SDL_assert(SDL_IsSupportedAudioFormat(src_format));
    SDL_assert(SDL_IsSupportedAudioFormat(dst_format));
    SDL_assert(SDL_IsSupportedChannelCount(src_channels));
    SDL_assert(SDL_IsSupportedChannelCount(dst_channels));
    if (!num_frames) {
        return;  // no data to convert, quit.
    }
#if DEBUG_AUDIO_CONVERT
    SDL_Log("SDL_AUDIO_CONVERT: Convert format %04x->%04x, channels %u->%u", src_format, dst_format, src_channels, dst_channels);
#endif
    const int dst_bitsize = (int) SDL_AUDIO_BITSIZE(dst_format);
    const int dst_sample_frame_size = (dst_bitsize / 8) * dst_channels;
    const bool chmaps_match = (src_channels == dst_channels) && SDL_AudioChannelMapsEqual(src_channels, src_map, dst_map);
    if (chmaps_match) {
        src_map = dst_map = NULL;  // NULL both these out so we don't do any unnecessary swizzling.
    }
    /* Type conversion goes like this now:
        - swizzle through source channel map to "standard" layout.
        - byteswap to CPU native format first if necessary.
        - convert to native Float32 if necessary.
        - change channel count if necessary.
        - convert to final data format.
        - byteswap back to foreign format if necessary.
        - swizzle through dest channel map from "standard" layout.
       The expectation is we can process data faster in float32
       (possibly with SIMD), and making several passes over the same
       buffer is likely to be CPU cache-friendly, avoiding the
       biggest performance hit in modern times. Previously we had
       (script-generated) custom converters for every data type and
       it was a bloat on SDL compile times and final library size. */
    // swizzle input to "standard" format if necessary.
    if (src_map) {
        void *buf = scratch ? scratch : dst;  // use scratch if available, since it has to be big enough to hold src, unless it's NULL, then dst has to be.
        SwizzleAudio(num_frames, buf, src, src_channels, src_map, src_format);
        src = buf;
    }
    // see if we can skip float conversion entirely.
    if ((src_channels == dst_channels) && (gain == 1.0f)) {
        if (src_format == dst_format) {
            // nothing to do, we're already in the right format, just copy it over if necessary.
            if (dst_map) {
                SwizzleAudio(num_frames, dst, src, dst_channels, dst_map, dst_format);
            } else if (src != dst) {
                SDL_memcpy(dst, src, num_frames * dst_sample_frame_size);
            }
            return;
        }
        // just a byteswap needed?
        if ((src_format ^ dst_format) == SDL_AUDIO_MASK_BIG_ENDIAN) {
            if (dst_map) {  // do this first, in case we duplicate channels, we can avoid an extra copy if src != dst.
                SwizzleAudio(num_frames, dst, src, dst_channels, dst_map, dst_format);
                src = dst;
            }
            ConvertAudioSwapEndian(dst, src, num_frames * dst_channels, dst_bitsize);
            return;  // all done.
        }
    }
    if (!scratch) {
        scratch = dst;
    }
    const bool srcconvert = src_format != SDL_AUDIO_F32;
    const bool channelconvert = src_channels != dst_channels;
    const bool dstconvert = dst_format != SDL_AUDIO_F32;
    // get us to float format.
    if (srcconvert) {
        void *buf = (channelconvert || dstconvert) ? scratch : dst;
        ConvertAudioToFloat((float *) buf, src, num_frames * src_channels, src_format);
        src = buf;
    }
    // Gain adjustment
    if (gain != 1.0f) {
        float *buf = (float *)((channelconvert || dstconvert) ? scratch : dst);
        const int total_samples = num_frames * src_channels;
        if (src == buf) {
            for (int i = 0; i < total_samples; i++) {
                buf[i] *= gain;
            }
        } else {
            const float *fsrc = (const float *)src;
            for (int i = 0; i < total_samples; i++) {
                buf[i] = fsrc[i] * gain;
            }
        }
        src = buf;
    }
    // Channel conversion
    if (channelconvert) {
        SDL_AudioChannelConverter channel_converter;
        SDL_AudioChannelConverter override = NULL;
        // SDL_IsSupportedChannelCount should have caught these asserts, or we added a new format and forgot to update the table.
        SDL_assert(src_channels <= SDL_arraysize(channel_converters));
        SDL_assert(dst_channels <= SDL_arraysize(channel_converters[0]));
        channel_converter = channel_converters[src_channels - 1][dst_channels - 1];
        SDL_assert(channel_converter != NULL);
        // swap in some SIMD versions for a few of these.
        if (channel_converter == SDL_ConvertStereoToMono) {
            #ifdef SDL_SSE3_INTRINSICS
            if (!override && SDL_HasSSE3()) { override = SDL_ConvertStereoToMono_SSE3; }
            #endif
        } else if (channel_converter == SDL_ConvertMonoToStereo) {
            #ifdef SDL_SSE_INTRINSICS
            if (!override && SDL_HasSSE()) { override = SDL_ConvertMonoToStereo_SSE; }
            #endif
        }
        if (override) {
            channel_converter = override;
        }
        void *buf = dstconvert ? scratch : dst;
        channel_converter((float *) buf, (const float *) src, num_frames);
        src = buf;
    }
    // Resampling is not done in here. SDL_AudioStream handles that.
    // Move to final data type.
    if (dstconvert) {
        ConvertAudioFromFloat(dst, (const float *) src, num_frames * dst_channels, dst_format);
        src = dst;
    }
    SDL_assert(src == dst);  // if we got here, we _had_ to have done _something_. Otherwise, we should have memcpy'd!
    if (dst_map) {
        SwizzleAudio(num_frames, dst, src, dst_channels, dst_map, dst_format);
    }
}
References channel_converters, ConvertAudioFromFloat(), ConvertAudioSwapEndian(), ConvertAudioToFloat(), NULL, SDL_arraysize, SDL_assert, SDL_AUDIO_BITSIZE, SDL_AUDIO_F32, SDL_AUDIO_MASK_BIG_ENDIAN, SDL_AudioChannelMapsEqual(), SDL_ConvertMonoToStereo(), SDL_ConvertStereoToMono(), SDL_HasSSE(), SDL_HasSSE3(), SDL_IsSupportedAudioFormat(), SDL_IsSupportedChannelCount(), SDL_Log(), SDL_memcpy, and SwizzleAudio().
Referenced by GetAudioStreamDataInternal(), SDL_PlaybackAudioThreadIterate(), SDL_ReadFromAudioQueue(), and SDL_RecordingAudioThreadIterate().
ConvertAudioFromFloat()
void ConvertAudioFromFloat (void * dst, const float * src, int num_samples, SDL_AudioFormat dst_fmt) extern
{
    switch (dst_fmt) {
        case SDL_AUDIO_S8:
            SDL_Convert_F32_to_S8((Sint8 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_U8:
            SDL_Convert_F32_to_U8((Uint8 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_S16:
            SDL_Convert_F32_to_S16((Sint16 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_S16 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_F32_to_S16((Sint16 *) dst, src, num_samples);
            SDL_Convert_Swap16((Uint16 *)dst, (const Uint16 *)dst, num_samples);
            break;
        case SDL_AUDIO_S32:
            SDL_Convert_F32_to_S32((Sint32 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_S32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_F32_to_S32((Sint32 *) dst, src, num_samples);
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)dst, num_samples);
            break;
        case SDL_AUDIO_F32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples);
            break;
        default: SDL_assert(!"Unexpected audio format!"); break;
    }
}
References SDL_assert, SDL_AUDIO_F32, SDL_AUDIO_MASK_BIG_ENDIAN, SDL_AUDIO_S16, SDL_AUDIO_S32, SDL_AUDIO_S8, SDL_AUDIO_U8, SDL_Convert_F32_to_S16, SDL_Convert_F32_to_S32, SDL_Convert_F32_to_S8, SDL_Convert_F32_to_U8, SDL_Convert_Swap16, and SDL_Convert_Swap32.
Referenced by ConvertAudio().
ConvertAudioSwapEndian()
void ConvertAudioSwapEndian (void * dst, const void * src, int num_samples, int bitsize) extern
{
    switch (bitsize) {
        case 16: SDL_Convert_Swap16((Uint16 *)dst, (const Uint16 *)src, num_samples); break;
        case 32: SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples); break;
        default: SDL_assert(!"Unexpected audio format!"); break;
    }
}
References SDL_assert, SDL_Convert_Swap16, and SDL_Convert_Swap32.
Referenced by ConvertAudio().
ConvertAudioToFloat()
void ConvertAudioToFloat (float * dst, const void * src, int num_samples, SDL_AudioFormat src_fmt) extern
{
    switch (src_fmt) {
        case SDL_AUDIO_S8:
            SDL_Convert_S8_to_F32(dst, (const Sint8 *) src, num_samples);
            break;
        case SDL_AUDIO_U8:
            SDL_Convert_U8_to_F32(dst, (const Uint8 *) src, num_samples);
            break;
        case SDL_AUDIO_S16:
            SDL_Convert_S16_to_F32(dst, (const Sint16 *) src, num_samples);
            break;
        case SDL_AUDIO_S16 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap16((Uint16 *)dst, (const Uint16 *)src, num_samples);
            SDL_Convert_S16_to_F32(dst, (const Sint16 *) dst, num_samples);
            break;
        case SDL_AUDIO_S32:
            SDL_Convert_S32_to_F32(dst, (const Sint32 *) src, num_samples);
            break;
        case SDL_AUDIO_S32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples);
            SDL_Convert_S32_to_F32(dst, (const Sint32 *) dst, num_samples);
            break;
        case SDL_AUDIO_F32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples);
            break;
        default: SDL_assert(!"Unexpected audio format!"); break;
    }
}
References SDL_assert, SDL_AUDIO_F32, SDL_AUDIO_MASK_BIG_ENDIAN, SDL_AUDIO_S16, SDL_AUDIO_S32, SDL_AUDIO_S8, SDL_AUDIO_U8, SDL_Convert_S16_to_F32, SDL_Convert_S32_to_F32, SDL_Convert_S8_to_F32, SDL_Convert_Swap16, SDL_Convert_Swap32, and SDL_Convert_U8_to_F32.
Referenced by ConvertAudio().
OnAudioStreamCreated()
void OnAudioStreamCreated (SDL_AudioStream * stream) extern
{
    SDL_assert(stream != NULL);
    // NOTE that you can create an audio stream without initializing the audio subsystem,
    //  but it will not be automatically destroyed during a later call to SDL_Quit!
    //  You must explicitly destroy it yourself!
    if (current_audio.device_hash_lock) {
        // this isn't really part of the "device list" but it's a convenient lock to use here.
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        if (current_audio.existing_streams) {
            current_audio.existing_streams->prev = stream;
        }
        stream->prev = NULL;
        stream->next = current_audio.existing_streams;
        current_audio.existing_streams = stream;
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
}
References current_audio, NULL, SDL_assert, SDL_LockRWLockForWriting(), and SDL_UnlockRWLock().
Referenced by SDL_CreateAudioStream().
OnAudioStreamDestroy()
void OnAudioStreamDestroy (SDL_AudioStream * stream) extern
{
    SDL_assert(stream != NULL);
    // NOTE that you can create an audio stream without initializing the audio subsystem,
    //  but it will not be automatically destroyed during a later call to SDL_Quit!
    //  You must explicitly destroy it yourself!
    if (current_audio.device_hash_lock) {
        // this isn't really part of the "device list" but it's a convenient lock to use here.
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        if (stream->prev) {
            stream->prev->next = stream->next;
        }
        if (stream->next) {
            stream->next->prev = stream->prev;
        }
        if (stream == current_audio.existing_streams) {
            current_audio.existing_streams = stream->next;
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
}
References current_audio, NULL, SDL_assert, SDL_LockRWLockForWriting(), and SDL_UnlockRWLock().
Referenced by SDL_DestroyAudioStream().
RefPhysicalAudioDevice()
void RefPhysicalAudioDevice (SDL_AudioDevice * device) extern
{
    SDL_AtomicIncRef(&device->refcount);
}
References SDL_AudioDevice::refcount, and SDL_AtomicIncRef.
Referenced by CreatePhysicalAudioDevice(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), SDL_DefaultAudioDeviceChanged(), SDL_InitAudio(), and SDL_OpenAudioDevice().
SDL_AddAudioDevice()
SDL_AudioDevice * SDL_AddAudioDevice (bool recording, const char * name, const SDL_AudioSpec * spec, void * handle) extern
{
    // device handles MUST be unique! If the target reuses the same handle for hardware with both recording and playback interfaces, wrap it in a pointer you SDL_malloc'd!
    SDL_assert(SDL_FindPhysicalAudioDeviceByHandle(handle) == NULL);
    const SDL_AudioFormat default_format = recording ? DEFAULT_AUDIO_RECORDING_FORMAT : DEFAULT_AUDIO_PLAYBACK_FORMAT;
    const int default_channels = recording ? DEFAULT_AUDIO_RECORDING_CHANNELS : DEFAULT_AUDIO_PLAYBACK_CHANNELS;
    const int default_freq = recording ? DEFAULT_AUDIO_RECORDING_FREQUENCY : DEFAULT_AUDIO_PLAYBACK_FREQUENCY;
    SDL_AudioSpec spec;
    SDL_zero(spec);
    if (!inspec) {
        spec.format = default_format;
        spec.channels = default_channels;
        spec.freq = default_freq;
    } else {
        spec.format = (inspec->format != 0) ? inspec->format : default_format;
        spec.channels = (inspec->channels != 0) ? inspec->channels : default_channels;
        spec.freq = (inspec->freq != 0) ? inspec->freq : default_freq;
    }
    SDL_AudioDevice *device = recording ? CreateAudioRecordingDevice(name, &spec, handle) : CreateAudioPlaybackDevice(name, &spec, handle);
    // Add a device add event to the pending list, to be pushed when the event queue is pumped (away from any of our internal threads).
    if (device) {
        SDL_PendingAudioDeviceEvent *p = (SDL_PendingAudioDeviceEvent *) SDL_malloc(sizeof (SDL_PendingAudioDeviceEvent));
        if (p) {  // if allocation fails, you won't get an event, but we can't help that.
            p->type = SDL_EVENT_AUDIO_DEVICE_ADDED;
            p->devid = device->instance_id;
            p->next = NULL;
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            SDL_assert(current_audio.pending_events_tail != NULL);
            SDL_assert(current_audio.pending_events_tail->next == NULL);
            current_audio.pending_events_tail->next = p;
            current_audio.pending_events_tail = p;
            SDL_UnlockRWLock(current_audio.device_hash_lock);
        }
    }
    return device;
}
References SDL_AudioSpec::channels, CreateAudioPlaybackDevice(), CreateAudioRecordingDevice(), current_audio, DEFAULT_AUDIO_PLAYBACK_CHANNELS, DEFAULT_AUDIO_PLAYBACK_FORMAT, DEFAULT_AUDIO_PLAYBACK_FREQUENCY, DEFAULT_AUDIO_RECORDING_CHANNELS, DEFAULT_AUDIO_RECORDING_FORMAT, DEFAULT_AUDIO_RECORDING_FREQUENCY, SDL_PendingAudioDeviceEvent::devid, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::instance_id, SDL_PendingAudioDeviceEvent::next, NULL, SDL_assert, SDL_EVENT_AUDIO_DEVICE_ADDED, SDL_FindPhysicalAudioDeviceByHandle(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_UnlockRWLock(), SDL_zero, and SDL_PendingAudioDeviceEvent::type.
Referenced by SDL_AudioDetectDevices_Default().
SDL_AudioChannelMapsEqual()
bool SDL_AudioChannelMapsEqual (int channels, const int * channel_map_a, const int * channel_map_b) extern
{
    if (channel_map_a == channel_map_b) {
        return true;
    } else if ((channel_map_a != NULL) != (channel_map_b != NULL)) {
        return false;
    } else if (channel_map_a && (SDL_memcmp(channel_map_a, channel_map_b, sizeof (*channel_map_a) * channels) != 0)) {
        return false;
    }
    return true;
}
References NULL, and SDL_memcmp().
Referenced by ConvertAudio(), SDL_PlaybackAudioThreadIterate(), and SDL_RecordingAudioThreadIterate().
SDL_AudioDeviceDisconnected()
void SDL_AudioDeviceDisconnected (SDL_AudioDevice * device) extern
{
    if (!device) {
        return;
    }
    // Save off removal info in a list so we can send events for each, next
    //  time the event queue pumps, in case something tries to close a device
    //  from an event filter, as this would risk deadlocks and other disasters
    //  if done from the device thread.
    SDL_PendingAudioDeviceEvent pending;
    pending.next = NULL;
    SDL_PendingAudioDeviceEvent *pending_tail = &pending;
    ObtainPhysicalAudioDeviceObj(device);
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    const SDL_AudioDeviceID devid = device->instance_id;
    const bool is_default_device = ((devid == current_audio.default_playback_device_id) || (devid == current_audio.default_recording_device_id));
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    const bool first_disconnect = SDL_CompareAndSwapAtomicInt(&device->zombie, 0, 1);
    if (first_disconnect) {   // if already disconnected this device, don't do it twice.
        // Swap in "Zombie" versions of the usual platform interfaces, so the device will keep
        // making progress until the app closes it. Otherwise, streams might continue to
        // accumulate waste data that never drains, apps that depend on audio callbacks to
        // progress will freeze, etc.
        device->WaitDevice = ZombieWaitDevice;
        device->GetDeviceBuf = ZombieGetDeviceBuf;
        device->PlayDevice = ZombiePlayDevice;
        device->WaitRecordingDevice = ZombieWaitDevice;
        device->RecordDevice = ZombieRecordDevice;
        device->FlushRecording = ZombieFlushRecording;
        // on default devices, dump any logical devices that explicitly opened this device. Things that opened the system default can stay.
        // on non-default devices, dump everything.
        // (by "dump" we mean send a REMOVED event; the zombie will keep consuming audio data for these logical devices until explicitly closed.)
        for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
            if (!is_default_device || !logdev->opened_as_default) {  // if opened as a default, leave it on the zombie device for later migration.
                SDL_PendingAudioDeviceEvent *p = (SDL_PendingAudioDeviceEvent *) SDL_malloc(sizeof (SDL_PendingAudioDeviceEvent));
                if (p) {  // if this failed, no event for you, but you have deeper problems anyhow.
                    p->type = SDL_EVENT_AUDIO_DEVICE_REMOVED;
                    p->devid = logdev->instance_id;
                    p->next = NULL;
                    pending_tail->next = p;
                    pending_tail = p;
                }
            }
        }
        SDL_PendingAudioDeviceEvent *p = (SDL_PendingAudioDeviceEvent *) SDL_malloc(sizeof (SDL_PendingAudioDeviceEvent));
        if (p) {  // if this failed, no event for you, but you have deeper problems anyhow.
            p->type = SDL_EVENT_AUDIO_DEVICE_REMOVED;
            p->devid = device->instance_id;
            p->next = NULL;
            pending_tail->next = p;
            pending_tail = p;
        }
    }
    ReleaseAudioDevice(device);
    if (first_disconnect) {
        if (pending.next) {  // NULL if event is disabled or disaster struck.
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            SDL_assert(current_audio.pending_events_tail != NULL);
            SDL_assert(current_audio.pending_events_tail->next == NULL);
            current_audio.pending_events_tail->next = pending.next;
            current_audio.pending_events_tail = pending_tail;
            SDL_UnlockRWLock(current_audio.device_hash_lock);
        }
        UnrefPhysicalAudioDevice(device);
    }
}
References current_audio, SDL_PendingAudioDeviceEvent::devid, SDL_AudioDevice::FlushRecording, SDL_AudioDevice::GetDeviceBuf, SDL_AudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, SDL_PendingAudioDeviceEvent::next, NULL, ObtainPhysicalAudioDeviceObj(), SDL_AudioDevice::PlayDevice, SDL_AudioDevice::RecordDevice, ReleaseAudioDevice(), SDL_assert, SDL_CompareAndSwapAtomicInt(), SDL_EVENT_AUDIO_DEVICE_REMOVED, SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_UnlockRWLock(), SDL_PendingAudioDeviceEvent::type, UnrefPhysicalAudioDevice(), SDL_AudioDevice::WaitDevice, SDL_AudioDevice::WaitRecordingDevice, SDL_AudioDevice::zombie, ZombieFlushRecording(), ZombieGetDeviceBuf(), ZombiePlayDevice(), ZombieRecordDevice(), and ZombieWaitDevice().
Referenced by PlaybackAudioThread(), RecordingAudioThread(), SDL_PlaybackAudioThreadIterate(), and SDL_RecordingAudioThreadIterate().
SDL_AudioDeviceFormatChanged()
bool SDL_AudioDeviceFormatChanged (SDL_AudioDevice * device, const SDL_AudioSpec * newspec, int new_sample_frames) extern
{
    ObtainPhysicalAudioDeviceObj(device);
    const bool result = SDL_AudioDeviceFormatChangedAlreadyLocked(device, newspec, new_sample_frames);
    ReleaseAudioDevice(device);
    return result;
}
References ObtainPhysicalAudioDeviceObj(), ReleaseAudioDevice(), and SDL_AudioDeviceFormatChangedAlreadyLocked().
SDL_AudioDeviceFormatChangedAlreadyLocked()
bool SDL_AudioDeviceFormatChangedAlreadyLocked (SDL_AudioDevice * device, const SDL_AudioSpec * newspec, int new_sample_frames) extern
{
    const int orig_work_buffer_size = device->work_buffer_size;
    // we don't currently have any place where channel maps change from under you, but we can check that if necessary later.
    if (SDL_AudioSpecsEqual(&device->spec, newspec, NULL, NULL) && (new_sample_frames == device->sample_frames)) {
        return true;  // we're already in that format.
    }
    SDL_copyp(&device->spec, newspec);
    UpdateAudioStreamFormatsPhysical(device);
    bool kill_device = false;
    device->sample_frames = new_sample_frames;
    SDL_UpdatedAudioDeviceFormat(device);
    if (device->work_buffer && (device->work_buffer_size > orig_work_buffer_size)) {
        SDL_aligned_free(device->work_buffer);
        device->work_buffer = (Uint8 *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
        if (!device->work_buffer) {
            kill_device = true;
        }
        if (device->postmix_buffer) {
            SDL_aligned_free(device->postmix_buffer);
            device->postmix_buffer = (float *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
            if (!device->postmix_buffer) {
                kill_device = true;
            }
        }
        SDL_aligned_free(device->mix_buffer);
        device->mix_buffer = NULL;
        if (device->spec.format != SDL_AUDIO_F32) {
            device->mix_buffer = (Uint8 *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
            if (!device->mix_buffer) {
                kill_device = true;
            }
        }
    }
    // Post an event for the physical device, and each logical device on this physical device.
    if (!kill_device) {
        // Queue up events to push to the queue next time it pumps (presumably
        //  in a safer thread).
        // !!! FIXME: this duplicates some code we could probably refactor.
        SDL_PendingAudioDeviceEvent pending;
        pending.next = NULL;
        SDL_PendingAudioDeviceEvent *pending_tail = &pending;
        SDL_PendingAudioDeviceEvent *p;
        p = (SDL_PendingAudioDeviceEvent *)SDL_malloc(sizeof(SDL_PendingAudioDeviceEvent));
        if (p) { // if this failed, no event for you, but you have deeper problems anyhow.
            p->type = SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED;
            p->devid = device->instance_id;
            p->next = NULL;
            pending_tail->next = p;
            pending_tail = p;
        }
        for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
            p = (SDL_PendingAudioDeviceEvent *)SDL_malloc(sizeof(SDL_PendingAudioDeviceEvent));
            if (p) { // if this failed, no event for you, but you have deeper problems anyhow.
                p->type = SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED;
                p->devid = logdev->instance_id;
                p->next = NULL;
                pending_tail->next = p;
                pending_tail = p;
            }
        }
        if (pending.next) {
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            SDL_assert(current_audio.pending_events_tail != NULL);
            SDL_assert(current_audio.pending_events_tail->next == NULL);
            current_audio.pending_events_tail->next = pending.next;
            current_audio.pending_events_tail = pending_tail;
            SDL_UnlockRWLock(current_audio.device_hash_lock);
        }
    }
    if (kill_device) {
        return false;
    }
    return true;
}
References current_audio, SDL_PendingAudioDeviceEvent::devid, SDL_AudioSpec::format, SDL_AudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_AudioDevice::mix_buffer, SDL_LogicalAudioDevice::next, SDL_PendingAudioDeviceEvent::next, NULL, SDL_AudioDevice::postmix_buffer, SDL_AudioDevice::sample_frames, SDL_aligned_alloc(), SDL_aligned_free(), SDL_assert, SDL_AUDIO_F32, SDL_AudioSpecsEqual(), SDL_copyp, SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED, SDL_GetSIMDAlignment(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_UnlockRWLock(), SDL_UpdatedAudioDeviceFormat(), SDL_AudioDevice::spec, SDL_PendingAudioDeviceEvent::type, UpdateAudioStreamFormatsPhysical(), SDL_AudioDevice::work_buffer, and SDL_AudioDevice::work_buffer_size.
Referenced by SDL_AudioDeviceFormatChanged().
SDL_AudioSpecsEqual()
bool SDL_AudioSpecsEqual (const SDL_AudioSpec * a, const SDL_AudioSpec * b, const int * channel_map_a, const int * channel_map_b) extern
{
    if ((a->format != b->format) || (a->channels != b->channels) || (a->freq != b->freq) || ((channel_map_a != NULL) != (channel_map_b != NULL))) {
        return false;
    } else if (channel_map_a && (SDL_memcmp(channel_map_a, channel_map_b, sizeof (*channel_map_a) * a->channels) != 0)) {
        return false;
    }
    return true;
}
References SDL_AudioSpec::channels, SDL_AudioSpec::format, SDL_AudioSpec::freq, NULL, and SDL_memcmp().
Referenced by SDL_AddTrackToAudioQueue(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_DefaultAudioDeviceChanged(), SDL_PlaybackAudioThreadIterate(), SDL_WriteToAudioQueue(), and UpdateAudioStreamInputSpec().
SDL_AudioThreadFinalize()
void SDL_AudioThreadFinalize (SDL_AudioDevice * device) extern
{
}
Referenced by SDL_PlaybackAudioThreadShutdown(), and SDL_RecordingAudioThreadShutdown().
SDL_ChannelMapDup()
int * SDL_ChannelMapDup (const int * origchmap, int channels) extern
{
    const size_t chmaplen = sizeof (*origchmap) * channels;
    int *chmap = (int *)SDL_malloc(chmaplen);
    if (chmap) {
        SDL_memcpy(chmap, origchmap, chmaplen);
    }
    return chmap;
}
References SDL_malloc(), and SDL_memcpy.
Referenced by SDL_GetAudioDeviceChannelMap(), SDL_GetAudioStreamInputChannelMap(), SDL_GetAudioStreamOutputChannelMap(), and SetAudioStreamChannelMap().
SDL_ChannelMapIsBogus()
bool SDL_ChannelMapIsBogus (const int * map, int channels) extern
{
    if (chmap) {
        for (int i = 0; i < channels; i++) {
            const int mapping = chmap[i];
            if ((mapping < -1) || (mapping >= channels)) {
                return true;
            }
        }
    }
    return false;
}
Referenced by SetAudioStreamChannelMap().
SDL_ChannelMapIsDefault()
bool SDL_ChannelMapIsDefault (const int * map, int channels) extern
{
    if (chmap) {
        for (int i = 0; i < channels; i++) {
            if (chmap[i] != i) {
                return false;
            }
        }
    }
    return true;
}
Referenced by SetAudioStreamChannelMap().
SDL_ChooseAudioConverters()
void SDL_ChooseAudioConverters (void) extern
{
    static bool converters_chosen = false;
    if (converters_chosen) {
        return;
    }
#define SET_CONVERTER_FUNCS(fntype) \
    SDL_Convert_Swap16 = SDL_Convert_Swap16_##fntype; \
    SDL_Convert_Swap32 = SDL_Convert_Swap32_##fntype;
#ifdef SDL_SSE4_1_INTRINSICS
    if (SDL_HasSSE41()) {
        SET_CONVERTER_FUNCS(SSSE3);
    } else
#endif
#ifdef SDL_NEON_INTRINSICS
    if (SDL_HasNEON()) {
        SET_CONVERTER_FUNCS(NEON);
    } else
#endif
    {
        SET_CONVERTER_FUNCS(Scalar);
    }
#undef SET_CONVERTER_FUNCS
#define SET_CONVERTER_FUNCS(fntype) \
    SDL_Convert_S8_to_F32 = SDL_Convert_S8_to_F32_##fntype; \
    SDL_Convert_U8_to_F32 = SDL_Convert_U8_to_F32_##fntype; \
    SDL_Convert_S16_to_F32 = SDL_Convert_S16_to_F32_##fntype; \
    SDL_Convert_S32_to_F32 = SDL_Convert_S32_to_F32_##fntype; \
    SDL_Convert_F32_to_S8 = SDL_Convert_F32_to_S8_##fntype; \
    SDL_Convert_F32_to_U8 = SDL_Convert_F32_to_U8_##fntype; \
    SDL_Convert_F32_to_S16 = SDL_Convert_F32_to_S16_##fntype; \
    SDL_Convert_F32_to_S32 = SDL_Convert_F32_to_S32_##fntype; \
#ifdef SDL_SSE2_INTRINSICS
    if (SDL_HasSSE2()) {
        SET_CONVERTER_FUNCS(SSE2);
    } else
#endif
#ifdef SDL_NEON_INTRINSICS
    if (SDL_HasNEON()) {
        SET_CONVERTER_FUNCS(NEON);
    } else
#endif
    {
        SET_CONVERTER_FUNCS(Scalar);
    }
#undef SET_CONVERTER_FUNCS
    converters_chosen = true;
}
References SDL_HasNEON(), SDL_HasSSE2(), SDL_HasSSE41(), and SET_CONVERTER_FUNCS.
Referenced by SDL_CreateAudioStream(), and SDL_InitAudio().
SDL_ClosestAudioFormats()
const SDL_AudioFormat * SDL_ClosestAudioFormats (SDL_AudioFormat format)
{
    for (int i = 0; i < NUM_FORMATS; i++) {
        if (format_list[i][0] == format) {
            return &format_list[i][0];
        }
    }
    return &format_list[0][NUM_FORMATS]; // not found; return what looks like a list with only a zero in it.
}
References format_list, and NUM_FORMATS.
SDL_DefaultAudioDeviceChanged()
void SDL_DefaultAudioDeviceChanged (SDL_AudioDevice * new_default_device) extern
{
    if (!new_default_device) {  // !!! FIXME: what should we do in this case? Maybe all devices are lost, so there _isn't_ a default?
        return;  // uhoh.
    }
    const bool recording = new_default_device->recording;
    // change the official default over right away, so new opens will go to the new device.
    SDL_LockRWLockForWriting(current_audio.device_hash_lock);
    const SDL_AudioDeviceID current_devid = recording ? current_audio.default_recording_device_id : current_audio.default_playback_device_id;
    const bool is_already_default = (new_default_device->instance_id == current_devid);
    if (!is_already_default) {
        if (recording) {
            current_audio.default_recording_device_id = new_default_device->instance_id;
        } else {
            current_audio.default_playback_device_id = new_default_device->instance_id;
        }
    }
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    if (is_already_default) {
        return;  // this is already the default.
    }
    // Queue up events to push to the queue next time it pumps (presumably
    //  in a safer thread).
    // !!! FIXME: this duplicates some code we could probably refactor.
    SDL_PendingAudioDeviceEvent pending;
    pending.next = NULL;
    SDL_PendingAudioDeviceEvent *pending_tail = &pending;
    // Default device gets an extra ref, so it lives until a new default replaces it, even if disconnected.
    RefPhysicalAudioDevice(new_default_device);
    ObtainPhysicalAudioDeviceObj(new_default_device);
    SDL_AudioDevice *current_default_device = ObtainPhysicalAudioDevice(current_devid);
    if (current_default_device) {
        // migrate any logical devices that were opened as a default to the new physical device...
        SDL_assert(current_default_device->recording == recording);
        // See if we have to open the new physical device, and if so, find the best audiospec for it.
        SDL_AudioSpec spec;
        bool needs_migration = false;
        SDL_zero(spec);
        for (SDL_LogicalAudioDevice *logdev = current_default_device->logical_devices; logdev; logdev = logdev->next) {
            if (logdev->opened_as_default) {
                needs_migration = true;
                for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = stream->next_binding) {
                    const SDL_AudioSpec *streamspec = recording ? &stream->dst_spec : &stream->src_spec;
                    if (SDL_AUDIO_BITSIZE(streamspec->format) > SDL_AUDIO_BITSIZE(spec.format)) {
                        spec.format = streamspec->format;
                    }
                    if (streamspec->channels > spec.channels) {
                        spec.channels = streamspec->channels;
                    }
                    if (streamspec->freq > spec.freq) {
                        spec.freq = streamspec->freq;
                    }
                }
            }
        }
        if (needs_migration) {
            // New default physical device not been opened yet? Open at the OS level...
            if (!OpenPhysicalAudioDevice(new_default_device, &spec)) {
                needs_migration = false;  // uhoh, just leave everything on the old default, nothing to be done.
            }
        }
        if (needs_migration) {
            // we don't currently report channel map changes, so we'll leave them as NULL for now.
            const bool spec_changed = !SDL_AudioSpecsEqual(&current_default_device->spec, &new_default_device->spec, NULL, NULL);
            SDL_LogicalAudioDevice *next = NULL;
            for (SDL_LogicalAudioDevice *logdev = current_default_device->logical_devices; logdev; logdev = next) {
                next = logdev->next;
                if (!logdev->opened_as_default) {
                    continue;  // not opened as a default, leave it on the current physical device.
                }
                // now migrate the logical device. Hold device_hash_lock so ObtainLogicalAudioDevice doesn't get a device in the middle of transition.
                SDL_LockRWLockForWriting(current_audio.device_hash_lock);
                if (logdev->next) {
                    logdev->next->prev = logdev->prev;
                }
                if (logdev->prev) {
                    logdev->prev->next = logdev->next;
                }
                if (current_default_device->logical_devices == logdev) {
                    current_default_device->logical_devices = logdev->next;
                }
                logdev->physical_device = new_default_device;
                logdev->prev = NULL;
                logdev->next = new_default_device->logical_devices;
                new_default_device->logical_devices = logdev;
                SDL_UnlockRWLock(current_audio.device_hash_lock);
                SDL_assert(SDL_GetAtomicInt(&current_default_device->refcount) > 1);  // we should hold at least one extra reference to this device, beyond logical devices, during this phase...
                RefPhysicalAudioDevice(new_default_device);
                UnrefPhysicalAudioDevice(current_default_device);
                SDL_SetAudioPostmixCallback(logdev->instance_id, logdev->postmix, logdev->postmix_userdata);
                SDL_PendingAudioDeviceEvent *p;
                // Queue an event for each logical device we moved.
                if (spec_changed) {
                    p = (SDL_PendingAudioDeviceEvent *)SDL_malloc(sizeof(SDL_PendingAudioDeviceEvent));
                    if (p) { // if this failed, no event for you, but you have deeper problems anyhow.
                        p->type = SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED;
                        p->devid = logdev->instance_id;
                        p->next = NULL;
                        pending_tail->next = p;
                        pending_tail = p;
                    }
                }
            }
            UpdateAudioStreamFormatsPhysical(current_default_device);
            UpdateAudioStreamFormatsPhysical(new_default_device);
            if (!current_default_device->logical_devices) {   // nothing left on the current physical device, close it.
                ClosePhysicalAudioDevice(current_default_device);
            }
        }
        ReleaseAudioDevice(current_default_device);
    }
    ReleaseAudioDevice(new_default_device);
    // Default device gets an extra ref, so it lives until a new default replaces it, even if disconnected.
    if (current_default_device) {  // (despite the name, it's no longer current at this point)
        UnrefPhysicalAudioDevice(current_default_device);
    }
    if (pending.next) {
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        SDL_assert(current_audio.pending_events_tail != NULL);
        SDL_assert(current_audio.pending_events_tail->next == NULL);
        current_audio.pending_events_tail->next = pending.next;
        current_audio.pending_events_tail = pending_tail;
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
}
References SDL_AudioSpec::channels, ClosePhysicalAudioDevice(), current_audio, SDL_PendingAudioDeviceEvent::devid, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, SDL_PendingAudioDeviceEvent::next, NULL, ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), OpenPhysicalAudioDevice(), SDL_AudioDevice::recording, SDL_AudioDevice::refcount, RefPhysicalAudioDevice(), ReleaseAudioDevice(), SDL_assert, SDL_AUDIO_BITSIZE, SDL_AudioSpecsEqual(), SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED, SDL_GetAtomicInt(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_SetAudioPostmixCallback(), SDL_UnlockRWLock(), SDL_zero, SDL_AudioDevice::spec, SDL_PendingAudioDeviceEvent::type, UnrefPhysicalAudioDevice(), and UpdateAudioStreamFormatsPhysical().
SDL_FindPhysicalAudioDeviceByCallback()
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByCallback (bool(* callback)(SDL_AudioDevice *device, void *userdata), void * userdata) extern
{
    if (!SDL_GetCurrentAudioDriver()) {
        SDL_SetError("Audio subsystem is not initialized");
        return NULL;
    }
    FindAudioDeviceByCallbackData data = { callback, userdata, NULL };
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    SDL_IterateHashTable(current_audio.device_hash, FindAudioDeviceByCallback, &data);
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    if (!data.retval) {
        SDL_SetError("Device not found");
    }
    return data.retval;
}
References current_audio, FindAudioDeviceByCallback(), NULL, SDL_GetCurrentAudioDriver(), SDL_IterateHashTable(), SDL_LockRWLockForReading(), SDL_SetError(), and SDL_UnlockRWLock().
Referenced by SDL_FindPhysicalAudioDeviceByHandle().
SDL_FindPhysicalAudioDeviceByHandle()
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByHandle (void * handle) extern
{
    return SDL_FindPhysicalAudioDeviceByCallback(TestDeviceHandleCallback, handle);
}
References SDL_FindPhysicalAudioDeviceByCallback(), and TestDeviceHandleCallback().
Referenced by SDL_AddAudioDevice().
SDL_GetAudioStreamDataAdjustGain()
int SDL_GetAudioStreamDataAdjustGain (SDL_AudioStream * stream, void * voidbuf, int len, float extra_gain) extern
{
    Uint8 *buf = (Uint8 *) voidbuf;
#if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: want to get %d converted bytes", len);
#endif
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1;
    } else if (!buf) {
        SDL_InvalidParamError("buf");
        return -1;
    } else if (len < 0) {
        SDL_InvalidParamError("len");
        return -1;
    } else if (len == 0) {
        return 0; // nothing to do.
    }
    SDL_LockMutex(stream->lock);
    if (!CheckAudioStreamIsFullySetup(stream)) {
        SDL_UnlockMutex(stream->lock);
        return -1;
    }
    const float gain = stream->gain * extra_gain;
    const int dst_frame_size = SDL_AUDIO_FRAMESIZE(stream->dst_spec);
    len -= len % dst_frame_size;  // chop off any fractional sample frame.
    // give the callback a chance to fill in more stream data if it wants.
    if (stream->get_callback) {
        Sint64 total_request = len / dst_frame_size;  // start with sample frames desired
        Sint64 additional_request = total_request;
        Sint64 resample_offset = 0;
        Sint64 available_frames = GetAudioStreamAvailableFrames(stream, &resample_offset);
        additional_request -= SDL_min(additional_request, available_frames);
        Sint64 resample_rate = GetAudioStreamResampleRate(stream, stream->src_spec.freq, resample_offset);
        if (resample_rate) {
            total_request = SDL_GetResamplerInputFrames(total_request, resample_rate, resample_offset);
            additional_request = SDL_GetResamplerInputFrames(additional_request, resample_rate, resample_offset);
        }
        total_request *= SDL_AUDIO_FRAMESIZE(stream->src_spec);  // convert sample frames to bytes.
        additional_request *= SDL_AUDIO_FRAMESIZE(stream->src_spec);  // convert sample frames to bytes.
        stream->get_callback(stream->get_callback_userdata, stream, (int) SDL_min(additional_request, SDL_INT_MAX), (int) SDL_min(total_request, SDL_INT_MAX));
    }
    // Process the data in chunks to avoid allocating too much memory (and potential integer overflows)
    const int chunk_size = 4096;
    int total = 0;
    while (total < len) {
        // Audio is processed a track at a time.
        SDL_AudioSpec input_spec;
        int *input_chmap;
        bool flushed;
        const Sint64 available_frames = GetAudioStreamHead(stream, &input_spec, &input_chmap, &flushed);
        if (available_frames == 0) {
            if (flushed) {
                SDL_PopAudioQueueHead(stream->queue);
                SDL_zero(stream->input_spec);
                stream->resample_offset = 0;
                stream->input_chmap = NULL;
                continue;
            }
            // There are no frames available, but the track hasn't been flushed, so more might be added later.
            break;
        }
        if (!UpdateAudioStreamInputSpec(stream, &input_spec, input_chmap)) {
            total = total ? total : -1;
            break;
        }
        // Clamp the output length to the maximum currently available.
        // GetAudioStreamDataInternal requires enough input data is available.
        int output_frames = (len - total) / dst_frame_size;
        output_frames = SDL_min(output_frames, chunk_size);
        output_frames = (int) SDL_min(output_frames, available_frames);
        if (!GetAudioStreamDataInternal(stream, &buf[total], output_frames, gain)) {
            total = total ? total : -1;
            break;
        }
        total += output_frames * dst_frame_size;
    }
    SDL_UnlockMutex(stream->lock);
#if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: Final result was %d", total);
#endif
    return total;
}
References CheckAudioStreamIsFullySetup(), GetAudioStreamAvailableFrames(), GetAudioStreamDataInternal(), GetAudioStreamHead(), GetAudioStreamResampleRate(), NULL, SDL_AUDIO_FRAMESIZE, SDL_GetResamplerInputFrames(), SDL_INT_MAX, SDL_InvalidParamError, SDL_LockMutex(), SDL_Log(), SDL_min, SDL_PopAudioQueueHead(), SDL_UnlockMutex(), SDL_zero, and UpdateAudioStreamInputSpec().
Referenced by SDL_GetAudioStreamData(), and SDL_PlaybackAudioThreadIterate().
SDL_GetAudioThreadName()
char * SDL_GetAudioThreadName (SDL_AudioDevice * device, char * buf, size_t buflen) extern
{
    (void)SDL_snprintf(buf, buflen, "SDLAudio%c%d", (device->recording) ? 'C' : 'P', (int) device->instance_id);
    return buf;
}
References SDL_AudioDevice::instance_id, SDL_AudioDevice::recording, SDL_snprintf(), and void().
Referenced by OpenPhysicalAudioDevice().
SDL_GetDefaultSampleFramesFromFreq()
int SDL_GetDefaultSampleFramesFromFreq (const int freq)
{
    const char *hint = SDL_GetHint(SDL_HINT_AUDIO_DEVICE_SAMPLE_FRAMES);
    if (hint) {
        const int val = SDL_atoi(hint);
        if (val > 0) {
            return val;
        }
    }
    if (freq <= 22050) {
        return 512;
    } else if (freq <= 48000) {
        return 1024;
    } else if (freq <= 96000) {
        return 2048;
    } else {
        return 4096;
    }
}
References SDL_atoi(), SDL_GetHint(), and SDL_HINT_AUDIO_DEVICE_SAMPLE_FRAMES.
Referenced by CreatePhysicalAudioDevice(), and OpenPhysicalAudioDevice().
SDL_InitAudio()
bool SDL_InitAudio (const char * driver_name) extern
{
    if (SDL_GetCurrentAudioDriver()) {
        SDL_QuitAudio(); // shutdown driver if already running.
    }
    // make sure device IDs start at 2 (because of SDL2 legacy interface), but don't reset the counter on each init, in case the app is holding an old device ID somewhere.
    SDL_CompareAndSwapAtomicInt(&last_device_instance_id, 0, 2);
    SDL_ChooseAudioConverters();
    SDL_SetupAudioResampler();
    SDL_RWLock *device_hash_lock = SDL_CreateRWLock();  // create this early, so if it fails we don't have to tear down the whole audio subsystem.
    if (!device_hash_lock) {
        return false;
    }
    SDL_HashTable *device_hash = SDL_CreateHashTable(0, false, HashAudioDeviceID, SDL_KeyMatchID, NULL, NULL);
    if (!device_hash) {
        SDL_DestroyRWLock(device_hash_lock);
        return false;
    }
    // Select the proper audio driver
    if (!driver_name) {
        driver_name = SDL_GetHint(SDL_HINT_AUDIO_DRIVER);
    }
    bool initialized = false;
    bool tried_to_init = false;
    if (driver_name && *driver_name != 0) {
        char *driver_name_copy = SDL_strdup(driver_name);
        const char *driver_attempt = driver_name_copy;
        if (!driver_name_copy) {
            SDL_DestroyRWLock(device_hash_lock);
            SDL_DestroyHashTable(device_hash);
            return false;
        }
        while (driver_attempt && *driver_attempt != 0 && !initialized) {
            char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            if (driver_attempt_end) {
                *driver_attempt_end = '\0';
            }
            // SDL 1.2 uses the name "dsound", so we'll support both.
            if (SDL_strcmp(driver_attempt, "dsound") == 0) {
                driver_attempt = "directsound";
            } else if (SDL_strcmp(driver_attempt, "pulse") == 0) {  // likewise, "pulse" was renamed to "pulseaudio"
                driver_attempt = "pulseaudio";
            }
            for (int i = 0; bootstrap[i]; ++i) {
                if (!bootstrap[i]->is_preferred && SDL_strcasecmp(bootstrap[i]->name, driver_attempt) == 0) {
                    tried_to_init = true;
                    SDL_zero(current_audio);
                    current_audio.pending_events_tail = &current_audio.pending_events;
                    current_audio.device_hash_lock = device_hash_lock;
                    current_audio.device_hash = device_hash;
                    if (bootstrap[i]->init(&current_audio.impl)) {
                        current_audio.name = bootstrap[i]->name;
                        current_audio.desc = bootstrap[i]->desc;
                        initialized = true;
                        break;
                    }
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
        SDL_free(driver_name_copy);
    } else {
        for (int i = 0; (!initialized) && (bootstrap[i]); ++i) {
            if (bootstrap[i]->demand_only) {
                continue;
            }
            tried_to_init = true;
            SDL_zero(current_audio);
            current_audio.pending_events_tail = &current_audio.pending_events;
            current_audio.device_hash_lock = device_hash_lock;
            current_audio.device_hash = device_hash;
            if (bootstrap[i]->init(&current_audio.impl)) {
                current_audio.name = bootstrap[i]->name;
                current_audio.desc = bootstrap[i]->desc;
                initialized = true;
            }
        }
    }
    if (initialized) {
        SDL_DebugLogBackend("audio", current_audio.name);
    } else {
        // specific drivers will set the error message if they fail, but otherwise we do it here.
        if (!tried_to_init) {
            if (driver_name) {
                SDL_SetError("Audio target '%s' not available", driver_name);
            } else {
                SDL_SetError("No available audio device");
            }
        }
        SDL_DestroyRWLock(device_hash_lock);
        SDL_DestroyHashTable(device_hash);
        SDL_zero(current_audio);
        return false;  // No driver was available, so fail.
    }
    CompleteAudioEntryPoints();
    // Make sure we have a list of devices available at startup...
    SDL_AudioDevice *default_playback = NULL;
    SDL_AudioDevice *default_recording = NULL;
    current_audio.impl.DetectDevices(&default_playback, &default_recording);
    // If no default was _ever_ specified, just take the first device we see, if any.
    if (!default_playback) {
        default_playback = GetFirstAddedAudioDevice(/*recording=*/false);
    }
    if (!default_recording) {
        default_recording = GetFirstAddedAudioDevice(/*recording=*/true);
    }
    if (default_playback) {
        current_audio.default_playback_device_id = default_playback->instance_id;
        RefPhysicalAudioDevice(default_playback);  // extra ref on default devices.
    }
    if (default_recording) {
        current_audio.default_recording_device_id = default_recording->instance_id;
        RefPhysicalAudioDevice(default_recording);  // extra ref on default devices.
    }
    return true;
}
References bootstrap, CompleteAudioEntryPoints(), current_audio, GetFirstAddedAudioDevice(), HashAudioDeviceID(), SDL_AudioDevice::instance_id, last_device_instance_id, NULL, RefPhysicalAudioDevice(), SDL_ChooseAudioConverters(), SDL_CompareAndSwapAtomicInt(), SDL_CreateHashTable(), SDL_CreateRWLock(), SDL_DebugLogBackend(), SDL_DestroyHashTable(), SDL_DestroyRWLock(), SDL_free(), SDL_GetCurrentAudioDriver(), SDL_GetHint(), SDL_HINT_AUDIO_DRIVER, SDL_KeyMatchID(), SDL_QuitAudio(), SDL_SetError(), SDL_SetupAudioResampler(), SDL_strcasecmp(), SDL_strchr(), SDL_strcmp(), SDL_strdup(), and SDL_zero.
Referenced by SDL_InitSubSystem().
SDL_PlaybackAudioThreadIterate()
bool SDL_PlaybackAudioThreadIterate (SDL_AudioDevice * device) extern
{
    SDL_assert(!device->recording);
    SDL_LockMutex(device->lock);
    if (SDL_GetAtomicInt(&device->shutdown)) {
        SDL_UnlockMutex(device->lock);
        return false;  // we're done, shut it down.
    }
    bool failed = false;
    int buffer_size = device->buffer_size;
    Uint8 *device_buffer = device->GetDeviceBuf(device, &buffer_size);
    if (buffer_size == 0) {
        // WASAPI (maybe others, later) does this to say "just abandon this iteration and try again next time."
    } else if (!device_buffer) {
        failed = true;
    } else {
        SDL_assert(buffer_size <= device->buffer_size);  // you can ask for less, but not more.
        SDL_assert(AudioDeviceCanUseSimpleCopy(device) == device->simple_copy);  // make sure this hasn't gotten out of sync.
        // can we do a basic copy without silencing/mixing the buffer? This is an extremely likely scenario, so we special-case it.
        if (device->simple_copy) {
            SDL_LogicalAudioDevice *logdev = device->logical_devices;
            SDL_AudioStream *stream = logdev->bound_streams;
            // We should have updated this elsewhere if the format changed!
            SDL_assert(SDL_AudioSpecsEqual(&stream->dst_spec, &device->spec, NULL, NULL));
            SDL_assert(stream->src_spec.format != SDL_AUDIO_UNKNOWN);
            const int br = SDL_GetAtomicInt(&logdev->paused) ? 0 : SDL_GetAudioStreamDataAdjustGain(stream, device_buffer, buffer_size, logdev->gain);
            if (br < 0) {  // Probably OOM. Kill the audio device; the whole thing is likely dying soon anyhow.
                failed = true;
                SDL_memset(device_buffer, device->silence_value, buffer_size);  // just supply silence to the device before we die.
            } else if (br < buffer_size) {
                SDL_memset(device_buffer + br, device->silence_value, buffer_size - br);  // silence whatever we didn't write to.
            }
            // generally channel maps will line up, but if the audio stream's chmap has been explicitly changed, do a final swizzle to device layout.
            if ((br > 0) && (!SDL_AudioChannelMapsEqual(device->spec.channels, stream->dst_chmap, device->chmap))) {
                ConvertAudio(br / SDL_AUDIO_FRAMESIZE(device->spec), device_buffer, device->spec.format, device->spec.channels, NULL,
                             device_buffer, device->spec.format, device->spec.channels, device->chmap, NULL, 1.0f);
            }
        } else {  // need to actually mix (or silence the buffer)
            float *final_mix_buffer = (float *) ((device->spec.format == SDL_AUDIO_F32) ? device_buffer : device->mix_buffer);
            const int needed_samples = buffer_size / SDL_AUDIO_BYTESIZE(device->spec.format);
            const int work_buffer_size = needed_samples * sizeof (float);
            SDL_AudioSpec outspec;
            SDL_assert(work_buffer_size <= device->work_buffer_size);
            SDL_copyp(&outspec, &device->spec);
            outspec.format = SDL_AUDIO_F32;
            SDL_memset(final_mix_buffer, '\0', work_buffer_size);  // start with silence.
            for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
                if (SDL_GetAtomicInt(&logdev->paused)) {
                    continue;  // paused? Skip this logical device.
                }
                const SDL_AudioPostmixCallback postmix = logdev->postmix;
                float *mix_buffer = final_mix_buffer;
                if (postmix) {
                    mix_buffer = device->postmix_buffer;
                    SDL_memset(mix_buffer, '\0', work_buffer_size);  // start with silence.
                }
                for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = stream->next_binding) {
                    // We should have updated this elsewhere if the format changed!
                    SDL_assert(SDL_AudioSpecsEqual(&stream->dst_spec, &outspec, NULL, NULL));
                    SDL_assert(stream->src_spec.format != SDL_AUDIO_UNKNOWN);
                    /* this will hold a lock on `stream` while getting. We don't explicitly lock the streams
                       for iterating here because the binding linked list can only change while the device lock is held.
                       (we _do_ lock the stream during binding/unbinding to make sure that two threads can't try to bind
                       the same stream to different devices at the same time, though.) */
                    const int br = SDL_GetAudioStreamDataAdjustGain(stream, device->work_buffer, work_buffer_size, logdev->gain);
                    if (br < 0) {  // Probably OOM. Kill the audio device; the whole thing is likely dying soon anyhow.
                        failed = true;
                        break;
                    } else if (br > 0) {  // it's okay if we get less than requested, we mix what we have.
                        // generally channel maps will line up, but if the audio stream's chmap has been explicitly changed, do a final swizzle to device layout.
                        if (!SDL_AudioChannelMapsEqual(device->spec.channels, stream->dst_chmap, device->chmap)) {
                            ConvertAudio(br / SDL_AUDIO_FRAMESIZE(device->spec), device->work_buffer, device->spec.format, device->spec.channels, NULL,
                                         device->work_buffer, device->spec.format, device->spec.channels, device->chmap, NULL, 1.0f);
                        }
                        MixFloat32Audio(mix_buffer, (float *) device->work_buffer, br);
                    }
                }
                if (postmix) {
                    SDL_assert(mix_buffer == device->postmix_buffer);
                    postmix(logdev->postmix_userdata, &outspec, mix_buffer, work_buffer_size);
                    MixFloat32Audio(final_mix_buffer, mix_buffer, work_buffer_size);
                }
            }
            if (((Uint8 *) final_mix_buffer) != device_buffer) {
                // !!! FIXME: we can't promise the device buf is aligned/padded for SIMD.
                //ConvertAudio(needed_samples / device->spec.channels, final_mix_buffer, SDL_AUDIO_F32, device->spec.channels, NULL, device_buffer, device->spec.format, device->spec.channels, NULL, NULL, 1.0f);
                ConvertAudio(needed_samples / device->spec.channels, final_mix_buffer, SDL_AUDIO_F32, device->spec.channels, NULL, device->work_buffer, device->spec.format, device->spec.channels, NULL, NULL, 1.0f);
                SDL_memcpy(device_buffer, device->work_buffer, buffer_size);
            }
        }
        // PlayDevice SHOULD NOT BLOCK, as we are holding a lock right now. Block in WaitDevice instead!
        if (!device->PlayDevice(device, device_buffer, buffer_size)) {
            failed = true;
        }
    }
    SDL_UnlockMutex(device->lock);
    if (failed) {
        SDL_AudioDeviceDisconnected(device);  // doh.
    }
    return true;  // always go on if not shutting down, even if device failed.
}
References AudioDeviceCanUseSimpleCopy(), SDL_LogicalAudioDevice::bound_streams, SDL_AudioDevice::buffer_size, SDL_AudioSpec::channels, SDL_AudioDevice::chmap, ConvertAudio(), SDL_AudioSpec::format, SDL_LogicalAudioDevice::gain, SDL_AudioDevice::GetDeviceBuf, SDL_AudioDevice::lock, SDL_AudioDevice::logical_devices, SDL_AudioDevice::mix_buffer, MixFloat32Audio(), SDL_LogicalAudioDevice::next, NULL, SDL_LogicalAudioDevice::paused, SDL_AudioDevice::PlayDevice, SDL_AudioDevice::postmix_buffer, SDL_AudioDevice::recording, SDL_assert, SDL_AUDIO_BYTESIZE, SDL_AUDIO_F32, SDL_AUDIO_FRAMESIZE, SDL_AUDIO_UNKNOWN, SDL_AudioChannelMapsEqual(), SDL_AudioDeviceDisconnected(), SDL_AudioSpecsEqual(), SDL_copyp, SDL_GetAtomicInt(), SDL_GetAudioStreamDataAdjustGain(), SDL_LockMutex(), SDL_memcpy, SDL_memset, SDL_UnlockMutex(), SDL_AudioDevice::shutdown, SDL_AudioDevice::silence_value, SDL_AudioDevice::simple_copy, SDL_AudioDevice::spec, and SDL_AudioDevice::work_buffer.
Referenced by DUMMYAUDIO_OpenDevice(), and PlaybackAudioThread().
SDL_PlaybackAudioThreadSetup()
void SDL_PlaybackAudioThreadSetup (SDL_AudioDevice * device) extern
{
    SDL_assert(!device->recording);
    current_audio.impl.ThreadInit(device);
}
References current_audio, SDL_AudioDevice::recording, and SDL_assert.
Referenced by PlaybackAudioThread().
SDL_PlaybackAudioThreadShutdown()
void SDL_PlaybackAudioThreadShutdown (SDL_AudioDevice * device) extern
{
    SDL_assert(!device->recording);
    const int frames = device->buffer_size / SDL_AUDIO_FRAMESIZE(device->spec);
    // Wait for the audio to drain if device didn't die.
    if (!SDL_GetAtomicInt(&device->zombie)) {
        SDL_Delay(((frames * 1000) / device->spec.freq) * 2);
    }
    current_audio.impl.ThreadDeinit(device);
    SDL_AudioThreadFinalize(device);
}
References SDL_AudioDevice::buffer_size, current_audio, SDL_AudioSpec::freq, SDL_AudioDevice::recording, SDL_assert, SDL_AUDIO_FRAMESIZE, SDL_AudioThreadFinalize(), SDL_Delay(), SDL_GetAtomicInt(), SDL_AudioDevice::spec, and SDL_AudioDevice::zombie.
Referenced by PlaybackAudioThread().
SDL_QuitAudio()
void SDL_QuitAudio (void) extern
{
    if (!current_audio.name) {  // not initialized?!
        return;
    }
    current_audio.impl.DeinitializeStart();
    // Destroy any audio streams that still exist...unless app asked to keep it.
    SDL_AudioStream *next = NULL;
    for (SDL_AudioStream *i = current_audio.existing_streams; i; i = next) {
        next = i->next;
        if (i->simplified || SDL_GetBooleanProperty(i->props, SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN, true)) {
            SDL_DestroyAudioStream(i);
        } else {
            i->prev = NULL;
            i->next = NULL;
        }
    }
    SDL_LockRWLockForWriting(current_audio.device_hash_lock);
    SDL_SetAtomicInt(&current_audio.shutting_down, 1);
    SDL_HashTable *device_hash = current_audio.device_hash;
    current_audio.device_hash = NULL;
    SDL_PendingAudioDeviceEvent *pending_events = current_audio.pending_events.next;
    current_audio.pending_events.next = NULL;
    SDL_SetAtomicInt(&current_audio.playback_device_count, 0);
    SDL_SetAtomicInt(&current_audio.recording_device_count, 0);
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    SDL_PendingAudioDeviceEvent *pending_next = NULL;
    for (SDL_PendingAudioDeviceEvent *i = pending_events; i; i = pending_next) {
        pending_next = i->next;
        SDL_free(i);
    }
    SDL_IterateHashTable(device_hash, DestroyOnePhysicalAudioDevice, NULL);
    // Free the driver data
    current_audio.impl.Deinitialize();
    SDL_DestroyRWLock(current_audio.device_hash_lock);
    SDL_DestroyHashTable(device_hash);
    SDL_zero(current_audio);
}
References current_audio, DestroyOnePhysicalAudioDevice(), SDL_AudioStream::next, SDL_PendingAudioDeviceEvent::next, NULL, SDL_DestroyAudioStream(), SDL_DestroyHashTable(), SDL_DestroyRWLock(), SDL_free(), SDL_GetBooleanProperty(), SDL_IterateHashTable(), SDL_LockRWLockForWriting(), SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN, SDL_SetAtomicInt(), SDL_UnlockRWLock(), and SDL_zero.
Referenced by SDL_InitAudio(), and SDL_QuitSubSystem().
SDL_RecordingAudioThreadIterate()
bool SDL_RecordingAudioThreadIterate (SDL_AudioDevice * device) extern
{
    SDL_assert(device->recording);
    SDL_LockMutex(device->lock);
    if (SDL_GetAtomicInt(&device->shutdown)) {
        SDL_UnlockMutex(device->lock);
        return false;  // we're done, shut it down.
    }
    bool failed = false;
    if (!device->logical_devices) {
        device->FlushRecording(device); // nothing wants data, dump anything pending.
    } else {
        // this SHOULD NOT BLOCK, as we are holding a lock right now. Block in WaitRecordingDevice!
        int br = device->RecordDevice(device, device->work_buffer, device->buffer_size);
        if (br < 0) {  // uhoh, device failed for some reason!
            failed = true;
        } else if (br > 0) {  // queue the new data to each bound stream.
            for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
                if (SDL_GetAtomicInt(&logdev->paused)) {
                    continue;  // paused? Skip this logical device.
                }
                void *output_buffer = device->work_buffer;
                // I don't know why someone would want a postmix on a recording device, but we offer it for API consistency.
                if (logdev->postmix || (logdev->gain != 1.0f)) {
                    // move to float format.
                    SDL_AudioSpec outspec;
                    SDL_copyp(&outspec, &device->spec);
                    outspec.format = SDL_AUDIO_F32;
                    output_buffer = device->postmix_buffer;
                    const int frames = br / SDL_AUDIO_FRAMESIZE(device->spec);
                    br = frames * SDL_AUDIO_FRAMESIZE(outspec);
                    ConvertAudio(frames, device->work_buffer, device->spec.format, outspec.channels, NULL, device->postmix_buffer, SDL_AUDIO_F32, outspec.channels, NULL, NULL, logdev->gain);
                    if (logdev->postmix) {
                        logdev->postmix(logdev->postmix_userdata, &outspec, device->postmix_buffer, br);
                    }
                }
                for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = stream->next_binding) {
                    // We should have updated this elsewhere if the format changed!
                    SDL_assert(stream->src_spec.format == ((logdev->postmix || (logdev->gain != 1.0f)) ? SDL_AUDIO_F32 : device->spec.format));
                    SDL_assert(stream->src_spec.channels == device->spec.channels);
                    SDL_assert(stream->src_spec.freq == device->spec.freq);
                    SDL_assert(stream->dst_spec.format != SDL_AUDIO_UNKNOWN);
                    void *final_buf = output_buffer;
                    // generally channel maps will line up, but if the audio stream's chmap has been explicitly changed, do a final swizzle to stream layout.
                    if (!SDL_AudioChannelMapsEqual(device->spec.channels, stream->src_chmap, device->chmap)) {
                        final_buf = device->mix_buffer;  // this is otherwise unused on recording devices, so it makes convenient scratch space here.
                        ConvertAudio(br / SDL_AUDIO_FRAMESIZE(device->spec), output_buffer, device->spec.format, device->spec.channels, NULL,
                                     final_buf, device->spec.format, device->spec.channels, stream->src_chmap, NULL, 1.0f);
                    }
                    /* this will hold a lock on `stream` while putting. We don't explicitly lock the streams
                       for iterating here because the binding linked list can only change while the device lock is held.
                       (we _do_ lock the stream during binding/unbinding to make sure that two threads can't try to bind
                       the same stream to different devices at the same time, though.) */
                    if (!SDL_PutAudioStreamData(stream, final_buf, br)) {
                        // oh crud, we probably ran out of memory. This is possibly an overreaction to kill the audio device, but it's likely the whole thing is going down in a moment anyhow.
                        failed = true;
                        break;
                    }
                }
            }
        }
    }
    SDL_UnlockMutex(device->lock);
    if (failed) {
        SDL_AudioDeviceDisconnected(device);  // doh.
    }
    return true;  // always go on if not shutting down, even if device failed.
}
References SDL_AudioDevice::buffer_size, SDL_AudioSpec::channels, SDL_AudioDevice::chmap, ConvertAudio(), SDL_AudioDevice::FlushRecording, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::lock, SDL_AudioDevice::logical_devices, SDL_AudioDevice::mix_buffer, SDL_LogicalAudioDevice::next, NULL, SDL_AudioDevice::postmix_buffer, SDL_AudioDevice::RecordDevice, SDL_AudioDevice::recording, SDL_assert, SDL_AUDIO_F32, SDL_AUDIO_FRAMESIZE, SDL_AUDIO_UNKNOWN, SDL_AudioChannelMapsEqual(), SDL_AudioDeviceDisconnected(), SDL_copyp, SDL_GetAtomicInt(), SDL_LockMutex(), SDL_PutAudioStreamData(), SDL_UnlockMutex(), SDL_AudioDevice::shutdown, SDL_AudioDevice::spec, and SDL_AudioDevice::work_buffer.
Referenced by DUMMYAUDIO_OpenDevice(), and RecordingAudioThread().
SDL_RecordingAudioThreadSetup()
void SDL_RecordingAudioThreadSetup (SDL_AudioDevice * device) extern
{
    SDL_assert(device->recording);
    current_audio.impl.ThreadInit(device);
}
References current_audio, SDL_AudioDevice::recording, and SDL_assert.
Referenced by RecordingAudioThread().
SDL_RecordingAudioThreadShutdown()
void SDL_RecordingAudioThreadShutdown (SDL_AudioDevice * device) extern
{
    SDL_assert(device->recording);
    device->FlushRecording(device);
    current_audio.impl.ThreadDeinit(device);
    SDL_AudioThreadFinalize(device);
}
References current_audio, SDL_AudioDevice::FlushRecording, SDL_AudioDevice::recording, SDL_assert, and SDL_AudioThreadFinalize().
Referenced by RecordingAudioThread().
SDL_SetupAudioResampler()
void SDL_SetupAudioResampler (void) extern
{
    static SDL_InitState init;
    if (SDL_ShouldInit(&init)) {
        SetupAudioResampler();
        SDL_SetInitialized(&init, true);
    }
}
References SDL_SetInitialized(), SDL_ShouldInit(), and SetupAudioResampler().
Referenced by SDL_CreateAudioStream(), and SDL_InitAudio().
SDL_UpdatedAudioDeviceFormat()
void SDL_UpdatedAudioDeviceFormat (SDL_AudioDevice * device) extern
{
    device->silence_value = SDL_GetSilenceValueForFormat(device->spec.format);
    device->buffer_size = device->sample_frames * SDL_AUDIO_FRAMESIZE(device->spec);
    device->work_buffer_size = device->sample_frames * sizeof (float) * device->spec.channels;
    device->work_buffer_size = SDL_max(device->buffer_size, device->work_buffer_size);  // just in case we end up with a 64-bit audio format at some point.
}
References SDL_AudioDevice::buffer_size, SDL_AudioSpec::channels, SDL_AudioSpec::format, SDL_AudioDevice::sample_frames, SDL_AUDIO_FRAMESIZE, SDL_GetSilenceValueForFormat(), SDL_max, SDL_AudioDevice::silence_value, SDL_AudioDevice::spec, and SDL_AudioDevice::work_buffer_size.
Referenced by OpenPhysicalAudioDevice(), PS2AUDIO_OpenDevice(), and SDL_AudioDeviceFormatChangedAlreadyLocked().
SetAudioStreamChannelMap()
bool SetAudioStreamChannelMap (SDL_AudioStream * stream, const SDL_AudioSpec * spec, int ** stream_chmap, const int * chmap, int channels, int isinput) extern
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    bool result = true;
    SDL_LockMutex(stream->lock);
    if (channels != spec->channels) {
        result = SDL_SetError("Wrong number of channels");
    } else if (!*stream_chmap && !chmap) {
        // already at default, we're good.
    } else if (*stream_chmap && chmap && (SDL_memcmp(*stream_chmap, chmap, sizeof (*chmap) * channels) == 0)) {
        // already have this map, don't allocate/copy it again.
    } else if (SDL_ChannelMapIsBogus(chmap, channels)) {
        result = SDL_SetError("Invalid channel mapping");
    } else {
        if (SDL_ChannelMapIsDefault(chmap, channels)) {
            chmap = NULL;  // just apply a default mapping.
        }
        if (chmap) {
            int *dupmap = SDL_ChannelMapDup(chmap, channels);
            if (!dupmap) {
                result = SDL_SetError("Invalid channel mapping");
            } else {
                SDL_free(*stream_chmap);
                *stream_chmap = dupmap;
            }
        } else {
            SDL_free(*stream_chmap);
            *stream_chmap = NULL;
        }
    }
    SDL_UnlockMutex(stream->lock);
    return result;
}
References SDL_AudioSpec::channels, NULL, SDL_ChannelMapDup(), SDL_ChannelMapIsBogus(), SDL_ChannelMapIsDefault(), SDL_free(), SDL_InvalidParamError, SDL_LockMutex(), SDL_memcmp(), SDL_SetError(), and SDL_UnlockMutex().
Referenced by SDL_SetAudioStreamInputChannelMap(), SDL_SetAudioStreamOutputChannelMap(), and UpdateAudioStreamFormatsPhysical().
UnrefPhysicalAudioDevice()
void UnrefPhysicalAudioDevice (SDL_AudioDevice * device) extern
{
    if (SDL_AtomicDecRef(&device->refcount)) {
        // take it out of the device list.
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        if (SDL_RemoveFromHashTable(current_audio.device_hash, (const void *) (uintptr_t) device->instance_id)) {
            SDL_AddAtomicInt(device->recording ? &current_audio.recording_device_count : &current_audio.playback_device_count, -1);
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
        DestroyPhysicalAudioDevice(device);  // ...and nuke it.
    }
}
References current_audio, DestroyPhysicalAudioDevice(), SDL_AudioDevice::instance_id, SDL_AudioDevice::recording, SDL_AudioDevice::refcount, SDL_AddAtomicInt(), SDL_AtomicDecRef, SDL_LockRWLockForWriting(), SDL_RemoveFromHashTable(), and SDL_UnlockRWLock().
Referenced by ObtainLogicalAudioDevice(), ReleaseAudioDevice(), SDL_AudioDeviceDisconnected(), SDL_CloseAudioDevice(), and SDL_DefaultAudioDeviceChanged().
Variable Documentation
AAUDIO_bootstrap
AudioBootStrap AAUDIO_bootstrap extern
ALSA_bootstrap
AudioBootStrap ALSA_bootstrap extern
COREAUDIO_bootstrap
AudioBootStrap COREAUDIO_bootstrap extern
DISKAUDIO_bootstrap
AudioBootStrap DISKAUDIO_bootstrap extern
DSOUND_bootstrap
AudioBootStrap DSOUND_bootstrap extern
DSP_bootstrap
AudioBootStrap DSP_bootstrap extern
DUMMYAUDIO_bootstrap
AudioBootStrap DUMMYAUDIO_bootstrap extern
{
    "dummy", "SDL dummy audio driver", DUMMYAUDIO_Init, true, false
};
EMSCRIPTENAUDIO_bootstrap
AudioBootStrap EMSCRIPTENAUDIO_bootstrap extern
HAIKUAUDIO_bootstrap
AudioBootStrap HAIKUAUDIO_bootstrap extern
JACK_bootstrap
AudioBootStrap JACK_bootstrap extern
N3DSAUDIO_bootstrap
AudioBootStrap N3DSAUDIO_bootstrap extern
NETBSDAUDIO_bootstrap
AudioBootStrap NETBSDAUDIO_bootstrap extern
NGAGEAUDIO_bootstrap
AudioBootStrap NGAGEAUDIO_bootstrap extern
OPENSLES_bootstrap
AudioBootStrap OPENSLES_bootstrap extern
PIPEWIRE_bootstrap
AudioBootStrap PIPEWIRE_bootstrap extern
PIPEWIRE_PREFERRED_bootstrap
AudioBootStrap PIPEWIRE_PREFERRED_bootstrap extern
PRIVATEAUDIO_bootstrap
AudioBootStrap PRIVATEAUDIO_bootstrap extern
PS2AUDIO_bootstrap
AudioBootStrap PS2AUDIO_bootstrap extern
{
    "ps2", "PS2 audio driver", PS2AUDIO_Init, false, false
};
PSPAUDIO_bootstrap
AudioBootStrap PSPAUDIO_bootstrap extern
PULSEAUDIO_bootstrap
AudioBootStrap PULSEAUDIO_bootstrap extern
QSAAUDIO_bootstrap
AudioBootStrap QSAAUDIO_bootstrap extern
SNDIO_bootstrap
AudioBootStrap SNDIO_bootstrap extern
VITAAUD_bootstrap
AudioBootStrap VITAAUD_bootstrap extern
WASAPI_bootstrap
AudioBootStrap WASAPI_bootstrap extern
WINMM_bootstrap
AudioBootStrap WINMM_bootstrap extern