SDL3: CSDLmain Class Reference
CSDLmain Class Reference
#include <SDL_sysmain_main.hpp>
Inherits CActive.
Public Member Functions
void Start ()
~CSDLmain ()
Static Public Member Functions
static CSDLmain * NewL ()
Protected Member Functions
void DoCancel ()
void RunL ()
Private Member Functions
void ConstructL ()
CSDLmain ()
Private Attributes
SDL_AppResult iResult
Constructor & Destructor Documentation
~CSDLmain()
CSDLmain::~CSDLmain ()
{
    Cancel();
}
CSDLmain()
CSDLmain::CSDLmain () private
: CActive(EPriorityLow) {}
Referenced by NewL().
Member Function Documentation
ConstructL()
void CSDLmain::ConstructL () private
{
    CActiveScheduler::Add(this);
}
Referenced by NewL().
DoCancel()
void CSDLmain::DoCancel () protected
{}
NewL()
CSDLmain * CSDLmain::NewL () static
{
    CSDLmain *self = new (ELeave) CSDLmain();
    CleanupStack::PushL(self);
    self->ConstructL();
    CleanupStack::Pop(self);
    return self;
}
References ConstructL(), and CSDLmain().
Referenced by E32Main().
RunL()
void CSDLmain::RunL () protected
{
    if (callbacks_initialized)
    {
        SDL_Event event;
        iResult = SDL_AppIterate(NULL);
        if (iResult != SDL_APP_CONTINUE)
        {
            DeinitAudio();
            SDL_AppQuit(NULL, iResult);
            SDL_Quit();
            CActiveScheduler::Stop();
            return;
        }
        SDL_PumpEvents();
        if (SDL_PollEvent(&event))
        {
            iResult = SDL_AppEvent(NULL, &event);
            if (iResult != SDL_APP_CONTINUE)
            {
                DeinitAudio();
                SDL_AppQuit(NULL, iResult);
                SDL_Quit();
                CActiveScheduler::Stop();
                return;
            }
        }
        Start();
    }
    else
    {
        SDL_SetMainReady();
        SDL_AppInit(NULL, 0, NULL);
        callbacks_initialized = true;
        Start();
    }
}
References callbacks_initialized, DeinitAudio(), iResult, NULL, SDL_APP_CONTINUE, SDL_AppEvent(), SDL_AppInit(), SDL_AppIterate(), SDL_AppQuit(), SDL_PollEvent(), SDL_PumpEvents(), SDL_Quit(), SDL_SetMainReady(), and Start().
Start()
void CSDLmain::Start ()
{
    SetActive();
    TRequestStatus *status = &iStatus;
    User::RequestComplete(status, KErrNone);
}
Referenced by E32Main(), and RunL().
Field Documentation
iResult
SDL_AppResult CSDLmain::iResult private
Referenced by RunL().
The documentation for this class was generated from the following files:
SDL-main/src/main/ngage/SDL_sysmain_main.hpp
SDL-main/src/main/ngage/SDL_sysmain_main.cpp