SDL3: SDL-main/src/camera/SDL_syscamera.h File Reference
SDL_syscamera.h File Reference
#include "../SDL_internal.h"
#include "../video/SDL_surface_c.h"
Data Structures
struct CameraBootStrap
struct CameraFormatAddData
struct SDL_Camera
struct SDL_CameraDriver
struct SDL_CameraDriverImpl
struct SDL_PendingCameraEvent
struct SurfaceList
Macros
#define DEBUG_CAMERA 0
Typedefs
typedef struct CameraBootStrap CameraBootStrap
typedef struct CameraFormatAddData CameraFormatAddData
typedef struct SDL_CameraDriver SDL_CameraDriver
typedef struct SDL_CameraDriverImpl SDL_CameraDriverImpl
typedef enum SDL_CameraFrameResult SDL_CameraFrameResult
typedef struct SDL_PendingCameraEvent SDL_PendingCameraEvent
typedef struct SurfaceList SurfaceList
Enumerations
enum SDL_CameraFrameResult { SDL_CAMERA_FRAME_ERROR , SDL_CAMERA_FRAME_SKIP , SDL_CAMERA_FRAME_READY }
Functions
void RefPhysicalCamera (SDL_Camera *device)
SDL_Camera * SDL_AddCamera (const char *name, SDL_CameraPosition position, int num_specs, const SDL_CameraSpec *specs, void *handle)
bool SDL_AddCameraFormat (CameraFormatAddData *data, SDL_PixelFormat format, SDL_Colorspace colorspace, int w, int h, int framerate_numerator, int framerate_denominator)
void SDL_CameraDisconnected (SDL_Camera *device)
void SDL_CameraPermissionOutcome (SDL_Camera *device, bool approved)
bool SDL_CameraThreadIterate (SDL_Camera *device)
void SDL_CameraThreadSetup (SDL_Camera *device)
void SDL_CameraThreadShutdown (SDL_Camera *device)
SDL_Camera * SDL_FindPhysicalCameraByCallback (bool(*callback)(SDL_Camera *device, void *userdata), void *userdata)
char * SDL_GetCameraThreadName (SDL_Camera *device, char *buf, size_t buflen)
bool SDL_PrepareCameraSurfaces (SDL_Camera *device)
void UnrefPhysicalCamera (SDL_Camera *device)
Variables
CameraBootStrap ANDROIDCAMERA_bootstrap
CameraBootStrap COREMEDIA_bootstrap
CameraBootStrap DUMMYCAMERA_bootstrap
CameraBootStrap EMSCRIPTENCAMERA_bootstrap
CameraBootStrap MEDIAFOUNDATION_bootstrap
CameraBootStrap PIPEWIRECAMERA_bootstrap
CameraBootStrap V4L2_bootstrap
CameraBootStrap VITACAMERA_bootstrap
Macro Definition Documentation
DEBUG_CAMERA
#define DEBUG_CAMERA 0
Typedef Documentation
CameraBootStrap
typedef struct CameraBootStrap CameraBootStrap
CameraFormatAddData
typedef struct CameraFormatAddData CameraFormatAddData
SDL_CameraDriver
typedef struct SDL_CameraDriver SDL_CameraDriver
SDL_CameraDriverImpl
typedef struct SDL_CameraDriverImpl SDL_CameraDriverImpl
SDL_CameraFrameResult
typedef enum SDL_CameraFrameResult SDL_CameraFrameResult
SDL_PendingCameraEvent
typedef struct SDL_PendingCameraEvent SDL_PendingCameraEvent
SurfaceList
typedef struct SurfaceList SurfaceList
Enumeration Type Documentation
SDL_CameraFrameResult
enum SDL_CameraFrameResult
Enumerator
SDL_CAMERA_FRAME_ERROR
SDL_CAMERA_FRAME_SKIP
SDL_CAMERA_FRAME_READY
{
    SDL_CAMERA_FRAME_ERROR,
    SDL_CAMERA_FRAME_SKIP,
    SDL_CAMERA_FRAME_READY
} SDL_CameraFrameResult;
Function Documentation
RefPhysicalCamera()
void RefPhysicalCamera (SDL_Camera * device) extern
{
    SDL_AtomicIncRef(&device->refcount);
}
References SDL_Camera::refcount, and SDL_AtomicIncRef.
Referenced by ObtainPhysicalCameraObj(), and SDL_AddCamera().
SDL_AddCamera()
SDL_Camera * SDL_AddCamera (const char * name, SDL_CameraPosition position, int num_specs, const SDL_CameraSpec * specs, void * handle) extern
{
    SDL_assert(name != NULL);
    SDL_assert(num_specs >= 0);
    SDL_assert((specs != NULL) == (num_specs > 0));
    SDL_assert(handle != NULL);
    SDL_LockRWLockForReading(camera_driver.device_hash_lock);
    const int shutting_down = SDL_GetAtomicInt(&camera_driver.shutting_down);
    SDL_UnlockRWLock(camera_driver.device_hash_lock);
    if (shutting_down) {
        return NULL;  // we're shutting down, don't add any devices that are hotplugged at the last possible moment.
    }
    SDL_Camera *device = (SDL_Camera *)SDL_calloc(1, sizeof(SDL_Camera));
    if (!device) {
        return NULL;
    }
    device->name = SDL_strdup(name);
    if (!device->name) {
        SDL_free(device);
        return NULL;
    }
    device->position = position;
    device->lock = SDL_CreateMutex();
    if (!device->lock) {
        SDL_free(device->name);
        SDL_free(device);
        return NULL;
    }
    device->all_specs = (SDL_CameraSpec *)SDL_calloc(num_specs + 1, sizeof (*specs));
    if (!device->all_specs) {
        SDL_DestroyMutex(device->lock);
        SDL_free(device->name);
        SDL_free(device);
        return NULL;
    }
    if (num_specs > 0) {
        SDL_memcpy(device->all_specs, specs, sizeof (*specs) * num_specs);
        SDL_qsort(device->all_specs, num_specs, sizeof (*specs), CameraSpecCmp);
        // weed out duplicates, just in case.
        for (int i = 0; i < num_specs; i++) {
            SDL_CameraSpec *a = &device->all_specs[i];
            SDL_CameraSpec *b = &device->all_specs[i + 1];
            if (SDL_memcmp(a, b, sizeof (*a)) == 0) {
                SDL_memmove(a, b, sizeof (*specs) * (num_specs - i));
                i--;
                num_specs--;
            }
        }
    }
    #if DEBUG_CAMERA
    const char *posstr = "unknown position";
    if (position == SDL_CAMERA_POSITION_FRONT_FACING) {
        posstr = "front-facing";
    } else if (position == SDL_CAMERA_POSITION_BACK_FACING) {
        posstr = "back-facing";
    }
    SDL_Log("CAMERA: Adding device '%s' (%s) with %d spec%s%s", name, posstr, num_specs, (num_specs == 1) ? "" : "s", (num_specs == 0) ? "" : ":");
    for (int i = 0; i < num_specs; i++) {
        const SDL_CameraSpec *spec = &device->all_specs[i];
        SDL_Log("CAMERA:   - fmt=%s, w=%d, h=%d, numerator=%d, denominator=%d", SDL_GetPixelFormatName(spec->format), spec->width, spec->height, spec->framerate_numerator, spec->framerate_denominator);
    }
    #endif
    device->num_specs = num_specs;
    device->handle = handle;
    device->instance_id = SDL_GetNextObjectID();
    SDL_SetAtomicInt(&device->shutdown, 0);
    SDL_SetAtomicInt(&device->zombie, 0);
    RefPhysicalCamera(device);
    SDL_LockRWLockForWriting(camera_driver.device_hash_lock);
    if (SDL_InsertIntoHashTable(camera_driver.device_hash, (const void *) (uintptr_t) device->instance_id, device, false)) {
        SDL_AddAtomicInt(&camera_driver.device_count, 1);
    } else {
        SDL_DestroyMutex(device->lock);
        SDL_free(device->all_specs);
        SDL_free(device->name);
        SDL_free(device);
        device = NULL;
    }
    // Add a device add event to the pending list, to be pushed when the event queue is pumped (away from any of our internal threads).
    if (device) {
        SDL_PendingCameraEvent *p = (SDL_PendingCameraEvent *) SDL_malloc(sizeof (SDL_PendingCameraEvent));
        if (p) {  // if allocation fails, you won't get an event, but we can't help that.
            p->type = SDL_EVENT_CAMERA_DEVICE_ADDED;
            p->devid = device->instance_id;
            p->next = NULL;
            SDL_assert(camera_driver.pending_events_tail != NULL);
            SDL_assert(camera_driver.pending_events_tail->next == NULL);
            camera_driver.pending_events_tail->next = p;
            camera_driver.pending_events_tail = p;
        }
    }
    SDL_UnlockRWLock(camera_driver.device_hash_lock);
    return device;
}
References SDL_Camera::all_specs, camera_driver, CameraSpecCmp(), SDL_PendingCameraEvent::devid, SDL_CameraSpec::format, SDL_CameraSpec::framerate_denominator, SDL_CameraSpec::framerate_numerator, SDL_Camera::handle, SDL_CameraSpec::height, SDL_Camera::instance_id, SDL_Camera::lock, SDL_Camera::name, SDL_PendingCameraEvent::next, NULL, SDL_Camera::num_specs, SDL_Camera::position, RefPhysicalCamera(), SDL_AddAtomicInt(), SDL_assert, SDL_calloc(), SDL_CAMERA_POSITION_BACK_FACING, SDL_CAMERA_POSITION_FRONT_FACING, SDL_CreateMutex(), SDL_DestroyMutex(), SDL_EVENT_CAMERA_DEVICE_ADDED, SDL_free(), SDL_GetAtomicInt(), SDL_GetNextObjectID(), SDL_GetPixelFormatName(), SDL_InsertIntoHashTable(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_Log(), SDL_malloc(), SDL_memcmp(), SDL_memcpy, SDL_memmove, SDL_qsort(), SDL_SetAtomicInt(), SDL_strdup(), SDL_UnlockRWLock(), SDL_Camera::shutdown, SDL_PendingCameraEvent::type, SDL_CameraSpec::width, and SDL_Camera::zombie.
SDL_AddCameraFormat()
bool SDL_AddCameraFormat (CameraFormatAddData * data, SDL_PixelFormat format, SDL_Colorspace colorspace, int w, int h, int framerate_numerator, int framerate_denominator)
{
    SDL_assert(data != NULL);
    if (data->allocated_specs <= data->num_specs) {
        const int newalloc = data->allocated_specs ? (data->allocated_specs * 2) : 16;
        void *ptr = SDL_realloc(data->specs, sizeof (SDL_CameraSpec) * newalloc);
        if (!ptr) {
            return false;
        }
        data->specs = (SDL_CameraSpec *) ptr;
        data->allocated_specs = newalloc;
    }
    SDL_CameraSpec *spec = &data->specs[data->num_specs];
    spec->format = format;
    spec->colorspace = colorspace;
    spec->width = w;
    spec->height = h;
    spec->framerate_numerator = framerate_numerator;
    spec->framerate_denominator = framerate_denominator;
    data->num_specs++;
    return true;
}
References SDL_CameraSpec::colorspace, SDL_CameraSpec::format, SDL_CameraSpec::framerate_denominator, SDL_CameraSpec::framerate_numerator, SDL_CameraSpec::height, NULL, SDL_assert, SDL_realloc(), and SDL_CameraSpec::width.
SDL_CameraDisconnected()
void SDL_CameraDisconnected (SDL_Camera * device) extern
{
    if (!device) {
        return;
    }
    #if DEBUG_CAMERA
    SDL_Log("CAMERA: DISCONNECTED! dev[%p]", device);
    #endif
    // Save off removal info in a list so we can send events for each, next
    //  time the event queue pumps, in case something tries to close a device
    //  from an event filter, as this would risk deadlocks and other disasters
    //  if done from the device thread.
    SDL_PendingCameraEvent pending;
    pending.next = NULL;
    SDL_PendingCameraEvent *pending_tail = &pending;
    ObtainPhysicalCameraObj(device);
    const bool first_disconnect = SDL_CompareAndSwapAtomicInt(&device->zombie, 0, 1);
    if (first_disconnect) {   // if already disconnected this device, don't do it twice.
        // Swap in "Zombie" versions of the usual platform interfaces, so the device will keep
        // making progress until the app closes it. Otherwise, streams might continue to
        // accumulate waste data that never drains, apps that depend on audio callbacks to
        // progress will freeze, etc.
        device->WaitDevice = ZombieWaitDevice;
        device->AcquireFrame = ZombieAcquireFrame;
        device->ReleaseFrame = ZombieReleaseFrame;
        // Zombie functions will just report the timestamp as SDL_GetTicksNS(), so we don't need to adjust anymore to get it to match.
        device->adjust_timestamp = 0;
        device->base_timestamp = 0;
        SDL_PendingCameraEvent *p = (SDL_PendingCameraEvent *) SDL_malloc(sizeof (SDL_PendingCameraEvent));
        if (p) {  // if this failed, no event for you, but you have deeper problems anyhow.
            p->type = SDL_EVENT_CAMERA_DEVICE_REMOVED;
            p->devid = device->instance_id;
            p->next = NULL;
            pending_tail->next = p;
            pending_tail = p;
        }
    }
    ReleaseCamera(device);
    if (first_disconnect) {
        if (pending.next) {  // NULL if event is disabled or disaster struck.
            SDL_LockRWLockForWriting(camera_driver.device_hash_lock);
            SDL_assert(camera_driver.pending_events_tail != NULL);
            SDL_assert(camera_driver.pending_events_tail->next == NULL);
            camera_driver.pending_events_tail->next = pending.next;
            camera_driver.pending_events_tail = pending_tail;
            SDL_UnlockRWLock(camera_driver.device_hash_lock);
        }
    }
}
References SDL_Camera::AcquireFrame, SDL_Camera::adjust_timestamp, SDL_Camera::base_timestamp, camera_driver, SDL_PendingCameraEvent::devid, SDL_Camera::instance_id, SDL_PendingCameraEvent::next, NULL, ObtainPhysicalCameraObj(), ReleaseCamera(), SDL_Camera::ReleaseFrame, SDL_assert, SDL_CompareAndSwapAtomicInt(), SDL_EVENT_CAMERA_DEVICE_REMOVED, SDL_LockRWLockForWriting(), SDL_Log(), SDL_malloc(), SDL_UnlockRWLock(), SDL_PendingCameraEvent::type, SDL_Camera::WaitDevice, SDL_Camera::zombie, ZombieAcquireFrame(), ZombieReleaseFrame(), and ZombieWaitDevice().
Referenced by CameraThread(), and SDL_CameraThreadIterate().
SDL_CameraPermissionOutcome()
void SDL_CameraPermissionOutcome (SDL_Camera * device, bool approved) extern
{
    if (!device) {
        return;
    }
    SDL_PendingCameraEvent pending;
    pending.next = NULL;
    SDL_PendingCameraEvent *pending_tail = &pending;
    const int permission = approved ? 1 : -1;
    ObtainPhysicalCameraObj(device);
    if (device->permission != permission) {
        device->permission = permission;
        SDL_PendingCameraEvent *p = (SDL_PendingCameraEvent *) SDL_malloc(sizeof (SDL_PendingCameraEvent));
        if (p) {  // if this failed, no event for you, but you have deeper problems anyhow.
            p->type = approved ? SDL_EVENT_CAMERA_DEVICE_APPROVED : SDL_EVENT_CAMERA_DEVICE_DENIED;
            p->devid = device->instance_id;
            p->next = NULL;
            pending_tail->next = p;
            pending_tail = p;
        }
    }
    ReleaseCamera(device);
    if (pending.next) {  // NULL if event is disabled or disaster struck.
        SDL_LockRWLockForWriting(camera_driver.device_hash_lock);
        SDL_assert(camera_driver.pending_events_tail != NULL);
        SDL_assert(camera_driver.pending_events_tail->next == NULL);
        camera_driver.pending_events_tail->next = pending.next;
        camera_driver.pending_events_tail = pending_tail;
        SDL_UnlockRWLock(camera_driver.device_hash_lock);
    }
}
References camera_driver, SDL_PendingCameraEvent::devid, SDL_Camera::instance_id, SDL_PendingCameraEvent::next, NULL, ObtainPhysicalCameraObj(), SDL_Camera::permission, ReleaseCamera(), SDL_assert, SDL_EVENT_CAMERA_DEVICE_APPROVED, SDL_EVENT_CAMERA_DEVICE_DENIED, SDL_LockRWLockForWriting(), SDL_malloc(), SDL_UnlockRWLock(), and SDL_PendingCameraEvent::type.
SDL_CameraThreadIterate()
bool SDL_CameraThreadIterate (SDL_Camera * device) extern
{
    SDL_LockMutex(device->lock);
    if (SDL_GetAtomicInt(&device->shutdown)) {
        SDL_UnlockMutex(device->lock);
        return false;  // we're done, shut it down.
    }
    const int permission = device->permission;
    if (permission <= 0) {
        SDL_UnlockMutex(device->lock);
        return (permission < 0) ? false : true;  // if permission was denied, shut it down. if undecided, we're done for now.
    }
    bool failed = false;  // set to true if disaster worthy of treating the device as lost has happened.
    SDL_Surface *acquired = NULL;
    SDL_Surface *output_surface = NULL;
    SurfaceList *slist = NULL;
    Uint64 timestampNS = 0;
    // AcquireFrame SHOULD NOT BLOCK, as we are holding a lock right now. Block in WaitDevice instead!
    const SDL_CameraFrameResult rc = device->AcquireFrame(device, device->acquire_surface, &timestampNS);
    if (rc == SDL_CAMERA_FRAME_READY) {  // new frame acquired!
        #if DEBUG_CAMERA
        SDL_Log("CAMERA: New frame available! pixels=%p pitch=%d", device->acquire_surface->pixels, device->acquire_surface->pitch);
        #endif
        if (device->drop_frames > 0) {
            #if DEBUG_CAMERA
            SDL_Log("CAMERA: Dropping an initial frame");
            #endif
            device->drop_frames--;
            device->ReleaseFrame(device, device->acquire_surface);
            device->acquire_surface->pixels = NULL;
            device->acquire_surface->pitch = 0;
        } else if (device->empty_output_surfaces.next == NULL) {
            // uhoh, no output frames available! Either the app is slow, or it forgot to release frames when done with them. Drop this new frame.
            #if DEBUG_CAMERA
            SDL_Log("CAMERA: No empty output surfaces! Dropping frame!");
            #endif
            device->ReleaseFrame(device, device->acquire_surface);
            device->acquire_surface->pixels = NULL;
            device->acquire_surface->pitch = 0;
        } else {
            if (!device->adjust_timestamp) {
                device->adjust_timestamp = SDL_GetTicksNS();
                device->base_timestamp = timestampNS;
            }
            timestampNS = (timestampNS - device->base_timestamp) + device->adjust_timestamp;
            slist = device->empty_output_surfaces.next;
            output_surface = slist->surface;
            device->empty_output_surfaces.next = slist->next;
            acquired = device->acquire_surface;
            slist->timestampNS = timestampNS;
        }
    } else if (rc == SDL_CAMERA_FRAME_SKIP) {  // no frame available yet; not an error.
        #if 0 //DEBUG_CAMERA
        SDL_Log("CAMERA: No frame available yet.");
        #endif
    } else {  // fatal error!
        #if DEBUG_CAMERA
        SDL_Log("CAMERA: dev[%p] error AcquireFrame: %s", device, SDL_GetError());
        #endif
        failed = true;
    }
    // we can let go of the lock once we've tried to grab a frame of video and maybe moved the output frame off the empty list.
    // this lets us chew up the CPU for conversion and scaling without blocking other threads.
    SDL_UnlockMutex(device->lock);
    if (failed) {
        SDL_assert(slist == NULL);
        SDL_assert(acquired == NULL);
        SDL_CameraDisconnected(device);  // doh.
    } else if (acquired) {  // we have a new frame, scale/convert if necessary and queue it for the app!
        SDL_assert(slist != NULL);
        if (!device->needs_scaling && !device->needs_conversion) {  // no conversion needed? Just move the pointer/pitch into the output surface.
            #if DEBUG_CAMERA
            SDL_Log("CAMERA: Frame is going through without conversion!");
            #endif
            output_surface->w = acquired->w;
            output_surface->h = acquired->h;
            output_surface->pixels = acquired->pixels;
            output_surface->pitch = acquired->pitch;
        } else {  // convert/scale into a different surface.
            #if DEBUG_CAMERA
            SDL_Log("CAMERA: Frame is getting converted!");
            #endif
            SDL_Surface *srcsurf = acquired;
            if (device->needs_scaling == -1) {  // downscaling? Do it first.  -1: downscale, 0: no scaling, 1: upscale
                SDL_Surface *dstsurf = device->needs_conversion ? device->conversion_surface : output_surface;
                SDL_StretchSurface(srcsurf, NULL, dstsurf, NULL, SDL_SCALEMODE_NEAREST);  // !!! FIXME: linear scale? letterboxing?
                srcsurf = dstsurf;
            }
            if (device->needs_conversion) {
                SDL_Surface *dstsurf = (device->needs_scaling == 1) ? device->conversion_surface : output_surface;
                SDL_ConvertPixels(srcsurf->w, srcsurf->h,
                                  srcsurf->format, srcsurf->pixels, srcsurf->pitch,
                                  dstsurf->format, dstsurf->pixels, dstsurf->pitch);
                srcsurf = dstsurf;
            }
            if (device->needs_scaling == 1) {  // upscaling? Do it last.  -1: downscale, 0: no scaling, 1: upscale
                SDL_StretchSurface(srcsurf, NULL, output_surface, NULL, SDL_SCALEMODE_NEAREST);  // !!! FIXME: linear scale? letterboxing?
            }
            // we made a copy, so we can give the driver back its resources.
            device->ReleaseFrame(device, acquired);
        }
        // we either released these already after we copied the data, or the pointer was migrated to output_surface.
        acquired->pixels = NULL;
        acquired->pitch = 0;
        // make the filled output surface available to the app.
        SDL_LockMutex(device->lock);
        slist->next = device->filled_output_surfaces.next;
        device->filled_output_surfaces.next = slist;
        SDL_UnlockMutex(device->lock);
    }
    return true;  // always go on if not shutting down, even if device failed.
}
References SDL_Camera::acquire_surface, SDL_Camera::AcquireFrame, SDL_Camera::adjust_timestamp, SDL_Camera::base_timestamp, SDL_Camera::conversion_surface, SDL_Camera::drop_frames, SDL_Camera::empty_output_surfaces, false, SDL_Camera::filled_output_surfaces, SDL_Surface::format, SDL_Surface::h, SDL_Camera::lock, SDL_Camera::needs_conversion, SDL_Camera::needs_scaling, SurfaceList::next, NULL, SDL_Camera::permission, SDL_Surface::pitch, SDL_Surface::pixels, SDL_Camera::ReleaseFrame, SDL_assert, SDL_CAMERA_FRAME_READY, SDL_CAMERA_FRAME_SKIP, SDL_CameraDisconnected(), SDL_ConvertPixels(), SDL_GetAtomicInt(), SDL_GetError(), SDL_GetTicksNS(), SDL_LockMutex(), SDL_Log(), SDL_SCALEMODE_NEAREST, SDL_StretchSurface(), SDL_UnlockMutex(), SDL_Camera::shutdown, SurfaceList::surface, SurfaceList::timestampNS, and SDL_Surface::w.
Referenced by CameraThread().
SDL_CameraThreadSetup()
void SDL_CameraThreadSetup (SDL_Camera * device) extern
{
    //camera_driver.impl.ThreadInit(device);
#ifdef SDL_VIDEO_DRIVER_ANDROID
    // TODO
    /*
    {
        // Set thread priority to THREAD_PRIORITY_VIDEO
        extern void Android_JNI_CameraSetThreadPriority(int, int);
        Android_JNI_CameraSetThreadPriority(device->recording, device);
    }*/
#else
    // The camera capture is always a high priority thread
    SDL_SetCurrentThreadPriority(SDL_THREAD_PRIORITY_HIGH);
#endif
}
References SDL_SetCurrentThreadPriority(), and SDL_THREAD_PRIORITY_HIGH.
Referenced by CameraThread().
SDL_CameraThreadShutdown()
void SDL_CameraThreadShutdown (SDL_Camera * device) extern
{
    //device->FlushRecording(device);
    //camera_driver.impl.ThreadDeinit(device);
    //SDL_CameraThreadFinalize(device);
}
Referenced by CameraThread().
SDL_FindPhysicalCameraByCallback()
SDL_Camera * SDL_FindPhysicalCameraByCallback (bool(* callback)(SDL_Camera *device, void *userdata), void * userdata) extern
{
    if (!SDL_GetCurrentCameraDriver()) {
        SDL_SetError("Camera subsystem is not initialized");
        return NULL;
    }
    FindOnePhysicalCameraByCallbackData data = { callback, userdata, NULL };
    SDL_LockRWLockForReading(camera_driver.device_hash_lock);
    SDL_IterateHashTable(camera_driver.device_hash, FindOnePhysicalCameraByCallback, &data);
    SDL_UnlockRWLock(camera_driver.device_hash_lock);
    if (!data.device) {
        SDL_SetError("Device not found");
    }
    return data.device;
}
References camera_driver, FindOnePhysicalCameraByCallback(), NULL, SDL_GetCurrentCameraDriver(), SDL_IterateHashTable(), SDL_LockRWLockForReading(), SDL_SetError(), and SDL_UnlockRWLock().
SDL_GetCameraThreadName()
char * SDL_GetCameraThreadName (SDL_Camera * device, char * buf, size_t buflen) extern
{
    (void)SDL_snprintf(buf, buflen, "SDLCamera%d", (int) device->instance_id);
    return buf;
}
References SDL_Camera::instance_id, SDL_snprintf(), and void().
Referenced by SDL_OpenCamera().
SDL_PrepareCameraSurfaces()
bool SDL_PrepareCameraSurfaces (SDL_Camera * device) extern
{
    SDL_CameraSpec *appspec = &device->spec;           // the app wants this format.
    const SDL_CameraSpec *devspec = &device->actual_spec;  // the hardware is set to this format.
    SDL_assert(device->acquire_surface == NULL);   // shouldn't call this function twice on an opened camera!
    SDL_assert(devspec->format != SDL_PIXELFORMAT_UNKNOWN);  // fix the backend, it should have an actual format by now.
    SDL_assert(devspec->width >= 0);  // fix the backend, it should have an actual format by now.
    SDL_assert(devspec->height >= 0);  // fix the backend, it should have an actual format by now.
    if (appspec->width <= 0 || appspec->height <= 0) {
        appspec->width = devspec->width;
        appspec->height = devspec->height;
    }
    if (appspec->format == SDL_PIXELFORMAT_UNKNOWN) {
        appspec->format = devspec->format;
    }
    if (appspec->framerate_denominator == 0) {
        appspec->framerate_numerator = devspec->framerate_numerator;
        appspec->framerate_denominator = devspec->framerate_denominator;
    }
    if ((devspec->width == appspec->width) && (devspec->height == appspec->height)) {
        device->needs_scaling = 0;
    } else {
        const Uint64 srcarea = ((Uint64) devspec->width) * ((Uint64) devspec->height);
        const Uint64 dstarea = ((Uint64) appspec->width) * ((Uint64) appspec->height);
        if (dstarea <= srcarea) {
            device->needs_scaling = -1;  // downscaling (or changing to new aspect ratio with same area)
        } else {
            device->needs_scaling = 1;  // upscaling
        }
    }
    device->needs_conversion = (devspec->format != appspec->format);
    device->acquire_surface = SDL_CreateSurfaceFrom(devspec->width, devspec->height, devspec->format, NULL, 0);
    if (!device->acquire_surface) {
        goto failed;
    }
    SDL_SetSurfaceColorspace(device->acquire_surface, devspec->colorspace);
    // if we have to scale _and_ convert, we need a middleman surface, since we can't do both changes at once.
    if (device->needs_scaling && device->needs_conversion) {
        const bool downscaling_first = (device->needs_scaling < 0);
        const SDL_CameraSpec *s = downscaling_first ? appspec : devspec;
        const SDL_PixelFormat fmt = downscaling_first ? devspec->format : appspec->format;
        device->conversion_surface = SDL_CreateSurface(s->width, s->height, fmt);
        if (!device->conversion_surface) {
            goto failed;
        }
        SDL_SetSurfaceColorspace(device->conversion_surface, devspec->colorspace);
    }
    // output surfaces are in the app-requested format. If no conversion is necessary, we'll just use the pointers
    // the backend fills into acquired_surface, and you can get all the way from DMA access in the camera hardware
    // to the app without a single copy. Otherwise, these will be full surfaces that hold converted/scaled copies.
    for (int i = 0; i < (SDL_arraysize(device->output_surfaces) - 1); i++) {
        device->output_surfaces[i].next = &device->output_surfaces[i + 1];
    }
    device->empty_output_surfaces.next = device->output_surfaces;
    for (int i = 0; i < SDL_arraysize(device->output_surfaces); i++) {
        SDL_Surface *surf;
        if (device->needs_scaling || device->needs_conversion) {
            surf = SDL_CreateSurface(appspec->width, appspec->height, appspec->format);
        } else {
            surf = SDL_CreateSurfaceFrom(appspec->width, appspec->height, appspec->format, NULL, 0);
        }
        if (!surf) {
            goto failed;
        }
        SDL_SetSurfaceColorspace(surf, devspec->colorspace);
        device->output_surfaces[i].surface = surf;
    }
    return true;
failed:
    if (device->acquire_surface) {
        SDL_DestroySurface(device->acquire_surface);
        device->acquire_surface = NULL;
    }
    if (device->conversion_surface) {
        SDL_DestroySurface(device->conversion_surface);
        device->conversion_surface = NULL;
    }
    for (int i = 0; i < SDL_arraysize(device->output_surfaces); i++) {
        SDL_Surface *surf = device->output_surfaces[i].surface;
        if (surf) {
            SDL_DestroySurface(surf);
        }
    }
    SDL_zeroa(device->output_surfaces);
    return false;
}
References SDL_Camera::acquire_surface, SDL_Camera::actual_spec, SDL_CameraSpec::colorspace, SDL_Camera::conversion_surface, SDL_Camera::empty_output_surfaces, SDL_CameraSpec::format, SDL_CameraSpec::framerate_denominator, SDL_CameraSpec::framerate_numerator, SDL_CameraSpec::height, SDL_Camera::needs_conversion, SDL_Camera::needs_scaling, SurfaceList::next, NULL, SDL_Camera::output_surfaces, SDL_arraysize, SDL_assert, SDL_CreateSurface(), SDL_CreateSurfaceFrom(), SDL_DestroySurface(), SDL_PIXELFORMAT_UNKNOWN, SDL_SetSurfaceColorspace(), SDL_zeroa, SDL_Camera::spec, SurfaceList::surface, and SDL_CameraSpec::width.
Referenced by SDL_OpenCamera().
UnrefPhysicalCamera()
void UnrefPhysicalCamera (SDL_Camera * device) extern
{
    if (SDL_AtomicDecRef(&device->refcount)) {
        // take it out of the device list.
        SDL_LockRWLockForWriting(camera_driver.device_hash_lock);
        if (SDL_RemoveFromHashTable(camera_driver.device_hash, (const void *) (uintptr_t) device->instance_id)) {
            SDL_AddAtomicInt(&camera_driver.device_count, -1);
        }
        SDL_UnlockRWLock(camera_driver.device_hash_lock);
    }
}
References camera_driver, SDL_Camera::instance_id, SDL_Camera::refcount, SDL_AddAtomicInt(), SDL_AtomicDecRef, SDL_LockRWLockForWriting(), SDL_RemoveFromHashTable(), and SDL_UnlockRWLock().
Referenced by ReleaseCamera().
Variable Documentation
ANDROIDCAMERA_bootstrap
CameraBootStrap ANDROIDCAMERA_bootstrap extern
COREMEDIA_bootstrap
CameraBootStrap COREMEDIA_bootstrap extern
DUMMYCAMERA_bootstrap
CameraBootStrap DUMMYCAMERA_bootstrap extern
EMSCRIPTENCAMERA_bootstrap
CameraBootStrap EMSCRIPTENCAMERA_bootstrap extern
MEDIAFOUNDATION_bootstrap
CameraBootStrap MEDIAFOUNDATION_bootstrap extern
PIPEWIRECAMERA_bootstrap
CameraBootStrap PIPEWIRECAMERA_bootstrap extern
V4L2_bootstrap
CameraBootStrap V4L2_bootstrap extern
VITACAMERA_bootstrap
CameraBootStrap VITACAMERA_bootstrap extern