SDL3: SDL-main/include/SDL3/SDL_atomic.h File Reference
SDL_atomic.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_platform_defines.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_AtomicInt
struct SDL_AtomicU32
Macros
#define SDL_AtomicDecRef(a)
#define SDL_AtomicIncRef(a)
#define SDL_CompilerBarrier()
#define SDL_CPUPauseInstruction()
#define SDL_MemoryBarrierAcquire()
#define SDL_MemoryBarrierRelease()
Typedefs
typedef struct SDL_AtomicInt SDL_AtomicInt
typedef struct SDL_AtomicU32 SDL_AtomicU32
typedef int SDL_SpinLock
Functions
SDL_DECLSPEC int SDLCALL SDL_AddAtomicInt (SDL_AtomicInt *a, int v)
SDL_DECLSPEC bool SDLCALL SDL_CompareAndSwapAtomicInt (SDL_AtomicInt *a, int oldval, int newval)
SDL_DECLSPEC bool SDLCALL SDL_CompareAndSwapAtomicPointer (void **a, void *oldval, void *newval)
SDL_DECLSPEC bool SDLCALL SDL_CompareAndSwapAtomicU32 (SDL_AtomicU32 *a, Uint32 oldval, Uint32 newval)
SDL_DECLSPEC int SDLCALL SDL_GetAtomicInt (SDL_AtomicInt *a)
SDL_DECLSPEC void *SDLCALL SDL_GetAtomicPointer (void **a)
SDL_DECLSPEC Uint32 SDLCALL SDL_GetAtomicU32 (SDL_AtomicU32 *a)
SDL_DECLSPEC void SDLCALL SDL_LockSpinlock (SDL_SpinLock *lock)
SDL_DECLSPEC void SDLCALL SDL_MemoryBarrierAcquireFunction (void)
SDL_DECLSPEC void SDLCALL SDL_MemoryBarrierReleaseFunction (void)
SDL_DECLSPEC int SDLCALL SDL_SetAtomicInt (SDL_AtomicInt *a, int v)
SDL_DECLSPEC void *SDLCALL SDL_SetAtomicPointer (void **a, void *v)
SDL_DECLSPEC Uint32 SDLCALL SDL_SetAtomicU32 (SDL_AtomicU32 *a, Uint32 v)
SDL_DECLSPEC bool SDLCALL SDL_TryLockSpinlock (SDL_SpinLock *lock)
SDL_DECLSPEC void SDLCALL SDL_UnlockSpinlock (SDL_SpinLock *lock)
Macro Definition Documentation
SDL_AtomicDecRef
#define SDL_AtomicDecRef (a)
Value:
(SDL_AddAtomicInt(a, -1) == 1)
Decrement an atomic variable used as a reference count.
Note: If you don't know what this macro is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt to decrement.
Returns
true if the variable reached zero after decrementing, false otherwise.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
See also
SDL_AtomicIncRef
Referenced by SDL_CleanupTLS(), SDL_LockJoysticks(), SDL_LockSensors(), SDL_ShowMessageBox(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().
SDL_AtomicIncRef
#define SDL_AtomicIncRef (a)
Value:
SDL_AddAtomicInt(a, 1)
Increment an atomic variable used as a reference count.
Note: If you don't know what this macro is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt to increment.
Returns
the previous value of the atomic variable.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
See also
SDL_AtomicDecRef
Referenced by AssignAudioDeviceInstanceId(), RefPhysicalAudioDevice(), RefPhysicalCamera(), SDL_GetNextObjectID(), SDL_LockJoysticks(), SDL_LockSensors(), SDL_SetTLS(), and SDL_ShowMessageBox().
SDL_CompilerBarrier
#define SDL_CompilerBarrier ()
Value:
{ SDL_SpinLock _tmp = 0; SDL_LockSpinlock(&_tmp); SDL_UnlockSpinlock(&_tmp); }
#define SDL_CompilerBarrier()   \
{ SDL_SpinLock _tmp = 0; SDL_LockSpinlock(&_tmp); SDL_UnlockSpinlock(&_tmp); }
Referenced by SDL_UnlockSpinlock().
SDL_CPUPauseInstruction
#define SDL_CPUPauseInstruction ()
Referenced by SDL_DelayPrecise(), and SDL_LockSpinlock().
SDL_MemoryBarrierAcquire
#define SDL_MemoryBarrierAcquire ()
Value:
SDL_CompilerBarrier()
Referenced by SDL_MemoryBarrierAcquireFunction().
SDL_MemoryBarrierRelease
#define SDL_MemoryBarrierRelease ()
Value:
SDL_CompilerBarrier()
Referenced by SDL_MemoryBarrierReleaseFunction().
Typedef Documentation
SDL_AtomicInt
typedef struct SDL_AtomicInt SDL_AtomicInt
A type representing an atomic integer value.
This can be used to manage a value that is synchronized across multiple CPUs without a race condition; when an app sets a value with SDL_SetAtomicInt all other threads, regardless of the CPU it is running on, will see that value when retrieved with SDL_GetAtomicInt, regardless of CPU caches, etc.
This is also useful for atomic compare-and-swap operations: a thread can change the value as long as its current value matches expectations. When done in a loop, one can guarantee data consistency across threads without a lock (but the usual warnings apply: if you don't know what you're doing, or you don't do it carefully, you can confidently cause any number of disasters with this, so in most cases, you should use a mutex instead of this!).
This is a struct so people don't accidentally use numeric operations on it directly. You have to use SDL atomic functions.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicInt
SDL_GetAtomicInt
SDL_SetAtomicInt
SDL_AddAtomicInt
SDL_AtomicU32
typedef struct SDL_AtomicU32 SDL_AtomicU32
A type representing an atomic unsigned 32-bit value.
This can be used to manage a value that is synchronized across multiple CPUs without a race condition; when an app sets a value with SDL_SetAtomicU32 all other threads, regardless of the CPU it is running on, will see that value when retrieved with SDL_GetAtomicU32, regardless of CPU caches, etc.
This is also useful for atomic compare-and-swap operations: a thread can change the value as long as its current value matches expectations. When done in a loop, one can guarantee data consistency across threads without a lock (but the usual warnings apply: if you don't know what you're doing, or you don't do it carefully, you can confidently cause any number of disasters with this, so in most cases, you should use a mutex instead of this!).
This is a struct so people don't accidentally use numeric operations on it directly. You have to use SDL atomic functions.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicU32
SDL_GetAtomicU32
SDL_SetAtomicU32
SDL_SpinLock
typedef int SDL_SpinLock
CategoryAtomic
Atomic operations.
IMPORTANT: If you are not an expert in concurrent lockless programming, you should not be using any functions in this file. You should be protecting your data structures with full mutexes instead.
Seriously, here be dragons!
You can find out a little more about lockless programming and the subtle issues that can arise here: https://learn.microsoft.com/en-us/windows/win32/dxtecharts/lockless-programming
There's also lots of good information here:
https://www.1024cores.net/home/lock-free-algorithms
https://preshing.com/
These operations may or may not actually be implemented using processor specific atomic operations. When possible they are implemented as true processor specific atomic operations. When that is not possible the are implemented using locks that do use the available atomic operations.
All of the atomic operations that modify memory are full memory barriers. An atomic spinlock.
The atomic locks are efficient spinlocks using CPU instructions, but are vulnerable to starvation and can spin forever if a thread holding a lock has been terminated. For this reason you should minimize the code executed inside an atomic lock and never do expensive things like API or system calls while holding them.
They are also vulnerable to starvation if the thread holding the lock is lower priority than other threads and doesn't get scheduled. In general you should use mutexes instead, since they have better performance and contention behavior.
The atomic locks are not safe to lock recursively.
Porting Note: The spin lock functions and type are required and can not be emulated because they are used in the atomic emulation code.
Function Documentation
SDL_AddAtomicInt()
SDL_DECLSPEC int SDLCALL SDL_AddAtomicInt (SDL_AtomicInt * a, int v) extern
Add to an atomic variable.
This function also acts as a full memory barrier.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable to be modified.
v the desired value to add.
Returns
the previous value of the atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AtomicDecRef
SDL_AtomicIncRef
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_add, sizeof(long) == sizeof(a->value));
    return _InterlockedExchangeAdd((long *)&a->value, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_add, sizeof(int) == sizeof(a->value));
    return _SDL_xadd_watcom((volatile int *)&a->value, v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_fetch_and_add(&a->value, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    int pv = a->value;
    membar_consumer();
    atomic_add_int((volatile uint_t *)&a->value, v);
    return pv;
#else
    int value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicInt(a, value, (value + v)));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicInt(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by CreatePhysicalAudioDevice(), GetAsyncIOTaskOutcome(), RequestAsyncIO(), SDL_AddCamera(), SDL_AddEvent(), SDL_CloseAsyncIO(), SDL_CutEvent(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_RegisterEvents(), SDL_TryLockRWLockForReading_generic(), SDL_TryLockRWLockForWriting_generic(), SDL_UnlockRWLock(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().
SDL_CompareAndSwapAtomicInt()
SDL_DECLSPEC bool SDLCALL SDL_CompareAndSwapAtomicInt (SDL_AtomicInt * a, int oldval, int newval) extern
Set an atomic variable to a new value if it is currently an old value.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable to be modified.
oldval the old value.
newval the new value.
Returns
true if the atomic variable was set, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicInt
SDL_SetAtomicInt
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(long) == sizeof(a->value));
    return _InterlockedCompareExchange((long *)&a->value, (long)newval, (long)oldval) == (long)oldval;
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_cmpxchg_watcom((volatile int *)&a->value, newval, oldval);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_bool_compare_and_swap(&a->value, oldval, newval);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap32Barrier(oldval, newval, &a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(uint_t) == sizeof(a->value));
    return ((int)atomic_cas_uint((volatile uint_t *)&a->value, (uint_t)oldval, (uint_t)newval) == oldval);
#elif defined(EMULATE_CAS)
    bool result = false;
    enterLock(a);
    if (a->value == oldval) {
        a->value = newval;
        result = true;
    }
    leaveLock(a);
    return result;
#else
#error Please define your platform.
#endif
}
References enterLock(), leaveLock(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by SDL_AddAtomicInt(), SDL_AudioDeviceDisconnected(), SDL_CameraDisconnected(), SDL_DetachThread(), SDL_DispatchMainCallbackEvent(), SDL_GetAtomicInt(), SDL_InitAudio(), SDL_InitMainCallbacks(), SDL_IterateMainCallbacks(), SDL_MainCallbackEventWatcher(), SDL_RunThread(), SDL_SetAtomicInt(), SDL_SetTLS(), SDL_ShouldInit(), and SDL_ShouldQuit().
SDL_CompareAndSwapAtomicPointer()
SDL_DECLSPEC bool SDLCALL SDL_CompareAndSwapAtomicPointer (void ** a, void * oldval, void * newval) extern
Set a pointer to a new value if it is currently an old value.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to a pointer.
oldval the old pointer value.
newval the new pointer value.
Returns
true if the pointer was set, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicInt
SDL_GetAtomicPointer
SDL_SetAtomicPointer
{
#ifdef HAVE_MSC_ATOMICS
    return _InterlockedCompareExchangePointer(a, newval, oldval) == oldval;
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_cmpxchg_watcom((int *)a, (long)newval, (long)oldval);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_bool_compare_and_swap(a, oldval, newval);
#elif defined(SDL_PLATFORM_MACOS) && defined(__LP64__)  // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap64Barrier((int64_t)oldval, (int64_t)newval, (int64_t *)a);
#elif defined(SDL_PLATFORM_MACOS) && !defined(__LP64__) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap32Barrier((int32_t)oldval, (int32_t)newval, (int32_t *)a);
#elif defined(SDL_PLATFORM_SOLARIS)
    return (atomic_cas_ptr(a, oldval, newval) == oldval);
#elif defined(EMULATE_CAS)
    bool result = false;
    enterLock(a);
    if (*a == oldval) {
        *a = newval;
        result = true;
    }
    leaveLock(a);
    return result;
#else
#error Please define your platform.
#endif
}
References enterLock(), and leaveLock().
Referenced by SDL_DestroyWindow(), SDL_GetAtomicPointer(), and SDL_SetAtomicPointer().
SDL_CompareAndSwapAtomicU32()
SDL_DECLSPEC bool SDLCALL SDL_CompareAndSwapAtomicU32 (SDL_AtomicU32 * a, Uint32 oldval, Uint32 newval) extern
Set an atomic variable to a new value if it is currently an old value.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicU32 variable to be modified.
oldval the old value.
newval the new value.
Returns
true if the atomic variable was set, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicU32
SDL_SetAtomicU32
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(long) == sizeof(a->value));
    return _InterlockedCompareExchange((long *)&a->value, (long)newval, (long)oldval) == (long)oldval;
#elif defined(HAVE_WATCOM_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(int) == sizeof(a->value));
    return _SDL_cmpxchg_watcom((volatile int *)&a->value, (int)newval, (int)oldval);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_bool_compare_and_swap(&a->value, oldval, newval);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicCompareAndSwap32Barrier((int32_t)oldval, (int32_t)newval, (int32_t *)&a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_cas, sizeof(uint_t) == sizeof(a->value));
    return ((Uint32)atomic_cas_uint((volatile uint_t *)&a->value, (uint_t)oldval, (uint_t)newval) == oldval);
#elif defined(EMULATE_CAS)
    bool result = false;
    enterLock(a);
    if (a->value == oldval) {
        a->value = newval;
        result = true;
    }
    leaveLock(a);
    return result;
#else
#error Please define your platform.
#endif
}
References enterLock(), leaveLock(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicU32::value.
Referenced by GetHintProperties(), SDL_CreateProperties(), SDL_GetAtomicU32(), SDL_GetGlobalProperties(), SDL_QuitHints(), SDL_QuitProperties(), and SDL_SetAtomicU32().
SDL_GetAtomicInt()
SDL_DECLSPEC int SDLCALL SDL_GetAtomicInt (SDL_AtomicInt * a) extern
Get the value of an atomic variable.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable.
Returns
the current value of an atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAtomicInt
{
#ifdef HAVE_ATOMIC_LOAD_N
    return __atomic_load_n(&a->value, __ATOMIC_SEQ_CST);
#elif defined(HAVE_MSC_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(long) == sizeof(a->value));
    return _InterlockedOr((long *)&a->value, 0);
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_xadd_watcom(&a->value, 0);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_or_and_fetch(&a->value, 0);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return sizeof(a->value) == sizeof(uint32_t) ? OSAtomicOr32Barrier(0, (volatile uint32_t *)&a->value) : OSAtomicAdd64Barrier(0, (volatile int64_t *)&a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    return atomic_or_uint_nv((volatile uint_t *)&a->value, 0);
#else
    int value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicInt(a, value, value));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicInt(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by CountAudioDevices(), CreatePhysicalAudioDevice(), GetAudioDevices(), OpenPhysicalAudioDevice(), SDL_AddCamera(), SDL_AddEvent(), SDL_AudioDevicePaused(), SDL_CameraThreadIterate(), SDL_CheckInitLog(), SDL_CutEvent(), SDL_DefaultAudioDeviceChanged(), SDL_DestroyAsyncIOQueue(), SDL_DispatchMainCallbackEvent(), SDL_GetCameras(), SDL_GetMessageBoxCount(), SDL_GetNumAllocations(), SDL_GetThreadState(), SDL_GetTLS(), SDL_InitMainCallbacks(), SDL_IterateMainCallbacks(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_OpenAudioDevice(), SDL_PeepEventsInternal(), SDL_PlaybackAudioThreadIterate(), SDL_PlaybackAudioThreadShutdown(), SDL_PumpEventsInternal(), SDL_QuitTLSData(), SDL_RecordingAudioThreadIterate(), SDL_RemoveTimer(), SDL_RunOnMainThread(), SDL_SetTLS(), SDL_ShouldInit(), SDL_ShouldQuit(), SDL_TimerThread(), SDL_TryLockRWLockForReading_generic(), SDL_TryLockRWLockForWriting_generic(), SDL_UnlockJoysticks(), SDL_UnlockRWLock(), SDL_UnlockSensors(), SDL_WaitEventTimeoutNS(), SerializePhysicalDeviceClose(), ZombieWaitDevice(), and ZombieWaitDevice().
SDL_GetAtomicPointer()
SDL_DECLSPEC void *SDLCALL SDL_GetAtomicPointer (void ** a) extern
Get the value of a pointer atomically.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to a pointer.
Returns
the current value of a pointer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicPointer
SDL_SetAtomicPointer
{
#ifdef HAVE_ATOMIC_LOAD_N
    return __atomic_load_n(a, __ATOMIC_SEQ_CST);
#elif defined(HAVE_MSC_ATOMICS)
    return _InterlockedCompareExchangePointer(a, NULL, NULL);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_val_compare_and_swap(a, (void *)0, (void *)0);
#elif defined(SDL_PLATFORM_SOLARIS)
    return atomic_cas_ptr(a, (void *)0, (void *)0);
#else
    void *value;
    do {
        value = *a;
    } while (!SDL_CompareAndSwapAtomicPointer(a, value, value));
    return value;
#endif
}
References NULL, and SDL_CompareAndSwapAtomicPointer().
Referenced by ObtainLogicalAudioDevice().
SDL_GetAtomicU32()
SDL_DECLSPEC Uint32 SDLCALL SDL_GetAtomicU32 (SDL_AtomicU32 * a) extern
Get the value of an atomic variable.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicU32 variable.
Returns
the current value of an atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAtomicU32
{
#ifdef HAVE_ATOMIC_LOAD_N
    return __atomic_load_n(&a->value, __ATOMIC_SEQ_CST);
#elif defined(HAVE_MSC_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(long) == sizeof(a->value));
    return (Uint32)_InterlockedOr((long *)&a->value, 0);
#elif defined(HAVE_WATCOM_ATOMICS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(int) == sizeof(a->value));
    return (Uint32)_SDL_xadd_watcom((volatile int *)&a->value, 0);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_or_and_fetch(&a->value, 0);
#elif defined(SDL_PLATFORM_MACOS) // this is deprecated in 10.12 sdk; favor gcc atomics.
    return OSAtomicOr32Barrier(0, (volatile uint32_t *)&a->value);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_get, sizeof(uint_t) == sizeof(a->value));
    return (Uint32)atomic_or_uint_nv((volatile uint_t *)&a->value, 0);
#else
    Uint32 value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicU32(a, value, value));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicU32(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicU32::value.
Referenced by GetHintProperties(), SDL_CreateProperties(), SDL_GetGlobalProperties(), SDL_QuitHints(), and SDL_QuitProperties().
SDL_LockSpinlock()
SDL_DECLSPEC void SDLCALL SDL_LockSpinlock (SDL_SpinLock * lock) extern
Lock a spin lock by setting it to a non-zero value.
Please note that spinlocks are dangerous if you don't know what you're doing. Please be careful using any sort of spinlock!
Parameters
lock a pointer to a lock variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_TryLockSpinlock
SDL_UnlockSpinlock
{
    int iterations = 0;
    // FIXME: Should we have an eventual timeout?
    while (!SDL_TryLockSpinlock(lock)) {
        if (iterations < 32) {
            iterations++;
            SDL_CPUPauseInstruction();
        } else {
            // !!! FIXME: this doesn't definitely give up the current timeslice, it does different things on various platforms.
            SDL_Delay(0);
        }
    }
}
References lock, SDL_CPUPauseInstruction, SDL_Delay(), and SDL_TryLockSpinlock().
Referenced by enterLock(), SDL_CreateTimer(), SDL_ReportAssertion(), and SDL_TimerThread().
SDL_MemoryBarrierAcquireFunction()
SDL_DECLSPEC void SDLCALL SDL_MemoryBarrierAcquireFunction (void) extern
Insert a memory acquire barrier (function version).
Please refer to SDL_MemoryBarrierRelease for details. This is a function version, which might be useful if you need to use this functionality from a scripting language, etc. Also, some of the macro versions call this function behind the scenes, where more heavy lifting can happen inside of SDL. Generally, though, an app written in C/C++/etc should use the macro version, as it will be more efficient.
Thread Safety
Obviously this function is safe to use from any thread at any time, but if you find yourself needing this, you are probably dealing with some very sensitive code; be careful!
Since
This function is available since SDL 3.2.0.
See also
SDL_MemoryBarrierAcquire
{
    SDL_MemoryBarrierAcquire();
}
References SDL_MemoryBarrierAcquire.
SDL_MemoryBarrierReleaseFunction()
SDL_DECLSPEC void SDLCALL SDL_MemoryBarrierReleaseFunction (void) extern
Insert a memory release barrier (function version).
Please refer to SDL_MemoryBarrierRelease for details. This is a function version, which might be useful if you need to use this functionality from a scripting language, etc. Also, some of the macro versions call this function behind the scenes, where more heavy lifting can happen inside of SDL. Generally, though, an app written in C/C++/etc should use the macro version, as it will be more efficient.
Thread Safety
Obviously this function is safe to use from any thread at any time, but if you find yourself needing this, you are probably dealing with some very sensitive code; be careful!
Since
This function is available since SDL 3.2.0.
See also
SDL_MemoryBarrierRelease
{
    SDL_MemoryBarrierRelease();
}
References SDL_MemoryBarrierRelease.
SDL_SetAtomicInt()
SDL_DECLSPEC int SDLCALL SDL_SetAtomicInt (SDL_AtomicInt * a, int v) extern
Set an atomic variable to a value.
This function also acts as a full memory barrier.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicInt variable to be modified.
v the desired value.
Returns
the previous value of the atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicInt
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(long) == sizeof(a->value));
    return _InterlockedExchange((long *)&a->value, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_xchg_watcom(&a->value, v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_lock_test_and_set(&a->value, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(uint_t) == sizeof(a->value));
    return (int)atomic_swap_uint((volatile uint_t *)&a->value, v);
#else
    int value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicInt(a, value, v));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicInt(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicInt::value.
Referenced by ClosePhysicalAudioDevice(), ClosePhysicalCamera(), CreatePhysicalAudioDevice(), SDL_AddCamera(), SDL_CreateAsyncIOQueue(), SDL_CreateMainThreadCallback(), SDL_CreateRWLock(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateTimer(), SDL_InitMainCallbacks(), SDL_InitTimers(), SDL_OpenAudioDevice(), SDL_OpenAudioDeviceStream(), SDL_OpenCamera(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_QuitMainThreadCallbacks(), SDL_QuitTimers(), SDL_RemoveTimer(), SDL_RunMainThreadCallbacks(), SDL_SetInitialized(), SDL_StopEventLoop(), SDL_TimerThread(), and SetLogicalAudioDevicePauseState().
SDL_SetAtomicPointer()
SDL_DECLSPEC void *SDLCALL SDL_SetAtomicPointer (void ** a, void * v) extern
Set a pointer to a value atomically.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to a pointer.
v the desired pointer value.
Returns
the previous value of the pointer.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CompareAndSwapAtomicPointer
SDL_GetAtomicPointer
{
#ifdef HAVE_MSC_ATOMICS
    return _InterlockedExchangePointer(a, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    return (void *)_SDL_xchg_watcom((int *)a, (long)v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_lock_test_and_set(a, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    return atomic_swap_ptr(a, v);
#else
    void *value;
    do {
        value = *a;
    } while (!SDL_CompareAndSwapAtomicPointer(a, value, v));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicPointer().
Referenced by SDL_SendWakeupEvent(), and SDL_WaitEventTimeout_Device().
SDL_SetAtomicU32()
SDL_DECLSPEC Uint32 SDLCALL SDL_SetAtomicU32 (SDL_AtomicU32 * a, Uint32 v) extern
Set an atomic variable to a value.
This function also acts as a full memory barrier.
Note: If you don't know what this function is for, you shouldn't use it!
Parameters
a a pointer to an SDL_AtomicU32 variable to be modified.
v the desired value.
Returns
the previous value of the atomic variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAtomicU32
{
#ifdef HAVE_MSC_ATOMICS
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(long) == sizeof(a->value));
    return _InterlockedExchange((long *)&a->value, v);
#elif defined(HAVE_WATCOM_ATOMICS)
    return _SDL_xchg_watcom(&a->value, v);
#elif defined(HAVE_GCC_ATOMICS)
    return __sync_lock_test_and_set(&a->value, v);
#elif defined(SDL_PLATFORM_SOLARIS)
    SDL_COMPILE_TIME_ASSERT(atomic_set, sizeof(uint_t) == sizeof(a->value));
    return (Uint32)atomic_swap_uint((volatile uint_t *)&a->value, v);
#else
    Uint32 value;
    do {
        value = a->value;
    } while (!SDL_CompareAndSwapAtomicU32(a, value, v));
    return value;
#endif
}
References SDL_CompareAndSwapAtomicU32(), SDL_COMPILE_TIME_ASSERT, and SDL_AtomicU32::value.
SDL_TryLockSpinlock()
SDL_DECLSPEC bool SDLCALL SDL_TryLockSpinlock (SDL_SpinLock * lock) extern
Try to lock a spin lock by setting it to a non-zero value.
Please note that spinlocks are dangerous if you don't know what you're doing. Please be careful using any sort of spinlock!
Parameters
lock a pointer to a lock variable.
Returns
true if the lock succeeded, false if the lock is already held.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockSpinlock
SDL_UnlockSpinlock
{
#if defined(HAVE_GCC_ATOMICS) || defined(HAVE_GCC_SYNC_LOCK_TEST_AND_SET)
    return __sync_lock_test_and_set(lock, 1) == 0;
#elif defined(_MSC_VER) && (defined(_M_ARM) || defined(_M_ARM64))
    return _InterlockedExchange_acq(lock, 1) == 0;
#elif defined(_MSC_VER)
    SDL_COMPILE_TIME_ASSERT(locksize, sizeof(*lock) == sizeof(long));
    return InterlockedExchange((long *)lock, 1) == 0;
#elif defined(__WATCOMC__) && defined(__386__)
    return _SDL_xchg_watcom(lock, 1) == 0;
#elif defined(__GNUC__) && defined(__arm__) &&               \
    (defined(__ARM_ARCH_3__) || defined(__ARM_ARCH_3M__) ||  \
     defined(__ARM_ARCH_4__) || defined(__ARM_ARCH_4T__) ||  \
     defined(__ARM_ARCH_5__) || defined(__ARM_ARCH_5TE__) || \
     defined(__ARM_ARCH_5TEJ__))
    int result;
#ifdef SDL_PLATFORM_RISCOS
    if (__cpucap_have_rex()) {
        __asm__ __volatile__(
            "ldrex %0, [%2]\nteq   %0, #0\nstrexeq %0, %1, [%2]"
            : "=&r"(result)
            : "r"(1), "r"(lock)
            : "cc", "memory");
        return result == 0;
    }
#endif
    __asm__ __volatile__(
        "swp %0, %1, [%2]\n"
        : "=&r,&r"(result)
        : "r,0"(1), "r,r"(lock)
        : "memory");
    return result == 0;
#elif defined(__GNUC__) && defined(__arm__)
    int result;
    __asm__ __volatile__(
        "ldrex %0, [%2]\nteq   %0, #0\nstrexeq %0, %1, [%2]"
        : "=&r"(result)
        : "r"(1), "r"(lock)
        : "cc", "memory");
    return result == 0;
#elif defined(__GNUC__) && (defined(__i386__) || defined(__x86_64__))
    int result;
    __asm__ __volatile__(
        "lock ; xchgl %0, (%1)\n"
        : "=r"(result)
        : "r"(lock), "0"(1)
        : "cc", "memory");
    return result == 0;
#elif defined(SDL_PLATFORM_MACOS) || defined(SDL_PLATFORM_IOS) || defined(SDL_PLATFORM_TVOS)
    // Maybe used for PowerPC, but the Intel asm or gcc atomics are favored.
    return OSAtomicCompareAndSwap32Barrier(0, 1, lock);
#elif defined(SDL_PLATFORM_SOLARIS) && defined(_LP64)
    // Used for Solaris with non-gcc compilers.
    return ((int)atomic_cas_64((volatile uint64_t *)lock, 0, 1) == 0);
#elif defined(SDL_PLATFORM_SOLARIS) && !defined(_LP64)
    // Used for Solaris with non-gcc compilers.
    return ((int)atomic_cas_32((volatile uint32_t *)lock, 0, 1) == 0);
#elif defined(PS2)
    uint32_t oldintr;
    bool res = false;
    // disable interruption
    oldintr = DIntr();
    if (*lock == 0) {
        *lock = 1;
        res = true;
    }
    // enable interruption
    if (oldintr) {
        EIntr();
    }
    return res;
#else
    // Terrible terrible damage
    static SDL_Mutex *_spinlock_mutex;
    if (!_spinlock_mutex) {
        // Race condition on first lock...
        _spinlock_mutex = SDL_CreateMutex();
    }
    SDL_LockMutex(_spinlock_mutex);
    if (*lock == 0) {
        *lock = 1;
        SDL_UnlockMutex(_spinlock_mutex);
        return true;
    } else {
        SDL_UnlockMutex(_spinlock_mutex);
        return false;
    }
#endif
}
References lock, SDL_COMPILE_TIME_ASSERT, SDL_CreateMutex(), SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_LockSpinlock().
SDL_UnlockSpinlock()
SDL_DECLSPEC void SDLCALL SDL_UnlockSpinlock (SDL_SpinLock * lock) extern
Unlock a spin lock by setting it to 0.
Always returns immediately.
Please note that spinlocks are dangerous if you don't know what you're doing. Please be careful using any sort of spinlock!
Parameters
lock a pointer to a lock variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockSpinlock
SDL_TryLockSpinlock
{
#if defined(HAVE_GCC_ATOMICS) || defined(HAVE_GCC_SYNC_LOCK_TEST_AND_SET)
    __sync_lock_release(lock);
#elif defined(_MSC_VER) && (defined(_M_ARM) || defined(_M_ARM64))
    _InterlockedExchange_rel(lock, 0);
#elif defined(_MSC_VER)
    _ReadWriteBarrier();
    *lock = 0;
#elif defined(__WATCOMC__) && defined(__386__)
    SDL_CompilerBarrier();
    *lock = 0;
#elif defined(SDL_PLATFORM_SOLARIS)
    // Used for Solaris when not using gcc.
    *lock = 0;
    membar_producer();
#else
    *lock = 0;
#endif
}
References lock, and SDL_CompilerBarrier.
Referenced by leaveLock(), SDL_CreateTimer(), SDL_ReportAssertion(), and SDL_TimerThread().