SDL3: SDL-main/include/SDL3/SDL_mutex.h File Reference
SDL_mutex.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_atomic.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_thread.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_InitState
Macros
#define SDL_ACQUIRE(x)
#define SDL_ACQUIRE_SHARED(x)
#define SDL_ACQUIRED_AFTER(x)
#define SDL_ACQUIRED_BEFORE(x)
#define SDL_ASSERT_CAPABILITY(x)
#define SDL_ASSERT_SHARED_CAPABILITY(x)
#define SDL_CAPABILITY(x)
#define SDL_EXCLUDES(x)
#define SDL_GUARDED_BY(x)
#define SDL_NO_THREAD_SAFETY_ANALYSIS SDL_THREAD_ANNOTATION_ATTRIBUTE__(no_thread_safety_analysis)
#define SDL_PT_GUARDED_BY(x)
#define SDL_RELEASE(x)
#define SDL_RELEASE_GENERIC(x)
#define SDL_RELEASE_SHARED(x)
#define SDL_REQUIRES(x)
#define SDL_REQUIRES_SHARED(x)
#define SDL_RETURN_CAPABILITY(x)
#define SDL_SCOPED_CAPABILITY SDL_THREAD_ANNOTATION_ATTRIBUTE__(scoped_lockable)
#define SDL_THREAD_ANNOTATION_ATTRIBUTE__(x)
#define SDL_TRY_ACQUIRE(x, y)
#define SDL_TRY_ACQUIRE_SHARED(x, y)
Thread-safe initialization state functions
typedef struct SDL_InitState SDL_InitState
enum SDL_InitStatus { SDL_INIT_STATUS_UNINITIALIZED , SDL_INIT_STATUS_INITIALIZING , SDL_INIT_STATUS_INITIALIZED , SDL_INIT_STATUS_UNINITIALIZING }
typedef enum SDL_InitStatus SDL_InitStatus
SDL_DECLSPEC void SDLCALL SDL_SetInitialized (SDL_InitState *state, bool initialized)
SDL_DECLSPEC bool SDLCALL SDL_ShouldInit (SDL_InitState *state)
SDL_DECLSPEC bool SDLCALL SDL_ShouldQuit (SDL_InitState *state)
Mutex functions
SDL_DECLSPEC SDL_Mutex *SDLCALL SDL_CreateMutex (void)
SDL_DECLSPEC void SDLCALL SDL_DestroyMutex (SDL_Mutex *mutex)
SDL_DECLSPEC void SDLCALL SDL_LockMutex (SDL_Mutex *mutex)
typedef struct SDL_Mutex SDL_Mutex
SDL_DECLSPEC bool SDLCALL SDL_TryLockMutex (SDL_Mutex *mutex)
SDL_DECLSPEC void SDLCALL SDL_UnlockMutex (SDL_Mutex *mutex)
Read/write lock functions
SDL_DECLSPEC SDL_RWLock *SDLCALL SDL_CreateRWLock (void)
SDL_DECLSPEC void SDLCALL SDL_DestroyRWLock (SDL_RWLock *rwlock)
SDL_DECLSPEC void SDLCALL SDL_LockRWLockForReading (SDL_RWLock *rwlock)
SDL_DECLSPEC void SDLCALL SDL_LockRWLockForWriting (SDL_RWLock *rwlock)
typedef struct SDL_RWLock SDL_RWLock
SDL_DECLSPEC bool SDLCALL SDL_TryLockRWLockForReading (SDL_RWLock *rwlock)
SDL_DECLSPEC bool SDLCALL SDL_TryLockRWLockForWriting (SDL_RWLock *rwlock)
SDL_DECLSPEC void SDLCALL SDL_UnlockRWLock (SDL_RWLock *rwlock)
Semaphore functions
SDL_DECLSPEC SDL_Semaphore *SDLCALL SDL_CreateSemaphore (Uint32 initial_value)
SDL_DECLSPEC void SDLCALL SDL_DestroySemaphore (SDL_Semaphore *sem)
SDL_DECLSPEC Uint32 SDLCALL SDL_GetSemaphoreValue (SDL_Semaphore *sem)
typedef struct SDL_Semaphore SDL_Semaphore
SDL_DECLSPEC void SDLCALL SDL_SignalSemaphore (SDL_Semaphore *sem)
SDL_DECLSPEC bool SDLCALL SDL_TryWaitSemaphore (SDL_Semaphore *sem)
SDL_DECLSPEC void SDLCALL SDL_WaitSemaphore (SDL_Semaphore *sem)
SDL_DECLSPEC bool SDLCALL SDL_WaitSemaphoreTimeout (SDL_Semaphore *sem, Sint32 timeoutMS)
Condition variable functions
SDL_DECLSPEC void SDLCALL SDL_BroadcastCondition (SDL_Condition *cond)
typedef struct SDL_Condition SDL_Condition
SDL_DECLSPEC SDL_Condition *SDLCALL SDL_CreateCondition (void)
SDL_DECLSPEC void SDLCALL SDL_DestroyCondition (SDL_Condition *cond)
SDL_DECLSPEC void SDLCALL SDL_SignalCondition (SDL_Condition *cond)
SDL_DECLSPEC void SDLCALL SDL_WaitCondition (SDL_Condition *cond, SDL_Mutex *mutex)
SDL_DECLSPEC bool SDLCALL SDL_WaitConditionTimeout (SDL_Condition *cond, SDL_Mutex *mutex, Sint32 timeoutMS)
Macro Definition Documentation
SDL_ACQUIRE
#define SDL_ACQUIRE (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquire_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_ACQUIRE(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquire_capability(x))
SDL_ACQUIRE_SHARED
#define SDL_ACQUIRE_SHARED (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquire_shared_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_ACQUIRE_SHARED(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquire_shared_capability(x))
SDL_ACQUIRED_AFTER
#define SDL_ACQUIRED_AFTER (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquired_after(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_ACQUIRED_AFTER(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquired_after(x))
SDL_ACQUIRED_BEFORE
#define SDL_ACQUIRED_BEFORE (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquired_before(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_ACQUIRED_BEFORE(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(acquired_before(x))
SDL_ASSERT_CAPABILITY
#define SDL_ASSERT_CAPABILITY (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(assert_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_ASSERT_CAPABILITY(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(assert_capability(x))
SDL_ASSERT_SHARED_CAPABILITY
#define SDL_ASSERT_SHARED_CAPABILITY (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(assert_shared_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_ASSERT_SHARED_CAPABILITY(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(assert_shared_capability(x))
SDL_CAPABILITY
#define SDL_CAPABILITY (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_CAPABILITY(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(capability(x))
SDL_EXCLUDES
#define SDL_EXCLUDES (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(locks_excluded(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_EXCLUDES(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(locks_excluded(x))
SDL_GUARDED_BY
#define SDL_GUARDED_BY (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(guarded_by(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_GUARDED_BY(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(guarded_by(x))
SDL_NO_THREAD_SAFETY_ANALYSIS
#define SDL_NO_THREAD_SAFETY_ANALYSIS SDL_THREAD_ANNOTATION_ATTRIBUTE__(no_thread_safety_analysis)
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_NO_THREAD_SAFETY_ANALYSIS \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(no_thread_safety_analysis)
Referenced by ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), ObtainPhysicalCameraObj(), ReleaseAudioDevice(), ReleaseCamera(), SDL_LockMutex(), SDL_LockMutex(), SDL_LockRWLockForReading(), SDL_LockRWLockForReading(), SDL_LockRWLockForReading_srw(), SDL_LockRWLockForWriting(), SDL_LockRWLockForWriting(), SDL_LockRWLockForWriting_srw(), SDL_UnlockMutex(), SDL_UnlockMutex(), SDL_UnlockRWLock(), SDL_UnlockRWLock(), and SDL_UnlockRWLock_srw().
SDL_PT_GUARDED_BY
#define SDL_PT_GUARDED_BY (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(pt_guarded_by(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_PT_GUARDED_BY(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(pt_guarded_by(x))
SDL_RELEASE
#define SDL_RELEASE (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(release_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_RELEASE(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(release_capability(x))
SDL_RELEASE_GENERIC
#define SDL_RELEASE_GENERIC (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(release_generic_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_RELEASE_GENERIC(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(release_generic_capability(x))
SDL_RELEASE_SHARED
#define SDL_RELEASE_SHARED (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(release_shared_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_RELEASE_SHARED(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(release_shared_capability(x))
SDL_REQUIRES
#define SDL_REQUIRES (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(requires_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_REQUIRES(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(requires_capability(x))
SDL_REQUIRES_SHARED
#define SDL_REQUIRES_SHARED (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(requires_shared_capability(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_REQUIRES_SHARED(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(requires_shared_capability(x))
SDL_RETURN_CAPABILITY
#define SDL_RETURN_CAPABILITY (x)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(lock_returned(x))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_RETURN_CAPABILITY(x) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(lock_returned(x))
SDL_SCOPED_CAPABILITY
#define SDL_SCOPED_CAPABILITY SDL_THREAD_ANNOTATION_ATTRIBUTE__(scoped_lockable)
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_SCOPED_CAPABILITY \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(scoped_lockable)
SDL_THREAD_ANNOTATION_ATTRIBUTE__
#define SDL_THREAD_ANNOTATION_ATTRIBUTE__ (x)
Value:
/* no-op */
CategoryMutex
SDL offers several thread synchronization primitives. This document can't cover the complicated topic of thread safety, but reading up on what each of these primitives are, why they are useful, and how to correctly use them is vital to writing correct and safe multithreaded programs.
Mutexes: SDL_CreateMutex()
Read/Write locks: SDL_CreateRWLock()
Semaphores: SDL_CreateSemaphore()
Condition variables: SDL_CreateCondition()
SDL also offers a datatype, SDL_InitState, which can be used to make sure only one thread initializes/deinitializes some resource that several threads might try to use for the first time simultaneously.
SDL_TRY_ACQUIRE
#define SDL_TRY_ACQUIRE (x, y)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(try_acquire_capability(x, y))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_TRY_ACQUIRE(x, y) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(try_acquire_capability(x, y))
SDL_TRY_ACQUIRE_SHARED
#define SDL_TRY_ACQUIRE_SHARED (x, y)
Value:
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(try_acquire_shared_capability(x, y))
Wrapper around Clang thread safety analysis annotations.
Please see https://clang.llvm.org/docs/ThreadSafetyAnalysis.html#mutex-h
Since
This macro is available since SDL 3.2.0.
#define SDL_TRY_ACQUIRE_SHARED(x, y) \
  SDL_THREAD_ANNOTATION_ATTRIBUTE__(try_acquire_shared_capability(x, y))
Typedef Documentation
SDL_Condition
typedef struct SDL_Condition SDL_Condition
A means to block multiple threads until a condition is satisfied.
Condition variables, paired with an SDL_Mutex, let an app halt multiple threads until a condition has occurred, at which time the app can release one or all waiting threads.
Wikipedia has a thorough explanation of the concept:
https://en.wikipedia.org/wiki/Condition_variable
Since
This struct is available since SDL 3.2.0.
SDL_InitState
typedef struct SDL_InitState SDL_InitState
A structure used for thread-safe initialization and shutdown.
Here is an example of using this:
static SDL_InitState init;
bool InitSystem(void)
{
    if (!SDL_ShouldInit(&init)) {
        // The system is initialized
        return true;
    }
    // At this point, you should not leave this function without calling SDL_SetInitialized()
    bool initialized = DoInitTasks();
    SDL_SetInitialized(&init, initialized);
    return initialized;
}
bool UseSubsystem(void)
{
    if (SDL_ShouldInit(&init)) {
        // Error, the subsystem isn't initialized
        SDL_SetInitialized(&init, false);
        return false;
    }
    // Do work using the initialized subsystem
    return true;
}
void QuitSystem(void)
{
    if (!SDL_ShouldQuit(&init)) {
        // The system is not initialized
        return;
    }
    // At this point, you should not leave this function without calling SDL_SetInitialized()
    DoQuitTasks();
    SDL_SetInitialized(&init, false);
}
Note that this doesn't protect any resources created during initialization, or guarantee that nobody is using those resources during cleanup. You should use other mechanisms to protect those, if that's a concern for your code.
Since
This struct is available since SDL 3.2.0.
SDL_InitStatus
typedef enum SDL_InitStatus SDL_InitStatus
The current status of an SDL_InitState structure.
Since
This enum is available since SDL 3.2.0.
SDL_Mutex
typedef struct SDL_Mutex SDL_Mutex
A means to serialize access to a resource between threads.
Mutexes (short for "mutual exclusion") are a synchronization primitive that allows exactly one thread to proceed at a time.
Wikipedia has a thorough explanation of the concept:
https://en.wikipedia.org/wiki/Mutex
Since
This struct is available since SDL 3.2.0.
SDL_RWLock
typedef struct SDL_RWLock SDL_RWLock
A mutex that allows read-only threads to run in parallel.
A rwlock is roughly the same concept as SDL_Mutex, but allows threads that request read-only access to all hold the lock at the same time. If a thread requests write access, it will block until all read-only threads have released the lock, and no one else can hold the thread (for reading or writing) at the same time as the writing thread.
This can be more efficient in cases where several threads need to access data frequently, but changes to that data are rare.
There are other rules that apply to rwlocks that don't apply to mutexes, about how threads are scheduled and when they can be recursively locked. These are documented in the other rwlock functions.
Since
This struct is available since SDL 3.2.0.
SDL_Semaphore
typedef struct SDL_Semaphore SDL_Semaphore
A means to manage access to a resource, by count, between threads.
Semaphores (specifically, "counting semaphores"), let X number of threads request access at the same time, each thread granted access decrementing a counter. When the counter reaches zero, future requests block until a prior thread releases their request, incrementing the counter again.
Wikipedia has a thorough explanation of the concept:
https://en.wikipedia.org/wiki/Semaphore_(programming)
Since
This struct is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_InitStatus
enum SDL_InitStatus
The current status of an SDL_InitState structure.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_INIT_STATUS_UNINITIALIZED
SDL_INIT_STATUS_INITIALIZING
SDL_INIT_STATUS_INITIALIZED
SDL_INIT_STATUS_UNINITIALIZING
{
    SDL_INIT_STATUS_UNINITIALIZED,
    SDL_INIT_STATUS_INITIALIZING,
    SDL_INIT_STATUS_INITIALIZED,
    SDL_INIT_STATUS_UNINITIALIZING
} SDL_InitStatus;
Function Documentation
SDL_BroadcastCondition()
SDL_DECLSPEC void SDLCALL SDL_BroadcastCondition (SDL_Condition * cond) extern
Restart all threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    SDL_cond_generic *cond = (SDL_cond_generic *)_cond;
    if (!cond) {
        return;
    }
#ifndef SDL_THREADS_DISABLED
    /* If there are waiting threads not already signalled, then
       signal the condition and wait for the thread to respond.
     */
    SDL_WaitSemaphore(cond->signal_sem);
    if (cond->num_waiting > cond->num_signals) {
        const int num_waiting = (cond->num_waiting - cond->num_signals);
        cond->num_signals = cond->num_waiting;
        for (int i = 0; i < num_waiting; i++) {
            SDL_SignalSemaphore(cond->sem);
        }
        /* Now all released threads are blocked here, waiting for us.
           Collect them all (and win fabulous prizes!) :-)
         */
        SDL_SignalSemaphore(cond->signal_sem);
        for (int i = 0; i < num_waiting; i++) {
            SDL_WaitSemaphore(cond->handshake_sem);
        }
    } else {
        SDL_SignalSemaphore(cond->signal_sem);
    }
#endif
}
References SDL_Condition::cond, SDL_cond_generic::handshake_sem, SDL_cond_generic::num_signals, SDL_cond_generic::num_waiting, SDL_cond_impl_active, SDL_SignalSemaphore(), SDL_WaitSemaphore(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by AsyncIOThreadpoolWorker(), ClosePhysicalAudioDevice(), generic_asyncioqueue_signal(), hidapi_thread_cond_broadcast(), QueueAsyncIOTask(), SDL_UnlockRWLock(), SDL_WaitThreadBarrier(), and ShutdownThreadpool().
SDL_CreateCondition()
SDL_DECLSPEC SDL_Condition *SDLCALL SDL_CreateCondition (void) extern
Create a condition variable.
Returns
a new condition variable or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
SDL_DestroyCondition
{
    SDL_cond_generic *cond = (SDL_cond_generic *)SDL_calloc(1, sizeof(*cond));
#ifndef SDL_THREADS_DISABLED
    if (cond) {
        cond->sem = SDL_CreateSemaphore(0);
        cond->handshake_sem = SDL_CreateSemaphore(0);
        cond->signal_sem = SDL_CreateSemaphore(1);
        if (!cond->sem || !cond->handshake_sem || !cond->signal_sem) {
            SDL_DestroyCondition_generic((SDL_Condition *)cond);
            cond = NULL;
        }
    }
#endif
    return (SDL_Condition *)cond;
}
References SDL_Condition::cond, SDL_cond_generic::handshake_sem, kernel32, NULL, pSleepConditionVariableCS, pSleepConditionVariableSRW, pWakeAllConditionVariable, pWakeConditionVariable, SDL_assert, SDL_calloc(), SDL_cond_impl_active, SDL_cond_impl_cv, SDL_cond_impl_generic, SDL_copyp, SDL_CreateMutex(), SDL_CreateSemaphore(), SDL_DestroyCondition_generic, SDL_DestroyMutex(), SDL_free(), SDL_malloc(), SDL_mutex_impl_active, SDL_MUTEX_INVALID, SDL_SetError(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by CreatePhysicalAudioDevice(), hidapi_thread_state_init(), PrepareThreadpool(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateThreadBarrier(), and SDL_SYS_CreateAsyncIOQueue_Generic().
SDL_CreateMutex()
SDL_DECLSPEC SDL_Mutex *SDLCALL SDL_CreateMutex (void) extern
Create a new mutex.
All newly-created mutexes begin in the unlocked state.
Calls to SDL_LockMutex() will not return while the mutex is locked by another thread. See SDL_TryLockMutex() to attempt to lock without blocking.
SDL mutexes are reentrant.
Returns
the initialized and unlocked mutex or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyMutex
SDL_LockMutex
SDL_TryLockMutex
SDL_UnlockMutex
{
    SDL_Mutex *mutex = (SDL_Mutex *)SDL_calloc(1, sizeof(*mutex));
#ifndef SDL_THREADS_DISABLED
    if (mutex) {
        // Create the mutex semaphore, with initial value 1
        mutex->sem = SDL_CreateSemaphore(1);
        mutex->recursive = 0;
        mutex->owner = 0;
        if (!mutex->sem) {
            SDL_free(mutex);
            mutex = NULL;
        }
    }
#endif // !SDL_THREADS_DISABLED
    return mutex;
}
References SDL_Mutex::id, NULL, SDL_Mutex::owner, SDL_Mutex::recursive, SDL_calloc(), SDL_CreateSemaphore(), SDL_free(), SDL_SetError(), and SDL_Mutex::sem.
Referenced by CreatePhysicalAudioDevice(), hidapi_thread_state_init(), PrepareThreadpool(), SDL_AddCamera(), SDL_AsyncIOFromFile(), SDL_CreateAudioStream(), SDL_CreateCondition(), SDL_CreateEnvironment(), SDL_CreateProperties(), SDL_CreateRendererWithProperties(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateThreadBarrier(), SDL_Generic_InitTLSData(), SDL_InitEventWatchList(), SDL_InitJoysticks(), SDL_InitLog(), SDL_InitMainThreadCallbacks(), SDL_InitSensors(), SDL_InitTimers(), SDL_ReportAssertion(), SDL_StartEventLoop(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), and SDL_TryLockSpinlock().
SDL_CreateRWLock()
SDL_DECLSPEC SDL_RWLock *SDLCALL SDL_CreateRWLock (void) extern
Create a new read/write lock.
A read/write lock is useful for situations where you have multiple threads trying to access a resource that is rarely updated. All threads requesting a read-only lock will be allowed to run in parallel; if a thread requests a write lock, it will be provided exclusive access. This makes it safe for multiple threads to use a resource at the same time if they promise not to change it, and when it has to be changed, the rwlock will serve as a gateway to make sure those changes can be made safely.
In the right situation, a rwlock can be more efficient than a mutex, which only lets a single thread proceed at a time, even if it won't be modifying the data.
All newly-created read/write locks begin in the unlocked state.
Calls to SDL_LockRWLockForReading() and SDL_LockRWLockForWriting will not return while the rwlock is locked for writing by another thread. See SDL_TryLockRWLockForReading() and SDL_TryLockRWLockForWriting() to attempt to lock without blocking.
SDL read/write locks are only recursive for read-only locks! They are not guaranteed to be fair, or provide access in a FIFO manner! They are not guaranteed to favor writers. You may not lock a rwlock for both read-only and write access at the same time from the same thread (so you can't promote your read-only lock to a write lock without unlocking first).
Returns
the initialized and unlocked read/write lock or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyRWLock
SDL_LockRWLockForReading
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
    SDL_RWLock *rwlock = (SDL_RWLock *) SDL_calloc(1, sizeof (*rwlock));
    if (!rwlock) {
        return NULL;
    }
#ifndef SDL_THREADS_DISABLED
    rwlock->lock = SDL_CreateMutex();
    if (!rwlock->lock) {
        SDL_free(rwlock);
        return NULL;
    }
    rwlock->condition = SDL_CreateCondition();
    if (!rwlock->condition) {
        SDL_DestroyMutex(rwlock->lock);
        SDL_free(rwlock);
        return NULL;
    }
    SDL_SetAtomicInt(&rwlock->reader_count, 0);
    SDL_SetAtomicInt(&rwlock->writer_count, 0);
#endif
    return rwlock;
}
References SDL_RWLock::condition, SDL_RWLock::id, kernel32, SDL_RWLock::lock, LOOKUP_SRW_SYM, NULL, SDL_RWLock::reader_count, SDL_calloc(), SDL_copyp, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroyMutex(), SDL_free(), SDL_rwlock_impl_active, SDL_rwlock_impl_generic, SDL_rwlock_impl_srw, SDL_SetAtomicInt(), SDL_SetError(), and SDL_RWLock::writer_count.
Referenced by SDL_CameraInit(), SDL_CreateHashTable(), SDL_InitAudio(), and SDL_InitPen().
SDL_CreateSemaphore()
SDL_DECLSPEC SDL_Semaphore *SDLCALL SDL_CreateSemaphore (Uint32 initial_value) extern
Create a semaphore.
This function creates a new semaphore and initializes it with the value initial_value. Each wait operation on the semaphore will atomically decrement the semaphore value and potentially block if the semaphore value is 0. Each post operation will atomically increment the semaphore value and wake waiting threads and allow them to retry the wait operation.
Parameters
initial_value the starting value of the semaphore.
Returns
a new semaphore or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroySemaphore
SDL_SignalSemaphore
SDL_TryWaitSemaphore
SDL_GetSemaphoreValue
SDL_WaitSemaphore
SDL_WaitSemaphoreTimeout
{
    SDL_Semaphore *sem;
    sem = (SDL_Semaphore *)SDL_malloc(sizeof(*sem));
    if (!sem) {
        return NULL;
    }
    sem->count = initial_value;
    sem->waiters_count = 0;
    sem->count_lock = SDL_CreateMutex();
    sem->count_nonzero = SDL_CreateCondition();
    if (!sem->count_lock || !sem->count_nonzero) {
        SDL_DestroySemaphore(sem);
        return NULL;
    }
    return sem;
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, NULL, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroySemaphore(), SDL_free(), SDL_malloc(), SDL_SetError(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_CreateCondition(), SDL_CreateMainThreadCallback(), SDL_CreateMutex(), and SDL_InitTimers().
SDL_DestroyCondition()
SDL_DECLSPEC void SDLCALL SDL_DestroyCondition (SDL_Condition * cond) extern
Destroy a condition variable.
Parameters
cond the condition variable to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateCondition
{
    SDL_cond_generic *cond = (SDL_cond_generic *)_cond;
    if (cond) {
        if (cond->sem) {
            SDL_DestroySemaphore(cond->sem);
        }
        if (cond->handshake_sem) {
            SDL_DestroySemaphore(cond->handshake_sem);
        }
        if (cond->signal_sem) {
            SDL_DestroySemaphore(cond->signal_sem);
        }
        SDL_free(cond);
    }
}
References SDL_Condition::cond, SDL_cond_generic::handshake_sem, SDL_cond_impl_active, SDL_DestroySemaphore(), SDL_free(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by CreatePhysicalAudioDevice(), DestroyPhysicalAudioDevice(), generic_asyncioqueue_destroy(), hidapi_thread_state_destroy(), PrepareThreadpool(), SDL_DestroyRWLock(), SDL_DestroySemaphore(), SDL_DestroyThreadBarrier(), and ShutdownThreadpool().
SDL_DestroyMutex()
SDL_DECLSPEC void SDLCALL SDL_DestroyMutex (SDL_Mutex * mutex) extern
Destroy a mutex created with SDL_CreateMutex().
This function must be called on any mutex that is no longer needed. Failure to destroy a mutex will result in a system memory or resource leak. While it is safe to destroy a mutex that is unlocked, it is not safe to attempt to destroy a locked mutex, and may result in undefined behavior depending on the platform.
Parameters
mutex the mutex to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateMutex
{
    if (mutex) {
        if (mutex->sem) {
            SDL_DestroySemaphore(mutex->sem);
        }
        SDL_free(mutex);
    }
}
References SDL_Mutex::id, SDL_DestroySemaphore(), SDL_free(), and SDL_Mutex::sem.
Referenced by CreatePhysicalAudioDevice(), DestroyCameraHashItem(), DestroyPhysicalAudioDevice(), generic_asyncio_destroy(), generic_asyncioqueue_destroy(), GetAsyncIOTaskOutcome(), hidapi_thread_state_destroy(), PrepareThreadpool(), SDL_AddCamera(), SDL_AssertionsQuit(), SDL_AsyncIOFromFile(), SDL_CreateCondition(), SDL_CreateProperties(), SDL_CreateRWLock(), SDL_DestroyAudioStream(), SDL_DestroyEnvironment(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroyRWLock(), SDL_DestroySemaphore(), SDL_DestroyThreadBarrier(), SDL_FreeProperties(), SDL_Generic_QuitTLSData(), SDL_QuitEventWatchList(), SDL_QuitLog(), SDL_QuitMainThreadCallbacks(), SDL_QuitTimers(), SDL_StopEventLoop(), SDL_SYS_AsyncIOFromFile_Generic(), SDL_SYS_CreateAsyncIOQueue_Generic(), SDL_UnlockJoysticks(), SDL_UnlockSensors(), and ShutdownThreadpool().
SDL_DestroyRWLock()
SDL_DECLSPEC void SDLCALL SDL_DestroyRWLock (SDL_RWLock * rwlock) extern
Destroy a read/write lock created with SDL_CreateRWLock().
This function must be called on any read/write lock that is no longer needed. Failure to destroy a rwlock will result in a system memory or resource leak. While it is safe to destroy a rwlock that is unlocked, it is not safe to attempt to destroy a locked rwlock, and may result in undefined behavior depending on the platform.
Parameters
rwlock the rwlock to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRWLock
{
    if (rwlock) {
#ifndef SDL_THREADS_DISABLED
        SDL_DestroyMutex(rwlock->lock);
        SDL_DestroyCondition(rwlock->condition);
#endif
        SDL_free(rwlock);
    }
}
References SDL_RWLock::condition, SDL_RWLock::id, SDL_RWLock::lock, SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_free(), and SDL_rwlock_impl_active.
Referenced by SDL_CameraInit(), SDL_DestroyHashTable(), SDL_InitAudio(), SDL_QuitAudio(), SDL_QuitCamera(), and SDL_QuitPen().
SDL_DestroySemaphore()
SDL_DECLSPEC void SDLCALL SDL_DestroySemaphore (SDL_Semaphore * sem) extern
Destroy a semaphore.
It is not safe to destroy a semaphore if there are threads currently waiting on it.
Parameters
sem the semaphore to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateSemaphore
{
    if (sem) {
        sem->count = 0xFFFFFFFF;
        while (sem->waiters_count > 0) {
            SDL_SignalCondition(sem->count_nonzero);
            SDL_Delay(10);
        }
        SDL_DestroyCondition(sem->count_nonzero);
        if (sem->count_lock) {
            SDL_LockMutex(sem->count_lock);
            SDL_UnlockMutex(sem->count_lock);
            SDL_DestroyMutex(sem->count_lock);
        }
        SDL_free(sem);
    }
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, SDL_Delay(), SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_free(), SDL_LockMutex(), SDL_SignalCondition(), SDL_UnlockMutex(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_CreateSemaphore(), SDL_DestroyCondition(), SDL_DestroyMainThreadCallback(), SDL_DestroyMutex(), and SDL_QuitTimers().
SDL_GetSemaphoreValue()
SDL_DECLSPEC Uint32 SDLCALL SDL_GetSemaphoreValue (SDL_Semaphore * sem) extern
Get the current value of a semaphore.
Parameters
sem the semaphore to query.
Returns
the current value of the semaphore.
Since
This function is available since SDL 3.2.0.
{
    Uint32 value;
    value = 0;
    if (sem) {
        SDL_LockMutex(sem->count_lock);
        value = sem->count;
        SDL_UnlockMutex(sem->count_lock);
    }
    return value;
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_Semaphore::sem.
SDL_LockMutex()
SDL_DECLSPEC void SDLCALL SDL_LockMutex (SDL_Mutex * mutex) extern
Lock the mutex.
This will block until the mutex is available, which is to say it is in the unlocked state and the OS has chosen the caller as the next thread to lock it. Of all threads waiting to lock the mutex, only one may do so at a time.
It is legal for the owning thread to lock an already-locked mutex. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive mutex").
This function does not fail; if mutex is NULL, it will return immediately having locked nothing. If the mutex is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
mutex the mutex to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_TryLockMutex
SDL_UnlockMutex
{
#ifndef SDL_THREADS_DISABLED
    if (mutex != NULL) {
        SDL_ThreadID this_thread = SDL_GetCurrentThreadID();
        if (mutex->owner == this_thread) {
            ++mutex->recursive;
        } else {
            /* The order of operations is important.
               We set the locking thread id after we obtain the lock
               so unlocks from other threads will fail.
             */
            SDL_WaitSemaphore(mutex->sem);
            mutex->owner = this_thread;
            mutex->recursive = 0;
        }
    }
#endif // SDL_THREADS_DISABLED
}
References NULL, SDL_assert, SDL_GetCurrentThreadID(), SDL_NO_THREAD_SAFETY_ANALYSIS, and SDL_WaitSemaphore().
Referenced by AsyncIOTaskComplete(), AsyncIOThreadpoolWorker(), ClosePhysicalAudioDevice(), DestroyLogicalAudioDevice(), DestroyPhysicalAudioDevice(), generic_asyncioqueue_cancel_task(), generic_asyncioqueue_get_results(), generic_asyncioqueue_signal(), generic_asyncioqueue_wait_results(), GetAsyncIOTaskOutcome(), hidapi_thread_mutex_lock(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), ObtainPhysicalCameraObj(), PutAudioStreamBuffer(), QueueAsyncIOTask(), RequestAsyncIO(), SDL_AddEventWatchList(), SDL_BindAudioStreams(), SDL_CameraThreadIterate(), SDL_ClearAudioStream(), SDL_CloseAsyncIO(), SDL_CopyProperties(), SDL_CreateTimer(), SDL_DestroySemaphore(), SDL_DispatchEventWatchList(), SDL_EnumerateProperties(), SDL_FilterEvents(), SDL_FlushAudioStream(), SDL_FlushEvents(), SDL_Generic_GetTLSData(), SDL_Generic_QuitTLSData(), SDL_Generic_SetTLSData(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), SDL_GetAudioStreamDevice(), SDL_GetAudioStreamFormat(), SDL_GetAudioStreamFrequencyRatio(), SDL_GetAudioStreamGain(), SDL_GetAudioStreamInputChannelMap(), SDL_GetAudioStreamOutputChannelMap(), SDL_GetAudioStreamProperties(), SDL_GetAudioStreamQueued(), SDL_GetBooleanProperty(), SDL_GetEnvironmentVariable(), SDL_GetEnvironmentVariables(), SDL_GetEventFilter(), SDL_GetFloatProperty(), SDL_GetLogOutputFunction(), SDL_GetLogPriority(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetSemaphoreValue(), SDL_GetStringProperty(), SDL_HasEvents(), SDL_LockAudioStream(), SDL_LockJoysticks(), SDL_LockProperties(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_LockSensors(), SDL_LogMessageV(), SDL_PeepEventsInternal(), SDL_PlaybackAudioThreadIterate(), SDL_PrivateSetProperty(), SDL_PutAudioStreamPlanarData(), SDL_QuitMainThreadCallbacks(), SDL_RecordingAudioThreadIterate(), SDL_RemoveEventWatchList(), SDL_RemoveTimer(), SDL_ReportAssertion(), SDL_ResetLogPriorities(), SDL_RunMainThreadCallbacks(), SDL_RunOnMainThread(), SDL_SetAudioStreamFormat(), SDL_SetAudioStreamFrequencyRatio(), SDL_SetAudioStreamGain(), SDL_SetAudioStreamGetCallback(), SDL_SetAudioStreamPutCallback(), SDL_SetEnvironmentVariable(), SDL_SetEventFilter(), SDL_SetLogOutputFunction(), SDL_SetLogPriorities(), SDL_SetLogPriority(), SDL_SetLogPriorityPrefix(), SDL_SetRenderTarget(), SDL_SignalSemaphore(), SDL_StartEventLoop(), SDL_StopEventLoop(), SDL_TryLockSpinlock(), SDL_UnbindAudioStreams(), SDL_UnlockJoysticks(), SDL_UnlockRWLock(), SDL_UnlockSensors(), SDL_UnsetEnvironmentVariable(), SDL_WaitConditionTimeoutNS_generic(), SDL_WaitSemaphoreTimeoutNS(), SDL_WaitThreadBarrier(), SetAudioStreamChannelMap(), ShutdownThreadpool(), SynchronousIO(), and UpdateAudioStreamFormatsPhysical().
SDL_LockRWLockForReading()
SDL_DECLSPEC void SDLCALL SDL_LockRWLockForReading (SDL_RWLock * rwlock) extern
Lock the read/write lock for read only operations.
This will block until the rwlock is available, which is to say it is not locked for writing by any other thread. Of all threads waiting to lock the rwlock, all may do so at the same time as long as they are requesting read-only access; if a thread wants to lock for writing, only one may do so at a time, and no other threads, read-only or not, may hold the lock at the same time.
It is legal for the owning thread to lock an already-locked rwlock for reading. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive rwlock").
Note that locking for writing is not recursive (this is only available to read-only locks).
It is illegal to request a read-only lock from a thread that already holds the write lock. Doing so results in undefined behavior. Unlock the write lock before requesting a read-only lock. (But, of course, if you have the write lock, you don't need further locks to read in any case.)
This function does not fail; if rwlock is NULL, it will return immediately having locked nothing. If the rwlock is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
rwlock the read/write lock to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_UnlockRWLock
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        // !!! FIXME: these don't have to be atomic, we always gate them behind a mutex.
        SDL_LockMutex(rwlock->lock);
        SDL_assert(SDL_GetAtomicInt(&rwlock->writer_count) == 0);  // shouldn't be able to grab lock if there's a writer!
        SDL_AddAtomicInt(&rwlock->reader_count, 1);
        SDL_UnlockMutex(rwlock->lock);   // other readers can attempt to share the lock.
    }
#endif
}
References SDL_AddAtomicInt(), SDL_assert, SDL_GetAtomicInt(), SDL_LockMutex(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_impl_active, and SDL_UnlockMutex().
Referenced by CreatePhysicalAudioDevice(), GetAudioDevices(), GetFirstAddedAudioDevice(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), ObtainPhysicalCamera(), SDL_AddCamera(), SDL_AudioDeviceDisconnected(), SDL_FindInHashTable(), SDL_FindPenByCallback(), SDL_FindPenByHandle(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetAudioDeviceName(), SDL_GetCameras(), SDL_GetPenStatus(), SDL_HashTableEmpty(), SDL_IterateHashTable(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_UpdateAudio(), and SDL_UpdateCamera().
SDL_LockRWLockForWriting()
SDL_DECLSPEC void SDLCALL SDL_LockRWLockForWriting (SDL_RWLock * rwlock) extern
Lock the read/write lock for write operations.
This will block until the rwlock is available, which is to say it is not locked for reading or writing by any other thread. Only one thread may hold the lock when it requests write access; all other threads, whether they also want to write or only want read-only access, must wait until the writer thread has released the lock.
It is illegal for the owning thread to lock an already-locked rwlock for writing (read-only may be locked recursively, writing can not). Doing so results in undefined behavior.
It is illegal to request a write lock from a thread that already holds a read-only lock. Doing so results in undefined behavior. Unlock the read-only lock before requesting a write lock.
This function does not fail; if rwlock is NULL, it will return immediately having locked nothing. If the rwlock is valid, this function will always block until it can lock the mutex, and return with it locked.
Parameters
rwlock the read/write lock to lock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        SDL_LockMutex(rwlock->lock);
        while (SDL_GetAtomicInt(&rwlock->reader_count) > 0) {  // while something is holding the shared lock, keep waiting.
            SDL_WaitCondition(rwlock->condition, rwlock->lock);  // release the lock and wait for readers holding the shared lock to release it, regrab the lock.
        }
        // we hold the lock!
        SDL_AddAtomicInt(&rwlock->writer_count, 1);  // we let these be recursive, but the API doesn't require this. It _does_ trust you unlock correctly!
    }
#endif
}
References SDL_AddAtomicInt(), SDL_assert, SDL_GetAtomicInt(), SDL_LockMutex(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_impl_active, and SDL_WaitCondition().
Referenced by CreatePhysicalAudioDevice(), DestroyLogicalAudioDevice(), OnAudioStreamCreated(), OnAudioStreamDestroy(), SDL_AddAudioDevice(), SDL_AddCamera(), SDL_AddPenDevice(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CameraDisconnected(), SDL_CameraPermissionOutcome(), SDL_ClearHashTable(), SDL_DefaultAudioDeviceChanged(), SDL_InsertIntoHashTable(), SDL_OpenAudioDevice(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_RemoveAllPenDevices(), SDL_RemoveFromHashTable(), SDL_RemovePenDevice(), SDL_UpdateAudio(), SDL_UpdateCamera(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().
SDL_SetInitialized()
SDL_DECLSPEC void SDLCALL SDL_SetInitialized (SDL_InitState * state, bool initialized) extern
Finish an initialization state transition.
This function sets the status of the passed in state to SDL_INIT_STATUS_INITIALIZED or SDL_INIT_STATUS_UNINITIALIZED and allows any threads waiting for the status to proceed.
Parameters
state the initialization state to check.
initialized the new initialization state.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShouldInit
SDL_ShouldQuit
{
    SDL_assert(state->thread == SDL_GetCurrentThreadID());
    if (initialized) {
        SDL_SetAtomicInt(&state->status, SDL_INIT_STATUS_INITIALIZED);
    } else {
        SDL_SetAtomicInt(&state->status, SDL_INIT_STATUS_UNINITIALIZED);
    }
}
References SDL_assert, SDL_GetCurrentThreadID(), SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_UNINITIALIZED, SDL_SetAtomicInt(), SDL_InitState::status, and SDL_InitState::thread.
Referenced by PrepareThreadpool(), SDL_GetPixelFormatDetails(), SDL_InitLog(), SDL_InitProperties(), SDL_InitTimers(), SDL_QuitLog(), SDL_QuitPixelFormatDetails(), SDL_QuitProperties(), SDL_QuitTimers(), SDL_SetObjectsInvalid(), SDL_SetObjectValid(), SDL_SetupAudioResampler(), and ShutdownThreadpool().
SDL_ShouldInit()
SDL_DECLSPEC bool SDLCALL SDL_ShouldInit (SDL_InitState * state) extern
Return whether initialization should be done.
This function checks the passed in state and if initialization should be done, sets the status to SDL_INIT_STATUS_INITIALIZING and returns true. If another thread is already modifying this state, it will wait until that's done before returning.
If this function returns true, the calling code must call SDL_SetInitialized() to complete the initialization.
Parameters
state the initialization state to check.
Returns
true if initialization needs to be done, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetInitialized
SDL_ShouldQuit
{
    while (SDL_GetAtomicInt(&state->status) != SDL_INIT_STATUS_INITIALIZED) {
        if (SDL_CompareAndSwapAtomicInt(&state->status, SDL_INIT_STATUS_UNINITIALIZED, SDL_INIT_STATUS_INITIALIZING)) {
            state->thread = SDL_GetCurrentThreadID();
            return true;
        }
        // Wait for the other thread to complete transition
        SDL_Delay(1);
    }
    return false;
}
References SDL_CompareAndSwapAtomicInt(), SDL_Delay(), SDL_GetAtomicInt(), SDL_GetCurrentThreadID(), SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_INITIALIZING, SDL_INIT_STATUS_UNINITIALIZED, SDL_InitState::status, and SDL_InitState::thread.
Referenced by PrepareThreadpool(), SDL_GetPixelFormatDetails(), SDL_InitLog(), SDL_InitProperties(), SDL_InitTimers(), SDL_SetObjectValid(), and SDL_SetupAudioResampler().
SDL_ShouldQuit()
SDL_DECLSPEC bool SDLCALL SDL_ShouldQuit (SDL_InitState * state) extern
Return whether cleanup should be done.
This function checks the passed in state and if cleanup should be done, sets the status to SDL_INIT_STATUS_UNINITIALIZING and returns true.
If this function returns true, the calling code must call SDL_SetInitialized() to complete the cleanup.
Parameters
state the initialization state to check.
Returns
true if cleanup needs to be done, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetInitialized
SDL_ShouldInit
{
    while (SDL_GetAtomicInt(&state->status) != SDL_INIT_STATUS_UNINITIALIZED) {
        if (SDL_CompareAndSwapAtomicInt(&state->status, SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_UNINITIALIZING)) {
            state->thread = SDL_GetCurrentThreadID();
            return true;
        }
        // Wait for the other thread to complete transition
        SDL_Delay(1);
    }
    return false;
}
References SDL_CompareAndSwapAtomicInt(), SDL_Delay(), SDL_GetAtomicInt(), SDL_GetCurrentThreadID(), SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_UNINITIALIZED, SDL_INIT_STATUS_UNINITIALIZING, SDL_InitState::status, and SDL_InitState::thread.
Referenced by SDL_QuitLog(), SDL_QuitPixelFormatDetails(), SDL_QuitProperties(), SDL_QuitTimers(), SDL_SetObjectsInvalid(), and ShutdownThreadpool().
SDL_SignalCondition()
SDL_DECLSPEC void SDLCALL SDL_SignalCondition (SDL_Condition * cond) extern
Restart one of the threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    SDL_cond_generic *cond = (SDL_cond_generic *)_cond;
    if (!cond) {
        return;
    }
#ifndef SDL_THREADS_DISABLED
    /* If there are waiting threads not already signalled, then
       signal the condition and wait for the thread to respond.
     */
    SDL_WaitSemaphore(cond->signal_sem);
    if (cond->num_waiting > cond->num_signals) {
        cond->num_signals++;
        SDL_SignalSemaphore(cond->sem);
        SDL_SignalSemaphore(cond->signal_sem);
        SDL_WaitSemaphore(cond->handshake_sem);
    } else {
        SDL_SignalSemaphore(cond->signal_sem);
    }
#endif
}
References SDL_Condition::cond, SDL_cond_generic::handshake_sem, SDL_cond_generic::num_signals, SDL_cond_generic::num_waiting, SDL_cond_impl_active, SDL_SignalSemaphore(), SDL_WaitSemaphore(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by AsyncIOTaskComplete(), hidapi_thread_cond_signal(), SDL_DestroySemaphore(), and SDL_SignalSemaphore().
SDL_SignalSemaphore()
SDL_DECLSPEC void SDLCALL SDL_SignalSemaphore (SDL_Semaphore * sem) extern
Atomically increment a semaphore's value and wake waiting threads.
Parameters
sem the semaphore to increment.
Since
This function is available since SDL 3.2.0.
See also
SDL_TryWaitSemaphore
SDL_WaitSemaphore
SDL_WaitSemaphoreTimeout
{
    if (!sem) {
        return;
    }
    SDL_LockMutex(sem->count_lock);
    if (sem->waiters_count > 0) {
        SDL_SignalCondition(sem->count_nonzero);
    }
    ++sem->count;
    SDL_UnlockMutex(sem->count_lock);
}
References SDL_Semaphore::count, SDL_Semaphore::count_lock, SDL_Semaphore::count_nonzero, SDL_LockMutex(), SDL_SignalCondition(), SDL_UnlockMutex(), SDL_Semaphore::sem, and SDL_Semaphore::waiters_count.
Referenced by SDL_BroadcastCondition(), SDL_CreateTimer(), SDL_QuitMainThreadCallbacks(), SDL_QuitTimers(), SDL_RunMainThreadCallbacks(), SDL_SignalCondition(), SDL_UnlockMutex(), and SDL_WaitConditionTimeoutNS_generic().
SDL_TryLockMutex()
SDL_DECLSPEC bool SDLCALL SDL_TryLockMutex (SDL_Mutex * mutex) extern
Try to lock a mutex without blocking.
This works just like SDL_LockMutex(), but if the mutex is not available, this function returns false immediately.
This technique is useful if you need exclusive access to a resource but don't want to wait for it, and will return to it to try again later.
This function returns true if passed a NULL mutex.
Parameters
mutex the mutex to try to lock.
Returns
true on success, false if the mutex would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockMutex
SDL_UnlockMutex
{
    bool result = true;
#ifndef SDL_THREADS_DISABLED
    if (mutex) {
        SDL_ThreadID this_thread = SDL_GetCurrentThreadID();
        if (mutex->owner == this_thread) {
            ++mutex->recursive;
        } else {
            /* The order of operations is important.
               We set the locking thread id after we obtain the lock
               so unlocks from other threads will fail.
             */
            result = SDL_TryWaitSemaphore(mutex->sem);
            if (result) {
                mutex->owner = this_thread;
                mutex->recursive = 0;
            }
        }
    }
#endif // SDL_THREADS_DISABLED
    return result;
}
References SDL_Mutex::id, SDL_Mutex::owner, SDL_Mutex::recursive, SDL_assert, SDL_GetCurrentThreadID(), SDL_TryWaitSemaphore(), and SDL_Mutex::sem.
Referenced by SDL_TryLockRWLockForReading_generic(), and SDL_TryLockRWLockForWriting_generic().
SDL_TryLockRWLockForReading()
SDL_DECLSPEC bool SDLCALL SDL_TryLockRWLockForReading (SDL_RWLock * rwlock) extern
Try to lock a read/write lock for reading without blocking.
This works just like SDL_LockRWLockForReading(), but if the rwlock is not available, then this function returns false immediately.
This technique is useful if you need access to a resource but don't want to wait for it, and will return to it to try again later.
Trying to lock for read-only access can succeed if other threads are holding read-only locks, as this won't prevent access.
This function returns true if passed a NULL rwlock.
Parameters
rwlock the rwlock to try to lock.
Returns
true on success, false if the lock would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_TryLockRWLockForWriting
SDL_UnlockRWLock
{
    return SDL_TryLockRWLockForReading_generic(rwlock);
}
References SDL_RWLock::id, SDL_assert, SDL_rwlock_impl_active, and SDL_TryLockRWLockForReading_generic().
SDL_TryLockRWLockForWriting()
SDL_DECLSPEC bool SDLCALL SDL_TryLockRWLockForWriting (SDL_RWLock * rwlock) extern
Try to lock a read/write lock for writing without blocking.
This works just like SDL_LockRWLockForWriting(), but if the rwlock is not available, then this function returns false immediately.
This technique is useful if you need exclusive access to a resource but don't want to wait for it, and will return to it to try again later.
It is illegal for the owning thread to lock an already-locked rwlock for writing (read-only may be locked recursively, writing can not). Doing so results in undefined behavior.
It is illegal to request a write lock from a thread that already holds a read-only lock. Doing so results in undefined behavior. Unlock the read-only lock before requesting a write lock.
This function returns true if passed a NULL rwlock.
Parameters
rwlock the rwlock to try to lock.
Returns
true on success, false if the lock would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_UnlockRWLock
{
    return SDL_TryLockRWLockForWriting_generic(rwlock);
}
References SDL_RWLock::id, SDL_assert, SDL_rwlock_impl_active, and SDL_TryLockRWLockForWriting_generic().
SDL_TryWaitSemaphore()
SDL_DECLSPEC bool SDLCALL SDL_TryWaitSemaphore (SDL_Semaphore * sem) extern
See if a semaphore has a positive value and decrement it if it does.
This function checks to see if the semaphore pointed to by sem has a positive value and atomically decrements the semaphore value if it does. If the semaphore doesn't have a positive value, the function immediately returns false.
Parameters
sem the semaphore to wait on.
Returns
true if the wait succeeds, false if the wait would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalSemaphore
SDL_WaitSemaphore
SDL_WaitSemaphoreTimeout
{
    return SDL_WaitSemaphoreTimeoutNS(sem, 0);
}
References SDL_WaitSemaphoreTimeoutNS().
Referenced by SDL_TryLockMutex().
SDL_UnlockMutex()
SDL_DECLSPEC void SDLCALL SDL_UnlockMutex (SDL_Mutex * mutex) extern
Unlock the mutex.
It is legal for the owning thread to lock an already-locked mutex. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive mutex").
It is illegal to unlock a mutex that has not been locked by the current thread, and doing so results in undefined behavior.
Parameters
mutex the mutex to unlock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockMutex
SDL_TryLockMutex
{
#ifndef SDL_THREADS_DISABLED
    if (mutex != NULL) {
        // If we don't own the mutex, we can't unlock it
        if (SDL_GetCurrentThreadID() != mutex->owner) {
            SDL_assert(!"Tried to unlock a mutex we don't own!");
            return; // (undefined behavior!) SDL_SetError("mutex not owned by this thread");
        }
        if (mutex->recursive) {
            --mutex->recursive;
        } else {
            /* The order of operations is important.
               First reset the owner so another thread doesn't lock
               the mutex and set the ownership before we reset it,
               then release the lock semaphore.
             */
            mutex->owner = 0;
            SDL_SignalSemaphore(mutex->sem);
        }
    }
#endif // SDL_THREADS_DISABLED
}
References NULL, SDL_assert, SDL_GetCurrentThreadID(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_SetError(), and SDL_SignalSemaphore().
Referenced by AsyncIOTaskComplete(), AsyncIOThreadpoolWorker(), ClosePhysicalAudioDevice(), DestroyLogicalAudioDevice(), DestroyPhysicalAudioDevice(), generic_asyncioqueue_cancel_task(), generic_asyncioqueue_get_results(), generic_asyncioqueue_signal(), generic_asyncioqueue_wait_results(), GetAsyncIOTaskOutcome(), hidapi_thread_mutex_unlock(), ObtainLogicalAudioDevice(), PutAudioStreamBuffer(), QueueAsyncIOTask(), ReleaseAudioDevice(), ReleaseCamera(), RequestAsyncIO(), SDL_AddEventWatchList(), SDL_BindAudioStreams(), SDL_CameraThreadIterate(), SDL_ClearAudioStream(), SDL_CloseAsyncIO(), SDL_CopyProperties(), SDL_CreateTimer(), SDL_DestroySemaphore(), SDL_DispatchEventWatchList(), SDL_EnumerateProperties(), SDL_FilterEvents(), SDL_FlushAudioStream(), SDL_FlushEvents(), SDL_Generic_GetTLSData(), SDL_Generic_QuitTLSData(), SDL_Generic_SetTLSData(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), SDL_GetAudioStreamDevice(), SDL_GetAudioStreamFormat(), SDL_GetAudioStreamFrequencyRatio(), SDL_GetAudioStreamGain(), SDL_GetAudioStreamInputChannelMap(), SDL_GetAudioStreamOutputChannelMap(), SDL_GetAudioStreamProperties(), SDL_GetAudioStreamQueued(), SDL_GetBooleanProperty(), SDL_GetEnvironmentVariable(), SDL_GetEnvironmentVariables(), SDL_GetEventFilter(), SDL_GetFloatProperty(), SDL_GetLogOutputFunction(), SDL_GetLogPriority(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetSemaphoreValue(), SDL_GetStringProperty(), SDL_HasEvents(), SDL_LockRWLockForReading(), SDL_LogMessageV(), SDL_PeepEventsInternal(), SDL_PlaybackAudioThreadIterate(), SDL_PrivateSetProperty(), SDL_PutAudioStreamPlanarData(), SDL_QuitMainThreadCallbacks(), SDL_RecordingAudioThreadIterate(), SDL_RemoveEventWatchList(), SDL_RemoveTimer(), SDL_ReportAssertion(), SDL_ResetLogPriorities(), SDL_RunMainThreadCallbacks(), SDL_RunOnMainThread(), SDL_SetAudioStreamFormat(), SDL_SetAudioStreamFrequencyRatio(), SDL_SetAudioStreamGain(), SDL_SetAudioStreamGetCallback(), SDL_SetAudioStreamPutCallback(), SDL_SetEnvironmentVariable(), SDL_SetEventFilter(), SDL_SetLogOutputFunction(), SDL_SetLogPriorities(), SDL_SetLogPriority(), SDL_SetLogPriorityPrefix(), SDL_SetRenderTarget(), SDL_SignalSemaphore(), SDL_StartEventLoop(), SDL_StopEventLoop(), SDL_TryLockRWLockForReading_generic(), SDL_TryLockRWLockForWriting_generic(), SDL_TryLockSpinlock(), SDL_UnbindAudioStreams(), SDL_UnlockAudioStream(), SDL_UnlockJoysticks(), SDL_UnlockProperties(), SDL_UnlockRWLock(), SDL_UnlockSensors(), SDL_UnsetEnvironmentVariable(), SDL_WaitConditionTimeoutNS_generic(), SDL_WaitSemaphoreTimeoutNS(), SDL_WaitThreadBarrier(), SetAudioStreamChannelMap(), ShutdownThreadpool(), SynchronousIO(), and UpdateAudioStreamFormatsPhysical().
SDL_UnlockRWLock()
SDL_DECLSPEC void SDLCALL SDL_UnlockRWLock (SDL_RWLock * rwlock) extern
Unlock the read/write lock.
Use this function to unlock the rwlock, whether it was locked for read-only or write operations.
It is legal for the owning thread to lock an already-locked read-only lock. It must unlock it the same number of times before it is actually made available for other threads in the system (this is known as a "recursive rwlock").
It is illegal to unlock a rwlock that has not been locked by the current thread, and doing so results in undefined behavior.
Parameters
rwlock the rwlock to unlock.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockRWLockForReading
SDL_LockRWLockForWriting
SDL_TryLockRWLockForReading
SDL_TryLockRWLockForWriting
{
#ifndef SDL_THREADS_DISABLED
    if (rwlock) {
        SDL_LockMutex(rwlock->lock);  // recursive lock for writers, readers grab lock to make sure things are sane.
        if (SDL_GetAtomicInt(&rwlock->reader_count) > 0) {  // we're a reader
            SDL_AddAtomicInt(&rwlock->reader_count, -1);
            SDL_BroadcastCondition(rwlock->condition);  // alert any pending writers to attempt to try to grab the lock again.
        } else if (SDL_GetAtomicInt(&rwlock->writer_count) > 0) {  // we're a writer
            SDL_AddAtomicInt(&rwlock->writer_count, -1);
            SDL_UnlockMutex(rwlock->lock);  // recursive unlock.
        }
        SDL_UnlockMutex(rwlock->lock);
    }
#endif
}
References SDL_AddAtomicInt(), SDL_assert, SDL_BroadcastCondition(), SDL_GetAtomicInt(), SDL_LockMutex(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_rwlock_impl_active, and SDL_UnlockMutex().
Referenced by CreatePhysicalAudioDevice(), DestroyLogicalAudioDevice(), GetAudioDevices(), GetFirstAddedAudioDevice(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), ObtainPhysicalCamera(), OnAudioStreamCreated(), OnAudioStreamDestroy(), SDL_AddAudioDevice(), SDL_AddCamera(), SDL_AddPenDevice(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CameraDisconnected(), SDL_CameraPermissionOutcome(), SDL_ClearHashTable(), SDL_DefaultAudioDeviceChanged(), SDL_FindInHashTable(), SDL_FindPenByCallback(), SDL_FindPenByHandle(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetAudioDeviceName(), SDL_GetCameras(), SDL_GetPenStatus(), SDL_HashTableEmpty(), SDL_InsertIntoHashTable(), SDL_IterateHashTable(), SDL_OpenAudioDevice(), SDL_QuitAudio(), SDL_QuitCamera(), SDL_RemoveAllPenDevices(), SDL_RemoveFromHashTable(), SDL_RemovePenDevice(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_UpdateAudio(), SDL_UpdateCamera(), UnrefPhysicalAudioDevice(), and UnrefPhysicalCamera().
SDL_WaitCondition()
SDL_DECLSPEC void SDLCALL SDL_WaitCondition (SDL_Condition * cond, SDL_Mutex * mutex) extern
Wait until a condition variable is signaled.
This function unlocks the specified mutex and waits for another thread to call SDL_SignalCondition() or SDL_BroadcastCondition() on the condition variable cond. Once the condition variable is signaled, the mutex is re-locked and the function returns.
The mutex must be locked before calling this function. Locking the mutex recursively (more than once) is not supported and leads to undefined behavior.
This function is the equivalent of calling SDL_WaitConditionTimeout() with a time length of -1.
Parameters
cond the condition variable to wait on.
mutex the mutex used to coordinate thread access.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitConditionTimeout
{
    SDL_WaitConditionTimeoutNS(cond, mutex, -1);
}
References SDL_WaitConditionTimeoutNS().
Referenced by hidapi_thread_cond_wait(), SDL_LockRWLockForWriting(), SDL_WaitThreadBarrier(), SerializePhysicalDeviceClose(), and ShutdownThreadpool().
SDL_WaitConditionTimeout()
SDL_DECLSPEC bool SDLCALL SDL_WaitConditionTimeout (SDL_Condition * cond, SDL_Mutex * mutex, Sint32 timeoutMS) extern
Wait until a condition variable is signaled or a certain time has passed.
This function unlocks the specified mutex and waits for another thread to call SDL_SignalCondition() or SDL_BroadcastCondition() on the condition variable cond, or for the specified time to elapse. Once the condition variable is signaled or the time elapsed, the mutex is re-locked and the function returns.
The mutex must be locked before calling this function. Locking the mutex recursively (more than once) is not supported and leads to undefined behavior.
Parameters
cond the condition variable to wait on.
mutex the mutex used to coordinate thread access.
timeoutMS the maximum time to wait, in milliseconds, or -1 to wait indefinitely.
Returns
true if the condition variable is signaled, false if the condition is not signaled in the allotted time.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitCondition
{
    Sint64 timeoutNS;
    if (timeoutMS >= 0) {
        timeoutNS = SDL_MS_TO_NS(timeoutMS);
    } else {
        timeoutNS = -1;
    }
    return SDL_WaitConditionTimeoutNS(cond, mutex, timeoutNS);
}
References SDL_MS_TO_NS, and SDL_WaitConditionTimeoutNS().
Referenced by AsyncIOThreadpoolWorker(), generic_asyncioqueue_wait_results(), and hidapi_thread_cond_timedwait().
SDL_WaitSemaphore()
SDL_DECLSPEC void SDLCALL SDL_WaitSemaphore (SDL_Semaphore * sem) extern
Wait until a semaphore has a positive value and then decrements it.
This function suspends the calling thread until the semaphore pointed to by sem has a positive value, and then atomically decrement the semaphore value.
This function is the equivalent of calling SDL_WaitSemaphoreTimeout() with a time length of -1.
Parameters
sem the semaphore wait on.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalSemaphore
SDL_TryWaitSemaphore
SDL_WaitSemaphoreTimeout
{
    SDL_WaitSemaphoreTimeoutNS(sem, -1);
}
References SDL_WaitSemaphoreTimeoutNS().
Referenced by SDL_BroadcastCondition(), SDL_LockMutex(), SDL_RunOnMainThread(), SDL_SignalCondition(), and SDL_WaitConditionTimeoutNS_generic().
SDL_WaitSemaphoreTimeout()
SDL_DECLSPEC bool SDLCALL SDL_WaitSemaphoreTimeout (SDL_Semaphore * sem, Sint32 timeoutMS) extern
Wait until a semaphore has a positive value and then decrements it.
This function suspends the calling thread until either the semaphore pointed to by sem has a positive value or the specified time has elapsed. If the call is successful it will atomically decrement the semaphore value.
Parameters
sem the semaphore to wait on.
timeoutMS the length of the timeout, in milliseconds, or -1 to wait indefinitely.
Returns
true if the wait succeeds or false if the wait times out.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalSemaphore
SDL_TryWaitSemaphore
SDL_WaitSemaphore
{
    Sint64 timeoutNS;
    if (timeoutMS >= 0) {
        timeoutNS = SDL_MS_TO_NS(timeoutMS);
    } else {
        timeoutNS = -1;
    }
    return SDL_WaitSemaphoreTimeoutNS(sem, timeoutNS);
}
References SDL_MS_TO_NS, and SDL_WaitSemaphoreTimeoutNS().