SDL3: SDL-main/src/audio/ngage/SDL_ngageaudio.hpp File Reference
SDL_ngageaudio.hpp File Reference
#include <e32base.h>
#include <e32std.h>
#include <mda/common/audio.h>
#include <mdaaudiooutputstream.h>
#include "../SDL_sysaudio.h"
#include "SDL_ngageaudio.h"
Data Structures
class CAudio
Functions
TBool AudioIsReady ()
void DeinitAudio ()
void InitAudio (TInt *aLatency)
Function Documentation
AudioIsReady()
TBool AudioIsReady ()
Referenced by E32Main().
DeinitAudio()
void DeinitAudio ()
Referenced by CSDLmain::RunL().
InitAudio()
void InitAudio (TInt * aLatency)
Referenced by E32Main().