SDL3: SDL-main/src/audio/SDL_audiocvt.c File Reference
SDL_audiocvt.c File Reference
#include "SDL_internal.h"
#include "SDL_sysaudio.h"
#include "SDL_audioqueue.h"
#include "SDL_audioresample.h"
#include "SDL_audio_channel_converters.h"
Macros
#define CHANNEL_SWIZZLE(bits)
#define GENERIC_INTERLEAVE_FUNCTION(bits)
#define GENERIC_INTERLEAVE_WITH_NULLS_FUNCTION(bits)
#define INTERLEAVE_STACK_SIZE 1024
#define SDL_INT_MAX ((int)(~0u>>1))
Functions
static int CalculateMaxFrameSize (SDL_AudioFormat src_format, int src_channels, SDL_AudioFormat dst_format, int dst_channels)
static bool CheckAudioStreamIsFullySetup (SDL_AudioStream *stream)
void ConvertAudio (int num_frames, const void *src, SDL_AudioFormat src_format, int src_channels, const int *src_map, void *dst, SDL_AudioFormat dst_format, int dst_channels, const int *dst_map, void *scratch, float gain)
static void SDLCALL DontFreeThisAudioBuffer (void *userdata, const void *buf, int len)
static Uint8 * EnsureAudioStreamWorkBufferSize (SDL_AudioStream *stream, size_t newlen)
static void SDLCALL FreeAllocatedAudioBuffer (void *userdata, const void *buf, int len)
static Sint64 GetAudioStreamAvailableFrames (SDL_AudioStream *stream, Sint64 *out_resample_offset)
static bool GetAudioStreamDataInternal (SDL_AudioStream *stream, void *buf, int output_frames, float gain)
static Sint64 GetAudioStreamHead (SDL_AudioStream *stream, SDL_AudioSpec *out_spec, int **out_chmap, bool *out_flushed)
static Sint64 GetAudioStreamResampleRate (SDL_AudioStream *stream, int src_freq, Sint64 resample_offset)
static void InterleaveAudioChannels (void *output, const void *const *channel_buffers, int channels, int num_samples, const SDL_AudioSpec *spec)
static void InterleaveAudioChannelsGeneric16 (void *output, const void *const *channel_buffers, const int channels, int num_samples)
static void InterleaveAudioChannelsGeneric32 (void *output, const void *const *channel_buffers, const int channels, int num_samples)
static void InterleaveAudioChannelsGeneric8 (void *output, const void *const *channel_buffers, const int channels, int num_samples)
static void InterleaveAudioChannelsWithNullsGeneric16 (void *output, const void *const *channel_buffers, const int channels, int num_samples, const int isilence)
static void InterleaveAudioChannelsWithNullsGeneric32 (void *output, const void *const *channel_buffers, const int channels, int num_samples, const int isilence)
static void InterleaveAudioChannelsWithNullsGeneric8 (void *output, const void *const *channel_buffers, const int channels, int num_samples, const int isilence)
static Sint64 NextAudioStreamIter (SDL_AudioStream *stream, void **inout_iter, Sint64 *inout_resample_offset, SDL_AudioSpec *out_spec, int **out_chmap, bool *out_flushed)
static bool PutAudioStreamBuffer (SDL_AudioStream *stream, const void *buf, int len, SDL_ReleaseAudioBufferCallback callback, void *userdata)
static bool PutAudioStreamBufferInternal (SDL_AudioStream *stream, const SDL_AudioSpec *spec, const int *chmap, const void *buf, int len, SDL_ReleaseAudioBufferCallback callback, void *userdata)
bool SDL_ChannelMapIsBogus (const int *chmap, int channels)
bool SDL_ChannelMapIsDefault (const int *chmap, int channels)
bool SDL_ClearAudioStream (SDL_AudioStream *stream)
bool SDL_ConvertAudioSamples (const SDL_AudioSpec *src_spec, const Uint8 *src_data, int src_len, const SDL_AudioSpec *dst_spec, Uint8 **dst_data, int *dst_len)
SDL_AudioStream * SDL_CreateAudioStream (const SDL_AudioSpec *src_spec, const SDL_AudioSpec *dst_spec)
void SDL_DestroyAudioStream (SDL_AudioStream *stream)
bool SDL_FlushAudioStream (SDL_AudioStream *stream)
int SDL_GetAudioStreamAvailable (SDL_AudioStream *stream)
int SDL_GetAudioStreamData (SDL_AudioStream *stream, void *voidbuf, int len)
int SDL_GetAudioStreamDataAdjustGain (SDL_AudioStream *stream, void *voidbuf, int len, float extra_gain)
bool SDL_GetAudioStreamFormat (SDL_AudioStream *stream, SDL_AudioSpec *src_spec, SDL_AudioSpec *dst_spec)
float SDL_GetAudioStreamFrequencyRatio (SDL_AudioStream *stream)
float SDL_GetAudioStreamGain (SDL_AudioStream *stream)
int * SDL_GetAudioStreamInputChannelMap (SDL_AudioStream *stream, int *count)
int * SDL_GetAudioStreamOutputChannelMap (SDL_AudioStream *stream, int *count)
SDL_PropertiesID SDL_GetAudioStreamProperties (SDL_AudioStream *stream)
int SDL_GetAudioStreamQueued (SDL_AudioStream *stream)
static bool SDL_IsSupportedAudioFormat (const SDL_AudioFormat fmt)
static bool SDL_IsSupportedChannelCount (const int channels)
bool SDL_LockAudioStream (SDL_AudioStream *stream)
bool SDL_PutAudioStreamData (SDL_AudioStream *stream, const void *buf, int len)
bool SDL_PutAudioStreamDataNoCopy (SDL_AudioStream *stream, const void *buf, int len, SDL_AudioStreamDataCompleteCallback callback, void *userdata)
bool SDL_PutAudioStreamPlanarData (SDL_AudioStream *stream, const void *const *channel_buffers, int num_channels, int num_samples)
bool SDL_SetAudioStreamFormat (SDL_AudioStream *stream, const SDL_AudioSpec *src_spec, const SDL_AudioSpec *dst_spec)
bool SDL_SetAudioStreamFrequencyRatio (SDL_AudioStream *stream, float freq_ratio)
bool SDL_SetAudioStreamGain (SDL_AudioStream *stream, float gain)
bool SDL_SetAudioStreamGetCallback (SDL_AudioStream *stream, SDL_AudioStreamCallback callback, void *userdata)
bool SDL_SetAudioStreamInputChannelMap (SDL_AudioStream *stream, const int *chmap, int channels)
bool SDL_SetAudioStreamOutputChannelMap (SDL_AudioStream *stream, const int *chmap, int channels)
bool SDL_SetAudioStreamPutCallback (SDL_AudioStream *stream, SDL_AudioStreamCallback callback, void *userdata)
bool SDL_UnlockAudioStream (SDL_AudioStream *stream)
bool SetAudioStreamChannelMap (SDL_AudioStream *stream, const SDL_AudioSpec *spec, int **stream_chmap, const int *chmap, int channels, int isinput)
static void SwizzleAudio (const int num_frames, void *dst, const void *src, int channels, const int *map, SDL_AudioFormat fmt)
static bool UpdateAudioStreamInputSpec (SDL_AudioStream *stream, const SDL_AudioSpec *spec, const int *chmap)
Macro Definition Documentation
CHANNEL_SWIZZLE
#define CHANNEL_SWIZZLE (bits)
Referenced by SwizzleAudio().
GENERIC_INTERLEAVE_FUNCTION
#define GENERIC_INTERLEAVE_FUNCTION (bits)
Value:
    static void InterleaveAudioChannelsGeneric##bits(void *output, const void * const *channel_buffers, const int channels, int num_samples) { \
        Uint##bits *dst = (Uint##bits *) output; \
        const Uint##bits * const *srcs = (const Uint##bits * const *) channel_buffers; \
        for (int frame = 0; frame < num_samples; frame++) { \
            for (int channel = 0; channel < channels; channel++) { \
                *(dst++) = srcs[channel][frame]; \
            } \
        } \
    }
#define GENERIC_INTERLEAVE_FUNCTION(bits) \
    static void InterleaveAudioChannelsGeneric##bits(void *output, const void * const *channel_buffers, const int channels, int num_samples) { \
        Uint##bits *dst = (Uint##bits *) output; \
        const Uint##bits * const *srcs = (const Uint##bits * const *) channel_buffers; \
        for (int frame = 0; frame < num_samples; frame++) { \
            for (int channel = 0; channel < channels; channel++) { \
                *(dst++) = srcs[channel][frame]; \
            } \
        } \
    }
Referenced by InterleaveAudioChannelsGeneric16(), and InterleaveAudioChannelsGeneric32().
GENERIC_INTERLEAVE_WITH_NULLS_FUNCTION
#define GENERIC_INTERLEAVE_WITH_NULLS_FUNCTION (bits)
Value:
    static void InterleaveAudioChannelsWithNullsGeneric##bits(void *output, const void * const *channel_buffers, const int channels, int num_samples, const int isilence) { \
        const Uint##bits silence = (Uint##bits) isilence; \
        Uint##bits *dst = (Uint##bits *) output; \
        const Uint##bits * const *srcs = (const Uint##bits * const *) channel_buffers; \
        for (int frame = 0; frame < num_samples; frame++) { \
            for (int channel = 0; channel < channels; channel++) { \
                *(dst++) = srcs[channel] ? srcs[channel][frame] : silence; \
            } \
        } \
    }
#define GENERIC_INTERLEAVE_WITH_NULLS_FUNCTION(bits) \
    static void InterleaveAudioChannelsWithNullsGeneric##bits(void *output, const void * const *channel_buffers, const int channels, int num_samples, const int isilence) { \
        const Uint##bits silence = (Uint##bits) isilence; \
        Uint##bits *dst = (Uint##bits *) output; \
        const Uint##bits * const *srcs = (const Uint##bits * const *) channel_buffers; \
        for (int frame = 0; frame < num_samples; frame++) { \
            for (int channel = 0; channel < channels; channel++) { \
                *(dst++) = srcs[channel] ? srcs[channel][frame] : silence; \
            } \
        } \
    }
Referenced by InterleaveAudioChannelsWithNullsGeneric16(), and InterleaveAudioChannelsWithNullsGeneric32().
INTERLEAVE_STACK_SIZE
#define INTERLEAVE_STACK_SIZE 1024
Referenced by SDL_PutAudioStreamPlanarData().
SDL_INT_MAX
#define SDL_INT_MAX ((int)(~0u>>1))
Referenced by SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), and SDL_GetAudioStreamQueued().
Function Documentation
CalculateMaxFrameSize()
int CalculateMaxFrameSize (SDL_AudioFormat src_format, int src_channels, SDL_AudioFormat dst_format, int dst_channels) static
{
    const int src_format_size = SDL_AUDIO_BYTESIZE(src_format);
    const int dst_format_size = SDL_AUDIO_BYTESIZE(dst_format);
    const int max_app_format_size = SDL_max(src_format_size, dst_format_size);
    const int max_format_size = SDL_max(max_app_format_size, sizeof (float));  // ConvertAudio and ResampleAudio use floats.
    const int max_channels = SDL_max(src_channels, dst_channels);
    return max_format_size * max_channels;
}
References SDL_AUDIO_BYTESIZE, and SDL_max.
Referenced by GetAudioStreamDataInternal().
CheckAudioStreamIsFullySetup()
bool CheckAudioStreamIsFullySetup (SDL_AudioStream * stream) static
{
    if (stream->src_spec.format == SDL_AUDIO_UNKNOWN) {
        return SDL_SetError("Stream has no source format");
    } else if (stream->dst_spec.format == SDL_AUDIO_UNKNOWN) {
        return SDL_SetError("Stream has no destination format");
    }
    return true;
}
References SDL_AUDIO_UNKNOWN, and SDL_SetError().
Referenced by PutAudioStreamBuffer(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), and SDL_PutAudioStreamPlanarData().
ConvertAudio()
void ConvertAudio (int num_frames, const void * src, SDL_AudioFormat src_format, int src_channels, const int * src_map, void * dst, SDL_AudioFormat dst_format, int dst_channels, const int * dst_map, void * scratch, float gain)
{
    SDL_assert(src != NULL);
    SDL_assert(dst != NULL);
    SDL_assert(SDL_IsSupportedAudioFormat(src_format));
    SDL_assert(SDL_IsSupportedAudioFormat(dst_format));
    SDL_assert(SDL_IsSupportedChannelCount(src_channels));
    SDL_assert(SDL_IsSupportedChannelCount(dst_channels));
    if (!num_frames) {
        return;  // no data to convert, quit.
    }
#if DEBUG_AUDIO_CONVERT
    SDL_Log("SDL_AUDIO_CONVERT: Convert format %04x->%04x, channels %u->%u", src_format, dst_format, src_channels, dst_channels);
#endif
    const int dst_bitsize = (int) SDL_AUDIO_BITSIZE(dst_format);
    const int dst_sample_frame_size = (dst_bitsize / 8) * dst_channels;
    const bool chmaps_match = (src_channels == dst_channels) && SDL_AudioChannelMapsEqual(src_channels, src_map, dst_map);
    if (chmaps_match) {
        src_map = dst_map = NULL;  // NULL both these out so we don't do any unnecessary swizzling.
    }
    /* Type conversion goes like this now:
        - swizzle through source channel map to "standard" layout.
        - byteswap to CPU native format first if necessary.
        - convert to native Float32 if necessary.
        - change channel count if necessary.
        - convert to final data format.
        - byteswap back to foreign format if necessary.
        - swizzle through dest channel map from "standard" layout.
       The expectation is we can process data faster in float32
       (possibly with SIMD), and making several passes over the same
       buffer is likely to be CPU cache-friendly, avoiding the
       biggest performance hit in modern times. Previously we had
       (script-generated) custom converters for every data type and
       it was a bloat on SDL compile times and final library size. */
    // swizzle input to "standard" format if necessary.
    if (src_map) {
        void *buf = scratch ? scratch : dst;  // use scratch if available, since it has to be big enough to hold src, unless it's NULL, then dst has to be.
        SwizzleAudio(num_frames, buf, src, src_channels, src_map, src_format);
        src = buf;
    }
    // see if we can skip float conversion entirely.
    if ((src_channels == dst_channels) && (gain == 1.0f)) {
        if (src_format == dst_format) {
            // nothing to do, we're already in the right format, just copy it over if necessary.
            if (dst_map) {
                SwizzleAudio(num_frames, dst, src, dst_channels, dst_map, dst_format);
            } else if (src != dst) {
                SDL_memcpy(dst, src, num_frames * dst_sample_frame_size);
            }
            return;
        }
        // just a byteswap needed?
        if ((src_format ^ dst_format) == SDL_AUDIO_MASK_BIG_ENDIAN) {
            if (dst_map) {  // do this first, in case we duplicate channels, we can avoid an extra copy if src != dst.
                SwizzleAudio(num_frames, dst, src, dst_channels, dst_map, dst_format);
                src = dst;
            }
            ConvertAudioSwapEndian(dst, src, num_frames * dst_channels, dst_bitsize);
            return;  // all done.
        }
    }
    if (!scratch) {
        scratch = dst;
    }
    const bool srcconvert = src_format != SDL_AUDIO_F32;
    const bool channelconvert = src_channels != dst_channels;
    const bool dstconvert = dst_format != SDL_AUDIO_F32;
    // get us to float format.
    if (srcconvert) {
        void *buf = (channelconvert || dstconvert) ? scratch : dst;
        ConvertAudioToFloat((float *) buf, src, num_frames * src_channels, src_format);
        src = buf;
    }
    // Gain adjustment
    if (gain != 1.0f) {
        float *buf = (float *)((channelconvert || dstconvert) ? scratch : dst);
        const int total_samples = num_frames * src_channels;
        if (src == buf) {
            for (int i = 0; i < total_samples; i++) {
                buf[i] *= gain;
            }
        } else {
            const float *fsrc = (const float *)src;
            for (int i = 0; i < total_samples; i++) {
                buf[i] = fsrc[i] * gain;
            }
        }
        src = buf;
    }
    // Channel conversion
    if (channelconvert) {
        SDL_AudioChannelConverter channel_converter;
        SDL_AudioChannelConverter override = NULL;
        // SDL_IsSupportedChannelCount should have caught these asserts, or we added a new format and forgot to update the table.
        SDL_assert(src_channels <= SDL_arraysize(channel_converters));
        SDL_assert(dst_channels <= SDL_arraysize(channel_converters[0]));
        channel_converter = channel_converters[src_channels - 1][dst_channels - 1];
        SDL_assert(channel_converter != NULL);
        // swap in some SIMD versions for a few of these.
        if (channel_converter == SDL_ConvertStereoToMono) {
            #ifdef SDL_SSE3_INTRINSICS
            if (!override && SDL_HasSSE3()) { override = SDL_ConvertStereoToMono_SSE3; }
            #endif
        } else if (channel_converter == SDL_ConvertMonoToStereo) {
            #ifdef SDL_SSE_INTRINSICS
            if (!override && SDL_HasSSE()) { override = SDL_ConvertMonoToStereo_SSE; }
            #endif
        }
        if (override) {
            channel_converter = override;
        }
        void *buf = dstconvert ? scratch : dst;
        channel_converter((float *) buf, (const float *) src, num_frames);
        src = buf;
    }
    // Resampling is not done in here. SDL_AudioStream handles that.
    // Move to final data type.
    if (dstconvert) {
        ConvertAudioFromFloat(dst, (const float *) src, num_frames * dst_channels, dst_format);
        src = dst;
    }
    SDL_assert(src == dst);  // if we got here, we _had_ to have done _something_. Otherwise, we should have memcpy'd!
    if (dst_map) {
        SwizzleAudio(num_frames, dst, src, dst_channels, dst_map, dst_format);
    }
}
References channel_converters, ConvertAudioFromFloat(), ConvertAudioSwapEndian(), ConvertAudioToFloat(), NULL, SDL_arraysize, SDL_assert, SDL_AUDIO_BITSIZE, SDL_AUDIO_F32, SDL_AUDIO_MASK_BIG_ENDIAN, SDL_AudioChannelMapsEqual(), SDL_ConvertMonoToStereo(), SDL_ConvertStereoToMono(), SDL_HasSSE(), SDL_HasSSE3(), SDL_IsSupportedAudioFormat(), SDL_IsSupportedChannelCount(), SDL_Log(), SDL_memcpy, and SwizzleAudio().
Referenced by GetAudioStreamDataInternal(), SDL_PlaybackAudioThreadIterate(), SDL_ReadFromAudioQueue(), and SDL_RecordingAudioThreadIterate().
DontFreeThisAudioBuffer()
void SDLCALL DontFreeThisAudioBuffer (void * userdata, const void * buf, int len) static
{
    // We don't own the buffer, but know it will outlive the stream
}
References SDLCALL.
Referenced by SDL_PutAudioStreamDataNoCopy().
EnsureAudioStreamWorkBufferSize()
Uint8 * EnsureAudioStreamWorkBufferSize (SDL_AudioStream * stream, size_t newlen) static
{
    if (stream->work_buffer_allocation >= newlen) {
        return stream->work_buffer;
    }
    Uint8 *ptr = (Uint8 *) SDL_aligned_alloc(SDL_GetSIMDAlignment(), newlen);
    if (!ptr) {
        return NULL;  // previous work buffer is still valid!
    }
    SDL_aligned_free(stream->work_buffer);
    stream->work_buffer = ptr;
    stream->work_buffer_allocation = newlen;
    return ptr;
}
References NULL, SDL_aligned_alloc(), SDL_aligned_free(), and SDL_GetSIMDAlignment().
Referenced by GetAudioStreamDataInternal().
FreeAllocatedAudioBuffer()
void SDLCALL FreeAllocatedAudioBuffer (void * userdata, const void * buf, int len) static
{
    SDL_free((void *)buf);
}
References SDL_free(), and SDLCALL.
Referenced by SDL_PutAudioStreamData(), and SDL_PutAudioStreamPlanarData().
GetAudioStreamAvailableFrames()
Sint64 GetAudioStreamAvailableFrames (SDL_AudioStream * stream, Sint64 * out_resample_offset) static
{
    void *iter = SDL_BeginAudioQueueIter(stream->queue);
    Sint64 resample_offset = stream->resample_offset;
    Sint64 output_frames = 0;
    while (iter) {
        output_frames += NextAudioStreamIter(stream, &iter, &resample_offset, NULL, NULL, NULL);
        // Already got loads of frames. Just clamp it to something reasonable
        if (output_frames >= SDL_MAX_SINT32) {
            output_frames = SDL_MAX_SINT32;
            break;
        }
    }
    if (out_resample_offset) {
        *out_resample_offset = resample_offset;
    }
    return output_frames;
}
References NextAudioStreamIter(), NULL, SDL_BeginAudioQueueIter(), and SDL_MAX_SINT32.
Referenced by SDL_GetAudioStreamAvailable(), and SDL_GetAudioStreamDataAdjustGain().
GetAudioStreamDataInternal()
bool GetAudioStreamDataInternal (SDL_AudioStream * stream, void * buf, int output_frames, float gain) static
{
    const SDL_AudioSpec *src_spec = &stream->input_spec;
    const SDL_AudioSpec *dst_spec = &stream->dst_spec;
    const SDL_AudioFormat src_format = src_spec->format;
    const int src_channels = src_spec->channels;
    const SDL_AudioFormat dst_format = dst_spec->format;
    const int dst_channels = dst_spec->channels;
    const int *dst_map = stream->dst_chmap;
    const int max_frame_size = CalculateMaxFrameSize(src_format, src_channels, dst_format, dst_channels);
    const Sint64 resample_rate = GetAudioStreamResampleRate(stream, src_spec->freq, stream->resample_offset);
#if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: asking for %d frames.", output_frames);
#endif
    SDL_assert(output_frames > 0);
    // Not resampling? It's an easy conversion (and maybe not even that!)
    if (resample_rate == 0) {
        Uint8 *work_buffer = NULL;
        // Ensure we have enough scratch space for any conversions
        if ((src_format != dst_format) || (src_channels != dst_channels) || (gain != 1.0f)) {
            work_buffer = EnsureAudioStreamWorkBufferSize(stream, output_frames * max_frame_size);
            if (!work_buffer) {
                return false;
            }
        }
        if (SDL_ReadFromAudioQueue(stream->queue, (Uint8 *)buf, dst_format, dst_channels, dst_map, 0, output_frames, 0, work_buffer, gain) != buf) {
            return SDL_SetError("Not enough data in queue");
        }
        return true;
    }
    // Time to do some resampling!
    // Calculate the number of input frames necessary for this request.
    // Because resampling happens "between" frames, The same number of output_frames
    // can require a different number of input_frames, depending on the resample_offset.
    // In fact, input_frames can sometimes even be zero when upsampling.
    const int input_frames = (int) SDL_GetResamplerInputFrames(output_frames, resample_rate, stream->resample_offset);
    const int padding_frames = SDL_GetResamplerPaddingFrames(resample_rate);
    const SDL_AudioFormat resample_format = SDL_AUDIO_F32;
    // If increasing channels, do it after resampling, since we'd just
    // do more work to resample duplicate channels. If we're decreasing, do
    // it first so we resample the interpolated data instead of interpolating
    // the resampled data.
    const int resample_channels = SDL_min(src_channels, dst_channels);
    // The size of the frame used when resampling
    const int resample_frame_size = SDL_AUDIO_BYTESIZE(resample_format) * resample_channels;
    // The main portion of the work_buffer can be used to store 3 things:
    // src_sample_frame_size * (left_padding+input_buffer+right_padding)
    //   resample_frame_size * (left_padding+input_buffer+right_padding)
    // dst_sample_frame_size * output_frames
    //
    // ResampleAudio also requires an additional buffer if it can't write straight to the output:
    //   resample_frame_size * output_frames
    //
    // Note, ConvertAudio requires (num_frames * max_sample_frame_size) of scratch space
    const int work_buffer_frames = input_frames + (padding_frames * 2);
    int work_buffer_capacity = work_buffer_frames * max_frame_size;
    int resample_buffer_offset = -1;
    // Check if we can resample directly into the output buffer.
    // Note, this is just to avoid extra copies.
    // Some other formats may fit directly into the output buffer, but i'd rather process data in a SIMD-aligned buffer.
    if ((dst_format != resample_format) || (dst_channels != resample_channels)) {
        // Allocate space for converting the resampled output to the destination format
        int resample_convert_bytes = output_frames * max_frame_size;
        work_buffer_capacity = SDL_max(work_buffer_capacity, resample_convert_bytes);
        // SIMD-align the buffer
        int simd_alignment = (int) SDL_GetSIMDAlignment();
        work_buffer_capacity += simd_alignment - 1;
        work_buffer_capacity -= work_buffer_capacity % simd_alignment;
        // Allocate space for the resampled output
        int resample_bytes = output_frames * resample_frame_size;
        resample_buffer_offset = work_buffer_capacity;
        work_buffer_capacity += resample_bytes;
    }
    Uint8 *work_buffer = EnsureAudioStreamWorkBufferSize(stream, work_buffer_capacity);
    if (!work_buffer) {
        return false;
    }
    // adjust gain either before resampling or after, depending on which point has less
    // samples to process.
    const float preresample_gain = (input_frames > output_frames) ? 1.0f : gain;
    const float postresample_gain = (input_frames > output_frames) ? gain : 1.0f;
    // (dst channel map is NULL because we'll do the final swizzle on ConvertAudio after resample.)
    const Uint8 *input_buffer = SDL_ReadFromAudioQueue(stream->queue,
        NULL, resample_format, resample_channels, NULL,
        padding_frames, input_frames, padding_frames, work_buffer, preresample_gain);
    if (!input_buffer) {
        return SDL_SetError("Not enough data in queue (resample)");
    }
    input_buffer += padding_frames * resample_frame_size;
    // Decide where the resampled output goes
    void *resample_buffer = (resample_buffer_offset != -1) ? (work_buffer + resample_buffer_offset) : buf;
    SDL_ResampleAudio(resample_channels,
                  (const float *)input_buffer, input_frames,
                  (float *)resample_buffer, output_frames,
                  resample_rate, &stream->resample_offset);
    // Convert to the final format, if necessary (src channel map is NULL because SDL_ReadFromAudioQueue already handled this).
    ConvertAudio(output_frames, resample_buffer, resample_format, resample_channels, NULL, buf, dst_format, dst_channels, dst_map, work_buffer, postresample_gain);
    return true;
}
References CalculateMaxFrameSize(), SDL_AudioSpec::channels, ConvertAudio(), EnsureAudioStreamWorkBufferSize(), SDL_AudioSpec::format, SDL_AudioSpec::freq, GetAudioStreamResampleRate(), NULL, SDL_assert, SDL_AUDIO_BYTESIZE, SDL_AUDIO_F32, SDL_GetResamplerInputFrames(), SDL_GetResamplerPaddingFrames(), SDL_GetSIMDAlignment(), SDL_Log(), SDL_max, SDL_min, SDL_ReadFromAudioQueue(), SDL_ResampleAudio(), and SDL_SetError().
Referenced by SDL_GetAudioStreamDataAdjustGain().
GetAudioStreamHead()
Sint64 GetAudioStreamHead (SDL_AudioStream * stream, SDL_AudioSpec * out_spec, int ** out_chmap, bool * out_flushed) static
{
    void *iter = SDL_BeginAudioQueueIter(stream->queue);
    if (!iter) {
        SDL_zerop(out_spec);
        *out_flushed = false;
        return 0;
    }
    Sint64 resample_offset = stream->resample_offset;
    return NextAudioStreamIter(stream, &iter, &resample_offset, out_spec, out_chmap, out_flushed);
}
References NextAudioStreamIter(), SDL_BeginAudioQueueIter(), and SDL_zerop.
Referenced by SDL_GetAudioStreamDataAdjustGain().
GetAudioStreamResampleRate()
Sint64 GetAudioStreamResampleRate (SDL_AudioStream * stream, int src_freq, Sint64 resample_offset) static
{
    src_freq = (int)((float)src_freq * stream->freq_ratio);
    Sint64 resample_rate = SDL_GetResampleRate(src_freq, stream->dst_spec.freq);
    // If src_freq == dst_freq, and we aren't between frames, don't resample
    if ((resample_rate == 0x100000000) && (resample_offset == 0)) {
        resample_rate = 0;
    }
    return resample_rate;
}
References SDL_GetResampleRate().
Referenced by GetAudioStreamDataInternal(), NextAudioStreamIter(), and SDL_GetAudioStreamDataAdjustGain().
InterleaveAudioChannels()
void InterleaveAudioChannels (void * output, const void *const * channel_buffers, int channels, int num_samples, const SDL_AudioSpec * spec) static
{
    bool have_null_channel = false;
    void *channels_full[16];
    // if didn't specify enough channels, pad out a channel array with NULLs.
    if ((channels >= 0) && (channels < spec->channels)) {
        have_null_channel = true;
        SDL_assert(SDL_IsSupportedChannelCount(spec->channels));
        SDL_assert(spec->channels <= SDL_arraysize(channels_full));
        SDL_memcpy(channels_full, channel_buffers, channels * sizeof (*channel_buffers));
        SDL_memset(channels_full + channels, 0, (spec->channels - channels) * sizeof (*channel_buffers));
        channel_buffers = (const void * const *) channels_full;
    }
    channels = spec->channels;  // it's either < 0, needs to be clamped to spec->channels, or we just padded it out to spec->channels with channels_full.
    if (!have_null_channel) {
        for (int i = 0; i < channels; i++) {
            if (channel_buffers[i] == NULL) {
                have_null_channel = true;
                break;
            }
        }
    }
    if (have_null_channel) {
        const int silence = SDL_GetSilenceValueForFormat(spec->format);
        switch (SDL_AUDIO_BITSIZE(spec->format)) {
            case 8: InterleaveAudioChannelsWithNullsGeneric8(output, channel_buffers, channels, num_samples, silence); break;
            case 16: InterleaveAudioChannelsWithNullsGeneric16(output, channel_buffers, channels, num_samples, silence); break;
            case 32: InterleaveAudioChannelsWithNullsGeneric32(output, channel_buffers, channels, num_samples, silence); break;
            //case 64: InterleaveAudioChannelsGeneric64(output, channel_buffers, channels, num_samples); break;  (we don't have any 64-bit audio data types at the moment.)
            default: SDL_assert(!"Missing needed generic audio interleave function!"); SDL_memset(output, 0, SDL_AUDIO_FRAMESIZE(*spec) * num_samples); break;
        }
    } else {
        // !!! FIXME: it would be possible to do this really well in SIMD for stereo data, using unpack (intel) or zip (arm) instructions, etc.
        switch (SDL_AUDIO_BITSIZE(spec->format)) {
            case 8: InterleaveAudioChannelsGeneric8(output, channel_buffers, channels, num_samples); break;
            case 16: InterleaveAudioChannelsGeneric16(output, channel_buffers, channels, num_samples); break;
            case 32: InterleaveAudioChannelsGeneric32(output, channel_buffers, channels, num_samples); break;
            //case 64: InterleaveAudioChannelsGeneric64(output, channel_buffers, channels, num_samples); break;  (we don't have any 64-bit audio data types at the moment.)
            default: SDL_assert(!"Missing needed generic audio interleave function!"); SDL_memset(output, 0, SDL_AUDIO_FRAMESIZE(*spec) * num_samples); break;
        }
    }
}
References SDL_AudioSpec::channels, SDL_AudioSpec::format, InterleaveAudioChannelsGeneric16(), InterleaveAudioChannelsGeneric32(), InterleaveAudioChannelsGeneric8(), InterleaveAudioChannelsWithNullsGeneric16(), InterleaveAudioChannelsWithNullsGeneric32(), InterleaveAudioChannelsWithNullsGeneric8(), NULL, SDL_arraysize, SDL_assert, SDL_AUDIO_BITSIZE, SDL_AUDIO_FRAMESIZE, SDL_GetSilenceValueForFormat(), SDL_IsSupportedChannelCount(), SDL_memcpy, and SDL_memset.
Referenced by SDL_PutAudioStreamPlanarData().
InterleaveAudioChannelsGeneric16()
void InterleaveAudioChannelsGeneric16 (void * output, const void *const * channel_buffers, const int channels, int num_samples) static
References GENERIC_INTERLEAVE_FUNCTION.
Referenced by InterleaveAudioChannels().
InterleaveAudioChannelsGeneric32()
void InterleaveAudioChannelsGeneric32 (void * output, const void *const * channel_buffers, const int channels, int num_samples) static
References GENERIC_INTERLEAVE_FUNCTION.
Referenced by InterleaveAudioChannels().
InterleaveAudioChannelsGeneric8()
void InterleaveAudioChannelsGeneric8 (void * output, const void *const * channel_buffers, const int channels, int num_samples) static
Referenced by InterleaveAudioChannels().
InterleaveAudioChannelsWithNullsGeneric16()
void InterleaveAudioChannelsWithNullsGeneric16 (void * output, const void *const * channel_buffers, const int channels, int num_samples, const int isilence) static
References GENERIC_INTERLEAVE_WITH_NULLS_FUNCTION.
Referenced by InterleaveAudioChannels().
InterleaveAudioChannelsWithNullsGeneric32()
void InterleaveAudioChannelsWithNullsGeneric32 (void * output, const void *const * channel_buffers, const int channels, int num_samples, const int isilence) static
References GENERIC_INTERLEAVE_WITH_NULLS_FUNCTION.
Referenced by InterleaveAudioChannels().
InterleaveAudioChannelsWithNullsGeneric8()
void InterleaveAudioChannelsWithNullsGeneric8 (void * output, const void *const * channel_buffers, const int channels, int num_samples, const int isilence) static
Referenced by InterleaveAudioChannels().
NextAudioStreamIter()
Sint64 NextAudioStreamIter (SDL_AudioStream * stream, void ** inout_iter, Sint64 * inout_resample_offset, SDL_AudioSpec * out_spec, int ** out_chmap, bool * out_flushed) static
{
    SDL_AudioSpec spec;
    bool flushed;
    int *chmap;
    size_t queued_bytes = SDL_NextAudioQueueIter(stream->queue, inout_iter, &spec, &chmap, &flushed);
    if (out_spec) {
        SDL_copyp(out_spec, &spec);
    }
    if (out_chmap) {
        *out_chmap = chmap;
    }
    // There is infinite audio available, whether or not we are resampling
    if (queued_bytes == SDL_SIZE_MAX) {
        *inout_resample_offset = 0;
        if (out_flushed) {
            *out_flushed = false;
        }
        return SDL_MAX_SINT32;
    }
    Sint64 resample_offset = *inout_resample_offset;
    Sint64 resample_rate = GetAudioStreamResampleRate(stream, spec.freq, resample_offset);
    Sint64 output_frames = (Sint64)(queued_bytes / SDL_AUDIO_FRAMESIZE(spec));
    if (resample_rate) {
        // Resampling requires padding frames to the left and right of the current position.
        // Past the end of the track, the right padding is filled with silence.
        // But we only want to do that if the track is actually finished (flushed).
        if (!flushed) {
            output_frames -= SDL_GetResamplerPaddingFrames(resample_rate);
        }
        output_frames = SDL_GetResamplerOutputFrames(output_frames, resample_rate, &resample_offset);
    }
    if (flushed) {
        resample_offset = 0;
    }
    *inout_resample_offset = resample_offset;
    if (out_flushed) {
        *out_flushed = flushed;
    }
    return output_frames;
}
References SDL_AudioSpec::freq, GetAudioStreamResampleRate(), SDL_AUDIO_FRAMESIZE, SDL_copyp, SDL_GetResamplerOutputFrames(), SDL_GetResamplerPaddingFrames(), SDL_MAX_SINT32, SDL_NextAudioQueueIter(), and SDL_SIZE_MAX.
Referenced by GetAudioStreamAvailableFrames(), and GetAudioStreamHead().
PutAudioStreamBuffer()
bool PutAudioStreamBuffer (SDL_AudioStream * stream, const void * buf, int len, SDL_ReleaseAudioBufferCallback callback, void * userdata) static
{
#if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: wants to put %d bytes", len);
#endif
    SDL_LockMutex(stream->lock);
    if (!CheckAudioStreamIsFullySetup(stream)) {
        SDL_UnlockMutex(stream->lock);
        return false;
    }
    if ((len % SDL_AUDIO_FRAMESIZE(stream->src_spec)) != 0) {
        SDL_UnlockMutex(stream->lock);
        return SDL_SetError("Can't add partial sample frames");
    }
    const bool retval = PutAudioStreamBufferInternal(stream, &stream->src_spec, stream->src_chmap, buf, len, callback, userdata);
    SDL_UnlockMutex(stream->lock);
    return retval;
}
References CheckAudioStreamIsFullySetup(), PutAudioStreamBufferInternal(), SDL_AUDIO_FRAMESIZE, SDL_LockMutex(), SDL_Log(), SDL_SetError(), and SDL_UnlockMutex().
Referenced by SDL_PutAudioStreamData(), and SDL_PutAudioStreamDataNoCopy().
PutAudioStreamBufferInternal()
bool PutAudioStreamBufferInternal (SDL_AudioStream * stream, const SDL_AudioSpec * spec, const int * chmap, const void * buf, int len, SDL_ReleaseAudioBufferCallback callback, void * userdata) static
{
    SDL_AudioTrack *track = NULL;
    if (callback) {
        track = SDL_CreateAudioTrack(stream->queue, spec, chmap, (Uint8 *)buf, len, len, callback, userdata);
        if (!track) {
            return false;
        }
    }
    const int prev_available = stream->put_callback ? SDL_GetAudioStreamAvailable(stream) : 0;
    bool retval = true;
    if (track) {
        SDL_AddTrackToAudioQueue(stream->queue, track);
    } else {
        retval = SDL_WriteToAudioQueue(stream->queue, spec, chmap, (const Uint8 *)buf, len);
    }
    if (retval) {
        if (stream->put_callback) {
            const int newavail = SDL_GetAudioStreamAvailable(stream) - prev_available;
            stream->put_callback(stream->put_callback_userdata, stream, newavail, newavail);
        }
    }
    return retval;
}
References NULL, SDL_AddTrackToAudioQueue(), SDL_CreateAudioTrack(), SDL_GetAudioStreamAvailable(), and SDL_WriteToAudioQueue().
Referenced by PutAudioStreamBuffer(), and SDL_PutAudioStreamPlanarData().
SDL_ChannelMapIsBogus()
bool SDL_ChannelMapIsBogus (const int * chmap, int channels)
{
    if (chmap) {
        for (int i = 0; i < channels; i++) {
            const int mapping = chmap[i];
            if ((mapping < -1) || (mapping >= channels)) {
                return true;
            }
        }
    }
    return false;
}
Referenced by SetAudioStreamChannelMap().
SDL_ChannelMapIsDefault()
bool SDL_ChannelMapIsDefault (const int * chmap, int channels)
{
    if (chmap) {
        for (int i = 0; i < channels; i++) {
            if (chmap[i] != i) {
                return false;
            }
        }
    }
    return true;
}
Referenced by SetAudioStreamChannelMap().
SDL_ClearAudioStream()
bool SDL_ClearAudioStream (SDL_AudioStream * stream)
Clear any pending data in the stream.
This drops any queued data, so there will be nothing to read from the stream until more is added.
Parameters
stream the audio stream to clear.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamAvailable
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
SDL_PutAudioStreamData
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    SDL_ClearAudioQueue(stream->queue);
    SDL_zero(stream->input_spec);
    stream->input_chmap = NULL;
    stream->resample_offset = 0;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References NULL, SDL_ClearAudioQueue(), SDL_InvalidParamError, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_zero.
SDL_ConvertAudioSamples()
bool SDL_ConvertAudioSamples (const SDL_AudioSpec * src_spec, const Uint8 * src_data, int src_len, const SDL_AudioSpec * dst_spec, Uint8 ** dst_data, int * dst_len)
Convert some audio data of one format to another format.
Please note that this function is for convenience, but should not be used to resample audio in blocks, as it will introduce audio artifacts on the boundaries. You should only use this function if you are converting audio data in its entirety in one call. If you want to convert audio in smaller chunks, use an SDL_AudioStream, which is designed for this situation.
Internally, this function creates and destroys an SDL_AudioStream on each use, so it's also less efficient than using one directly, if you need to convert multiple times.
Parameters
src_spec the format details of the input audio.
src_data the audio data to be converted.
src_len the len of src_data.
dst_spec the format details of the output audio.
dst_data will be filled with a pointer to converted audio data, which should be freed with SDL_free(). On error, it will be NULL.
dst_len will be filled with the len of dst_data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (dst_data) {
        *dst_data = NULL;
    }
    if (dst_len) {
        *dst_len = 0;
    }
    if (!src_data) {
        return SDL_InvalidParamError("src_data");
    } else if (src_len < 0) {
        return SDL_InvalidParamError("src_len");
    } else if (!dst_data) {
        return SDL_InvalidParamError("dst_data");
    } else if (!dst_len) {
        return SDL_InvalidParamError("dst_len");
    }
    bool result = false;
    Uint8 *dst = NULL;
    int dstlen = 0;
    SDL_AudioStream *stream = SDL_CreateAudioStream(src_spec, dst_spec);
    if (stream) {
        if (SDL_PutAudioStreamDataNoCopy(stream, src_data, src_len, NULL, NULL) && SDL_FlushAudioStream(stream)) {
            dstlen = SDL_GetAudioStreamAvailable(stream);
            if (dstlen >= 0) {
                dst = (Uint8 *)SDL_malloc(dstlen);
                if (dst) {
                    result = (SDL_GetAudioStreamData(stream, dst, dstlen) == dstlen);
                }
            }
        }
    }
    if (result) {
        *dst_data = dst;
        *dst_len = dstlen;
    } else {
        SDL_free(dst);
    }
    SDL_DestroyAudioStream(stream);
    return result;
}
References NULL, SDL_CreateAudioStream(), SDL_DestroyAudioStream(), SDL_FlushAudioStream(), SDL_free(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamData(), SDL_InvalidParamError, SDL_malloc(), and SDL_PutAudioStreamDataNoCopy().
SDL_CreateAudioStream()
SDL_AudioStream * SDL_CreateAudioStream (const SDL_AudioSpec * src_spec, const SDL_AudioSpec * dst_spec)
Create a new audio stream.
Parameters
src_spec the format details of the input audio.
dst_spec the format details of the output audio.
Returns
a new audio stream on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PutAudioStreamData
SDL_GetAudioStreamData
SDL_GetAudioStreamAvailable
SDL_FlushAudioStream
SDL_ClearAudioStream
SDL_SetAudioStreamFormat
SDL_DestroyAudioStream
{
    SDL_ChooseAudioConverters();
    SDL_SetupAudioResampler();
    SDL_AudioStream *result = (SDL_AudioStream *)SDL_calloc(1, sizeof(SDL_AudioStream));
    if (!result) {
        return NULL;
    }
    result->freq_ratio = 1.0f;
    result->gain = 1.0f;
    result->queue = SDL_CreateAudioQueue(8192);
    if (!result->queue) {
        SDL_free(result);
        return NULL;
    }
    result->lock = SDL_CreateMutex();
    if (!result->lock) {
        SDL_free(result->queue);
        SDL_free(result);
        return NULL;
    }
    OnAudioStreamCreated(result);
    if (!SDL_SetAudioStreamFormat(result, src_spec, dst_spec)) {
        SDL_DestroyAudioStream(result);
        return NULL;
    }
    return result;
}
References SDL_AudioStream::freq_ratio, SDL_AudioStream::gain, SDL_AudioStream::lock, NULL, OnAudioStreamCreated(), SDL_AudioStream::queue, SDL_calloc(), SDL_ChooseAudioConverters(), SDL_CreateAudioQueue(), SDL_CreateMutex(), SDL_DestroyAudioStream(), SDL_free(), SDL_SetAudioStreamFormat(), and SDL_SetupAudioResampler().
Referenced by SDL_ConvertAudioSamples(), and SDL_OpenAudioDeviceStream().
SDL_DestroyAudioStream()
void SDL_DestroyAudioStream (SDL_AudioStream * stream)
Free an audio stream.
This will release all allocated data, including any audio that is still queued. You do not need to manually clear the stream first.
If this stream was bound to an audio device, it is unbound during this call. If this stream was created with SDL_OpenAudioDeviceStream, the audio device that was opened alongside this stream's creation will be closed, too.
Parameters
stream the audio stream to destroy.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateAudioStream
{
    if (!stream) {
        return;
    }
    SDL_DestroyProperties(stream->props);
    OnAudioStreamDestroy(stream);
    const bool simplified = stream->simplified;
    if (simplified) {
        if (stream->bound_device) {
            SDL_assert(stream->bound_device->simplified);
            SDL_CloseAudioDevice(stream->bound_device->instance_id);  // this will unbind the stream.
        }
    } else {
        SDL_UnbindAudioStream(stream);
    }
    SDL_aligned_free(stream->work_buffer);
    SDL_DestroyAudioQueue(stream->queue);
    SDL_DestroyMutex(stream->lock);
    SDL_free(stream);
}
References OnAudioStreamDestroy(), SDL_aligned_free(), SDL_assert, SDL_CloseAudioDevice(), SDL_DestroyAudioQueue(), SDL_DestroyMutex(), SDL_DestroyProperties(), SDL_free(), and SDL_UnbindAudioStream().
Referenced by SDL_ConvertAudioSamples(), SDL_CreateAudioStream(), SDL_OpenAudioDeviceStream(), and SDL_QuitAudio().
SDL_FlushAudioStream()
bool SDL_FlushAudioStream (SDL_AudioStream * stream)
Tell the stream that you're done sending data, and anything being buffered should be converted/resampled and made available immediately.
It is legal to add more data to a stream after flushing, but there may be audio gaps in the output. Generally this is intended to signal the end of input, so the complete output becomes available.
Parameters
stream the audio stream to flush.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PutAudioStreamData
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    SDL_FlushAudioQueue(stream->queue);
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_FlushAudioQueue(), SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_ConvertAudioSamples().
SDL_GetAudioStreamAvailable()
int SDL_GetAudioStreamAvailable (SDL_AudioStream * stream)
Get the number of converted/resampled bytes available.
The stream may be buffering data behind the scenes until it has enough to resample correctly, so this number might be lower than what you expect, or even be zero. Add more data or flush the stream if you need the data now.
If the stream has so much data that it would overflow an int, the return value is clamped to a maximum value, but no queued data is lost; if there are gigabytes of data queued, the app might need to read some of it with SDL_GetAudioStreamData before this function's return value is no longer clamped.
Parameters
stream the audio stream to query.
Returns
the number of converted/resampled bytes available or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamData
SDL_PutAudioStreamData
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1;
    }
    SDL_LockMutex(stream->lock);
    if (!CheckAudioStreamIsFullySetup(stream)) {
        SDL_UnlockMutex(stream->lock);
        return 0;
    }
    Sint64 count = GetAudioStreamAvailableFrames(stream, NULL);
    // convert from sample frames to bytes in destination format.
    count *= SDL_AUDIO_FRAMESIZE(stream->dst_spec);
    SDL_UnlockMutex(stream->lock);
    // if this overflows an int, just clamp it to a maximum.
    return (int) SDL_min(count, SDL_INT_MAX);
}
References CheckAudioStreamIsFullySetup(), count, GetAudioStreamAvailableFrames(), NULL, SDL_AUDIO_FRAMESIZE, SDL_INT_MAX, SDL_InvalidParamError, SDL_LockMutex(), SDL_min, and SDL_UnlockMutex().
Referenced by PutAudioStreamBufferInternal(), and SDL_ConvertAudioSamples().
SDL_GetAudioStreamData()
int SDL_GetAudioStreamData (SDL_AudioStream * stream, void * buf, int len)
Get converted/resampled data from the stream.
The input/output data format/channels/samplerate is specified when creating the stream, and can be changed after creation by calling SDL_SetAudioStreamFormat.
Note that any conversion and resampling necessary is done during this call, and SDL_PutAudioStreamData simply queues unconverted data for later. This is different than SDL2, where that work was done while inputting new data to the stream and requesting the output just copied the converted data.
Parameters
stream the stream the audio is being requested from.
buf a buffer to fill with audio data.
len the maximum number of bytes to fill.
Returns
the number of bytes read from the stream or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearAudioStream
SDL_GetAudioStreamAvailable
SDL_PutAudioStreamData
{
    return SDL_GetAudioStreamDataAdjustGain(stream, voidbuf, len, 1.0f);
}
References SDL_GetAudioStreamDataAdjustGain().
Referenced by SDL_ConvertAudioSamples().
SDL_GetAudioStreamDataAdjustGain()
int SDL_GetAudioStreamDataAdjustGain (SDL_AudioStream * stream, void * voidbuf, int len, float extra_gain)
{
    Uint8 *buf = (Uint8 *) voidbuf;
#if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: want to get %d converted bytes", len);
#endif
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1;
    } else if (!buf) {
        SDL_InvalidParamError("buf");
        return -1;
    } else if (len < 0) {
        SDL_InvalidParamError("len");
        return -1;
    } else if (len == 0) {
        return 0; // nothing to do.
    }
    SDL_LockMutex(stream->lock);
    if (!CheckAudioStreamIsFullySetup(stream)) {
        SDL_UnlockMutex(stream->lock);
        return -1;
    }
    const float gain = stream->gain * extra_gain;
    const int dst_frame_size = SDL_AUDIO_FRAMESIZE(stream->dst_spec);
    len -= len % dst_frame_size;  // chop off any fractional sample frame.
    // give the callback a chance to fill in more stream data if it wants.
    if (stream->get_callback) {
        Sint64 total_request = len / dst_frame_size;  // start with sample frames desired
        Sint64 additional_request = total_request;
        Sint64 resample_offset = 0;
        Sint64 available_frames = GetAudioStreamAvailableFrames(stream, &resample_offset);
        additional_request -= SDL_min(additional_request, available_frames);
        Sint64 resample_rate = GetAudioStreamResampleRate(stream, stream->src_spec.freq, resample_offset);
        if (resample_rate) {
            total_request = SDL_GetResamplerInputFrames(total_request, resample_rate, resample_offset);
            additional_request = SDL_GetResamplerInputFrames(additional_request, resample_rate, resample_offset);
        }
        total_request *= SDL_AUDIO_FRAMESIZE(stream->src_spec);  // convert sample frames to bytes.
        additional_request *= SDL_AUDIO_FRAMESIZE(stream->src_spec);  // convert sample frames to bytes.
        stream->get_callback(stream->get_callback_userdata, stream, (int) SDL_min(additional_request, SDL_INT_MAX), (int) SDL_min(total_request, SDL_INT_MAX));
    }
    // Process the data in chunks to avoid allocating too much memory (and potential integer overflows)
    const int chunk_size = 4096;
    int total = 0;
    while (total < len) {
        // Audio is processed a track at a time.
        SDL_AudioSpec input_spec;
        int *input_chmap;
        bool flushed;
        const Sint64 available_frames = GetAudioStreamHead(stream, &input_spec, &input_chmap, &flushed);
        if (available_frames == 0) {
            if (flushed) {
                SDL_PopAudioQueueHead(stream->queue);
                SDL_zero(stream->input_spec);
                stream->resample_offset = 0;
                stream->input_chmap = NULL;
                continue;
            }
            // There are no frames available, but the track hasn't been flushed, so more might be added later.
            break;
        }
        if (!UpdateAudioStreamInputSpec(stream, &input_spec, input_chmap)) {
            total = total ? total : -1;
            break;
        }
        // Clamp the output length to the maximum currently available.
        // GetAudioStreamDataInternal requires enough input data is available.
        int output_frames = (len - total) / dst_frame_size;
        output_frames = SDL_min(output_frames, chunk_size);
        output_frames = (int) SDL_min(output_frames, available_frames);
        if (!GetAudioStreamDataInternal(stream, &buf[total], output_frames, gain)) {
            total = total ? total : -1;
            break;
        }
        total += output_frames * dst_frame_size;
    }
    SDL_UnlockMutex(stream->lock);
#if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: Final result was %d", total);
#endif
    return total;
}
References CheckAudioStreamIsFullySetup(), GetAudioStreamAvailableFrames(), GetAudioStreamDataInternal(), GetAudioStreamHead(), GetAudioStreamResampleRate(), NULL, SDL_AUDIO_FRAMESIZE, SDL_GetResamplerInputFrames(), SDL_INT_MAX, SDL_InvalidParamError, SDL_LockMutex(), SDL_Log(), SDL_min, SDL_PopAudioQueueHead(), SDL_UnlockMutex(), SDL_zero, and UpdateAudioStreamInputSpec().
Referenced by SDL_GetAudioStreamData(), and SDL_PlaybackAudioThreadIterate().
SDL_GetAudioStreamFormat()
bool SDL_GetAudioStreamFormat (SDL_AudioStream * stream, SDL_AudioSpec * src_spec, SDL_AudioSpec * dst_spec)
Query the current format of an audio stream.
Parameters
stream the SDL_AudioStream to query.
src_spec where to store the input audio format; ignored if NULL.
dst_spec where to store the output audio format; ignored if NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamFormat
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    if (src_spec) {
        SDL_copyp(src_spec, &stream->src_spec);
    }
    if (dst_spec) {
        SDL_copyp(dst_spec, &stream->dst_spec);
    }
    SDL_UnlockMutex(stream->lock);
    if (src_spec && src_spec->format == 0) {
        return SDL_SetError("Stream has no source format");
    } else if (dst_spec && dst_spec->format == 0) {
        return SDL_SetError("Stream has no destination format");
    }
    return true;
}
References SDL_AudioSpec::format, SDL_copyp, SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), and SDL_UnlockMutex().
SDL_GetAudioStreamFrequencyRatio()
float SDL_GetAudioStreamFrequencyRatio (SDL_AudioStream * stream)
Get the frequency ratio of an audio stream.
Parameters
stream the SDL_AudioStream to query.
Returns
the frequency ratio of the stream or 0.0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamFrequencyRatio
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return 0.0f;
    }
    SDL_LockMutex(stream->lock);
    const float freq_ratio = stream->freq_ratio;
    SDL_UnlockMutex(stream->lock);
    return freq_ratio;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamGain()
float SDL_GetAudioStreamGain (SDL_AudioStream * stream)
Get the gain of an audio stream.
The gain of a stream is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio streams default to a gain of 1.0f (no change in output).
Parameters
stream the SDL_AudioStream to query.
Returns
the gain of the stream or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamGain
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1.0f;
    }
    SDL_LockMutex(stream->lock);
    const float gain = stream->gain;
    SDL_UnlockMutex(stream->lock);
    return gain;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamInputChannelMap()
int * SDL_GetAudioStreamInputChannelMap (SDL_AudioStream * stream, int * count)
Get the current input channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
Audio streams default to no remapping applied. This is represented by returning NULL, and does not signify an error.
Parameters
stream the SDL_AudioStream to query.
count On output, set to number of channels in the map. Can be NULL.
Returns
an array of the current channel mapping, with as many elements as the current output spec's channels, or NULL if default. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    int *result = NULL;
    int channels = 0;
    if (stream) {
        SDL_LockMutex(stream->lock);
        channels = stream->src_spec.channels;
        result = SDL_ChannelMapDup(stream->src_chmap, channels);
        SDL_UnlockMutex(stream->lock);
    }
    if (count) {
        *count = channels;
    }
    return result;
}
References count, NULL, SDL_ChannelMapDup(), SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamOutputChannelMap()
int * SDL_GetAudioStreamOutputChannelMap (SDL_AudioStream * stream, int * count)
Get the current output channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
Audio streams default to no remapping applied. This is represented by returning NULL, and does not signify an error.
Parameters
stream the SDL_AudioStream to query.
count On output, set to number of channels in the map. Can be NULL.
Returns
an array of the current channel mapping, with as many elements as the current output spec's channels, or NULL if default. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    int *result = NULL;
    int channels = 0;
    if (stream) {
        SDL_LockMutex(stream->lock);
        channels = stream->dst_spec.channels;
        result = SDL_ChannelMapDup(stream->dst_chmap, channels);
        SDL_UnlockMutex(stream->lock);
    }
    if (count) {
        *count = channels;
    }
    return result;
}
References count, NULL, SDL_ChannelMapDup(), SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamProperties()
SDL_PropertiesID SDL_GetAudioStreamProperties (SDL_AudioStream * stream)
Get the properties associated with an audio stream.
The application can hang any data it wants here, but the following properties are understood by SDL:
SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN: if true (the default), the stream be automatically cleaned up when the audio subsystem quits. If set to false, the streams will persist beyond that. This property is ignored for streams created through SDL_OpenAudioDeviceStream(), and will always be cleaned up. Streams that are not cleaned up will still be unbound from devices when the audio subsystem quits. This property was added in SDL 3.4.0.
Parameters
stream the SDL_AudioStream to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return 0;
    }
    SDL_LockMutex(stream->lock);
    if (stream->props == 0) {
        stream->props = SDL_CreateProperties();
    }
    SDL_UnlockMutex(stream->lock);
    return stream->props;
}
References SDL_CreateProperties(), SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_GetAudioStreamQueued()
int SDL_GetAudioStreamQueued (SDL_AudioStream * stream)
Get the number of bytes currently queued.
This is the number of bytes put into a stream as input, not the number that can be retrieved as output. Because of several details, it's not possible to calculate one number directly from the other. If you need to know how much usable data can be retrieved right now, you should use SDL_GetAudioStreamAvailable() and not this function.
Note that audio streams can change their input format at any time, even if there is still data queued in a different format, so the returned byte count will not necessarily match the number of sample frames available. Users of this API should be aware of format changes they make when feeding a stream and plan accordingly.
Queued data is not converted until it is consumed by SDL_GetAudioStreamData, so this value should be representative of the exact data that was put into the stream.
If the stream has so much data that it would overflow an int, the return value is clamped to a maximum value, but no queued data is lost; if there are gigabytes of data queued, the app might need to read some of it with SDL_GetAudioStreamData before this function's return value is no longer clamped.
Parameters
stream the audio stream to query.
Returns
the number of bytes queued or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PutAudioStreamData
SDL_ClearAudioStream
{
    if (!stream) {
        SDL_InvalidParamError("stream");
        return -1;
    }
    SDL_LockMutex(stream->lock);
    size_t total = SDL_GetAudioQueueQueued(stream->queue);
    SDL_UnlockMutex(stream->lock);
    // if this overflows an int, just clamp it to a maximum.
    return (int) SDL_min(total, SDL_INT_MAX);
}
References SDL_GetAudioQueueQueued(), SDL_INT_MAX, SDL_InvalidParamError, SDL_LockMutex(), SDL_min, and SDL_UnlockMutex().
SDL_IsSupportedAudioFormat()
bool SDL_IsSupportedAudioFormat (const SDL_AudioFormat fmt) static
{
    switch (fmt) {
    case SDL_AUDIO_U8:
    case SDL_AUDIO_S8:
    case SDL_AUDIO_S16LE:
    case SDL_AUDIO_S16BE:
    case SDL_AUDIO_S32LE:
    case SDL_AUDIO_S32BE:
    case SDL_AUDIO_F32LE:
    case SDL_AUDIO_F32BE:
        return true;  // supported.
    default:
        break;
    }
    return false;  // unsupported.
}
References SDL_AUDIO_F32BE, SDL_AUDIO_F32LE, SDL_AUDIO_S16BE, SDL_AUDIO_S16LE, SDL_AUDIO_S32BE, SDL_AUDIO_S32LE, SDL_AUDIO_S8, and SDL_AUDIO_U8.
Referenced by ConvertAudio(), and SDL_SetAudioStreamFormat().
SDL_IsSupportedChannelCount()
bool SDL_IsSupportedChannelCount (const int channels) static
{
    return ((channels >= 1) && (channels <= 8));
}
Referenced by ConvertAudio(), InterleaveAudioChannels(), and SDL_SetAudioStreamFormat().
SDL_LockAudioStream()
bool SDL_LockAudioStream (SDL_AudioStream * stream)
Lock an audio stream for serialized access.
Each SDL_AudioStream has an internal mutex it uses to protect its data structures from threading conflicts. This function allows an app to lock that mutex, which could be useful if registering callbacks on this stream.
One does not need to lock a stream to use in it most cases, as the stream manages this lock internally. However, this lock is held during callbacks, which may run from arbitrary threads at any time, so if an app needs to protect shared data during those callbacks, locking the stream guarantees that the callback is not running while the lock is held.
As this is just a wrapper over SDL_LockMutex for an internal lock; it has all the same attributes (recursive locks are allowed, etc).
Parameters
stream the audio stream to lock.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_UnlockAudioStream
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, and SDL_LockMutex().
SDL_PutAudioStreamData()
bool SDL_PutAudioStreamData (SDL_AudioStream * stream, const void * buf, int len)
Add data to the stream.
This data must match the format/channels/samplerate specified in the latest call to SDL_SetAudioStreamFormat, or the format specified when creating the stream if it hasn't been changed.
Note that this call simply copies the unconverted data for later. This is different than SDL2, where data was converted during the Put call and the Get call would just dequeue the previously-converted data.
Parameters
stream the stream the audio data is being added to.
buf a pointer to the audio data to add.
len the number of bytes to write to the stream.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearAudioStream
SDL_FlushAudioStream
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (!buf) {
        return SDL_InvalidParamError("buf");
    } else if (len < 0) {
        return SDL_InvalidParamError("len");
    } else if (len == 0) {
        return true; // nothing to do.
    }
    // When copying in large amounts of data, try and do as much work as possible
    // outside of the stream lock, otherwise the output device is likely to be starved.
    const int large_input_thresh = 64 * 1024;
    if (len >= large_input_thresh) {
        void *data = SDL_malloc(len);
        if (!data) {
            return false;
        }
        SDL_memcpy(data, buf, len);
        bool ret = PutAudioStreamBuffer(stream, data, len, FreeAllocatedAudioBuffer, NULL);
        if (!ret) {
            SDL_free(data);
        }
        return ret;
    }
    return PutAudioStreamBuffer(stream, buf, len, NULL, NULL);
}
References FreeAllocatedAudioBuffer(), NULL, PutAudioStreamBuffer(), SDL_free(), SDL_InvalidParamError, SDL_malloc(), and SDL_memcpy.
Referenced by SDL_PutAudioStreamPlanarData(), and SDL_RecordingAudioThreadIterate().
SDL_PutAudioStreamDataNoCopy()
bool SDL_PutAudioStreamDataNoCopy (SDL_AudioStream * stream, const void * buf, int len, SDL_AudioStreamDataCompleteCallback callback, void * userdata)
Add external data to an audio stream without copying it.
Unlike SDL_PutAudioStreamData(), this function does not make a copy of the provided data, instead storing the provided pointer. This means that the put operation does not need to allocate and copy the data, but the original data must remain available until the stream is done with it, either by being read from the stream in its entirety, or a call to SDL_ClearAudioStream() or SDL_DestroyAudioStream().
The data must match the format/channels/samplerate specified in the latest call to SDL_SetAudioStreamFormat, or the format specified when creating the stream if it hasn't been changed.
An optional callback may be provided, which is called when the stream no longer needs the data. Once this callback fires, the stream will not access the data again. This callback will fire for any reason the data is no longer needed, including clearing or destroying the stream.
Note that there is still an allocation to store tracking information, so this function is more efficient for larger blocks of data. If you're planning to put a few samples at a time, it will be more efficient to use SDL_PutAudioStreamData(), which allocates and buffers in blocks.
Parameters
stream the stream the audio data is being added to.
buf a pointer to the audio data to add.
len the number of bytes to add to the stream.
callback the callback function to call when the data is no longer needed by the stream. May be NULL.
userdata an opaque pointer provided to the callback for its own personal use.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.4.0.
See also
SDL_ClearAudioStream
SDL_FlushAudioStream
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (!buf) {
        return SDL_InvalidParamError("buf");
    } else if (len < 0) {
        return SDL_InvalidParamError("len");
    } else if (len == 0) {
        if (callback) {
            callback(userdata, buf, len);
        }
        return true; // nothing to do.
    }
    return PutAudioStreamBuffer(stream, buf, len, callback ? callback : DontFreeThisAudioBuffer, userdata);
}
References DontFreeThisAudioBuffer(), PutAudioStreamBuffer(), and SDL_InvalidParamError.
Referenced by SDL_ConvertAudioSamples().
SDL_PutAudioStreamPlanarData()
bool SDL_PutAudioStreamPlanarData (SDL_AudioStream * stream, const void *const * channel_buffers, int num_channels, int num_samples)
Add data to the stream with each channel in a separate array.
This data must match the format/channels/samplerate specified in the latest call to SDL_SetAudioStreamFormat, or the format specified when creating the stream if it hasn't been changed.
The data will be interleaved and queued. Note that SDL_AudioStream only operates on interleaved data, so this is simply a convenience function for easily queueing data from sources that provide separate arrays. There is no equivalent function to retrieve planar data.
The arrays in channel_buffers are ordered as they are to be interleaved; the first array will be the first sample in the interleaved data. Any individual array may be NULL; in this case, silence will be interleaved for that channel.
num_channels specifies how many arrays are in channel_buffers. This can be used as a safety to prevent overflow, in case the stream format has changed elsewhere. If more channels are specified than the current input spec, they are ignored. If less channels are specified, the missing arrays are treated as if they are NULL (silence is written to those channels). If the count is -1, SDL will assume the array count matches the current input spec.
Note that num_samples is the number of samples per array. This can also be thought of as the number of sample frames to be queued. A value of 1 with stereo arrays will queue two samples to the stream. This is different than SDL_PutAudioStreamData, which wants the size of a single array in bytes.
Parameters
stream the stream the audio data is being added to.
channel_buffers a pointer to an array of arrays, one array per channel.
num_channels the number of arrays in channel_buffers or -1.
num_samples the number of samples per array to write to the stream.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, but if the stream has a callback set, the caller might need to manage extra locking.
Since
This function is available since SDL 3.4.0.
See also
SDL_ClearAudioStream
SDL_FlushAudioStream
SDL_GetAudioStreamData
SDL_GetAudioStreamQueued
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (!channel_buffers) {
        return SDL_InvalidParamError("channel_buffers");
    } else if (num_samples < 0) {
        return SDL_InvalidParamError("num_samples");
    } else if (num_samples == 0) {
        return true; // nothing to do.
    }
    // we do the interleaving up front without the lock held, so the audio device doesn't starve while we work.
    //  but we _do_ need to know the current input spec.
    SDL_AudioSpec spec;
    int chmap_copy[SDL_MAX_CHANNELMAP_CHANNELS];
    int *chmap = NULL;
    SDL_LockMutex(stream->lock);
    if (!CheckAudioStreamIsFullySetup(stream)) {
        SDL_UnlockMutex(stream->lock);
        return false;
    }
    SDL_copyp(&spec, &stream->src_spec);
    if (stream->src_chmap) {
        chmap = chmap_copy;
        SDL_memcpy(chmap, stream->src_chmap, sizeof (*chmap) * spec.channels);
    }
    SDL_UnlockMutex(stream->lock);
    if (spec.channels == 1) {  // nothing to interleave, just use the usual function.
        return SDL_PutAudioStreamData(stream, channel_buffers[0], SDL_AUDIO_FRAMESIZE(spec) * num_samples);
    }
    bool retval = false;
    const int len = SDL_AUDIO_FRAMESIZE(spec) * num_samples;
    #if DEBUG_AUDIOSTREAM
    SDL_Log("AUDIOSTREAM: wants to put %d bytes of planar data", len);
    #endif
    // Is the data small enough to just interleave it on the stack and put it through the normal interface?
    #define INTERLEAVE_STACK_SIZE 1024
    Uint8 stackbuf[INTERLEAVE_STACK_SIZE];
    void *data = stackbuf;
    SDL_ReleaseAudioBufferCallback callback = NULL;
    if (len > INTERLEAVE_STACK_SIZE) {
        // too big for the stack? Just SDL_malloc a block and interleave into that. To avoid the extra copy, we'll just set it as a
        //  new track in the queue (the distinction is specifying a callback to PutAudioStreamBufferInternal, to release the buffer).
        data = SDL_malloc(len);
        if (!data) {
            return false;
        }
        callback = FreeAllocatedAudioBuffer;
    }
    InterleaveAudioChannels(data, channel_buffers, num_channels, num_samples, &spec);
    // it's okay if the stream format changed on another thread while we didn't hold the lock; PutAudioStreamBufferInternal will notice
    //  and set up a new track with the right format, and the next SDL_PutAudioStreamData will notice that stream->src_spec doesn't
    //  match the new track and set up a new one again. It's a bad idea to change the format on another thread while putting here,
    //  but everything _will_ work out with the format that was (presumably) expected.
    SDL_LockMutex(stream->lock);
    retval = PutAudioStreamBufferInternal(stream, &spec, chmap, data, len, callback, NULL);
    SDL_UnlockMutex(stream->lock);
    return retval;
}
References SDL_AudioSpec::channels, CheckAudioStreamIsFullySetup(), FreeAllocatedAudioBuffer(), INTERLEAVE_STACK_SIZE, InterleaveAudioChannels(), NULL, PutAudioStreamBufferInternal(), SDL_AUDIO_FRAMESIZE, SDL_copyp, SDL_InvalidParamError, SDL_LockMutex(), SDL_Log(), SDL_malloc(), SDL_MAX_CHANNELMAP_CHANNELS, SDL_memcpy, SDL_PutAudioStreamData(), and SDL_UnlockMutex().
SDL_SetAudioStreamFormat()
bool SDL_SetAudioStreamFormat (SDL_AudioStream * stream, const SDL_AudioSpec * src_spec, const SDL_AudioSpec * dst_spec)
Change the input and output formats of an audio stream.
Future calls to and SDL_GetAudioStreamAvailable and SDL_GetAudioStreamData will reflect the new format, and future calls to SDL_PutAudioStreamData must provide data in the new input formats.
Data that was previously queued in the stream will still be operated on in the format that was current when it was added, which is to say you can put the end of a sound file in one format to a stream, change formats for the next sound file, and start putting that new data while the previous sound file is still queued, and everything will still play back correctly.
If a stream is bound to a device, then the format of the side of the stream bound to a device cannot be changed (src_spec for recording devices, dst_spec for playback devices). Attempts to make a change to this side will be ignored, but this will not report an error. The other side's format can be changed.
Parameters
stream the stream the format is being changed.
src_spec the new format of the audio input; if NULL, it is not changed.
dst_spec the new format of the audio output; if NULL, it is not changed.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamFormat
SDL_SetAudioStreamFrequencyRatio
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    // note that while we've removed the maximum frequency checks, SDL _will_
    // fail to resample to extremely high sample rates correctly. Really high,
    // like 196608000Hz. File a bug.  :P
    if (src_spec) {
        if (!SDL_IsSupportedAudioFormat(src_spec->format)) {
            return SDL_InvalidParamError("src_spec->format");
        } else if (!SDL_IsSupportedChannelCount(src_spec->channels)) {
            return SDL_InvalidParamError("src_spec->channels");
        } else if (src_spec->freq <= 0) {
            return SDL_InvalidParamError("src_spec->freq");
        }
    }
    if (dst_spec) {
        if (!SDL_IsSupportedAudioFormat(dst_spec->format)) {
            return SDL_InvalidParamError("dst_spec->format");
        } else if (!SDL_IsSupportedChannelCount(dst_spec->channels)) {
            return SDL_InvalidParamError("dst_spec->channels");
        } else if (dst_spec->freq <= 0) {
            return SDL_InvalidParamError("dst_spec->freq");
        }
    }
    SDL_LockMutex(stream->lock);
    // quietly refuse to change the format of the end currently bound to a device.
    if (stream->bound_device) {
        if (stream->bound_device->physical_device->recording) {
            src_spec = NULL;
        } else {
            dst_spec = NULL;
        }
    }
    if (src_spec) {
        if (src_spec->channels != stream->src_spec.channels) {
            SDL_free(stream->src_chmap);
            stream->src_chmap = NULL;
        }
        SDL_copyp(&stream->src_spec, src_spec);
    }
    if (dst_spec) {
        if (dst_spec->channels != stream->dst_spec.channels) {
            SDL_free(stream->dst_chmap);
            stream->dst_chmap = NULL;
        }
        SDL_copyp(&stream->dst_spec, dst_spec);
    }
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_AudioSpec::channels, SDL_AudioSpec::format, SDL_AudioSpec::freq, NULL, SDL_copyp, SDL_free(), SDL_InvalidParamError, SDL_IsSupportedAudioFormat(), SDL_IsSupportedChannelCount(), SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_CreateAudioStream().
SDL_SetAudioStreamFrequencyRatio()
bool SDL_SetAudioStreamFrequencyRatio (SDL_AudioStream * stream, float ratio)
Change the frequency ratio of an audio stream.
The frequency ratio is used to adjust the rate at which input data is consumed. Changing this effectively modifies the speed and pitch of the audio. A value greater than 1.0f will play the audio faster, and at a higher pitch. A value less than 1.0f will play the audio slower, and at a lower pitch. 1.0f means play at normal speed.
This is applied during SDL_GetAudioStreamData, and can be continuously changed to create various effects.
Parameters
stream the stream on which the frequency ratio is being changed.
ratio the frequency ratio. 1.0 is normal speed. Must be between 0.01 and 100.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamFrequencyRatio
SDL_SetAudioStreamFormat
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    // Picked mostly arbitrarily.
    const float min_freq_ratio = 0.01f;
    const float max_freq_ratio = 100.0f;
    if (freq_ratio < min_freq_ratio) {
        return SDL_SetError("Frequency ratio is too low");
    } else if (freq_ratio > max_freq_ratio) {
        return SDL_SetError("Frequency ratio is too high");
    }
    SDL_LockMutex(stream->lock);
    stream->freq_ratio = freq_ratio;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), and SDL_UnlockMutex().
SDL_SetAudioStreamGain()
bool SDL_SetAudioStreamGain (SDL_AudioStream * stream, float gain)
Change the gain of an audio stream.
The gain of a stream is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio streams default to a gain of 1.0f (no change in output).
This is applied during SDL_GetAudioStreamData, and can be continuously changed to create various effects.
Parameters
stream the stream on which the gain is being changed.
gain the gain. 1.0f is no change, 0.0f is silence.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamGain
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    } else if (gain < 0.0f) {
        return SDL_InvalidParamError("gain");
    }
    SDL_LockMutex(stream->lock);
    stream->gain = gain;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
SDL_SetAudioStreamGetCallback()
bool SDL_SetAudioStreamGetCallback (SDL_AudioStream * stream, SDL_AudioStreamCallback callback, void * userdata)
Set a callback that runs when data is requested from an audio stream.
This callback is called before data is obtained from the stream, giving the callback the chance to add more on-demand.
The callback can (optionally) call SDL_PutAudioStreamData() to add more audio to the stream during this call; if needed, the request that triggered this callback will obtain the new data immediately.
The callback's additional_amount argument is roughly how many bytes of unconverted data (in the stream's input format) is needed by the caller, although this may overestimate a little for safety. This takes into account how much is already in the stream and only asks for any extra necessary to resolve the request, which means the callback may be asked for zero bytes, and a different amount on each call.
The callback is not required to supply exact amounts; it is allowed to supply too much or too little or none at all. The caller will get what's available, up to the amount they requested, regardless of this callback's outcome.
Clearing or flushing an audio stream does not call this callback.
This function obtains the stream's lock, which means any existing callback (get or put) in progress will finish running before setting the new callback.
Setting a NULL function turns off the callback.
Parameters
stream the audio stream to set the new callback on.
callback the new callback function to call when data is requested from the stream.
userdata an opaque pointer provided to the callback for its own personal use.
Returns
true on success or false on failure; call SDL_GetError() for more information. This only fails if stream is NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamPutCallback
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    stream->get_callback = callback;
    stream->get_callback_userdata = userdata;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_OpenAudioDeviceStream().
SDL_SetAudioStreamInputChannelMap()
bool SDL_SetAudioStreamInputChannelMap (SDL_AudioStream * stream, const int * chmap, int count)
Set the current input channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
The input channel map reorders data that is added to a stream via SDL_PutAudioStreamData. Future calls to SDL_PutAudioStreamData must provide data in the new channel order.
Each item in the array represents an input channel, and its value is the channel that it should be remapped to. To reverse a stereo signal's left and right values, you'd have an array of { 1, 0 }. It is legal to remap multiple channels to the same thing, so { 1, 1 } would duplicate the right channel to both channels of a stereo signal. An element in the channel map set to -1 instead of a valid channel will mute that channel, setting it to a silence value.
You cannot change the number of channels through a channel map, just reorder/mute them.
Data that was previously queued in the stream will still be operated on in the order that was current when it was added, which is to say you can put the end of a sound file in one order to a stream, change orders for the next sound file, and start putting that new data while the previous sound file is still queued, and everything will still play back correctly.
Audio streams default to no remapping applied. Passing a NULL channel map is legal, and turns off remapping.
SDL will copy the channel map; the caller does not have to save this array after this call.
If count is not equal to the current number of channels in the audio stream's format, this will fail. This is a safety measure to make sure a race condition hasn't changed the format while this call is setting the channel map.
Unlike attempting to change the stream's format, the input channel map on a stream bound to a recording device is permitted to change at any time; any data added to the stream from the device after this call will have the new mapping, but previously-added data will still have the prior mapping.
Parameters
stream the SDL_AudioStream to change.
chmap the new channel map, NULL to reset to default.
count The number of channels in the map.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running. Don't change the stream's format to have a different number of channels from a a different thread at the same time, though!
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    return SetAudioStreamChannelMap(stream, &stream->src_spec, &stream->src_chmap, chmap, channels, 1);
}
References SetAudioStreamChannelMap().
SDL_SetAudioStreamOutputChannelMap()
bool SDL_SetAudioStreamOutputChannelMap (SDL_AudioStream * stream, const int * chmap, int count)
Set the current output channel map of an audio stream.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
The output channel map reorders data that is leaving a stream via SDL_GetAudioStreamData.
Each item in the array represents an input channel, and its value is the channel that it should be remapped to. To reverse a stereo signal's left and right values, you'd have an array of { 1, 0 }. It is legal to remap multiple channels to the same thing, so { 1, 1 } would duplicate the right channel to both channels of a stereo signal. An element in the channel map set to -1 instead of a valid channel will mute that channel, setting it to a silence value.
You cannot change the number of channels through a channel map, just reorder/mute them.
The output channel map can be changed at any time, as output remapping is applied during SDL_GetAudioStreamData.
Audio streams default to no remapping applied. Passing a NULL channel map is legal, and turns off remapping.
SDL will copy the channel map; the caller does not have to save this array after this call.
If count is not equal to the current number of channels in the audio stream's format, this will fail. This is a safety measure to make sure a race condition hasn't changed the format while this call is setting the channel map.
Unlike attempting to change the stream's format, the output channel map on a stream bound to a recording device is permitted to change at any time; any data added to the stream after this call will have the new mapping, but previously-added data will still have the prior mapping. When the channel map doesn't match the hardware's channel layout, SDL will convert the data before feeding it to the device for playback.
Parameters
stream the SDL_AudioStream to change.
chmap the new channel map, NULL to reset to default.
count The number of channels in the map.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running. Don't change the stream's format to have a different number of channels from a a different thread at the same time, though!
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    return SetAudioStreamChannelMap(stream, &stream->dst_spec, &stream->dst_chmap, chmap, channels, 0);
}
References SetAudioStreamChannelMap().
SDL_SetAudioStreamPutCallback()
bool SDL_SetAudioStreamPutCallback (SDL_AudioStream * stream, SDL_AudioStreamCallback callback, void * userdata)
Set a callback that runs when data is added to an audio stream.
This callback is called after the data is added to the stream, giving the callback the chance to obtain it immediately.
The callback can (optionally) call SDL_GetAudioStreamData() to obtain audio from the stream during this call.
The callback's additional_amount argument is how many bytes of converted data (in the stream's output format) was provided by the caller, although this may underestimate a little for safety. This value might be less than what is currently available in the stream, if data was already there, and might be less than the caller provided if the stream needs to keep a buffer to aid in resampling. Which means the callback may be provided with zero bytes, and a different amount on each call.
The callback may call SDL_GetAudioStreamAvailable to see the total amount currently available to read from the stream, instead of the total provided by the current call.
The callback is not required to obtain all data. It is allowed to read less or none at all. Anything not read now simply remains in the stream for later access.
Clearing or flushing an audio stream does not call this callback.
This function obtains the stream's lock, which means any existing callback (get or put) in progress will finish running before setting the new callback.
Setting a NULL function turns off the callback.
Parameters
stream the audio stream to set the new callback on.
callback the new callback function to call when data is added to the stream.
userdata an opaque pointer provided to the callback for its own personal use.
Returns
true on success or false on failure; call SDL_GetError() for more information. This only fails if stream is NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamGetCallback
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_LockMutex(stream->lock);
    stream->put_callback = callback;
    stream->put_callback_userdata = userdata;
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_OpenAudioDeviceStream().
SDL_UnlockAudioStream()
bool SDL_UnlockAudioStream (SDL_AudioStream * stream)
Unlock an audio stream for serialized access.
This unlocks an audio stream after a call to SDL_LockAudioStream.
Parameters
stream the audio stream to unlock.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
You should only call this from the same thread that previously called SDL_LockAudioStream.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockAudioStream
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    SDL_UnlockMutex(stream->lock);
    return true;
}
References SDL_InvalidParamError, and SDL_UnlockMutex().
SetAudioStreamChannelMap()
bool SetAudioStreamChannelMap (SDL_AudioStream * stream, const SDL_AudioSpec * spec, int ** stream_chmap, const int * chmap, int channels, int isinput)
{
    if (!stream) {
        return SDL_InvalidParamError("stream");
    }
    bool result = true;
    SDL_LockMutex(stream->lock);
    if (channels != spec->channels) {
        result = SDL_SetError("Wrong number of channels");
    } else if (!*stream_chmap && !chmap) {
        // already at default, we're good.
    } else if (*stream_chmap && chmap && (SDL_memcmp(*stream_chmap, chmap, sizeof (*chmap) * channels) == 0)) {
        // already have this map, don't allocate/copy it again.
    } else if (SDL_ChannelMapIsBogus(chmap, channels)) {
        result = SDL_SetError("Invalid channel mapping");
    } else {
        if (SDL_ChannelMapIsDefault(chmap, channels)) {
            chmap = NULL;  // just apply a default mapping.
        }
        if (chmap) {
            int *dupmap = SDL_ChannelMapDup(chmap, channels);
            if (!dupmap) {
                result = SDL_SetError("Invalid channel mapping");
            } else {
                SDL_free(*stream_chmap);
                *stream_chmap = dupmap;
            }
        } else {
            SDL_free(*stream_chmap);
            *stream_chmap = NULL;
        }
    }
    SDL_UnlockMutex(stream->lock);
    return result;
}
References SDL_AudioSpec::channels, NULL, SDL_ChannelMapDup(), SDL_ChannelMapIsBogus(), SDL_ChannelMapIsDefault(), SDL_free(), SDL_InvalidParamError, SDL_LockMutex(), SDL_memcmp(), SDL_SetError(), and SDL_UnlockMutex().
Referenced by SDL_SetAudioStreamInputChannelMap(), SDL_SetAudioStreamOutputChannelMap(), and UpdateAudioStreamFormatsPhysical().
SwizzleAudio()
void SwizzleAudio (const int num_frames, void * dst, const void * src, int channels, const int * map, SDL_AudioFormat fmt) static
{
    const int bitsize = (int) SDL_AUDIO_BITSIZE(fmt);
    bool has_null_mappings = false;  // !!! FIXME: calculate this when setting the channel map instead.
    for (int i = 0; i < channels; i++) {
        if (map[i] == -1) {
            has_null_mappings = true;
            break;
        }
    }
    #define CHANNEL_SWIZZLE(bits) { \
        Uint##bits *tdst = (Uint##bits *) dst; /* treat as UintX; we only care about moving bits and not the type here. */ \
        const Uint##bits *tsrc = (const Uint##bits *) src; \
        if (src != dst) {  /* don't need to copy to a temporary frame first. */ \
            if (has_null_mappings) { \
                const Uint##bits silence = (Uint##bits) SDL_GetSilenceValueForFormat(fmt); \
                for (int i = 0; i < num_frames; i++, tsrc += channels, tdst += channels) { \
                    for (int ch = 0; ch < channels; ch++) { \
                        const int m = map[ch]; \
                        tdst[ch] = (m == -1) ? silence : tsrc[m]; \
                    } \
                } \
            } else { \
                for (int i = 0; i < num_frames; i++, tsrc += channels, tdst += channels) { \
                    for (int ch = 0; ch < channels; ch++) { \
                        tdst[ch] = tsrc[map[ch]]; \
                    } \
                } \
            } \
        } else { \
            bool isstack; \
            Uint##bits *tmp = (Uint##bits *) SDL_small_alloc(int, channels, &isstack); /* !!! FIXME: allocate this when setting the channel map instead. */ \
            if (tmp) { \
                if (has_null_mappings) { \
                    const Uint##bits silence = (Uint##bits) SDL_GetSilenceValueForFormat(fmt); \
                    for (int i = 0; i < num_frames; i++, tsrc += channels, tdst += channels) { \
                        for (int ch = 0; ch < channels; ch++) { \
                            const int m = map[ch]; \
                            tmp[ch] = (m == -1) ? silence : tsrc[m]; \
                        } \
                        for (int ch = 0; ch < channels; ch++) { \
                            tdst[ch] = tmp[ch]; \
                        } \
                    } \
                } else { \
                    for (int i = 0; i < num_frames; i++, tsrc += channels, tdst += channels) { \
                        for (int ch = 0; ch < channels; ch++) { \
                            tmp[ch] = tsrc[map[ch]]; \
                        } \
                        for (int ch = 0; ch < channels; ch++) { \
                            tdst[ch] = tmp[ch]; \
                        } \
                    } \
                } \
                SDL_small_free(tmp, isstack); \
            } \
        } \
    }
    switch (bitsize) {
        case 8: CHANNEL_SWIZZLE(8); break;
        case 16: CHANNEL_SWIZZLE(16); break;
        case 32: CHANNEL_SWIZZLE(32); break;
        // we don't currently have int64 or double audio datatypes, so no `case 64` for now.
        default: SDL_assert(!"Unsupported audio datatype size"); break;
    }
    #undef CHANNEL_SWIZZLE
}
References CHANNEL_SWIZZLE, SDL_assert, and SDL_AUDIO_BITSIZE.
Referenced by ConvertAudio().
UpdateAudioStreamInputSpec()
bool UpdateAudioStreamInputSpec (SDL_AudioStream * stream, const SDL_AudioSpec * spec, const int * chmap) static
{
    if (SDL_AudioSpecsEqual(&stream->input_spec, spec, stream->input_chmap, chmap)) {
        return true;
    }
    if (!SDL_ResetAudioQueueHistory(stream->queue, SDL_GetResamplerHistoryFrames())) {
        return false;
    }
    if (!chmap) {
        stream->input_chmap = NULL;
    } else {
        const size_t chmaplen = sizeof (*chmap) * spec->channels;
        stream->input_chmap = stream->input_chmap_storage;
        SDL_memcpy(stream->input_chmap, chmap, chmaplen);
    }
    SDL_copyp(&stream->input_spec, spec);
    return true;
}
References SDL_AudioSpec::channels, NULL, SDL_AudioSpecsEqual(), SDL_copyp, SDL_GetResamplerHistoryFrames(), SDL_memcpy, and SDL_ResetAudioQueueHistory().
Referenced by SDL_GetAudioStreamDataAdjustGain().