SDL3: SDL-main/src/main/SDL_main_callbacks.h File Reference
SDL_main_callbacks.h File Reference
Functions
bool SDL_HasMainCallbacks (void)
SDL_AppResult SDL_InitMainCallbacks (int argc, char *argv[], SDL_AppInit_func appinit, SDL_AppIterate_func _appiter, SDL_AppEvent_func _appevent, SDL_AppQuit_func _appquit)
SDL_AppResult SDL_IterateMainCallbacks (bool pump_events)
void SDL_QuitMainCallbacks (SDL_AppResult result)
Function Documentation
SDL_HasMainCallbacks()
bool SDL_HasMainCallbacks (void)
{
    if (SDL_main_iteration_callback) {
        return true;
    }
    return false;
}
References SDL_main_iteration_callback.
Referenced by SDL_OnWindowLiveResizeUpdate().
SDL_InitMainCallbacks()
SDL_AppResult SDL_InitMainCallbacks (int argc, char * argv[], SDL_AppInit_func appinit, SDL_AppIterate_func _appiter, SDL_AppEvent_func _appevent, SDL_AppQuit_func _appquit)
{
    SDL_main_iteration_callback = appiter;
    SDL_main_event_callback = appevent;
    SDL_main_quit_callback = appquit;
    SDL_SetAtomicInt(&apprc, SDL_APP_CONTINUE);
    const SDL_AppResult rc = appinit(&SDL_main_appstate, argc, argv);
    if (SDL_CompareAndSwapAtomicInt(&apprc, SDL_APP_CONTINUE, rc) && (rc == SDL_APP_CONTINUE)) { // bounce if SDL_AppInit already said abort, otherwise...
        // make sure we definitely have events initialized, even if the app didn't do it.
        if (!SDL_InitSubSystem(SDL_INIT_EVENTS)) {
            SDL_SetAtomicInt(&apprc, SDL_APP_FAILURE);
            return SDL_APP_FAILURE;
        }
        if (!SDL_AddEventWatch(SDL_MainCallbackEventWatcher, NULL)) {
            SDL_SetAtomicInt(&apprc, SDL_APP_FAILURE);
            return SDL_APP_FAILURE;
        }
    }
    return (SDL_AppResult)SDL_GetAtomicInt(&apprc);
}
References apprc, NULL, SDL_AddEventWatch(), SDL_APP_CONTINUE, SDL_APP_FAILURE, SDL_CompareAndSwapAtomicInt(), SDL_GetAtomicInt(), SDL_INIT_EVENTS, SDL_InitSubSystem(), SDL_main_appstate, SDL_main_event_callback, SDL_main_iteration_callback, SDL_main_quit_callback, SDL_MainCallbackEventWatcher(), and SDL_SetAtomicInt().
Referenced by SDL_EnterAppMainCallbacks().
SDL_IterateMainCallbacks()
SDL_AppResult SDL_IterateMainCallbacks (bool pump_events)
{
    if (pump_events) {
        SDL_PumpEvents();
    }
    SDL_DispatchMainCallbackEvents();
    SDL_AppResult rc = (SDL_AppResult)SDL_GetAtomicInt(&apprc);
    if (rc == SDL_APP_CONTINUE) {
        rc = SDL_main_iteration_callback(SDL_main_appstate);
        if (!SDL_CompareAndSwapAtomicInt(&apprc, SDL_APP_CONTINUE, rc)) {
            rc = (SDL_AppResult)SDL_GetAtomicInt(&apprc); // something else already set a quit result, keep that.
        }
    }
    return rc;
}
References apprc, SDL_APP_CONTINUE, SDL_CompareAndSwapAtomicInt(), SDL_DispatchMainCallbackEvents(), SDL_GetAtomicInt(), SDL_main_appstate, SDL_main_iteration_callback, and SDL_PumpEvents().
Referenced by EmscriptenInternalMainloop(), GenericIterateMainCallbacks(), and SDL_OnWindowLiveResizeUpdate().
SDL_QuitMainCallbacks()
void SDL_QuitMainCallbacks (SDL_AppResult result)
{
    SDL_RemoveEventWatch(SDL_MainCallbackEventWatcher, NULL);
    SDL_main_quit_callback(SDL_main_appstate, result);
    SDL_main_appstate = NULL;  // just in case.
    // for symmetry, you should explicitly Quit what you Init, but we might come through here uninitialized and SDL_Quit() will clear everything anyhow.
    //SDL_QuitSubSystem(SDL_INIT_EVENTS);
    SDL_Quit();
}
References NULL, SDL_main_appstate, SDL_main_quit_callback, SDL_MainCallbackEventWatcher(), SDL_Quit(), and SDL_RemoveEventWatch().
Referenced by EmscriptenInternalMainloop(), and SDL_EnterAppMainCallbacks().