SDL3: SDL-main/src/filesystem/gdk/SDL_sysfilesystem.cpp File Reference
SDL_sysfilesystem.cpp File Reference
#include "SDL_internal.h"
#include "../SDL_sysfilesystem.h"
#include "../../core/windows/SDL_windows.h"
#include <SDL3/SDL_hints.h>
#include <SDL3/SDL_system.h>
#include <SDL3/SDL_filesystem.h>
#include <XGameSaveFiles.h>
Functions
char * SDL_SYS_GetBasePath (void)
char * SDL_SYS_GetCurrentDirectory (void)
char * SDL_SYS_GetPrefPath (const char *org, const char *app)
char * SDL_SYS_GetUserFolder (SDL_Folder folder)
Function Documentation
SDL_SYS_GetBasePath()
char * SDL_SYS_GetBasePath (void)
{
    /* NOTE: This function is a UTF8 version of the Win32 SDL_GetBasePath()!
     * The GDK actually _recommends_ the 'A' functions over the 'W' functions :o
     */
    DWORD buflen = 128;
    CHAR *path = NULL;
    DWORD len = 0;
    int i;
    while (true) {
        void *ptr = SDL_realloc(path, buflen * sizeof(CHAR));
        if (!ptr) {
            SDL_free(path);
            return NULL;
        }
        path = (CHAR *)ptr;
        len = GetModuleFileNameA(NULL, path, buflen);
        // if it truncated, then len >= buflen - 1
        // if there was enough room (or failure), len < buflen - 1
        if (len < buflen - 1) {
            break;
        }
        // buffer too small? Try again.
        buflen *= 2;
    }
    if (len == 0) {
        SDL_free(path);
        WIN_SetError("Couldn't locate our .exe");
        return NULL;
    }
    for (i = len - 1; i > 0; i--) {
        if (path[i] == '\\') {
            break;
        }
    }
    SDL_assert(i > 0);  // Should have been an absolute path.
    path[i + 1] = '\0'; // chop off filename.
    return path;
}
References NULL, SDL_assert, SDL_free(), SDL_realloc(), and WIN_SetError().
Referenced by SDL_GetBasePath().
SDL_SYS_GetCurrentDirectory()
char * SDL_SYS_GetCurrentDirectory (void)
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
Referenced by SDL_GetCurrentDirectory().
SDL_SYS_GetPrefPath()
char * SDL_SYS_GetPrefPath (const char * org, const char * app)
{
    XUserHandle user = NULL;
    XAsyncBlock block = { 0 };
    char *folderPath;
    HRESULT result;
    const char *csid = SDL_GetHint("SDL_GDK_SERVICE_CONFIGURATION_ID");
    // This should be set before calling SDL_GetPrefPath!
    if (!csid) {
        SDL_LogWarn(SDL_LOG_CATEGORY_SYSTEM, "Set SDL_GDK_SERVICE_CONFIGURATION_ID before calling SDL_GetPrefPath!");
        return SDL_strdup("T:\\");
    }
    if (!SDL_GetGDKDefaultUser(&user)) {
        // Error already set, just return
        return NULL;
    }
    if (FAILED(result = XGameSaveFilesGetFolderWithUiAsync(user, csid, &block))) {
        WIN_SetErrorFromHRESULT("XGameSaveFilesGetFolderWithUiAsync", result);
        return NULL;
    }
    folderPath = (char *)SDL_malloc(MAX_PATH);
    do {
        result = XGameSaveFilesGetFolderWithUiResult(&block, MAX_PATH, folderPath);
    } while (result == E_PENDING);
    if (FAILED(result)) {
        WIN_SetErrorFromHRESULT("XGameSaveFilesGetFolderWithUiResult", result);
        SDL_free(folderPath);
        return NULL;
    }
    /* We aren't using 'app' here because the container rules are a lot more
     * strict than the NTFS rules, so it will most likely be invalid :(
     */
    SDL_strlcat(folderPath, "\\SDLPrefPath\\", MAX_PATH);
    if (CreateDirectoryA(folderPath, NULL) == FALSE) {
        if (GetLastError() != ERROR_ALREADY_EXISTS) {
            WIN_SetError("CreateDirectoryA");
            SDL_free(folderPath);
            return NULL;
        }
    }
    return folderPath;
}
References FAILED, FALSE, NULL, SDL_free(), SDL_GetGDKDefaultUser(), SDL_GetHint(), SDL_LOG_CATEGORY_SYSTEM, SDL_LogWarn(), SDL_malloc(), SDL_strdup(), SDL_strlcat(), WIN_SetError(), and WIN_SetErrorFromHRESULT().
Referenced by SDL_GetPrefPath().
SDL_SYS_GetUserFolder()
char * SDL_SYS_GetUserFolder (SDL_Folder folder)
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
Referenced by SDL_GetUserFolder().