SDL3: SDL-main/src/storage/steam/SDL_steamstorage.c File Reference
SDL_steamstorage.c File Reference
#include "SDL_internal.h"
#include "../SDL_sysstorage.h"
#include "SDL_steamstorage_proc.h"
Data Structures
struct STEAM_RemoteStorage
Macros
#define STEAM_PROC(ret, func, parms)
#define STEAM_PROC(ret, func, parms)
#define STEAM_PROC(ret, func, parms)
Typedefs
typedef struct STEAM_RemoteStorage STEAM_RemoteStorage
Functions
static bool STEAM_CloseStorage (void *userdata)
static bool STEAM_GetStoragePathInfo (void *userdata, const char *path, SDL_PathInfo *info)
static Uint64 STEAM_GetStorageSpaceRemaining (void *userdata)
static bool STEAM_ReadStorageFile (void *userdata, const char *path, void *destination, Uint64 length)
static bool STEAM_StorageReady (void *userdata)
static SDL_Storage * STEAM_User_Create (const char *org, const char *app, SDL_PropertiesID props)
static bool STEAM_WriteStorageFile (void *userdata, const char *path, const void *source, Uint64 length)
Variables
static const SDL_StorageInterface STEAM_user_iface
UserStorageBootStrap STEAM_userbootstrap
Macro Definition Documentation
STEAM_PROC [1/3]
#define STEAM_PROC (ret, func, parms)
Value:
    typedef ret (*steamfntype_##func) parms;
#define STEAM_PROC(ret, func, parms) \
    typedef ret (*steamfntype_##func) parms;
STEAM_PROC [2/3]
#define STEAM_PROC (ret, func, parms)
Value:
        steamfntype_##func func;
#define STEAM_PROC(ret, func, parms) \
    typedef ret (*steamfntype_##func) parms;
STEAM_PROC [3/3]
#define STEAM_PROC (ret, func, parms)
Value:
        steam->func = (steamfntype_##func) SDL_LoadFunction(steam->libsteam_api, #func); \
        if (steam->func == NULL) { \
            SDL_SetError("Could not load function " #func); \
            goto steamfail; \
        }
#define STEAM_PROC(ret, func, parms) \
    typedef ret (*steamfntype_##func) parms;
Typedef Documentation
STEAM_RemoteStorage
typedef struct STEAM_RemoteStorage STEAM_RemoteStorage
Function Documentation
STEAM_CloseStorage()
bool STEAM_CloseStorage (void * userdata) static
{
    bool result = true;
    STEAM_RemoteStorage *steam = (STEAM_RemoteStorage *)userdata;
    void *steamremotestorage = steam->SteamAPI_SteamRemoteStorage_v016();
    if (steamremotestorage == NULL) {
        result = SDL_SetError("SteamRemoteStorage unavailable");
    } else if (!steam->SteamAPI_ISteamRemoteStorage_EndFileWriteBatch(steamremotestorage)) {
        result = SDL_SetError("SteamRemoteStorage()->EndFileWriteBatch() failed");
    }
    SDL_UnloadObject(steam->libsteam_api);
    SDL_free(steam);
    return result;
}
References STEAM_RemoteStorage::libsteam_api, NULL, SDL_free(), SDL_SetError(), SDL_UnloadObject(), STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_EndFileWriteBatch, and STEAM_RemoteStorage::SteamAPI_SteamRemoteStorage_v016.
STEAM_GetStoragePathInfo()
bool STEAM_GetStoragePathInfo (void * userdata, const char * path, SDL_PathInfo * info) static
{
    STEAM_RemoteStorage *steam = (STEAM_RemoteStorage *)userdata;
    void *steamremotestorage = steam->SteamAPI_SteamRemoteStorage_v016();
    if (steamremotestorage == NULL) {
        return SDL_SetError("SteamRemoteStorage unavailable");
    }
    if (info) {
        SDL_zerop(info);
        info->type = SDL_PATHTYPE_FILE;
        info->size = steam->SteamAPI_ISteamRemoteStorage_GetFileSize(steamremotestorage, path);
    }
    return true;
}
References NULL, SDL_PATHTYPE_FILE, SDL_SetError(), SDL_zerop, SDL_PathInfo::size, STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_GetFileSize, STEAM_RemoteStorage::SteamAPI_SteamRemoteStorage_v016, and SDL_PathInfo::type.
STEAM_GetStorageSpaceRemaining()
Uint64 STEAM_GetStorageSpaceRemaining (void * userdata) static
{
    Uint64 total, remaining;
    STEAM_RemoteStorage *steam = (STEAM_RemoteStorage *)userdata;
    void *steamremotestorage = steam->SteamAPI_SteamRemoteStorage_v016();
    if (steamremotestorage == NULL) {
        SDL_SetError("SteamRemoteStorage unavailable");
        return 0;
    }
    if (!steam->SteamAPI_ISteamRemoteStorage_GetQuota(steamremotestorage, &total, &remaining)) {
        SDL_SetError("SteamRemoteStorage()->GetQuota failed");
        return 0;
    }
    return remaining;
}
References NULL, SDL_SetError(), STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_GetQuota, and STEAM_RemoteStorage::SteamAPI_SteamRemoteStorage_v016.
STEAM_ReadStorageFile()
bool STEAM_ReadStorageFile (void * userdata, const char * path, void * destination, Uint64 length) static
{
    bool result = false;
    STEAM_RemoteStorage *steam = (STEAM_RemoteStorage *)userdata;
    void *steamremotestorage = steam->SteamAPI_SteamRemoteStorage_v016();
    if (steamremotestorage == NULL) {
        return SDL_SetError("SteamRemoteStorage unavailable");
    }
    if (length > SDL_MAX_SINT32) {
        return SDL_SetError("SteamRemoteStorage only supports INT32_MAX read size");
    }
    if (steam->SteamAPI_ISteamRemoteStorage_FileRead(steamremotestorage, path, destination, (Sint32) length) == length) {
        result = true;
    } else {
        SDL_SetError("SteamAPI_ISteamRemoteStorage_FileRead() failed");
    }
    return result;
}
References NULL, SDL_MAX_SINT32, SDL_SetError(), STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_FileRead, and STEAM_RemoteStorage::SteamAPI_SteamRemoteStorage_v016.
STEAM_StorageReady()
bool STEAM_StorageReady (void * userdata) static
{
    return true;
}
STEAM_User_Create()
SDL_Storage * STEAM_User_Create (const char * org, const char * app, SDL_PropertiesID props) static
{
    SDL_Storage *result;
    STEAM_RemoteStorage *steam;
    void *steamremotestorage;
    steam = (STEAM_RemoteStorage *)SDL_malloc(sizeof(STEAM_RemoteStorage));
    if (steam == NULL) {
        return NULL;
    }
    steam->libsteam_api = SDL_LoadObject(
#if defined(_WIN64)
        "steam_api64.dll"
#elif defined(_WIN32)
        "steam_api.dll"
#elif defined(__APPLE__)
        "libsteam_api.dylib"
#else
        "libsteam_api.so"
#endif
    );
    if (steam->libsteam_api == NULL) {
        SDL_free(steam);
        return NULL;
    }
    #define STEAM_PROC(ret, func, parms) \
        steam->func = (steamfntype_##func) SDL_LoadFunction(steam->libsteam_api, #func); \
        if (steam->func == NULL) { \
            SDL_SetError("Could not load function " #func); \
            goto steamfail; \
        }
    #include "SDL_steamstorage_proc.h"
    steamremotestorage = steam->SteamAPI_SteamRemoteStorage_v016();
    if (steamremotestorage == NULL) {
        SDL_SetError("SteamRemoteStorage unavailable");
        goto steamfail;
    }
    if (!steam->SteamAPI_ISteamRemoteStorage_IsCloudEnabledForAccount(steamremotestorage)) {
        SDL_SetError("Steam cloud is disabled for this user");
        goto steamfail;
    }
    if (!steam->SteamAPI_ISteamRemoteStorage_IsCloudEnabledForApp(steamremotestorage)) {
        SDL_SetError("Steam cloud is disabled for this application");
        goto steamfail;
    }
    if (!steam->SteamAPI_ISteamRemoteStorage_BeginFileWriteBatch(steamremotestorage)) {
        SDL_SetError("SteamRemoteStorage()->BeginFileWriteBatch failed");
        goto steamfail;
    }
    result = SDL_OpenStorage(&STEAM_user_iface, steam);
    if (result == NULL) {
        goto steamfail;
    }
    return result;
steamfail:
    SDL_UnloadObject(steam->libsteam_api);
    SDL_free(steam);
    return NULL;
}
References STEAM_RemoteStorage::libsteam_api, NULL, SDL_free(), SDL_LoadObject(), SDL_malloc(), SDL_OpenStorage(), SDL_SetError(), SDL_UnloadObject(), STEAM_user_iface, STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_BeginFileWriteBatch, STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_IsCloudEnabledForAccount, STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_IsCloudEnabledForApp, and STEAM_RemoteStorage::SteamAPI_SteamRemoteStorage_v016.
STEAM_WriteStorageFile()
bool STEAM_WriteStorageFile (void * userdata, const char * path, const void * source, Uint64 length) static
{
    bool result = false;
    STEAM_RemoteStorage *steam = (STEAM_RemoteStorage *)userdata;
    void *steamremotestorage = steam->SteamAPI_SteamRemoteStorage_v016();
    if (steamremotestorage == NULL) {
        return SDL_SetError("SteamRemoteStorage unavailable");
    }
    if (length > SDL_MAX_SINT32) {
        return SDL_SetError("SteamRemoteStorage only supports INT32_MAX write size");
    }
    if (steam->SteamAPI_ISteamRemoteStorage_FileWrite(steamremotestorage, path, source, (Sint32) length) == length) {
        result = true;
    } else {
        SDL_SetError("SteamAPI_ISteamRemoteStorage_FileRead() failed");
    }
    return result;
}
References NULL, SDL_MAX_SINT32, SDL_SetError(), STEAM_RemoteStorage::SteamAPI_ISteamRemoteStorage_FileWrite, and STEAM_RemoteStorage::SteamAPI_SteamRemoteStorage_v016.
Variable Documentation
STEAM_user_iface
const SDL_StorageInterface STEAM_user_iface static
Initial value:
= {
    sizeof(SDL_StorageInterface),
    STEAM_CloseStorage,
    STEAM_StorageReady,
    NULL,
    STEAM_GetStoragePathInfo,
    STEAM_ReadStorageFile,
    STEAM_WriteStorageFile,
    NULL,
    NULL,
    NULL,
    NULL,
    STEAM_GetStorageSpaceRemaining
}
{
    sizeof(SDL_StorageInterface),
    STEAM_CloseStorage,
    STEAM_StorageReady,
    NULL,   // enumerate
    STEAM_GetStoragePathInfo,
    STEAM_ReadStorageFile,
    STEAM_WriteStorageFile,
    NULL,   // mkdir
    NULL,   // remove
    NULL,   // rename
    NULL,   // copy
    STEAM_GetStorageSpaceRemaining
};
Referenced by STEAM_User_Create().
STEAM_userbootstrap
UserStorageBootStrap STEAM_userbootstrap
Initial value:
= {
    "steam",
    "SDL Steam user storage driver",
    STEAM_User_Create
}
{
    "steam",
    "SDL Steam user storage driver",
    STEAM_User_Create
};