SDL3: SDL-main/src/locale/unix/SDL_syslocale.c File Reference
SDL_syslocale.c File Reference
#include "SDL_internal.h"
#include "../SDL_syslocale.h"
Functions
static void normalize_locale_str (char *dst, char *str, size_t buflen)
static void normalize_locales (char *dst, char *src, size_t buflen)
bool SDL_SYS_GetPreferredLocales (char *buf, size_t buflen)
Function Documentation
normalize_locale_str()
void normalize_locale_str (char * dst, char * str, size_t buflen) static
{
    char *ptr;
    ptr = SDL_strchr(str, '.'); // chop off encoding if specified.
    if (ptr) {
        *ptr = '\0';
    }
    ptr = SDL_strchr(str, '@'); // chop off extra bits if specified.
    if (ptr) {
        *ptr = '\0';
    }
    // The "C" locale isn't useful for our needs, ignore it if you see it.
    if ((str[0] == 'C') && (str[1] == '\0')) {
        return;
    }
    if (*str) {
        if (*dst) {
            SDL_strlcat(dst, ",", buflen); // SDL has these split by commas
        }
        SDL_strlcat(dst, str, buflen);
    }
}
References SDL_strchr(), and SDL_strlcat().
Referenced by normalize_locales().
normalize_locales()
void normalize_locales (char * dst, char * src, size_t buflen) static
{
    char *ptr;
    // entries are separated by colons
    while ((ptr = SDL_strchr(src, ':')) != NULL) {
        *ptr = '\0';
        normalize_locale_str(dst, src, buflen);
        src = ptr + 1;
    }
    normalize_locale_str(dst, src, buflen);
}
References normalize_locale_str(), NULL, and SDL_strchr().
Referenced by SDL_SYS_GetPreferredLocales().
SDL_SYS_GetPreferredLocales()
bool SDL_SYS_GetPreferredLocales (char * buf, size_t buflen)
{
    // !!! FIXME: should we be using setlocale()? Or some D-Bus thing?
    bool isstack;
    const char *envr;
    char *tmp;
    SDL_assert(buflen > 0);
    tmp = SDL_small_alloc(char, buflen, &isstack);
    if (!tmp) {
        return false;
    }
    *tmp = '\0';
    // LANG is the primary locale (maybe)
    envr = SDL_getenv("LANG");
    if (envr) {
        SDL_strlcpy(tmp, envr, buflen);
    }
    // fallback languages
    envr = SDL_getenv("LANGUAGE");
    if (envr) {
        if (*tmp) {
            SDL_strlcat(tmp, ":", buflen);
        }
        SDL_strlcat(tmp, envr, buflen);
    }
    if (*tmp == '\0') {
        SDL_SetError("LANG environment variable isn't set");
    } else {
        normalize_locales(buf, tmp, buflen);
    }
    SDL_small_free(tmp, isstack);
    return true;
}
References normalize_locales(), SDL_assert, SDL_getenv(), SDL_SetError(), SDL_small_alloc, SDL_small_free, SDL_strlcat(), and SDL_strlcpy().