SDL3: SDL-main/src/video/SDL_sysvideo.h File Reference
SDL_sysvideo.h File Reference
#include "SDL_internal.h"
#include <SDL3/SDL_vulkan.h>
#include "SDL_surface_c.h"
Data Structures
struct SDL_HDROutputProperties
struct SDL_VideoDevice
struct SDL_VideoDisplay
struct SDL_Window
struct VideoBootStrap
Macros
#define SDL_WINDOW_FULLSCREEN_VISIBLE(W)
#define SDL_WINDOW_IS_POPUP(W)
Typedefs
typedef struct SDL_DisplayData SDL_DisplayData
typedef struct SDL_VideoData SDL_VideoData
typedef struct SDL_VideoDevice SDL_VideoDevice
typedef struct SDL_VideoDisplay SDL_VideoDisplay
typedef struct SDL_WindowData SDL_WindowData
typedef struct VideoBootStrap VideoBootStrap
Enumerations
enum DeviceCaps {
VIDEO_DEVICE_CAPS_MODE_SWITCHING_EMULATED = 0x01 , VIDEO_DEVICE_CAPS_HAS_POPUP_WINDOW_SUPPORT = 0x02 , VIDEO_DEVICE_CAPS_SENDS_FULLSCREEN_DIMENSIONS = 0x04 , VIDEO_DEVICE_CAPS_FULLSCREEN_ONLY = 0x08 ,
VIDEO_DEVICE_CAPS_SENDS_DISPLAY_CHANGES = 0x10 , VIDEO_DEVICE_CAPS_DISABLE_MOUSE_WARP_ON_FULLSCREEN_TRANSITIONS = 0x20 , VIDEO_DEVICE_CAPS_SENDS_HDR_CHANGES = 0x40
}
enum SDL_FullscreenOp { SDL_FULLSCREEN_OP_LEAVE = 0 , SDL_FULLSCREEN_OP_ENTER , SDL_FULLSCREEN_OP_UPDATE }
enum SDL_FullscreenResult { SDL_FULLSCREEN_FAILED , SDL_FULLSCREEN_SUCCEEDED , SDL_FULLSCREEN_PENDING }
Functions
SDL_DisplayID SDL_AddBasicVideoDisplay (const SDL_DisplayMode *desktop_mode)
bool SDL_AddFullscreenDisplayMode (SDL_VideoDisplay *display, const SDL_DisplayMode *mode)
SDL_DisplayID SDL_AddVideoDisplay (const SDL_VideoDisplay *display, bool send_event)
void SDL_CheckWindowPixelSizeChanged (SDL_Window *window)
void SDL_DelVideoDisplay (SDL_DisplayID display, bool send_event)
SDL_DisplayData * SDL_GetDisplayDriverData (SDL_DisplayID display)
SDL_DisplayData * SDL_GetDisplayDriverDataForWindow (SDL_Window *window)
SDL_DisplayID SDL_GetDisplayForWindowPosition (SDL_Window *window)
int SDL_GetDisplayIndex (SDL_DisplayID displayID)
int SDL_GetMessageBoxCount (void)
bool SDL_GetTextInputAutocorrect (SDL_PropertiesID props)
SDL_Capitalization SDL_GetTextInputCapitalization (SDL_PropertiesID props)
bool SDL_GetTextInputMultiline (SDL_PropertiesID props)
SDL_TextInputType SDL_GetTextInputType (SDL_PropertiesID props)
SDL_Window * SDL_GetToplevelForKeyboardFocus (void)
SDL_VideoDevice * SDL_GetVideoDevice (void)
SDL_VideoDisplay * SDL_GetVideoDisplay (SDL_DisplayID display)
SDL_VideoDisplay * SDL_GetVideoDisplayForFullscreenWindow (SDL_Window *window)
SDL_VideoDisplay * SDL_GetVideoDisplayForWindow (SDL_Window *window)
void SDL_GL_DeduceMaxSupportedESProfile (int *major, int *minor)
void SDL_GlobalToRelativeForWindow (SDL_Window *window, int abs_x, int abs_y, int *rel_x, int *rel_y)
bool SDL_HasWindows (void)
void SDL_OnDisplayAdded (SDL_VideoDisplay *display)
void SDL_OnDisplayMoved (SDL_VideoDisplay *display)
bool SDL_OnVideoThread (void)
void SDL_OnWindowDisplayChanged (SDL_Window *window)
void SDL_OnWindowEnter (SDL_Window *window)
void SDL_OnWindowFocusGained (SDL_Window *window)
void SDL_OnWindowFocusLost (SDL_Window *window)
void SDL_OnWindowHidden (SDL_Window *window)
void SDL_OnWindowLeave (SDL_Window *window)
void SDL_OnWindowLiveResizeUpdate (SDL_Window *window)
void SDL_OnWindowMaximized (SDL_Window *window)
void SDL_OnWindowMinimized (SDL_Window *window)
void SDL_OnWindowMoved (SDL_Window *window)
void SDL_OnWindowPixelSizeChanged (SDL_Window *window)
void SDL_OnWindowResized (SDL_Window *window)
void SDL_OnWindowRestored (SDL_Window *window)
void SDL_OnWindowShown (SDL_Window *window)
bool SDL_RecreateWindow (SDL_Window *window, SDL_WindowFlags flags)
void SDL_RelativeToGlobalForWindow (SDL_Window *window, int rel_x, int rel_y, int *abs_x, int *abs_y)
void SDL_ResetFullscreenDisplayModes (SDL_VideoDisplay *display)
void SDL_SetCurrentDisplayMode (SDL_VideoDisplay *display, const SDL_DisplayMode *mode)
void SDL_SetDesktopDisplayMode (SDL_VideoDisplay *display, const SDL_DisplayMode *mode)
void SDL_SetDisplayContentScale (SDL_VideoDisplay *display, float scale)
void SDL_SetDisplayHDRProperties (SDL_VideoDisplay *display, const SDL_HDROutputProperties *HDR)
bool SDL_SetDisplayModeForDisplay (SDL_VideoDisplay *display, SDL_DisplayMode *mode)
void SDL_SetSystemTheme (SDL_SystemTheme theme)
void SDL_SetWindowHDRProperties (SDL_Window *window, const SDL_HDROutputProperties *HDR, bool send_event)
void SDL_SetWindowSafeAreaInsets (SDL_Window *window, int left, int right, int top, int bottom)
bool SDL_ShouldAllowTopmost (void)
bool SDL_ShouldFocusPopup (SDL_Window *window)
bool SDL_ShouldRelinquishPopupFocus (SDL_Window *window, SDL_Window **new_focus)
void SDL_ToggleDragAndDropSupport (void)
bool SDL_UninitializedVideo (void)
void SDL_UpdateDesktopBounds (void)
bool SDL_UpdateFullscreenMode (SDL_Window *window, SDL_FullscreenOp fullscreen, bool commit)
void SDL_UpdateWindowGrab (SDL_Window *window)
Variables
VideoBootStrap Android_bootstrap
VideoBootStrap COCOA_bootstrap
VideoBootStrap DUMMY_bootstrap
VideoBootStrap DUMMY_evdev_bootstrap
VideoBootStrap Emscripten_bootstrap
VideoBootStrap HAIKU_bootstrap
VideoBootStrap KMSDRM_bootstrap
VideoBootStrap N3DS_bootstrap
VideoBootStrap NGAGE_bootstrap
VideoBootStrap OFFSCREEN_bootstrap
VideoBootStrap OPENVR_bootstrap
VideoBootStrap PRIVATE_bootstrap
VideoBootStrap PS2_bootstrap
VideoBootStrap PSP_bootstrap
VideoBootStrap QNX_bootstrap
VideoBootStrap RISCOS_bootstrap
VideoBootStrap RPI_bootstrap
VideoBootStrap UIKIT_bootstrap
VideoBootStrap VITA_bootstrap
VideoBootStrap VIVANTE_bootstrap
VideoBootStrap Wayland_bootstrap
VideoBootStrap Wayland_preferred_bootstrap
VideoBootStrap WINDOWS_bootstrap
VideoBootStrap X11_bootstrap
Macro Definition Documentation
SDL_WINDOW_FULLSCREEN_VISIBLE
#define SDL_WINDOW_FULLSCREEN_VISIBLE (W)
Value:
    ((((W)->flags & SDL_WINDOW_FULLSCREEN) != 0) &&   \
     (((W)->flags & SDL_WINDOW_HIDDEN) == 0) && \
     (((W)->flags & SDL_WINDOW_MINIMIZED) == 0))
#define SDL_WINDOW_FULLSCREEN_VISIBLE(W)        \
    ((((W)->flags & SDL_WINDOW_FULLSCREEN) != 0) &&   \
     (((W)->flags & SDL_WINDOW_HIDDEN) == 0) && \
     (((W)->flags & SDL_WINDOW_MINIMIZED) == 0))
Referenced by SDL_OnWindowDisplayChanged(), and SDL_SetWindowFullscreenMode().
SDL_WINDOW_IS_POPUP
#define SDL_WINDOW_IS_POPUP (W)
Value:
    (((W)->flags & (SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU)) != 0)
#define SDL_WINDOW_IS_POPUP(W) \
    (((W)->flags & (SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU)) != 0)
Referenced by ApplyWindowFlags(), SDL_GlobalToRelativeForWindow(), SDL_RelativeToGlobalForWindow(), SDL_ShouldFocusPopup(), and SDL_ShouldRelinquishPopupFocus().
Typedef Documentation
SDL_DisplayData
typedef struct SDL_DisplayData SDL_DisplayData
SDL_VideoData
typedef struct SDL_VideoData SDL_VideoData
SDL_VideoDevice
typedef struct SDL_VideoDevice SDL_VideoDevice
SDL_VideoDisplay
typedef struct SDL_VideoDisplay SDL_VideoDisplay
SDL_WindowData
typedef struct SDL_WindowData SDL_WindowData
VideoBootStrap
typedef struct VideoBootStrap VideoBootStrap
Enumeration Type Documentation
DeviceCaps
enum DeviceCaps
Enumerator
VIDEO_DEVICE_CAPS_MODE_SWITCHING_EMULATED
VIDEO_DEVICE_CAPS_HAS_POPUP_WINDOW_SUPPORT
VIDEO_DEVICE_CAPS_SENDS_FULLSCREEN_DIMENSIONS
VIDEO_DEVICE_CAPS_FULLSCREEN_ONLY
VIDEO_DEVICE_CAPS_SENDS_DISPLAY_CHANGES
VIDEO_DEVICE_CAPS_DISABLE_MOUSE_WARP_ON_FULLSCREEN_TRANSITIONS
VIDEO_DEVICE_CAPS_SENDS_HDR_CHANGES
{
    VIDEO_DEVICE_CAPS_MODE_SWITCHING_EMULATED = 0x01,
    VIDEO_DEVICE_CAPS_HAS_POPUP_WINDOW_SUPPORT = 0x02,
    VIDEO_DEVICE_CAPS_SENDS_FULLSCREEN_DIMENSIONS = 0x04,
    VIDEO_DEVICE_CAPS_FULLSCREEN_ONLY = 0x08,
    VIDEO_DEVICE_CAPS_SENDS_DISPLAY_CHANGES = 0x10,
    VIDEO_DEVICE_CAPS_DISABLE_MOUSE_WARP_ON_FULLSCREEN_TRANSITIONS = 0x20,
    VIDEO_DEVICE_CAPS_SENDS_HDR_CHANGES = 0x40
} DeviceCaps;
SDL_FullscreenOp
enum SDL_FullscreenOp
Enumerator
SDL_FULLSCREEN_OP_LEAVE
SDL_FULLSCREEN_OP_ENTER
SDL_FULLSCREEN_OP_UPDATE
{
    SDL_FULLSCREEN_OP_LEAVE = 0,
    SDL_FULLSCREEN_OP_ENTER,
    SDL_FULLSCREEN_OP_UPDATE
} SDL_FullscreenOp;
SDL_FullscreenResult
enum SDL_FullscreenResult
Enumerator
SDL_FULLSCREEN_FAILED
SDL_FULLSCREEN_SUCCEEDED
SDL_FULLSCREEN_PENDING
{
    SDL_FULLSCREEN_FAILED,
    SDL_FULLSCREEN_SUCCEEDED,
    SDL_FULLSCREEN_PENDING
} SDL_FullscreenResult;
Function Documentation
SDL_AddBasicVideoDisplay()
SDL_DisplayID SDL_AddBasicVideoDisplay (const SDL_DisplayMode * desktop_mode) extern
{
    SDL_VideoDisplay display;
    SDL_zero(display);
    if (desktop_mode) {
        SDL_memcpy(&display.desktop_mode, desktop_mode, sizeof(display.desktop_mode));
    }
    return SDL_AddVideoDisplay(&display, false);
}
References SDL_AddVideoDisplay(), SDL_memcpy, and SDL_zero.
SDL_AddFullscreenDisplayMode()
bool SDL_AddFullscreenDisplayMode (SDL_VideoDisplay * display, const SDL_DisplayMode * mode) extern
{
    SDL_DisplayMode *modes;
    SDL_DisplayMode new_mode;
    int i, nmodes;
    // Finalize the mode for the display
    SDL_memcpy(&new_mode, mode, sizeof(new_mode));
    new_mode.displayID = display->id;
    SDL_FinalizeDisplayMode(&new_mode);
    // Make sure we don't already have the mode in the list
    modes = display->fullscreen_modes;
    nmodes = display->num_fullscreen_modes;
    for (i = 0; i < nmodes; ++i) {
        if (cmpmodes(&new_mode, &modes[i]) == 0) {
            return false;
        }
    }
    // Go ahead and add the new mode
    if (nmodes == display->max_fullscreen_modes) {
        modes = (SDL_DisplayMode *)SDL_malloc((display->max_fullscreen_modes + 32) * sizeof(*modes));
        if (!modes) {
            return false;
        }
        if (display->fullscreen_modes) {
            // Copy the list and update the current mode pointer, if necessary.
            SDL_memcpy(modes, display->fullscreen_modes, nmodes * sizeof(*modes));
            for (i = 0; i < nmodes; ++i) {
                if (display->current_mode == &display->fullscreen_modes[i]) {
                    display->current_mode = &modes[i];
                }
            }
            SDL_free(display->fullscreen_modes);
        }
        display->fullscreen_modes = modes;
        display->max_fullscreen_modes += 32;
    }
    SDL_memcpy(&modes[display->num_fullscreen_modes++], &new_mode, sizeof(new_mode));
    // Re-sort video modes
    SDL_qsort(display->fullscreen_modes, display->num_fullscreen_modes,
              sizeof(SDL_DisplayMode), cmpmodes);
    return true;
}
References cmpmodes(), SDL_DisplayMode::displayID, SDL_FinalizeDisplayMode(), SDL_free(), SDL_malloc(), SDL_memcpy, and SDL_qsort().
SDL_AddVideoDisplay()
SDL_DisplayID SDL_AddVideoDisplay (const SDL_VideoDisplay * display, bool send_event) extern
{
    SDL_VideoDisplay **displays, *new_display;
    SDL_DisplayID id;
    SDL_PropertiesID props;
    int i;
    new_display = (SDL_VideoDisplay *)SDL_malloc(sizeof(*new_display));
    if (!new_display) {
        return 0;
    }
    displays = (SDL_VideoDisplay **)SDL_realloc(_this->displays, (_this->num_displays + 1) * sizeof(*displays));
    if (!displays) {
        SDL_free(new_display);
        return 0;
    }
    _this->displays = displays;
    _this->displays[_this->num_displays++] = new_display;
    id = SDL_GetNextObjectID();
    SDL_copyp(new_display, display);
    new_display->id = id;
    new_display->device = _this;
    if (display->name) {
        new_display->name = SDL_strdup(display->name);
    } else {
        char name[32];
        SDL_itoa(id, name, 10);
        new_display->name = SDL_strdup(name);
    }
    if (new_display->content_scale == 0.0f) {
        new_display->content_scale = 1.0f;
    }
    new_display->desktop_mode.displayID = id;
    new_display->current_mode = &new_display->desktop_mode;
    SDL_FinalizeDisplayMode(&new_display->desktop_mode);
    for (i = 0; i < new_display->num_fullscreen_modes; ++i) {
        new_display->fullscreen_modes[i].displayID = id;
    }
    new_display->HDR.HDR_headroom = SDL_max(display->HDR.HDR_headroom, 1.0f);
    new_display->HDR.SDR_white_level = SDL_max(display->HDR.SDR_white_level, 1.0f);
    props = SDL_GetDisplayProperties(id);
    SDL_SetBooleanProperty(props, SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN, new_display->HDR.HDR_headroom > 1.0f);
    SDL_UpdateDesktopBounds();
    if (send_event) {
        SDL_SendDisplayEvent(new_display, SDL_EVENT_DISPLAY_ADDED, 0, 0);
    }
    return id;
}
References _this, SDL_VideoDisplay::content_scale, SDL_VideoDisplay::current_mode, SDL_VideoDisplay::desktop_mode, SDL_VideoDisplay::device, SDL_DisplayMode::displayID, SDL_VideoDisplay::fullscreen_modes, SDL_VideoDisplay::HDR, SDL_HDROutputProperties::HDR_headroom, SDL_VideoDisplay::id, SDL_VideoDisplay::name, SDL_VideoDisplay::num_fullscreen_modes, SDL_copyp, SDL_EVENT_DISPLAY_ADDED, SDL_FinalizeDisplayMode(), SDL_free(), SDL_GetDisplayProperties(), SDL_GetNextObjectID(), SDL_itoa(), SDL_malloc(), SDL_max, SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN, SDL_realloc(), SDL_SendDisplayEvent(), SDL_SetBooleanProperty(), SDL_strdup(), SDL_UpdateDesktopBounds(), and SDL_HDROutputProperties::SDR_white_level.
Referenced by SDL_AddBasicVideoDisplay(), and videoInit().
SDL_CheckWindowPixelSizeChanged()
void SDL_CheckWindowPixelSizeChanged (SDL_Window * window) extern
{
    int pixel_w = 0, pixel_h = 0;
    SDL_GetWindowSizeInPixels(window, &pixel_w, &pixel_h);
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, pixel_w, pixel_h);
    SDL_CheckWindowDisplayScaleChanged(window);
}
References SDL_CheckWindowDisplayScaleChanged(), SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, SDL_GetWindowSizeInPixels(), and SDL_SendWindowEvent().
Referenced by SDL_CreateWindowWithProperties(), SDL_OnWindowDisplayChanged(), SDL_OnWindowResized(), and SDL_SendWindowEvent().
SDL_DelVideoDisplay()
void SDL_DelVideoDisplay (SDL_DisplayID display, bool send_event) extern
{
    SDL_VideoDisplay *display;
    int display_index = SDL_GetDisplayIndex(displayID);
    if (display_index < 0) {
        return;
    }
    display = _this->displays[display_index];
    if (send_event) {
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_REMOVED, 0, 0);
    }
    SDL_DestroyProperties(display->props);
    SDL_free(display->name);
    SDL_ResetFullscreenDisplayModes(display);
    SDL_free(display->desktop_mode.internal);
    display->desktop_mode.internal = NULL;
    SDL_free(display->internal);
    display->internal = NULL;
    SDL_free(display);
    if (display_index < (_this->num_displays - 1)) {
        SDL_memmove(&_this->displays[display_index], &_this->displays[display_index + 1], (_this->num_displays - display_index - 1) * sizeof(_this->displays[display_index]));
    }
    --_this->num_displays;
    SDL_UpdateDesktopBounds();
}
References _this, NULL, SDL_DestroyProperties(), SDL_EVENT_DISPLAY_REMOVED, SDL_free(), SDL_GetDisplayIndex(), SDL_memmove, SDL_ResetFullscreenDisplayModes(), SDL_SendDisplayEvent(), and SDL_UpdateDesktopBounds().
Referenced by SDL_VideoQuit().
SDL_GetDisplayDriverData()
SDL_DisplayData * SDL_GetDisplayDriverData (SDL_DisplayID display) extern
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    return display->internal;
}
References CHECK_DISPLAY_MAGIC, NULL, and SDL_GetVideoDisplay().
Referenced by SDL_GetDisplayDriverDataForWindow().
SDL_GetDisplayDriverDataForWindow()
SDL_DisplayData * SDL_GetDisplayDriverDataForWindow (SDL_Window * window) extern
{
    return SDL_GetDisplayDriverData(SDL_GetDisplayForWindow(window));
}
References SDL_GetDisplayDriverData(), and SDL_GetDisplayForWindow().
SDL_GetDisplayForWindowPosition()
SDL_DisplayID SDL_GetDisplayForWindowPosition (SDL_Window * window) extern
{
    int x, y;
    SDL_DisplayID displayID = 0;
    CHECK_WINDOW_MAGIC(window, 0);
    if (_this->GetDisplayForWindow) {
        displayID = _this->GetDisplayForWindow(_this, window);
    }
    /* A backend implementation may fail to get a display for the window
     * (for example if the window is off-screen), but other code may expect it
     * to succeed in that situation, so we fall back to a generic position-
     * based implementation in that case. */
    SDL_RelativeToGlobalForWindow(window, window->x, window->y, &x, &y);
    if (!displayID) {
        /* Fullscreen windows may be larger than the display if they were moved between differently sized
         * displays and the new position was received before the new size or vice versa. Using the center
         * of the window rect in this case can report the wrong display, so use the origin.
         */
        if (window->flags & SDL_WINDOW_FULLSCREEN) {
            displayID = GetDisplayForRect(x, y, 1, 1);
        } else {
            displayID = GetDisplayForRect(x, y, window->w, window->h);
        }
    }
    if (!displayID) {
        // Use the primary display for a window if we can't find it anywhere else
        displayID = SDL_GetPrimaryDisplay();
    }
    return displayID;
}
References _this, CHECK_WINDOW_MAGIC, GetDisplayForRect(), SDL_GetPrimaryDisplay(), SDL_RelativeToGlobalForWindow(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_CheckWindowDisplayChanged(), SDL_CheckWindowDisplayScaleChanged(), SDL_GetDisplayForWindow(), and SDL_OnWindowDisplayChanged().
SDL_GetDisplayIndex()
int SDL_GetDisplayIndex (SDL_DisplayID displayID) extern
{
    int display_index;
    if (!_this) {
        SDL_UninitializedVideo();
        return -1;
    }
    for (display_index = 0; display_index < _this->num_displays; ++display_index) {
        if (displayID == _this->displays[display_index]->id) {
            return display_index;
        }
    }
    SDL_SetError("Invalid display");
    return -1;
}
References _this, SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_CheckWindowDisplayChanged(), SDL_CreateWindowWithProperties(), SDL_DelVideoDisplay(), SDL_GetDisplayBounds(), SDL_GetVideoDisplay(), and SDL_SetWindowPosition().
SDL_GetMessageBoxCount()
int SDL_GetMessageBoxCount (void) extern
{
    return SDL_GetAtomicInt(&SDL_messagebox_count);
}
References SDL_GetAtomicInt(), and SDL_messagebox_count.
Referenced by SDL_UpdateMouseCapture().
SDL_GetTextInputAutocorrect()
bool SDL_GetTextInputAutocorrect (SDL_PropertiesID props) extern
{
    return SDL_GetBooleanProperty(props, SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN, true);
}
References SDL_GetBooleanProperty(), and SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN.
SDL_GetTextInputCapitalization()
SDL_Capitalization SDL_GetTextInputCapitalization (SDL_PropertiesID props) extern
{
    if (SDL_HasProperty(props, SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER)) {
        return (SDL_Capitalization)SDL_GetNumberProperty(props, SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER, SDL_CAPITALIZE_NONE);
    }
    switch (SDL_GetTextInputType(props)) {
    case SDL_TEXTINPUT_TYPE_TEXT:
        return SDL_CAPITALIZE_SENTENCES;
    case SDL_TEXTINPUT_TYPE_TEXT_NAME:
        return SDL_CAPITALIZE_WORDS;
    default:
        return SDL_CAPITALIZE_NONE;
    }
}
References SDL_CAPITALIZE_NONE, SDL_CAPITALIZE_SENTENCES, SDL_CAPITALIZE_WORDS, SDL_GetNumberProperty(), SDL_GetTextInputType(), SDL_HasProperty(), SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER, SDL_TEXTINPUT_TYPE_TEXT, and SDL_TEXTINPUT_TYPE_TEXT_NAME.
SDL_GetTextInputMultiline()
bool SDL_GetTextInputMultiline (SDL_PropertiesID props) extern
{
    if (SDL_HasProperty(props, SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN)) {
        return SDL_GetBooleanProperty(props, SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN, false);
    }
    if (SDL_GetHintBoolean(SDL_HINT_RETURN_KEY_HIDES_IME, false)) {
        return false;
    } else {
        return true;
    }
}
References SDL_GetBooleanProperty(), SDL_GetHintBoolean(), SDL_HasProperty(), SDL_HINT_RETURN_KEY_HIDES_IME, and SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN.
SDL_GetTextInputType()
SDL_TextInputType SDL_GetTextInputType (SDL_PropertiesID props) extern
{
    return (SDL_TextInputType)SDL_GetNumberProperty(props, SDL_PROP_TEXTINPUT_TYPE_NUMBER, SDL_TEXTINPUT_TYPE_TEXT);
}
References SDL_GetNumberProperty(), SDL_PROP_TEXTINPUT_TYPE_NUMBER, and SDL_TEXTINPUT_TYPE_TEXT.
Referenced by SDL_GetTextInputCapitalization().
SDL_GetToplevelForKeyboardFocus()
SDL_Window * SDL_GetToplevelForKeyboardFocus (void) extern
{
    SDL_Window *focus = SDL_GetKeyboardFocus();
    if (focus) {
        // Get the toplevel parent window.
        while (focus->parent) {
            focus = focus->parent;
        }
    }
    return focus;
}
References SDL_Window::parent, and SDL_GetKeyboardFocus().
Referenced by SDL_PromptAssertion().
SDL_GetVideoDevice()
SDL_VideoDevice * SDL_GetVideoDevice (void) extern
{
    return _this;
}
References _this.
Referenced by GDK_RegisterChangeNotifications(), SDL_CancelClipboardData(), SDL_GetClipboardData(), SDL_GetClipboardMimeTypes(), SDL_GetClipboardText(), SDL_GetPrimarySelectionText(), SDL_GetTouch(), SDL_GPUSelectBackend(), SDL_HasClipboardData(), SDL_HasClipboardText(), SDL_HasPrimarySelectionText(), SDL_PumpEventsInternal(), SDL_SaveClipboardMimeTypes(), SDL_SendWakeupEvent(), SDL_SendWindowEvent(), SDL_SetClipboardData(), SDL_SetClipboardText(), SDL_SetKeyboardFocus(), SDL_SetPrimarySelectionText(), and SDL_WaitEventTimeoutNS().
SDL_GetVideoDisplay()
SDL_VideoDisplay * SDL_GetVideoDisplay (SDL_DisplayID display) extern
{
    int display_index;
    display_index = SDL_GetDisplayIndex(displayID);
    if (display_index < 0) {
        return NULL;
    }
    return _this->displays[display_index];
}
References _this, NULL, and SDL_GetDisplayIndex().
Referenced by SDL_GetClosestFullscreenDisplayMode(), SDL_GetCurrentDisplayMode(), SDL_GetCurrentDisplayOrientation(), SDL_GetDesktopDisplayMode(), SDL_GetDisplayBounds(), SDL_GetDisplayContentScale(), SDL_GetDisplayDriverData(), SDL_GetDisplayName(), SDL_GetDisplayProperties(), SDL_GetDisplayUsableBounds(), SDL_GetFullscreenDisplayModes(), SDL_GetFullscreenModeMatch(), SDL_GetNaturalDisplayOrientation(), SDL_GetVideoDisplayForFullscreenWindow(), and SDL_GetVideoDisplayForWindow().
SDL_GetVideoDisplayForFullscreenWindow()
SDL_VideoDisplay * SDL_GetVideoDisplayForFullscreenWindow (SDL_Window * window) extern
{
    SDL_DisplayID displayID = 0;
    CHECK_WINDOW_MAGIC(window, 0);
    // An explicit fullscreen display overrides all
    if (window->current_fullscreen_mode.displayID) {
        displayID = window->current_fullscreen_mode.displayID;
    }
    /* This is used to handle the very common pattern of SDL_SetWindowPosition()
     * followed immediately by SDL_SetWindowFullscreen() to make the window fullscreen
     * desktop on a specific display. If the backend doesn't support changing the
     * window position, or an async window manager hasn't yet actually moved the window,
     * the current position won't be updated at the time of the fullscreen call.
     */
    if (!displayID) {
        // Use the pending position and dimensions, if available, otherwise, use the current.
        const int x = window->last_position_pending ? window->pending.x : window->x;
        const int y = window->last_position_pending ? window->pending.y : window->y;
        const int w = window->last_size_pending ? window->pending.w : window->w;
        const int h = window->last_size_pending ? window->pending.h : window->h;
        displayID = GetDisplayForRect(x, y, w, h);
    }
    if (!displayID) {
        // Use the primary display for a window if we can't find it anywhere else
        displayID = SDL_GetPrimaryDisplay();
    }
    return SDL_GetVideoDisplay(displayID);
}
References CHECK_WINDOW_MAGIC, GetDisplayForRect(), SDL_GetPrimaryDisplay(), and SDL_GetVideoDisplay().
Referenced by SDL_GetDisplayForWindow(), and SDL_UpdateFullscreenMode().
SDL_GetVideoDisplayForWindow()
SDL_VideoDisplay * SDL_GetVideoDisplayForWindow (SDL_Window * window) extern
{
    return SDL_GetVideoDisplay(SDL_GetDisplayForWindow(window));
}
References SDL_GetDisplayForWindow(), and SDL_GetVideoDisplay().
Referenced by SDL_CreateWindowWithProperties().
SDL_GL_DeduceMaxSupportedESProfile()
void SDL_GL_DeduceMaxSupportedESProfile (int * major, int * minor) extern
{
// THIS REQUIRES AN EXISTING GL CONTEXT THAT HAS BEEN MADE CURRENT.
// Please refer to https://bugzilla.libsdl.org/show_bug.cgi?id=3725 for discussion.
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    /* XXX This is fragile; it will break in the event of release of
     * new versions of OpenGL ES.
     */
    if (SDL_GL_ExtensionSupported("GL_ARB_ES3_2_compatibility")) {
        *major = 3;
        *minor = 2;
    } else if (SDL_GL_ExtensionSupported("GL_ARB_ES3_1_compatibility")) {
        *major = 3;
        *minor = 1;
    } else if (SDL_GL_ExtensionSupported("GL_ARB_ES3_compatibility")) {
        *major = 3;
        *minor = 0;
    } else {
        *major = 2;
        *minor = 0;
    }
#endif
}
References SDL_GL_ExtensionSupported().
SDL_GlobalToRelativeForWindow()
void SDL_GlobalToRelativeForWindow (SDL_Window * window, int abs_x, int abs_y, int * rel_x, int * rel_y) extern
{
    SDL_Window *w;
    if (SDL_WINDOW_IS_POPUP(window)) {
        // Convert absolute window coordinates to relative for a popup
        for (w = window->parent; w; w = w->parent) {
            abs_x -= w->x;
            abs_y -= w->y;
            if (!SDL_WINDOW_IS_POPUP(w)) {
                break;
            }
        }
    }
    if (rel_x) {
        *rel_x = abs_x;
    }
    if (rel_y) {
        *rel_y = abs_y;
    }
}
References SDL_Window::parent, SDL_WINDOW_IS_POPUP, SDL_Window::x, and SDL_Window::y.
SDL_HasWindows()
bool SDL_HasWindows (void) extern
{
    return _this && _this->windows;
}
References _this.
Referenced by SDL_PrivateJoystickShouldIgnoreEvent().
SDL_OnDisplayAdded()
void SDL_OnDisplayAdded (SDL_VideoDisplay * display) extern
{
    SDL_Window *window;
    // See if any windows have changed to the new display
    for (window = _this->windows; window; window = window->next) {
        SDL_CheckWindowDisplayChanged(window);
    }
}
References _this, and SDL_CheckWindowDisplayChanged().
Referenced by SDL_SendDisplayEvent().
SDL_OnDisplayMoved()
void SDL_OnDisplayMoved (SDL_VideoDisplay * display) extern
{
    SDL_UpdateDesktopBounds();
}
References SDL_UpdateDesktopBounds().
Referenced by SDL_SendDisplayEvent().
SDL_OnVideoThread()
bool SDL_OnVideoThread (void) extern
{
    return (_this && SDL_GetCurrentThreadID() == _this->thread);
}
References _this, and SDL_GetCurrentThreadID().
Referenced by SDL_CaptureMouse().
SDL_OnWindowDisplayChanged()
void SDL_OnWindowDisplayChanged (SDL_Window * window) extern
{
    // Don't run this if a fullscreen change was made in an event watcher callback in response to a display changed event.
    if (window->update_fullscreen_on_display_changed && (window->flags & SDL_WINDOW_FULLSCREEN)) {
        const bool auto_mode_switch = SDL_GetHintBoolean(SDL_HINT_VIDEO_MATCH_EXCLUSIVE_MODE_ON_MOVE, true);
        if (auto_mode_switch && (window->requested_fullscreen_mode.w != 0 || window->requested_fullscreen_mode.h != 0)) {
            SDL_DisplayID displayID = SDL_GetDisplayForWindowPosition(window);
            bool include_high_density_modes = false;
            if (window->requested_fullscreen_mode.pixel_density > 1.0f) {
                include_high_density_modes = true;
            }
            const bool found_match = SDL_GetClosestFullscreenDisplayMode(displayID, window->requested_fullscreen_mode.w, window->requested_fullscreen_mode.h,
                                                                         window->requested_fullscreen_mode.refresh_rate, include_high_density_modes, &window->current_fullscreen_mode);
            // If a mode without matching dimensions was not found, just go to fullscreen desktop.
            if (!found_match ||
                window->requested_fullscreen_mode.w != window->current_fullscreen_mode.w ||
                window->requested_fullscreen_mode.h != window->current_fullscreen_mode.h) {
                SDL_zero(window->current_fullscreen_mode);
            }
        } else {
            SDL_zero(window->current_fullscreen_mode);
        }
        if (SDL_WINDOW_FULLSCREEN_VISIBLE(window)) {
            SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_UPDATE, true);
        }
    }
    SDL_CheckWindowPixelSizeChanged(window);
}
References SDL_CheckWindowPixelSizeChanged(), SDL_FULLSCREEN_OP_UPDATE, SDL_GetClosestFullscreenDisplayMode(), SDL_GetDisplayForWindowPosition(), SDL_GetHintBoolean(), SDL_HINT_VIDEO_MATCH_EXCLUSIVE_MODE_ON_MOVE, SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_FULLSCREEN_VISIBLE, and SDL_zero.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowEnter()
void SDL_OnWindowEnter (SDL_Window * window) extern
{
    if (_this->OnWindowEnter) {
        _this->OnWindowEnter(_this, window);
    }
}
References _this.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowFocusGained()
void SDL_OnWindowFocusGained (SDL_Window * window) extern
{
    SDL_Mouse *mouse = SDL_GetMouse();
    if (mouse && mouse->relative_mode) {
        SDL_SetMouseFocus(window);
    }
    SDL_UpdateWindowGrab(window);
}
References SDL_Mouse::relative_mode, SDL_GetMouse(), SDL_SetMouseFocus(), and SDL_UpdateWindowGrab().
Referenced by SDL_SendWindowEvent().
SDL_OnWindowFocusLost()
void SDL_OnWindowFocusLost (SDL_Window * window) extern
{
    SDL_UpdateWindowGrab(window);
    if (SDL_ShouldMinimizeOnFocusLoss(window)) {
        SDL_MinimizeWindow(window);
    }
}
References SDL_MinimizeWindow(), SDL_ShouldMinimizeOnFocusLoss(), and SDL_UpdateWindowGrab().
Referenced by SDL_SendWindowEvent().
SDL_OnWindowHidden()
void SDL_OnWindowHidden (SDL_Window * window) extern
{
    /* Store the maximized and fullscreen flags for restoration later, in case
     * this was initiated by the window manager due to the window being unmapped
     * when minimized.
     */
    window->pending_flags |= (window->flags & (SDL_WINDOW_FULLSCREEN | SDL_WINDOW_MAXIMIZED));
    // The window is already hidden at this point, so just change the mode back if necessary.
    SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, false);
}
References SDL_FULLSCREEN_OP_LEAVE, SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, and SDL_WINDOW_MAXIMIZED.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowLeave()
void SDL_OnWindowLeave (SDL_Window * window) extern
{
}
Referenced by SDL_SendWindowEvent().
SDL_OnWindowLiveResizeUpdate()
void SDL_OnWindowLiveResizeUpdate (SDL_Window * window) extern
{
    if (SDL_HasMainCallbacks()) {
        SDL_IterateMainCallbacks(false);
    } else {
        // Send an expose event so the application can redraw
        SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_EXPOSED, 1, 0);
    }
    SDL_PumpEventMaintenance();
}
References SDL_EVENT_WINDOW_EXPOSED, SDL_HasMainCallbacks(), SDL_IterateMainCallbacks(), SDL_PumpEventMaintenance(), and SDL_SendWindowEvent().
SDL_OnWindowMaximized()
void SDL_OnWindowMaximized (SDL_Window * window) extern
{
}
Referenced by SDL_SendWindowEvent().
SDL_OnWindowMinimized()
void SDL_OnWindowMinimized (SDL_Window * window) extern
{
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, false);
    }
}
References SDL_FULLSCREEN_OP_LEAVE, SDL_UpdateFullscreenMode(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowMoved()
void SDL_OnWindowMoved (SDL_Window * window) extern
{
    SDL_CheckWindowDisplayChanged(window);
}
References SDL_CheckWindowDisplayChanged().
Referenced by SDL_SendWindowEvent().
SDL_OnWindowPixelSizeChanged()
void SDL_OnWindowPixelSizeChanged (SDL_Window * window) extern
{
    window->surface_valid = false;
}
Referenced by SDL_SendWindowEvent().
SDL_OnWindowResized()
void SDL_OnWindowResized (SDL_Window * window) extern
{
    SDL_CheckWindowDisplayChanged(window);
    SDL_CheckWindowPixelSizeChanged(window);
    SDL_CheckWindowSafeAreaChanged(window);
    if ((window->flags & SDL_WINDOW_TRANSPARENT) && _this->UpdateWindowShape) {
        SDL_Surface *surface = (SDL_Surface *)SDL_GetPointerProperty(window->props, SDL_PROP_WINDOW_SHAPE_POINTER, NULL);
        if (surface) {
            _this->UpdateWindowShape(_this, window, surface);
        }
    }
}
References _this, NULL, SDL_CheckWindowDisplayChanged(), SDL_CheckWindowPixelSizeChanged(), SDL_CheckWindowSafeAreaChanged(), SDL_GetPointerProperty(), SDL_PROP_WINDOW_SHAPE_POINTER, and SDL_WINDOW_TRANSPARENT.
Referenced by SDL_SendWindowEvent(), and SDL_UpdateFullscreenMode().
SDL_OnWindowRestored()
void SDL_OnWindowRestored (SDL_Window * window) extern
{
    /*
     * FIXME: Is this fine to just remove this, or should it be preserved just
     * for the fullscreen case? In principle it seems like just hiding/showing
     * windows shouldn't affect the stacking order; maybe the right fix is to
     * re-decouple OnWindowShown and OnWindowRestored.
     */
    // SDL_RaiseWindow(window);
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_ENTER, false);
    }
}
References SDL_FULLSCREEN_OP_ENTER, SDL_UpdateFullscreenMode(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_SendWindowEvent().
SDL_OnWindowShown()
void SDL_OnWindowShown (SDL_Window * window) extern
{
    // Set window state if we have pending window flags cached
    ApplyWindowFlags(window, window->pending_flags);
    window->pending_flags = 0;
}
References ApplyWindowFlags().
Referenced by SDL_SendWindowEvent().
SDL_RecreateWindow()
bool SDL_RecreateWindow (SDL_Window * window, SDL_WindowFlags flags) extern
{
    bool loaded_opengl = false;
    bool need_gl_unload = false;
    bool need_gl_load = false;
    bool loaded_vulkan = false;
    bool need_vulkan_unload = false;
    bool need_vulkan_load = false;
    SDL_WindowFlags graphics_flags;
    // ensure no more than one of these flags is set
    graphics_flags = flags & (SDL_WINDOW_OPENGL | SDL_WINDOW_METAL | SDL_WINDOW_VULKAN);
    if (graphics_flags & (graphics_flags - 1)) {
        return SDL_SetError("Conflicting window flags specified");
    }
    if ((flags & SDL_WINDOW_OPENGL) && !_this->GL_CreateContext) {
        return SDL_ContextNotSupported("OpenGL");
    }
    if ((flags & SDL_WINDOW_VULKAN) && !_this->Vulkan_CreateSurface) {
        return SDL_ContextNotSupported("Vulkan");
    }
    if ((flags & SDL_WINDOW_METAL) && !_this->Metal_CreateView) {
        return SDL_ContextNotSupported("Metal");
    }
    if (window->flags & SDL_WINDOW_EXTERNAL) {
        // Can't destroy and re-create external windows, hrm
        flags |= SDL_WINDOW_EXTERNAL;
    } else {
        flags &= ~SDL_WINDOW_EXTERNAL;
    }
    // If this is a modal dialog, clear the modal status.
    if (window->flags & SDL_WINDOW_MODAL) {
        SDL_SetWindowModal(window, false);
    }
    // Restore video mode, etc.
    if (!(window->flags & SDL_WINDOW_EXTERNAL)) {
        const bool restore_on_show = window->restore_on_show;
        SDL_HideWindow(window);
        window->restore_on_show = restore_on_show;
    }
    // Tear down the old native window
    SDL_DestroyWindowSurface(window);
    if ((window->flags & SDL_WINDOW_OPENGL) != (flags & SDL_WINDOW_OPENGL)) {
        if (flags & SDL_WINDOW_OPENGL) {
            need_gl_load = true;
        } else {
            need_gl_unload = true;
        }
    } else if (window->flags & SDL_WINDOW_OPENGL) {
        need_gl_unload = true;
        need_gl_load = true;
    }
    if ((window->flags & SDL_WINDOW_VULKAN) != (flags & SDL_WINDOW_VULKAN)) {
        if (flags & SDL_WINDOW_VULKAN) {
            need_vulkan_load = true;
        } else {
            need_vulkan_unload = true;
        }
    } else if (window->flags & SDL_WINDOW_VULKAN) {
        need_vulkan_unload = true;
        need_vulkan_load = true;
    }
    if (need_gl_unload) {
        SDL_GL_UnloadLibrary();
    }
    if (need_vulkan_unload) {
        SDL_Vulkan_UnloadLibrary();
    }
    if (_this->DestroyWindow && !(flags & SDL_WINDOW_EXTERNAL)) {
        _this->DestroyWindow(_this, window);
    }
    if (need_gl_load) {
        if (!SDL_GL_LoadLibrary(NULL)) {
            return false;
        }
        loaded_opengl = true;
    }
    if (need_vulkan_load) {
        if (!SDL_Vulkan_LoadLibrary(NULL)) {
            return false;
        }
        loaded_vulkan = true;
    }
    window->flags = ((flags & CREATE_FLAGS) | SDL_WINDOW_HIDDEN);
    window->is_destroying = false;
    if (_this->CreateSDLWindow && !(flags & SDL_WINDOW_EXTERNAL)) {
        /* Reset the window size to the original floating value, so the
         * recreated window has the proper base size.
         */
        window->x = window->windowed.x = window->floating.x;
        window->y = window->windowed.y = window->floating.y;
        window->w = window->windowed.w = window->floating.w;
        window->h = window->windowed.h = window->floating.h;
        if (!_this->CreateSDLWindow(_this, window, 0)) {
            if (loaded_opengl) {
                SDL_GL_UnloadLibrary();
                window->flags &= ~SDL_WINDOW_OPENGL;
            }
            if (loaded_vulkan) {
                SDL_Vulkan_UnloadLibrary();
                window->flags &= ~SDL_WINDOW_VULKAN;
            }
            return false;
        }
    }
    if (flags & SDL_WINDOW_EXTERNAL) {
        window->flags |= SDL_WINDOW_EXTERNAL;
    }
    if (_this->SetWindowTitle && window->title) {
        _this->SetWindowTitle(_this, window);
    }
    if (_this->SetWindowIcon && window->icon) {
        _this->SetWindowIcon(_this, window, window->icon);
    }
    if (_this->SetWindowMinimumSize && (window->min_w || window->min_h)) {
        _this->SetWindowMinimumSize(_this, window);
    }
    if (_this->SetWindowMaximumSize && (window->max_w || window->max_h)) {
        _this->SetWindowMaximumSize(_this, window);
    }
    if (_this->SetWindowAspectRatio && (window->min_aspect > 0.0f || window->max_aspect > 0.0f)) {
        _this->SetWindowAspectRatio(_this, window);
    }
    if (window->hit_test) {
        _this->SetWindowHitTest(window, true);
    }
    SDL_FinishWindowCreation(window, flags);
    return true;
}
References _this, CREATE_FLAGS, NULL, SDL_ContextNotSupported(), SDL_DestroyWindowSurface(), SDL_FinishWindowCreation(), SDL_GL_LoadLibrary(), SDL_GL_UnloadLibrary(), SDL_HideWindow(), SDL_SetError(), SDL_SetWindowModal(), SDL_Vulkan_LoadLibrary(), SDL_Vulkan_UnloadLibrary(), SDL_WINDOW_EXTERNAL, SDL_WINDOW_HIDDEN, SDL_WINDOW_METAL, SDL_WINDOW_MODAL, SDL_WINDOW_OPENGL, and SDL_WINDOW_VULKAN.
SDL_RelativeToGlobalForWindow()
void SDL_RelativeToGlobalForWindow (SDL_Window * window, int rel_x, int rel_y, int * abs_x, int * abs_y) extern
{
    SDL_Window *w;
    if (SDL_WINDOW_IS_POPUP(window)) {
        // Calculate the total offset of the popup from the parents
        for (w = window->parent; w; w = w->parent) {
            rel_x += w->x;
            rel_y += w->y;
            if (!SDL_WINDOW_IS_POPUP(w)) {
                break;
            }
        }
    }
    if (abs_x) {
        *abs_x = rel_x;
    }
    if (abs_y) {
        *abs_y = rel_y;
    }
}
References SDL_Window::parent, SDL_WINDOW_IS_POPUP, SDL_Window::x, and SDL_Window::y.
Referenced by SDL_GetDisplayForWindowPosition().
SDL_ResetFullscreenDisplayModes()
void SDL_ResetFullscreenDisplayModes (SDL_VideoDisplay * display) extern
{
    int i;
    for (i = display->num_fullscreen_modes; i--;) {
        SDL_free(display->fullscreen_modes[i].internal);
        display->fullscreen_modes[i].internal = NULL;
    }
    SDL_free(display->fullscreen_modes);
    display->fullscreen_modes = NULL;
    display->num_fullscreen_modes = 0;
    display->max_fullscreen_modes = 0;
    display->current_mode = &display->desktop_mode;
}
References NULL, and SDL_free().
Referenced by SDL_DelVideoDisplay().
SDL_SetCurrentDisplayMode()
void SDL_SetCurrentDisplayMode (SDL_VideoDisplay * display, const SDL_DisplayMode * mode) extern
{
    SDL_DisplayMode last_mode;
    if (display->current_mode) {
        SDL_copyp(&last_mode, display->current_mode);
    } else {
        SDL_zero(last_mode);
    }
    display->current_mode = mode;
    if (DisplayModeChanged(&last_mode, mode)) {
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, mode->w, mode->h);
    }
}
References DisplayModeChanged(), SDL_DisplayMode::h, SDL_copyp, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, SDL_SendDisplayEvent(), SDL_zero, and SDL_DisplayMode::w.
Referenced by SDL_SetDisplayModeForDisplay().
SDL_SetDesktopDisplayMode()
void SDL_SetDesktopDisplayMode (SDL_VideoDisplay * display, const SDL_DisplayMode * mode) extern
{
    SDL_DisplayMode last_mode;
    if (display->fullscreen_active) {
        // This is a temporary mode change, don't save the desktop mode
        return;
    }
    SDL_copyp(&last_mode, &display->desktop_mode);
    if (display->desktop_mode.internal) {
        SDL_free(display->desktop_mode.internal);
    }
    SDL_copyp(&display->desktop_mode, mode);
    display->desktop_mode.displayID = display->id;
    SDL_FinalizeDisplayMode(&display->desktop_mode);
    if (DisplayModeChanged(&last_mode, &display->desktop_mode)) {
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED, mode->w, mode->h);
        if (display->current_mode == &display->desktop_mode) {
            SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, mode->w, mode->h);
        }
    }
}
References DisplayModeChanged(), SDL_DisplayMode::h, SDL_copyp, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED, SDL_FinalizeDisplayMode(), SDL_free(), SDL_SendDisplayEvent(), and SDL_DisplayMode::w.
SDL_SetDisplayContentScale()
void SDL_SetDisplayContentScale (SDL_VideoDisplay * display, float scale) extern
{
    if (scale != display->content_scale) {
        SDL_Window *window;
        display->content_scale = scale;
        SDL_SendDisplayEvent(display, SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED, 0, 0);
        // Check the windows on this display
        for (window = _this->windows; window; window = window->next) {
            if (display->id == window->last_displayID) {
                SDL_CheckWindowDisplayScaleChanged(window);
            }
        }
    }
}
References _this, SDL_CheckWindowDisplayScaleChanged(), SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED, and SDL_SendDisplayEvent().
SDL_SetDisplayHDRProperties()
void SDL_SetDisplayHDRProperties (SDL_VideoDisplay * display, const SDL_HDROutputProperties * HDR) extern
{
    bool changed = false;
    if (HDR->SDR_white_level != display->HDR.SDR_white_level) {
        display->HDR.SDR_white_level = SDL_max(HDR->SDR_white_level, 1.0f);
        changed = true;
    }
    if (HDR->HDR_headroom != display->HDR.HDR_headroom) {
        display->HDR.HDR_headroom = SDL_max(HDR->HDR_headroom, 1.0f);
        changed = true;
    }
    SDL_copyp(&display->HDR, HDR);
    if (changed && !SDL_DriverSendsHDRChanges(_this)) {
        for (SDL_Window *w = display->device->windows; w; w = w->next) {
            if (SDL_GetDisplayForWindow(w) == display->id) {
                SDL_SetWindowHDRProperties(w, &display->HDR, true);
            }
        }
    }
}
References _this, SDL_HDROutputProperties::HDR_headroom, SDL_copyp, SDL_DriverSendsHDRChanges(), SDL_GetDisplayForWindow(), SDL_max, SDL_SetWindowHDRProperties(), and SDL_HDROutputProperties::SDR_white_level.
SDL_SetDisplayModeForDisplay()
bool SDL_SetDisplayModeForDisplay (SDL_VideoDisplay * display, SDL_DisplayMode * mode) extern
{
    /* Mode switching is being emulated per-window; nothing to do and cannot fail,
     * except for XWayland, which still needs the actual mode setting call since
     * it's emulated via the XRandR interface.
     */
    if (SDL_ModeSwitchingEmulated(_this) && SDL_strcmp(_this->name, "x11") != 0) {
        return true;
    }
    if (!mode) {
        mode = &display->desktop_mode;
    }
    if (mode == display->current_mode) {
        return true;
    }
    // Actually change the display mode
    if (_this->SetDisplayMode) {
        bool result;
        _this->setting_display_mode = true;
        result = _this->SetDisplayMode(_this, display, mode);
        _this->setting_display_mode = false;
        if (!result) {
            return false;
        }
    }
    SDL_SetCurrentDisplayMode(display, mode);
    return true;
}
References _this, SDL_ModeSwitchingEmulated(), SDL_SetCurrentDisplayMode(), and SDL_strcmp().
Referenced by SDL_UpdateFullscreenMode().
SDL_SetSystemTheme()
void SDL_SetSystemTheme (SDL_SystemTheme theme) extern
{
    if (_this && theme != _this->system_theme) {
        _this->system_theme = theme;
        SDL_SendSystemThemeChangedEvent();
    }
}
References _this, and SDL_SendSystemThemeChangedEvent().
Referenced by DBus_MessageFilter().
SDL_SetWindowHDRProperties()
void SDL_SetWindowHDRProperties (SDL_Window * window, const SDL_HDROutputProperties * HDR, bool send_event) extern
{
    if (window->HDR.HDR_headroom != HDR->HDR_headroom || window->HDR.SDR_white_level != window->HDR.SDR_white_level) {
        SDL_PropertiesID window_props = SDL_GetWindowProperties(window);
        SDL_SetFloatProperty(window_props, SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT, SDL_max(HDR->HDR_headroom, 1.0f));
        SDL_SetFloatProperty(window_props, SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT, SDL_max(HDR->SDR_white_level, 1.0f));
        SDL_SetBooleanProperty(window_props, SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN, HDR->HDR_headroom > 1.0f);
        SDL_copyp(&window->HDR, HDR);
        if (send_event) {
            SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_HDR_STATE_CHANGED, HDR->HDR_headroom > 1.0f, 0);
        }
    }
}
References SDL_HDROutputProperties::HDR_headroom, SDL_copyp, SDL_EVENT_WINDOW_HDR_STATE_CHANGED, SDL_GetWindowProperties(), SDL_max, SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN, SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT, SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT, SDL_SendWindowEvent(), SDL_SetBooleanProperty(), SDL_SetFloatProperty(), and SDL_HDROutputProperties::SDR_white_level.
Referenced by SDL_CreateWindowWithProperties(), and SDL_SetDisplayHDRProperties().
SDL_SetWindowSafeAreaInsets()
void SDL_SetWindowSafeAreaInsets (SDL_Window * window, int left, int right, int top, int bottom) extern
{
    window->safe_inset_left = left;
    window->safe_inset_right = right;
    window->safe_inset_top = top;
    window->safe_inset_bottom = bottom;
    SDL_CheckWindowSafeAreaChanged(window);
}
References bottom, left, right, SDL_CheckWindowSafeAreaChanged(), and top.
SDL_ShouldAllowTopmost()
bool SDL_ShouldAllowTopmost (void) extern
{
    return SDL_GetHintBoolean(SDL_HINT_WINDOW_ALLOW_TOPMOST, true);
}
References SDL_GetHintBoolean(), and SDL_HINT_WINDOW_ALLOW_TOPMOST.
SDL_ShouldFocusPopup()
bool SDL_ShouldFocusPopup (SDL_Window * window) extern
{
    SDL_Window *toplevel_parent;
    for (toplevel_parent = window->parent; SDL_WINDOW_IS_POPUP(toplevel_parent); toplevel_parent = toplevel_parent->parent) {
    }
    SDL_Window *current_focus = toplevel_parent->keyboard_focus;
    bool found_higher_focus = false;
    /* Traverse the window tree from the currently focused window to the toplevel parent and see if we encounter
     * the new focus request. If the new window is found, a higher-level window already has focus.
     */
    SDL_Window *w;
    for (w = current_focus; w != toplevel_parent; w = w->parent) {
        if (w == window) {
            found_higher_focus = true;
            break;
        }
    }
    return !found_higher_focus || w == toplevel_parent;
}
References SDL_Window::keyboard_focus, SDL_Window::parent, and SDL_WINDOW_IS_POPUP.
SDL_ShouldRelinquishPopupFocus()
bool SDL_ShouldRelinquishPopupFocus (SDL_Window * window, SDL_Window ** new_focus) extern
{
    SDL_Window *focus = window->parent;
    bool set_focus = !!(window->flags & SDL_WINDOW_INPUT_FOCUS);
    // Find the highest level window, up to the toplevel parent, that isn't being hidden or destroyed, and can grab the keyboard focus.
    while (SDL_WINDOW_IS_POPUP(focus) && ((focus->flags & SDL_WINDOW_NOT_FOCUSABLE) || focus->is_hiding || focus->is_destroying)) {
        focus = focus->parent;
        // If some window in the chain currently had focus, set it to the new lowest-level window.
        if (!set_focus) {
            set_focus = !!(focus->flags & SDL_WINDOW_INPUT_FOCUS);
        }
    }
    *new_focus = focus;
    return set_focus;
}
References SDL_Window::flags, SDL_Window::is_destroying, SDL_Window::is_hiding, SDL_Window::parent, SDL_WINDOW_INPUT_FOCUS, SDL_WINDOW_IS_POPUP, and SDL_WINDOW_NOT_FOCUSABLE.
SDL_ToggleDragAndDropSupport()
void SDL_ToggleDragAndDropSupport (void) extern
{
    if (_this && _this->AcceptDragAndDrop) {
        const bool enable = IsAcceptingDragAndDrop();
        SDL_Window *window;
        for (window = _this->windows; window; window = window->next) {
            _this->AcceptDragAndDrop(window, enable);
        }
    }
}
References _this, and IsAcceptingDragAndDrop().
Referenced by SDL_SetEventEnabled().
SDL_UninitializedVideo()
bool SDL_UninitializedVideo (void) extern
{
    return SDL_SetError("Video subsystem has not been initialized");
}
References SDL_SetError().
Referenced by SDL_DisableScreenSaver(), SDL_EGL_GetCurrentConfig(), SDL_EGL_GetCurrentDisplay(), SDL_EGL_GetProcAddress(), SDL_EGL_GetWindowSurface(), SDL_EnableScreenSaver(), SDL_GetClipboardData(), SDL_GetClipboardMimeTypes(), SDL_GetClipboardText(), SDL_GetCurrentVideoDriver(), SDL_GetDisplayIndex(), SDL_GetDisplays(), SDL_GetPrimaryDisplay(), SDL_GetPrimarySelectionText(), SDL_GetWindowFromID(), SDL_GetWindows(), SDL_GL_DestroyContext(), SDL_GL_GetAttribute(), SDL_GL_GetCurrentContext(), SDL_GL_GetCurrentWindow(), SDL_GL_GetProcAddress(), SDL_GL_LoadLibrary(), SDL_GL_MakeCurrent(), SDL_GL_SetAttribute(), SDL_GL_SetSwapInterval(), SDL_GL_UnloadLibrary(), SDL_HasClipboardData(), SDL_HasClipboardText(), SDL_HasPrimarySelectionText(), SDL_SaveClipboardMimeTypes(), SDL_SetClipboardData(), SDL_SetClipboardText(), SDL_SetPrimarySelectionText(), SDL_Vulkan_GetPresentationSupport(), SDL_Vulkan_GetVkGetInstanceProcAddr(), SDL_Vulkan_LoadLibrary(), and SDL_Vulkan_UnloadLibrary().
SDL_UpdateDesktopBounds()
void SDL_UpdateDesktopBounds (void) extern
{
    SDL_Rect rect;
    SDL_zero(rect);
    SDL_DisplayID *displays = SDL_GetDisplays(NULL);
    if (displays) {
        for (int i = 0; displays[i]; ++i) {
            SDL_Rect bounds;
            if (SDL_GetDisplayBounds(displays[i], &bounds)) {
                if (i == 0) {
                    SDL_copyp(&rect, &bounds);
                } else {
                    SDL_GetRectUnion(&rect, &bounds, &rect);
                }
            }
        }
        SDL_free(displays);
    }
    SDL_copyp(&_this->desktop_bounds, &rect);
}
References _this, NULL, SDL_copyp, SDL_free(), SDL_GetDisplayBounds(), SDL_GetDisplays(), SDL_GetRectUnion(), and SDL_zero.
Referenced by SDL_AddVideoDisplay(), SDL_DelVideoDisplay(), and SDL_OnDisplayMoved().
SDL_UpdateFullscreenMode()
bool SDL_UpdateFullscreenMode (SDL_Window * window, SDL_FullscreenOp fullscreen, bool commit) extern
{
    SDL_VideoDisplay *display = NULL;
    SDL_DisplayMode *mode = NULL;
    int i;
    CHECK_WINDOW_MAGIC(window, false);
    window->fullscreen_exclusive = false;
    window->update_fullscreen_on_display_changed = false;
    // If we are in the process of hiding don't go back to fullscreen
    if (window->is_destroying || window->is_hiding) {
        fullscreen = SDL_FULLSCREEN_OP_LEAVE;
    }
    // Get the correct display for this operation
    if (fullscreen) {
        display = SDL_GetVideoDisplayForFullscreenWindow(window);
        if (!display) {
            // This should never happen, but it did...
            goto done;
        }
    } else {
        for (i = 0; i < _this->num_displays; ++i) {
            display = _this->displays[i];
            if (display->fullscreen_window == window) {
                break;
            }
        }
        if (!display || i == _this->num_displays) {
            // Already not fullscreen on any display
            display = NULL;
        }
    }
    if (fullscreen) {
        mode = (SDL_DisplayMode *)SDL_GetWindowFullscreenMode(window);
        if (mode) {
            window->fullscreen_exclusive = true;
        } else {
            // Make sure the current mode is zeroed for fullscreen desktop.
            SDL_zero(window->current_fullscreen_mode);
        }
    }
#if defined(SDL_PLATFORM_MACOS) && defined(SDL_VIDEO_DRIVER_COCOA)
    /* if the window is going away and no resolution change is necessary,
       do nothing, or else we may trigger an ugly double-transition
     */
    if (SDL_strcmp(_this->name, "cocoa") == 0) { // don't do this for X11, etc
        if (window->is_destroying && !window->last_fullscreen_exclusive_display) {
            window->fullscreen_exclusive = false;
            if (display) {
                display->fullscreen_window = NULL;
            }
            goto done;
        }
        if (commit) {
            // If we're switching between a fullscreen Space and exclusive fullscreen, we need to get back to normal first.
            if (fullscreen && Cocoa_IsWindowInFullscreenSpace(window) && !window->last_fullscreen_exclusive_display && window->fullscreen_exclusive) {
                if (!Cocoa_SetWindowFullscreenSpace(window, false, true)) {
                    goto error;
                }
            } else if (fullscreen && window->last_fullscreen_exclusive_display && !window->fullscreen_exclusive) {
                for (i = 0; i < _this->num_displays; ++i) {
                    SDL_VideoDisplay *last_display = _this->displays[i];
                    if (last_display->fullscreen_window == window) {
                        SDL_SetDisplayModeForDisplay(last_display, NULL);
                        if (_this->SetWindowFullscreen) {
                            _this->SetWindowFullscreen(_this, window, last_display, false);
                        }
                        last_display->fullscreen_window = NULL;
                    }
                }
            }
            if (Cocoa_SetWindowFullscreenSpace(window, !!fullscreen, syncHint)) {
                goto done;
            }
        }
    }
#endif
    if (display) {
        // Restore the video mode on other displays if needed
        for (i = 0; i < _this->num_displays; ++i) {
            SDL_VideoDisplay *other = _this->displays[i];
            if (other != display && other->fullscreen_window == window) {
                SDL_SetDisplayModeForDisplay(other, NULL);
                other->fullscreen_window = NULL;
            }
        }
    }
    if (fullscreen) {
        int mode_w = 0, mode_h = 0;
        bool resized = false;
        // Hide any other fullscreen window on this display
        if (display->fullscreen_window &&
            display->fullscreen_window != window) {
            SDL_MinimizeWindow(display->fullscreen_window);
        }
        display->fullscreen_active = window->fullscreen_exclusive;
        if (!SDL_SetDisplayModeForDisplay(display, mode)) {
            goto error;
        }
        if (commit) {
            SDL_FullscreenResult ret = SDL_FULLSCREEN_SUCCEEDED;
            if (_this->SetWindowFullscreen) {
                ret = _this->SetWindowFullscreen(_this, window, display, fullscreen);
            } else {
                resized = true;
            }
            if (ret == SDL_FULLSCREEN_SUCCEEDED) {
                // Window is fullscreen immediately upon return. If the driver hasn't already sent the event, do so now.
                if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_ENTER_FULLSCREEN, 0, 0);
                }
            } else if (ret == SDL_FULLSCREEN_FAILED) {
                display->fullscreen_active = false;
                goto error;
            }
        }
        if (window->flags & SDL_WINDOW_FULLSCREEN) {
            display->fullscreen_window = window;
            /* Android may not resize the window to exactly what our fullscreen mode is,
             * especially on windowed Android environments like the Chromebook or Samsung DeX.
             * Given this, we shouldn't use the mode size. Android's SetWindowFullscreen
             * will generate the window event for us with the proper final size.
             *
             * This is also unnecessary on Cocoa, Wayland, Win32, and X11 (will send SDL_EVENT_WINDOW_RESIZED).
             */
            if (!SDL_SendsFullscreenDimensions(_this)) {
                SDL_Rect displayRect;
                if (mode) {
                    mode_w = mode->w;
                    mode_h = mode->h;
                    SDL_GetDisplayBounds(mode->displayID, &displayRect);
                } else {
                    mode_w = display->desktop_mode.w;
                    mode_h = display->desktop_mode.h;
                    SDL_GetDisplayBounds(display->id, &displayRect);
                }
                if (window->w != mode_w || window->h != mode_h) {
                    resized = true;
                }
                SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_MOVED, displayRect.x, displayRect.y);
                if (resized) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_RESIZED, mode_w, mode_h);
                } else {
                    SDL_OnWindowResized(window);
                }
            }
            // Restore the cursor position
            if (!SDL_DisableMouseWarpOnFullscreenTransitions(_this)) {
                SDL_RestoreMousePosition(window);
            }
        }
    } else {
        bool resized = false;
        // Restore the desktop mode
        if (display) {
            display->fullscreen_active = false;
            SDL_SetDisplayModeForDisplay(display, NULL);
        }
        if (commit) {
            SDL_FullscreenResult ret = SDL_FULLSCREEN_SUCCEEDED;
            if (_this->SetWindowFullscreen) {
                SDL_VideoDisplay *full_screen_display = display ? display : SDL_GetVideoDisplayForFullscreenWindow(window);
                if (full_screen_display) {
                    ret = _this->SetWindowFullscreen(_this, window, full_screen_display, SDL_FULLSCREEN_OP_LEAVE);
                }
            } else {
                resized = true;
            }
            if (ret == SDL_FULLSCREEN_SUCCEEDED) {
                // Window left fullscreen immediately upon return. If the driver hasn't already sent the event, do so now.
                if (window->flags & SDL_WINDOW_FULLSCREEN) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_LEAVE_FULLSCREEN, 0, 0);
                }
            } else if (ret == SDL_FULLSCREEN_FAILED) {
                goto error;
            }
        }
        if (!(window->flags & SDL_WINDOW_FULLSCREEN)) {
            if (display) {
                display->fullscreen_window = NULL;
            }
            if (!SDL_SendsFullscreenDimensions(_this)) {
                SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_MOVED, window->windowed.x, window->windowed.y);
                if (resized) {
                    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_RESIZED, window->windowed.w, window->windowed.h);
                } else {
                    SDL_OnWindowResized(window);
                }
            }
            // Restore the cursor position if we've exited fullscreen on a display
            if (display && !SDL_DisableMouseWarpOnFullscreenTransitions(_this)) {
                SDL_RestoreMousePosition(window);
            }
        }
    }
done:
    window->last_fullscreen_exclusive_display = display && (window->flags & SDL_WINDOW_FULLSCREEN) && window->fullscreen_exclusive ? display->id : 0;
    return true;
error:
    if (fullscreen) {
        // Something went wrong and the window is no longer fullscreen.
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, commit);
    }
    return false;
}
References _this, CHECK_WINDOW_MAGIC, SDL_DisplayMode::displayID, SDL_VideoDisplay::fullscreen_window, SDL_DisplayMode::h, NULL, SDL_DisableMouseWarpOnFullscreenTransitions(), SDL_EVENT_WINDOW_ENTER_FULLSCREEN, SDL_EVENT_WINDOW_LEAVE_FULLSCREEN, SDL_EVENT_WINDOW_MOVED, SDL_EVENT_WINDOW_RESIZED, SDL_FULLSCREEN_FAILED, SDL_FULLSCREEN_OP_LEAVE, SDL_FULLSCREEN_SUCCEEDED, SDL_GetDisplayBounds(), SDL_GetVideoDisplayForFullscreenWindow(), SDL_GetWindowFullscreenMode(), SDL_MinimizeWindow(), SDL_OnWindowResized(), SDL_RestoreMousePosition(), SDL_SendsFullscreenDimensions(), SDL_SendWindowEvent(), SDL_SetDisplayModeForDisplay(), SDL_strcmp(), SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, SDL_zero, syncHint, SDL_DisplayMode::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_DestroyWindow(), SDL_OnWindowDisplayChanged(), SDL_OnWindowHidden(), SDL_OnWindowMinimized(), SDL_OnWindowRestored(), SDL_SetWindowFullscreen(), SDL_SetWindowFullscreenMode(), and SDL_UpdateFullscreenMode().
SDL_UpdateWindowGrab()
void SDL_UpdateWindowGrab (SDL_Window * window) extern
{
    bool keyboard_grabbed, mouse_grabbed;
    if (window->flags & SDL_WINDOW_INPUT_FOCUS) {
        if (SDL_GetMouse()->relative_mode || (window->flags & SDL_WINDOW_MOUSE_GRABBED)) {
            mouse_grabbed = true;
        } else {
            mouse_grabbed = false;
        }
        if (window->flags & SDL_WINDOW_KEYBOARD_GRABBED) {
            keyboard_grabbed = true;
        } else {
            keyboard_grabbed = false;
        }
    } else {
        mouse_grabbed = false;
        keyboard_grabbed = false;
    }
    if (mouse_grabbed || keyboard_grabbed) {
        if (_this->grabbed_window && (_this->grabbed_window != window)) {
            // stealing a grab from another window!
            _this->grabbed_window->flags &= ~(SDL_WINDOW_MOUSE_GRABBED | SDL_WINDOW_KEYBOARD_GRABBED);
            if (_this->SetWindowMouseGrab) {
                _this->SetWindowMouseGrab(_this, _this->grabbed_window, false);
            }
            if (_this->SetWindowKeyboardGrab) {
                _this->SetWindowKeyboardGrab(_this, _this->grabbed_window, false);
            }
        }
        _this->grabbed_window = window;
    } else if (_this->grabbed_window == window) {
        _this->grabbed_window = NULL; // ungrabbing input.
    }
    if (_this->SetWindowMouseGrab) {
        if (!_this->SetWindowMouseGrab(_this, window, mouse_grabbed)) {
            window->flags &= ~SDL_WINDOW_MOUSE_GRABBED;
        }
    }
    if (_this->SetWindowKeyboardGrab) {
        if (!_this->SetWindowKeyboardGrab(_this, window, keyboard_grabbed)) {
            window->flags &= ~SDL_WINDOW_KEYBOARD_GRABBED;
        }
    }
    if (_this->grabbed_window && !(_this->grabbed_window->flags & (SDL_WINDOW_MOUSE_GRABBED | SDL_WINDOW_KEYBOARD_GRABBED))) {
        _this->grabbed_window = NULL;
    }
}
References _this, NULL, SDL_GetMouse(), SDL_WINDOW_INPUT_FOCUS, SDL_WINDOW_KEYBOARD_GRABBED, and SDL_WINDOW_MOUSE_GRABBED.
Referenced by SDL_OnWindowFocusGained(), SDL_OnWindowFocusLost(), SDL_SetRelativeMouseMode(), SDL_SetWindowKeyboardGrab(), and SDL_SetWindowMouseGrab().
Variable Documentation
Android_bootstrap
VideoBootStrap Android_bootstrap extern
COCOA_bootstrap
VideoBootStrap COCOA_bootstrap extern
DUMMY_bootstrap
VideoBootStrap DUMMY_bootstrap extern
DUMMY_evdev_bootstrap
VideoBootStrap DUMMY_evdev_bootstrap extern
Emscripten_bootstrap
VideoBootStrap Emscripten_bootstrap extern
HAIKU_bootstrap
VideoBootStrap HAIKU_bootstrap extern
KMSDRM_bootstrap
VideoBootStrap KMSDRM_bootstrap extern
N3DS_bootstrap
VideoBootStrap N3DS_bootstrap extern
NGAGE_bootstrap
VideoBootStrap NGAGE_bootstrap extern
OFFSCREEN_bootstrap
VideoBootStrap OFFSCREEN_bootstrap extern
OPENVR_bootstrap
VideoBootStrap OPENVR_bootstrap extern
PRIVATE_bootstrap
VideoBootStrap PRIVATE_bootstrap extern
PS2_bootstrap
VideoBootStrap PS2_bootstrap extern
PSP_bootstrap
VideoBootStrap PSP_bootstrap extern
QNX_bootstrap
VideoBootStrap QNX_bootstrap extern
{
    "qnx", "QNX Screen",
    createDevice,
    NULL, // no ShowMessageBox implementation
    false
};
RISCOS_bootstrap
VideoBootStrap RISCOS_bootstrap extern
RPI_bootstrap
VideoBootStrap RPI_bootstrap extern
UIKIT_bootstrap
VideoBootStrap UIKIT_bootstrap extern
VITA_bootstrap
VideoBootStrap VITA_bootstrap extern
VIVANTE_bootstrap
VideoBootStrap VIVANTE_bootstrap extern
Wayland_bootstrap
VideoBootStrap Wayland_bootstrap extern
Wayland_preferred_bootstrap
VideoBootStrap Wayland_preferred_bootstrap extern
WINDOWS_bootstrap
VideoBootStrap WINDOWS_bootstrap extern
X11_bootstrap
VideoBootStrap X11_bootstrap extern