SDL3: SDL-main/src/core/openbsd/SDL_wscons_kbd.c File Reference
SDL_wscons_kbd.c File Reference
#include "SDL_internal.h"
#include <dev/wscons/wsksymvar.h>
#include <dev/wscons/wsksymdef.h>
#include "SDL_wscons.h"
#include <sys/time.h>
#include <dev/wscons/wsconsio.h>
#include <dev/wscons/wsdisplay_usl_io.h>
#include <termios.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <sys/param.h>
#include <unistd.h>
#include "../../events/SDL_events_c.h"
#include "../../events/SDL_keyboard_c.h"
Data Structures
struct SDL_wscons_compose_tab_s
struct SDL_WSCONS_input_data
struct wscons_keycode_to_SDL
Macros
#define IS_ALT_HELD (input->shiftstate[1] > 0)
#define IS_ALTGR_MODE ((input->ledstate & (1 << 4)) || (input->shiftstate[3] > 0))
#define IS_CAPSLOCK_ON (input->ledstate & LED_CAP)
#define IS_CONTROL_HELD (input->shiftstate[2] > 0)
#define IS_NUMLOCK_ON (input->ledstate & LED_NUM)
#define IS_SCROLLLOCK_ON (input->ledstate & LED_SCR)
#define IS_SHIFT_HELD ((input->shiftstate[0] > 0) || (input->ledstate & (1 << 5)))
#define RETIFIOCTLERR(x)
Typedefs
typedef struct SDL_WSCONS_mouse_input_data SDL_WSCONS_mouse_input_data
Functions
static Uint64 GetEventTimestamp (struct timespec *time)
static keysym_t ksym_upcase (keysym_t ksym)
static void put_queue (SDL_WSCONS_input_data *kbd, uint c)
static void put_utf8 (SDL_WSCONS_input_data *input, uint c)
void SDL_WSCONS_Init (void)
static SDL_WSCONS_input_data * SDL_WSCONS_Init_Keyboard (const char *dev)
SDL_WSCONS_mouse_input_data * SDL_WSCONS_Init_Mouse (void)
void SDL_WSCONS_PumpEvents (void)
void SDL_WSCONS_Quit (void)
void SDL_WSCONS_Quit_Mouse (SDL_WSCONS_mouse_input_data *input)
static void Translate_to_keycode (SDL_WSCONS_input_data *input, int type, keysym_t ksym, Uint64 timestamp)
static void Translate_to_text (SDL_WSCONS_input_data *input, keysym_t ksym)
static void updateKeyboard (SDL_WSCONS_input_data *input)
void updateMouse (SDL_WSCONS_mouse_input_data *input)
Variables
static struct SDL_wscons_compose_tab_s compose_tab []
static struct wscons_keycode_to_SDL conversion_table []
static SDL_WSCONS_input_data * inputs [4] = { NULL, NULL, NULL, NULL }
static const unsigned char latin1_to_upper [256]
static SDL_WSCONS_mouse_input_data * mouseInputData = NULL
Macro Definition Documentation
IS_ALT_HELD
#define IS_ALT_HELD (input->shiftstate[1] > 0)
Referenced by updateKeyboard().
IS_ALTGR_MODE
#define IS_ALTGR_MODE ((input->ledstate & (1 << 4)) || (input->shiftstate[3] > 0))
Referenced by updateKeyboard().
IS_CAPSLOCK_ON
#define IS_CAPSLOCK_ON (input->ledstate & LED_CAP)
Referenced by updateKeyboard().
IS_CONTROL_HELD
#define IS_CONTROL_HELD (input->shiftstate[2] > 0)
Referenced by updateKeyboard().
IS_NUMLOCK_ON
#define IS_NUMLOCK_ON (input->ledstate & LED_NUM)
Referenced by Translate_to_keycode(), and updateKeyboard().
IS_SCROLLLOCK_ON
#define IS_SCROLLLOCK_ON (input->ledstate & LED_SCR)
IS_SHIFT_HELD
#define IS_SHIFT_HELD ((input->shiftstate[0] > 0) || (input->ledstate & (1 << 5)))
Referenced by Translate_to_keycode(), and updateKeyboard().
RETIFIOCTLERR
#define RETIFIOCTLERR (x)
Value:
    if ((x) == -1) {     \
        SDL_free(input); \
        input = NULL;    \
        return NULL;     \
    }
#define RETIFIOCTLERR(x) \
    if ((x) == -1) {     \
        SDL_free(input); \
        input = NULL;    \
        return NULL;     \
    }
Referenced by SDL_WSCONS_Init_Keyboard().
Typedef Documentation
SDL_WSCONS_mouse_input_data
typedef struct SDL_WSCONS_mouse_input_data SDL_WSCONS_mouse_input_data
Function Documentation
GetEventTimestamp()
Uint64 GetEventTimestamp (struct timespec * time) static
{
    // FIXME: Get the event time in the SDL tick time base
    return SDL_GetTicksNS();
}
References SDL_GetTicksNS().
Referenced by updateKeyboard().
ksym_upcase()
keysym_t ksym_upcase (keysym_t ksym) static
{
    if (ksym >= KS_f1 && ksym <= KS_f20) {
        return KS_F1 - KS_f1 + ksym;
    }
    if (KS_GROUP(ksym) == KS_GROUP_Ascii && ksym <= 0xff && latin1_to_upper[ksym] != 0x00) {
        return latin1_to_upper[ksym];
    }
    return ksym;
}
References latin1_to_upper.
Referenced by updateKeyboard().
put_queue()
void put_queue (SDL_WSCONS_input_data * kbd, uint c) static
{
    // c is already part of a UTF-8 sequence and safe to add as a character
    if (kbd->text_len < (sizeof(kbd->text) - 1)) {
        kbd->text[kbd->text_len++] = (char)(c);
    }
}
References SDL_WSCONS_input_data::text, SDL_WSCONS_input_data::text_len, and uint.
Referenced by put_utf8().
put_utf8()
void put_utf8 (SDL_WSCONS_input_data * input, uint c) static
{
    if (c < 0x80)
        /*  0******* */
        put_queue(input, c);
    else if (c < 0x800) {
        /* 110***** 10****** */
        put_queue(input, 0xc0 | (c >> 6));
        put_queue(input, 0x80 | (c & 0x3f));
    } else if (c < 0x10000) {
        if (c >= 0xD800 && c <= 0xF500) {
            return;
        }
        if (c == 0xFFFF) {
            return;
        }
        /* 1110**** 10****** 10****** */
        put_queue(input, 0xe0 | (c >> 12));
        put_queue(input, 0x80 | ((c >> 6) & 0x3f));
        put_queue(input, 0x80 | (c & 0x3f));
    } else if (c < 0x110000) {
        /* 11110*** 10****** 10****** 10****** */
        put_queue(input, 0xf0 | (c >> 18));
        put_queue(input, 0x80 | ((c >> 12) & 0x3f));
        put_queue(input, 0x80 | ((c >> 6) & 0x3f));
        put_queue(input, 0x80 | (c & 0x3f));
    }
}
References put_queue(), and uint.
Referenced by Translate_to_text().
SDL_WSCONS_Init()
void SDL_WSCONS_Init (void)
{
    inputs[0] = SDL_WSCONS_Init_Keyboard("/dev/wskbd0");
    inputs[1] = SDL_WSCONS_Init_Keyboard("/dev/wskbd1");
    inputs[2] = SDL_WSCONS_Init_Keyboard("/dev/wskbd2");
    inputs[3] = SDL_WSCONS_Init_Keyboard("/dev/wskbd3");
    mouseInputData = SDL_WSCONS_Init_Mouse();
    return;
}
References inputs, mouseInputData, SDL_WSCONS_Init_Keyboard(), and SDL_WSCONS_Init_Mouse().
SDL_WSCONS_Init_Keyboard()
SDL_WSCONS_input_data * SDL_WSCONS_Init_Keyboard (const char * dev) static
{
#ifdef WSKBDIO_SETVERSION
    int version = WSKBDIO_EVENT_VERSION;
#endif
    SDL_WSCONS_input_data *input = (SDL_WSCONS_input_data *)SDL_calloc(1, sizeof(SDL_WSCONS_input_data));
    if (!input) {
        return NULL;
    }
    input->fd = open(dev, O_RDWR | O_NONBLOCK | O_CLOEXEC);
    if (input->fd == -1) {
        SDL_free(input);
        input = NULL;
        return NULL;
    }
    input->keyboardID = SDL_GetNextObjectID();
    SDL_AddKeyboard(input->keyboardID, NULL, false);
    input->keymap.map = SDL_calloc(KS_NUMKEYCODES, sizeof(struct wscons_keymap));
    if (!input->keymap.map) {
        SDL_free(input);
        return NULL;
    }
    input->keymap.maplen = KS_NUMKEYCODES;
    RETIFIOCTLERR(ioctl(input->fd, WSKBDIO_GETMAP, &input->keymap));
    RETIFIOCTLERR(ioctl(input->fd, WSKBDIO_GETLEDS, &input->ledstate));
    input->origledstate = input->ledstate;
    RETIFIOCTLERR(ioctl(input->fd, WSKBDIO_GETENCODING, &input->encoding));
    RETIFIOCTLERR(ioctl(input->fd, WSKBDIO_GTYPE, &input->type));
#ifdef WSKBDIO_SETVERSION
    RETIFIOCTLERR(ioctl(input->fd, WSKBDIO_SETVERSION, &version));
#endif
    return input;
}
References NULL, O_CLOEXEC, RETIFIOCTLERR, SDL_AddKeyboard(), SDL_calloc(), SDL_free(), and SDL_GetNextObjectID().
Referenced by SDL_WSCONS_Init().
SDL_WSCONS_Init_Mouse()
SDL_WSCONS_mouse_input_data * SDL_WSCONS_Init_Mouse (void) extern
{
#ifdef WSMOUSEIO_SETVERSION
    int version = WSMOUSE_EVENT_VERSION;
#endif
    SDL_WSCONS_mouse_input_data *input = SDL_calloc(1, sizeof(SDL_WSCONS_mouse_input_data));
    if (!input) {
        return NULL;
    }
    input->fd = open("/dev/wsmouse", O_RDWR | O_NONBLOCK | O_CLOEXEC);
    if (input->fd == -1) {
        SDL_free(input);
        return NULL;
    }
    input->mouseID = SDL_GetNextObjectID();
    SDL_AddMouse(input->mouseID, NULL, false);
#ifdef WSMOUSEIO_SETMODE
    ioctl(input->fd, WSMOUSEIO_SETMODE, WSMOUSE_COMPAT);
#endif
#ifdef WSMOUSEIO_SETVERSION
    ioctl(input->fd, WSMOUSEIO_SETVERSION, &version);
#endif
    return input;
}
References NULL, O_CLOEXEC, SDL_AddMouse(), SDL_calloc(), SDL_free(), and SDL_GetNextObjectID().
Referenced by SDL_WSCONS_Init().
SDL_WSCONS_PumpEvents()
void SDL_WSCONS_PumpEvents (void)
{
    int i = 0;
    for (i = 0; i < 4; i++) {
        updateKeyboard(inputs[i]);
    }
    if (mouseInputData) {
        updateMouse(mouseInputData);
    }
}
References inputs, mouseInputData, updateKeyboard(), and updateMouse().
SDL_WSCONS_Quit()
void SDL_WSCONS_Quit (void)
{
    int i = 0;
    SDL_WSCONS_input_data *input = NULL;
    SDL_WSCONS_Quit_Mouse(mouseInputData);
    mouseInputData = NULL;
    for (i = 0; i < 4; i++) {
        input = inputs[i];
        if (input) {
            if (input->fd != -1 && input->fd != 0) {
                ioctl(input->fd, WSKBDIO_SETLEDS, &input->origledstate);
                close(input->fd);
                input->fd = -1;
            }
            SDL_free(input);
            input = NULL;
        }
        inputs[i] = NULL;
    }
}
References inputs, mouseInputData, NULL, SDL_free(), and SDL_WSCONS_Quit_Mouse().
SDL_WSCONS_Quit_Mouse()
void SDL_WSCONS_Quit_Mouse (SDL_WSCONS_mouse_input_data * input) extern
{
    if (!input) {
        return;
    }
    close(input->fd);
    SDL_free(input);
}
References SDL_free().
Referenced by SDL_WSCONS_Quit().
Translate_to_keycode()
void Translate_to_keycode (SDL_WSCONS_input_data * input, int type, keysym_t ksym, Uint64 timestamp) static
{
    struct wscons_keymap keyDesc = input->keymap.map[ksym];
    keysym_t *group = &keyDesc.group1[KS_GROUP(keyDesc.group1[0]) == KS_GROUP_Keypad && IS_NUMLOCK_ON ? !IS_SHIFT_HELD : 0];
    int i = 0;
    // Check command first, then group[0]
    switch (keyDesc.command) {
    case KS_Cmd_ScrollBack:
    {
        SDL_SendKeyboardKey(timestamp, input->keyboardID, 0, SDL_SCANCODE_PAGEUP, (type == WSCONS_EVENT_KEY_DOWN));
        return;
    }
    case KS_Cmd_ScrollFwd:
    {
        SDL_SendKeyboardKey(timestamp, input->keyboardID, 0, SDL_SCANCODE_PAGEDOWN, (type == WSCONS_EVENT_KEY_DOWN));
        return;
    }
    default:
        break;
    }
    for (i = 0; i < SDL_arraysize(conversion_table); i++) {
        if (conversion_table[i].sourcekey == group[0]) {
            SDL_SendKeyboardKey(timestamp, input->keyboardID, group[0], conversion_table[i].targetKey, (type == WSCONS_EVENT_KEY_DOWN));
            return;
        }
    }
    SDL_SendKeyboardKey(timestamp, input->keyboardID, group[0], SDL_SCANCODE_UNKNOWN, (type == WSCONS_EVENT_KEY_DOWN));
}
References conversion_table, IS_NUMLOCK_ON, IS_SHIFT_HELD, SDL_arraysize, SDL_SCANCODE_PAGEDOWN, SDL_SCANCODE_PAGEUP, SDL_SCANCODE_UNKNOWN, and SDL_SendKeyboardKey().
Referenced by updateKeyboard().
Translate_to_text()
void Translate_to_text (SDL_WSCONS_input_data * input, keysym_t ksym) static
{
    if (KS_GROUP(ksym) == KS_GROUP_Keypad) {
        if (SDL_isprint(ksym & 0xFF)) {
            ksym &= 0xFF;
        }
    }
    switch (ksym) {
    case KS_Escape:
    case KS_Delete:
    case KS_BackSpace:
    case KS_Return:
    case KS_Linefeed:
        // All of these are unprintable characters. Ignore them
        break;
    default:
        put_utf8(input, ksym);
        break;
    }
    if (input->text_len > 0) {
        input->text[input->text_len] = '\0';
        SDL_SendKeyboardText(input->text);
        // SDL_memset(input->text, 0, sizeof(input->text));
        input->text_len = 0;
        input->text[0] = 0;
    }
}
References put_utf8(), SDL_isprint(), and SDL_SendKeyboardText().
Referenced by updateKeyboard().
updateKeyboard()
void updateKeyboard (SDL_WSCONS_input_data * input) static
{
    struct wscons_event events[64];
    int type;
    int n, i, gindex, acc_i;
    keysym_t *group;
    keysym_t ksym, result;
    if (!input) {
        return;
    }
    if ((n = read(input->fd, events, sizeof(events))) > 0) {
        n /= sizeof(struct wscons_event);
        for (i = 0; i < n; i++) {
            Uint64 timestamp = GetEventTimestamp(&events[i].time);
            type = events[i].type;
            switch (type) {
            case WSCONS_EVENT_KEY_DOWN:
            {
                switch (input->keymap.map[events[i].value].group1[0]) {
                case KS_Hold_Screen:
                {
                    if (input->lockheldstate[0] >= 1) {
                        break;
                    }
                    input->ledstate ^= LED_SCR;
                    ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                    input->lockheldstate[0] = 1;
                    break;
                }
                case KS_Num_Lock:
                {
                    if (input->lockheldstate[1] >= 1) {
                        break;
                    }
                    input->ledstate ^= LED_NUM;
                    ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                    input->lockheldstate[1] = 1;
                    break;
                }
                case KS_Caps_Lock:
                {
                    if (input->lockheldstate[2] >= 1) {
                        break;
                    }
                    input->ledstate ^= LED_CAP;
                    ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                    input->lockheldstate[2] = 1;
                    break;
                }
#ifndef SDL_PLATFORM_NETBSD
                case KS_Mode_Lock:
                {
                    if (input->lockheldstate[3] >= 1) {
                        break;
                    }
                    input->ledstate ^= 1 << 4;
                    ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                    input->lockheldstate[3] = 1;
                    break;
                }
#endif
                case KS_Shift_Lock:
                {
                    if (input->lockheldstate[4] >= 1) {
                        break;
                    }
                    input->ledstate ^= 1 << 5;
                    ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                    input->lockheldstate[4] = 1;
                    break;
                }
                case KS_Shift_L:
                {
                    if (input->shiftheldstate[0]) {
                        break;
                    }
                    input->shiftstate[0]++;
                    input->shiftheldstate[0] = 1;
                    break;
                }
                case KS_Shift_R:
                {
                    if (input->shiftheldstate[1]) {
                        break;
                    }
                    input->shiftstate[0]++;
                    input->shiftheldstate[1] = 1;
                    break;
                }
                case KS_Alt_L:
                {
                    if (input->shiftheldstate[2]) {
                        break;
                    }
                    input->shiftstate[1]++;
                    input->shiftheldstate[2] = 1;
                    break;
                }
                case KS_Alt_R:
                {
                    if (input->shiftheldstate[3]) {
                        break;
                    }
                    input->shiftstate[1]++;
                    input->shiftheldstate[3] = 1;
                    break;
                }
                case KS_Control_L:
                {
                    if (input->shiftheldstate[4]) {
                        break;
                    }
                    input->shiftstate[2]++;
                    input->shiftheldstate[4] = 1;
                    break;
                }
                case KS_Control_R:
                {
                    if (input->shiftheldstate[5]) {
                        break;
                    }
                    input->shiftstate[2]++;
                    input->shiftheldstate[5] = 1;
                    break;
                }
                case KS_Mode_switch:
                {
                    if (input->shiftheldstate[6]) {
                        break;
                    }
                    input->shiftstate[3]++;
                    input->shiftheldstate[6] = 1;
                    break;
                }
                }
            } break;
            case WSCONS_EVENT_KEY_UP:
            {
                switch (input->keymap.map[events[i].value].group1[0]) {
                case KS_Hold_Screen:
                {
                    if (input->lockheldstate[0]) {
                        input->lockheldstate[0] = 0;
                    }
                } break;
                case KS_Num_Lock:
                {
                    if (input->lockheldstate[1]) {
                        input->lockheldstate[1] = 0;
                    }
                } break;
                case KS_Caps_Lock:
                {
                    if (input->lockheldstate[2]) {
                        input->lockheldstate[2] = 0;
                    }
                } break;
#ifndef SDL_PLATFORM_NETBSD
                case KS_Mode_Lock:
                {
                    if (input->lockheldstate[3]) {
                        input->lockheldstate[3] = 0;
                    }
                } break;
#endif
                case KS_Shift_Lock:
                {
                    if (input->lockheldstate[4]) {
                        input->lockheldstate[4] = 0;
                    }
                } break;
                case KS_Shift_L:
                {
                    input->shiftheldstate[0] = 0;
                    if (input->shiftstate[0]) {
                        input->shiftstate[0]--;
                    }
                    break;
                }
                case KS_Shift_R:
                {
                    input->shiftheldstate[1] = 0;
                    if (input->shiftstate[0]) {
                        input->shiftstate[0]--;
                    }
                    break;
                }
                case KS_Alt_L:
                {
                    input->shiftheldstate[2] = 0;
                    if (input->shiftstate[1]) {
                        input->shiftstate[1]--;
                    }
                    break;
                }
                case KS_Alt_R:
                {
                    input->shiftheldstate[3] = 0;
                    if (input->shiftstate[1]) {
                        input->shiftstate[1]--;
                    }
                    break;
                }
                case KS_Control_L:
                {
                    input->shiftheldstate[4] = 0;
                    if (input->shiftstate[2]) {
                        input->shiftstate[2]--;
                    }
                    break;
                }
                case KS_Control_R:
                {
                    input->shiftheldstate[5] = 0;
                    if (input->shiftstate[2]) {
                        input->shiftstate[2]--;
                    }
                    break;
                }
                case KS_Mode_switch:
                {
                    input->shiftheldstate[6] = 0;
                    if (input->shiftstate[3]) {
                        input->shiftstate[3]--;
                    }
                    break;
                }
                }
            } break;
            case WSCONS_EVENT_ALL_KEYS_UP:
                for (i = 0; i < SDL_SCANCODE_COUNT; i++) {
                    SDL_SendKeyboardKey(timestamp, input->keyboardID, 0, (SDL_Scancode)i, false);
                }
                break;
            default:
                break;
            }
            if (input->type == WSKBD_TYPE_USB && events[i].value <= 0xE7) {
                SDL_SendKeyboardKey(timestamp, input->keyboardID, 0, (SDL_Scancode)events[i].value, (type == WSCONS_EVENT_KEY_DOWN));
            } else {
                Translate_to_keycode(input, type, events[i].value, timestamp);
            }
            if (type == WSCONS_EVENT_KEY_UP) {
                continue;
            }
            if (IS_ALTGR_MODE && !IS_CONTROL_HELD)
                group = &input->keymap.map[events[i].value].group2[0];
            else
                group = &input->keymap.map[events[i].value].group1[0];
            if (IS_NUMLOCK_ON && KS_GROUP(group[1]) == KS_GROUP_Keypad) {
                gindex = !IS_SHIFT_HELD;
                ksym = group[gindex];
            } else {
                if (IS_CAPSLOCK_ON && !IS_SHIFT_HELD) {
                    gindex = 0;
                    ksym = ksym_upcase(group[0]);
                } else {
                    gindex = IS_SHIFT_HELD;
                    ksym = group[gindex];
                }
            }
            result = KS_voidSymbol;
            switch (KS_GROUP(ksym)) {
            case KS_GROUP_Ascii:
            case KS_GROUP_Keypad:
            case KS_GROUP_Function:
                result = ksym;
                break;
            case KS_GROUP_Mod:
                if (ksym == KS_Multi_key) {
                    input->ledstate |= WSKBD_LED_COMPOSE;
                    ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                    input->composelen = 2;
                    input->composebuffer[0] = input->composebuffer[1] = 0;
                }
                break;
            case KS_GROUP_Dead:
                if (input->composelen == 0) {
                    input->ledstate |= WSKBD_LED_COMPOSE;
                    ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                    input->composelen = 1;
                    input->composebuffer[0] = ksym;
                    input->composebuffer[1] = 0;
                } else
                    result = ksym;
                break;
            }
            if (result == KS_voidSymbol) {
                continue;
            }
            if (input->composelen > 0) {
                if (input->composelen == 2 && group == &input->keymap.map[events[i].value].group2[0]) {
                    if (input->keymap.map[events[i].value].group2[gindex] == input->keymap.map[events[i].value].group1[gindex]) {
                        input->composelen = 0;
                        input->composebuffer[0] = input->composebuffer[1] = 0;
                    }
                }
                if (input->composelen != 0) {
                    input->composebuffer[2 - input->composelen] = result;
                    if (--input->composelen == 0) {
                        result = KS_voidSymbol;
                        input->ledstate &= ~WSKBD_LED_COMPOSE;
                        ioctl(input->fd, WSKBDIO_SETLEDS, &input->ledstate);
                        for (acc_i = 0; acc_i < SDL_arraysize(compose_tab); acc_i++) {
                            if ((compose_tab[acc_i].elem[0] == input->composebuffer[0] && compose_tab[acc_i].elem[1] == input->composebuffer[1]) || (compose_tab[acc_i].elem[0] == input->composebuffer[1] && compose_tab[acc_i].elem[1] == input->composebuffer[0])) {
                                result = compose_tab[acc_i].result;
                                break;
                            }
                        }
                    } else
                        continue;
                }
            }
            if (KS_GROUP(result) == KS_GROUP_Ascii) {
                if (IS_CONTROL_HELD) {
                    if ((result >= KS_at && result <= KS_z) || result == KS_space) {
                        result = result & 0x1f;
                    } else if (result == KS_2) {
                        result = 0x00;
                    } else if (result >= KS_3 && result <= KS_7) {
                        result = KS_Escape + (result - KS_3);
                    } else if (result == KS_8) {
                        result = KS_Delete;
                    }
                }
                if (IS_ALT_HELD) {
                    if (input->encoding & KB_METAESC) {
                        Translate_to_keycode(input, WSCONS_EVENT_KEY_DOWN, KS_Escape, 0);
                        Translate_to_text(input, result);
                        continue;
                    } else {
                        result |= 0x80;
                    }
                }
            }
            Translate_to_text(input, result);
            continue;
        }
    }
}
References compose_tab, GetEventTimestamp(), IS_ALT_HELD, IS_ALTGR_MODE, IS_CAPSLOCK_ON, IS_CONTROL_HELD, IS_NUMLOCK_ON, IS_SHIFT_HELD, ksym_upcase(), SDL_arraysize, SDL_SCANCODE_COUNT, SDL_SendKeyboardKey(), Translate_to_keycode(), and Translate_to_text().
Referenced by SDL_WSCONS_PumpEvents().
updateMouse()
void updateMouse (SDL_WSCONS_mouse_input_data * input) extern
{
    struct wscons_event events[64];
    int n;
    SDL_Mouse *mouse = SDL_GetMouse();
    if ((n = read(input->fd, events, sizeof(events))) > 0) {
        int i;
        n /= sizeof(struct wscons_event);
        for (i = 0; i < n; i++) {
            Uint64 timestamp = GetEventTimestamp(&events[i].time);
            int type = events[i].type;
            switch (type) {
            case WSCONS_EVENT_MOUSE_DOWN:
            case WSCONS_EVENT_MOUSE_UP:
            {
                Uint8 button = SDL_BUTTON_LEFT + events[i].value;
                bool down = (type == WSCONS_EVENT_MOUSE_DOWN);
                SDL_SendMouseButton(timestamp, mouse->focus, input->mouseID, button, down);
                break;
            }
            case WSCONS_EVENT_MOUSE_DELTA_X:
            {
                SDL_SendMouseMotion(timestamp, mouse->focus, input->mouseID, true, (float)events[i].value, 0.0f);
                break;
            }
            case WSCONS_EVENT_MOUSE_DELTA_Y:
            {
                SDL_SendMouseMotion(timestamp, mouse->focus, input->mouseID, true, 0.0f, -(float)events[i].value);
                break;
            }
            case WSCONS_EVENT_MOUSE_DELTA_W:
            {
                SDL_SendMouseWheel(timestamp, mouse->focus, input->mouseID, events[i].value, 0, SDL_MOUSEWHEEL_NORMAL);
                break;
            }
            case WSCONS_EVENT_MOUSE_DELTA_Z:
            {
                SDL_SendMouseWheel(timestamp, mouse->focus, input->mouseID, 0, -events[i].value, SDL_MOUSEWHEEL_NORMAL);
                break;
            }
            default:
                break;
            }
        }
    }
}
References SDL_Mouse::focus, GetEventTimestamp(), SDL_BUTTON_LEFT, SDL_GetMouse(), SDL_MOUSEWHEEL_NORMAL, SDL_SendMouseButton(), SDL_SendMouseMotion(), and SDL_SendMouseWheel().
Referenced by SDL_WSCONS_PumpEvents().
Variable Documentation
compose_tab
struct SDL_wscons_compose_tab_s compose_tab[] static
Referenced by updateKeyboard().
conversion_table
struct wscons_keycode_to_SDL conversion_table[] static
Referenced by Translate_to_keycode().
inputs
SDL_WSCONS_input_data* inputs[4] = { NULL, NULL, NULL, NULL } static
{ NULL, NULL, NULL, NULL };
Referenced by SDL_WSCONS_Init(), SDL_WSCONS_PumpEvents(), and SDL_WSCONS_Quit().
latin1_to_upper
const unsigned char latin1_to_upper[256] static
{
    // 0  8  1  9  2  a  3  b  4  c  5  d  6  e  7  f
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 0
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 0
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 1
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 1
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 2
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 2
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 3
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 3
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 4
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 4
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 5
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 5
    0x00, 'A', 'B', 'C', 'D', 'E', 'F', 'G',        // 6
    'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O',         // 6
    'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W',         // 7
    'X', 'Y', 'Z', 0x00, 0x00, 0x00, 0x00, 0x00,    // 7
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 8
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 8
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 9
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // 9
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // a
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // a
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // b
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // b
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // c
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // c
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // d
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, // d
    0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, // e
    0xc8, 0xc9, 0xca, 0xcb, 0xcc, 0xcd, 0xce, 0xcf, // e
    0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0x00, // f
    0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0x00, // f
};
Referenced by ksym_upcase().
mouseInputData
SDL_WSCONS_mouse_input_data* mouseInputData = NULL static
Referenced by SDL_WSCONS_Init(), SDL_WSCONS_PumpEvents(), and SDL_WSCONS_Quit().