SDL3: SDL-main/src/joystick/controller_type.h File Reference
controller_type.h File Reference
Data Structures
struct ControllerDescription_t
Enumerations
enum EControllerType {
k_eControllerType_None = -1 , k_eControllerType_Unknown = 0 , k_eControllerType_UnknownSteamController = 1 , k_eControllerType_SteamController = 2 ,
k_eControllerType_SteamControllerV2 = 3 , k_eControllerType_SteamControllerNeptune = 4 , k_eControllerType_UnknownNonSteamController = 30 , k_eControllerType_XBox360Controller = 31 ,
k_eControllerType_XBoxOneController = 32 , k_eControllerType_PS3Controller = 33 , k_eControllerType_PS4Controller = 34 , k_eControllerType_WiiController = 35 ,
k_eControllerType_AppleController = 36 , k_eControllerType_AndroidController = 37 , k_eControllerType_SwitchProController = 38 , k_eControllerType_SwitchJoyConLeft = 39 ,
k_eControllerType_SwitchJoyConRight = 40 , k_eControllerType_SwitchJoyConPair = 41 , k_eControllerType_SwitchInputOnlyController = 42 , k_eControllerType_MobileTouch = 43 ,
k_eControllerType_XInputSwitchController = 44 , k_eControllerType_PS5Controller = 45 , k_eControllerType_XInputPS4Controller = 46 , k_eControllerType_LastController ,
k_eControllertype_GenericKeyboard = 400 , k_eControllertype_GenericMouse = 800
}
Functions
const char * GuessControllerName (int nVID, int nPID)
EControllerType GuessControllerType (int nVID, int nPID)
Enumeration Type Documentation
EControllerType
enum EControllerType
Enumerator
k_eControllerType_None
k_eControllerType_Unknown
k_eControllerType_UnknownSteamController
k_eControllerType_SteamController
k_eControllerType_SteamControllerV2
k_eControllerType_SteamControllerNeptune
k_eControllerType_UnknownNonSteamController
k_eControllerType_XBox360Controller
k_eControllerType_XBoxOneController
k_eControllerType_PS3Controller
k_eControllerType_PS4Controller
k_eControllerType_WiiController
k_eControllerType_AppleController
k_eControllerType_AndroidController
k_eControllerType_SwitchProController
k_eControllerType_SwitchJoyConLeft
k_eControllerType_SwitchJoyConRight
k_eControllerType_SwitchJoyConPair
k_eControllerType_SwitchInputOnlyController
k_eControllerType_MobileTouch
k_eControllerType_XInputSwitchController
k_eControllerType_PS5Controller
k_eControllerType_XInputPS4Controller
k_eControllerType_LastController
k_eControllertype_GenericKeyboard
k_eControllertype_GenericMouse
{
    k_eControllerType_None = -1,
    k_eControllerType_Unknown = 0,
    // Steam Controllers
    k_eControllerType_UnknownSteamController = 1,
    k_eControllerType_SteamController = 2,
    k_eControllerType_SteamControllerV2 = 3,
    k_eControllerType_SteamControllerNeptune = 4,
    // Other Controllers
    k_eControllerType_UnknownNonSteamController = 30,
    k_eControllerType_XBox360Controller = 31,
    k_eControllerType_XBoxOneController = 32,
    k_eControllerType_PS3Controller = 33,
    k_eControllerType_PS4Controller = 34,
    k_eControllerType_WiiController = 35,
    k_eControllerType_AppleController = 36,
    k_eControllerType_AndroidController = 37,
    k_eControllerType_SwitchProController = 38,
    k_eControllerType_SwitchJoyConLeft = 39,
    k_eControllerType_SwitchJoyConRight = 40,
    k_eControllerType_SwitchJoyConPair = 41,
    k_eControllerType_SwitchInputOnlyController = 42,
    k_eControllerType_MobileTouch = 43,
    k_eControllerType_XInputSwitchController = 44,  // Client-side only, used to mark Nintendo Switch style controllers as using XInput instead of the Nintendo Switch protocol
    k_eControllerType_PS5Controller = 45,
    k_eControllerType_XInputPS4Controller = 46,     // Client-side only, used to mark DualShock 4 style controllers using XInput instead of the DualShock 4 controller protocol
    k_eControllerType_LastController,           // Don't add game controllers below this enumeration - this enumeration can change value
    // Keyboards and Mice
    k_eControllertype_GenericKeyboard = 400,
    k_eControllertype_GenericMouse = 800,
} EControllerType;
Function Documentation
GuessControllerName()
const char * GuessControllerName (int nVID, int nPID) extern
{
    unsigned int unDeviceID = MAKE_CONTROLLER_ID( nVID, nPID );
    int iIndex;
    for ( iIndex = 0; iIndex < sizeof( arrControllers ) / sizeof( arrControllers[0] ); ++iIndex )
    {
        if ( unDeviceID == arrControllers[ iIndex ].m_unDeviceID )
        {
            return arrControllers[ iIndex ].m_pszName;
        }
    }
    return NULL;
}
References arrControllers, MAKE_CONTROLLER_ID, and NULL.
Referenced by SDL_CreateJoystickName().
GuessControllerType()
EControllerType GuessControllerType (int nVID, int nPID) extern
{
#if 0//def _DEBUG
    // Verify that there are no duplicates in the controller list
    // If the list were sorted, we could do this much more efficiently, as well as improve lookup speed.
    static bool s_bCheckedForDuplicates;
    if ( !s_bCheckedForDuplicates )
    {
        s_bCheckedForDuplicates = true;
        int i, j;
        for ( i = 0; i < sizeof( arrControllers ) / sizeof( arrControllers[ 0 ] ); ++i )
        {
            for ( j = i + 1; j < sizeof( arrControllers ) / sizeof( arrControllers[ 0 ] ); ++j )
            {
                if ( arrControllers[ i ].m_unDeviceID == arrControllers[ j ].m_unDeviceID )
                {
                    Log( "Duplicate controller entry found for VID 0x%.4x PID 0x%.4x\n", ( arrControllers[ i ].m_unDeviceID >> 16 ), arrControllers[ i ].m_unDeviceID & 0xFFFF );
                }
            }
        }
    }
#endif // _DEBUG
    unsigned int unDeviceID = MAKE_CONTROLLER_ID( nVID, nPID );
    int iIndex;
    const char *pszOverride = GetControllerTypeOverride( nVID, nPID );
    if ( pszOverride )
    {
        if ( SDL_strncasecmp( pszOverride, "Xbox360", 7 ) == 0 )
        {
            return k_eControllerType_XBox360Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "XboxOne", 7 ) == 0 )
        {
            return k_eControllerType_XBoxOneController;
        }
        if ( SDL_strncasecmp( pszOverride, "PS3", 3 ) == 0 )
        {
            return k_eControllerType_PS3Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "PS4", 3 ) == 0 )
        {
            return k_eControllerType_PS4Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "PS5", 3 ) == 0 )
        {
            return k_eControllerType_PS5Controller;
        }
        if ( SDL_strncasecmp( pszOverride, "SwitchPro", 9 ) == 0 )
        {
            return k_eControllerType_SwitchProController;
        }
        if ( SDL_strncasecmp( pszOverride, "Steam", 5 ) == 0 )
        {
            return k_eControllerType_SteamController;
        }
        return k_eControllerType_UnknownNonSteamController;
    }
    for ( iIndex = 0; iIndex < sizeof( arrControllers ) / sizeof( arrControllers[0] ); ++iIndex )
    {
        if ( unDeviceID == arrControllers[ iIndex ].m_unDeviceID )
        {
            return arrControllers[ iIndex ].m_eControllerType;
        }
    }
    return k_eControllerType_UnknownNonSteamController;
}
References arrControllers, GetControllerTypeOverride(), k_eControllerType_PS3Controller, k_eControllerType_PS4Controller, k_eControllerType_PS5Controller, k_eControllerType_SteamController, k_eControllerType_SwitchProController, k_eControllerType_UnknownNonSteamController, k_eControllerType_XBox360Controller, k_eControllerType_XBoxOneController, MAKE_CONTROLLER_ID, and SDL_strncasecmp().
Referenced by SDL_GetGamepadTypeFromVIDPID(), SDL_GetJoystickGUIDType(), SDL_IsJoystickNintendoSwitchJoyCon(), SDL_IsJoystickNintendoSwitchJoyConLeft(), SDL_IsJoystickNintendoSwitchJoyConRight(), SDL_IsJoystickNintendoSwitchPro(), SDL_IsJoystickNintendoSwitchProInputOnly(), SDL_IsJoystickPS4(), SDL_IsJoystickPS5(), SDL_IsJoystickSteamController(), SDL_IsJoystickSteamDeck(), and SDL_IsJoystickXboxOne().