SDL3: SDL-main/src/events/SDL_events_c.h File Reference
SDL_events_c.h File Reference
#include "SDL_internal.h"
#include "../video/SDL_sysvideo.h"
#include "SDL_clipboardevents_c.h"
#include "SDL_displayevents_c.h"
#include "SDL_dropevents_c.h"
#include "SDL_keyboard_c.h"
#include "SDL_mouse_c.h"
#include "SDL_touch_c.h"
#include "SDL_pen_c.h"
#include "SDL_windowevents_c.h"
Functions
void * SDL_AllocateTemporaryMemory (size_t size)
void * SDL_ClaimTemporaryMemory (const void *mem)
const char * SDL_CreateTemporaryString (const char *string)
void SDL_FreeTemporaryMemory (void)
bool SDL_InitEvents (void)
bool SDL_InitQuit (void)
void SDL_PumpEventMaintenance (void)
void SDL_QuitEvents (void)
void SDL_QuitInterrupt (void)
void SDL_QuitQuit (void)
void SDL_SendAppEvent (SDL_EventType eventType)
void SDL_SendKeymapChangedEvent (void)
void SDL_SendLocaleChangedEvent (void)
void SDL_SendPendingSignalEvents (void)
void SDL_SendQuit (void)
void SDL_SendSystemThemeChangedEvent (void)
bool SDL_StartEventLoop (void)
void SDL_StopEventLoop (void)
Function Documentation
SDL_AllocateTemporaryMemory()
void * SDL_AllocateTemporaryMemory (size_t size) extern
{
    return SDL_FreeLater(SDL_malloc(size));
}
References SDL_FreeLater(), and SDL_malloc().
Referenced by CreateCandidatesForEvent(), SDL_CopyClipboardMimeTypes(), and SDL_TransferSysWMMemoryToEvent().
SDL_ClaimTemporaryMemory()
void * SDL_ClaimTemporaryMemory (const void * mem) extern
{
    SDL_TemporaryMemoryState *state;
    state = SDL_GetTemporaryMemoryState(false);
    if (state && mem) {
        SDL_TemporaryMemory *entry = SDL_GetTemporaryMemoryEntry(state, mem);
        if (entry) {
            SDL_UnlinkTemporaryMemoryEntry(state, entry);
            SDL_FreeTemporaryMemoryEntry(state, entry, false);
            return (void *)mem;
        }
    }
    return NULL;
}
References NULL, SDL_FreeTemporaryMemoryEntry(), SDL_GetTemporaryMemoryEntry(), SDL_GetTemporaryMemoryState(), and SDL_UnlinkTemporaryMemoryEntry().
SDL_CreateTemporaryString()
const char * SDL_CreateTemporaryString (const char * string) extern
{
    if (string) {
        return (const char *)SDL_FreeLater(SDL_strdup(string));
    }
    return NULL;
}
References NULL, SDL_FreeLater(), and SDL_strdup().
Referenced by SDL_SendDrop(), SDL_SendEditingText(), and SDL_SendKeyboardText().
SDL_FreeTemporaryMemory()
void SDL_FreeTemporaryMemory (void) extern
{
    SDL_TemporaryMemoryState *state;
    state = SDL_GetTemporaryMemoryState(false);
    if (!state) {
        return;
    }
    while (state->head) {
        SDL_TemporaryMemory *entry = state->head;
        SDL_UnlinkTemporaryMemoryEntry(state, entry);
        SDL_FreeTemporaryMemoryEntry(state, entry, true);
    }
}
References SDL_TemporaryMemoryState::head, SDL_FreeTemporaryMemoryEntry(), SDL_GetTemporaryMemoryState(), and SDL_UnlinkTemporaryMemoryEntry().
Referenced by SDL_CleanupTemporaryMemory(), and SDL_PumpEventsInternal().
SDL_InitEvents()
bool SDL_InitEvents (void) extern
{
#ifdef SDL_PLATFORM_ANDROID
    Android_InitEvents();
#endif
#ifndef SDL_JOYSTICK_DISABLED
    SDL_AddHintCallback(SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_AutoUpdateJoysticksChanged, NULL);
#endif
#ifndef SDL_SENSOR_DISABLED
    SDL_AddHintCallback(SDL_HINT_AUTO_UPDATE_SENSORS, SDL_AutoUpdateSensorsChanged, NULL);
#endif
    SDL_AddHintCallback(SDL_HINT_EVENT_LOGGING, SDL_EventLoggingChanged, NULL);
    SDL_AddHintCallback(SDL_HINT_POLL_SENTINEL, SDL_PollSentinelChanged, NULL);
    SDL_InitMainThreadCallbacks();
    if (!SDL_StartEventLoop()) {
        SDL_RemoveHintCallback(SDL_HINT_EVENT_LOGGING, SDL_EventLoggingChanged, NULL);
        return false;
    }
    SDL_InitQuit();
    return true;
}
References Android_InitEvents(), NULL, SDL_AddHintCallback(), SDL_AutoUpdateJoysticksChanged(), SDL_AutoUpdateSensorsChanged(), SDL_EventLoggingChanged(), SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_HINT_AUTO_UPDATE_SENSORS, SDL_HINT_EVENT_LOGGING, SDL_HINT_POLL_SENTINEL, SDL_InitMainThreadCallbacks(), SDL_InitQuit(), SDL_PollSentinelChanged(), SDL_RemoveHintCallback(), and SDL_StartEventLoop().
Referenced by SDL_InitSubSystem().
SDL_InitQuit()
bool SDL_InitQuit (void) extern
{
#ifdef HAVE_SIGNAL_SUPPORT
    if (!SDL_GetHintBoolean(SDL_HINT_NO_SIGNAL_HANDLERS, false)) {
        return SDL_QuitInit_Internal();
    }
#endif
    return true;
}
References SDL_GetHintBoolean(), and SDL_HINT_NO_SIGNAL_HANDLERS.
Referenced by SDL_InitEvents().
SDL_PumpEventMaintenance()
void SDL_PumpEventMaintenance (void) extern
{
#ifndef SDL_AUDIO_DISABLED
    SDL_UpdateAudio();
#endif
#ifndef SDL_CAMERA_DISABLED
    SDL_UpdateCamera();
#endif
#ifndef SDL_SENSOR_DISABLED
    // Check for sensor state change
    if (SDL_update_sensors) {
        SDL_UpdateSensors();
    }
#endif
#ifndef SDL_JOYSTICK_DISABLED
    // Check for joystick state change
    if (SDL_update_joysticks) {
        SDL_UpdateJoysticks();
    }
#endif
    SDL_UpdateTrays();
    SDL_SendPendingSignalEvents(); // in case we had a signal handler fire, etc.
}
References SDL_SendPendingSignalEvents(), SDL_update_joysticks, SDL_update_sensors, SDL_UpdateAudio(), SDL_UpdateCamera(), SDL_UpdateJoysticks(), SDL_UpdateSensors(), and SDL_UpdateTrays().
Referenced by SDL_OnWindowLiveResizeUpdate(), and SDL_PumpEventsInternal().
SDL_QuitEvents()
void SDL_QuitEvents (void) extern
{
    SDL_QuitQuit();
    SDL_StopEventLoop();
    SDL_QuitMainThreadCallbacks();
    SDL_RemoveHintCallback(SDL_HINT_POLL_SENTINEL, SDL_PollSentinelChanged, NULL);
    SDL_RemoveHintCallback(SDL_HINT_EVENT_LOGGING, SDL_EventLoggingChanged, NULL);
#ifndef SDL_JOYSTICK_DISABLED
    SDL_RemoveHintCallback(SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_AutoUpdateJoysticksChanged, NULL);
#endif
#ifndef SDL_SENSOR_DISABLED
    SDL_RemoveHintCallback(SDL_HINT_AUTO_UPDATE_SENSORS, SDL_AutoUpdateSensorsChanged, NULL);
#endif
#ifdef SDL_PLATFORM_ANDROID
    Android_QuitEvents();
#endif
}
References Android_QuitEvents(), NULL, SDL_AutoUpdateJoysticksChanged(), SDL_AutoUpdateSensorsChanged(), SDL_EventLoggingChanged(), SDL_HINT_AUTO_UPDATE_JOYSTICKS, SDL_HINT_AUTO_UPDATE_SENSORS, SDL_HINT_EVENT_LOGGING, SDL_HINT_POLL_SENTINEL, SDL_PollSentinelChanged(), SDL_QuitMainThreadCallbacks(), SDL_QuitQuit(), SDL_RemoveHintCallback(), and SDL_StopEventLoop().
Referenced by SDL_QuitSubSystem().
SDL_QuitInterrupt()
void SDL_QuitInterrupt (void) extern
SDL_QuitQuit()
void SDL_QuitQuit (void) extern
{
#ifdef HAVE_SIGNAL_SUPPORT
    if (!disable_signals) {
        SDL_QuitQuit_Internal();
    }
#endif
}
Referenced by SDL_QuitEvents().
SDL_SendAppEvent()
void SDL_SendAppEvent (SDL_EventType eventType) extern
{
    if (SDL_EventEnabled(eventType)) {
        SDL_Event event;
        event.type = eventType;
        event.common.timestamp = 0;
        switch (eventType) {
        case SDL_EVENT_TERMINATING:
        case SDL_EVENT_LOW_MEMORY:
        case SDL_EVENT_WILL_ENTER_BACKGROUND:
        case SDL_EVENT_DID_ENTER_BACKGROUND:
        case SDL_EVENT_WILL_ENTER_FOREGROUND:
        case SDL_EVENT_DID_ENTER_FOREGROUND:
            // We won't actually queue this event, it needs to be handled in this call stack by an event watcher
            if (SDL_EventLoggingVerbosity > 0) {
                SDL_LogEvent(&event);
            }
            SDL_CallEventWatchers(&event);
            break;
        default:
            SDL_PushEvent(&event);
            break;
        }
    }
}
References SDL_CallEventWatchers(), SDL_EVENT_DID_ENTER_BACKGROUND, SDL_EVENT_DID_ENTER_FOREGROUND, SDL_EVENT_LOW_MEMORY, SDL_EVENT_TERMINATING, SDL_EVENT_WILL_ENTER_BACKGROUND, SDL_EVENT_WILL_ENTER_FOREGROUND, SDL_EventEnabled(), SDL_EventLoggingVerbosity, SDL_LogEvent(), and SDL_PushEvent().
Referenced by GDK_RegisterChangeNotifications(), SDL_OnApplicationDidEnterBackground(), SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationDidReceiveMemoryWarning(), SDL_OnApplicationWillEnterBackground(), SDL_OnApplicationWillEnterForeground(), SDL_OnApplicationWillTerminate(), SDL_SendKeymapChangedEvent(), SDL_SendLocaleChangedEvent(), SDL_SendQuit(), and SDL_SendSystemThemeChangedEvent().
SDL_SendKeymapChangedEvent()
void SDL_SendKeymapChangedEvent (void) extern
{
    SDL_SendAppEvent(SDL_EVENT_KEYMAP_CHANGED);
}
References SDL_EVENT_KEYMAP_CHANGED, and SDL_SendAppEvent().
Referenced by SDL_SetKeymap().
SDL_SendLocaleChangedEvent()
void SDL_SendLocaleChangedEvent (void) extern
{
    SDL_SendAppEvent(SDL_EVENT_LOCALE_CHANGED);
}
References SDL_EVENT_LOCALE_CHANGED, and SDL_SendAppEvent().
Referenced by SDL_BLooper::MessageReceived().
SDL_SendPendingSignalEvents()
void SDL_SendPendingSignalEvents (void) extern
{
#ifdef HAVE_SIGNAL_SUPPORT
    if (send_quit_pending) {
        SDL_SendQuit();
        SDL_assert(!send_quit_pending);
    }
#ifdef SDL_BACKGROUNDING_SIGNAL
    if (send_backgrounding_pending) {
        send_backgrounding_pending = false;
        SDL_OnApplicationWillEnterBackground();
    }
#endif
#ifdef SDL_FOREGROUNDING_SIGNAL
    if (send_foregrounding_pending) {
        send_foregrounding_pending = false;
        SDL_OnApplicationDidEnterForeground();
    }
#endif
#endif
}
References SDL_assert, SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationWillEnterBackground(), and SDL_SendQuit().
Referenced by SDL_PumpEventMaintenance().
SDL_SendQuit()
void SDL_SendQuit (void) extern
{
#ifdef HAVE_SIGNAL_SUPPORT
    send_quit_pending = false;
#endif
    SDL_SendAppEvent(SDL_EVENT_QUIT);
}
References SDL_EVENT_QUIT, and SDL_SendAppEvent().
Referenced by SDL_SendPendingSignalEvents(), SDL_SendWindowEvent(), and SDL_UnregisterTray().
SDL_SendSystemThemeChangedEvent()
void SDL_SendSystemThemeChangedEvent (void) extern
{
    SDL_SendAppEvent(SDL_EVENT_SYSTEM_THEME_CHANGED);
}
References SDL_EVENT_SYSTEM_THEME_CHANGED, and SDL_SendAppEvent().
Referenced by SDL_SetSystemTheme().
SDL_StartEventLoop()
bool SDL_StartEventLoop (void) extern
{
    /* We'll leave the event queue alone, since we might have gotten
       some important events at launch (like SDL_EVENT_DROP_FILE)
       FIXME: Does this introduce any other bugs with events at startup?
     */
    // Create the lock and set ourselves active
#ifndef SDL_THREADS_DISABLED
    if (!SDL_EventQ.lock) {
        SDL_EventQ.lock = SDL_CreateMutex();
        if (SDL_EventQ.lock == NULL) {
            return false;
        }
    }
    SDL_LockMutex(SDL_EventQ.lock);
    if (!SDL_InitEventWatchList(&SDL_event_watchers)) {
        SDL_UnlockMutex(SDL_EventQ.lock);
        return false;
    }
#endif // !SDL_THREADS_DISABLED
    SDL_InitWindowEventWatch();
    SDL_EventQ.active = true;
#ifndef SDL_THREADS_DISABLED
    SDL_UnlockMutex(SDL_EventQ.lock);
#endif
    return true;
}
References NULL, SDL_CreateMutex(), SDL_event_watchers, SDL_EventQ, SDL_InitEventWatchList(), SDL_InitWindowEventWatch(), SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_InitEvents().
SDL_StopEventLoop()
void SDL_StopEventLoop (void) extern
{
    const char *report = SDL_GetHint("SDL_EVENT_QUEUE_STATISTICS");
    int i;
    SDL_EventEntry *entry;
    SDL_LockMutex(SDL_EventQ.lock);
    SDL_EventQ.active = false;
    if (report && SDL_atoi(report)) {
        SDL_Log("SDL EVENT QUEUE: Maximum events in-flight: %d",
                SDL_EventQ.max_events_seen);
    }
    // Clean out EventQ
    for (entry = SDL_EventQ.head; entry;) {
        SDL_EventEntry *next = entry->next;
        SDL_TransferTemporaryMemoryFromEvent(entry);
        SDL_free(entry);
        entry = next;
    }
    for (entry = SDL_EventQ.free; entry;) {
        SDL_EventEntry *next = entry->next;
        SDL_free(entry);
        entry = next;
    }
    SDL_SetAtomicInt(&SDL_EventQ.count, 0);
    SDL_EventQ.max_events_seen = 0;
    SDL_EventQ.head = NULL;
    SDL_EventQ.tail = NULL;
    SDL_EventQ.free = NULL;
    SDL_SetAtomicInt(&SDL_sentinel_pending, 0);
    // Clear disabled event state
    for (i = 0; i < SDL_arraysize(SDL_disabled_events); ++i) {
        SDL_free(SDL_disabled_events[i]);
        SDL_disabled_events[i] = NULL;
    }
    SDL_QuitEventWatchList(&SDL_event_watchers);
    SDL_QuitWindowEventWatch();
    SDL_Mutex *lock = NULL;
    if (SDL_EventQ.lock) {
        lock = SDL_EventQ.lock;
        SDL_EventQ.lock = NULL;
    }
    SDL_UnlockMutex(lock);
    if (lock) {
        SDL_DestroyMutex(lock);
    }
}
References lock, SDL_EventEntry::next, NULL, SDL_arraysize, SDL_atoi(), SDL_DestroyMutex(), SDL_disabled_events, SDL_event_watchers, SDL_EventQ, SDL_free(), SDL_GetHint(), SDL_LockMutex(), SDL_Log(), SDL_QuitEventWatchList(), SDL_QuitWindowEventWatch(), SDL_sentinel_pending, SDL_SetAtomicInt(), SDL_TransferTemporaryMemoryFromEvent(), and SDL_UnlockMutex().
Referenced by SDL_QuitEvents().