SDL3: SDL-main/src/SDL_properties_c.h File Reference
SDL_properties_c.h File Reference
Functions
bool SDL_DumpProperties (SDL_PropertiesID props)
bool SDL_InitProperties (void)
void SDL_QuitProperties (void)
bool SDL_SetFreeableProperty (SDL_PropertiesID props, const char *name, void *value)
bool SDL_SetSurfaceProperty (SDL_PropertiesID props, const char *name, SDL_Surface *surface)
Function Documentation
SDL_DumpProperties()
bool SDL_DumpProperties (SDL_PropertiesID props) extern
{
    return SDL_EnumerateProperties(props, SDL_DumpPropertiesCallback, NULL);
}
References NULL, SDL_DumpPropertiesCallback(), and SDL_EnumerateProperties().
SDL_InitProperties()
bool SDL_InitProperties (void) extern
{
    if (!SDL_ShouldInit(&SDL_properties_init)) {
        return true;
    }
    SDL_properties = SDL_CreateHashTable(0, true, SDL_HashID, SDL_KeyMatchID, NULL, NULL);
    const bool initialized = (SDL_properties != NULL);
    SDL_SetInitialized(&SDL_properties_init, initialized);
    return initialized;
}
References NULL, SDL_CreateHashTable(), SDL_HashID(), SDL_KeyMatchID(), SDL_properties, SDL_properties_init, SDL_SetInitialized(), and SDL_ShouldInit().
Referenced by SDL_CheckInitProperties().
SDL_QuitProperties()
void SDL_QuitProperties (void) extern
{
    if (!SDL_ShouldQuit(&SDL_properties_init)) {
        return;
    }
    SDL_PropertiesID props;
    do {
        props = SDL_GetAtomicU32(&SDL_global_properties);
    } while (!SDL_CompareAndSwapAtomicU32(&SDL_global_properties, props, 0));
    if (props) {
        SDL_DestroyProperties(props);
    }
    // this can't just DestroyHashTable with SDL_FreeProperties as the destructor, because
    //  other destructors under this might cause use to attempt a recursive lock on SDL_properties,
    //  which isn't allowed with rwlocks. So manually iterate and free everything.
    SDL_HashTable *properties = SDL_properties;
    SDL_properties = NULL;
    SDL_IterateHashTable(properties, FreeOneProperties, NULL);
    SDL_DestroyHashTable(properties);
    SDL_SetInitialized(&SDL_properties_init, false);
}
References FreeOneProperties(), NULL, SDL_CompareAndSwapAtomicU32(), SDL_DestroyHashTable(), SDL_DestroyProperties(), SDL_GetAtomicU32(), SDL_global_properties, SDL_IterateHashTable(), SDL_properties, SDL_properties_init, SDL_SetInitialized(), and SDL_ShouldQuit().
Referenced by SDL_Quit().
SDL_SetFreeableProperty()
bool SDL_SetFreeableProperty (SDL_PropertiesID props, const char * name, void * value) extern
{
    return SDL_SetPointerPropertyWithCleanup(props, name, value, CleanupFreeableProperty, NULL);
}
References CleanupFreeableProperty(), NULL, and SDL_SetPointerPropertyWithCleanup().
SDL_SetSurfaceProperty()
bool SDL_SetSurfaceProperty (SDL_PropertiesID props, const char * name, SDL_Surface * surface) extern
{
    return SDL_SetPointerPropertyWithCleanup(props, name, surface, CleanupSurface, NULL);
}
References CleanupSurface(), NULL, and SDL_SetPointerPropertyWithCleanup().
Referenced by SDL_SetWindowShape().