SDL3: SDL-main/src/hidapi/testgui/test.cpp File Reference
test.cpp File Reference
#include <fx.h>
#include "hidapi.h"
#include "mac_support.h"
#include <string.h>
#include <stdlib.h>
#include <limits.h>
Data Structures
class MainWindow
Functions
FXDEFMAP (MainWindow) MainWindowMap[]
FXIMPLEMENT (MainWindow, FXMainWindow, MainWindowMap, ARRAYNUMBER(MainWindowMap))
int main (int argc, char **argv)
Variables
FXMainWindow * g_main_window
const int timeout_scalar = 1
Function Documentation
FXDEFMAP()
FXDEFMAP (MainWindow)
References MainWindow::ID_CLEAR, MainWindow::ID_CONNECT, MainWindow::ID_DISCONNECT, MainWindow::ID_GET_FEATURE_REPORT, MainWindow::ID_MAC_TIMER, MainWindow::ID_RESCAN, MainWindow::ID_SEND_FEATURE_REPORT, MainWindow::ID_SEND_OUTPUT_REPORT, MainWindow::ID_TIMER, MainWindow::onClear(), MainWindow::onConnect(), MainWindow::onDisconnect(), MainWindow::onGetFeatureReport(), MainWindow::onMacTimeout(), MainWindow::onRescan(), MainWindow::onSendFeatureReport(), MainWindow::onSendOutputReport(), and MainWindow::onTimeout().
FXIMPLEMENT()
FXIMPLEMENT (MainWindow , FXMainWindow , MainWindowMap , ARRAYNUMBER(MainWindowMap))
main()
int main (int argc, char ** argv)
{
    FXApp app("HIDAPI Test Application", "Signal 11 Software");
    app.init(argc, argv);
    g_main_window = new MainWindow(&app);
    app.create();
    app.run();
    return 0;
}
References g_main_window.
Variable Documentation
g_main_window
FXMainWindow* g_main_window
Referenced by MyAppDelegate::applicationWillBecomeActive:, MyAppDelegate::applicationWillHide:, and main().
timeout_scalar
const int timeout_scalar = 1
Referenced by MainWindow::create(), MainWindow::onConnect(), MainWindow::onMacTimeout(), and MainWindow::onTimeout().