SDL3: SDL-main/src/filesystem/SDL_filesystem.c File Reference
SDL_filesystem.c File Reference
#include "SDL_internal.h"
#include "SDL_filesystem_c.h"
#include "SDL_sysfilesystem.h"
#include "../stdlib/SDL_sysstdlib.h"
Data Structures
struct GlobDirCallbackData
Typedefs
typedef struct GlobDirCallbackData GlobDirCallbackData
Functions
static char * CaseFoldUtf8String (const char *fname)
static size_t EncodeCodepointToUtf8 (char *ptr, Uint32 cp, size_t remaining)
static bool EverythingMatch (const char *pattern, const char *str, bool *matched_to_dir)
static SDL_EnumerationResult SDLCALL GlobDirectoryCallback (void *userdata, const char *dirname, const char *fname)
static bool GlobDirectoryEnumerator (const char *path, SDL_EnumerateDirectoryCallback cb, void *cbuserdata, void *userdata)
static bool GlobDirectoryGetPathInfo (const char *path, SDL_PathInfo *info, void *userdata)
bool SDL_CopyFile (const char *oldpath, const char *newpath)
bool SDL_CreateDirectory (const char *path)
bool SDL_EnumerateDirectory (const char *path, SDL_EnumerateDirectoryCallback callback, void *userdata)
const char * SDL_GetBasePath (void)
char * SDL_GetCurrentDirectory (void)
bool SDL_GetPathInfo (const char *path, SDL_PathInfo *info)
char * SDL_GetPrefPath (const char *org, const char *app)
const char * SDL_GetUserFolder (SDL_Folder folder)
char ** SDL_GlobDirectory (const char *path, const char *pattern, SDL_GlobFlags flags, int *count)
void SDL_InitFilesystem (void)
char ** SDL_InternalGlobDirectory (const char *path, const char *pattern, SDL_GlobFlags flags, int *count, SDL_GlobEnumeratorFunc enumerator, SDL_GlobGetPathInfoFunc getpathinfo, void *userdata)
void SDL_QuitFilesystem (void)
bool SDL_RemovePath (const char *path)
bool SDL_RenamePath (const char *oldpath, const char *newpath)
static bool WildcardMatch (const char *pattern, const char *str, bool *matched_to_dir)
Variables
static char * CachedBasePath = NULL
static char * CachedUserFolders [SDL_FOLDER_COUNT]
Typedef Documentation
GlobDirCallbackData
typedef struct GlobDirCallbackData GlobDirCallbackData
Function Documentation
CaseFoldUtf8String()
char * CaseFoldUtf8String (const char * fname) static
{
    SDL_assert(fname != NULL);
    const size_t allocation = (SDL_strlen(fname) + 1) * 3 * 4;
    char *result = (char *) SDL_malloc(allocation);  // lazy: just allocating the max needed.
    if (!result) {
        return NULL;
    }
    Uint32 codepoint;
    char *ptr = result;
    size_t remaining = allocation;
    while ((codepoint = SDL_StepUTF8(&fname, NULL)) != 0) {
        Uint32 folded[3];
        const int num_folded = SDL_CaseFoldUnicode(codepoint, folded);
        SDL_assert(num_folded > 0);
        SDL_assert(num_folded <= SDL_arraysize(folded));
        for (int i = 0; i < num_folded; i++) {
            SDL_assert(remaining > 0);
            const size_t rc = EncodeCodepointToUtf8(ptr, folded[i], remaining);
            SDL_assert(rc > 0);
            SDL_assert(rc < remaining);
            remaining -= rc;
            ptr += rc;
        }
    }
    SDL_assert(remaining > 0);
    remaining--;
    *ptr = '\0';
    if (remaining > 0) {
        SDL_assert(allocation > remaining);
        ptr = (char *)SDL_realloc(result, allocation - remaining);  // shrink it down.
        if (ptr) {  // shouldn't fail, but if it does, `result` is still valid.
            result = ptr;
        }
    }
    return result;
}
References EncodeCodepointToUtf8(), NULL, SDL_arraysize, SDL_assert, SDL_CaseFoldUnicode(), SDL_malloc(), SDL_realloc(), SDL_StepUTF8(), and SDL_strlen().
Referenced by GlobDirectoryCallback(), and SDL_InternalGlobDirectory().
EncodeCodepointToUtf8()
size_t EncodeCodepointToUtf8 (char * ptr, Uint32 cp, size_t remaining) static
{
    if (cp < 0x80) {  // fits in a single UTF-8 byte.
        if (remaining) {
            *ptr = (char) cp;
            return 1;
        }
    } else if (cp < 0x800) {  // fits in 2 bytes.
        if (remaining >= 2) {
            ptr[0] = (char) ((cp >> 6) | 128 | 64);
            ptr[1] = (char) (cp & 0x3F) | 128;
            return 2;
        }
    } else if (cp < 0x10000) { // fits in 3 bytes.
        if (remaining >= 3) {
            ptr[0] = (char) ((cp >> 12) | 128 | 64 | 32);
            ptr[1] = (char) ((cp >> 6) & 0x3F) | 128;
            ptr[2] = (char) (cp & 0x3F) | 128;
            return 3;
        }
    } else if (cp <= 0x10FFFF) {  // fits in 4 bytes.
        if (remaining >= 4) {
            ptr[0] = (char) ((cp >> 18) | 128 | 64 | 32 | 16);
            ptr[1] = (char) ((cp >> 12) & 0x3F) | 128;
            ptr[2] = (char) ((cp >> 6) & 0x3F) | 128;
            ptr[3] = (char) (cp & 0x3F) | 128;
            return 4;
        }
    }
    return 0;
}
References cp.
Referenced by CaseFoldUtf8String().
EverythingMatch()
bool EverythingMatch (const char * pattern, const char * str, bool * matched_to_dir) static
{
    SDL_assert(pattern == NULL);
    SDL_assert(str != NULL);
    SDL_assert(matched_to_dir != NULL);
    *matched_to_dir = true;
    return true;  // everything matches!
}
References NULL, and SDL_assert.
Referenced by SDL_InternalGlobDirectory().
GlobDirectoryCallback()
SDL_EnumerationResult SDLCALL GlobDirectoryCallback (void * userdata, const char * dirname, const char * fname) static
{
    SDL_assert(userdata != NULL);
    SDL_assert(dirname != NULL);
    SDL_assert(fname != NULL);
    //SDL_Log("GlobDirectoryCallback('%s', '%s')", dirname, fname);
    GlobDirCallbackData *data = (GlobDirCallbackData *) userdata;
    // !!! FIXME: if we're careful, we can keep a single buffer in `data` that we push and pop paths off the end of as we walk the tree,
    // !!! FIXME: and only casefold the new pieces instead of allocating and folding full paths for all of this.
    char *fullpath = NULL;
    if (SDL_asprintf(&fullpath, "%s%s", dirname, fname) < 0) {
        return SDL_ENUM_FAILURE;
    }
    char *folded = NULL;
    if (data->flags & SDL_GLOB_CASEINSENSITIVE) {
        folded = CaseFoldUtf8String(fullpath);
        if (!folded) {
            return SDL_ENUM_FAILURE;
        }
    }
    bool matched_to_dir = false;
    const bool matched = data->matcher(data->pattern, (folded ? folded : fullpath) + data->basedirlen, &matched_to_dir);
    //SDL_Log("GlobDirectoryCallback: Considered %spath='%s' vs pattern='%s': %smatched (matched_to_dir=%s)", folded ? "(folded) " : "", (folded ? folded : fullpath) + data->basedirlen, data->pattern, matched ? "" : "NOT ", matched_to_dir ? "TRUE" : "FALSE");
    SDL_free(folded);
    if (matched) {
        const char *subpath = fullpath + data->basedirlen;
        const size_t slen = SDL_strlen(subpath) + 1;
        if (SDL_WriteIO(data->string_stream, subpath, slen) != slen) {
            SDL_free(fullpath);
            return SDL_ENUM_FAILURE;  // stop enumerating, return failure to the app.
        }
        data->num_entries++;
    }
    SDL_EnumerationResult result = SDL_ENUM_CONTINUE;  // keep enumerating by default.
    if (matched_to_dir) {
        SDL_PathInfo info;
        if (data->getpathinfo(fullpath, &info, data->fsuserdata) && (info.type == SDL_PATHTYPE_DIRECTORY)) {
            //SDL_Log("GlobDirectoryCallback: Descending into subdir '%s'", fname);
            if (!data->enumerator(fullpath, GlobDirectoryCallback, data, data->fsuserdata)) {
                result = SDL_ENUM_FAILURE;
            }
        }
    }
    SDL_free(fullpath);
    return result;
}
References CaseFoldUtf8String(), GlobDirectoryCallback(), NULL, SDL_asprintf(), SDL_assert, SDL_ENUM_CONTINUE, SDL_ENUM_FAILURE, SDL_free(), SDL_GLOB_CASEINSENSITIVE, SDL_PATHTYPE_DIRECTORY, SDL_strlen(), SDL_WriteIO(), SDLCALL, and SDL_PathInfo::type.
Referenced by GlobDirectoryCallback(), and SDL_InternalGlobDirectory().
GlobDirectoryEnumerator()
bool GlobDirectoryEnumerator (const char * path, SDL_EnumerateDirectoryCallback cb, void * cbuserdata, void * userdata) static
{
    return SDL_EnumerateDirectory(path, cb, cbuserdata);
}
References SDL_EnumerateDirectory().
Referenced by SDL_GlobDirectory().
GlobDirectoryGetPathInfo()
bool GlobDirectoryGetPathInfo (const char * path, SDL_PathInfo * info, void * userdata) static
{
    return SDL_GetPathInfo(path, info);
}
References SDL_GetPathInfo().
Referenced by SDL_GlobDirectory().
SDL_CopyFile()
bool SDL_CopyFile (const char * oldpath, const char * newpath)
Copy a file.
If the file at newpath already exists, it will be overwritten with the contents of the file at oldpath.
This function will block until the copy is complete, which might be a significant time for large files on slow disks. On some platforms, the copy can be handed off to the OS itself, but on others SDL might just open both paths, and read from one and write to the other.
Note that this is not an atomic operation! If something tries to read from newpath while the copy is in progress, it will see an incomplete copy of the data, and if the calling thread terminates (or the power goes out) during the copy, newpath's previous contents will be gone, replaced with an incomplete copy of the data. To avoid this risk, it is recommended that the app copy to a temporary file in the same directory as newpath, and if the copy is successful, use SDL_RenamePath() to replace newpath with the temporary file. This will ensure that reads of newpath will either see a complete copy of the data, or it will see the pre-copy state of newpath.
This function attempts to synchronize the newly-copied data to disk before returning, if the platform allows it, so that the renaming trick will not have a problem in a system crash or power failure, where the file could be renamed but the contents never made it from the system file cache to the physical disk.
If the copy fails for any reason, the state of newpath is undefined. It might be half a copy, it might be the untouched data of what was already there, or it might be a zero-byte file, etc.
Parameters
oldpath the old path.
newpath the new path.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    if (!oldpath) {
        return SDL_InvalidParamError("oldpath");
    } else if (!newpath) {
        return SDL_InvalidParamError("newpath");
    }
    return SDL_SYS_CopyFile(oldpath, newpath);
}
References SDL_InvalidParamError, and SDL_SYS_CopyFile().
Referenced by GENERIC_CopyStorageFile().
SDL_CreateDirectory()
bool SDL_CreateDirectory (const char * path)
Create a directory, and any missing parent directories.
This reports success if path already exists as a directory.
If parent directories are missing, it will also create them. Note that if this fails, it will not remove any parent directories it already made.
Parameters
path the path of the directory to create.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    if (!path) {
        return SDL_InvalidParamError("path");
    }
    bool retval = SDL_SYS_CreateDirectory(path);
    if (!retval && *path) {  // maybe we're missing parent directories?
        char *parents = SDL_strdup(path);
        if (!parents) {
            return false;  // oh well.
        }
        // in case there was a separator at the end of the path and it was
        // upsetting something, chop it off.
        const size_t slen = SDL_strlen(parents);
        #ifdef SDL_PLATFORM_WINDOWS
        if ((parents[slen - 1] == '/') || (parents[slen - 1] == '\\'))
        #else
        if (parents[slen - 1] == '/')
        #endif
        {
            parents[slen - 1] = '\0';
            retval = SDL_SYS_CreateDirectory(parents);
        }
        if (!retval) {
            for (char *ptr = parents; *ptr; ptr++) {
                const char ch = *ptr;
                #ifdef SDL_PLATFORM_WINDOWS
                const bool issep = (ch == '/') || (ch == '\\');
                if (issep && ((ptr - parents) == 2) && (parents[1] == ':')) {
                    continue;  // it's just the drive letter, skip it.
                }
                #else
                const bool issep = (ch == '/');
                if (issep && ((ptr - parents) == 0)) {
                    continue; // it's just the root directory, skip it.
                }
                #endif
                if (issep) {
                    *ptr = '\0';
                    // (this does not fail if the path already exists as a directory.)
                    retval = SDL_SYS_CreateDirectory(parents);
                    if (!retval) {  // still failing when making parents? Give up.
                        break;
                    }
                    *ptr = ch;
                }
            }
            // last chance: did it work this time?
            retval = SDL_SYS_CreateDirectory(parents);
        }
        SDL_free(parents);
    }
    return retval;
}
References SDL_free(), SDL_InvalidParamError, SDL_strdup(), SDL_strlen(), and SDL_SYS_CreateDirectory().
Referenced by GENERIC_CreateStorageDirectory().
SDL_EnumerateDirectory()
bool SDL_EnumerateDirectory (const char * path, SDL_EnumerateDirectoryCallback callback, void * userdata)
Enumerate a directory through a callback function.
This function provides every directory entry through an app-provided callback, called once for each directory entry, until all results have been provided or the callback returns either SDL_ENUM_SUCCESS or SDL_ENUM_FAILURE.
This will return false if there was a system problem in general, or if a callback returns SDL_ENUM_FAILURE. A successful return means a callback returned SDL_ENUM_SUCCESS to halt enumeration, or all directory entries were enumerated.
Parameters
path the path of the directory to enumerate.
callback a function that is called for each entry in the directory.
userdata a pointer that is passed to callback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!callback) {
        return SDL_InvalidParamError("callback");
    }
    return SDL_SYS_EnumerateDirectory(path, callback, userdata);
}
References SDL_InvalidParamError, and SDL_SYS_EnumerateDirectory().
Referenced by GENERIC_EnumerateStorageDirectory(), and GlobDirectoryEnumerator().
SDL_GetBasePath()
const char * SDL_GetBasePath (void)
CategoryFilesystem
SDL offers an API for examining and manipulating the system's filesystem. This covers most things one would need to do with directories, except for actual file I/O (which is covered by [CategoryIOStream](CategoryIOStream) and [CategoryAsyncIO](CategoryAsyncIO) instead).
There are functions to answer necessary path questions:
Where is my app's data? SDL_GetBasePath().
Where can I safely write files? SDL_GetPrefPath().
Where are paths like Downloads, Desktop, Music? SDL_GetUserFolder().
What is this thing at this location? SDL_GetPathInfo().
What items live in this folder? SDL_EnumerateDirectory().
What items live in this folder by wildcard? SDL_GlobDirectory().
What is my current working directory? SDL_GetCurrentDirectory().
SDL also offers functions to manipulate the directory tree: renaming, removing, copying files. Get the directory where the application was run from.
SDL caches the result of this call internally, but the first call to this function is not necessarily fast, so plan accordingly.
macOS and iOS Specific Functionality: If the application is in a ".app" bundle, this function returns the Resource directory (e.g. MyApp.app/Contents/Resources/). This behaviour can be overridden by adding a property to the Info.plist file. Adding a string key with the name SDL_FILESYSTEM_BASE_DIR_TYPE with a supported value will change the behaviour.
Supported values for the SDL_FILESYSTEM_BASE_DIR_TYPE property (Given an application in /Applications/SDLApp/MyApp.app):
resource: bundle resource directory (the default). For example: /Applications/SDLApp/MyApp.app/Contents/Resources
bundle: the Bundle directory. For example: /Applications/SDLApp/MyApp.app/
parent: the containing directory of the bundle. For example: /Applications/SDLApp/
Nintendo 3DS Specific Functionality: This function returns "romfs" directory of the application as it is uncommon to store resources outside the executable. As such it is not a writable directory.
The returned path is guaranteed to end with a path separator ('\' on Windows, '/' on most other platforms).
Returns
an absolute path in UTF-8 encoding to the application data directory. NULL will be returned on error or when the platform doesn't implement this functionality, call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPrefPath
{
    if (!CachedBasePath) {
        CachedBasePath = SDL_SYS_GetBasePath();
    }
    return CachedBasePath;
}
References CachedBasePath, and SDL_SYS_GetBasePath().
Referenced by GENERIC_Title_Create().
SDL_GetCurrentDirectory()
char * SDL_GetCurrentDirectory (void)
Get what the system believes is the "current working directory."
For systems without a concept of a current working directory, this will still attempt to provide something reasonable.
SDL does not provide a means to change the current working directory; for platforms without this concept, this would cause surprises with file access outside of SDL.
The returned path is guaranteed to end with a path separator ('\' on Windows, '/' on most other platforms).
Returns
a UTF-8 string of the current working directory in platform-dependent notation. NULL if there's a problem. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
{
    return SDL_SYS_GetCurrentDirectory();
}
References SDL_SYS_GetCurrentDirectory().
SDL_GetPathInfo()
bool SDL_GetPathInfo (const char * path, SDL_PathInfo * info)
Get information about a filesystem path.
Parameters
path the path to query.
info a pointer filled in with information about the path, or NULL to check for the existence of a file.
Returns
true on success or false if the file doesn't exist, or another failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PathInfo dummy;
    if (!info) {
        info = &dummy;
    }
    SDL_zerop(info);
    if (!path) {
        return SDL_InvalidParamError("path");
    }
    return SDL_SYS_GetPathInfo(path, info);
}
References SDL_InvalidParamError, SDL_SYS_GetPathInfo(), and SDL_zerop.
Referenced by GENERIC_GetStoragePathInfo(), and GlobDirectoryGetPathInfo().
SDL_GetPrefPath()
char * SDL_GetPrefPath (const char * org, const char * app)
Get the user-and-app-specific path where files can be written.
Get the "pref dir". This is meant to be where users can write personal files (preferences and save games, etc) that are specific to your application. This directory is unique per user, per application.
This function will decide the appropriate location in the native filesystem, create the directory if necessary, and return a string of the absolute path to the directory in UTF-8 encoding.
On Windows, the string might look like:
C:\\Users\\bob\\AppData\\Roaming\\My Company\\My Program Name\\
On Linux, the string might look like:
/home/bob/.local/share/My Program Name/
On macOS, the string might look like:
/Users/bob/Library/Application Support/My Program Name/
You should assume the path returned by this function is the only safe place to write files (and that SDL_GetBasePath(), while it might be writable, or even the parent of the returned path, isn't where you should be writing things).
Both the org and app strings may become part of a directory name, so please follow these rules:
Try to use the same org string (including case-sensitivity) for all your applications that use this function.
Always use a unique app string for each one, and make sure it never changes for an app once you've decided on it.
Unicode characters are legal, as long as they are UTF-8 encoded, but...
...only use letters, numbers, and spaces. Avoid punctuation like "Game Name 2: Bad Guy's Revenge!" ... "Game Name 2" is sufficient.
Due to historical mistakes, org is allowed to be NULL or "". In such cases, SDL will omit the org subdirectory, including on platforms where it shouldn't, and including on platforms where this would make your app fail certification for an app store. New apps should definitely specify a real string for org.
The returned path is guaranteed to end with a path separator ('\' on Windows, '/' on most other platforms).
Parameters
org the name of your organization.
app the name of your application.
Returns
a UTF-8 string of the user directory in platform-dependent notation. NULL if there's a problem (creating directory failed, etc.). This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetBasePath
{
    if (!app) {
        SDL_InvalidParamError("app");
        return NULL;
    }
    // if org is NULL, just make it "" so backends don't have to check both.
    if (!org) {
        org = "";
    }
    return SDL_SYS_GetPrefPath(org, app);
}
References NULL, SDL_InvalidParamError, and SDL_SYS_GetPrefPath().
Referenced by GENERIC_User_Create().
SDL_GetUserFolder()
const char * SDL_GetUserFolder (SDL_Folder folder)
Finds the most suitable user folder for a specific purpose.
Many OSes provide certain standard folders for certain purposes, such as storing pictures, music or videos for a certain user. This function gives the path for many of those special locations.
This function is specifically for user folders, which are meant for the user to access and manage. For application-specific folders, meant to hold data for the application to manage, see SDL_GetBasePath() and SDL_GetPrefPath().
The returned path is guaranteed to end with a path separator ('\' on Windows, '/' on most other platforms).
If NULL is returned, the error may be obtained with SDL_GetError().
Parameters
folder the type of folder to find.
Returns
either a null-terminated C string containing the full path to the folder, or NULL if an error happened.
Since
This function is available since SDL 3.2.0.
{
    const int idx = (int) folder;
    if ((idx < 0) || (idx >= SDL_arraysize(CachedUserFolders))) {
        SDL_InvalidParamError("folder");
        return NULL;
    }
    if (!CachedUserFolders[idx]) {
        CachedUserFolders[idx] = SDL_SYS_GetUserFolder(folder);
    }
    return CachedUserFolders[idx];
}
References CachedUserFolders, NULL, SDL_arraysize, SDL_InvalidParamError, and SDL_SYS_GetUserFolder().
SDL_GlobDirectory()
char ** SDL_GlobDirectory (const char * path, const char * pattern, SDL_GlobFlags flags, int * count)
Enumerate a directory tree, filtered by pattern, and return a list.
Files are filtered out if they don't match the string in pattern, which may contain wildcard characters * (match everything) and ? (match one character). If pattern is NULL, no filtering is done and all results are returned. Subdirectories are permitted, and are specified with a path separator of /. Wildcard characters * and ? never match a path separator.
flags may be set to SDL_GLOB_CASEINSENSITIVE to make the pattern matching case-insensitive.
The returned array is always NULL-terminated, for your iterating convenience, but if count is non-NULL, on return it will contain the number of items in the array, not counting the NULL terminator.
Parameters
path the path of the directory to enumerate.
pattern the pattern that files in the directory must match. Can be NULL.
flags SDL_GLOB_* bitflags that affect this search.
count on return, will be set to the number of items in the returned array. Can be NULL.
Returns
an array of strings on success or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    //SDL_Log("SDL_GlobDirectory('%s', '%s') ...", path, pattern);
    return SDL_InternalGlobDirectory(path, pattern, flags, count, GlobDirectoryEnumerator, GlobDirectoryGetPathInfo, NULL);
}
References count, GlobDirectoryEnumerator(), GlobDirectoryGetPathInfo(), NULL, and SDL_InternalGlobDirectory().
SDL_InitFilesystem()
void SDL_InitFilesystem (void)
{
}
Referenced by SDL_InitMainThread().
SDL_InternalGlobDirectory()
char ** SDL_InternalGlobDirectory (const char * path, const char * pattern, SDL_GlobFlags flags, int * count, SDL_GlobEnumeratorFunc enumerator, SDL_GlobGetPathInfoFunc getpathinfo, void * userdata)
{
    int dummycount;
    if (!count) {
        count = &dummycount;
    }
    *count = 0;
    if (!path) {
        SDL_InvalidParamError("path");
        return NULL;
    }
    // if path ends with any slash, chop them off, so we don't confuse the pattern matcher later.
    char *pathcpy = NULL;
    size_t pathlen = SDL_strlen(path);
    if ((pathlen > 1) && ((path[pathlen-1] == '/') || (path[pathlen-1] == '\\'))) {
        pathcpy = SDL_strdup(path);
        if (!pathcpy) {
            return NULL;
        }
        char *ptr = &pathcpy[pathlen-1];
        while ((ptr >= pathcpy) && ((*ptr == '/') || (*ptr == '\\'))) {
            *(ptr--) = '\0';
        }
        path = pathcpy;
    }
    if (!pattern) {
        flags &= ~SDL_GLOB_CASEINSENSITIVE;  // avoid some unnecessary allocations and work later.
    }
    char *folded = NULL;
    if (flags & SDL_GLOB_CASEINSENSITIVE) {
        SDL_assert(pattern != NULL);
        folded = CaseFoldUtf8String(pattern);
        if (!folded) {
            SDL_free(pathcpy);
            return NULL;
        }
    }
    GlobDirCallbackData data;
    SDL_zero(data);
    data.string_stream = SDL_IOFromDynamicMem();
    if (!data.string_stream) {
        SDL_free(folded);
        SDL_free(pathcpy);
        return NULL;
    }
    if (!pattern) {
        data.matcher = EverythingMatch;  // no pattern? Everything matches.
    // !!! FIXME
    //} else if (flags & SDL_GLOB_GITIGNORE) {
    //    data.matcher = GitIgnoreMatch;
    } else {
        data.matcher = WildcardMatch;
    }
    data.pattern = folded ? folded : pattern;
    data.flags = flags;
    data.enumerator = enumerator;
    data.getpathinfo = getpathinfo;
    data.fsuserdata = userdata;
    data.basedirlen = *path ? (SDL_strlen(path) + 1) : 0;  // +1 for the '/' we'll be adding.
    char **result = NULL;
    if (data.enumerator(path, GlobDirectoryCallback, &data, data.fsuserdata)) {
        const size_t streamlen = (size_t) SDL_GetIOSize(data.string_stream);
        const size_t buflen = streamlen + ((data.num_entries + 1) * sizeof (char *));  // +1 for NULL terminator at end of array.
        result = (char **) SDL_malloc(buflen);
        if (result) {
            if (data.num_entries > 0) {
                Sint64 iorc = SDL_SeekIO(data.string_stream, 0, SDL_IO_SEEK_SET);
                SDL_assert(iorc == 0);  // this should never fail for a memory stream!
                char *ptr = (char *) (result + (data.num_entries + 1));
                iorc = SDL_ReadIO(data.string_stream, ptr, streamlen);
                SDL_assert(iorc == (Sint64) streamlen);  // this should never fail for a memory stream!
                for (int i = 0; i < data.num_entries; i++) {
                    result[i] = ptr;
                    ptr += SDL_strlen(ptr) + 1;
                }
            }
            result[data.num_entries] = NULL;  // NULL terminate the list.
            *count = data.num_entries;
        }
    }
    SDL_CloseIO(data.string_stream);
    SDL_free(folded);
    SDL_free(pathcpy);
    return result;
}
References CaseFoldUtf8String(), count, EverythingMatch(), GlobDirectoryCallback(), NULL, SDL_assert, SDL_CloseIO(), SDL_free(), SDL_GetIOSize(), SDL_GLOB_CASEINSENSITIVE, SDL_InvalidParamError, SDL_IO_SEEK_SET, SDL_IOFromDynamicMem(), SDL_malloc(), SDL_ReadIO(), SDL_SeekIO(), SDL_strdup(), SDL_strlen(), SDL_zero, and WildcardMatch().
Referenced by SDL_GlobDirectory(), and SDL_GlobStorageDirectory().
SDL_QuitFilesystem()
void SDL_QuitFilesystem (void)
{
    if (CachedBasePath) {
        SDL_free(CachedBasePath);
        CachedBasePath = NULL;
    }
    for (int i = 0; i < SDL_arraysize(CachedUserFolders); i++) {
        if (CachedUserFolders[i]) {
            SDL_free(CachedUserFolders[i]);
            CachedUserFolders[i] = NULL;
        }
    }
}
References CachedBasePath, CachedUserFolders, NULL, SDL_arraysize, and SDL_free().
Referenced by SDL_QuitMainThread().
SDL_RemovePath()
bool SDL_RemovePath (const char * path)
Remove a file or an empty directory.
Directories that are not empty will fail; this function will not recursely delete directory trees.
Parameters
path the path to remove from the filesystem.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    if (!path) {
        return SDL_InvalidParamError("path");
    }
    return SDL_SYS_RemovePath(path);
}
References SDL_InvalidParamError, and SDL_SYS_RemovePath().
Referenced by GENERIC_RemoveStoragePath(), SDL_DestroyTray(), and SDL_SetTrayIcon().
SDL_RenamePath()
bool SDL_RenamePath (const char * oldpath, const char * newpath)
Rename a file or directory.
If the file at newpath already exists, it will replaced.
Note that this will not copy files across filesystems/drives/volumes, as that is a much more complicated (and possibly time-consuming) operation.
Which is to say, if this function fails, SDL_CopyFile() to a temporary file in the same directory as newpath, then SDL_RenamePath() from the temporary file to newpath and SDL_RemovePath() on oldpath might work for files. Renaming a non-empty directory across filesystems is dramatically more complex, however.
Parameters
oldpath the old path.
newpath the new path.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    if (!oldpath) {
        return SDL_InvalidParamError("oldpath");
    } else if (!newpath) {
        return SDL_InvalidParamError("newpath");
    }
    return SDL_SYS_RenamePath(oldpath, newpath);
}
References SDL_InvalidParamError, and SDL_SYS_RenamePath().
Referenced by GENERIC_RenameStoragePath().
WildcardMatch()
bool WildcardMatch (const char * pattern, const char * str, bool * matched_to_dir) static
{
    SDL_assert(pattern != NULL);
    SDL_assert(str != NULL);
    SDL_assert(matched_to_dir != NULL);
    const char *str_backtrack = NULL;
    const char *pattern_backtrack = NULL;
    char sch_backtrack = 0;
    char sch = *str;
    char pch = *pattern;
    while (sch) {
        if (pch == '*') {
            str_backtrack = str;
            pattern_backtrack = ++pattern;
            sch_backtrack = sch;
            pch = *pattern;
        } else if (pch == sch) {
            if (pch == '/') {
                str_backtrack = pattern_backtrack = NULL;
            }
            sch = *(++str);
            pch = *(++pattern);
        } else if ((pch == '?') && (sch != '/')) {  // end of string (checked at `while`) or path separator do not match '?'.
            sch = *(++str);
            pch = *(++pattern);
        } else if (!pattern_backtrack || (sch_backtrack == '/')) { // we didn't have a match. Are we in a '*' and NOT on a path separator? Keep going. Otherwise, fail.
            *matched_to_dir = false;
            return false;
        } else {  // still here? Wasn't a match, but we're definitely in a '*' pattern.
            str = ++str_backtrack;
            pattern = pattern_backtrack;
            sch_backtrack = sch;
            sch = *str;
            pch = *pattern;
        }
        #ifdef SDL_PLATFORM_WINDOWS
        if (sch == '\\') {
            sch = '/';
        }
        #endif
    }
    // '*' at the end can be ignored, they are allowed to match nothing.
    while (pch == '*') {
        pch = *(++pattern);
    }
    *matched_to_dir = ((pch == '/') || (pch == '\0'));  // end of string and the pattern is complete or failed at a '/'? We should descend into this directory.
    return (pch == '\0');  // survived the whole pattern? That's a match!
}
References NULL, and SDL_assert.
Referenced by SDL_InternalGlobDirectory().
Variable Documentation
CachedBasePath
char* CachedBasePath = NULL static
Referenced by SDL_GetBasePath(), and SDL_QuitFilesystem().
CachedUserFolders
char* CachedUserFolders[SDL_FOLDER_COUNT] static
Referenced by SDL_GetUserFolder(), and SDL_QuitFilesystem().