SDL3: SDL-main/src/thread/SDL_thread_c.h File Reference
SDL_thread_c.h File Reference
#include "SDL_internal.h"
#include "generic/SDL_systhread_c.h"
#include "../SDL_error_c.h"
Data Structures
struct SDL_Thread
struct SDL_TLSData
Macros
#define TLS_ALLOC_CHUNKSIZE 4
Functions
SDL_TLSData * SDL_Generic_GetTLSData (void)
void SDL_Generic_InitTLSData (void)
void SDL_Generic_QuitTLSData (void)
bool SDL_Generic_SetTLSData (SDL_TLSData *data)
void SDL_InitTLSData (void)
void SDL_QuitTLSData (void)
void SDL_RunThread (SDL_Thread *thread)
Macro Definition Documentation
TLS_ALLOC_CHUNKSIZE
#define TLS_ALLOC_CHUNKSIZE 4
Referenced by SDL_SetTLS().
Function Documentation
SDL_Generic_GetTLSData()
SDL_TLSData * SDL_Generic_GetTLSData (void) extern
{
    SDL_ThreadID thread = SDL_GetCurrentThreadID();
    SDL_TLSEntry *entry;
    SDL_TLSData *storage = NULL;
    SDL_LockMutex(SDL_generic_TLS_mutex);
    for (entry = SDL_generic_TLS; entry; entry = entry->next) {
        if (entry->thread == thread) {
            storage = entry->storage;
            break;
        }
    }
    SDL_UnlockMutex(SDL_generic_TLS_mutex);
    return storage;
}
References SDL_TLSEntry::next, NULL, SDL_generic_TLS, SDL_generic_TLS_mutex, SDL_GetCurrentThreadID(), SDL_LockMutex(), SDL_UnlockMutex(), SDL_TLSEntry::storage, and SDL_TLSEntry::thread.
Referenced by SDL_SYS_GetTLSData().
SDL_Generic_InitTLSData()
void SDL_Generic_InitTLSData (void) extern
{
    if (!SDL_generic_TLS_mutex) {
        SDL_generic_TLS_mutex = SDL_CreateMutex();
    }
}
References SDL_CreateMutex(), and SDL_generic_TLS_mutex.
Referenced by SDL_SYS_InitTLSData().
SDL_Generic_QuitTLSData()
void SDL_Generic_QuitTLSData (void) extern
{
    SDL_TLSEntry *entry;
    // This should have been cleaned up by the time we get here
    SDL_assert(!SDL_generic_TLS);
    if (SDL_generic_TLS) {
        SDL_LockMutex(SDL_generic_TLS_mutex);
        for (entry = SDL_generic_TLS; entry; ) {
            SDL_TLSEntry *next = entry->next;
            SDL_free(entry->storage);
            SDL_free(entry);
            entry = next;
        }
        SDL_generic_TLS = NULL;
        SDL_UnlockMutex(SDL_generic_TLS_mutex);
    }
    if (SDL_generic_TLS_mutex) {
        SDL_DestroyMutex(SDL_generic_TLS_mutex);
        SDL_generic_TLS_mutex = NULL;
    }
}
References SDL_TLSEntry::next, NULL, SDL_assert, SDL_DestroyMutex(), SDL_free(), SDL_generic_TLS, SDL_generic_TLS_mutex, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_TLSEntry::storage.
Referenced by SDL_SYS_QuitTLSData().
SDL_Generic_SetTLSData()
bool SDL_Generic_SetTLSData (SDL_TLSData * data) extern
{
    SDL_ThreadID thread = SDL_GetCurrentThreadID();
    SDL_TLSEntry *prev, *entry;
    bool result = true;
    SDL_LockMutex(SDL_generic_TLS_mutex);
    prev = NULL;
    for (entry = SDL_generic_TLS; entry; entry = entry->next) {
        if (entry->thread == thread) {
            if (data) {
                entry->storage = data;
            } else {
                if (prev) {
                    prev->next = entry->next;
                } else {
                    SDL_generic_TLS = entry->next;
                }
                SDL_free(entry);
            }
            break;
        }
        prev = entry;
    }
    if (!entry && data) {
        entry = (SDL_TLSEntry *)SDL_malloc(sizeof(*entry));
        if (entry) {
            entry->thread = thread;
            entry->storage = data;
            entry->next = SDL_generic_TLS;
            SDL_generic_TLS = entry;
        } else {
            result = false;
        }
    }
    SDL_UnlockMutex(SDL_generic_TLS_mutex);
    return result;
}
References SDL_TLSEntry::next, NULL, SDL_free(), SDL_generic_TLS, SDL_generic_TLS_mutex, SDL_GetCurrentThreadID(), SDL_LockMutex(), SDL_malloc(), SDL_UnlockMutex(), SDL_TLSEntry::storage, and SDL_TLSEntry::thread.
Referenced by SDL_SYS_SetTLSData().
SDL_InitTLSData()
void SDL_InitTLSData (void) extern
{
    SDL_SYS_InitTLSData();
}
References SDL_SYS_InitTLSData().
Referenced by SDL_InitMainThread(), and SDL_SetTLS().
SDL_QuitTLSData()
void SDL_QuitTLSData (void) extern
{
    SDL_CleanupTLS();
    if (SDL_GetAtomicInt(&SDL_tls_allocated) == 0) {
        SDL_SYS_QuitTLSData();
    } else {
        // Some thread hasn't called SDL_CleanupTLS()
    }
}
References SDL_CleanupTLS(), SDL_GetAtomicInt(), SDL_SYS_QuitTLSData(), and SDL_tls_allocated.
Referenced by SDL_QuitMainThread().
SDL_RunThread()
void SDL_RunThread (SDL_Thread * thread) extern
{
    void *userdata = thread->userdata;
    int(SDLCALL *userfunc)(void *) = thread->userfunc;
    int *statusloc = &thread->status;
    // Perform any system-dependent setup - this function may not fail
    SDL_SYS_SetupThread(thread->name);
    // Get the thread id
    thread->threadid = SDL_GetCurrentThreadID();
    // Run the function
    *statusloc = userfunc(userdata);
    // Clean up thread-local storage
    SDL_CleanupTLS();
    // Mark us as ready to be joined (or detached)
    if (!SDL_CompareAndSwapAtomicInt(&thread->state, SDL_THREAD_ALIVE, SDL_THREAD_COMPLETE)) {
        // Clean up if something already detached us.
        if (SDL_GetThreadState(thread) == SDL_THREAD_DETACHED) {
            SDL_free(thread->name); // Can't free later, we've already cleaned up TLS
            SDL_free(thread);
        }
    }
}
References SDL_CleanupTLS(), SDL_CompareAndSwapAtomicInt(), SDL_free(), SDL_GetCurrentThreadID(), SDL_GetThreadState(), SDL_SYS_SetupThread(), SDL_THREAD_ALIVE, SDL_THREAD_COMPLETE, SDL_THREAD_DETACHED, SDLCALL, and SDL_TLSEntry::thread.
Referenced by RunThread().