SDL3: SDL-main/src/filesystem/SDL_sysfilesystem.h File Reference
SDL_sysfilesystem.h File Reference
Typedefs
typedef bool(* SDL_GlobEnumeratorFunc) (const char *path, SDL_EnumerateDirectoryCallback cb, void *cbuserdata, void *userdata)
typedef bool(* SDL_GlobGetPathInfoFunc) (const char *path, SDL_PathInfo *info, void *userdata)
Functions
char ** SDL_InternalGlobDirectory (const char *path, const char *pattern, SDL_GlobFlags flags, int *count, SDL_GlobEnumeratorFunc enumerator, SDL_GlobGetPathInfoFunc getpathinfo, void *userdata)
bool SDL_SYS_CopyFile (const char *oldpath, const char *newpath)
bool SDL_SYS_CreateDirectory (const char *path)
bool SDL_SYS_EnumerateDirectory (const char *path, SDL_EnumerateDirectoryCallback cb, void *userdata)
char * SDL_SYS_GetBasePath (void)
char * SDL_SYS_GetCurrentDirectory (void)
bool SDL_SYS_GetPathInfo (const char *path, SDL_PathInfo *info)
char * SDL_SYS_GetPrefPath (const char *org, const char *app)
char * SDL_SYS_GetUserFolder (SDL_Folder folder)
bool SDL_SYS_RemovePath (const char *path)
bool SDL_SYS_RenamePath (const char *oldpath, const char *newpath)
Typedef Documentation
SDL_GlobEnumeratorFunc
typedef bool(* SDL_GlobEnumeratorFunc) (const char *path, SDL_EnumerateDirectoryCallback cb, void *cbuserdata, void *userdata)
SDL_GlobGetPathInfoFunc
typedef bool(* SDL_GlobGetPathInfoFunc) (const char *path, SDL_PathInfo *info, void *userdata)
Function Documentation
SDL_InternalGlobDirectory()
char ** SDL_InternalGlobDirectory (const char * path, const char * pattern, SDL_GlobFlags flags, int * count, SDL_GlobEnumeratorFunc enumerator, SDL_GlobGetPathInfoFunc getpathinfo, void * userdata) extern
{
    int dummycount;
    if (!count) {
        count = &dummycount;
    }
    *count = 0;
    if (!path) {
        SDL_InvalidParamError("path");
        return NULL;
    }
    // if path ends with any slash, chop them off, so we don't confuse the pattern matcher later.
    char *pathcpy = NULL;
    size_t pathlen = SDL_strlen(path);
    if ((pathlen > 1) && ((path[pathlen-1] == '/') || (path[pathlen-1] == '\\'))) {
        pathcpy = SDL_strdup(path);
        if (!pathcpy) {
            return NULL;
        }
        char *ptr = &pathcpy[pathlen-1];
        while ((ptr >= pathcpy) && ((*ptr == '/') || (*ptr == '\\'))) {
            *(ptr--) = '\0';
        }
        path = pathcpy;
    }
    if (!pattern) {
        flags &= ~SDL_GLOB_CASEINSENSITIVE;  // avoid some unnecessary allocations and work later.
    }
    char *folded = NULL;
    if (flags & SDL_GLOB_CASEINSENSITIVE) {
        SDL_assert(pattern != NULL);
        folded = CaseFoldUtf8String(pattern);
        if (!folded) {
            SDL_free(pathcpy);
            return NULL;
        }
    }
    GlobDirCallbackData data;
    SDL_zero(data);
    data.string_stream = SDL_IOFromDynamicMem();
    if (!data.string_stream) {
        SDL_free(folded);
        SDL_free(pathcpy);
        return NULL;
    }
    if (!pattern) {
        data.matcher = EverythingMatch;  // no pattern? Everything matches.
    // !!! FIXME
    //} else if (flags & SDL_GLOB_GITIGNORE) {
    //    data.matcher = GitIgnoreMatch;
    } else {
        data.matcher = WildcardMatch;
    }
    data.pattern = folded ? folded : pattern;
    data.flags = flags;
    data.enumerator = enumerator;
    data.getpathinfo = getpathinfo;
    data.fsuserdata = userdata;
    data.basedirlen = *path ? (SDL_strlen(path) + 1) : 0;  // +1 for the '/' we'll be adding.
    char **result = NULL;
    if (data.enumerator(path, GlobDirectoryCallback, &data, data.fsuserdata)) {
        const size_t streamlen = (size_t) SDL_GetIOSize(data.string_stream);
        const size_t buflen = streamlen + ((data.num_entries + 1) * sizeof (char *));  // +1 for NULL terminator at end of array.
        result = (char **) SDL_malloc(buflen);
        if (result) {
            if (data.num_entries > 0) {
                Sint64 iorc = SDL_SeekIO(data.string_stream, 0, SDL_IO_SEEK_SET);
                SDL_assert(iorc == 0);  // this should never fail for a memory stream!
                char *ptr = (char *) (result + (data.num_entries + 1));
                iorc = SDL_ReadIO(data.string_stream, ptr, streamlen);
                SDL_assert(iorc == (Sint64) streamlen);  // this should never fail for a memory stream!
                for (int i = 0; i < data.num_entries; i++) {
                    result[i] = ptr;
                    ptr += SDL_strlen(ptr) + 1;
                }
            }
            result[data.num_entries] = NULL;  // NULL terminate the list.
            *count = data.num_entries;
        }
    }
    SDL_CloseIO(data.string_stream);
    SDL_free(folded);
    SDL_free(pathcpy);
    return result;
}
References CaseFoldUtf8String(), count, EverythingMatch(), GlobDirectoryCallback(), NULL, SDL_assert, SDL_CloseIO(), SDL_free(), SDL_GetIOSize(), SDL_GLOB_CASEINSENSITIVE, SDL_InvalidParamError, SDL_IO_SEEK_SET, SDL_IOFromDynamicMem(), SDL_malloc(), SDL_ReadIO(), SDL_SeekIO(), SDL_strdup(), SDL_strlen(), SDL_zero, and WildcardMatch().
Referenced by SDL_GlobDirectory(), and SDL_GlobStorageDirectory().
SDL_SYS_CopyFile()
bool SDL_SYS_CopyFile (const char * oldpath, const char * newpath) extern
Referenced by SDL_CopyFile().
SDL_SYS_CreateDirectory()
bool SDL_SYS_CreateDirectory (const char * path) extern
Referenced by SDL_CreateDirectory().
SDL_SYS_EnumerateDirectory()
bool SDL_SYS_EnumerateDirectory (const char * path, SDL_EnumerateDirectoryCallback cb, void * userdata) extern
Referenced by SDL_EnumerateDirectory().
SDL_SYS_GetBasePath()
char * SDL_SYS_GetBasePath (void) extern
{
    /* NOTE: This function is a UTF8 version of the Win32 SDL_GetBasePath()!
     * The GDK actually _recommends_ the 'A' functions over the 'W' functions :o
     */
    DWORD buflen = 128;
    CHAR *path = NULL;
    DWORD len = 0;
    int i;
    while (true) {
        void *ptr = SDL_realloc(path, buflen * sizeof(CHAR));
        if (!ptr) {
            SDL_free(path);
            return NULL;
        }
        path = (CHAR *)ptr;
        len = GetModuleFileNameA(NULL, path, buflen);
        // if it truncated, then len >= buflen - 1
        // if there was enough room (or failure), len < buflen - 1
        if (len < buflen - 1) {
            break;
        }
        // buffer too small? Try again.
        buflen *= 2;
    }
    if (len == 0) {
        SDL_free(path);
        WIN_SetError("Couldn't locate our .exe");
        return NULL;
    }
    for (i = len - 1; i > 0; i--) {
        if (path[i] == '\\') {
            break;
        }
    }
    SDL_assert(i > 0);  // Should have been an absolute path.
    path[i + 1] = '\0'; // chop off filename.
    return path;
}
References NGAGE_GetAppPath(), NULL, SDL_assert, SDL_free(), SDL_realloc(), SDL_strdup(), and WIN_SetError().
Referenced by SDL_GetBasePath().
SDL_SYS_GetCurrentDirectory()
char * SDL_SYS_GetCurrentDirectory (void) extern
{
    SDL_Unsupported();
    return NULL;
}
References NULL, and SDL_Unsupported.
Referenced by SDL_GetCurrentDirectory().
SDL_SYS_GetPathInfo()
bool SDL_SYS_GetPathInfo (const char * path, SDL_PathInfo * info) extern
Referenced by SDL_GetPathInfo().
SDL_SYS_GetPrefPath()
char * SDL_SYS_GetPrefPath (const char * org, const char * app) extern
{
    XUserHandle user = NULL;
    XAsyncBlock block = { 0 };
    char *folderPath;
    HRESULT result;
    const char *csid = SDL_GetHint("SDL_GDK_SERVICE_CONFIGURATION_ID");
    // This should be set before calling SDL_GetPrefPath!
    if (!csid) {
        SDL_LogWarn(SDL_LOG_CATEGORY_SYSTEM, "Set SDL_GDK_SERVICE_CONFIGURATION_ID before calling SDL_GetPrefPath!");
        return SDL_strdup("T:\\");
    }
    if (!SDL_GetGDKDefaultUser(&user)) {
        // Error already set, just return
        return NULL;
    }
    if (FAILED(result = XGameSaveFilesGetFolderWithUiAsync(user, csid, &block))) {
        WIN_SetErrorFromHRESULT("XGameSaveFilesGetFolderWithUiAsync", result);
        return NULL;
    }
    folderPath = (char *)SDL_malloc(MAX_PATH);
    do {
        result = XGameSaveFilesGetFolderWithUiResult(&block, MAX_PATH, folderPath);
    } while (result == E_PENDING);
    if (FAILED(result)) {
        WIN_SetErrorFromHRESULT("XGameSaveFilesGetFolderWithUiResult", result);
        SDL_free(folderPath);
        return NULL;
    }
    /* We aren't using 'app' here because the container rules are a lot more
     * strict than the NTFS rules, so it will most likely be invalid :(
     */
    SDL_strlcat(folderPath, "\\SDLPrefPath\\", MAX_PATH);
    if (CreateDirectoryA(folderPath, NULL) == FALSE) {
        if (GetLastError() != ERROR_ALREADY_EXISTS) {
            WIN_SetError("CreateDirectoryA");
            SDL_free(folderPath);
            return NULL;
        }
    }
    return folderPath;
}
References FAILED, FALSE, NULL, SDL_asprintf(), SDL_free(), SDL_GetGDKDefaultUser(), SDL_GetHint(), SDL_LOG_CATEGORY_SYSTEM, SDL_LogWarn(), SDL_malloc(), SDL_strdup(), SDL_strlcat(), WIN_SetError(), and WIN_SetErrorFromHRESULT().
Referenced by SDL_GetPrefPath().
SDL_SYS_GetUserFolder()
char * SDL_SYS_GetUserFolder (SDL_Folder folder) extern
{
    SDL_Unsupported();
    return NULL;
}
References NULL, SDL_FOLDER_HOME, SDL_FOLDER_PICTURES, SDL_FOLDER_SAVEDGAMES, SDL_FOLDER_SCREENSHOTS, SDL_FOLDER_VIDEOS, SDL_strdup(), and SDL_Unsupported.
Referenced by SDL_GetUserFolder().
SDL_SYS_RemovePath()
bool SDL_SYS_RemovePath (const char * path) extern
Referenced by SDL_RemovePath().
SDL_SYS_RenamePath()
bool SDL_SYS_RenamePath (const char * oldpath, const char * newpath) extern
Referenced by SDL_RenamePath().