SDL3: SDL-main/include/SDL3/SDL_main.h File Reference
SDL_main.h File Reference
#include <SDL3/SDL_platform_defines.h>
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_events.h>
#include <SDL3/SDL_init.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
#define SDLMAIN_DECLSPEC
Typedefs
typedef int(SDLCALL * SDL_main_func) (int argc, char *argv[])
Functions
SDL_DECLSPEC int SDLCALL SDL_EnterAppMainCallbacks (int argc, char *argv[], SDL_AppInit_func appinit, SDL_AppIterate_func appiter, SDL_AppEvent_func appevent, SDL_AppQuit_func appquit)
SDL_DECLSPEC void SDLCALL SDL_GDKSuspendComplete (void)
int SDLCALL SDL_main (int argc, char *argv[])
SDL_DECLSPEC int SDLCALL SDL_RunApp (int argc, char *argv[], SDL_main_func mainFunction, void *reserved)
SDL_DECLSPEC void SDLCALL SDL_SetMainReady (void)
Macro Definition Documentation
SDLMAIN_DECLSPEC
#define SDLMAIN_DECLSPEC
CategoryMain
Redefine main() if necessary so that it is called by SDL.
In order to make this consistent on all platforms, the application's main() should look like this:
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
int main(int argc, char *argv[])
{
}
SDL will take care of platform specific details on how it gets called.
This is also where an app can be configured to use the main callbacks, via the SDL_MAIN_USE_CALLBACKS macro.
SDL_main.h is a "single-header library," which is to say that including this header inserts code into your program, and you should only include it once in most cases. SDL.h does not include this header automatically.
For more information, see:
https://wiki.libsdl.org/SDL3/README-main-functions
Referenced by SDL_main().
Typedef Documentation
SDL_main_func
typedef int(SDLCALL * SDL_main_func) (int argc, char *argv[])
The prototype for the application's main() function
Parameters
argc an ANSI-C style main function's argc.
argv an ANSI-C style main function's argv.
Returns
an ANSI-C main return code; generally 0 is considered successful program completion, and small non-zero values are considered errors.
Since
This datatype is available since SDL 3.2.0.
Function Documentation
SDL_EnterAppMainCallbacks()
SDL_DECLSPEC int SDLCALL SDL_EnterAppMainCallbacks (int argc, char * argv[], SDL_AppInit_func appinit, SDL_AppIterate_func appiter, SDL_AppEvent_func appevent, SDL_AppQuit_func appquit) extern
An entry point for SDL's use in SDL_MAIN_USE_CALLBACKS.
Generally, you should not call this function directly. This only exists to hand off work into SDL as soon as possible, where it has a lot more control and functionality available, and make the inline code in SDL_main.h as small as possible.
Not all platforms use this, it's actual use is hidden in a magic header-only library, and you should not call this directly unless you really know what you're doing.
Parameters
argc standard Unix main argc.
argv standard Unix main argv.
appinit the application's SDL_AppInit function.
appiter the application's SDL_AppIterate function.
appevent the application's SDL_AppEvent function.
appquit the application's SDL_AppQuit function.
Returns
standard Unix main return value.
Thread Safety
It is not safe to call this anywhere except as the only function call in SDL_main.
Since
This function is available since SDL 3.2.0.
{
    SDL_AppResult rc = SDL_InitMainCallbacks(argc, argv, appinit, appiter, appevent, appquit);
    if (rc == SDL_APP_CONTINUE) {
        if (!SDL_AddEventWatch(EmscriptenMainCallbackEventWatcher, NULL)) {
            rc = SDL_APP_FAILURE;
        } else {
            SDL_AddHintCallback(SDL_HINT_MAIN_CALLBACK_RATE, MainCallbackRateHintChanged, NULL);
            callback_rate_changed = false;
            emscripten_set_main_loop(EmscriptenInternalMainloop, 0, 0);  // don't throw an exception since we do an orderly return.
            if (callback_rate_increment > 0.0) {
                emscripten_set_main_loop_timing(EM_TIMING_SETTIMEOUT, callback_rate_increment);
            }
        }
    } else {
        SDL_QuitMainCallbacks(rc);
    }
    return (rc == SDL_APP_FAILURE) ? 1 : 0;
}
References callback_rate_changed, callback_rate_increment, EmscriptenInternalMainloop(), EmscriptenMainCallbackEventWatcher(), GenericIterateMainCallbacks(), MainCallbackRateHintChanged(), NULL, SDL_AddEventWatch(), SDL_AddHintCallback(), SDL_APP_CONTINUE, SDL_APP_FAILURE, SDL_DelayPrecise(), SDL_GetTicksNS(), SDL_HINT_MAIN_CALLBACK_RATE, SDL_InitMainCallbacks(), SDL_QuitMainCallbacks(), and SDL_RemoveHintCallback().
SDL_GDKSuspendComplete()
void SDL_GDKSuspendComplete (void) extern
Callback from the application to let the suspend continue.
This function is only needed for Xbox GDK support; all other platforms will do nothing and set an "unsupported" error message.
Since
This function is available since SDL 3.2.0.
{
    SDL_Unsupported();
}
References plmSuspendComplete, and SDL_Unsupported.
SDL_main()
int SDLCALL SDL_main (int argc, char * argv[]) extern
An app-supplied function for program entry.
Apps do not directly create this function; they should create a standard ANSI-C main function instead. If SDL needs to insert some startup code before main runs, or the platform doesn't actually use a function called "main", SDL will do some macro magic to redefine main to SDL_main and provide its own main.
Apps should include SDL_main.h in the same file as their main function, and they should not use that symbol for anything else in that file, as it might get redefined.
This function is only provided by the app if it isn't using SDL_MAIN_USE_CALLBACKS.
Program startup is a surprisingly complex topic. Please see [README-main-functions](README-main-functions), (or docs/README-main-functions.md in the source tree) for a more detailed explanation.
Parameters
argc an ANSI-C style main function's argc.
argv an ANSI-C style main function's argv.
Returns
an ANSI-C main return code; generally 0 is considered successful program completion, and small non-zero values are considered errors.
Thread Safety
This is the program entry point.
Since
This function is available since SDL 3.2.0.
References SDL_DECLSPEC, SDLCALL, and SDLMAIN_DECLSPEC.
Referenced by main().
SDL_RunApp()
SDL_DECLSPEC int SDLCALL SDL_RunApp (int argc, char * argv[], SDL_main_func mainFunction, void * reserved) extern
Initializes and launches an SDL application, by doing platform-specific initialization before calling your mainFunction and cleanups after it returns, if that is needed for a specific platform, otherwise it just calls mainFunction.
You can use this if you want to use your own main() implementation without using SDL_main (like when using SDL_MAIN_HANDLED). When using this, you do not need SDL_SetMainReady().
Parameters
argc the argc parameter from the application's main() function, or 0 if the platform's main-equivalent has no argc.
argv the argv parameter from the application's main() function, or NULL if the platform's main-equivalent has no argv.
mainFunction your SDL app's C-style main(). NOT the function you're calling this from! Its name doesn't matter; it doesn't literally have to be main.
reserved should be NULL (reserved for future use, will probably be platform-specific then).
Returns
the return value from mainFunction: 0 on success, otherwise failure; SDL_GetError() might have more information on the failure.
Thread Safety
Generally this is called once, near startup, from the process's initial thread.
Since
This function is available since SDL 3.2.0.
{
    (void)reserved;
    if(!argv)
    {
        // make sure argv isn't NULL, in case some user code doesn't like that
        static char dummyargv0[] = { 'S', 'D', 'L', '_', 'a', 'p', 'p', '\0' };
        static char *argvdummy[2] = { dummyargv0, NULL };
        argc = 1;
        argv = argvdummy;
    }
    return mainFunction(argc, argv);
}
References NULL, and void().
Referenced by main().
SDL_SetMainReady()
SDL_DECLSPEC void SDLCALL SDL_SetMainReady (void) extern
Circumvent failure of SDL_Init() when not using SDL_main() as an entry point.
This function is defined in SDL_main.h, along with the preprocessor rule to redefine main() as SDL_main(). Thus to ensure that your main() function will not be changed it is necessary to define SDL_MAIN_HANDLED before including SDL.h.
Since
This function is available since SDL 3.2.0.
See also
SDL_Init
{
    SDL_MainIsReady = true;
    if (SDL_MainThreadID == 0) {
        SDL_MainThreadID = SDL_GetCurrentThreadID();
    }
}
References SDL_GetCurrentThreadID(), SDL_MainIsReady, and SDL_MainThreadID.
Referenced by CSDLmain::RunL(), and SDL_RunApp().