SDL3: SDL-main/src/audio/SDL_audioresample.h File Reference
SDL_audioresample.h File Reference
#include "SDL_internal.h"
Functions
Sint64 SDL_GetResampleRate (int src_rate, int dst_rate)
int SDL_GetResamplerHistoryFrames (void)
Sint64 SDL_GetResamplerInputFrames (Sint64 output_frames, Sint64 resample_rate, Sint64 resample_offset)
Sint64 SDL_GetResamplerOutputFrames (Sint64 input_frames, Sint64 resample_rate, Sint64 *inout_resample_offset)
int SDL_GetResamplerPaddingFrames (Sint64 resample_rate)
void SDL_ResampleAudio (int chans, const float *src, int inframes, float *dst, int outframes, Sint64 resample_rate, Sint64 *inout_resample_offset)
Function Documentation
SDL_GetResampleRate()
Sint64 SDL_GetResampleRate (int src_rate, int dst_rate)
{
    SDL_assert(src_rate > 0);
    SDL_assert(dst_rate > 0);
    Sint64 numerator = (Sint64)src_rate << 32;
    Sint64 denominator = (Sint64)dst_rate;
    // Generally it's expected that `dst_frames = (src_frames * dst_rate) / src_rate`
    // To match this as closely as possible without infinite precision, always round up the resample rate.
    // For example, without rounding up, a sample ratio of 2:3 would have `sample_rate = 0xAAAAAAAA`
    // After 3 frames, the position would be 0x1.FFFFFFFE, meaning we haven't fully consumed the second input frame.
    // By rounding up to 0xAAAAAAAB, we would instead reach 0x2.00000001, fulling consuming the second frame.
    // Technically you could say this is kicking the can 0x100000000 steps down the road, but I'm fine with that :)
    // sample_rate = div_ceil(numerator, denominator)
    Sint64 sample_rate = ((numerator - 1) / denominator) + 1;
    SDL_assert(sample_rate > 0);
    return sample_rate;
}
References SDL_assert.
Referenced by GetAudioStreamResampleRate().
SDL_GetResamplerHistoryFrames()
int SDL_GetResamplerHistoryFrames (void)
{
    // Even if we aren't currently resampling, make sure to keep enough history in case we need to later.
    return RESAMPLER_MAX_PADDING_FRAMES;
}
References RESAMPLER_MAX_PADDING_FRAMES.
Referenced by UpdateAudioStreamInputSpec().
SDL_GetResamplerInputFrames()
Sint64 SDL_GetResamplerInputFrames (Sint64 output_frames, Sint64 resample_rate, Sint64 resample_offset)
{
    // Calculate the index of the last input frame, then add 1.
    // ((((output_frames - 1) * resample_rate) + resample_offset) >> 32) + 1
    Sint64 output_offset;
    if (!ResamplerMul(output_frames, resample_rate, &output_offset) ||
        !ResamplerAdd(output_offset, -resample_rate + resample_offset + 0x100000000, &output_offset)) {
        output_offset = SDL_MAX_SINT64;
    }
    Sint64 input_frames = (Sint64)(Sint32)(output_offset >> 32);
    input_frames = SDL_max(input_frames, 0);
    return input_frames;
}
References ResamplerAdd(), ResamplerMul(), SDL_max, and SDL_MAX_SINT64.
Referenced by GetAudioStreamDataInternal(), and SDL_GetAudioStreamDataAdjustGain().
SDL_GetResamplerOutputFrames()
Sint64 SDL_GetResamplerOutputFrames (Sint64 input_frames, Sint64 resample_rate, Sint64 * inout_resample_offset)
{
    Sint64 resample_offset = *inout_resample_offset;
    // input_offset = (input_frames << 32) - resample_offset;
    Sint64 input_offset;
    if (!ResamplerMul(input_frames, 0x100000000, &input_offset) ||
        !ResamplerAdd(input_offset, -resample_offset, &input_offset)) {
        input_offset = SDL_MAX_SINT64;
    }
    // output_frames = div_ceil(input_offset, resample_rate)
    Sint64 output_frames = (input_offset > 0) ? ((input_offset - 1) / resample_rate) + 1 : 0;
    *inout_resample_offset = (output_frames * resample_rate) - input_offset;
    return output_frames;
}
References ResamplerAdd(), ResamplerMul(), and SDL_MAX_SINT64.
Referenced by NextAudioStreamIter().
SDL_GetResamplerPaddingFrames()
int SDL_GetResamplerPaddingFrames (Sint64 resample_rate)
{
    // This must always be <= SDL_GetResamplerHistoryFrames()
    return resample_rate ? RESAMPLER_MAX_PADDING_FRAMES : 0;
}
References RESAMPLER_MAX_PADDING_FRAMES.
Referenced by GetAudioStreamDataInternal(), and NextAudioStreamIter().
SDL_ResampleAudio()
void SDL_ResampleAudio (int chans, const float * src, int inframes, float * dst, int outframes, Sint64 resample_rate, Sint64 * inout_resample_offset)
{
    int i;
    Sint64 srcpos = *inout_resample_offset;
    ResampleFrameFunc resample_frame = ResampleFrame[chans - 1];
    SDL_assert(resample_rate > 0);
    src -= (RESAMPLER_ZERO_CROSSINGS - 1) * chans;
    for (i = 0; i < outframes; ++i) {
        int srcindex = (int)(Sint32)(srcpos >> 32);
        Uint32 srcfraction = (Uint32)(srcpos & 0xFFFFFFFF);
        srcpos += resample_rate;
        SDL_assert(srcindex >= -1 && srcindex < inframes);
        const Cubic *filter = ResamplerFilter[srcfraction >> RESAMPLER_FILTER_INTERP_BITS];
        const float frac = (float)(srcfraction & (RESAMPLER_FILTER_INTERP_RANGE - 1)) * (1.0f / RESAMPLER_FILTER_INTERP_RANGE);
        const float *frame = &src[srcindex * chans];
        resample_frame(frame, dst, filter, frac, chans);
        dst += chans;
    }
    *inout_resample_offset = srcpos - ((Sint64)inframes << 32);
}
References ResampleFrame, RESAMPLER_FILTER_INTERP_BITS, RESAMPLER_FILTER_INTERP_RANGE, RESAMPLER_ZERO_CROSSINGS, ResamplerFilter, and SDL_assert.
Referenced by GetAudioStreamDataInternal().