SDL3: SDL-main/src/joystick/hidapi/SDL_hidapijoystick_c.h File Reference
SDL_hidapijoystick_c.h File Reference
#include "SDL_internal.h"
#include "../usb_ids.h"
Data Structures
struct SDL_HIDAPI_Device
struct SDL_HIDAPI_DeviceDriver
Macros
#define SDL_HIDAPI_DEFAULT true
#define SDL_JOYSTICK_CAP_MONO_LED 0x00000001
#define SDL_JOYSTICK_CAP_PLAYER_LED 0x00000004
#define SDL_JOYSTICK_CAP_RGB_LED 0x00000002
#define SDL_JOYSTICK_CAP_RUMBLE 0x00000010
#define SDL_JOYSTICK_CAP_TRIGGER_RUMBLE 0x00000020
#define SDL_JOYSTICK_HIDAPI_8BITDO
#define SDL_JOYSTICK_HIDAPI_FLYDIGI
#define SDL_JOYSTICK_HIDAPI_GAMECUBE
#define SDL_JOYSTICK_HIDAPI_GIP
#define SDL_JOYSTICK_HIDAPI_LG4FF
#define SDL_JOYSTICK_HIDAPI_LUNA
#define SDL_JOYSTICK_HIDAPI_PS3
#define SDL_JOYSTICK_HIDAPI_PS4
#define SDL_JOYSTICK_HIDAPI_PS5
#define SDL_JOYSTICK_HIDAPI_SHIELD
#define SDL_JOYSTICK_HIDAPI_SINPUT
#define SDL_JOYSTICK_HIDAPI_STADIA
#define SDL_JOYSTICK_HIDAPI_STEAM
#define SDL_JOYSTICK_HIDAPI_STEAM_HORI
#define SDL_JOYSTICK_HIDAPI_STEAMDECK
#define SDL_JOYSTICK_HIDAPI_SWITCH
#define SDL_JOYSTICK_HIDAPI_WII
#define SDL_JOYSTICK_HIDAPI_XBOX360
#define SDL_JOYSTICK_HIDAPI_XBOXONE
#define USB_PACKET_LENGTH 64
Typedefs
typedef struct SDL_HIDAPI_Device SDL_HIDAPI_Device
typedef struct SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DeviceDriver
Functions
void HIDAPI_DisconnectBluetoothDevice (const char *serial)
void HIDAPI_DumpPacket (const char *prefix, const Uint8 *data, int size)
char * HIDAPI_GetDeviceManufacturerName (Uint16 vendor_id, Uint16 product_id)
char * HIDAPI_GetDeviceProductName (Uint16 vendor_id, Uint16 product_id)
SDL_GamepadType HIDAPI_GetGamepadTypeFromGUID (SDL_GUID guid)
SDL_JoystickType HIDAPI_GetJoystickTypeFromGUID (SDL_GUID guid)
bool HIDAPI_HasConnectedUSBDevice (const char *serial)
bool HIDAPI_IsDevicePresent (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char *name)
bool HIDAPI_IsDeviceTypePresent (SDL_GamepadType type)
bool HIDAPI_JoystickConnected (SDL_HIDAPI_Device *device, SDL_JoystickID *pJoystickID)
void HIDAPI_JoystickDisconnected (SDL_HIDAPI_Device *device, SDL_JoystickID joystickID)
float HIDAPI_RemapVal (float val, float val_min, float val_max, float output_min, float output_max)
void HIDAPI_SetDeviceName (SDL_HIDAPI_Device *device, const char *name)
void HIDAPI_SetDeviceProduct (SDL_HIDAPI_Device *device, Uint16 vendor_id, Uint16 product_id)
void HIDAPI_SetDeviceSerial (SDL_HIDAPI_Device *device, const char *serial)
bool HIDAPI_SupportsPlaystationDetection (Uint16 vendor, Uint16 product)
void HIDAPI_UpdateDeviceProperties (SDL_HIDAPI_Device *device)
void HIDAPI_UpdateDevices (void)
Variables
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_Driver8BitDo
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverCombined
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverFlydigi
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverGameCube
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverGIP
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverJoyCons
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverLg4ff
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverLuna
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverNintendoClassic
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS3
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS3SonySixaxis
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS3ThirdParty
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS4
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS5
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverShield
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSInput
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverStadia
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSteam
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSteamDeck
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSteamHori
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSwitch
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverWii
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverXbox360
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverXbox360W
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverXboxOne
Macro Definition Documentation
SDL_HIDAPI_DEFAULT
#define SDL_HIDAPI_DEFAULT true
SDL_JOYSTICK_CAP_MONO_LED
#define SDL_JOYSTICK_CAP_MONO_LED 0x00000001
SDL_JOYSTICK_CAP_PLAYER_LED
#define SDL_JOYSTICK_CAP_PLAYER_LED 0x00000004
SDL_JOYSTICK_CAP_RGB_LED
#define SDL_JOYSTICK_CAP_RGB_LED 0x00000002
SDL_JOYSTICK_CAP_RUMBLE
#define SDL_JOYSTICK_CAP_RUMBLE 0x00000010
SDL_JOYSTICK_CAP_TRIGGER_RUMBLE
#define SDL_JOYSTICK_CAP_TRIGGER_RUMBLE 0x00000020
SDL_JOYSTICK_HIDAPI_8BITDO
#define SDL_JOYSTICK_HIDAPI_8BITDO
SDL_JOYSTICK_HIDAPI_FLYDIGI
#define SDL_JOYSTICK_HIDAPI_FLYDIGI
SDL_JOYSTICK_HIDAPI_GAMECUBE
#define SDL_JOYSTICK_HIDAPI_GAMECUBE
SDL_JOYSTICK_HIDAPI_GIP
#define SDL_JOYSTICK_HIDAPI_GIP
SDL_JOYSTICK_HIDAPI_LG4FF
#define SDL_JOYSTICK_HIDAPI_LG4FF
SDL_JOYSTICK_HIDAPI_LUNA
#define SDL_JOYSTICK_HIDAPI_LUNA
SDL_JOYSTICK_HIDAPI_PS3
#define SDL_JOYSTICK_HIDAPI_PS3
SDL_JOYSTICK_HIDAPI_PS4
#define SDL_JOYSTICK_HIDAPI_PS4
SDL_JOYSTICK_HIDAPI_PS5
#define SDL_JOYSTICK_HIDAPI_PS5
SDL_JOYSTICK_HIDAPI_SHIELD
#define SDL_JOYSTICK_HIDAPI_SHIELD
SDL_JOYSTICK_HIDAPI_SINPUT
#define SDL_JOYSTICK_HIDAPI_SINPUT
SDL_JOYSTICK_HIDAPI_STADIA
#define SDL_JOYSTICK_HIDAPI_STADIA
SDL_JOYSTICK_HIDAPI_STEAM
#define SDL_JOYSTICK_HIDAPI_STEAM
SDL_JOYSTICK_HIDAPI_STEAM_HORI
#define SDL_JOYSTICK_HIDAPI_STEAM_HORI
SDL_JOYSTICK_HIDAPI_STEAMDECK
#define SDL_JOYSTICK_HIDAPI_STEAMDECK
SDL_JOYSTICK_HIDAPI_SWITCH
#define SDL_JOYSTICK_HIDAPI_SWITCH
SDL_JOYSTICK_HIDAPI_WII
#define SDL_JOYSTICK_HIDAPI_WII
SDL_JOYSTICK_HIDAPI_XBOX360
#define SDL_JOYSTICK_HIDAPI_XBOX360
SDL_JOYSTICK_HIDAPI_XBOXONE
#define SDL_JOYSTICK_HIDAPI_XBOXONE
USB_PACKET_LENGTH
#define USB_PACKET_LENGTH 64
Typedef Documentation
SDL_HIDAPI_Device
typedef struct SDL_HIDAPI_Device SDL_HIDAPI_Device
SDL_HIDAPI_DeviceDriver
typedef struct SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DeviceDriver
Function Documentation
HIDAPI_DisconnectBluetoothDevice()
void HIDAPI_DisconnectBluetoothDevice (const char * serial) extern
HIDAPI_DumpPacket()
void HIDAPI_DumpPacket (const char * prefix, const Uint8 * data, int size) extern
HIDAPI_GetDeviceManufacturerName()
char * HIDAPI_GetDeviceManufacturerName (Uint16 vendor_id, Uint16 product_id) extern
HIDAPI_GetDeviceProductName()
char * HIDAPI_GetDeviceProductName (Uint16 vendor_id, Uint16 product_id) extern
HIDAPI_GetGamepadTypeFromGUID()
SDL_GamepadType HIDAPI_GetGamepadTypeFromGUID (SDL_GUID guid) extern
Referenced by SDL_GetGamepadTypeFromGUID().
HIDAPI_GetJoystickTypeFromGUID()
SDL_JoystickType HIDAPI_GetJoystickTypeFromGUID (SDL_GUID guid) extern
Referenced by SDL_GetJoystickGUIDType().
HIDAPI_HasConnectedUSBDevice()
bool HIDAPI_HasConnectedUSBDevice (const char * serial) extern
HIDAPI_IsDevicePresent()
bool HIDAPI_IsDevicePresent (Uint16 vendor_id, Uint16 product_id, Uint16 version, const char * name) extern
HIDAPI_IsDeviceTypePresent()
bool HIDAPI_IsDeviceTypePresent (SDL_GamepadType type) extern
HIDAPI_JoystickConnected()
bool HIDAPI_JoystickConnected (SDL_HIDAPI_Device * device, SDL_JoystickID * pJoystickID) extern
HIDAPI_JoystickDisconnected()
void HIDAPI_JoystickDisconnected (SDL_HIDAPI_Device * device, SDL_JoystickID joystickID) extern
HIDAPI_RemapVal()
float HIDAPI_RemapVal (float val, float val_min, float val_max, float output_min, float output_max) extern
HIDAPI_SetDeviceName()
void HIDAPI_SetDeviceName (SDL_HIDAPI_Device * device, const char * name) extern
HIDAPI_SetDeviceProduct()
void HIDAPI_SetDeviceProduct (SDL_HIDAPI_Device * device, Uint16 vendor_id, Uint16 product_id) extern
HIDAPI_SetDeviceSerial()
void HIDAPI_SetDeviceSerial (SDL_HIDAPI_Device * device, const char * serial) extern
HIDAPI_SupportsPlaystationDetection()
bool HIDAPI_SupportsPlaystationDetection (Uint16 vendor, Uint16 product) extern
HIDAPI_UpdateDeviceProperties()
void HIDAPI_UpdateDeviceProperties (SDL_HIDAPI_Device * device) extern
HIDAPI_UpdateDevices()
void HIDAPI_UpdateDevices (void) extern
Referenced by SDL_UpdateJoysticks().
Variable Documentation
SDL_HIDAPI_Driver8BitDo
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_Driver8BitDo extern
SDL_HIDAPI_DriverCombined
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverCombined extern
SDL_HIDAPI_DriverFlydigi
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverFlydigi extern
SDL_HIDAPI_DriverGameCube
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverGameCube extern
SDL_HIDAPI_DriverGIP
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverGIP extern
SDL_HIDAPI_DriverJoyCons
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverJoyCons extern
SDL_HIDAPI_DriverLg4ff
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverLg4ff extern
SDL_HIDAPI_DriverLuna
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverLuna extern
SDL_HIDAPI_DriverNintendoClassic
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverNintendoClassic extern
SDL_HIDAPI_DriverPS3
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS3 extern
SDL_HIDAPI_DriverPS3SonySixaxis
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS3SonySixaxis extern
SDL_HIDAPI_DriverPS3ThirdParty
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS3ThirdParty extern
SDL_HIDAPI_DriverPS4
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS4 extern
SDL_HIDAPI_DriverPS5
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverPS5 extern
SDL_HIDAPI_DriverShield
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverShield extern
SDL_HIDAPI_DriverSInput
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSInput extern
SDL_HIDAPI_DriverStadia
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverStadia extern
SDL_HIDAPI_DriverSteam
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSteam extern
SDL_HIDAPI_DriverSteamDeck
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSteamDeck extern
SDL_HIDAPI_DriverSteamHori
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSteamHori extern
SDL_HIDAPI_DriverSwitch
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverSwitch extern
SDL_HIDAPI_DriverWii
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverWii extern
SDL_HIDAPI_DriverXbox360
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverXbox360 extern
SDL_HIDAPI_DriverXbox360W
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverXbox360W extern
SDL_HIDAPI_DriverXboxOne
SDL_HIDAPI_DeviceDriver SDL_HIDAPI_DriverXboxOne extern