SDL3: SDL-main/src/thread/pthread/SDL_syscond.c File Reference
SDL_syscond.c File Reference
#include "SDL_internal.h"
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include <errno.h>
#include <pthread.h>
#include "SDL_sysmutex_c.h"
Data Structures
struct SDL_Condition
Functions
void SDL_BroadcastCondition (SDL_Condition *cond)
SDL_Condition * SDL_CreateCondition (void)
void SDL_DestroyCondition (SDL_Condition *cond)
void SDL_SignalCondition (SDL_Condition *cond)
bool SDL_WaitConditionTimeoutNS (SDL_Condition *cond, SDL_Mutex *mutex, Sint64 timeoutNS)
Function Documentation
SDL_BroadcastCondition()
void SDL_BroadcastCondition (SDL_Condition * cond)
Restart all threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    if (!cond) {
        return;
    }
    pthread_cond_broadcast(&cond->cond);
}
References SDL_Condition::cond.
SDL_CreateCondition()
SDL_Condition * SDL_CreateCondition (void)
Create a condition variable.
Returns
a new condition variable or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
SDL_DestroyCondition
{
    SDL_Condition *cond;
    cond = (SDL_Condition *)SDL_malloc(sizeof(SDL_Condition));
    if (cond) {
        if (pthread_cond_init(&cond->cond, NULL) != 0) {
            SDL_SetError("pthread_cond_init() failed");
            SDL_free(cond);
            cond = NULL;
        }
    }
    return cond;
}
References SDL_Condition::cond, NULL, SDL_free(), SDL_malloc(), and SDL_SetError().
SDL_DestroyCondition()
void SDL_DestroyCondition (SDL_Condition * cond)
Destroy a condition variable.
Parameters
cond the condition variable to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateCondition
{
    if (cond) {
        pthread_cond_destroy(&cond->cond);
        SDL_free(cond);
    }
}
References SDL_Condition::cond, and SDL_free().
SDL_SignalCondition()
void SDL_SignalCondition (SDL_Condition * cond)
Restart one of the threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    if (!cond) {
        return;
    }
    pthread_cond_signal(&cond->cond);
}
References SDL_Condition::cond.
SDL_WaitConditionTimeoutNS()
bool SDL_WaitConditionTimeoutNS (SDL_Condition * cond, SDL_Mutex * mutex, Sint64 timeoutNS)
{
#ifndef HAVE_CLOCK_GETTIME
    struct timeval delta;
#endif
    struct timespec abstime;
    if (!cond || !mutex) {
        return true;
    }
    if (timeoutNS < 0) {
        return (pthread_cond_wait(&cond->cond, &mutex->id) == 0);
    }
#ifdef HAVE_CLOCK_GETTIME
    clock_gettime(CLOCK_REALTIME, &abstime);
    abstime.tv_sec += (timeoutNS / SDL_NS_PER_SECOND);
    abstime.tv_nsec += (timeoutNS % SDL_NS_PER_SECOND);
#else
    gettimeofday(&delta, NULL);
    abstime.tv_sec = delta.tv_sec + (timeoutNS / SDL_NS_PER_SECOND);
    abstime.tv_nsec = SDL_US_TO_NS(delta.tv_usec) + (timeoutNS % SDL_NS_PER_SECOND);
#endif
    while (abstime.tv_nsec >= 1000000000) {
        abstime.tv_sec += 1;
        abstime.tv_nsec -= 1000000000;
    }
    bool result;
    int rc;
tryagain:
    rc = pthread_cond_timedwait(&cond->cond, &mutex->id, &abstime);
    switch (rc) {
    case EINTR:
        goto tryagain;
        // break; -Wunreachable-code-break
    case ETIMEDOUT:
        result = false;
        break;
    default:
        result = true;
        break;
    }
    return result;
}
References SDL_Condition::cond, SDL_Mutex::id, NULL, SDL_NS_PER_SECOND, and SDL_US_TO_NS.