SDL3: SDL-main/src/events/SDL_dropevents_c.h File Reference
SDL_dropevents_c.h File Reference
#include "SDL_internal.h"
Functions
bool SDL_SendDropComplete (SDL_Window *window)
bool SDL_SendDropFile (SDL_Window *window, const char *source, const char *file)
bool SDL_SendDropPosition (SDL_Window *window, float x, float y)
bool SDL_SendDropText (SDL_Window *window, const char *text)
Function Documentation
SDL_SendDropComplete()
bool SDL_SendDropComplete (SDL_Window * window) extern
{
    return SDL_SendDrop(window, SDL_EVENT_DROP_COMPLETE, NULL, NULL, 0, 0);
}
References NULL, SDL_EVENT_DROP_COMPLETE, and SDL_SendDrop().
SDL_SendDropFile()
bool SDL_SendDropFile (SDL_Window * window, const char * source, const char * file) extern
{
    return SDL_SendDrop(window, SDL_EVENT_DROP_FILE, source, file, 0, 0);
}
References SDL_EVENT_DROP_FILE, and SDL_SendDrop().
SDL_SendDropPosition()
bool SDL_SendDropPosition (SDL_Window * window, float x, float y) extern
{
    return SDL_SendDrop(window, SDL_EVENT_DROP_POSITION, NULL, NULL, x, y);
}
References NULL, SDL_EVENT_DROP_POSITION, and SDL_SendDrop().
SDL_SendDropText()
bool SDL_SendDropText (SDL_Window * window, const char * text) extern
{
    return SDL_SendDrop(window, SDL_EVENT_DROP_TEXT, NULL, text, 0, 0);
}
References NULL, SDL_EVENT_DROP_TEXT, and SDL_SendDrop().