SDL3: CRenderer Class Reference
CRenderer Class Reference
#include <SDL_render_ngage_c.hpp>
Inherits MDirectScreenAccess.
Public Member Functions
void Clear (TUint32 iColor)
bool Copy (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_Rect *srcrect, const SDL_Rect *dstrect)
bool CopyEx (SDL_Renderer *renderer, SDL_Texture *texture, const NGAGE_CopyExData *copydata)
bool CreateTextureData (NGAGE_TextureData *aTextureData, const TInt aWidth, const TInt aHeight)
void DisableKeyBlocking ()
void DrawLines (NGAGE_Vertex *aVerts, const TInt aCount)
void DrawPoints (NGAGE_Vertex *aVerts, const TInt aCount)
void FillRects (NGAGE_Vertex *aVerts, const TInt aCount)
void Flip ()
void HandleEvent (const TWsEvent &aWsEvent)
void PumpEvents ()
void SetClipRect (TInt aX, TInt aY, TInt aWidth, TInt aHeight)
void SetDrawColor (TUint32 iColor)
void SuspendScreenSaver (TBool aSuspend)
void UpdateFPS ()
virtual ~CRenderer ()
Static Public Member Functions
static CRenderer * NewL ()
Private Member Functions
void AbortNow (RDirectScreenAccess::TTerminationReasons aReason)
void ConstructL (void)
CRenderer ()
void Restart (RDirectScreenAccess::TTerminationReasons aReason)
Private Attributes
CDirectScreenAccess * iDirectScreen
const CFont * iFont
TUint iFPS
TBool iIsFocused
CNRenderer * iRenderer
CFbsBitGc * iScreenGc
TBool iShowFPS
TBool iSuspendScreenSaver
TWsEvent iWsEvent
TRequestStatus iWsEventStatus
CWsScreenDevice * iWsScreen
RWsSession iWsSession
RWindow iWsWindow
RWindowGroup iWsWindowGroup
TInt iWsWindowGroupID
Constructor & Destructor Documentation
~CRenderer()
virtual CRenderer::~CRenderer () virtual
CRenderer()
CRenderer::CRenderer () private
Referenced by NewL().
Member Function Documentation
AbortNow()
void CRenderer::AbortNow (RDirectScreenAccess::TTerminationReasons aReason) private
Clear()
void CRenderer::Clear (TUint32 iColor)
ConstructL()
void CRenderer::ConstructL (void) private
Copy()
bool CRenderer::Copy (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_Rect * srcrect, const SDL_Rect * dstrect)
CopyEx()
bool CRenderer::CopyEx (SDL_Renderer * renderer, SDL_Texture * texture, const NGAGE_CopyExData * copydata)
CreateTextureData()
bool CRenderer::CreateTextureData (NGAGE_TextureData * aTextureData, const TInt aWidth, const TInt aHeight)
DisableKeyBlocking()
void CRenderer::DisableKeyBlocking ()
DrawLines()
void CRenderer::DrawLines (NGAGE_Vertex * aVerts, const TInt aCount)
DrawPoints()
void CRenderer::DrawPoints (NGAGE_Vertex * aVerts, const TInt aCount)
FillRects()
void CRenderer::FillRects (NGAGE_Vertex * aVerts, const TInt aCount)
Flip()
void CRenderer::Flip ()
HandleEvent()
void CRenderer::HandleEvent (const TWsEvent & aWsEvent)
NewL()
CRenderer * CRenderer::NewL () static
References CRenderer().
Referenced by E32Main().
PumpEvents()
void CRenderer::PumpEvents ()
Restart()
void CRenderer::Restart (RDirectScreenAccess::TTerminationReasons aReason) private
SetClipRect()
void CRenderer::SetClipRect (TInt aX, TInt aY, TInt aWidth, TInt aHeight)
SetDrawColor()
void CRenderer::SetDrawColor (TUint32 iColor)
SuspendScreenSaver()
void CRenderer::SuspendScreenSaver (TBool aSuspend)
UpdateFPS()
void CRenderer::UpdateFPS ()
Field Documentation
iDirectScreen
CDirectScreenAccess* CRenderer::iDirectScreen private
iFont
const CFont* CRenderer::iFont private
iFPS
TUint CRenderer::iFPS private
iIsFocused
TBool CRenderer::iIsFocused private
iRenderer
CNRenderer* CRenderer::iRenderer private
iScreenGc
CFbsBitGc* CRenderer::iScreenGc private
iShowFPS
TBool CRenderer::iShowFPS private
iSuspendScreenSaver
TBool CRenderer::iSuspendScreenSaver private
iWsEvent
TWsEvent CRenderer::iWsEvent private
iWsEventStatus
TRequestStatus CRenderer::iWsEventStatus private
iWsScreen
CWsScreenDevice* CRenderer::iWsScreen private
iWsSession
RWsSession CRenderer::iWsSession private
iWsWindow
RWindow CRenderer::iWsWindow private
iWsWindowGroup
RWindowGroup CRenderer::iWsWindowGroup private
iWsWindowGroupID
TInt CRenderer::iWsWindowGroupID private
The documentation for this class was generated from the following file:
SDL-main/src/render/ngage/SDL_render_ngage_c.hpp