SDL3: SDL-main/src/misc/unix/SDL_sysurl.c File Reference
SDL_sysurl.c File Reference
#include "SDL_internal.h"
#include "../SDL_sysurl.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <errno.h>
Functions
bool SDL_SYS_OpenURL (const char *url)
Function Documentation
SDL_SYS_OpenURL()
bool SDL_SYS_OpenURL (const char * url)
{
    const char *args[] = { "xdg-open", url, NULL };
    SDL_Environment *env = NULL;
    SDL_Process *process = NULL;
    bool result = false;
    env = SDL_CreateEnvironment(true);
    if (!env) {
        goto done;
    }
    // Clear LD_PRELOAD so Chrome opens correctly when this application is launched by Steam
    SDL_UnsetEnvironmentVariable(env, "LD_PRELOAD");
    SDL_PropertiesID props = SDL_CreateProperties();
    if (!props) {
        goto done;
    }
    SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, args);
    SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER, env);
    SDL_SetBooleanProperty(props, SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN, true);
    process = SDL_CreateProcessWithProperties(props);
    SDL_DestroyProperties(props);
    if (!process) {
        goto done;
    }
    result = true;
done:
    SDL_DestroyEnvironment(env);
    SDL_DestroyProcess(process);
    return result;
}
References NULL, SDL_CreateEnvironment(), SDL_CreateProcessWithProperties(), SDL_CreateProperties(), SDL_DestroyEnvironment(), SDL_DestroyProcess(), SDL_DestroyProperties(), SDL_PROP_PROCESS_CREATE_ARGS_POINTER, SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN, SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER, SDL_SetBooleanProperty(), SDL_SetPointerProperty(), and SDL_UnsetEnvironmentVariable().