SDL3: SDL-main/src/io/n3ds/SDL_iostreamromfs.c File Reference
SDL_iostreamromfs.c File Reference
#include "SDL_iostreamromfs.h"
Functions
static bool HasPrefix (const char *file, const char *prefix)
static bool IsReadMode (const char *mode)
FILE * N3DS_FileOpen (const char *file, const char *mode)
static FILE * TryOpenFile (const char *file, const char *mode)
static FILE * TryOpenInRomfs (const char *file, const char *mode)
Function Documentation
HasPrefix()
bool HasPrefix (const char * file, const char * prefix) static
{
    return SDL_strncmp(prefix, file, SDL_strlen(prefix)) == 0;
}
References SDL_strlen(), and SDL_strncmp().
Referenced by N3DS_FileOpen().
IsReadMode()
bool IsReadMode (const char * mode) static
{
    return SDL_strchr(mode, 'r') != NULL;
}
References NULL, and SDL_strchr().
Referenced by N3DS_FileOpen().
N3DS_FileOpen()
FILE * N3DS_FileOpen (const char * file, const char * mode)
{
    // romfs are read-only
    if (!IsReadMode(mode)) {
        return fopen(file, mode);
    }
    // If the path has an explicit prefix, we skip the guess work
    if (HasPrefix(file, "romfs:/") || HasPrefix(file, "sdmc:/")) {
        return fopen(file, mode);
    }
    return TryOpenFile(file, mode);
}
References HasPrefix(), IsReadMode(), and TryOpenFile().
Referenced by SDL_IOFromFile().
TryOpenFile()
FILE * TryOpenFile (const char * file, const char * mode) static
{
    FILE *fp = NULL;
    fp = TryOpenInRomfs(file, mode);
    if (!fp) {
        fp = fopen(file, mode);
    }
    return fp;
}
References NULL, and TryOpenInRomfs().
Referenced by N3DS_FileOpen().
TryOpenInRomfs()
FILE * TryOpenInRomfs (const char * file, const char * mode) static
{
    FILE *fp = NULL;
    char *prefixed_filepath = NULL;
    if (SDL_asprintf(&prefixed_filepath, "romfs:/%s", file) < 0) {
        return NULL;
    }
    fp = fopen(prefixed_filepath, mode);
    SDL_free(prefixed_filepath);
    return fp;
}
References NULL, SDL_asprintf(), and SDL_free().
Referenced by TryOpenFile().