SDL3: SDL-main/src/video/SDL_video_unsupported.c File Reference
SDL_video_unsupported.c File Reference
#include "SDL_internal.h"
Typedefs
typedef void(SDLCALL * SDL_iOSAnimationCallback) (void *userdata)
Functions
SDL_DECLSPEC int SDLCALL SDL_GetDirect3D9AdapterIndex (SDL_DisplayID displayID)
SDL_DECLSPEC bool SDLCALL SDL_GetDXGIOutputInfo (SDL_DisplayID displayID, int *adapterIndex, int *outputIndex)
SDL_DECLSPEC bool SDLCALL SDL_GetGDKTaskQueue (void *outTaskQueue)
SDL_DECLSPEC void SDLCALL SDL_OnApplicationDidChangeStatusBarOrientation (void)
SDL_DECLSPEC bool SDLCALL SDL_SetiOSAnimationCallback (SDL_Window *window, int interval, SDL_iOSAnimationCallback callback, void *callbackParam)
SDL_DECLSPEC void SDLCALL SDL_SetiOSEventPump (bool enabled)
Typedef Documentation
SDL_iOSAnimationCallback
typedef void(SDLCALL * SDL_iOSAnimationCallback) (void *userdata)
Function Documentation
SDL_GetDirect3D9AdapterIndex()
int SDL_GetDirect3D9AdapterIndex (SDL_DisplayID displayID)
{
    (void)displayID;
    SDL_Unsupported();
    return -1;
}
References SDL_Unsupported, and void().
SDL_GetDXGIOutputInfo()
bool SDL_GetDXGIOutputInfo (SDL_DisplayID displayID, int * adapterIndex, int * outputIndex)
{
    (void)displayID;
    (void)adapterIndex;
    (void)outputIndex;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
SDL_GetGDKTaskQueue()
bool SDL_GetGDKTaskQueue (void * outTaskQueue)
{
    (void)outTaskQueue;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
SDL_OnApplicationDidChangeStatusBarOrientation()
void SDL_OnApplicationDidChangeStatusBarOrientation (void)
{
    SDL_Unsupported();
}
References SDL_Unsupported.
SDL_SetiOSAnimationCallback()
bool SDL_SetiOSAnimationCallback (SDL_Window * window, int interval, SDL_iOSAnimationCallback callback, void * callbackParam)
{
    (void)window;
    (void)interval;
    (void)callback;
    (void)callbackParam;
    return SDL_Unsupported();
}
References SDL_Unsupported, and void().
SDL_SetiOSEventPump()
void SDL_SetiOSEventPump (bool enabled)
{
    (void)enabled;
    SDL_Unsupported();
}
References SDL_Unsupported, and void().