SDL3: SDL-main/src/joystick/SDL_steam_virtual_gamepad.h File Reference
SDL_steam_virtual_gamepad.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_SteamVirtualGamepadInfo
Typedefs
typedef struct SDL_SteamVirtualGamepadInfo SDL_SteamVirtualGamepadInfo
Functions
const SDL_SteamVirtualGamepadInfo * SDL_GetSteamVirtualGamepadInfo (int slot)
void SDL_InitSteamVirtualGamepadInfo (void)
void SDL_QuitSteamVirtualGamepadInfo (void)
bool SDL_SteamVirtualGamepadEnabled (void)
bool SDL_UpdateSteamVirtualGamepadInfo (void)
Typedef Documentation
SDL_SteamVirtualGamepadInfo
typedef struct SDL_SteamVirtualGamepadInfo SDL_SteamVirtualGamepadInfo
Function Documentation
SDL_GetSteamVirtualGamepadInfo()
const SDL_SteamVirtualGamepadInfo * SDL_GetSteamVirtualGamepadInfo (int slot)
{
    SDL_AssertJoysticksLocked();
    if (slot < 0 || slot >= SDL_steam_virtual_gamepad_info_count) {
        return NULL;
    }
    return SDL_steam_virtual_gamepad_info[slot];
}
References NULL, and SDL_AssertJoysticksLocked().
Referenced by SDL_GetJoystickVirtualGamepadInfoForID().
SDL_InitSteamVirtualGamepadInfo()
void SDL_InitSteamVirtualGamepadInfo (void)
{
    const char *file;
    SDL_AssertJoysticksLocked();
    // The file isn't available inside the macOS sandbox
    if (SDL_GetSandbox() == SDL_SANDBOX_MACOS) {
        return;
    }
    file = SDL_GetHint(SDL_HINT_STEAM_VIRTUAL_GAMEPAD_INFO_FILE);
    if (file && *file) {
        SDL_steam_virtual_gamepad_info_file = SDL_strdup(file);
    }
    SDL_UpdateSteamVirtualGamepadInfo();
}
References SDL_AssertJoysticksLocked(), SDL_GetHint(), SDL_GetSandbox(), SDL_HINT_STEAM_VIRTUAL_GAMEPAD_INFO_FILE, SDL_SANDBOX_MACOS, SDL_strdup(), and SDL_UpdateSteamVirtualGamepadInfo().
Referenced by SDL_InitJoysticks().
SDL_QuitSteamVirtualGamepadInfo()
void SDL_QuitSteamVirtualGamepadInfo (void)
{
    SDL_AssertJoysticksLocked();
    if (SDL_steam_virtual_gamepad_info_file) {
        SDL_FreeSteamVirtualGamepadInfo();
        SDL_free(SDL_steam_virtual_gamepad_info_file);
        SDL_steam_virtual_gamepad_info_file = NULL;
    }
}
References NULL, SDL_AssertJoysticksLocked(), SDL_free(), and SDL_FreeSteamVirtualGamepadInfo().
Referenced by SDL_QuitJoysticks().
SDL_SteamVirtualGamepadEnabled()
bool SDL_SteamVirtualGamepadEnabled (void)
{
    SDL_AssertJoysticksLocked();
    return (SDL_steam_virtual_gamepad_info != NULL);
}
References NULL, and SDL_AssertJoysticksLocked().
Referenced by SDL_GetJoystickVirtualGamepadInfoForID().
SDL_UpdateSteamVirtualGamepadInfo()
bool SDL_UpdateSteamVirtualGamepadInfo (void)
{
    const int UPDATE_CHECK_INTERVAL_MS = 3000;
    Uint64 now;
    Uint64 mtime;
    char *data, *end, *next, *line, *value;
    size_t size;
    int slot, new_slot;
    SDL_SteamVirtualGamepadInfo info;
    SDL_AssertJoysticksLocked();
    if (!SDL_steam_virtual_gamepad_info_file) {
        return false;
    }
    now = SDL_GetTicks();
    if (SDL_steam_virtual_gamepad_info_check_time &&
        now < (SDL_steam_virtual_gamepad_info_check_time + UPDATE_CHECK_INTERVAL_MS)) {
        return false;
    }
    SDL_steam_virtual_gamepad_info_check_time = now;
    mtime = GetFileModificationTime(SDL_steam_virtual_gamepad_info_file);
    if (mtime == 0 || mtime == SDL_steam_virtual_gamepad_info_file_mtime) {
        return false;
    }
    data = (char *)SDL_LoadFile(SDL_steam_virtual_gamepad_info_file, &size);
    if (!data) {
        return false;
    }
    SDL_FreeSteamVirtualGamepadInfo();
    slot = -1;
    SDL_zero(info);
    for (next = data, end = data + size; next < end; ) {
        while (next < end && (*next == '\0' || *next == '\r' || *next == '\n')) {
            ++next;
        }
        line = next;
        while (next < end && (*next != '\r' && *next != '\n')) {
            ++next;
        }
        *next = '\0';
        if (SDL_sscanf(line, "[slot %d]", &new_slot) == 1) {
            if (slot >= 0) {
                AddVirtualGamepadInfo(slot, &info);
            }
            slot = new_slot;
        } else {
            value = SDL_strchr(line, '=');
            if (value) {
                *value++ = '\0';
                if (SDL_strcmp(line, "name") == 0) {
                    SDL_free(info.name);
                    info.name = SDL_strdup(value);
                } else if (SDL_strcmp(line, "VID") == 0) {
                    info.vendor_id = (Uint16)SDL_strtoul(value, NULL, 0);
                } else if (SDL_strcmp(line, "PID") == 0) {
                    info.product_id = (Uint16)SDL_strtoul(value, NULL, 0);
                } else if (SDL_strcmp(line, "type") == 0) {
                    info.type = SDL_GetGamepadTypeFromString(value);
                } else if (SDL_strcmp(line, "handle") == 0) {
                    info.handle = (Uint64)SDL_strtoull(value, NULL, 0);
                }
            }
        }
    }
    if (slot >= 0) {
        AddVirtualGamepadInfo(slot, &info);
    }
    SDL_free(info.name);
    SDL_free(data);
    SDL_steam_virtual_gamepad_info_file_mtime = mtime;
    return true;
}
References AddVirtualGamepadInfo(), GetFileModificationTime(), SDL_SteamVirtualGamepadInfo::handle, SDL_SteamVirtualGamepadInfo::name, NULL, SDL_SteamVirtualGamepadInfo::product_id, SDL_AssertJoysticksLocked(), SDL_free(), SDL_FreeSteamVirtualGamepadInfo(), SDL_GetGamepadTypeFromString(), SDL_GetTicks(), SDL_LoadFile(), SDL_sscanf(), SDL_strchr(), SDL_strcmp(), SDL_strdup(), SDL_strtoul(), SDL_strtoull(), SDL_zero, SDL_SteamVirtualGamepadInfo::type, and SDL_SteamVirtualGamepadInfo::vendor_id.
Referenced by SDL_InitSteamVirtualGamepadInfo(), and SDL_UpdateJoysticks().