SDL3: hidapi_backend Struct Reference
hidapi_backend Struct Reference
Data Fields
void(* hid_close)(void *device)
const wchar_t *(* hid_error)(void *device)
struct hid_device_info *(* hid_get_device_info)(void *device)
int(* hid_get_feature_report)(void *device, unsigned char *data, size_t length)
int(* hid_get_indexed_string)(void *device, int string_index, wchar_t *string, size_t maxlen)
int(* hid_get_input_report)(void *device, unsigned char *data, size_t length)
int(* hid_get_manufacturer_string)(void *device, wchar_t *string, size_t maxlen)
int(* hid_get_product_string)(void *device, wchar_t *string, size_t maxlen)
int(* hid_get_report_descriptor)(void *device, unsigned char *buf, size_t buf_size)
int(* hid_get_serial_number_string)(void *device, wchar_t *string, size_t maxlen)
int(* hid_read)(void *device, unsigned char *data, size_t length)
int(* hid_read_timeout)(void *device, unsigned char *data, size_t length, int milliseconds)
int(* hid_send_feature_report)(void *device, const unsigned char *data, size_t length)
int(* hid_set_nonblocking)(void *device, int nonblock)
int(* hid_write)(void *device, const unsigned char *data, size_t length)
Field Documentation
hid_close
void(* hidapi_backend::hid_close) (void *device)
Referenced by SDL_hid_close().
hid_error
const wchar_t *(* hidapi_backend::hid_error) (void *device)
hid_get_device_info
struct hid_device_info *(* hidapi_backend::hid_get_device_info) (void *device)
Referenced by SDL_hid_get_device_info().
hid_get_feature_report
int(* hidapi_backend::hid_get_feature_report) (void *device, unsigned char *data, size_t length)
Referenced by SDL_hid_get_feature_report().
hid_get_indexed_string
int(* hidapi_backend::hid_get_indexed_string) (void *device, int string_index, wchar_t *string, size_t maxlen)
Referenced by SDL_hid_get_indexed_string().
hid_get_input_report
int(* hidapi_backend::hid_get_input_report) (void *device, unsigned char *data, size_t length)
Referenced by SDL_hid_get_input_report().
hid_get_manufacturer_string
int(* hidapi_backend::hid_get_manufacturer_string) (void *device, wchar_t *string, size_t maxlen)
Referenced by SDL_hid_get_manufacturer_string().
hid_get_product_string
int(* hidapi_backend::hid_get_product_string) (void *device, wchar_t *string, size_t maxlen)
Referenced by SDL_hid_get_product_string().
hid_get_report_descriptor
int(* hidapi_backend::hid_get_report_descriptor) (void *device, unsigned char *buf, size_t buf_size)
Referenced by SDL_hid_get_report_descriptor().
hid_get_serial_number_string
int(* hidapi_backend::hid_get_serial_number_string) (void *device, wchar_t *string, size_t maxlen)
Referenced by SDL_hid_get_serial_number_string().
hid_read
int(* hidapi_backend::hid_read) (void *device, unsigned char *data, size_t length)
Referenced by SDL_hid_read().
hid_read_timeout
int(* hidapi_backend::hid_read_timeout) (void *device, unsigned char *data, size_t length, int milliseconds)
Referenced by SDL_hid_read_timeout().
hid_send_feature_report
int(* hidapi_backend::hid_send_feature_report) (void *device, const unsigned char *data, size_t length)
Referenced by SDL_hid_send_feature_report().
hid_set_nonblocking
int(* hidapi_backend::hid_set_nonblocking) (void *device, int nonblock)
Referenced by SDL_hid_set_nonblocking().
hid_write
int(* hidapi_backend::hid_write) (void *device, const unsigned char *data, size_t length)
Referenced by SDL_hid_write().
The documentation for this struct was generated from the following file:
SDL-main/src/hidapi/SDL_hidapi.c