SDL3: SDL-main/src/audio/SDL_audio.c File Reference
SDL_audio.c File Reference
#include "SDL_internal.h"
#include "SDL_audio_c.h"
#include "SDL_sysaudio.h"
#include "../thread/SDL_systhread.h"
Data Structures
struct CountAudioDevicesData
struct FindAudioDeviceByCallbackData
struct FindLowestDeviceIDData
Macros
#define CASE(X)
#define CHECK_FMT_STRING(x)
#define FILL_STUB(x)
#define NATIVE(type)
#define NUM_FORMATS 8
#define SWAPPED(type)
Typedefs
typedef struct CountAudioDevicesData CountAudioDevicesData
typedef struct FindAudioDeviceByCallbackData FindAudioDeviceByCallbackData
typedef struct FindLowestDeviceIDData FindLowestDeviceIDData
Functions
static SDL_AudioDeviceID AssignAudioDeviceInstanceId (bool recording, bool islogical)
static bool AudioDeviceCanUseSimpleCopy (SDL_AudioDevice *device)
static void ClosePhysicalAudioDevice (SDL_AudioDevice *device)
static void CompleteAudioEntryPoints (void)
static bool SDLCALL CountAudioDevices (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
static SDL_AudioDevice * CreateAudioPlaybackDevice (const char *name, const SDL_AudioSpec *spec, void *handle)
static SDL_AudioDevice * CreateAudioRecordingDevice (const char *name, const SDL_AudioSpec *spec, void *handle)
static SDL_AudioDevice * CreatePhysicalAudioDevice (const char *name, bool recording, const SDL_AudioSpec *spec, void *handle, SDL_AtomicInt *device_count)
static void DestroyLogicalAudioDevice (SDL_LogicalAudioDevice *logdev)
static bool SDLCALL DestroyOnePhysicalAudioDevice (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
static void DestroyPhysicalAudioDevice (SDL_AudioDevice *device)
static bool SDLCALL FindAudioDeviceByCallback (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
static bool SDLCALL FindLowestDeviceID (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
static SDL_AudioDeviceID * GetAudioDevices (int *count, bool recording)
static SDL_AudioDevice * GetFirstAddedAudioDevice (const bool recording)
static Uint32 SDLCALL HashAudioDeviceID (void *userdata, const void *key)
static void MixFloat32Audio (float *dst, const float *src, const int buffer_size)
static SDL_LogicalAudioDevice * ObtainLogicalAudioDevice (SDL_AudioDeviceID devid, SDL_AudioDevice **_device) SDL_NO_THREAD_SAFETY_ANALYSIS
static SDL_AudioDevice * ObtainPhysicalAudioDevice (SDL_AudioDeviceID devid)
static SDL_AudioDevice * ObtainPhysicalAudioDeviceDefaultAllowed (SDL_AudioDeviceID devid)
static void ObtainPhysicalAudioDeviceObj (SDL_AudioDevice *device) SDL_NO_THREAD_SAFETY_ANALYSIS
void OnAudioStreamCreated (SDL_AudioStream *stream)
void OnAudioStreamDestroy (SDL_AudioStream *stream)
static bool OpenPhysicalAudioDevice (SDL_AudioDevice *device, const SDL_AudioSpec *inspec)
static SDL_AudioFormat ParseAudioFormatString (const char *string)
static int SDLCALL PlaybackAudioThread (void *devicep)
static void PrepareAudioFormat (bool recording, SDL_AudioSpec *spec)
static int SDLCALL RecordingAudioThread (void *devicep)
void RefPhysicalAudioDevice (SDL_AudioDevice *device)
static void ReleaseAudioDevice (SDL_AudioDevice *device) SDL_NO_THREAD_SAFETY_ANALYSIS
SDL_AudioDevice * SDL_AddAudioDevice (bool recording, const char *name, const SDL_AudioSpec *inspec, void *handle)
bool SDL_AudioChannelMapsEqual (int channels, const int *channel_map_a, const int *channel_map_b)
static void SDL_AudioCloseDevice_Default (SDL_AudioDevice *device)
static void SDL_AudioDeinitialize_Default (void)
static void SDL_AudioDeinitializeStart_Default (void)
static void SDL_AudioDetectDevices_Default (SDL_AudioDevice **default_playback, SDL_AudioDevice **default_recording)
void SDL_AudioDeviceDisconnected (SDL_AudioDevice *device)
bool SDL_AudioDeviceFormatChanged (SDL_AudioDevice *device, const SDL_AudioSpec *newspec, int new_sample_frames)
bool SDL_AudioDeviceFormatChangedAlreadyLocked (SDL_AudioDevice *device, const SDL_AudioSpec *newspec, int new_sample_frames)
bool SDL_AudioDevicePaused (SDL_AudioDeviceID devid)
static void SDL_AudioFlushRecording_Default (SDL_AudioDevice *device)
static void SDL_AudioFreeDeviceHandle_Default (SDL_AudioDevice *device)
static Uint8 * SDL_AudioGetDeviceBuf_Default (SDL_AudioDevice *device, int *buffer_size)
static bool SDL_AudioOpenDevice_Default (SDL_AudioDevice *device)
static bool SDL_AudioPlayDevice_Default (SDL_AudioDevice *device, const Uint8 *buffer, int buffer_size)
static int SDL_AudioRecordDevice_Default (SDL_AudioDevice *device, void *buffer, int buflen)
bool SDL_AudioSpecsEqual (const SDL_AudioSpec *a, const SDL_AudioSpec *b, const int *channel_map_a, const int *channel_map_b)
bool SDL_AudioStreamDevicePaused (SDL_AudioStream *stream)
static void SDL_AudioThreadDeinit_Default (SDL_AudioDevice *device)
void SDL_AudioThreadFinalize (SDL_AudioDevice *device)
static void SDL_AudioThreadInit_Default (SDL_AudioDevice *device)
static bool SDL_AudioWaitDevice_Default (SDL_AudioDevice *device)
static bool SDL_AudioWaitRecordingDevice_Default (SDL_AudioDevice *device)
bool SDL_BindAudioStream (SDL_AudioDeviceID devid, SDL_AudioStream *stream)
bool SDL_BindAudioStreams (SDL_AudioDeviceID devid, SDL_AudioStream *const *streams, int num_streams)
int * SDL_ChannelMapDup (const int *origchmap, int channels)
void SDL_CloseAudioDevice (SDL_AudioDeviceID devid)
const SDL_AudioFormat * SDL_ClosestAudioFormats (SDL_AudioFormat format)
SDL_COMPILE_TIME_ASSERT (check_lowest_audio_default_value, SDL_AUDIO_DEVICE_DEFAULT_RECORDING< SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK)
void SDL_DefaultAudioDeviceChanged (SDL_AudioDevice *new_default_device)
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByCallback (bool(*callback)(SDL_AudioDevice *device, void *userdata), void *userdata)
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByHandle (void *handle)
int * SDL_GetAudioDeviceChannelMap (SDL_AudioDeviceID devid, int *count)
bool SDL_GetAudioDeviceFormat (SDL_AudioDeviceID devid, SDL_AudioSpec *spec, int *sample_frames)
float SDL_GetAudioDeviceGain (SDL_AudioDeviceID devid)
const char * SDL_GetAudioDeviceName (SDL_AudioDeviceID devid)
const char * SDL_GetAudioDriver (int index)
const char * SDL_GetAudioFormatName (SDL_AudioFormat format)
SDL_AudioDeviceID * SDL_GetAudioPlaybackDevices (int *count)
SDL_AudioDeviceID * SDL_GetAudioRecordingDevices (int *count)
SDL_AudioDeviceID SDL_GetAudioStreamDevice (SDL_AudioStream *stream)
char * SDL_GetAudioThreadName (SDL_AudioDevice *device, char *buf, size_t buflen)
const char * SDL_GetCurrentAudioDriver (void)
int SDL_GetDefaultSampleFramesFromFreq (const int freq)
int SDL_GetNumAudioDrivers (void)
int SDL_GetSilenceValueForFormat (SDL_AudioFormat format)
bool SDL_InitAudio (const char *driver_name)
bool SDL_IsAudioDevicePhysical (SDL_AudioDeviceID devid)
bool SDL_IsAudioDevicePlayback (SDL_AudioDeviceID devid)
SDL_AudioDeviceID SDL_OpenAudioDevice (SDL_AudioDeviceID devid, const SDL_AudioSpec *spec)
SDL_AudioStream * SDL_OpenAudioDeviceStream (SDL_AudioDeviceID devid, const SDL_AudioSpec *spec, SDL_AudioStreamCallback callback, void *userdata)
bool SDL_PauseAudioDevice (SDL_AudioDeviceID devid)
bool SDL_PauseAudioStreamDevice (SDL_AudioStream *stream)
bool SDL_PlaybackAudioThreadIterate (SDL_AudioDevice *device)
void SDL_PlaybackAudioThreadSetup (SDL_AudioDevice *device)
void SDL_PlaybackAudioThreadShutdown (SDL_AudioDevice *device)
void SDL_QuitAudio (void)
bool SDL_RecordingAudioThreadIterate (SDL_AudioDevice *device)
void SDL_RecordingAudioThreadSetup (SDL_AudioDevice *device)
void SDL_RecordingAudioThreadShutdown (SDL_AudioDevice *device)
bool SDLCALL SDL_ResumeAudioDevice (SDL_AudioDeviceID devid)
bool SDL_ResumeAudioStreamDevice (SDL_AudioStream *stream)
bool SDL_SetAudioDeviceGain (SDL_AudioDeviceID devid, float gain)
bool SDL_SetAudioPostmixCallback (SDL_AudioDeviceID devid, SDL_AudioPostmixCallback callback, void *userdata)
void SDL_UnbindAudioStream (SDL_AudioStream *stream)
void SDL_UnbindAudioStreams (SDL_AudioStream *const *streams, int num_streams)
void SDL_UpdateAudio (void)
void SDL_UpdatedAudioDeviceFormat (SDL_AudioDevice *device)
static void SerializePhysicalDeviceClose (SDL_AudioDevice *device)
static bool SetLogicalAudioDevicePauseState (SDL_AudioDeviceID devid, int value)
static bool TestDeviceHandleCallback (SDL_AudioDevice *device, void *handle)
void UnrefPhysicalAudioDevice (SDL_AudioDevice *device)
static void UpdateAudioStreamFormatsPhysical (SDL_AudioDevice *device)
static void ZombieFlushRecording (SDL_AudioDevice *device)
static Uint8 * ZombieGetDeviceBuf (SDL_AudioDevice *device, int *buffer_size)
static bool ZombiePlayDevice (SDL_AudioDevice *device, const Uint8 *buffer, int buflen)
static int ZombieRecordDevice (SDL_AudioDevice *device, void *buffer, int buflen)
static bool ZombieWaitDevice (SDL_AudioDevice *device)
Variables
static const AudioBootStrap *const bootstrap []
static SDL_AudioDriver current_audio
static const AudioBootStrap * deduped_bootstrap [SDL_arraysize(bootstrap) - 1]
static const SDL_AudioFormat format_list [8][8+1]
static SDL_AtomicInt last_device_instance_id
Macro Definition Documentation
CASE
#define CASE (X)
Value:
    case X: return #X;
Referenced by SDL_GetAudioFormatName().
CHECK_FMT_STRING
#define CHECK_FMT_STRING (x)
Value:
if (SDL_strcmp(string, #x) == 0) { return SDL_AUDIO_##x; }
Referenced by ParseAudioFormatString().
FILL_STUB
#define FILL_STUB (x)
Value:
if (!current_audio.impl.x) { current_audio.impl.x = SDL_Audio##x##_Default; }
Referenced by CompleteAudioEntryPoints().
NATIVE
#define NATIVE (type)
Value:
SDL_AUDIO_##type##LE
NUM_FORMATS
#define NUM_FORMATS 8
Referenced by SDL_ClosestAudioFormats().
SWAPPED
#define SWAPPED (type)
Value:
SDL_AUDIO_##type##BE
Typedef Documentation
CountAudioDevicesData
typedef struct CountAudioDevicesData CountAudioDevicesData
FindAudioDeviceByCallbackData
typedef struct FindAudioDeviceByCallbackData FindAudioDeviceByCallbackData
FindLowestDeviceIDData
typedef struct FindLowestDeviceIDData FindLowestDeviceIDData
Function Documentation
AssignAudioDeviceInstanceId()
SDL_AudioDeviceID AssignAudioDeviceInstanceId (bool recording, bool islogical) static
{
    /* Assign an instance id! Start at 2, in case there are things from the SDL2 era that still think 1 is a special value.
       Also, make sure we don't assign SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, etc. */
    // The bottom two bits of the instance id tells you if it's an playback device (1<<0), and if it's a physical device (1<<1).
    const SDL_AudioDeviceID flags = (recording ? 0 : (1<<0)) | (islogical ? 0 : (1<<1));
    const SDL_AudioDeviceID instance_id = (((SDL_AudioDeviceID) (SDL_AtomicIncRef(&last_device_instance_id) + 1)) << 2) | flags;
    SDL_assert( (instance_id >= 2) && (instance_id < SDL_AUDIO_DEVICE_DEFAULT_RECORDING) );
    return instance_id;
}
References last_device_instance_id, SDL_assert, SDL_AtomicIncRef, and SDL_AUDIO_DEVICE_DEFAULT_RECORDING.
Referenced by CreatePhysicalAudioDevice(), and SDL_OpenAudioDevice().
AudioDeviceCanUseSimpleCopy()
bool AudioDeviceCanUseSimpleCopy (SDL_AudioDevice * device) static
{
    SDL_assert(device != NULL);
    return (
        device->logical_devices &&  // there's a logical device
        !device->logical_devices->next &&  // there's only _ONE_ logical device
        !device->logical_devices->postmix && // there isn't a postmix callback
        device->logical_devices->bound_streams &&  // there's a bound stream
        !device->logical_devices->bound_streams->next_binding  // there's only _ONE_ bound stream.
    );
}
References SDL_LogicalAudioDevice::bound_streams, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, SDL_AudioStream::next_binding, NULL, SDL_LogicalAudioDevice::postmix, and SDL_assert.
Referenced by SDL_PlaybackAudioThreadIterate(), and UpdateAudioStreamFormatsPhysical().
ClosePhysicalAudioDevice()
void ClosePhysicalAudioDevice (SDL_AudioDevice * device) static
{
    SerializePhysicalDeviceClose(device);
    SDL_SetAtomicInt(&device->shutdown, 1);
    // YOU MUST PROTECT KEY POINTS WITH SerializePhysicalDeviceClose() WHILE THE THREAD JOINS
    SDL_UnlockMutex(device->lock);
    if (device->thread) {
        SDL_WaitThread(device->thread, NULL);
        device->thread = NULL;
    }
    if (device->currently_opened) {
        current_audio.impl.CloseDevice(device);  // if ProvidesOwnCallbackThread, this must join on any existing device thread before returning!
        device->currently_opened = false;
        device->hidden = NULL;  // just in case.
    }
    SDL_LockMutex(device->lock);
    SDL_SetAtomicInt(&device->shutdown, 0);  // ready to go again.
    SDL_BroadcastCondition(device->close_cond);  // release anyone waiting in SerializePhysicalDeviceClose; they'll still block until we release device->lock, though.
    SDL_aligned_free(device->work_buffer);
    device->work_buffer = NULL;
    SDL_aligned_free(device->mix_buffer);
    device->mix_buffer = NULL;
    SDL_aligned_free(device->postmix_buffer);
    device->postmix_buffer = NULL;
    SDL_copyp(&device->spec, &device->default_spec);
    device->sample_frames = 0;
    device->silence_value = SDL_GetSilenceValueForFormat(device->spec.format);
}
References SDL_AudioDevice::close_cond, current_audio, SDL_AudioDevice::currently_opened, SDL_AudioDevice::default_spec, SDL_AudioSpec::format, SDL_AudioDevice::hidden, SDL_AudioDevice::lock, SDL_AudioDevice::mix_buffer, NULL, SDL_AudioDevice::postmix_buffer, SDL_AudioDevice::sample_frames, SDL_aligned_free(), SDL_BroadcastCondition(), SDL_copyp, SDL_GetSilenceValueForFormat(), SDL_LockMutex(), SDL_SetAtomicInt(), SDL_UnlockMutex(), SDL_WaitThread(), SerializePhysicalDeviceClose(), SDL_AudioDevice::shutdown, SDL_AudioDevice::silence_value, SDL_AudioDevice::spec, SDL_AudioDevice::thread, and SDL_AudioDevice::work_buffer.
Referenced by DestroyPhysicalAudioDevice(), OpenPhysicalAudioDevice(), SDL_CloseAudioDevice(), and SDL_DefaultAudioDeviceChanged().
CompleteAudioEntryPoints()
void CompleteAudioEntryPoints (void) static
{
    #define FILL_STUB(x) if (!current_audio.impl.x) { current_audio.impl.x = SDL_Audio##x##_Default; }
    FILL_STUB(DetectDevices);
    FILL_STUB(OpenDevice);
    FILL_STUB(ThreadInit);
    FILL_STUB(ThreadDeinit);
    FILL_STUB(WaitDevice);
    FILL_STUB(PlayDevice);
    FILL_STUB(GetDeviceBuf);
    FILL_STUB(WaitRecordingDevice);
    FILL_STUB(RecordDevice);
    FILL_STUB(FlushRecording);
    FILL_STUB(CloseDevice);
    FILL_STUB(FreeDeviceHandle);
    FILL_STUB(DeinitializeStart);
    FILL_STUB(Deinitialize);
    #undef FILL_STUB
}
References FILL_STUB.
Referenced by SDL_InitAudio().
CountAudioDevices()
bool SDLCALL CountAudioDevices (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    CountAudioDevicesData *data = (CountAudioDevicesData *) userdata;
    const SDL_AudioDeviceID devid = (SDL_AudioDeviceID) (uintptr_t) key;
    // bit #0 of devid is set for playback devices and unset for recording.
    // bit #1 of devid is set for physical devices and unset for logical.
    const bool devid_recording = !(devid & (1<<0));
    const bool isphysical = !!(devid & (1<<1));
    if (isphysical && (devid_recording == data->recording)) {
        SDL_assert(data->devs_seen < data->num_devices);
        SDL_AudioDevice *device = (SDL_AudioDevice *) value;  // this is normally risky, but we hold the device_hash_lock here.
        const bool zombie = SDL_GetAtomicInt(&device->zombie) != 0;
        if (zombie) {
            data->devs_skipped++;
        } else {
            data->result[data->devs_seen++] = devid;
        }
    }
    return true;  // keep iterating.
}
References SDL_assert, SDL_GetAtomicInt(), SDLCALL, and SDL_AudioDevice::zombie.
Referenced by GetAudioDevices().
CreateAudioPlaybackDevice()
SDL_AudioDevice * CreateAudioPlaybackDevice (const char * name, const SDL_AudioSpec * spec, void * handle) static
{
    return CreatePhysicalAudioDevice(name, false, spec, handle, &current_audio.playback_device_count);
}
References CreatePhysicalAudioDevice(), and current_audio.
Referenced by SDL_AddAudioDevice().
CreateAudioRecordingDevice()
SDL_AudioDevice * CreateAudioRecordingDevice (const char * name, const SDL_AudioSpec * spec, void * handle) static
{
    SDL_assert(current_audio.impl.HasRecordingSupport);
    return CreatePhysicalAudioDevice(name, true, spec, handle, &current_audio.recording_device_count);
}
References CreatePhysicalAudioDevice(), current_audio, and SDL_assert.
Referenced by SDL_AddAudioDevice().
CreatePhysicalAudioDevice()
SDL_AudioDevice * CreatePhysicalAudioDevice (const char * name, bool recording, const SDL_AudioSpec * spec, void * handle, SDL_AtomicInt * device_count) static
{
    SDL_assert(name != NULL);
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    const int shutting_down = SDL_GetAtomicInt(&current_audio.shutting_down);
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    if (shutting_down) {
        return NULL;  // we're shutting down, don't add any devices that are hotplugged at the last possible moment.
    }
    SDL_AudioDevice *device = (SDL_AudioDevice *)SDL_calloc(1, sizeof(SDL_AudioDevice));
    if (!device) {
        return NULL;
    }
    device->name = SDL_strdup(name);
    if (!device->name) {
        SDL_free(device);
        return NULL;
    }
    device->lock = SDL_CreateMutex();
    if (!device->lock) {
        SDL_free(device->name);
        SDL_free(device);
        return NULL;
    }
    device->close_cond = SDL_CreateCondition();
    if (!device->close_cond) {
        SDL_DestroyMutex(device->lock);
        SDL_free(device->name);
        SDL_free(device);
        return NULL;
    }
    SDL_SetAtomicInt(&device->shutdown, 0);
    SDL_SetAtomicInt(&device->zombie, 0);
    device->recording = recording;
    SDL_copyp(&device->spec, spec);
    SDL_copyp(&device->default_spec, spec);
    device->sample_frames = SDL_GetDefaultSampleFramesFromFreq(device->spec.freq);
    device->silence_value = SDL_GetSilenceValueForFormat(device->spec.format);
    device->handle = handle;
    device->instance_id = AssignAudioDeviceInstanceId(recording, /*islogical=*/false);
    SDL_LockRWLockForWriting(current_audio.device_hash_lock);
    if (SDL_InsertIntoHashTable(current_audio.device_hash, (const void *) (uintptr_t) device->instance_id, device, false)) {
        SDL_AddAtomicInt(device_count, 1);
    } else {
        SDL_DestroyCondition(device->close_cond);
        SDL_DestroyMutex(device->lock);
        SDL_free(device->name);
        SDL_free(device);
        device = NULL;
    }
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    RefPhysicalAudioDevice(device);  // unref'd on device disconnect.
    return device;
}
References AssignAudioDeviceInstanceId(), SDL_AudioDevice::close_cond, current_audio, SDL_AudioDevice::default_spec, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::handle, SDL_AudioDevice::instance_id, SDL_AudioDevice::lock, SDL_AudioDevice::name, NULL, SDL_AudioDevice::recording, RefPhysicalAudioDevice(), SDL_AudioDevice::sample_frames, SDL_AddAtomicInt(), SDL_assert, SDL_calloc(), SDL_copyp, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_free(), SDL_GetAtomicInt(), SDL_GetDefaultSampleFramesFromFreq(), SDL_GetSilenceValueForFormat(), SDL_InsertIntoHashTable(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_SetAtomicInt(), SDL_strdup(), SDL_UnlockRWLock(), SDL_AudioDevice::shutdown, SDL_AudioDevice::silence_value, SDL_AudioDevice::spec, and SDL_AudioDevice::zombie.
Referenced by CreateAudioPlaybackDevice(), and CreateAudioRecordingDevice().
DestroyLogicalAudioDevice()
void DestroyLogicalAudioDevice (SDL_LogicalAudioDevice * logdev) static
{
    // Remove ourselves from the device_hash hashtable.
    if (current_audio.device_hash) {  // will be NULL while shutting down.
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        SDL_RemoveFromHashTable(current_audio.device_hash, (const void *) (uintptr_t) logdev->instance_id);
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
    // remove ourselves from the physical device's list of logical devices.
    if (logdev->next) {
        logdev->next->prev = logdev->prev;
    }
    if (logdev->prev) {
        logdev->prev->next = logdev->next;
    }
    if (logdev->physical_device->logical_devices == logdev) {
        logdev->physical_device->logical_devices = logdev->next;
    }
    // unbind any still-bound streams...
    SDL_AudioStream *next;
    for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = next) {
        SDL_LockMutex(stream->lock);
        next = stream->next_binding;
        stream->next_binding = NULL;
        stream->prev_binding = NULL;
        stream->bound_device = NULL;
        SDL_UnlockMutex(stream->lock);
    }
    UpdateAudioStreamFormatsPhysical(logdev->physical_device);
    SDL_free(logdev);
}
References SDL_LogicalAudioDevice::bound_streams, current_audio, SDL_LogicalAudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, NULL, SDL_LogicalAudioDevice::physical_device, SDL_LogicalAudioDevice::prev, SDL_free(), SDL_LockMutex(), SDL_LockRWLockForWriting(), SDL_RemoveFromHashTable(), SDL_UnlockMutex(), SDL_UnlockRWLock(), and UpdateAudioStreamFormatsPhysical().
Referenced by DestroyPhysicalAudioDevice(), and SDL_CloseAudioDevice().
DestroyOnePhysicalAudioDevice()
bool SDLCALL DestroyOnePhysicalAudioDevice (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    // bit #1 of devid is set for physical devices and unset for logical.
    const SDL_AudioDeviceID devid = (SDL_AudioDeviceID) (uintptr_t) key;
    const bool isphysical = !!(devid & (1<<1));
    if (isphysical) {
        SDL_AudioDevice *dev = (SDL_AudioDevice *) value;
        SDL_assert(dev->instance_id == devid);
        DestroyPhysicalAudioDevice(dev);
    }
    return true;  // keep iterating.
}
References DestroyPhysicalAudioDevice(), SDL_AudioDevice::instance_id, SDL_assert, and SDLCALL.
Referenced by SDL_QuitAudio().
DestroyPhysicalAudioDevice()
void DestroyPhysicalAudioDevice (SDL_AudioDevice * device) static
{
    if (!device) {
        return;
    }
    // Destroy any logical devices that still exist...
    SDL_LockMutex(device->lock);  // don't use ObtainPhysicalAudioDeviceObj because we don't want to change refcounts while destroying.
    while (device->logical_devices) {
        DestroyLogicalAudioDevice(device->logical_devices);
    }
    ClosePhysicalAudioDevice(device);
    current_audio.impl.FreeDeviceHandle(device);
    SDL_UnlockMutex(device->lock);  // don't use ReleaseAudioDevice because we don't want to change refcounts while destroying.
    SDL_DestroyMutex(device->lock);
    SDL_DestroyCondition(device->close_cond);
    SDL_free(device->work_buffer);
    SDL_free(device->chmap);
    SDL_free(device->name);
    SDL_free(device);
}
References SDL_AudioDevice::chmap, SDL_AudioDevice::close_cond, ClosePhysicalAudioDevice(), current_audio, DestroyLogicalAudioDevice(), SDL_AudioDevice::lock, SDL_AudioDevice::logical_devices, SDL_AudioDevice::name, SDL_DestroyCondition(), SDL_DestroyMutex(), SDL_free(), SDL_LockMutex(), SDL_UnlockMutex(), and SDL_AudioDevice::work_buffer.
Referenced by DestroyOnePhysicalAudioDevice(), and UnrefPhysicalAudioDevice().
FindAudioDeviceByCallback()
bool SDLCALL FindAudioDeviceByCallback (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    FindAudioDeviceByCallbackData *data = (FindAudioDeviceByCallbackData *) userdata;
    const SDL_AudioDeviceID devid = (SDL_AudioDeviceID) (uintptr_t) key;
    // bit #1 of devid is set for physical devices and unset for logical.
    const bool isphysical = !!(devid & (1<<1));
    if (isphysical) {
        SDL_AudioDevice *device = (SDL_AudioDevice *) value;
        if (data->callback(device, data->userdata)) {  // found it?
            data->retval = device;
            SDL_assert(data->retval->instance_id == devid);
            return false;  // stop iterating, we found it.
        }
    }
    return true;  // keep iterating.
}
References SDL_assert, and SDLCALL.
Referenced by SDL_FindPhysicalAudioDeviceByCallback().
FindLowestDeviceID()
bool SDLCALL FindLowestDeviceID (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    FindLowestDeviceIDData *data = (FindLowestDeviceIDData *) userdata;
    const SDL_AudioDeviceID devid = (SDL_AudioDeviceID) (uintptr_t) key;
    // bit #0 of devid is set for playback devices and unset for recording.
    // bit #1 of devid is set for physical devices and unset for logical.
    const bool devid_recording = !(devid & (1 << 0));
    const bool isphysical = !!(devid & (1 << 1));
    if (isphysical && (devid_recording == data->recording) && (devid < data->highest)) {
        data->highest = devid;
        data->result = (SDL_AudioDevice *) value;
        SDL_assert(data->result->instance_id == devid);
    }
    return true;  // keep iterating.
}
References SDL_assert, and SDLCALL.
Referenced by GetFirstAddedAudioDevice().
GetAudioDevices()
SDL_AudioDeviceID * GetAudioDevices (int * count, bool recording) static
{
    SDL_AudioDeviceID *result = NULL;
    int num_devices = 0;
    if (SDL_GetCurrentAudioDriver()) {
        SDL_LockRWLockForReading(current_audio.device_hash_lock);
        {
            num_devices = SDL_GetAtomicInt(recording ? &current_audio.recording_device_count : &current_audio.playback_device_count);
            result = (SDL_AudioDeviceID *) SDL_malloc((num_devices + 1) * sizeof (SDL_AudioDeviceID));
            if (result) {
                CountAudioDevicesData data = { 0, 0, num_devices, result, recording };
                SDL_IterateHashTable(current_audio.device_hash, CountAudioDevices, &data);
                SDL_assert((data.devs_seen + data.devs_skipped) == num_devices);
                num_devices = data.devs_seen;  // might be less if we skipped any.
                result[num_devices] = 0;  // null-terminated.
            }
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    } else {
        SDL_SetError("Audio subsystem is not initialized");
    }
    if (count) {
        if (result) {
            *count = num_devices;
        } else {
            *count = 0;
        }
    }
    return result;
}
References count, CountAudioDevices(), current_audio, NULL, SDL_assert, SDL_GetAtomicInt(), SDL_GetCurrentAudioDriver(), SDL_IterateHashTable(), SDL_LockRWLockForReading(), SDL_malloc(), SDL_SetError(), and SDL_UnlockRWLock().
Referenced by SDL_GetAudioPlaybackDevices(), and SDL_GetAudioRecordingDevices().
GetFirstAddedAudioDevice()
SDL_AudioDevice * GetFirstAddedAudioDevice (const bool recording) static
{
    const SDL_AudioDeviceID highest = SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK;  // According to AssignAudioDeviceInstanceId, nothing can have a value this large.
    // (Device IDs increase as new devices are added, so the first device added has the lowest SDL_AudioDeviceID value.)
    FindLowestDeviceIDData data = { recording, highest, NULL };
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    SDL_IterateHashTable(current_audio.device_hash, FindLowestDeviceID, &data);
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    return data.result;
}
References current_audio, FindLowestDeviceID(), NULL, SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, SDL_IterateHashTable(), SDL_LockRWLockForReading(), and SDL_UnlockRWLock().
Referenced by SDL_InitAudio().
HashAudioDeviceID()
Uint32 SDLCALL HashAudioDeviceID (void * userdata, const void * key) static
{
    // shift right 2, to dump the first two bits, since these are flags
    //  (recording vs playback, logical vs physical) and the rest are unique incrementing integers.
    return ((Uint32) ((uintptr_t) key)) >> 2;
}
References SDLCALL.
Referenced by SDL_InitAudio().
MixFloat32Audio()
void MixFloat32Audio (float * dst, const float * src, const int buffer_size) static
{
    if (!SDL_MixAudio((Uint8 *) dst, (const Uint8 *) src, SDL_AUDIO_F32, buffer_size, 1.0f)) {
        SDL_assert(!"This shouldn't happen.");
    }
}
References SDL_assert, SDL_AUDIO_F32, and SDL_MixAudio().
Referenced by SDL_PlaybackAudioThreadIterate().
ObtainLogicalAudioDevice()
SDL_LogicalAudioDevice * ObtainLogicalAudioDevice (SDL_AudioDeviceID devid, SDL_AudioDevice ** _device) static
{
    SDL_assert(_device != NULL);
    if (!SDL_GetCurrentAudioDriver()) {
        SDL_SetError("Audio subsystem is not initialized");
        *_device = NULL;
        return NULL;
    }
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = NULL;
    // bit #1 of devid is set for physical devices and unset for logical.
    const bool islogical = !(devid & (1<<1));
    if (islogical) {  // don't bother looking if it's not a logical device id value.
        SDL_LockRWLockForReading(current_audio.device_hash_lock);
        SDL_FindInHashTable(current_audio.device_hash, (const void *) (uintptr_t) devid, (const void **) &logdev);
        if (logdev) {
            SDL_assert(logdev->instance_id == devid);
            device = logdev->physical_device;
            SDL_assert(device != NULL);
            RefPhysicalAudioDevice(device);  // reference it, in case the logical device migrates to a new default.
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
        if (logdev) {
            // we have to release the device_hash_lock before we take the device lock, to avoid deadlocks, so do a loop
            //  to make sure the correct physical device gets locked, in case we're in a race with the default changing.
            while (true) {
                SDL_LockMutex(device->lock);
                SDL_AudioDevice *recheck_device = (SDL_AudioDevice *) SDL_GetAtomicPointer((void **) &logdev->physical_device);
                if (device == recheck_device) {
                    break;
                }
                // default changed from under us! Try again!
                RefPhysicalAudioDevice(recheck_device);
                SDL_UnlockMutex(device->lock);
                UnrefPhysicalAudioDevice(device);
                device = recheck_device;
            }
        }
    }
    if (!logdev) {
        SDL_SetError("Invalid audio device instance ID");
    }
    *_device = device;
    return logdev;
}
References current_audio, SDL_AudioDevice::lock, NULL, RefPhysicalAudioDevice(), SDL_assert, SDL_FindInHashTable(), SDL_GetAtomicPointer(), SDL_GetCurrentAudioDriver(), SDL_LockMutex(), SDL_LockRWLockForReading(), SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_SetError(), SDL_UnlockMutex(), SDL_UnlockRWLock(), and UnrefPhysicalAudioDevice().
Referenced by ObtainPhysicalAudioDevice(), SDL_AudioDevicePaused(), SDL_BindAudioStreams(), SDL_CloseAudioDevice(), SDL_GetAudioDeviceGain(), SDL_OpenAudioDevice(), SDL_OpenAudioDeviceStream(), SDL_SetAudioDeviceGain(), SDL_SetAudioPostmixCallback(), and SetLogicalAudioDevicePauseState().
ObtainPhysicalAudioDevice()
SDL_AudioDevice * ObtainPhysicalAudioDevice (SDL_AudioDeviceID devid) static
{
    SDL_AudioDevice *device = NULL;
    // bit #1 of devid is set for physical devices and unset for logical.
    const bool islogical = !(devid & (1<<1));
    if (islogical) {
        ObtainLogicalAudioDevice(devid, &device);
    } else if (!SDL_GetCurrentAudioDriver()) {  // (the `islogical` path, above, checks this in ObtainLogicalAudioDevice.)
        SDL_SetError("Audio subsystem is not initialized");
    } else {
        SDL_LockRWLockForReading(current_audio.device_hash_lock);
        SDL_FindInHashTable(current_audio.device_hash, (const void *) (uintptr_t) devid, (const void **) &device);
        SDL_assert(device->instance_id == devid);
        SDL_UnlockRWLock(current_audio.device_hash_lock);
        if (!device) {
            SDL_SetError("Invalid audio device instance ID");
        } else {
            ObtainPhysicalAudioDeviceObj(device);
        }
    }
    return device;
}
References current_audio, NULL, ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), SDL_assert, SDL_FindInHashTable(), SDL_GetCurrentAudioDriver(), SDL_LockRWLockForReading(), SDL_SetError(), and SDL_UnlockRWLock().
Referenced by ObtainPhysicalAudioDeviceDefaultAllowed(), and SDL_DefaultAudioDeviceChanged().
ObtainPhysicalAudioDeviceDefaultAllowed()
SDL_AudioDevice * ObtainPhysicalAudioDeviceDefaultAllowed (SDL_AudioDeviceID devid) static
{
    const bool wants_default = ((devid == SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK) || (devid == SDL_AUDIO_DEVICE_DEFAULT_RECORDING));
    if (!wants_default) {
        return ObtainPhysicalAudioDevice(devid);
    }
    const SDL_AudioDeviceID orig_devid = devid;
    while (true) {
        SDL_LockRWLockForReading(current_audio.device_hash_lock);
        if (orig_devid == SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK) {
            devid = current_audio.default_playback_device_id;
        } else if (orig_devid == SDL_AUDIO_DEVICE_DEFAULT_RECORDING) {
            devid = current_audio.default_recording_device_id;
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
        if (devid == 0) {
            SDL_SetError("No default audio device available");
            break;
        }
        SDL_AudioDevice *device = ObtainPhysicalAudioDevice(devid);
        if (!device) {
            break;
        }
        // make sure the default didn't change while we were waiting for the lock...
        bool got_it = false;
        SDL_LockRWLockForReading(current_audio.device_hash_lock);
        if ((orig_devid == SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK) && (devid == current_audio.default_playback_device_id)) {
            got_it = true;
        } else if ((orig_devid == SDL_AUDIO_DEVICE_DEFAULT_RECORDING) && (devid == current_audio.default_recording_device_id)) {
            got_it = true;
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
        if (got_it) {
            return device;
        }
        ReleaseAudioDevice(device);  // let it go and try again.
    }
    return NULL;
}
References current_audio, NULL, ObtainPhysicalAudioDevice(), ReleaseAudioDevice(), SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, SDL_AUDIO_DEVICE_DEFAULT_RECORDING, SDL_LockRWLockForReading(), SDL_SetError(), and SDL_UnlockRWLock().
Referenced by SDL_GetAudioDeviceChannelMap(), SDL_GetAudioDeviceFormat(), and SDL_OpenAudioDevice().
ObtainPhysicalAudioDeviceObj()
void ObtainPhysicalAudioDeviceObj (SDL_AudioDevice * device) static
{
    if (device) {
        RefPhysicalAudioDevice(device);
        SDL_LockMutex(device->lock);
    }
}
References RefPhysicalAudioDevice(), SDL_LockMutex(), and SDL_NO_THREAD_SAFETY_ANALYSIS.
Referenced by ObtainPhysicalAudioDevice(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChanged(), and SDL_DefaultAudioDeviceChanged().
OnAudioStreamCreated()
void OnAudioStreamCreated (SDL_AudioStream * stream)
{
    SDL_assert(stream != NULL);
    // NOTE that you can create an audio stream without initializing the audio subsystem,
    //  but it will not be automatically destroyed during a later call to SDL_Quit!
    //  You must explicitly destroy it yourself!
    if (current_audio.device_hash_lock) {
        // this isn't really part of the "device list" but it's a convenient lock to use here.
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        if (current_audio.existing_streams) {
            current_audio.existing_streams->prev = stream;
        }
        stream->prev = NULL;
        stream->next = current_audio.existing_streams;
        current_audio.existing_streams = stream;
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
}
References current_audio, NULL, SDL_assert, SDL_LockRWLockForWriting(), and SDL_UnlockRWLock().
Referenced by SDL_CreateAudioStream().
OnAudioStreamDestroy()
void OnAudioStreamDestroy (SDL_AudioStream * stream)
{
    SDL_assert(stream != NULL);
    // NOTE that you can create an audio stream without initializing the audio subsystem,
    //  but it will not be automatically destroyed during a later call to SDL_Quit!
    //  You must explicitly destroy it yourself!
    if (current_audio.device_hash_lock) {
        // this isn't really part of the "device list" but it's a convenient lock to use here.
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        if (stream->prev) {
            stream->prev->next = stream->next;
        }
        if (stream->next) {
            stream->next->prev = stream->prev;
        }
        if (stream == current_audio.existing_streams) {
            current_audio.existing_streams = stream->next;
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
}
References current_audio, NULL, SDL_assert, SDL_LockRWLockForWriting(), and SDL_UnlockRWLock().
Referenced by SDL_DestroyAudioStream().
OpenPhysicalAudioDevice()
bool OpenPhysicalAudioDevice (SDL_AudioDevice * device, const SDL_AudioSpec * inspec) static
{
    SerializePhysicalDeviceClose(device);  // make sure another thread that's closing didn't release the lock to let the device thread join...
    if (device->currently_opened) {
        return true;  // we're already good.
    }
    // Just pretend to open a zombie device. It can still collect logical devices on a default device under the assumption they will all migrate when the default device is officially changed.
    if (SDL_GetAtomicInt(&device->zombie)) {
        return true;  // Braaaaaaaaains.
    }
    // These start with the backend's implementation, but we might swap them out with zombie versions later.
    device->WaitDevice = current_audio.impl.WaitDevice;
    device->PlayDevice = current_audio.impl.PlayDevice;
    device->GetDeviceBuf = current_audio.impl.GetDeviceBuf;
    device->WaitRecordingDevice = current_audio.impl.WaitRecordingDevice;
    device->RecordDevice = current_audio.impl.RecordDevice;
    device->FlushRecording = current_audio.impl.FlushRecording;
    SDL_AudioSpec spec;
    SDL_copyp(&spec, inspec ? inspec : &device->default_spec);
    PrepareAudioFormat(device->recording, &spec);
    /* We impose a simple minimum on device formats. This prevents something low quality, like an old game using S8/8000Hz audio,
       from ruining a music thing playing at CD quality that tries to open later, or some VoIP library that opens for mono output
       ruining your surround-sound game because it got there first.
       These are just requests! The backend may change any of these values during OpenDevice method! */
    const SDL_AudioFormat minimum_format = device->recording ? DEFAULT_AUDIO_RECORDING_FORMAT : DEFAULT_AUDIO_PLAYBACK_FORMAT;
    const int minimum_channels = device->recording ? DEFAULT_AUDIO_RECORDING_CHANNELS : DEFAULT_AUDIO_PLAYBACK_CHANNELS;
    const int minimum_freq = device->recording ? DEFAULT_AUDIO_RECORDING_FREQUENCY : DEFAULT_AUDIO_PLAYBACK_FREQUENCY;
    device->spec.format = (SDL_AUDIO_BITSIZE(minimum_format) >= SDL_AUDIO_BITSIZE(spec.format)) ? minimum_format : spec.format;
    device->spec.channels = SDL_max(minimum_channels, spec.channels);
    device->spec.freq = SDL_max(minimum_freq, spec.freq);
    device->sample_frames = SDL_GetDefaultSampleFramesFromFreq(device->spec.freq);
    SDL_UpdatedAudioDeviceFormat(device);  // start this off sane.
    device->currently_opened = true;  // mark this true even if impl.OpenDevice fails, so we know to clean up.
    if (!current_audio.impl.OpenDevice(device)) {
        ClosePhysicalAudioDevice(device);  // clean up anything the backend left half-initialized.
        return false;
    }
    SDL_UpdatedAudioDeviceFormat(device);  // in case the backend changed things and forgot to call this.
    // Allocate a scratch audio buffer
    device->work_buffer = (Uint8 *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
    if (!device->work_buffer) {
        ClosePhysicalAudioDevice(device);
        return false;
    }
    if (device->spec.format != SDL_AUDIO_F32) {
        device->mix_buffer = (Uint8 *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
        if (!device->mix_buffer) {
            ClosePhysicalAudioDevice(device);
            return false;
        }
    }
    // Start the audio thread if necessary
    if (!current_audio.impl.ProvidesOwnCallbackThread) {
        char threadname[64];
        SDL_GetAudioThreadName(device, threadname, sizeof (threadname));
        device->thread = SDL_CreateThread(device->recording ? RecordingAudioThread : PlaybackAudioThread, threadname, device);
        if (!device->thread) {
            ClosePhysicalAudioDevice(device);
            return SDL_SetError("Couldn't create audio thread");
        }
    }
    return true;
}
References SDL_AudioSpec::channels, ClosePhysicalAudioDevice(), current_audio, SDL_AudioDevice::currently_opened, DEFAULT_AUDIO_PLAYBACK_CHANNELS, DEFAULT_AUDIO_PLAYBACK_FORMAT, DEFAULT_AUDIO_PLAYBACK_FREQUENCY, DEFAULT_AUDIO_RECORDING_CHANNELS, DEFAULT_AUDIO_RECORDING_FORMAT, DEFAULT_AUDIO_RECORDING_FREQUENCY, SDL_AudioDevice::default_spec, SDL_AudioDevice::FlushRecording, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::GetDeviceBuf, SDL_AudioDevice::mix_buffer, PlaybackAudioThread(), SDL_AudioDevice::PlayDevice, PrepareAudioFormat(), SDL_AudioDevice::RecordDevice, SDL_AudioDevice::recording, RecordingAudioThread(), SDL_AudioDevice::sample_frames, SDL_aligned_alloc(), SDL_AUDIO_BITSIZE, SDL_AUDIO_F32, SDL_copyp, SDL_CreateThread, SDL_GetAtomicInt(), SDL_GetAudioThreadName(), SDL_GetDefaultSampleFramesFromFreq(), SDL_GetSIMDAlignment(), SDL_max, SDL_SetError(), SDL_UpdatedAudioDeviceFormat(), SerializePhysicalDeviceClose(), SDL_AudioDevice::spec, SDL_AudioDevice::thread, SDL_AudioDevice::WaitDevice, SDL_AudioDevice::WaitRecordingDevice, SDL_AudioDevice::work_buffer, SDL_AudioDevice::work_buffer_size, and SDL_AudioDevice::zombie.
Referenced by SDL_DefaultAudioDeviceChanged(), and SDL_OpenAudioDevice().
ParseAudioFormatString()
SDL_AudioFormat ParseAudioFormatString (const char * string) static
{
    if (string) {
        #define CHECK_FMT_STRING(x) if (SDL_strcmp(string, #x) == 0) { return SDL_AUDIO_##x; }
        CHECK_FMT_STRING(U8);
        CHECK_FMT_STRING(S8);
        CHECK_FMT_STRING(S16LE);
        CHECK_FMT_STRING(S16BE);
        CHECK_FMT_STRING(S16);
        CHECK_FMT_STRING(S32LE);
        CHECK_FMT_STRING(S32BE);
        CHECK_FMT_STRING(S32);
        CHECK_FMT_STRING(F32LE);
        CHECK_FMT_STRING(F32BE);
        CHECK_FMT_STRING(F32);
        #undef CHECK_FMT_STRING
    }
    return SDL_AUDIO_UNKNOWN;
}
References CHECK_FMT_STRING, and SDL_AUDIO_UNKNOWN.
Referenced by PrepareAudioFormat().
PlaybackAudioThread()
int SDLCALL PlaybackAudioThread (void * devicep) static
{
    SDL_AudioDevice *device = (SDL_AudioDevice *)devicep;
    SDL_assert(device != NULL);
    SDL_assert(!device->recording);
    SDL_PlaybackAudioThreadSetup(device);
    while (SDL_PlaybackAudioThreadIterate(device)) {
        if (!device->WaitDevice(device)) {
            SDL_AudioDeviceDisconnected(device);  // doh. (but don't break out of the loop, just be a zombie for now!)
        }
    }
    SDL_PlaybackAudioThreadShutdown(device);
    return 0;
}
References NULL, SDL_AudioDevice::recording, SDL_assert, SDL_AudioDeviceDisconnected(), SDL_PlaybackAudioThreadIterate(), SDL_PlaybackAudioThreadSetup(), SDL_PlaybackAudioThreadShutdown(), SDLCALL, and SDL_AudioDevice::WaitDevice.
Referenced by OpenPhysicalAudioDevice().
PrepareAudioFormat()
void PrepareAudioFormat (bool recording, SDL_AudioSpec * spec) static
{
    if (spec->freq == 0) {
        spec->freq = recording ? DEFAULT_AUDIO_RECORDING_FREQUENCY : DEFAULT_AUDIO_PLAYBACK_FREQUENCY;
        const char *hint = SDL_GetHint(SDL_HINT_AUDIO_FREQUENCY);
        if (hint) {
            const int val = SDL_atoi(hint);
            if (val > 0) {
                spec->freq = val;
            }
        }
    }
    if (spec->channels == 0) {
        spec->channels = recording ? DEFAULT_AUDIO_RECORDING_CHANNELS : DEFAULT_AUDIO_PLAYBACK_CHANNELS;
        const char *hint = SDL_GetHint(SDL_HINT_AUDIO_CHANNELS);
        if (hint) {
            const int val = SDL_atoi(hint);
            if (val > 0) {
                spec->channels = val;
            }
        }
    }
    if (spec->format == 0) {
        const SDL_AudioFormat val = ParseAudioFormatString(SDL_GetHint(SDL_HINT_AUDIO_FORMAT));
        spec->format = (val != SDL_AUDIO_UNKNOWN) ? val : (recording ? DEFAULT_AUDIO_RECORDING_FORMAT : DEFAULT_AUDIO_PLAYBACK_FORMAT);
    }
}
References SDL_AudioSpec::channels, DEFAULT_AUDIO_PLAYBACK_CHANNELS, DEFAULT_AUDIO_PLAYBACK_FORMAT, DEFAULT_AUDIO_PLAYBACK_FREQUENCY, DEFAULT_AUDIO_RECORDING_CHANNELS, DEFAULT_AUDIO_RECORDING_FORMAT, DEFAULT_AUDIO_RECORDING_FREQUENCY, SDL_AudioSpec::format, SDL_AudioSpec::freq, ParseAudioFormatString(), SDL_atoi(), SDL_AUDIO_UNKNOWN, SDL_GetHint(), SDL_HINT_AUDIO_CHANNELS, SDL_HINT_AUDIO_FORMAT, and SDL_HINT_AUDIO_FREQUENCY.
Referenced by OpenPhysicalAudioDevice().
RecordingAudioThread()
int SDLCALL RecordingAudioThread (void * devicep) static
{
    SDL_AudioDevice *device = (SDL_AudioDevice *)devicep;
    SDL_assert(device != NULL);
    SDL_assert(device->recording);
    SDL_RecordingAudioThreadSetup(device);
    do {
        if (!device->WaitRecordingDevice(device)) {
            SDL_AudioDeviceDisconnected(device);  // doh. (but don't break out of the loop, just be a zombie for now!)
        }
    } while (SDL_RecordingAudioThreadIterate(device));
    SDL_RecordingAudioThreadShutdown(device);
    return 0;
}
References NULL, SDL_AudioDevice::recording, SDL_assert, SDL_AudioDeviceDisconnected(), SDL_RecordingAudioThreadIterate(), SDL_RecordingAudioThreadSetup(), SDL_RecordingAudioThreadShutdown(), SDLCALL, and SDL_AudioDevice::WaitRecordingDevice.
Referenced by OpenPhysicalAudioDevice().
RefPhysicalAudioDevice()
void RefPhysicalAudioDevice (SDL_AudioDevice * device)
{
    SDL_AtomicIncRef(&device->refcount);
}
References SDL_AudioDevice::refcount, and SDL_AtomicIncRef.
Referenced by CreatePhysicalAudioDevice(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), SDL_DefaultAudioDeviceChanged(), SDL_InitAudio(), and SDL_OpenAudioDevice().
ReleaseAudioDevice()
void ReleaseAudioDevice (SDL_AudioDevice * device) static
{
    if (device) {
        SDL_UnlockMutex(device->lock);
        UnrefPhysicalAudioDevice(device);
    }
}
References SDL_NO_THREAD_SAFETY_ANALYSIS, SDL_UnlockMutex(), and UnrefPhysicalAudioDevice().
Referenced by ObtainPhysicalAudioDeviceDefaultAllowed(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChanged(), SDL_AudioDevicePaused(), SDL_BindAudioStreams(), SDL_CloseAudioDevice(), SDL_DefaultAudioDeviceChanged(), SDL_GetAudioDeviceChannelMap(), SDL_GetAudioDeviceFormat(), SDL_GetAudioDeviceGain(), SDL_OpenAudioDevice(), SDL_OpenAudioDeviceStream(), SDL_SetAudioDeviceGain(), SDL_SetAudioPostmixCallback(), and SetLogicalAudioDevicePauseState().
SDL_AddAudioDevice()
SDL_AudioDevice * SDL_AddAudioDevice (bool recording, const char * name, const SDL_AudioSpec * inspec, void * handle)
{
    // device handles MUST be unique! If the target reuses the same handle for hardware with both recording and playback interfaces, wrap it in a pointer you SDL_malloc'd!
    SDL_assert(SDL_FindPhysicalAudioDeviceByHandle(handle) == NULL);
    const SDL_AudioFormat default_format = recording ? DEFAULT_AUDIO_RECORDING_FORMAT : DEFAULT_AUDIO_PLAYBACK_FORMAT;
    const int default_channels = recording ? DEFAULT_AUDIO_RECORDING_CHANNELS : DEFAULT_AUDIO_PLAYBACK_CHANNELS;
    const int default_freq = recording ? DEFAULT_AUDIO_RECORDING_FREQUENCY : DEFAULT_AUDIO_PLAYBACK_FREQUENCY;
    SDL_AudioSpec spec;
    SDL_zero(spec);
    if (!inspec) {
        spec.format = default_format;
        spec.channels = default_channels;
        spec.freq = default_freq;
    } else {
        spec.format = (inspec->format != 0) ? inspec->format : default_format;
        spec.channels = (inspec->channels != 0) ? inspec->channels : default_channels;
        spec.freq = (inspec->freq != 0) ? inspec->freq : default_freq;
    }
    SDL_AudioDevice *device = recording ? CreateAudioRecordingDevice(name, &spec, handle) : CreateAudioPlaybackDevice(name, &spec, handle);
    // Add a device add event to the pending list, to be pushed when the event queue is pumped (away from any of our internal threads).
    if (device) {
        SDL_PendingAudioDeviceEvent *p = (SDL_PendingAudioDeviceEvent *) SDL_malloc(sizeof (SDL_PendingAudioDeviceEvent));
        if (p) {  // if allocation fails, you won't get an event, but we can't help that.
            p->type = SDL_EVENT_AUDIO_DEVICE_ADDED;
            p->devid = device->instance_id;
            p->next = NULL;
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            SDL_assert(current_audio.pending_events_tail != NULL);
            SDL_assert(current_audio.pending_events_tail->next == NULL);
            current_audio.pending_events_tail->next = p;
            current_audio.pending_events_tail = p;
            SDL_UnlockRWLock(current_audio.device_hash_lock);
        }
    }
    return device;
}
References SDL_AudioSpec::channels, CreateAudioPlaybackDevice(), CreateAudioRecordingDevice(), current_audio, DEFAULT_AUDIO_PLAYBACK_CHANNELS, DEFAULT_AUDIO_PLAYBACK_FORMAT, DEFAULT_AUDIO_PLAYBACK_FREQUENCY, DEFAULT_AUDIO_RECORDING_CHANNELS, DEFAULT_AUDIO_RECORDING_FORMAT, DEFAULT_AUDIO_RECORDING_FREQUENCY, SDL_PendingAudioDeviceEvent::devid, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::instance_id, SDL_PendingAudioDeviceEvent::next, NULL, SDL_assert, SDL_EVENT_AUDIO_DEVICE_ADDED, SDL_FindPhysicalAudioDeviceByHandle(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_UnlockRWLock(), SDL_zero, and SDL_PendingAudioDeviceEvent::type.
Referenced by SDL_AudioDetectDevices_Default().
SDL_AudioChannelMapsEqual()
bool SDL_AudioChannelMapsEqual (int channels, const int * channel_map_a, const int * channel_map_b)
{
    if (channel_map_a == channel_map_b) {
        return true;
    } else if ((channel_map_a != NULL) != (channel_map_b != NULL)) {
        return false;
    } else if (channel_map_a && (SDL_memcmp(channel_map_a, channel_map_b, sizeof (*channel_map_a) * channels) != 0)) {
        return false;
    }
    return true;
}
References NULL, and SDL_memcmp().
Referenced by ConvertAudio(), SDL_PlaybackAudioThreadIterate(), and SDL_RecordingAudioThreadIterate().
SDL_AudioCloseDevice_Default()
void SDL_AudioCloseDevice_Default (SDL_AudioDevice * device) static
{ /* no-op. */ }
SDL_AudioDeinitialize_Default()
void SDL_AudioDeinitialize_Default (void) static
{ /* no-op. */ }
SDL_AudioDeinitializeStart_Default()
void SDL_AudioDeinitializeStart_Default (void) static
{ /* no-op. */ }
SDL_AudioDetectDevices_Default()
void SDL_AudioDetectDevices_Default (SDL_AudioDevice ** default_playback, SDL_AudioDevice ** default_recording) static
{
    // you have to write your own implementation if these assertions fail.
    SDL_assert(current_audio.impl.OnlyHasDefaultPlaybackDevice);
    SDL_assert(current_audio.impl.OnlyHasDefaultRecordingDevice || !current_audio.impl.HasRecordingSupport);
    *default_playback = SDL_AddAudioDevice(false, DEFAULT_PLAYBACK_DEVNAME, NULL, (void *)((size_t)0x1));
    if (current_audio.impl.HasRecordingSupport) {
        *default_recording = SDL_AddAudioDevice(true, DEFAULT_RECORDING_DEVNAME, NULL, (void *)((size_t)0x2));
    }
}
References current_audio, DEFAULT_PLAYBACK_DEVNAME, DEFAULT_RECORDING_DEVNAME, NULL, SDL_AddAudioDevice(), and SDL_assert.
SDL_AudioDeviceDisconnected()
void SDL_AudioDeviceDisconnected (SDL_AudioDevice * device)
{
    if (!device) {
        return;
    }
    // Save off removal info in a list so we can send events for each, next
    //  time the event queue pumps, in case something tries to close a device
    //  from an event filter, as this would risk deadlocks and other disasters
    //  if done from the device thread.
    SDL_PendingAudioDeviceEvent pending;
    pending.next = NULL;
    SDL_PendingAudioDeviceEvent *pending_tail = &pending;
    ObtainPhysicalAudioDeviceObj(device);
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    const SDL_AudioDeviceID devid = device->instance_id;
    const bool is_default_device = ((devid == current_audio.default_playback_device_id) || (devid == current_audio.default_recording_device_id));
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    const bool first_disconnect = SDL_CompareAndSwapAtomicInt(&device->zombie, 0, 1);
    if (first_disconnect) {   // if already disconnected this device, don't do it twice.
        // Swap in "Zombie" versions of the usual platform interfaces, so the device will keep
        // making progress until the app closes it. Otherwise, streams might continue to
        // accumulate waste data that never drains, apps that depend on audio callbacks to
        // progress will freeze, etc.
        device->WaitDevice = ZombieWaitDevice;
        device->GetDeviceBuf = ZombieGetDeviceBuf;
        device->PlayDevice = ZombiePlayDevice;
        device->WaitRecordingDevice = ZombieWaitDevice;
        device->RecordDevice = ZombieRecordDevice;
        device->FlushRecording = ZombieFlushRecording;
        // on default devices, dump any logical devices that explicitly opened this device. Things that opened the system default can stay.
        // on non-default devices, dump everything.
        // (by "dump" we mean send a REMOVED event; the zombie will keep consuming audio data for these logical devices until explicitly closed.)
        for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
            if (!is_default_device || !logdev->opened_as_default) {  // if opened as a default, leave it on the zombie device for later migration.
                SDL_PendingAudioDeviceEvent *p = (SDL_PendingAudioDeviceEvent *) SDL_malloc(sizeof (SDL_PendingAudioDeviceEvent));
                if (p) {  // if this failed, no event for you, but you have deeper problems anyhow.
                    p->type = SDL_EVENT_AUDIO_DEVICE_REMOVED;
                    p->devid = logdev->instance_id;
                    p->next = NULL;
                    pending_tail->next = p;
                    pending_tail = p;
                }
            }
        }
        SDL_PendingAudioDeviceEvent *p = (SDL_PendingAudioDeviceEvent *) SDL_malloc(sizeof (SDL_PendingAudioDeviceEvent));
        if (p) {  // if this failed, no event for you, but you have deeper problems anyhow.
            p->type = SDL_EVENT_AUDIO_DEVICE_REMOVED;
            p->devid = device->instance_id;
            p->next = NULL;
            pending_tail->next = p;
            pending_tail = p;
        }
    }
    ReleaseAudioDevice(device);
    if (first_disconnect) {
        if (pending.next) {  // NULL if event is disabled or disaster struck.
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            SDL_assert(current_audio.pending_events_tail != NULL);
            SDL_assert(current_audio.pending_events_tail->next == NULL);
            current_audio.pending_events_tail->next = pending.next;
            current_audio.pending_events_tail = pending_tail;
            SDL_UnlockRWLock(current_audio.device_hash_lock);
        }
        UnrefPhysicalAudioDevice(device);
    }
}
References current_audio, SDL_PendingAudioDeviceEvent::devid, SDL_AudioDevice::FlushRecording, SDL_AudioDevice::GetDeviceBuf, SDL_AudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, SDL_PendingAudioDeviceEvent::next, NULL, ObtainPhysicalAudioDeviceObj(), SDL_AudioDevice::PlayDevice, SDL_AudioDevice::RecordDevice, ReleaseAudioDevice(), SDL_assert, SDL_CompareAndSwapAtomicInt(), SDL_EVENT_AUDIO_DEVICE_REMOVED, SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_UnlockRWLock(), SDL_PendingAudioDeviceEvent::type, UnrefPhysicalAudioDevice(), SDL_AudioDevice::WaitDevice, SDL_AudioDevice::WaitRecordingDevice, SDL_AudioDevice::zombie, ZombieFlushRecording(), ZombieGetDeviceBuf(), ZombiePlayDevice(), ZombieRecordDevice(), and ZombieWaitDevice().
Referenced by PlaybackAudioThread(), RecordingAudioThread(), SDL_PlaybackAudioThreadIterate(), and SDL_RecordingAudioThreadIterate().
SDL_AudioDeviceFormatChanged()
bool SDL_AudioDeviceFormatChanged (SDL_AudioDevice * device, const SDL_AudioSpec * newspec, int new_sample_frames)
{
    ObtainPhysicalAudioDeviceObj(device);
    const bool result = SDL_AudioDeviceFormatChangedAlreadyLocked(device, newspec, new_sample_frames);
    ReleaseAudioDevice(device);
    return result;
}
References ObtainPhysicalAudioDeviceObj(), ReleaseAudioDevice(), and SDL_AudioDeviceFormatChangedAlreadyLocked().
SDL_AudioDeviceFormatChangedAlreadyLocked()
bool SDL_AudioDeviceFormatChangedAlreadyLocked (SDL_AudioDevice * device, const SDL_AudioSpec * newspec, int new_sample_frames)
{
    const int orig_work_buffer_size = device->work_buffer_size;
    // we don't currently have any place where channel maps change from under you, but we can check that if necessary later.
    if (SDL_AudioSpecsEqual(&device->spec, newspec, NULL, NULL) && (new_sample_frames == device->sample_frames)) {
        return true;  // we're already in that format.
    }
    SDL_copyp(&device->spec, newspec);
    UpdateAudioStreamFormatsPhysical(device);
    bool kill_device = false;
    device->sample_frames = new_sample_frames;
    SDL_UpdatedAudioDeviceFormat(device);
    if (device->work_buffer && (device->work_buffer_size > orig_work_buffer_size)) {
        SDL_aligned_free(device->work_buffer);
        device->work_buffer = (Uint8 *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
        if (!device->work_buffer) {
            kill_device = true;
        }
        if (device->postmix_buffer) {
            SDL_aligned_free(device->postmix_buffer);
            device->postmix_buffer = (float *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
            if (!device->postmix_buffer) {
                kill_device = true;
            }
        }
        SDL_aligned_free(device->mix_buffer);
        device->mix_buffer = NULL;
        if (device->spec.format != SDL_AUDIO_F32) {
            device->mix_buffer = (Uint8 *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
            if (!device->mix_buffer) {
                kill_device = true;
            }
        }
    }
    // Post an event for the physical device, and each logical device on this physical device.
    if (!kill_device) {
        // Queue up events to push to the queue next time it pumps (presumably
        //  in a safer thread).
        // !!! FIXME: this duplicates some code we could probably refactor.
        SDL_PendingAudioDeviceEvent pending;
        pending.next = NULL;
        SDL_PendingAudioDeviceEvent *pending_tail = &pending;
        SDL_PendingAudioDeviceEvent *p;
        p = (SDL_PendingAudioDeviceEvent *)SDL_malloc(sizeof(SDL_PendingAudioDeviceEvent));
        if (p) { // if this failed, no event for you, but you have deeper problems anyhow.
            p->type = SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED;
            p->devid = device->instance_id;
            p->next = NULL;
            pending_tail->next = p;
            pending_tail = p;
        }
        for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
            p = (SDL_PendingAudioDeviceEvent *)SDL_malloc(sizeof(SDL_PendingAudioDeviceEvent));
            if (p) { // if this failed, no event for you, but you have deeper problems anyhow.
                p->type = SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED;
                p->devid = logdev->instance_id;
                p->next = NULL;
                pending_tail->next = p;
                pending_tail = p;
            }
        }
        if (pending.next) {
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            SDL_assert(current_audio.pending_events_tail != NULL);
            SDL_assert(current_audio.pending_events_tail->next == NULL);
            current_audio.pending_events_tail->next = pending.next;
            current_audio.pending_events_tail = pending_tail;
            SDL_UnlockRWLock(current_audio.device_hash_lock);
        }
    }
    if (kill_device) {
        return false;
    }
    return true;
}
References current_audio, SDL_PendingAudioDeviceEvent::devid, SDL_AudioSpec::format, SDL_AudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_AudioDevice::mix_buffer, SDL_LogicalAudioDevice::next, SDL_PendingAudioDeviceEvent::next, NULL, SDL_AudioDevice::postmix_buffer, SDL_AudioDevice::sample_frames, SDL_aligned_alloc(), SDL_aligned_free(), SDL_assert, SDL_AUDIO_F32, SDL_AudioSpecsEqual(), SDL_copyp, SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED, SDL_GetSIMDAlignment(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_UnlockRWLock(), SDL_UpdatedAudioDeviceFormat(), SDL_AudioDevice::spec, SDL_PendingAudioDeviceEvent::type, UpdateAudioStreamFormatsPhysical(), SDL_AudioDevice::work_buffer, and SDL_AudioDevice::work_buffer_size.
Referenced by SDL_AudioDeviceFormatChanged().
SDL_AudioDevicePaused()
bool SDL_AudioDevicePaused (SDL_AudioDeviceID devid)
Use this function to query if an audio device is paused.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow.
Physical devices can not be paused or unpaused, only logical devices created through SDL_OpenAudioDevice() can be. Physical and invalid device IDs will report themselves as unpaused here.
Parameters
devid a device opened by SDL_OpenAudioDevice().
Returns
true if device is valid and paused, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseAudioDevice
SDL_ResumeAudioDevice
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    bool result = false;
    if (logdev && SDL_GetAtomicInt(&logdev->paused)) {
        result = true;
    }
    ReleaseAudioDevice(device);
    return result;
}
References NULL, ObtainLogicalAudioDevice(), SDL_LogicalAudioDevice::paused, ReleaseAudioDevice(), and SDL_GetAtomicInt().
Referenced by SDL_AudioStreamDevicePaused().
SDL_AudioFlushRecording_Default()
void SDL_AudioFlushRecording_Default (SDL_AudioDevice * device) static
{ /* no-op. */ }
SDL_AudioFreeDeviceHandle_Default()
void SDL_AudioFreeDeviceHandle_Default (SDL_AudioDevice * device) static
{ /* no-op. */ }
SDL_AudioGetDeviceBuf_Default()
Uint8 * SDL_AudioGetDeviceBuf_Default (SDL_AudioDevice * device, int * buffer_size) static
{
    *buffer_size = 0;
    return NULL;
}
References NULL.
SDL_AudioOpenDevice_Default()
bool SDL_AudioOpenDevice_Default (SDL_AudioDevice * device) static
{
    return SDL_Unsupported();
}
References SDL_Unsupported.
SDL_AudioPlayDevice_Default()
bool SDL_AudioPlayDevice_Default (SDL_AudioDevice * device, const Uint8 * buffer, int buffer_size) static
{ return true; /* no-op. */ }
SDL_AudioRecordDevice_Default()
int SDL_AudioRecordDevice_Default (SDL_AudioDevice * device, void * buffer, int buflen) static
{
    SDL_Unsupported();
    return -1;
}
References SDL_Unsupported.
SDL_AudioSpecsEqual()
bool SDL_AudioSpecsEqual (const SDL_AudioSpec * a, const SDL_AudioSpec * b, const int * channel_map_a, const int * channel_map_b)
{
    if ((a->format != b->format) || (a->channels != b->channels) || (a->freq != b->freq) || ((channel_map_a != NULL) != (channel_map_b != NULL))) {
        return false;
    } else if (channel_map_a && (SDL_memcmp(channel_map_a, channel_map_b, sizeof (*channel_map_a) * a->channels) != 0)) {
        return false;
    }
    return true;
}
References SDL_AudioSpec::channels, SDL_AudioSpec::format, SDL_AudioSpec::freq, NULL, and SDL_memcmp().
Referenced by SDL_AddTrackToAudioQueue(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_DefaultAudioDeviceChanged(), SDL_PlaybackAudioThreadIterate(), SDL_WriteToAudioQueue(), and UpdateAudioStreamInputSpec().
SDL_AudioStreamDevicePaused()
bool SDL_AudioStreamDevicePaused (SDL_AudioStream * stream)
Use this function to query if an audio device associated with a stream is paused.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow.
Parameters
stream the audio stream associated with the audio device to query.
Returns
true if device is valid and paused, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseAudioStreamDevice
SDL_ResumeAudioStreamDevice
{
    SDL_AudioDeviceID devid = SDL_GetAudioStreamDevice(stream);
    if (!devid) {
        return false;
    }
    return SDL_AudioDevicePaused(devid);
}
References SDL_AudioDevicePaused(), and SDL_GetAudioStreamDevice().
SDL_AudioThreadDeinit_Default()
void SDL_AudioThreadDeinit_Default (SDL_AudioDevice * device) static
{ /* no-op. */ }
SDL_AudioThreadFinalize()
void SDL_AudioThreadFinalize (SDL_AudioDevice * device)
{
}
Referenced by SDL_PlaybackAudioThreadShutdown(), and SDL_RecordingAudioThreadShutdown().
SDL_AudioThreadInit_Default()
void SDL_AudioThreadInit_Default (SDL_AudioDevice * device) static
{
    SDL_SetCurrentThreadPriority(device->recording ? SDL_THREAD_PRIORITY_HIGH : SDL_THREAD_PRIORITY_TIME_CRITICAL);
}
References SDL_AudioDevice::recording, SDL_SetCurrentThreadPriority(), SDL_THREAD_PRIORITY_HIGH, and SDL_THREAD_PRIORITY_TIME_CRITICAL.
SDL_AudioWaitDevice_Default()
bool SDL_AudioWaitDevice_Default (SDL_AudioDevice * device) static
{ return true; /* no-op. */ }
SDL_AudioWaitRecordingDevice_Default()
bool SDL_AudioWaitRecordingDevice_Default (SDL_AudioDevice * device) static
{ return true; /* no-op. */ }
SDL_BindAudioStream()
bool SDL_BindAudioStream (SDL_AudioDeviceID devid, SDL_AudioStream * stream)
Bind a single audio stream to an audio device.
This is a convenience function, equivalent to calling SDL_BindAudioStreams(devid, &stream, 1).
Parameters
devid an audio device to bind a stream to.
stream an audio stream to bind to a device.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStreams
SDL_UnbindAudioStream
SDL_GetAudioStreamDevice
{
    return SDL_BindAudioStreams(devid, &stream, 1);
}
References SDL_BindAudioStreams().
SDL_BindAudioStreams()
bool SDL_BindAudioStreams (SDL_AudioDeviceID devid, SDL_AudioStream *const * streams, int num_streams)
Bind a list of audio streams to an audio device.
Audio data will flow through any bound streams. For a playback device, data for all bound streams will be mixed together and fed to the device. For a recording device, a copy of recorded data will be provided to each bound stream.
Audio streams can only be bound to an open device. This operation is atomic–all streams bound in the same call will start processing at the same time, so they can stay in sync. Also: either all streams will be bound or none of them will be.
It is an error to bind an already-bound stream; it must be explicitly unbound first.
Binding a stream to a device will set its output format for playback devices, and its input format for recording devices, so they match the device's settings. The caller is welcome to change the other end of the stream's format at any time with SDL_SetAudioStreamFormat(). If the other end of the stream's format has never been set (the audio stream was created with a NULL audio spec), this function will set it to match the device end's format.
Parameters
devid an audio device to bind a stream to.
streams an array of audio streams to bind.
num_streams number streams listed in the streams array.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStreams
SDL_UnbindAudioStream
SDL_GetAudioStreamDevice
{
    const bool islogical = !(devid & (1<<1));
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = NULL;
    bool result = true;
    if (num_streams == 0) {
        return true;  // nothing to do
    } else if (num_streams < 0) {
        return SDL_InvalidParamError("num_streams");
    } else if (!streams) {
        return SDL_InvalidParamError("streams");
    } else if (!islogical) {
        return SDL_SetError("Audio streams are bound to device ids from SDL_OpenAudioDevice, not raw physical devices");
    }
    logdev = ObtainLogicalAudioDevice(devid, &device);
    if (!logdev) {
        result = false;  // ObtainLogicalAudioDevice set the error string.
    } else if (logdev->simplified) {
        result = SDL_SetError("Cannot change stream bindings on device opened with SDL_OpenAudioDeviceStream");
    } else {
        // make sure start of list is sane.
        SDL_assert(!logdev->bound_streams || (logdev->bound_streams->prev_binding == NULL));
        // lock all the streams upfront, so we can verify they aren't bound elsewhere and add them all in one block, as this is intended to add everything or nothing.
        for (int i = 0; i < num_streams; i++) {
            SDL_AudioStream *stream = streams[i];
            if (!stream) {
                SDL_SetError("Stream #%d is NULL", i);
                result = false;  // to pacify the static analyzer, that doesn't realize SDL_SetError() always returns false.
            } else {
                SDL_LockMutex(stream->lock);
                SDL_assert((stream->bound_device == NULL) == ((stream->prev_binding == NULL) || (stream->next_binding == NULL)));
                if (stream->bound_device) {
                    result = SDL_SetError("Stream #%d is already bound to a device", i);
                } else if (stream->simplified) {  // You can get here if you closed the device instead of destroying the stream.
                    result = SDL_SetError("Cannot change binding on a stream created with SDL_OpenAudioDeviceStream");
                }
            }
            if (!result) {
                int j;
                for (j = 0; j < i; j++) {
                    SDL_UnlockMutex(streams[j]->lock);
                }
                if (stream) {
                    SDL_UnlockMutex(stream->lock);
                }
                break;
            }
        }
    }
    if (result) {
        // Now that everything is verified, chain everything together.
        const bool recording = device->recording;
        for (int i = 0; i < num_streams; i++) {
            SDL_AudioStream *stream = streams[i];
            if (stream) {  // shouldn't be NULL, but just in case...
                // if the stream never had its non-device-end format set, just set it to the device end's format.
                if (recording && (stream->dst_spec.format == SDL_AUDIO_UNKNOWN)) {
                    SDL_copyp(&stream->dst_spec, &device->spec);
                } else if (!recording && (stream->src_spec.format == SDL_AUDIO_UNKNOWN)) {
                    SDL_copyp(&stream->src_spec, &device->spec);
                }
                stream->bound_device = logdev;
                stream->prev_binding = NULL;
                stream->next_binding = logdev->bound_streams;
                if (logdev->bound_streams) {
                    logdev->bound_streams->prev_binding = stream;
                }
                logdev->bound_streams = stream;
                SDL_UnlockMutex(stream->lock);
            }
        }
    }
    UpdateAudioStreamFormatsPhysical(device);
    ReleaseAudioDevice(device);
    return result;
}
References SDL_LogicalAudioDevice::bound_streams, lock, NULL, ObtainLogicalAudioDevice(), SDL_AudioStream::prev_binding, SDL_AudioDevice::recording, ReleaseAudioDevice(), SDL_assert, SDL_AUDIO_UNKNOWN, SDL_copyp, SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), SDL_UnlockMutex(), SDL_LogicalAudioDevice::simplified, SDL_AudioDevice::spec, and UpdateAudioStreamFormatsPhysical().
Referenced by SDL_BindAudioStream().
SDL_ChannelMapDup()
int * SDL_ChannelMapDup (const int * origchmap, int channels)
{
    const size_t chmaplen = sizeof (*origchmap) * channels;
    int *chmap = (int *)SDL_malloc(chmaplen);
    if (chmap) {
        SDL_memcpy(chmap, origchmap, chmaplen);
    }
    return chmap;
}
References SDL_malloc(), and SDL_memcpy.
Referenced by SDL_GetAudioDeviceChannelMap(), SDL_GetAudioStreamInputChannelMap(), SDL_GetAudioStreamOutputChannelMap(), and SetAudioStreamChannelMap().
SDL_CloseAudioDevice()
void SDL_CloseAudioDevice (SDL_AudioDeviceID devid)
Close a previously-opened audio device.
The application should close open audio devices once they are no longer needed.
This function may block briefly while pending audio data is played by the hardware, so that applications don't drop the last buffer of data they supplied if terminating immediately afterwards.
Parameters
devid an audio device id previously returned by SDL_OpenAudioDevice().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenAudioDevice
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    if (logdev) {
        DestroyLogicalAudioDevice(logdev);
    }
    if (device) {
        if (!device->logical_devices) {  // no more logical devices? Close the physical device, too.
            ClosePhysicalAudioDevice(device);
        }
        UnrefPhysicalAudioDevice(device);  // one reference for each logical device.
    }
    ReleaseAudioDevice(device);
}
References ClosePhysicalAudioDevice(), DestroyLogicalAudioDevice(), SDL_AudioDevice::logical_devices, NULL, ObtainLogicalAudioDevice(), ReleaseAudioDevice(), and UnrefPhysicalAudioDevice().
Referenced by SDL_DestroyAudioStream(), SDL_OpenAudioDevice(), and SDL_OpenAudioDeviceStream().
SDL_ClosestAudioFormats()
const SDL_AudioFormat * SDL_ClosestAudioFormats (SDL_AudioFormat format)
{
    for (int i = 0; i < NUM_FORMATS; i++) {
        if (format_list[i][0] == format) {
            return &format_list[i][0];
        }
    }
    return &format_list[0][NUM_FORMATS]; // not found; return what looks like a list with only a zero in it.
}
References format_list, and NUM_FORMATS.
SDL_COMPILE_TIME_ASSERT()
SDL_COMPILE_TIME_ASSERT (check_lowest_audio_default_value)
References SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, and SDL_AUDIO_DEVICE_DEFAULT_RECORDING.
SDL_DefaultAudioDeviceChanged()
void SDL_DefaultAudioDeviceChanged (SDL_AudioDevice * new_default_device)
{
    if (!new_default_device) {  // !!! FIXME: what should we do in this case? Maybe all devices are lost, so there _isn't_ a default?
        return;  // uhoh.
    }
    const bool recording = new_default_device->recording;
    // change the official default over right away, so new opens will go to the new device.
    SDL_LockRWLockForWriting(current_audio.device_hash_lock);
    const SDL_AudioDeviceID current_devid = recording ? current_audio.default_recording_device_id : current_audio.default_playback_device_id;
    const bool is_already_default = (new_default_device->instance_id == current_devid);
    if (!is_already_default) {
        if (recording) {
            current_audio.default_recording_device_id = new_default_device->instance_id;
        } else {
            current_audio.default_playback_device_id = new_default_device->instance_id;
        }
    }
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    if (is_already_default) {
        return;  // this is already the default.
    }
    // Queue up events to push to the queue next time it pumps (presumably
    //  in a safer thread).
    // !!! FIXME: this duplicates some code we could probably refactor.
    SDL_PendingAudioDeviceEvent pending;
    pending.next = NULL;
    SDL_PendingAudioDeviceEvent *pending_tail = &pending;
    // Default device gets an extra ref, so it lives until a new default replaces it, even if disconnected.
    RefPhysicalAudioDevice(new_default_device);
    ObtainPhysicalAudioDeviceObj(new_default_device);
    SDL_AudioDevice *current_default_device = ObtainPhysicalAudioDevice(current_devid);
    if (current_default_device) {
        // migrate any logical devices that were opened as a default to the new physical device...
        SDL_assert(current_default_device->recording == recording);
        // See if we have to open the new physical device, and if so, find the best audiospec for it.
        SDL_AudioSpec spec;
        bool needs_migration = false;
        SDL_zero(spec);
        for (SDL_LogicalAudioDevice *logdev = current_default_device->logical_devices; logdev; logdev = logdev->next) {
            if (logdev->opened_as_default) {
                needs_migration = true;
                for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = stream->next_binding) {
                    const SDL_AudioSpec *streamspec = recording ? &stream->dst_spec : &stream->src_spec;
                    if (SDL_AUDIO_BITSIZE(streamspec->format) > SDL_AUDIO_BITSIZE(spec.format)) {
                        spec.format = streamspec->format;
                    }
                    if (streamspec->channels > spec.channels) {
                        spec.channels = streamspec->channels;
                    }
                    if (streamspec->freq > spec.freq) {
                        spec.freq = streamspec->freq;
                    }
                }
            }
        }
        if (needs_migration) {
            // New default physical device not been opened yet? Open at the OS level...
            if (!OpenPhysicalAudioDevice(new_default_device, &spec)) {
                needs_migration = false;  // uhoh, just leave everything on the old default, nothing to be done.
            }
        }
        if (needs_migration) {
            // we don't currently report channel map changes, so we'll leave them as NULL for now.
            const bool spec_changed = !SDL_AudioSpecsEqual(&current_default_device->spec, &new_default_device->spec, NULL, NULL);
            SDL_LogicalAudioDevice *next = NULL;
            for (SDL_LogicalAudioDevice *logdev = current_default_device->logical_devices; logdev; logdev = next) {
                next = logdev->next;
                if (!logdev->opened_as_default) {
                    continue;  // not opened as a default, leave it on the current physical device.
                }
                // now migrate the logical device. Hold device_hash_lock so ObtainLogicalAudioDevice doesn't get a device in the middle of transition.
                SDL_LockRWLockForWriting(current_audio.device_hash_lock);
                if (logdev->next) {
                    logdev->next->prev = logdev->prev;
                }
                if (logdev->prev) {
                    logdev->prev->next = logdev->next;
                }
                if (current_default_device->logical_devices == logdev) {
                    current_default_device->logical_devices = logdev->next;
                }
                logdev->physical_device = new_default_device;
                logdev->prev = NULL;
                logdev->next = new_default_device->logical_devices;
                new_default_device->logical_devices = logdev;
                SDL_UnlockRWLock(current_audio.device_hash_lock);
                SDL_assert(SDL_GetAtomicInt(&current_default_device->refcount) > 1);  // we should hold at least one extra reference to this device, beyond logical devices, during this phase...
                RefPhysicalAudioDevice(new_default_device);
                UnrefPhysicalAudioDevice(current_default_device);
                SDL_SetAudioPostmixCallback(logdev->instance_id, logdev->postmix, logdev->postmix_userdata);
                SDL_PendingAudioDeviceEvent *p;
                // Queue an event for each logical device we moved.
                if (spec_changed) {
                    p = (SDL_PendingAudioDeviceEvent *)SDL_malloc(sizeof(SDL_PendingAudioDeviceEvent));
                    if (p) { // if this failed, no event for you, but you have deeper problems anyhow.
                        p->type = SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED;
                        p->devid = logdev->instance_id;
                        p->next = NULL;
                        pending_tail->next = p;
                        pending_tail = p;
                    }
                }
            }
            UpdateAudioStreamFormatsPhysical(current_default_device);
            UpdateAudioStreamFormatsPhysical(new_default_device);
            if (!current_default_device->logical_devices) {   // nothing left on the current physical device, close it.
                ClosePhysicalAudioDevice(current_default_device);
            }
        }
        ReleaseAudioDevice(current_default_device);
    }
    ReleaseAudioDevice(new_default_device);
    // Default device gets an extra ref, so it lives until a new default replaces it, even if disconnected.
    if (current_default_device) {  // (despite the name, it's no longer current at this point)
        UnrefPhysicalAudioDevice(current_default_device);
    }
    if (pending.next) {
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        SDL_assert(current_audio.pending_events_tail != NULL);
        SDL_assert(current_audio.pending_events_tail->next == NULL);
        current_audio.pending_events_tail->next = pending.next;
        current_audio.pending_events_tail = pending_tail;
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
}
References SDL_AudioSpec::channels, ClosePhysicalAudioDevice(), current_audio, SDL_PendingAudioDeviceEvent::devid, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, SDL_PendingAudioDeviceEvent::next, NULL, ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceObj(), OpenPhysicalAudioDevice(), SDL_AudioDevice::recording, SDL_AudioDevice::refcount, RefPhysicalAudioDevice(), ReleaseAudioDevice(), SDL_assert, SDL_AUDIO_BITSIZE, SDL_AudioSpecsEqual(), SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED, SDL_GetAtomicInt(), SDL_LockRWLockForWriting(), SDL_malloc(), SDL_SetAudioPostmixCallback(), SDL_UnlockRWLock(), SDL_zero, SDL_AudioDevice::spec, SDL_PendingAudioDeviceEvent::type, UnrefPhysicalAudioDevice(), and UpdateAudioStreamFormatsPhysical().
SDL_FindPhysicalAudioDeviceByCallback()
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByCallback (bool(* callback)(SDL_AudioDevice *device, void *userdata), void * userdata)
{
    if (!SDL_GetCurrentAudioDriver()) {
        SDL_SetError("Audio subsystem is not initialized");
        return NULL;
    }
    FindAudioDeviceByCallbackData data = { callback, userdata, NULL };
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    SDL_IterateHashTable(current_audio.device_hash, FindAudioDeviceByCallback, &data);
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    if (!data.retval) {
        SDL_SetError("Device not found");
    }
    return data.retval;
}
References current_audio, FindAudioDeviceByCallback(), NULL, SDL_GetCurrentAudioDriver(), SDL_IterateHashTable(), SDL_LockRWLockForReading(), SDL_SetError(), and SDL_UnlockRWLock().
Referenced by SDL_FindPhysicalAudioDeviceByHandle().
SDL_FindPhysicalAudioDeviceByHandle()
SDL_AudioDevice * SDL_FindPhysicalAudioDeviceByHandle (void * handle)
{
    return SDL_FindPhysicalAudioDeviceByCallback(TestDeviceHandleCallback, handle);
}
References SDL_FindPhysicalAudioDeviceByCallback(), and TestDeviceHandleCallback().
Referenced by SDL_AddAudioDevice().
SDL_GetAudioDeviceChannelMap()
int * SDL_GetAudioDeviceChannelMap (SDL_AudioDeviceID devid, int * count)
Get the current channel map of an audio device.
Channel maps are optional; most things do not need them, instead passing data in the order that SDL expects.
Audio devices usually have no remapping applied. This is represented by returning NULL, and does not signify an error.
Parameters
devid the instance ID of the device to query.
count On output, set to number of channels in the map. Can be NULL.
Returns
an array of the current channel mapping, with as many elements as the current output spec's channels, or NULL if default. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioStreamInputChannelMap
{
    int *result = NULL;
    int channels = 0;
    SDL_AudioDevice *device = ObtainPhysicalAudioDeviceDefaultAllowed(devid);
    if (device) {
        channels = device->spec.channels;
        if (channels > 0 && device->chmap) {
            result = SDL_ChannelMapDup(device->chmap, channels);
        }
    }
    ReleaseAudioDevice(device);
    if (count) {
        *count = channels;
    }
    return result;
}
References SDL_AudioSpec::channels, SDL_AudioDevice::chmap, count, NULL, ObtainPhysicalAudioDeviceDefaultAllowed(), ReleaseAudioDevice(), SDL_ChannelMapDup(), and SDL_AudioDevice::spec.
SDL_GetAudioDeviceFormat()
bool SDL_GetAudioDeviceFormat (SDL_AudioDeviceID devid, SDL_AudioSpec * spec, int * sample_frames)
Get the current audio format of a specific audio device.
For an opened device, this will report the format the device is currently using. If the device isn't yet opened, this will report the device's preferred format (or a reasonable default if this can't be determined).
You may also specify SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING here, which is useful for getting a reasonable recommendation before opening the system-recommended default device.
You can also use this to request the current device buffer size. This is specified in sample frames and represents the amount of data SDL will feed to the physical hardware in each chunk. This can be converted to milliseconds of audio with the following equation:
ms = (int) ((((Sint64) frames) * 1000) / spec.freq);
Buffer size is only important if you need low-level control over the audio playback timing. Most apps do not need this.
Parameters
devid the instance ID of the device to query.
spec on return, will be filled with device details.
sample_frames pointer to store device buffer size, in sample frames. Can be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!spec) {
        return SDL_InvalidParamError("spec");
    }
    bool result = false;
    SDL_AudioDevice *device = ObtainPhysicalAudioDeviceDefaultAllowed(devid);
    if (device) {
        SDL_copyp(spec, &device->spec);
        if (sample_frames) {
            *sample_frames = device->sample_frames;
        }
        result = true;
    }
    ReleaseAudioDevice(device);
    return result;
}
References ObtainPhysicalAudioDeviceDefaultAllowed(), ReleaseAudioDevice(), SDL_AudioDevice::sample_frames, SDL_copyp, SDL_InvalidParamError, and SDL_AudioDevice::spec.
SDL_GetAudioDeviceGain()
float SDL_GetAudioDeviceGain (SDL_AudioDeviceID devid)
Get the gain of an audio device.
The gain of a device is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio devices default to a gain of 1.0f (no change in output).
Physical devices may not have their gain changed, only logical devices, and this function will always return -1.0f when used on physical devices.
Parameters
devid the audio device to query.
Returns
the gain of the device or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetAudioDeviceGain
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    const float result = logdev ? logdev->gain : -1.0f;
    ReleaseAudioDevice(device);
    return result;
}
References SDL_LogicalAudioDevice::gain, NULL, ObtainLogicalAudioDevice(), and ReleaseAudioDevice().
SDL_GetAudioDeviceName()
const char * SDL_GetAudioDeviceName (SDL_AudioDeviceID devid)
Get the human-readable name of a specific audio device.
Parameters
devid the instance ID of the device to query.
Returns
the name of the audio device, or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioPlaybackDevices
SDL_GetAudioRecordingDevices
{
    // bit #1 of devid is set for physical devices and unset for logical.
    const bool islogical = !(devid & (1<<1));
    const char *result = NULL;
    const void *vdev = NULL;
    if (!SDL_GetCurrentAudioDriver()) {
        SDL_SetError("Audio subsystem is not initialized");
    } else {
        // This does not call ObtainPhysicalAudioDevice() because the device's name never changes, so
        // it doesn't have to lock the whole device. However, just to make sure the device pointer itself
        // remains valid (in case the device is unplugged at the wrong moment), we hold the
        // device_hash_lock while we copy the string.
        SDL_LockRWLockForReading(current_audio.device_hash_lock);
        SDL_FindInHashTable(current_audio.device_hash, (const void *) (uintptr_t) devid, &vdev);
        if (!vdev) {
            SDL_SetError("Invalid audio device instance ID");
        } else if (islogical) {
            const SDL_LogicalAudioDevice *logdev = (const SDL_LogicalAudioDevice *) vdev;
            SDL_assert(logdev->instance_id == devid);
            result = SDL_GetPersistentString(logdev->physical_device->name);
        } else {
            const SDL_AudioDevice *device = (const SDL_AudioDevice *) vdev;
            SDL_assert(device->instance_id == devid);
            result = SDL_GetPersistentString(device->name);
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
    }
    return result;
}
References current_audio, SDL_AudioDevice::instance_id, SDL_LogicalAudioDevice::instance_id, SDL_AudioDevice::name, NULL, SDL_LogicalAudioDevice::physical_device, SDL_assert, SDL_FindInHashTable(), SDL_GetCurrentAudioDriver(), SDL_GetPersistentString(), SDL_LockRWLockForReading(), SDL_SetError(), and SDL_UnlockRWLock().
SDL_GetAudioDriver()
const char * SDL_GetAudioDriver (int index)
Use this function to get the name of a built in audio driver.
The list of audio drivers is given in the order that they are normally initialized by default; the drivers that seem more reasonable to choose first (as far as the SDL developers believe) are earlier in the list.
The names of drivers are all simple, low-ASCII identifiers, like "alsa", "coreaudio" or "wasapi". These never have Unicode characters, and are not meant to be proper names.
Parameters
index the index of the audio driver; the value ranges from 0 to SDL_GetNumAudioDrivers() - 1.
Returns
the name of the audio driver at the requested index, or NULL if an invalid index was specified.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumAudioDrivers
{
    if (index >= 0 && index < SDL_GetNumAudioDrivers()) {
        return deduped_bootstrap[index]->name;
    }
    SDL_InvalidParamError("index");
    return NULL;
}
References deduped_bootstrap, NULL, SDL_GetNumAudioDrivers(), and SDL_InvalidParamError.
SDL_GetAudioFormatName()
const char * SDL_GetAudioFormatName (SDL_AudioFormat format)
Get the human readable name of an audio format.
Parameters
format the audio format to query.
Returns
the human readable name of the specified audio format or "SDL_AUDIO_UNKNOWN" if the format isn't recognized.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    switch (format) {
#define CASE(X) \
    case X: return #X;
    CASE(SDL_AUDIO_U8)
    CASE(SDL_AUDIO_S8)
    CASE(SDL_AUDIO_S16LE)
    CASE(SDL_AUDIO_S16BE)
    CASE(SDL_AUDIO_S32LE)
    CASE(SDL_AUDIO_S32BE)
    CASE(SDL_AUDIO_F32LE)
    CASE(SDL_AUDIO_F32BE)
#undef CASE
    default:
        return "SDL_AUDIO_UNKNOWN";
    }
}
References CASE, SDL_AUDIO_F32BE, SDL_AUDIO_F32LE, SDL_AUDIO_S16BE, SDL_AUDIO_S16LE, SDL_AUDIO_S32BE, SDL_AUDIO_S32LE, SDL_AUDIO_S8, and SDL_AUDIO_U8.
SDL_GetAudioPlaybackDevices()
SDL_AudioDeviceID * SDL_GetAudioPlaybackDevices (int * count)
Get a list of currently-connected audio playback devices.
This returns of list of available devices that play sound, perhaps to speakers or headphones ("playback" devices). If you want devices that record audio, like a microphone ("recording" devices), use SDL_GetAudioRecordingDevices() instead.
This only returns a list of physical devices; it will not have any device IDs returned by SDL_OpenAudioDevice().
If this function returns NULL, to signify an error, *count will be set to zero.
Parameters
count a pointer filled in with the number of devices returned, may be NULL.
Returns
a 0 terminated array of device instance IDs or NULL on error; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenAudioDevice
SDL_GetAudioRecordingDevices
{
    return GetAudioDevices(count, false);
}
References count, and GetAudioDevices().
SDL_GetAudioRecordingDevices()
SDL_AudioDeviceID * SDL_GetAudioRecordingDevices (int * count)
Get a list of currently-connected audio recording devices.
This returns of list of available devices that record audio, like a microphone ("recording" devices). If you want devices that play sound, perhaps to speakers or headphones ("playback" devices), use SDL_GetAudioPlaybackDevices() instead.
This only returns a list of physical devices; it will not have any device IDs returned by SDL_OpenAudioDevice().
If this function returns NULL, to signify an error, *count will be set to zero.
Parameters
count a pointer filled in with the number of devices returned, may be NULL.
Returns
a 0 terminated array of device instance IDs, or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenAudioDevice
SDL_GetAudioPlaybackDevices
{
    return GetAudioDevices(count, true);
}
References count, and GetAudioDevices().
SDL_GetAudioStreamDevice()
SDL_AudioDeviceID SDL_GetAudioStreamDevice (SDL_AudioStream * stream)
Query an audio stream for its currently-bound device.
This reports the logical audio device that an audio stream is currently bound to.
If not bound, or invalid, this returns zero, which is not a valid device ID.
Parameters
stream the audio stream to query.
Returns
the bound audio device, or 0 if not bound or invalid.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStream
SDL_BindAudioStreams
{
    SDL_AudioDeviceID result = 0;
    if (!stream) {
        SDL_InvalidParamError("stream");
        return 0;
    }
    SDL_LockMutex(stream->lock);
    if (stream->bound_device) {
        result = stream->bound_device->instance_id;
    } else {
        SDL_SetError("Audio stream not bound to an audio device");
    }
    SDL_UnlockMutex(stream->lock);
    return result;
}
References SDL_InvalidParamError, SDL_LockMutex(), SDL_SetError(), and SDL_UnlockMutex().
Referenced by SDL_AudioStreamDevicePaused(), SDL_PauseAudioStreamDevice(), and SDL_ResumeAudioStreamDevice().
SDL_GetAudioThreadName()
char * SDL_GetAudioThreadName (SDL_AudioDevice * device, char * buf, size_t buflen)
{
    (void)SDL_snprintf(buf, buflen, "SDLAudio%c%d", (device->recording) ? 'C' : 'P', (int) device->instance_id);
    return buf;
}
References SDL_AudioDevice::instance_id, SDL_AudioDevice::recording, SDL_snprintf(), and void().
Referenced by OpenPhysicalAudioDevice().
SDL_GetCurrentAudioDriver()
const char * SDL_GetCurrentAudioDriver (void)
Get the name of the current audio driver.
The names of drivers are all simple, low-ASCII identifiers, like "alsa", "coreaudio" or "wasapi". These never have Unicode characters, and are not meant to be proper names.
Returns
the name of the current audio driver or NULL if no driver has been initialized.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return current_audio.name;
}
References current_audio.
Referenced by GetAudioDevices(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_GetAudioDeviceName(), SDL_InitAudio(), and SDL_OpenAudioDevice().
SDL_GetDefaultSampleFramesFromFreq()
int SDL_GetDefaultSampleFramesFromFreq (const int freq)
{
    const char *hint = SDL_GetHint(SDL_HINT_AUDIO_DEVICE_SAMPLE_FRAMES);
    if (hint) {
        const int val = SDL_atoi(hint);
        if (val > 0) {
            return val;
        }
    }
    if (freq <= 22050) {
        return 512;
    } else if (freq <= 48000) {
        return 1024;
    } else if (freq <= 96000) {
        return 2048;
    } else {
        return 4096;
    }
}
References SDL_atoi(), SDL_GetHint(), and SDL_HINT_AUDIO_DEVICE_SAMPLE_FRAMES.
Referenced by CreatePhysicalAudioDevice(), and OpenPhysicalAudioDevice().
SDL_GetNumAudioDrivers()
int SDL_GetNumAudioDrivers (void)
Use this function to get the number of built-in audio drivers.
This function returns a hardcoded number. This never returns a negative value; if there are no drivers compiled into this build of SDL, this function returns zero. The presence of a driver in this list does not mean it will function, it just means SDL is capable of interacting with that interface. For example, a build of SDL might have esound support, but if there's no esound server available, SDL's esound driver would fail if used.
By default, SDL tries all drivers, in its preferred order, until one is found to be usable.
Returns
the number of built-in audio drivers.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioDriver
{
    static int num_drivers = -1;
    if (num_drivers >= 0) {
        return num_drivers;
    }
    num_drivers = 0;
    // Build a list of unique audio drivers.
    for (int i = 0; bootstrap[i] != NULL; ++i) {
        bool duplicate = false;
        for (int j = 0; j < i; ++j) {
            if (SDL_strcmp(bootstrap[i]->name, bootstrap[j]->name) == 0) {
                duplicate = true;
                break;
            }
        }
        if (!duplicate) {
            deduped_bootstrap[num_drivers++] = bootstrap[i];
        }
    }
    return num_drivers;
}
References bootstrap, deduped_bootstrap, NULL, and SDL_strcmp().
Referenced by SDL_GetAudioDriver().
SDL_GetSilenceValueForFormat()
int SDL_GetSilenceValueForFormat (SDL_AudioFormat format)
Get the appropriate memset value for silencing an audio format.
The value returned by this function can be used as the second argument to memset (or SDL_memset) to set an audio buffer in a specific format to silence.
Parameters
format the audio data format to query.
Returns
a byte value that can be passed to memset.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (format == SDL_AUDIO_U8) ? 0x80 : 0x00;
}
References SDL_AUDIO_U8.
Referenced by ClosePhysicalAudioDevice(), CreatePhysicalAudioDevice(), InterleaveAudioChannels(), PeekIntoAudioQueueFuture(), SDL_ResetAudioQueueHistory(), and SDL_UpdatedAudioDeviceFormat().
SDL_InitAudio()
bool SDL_InitAudio (const char * driver_name)
{
    if (SDL_GetCurrentAudioDriver()) {
        SDL_QuitAudio(); // shutdown driver if already running.
    }
    // make sure device IDs start at 2 (because of SDL2 legacy interface), but don't reset the counter on each init, in case the app is holding an old device ID somewhere.
    SDL_CompareAndSwapAtomicInt(&last_device_instance_id, 0, 2);
    SDL_ChooseAudioConverters();
    SDL_SetupAudioResampler();
    SDL_RWLock *device_hash_lock = SDL_CreateRWLock();  // create this early, so if it fails we don't have to tear down the whole audio subsystem.
    if (!device_hash_lock) {
        return false;
    }
    SDL_HashTable *device_hash = SDL_CreateHashTable(0, false, HashAudioDeviceID, SDL_KeyMatchID, NULL, NULL);
    if (!device_hash) {
        SDL_DestroyRWLock(device_hash_lock);
        return false;
    }
    // Select the proper audio driver
    if (!driver_name) {
        driver_name = SDL_GetHint(SDL_HINT_AUDIO_DRIVER);
    }
    bool initialized = false;
    bool tried_to_init = false;
    if (driver_name && *driver_name != 0) {
        char *driver_name_copy = SDL_strdup(driver_name);
        const char *driver_attempt = driver_name_copy;
        if (!driver_name_copy) {
            SDL_DestroyRWLock(device_hash_lock);
            SDL_DestroyHashTable(device_hash);
            return false;
        }
        while (driver_attempt && *driver_attempt != 0 && !initialized) {
            char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            if (driver_attempt_end) {
                *driver_attempt_end = '\0';
            }
            // SDL 1.2 uses the name "dsound", so we'll support both.
            if (SDL_strcmp(driver_attempt, "dsound") == 0) {
                driver_attempt = "directsound";
            } else if (SDL_strcmp(driver_attempt, "pulse") == 0) {  // likewise, "pulse" was renamed to "pulseaudio"
                driver_attempt = "pulseaudio";
            }
            for (int i = 0; bootstrap[i]; ++i) {
                if (!bootstrap[i]->is_preferred && SDL_strcasecmp(bootstrap[i]->name, driver_attempt) == 0) {
                    tried_to_init = true;
                    SDL_zero(current_audio);
                    current_audio.pending_events_tail = &current_audio.pending_events;
                    current_audio.device_hash_lock = device_hash_lock;
                    current_audio.device_hash = device_hash;
                    if (bootstrap[i]->init(&current_audio.impl)) {
                        current_audio.name = bootstrap[i]->name;
                        current_audio.desc = bootstrap[i]->desc;
                        initialized = true;
                        break;
                    }
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
        SDL_free(driver_name_copy);
    } else {
        for (int i = 0; (!initialized) && (bootstrap[i]); ++i) {
            if (bootstrap[i]->demand_only) {
                continue;
            }
            tried_to_init = true;
            SDL_zero(current_audio);
            current_audio.pending_events_tail = &current_audio.pending_events;
            current_audio.device_hash_lock = device_hash_lock;
            current_audio.device_hash = device_hash;
            if (bootstrap[i]->init(&current_audio.impl)) {
                current_audio.name = bootstrap[i]->name;
                current_audio.desc = bootstrap[i]->desc;
                initialized = true;
            }
        }
    }
    if (initialized) {
        SDL_DebugLogBackend("audio", current_audio.name);
    } else {
        // specific drivers will set the error message if they fail, but otherwise we do it here.
        if (!tried_to_init) {
            if (driver_name) {
                SDL_SetError("Audio target '%s' not available", driver_name);
            } else {
                SDL_SetError("No available audio device");
            }
        }
        SDL_DestroyRWLock(device_hash_lock);
        SDL_DestroyHashTable(device_hash);
        SDL_zero(current_audio);
        return false;  // No driver was available, so fail.
    }
    CompleteAudioEntryPoints();
    // Make sure we have a list of devices available at startup...
    SDL_AudioDevice *default_playback = NULL;
    SDL_AudioDevice *default_recording = NULL;
    current_audio.impl.DetectDevices(&default_playback, &default_recording);
    // If no default was _ever_ specified, just take the first device we see, if any.
    if (!default_playback) {
        default_playback = GetFirstAddedAudioDevice(/*recording=*/false);
    }
    if (!default_recording) {
        default_recording = GetFirstAddedAudioDevice(/*recording=*/true);
    }
    if (default_playback) {
        current_audio.default_playback_device_id = default_playback->instance_id;
        RefPhysicalAudioDevice(default_playback);  // extra ref on default devices.
    }
    if (default_recording) {
        current_audio.default_recording_device_id = default_recording->instance_id;
        RefPhysicalAudioDevice(default_recording);  // extra ref on default devices.
    }
    return true;
}
References bootstrap, CompleteAudioEntryPoints(), current_audio, GetFirstAddedAudioDevice(), HashAudioDeviceID(), SDL_AudioDevice::instance_id, last_device_instance_id, NULL, RefPhysicalAudioDevice(), SDL_ChooseAudioConverters(), SDL_CompareAndSwapAtomicInt(), SDL_CreateHashTable(), SDL_CreateRWLock(), SDL_DebugLogBackend(), SDL_DestroyHashTable(), SDL_DestroyRWLock(), SDL_free(), SDL_GetCurrentAudioDriver(), SDL_GetHint(), SDL_HINT_AUDIO_DRIVER, SDL_KeyMatchID(), SDL_QuitAudio(), SDL_SetError(), SDL_SetupAudioResampler(), SDL_strcasecmp(), SDL_strchr(), SDL_strcmp(), SDL_strdup(), and SDL_zero.
Referenced by SDL_InitSubSystem().
SDL_IsAudioDevicePhysical()
bool SDL_IsAudioDevicePhysical (SDL_AudioDeviceID devid)
Determine if an audio device is physical (instead of logical).
An SDL_AudioDeviceID that represents physical hardware is a physical device; there is one for each piece of hardware that SDL can see. Logical devices are created by calling SDL_OpenAudioDevice or SDL_OpenAudioDeviceStream, and while each is associated with a physical device, there can be any number of logical devices on one physical device.
For the most part, logical and physical IDs are interchangeable–if you try to open a logical device, SDL understands to assign that effort to the underlying physical device, etc. However, it might be useful to know if an arbitrary device ID is physical or logical. This function reports which.
This function may return either true or false for invalid device IDs.
Parameters
devid the device ID to query.
Returns
true if devid is a physical device, false if it is logical.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (devid & (1 << 1)) != 0;
}
SDL_IsAudioDevicePlayback()
bool SDL_IsAudioDevicePlayback (SDL_AudioDeviceID devid)
Determine if an audio device is a playback device (instead of recording).
This function may return either true or false for invalid device IDs.
Parameters
devid the device ID to query.
Returns
true if devid is a playback device, false if it is recording.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (devid & (1 << 0)) != 0;
}
SDL_OpenAudioDevice()
SDL_AudioDeviceID SDL_OpenAudioDevice (SDL_AudioDeviceID devid, const SDL_AudioSpec * spec)
Open a specific audio device.
You can open both playback and recording devices through this function. Playback devices will take data from bound audio streams, mix it, and send it to the hardware. Recording devices will feed any bound audio streams with a copy of any incoming data.
An opened audio device starts out with no audio streams bound. To start audio playing, bind a stream and supply audio data to it. Unlike SDL2, there is no audio callback; you only bind audio streams and make sure they have data flowing into them (however, you can simulate SDL2's semantics fairly closely by using SDL_OpenAudioDeviceStream instead of this function).
If you don't care about opening a specific device, pass a devid of either SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING. In this case, SDL will try to pick the most reasonable default, and may also switch between physical devices seamlessly later, if the most reasonable default changes during the lifetime of this opened device (user changed the default in the OS's system preferences, the default got unplugged so the system jumped to a new default, the user plugged in headphones on a mobile device, etc). Unless you have a good reason to choose a specific device, this is probably what you want.
You may request a specific format for the audio device, but there is no promise the device will honor that request for several reasons. As such, it's only meant to be a hint as to what data your app will provide. Audio streams will accept data in whatever format you specify and manage conversion for you as appropriate. SDL_GetAudioDeviceFormat can tell you the preferred format for the device before opening and the actual format the device is using after opening.
It's legal to open the same device ID more than once; each successful open will generate a new logical SDL_AudioDeviceID that is managed separately from others on the same physical device. This allows libraries to open a device separately from the main app and bind its own streams without conflicting.
It is also legal to open a device ID returned by a previous call to this function; doing so just creates another logical device on the same physical device. This may be useful for making logical groupings of audio streams.
This function returns the opened device ID on success. This is a new, unique SDL_AudioDeviceID that represents a logical device.
Some backends might offer arbitrary devices (for example, a networked audio protocol that can connect to an arbitrary server). For these, as a change from SDL2, you should open a default device ID and use an SDL hint to specify the target if you care, or otherwise let the backend figure out a reasonable default. Most backends don't offer anything like this, and often this would be an end user setting an environment variable for their custom need, and not something an application should specifically manage.
When done with an audio device, possibly at the end of the app's life, one should call SDL_CloseAudioDevice() on the returned device id.
Parameters
devid the device instance id to open, or SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING for the most reasonable default device.
spec the requested device configuration. Can be NULL to use reasonable defaults.
Returns
the device ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseAudioDevice
SDL_GetAudioDeviceFormat
{
    if (!SDL_GetCurrentAudioDriver()) {
        SDL_SetError("Audio subsystem is not initialized");
        return 0;
    }
    bool wants_default = ((devid == SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK) || (devid == SDL_AUDIO_DEVICE_DEFAULT_RECORDING));
    // this will let you use a logical device to make a new logical device on the parent physical device. Could be useful?
    SDL_AudioDevice *device = NULL;
    const bool islogical = (!wants_default && !(devid & (1<<1)));
    if (!islogical) {
        device = ObtainPhysicalAudioDeviceDefaultAllowed(devid);
    } else {
        SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
        if (logdev) {
            wants_default = logdev->opened_as_default;  // was the original logical device meant to be a default? Make this one, too.
        }
    }
    SDL_AudioDeviceID result = 0;
    if (device) {
        SDL_LogicalAudioDevice *logdev = NULL;
        if (!wants_default && SDL_GetAtomicInt(&device->zombie)) {
            // uhoh, this device is undead, and just waiting to be cleaned up. Refuse explicit opens.
            SDL_SetError("Device was already lost and can't accept new opens");
        } else if ((logdev = (SDL_LogicalAudioDevice *) SDL_calloc(1, sizeof (SDL_LogicalAudioDevice))) == NULL) {
            // SDL_calloc already called SDL_OutOfMemory
        } else if (!OpenPhysicalAudioDevice(device, spec)) {  // if this is the first thing using this physical device, open at the OS level if necessary...
            SDL_free(logdev);
        } else {
            RefPhysicalAudioDevice(device);  // unref'd on successful SDL_CloseAudioDevice
            SDL_SetAtomicInt(&logdev->paused, 0);
            result = logdev->instance_id = AssignAudioDeviceInstanceId(device->recording, /*islogical=*/true);
            logdev->physical_device = device;
            logdev->gain = 1.0f;
            logdev->opened_as_default = wants_default;
            logdev->next = device->logical_devices;
            if (device->logical_devices) {
                device->logical_devices->prev = logdev;
            }
            device->logical_devices = logdev;
            UpdateAudioStreamFormatsPhysical(device);
        }
        ReleaseAudioDevice(device);
        if (result) {
            SDL_LockRWLockForWriting(current_audio.device_hash_lock);
            const bool inserted = SDL_InsertIntoHashTable(current_audio.device_hash, (const void *) (uintptr_t) result, logdev, false);
            SDL_UnlockRWLock(current_audio.device_hash_lock);
            if (!inserted) {
                SDL_CloseAudioDevice(result);
                result = 0;
            }
        }
    }
    return result;
}
References AssignAudioDeviceInstanceId(), current_audio, SDL_LogicalAudioDevice::gain, SDL_LogicalAudioDevice::instance_id, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, NULL, ObtainLogicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), SDL_LogicalAudioDevice::opened_as_default, OpenPhysicalAudioDevice(), SDL_LogicalAudioDevice::paused, SDL_LogicalAudioDevice::physical_device, SDL_LogicalAudioDevice::prev, SDL_AudioDevice::recording, RefPhysicalAudioDevice(), ReleaseAudioDevice(), SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK, SDL_AUDIO_DEVICE_DEFAULT_RECORDING, SDL_calloc(), SDL_CloseAudioDevice(), SDL_free(), SDL_GetAtomicInt(), SDL_GetCurrentAudioDriver(), SDL_InsertIntoHashTable(), SDL_LockRWLockForWriting(), SDL_SetAtomicInt(), SDL_SetError(), SDL_UnlockRWLock(), UpdateAudioStreamFormatsPhysical(), and SDL_AudioDevice::zombie.
Referenced by SDL_OpenAudioDeviceStream().
SDL_OpenAudioDeviceStream()
SDL_AudioStream * SDL_OpenAudioDeviceStream (SDL_AudioDeviceID devid, const SDL_AudioSpec * spec, SDL_AudioStreamCallback callback, void * userdata)
Convenience function for straightforward audio init for the common case.
If all your app intends to do is provide a single source of PCM audio, this function allows you to do all your audio setup in a single call.
This is also intended to be a clean means to migrate apps from SDL2.
This function will open an audio device, create a stream and bind it. Unlike other methods of setup, the audio device will be closed when this stream is destroyed, so the app can treat the returned SDL_AudioStream as the only object needed to manage audio playback.
Also unlike other functions, the audio device begins paused. This is to map more closely to SDL2-style behavior, since there is no extra step here to bind a stream to begin audio flowing. The audio device should be resumed with SDL_ResumeAudioStreamDevice().
This function works with both playback and recording devices.
The spec parameter represents the app's side of the audio stream. That is, for recording audio, this will be the output format, and for playing audio, this will be the input format. If spec is NULL, the system will choose the format, and the app can use SDL_GetAudioStreamFormat() to obtain this information later.
If you don't care about opening a specific audio device, you can (and probably should), use SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK for playback and SDL_AUDIO_DEVICE_DEFAULT_RECORDING for recording.
One can optionally provide a callback function; if NULL, the app is expected to queue audio data for playback (or unqueue audio data if capturing). Otherwise, the callback will begin to fire once the device is unpaused.
Destroying the returned stream with SDL_DestroyAudioStream will also close the audio device associated with this stream.
Parameters
devid an audio device to open, or SDL_AUDIO_DEVICE_DEFAULT_PLAYBACK or SDL_AUDIO_DEVICE_DEFAULT_RECORDING.
spec the audio stream's data format. Can be NULL.
callback a callback where the app will provide new data for playback, or receive new data for recording. Can be NULL, in which case the app will need to call SDL_PutAudioStreamData or SDL_GetAudioStreamData as necessary.
userdata app-controlled pointer passed to callback. Can be NULL. Ignored if callback is NULL.
Returns
an audio stream on success, ready to use, or NULL on failure; call SDL_GetError() for more information. When done with this stream, call SDL_DestroyAudioStream to free resources and close the device.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioStreamDevice
SDL_ResumeAudioStreamDevice
{
    SDL_AudioDeviceID logdevid = SDL_OpenAudioDevice(devid, spec);
    if (!logdevid) {
        return NULL;  // error string should already be set.
    }
    bool failed = false;
    SDL_AudioStream *stream = NULL;
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(logdevid, &device);
    if (!logdev) { // this shouldn't happen, but just in case.
        failed = true;
    } else {
        SDL_SetAtomicInt(&logdev->paused, 1);   // start the device paused, to match SDL2.
        SDL_assert(device != NULL);
        const bool recording = device->recording;
        // if the app didn't request a format _at all_, just make a stream that does no conversion; they can query for it later.
        SDL_AudioSpec tmpspec;
        if (!spec) {
            SDL_copyp(&tmpspec, &device->spec);
            spec = &tmpspec;
        }
        if (recording) {
            stream = SDL_CreateAudioStream(&device->spec, spec);
        } else {
            stream = SDL_CreateAudioStream(spec, &device->spec);
        }
        if (!stream) {
            failed = true;
        } else {
            // don't do all the complicated validation and locking of SDL_BindAudioStream just to set a few fields here.
            logdev->bound_streams = stream;
            logdev->simplified = true;  // forbid further binding changes on this logical device.
            stream->bound_device = logdev;
            stream->simplified = true;  // so we know to close the audio device when this is destroyed.
            UpdateAudioStreamFormatsPhysical(device);
            if (callback) {
                bool rc;
                if (recording) {
                    rc = SDL_SetAudioStreamPutCallback(stream, callback, userdata);
                } else {
                    rc = SDL_SetAudioStreamGetCallback(stream, callback, userdata);
                }
                SDL_assert(rc);  // should only fail if stream==NULL atm.
            }
        }
    }
    ReleaseAudioDevice(device);
    if (failed) {
        SDL_DestroyAudioStream(stream);
        SDL_CloseAudioDevice(logdevid);
        stream = NULL;
    }
    return stream;
}
References SDL_LogicalAudioDevice::bound_streams, NULL, ObtainLogicalAudioDevice(), SDL_LogicalAudioDevice::paused, SDL_AudioDevice::recording, ReleaseAudioDevice(), SDL_assert, SDL_CloseAudioDevice(), SDL_copyp, SDL_CreateAudioStream(), SDL_DestroyAudioStream(), SDL_OpenAudioDevice(), SDL_SetAtomicInt(), SDL_SetAudioStreamGetCallback(), SDL_SetAudioStreamPutCallback(), SDL_LogicalAudioDevice::simplified, SDL_AudioDevice::spec, and UpdateAudioStreamFormatsPhysical().
SDL_PauseAudioDevice()
bool SDL_PauseAudioDevice (SDL_AudioDeviceID devid)
Use this function to pause audio playback on a specified device.
This function pauses audio processing for a given device. Any bound audio streams will not progress, and no audio will be generated. Pausing one device does not prevent other unpaused devices from running.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow. Pausing a paused device is a legal no-op.
Pausing a device can be useful to halt all audio without unbinding all the audio streams. This might be useful while a game is paused, or a level is loading, etc.
Physical devices can not be paused or unpaused, only logical devices created through SDL_OpenAudioDevice() can be.
Parameters
devid a device opened by SDL_OpenAudioDevice().
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResumeAudioDevice
SDL_AudioDevicePaused
{
    return SetLogicalAudioDevicePauseState(devid, 1);
}
References SetLogicalAudioDevicePauseState().
Referenced by SDL_PauseAudioStreamDevice().
SDL_PauseAudioStreamDevice()
bool SDL_PauseAudioStreamDevice (SDL_AudioStream * stream)
Use this function to pause audio playback on the audio device associated with an audio stream.
This function pauses audio processing for a given device. Any bound audio streams will not progress, and no audio will be generated. Pausing one device does not prevent other unpaused devices from running.
Pausing a device can be useful to halt all audio without unbinding all the audio streams. This might be useful while a game is paused, or a level is loading, etc.
Parameters
stream the audio stream associated with the audio device to pause.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResumeAudioStreamDevice
{
    SDL_AudioDeviceID devid = SDL_GetAudioStreamDevice(stream);
    if (!devid) {
        return false;
    }
    return SDL_PauseAudioDevice(devid);
}
References SDL_GetAudioStreamDevice(), and SDL_PauseAudioDevice().
SDL_PlaybackAudioThreadIterate()
bool SDL_PlaybackAudioThreadIterate (SDL_AudioDevice * device)
{
    SDL_assert(!device->recording);
    SDL_LockMutex(device->lock);
    if (SDL_GetAtomicInt(&device->shutdown)) {
        SDL_UnlockMutex(device->lock);
        return false;  // we're done, shut it down.
    }
    bool failed = false;
    int buffer_size = device->buffer_size;
    Uint8 *device_buffer = device->GetDeviceBuf(device, &buffer_size);
    if (buffer_size == 0) {
        // WASAPI (maybe others, later) does this to say "just abandon this iteration and try again next time."
    } else if (!device_buffer) {
        failed = true;
    } else {
        SDL_assert(buffer_size <= device->buffer_size);  // you can ask for less, but not more.
        SDL_assert(AudioDeviceCanUseSimpleCopy(device) == device->simple_copy);  // make sure this hasn't gotten out of sync.
        // can we do a basic copy without silencing/mixing the buffer? This is an extremely likely scenario, so we special-case it.
        if (device->simple_copy) {
            SDL_LogicalAudioDevice *logdev = device->logical_devices;
            SDL_AudioStream *stream = logdev->bound_streams;
            // We should have updated this elsewhere if the format changed!
            SDL_assert(SDL_AudioSpecsEqual(&stream->dst_spec, &device->spec, NULL, NULL));
            SDL_assert(stream->src_spec.format != SDL_AUDIO_UNKNOWN);
            const int br = SDL_GetAtomicInt(&logdev->paused) ? 0 : SDL_GetAudioStreamDataAdjustGain(stream, device_buffer, buffer_size, logdev->gain);
            if (br < 0) {  // Probably OOM. Kill the audio device; the whole thing is likely dying soon anyhow.
                failed = true;
                SDL_memset(device_buffer, device->silence_value, buffer_size);  // just supply silence to the device before we die.
            } else if (br < buffer_size) {
                SDL_memset(device_buffer + br, device->silence_value, buffer_size - br);  // silence whatever we didn't write to.
            }
            // generally channel maps will line up, but if the audio stream's chmap has been explicitly changed, do a final swizzle to device layout.
            if ((br > 0) && (!SDL_AudioChannelMapsEqual(device->spec.channels, stream->dst_chmap, device->chmap))) {
                ConvertAudio(br / SDL_AUDIO_FRAMESIZE(device->spec), device_buffer, device->spec.format, device->spec.channels, NULL,
                             device_buffer, device->spec.format, device->spec.channels, device->chmap, NULL, 1.0f);
            }
        } else {  // need to actually mix (or silence the buffer)
            float *final_mix_buffer = (float *) ((device->spec.format == SDL_AUDIO_F32) ? device_buffer : device->mix_buffer);
            const int needed_samples = buffer_size / SDL_AUDIO_BYTESIZE(device->spec.format);
            const int work_buffer_size = needed_samples * sizeof (float);
            SDL_AudioSpec outspec;
            SDL_assert(work_buffer_size <= device->work_buffer_size);
            SDL_copyp(&outspec, &device->spec);
            outspec.format = SDL_AUDIO_F32;
            SDL_memset(final_mix_buffer, '\0', work_buffer_size);  // start with silence.
            for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
                if (SDL_GetAtomicInt(&logdev->paused)) {
                    continue;  // paused? Skip this logical device.
                }
                const SDL_AudioPostmixCallback postmix = logdev->postmix;
                float *mix_buffer = final_mix_buffer;
                if (postmix) {
                    mix_buffer = device->postmix_buffer;
                    SDL_memset(mix_buffer, '\0', work_buffer_size);  // start with silence.
                }
                for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = stream->next_binding) {
                    // We should have updated this elsewhere if the format changed!
                    SDL_assert(SDL_AudioSpecsEqual(&stream->dst_spec, &outspec, NULL, NULL));
                    SDL_assert(stream->src_spec.format != SDL_AUDIO_UNKNOWN);
                    /* this will hold a lock on `stream` while getting. We don't explicitly lock the streams
                       for iterating here because the binding linked list can only change while the device lock is held.
                       (we _do_ lock the stream during binding/unbinding to make sure that two threads can't try to bind
                       the same stream to different devices at the same time, though.) */
                    const int br = SDL_GetAudioStreamDataAdjustGain(stream, device->work_buffer, work_buffer_size, logdev->gain);
                    if (br < 0) {  // Probably OOM. Kill the audio device; the whole thing is likely dying soon anyhow.
                        failed = true;
                        break;
                    } else if (br > 0) {  // it's okay if we get less than requested, we mix what we have.
                        // generally channel maps will line up, but if the audio stream's chmap has been explicitly changed, do a final swizzle to device layout.
                        if (!SDL_AudioChannelMapsEqual(device->spec.channels, stream->dst_chmap, device->chmap)) {
                            ConvertAudio(br / SDL_AUDIO_FRAMESIZE(device->spec), device->work_buffer, device->spec.format, device->spec.channels, NULL,
                                         device->work_buffer, device->spec.format, device->spec.channels, device->chmap, NULL, 1.0f);
                        }
                        MixFloat32Audio(mix_buffer, (float *) device->work_buffer, br);
                    }
                }
                if (postmix) {
                    SDL_assert(mix_buffer == device->postmix_buffer);
                    postmix(logdev->postmix_userdata, &outspec, mix_buffer, work_buffer_size);
                    MixFloat32Audio(final_mix_buffer, mix_buffer, work_buffer_size);
                }
            }
            if (((Uint8 *) final_mix_buffer) != device_buffer) {
                // !!! FIXME: we can't promise the device buf is aligned/padded for SIMD.
                //ConvertAudio(needed_samples / device->spec.channels, final_mix_buffer, SDL_AUDIO_F32, device->spec.channels, NULL, device_buffer, device->spec.format, device->spec.channels, NULL, NULL, 1.0f);
                ConvertAudio(needed_samples / device->spec.channels, final_mix_buffer, SDL_AUDIO_F32, device->spec.channels, NULL, device->work_buffer, device->spec.format, device->spec.channels, NULL, NULL, 1.0f);
                SDL_memcpy(device_buffer, device->work_buffer, buffer_size);
            }
        }
        // PlayDevice SHOULD NOT BLOCK, as we are holding a lock right now. Block in WaitDevice instead!
        if (!device->PlayDevice(device, device_buffer, buffer_size)) {
            failed = true;
        }
    }
    SDL_UnlockMutex(device->lock);
    if (failed) {
        SDL_AudioDeviceDisconnected(device);  // doh.
    }
    return true;  // always go on if not shutting down, even if device failed.
}
References AudioDeviceCanUseSimpleCopy(), SDL_LogicalAudioDevice::bound_streams, SDL_AudioDevice::buffer_size, SDL_AudioSpec::channels, SDL_AudioDevice::chmap, ConvertAudio(), SDL_AudioSpec::format, SDL_LogicalAudioDevice::gain, SDL_AudioDevice::GetDeviceBuf, SDL_AudioDevice::lock, SDL_AudioDevice::logical_devices, SDL_AudioDevice::mix_buffer, MixFloat32Audio(), SDL_LogicalAudioDevice::next, NULL, SDL_LogicalAudioDevice::paused, SDL_AudioDevice::PlayDevice, SDL_AudioDevice::postmix_buffer, SDL_AudioDevice::recording, SDL_assert, SDL_AUDIO_BYTESIZE, SDL_AUDIO_F32, SDL_AUDIO_FRAMESIZE, SDL_AUDIO_UNKNOWN, SDL_AudioChannelMapsEqual(), SDL_AudioDeviceDisconnected(), SDL_AudioSpecsEqual(), SDL_copyp, SDL_GetAtomicInt(), SDL_GetAudioStreamDataAdjustGain(), SDL_LockMutex(), SDL_memcpy, SDL_memset, SDL_UnlockMutex(), SDL_AudioDevice::shutdown, SDL_AudioDevice::silence_value, SDL_AudioDevice::simple_copy, SDL_AudioDevice::spec, and SDL_AudioDevice::work_buffer.
Referenced by DUMMYAUDIO_OpenDevice(), and PlaybackAudioThread().
SDL_PlaybackAudioThreadSetup()
void SDL_PlaybackAudioThreadSetup (SDL_AudioDevice * device)
{
    SDL_assert(!device->recording);
    current_audio.impl.ThreadInit(device);
}
References current_audio, SDL_AudioDevice::recording, and SDL_assert.
Referenced by PlaybackAudioThread().
SDL_PlaybackAudioThreadShutdown()
void SDL_PlaybackAudioThreadShutdown (SDL_AudioDevice * device)
{
    SDL_assert(!device->recording);
    const int frames = device->buffer_size / SDL_AUDIO_FRAMESIZE(device->spec);
    // Wait for the audio to drain if device didn't die.
    if (!SDL_GetAtomicInt(&device->zombie)) {
        SDL_Delay(((frames * 1000) / device->spec.freq) * 2);
    }
    current_audio.impl.ThreadDeinit(device);
    SDL_AudioThreadFinalize(device);
}
References SDL_AudioDevice::buffer_size, current_audio, SDL_AudioSpec::freq, SDL_AudioDevice::recording, SDL_assert, SDL_AUDIO_FRAMESIZE, SDL_AudioThreadFinalize(), SDL_Delay(), SDL_GetAtomicInt(), SDL_AudioDevice::spec, and SDL_AudioDevice::zombie.
Referenced by PlaybackAudioThread().
SDL_QuitAudio()
void SDL_QuitAudio (void)
{
    if (!current_audio.name) {  // not initialized?!
        return;
    }
    current_audio.impl.DeinitializeStart();
    // Destroy any audio streams that still exist...unless app asked to keep it.
    SDL_AudioStream *next = NULL;
    for (SDL_AudioStream *i = current_audio.existing_streams; i; i = next) {
        next = i->next;
        if (i->simplified || SDL_GetBooleanProperty(i->props, SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN, true)) {
            SDL_DestroyAudioStream(i);
        } else {
            i->prev = NULL;
            i->next = NULL;
        }
    }
    SDL_LockRWLockForWriting(current_audio.device_hash_lock);
    SDL_SetAtomicInt(&current_audio.shutting_down, 1);
    SDL_HashTable *device_hash = current_audio.device_hash;
    current_audio.device_hash = NULL;
    SDL_PendingAudioDeviceEvent *pending_events = current_audio.pending_events.next;
    current_audio.pending_events.next = NULL;
    SDL_SetAtomicInt(&current_audio.playback_device_count, 0);
    SDL_SetAtomicInt(&current_audio.recording_device_count, 0);
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    SDL_PendingAudioDeviceEvent *pending_next = NULL;
    for (SDL_PendingAudioDeviceEvent *i = pending_events; i; i = pending_next) {
        pending_next = i->next;
        SDL_free(i);
    }
    SDL_IterateHashTable(device_hash, DestroyOnePhysicalAudioDevice, NULL);
    // Free the driver data
    current_audio.impl.Deinitialize();
    SDL_DestroyRWLock(current_audio.device_hash_lock);
    SDL_DestroyHashTable(device_hash);
    SDL_zero(current_audio);
}
References current_audio, DestroyOnePhysicalAudioDevice(), SDL_AudioStream::next, SDL_PendingAudioDeviceEvent::next, NULL, SDL_DestroyAudioStream(), SDL_DestroyHashTable(), SDL_DestroyRWLock(), SDL_free(), SDL_GetBooleanProperty(), SDL_IterateHashTable(), SDL_LockRWLockForWriting(), SDL_PROP_AUDIOSTREAM_AUTO_CLEANUP_BOOLEAN, SDL_SetAtomicInt(), SDL_UnlockRWLock(), and SDL_zero.
Referenced by SDL_InitAudio(), and SDL_QuitSubSystem().
SDL_RecordingAudioThreadIterate()
bool SDL_RecordingAudioThreadIterate (SDL_AudioDevice * device)
{
    SDL_assert(device->recording);
    SDL_LockMutex(device->lock);
    if (SDL_GetAtomicInt(&device->shutdown)) {
        SDL_UnlockMutex(device->lock);
        return false;  // we're done, shut it down.
    }
    bool failed = false;
    if (!device->logical_devices) {
        device->FlushRecording(device); // nothing wants data, dump anything pending.
    } else {
        // this SHOULD NOT BLOCK, as we are holding a lock right now. Block in WaitRecordingDevice!
        int br = device->RecordDevice(device, device->work_buffer, device->buffer_size);
        if (br < 0) {  // uhoh, device failed for some reason!
            failed = true;
        } else if (br > 0) {  // queue the new data to each bound stream.
            for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
                if (SDL_GetAtomicInt(&logdev->paused)) {
                    continue;  // paused? Skip this logical device.
                }
                void *output_buffer = device->work_buffer;
                // I don't know why someone would want a postmix on a recording device, but we offer it for API consistency.
                if (logdev->postmix || (logdev->gain != 1.0f)) {
                    // move to float format.
                    SDL_AudioSpec outspec;
                    SDL_copyp(&outspec, &device->spec);
                    outspec.format = SDL_AUDIO_F32;
                    output_buffer = device->postmix_buffer;
                    const int frames = br / SDL_AUDIO_FRAMESIZE(device->spec);
                    br = frames * SDL_AUDIO_FRAMESIZE(outspec);
                    ConvertAudio(frames, device->work_buffer, device->spec.format, outspec.channels, NULL, device->postmix_buffer, SDL_AUDIO_F32, outspec.channels, NULL, NULL, logdev->gain);
                    if (logdev->postmix) {
                        logdev->postmix(logdev->postmix_userdata, &outspec, device->postmix_buffer, br);
                    }
                }
                for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = stream->next_binding) {
                    // We should have updated this elsewhere if the format changed!
                    SDL_assert(stream->src_spec.format == ((logdev->postmix || (logdev->gain != 1.0f)) ? SDL_AUDIO_F32 : device->spec.format));
                    SDL_assert(stream->src_spec.channels == device->spec.channels);
                    SDL_assert(stream->src_spec.freq == device->spec.freq);
                    SDL_assert(stream->dst_spec.format != SDL_AUDIO_UNKNOWN);
                    void *final_buf = output_buffer;
                    // generally channel maps will line up, but if the audio stream's chmap has been explicitly changed, do a final swizzle to stream layout.
                    if (!SDL_AudioChannelMapsEqual(device->spec.channels, stream->src_chmap, device->chmap)) {
                        final_buf = device->mix_buffer;  // this is otherwise unused on recording devices, so it makes convenient scratch space here.
                        ConvertAudio(br / SDL_AUDIO_FRAMESIZE(device->spec), output_buffer, device->spec.format, device->spec.channels, NULL,
                                     final_buf, device->spec.format, device->spec.channels, stream->src_chmap, NULL, 1.0f);
                    }
                    /* this will hold a lock on `stream` while putting. We don't explicitly lock the streams
                       for iterating here because the binding linked list can only change while the device lock is held.
                       (we _do_ lock the stream during binding/unbinding to make sure that two threads can't try to bind
                       the same stream to different devices at the same time, though.) */
                    if (!SDL_PutAudioStreamData(stream, final_buf, br)) {
                        // oh crud, we probably ran out of memory. This is possibly an overreaction to kill the audio device, but it's likely the whole thing is going down in a moment anyhow.
                        failed = true;
                        break;
                    }
                }
            }
        }
    }
    SDL_UnlockMutex(device->lock);
    if (failed) {
        SDL_AudioDeviceDisconnected(device);  // doh.
    }
    return true;  // always go on if not shutting down, even if device failed.
}
References SDL_AudioDevice::buffer_size, SDL_AudioSpec::channels, SDL_AudioDevice::chmap, ConvertAudio(), SDL_AudioDevice::FlushRecording, SDL_AudioSpec::format, SDL_AudioSpec::freq, SDL_AudioDevice::lock, SDL_AudioDevice::logical_devices, SDL_AudioDevice::mix_buffer, SDL_LogicalAudioDevice::next, NULL, SDL_AudioDevice::postmix_buffer, SDL_AudioDevice::RecordDevice, SDL_AudioDevice::recording, SDL_assert, SDL_AUDIO_F32, SDL_AUDIO_FRAMESIZE, SDL_AUDIO_UNKNOWN, SDL_AudioChannelMapsEqual(), SDL_AudioDeviceDisconnected(), SDL_copyp, SDL_GetAtomicInt(), SDL_LockMutex(), SDL_PutAudioStreamData(), SDL_UnlockMutex(), SDL_AudioDevice::shutdown, SDL_AudioDevice::spec, and SDL_AudioDevice::work_buffer.
Referenced by DUMMYAUDIO_OpenDevice(), and RecordingAudioThread().
SDL_RecordingAudioThreadSetup()
void SDL_RecordingAudioThreadSetup (SDL_AudioDevice * device)
{
    SDL_assert(device->recording);
    current_audio.impl.ThreadInit(device);
}
References current_audio, SDL_AudioDevice::recording, and SDL_assert.
Referenced by RecordingAudioThread().
SDL_RecordingAudioThreadShutdown()
void SDL_RecordingAudioThreadShutdown (SDL_AudioDevice * device)
{
    SDL_assert(device->recording);
    device->FlushRecording(device);
    current_audio.impl.ThreadDeinit(device);
    SDL_AudioThreadFinalize(device);
}
References current_audio, SDL_AudioDevice::FlushRecording, SDL_AudioDevice::recording, SDL_assert, and SDL_AudioThreadFinalize().
Referenced by RecordingAudioThread().
SDL_ResumeAudioDevice()
bool SDLCALL SDL_ResumeAudioDevice (SDL_AudioDeviceID devid)
Use this function to unpause audio playback on a specified device.
This function unpauses audio processing for a given device that has previously been paused with SDL_PauseAudioDevice(). Once unpaused, any bound audio streams will begin to progress again, and audio can be generated.
Unlike in SDL2, audio devices start in an unpaused state, since an app has to bind a stream before any audio will flow. Unpausing an unpaused device is a legal no-op.
Physical devices can not be paused or unpaused, only logical devices created through SDL_OpenAudioDevice() can be.
Parameters
devid a device opened by SDL_OpenAudioDevice().
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AudioDevicePaused
SDL_PauseAudioDevice
{
    return SetLogicalAudioDevicePauseState(devid, 0);
}
References SDLCALL, and SetLogicalAudioDevicePauseState().
Referenced by SDL_ResumeAudioStreamDevice().
SDL_ResumeAudioStreamDevice()
bool SDL_ResumeAudioStreamDevice (SDL_AudioStream * stream)
Use this function to unpause audio playback on the audio device associated with an audio stream.
This function unpauses audio processing for a given device that has previously been paused. Once unpaused, any bound audio streams will begin to progress again, and audio can be generated.
SDL_OpenAudioDeviceStream opens audio devices in a paused state, so this function call is required for audio playback to begin on such devices.
Parameters
stream the audio stream associated with the audio device to resume.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseAudioStreamDevice
{
    SDL_AudioDeviceID devid = SDL_GetAudioStreamDevice(stream);
    if (!devid) {
        return false;
    }
    return SDL_ResumeAudioDevice(devid);
}
References SDL_GetAudioStreamDevice(), and SDL_ResumeAudioDevice().
SDL_SetAudioDeviceGain()
bool SDL_SetAudioDeviceGain (SDL_AudioDeviceID devid, float gain)
Change the gain of an audio device.
The gain of a device is its volume; a larger gain means a louder output, with a gain of zero being silence.
Audio devices default to a gain of 1.0f (no change in output).
Physical devices may not have their gain changed, only logical devices, and this function will always return false when used on physical devices. While it might seem attractive to adjust several logical devices at once in this way, it would allow an app or library to interfere with another portion of the program's otherwise-isolated devices.
This is applied, along with any per-audiostream gain, during playback to the hardware, and can be continuously changed to create various effects. On recording devices, this will adjust the gain before passing the data into an audiostream; that recording audiostream can then adjust its gain further when outputting the data elsewhere, if it likes, but that second gain is not applied until the data leaves the audiostream again.
Parameters
devid the audio device on which to change gain.
gain the gain. 1.0f is no change, 0.0f is silence.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread, as it holds a stream-specific mutex while running.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetAudioDeviceGain
{
    if (gain < 0.0f) {
        return SDL_InvalidParamError("gain");
    }
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    bool result = false;
    if (logdev) {
        logdev->gain = gain;
        UpdateAudioStreamFormatsPhysical(device);
        result = true;
    }
    ReleaseAudioDevice(device);
    return result;
}
References SDL_LogicalAudioDevice::gain, NULL, ObtainLogicalAudioDevice(), ReleaseAudioDevice(), SDL_InvalidParamError, and UpdateAudioStreamFormatsPhysical().
SDL_SetAudioPostmixCallback()
bool SDL_SetAudioPostmixCallback (SDL_AudioDeviceID devid, SDL_AudioPostmixCallback callback, void * userdata)
Set a callback that fires when data is about to be fed to an audio device.
This is useful for accessing the final mix, perhaps for writing a visualizer or applying a final effect to the audio data before playback.
The buffer is the final mix of all bound audio streams on an opened device; this callback will fire regularly for any device that is both opened and unpaused. If there is no new data to mix, either because no streams are bound to the device or all the streams are empty, this callback will still fire with the entire buffer set to silence.
This callback is allowed to make changes to the data; the contents of the buffer after this call is what is ultimately passed along to the hardware.
The callback is always provided the data in float format (values from -1.0f to 1.0f), but the number of channels or sample rate may be different than the format the app requested when opening the device; SDL might have had to manage a conversion behind the scenes, or the playback might have jumped to new physical hardware when a system default changed, etc. These details may change between calls. Accordingly, the size of the buffer might change between calls as well.
This callback can run at any time, and from any thread; if you need to serialize access to your app's data, you should provide and use a mutex or other synchronization device.
All of this to say: there are specific needs this callback can fulfill, but it is not the simplest interface. Apps should generally provide audio in their preferred format through an SDL_AudioStream and let SDL handle the difference.
This function is extremely time-sensitive; the callback should do the least amount of work possible and return as quickly as it can. The longer the callback runs, the higher the risk of audio dropouts or other problems.
This function will block until the audio device is in between iterations, so any existing callback that might be running will finish before this function sets the new callback and returns.
Setting a NULL callback function disables any previously-set callback.
Parameters
devid the ID of an opened audio device.
callback a callback function to be called. Can be NULL.
userdata app-controlled pointer passed to callback. Can be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    bool result = false;
    if (logdev) {
        result = true;
        if (callback && !device->postmix_buffer) {
            device->postmix_buffer = (float *)SDL_aligned_alloc(SDL_GetSIMDAlignment(), device->work_buffer_size);
            if (!device->postmix_buffer) {
                result = false;
            }
        }
        if (result) {
            logdev->postmix = callback;
            logdev->postmix_userdata = userdata;
        }
        UpdateAudioStreamFormatsPhysical(device);
    }
    ReleaseAudioDevice(device);
    return result;
}
References NULL, ObtainLogicalAudioDevice(), SDL_LogicalAudioDevice::postmix, SDL_AudioDevice::postmix_buffer, SDL_LogicalAudioDevice::postmix_userdata, ReleaseAudioDevice(), SDL_aligned_alloc(), SDL_GetSIMDAlignment(), UpdateAudioStreamFormatsPhysical(), and SDL_AudioDevice::work_buffer_size.
Referenced by SDL_DefaultAudioDeviceChanged().
SDL_UnbindAudioStream()
void SDL_UnbindAudioStream (SDL_AudioStream * stream)
Unbind a single audio stream from its audio device.
This is a convenience function, equivalent to calling SDL_UnbindAudioStreams(&stream, 1).
Parameters
stream an audio stream to unbind from a device. Can be NULL.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStream
{
    SDL_UnbindAudioStreams(&stream, 1);
}
References SDL_UnbindAudioStreams().
Referenced by SDL_DestroyAudioStream().
SDL_UnbindAudioStreams()
void SDL_UnbindAudioStreams (SDL_AudioStream *const * streams, int num_streams)
Unbind a list of audio streams from their audio devices.
The streams being unbound do not all have to be on the same device. All streams on the same device will be unbound atomically (data will stop flowing through all unbound streams on the same device at the same time).
Unbinding a stream that isn't bound to a device is a legal no-op.
Parameters
streams an array of audio streams to unbind. Can be NULL or contain NULL.
num_streams number streams listed in the streams array.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BindAudioStreams
{
    if (num_streams <= 0 || !streams) {
        return; // nothing to do
    }
    /* to prevent deadlock when holding both locks, we _must_ lock the device first, and the stream second, as that is the order the audio thread will do it.
       But this means we have an unlikely, pathological case where a stream could change its binding between when we lookup its bound device and when we lock everything,
       so we double-check here. */
    for (int i = 0; i < num_streams; i++) {
        SDL_AudioStream *stream = streams[i];
        if (!stream) {
            continue;  // nothing to do, it's a NULL stream.
        }
        while (true) {
            SDL_LockMutex(stream->lock);   // lock to check this and then release it, in case the device isn't locked yet.
            SDL_LogicalAudioDevice *bounddev = stream->bound_device;
            SDL_UnlockMutex(stream->lock);
            // lock in correct order.
            if (bounddev) {
                SDL_LockMutex(bounddev->physical_device->lock);  // this requires recursive mutexes, since we're likely locking the same device multiple times.
            }
            SDL_LockMutex(stream->lock);
            if (bounddev == stream->bound_device) {
                break;  // the binding didn't change in the small window where it could, so we're good.
            } else {
                SDL_UnlockMutex(stream->lock);  // it changed bindings! Try again.
                if (bounddev) {
                    SDL_UnlockMutex(bounddev->physical_device->lock);
                }
            }
        }
    }
    // everything is locked, start unbinding streams.
    for (int i = 0; i < num_streams; i++) {
        SDL_AudioStream *stream = streams[i];
        // don't allow unbinding from "simplified" devices (opened with SDL_OpenAudioDeviceStream). Just ignore them.
        if (stream && stream->bound_device && !stream->bound_device->simplified) {
            if (stream->bound_device->bound_streams == stream) {
                SDL_assert(!stream->prev_binding);
                stream->bound_device->bound_streams = stream->next_binding;
            }
            if (stream->prev_binding) {
                stream->prev_binding->next_binding = stream->next_binding;
            }
            if (stream->next_binding) {
                stream->next_binding->prev_binding = stream->prev_binding;
            }
            stream->prev_binding = stream->next_binding = NULL;
        }
    }
    // Finalize and unlock everything.
    for (int i = 0; i < num_streams; i++) {
        SDL_AudioStream *stream = streams[i];
        if (stream) {
            SDL_LogicalAudioDevice *logdev = stream->bound_device;
            stream->bound_device = NULL;
            SDL_UnlockMutex(stream->lock);
            if (logdev) {
                UpdateAudioStreamFormatsPhysical(logdev->physical_device);
                SDL_UnlockMutex(logdev->physical_device->lock);
            }
        }
    }
}
References SDL_AudioDevice::lock, NULL, SDL_LogicalAudioDevice::physical_device, SDL_assert, SDL_LockMutex(), SDL_UnlockMutex(), and UpdateAudioStreamFormatsPhysical().
Referenced by SDL_UnbindAudioStream().
SDL_UpdateAudio()
void SDL_UpdateAudio (void)
{
    SDL_LockRWLockForReading(current_audio.device_hash_lock);
    SDL_PendingAudioDeviceEvent *pending_events = current_audio.pending_events.next;
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    if (!pending_events) {
        return;  // nothing to do, check next time.
    }
    // okay, let's take this whole list of events so we can dump the lock, and new ones can queue up for a later update.
    SDL_LockRWLockForWriting(current_audio.device_hash_lock);
    pending_events = current_audio.pending_events.next;  // in case this changed...
    current_audio.pending_events.next = NULL;
    current_audio.pending_events_tail = &current_audio.pending_events;
    SDL_UnlockRWLock(current_audio.device_hash_lock);
    SDL_PendingAudioDeviceEvent *pending_next = NULL;
    for (SDL_PendingAudioDeviceEvent *i = pending_events; i; i = pending_next) {
        pending_next = i->next;
        if (SDL_EventEnabled(i->type)) {
            SDL_Event event;
            SDL_zero(event);
            event.type = i->type;
            event.adevice.which = (Uint32) i->devid;
            event.adevice.recording = ((i->devid & (1<<0)) == 0);  // bit #0 of devid is set for playback devices and unset for recording.
            SDL_PushEvent(&event);
        }
        SDL_free(i);
    }
}
References current_audio, SDL_PendingAudioDeviceEvent::next, NULL, SDL_EventEnabled(), SDL_free(), SDL_LockRWLockForReading(), SDL_LockRWLockForWriting(), SDL_PushEvent(), SDL_UnlockRWLock(), and SDL_zero.
Referenced by SDL_PumpEventMaintenance().
SDL_UpdatedAudioDeviceFormat()
void SDL_UpdatedAudioDeviceFormat (SDL_AudioDevice * device)
{
    device->silence_value = SDL_GetSilenceValueForFormat(device->spec.format);
    device->buffer_size = device->sample_frames * SDL_AUDIO_FRAMESIZE(device->spec);
    device->work_buffer_size = device->sample_frames * sizeof (float) * device->spec.channels;
    device->work_buffer_size = SDL_max(device->buffer_size, device->work_buffer_size);  // just in case we end up with a 64-bit audio format at some point.
}
References SDL_AudioDevice::buffer_size, SDL_AudioSpec::channels, SDL_AudioSpec::format, SDL_AudioDevice::sample_frames, SDL_AUDIO_FRAMESIZE, SDL_GetSilenceValueForFormat(), SDL_max, SDL_AudioDevice::silence_value, SDL_AudioDevice::spec, and SDL_AudioDevice::work_buffer_size.
Referenced by OpenPhysicalAudioDevice(), PS2AUDIO_OpenDevice(), and SDL_AudioDeviceFormatChangedAlreadyLocked().
SerializePhysicalDeviceClose()
void SerializePhysicalDeviceClose (SDL_AudioDevice * device) static
{
    while (SDL_GetAtomicInt(&device->shutdown)) {
        SDL_WaitCondition(device->close_cond, device->lock);
    }
}
References SDL_AudioDevice::close_cond, SDL_AudioDevice::lock, SDL_GetAtomicInt(), SDL_WaitCondition(), and SDL_AudioDevice::shutdown.
Referenced by ClosePhysicalAudioDevice(), and OpenPhysicalAudioDevice().
SetLogicalAudioDevicePauseState()
bool SetLogicalAudioDevicePauseState (SDL_AudioDeviceID devid, int value) static
{
    SDL_AudioDevice *device = NULL;
    SDL_LogicalAudioDevice *logdev = ObtainLogicalAudioDevice(devid, &device);
    if (logdev) {
        SDL_SetAtomicInt(&logdev->paused, value);
    }
    ReleaseAudioDevice(device);
    return logdev ? true : false;  // ObtainLogicalAudioDevice will have set an error.
}
References NULL, ObtainLogicalAudioDevice(), SDL_LogicalAudioDevice::paused, ReleaseAudioDevice(), SDL_SetAtomicInt(), and true.
Referenced by SDL_PauseAudioDevice(), and SDL_ResumeAudioDevice().
TestDeviceHandleCallback()
bool TestDeviceHandleCallback (SDL_AudioDevice * device, void * handle) static
{
    return device->handle == handle;
}
References SDL_AudioDevice::handle.
Referenced by SDL_FindPhysicalAudioDeviceByHandle().
UnrefPhysicalAudioDevice()
void UnrefPhysicalAudioDevice (SDL_AudioDevice * device)
{
    if (SDL_AtomicDecRef(&device->refcount)) {
        // take it out of the device list.
        SDL_LockRWLockForWriting(current_audio.device_hash_lock);
        if (SDL_RemoveFromHashTable(current_audio.device_hash, (const void *) (uintptr_t) device->instance_id)) {
            SDL_AddAtomicInt(device->recording ? &current_audio.recording_device_count : &current_audio.playback_device_count, -1);
        }
        SDL_UnlockRWLock(current_audio.device_hash_lock);
        DestroyPhysicalAudioDevice(device);  // ...and nuke it.
    }
}
References current_audio, DestroyPhysicalAudioDevice(), SDL_AudioDevice::instance_id, SDL_AudioDevice::recording, SDL_AudioDevice::refcount, SDL_AddAtomicInt(), SDL_AtomicDecRef, SDL_LockRWLockForWriting(), SDL_RemoveFromHashTable(), and SDL_UnlockRWLock().
Referenced by ObtainLogicalAudioDevice(), ReleaseAudioDevice(), SDL_AudioDeviceDisconnected(), SDL_CloseAudioDevice(), and SDL_DefaultAudioDeviceChanged().
UpdateAudioStreamFormatsPhysical()
void UpdateAudioStreamFormatsPhysical (SDL_AudioDevice * device) static
{
    if (!device) {
        return;
    }
    const bool recording = device->recording;
    SDL_AudioSpec spec;
    SDL_copyp(&spec, &device->spec);
    const SDL_AudioFormat devformat = spec.format;
    if (!recording) {
        const bool simple_copy = AudioDeviceCanUseSimpleCopy(device);
        device->simple_copy = simple_copy;
        if (!simple_copy) {
            spec.format = SDL_AUDIO_F32;  // mixing and postbuf operates in float32 format.
        }
    }
    for (SDL_LogicalAudioDevice *logdev = device->logical_devices; logdev; logdev = logdev->next) {
        if (recording) {
            const bool need_float32 = (logdev->postmix || logdev->gain != 1.0f);
            spec.format = need_float32 ? SDL_AUDIO_F32 : devformat;
        }
        for (SDL_AudioStream *stream = logdev->bound_streams; stream; stream = stream->next_binding) {
            // set the proper end of the stream to the device's format.
            // SDL_SetAudioStreamFormat does a ton of validation just to memcpy an audiospec.
            SDL_AudioSpec *streamspec = recording ? &stream->src_spec : &stream->dst_spec;
            int **streamchmap = recording ? &stream->src_chmap : &stream->dst_chmap;
            SDL_LockMutex(stream->lock);
            SDL_copyp(streamspec, &spec);
            SetAudioStreamChannelMap(stream, streamspec, streamchmap, device->chmap, device->spec.channels, -1);  // this should be fast for normal cases, though!
            SDL_UnlockMutex(stream->lock);
        }
    }
}
References AudioDeviceCanUseSimpleCopy(), SDL_AudioSpec::channels, SDL_AudioDevice::chmap, SDL_AudioSpec::format, SDL_AudioDevice::logical_devices, SDL_LogicalAudioDevice::next, SDL_AudioDevice::recording, SDL_AUDIO_F32, SDL_copyp, SDL_LockMutex(), SDL_UnlockMutex(), SetAudioStreamChannelMap(), SDL_AudioDevice::simple_copy, and SDL_AudioDevice::spec.
Referenced by DestroyLogicalAudioDevice(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_BindAudioStreams(), SDL_DefaultAudioDeviceChanged(), SDL_OpenAudioDevice(), SDL_OpenAudioDeviceStream(), SDL_SetAudioDeviceGain(), SDL_SetAudioPostmixCallback(), and SDL_UnbindAudioStreams().
ZombieFlushRecording()
void ZombieFlushRecording (SDL_AudioDevice * device) static
{
    // no-op, this is all imaginary.
}
Referenced by SDL_AudioDeviceDisconnected().
ZombieGetDeviceBuf()
Uint8 * ZombieGetDeviceBuf (SDL_AudioDevice * device, int * buffer_size) static
{
    return device->work_buffer;
}
References SDL_AudioDevice::work_buffer.
Referenced by SDL_AudioDeviceDisconnected().
ZombiePlayDevice()
bool ZombiePlayDevice (SDL_AudioDevice * device, const Uint8 * buffer, int buflen) static
{
    return true;  // no-op, just throw the audio away.
}
Referenced by SDL_AudioDeviceDisconnected().
ZombieRecordDevice()
int ZombieRecordDevice (SDL_AudioDevice * device, void * buffer, int buflen) static
{
    // return a full buffer of silence every time.
    SDL_memset(buffer, device->silence_value, buflen);
    return buflen;
}
References SDL_memset, and SDL_AudioDevice::silence_value.
Referenced by SDL_AudioDeviceDisconnected().
ZombieWaitDevice()
bool ZombieWaitDevice (SDL_AudioDevice * device) static
{
    if (!SDL_GetAtomicInt(&device->shutdown)) {
        const int frames = device->buffer_size / SDL_AUDIO_FRAMESIZE(device->spec);
        SDL_Delay((frames * 1000) / device->spec.freq);
    }
    return true;
}
References SDL_AudioDevice::buffer_size, SDL_AudioSpec::freq, SDL_AUDIO_FRAMESIZE, SDL_Delay(), SDL_GetAtomicInt(), SDL_AudioDevice::shutdown, and SDL_AudioDevice::spec.
Referenced by SDL_AudioDeviceDisconnected(), and SDL_CameraDisconnected().
Variable Documentation
bootstrap
const AudioBootStrap* const bootstrap[] static
{
#ifdef SDL_AUDIO_DRIVER_PRIVATE
    &PRIVATEAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_PULSEAUDIO
#ifdef SDL_AUDIO_DRIVER_PIPEWIRE
    &PIPEWIRE_PREFERRED_bootstrap,
#endif
    &PULSEAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_PIPEWIRE
    &PIPEWIRE_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_ALSA
    &ALSA_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_SNDIO
    &SNDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_NETBSD
    &NETBSDAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_WASAPI
    &WASAPI_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_DSOUND
    &DSOUND_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_HAIKU
    &HAIKUAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_COREAUDIO
    &COREAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_AAUDIO
    &AAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_OPENSLES
    &OPENSLES_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_PS2
    &PS2AUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_PSP
    &PSPAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_VITA
    &VITAAUD_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_N3DS
    &N3DSAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_NGAGE
    &NGAGEAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_EMSCRIPTEN
    &EMSCRIPTENAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_JACK
    &JACK_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_OSS
    &DSP_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_QNX
    &QSAAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_DISK
    &DISKAUDIO_bootstrap,
#endif
#ifdef SDL_AUDIO_DRIVER_DUMMY
    &DUMMYAUDIO_bootstrap,
#endif
    NULL
};
Referenced by SDL_CameraInit(), SDL_GetCameraDriver(), SDL_GetNumAudioDrivers(), SDL_GetNumCameraDrivers(), SDL_GetNumVideoDrivers(), SDL_InitAudio(), SDL_ShowMessageBox(), and SDL_VideoInit().
current_audio
SDL_AudioDriver current_audio static
Referenced by ClosePhysicalAudioDevice(), CreateAudioPlaybackDevice(), CreateAudioRecordingDevice(), CreatePhysicalAudioDevice(), DestroyLogicalAudioDevice(), DestroyPhysicalAudioDevice(), GetAudioDevices(), GetFirstAddedAudioDevice(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), OnAudioStreamCreated(), OnAudioStreamDestroy(), OpenPhysicalAudioDevice(), SDL_AddAudioDevice(), SDL_AudioDetectDevices_Default(), SDL_AudioDeviceDisconnected(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_DefaultAudioDeviceChanged(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_GetAudioDeviceName(), SDL_GetCurrentAudioDriver(), SDL_InitAudio(), SDL_OpenAudioDevice(), SDL_PlaybackAudioThreadSetup(), SDL_PlaybackAudioThreadShutdown(), SDL_QuitAudio(), SDL_RecordingAudioThreadSetup(), SDL_RecordingAudioThreadShutdown(), SDL_UpdateAudio(), and UnrefPhysicalAudioDevice().
deduped_bootstrap
const AudioBootStrap* deduped_bootstrap[SDL_arraysize(bootstrap) - 1] static
Referenced by SDL_GetAudioDriver(), SDL_GetNumAudioDrivers(), SDL_GetNumVideoDrivers(), and SDL_GetVideoDriver().
format_list
const SDL_AudioFormat format_list[8][8+1] static
Initial value:
= {
    { SDL_AUDIO_U8,  SDL_AUDIO_F32LE ,   SDL_AUDIO_F32BE , SDL_AUDIO_S8,  SDL_AUDIO_S16LE ,   SDL_AUDIO_S16BE ,  SDL_AUDIO_S32LE ,   SDL_AUDIO_S32BE , SDL_AUDIO_UNKNOWN },
    { SDL_AUDIO_S8,  SDL_AUDIO_F32LE ,   SDL_AUDIO_F32BE , SDL_AUDIO_U8,  SDL_AUDIO_S16LE ,   SDL_AUDIO_S16BE ,  SDL_AUDIO_S32LE ,   SDL_AUDIO_S32BE , SDL_AUDIO_UNKNOWN },
    {  SDL_AUDIO_S16LE ,   SDL_AUDIO_F32LE ,   SDL_AUDIO_F32BE ,  SDL_AUDIO_S16BE ,  SDL_AUDIO_S32LE ,   SDL_AUDIO_S32BE , SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    {  SDL_AUDIO_S16BE ,  SDL_AUDIO_F32LE ,   SDL_AUDIO_F32BE ,  SDL_AUDIO_S16LE ,   SDL_AUDIO_S32BE ,  SDL_AUDIO_S32LE ,  SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    {  SDL_AUDIO_S32LE ,   SDL_AUDIO_F32LE ,   SDL_AUDIO_F32BE ,  SDL_AUDIO_S32BE ,  SDL_AUDIO_S16LE ,   SDL_AUDIO_S16BE , SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    {  SDL_AUDIO_S32BE ,  SDL_AUDIO_F32LE ,   SDL_AUDIO_F32BE ,  SDL_AUDIO_S32LE ,   SDL_AUDIO_S16BE ,  SDL_AUDIO_S16LE ,  SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    {  SDL_AUDIO_F32LE ,   SDL_AUDIO_F32BE ,  SDL_AUDIO_S32LE ,   SDL_AUDIO_S32BE ,  SDL_AUDIO_S16LE ,   SDL_AUDIO_S16BE , SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    {  SDL_AUDIO_F32BE ,  SDL_AUDIO_F32LE ,   SDL_AUDIO_S32BE ,  SDL_AUDIO_S32LE ,   SDL_AUDIO_S16BE ,  SDL_AUDIO_S16LE ,  SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
}
{
    { SDL_AUDIO_U8, NATIVE(F32),  SWAPPED(F32), SDL_AUDIO_S8, NATIVE(S16),  SWAPPED(S16), NATIVE(S32),  SWAPPED(S32), SDL_AUDIO_UNKNOWN },
    { SDL_AUDIO_S8, NATIVE(F32),  SWAPPED(F32), SDL_AUDIO_U8, NATIVE(S16),  SWAPPED(S16), NATIVE(S32),  SWAPPED(S32), SDL_AUDIO_UNKNOWN },
    { NATIVE(S16),  NATIVE(F32),  SWAPPED(F32), SWAPPED(S16), NATIVE(S32),  SWAPPED(S32), SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    { SWAPPED(S16), NATIVE(F32),  SWAPPED(F32), NATIVE(S16),  SWAPPED(S32), NATIVE(S32),  SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    { NATIVE(S32),  NATIVE(F32),  SWAPPED(F32), SWAPPED(S32), NATIVE(S16),  SWAPPED(S16), SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    { SWAPPED(S32), NATIVE(F32),  SWAPPED(F32), NATIVE(S32),  SWAPPED(S16), NATIVE(S16),  SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    { NATIVE(F32),  SWAPPED(F32), NATIVE(S32),  SWAPPED(S32), NATIVE(S16),  SWAPPED(S16), SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
    { SWAPPED(F32), NATIVE(F32),  SWAPPED(S32), NATIVE(S32),  SWAPPED(S16), NATIVE(S16),  SDL_AUDIO_U8, SDL_AUDIO_S8, SDL_AUDIO_UNKNOWN },
};
Referenced by SDL_ClosestAudioFormats().
last_device_instance_id
SDL_AtomicInt last_device_instance_id static
Referenced by AssignAudioDeviceInstanceId(), and SDL_InitAudio().