SDL3: SDL_AudioDriverImpl Struct Reference
SDL_AudioDriverImpl Struct Reference
#include <SDL_sysaudio.h>
Data Fields
void(* CloseDevice)(SDL_AudioDevice *device)
void(* Deinitialize)(void)
void(* DeinitializeStart)(void)
void(* DetectDevices)(SDL_AudioDevice **default_playback, SDL_AudioDevice **default_recording)
void(* FlushRecording)(SDL_AudioDevice *device)
void(* FreeDeviceHandle)(SDL_AudioDevice *device)
Uint8 *(* GetDeviceBuf)(SDL_AudioDevice *device, int *buffer_size)
bool HasRecordingSupport
bool OnlyHasDefaultPlaybackDevice
bool OnlyHasDefaultRecordingDevice
bool(* OpenDevice)(SDL_AudioDevice *device)
bool(* PlayDevice)(SDL_AudioDevice *device, const Uint8 *buffer, int buflen)
bool ProvidesOwnCallbackThread
int(* RecordDevice)(SDL_AudioDevice *device, void *buffer, int buflen)
void(* ThreadDeinit)(SDL_AudioDevice *device)
void(* ThreadInit)(SDL_AudioDevice *device)
bool(* WaitDevice)(SDL_AudioDevice *device)
bool(* WaitRecordingDevice)(SDL_AudioDevice *device)
Field Documentation
CloseDevice
void(* SDL_AudioDriverImpl::CloseDevice) (SDL_AudioDevice *device)
Referenced by DUMMYAUDIO_Init(), and PS2AUDIO_Init().
Deinitialize
void(* SDL_AudioDriverImpl::Deinitialize) (void)
Referenced by PS2AUDIO_Init().
DeinitializeStart
void(* SDL_AudioDriverImpl::DeinitializeStart) (void)
DetectDevices
void(* SDL_AudioDriverImpl::DetectDevices) (SDL_AudioDevice **default_playback, SDL_AudioDevice **default_recording)
FlushRecording
void(* SDL_AudioDriverImpl::FlushRecording) (SDL_AudioDevice *device)
FreeDeviceHandle
void(* SDL_AudioDriverImpl::FreeDeviceHandle) (SDL_AudioDevice *device)
GetDeviceBuf
Uint8 *(* SDL_AudioDriverImpl::GetDeviceBuf) (SDL_AudioDevice *device, int *buffer_size)
Referenced by DUMMYAUDIO_Init(), and PS2AUDIO_Init().
HasRecordingSupport
bool SDL_AudioDriverImpl::HasRecordingSupport
Referenced by DUMMYAUDIO_Init().
OnlyHasDefaultPlaybackDevice
bool SDL_AudioDriverImpl::OnlyHasDefaultPlaybackDevice
Referenced by DUMMYAUDIO_Init(), and PS2AUDIO_Init().
OnlyHasDefaultRecordingDevice
bool SDL_AudioDriverImpl::OnlyHasDefaultRecordingDevice
Referenced by DUMMYAUDIO_Init().
OpenDevice
bool(* SDL_AudioDriverImpl::OpenDevice) (SDL_AudioDevice *device)
Referenced by DUMMYAUDIO_Init(), and PS2AUDIO_Init().
PlayDevice
bool(* SDL_AudioDriverImpl::PlayDevice) (SDL_AudioDevice *device, const Uint8 *buffer, int buflen)
Referenced by PS2AUDIO_Init().
ProvidesOwnCallbackThread
bool SDL_AudioDriverImpl::ProvidesOwnCallbackThread
Referenced by DUMMYAUDIO_Init().
RecordDevice
int(* SDL_AudioDriverImpl::RecordDevice) (SDL_AudioDevice *device, void *buffer, int buflen)
Referenced by DUMMYAUDIO_Init().
ThreadDeinit
void(* SDL_AudioDriverImpl::ThreadDeinit) (SDL_AudioDevice *device)
ThreadInit
void(* SDL_AudioDriverImpl::ThreadInit) (SDL_AudioDevice *device)
Referenced by PS2AUDIO_Init().
WaitDevice
bool(* SDL_AudioDriverImpl::WaitDevice) (SDL_AudioDevice *device)
Referenced by DUMMYAUDIO_Init(), and PS2AUDIO_Init().
WaitRecordingDevice
bool(* SDL_AudioDriverImpl::WaitRecordingDevice) (SDL_AudioDevice *device)
Referenced by DUMMYAUDIO_Init().
The documentation for this struct was generated from the following file:
SDL-main/src/audio/SDL_sysaudio.h