SDL3: SDL_uikitview Class Reference
SDL_uikitview Class Reference
#include <SDL_uikitview.h>
Inherits UIView, and <UIPointerInteractionDelegate>.
Instance Methods
(SDL_Window *) - getSDLWindow
(void) - indirectPointerHovering:
(instancetype) - initWithFrame:
(void) - pencilHovering:
(UIPointerRegion *) - pointerInteraction:regionForRequest:defaultRegion:
(UIPointerStyle *) - pointerInteraction:styleForRegion:
(void) - safeAreaInsetsDidChange
(void) - setSDLWindow:
(void) - touchesBegan:withEvent:
(void) - touchesEnded:withEvent:
(void) - touchesMoved:withEvent:
(CGPoint) - touchLocation:shouldNormalize:
Method Documentation
getSDLWindow
- (SDL_Window *) getSDLWindow
References getSDLWindow.
Referenced by getSDLWindow.
indirectPointerHovering:
- (void) indirectPointerHovering: (ios(13.4)) API_AVAILABLE
References void().
initWithFrame:
- (instancetype) initWithFrame: (CGRect) frame
pencilHovering:
- (void) pencilHovering: (ios(13.0)) API_AVAILABLE
References void().
pointerInteraction:regionForRequest:defaultRegion:
- (UIPointerRegion *) pointerInteraction: (UIPointerInteraction *) interaction regionForRequest: (UIPointerRegionRequest *) request defaultRegion: (ios(13.4)) API_AVAILABLE
pointerInteraction:styleForRegion:
- (UIPointerStyle *) pointerInteraction: (UIPointerInteraction *) interaction styleForRegion: (ios(13.4)) API_AVAILABLE
safeAreaInsetsDidChange
- (void) safeAreaInsetsDidChange
References safeAreaInsetsDidChange, and void().
Referenced by safeAreaInsetsDidChange.
setSDLWindow:
- (void) setSDLWindow: (SDL_Window *) window
References void().
touchesBegan:withEvent:
- (void) touchesBegan: (NSSet *) touches withEvent: (UIEvent *) event
References void().
touchesEnded:withEvent:
- (void) touchesEnded: (NSSet *) touches withEvent: (UIEvent *) event
References void().
touchesMoved:withEvent:
- (void) touchesMoved: (NSSet *) touches withEvent: (UIEvent *) event
References void().
touchLocation:shouldNormalize:
- (CGPoint) touchLocation: (UITouch *) touch shouldNormalize: (BOOL) normalize
The documentation for this class was generated from the following file:
SDL-main/src/video/uikit/SDL_uikitview.h