SDL3: SDL-main/include/SDL3/SDL_storage.h File Reference
SDL_storage.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_filesystem.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_StorageInterface
Typedefs
typedef struct SDL_Storage SDL_Storage
typedef struct SDL_StorageInterface SDL_StorageInterface
Functions
SDL_DECLSPEC bool SDLCALL SDL_CloseStorage (SDL_Storage *storage)
SDL_COMPILE_TIME_ASSERT (SDL_StorageInterface_SIZE,(sizeof(void *)==4 &&sizeof(SDL_StorageInterface)==48)||(sizeof(void *)==8 &&sizeof(SDL_StorageInterface)==96))
SDL_DECLSPEC bool SDLCALL SDL_CopyStorageFile (SDL_Storage *storage, const char *oldpath, const char *newpath)
SDL_DECLSPEC bool SDLCALL SDL_CreateStorageDirectory (SDL_Storage *storage, const char *path)
SDL_DECLSPEC bool SDLCALL SDL_EnumerateStorageDirectory (SDL_Storage *storage, const char *path, SDL_EnumerateDirectoryCallback callback, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_GetStorageFileSize (SDL_Storage *storage, const char *path, Uint64 *length)
SDL_DECLSPEC bool SDLCALL SDL_GetStoragePathInfo (SDL_Storage *storage, const char *path, SDL_PathInfo *info)
SDL_DECLSPEC Uint64 SDLCALL SDL_GetStorageSpaceRemaining (SDL_Storage *storage)
SDL_DECLSPEC char **SDLCALL SDL_GlobStorageDirectory (SDL_Storage *storage, const char *path, const char *pattern, SDL_GlobFlags flags, int *count)
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenFileStorage (const char *path)
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenStorage (const SDL_StorageInterface *iface, void *userdata)
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenTitleStorage (const char *override, SDL_PropertiesID props)
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenUserStorage (const char *org, const char *app, SDL_PropertiesID props)
SDL_DECLSPEC bool SDLCALL SDL_ReadStorageFile (SDL_Storage *storage, const char *path, void *destination, Uint64 length)
SDL_DECLSPEC bool SDLCALL SDL_RemoveStoragePath (SDL_Storage *storage, const char *path)
SDL_DECLSPEC bool SDLCALL SDL_RenameStoragePath (SDL_Storage *storage, const char *oldpath, const char *newpath)
SDL_DECLSPEC bool SDLCALL SDL_StorageReady (SDL_Storage *storage)
SDL_DECLSPEC bool SDLCALL SDL_WriteStorageFile (SDL_Storage *storage, const char *path, const void *source, Uint64 length)
Typedef Documentation
SDL_Storage
typedef struct SDL_Storage SDL_Storage
An abstract interface for filesystem access.
This is an opaque datatype. One can create this object using standard SDL functions like SDL_OpenTitleStorage or SDL_OpenUserStorage, etc, or create an object with a custom implementation using SDL_OpenStorage.
Since
This struct is available since SDL 3.2.0.
SDL_StorageInterface
typedef struct SDL_StorageInterface SDL_StorageInterface
CategoryStorage
The storage API is a high-level API designed to abstract away the portability issues that come up when using something lower-level (in SDL's case, this sits on top of the [Filesystem](CategoryFilesystem) and [IOStream](CategoryIOStream) subsystems). It is significantly more restrictive than a typical filesystem API, for a number of reasons:
What to Access: A common pitfall with existing filesystem APIs is the assumption that all storage is monolithic. However, many other platforms (game consoles in particular) are more strict about what type of filesystem is being accessed; for example, game content and user data are usually two separate storage devices with entirely different characteristics (and possibly different low-level APIs altogether!).
How to Access: Another common mistake is applications assuming that all storage is universally writeable - again, many platforms treat game content and user data as two separate storage devices, and only user data is writeable while game content is read-only.
When to Access: The most common portability issue with filesystem access is timing - you cannot always assume that the storage device is always accessible all of the time, nor can you assume that there are no limits to how long you have access to a particular device.
Consider the following example:
void ReadGameData(void)
{
    extern char** fileNames;
    extern size_t numFiles;
    for (size_t i = 0; i < numFiles; i += 1) {
        FILE *data = fopen(fileNames[i], "rwb");
        if (data == NULL) {
            // Something bad happened!
        } else {
            // A bunch of stuff happens here
            fclose(data);
        }
    }
}
void ReadSave(void)
{
    FILE *save = fopen("saves/save0.sav", "rb");
    if (save == NULL) {
        // Something bad happened!
    } else {
        // A bunch of stuff happens here
        fclose(save);
    }
}
void WriteSave(void)
{
    FILE *save = fopen("saves/save0.sav", "wb");
    if (save == NULL) {
        // Something bad happened!
    } else {
        // A bunch of stuff happens here
        fclose(save);
    }
}
Going over the bullet points again:
What to Access: This code accesses a global filesystem; game data and saves are all presumed to be in the current working directory (which may or may not be the game's installation folder!).
How to Access: This code assumes that content paths are writeable, and that save data is also writeable despite being in the same location as the game data.
When to Access: This code assumes that they can be called at any time, since the filesystem is always accessible and has no limits on how long the filesystem is being accessed.
Due to these assumptions, the filesystem code is not portable and will fail under these common scenarios:
The game is installed on a device that is read-only, both content loading and game saves will fail or crash outright
Game/User storage is not implicitly mounted, so no files will be found for either scenario when a platform requires explicitly mounting filesystems
Save data may not be safe since the I/O is not being flushed or validated, so an error occurring elsewhere in the program may result in missing/corrupted save data
When using SDL_Storage, these types of problems are virtually impossible to trip over:
void ReadGameData(void)
{
    extern char** fileNames;
    extern size_t numFiles;
    SDL_Storage *title = SDL_OpenTitleStorage(NULL, 0);
    if (title == NULL) {
        // Something bad happened!
    }
    while (!SDL_StorageReady(title)) {
        SDL_Delay(1);
    }
    for (size_t i = 0; i < numFiles; i += 1) {
        void* dst;
        Uint64 dstLen = 0;
        if (SDL_GetStorageFileSize(title, fileNames[i], &dstLen) && dstLen > 0) {
            dst = SDL_malloc(dstLen);
            if (SDL_ReadStorageFile(title, fileNames[i], dst, dstLen)) {
                // A bunch of stuff happens here
            } else {
                // Something bad happened!
            }
            SDL_free(dst);
        } else {
            // Something bad happened!
        }
    }
    SDL_CloseStorage(title);
}
void ReadSave(void)
{
    SDL_Storage *user = SDL_OpenUserStorage("libsdl", "Storage Example", 0);
    if (user == NULL) {
        // Something bad happened!
    }
    while (!SDL_StorageReady(user)) {
        SDL_Delay(1);
    }
    Uint64 saveLen = 0;
    if (SDL_GetStorageFileSize(user, "save0.sav", &saveLen) && saveLen > 0) {
        void* dst = SDL_malloc(saveLen);
        if (SDL_ReadStorageFile(user, "save0.sav", dst, saveLen)) {
            // A bunch of stuff happens here
        } else {
            // Something bad happened!
        }
        SDL_free(dst);
    } else {
        // Something bad happened!
    }
    SDL_CloseStorage(user);
}
void WriteSave(void)
{
    SDL_Storage *user = SDL_OpenUserStorage("libsdl", "Storage Example", 0);
    if (user == NULL) {
        // Something bad happened!
    }
    while (!SDL_StorageReady(user)) {
        SDL_Delay(1);
    }
    extern void *saveData; // A bunch of stuff happened here...
    extern Uint64 saveLen;
    if (!SDL_WriteStorageFile(user, "save0.sav", saveData, saveLen)) {
        // Something bad happened!
    }
    SDL_CloseStorage(user);
}
Note the improvements that SDL_Storage makes:
What to Access: This code explicitly reads from a title or user storage device based on the context of the function.
How to Access: This code explicitly uses either a read or write function based on the context of the function.
When to Access: This code explicitly opens the device when it needs to, and closes it when it is finished working with the filesystem.
The result is an application that is significantly more robust against the increasing demands of platforms and their filesystems!
A publicly available example of an SDL_Storage backend is the Steam Cloud backend - you can initialize Steamworks when starting the program, and then SDL will recognize that Steamworks is initialized and automatically use ISteamRemoteStorage when the application opens user storage. More importantly, when you open storage it knows to begin a "batch" of filesystem operations, and when you close storage it knows to end and flush the batch. This is used by Steam to support Dynamic Cloud Sync ; users can save data on one PC, put the device to sleep, and then continue playing on another PC (and vice versa) with the save data fully synchronized across all devices, allowing for a seamless experience without having to do full restarts of the program.
Notes on valid paths
All paths in the Storage API use Unix-style path separators ('/'). Using a different path separator will not work, even if the underlying platform would otherwise accept it. This is to keep code using the Storage API portable between platforms and Storage implementations and simplify app code.
Paths with relative directories ("." and "..") are forbidden by the Storage API.
All valid UTF-8 strings (discounting the NULL terminator character and the '/' path separator) are usable for filenames, however, an underlying Storage implementation may not support particularly strange sequences and refuse to create files with those names, etc. Function interface for SDL_Storage.
Apps that want to supply a custom implementation of SDL_Storage will fill in all the functions in this struct, and then pass it to SDL_OpenStorage to create a custom SDL_Storage object.
It is not usually necessary to do this; SDL provides standard implementations for many things you might expect to do with an SDL_Storage.
This structure should be initialized using SDL_INIT_INTERFACE()
Since
This struct is available since SDL 3.2.0.
See also
SDL_INIT_INTERFACE
Function Documentation
SDL_CloseStorage()
SDL_DECLSPEC bool SDLCALL SDL_CloseStorage (SDL_Storage * storage) extern
Closes and frees a storage container.
Parameters
storage a storage container to close.
Returns
true if the container was freed with no errors, false otherwise; call SDL_GetError() for more information. Even if the function returns an error, the container data will be freed; the error is only for informational purposes.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenFileStorage
SDL_OpenStorage
SDL_OpenTitleStorage
SDL_OpenUserStorage
{
    bool result = true;
    CHECK_STORAGE_MAGIC()
    if (storage->iface.close) {
        result = storage->iface.close(storage->userdata);
    }
    SDL_free(storage);
    return result;
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_free(), and SDL_Storage::userdata.
SDL_COMPILE_TIME_ASSERT()
SDL_COMPILE_TIME_ASSERT (SDL_StorageInterface_SIZE , (sizeof(void *)==4 &&sizeof(SDL_StorageInterface)==48)||(sizeof(void *)==8 &&sizeof(SDL_StorageInterface)==96))
SDL_CopyStorageFile()
SDL_DECLSPEC bool SDLCALL SDL_CopyStorageFile (SDL_Storage * storage, const char * oldpath, const char * newpath) extern
Copy a file in a writable storage container.
Parameters
storage a storage container.
oldpath the old path.
newpath the new path.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!oldpath) {
        return SDL_InvalidParamError("oldpath");
    } else if (!newpath) {
        return SDL_InvalidParamError("newpath");
    } else if (!ValidateStoragePath(oldpath)) {
        return false;
    } else if (!ValidateStoragePath(newpath)) {
        return false;
    } else if (!storage->iface.copy) {
        return SDL_Unsupported();
    }
    return storage->iface.copy(storage->userdata, oldpath, newpath);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_CreateStorageDirectory()
SDL_DECLSPEC bool SDLCALL SDL_CreateStorageDirectory (SDL_Storage * storage, const char * path) extern
Create a directory in a writable storage container.
Parameters
storage a storage container.
path the path of the directory to create.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.mkdir) {
        return SDL_Unsupported();
    }
    return storage->iface.mkdir(storage->userdata, path);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_EnumerateStorageDirectory()
SDL_DECLSPEC bool SDLCALL SDL_EnumerateStorageDirectory (SDL_Storage * storage, const char * path, SDL_EnumerateDirectoryCallback callback, void * userdata) extern
Enumerate a directory in a storage container through a callback function.
This function provides every directory entry through an app-provided callback, called once for each directory entry, until all results have been provided or the callback returns either SDL_ENUM_SUCCESS or SDL_ENUM_FAILURE.
This will return false if there was a system problem in general, or if a callback returns SDL_ENUM_FAILURE. A successful return means a callback returned SDL_ENUM_SUCCESS to halt enumeration, or all directory entries were enumerated.
If path is NULL, this is treated as a request to enumerate the root of the storage container's tree. An empty string also works for this.
Parameters
storage a storage container.
path the path of the directory to enumerate, or NULL for the root.
callback a function that is called for each entry in the directory.
userdata a pointer that is passed to callback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        path = "";  // we allow NULL to mean "root of the storage tree".
    }
    if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.enumerate) {
        return SDL_Unsupported();
    }
    return storage->iface.enumerate(storage->userdata, path, callback, userdata);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
Referenced by GlobStorageDirectoryEnumerator().
SDL_GetStorageFileSize()
SDL_DECLSPEC bool SDLCALL SDL_GetStorageFileSize (SDL_Storage * storage, const char * path, Uint64 * length) extern
Query the size of a file within a storage container.
Parameters
storage a storage container to query.
path the relative path of the file to query.
length a pointer to be filled with the file's length.
Returns
true if the file could be queried or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ReadStorageFile
SDL_StorageReady
{
    SDL_PathInfo info;
    if (SDL_GetStoragePathInfo(storage, path, &info)) {
        if (length) {
            *length = info.size;
        }
        return true;
    } else {
        if (length) {
            *length = 0;
        }
        return false;
    }
}
References SDL_GetStoragePathInfo(), and SDL_PathInfo::size.
SDL_GetStoragePathInfo()
SDL_DECLSPEC bool SDLCALL SDL_GetStoragePathInfo (SDL_Storage * storage, const char * path, SDL_PathInfo * info) extern
Get information about a filesystem path in a storage container.
Parameters
storage a storage container.
path the path to query.
info a pointer filled in with information about the path, or NULL to check for the existence of a file.
Returns
true on success or false if the file doesn't exist, or another failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    SDL_PathInfo dummy;
    if (!info) {
        info = &dummy;
    }
    SDL_zerop(info);
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.info) {
        return SDL_Unsupported();
    }
    return storage->iface.info(storage->userdata, path, info);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_StorageInterface::info, SDL_InvalidParamError, SDL_Unsupported, SDL_zerop, SDL_Storage::userdata, and ValidateStoragePath().
Referenced by GlobStorageDirectoryGetPathInfo(), and SDL_GetStorageFileSize().
SDL_GetStorageSpaceRemaining()
SDL_DECLSPEC Uint64 SDLCALL SDL_GetStorageSpaceRemaining (SDL_Storage * storage) extern
Queries the remaining space in a storage container.
Parameters
storage a storage container to query.
Returns
the amount of remaining space, in bytes.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
SDL_WriteStorageFile
{
    CHECK_STORAGE_MAGIC_RET(0)
    if (!storage->iface.space_remaining) {
        SDL_Unsupported();
        return 0;
    }
    return storage->iface.space_remaining(storage->userdata);
}
References CHECK_STORAGE_MAGIC_RET, SDL_Storage::iface, SDL_Unsupported, and SDL_Storage::userdata.
SDL_GlobStorageDirectory()
SDL_DECLSPEC char **SDLCALL SDL_GlobStorageDirectory (SDL_Storage * storage, const char * path, const char * pattern, SDL_GlobFlags flags, int * count) extern
Enumerate a directory tree, filtered by pattern, and return a list.
Files are filtered out if they don't match the string in pattern, which may contain wildcard characters * (match everything) and ? (match one character). If pattern is NULL, no filtering is done and all results are returned. Subdirectories are permitted, and are specified with a path separator of '/'. Wildcard characters * and ? never match a path separator.
flags may be set to SDL_GLOB_CASEINSENSITIVE to make the pattern matching case-insensitive.
The returned array is always NULL-terminated, for your iterating convenience, but if count is non-NULL, on return it will contain the number of items in the array, not counting the NULL terminator.
If path is NULL, this is treated as a request to enumerate the root of the storage container's tree. An empty string also works for this.
Parameters
storage a storage container.
path the path of the directory to enumerate, or NULL for the root.
pattern the pattern that files in the directory must match. Can be NULL.
flags SDL_GLOB_* bitflags that affect this search.
count on return, will be set to the number of items in the returned array. Can be NULL.
Returns
an array of strings on success or NULL on failure; call SDL_GetError() for more information. The caller should pass the returned pointer to SDL_free when done with it. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
It is safe to call this function from any thread, assuming the storage object is thread-safe.
Since
This function is available since SDL 3.2.0.
{
    CHECK_STORAGE_MAGIC_RET(NULL)
    if (!path) {
        path = "";  // we allow NULL to mean "root of the storage tree".
    }
    if (!ValidateStoragePath(path)) {
        return NULL;
    }
    return SDL_InternalGlobDirectory(path, pattern, flags, count, GlobStorageDirectoryEnumerator, GlobStorageDirectoryGetPathInfo, storage);
}
References CHECK_STORAGE_MAGIC_RET, count, GlobStorageDirectoryEnumerator(), GlobStorageDirectoryGetPathInfo(), NULL, SDL_InternalGlobDirectory(), and ValidateStoragePath().
SDL_OpenFileStorage()
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenFileStorage (const char * path) extern
Opens up a container for local filesystem storage.
This is provided for development and tools. Portable applications should use SDL_OpenTitleStorage() for access to game data and SDL_OpenUserStorage() for access to user data.
Parameters
path the base path prepended to all storage paths, or NULL for no base path.
Returns
a filesystem storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_GetStorageSpaceRemaining
SDL_OpenTitleStorage
SDL_OpenUserStorage
SDL_ReadStorageFile
SDL_WriteStorageFile
{
    return GENERIC_OpenFileStorage(path);
}
References GENERIC_OpenFileStorage().
SDL_OpenStorage()
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenStorage (const SDL_StorageInterface * iface, void * userdata) extern
Opens up a container using a client-provided storage interface.
Applications do not need to use this function unless they are providing their own SDL_Storage implementation. If you just need an SDL_Storage, you should use the built-in implementations in SDL, like SDL_OpenTitleStorage() or SDL_OpenUserStorage().
This function makes a copy of iface and the caller does not need to keep it around after this call.
Parameters
iface the interface that implements this storage, initialized using SDL_INIT_INTERFACE().
userdata the pointer that will be passed to the interface functions.
Returns
a storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_GetStorageSpaceRemaining
SDL_INIT_INTERFACE
SDL_ReadStorageFile
SDL_StorageReady
SDL_WriteStorageFile
{
    SDL_Storage *storage;
    if (!iface) {
        SDL_InvalidParamError("iface");
        return NULL;
    }
    if (iface->version < sizeof(*iface)) {
        // Update this to handle older versions of this interface
        SDL_SetError("Invalid interface, should be initialized with SDL_INIT_INTERFACE()");
        return NULL;
    }
    storage = (SDL_Storage *)SDL_calloc(1, sizeof(*storage));
    if (storage) {
        SDL_copyp(&storage->iface, iface);
        storage->userdata = userdata;
    }
    return storage;
}
References SDL_Storage::iface, NULL, SDL_calloc(), SDL_copyp, SDL_InvalidParamError, SDL_SetError(), SDL_Storage::userdata, and SDL_StorageInterface::version.
Referenced by GENERIC_OpenFileStorage(), GENERIC_Title_Create(), GENERIC_User_Create(), and STEAM_User_Create().
SDL_OpenTitleStorage()
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenTitleStorage (const char * override, SDL_PropertiesID props) extern
Opens up a read-only container for the application's filesystem.
By default, SDL_OpenTitleStorage uses the generic storage implementation. When the path override is not provided, the generic implementation will use the output of SDL_GetBasePath as the base path.
Parameters
override a path to override the backend's default title root.
props a property list that may contain backend-specific information.
Returns
a title storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_OpenUserStorage
SDL_ReadStorageFile
{
    SDL_Storage *storage = NULL;
    int i = 0;
    // Select the proper storage driver
    const char *driver_name = SDL_GetHint(SDL_HINT_STORAGE_TITLE_DRIVER);
    if (driver_name && *driver_name != 0) {
        const char *driver_attempt = driver_name;
        while (driver_attempt && *driver_attempt != 0 && !storage) {
            const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
            for (i = 0; titlebootstrap[i]; ++i) {
                if ((driver_attempt_len == SDL_strlen(titlebootstrap[i]->name)) &&
                    (SDL_strncasecmp(titlebootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                    storage = titlebootstrap[i]->create(override, props);
                    break;
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
    } else {
        for (i = 0; titlebootstrap[i]; ++i) {
            storage = titlebootstrap[i]->create(override, props);
            if (storage) {
                break;
            }
        }
    }
    if (storage) {
        SDL_DebugLogBackend("title_storage", titlebootstrap[i]->name);
    } else {
        if (driver_name) {
            SDL_SetError("%s not available", driver_name);
        } else {
            SDL_SetError("No available title storage driver");
        }
    }
    return storage;
}
References NULL, SDL_DebugLogBackend(), SDL_GetHint(), SDL_HINT_STORAGE_TITLE_DRIVER, SDL_SetError(), SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), and titlebootstrap.
SDL_OpenUserStorage()
SDL_DECLSPEC SDL_Storage *SDLCALL SDL_OpenUserStorage (const char * org, const char * app, SDL_PropertiesID props) extern
Opens up a container for a user's unique read/write filesystem.
While title storage can generally be kept open throughout runtime, user storage should only be opened when the client is ready to read/write files. This allows the backend to properly batch file operations and flush them when the container has been closed; ensuring safe and optimal save I/O.
Parameters
org the name of your organization.
app the name of your application.
props a property list that may contain backend-specific information.
Returns
a user storage container on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseStorage
SDL_GetStorageFileSize
SDL_GetStorageSpaceRemaining
SDL_OpenTitleStorage
SDL_ReadStorageFile
SDL_StorageReady
SDL_WriteStorageFile
{
    SDL_Storage *storage = NULL;
    int i = 0;
    // Select the proper storage driver
    const char *driver_name = SDL_GetHint(SDL_HINT_STORAGE_USER_DRIVER);
    if (driver_name && *driver_name != 0) {
        const char *driver_attempt = driver_name;
        while (driver_attempt && *driver_attempt != 0 && !storage) {
            const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
            size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt)
                                                                     : SDL_strlen(driver_attempt);
            for (i = 0; userbootstrap[i]; ++i) {
                if ((driver_attempt_len == SDL_strlen(userbootstrap[i]->name)) &&
                    (SDL_strncasecmp(userbootstrap[i]->name, driver_attempt, driver_attempt_len) == 0)) {
                    storage = userbootstrap[i]->create(org, app, props);
                    break;
                }
            }
            driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
        }
    } else {
        for (i = 0; userbootstrap[i]; ++i) {
            storage = userbootstrap[i]->create(org, app, props);
            if (storage) {
                break;
            }
        }
    }
    if (storage) {
        SDL_DebugLogBackend("user_storage", userbootstrap[i]->name);
    } else {
        if (driver_name) {
            SDL_SetError("%s not available", driver_name);
        } else {
            SDL_SetError("No available user storage driver");
        }
    }
    return storage;
}
References NULL, SDL_DebugLogBackend(), SDL_GetHint(), SDL_HINT_STORAGE_USER_DRIVER, SDL_SetError(), SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), and userbootstrap.
SDL_ReadStorageFile()
SDL_DECLSPEC bool SDLCALL SDL_ReadStorageFile (SDL_Storage * storage, const char * path, void * destination, Uint64 length) extern
Synchronously read a file from a storage container into a client-provided buffer.
The value of length must match the length of the file exactly; call SDL_GetStorageFileSize() to get this value. This behavior may be relaxed in a future release.
Parameters
storage a storage container to read from.
path the relative path of the file to read.
destination a client-provided buffer to read the file into.
length the length of the destination buffer.
Returns
true if the file was read or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetStorageFileSize
SDL_StorageReady
SDL_WriteStorageFile
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.read_file) {
        return SDL_Unsupported();
    }
    return storage->iface.read_file(storage->userdata, path, destination, length);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_RemoveStoragePath()
SDL_DECLSPEC bool SDLCALL SDL_RemoveStoragePath (SDL_Storage * storage, const char * path) extern
Remove a file or an empty directory in a writable storage container.
Parameters
storage a storage container.
path the path of the directory to enumerate.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.remove) {
        return SDL_Unsupported();
    }
    return storage->iface.remove(storage->userdata, path);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_RenameStoragePath()
SDL_DECLSPEC bool SDLCALL SDL_RenameStoragePath (SDL_Storage * storage, const char * oldpath, const char * newpath) extern
Rename a file or directory in a writable storage container.
Parameters
storage a storage container.
oldpath the old path.
newpath the new path.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!oldpath) {
        return SDL_InvalidParamError("oldpath");
    } else if (!newpath) {
        return SDL_InvalidParamError("newpath");
    } else if (!ValidateStoragePath(oldpath)) {
        return false;
    } else if (!ValidateStoragePath(newpath)) {
        return false;
    } else if (!storage->iface.rename) {
        return SDL_Unsupported();
    }
    return storage->iface.rename(storage->userdata, oldpath, newpath);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().
SDL_StorageReady()
SDL_DECLSPEC bool SDLCALL SDL_StorageReady (SDL_Storage * storage) extern
Checks if the storage container is ready to use.
This function should be called in regular intervals until it returns true - however, it is not recommended to spinwait on this call, as the backend may depend on a synchronous message loop. You might instead poll this in your game's main loop while processing events and drawing a loading screen.
Parameters
storage a storage container to query.
Returns
true if the container is ready, false otherwise.
Since
This function is available since SDL 3.2.0.
{
    CHECK_STORAGE_MAGIC_RET(false)
    if (storage->iface.ready) {
        return storage->iface.ready(storage->userdata);
    }
    return true;
}
References CHECK_STORAGE_MAGIC_RET, SDL_Storage::iface, and SDL_Storage::userdata.
SDL_WriteStorageFile()
SDL_DECLSPEC bool SDLCALL SDL_WriteStorageFile (SDL_Storage * storage, const char * path, const void * source, Uint64 length) extern
Synchronously write a file from client memory into a storage container.
Parameters
storage a storage container to write to.
path the relative path of the file to write.
source a client-provided buffer to write from.
length the length of the source buffer.
Returns
true if the file was written or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetStorageSpaceRemaining
SDL_ReadStorageFile
SDL_StorageReady
{
    CHECK_STORAGE_MAGIC()
    if (!path) {
        return SDL_InvalidParamError("path");
    } else if (!ValidateStoragePath(path)) {
        return false;
    } else if (!storage->iface.write_file) {
        return SDL_Unsupported();
    }
    return storage->iface.write_file(storage->userdata, path, source, length);
}
References CHECK_STORAGE_MAGIC, SDL_Storage::iface, SDL_InvalidParamError, SDL_Unsupported, SDL_Storage::userdata, and ValidateStoragePath().