SDL3: SDL-main/src/locale/n3ds/SDL_syslocale.c File Reference
SDL_syslocale.c File Reference
#include "../SDL_syslocale.h"
#include "SDL_internal.h"
#include <3ds.h>
Macros
#define BAD_LOCALE 255
Functions
static u8 GetLocaleIndex (void)
bool SDL_SYS_GetPreferredLocales (char *buf, size_t buflen)
Macro Definition Documentation
BAD_LOCALE
#define BAD_LOCALE 255
Referenced by GetLocaleIndex(), and SDL_SYS_GetPreferredLocales().
Function Documentation
GetLocaleIndex()
u8 GetLocaleIndex (void) static
{
    u8 current_locale;
    Result result;
    if (R_FAILED(cfguInit())) {
        return BAD_LOCALE;
    }
    result = CFGU_GetSystemLanguage(&current_locale);
    cfguExit();
    return R_SUCCEEDED(result) ? current_locale : BAD_LOCALE;
}
References BAD_LOCALE.
Referenced by SDL_SYS_GetPreferredLocales().
SDL_SYS_GetPreferredLocales()
bool SDL_SYS_GetPreferredLocales (char * buf, size_t buflen)
{
    // The 3DS only supports these 12 languages, only one can be active at a time
    static const char AVAILABLE_LOCALES[][6] = { "ja_JP", "en_US", "fr_FR", "de_DE",
                                                 "it_IT", "es_ES", "zh_CN", "ko_KR",
                                                 "nl_NL", "pt_PT", "ru_RU", "zh_TW" };
    u8 current_locale = GetLocaleIndex();
    if (current_locale != BAD_LOCALE) {
        SDL_strlcpy(buf, AVAILABLE_LOCALES[current_locale], buflen);
    }
    return true;
}
References BAD_LOCALE, GetLocaleIndex(), and SDL_strlcpy().