SDL3: SDL-main/src/storage/SDL_sysstorage.h File Reference
SDL_sysstorage.h File Reference
#include "SDL_internal.h"
Data Structures
struct TitleStorageBootStrap
struct UserStorageBootStrap
Typedefs
typedef struct TitleStorageBootStrap TitleStorageBootStrap
typedef struct UserStorageBootStrap UserStorageBootStrap
Functions
SDL_Storage * GENERIC_OpenFileStorage (const char *path)
Variables
TitleStorageBootStrap GENERIC_titlebootstrap
UserStorageBootStrap GENERIC_userbootstrap
UserStorageBootStrap PRIVATE_userbootstrap
UserStorageBootStrap STEAM_userbootstrap
Typedef Documentation
TitleStorageBootStrap
typedef struct TitleStorageBootStrap TitleStorageBootStrap
UserStorageBootStrap
typedef struct UserStorageBootStrap UserStorageBootStrap
Function Documentation
GENERIC_OpenFileStorage()
SDL_Storage * GENERIC_OpenFileStorage (const char * path) extern
{
    SDL_Storage *result;
    size_t len = 0;
    char *basepath = NULL;
    if (path) {
        len += SDL_strlen(path);
    }
    if (len > 0) {
        #ifdef SDL_PLATFORM_WINDOWS
        const bool appended_separator = (path[len-1] == '/') || (path[len-1] == '\\');
        #else
        const bool appended_separator = (path[len-1] == '/');
        #endif
        if (appended_separator) {
            basepath = SDL_strdup(path);
            if (!basepath) {
                return NULL;
            }
        } else {
            if (SDL_asprintf(&basepath, "%s/", path) < 0) {
                return NULL;
            }
        }
    }
    result = SDL_OpenStorage(&GENERIC_file_iface, basepath);
    if (result == NULL) {
        SDL_free(basepath);
    }
    return result;
}
References GENERIC_file_iface, NULL, SDL_asprintf(), SDL_free(), SDL_OpenStorage(), SDL_strdup(), and SDL_strlen().
Referenced by SDL_OpenFileStorage().
Variable Documentation
GENERIC_titlebootstrap
TitleStorageBootStrap GENERIC_titlebootstrap extern
{
    "generic",
    "SDL generic title storage driver",
    GENERIC_Title_Create
};
GENERIC_userbootstrap
UserStorageBootStrap GENERIC_userbootstrap extern
{
    "generic",
    "SDL generic user storage driver",
    GENERIC_User_Create
};
PRIVATE_userbootstrap
UserStorageBootStrap PRIVATE_userbootstrap extern
STEAM_userbootstrap
UserStorageBootStrap STEAM_userbootstrap extern
{
    "steam",
    "SDL Steam user storage driver",
    STEAM_User_Create
};