SDL3: SDL-main/include/SDL3/SDL_events.h File Reference
SDL_events.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_audio.h>
#include <SDL3/SDL_camera.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_gamepad.h>
#include <SDL3/SDL_joystick.h>
#include <SDL3/SDL_keyboard.h>
#include <SDL3/SDL_keycode.h>
#include <SDL3/SDL_mouse.h>
#include <SDL3/SDL_pen.h>
#include <SDL3/SDL_power.h>
#include <SDL3/SDL_sensor.h>
#include <SDL3/SDL_scancode.h>
#include <SDL3/SDL_touch.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_AudioDeviceEvent
struct SDL_CameraDeviceEvent
struct SDL_ClipboardEvent
struct SDL_CommonEvent
struct SDL_DisplayEvent
struct SDL_DropEvent
union SDL_Event
struct SDL_GamepadAxisEvent
struct SDL_GamepadButtonEvent
struct SDL_GamepadDeviceEvent
struct SDL_GamepadSensorEvent
struct SDL_GamepadTouchpadEvent
struct SDL_JoyAxisEvent
struct SDL_JoyBallEvent
struct SDL_JoyBatteryEvent
struct SDL_JoyButtonEvent
struct SDL_JoyDeviceEvent
struct SDL_JoyHatEvent
struct SDL_KeyboardDeviceEvent
struct SDL_KeyboardEvent
struct SDL_MouseButtonEvent
struct SDL_MouseDeviceEvent
struct SDL_MouseMotionEvent
struct SDL_MouseWheelEvent
struct SDL_PenAxisEvent
struct SDL_PenButtonEvent
struct SDL_PenMotionEvent
struct SDL_PenProximityEvent
struct SDL_PenTouchEvent
struct SDL_QuitEvent
struct SDL_RenderEvent
struct SDL_SensorEvent
struct SDL_TextEditingCandidatesEvent
struct SDL_TextEditingEvent
struct SDL_TextInputEvent
struct SDL_TouchFingerEvent
struct SDL_UserEvent
struct SDL_WindowEvent
Typedefs
typedef struct SDL_AudioDeviceEvent SDL_AudioDeviceEvent
typedef struct SDL_CameraDeviceEvent SDL_CameraDeviceEvent
typedef struct SDL_ClipboardEvent SDL_ClipboardEvent
typedef struct SDL_CommonEvent SDL_CommonEvent
typedef struct SDL_DisplayEvent SDL_DisplayEvent
typedef struct SDL_DropEvent SDL_DropEvent
typedef union SDL_Event SDL_Event
typedef enum SDL_EventAction SDL_EventAction
typedef bool(SDLCALL * SDL_EventFilter) (void *userdata, SDL_Event *event)
typedef enum SDL_EventType SDL_EventType
typedef struct SDL_GamepadAxisEvent SDL_GamepadAxisEvent
typedef struct SDL_GamepadButtonEvent SDL_GamepadButtonEvent
typedef struct SDL_GamepadDeviceEvent SDL_GamepadDeviceEvent
typedef struct SDL_GamepadSensorEvent SDL_GamepadSensorEvent
typedef struct SDL_GamepadTouchpadEvent SDL_GamepadTouchpadEvent
typedef struct SDL_JoyAxisEvent SDL_JoyAxisEvent
typedef struct SDL_JoyBallEvent SDL_JoyBallEvent
typedef struct SDL_JoyBatteryEvent SDL_JoyBatteryEvent
typedef struct SDL_JoyButtonEvent SDL_JoyButtonEvent
typedef struct SDL_JoyDeviceEvent SDL_JoyDeviceEvent
typedef struct SDL_JoyHatEvent SDL_JoyHatEvent
typedef struct SDL_KeyboardDeviceEvent SDL_KeyboardDeviceEvent
typedef struct SDL_KeyboardEvent SDL_KeyboardEvent
typedef struct SDL_MouseButtonEvent SDL_MouseButtonEvent
typedef struct SDL_MouseDeviceEvent SDL_MouseDeviceEvent
typedef struct SDL_MouseMotionEvent SDL_MouseMotionEvent
typedef struct SDL_MouseWheelEvent SDL_MouseWheelEvent
typedef struct SDL_PenAxisEvent SDL_PenAxisEvent
typedef struct SDL_PenButtonEvent SDL_PenButtonEvent
typedef struct SDL_PenMotionEvent SDL_PenMotionEvent
typedef struct SDL_PenProximityEvent SDL_PenProximityEvent
typedef struct SDL_PenTouchEvent SDL_PenTouchEvent
typedef struct SDL_QuitEvent SDL_QuitEvent
typedef struct SDL_RenderEvent SDL_RenderEvent
typedef struct SDL_SensorEvent SDL_SensorEvent
typedef struct SDL_TextEditingCandidatesEvent SDL_TextEditingCandidatesEvent
typedef struct SDL_TextEditingEvent SDL_TextEditingEvent
typedef struct SDL_TextInputEvent SDL_TextInputEvent
typedef struct SDL_TouchFingerEvent SDL_TouchFingerEvent
typedef struct SDL_UserEvent SDL_UserEvent
typedef struct SDL_WindowEvent SDL_WindowEvent
Enumerations
enum SDL_EventAction { SDL_ADDEVENT , SDL_PEEKEVENT , SDL_GETEVENT }
enum SDL_EventType {
SDL_EVENT_FIRST = 0 , SDL_EVENT_QUIT = 0x100 , SDL_EVENT_TERMINATING , SDL_EVENT_LOW_MEMORY ,
SDL_EVENT_WILL_ENTER_BACKGROUND , SDL_EVENT_DID_ENTER_BACKGROUND , SDL_EVENT_WILL_ENTER_FOREGROUND , SDL_EVENT_DID_ENTER_FOREGROUND ,
SDL_EVENT_LOCALE_CHANGED , SDL_EVENT_SYSTEM_THEME_CHANGED , SDL_EVENT_DISPLAY_ORIENTATION = 0x151 , SDL_EVENT_DISPLAY_ADDED ,
SDL_EVENT_DISPLAY_REMOVED , SDL_EVENT_DISPLAY_MOVED , SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED , SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED ,
SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED , SDL_EVENT_DISPLAY_FIRST = SDL_EVENT_DISPLAY_ORIENTATION , SDL_EVENT_DISPLAY_LAST = SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED , SDL_EVENT_WINDOW_SHOWN = 0x202 ,
SDL_EVENT_WINDOW_HIDDEN , SDL_EVENT_WINDOW_EXPOSED , SDL_EVENT_WINDOW_MOVED , SDL_EVENT_WINDOW_RESIZED ,
SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED , SDL_EVENT_WINDOW_METAL_VIEW_RESIZED , SDL_EVENT_WINDOW_MINIMIZED , SDL_EVENT_WINDOW_MAXIMIZED ,
SDL_EVENT_WINDOW_RESTORED , SDL_EVENT_WINDOW_MOUSE_ENTER , SDL_EVENT_WINDOW_MOUSE_LEAVE , SDL_EVENT_WINDOW_FOCUS_GAINED ,
SDL_EVENT_WINDOW_FOCUS_LOST , SDL_EVENT_WINDOW_CLOSE_REQUESTED , SDL_EVENT_WINDOW_HIT_TEST , SDL_EVENT_WINDOW_ICCPROF_CHANGED ,
SDL_EVENT_WINDOW_DISPLAY_CHANGED , SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED , SDL_EVENT_WINDOW_SAFE_AREA_CHANGED , SDL_EVENT_WINDOW_OCCLUDED ,
SDL_EVENT_WINDOW_ENTER_FULLSCREEN , SDL_EVENT_WINDOW_LEAVE_FULLSCREEN , SDL_EVENT_WINDOW_DESTROYED , SDL_EVENT_WINDOW_HDR_STATE_CHANGED ,
SDL_EVENT_WINDOW_FIRST = SDL_EVENT_WINDOW_SHOWN , SDL_EVENT_WINDOW_LAST = SDL_EVENT_WINDOW_HDR_STATE_CHANGED , SDL_EVENT_KEY_DOWN = 0x300 , SDL_EVENT_KEY_UP ,
SDL_EVENT_TEXT_EDITING , SDL_EVENT_TEXT_INPUT , SDL_EVENT_KEYMAP_CHANGED , SDL_EVENT_KEYBOARD_ADDED ,
SDL_EVENT_KEYBOARD_REMOVED , SDL_EVENT_TEXT_EDITING_CANDIDATES , SDL_EVENT_MOUSE_MOTION = 0x400 , SDL_EVENT_MOUSE_BUTTON_DOWN ,
SDL_EVENT_MOUSE_BUTTON_UP , SDL_EVENT_MOUSE_WHEEL , SDL_EVENT_MOUSE_ADDED , SDL_EVENT_MOUSE_REMOVED ,
SDL_EVENT_JOYSTICK_AXIS_MOTION = 0x600 , SDL_EVENT_JOYSTICK_BALL_MOTION , SDL_EVENT_JOYSTICK_HAT_MOTION , SDL_EVENT_JOYSTICK_BUTTON_DOWN ,
SDL_EVENT_JOYSTICK_BUTTON_UP , SDL_EVENT_JOYSTICK_ADDED , SDL_EVENT_JOYSTICK_REMOVED , SDL_EVENT_JOYSTICK_BATTERY_UPDATED ,
SDL_EVENT_JOYSTICK_UPDATE_COMPLETE , SDL_EVENT_GAMEPAD_AXIS_MOTION = 0x650 , SDL_EVENT_GAMEPAD_BUTTON_DOWN , SDL_EVENT_GAMEPAD_BUTTON_UP ,
SDL_EVENT_GAMEPAD_ADDED , SDL_EVENT_GAMEPAD_REMOVED , SDL_EVENT_GAMEPAD_REMAPPED , SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN ,
SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION , SDL_EVENT_GAMEPAD_TOUCHPAD_UP , SDL_EVENT_GAMEPAD_SENSOR_UPDATE , SDL_EVENT_GAMEPAD_UPDATE_COMPLETE ,
SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED , SDL_EVENT_FINGER_DOWN = 0x700 , SDL_EVENT_FINGER_UP , SDL_EVENT_FINGER_MOTION ,
SDL_EVENT_FINGER_CANCELED , SDL_EVENT_CLIPBOARD_UPDATE = 0x900 , SDL_EVENT_DROP_FILE = 0x1000 , SDL_EVENT_DROP_TEXT ,
SDL_EVENT_DROP_BEGIN , SDL_EVENT_DROP_COMPLETE , SDL_EVENT_DROP_POSITION , SDL_EVENT_AUDIO_DEVICE_ADDED = 0x1100 ,
SDL_EVENT_AUDIO_DEVICE_REMOVED , SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED , SDL_EVENT_SENSOR_UPDATE = 0x1200 , SDL_EVENT_PEN_PROXIMITY_IN = 0x1300 ,
SDL_EVENT_PEN_PROXIMITY_OUT , SDL_EVENT_PEN_DOWN , SDL_EVENT_PEN_UP , SDL_EVENT_PEN_BUTTON_DOWN ,
SDL_EVENT_PEN_BUTTON_UP , SDL_EVENT_PEN_MOTION , SDL_EVENT_PEN_AXIS , SDL_EVENT_CAMERA_DEVICE_ADDED = 0x1400 ,
SDL_EVENT_CAMERA_DEVICE_REMOVED , SDL_EVENT_CAMERA_DEVICE_APPROVED , SDL_EVENT_CAMERA_DEVICE_DENIED , SDL_EVENT_RENDER_TARGETS_RESET = 0x2000 ,
SDL_EVENT_RENDER_DEVICE_RESET , SDL_EVENT_RENDER_DEVICE_LOST , SDL_EVENT_PRIVATE0 = 0x4000 , SDL_EVENT_PRIVATE1 ,
SDL_EVENT_PRIVATE2 , SDL_EVENT_PRIVATE3 , SDL_EVENT_POLL_SENTINEL = 0x7F00 , SDL_EVENT_USER = 0x8000 ,
SDL_EVENT_LAST = 0xFFFF , SDL_EVENT_ENUM_PADDING = 0x7FFFFFFF
}
Functions
SDL_DECLSPEC bool SDLCALL SDL_AddEventWatch (SDL_EventFilter filter, void *userdata)
SDL_COMPILE_TIME_ASSERT (SDL_Event, sizeof(SDL_Event)==sizeof(((SDL_Event *) NULL) ->padding))
SDL_DECLSPEC bool SDLCALL SDL_EventEnabled (Uint32 type)
SDL_DECLSPEC void SDLCALL SDL_FilterEvents (SDL_EventFilter filter, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_FlushEvent (Uint32 type)
SDL_DECLSPEC void SDLCALL SDL_FlushEvents (Uint32 minType, Uint32 maxType)
SDL_DECLSPEC int SDLCALL SDL_GetEventDescription (const SDL_Event *event, char *buf, int buflen)
SDL_DECLSPEC bool SDLCALL SDL_GetEventFilter (SDL_EventFilter *filter, void **userdata)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetWindowFromEvent (const SDL_Event *event)
SDL_DECLSPEC bool SDLCALL SDL_HasEvent (Uint32 type)
SDL_DECLSPEC bool SDLCALL SDL_HasEvents (Uint32 minType, Uint32 maxType)
SDL_DECLSPEC int SDLCALL SDL_PeepEvents (SDL_Event *events, int numevents, SDL_EventAction action, Uint32 minType, Uint32 maxType)
SDL_DECLSPEC bool SDLCALL SDL_PollEvent (SDL_Event *event)
SDL_DECLSPEC void SDLCALL SDL_PumpEvents (void)
SDL_DECLSPEC bool SDLCALL SDL_PushEvent (SDL_Event *event)
SDL_DECLSPEC Uint32 SDLCALL SDL_RegisterEvents (int numevents)
SDL_DECLSPEC void SDLCALL SDL_RemoveEventWatch (SDL_EventFilter filter, void *userdata)
SDL_DECLSPEC void SDLCALL SDL_SetEventEnabled (Uint32 type, bool enabled)
SDL_DECLSPEC void SDLCALL SDL_SetEventFilter (SDL_EventFilter filter, void *userdata)
SDL_DECLSPEC bool SDLCALL SDL_WaitEvent (SDL_Event *event)
SDL_DECLSPEC bool SDLCALL SDL_WaitEventTimeout (SDL_Event *event, Sint32 timeoutMS)
Typedef Documentation
SDL_AudioDeviceEvent
typedef struct SDL_AudioDeviceEvent SDL_AudioDeviceEvent
Audio device event structure (event.adevice.*)
Since
This struct is available since SDL 3.2.0.
SDL_CameraDeviceEvent
typedef struct SDL_CameraDeviceEvent SDL_CameraDeviceEvent
Camera device event structure (event.cdevice.*)
Since
This struct is available since SDL 3.2.0.
SDL_ClipboardEvent
typedef struct SDL_ClipboardEvent SDL_ClipboardEvent
An event triggered when the clipboard contents have changed (event.clipboard.*)
Since
This struct is available since SDL 3.2.0.
SDL_CommonEvent
typedef struct SDL_CommonEvent SDL_CommonEvent
Fields shared by every event
Since
This struct is available since SDL 3.2.0.
SDL_DisplayEvent
typedef struct SDL_DisplayEvent SDL_DisplayEvent
Display state change event data (event.display.*)
Since
This struct is available since SDL 3.2.0.
SDL_DropEvent
typedef struct SDL_DropEvent SDL_DropEvent
An event used to drop text or request a file open by the system (event.drop.*)
Since
This struct is available since SDL 3.2.0.
SDL_Event
typedef union SDL_Event SDL_Event
The structure for all events in SDL.
The SDL_Event structure is the core of all event handling in SDL. SDL_Event is a union of all event structures used in SDL.
Since
This struct is available since SDL 3.2.0.
SDL_EventAction
typedef enum SDL_EventAction SDL_EventAction
The type of action to request from SDL_PeepEvents().
Since
This enum is available since SDL 3.2.0.
SDL_EventFilter
typedef bool(SDLCALL * SDL_EventFilter) (void *userdata, SDL_Event *event)
A function pointer used for callbacks that watch the event queue.
Parameters
userdata what was passed as userdata to SDL_SetEventFilter() or SDL_AddEventWatch, etc.
event the event that triggered the callback.
Returns
true to permit event to be added to the queue, and false to disallow it. When used with SDL_AddEventWatch, the return value is ignored.
Thread Safety
SDL may call this callback at any time from any thread; the application is responsible for locking resources the callback touches that need to be protected.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_SetEventFilter
SDL_AddEventWatch
SDL_EventType
typedef enum SDL_EventType SDL_EventType
CategoryEvents
Event queue management.
It's extremely common–often required–that an app deal with SDL's event queue. Almost all useful information about interactions with the real world flow through here: the user interacting with the computer and app, hardware coming and going, the system changing in some way, etc.
An app generally takes a moment, perhaps at the start of a new frame, to examine any events that have occured since the last time and process or ignore them. This is generally done by calling SDL_PollEvent() in a loop until it returns false (or, if using the main callbacks, events are provided one at a time in calls to SDL_AppEvent() before the next call to SDL_AppIterate(); in this scenario, the app does not call SDL_PollEvent() at all).
There is other forms of control, too: SDL_PeepEvents() has more functionality at the cost of more complexity, and SDL_WaitEvent() can block the process until something interesting happens, which might be beneficial for certain types of programs on low-power hardware. One may also call SDL_AddEventWatch() to set a callback when new events arrive.
The app is free to generate their own events, too: SDL_PushEvent allows the app to put events onto the queue for later retrieval; SDL_RegisterEvents can guarantee that these events have a type that isn't in use by other parts of the system. The types of events that can be delivered.
Since
This enum is available since SDL 3.2.0.
SDL_GamepadAxisEvent
typedef struct SDL_GamepadAxisEvent SDL_GamepadAxisEvent
Gamepad axis motion event structure (event.gaxis.*)
Since
This struct is available since SDL 3.2.0.
SDL_GamepadButtonEvent
typedef struct SDL_GamepadButtonEvent SDL_GamepadButtonEvent
Gamepad button event structure (event.gbutton.*)
Since
This struct is available since SDL 3.2.0.
SDL_GamepadDeviceEvent
typedef struct SDL_GamepadDeviceEvent SDL_GamepadDeviceEvent
Gamepad device event structure (event.gdevice.*)
Joysticks that are supported gamepads receive both an SDL_JoyDeviceEvent and an SDL_GamepadDeviceEvent.
SDL will send GAMEPAD_ADDED events for joysticks that are already plugged in during SDL_Init() and are recognized as gamepads. It will also send events for joysticks that get gamepad mappings at runtime.
Since
This struct is available since SDL 3.2.0.
See also
SDL_JoyDeviceEvent
SDL_GamepadSensorEvent
typedef struct SDL_GamepadSensorEvent SDL_GamepadSensorEvent
Gamepad sensor event structure (event.gsensor.*)
Since
This struct is available since SDL 3.2.0.
SDL_GamepadTouchpadEvent
typedef struct SDL_GamepadTouchpadEvent SDL_GamepadTouchpadEvent
Gamepad touchpad event structure (event.gtouchpad.*)
Since
This struct is available since SDL 3.2.0.
SDL_JoyAxisEvent
typedef struct SDL_JoyAxisEvent SDL_JoyAxisEvent
Joystick axis motion event structure (event.jaxis.*)
Since
This struct is available since SDL 3.2.0.
SDL_JoyBallEvent
typedef struct SDL_JoyBallEvent SDL_JoyBallEvent
Joystick trackball motion event structure (event.jball.*)
Since
This struct is available since SDL 3.2.0.
SDL_JoyBatteryEvent
typedef struct SDL_JoyBatteryEvent SDL_JoyBatteryEvent
Joystick battery level change event structure (event.jbattery.*)
Since
This struct is available since SDL 3.2.0.
SDL_JoyButtonEvent
typedef struct SDL_JoyButtonEvent SDL_JoyButtonEvent
Joystick button event structure (event.jbutton.*)
Since
This struct is available since SDL 3.2.0.
SDL_JoyDeviceEvent
typedef struct SDL_JoyDeviceEvent SDL_JoyDeviceEvent
Joystick device event structure (event.jdevice.*)
SDL will send JOYSTICK_ADDED events for devices that are already plugged in during SDL_Init.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GamepadDeviceEvent
SDL_JoyHatEvent
typedef struct SDL_JoyHatEvent SDL_JoyHatEvent
Joystick hat position change event structure (event.jhat.*)
Since
This struct is available since SDL 3.2.0.
SDL_KeyboardDeviceEvent
typedef struct SDL_KeyboardDeviceEvent SDL_KeyboardDeviceEvent
Keyboard device event structure (event.kdevice.*)
Since
This struct is available since SDL 3.2.0.
SDL_KeyboardEvent
typedef struct SDL_KeyboardEvent SDL_KeyboardEvent
Keyboard button event structure (event.key.*)
The key is the base SDL_Keycode generated by pressing the scancode using the current keyboard layout, applying any options specified in SDL_HINT_KEYCODE_OPTIONS. You can get the SDL_Keycode corresponding to the event scancode and modifiers directly from the keyboard layout, bypassing SDL_HINT_KEYCODE_OPTIONS, by calling SDL_GetKeyFromScancode().
Since
This struct is available since SDL 3.2.0.
See also
SDL_GetKeyFromScancode
SDL_HINT_KEYCODE_OPTIONS
SDL_MouseButtonEvent
typedef struct SDL_MouseButtonEvent SDL_MouseButtonEvent
Mouse button event structure (event.button.*)
Since
This struct is available since SDL 3.2.0.
SDL_MouseDeviceEvent
typedef struct SDL_MouseDeviceEvent SDL_MouseDeviceEvent
Mouse device event structure (event.mdevice.*)
Since
This struct is available since SDL 3.2.0.
SDL_MouseMotionEvent
typedef struct SDL_MouseMotionEvent SDL_MouseMotionEvent
Mouse motion event structure (event.motion.*)
Since
This struct is available since SDL 3.2.0.
SDL_MouseWheelEvent
typedef struct SDL_MouseWheelEvent SDL_MouseWheelEvent
Mouse wheel event structure (event.wheel.*)
Since
This struct is available since SDL 3.2.0.
SDL_PenAxisEvent
typedef struct SDL_PenAxisEvent SDL_PenAxisEvent
Pressure-sensitive pen pressure / angle event structure (event.paxis.*)
You might get some of these events even if the pen isn't touching the tablet.
Since
This struct is available since SDL 3.2.0.
SDL_PenButtonEvent
typedef struct SDL_PenButtonEvent SDL_PenButtonEvent
Pressure-sensitive pen button event structure (event.pbutton.*)
This is for buttons on the pen itself that the user might click. The pen itself pressing down to draw triggers a SDL_EVENT_PEN_DOWN event instead.
Since
This struct is available since SDL 3.2.0.
SDL_PenMotionEvent
typedef struct SDL_PenMotionEvent SDL_PenMotionEvent
Pressure-sensitive pen motion event structure (event.pmotion.*)
Depending on the hardware, you may get motion events when the pen is not touching a tablet, for tracking a pen even when it isn't drawing. You should listen for SDL_EVENT_PEN_DOWN and SDL_EVENT_PEN_UP events, or check pen_state & SDL_PEN_INPUT_DOWN to decide if a pen is "drawing" when dealing with pen motion.
Since
This struct is available since SDL 3.2.0.
SDL_PenProximityEvent
typedef struct SDL_PenProximityEvent SDL_PenProximityEvent
Pressure-sensitive pen proximity event structure (event.pproximity.*)
When a pen becomes visible to the system (it is close enough to a tablet, etc), SDL will send an SDL_EVENT_PEN_PROXIMITY_IN event with the new pen's ID. This ID is valid until the pen leaves proximity again (has been removed from the tablet's area, the tablet has been unplugged, etc). If the same pen reenters proximity again, it will be given a new ID.
Note that "proximity" means "close enough for the tablet to know the tool is there." The pen touching and lifting off from the tablet while not leaving the area are handled by SDL_EVENT_PEN_DOWN and SDL_EVENT_PEN_UP.
Since
This struct is available since SDL 3.2.0.
SDL_PenTouchEvent
typedef struct SDL_PenTouchEvent SDL_PenTouchEvent
Pressure-sensitive pen touched event structure (event.ptouch.*)
These events come when a pen touches a surface (a tablet, etc), or lifts off from one.
Since
This struct is available since SDL 3.2.0.
SDL_QuitEvent
typedef struct SDL_QuitEvent SDL_QuitEvent
The "quit requested" event
Since
This struct is available since SDL 3.2.0.
SDL_RenderEvent
typedef struct SDL_RenderEvent SDL_RenderEvent
Renderer event structure (event.render.*)
Since
This struct is available since SDL 3.2.0.
SDL_SensorEvent
typedef struct SDL_SensorEvent SDL_SensorEvent
Sensor event structure (event.sensor.*)
Since
This struct is available since SDL 3.2.0.
SDL_TextEditingCandidatesEvent
typedef struct SDL_TextEditingCandidatesEvent SDL_TextEditingCandidatesEvent
Keyboard IME candidates event structure (event.edit_candidates.*)
Since
This struct is available since SDL 3.2.0.
SDL_TextEditingEvent
typedef struct SDL_TextEditingEvent SDL_TextEditingEvent
Keyboard text editing event structure (event.edit.*)
The start cursor is the position, in UTF-8 characters, where new typing will be inserted into the editing text. The length is the number of UTF-8 characters that will be replaced by new typing.
Since
This struct is available since SDL 3.2.0.
SDL_TextInputEvent
typedef struct SDL_TextInputEvent SDL_TextInputEvent
Keyboard text input event structure (event.text.*)
This event will never be delivered unless text input is enabled by calling SDL_StartTextInput(). Text input is disabled by default!
Since
This struct is available since SDL 3.2.0.
See also
SDL_StartTextInput
SDL_StopTextInput
SDL_TouchFingerEvent
typedef struct SDL_TouchFingerEvent SDL_TouchFingerEvent
Touch finger event structure (event.tfinger.*)
Coordinates in this event are normalized. x and y are normalized to a range between 0.0f and 1.0f, relative to the window, so (0,0) is the top left and (1,1) is the bottom right. Delta coordinates dx and dy are normalized in the ranges of -1.0f (traversed all the way from the bottom or right to all the way up or left) to 1.0f (traversed all the way from the top or left to all the way down or right).
Note that while the coordinates are normalized, they are not clamped, which means in some circumstances you can get a value outside of this range. For example, a renderer using logical presentation might give a negative value when the touch is in the letterboxing. Some platforms might report a touch outside of the window, which will also be outside of the range.
Since
This struct is available since SDL 3.2.0.
SDL_UserEvent
typedef struct SDL_UserEvent SDL_UserEvent
A user-defined event type (event.user.*)
This event is unique; it is never created by SDL, but only by the application. The event can be pushed onto the event queue using SDL_PushEvent(). The contents of the structure members are completely up to the programmer; the only requirement is that '''type''' is a value obtained from SDL_RegisterEvents().
Since
This struct is available since SDL 3.2.0.
SDL_WindowEvent
typedef struct SDL_WindowEvent SDL_WindowEvent
Window state change event data (event.window.*)
Since
This struct is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_EventAction
enum SDL_EventAction
The type of action to request from SDL_PeepEvents().
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_ADDEVENT
Add events to the back of the queue.
SDL_PEEKEVENT
Check but don't remove events from the queue front.
SDL_GETEVENT
Retrieve/remove events from the front of the queue.
{
    SDL_ADDEVENT,  /**< Add events to the back of the queue. */
    SDL_PEEKEVENT, /**< Check but don't remove events from the queue front. */
    SDL_GETEVENT   /**< Retrieve/remove events from the front of the queue. */
} SDL_EventAction;
SDL_EventType
enum SDL_EventType
CategoryEvents
Event queue management.
It's extremely common–often required–that an app deal with SDL's event queue. Almost all useful information about interactions with the real world flow through here: the user interacting with the computer and app, hardware coming and going, the system changing in some way, etc.
An app generally takes a moment, perhaps at the start of a new frame, to examine any events that have occured since the last time and process or ignore them. This is generally done by calling SDL_PollEvent() in a loop until it returns false (or, if using the main callbacks, events are provided one at a time in calls to SDL_AppEvent() before the next call to SDL_AppIterate(); in this scenario, the app does not call SDL_PollEvent() at all).
There is other forms of control, too: SDL_PeepEvents() has more functionality at the cost of more complexity, and SDL_WaitEvent() can block the process until something interesting happens, which might be beneficial for certain types of programs on low-power hardware. One may also call SDL_AddEventWatch() to set a callback when new events arrive.
The app is free to generate their own events, too: SDL_PushEvent allows the app to put events onto the queue for later retrieval; SDL_RegisterEvents can guarantee that these events have a type that isn't in use by other parts of the system. The types of events that can be delivered.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_EVENT_FIRST
Unused (do not remove)
SDL_EVENT_QUIT
User-requested quit
SDL_EVENT_TERMINATING
The application is being terminated by the OS. This event must be handled in a callback set with SDL_AddEventWatch(). Called on iOS in applicationWillTerminate() Called on Android in onDestroy()
SDL_EVENT_LOW_MEMORY
The application is low on memory, free memory if possible. This event must be handled in a callback set with SDL_AddEventWatch(). Called on iOS in applicationDidReceiveMemoryWarning() Called on Android in onTrimMemory()
SDL_EVENT_WILL_ENTER_BACKGROUND
The application is about to enter the background. This event must be handled in a callback set with SDL_AddEventWatch(). Called on iOS in applicationWillResignActive() Called on Android in onPause()
SDL_EVENT_DID_ENTER_BACKGROUND
The application did enter the background and may not get CPU for some time. This event must be handled in a callback set with SDL_AddEventWatch(). Called on iOS in applicationDidEnterBackground() Called on Android in onPause()
SDL_EVENT_WILL_ENTER_FOREGROUND
The application is about to enter the foreground. This event must be handled in a callback set with SDL_AddEventWatch(). Called on iOS in applicationWillEnterForeground() Called on Android in onResume()
SDL_EVENT_DID_ENTER_FOREGROUND
The application is now interactive. This event must be handled in a callback set with SDL_AddEventWatch(). Called on iOS in applicationDidBecomeActive() Called on Android in onResume()
SDL_EVENT_LOCALE_CHANGED
The user's locale preferences have changed.
SDL_EVENT_SYSTEM_THEME_CHANGED
The system theme changed
SDL_EVENT_DISPLAY_ORIENTATION
Display orientation has changed to data1
SDL_EVENT_DISPLAY_ADDED
Display has been added to the system
SDL_EVENT_DISPLAY_REMOVED
Display has been removed from the system
SDL_EVENT_DISPLAY_MOVED
Display has changed position
SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED
Display has changed desktop mode
SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED
Display has changed current mode
SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED
Display has changed content scale
SDL_EVENT_DISPLAY_FIRST
SDL_EVENT_DISPLAY_LAST
SDL_EVENT_WINDOW_SHOWN
Window has been shown
SDL_EVENT_WINDOW_HIDDEN
Window has been hidden
SDL_EVENT_WINDOW_EXPOSED
Window has been exposed and should be redrawn, and can be redrawn directly from event watchers for this event. data1 is 1 for live-resize expose events, 0 otherwise.
SDL_EVENT_WINDOW_MOVED
Window has been moved to data1, data2
SDL_EVENT_WINDOW_RESIZED
Window has been resized to data1xdata2
SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED
The pixel size of the window has changed to data1xdata2
SDL_EVENT_WINDOW_METAL_VIEW_RESIZED
The pixel size of a Metal view associated with the window has changed
SDL_EVENT_WINDOW_MINIMIZED
Window has been minimized
SDL_EVENT_WINDOW_MAXIMIZED
Window has been maximized
SDL_EVENT_WINDOW_RESTORED
Window has been restored to normal size and position
SDL_EVENT_WINDOW_MOUSE_ENTER
Window has gained mouse focus
SDL_EVENT_WINDOW_MOUSE_LEAVE
Window has lost mouse focus
SDL_EVENT_WINDOW_FOCUS_GAINED
Window has gained keyboard focus
SDL_EVENT_WINDOW_FOCUS_LOST
Window has lost keyboard focus
SDL_EVENT_WINDOW_CLOSE_REQUESTED
The window manager requests that the window be closed
SDL_EVENT_WINDOW_HIT_TEST
Window had a hit test that wasn't SDL_HITTEST_NORMAL
SDL_EVENT_WINDOW_ICCPROF_CHANGED
The ICC profile of the window's display has changed
SDL_EVENT_WINDOW_DISPLAY_CHANGED
Window has been moved to display data1
SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED
Window display scale has been changed
SDL_EVENT_WINDOW_SAFE_AREA_CHANGED
The window safe area has been changed
SDL_EVENT_WINDOW_OCCLUDED
The window has been occluded
SDL_EVENT_WINDOW_ENTER_FULLSCREEN
The window has entered fullscreen mode
SDL_EVENT_WINDOW_LEAVE_FULLSCREEN
The window has left fullscreen mode
SDL_EVENT_WINDOW_DESTROYED
The window with the associated ID is being or has been destroyed. If this message is being handled in an event watcher, the window handle is still valid and can still be used to retrieve any properties associated with the window. Otherwise, the handle has already been destroyed and all resources associated with it are invalid
SDL_EVENT_WINDOW_HDR_STATE_CHANGED
Window HDR properties have changed
SDL_EVENT_WINDOW_FIRST
SDL_EVENT_WINDOW_LAST
SDL_EVENT_KEY_DOWN
Key pressed
SDL_EVENT_KEY_UP
Key released
SDL_EVENT_TEXT_EDITING
Keyboard text editing (composition)
SDL_EVENT_TEXT_INPUT
Keyboard text input
SDL_EVENT_KEYMAP_CHANGED
Keymap changed due to a system event such as an input language or keyboard layout change.
SDL_EVENT_KEYBOARD_ADDED
A new keyboard has been inserted into the system
SDL_EVENT_KEYBOARD_REMOVED
A keyboard has been removed
SDL_EVENT_TEXT_EDITING_CANDIDATES
Keyboard text editing candidates
SDL_EVENT_MOUSE_MOTION
Mouse moved
SDL_EVENT_MOUSE_BUTTON_DOWN
Mouse button pressed
SDL_EVENT_MOUSE_BUTTON_UP
Mouse button released
SDL_EVENT_MOUSE_WHEEL
Mouse wheel motion
SDL_EVENT_MOUSE_ADDED
A new mouse has been inserted into the system
SDL_EVENT_MOUSE_REMOVED
A mouse has been removed
SDL_EVENT_JOYSTICK_AXIS_MOTION
Joystick axis motion
SDL_EVENT_JOYSTICK_BALL_MOTION
Joystick trackball motion
SDL_EVENT_JOYSTICK_HAT_MOTION
Joystick hat position change
SDL_EVENT_JOYSTICK_BUTTON_DOWN
Joystick button pressed
SDL_EVENT_JOYSTICK_BUTTON_UP
Joystick button released
SDL_EVENT_JOYSTICK_ADDED
A new joystick has been inserted into the system
SDL_EVENT_JOYSTICK_REMOVED
An opened joystick has been removed
SDL_EVENT_JOYSTICK_BATTERY_UPDATED
Joystick battery level change
SDL_EVENT_JOYSTICK_UPDATE_COMPLETE
Joystick update is complete
SDL_EVENT_GAMEPAD_AXIS_MOTION
Gamepad axis motion
SDL_EVENT_GAMEPAD_BUTTON_DOWN
Gamepad button pressed
SDL_EVENT_GAMEPAD_BUTTON_UP
Gamepad button released
SDL_EVENT_GAMEPAD_ADDED
A new gamepad has been inserted into the system
SDL_EVENT_GAMEPAD_REMOVED
A gamepad has been removed
SDL_EVENT_GAMEPAD_REMAPPED
The gamepad mapping was updated
SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN
Gamepad touchpad was touched
SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION
Gamepad touchpad finger was moved
SDL_EVENT_GAMEPAD_TOUCHPAD_UP
Gamepad touchpad finger was lifted
SDL_EVENT_GAMEPAD_SENSOR_UPDATE
Gamepad sensor was updated
SDL_EVENT_GAMEPAD_UPDATE_COMPLETE
Gamepad update is complete
SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED
Gamepad Steam handle has changed
SDL_EVENT_FINGER_DOWN
SDL_EVENT_FINGER_UP
SDL_EVENT_FINGER_MOTION
SDL_EVENT_FINGER_CANCELED
SDL_EVENT_CLIPBOARD_UPDATE
The clipboard or primary selection changed
SDL_EVENT_DROP_FILE
The system requests a file open
SDL_EVENT_DROP_TEXT
text/plain drag-and-drop event
SDL_EVENT_DROP_BEGIN
A new set of drops is beginning (NULL filename)
SDL_EVENT_DROP_COMPLETE
Current set of drops is now complete (NULL filename)
SDL_EVENT_DROP_POSITION
Position while moving over the window
SDL_EVENT_AUDIO_DEVICE_ADDED
A new audio device is available
SDL_EVENT_AUDIO_DEVICE_REMOVED
An audio device has been removed.
SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED
An audio device's format has been changed by the system.
SDL_EVENT_SENSOR_UPDATE
A sensor was updated
SDL_EVENT_PEN_PROXIMITY_IN
Pressure-sensitive pen has become available
SDL_EVENT_PEN_PROXIMITY_OUT
Pressure-sensitive pen has become unavailable
SDL_EVENT_PEN_DOWN
Pressure-sensitive pen touched drawing surface
SDL_EVENT_PEN_UP
Pressure-sensitive pen stopped touching drawing surface
SDL_EVENT_PEN_BUTTON_DOWN
Pressure-sensitive pen button pressed
SDL_EVENT_PEN_BUTTON_UP
Pressure-sensitive pen button released
SDL_EVENT_PEN_MOTION
Pressure-sensitive pen is moving on the tablet
SDL_EVENT_PEN_AXIS
Pressure-sensitive pen angle/pressure/etc changed
SDL_EVENT_CAMERA_DEVICE_ADDED
A new camera device is available
SDL_EVENT_CAMERA_DEVICE_REMOVED
A camera device has been removed.
SDL_EVENT_CAMERA_DEVICE_APPROVED
A camera device has been approved for use by the user.
SDL_EVENT_CAMERA_DEVICE_DENIED
A camera device has been denied for use by the user.
SDL_EVENT_RENDER_TARGETS_RESET
The render targets have been reset and their contents need to be updated
SDL_EVENT_RENDER_DEVICE_RESET
The device has been reset and all textures need to be recreated
SDL_EVENT_RENDER_DEVICE_LOST
The device has been lost and can't be recovered.
SDL_EVENT_PRIVATE0
SDL_EVENT_PRIVATE1
SDL_EVENT_PRIVATE2
SDL_EVENT_PRIVATE3
SDL_EVENT_POLL_SENTINEL
Signals the end of an event poll cycle
SDL_EVENT_USER
Events SDL_EVENT_USER through SDL_EVENT_LAST are for your use, and should be allocated with SDL_RegisterEvents()
SDL_EVENT_LAST
This last event is only for bounding internal arrays
SDL_EVENT_ENUM_PADDING
{
    SDL_EVENT_FIRST     = 0,     /**< Unused (do not remove) */
    /* Application events */
    SDL_EVENT_QUIT           = 0x100, /**< User-requested quit */
    /* These application events have special meaning on iOS and Android, see README-ios.md and README-android.md for details */
    SDL_EVENT_TERMINATING,      /**< The application is being terminated by the OS. This event must be handled in a callback set with SDL_AddEventWatch().
                                     Called on iOS in applicationWillTerminate()
                                     Called on Android in onDestroy()
                                */
    SDL_EVENT_LOW_MEMORY,       /**< The application is low on memory, free memory if possible. This event must be handled in a callback set with SDL_AddEventWatch().
                                     Called on iOS in applicationDidReceiveMemoryWarning()
                                     Called on Android in onTrimMemory()
                                */
    SDL_EVENT_WILL_ENTER_BACKGROUND, /**< The application is about to enter the background. This event must be handled in a callback set with SDL_AddEventWatch().
                                     Called on iOS in applicationWillResignActive()
                                     Called on Android in onPause()
                                */
    SDL_EVENT_DID_ENTER_BACKGROUND, /**< The application did enter the background and may not get CPU for some time. This event must be handled in a callback set with SDL_AddEventWatch().
                                     Called on iOS in applicationDidEnterBackground()
                                     Called on Android in onPause()
                                */
    SDL_EVENT_WILL_ENTER_FOREGROUND, /**< The application is about to enter the foreground. This event must be handled in a callback set with SDL_AddEventWatch().
                                     Called on iOS in applicationWillEnterForeground()
                                     Called on Android in onResume()
                                */
    SDL_EVENT_DID_ENTER_FOREGROUND, /**< The application is now interactive. This event must be handled in a callback set with SDL_AddEventWatch().
                                     Called on iOS in applicationDidBecomeActive()
                                     Called on Android in onResume()
                                */
    SDL_EVENT_LOCALE_CHANGED,  /**< The user's locale preferences have changed. */
    SDL_EVENT_SYSTEM_THEME_CHANGED, /**< The system theme changed */
    /* Display events */
    /* 0x150 was SDL_DISPLAYEVENT, reserve the number for sdl2-compat */
    SDL_EVENT_DISPLAY_ORIENTATION = 0x151,   /**< Display orientation has changed to data1 */
    SDL_EVENT_DISPLAY_ADDED,                 /**< Display has been added to the system */
    SDL_EVENT_DISPLAY_REMOVED,               /**< Display has been removed from the system */
    SDL_EVENT_DISPLAY_MOVED,                 /**< Display has changed position */
    SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED,  /**< Display has changed desktop mode */
    SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED,  /**< Display has changed current mode */
    SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED, /**< Display has changed content scale */
    SDL_EVENT_DISPLAY_FIRST = SDL_EVENT_DISPLAY_ORIENTATION,
    SDL_EVENT_DISPLAY_LAST = SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED,
    /* Window events */
    /* 0x200 was SDL_WINDOWEVENT, reserve the number for sdl2-compat */
    /* 0x201 was SDL_SYSWMEVENT, reserve the number for sdl2-compat */
    SDL_EVENT_WINDOW_SHOWN = 0x202,     /**< Window has been shown */
    SDL_EVENT_WINDOW_HIDDEN,            /**< Window has been hidden */
    SDL_EVENT_WINDOW_EXPOSED,           /**< Window has been exposed and should be redrawn, and can be redrawn directly from event watchers for this event.
                                             data1 is 1 for live-resize expose events, 0 otherwise. */
    SDL_EVENT_WINDOW_MOVED,             /**< Window has been moved to data1, data2 */
    SDL_EVENT_WINDOW_RESIZED,           /**< Window has been resized to data1xdata2 */
    SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED,/**< The pixel size of the window has changed to data1xdata2 */
    SDL_EVENT_WINDOW_METAL_VIEW_RESIZED,/**< The pixel size of a Metal view associated with the window has changed */
    SDL_EVENT_WINDOW_MINIMIZED,         /**< Window has been minimized */
    SDL_EVENT_WINDOW_MAXIMIZED,         /**< Window has been maximized */
    SDL_EVENT_WINDOW_RESTORED,          /**< Window has been restored to normal size and position */
    SDL_EVENT_WINDOW_MOUSE_ENTER,       /**< Window has gained mouse focus */
    SDL_EVENT_WINDOW_MOUSE_LEAVE,       /**< Window has lost mouse focus */
    SDL_EVENT_WINDOW_FOCUS_GAINED,      /**< Window has gained keyboard focus */
    SDL_EVENT_WINDOW_FOCUS_LOST,        /**< Window has lost keyboard focus */
    SDL_EVENT_WINDOW_CLOSE_REQUESTED,   /**< The window manager requests that the window be closed */
    SDL_EVENT_WINDOW_HIT_TEST,          /**< Window had a hit test that wasn't SDL_HITTEST_NORMAL */
    SDL_EVENT_WINDOW_ICCPROF_CHANGED,   /**< The ICC profile of the window's display has changed */
    SDL_EVENT_WINDOW_DISPLAY_CHANGED,   /**< Window has been moved to display data1 */
    SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED, /**< Window display scale has been changed */
    SDL_EVENT_WINDOW_SAFE_AREA_CHANGED, /**< The window safe area has been changed */
    SDL_EVENT_WINDOW_OCCLUDED,          /**< The window has been occluded */
    SDL_EVENT_WINDOW_ENTER_FULLSCREEN,  /**< The window has entered fullscreen mode */
    SDL_EVENT_WINDOW_LEAVE_FULLSCREEN,  /**< The window has left fullscreen mode */
    SDL_EVENT_WINDOW_DESTROYED,         /**< The window with the associated ID is being or has been destroyed. If this message is being handled
                                             in an event watcher, the window handle is still valid and can still be used to retrieve any properties
                                             associated with the window. Otherwise, the handle has already been destroyed and all resources
                                             associated with it are invalid */
    SDL_EVENT_WINDOW_HDR_STATE_CHANGED, /**< Window HDR properties have changed */
    SDL_EVENT_WINDOW_FIRST = SDL_EVENT_WINDOW_SHOWN,
    SDL_EVENT_WINDOW_LAST = SDL_EVENT_WINDOW_HDR_STATE_CHANGED,
    /* Keyboard events */
    SDL_EVENT_KEY_DOWN        = 0x300, /**< Key pressed */
    SDL_EVENT_KEY_UP,                  /**< Key released */
    SDL_EVENT_TEXT_EDITING,            /**< Keyboard text editing (composition) */
    SDL_EVENT_TEXT_INPUT,              /**< Keyboard text input */
    SDL_EVENT_KEYMAP_CHANGED,          /**< Keymap changed due to a system event such as an
                                            input language or keyboard layout change. */
    SDL_EVENT_KEYBOARD_ADDED,          /**< A new keyboard has been inserted into the system */
    SDL_EVENT_KEYBOARD_REMOVED,        /**< A keyboard has been removed */
    SDL_EVENT_TEXT_EDITING_CANDIDATES, /**< Keyboard text editing candidates */
    /* Mouse events */
    SDL_EVENT_MOUSE_MOTION    = 0x400, /**< Mouse moved */
    SDL_EVENT_MOUSE_BUTTON_DOWN,       /**< Mouse button pressed */
    SDL_EVENT_MOUSE_BUTTON_UP,         /**< Mouse button released */
    SDL_EVENT_MOUSE_WHEEL,             /**< Mouse wheel motion */
    SDL_EVENT_MOUSE_ADDED,             /**< A new mouse has been inserted into the system */
    SDL_EVENT_MOUSE_REMOVED,           /**< A mouse has been removed */
    /* Joystick events */
    SDL_EVENT_JOYSTICK_AXIS_MOTION  = 0x600, /**< Joystick axis motion */
    SDL_EVENT_JOYSTICK_BALL_MOTION,          /**< Joystick trackball motion */
    SDL_EVENT_JOYSTICK_HAT_MOTION,           /**< Joystick hat position change */
    SDL_EVENT_JOYSTICK_BUTTON_DOWN,          /**< Joystick button pressed */
    SDL_EVENT_JOYSTICK_BUTTON_UP,            /**< Joystick button released */
    SDL_EVENT_JOYSTICK_ADDED,                /**< A new joystick has been inserted into the system */
    SDL_EVENT_JOYSTICK_REMOVED,              /**< An opened joystick has been removed */
    SDL_EVENT_JOYSTICK_BATTERY_UPDATED,      /**< Joystick battery level change */
    SDL_EVENT_JOYSTICK_UPDATE_COMPLETE,      /**< Joystick update is complete */
    /* Gamepad events */
    SDL_EVENT_GAMEPAD_AXIS_MOTION  = 0x650, /**< Gamepad axis motion */
    SDL_EVENT_GAMEPAD_BUTTON_DOWN,          /**< Gamepad button pressed */
    SDL_EVENT_GAMEPAD_BUTTON_UP,            /**< Gamepad button released */
    SDL_EVENT_GAMEPAD_ADDED,                /**< A new gamepad has been inserted into the system */
    SDL_EVENT_GAMEPAD_REMOVED,              /**< A gamepad has been removed */
    SDL_EVENT_GAMEPAD_REMAPPED,             /**< The gamepad mapping was updated */
    SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN,        /**< Gamepad touchpad was touched */
    SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION,      /**< Gamepad touchpad finger was moved */
    SDL_EVENT_GAMEPAD_TOUCHPAD_UP,          /**< Gamepad touchpad finger was lifted */
    SDL_EVENT_GAMEPAD_SENSOR_UPDATE,        /**< Gamepad sensor was updated */
    SDL_EVENT_GAMEPAD_UPDATE_COMPLETE,      /**< Gamepad update is complete */
    SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED,  /**< Gamepad Steam handle has changed */
    /* Touch events */
    SDL_EVENT_FINGER_DOWN      = 0x700,
    SDL_EVENT_FINGER_UP,
    SDL_EVENT_FINGER_MOTION,
    SDL_EVENT_FINGER_CANCELED,
    /* 0x800, 0x801, and 0x802 were the Gesture events from SDL2. Do not reuse these values! sdl2-compat needs them! */
    /* Clipboard events */
    SDL_EVENT_CLIPBOARD_UPDATE = 0x900, /**< The clipboard or primary selection changed */
    /* Drag and drop events */
    SDL_EVENT_DROP_FILE        = 0x1000, /**< The system requests a file open */
    SDL_EVENT_DROP_TEXT,                 /**< text/plain drag-and-drop event */
    SDL_EVENT_DROP_BEGIN,                /**< A new set of drops is beginning (NULL filename) */
    SDL_EVENT_DROP_COMPLETE,             /**< Current set of drops is now complete (NULL filename) */
    SDL_EVENT_DROP_POSITION,             /**< Position while moving over the window */
    /* Audio hotplug events */
    SDL_EVENT_AUDIO_DEVICE_ADDED = 0x1100,  /**< A new audio device is available */
    SDL_EVENT_AUDIO_DEVICE_REMOVED,         /**< An audio device has been removed. */
    SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED,  /**< An audio device's format has been changed by the system. */
    /* Sensor events */
    SDL_EVENT_SENSOR_UPDATE = 0x1200,     /**< A sensor was updated */
    /* Pressure-sensitive pen events */
    SDL_EVENT_PEN_PROXIMITY_IN = 0x1300,  /**< Pressure-sensitive pen has become available */
    SDL_EVENT_PEN_PROXIMITY_OUT,          /**< Pressure-sensitive pen has become unavailable */
    SDL_EVENT_PEN_DOWN,                   /**< Pressure-sensitive pen touched drawing surface */
    SDL_EVENT_PEN_UP,                     /**< Pressure-sensitive pen stopped touching drawing surface */
    SDL_EVENT_PEN_BUTTON_DOWN,            /**< Pressure-sensitive pen button pressed */
    SDL_EVENT_PEN_BUTTON_UP,              /**< Pressure-sensitive pen button released */
    SDL_EVENT_PEN_MOTION,                 /**< Pressure-sensitive pen is moving on the tablet */
    SDL_EVENT_PEN_AXIS,                   /**< Pressure-sensitive pen angle/pressure/etc changed */
    /* Camera hotplug events */
    SDL_EVENT_CAMERA_DEVICE_ADDED = 0x1400,  /**< A new camera device is available */
    SDL_EVENT_CAMERA_DEVICE_REMOVED,         /**< A camera device has been removed. */
    SDL_EVENT_CAMERA_DEVICE_APPROVED,        /**< A camera device has been approved for use by the user. */
    SDL_EVENT_CAMERA_DEVICE_DENIED,          /**< A camera device has been denied for use by the user. */
    /* Render events */
    SDL_EVENT_RENDER_TARGETS_RESET = 0x2000, /**< The render targets have been reset and their contents need to be updated */
    SDL_EVENT_RENDER_DEVICE_RESET, /**< The device has been reset and all textures need to be recreated */
    SDL_EVENT_RENDER_DEVICE_LOST, /**< The device has been lost and can't be recovered. */
    /* Reserved events for private platforms */
    SDL_EVENT_PRIVATE0 = 0x4000,
    SDL_EVENT_PRIVATE1,
    SDL_EVENT_PRIVATE2,
    SDL_EVENT_PRIVATE3,
    /* Internal events */
    SDL_EVENT_POLL_SENTINEL = 0x7F00, /**< Signals the end of an event poll cycle */
    /** Events SDL_EVENT_USER through SDL_EVENT_LAST are for your use,
     *  and should be allocated with SDL_RegisterEvents()
     */
    SDL_EVENT_USER    = 0x8000,
    /**
     *  This last event is only for bounding internal arrays
     */
    SDL_EVENT_LAST    = 0xFFFF,
    /* This just makes sure the enum is the size of Uint32 */
    SDL_EVENT_ENUM_PADDING = 0x7FFFFFFF
} SDL_EventType;
Function Documentation
SDL_AddEventWatch()
SDL_DECLSPEC bool SDLCALL SDL_AddEventWatch (SDL_EventFilter filter, void * userdata) extern
Add a callback to be triggered when an event is added to the event queue.
filter will be called when an event happens, and its return value is ignored.
WARNING: Be very careful of what you do in the event filter function, as it may run in a different thread!
If the quit event is generated by a signal (e.g. SIGINT), it will bypass the internal queue and be delivered to the watch callback immediately, and arrive at the next event poll.
Note: the callback is called for events posted by the user through SDL_PushEvent(), but not for disabled events, nor for events by a filter callback set with SDL_SetEventFilter(), nor for events posted by the user through SDL_PeepEvents().
Parameters
filter an SDL_EventFilter function to call when an event happens.
userdata a pointer that is passed to filter.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveEventWatch
SDL_SetEventFilter
{
    return SDL_AddEventWatchList(&SDL_event_watchers, filter, userdata);
}
References SDL_AddEventWatchList(), SDL_event_watchers, and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_EnterAppMainCallbacks(), SDL_InitGamepads(), and SDL_InitMainCallbacks().
SDL_COMPILE_TIME_ASSERT()
SDL_COMPILE_TIME_ASSERT (SDL_Event , sizeof(SDL_Event) = =sizeof(((SDL_Event *) NULL) ->padding))
References NULL, SDL_DECLSPEC, and SDLCALL.
SDL_EventEnabled()
SDL_DECLSPEC bool SDLCALL SDL_EventEnabled (Uint32 type) extern
Query the state of processing events by type.
Parameters
type the type of event; see SDL_EventType for details.
Returns
true if the event is being processed, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetEventEnabled
{
    Uint8 hi = ((type >> 8) & 0xff);
    Uint8 lo = (type & 0xff);
    if (SDL_disabled_events[hi] &&
        (SDL_disabled_events[hi]->bits[lo / 32] & (1U << (lo & 31)))) {
        return false;
    } else {
        return true;
    }
}
References SDL_disabled_events.
Referenced by IsAcceptingDragAndDrop(), SDL_AddPenDevice(), SDL_GamepadEventsEnabled(), SDL_GamepadEventWatcher(), SDL_JoystickEventsEnabled(), SDL_PrivateJoystickAdded(), SDL_PrivateJoystickRemoved(), SDL_PrivateSendMouseButton(), SDL_PrivateSendMouseMotion(), SDL_PumpEventsInternal(), SDL_RemovePenDevice(), SDL_SendAppEvent(), SDL_SendClipboardUpdate(), SDL_SendDisplayEvent(), SDL_SendDrop(), SDL_SendEditingText(), SDL_SendEditingTextCandidates(), SDL_SendGamepadAxis(), SDL_SendGamepadButton(), SDL_SendJoystickAxis(), SDL_SendJoystickBall(), SDL_SendJoystickButton(), SDL_SendJoystickHat(), SDL_SendJoystickPowerInfo(), SDL_SendJoystickSensor(), SDL_SendJoystickTouchpad(), SDL_SendKeyboardKeyInternal(), SDL_SendKeyboardText(), SDL_SendMouseWheel(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SendSensorUpdate(), SDL_SendTouch(), SDL_SendTouchMotion(), SDL_SendWindowEvent(), SDL_UpdateAudio(), SDL_UpdateCamera(), and SDL_UpdateJoysticks().
SDL_FilterEvents()
SDL_DECLSPEC void SDLCALL SDL_FilterEvents (SDL_EventFilter filter, void * userdata) extern
Run a specific filter function on the current event queue, removing any events for which the filter returns false.
See SDL_SetEventFilter() for more information. Unlike SDL_SetEventFilter(), this function does not change the filter permanently, it only uses the supplied filter until this function returns.
Parameters
filter the SDL_EventFilter function to call when an event happens.
userdata a pointer that is passed to filter.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetEventFilter
SDL_SetEventFilter
{
    SDL_LockMutex(SDL_EventQ.lock);
    {
        SDL_EventEntry *entry, *next;
        for (entry = SDL_EventQ.head; entry; entry = next) {
            next = entry->next;
            if (!filter(userdata, &entry->event)) {
                SDL_CutEvent(entry);
            }
        }
    }
    SDL_UnlockMutex(SDL_EventQ.lock);
}
References SDL_EventEntry::event, SDL_EventEntry::next, SDL_MainThreadCallbackEntry::next, SDL_CutEvent(), SDL_EventQ, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_SendWindowEvent().
SDL_FlushEvent()
SDL_DECLSPEC void SDLCALL SDL_FlushEvent (Uint32 type) extern
Clear events of a specific type from the event queue.
This will unconditionally remove any events from the queue that match type. If you need to remove a range of event types, use SDL_FlushEvents() instead.
It's also normal to just ignore events you don't care about in your event loop without calling this function.
This function only affects currently queued events. If you want to make sure that all pending OS events are flushed, you can call SDL_PumpEvents() on the main thread immediately before the flush call.
If you have user events with custom data that needs to be freed, you should use SDL_PeepEvents() to remove and clean up those events before calling this function.
Parameters
type the type of event to be cleared; see SDL_EventType for details.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_FlushEvents
{
    SDL_FlushEvents(type, type);
}
References SDL_FlushEvents().
Referenced by SDL_SetEventEnabled(), and SDL_SetRelativeMouseMode().
SDL_FlushEvents()
SDL_DECLSPEC void SDLCALL SDL_FlushEvents (Uint32 minType, Uint32 maxType) extern
Clear events of a range of types from the event queue.
This will unconditionally remove any events from the queue that are in the range of minType to maxType, inclusive. If you need to remove a single event type, use SDL_FlushEvent() instead.
It's also normal to just ignore events you don't care about in your event loop without calling this function.
This function only affects currently queued events. If you want to make sure that all pending OS events are flushed, you can call SDL_PumpEvents() on the main thread immediately before the flush call.
Parameters
minType the low end of event type to be cleared, inclusive; see SDL_EventType for details.
maxType the high end of event type to be cleared, inclusive; see SDL_EventType for details.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_FlushEvent
{
    SDL_EventEntry *entry, *next;
    Uint32 type;
    // Make sure the events are current
#if 0
    /* Actually, we can't do this since we might be flushing while processing
       a resize event, and calling this might trigger further resize events.
    */
    SDL_PumpEvents();
#endif
    // Lock the event queue
    SDL_LockMutex(SDL_EventQ.lock);
    {
        // Don't look after we've quit
        if (!SDL_EventQ.active) {
            SDL_UnlockMutex(SDL_EventQ.lock);
            return;
        }
        for (entry = SDL_EventQ.head; entry; entry = next) {
            next = entry->next;
            type = entry->event.type;
            if (minType <= type && type <= maxType) {
                SDL_CutEvent(entry);
            }
        }
    }
    SDL_UnlockMutex(SDL_EventQ.lock);
}
References SDL_EventEntry::event, SDL_EventEntry::next, SDL_CutEvent(), SDL_EventQ, SDL_LockMutex(), SDL_PumpEvents(), SDL_UnlockMutex(), and SDL_Event::type.
Referenced by SDL_FlushEvent().
SDL_GetEventDescription()
SDL_DECLSPEC int SDLCALL SDL_GetEventDescription (const SDL_Event * event, char * buf, int buflen) extern
Generate a human-readable description of an event.
This will fill buf with a null-terminated string that might look something like this:
SDL_EVENT_MOUSE_MOTION (timestamp=1140256324 windowid=2 which=0 state=0 x=492.99 y=139.09 xrel=52 yrel=6)
The exact format of the string is not guaranteed; it is intended for logging purposes, to be read by a human, and not parsed by a computer.
The returned value follows the same rules as SDL_snprintf(): buf will always be NULL-terminated (unless buflen is zero), and will be truncated if buflen is too small. The return code is the number of bytes needed for the complete string, not counting the NULL-terminator, whether the string was truncated or not. Unlike SDL_snprintf(), though, this function never returns -1.
Parameters
event an event to describe. May be NULL.
buf the buffer to fill with the description string. May be NULL.
buflen the maximum bytes that can be written to buf.
Returns
number of bytes needed for the full string, not counting the null-terminator byte.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.4.0.
{
    if (!event) {
        return SDL_snprintf(buf, buflen, "(null)");
    }
    static const char *pen_axisnames[] = { "PRESSURE", "XTILT", "YTILT", "DISTANCE", "ROTATION", "SLIDER", "TANGENTIAL_PRESSURE" };
    SDL_COMPILE_TIME_ASSERT(pen_axisnames_array_matches, SDL_arraysize(pen_axisnames) == SDL_PEN_AXIS_COUNT);
    char name[64];
    char details[128];
// this is to make (void)SDL_snprintf() calls cleaner.
#define uint unsigned int
    name[0] = '\0';
    details[0] = '\0';
    // !!! FIXME: This code is kinda ugly, sorry.
    if ((event->type >= SDL_EVENT_USER) && (event->type <= SDL_EVENT_LAST)) {
        char plusstr[16];
        SDL_strlcpy(name, "SDL_EVENT_USER", sizeof(name));
        if (event->type > SDL_EVENT_USER) {
            (void)SDL_snprintf(plusstr, sizeof(plusstr), "+%u", ((uint)event->type) - SDL_EVENT_USER);
        } else {
            plusstr[0] = '\0';
        }
        (void)SDL_snprintf(details, sizeof(details), "%s (timestamp=%u windowid=%u code=%d data1=%p data2=%p)",
                           plusstr, (uint)event->user.timestamp, (uint)event->user.windowID,
                           (int)event->user.code, event->user.data1, event->user.data2);
    }
    switch (event->type) {
#define SDL_EVENT_CASE(x) \
    case x:               \
        SDL_strlcpy(name, #x, sizeof(name));
        SDL_EVENT_CASE(SDL_EVENT_FIRST)
        SDL_strlcpy(details, " (THIS IS PROBABLY A BUG!)", sizeof(details));
        break;
        SDL_EVENT_CASE(SDL_EVENT_QUIT)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u)", (uint)event->quit.timestamp);
        break;
        SDL_EVENT_CASE(SDL_EVENT_TERMINATING)
        break;
        SDL_EVENT_CASE(SDL_EVENT_LOW_MEMORY)
        break;
        SDL_EVENT_CASE(SDL_EVENT_WILL_ENTER_BACKGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_DID_ENTER_BACKGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_WILL_ENTER_FOREGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_DID_ENTER_FOREGROUND)
        break;
        SDL_EVENT_CASE(SDL_EVENT_LOCALE_CHANGED)
        break;
        SDL_EVENT_CASE(SDL_EVENT_SYSTEM_THEME_CHANGED)
        break;
        SDL_EVENT_CASE(SDL_EVENT_KEYMAP_CHANGED)
        break;
        SDL_EVENT_CASE(SDL_EVENT_CLIPBOARD_UPDATE)
        break;
#define SDL_RENDEREVENT_CASE(x)                \
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name));   \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u event=%s windowid=%u)", \
                           (uint)event->display.timestamp, name, (uint)event->render.windowID); \
        break
        SDL_RENDEREVENT_CASE(SDL_EVENT_RENDER_TARGETS_RESET);
        SDL_RENDEREVENT_CASE(SDL_EVENT_RENDER_DEVICE_RESET);
        SDL_RENDEREVENT_CASE(SDL_EVENT_RENDER_DEVICE_LOST);
#define SDL_DISPLAYEVENT_CASE(x)               \
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name));   \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u display=%u event=%s data1=%d, data2=%d)", \
                           (uint)event->display.timestamp, (uint)event->display.displayID, name, (int)event->display.data1, (int)event->display.data2); \
        break
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_ORIENTATION);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_ADDED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_REMOVED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_MOVED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED);
        SDL_DISPLAYEVENT_CASE(SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED);
#undef SDL_DISPLAYEVENT_CASE
#define SDL_WINDOWEVENT_CASE(x)                \
    case x:                                    \
        SDL_strlcpy(name, #x, sizeof(name)); \
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u event=%s data1=%d data2=%d)", \
                           (uint)event->window.timestamp, (uint)event->window.windowID, name, (int)event->window.data1, (int)event->window.data2); \
        break
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_SHOWN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_HIDDEN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_EXPOSED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MOVED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_RESIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_METAL_VIEW_RESIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_SAFE_AREA_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MINIMIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MAXIMIZED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_RESTORED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MOUSE_ENTER);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_MOUSE_LEAVE);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_FOCUS_GAINED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_FOCUS_LOST);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_CLOSE_REQUESTED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_HIT_TEST);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_ICCPROF_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_DISPLAY_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_OCCLUDED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_ENTER_FULLSCREEN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_LEAVE_FULLSCREEN);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_DESTROYED);
        SDL_WINDOWEVENT_CASE(SDL_EVENT_WINDOW_HDR_STATE_CHANGED);
#undef SDL_WINDOWEVENT_CASE
#define PRINT_KEYDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->kdevice.timestamp, (uint)event->kdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_KEYBOARD_ADDED)
        PRINT_KEYDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_KEYBOARD_REMOVED)
        PRINT_KEYDEV_EVENT(event);
        break;
#undef PRINT_KEYDEV_EVENT
#define PRINT_KEY_EVENT(event)                                                                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u state=%s repeat=%s scancode=%u keycode=%u mod=0x%x)", \
                       (uint)event->key.timestamp, (uint)event->key.windowID, (uint)event->key.which,                                       \
                       event->key.down ? "pressed" : "released",                                                            \
                       event->key.repeat ? "true" : "false",                                                                                \
                       (uint)event->key.scancode,                                                                                           \
                       (uint)event->key.key,                                                                                                \
                       (uint)event->key.mod)
        SDL_EVENT_CASE(SDL_EVENT_KEY_DOWN)
        PRINT_KEY_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_KEY_UP)
        PRINT_KEY_EVENT(event);
        break;
#undef PRINT_KEY_EVENT
        SDL_EVENT_CASE(SDL_EVENT_TEXT_EDITING)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u text='%s' start=%d length=%d)",
                           (uint)event->edit.timestamp, (uint)event->edit.windowID,
                           event->edit.text, (int)event->edit.start, (int)event->edit.length);
        break;
        SDL_EVENT_CASE(SDL_EVENT_TEXT_EDITING_CANDIDATES)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u num_candidates=%d selected_candidate=%d)",
                           (uint)event->edit_candidates.timestamp, (uint)event->edit_candidates.windowID,
                           (int)event->edit_candidates.num_candidates, (int)event->edit_candidates.selected_candidate);
        break;
        SDL_EVENT_CASE(SDL_EVENT_TEXT_INPUT)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u text='%s')", (uint)event->text.timestamp, (uint)event->text.windowID, event->text.text);
        break;
#define PRINT_MOUSEDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->mdevice.timestamp, (uint)event->mdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_ADDED)
        PRINT_MOUSEDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_REMOVED)
        PRINT_MOUSEDEV_EVENT(event);
        break;
#undef PRINT_MOUSEDEV_EVENT
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u state=%u x=%g y=%g xrel=%g yrel=%g)",
                           (uint)event->motion.timestamp, (uint)event->motion.windowID,
                           (uint)event->motion.which, (uint)event->motion.state,
                           event->motion.x, event->motion.y,
                           event->motion.xrel, event->motion.yrel);
        break;
#define PRINT_MBUTTON_EVENT(event)                                                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u button=%u state=%s clicks=%u x=%g y=%g)", \
                       (uint)event->button.timestamp, (uint)event->button.windowID,                                             \
                       (uint)event->button.which, (uint)event->button.button,                                                   \
                       event->button.down ? "pressed" : "released",                                                             \
                       (uint)event->button.clicks, event->button.x, event->button.y)
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_BUTTON_DOWN)
        PRINT_MBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_BUTTON_UP)
        PRINT_MBUTTON_EVENT(event);
        break;
#undef PRINT_MBUTTON_EVENT
        SDL_EVENT_CASE(SDL_EVENT_MOUSE_WHEEL)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u x=%g y=%g integer_x=%d integer_y=%d direction=%s)",
                           (uint)event->wheel.timestamp, (uint)event->wheel.windowID,
                           (uint)event->wheel.which, event->wheel.x, event->wheel.y,
                           (int)event->wheel.integer_x, (int)event->wheel.integer_y,
                           event->wheel.direction == SDL_MOUSEWHEEL_NORMAL ? "normal" : "flipped");
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_AXIS_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d axis=%u value=%d)",
                           (uint)event->jaxis.timestamp, (int)event->jaxis.which,
                           (uint)event->jaxis.axis, (int)event->jaxis.value);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BALL_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d ball=%u xrel=%d yrel=%d)",
                           (uint)event->jball.timestamp, (int)event->jball.which,
                           (uint)event->jball.ball, (int)event->jball.xrel, (int)event->jball.yrel);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_HAT_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d hat=%u value=%u)",
                           (uint)event->jhat.timestamp, (int)event->jhat.which,
                           (uint)event->jhat.hat, (uint)event->jhat.value);
        break;
#define PRINT_JBUTTON_EVENT(event)                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d button=%u state=%s)", \
                       (uint)event->jbutton.timestamp, (int)event->jbutton.which,               \
                       (uint)event->jbutton.button, event->jbutton.down ? "pressed" : "released")
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BUTTON_DOWN)
        PRINT_JBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BUTTON_UP)
        PRINT_JBUTTON_EVENT(event);
        break;
#undef PRINT_JBUTTON_EVENT
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_BATTERY_UPDATED)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d state=%u percent=%d)",
                           (uint)event->jbattery.timestamp, (int)event->jbattery.which,
                           event->jbattery.state, event->jbattery.percent);
        break;
#define PRINT_JOYDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d)", (uint)event->jdevice.timestamp, (int)event->jdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_ADDED)
        PRINT_JOYDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_REMOVED)
        PRINT_JOYDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_JOYSTICK_UPDATE_COMPLETE)
        PRINT_JOYDEV_EVENT(event);
        break;
#undef PRINT_JOYDEV_EVENT
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_AXIS_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d axis=%u value=%d)",
                           (uint)event->gaxis.timestamp, (int)event->gaxis.which,
                           (uint)event->gaxis.axis, (int)event->gaxis.value);
        break;
#define PRINT_CBUTTON_EVENT(event)                                                              \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d button=%u state=%s)", \
                       (uint)event->gbutton.timestamp, (int)event->gbutton.which,               \
                       (uint)event->gbutton.button, event->gbutton.down ? "pressed" : "released")
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_BUTTON_DOWN)
        PRINT_CBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_BUTTON_UP)
        PRINT_CBUTTON_EVENT(event);
        break;
#undef PRINT_CBUTTON_EVENT
#define PRINT_GAMEPADDEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d)", (uint)event->gdevice.timestamp, (int)event->gdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_ADDED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_REMOVED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_REMAPPED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_UPDATE_COMPLETE)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED)
        PRINT_GAMEPADDEV_EVENT(event);
        break;
#undef PRINT_GAMEPADDEV_EVENT
#define PRINT_CTOUCHPAD_EVENT(event)                                                                                     \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d touchpad=%d finger=%d x=%f y=%f pressure=%f)", \
                       (uint)event->gtouchpad.timestamp, (int)event->gtouchpad.which,                                    \
                       (int)event->gtouchpad.touchpad, (int)event->gtouchpad.finger,                                     \
                       event->gtouchpad.x, event->gtouchpad.y, event->gtouchpad.pressure)
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN)
        PRINT_CTOUCHPAD_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_TOUCHPAD_UP)
        PRINT_CTOUCHPAD_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION)
        PRINT_CTOUCHPAD_EVENT(event);
        break;
#undef PRINT_CTOUCHPAD_EVENT
        SDL_EVENT_CASE(SDL_EVENT_GAMEPAD_SENSOR_UPDATE)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d sensor=%d data[0]=%f data[1]=%f data[2]=%f)",
                           (uint)event->gsensor.timestamp, (int)event->gsensor.which, (int)event->gsensor.sensor,
                           event->gsensor.data[0], event->gsensor.data[1], event->gsensor.data[2]);
        break;
#define PRINT_FINGER_EVENT(event)                                                                                                                      \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u touchid=%" SDL_PRIu64 " fingerid=%" SDL_PRIu64 " x=%f y=%f dx=%f dy=%f pressure=%f)", \
                       (uint)event->tfinger.timestamp, event->tfinger.touchID,                                                              \
                       event->tfinger.fingerID, event->tfinger.x, event->tfinger.y,                                                         \
                       event->tfinger.dx, event->tfinger.dy, event->tfinger.pressure)
        SDL_EVENT_CASE(SDL_EVENT_FINGER_DOWN)
        PRINT_FINGER_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_FINGER_UP)
        PRINT_FINGER_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_FINGER_CANCELED)
        PRINT_FINGER_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_FINGER_MOTION)
        PRINT_FINGER_EVENT(event);
        break;
#undef PRINT_FINGER_EVENT
#define PRINT_PTOUCH_EVENT(event)                                                                             \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g eraser=%s state=%s)", \
                       (uint)event->ptouch.timestamp, (uint)event->ptouch.windowID, (uint)event->ptouch.which, (uint)event->ptouch.pen_state, event->ptouch.x, event->ptouch.y, \
                       event->ptouch.eraser ? "yes" : "no", event->ptouch.down ? "down" : "up");
        SDL_EVENT_CASE(SDL_EVENT_PEN_DOWN)
        PRINT_PTOUCH_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_UP)
        PRINT_PTOUCH_EVENT(event);
        break;
#undef PRINT_PTOUCH_EVENT
#define PRINT_PPROXIMITY_EVENT(event)                                                                             \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u)", \
                       (uint)event->pproximity.timestamp, (uint)event->pproximity.windowID, (uint)event->pproximity.which);
        SDL_EVENT_CASE(SDL_EVENT_PEN_PROXIMITY_IN)
        PRINT_PPROXIMITY_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_PROXIMITY_OUT)
        PRINT_PPROXIMITY_EVENT(event);
        break;
#undef PRINT_PPROXIMITY_EVENT
        SDL_EVENT_CASE(SDL_EVENT_PEN_AXIS)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g axis=%s value=%g)",
                           (uint)event->paxis.timestamp, (uint)event->paxis.windowID, (uint)event->paxis.which, (uint)event->paxis.pen_state, event->paxis.x, event->paxis.y,
                           ((((int) event->paxis.axis) >= 0) && (event->paxis.axis < SDL_arraysize(pen_axisnames))) ? pen_axisnames[event->paxis.axis] : "[UNKNOWN]", event->paxis.value);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_MOTION)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g)",
                           (uint)event->pmotion.timestamp, (uint)event->pmotion.windowID, (uint)event->pmotion.which, (uint)event->pmotion.pen_state, event->pmotion.x, event->pmotion.y);
        break;
#define PRINT_PBUTTON_EVENT(event)                                                                                                               \
    (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u windowid=%u which=%u pen_state=%u x=%g y=%g button=%u state=%s)", \
                       (uint)event->pbutton.timestamp, (uint)event->pbutton.windowID, (uint)event->pbutton.which, (uint)event->pbutton.pen_state, event->pbutton.x, event->pbutton.y, \
                       (uint)event->pbutton.button, event->pbutton.down ? "down" : "up");
        SDL_EVENT_CASE(SDL_EVENT_PEN_BUTTON_DOWN)
        PRINT_PBUTTON_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_PEN_BUTTON_UP)
        PRINT_PBUTTON_EVENT(event);
        break;
#undef PRINT_PBUTTON_EVENT
#define PRINT_DROP_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (data='%s' timestamp=%u windowid=%u x=%f y=%f)", event->drop.data, (uint)event->drop.timestamp, (uint)event->drop.windowID, event->drop.x, event->drop.y)
        SDL_EVENT_CASE(SDL_EVENT_DROP_FILE)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_TEXT)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_BEGIN)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_COMPLETE)
        PRINT_DROP_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_DROP_POSITION)
        PRINT_DROP_EVENT(event);
        break;
#undef PRINT_DROP_EVENT
#define PRINT_AUDIODEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u recording=%s)", (uint)event->adevice.timestamp, (uint)event->adevice.which, event->adevice.recording ? "true" : "false")
        SDL_EVENT_CASE(SDL_EVENT_AUDIO_DEVICE_ADDED)
        PRINT_AUDIODEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_AUDIO_DEVICE_REMOVED)
        PRINT_AUDIODEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED)
        PRINT_AUDIODEV_EVENT(event);
        break;
#undef PRINT_AUDIODEV_EVENT
#define PRINT_CAMERADEV_EVENT(event) (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%u)", (uint)event->cdevice.timestamp, (uint)event->cdevice.which)
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_ADDED)
        PRINT_CAMERADEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_REMOVED)
        PRINT_CAMERADEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_APPROVED)
        PRINT_CAMERADEV_EVENT(event);
        break;
        SDL_EVENT_CASE(SDL_EVENT_CAMERA_DEVICE_DENIED)
        PRINT_CAMERADEV_EVENT(event);
        break;
#undef PRINT_CAMERADEV_EVENT
        SDL_EVENT_CASE(SDL_EVENT_SENSOR_UPDATE)
        (void)SDL_snprintf(details, sizeof(details), " (timestamp=%u which=%d data[0]=%f data[1]=%f data[2]=%f data[3]=%f data[4]=%f data[5]=%f)",
                           (uint)event->sensor.timestamp, (int)event->sensor.which,
                           event->sensor.data[0], event->sensor.data[1], event->sensor.data[2],
                           event->sensor.data[3], event->sensor.data[4], event->sensor.data[5]);
        break;
#undef SDL_EVENT_CASE
    case SDL_EVENT_POLL_SENTINEL:
        // No logging necessary for this one
        break;
    default:
        if (!name[0]) {
            if (event->type >= SDL_EVENT_USER) {
                SDL_strlcpy(name, "USER", sizeof(name));
            } else {
                SDL_strlcpy(name, "UNKNOWN", sizeof(name));
            }
            (void)SDL_snprintf(details, sizeof(details), " 0x%x", (uint)event->type);
        }
        break;
    }
#undef uint
    int retval = 0;
    if (name[0]) {
        retval = SDL_snprintf(buf, buflen, "%s%s", name, details);
    } else if (buf && (buflen > 0)) {
        *buf = '\0';
    }
    return retval;
}
References PRINT_AUDIODEV_EVENT, PRINT_CAMERADEV_EVENT, PRINT_CBUTTON_EVENT, PRINT_CTOUCHPAD_EVENT, PRINT_DROP_EVENT, PRINT_FINGER_EVENT, PRINT_GAMEPADDEV_EVENT, PRINT_JBUTTON_EVENT, PRINT_JOYDEV_EVENT, PRINT_KEY_EVENT, PRINT_KEYDEV_EVENT, PRINT_MBUTTON_EVENT, PRINT_MOUSEDEV_EVENT, PRINT_PBUTTON_EVENT, PRINT_PPROXIMITY_EVENT, PRINT_PTOUCH_EVENT, SDL_arraysize, SDL_COMPILE_TIME_ASSERT, SDL_DISPLAYEVENT_CASE, SDL_EVENT_AUDIO_DEVICE_ADDED, SDL_EVENT_AUDIO_DEVICE_FORMAT_CHANGED, SDL_EVENT_AUDIO_DEVICE_REMOVED, SDL_EVENT_CAMERA_DEVICE_ADDED, SDL_EVENT_CAMERA_DEVICE_APPROVED, SDL_EVENT_CAMERA_DEVICE_DENIED, SDL_EVENT_CAMERA_DEVICE_REMOVED, SDL_EVENT_CASE, SDL_EVENT_CLIPBOARD_UPDATE, SDL_EVENT_DID_ENTER_BACKGROUND, SDL_EVENT_DID_ENTER_FOREGROUND, SDL_EVENT_DISPLAY_ADDED, SDL_EVENT_DISPLAY_CONTENT_SCALE_CHANGED, SDL_EVENT_DISPLAY_CURRENT_MODE_CHANGED, SDL_EVENT_DISPLAY_DESKTOP_MODE_CHANGED, SDL_EVENT_DISPLAY_MOVED, SDL_EVENT_DISPLAY_ORIENTATION, SDL_EVENT_DISPLAY_REMOVED, SDL_EVENT_DROP_BEGIN, SDL_EVENT_DROP_COMPLETE, SDL_EVENT_DROP_FILE, SDL_EVENT_DROP_POSITION, SDL_EVENT_DROP_TEXT, SDL_EVENT_FINGER_CANCELED, SDL_EVENT_FINGER_DOWN, SDL_EVENT_FINGER_MOTION, SDL_EVENT_FINGER_UP, SDL_EVENT_FIRST, SDL_EVENT_GAMEPAD_ADDED, SDL_EVENT_GAMEPAD_AXIS_MOTION, SDL_EVENT_GAMEPAD_BUTTON_DOWN, SDL_EVENT_GAMEPAD_BUTTON_UP, SDL_EVENT_GAMEPAD_REMAPPED, SDL_EVENT_GAMEPAD_REMOVED, SDL_EVENT_GAMEPAD_SENSOR_UPDATE, SDL_EVENT_GAMEPAD_STEAM_HANDLE_UPDATED, SDL_EVENT_GAMEPAD_TOUCHPAD_DOWN, SDL_EVENT_GAMEPAD_TOUCHPAD_MOTION, SDL_EVENT_GAMEPAD_TOUCHPAD_UP, SDL_EVENT_GAMEPAD_UPDATE_COMPLETE, SDL_EVENT_JOYSTICK_ADDED, SDL_EVENT_JOYSTICK_AXIS_MOTION, SDL_EVENT_JOYSTICK_BALL_MOTION, SDL_EVENT_JOYSTICK_BATTERY_UPDATED, SDL_EVENT_JOYSTICK_BUTTON_DOWN, SDL_EVENT_JOYSTICK_BUTTON_UP, SDL_EVENT_JOYSTICK_HAT_MOTION, SDL_EVENT_JOYSTICK_REMOVED, SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_EVENT_KEY_DOWN, SDL_EVENT_KEY_UP, SDL_EVENT_KEYBOARD_ADDED, SDL_EVENT_KEYBOARD_REMOVED, SDL_EVENT_KEYMAP_CHANGED, SDL_EVENT_LAST, SDL_EVENT_LOCALE_CHANGED, SDL_EVENT_LOW_MEMORY, SDL_EVENT_MOUSE_ADDED, SDL_EVENT_MOUSE_BUTTON_DOWN, SDL_EVENT_MOUSE_BUTTON_UP, SDL_EVENT_MOUSE_MOTION, SDL_EVENT_MOUSE_REMOVED, SDL_EVENT_MOUSE_WHEEL, SDL_EVENT_PEN_AXIS, SDL_EVENT_PEN_BUTTON_DOWN, SDL_EVENT_PEN_BUTTON_UP, SDL_EVENT_PEN_DOWN, SDL_EVENT_PEN_MOTION, SDL_EVENT_PEN_PROXIMITY_IN, SDL_EVENT_PEN_PROXIMITY_OUT, SDL_EVENT_PEN_UP, SDL_EVENT_POLL_SENTINEL, SDL_EVENT_QUIT, SDL_EVENT_RENDER_DEVICE_LOST, SDL_EVENT_RENDER_DEVICE_RESET, SDL_EVENT_RENDER_TARGETS_RESET, SDL_EVENT_SENSOR_UPDATE, SDL_EVENT_SYSTEM_THEME_CHANGED, SDL_EVENT_TERMINATING, SDL_EVENT_TEXT_EDITING, SDL_EVENT_TEXT_EDITING_CANDIDATES, SDL_EVENT_TEXT_INPUT, SDL_EVENT_USER, SDL_EVENT_WILL_ENTER_BACKGROUND, SDL_EVENT_WILL_ENTER_FOREGROUND, SDL_EVENT_WINDOW_CLOSE_REQUESTED, SDL_EVENT_WINDOW_DESTROYED, SDL_EVENT_WINDOW_DISPLAY_CHANGED, SDL_EVENT_WINDOW_DISPLAY_SCALE_CHANGED, SDL_EVENT_WINDOW_ENTER_FULLSCREEN, SDL_EVENT_WINDOW_EXPOSED, SDL_EVENT_WINDOW_FOCUS_GAINED, SDL_EVENT_WINDOW_FOCUS_LOST, SDL_EVENT_WINDOW_HDR_STATE_CHANGED, SDL_EVENT_WINDOW_HIDDEN, SDL_EVENT_WINDOW_HIT_TEST, SDL_EVENT_WINDOW_ICCPROF_CHANGED, SDL_EVENT_WINDOW_LEAVE_FULLSCREEN, SDL_EVENT_WINDOW_MAXIMIZED, SDL_EVENT_WINDOW_METAL_VIEW_RESIZED, SDL_EVENT_WINDOW_MINIMIZED, SDL_EVENT_WINDOW_MOUSE_ENTER, SDL_EVENT_WINDOW_MOUSE_LEAVE, SDL_EVENT_WINDOW_MOVED, SDL_EVENT_WINDOW_OCCLUDED, SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, SDL_EVENT_WINDOW_RESIZED, SDL_EVENT_WINDOW_RESTORED, SDL_EVENT_WINDOW_SAFE_AREA_CHANGED, SDL_EVENT_WINDOW_SHOWN, SDL_MOUSEWHEEL_NORMAL, SDL_PEN_AXIS_COUNT, SDL_RENDEREVENT_CASE, SDL_snprintf(), SDL_strlcpy(), SDL_WINDOWEVENT_CASE, uint, and void().
Referenced by SDL_LogEvent().
SDL_GetEventFilter()
SDL_DECLSPEC bool SDLCALL SDL_GetEventFilter (SDL_EventFilter * filter, void ** userdata) extern
Query the current event filter.
This function can be used to "chain" filters, by saving the existing filter before replacing it with a function that will call that saved filter.
Parameters
filter the current callback function will be stored here.
userdata the pointer that is passed to the current event filter will be stored here.
Returns
true on success or false if there is no event filter set.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetEventFilter
{
    SDL_EventWatcher event_ok;
    SDL_LockMutex(SDL_event_watchers.lock);
    {
        event_ok = SDL_event_watchers.filter;
    }
    SDL_UnlockMutex(SDL_event_watchers.lock);
    if (filter) {
        *filter = event_ok.callback;
    }
    if (userdata) {
        *userdata = event_ok.userdata;
    }
    return event_ok.callback ? true : false;
}
References SDL_EventWatcher::callback, SDL_event_watchers, SDL_LockMutex(), SDL_UnlockMutex(), true, SDL_EventWatcher::userdata, and SDL_MainThreadCallbackEntry::userdata.
SDL_GetWindowFromEvent()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetWindowFromEvent (const SDL_Event * event) extern
Get window associated with an event.
Parameters
event an event containing a windowID.
Returns
the associated window on success or NULL if there is none.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_WaitEvent
SDL_WaitEventTimeout
{
    SDL_WindowID windowID;
    switch (SDL_GetEventCategory(event->type)) {
    case SDL_EVENTCATEGORY_USER:
        windowID = event->user.windowID;
        break;
    case SDL_EVENTCATEGORY_WINDOW:
        windowID = event->window.windowID;
        break;
    case SDL_EVENTCATEGORY_KEY:
        windowID = event->key.windowID;
        break;
    case SDL_EVENTCATEGORY_EDIT:
        windowID = event->edit.windowID;
        break;
    case SDL_EVENTCATEGORY_TEXT:
        windowID = event->text.windowID;
        break;
    case SDL_EVENTCATEGORY_EDIT_CANDIDATES:
        windowID = event->edit_candidates.windowID;
        break;
    case SDL_EVENTCATEGORY_MOTION:
        windowID = event->motion.windowID;
        break;
    case SDL_EVENTCATEGORY_BUTTON:
        windowID = event->button.windowID;
        break;
    case SDL_EVENTCATEGORY_WHEEL:
        windowID = event->wheel.windowID;
        break;
    case SDL_EVENTCATEGORY_TFINGER:
        windowID = event->tfinger.windowID;
        break;
    case SDL_EVENTCATEGORY_PPROXIMITY:
        windowID = event->pproximity.windowID;
        break;
    case SDL_EVENTCATEGORY_PTOUCH:
        windowID = event->ptouch.windowID;
        break;
    case SDL_EVENTCATEGORY_PBUTTON:
        windowID = event->pbutton.windowID;
        break;
    case SDL_EVENTCATEGORY_PMOTION:
        windowID = event->pmotion.windowID;
        break;
    case SDL_EVENTCATEGORY_PAXIS:
        windowID = event->paxis.windowID;
        break;
    case SDL_EVENTCATEGORY_DROP:
        windowID = event->drop.windowID;
        break;
    case SDL_EVENTCATEGORY_RENDER:
        windowID = event->render.windowID;
        break;
    default:
        // < 0  -> invalid event type (error is set by SDL_GetEventCategory)
        // else -> event has no associated window (not an error)
        return NULL;
    }
    return SDL_GetWindowFromID(windowID);
}
References NULL, SDL_EVENTCATEGORY_BUTTON, SDL_EVENTCATEGORY_DROP, SDL_EVENTCATEGORY_EDIT, SDL_EVENTCATEGORY_EDIT_CANDIDATES, SDL_EVENTCATEGORY_KEY, SDL_EVENTCATEGORY_MOTION, SDL_EVENTCATEGORY_PAXIS, SDL_EVENTCATEGORY_PBUTTON, SDL_EVENTCATEGORY_PMOTION, SDL_EVENTCATEGORY_PPROXIMITY, SDL_EVENTCATEGORY_PTOUCH, SDL_EVENTCATEGORY_RENDER, SDL_EVENTCATEGORY_TEXT, SDL_EVENTCATEGORY_TFINGER, SDL_EVENTCATEGORY_USER, SDL_EVENTCATEGORY_WHEEL, SDL_EVENTCATEGORY_WINDOW, SDL_GetEventCategory(), and SDL_GetWindowFromID().
SDL_HasEvent()
SDL_DECLSPEC bool SDLCALL SDL_HasEvent (Uint32 type) extern
Check for the existence of a certain event type in the event queue.
If you need to check for a range of event types, use SDL_HasEvents() instead.
Parameters
type the type of event to be queried; see SDL_EventType for details.
Returns
true if events matching type are present, or false if events matching type are not present.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasEvents
{
    return SDL_HasEvents(type, type);
}
References SDL_HasEvents().
SDL_HasEvents()
SDL_DECLSPEC bool SDLCALL SDL_HasEvents (Uint32 minType, Uint32 maxType) extern
Check for the existence of certain event types in the event queue.
If you need to check for a single event type, use SDL_HasEvent() instead.
Parameters
minType the low end of event type to be queried, inclusive; see SDL_EventType for details.
maxType the high end of event type to be queried, inclusive; see SDL_EventType for details.
Returns
true if events with type >= minType and <= maxType are present, or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasEvents
{
    bool found = false;
    SDL_LockMutex(SDL_EventQ.lock);
    {
        if (SDL_EventQ.active) {
            for (SDL_EventEntry *entry = SDL_EventQ.head; entry; entry = entry->next) {
                const Uint32 type = entry->event.type;
                if (minType <= type && type <= maxType) {
                    found = true;
                    break;
                }
            }
        }
    }
    SDL_UnlockMutex(SDL_EventQ.lock);
    return found;
}
References SDL_EventQ, SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_HasEvent().
SDL_PeepEvents()
SDL_DECLSPEC int SDLCALL SDL_PeepEvents (SDL_Event * events, int numevents, SDL_EventAction action, Uint32 minType, Uint32 maxType) extern
Check the event queue for messages and optionally return them.
action may be any of the following:
SDL_ADDEVENT: up to numevents events will be added to the back of the event queue.
SDL_PEEKEVENT: numevents events at the front of the event queue, within the specified minimum and maximum type, will be returned to the caller and will not be removed from the queue. If you pass NULL for events, then numevents is ignored and the total number of matching events will be returned.
SDL_GETEVENT: up to numevents events at the front of the event queue, within the specified minimum and maximum type, will be returned to the caller and will be removed from the queue.
You may have to call SDL_PumpEvents() before calling this function. Otherwise, the events may not be ready to be filtered when you call SDL_PeepEvents().
Parameters
events destination buffer for the retrieved events, may be NULL to leave the events in the queue and return the number of events that would have been stored.
numevents if action is SDL_ADDEVENT, the number of events to add back to the event queue; if action is SDL_PEEKEVENT or SDL_GETEVENT, the maximum number of events to retrieve.
action action to take; see Remarks for details.
minType minimum value of the event type to be considered; SDL_EVENT_FIRST is a safe choice.
maxType maximum value of the event type to be considered; SDL_EVENT_LAST is a safe choice.
Returns
the number of events actually stored or -1 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_PumpEvents
SDL_PushEvent
{
    return SDL_PeepEventsInternal(events, numevents, action, minType, maxType, false);
}
References SDL_PeepEventsInternal().
Referenced by SDL_DispatchMainCallbackEvents(), SDL_PushEvent(), SDL_WaitEventTimeout_Device(), and SDL_WaitEventTimeoutNS().
SDL_PollEvent()
SDL_DECLSPEC bool SDLCALL SDL_PollEvent (SDL_Event * event) extern
Poll for currently pending events.
If event is not NULL, the next event is removed from the queue and stored in the SDL_Event structure pointed to by event. The 1 returned refers to this event, immediately stored in the SDL Event structure – not an event to follow.
If event is NULL, it simply returns 1 if there is an event in the queue, but will not remove it from the queue.
As this function may implicitly call SDL_PumpEvents(), you can only call this function in the thread that set the video mode.
SDL_PollEvent() is the favored way of receiving system events since it can be done from the main loop and does not suspend the main loop while waiting on an event to be posted.
The common practice is to fully process the event queue once every frame, usually as a first step before updating the game's state:
while (game_is_still_running) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {  // poll until all events are handled!
        // decide what to do with this event.
    }
    // update game state, draw the current frame
}
Parameters
event the SDL_Event structure to be filled with the next event from the queue, or NULL.
Returns
true if this got an event or false if there are none available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PushEvent
SDL_WaitEvent
SDL_WaitEventTimeout
{
    return SDL_WaitEventTimeoutNS(event, 0);
}
References SDL_WaitEventTimeoutNS().
Referenced by CSDLmain::RunL().
SDL_PumpEvents()
SDL_DECLSPEC void SDLCALL SDL_PumpEvents (void) extern
Pump the event loop, gathering events from the input devices.
This function updates the event queue and internal input device state.
SDL_PumpEvents() gathers all the pending input information from devices and places it in the event queue. Without calls to SDL_PumpEvents() no events would ever be placed on the queue. Often the need for calls to SDL_PumpEvents() is hidden from the user since SDL_PollEvent() and SDL_WaitEvent() implicitly call SDL_PumpEvents(). However, if you are not polling or waiting for events (e.g. you are filtering them), then you must call SDL_PumpEvents() to force an event queue update.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_WaitEvent
{
    SDL_PumpEventsInternal(false);
}
References SDL_PumpEventsInternal().
Referenced by EmscriptenInternalMainloop(), CSDLmain::RunL(), SDL_FlushEvents(), and SDL_IterateMainCallbacks().
SDL_PushEvent()
SDL_DECLSPEC bool SDLCALL SDL_PushEvent (SDL_Event * event) extern
Add an event to the event queue.
The event queue can actually be used as a two way communication channel. Not only can events be read from the queue, but the user can also push their own events onto it. event is a pointer to the event structure you wish to push onto the queue. The event is copied into the queue, and the caller may dispose of the memory pointed to after SDL_PushEvent() returns.
Note: Pushing device input events onto the queue doesn't modify the state of the device within SDL.
Note: Events pushed onto the queue with SDL_PushEvent() get passed through the event filter but events added with SDL_PeepEvents() do not.
For pushing application-specific events, please use SDL_RegisterEvents() to get an event type that does not conflict with other code that also wants its own custom event types.
Parameters
event the SDL_Event to be added to the queue.
Returns
true on success, false if the event was filtered or on failure; call SDL_GetError() for more information. A common reason for error is the event queue being full.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PeepEvents
SDL_PollEvent
SDL_RegisterEvents
{
    if (!event->common.timestamp) {
        event->common.timestamp = SDL_GetTicksNS();
    }
    if (!SDL_CallEventWatchers(event)) {
        SDL_ClearError();
        return false;
    }
    if (SDL_PeepEvents(event, 1, SDL_ADDEVENT, 0, 0) <= 0) {
        return false;
    }
    return true;
}
References SDL_ADDEVENT, SDL_CallEventWatchers(), SDL_ClearError(), SDL_GetTicksNS(), and SDL_PeepEvents().
Referenced by SDL_AddKeyboard(), SDL_AddMouse(), SDL_AddPenDevice(), SDL_GamepadEventWatcher(), SDL_PrivateGamepadAdded(), SDL_PrivateGamepadRemapped(), SDL_PrivateGamepadRemoved(), SDL_PrivateJoystickAdded(), SDL_PrivateJoystickRemoved(), SDL_PrivateSendMouseButton(), SDL_PrivateSendMouseMotion(), SDL_PumpEventsInternal(), SDL_RemoveKeyboard(), SDL_RemoveMouse(), SDL_RemovePenDevice(), SDL_SendAppEvent(), SDL_SendClipboardUpdate(), SDL_SendDisplayEvent(), SDL_SendDrop(), SDL_SendEditingText(), SDL_SendEditingTextCandidates(), SDL_SendGamepadAxis(), SDL_SendGamepadButton(), SDL_SendJoystickAxis(), SDL_SendJoystickBall(), SDL_SendJoystickButton(), SDL_SendJoystickHat(), SDL_SendJoystickPowerInfo(), SDL_SendJoystickSensor(), SDL_SendJoystickTouchpad(), SDL_SendKeyboardKeyInternal(), SDL_SendKeyboardText(), SDL_SendMouseWheel(), SDL_SendPenAxis(), SDL_SendPenButton(), SDL_SendPenMotion(), SDL_SendPenTouch(), SDL_SendSensorUpdate(), SDL_SendTouch(), SDL_SendTouchMotion(), SDL_SendWindowEvent(), SDL_UpdateAudio(), SDL_UpdateCamera(), SDL_UpdateJoysticks(), and SendSteamHandleUpdateEvents().
SDL_RegisterEvents()
SDL_DECLSPEC Uint32 SDLCALL SDL_RegisterEvents (int numevents) extern
Allocate a set of user-defined events, and return the beginning event number for that set of events.
Parameters
numevents the number of events to be allocated.
Returns
the beginning event number, or 0 if numevents is invalid or if there are not enough user-defined events left.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PushEvent
{
    Uint32 event_base = 0;
    if (numevents > 0) {
        int value = SDL_AddAtomicInt(&SDL_userevents, numevents);
        if (value >= 0 && value <= (SDL_EVENT_LAST - SDL_EVENT_USER)) {
            event_base = (Uint32)(SDL_EVENT_USER + value);
        }
    }
    return event_base;
}
References SDL_AddAtomicInt(), SDL_EVENT_LAST, SDL_EVENT_USER, and SDL_userevents.
SDL_RemoveEventWatch()
SDL_DECLSPEC void SDLCALL SDL_RemoveEventWatch (SDL_EventFilter filter, void * userdata) extern
Remove an event watch callback added with SDL_AddEventWatch().
This function takes the same input as SDL_AddEventWatch() to identify and delete the corresponding callback.
Parameters
filter the function originally passed to SDL_AddEventWatch().
userdata the pointer originally passed to SDL_AddEventWatch().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddEventWatch
{
    SDL_RemoveEventWatchList(&SDL_event_watchers, filter, userdata);
}
References SDL_event_watchers, SDL_RemoveEventWatchList(), and SDL_MainThreadCallbackEntry::userdata.
Referenced by SDL_QuitGamepads(), and SDL_QuitMainCallbacks().
SDL_SetEventEnabled()
SDL_DECLSPEC void SDLCALL SDL_SetEventEnabled (Uint32 type, bool enabled) extern
Set the state of processing events by type.
Parameters
type the type of event; see SDL_EventType for details.
enabled whether to process the event or not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_EventEnabled
{
    bool current_state;
    Uint8 hi = ((type >> 8) & 0xff);
    Uint8 lo = (type & 0xff);
    if (SDL_disabled_events[hi] &&
        (SDL_disabled_events[hi]->bits[lo / 32] & (1U << (lo & 31)))) {
        current_state = false;
    } else {
        current_state = true;
    }
    if ((enabled != false) != current_state) {
        if (enabled) {
            SDL_assert(SDL_disabled_events[hi] != NULL);
            SDL_disabled_events[hi]->bits[lo / 32] &= ~(1U << (lo & 31));
            // Gamepad events depend on joystick events
            switch (type) {
            case SDL_EVENT_GAMEPAD_ADDED:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_ADDED, true);
                break;
            case SDL_EVENT_GAMEPAD_REMOVED:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_REMOVED, true);
                break;
            case SDL_EVENT_GAMEPAD_AXIS_MOTION:
            case SDL_EVENT_GAMEPAD_BUTTON_DOWN:
            case SDL_EVENT_GAMEPAD_BUTTON_UP:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_AXIS_MOTION, true);
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_HAT_MOTION, true);
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_BUTTON_DOWN, true);
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_BUTTON_UP, true);
                break;
            case SDL_EVENT_GAMEPAD_UPDATE_COMPLETE:
                SDL_SetEventEnabled(SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, true);
                break;
            default:
                break;
            }
        } else {
            // Disable this event type and discard pending events
            if (!SDL_disabled_events[hi]) {
                SDL_disabled_events[hi] = (SDL_DisabledEventBlock *)SDL_calloc(1, sizeof(SDL_DisabledEventBlock));
            }
            // Out of memory, nothing we can do...
            if (SDL_disabled_events[hi]) {
                SDL_disabled_events[hi]->bits[lo / 32] |= (1U << (lo & 31));
                SDL_FlushEvent(type);
            }
        }
        /* turn off drag'n'drop support if we've disabled the events.
           This might change some UI details at the OS level. */
        if (type == SDL_EVENT_DROP_FILE || type == SDL_EVENT_DROP_TEXT) {
            SDL_ToggleDragAndDropSupport();
        }
    }
}
References NULL, SDL_assert, SDL_calloc(), SDL_disabled_events, SDL_EVENT_DROP_FILE, SDL_EVENT_DROP_TEXT, SDL_EVENT_GAMEPAD_ADDED, SDL_EVENT_GAMEPAD_AXIS_MOTION, SDL_EVENT_GAMEPAD_BUTTON_DOWN, SDL_EVENT_GAMEPAD_BUTTON_UP, SDL_EVENT_GAMEPAD_REMOVED, SDL_EVENT_GAMEPAD_UPDATE_COMPLETE, SDL_EVENT_JOYSTICK_ADDED, SDL_EVENT_JOYSTICK_AXIS_MOTION, SDL_EVENT_JOYSTICK_BUTTON_DOWN, SDL_EVENT_JOYSTICK_BUTTON_UP, SDL_EVENT_JOYSTICK_HAT_MOTION, SDL_EVENT_JOYSTICK_REMOVED, SDL_EVENT_JOYSTICK_UPDATE_COMPLETE, SDL_FlushEvent(), SDL_SetEventEnabled(), and SDL_ToggleDragAndDropSupport().
Referenced by SDL_PollSentinelChanged(), SDL_SetEventEnabled(), SDL_SetGamepadEventsEnabled(), and SDL_SetJoystickEventsEnabled().
SDL_SetEventFilter()
SDL_DECLSPEC void SDLCALL SDL_SetEventFilter (SDL_EventFilter filter, void * userdata) extern
Set up a filter to process all events before they are added to the internal event queue.
If you just want to see events without modifying them or preventing them from being queued, you should use SDL_AddEventWatch() instead.
If the filter function returns true when called, then the event will be added to the internal queue. If it returns false, then the event will be dropped from the queue, but the internal state will still be updated. This allows selective filtering of dynamically arriving events.
WARNING: Be very careful of what you do in the event filter function, as it may run in a different thread!
On platforms that support it, if the quit event is generated by an interrupt signal (e.g. pressing Ctrl-C), it will be delivered to the application at the next event poll.
Note: Disabled events never make it to the event filter function; see SDL_SetEventEnabled().
Note: Events pushed onto the queue with SDL_PushEvent() get passed through the event filter, but events pushed onto the queue with SDL_PeepEvents() do not.
Parameters
filter an SDL_EventFilter function to call when an event happens.
userdata a pointer that is passed to filter.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddEventWatch
SDL_SetEventEnabled
SDL_GetEventFilter
SDL_PeepEvents
SDL_PushEvent
{
    SDL_EventEntry *event, *next;
    SDL_LockMutex(SDL_event_watchers.lock);
    {
        // Set filter and discard pending events
        SDL_event_watchers.filter.callback = filter;
        SDL_event_watchers.filter.userdata = userdata;
        if (filter) {
            // Cut all events not accepted by the filter
            SDL_LockMutex(SDL_EventQ.lock);
            {
                for (event = SDL_EventQ.head; event; event = next) {
                    next = event->next;
                    if (!filter(userdata, &event->event)) {
                        SDL_CutEvent(event);
                    }
                }
            }
            SDL_UnlockMutex(SDL_EventQ.lock);
        }
    }
    SDL_UnlockMutex(SDL_event_watchers.lock);
}
References SDL_MainThreadCallbackEntry::next, SDL_CutEvent(), SDL_event_watchers, SDL_EventQ, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_MainThreadCallbackEntry::userdata.
SDL_WaitEvent()
SDL_DECLSPEC bool SDLCALL SDL_WaitEvent (SDL_Event * event) extern
Wait indefinitely for the next available event.
If event is not NULL, the next event is removed from the queue and stored in the SDL_Event structure pointed to by event.
As this function may implicitly call SDL_PumpEvents(), you can only call this function in the thread that initialized the video subsystem.
Parameters
event the SDL_Event structure to be filled in with the next event from the queue, or NULL.
Returns
true on success or false if there was an error while waiting for events; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_PushEvent
SDL_WaitEventTimeout
{
    return SDL_WaitEventTimeoutNS(event, -1);
}
References SDL_WaitEventTimeoutNS().
Referenced by GenericIterateMainCallbacks().
SDL_WaitEventTimeout()
SDL_DECLSPEC bool SDLCALL SDL_WaitEventTimeout (SDL_Event * event, Sint32 timeoutMS) extern
Wait until the specified timeout (in milliseconds) for the next available event.
If event is not NULL, the next event is removed from the queue and stored in the SDL_Event structure pointed to by event.
As this function may implicitly call SDL_PumpEvents(), you can only call this function in the thread that initialized the video subsystem.
The timeout is not guaranteed, the actual wait time could be longer due to system scheduling.
Parameters
event the SDL_Event structure to be filled in with the next event from the queue, or NULL.
timeoutMS the maximum number of milliseconds to wait for the next available event.
Returns
true if this got an event or false if the timeout elapsed without any events available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_PollEvent
SDL_PushEvent
SDL_WaitEvent
{
    Sint64 timeoutNS;
    if (timeoutMS > 0) {
        timeoutNS = SDL_MS_TO_NS(timeoutMS);
    } else {
        timeoutNS = timeoutMS;
    }
    return SDL_WaitEventTimeoutNS(event, timeoutNS);
}
References SDL_MS_TO_NS, and SDL_WaitEventTimeoutNS().