SDL3: SDL-main/src/process/SDL_process.c File Reference
SDL_process.c File Reference
#include "SDL_internal.h"
#include "SDL_sysprocess.h"
Functions
SDL_Process * SDL_CreateProcess (const char *const *args, bool pipe_stdio)
SDL_Process * SDL_CreateProcessWithProperties (SDL_PropertiesID props)
void SDL_DestroyProcess (SDL_Process *process)
SDL_IOStream * SDL_GetProcessInput (SDL_Process *process)
SDL_IOStream * SDL_GetProcessOutput (SDL_Process *process)
SDL_PropertiesID SDL_GetProcessProperties (SDL_Process *process)
bool SDL_KillProcess (SDL_Process *process, bool force)
void * SDL_ReadProcess (SDL_Process *process, size_t *datasize, int *exitcode)
bool SDL_WaitProcess (SDL_Process *process, bool block, int *exitcode)
Function Documentation
SDL_CreateProcess()
SDL_Process * SDL_CreateProcess (const char *const * args, bool pipe_stdio)
Create a new process.
The path to the executable is supplied in args[0]. args[1..N] are additional arguments passed on the command line of the new process, and the argument list should be terminated with a NULL, e.g.:
const char *args[] = { "myprogram", "argument", NULL };
Setting pipe_stdio to true is equivalent to setting SDL_PROP_PROCESS_CREATE_STDIN_NUMBER and SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER to SDL_PROCESS_STDIO_APP, and will allow the use of SDL_ReadProcess() or SDL_GetProcessInput() and SDL_GetProcessOutput().
See SDL_CreateProcessWithProperties() for more details.
Parameters
args the path and arguments for the new process.
pipe_stdio true to create pipes to the process's standard input and from the process's standard output, false for the process to have no input and inherit the application's standard output.
Returns
the newly created and running process, or NULL if the process couldn't be created.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcessWithProperties
SDL_GetProcessProperties
SDL_ReadProcess
SDL_GetProcessInput
SDL_GetProcessOutput
SDL_KillProcess
SDL_WaitProcess
SDL_DestroyProcess
{
    if (!args || !args[0] || !args[0][0]) {
        SDL_InvalidParamError("args");
        return NULL;
    }
    SDL_Process *process;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, (void *)args);
    if (pipe_stdio) {
        SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROCESS_STDIO_APP);
        SDL_SetNumberProperty(props, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_PROCESS_STDIO_APP);
    }
    process = SDL_CreateProcessWithProperties(props);
    SDL_DestroyProperties(props);
    return process;
}
References NULL, SDL_CreateProcessWithProperties(), SDL_CreateProperties(), SDL_DestroyProperties(), SDL_InvalidParamError, SDL_PROCESS_STDIO_APP, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, SDL_PROP_PROCESS_CREATE_STDIN_NUMBER, SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER, SDL_SetNumberProperty(), and SDL_SetPointerProperty().
SDL_CreateProcessWithProperties()
SDL_Process * SDL_CreateProcessWithProperties (SDL_PropertiesID props)
Create a new process with the specified properties.
These are the supported properties:
SDL_PROP_PROCESS_CREATE_ARGS_POINTER: an array of strings containing the program to run, any arguments, and a NULL pointer, e.g. const char *args[] = { "myprogram", "argument", NULL }. This is a required property.
SDL_PROP_PROCESS_CREATE_ENVIRONMENT_POINTER: an SDL_Environment pointer. If this property is set, it will be the entire environment for the process, otherwise the current environment is used.
SDL_PROP_PROCESS_CREATE_WORKING_DIRECTORY_STRING: a UTF-8 encoded string representing the working directory for the process, defaults to the current working directory.
SDL_PROP_PROCESS_CREATE_STDIN_NUMBER: an SDL_ProcessIO value describing where standard input for the process comes from, defaults to SDL_PROCESS_STDIO_NULL.
SDL_PROP_PROCESS_CREATE_STDIN_POINTER: an SDL_IOStream pointer used for standard input when SDL_PROP_PROCESS_CREATE_STDIN_NUMBER is set to SDL_PROCESS_STDIO_REDIRECT.
SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER: an SDL_ProcessIO value describing where standard output for the process goes to, defaults to SDL_PROCESS_STDIO_INHERITED.
SDL_PROP_PROCESS_CREATE_STDOUT_POINTER: an SDL_IOStream pointer used for standard output when SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER is set to SDL_PROCESS_STDIO_REDIRECT.
SDL_PROP_PROCESS_CREATE_STDERR_NUMBER: an SDL_ProcessIO value describing where standard error for the process goes to, defaults to SDL_PROCESS_STDIO_INHERITED.
SDL_PROP_PROCESS_CREATE_STDERR_POINTER: an SDL_IOStream pointer used for standard error when SDL_PROP_PROCESS_CREATE_STDERR_NUMBER is set to SDL_PROCESS_STDIO_REDIRECT.
SDL_PROP_PROCESS_CREATE_STDERR_TO_STDOUT_BOOLEAN: true if the error output of the process should be redirected into the standard output of the process. This property has no effect if SDL_PROP_PROCESS_CREATE_STDERR_NUMBER is set.
SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN: true if the process should run in the background. In this case the default input and output is SDL_PROCESS_STDIO_NULL and the exitcode of the process is not available, and will always be 0.
SDL_PROP_PROCESS_CREATE_CMDLINE_STRING: a string containing the program to run and any parameters. This string is passed directly to CreateProcess on Windows, and does nothing on other platforms. This property is only important if you want to start programs that does non-standard command-line processing, and in most cases using SDL_PROP_PROCESS_CREATE_ARGS_POINTER is sufficient.
On POSIX platforms, wait() and waitpid(-1, ...) should not be called, and SIGCHLD should not be ignored or handled because those would prevent SDL from properly tracking the lifetime of the underlying process. You should use SDL_WaitProcess() instead.
Parameters
props the properties to use.
Returns
the newly created and running process, or NULL if the process couldn't be created.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_GetProcessProperties
SDL_ReadProcess
SDL_GetProcessInput
SDL_GetProcessOutput
SDL_KillProcess
SDL_WaitProcess
SDL_DestroyProcess
{
    const char * const *args = SDL_GetPointerProperty(props, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, NULL);
#if defined(SDL_PLATFORM_WINDOWS)
    const char *cmdline = SDL_GetStringProperty(props, SDL_PROP_PROCESS_CREATE_CMDLINE_STRING, NULL);
    if ((!args || !args[0] || !args[0][0]) && (!cmdline || !cmdline[0])) {
        SDL_SetError("Either SDL_PROP_PROCESS_CREATE_ARGS_POINTER or SDL_PROP_PROCESS_CREATE_CMDLINE_STRING must be valid");
        return NULL;
    }
#else
    if (!args || !args[0] || !args[0][0]) {
        SDL_InvalidParamError("SDL_PROP_PROCESS_CREATE_ARGS_POINTER");
        return NULL;
    }
#endif
    SDL_Process *process = (SDL_Process *)SDL_calloc(1, sizeof(*process));
    if (!process) {
        return NULL;
    }
    process->background = SDL_GetBooleanProperty(props, SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN, false);
    process->props = SDL_CreateProperties();
    if (!process->props) {
        SDL_DestroyProcess(process);
        return NULL;
    }
    SDL_SetBooleanProperty(process->props, SDL_PROP_PROCESS_BACKGROUND_BOOLEAN, process->background);
    if (!SDL_SYS_CreateProcessWithProperties(process, props)) {
        SDL_DestroyProcess(process);
        return NULL;
    }
    process->alive = true;
    return process;
}
References SDL_Process::alive, SDL_Process::background, NULL, SDL_Process::props, SDL_calloc(), SDL_CreateProperties(), SDL_DestroyProcess(), SDL_GetBooleanProperty(), SDL_GetPointerProperty(), SDL_GetStringProperty(), SDL_InvalidParamError, SDL_PROP_PROCESS_BACKGROUND_BOOLEAN, SDL_PROP_PROCESS_CREATE_ARGS_POINTER, SDL_PROP_PROCESS_CREATE_BACKGROUND_BOOLEAN, SDL_PROP_PROCESS_CREATE_CMDLINE_STRING, SDL_SetBooleanProperty(), SDL_SetError(), and SDL_SYS_CreateProcessWithProperties().
Referenced by run_zenity(), SDL_CreateProcess(), SDL_SYS_OpenURL(), and SDL_Zenity_detect().
SDL_DestroyProcess()
void SDL_DestroyProcess (SDL_Process * process)
Destroy a previously created process object.
Note that this does not stop the process, just destroys the SDL object used to track it. If you want to stop the process you should use SDL_KillProcess().
Parameters
process The process object to destroy.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_CreateProcessWithProperties
SDL_KillProcess
{
    if (!process) {
        return;
    }
    // Check to see if the process has exited, will reap zombies on POSIX platforms
    if (process->alive) {
        SDL_WaitProcess(process, false, NULL);
    }
    SDL_SYS_DestroyProcess(process);
    SDL_DestroyProperties(process->props);
    SDL_free(process);
}
References SDL_Process::alive, NULL, SDL_Process::props, SDL_DestroyProperties(), SDL_free(), SDL_SYS_DestroyProcess(), and SDL_WaitProcess().
Referenced by run_zenity(), SDL_CreateProcessWithProperties(), SDL_SYS_OpenURL(), and SDL_Zenity_detect().
SDL_GetProcessInput()
SDL_IOStream * SDL_GetProcessInput (SDL_Process * process)
Get the SDL_IOStream associated with process standard input.
The process must have been created with SDL_CreateProcess() and pipe_stdio set to true, or with SDL_CreateProcessWithProperties() and SDL_PROP_PROCESS_CREATE_STDIN_NUMBER set to SDL_PROCESS_STDIO_APP.
Writing to this stream can return less data than expected if the process hasn't read its input. It may be blocked waiting for its output to be read, if so you may need to call SDL_GetProcessOutput() and read the output in parallel with writing input.
Parameters
process The process to get the input stream for.
Returns
the input stream or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_CreateProcessWithProperties
SDL_GetProcessOutput
{
    if (!process) {
        SDL_InvalidParamError("process");
        return NULL;
    }
    SDL_IOStream *io = (SDL_IOStream *)SDL_GetPointerProperty(process->props, SDL_PROP_PROCESS_STDIN_POINTER, NULL);
    if (!io) {
        SDL_SetError("Process not created with standard input available");
        return NULL;
    }
    return io;
}
References NULL, SDL_Process::props, SDL_GetPointerProperty(), SDL_InvalidParamError, SDL_PROP_PROCESS_STDIN_POINTER, and SDL_SetError().
SDL_GetProcessOutput()
SDL_IOStream * SDL_GetProcessOutput (SDL_Process * process)
Get the SDL_IOStream associated with process standard output.
The process must have been created with SDL_CreateProcess() and pipe_stdio set to true, or with SDL_CreateProcessWithProperties() and SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER set to SDL_PROCESS_STDIO_APP.
Reading from this stream can return 0 with SDL_GetIOStatus() returning SDL_IO_STATUS_NOT_READY if no output is available yet.
Parameters
process The process to get the output stream for.
Returns
the output stream or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_CreateProcessWithProperties
SDL_GetProcessInput
{
    if (!process) {
        SDL_InvalidParamError("process");
        return NULL;
    }
    SDL_IOStream *io = (SDL_IOStream *)SDL_GetPointerProperty(process->props, SDL_PROP_PROCESS_STDOUT_POINTER, NULL);
    if (!io) {
        SDL_SetError("Process not created with standard output available");
        return NULL;
    }
    return io;
}
References NULL, SDL_Process::props, SDL_GetPointerProperty(), SDL_InvalidParamError, SDL_PROP_PROCESS_STDOUT_POINTER, and SDL_SetError().
SDL_GetProcessProperties()
SDL_PropertiesID SDL_GetProcessProperties (SDL_Process * process)
Get the properties associated with a process.
The following read-only properties are provided by SDL:
SDL_PROP_PROCESS_PID_NUMBER: the process ID of the process.
SDL_PROP_PROCESS_STDIN_POINTER: an SDL_IOStream that can be used to write input to the process, if it was created with SDL_PROP_PROCESS_CREATE_STDIN_NUMBER set to SDL_PROCESS_STDIO_APP.
SDL_PROP_PROCESS_STDOUT_POINTER: a non-blocking SDL_IOStream that can be used to read output from the process, if it was created with SDL_PROP_PROCESS_CREATE_STDOUT_NUMBER set to SDL_PROCESS_STDIO_APP.
SDL_PROP_PROCESS_STDERR_POINTER: a non-blocking SDL_IOStream that can be used to read error output from the process, if it was created with SDL_PROP_PROCESS_CREATE_STDERR_NUMBER set to SDL_PROCESS_STDIO_APP.
SDL_PROP_PROCESS_BACKGROUND_BOOLEAN: true if the process is running in the background.
Parameters
process the process to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_CreateProcessWithProperties
{
    if (!process) {
        return SDL_InvalidParamError("process");
    }
    return process->props;
}
References SDL_Process::props, and SDL_InvalidParamError.
SDL_KillProcess()
bool SDL_KillProcess (SDL_Process * process, bool force)
Stop a process.
Parameters
process The process to stop.
force true to terminate the process immediately, false to try to stop the process gracefully. In general you should try to stop the process gracefully first as terminating a process may leave it with half-written data or in some other unstable state.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_CreateProcessWithProperties
SDL_WaitProcess
SDL_DestroyProcess
{
    if (!process) {
        return SDL_InvalidParamError("process");
    }
    if (!process->alive) {
        return SDL_SetError("Process isn't running");
    }
    return SDL_SYS_KillProcess(process, force);
}
References SDL_Process::alive, SDL_InvalidParamError, SDL_SetError(), and SDL_SYS_KillProcess().
SDL_ReadProcess()
void * SDL_ReadProcess (SDL_Process * process, size_t * datasize, int * exitcode)
Read all the output from a process.
If a process was created with I/O enabled, you can use this function to read the output. This function blocks until the process is complete, capturing all output, and providing the process exit code.
The data is allocated with a zero byte at the end (null terminated) for convenience. This extra byte is not included in the value reported via datasize.
The data should be freed with SDL_free().
Parameters
process The process to read.
datasize a pointer filled in with the number of bytes read, may be NULL.
exitcode a pointer filled in with the process exit code if the process has exited, may be NULL.
Returns
the data or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_CreateProcessWithProperties
SDL_DestroyProcess
{
    void *result;
    if (datasize) {
        *datasize = 0;
    }
    if (exitcode) {
        *exitcode = -1;
    }
    if (!process) {
        SDL_InvalidParamError("process");
        return NULL;
    }
    SDL_IOStream *io = (SDL_IOStream *)SDL_GetPointerProperty(process->props, SDL_PROP_PROCESS_STDOUT_POINTER, NULL);
    if (!io) {
        SDL_SetError("Process not created with I/O enabled");
        return NULL;
    }
    result = SDL_LoadFile_IO(io, datasize, false);
    SDL_WaitProcess(process, true, exitcode);
    return result;
}
References NULL, SDL_Process::props, SDL_GetPointerProperty(), SDL_InvalidParamError, SDL_LoadFile_IO(), SDL_PROP_PROCESS_STDOUT_POINTER, SDL_SetError(), and SDL_WaitProcess().
Referenced by run_zenity().
SDL_WaitProcess()
bool SDL_WaitProcess (SDL_Process * process, bool block, int * exitcode)
Wait for a process to finish.
This can be called multiple times to get the status of a process.
The exit code will be the exit code of the process if it terminates normally, a negative signal if it terminated due to a signal, or -255 otherwise. It will not be changed if the process is still running.
If you create a process with standard output piped to the application (pipe_stdio being true) then you should read all of the process output before calling SDL_WaitProcess(). If you don't do this the process might be blocked indefinitely waiting for output to be read and SDL_WaitProcess() will never return true;
Parameters
process The process to wait for.
block If true, block until the process finishes; otherwise, report on the process' status.
exitcode a pointer filled in with the process exit code if the process has exited, may be NULL.
Returns
true if the process exited, false otherwise.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProcess
SDL_CreateProcessWithProperties
SDL_KillProcess
SDL_DestroyProcess
{
    if (!process) {
        return SDL_InvalidParamError("process");
    }
    if (!process->alive) {
        if (exitcode) {
            *exitcode = process->exitcode;
        }
        return true;
    }
    if (SDL_SYS_WaitProcess(process, block, &process->exitcode)) {
        process->alive = false;
        if (exitcode) {
            if (process->background) {
                process->exitcode = 0;
            }
            *exitcode = process->exitcode;
        }
        return true;
    }
    return false;
}
References SDL_Process::alive, SDL_Process::background, SDL_Process::exitcode, SDL_InvalidParamError, and SDL_SYS_WaitProcess().
Referenced by SDL_DestroyProcess(), SDL_ReadProcess(), and SDL_Zenity_detect().