SDL3: SDL-main/src/main/emscripten/SDL_sysmain_callbacks.c File Reference
SDL_sysmain_callbacks.c File Reference
#include "SDL_internal.h"
#include "../SDL_main_callbacks.h"
#include <emscripten.h>
Functions
static void EmscriptenInternalMainloop (void)
static bool SDLCALL EmscriptenMainCallbackEventWatcher (void *userdata, SDL_Event *event)
static void SDLCALL MainCallbackRateHintChanged (void *userdata, const char *name, const char *oldValue, const char *newValue)
int SDL_EnterAppMainCallbacks (int argc, char *argv[], SDL_AppInit_func appinit, SDL_AppIterate_func appiter, SDL_AppEvent_func appevent, SDL_AppQuit_func appquit)
Variables
static bool callback_rate_changed = false
static Uint32 callback_rate_increment = 0
static bool iterate_after_waitevent = false
static bool saw_new_event = false
Function Documentation
EmscriptenInternalMainloop()
void EmscriptenInternalMainloop (void) static
{
    // callback rate changed? Update emscripten's mainloop iteration speed.
    if (callback_rate_changed) {
        callback_rate_changed = false;
        if (callback_rate_increment == 0) {
            emscripten_set_main_loop_timing(EM_TIMING_RAF, 1);
        } else {
            emscripten_set_main_loop_timing(EM_TIMING_SETTIMEOUT, callback_rate_increment);
        }
    }
    if (iterate_after_waitevent) {
        SDL_PumpEvents();
        if (!saw_new_event) {
            // do nothing yet. Note that we're still going to iterate here because we can't block,
            // but we can stop the app's iteration from progressing until there's an event.
            return;
        }
        saw_new_event = false;
    }
    const SDL_AppResult rc = SDL_IterateMainCallbacks(!iterate_after_waitevent);
    if (rc != SDL_APP_CONTINUE) {
        SDL_QuitMainCallbacks(rc);
        emscripten_cancel_main_loop();  // kill" the mainloop, so it stops calling back into it.
        exit((rc == SDL_APP_FAILURE) ? 1 : 0);  // hopefully this takes down everything else, too.
    }
}
References callback_rate_changed, callback_rate_increment, iterate_after_waitevent, saw_new_event, SDL_APP_CONTINUE, SDL_APP_FAILURE, SDL_IterateMainCallbacks(), SDL_PumpEvents(), and SDL_QuitMainCallbacks().
Referenced by SDL_EnterAppMainCallbacks().
EmscriptenMainCallbackEventWatcher()
bool SDLCALL EmscriptenMainCallbackEventWatcher (void * userdata, SDL_Event * event) static
{
    saw_new_event = true;
    return true;
}
References saw_new_event, and SDLCALL.
Referenced by SDL_EnterAppMainCallbacks().
MainCallbackRateHintChanged()
void SDLCALL MainCallbackRateHintChanged (void * userdata, const char * name, const char * oldValue, const char * newValue) static
{
    callback_rate_changed = true;
    iterate_after_waitevent = newValue && (SDL_strcmp(newValue, "waitevent") == 0);
    if (iterate_after_waitevent) {
        callback_rate_increment = 0;
    } else {
        const double callback_rate = newValue ? SDL_atof(newValue) : 0.0;
        if (callback_rate > 0.0) {
            callback_rate_increment = (Uint32) SDL_NS_TO_MS((double) SDL_NS_PER_SECOND / callback_rate);
        } else {
            callback_rate_increment = 0;
        }
    }
}
References callback_rate_changed, callback_rate_increment, iterate_after_waitevent, SDL_atof(), SDL_NS_PER_SECOND, SDL_NS_TO_MS, SDL_strcmp(), and SDLCALL.
Referenced by SDL_EnterAppMainCallbacks().
SDL_EnterAppMainCallbacks()
int SDL_EnterAppMainCallbacks (int argc, char * argv[], SDL_AppInit_func appinit, SDL_AppIterate_func appiter, SDL_AppEvent_func appevent, SDL_AppQuit_func appquit)
An entry point for SDL's use in SDL_MAIN_USE_CALLBACKS.
Generally, you should not call this function directly. This only exists to hand off work into SDL as soon as possible, where it has a lot more control and functionality available, and make the inline code in SDL_main.h as small as possible.
Not all platforms use this, it's actual use is hidden in a magic header-only library, and you should not call this directly unless you really know what you're doing.
Parameters
argc standard Unix main argc.
argv standard Unix main argv.
appinit the application's SDL_AppInit function.
appiter the application's SDL_AppIterate function.
appevent the application's SDL_AppEvent function.
appquit the application's SDL_AppQuit function.
Returns
standard Unix main return value.
Thread Safety
It is not safe to call this anywhere except as the only function call in SDL_main.
Since
This function is available since SDL 3.2.0.
{
    SDL_AppResult rc = SDL_InitMainCallbacks(argc, argv, appinit, appiter, appevent, appquit);
    if (rc == SDL_APP_CONTINUE) {
        if (!SDL_AddEventWatch(EmscriptenMainCallbackEventWatcher, NULL)) {
            rc = SDL_APP_FAILURE;
        } else {
            SDL_AddHintCallback(SDL_HINT_MAIN_CALLBACK_RATE, MainCallbackRateHintChanged, NULL);
            callback_rate_changed = false;
            emscripten_set_main_loop(EmscriptenInternalMainloop, 0, 0);  // don't throw an exception since we do an orderly return.
            if (callback_rate_increment > 0.0) {
                emscripten_set_main_loop_timing(EM_TIMING_SETTIMEOUT, callback_rate_increment);
            }
        }
    } else {
        SDL_QuitMainCallbacks(rc);
    }
    return (rc == SDL_APP_FAILURE) ? 1 : 0;
}
Variable Documentation
callback_rate_changed
bool callback_rate_changed = false static
Referenced by EmscriptenInternalMainloop(), MainCallbackRateHintChanged(), and SDL_EnterAppMainCallbacks().
callback_rate_increment
Uint32 callback_rate_increment = 0 static
Referenced by EmscriptenInternalMainloop(), MainCallbackRateHintChanged(), and SDL_EnterAppMainCallbacks().
iterate_after_waitevent
bool iterate_after_waitevent = false static
Referenced by EmscriptenInternalMainloop(), GenericIterateMainCallbacks(), and MainCallbackRateHintChanged().
saw_new_event
bool saw_new_event = false static
Referenced by EmscriptenInternalMainloop(), and EmscriptenMainCallbackEventWatcher().