SDL3: SDL-main/include/SDL3/SDL_test_font.h File Reference
SDL_test_font.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_rect.h>
#include <SDL3/SDL_render.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDLTest_TextWindow
Macros
#define FONT_LINE_HEIGHT (FONT_CHARACTER_SIZE + 2)
Typedefs
typedef struct SDLTest_TextWindow SDLTest_TextWindow
Functions
void SDLCALL SDLTest_CleanupTextDrawing (void)
bool SDLCALL SDLTest_DrawCharacter (SDL_Renderer *renderer, float x, float y, Uint32 c)
bool SDLCALL SDLTest_DrawString (SDL_Renderer *renderer, float x, float y, const char *s)
void SDLCALL SDLTest_TextWindowAddText (SDLTest_TextWindow *textwin, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
void SDLCALL SDLTest_TextWindowAddTextWithLength (SDLTest_TextWindow *textwin, const char *text, size_t len)
void SDLCALL SDLTest_TextWindowClear (SDLTest_TextWindow *textwin)
SDLTest_TextWindow *SDLCALL SDLTest_TextWindowCreate (float x, float y, float w, float h)
void SDLCALL SDLTest_TextWindowDestroy (SDLTest_TextWindow *textwin)
void SDLCALL SDLTest_TextWindowDisplay (SDLTest_TextWindow *textwin, SDL_Renderer *renderer)
Variables
int FONT_CHARACTER_SIZE
Macro Definition Documentation
FONT_LINE_HEIGHT
#define FONT_LINE_HEIGHT (FONT_CHARACTER_SIZE + 2)
Typedef Documentation
SDLTest_TextWindow
typedef struct SDLTest_TextWindow SDLTest_TextWindow
Function Documentation
SDLTest_CleanupTextDrawing()
void SDLCALL SDLTest_CleanupTextDrawing (void)
References SDLCALL, and SDLTest_CleanupTextDrawing().
Referenced by SDLTest_CleanupTextDrawing().
SDLTest_DrawCharacter()
bool SDLCALL SDLTest_DrawCharacter (SDL_Renderer * renderer, float x, float y, Uint32 c)
References SDLCALL.
SDLTest_DrawString()
bool SDLCALL SDLTest_DrawString (SDL_Renderer * renderer, float x, float y, const char * s)
References SDLCALL.
SDLTest_TextWindowAddText()
void SDLCALL SDLTest_TextWindowAddText (SDLTest_TextWindow * textwin, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
References SDL_PRINTF_FORMAT_STRING, SDL_PRINTF_VARARG_FUNC, and SDLCALL.
SDLTest_TextWindowAddTextWithLength()
void SDLCALL SDLTest_TextWindowAddTextWithLength (SDLTest_TextWindow * textwin, const char * text, size_t len)
References SDLCALL, and SDLTest_TextWindowAddTextWithLength().
Referenced by SDLTest_TextWindowAddTextWithLength().
SDLTest_TextWindowClear()
void SDLCALL SDLTest_TextWindowClear (SDLTest_TextWindow * textwin)
References SDLCALL, and SDLTest_TextWindowClear().
Referenced by SDLTest_TextWindowClear().
SDLTest_TextWindowCreate()
SDLTest_TextWindow *SDLCALL SDLTest_TextWindowCreate (float x, float y, float w, float h)
References SDLCALL.
SDLTest_TextWindowDestroy()
void SDLCALL SDLTest_TextWindowDestroy (SDLTest_TextWindow * textwin)
References SDLCALL, and SDLTest_TextWindowDestroy().
Referenced by SDLTest_TextWindowDestroy().
SDLTest_TextWindowDisplay()
void SDLCALL SDLTest_TextWindowDisplay (SDLTest_TextWindow * textwin, SDL_Renderer * renderer)
References SDLCALL.
Variable Documentation
FONT_CHARACTER_SIZE
int FONT_CHARACTER_SIZE extern