SDL3: SDL-main/src/thread/SDL_systhread.h File Reference
SDL_systhread.h File Reference
#include "SDL_internal.h"
#include "SDL_thread_c.h"
Functions
SDL_Thread * SDL_CreateThreadWithStackSize (SDL_ThreadFunction fn, const char *name, size_t stacksize, void *data)
bool SDL_SYS_CreateThread (SDL_Thread *thread, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
void SDL_SYS_DetachThread (SDL_Thread *thread)
SDL_TLSData * SDL_SYS_GetTLSData (void)
void SDL_SYS_InitTLSData (void)
void SDL_SYS_QuitTLSData (void)
bool SDL_SYS_SetThreadPriority (SDL_ThreadPriority priority)
bool SDL_SYS_SetTLSData (SDL_TLSData *data)
void SDL_SYS_SetupThread (const char *name)
void SDL_SYS_WaitThread (SDL_Thread *thread)
Function Documentation
SDL_CreateThreadWithStackSize()
SDL_Thread * SDL_CreateThreadWithStackSize (SDL_ThreadFunction fn, const char * name, size_t stacksize, void * data) extern
{
    const SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, (void *) fn);
    SDL_SetStringProperty(props, SDL_PROP_THREAD_CREATE_NAME_STRING, name);
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, userdata);
    SDL_SetNumberProperty(props, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, (Sint64) stacksize);
    SDL_Thread *thread = SDL_CreateThreadWithProperties(props);
    SDL_DestroyProperties(props);
    return thread;
}
References SDL_CreateProperties(), SDL_CreateThreadWithProperties, SDL_DestroyProperties(), SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, SDL_PROP_THREAD_CREATE_NAME_STRING, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_SetStringProperty(), and SDL_TLSEntry::thread.
SDL_SYS_CreateThread()
bool SDL_SYS_CreateThread (SDL_Thread * thread, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread) extern
{
    return SDL_SetError("Threads are not supported on this platform");
}
References SDL_Thread::handle, RunThread(), SDL_SetError(), and SDL_Thread::stacksize.
Referenced by SDL_CreateThreadWithPropertiesRuntime().
SDL_SYS_DetachThread()
void SDL_SYS_DetachThread (SDL_Thread * thread) extern
{
    return;
}
References SDL_Thread::handle.
Referenced by SDL_DetachThread().
SDL_SYS_GetTLSData()
SDL_TLSData * SDL_SYS_GetTLSData (void) extern
{
    return SDL_Generic_GetTLSData();
}
References generic_local_storage, INVALID_PTHREAD_KEY, NULL, SDL_Generic_GetTLSData(), and thread_local_storage.
Referenced by SDL_CleanupTLS(), SDL_GetTLS(), and SDL_SetTLS().
SDL_SYS_InitTLSData()
void SDL_SYS_InitTLSData (void) extern
{
    SDL_Generic_InitTLSData();
}
References generic_local_storage, INVALID_PTHREAD_KEY, NULL, SDL_Generic_InitTLSData(), and thread_local_storage.
Referenced by SDL_InitTLSData().
SDL_SYS_QuitTLSData()
void SDL_SYS_QuitTLSData (void) extern
{
    SDL_Generic_QuitTLSData();
}
References generic_local_storage, INVALID_PTHREAD_KEY, SDL_Generic_QuitTLSData(), and thread_local_storage.
Referenced by SDL_QuitTLSData().
SDL_SYS_SetThreadPriority()
bool SDL_SYS_SetThreadPriority (SDL_ThreadPriority priority) extern
{
    return true;
}
References SDL_GetHint(), SDL_GetHintBoolean(), SDL_HINT_THREAD_FORCE_REALTIME_TIME_CRITICAL, SDL_HINT_THREAD_PRIORITY_POLICY, SDL_SetError(), SDL_SetLinuxThreadPriorityAndPolicy(), SDL_strcmp(), SDL_THREAD_PRIORITY_HIGH, SDL_THREAD_PRIORITY_LOW, SDL_THREAD_PRIORITY_NORMAL, and SDL_THREAD_PRIORITY_TIME_CRITICAL.
Referenced by SDL_SetCurrentThreadPriority().
SDL_SYS_SetTLSData()
bool SDL_SYS_SetTLSData (SDL_TLSData * data) extern
{
    return SDL_Generic_SetTLSData(data);
}
References generic_local_storage, SDL_Generic_SetTLSData(), SDL_SetError(), and thread_local_storage.
Referenced by SDL_CleanupTLS(), and SDL_SetTLS().
SDL_SYS_SetupThread()
void SDL_SYS_SetupThread (const char * name) extern
{
    return;
}
References NULL, SDL_assert, and SDL_strlcpy().
Referenced by SDL_RunThread().
SDL_SYS_WaitThread()
void SDL_SYS_WaitThread (SDL_Thread * thread) extern
{
    return;
}
References SDL_Thread::handle.
Referenced by SDL_WaitThread().