SDL3: SDL-main/src/SDL_properties.c File Reference
SDL_properties.c File Reference
#include "SDL_internal.h"
#include "SDL_hints_c.h"
#include "SDL_properties_c.h"
Data Structures
struct CopyOnePropertyData
struct EnumerateOnePropertyData
struct SDL_Properties
struct SDL_Property
Typedefs
typedef struct CopyOnePropertyData CopyOnePropertyData
typedef struct EnumerateOnePropertyData EnumerateOnePropertyData
Functions
static void SDLCALL CleanupFreeableProperty (void *userdata, void *value)
static void SDLCALL CleanupSurface (void *userdata, void *value)
static bool SDLCALL CopyOneProperty (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
static bool SDLCALL EnumerateOneProperty (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
static bool SDLCALL FreeOneProperties (void *userdata, const SDL_HashTable *table, const void *key, const void *value)
static bool SDL_CheckInitProperties (void)
bool SDL_ClearProperty (SDL_PropertiesID props, const char *name)
bool SDL_CopyProperties (SDL_PropertiesID src, SDL_PropertiesID dst)
SDL_PropertiesID SDL_CreateProperties (void)
void SDL_DestroyProperties (SDL_PropertiesID props)
bool SDL_DumpProperties (SDL_PropertiesID props)
static void SDLCALL SDL_DumpPropertiesCallback (void *userdata, SDL_PropertiesID props, const char *name)
bool SDL_EnumerateProperties (SDL_PropertiesID props, SDL_EnumeratePropertiesCallback callback, void *userdata)
static void SDL_FreeProperties (SDL_Properties *properties)
static void SDLCALL SDL_FreeProperty (void *data, const void *key, const void *value)
static void SDL_FreePropertyWithCleanup (const void *key, const void *value, void *data, bool cleanup)
bool SDL_GetBooleanProperty (SDL_PropertiesID props, const char *name, bool default_value)
float SDL_GetFloatProperty (SDL_PropertiesID props, const char *name, float default_value)
SDL_PropertiesID SDL_GetGlobalProperties (void)
Sint64 SDL_GetNumberProperty (SDL_PropertiesID props, const char *name, Sint64 default_value)
void * SDL_GetPointerProperty (SDL_PropertiesID props, const char *name, void *default_value)
SDL_PropertyType SDL_GetPropertyType (SDL_PropertiesID props, const char *name)
const char * SDL_GetStringProperty (SDL_PropertiesID props, const char *name, const char *default_value)
bool SDL_HasProperty (SDL_PropertiesID props, const char *name)
bool SDL_InitProperties (void)
bool SDL_LockProperties (SDL_PropertiesID props)
static bool SDL_PrivateSetProperty (SDL_PropertiesID props, const char *name, SDL_Property *property)
void SDL_QuitProperties (void)
bool SDL_SetBooleanProperty (SDL_PropertiesID props, const char *name, bool value)
bool SDL_SetFloatProperty (SDL_PropertiesID props, const char *name, float value)
bool SDL_SetFreeableProperty (SDL_PropertiesID props, const char *name, void *value)
bool SDL_SetNumberProperty (SDL_PropertiesID props, const char *name, Sint64 value)
bool SDL_SetPointerProperty (SDL_PropertiesID props, const char *name, void *value)
bool SDL_SetPointerPropertyWithCleanup (SDL_PropertiesID props, const char *name, void *value, SDL_CleanupPropertyCallback cleanup, void *userdata)
bool SDL_SetStringProperty (SDL_PropertiesID props, const char *name, const char *value)
bool SDL_SetSurfaceProperty (SDL_PropertiesID props, const char *name, SDL_Surface *surface)
void SDL_UnlockProperties (SDL_PropertiesID props)
Variables
static SDL_AtomicU32 SDL_global_properties
static SDL_AtomicU32 SDL_last_properties_id
static SDL_HashTable * SDL_properties
static SDL_InitState SDL_properties_init
Typedef Documentation
CopyOnePropertyData
typedef struct CopyOnePropertyData CopyOnePropertyData
EnumerateOnePropertyData
typedef struct EnumerateOnePropertyData EnumerateOnePropertyData
Function Documentation
CleanupFreeableProperty()
void SDLCALL CleanupFreeableProperty (void * userdata, void * value) static
{
    SDL_free(value);
}
References SDL_free(), and SDLCALL.
Referenced by SDL_SetFreeableProperty().
CleanupSurface()
void SDLCALL CleanupSurface (void * userdata, void * value) static
{
    SDL_Surface *surface = (SDL_Surface *)value;
    SDL_DestroySurface(surface);
}
References SDL_DestroySurface(), and SDLCALL.
Referenced by SDL_SetSurfaceProperty().
CopyOneProperty()
bool SDLCALL CopyOneProperty (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    const SDL_Property *src_property = (const SDL_Property *)value;
    if (src_property->cleanup) {
        // Can't copy properties with cleanup functions, we don't know how to duplicate the data
        return true;  // keep iterating.
    }
    CopyOnePropertyData *data = (CopyOnePropertyData *) userdata;
    SDL_Properties *dst_properties = data->dst_properties;
    const char *src_name = (const char *)key;
    SDL_Property *dst_property;
    char *dst_name = SDL_strdup(src_name);
    if (!dst_name) {
        data->result = false;
        return true; // keep iterating (I guess...?)
    }
    dst_property = (SDL_Property *)SDL_malloc(sizeof(*dst_property));
    if (!dst_property) {
        SDL_free(dst_name);
        data->result = false;
        return true; // keep iterating (I guess...?)
    }
    SDL_copyp(dst_property, src_property);
    if (src_property->type == SDL_PROPERTY_TYPE_STRING) {
        dst_property->value.string_value = SDL_strdup(src_property->value.string_value);
        if (!dst_property->value.string_value) {
            SDL_free(dst_name);
            SDL_free(dst_property);
            data->result = false;
            return true; // keep iterating (I guess...?)
        }
    }
    if (!SDL_InsertIntoHashTable(dst_properties->props, dst_name, dst_property, true)) {
        SDL_FreePropertyWithCleanup(dst_name, dst_property, NULL, false);
        data->result = false;
    }
    return true;  // keep iterating.
}
References SDL_Property::cleanup, NULL, SDL_Properties::props, SDL_copyp, SDL_free(), SDL_FreePropertyWithCleanup(), SDL_InsertIntoHashTable(), SDL_malloc(), SDL_PROPERTY_TYPE_STRING, SDL_strdup(), SDLCALL, SDL_Property::string_value, SDL_Property::type, and SDL_Property::value.
Referenced by SDL_CopyProperties().
EnumerateOneProperty()
bool SDLCALL EnumerateOneProperty (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    (void) table;
    (void) value;
    const EnumerateOnePropertyData *data = (const EnumerateOnePropertyData *) userdata;
    data->callback(data->userdata, data->props, (const char *)key);
    return true;  // keep iterating.
}
References SDLCALL, and void().
Referenced by SDL_EnumerateProperties().
FreeOneProperties()
bool SDLCALL FreeOneProperties (void * userdata, const SDL_HashTable * table, const void * key, const void * value) static
{
    SDL_FreeProperties((SDL_Properties *)value);
    return true;  // keep iterating.
}
References SDL_FreeProperties(), and SDLCALL.
Referenced by SDL_QuitProperties().
SDL_CheckInitProperties()
bool SDL_CheckInitProperties (void) static
{
    return SDL_InitProperties();
}
References SDL_InitProperties().
Referenced by SDL_CreateProperties().
SDL_ClearProperty()
bool SDL_ClearProperty (SDL_PropertiesID props, const char * name)
Clear a property from a group of properties.
Parameters
props the properties to modify.
name the name of the property to clear.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return SDL_PrivateSetProperty(props, name, NULL);
}
References NULL, and SDL_PrivateSetProperty().
Referenced by SDL_DestroyRendererWithoutFreeing(), SDL_DestroyWindowTexture(), SDL_GetDisplayForWindow(), SDL_SetPointerProperty(), SDL_SetPointerPropertyWithCleanup(), and SDL_SetStringProperty().
SDL_CopyProperties()
bool SDL_CopyProperties (SDL_PropertiesID src, SDL_PropertiesID dst)
Copy a group of properties.
Copy all the properties from one group of properties to another, with the exception of properties requiring cleanup (set using SDL_SetPointerPropertyWithCleanup()), which will not be copied. Any property that already exists on dst will be overwritten.
Parameters
src the properties to copy.
dst the destination properties.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread. This function acquires simultaneous mutex locks on both the source and destination property sets.
Since
This function is available since SDL 3.2.0.
{
    if (!src) {
        return SDL_InvalidParamError("src");
    }
    if (!dst) {
        return SDL_InvalidParamError("dst");
    }
    SDL_Properties *src_properties = NULL;
    SDL_Properties *dst_properties = NULL;
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)src, (const void **)&src_properties);
    if (!src_properties) {
        return SDL_InvalidParamError("src");
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)dst, (const void **)&dst_properties);
    if (!dst_properties) {
        return SDL_InvalidParamError("dst");
    }
    bool result = true;
    SDL_LockMutex(src_properties->lock);
    SDL_LockMutex(dst_properties->lock);
    {
        CopyOnePropertyData data = { dst_properties, true };
        SDL_IterateHashTable(src_properties->props, CopyOneProperty, &data);
        result = data.result;
    }
    SDL_UnlockMutex(dst_properties->lock);
    SDL_UnlockMutex(src_properties->lock);
    return result;
}
References CopyOneProperty(), SDL_Properties::lock, NULL, SDL_Properties::props, SDL_FindInHashTable(), SDL_InvalidParamError, SDL_IterateHashTable(), SDL_LockMutex(), SDL_properties, and SDL_UnlockMutex().
Referenced by SDL_InitializeSurface(), and SDL_StartTextInputWithProperties().
SDL_CreateProperties()
SDL_PropertiesID SDL_CreateProperties (void)
Create a group of properties.
All properties are automatically destroyed when SDL_Quit() is called.
Returns
an ID for a new group of properties, or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyProperties
{
    if (!SDL_CheckInitProperties()) {
        return 0;
    }
    SDL_Properties *properties = (SDL_Properties *)SDL_calloc(1, sizeof(*properties));
    if (!properties) {
        return 0;
    }
    properties->lock = SDL_CreateMutex();
    if (!properties->lock) {
        SDL_free(properties);
        return 0;
    }
    properties->props = SDL_CreateHashTable(0, false, SDL_HashString, SDL_KeyMatchString, SDL_FreeProperty, NULL);
    if (!properties->props) {
        SDL_DestroyMutex(properties->lock);
        SDL_free(properties);
        return 0;
    }
    SDL_PropertiesID props = 0;
    while (true) {
        props = (SDL_GetAtomicU32(&SDL_last_properties_id) + 1);
        if (props == 0) {
            continue;
        } else if (SDL_CompareAndSwapAtomicU32(&SDL_last_properties_id, props - 1, props)) {
            break;
        }
    }
    SDL_assert(!SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, NULL));  // should NOT be in the hash table already.
    if (!SDL_InsertIntoHashTable(SDL_properties, (const void *)(uintptr_t)props, properties, false)) {
        SDL_FreeProperties(properties);
        return 0;
    }
    return props;  // All done!
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_assert, SDL_calloc(), SDL_CheckInitProperties(), SDL_CompareAndSwapAtomicU32(), SDL_CreateHashTable(), SDL_CreateMutex(), SDL_DestroyMutex(), SDL_FindInHashTable(), SDL_free(), SDL_FreeProperties(), SDL_FreeProperty(), SDL_GetAtomicU32(), SDL_HashString(), SDL_InsertIntoHashTable(), SDL_KeyMatchString(), SDL_last_properties_id, and SDL_properties.
Referenced by GetHintProperties(), run_zenity(), SDL_CreateGPUDevice(), SDL_CreateGPURenderer(), SDL_CreatePopupWindow(), SDL_CreateProcess(), SDL_CreateProcessWithProperties(), SDL_CreateRenderer(), SDL_CreateSoftwareRenderer(), SDL_CreateTexture(), SDL_CreateTextureFromSurface(), SDL_CreateTextureWithProperties(), SDL_CreateThreadRuntime(), SDL_CreateThreadWithStackSize(), SDL_CreateWindow(), SDL_GetAudioStreamProperties(), SDL_GetCameraProperties(), SDL_GetDisplayProperties(), SDL_GetGlobalProperties(), SDL_GetIOProperties(), SDL_GetJoystickProperties(), SDL_GetRendererProperties(), SDL_GetSensorProperties(), SDL_GetSurfaceProperties(), SDL_GetTextureProperties(), SDL_GetWindowProperties(), SDL_GPUSupportsShaderFormats(), SDL_ShowOpenFileDialog(), SDL_ShowOpenFolderDialog(), SDL_ShowSaveFileDialog(), SDL_StartTextInputWithProperties(), SDL_SYS_OpenURL(), and SDL_Zenity_detect().
SDL_DestroyProperties()
void SDL_DestroyProperties (SDL_PropertiesID props)
Destroy a group of properties.
All properties are deleted and their cleanup functions will be called, if any.
Parameters
props the properties to destroy.
Thread Safety
This function should not be called while these properties are locked or other threads might be setting or getting values from these properties.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProperties
{
    if (props) {
        // this can't just use RemoveFromHashTable with SDL_FreeProperties as the destructor, because
        //  other destructors under this might cause use to attempt a recursive lock on SDL_properties,
        //  which isn't allowed with rwlocks. So manually look it up and remove/free it.
        SDL_Properties *properties = NULL;
        if (SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties)) {
            SDL_FreeProperties(properties);
            SDL_RemoveFromHashTable(SDL_properties, (const void *)(uintptr_t)props);
        }
    }
}
References NULL, SDL_FindInHashTable(), SDL_FreeProperties(), SDL_properties, and SDL_RemoveFromHashTable().
Referenced by ClosePhysicalCamera(), GetHintProperties(), run_zenity(), SDL_CloseIO(), SDL_CloseJoystick(), SDL_CloseSensor(), SDL_CreateGPUDevice(), SDL_CreateGPURenderer(), SDL_CreatePopupWindow(), SDL_CreateProcess(), SDL_CreateRenderer(), SDL_CreateSoftwareRenderer(), SDL_CreateTexture(), SDL_CreateTextureFromSurface(), SDL_CreateTextureWithProperties(), SDL_CreateThreadRuntime(), SDL_CreateThreadWithStackSize(), SDL_CreateWindow(), SDL_DelVideoDisplay(), SDL_DestroyAudioStream(), SDL_DestroyProcess(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroySurface(), SDL_DestroyTextureInternal(), SDL_DestroyWindow(), SDL_GetGlobalProperties(), SDL_GPUSupportsShaderFormats(), SDL_QuitHints(), SDL_QuitProperties(), SDL_ShowOpenFileDialog(), SDL_ShowOpenFolderDialog(), SDL_ShowSaveFileDialog(), SDL_StartTextInputWithProperties(), SDL_SYS_OpenURL(), and SDL_Zenity_detect().
SDL_DumpProperties()
bool SDL_DumpProperties (SDL_PropertiesID props)
{
    return SDL_EnumerateProperties(props, SDL_DumpPropertiesCallback, NULL);
}
References NULL, SDL_DumpPropertiesCallback(), and SDL_EnumerateProperties().
SDL_DumpPropertiesCallback()
void SDLCALL SDL_DumpPropertiesCallback (void * userdata, SDL_PropertiesID props, const char * name) static
{
    switch (SDL_GetPropertyType(props, name)) {
    case SDL_PROPERTY_TYPE_POINTER:
        SDL_Log("%s: %p", name, SDL_GetPointerProperty(props, name, NULL));
        break;
    case SDL_PROPERTY_TYPE_STRING:
        SDL_Log("%s: \"%s\"", name, SDL_GetStringProperty(props, name, ""));
        break;
    case SDL_PROPERTY_TYPE_NUMBER:
        {
            Sint64 value = SDL_GetNumberProperty(props, name, 0);
            SDL_Log("%s: %" SDL_PRIs64 " (%" SDL_PRIx64 ")", name, value, value);
        }
        break;
    case SDL_PROPERTY_TYPE_FLOAT:
        SDL_Log("%s: %g", name, SDL_GetFloatProperty(props, name, 0.0f));
        break;
    case SDL_PROPERTY_TYPE_BOOLEAN:
        SDL_Log("%s: %s", name, SDL_GetBooleanProperty(props, name, false) ? "true" : "false");
        break;
    default:
        SDL_Log("%s UNKNOWN TYPE", name);
        break;
    }
}
References NULL, SDL_GetBooleanProperty(), SDL_GetFloatProperty(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetStringProperty(), SDL_Log(), SDL_PRIs64, SDL_PRIx64, SDL_PROPERTY_TYPE_BOOLEAN, SDL_PROPERTY_TYPE_FLOAT, SDL_PROPERTY_TYPE_NUMBER, SDL_PROPERTY_TYPE_POINTER, SDL_PROPERTY_TYPE_STRING, and SDLCALL.
Referenced by SDL_DumpProperties().
SDL_EnumerateProperties()
bool SDL_EnumerateProperties (SDL_PropertiesID props, SDL_EnumeratePropertiesCallback callback, void * userdata)
Enumerate the properties contained in a group of properties.
The callback function is called for each property in the group of properties. The properties are locked during enumeration.
Parameters
props the properties to query.
callback the function to call for each property.
userdata a pointer that is passed to callback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_Properties *properties = NULL;
    if (!props) {
        return SDL_InvalidParamError("props");
    }
    if (!callback) {
        return SDL_InvalidParamError("callback");
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return SDL_InvalidParamError("props");
    }
    SDL_LockMutex(properties->lock);
    {
        EnumerateOnePropertyData data = { callback, userdata, props };
        SDL_IterateHashTable(properties->props, EnumerateOneProperty, &data);
    }
    SDL_UnlockMutex(properties->lock);
    return true;
}
References EnumerateOneProperty(), SDL_Properties::lock, NULL, SDL_Properties::props, SDL_FindInHashTable(), SDL_InvalidParamError, SDL_IterateHashTable(), SDL_LockMutex(), SDL_properties, and SDL_UnlockMutex().
Referenced by SDL_DumpProperties(), and SDL_ResetHints().
SDL_FreeProperties()
void SDL_FreeProperties (SDL_Properties * properties) static
{
    if (properties) {
        SDL_DestroyHashTable(properties->props);
        SDL_DestroyMutex(properties->lock);
        SDL_free(properties);
    }
}
References SDL_Properties::lock, SDL_Properties::props, SDL_DestroyHashTable(), SDL_DestroyMutex(), and SDL_free().
Referenced by FreeOneProperties(), SDL_CreateProperties(), and SDL_DestroyProperties().
SDL_FreeProperty()
void SDLCALL SDL_FreeProperty (void * data, const void * key, const void * value) static
{
    SDL_FreePropertyWithCleanup(key, value, data, true);
}
References SDL_FreePropertyWithCleanup(), and SDLCALL.
Referenced by SDL_CreateProperties().
SDL_FreePropertyWithCleanup()
void SDL_FreePropertyWithCleanup (const void * key, const void * value, void * data, bool cleanup) static
{
    SDL_Property *property = (SDL_Property *)value;
    if (property) {
        switch (property->type) {
        case SDL_PROPERTY_TYPE_POINTER:
            if (property->cleanup && cleanup) {
                property->cleanup(property->userdata, property->value.pointer_value);
            }
            break;
        case SDL_PROPERTY_TYPE_STRING:
            SDL_free(property->value.string_value);
            break;
        default:
            break;
        }
        SDL_free(property->string_storage);
    }
    SDL_free((void *)key);
    SDL_free((void *)value);
}
References SDL_free(), SDL_PROPERTY_TYPE_POINTER, and SDL_PROPERTY_TYPE_STRING.
Referenced by CopyOneProperty(), SDL_FreeProperty(), SDL_PrivateSetProperty(), and SDL_SetPointerPropertyWithCleanup().
SDL_GetBooleanProperty()
bool SDL_GetBooleanProperty (SDL_PropertiesID props, const char * name, bool default_value)
Get a boolean property from a group of properties.
You can use SDL_GetPropertyType() to query whether the property exists and is a boolean property.
Parameters
props the properties to query.
name the name of the property to query.
default_value the default value of the property.
Returns
the value of the property, or default_value if it is not set or not a boolean property.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPropertyType
SDL_HasProperty
SDL_SetBooleanProperty
{
    SDL_Properties *properties = NULL;
    bool value = default_value ? true : false;
    if (!props) {
        return value;
    }
    if (!name || !*name) {
        return value;
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return value;
    }
    SDL_LockMutex(properties->lock);
    {
        SDL_Property *property = NULL;
        if (SDL_FindInHashTable(properties->props, name, (const void **)&property)) {
            switch (property->type) {
            case SDL_PROPERTY_TYPE_STRING:
                value = SDL_GetStringBoolean(property->value.string_value, default_value);
                break;
            case SDL_PROPERTY_TYPE_NUMBER:
                value = (property->value.number_value != 0);
                break;
            case SDL_PROPERTY_TYPE_FLOAT:
                value = (property->value.float_value != 0.0f);
                break;
            case SDL_PROPERTY_TYPE_BOOLEAN:
                value = property->value.boolean_value;
                break;
            default:
                break;
            }
        }
    }
    SDL_UnlockMutex(properties->lock);
    return value;
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_FindInHashTable(), SDL_GetStringBoolean(), SDL_LockMutex(), SDL_properties, SDL_PROPERTY_TYPE_BOOLEAN, SDL_PROPERTY_TYPE_FLOAT, SDL_PROPERTY_TYPE_NUMBER, SDL_PROPERTY_TYPE_STRING, SDL_UnlockMutex(), and true.
Referenced by create_zenity_args(), SDL_CreateGPUDeviceWithProperties(), SDL_CreateProcessWithProperties(), SDL_CreateWindowWithProperties(), SDL_DumpPropertiesCallback(), SDL_GetTextInputAutocorrect(), SDL_GetTextInputMultiline(), SDL_GetWindowFlagProperties(), SDL_QuitAudio(), and SDL_SYS_ShowFileDialogWithProperties().
SDL_GetFloatProperty()
float SDL_GetFloatProperty (SDL_PropertiesID props, const char * name, float default_value)
Get a floating point property from a group of properties.
You can use SDL_GetPropertyType() to query whether the property exists and is a floating point property.
Parameters
props the properties to query.
name the name of the property to query.
default_value the default value of the property.
Returns
the value of the property, or default_value if it is not set or not a float property.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPropertyType
SDL_HasProperty
SDL_SetFloatProperty
{
    SDL_Properties *properties = NULL;
    float value = default_value;
    if (!props) {
        return value;
    }
    if (!name || !*name) {
        return value;
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return value;
    }
    SDL_LockMutex(properties->lock);
    {
        SDL_Property *property = NULL;
        if (SDL_FindInHashTable(properties->props, name, (const void **)&property)) {
            switch (property->type) {
            case SDL_PROPERTY_TYPE_STRING:
                value = (float)SDL_atof(property->value.string_value);
                break;
            case SDL_PROPERTY_TYPE_NUMBER:
                value = (float)property->value.number_value;
                break;
            case SDL_PROPERTY_TYPE_FLOAT:
                value = property->value.float_value;
                break;
            case SDL_PROPERTY_TYPE_BOOLEAN:
                value = (float)property->value.boolean_value;
                break;
            default:
                break;
            }
        }
    }
    SDL_UnlockMutex(properties->lock);
    return value;
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_atof(), SDL_FindInHashTable(), SDL_LockMutex(), SDL_properties, SDL_PROPERTY_TYPE_BOOLEAN, SDL_PROPERTY_TYPE_FLOAT, SDL_PROPERTY_TYPE_NUMBER, SDL_PROPERTY_TYPE_STRING, and SDL_UnlockMutex().
Referenced by SDL_CreateTextureWithProperties(), SDL_DumpPropertiesCallback(), SDL_GetSurfaceHDRHeadroom(), SDL_GetSurfaceSDRWhitePoint(), and UpdateHDRProperties().
SDL_GetGlobalProperties()
SDL_PropertiesID SDL_GetGlobalProperties (void)
Get the global SDL properties.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID props = SDL_GetAtomicU32(&SDL_global_properties);
    if (!props) {
        props = SDL_CreateProperties();
        if (!SDL_CompareAndSwapAtomicU32(&SDL_global_properties, 0, props)) {
            // Somebody else created global properties before us, just use those
            SDL_DestroyProperties(props);
            props = SDL_GetAtomicU32(&SDL_global_properties);
        }
    }
    return props;
}
References SDL_CompareAndSwapAtomicU32(), SDL_CreateProperties(), SDL_DestroyProperties(), SDL_GetAtomicU32(), and SDL_global_properties.
Referenced by SDL_GetAppMetadataProperty(), and SDL_SetAppMetadataProperty().
SDL_GetNumberProperty()
Sint64 SDL_GetNumberProperty (SDL_PropertiesID props, const char * name, Sint64 default_value)
Get a number property from a group of properties.
You can use SDL_GetPropertyType() to query whether the property exists and is a number property.
Parameters
props the properties to query.
name the name of the property to query.
default_value the default value of the property.
Returns
the value of the property, or default_value if it is not set or not a number property.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPropertyType
SDL_HasProperty
SDL_SetNumberProperty
{
    SDL_Properties *properties = NULL;
    Sint64 value = default_value;
    if (!props) {
        return value;
    }
    if (!name || !*name) {
        return value;
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return value;
    }
    SDL_LockMutex(properties->lock);
    {
        SDL_Property *property = NULL;
        if (SDL_FindInHashTable(properties->props, name, (const void **)&property)) {
            switch (property->type) {
            case SDL_PROPERTY_TYPE_STRING:
                value = (Sint64)SDL_strtoll(property->value.string_value, NULL, 0);
                break;
            case SDL_PROPERTY_TYPE_NUMBER:
                value = property->value.number_value;
                break;
            case SDL_PROPERTY_TYPE_FLOAT:
                value = (Sint64)SDL_round((double)property->value.float_value);
                break;
            case SDL_PROPERTY_TYPE_BOOLEAN:
                value = property->value.boolean_value;
                break;
            default:
                break;
            }
        }
    }
    SDL_UnlockMutex(properties->lock);
    return value;
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_FindInHashTable(), SDL_LockMutex(), SDL_properties, SDL_PROPERTY_TYPE_BOOLEAN, SDL_PROPERTY_TYPE_FLOAT, SDL_PROPERTY_TYPE_NUMBER, SDL_PROPERTY_TYPE_STRING, SDL_round(), SDL_strtoll(), and SDL_UnlockMutex().
Referenced by create_zenity_args(), dynamic_mem_realloc(), get_x11_window_handle(), SDL_CreateColorCursor(), SDL_CreateRendererWithProperties(), SDL_CreateTextureWithProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateWindowWithProperties(), SDL_DumpPropertiesCallback(), SDL_Fcitx_UpdateTextInputArea(), SDL_GetRenderVSync(), SDL_GetTextInputCapitalization(), SDL_GetTextInputType(), SDL_GetWindowFlagProperties(), SDL_SetupRendererColorspace(), SDL_ShowFileDialogWithProperties(), SDL_SYS_ShowFileDialogWithProperties(), and SDL_UpdateTextureFromSurface().
SDL_GetPointerProperty()
void * SDL_GetPointerProperty (SDL_PropertiesID props, const char * name, void * default_value)
Get a pointer property from a group of properties.
By convention, the names of properties that SDL exposes on objects will start with "SDL.", and properties that SDL uses internally will start with "SDL.internal.". These should be considered read-only and should not be modified by applications.
Parameters
props the properties to query.
name the name of the property to query.
default_value the default value of the property.
Returns
the value of the property, or default_value if it is not set or not a pointer property.
Thread Safety
It is safe to call this function from any thread, although the data returned is not protected and could potentially be freed if you call SDL_SetPointerProperty() or SDL_ClearProperty() on these properties from another thread. If you need to avoid this, use SDL_LockProperties() and SDL_UnlockProperties().
Since
This function is available since SDL 3.2.0.
See also
SDL_GetBooleanProperty
SDL_GetFloatProperty
SDL_GetNumberProperty
SDL_GetPropertyType
SDL_GetStringProperty
SDL_HasProperty
SDL_SetPointerProperty
{
    SDL_Properties *properties = NULL;
    void *value = default_value;
    if (!props) {
        return value;
    }
    if (!name || !*name) {
        return value;
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return value;
    }
    // Note that taking the lock here only guarantees that we won't read the
    // hashtable while it's being modified. The value itself can easily be
    // freed from another thread after it is returned here.
    SDL_LockMutex(properties->lock);
    {
        SDL_Property *property = NULL;
        if (SDL_FindInHashTable(properties->props, name, (const void **)&property)) {
            if (property->type == SDL_PROPERTY_TYPE_POINTER) {
                value = property->value.pointer_value;
            }
        }
    }
    SDL_UnlockMutex(properties->lock);
    return value;
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_FindInHashTable(), SDL_LockMutex(), SDL_properties, SDL_PROPERTY_TYPE_POINTER, and SDL_UnlockMutex().
Referenced by create_zenity_args(), dynamic_mem_close(), get_x11_window_handle(), mem_close(), ResetHintsCallback(), SDL_AddHintCallback(), SDL_CreateGPURenderer(), SDL_CreateGPURenderState(), SDL_CreateProcessWithProperties(), SDL_CreateRendererWithProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateWindowTexture(), SDL_CreateWindowWithProperties(), SDL_DestroyRendererWithoutFreeing(), SDL_DumpPropertiesCallback(), SDL_Fcitx_UpdateTextInputArea(), SDL_GetHint(), SDL_GetProcessInput(), SDL_GetProcessOutput(), SDL_GetRenderer(), SDL_GetRenderTarget(), SDL_GetWindowTextureVSync(), SDL_OnWindowResized(), SDL_ReadProcess(), SDL_RemoveHintCallback(), SDL_RenderApplyWindowShape(), SDL_RenderReadPixels(), SDL_ResetHint(), SDL_SetHintWithPriority(), SDL_SetWindowTextureVSync(), SDL_ShowFileDialogWithProperties(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UpdateWindowTexture(), windows_ShowFileDialog(), and windows_ShowFolderDialog().
SDL_GetPropertyType()
SDL_PropertyType SDL_GetPropertyType (SDL_PropertiesID props, const char * name)
Get the type of a property in a group of properties.
Parameters
props the properties to query.
name the name of the property to query.
Returns
the type of the property, or SDL_PROPERTY_TYPE_INVALID if it is not set.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasProperty
{
    SDL_Properties *properties = NULL;
    SDL_PropertyType type = SDL_PROPERTY_TYPE_INVALID;
    if (!props) {
        return SDL_PROPERTY_TYPE_INVALID;
    }
    if (!name || !*name) {
        return SDL_PROPERTY_TYPE_INVALID;
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return SDL_PROPERTY_TYPE_INVALID;
    }
    SDL_LockMutex(properties->lock);
    {
        SDL_Property *property = NULL;
        if (SDL_FindInHashTable(properties->props, name, (const void **)&property)) {
            type = property->type;
        }
    }
    SDL_UnlockMutex(properties->lock);
    return type;
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_FindInHashTable(), SDL_LockMutex(), SDL_properties, SDL_PROPERTY_TYPE_INVALID, and SDL_UnlockMutex().
Referenced by SDL_DumpPropertiesCallback(), and SDL_HasProperty().
SDL_GetStringProperty()
const char * SDL_GetStringProperty (SDL_PropertiesID props, const char * name, const char * default_value)
Get a string property from a group of properties.
Parameters
props the properties to query.
name the name of the property to query.
default_value the default value of the property.
Returns
the value of the property, or default_value if it is not set or not a string property.
Thread Safety
It is safe to call this function from any thread, although the data returned is not protected and could potentially be freed if you call SDL_SetStringProperty() or SDL_ClearProperty() on these properties from another thread. If you need to avoid this, use SDL_LockProperties() and SDL_UnlockProperties().
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPropertyType
SDL_HasProperty
SDL_SetStringProperty
{
    SDL_Properties *properties = NULL;
    const char *value = default_value;
    if (!props) {
        return value;
    }
    if (!name || !*name) {
        return value;
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return value;
    }
    SDL_LockMutex(properties->lock);
    {
        SDL_Property *property = NULL;
        if (SDL_FindInHashTable(properties->props, name, (const void **)&property)) {
            switch (property->type) {
            case SDL_PROPERTY_TYPE_STRING:
                value = property->value.string_value;
                break;
            case SDL_PROPERTY_TYPE_NUMBER:
                if (property->string_storage) {
                    value = property->string_storage;
                } else {
                    SDL_asprintf(&property->string_storage, "%" SDL_PRIs64, property->value.number_value);
                    if (property->string_storage) {
                        value = property->string_storage;
                    }
                }
                break;
            case SDL_PROPERTY_TYPE_FLOAT:
                if (property->string_storage) {
                    value = property->string_storage;
                } else {
                    SDL_asprintf(&property->string_storage, "%f", property->value.float_value);
                    if (property->string_storage) {
                        value = property->string_storage;
                    }
                }
                break;
            case SDL_PROPERTY_TYPE_BOOLEAN:
                value = property->value.boolean_value ? "true" : "false";
                break;
            default:
                break;
            }
        }
    }
    SDL_UnlockMutex(properties->lock);
    return value;
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_asprintf(), SDL_FindInHashTable(), SDL_LockMutex(), SDL_PRIs64, SDL_properties, SDL_PROPERTY_TYPE_BOOLEAN, SDL_PROPERTY_TYPE_FLOAT, SDL_PROPERTY_TYPE_NUMBER, SDL_PROPERTY_TYPE_STRING, and SDL_UnlockMutex().
Referenced by SDL_Blit_Slow_Float(), SDL_CreateGPUBuffer(), SDL_CreateGPUTransferBuffer(), SDL_CreateProcessWithProperties(), SDL_CreateRendererWithProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateWindowWithProperties(), SDL_DumpPropertiesCallback(), SDL_GetAppMetadataProperty(), SDL_GPUSelectBackend(), and SDL_SYS_ShowFileDialogWithProperties().
SDL_HasProperty()
bool SDL_HasProperty (SDL_PropertiesID props, const char * name)
Return whether a property exists in a group of properties.
Parameters
props the properties to query.
name the name of the property to query.
Returns
true if the property exists, or false if it doesn't.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPropertyType
{
    return (SDL_GetPropertyType(props, name) != SDL_PROPERTY_TYPE_INVALID);
}
References SDL_GetPropertyType(), and SDL_PROPERTY_TYPE_INVALID.
Referenced by SDL_GetTextInputCapitalization(), and SDL_GetTextInputMultiline().
SDL_InitProperties()
bool SDL_InitProperties (void)
{
    if (!SDL_ShouldInit(&SDL_properties_init)) {
        return true;
    }
    SDL_properties = SDL_CreateHashTable(0, true, SDL_HashID, SDL_KeyMatchID, NULL, NULL);
    const bool initialized = (SDL_properties != NULL);
    SDL_SetInitialized(&SDL_properties_init, initialized);
    return initialized;
}
References NULL, SDL_CreateHashTable(), SDL_HashID(), SDL_KeyMatchID(), SDL_properties, SDL_properties_init, SDL_SetInitialized(), and SDL_ShouldInit().
Referenced by SDL_CheckInitProperties().
SDL_LockProperties()
bool SDL_LockProperties (SDL_PropertiesID props)
Lock a group of properties.
Obtain a multi-threaded lock for these properties. Other threads will wait while trying to lock these properties until they are unlocked. Properties must be unlocked before they are destroyed.
The lock is automatically taken when setting individual properties, this function is only needed when you want to set several properties atomically or want to guarantee that properties being queried aren't freed in another thread.
Parameters
props the properties to lock.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_UnlockProperties
{
    SDL_Properties *properties = NULL;
    if (!props) {
        return SDL_InvalidParamError("props");
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return SDL_InvalidParamError("props");
    }
    SDL_LockMutex(properties->lock);
    return true;
}
References SDL_Properties::lock, NULL, SDL_FindInHashTable(), SDL_InvalidParamError, SDL_LockMutex(), and SDL_properties.
Referenced by SDL_AddHintCallback(), SDL_GetHint(), SDL_RemoveHintCallback(), SDL_ResetHint(), and SDL_SetHintWithPriority().
SDL_PrivateSetProperty()
bool SDL_PrivateSetProperty (SDL_PropertiesID props, const char * name, SDL_Property * property) static
{
    SDL_Properties *properties = NULL;
    bool result = true;
    if (!props) {
        SDL_FreePropertyWithCleanup(NULL, property, NULL, true);
        return SDL_InvalidParamError("props");
    }
    if (!name || !*name) {
        SDL_FreePropertyWithCleanup(NULL, property, NULL, true);
        return SDL_InvalidParamError("name");
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        SDL_FreePropertyWithCleanup(NULL, property, NULL, true);
        return SDL_InvalidParamError("props");
    }
    SDL_LockMutex(properties->lock);
    {
        SDL_RemoveFromHashTable(properties->props, name);
        if (property) {
            char *key = SDL_strdup(name);
            if (!key || !SDL_InsertIntoHashTable(properties->props, key, property, false)) {
                SDL_FreePropertyWithCleanup(key, property, NULL, true);
                result = false;
            }
        }
    }
    SDL_UnlockMutex(properties->lock);
    return result;
}
References SDL_Properties::lock, NULL, SDL_Properties::props, SDL_FindInHashTable(), SDL_FreePropertyWithCleanup(), SDL_InsertIntoHashTable(), SDL_InvalidParamError, SDL_LockMutex(), SDL_properties, SDL_RemoveFromHashTable(), SDL_strdup(), and SDL_UnlockMutex().
Referenced by SDL_ClearProperty(), SDL_SetBooleanProperty(), SDL_SetFloatProperty(), SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_SetPointerPropertyWithCleanup(), and SDL_SetStringProperty().
SDL_QuitProperties()
void SDL_QuitProperties (void)
{
    if (!SDL_ShouldQuit(&SDL_properties_init)) {
        return;
    }
    SDL_PropertiesID props;
    do {
        props = SDL_GetAtomicU32(&SDL_global_properties);
    } while (!SDL_CompareAndSwapAtomicU32(&SDL_global_properties, props, 0));
    if (props) {
        SDL_DestroyProperties(props);
    }
    // this can't just DestroyHashTable with SDL_FreeProperties as the destructor, because
    //  other destructors under this might cause use to attempt a recursive lock on SDL_properties,
    //  which isn't allowed with rwlocks. So manually iterate and free everything.
    SDL_HashTable *properties = SDL_properties;
    SDL_properties = NULL;
    SDL_IterateHashTable(properties, FreeOneProperties, NULL);
    SDL_DestroyHashTable(properties);
    SDL_SetInitialized(&SDL_properties_init, false);
}
References FreeOneProperties(), NULL, SDL_CompareAndSwapAtomicU32(), SDL_DestroyHashTable(), SDL_DestroyProperties(), SDL_GetAtomicU32(), SDL_global_properties, SDL_IterateHashTable(), SDL_properties, SDL_properties_init, SDL_SetInitialized(), and SDL_ShouldQuit().
Referenced by SDL_Quit().
SDL_SetBooleanProperty()
bool SDL_SetBooleanProperty (SDL_PropertiesID props, const char * name, bool value)
Set a boolean property in a group of properties.
Parameters
props the properties to modify.
name the name of the property to modify.
value the new value of the property.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetBooleanProperty
{
    SDL_Property *property = (SDL_Property *)SDL_calloc(1, sizeof(*property));
    if (!property) {
        return false;
    }
    property->type = SDL_PROPERTY_TYPE_BOOLEAN;
    property->value.boolean_value = value ? true : false;
    return SDL_PrivateSetProperty(props, name, property);
}
References SDL_calloc(), SDL_PrivateSetProperty(), SDL_PROPERTY_TYPE_BOOLEAN, true, and SDL_Property::type.
Referenced by IOS_JoystickOpen(), SDL_AddVideoDisplay(), SDL_CreateGPURenderer(), SDL_CreateProcessWithProperties(), SDL_GPU_FillProperties(), SDL_SetWindowHDRProperties(), SDL_ShowOpenFileDialog(), SDL_ShowOpenFolderDialog(), SDL_SYS_OpenURL(), and UpdateHDRProperties().
SDL_SetFloatProperty()
bool SDL_SetFloatProperty (SDL_PropertiesID props, const char * name, float value)
Set a floating point property in a group of properties.
Parameters
props the properties to modify.
name the name of the property to modify.
value the new value of the property.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetFloatProperty
{
    SDL_Property *property = (SDL_Property *)SDL_calloc(1, sizeof(*property));
    if (!property) {
        return false;
    }
    property->type = SDL_PROPERTY_TYPE_FLOAT;
    property->value.float_value = value;
    return SDL_PrivateSetProperty(props, name, property);
}
References SDL_calloc(), SDL_PrivateSetProperty(), SDL_PROPERTY_TYPE_FLOAT, and SDL_Property::type.
Referenced by SDL_Blit_Slow_Float(), SDL_CreateTextureFromSurface(), SDL_CreateTextureWithProperties(), SDL_RenderReadPixels(), SDL_SetWindowHDRProperties(), and UpdateHDRProperties().
SDL_SetFreeableProperty()
bool SDL_SetFreeableProperty (SDL_PropertiesID props, const char * name, void * value)
{
    return SDL_SetPointerPropertyWithCleanup(props, name, value, CleanupFreeableProperty, NULL);
}
References CleanupFreeableProperty(), NULL, and SDL_SetPointerPropertyWithCleanup().
SDL_SetNumberProperty()
bool SDL_SetNumberProperty (SDL_PropertiesID props, const char * name, Sint64 value)
Set an integer property in a group of properties.
Parameters
props the properties to modify.
name the name of the property to modify.
value the new value of the property.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumberProperty
{
    SDL_Property *property = (SDL_Property *)SDL_calloc(1, sizeof(*property));
    if (!property) {
        return false;
    }
    property->type = SDL_PROPERTY_TYPE_NUMBER;
    property->value.number_value = value;
    return SDL_PrivateSetProperty(props, name, property);
}
References SDL_calloc(), SDL_PrivateSetProperty(), SDL_PROPERTY_TYPE_NUMBER, and SDL_Property::type.
Referenced by run_zenity(), SDL_CreatePopupWindow(), SDL_CreateProcess(), SDL_CreateRendererWithProperties(), SDL_CreateTexture(), SDL_CreateTextureFromSurface(), SDL_CreateTextureWithProperties(), SDL_CreateThreadWithStackSize(), SDL_CreateWindow(), SDL_GetDisplayForWindow(), SDL_IOFromConstMem(), SDL_IOFromFD(), SDL_IOFromMem(), SDL_SetRenderVSync(), SDL_ShowOpenFileDialog(), SDL_ShowSaveFileDialog(), and SDL_Zenity_detect().
SDL_SetPointerProperty()
bool SDL_SetPointerProperty (SDL_PropertiesID props, const char * name, void * value)
Set a pointer property in a group of properties.
Parameters
props the properties to modify.
name the name of the property to modify.
value the new value of the property, or NULL to delete the property.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPointerProperty
SDL_HasProperty
SDL_SetBooleanProperty
SDL_SetFloatProperty
SDL_SetNumberProperty
SDL_SetPointerPropertyWithCleanup
SDL_SetStringProperty
{
    SDL_Property *property;
    if (!value) {
        return SDL_ClearProperty(props, name);
    }
    property = (SDL_Property *)SDL_calloc(1, sizeof(*property));
    if (!property) {
        return false;
    }
    property->type = SDL_PROPERTY_TYPE_POINTER;
    property->value.pointer_value = value;
    return SDL_PrivateSetProperty(props, name, property);
}
References SDL_calloc(), SDL_ClearProperty(), SDL_PrivateSetProperty(), SDL_PROPERTY_TYPE_POINTER, and SDL_Property::type.
Referenced by dynamic_mem_realloc(), run_zenity(), SDL_AddSupportedTextureFormat(), SDL_CreateGPURenderer(), SDL_CreatePopupWindow(), SDL_CreateProcess(), SDL_CreateRenderer(), SDL_CreateRendererWithProperties(), SDL_CreateSoftwareRenderer(), SDL_CreateTextureWithProperties(), SDL_CreateThreadRuntime(), SDL_CreateThreadWithStackSize(), SDL_IOFromConstMem(), SDL_IOFromFile(), SDL_IOFromMem(), SDL_ShowOpenFileDialog(), SDL_ShowOpenFolderDialog(), SDL_ShowSaveFileDialog(), SDL_SYS_OpenURL(), and SDL_Zenity_detect().
SDL_SetPointerPropertyWithCleanup()
bool SDL_SetPointerPropertyWithCleanup (SDL_PropertiesID props, const char * name, void * value, SDL_CleanupPropertyCallback cleanup, void * userdata)
Set a pointer property in a group of properties with a cleanup function that is called when the property is deleted.
The cleanup function is also called if setting the property fails for any reason.
For simply setting basic data types, like numbers, bools, or strings, use SDL_SetNumberProperty, SDL_SetBooleanProperty, or SDL_SetStringProperty instead, as those functions will handle cleanup on your behalf. This function is only for more complex, custom data.
Parameters
props the properties to modify.
name the name of the property to modify.
value the new value of the property, or NULL to delete the property.
cleanup the function to call when this property is deleted, or NULL if no cleanup is necessary.
userdata a pointer that is passed to the cleanup function.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPointerProperty
SDL_SetPointerProperty
SDL_CleanupPropertyCallback
{
    SDL_Property *property;
    if (!value) {
        if (cleanup) {
            cleanup(userdata, value);
        }
        return SDL_ClearProperty(props, name);
    }
    property = (SDL_Property *)SDL_calloc(1, sizeof(*property));
    if (!property) {
        if (cleanup) {
            cleanup(userdata, value);
        }
        SDL_FreePropertyWithCleanup(NULL, property, NULL, false);
        return false;
    }
    property->type = SDL_PROPERTY_TYPE_POINTER;
    property->value.pointer_value = value;
    property->cleanup = cleanup;
    property->userdata = userdata;
    return SDL_PrivateSetProperty(props, name, property);
}
References NULL, SDL_calloc(), SDL_ClearProperty(), SDL_FreePropertyWithCleanup(), SDL_PrivateSetProperty(), SDL_PROPERTY_TYPE_POINTER, and SDL_Property::type.
Referenced by SDL_AddHintCallback(), SDL_CreateWindowTexture(), SDL_SetFreeableProperty(), SDL_SetHintWithPriority(), and SDL_SetSurfaceProperty().
SDL_SetStringProperty()
bool SDL_SetStringProperty (SDL_PropertiesID props, const char * name, const char * value)
Set a string property in a group of properties.
This function makes a copy of the string; the caller does not have to preserve the data after this call completes.
Parameters
props the properties to modify.
name the name of the property to modify.
value the new value of the property, or NULL to delete the property.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetStringProperty
{
    SDL_Property *property;
    if (!value) {
        return SDL_ClearProperty(props, name);
    }
    property = (SDL_Property *)SDL_calloc(1, sizeof(*property));
    if (!property) {
        return false;
    }
    property->type = SDL_PROPERTY_TYPE_STRING;
    property->value.string_value = SDL_strdup(value);
    if (!property->value.string_value) {
        SDL_free(property);
        return false;
    }
    return SDL_PrivateSetProperty(props, name, property);
}
References SDL_calloc(), SDL_ClearProperty(), SDL_free(), SDL_PrivateSetProperty(), SDL_PROPERTY_TYPE_STRING, SDL_strdup(), SDL_Property::string_value, SDL_Property::type, and SDL_Property::value.
Referenced by SDL_CreateGPURenderer(), SDL_CreateRenderer(), SDL_CreateRendererWithProperties(), SDL_CreateThreadRuntime(), SDL_CreateThreadWithStackSize(), SDL_CreateWindow(), SDL_GPU_FillProperties(), SDL_SetAppMetadataProperty(), SDL_ShowOpenFileDialog(), SDL_ShowOpenFolderDialog(), and SDL_ShowSaveFileDialog().
SDL_SetSurfaceProperty()
bool SDL_SetSurfaceProperty (SDL_PropertiesID props, const char * name, SDL_Surface * surface)
{
    return SDL_SetPointerPropertyWithCleanup(props, name, surface, CleanupSurface, NULL);
}
References CleanupSurface(), NULL, and SDL_SetPointerPropertyWithCleanup().
Referenced by SDL_SetWindowShape().
SDL_UnlockProperties()
void SDL_UnlockProperties (SDL_PropertiesID props)
Unlock a group of properties.
Parameters
props the properties to unlock.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockProperties
{
    SDL_Properties *properties = NULL;
    if (!props) {
        return;
    }
    SDL_FindInHashTable(SDL_properties, (const void *)(uintptr_t)props, (const void **)&properties);
    if (!properties) {
        return;
    }
    SDL_UnlockMutex(properties->lock);
}
References SDL_Properties::lock, NULL, SDL_FindInHashTable(), SDL_properties, and SDL_UnlockMutex().
Referenced by SDL_AddHintCallback(), SDL_GetHint(), SDL_RemoveHintCallback(), SDL_ResetHint(), and SDL_SetHintWithPriority().
Variable Documentation
SDL_global_properties
SDL_AtomicU32 SDL_global_properties static
Referenced by SDL_GetGlobalProperties(), and SDL_QuitProperties().
SDL_last_properties_id
SDL_AtomicU32 SDL_last_properties_id static
Referenced by SDL_CreateProperties().
SDL_properties
SDL_HashTable* SDL_properties static
Referenced by SDL_CopyProperties(), SDL_CreateProperties(), SDL_DestroyProperties(), SDL_EnumerateProperties(), SDL_GetBooleanProperty(), SDL_GetFloatProperty(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPropertyType(), SDL_GetStringProperty(), SDL_InitProperties(), SDL_LockProperties(), SDL_PrivateSetProperty(), SDL_QuitProperties(), and SDL_UnlockProperties().
SDL_properties_init
SDL_InitState SDL_properties_init static
Referenced by SDL_InitProperties(), and SDL_QuitProperties().