SDL3: SDL-main/include/SDL3/SDL_haptic.h File Reference
SDL_haptic.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_joystick.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_HapticCondition
struct SDL_HapticConstant
struct SDL_HapticCustom
struct SDL_HapticDirection
union SDL_HapticEffect
struct SDL_HapticLeftRight
struct SDL_HapticPeriodic
struct SDL_HapticRamp
Macros
#define SDL_HAPTIC_INFINITY 4294967295U
Typedefs
typedef struct SDL_Haptic SDL_Haptic
Haptic effects
#define SDL_HAPTIC_AUTOCENTER (1u<<17)
#define SDL_HAPTIC_CONSTANT (1u<<0)
#define SDL_HAPTIC_CUSTOM (1u<<15)
#define SDL_HAPTIC_DAMPER (1u<<8)
#define SDL_HAPTIC_FRICTION (1u<<10)
#define SDL_HAPTIC_GAIN (1u<<16)
#define SDL_HAPTIC_INERTIA (1u<<9)
#define SDL_HAPTIC_LEFTRIGHT (1u<<11)
#define SDL_HAPTIC_PAUSE (1u<<19)
#define SDL_HAPTIC_RAMP (1u<<6)
#define SDL_HAPTIC_RESERVED1 (1u<<12)
#define SDL_HAPTIC_RESERVED2 (1u<<13)
#define SDL_HAPTIC_RESERVED3 (1u<<14)
#define SDL_HAPTIC_SAWTOOTHDOWN (1u<<5)
#define SDL_HAPTIC_SAWTOOTHUP (1u<<4)
#define SDL_HAPTIC_SINE (1u<<1)
#define SDL_HAPTIC_SPRING (1u<<7)
#define SDL_HAPTIC_SQUARE (1u<<2)
#define SDL_HAPTIC_STATUS (1u<<18)
#define SDL_HAPTIC_TRIANGLE (1u<<3)
typedef Uint16 SDL_HapticEffectType
Direction encodings
SDL_DECLSPEC void SDLCALL SDL_CloseHaptic (SDL_Haptic *haptic)
SDL_DECLSPEC SDL_HapticEffectID SDLCALL SDL_CreateHapticEffect (SDL_Haptic *haptic, const SDL_HapticEffect *effect)
SDL_DECLSPEC void SDLCALL SDL_DestroyHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect)
SDL_DECLSPEC bool SDLCALL SDL_GetHapticEffectStatus (SDL_Haptic *haptic, SDL_HapticEffectID effect)
SDL_DECLSPEC Uint32 SDLCALL SDL_GetHapticFeatures (SDL_Haptic *haptic)
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_GetHapticFromID (SDL_HapticID instance_id)
SDL_DECLSPEC SDL_HapticID SDLCALL SDL_GetHapticID (SDL_Haptic *haptic)
SDL_DECLSPEC const char *SDLCALL SDL_GetHapticName (SDL_Haptic *haptic)
SDL_DECLSPEC const char *SDLCALL SDL_GetHapticNameForID (SDL_HapticID instance_id)
SDL_DECLSPEC SDL_HapticID *SDLCALL SDL_GetHaptics (int *count)
SDL_DECLSPEC int SDLCALL SDL_GetMaxHapticEffects (SDL_Haptic *haptic)
SDL_DECLSPEC int SDLCALL SDL_GetMaxHapticEffectsPlaying (SDL_Haptic *haptic)
SDL_DECLSPEC int SDLCALL SDL_GetNumHapticAxes (SDL_Haptic *haptic)
#define SDL_HAPTIC_CARTESIAN 1
#define SDL_HAPTIC_POLAR 0
#define SDL_HAPTIC_SPHERICAL 2
#define SDL_HAPTIC_STEERING_AXIS 3
typedef struct SDL_HapticCondition SDL_HapticCondition
typedef struct SDL_HapticConstant SDL_HapticConstant
typedef struct SDL_HapticCustom SDL_HapticCustom
typedef struct SDL_HapticDirection SDL_HapticDirection
typedef Uint8 SDL_HapticDirectionType
typedef union SDL_HapticEffect SDL_HapticEffect
typedef int SDL_HapticEffectID
SDL_DECLSPEC bool SDLCALL SDL_HapticEffectSupported (SDL_Haptic *haptic, const SDL_HapticEffect *effect)
typedef Uint32 SDL_HapticID
typedef struct SDL_HapticLeftRight SDL_HapticLeftRight
typedef struct SDL_HapticPeriodic SDL_HapticPeriodic
typedef struct SDL_HapticRamp SDL_HapticRamp
SDL_DECLSPEC bool SDLCALL SDL_HapticRumbleSupported (SDL_Haptic *haptic)
SDL_DECLSPEC bool SDLCALL SDL_InitHapticRumble (SDL_Haptic *haptic)
SDL_DECLSPEC bool SDLCALL SDL_IsJoystickHaptic (SDL_Joystick *joystick)
SDL_DECLSPEC bool SDLCALL SDL_IsMouseHaptic (void)
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_OpenHaptic (SDL_HapticID instance_id)
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_OpenHapticFromJoystick (SDL_Joystick *joystick)
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_OpenHapticFromMouse (void)
SDL_DECLSPEC bool SDLCALL SDL_PauseHaptic (SDL_Haptic *haptic)
SDL_DECLSPEC bool SDLCALL SDL_PlayHapticRumble (SDL_Haptic *haptic, float strength, Uint32 length)
SDL_DECLSPEC bool SDLCALL SDL_ResumeHaptic (SDL_Haptic *haptic)
SDL_DECLSPEC bool SDLCALL SDL_RunHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect, Uint32 iterations)
SDL_DECLSPEC bool SDLCALL SDL_SetHapticAutocenter (SDL_Haptic *haptic, int autocenter)
SDL_DECLSPEC bool SDLCALL SDL_SetHapticGain (SDL_Haptic *haptic, int gain)
SDL_DECLSPEC bool SDLCALL SDL_StopHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect)
SDL_DECLSPEC bool SDLCALL SDL_StopHapticEffects (SDL_Haptic *haptic)
SDL_DECLSPEC bool SDLCALL SDL_StopHapticRumble (SDL_Haptic *haptic)
SDL_DECLSPEC bool SDLCALL SDL_UpdateHapticEffect (SDL_Haptic *haptic, SDL_HapticEffectID effect, const SDL_HapticEffect *data)
Macro Definition Documentation
SDL_HAPTIC_AUTOCENTER
#define SDL_HAPTIC_AUTOCENTER (1u<<17)
Device can set autocenter.
Device supports setting autocenter.
Since
This macro is available since SDL 3.2.0.
See also
SDL_SetHapticAutocenter
Referenced by SDL_OpenHaptic(), SDL_OpenHapticFromJoystick(), and SDL_SetHapticAutocenter().
SDL_HAPTIC_CARTESIAN
#define SDL_HAPTIC_CARTESIAN 1
Uses cartesian coordinates for the direction.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticDirection
Referenced by SDL_InitHapticRumble().
SDL_HAPTIC_CONSTANT
#define SDL_HAPTIC_CONSTANT (1u<<0)
Constant effect supported.
Constant haptic effect.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticCondition
SDL_HAPTIC_CUSTOM
#define SDL_HAPTIC_CUSTOM (1u<<15)
Custom effect is supported.
User defined custom haptic effect.
Since
This macro is available since SDL 3.2.0.
SDL_HAPTIC_DAMPER
#define SDL_HAPTIC_DAMPER (1u<<8)
Damper effect supported - uses axes velocity.
Condition haptic effect that simulates dampening. Effect is based on the axes velocity.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticCondition
SDL_HAPTIC_FRICTION
#define SDL_HAPTIC_FRICTION (1u<<10)
Friction effect supported - uses axes movement.
Condition haptic effect that simulates friction. Effect is based on the axes movement.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticCondition
SDL_HAPTIC_GAIN
#define SDL_HAPTIC_GAIN (1u<<16)
Device can set global gain.
Device supports setting the global gain.
Since
This macro is available since SDL 3.2.0.
See also
SDL_SetHapticGain
Referenced by SDL_OpenHaptic(), SDL_OpenHapticFromJoystick(), and SDL_SetHapticGain().
SDL_HAPTIC_INERTIA
#define SDL_HAPTIC_INERTIA (1u<<9)
Inertia effect supported - uses axes acceleration.
Condition haptic effect that simulates inertia. Effect is based on the axes acceleration.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticCondition
SDL_HAPTIC_INFINITY
#define SDL_HAPTIC_INFINITY 4294967295U
Used to play a device an infinite number of times.
Since
This macro is available since SDL 3.2.0.
See also
SDL_RunHapticEffect
SDL_HAPTIC_LEFTRIGHT
#define SDL_HAPTIC_LEFTRIGHT (1u<<11)
Left/Right effect supported.
Haptic effect for direct control over high/low frequency motors.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticLeftRight
Referenced by SDL_HapticRumbleSupported(), SDL_InitHapticRumble(), and SDL_PlayHapticRumble().
SDL_HAPTIC_PAUSE
#define SDL_HAPTIC_PAUSE (1u<<19)
Device can be paused.
Devices supports being paused.
Since
This macro is available since SDL 3.2.0.
See also
SDL_PauseHaptic
SDL_ResumeHaptic
Referenced by SDL_PauseHaptic(), and SDL_ResumeHaptic().
SDL_HAPTIC_POLAR
#define SDL_HAPTIC_POLAR 0
Uses polar coordinates for the direction.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticDirection
SDL_HAPTIC_RAMP
#define SDL_HAPTIC_RAMP (1u<<6)
Ramp effect supported.
Ramp haptic effect.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticRamp
SDL_HAPTIC_RESERVED1
#define SDL_HAPTIC_RESERVED1 (1u<<12)
Reserved for future use.
Since
This macro is available since SDL 3.2.0.
SDL_HAPTIC_RESERVED2
#define SDL_HAPTIC_RESERVED2 (1u<<13)
Reserved for future use.
Since
This macro is available since SDL 3.2.0.
SDL_HAPTIC_RESERVED3
#define SDL_HAPTIC_RESERVED3 (1u<<14)
Reserved for future use.
Since
This macro is available since SDL 3.2.0.
SDL_HAPTIC_SAWTOOTHDOWN
#define SDL_HAPTIC_SAWTOOTHDOWN (1u<<5)
Sawtoothdown wave effect supported.
Periodic haptic effect that simulates saw tooth down waves.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticPeriodic
SDL_HAPTIC_SAWTOOTHUP
#define SDL_HAPTIC_SAWTOOTHUP (1u<<4)
Sawtoothup wave effect supported.
Periodic haptic effect that simulates saw tooth up waves.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticPeriodic
SDL_HAPTIC_SINE
#define SDL_HAPTIC_SINE (1u<<1)
Sine wave effect supported.
Periodic haptic effect that simulates sine waves.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticPeriodic
Referenced by SDL_HapticRumbleSupported(), SDL_InitHapticRumble(), and SDL_PlayHapticRumble().
SDL_HAPTIC_SPHERICAL
#define SDL_HAPTIC_SPHERICAL 2
Uses spherical coordinates for the direction.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticDirection
SDL_HAPTIC_SPRING
#define SDL_HAPTIC_SPRING (1u<<7)
Spring effect supported - uses axes position.
Condition haptic effect that simulates a spring. Effect is based on the axes position.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticCondition
SDL_HAPTIC_SQUARE
#define SDL_HAPTIC_SQUARE (1u<<2)
Square wave effect supported.
Periodic haptic effect that simulates square waves.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticPeriodic
SDL_HAPTIC_STATUS
#define SDL_HAPTIC_STATUS (1u<<18)
Device can be queried for effect status.
Device supports querying effect status.
Since
This macro is available since SDL 3.2.0.
See also
SDL_GetHapticEffectStatus
Referenced by SDL_GetHapticEffectStatus().
SDL_HAPTIC_STEERING_AXIS
#define SDL_HAPTIC_STEERING_AXIS 3
Use this value to play an effect on the steering wheel axis.
This provides better compatibility across platforms and devices as SDL will guess the correct axis.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticDirection
SDL_HAPTIC_TRIANGLE
#define SDL_HAPTIC_TRIANGLE (1u<<3)
Triangle wave effect supported.
Periodic haptic effect that simulates triangular waves.
Since
This macro is available since SDL 3.2.0.
See also
SDL_HapticPeriodic
Typedef Documentation
SDL_Haptic
typedef struct SDL_Haptic SDL_Haptic
CategoryHaptic
The SDL haptic subsystem manages haptic (force feedback) devices.
The basic usage is as follows:
Initialize the subsystem (SDL_INIT_HAPTIC).
Open a haptic device.
SDL_OpenHaptic() to open from index.
SDL_OpenHapticFromJoystick() to open from an existing joystick.
Create an effect (SDL_HapticEffect).
Upload the effect with SDL_CreateHapticEffect().
Run the effect with SDL_RunHapticEffect().
(optional) Free the effect with SDL_DestroyHapticEffect().
Close the haptic device with SDL_CloseHaptic().
Simple rumble example:
SDL_Haptic *haptic = NULL;
// Open the device
SDL_HapticID *haptics = SDL_GetHaptics(NULL);
if (haptics) {
    haptic = SDL_OpenHaptic(haptics[0]);
    SDL_free(haptics);
}
if (haptic == NULL)
   return;
// Initialize simple rumble
if (!SDL_InitHapticRumble(haptic))
   return;
// Play effect at 50% strength for 2 seconds
if (!SDL_PlayHapticRumble(haptic, 0.5, 2000))
   return;
SDL_Delay(2000);
// Clean up
SDL_CloseHaptic(haptic);
Complete example:
bool test_haptic(SDL_Joystick *joystick)
{
   SDL_Haptic *haptic;
   SDL_HapticEffect effect;
   SDL_HapticEffectID effect_id;
   // Open the device
   haptic = SDL_OpenHapticFromJoystick(joystick);
   if (haptic == NULL) return false; // Most likely joystick isn't haptic
   // See if it can do sine waves
   if ((SDL_GetHapticFeatures(haptic) & SDL_HAPTIC_SINE)==0) {
      SDL_CloseHaptic(haptic); // No sine effect
      return false;
   }
   // Create the effect
   SDL_memset(&effect, 0, sizeof(SDL_HapticEffect)); // 0 is safe default
   effect.type = SDL_HAPTIC_SINE;
   effect.periodic.direction.type = SDL_HAPTIC_POLAR; // Polar coordinates
   effect.periodic.direction.dir[0] = 18000; // Force comes from south
   effect.periodic.period = 1000; // 1000 ms
   effect.periodic.magnitude = 20000; // 20000/32767 strength
   effect.periodic.length = 5000; // 5 seconds long
   effect.periodic.attack_length = 1000; // Takes 1 second to get max strength
   effect.periodic.fade_length = 1000; // Takes 1 second to fade away
   // Upload the effect
   effect_id = SDL_CreateHapticEffect(haptic, &effect);
   // Test the effect
   SDL_RunHapticEffect(haptic, effect_id, 1);
   SDL_Delay(5000); // Wait for the effect to finish
   // We destroy the effect, although closing the device also does this
   SDL_DestroyHapticEffect(haptic, effect_id);
   // Close the device
   SDL_CloseHaptic(haptic);
   return true; // Success
}
Note that the SDL haptic subsystem is not thread-safe. The haptic structure used to identify an SDL haptic.
Since
This struct is available since SDL 3.2.0.
See also
SDL_OpenHaptic
SDL_OpenHapticFromJoystick
SDL_CloseHaptic
SDL_HapticCondition
typedef struct SDL_HapticCondition SDL_HapticCondition
A structure containing a template for a Condition effect.
The struct handles the following effects:
SDL_HAPTIC_SPRING: Effect based on axes position.
SDL_HAPTIC_DAMPER: Effect based on axes velocity.
SDL_HAPTIC_INERTIA: Effect based on axes acceleration.
SDL_HAPTIC_FRICTION: Effect based on axes movement.
Direction is handled by condition internals instead of a direction member. The condition effect specific members have three parameters. The first refers to the X axis, the second refers to the Y axis and the third refers to the Z axis. The right terms refer to the positive side of the axis and the left terms refer to the negative side of the axis. Please refer to the SDL_HapticDirection diagram for which side is positive and which is negative.
Since
This struct is available since SDL 3.2.0.
See also
SDL_HapticDirection
SDL_HAPTIC_SPRING
SDL_HAPTIC_DAMPER
SDL_HAPTIC_INERTIA
SDL_HAPTIC_FRICTION
SDL_HapticEffect
SDL_HapticConstant
typedef struct SDL_HapticConstant SDL_HapticConstant
A structure containing a template for a Constant effect.
This struct is exclusively for the SDL_HAPTIC_CONSTANT effect.
A constant effect applies a constant force in the specified direction to the joystick.
Since
This struct is available since SDL 3.2.0.
See also
SDL_HAPTIC_CONSTANT
SDL_HapticEffect
SDL_HapticCustom
typedef struct SDL_HapticCustom SDL_HapticCustom
A structure containing a template for the SDL_HAPTIC_CUSTOM effect.
This struct is exclusively for the SDL_HAPTIC_CUSTOM effect.
A custom force feedback effect is much like a periodic effect, where the application can define its exact shape. You will have to allocate the data yourself. Data should consist of channels * samples Uint16 samples.
If channels is one, the effect is rotated using the defined direction. Otherwise it uses the samples in data for the different axes.
Since
This struct is available since SDL 3.2.0.
See also
SDL_HAPTIC_CUSTOM
SDL_HapticEffect
SDL_HapticDirection
typedef struct SDL_HapticDirection SDL_HapticDirection
Structure that represents a haptic direction.
This is the direction where the force comes from, instead of the direction in which the force is exerted.
Directions can be specified by:
SDL_HAPTIC_POLAR : Specified by polar coordinates.
SDL_HAPTIC_CARTESIAN : Specified by cartesian coordinates.
SDL_HAPTIC_SPHERICAL : Specified by spherical coordinates.
Cardinal directions of the haptic device are relative to the positioning of the device. North is considered to be away from the user.
The following diagram represents the cardinal directions:
              .--.
              |__| .-------.
              |=.| |.-----.|
              |--| ||     ||
              |  | |'-----'|
              |__|~')_____('
                [ COMPUTER ]
                  North (0,-1)
                      ^
                      |
                      |
(-1,0)  West <----[ HAPTIC ]----> East (1,0)
                      |
                      |
                      v
                   South (0,1)
                   [ USER ]
                     \|||/
                     (o o)
               ---ooO-(_)-Ooo---
If type is SDL_HAPTIC_POLAR, direction is encoded by hundredths of a degree starting north and turning clockwise. SDL_HAPTIC_POLAR only uses the first dir parameter. The cardinal directions would be:
North: 0 (0 degrees)
East: 9000 (90 degrees)
South: 18000 (180 degrees)
West: 27000 (270 degrees)
If type is SDL_HAPTIC_CARTESIAN, direction is encoded by three positions (X axis, Y axis and Z axis (with 3 axes)). SDL_HAPTIC_CARTESIAN uses the first three dir parameters. The cardinal directions would be:
North: 0,-1, 0
East: 1, 0, 0
South: 0, 1, 0
West: -1, 0, 0
The Z axis represents the height of the effect if supported, otherwise it's unused. In cartesian encoding (1, 2) would be the same as (2, 4), you can use any multiple you want, only the direction matters.
If type is SDL_HAPTIC_SPHERICAL, direction is encoded by two rotations. The first two dir parameters are used. The dir parameters are as follows (all values are in hundredths of degrees):
Degrees from (1, 0) rotated towards (0, 1).
Degrees towards (0, 0, 1) (device needs at least 3 axes).
Example of force coming from the south with all encodings (force coming from the south means the user will have to pull the stick to counteract):
SDL_HapticDirection direction;
// Cartesian directions
direction.type = SDL_HAPTIC_CARTESIAN; // Using cartesian direction encoding.
direction.dir[0] = 0; // X position
direction.dir[1] = 1; // Y position
// Assuming the device has 2 axes, we don't need to specify third parameter.
// Polar directions
direction.type = SDL_HAPTIC_POLAR; // We'll be using polar direction encoding.
direction.dir[0] = 18000; // Polar only uses first parameter
// Spherical coordinates
direction.type = SDL_HAPTIC_SPHERICAL; // Spherical encoding
direction.dir[0] = 9000; // Since we only have two axes we don't need more parameters.
Since
This struct is available since SDL 3.2.0.
See also
SDL_HAPTIC_POLAR
SDL_HAPTIC_CARTESIAN
SDL_HAPTIC_SPHERICAL
SDL_HAPTIC_STEERING_AXIS
SDL_HapticEffect
SDL_GetNumHapticAxes
SDL_HapticDirectionType
typedef Uint8 SDL_HapticDirectionType
Type of coordinates used for haptic direction.
SDL_HapticEffect
typedef union SDL_HapticEffect SDL_HapticEffect
The generic template for any haptic effect.
All values max at 32767 (0x7FFF). Signed values also can be negative. Time values unless specified otherwise are in milliseconds.
You can also pass SDL_HAPTIC_INFINITY to length instead of a 0-32767 value. Neither delay, interval, attack_length nor fade_length support SDL_HAPTIC_INFINITY. Fade will also not be used since effect never ends.
Additionally, the SDL_HAPTIC_RAMP effect does not support a duration of SDL_HAPTIC_INFINITY.
Button triggers may not be supported on all devices, it is advised to not use them if possible. Buttons start at index 1 instead of index 0 like the joystick.
If both attack_length and fade_level are 0, the envelope is not used, otherwise both values are used.
Common parts:
// Replay - All effects have this
Uint32 length;        // Duration of effect (ms).
Uint16 delay;         // Delay before starting effect.
// Trigger - All effects have this
Uint16 button;        // Button that triggers effect.
Uint16 interval;      // How soon before effect can be triggered again.
// Envelope - All effects except condition effects have this
Uint16 attack_length; // Duration of the attack (ms).
Uint16 attack_level;  // Level at the start of the attack.
Uint16 fade_length;   // Duration of the fade out (ms).
Uint16 fade_level;    // Level at the end of the fade.
Here we have an example of a constant effect evolution in time:
Strength
^
|
|    effect level -->  _________________
|                     /                 \
|                    /                   \
|                   /                     \
|                  /                       \
| attack_level --> |                        \
|                  |                        |  <---  fade_level
|
+--------------------------------------------------> Time
                   [--]                 [---]
                   attack_length        fade_length
[------------------][-----------------------]
delay               length
Note either the attack_level or the fade_level may be above the actual effect level.
Since
This struct is available since SDL 3.2.0.
See also
SDL_HapticConstant
SDL_HapticPeriodic
SDL_HapticCondition
SDL_HapticRamp
SDL_HapticLeftRight
SDL_HapticCustom
SDL_HapticEffectID
typedef int SDL_HapticEffectID
ID for haptic effects.
This is -1 if the ID is invalid.
See also
SDL_CreateHapticEffect
SDL_HapticEffectType
typedef Uint16 SDL_HapticEffectType
Type of haptic effect.
SDL_HapticID
typedef Uint32 SDL_HapticID
This is a unique ID for a haptic device for the time it is connected to the system, and is never reused for the lifetime of the application.
If the haptic device is disconnected and reconnected, it will get a new ID.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
SDL_HapticLeftRight
typedef struct SDL_HapticLeftRight SDL_HapticLeftRight
A structure containing a template for a Left/Right effect.
This struct is exclusively for the SDL_HAPTIC_LEFTRIGHT effect.
The Left/Right effect is used to explicitly control the large and small motors, commonly found in modern game controllers. The small (right) motor is high frequency, and the large (left) motor is low frequency.
Since
This struct is available since SDL 3.2.0.
See also
SDL_HAPTIC_LEFTRIGHT
SDL_HapticEffect
SDL_HapticPeriodic
typedef struct SDL_HapticPeriodic SDL_HapticPeriodic
A structure containing a template for a Periodic effect.
The struct handles the following effects:
SDL_HAPTIC_SINE
SDL_HAPTIC_SQUARE
SDL_HAPTIC_TRIANGLE
SDL_HAPTIC_SAWTOOTHUP
SDL_HAPTIC_SAWTOOTHDOWN
A periodic effect consists in a wave-shaped effect that repeats itself over time. The type determines the shape of the wave and the parameters determine the dimensions of the wave.
Phase is given by hundredth of a degree meaning that giving the phase a value of 9000 will displace it 25% of its period. Here are sample values:
0: No phase displacement.
9000: Displaced 25% of its period.
18000: Displaced 50% of its period.
27000: Displaced 75% of its period.
36000: Displaced 100% of its period, same as 0, but 0 is preferred.
Examples:
SDL_HAPTIC_SINE
  __      __      __      __
 /  \    /  \    /  \    /
/    \__/    \__/    \__/
SDL_HAPTIC_SQUARE
 __    __    __    __    __
|  |  |  |  |  |  |  |  |  |
|  |__|  |__|  |__|  |__|  |
SDL_HAPTIC_TRIANGLE
  /\    /\    /\    /\    /\
 /  \  /  \  /  \  /  \  /
/    \/    \/    \/    \/
SDL_HAPTIC_SAWTOOTHUP
  /|  /|  /|  /|  /|  /|  /|
 / | / | / | / | / | / | / |
/  |/  |/  |/  |/  |/  |/  |
SDL_HAPTIC_SAWTOOTHDOWN
\  |\  |\  |\  |\  |\  |\  |
 \ | \ | \ | \ | \ | \ | \ |
  \|  \|  \|  \|  \|  \|  \|
Since
This struct is available since SDL 3.2.0.
See also
SDL_HAPTIC_SINE
SDL_HAPTIC_SQUARE
SDL_HAPTIC_TRIANGLE
SDL_HAPTIC_SAWTOOTHUP
SDL_HAPTIC_SAWTOOTHDOWN
SDL_HapticEffect
SDL_HapticRamp
typedef struct SDL_HapticRamp SDL_HapticRamp
A structure containing a template for a Ramp effect.
This struct is exclusively for the SDL_HAPTIC_RAMP effect.
The ramp effect starts at start strength and ends at end strength. It augments in linear fashion. If you use attack and fade with a ramp the effects get added to the ramp effect making the effect become quadratic instead of linear.
Since
This struct is available since SDL 3.2.0.
See also
SDL_HAPTIC_RAMP
SDL_HapticEffect
Function Documentation
SDL_CloseHaptic()
SDL_DECLSPEC void SDLCALL SDL_CloseHaptic (SDL_Haptic * haptic) extern
Close a haptic device previously opened with SDL_OpenHaptic().
Parameters
haptic the SDL_Haptic device to close.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHaptic
{
    SDL_HapticEffectID i;
    SDL_Haptic *hapticlist;
    SDL_Haptic *hapticlistprev;
    CHECK_HAPTIC_MAGIC(haptic,);
    // Check if it's still in use
    if (--haptic->ref_count > 0) {
        return;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        SDL_HIDAPI_HapticClose(haptic);
    } else
    #endif
    {
        // Close it, properly removing effects if needed
        for (i = 0; i < haptic->neffects; i++) {
            if (haptic->effects[i].hweffect != NULL) {
                SDL_DestroyHapticEffect(haptic, i);
            }
        }
        SDL_SYS_HapticClose(haptic);
    }
    SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, false);
    // Remove from the list
    hapticlist = SDL_haptics;
    hapticlistprev = NULL;
    while (hapticlist) {
        if (haptic == hapticlist) {
            if (hapticlistprev) {
                // unlink this entry
                hapticlistprev->next = hapticlist->next;
            } else {
                SDL_haptics = haptic->next;
            }
            break;
        }
        hapticlistprev = hapticlist;
        hapticlist = hapticlist->next;
    }
    // Free the data associated with this device
    SDL_free(haptic->name);
    SDL_free(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, haptic_effect::hweffect, SDL_Haptic::name, SDL_Haptic::neffects, SDL_Haptic::next, NULL, SDL_Haptic::ref_count, SDL_DestroyHapticEffect(), SDL_free(), SDL_haptics, SDL_HIDAPI_HapticClose(), SDL_HIDAPI_HapticIsHidapi(), SDL_OBJECT_TYPE_HAPTIC, SDL_SetObjectValid(), and SDL_SYS_HapticClose().
Referenced by SDL_QuitHaptics().
SDL_CreateHapticEffect()
SDL_DECLSPEC SDL_HapticEffectID SDLCALL SDL_CreateHapticEffect (SDL_Haptic * haptic, const SDL_HapticEffect * effect) extern
Create a new haptic effect on a specified device.
Parameters
haptic an SDL_Haptic device to create the effect on.
effect an SDL_HapticEffect structure containing the properties of the effect to create.
Returns
the ID of the effect on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyHapticEffect
SDL_RunHapticEffect
SDL_UpdateHapticEffect
{
    SDL_HapticEffectID i;
    CHECK_HAPTIC_MAGIC(haptic, -1);
    if (!effect) {
        SDL_InvalidParamError("effect");
        return -1;
    }
    // Check to see if effect is supported
    if (SDL_HapticEffectSupported(haptic, effect) == false) {
        SDL_SetError("Haptic: Effect not supported by haptic device.");
        return -1;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticNewEffect(haptic, effect);
    }
    #endif
    // See if there's a free slot
    for (i = 0; i < haptic->neffects; i++) {
        if (haptic->effects[i].hweffect == NULL) {
            // Now let the backend create the real effect
            if (!SDL_SYS_HapticNewEffect(haptic, &haptic->effects[i], effect)) {
                return -1; // Backend failed to create effect
            }
            SDL_memcpy(&haptic->effects[i].effect, effect,
                       sizeof(SDL_HapticEffect));
            return i;
        }
    }
    SDL_SetError("Haptic: Device has no free space left.");
    return -1;
}
References CHECK_HAPTIC_MAGIC, haptic_effect::effect, SDL_Haptic::effects, haptic_effect::hweffect, SDL_Haptic::neffects, NULL, SDL_HapticEffectSupported(), SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticNewEffect(), SDL_InvalidParamError, SDL_memcpy, SDL_SetError(), and SDL_SYS_HapticNewEffect().
Referenced by SDL_InitHapticRumble().
SDL_DestroyHapticEffect()
SDL_DECLSPEC void SDLCALL SDL_DestroyHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect) extern
Destroy a haptic effect on the device.
This will stop the effect if it's running. Effects are automatically destroyed when the device is closed.
Parameters
haptic the SDL_Haptic device to destroy the effect on.
effect the ID of the haptic effect to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateHapticEffect
{
    CHECK_HAPTIC_MAGIC(haptic,);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        SDL_HIDAPI_HapticDestroyEffect(haptic, effect);
        return;
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return;
    }
    // Not allocated
    if (haptic->effects[effect].hweffect == NULL) {
        return;
    }
    SDL_SYS_HapticDestroyEffect(haptic, &haptic->effects[effect]);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, haptic_effect::hweffect, NULL, SDL_HIDAPI_HapticDestroyEffect(), SDL_HIDAPI_HapticIsHidapi(), SDL_SYS_HapticDestroyEffect(), and ValidEffect().
Referenced by SDL_CloseHaptic().
SDL_GetHapticEffectStatus()
SDL_DECLSPEC bool SDLCALL SDL_GetHapticEffectStatus (SDL_Haptic * haptic, SDL_HapticEffectID effect) extern
Get the status of the current effect on the specified haptic device.
Device must support the SDL_HAPTIC_STATUS feature.
Parameters
haptic the SDL_Haptic device to query for the effect status on.
effect the ID of the haptic effect to query its status.
Returns
true if it is playing, false if it isn't playing or haptic status isn't supported.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticGetEffectStatus(haptic, effect);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    if (!(haptic->supported & SDL_HAPTIC_STATUS)) {
        return SDL_SetError("Haptic: Device does not support status queries.");
    }
    SDL_ClearError();
    return (SDL_SYS_HapticGetEffectStatus(haptic, &haptic->effects[effect]) > 0);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, SDL_ClearError(), SDL_HAPTIC_STATUS, SDL_HIDAPI_HapticGetEffectStatus(), SDL_HIDAPI_HapticIsHidapi(), SDL_SetError(), SDL_SYS_HapticGetEffectStatus(), SDL_Haptic::supported, and ValidEffect().
SDL_GetHapticFeatures()
SDL_DECLSPEC Uint32 SDLCALL SDL_GetHapticFeatures (SDL_Haptic * haptic) extern
Get the haptic device's supported features in bitwise manner.
Parameters
haptic the SDL_Haptic device to query.
Returns
a list of supported haptic features in bitwise manner (OR'd), or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_HapticEffectSupported
SDL_GetMaxHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, 0);
    return haptic->supported;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::supported.
SDL_GetHapticFromID()
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_GetHapticFromID (SDL_HapticID instance_id) extern
Get the SDL_Haptic associated with an instance ID, if it has been opened.
Parameters
instance_id the instance ID to get the SDL_Haptic for.
Returns
an SDL_Haptic on success or NULL on failure or if it hasn't been opened yet; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    SDL_Haptic *haptic;
    for (haptic = SDL_haptics; haptic; haptic = haptic->next) {
        if (instance_id == haptic->instance_id) {
            break;
        }
    }
    return haptic;
}
References SDL_Haptic::instance_id, SDL_Haptic::next, and SDL_haptics.
SDL_GetHapticID()
SDL_DECLSPEC SDL_HapticID SDLCALL SDL_GetHapticID (SDL_Haptic * haptic) extern
Get the instance ID of an opened haptic device.
Parameters
haptic the SDL_Haptic device to query.
Returns
the instance ID of the specified haptic device on success or 0 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_HAPTIC_MAGIC(haptic, 0);
    return haptic->instance_id;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::instance_id.
SDL_GetHapticName()
SDL_DECLSPEC const char *SDLCALL SDL_GetHapticName (SDL_Haptic * haptic) extern
Get the implementation dependent name of a haptic device.
Parameters
haptic the SDL_Haptic obtained from SDL_OpenJoystick().
Returns
the name of the selected haptic device. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticNameForID
{
    CHECK_HAPTIC_MAGIC(haptic, NULL);
    return SDL_GetPersistentString(haptic->name);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::name, NULL, and SDL_GetPersistentString().
SDL_GetHapticNameForID()
SDL_DECLSPEC const char *SDLCALL SDL_GetHapticNameForID (SDL_HapticID instance_id) extern
Get the implementation dependent name of a haptic device.
This can be called before any haptic devices are opened.
Parameters
instance_id the haptic device instance ID.
Returns
the name of the selected haptic device. If no name can be found, this function returns NULL; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticName
SDL_OpenHaptic
{
    int device_index;
    const char *name = NULL;
    if (SDL_GetHapticIndex(instance_id, &device_index)) {
        name = SDL_GetPersistentString(SDL_SYS_HapticName(device_index));
    }
    return name;
}
References NULL, SDL_GetHapticIndex(), SDL_GetPersistentString(), and SDL_SYS_HapticName().
SDL_GetHaptics()
SDL_DECLSPEC SDL_HapticID *SDLCALL SDL_GetHaptics (int * count) extern
Get a list of currently connected haptic devices.
Parameters
count a pointer filled in with the number of haptic devices returned, may be NULL.
Returns
a 0 terminated array of haptic device instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHaptic
{
    int device_index;
    int haptic_index = 0, num_haptics = 0;
    SDL_HapticID *haptics;
    num_haptics = SDL_SYS_NumHaptics();
    haptics = (SDL_HapticID *)SDL_malloc((num_haptics + 1) * sizeof(*haptics));
    if (haptics) {
        if (count) {
            *count = num_haptics;
        }
        for (device_index = 0; device_index < num_haptics; ++device_index) {
            haptics[haptic_index] = SDL_SYS_HapticInstanceID(device_index);
            SDL_assert(haptics[haptic_index] > 0);
            ++haptic_index;
        }
        haptics[haptic_index] = 0;
    } else {
        if (count) {
            *count = 0;
        }
    }
    return haptics;
}
References count, SDL_assert, SDL_malloc(), SDL_SYS_HapticInstanceID(), and SDL_SYS_NumHaptics().
SDL_GetMaxHapticEffects()
SDL_DECLSPEC int SDLCALL SDL_GetMaxHapticEffects (SDL_Haptic * haptic) extern
Get the number of effects a haptic device can store.
On some platforms this isn't fully supported, and therefore is an approximation. Always check to see if your created effect was actually created and do not rely solely on SDL_GetMaxHapticEffects().
Parameters
haptic the SDL_Haptic device to query.
Returns
the number of effects the haptic device can store or a negative error code on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMaxHapticEffectsPlaying
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, -1);
    return haptic->neffects;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::neffects.
SDL_GetMaxHapticEffectsPlaying()
SDL_DECLSPEC int SDLCALL SDL_GetMaxHapticEffectsPlaying (SDL_Haptic * haptic) extern
Get the number of effects a haptic device can play at the same time.
This is not supported on all platforms, but will always return a value.
Parameters
haptic the SDL_Haptic device to query maximum playing effects.
Returns
the number of effects the haptic device can play at the same time or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetMaxHapticEffects
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, -1);
    return haptic->nplaying;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::nplaying.
SDL_GetNumHapticAxes()
SDL_DECLSPEC int SDLCALL SDL_GetNumHapticAxes (SDL_Haptic * haptic) extern
Get the number of haptic axes the device has.
The number of haptic axes might be useful if working with the SDL_HapticDirection effect.
Parameters
haptic the SDL_Haptic device to query.
Returns
the number of axes on success or -1 on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    CHECK_HAPTIC_MAGIC(haptic, -1);
    return haptic->naxes;
}
References CHECK_HAPTIC_MAGIC, and SDL_Haptic::naxes.
SDL_HapticEffectSupported()
SDL_DECLSPEC bool SDLCALL SDL_HapticEffectSupported (SDL_Haptic * haptic, const SDL_HapticEffect * effect) extern
Check to see if an effect is supported by a haptic device.
Parameters
haptic the SDL_Haptic device to query.
effect the desired effect to query.
Returns
true if the effect is supported or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateHapticEffect
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!effect) {
        return false;
    }
    if ((haptic->supported & effect->type) != 0) {
        return true;
    }
    return false;
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::supported, and SDL_HapticEffect::type.
Referenced by SDL_CreateHapticEffect().
SDL_HapticRumbleSupported()
SDL_DECLSPEC bool SDLCALL SDL_HapticRumbleSupported (SDL_Haptic * haptic) extern
Check whether rumble is supported on a haptic device.
Parameters
haptic haptic device to check for rumble support.
Returns
true if the effect is supported or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_InitHapticRumble
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    // Most things can use SINE, but XInput only has LEFTRIGHT.
    return (haptic->supported & (SDL_HAPTIC_SINE | SDL_HAPTIC_LEFTRIGHT)) != 0;
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_LEFTRIGHT, SDL_HAPTIC_SINE, and SDL_Haptic::supported.
SDL_InitHapticRumble()
SDL_DECLSPEC bool SDLCALL SDL_InitHapticRumble (SDL_Haptic * haptic) extern
Initialize a haptic device for simple rumble playback.
Parameters
haptic the haptic device to initialize for simple rumble playback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_PlayHapticRumble
SDL_StopHapticRumble
SDL_HapticRumbleSupported
{
    SDL_HapticEffect *efx = &haptic->rumble_effect;
    CHECK_HAPTIC_MAGIC(haptic, false);
    // Already allocated.
    if (haptic->rumble_id >= 0) {
        return true;
    }
    SDL_zerop(efx);
    if (haptic->supported & SDL_HAPTIC_SINE) {
        efx->type = SDL_HAPTIC_SINE;
        efx->periodic.direction.type = SDL_HAPTIC_CARTESIAN;
        efx->periodic.period = 1000;
        efx->periodic.magnitude = 0x4000;
        efx->periodic.length = 5000;
        efx->periodic.attack_length = 0;
        efx->periodic.fade_length = 0;
    } else if (haptic->supported & SDL_HAPTIC_LEFTRIGHT) { // XInput?
        efx->type = SDL_HAPTIC_LEFTRIGHT;
        efx->leftright.length = 5000;
        efx->leftright.large_magnitude = 0x4000;
        efx->leftright.small_magnitude = 0x4000;
    } else {
        return SDL_SetError("Device doesn't support rumble");
    }
    haptic->rumble_id = SDL_CreateHapticEffect(haptic, &haptic->rumble_effect);
    if (haptic->rumble_id >= 0) {
        return true;
    }
    return false;
}
References SDL_HapticPeriodic::attack_length, CHECK_HAPTIC_MAGIC, SDL_HapticPeriodic::direction, SDL_HapticPeriodic::fade_length, SDL_HapticLeftRight::large_magnitude, SDL_HapticEffect::leftright, SDL_HapticLeftRight::length, SDL_HapticPeriodic::length, SDL_HapticPeriodic::magnitude, SDL_HapticPeriodic::period, SDL_HapticEffect::periodic, SDL_Haptic::rumble_effect, SDL_Haptic::rumble_id, SDL_CreateHapticEffect(), SDL_HAPTIC_CARTESIAN, SDL_HAPTIC_LEFTRIGHT, SDL_HAPTIC_SINE, SDL_SetError(), SDL_zerop, SDL_HapticLeftRight::small_magnitude, SDL_Haptic::supported, SDL_HapticDirection::type, and SDL_HapticEffect::type.
SDL_IsJoystickHaptic()
SDL_DECLSPEC bool SDLCALL SDL_IsJoystickHaptic (SDL_Joystick * joystick) extern
Query if a joystick has haptic features.
Parameters
joystick the SDL_Joystick to test for haptic capabilities.
Returns
true if the joystick is haptic or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHapticFromJoystick
{
    bool result = false;
    SDL_LockJoysticks();
    {
        // Must be a valid joystick
        if (SDL_IsJoystickValid(joystick) &&
            !SDL_IsGamepad(SDL_GetJoystickID(joystick))) {
            #ifdef SDL_JOYSTICK_HIDAPI
            result = SDL_SYS_JoystickIsHaptic(joystick) || SDL_HIDAPI_JoystickIsHaptic(joystick);
            #else
            result = SDL_SYS_JoystickIsHaptic(joystick);
            #endif
        }
    }
    SDL_UnlockJoysticks();
    return result;
}
References SDL_GetJoystickID(), SDL_HIDAPI_JoystickIsHaptic(), SDL_IsGamepad(), SDL_IsJoystickValid(), SDL_LockJoysticks(), SDL_SYS_JoystickIsHaptic(), and SDL_UnlockJoysticks().
Referenced by SDL_OpenHapticFromJoystick().
SDL_IsMouseHaptic()
SDL_DECLSPEC bool SDLCALL SDL_IsMouseHaptic (void) extern
Query whether or not the current mouse has haptic capabilities.
Returns
true if the mouse is haptic or false if it isn't.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenHapticFromMouse
{
    if (SDL_SYS_HapticMouse() < 0) {
        return false;
    }
    return true;
}
References SDL_SYS_HapticMouse().
SDL_OpenHaptic()
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_OpenHaptic (SDL_HapticID instance_id) extern
Open a haptic device for use.
The index passed as an argument refers to the N'th haptic device on this system.
When opening a haptic device, its gain will be set to maximum and autocenter will be disabled. To modify these values use SDL_SetHapticGain() and SDL_SetHapticAutocenter().
Parameters
instance_id the haptic device instance ID.
Returns
the device identifier or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseHaptic
SDL_GetHaptics
SDL_OpenHapticFromJoystick
SDL_OpenHapticFromMouse
SDL_SetHapticAutocenter
SDL_SetHapticGain
{
    SDL_Haptic *haptic;
    SDL_Haptic *hapticlist;
    const char *name;
    int device_index = 0;
    if (!SDL_GetHapticIndex(instance_id, &device_index)) {
        return NULL;
    }
    hapticlist = SDL_haptics;
    /* If the haptic device is already open, return it
     * it is important that we have a single haptic device for each instance id
     */
    while (hapticlist) {
        if (instance_id == hapticlist->instance_id) {
            haptic = hapticlist;
            ++haptic->ref_count;
            return haptic;
        }
        hapticlist = hapticlist->next;
    }
    // Create the haptic device
    haptic = (SDL_Haptic *)SDL_calloc(1, sizeof(*haptic));
    if (!haptic) {
        return NULL;
    }
    // Initialize the haptic device
    haptic->instance_id = instance_id;
    haptic->rumble_id = -1;
    if (!SDL_SYS_HapticOpen(haptic)) {
        SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, false);
        SDL_free(haptic);
        return NULL;
    }
    if (!haptic->name) {
        name = SDL_SYS_HapticName(device_index);
        if (name) {
            haptic->name = SDL_strdup(name);
        }
    }
    // Add haptic to list
    ++haptic->ref_count;
    // Link the haptic in the list
    haptic->next = SDL_haptics;
    SDL_haptics = haptic;
    SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, true);
    // Disable autocenter and set gain to max.
    if (haptic->supported & SDL_HAPTIC_GAIN) {
        SDL_SetHapticGain(haptic, 100);
    }
    if (haptic->supported & SDL_HAPTIC_AUTOCENTER) {
        SDL_SetHapticAutocenter(haptic, 0);
    }
    return haptic;
}
References SDL_Haptic::instance_id, SDL_Haptic::name, SDL_Haptic::next, NULL, SDL_Haptic::ref_count, SDL_Haptic::rumble_id, SDL_calloc(), SDL_free(), SDL_GetHapticIndex(), SDL_HAPTIC_AUTOCENTER, SDL_HAPTIC_GAIN, SDL_haptics, SDL_OBJECT_TYPE_HAPTIC, SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_SetObjectValid(), SDL_strdup(), SDL_SYS_HapticName(), SDL_SYS_HapticOpen(), and SDL_Haptic::supported.
Referenced by SDL_OpenHapticFromMouse().
SDL_OpenHapticFromJoystick()
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_OpenHapticFromJoystick (SDL_Joystick * joystick) extern
Open a haptic device for use from a joystick device.
You must still close the haptic device separately. It will not be closed with the joystick.
When opened from a joystick you should first close the haptic device before closing the joystick device. If not, on some implementations the haptic device will also get unallocated and you'll be unable to use force feedback on that device.
Parameters
joystick the SDL_Joystick to create a haptic device from.
Returns
a valid haptic device identifier on success or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseHaptic
SDL_IsJoystickHaptic
{
    SDL_Haptic *haptic;
    SDL_Haptic *hapticlist;
    SDL_LockJoysticks();
    {
        // Joystick must be valid and haptic
        if (!SDL_IsJoystickHaptic(joystick)) {
            SDL_SetError("Haptic: Joystick isn't a haptic device.");
            SDL_UnlockJoysticks();
            return NULL;
        }
        hapticlist = SDL_haptics;
        // Check to see if joystick's haptic is already open
        while (hapticlist) {
            #ifdef SDL_JOYSTICK_HIDAPI
            if (SDL_SYS_JoystickSameHaptic(hapticlist, joystick) || SDL_HIDAPI_JoystickSameHaptic(hapticlist, joystick)) {
            #else
            if (SDL_SYS_JoystickSameHaptic(hapticlist, joystick)) {
            #endif
                haptic = hapticlist;
                ++haptic->ref_count;
                SDL_UnlockJoysticks();
                return haptic;
            }
            hapticlist = hapticlist->next;
        }
        // Create the haptic device
        haptic = (SDL_Haptic *)SDL_calloc(1, sizeof(*haptic));
        if (!haptic) {
            SDL_UnlockJoysticks();
            return NULL;
        }
        /* Initialize the haptic device
         * This function should fill in the instance ID and name.
         */
        SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, true);
        haptic->rumble_id = -1;
        #ifdef SDL_JOYSTICK_HIDAPI
        if (SDL_HIDAPI_JoystickIsHaptic(joystick)) {
            if (!SDL_HIDAPI_HapticOpenFromJoystick(haptic, joystick)) {
                SDL_SetError("Haptic: SDL_HIDAPI_HapticOpenFromJoystick failed.");
                SDL_free(haptic);
                SDL_UnlockJoysticks();
                return NULL;
            }
        } else
        #endif
        if (!SDL_SYS_HapticOpenFromJoystick(haptic, joystick)) {
            SDL_SetError("Haptic: SDL_SYS_HapticOpenFromJoystick failed.");
            SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, false);
            SDL_free(haptic);
            SDL_UnlockJoysticks();
            return NULL;
        }
        SDL_assert(haptic->instance_id != 0);
    }
    SDL_UnlockJoysticks();
    // Check if custom number of haptic axes was defined
    Uint16 vid = SDL_GetJoystickVendor(joystick);
    Uint16 pid = SDL_GetJoystickProduct(joystick);
    int general_axes = SDL_GetNumJoystickAxes(joystick);
    int naxes = SDL_Haptic_Get_Naxes(vid, pid);
    if (naxes > 0)
        haptic->naxes = naxes;
    // Limit to the actual number of axes found on the device
    if (general_axes >= 0 && naxes > general_axes)
        haptic->naxes = general_axes;
    // Add haptic to list
    ++haptic->ref_count;
    // Link the haptic in the list
    haptic->next = SDL_haptics;
    SDL_haptics = haptic;
    SDL_SetObjectValid(haptic, SDL_OBJECT_TYPE_HAPTIC, true);
    // Disable autocenter and set gain to max.
    if (haptic->supported & SDL_HAPTIC_GAIN) {
        SDL_SetHapticGain(haptic, 100);
    }
    if (haptic->supported & SDL_HAPTIC_AUTOCENTER) {
        SDL_SetHapticAutocenter(haptic, 0);
    }
    return haptic;
}
References SDL_Haptic::instance_id, SDL_Haptic::naxes, SDL_Haptic::next, NULL, SDL_Haptic::ref_count, SDL_Haptic::rumble_id, SDL_assert, SDL_calloc(), SDL_free(), SDL_GetJoystickProduct(), SDL_GetJoystickVendor(), SDL_GetNumJoystickAxes(), SDL_HAPTIC_AUTOCENTER, SDL_HAPTIC_GAIN, SDL_Haptic_Get_Naxes(), SDL_haptics, SDL_HIDAPI_HapticOpenFromJoystick(), SDL_HIDAPI_JoystickIsHaptic(), SDL_HIDAPI_JoystickSameHaptic(), SDL_IsJoystickHaptic(), SDL_LockJoysticks(), SDL_OBJECT_TYPE_HAPTIC, SDL_SetError(), SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_SetObjectValid(), SDL_SYS_HapticOpenFromJoystick(), SDL_SYS_JoystickSameHaptic(), SDL_UnlockJoysticks(), and SDL_Haptic::supported.
SDL_OpenHapticFromMouse()
SDL_DECLSPEC SDL_Haptic *SDLCALL SDL_OpenHapticFromMouse (void) extern
Try to open a haptic device from the current mouse.
Returns
the haptic device identifier or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseHaptic
SDL_IsMouseHaptic
{
    int device_index;
    device_index = SDL_SYS_HapticMouse();
    if (device_index < 0) {
        SDL_SetError("Haptic: Mouse isn't a haptic device.");
        return NULL;
    }
    return SDL_OpenHaptic(device_index);
}
References NULL, SDL_OpenHaptic(), SDL_SetError(), and SDL_SYS_HapticMouse().
SDL_PauseHaptic()
SDL_DECLSPEC bool SDLCALL SDL_PauseHaptic (SDL_Haptic * haptic) extern
Pause a haptic device.
Device must support the SDL_HAPTIC_PAUSE feature. Call SDL_ResumeHaptic() to resume playback.
Do not modify the effects nor add new ones while the device is paused. That can cause all sorts of weird errors.
Parameters
haptic the SDL_Haptic device to pause.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_ResumeHaptic
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_PAUSE)) {
        return SDL_SetError("Haptic: Device does not support setting pausing.");
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticPause(haptic);
    }
    #endif
    return SDL_SYS_HapticPause(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_PAUSE, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticPause(), SDL_SetError(), SDL_SYS_HapticPause(), and SDL_Haptic::supported.
SDL_PlayHapticRumble()
SDL_DECLSPEC bool SDLCALL SDL_PlayHapticRumble (SDL_Haptic * haptic, float strength, Uint32 length) extern
Run a simple rumble effect on a haptic device.
Parameters
haptic the haptic device to play the rumble effect on.
strength strength of the rumble to play as a 0-1 float value.
length length of the rumble to play in milliseconds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_InitHapticRumble
SDL_StopHapticRumble
{
    SDL_HapticEffect *efx;
    Sint16 magnitude;
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (haptic->rumble_id < 0) {
        return SDL_SetError("Haptic: Rumble effect not initialized on haptic device");
    }
    // Clamp strength.
    if (strength > 1.0f) {
        strength = 1.0f;
    } else if (strength < 0.0f) {
        strength = 0.0f;
    }
    magnitude = (Sint16)(32767.0f * strength);
    efx = &haptic->rumble_effect;
    if (efx->type == SDL_HAPTIC_SINE) {
        efx->periodic.magnitude = magnitude;
        efx->periodic.length = length;
    } else if (efx->type == SDL_HAPTIC_LEFTRIGHT) {
        efx->leftright.small_magnitude = efx->leftright.large_magnitude = magnitude;
        efx->leftright.length = length;
    } else {
        SDL_assert(!"This should have been caught elsewhere");
    }
    if (!SDL_UpdateHapticEffect(haptic, haptic->rumble_id, &haptic->rumble_effect)) {
        return false;
    }
    return SDL_RunHapticEffect(haptic, haptic->rumble_id, 1);
}
References CHECK_HAPTIC_MAGIC, SDL_HapticLeftRight::large_magnitude, SDL_HapticEffect::leftright, SDL_HapticLeftRight::length, SDL_HapticPeriodic::length, SDL_HapticPeriodic::magnitude, SDL_HapticEffect::periodic, SDL_Haptic::rumble_effect, SDL_Haptic::rumble_id, SDL_assert, SDL_HAPTIC_LEFTRIGHT, SDL_HAPTIC_SINE, SDL_RunHapticEffect(), SDL_SetError(), SDL_UpdateHapticEffect(), SDL_HapticLeftRight::small_magnitude, and SDL_HapticEffect::type.
SDL_ResumeHaptic()
SDL_DECLSPEC bool SDLCALL SDL_ResumeHaptic (SDL_Haptic * haptic) extern
Resume a haptic device.
Call to unpause after SDL_PauseHaptic().
Parameters
haptic the SDL_Haptic device to unpause.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_PauseHaptic
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_PAUSE)) {
        return true; // Not going to be paused, so we pretend it's unpaused.
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticResume(haptic);
    }
    #endif
    return SDL_SYS_HapticResume(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_PAUSE, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticResume(), SDL_SYS_HapticResume(), and SDL_Haptic::supported.
SDL_RunHapticEffect()
SDL_DECLSPEC bool SDLCALL SDL_RunHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect, Uint32 iterations) extern
Run the haptic effect on its associated haptic device.
To repeat the effect over and over indefinitely, set iterations to SDL_HAPTIC_INFINITY. (Repeats the envelope - attack and fade.) To make one instance of the effect last indefinitely (so the effect does not fade), set the effect's length in its structure/union to SDL_HAPTIC_INFINITY instead.
Parameters
haptic the SDL_Haptic device to run the effect on.
effect the ID of the haptic effect to run.
iterations the number of iterations to run the effect; use SDL_HAPTIC_INFINITY to repeat forever.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticEffectStatus
SDL_StopHapticEffect
SDL_StopHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticRunEffect(haptic, effect, iterations);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    // Run the effect
    if (!SDL_SYS_HapticRunEffect(haptic, &haptic->effects[effect], iterations)) {
        return false;
    }
    return true;
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticRunEffect(), SDL_SYS_HapticRunEffect(), and ValidEffect().
Referenced by SDL_PlayHapticRumble().
SDL_SetHapticAutocenter()
SDL_DECLSPEC bool SDLCALL SDL_SetHapticAutocenter (SDL_Haptic * haptic, int autocenter) extern
Set the global autocenter of the device.
Autocenter should be between 0 and 100. Setting it to 0 will disable autocentering.
Device must support the SDL_HAPTIC_AUTOCENTER feature.
Parameters
haptic the SDL_Haptic device to set autocentering on.
autocenter value to set autocenter to (0-100).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticFeatures
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_AUTOCENTER)) {
        return SDL_SetError("Haptic: Device does not support setting autocenter.");
    }
    if ((autocenter < 0) || (autocenter > 100)) {
        return SDL_SetError("Haptic: Autocenter must be between 0 and 100.");
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticSetAutocenter(haptic, autocenter);
    }
    #endif
    return SDL_SYS_HapticSetAutocenter(haptic, autocenter);
}
References CHECK_HAPTIC_MAGIC, SDL_HAPTIC_AUTOCENTER, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticSetAutocenter(), SDL_SetError(), SDL_SYS_HapticSetAutocenter(), and SDL_Haptic::supported.
Referenced by SDL_OpenHaptic(), and SDL_OpenHapticFromJoystick().
SDL_SetHapticGain()
SDL_DECLSPEC bool SDLCALL SDL_SetHapticGain (SDL_Haptic * haptic, int gain) extern
Set the global gain of the specified haptic device.
Device must support the SDL_HAPTIC_GAIN feature.
The user may specify the maximum gain by setting the environment variable SDL_HAPTIC_GAIN_MAX which should be between 0 and 100. All calls to SDL_SetHapticGain() will scale linearly using SDL_HAPTIC_GAIN_MAX as the maximum.
Parameters
haptic the SDL_Haptic device to set the gain on.
gain value to set the gain to, should be between 0 and 100 (0 - 100).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetHapticFeatures
{
    const char *env;
    int real_gain, max_gain;
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (!(haptic->supported & SDL_HAPTIC_GAIN)) {
        return SDL_SetError("Haptic: Device does not support setting gain.");
    }
    if ((gain < 0) || (gain > 100)) {
        return SDL_SetError("Haptic: Gain must be between 0 and 100.");
    }
    // The user can use an environment variable to override the max gain.
    env = SDL_getenv("SDL_HAPTIC_GAIN_MAX");
    if (env) {
        max_gain = SDL_atoi(env);
        // Check for sanity.
        if (max_gain < 0) {
            max_gain = 0;
        } else if (max_gain > 100) {
            max_gain = 100;
        }
        // We'll scale it linearly with SDL_HAPTIC_GAIN_MAX
        real_gain = (gain * max_gain) / 100;
    } else {
        real_gain = gain;
    }
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticSetGain(haptic, real_gain);
    }
    #endif
    return SDL_SYS_HapticSetGain(haptic, real_gain);
}
References CHECK_HAPTIC_MAGIC, SDL_atoi(), SDL_getenv(), SDL_HAPTIC_GAIN, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticSetGain(), SDL_SetError(), SDL_SYS_HapticSetGain(), and SDL_Haptic::supported.
Referenced by SDL_OpenHaptic(), and SDL_OpenHapticFromJoystick().
SDL_StopHapticEffect()
SDL_DECLSPEC bool SDLCALL SDL_StopHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect) extern
Stop the haptic effect on its associated haptic device.
Parameters
haptic the SDL_Haptic device to stop the effect on.
effect the ID of the haptic effect to stop.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_RunHapticEffect
SDL_StopHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticStopEffect(haptic, effect);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    // Stop the effect
    if (!SDL_SYS_HapticStopEffect(haptic, &haptic->effects[effect])) {
        return false;
    }
    return true;
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::effects, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticStopEffect(), SDL_SYS_HapticStopEffect(), and ValidEffect().
Referenced by SDL_StopHapticRumble().
SDL_StopHapticEffects()
SDL_DECLSPEC bool SDLCALL SDL_StopHapticEffects (SDL_Haptic * haptic) extern
Stop all the currently playing effects on a haptic device.
Parameters
haptic the SDL_Haptic device to stop.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_RunHapticEffect
SDL_StopHapticEffects
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticStopAll(haptic);
    }
    #endif
    return SDL_SYS_HapticStopAll(haptic);
}
References CHECK_HAPTIC_MAGIC, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticStopAll(), and SDL_SYS_HapticStopAll().
SDL_StopHapticRumble()
SDL_DECLSPEC bool SDLCALL SDL_StopHapticRumble (SDL_Haptic * haptic) extern
Stop the simple rumble on a haptic device.
Parameters
haptic the haptic device to stop the rumble effect on.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_PlayHapticRumble
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    if (haptic->rumble_id < 0) {
        return SDL_SetError("Haptic: Rumble effect not initialized on haptic device");
    }
    return SDL_StopHapticEffect(haptic, haptic->rumble_id);
}
References CHECK_HAPTIC_MAGIC, SDL_Haptic::rumble_id, SDL_SetError(), and SDL_StopHapticEffect().
SDL_UpdateHapticEffect()
SDL_DECLSPEC bool SDLCALL SDL_UpdateHapticEffect (SDL_Haptic * haptic, SDL_HapticEffectID effect, const SDL_HapticEffect * data) extern
Update the properties of an effect.
Can be used dynamically, although behavior when dynamically changing direction may be strange. Specifically the effect may re-upload itself and start playing from the start. You also cannot change the type either when running SDL_UpdateHapticEffect().
Parameters
haptic the SDL_Haptic device that has the effect.
effect the identifier of the effect to update.
data an SDL_HapticEffect structure containing the new effect properties to use.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateHapticEffect
SDL_RunHapticEffect
{
    CHECK_HAPTIC_MAGIC(haptic, false);
    #ifdef SDL_JOYSTICK_HIDAPI
    if (SDL_HIDAPI_HapticIsHidapi(haptic)) {
        return SDL_HIDAPI_HapticUpdateEffect(haptic, effect, data);
    }
    #endif
    if (!ValidEffect(haptic, effect)) {
        return false;
    }
    if (!data) {
        return SDL_InvalidParamError("data");
    }
    // Can't change type dynamically.
    if (data->type != haptic->effects[effect].effect.type) {
        return SDL_SetError("Haptic: Updating effect type is illegal.");
    }
    // Updates the effect
    if (!SDL_SYS_HapticUpdateEffect(haptic, &haptic->effects[effect], data)) {
        return false;
    }
    SDL_memcpy(&haptic->effects[effect].effect, data,
               sizeof(SDL_HapticEffect));
    return true;
}
References CHECK_HAPTIC_MAGIC, haptic_effect::effect, SDL_Haptic::effects, SDL_HIDAPI_HapticIsHidapi(), SDL_HIDAPI_HapticUpdateEffect(), SDL_InvalidParamError, SDL_memcpy, SDL_SetError(), SDL_SYS_HapticUpdateEffect(), SDL_HapticEffect::type, and ValidEffect().
Referenced by SDL_PlayHapticRumble().