SDL3: SDL_AsyncIOQueueInterface Struct Reference
SDL_AsyncIOQueueInterface Struct Reference
#include <SDL_sysasyncio.h>
Data Fields
void(* cancel_task)(void *userdata, SDL_AsyncIOTask *task)
void(* destroy)(void *userdata)
SDL_AsyncIOTask *(* get_results)(void *userdata)
bool(* queue_task)(void *userdata, SDL_AsyncIOTask *task)
void(* signal)(void *userdata)
SDL_AsyncIOTask *(* wait_results)(void *userdata, Sint32 timeoutMS)
Field Documentation
cancel_task
void(* SDL_AsyncIOQueueInterface::cancel_task) (void *userdata, SDL_AsyncIOTask *task)
destroy
void(* SDL_AsyncIOQueueInterface::destroy) (void *userdata)
Referenced by SDL_DestroyAsyncIOQueue().
get_results
SDL_AsyncIOTask *(* SDL_AsyncIOQueueInterface::get_results) (void *userdata)
Referenced by SDL_GetAsyncIOResult().
queue_task
bool(* SDL_AsyncIOQueueInterface::queue_task) (void *userdata, SDL_AsyncIOTask *task)
Referenced by generic_asyncio_io().
signal
void(* SDL_AsyncIOQueueInterface::signal) (void *userdata)
Referenced by SDL_SignalAsyncIOQueue().
wait_results
SDL_AsyncIOTask *(* SDL_AsyncIOQueueInterface::wait_results) (void *userdata, Sint32 timeoutMS)
Referenced by SDL_DestroyAsyncIOQueue(), and SDL_WaitAsyncIOResult().
The documentation for this struct was generated from the following file:
SDL-main/src/io/SDL_sysasyncio.h