SDL3: SDL-main/src/tray/unix/SDL_tray.c File Reference
SDL_tray.c File Reference
#include "SDL_internal.h"
#include "../SDL_tray_utils.h"
#include <dlfcn.h>
#include <errno.h>
#include <unistd.h>
Data Structures
struct SDL_Tray
struct SDL_TrayEntry
struct SDL_TrayMenu
Macros
#define _G_TYPE_CIC(ip, gt, ct)
#define FALSE 0
#define G_CALLBACK(f)
#define g_signal_connect(instance, detailed_signal, c_handler, data)
#define G_TYPE_CHECK_INSTANCE_CAST(instance, g_type, c_type)
#define GTK_CHECK_MENU_ITEM(obj)
#define GTK_MENU(obj)
#define GTK_MENU_ITEM(obj)
#define GTK_WIDGET(widget)
#define ICON_DIR_TEMPLATE "/tmp/SDL-tray-XXXXXX"
#define TRUE 1
Typedefs
typedef struct _AppIndicator AppIndicator
typedef gint gboolean
typedef void(* GCallback) (void)
typedef char gchar
typedef struct _GClosure GClosure
typedef void(* GClosureNotify) (gpointer data, GClosure *closure)
typedef int gint
typedef void * gpointer
typedef gboolean(* GSourceFunc) (gpointer user_data)
typedef struct _GtkCheckMenuItem GtkCheckMenuItem
typedef struct _GtkMenu GtkMenu
typedef struct _GtkMenuItem GtkMenuItem
typedef struct _GtkMenuShell GtkMenuShell
typedef struct _GtkWidget GtkWidget
typedef unsigned int guint
typedef unsigned long gulong
Enumerations
enum AppIndicatorCategory {
APP_INDICATOR_CATEGORY_APPLICATION_STATUS , APP_INDICATOR_CATEGORY_COMMUNICATIONS , APP_INDICATOR_CATEGORY_SYSTEM_SERVICES , APP_INDICATOR_CATEGORY_HARDWARE ,
APP_INDICATOR_CATEGORY_OTHER
}
enum AppIndicatorStatus { APP_INDICATOR_STATUS_PASSIVE , APP_INDICATOR_STATUS_ACTIVE , APP_INDICATOR_STATUS_ATTENTION }
enum GConnectFlags { G_CONNECT_AFTER = 1 << 0 , G_CONNECT_SWAPPED = 1 << 1 }
Functions
static void call_callback (GtkMenuItem *item, gpointer ptr)
static void DestroySDLMenu (SDL_TrayMenu *menu)
static void * find_lib (const char **names)
static const char * get_appindicator_id (void)
static bool init_gtk (void)
static bool new_tmp_filename (SDL_Tray *tray)
static void quit_gtk (void)
void SDL_ClickTrayEntry (SDL_TrayEntry *entry)
SDL_Tray * SDL_CreateTray (SDL_Surface *icon, const char *tooltip)
SDL_TrayMenu * SDL_CreateTrayMenu (SDL_Tray *tray)
SDL_TrayMenu * SDL_CreateTraySubmenu (SDL_TrayEntry *entry)
void SDL_DestroyTray (SDL_Tray *tray)
const SDL_TrayEntry ** SDL_GetTrayEntries (SDL_TrayMenu *menu, int *count)
bool SDL_GetTrayEntryChecked (SDL_TrayEntry *entry)
bool SDL_GetTrayEntryEnabled (SDL_TrayEntry *entry)
const char * SDL_GetTrayEntryLabel (SDL_TrayEntry *entry)
SDL_TrayMenu * SDL_GetTrayEntryParent (SDL_TrayEntry *entry)
SDL_TrayMenu * SDL_GetTrayMenu (SDL_Tray *tray)
SDL_TrayEntry * SDL_GetTrayMenuParentEntry (SDL_TrayMenu *menu)
SDL_Tray * SDL_GetTrayMenuParentTray (SDL_TrayMenu *menu)
SDL_TrayMenu * SDL_GetTraySubmenu (SDL_TrayEntry *entry)
SDL_TrayEntry * SDL_InsertTrayEntryAt (SDL_TrayMenu *menu, int pos, const char *label, SDL_TrayEntryFlags flags)
bool SDL_IsTraySupported (void)
void SDL_RemoveTrayEntry (SDL_TrayEntry *entry)
void SDL_SetTrayEntryCallback (SDL_TrayEntry *entry, SDL_TrayCallback callback, void *userdata)
void SDL_SetTrayEntryChecked (SDL_TrayEntry *entry, bool checked)
void SDL_SetTrayEntryEnabled (SDL_TrayEntry *entry, bool enabled)
void SDL_SetTrayEntryLabel (SDL_TrayEntry *entry, const char *label)
void SDL_SetTrayIcon (SDL_Tray *tray, SDL_Surface *icon)
void SDL_SetTrayTooltip (SDL_Tray *tray, const char *tooltip)
void SDL_UpdateTrays (void)
Variables
static AppIndicator *(* app_indicator_new)(const gchar *id, const gchar *icon_name, AppIndicatorCategory category)
static void(* app_indicator_set_icon)(AppIndicator *self, const gchar *icon_name)
static void(* app_indicator_set_menu)(AppIndicator *self, GtkMenu *menu)
static void(* app_indicator_set_status)(AppIndicator *self, AppIndicatorStatus status)
const char * appindicator_names []
static gchar *(* g_mkdtemp)(gchar *template)
static gpointer(* g_object_ref)(gpointer object)
static gpointer(* g_object_ref_sink)(gpointer object)
static void(* g_object_unref)(gpointer object)
static gulong(* g_signal_connect_data)(gpointer instance, const gchar *detailed_signal, GCallback c_handler, gpointer data, GClosureNotify destroy_data, GConnectFlags connect_flags)
const char * gdk_names []
static gboolean(* gtk_check_menu_item_get_active)(GtkCheckMenuItem *check_menu_item)
static GtkWidget *(* gtk_check_menu_item_new_with_label)(const gchar *label)
static void(* gtk_check_menu_item_set_active)(GtkCheckMenuItem *check_menu_item, gboolean is_active)
static gboolean(* gtk_init_check)(int *argc, char ***argv)
static bool gtk_is_init = false
static gboolean(* gtk_main_iteration_do)(gboolean blocking)
static const gchar *(* gtk_menu_item_get_label)(GtkMenuItem *menu_item)
static GtkWidget *(* gtk_menu_item_new_with_label)(const gchar *label)
static void(* gtk_menu_item_set_label)(GtkMenuItem *menu_item, const gchar *label)
static void(* gtk_menu_item_set_submenu)(GtkMenuItem *menu_item, GtkWidget *submenu)
static GtkWidget *(* gtk_menu_new)(void)
static void(* gtk_menu_shell_append)(GtkMenuShell *menu_shell, GtkWidget *child)
static void(* gtk_menu_shell_insert)(GtkMenuShell *menu_shell, GtkWidget *child, gint position)
const char * gtk_names []
static GtkWidget *(* gtk_separator_menu_item_new)(void)
static void(* gtk_widget_destroy)(GtkWidget *widget)
static gboolean(* gtk_widget_get_sensitive)(GtkWidget *widget)
static void(* gtk_widget_set_sensitive)(GtkWidget *widget, gboolean sensitive)
static void(* gtk_widget_show)(GtkWidget *widget)
static void * libappindicator = NULL
static void * libgdk = NULL
static void * libgtk = NULL
Macro Definition Documentation
_G_TYPE_CIC
#define _G_TYPE_CIC (ip, gt, ct)
Value:
((ct*) ip)
FALSE
#define FALSE 0
Referenced by decode_detailed_timing(), decode_header(), decode_vendor_and_product_identification(), get_string_property(), init_gtk(), IsWindowsVersionOrGreater(), new_hid_device(), OutOfMemory(), PLATFORM_hid_enumerate(), PLATFORM_hid_exit(), PLATFORM_hid_open_path(), PLATFORM_hid_read_timeout(), PLATFORM_hid_send_feature_report(), PLATFORM_hid_write(), process_pending_events(), read_thread(), SDL_GetTrayEntryChecked(), SDL_GetTrayEntryEnabled(), SDL_hid_winapi_descriptor_reconstruct_pp_data(), SDL_SetTrayEntryLabel(), SDL_SYS_GetPrefPath(), and SDL_UpdateTrays().
G_CALLBACK
#define G_CALLBACK (f)
Value:
((GCallback) (f))
Referenced by SDL_InsertTrayEntryAt().
g_signal_connect
#define g_signal_connect (instance, detailed_signal, c_handler, data)
Value:
    g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
#define g_signal_connect(instance, detailed_signal, c_handler, data) \
    g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
Referenced by SDL_InsertTrayEntryAt().
G_TYPE_CHECK_INSTANCE_CAST
#define G_TYPE_CHECK_INSTANCE_CAST (instance, g_type, c_type)
Value:
(_G_TYPE_CIC ((instance), (g_type), c_type))
GTK_CHECK_MENU_ITEM
#define GTK_CHECK_MENU_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_CHECK_MENU_ITEM, GtkCheckMenuItem))
Referenced by SDL_GetTrayEntryChecked(), SDL_InsertTrayEntryAt(), and SDL_SetTrayEntryChecked().
GTK_MENU
#define GTK_MENU (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_MENU, GtkMenu))
Referenced by SDL_CreateTray().
GTK_MENU_ITEM
#define GTK_MENU_ITEM (obj)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((obj), GTK_TYPE_MENU_ITEM, GtkMenuItem))
Referenced by SDL_CreateTraySubmenu(), SDL_GetTrayEntryLabel(), and SDL_SetTrayEntryLabel().
GTK_WIDGET
#define GTK_WIDGET (widget)
Value:
(G_TYPE_CHECK_INSTANCE_CAST ((widget), GTK_TYPE_WIDGET, GtkWidget))
Referenced by SDL_CreateTraySubmenu().
ICON_DIR_TEMPLATE
#define ICON_DIR_TEMPLATE "/tmp/SDL-tray-XXXXXX"
Referenced by SDL_CreateTray().
TRUE
#define TRUE 1
Referenced by browse_callback_proc(), CreateIconFromSurface(), decode_color_characteristics(), decode_descriptors(), decode_display_parameters(), decode_edid_version(), decode_established_timings(), decode_header(), decode_standard_timings(), decode_vendor_and_product_identification(), hid_get_report(), new_hid_device(), PLATFORM_hid_close(), PLATFORM_hid_init(), PLATFORM_hid_open_path(), PLATFORM_hid_read_timeout(), PLATFORM_hid_write(), SDL_hid_winapi_descriptor_reconstruct_pp_data(), and SDL_WaitConditionTimeoutNS_cv().
Typedef Documentation
AppIndicator
typedef struct _AppIndicator AppIndicator
gboolean
typedef gint gboolean
GCallback
typedef void(* GCallback) (void)
gchar
typedef char gchar
GClosure
typedef struct _GClosure GClosure
GClosureNotify
typedef void(* GClosureNotify) (gpointer data, GClosure *closure)
gint
typedef int gint
gpointer
typedef void* gpointer
GSourceFunc
typedef gboolean(* GSourceFunc) (gpointer user_data)
GtkCheckMenuItem
typedef struct _GtkCheckMenuItem GtkCheckMenuItem
GtkMenu
typedef struct _GtkMenu GtkMenu
GtkMenuItem
typedef struct _GtkMenuItem GtkMenuItem
GtkMenuShell
typedef struct _GtkMenuShell GtkMenuShell
GtkWidget
typedef struct _GtkWidget GtkWidget
guint
typedef unsigned int guint
gulong
typedef unsigned long gulong
Enumeration Type Documentation
AppIndicatorCategory
enum AppIndicatorCategory
Enumerator
APP_INDICATOR_CATEGORY_APPLICATION_STATUS
APP_INDICATOR_CATEGORY_COMMUNICATIONS
APP_INDICATOR_CATEGORY_SYSTEM_SERVICES
APP_INDICATOR_CATEGORY_HARDWARE
APP_INDICATOR_CATEGORY_OTHER
             {
    APP_INDICATOR_CATEGORY_APPLICATION_STATUS,
    APP_INDICATOR_CATEGORY_COMMUNICATIONS,
    APP_INDICATOR_CATEGORY_SYSTEM_SERVICES,
    APP_INDICATOR_CATEGORY_HARDWARE,
    APP_INDICATOR_CATEGORY_OTHER
} AppIndicatorCategory;
AppIndicatorStatus
enum AppIndicatorStatus
Enumerator
APP_INDICATOR_STATUS_PASSIVE
APP_INDICATOR_STATUS_ACTIVE
APP_INDICATOR_STATUS_ATTENTION
             {
    APP_INDICATOR_STATUS_PASSIVE,
    APP_INDICATOR_STATUS_ACTIVE,
    APP_INDICATOR_STATUS_ATTENTION
} AppIndicatorStatus;
GConnectFlags
enum GConnectFlags
Enumerator
G_CONNECT_AFTER
G_CONNECT_SWAPPED
{
    G_CONNECT_AFTER = 1 << 0,
    G_CONNECT_SWAPPED = 1 << 1
} GConnectFlags;
Function Documentation
call_callback()
void call_callback (GtkMenuItem * item, gpointer ptr) static
{
    SDL_TrayEntry *entry = ptr;
    /* Not needed with AppIndicator, may be needed with other frameworks */
    /* if (entry->flags & SDL_TRAYENTRY_CHECKBOX) {
        SDL_SetTrayEntryChecked(entry, !SDL_GetTrayEntryChecked(entry));
    } */
    if (entry->ignore_signal) {
        return;
    }
    if (entry->callback) {
        entry->callback(entry->userdata, entry);
    }
}
References SDL_TrayEntry::callback, SDL_TrayEntry::ignore_signal, and SDL_TrayEntry::userdata.
Referenced by SDL_InsertTrayEntryAt().
DestroySDLMenu()
void DestroySDLMenu (SDL_TrayMenu * menu) static
{
    for (int i = 0; i < menu->nEntries; i++) {
        if (menu->entries[i] && menu->entries[i]->submenu) {
            DestroySDLMenu(menu->entries[i]->submenu);
        }
        SDL_free(menu->entries[i]);
    }
    if (menu->menu) {
        g_object_unref(menu->menu);
    }
    SDL_free(menu->entries);
    SDL_free(menu);
}
References DestroySDLMenu(), SDL_TrayMenu::entries, g_object_unref, SDL_TrayMenu::menu, SDL_TrayMenu::nEntries, SDL_free(), and SDL_TrayEntry::submenu.
Referenced by DestroySDLMenu(), SDL_DestroyTray(), and SDL_RemoveTrayEntry().
find_lib()
void * find_lib (const char ** names) static
{
    const char **name_ptr = names;
    void *handle = NULL;
    do {
        handle = dlopen(*name_ptr, RTLD_LAZY);
    } while (*++name_ptr && !handle);
    return handle;
}
References NULL.
Referenced by init_gtk().
get_appindicator_id()
const char * get_appindicator_id (void) static
{
    static int count = 0;
    static char buffer[256];
    int would_have_written = SDL_snprintf(buffer, sizeof(buffer), "sdl-appindicator-%d-%d", getpid(), count++);
    if (would_have_written <= 0 || would_have_written >= sizeof(buffer) - 1) {
        SDL_SetError("Couldn't fit %d bytes in buffer of size %d", would_have_written, (int) sizeof(buffer));
        return NULL;
    }
    return buffer;
}
References count, NULL, SDL_SetError(), and SDL_snprintf().
Referenced by SDL_CreateTray().
init_gtk()
bool init_gtk (void) static
{
    if (gtk_is_init) {
        return true;
    }
    libappindicator = find_lib(appindicator_names);
    libgtk = find_lib(gtk_names);
    libgdk = find_lib(gdk_names);
    if (!libappindicator || !libgtk || !libgdk) {
        quit_gtk();
        return SDL_SetError("Could not load GTK/AppIndicator libraries");
    }
    gtk_init_check = dlsym(libgtk, "gtk_init_check");
    gtk_main_iteration_do = dlsym(libgtk, "gtk_main_iteration_do");
    gtk_menu_new = dlsym(libgtk, "gtk_menu_new");
    gtk_separator_menu_item_new = dlsym(libgtk, "gtk_separator_menu_item_new");
    gtk_menu_item_new_with_label = dlsym(libgtk, "gtk_menu_item_new_with_label");
    gtk_menu_item_set_submenu = dlsym(libgtk, "gtk_menu_item_set_submenu");
    gtk_check_menu_item_new_with_label = dlsym(libgtk, "gtk_check_menu_item_new_with_label");
    gtk_check_menu_item_set_active = dlsym(libgtk, "gtk_check_menu_item_set_active");
    gtk_widget_set_sensitive = dlsym(libgtk, "gtk_widget_set_sensitive");
    gtk_widget_show = dlsym(libgtk, "gtk_widget_show");
    gtk_menu_shell_append = dlsym(libgtk, "gtk_menu_shell_append");
    gtk_menu_shell_insert = dlsym(libgtk, "gtk_menu_shell_insert");
    gtk_widget_destroy = dlsym(libgtk, "gtk_widget_destroy");
    gtk_menu_item_get_label = dlsym(libgtk, "gtk_menu_item_get_label");
    gtk_menu_item_set_label = dlsym(libgtk, "gtk_menu_item_set_label");
    gtk_check_menu_item_get_active = dlsym(libgtk, "gtk_check_menu_item_get_active");
    gtk_widget_get_sensitive = dlsym(libgtk, "gtk_widget_get_sensitive");
    /* Technically these are GLib or GObject functions, but we can find
     * them via GDK */
    g_mkdtemp = dlsym(libgdk, "g_mkdtemp");
    g_signal_connect_data = dlsym(libgdk, "g_signal_connect_data");
    g_object_unref = dlsym(libgdk, "g_object_unref");
    g_object_ref_sink = dlsym(libgdk, "g_object_ref_sink");
    g_object_ref = dlsym(libgdk, "g_object_ref");
    app_indicator_new = dlsym(libappindicator, "app_indicator_new");
    app_indicator_set_status = dlsym(libappindicator, "app_indicator_set_status");
    app_indicator_set_icon = dlsym(libappindicator, "app_indicator_set_icon");
    app_indicator_set_menu = dlsym(libappindicator, "app_indicator_set_menu");
    if (!gtk_init_check ||
        !gtk_main_iteration_do ||
        !gtk_menu_new ||
        !gtk_separator_menu_item_new ||
        !gtk_menu_item_new_with_label ||
        !gtk_menu_item_set_submenu ||
        !gtk_check_menu_item_new_with_label ||
        !gtk_check_menu_item_set_active ||
        !gtk_widget_set_sensitive ||
        !gtk_widget_show ||
        !gtk_menu_shell_append ||
        !gtk_menu_shell_insert ||
        !gtk_widget_destroy ||
        !g_mkdtemp ||
        !g_object_ref_sink ||
        !g_object_ref ||
        !g_signal_connect_data ||
        !g_object_unref ||
        !app_indicator_new ||
        !app_indicator_set_status ||
        !app_indicator_set_icon ||
        !app_indicator_set_menu ||
        !gtk_menu_item_get_label ||
        !gtk_menu_item_set_label ||
        !gtk_check_menu_item_get_active ||
        !gtk_widget_get_sensitive) {
        quit_gtk();
        return SDL_SetError("Could not load GTK/AppIndicator functions");
    }
    if (gtk_init_check(0, NULL) == FALSE) {
        quit_gtk();
        return SDL_SetError("Could not init GTK");
    }
    gtk_is_init = true;
    return true;
}
References app_indicator_new, app_indicator_set_icon, app_indicator_set_menu, app_indicator_set_status, appindicator_names, FALSE, find_lib(), g_mkdtemp, g_object_ref, g_object_ref_sink, g_object_unref, g_signal_connect_data, gdk_names, gtk_check_menu_item_get_active, gtk_check_menu_item_new_with_label, gtk_check_menu_item_set_active, gtk_init_check, gtk_is_init, gtk_main_iteration_do, gtk_menu_item_get_label, gtk_menu_item_new_with_label, gtk_menu_item_set_label, gtk_menu_item_set_submenu, gtk_menu_new, gtk_menu_shell_append, gtk_menu_shell_insert, gtk_names, gtk_separator_menu_item_new, gtk_widget_destroy, gtk_widget_get_sensitive, gtk_widget_set_sensitive, gtk_widget_show, libappindicator, libgdk, libgtk, NULL, quit_gtk(), and SDL_SetError().
Referenced by SDL_CreateTray(), and SDL_IsTraySupported().
new_tmp_filename()
bool new_tmp_filename (SDL_Tray * tray) static
{
    static int count = 0;
    int would_have_written = SDL_snprintf(tray->icon_path, sizeof(tray->icon_path), "%s/%d.bmp", tray->icon_dir, count++);
    if (would_have_written > 0 && ((unsigned) would_have_written) < sizeof(tray->icon_path) - 1) {
        return true;
    }
    tray->icon_path[0] = '\0';
    SDL_SetError("Failed to format new temporary filename");
    return false;
}
References count, SDL_Tray::icon_dir, SDL_Tray::icon_path, SDL_SetError(), and SDL_snprintf().
Referenced by SDL_CreateTray(), and SDL_SetTrayIcon().
quit_gtk()
void quit_gtk (void) static
{
    if (libappindicator) {
        dlclose(libappindicator);
        libappindicator = NULL;
    }
    if (libgtk) {
        dlclose(libgtk);
        libgtk = NULL;
    }
    if (libgdk) {
        dlclose(libgdk);
        libgdk = NULL;
    }
    gtk_is_init = false;
}
References gtk_is_init, libappindicator, libgdk, libgtk, and NULL.
Referenced by init_gtk().
SDL_ClickTrayEntry()
void SDL_ClickTrayEntry (SDL_TrayEntry * entry)
Simulate a click on a tray entry.
Parameters
entry The entry to activate.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
{
    if (!entry) {
        return;
    }
    if (entry->flags & SDL_TRAYENTRY_CHECKBOX) {
        SDL_SetTrayEntryChecked(entry, !SDL_GetTrayEntryChecked(entry));
    }
    if (entry->callback) {
        entry->callback(entry->userdata, entry);
    }
}
References SDL_TrayEntry::callback, SDL_TrayEntry::flags, SDL_GetTrayEntryChecked(), SDL_SetTrayEntryChecked(), SDL_TRAYENTRY_CHECKBOX, and SDL_TrayEntry::userdata.
SDL_CreateTray()
SDL_Tray * SDL_CreateTray (SDL_Surface * icon, const char * tooltip)
Create an icon to be placed in the operating system's tray, or equivalent.
Many platforms advise not using a system tray unless persistence is a necessary feature. Avoid needlessly creating a tray icon, as the user may feel like it clutters their interface.
Using tray icons require the video subsystem.
Parameters
icon a surface to be used as icon. May be NULL.
tooltip a tooltip to be displayed when the mouse hovers the icon in UTF-8 encoding. Not supported on all platforms. May be NULL.
Returns
The newly created system tray icon.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenu
SDL_DestroyTray
{
    if (!SDL_IsMainThread()) {
        SDL_SetError("This function should be called on the main thread");
        return NULL;
    }
    if (init_gtk() != true) {
        return NULL;
    }
    SDL_Tray *tray = (SDL_Tray *)SDL_calloc(1, sizeof(*tray));
    if (!tray) {
        return NULL;
    }
    /* On success, g_mkdtemp edits its argument in-place to replace the Xs
     * with a random directory name, which it creates safely and atomically.
     * On failure, it sets errno. */
    SDL_strlcpy(tray->icon_dir, ICON_DIR_TEMPLATE, sizeof(tray->icon_dir));
    if (!g_mkdtemp(tray->icon_dir)) {
        SDL_SetError("Cannot create directory for tray icon: %s", strerror(errno));
        SDL_free(tray);
        return NULL;
    }
    if (icon) {
        if (!new_tmp_filename(tray)) {
            SDL_free(tray);
            return NULL;
        }
        SDL_SaveBMP(icon, tray->icon_path);
    }
    tray->indicator = app_indicator_new(get_appindicator_id(), tray->icon_path,
                                        APP_INDICATOR_CATEGORY_APPLICATION_STATUS);
    app_indicator_set_status(tray->indicator, APP_INDICATOR_STATUS_ACTIVE);
    // The tray icon isn't shown before a menu is created; create one early.
    tray->menu_cached = (GtkMenuShell *) g_object_ref_sink(gtk_menu_new());
    app_indicator_set_menu(tray->indicator, GTK_MENU(tray->menu_cached));
    SDL_RegisterTray(tray);
    return tray;
}
References APP_INDICATOR_CATEGORY_APPLICATION_STATUS, app_indicator_new, app_indicator_set_menu, app_indicator_set_status, APP_INDICATOR_STATUS_ACTIVE, g_mkdtemp, g_object_ref_sink, get_appindicator_id(), GTK_MENU, gtk_menu_new, SDL_Tray::icon_dir, ICON_DIR_TEMPLATE, SDL_Tray::icon_path, SDL_Tray::indicator, init_gtk(), SDL_Tray::menu_cached, new_tmp_filename(), NULL, SDL_calloc(), SDL_free(), SDL_IsMainThread(), SDL_RegisterTray(), SDL_SaveBMP(), SDL_SetError(), and SDL_strlcpy().
SDL_CreateTrayMenu()
SDL_TrayMenu * SDL_CreateTrayMenu (SDL_Tray * tray)
Create a menu for a system tray.
This should be called at most once per tray icon.
This function does the same thing as SDL_CreateTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_GetTrayMenu
SDL_GetTrayMenuParentTray
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        SDL_InvalidParamError("tray");
        return NULL;
    }
    tray->menu = (SDL_TrayMenu *)SDL_calloc(1, sizeof(*tray->menu));
    if (!tray->menu) {
        return NULL;
    }
    tray->menu->menu = g_object_ref(tray->menu_cached);
    tray->menu->parent_tray = tray;
    tray->menu->parent_entry = NULL;
    tray->menu->nEntries = 0;
    tray->menu->entries = NULL;
    return tray->menu;
}
References SDL_TrayMenu::entries, g_object_ref, SDL_Tray::menu, SDL_TrayMenu::menu, SDL_Tray::menu_cached, SDL_TrayMenu::nEntries, NULL, SDL_TrayMenu::parent_entry, SDL_TrayMenu::parent_tray, SDL_calloc(), SDL_InvalidParamError, SDL_OBJECT_TYPE_TRAY, and SDL_ObjectValid().
SDL_CreateTraySubmenu()
SDL_TrayMenu * SDL_CreateTraySubmenu (SDL_TrayEntry * entry)
Create a submenu for a system tray entry.
This should be called at most once per tray entry.
This function does the same thing as SDL_CreateTrayMenu, except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_GetTraySubmenu
SDL_GetTrayMenuParentEntry
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    if (entry->submenu) {
        SDL_SetError("Tray entry submenu already exists");
        return NULL;
    }
    if (!(entry->flags & SDL_TRAYENTRY_SUBMENU)) {
        SDL_SetError("Cannot create submenu for entry not created with SDL_TRAYENTRY_SUBMENU");
        return NULL;
    }
    entry->submenu = (SDL_TrayMenu *)SDL_calloc(1, sizeof(*entry->submenu));
    if (!entry->submenu) {
        return NULL;
    }
    entry->submenu->menu = g_object_ref_sink(gtk_menu_new());
    entry->submenu->parent_tray = NULL;
    entry->submenu->parent_entry = entry;
    entry->submenu->nEntries = 0;
    entry->submenu->entries = NULL;
    gtk_menu_item_set_submenu(GTK_MENU_ITEM(entry->item), GTK_WIDGET(entry->submenu->menu));
    return entry->submenu;
}
References SDL_TrayMenu::entries, SDL_TrayEntry::flags, g_object_ref_sink, GTK_MENU_ITEM, gtk_menu_item_set_submenu, gtk_menu_new, GTK_WIDGET, SDL_TrayEntry::item, SDL_TrayMenu::menu, SDL_TrayMenu::nEntries, NULL, SDL_TrayMenu::parent_entry, SDL_TrayMenu::parent_tray, SDL_calloc(), SDL_InvalidParamError, SDL_SetError(), SDL_TRAYENTRY_SUBMENU, and SDL_TrayEntry::submenu.
SDL_DestroyTray()
void SDL_DestroyTray (SDL_Tray * tray)
Destroys a tray object.
This also destroys all associated menus and entries.
Parameters
tray the tray icon to be destroyed.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        return;
    }
    SDL_UnregisterTray(tray);
    if (tray->menu) {
        DestroySDLMenu(tray->menu);
    }
    if (*tray->icon_path) {
        SDL_RemovePath(tray->icon_path);
    }
    if (*tray->icon_dir) {
        SDL_RemovePath(tray->icon_dir);
    }
    if (tray->menu_cached) {
        g_object_unref(tray->menu_cached);
    }
    if (tray->indicator) {
        g_object_unref(tray->indicator);
    }
    SDL_free(tray);
}
References DestroySDLMenu(), g_object_unref, SDL_Tray::icon_dir, SDL_Tray::icon_path, SDL_Tray::indicator, SDL_Tray::menu, SDL_Tray::menu_cached, SDL_free(), SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), SDL_RemovePath(), and SDL_UnregisterTray().
SDL_GetTrayEntries()
const SDL_TrayEntry ** SDL_GetTrayEntries (SDL_TrayMenu * menu, int * count)
Returns a list of entries in the menu, in order.
Parameters
menu The menu to get entries from.
count An optional pointer to obtain the number of entries in the menu.
Returns
a NULL-terminated list of entries within the given menu. The pointer becomes invalid when any function that inserts or deletes entries in the menu is called.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_RemoveTrayEntry
SDL_InsertTrayEntryAt
{
    if (!menu) {
        SDL_InvalidParamError("menu");
        return NULL;
    }
    if (count) {
        *count = menu->nEntries;
    }
    return (const SDL_TrayEntry **)menu->entries;
}
References count, SDL_TrayMenu::entries, SDL_TrayMenu::nEntries, NULL, and SDL_InvalidParamError.
SDL_GetTrayEntryChecked()
bool SDL_GetTrayEntryChecked (SDL_TrayEntry * entry)
Gets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be read.
Returns
true if the entry is checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryChecked
{
    if (!entry || !(entry->flags & SDL_TRAYENTRY_CHECKBOX)) {
        return false;
    }
    return gtk_check_menu_item_get_active(GTK_CHECK_MENU_ITEM(entry->item));
}
References SDL_TrayEntry::flags, GTK_CHECK_MENU_ITEM, gtk_check_menu_item_get_active, SDL_TrayEntry::item, and SDL_TRAYENTRY_CHECKBOX.
SDL_GetTrayEntryEnabled()
bool SDL_GetTrayEntryEnabled (SDL_TrayEntry * entry)
Gets whether or not an entry is enabled.
Parameters
entry the entry to be read.
Returns
true if the entry is enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryEnabled
{
    if (!entry) {
        return false;
    }
    return gtk_widget_get_sensitive(entry->item);
}
References gtk_widget_get_sensitive, and SDL_TrayEntry::item.
SDL_GetTrayEntryLabel()
const char * SDL_GetTrayEntryLabel (SDL_TrayEntry * entry)
Gets the label of an entry.
If the returned value is NULL, the entry is a separator.
Parameters
entry the entry to be read.
Returns
the label of the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_SetTrayEntryLabel
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    return gtk_menu_item_get_label(GTK_MENU_ITEM(entry->item));
}
References GTK_MENU_ITEM, gtk_menu_item_get_label, SDL_TrayEntry::item, NULL, and SDL_InvalidParamError.
SDL_GetTrayEntryParent()
SDL_TrayMenu * SDL_GetTrayEntryParent (SDL_TrayEntry * entry)
Gets the menu containing a certain tray entry.
Parameters
entry the entry for which to get the parent menu.
Returns
the parent menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    return entry->parent;
}
References NULL, SDL_TrayEntry::parent, and SDL_InvalidParamError.
SDL_GetTrayMenu()
SDL_TrayMenu * SDL_GetTrayMenu (SDL_Tray * tray)
Gets a previously created tray menu.
You should have called SDL_CreateTrayMenu() on the tray object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTraySubmenu(), except that it takes a SDL_Tray instead of a SDL_TrayEntry.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
tray the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
SDL_CreateTrayMenu
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        SDL_InvalidParamError("tray");
        return NULL;
    }
    return tray->menu;
}
References SDL_Tray::menu, NULL, SDL_InvalidParamError, SDL_OBJECT_TYPE_TRAY, and SDL_ObjectValid().
SDL_GetTrayMenuParentEntry()
SDL_TrayEntry * SDL_GetTrayMenuParentEntry (SDL_TrayMenu * menu)
Gets the entry for which the menu is a submenu, if the current menu is a submenu.
Either this function or SDL_GetTrayMenuParentTray() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent entry.
Returns
the parent entry, or NULL if this menu is not a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTraySubmenu
SDL_GetTrayMenuParentTray
{
    return menu->parent_entry;
}
References SDL_TrayMenu::parent_entry.
SDL_GetTrayMenuParentTray()
SDL_Tray * SDL_GetTrayMenuParentTray (SDL_TrayMenu * menu)
Gets the tray for which this menu is the first-level menu, if the current menu isn't a submenu.
Either this function or SDL_GetTrayMenuParentEntry() will return non-NULL for any given menu.
Parameters
menu the menu for which to get the parent enttrayry.
Returns
the parent tray, or NULL if this menu is a submenu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTrayMenu
SDL_GetTrayMenuParentEntry
{
    if (!menu) {
        SDL_InvalidParamError("menu");
        return NULL;
    }
    return menu->parent_tray;
}
References NULL, SDL_TrayMenu::parent_tray, and SDL_InvalidParamError.
SDL_GetTraySubmenu()
SDL_TrayMenu * SDL_GetTraySubmenu (SDL_TrayEntry * entry)
Gets a previously created tray entry submenu.
You should have called SDL_CreateTraySubmenu() on the entry object. This function allows you to fetch it again later.
This function does the same thing as SDL_GetTrayMenu(), except that it takes a SDL_TrayEntry instead of a SDL_Tray.
A menu does not need to be destroyed; it will be destroyed with the tray.
Parameters
entry the tray entry to bind the menu to.
Returns
the newly created menu.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_InsertTrayEntryAt
SDL_CreateTraySubmenu
{
    if (!entry) {
        SDL_InvalidParamError("entry");
        return NULL;
    }
    return entry->submenu;
}
References NULL, SDL_InvalidParamError, and SDL_TrayEntry::submenu.
SDL_InsertTrayEntryAt()
SDL_TrayEntry * SDL_InsertTrayEntryAt (SDL_TrayMenu * menu, int pos, const char * label, SDL_TrayEntryFlags flags)
Insert a tray entry at a given position.
If label is NULL, the entry will be a separator. Many functions won't work for an entry that is a separator.
An entry does not need to be destroyed; it will be destroyed with the tray.
Parameters
menu the menu to append the entry to.
pos the desired position for the new entry. Entries at or following this place will be moved. If pos is -1, the entry is appended.
label the text to be displayed on the entry, in UTF-8 encoding, or NULL for a separator.
flags a combination of flags, some of which are mandatory.
Returns
the newly created entry, or NULL if pos is out of bounds.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_TrayEntryFlags
SDL_GetTrayEntries
SDL_RemoveTrayEntry
SDL_GetTrayEntryParent
{
    if (!menu) {
        SDL_InvalidParamError("menu");
        return NULL;
    }
    if (pos < -1 || pos > menu->nEntries) {
        SDL_InvalidParamError("pos");
        return NULL;
    }
    if (pos == -1) {
        pos = menu->nEntries;
    }
    SDL_TrayEntry *entry = (SDL_TrayEntry *)SDL_calloc(1, sizeof(*entry));
    if (!entry) {
        return NULL;
    }
    entry->parent = menu;
    entry->item = NULL;
    entry->ignore_signal = false;
    entry->flags = flags;
    entry->callback = NULL;
    entry->userdata = NULL;
    entry->submenu = NULL;
    if (label == NULL) {
        entry->item = gtk_separator_menu_item_new();
    } else if (flags & SDL_TRAYENTRY_CHECKBOX) {
        entry->item = gtk_check_menu_item_new_with_label(label);
        gboolean active = ((flags & SDL_TRAYENTRY_CHECKED) != 0);
        gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(entry->item), active);
    } else {
        entry->item = gtk_menu_item_new_with_label(label);
    }
    gboolean sensitive = ((flags & SDL_TRAYENTRY_DISABLED) == 0);
    gtk_widget_set_sensitive(entry->item, sensitive);
    SDL_TrayEntry **new_entries = (SDL_TrayEntry **)SDL_realloc(menu->entries, (menu->nEntries + 2) * sizeof(*new_entries));
    if (!new_entries) {
        SDL_free(entry);
        return NULL;
    }
    menu->entries = new_entries;
    menu->nEntries++;
    for (int i = menu->nEntries - 1; i > pos; i--) {
        menu->entries[i] = menu->entries[i - 1];
    }
    new_entries[pos] = entry;
    new_entries[menu->nEntries] = NULL;
    gtk_widget_show(entry->item);
    gtk_menu_shell_insert(menu->menu, entry->item, (pos == menu->nEntries) ? -1 : pos);
    g_signal_connect(entry->item, "activate", G_CALLBACK(call_callback), entry);
    return entry;
}
References active, call_callback(), SDL_TrayEntry::callback, SDL_TrayMenu::entries, SDL_TrayEntry::flags, G_CALLBACK, g_signal_connect, GTK_CHECK_MENU_ITEM, gtk_check_menu_item_new_with_label, gtk_check_menu_item_set_active, gtk_menu_item_new_with_label, gtk_menu_shell_insert, gtk_separator_menu_item_new, gtk_widget_set_sensitive, gtk_widget_show, SDL_TrayEntry::ignore_signal, SDL_TrayEntry::item, SDL_TrayMenu::menu, SDL_TrayMenu::nEntries, NULL, SDL_TrayEntry::parent, SDL_calloc(), SDL_free(), SDL_InvalidParamError, SDL_realloc(), SDL_TRAYENTRY_CHECKBOX, SDL_TRAYENTRY_CHECKED, SDL_TRAYENTRY_DISABLED, SDL_TrayEntry::submenu, and SDL_TrayEntry::userdata.
SDL_IsTraySupported()
bool SDL_IsTraySupported (void)
Check whether or not tray icons can be created.
Note that this function does not guarantee that SDL_CreateTray() will or will not work; you should still check SDL_CreateTray() for errors.
Using tray icons require the video subsystem.
Returns
true if trays are available, false otherwise.
Thread Safety
This function should only be called on the main thread. It will return false if not called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateTray
{
    if (!SDL_IsMainThread()) {
        SDL_SetError("This function should be called on the main thread");
        return false;
    }
    static bool has_trays = false;
    static bool has_been_detected_once = false;
    if (!has_been_detected_once) {
        has_trays = init_gtk();
        has_been_detected_once = true;
    }
    return has_trays;
}
References init_gtk(), SDL_IsMainThread(), and SDL_SetError().
SDL_RemoveTrayEntry()
void SDL_RemoveTrayEntry (SDL_TrayEntry * entry)
Removes a tray entry.
Parameters
entry The entry to be deleted.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
    if (!entry) {
        return;
    }
    SDL_TrayMenu *menu = entry->parent;
    bool found = false;
    for (int i = 0; i < menu->nEntries - 1; i++) {
        if (menu->entries[i] == entry) {
            found = true;
        }
        if (found) {
            menu->entries[i] = menu->entries[i + 1];
        }
    }
    if (entry->submenu) {
        DestroySDLMenu(entry->submenu);
    }
    menu->nEntries--;
    SDL_TrayEntry **new_entries = (SDL_TrayEntry **)SDL_realloc(menu->entries, (menu->nEntries + 1) * sizeof(*new_entries));
    /* Not sure why shrinking would fail, but even if it does, we can live with a "too big" array */
    if (new_entries) {
        menu->entries = new_entries;
        menu->entries[menu->nEntries] = NULL;
    }
    gtk_widget_destroy(entry->item);
    SDL_free(entry);
}
References DestroySDLMenu(), SDL_TrayMenu::entries, gtk_widget_destroy, SDL_TrayEntry::item, SDL_TrayMenu::nEntries, NULL, SDL_TrayEntry::parent, SDL_free(), SDL_realloc(), and SDL_TrayEntry::submenu.
SDL_SetTrayEntryCallback()
void SDL_SetTrayEntryCallback (SDL_TrayEntry * entry, SDL_TrayCallback callback, void * userdata)
Sets a callback to be invoked when the entry is selected.
Parameters
entry the entry to be updated.
callback a callback to be invoked when the entry is selected.
userdata an optional pointer to pass extra data to the callback when it will be invoked.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
{
    if (!entry) {
        return;
    }
    entry->callback = callback;
    entry->userdata = userdata;
}
References SDL_TrayEntry::callback, and SDL_TrayEntry::userdata.
SDL_SetTrayEntryChecked()
void SDL_SetTrayEntryChecked (SDL_TrayEntry * entry, bool checked)
Sets whether or not an entry is checked.
The entry must have been created with the SDL_TRAYENTRY_CHECKBOX flag.
Parameters
entry the entry to be updated.
checked true if the entry should be checked; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryChecked
{
    if (!entry || !(entry->flags & SDL_TRAYENTRY_CHECKBOX)) {
        return;
    }
    entry->ignore_signal = true;
    gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(entry->item), checked);
    entry->ignore_signal = false;
}
References SDL_TrayEntry::flags, GTK_CHECK_MENU_ITEM, gtk_check_menu_item_set_active, SDL_TrayEntry::ignore_signal, SDL_TrayEntry::item, and SDL_TRAYENTRY_CHECKBOX.
SDL_SetTrayEntryEnabled()
void SDL_SetTrayEntryEnabled (SDL_TrayEntry * entry, bool enabled)
Sets whether or not an entry is enabled.
Parameters
entry the entry to be updated.
enabled true if the entry should be enabled; false otherwise.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryEnabled
{
    if (!entry) {
        return;
    }
    gtk_widget_set_sensitive(entry->item, enabled);
}
References gtk_widget_set_sensitive, and SDL_TrayEntry::item.
SDL_SetTrayEntryLabel()
void SDL_SetTrayEntryLabel (SDL_TrayEntry * entry, const char * label)
Sets the label of an entry.
An entry cannot change between a separator and an ordinary entry; that is, it is not possible to set a non-NULL label on an entry that has a NULL label (separators), or to set a NULL label to an entry that has a non-NULL label. The function will silently fail if that happens.
Parameters
entry the entry to be updated.
label the new label for the entry in UTF-8 encoding.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTrayEntries
SDL_InsertTrayEntryAt
SDL_GetTrayEntryLabel
{
    if (!entry) {
        return;
    }
    gtk_menu_item_set_label(GTK_MENU_ITEM(entry->item), label);
}
References GTK_MENU_ITEM, gtk_menu_item_set_label, and SDL_TrayEntry::item.
SDL_SetTrayIcon()
void SDL_SetTrayIcon (SDL_Tray * tray, SDL_Surface * icon)
Updates the system tray icon's icon.
Parameters
tray the tray icon to be updated.
icon the new icon. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
    if (!SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY)) {
        return;
    }
    if (*tray->icon_path) {
        SDL_RemovePath(tray->icon_path);
    }
    /* AppIndicator caches the icon files; always change filename to avoid caching */
    if (icon && new_tmp_filename(tray)) {
        SDL_SaveBMP(icon, tray->icon_path);
        app_indicator_set_icon(tray->indicator, tray->icon_path);
    } else {
        *tray->icon_path = '\0';
        app_indicator_set_icon(tray->indicator, NULL);
    }
}
References app_indicator_set_icon, SDL_Tray::icon_path, SDL_Tray::indicator, new_tmp_filename(), NULL, SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), SDL_RemovePath(), and SDL_SaveBMP().
SDL_SetTrayTooltip()
void SDL_SetTrayTooltip (SDL_Tray * tray, const char * tooltip)
Updates the system tray icon's tooltip.
Parameters
tray the tray icon to be updated.
tooltip the new tooltip in UTF-8 encoding. May be NULL.
Thread Safety
This function should be called on the thread that created the tray.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTray
{
    /* AppIndicator provides no tooltip support. */
}
SDL_UpdateTrays()
void SDL_UpdateTrays (void)
Update the trays.
This is called automatically by the event loop and is only needed if you're using trays but aren't handling SDL events.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (SDL_HasActiveTrays()) {
        gtk_main_iteration_do(FALSE);
    }
}
References FALSE, gtk_main_iteration_do, and SDL_HasActiveTrays().
Variable Documentation
app_indicator_new
AppIndicator *(* app_indicator_new) (const gchar *id, const gchar *icon_name, AppIndicatorCategory category) (const gchar * id, const gchar * icon_name, AppIndicatorCategory category) static
Referenced by init_gtk(), and SDL_CreateTray().
app_indicator_set_icon
void(* app_indicator_set_icon) (AppIndicator *self, const gchar *icon_name) (AppIndicator * self, const gchar * icon_name) static
Referenced by init_gtk(), and SDL_SetTrayIcon().
app_indicator_set_menu
void(* app_indicator_set_menu) (AppIndicator *self, GtkMenu *menu) (AppIndicator * self, GtkMenu * menu) static
Referenced by init_gtk(), and SDL_CreateTray().
app_indicator_set_status
void(* app_indicator_set_status) (AppIndicator *self, AppIndicatorStatus status) (AppIndicator * self, AppIndicatorStatus status) static
Referenced by init_gtk(), and SDL_CreateTray().
appindicator_names
const char* appindicator_names[]
Initial value:
= {
    "libayatana-appindicator3.so.1",
    "libappindicator3.so.1",
    NULL
}
{
#ifdef SDL_PLATFORM_OPENBSD
    "libayatana-appindicator3.so",
    "libappindicator3.so",
#else
    "libayatana-appindicator3.so.1",
    "libappindicator3.so.1",
#endif
    NULL
};
Referenced by init_gtk().
g_mkdtemp
gchar *(* g_mkdtemp) (gchar *template) (gchar * template) static
Referenced by init_gtk(), and SDL_CreateTray().
g_object_ref
gpointer(* g_object_ref) (gpointer object) (gpointer object) static
Referenced by init_gtk(), and SDL_CreateTrayMenu().
g_object_ref_sink
gpointer(* g_object_ref_sink) (gpointer object) (gpointer object) static
Referenced by init_gtk(), SDL_CreateTray(), and SDL_CreateTraySubmenu().
g_object_unref
void(* g_object_unref) (gpointer object) (gpointer object) static
Referenced by DestroySDLMenu(), init_gtk(), and SDL_DestroyTray().
g_signal_connect_data
gulong(* g_signal_connect_data) (gpointer instance, const gchar *detailed_signal, GCallback c_handler, gpointer data, GClosureNotify destroy_data, GConnectFlags connect_flags) (gpointer instance, const gchar * detailed_signal, GCallback c_handler, gpointer data, GClosureNotify destroy_data, GConnectFlags connect_flags) static
Referenced by init_gtk().
gdk_names
const char* gdk_names[]
Initial value:
= {
    "libgdk-3.so.0",
    NULL
}
{
#ifdef SDL_PLATFORM_OPENBSD
    "libgdk-3.so",
#else
    "libgdk-3.so.0",
#endif
    NULL
};
Referenced by init_gtk().
gtk_check_menu_item_get_active
gboolean(* gtk_check_menu_item_get_active) (GtkCheckMenuItem *check_menu_item) (GtkCheckMenuItem * check_menu_item) static
Referenced by init_gtk(), and SDL_GetTrayEntryChecked().
gtk_check_menu_item_new_with_label
GtkWidget *(* gtk_check_menu_item_new_with_label) (const gchar *label) (const gchar * label) static
Referenced by init_gtk(), and SDL_InsertTrayEntryAt().
gtk_check_menu_item_set_active
void(* gtk_check_menu_item_set_active) (GtkCheckMenuItem *check_menu_item, gboolean is_active) (GtkCheckMenuItem * check_menu_item, gboolean is_active) static
Referenced by init_gtk(), SDL_InsertTrayEntryAt(), and SDL_SetTrayEntryChecked().
gtk_init_check
gboolean(* gtk_init_check) (int *argc, char ***argv) (int * argc, char *** argv) static
Referenced by init_gtk().
gtk_is_init
bool gtk_is_init = false static
Referenced by init_gtk(), and quit_gtk().
gtk_main_iteration_do
gboolean(* gtk_main_iteration_do) (gboolean blocking) (gboolean blocking) static
Referenced by init_gtk(), and SDL_UpdateTrays().
gtk_menu_item_get_label
const gchar *(* gtk_menu_item_get_label) (GtkMenuItem *menu_item) (GtkMenuItem * menu_item) static
Referenced by init_gtk(), and SDL_GetTrayEntryLabel().
gtk_menu_item_new_with_label
GtkWidget *(* gtk_menu_item_new_with_label) (const gchar *label) (const gchar * label) static
Referenced by init_gtk(), and SDL_InsertTrayEntryAt().
gtk_menu_item_set_label
void(* gtk_menu_item_set_label) (GtkMenuItem *menu_item, const gchar *label) (GtkMenuItem * menu_item, const gchar * label) static
Referenced by init_gtk(), and SDL_SetTrayEntryLabel().
gtk_menu_item_set_submenu
void(* gtk_menu_item_set_submenu) (GtkMenuItem *menu_item, GtkWidget *submenu) (GtkMenuItem * menu_item, GtkWidget * submenu) static
Referenced by init_gtk(), and SDL_CreateTraySubmenu().
gtk_menu_new
GtkWidget *(* gtk_menu_new) (void) (void) static
Referenced by init_gtk(), SDL_CreateTray(), and SDL_CreateTraySubmenu().
gtk_menu_shell_append
void(* gtk_menu_shell_append) (GtkMenuShell *menu_shell, GtkWidget *child) (GtkMenuShell * menu_shell, GtkWidget * child) static
Referenced by init_gtk().
gtk_menu_shell_insert
void(* gtk_menu_shell_insert) (GtkMenuShell *menu_shell, GtkWidget *child, gint position) (GtkMenuShell * menu_shell, GtkWidget * child, gint position) static
Referenced by init_gtk(), and SDL_InsertTrayEntryAt().
gtk_names
const char* gtk_names[]
Initial value:
= {
    "libgtk-3.so.0",
    NULL
}
{
#ifdef SDL_PLATFORM_OPENBSD
    "libgtk-3.so",
#else
    "libgtk-3.so.0",
#endif
    NULL
};
Referenced by init_gtk().
gtk_separator_menu_item_new
GtkWidget *(* gtk_separator_menu_item_new) (void) (void) static
Referenced by init_gtk(), and SDL_InsertTrayEntryAt().
gtk_widget_destroy
void(* gtk_widget_destroy) (GtkWidget *widget) (GtkWidget * widget) static
Referenced by init_gtk(), and SDL_RemoveTrayEntry().
gtk_widget_get_sensitive
gboolean(* gtk_widget_get_sensitive) (GtkWidget *widget) (GtkWidget * widget) static
Referenced by init_gtk(), and SDL_GetTrayEntryEnabled().
gtk_widget_set_sensitive
void(* gtk_widget_set_sensitive) (GtkWidget *widget, gboolean sensitive) (GtkWidget * widget, gboolean sensitive) static
Referenced by init_gtk(), SDL_InsertTrayEntryAt(), and SDL_SetTrayEntryEnabled().
gtk_widget_show
void(* gtk_widget_show) (GtkWidget *widget) (GtkWidget * widget) static
Referenced by init_gtk(), and SDL_InsertTrayEntryAt().
libappindicator
void* libappindicator = NULL static
Referenced by init_gtk(), and quit_gtk().
libgdk
void* libgdk = NULL static
Referenced by init_gtk(), and quit_gtk().
libgtk
void* libgtk = NULL static
Referenced by init_gtk(), and quit_gtk().