SDL3: SDL-main/src/core/windows/SDL_windows.h File Reference
SDL_windows.h File Reference
#include <windows.h>
#include <basetyps.h>
#include <mmreg.h>
Macros
#define MINGW32_FORCEALIGN
#define SDL_tcslen SDL_strlen
#define SDL_tcsstr SDL_strstr
#define WIN_StringToUTF8 WIN_StringToUTF8A
#define WIN_StringToUTF8A(S)
#define WIN_StringToUTF8W(S)
#define WIN_UTF8ToString WIN_UTF8ToStringA
#define WIN_UTF8ToStringA(S)
#define WIN_UTF8ToStringW(S)
Functions
SDL_AudioFormat SDL_WaveFormatExToSDLFormat (WAVEFORMATEX *waveformat)
HRESULT WIN_CoInitialize (void)
void WIN_CoUninitialize (void)
BOOL WIN_IsEqualGUID (const GUID *a, const GUID *b)
BOOL WIN_IsEqualIID (REFIID a, REFIID b)
BOOL WIN_IsWindows7OrGreater (void)
BOOL WIN_IsWindows8OrGreater (void)
BOOL WIN_IsWindowsVistaOrGreater (void)
BOOL WIN_IsWindowsXP (void)
FARPROC WIN_LoadComBaseFunction (const char *name)
char * WIN_LookupAudioDeviceName (const WCHAR *name, const GUID *guid)
void WIN_RECTToRect (const RECT *winrect, SDL_Rect *sdlrect)
void WIN_RectToRECT (const SDL_Rect *sdlrect, RECT *winrect)
HRESULT WIN_RoInitialize (void)
void WIN_RoUninitialize (void)
bool WIN_SetError (const char *prefix)
bool WIN_SetErrorFromHRESULT (const char *prefix, HRESULT hr)
int WIN_WideCharToMultiByte (UINT CodePage, DWORD dwFlags, LPCWCH lpWideCharStr, int cchWideChar, LPSTR lpMultiByteStr, int cbMultiByte, LPCCH lpDefaultChar, LPBOOL lpUsedDefaultChar)
bool WIN_WindowRectValid (const RECT *rect)
Macro Definition Documentation
MINGW32_FORCEALIGN
#define MINGW32_FORCEALIGN
SDL_tcslen
#define SDL_tcslen SDL_strlen
Referenced by SDL_LogOutput().
SDL_tcsstr
#define SDL_tcsstr SDL_strstr
WIN_StringToUTF8
#define WIN_StringToUTF8 WIN_StringToUTF8A
WIN_StringToUTF8A
#define WIN_StringToUTF8A (S)
Value:
SDL_iconv_string("UTF-8", "ASCII", (const char *)(S), (SDL_strlen(S) + 1))
WIN_StringToUTF8W
#define WIN_StringToUTF8W (S)
Value:
SDL_iconv_string("UTF-8", "UTF-16LE", (const char *)(S), (SDL_wcslen(S) + 1) * sizeof(WCHAR))
Referenced by SDL_CreateEnvironment(), windows_ShowFileDialog(), and windows_ShowFolderDialog().
WIN_UTF8ToString
#define WIN_UTF8ToString WIN_UTF8ToStringA
Referenced by SDL_LogOutput().
WIN_UTF8ToStringA
#define WIN_UTF8ToStringA (S)
Value:
SDL_iconv_string("ASCII", "UTF-8", (const char *)(S), SDL_strlen(S) + 1)
WIN_UTF8ToStringW
#define WIN_UTF8ToStringW (S)
Value:
(WCHAR *)SDL_iconv_string("UTF-16LE", "UTF-8", (const char *)(S), SDL_strlen(S) + 1)
Referenced by escape_label(), GetFileModificationTime(), SDL_CreateTray(), SDL_SetTrayTooltip(), SDL_SYS_OpenURL(), windows_ShowFileDialog(), and windows_ShowFolderDialog().
Function Documentation
SDL_WaveFormatExToSDLFormat()
SDL_AudioFormat SDL_WaveFormatExToSDLFormat (WAVEFORMATEX * waveformat) extern
WIN_CoInitialize()
HRESULT WIN_CoInitialize (void) extern
Referenced by SDL_SYS_OpenURL().
WIN_CoUninitialize()
void WIN_CoUninitialize (void) extern
Referenced by SDL_SYS_OpenURL().
WIN_IsEqualGUID()
BOOL WIN_IsEqualGUID (const GUID * a, const GUID * b) extern
WIN_IsEqualIID()
BOOL WIN_IsEqualIID (REFIID a, REFIID b) extern
WIN_IsWindows7OrGreater()
BOOL WIN_IsWindows7OrGreater (void) extern
WIN_IsWindows8OrGreater()
BOOL WIN_IsWindows8OrGreater (void) extern
WIN_IsWindowsVistaOrGreater()
BOOL WIN_IsWindowsVistaOrGreater (void) extern
WIN_IsWindowsXP()
BOOL WIN_IsWindowsXP (void) extern
WIN_LoadComBaseFunction()
FARPROC WIN_LoadComBaseFunction (const char * name)
WIN_LookupAudioDeviceName()
char * WIN_LookupAudioDeviceName (const WCHAR * name, const GUID * guid) extern
WIN_RECTToRect()
void WIN_RECTToRect (const RECT * winrect, SDL_Rect * sdlrect) extern
WIN_RectToRECT()
void WIN_RectToRECT (const SDL_Rect * sdlrect, RECT * winrect) extern
WIN_RoInitialize()
HRESULT WIN_RoInitialize (void) extern
WIN_RoUninitialize()
void WIN_RoUninitialize (void) extern
WIN_SetError()
bool WIN_SetError (const char * prefix) extern
Referenced by SDL_SYS_GetBasePath(), SDL_SYS_GetPrefPath(), and SDL_SYS_OpenURL().
WIN_SetErrorFromHRESULT()
bool WIN_SetErrorFromHRESULT (const char * prefix, HRESULT hr) extern
Referenced by SDL_GetGDKDefaultUser(), SDL_SYS_GetPrefPath(), and SDL_SYS_OpenURL().
WIN_WideCharToMultiByte()
int WIN_WideCharToMultiByte (UINT CodePage, DWORD dwFlags, LPCWCH lpWideCharStr, int cchWideChar, LPSTR lpMultiByteStr, int cbMultiByte, LPCCH lpDefaultChar, LPBOOL lpUsedDefaultChar) extern
Referenced by hid_internal_UTF16toUTF8().
WIN_WindowRectValid()
bool WIN_WindowRectValid (const RECT * rect)