SDL3: SDL-main/src/cpuinfo/SDL_cpuinfo.c File Reference
SDL_cpuinfo.c File Reference
#include "SDL_internal.h"
#include "SDL_cpuinfo_c.h"
Macros
#define CPU_CFG2 0x2
#define CPU_CFG2_LASX (1 << 7)
#define CPU_CFG2_LSX (1 << 6)
#define CPU_FEATURE_AVAILABLE(f)
#define CPU_HAS_ALTIVEC (1 << 0)
#define CPU_HAS_ARM_SIMD (1 << 11)
#define CPU_HAS_AVX (1 << 7)
#define CPU_HAS_AVX2 (1 << 8)
#define CPU_HAS_AVX512F (1 << 10)
#define CPU_HAS_LASX (1 << 13)
#define CPU_HAS_LSX (1 << 12)
#define CPU_HAS_MMX (1 << 1)
#define CPU_HAS_NEON (1 << 9)
#define CPU_HAS_SSE (1 << 2)
#define CPU_HAS_SSE2 (1 << 3)
#define CPU_HAS_SSE3 (1 << 4)
#define CPU_HAS_SSE41 (1 << 5)
#define CPU_HAS_SSE42 (1 << 6)
#define CPU_haveAVX()
#define CPU_haveLASX()
#define CPU_haveLSX()
#define CPU_haveMMX()
#define CPU_haveSSE()
#define CPU_haveSSE2()
#define CPU_haveSSE3()
#define CPU_haveSSE41()
#define CPU_haveSSE42()
#define cpuid(func, a, b, c, d)
#define SDL_CPUFEATURES_RESET_VALUE 0xFFFFFFFF
Functions
static void CPU_calcCPUIDFeatures (void)
static int CPU_haveAltiVec (void)
static int CPU_haveARMSIMD (void)
static int CPU_haveAVX2 (void)
static int CPU_haveAVX512F (void)
static int CPU_haveCPUID (void)
static int CPU_haveNEON (void)
static int CPU_readCPUCFG (void)
static bool ref_string_equals (const char *ref, const char *test, const char *end_test)
static Uint32 SDLCALL SDL_CPUFeatureMaskFromHint (void)
int SDL_GetCPUCacheLineSize (void)
static Uint32 SDL_GetCPUFeatures (void)
static const char * SDL_GetCPUType (void)
int SDL_GetNumLogicalCPUCores (void)
size_t SDL_GetSIMDAlignment (void)
int SDL_GetSystemRAM (void)
bool SDL_HasAltiVec (void)
bool SDL_HasARMSIMD (void)
bool SDL_HasAVX (void)
bool SDL_HasAVX2 (void)
bool SDL_HasAVX512F (void)
bool SDL_HasLASX (void)
bool SDL_HasLSX (void)
bool SDL_HasMMX (void)
bool SDL_HasNEON (void)
bool SDL_HasSSE (void)
bool SDL_HasSSE2 (void)
bool SDL_HasSSE3 (void)
bool SDL_HasSSE41 (void)
bool SDL_HasSSE42 (void)
void SDL_QuitCPUInfo (void)
Variables
static int CPU_CPUIDFeatures [4]
static int CPU_CPUIDMaxFunction = 0
static bool CPU_OSSavesYMM = false
static bool CPU_OSSavesZMM = false
static Uint32 SDL_CPUFeatures = 0xFFFFFFFF
static int SDL_NumLogicalCPUCores = 0
static Uint32 SDL_SIMDAlignment = 0xFFFFFFFF
static int SDL_SystemRAM = 0
Macro Definition Documentation
CPU_CFG2
#define CPU_CFG2 0x2
Referenced by CPU_readCPUCFG().
CPU_CFG2_LASX
#define CPU_CFG2_LASX (1 << 7)
CPU_CFG2_LSX
#define CPU_CFG2_LSX (1 << 6)
CPU_FEATURE_AVAILABLE
#define CPU_FEATURE_AVAILABLE (f)
Value:
((SDL_GetCPUFeatures() & (f)) ? true : false)
Referenced by SDL_HasAltiVec(), SDL_HasARMSIMD(), SDL_HasAVX(), SDL_HasAVX2(), SDL_HasAVX512F(), SDL_HasLASX(), SDL_HasLSX(), SDL_HasMMX(), SDL_HasNEON(), SDL_HasSSE(), SDL_HasSSE2(), SDL_HasSSE3(), SDL_HasSSE41(), and SDL_HasSSE42().
CPU_HAS_ALTIVEC
#define CPU_HAS_ALTIVEC (1 << 0)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasAltiVec().
CPU_HAS_ARM_SIMD
#define CPU_HAS_ARM_SIMD (1 << 11)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasARMSIMD().
CPU_HAS_AVX
#define CPU_HAS_AVX (1 << 7)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasAVX().
CPU_HAS_AVX2
#define CPU_HAS_AVX2 (1 << 8)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasAVX2().
CPU_HAS_AVX512F
#define CPU_HAS_AVX512F (1 << 10)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasAVX512F().
CPU_HAS_LASX
#define CPU_HAS_LASX (1 << 13)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasLASX().
CPU_HAS_LSX
#define CPU_HAS_LSX (1 << 12)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasLSX().
CPU_HAS_MMX
#define CPU_HAS_MMX (1 << 1)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasMMX().
CPU_HAS_NEON
#define CPU_HAS_NEON (1 << 9)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasNEON().
CPU_HAS_SSE
#define CPU_HAS_SSE (1 << 2)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasSSE().
CPU_HAS_SSE2
#define CPU_HAS_SSE2 (1 << 3)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasSSE2().
CPU_HAS_SSE3
#define CPU_HAS_SSE3 (1 << 4)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasSSE3().
CPU_HAS_SSE41
#define CPU_HAS_SSE41 (1 << 5)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasSSE41().
CPU_HAS_SSE42
#define CPU_HAS_SSE42 (1 << 6)
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_HasSSE42().
CPU_haveAVX
#define CPU_haveAVX ()
Value:
(CPU_OSSavesYMM && (CPU_CPUIDFeatures[2] & 0x10000000))
Referenced by SDL_GetCPUFeatures().
CPU_haveLASX
#define CPU_haveLASX ()
Value:
(CPU_readCPUCFG() & CPU_CFG2_LASX)
Referenced by SDL_GetCPUFeatures().
CPU_haveLSX
#define CPU_haveLSX ()
Value:
(CPU_readCPUCFG() & CPU_CFG2_LSX)
Referenced by SDL_GetCPUFeatures().
CPU_haveMMX
#define CPU_haveMMX ()
Value:
(CPU_CPUIDFeatures[3] & 0x00800000)
Referenced by SDL_GetCPUFeatures().
CPU_haveSSE
#define CPU_haveSSE ()
Value:
(CPU_CPUIDFeatures[3] & 0x02000000)
Referenced by SDL_GetCPUFeatures().
CPU_haveSSE2
#define CPU_haveSSE2 ()
Value:
(CPU_CPUIDFeatures[3] & 0x04000000)
Referenced by SDL_GetCPUFeatures().
CPU_haveSSE3
#define CPU_haveSSE3 ()
Value:
(CPU_CPUIDFeatures[2] & 0x00000001)
Referenced by SDL_GetCPUFeatures().
CPU_haveSSE41
#define CPU_haveSSE41 ()
Value:
(CPU_CPUIDFeatures[2] & 0x00080000)
Referenced by SDL_GetCPUFeatures().
CPU_haveSSE42
#define CPU_haveSSE42 ()
Value:
(CPU_CPUIDFeatures[2] & 0x00100000)
Referenced by SDL_GetCPUFeatures().
cpuid
#define cpuid (func, a, b, c, d)
Value:
    do {                        \
        a = b = c = d = 0;      \
        (void)a;                \
        (void)b;                \
        (void)c;                \
        (void)d;                \
    } while (0)
#define cpuid(func, a, b, c, d) \
    do {                        \
        a = b = c = d = 0;      \
        (void)a;                \
        (void)b;                \
        (void)c;                \
        (void)d;                \
    } while (0)
Referenced by CPU_calcCPUIDFeatures(), CPU_haveAVX2(), CPU_haveAVX512F(), SDL_GetCPUCacheLineSize(), and SDL_GetCPUType().
SDL_CPUFEATURES_RESET_VALUE
#define SDL_CPUFEATURES_RESET_VALUE 0xFFFFFFFF
Referenced by SDL_CPUFeatureMaskFromHint(), SDL_GetCPUFeatures(), and SDL_QuitCPUInfo().
Function Documentation
CPU_calcCPUIDFeatures()
void CPU_calcCPUIDFeatures (void) static
{
    static bool checked = false;
    if (!checked) {
        checked = true;
        if (CPU_haveCPUID()) {
            int a, b, c, d;
            cpuid(0, a, b, c, d);
            CPU_CPUIDMaxFunction = a;
            if (CPU_CPUIDMaxFunction >= 1) {
                cpuid(1, a, b, c, d);
                CPU_CPUIDFeatures[0] = a;
                CPU_CPUIDFeatures[1] = b;
                CPU_CPUIDFeatures[2] = c;
                CPU_CPUIDFeatures[3] = d;
                // Check to make sure we can call xgetbv
                if (c & 0x08000000) {
                    // Call xgetbv to see if YMM (etc) register state is saved
#if (defined(__GNUC__) || defined(__llvm__)) && (defined(__i386__) || defined(__x86_64__))
                    __asm__(".byte 0x0f, 0x01, 0xd0"
                            : "=a"(a)
                            : "c"(0)
                            : "%edx");
#elif defined(_MSC_VER) && (defined(_M_IX86) || defined(_M_X64)) && (_MSC_FULL_VER >= 160040219) // VS2010 SP1
                    a = (int)_xgetbv(0);
#elif (defined(_MSC_VER) && defined(_M_IX86)) || defined(__WATCOMC__)
                    __asm
{
                        xor ecx, ecx
                        _asm _emit 0x0f _asm _emit 0x01 _asm _emit 0xd0
                        mov a, eax
                        }
#endif
                    CPU_OSSavesYMM = ((a & 6) == 6) ? true : false;
                    CPU_OSSavesZMM = (CPU_OSSavesYMM && ((a & 0xe0) == 0xe0)) ? true : false;
                }
            }
        }
    }
}
References CPU_CPUIDFeatures, CPU_CPUIDMaxFunction, CPU_haveCPUID(), CPU_OSSavesYMM, CPU_OSSavesZMM, cpuid, and d.
Referenced by SDL_GetCPUFeatures(), and SDL_GetCPUType().
CPU_haveAltiVec()
int CPU_haveAltiVec (void) static
{
    volatile int altivec = 0;
#ifndef SDL_CPUINFO_DISABLED
#if (defined(SDL_PLATFORM_MACOS) && (defined(__ppc__) || defined(__ppc64__))) || (defined(SDL_PLATFORM_OPENBSD) && defined(__powerpc__))
#ifdef SDL_PLATFORM_OPENBSD
    int selectors[2] = { CTL_MACHDEP, CPU_ALTIVEC };
#else
    int selectors[2] = { CTL_HW, HW_VECTORUNIT };
#endif
    int hasVectorUnit = 0;
    size_t length = sizeof(hasVectorUnit);
    int error = sysctl(selectors, 2, &hasVectorUnit, &length, NULL, 0);
    if (0 == error) {
        altivec = (hasVectorUnit != 0);
    }
#elif defined(SDL_PLATFORM_FREEBSD) && defined(__powerpc__)
    unsigned long cpufeatures = 0;
    elf_aux_info(AT_HWCAP, &cpufeatures, sizeof(cpufeatures));
    altivec = cpufeatures & PPC_FEATURE_HAS_ALTIVEC;
    return altivec;
#elif defined(SDL_PLATFORM_LINUX) && defined(__powerpc__) && defined(HAVE_GETAUXVAL)
    altivec = getauxval(AT_HWCAP) & PPC_FEATURE_HAS_ALTIVEC;
#elif defined(SDL_ALTIVEC_BLITTERS) && defined(HAVE_SETJMP)
    void (*handler)(int sig);
    handler = signal(SIGILL, illegal_instruction);
    if (setjmp(jmpbuf) == 0) {
        asm volatile("mtspr 256, %0\n\t"
                     "vand %%v0, %%v0, %%v0" ::"r"(-1));
        altivec = 1;
    }
    signal(SIGILL, handler);
#endif
#endif
    return altivec;
}
References NULL, and void().
Referenced by SDL_GetCPUFeatures().
CPU_haveARMSIMD()
int CPU_haveARMSIMD (void) static
{
    return 0;
}
Referenced by SDL_GetCPUFeatures().
CPU_haveAVX2()
int CPU_haveAVX2 (void) static
{
    if (CPU_OSSavesYMM && (CPU_CPUIDMaxFunction >= 7)) {
        int a, b, c, d;
        (void)a;
        (void)b;
        (void)c;
        (void)d; // compiler warnings...
        cpuid(7, a, b, c, d);
        return b & 0x00000020;
    }
    return 0;
}
References CPU_CPUIDMaxFunction, CPU_OSSavesYMM, cpuid, d, and void().
Referenced by SDL_GetCPUFeatures().
CPU_haveAVX512F()
int CPU_haveAVX512F (void) static
{
    if (CPU_OSSavesZMM && (CPU_CPUIDMaxFunction >= 7)) {
        int a, b, c, d;
        (void)a;
        (void)b;
        (void)c;
        (void)d; // compiler warnings...
        cpuid(7, a, b, c, d);
        return b & 0x00010000;
    }
    return 0;
}
References CPU_CPUIDMaxFunction, CPU_OSSavesZMM, cpuid, d, and void().
Referenced by SDL_GetCPUFeatures().
CPU_haveCPUID()
int CPU_haveCPUID (void) static
{
    int has_CPUID = 0;
/* *INDENT-OFF* */ // clang-format off
#ifndef SDL_PLATFORM_EMSCRIPTEN
#if (defined(__GNUC__) || defined(__llvm__)) && defined(__i386__)
    __asm__ (
"        pushfl                      # Get original EFLAGS             \n"
"        popl    %%eax                                                 \n"
"        movl    %%eax,%%ecx                                           \n"
"        xorl    $0x200000,%%eax     # Flip ID bit in EFLAGS           \n"
"        pushl   %%eax               # Save new EFLAGS value on stack  \n"
"        popfl                       # Replace current EFLAGS value    \n"
"        pushfl                      # Get new EFLAGS                  \n"
"        popl    %%eax               # Store new EFLAGS in EAX         \n"
"        xorl    %%ecx,%%eax         # Can not toggle ID bit,          \n"
"        jz      1f                  # Processor=80486                 \n"
"        movl    $1,%0               # We have CPUID support           \n"
"1:                                                                    \n"
    : "=m" (has_CPUID)
    :
    : "%eax", "%ecx"
    );
#elif (defined(__GNUC__) || defined(__llvm__)) && defined(__x86_64__)
/* Technically, if this is being compiled under __x86_64__ then it has
   CPUid by definition.  But it's nice to be able to prove it.  :)      */
    __asm__ (
"        pushfq                      # Get original EFLAGS             \n"
"        popq    %%rax                                                 \n"
"        movq    %%rax,%%rcx                                           \n"
"        xorl    $0x200000,%%eax     # Flip ID bit in EFLAGS           \n"
"        pushq   %%rax               # Save new EFLAGS value on stack  \n"
"        popfq                       # Replace current EFLAGS value    \n"
"        pushfq                      # Get new EFLAGS                  \n"
"        popq    %%rax               # Store new EFLAGS in EAX         \n"
"        xorl    %%ecx,%%eax         # Can not toggle ID bit,          \n"
"        jz      1f                  # Processor=80486                 \n"
"        movl    $1,%0               # We have CPUID support           \n"
"1:                                                                    \n"
    : "=m" (has_CPUID)
    :
    : "%rax", "%rcx"
    );
#elif (defined(_MSC_VER) && defined(_M_IX86)) || defined(__WATCOMC__)
    __asm {
        pushfd                      ; Get original EFLAGS
        pop     eax
        mov     ecx, eax
        xor     eax, 200000h        ; Flip ID bit in EFLAGS
        push    eax                 ; Save new EFLAGS value on stack
        popfd                       ; Replace current EFLAGS value
        pushfd                      ; Get new EFLAGS
        pop     eax                 ; Store new EFLAGS in EAX
        xor     eax, ecx            ; Can not toggle ID bit,
        jz      done                ; Processor=80486
        mov     has_CPUID,1         ; We have CPUID support
done:
    }
#elif defined(_MSC_VER) && defined(_M_X64)
    has_CPUID = 1;
#elif defined(__sun) && defined(__i386)
    __asm (
"       pushfl                 \n"
"       popl    %eax           \n"
"       movl    %eax,%ecx      \n"
"       xorl    $0x200000,%eax \n"
"       pushl   %eax           \n"
"       popfl                  \n"
"       pushfl                 \n"
"       popl    %eax           \n"
"       xorl    %ecx,%eax      \n"
"       jz      1f             \n"
"       movl    $1,-8(%ebp)    \n"
"1:                            \n"
    );
#elif defined(__sun) && defined(__amd64)
    __asm (
"       pushfq                 \n"
"       popq    %rax           \n"
"       movq    %rax,%rcx      \n"
"       xorl    $0x200000,%eax \n"
"       pushq   %rax           \n"
"       popfq                  \n"
"       pushfq                 \n"
"       popq    %rax           \n"
"       xorl    %ecx,%eax      \n"
"       jz      1f             \n"
"       movl    $1,-8(%rbp)    \n"
"1:                            \n"
    );
#endif
#endif // !SDL_PLATFORM_EMSCRIPTEN
/* *INDENT-ON* */ // clang-format on
    return has_CPUID;
}
References pop.
Referenced by CPU_calcCPUIDFeatures().
CPU_haveNEON()
int CPU_haveNEON (void) static
{
/* The way you detect NEON is a privileged instruction on ARM, so you have
   query the OS kernel in a platform-specific way. :/ */
#if defined(SDL_PLATFORM_WINDOWS) && (defined(_M_ARM) || defined(_M_ARM64))
// Visual Studio, for ARM, doesn't define __ARM_ARCH. Handle this first.
// Seems to have been removed
#ifndef PF_ARM_NEON_INSTRUCTIONS_AVAILABLE
#define PF_ARM_NEON_INSTRUCTIONS_AVAILABLE 19
#endif
    // All WinRT ARM devices are required to support NEON, but just in case.
    return IsProcessorFeaturePresent(PF_ARM_NEON_INSTRUCTIONS_AVAILABLE) != 0;
#elif (defined(__ARM_ARCH) && (__ARM_ARCH >= 8)) || defined(__aarch64__)
    return 1; // ARMv8 always has non-optional NEON support.
#elif defined(SDL_PLATFORM_VITA)
    return 1;
#elif defined(SDL_PLATFORM_3DS)
    return 0;
#elif defined(SDL_PLATFORM_NGAGE)
    return 0; // The ARM920T is based on the ARMv4T architecture and doesn't have NEON.
#elif defined(SDL_PLATFORM_APPLE) && defined(__ARM_ARCH) && (__ARM_ARCH >= 7)
    // (note that sysctlbyname("hw.optional.neon") doesn't work!)
    return 1; // all Apple ARMv7 chips and later have NEON.
#elif defined(SDL_PLATFORM_APPLE)
    return 0; // assume anything else from Apple doesn't have NEON.
#elif !defined(__arm__)
    return 0; // not an ARM CPU at all.
#elif defined(SDL_PLATFORM_OPENBSD)
    return 1; // OpenBSD only supports ARMv7 CPUs that have NEON.
#elif defined(HAVE_ELF_AUX_INFO)
    unsigned long hasneon = 0;
    if (elf_aux_info(AT_HWCAP, (void *)&hasneon, (int)sizeof(hasneon)) != 0) {
        return 0;
    }
    return (hasneon & HWCAP_NEON) == HWCAP_NEON;
#elif (defined(SDL_PLATFORM_LINUX) || defined(SDL_PLATFORM_ANDROID)) && defined(HAVE_GETAUXVAL)
    return (getauxval(AT_HWCAP) & HWCAP_NEON) == HWCAP_NEON;
#elif defined(SDL_PLATFORM_LINUX)
    return readProcAuxvForNeon();
#elif defined(SDL_PLATFORM_ANDROID)
    // Use NDK cpufeatures to read either /proc/self/auxv or /proc/cpuinfo
    {
        AndroidCpuFamily cpu_family = android_getCpuFamily();
        if (cpu_family == ANDROID_CPU_FAMILY_ARM) {
            uint64_t cpu_features = android_getCpuFeatures();
            if (cpu_features & ANDROID_CPU_ARM_FEATURE_NEON) {
                return 1;
            }
        }
        return 0;
    }
#elif defined(SDL_PLATFORM_RISCOS)
    // Use the VFPSupport_Features SWI to access the MVFR registers
    {
        _kernel_swi_regs regs;
        regs.r[0] = 0;
        if (_kernel_swi(VFPSupport_Features, &regs, &regs) == NULL) {
            if ((regs.r[2] & 0xFFF000) == 0x111000) {
                return 1;
            }
        }
        return 0;
    }
#elif defined(SDL_PLATFORM_EMSCRIPTEN)
    return 0;
#else
#warning SDL_HasNEON is not implemented for this ARM platform. Write me.
    return 0;
#endif
}
References NULL.
Referenced by SDL_GetCPUFeatures().
CPU_readCPUCFG()
int CPU_readCPUCFG (void) static
{
    uint32_t cfg2 = 0;
#if defined __loongarch__
    __asm__ volatile(
        "cpucfg %0, %1 \n\t"
        : "+&r"(cfg2)
        : "r"(CPU_CFG2));
#endif
    return cfg2;
}
References CPU_CFG2.
ref_string_equals()
bool ref_string_equals (const char * ref, const char * test, const char * end_test) static
{
    size_t len_test = end_test - test;
    return SDL_strncmp(ref, test, len_test) == 0 && ref[len_test] == '\0' && (test[len_test] == '\0' || test[len_test] == ',');
}
References SDL_strncmp().
Referenced by SDL_CPUFeatureMaskFromHint().
SDL_CPUFeatureMaskFromHint()
Uint32 SDLCALL SDL_CPUFeatureMaskFromHint (void) static
{
    Uint32 result_mask = SDL_CPUFEATURES_RESET_VALUE;
    const char *hint = SDL_GetHint(SDL_HINT_CPU_FEATURE_MASK);
    if (hint) {
        for (const char *spot = hint, *next; *spot; spot = next) {
            const char *end = SDL_strchr(spot, ',');
            Uint32 spot_mask;
            bool add_spot_mask = true;
            if (end) {
                next = end + 1;
            } else {
                size_t len = SDL_strlen(spot);
                end = spot + len;
                next = end;
            }
            if (spot[0] == '+') {
                add_spot_mask = true;
                spot += 1;
            } else if (spot[0] == '-') {
                add_spot_mask = false;
                spot += 1;
            }
            if (ref_string_equals("all", spot, end)) {
                spot_mask = SDL_CPUFEATURES_RESET_VALUE;
            } else if (ref_string_equals("altivec", spot, end)) {
                spot_mask= CPU_HAS_ALTIVEC;
            } else if (ref_string_equals("mmx", spot, end)) {
                spot_mask = CPU_HAS_MMX;
            } else if (ref_string_equals("sse", spot, end)) {
                spot_mask = CPU_HAS_SSE;
            } else if (ref_string_equals("sse2", spot, end)) {
                spot_mask = CPU_HAS_SSE2;
            } else if (ref_string_equals("sse3", spot, end)) {
                spot_mask = CPU_HAS_SSE3;
            } else if (ref_string_equals("sse41", spot, end)) {
                spot_mask = CPU_HAS_SSE41;
            } else if (ref_string_equals("sse42", spot, end)) {
                spot_mask = CPU_HAS_SSE42;
            } else if (ref_string_equals("avx", spot, end)) {
                spot_mask = CPU_HAS_AVX;
            } else if (ref_string_equals("avx2", spot, end)) {
                spot_mask = CPU_HAS_AVX2;
            } else if (ref_string_equals("avx512f", spot, end)) {
                spot_mask = CPU_HAS_AVX512F;
            } else if (ref_string_equals("arm-simd", spot, end)) {
                spot_mask = CPU_HAS_ARM_SIMD;
            } else if (ref_string_equals("neon", spot, end)) {
                spot_mask = CPU_HAS_NEON;
            } else if (ref_string_equals("lsx", spot, end)) {
                spot_mask = CPU_HAS_LSX;
            } else if (ref_string_equals("lasx", spot, end)) {
                spot_mask = CPU_HAS_LASX;
            } else {
                // Ignore unknown/incorrect cpu feature(s)
                continue;
            }
            if (add_spot_mask) {
                result_mask |= spot_mask;
            } else {
                result_mask &= ~spot_mask;
            }
        }
    }
    return result_mask;
}
References CPU_HAS_ALTIVEC, CPU_HAS_ARM_SIMD, CPU_HAS_AVX, CPU_HAS_AVX2, CPU_HAS_AVX512F, CPU_HAS_LASX, CPU_HAS_LSX, CPU_HAS_MMX, CPU_HAS_NEON, CPU_HAS_SSE, CPU_HAS_SSE2, CPU_HAS_SSE3, CPU_HAS_SSE41, CPU_HAS_SSE42, ref_string_equals(), SDL_CPUFEATURES_RESET_VALUE, SDL_GetHint(), SDL_HINT_CPU_FEATURE_MASK, SDL_strchr(), SDL_strlen(), and SDLCALL.
Referenced by SDL_GetCPUFeatures().
SDL_GetCPUCacheLineSize()
int SDL_GetCPUCacheLineSize (void)
Determine the L1 cache line size of the CPU.
This is useful for determining multi-threaded structure padding or SIMD prefetch sizes.
Returns
the L1 cache line size of the CPU, in bytes.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    const char *cpuType = SDL_GetCPUType();
    int cacheline_size = SDL_CACHELINE_SIZE; // initial guess
    int a, b, c, d;
    (void)a;
    (void)b;
    (void)c;
    (void)d;
    if (SDL_strcmp(cpuType, "GenuineIntel") == 0 || SDL_strcmp(cpuType, "CentaurHauls") == 0 || SDL_strcmp(cpuType, "  Shanghai  ") == 0) {
        cpuid(0x00000001, a, b, c, d);
        cacheline_size = ((b >> 8) & 0xff) * 8;
    } else if (SDL_strcmp(cpuType, "AuthenticAMD") == 0 || SDL_strcmp(cpuType, "HygonGenuine") == 0) {
        cpuid(0x80000005, a, b, c, d);
        cacheline_size = c & 0xff;
    } else {
#if defined(HAVE_SYSCONF) && defined(_SC_LEVEL1_DCACHE_LINESIZE)
        if ((cacheline_size = (int)sysconf(_SC_LEVEL1_DCACHE_LINESIZE)) > 0) {
            return cacheline_size;
        } else {
            cacheline_size = SDL_CACHELINE_SIZE;
        }
#endif
#if defined(SDL_PLATFORM_LINUX)
        {
            FILE *f = fopen("/sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size", "r");
            if (f) {
                int size;
                if (fscanf(f, "%d", &size) == 1) {
                    cacheline_size = size;
                }
                fclose(f);
            }
        }
#elif defined(__FREEBSD__) && defined(CACHE_LINE_SIZE)
        cacheline_size = CACHE_LINE_SIZE;
#endif
    }
    return cacheline_size;
}
References cpuid, d, SDL_CACHELINE_SIZE, SDL_GetCPUType(), SDL_strcmp(), and void().
SDL_GetCPUFeatures()
Uint32 SDL_GetCPUFeatures (void) static
{
    if (SDL_CPUFeatures == SDL_CPUFEATURES_RESET_VALUE) {
        CPU_calcCPUIDFeatures();
        SDL_CPUFeatures = 0;
        SDL_SIMDAlignment = sizeof(void *); // a good safe base value
        if (CPU_haveAltiVec()) {
            SDL_CPUFeatures |= CPU_HAS_ALTIVEC;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveMMX()) {
            SDL_CPUFeatures |= CPU_HAS_MMX;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 8);
        }
        if (CPU_haveSSE()) {
            SDL_CPUFeatures |= CPU_HAS_SSE;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveSSE2()) {
            SDL_CPUFeatures |= CPU_HAS_SSE2;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveSSE3()) {
            SDL_CPUFeatures |= CPU_HAS_SSE3;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveSSE41()) {
            SDL_CPUFeatures |= CPU_HAS_SSE41;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveSSE42()) {
            SDL_CPUFeatures |= CPU_HAS_SSE42;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveAVX()) {
            SDL_CPUFeatures |= CPU_HAS_AVX;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 32);
        }
        if (CPU_haveAVX2()) {
            SDL_CPUFeatures |= CPU_HAS_AVX2;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 32);
        }
        if (CPU_haveAVX512F()) {
            SDL_CPUFeatures |= CPU_HAS_AVX512F;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 64);
        }
        if (CPU_haveARMSIMD()) {
            SDL_CPUFeatures |= CPU_HAS_ARM_SIMD;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveNEON()) {
            SDL_CPUFeatures |= CPU_HAS_NEON;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveLSX()) {
            SDL_CPUFeatures |= CPU_HAS_LSX;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 16);
        }
        if (CPU_haveLASX()) {
            SDL_CPUFeatures |= CPU_HAS_LASX;
            SDL_SIMDAlignment = SDL_max(SDL_SIMDAlignment, 32);
        }
        SDL_CPUFeatures &= SDL_CPUFeatureMaskFromHint();
    }
    return SDL_CPUFeatures;
}
References CPU_calcCPUIDFeatures(), CPU_HAS_ALTIVEC, CPU_HAS_ARM_SIMD, CPU_HAS_AVX, CPU_HAS_AVX2, CPU_HAS_AVX512F, CPU_HAS_LASX, CPU_HAS_LSX, CPU_HAS_MMX, CPU_HAS_NEON, CPU_HAS_SSE, CPU_HAS_SSE2, CPU_HAS_SSE3, CPU_HAS_SSE41, CPU_HAS_SSE42, CPU_haveAltiVec(), CPU_haveARMSIMD(), CPU_haveAVX, CPU_haveAVX2(), CPU_haveAVX512F(), CPU_haveLASX, CPU_haveLSX, CPU_haveMMX, CPU_haveNEON(), CPU_haveSSE, CPU_haveSSE2, CPU_haveSSE3, CPU_haveSSE41, CPU_haveSSE42, SDL_CPUFeatureMaskFromHint(), SDL_CPUFeatures, SDL_CPUFEATURES_RESET_VALUE, SDL_max, and SDL_SIMDAlignment.
Referenced by SDL_GetSIMDAlignment().
SDL_GetCPUType()
const char * SDL_GetCPUType (void) static
{
    static char SDL_CPUType[13];
    if (!SDL_CPUType[0]) {
        int i = 0;
        CPU_calcCPUIDFeatures();
        if (CPU_CPUIDMaxFunction > 0) { // do we have CPUID at all?
            int a, b, c, d;
            cpuid(0x00000000, a, b, c, d);
            (void)a;
            SDL_CPUType[i++] = (char)(b & 0xff);
            b >>= 8;
            SDL_CPUType[i++] = (char)(b & 0xff);
            b >>= 8;
            SDL_CPUType[i++] = (char)(b & 0xff);
            b >>= 8;
            SDL_CPUType[i++] = (char)(b & 0xff);
            SDL_CPUType[i++] = (char)(d & 0xff);
            d >>= 8;
            SDL_CPUType[i++] = (char)(d & 0xff);
            d >>= 8;
            SDL_CPUType[i++] = (char)(d & 0xff);
            d >>= 8;
            SDL_CPUType[i++] = (char)(d & 0xff);
            SDL_CPUType[i++] = (char)(c & 0xff);
            c >>= 8;
            SDL_CPUType[i++] = (char)(c & 0xff);
            c >>= 8;
            SDL_CPUType[i++] = (char)(c & 0xff);
            c >>= 8;
            SDL_CPUType[i++] = (char)(c & 0xff);
        }
        if (!SDL_CPUType[0]) {
            SDL_strlcpy(SDL_CPUType, "Unknown", sizeof(SDL_CPUType));
        }
    }
    return SDL_CPUType;
}
References CPU_calcCPUIDFeatures(), CPU_CPUIDMaxFunction, cpuid, d, SDL_strlcpy(), and void().
Referenced by SDL_GetCPUCacheLineSize().
SDL_GetNumLogicalCPUCores()
int SDL_GetNumLogicalCPUCores (void)
Get the number of logical CPU cores available.
Returns
the total number of logical CPU cores. On CPUs that include technologies such as hyperthreading, the number of logical cores may be more than the number of physical cores.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!SDL_NumLogicalCPUCores) {
#if defined(HAVE_SYSCONF) && defined(_SC_NPROCESSORS_ONLN)
        if (SDL_NumLogicalCPUCores <= 0) {
            SDL_NumLogicalCPUCores = (int)sysconf(_SC_NPROCESSORS_ONLN);
        }
#endif
#ifdef HAVE_SYSCTLBYNAME
        if (SDL_NumLogicalCPUCores <= 0) {
            size_t size = sizeof(SDL_NumLogicalCPUCores);
            sysctlbyname("hw.ncpu", &SDL_NumLogicalCPUCores, &size, NULL, 0);
        }
#endif
#if defined(SDL_PLATFORM_WINDOWS)
        if (SDL_NumLogicalCPUCores <= 0) {
            SYSTEM_INFO info;
            GetSystemInfo(&info);
            SDL_NumLogicalCPUCores = info.dwNumberOfProcessors;
        }
#endif
#ifdef SDL_PLATFORM_3DS
        if (SDL_NumLogicalCPUCores <= 0) {
            bool isNew3DS = false;
            APT_CheckNew3DS(&isNew3DS);
            // 1 core is always dedicated to the OS
            // Meaning that the New3DS has 3 available core, and the Old3DS only one.
            SDL_NumLogicalCPUCores = isNew3DS ? 4 : 2;
        }
#endif
        // There has to be at least 1, right? :)
        if (SDL_NumLogicalCPUCores <= 0) {
            SDL_NumLogicalCPUCores = 1;
        }
    }
    return SDL_NumLogicalCPUCores;
}
References NULL, and SDL_NumLogicalCPUCores.
Referenced by PrepareThreadpool().
SDL_GetSIMDAlignment()
size_t SDL_GetSIMDAlignment (void)
Report the alignment this system needs for SIMD allocations.
This will return the minimum number of bytes to which a pointer must be aligned to be compatible with SIMD instructions on the current machine. For example, if the machine supports SSE only, it will return 16, but if it supports AVX-512F, it'll return 64 (etc). This only reports values for instruction sets SDL knows about, so if your SDL build doesn't have SDL_HasAVX512F(), then it might return 16 for the SSE support it sees and not 64 for the AVX-512 instructions that exist but SDL doesn't know about. Plan accordingly.
Returns
the alignment in bytes needed for available, known SIMD instructions.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_aligned_alloc
SDL_aligned_free
{
    if (SDL_SIMDAlignment == 0xFFFFFFFF) {
        SDL_GetCPUFeatures(); // make sure this has been calculated
    }
    SDL_assert(SDL_SIMDAlignment != 0);
    return SDL_SIMDAlignment;
}
References SDL_assert, SDL_GetCPUFeatures(), and SDL_SIMDAlignment.
Referenced by EnsureAudioStreamWorkBufferSize(), GetAudioStreamDataInternal(), OpenPhysicalAudioDevice(), SDL_AudioDeviceFormatChangedAlreadyLocked(), SDL_CreateSurface(), SDL_ResetAudioQueueHistory(), SDL_SetAudioPostmixCallback(), and ZombieAcquireFrame().
SDL_GetSystemRAM()
int SDL_GetSystemRAM (void)
Get the amount of RAM configured in the system.
Returns
the amount of RAM configured in the system in MiB.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (!SDL_SystemRAM) {
#if defined(HAVE_SYSCONF) && defined(_SC_PHYS_PAGES) && defined(_SC_PAGESIZE)
        if (SDL_SystemRAM <= 0) {
            SDL_SystemRAM = (int)((Sint64)sysconf(_SC_PHYS_PAGES) * sysconf(_SC_PAGESIZE) / (1024 * 1024));
        }
#endif
#ifdef HAVE_SYSCTLBYNAME
        if (SDL_SystemRAM <= 0) {
#ifdef HW_PHYSMEM64
            // (64-bit): NetBSD since 2003, OpenBSD
            int mib[2] = { CTL_HW, HW_PHYSMEM64 };
#elif defined(HW_REALMEM)
            // (64-bit): FreeBSD since 2005, DragonFly
            int mib[2] = { CTL_HW, HW_REALMEM };
#elif defined(HW_MEMSIZE)
            // (64-bit): Darwin
            int mib[2] = { CTL_HW, HW_MEMSIZE };
#else
            // (32-bit): very old BSD, might only report up to 2 GiB
            int mib[2] = { CTL_HW, HW_PHYSMEM };
#endif // HW_PHYSMEM64
            Uint64 memsize = 0;
            size_t len = sizeof(memsize);
            if (sysctl(mib, 2, &memsize, &len, NULL, 0) == 0) {
                SDL_SystemRAM = (int)(memsize / (1024 * 1024));
            }
        }
#endif
#if defined(SDL_PLATFORM_WINDOWS)
        if (SDL_SystemRAM <= 0) {
            MEMORYSTATUSEX stat;
            stat.dwLength = sizeof(stat);
            if (GlobalMemoryStatusEx(&stat)) {
                SDL_SystemRAM = (int)(stat.ullTotalPhys / (1024 * 1024));
            }
        }
#endif
#ifdef SDL_PLATFORM_RISCOS
        if (SDL_SystemRAM <= 0) {
            _kernel_swi_regs regs;
            regs.r[0] = 0x108;
            if (_kernel_swi(OS_Memory, &regs, &regs) == NULL) {
                SDL_SystemRAM = (int)(regs.r[1] * regs.r[2] / (1024 * 1024));
            }
        }
#endif
#ifdef SDL_PLATFORM_3DS
        if (SDL_SystemRAM <= 0) {
            // The New3DS has 255MiB, the Old3DS 127MiB
            SDL_SystemRAM = (int)(osGetMemRegionSize(MEMREGION_ALL) / (1024 * 1024));
        }
#endif
#ifdef SDL_PLATFORM_VITA
        if (SDL_SystemRAM <= 0) {
            /* Vita has 512MiB on SoC, that's split into 256MiB(+109MiB in extended memory mode) for app
               +26MiB of physically continuous memory, +112MiB of CDRAM(VRAM) + system reserved memory. */
            SDL_SystemRAM = 536870912;
        }
#endif
#ifdef SDL_PLATFORM_PS2
        if (SDL_SystemRAM <= 0) {
            // PlayStation 2 has 32MiB however there are some special models with 64 and 128
            SDL_SystemRAM = GetMemorySize();
        }
#endif
#ifdef SDL_PLATFORM_HAIKU
        if (SDL_SystemRAM <= 0) {
            system_info info;
            if (get_system_info(&info) == B_OK) {
                /* To have an accurate amount, we also take in account the inaccessible pages (aka ignored)
                  which is a bit handier compared to the legacy system's api (i.e. used_pages).*/
                SDL_SystemRAM = (int)SDL_round((info.max_pages + info.ignored_pages > 0 ? info.ignored_pages : 0) * B_PAGE_SIZE / 1048576.0);
            }
        }
#endif
    }
    return SDL_SystemRAM;
}
References NULL, SDL_round(), and SDL_SystemRAM.
SDL_HasAltiVec()
bool SDL_HasAltiVec (void)
Determine whether the CPU has AltiVec features.
This always returns false on CPUs that aren't using PowerPC instruction sets.
Returns
true if the CPU has AltiVec features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_ALTIVEC);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_ALTIVEC.
SDL_HasARMSIMD()
bool SDL_HasARMSIMD (void)
Determine whether the CPU has ARM SIMD (ARMv6) features.
This is different from ARM NEON, which is a different instruction set.
This always returns false on CPUs that aren't using ARM instruction sets.
Returns
true if the CPU has ARM SIMD features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasNEON
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_ARM_SIMD);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_ARM_SIMD.
SDL_HasAVX()
bool SDL_HasAVX (void)
Determine whether the CPU has AVX features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has AVX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasAVX2
SDL_HasAVX512F
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_AVX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_AVX.
SDL_HasAVX2()
bool SDL_HasAVX2 (void)
Determine whether the CPU has AVX2 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has AVX2 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasAVX
SDL_HasAVX512F
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_AVX2);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_AVX2.
SDL_HasAVX512F()
bool SDL_HasAVX512F (void)
Determine whether the CPU has AVX-512F (foundation) features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has AVX-512F features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasAVX
SDL_HasAVX2
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_AVX512F);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_AVX512F.
SDL_HasLASX()
bool SDL_HasLASX (void)
Determine whether the CPU has LASX (LOONGARCH SIMD) features.
This always returns false on CPUs that aren't using LOONGARCH instruction sets.
Returns
true if the CPU has LOONGARCH LASX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_LASX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_LASX.
SDL_HasLSX()
bool SDL_HasLSX (void)
Determine whether the CPU has LSX (LOONGARCH SIMD) features.
This always returns false on CPUs that aren't using LOONGARCH instruction sets.
Returns
true if the CPU has LOONGARCH LSX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_LSX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_LSX.
SDL_HasMMX()
bool SDL_HasMMX (void)
Determine whether the CPU has MMX features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has MMX features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_MMX);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_MMX.
SDL_HasNEON()
bool SDL_HasNEON (void)
Determine whether the CPU has NEON (ARM SIMD) features.
This always returns false on CPUs that aren't using ARM instruction sets.
Returns
true if the CPU has ARM NEON features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_NEON);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_NEON.
Referenced by SDL_ChooseAudioConverters(), and SetupAudioResampler().
SDL_HasSSE()
bool SDL_HasSSE (void)
Determine whether the CPU has SSE features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE2
SDL_HasSSE3
SDL_HasSSE41
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE.
Referenced by ConvertAudio(), SDL_BlitCopy(), SDL_FillSurfaceRects(), and SetupAudioResampler().
SDL_HasSSE2()
bool SDL_HasSSE2 (void)
Determine whether the CPU has SSE2 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE2 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE3
SDL_HasSSE41
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE2);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE2.
Referenced by SDL_ChooseAudioConverters().
SDL_HasSSE3()
bool SDL_HasSSE3 (void)
Determine whether the CPU has SSE3 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE3 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE2
SDL_HasSSE41
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE3);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE3.
Referenced by ConvertAudio().
SDL_HasSSE41()
bool SDL_HasSSE41 (void)
Determine whether the CPU has SSE4.1 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE4.1 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE2
SDL_HasSSE3
SDL_HasSSE42
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE41);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE41.
Referenced by SDL_ChooseAudioConverters().
SDL_HasSSE42()
bool SDL_HasSSE42 (void)
Determine whether the CPU has SSE4.2 features.
This always returns false on CPUs that aren't using Intel instruction sets.
Returns
true if the CPU has SSE4.2 features or false if not.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasSSE
SDL_HasSSE2
SDL_HasSSE3
SDL_HasSSE41
{
    return CPU_FEATURE_AVAILABLE(CPU_HAS_SSE42);
}
References CPU_FEATURE_AVAILABLE, and CPU_HAS_SSE42.
SDL_QuitCPUInfo()
void SDL_QuitCPUInfo (void)
{
    SDL_CPUFeatures = SDL_CPUFEATURES_RESET_VALUE;
}
References SDL_CPUFeatures, and SDL_CPUFEATURES_RESET_VALUE.
Referenced by SDL_Quit().
Variable Documentation
CPU_CPUIDFeatures
int CPU_CPUIDFeatures[4] static
Referenced by CPU_calcCPUIDFeatures().
CPU_CPUIDMaxFunction
int CPU_CPUIDMaxFunction = 0 static
Referenced by CPU_calcCPUIDFeatures(), CPU_haveAVX2(), CPU_haveAVX512F(), and SDL_GetCPUType().
CPU_OSSavesYMM
bool CPU_OSSavesYMM = false static
Referenced by CPU_calcCPUIDFeatures(), and CPU_haveAVX2().
CPU_OSSavesZMM
bool CPU_OSSavesZMM = false static
Referenced by CPU_calcCPUIDFeatures(), and CPU_haveAVX512F().
SDL_CPUFeatures
Uint32 SDL_CPUFeatures = 0xFFFFFFFF static
Referenced by SDL_GetCPUFeatures(), and SDL_QuitCPUInfo().
SDL_NumLogicalCPUCores
int SDL_NumLogicalCPUCores = 0 static
Referenced by SDL_GetNumLogicalCPUCores().
SDL_SIMDAlignment
Uint32 SDL_SIMDAlignment = 0xFFFFFFFF static
Referenced by SDL_GetCPUFeatures(), and SDL_GetSIMDAlignment().
SDL_SystemRAM
int SDL_SystemRAM = 0 static
Referenced by SDL_GetSystemRAM().