SDL3: SDL-main/src/video/qnx/SDL_qnx.h File Reference
SDL_qnx.h File Reference
#include "../SDL_sysvideo.h"
#include <screen/screen.h>
#include <EGL/egl.h>
Data Structures
struct window_impl_t
Functions
SDL_GLContext glCreateContext (SDL_VideoDevice *_this, SDL_Window *window)
void glDeleteContext (SDL_VideoDevice *_this, SDL_GLContext context)
bool glGetConfig (EGLConfig *pconf, int *pformat)
SDL_FunctionPointer glGetProcAddress (SDL_VideoDevice *_this, const char *proc)
bool glLoadLibrary (SDL_VideoDevice *_this, const char *name)
bool glMakeCurrent (SDL_VideoDevice *_this, SDL_Window *window, SDL_GLContext context)
bool glSetSwapInterval (SDL_VideoDevice *_this, int interval)
bool glSwapWindow (SDL_VideoDevice *_this, SDL_Window *window)
void glUnloadLibrary (SDL_VideoDevice *_this)
void handleKeyboardEvent (screen_event_t event)
Function Documentation
glCreateContext()
SDL_GLContext glCreateContext (SDL_VideoDevice * _this, SDL_Window * window) extern
Associates the given window with the necessary EGL structures for drawing and displaying content.
Parameters
SDL_VideoDevice *_this
window The SDL window to create the context for
Returns
A pointer to the created context, if successful, NULL on error
{
    window_impl_t   *impl = (window_impl_t *)window->internal;
    EGLContext      context;
    EGLSurface      surface;
    struct {
        EGLint client_version[2];
        EGLint none;
    } egl_ctx_attr = {
        .client_version = { EGL_CONTEXT_CLIENT_VERSION, 2 },
        .none = EGL_NONE
    };
    struct {
        EGLint render_buffer[2];
        EGLint none;
    } egl_surf_attr = {
        .render_buffer = { EGL_RENDER_BUFFER, EGL_BACK_BUFFER },
        .none = EGL_NONE
    };
    context = eglCreateContext(egl_disp, impl->conf, EGL_NO_CONTEXT,
                               (EGLint *)&egl_ctx_attr);
    if (context == EGL_NO_CONTEXT) {
        return NULL;
    }
    surface = eglCreateWindowSurface(egl_disp, impl->conf,
                                     (EGLNativeWindowType)impl->window,
                                     (EGLint *)&egl_surf_attr);
    if (surface == EGL_NO_SURFACE) {
        return NULL;
    }
    eglMakeCurrent(egl_disp, surface, surface, context);
    impl->surface = surface;
    return context;
}
References _this, window_impl_t::conf, context, EGL_BACK_BUFFER, EGL_CONTEXT_CLIENT_VERSION, egl_disp, EGL_NO_CONTEXT, EGL_NO_SURFACE, EGL_NONE, EGL_RENDER_BUFFER, eglCreateContext(), eglCreateWindowSurface(), eglMakeCurrent(), NULL, window_impl_t::surface, and window_impl_t::window.
Referenced by createDevice().
glDeleteContext()
void glDeleteContext (SDL_VideoDevice * _this, SDL_GLContext context) extern
Destroys a context.
Parameters
SDL_VideoDevice *_this
context The context to destroy
{
    eglDestroyContext(egl_disp, context);
    return true;
}
References _this, context, egl_disp, and eglDestroyContext().
Referenced by createDevice().
glGetConfig()
bool glGetConfig (EGLConfig * pconf, int * pformat) extern
Enumerates the supported EGL configurations and chooses a suitable one.
Parameters
[out] pconf The chosen configuration
[out] pformat The chosen pixel format
Returns
true if successful, -1 on error
{
    EGLConfig egl_conf = (EGLConfig)0;
    EGLConfig *egl_configs;
    EGLint egl_num_configs;
    EGLint val;
    EGLBoolean rc;
    EGLint i;
    // Determine the numbfer of configurations.
    rc = eglGetConfigs(egl_disp, NULL, 0, &egl_num_configs);
    if (rc != EGL_TRUE) {
        return false;
    }
    if (egl_num_configs == 0) {
        return false;
    }
    // Allocate enough memory for all configurations.
    egl_configs = SDL_malloc(egl_num_configs * sizeof(*egl_configs));
    if (!egl_configs) {
        return false;
    }
    // Get the list of configurations.
    rc = eglGetConfigs(egl_disp, egl_configs, egl_num_configs,
                       &egl_num_configs);
    if (rc != EGL_TRUE) {
        SDL_free(egl_configs);
        return false;
    }
    // Find a good configuration.
    for (i = 0; i < egl_num_configs; i++) {
        eglGetConfigAttrib(egl_disp, egl_configs[i], EGL_SURFACE_TYPE, &val);
        if (!(val & EGL_WINDOW_BIT)) {
            continue;
        }
        eglGetConfigAttrib(egl_disp, egl_configs[i], EGL_RENDERABLE_TYPE, &val);
        if (!(val & EGL_OPENGL_ES2_BIT)) {
            continue;
        }
        eglGetConfigAttrib(egl_disp, egl_configs[i], EGL_DEPTH_SIZE, &val);
        if (val == 0) {
            continue;
        }
        egl_conf = egl_configs[i];
        break;
    }
    SDL_free(egl_configs);
    *pconf = egl_conf;
    *pformat = chooseFormat(egl_conf);
    return true;
}
References chooseFormat(), EGL_DEPTH_SIZE, egl_disp, EGL_OPENGL_ES2_BIT, EGL_RENDERABLE_TYPE, EGL_SURFACE_TYPE, EGL_TRUE, EGL_WINDOW_BIT, eglGetConfigAttrib(), eglGetConfigs(), NULL, SDL_free(), and SDL_malloc().
Referenced by createWindow().
glGetProcAddress()
SDL_FunctionPointer glGetProcAddress (SDL_VideoDevice * _this, const char * proc) extern
Finds the address of an EGL extension function.
Parameters
proc Function name
Returns
Function address
{
    return eglGetProcAddress(proc);
}
References _this, and eglGetProcAddress().
Referenced by createDevice().
glLoadLibrary()
bool glLoadLibrary (SDL_VideoDevice * _this, const char * name) extern
Initializes the EGL library.
Parameters
SDL_VideoDevice *_this
name unused
Returns
0 if successful, -1 on error
{
    EGLNativeDisplayType    disp_id = EGL_DEFAULT_DISPLAY;
    egl_disp = eglGetDisplay(disp_id);
    if (egl_disp == EGL_NO_DISPLAY) {
        return false;
    }
    if (eglInitialize(egl_disp, NULL, NULL) == EGL_FALSE) {
        return false;
    }
    return true;
}
References _this, EGL_DEFAULT_DISPLAY, egl_disp, EGL_FALSE, EGL_NO_DISPLAY, eglGetDisplay(), eglInitialize(), and NULL.
Referenced by createDevice().
glMakeCurrent()
bool glMakeCurrent (SDL_VideoDevice * _this, SDL_Window * window, SDL_GLContext context) extern
Makes the given context the current one for drawing operations.
Parameters
SDL_VideoDevice *_this
window SDL window associated with the context (maybe NULL)
context The context to activate
Returns
0 if successful, -1 on error
{
    window_impl_t   *impl;
    EGLSurface      surface = NULL;
    if (window) {
        impl = (window_impl_t *)window->internal;
        surface = impl->surface;
    }
    if (eglMakeCurrent(egl_disp, surface, surface, context) != EGL_TRUE) {
        return false;
    }
    return true;
}
References _this, context, egl_disp, EGL_TRUE, eglMakeCurrent(), NULL, and window_impl_t::surface.
Referenced by createDevice().
glSetSwapInterval()
bool glSetSwapInterval (SDL_VideoDevice * _this, int interval) extern
Sets a new value for the number of frames to display before swapping buffers.
Parameters
SDL_VideoDevice *_this
interval New interval value
Returns
0 if successful, -1 on error
{
    if (eglSwapInterval(egl_disp, interval) != EGL_TRUE) {
        return false;
    }
    return true;
}
References _this, egl_disp, EGL_TRUE, and eglSwapInterval().
Referenced by createDevice().
glSwapWindow()
bool glSwapWindow (SDL_VideoDevice * _this, SDL_Window * window) extern
Swaps the EGL buffers associated with the given window
Parameters
SDL_VideoDevice *_this
window Window to swap buffers for
Returns
0 if successful, -1 on error
{
    // !!! FIXME: should we migrate this all over to use SDL_egl.c?
    window_impl_t   *impl = (window_impl_t *)window->internal;
    return eglSwapBuffers(egl_disp, impl->surface) == EGL_TRUE ? 0 : -1;
}
References _this, egl_disp, EGL_TRUE, eglSwapBuffers(), and window_impl_t::surface.
Referenced by createDevice().
glUnloadLibrary()
void glUnloadLibrary (SDL_VideoDevice * _this) extern
Terminates access to the EGL library.
Parameters
SDL_VideoDevice *_this
{
    eglTerminate(egl_disp);
}
References _this, egl_disp, and eglTerminate().
Referenced by createDevice().
handleKeyboardEvent()
void handleKeyboardEvent (screen_event_t event) extern
Called from the event dispatcher when a keyboard event is encountered. Translates the event such that it can be handled by SDL.
Parameters
event Screen keyboard event
{
    int             val;
    SDL_Scancode    scancode;
    // Get the key value.
    if (screen_get_event_property_iv(event, SCREEN_PROPERTY_SYM, &val) < 0) {
        return;
    }
    // Skip unrecognized keys.
    if ((val < 0) || (val >= SDL_arraysize(key_to_sdl))) {
        return;
    }
    // Translate to an SDL scan code.
    scancode = key_to_sdl[val];
    if (scancode == 0) {
        return;
    }
    // Get event flags (key state).
    if (screen_get_event_property_iv(event, SCREEN_PROPERTY_FLAGS, &val) < 0) {
        return;
    }
    // Propagate the event to SDL.
    // FIXME:
    // Need to handle more key states (such as key combinations).
    if (val & KEY_DOWN) {
        SDL_SendKeyboardKey(0, SDL_DEFAULT_KEYBOARD_ID, val, scancode, true);
    } else {
        SDL_SendKeyboardKey(0, SDL_DEFAULT_KEYBOARD_ID, val, scancode, false);
    }
}
References key_to_sdl, scancode, SDL_arraysize, SDL_DEFAULT_KEYBOARD_ID, and SDL_SendKeyboardKey().
Referenced by pumpEvents().