SDL3: SDL-main/src/hidapi/netbsd/hid.c File Reference
hid.c File Reference
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <locale.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <iconv.h>
#include <poll.h>
#include <sys/drvctlio.h>
#include <dev/usb/usb.h>
#include <dev/usb/usbhid.h>
#include "../hidapi/hidapi.h"
Data Structures
struct hid_enumerate_data
struct hid_usage_iterator
struct PLATFORM_hid_device_
Macros
#define HIDAPI_MAX_CHILD_DEVICES 256
Typedefs
typedef void(* enumerate_devices_callback) (const struct usb_device_info *, void *)
Functions
static struct hid_device_info * create_device_info (const struct usb_device_info *udi, const char *path, const struct usb_ctl_report_desc *ucrd)
static void enumerate_usb_devices (int bus, uint8_t addr, enumerate_devices_callback func, void *data)
static int get_hid_item_size (const uint8_t *report_descriptor, uint32_t size, unsigned int pos, int *data_len, int *key_size)
static uint32_t get_hid_report_bytes (const uint8_t *rpt, size_t len, size_t num_bytes, size_t cur)
static int get_next_hid_usage (const uint8_t *report_descriptor, uint32_t size, struct hid_usage_iterator *ctx, unsigned short *usage_page, unsigned short *usage)
static int get_report (PLATFORM_hid_device *dev, uint8_t *data, size_t length, int report)
static void hid_enumerate_callback (const struct usb_device_info *udi, void *data)
static int hid_iterate_over_collection (const uint8_t *report_descriptor, uint32_t size, unsigned int *pos, int *data_len, int *key_size)
static int is_uhid_device (const char *s)
static int is_uhid_parent_device (const char *s)
static int is_usb_controller (const char *s)
void PLATFORM_hid_close (PLATFORM_hid_device *dev)
struct hid_device_info * PLATFORM_hid_enumerate (unsigned short vendor_id, unsigned short product_id)
const wchar_t * PLATFORM_hid_error (PLATFORM_hid_device *dev)
int PLATFORM_hid_exit (void)
void PLATFORM_hid_free_enumeration (struct hid_device_info *devs)
struct hid_device_info * PLATFORM_hid_get_device_info (PLATFORM_hid_device *dev)
int PLATFORM_hid_get_feature_report (PLATFORM_hid_device *dev, unsigned char *data, size_t length)
int PLATFORM_hid_get_indexed_string (PLATFORM_hid_device *dev, int string_index, wchar_t *string, size_t maxlen)
int PLATFORM_hid_get_input_report (PLATFORM_hid_device *dev, unsigned char *data, size_t length)
int PLATFORM_hid_get_manufacturer_string (PLATFORM_hid_device *dev, wchar_t *string, size_t maxlen)
int PLATFORM_hid_get_product_string (PLATFORM_hid_device *dev, wchar_t *string, size_t maxlen)
int PLATFORM_hid_get_report_descriptor (PLATFORM_hid_device *dev, unsigned char *buf, size_t buf_size)
int PLATFORM_hid_get_serial_number_string (PLATFORM_hid_device *dev, wchar_t *string, size_t maxlen)
int PLATFORM_hid_init (void)
PLATFORM_hid_device * PLATFORM_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
PLATFORM_hid_device * PLATFORM_hid_open_path (const char *path)
int PLATFORM_hid_read (PLATFORM_hid_device *dev, unsigned char *data, size_t length)
int PLATFORM_hid_read_timeout (PLATFORM_hid_device *dev, unsigned char *data, size_t length, int milliseconds)
int PLATFORM_hid_send_feature_report (PLATFORM_hid_device *dev, const unsigned char *data, size_t length)
int PLATFORM_hid_set_nonblocking (PLATFORM_hid_device *dev, int nonblock)
const struct hid_api_version * PLATFORM_hid_version (void)
const char * PLATFORM_hid_version_str (void)
int PLATFORM_hid_write (PLATFORM_hid_device *dev, const unsigned char *data, size_t length)
static void register_device_error (PLATFORM_hid_device *dev, const char *msg)
static void register_device_error_format (PLATFORM_hid_device *dev, const char *format,...)
static void register_error_str (wchar_t **error_str, const char *msg)
static void register_error_str_vformat (wchar_t **error_str, const char *format, va_list args)
static void register_global_error (const char *msg)
static void register_global_error_format (const char *format,...)
static int set_report (PLATFORM_hid_device *dev, const uint8_t *data, size_t length, int report)
static wchar_t * utf8_to_wchar_t (const char *utf8)
static void walk_device_tree (int drvctl, const char *dev, int depth, char arr[static 256][USB_MAX_DEVNAMELEN], size_t *len, int(*cmp)(const char *))
Variables
static wchar_t * last_global_error_str = NULL
Macro Definition Documentation
HIDAPI_MAX_CHILD_DEVICES
#define HIDAPI_MAX_CHILD_DEVICES 256
Referenced by hid_enumerate_callback(), PLATFORM_hid_enumerate(), PLATFORM_hid_open_path(), and walk_device_tree().
Typedef Documentation
enumerate_devices_callback
typedef void(* enumerate_devices_callback) (const struct usb_device_info *, void *)
Function Documentation
create_device_info()
struct hid_device_info * create_device_info (const struct usb_device_info * udi, const char * path, const struct usb_ctl_report_desc * ucrd) static
{
    struct hid_device_info *root;
    struct hid_device_info *end;
    root = (struct hid_device_info *) calloc(1, sizeof(struct hid_device_info));
    if (!root)
        return NULL;
    end = root;
    /* Path */
    end->path = (path) ? strdup(path) : NULL;
    /* Vendor Id */
    end->vendor_id = udi->udi_vendorNo;
    /* Product Id */
    end->product_id = udi->udi_productNo;
    /* Serial Number */
    end->serial_number = utf8_to_wchar_t(udi->udi_serial);
    /* Release Number */
    end->release_number = udi->udi_releaseNo;
    /* Manufacturer String */
    end->manufacturer_string = utf8_to_wchar_t(udi->udi_vendor);
    /* Product String */
    end->product_string = utf8_to_wchar_t(udi->udi_product);
    /* Usage Page */
    end->usage_page = 0;
    /* Usage */
    end->usage = 0;
    /* Interface Number */
    end->interface_number = -1;
    /* Next Device Info */
    end->next = NULL;
    /* Bus Type */
    end->bus_type = HID_API_BUS_USB;
    if (ucrd) {
        uint16_t page;
        uint16_t usage;
        struct hid_usage_iterator usage_iterator;
        page = usage = 0;
        memset(&usage_iterator, 0, sizeof(usage_iterator));
        /*
         * Parse the first usage and usage page
         * out of the report descriptor.
         */
        if (get_next_hid_usage(ucrd->ucrd_data, ucrd->ucrd_size, &usage_iterator, &page, &usage) == 0) {
            end->usage_page = page;
            end->usage = usage;
        }
        /*
         * Parse any additional usage and usage pages
         * out of the report descriptor.
         */
        while (get_next_hid_usage(ucrd->ucrd_data, ucrd->ucrd_size, &usage_iterator, &page, &usage) == 0) {
            /* Create new record for additional usage pairs */
            struct hid_device_info *node = (struct hid_device_info *) calloc(1, sizeof(struct hid_device_info));
            if (!node)
                continue;
            /* Update fields */
            node->path = (end->path) ? strdup(end->path) : NULL;
            node->vendor_id = end->vendor_id;
            node->product_id = end->product_id;
            node->serial_number = (end->serial_number) ? wcsdup(end->serial_number) : NULL;
            node->release_number = end->release_number;
            node->manufacturer_string = (end->manufacturer_string) ? wcsdup(end->manufacturer_string) : NULL;
            node->product_string = (end->product_string) ? wcsdup(end->product_string) : NULL;
            node->usage_page = page;
            node->usage = usage;
            node->interface_number = end->interface_number;
            node->next = NULL;
            node->bus_type = end->bus_type;
            /* Insert node */
            end->next = node;
            end = node;
        }
    }
    return root;
}
References hid_device_info::bus_type, calloc, get_next_hid_usage(), HID_API_BUS_USB, hid_device_info::interface_number, hid_device_info::manufacturer_string, memset(), hid_device_info::next, NULL, hid_device_info::path, hid_device_info::product_id, hid_device_info::product_string, hid_device_info::release_number, hid_device_info::serial_number, strdup, hid_device_info::usage, hid_device_info::usage_page, utf8_to_wchar_t(), hid_device_info::vendor_id, and wcsdup.
enumerate_usb_devices()
void enumerate_usb_devices (int bus, uint8_t addr, enumerate_devices_callback func, void * data) static
{
    int res;
    struct usb_device_info udi;
    udi.udi_addr = addr;
    res = ioctl(bus, USB_DEVICEINFO, &udi);
    if (res == -1)
        return;
    for (int port = 0; port < udi.udi_nports; port++) {
        addr = udi.udi_ports[port];
        if (addr >= USB_MAX_DEVICES)
            continue;
        enumerate_usb_devices(bus, addr, func, data);
    }
    func(&udi, data);
}
References enumerate_usb_devices().
Referenced by enumerate_usb_devices(), and PLATFORM_hid_enumerate().
get_hid_item_size()
int get_hid_item_size (const uint8_t * report_descriptor, uint32_t size, unsigned int pos, int * data_len, int * key_size) static
{
    int key = report_descriptor[pos];
    int size_code;
    /*
     * This is a Long Item. The next byte contains the
     * length of the data section (value) for this key.
     * See the HID specification, version 1.11, section
     * 6.2.2.3, titled "Long Items."
     */
    if ((key & 0xf0) == 0xf0) {
        if (pos + 1 < size)
        {
            *data_len = report_descriptor[pos + 1];
            *key_size = 3;
            return 1;
        }
        *data_len = 0; /* malformed report */
        *key_size = 0;
    }
    /*
     * This is a Short Item. The bottom two bits of the
     * key contain the size code for the data section
     * (value) for this key. Refer to the HID
     * specification, version 1.11, section 6.2.2.2,
     * titled "Short Items."
     */
    size_code = key & 0x3;
    switch (size_code) {
    case 0:
    case 1:
    case 2:
        *data_len = size_code;
        *key_size = 1;
        return 1;
    case 3:
        *data_len = 4;
        *key_size = 1;
        return 1;
    default:
        /* Can't ever happen since size_code is & 0x3 */
        *data_len = 0;
        *key_size = 0;
        break;
    };
    /* malformed report */
    return 0;
}
get_hid_report_bytes()
uint32_t get_hid_report_bytes (const uint8_t * rpt, size_t len, size_t num_bytes, size_t cur) static
{
    /* Return if there aren't enough bytes. */
    if (cur + num_bytes >= len)
        return 0;
    if (num_bytes == 0)
        return 0;
    else if (num_bytes == 1)
        return rpt[cur + 1];
    else if (num_bytes == 2)
        return (rpt[cur + 2] * 256 + rpt[cur + 1]);
    else if (num_bytes == 4)
        return (
            rpt[cur + 4] * 0x01000000 +
            rpt[cur + 3] * 0x00010000 +
            rpt[cur + 2] * 0x00000100 +
            rpt[cur + 1] * 0x00000001
        );
    else
        return 0;
}
get_next_hid_usage()
int get_next_hid_usage (const uint8_t * report_descriptor, uint32_t size, struct hid_usage_iterator * ctx, unsigned short * usage_page, unsigned short * usage) static
{
    int data_len, key_size;
    int initial = ctx->pos == 0; /* Used to handle case where no top-level application collection is defined */
    int usage_found = 0;
    while (ctx->pos < size) {
        int key = report_descriptor[ctx->pos];
        int key_cmd = key & 0xfc;
        /* Determine data_len and key_size */
        if (!get_hid_item_size(report_descriptor, size, ctx->pos, &data_len, &key_size))
            return -1; /* malformed report */
        switch (key_cmd) {
        case 0x4: /* Usage Page 6.2.2.7 (Global) */
            ctx->usage_page = get_hid_report_bytes(report_descriptor, size, data_len, ctx->pos);
            ctx->usage_page_found = 1;
            break;
        case 0x8: /* Usage 6.2.2.8 (Local) */
            if (data_len == 4) { /* Usages 5.5 / Usage Page 6.2.2.7 */
                ctx->usage_page = get_hid_report_bytes(report_descriptor, size, 2, ctx->pos + 2);
                ctx->usage_page_found = 1;
                *usage = get_hid_report_bytes(report_descriptor, size, 2, ctx->pos);
                usage_found = 1;
            }
            else {
                *usage = get_hid_report_bytes(report_descriptor, size, data_len, ctx->pos);
                usage_found = 1;
            }
            break;
        case 0xa0: /* Collection 6.2.2.4 (Main) */
            if (!hid_iterate_over_collection(report_descriptor, size, &ctx->pos, &data_len, &key_size)) {
                return -1;
            }
            /* A pair is valid - to be reported when Collection is found */
            if (usage_found && ctx->usage_page_found) {
                *usage_page = ctx->usage_page;
                return 0;
            }
            break;
        }
        /* Skip over this key and its associated data */
        ctx->pos += data_len + key_size;
    }
    /* If no top-level application collection is found and usage page/usage pair is found, pair is valid
       https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/top-level-collections */
    if (initial && usage_found && ctx->usage_page_found) {
            *usage_page = ctx->usage_page;
            return 0; /* success */
    }
    return 1; /* finished processing */
}
References get_hid_item_size(), get_hid_report_bytes(), and hid_iterate_over_collection().
get_report()
int get_report (PLATFORM_hid_device * dev, uint8_t * data, size_t length, int report) static
{
    int res;
    int device_handle;
    struct usb_ctl_report ucr;
    if (length < 1) {
        register_device_error(dev, "report must be greater than 1 byte");
        return -1;
    }
    device_handle = dev->report_handles[*data];
    if (device_handle < 0) {
        register_device_error_format(dev, "unsupported report id: %hhu", *data);
        return -1;
    }
    length--;
    data++;
    if (length > sizeof(ucr.ucr_data)) {
        length = sizeof(ucr.ucr_data);
    }
    ucr.ucr_report = report;
    res = ioctl(device_handle, USB_GET_REPORT, &ucr);
    if (res == -1) {
        register_device_error_format(dev, "ioctl (USB_GET_REPORT): %s", strerror(errno));
        return -1;
    }
    memcpy(data, ucr.ucr_data, length);
    return (int) (length + 1);
}
References hid_device, memcpy, register_device_error(), and register_device_error_format().
hid_enumerate_callback()
void hid_enumerate_callback (const struct usb_device_info * udi, void * data) static
{
    struct hid_enumerate_data *hed;
    hed = (struct hid_enumerate_data *) data;
    if (hed->vendor_id != 0 && hed->vendor_id != udi->udi_vendorNo)
        return;
    if (hed->product_id != 0 && hed->product_id != udi->udi_productNo)
        return;
    for (size_t i = 0; i < USB_MAX_DEVNAMES; i++) {
        const char *parent_dev;
        char arr[HIDAPI_MAX_CHILD_DEVICES][USB_MAX_DEVNAMELEN];
        size_t len;
        const char *child_dev;
        char devpath[USB_MAX_DEVNAMELEN];
        int uhid;
        struct usb_ctl_report_desc ucrd;
        int use_ucrd;
        struct hid_device_info *node;
        parent_dev = udi->udi_devnames[i];
        if (!is_uhid_parent_device(parent_dev))
            continue;
        len = 0;
        walk_device_tree(hed->drvctl, parent_dev, 0, arr, &len, is_uhid_device);
        if (len == 0)
            continue;
        child_dev = arr[0];
        strlcpy(devpath, "/dev/", sizeof(devpath));
        strlcat(devpath, child_dev, sizeof(devpath));
        uhid = open(devpath, O_RDONLY | O_CLOEXEC);
        if (uhid >= 0) {
            use_ucrd = (ioctl(uhid, USB_GET_REPORT_DESC, &ucrd) != -1);
            close(uhid);
        } else {
            use_ucrd = 0;
        }
        node = create_device_info(udi, parent_dev, (use_ucrd) ? &ucrd : NULL);
        if (!node)
            continue;
        if (!hed->root) {
            hed->root = node;
            hed->end = node;
        } else {
            hed->end->next = node;
            hed->end = node;
        }
        while (hed->end->next)
            hed->end = hed->end->next;
    }
}
References create_device_info(), hid_enumerate_data::drvctl, hid_enumerate_data::end, HIDAPI_MAX_CHILD_DEVICES, is_uhid_device(), is_uhid_parent_device(), hid_device_info::next, NULL, O_CLOEXEC, hid_enumerate_data::product_id, hid_enumerate_data::root, hid_enumerate_data::vendor_id, and walk_device_tree().
Referenced by PLATFORM_hid_enumerate().
hid_iterate_over_collection()
int hid_iterate_over_collection (const uint8_t * report_descriptor, uint32_t size, unsigned int * pos, int * data_len, int * key_size) static
{
    int collection_level = 0;
    while (*pos < size) {
        int key = report_descriptor[*pos];
        int key_cmd = key & 0xfc;
        /* Determine data_len and key_size */
        if (!get_hid_item_size(report_descriptor, size, *pos, data_len, key_size))
            return 0; /* malformed report */
        switch (key_cmd) {
        case 0xa0: /* Collection 6.2.2.4 (Main) */
            collection_level++;
            break;
        case 0xc0: /* End Collection 6.2.2.4 (Main) */
            collection_level--;
            break;
        }
        if (collection_level < 0) {
            /* Broken descriptor or someone is using this function wrong,
             * i.e. should be called exactly at the collection start */
            return 0;
        }
        if (collection_level == 0) {
            /* Found it!
             * Also possible when called not at the collection start, but should not happen if used correctly */
            return 1;
        }
        *pos += *data_len + *key_size;
    }
    return 0; /* Did not find the end of a Collection */
}
References get_hid_item_size().
is_uhid_device()
int is_uhid_device (const char * s) static
{
    return (!strncmp(s, "uhid", 4) && isdigit((int) s[4]));
}
Referenced by hid_enumerate_callback(), and PLATFORM_hid_open_path().
is_uhid_parent_device()
int is_uhid_parent_device (const char * s) static
{
    return (!strncmp(s, "uhidev", 6) && isdigit((int) s[6]));
}
Referenced by hid_enumerate_callback(), and PLATFORM_hid_open_path().
is_usb_controller()
int is_usb_controller (const char * s) static
{
    return (!strncmp(s, "usb", 3) && isdigit((int) s[3]));
}
Referenced by PLATFORM_hid_enumerate().
PLATFORM_hid_close()
void PLATFORM_hid_close (PLATFORM_hid_device * dev)
< API export macro < API call macro
{
    if (!dev)
        return;
    /* Free the device error message */
    register_device_error(dev, NULL);
    hid_free_enumeration(dev->device_info);
    for (size_t i = 0; i < dev->poll_handles_length; i++)
        close(dev->poll_handles[i].fd);
    free(dev);
}
References free, HID_API_CALL, HID_API_EXPORT, hid_device, hid_free_enumeration, NULL, and register_device_error().
PLATFORM_hid_enumerate()
struct hid_device_info * PLATFORM_hid_enumerate (unsigned short vendor_id, unsigned short product_id)
< API export macro < API call macro
{
    int res;
    int drvctl;
    char arr[HIDAPI_MAX_CHILD_DEVICES][USB_MAX_DEVNAMELEN];
    size_t len;
    struct hid_enumerate_data hed;
    res = hid_init();
    if (res == -1)
        return NULL;
    drvctl = open(DRVCTLDEV, O_RDONLY | O_CLOEXEC);
    if (drvctl == -1) {
        register_global_error_format("failed to open drvctl: %s", strerror(errno));
        return NULL;
    }
    len = 0;
    walk_device_tree(drvctl, "", 0, arr, &len, is_usb_controller);
    hed.root = NULL;
    hed.end = NULL;
    hed.drvctl = drvctl;
    hed.vendor_id = vendor_id;
    hed.product_id = product_id;
    for (size_t i = 0; i < len; i++) {
        char devpath[USB_MAX_DEVNAMELEN];
        int bus;
        strlcpy(devpath, "/dev/", sizeof(devpath));
        strlcat(devpath, arr[i], sizeof(devpath));
        bus = open(devpath, O_RDONLY | O_CLOEXEC);
        if (bus == -1)
            continue;
        enumerate_usb_devices(bus, 0, hid_enumerate_callback, &hed);
        close(bus);
    }
    close(drvctl);
    return hed.root;
}
References hid_enumerate_data::drvctl, hid_enumerate_data::end, enumerate_usb_devices(), HID_API_CALL, HID_API_EXPORT, hid_enumerate_callback(), hid_init, HIDAPI_MAX_CHILD_DEVICES, is_usb_controller(), NULL, O_CLOEXEC, hid_enumerate_data::product_id, register_global_error_format(), hid_enumerate_data::root, hid_enumerate_data::vendor_id, and walk_device_tree().
PLATFORM_hid_error()
const wchar_t * PLATFORM_hid_error (PLATFORM_hid_device * dev)
< API call macro API export macro
References HID_API_CALL, HID_API_EXPORT, hid_device, last_global_error_str, and NULL.
PLATFORM_hid_exit()
int PLATFORM_hid_exit (void)
< API export macro < API call macro
{
    /* Free global error message */
    register_global_error(NULL);
    return 0;
}
References HID_API_CALL, HID_API_EXPORT, NULL, and register_global_error().
PLATFORM_hid_free_enumeration()
void PLATFORM_hid_free_enumeration (struct hid_device_info * devs)
< API export macro < API call macro API export macro
References free, HID_API_CALL, HID_API_EXPORT, hid_device_info::manufacturer_string, hid_device_info::next, hid_device_info::path, hid_device_info::product_string, and hid_device_info::serial_number.
PLATFORM_hid_get_device_info()
struct hid_device_info * PLATFORM_hid_get_device_info (PLATFORM_hid_device * dev)
< API export macro < API call macro
{
    int res;
    struct usb_device_info udi;
    struct usb_ctl_report_desc ucrd;
    int use_ucrd;
    struct hid_device_info *hdi;
    if (dev->device_info)
        return dev->device_info;
    res = ioctl(dev->device_handle, USB_GET_DEVICEINFO, &udi);
    if (res == -1) {
        register_device_error_format(dev, "ioctl (USB_GET_DEVICEINFO): %s", strerror(errno));
        return NULL;
    }
    use_ucrd = (ioctl(dev->device_handle, USB_GET_REPORT_DESC, &ucrd) != -1);
    hdi = create_device_info(&udi, dev->path, (use_ucrd) ? &ucrd : NULL);
    if (!hdi) {
        register_device_error(dev, "failed to create device info");
        return NULL;
    }
    dev->device_info = hdi;
    return hdi;
}
References create_device_info(), HID_API_CALL, HID_API_EXPORT, hid_device, NULL, register_device_error(), and register_device_error_format().
PLATFORM_hid_get_feature_report()
int PLATFORM_hid_get_feature_report (PLATFORM_hid_device * dev, unsigned char * data, size_t length)
< API export macro < API call macro
{
    return get_report(dev, data, length, UHID_FEATURE_REPORT);
}
References get_report(), HID_API_CALL, HID_API_EXPORT, and hid_device.
PLATFORM_hid_get_indexed_string()
int PLATFORM_hid_get_indexed_string (PLATFORM_hid_device * dev, int string_index, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro
{
    int res;
    struct usb_string_desc usd;
    usb_string_descriptor_t *str;
    iconv_t ic;
    char *src;
    size_t srcleft;
    char *dst;
    size_t dstleft;
    size_t ic_res;
    /* First let us get the supported language IDs. */
    usd.usd_string_index = 0;
    usd.usd_language_id = 0;
    res = ioctl(dev->device_handle, USB_GET_STRING_DESC, &usd);
    if (res == -1) {
        register_device_error_format(dev, "ioctl (USB_GET_STRING_DESC): %s", strerror(errno));
        return -1;
    }
    str = &usd.usd_desc;
    if (str->bLength < 4) {
        register_device_error(dev, "failed to get supported language IDs");
        return -1;
    }
    /* Now we can get the requested string. */
    usd.usd_string_index = string_index;
    usd.usd_language_id = UGETW(str->bString[0]);
    res = ioctl(dev->device_handle, USB_GET_STRING_DESC, &usd);
    if (res == -1) {
        register_device_error_format(dev, "ioctl (USB_GET_STRING_DESC): %s", strerror(errno));
        return -1;
    }
    /* Now we need to convert it, using iconv. */
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
    ic = iconv_open("utf-32le", "utf-16le");
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
    ic = iconv_open("utf-32be", "utf-16le");
#endif
    if (ic == (iconv_t) -1) {
        register_device_error_format(dev, "iconv_open failed: %s", strerror(errno));
        return -1;
    }
    src = (char *) str->bString;
    srcleft = str->bLength - 2;
    dst = (char *) string;
    dstleft = sizeof(wchar_t[maxlen]);
    ic_res = iconv(ic, &src, &srcleft, &dst, &dstleft);
    iconv_close(ic);
    if (ic_res == (size_t) -1) {
        register_device_error_format(dev, "iconv failed: %s", strerror(errno));
        return -1;
    }
    /* Write the terminating NULL. */
    string[maxlen - 1] = L'\0';
    if (dstleft >= sizeof(wchar_t))
        *((wchar_t *) dst) = L'\0';
    return 0;
}
References HID_API_EXPORT_CALL, hid_device, iconv, iconv_close, iconv_open, iconv_t, register_device_error(), and register_device_error_format().
PLATFORM_hid_get_input_report()
int PLATFORM_hid_get_input_report (PLATFORM_hid_device * dev, unsigned char * data, size_t length)
< API export macro < API call macro
{
    return get_report(dev, data, length, UHID_INPUT_REPORT);
}
References get_report(), HID_API_CALL, HID_API_EXPORT, and hid_device.
PLATFORM_hid_get_manufacturer_string()
int PLATFORM_hid_get_manufacturer_string (PLATFORM_hid_device * dev, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro
{
    struct hid_device_info *hdi;
    if (!string || !maxlen) {
        register_device_error(dev, "Zero buffer/length");
        return -1;
    }
    hdi = hid_get_device_info(dev);
    if (!dev)
        return -1;
    if (hdi->manufacturer_string) {
        wcsncpy(string, hdi->manufacturer_string, maxlen);
        string[maxlen - 1] = L'\0';
    } else {
        string[0] = L'\0';
    }
    return 0;
}
References HID_API_EXPORT_CALL, hid_device, hid_get_device_info, hid_device_info::manufacturer_string, register_device_error(), and wcsncpy.
PLATFORM_hid_get_product_string()
int PLATFORM_hid_get_product_string (PLATFORM_hid_device * dev, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro
{
    struct hid_device_info *hdi;
    if (!string || !maxlen) {
        register_device_error(dev, "Zero buffer/length");
        return -1;
    }
    hdi = hid_get_device_info(dev);
    if (!dev)
        return -1;
    if (hdi->product_string) {
        wcsncpy(string, hdi->product_string, maxlen);
        string[maxlen - 1] = L'\0';
    } else {
        string[0] = L'\0';
    }
    return 0;
}
References HID_API_EXPORT_CALL, hid_device, hid_get_device_info, hid_device_info::product_string, register_device_error(), and wcsncpy.
PLATFORM_hid_get_report_descriptor()
int PLATFORM_hid_get_report_descriptor (PLATFORM_hid_device * dev, unsigned char * buf, size_t buf_size)
< API export macro < API call macro < API export and call macro API export macro
References HID_API_EXPORT_CALL, hid_device, memcpy, and register_device_error_format().
PLATFORM_hid_get_serial_number_string()
int PLATFORM_hid_get_serial_number_string (PLATFORM_hid_device * dev, wchar_t * string, size_t maxlen)
< API export macro < API call macro < API export and call macro
{
    struct hid_device_info *hdi;
    if (!string || !maxlen) {
        register_device_error(dev, "Zero buffer/length");
        return -1;
    }
    hdi = hid_get_device_info(dev);
    if (!dev)
        return -1;
    if (hdi->serial_number) {
        wcsncpy(string, hdi->serial_number, maxlen);
        string[maxlen - 1] = L'\0';
    } else {
        string[0] = L'\0';
    }
    return 0;
}
References HID_API_EXPORT_CALL, hid_device, hid_get_device_info, register_device_error(), hid_device_info::serial_number, and wcsncpy.
PLATFORM_hid_init()
int PLATFORM_hid_init (void)
< API export macro < API call macro
{
    /* indicate no error */
    register_global_error(NULL);
    return 0;
}
References HID_API_CALL, HID_API_EXPORT, NULL, and register_global_error().
PLATFORM_hid_open()
PLATFORM_hid_device * PLATFORM_hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)
< API call macro API export macro
References HID_API_CALL, HID_API_EXPORT, hid_device, hid_enumerate, hid_free_enumeration, hid_open_path, hid_device_info::next, NULL, hid_device_info::path, hid_device_info::product_id, register_global_error(), hid_device_info::serial_number, hid_device_info::vendor_id, and wcscmp.
PLATFORM_hid_open_path()
PLATFORM_hid_device * PLATFORM_hid_open_path (const char * path)
< API call macro
{
    int res;
    hid_device *dev;
    int drvctl;
    char arr[HIDAPI_MAX_CHILD_DEVICES][USB_MAX_DEVNAMELEN];
    size_t len;
    res = hid_init();
    if (res == -1)
        goto err_0;
    dev = (hid_device *) calloc(1, sizeof(hid_device));
    if (!dev) {
        register_global_error("could not allocate hid_device");
        goto err_0;
    }
    drvctl = open(DRVCTLDEV, O_RDONLY | O_CLOEXEC);
    if (drvctl == -1) {
        register_global_error_format("failed to open drvctl: %s", strerror(errno));
        goto err_1;
    }
    if (!is_uhid_parent_device(path)) {
        register_global_error("not a uhidev device");
        goto err_2;
    }
    len = 0;
    walk_device_tree(drvctl, path, 0, arr, &len, is_uhid_device);
    dev->poll_handles_length = 0;
    memset(dev->poll_handles, 0x00, sizeof(dev->poll_handles));
    memset(dev->report_handles, 0xff, sizeof(dev->report_handles));
    for (size_t i = 0; i < len; i++) {
        const char *child_dev;
        char devpath[USB_MAX_DEVNAMELEN];
        int uhid;
        int rep_id;
        struct pollfd *ph;
        child_dev = arr[i];
        strlcpy(devpath, "/dev/", sizeof(devpath));
        strlcat(devpath, child_dev, sizeof(devpath));
        uhid = open(devpath, O_RDWR | O_CLOEXEC);
        if (uhid == -1) {
            register_global_error_format("failed to open %s: %s", child_dev, strerror(errno));
            goto err_3;
        }
        res = ioctl(uhid, USB_GET_REPORT_ID, &rep_id);
        if (res == -1) {
            close(uhid);
            register_global_error_format("failed to get report id %s: %s", child_dev, strerror(errno));
            goto err_3;
        }
        ph = &dev->poll_handles[dev->poll_handles_length++];
        ph->fd = uhid;
        ph->events = POLLIN;
        ph->revents = 0;
        dev->report_handles[rep_id] = uhid;
        dev->device_handle = uhid;
    }
    dev->blocking = 1;
    dev->last_error_str = NULL;
    dev->device_info = NULL;
    strlcpy(dev->path, path, sizeof(dev->path));
    register_global_error(NULL);
    return dev;
err_3:
    for (size_t i = 0; i < dev->poll_handles_length; i++)
        close(dev->poll_handles[i].fd);
err_2:
    close(drvctl);
err_1:
    free(dev);
err_0:
    return NULL;
}
References calloc, free, HID_API_CALL, HID_API_EXPORT, hid_device, hid_init, HIDAPI_MAX_CHILD_DEVICES, is_uhid_device(), is_uhid_parent_device(), memset(), NULL, O_CLOEXEC, hid_device_info::path, register_global_error(), register_global_error_format(), and walk_device_tree().
PLATFORM_hid_read()
int PLATFORM_hid_read (PLATFORM_hid_device * dev, unsigned char * data, size_t length)
< API export macro < API call macro
{
    return hid_read_timeout(dev, data, length, (dev->blocking) ? -1 : 0);
}
References HID_API_CALL, HID_API_EXPORT, hid_device, and hid_read_timeout.
PLATFORM_hid_read_timeout()
int PLATFORM_hid_read_timeout (PLATFORM_hid_device * dev, unsigned char * data, size_t length, int milliseconds)
< API export macro < API call macro
{
    int res;
    size_t i;
    struct pollfd *ph;
    ssize_t n;
    res = poll(dev->poll_handles, dev->poll_handles_length, milliseconds);
    if (res == -1) {
        register_device_error_format(dev, "error while polling: %s", strerror(errno));
        return -1;
    }
    if (res == 0)
        return 0;
    for (i = 0; i < dev->poll_handles_length; i++) {
        ph = &dev->poll_handles[i];
        if (ph->revents & (POLLERR | POLLHUP | POLLNVAL)) {
            register_device_error(dev, "device IO error while polling");
            return -1;
        }
        if (ph->revents & POLLIN)
            break;
    }
    if (i == dev->poll_handles_length)
        return 0;
    n = read(ph->fd, data, length);
    if (n == -1) {
        if (errno == EAGAIN || errno == EINPROGRESS)
            n = 0;
        else
            register_device_error_format(dev, "error while reading: %s", strerror(errno));
    }
    return n;
}
References HID_API_CALL, HID_API_EXPORT, hid_device, register_device_error(), and register_device_error_format().
PLATFORM_hid_send_feature_report()
int PLATFORM_hid_send_feature_report (PLATFORM_hid_device * dev, const unsigned char * data, size_t length)
< API export macro < API call macro
{
    return set_report(dev, data, length, UHID_FEATURE_REPORT);
}
References HID_API_CALL, HID_API_EXPORT, hid_device, and set_report().
PLATFORM_hid_set_nonblocking()
int PLATFORM_hid_set_nonblocking (PLATFORM_hid_device * dev, int nonblock)
< API export macro < API call macro
{
    dev->blocking = !nonblock;
    return 0;
}
References HID_API_CALL, HID_API_EXPORT, and hid_device.
PLATFORM_hid_version()
const struct hid_api_version * PLATFORM_hid_version (void)
< API call macro API export macro
References api_version, HID_API_CALL, HID_API_EXPORT, HID_API_VERSION_MAJOR, HID_API_VERSION_MINOR, and HID_API_VERSION_PATCH.
PLATFORM_hid_version_str()
const char * PLATFORM_hid_version_str (void)
< API call macro
{
    return HID_API_VERSION_STR;
}
References HID_API_CALL, HID_API_EXPORT, and HID_API_VERSION_STR.
PLATFORM_hid_write()
int PLATFORM_hid_write (PLATFORM_hid_device * dev, const unsigned char * data, size_t length)
< API export macro < API call macro
{
    return set_report(dev, data, length, UHID_OUTPUT_REPORT);
}
References HID_API_CALL, HID_API_EXPORT, hid_device, and set_report().
register_device_error()
void register_device_error (PLATFORM_hid_device * dev, const char * msg) static
{
    register_error_str(&dev->last_error_str, msg);
}
References hid_device, and register_error_str().
register_device_error_format()
void register_device_error_format (PLATFORM_hid_device * dev, const char * format, ...) static
{
    va_list args;
    va_start(args, format);
    register_error_str_vformat(&dev->last_error_str, format, args);
    va_end(args);
}
References hid_device, and register_error_str_vformat().
register_error_str()
void register_error_str (wchar_t ** error_str, const char * msg) static
{
    free(*error_str);
    *error_str = utf8_to_wchar_t(msg);
}
References free, and utf8_to_wchar_t().
register_error_str_vformat()
void register_error_str_vformat (wchar_t ** error_str, const char * format, va_list args) static
{
    char msg[256];
    vsnprintf(msg, sizeof(msg), format, args);
    register_error_str(error_str, msg);
}
References register_error_str().
register_global_error()
void register_global_error (const char * msg) static
{
    register_error_str(&last_global_error_str, msg);
}
References last_global_error_str, and register_error_str().
register_global_error_format()
void register_global_error_format (const char * format, ...) static
{
    va_list args;
    va_start(args, format);
    register_error_str_vformat(&last_global_error_str, format, args);
    va_end(args);
}
References last_global_error_str, and register_error_str_vformat().
set_report()
int set_report (PLATFORM_hid_device * dev, const uint8_t * data, size_t length, int report) static
{
    int res;
    int device_handle;
    struct usb_ctl_report ucr;
    if (length < 1) {
        register_device_error(dev, "report must be greater than 1 byte");
        return -1;
    }
    device_handle = dev->report_handles[*data];
    if (device_handle < 0) {
        register_device_error_format(dev, "unsupported report id: %hhu", *data);
        return -1;
    }
    length--;
    data++;
    if (length > sizeof(ucr.ucr_data)) {
        register_device_error_format(dev, "report must be less than or equal to %zu bytes", sizeof(ucr.ucr_data));
        return -1;
    }
    ucr.ucr_report = report;
    memcpy(ucr.ucr_data, data, length);
    res = ioctl(device_handle, USB_SET_REPORT, &ucr);
    if (res == -1) {
        register_device_error_format(dev, "ioctl (USB_SET_REPORT): %s", strerror(errno));
        return -1;
    }
    return (int) (length + 1);
}
References hid_device, memcpy, register_device_error(), and register_device_error_format().
utf8_to_wchar_t()
wchar_t * utf8_to_wchar_t (const char * utf8) static
{
    wchar_t *ret = NULL;
    if (utf8) {
        size_t wlen = mbstowcs(NULL, utf8, 0);
        if ((size_t) -1 == wlen) {
            return wcsdup(L"");
        }
        ret = (wchar_t*) calloc(wlen+1, sizeof(wchar_t));
        if (ret == NULL) {
            /* as much as we can do at this point */
            return NULL;
        }
        mbstowcs(ret, utf8, wlen+1);
        ret[wlen] = 0x0000;
    }
    return ret;
}
References calloc, NULL, and wcsdup.
walk_device_tree()
void walk_device_tree (int drvctl, const char * dev, int depth, char arr[static 256][USB_MAX_DEVNAMELEN], size_t * len, int(* cmp)(const char *)) static
{
    int res;
    char childname[HIDAPI_MAX_CHILD_DEVICES][USB_MAX_DEVNAMELEN];
    struct devlistargs dla;
    if (depth && (!dev || !*dev))
        return;
    if (cmp(dev) && *len < HIDAPI_MAX_CHILD_DEVICES)
        strlcpy(arr[(*len)++], dev, sizeof(*arr));
    strlcpy(dla.l_devname, dev, sizeof(dla.l_devname));
    dla.l_childname = childname;
    dla.l_children = HIDAPI_MAX_CHILD_DEVICES;
    res = ioctl(drvctl, DRVLISTDEV, &dla);
    if (res == -1)
        return;
    /*
     * DO NOT CHANGE THIS. This is a fail-safe check
     * for the unlikely event that a parent device has
     * more than HIDAPI_MAX_CHILD_DEVICES child devices
     * to prevent iterating over uninitialized data.
     */
    if (dla.l_children > HIDAPI_MAX_CHILD_DEVICES)
        return;
    for (size_t i = 0; i < dla.l_children; i++)
        walk_device_tree(drvctl, dla.l_childname[i], depth + 1, arr, len, cmp);
}
References HIDAPI_MAX_CHILD_DEVICES, and walk_device_tree().
Referenced by hid_enumerate_callback(), PLATFORM_hid_enumerate(), PLATFORM_hid_open_path(), and walk_device_tree().
Variable Documentation
last_global_error_str
wchar_t* last_global_error_str = NULL static