SDL3: SDL-main/src/thread/pthread/SDL_systls.c File Reference
SDL_systls.c File Reference
#include "SDL_internal.h"
#include "../SDL_systhread.h"
#include "../SDL_thread_c.h"
#include <pthread.h>
Macros
#define INVALID_PTHREAD_KEY ((pthread_key_t)-1)
Functions
SDL_TLSData * SDL_SYS_GetTLSData (void)
void SDL_SYS_InitTLSData (void)
void SDL_SYS_QuitTLSData (void)
bool SDL_SYS_SetTLSData (SDL_TLSData *data)
Variables
static bool generic_local_storage = false
static pthread_key_t thread_local_storage = ((pthread_key_t)-1)
Macro Definition Documentation
INVALID_PTHREAD_KEY
#define INVALID_PTHREAD_KEY ((pthread_key_t)-1)
Referenced by SDL_SYS_GetTLSData(), SDL_SYS_InitTLSData(), and SDL_SYS_QuitTLSData().
Function Documentation
SDL_SYS_GetTLSData()
SDL_TLSData * SDL_SYS_GetTLSData (void)
{
    if (generic_local_storage) {
        return SDL_Generic_GetTLSData();
    }
    if (thread_local_storage != INVALID_PTHREAD_KEY) {
        return (SDL_TLSData *)pthread_getspecific(thread_local_storage);
    }
    return NULL;
}
References generic_local_storage, INVALID_PTHREAD_KEY, NULL, SDL_Generic_GetTLSData(), and thread_local_storage.
SDL_SYS_InitTLSData()
void SDL_SYS_InitTLSData (void)
{
    if (thread_local_storage == INVALID_PTHREAD_KEY && !generic_local_storage) {
        if (pthread_key_create(&thread_local_storage, NULL) != 0) {
            thread_local_storage = INVALID_PTHREAD_KEY;
            SDL_Generic_InitTLSData();
            generic_local_storage = true;
        }
    }
}
References generic_local_storage, INVALID_PTHREAD_KEY, NULL, SDL_Generic_InitTLSData(), and thread_local_storage.
SDL_SYS_QuitTLSData()
void SDL_SYS_QuitTLSData (void)
{
    if (generic_local_storage) {
        SDL_Generic_QuitTLSData();
        generic_local_storage = false;
    } else {
        if (thread_local_storage != INVALID_PTHREAD_KEY) {
            pthread_key_delete(thread_local_storage);
            thread_local_storage = INVALID_PTHREAD_KEY;
        }
    }
}
References generic_local_storage, INVALID_PTHREAD_KEY, SDL_Generic_QuitTLSData(), and thread_local_storage.
SDL_SYS_SetTLSData()
bool SDL_SYS_SetTLSData (SDL_TLSData * data)
{
    if (generic_local_storage) {
        return SDL_Generic_SetTLSData(data);
    }
    if (pthread_setspecific(thread_local_storage, data) != 0) {
        return SDL_SetError("pthread_setspecific() failed");
    }
    return true;
}
References generic_local_storage, SDL_Generic_SetTLSData(), SDL_SetError(), and thread_local_storage.
Variable Documentation
generic_local_storage
bool generic_local_storage = false static
Referenced by SDL_SYS_GetTLSData(), SDL_SYS_InitTLSData(), SDL_SYS_QuitTLSData(), and SDL_SYS_SetTLSData().
thread_local_storage
pthread_key_t thread_local_storage = ((pthread_key_t)-1) static
Referenced by SDL_SYS_GetTLSData(), SDL_SYS_InitTLSData(), SDL_SYS_QuitTLSData(), and SDL_SYS_SetTLSData().