SDL3: SDL-main/src/render/opengl/SDL_glfuncs.h File Reference
SDL_glfuncs.h File Reference
Macros
#define SDL_PROC_UNUSED(ret, func, params)
Functions
SDL_PROC (void, glColor4ub,(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)) SDL_PROC(void
GLint GLenum GLsizei const GLvoid *pointer SDL_PROC (void, glDrawPixels,(GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)) SDL_PROC(void
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar SDL_PROC (void, glReadPixels,(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)) SDL_PROC(void
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 SDL_PROC (void, glRotatef,(GLfloat angle, GLfloat x, GLfloat y, GLfloat z)) SDL_PROC(void
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer SDL_PROC (void, glTexImage2D,(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)) SDL_PROC(void
Variables
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble bottom
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei GLsizei GLenum format
glColorPointer
GLint GLenum GLsizei const GLvoid *pointer glOrtho
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar glRectf
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 glTexCoordPointer
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer glTexSubImage2D
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei GLsizei height
GLint GLenum GLsizei const GLvoid *pointer GLdouble left
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint level
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble right
GLint size
GLint GLenum GLsizei stride
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum target
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble top
GLint GLenum type
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei width
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat x1
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat x2
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint xoffset
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat y1
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint yoffset
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble zNear
Macro Definition Documentation
SDL_PROC_UNUSED
#define SDL_PROC_UNUSED (ret, func, params)
Function Documentation
SDL_PROC() [1/5]
SDL_PROC (void , glColor4ub , (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
References glColor4ub(), glColor4ubv(), glColor4ui(), glColor4uiv(), glColor4us(), glColor4usv(), glColorMask(), glColorMaterial(), SDL_PROC(), and SDL_PROC_UNUSED.
Referenced by SDL_PROC(), SDL_PROC(), SDL_PROC(), SDL_PROC(), and SDL_PROC().
SDL_PROC() [2/5]
GLint GLenum GLsizei const GLvoid *pointer SDL_PROC (void , glDrawPixels , (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels))
References bottom, flag, glDrawPixels(), glEdgeFlag(), glEdgeFlagPointer(), glEdgeFlagv(), glEnable(), glEnableClientState(), glEnd(), glEndList(), glEvalCoord1d(), glEvalCoord1dv(), glEvalCoord1f(), glEvalCoord1fv(), glEvalCoord2d(), glEvalCoord2dv(), glEvalCoord2f(), glEvalCoord2fv(), glEvalMesh1(), glEvalMesh2(), glEvalPoint1(), glEvalPoint2(), glFeedbackBuffer(), glFinish(), glFlush(), glFogf(), glFogfv(), glFogi(), glFogiv(), glFrontFace(), glFrustum(), glGenLists(), glGenTextures(), glGetBooleanv(), glGetClipPlane(), glGetDoublev(), glGetError(), glGetFloatv(), glGetIntegerv(), glGetLightfv(), glGetLightiv(), glGetMapdv(), glGetMapfv(), glGetMapiv(), glGetMaterialfv(), glGetMaterialiv(), glGetPixelMapfv(), glGetPixelMapuiv(), glGetPixelMapusv(), glGetPointerv(), glGetPolygonStipple(), glGetString(), glGetTexEnvfv(), glGetTexEnviv(), glGetTexGendv(), glGetTexGenfv(), glGetTexGeniv(), glGetTexImage(), glGetTexLevelParameterfv(), glGetTexLevelParameteriv(), glGetTexParameterfv(), glGetTexParameteriv(), glHint(), glIndexd(), glIndexdv(), glIndexf(), glIndexfv(), glIndexi(), glIndexiv(), glIndexMask(), glIndexPointer(), glIndexs(), glIndexsv(), glIndexub(), glIndexubv(), glInitNames(), glInterleavedArrays(), glIsEnabled(), glIsList(), glIsTexture(), glLightf(), glLightfv(), glLighti(), glLightiv(), glLightModelf(), glLightModelfv(), glLightModeli(), glLightModeliv(), glLineStipple(), glLineWidth(), glListBase(), glLoadIdentity(), glLoadMatrixd(), glLoadMatrixf(), glLoadName(), glLogicOp(), glMap1d(), glMap1f(), glMap2d(), glMap2f(), glMapGrid1d(), glMapGrid1f(), glMapGrid2d(), glMapGrid2f(), glMaterialf(), glMaterialfv(), glMateriali(), glMaterialiv(), glMatrixMode(), glMultMatrixd(), glMultMatrixf(), glNewList(), glNormal3b(), glNormal3bv(), glNormal3d(), glNormal3dv(), glNormal3f(), glNormal3fv(), glNormal3i(), glNormal3iv(), glNormal3s(), glNormal3sv(), glNormalPointer(), left, level, right, SDL_PROC(), SDL_PROC_UNUSED, top, and zNear.
SDL_PROC() [3/5]
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar SDL_PROC (void , glReadPixels , (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels))
References glReadPixels(), glRectd(), glRectdv(), SDL_PROC(), SDL_PROC_UNUSED, x1, x2, and y1.
SDL_PROC() [4/5]
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 SDL_PROC (void , glRotatef , (GLfloat angle, GLfloat x, GLfloat y, GLfloat z))
References glRotatef(), glScaled(), glScalef(), glScissor(), glSelectBuffer(), glShadeModel(), glStencilFunc(), glStencilMask(), glStencilOp(), glTexCoord1d(), glTexCoord1dv(), glTexCoord1f(), glTexCoord1fv(), glTexCoord1i(), glTexCoord1iv(), glTexCoord1s(), glTexCoord1sv(), glTexCoord2d(), glTexCoord2dv(), glTexCoord2f(), glTexCoord2fv(), glTexCoord2i(), glTexCoord2iv(), glTexCoord2s(), glTexCoord2sv(), glTexCoord3d(), glTexCoord3dv(), glTexCoord3f(), glTexCoord3fv(), glTexCoord3i(), glTexCoord3iv(), glTexCoord3s(), glTexCoord3sv(), glTexCoord4d(), glTexCoord4dv(), glTexCoord4f(), glTexCoord4fv(), glTexCoord4i(), glTexCoord4iv(), glTexCoord4s(), glTexCoord4sv(), SDL_PROC(), and SDL_PROC_UNUSED.
SDL_PROC() [5/5]
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer SDL_PROC (void , glTexImage2D , (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels))
References glTexImage2D(), glTexParameterf(), glTexParameterfv(), glTexParameteri(), glTexParameteriv(), glTexSubImage1D(), level, SDL_PROC(), SDL_PROC_UNUSED, and xoffset.
Variable Documentation
bottom
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble bottom
Referenced by Android_SetWindowSafeAreaInsets(), glFrustum(), glOrtho(), glPopName(), init_orthographic_matrix(), SDL_GetClosestPointOnRect(), SDL_GetWindowBordersSize(), SDL_PROC(), SDL_SetWindowSafeAreaInsets(), WIN_GetWindowBordersSize(), and X11_GetWindowBordersSize().
format
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei GLsizei GLenum format
glColorPointer
glColorPointer
glOrtho
GLint GLenum GLsizei const GLvoid *pointer glOrtho
glRectf
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar glRectf
glTexCoordPointer
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 glTexCoordPointer
glTexSubImage2D
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer glTexSubImage2D
height
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei GLsizei height
left
GLint GLenum GLsizei const GLvoid *pointer GLdouble left
Referenced by Android_SetWindowSafeAreaInsets(), glFrustum(), glOrtho(), glPopName(), init_orthographic_matrix(), SDL_GetWindowBordersSize(), SDL_iconv(), SDL_memcpy(), SDL_memset(), SDL_murmur3_32(), SDL_PROC(), SDL_SetWindowSafeAreaInsets(), WIN_GetWindowBordersSize(), and X11_GetWindowBordersSize().
level
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint level
Referenced by glBindImageTexture(), glCompressedTexImage1D(), glCompressedTexImage2D(), glCompressedTexImage2D(), glCompressedTexImage3D(), glCompressedTexImage3D(), glCompressedTexSubImage1D(), glCompressedTexSubImage2D(), glCompressedTexSubImage2D(), glCompressedTexSubImage3D(), glCompressedTexSubImage3D(), glCopyTexImage1D(), glCopyTexImage2D(), glCopyTexSubImage1D(), glCopyTexSubImage2D(), glCopyTexSubImage3D(), glFramebufferTexture(), glFramebufferTexture2D(), glFramebufferTextureLayer(), glGetTexImage(), glGetTexLevelParameterfv(), glGetTexLevelParameteriv(), glPopName(), glSampleCoverage(), glTexImage1D(), glTexImage2D(), glTexImage2D(), glTexImage3D(), glTexImage3D(), glTexSubImage1D(), glTexSubImage2D(), glTexSubImage2D(), glTexSubImage3D(), glTexSubImage3D(), SDL_PROC(), and SDL_PROC().
right
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble right
Referenced by Android_SetWindowSafeAreaInsets(), glFrustum(), glOrtho(), glPopName(), init_orthographic_matrix(), SDL_GetClosestPointOnRect(), SDL_GetWindowBordersSize(), SDL_PROC(), SDL_RenderTextureAffine(), SDL_SetWindowSafeAreaInsets(), WIN_GetWindowBordersSize(), and X11_GetWindowBordersSize().
size
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint size
stride
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei stride
target
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum target
top
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble top
Referenced by Android_SetWindowSafeAreaInsets(), glFrustum(), glOrtho(), glPopName(), init_orthographic_matrix(), SDL_GetWindowBordersSize(), SDL_LoadBMP_IO(), SDL_PROC(), SDL_SetWindowSafeAreaInsets(), WIN_GetWindowBordersSize(), and X11_GetWindowBordersSize().
type
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei GLsizei GLenum GLenum type
width
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei width
x1
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat x1
Referenced by glPopName(), glRectd(), glRectf(), glRecti(), glRects(), RenderLineBresenham(), SDL_BlendLine(), SDL_DrawLine(), SDL_INTERSECTRECTANDLINE(), SDL_PROC(), and SDL_RenderLine().
x2
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat x2
Referenced by glPopName(), glRectd(), glRectf(), glRecti(), glRects(), RenderLineBresenham(), SDL_BlendLine(), SDL_DrawLine(), SDL_INTERSECTRECTANDLINE(), SDL_PROC(), and SDL_RenderLine().
xoffset
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint xoffset
Referenced by glCompressedTexSubImage1D(), glCompressedTexSubImage2D(), glCompressedTexSubImage2D(), glCompressedTexSubImage3D(), glCompressedTexSubImage3D(), glCopyTexSubImage1D(), glCopyTexSubImage2D(), glCopyTexSubImage3D(), glPopName(), glSampleCoverage(), glTexSubImage1D(), glTexSubImage2D(), glTexSubImage2D(), glTexSubImage3D(), glTexSubImage3D(), SDL_PROC(), and SDL_ShowAndroidToast().
y1
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat y1
Referenced by CubicLeastSquares(), glPopName(), glRectd(), glRectf(), glRecti(), glRects(), RenderLineBresenham(), SDL_BlendLine(), SDL_DrawLine(), SDL_INTERSECTRECTANDLINE(), SDL_PROC(), SDL_RenderLine(), and SDL_uclibc_pow().
yoffset
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint yoffset
Referenced by glCompressedTexSubImage2D(), glCompressedTexSubImage2D(), glCompressedTexSubImage3D(), glCompressedTexSubImage3D(), glCopyTexSubImage2D(), glCopyTexSubImage3D(), glPopName(), glSampleCoverage(), glTexSubImage2D(), glTexSubImage2D(), glTexSubImage3D(), glTexSubImage3D(), and SDL_ShowAndroidToast().
zNear
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble zNear
Referenced by SDL_PROC().