SDL3: SDL-main/src/io/SDL_sysasyncio.h File Reference
SDL_sysasyncio.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_AsyncIO
struct SDL_AsyncIOInterface
struct SDL_AsyncIOQueue
struct SDL_AsyncIOQueueInterface
struct SDL_AsyncIOTask
Macros
#define LINKED_LIST_DECLARE_FIELDS(type, prefix)
#define LINKED_LIST_NEXT(item, prefix)
#define LINKED_LIST_PREPEND(item, list, prefix)
#define LINKED_LIST_PREV(item, prefix)
#define LINKED_LIST_START(list, prefix)
#define LINKED_LIST_UNLINK(item, prefix)
#define SDL_ASYNCIO_ONLY_HAVE_GENERIC 1
Typedefs
typedef struct SDL_AsyncIOInterface SDL_AsyncIOInterface
typedef struct SDL_AsyncIOQueueInterface SDL_AsyncIOQueueInterface
typedef struct SDL_AsyncIOTask SDL_AsyncIOTask
Functions
bool SDL_SYS_AsyncIOFromFile (const char *file, const char *mode, SDL_AsyncIO *asyncio)
bool SDL_SYS_AsyncIOFromFile_Generic (const char *file, const char *mode, SDL_AsyncIO *asyncio)
bool SDL_SYS_CreateAsyncIOQueue (SDL_AsyncIOQueue *queue)
bool SDL_SYS_CreateAsyncIOQueue_Generic (SDL_AsyncIOQueue *queue)
void SDL_SYS_QuitAsyncIO (void)
void SDL_SYS_QuitAsyncIO_Generic (void)
Macro Definition Documentation
LINKED_LIST_DECLARE_FIELDS
#define LINKED_LIST_DECLARE_FIELDS (type, prefix)
Value:
    type *prefix##prev; \
    type *prefix##next
#define LINKED_LIST_DECLARE_FIELDS(type, prefix) \
    type *prefix##prev; \
    type *prefix##next
LINKED_LIST_NEXT
#define LINKED_LIST_NEXT (item, prefix)
Value:
(item->prefix##next)
LINKED_LIST_PREPEND
#define LINKED_LIST_PREPEND (item, list, prefix)
Value:
    do { \
    item->prefix##prev = &list; \
    item->prefix##next = list.prefix##next; \
    if (item->prefix##next) { \
        item->prefix##next->prefix##prev = item; \
    } \
    list.prefix##next = item; \
} while (false)
#define LINKED_LIST_PREPEND(item, list, prefix) do { \
    item->prefix##prev = &list; \
    item->prefix##next = list.prefix##next; \
    if (item->prefix##next) { \
        item->prefix##next->prefix##prev = item; \
    } \
    list.prefix##next = item; \
} while (false)
Referenced by AsyncIOTaskComplete(), GetAsyncIOTaskOutcome(), QueueAsyncIOTask(), RequestAsyncIO(), and SDL_CloseAsyncIO().
LINKED_LIST_PREV
#define LINKED_LIST_PREV (item, prefix)
Value:
(item->prefix##prev)
Referenced by generic_asyncioqueue_cancel_task().
LINKED_LIST_START
#define LINKED_LIST_START (list, prefix)
Value:
(list.prefix##next)
Referenced by AsyncIOThreadpoolWorker(), generic_asyncioqueue_get_results(), generic_asyncioqueue_wait_results(), GetAsyncIOTaskOutcome(), SDL_CloseAsyncIO(), and ShutdownThreadpool().
LINKED_LIST_UNLINK
#define LINKED_LIST_UNLINK (item, prefix)
Value:
    do { \
    if (item->prefix##next) { \
        item->prefix##next->prefix##prev = item->prefix##prev; \
    } \
    item->prefix##prev->prefix##next = task->prefix##next; \
    item->prefix##prev = item->prefix##next = NULL; \
} while (false)
#define LINKED_LIST_UNLINK(item, prefix) do { \
    if (item->prefix##next) { \
        item->prefix##next->prefix##prev = item->prefix##prev; \
    } \
    item->prefix##prev->prefix##next = task->prefix##next; \
    item->prefix##prev = item->prefix##next = NULL; \
} while (false)
Referenced by AsyncIOThreadpoolWorker(), generic_asyncioqueue_cancel_task(), generic_asyncioqueue_get_results(), generic_asyncioqueue_wait_results(), GetAsyncIOTaskOutcome(), RequestAsyncIO(), SDL_CloseAsyncIO(), and ShutdownThreadpool().
SDL_ASYNCIO_ONLY_HAVE_GENERIC
#define SDL_ASYNCIO_ONLY_HAVE_GENERIC 1
Typedef Documentation
SDL_AsyncIOInterface
typedef struct SDL_AsyncIOInterface SDL_AsyncIOInterface
SDL_AsyncIOQueueInterface
typedef struct SDL_AsyncIOQueueInterface SDL_AsyncIOQueueInterface
SDL_AsyncIOTask
typedef struct SDL_AsyncIOTask SDL_AsyncIOTask
Function Documentation
SDL_SYS_AsyncIOFromFile()
bool SDL_SYS_AsyncIOFromFile (const char * file, const char * mode, SDL_AsyncIO * asyncio) extern
{
    return SDL_SYS_AsyncIOFromFile_Generic(file, mode, asyncio);
}
References SDL_SYS_AsyncIOFromFile_Generic().
Referenced by SDL_AsyncIOFromFile().
SDL_SYS_AsyncIOFromFile_Generic()
bool SDL_SYS_AsyncIOFromFile_Generic (const char * file, const char * mode, SDL_AsyncIO * asyncio) extern
{
    #if SDL_ASYNCIO_USE_THREADPOOL
    if (!PrepareThreadpool()) {
        return false;
    }
    #endif
    GenericAsyncIOData *data = (GenericAsyncIOData *) SDL_calloc(1, sizeof (*data));
    if (!data) {
        return false;
    }
    data->lock = SDL_CreateMutex();
    if (!data->lock) {
        SDL_free(data);
        return false;
    }
    data->io = SDL_IOFromFile(file, mode);
    if (!data->io) {
        SDL_DestroyMutex(data->lock);
        SDL_free(data);
        return false;
    }
    static const SDL_AsyncIOInterface SDL_AsyncIOFile_Generic = {
        generic_asyncio_size,
        generic_asyncio_io,
        generic_asyncio_io,
        generic_asyncio_io,
        generic_asyncio_destroy
    };
    SDL_copyp(&asyncio->iface, &SDL_AsyncIOFile_Generic);
    asyncio->userdata = data;
    return true;
}
References generic_asyncio_destroy(), generic_asyncio_io(), generic_asyncio_size(), SDL_AsyncIO::iface, PrepareThreadpool(), SDL_calloc(), SDL_copyp, SDL_CreateMutex(), SDL_DestroyMutex(), SDL_free(), SDL_IOFromFile(), and SDL_AsyncIO::userdata.
Referenced by SDL_SYS_AsyncIOFromFile().
SDL_SYS_CreateAsyncIOQueue()
bool SDL_SYS_CreateAsyncIOQueue (SDL_AsyncIOQueue * queue) extern
{
    return SDL_SYS_CreateAsyncIOQueue_Generic(queue);
}
References SDL_SYS_CreateAsyncIOQueue_Generic().
Referenced by SDL_CreateAsyncIOQueue().
SDL_SYS_CreateAsyncIOQueue_Generic()
bool SDL_SYS_CreateAsyncIOQueue_Generic (SDL_AsyncIOQueue * queue) extern
{
    #if SDL_ASYNCIO_USE_THREADPOOL
    if (!PrepareThreadpool()) {
        return false;
    }
    #endif
    GenericAsyncIOQueueData *data = (GenericAsyncIOQueueData *) SDL_calloc(1, sizeof (*data));
    if (!data) {
        return false;
    }
    data->lock = SDL_CreateMutex();
    if (!data->lock) {
        SDL_free(data);
        return false;
    }
    data->condition = SDL_CreateCondition();
    if (!data->condition) {
        SDL_DestroyMutex(data->lock);
        SDL_free(data);
        return false;
    }
    static const SDL_AsyncIOQueueInterface SDL_AsyncIOQueue_Generic = {
        generic_asyncioqueue_queue_task,
        generic_asyncioqueue_cancel_task,
        generic_asyncioqueue_get_results,
        generic_asyncioqueue_wait_results,
        generic_asyncioqueue_signal,
        generic_asyncioqueue_destroy
    };
    SDL_copyp(&queue->iface, &SDL_AsyncIOQueue_Generic);
    queue->userdata = data;
    return true;
}
References generic_asyncioqueue_cancel_task(), generic_asyncioqueue_destroy(), generic_asyncioqueue_get_results(), generic_asyncioqueue_queue_task(), generic_asyncioqueue_signal(), generic_asyncioqueue_wait_results(), SDL_AsyncIOQueue::iface, PrepareThreadpool(), SDL_calloc(), SDL_copyp, SDL_CreateCondition(), SDL_CreateMutex(), SDL_DestroyMutex(), SDL_free(), and SDL_AsyncIOQueue::userdata.
Referenced by SDL_SYS_CreateAsyncIOQueue().
SDL_SYS_QuitAsyncIO()
void SDL_SYS_QuitAsyncIO (void) extern
{
    SDL_SYS_QuitAsyncIO_Generic();
}
References SDL_SYS_QuitAsyncIO_Generic().
Referenced by SDL_QuitAsyncIO().
SDL_SYS_QuitAsyncIO_Generic()
void SDL_SYS_QuitAsyncIO_Generic (void) extern
{
    #if SDL_ASYNCIO_USE_THREADPOOL
    ShutdownThreadpool();
    #endif
}
References ShutdownThreadpool().
Referenced by SDL_SYS_QuitAsyncIO().