SDL3: SDL3Cocoa_WindowListener Class Reference
SDL3Cocoa_WindowListener Class Reference
#include <SDL_cocoawindow.h>
Inherits NSResponder, and <NSWindowDelegate>.
Instance Methods
(void) - addPendingWindowOperation:
(void) - clearFocusClickPending:
(void) - close
(void) - handleTouches:withEvent:
(BOOL) - isInFullscreenSpace
(BOOL) - isInFullscreenSpaceTransition
(BOOL) - isMoving
(BOOL) - isMovingOrFocusClickPending
(BOOL) - isTouchFromTrackpad:
(void) - listen:
(void) - mouseDown:
(void) - mouseDragged:
(void) - mouseMoved:
(void) - mouseUp:
(void) - onMovingOrFocusClickPendingStateCleared
(void) - otherMouseDown:
(void) - otherMouseDragged:
(void) - otherMouseUp:
(void) - pauseVisibleObservation
(BOOL) - processHitTest:
(void) - resumeVisibleObservation
(void) - rightMouseDown:
(void) - rightMouseDragged:
(void) - rightMouseUp:
(void) - scrollWheel:
(void) - setFocusClickPending:
(BOOL) - setFullscreenSpace:
(void) - setPendingMoveX:Y:
(void) - tabletPoint:
(void) - tabletProximity:
(void) - touchesBeganWithEvent:
(void) - touchesCancelledWithEvent:
(void) - touchesEndedWithEvent:
(void) - touchesMovedWithEvent:
(void) - updateHitTest
(void) - updateIgnoreMouseState:
(NSApplicationPresentationOptions) - window:willUseFullScreenPresentationOptions:
(void) - windowDidBecomeKey:
(void) - windowDidChangeBackingProperties:
(void) - windowDidChangeOcclusionState:
(void) - windowDidChangeScreen:
(void) - windowDidChangeScreenProfile:
(void) - windowDidDeminiaturize:
(void) - windowDidEndLiveResize:
(void) - windowDidEnterFullScreen:
(void) - windowDidExitFullScreen:
(void) - windowDidExpose:
(void) - windowDidFinishMoving
(void) - windowDidMiniaturize:
(void) - windowDidMove:
(void) - windowDidResignKey:
(void) - windowDidResize:
(BOOL) - windowShouldClose:
(void) - windowWillEnterFullScreen:
(void) - windowWillExitFullScreen:
(void) - windowWillStartLiveResize:
Protected Attributes
__weak SDL_CocoaWindowData * _data
NSInteger focusClickPending
BOOL inFullscreenTransition
BOOL isDragAreaRunning
BOOL isFullscreenSpace
BOOL isMiniaturizing
BOOL isMoving
NSTimer * liveResizeTimer
BOOL observingVisible
PendingWindowOperation pendingWindowOperation
float pendingWindowWarpX
float pendingWindowWarpY
BOOL wasCtrlLeft
BOOL wasVisible
Method Documentation
addPendingWindowOperation:
- (void) addPendingWindowOperation: (PendingWindowOperation) operation
References close, and void().
clearFocusClickPending:
- (void) clearFocusClickPending: (NSInteger) button
References void().
close
- (void) close
References isMoving.
Referenced by addPendingWindowOperation:.
handleTouches:withEvent:
- (void) handleTouches: (NSTouchPhase) phase withEvent: (NSEvent *) theEvent
References void().
isInFullscreenSpace
- (BOOL) isInFullscreenSpace
References isInFullscreenSpaceTransition.
Referenced by setFullscreenSpace:.
isInFullscreenSpaceTransition
- (BOOL) isInFullscreenSpaceTransition
References void().
Referenced by isInFullscreenSpace.
isMoving
- (BOOL) isMoving
References isMovingOrFocusClickPending.
isMovingOrFocusClickPending
- (BOOL) isMovingOrFocusClickPending
References void().
Referenced by isMoving.
isTouchFromTrackpad:
- (BOOL) isTouchFromTrackpad: (NSEvent *) theEvent
References void().
listen:
- (void) listen: (SDL_CocoaWindowData *) data
References pauseVisibleObservation, and void().
mouseDown:
- (void) mouseDown: (NSEvent *) theEvent
References void().
mouseDragged:
- (void) mouseDragged: (NSEvent *) theEvent
References void().
mouseMoved:
- (void) mouseMoved: (NSEvent *) theEvent
References void().
mouseUp:
- (void) mouseUp: (NSEvent *) theEvent
References void().
onMovingOrFocusClickPendingStateCleared
- (void) onMovingOrFocusClickPendingStateCleared
Referenced by windowDidFinishMoving.
otherMouseDown:
- (void) otherMouseDown: (NSEvent *) theEvent
References void().
otherMouseDragged:
- (void) otherMouseDragged: (NSEvent *) theEvent
References void().
otherMouseUp:
- (void) otherMouseUp: (NSEvent *) theEvent
References void().
pauseVisibleObservation
- (void) pauseVisibleObservation
References resumeVisibleObservation, and void().
Referenced by listen:.
processHitTest:
- (BOOL) processHitTest: (NSEvent *) theEvent
References void().
resumeVisibleObservation
- (void) resumeVisibleObservation
Referenced by pauseVisibleObservation.
rightMouseDown:
- (void) rightMouseDown: (NSEvent *) theEvent
References void().
rightMouseDragged:
- (void) rightMouseDragged: (NSEvent *) theEvent
References void().
rightMouseUp:
- (void) rightMouseUp: (NSEvent *) theEvent
References void().
scrollWheel:
- (void) scrollWheel: (NSEvent *) theEvent
References void().
setFocusClickPending:
- (void) setFocusClickPending: (NSInteger) button
References void().
setFullscreenSpace:
- (BOOL) setFullscreenSpace: (BOOL) state
References isInFullscreenSpace.
setPendingMoveX:Y:
- (void) setPendingMoveX: (float) x Y: (float) y
References void(), and windowDidFinishMoving.
tabletPoint:
- (void) tabletPoint: (NSEvent *) theEvent
tabletProximity:
- (void) tabletProximity: (NSEvent *) theEvent
References void().
touchesBeganWithEvent:
- (void) touchesBeganWithEvent: (NSEvent *) theEvent
References void().
touchesCancelledWithEvent:
- (void) touchesCancelledWithEvent: (NSEvent *) theEvent
References void().
touchesEndedWithEvent:
- (void) touchesEndedWithEvent: (NSEvent *) theEvent
References void().
touchesMovedWithEvent:
- (void) touchesMovedWithEvent: (NSEvent *) theEvent
References void().
updateHitTest
- (void) updateHitTest
Referenced by window:willUseFullScreenPresentationOptions:.
updateIgnoreMouseState:
- (void) updateIgnoreMouseState: (NSEvent *) theEvent
References void().
window:willUseFullScreenPresentationOptions:
- (NSApplicationPresentationOptions) window: (NSWindow *) window willUseFullScreenPresentationOptions: (NSApplicationPresentationOptions) proposedOptions
References updateHitTest, and void().
windowDidBecomeKey:
- (void) windowDidBecomeKey: (NSNotification *) aNotification
References void().
windowDidChangeBackingProperties:
- (void) windowDidChangeBackingProperties: (NSNotification *) aNotification
References void().
windowDidChangeOcclusionState:
- (void) windowDidChangeOcclusionState: (NSNotification *) aNotification
References void().
windowDidChangeScreen:
- (void) windowDidChangeScreen: (NSNotification *) aNotification
References void().
windowDidChangeScreenProfile:
- (void) windowDidChangeScreenProfile: (NSNotification *) aNotification
References void().
windowDidDeminiaturize:
- (void) windowDidDeminiaturize: (NSNotification *) aNotification
References void().
windowDidEndLiveResize:
- (void) windowDidEndLiveResize: (NSNotification *) aNotification
References void().
windowDidEnterFullScreen:
- (void) windowDidEnterFullScreen: (NSNotification *) aNotification
References void().
windowDidExitFullScreen:
- (void) windowDidExitFullScreen: (NSNotification *) aNotification
windowDidExpose:
- (void) windowDidExpose: (NSNotification *) aNotification
References void().
windowDidFinishMoving
- (void) windowDidFinishMoving
References onMovingOrFocusClickPendingStateCleared, and void().
Referenced by setPendingMoveX:Y:.
windowDidMiniaturize:
- (void) windowDidMiniaturize: (NSNotification *) aNotification
References void().
windowDidMove:
- (void) windowDidMove: (NSNotification *) aNotification
References void().
windowDidResignKey:
- (void) windowDidResignKey: (NSNotification *) aNotification
References void().
windowDidResize:
- (void) windowDidResize: (NSNotification *) aNotification
References void().
windowShouldClose:
- (BOOL) windowShouldClose: (id) sender
References void().
windowWillEnterFullScreen:
- (void) windowWillEnterFullScreen: (NSNotification *) aNotification
References void().
windowWillExitFullScreen:
- (void) windowWillExitFullScreen: (NSNotification *) aNotification
References void().
windowWillStartLiveResize:
- (void) windowWillStartLiveResize: (NSNotification *) aNotification
References void().
Field Documentation
_data
- (__weak SDL_CocoaWindowData*) _data protected
focusClickPending
- (NSInteger) focusClickPending protected
inFullscreenTransition
- (BOOL) inFullscreenTransition protected
isDragAreaRunning
- (BOOL) isDragAreaRunning protected
isFullscreenSpace
- (BOOL) isFullscreenSpace protected
isMiniaturizing
- (BOOL) isMiniaturizing protected
isMoving
- (BOOL) isMoving protected
Referenced by close.
liveResizeTimer
- (NSTimer*) liveResizeTimer protected
observingVisible
- (BOOL) observingVisible protected
pendingWindowOperation
- (PendingWindowOperation) pendingWindowOperation protected
pendingWindowWarpX
- (float) pendingWindowWarpX protected
pendingWindowWarpY
- (float) pendingWindowWarpY protected
wasCtrlLeft
- (BOOL) wasCtrlLeft protected
wasVisible
- (BOOL) wasVisible protected
The documentation for this class was generated from the following file:
SDL-main/src/video/cocoa/SDL_cocoawindow.h