SDL3: SDL-main/src/SDL_error_c.h File Reference
SDL_error_c.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_error
Macros
#define SDL_PopError()
#define SDL_PushError()
Typedefs
typedef struct SDL_error SDL_error
Enumerations
enum SDL_ErrorCode { SDL_ErrorCodeNone , SDL_ErrorCodeGeneric , SDL_ErrorCodeOutOfMemory }
Functions
SDL_error * SDL_GetErrBuf (bool create)
Macro Definition Documentation
SDL_PopError
#define SDL_PopError ()
Value:
    do {                                        \
        if (saved_error) {                      \
            SDL_SetError("%s", saved_error);    \
            SDL_free(saved_error);              \
        }                                       \
    } while (0)
#define SDL_PopError()                          \
    do {                                        \
        if (saved_error) {                      \
            SDL_SetError("%s", saved_error);    \
            SDL_free(saved_error);              \
        }                                       \
    } while (0)
Referenced by SDL_InitSubSystem().
SDL_PushError
#define SDL_PushError ()
Value:
    char *saved_error = SDL_strdup(SDL_GetError())
#define SDL_PushError() \
    char *saved_error = SDL_strdup(SDL_GetError())
Referenced by SDL_InitSubSystem().
Typedef Documentation
SDL_error
typedef struct SDL_error SDL_error
Enumeration Type Documentation
SDL_ErrorCode
enum SDL_ErrorCode
Enumerator
SDL_ErrorCodeNone
SDL_ErrorCodeGeneric
SDL_ErrorCodeOutOfMemory
{
    SDL_ErrorCodeNone,
    SDL_ErrorCodeGeneric,
    SDL_ErrorCodeOutOfMemory,
} SDL_ErrorCode;
Function Documentation
SDL_GetErrBuf()
SDL_error * SDL_GetErrBuf (bool create) extern
{
#ifdef SDL_THREADS_DISABLED
    return SDL_GetStaticErrBuf();
#else
    static SDL_TLSID tls_errbuf;
    SDL_error *errbuf;
    errbuf = (SDL_error *)SDL_GetTLS(&tls_errbuf);
    if (!errbuf) {
        if (!create) {
            return NULL;
        }
        /* Get the original memory functions for this allocation because the lifetime
         * of the error buffer may span calls to SDL_SetMemoryFunctions() by the app
         */
        SDL_realloc_func realloc_func;
        SDL_free_func free_func;
        SDL_GetOriginalMemoryFunctions(NULL, NULL, &realloc_func, &free_func);
        errbuf = (SDL_error *)realloc_func(NULL, sizeof(*errbuf));
        if (!errbuf) {
            return SDL_GetStaticErrBuf();
        }
        SDL_zerop(errbuf);
        errbuf->realloc_func = realloc_func;
        errbuf->free_func = free_func;
        SDL_SetTLS(&tls_errbuf, errbuf, SDL_FreeErrBuf);
    }
    return errbuf;
#endif // SDL_THREADS_DISABLED
}
References free_func, SDL_error::free_func, NULL, realloc_func, SDL_error::realloc_func, SDL_FreeErrBuf(), SDL_GetOriginalMemoryFunctions(), SDL_GetStaticErrBuf(), SDL_GetTLS(), SDL_SetTLS(), and SDL_zerop.
Referenced by SDL_ClearError(), SDL_GetError(), SDL_OutOfMemory(), and SDL_SetErrorV().