SDL3: SDL-main/src/thread/windows/SDL_syscond_cv.c File Reference
SDL_syscond_cv.c File Reference
#include "SDL_internal.h"
#include "../generic/SDL_syscond_c.h"
#include "SDL_sysmutex_c.h"
Data Structures
struct CONDITION_VARIABLE
struct SDL_cond_cv
struct SDL_cond_impl_t
Macros
#define CONDITION_VARIABLE_INIT
Typedefs
typedef struct CONDITION_VARIABLE CONDITION_VARIABLE
typedef struct CONDITION_VARIABLE * PCONDITION_VARIABLE
typedef void(* pfnSDL_BroadcastCondition) (SDL_Condition *)
typedef SDL_Condition *(* pfnSDL_CreateCondition) (void)
typedef void(* pfnSDL_DestroyCondition) (SDL_Condition *)
typedef void(* pfnSDL_SignalCondition) (SDL_Condition *)
typedef bool(* pfnSDL_WaitConditionTimeoutNS) (SDL_Condition *, SDL_Mutex *, Sint64)
typedef BOOL(WINAPI * pfnSleepConditionVariableCS) (PCONDITION_VARIABLE, PCRITICAL_SECTION, DWORD)
typedef BOOL(WINAPI * pfnSleepConditionVariableSRW) (PCONDITION_VARIABLE, PSRWLOCK, DWORD, ULONG)
typedef VOID(WINAPI * pfnWakeAllConditionVariable) (PCONDITION_VARIABLE)
typedef VOID(WINAPI * pfnWakeConditionVariable) (PCONDITION_VARIABLE)
typedef struct SDL_cond_cv SDL_cond_cv
typedef struct SDL_cond_impl_t SDL_cond_impl_t
Functions
void SDL_BroadcastCondition (SDL_Condition *cond)
static void SDL_BroadcastCondition_cv (SDL_Condition *_cond)
SDL_Condition * SDL_CreateCondition (void)
static SDL_Condition * SDL_CreateCondition_cv (void)
void SDL_DestroyCondition (SDL_Condition *cond)
static void SDL_DestroyCondition_cv (SDL_Condition *cond)
void SDL_SignalCondition (SDL_Condition *cond)
static void SDL_SignalCondition_cv (SDL_Condition *_cond)
bool SDL_WaitConditionTimeoutNS (SDL_Condition *cond, SDL_Mutex *mutex, Sint64 timeoutNS)
static bool SDL_WaitConditionTimeoutNS_cv (SDL_Condition *_cond, SDL_Mutex *_mutex, Sint64 timeoutNS)
Variables
static pfnSleepConditionVariableCS pSleepConditionVariableCS = NULL
static pfnSleepConditionVariableSRW pSleepConditionVariableSRW = NULL
static pfnWakeAllConditionVariable pWakeAllConditionVariable = NULL
static pfnWakeConditionVariable pWakeConditionVariable = NULL
static SDL_cond_impl_t SDL_cond_impl_active = { 0 }
static const SDL_cond_impl_t SDL_cond_impl_cv
static const SDL_cond_impl_t SDL_cond_impl_generic
Macro Definition Documentation
CONDITION_VARIABLE_INIT
#define CONDITION_VARIABLE_INIT
Value:
    {                           \
        0                       \
    }
Native Windows Condition Variable (SRW Locks)
#define CONDITION_VARIABLE_INIT \
    {                           \
        0                       \
    }
Typedef Documentation
CONDITION_VARIABLE
typedef struct CONDITION_VARIABLE CONDITION_VARIABLE
PCONDITION_VARIABLE
typedef struct CONDITION_VARIABLE * PCONDITION_VARIABLE
pfnSDL_BroadcastCondition
typedef void(* pfnSDL_BroadcastCondition) (SDL_Condition *)
pfnSDL_CreateCondition
typedef SDL_Condition *(* pfnSDL_CreateCondition) (void)
pfnSDL_DestroyCondition
typedef void(* pfnSDL_DestroyCondition) (SDL_Condition *)
pfnSDL_SignalCondition
typedef void(* pfnSDL_SignalCondition) (SDL_Condition *)
pfnSDL_WaitConditionTimeoutNS
typedef bool(* pfnSDL_WaitConditionTimeoutNS) (SDL_Condition *, SDL_Mutex *, Sint64)
pfnSleepConditionVariableCS
typedef BOOL(WINAPI * pfnSleepConditionVariableCS) (PCONDITION_VARIABLE, PCRITICAL_SECTION, DWORD)
pfnSleepConditionVariableSRW
typedef BOOL(WINAPI * pfnSleepConditionVariableSRW) (PCONDITION_VARIABLE, PSRWLOCK, DWORD, ULONG)
pfnWakeAllConditionVariable
typedef VOID(WINAPI * pfnWakeAllConditionVariable) (PCONDITION_VARIABLE)
pfnWakeConditionVariable
typedef VOID(WINAPI * pfnWakeConditionVariable) (PCONDITION_VARIABLE)
SDL_cond_cv
typedef struct SDL_cond_cv SDL_cond_cv
SDL_cond_impl_t
typedef struct SDL_cond_impl_t SDL_cond_impl_t
Function Documentation
SDL_BroadcastCondition()
void SDL_BroadcastCondition (SDL_Condition * cond)
Restart all threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    if (!cond) {
        return;
    }
    SDL_cond_impl_active.Broadcast(cond);
}
References SDL_cond_generic::handshake_sem, SDL_cond_generic::num_signals, SDL_cond_generic::num_waiting, SDL_cond_impl_active, SDL_SignalSemaphore(), SDL_WaitSemaphore(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by AsyncIOThreadpoolWorker(), ClosePhysicalAudioDevice(), generic_asyncioqueue_signal(), hidapi_thread_cond_broadcast(), QueueAsyncIOTask(), SDL_UnlockRWLock(), SDL_WaitThreadBarrier(), and ShutdownThreadpool().
SDL_BroadcastCondition_cv()
void SDL_BroadcastCondition_cv (SDL_Condition * _cond) static
{
    SDL_cond_cv *cond = (SDL_cond_cv *)_cond;
    pWakeAllConditionVariable(&cond->cond);
}
References SDL_cond_cv::cond, and pWakeAllConditionVariable.
SDL_CreateCondition()
SDL_Condition * SDL_CreateCondition (void)
Create a condition variable.
Returns
a new condition variable or NULL on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
SDL_DestroyCondition
{
    if (!SDL_cond_impl_active.Create) {
        const SDL_cond_impl_t *impl = NULL;
        if (SDL_mutex_impl_active.Type == SDL_MUTEX_INVALID) {
            // The mutex implementation isn't decided yet, trigger it
            SDL_Mutex *mutex = SDL_CreateMutex();
            if (!mutex) {
                return NULL;
            }
            SDL_DestroyMutex(mutex);
            SDL_assert(SDL_mutex_impl_active.Type != SDL_MUTEX_INVALID);
        }
        // Default to generic implementation, works with all mutex implementations
        impl = &SDL_cond_impl_generic;
        {
            HMODULE kernel32 = GetModuleHandle(TEXT("kernel32.dll"));
            if (kernel32) {
                pWakeConditionVariable = (pfnWakeConditionVariable)GetProcAddress(kernel32, "WakeConditionVariable");
                pWakeAllConditionVariable = (pfnWakeAllConditionVariable)GetProcAddress(kernel32, "WakeAllConditionVariable");
                pSleepConditionVariableSRW = (pfnSleepConditionVariableSRW)GetProcAddress(kernel32, "SleepConditionVariableSRW");
                pSleepConditionVariableCS = (pfnSleepConditionVariableCS)GetProcAddress(kernel32, "SleepConditionVariableCS");
                if (pWakeConditionVariable && pWakeAllConditionVariable && pSleepConditionVariableSRW && pSleepConditionVariableCS) {
                    // Use the Windows provided API
                    impl = &SDL_cond_impl_cv;
                }
            }
        }
        SDL_copyp(&SDL_cond_impl_active, impl);
    }
    return SDL_cond_impl_active.Create();
}
References SDL_cond_generic::handshake_sem, kernel32, NULL, pSleepConditionVariableCS, pSleepConditionVariableSRW, pWakeAllConditionVariable, pWakeConditionVariable, SDL_assert, SDL_calloc(), SDL_cond_impl_active, SDL_cond_impl_cv, SDL_cond_impl_generic, SDL_copyp, SDL_CreateMutex(), SDL_CreateSemaphore(), SDL_DestroyCondition_generic, SDL_DestroyMutex(), SDL_mutex_impl_active, SDL_MUTEX_INVALID, SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by CreatePhysicalAudioDevice(), hidapi_thread_state_init(), PrepareThreadpool(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateThreadBarrier(), and SDL_SYS_CreateAsyncIOQueue_Generic().
SDL_CreateCondition_cv()
SDL_Condition * SDL_CreateCondition_cv (void) static
{
    // Relies on CONDITION_VARIABLE_INIT == 0.
    return (SDL_Condition *)SDL_calloc(1, sizeof(SDL_cond_cv));
}
References SDL_calloc().
SDL_DestroyCondition()
void SDL_DestroyCondition (SDL_Condition * cond)
Destroy a condition variable.
Parameters
cond the condition variable to destroy.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateCondition
{
    if (cond) {
        SDL_cond_impl_active.Destroy(cond);
    }
}
References SDL_cond_generic::handshake_sem, SDL_cond_impl_active, SDL_DestroySemaphore(), SDL_free(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by CreatePhysicalAudioDevice(), DestroyPhysicalAudioDevice(), generic_asyncioqueue_destroy(), hidapi_thread_state_destroy(), PrepareThreadpool(), SDL_DestroyRWLock(), SDL_DestroySemaphore(), SDL_DestroyThreadBarrier(), and ShutdownThreadpool().
SDL_DestroyCondition_cv()
void SDL_DestroyCondition_cv (SDL_Condition * cond) static
{
    // There are no kernel allocated resources
    SDL_free(cond);
}
References SDL_free().
SDL_SignalCondition()
void SDL_SignalCondition (SDL_Condition * cond)
Restart one of the threads that are waiting on the condition variable.
Parameters
cond the condition variable to signal.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_WaitCondition
SDL_WaitConditionTimeout
{
    if (!cond) {
        return;
    }
    SDL_cond_impl_active.Signal(cond);
}
References SDL_cond_generic::handshake_sem, SDL_cond_generic::num_signals, SDL_cond_generic::num_waiting, SDL_cond_impl_active, SDL_SignalSemaphore(), SDL_WaitSemaphore(), SDL_cond_generic::sem, and SDL_cond_generic::signal_sem.
Referenced by AsyncIOTaskComplete(), hidapi_thread_cond_signal(), SDL_DestroySemaphore(), and SDL_SignalSemaphore().
SDL_SignalCondition_cv()
void SDL_SignalCondition_cv (SDL_Condition * _cond) static
{
    SDL_cond_cv *cond = (SDL_cond_cv *)_cond;
    pWakeConditionVariable(&cond->cond);
}
References SDL_cond_cv::cond, and pWakeConditionVariable.
SDL_WaitConditionTimeoutNS()
bool SDL_WaitConditionTimeoutNS (SDL_Condition * cond, SDL_Mutex * mutex, Sint64 timeoutNS)
{
    if (!cond || !mutex) {
        return true;
    }
    return SDL_cond_impl_active.WaitTimeoutNS(cond, mutex, timeoutNS);
}
References SDL_cond_impl_active, and SDL_WaitConditionTimeoutNS_generic().
Referenced by SDL_WaitCondition(), SDL_WaitConditionTimeout(), and SDL_WaitSemaphoreTimeoutNS().
SDL_WaitConditionTimeoutNS_cv()
bool SDL_WaitConditionTimeoutNS_cv (SDL_Condition * _cond, SDL_Mutex * _mutex, Sint64 timeoutNS) static
{
    SDL_cond_cv *cond = (SDL_cond_cv *)_cond;
    DWORD timeout;
    bool result;
    if (timeoutNS < 0) {
        timeout = INFINITE;
    } else {
        timeout = (DWORD)SDL_NS_TO_MS(timeoutNS);
    }
    if (SDL_mutex_impl_active.Type == SDL_MUTEX_SRW) {
        SDL_mutex_srw *mutex = (SDL_mutex_srw *)_mutex;
        if (mutex->count != 1 || mutex->owner != GetCurrentThreadId()) {
            // Passed mutex is not locked or locked recursively"
            return false;
        }
        // The mutex must be updated to the released state
        mutex->count = 0;
        mutex->owner = 0;
        result = (pSleepConditionVariableSRW(&cond->cond, &mutex->srw, timeout, 0) == TRUE);
        // The mutex is owned by us again, regardless of status of the wait
        SDL_assert(mutex->count == 0 && mutex->owner == 0);
        mutex->count = 1;
        mutex->owner = GetCurrentThreadId();
    } else {
        SDL_mutex_cs *mutex = (SDL_mutex_cs *)_mutex;
        SDL_assert(SDL_mutex_impl_active.Type == SDL_MUTEX_CS);
        result = (pSleepConditionVariableCS(&cond->cond, &mutex->cs, timeout) == TRUE);
    }
    return result;
}
References SDL_cond_cv::cond, SDL_mutex_srw::count, SDL_mutex_cs::cs, SDL_mutex_srw::owner, pSleepConditionVariableCS, pSleepConditionVariableSRW, SDL_assert, SDL_MUTEX_CS, SDL_mutex_impl_active, SDL_MUTEX_SRW, SDL_NS_TO_MS, SDL_mutex_srw::srw, and TRUE.
Variable Documentation
pSleepConditionVariableCS
pfnSleepConditionVariableCS pSleepConditionVariableCS = NULL static
Referenced by SDL_CreateCondition(), and SDL_WaitConditionTimeoutNS_cv().
pSleepConditionVariableSRW
pfnSleepConditionVariableSRW pSleepConditionVariableSRW = NULL static
Referenced by SDL_CreateCondition(), and SDL_WaitConditionTimeoutNS_cv().
pWakeAllConditionVariable
pfnWakeAllConditionVariable pWakeAllConditionVariable = NULL static
Referenced by SDL_BroadcastCondition_cv(), and SDL_CreateCondition().
pWakeConditionVariable
pfnWakeConditionVariable pWakeConditionVariable = NULL static
Referenced by SDL_CreateCondition(), and SDL_SignalCondition_cv().
SDL_cond_impl_active
SDL_cond_impl_t SDL_cond_impl_active = { 0 } static
{ 0 };
Referenced by SDL_BroadcastCondition(), SDL_CreateCondition(), SDL_DestroyCondition(), SDL_SignalCondition(), and SDL_WaitConditionTimeoutNS().
SDL_cond_impl_cv
const SDL_cond_impl_t SDL_cond_impl_cv static
Initial value:
= {
    &SDL_CreateCondition_cv,
    &SDL_DestroyCondition_cv,
    &SDL_SignalCondition_cv,
    &SDL_BroadcastCondition_cv,
    &SDL_WaitConditionTimeoutNS_cv,
}
{
    &SDL_CreateCondition_cv,
    &SDL_DestroyCondition_cv,
    &SDL_SignalCondition_cv,
    &SDL_BroadcastCondition_cv,
    &SDL_WaitConditionTimeoutNS_cv,
};
Referenced by SDL_CreateCondition().
SDL_cond_impl_generic
const SDL_cond_impl_t SDL_cond_impl_generic static
Initial value:
= {
    &SDL_CreateCondition_generic,
    &SDL_DestroyCondition_generic,
    &SDL_SignalCondition_generic,
    &SDL_BroadcastCondition_generic,
    &SDL_WaitConditionTimeoutNS_generic,
}
{
    &SDL_CreateCondition_generic,
    &SDL_DestroyCondition_generic,
    &SDL_SignalCondition_generic,
    &SDL_BroadcastCondition_generic,
    &SDL_WaitConditionTimeoutNS_generic,
};
Referenced by SDL_CreateCondition().