SDL3: SDL-main/src/audio/SDL_audiotypecvt.c File Reference
SDL_audiotypecvt.c File Reference
#include "SDL_internal.h"
#include "SDL_sysaudio.h"
Data Structures
union float_bits
Macros
#define CONVERT_16_FWD(CVT1, CVT16)
#define CONVERT_16_REV(CVT1, CVT16)
#define DIVBY2147483648 0.0000000004656612873077392578125f
#define SET_CONVERTER_FUNCS(fntype)
#define SET_CONVERTER_FUNCS(fntype)
#define SIGNMASK(x)
Functions
void ConvertAudioFromFloat (void *dst, const float *src, int num_samples, SDL_AudioFormat dst_fmt)
void ConvertAudioSwapEndian (void *dst, const void *src, int num_samples, int bitsize)
void ConvertAudioToFloat (float *dst, const void *src, int num_samples, SDL_AudioFormat src_fmt)
void SDL_ChooseAudioConverters (void)
SDL_COMPILE_TIME_ASSERT (float_bits, sizeof(float)==sizeof(Uint32))
static void SDL_Convert_F32_to_S16_Scalar (Sint16 *dst, const float *src, int num_samples)
static void SDL_Convert_F32_to_S32_Scalar (Sint32 *dst, const float *src, int num_samples)
static void SDL_Convert_F32_to_S8_Scalar (Sint8 *dst, const float *src, int num_samples)
static void SDL_Convert_F32_to_U8_Scalar (Uint8 *dst, const float *src, int num_samples)
static void SDL_Convert_S16_to_F32_Scalar (float *dst, const Sint16 *src, int num_samples)
static void SDL_Convert_S32_to_F32_Scalar (float *dst, const Sint32 *src, int num_samples)
static void SDL_Convert_S8_to_F32_Scalar (float *dst, const Sint8 *src, int num_samples)
static void SDL_Convert_Swap16_Scalar (Uint16 *dst, const Uint16 *src, int num_samples)
static void SDL_Convert_Swap32_Scalar (Uint32 *dst, const Uint32 *src, int num_samples)
static void SDL_Convert_U8_to_F32_Scalar (float *dst, const Uint8 *src, int num_samples)
Variables
static void(* SDL_Convert_F32_to_S16)(Sint16 *dst, const float *src, int num_samples) = NULL
static void(* SDL_Convert_F32_to_S32)(Sint32 *dst, const float *src, int num_samples) = NULL
static void(* SDL_Convert_F32_to_S8)(Sint8 *dst, const float *src, int num_samples) = NULL
static void(* SDL_Convert_F32_to_U8)(Uint8 *dst, const float *src, int num_samples) = NULL
static void(* SDL_Convert_S16_to_F32)(float *dst, const Sint16 *src, int num_samples) = NULL
static void(* SDL_Convert_S32_to_F32)(float *dst, const Sint32 *src, int num_samples) = NULL
static void(* SDL_Convert_S8_to_F32)(float *dst, const Sint8 *src, int num_samples) = NULL
static void(* SDL_Convert_Swap16)(Uint16 *dst, const Uint16 *src, int num_samples) = NULL
static void(* SDL_Convert_Swap32)(Uint32 *dst, const Uint32 *src, int num_samples) = NULL
static void(* SDL_Convert_U8_to_F32)(float *dst, const Uint8 *src, int num_samples) = NULL
Macro Definition Documentation
CONVERT_16_FWD
#define CONVERT_16_FWD (CVT1, CVT16)
Value:
    int i = 0;                                               \
    if (num_samples >= 16) {                                 \
        while ((uintptr_t)(&dst[i]) & 15) { CVT1  ++i;     } \
        while ((i + 16) <= num_samples)   { CVT16 i += 16; } \
    }                                                        \
    while (i < num_samples)               { CVT1  ++i;     }
#define CONVERT_16_FWD(CVT1, CVT16)                          \
    int i = 0;                                               \
    if (num_samples >= 16) {                                 \
        while ((uintptr_t)(&dst[i]) & 15) { CVT1  ++i;     } \
        while ((i + 16) <= num_samples)   { CVT16 i += 16; } \
    }                                                        \
    while (i < num_samples)               { CVT1  ++i;     }
CONVERT_16_REV
#define CONVERT_16_REV (CVT1, CVT16)
Value:
    int i = num_samples;                                     \
    if (i >= 16) {                                           \
        while ((uintptr_t)(&dst[i]) & 15) { --i;     CVT1  } \
        while (i >= 16)                   { i -= 16; CVT16 } \
    }                                                        \
    while (i > 0)                         { --i;     CVT1  }
#define CONVERT_16_REV(CVT1, CVT16)                          \
    int i = num_samples;                                     \
    if (i >= 16) {                                           \
        while ((uintptr_t)(&dst[i]) & 15) { --i;     CVT1  } \
        while (i >= 16)                   { i -= 16; CVT16 } \
    }                                                        \
    while (i > 0)                         { --i;     CVT1  }
DIVBY2147483648
#define DIVBY2147483648 0.0000000004656612873077392578125f
Referenced by SDL_Convert_S32_to_F32_Scalar().
SET_CONVERTER_FUNCS [1/2]
#define SET_CONVERTER_FUNCS (fntype)
Value:
    SDL_Convert_Swap16 = SDL_Convert_Swap16_##fntype; \
    SDL_Convert_Swap32 = SDL_Convert_Swap32_##fntype;
Referenced by SDL_ChooseAudioConverters().
SET_CONVERTER_FUNCS [2/2]
#define SET_CONVERTER_FUNCS (fntype)
Value:
    SDL_Convert_S8_to_F32 = SDL_Convert_S8_to_F32_##fntype; \
    SDL_Convert_U8_to_F32 = SDL_Convert_U8_to_F32_##fntype; \
    SDL_Convert_S16_to_F32 = SDL_Convert_S16_to_F32_##fntype; \
    SDL_Convert_S32_to_F32 = SDL_Convert_S32_to_F32_##fntype; \
    SDL_Convert_F32_to_S8 = SDL_Convert_F32_to_S8_##fntype; \
    SDL_Convert_F32_to_U8 = SDL_Convert_F32_to_U8_##fntype; \
    SDL_Convert_F32_to_S16 = SDL_Convert_F32_to_S16_##fntype; \
    SDL_Convert_F32_to_S32 = SDL_Convert_F32_to_S32_##fntype; \
SIGNMASK
#define SIGNMASK (x)
Value:
(Uint32)(0u - ((Uint32)(x) >> 31))
Referenced by SDL_Convert_F32_to_S16_Scalar(), SDL_Convert_F32_to_S32_Scalar(), SDL_Convert_F32_to_S8_Scalar(), and SDL_Convert_F32_to_U8_Scalar().
Function Documentation
ConvertAudioFromFloat()
void ConvertAudioFromFloat (void * dst, const float * src, int num_samples, SDL_AudioFormat dst_fmt)
{
    switch (dst_fmt) {
        case SDL_AUDIO_S8:
            SDL_Convert_F32_to_S8((Sint8 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_U8:
            SDL_Convert_F32_to_U8((Uint8 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_S16:
            SDL_Convert_F32_to_S16((Sint16 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_S16 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_F32_to_S16((Sint16 *) dst, src, num_samples);
            SDL_Convert_Swap16((Uint16 *)dst, (const Uint16 *)dst, num_samples);
            break;
        case SDL_AUDIO_S32:
            SDL_Convert_F32_to_S32((Sint32 *) dst, src, num_samples);
            break;
        case SDL_AUDIO_S32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_F32_to_S32((Sint32 *) dst, src, num_samples);
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)dst, num_samples);
            break;
        case SDL_AUDIO_F32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples);
            break;
        default: SDL_assert(!"Unexpected audio format!"); break;
    }
}
References SDL_assert, SDL_AUDIO_F32, SDL_AUDIO_MASK_BIG_ENDIAN, SDL_AUDIO_S16, SDL_AUDIO_S32, SDL_AUDIO_S8, SDL_AUDIO_U8, SDL_Convert_F32_to_S16, SDL_Convert_F32_to_S32, SDL_Convert_F32_to_S8, SDL_Convert_F32_to_U8, SDL_Convert_Swap16, and SDL_Convert_Swap32.
Referenced by ConvertAudio().
ConvertAudioSwapEndian()
void ConvertAudioSwapEndian (void * dst, const void * src, int num_samples, int bitsize)
{
    switch (bitsize) {
        case 16: SDL_Convert_Swap16((Uint16 *)dst, (const Uint16 *)src, num_samples); break;
        case 32: SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples); break;
        default: SDL_assert(!"Unexpected audio format!"); break;
    }
}
References SDL_assert, SDL_Convert_Swap16, and SDL_Convert_Swap32.
Referenced by ConvertAudio().
ConvertAudioToFloat()
void ConvertAudioToFloat (float * dst, const void * src, int num_samples, SDL_AudioFormat src_fmt)
{
    switch (src_fmt) {
        case SDL_AUDIO_S8:
            SDL_Convert_S8_to_F32(dst, (const Sint8 *) src, num_samples);
            break;
        case SDL_AUDIO_U8:
            SDL_Convert_U8_to_F32(dst, (const Uint8 *) src, num_samples);
            break;
        case SDL_AUDIO_S16:
            SDL_Convert_S16_to_F32(dst, (const Sint16 *) src, num_samples);
            break;
        case SDL_AUDIO_S16 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap16((Uint16 *)dst, (const Uint16 *)src, num_samples);
            SDL_Convert_S16_to_F32(dst, (const Sint16 *) dst, num_samples);
            break;
        case SDL_AUDIO_S32:
            SDL_Convert_S32_to_F32(dst, (const Sint32 *) src, num_samples);
            break;
        case SDL_AUDIO_S32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples);
            SDL_Convert_S32_to_F32(dst, (const Sint32 *) dst, num_samples);
            break;
        case SDL_AUDIO_F32 ^ SDL_AUDIO_MASK_BIG_ENDIAN:
            SDL_Convert_Swap32((Uint32 *)dst, (const Uint32 *)src, num_samples);
            break;
        default: SDL_assert(!"Unexpected audio format!"); break;
    }
}
References SDL_assert, SDL_AUDIO_F32, SDL_AUDIO_MASK_BIG_ENDIAN, SDL_AUDIO_S16, SDL_AUDIO_S32, SDL_AUDIO_S8, SDL_AUDIO_U8, SDL_Convert_S16_to_F32, SDL_Convert_S32_to_F32, SDL_Convert_S8_to_F32, SDL_Convert_Swap16, SDL_Convert_Swap32, and SDL_Convert_U8_to_F32.
Referenced by ConvertAudio().
SDL_ChooseAudioConverters()
void SDL_ChooseAudioConverters (void)
{
    static bool converters_chosen = false;
    if (converters_chosen) {
        return;
    }
#define SET_CONVERTER_FUNCS(fntype) \
    SDL_Convert_Swap16 = SDL_Convert_Swap16_##fntype; \
    SDL_Convert_Swap32 = SDL_Convert_Swap32_##fntype;
#ifdef SDL_SSE4_1_INTRINSICS
    if (SDL_HasSSE41()) {
        SET_CONVERTER_FUNCS(SSSE3);
    } else
#endif
#ifdef SDL_NEON_INTRINSICS
    if (SDL_HasNEON()) {
        SET_CONVERTER_FUNCS(NEON);
    } else
#endif
    {
        SET_CONVERTER_FUNCS(Scalar);
    }
#undef SET_CONVERTER_FUNCS
#define SET_CONVERTER_FUNCS(fntype) \
    SDL_Convert_S8_to_F32 = SDL_Convert_S8_to_F32_##fntype; \
    SDL_Convert_U8_to_F32 = SDL_Convert_U8_to_F32_##fntype; \
    SDL_Convert_S16_to_F32 = SDL_Convert_S16_to_F32_##fntype; \
    SDL_Convert_S32_to_F32 = SDL_Convert_S32_to_F32_##fntype; \
    SDL_Convert_F32_to_S8 = SDL_Convert_F32_to_S8_##fntype; \
    SDL_Convert_F32_to_U8 = SDL_Convert_F32_to_U8_##fntype; \
    SDL_Convert_F32_to_S16 = SDL_Convert_F32_to_S16_##fntype; \
    SDL_Convert_F32_to_S32 = SDL_Convert_F32_to_S32_##fntype; \
#ifdef SDL_SSE2_INTRINSICS
    if (SDL_HasSSE2()) {
        SET_CONVERTER_FUNCS(SSE2);
    } else
#endif
#ifdef SDL_NEON_INTRINSICS
    if (SDL_HasNEON()) {
        SET_CONVERTER_FUNCS(NEON);
    } else
#endif
    {
        SET_CONVERTER_FUNCS(Scalar);
    }
#undef SET_CONVERTER_FUNCS
    converters_chosen = true;
}
References SDL_HasNEON(), SDL_HasSSE2(), SDL_HasSSE41(), and SET_CONVERTER_FUNCS.
Referenced by SDL_CreateAudioStream(), and SDL_InitAudio().
SDL_COMPILE_TIME_ASSERT()
SDL_COMPILE_TIME_ASSERT (float_bits , sizeof(float) = =sizeof(Uint32))
SDL_Convert_F32_to_S16_Scalar()
void SDL_Convert_F32_to_S16_Scalar (Sint16 * dst, const float * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("F32", "S16");
    for (i = 0; i < num_samples; ++i) {
        /* 1) Shift the float range from [-1.0, 1.0] to [383.0, 385.0]
         * 2) Shift the integer range from [0x43BF8000, 0x43C08000] to [-32768, 32768]
         * 3) Clamp values outside the [-32768, 32767] range */
        union float_bits x;
        x.f32 = src[i] + 384.0f;
        Uint32 y = x.u32 - 0x43C00000u;
        Uint32 z = 0x7FFFu - (y ^ SIGNMASK(y));
        y = y ^ (z & SIGNMASK(z));
        dst[i] = (Sint16)(y & 0xFFFF);
    }
}
References LOG_DEBUG_AUDIO_CONVERT, and SIGNMASK.
SDL_Convert_F32_to_S32_Scalar()
void SDL_Convert_F32_to_S32_Scalar (Sint32 * dst, const float * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("F32", "S32");
    for (i = 0; i < num_samples; ++i) {
        /* 1) Shift the float range from [-1.0, 1.0] to [-2147483648.0, 2147483648.0]
         * 2) Set values outside the [-2147483648.0, 2147483647.0] range to -2147483648.0
         * 3) Convert the float to an integer, and fixup values outside the valid range */
        union float_bits x;
        x.f32 = src[i];
        Uint32 y = x.u32 + 0x0F800000u;
        Uint32 z = y - 0xCF000000u;
        z &= SIGNMASK(y ^ z);
        x.u32 = y - z;
        dst[i] = (Sint32)x.f32 ^ (Sint32)SIGNMASK(z);
    }
}
References LOG_DEBUG_AUDIO_CONVERT, and SIGNMASK.
SDL_Convert_F32_to_S8_Scalar()
void SDL_Convert_F32_to_S8_Scalar (Sint8 * dst, const float * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("F32", "S8");
    for (i = 0; i < num_samples; ++i) {
        /* 1) Shift the float range from [-1.0, 1.0] to [98303.0, 98305.0]
         * 2) Shift the integer range from [0x47BFFF80, 0x47C00080] to [-128, 128]
         * 3) Clamp the value to [-128, 127] */
        union float_bits x;
        x.f32 = src[i] + 98304.0f;
        Uint32 y = x.u32 - 0x47C00000u;
        Uint32 z = 0x7Fu - (y ^ SIGNMASK(y));
        y = y ^ (z & SIGNMASK(z));
        dst[i] = (Sint8)(y & 0xFF);
    }
}
References LOG_DEBUG_AUDIO_CONVERT, and SIGNMASK.
SDL_Convert_F32_to_U8_Scalar()
void SDL_Convert_F32_to_U8_Scalar (Uint8 * dst, const float * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("F32", "U8");
    for (i = 0; i < num_samples; ++i) {
        /* 1) Shift the float range from [-1.0, 1.0] to [98303.0, 98305.0]
         * 2) Shift the integer range from [0x47BFFF80, 0x47C00080] to [-128, 128]
         * 3) Clamp the value to [-128, 127]
         * 4) Shift the integer range from [-128, 127] to [0, 255] */
        union float_bits x;
        x.f32 = src[i] + 98304.0f;
        Uint32 y = x.u32 - 0x47C00000u;
        Uint32 z = 0x7Fu - (y ^ SIGNMASK(y));
        y = (y ^ 0x80u) ^ (z & SIGNMASK(z));
        dst[i] = (Uint8)(y & 0xFF);
    }
}
References LOG_DEBUG_AUDIO_CONVERT, and SIGNMASK.
SDL_Convert_S16_to_F32_Scalar()
void SDL_Convert_S16_to_F32_Scalar (float * dst, const Sint16 * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("S16", "F32");
    for (i = num_samples - 1; i >= 0; --i) {
        /* 1) Construct a float in the range [256.0, 258.0)
         * 2) Shift the float range to [-1.0, 1.0) */
        union float_bits x;
        x.u32 = (Uint16)src[i] ^ 0x43808000u;
        dst[i] = x.f32 - 257.0f;
    }
}
References LOG_DEBUG_AUDIO_CONVERT.
SDL_Convert_S32_to_F32_Scalar()
void SDL_Convert_S32_to_F32_Scalar (float * dst, const Sint32 * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("S32", "F32");
    for (i = num_samples - 1; i >= 0; --i) {
        dst[i] = (float)src[i] * DIVBY2147483648;
    }
}
References DIVBY2147483648, and LOG_DEBUG_AUDIO_CONVERT.
SDL_Convert_S8_to_F32_Scalar()
void SDL_Convert_S8_to_F32_Scalar (float * dst, const Sint8 * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("S8", "F32");
    for (i = num_samples - 1; i >= 0; --i) {
        /* 1) Construct a float in the range [65536.0, 65538.0)
         * 2) Shift the float range to [-1.0, 1.0) */
        union float_bits x;
        x.u32 = (Uint8)src[i] ^ 0x47800080u;
        dst[i] = x.f32 - 65537.0f;
    }
}
References LOG_DEBUG_AUDIO_CONVERT.
SDL_Convert_Swap16_Scalar()
void SDL_Convert_Swap16_Scalar (Uint16 * dst, const Uint16 * src, int num_samples) static
{
    int i;
    for (i = 0; i < num_samples; ++i) {
        dst[i] = SDL_Swap16(src[i]);
    }
}
References SDL_Swap16().
SDL_Convert_Swap32_Scalar()
void SDL_Convert_Swap32_Scalar (Uint32 * dst, const Uint32 * src, int num_samples) static
{
    int i;
    for (i = 0; i < num_samples; ++i) {
        dst[i] = SDL_Swap32(src[i]);
    }
}
References SDL_Swap32().
SDL_Convert_U8_to_F32_Scalar()
void SDL_Convert_U8_to_F32_Scalar (float * dst, const Uint8 * src, int num_samples) static
{
    int i;
    LOG_DEBUG_AUDIO_CONVERT("U8", "F32");
    for (i = num_samples - 1; i >= 0; --i) {
        /* 1) Construct a float in the range [65536.0, 65538.0)
         * 2) Shift the float range to [-1.0, 1.0) */
        union float_bits x;
        x.u32 = src[i] ^ 0x47800000u;
        dst[i] = x.f32 - 65537.0f;
    }
}
References LOG_DEBUG_AUDIO_CONVERT.
Variable Documentation
SDL_Convert_F32_to_S16
void(* SDL_Convert_F32_to_S16) (Sint16 *dst, const float *src, int num_samples) (Sint16 * dst, const float * src, int num_samples) = NULL static
Referenced by ConvertAudioFromFloat().
SDL_Convert_F32_to_S32
void(* SDL_Convert_F32_to_S32) (Sint32 *dst, const float *src, int num_samples) (Sint32 * dst, const float * src, int num_samples) = NULL static
Referenced by ConvertAudioFromFloat().
SDL_Convert_F32_to_S8
void(* SDL_Convert_F32_to_S8) (Sint8 *dst, const float *src, int num_samples) (Sint8 * dst, const float * src, int num_samples) = NULL static
Referenced by ConvertAudioFromFloat().
SDL_Convert_F32_to_U8
void(* SDL_Convert_F32_to_U8) (Uint8 *dst, const float *src, int num_samples) (Uint8 * dst, const float * src, int num_samples) = NULL static
Referenced by ConvertAudioFromFloat().
SDL_Convert_S16_to_F32
void(* SDL_Convert_S16_to_F32) (float *dst, const Sint16 *src, int num_samples) (float * dst, const Sint16 * src, int num_samples) = NULL static
Referenced by ConvertAudioToFloat().
SDL_Convert_S32_to_F32
void(* SDL_Convert_S32_to_F32) (float *dst, const Sint32 *src, int num_samples) (float * dst, const Sint32 * src, int num_samples) = NULL static
Referenced by ConvertAudioToFloat().
SDL_Convert_S8_to_F32
void(* SDL_Convert_S8_to_F32) (float *dst, const Sint8 *src, int num_samples) (float * dst, const Sint8 * src, int num_samples) = NULL static
Referenced by ConvertAudioToFloat().
SDL_Convert_Swap16
void(* SDL_Convert_Swap16) (Uint16 *dst, const Uint16 *src, int num_samples) (Uint16 * dst, const Uint16 * src, int num_samples) = NULL static
Referenced by ConvertAudioFromFloat(), ConvertAudioSwapEndian(), and ConvertAudioToFloat().
SDL_Convert_Swap32
void(* SDL_Convert_Swap32) (Uint32 *dst, const Uint32 *src, int num_samples) (Uint32 * dst, const Uint32 * src, int num_samples) = NULL static
Referenced by ConvertAudioFromFloat(), ConvertAudioSwapEndian(), and ConvertAudioToFloat().
SDL_Convert_U8_to_F32
void(* SDL_Convert_U8_to_F32) (float *dst, const Uint8 *src, int num_samples) (float * dst, const Uint8 * src, int num_samples) = NULL static
Referenced by ConvertAudioToFloat().