SDL3: SDL-main/src/atomic/SDL_spinlock.c File Reference
SDL_spinlock.c File Reference
#include "SDL_internal.h"
Functions
void SDL_LockSpinlock (SDL_SpinLock *lock)
bool SDL_TryLockSpinlock (SDL_SpinLock *lock)
void SDL_UnlockSpinlock (SDL_SpinLock *lock)
Function Documentation
SDL_LockSpinlock()
void SDL_LockSpinlock (SDL_SpinLock * lock)
Lock a spin lock by setting it to a non-zero value.
Please note that spinlocks are dangerous if you don't know what you're doing. Please be careful using any sort of spinlock!
Parameters
lock a pointer to a lock variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_TryLockSpinlock
SDL_UnlockSpinlock
{
    int iterations = 0;
    // FIXME: Should we have an eventual timeout?
    while (!SDL_TryLockSpinlock(lock)) {
        if (iterations < 32) {
            iterations++;
            SDL_CPUPauseInstruction();
        } else {
            // !!! FIXME: this doesn't definitely give up the current timeslice, it does different things on various platforms.
            SDL_Delay(0);
        }
    }
}
References lock, SDL_CPUPauseInstruction, SDL_Delay(), and SDL_TryLockSpinlock().
Referenced by enterLock(), SDL_CreateTimer(), SDL_ReportAssertion(), and SDL_TimerThread().
SDL_TryLockSpinlock()
bool SDL_TryLockSpinlock (SDL_SpinLock * lock)
Try to lock a spin lock by setting it to a non-zero value.
Please note that spinlocks are dangerous if you don't know what you're doing. Please be careful using any sort of spinlock!
Parameters
lock a pointer to a lock variable.
Returns
true if the lock succeeded, false if the lock is already held.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockSpinlock
SDL_UnlockSpinlock
{
#if defined(HAVE_GCC_ATOMICS) || defined(HAVE_GCC_SYNC_LOCK_TEST_AND_SET)
    return __sync_lock_test_and_set(lock, 1) == 0;
#elif defined(_MSC_VER) && (defined(_M_ARM) || defined(_M_ARM64))
    return _InterlockedExchange_acq(lock, 1) == 0;
#elif defined(_MSC_VER)
    SDL_COMPILE_TIME_ASSERT(locksize, sizeof(*lock) == sizeof(long));
    return InterlockedExchange((long *)lock, 1) == 0;
#elif defined(__WATCOMC__) && defined(__386__)
    return _SDL_xchg_watcom(lock, 1) == 0;
#elif defined(__GNUC__) && defined(__arm__) &&               \
    (defined(__ARM_ARCH_3__) || defined(__ARM_ARCH_3M__) ||  \
     defined(__ARM_ARCH_4__) || defined(__ARM_ARCH_4T__) ||  \
     defined(__ARM_ARCH_5__) || defined(__ARM_ARCH_5TE__) || \
     defined(__ARM_ARCH_5TEJ__))
    int result;
#ifdef SDL_PLATFORM_RISCOS
    if (__cpucap_have_rex()) {
        __asm__ __volatile__(
            "ldrex %0, [%2]\nteq   %0, #0\nstrexeq %0, %1, [%2]"
            : "=&r"(result)
            : "r"(1), "r"(lock)
            : "cc", "memory");
        return result == 0;
    }
#endif
    __asm__ __volatile__(
        "swp %0, %1, [%2]\n"
        : "=&r,&r"(result)
        : "r,0"(1), "r,r"(lock)
        : "memory");
    return result == 0;
#elif defined(__GNUC__) && defined(__arm__)
    int result;
    __asm__ __volatile__(
        "ldrex %0, [%2]\nteq   %0, #0\nstrexeq %0, %1, [%2]"
        : "=&r"(result)
        : "r"(1), "r"(lock)
        : "cc", "memory");
    return result == 0;
#elif defined(__GNUC__) && (defined(__i386__) || defined(__x86_64__))
    int result;
    __asm__ __volatile__(
        "lock ; xchgl %0, (%1)\n"
        : "=r"(result)
        : "r"(lock), "0"(1)
        : "cc", "memory");
    return result == 0;
#elif defined(SDL_PLATFORM_MACOS) || defined(SDL_PLATFORM_IOS) || defined(SDL_PLATFORM_TVOS)
    // Maybe used for PowerPC, but the Intel asm or gcc atomics are favored.
    return OSAtomicCompareAndSwap32Barrier(0, 1, lock);
#elif defined(SDL_PLATFORM_SOLARIS) && defined(_LP64)
    // Used for Solaris with non-gcc compilers.
    return ((int)atomic_cas_64((volatile uint64_t *)lock, 0, 1) == 0);
#elif defined(SDL_PLATFORM_SOLARIS) && !defined(_LP64)
    // Used for Solaris with non-gcc compilers.
    return ((int)atomic_cas_32((volatile uint32_t *)lock, 0, 1) == 0);
#elif defined(PS2)
    uint32_t oldintr;
    bool res = false;
    // disable interruption
    oldintr = DIntr();
    if (*lock == 0) {
        *lock = 1;
        res = true;
    }
    // enable interruption
    if (oldintr) {
        EIntr();
    }
    return res;
#else
    // Terrible terrible damage
    static SDL_Mutex *_spinlock_mutex;
    if (!_spinlock_mutex) {
        // Race condition on first lock...
        _spinlock_mutex = SDL_CreateMutex();
    }
    SDL_LockMutex(_spinlock_mutex);
    if (*lock == 0) {
        *lock = 1;
        SDL_UnlockMutex(_spinlock_mutex);
        return true;
    } else {
        SDL_UnlockMutex(_spinlock_mutex);
        return false;
    }
#endif
}
References lock, SDL_COMPILE_TIME_ASSERT, SDL_CreateMutex(), SDL_LockMutex(), and SDL_UnlockMutex().
Referenced by SDL_LockSpinlock().
SDL_UnlockSpinlock()
void SDL_UnlockSpinlock (SDL_SpinLock * lock)
Unlock a spin lock by setting it to 0.
Always returns immediately.
Please note that spinlocks are dangerous if you don't know what you're doing. Please be careful using any sort of spinlock!
Parameters
lock a pointer to a lock variable.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockSpinlock
SDL_TryLockSpinlock
{
#if defined(HAVE_GCC_ATOMICS) || defined(HAVE_GCC_SYNC_LOCK_TEST_AND_SET)
    __sync_lock_release(lock);
#elif defined(_MSC_VER) && (defined(_M_ARM) || defined(_M_ARM64))
    _InterlockedExchange_rel(lock, 0);
#elif defined(_MSC_VER)
    _ReadWriteBarrier();
    *lock = 0;
#elif defined(__WATCOMC__) && defined(__386__)
    SDL_CompilerBarrier();
    *lock = 0;
#elif defined(SDL_PLATFORM_SOLARIS)
    // Used for Solaris when not using gcc.
    *lock = 0;
    membar_producer();
#else
    *lock = 0;
#endif
}
References lock, and SDL_CompilerBarrier.
Referenced by leaveLock(), SDL_CreateTimer(), SDL_ReportAssertion(), and SDL_TimerThread().