SDL3: SDL-main/src/tray/SDL_tray_utils.h File Reference
SDL_tray_utils.h File Reference
#include "SDL_internal.h"
Functions
void SDL_CleanupTrays (void)
bool SDL_HasActiveTrays (void)
void SDL_RegisterTray (SDL_Tray *tray)
void SDL_UnregisterTray (SDL_Tray *tray)
Function Documentation
SDL_CleanupTrays()
void SDL_CleanupTrays (void) extern
{
    if (active_trays == 0) {
        return;
    }
    void **trays = (void **)SDL_malloc(active_trays * sizeof(*trays));
    if (!trays) {
        return;
    }
    int count = SDL_GetObjects(SDL_OBJECT_TYPE_TRAY, trays, active_trays);
    SDL_assert(count == active_trays);
    for (int i = 0; i < count; ++i) {
        SDL_DestroyTray((SDL_Tray *)trays[i]);
    }
    SDL_free(trays);
}
References active_trays, count, SDL_assert, SDL_DestroyTray(), SDL_free(), SDL_GetObjects(), SDL_malloc(), and SDL_OBJECT_TYPE_TRAY.
Referenced by SDL_Quit().
SDL_HasActiveTrays()
bool SDL_HasActiveTrays (void) extern
{
    return (active_trays > 0);
}
References active_trays.
Referenced by SDL_SendWindowEvent(), and SDL_UpdateTrays().
SDL_RegisterTray()
void SDL_RegisterTray (SDL_Tray * tray) extern
{
    SDL_SetObjectValid(tray, SDL_OBJECT_TYPE_TRAY, true);
    ++active_trays;
}
References active_trays, SDL_OBJECT_TYPE_TRAY, and SDL_SetObjectValid().
Referenced by SDL_CreateTray().
SDL_UnregisterTray()
void SDL_UnregisterTray (SDL_Tray * tray) extern
{
    SDL_assert(SDL_ObjectValid(tray, SDL_OBJECT_TYPE_TRAY));
    SDL_SetObjectValid(tray, SDL_OBJECT_TYPE_TRAY, false);
    --active_trays;
    if (active_trays > 0) {
        return;
    }
    if (!SDL_GetHintBoolean(SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE, true)) {
        return;
    }
    int toplevel_count = 0;
    SDL_Window **windows = SDL_GetWindows(NULL);
    if (windows) {
        for (int i = 0; windows[i]; ++i) {
            SDL_Window *window = windows[i];
            if (!window->parent && !(window->flags & SDL_WINDOW_HIDDEN)) {
                ++toplevel_count;
            }
        }
        SDL_free(windows);
    }
    if (toplevel_count == 0) {
        SDL_SendQuit();
    }
}
References active_trays, NULL, SDL_assert, SDL_free(), SDL_GetHintBoolean(), SDL_GetWindows(), SDL_HINT_QUIT_ON_LAST_WINDOW_CLOSE, SDL_OBJECT_TYPE_TRAY, SDL_ObjectValid(), SDL_SendQuit(), SDL_SetObjectValid(), and SDL_WINDOW_HIDDEN.
Referenced by SDL_DestroyTray().