SDL3: SDL-main/src/core/android/SDL_android.h File Reference
SDL_android.h File Reference
#include "SDL_internal.h"
#include <EGL/eglplatform.h>
#include <android/native_window_jni.h>
#include "../../audio/SDL_sysaudio.h"
#include <jni.h>
Macros
#define ALLOW_MULTIPLE_ANDROID_AUDIO_DEVICES 0
Enumerations
enum SDL_AndroidLifecycleEvent {
SDL_ANDROID_LIFECYCLE_WAKE , SDL_ANDROID_LIFECYCLE_PAUSE , SDL_ANDROID_LIFECYCLE_RESUME , SDL_ANDROID_LIFECYCLE_LOWMEMORY ,
SDL_ANDROID_LIFECYCLE_DESTROY , SDL_NUM_ANDROID_LIFECYCLE_EVENTS
}
Functions
void Android_AudioThreadInit (SDL_AudioDevice *device)
bool Android_IsChromebook (void)
bool Android_IsDeXMode (void)
int Android_JNI_CreateCustomCursor (SDL_Surface *surface, int hot_x, int hot_y)
void Android_JNI_DestroyCustomCursor (int cursorID)
bool Android_JNI_EnumerateAssetDirectory (const char *path, SDL_EnumerateDirectoryCallback cb, void *userdata)
bool Android_JNI_FileClose (void *userdata)
bool Android_JNI_FileOpen (void **puserdata, const char *fileName, const char *mode)
size_t Android_JNI_FileRead (void *userdata, void *buffer, size_t size, SDL_IOStatus *status)
Sint64 Android_JNI_FileSeek (void *userdata, Sint64 offset, SDL_IOWhence whence)
Sint64 Android_JNI_FileSize (void *userdata)
size_t Android_JNI_FileWrite (void *userdata, const void *buffer, size_t size, SDL_IOStatus *status)
bool Android_JNI_GetAccelerometerValues (float values[3])
bool Android_JNI_GetAssetPathInfo (const char *path, SDL_PathInfo *info)
char * Android_JNI_GetClipboardText (void)
SDL_DisplayOrientation Android_JNI_GetDisplayCurrentOrientation (void)
SDL_DisplayOrientation Android_JNI_GetDisplayNaturalOrientation (void)
JNIEnv * Android_JNI_GetEnv (void)
bool Android_JNI_GetLocale (char *buf, size_t buflen)
void Android_JNI_GetManifestEnvironmentVariables (void)
ANativeWindow * Android_JNI_GetNativeWindow (void)
int Android_JNI_GetPowerInfo (int *plugged, int *charged, int *battery, int *seconds, int *percent)
void Android_JNI_HapticRumble (int device_id, float low_frequency_intensity, float high_frequency_intensity, int length)
void Android_JNI_HapticRun (int device_id, float intensity, int length)
void Android_JNI_HapticStop (int device_id)
bool Android_JNI_HasClipboardText (void)
void Android_JNI_HideScreenKeyboard (void)
void Android_JNI_InitTouch (void)
bool Android_JNI_IsScreenKeyboardShown (void)
void Android_JNI_MinizeWindow (void)
int Android_JNI_OpenFileDescriptor (const char *uri, const char *mode)
bool Android_JNI_OpenFileDialog (SDL_DialogFileCallback callback, void *userdata, const SDL_DialogFileFilter *filters, int nfilters, bool forwrite, bool multiple)
bool Android_JNI_OpenURL (const char *url)
void Android_JNI_PollHapticDevices (void)
void Android_JNI_PollInputDevices (void)
bool Android_JNI_SendMessage (int command, int param)
void Android_JNI_SetActivityTitle (const char *title)
bool Android_JNI_SetClipboardText (const char *text)
bool Android_JNI_SetCustomCursor (int cursorID)
void Android_JNI_SetOrientation (int w, int h, int resizable, const char *hint)
bool Android_JNI_SetRelativeMouseEnabled (bool enabled)
bool Android_JNI_SetSystemCursor (int cursorID)
bool Android_JNI_SetupThread (void)
void Android_JNI_SetWindowStyle (bool fullscreen)
bool Android_JNI_ShouldMinimizeOnFocusLoss (void)
bool Android_JNI_ShowMessageBox (const SDL_MessageBoxData *messageboxdata, int *buttonID)
void Android_JNI_ShowScreenKeyboard (int input_type, SDL_Rect *inputRect)
bool Android_JNI_ShowToast (const char *message, int duration, int gravity, int xOffset, int yOffset)
bool Android_JNI_SupportsRelativeMouse (void)
bool Android_JNI_SuspendScreenSaver (bool suspend)
void Android_LockActivityMutex (void)
void Android_SendLifecycleEvent (SDL_AndroidLifecycleEvent event)
void Android_SetAllowRecreateActivity (bool enabled)
void Android_StartAudioHotplug (SDL_AudioDevice **default_playback, SDL_AudioDevice **default_recording)
void Android_StopAudioHotplug (void)
void Android_UnlockActivityMutex (void)
bool Android_WaitLifecycleEvent (SDL_AndroidLifecycleEvent *event, Sint64 timeoutNS)
int SDL_GetAndroidSDKVersion (void)
bool SDL_IsAndroidTablet (void)
bool SDL_IsAndroidTV (void)
Macro Definition Documentation
ALLOW_MULTIPLE_ANDROID_AUDIO_DEVICES
#define ALLOW_MULTIPLE_ANDROID_AUDIO_DEVICES 0
Enumeration Type Documentation
SDL_AndroidLifecycleEvent
enum SDL_AndroidLifecycleEvent
Enumerator
SDL_ANDROID_LIFECYCLE_WAKE
SDL_ANDROID_LIFECYCLE_PAUSE
SDL_ANDROID_LIFECYCLE_RESUME
SDL_ANDROID_LIFECYCLE_LOWMEMORY
SDL_ANDROID_LIFECYCLE_DESTROY
SDL_NUM_ANDROID_LIFECYCLE_EVENTS
{
    SDL_ANDROID_LIFECYCLE_WAKE,
    SDL_ANDROID_LIFECYCLE_PAUSE,
    SDL_ANDROID_LIFECYCLE_RESUME,
    SDL_ANDROID_LIFECYCLE_LOWMEMORY,
    SDL_ANDROID_LIFECYCLE_DESTROY,
    SDL_NUM_ANDROID_LIFECYCLE_EVENTS
} SDL_AndroidLifecycleEvent;
Function Documentation
Android_AudioThreadInit()
void Android_AudioThreadInit (SDL_AudioDevice * device) extern
Android_IsChromebook()
bool Android_IsChromebook (void) extern
Android_IsDeXMode()
bool Android_IsDeXMode (void) extern
Android_JNI_CreateCustomCursor()
int Android_JNI_CreateCustomCursor (SDL_Surface * surface, int hot_x, int hot_y)
Android_JNI_DestroyCustomCursor()
void Android_JNI_DestroyCustomCursor (int cursorID)
Android_JNI_EnumerateAssetDirectory()
bool Android_JNI_EnumerateAssetDirectory (const char * path, SDL_EnumerateDirectoryCallback cb, void * userdata)
Android_JNI_FileClose()
bool Android_JNI_FileClose (void * userdata)
Referenced by SDL_IOFromFile().
Android_JNI_FileOpen()
bool Android_JNI_FileOpen (void ** puserdata, const char * fileName, const char * mode)
Referenced by SDL_IOFromFile().
Android_JNI_FileRead()
size_t Android_JNI_FileRead (void * userdata, void * buffer, size_t size, SDL_IOStatus * status)
Referenced by SDL_IOFromFile().
Android_JNI_FileSeek()
Sint64 Android_JNI_FileSeek (void * userdata, Sint64 offset, SDL_IOWhence whence)
Referenced by SDL_IOFromFile().
Android_JNI_FileSize()
Sint64 Android_JNI_FileSize (void * userdata)
Referenced by SDL_IOFromFile().
Android_JNI_FileWrite()
size_t Android_JNI_FileWrite (void * userdata, const void * buffer, size_t size, SDL_IOStatus * status)
Referenced by SDL_IOFromFile().
Android_JNI_GetAccelerometerValues()
bool Android_JNI_GetAccelerometerValues (float values[3]) extern
Android_JNI_GetAssetPathInfo()
bool Android_JNI_GetAssetPathInfo (const char * path, SDL_PathInfo * info)
Android_JNI_GetClipboardText()
char * Android_JNI_GetClipboardText (void)
Android_JNI_GetDisplayCurrentOrientation()
SDL_DisplayOrientation Android_JNI_GetDisplayCurrentOrientation (void) extern
Android_JNI_GetDisplayNaturalOrientation()
SDL_DisplayOrientation Android_JNI_GetDisplayNaturalOrientation (void) extern
Android_JNI_GetEnv()
JNIEnv * Android_JNI_GetEnv (void)
Android_JNI_GetLocale()
bool Android_JNI_GetLocale (char * buf, size_t buflen)
Referenced by SDL_SYS_GetPreferredLocales().
Android_JNI_GetManifestEnvironmentVariables()
void Android_JNI_GetManifestEnvironmentVariables (void)
Referenced by SDL_CreateEnvironment().
Android_JNI_GetNativeWindow()
ANativeWindow * Android_JNI_GetNativeWindow (void) extern
Android_JNI_GetPowerInfo()
int Android_JNI_GetPowerInfo (int * plugged, int * charged, int * battery, int * seconds, int * percent)
Android_JNI_HapticRumble()
void Android_JNI_HapticRumble (int device_id, float low_frequency_intensity, float high_frequency_intensity, int length)
Android_JNI_HapticRun()
void Android_JNI_HapticRun (int device_id, float intensity, int length)
Android_JNI_HapticStop()
void Android_JNI_HapticStop (int device_id)
Android_JNI_HasClipboardText()
bool Android_JNI_HasClipboardText (void)
Android_JNI_HideScreenKeyboard()
void Android_JNI_HideScreenKeyboard (void) extern
Android_JNI_InitTouch()
void Android_JNI_InitTouch (void)
Android_JNI_IsScreenKeyboardShown()
bool Android_JNI_IsScreenKeyboardShown (void) extern
Android_JNI_MinizeWindow()
void Android_JNI_MinizeWindow (void) extern
Android_JNI_OpenFileDescriptor()
int Android_JNI_OpenFileDescriptor (const char * uri, const char * mode)
Referenced by SDL_IOFromFile().
Android_JNI_OpenFileDialog()
bool Android_JNI_OpenFileDialog (SDL_DialogFileCallback callback, void * userdata, const SDL_DialogFileFilter * filters, int nfilters, bool forwrite, bool multiple)
Referenced by SDL_SYS_ShowFileDialogWithProperties().
Android_JNI_OpenURL()
bool Android_JNI_OpenURL (const char * url)
Referenced by SDL_SYS_OpenURL().
Android_JNI_PollHapticDevices()
void Android_JNI_PollHapticDevices (void)
Android_JNI_PollInputDevices()
void Android_JNI_PollInputDevices (void)
Android_JNI_SendMessage()
bool Android_JNI_SendMessage (int command, int param)
Android_JNI_SetActivityTitle()
void Android_JNI_SetActivityTitle (const char * title) extern
Android_JNI_SetClipboardText()
bool Android_JNI_SetClipboardText (const char * text)
Android_JNI_SetCustomCursor()
bool Android_JNI_SetCustomCursor (int cursorID)
Android_JNI_SetOrientation()
void Android_JNI_SetOrientation (int w, int h, int resizable, const char * hint) extern
Android_JNI_SetRelativeMouseEnabled()
bool Android_JNI_SetRelativeMouseEnabled (bool enabled)
Android_JNI_SetSystemCursor()
bool Android_JNI_SetSystemCursor (int cursorID)
Android_JNI_SetupThread()
bool Android_JNI_SetupThread (void)
Referenced by RunThread().
Android_JNI_SetWindowStyle()
void Android_JNI_SetWindowStyle (bool fullscreen) extern
Android_JNI_ShouldMinimizeOnFocusLoss()
bool Android_JNI_ShouldMinimizeOnFocusLoss (void) extern
Referenced by SDL_ShouldMinimizeOnFocusLoss().
Android_JNI_ShowMessageBox()
bool Android_JNI_ShowMessageBox (const SDL_MessageBoxData * messageboxdata, int * buttonID)
Android_JNI_ShowScreenKeyboard()
void Android_JNI_ShowScreenKeyboard (int input_type, SDL_Rect * inputRect) extern
Android_JNI_ShowToast()
bool Android_JNI_ShowToast (const char * message, int duration, int gravity, int xOffset, int yOffset)
Android_JNI_SupportsRelativeMouse()
bool Android_JNI_SupportsRelativeMouse (void)
Android_JNI_SuspendScreenSaver()
bool Android_JNI_SuspendScreenSaver (bool suspend)
Android_LockActivityMutex()
void Android_LockActivityMutex (void)
Android_SendLifecycleEvent()
void Android_SendLifecycleEvent (SDL_AndroidLifecycleEvent event)
Referenced by SDL_SendWakeupEvent().
Android_SetAllowRecreateActivity()
void Android_SetAllowRecreateActivity (bool enabled)
Referenced by ResetHintsCallback(), SDL_ResetHint(), and SDL_SetHintWithPriority().
Android_StartAudioHotplug()
void Android_StartAudioHotplug (SDL_AudioDevice ** default_playback, SDL_AudioDevice ** default_recording)
Android_StopAudioHotplug()
void Android_StopAudioHotplug (void)
Android_UnlockActivityMutex()
void Android_UnlockActivityMutex (void)
Referenced by SDL_CreateRendererWithProperties().
Android_WaitLifecycleEvent()
bool Android_WaitLifecycleEvent (SDL_AndroidLifecycleEvent * event, Sint64 timeoutNS)
SDL_GetAndroidSDKVersion()
int SDL_GetAndroidSDKVersion (void)
{
    return SDL_Unsupported();
}
References SDL_Unsupported.
Referenced by PLATFORM_hid_init(), and SDL_PrivateAddGamepadMapping().
SDL_IsAndroidTablet()
bool SDL_IsAndroidTablet (void)
Referenced by SDL_IsTablet().
SDL_IsAndroidTV()
bool SDL_IsAndroidTV (void)
Referenced by SDL_IsTV().