SDL3: SDL-main/include/SDL3/SDL_system.h File Reference
SDL_system.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_keyboard.h>
#include <SDL3/SDL_video.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Typedefs
typedef enum SDL_Sandbox SDL_Sandbox
typedef bool(SDLCALL * SDL_X11EventHook) (void *userdata, XEvent *xevent)
typedef union _XEvent XEvent
Enumerations
enum SDL_Sandbox {
SDL_SANDBOX_NONE = 0 , SDL_SANDBOX_UNKNOWN_CONTAINER , SDL_SANDBOX_FLATPAK , SDL_SANDBOX_SNAP ,
SDL_SANDBOX_MACOS
}
Functions
SDL_DECLSPEC SDL_Sandbox SDLCALL SDL_GetSandbox (void)
SDL_DECLSPEC bool SDLCALL SDL_IsTablet (void)
SDL_DECLSPEC bool SDLCALL SDL_IsTV (void)
SDL_DECLSPEC void SDLCALL SDL_OnApplicationDidEnterBackground (void)
SDL_DECLSPEC void SDLCALL SDL_OnApplicationDidEnterForeground (void)
SDL_DECLSPEC void SDLCALL SDL_OnApplicationDidReceiveMemoryWarning (void)
SDL_DECLSPEC void SDLCALL SDL_OnApplicationWillEnterBackground (void)
SDL_DECLSPEC void SDLCALL SDL_OnApplicationWillEnterForeground (void)
SDL_DECLSPEC void SDLCALL SDL_OnApplicationWillTerminate (void)
SDL_DECLSPEC void SDLCALL SDL_SetX11EventHook (SDL_X11EventHook callback, void *userdata)
Typedef Documentation
SDL_Sandbox
typedef enum SDL_Sandbox SDL_Sandbox
Application sandbox environment.
Since
This enum is available since SDL 3.2.0.
SDL_X11EventHook
typedef bool(SDLCALL * SDL_X11EventHook) (void *userdata, XEvent *xevent)
A callback to be used with SDL_SetX11EventHook.
This callback may modify the event, and should return true if the event should continue to be processed, or false to prevent further processing.
As this is processing an event directly from the X11 event loop, this callback should do the minimum required work and return quickly.
Parameters
userdata the app-defined pointer provided to SDL_SetX11EventHook.
xevent a pointer to an Xlib XEvent union to process.
Returns
true to let event continue on, false to drop it.
Thread Safety
This may only be called (by SDL) from the thread handling the X11 event loop.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_SetX11EventHook
XEvent
typedef union _XEvent XEvent
CategorySystem
Platform-specific SDL API functions. These are functions that deal with needs of specific operating systems, that didn't make sense to offer as platform-independent, generic APIs.
Most apps can make do without these functions, but they can be useful for integrating with other parts of a specific system, adding platform-specific polish to an app, or solving problems that only affect one target.
Enumeration Type Documentation
SDL_Sandbox
enum SDL_Sandbox
Application sandbox environment.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_SANDBOX_NONE
SDL_SANDBOX_UNKNOWN_CONTAINER
SDL_SANDBOX_FLATPAK
SDL_SANDBOX_SNAP
SDL_SANDBOX_MACOS
{
    SDL_SANDBOX_NONE = 0,
    SDL_SANDBOX_UNKNOWN_CONTAINER,
    SDL_SANDBOX_FLATPAK,
    SDL_SANDBOX_SNAP,
    SDL_SANDBOX_MACOS
} SDL_Sandbox;
Function Documentation
SDL_GetSandbox()
SDL_DECLSPEC SDL_Sandbox SDLCALL SDL_GetSandbox (void) extern
Get the application sandbox environment, if any.
Returns
the application sandbox environment or SDL_SANDBOX_NONE if the application is not running in a sandbox environment.
Since
This function is available since SDL 3.2.0.
{
    static SDL_Sandbox sandbox;
    static bool sandbox_initialized;
    if (!sandbox_initialized) {
        sandbox = SDL_DetectSandbox();
        sandbox_initialized = true;
    }
    return sandbox;
}
References SDL_DetectSandbox().
Referenced by SDL_hid_init(), and SDL_InitSteamVirtualGamepadInfo().
SDL_IsTablet()
SDL_DECLSPEC bool SDLCALL SDL_IsTablet (void) extern
Query if the current device is a tablet.
If SDL can't determine this, it will return false.
Returns
true if the device is a tablet, false otherwise.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_PLATFORM_ANDROID
    return SDL_IsAndroidTablet();
#elif defined(SDL_PLATFORM_IOS)
    extern bool SDL_IsIPad(void);
    return SDL_IsIPad();
#else
    return false;
#endif
}
References SDL_IsAndroidTablet().
SDL_IsTV()
SDL_DECLSPEC bool SDLCALL SDL_IsTV (void) extern
Query if the current device is a TV.
If SDL can't determine this, it will return false.
Returns
true if the device is a TV, false otherwise.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_PLATFORM_ANDROID
    return SDL_IsAndroidTV();
#elif defined(SDL_PLATFORM_IOS)
    extern bool SDL_IsAppleTV(void);
    return SDL_IsAppleTV();
#else
    return false;
#endif
}
References SDL_IsAndroidTV().
SDL_OnApplicationDidEnterBackground()
SDL_DECLSPEC void SDLCALL SDL_OnApplicationDidEnterBackground (void) extern
Let iOS apps with external event handling report onApplicationDidEnterBackground.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_DID_ENTER_BACKGROUND);
}
References SDL_EVENT_DID_ENTER_BACKGROUND, and SDL_SendAppEvent().
SDL_OnApplicationDidEnterForeground()
SDL_DECLSPEC void SDLCALL SDL_OnApplicationDidEnterForeground (void) extern
Let iOS apps with external event handling report onApplicationDidBecomeActive.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_DID_ENTER_FOREGROUND);
    if (_this) {
        SDL_Window *window;
        for (window = _this->windows; window; window = window->next) {
            SDL_SetKeyboardFocus(window);
            SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_RESTORED, 0, 0);
        }
    }
}
References _this, SDL_EVENT_DID_ENTER_FOREGROUND, SDL_EVENT_WINDOW_RESTORED, SDL_SendAppEvent(), SDL_SendWindowEvent(), and SDL_SetKeyboardFocus().
Referenced by SDL_SendPendingSignalEvents().
SDL_OnApplicationDidReceiveMemoryWarning()
SDL_DECLSPEC void SDLCALL SDL_OnApplicationDidReceiveMemoryWarning (void) extern
Let iOS apps with external event handling report onApplicationDidReceiveMemoryWarning.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_LOW_MEMORY);
}
References SDL_EVENT_LOW_MEMORY, and SDL_SendAppEvent().
SDL_OnApplicationWillEnterBackground()
SDL_DECLSPEC void SDLCALL SDL_OnApplicationWillEnterBackground (void) extern
Let iOS apps with external event handling report onApplicationWillResignActive.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    if (_this) {
        SDL_Window *window;
        for (window = _this->windows; window; window = window->next) {
            SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_MINIMIZED, 0, 0);
        }
        SDL_SetKeyboardFocus(NULL);
    }
    SDL_SendAppEvent(SDL_EVENT_WILL_ENTER_BACKGROUND);
}
References _this, NULL, SDL_EVENT_WILL_ENTER_BACKGROUND, SDL_EVENT_WINDOW_MINIMIZED, SDL_SendAppEvent(), SDL_SendWindowEvent(), and SDL_SetKeyboardFocus().
Referenced by SDL_SendPendingSignalEvents().
SDL_OnApplicationWillEnterForeground()
SDL_DECLSPEC void SDLCALL SDL_OnApplicationWillEnterForeground (void) extern
Let iOS apps with external event handling report onApplicationWillEnterForeground.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_WILL_ENTER_FOREGROUND);
}
References SDL_EVENT_WILL_ENTER_FOREGROUND, and SDL_SendAppEvent().
SDL_OnApplicationWillTerminate()
SDL_DECLSPEC void SDLCALL SDL_OnApplicationWillTerminate (void) extern
Let iOS apps with external event handling report onApplicationWillTerminate.
This functions allows iOS apps that have their own event handling to hook into SDL to generate SDL events. This maps directly to an iOS-specific event, but since it doesn't do anything iOS-specific internally, it is available on all platforms, in case it might be useful for some specific paradigm. Most apps do not need to use this directly; SDL's internal event code will handle all this for windows created by SDL_CreateWindow!
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_SendAppEvent(SDL_EVENT_TERMINATING);
}
References SDL_EVENT_TERMINATING, and SDL_SendAppEvent().
SDL_SetX11EventHook()
void SDL_SetX11EventHook (SDL_X11EventHook callback, void * userdata) extern
Set a callback for every X11 event.
The callback may modify the event, and should return true if the event should continue to be processed, or false to prevent further processing.
Parameters
callback the SDL_X11EventHook function to call.
userdata a pointer to pass to every iteration of callback.
Since
This function is available since SDL 3.2.0.
{
}