SDL3: SDL-main/include/SDL3/SDL_iostream.h File Reference
SDL_iostream.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_IOStreamInterface
Typedefs
typedef enum SDL_IOStatus SDL_IOStatus
typedef struct SDL_IOStream SDL_IOStream
typedef struct SDL_IOStreamInterface SDL_IOStreamInterface
typedef enum SDL_IOWhence SDL_IOWhence
Enumerations
enum SDL_IOStatus {
SDL_IO_STATUS_READY , SDL_IO_STATUS_ERROR , SDL_IO_STATUS_EOF , SDL_IO_STATUS_NOT_READY ,
SDL_IO_STATUS_READONLY , SDL_IO_STATUS_WRITEONLY
}
enum SDL_IOWhence { SDL_IO_SEEK_SET , SDL_IO_SEEK_CUR , SDL_IO_SEEK_END }
Functions
SDL_COMPILE_TIME_ASSERT (SDL_IOStreamInterface_SIZE,(sizeof(void *)==4 &&sizeof(SDL_IOStreamInterface)==28)||(sizeof(void *)==8 &&sizeof(SDL_IOStreamInterface)==56))
Read endian functions
Read an item of the specified endianness and return in native format.
SDL_DECLSPEC bool SDLCALL SDL_ReadS16BE (SDL_IOStream *src, Sint16 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadS16LE (SDL_IOStream *src, Sint16 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadS32BE (SDL_IOStream *src, Sint32 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadS32LE (SDL_IOStream *src, Sint32 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadS64BE (SDL_IOStream *src, Sint64 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadS64LE (SDL_IOStream *src, Sint64 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadS8 (SDL_IOStream *src, Sint8 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadU16BE (SDL_IOStream *src, Uint16 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadU16LE (SDL_IOStream *src, Uint16 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadU32BE (SDL_IOStream *src, Uint32 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadU32LE (SDL_IOStream *src, Uint32 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadU64BE (SDL_IOStream *src, Uint64 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadU64LE (SDL_IOStream *src, Uint64 *value)
SDL_DECLSPEC bool SDLCALL SDL_ReadU8 (SDL_IOStream *src, Uint8 *value)
Write endian functions
Write an item of native format to the specified endianness.
SDL_DECLSPEC bool SDLCALL SDL_WriteS16BE (SDL_IOStream *dst, Sint16 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteS16LE (SDL_IOStream *dst, Sint16 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteS32BE (SDL_IOStream *dst, Sint32 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteS32LE (SDL_IOStream *dst, Sint32 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteS64BE (SDL_IOStream *dst, Sint64 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteS64LE (SDL_IOStream *dst, Sint64 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteS8 (SDL_IOStream *dst, Sint8 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteU16BE (SDL_IOStream *dst, Uint16 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteU16LE (SDL_IOStream *dst, Uint16 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteU32BE (SDL_IOStream *dst, Uint32 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteU32LE (SDL_IOStream *dst, Uint32 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteU64BE (SDL_IOStream *dst, Uint64 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteU64LE (SDL_IOStream *dst, Uint64 value)
SDL_DECLSPEC bool SDLCALL SDL_WriteU8 (SDL_IOStream *dst, Uint8 value)
IOFrom functions
Functions to create SDL_IOStream structures from various data streams.
SDL_DECLSPEC bool SDLCALL SDL_CloseIO (SDL_IOStream *context)
SDL_DECLSPEC bool SDLCALL SDL_FlushIO (SDL_IOStream *context)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetIOProperties (SDL_IOStream *context)
SDL_DECLSPEC Sint64 SDLCALL SDL_GetIOSize (SDL_IOStream *context)
SDL_DECLSPEC SDL_IOStatus SDLCALL SDL_GetIOStatus (SDL_IOStream *context)
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromConstMem (const void *mem, size_t size)
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromDynamicMem (void)
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromFile (const char *file, const char *mode)
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromMem (void *mem, size_t size)
SDL_DECLSPEC size_t SDLCALL SDL_IOprintf (SDL_IOStream *context, SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(2)
SDL_DECLSPEC size_t SDLCALL SDL_IOvprintf (SDL_IOStream *context, SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap) SDL_PRINTF_VARARG_FUNCV(2)
SDL_DECLSPEC void *SDLCALL SDL_LoadFile (const char *file, size_t *datasize)
SDL_DECLSPEC void *SDLCALL SDL_LoadFile_IO (SDL_IOStream *src, size_t *datasize, bool closeio)
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_OpenIO (const SDL_IOStreamInterface *iface, void *userdata)
#define SDL_PROP_IOSTREAM_ANDROID_AASSET_POINTER "SDL.iostream.android.aasset"
#define SDL_PROP_IOSTREAM_DYNAMIC_CHUNKSIZE_NUMBER "SDL.iostream.dynamic.chunksize"
#define SDL_PROP_IOSTREAM_DYNAMIC_MEMORY_POINTER "SDL.iostream.dynamic.memory"
#define SDL_PROP_IOSTREAM_FILE_DESCRIPTOR_NUMBER "SDL.iostream.file_descriptor"
#define SDL_PROP_IOSTREAM_MEMORY_FREE_FUNC_POINTER "SDL.iostream.memory.free"
#define SDL_PROP_IOSTREAM_MEMORY_POINTER "SDL.iostream.memory.base"
#define SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER "SDL.iostream.memory.size"
#define SDL_PROP_IOSTREAM_STDIO_FILE_POINTER "SDL.iostream.stdio.file"
#define SDL_PROP_IOSTREAM_WINDOWS_HANDLE_POINTER "SDL.iostream.windows.handle"
SDL_DECLSPEC size_t SDLCALL SDL_ReadIO (SDL_IOStream *context, void *ptr, size_t size)
SDL_DECLSPEC bool SDLCALL SDL_SaveFile (const char *file, const void *data, size_t datasize)
SDL_DECLSPEC bool SDLCALL SDL_SaveFile_IO (SDL_IOStream *src, const void *data, size_t datasize, bool closeio)
SDL_DECLSPEC Sint64 SDLCALL SDL_SeekIO (SDL_IOStream *context, Sint64 offset, SDL_IOWhence whence)
SDL_DECLSPEC Sint64 SDLCALL SDL_TellIO (SDL_IOStream *context)
SDL_DECLSPEC size_t SDLCALL SDL_WriteIO (SDL_IOStream *context, const void *ptr, size_t size)
Macro Definition Documentation
SDL_PROP_IOSTREAM_ANDROID_AASSET_POINTER
#define SDL_PROP_IOSTREAM_ANDROID_AASSET_POINTER "SDL.iostream.android.aasset"
Referenced by SDL_IOFromFile().
SDL_PROP_IOSTREAM_DYNAMIC_CHUNKSIZE_NUMBER
#define SDL_PROP_IOSTREAM_DYNAMIC_CHUNKSIZE_NUMBER "SDL.iostream.dynamic.chunksize"
Referenced by dynamic_mem_realloc().
SDL_PROP_IOSTREAM_DYNAMIC_MEMORY_POINTER
#define SDL_PROP_IOSTREAM_DYNAMIC_MEMORY_POINTER "SDL.iostream.dynamic.memory"
Referenced by dynamic_mem_close(), and dynamic_mem_realloc().
SDL_PROP_IOSTREAM_FILE_DESCRIPTOR_NUMBER
#define SDL_PROP_IOSTREAM_FILE_DESCRIPTOR_NUMBER "SDL.iostream.file_descriptor"
Referenced by SDL_IOFromFD().
SDL_PROP_IOSTREAM_MEMORY_FREE_FUNC_POINTER
#define SDL_PROP_IOSTREAM_MEMORY_FREE_FUNC_POINTER "SDL.iostream.memory.free"
Referenced by mem_close().
SDL_PROP_IOSTREAM_MEMORY_POINTER
#define SDL_PROP_IOSTREAM_MEMORY_POINTER "SDL.iostream.memory.base"
Referenced by SDL_IOFromConstMem(), and SDL_IOFromMem().
SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER
#define SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER "SDL.iostream.memory.size"
Referenced by SDL_IOFromConstMem(), and SDL_IOFromMem().
SDL_PROP_IOSTREAM_STDIO_FILE_POINTER
#define SDL_PROP_IOSTREAM_STDIO_FILE_POINTER "SDL.iostream.stdio.file"
SDL_PROP_IOSTREAM_WINDOWS_HANDLE_POINTER
#define SDL_PROP_IOSTREAM_WINDOWS_HANDLE_POINTER "SDL.iostream.windows.handle"
Typedef Documentation
SDL_IOStatus
typedef enum SDL_IOStatus SDL_IOStatus
CategoryIOStream
SDL provides an abstract interface for reading and writing data streams. It offers implementations for files, memory, etc, and the app can provide their own implementations, too.
SDL_IOStream is not related to the standard C++ iostream class, other than both are abstract interfaces to read/write data. SDL_IOStream status, set by a read or write operation.
Since
This enum is available since SDL 3.2.0.
SDL_IOStream
typedef struct SDL_IOStream SDL_IOStream
The read/write operation structure.
This operates as an opaque handle. There are several APIs to create various types of I/O streams, or an app can supply an SDL_IOStreamInterface to SDL_OpenIO() to provide their own stream implementation behind this struct's abstract interface.
Since
This struct is available since SDL 3.2.0.
SDL_IOStreamInterface
typedef struct SDL_IOStreamInterface SDL_IOStreamInterface
The function pointers that drive an SDL_IOStream.
Applications can provide this struct to SDL_OpenIO() to create their own implementation of SDL_IOStream. This is not necessarily required, as SDL already offers several common types of I/O streams, via functions like SDL_IOFromFile() and SDL_IOFromMem().
This structure should be initialized using SDL_INIT_INTERFACE()
Since
This struct is available since SDL 3.2.0.
See also
SDL_INIT_INTERFACE
SDL_IOWhence
typedef enum SDL_IOWhence SDL_IOWhence
Possible whence values for SDL_IOStream seeking.
These map to the same "whence" concept that fseek or lseek use in the standard C runtime.
Since
This enum is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_IOStatus
enum SDL_IOStatus
CategoryIOStream
SDL provides an abstract interface for reading and writing data streams. It offers implementations for files, memory, etc, and the app can provide their own implementations, too.
SDL_IOStream is not related to the standard C++ iostream class, other than both are abstract interfaces to read/write data. SDL_IOStream status, set by a read or write operation.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_IO_STATUS_READY
Everything is ready (no errors and not EOF).
SDL_IO_STATUS_ERROR
Read or write I/O error
SDL_IO_STATUS_EOF
End of file
SDL_IO_STATUS_NOT_READY
Non blocking I/O, not ready
SDL_IO_STATUS_READONLY
Tried to write a read-only buffer
SDL_IO_STATUS_WRITEONLY
Tried to read a write-only buffer
{
    SDL_IO_STATUS_READY,     /**< Everything is ready (no errors and not EOF). */
    SDL_IO_STATUS_ERROR,     /**< Read or write I/O error */
    SDL_IO_STATUS_EOF,       /**< End of file */
    SDL_IO_STATUS_NOT_READY, /**< Non blocking I/O, not ready */
    SDL_IO_STATUS_READONLY,  /**< Tried to write a read-only buffer */
    SDL_IO_STATUS_WRITEONLY  /**< Tried to read a write-only buffer */
} SDL_IOStatus;
SDL_IOWhence
enum SDL_IOWhence
Possible whence values for SDL_IOStream seeking.
These map to the same "whence" concept that fseek or lseek use in the standard C runtime.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_IO_SEEK_SET
Seek from the beginning of data
SDL_IO_SEEK_CUR
Seek relative to current read point
SDL_IO_SEEK_END
Seek relative to the end of data
{
    SDL_IO_SEEK_SET,  /**< Seek from the beginning of data */
    SDL_IO_SEEK_CUR,  /**< Seek relative to current read point */
    SDL_IO_SEEK_END   /**< Seek relative to the end of data */
} SDL_IOWhence;
Function Documentation
SDL_CloseIO()
SDL_DECLSPEC bool SDLCALL SDL_CloseIO (SDL_IOStream * context) extern
Close and free an allocated SDL_IOStream structure.
SDL_CloseIO() closes and cleans up the SDL_IOStream stream. It releases any resources used by the stream and frees the SDL_IOStream itself. This returns true on success, or false if the stream failed to flush to its output (e.g. to disk).
Note that if this fails to flush the stream for any reason, this function reports an error, but the SDL_IOStream is still invalid once this function returns.
This call flushes any buffered writes to the operating system, but there are no guarantees that those writes have gone to physical media; they might be in the OS's file cache, waiting to go to disk later. If it's absolutely crucial that writes go to disk immediately, so they are definitely stored even if the power fails before the file cache would have caught up, one should call SDL_FlushIO() before closing. Note that flushing takes time and makes the system and your app operate less efficiently, so do so sparingly.
Parameters
context SDL_IOStream structure to close.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenIO
{
    bool result = true;
    if (iostr) {
        if (iostr->iface.close) {
            result = iostr->iface.close(iostr->userdata);
        }
        SDL_DestroyProperties(iostr->props);
        SDL_free(iostr);
    }
    return result;
}
References SDL_IOStream::iface, SDL_IOStream::props, SDL_DestroyProperties(), SDL_free(), and SDL_IOStream::userdata.
Referenced by GENERIC_ReadStorageFile(), GENERIC_WriteStorageFile(), SDL_InternalGlobDirectory(), SDL_LoadBMP_IO(), SDL_LoadFile_IO(), SDL_LoadWAV_IO(), SDL_SaveBMP_IO(), SDL_SaveFile_IO(), SynchronousIO(), and WaveReadFormat().
SDL_COMPILE_TIME_ASSERT()
SDL_COMPILE_TIME_ASSERT (SDL_IOStreamInterface_SIZE , (sizeof(void *)==4 &&sizeof(SDL_IOStreamInterface)==28)||(sizeof(void *)==8 &&sizeof(SDL_IOStreamInterface)==56))
SDL_FlushIO()
SDL_DECLSPEC bool SDLCALL SDL_FlushIO (SDL_IOStream * context) extern
Flush any buffered data in the stream.
This function makes sure that any buffered data is written to the stream. Normally this isn't necessary but if the stream is a pipe or socket it guarantees that any pending data is sent.
Parameters
context SDL_IOStream structure to flush.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_OpenIO
SDL_WriteIO
{
    bool result = true;
    if (!context) {
        return SDL_InvalidParamError("context");
    }
    context->status = SDL_IO_STATUS_READY;
    SDL_ClearError();
    if (context->iface.flush) {
        result = context->iface.flush(context->userdata, &context->status);
    }
    if (!result && (context->status == SDL_IO_STATUS_READY)) {
        context->status = SDL_IO_STATUS_ERROR;
    }
    return result;
}
References context, SDL_ClearError(), SDL_InvalidParamError, SDL_IO_STATUS_ERROR, and SDL_IO_STATUS_READY.
Referenced by SynchronousIO().
SDL_GetIOProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetIOProperties (SDL_IOStream * context) extern
Get the properties associated with an SDL_IOStream.
Parameters
context a pointer to an SDL_IOStream structure.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    if (!context) {
        SDL_InvalidParamError("context");
        return 0;
    }
    if (context->props == 0) {
        context->props = SDL_CreateProperties();
    }
    return context->props;
}
References context, SDL_CreateProperties(), and SDL_InvalidParamError.
Referenced by dynamic_mem_close(), dynamic_mem_realloc(), SDL_IOFromConstMem(), SDL_IOFromFD(), SDL_IOFromFile(), and SDL_IOFromMem().
SDL_GetIOSize()
SDL_DECLSPEC Sint64 SDLCALL SDL_GetIOSize (SDL_IOStream * context) extern
Use this function to get the size of the data stream in an SDL_IOStream.
Parameters
context the SDL_IOStream to get the size of the data stream from.
Returns
the size of the data stream in the SDL_IOStream on success or a negative error code on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    if (!context) {
        return SDL_InvalidParamError("context");
    }
    if (!context->iface.size) {
        Sint64 pos, size;
        pos = SDL_SeekIO(context, 0, SDL_IO_SEEK_CUR);
        if (pos < 0) {
            return -1;
        }
        size = SDL_SeekIO(context, 0, SDL_IO_SEEK_END);
        SDL_SeekIO(context, pos, SDL_IO_SEEK_SET);
        return size;
    }
    return context->iface.size(context->userdata);
}
References context, SDL_InvalidParamError, SDL_IO_SEEK_CUR, SDL_IO_SEEK_END, SDL_IO_SEEK_SET, and SDL_SeekIO().
Referenced by generic_asyncio_size(), SDL_InternalGlobDirectory(), and SDL_LoadFile_IO().
SDL_GetIOStatus()
SDL_DECLSPEC SDL_IOStatus SDLCALL SDL_GetIOStatus (SDL_IOStream * context) extern
Query the stream status of an SDL_IOStream.
This information can be useful to decide if a short read or write was due to an error, an EOF, or a non-blocking operation that isn't yet ready to complete.
An SDL_IOStream's status is only expected to change after a SDL_ReadIO or SDL_WriteIO call; don't expect it to change if you just call this query function in a tight loop.
Parameters
context the SDL_IOStream to query.
Returns
an SDL_IOStatus enum with the current state.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    if (!context) {
        SDL_InvalidParamError("context");
        return SDL_IO_STATUS_ERROR;
    }
    return context->status;
}
References context, SDL_InvalidParamError, and SDL_IO_STATUS_ERROR.
Referenced by SDL_LoadFile_IO(), SDL_SaveFile_IO(), and SynchronousIO().
SDL_IOFromConstMem()
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromConstMem (const void * mem, size_t size) extern
Use this function to prepare a read-only memory buffer for use with SDL_IOStream.
This function sets up an SDL_IOStream struct based on a memory area of a certain size. It assumes the memory area is not writable.
Attempting to write to this SDL_IOStream stream will report an error without writing to the memory buffer.
This memory buffer is not copied by the SDL_IOStream; the pointer you provide must remain valid until you close the stream.
If you need to write to a memory buffer, you should use SDL_IOFromMem() with a writable buffer of memory instead.
The following properties will be set at creation time by SDL:
SDL_PROP_IOSTREAM_MEMORY_POINTER: this will be the mem parameter that was passed to this function.
SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER: this will be the size parameter that was passed to this function.
Additionally, the following properties are recognized:
SDL_PROP_IOSTREAM_MEMORY_FREE_FUNC_POINTER: if this property is set to a non-NULL value it will be interpreted as a function of SDL_free_func type and called with the passed mem pointer when closing the stream. By default it is unset, i.e., the memory will not be freed.
Parameters
mem a pointer to a read-only buffer to feed an SDL_IOStream stream.
size the buffer size, in bytes.
Returns
a pointer to a new SDL_IOStream structure or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_IOFromMem
SDL_CloseIO
SDL_ReadIO
SDL_SeekIO
SDL_TellIO
{
    if (!mem) {
        SDL_InvalidParamError("mem");
        return NULL;
    } else if (!size) {
        SDL_InvalidParamError("size");
        return NULL;
    }
    IOStreamMemData *iodata = (IOStreamMemData *) SDL_calloc(1, sizeof (*iodata));
    if (!iodata) {
        return NULL;
    }
    SDL_IOStreamInterface iface;
    SDL_INIT_INTERFACE(&iface);
    iface.size = mem_size;
    iface.seek = mem_seek;
    iface.read = mem_read;
    // leave iface.write as NULL.
    iface.close = mem_close;
    iodata->base = (Uint8 *)mem;
    iodata->here = iodata->base;
    iodata->stop = iodata->base + size;
    SDL_IOStream *iostr = SDL_OpenIO(&iface, iodata);
    if (!iostr) {
        SDL_free(iodata);
    } else {
        const SDL_PropertiesID props = SDL_GetIOProperties(iostr);
        if (props) {
            iodata->props = props;
            SDL_SetPointerProperty(props, SDL_PROP_IOSTREAM_MEMORY_POINTER, (void *)mem);
            SDL_SetNumberProperty(props, SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER, size);
        }
    }
    return iostr;
}
References IOStreamMemData::base, IOStreamMemData::here, mem_close(), mem_read(), mem_seek(), mem_size(), NULL, IOStreamMemData::props, SDL_calloc(), SDL_free(), SDL_GetIOProperties(), SDL_INIT_INTERFACE, SDL_InvalidParamError, SDL_OpenIO(), SDL_PROP_IOSTREAM_MEMORY_POINTER, SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER, SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_IOStreamInterface::size, and IOStreamMemData::stop.
Referenced by WaveReadFormat().
SDL_IOFromDynamicMem()
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromDynamicMem (void) extern
Use this function to create an SDL_IOStream that is backed by dynamically allocated memory.
This supports the following properties to provide access to the memory and control over allocations:
SDL_PROP_IOSTREAM_DYNAMIC_MEMORY_POINTER: a pointer to the internal memory of the stream. This can be set to NULL to transfer ownership of the memory to the application, which should free the memory with SDL_free(). If this is done, the next operation on the stream must be SDL_CloseIO().
SDL_PROP_IOSTREAM_DYNAMIC_CHUNKSIZE_NUMBER: memory will be allocated in multiples of this size, defaulting to 1024.
Returns
a pointer to a new SDL_IOStream structure or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseIO
SDL_ReadIO
SDL_SeekIO
SDL_TellIO
SDL_WriteIO
{
    IOStreamDynamicMemData *iodata = (IOStreamDynamicMemData *) SDL_calloc(1, sizeof (*iodata));
    if (!iodata) {
        return NULL;
    }
    SDL_IOStreamInterface iface;
    SDL_INIT_INTERFACE(&iface);
    iface.size = dynamic_mem_size;
    iface.seek = dynamic_mem_seek;
    iface.read = dynamic_mem_read;
    iface.write = dynamic_mem_write;
    iface.close = dynamic_mem_close;
    SDL_IOStream *iostr = SDL_OpenIO(&iface, iodata);
    if (iostr) {
        iodata->stream = iostr;
    } else {
        SDL_free(iodata);
    }
    return iostr;
}
References dynamic_mem_close(), dynamic_mem_read(), dynamic_mem_seek(), dynamic_mem_size(), dynamic_mem_write(), NULL, SDL_calloc(), SDL_free(), SDL_INIT_INTERFACE, SDL_OpenIO(), SDL_IOStreamInterface::size, and IOStreamDynamicMemData::stream.
Referenced by SDL_InternalGlobDirectory().
SDL_IOFromFile()
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromFile (const char * file, const char * mode) extern
Use this function to create a new SDL_IOStream structure for reading from and/or writing to a named file.
The mode string is treated roughly the same as in a call to the C library's fopen(), even if SDL doesn't happen to use fopen() behind the scenes.
Available mode strings:
"r": Open a file for reading. The file must exist.
"w": Create an empty file for writing. If a file with the same name already exists its content is erased and the file is treated as a new empty file.
"a": Append to a file. Writing operations append data at the end of the file. The file is created if it does not exist.
"r+": Open a file for update both reading and writing. The file must exist.
"w+": Create an empty file for both reading and writing. If a file with the same name already exists its content is erased and the file is treated as a new empty file.
"a+": Open a file for reading and appending. All writing operations are performed at the end of the file, protecting the previous content to be overwritten. You can reposition (fseek, rewind) the internal pointer to anywhere in the file for reading, but writing operations will move it back to the end of file. The file is created if it does not exist.
NOTE: In order to open a file as a binary file, a "b" character has to be included in the mode string. This additional "b" character can either be appended at the end of the string (thus making the following compound modes: "rb", "wb", "ab", "r+b", "w+b", "a+b") or be inserted between the letter and the "+" sign for the mixed modes ("rb+", "wb+", "ab+"). Additional characters may follow the sequence, although they should have no effect. For example, "t" is sometimes appended to make explicit the file is a text file.
This function supports Unicode filenames, but they must be encoded in UTF-8 format, regardless of the underlying operating system.
In Android, SDL_IOFromFile() can be used to open content:// URIs. As a fallback, SDL_IOFromFile() will transparently open a matching filename in the app's assets.
Closing the SDL_IOStream will close SDL's internal file handle.
The following properties may be set at creation time by SDL:
SDL_PROP_IOSTREAM_WINDOWS_HANDLE_POINTER: a pointer, that can be cast to a win32 HANDLE, that this SDL_IOStream is using to access the filesystem. If the program isn't running on Windows, or SDL used some other method to access the filesystem, this property will not be set.
SDL_PROP_IOSTREAM_STDIO_FILE_POINTER: a pointer, that can be cast to a stdio FILE *, that this SDL_IOStream is using to access the filesystem. If SDL used some other method to access the filesystem, this property will not be set. PLEASE NOTE that if SDL is using a different C runtime than your app, trying to use this pointer will almost certainly result in a crash! This is mostly a problem on Windows; make sure you build SDL and your app with the same compiler and settings to avoid it.
SDL_PROP_IOSTREAM_FILE_DESCRIPTOR_NUMBER: a file descriptor that this SDL_IOStream is using to access the filesystem.
SDL_PROP_IOSTREAM_ANDROID_AASSET_POINTER: a pointer, that can be cast to an Android NDK AAsset *, that this SDL_IOStream is using to access the filesystem. If SDL used some other method to access the filesystem, this property will not be set.
Parameters
file a UTF-8 string representing the filename to open.
mode an ASCII string representing the mode to be used for opening the file.
Returns
a pointer to the SDL_IOStream structure that is created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseIO
SDL_FlushIO
SDL_ReadIO
SDL_SeekIO
SDL_TellIO
SDL_WriteIO
{
    SDL_IOStream *iostr = NULL;
    if (!file || !*file) {
        SDL_InvalidParamError("file");
        return NULL;
    }
    if (!mode || !*mode) {
        SDL_InvalidParamError("mode");
        return NULL;
    }
#ifdef SDL_PLATFORM_ANDROID
#ifdef HAVE_STDIO_H
    // Try to open the file on the filesystem first
    if (*file == '/') {
        FILE *fp = fopen(file, mode);
        if (fp) {
            if (!IsRegularFileOrPipe(fp)) {
                fclose(fp);
                SDL_SetError("%s is not a regular file or pipe", file);
                return NULL;
            }
            return SDL_IOFromFP(fp, true);
        }
    } else if (SDL_strncmp(file, "content://", 10) == 0) {
        // Try opening content:// URI
        int fd = Android_JNI_OpenFileDescriptor(file, mode);
        if (fd == -1) {
            // SDL error is already set.
            return NULL;
        }
        FILE *fp = fdopen(fd, mode);
        if (!fp) {
            close(fd);
            SDL_SetError("Unable to open file descriptor (%d) from URI %s: %s", fd, file, strerror(errno));
            return NULL;
        }
        return SDL_IOFromFP(fp, true);
    } else {
        // Try opening it from internal storage if it's a relative path
        char *path = NULL;
        SDL_asprintf(&path, "%s/%s", SDL_GetAndroidInternalStoragePath(), file);
        if (path) {
            FILE *fp = fopen(path, mode);
            SDL_free(path);
            if (fp) {
                if (!IsRegularFileOrPipe(fp)) {
                    fclose(fp);
                    SDL_SetError("%s is not a regular file or pipe", path);
                    return NULL;
                }
                return SDL_IOFromFP(fp, true);
            }
        }
    }
#endif // HAVE_STDIO_H
    // Try to open the file from the asset system
    void *iodata = NULL;
    if (!Android_JNI_FileOpen(&iodata, file, mode)) {
        return NULL;
    }
    SDL_IOStreamInterface iface;
    SDL_INIT_INTERFACE(&iface);
    iface.size = Android_JNI_FileSize;
    iface.seek = Android_JNI_FileSeek;
    iface.read = Android_JNI_FileRead;
    iface.write = Android_JNI_FileWrite;
    iface.close = Android_JNI_FileClose;
    iostr = SDL_OpenIO(&iface, iodata);
    if (!iostr) {
        iface.close(iodata);
    } else {
        const SDL_PropertiesID props = SDL_GetIOProperties(iostr);
        if (props) {
            SDL_SetPointerProperty(props, SDL_PROP_IOSTREAM_ANDROID_AASSET_POINTER, iodata);
        }
    }
#elif defined(SDL_PLATFORM_WINDOWS)
    HANDLE handle = windows_file_open(file, mode);
    if (handle != INVALID_HANDLE_VALUE) {
        iostr = SDL_IOFromHandle(handle, mode, true);
    }
#elif defined(HAVE_STDIO_H)
    {
        #if defined(SDL_PLATFORM_3DS)
        FILE *fp = N3DS_FileOpen(file, mode);
        #else
        FILE *fp = fopen(file, mode);
        #endif
        if (!fp) {
            SDL_SetError("Couldn't open %s: %s", file, strerror(errno));
        } else if (!IsRegularFileOrPipe(fp)) {
            fclose(fp);
            fp = NULL;
            SDL_SetError("%s is not a regular file or pipe", file);
        } else {
            iostr = SDL_IOFromFP(fp, true);
        }
    }
#else
    SDL_SetError("SDL not compiled with stdio support");
#endif // !HAVE_STDIO_H
    return iostr;
}
References Android_JNI_FileClose(), Android_JNI_FileOpen(), Android_JNI_FileRead(), Android_JNI_FileSeek(), Android_JNI_FileSize(), Android_JNI_FileWrite(), Android_JNI_OpenFileDescriptor(), N3DS_FileOpen(), NULL, SDL_asprintf(), SDL_free(), SDL_GetAndroidInternalStoragePath(), SDL_GetIOProperties(), SDL_INIT_INTERFACE, SDL_InvalidParamError, SDL_OpenIO(), SDL_PROP_IOSTREAM_ANDROID_AASSET_POINTER, SDL_SetError(), SDL_SetPointerProperty(), SDL_strncmp(), and SDL_IOStreamInterface::size.
Referenced by GENERIC_ReadStorageFile(), GENERIC_WriteStorageFile(), SDL_AddGamepadMappingsFromFile(), SDL_LoadBMP(), SDL_LoadFile(), SDL_LoadWAV(), SDL_SaveBMP(), SDL_SaveFile(), and SDL_SYS_AsyncIOFromFile_Generic().
SDL_IOFromMem()
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_IOFromMem (void * mem, size_t size) extern
Use this function to prepare a read-write memory buffer for use with SDL_IOStream.
This function sets up an SDL_IOStream struct based on a memory area of a certain size, for both read and write access.
This memory buffer is not copied by the SDL_IOStream; the pointer you provide must remain valid until you close the stream.
If you need to make sure the SDL_IOStream never writes to the memory buffer, you should use SDL_IOFromConstMem() with a read-only buffer of memory instead.
The following properties will be set at creation time by SDL:
SDL_PROP_IOSTREAM_MEMORY_POINTER: this will be the mem parameter that was passed to this function.
SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER: this will be the size parameter that was passed to this function.
Additionally, the following properties are recognized:
SDL_PROP_IOSTREAM_MEMORY_FREE_FUNC_POINTER: if this property is set to a non-NULL value it will be interpreted as a function of SDL_free_func type and called with the passed mem pointer when closing the stream. By default it is unset, i.e., the memory will not be freed.
Parameters
mem a pointer to a buffer to feed an SDL_IOStream stream.
size the buffer size, in bytes.
Returns
a pointer to a new SDL_IOStream structure or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_IOFromConstMem
SDL_CloseIO
SDL_FlushIO
SDL_ReadIO
SDL_SeekIO
SDL_TellIO
SDL_WriteIO
{
    if (!mem) {
        SDL_InvalidParamError("mem");
        return NULL;
    } else if (!size) {
        SDL_InvalidParamError("size");
        return NULL;
    }
    IOStreamMemData *iodata = (IOStreamMemData *) SDL_calloc(1, sizeof (*iodata));
    if (!iodata) {
        return NULL;
    }
    SDL_IOStreamInterface iface;
    SDL_INIT_INTERFACE(&iface);
    iface.size = mem_size;
    iface.seek = mem_seek;
    iface.read = mem_read;
    iface.write = mem_write;
    iface.close = mem_close;
    iodata->base = (Uint8 *)mem;
    iodata->here = iodata->base;
    iodata->stop = iodata->base + size;
    SDL_IOStream *iostr = SDL_OpenIO(&iface, iodata);
    if (!iostr) {
        SDL_free(iodata);
    } else {
        const SDL_PropertiesID props = SDL_GetIOProperties(iostr);
        if (props) {
            iodata->props = props;
            SDL_SetPointerProperty(props, SDL_PROP_IOSTREAM_MEMORY_POINTER, mem);
            SDL_SetNumberProperty(props, SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER, size);
        }
    }
    return iostr;
}
References IOStreamMemData::base, IOStreamMemData::here, mem_close(), mem_read(), mem_seek(), mem_size(), mem_write(), NULL, IOStreamMemData::props, SDL_calloc(), SDL_free(), SDL_GetIOProperties(), SDL_INIT_INTERFACE, SDL_InvalidParamError, SDL_OpenIO(), SDL_PROP_IOSTREAM_MEMORY_POINTER, SDL_PROP_IOSTREAM_MEMORY_SIZE_NUMBER, SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_IOStreamInterface::size, and IOStreamMemData::stop.
SDL_IOprintf()
SDL_DECLSPEC size_t SDLCALL SDL_IOprintf (SDL_IOStream * context, SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
Print to an SDL_IOStream data stream.
This function does formatted printing to the stream.
Parameters
context a pointer to an SDL_IOStream structure.
fmt a printf() style format string.
... additional parameters matching % tokens in the fmt string, if any.
Returns
the number of bytes written or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_IOvprintf
SDL_WriteIO
{
    va_list ap;
    int size;
    char *string;
    size_t bytes;
    va_start(ap, fmt);
    size = SDL_vasprintf(&string, fmt, ap);
    va_end(ap);
    if (size < 0) {
        return 0;
    }
    bytes = SDL_WriteIO(context, string, (size_t)size);
    SDL_free(string);
    return bytes;
}
References context, SDL_free(), SDL_PRINTF_FORMAT_STRING, SDL_vasprintf(), and SDL_WriteIO().
SDL_IOvprintf()
SDL_DECLSPEC size_t SDLCALL SDL_IOvprintf (SDL_IOStream * context, SDL_PRINTF_FORMAT_STRING const char * fmt, va_list ap) extern
Print to an SDL_IOStream data stream.
This function does formatted printing to the stream.
Parameters
context a pointer to an SDL_IOStream structure.
fmt a printf() style format string.
ap a variable argument list.
Returns
the number of bytes written or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_IOprintf
SDL_WriteIO
{
    int size;
    char *string;
    size_t bytes;
    size = SDL_vasprintf(&string, fmt, ap);
    if (size < 0) {
        return 0;
    }
    bytes = SDL_WriteIO(context, string, (size_t)size);
    SDL_free(string);
    return bytes;
}
References context, SDL_free(), SDL_PRINTF_FORMAT_STRING, SDL_vasprintf(), and SDL_WriteIO().
SDL_LoadFile()
SDL_DECLSPEC void *SDLCALL SDL_LoadFile (const char * file, size_t * datasize) extern
Load all the data from a file path.
The data is allocated with a zero byte at the end (null terminated) for convenience. This extra byte is not included in the value reported via datasize.
The data should be freed with SDL_free().
Parameters
file the path to read all available data from.
datasize if not NULL, will store the number of bytes read.
Returns
the data or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_LoadFile_IO
SDL_SaveFile
{
    SDL_IOStream *stream = SDL_IOFromFile(file, "rb");
    if (!stream) {
        if (datasize) {
            *datasize = 0;
        }
        return NULL;
    }
    return SDL_LoadFile_IO(stream, datasize, true);
}
References NULL, SDL_IOFromFile(), and SDL_LoadFile_IO().
Referenced by SDL_LoadVIDPIDListFromHint(), and SDL_UpdateSteamVirtualGamepadInfo().
SDL_LoadFile_IO()
SDL_DECLSPEC void *SDLCALL SDL_LoadFile_IO (SDL_IOStream * src, size_t * datasize, bool closeio) extern
Load all the data from an SDL data stream.
The data is allocated with a zero byte at the end (null terminated) for convenience. This extra byte is not included in the value reported via datasize.
The data should be freed with SDL_free().
Parameters
src the SDL_IOStream to read all available data from.
datasize a pointer filled in with the number of bytes read, may be NULL.
closeio if true, calls SDL_CloseIO() on src before returning, even in the case of an error.
Returns
the data or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_LoadFile
SDL_SaveFile_IO
{
    const int FILE_CHUNK_SIZE = 1024;
    Sint64 size, size_total = 0;
    size_t size_read;
    char *data = NULL, *newdata;
    bool loading_chunks = false;
    if (!src) {
        SDL_InvalidParamError("src");
        goto done;
    }
    size = SDL_GetIOSize(src);
    if (size < 0) {
        size = FILE_CHUNK_SIZE;
        loading_chunks = true;
    }
    if (size >= SDL_SIZE_MAX - 1) {
        goto done;
    }
    data = (char *)SDL_malloc((size_t)(size + 1));
    if (!data) {
        goto done;
    }
    size_total = 0;
    for (;;) {
        if (loading_chunks) {
            if ((size_total + FILE_CHUNK_SIZE) > size) {
                size = (size_total + FILE_CHUNK_SIZE);
                if (size >= SDL_SIZE_MAX - 1) {
                    newdata = NULL;
                } else {
                    newdata = (char *)SDL_realloc(data, (size_t)(size + 1));
                }
                if (!newdata) {
                    SDL_free(data);
                    data = NULL;
                    goto done;
                }
                data = newdata;
            }
        }
        size_read = SDL_ReadIO(src, data + size_total, (size_t)(size - size_total));
        if (size_read > 0) {
            size_total += size_read;
            continue;
        } else if (SDL_GetIOStatus(src) == SDL_IO_STATUS_NOT_READY) {
            // Wait for the stream to be ready
            SDL_Delay(1);
            continue;
        }
        // The stream status will remain set for the caller to check
        break;
    }
    data[size_total] = '\0';
done:
    if (datasize) {
        *datasize = (size_t)size_total;
    }
    if (closeio && src) {
        SDL_CloseIO(src);
    }
    return data;
}
References NULL, SDL_CloseIO(), SDL_Delay(), SDL_free(), SDL_GetIOSize(), SDL_GetIOStatus(), SDL_InvalidParamError, SDL_IO_STATUS_NOT_READY, SDL_malloc(), SDL_ReadIO(), SDL_realloc(), and SDL_SIZE_MAX.
Referenced by SDL_AddGamepadMappingsFromIO(), SDL_LoadFile(), and SDL_ReadProcess().
SDL_OpenIO()
SDL_DECLSPEC SDL_IOStream *SDLCALL SDL_OpenIO (const SDL_IOStreamInterface * iface, void * userdata) extern
Create a custom SDL_IOStream.
Applications do not need to use this function unless they are providing their own SDL_IOStream implementation. If you just need an SDL_IOStream to read/write a common data source, you should use the built-in implementations in SDL, like SDL_IOFromFile() or SDL_IOFromMem(), etc.
This function makes a copy of iface and the caller does not need to keep it around after this call.
Parameters
iface the interface that implements this SDL_IOStream, initialized using SDL_INIT_INTERFACE().
userdata the pointer that will be passed to the interface functions.
Returns
a pointer to the allocated memory on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CloseIO
SDL_INIT_INTERFACE
SDL_IOFromConstMem
SDL_IOFromFile
SDL_IOFromMem
{
    if (!iface) {
        SDL_InvalidParamError("iface");
        return NULL;
    }
    if (iface->version < sizeof(*iface)) {
        // Update this to handle older versions of this interface
        SDL_SetError("Invalid interface, should be initialized with SDL_INIT_INTERFACE()");
        return NULL;
    }
    SDL_IOStream *iostr = (SDL_IOStream *)SDL_calloc(1, sizeof(*iostr));
    if (iostr) {
        SDL_copyp(&iostr->iface, iface);
        iostr->userdata = userdata;
    }
    return iostr;
}
References SDL_IOStream::iface, NULL, SDL_calloc(), SDL_copyp, SDL_InvalidParamError, SDL_SetError(), SDL_IOStream::userdata, and SDL_IOStreamInterface::version.
Referenced by SDL_IOFromConstMem(), SDL_IOFromDynamicMem(), SDL_IOFromFD(), SDL_IOFromFile(), and SDL_IOFromMem().
SDL_ReadIO()
SDL_DECLSPEC size_t SDLCALL SDL_ReadIO (SDL_IOStream * context, void * ptr, size_t size) extern
Read from a data source.
This function reads up size bytes from the data source to the area pointed at by ptr. This function may read less bytes than requested.
This function will return zero when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If zero is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
context a pointer to an SDL_IOStream structure.
ptr a pointer to a buffer to read data into.
size the number of bytes to read from the data source.
Returns
the number of bytes read, or 0 on end of file or other failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_WriteIO
SDL_GetIOStatus
{
    size_t bytes;
    if (!context) {
        SDL_InvalidParamError("context");
        return 0;
    } else if (!context->iface.read) {
        context->status = SDL_IO_STATUS_WRITEONLY;
        SDL_Unsupported();
        return 0;
    }
    context->status = SDL_IO_STATUS_READY;
    SDL_ClearError();
    if (size == 0) {
        return 0;
    }
    bytes = context->iface.read(context->userdata, ptr, size, &context->status);
    if (bytes == 0 && context->status == SDL_IO_STATUS_READY) {
        if (*SDL_GetError()) {
            context->status = SDL_IO_STATUS_ERROR;
        } else {
            context->status = SDL_IO_STATUS_EOF;
        }
    }
    return bytes;
}
References context, SDL_ClearError(), SDL_GetError(), SDL_InvalidParamError, SDL_IO_STATUS_EOF, SDL_IO_STATUS_ERROR, SDL_IO_STATUS_READY, SDL_IO_STATUS_WRITEONLY, and SDL_Unsupported.
Referenced by GENERIC_ReadStorageFile(), SDL_InternalGlobDirectory(), SDL_LoadBMP_IO(), SDL_LoadFile_IO(), SDL_ReadS8(), SDL_ReadU16BE(), SDL_ReadU16LE(), SDL_ReadU32BE(), SDL_ReadU32LE(), SDL_ReadU64BE(), SDL_ReadU64LE(), SDL_ReadU8(), SynchronousIO(), WaveNextChunk(), WaveReadFormat(), and WaveReadPartialChunkData().
SDL_ReadS16BE()
SDL_DECLSPEC bool SDLCALL SDL_ReadS16BE (SDL_IOStream * src, Sint16 * value) extern
Use this function to read 16 bits of big-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_ReadU16BE(src, (Uint16 *)value);
}
References SDL_ReadU16BE().
SDL_ReadS16LE()
SDL_DECLSPEC bool SDLCALL SDL_ReadS16LE (SDL_IOStream * src, Sint16 * value) extern
Use this function to read 16 bits of little-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_ReadU16LE(src, (Uint16 *)value);
}
References SDL_ReadU16LE().
SDL_ReadS32BE()
SDL_DECLSPEC bool SDLCALL SDL_ReadS32BE (SDL_IOStream * src, Sint32 * value) extern
Use this function to read 32 bits of big-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_ReadU32BE(src, (Uint32 *)value);
}
References SDL_ReadU32BE().
SDL_ReadS32LE()
SDL_DECLSPEC bool SDLCALL SDL_ReadS32LE (SDL_IOStream * src, Sint32 * value) extern
Use this function to read 32 bits of little-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_ReadU32LE(src, (Uint32 *)value);
}
References SDL_ReadU32LE().
Referenced by SDL_LoadBMP_IO().
SDL_ReadS64BE()
SDL_DECLSPEC bool SDLCALL SDL_ReadS64BE (SDL_IOStream * src, Sint64 * value) extern
Use this function to read 64 bits of big-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_ReadU64BE(src, (Uint64 *)value);
}
References SDL_ReadU64BE().
SDL_ReadS64LE()
SDL_DECLSPEC bool SDLCALL SDL_ReadS64LE (SDL_IOStream * src, Sint64 * value) extern
Use this function to read 64 bits of little-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_ReadU64LE(src, (Uint64 *)value);
}
References SDL_ReadU64LE().
SDL_ReadS8()
SDL_DECLSPEC bool SDLCALL SDL_ReadS8 (SDL_IOStream * src, Sint8 * value) extern
Use this function to read a signed byte from an SDL_IOStream.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the SDL_IOStream to read from.
value a pointer filled in with the data read.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Sint8 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = data;
    }
    return result;
}
References SDL_ReadIO().
SDL_ReadU16BE()
SDL_DECLSPEC bool SDLCALL SDL_ReadU16BE (SDL_IOStream * src, Uint16 * value) extern
Use this function to read 16 bits of big-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint16 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = SDL_Swap16BE(data);
    }
    return result;
}
References SDL_ReadIO(), and SDL_Swap16BE.
Referenced by SDL_ReadS16BE().
SDL_ReadU16LE()
SDL_DECLSPEC bool SDLCALL SDL_ReadU16LE (SDL_IOStream * src, Uint16 * value) extern
Use this function to read 16 bits of little-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint16 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = SDL_Swap16LE(data);
    }
    return result;
}
References SDL_ReadIO(), and SDL_Swap16LE.
Referenced by SDL_LoadBMP_IO(), SDL_ReadS16LE(), and WaveReadFormat().
SDL_ReadU32BE()
SDL_DECLSPEC bool SDLCALL SDL_ReadU32BE (SDL_IOStream * src, Uint32 * value) extern
Use this function to read 32 bits of big-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint32 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = SDL_Swap32BE(data);
    }
    return result;
}
References SDL_ReadIO(), and SDL_Swap32BE.
Referenced by SDL_ReadS32BE().
SDL_ReadU32LE()
SDL_DECLSPEC bool SDLCALL SDL_ReadU32LE (SDL_IOStream * src, Uint32 * value) extern
Use this function to read 32 bits of little-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint32 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = SDL_Swap32LE(data);
    }
    return result;
}
References SDL_ReadIO(), and SDL_Swap32LE.
Referenced by SDL_LoadBMP_IO(), SDL_ReadS32LE(), WaveLoad(), and WaveReadFormat().
SDL_ReadU64BE()
SDL_DECLSPEC bool SDLCALL SDL_ReadU64BE (SDL_IOStream * src, Uint64 * value) extern
Use this function to read 64 bits of big-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint64 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = SDL_Swap64BE(data);
    }
    return result;
}
References SDL_ReadIO(), and SDL_Swap64BE.
Referenced by SDL_ReadS64BE().
SDL_ReadU64LE()
SDL_DECLSPEC bool SDLCALL SDL_ReadU64LE (SDL_IOStream * src, Uint64 * value) extern
Use this function to read 64 bits of little-endian data from an SDL_IOStream and return in native format.
SDL byteswaps the data only if necessary, so the data returned will be in the native byte order.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the stream from which to read data.
value a pointer filled in with the data read.
Returns
true on successful read or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint64 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = SDL_Swap64LE(data);
    }
    return result;
}
References SDL_ReadIO(), and SDL_Swap64LE.
Referenced by SDL_ReadS64LE().
SDL_ReadU8()
SDL_DECLSPEC bool SDLCALL SDL_ReadU8 (SDL_IOStream * src, Uint8 * value) extern
Use this function to read a byte from an SDL_IOStream.
This function will return false when the data stream is completely read, and SDL_GetIOStatus() will return SDL_IO_STATUS_EOF. If false is returned and the stream is not at EOF, SDL_GetIOStatus() will return a different error value and SDL_GetError() will offer a human-readable message.
Parameters
src the SDL_IOStream to read from.
value a pointer filled in with the data read.
Returns
true on success or false on failure or EOF; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    Uint8 data = 0;
    bool result = false;
    if (SDL_ReadIO(src, &data, sizeof(data)) == sizeof(data)) {
        result = true;
    }
    if (value) {
        *value = data;
    }
    return result;
}
References SDL_ReadIO().
Referenced by readRlePixels(), SDL_LoadBMP_IO(), and WaveLoad().
SDL_SaveFile()
SDL_DECLSPEC bool SDLCALL SDL_SaveFile (const char * file, const void * data, size_t datasize) extern
Save all the data into a file path.
Parameters
file the path to write all available data into.
data the data to be written. If datasize is 0, may be NULL or a invalid pointer.
datasize the number of bytes to be written.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_SaveFile_IO
SDL_LoadFile
{
    SDL_IOStream *stream = SDL_IOFromFile(file, "wb");
    if (!stream) {
        return false;
    }
    return SDL_SaveFile_IO(stream, data, datasize, true);
}
References SDL_IOFromFile(), and SDL_SaveFile_IO().
SDL_SaveFile_IO()
SDL_DECLSPEC bool SDLCALL SDL_SaveFile_IO (SDL_IOStream * src, const void * data, size_t datasize, bool closeio) extern
Save all the data into an SDL data stream.
Parameters
src the SDL_IOStream to write all data to.
data the data to be written. If datasize is 0, may be NULL or a invalid pointer.
datasize the number of bytes to be written.
closeio if true, calls SDL_CloseIO() on src before returning, even in the case of an error.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_SaveFile
SDL_LoadFile_IO
{
    size_t size_written = 0;
    size_t size_total = 0;
    bool success = true;
    if (!src) {
        SDL_InvalidParamError("src");
        goto done;
    }
    if (!data && datasize > 0) {
        SDL_InvalidParamError("data");
        goto done;
    }
    if (datasize > 0) {
        while (size_total < datasize) {
            size_written = SDL_WriteIO(src, ((const char *) data) + size_written, datasize - size_written);
            if (size_written <= 0) {
                if (SDL_GetIOStatus(src) == SDL_IO_STATUS_NOT_READY) {
                    // Wait for the stream to be ready
                    SDL_Delay(1);
                    continue;
                } else {
                    success = false;
                    goto done;
                }
            }
            size_total += size_written;
        }
    }
done:
    if (closeio && src) {
        SDL_CloseIO(src);
    }
    return success;
}
References SDL_CloseIO(), SDL_Delay(), SDL_GetIOStatus(), SDL_InvalidParamError, SDL_IO_STATUS_NOT_READY, and SDL_WriteIO().
Referenced by SDL_SaveFile().
SDL_SeekIO()
SDL_DECLSPEC Sint64 SDLCALL SDL_SeekIO (SDL_IOStream * context, Sint64 offset, SDL_IOWhence whence) extern
Seek within an SDL_IOStream data stream.
This function seeks to byte offset, relative to whence.
whence may be any of the following values:
SDL_IO_SEEK_SET: seek from the beginning of data
SDL_IO_SEEK_CUR: seek relative to current read point
SDL_IO_SEEK_END: seek relative to the end of data
If this stream can not seek, it will return -1.
Parameters
context a pointer to an SDL_IOStream structure.
offset an offset in bytes, relative to whence location; can be negative.
whence any of SDL_IO_SEEK_SET, SDL_IO_SEEK_CUR, SDL_IO_SEEK_END.
Returns
the final offset in the data stream after the seek or -1 on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_TellIO
{
    if (!context) {
        SDL_InvalidParamError("context");
        return -1;
    } else if (!context->iface.seek) {
        SDL_Unsupported();
        return -1;
    }
    return context->iface.seek(context->userdata, offset, whence);
}
References context, SDL_InvalidParamError, and SDL_Unsupported.
Referenced by SDL_GetIOSize(), SDL_InternalGlobDirectory(), SDL_LoadBMP_IO(), SDL_LoadWAV_IO(), SDL_SaveBMP_IO(), SDL_TellIO(), SynchronousIO(), WaveLoad(), WaveNextChunk(), and WaveReadPartialChunkData().
SDL_TellIO()
SDL_DECLSPEC Sint64 SDLCALL SDL_TellIO (SDL_IOStream * context) extern
Determine the current read/write offset in an SDL_IOStream data stream.
SDL_TellIO is actually a wrapper function that calls the SDL_IOStream's seek method, with an offset of 0 bytes from SDL_IO_SEEK_CUR, to simplify application development.
Parameters
context an SDL_IOStream data stream object from which to get the current offset.
Returns
the current offset in the stream, or -1 if the information can not be determined.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_SeekIO
{
    return SDL_SeekIO(context, 0, SDL_IO_SEEK_CUR);
}
References context, SDL_IO_SEEK_CUR, and SDL_SeekIO().
Referenced by SDL_LoadBMP_IO(), SDL_SaveBMP_IO(), and WaveLoad().
SDL_WriteIO()
SDL_DECLSPEC size_t SDLCALL SDL_WriteIO (SDL_IOStream * context, const void * ptr, size_t size) extern
Write to an SDL_IOStream data stream.
This function writes exactly size bytes from the area pointed at by ptr to the stream. If this fails for any reason, it'll return less than size to demonstrate how far the write progressed. On success, it returns size.
On error, this function still attempts to write as much as possible, so it might return a positive value less than the requested write size.
The caller can use SDL_GetIOStatus() to determine if the problem is recoverable, such as a non-blocking write that can simply be retried later, or a fatal error.
Parameters
context a pointer to an SDL_IOStream structure.
ptr a pointer to a buffer containing data to write.
size the number of bytes to write.
Returns
the number of bytes written, which will be less than size on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
See also
SDL_IOprintf
SDL_ReadIO
SDL_SeekIO
SDL_FlushIO
SDL_GetIOStatus
{
    size_t bytes;
    if (!context) {
        SDL_InvalidParamError("context");
        return 0;
    } else if (!context->iface.write) {
        context->status = SDL_IO_STATUS_READONLY;
        SDL_Unsupported();
        return 0;
    }
    context->status = SDL_IO_STATUS_READY;
    SDL_ClearError();
    if (size == 0) {
        return 0;
    }
    bytes = context->iface.write(context->userdata, ptr, size, &context->status);
    if ((bytes == 0) && (context->status == SDL_IO_STATUS_READY)) {
        context->status = SDL_IO_STATUS_ERROR;
    }
    return bytes;
}
References context, SDL_ClearError(), SDL_InvalidParamError, SDL_IO_STATUS_ERROR, SDL_IO_STATUS_READONLY, SDL_IO_STATUS_READY, and SDL_Unsupported.
Referenced by GENERIC_WriteStorageFile(), GlobDirectoryCallback(), SDL_IOprintf(), SDL_IOvprintf(), SDL_SaveBMP_IO(), SDL_SaveFile_IO(), SDL_WriteS8(), SDL_WriteU16BE(), SDL_WriteU16LE(), SDL_WriteU32BE(), SDL_WriteU32LE(), SDL_WriteU64BE(), SDL_WriteU64LE(), SDL_WriteU8(), and SynchronousIO().
SDL_WriteS16BE()
SDL_DECLSPEC bool SDLCALL SDL_WriteS16BE (SDL_IOStream * dst, Sint16 value) extern
Use this function to write 16 bits in native format to an SDL_IOStream as big-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in big-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_WriteU16BE(dst, (Uint16)value);
}
References SDL_WriteU16BE().
SDL_WriteS16LE()
SDL_DECLSPEC bool SDLCALL SDL_WriteS16LE (SDL_IOStream * dst, Sint16 value) extern
Use this function to write 16 bits in native format to an SDL_IOStream as little-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in little-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_WriteU16LE(dst, (Uint16)value);
}
References SDL_WriteU16LE().
SDL_WriteS32BE()
SDL_DECLSPEC bool SDLCALL SDL_WriteS32BE (SDL_IOStream * dst, Sint32 value) extern
Use this function to write 32 bits in native format to an SDL_IOStream as big-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in big-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_WriteU32BE(dst, (Uint32)value);
}
References SDL_WriteU32BE().
SDL_WriteS32LE()
SDL_DECLSPEC bool SDLCALL SDL_WriteS32LE (SDL_IOStream * dst, Sint32 value) extern
Use this function to write 32 bits in native format to an SDL_IOStream as little-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in little-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_WriteU32LE(dst, (Uint32)value);
}
References SDL_WriteU32LE().
Referenced by SDL_SaveBMP_IO().
SDL_WriteS64BE()
SDL_DECLSPEC bool SDLCALL SDL_WriteS64BE (SDL_IOStream * dst, Sint64 value) extern
Use this function to write 64 bits in native format to an SDL_IOStream as big-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in big-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_WriteU64BE(dst, (Uint64)value);
}
References SDL_WriteU64BE().
SDL_WriteS64LE()
SDL_DECLSPEC bool SDLCALL SDL_WriteS64LE (SDL_IOStream * dst, Sint64 value) extern
Use this function to write 64 bits in native format to an SDL_IOStream as little-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in little-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return SDL_WriteU64LE(dst, (Uint64)value);
}
References SDL_WriteU64LE().
SDL_WriteS8()
SDL_DECLSPEC bool SDLCALL SDL_WriteS8 (SDL_IOStream * dst, Sint8 value) extern
Use this function to write a signed byte to an SDL_IOStream.
Parameters
dst the SDL_IOStream to write to.
value the byte value to write.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return (SDL_WriteIO(dst, &value, sizeof(value)) == sizeof(value));
}
References SDL_WriteIO().
SDL_WriteU16BE()
SDL_DECLSPEC bool SDLCALL SDL_WriteU16BE (SDL_IOStream * dst, Uint16 value) extern
Use this function to write 16 bits in native format to an SDL_IOStream as big-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in big-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    const Uint16 swapped = SDL_Swap16BE(value);
    return (SDL_WriteIO(dst, &swapped, sizeof(swapped)) == sizeof(swapped));
}
References SDL_Swap16BE, and SDL_WriteIO().
Referenced by SDL_WriteS16BE().
SDL_WriteU16LE()
SDL_DECLSPEC bool SDLCALL SDL_WriteU16LE (SDL_IOStream * dst, Uint16 value) extern
Use this function to write 16 bits in native format to an SDL_IOStream as little-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in little-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    const Uint16 swapped = SDL_Swap16LE(value);
    return (SDL_WriteIO(dst, &swapped, sizeof(swapped)) == sizeof(swapped));
}
References SDL_Swap16LE, and SDL_WriteIO().
Referenced by SDL_SaveBMP_IO(), and SDL_WriteS16LE().
SDL_WriteU32BE()
SDL_DECLSPEC bool SDLCALL SDL_WriteU32BE (SDL_IOStream * dst, Uint32 value) extern
Use this function to write 32 bits in native format to an SDL_IOStream as big-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in big-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    const Uint32 swapped = SDL_Swap32BE(value);
    return (SDL_WriteIO(dst, &swapped, sizeof(swapped)) == sizeof(swapped));
}
References SDL_Swap32BE, and SDL_WriteIO().
Referenced by SDL_WriteS32BE().
SDL_WriteU32LE()
SDL_DECLSPEC bool SDLCALL SDL_WriteU32LE (SDL_IOStream * dst, Uint32 value) extern
Use this function to write 32 bits in native format to an SDL_IOStream as little-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in little-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    const Uint32 swapped = SDL_Swap32LE(value);
    return (SDL_WriteIO(dst, &swapped, sizeof(swapped)) == sizeof(swapped));
}
References SDL_Swap32LE, and SDL_WriteIO().
Referenced by SDL_SaveBMP_IO(), and SDL_WriteS32LE().
SDL_WriteU64BE()
SDL_DECLSPEC bool SDLCALL SDL_WriteU64BE (SDL_IOStream * dst, Uint64 value) extern
Use this function to write 64 bits in native format to an SDL_IOStream as big-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in big-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    const Uint64 swapped = SDL_Swap64BE(value);
    return (SDL_WriteIO(dst, &swapped, sizeof(swapped)) == sizeof(swapped));
}
References SDL_Swap64BE, and SDL_WriteIO().
Referenced by SDL_WriteS64BE().
SDL_WriteU64LE()
SDL_DECLSPEC bool SDLCALL SDL_WriteU64LE (SDL_IOStream * dst, Uint64 value) extern
Use this function to write 64 bits in native format to an SDL_IOStream as little-endian data.
SDL byteswaps the data only if necessary, so the application always specifies native format, and the data written will be in little-endian format.
Parameters
dst the stream to which data will be written.
value the data to be written, in native format.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    const Uint64 swapped = SDL_Swap64LE(value);
    return (SDL_WriteIO(dst, &swapped, sizeof(swapped)) == sizeof(swapped));
}
References SDL_Swap64LE, and SDL_WriteIO().
Referenced by SDL_WriteS64LE().
SDL_WriteU8()
SDL_DECLSPEC bool SDLCALL SDL_WriteU8 (SDL_IOStream * dst, Uint8 value) extern
Use this function to write a byte to an SDL_IOStream.
Parameters
dst the SDL_IOStream to write to.
value the byte value to write.
Returns
true on successful write or false on failure; call SDL_GetError() for more information.
Thread Safety
This function is not thread safe.
Since
This function is available since SDL 3.2.0.
{
    return (SDL_WriteIO(dst, &value, sizeof(value)) == sizeof(value));
}
References SDL_WriteIO().
Referenced by SDL_SaveBMP_IO().