SDL3: hidapi API
hidapi API
Macros
#define HID_API_MAKE_VERSION(mj, mn, p)
Coverts a version as Major/Minor/Patch into a number: <8 bit major><16 bit minor><8 bit patch>.
#define HID_API_MAX_REPORT_DESCRIPTOR_SIZE 4096
Maximum expected HID Report descriptor size in bytes.
#define HID_API_VERSION HID_API_MAKE_VERSION(HID_API_VERSION_MAJOR, HID_API_VERSION_MINOR, HID_API_VERSION_PATCH)
Static/compile-time version of the library.
#define HID_API_VERSION_MAJOR 0
Static/compile-time major version of the library.
#define HID_API_VERSION_MINOR 14
Static/compile-time minor version of the library.
#define HID_API_VERSION_PATCH 0
Static/compile-time patch version of the library.
#define HID_API_VERSION_STR HID_API_TO_VERSION_STR(HID_API_VERSION_MAJOR, HID_API_VERSION_MINOR, HID_API_VERSION_PATCH)
Static/compile-time string version of the library.
Enumerations
enum hid_bus_type {
HID_API_BUS_UNKNOWN = 0x00 , HID_API_BUS_USB = 0x01 , HID_API_BUS_BLUETOOTH = 0x02 , HID_API_BUS_I2C = 0x03 ,
HID_API_BUS_SPI = 0x04
}
HID underlying bus types.
Functions
void hid_close (hid_device *dev)
Close a HID device.
int hid_darwin_get_location_id (PLATFORM_hid_device *dev, uint32_t *location_id)
Get the location ID for a HID device.
int hid_darwin_get_open_exclusive (void)
Getter for option set by hid_darwin_set_open_exclusive.
int hid_darwin_is_device_open_exclusive (PLATFORM_hid_device *dev)
Check how the device was opened.
void hid_darwin_set_open_exclusive (int open_exclusive)
Changes the behavior of all further calls to hid_open or hid_open_path.
struct hid_device_info * hid_enumerate (unsigned short vendor_id, unsigned short product_id)
Enumerate the HID Devices.
const wchar_t * hid_error (hid_device *dev)
Get a string describing the last error which occurred.
int hid_exit (void)
Finalize the HIDAPI library.
void hid_free_enumeration (struct hid_device_info *devs)
Free an enumeration Linked List.
struct hid_device_info * hid_get_device_info (hid_device *dev)
Get The struct hid_device_info from a HID device.
int hid_get_feature_report (hid_device *dev, unsigned char *data, size_t length)
Get a feature report from a HID device.
int hid_get_indexed_string (hid_device *dev, int string_index, wchar_t *string, size_t maxlen)
Get a string from a HID device, based on its string index.
int hid_get_input_report (hid_device *dev, unsigned char *data, size_t length)
Get a input report from a HID device.
int hid_get_manufacturer_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Manufacturer String from a HID device.
int hid_get_product_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Product String from a HID device.
int hid_get_report_descriptor (hid_device *dev, unsigned char *buf, size_t buf_size)
Get a report descriptor from a HID device.
int hid_get_serial_number_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Serial Number String from a HID device.
int hid_init (void)
Initialize the HIDAPI library.
PLATFORM_hid_device * hid_libusb_wrap_sys_device (intptr_t sys_dev, int interface_num)
Open a HID device using libusb_wrap_sys_device. See https://libusb.sourceforge.io/api-1.0/group__libusb__dev.html#ga98f783e115ceff4eaf88a60e6439563c, for details on libusb_wrap_sys_device.
hid_device * hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
hid_device * hid_open_path (const char *path)
Open a HID device by its path name.
int hid_read (hid_device *dev, unsigned char *data, size_t length)
Read an Input report from a HID device.
int hid_read_timeout (hid_device *dev, unsigned char *data, size_t length, int milliseconds)
Read an Input report from a HID device with timeout.
int hid_send_feature_report (hid_device *dev, const unsigned char *data, size_t length)
Send a Feature report to the device.
int hid_set_nonblocking (hid_device *dev, int nonblock)
Set the device handle to be non-blocking.
const struct hid_api_version * hid_version (void)
Get a runtime version of the library.
const char * hid_version_str (void)
Get a runtime version string of the library.
int hid_winapi_get_container_id (PLATFORM_hid_device *dev, GUID *container_id)
Get the container ID for a HID device.
int hid_write (hid_device *dev, const unsigned char *data, size_t length)
Write an Output report to a HID device.
Detailed Description
Since version 0.11.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 11, 0).
Since version 0.12.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 12, 0)
Macro Definition Documentation
HID_API_MAKE_VERSION
#define HID_API_MAKE_VERSION (mj, mn, p)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Value:
(((mj) << 24) | ((mn) << 8) | (p))
Coverts a version as Major/Minor/Patch into a number: <8 bit major><16 bit minor><8 bit patch>.
This macro was added in version 0.12.0.
Convenient function to be used for compile-time checks, like:
#if HID_API_VERSION >= HID_API_MAKE_VERSION(0, 12, 0)
HID_API_MAX_REPORT_DESCRIPTOR_SIZE
#define HID_API_MAX_REPORT_DESCRIPTOR_SIZE 4096
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Maximum expected HID Report descriptor size in bytes.
Since version 0.13.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 13, 0)
Referenced by fill_device_info_usage(), get_report_descriptor_size_from_interface_descriptors(), and hid_get_report_descriptor_libusb().
HID_API_VERSION
#define HID_API_VERSION HID_API_MAKE_VERSION(HID_API_VERSION_MAJOR, HID_API_VERSION_MINOR, HID_API_VERSION_PATCH)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Static/compile-time version of the library.
This macro was added in version 0.12.0.
See also
HID_API_MAKE_VERSION.
HID_API_VERSION_MAJOR
#define HID_API_VERSION_MAJOR 0
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Static/compile-time major version of the library.
Referenced by main(), and PLATFORM_hid_version().
HID_API_VERSION_MINOR
#define HID_API_VERSION_MINOR 14
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Static/compile-time minor version of the library.
Referenced by main(), and PLATFORM_hid_version().
HID_API_VERSION_PATCH
#define HID_API_VERSION_PATCH 0
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Static/compile-time patch version of the library.
Referenced by main(), and PLATFORM_hid_version().
HID_API_VERSION_STR
#define HID_API_VERSION_STR HID_API_TO_VERSION_STR(HID_API_VERSION_MAJOR, HID_API_VERSION_MINOR, HID_API_VERSION_PATCH)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Static/compile-time string version of the library.
Referenced by main(), and PLATFORM_hid_version_str().
Enumeration Type Documentation
hid_bus_type
enum hid_bus_type
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
HID underlying bus types.
Enumerator
HID_API_BUS_UNKNOWN
Unknown bus type
HID_API_BUS_USB
USB bus Specifications: https://usb.org/hid
HID_API_BUS_BLUETOOTH
Bluetooth or Bluetooth LE bus Specifications: https://www.bluetooth.com/specifications/specs/human-interface-device-profile-1-1-1/ https://www.bluetooth.com/specifications/specs/hid-service-1-0/ https://www.bluetooth.com/specifications/specs/hid-over-gatt-profile-1-0/
HID_API_BUS_I2C
I2C bus Specifications: https://docs.microsoft.com/previous-versions/windows/hardware/design/dn642101(v=vs.85)
HID_API_BUS_SPI
SPI bus Specifications: https://www.microsoft.com/download/details.aspx?id=103325
                     {
            /** Unknown bus type */
            HID_API_BUS_UNKNOWN = 0x00,
            /** USB bus
               Specifications:
               https://usb.org/hid */
            HID_API_BUS_USB = 0x01,
            /** Bluetooth or Bluetooth LE bus
               Specifications:
               https://www.bluetooth.com/specifications/specs/human-interface-device-profile-1-1-1/
               https://www.bluetooth.com/specifications/specs/hid-service-1-0/
               https://www.bluetooth.com/specifications/specs/hid-over-gatt-profile-1-0/ */
            HID_API_BUS_BLUETOOTH = 0x02,
            /** I2C bus
               Specifications:
               https://docs.microsoft.com/previous-versions/windows/hardware/design/dn642101(v=vs.85) */
            HID_API_BUS_I2C = 0x03,
            /** SPI bus
               Specifications:
               https://www.microsoft.com/download/details.aspx?id=103325 */
            HID_API_BUS_SPI = 0x04,
        } hid_bus_type;
Function Documentation
hid_close()
void hid_close (hid_device * dev)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Close a HID device.
Parameters
dev A device handle returned from hid_open(). < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_darwin_get_location_id()
int hid_darwin_get_location_id (PLATFORM_hid_device * dev, uint32_t * location_id)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/mac/hidapi_darwin.h>
Get the location ID for a HID device.
Since version 0.12.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 12, 0)
Parameters
dev A device handle returned from hid_open().
location_id The device's location ID on return.
Returns
This function returns 0 on success and -1 on error. < API export macro < API call macro < API export and call macro
< API export macro < API call macro < API export and call macro
{
    int res = get_int_property(dev->device_handle, CFSTR(kIOHIDLocationIDKey));
    if (res != 0) {
        *location_id = (uint32_t) res;
        return 0;
    } else {
        register_device_error(dev, "Failed to get IOHIDLocationID property");
        return -1;
    }
}
References get_int_property(), HID_API_EXPORT_CALL, hid_device, and register_device_error().
hid_darwin_get_open_exclusive()
int hid_darwin_get_open_exclusive (void)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/mac/hidapi_darwin.h>
Getter for option set by hid_darwin_set_open_exclusive.
Since version 0.12.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 12, 0)
Returns
1 if all further devices will be opened in exclusive mode.
Note
Value returned by this function before calling to hid_init or after hid_exit is not reliable. < API export macro < API call macro < API export and call macro
< API export macro < API call macro < API export and call macro
{
    return (device_open_options == kIOHIDOptionsTypeSeizeDevice) ? 1 : 0;
}
References device_open_options, and HID_API_EXPORT_CALL.
hid_darwin_is_device_open_exclusive()
int hid_darwin_is_device_open_exclusive (PLATFORM_hid_device * dev)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/mac/hidapi_darwin.h>
Check how the device was opened.
Since version 0.12.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 12, 0)
Parameters
dev A device to get property from.
Returns
1 if the device is opened in exclusive mode, 0 - opened in non-exclusive, -1 - if dev is invalid. < API export macro < API call macro < API export and call macro
< API export macro < API call macro < API export and call macro
{
    if (!dev)
        return -1;
    return (dev->open_options == kIOHIDOptionsTypeSeizeDevice) ? 1 : 0;
}
References HID_API_EXPORT_CALL, and hid_device.
hid_darwin_set_open_exclusive()
void hid_darwin_set_open_exclusive (int open_exclusive)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/mac/hidapi_darwin.h>
Changes the behavior of all further calls to hid_open or hid_open_path.
By default on Darwin platform all devices opened by HIDAPI with hid_open or hid_open_path are opened in exclusive mode (see kIOHIDOptionsTypeSeizeDevice).
Since version 0.12.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 12, 0)
Parameters
open_exclusive When set to 0 - all further devices will be opened in non-exclusive mode. Otherwise - all further devices will be opened in exclusive mode.
Note
During the initialisation by hid_init - this property is set to 1 (TRUE). This is done to preserve full backward compatibility with previous behavior.
Calling this function before hid_init or after hid_exit has no effect. < API export macro < API call macro < API export and call macro
< API export macro < API call macro < API export and call macro
{
    device_open_options = (open_exclusive == 0) ? kIOHIDOptionsTypeNone : kIOHIDOptionsTypeSeizeDevice;
}
References device_open_options, and HID_API_EXPORT_CALL.
Referenced by PLATFORM_hid_init(), and SDL_hid_init().
hid_enumerate()
struct hid_device_info * hid_enumerate (unsigned short vendor_id, unsigned short product_id)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Enumerate the HID Devices.
This function returns a linked list of all the HID devices attached to the system which match vendor_id and product_id. If vendor_id is set to 0 then any vendor matches. If product_id is set to 0 then any product matches. If vendor_id and product_id are both set to 0, then all HID devices will be returned.
Parameters
vendor_id The Vendor ID (VID) of the types of device to open.
product_id The Product ID (PID) of the types of device to open.
Returns
This function returns a pointer to a linked list of type struct hid_device_info, containing information about the HID devices attached to the system, or NULL in the case of failure or if no HID devices present in the system. Call hid_error(NULL) to get the failure reason.
Note
The returned value by this function must to be freed by calling hid_free_enumeration(), when not needed anymore. < API export macro < API call macro
References HID_API_CALL, and HID_API_EXPORT.
hid_error()
const wchar_t * hid_error (hid_device * dev)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get a string describing the last error which occurred.
This function is intended for logging/debugging purposes.
This function guarantees to never return NULL. If there was no error in the last function call - the returned string clearly indicates that.
Any HIDAPI function that can explicitly indicate an execution failure (e.g. by an error code, or by returning NULL) - may set the error string, to be returned by this function.
Strings returned from hid_error() must not be freed by the user, i.e. owned by HIDAPI library. Device-specific error string may remain allocated at most until hid_close() is called. Global error string may remain allocated at most until hid_exit() is called.
Parameters
dev A device handle returned from hid_open(), or NULL to get the last non-device-specific error (e.g. for errors in hid_open() or hid_enumerate()).
Returns
A string describing the last error (if any). < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_exit()
int hid_exit (void)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Finalize the HIDAPI library.
This function frees all of the static data associated with HIDAPI. It should be called at the end of execution to avoid memory leaks.
Returns
This function returns 0 on success and -1 on error. < API export macro < API call macro
References HID_API_CALL, and HID_API_EXPORT.
hid_free_enumeration()
void hid_free_enumeration (struct hid_device_info * devs)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Free an enumeration Linked List.
This function frees a linked list created by hid_enumerate().
Parameters
devs Pointer to a list of struct_device returned from hid_enumerate(). < API export macro < API call macro
References HID_API_CALL, and HID_API_EXPORT.
hid_get_device_info()
struct hid_device_info * hid_get_device_info (hid_device * dev)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get The struct hid_device_info from a HID device.
Since version 0.13.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 13, 0)
Parameters
dev A device handle returned from hid_open().
Returns
This function returns a pointer to the struct hid_device_info for this hid_device, or NULL in the case of failure. Call hid_error(dev) to get the failure reason. This struct is valid until the device is closed with hid_close().
Note
The returned object is owned by the dev, and SHOULD NOT be freed by the user. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_get_feature_report()
int hid_get_feature_report (hid_device * dev, unsigned char * data, size_t length)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get a feature report from a HID device.
Set the first byte of data[] to the Report ID of the report to be read. Make sure to allow space for this extra byte in data[]. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into, including the Report ID. Set the first byte of data[] to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length The number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
This function returns the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_get_indexed_string()
int hid_get_indexed_string (hid_device * dev, int string_index, wchar_t * string, size_t maxlen)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get a string from a HID device, based on its string index.
Parameters
dev A device handle returned from hid_open().
string_index The index of the string to get.
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro < API export and call macro
References HID_API_EXPORT_CALL, and hid_device.
hid_get_input_report()
int hid_get_input_report (hid_device * dev, unsigned char * data, size_t length)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get a input report from a HID device.
Since version 0.10.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 10, 0)
Set the first byte of data[] to the Report ID of the report to be read. Make sure to allow space for this extra byte in data[]. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into, including the Report ID. Set the first byte of data[] to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length The number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
This function returns the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_get_manufacturer_string()
int hid_get_manufacturer_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get The Manufacturer String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro < API export and call macro
References HID_API_EXPORT_CALL, and hid_device.
hid_get_product_string()
int hid_get_product_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get The Product String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro < API export and call macro
References HID_API_EXPORT_CALL, and hid_device.
hid_get_report_descriptor()
int hid_get_report_descriptor (hid_device * dev, unsigned char * buf, size_t buf_size)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get a report descriptor from a HID device.
Since version 0.14.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 14, 0)
User has to provide a preallocated buffer where descriptor will be copied to. The recommended size for preallocated buffer is HID_API_MAX_REPORT_DESCRIPTOR_SIZE bytes.
Parameters
dev A device handle returned from hid_open().
buf The buffer to copy descriptor into.
buf_size The size of the buffer in bytes.
Returns
This function returns non-negative number of bytes actually copied, or -1 on error. < API export macro < API call macro < API export and call macro
References HID_API_EXPORT_CALL, and hid_device.
hid_get_serial_number_string()
int hid_get_serial_number_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get The Serial Number String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro < API export and call macro
References HID_API_EXPORT_CALL, and hid_device.
hid_init()
int hid_init (void)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Initialize the HIDAPI library.
This function initializes the HIDAPI library. Calling it is not strictly necessary, as it will be called automatically by hid_enumerate() and any of the hid_open_*() functions if it is needed. This function should be called at the beginning of execution however, if there is a chance of HIDAPI handles being opened by different threads simultaneously.
Returns
This function returns 0 on success and -1 on error. Call hid_error(NULL) to get the failure reason. < API export macro < API call macro
References HID_API_CALL, and HID_API_EXPORT.
hid_libusb_wrap_sys_device()
PLATFORM_hid_device * hid_libusb_wrap_sys_device (intptr_t sys_dev, int interface_num)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/libusb/hidapi_libusb.h>
Open a HID device using libusb_wrap_sys_device. See https://libusb.sourceforge.io/api-1.0/group__libusb__dev.html#ga98f783e115ceff4eaf88a60e6439563c, for details on libusb_wrap_sys_device.
Parameters
sys_dev Platform-specific file descriptor that can be recognised by libusb.
interface_num USB interface number of the device to be used as HID interface. Pass -1 to select first HID interface of the device.
Returns
This function returns a pointer to a hid_device object on success or NULL on failure. < API export macro < API call macro
< API call macro
{
/* 0x01000107 is a LIBUSB_API_VERSION for 1.0.23 - version when libusb_wrap_sys_device was introduced */
#if (!defined(HIDAPI_TARGET_LIBUSB_API_VERSION) || HIDAPI_TARGET_LIBUSB_API_VERSION >= 0x01000107) && (LIBUSB_API_VERSION >= 0x01000107)
    hid_device *dev = NULL;
    struct libusb_config_descriptor *conf_desc = NULL;
    const struct libusb_interface_descriptor *selected_intf_desc = NULL;
    int res = 0;
    int j = 0, k = 0;
    if(hid_init() < 0)
        return NULL;
    dev = new_hid_device();
    res = libusb_wrap_sys_device(usb_context, sys_dev, &dev->device_handle);
    if (res < 0) {
        LOG("libusb_wrap_sys_device failed: %d %s\n", res, libusb_error_name(res));
        goto err;
    }
    res = libusb_get_active_config_descriptor(libusb_get_device(dev->device_handle), &conf_desc);
    if (res < 0)
        libusb_get_config_descriptor(libusb_get_device(dev->device_handle), 0, &conf_desc);
    if (!conf_desc) {
        LOG("Failed to get configuration descriptor: %d %s\n", res, libusb_error_name(res));
        goto err;
    }
    /* find matching HID interface */
    for (j = 0; j < conf_desc->bNumInterfaces && !selected_intf_desc; j++) {
        const struct libusb_interface *intf = &conf_desc->interface[j];
        for (k = 0; k < intf->num_altsetting; k++) {
            const struct libusb_interface_descriptor *intf_desc = &intf->altsetting[k];
            if (intf_desc->bInterfaceClass == LIBUSB_CLASS_HID) {
                if (interface_num < 0 || interface_num == intf_desc->bInterfaceNumber) {
                    selected_intf_desc = intf_desc;
                    break;
                }
            }
        }
    }
    if (!selected_intf_desc) {
        if (interface_num < 0) {
            LOG("Sys USB device doesn't contain a HID interface\n");
        }
        else {
            LOG("Sys USB device doesn't contain a HID interface with number %d\n", interface_num);
        }
        goto err;
    }
    if (!hidapi_initialize_device(dev, selected_intf_desc, conf_desc))
        goto err;
    return dev;
err:
    if (conf_desc)
        libusb_free_config_descriptor(conf_desc);
    if (dev->device_handle)
        libusb_close(dev->device_handle);
    free_hid_device(dev);
#else
    (void)sys_dev;
    (void)interface_num;
    LOG("libusb_wrap_sys_device is not available\n");
#endif
    return NULL;
}
References free_hid_device, HID_API_CALL, HID_API_EXPORT, hid_device, hid_init, hidapi_initialize_device(), LOG, new_hid_device(), NULL, usb_context, and void().
hid_open()
hid_device * hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
If serial_number is NULL, the first device with the specified VID and PID is opened.
Parameters
vendor_id The Vendor ID (VID) of the device to open.
product_id The Product ID (PID) of the device to open.
serial_number The Serial Number of the device to open (Optionally NULL).
Returns
This function returns a pointer to a hid_device object on success or NULL on failure. Call hid_error(NULL) to get the failure reason.
Note
The returned object must be freed by calling hid_close(), when not needed anymore. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_open_path()
hid_device * hid_open_path (const char * path)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Open a HID device by its path name.
The path name be determined by calling hid_enumerate(), or a platform-specific path name can be used (eg: /dev/hidraw0 on Linux).
Parameters
path The path name of the device to open
Returns
This function returns a pointer to a hid_device object on success or NULL on failure. Call hid_error(NULL) to get the failure reason.
Note
The returned object must be freed by calling hid_close(), when not needed anymore. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_read()
int hid_read (hid_device * dev, unsigned char * data, size_t length)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Read an Input report from a HID device.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
Returns
This function returns the actual number of bytes read and -1 on error. Call hid_error(dev) to get the failure reason. If no packet was available to be read and the handle is in non-blocking mode, this function returns 0. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_read_timeout()
int hid_read_timeout (hid_device * dev, unsigned char * data, size_t length, int milliseconds)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Read an Input report from a HID device with timeout.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
milliseconds timeout in milliseconds or -1 for blocking wait.
Returns
This function returns the actual number of bytes read and -1 on error. Call hid_error(dev) to get the failure reason. If no packet was available to be read within the timeout period, this function returns 0. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_send_feature_report()
int hid_send_feature_report (hid_device * dev, const unsigned char * data, size_t length)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Send a Feature report to the device.
Feature reports are sent over the Control endpoint as a Set_Report transfer. The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_send_feature_report() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_send_feature_report(): the Report ID (or 0x0, for devices which do not use numbered reports), followed by the report data (16 bytes). In this example, the length passed in would be 17.
Parameters
dev A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send, including the report number.
Returns
This function returns the actual number of bytes written and -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_set_nonblocking()
int hid_set_nonblocking (hid_device * dev, int nonblock)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Set the device handle to be non-blocking.
In non-blocking mode calls to hid_read() will return immediately with a value of 0 if there is no data to be read. In blocking mode, hid_read() will wait (block) until there is data to read before returning.
Nonblocking can be turned on and off at any time.
Parameters
dev A device handle returned from hid_open().
nonblock enable or not the nonblocking reads
1 to enable nonblocking
0 to disable nonblocking.
Returns
This function returns 0 on success and -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.
hid_version()
const struct hid_api_version * hid_version (void)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get a runtime version of the library.
This function is thread-safe.
Returns
Pointer to statically allocated struct, that contains version. < API export macro < API call macro
References HID_API_CALL, and HID_API_EXPORT.
hid_version_str()
const char * hid_version_str (void)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Get a runtime version string of the library.
This function is thread-safe.
Returns
Pointer to statically allocated string, that contains version string. < API export macro < API call macro
References HID_API_CALL, and HID_API_EXPORT.
hid_winapi_get_container_id()
int hid_winapi_get_container_id (PLATFORM_hid_device * dev, GUID * container_id)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/windows/hidapi_winapi.h>
Get the container ID for a HID device.
Since version 0.12.0, HID_API_VERSION >= HID_API_MAKE_VERSION(0, 12, 0)
This function returns the DEVPKEY_Device_ContainerId property of the given device. This can be used to correlate different interfaces/ports on the same hardware device.
Parameters
dev A device handle returned from hid_open().
container_id The device's container ID on return.
Returns
This function returns 0 on success and -1 on error. < API export macro < API call macro < API export and call macro
References HID_API_EXPORT_CALL, and hid_device.
hid_write()
int hid_write (hid_device * dev, const unsigned char * data, size_t length)
#include <C:/Users/emirm/Downloads/sdl_all/SDL-main/src/hidapi/hidapi/hidapi.h>
Write an Output report to a HID device.
The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_write() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_write(), the Report ID (or 0x0, for devices with a single report), followed by the report data (16 bytes). In this example, the length passed in would be 17.
hid_write() will send the data on the first OUT endpoint, if one exists. If it does not, it will send the data through the Control Endpoint (Endpoint 0).
Parameters
dev A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send.
Returns
This function returns the actual number of bytes written and -1 on error. Call hid_error(dev) to get the failure reason. < API export macro < API call macro
References HID_API_CALL, HID_API_EXPORT, and hid_device.