SDL3: SDL-main/src/events/SDL_pen_c.h File Reference
SDL_pen_c.h File Reference
#include "../SDL_internal.h"
#include "SDL_mouse_c.h"
Data Structures
struct SDL_PenInfo
Macros
#define SDL_PEN_CAPABILITY_DISTANCE (1u << 3)
#define SDL_PEN_CAPABILITY_ERASER (1u << 7)
#define SDL_PEN_CAPABILITY_PRESSURE (1u << 0)
#define SDL_PEN_CAPABILITY_ROTATION (1u << 4)
#define SDL_PEN_CAPABILITY_SLIDER (1u << 5)
#define SDL_PEN_CAPABILITY_TANGENTIAL_PRESSURE (1u << 6)
#define SDL_PEN_CAPABILITY_XTILT (1u << 1)
#define SDL_PEN_CAPABILITY_YTILT (1u << 2)
Typedefs
typedef Uint32 SDL_PenCapabilityFlags
typedef struct SDL_PenInfo SDL_PenInfo
typedef enum SDL_PenSubtype SDL_PenSubtype
Enumerations
enum SDL_PenSubtype {
SDL_PEN_TYPE_UNKNOWN , SDL_PEN_TYPE_ERASER , SDL_PEN_TYPE_PEN , SDL_PEN_TYPE_PENCIL ,
SDL_PEN_TYPE_BRUSH , SDL_PEN_TYPE_AIRBRUSH
}
Functions
SDL_PenID SDL_AddPenDevice (Uint64 timestamp, const char *name, const SDL_PenInfo *info, void *handle)
SDL_PenID SDL_FindPenByCallback (bool(*callback)(void *handle, void *userdata), void *userdata)
SDL_PenID SDL_FindPenByHandle (void *handle)
SDL_PenCapabilityFlags SDL_GetPenCapabilityFromAxis (SDL_PenAxis axis)
SDL_PenInputFlags SDL_GetPenStatus (SDL_PenID instance_id, float *axes, int num_axes)
bool SDL_InitPen (void)
void SDL_QuitPen (void)
void SDL_RemoveAllPenDevices (void(*callback)(SDL_PenID instance_id, void *handle, void *userdata), void *userdata)
void SDL_RemovePenDevice (Uint64 timestamp, SDL_PenID instance_id)
void SDL_SendPenAxis (Uint64 timestamp, SDL_PenID instance_id, SDL_Window *window, SDL_PenAxis axis, float value)
void SDL_SendPenButton (Uint64 timestamp, SDL_PenID instance_id, SDL_Window *window, Uint8 button, bool down)
void SDL_SendPenMotion (Uint64 timestamp, SDL_PenID instance_id, SDL_Window *window, float x, float y)
void SDL_SendPenTouch (Uint64 timestamp, SDL_PenID instance_id, SDL_Window *window, bool eraser, bool down)
Macro Definition Documentation
SDL_PEN_CAPABILITY_DISTANCE
#define SDL_PEN_CAPABILITY_DISTANCE (1u << 3)
Provides distance to drawing tablet on SDL_PEN_AXIS_DISTANCE.
SDL_PEN_CAPABILITY_ERASER
#define SDL_PEN_CAPABILITY_ERASER (1u << 7)
Pen also has an eraser tip.
SDL_PEN_CAPABILITY_PRESSURE
#define SDL_PEN_CAPABILITY_PRESSURE (1u << 0)
Provides pressure information on SDL_PEN_AXIS_PRESSURE.
SDL_PEN_CAPABILITY_ROTATION
#define SDL_PEN_CAPABILITY_ROTATION (1u << 4)
Provides barrel rotation info on SDL_PEN_AXIS_ROTATION.
SDL_PEN_CAPABILITY_SLIDER
#define SDL_PEN_CAPABILITY_SLIDER (1u << 5)
Provides slider/finger wheel/etc on SDL_PEN_AXIS_SLIDER.
SDL_PEN_CAPABILITY_TANGENTIAL_PRESSURE
#define SDL_PEN_CAPABILITY_TANGENTIAL_PRESSURE (1u << 6)
Provides barrel pressure on SDL_PEN_AXIS_TANGENTIAL_PRESSURE.
SDL_PEN_CAPABILITY_XTILT
#define SDL_PEN_CAPABILITY_XTILT (1u << 1)
Provides horizontal tilt information on SDL_PEN_AXIS_XTILT.
SDL_PEN_CAPABILITY_YTILT
#define SDL_PEN_CAPABILITY_YTILT (1u << 2)
Provides vertical tilt information on SDL_PEN_AXIS_YTILT.
Typedef Documentation
SDL_PenCapabilityFlags
typedef Uint32 SDL_PenCapabilityFlags
SDL_PenInfo
typedef struct SDL_PenInfo SDL_PenInfo
SDL_PenSubtype
typedef enum SDL_PenSubtype SDL_PenSubtype
Enumeration Type Documentation
SDL_PenSubtype
enum SDL_PenSubtype
Enumerator
SDL_PEN_TYPE_UNKNOWN
Unknown pen device
SDL_PEN_TYPE_ERASER
Eraser
SDL_PEN_TYPE_PEN
Generic pen; this is the default.
SDL_PEN_TYPE_PENCIL
Pencil
SDL_PEN_TYPE_BRUSH
Brush-like device
SDL_PEN_TYPE_AIRBRUSH
Airbrush device that "sprays" ink
{
    SDL_PEN_TYPE_UNKNOWN,   /**< Unknown pen device */
    SDL_PEN_TYPE_ERASER,    /**< Eraser */
    SDL_PEN_TYPE_PEN,       /**< Generic pen; this is the default. */
    SDL_PEN_TYPE_PENCIL,    /**< Pencil */
    SDL_PEN_TYPE_BRUSH,     /**< Brush-like device */
    SDL_PEN_TYPE_AIRBRUSH   /**< Airbrush device that "sprays" ink */
} SDL_PenSubtype;
Function Documentation
SDL_AddPenDevice()
SDL_PenID SDL_AddPenDevice (Uint64 timestamp, const char * name, const SDL_PenInfo * info, void * handle) extern
{
    SDL_assert(handle != NULL);  // just allocate a Uint8 so you have a unique pointer if not needed!
    SDL_assert(SDL_FindPenByHandle(handle) == 0);  // Backends shouldn't double-add pens!
    SDL_assert(pen_device_rwlock != NULL);   // subsystem should be initialized by now!
    char *namecpy = SDL_strdup(name ? name : "Unnamed pen");
    if (!namecpy) {
        return 0;
    }
    SDL_PenID result = 0;
    SDL_LockRWLockForWriting(pen_device_rwlock);
    SDL_Pen *pen = NULL;
    void *ptr = SDL_realloc(pen_devices, (pen_device_count + 1) * sizeof (*pen));
    if (ptr) {
        result = (SDL_PenID) SDL_GetNextObjectID();
        pen_devices = (SDL_Pen *) ptr;
        pen = &pen_devices[pen_device_count];
        pen_device_count++;
        SDL_zerop(pen);
        pen->instance_id = result;
        pen->name = namecpy;
        if (info) {
            SDL_copyp(&pen->info, info);
        }
        pen->driverdata = handle;
        // axes and input state defaults to zero.
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    if (!pen) {
        SDL_free(namecpy);
    }
    if (result && SDL_EventEnabled(SDL_EVENT_PEN_PROXIMITY_IN)) {
        SDL_Event event;
        SDL_zero(event);
        event.pproximity.type = SDL_EVENT_PEN_PROXIMITY_IN;
        event.pproximity.timestamp = timestamp;
        event.pproximity.which = result;
        SDL_PushEvent(&event);
    }
    return result;
}
References SDL_Pen::driverdata, SDL_Pen::info, SDL_Pen::instance_id, SDL_Pen::name, NULL, pen_device_rwlock, SDL_assert, SDL_copyp, SDL_EVENT_PEN_PROXIMITY_IN, SDL_EventEnabled(), SDL_FindPenByHandle(), SDL_free(), SDL_GetNextObjectID(), SDL_LockRWLockForWriting(), SDL_PushEvent(), SDL_realloc(), SDL_strdup(), SDL_UnlockRWLock(), SDL_zero, and SDL_zerop.
SDL_FindPenByCallback()
SDL_PenID SDL_FindPenByCallback (bool(* callback)(void *handle, void *userdata), void * userdata) extern
{
    SDL_PenID result = 0;
    SDL_LockRWLockForReading(pen_device_rwlock);
    for (int i = 0; i < pen_device_count; i++) {
        if (callback(pen_devices[i].driverdata, userdata)) {
            result = pen_devices[i].instance_id;
            break;
        }
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    return result;
}
References pen_device_rwlock, SDL_LockRWLockForReading(), and SDL_UnlockRWLock().
SDL_FindPenByHandle()
SDL_PenID SDL_FindPenByHandle (void * handle) extern
{
    SDL_PenID result = 0;
    SDL_LockRWLockForReading(pen_device_rwlock);
    for (int i = 0; i < pen_device_count; i++) {
        if (pen_devices[i].driverdata == handle) {
            result = pen_devices[i].instance_id;
            break;
        }
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    return result;
}
References pen_device_rwlock, SDL_LockRWLockForReading(), and SDL_UnlockRWLock().
Referenced by SDL_AddPenDevice().
SDL_GetPenCapabilityFromAxis()
SDL_PenCapabilityFlags SDL_GetPenCapabilityFromAxis (SDL_PenAxis axis)
{
    // the initial capability bits happen to match up, but as
    // more features show up later, the bits may no longer be contiguous!
    if ((axis >= SDL_PEN_AXIS_PRESSURE) && (axis <= SDL_PEN_AXIS_SLIDER)) {
        return ((SDL_PenCapabilityFlags) 1u) << ((SDL_PenCapabilityFlags) axis);
    }
    return 0;  // oh well.
}
References SDL_PEN_AXIS_PRESSURE, and SDL_PEN_AXIS_SLIDER.
SDL_GetPenStatus()
SDL_PenInputFlags SDL_GetPenStatus (SDL_PenID instance_id, float * axes, int num_axes)
{
    if (num_axes < 0) {
        num_axes = 0;
    }
    SDL_LockRWLockForReading(pen_device_rwlock);
    const SDL_Pen *pen = FindPenByInstanceId(instance_id);
    SDL_PenInputFlags result = 0;
    if (pen) {
        result = pen->input_state;
        if (axes && num_axes) {
            SDL_memcpy(axes, pen->axes, SDL_min(num_axes, SDL_PEN_AXIS_COUNT) * sizeof (*axes));
            // zero out axes we don't know about, in case the caller built with newer SDL headers that support more of them.
            if (num_axes > SDL_PEN_AXIS_COUNT) {
                SDL_memset(&axes[SDL_PEN_AXIS_COUNT], '\0', (num_axes - SDL_PEN_AXIS_COUNT) * sizeof (*axes));
            }
        }
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    return result;
}
References SDL_Pen::axes, FindPenByInstanceId(), SDL_Pen::input_state, pen_device_rwlock, SDL_LockRWLockForReading(), SDL_memcpy, SDL_memset, SDL_min, SDL_PEN_AXIS_COUNT, and SDL_UnlockRWLock().
SDL_InitPen()
bool SDL_InitPen (void) extern
{
    SDL_assert(pen_device_rwlock == NULL);
    SDL_assert(pen_devices == NULL);
    SDL_assert(pen_device_count == 0);
    pen_device_rwlock = SDL_CreateRWLock();
    if (!pen_device_rwlock) {
        return false;
    }
    return true;
}
References NULL, pen_device_rwlock, SDL_assert, and SDL_CreateRWLock().
Referenced by SDL_VideoInit().
SDL_QuitPen()
void SDL_QuitPen (void) extern
{
    SDL_DestroyRWLock(pen_device_rwlock);
    pen_device_rwlock = NULL;
    if (pen_devices) {
        for (int i = pen_device_count; i--; ) {
            SDL_free(pen_devices[i].name);
        }
        SDL_free(pen_devices);
        pen_devices = NULL;
    }
    pen_device_count = 0;
    pen_touching = 0;
}
References NULL, pen_device_rwlock, pen_touching, SDL_DestroyRWLock(), and SDL_free().
Referenced by SDL_VideoInit(), and SDL_VideoQuit().
SDL_RemoveAllPenDevices()
void SDL_RemoveAllPenDevices (void(* callback)(SDL_PenID instance_id, void *handle, void *userdata), void * userdata) extern
{
    SDL_LockRWLockForWriting(pen_device_rwlock);
    if (pen_device_count > 0) {
        SDL_assert(pen_devices != NULL);
        for (int i = 0; i < pen_device_count; i++) {
            callback(pen_devices[i].instance_id, pen_devices[i].driverdata, userdata);
            SDL_free(pen_devices[i].name);
        }
    }
    SDL_free(pen_devices);
    pen_devices = NULL;
    SDL_UnlockRWLock(pen_device_rwlock);
}
References NULL, pen_device_rwlock, SDL_assert, SDL_free(), SDL_LockRWLockForWriting(), and SDL_UnlockRWLock().
SDL_RemovePenDevice()
void SDL_RemovePenDevice (Uint64 timestamp, SDL_PenID instance_id) extern
{
    if (!instance_id) {
        return;
    }
    SDL_LockRWLockForWriting(pen_device_rwlock);
    SDL_Pen *pen = FindPenByInstanceId(instance_id);
    if (pen) {
        SDL_free(pen->name);
        // we don't free `pen`, it's just part of simple array. Shuffle it out.
        const int idx = ((int) (pen - pen_devices));
        SDL_assert((idx >= 0) && (idx < pen_device_count));
        if ( idx < (pen_device_count - 1) ) {
            SDL_memmove(&pen_devices[idx], &pen_devices[idx + 1], sizeof (*pen) * ((pen_device_count - idx) - 1));
        }
        SDL_assert(pen_device_count > 0);
        pen_device_count--;
        if (pen_device_count) {
            void *ptr = SDL_realloc(pen_devices, sizeof (*pen) * pen_device_count);  // shrink it down.
            if (ptr) {
                pen_devices = (SDL_Pen *) ptr;
            }
        } else {
            SDL_free(pen_devices);
            pen_devices = NULL;
        }
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    if (pen && SDL_EventEnabled(SDL_EVENT_PEN_PROXIMITY_OUT)) {
        SDL_Event event;
        SDL_zero(event);
        event.pproximity.type = SDL_EVENT_PEN_PROXIMITY_OUT;
        event.pproximity.timestamp = timestamp;
        event.pproximity.which = instance_id;
        SDL_PushEvent(&event);
    }
}
References FindPenByInstanceId(), SDL_Pen::name, NULL, pen_device_rwlock, SDL_assert, SDL_EVENT_PEN_PROXIMITY_OUT, SDL_EventEnabled(), SDL_free(), SDL_LockRWLockForWriting(), SDL_memmove, SDL_PushEvent(), SDL_realloc(), SDL_UnlockRWLock(), and SDL_zero.
SDL_SendPenAxis()
void SDL_SendPenAxis (Uint64 timestamp, SDL_PenID instance_id, SDL_Window * window, SDL_PenAxis axis, float value) extern
{
    SDL_assert((axis >= 0) && (axis < SDL_PEN_AXIS_COUNT));  // fix the backend if this triggers.
    bool send_event = false;
    SDL_PenInputFlags input_state = 0;
    float x = 0.0f;
    float y = 0.0f;
    // note that this locks for _reading_ because the lock protects the
    // pen_devices array from being reallocated from under us, not the data in it;
    // we assume only one thread (in the backend) is modifying an individual pen at
    // a time, so it can update input state cleanly here.
    SDL_LockRWLockForReading(pen_device_rwlock);
    SDL_Pen *pen = FindPenByInstanceId(instance_id);
    if (pen) {
        if (pen->axes[axis] != value) {
            pen->axes[axis] = value;  // we could do an SDL_SetAtomicInt here if we run into trouble...
            input_state = pen->input_state;
            x = pen->x;
            y = pen->y;
            send_event = true;
        }
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    if (send_event && SDL_EventEnabled(SDL_EVENT_PEN_AXIS)) {
        SDL_Event event;
        SDL_zero(event);
        event.paxis.type = SDL_EVENT_PEN_AXIS;
        event.paxis.timestamp = timestamp;
        event.paxis.windowID = window ? window->id : 0;
        event.paxis.which = instance_id;
        event.paxis.pen_state = input_state;
        event.paxis.x = x;
        event.paxis.y = y;
        event.paxis.axis = axis;
        event.paxis.value = value;
        SDL_PushEvent(&event);
        if (window && (axis == SDL_PEN_AXIS_PRESSURE) && (pen_touching == instance_id)) {
            SDL_Mouse *mouse = SDL_GetMouse();
            if (mouse && mouse->pen_touch_events) {
                const float normalized_x = x / (float)window->w;
                const float normalized_y = y / (float)window->h;
                SDL_SendTouchMotion(timestamp, SDL_PEN_TOUCHID, SDL_BUTTON_LEFT, window, normalized_x, normalized_y, value);
            }
        }
    }
}
References SDL_Pen::axes, FindPenByInstanceId(), SDL_Pen::input_state, pen_device_rwlock, SDL_Mouse::pen_touch_events, pen_touching, SDL_assert, SDL_BUTTON_LEFT, SDL_EVENT_PEN_AXIS, SDL_EventEnabled(), SDL_GetMouse(), SDL_LockRWLockForReading(), SDL_PEN_AXIS_COUNT, SDL_PEN_AXIS_PRESSURE, SDL_PEN_TOUCHID, SDL_PushEvent(), SDL_SendTouchMotion(), SDL_UnlockRWLock(), SDL_zero, SDL_Pen::x, and SDL_Pen::y.
SDL_SendPenButton()
void SDL_SendPenButton (Uint64 timestamp, SDL_PenID instance_id, SDL_Window * window, Uint8 button, bool down) extern
{
    bool send_event = false;
    SDL_PenInputFlags input_state = 0;
    float x = 0.0f;
    float y = 0.0f;
    if ((button < 1) || (button > 5)) {
        return; // clamp for now.
    }
    // note that this locks for _reading_ because the lock protects the
    // pen_devices array from being reallocated from under us, not the data in it;
    // we assume only one thread (in the backend) is modifying an individual pen at
    // a time, so it can update input state cleanly here.
    SDL_LockRWLockForReading(pen_device_rwlock);
    SDL_Pen *pen = FindPenByInstanceId(instance_id);
    if (pen) {
        input_state = pen->input_state;
        const Uint32 flag = (Uint32) (1u << button);
        const bool current = ((input_state & flag) != 0);
        x = pen->x;
        y = pen->y;
        if (down && !current) {
            input_state |= flag;
            send_event = true;
        } else if (!down && current) {
            input_state &= ~flag;
            send_event = true;
        }
        pen->input_state = input_state;  // we could do an SDL_SetAtomicInt here if we run into trouble...
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    if (send_event) {
        const SDL_EventType evtype = down ? SDL_EVENT_PEN_BUTTON_DOWN : SDL_EVENT_PEN_BUTTON_UP;
        if (SDL_EventEnabled(evtype)) {
            SDL_Event event;
            SDL_zero(event);
            event.pbutton.type = evtype;
            event.pbutton.timestamp = timestamp;
            event.pbutton.windowID = window ? window->id : 0;
            event.pbutton.which = instance_id;
            event.pbutton.pen_state = input_state;
            event.pbutton.x = x;
            event.pbutton.y = y;
            event.pbutton.button = button;
            event.pbutton.down = down;
            SDL_PushEvent(&event);
            if (window && (!pen_touching || (pen_touching == instance_id))) {
                SDL_Mouse *mouse = SDL_GetMouse();
                if (mouse && mouse->pen_mouse_events) {
                    static const Uint8 mouse_buttons[] = {
                        SDL_BUTTON_LEFT,
                        SDL_BUTTON_RIGHT,
                        SDL_BUTTON_MIDDLE,
                        SDL_BUTTON_X1,
                        SDL_BUTTON_X2
                    };
                    if (button < SDL_arraysize(mouse_buttons)) {
                        SDL_SendMouseButton(timestamp, window, SDL_PEN_MOUSEID, mouse_buttons[button], down);
                    }
                }
            }
        }
    }
}
References FindPenByInstanceId(), flag, SDL_Pen::input_state, pen_device_rwlock, SDL_Mouse::pen_mouse_events, pen_touching, SDL_arraysize, SDL_BUTTON_LEFT, SDL_BUTTON_MIDDLE, SDL_BUTTON_RIGHT, SDL_BUTTON_X1, SDL_BUTTON_X2, SDL_EVENT_PEN_BUTTON_DOWN, SDL_EVENT_PEN_BUTTON_UP, SDL_EventEnabled(), SDL_GetMouse(), SDL_LockRWLockForReading(), SDL_PEN_MOUSEID, SDL_PushEvent(), SDL_SendMouseButton(), SDL_UnlockRWLock(), SDL_zero, SDL_Pen::x, and SDL_Pen::y.
SDL_SendPenMotion()
void SDL_SendPenMotion (Uint64 timestamp, SDL_PenID instance_id, SDL_Window * window, float x, float y) extern
{
    bool send_event = false;
    SDL_PenInputFlags input_state = 0;
    // note that this locks for _reading_ because the lock protects the
    // pen_devices array from being reallocated from under us, not the data in it;
    // we assume only one thread (in the backend) is modifying an individual pen at
    // a time, so it can update input state cleanly here.
    SDL_LockRWLockForReading(pen_device_rwlock);
    SDL_Pen *pen = FindPenByInstanceId(instance_id);
    if (pen) {
        if ((pen->x != x) || (pen->y != y)) {
            pen->x = x;  // we could do an SDL_SetAtomicInt here if we run into trouble...
            pen->y = y;  // we could do an SDL_SetAtomicInt here if we run into trouble...
            input_state = pen->input_state;
            send_event = true;
        }
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    if (send_event && SDL_EventEnabled(SDL_EVENT_PEN_MOTION)) {
        SDL_Event event;
        SDL_zero(event);
        event.pmotion.type = SDL_EVENT_PEN_MOTION;
        event.pmotion.timestamp = timestamp;
        event.pmotion.windowID = window ? window->id : 0;
        event.pmotion.which = instance_id;
        event.pmotion.pen_state = input_state;
        event.pmotion.x = x;
        event.pmotion.y = y;
        SDL_PushEvent(&event);
        if (window) {
            SDL_Mouse *mouse = SDL_GetMouse();
            if (mouse) {
                if (pen_touching == instance_id) {
                    if (mouse->pen_mouse_events) {
                        SDL_SendMouseMotion(timestamp, window, SDL_PEN_MOUSEID, false, x, y);
                    }
                    if (mouse->pen_touch_events) {
                        const float normalized_x = x / (float)window->w;
                        const float normalized_y = y / (float)window->h;
                        SDL_SendTouchMotion(timestamp, SDL_PEN_TOUCHID, SDL_BUTTON_LEFT, window, normalized_x, normalized_y, pen->axes[SDL_PEN_AXIS_PRESSURE]);
                    }
                } else if (pen_touching == 0) {  // send mouse motion (without a pressed button) for pens that aren't touching.
                    // this might cause a little chaos if you have multiple pens hovering at the same time, but this seems unlikely in the real world, and also something you did to yourself.  :)
                    SDL_SendMouseMotion(timestamp, window, SDL_PEN_MOUSEID, false, x, y);
                }
            }
        }
    }
}
References SDL_Pen::axes, FindPenByInstanceId(), SDL_Pen::input_state, pen_device_rwlock, SDL_Mouse::pen_mouse_events, SDL_Mouse::pen_touch_events, pen_touching, SDL_BUTTON_LEFT, SDL_EVENT_PEN_MOTION, SDL_EventEnabled(), SDL_GetMouse(), SDL_LockRWLockForReading(), SDL_PEN_AXIS_PRESSURE, SDL_PEN_MOUSEID, SDL_PEN_TOUCHID, SDL_PushEvent(), SDL_SendMouseMotion(), SDL_SendTouchMotion(), SDL_UnlockRWLock(), SDL_zero, SDL_Pen::x, and SDL_Pen::y.
SDL_SendPenTouch()
void SDL_SendPenTouch (Uint64 timestamp, SDL_PenID instance_id, SDL_Window * window, bool eraser, bool down) extern
{
    bool send_event = false;
    SDL_PenInputFlags input_state = 0;
    float x = 0.0f;
    float y = 0.0f;
    // note that this locks for _reading_ because the lock protects the
    // pen_devices array from being reallocated from under us, not the data in it;
    // we assume only one thread (in the backend) is modifying an individual pen at
    // a time, so it can update input state cleanly here.
    SDL_LockRWLockForReading(pen_device_rwlock);
    SDL_Pen *pen = FindPenByInstanceId(instance_id);
    if (pen) {
        input_state = pen->input_state;
        x = pen->x;
        y = pen->y;
        if (down && ((input_state & SDL_PEN_INPUT_DOWN) == 0)) {
            input_state |= SDL_PEN_INPUT_DOWN;
            send_event = true;
        } else if (!down && (input_state & SDL_PEN_INPUT_DOWN)) {
            input_state &= ~SDL_PEN_INPUT_DOWN;
            send_event = true;
        }
        if (eraser && ((input_state & SDL_PEN_INPUT_ERASER_TIP) == 0)) {
            input_state |= SDL_PEN_INPUT_ERASER_TIP;
            send_event = true;
        } else if (!eraser && (input_state & SDL_PEN_INPUT_ERASER_TIP)) {
            input_state &= ~SDL_PEN_INPUT_ERASER_TIP;
            send_event = true;
        }
        pen->input_state = input_state;  // we could do an SDL_SetAtomicInt here if we run into trouble...
    }
    SDL_UnlockRWLock(pen_device_rwlock);
    if (send_event) {
        const SDL_EventType evtype = down ? SDL_EVENT_PEN_DOWN : SDL_EVENT_PEN_UP;
        if (SDL_EventEnabled(evtype)) {
            SDL_Event event;
            SDL_zero(event);
            event.ptouch.type = evtype;
            event.ptouch.timestamp = timestamp;
            event.ptouch.windowID = window ? window->id : 0;
            event.ptouch.which = instance_id;
            event.ptouch.pen_state = input_state;
            event.ptouch.x = x;
            event.ptouch.y = y;
            event.ptouch.eraser = eraser;
            event.ptouch.down = down;
            SDL_PushEvent(&event);
        }
        SDL_Mouse *mouse = SDL_GetMouse();
        if (mouse && window) {
            if (mouse->pen_mouse_events) {
                if (down) {
                    if (!pen_touching) {
                        SDL_SendMouseMotion(timestamp, window, SDL_PEN_MOUSEID, false, x, y);
                        SDL_SendMouseButton(timestamp, window, SDL_PEN_MOUSEID, SDL_BUTTON_LEFT, true);
                    }
                } else {
                    if (pen_touching == instance_id) {
                        SDL_SendMouseButton(timestamp, window, SDL_PEN_MOUSEID, SDL_BUTTON_LEFT, false);
                    }
                }
            }
            if (mouse->pen_touch_events) {
                const SDL_EventType touchtype = down ? SDL_EVENT_FINGER_DOWN : SDL_EVENT_FINGER_UP;
                const float normalized_x = x / (float)window->w;
                const float normalized_y = y / (float)window->h;
                if (!pen_touching || (pen_touching == instance_id)) {
                    SDL_SendTouch(timestamp, SDL_PEN_TOUCHID, SDL_BUTTON_LEFT, window, touchtype, normalized_x, normalized_y, pen->axes[SDL_PEN_AXIS_PRESSURE]);
                }
            }
        }
        if (down) {
            if (!pen_touching) {
                pen_touching = instance_id;
            }
        } else {
            if (pen_touching == instance_id) {
                pen_touching = 0;
            }
        }
    }
}
References SDL_Pen::axes, FindPenByInstanceId(), SDL_Pen::input_state, pen_device_rwlock, SDL_Mouse::pen_mouse_events, SDL_Mouse::pen_touch_events, pen_touching, SDL_BUTTON_LEFT, SDL_EVENT_FINGER_DOWN, SDL_EVENT_FINGER_UP, SDL_EVENT_PEN_DOWN, SDL_EVENT_PEN_UP, SDL_EventEnabled(), SDL_GetMouse(), SDL_LockRWLockForReading(), SDL_PEN_AXIS_PRESSURE, SDL_PEN_INPUT_DOWN, SDL_PEN_INPUT_ERASER_TIP, SDL_PEN_MOUSEID, SDL_PEN_TOUCHID, SDL_PushEvent(), SDL_SendMouseButton(), SDL_SendMouseMotion(), SDL_SendTouch(), SDL_UnlockRWLock(), SDL_zero, SDL_Pen::x, and SDL_Pen::y.