SDL3: hid_device_ref< T > Class Template Reference
hid_device_ref< T > Class Template Reference
Public Member Functions
T * GetObject () const
hid_device_ref (const hid_device_ref &rhs)
hid_device_ref (T *pObject=nullptr)
operator bool () const
T * operator-> () const
hid_device_ref & operator= (const hid_device_ref &rhs)
hid_device_ref & operator= (T *pObject)
void SetObject (T *pObject)
~hid_device_ref ()
Private Attributes
T * m_pObject
Constructor & Destructor Documentation
hid_device_ref() [1/2]
template<class T> hid_device_ref< T >::hid_device_ref (T * pObject = nullptr) inline
                                           : m_pObject( nullptr )
    {
        SetObject( pObject );
    }
References m_pObject, SetObject(), and T.
Referenced by hid_device_ref(), operator=(), and operator=().
hid_device_ref() [2/2]
template<class T> hid_device_ref< T >::hid_device_ref (const hid_device_ref< T > & rhs) inline
                                                : m_pObject( nullptr )
    {
        SetObject( rhs.GetObject() );
    }
References GetObject(), hid_device_ref(), m_pObject, and SetObject().
~hid_device_ref()
template<class T> hid_device_ref< T >::~hid_device_ref () inline
    {
        SetObject( nullptr );
    }
References SetObject().
Member Function Documentation
GetObject()
template<class T> T * hid_device_ref< T >::GetObject () const inline
    {
        return m_pObject;
    }
References m_pObject, and T.
Referenced by hid_device_ref(), and operator=().
operator bool()
template<class T> hid_device_ref< T >::operator bool () const inline
    {
        return ( m_pObject != nullptr );
    }
References m_pObject.
operator->()
template<class T> T * hid_device_ref< T >::operator-> () const inline
    {
        return m_pObject;
    }
References m_pObject, and T.
operator=() [1/2]
template<class T> hid_device_ref & hid_device_ref< T >::operator= (const hid_device_ref< T > & rhs) inline
    {
        SetObject( rhs.GetObject() );
        return *this;
    }
References GetObject(), hid_device_ref(), and SetObject().
operator=() [2/2]
template<class T> hid_device_ref & hid_device_ref< T >::operator= (T * pObject) inline
    {
        SetObject( pObject );
        return *this;
    }
References hid_device_ref(), SetObject(), and T.
SetObject()
template<class T> void hid_device_ref< T >::SetObject (T * pObject) inline
    {
        if ( m_pObject && m_pObject->DecrementRefCount() == 0 )
        {
            delete m_pObject;
        }
        m_pObject = pObject;
        if ( m_pObject )
        {
            m_pObject->IncrementRefCount();
        }
    }
References m_pObject, and T.
Referenced by hid_device_ref(), hid_device_ref(), operator=(), operator=(), and ~hid_device_ref().
Field Documentation
m_pObject
template<class T> T* hid_device_ref< T >::m_pObject private
Referenced by GetObject(), hid_device_ref(), hid_device_ref(), operator bool(), operator->(), and SetObject().
The documentation for this class was generated from the following file:
SDL-main/src/hidapi/android/hid.cpp