SDL3: SDL-main/src/video/SDL_clipboard.c File Reference
SDL_clipboard.c File Reference
#include "SDL_internal.h"
#include "SDL_clipboard_c.h"
#include "SDL_sysvideo.h"
#include "../events/SDL_events_c.h"
#include "../events/SDL_clipboardevents_c.h"
Functions
void SDL_CancelClipboardData (Uint32 sequence)
bool SDL_ClearClipboardData (void)
const void *SDLCALL SDL_ClipboardTextCallback (void *userdata, const char *mime_type, size_t *size)
char ** SDL_CopyClipboardMimeTypes (const char **clipboard_mime_types, size_t num_mime_types, bool temporary)
void SDL_FreeClipboardMimeTypes (SDL_VideoDevice *_this)
void * SDL_GetClipboardData (const char *mime_type, size_t *size)
char ** SDL_GetClipboardMimeTypes (size_t *num_mime_types)
char * SDL_GetClipboardText (void)
void * SDL_GetInternalClipboardData (SDL_VideoDevice *_this, const char *mime_type, size_t *size)
char * SDL_GetPrimarySelectionText (void)
static const char ** SDL_GetTextMimeTypes (SDL_VideoDevice *_this, size_t *num_mime_types)
bool SDL_HasClipboardData (const char *mime_type)
bool SDL_HasClipboardText (void)
bool SDL_HasInternalClipboardData (SDL_VideoDevice *_this, const char *mime_type)
bool SDL_HasPrimarySelectionText (void)
bool SDL_IsTextMimeType (const char *mime_type)
bool SDL_SaveClipboardMimeTypes (const char **mime_types, size_t num_mime_types)
bool SDL_SetClipboardData (SDL_ClipboardDataCallback callback, SDL_ClipboardCleanupCallback cleanup, void *userdata, const char **mime_types, size_t num_mime_types)
bool SDL_SetClipboardText (const char *text)
bool SDL_SetPrimarySelectionText (const char *text)
Function Documentation
SDL_CancelClipboardData()
void SDL_CancelClipboardData (Uint32 sequence)
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return;
    }
    if (sequence && sequence != _this->clipboard_sequence) {
        // This clipboard data was already canceled
        return;
    }
    if (_this->clipboard_cleanup) {
        _this->clipboard_cleanup(_this->clipboard_userdata);
    }
    SDL_FreeClipboardMimeTypes(_this);
    _this->clipboard_callback = NULL;
    _this->clipboard_cleanup = NULL;
    _this->clipboard_userdata = NULL;
}
References _this, NULL, SDL_FreeClipboardMimeTypes(), and SDL_GetVideoDevice().
Referenced by SDL_SendClipboardUpdate(), SDL_SetClipboardData(), and SDL_VideoQuit().
SDL_ClearClipboardData()
bool SDL_ClearClipboardData (void)
Clear the clipboard data.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
{
    return SDL_SetClipboardData(NULL, NULL, NULL, NULL, 0);
}
References NULL, and SDL_SetClipboardData().
Referenced by SDL_SetClipboardData(), and SDL_SetClipboardText().
SDL_ClipboardTextCallback()
const void *SDLCALL SDL_ClipboardTextCallback (void * userdata, const char * mime_type, size_t * size)
{
    char *text = (char *)userdata;
    if (text) {
        *size = SDL_strlen(text);
    } else {
        *size = 0;
    }
    return text;
}
References SDL_strlen(), and SDLCALL.
Referenced by SDL_SetClipboardText().
SDL_CopyClipboardMimeTypes()
char ** SDL_CopyClipboardMimeTypes (const char ** clipboard_mime_types, size_t num_mime_types, bool temporary)
{
    size_t allocSize = sizeof(char *);
    for (size_t i = 0; i < num_mime_types; i++) {
        allocSize += sizeof(char *) + SDL_strlen(clipboard_mime_types[i]) + 1;
    }
    char *ret;
    if (temporary)
        ret = (char *)SDL_AllocateTemporaryMemory(allocSize);
    else
        ret = (char *)SDL_malloc(allocSize);
    if (!ret) {
        return NULL;
    }
    char **result = (char **)ret;
    ret += sizeof(char *) * (num_mime_types + 1);
    for (size_t i = 0; i < num_mime_types; i++) {
        result[i] = ret;
        const char *mime_type = clipboard_mime_types[i];
        // Copy the whole string including the terminating null char
        char c;
        do {
            c = *ret++ = *mime_type++;
        } while (c != '\0');
    }
    result[num_mime_types] = NULL;
    return result;
}
References NULL, SDL_AllocateTemporaryMemory(), SDL_malloc(), and SDL_strlen().
Referenced by SDL_GetClipboardMimeTypes(), SDL_SetClipboardData(), and SDL_SetPrimarySelectionText().
SDL_FreeClipboardMimeTypes()
void SDL_FreeClipboardMimeTypes (SDL_VideoDevice * _this)
{
    if (_this->clipboard_mime_types) {
        for (size_t i = 0; i < _this->num_clipboard_mime_types; ++i) {
            SDL_free(_this->clipboard_mime_types[i]);
        }
        SDL_free(_this->clipboard_mime_types);
        _this->clipboard_mime_types = NULL;
        _this->num_clipboard_mime_types = 0;
    }
}
References _this, NULL, and SDL_free().
Referenced by SDL_CancelClipboardData(), and SDL_SaveClipboardMimeTypes().
SDL_GetClipboardData()
void * SDL_GetClipboardData (const char * mime_type, size_t * size)
Get the data from clipboard for a given mime type.
The size of text data does not include the terminator, but the text is guaranteed to be null terminated.
Parameters
mime_type the mime type to read from the clipboard.
size a pointer filled in with the length of the returned data.
Returns
the retrieved data buffer or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasClipboardData
SDL_SetClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t unused;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (!mime_type) {
        SDL_InvalidParamError("mime_type");
        return NULL;
    }
    if (!size) {
        size = &unused;
    }
    // Initialize size to empty, so implementations don't have to worry about it
    *size = 0;
    if (_this->GetClipboardData) {
        return _this->GetClipboardData(_this, mime_type, size);
    } else if (_this->GetClipboardText && SDL_IsTextMimeType(mime_type)) {
        char *text = _this->GetClipboardText(_this);
        if (text) {
            if (*text == '\0') {
                SDL_free(text);
                text = NULL;
            } else {
                *size = SDL_strlen(text);
            }
        }
        return text;
    } else {
        return SDL_GetInternalClipboardData(_this, mime_type, size);
    }
}
References _this, NULL, SDL_free(), SDL_GetInternalClipboardData(), SDL_GetVideoDevice(), SDL_InvalidParamError, SDL_IsTextMimeType(), SDL_strlen(), and SDL_UninitializedVideo().
Referenced by SDL_GetClipboardText().
SDL_GetClipboardMimeTypes()
char ** SDL_GetClipboardMimeTypes (size_t * num_mime_types)
Retrieve the list of mime types available in the clipboard.
Parameters
num_mime_types a pointer filled with the number of mime types, may be NULL.
Returns
a null terminated array of strings with mime types, or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (num_mime_types) {
        *num_mime_types = 0;
    }
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (num_mime_types) {
        *num_mime_types = _this->num_clipboard_mime_types;
    }
    return SDL_CopyClipboardMimeTypes((const char **)_this->clipboard_mime_types, _this->num_clipboard_mime_types, false);
}
References _this, NULL, SDL_CopyClipboardMimeTypes(), SDL_GetVideoDevice(), and SDL_UninitializedVideo().
SDL_GetClipboardText()
char * SDL_GetClipboardText (void)
Get UTF-8 text from the clipboard.
This functions returns an empty string if there was not enough memory left for a copy of the clipboard's content.
Returns
the clipboard text on success or an empty string on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasClipboardText
SDL_SetClipboardText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t i, num_mime_types;
    const char **text_mime_types;
    size_t length;
    char *text = NULL;
    if (!_this) {
        SDL_UninitializedVideo();
        return SDL_strdup("");
    }
    text_mime_types = SDL_GetTextMimeTypes(_this, &num_mime_types);
    for (i = 0; i < num_mime_types; ++i) {
        void *clipdata = SDL_GetClipboardData(text_mime_types[i], &length);
        if (clipdata) {
            text = (char *)clipdata;
            break;
        }
    }
    if (!text) {
        text = SDL_strdup("");
    }
    return text;
}
References _this, NULL, SDL_GetClipboardData(), SDL_GetTextMimeTypes(), SDL_GetVideoDevice(), SDL_strdup(), and SDL_UninitializedVideo().
SDL_GetInternalClipboardData()
void * SDL_GetInternalClipboardData (SDL_VideoDevice * _this, const char * mime_type, size_t * size)
{
    void *data = NULL;
    if (_this->clipboard_callback) {
        const void *provided_data = _this->clipboard_callback(_this->clipboard_userdata, mime_type, size);
        if (provided_data) {
            // Make a copy of it for the caller and guarantee null termination
            data = SDL_malloc(*size + sizeof(Uint32));
            if (data) {
                SDL_memcpy(data, provided_data, *size);
                SDL_memset((Uint8 *)data + *size, 0, sizeof(Uint32));
            }
        }
    }
    return data;
}
References _this, NULL, SDL_malloc(), SDL_memcpy, and SDL_memset.
Referenced by SDL_GetClipboardData().
SDL_GetPrimarySelectionText()
char * SDL_GetPrimarySelectionText (void)
Get UTF-8 text from the primary selection.
This functions returns an empty string if there was not enough memory left for a copy of the primary selection's content.
Returns
the primary selection text on success or an empty string on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HasPrimarySelectionText
SDL_SetPrimarySelectionText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        SDL_UninitializedVideo();
        return SDL_strdup("");
    }
    if (_this->GetPrimarySelectionText) {
        return _this->GetPrimarySelectionText(_this);
    } else {
        const char *text = _this->primary_selection_text;
        if (!text) {
            text = "";
        }
        return SDL_strdup(text);
    }
}
References _this, SDL_GetVideoDevice(), SDL_strdup(), and SDL_UninitializedVideo().
SDL_GetTextMimeTypes()
const char ** SDL_GetTextMimeTypes (SDL_VideoDevice * _this, size_t * num_mime_types) static
{
    if (_this->GetTextMimeTypes) {
        return _this->GetTextMimeTypes(_this, num_mime_types);
    } else {
        static const char *text_mime_types[] = {
            "text/plain;charset=utf-8"
        };
        *num_mime_types = SDL_arraysize(text_mime_types);
        return text_mime_types;
    }
}
References _this, and SDL_arraysize.
Referenced by SDL_GetClipboardText(), SDL_HasClipboardText(), and SDL_SetClipboardText().
SDL_HasClipboardData()
bool SDL_HasClipboardData (const char * mime_type)
Query whether there is data in the clipboard for the provided mime type.
Parameters
mime_type the mime type to check for data for.
Returns
true if there exists data in clipboard for the provided mime type, false if it does not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetClipboardData
SDL_GetClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!mime_type) {
        return SDL_InvalidParamError("mime_type");
    }
    if (_this->HasClipboardData) {
        return _this->HasClipboardData(_this, mime_type);
    } else if (_this->HasClipboardText && SDL_IsTextMimeType(mime_type)) {
        return _this->HasClipboardText(_this);
    } else {
        return SDL_HasInternalClipboardData(_this, mime_type);
    }
}
References _this, SDL_GetVideoDevice(), SDL_HasInternalClipboardData(), SDL_InvalidParamError, SDL_IsTextMimeType(), and SDL_UninitializedVideo().
Referenced by SDL_HasClipboardText().
SDL_HasClipboardText()
bool SDL_HasClipboardText (void)
Query whether the clipboard exists and contains a non-empty text string.
Returns
true if the clipboard has text, or false if it does not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetClipboardText
SDL_SetClipboardText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t i, num_mime_types;
    const char **text_mime_types;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    text_mime_types = SDL_GetTextMimeTypes(_this, &num_mime_types);
    for (i = 0; i < num_mime_types; ++i) {
        if (SDL_HasClipboardData(text_mime_types[i])) {
            return true;
        }
    }
    return false;
}
References _this, SDL_GetTextMimeTypes(), SDL_GetVideoDevice(), SDL_HasClipboardData(), and SDL_UninitializedVideo().
SDL_HasInternalClipboardData()
bool SDL_HasInternalClipboardData (SDL_VideoDevice * _this, const char * mime_type)
{
    size_t i;
    for (i = 0; i < _this->num_clipboard_mime_types; ++i) {
        if (SDL_strcmp(mime_type, _this->clipboard_mime_types[i]) == 0) {
            return true;
        }
    }
    return false;
}
References _this, and SDL_strcmp().
Referenced by SDL_HasClipboardData().
SDL_HasPrimarySelectionText()
bool SDL_HasPrimarySelectionText (void)
Query whether the primary selection exists and contains a non-empty text string.
Returns
true if the primary selection has text, or false if it does not.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPrimarySelectionText
SDL_SetPrimarySelectionText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (_this->HasPrimarySelectionText) {
        return _this->HasPrimarySelectionText(_this);
    } else {
        if (_this->primary_selection_text && _this->primary_selection_text[0] != '\0') {
            return true;
        } else {
            return false;
        }
    }
}
References _this, SDL_GetVideoDevice(), and SDL_UninitializedVideo().
SDL_IsTextMimeType()
bool SDL_IsTextMimeType (const char * mime_type)
{
    return (SDL_strncmp(mime_type, "text", 4) == 0);
}
References SDL_strncmp().
Referenced by SDL_GetClipboardData(), SDL_HasClipboardData(), and SDL_SetClipboardData().
SDL_SaveClipboardMimeTypes()
bool SDL_SaveClipboardMimeTypes (const char ** mime_types, size_t num_mime_types)
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    SDL_FreeClipboardMimeTypes(_this);
    if (mime_types && num_mime_types > 0) {
        size_t num_allocated = 0;
        _this->clipboard_mime_types = (char **)SDL_malloc(num_mime_types * sizeof(char *));
        if (_this->clipboard_mime_types) {
            for (size_t i = 0; i < num_mime_types; ++i) {
                _this->clipboard_mime_types[i] = SDL_strdup(mime_types[i]);
                if (_this->clipboard_mime_types[i]) {
                    ++num_allocated;
                }
            }
        }
        if (num_allocated < num_mime_types) {
            SDL_FreeClipboardMimeTypes(_this);
            return false;
        }
        _this->num_clipboard_mime_types = num_mime_types;
    }
    return true;
}
References _this, SDL_FreeClipboardMimeTypes(), SDL_GetVideoDevice(), SDL_malloc(), SDL_strdup(), and SDL_UninitializedVideo().
Referenced by SDL_SendClipboardUpdate(), and SDL_SetClipboardData().
SDL_SetClipboardData()
bool SDL_SetClipboardData (SDL_ClipboardDataCallback callback, SDL_ClipboardCleanupCallback cleanup, void * userdata, const char ** mime_types, size_t num_mime_types)
Offer clipboard data to the OS.
Tell the operating system that the application is offering clipboard data for each of the provided mime-types. Once another application requests the data the callback function will be called, allowing it to generate and respond with the data for the requested mime-type.
The size of text data does not include any terminator, and the text does not need to be null terminated (e.g. you can directly copy a portion of a document).
Parameters
callback a function pointer to the function that provides the clipboard data.
cleanup a function pointer to the function that cleans up the clipboard data.
userdata an opaque pointer that will be forwarded to the callbacks.
mime_types a list of mime-types that are being offered.
num_mime_types the number of mime-types in the mime_types list.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearClipboardData
SDL_GetClipboardData
SDL_HasClipboardData
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    // Parameter validation
    if (!((callback && mime_types && num_mime_types > 0) ||
          (!callback && !mime_types && num_mime_types == 0))) {
        return SDL_SetError("Invalid parameters");
    }
    SDL_CancelClipboardData(0);
    ++_this->clipboard_sequence;
    if (!_this->clipboard_sequence) {
        _this->clipboard_sequence = 1;
    }
    _this->clipboard_callback = callback;
    _this->clipboard_cleanup = cleanup;
    _this->clipboard_userdata = userdata;
    if (!SDL_SaveClipboardMimeTypes(mime_types, num_mime_types)) {
        SDL_ClearClipboardData();
        return false;
    }
    if (_this->SetClipboardData) {
        if (!_this->SetClipboardData(_this)) {
            return false;
        }
    } else if (_this->SetClipboardText) {
        char *text = NULL;
        size_t size;
        for (size_t i = 0; i < num_mime_types; ++i) {
            const char *mime_type = _this->clipboard_mime_types[i];
            if (SDL_IsTextMimeType(mime_type)) {
                const void *data = _this->clipboard_callback(_this->clipboard_userdata, mime_type, &size);
                if (data) {
                    text = (char *)SDL_malloc(size + 1);
                    SDL_memcpy(text, data, size);
                    text[size] = '\0';
                    if (!_this->SetClipboardText(_this, text)) {
                        SDL_free(text);
                        return false;
                    }
                    break;
                }
            }
        }
        if (text) {
            SDL_free(text);
        } else {
            if (!_this->SetClipboardText(_this, "")) {
                return false;
            }
        }
    }
    char **mime_types_copy = SDL_CopyClipboardMimeTypes(mime_types, num_mime_types, true);
    if (!mime_types_copy)
        return SDL_SetError("unable to copy current mime types");
    SDL_SendClipboardUpdate(true, mime_types_copy, num_mime_types);
    return true;
}
References _this, NULL, SDL_CancelClipboardData(), SDL_ClearClipboardData(), SDL_CopyClipboardMimeTypes(), SDL_free(), SDL_GetVideoDevice(), SDL_IsTextMimeType(), SDL_malloc(), SDL_memcpy, SDL_SaveClipboardMimeTypes(), SDL_SendClipboardUpdate(), SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_ClearClipboardData(), and SDL_SetClipboardText().
SDL_SetClipboardText()
bool SDL_SetClipboardText (const char * text)
CategoryClipboard
SDL provides access to the system clipboard, both for reading information from other processes and publishing information of its own.
This is not just text! SDL apps can access and publish data by mimetype.
Basic use (text)
Obtaining and publishing simple text to the system clipboard is as easy as calling SDL_GetClipboardText() and SDL_SetClipboardText(), respectively. These deal with C strings in UTF-8 encoding. Data transmission and encoding conversion is completely managed by SDL.
Clipboard callbacks (data other than text)
Things get more complicated when the clipboard contains something other than text. Not only can the system clipboard contain data of any type, in some cases it can contain the same data in different formats! For example, an image painting app might let the user copy a graphic to the clipboard, and offers it in .BMP, .JPG, or .PNG format for other apps to consume.
Obtaining clipboard data ("pasting") like this is a matter of calling SDL_GetClipboardData() and telling it the mimetype of the data you want. But how does one know if that format is available? SDL_HasClipboardData() can report if a specific mimetype is offered, and SDL_GetClipboardMimeTypes() can provide the entire list of mimetypes available, so the app can decide what to do with the data and what formats it can support.
Setting the clipboard ("copying") to arbitrary data is done with SDL_SetClipboardData. The app does not provide the data in this call, but rather the mimetypes it is willing to provide and a callback function. During the callback, the app will generate the data. This allows massive data sets to be provided to the clipboard, without any data being copied before it is explicitly requested. More specifically, it allows an app to offer data in multiple formats without providing a copy of all of them upfront. If the app has an image that it could provide in PNG or JPG format, it doesn't have to encode it to either of those unless and until something tries to paste it.
Primary Selection
The X11 and Wayland video targets have a concept of the "primary selection" in addition to the usual clipboard. This is generally highlighted (but not explicitly copied) text from various apps. SDL offers APIs for this through SDL_GetPrimarySelectionText() and SDL_SetPrimarySelectionText(). SDL offers these APIs on platforms without this concept, too, but only so far that it will keep a copy of a string that the app sets for later retrieval; the operating system will not ever attempt to change the string externally if it doesn't support a primary selection. Put UTF-8 text into the clipboard.
Parameters
text the text to store in the clipboard.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetClipboardText
SDL_HasClipboardText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    size_t num_mime_types;
    const char **text_mime_types;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (text && *text) {
        text_mime_types = SDL_GetTextMimeTypes(_this, &num_mime_types);
        return SDL_SetClipboardData(SDL_ClipboardTextCallback, SDL_free, SDL_strdup(text), text_mime_types, num_mime_types);
    }
    return SDL_ClearClipboardData();
}
References _this, SDL_ClearClipboardData(), SDL_ClipboardTextCallback(), SDL_free(), SDL_GetTextMimeTypes(), SDL_GetVideoDevice(), SDL_SetClipboardData(), SDL_strdup(), and SDL_UninitializedVideo().
SDL_SetPrimarySelectionText()
bool SDL_SetPrimarySelectionText (const char * text)
Put UTF-8 text into the primary selection.
Parameters
text the text to store in the primary selection.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetPrimarySelectionText
SDL_HasPrimarySelectionText
{
    SDL_VideoDevice *_this = SDL_GetVideoDevice();
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!text) {
        text = "";
    }
    if (_this->SetPrimarySelectionText) {
        if (!_this->SetPrimarySelectionText(_this, text)) {
            return false;
        }
    } else {
        SDL_free(_this->primary_selection_text);
        _this->primary_selection_text = SDL_strdup(text);
    }
    char **mime_types = SDL_CopyClipboardMimeTypes((const char **)_this->clipboard_mime_types, _this->num_clipboard_mime_types, true);
    if (!mime_types)
        return SDL_SetError("unable to copy current mime types");
    SDL_SendClipboardUpdate(true, mime_types, _this->num_clipboard_mime_types);
    return true;
}
References _this, SDL_CopyClipboardMimeTypes(), SDL_free(), SDL_GetVideoDevice(), SDL_SendClipboardUpdate(), SDL_SetError(), SDL_strdup(), and SDL_UninitializedVideo().