SDL3: SDL-main/src/events/SDL_keyboard_c.h File Reference
SDL_keyboard_c.h File Reference
#include "SDL_internal.h"
#include "SDL_keymap_c.h"
Macros
#define SDL_DEFAULT_KEYBOARD_ID 1
#define SDL_GLOBAL_KEYBOARD_ID 0
Functions
void SDL_AddKeyboard (SDL_KeyboardID keyboardID, const char *name, bool send_event)
bool SDL_HardwareKeyboardKeyPressed (void)
bool SDL_InitKeyboard (void)
bool SDL_IsKeyboard (Uint16 vendor, Uint16 product, int num_keys)
void SDL_QuitKeyboard (void)
void SDL_ReleaseAutoReleaseKeys (void)
void SDL_RemoveKeyboard (SDL_KeyboardID keyboardID, bool send_event)
void SDL_SendEditingText (const char *text, int start, int length)
void SDL_SendEditingTextCandidates (char **candidates, int num_candidates, int selected_candidate, bool horizontal)
bool SDL_SendKeyboardKey (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down)
bool SDL_SendKeyboardKeyAndKeycode (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, SDL_Keycode keycode, bool down)
bool SDL_SendKeyboardKeyAutoRelease (Uint64 timestamp, SDL_Scancode scancode)
bool SDL_SendKeyboardKeyIgnoreModifiers (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down)
void SDL_SendKeyboardText (const char *text)
void SDL_SendKeyboardUnicodeKey (Uint64 timestamp, Uint32 ch)
bool SDL_SetKeyboardFocus (SDL_Window *window)
void SDL_SetKeymap (SDL_Keymap *keymap, bool send_event)
void SDL_ToggleModState (SDL_Keymod modstate, bool toggle)
Macro Definition Documentation
SDL_DEFAULT_KEYBOARD_ID
#define SDL_DEFAULT_KEYBOARD_ID 1
Referenced by SDL_BLooper::_HandleKey(), handleKeyboardEvent(), and videoInit().
SDL_GLOBAL_KEYBOARD_ID
#define SDL_GLOBAL_KEYBOARD_ID 0
Referenced by SDL_ReleaseAutoReleaseKeys(), SDL_ResetKeyboard(), SDL_SendKeyboardKeyAutoRelease(), and SDL_SendKeyboardUnicodeKey().
Function Documentation
SDL_AddKeyboard()
void SDL_AddKeyboard (SDL_KeyboardID keyboardID, const char * name, bool send_event) extern
{
    int keyboard_index = SDL_GetKeyboardIndex(keyboardID);
    if (keyboard_index >= 0) {
        // We already know about this keyboard
        return;
    }
    SDL_assert(keyboardID != 0);
    SDL_KeyboardInstance *keyboards = (SDL_KeyboardInstance *)SDL_realloc(SDL_keyboards, (SDL_keyboard_count + 1) * sizeof(*keyboards));
    if (!keyboards) {
        return;
    }
    SDL_KeyboardInstance *instance = &keyboards[SDL_keyboard_count];
    instance->instance_id = keyboardID;
    instance->name = SDL_strdup(name ? name : "");
    SDL_keyboards = keyboards;
    ++SDL_keyboard_count;
    if (send_event) {
        SDL_Event event;
        SDL_zero(event);
        event.type = SDL_EVENT_KEYBOARD_ADDED;
        event.kdevice.which = keyboardID;
        SDL_PushEvent(&event);
    }
}
References SDL_KeyboardInstance::instance_id, SDL_KeyboardInstance::name, SDL_assert, SDL_EVENT_KEYBOARD_ADDED, SDL_GetKeyboardIndex(), SDL_keyboard_count, SDL_keyboards, SDL_PushEvent(), SDL_realloc(), SDL_strdup(), and SDL_zero.
Referenced by SDL_WSCONS_Init_Keyboard(), and videoInit().
SDL_HardwareKeyboardKeyPressed()
bool SDL_HardwareKeyboardKeyPressed (void) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    int scancode;
    for (scancode = SDL_SCANCODE_UNKNOWN; scancode < SDL_SCANCODE_COUNT; ++scancode) {
        if (keyboard->keysource[scancode] & KEYBOARD_HARDWARE) {
            return true;
        }
    }
    return keyboard->hardware_timestamp ? true : false;
}
References SDL_Keyboard::hardware_timestamp, KEYBOARD_HARDWARE, SDL_Keyboard::keysource, scancode, SDL_keyboard, SDL_SCANCODE_COUNT, SDL_SCANCODE_UNKNOWN, and true.
SDL_InitKeyboard()
bool SDL_InitKeyboard (void) extern
{
    SDL_AddHintCallback(SDL_HINT_KEYCODE_OPTIONS,
                        SDL_KeycodeOptionsChanged, &SDL_keyboard);
    return true;
}
References SDL_AddHintCallback(), SDL_HINT_KEYCODE_OPTIONS, SDL_keyboard, and SDL_KeycodeOptionsChanged().
Referenced by SDL_VideoInit().
SDL_IsKeyboard()
bool SDL_IsKeyboard (Uint16 vendor, Uint16 product, int num_keys) extern
{
    const int REAL_KEYBOARD_KEY_COUNT = 50;
    if (num_keys > 0 && num_keys < REAL_KEYBOARD_KEY_COUNT) {
        return false;
    }
    // Eventually we'll have a blacklist of devices that enumerate as keyboards but aren't really
    return true;
}
SDL_QuitKeyboard()
void SDL_QuitKeyboard (void) extern
{
    for (int i = SDL_keyboard_count; i--;) {
        SDL_RemoveKeyboard(SDL_keyboards[i].instance_id, false);
    }
    SDL_free(SDL_keyboards);
    SDL_keyboards = NULL;
    if (SDL_keyboard.keymap && SDL_keyboard.keymap->auto_release) {
        SDL_DestroyKeymap(SDL_keyboard.keymap);
        SDL_keyboard.keymap = NULL;
    }
    SDL_RemoveHintCallback(SDL_HINT_KEYCODE_OPTIONS,
                        SDL_KeycodeOptionsChanged, &SDL_keyboard);
}
References NULL, SDL_DestroyKeymap(), SDL_free(), SDL_HINT_KEYCODE_OPTIONS, SDL_keyboard, SDL_keyboard_count, SDL_keyboards, SDL_KeycodeOptionsChanged(), SDL_RemoveHintCallback(), and SDL_RemoveKeyboard().
Referenced by SDL_VideoInit(), and SDL_VideoQuit().
SDL_ReleaseAutoReleaseKeys()
void SDL_ReleaseAutoReleaseKeys (void) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    int scancode;
    if (keyboard->autorelease_pending) {
        for (scancode = SDL_SCANCODE_UNKNOWN; scancode < SDL_SCANCODE_COUNT; ++scancode) {
            if (keyboard->keysource[scancode] == KEYBOARD_AUTORELEASE) {
                SDL_SendKeyboardKeyInternal(0, KEYBOARD_AUTORELEASE, SDL_GLOBAL_KEYBOARD_ID, 0, (SDL_Scancode)scancode, false);
            }
        }
        keyboard->autorelease_pending = false;
    }
    if (keyboard->hardware_timestamp) {
        // Keep hardware keyboard "active" for 250 ms
        if (SDL_GetTicks() >= keyboard->hardware_timestamp + 250) {
            keyboard->hardware_timestamp = 0;
        }
    }
}
References SDL_Keyboard::autorelease_pending, SDL_Keyboard::hardware_timestamp, KEYBOARD_AUTORELEASE, SDL_Keyboard::keysource, scancode, SDL_GetTicks(), SDL_GLOBAL_KEYBOARD_ID, SDL_keyboard, SDL_SCANCODE_COUNT, SDL_SCANCODE_UNKNOWN, and SDL_SendKeyboardKeyInternal().
Referenced by SDL_PumpEventsInternal().
SDL_RemoveKeyboard()
void SDL_RemoveKeyboard (SDL_KeyboardID keyboardID, bool send_event) extern
{
    int keyboard_index = SDL_GetKeyboardIndex(keyboardID);
    if (keyboard_index < 0) {
        // We don't know about this keyboard
        return;
    }
    SDL_free(SDL_keyboards[keyboard_index].name);
    if (keyboard_index != SDL_keyboard_count - 1) {
        SDL_memmove(&SDL_keyboards[keyboard_index], &SDL_keyboards[keyboard_index + 1], (SDL_keyboard_count - keyboard_index - 1) * sizeof(SDL_keyboards[keyboard_index]));
    }
    --SDL_keyboard_count;
    if (send_event) {
        SDL_Event event;
        SDL_zero(event);
        event.type = SDL_EVENT_KEYBOARD_REMOVED;
        event.kdevice.which = keyboardID;
        SDL_PushEvent(&event);
    }
}
References SDL_EVENT_KEYBOARD_REMOVED, SDL_free(), SDL_GetKeyboardIndex(), SDL_keyboard_count, SDL_keyboards, SDL_memmove, SDL_PushEvent(), and SDL_zero.
Referenced by SDL_QuitKeyboard().
SDL_SendEditingText()
void SDL_SendEditingText (const char * text, int start, int length) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->focus || !SDL_TextInputActive(keyboard->focus)) {
        return;
    }
    if (!text) {
        return;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_TEXT_EDITING)) {
        SDL_Event event;
        event.type = SDL_EVENT_TEXT_EDITING;
        event.common.timestamp = 0;
        event.edit.windowID = keyboard->focus ? keyboard->focus->id : 0;
        event.edit.start = start;
        event.edit.length = length;
        event.edit.text = SDL_CreateTemporaryString(text);
        if (!event.edit.text) {
            return;
        }
        SDL_PushEvent(&event);
    }
}
References SDL_Keyboard::focus, SDL_Window::id, SDL_CreateTemporaryString(), SDL_EVENT_TEXT_EDITING, SDL_EventEnabled(), SDL_keyboard, SDL_PushEvent(), and SDL_TextInputActive().
Referenced by DBus_MessageFilter().
SDL_SendEditingTextCandidates()
void SDL_SendEditingTextCandidates (char ** candidates, int num_candidates, int selected_candidate, bool horizontal) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->focus || !SDL_TextInputActive(keyboard->focus)) {
        return;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_TEXT_EDITING_CANDIDATES)) {
        SDL_Event event;
        event.type = SDL_EVENT_TEXT_EDITING_CANDIDATES;
        event.common.timestamp = 0;
        event.edit.windowID = keyboard->focus ? keyboard->focus->id : 0;
        if (num_candidates > 0) {
            const char * const *event_candidates = CreateCandidatesForEvent(candidates, num_candidates);
            if (!event_candidates) {
                return;
            }
            event.edit_candidates.candidates = event_candidates;
            event.edit_candidates.num_candidates = num_candidates;
            event.edit_candidates.selected_candidate = selected_candidate;
            event.edit_candidates.horizontal = horizontal;
        } else {
            event.edit_candidates.candidates = NULL;
            event.edit_candidates.num_candidates = 0;
            event.edit_candidates.selected_candidate = -1;
            event.edit_candidates.horizontal = false;
        }
        SDL_PushEvent(&event);
    }
}
References CreateCandidatesForEvent(), SDL_Keyboard::focus, SDL_Window::id, NULL, SDL_EVENT_TEXT_EDITING_CANDIDATES, SDL_EventEnabled(), SDL_keyboard, SDL_PushEvent(), and SDL_TextInputActive().
SDL_SendKeyboardKey()
bool SDL_SendKeyboardKey (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down) extern
{
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_HARDWARE, keyboardID, rawcode, scancode, down);
}
References KEYBOARD_HARDWARE, scancode, and SDL_SendKeyboardKeyInternal().
Referenced by SDL_BLooper::_HandleKey(), handleKeyboardEvent(), SDL_ResetKeyboard(), Translate_to_keycode(), and updateKeyboard().
SDL_SendKeyboardKeyAndKeycode()
bool SDL_SendKeyboardKeyAndKeycode (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, SDL_Keycode keycode, bool down) extern
{
    if (down) {
        // Make sure we have this keycode in our keymap
        SetKeymapEntry(scancode, SDL_GetModState(), keycode);
    }
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_HARDWARE, keyboardID, rawcode, scancode, down);
}
References KEYBOARD_HARDWARE, keycode, scancode, SDL_GetModState(), SDL_SendKeyboardKeyInternal(), and SetKeymapEntry().
SDL_SendKeyboardKeyAutoRelease()
bool SDL_SendKeyboardKeyAutoRelease (Uint64 timestamp, SDL_Scancode scancode) extern
{
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_AUTORELEASE, SDL_GLOBAL_KEYBOARD_ID, 0, scancode, true);
}
References KEYBOARD_AUTORELEASE, scancode, SDL_GLOBAL_KEYBOARD_ID, and SDL_SendKeyboardKeyInternal().
SDL_SendKeyboardKeyIgnoreModifiers()
bool SDL_SendKeyboardKeyIgnoreModifiers (Uint64 timestamp, SDL_KeyboardID keyboardID, int rawcode, SDL_Scancode scancode, bool down) extern
{
    return SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_HARDWARE | KEYBOARD_IGNOREMODIFIERS, keyboardID, rawcode, scancode, down);
}
References KEYBOARD_HARDWARE, KEYBOARD_IGNOREMODIFIERS, scancode, and SDL_SendKeyboardKeyInternal().
SDL_SendKeyboardText()
void SDL_SendKeyboardText (const char * text) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (!keyboard->focus || !SDL_TextInputActive(keyboard->focus)) {
        return;
    }
    if (!text || !*text) {
        return;
    }
    // Don't post text events for unprintable characters
    if (SDL_iscntrl((unsigned char)*text)) {
        return;
    }
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_TEXT_INPUT)) {
        SDL_Event event;
        event.type = SDL_EVENT_TEXT_INPUT;
        event.common.timestamp = 0;
        event.text.windowID = keyboard->focus ? keyboard->focus->id : 0;
        event.text.text = SDL_CreateTemporaryString(text);
        if (!event.text.text) {
            return;
        }
        SDL_PushEvent(&event);
    }
}
References SDL_Keyboard::focus, SDL_Window::id, SDL_CreateTemporaryString(), SDL_EVENT_TEXT_INPUT, SDL_EventEnabled(), SDL_iscntrl(), SDL_keyboard, SDL_PushEvent(), and SDL_TextInputActive().
Referenced by SDL_BLooper::_HandleKey(), DBus_MessageFilter(), and Translate_to_text().
SDL_SendKeyboardUnicodeKey()
void SDL_SendKeyboardUnicodeKey (Uint64 timestamp, Uint32 ch) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    SDL_Keymod modstate = SDL_KMOD_NONE;
    SDL_Scancode scancode;
    if (ch == '\n') {
        ch = SDLK_RETURN;
    }
    scancode = SDL_GetKeymapScancode(keyboard->keymap, ch, &modstate);
    // Make sure we have this keycode in our keymap
    if (scancode == SDL_SCANCODE_UNKNOWN && ch < SDLK_SCANCODE_MASK) {
        scancode = GetNextReservedScancode();
        SetKeymapEntry(scancode, modstate, ch);
    }
    if (modstate & SDL_KMOD_SHIFT) {
        // If the character uses shift, press shift down
        SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, SDL_SCANCODE_LSHIFT, true);
    }
    // Send a keydown and keyup for the character
    SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, scancode, true);
    SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, scancode, false);
    if (modstate & SDL_KMOD_SHIFT) {
        // If the character uses shift, release shift
        SDL_SendKeyboardKeyInternal(timestamp, KEYBOARD_VIRTUAL, SDL_GLOBAL_KEYBOARD_ID, 0, SDL_SCANCODE_LSHIFT, false);
    }
}
References GetNextReservedScancode(), KEYBOARD_VIRTUAL, SDL_Keyboard::keymap, scancode, SDL_GetKeymapScancode(), SDL_GLOBAL_KEYBOARD_ID, SDL_keyboard, SDL_KMOD_NONE, SDL_KMOD_SHIFT, SDL_SCANCODE_LSHIFT, SDL_SCANCODE_UNKNOWN, SDL_SendKeyboardKeyInternal(), SDLK_RETURN, SDLK_SCANCODE_MASK, and SetKeymapEntry().
SDL_SetKeyboardFocus()
bool SDL_SetKeyboardFocus (SDL_Window * window) extern
{
    SDL_VideoDevice *video = SDL_GetVideoDevice();
    SDL_Keyboard *keyboard = &SDL_keyboard;
    SDL_Mouse *mouse = SDL_GetMouse();
    if (window) {
        if (!SDL_ObjectValid(window, SDL_OBJECT_TYPE_WINDOW) || window->is_destroying) {
            return SDL_SetError("Invalid window");
        }
    }
    if (keyboard->focus && !window) {
        // We won't get anymore keyboard messages, so reset keyboard state
        SDL_ResetKeyboard();
        // Also leave mouse relative mode
        if (mouse->relative_mode) {
            SDL_SetRelativeMouseMode(false);
            SDL_Window *focus = keyboard->focus;
            if ((focus->flags & SDL_WINDOW_MINIMIZED) != 0) {
                // We can't warp the mouse within minimized windows, so manually restore the position
                float x = focus->x + mouse->x;
                float y = focus->y + mouse->y;
                SDL_WarpMouseGlobal(x, y);
            }
        }
    }
    // See if the current window has lost focus
    if (keyboard->focus && keyboard->focus != window) {
        SDL_SendWindowEvent(keyboard->focus, SDL_EVENT_WINDOW_FOCUS_LOST, 0, 0);
        // Ensures IME compositions are committed
        if (SDL_TextInputActive(keyboard->focus)) {
            if (video && video->StopTextInput) {
                video->StopTextInput(video, keyboard->focus);
            }
        }
    }
    keyboard->focus = window;
    if (keyboard->focus) {
        SDL_SendWindowEvent(keyboard->focus, SDL_EVENT_WINDOW_FOCUS_GAINED, 0, 0);
        if (SDL_TextInputActive(keyboard->focus)) {
            if (video && video->StartTextInput) {
                video->StartTextInput(video, keyboard->focus, keyboard->focus->text_input_props);
            }
        }
    }
    SDL_UpdateRelativeMouseMode();
    return true;
}
References SDL_Window::flags, SDL_Keyboard::focus, SDL_Mouse::relative_mode, SDL_EVENT_WINDOW_FOCUS_GAINED, SDL_EVENT_WINDOW_FOCUS_LOST, SDL_GetMouse(), SDL_GetVideoDevice(), SDL_keyboard, SDL_OBJECT_TYPE_WINDOW, SDL_ObjectValid(), SDL_ResetKeyboard(), SDL_SendWindowEvent(), SDL_SetError(), SDL_SetRelativeMouseMode(), SDL_TextInputActive(), SDL_UpdateRelativeMouseMode(), SDL_WarpMouseGlobal(), SDL_WINDOW_MINIMIZED, SDL_VideoDevice::StartTextInput, SDL_VideoDevice::StopTextInput, SDL_Window::text_input_props, SDL_Mouse::x, SDL_Window::x, SDL_Mouse::y, and SDL_Window::y.
Referenced by SDL_BLooper::_HandleKeyboardFocus(), GDK_RegisterChangeNotifications(), SDL_DestroyWindow(), SDL_HideWindow(), SDL_OnApplicationDidEnterForeground(), SDL_OnApplicationWillEnterBackground(), and SDL_ShowWindow().
SDL_SetKeymap()
void SDL_SetKeymap (SDL_Keymap * keymap, bool send_event) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (keyboard->keymap && keyboard->keymap->auto_release) {
        SDL_DestroyKeymap(keyboard->keymap);
    }
    keyboard->keymap = keymap;
    if (keymap && !keymap->layout_determined) {
        keymap->layout_determined = true;
        // Detect French number row (all symbols)
        keymap->french_numbers = true;
        for (int i = SDL_SCANCODE_1; i <= SDL_SCANCODE_0; ++i) {
            if (SDL_isdigit(SDL_GetKeymapKeycode(keymap, (SDL_Scancode)i, SDL_KMOD_NONE)) ||
                !SDL_isdigit(SDL_GetKeymapKeycode(keymap, (SDL_Scancode)i, SDL_KMOD_SHIFT))) {
                keymap->french_numbers = false;
                break;
                }
        }
        // Detect non-Latin keymap
        keymap->thai_keyboard = false;
        keymap->latin_letters = false;
        for (int i = SDL_SCANCODE_A; i <= SDL_SCANCODE_D; ++i) {
            SDL_Keycode key = SDL_GetKeymapKeycode(keymap, (SDL_Scancode)i, SDL_KMOD_NONE);
            if (key <= 0xFF) {
                keymap->latin_letters = true;
                break;
            }
            if (key >= 0x0E00 && key <= 0x0E7F) {
                keymap->thai_keyboard = true;
                break;
            }
        }
    }
    if (send_event) {
        SDL_SendKeymapChangedEvent();
    }
}
References SDL_Keymap::auto_release, SDL_Keymap::french_numbers, SDL_Keyboard::keymap, SDL_Keymap::latin_letters, SDL_Keymap::layout_determined, SDL_DestroyKeymap(), SDL_GetKeymapKeycode(), SDL_isdigit(), SDL_keyboard, SDL_KMOD_NONE, SDL_KMOD_SHIFT, SDL_SCANCODE_0, SDL_SCANCODE_1, SDL_SCANCODE_A, SDL_SCANCODE_D, SDL_SendKeymapChangedEvent(), and SDL_Keymap::thai_keyboard.
SDL_ToggleModState()
void SDL_ToggleModState (SDL_Keymod modstate, bool toggle) extern
{
    SDL_Keyboard *keyboard = &SDL_keyboard;
    if (toggle) {
        keyboard->modstate |= modstate;
    } else {
        keyboard->modstate &= ~modstate;
    }
}
References SDL_Keyboard::modstate, and SDL_keyboard.