SDL3: SDL-main/include/SDL3/SDL_video.h File Reference
SDL_video.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_error.h>
#include <SDL3/SDL_pixels.h>
#include <SDL3/SDL_properties.h>
#include <SDL3/SDL_rect.h>
#include <SDL3/SDL_surface.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Data Structures
struct SDL_DisplayMode
Macros
#define SDL_GL_CONTEXT_DEBUG_FLAG 0x0001
#define SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG 0x0002
#define SDL_GL_CONTEXT_PROFILE_COMPATIBILITY 0x0002
#define SDL_GL_CONTEXT_PROFILE_CORE 0x0001
#define SDL_GL_CONTEXT_PROFILE_ES 0x0004
#define SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH 0x0001
#define SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE 0x0000
#define SDL_GL_CONTEXT_RESET_ISOLATION_FLAG 0x0008
#define SDL_GL_CONTEXT_RESET_LOSE_CONTEXT 0x0001
#define SDL_GL_CONTEXT_RESET_NO_NOTIFICATION 0x0000
#define SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG 0x0004
#define SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN "SDL.display.HDR_enabled"
#define SDL_PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER "SDL.display.KMSDRM.panel_orientation"
#define SDL_PROP_DISPLAY_WAYLAND_WL_OUTPUT_POINTER "SDL.display.wayland.wl_output"
#define SDL_PROP_GLOBAL_VIDEO_WAYLAND_WL_DISPLAY_POINTER "SDL.video.wayland.wl_display"
#define SDL_PROP_WINDOW_ANDROID_SURFACE_POINTER "SDL.window.android.surface"
#define SDL_PROP_WINDOW_ANDROID_WINDOW_POINTER "SDL.window.android.window"
#define SDL_PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER "SDL.window.cocoa.metal_view_tag"
#define SDL_PROP_WINDOW_COCOA_WINDOW_POINTER "SDL.window.cocoa.window"
#define SDL_PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN "SDL.window.create.always_on_top"
#define SDL_PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN "SDL.window.create.borderless"
#define SDL_PROP_WINDOW_CREATE_COCOA_VIEW_POINTER "SDL.window.create.cocoa.view"
#define SDL_PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER "SDL.window.create.cocoa.window"
#define SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN "SDL.window.create.constrain_popup"
#define SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID_STRING "SDL.window.create.emscripten.canvas_id"
#define SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING "SDL.window.create.emscripten.keyboard_element"
#define SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN "SDL.window.create.external_graphics_context"
#define SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER "SDL.window.create.flags"
#define SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN "SDL.window.create.focusable"
#define SDL_PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN "SDL.window.create.fullscreen"
#define SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER "SDL.window.create.height"
#define SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN "SDL.window.create.hidden"
#define SDL_PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN "SDL.window.create.high_pixel_density"
#define SDL_PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN "SDL.window.create.maximized"
#define SDL_PROP_WINDOW_CREATE_MENU_BOOLEAN "SDL.window.create.menu"
#define SDL_PROP_WINDOW_CREATE_METAL_BOOLEAN "SDL.window.create.metal"
#define SDL_PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN "SDL.window.create.minimized"
#define SDL_PROP_WINDOW_CREATE_MODAL_BOOLEAN "SDL.window.create.modal"
#define SDL_PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN "SDL.window.create.mouse_grabbed"
#define SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN "SDL.window.create.opengl"
#define SDL_PROP_WINDOW_CREATE_PARENT_POINTER "SDL.window.create.parent"
#define SDL_PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN "SDL.window.create.resizable"
#define SDL_PROP_WINDOW_CREATE_TITLE_STRING "SDL.window.create.title"
#define SDL_PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN "SDL.window.create.tooltip"
#define SDL_PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN "SDL.window.create.transparent"
#define SDL_PROP_WINDOW_CREATE_UTILITY_BOOLEAN "SDL.window.create.utility"
#define SDL_PROP_WINDOW_CREATE_VULKAN_BOOLEAN "SDL.window.create.vulkan"
#define SDL_PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN "SDL.window.create.wayland.create_egl_window"
#define SDL_PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN "SDL.window.create.wayland.surface_role_custom"
#define SDL_PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER "SDL.window.create.wayland.wl_surface"
#define SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER "SDL.window.create.width"
#define SDL_PROP_WINDOW_CREATE_WIN32_HWND_POINTER "SDL.window.create.win32.hwnd"
#define SDL_PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER "SDL.window.create.win32.pixel_format_hwnd"
#define SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER "SDL.window.create.x11.window"
#define SDL_PROP_WINDOW_CREATE_X_NUMBER "SDL.window.create.x"
#define SDL_PROP_WINDOW_CREATE_Y_NUMBER "SDL.window.create.y"
#define SDL_PROP_WINDOW_EMSCRIPTEN_CANVAS_ID_STRING "SDL.window.emscripten.canvas_id"
#define SDL_PROP_WINDOW_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING "SDL.window.emscripten.keyboard_element"
#define SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN "SDL.window.HDR_enabled"
#define SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT "SDL.window.HDR_headroom"
#define SDL_PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER "SDL.window.kmsdrm.dev_index"
#define SDL_PROP_WINDOW_KMSDRM_DRM_FD_NUMBER "SDL.window.kmsdrm.drm_fd"
#define SDL_PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER "SDL.window.kmsdrm.gbm_dev"
#define SDL_PROP_WINDOW_OPENVR_OVERLAY_ID_NUMBER "SDL.window.openvr.overlay_id"
#define SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT "SDL.window.SDR_white_level"
#define SDL_PROP_WINDOW_SHAPE_POINTER "SDL.window.shape"
#define SDL_PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER "SDL.window.uikit.metal_view_tag"
#define SDL_PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER "SDL.window.uikit.opengl.framebuffer"
#define SDL_PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER "SDL.window.uikit.opengl.renderbuffer"
#define SDL_PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER "SDL.window.uikit.opengl.resolve_framebuffer"
#define SDL_PROP_WINDOW_UIKIT_WINDOW_POINTER "SDL.window.uikit.window"
#define SDL_PROP_WINDOW_VIVANTE_DISPLAY_POINTER "SDL.window.vivante.display"
#define SDL_PROP_WINDOW_VIVANTE_SURFACE_POINTER "SDL.window.vivante.surface"
#define SDL_PROP_WINDOW_VIVANTE_WINDOW_POINTER "SDL.window.vivante.window"
#define SDL_PROP_WINDOW_WAYLAND_DISPLAY_POINTER "SDL.window.wayland.display"
#define SDL_PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER "SDL.window.wayland.egl_window"
#define SDL_PROP_WINDOW_WAYLAND_SURFACE_POINTER "SDL.window.wayland.surface"
#define SDL_PROP_WINDOW_WAYLAND_VIEWPORT_POINTER "SDL.window.wayland.viewport"
#define SDL_PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER "SDL.window.wayland.xdg_popup"
#define SDL_PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER "SDL.window.wayland.xdg_positioner"
#define SDL_PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER "SDL.window.wayland.xdg_surface"
#define SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING "SDL.window.wayland.xdg_toplevel_export_handle"
#define SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER "SDL.window.wayland.xdg_toplevel"
#define SDL_PROP_WINDOW_WIN32_HDC_POINTER "SDL.window.win32.hdc"
#define SDL_PROP_WINDOW_WIN32_HWND_POINTER "SDL.window.win32.hwnd"
#define SDL_PROP_WINDOW_WIN32_INSTANCE_POINTER "SDL.window.win32.instance"
#define SDL_PROP_WINDOW_X11_DISPLAY_POINTER "SDL.window.x11.display"
#define SDL_PROP_WINDOW_X11_SCREEN_NUMBER "SDL.window.x11.screen"
#define SDL_PROP_WINDOW_X11_WINDOW_NUMBER "SDL.window.x11.window"
#define SDL_WINDOW_ALWAYS_ON_TOP SDL_UINT64_C(0x0000000000010000)
#define SDL_WINDOW_BORDERLESS SDL_UINT64_C(0x0000000000000010)
#define SDL_WINDOW_EXTERNAL SDL_UINT64_C(0x0000000000000800)
#define SDL_WINDOW_FULLSCREEN SDL_UINT64_C(0x0000000000000001)
#define SDL_WINDOW_HIDDEN SDL_UINT64_C(0x0000000000000008)
#define SDL_WINDOW_HIGH_PIXEL_DENSITY SDL_UINT64_C(0x0000000000002000)
#define SDL_WINDOW_INPUT_FOCUS SDL_UINT64_C(0x0000000000000200)
#define SDL_WINDOW_KEYBOARD_GRABBED SDL_UINT64_C(0x0000000000100000)
#define SDL_WINDOW_MAXIMIZED SDL_UINT64_C(0x0000000000000080)
#define SDL_WINDOW_METAL SDL_UINT64_C(0x0000000020000000)
#define SDL_WINDOW_MINIMIZED SDL_UINT64_C(0x0000000000000040)
#define SDL_WINDOW_MODAL SDL_UINT64_C(0x0000000000001000)
#define SDL_WINDOW_MOUSE_CAPTURE SDL_UINT64_C(0x0000000000004000)
#define SDL_WINDOW_MOUSE_FOCUS SDL_UINT64_C(0x0000000000000400)
#define SDL_WINDOW_MOUSE_GRABBED SDL_UINT64_C(0x0000000000000100)
#define SDL_WINDOW_MOUSE_RELATIVE_MODE SDL_UINT64_C(0x0000000000008000)
#define SDL_WINDOW_NOT_FOCUSABLE SDL_UINT64_C(0x0000000080000000)
#define SDL_WINDOW_OCCLUDED SDL_UINT64_C(0x0000000000000004)
#define SDL_WINDOW_OPENGL SDL_UINT64_C(0x0000000000000002)
#define SDL_WINDOW_POPUP_MENU SDL_UINT64_C(0x0000000000080000)
#define SDL_WINDOW_RESIZABLE SDL_UINT64_C(0x0000000000000020)
#define SDL_WINDOW_SURFACE_VSYNC_ADAPTIVE (-1)
#define SDL_WINDOW_SURFACE_VSYNC_DISABLED 0
#define SDL_WINDOW_TOOLTIP SDL_UINT64_C(0x0000000000040000)
#define SDL_WINDOW_TRANSPARENT SDL_UINT64_C(0x0000000040000000)
#define SDL_WINDOW_UTILITY SDL_UINT64_C(0x0000000000020000)
#define SDL_WINDOW_VULKAN SDL_UINT64_C(0x0000000010000000)
#define SDL_WINDOWPOS_CENTERED SDL_WINDOWPOS_CENTERED_DISPLAY(0)
#define SDL_WINDOWPOS_CENTERED_DISPLAY(X)
#define SDL_WINDOWPOS_CENTERED_MASK 0x2FFF0000u
#define SDL_WINDOWPOS_ISCENTERED(X)
#define SDL_WINDOWPOS_ISUNDEFINED(X)
#define SDL_WINDOWPOS_UNDEFINED SDL_WINDOWPOS_UNDEFINED_DISPLAY(0)
#define SDL_WINDOWPOS_UNDEFINED_DISPLAY(X)
#define SDL_WINDOWPOS_UNDEFINED_MASK 0x1FFF0000u
Typedefs
typedef Uint32 SDL_DisplayID
typedef struct SDL_DisplayMode SDL_DisplayMode
typedef struct SDL_DisplayModeData SDL_DisplayModeData
typedef enum SDL_DisplayOrientation SDL_DisplayOrientation
typedef intptr_t SDL_EGLAttrib
typedef SDL_EGLAttrib *(SDLCALL * SDL_EGLAttribArrayCallback) (void *userdata)
typedef void * SDL_EGLConfig
typedef void * SDL_EGLDisplay
typedef int SDL_EGLint
typedef SDL_EGLint *(SDLCALL * SDL_EGLIntArrayCallback) (void *userdata, SDL_EGLDisplay display, SDL_EGLConfig config)
typedef void * SDL_EGLSurface
typedef enum SDL_FlashOperation SDL_FlashOperation
typedef enum SDL_GLAttr SDL_GLAttr
typedef struct SDL_GLContextState * SDL_GLContext
typedef Uint32 SDL_GLContextFlag
typedef Uint32 SDL_GLContextReleaseFlag
typedef Uint32 SDL_GLContextResetNotification
typedef Uint32 SDL_GLProfile
typedef SDL_HitTestResult(SDLCALL * SDL_HitTest) (SDL_Window *win, const SDL_Point *area, void *data)
typedef enum SDL_HitTestResult SDL_HitTestResult
typedef enum SDL_ProgressState SDL_ProgressState
typedef enum SDL_SystemTheme SDL_SystemTheme
typedef struct SDL_Window SDL_Window
typedef Uint64 SDL_WindowFlags
typedef Uint32 SDL_WindowID
Enumerations
enum SDL_DisplayOrientation {
SDL_ORIENTATION_UNKNOWN , SDL_ORIENTATION_LANDSCAPE , SDL_ORIENTATION_LANDSCAPE_FLIPPED , SDL_ORIENTATION_PORTRAIT ,
SDL_ORIENTATION_PORTRAIT_FLIPPED
}
enum SDL_FlashOperation { SDL_FLASH_CANCEL , SDL_FLASH_BRIEFLY , SDL_FLASH_UNTIL_FOCUSED }
enum SDL_GLAttr {
SDL_GL_RED_SIZE , SDL_GL_GREEN_SIZE , SDL_GL_BLUE_SIZE , SDL_GL_ALPHA_SIZE ,
SDL_GL_BUFFER_SIZE , SDL_GL_DOUBLEBUFFER , SDL_GL_DEPTH_SIZE , SDL_GL_STENCIL_SIZE ,
SDL_GL_ACCUM_RED_SIZE , SDL_GL_ACCUM_GREEN_SIZE , SDL_GL_ACCUM_BLUE_SIZE , SDL_GL_ACCUM_ALPHA_SIZE ,
SDL_GL_STEREO , SDL_GL_MULTISAMPLEBUFFERS , SDL_GL_MULTISAMPLESAMPLES , SDL_GL_ACCELERATED_VISUAL ,
SDL_GL_RETAINED_BACKING , SDL_GL_CONTEXT_MAJOR_VERSION , SDL_GL_CONTEXT_MINOR_VERSION , SDL_GL_CONTEXT_FLAGS ,
SDL_GL_CONTEXT_PROFILE_MASK , SDL_GL_SHARE_WITH_CURRENT_CONTEXT , SDL_GL_FRAMEBUFFER_SRGB_CAPABLE , SDL_GL_CONTEXT_RELEASE_BEHAVIOR ,
SDL_GL_CONTEXT_RESET_NOTIFICATION , SDL_GL_CONTEXT_NO_ERROR , SDL_GL_FLOATBUFFERS , SDL_GL_EGL_PLATFORM
}
enum SDL_HitTestResult {
SDL_HITTEST_NORMAL , SDL_HITTEST_DRAGGABLE , SDL_HITTEST_RESIZE_TOPLEFT , SDL_HITTEST_RESIZE_TOP ,
SDL_HITTEST_RESIZE_TOPRIGHT , SDL_HITTEST_RESIZE_RIGHT , SDL_HITTEST_RESIZE_BOTTOMRIGHT , SDL_HITTEST_RESIZE_BOTTOM ,
SDL_HITTEST_RESIZE_BOTTOMLEFT , SDL_HITTEST_RESIZE_LEFT
}
enum SDL_ProgressState {
SDL_PROGRESS_STATE_INVALID = -1 , SDL_PROGRESS_STATE_NONE , SDL_PROGRESS_STATE_INDETERMINATE , SDL_PROGRESS_STATE_NORMAL ,
SDL_PROGRESS_STATE_PAUSED , SDL_PROGRESS_STATE_ERROR
}
enum SDL_SystemTheme { SDL_SYSTEM_THEME_UNKNOWN , SDL_SYSTEM_THEME_LIGHT , SDL_SYSTEM_THEME_DARK }
Functions
SDL_DECLSPEC SDL_Window *SDLCALL SDL_CreatePopupWindow (SDL_Window *parent, int offset_x, int offset_y, int w, int h, SDL_WindowFlags flags)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_CreateWindow (const char *title, int w, int h, SDL_WindowFlags flags)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_CreateWindowWithProperties (SDL_PropertiesID props)
SDL_DECLSPEC void SDLCALL SDL_DestroyWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_DestroyWindowSurface (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_DisableScreenSaver (void)
SDL_DECLSPEC bool SDLCALL SDL_EnableScreenSaver (void)
SDL_DECLSPEC bool SDLCALL SDL_FlashWindow (SDL_Window *window, SDL_FlashOperation operation)
SDL_DECLSPEC bool SDLCALL SDL_GetClosestFullscreenDisplayMode (SDL_DisplayID displayID, int w, int h, float refresh_rate, bool include_high_density_modes, SDL_DisplayMode *closest)
SDL_DECLSPEC const SDL_DisplayMode *SDLCALL SDL_GetCurrentDisplayMode (SDL_DisplayID displayID)
SDL_DECLSPEC SDL_DisplayOrientation SDLCALL SDL_GetCurrentDisplayOrientation (SDL_DisplayID displayID)
SDL_DECLSPEC const char *SDLCALL SDL_GetCurrentVideoDriver (void)
SDL_DECLSPEC const SDL_DisplayMode *SDLCALL SDL_GetDesktopDisplayMode (SDL_DisplayID displayID)
SDL_DECLSPEC bool SDLCALL SDL_GetDisplayBounds (SDL_DisplayID displayID, SDL_Rect *rect)
SDL_DECLSPEC float SDLCALL SDL_GetDisplayContentScale (SDL_DisplayID displayID)
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetDisplayForPoint (const SDL_Point *point)
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetDisplayForRect (const SDL_Rect *rect)
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetDisplayForWindow (SDL_Window *window)
SDL_DECLSPEC const char *SDLCALL SDL_GetDisplayName (SDL_DisplayID displayID)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetDisplayProperties (SDL_DisplayID displayID)
SDL_DECLSPEC SDL_DisplayID *SDLCALL SDL_GetDisplays (int *count)
SDL_DECLSPEC bool SDLCALL SDL_GetDisplayUsableBounds (SDL_DisplayID displayID, SDL_Rect *rect)
SDL_DECLSPEC SDL_DisplayMode **SDLCALL SDL_GetFullscreenDisplayModes (SDL_DisplayID displayID, int *count)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetGrabbedWindow (void)
SDL_DECLSPEC SDL_DisplayOrientation SDLCALL SDL_GetNaturalDisplayOrientation (SDL_DisplayID displayID)
SDL_DECLSPEC int SDLCALL SDL_GetNumVideoDrivers (void)
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetPrimaryDisplay (void)
SDL_DECLSPEC SDL_SystemTheme SDLCALL SDL_GetSystemTheme (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetVideoDriver (int index)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowAspectRatio (SDL_Window *window, float *min_aspect, float *max_aspect)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowBordersSize (SDL_Window *window, int *top, int *left, int *bottom, int *right)
SDL_DECLSPEC float SDLCALL SDL_GetWindowDisplayScale (SDL_Window *window)
SDL_DECLSPEC SDL_WindowFlags SDLCALL SDL_GetWindowFlags (SDL_Window *window)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetWindowFromID (SDL_WindowID id)
SDL_DECLSPEC const SDL_DisplayMode *SDLCALL SDL_GetWindowFullscreenMode (SDL_Window *window)
SDL_DECLSPEC void *SDLCALL SDL_GetWindowICCProfile (SDL_Window *window, size_t *size)
SDL_DECLSPEC SDL_WindowID SDLCALL SDL_GetWindowID (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowKeyboardGrab (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowMaximumSize (SDL_Window *window, int *w, int *h)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowMinimumSize (SDL_Window *window, int *w, int *h)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowMouseGrab (SDL_Window *window)
SDL_DECLSPEC const SDL_Rect *SDLCALL SDL_GetWindowMouseRect (SDL_Window *window)
SDL_DECLSPEC float SDLCALL SDL_GetWindowOpacity (SDL_Window *window)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetWindowParent (SDL_Window *window)
SDL_DECLSPEC float SDLCALL SDL_GetWindowPixelDensity (SDL_Window *window)
SDL_DECLSPEC SDL_PixelFormat SDLCALL SDL_GetWindowPixelFormat (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowPosition (SDL_Window *window, int *x, int *y)
SDL_DECLSPEC SDL_ProgressState SDLCALL SDL_GetWindowProgressState (SDL_Window *window)
SDL_DECLSPEC float SDLCALL SDL_GetWindowProgressValue (SDL_Window *window)
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetWindowProperties (SDL_Window *window)
SDL_DECLSPEC SDL_Window **SDLCALL SDL_GetWindows (int *count)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSafeArea (SDL_Window *window, SDL_Rect *rect)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSize (SDL_Window *window, int *w, int *h)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSizeInPixels (SDL_Window *window, int *w, int *h)
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_GetWindowSurface (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSurfaceVSync (SDL_Window *window, int *vsync)
SDL_DECLSPEC const char *SDLCALL SDL_GetWindowTitle (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_HideWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_MaximizeWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_MinimizeWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_RaiseWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_RestoreWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_ScreenSaverEnabled (void)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowAlwaysOnTop (SDL_Window *window, bool on_top)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowAspectRatio (SDL_Window *window, float min_aspect, float max_aspect)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowBordered (SDL_Window *window, bool bordered)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowFocusable (SDL_Window *window, bool focusable)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowFullscreen (SDL_Window *window, bool fullscreen)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowFullscreenMode (SDL_Window *window, const SDL_DisplayMode *mode)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowHitTest (SDL_Window *window, SDL_HitTest callback, void *callback_data)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowIcon (SDL_Window *window, SDL_Surface *icon)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowKeyboardGrab (SDL_Window *window, bool grabbed)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMaximumSize (SDL_Window *window, int max_w, int max_h)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMinimumSize (SDL_Window *window, int min_w, int min_h)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowModal (SDL_Window *window, bool modal)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMouseGrab (SDL_Window *window, bool grabbed)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMouseRect (SDL_Window *window, const SDL_Rect *rect)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowOpacity (SDL_Window *window, float opacity)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowParent (SDL_Window *window, SDL_Window *parent)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowPosition (SDL_Window *window, int x, int y)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowProgressState (SDL_Window *window, SDL_ProgressState state)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowProgressValue (SDL_Window *window, float value)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowResizable (SDL_Window *window, bool resizable)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowShape (SDL_Window *window, SDL_Surface *shape)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowSize (SDL_Window *window, int w, int h)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowSurfaceVSync (SDL_Window *window, int vsync)
SDL_DECLSPEC bool SDLCALL SDL_SetWindowTitle (SDL_Window *window, const char *title)
SDL_DECLSPEC bool SDLCALL SDL_ShowWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_ShowWindowSystemMenu (SDL_Window *window, int x, int y)
SDL_DECLSPEC bool SDLCALL SDL_SyncWindow (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_UpdateWindowSurface (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_UpdateWindowSurfaceRects (SDL_Window *window, const SDL_Rect *rects, int numrects)
SDL_DECLSPEC bool SDLCALL SDL_WindowHasSurface (SDL_Window *window)
OpenGL support functions
SDL_DECLSPEC SDL_EGLConfig SDLCALL SDL_EGL_GetCurrentConfig (void)
SDL_DECLSPEC SDL_EGLDisplay SDLCALL SDL_EGL_GetCurrentDisplay (void)
SDL_DECLSPEC SDL_FunctionPointer SDLCALL SDL_EGL_GetProcAddress (const char *proc)
SDL_DECLSPEC SDL_EGLSurface SDLCALL SDL_EGL_GetWindowSurface (SDL_Window *window)
SDL_DECLSPEC void SDLCALL SDL_EGL_SetAttributeCallbacks (SDL_EGLAttribArrayCallback platformAttribCallback, SDL_EGLIntArrayCallback surfaceAttribCallback, SDL_EGLIntArrayCallback contextAttribCallback, void *userdata)
SDL_DECLSPEC SDL_GLContext SDLCALL SDL_GL_CreateContext (SDL_Window *window)
SDL_DECLSPEC bool SDLCALL SDL_GL_DestroyContext (SDL_GLContext context)
SDL_DECLSPEC bool SDLCALL SDL_GL_ExtensionSupported (const char *extension)
SDL_DECLSPEC bool SDLCALL SDL_GL_GetAttribute (SDL_GLAttr attr, int *value)
SDL_DECLSPEC SDL_GLContext SDLCALL SDL_GL_GetCurrentContext (void)
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GL_GetCurrentWindow (void)
SDL_DECLSPEC SDL_FunctionPointer SDLCALL SDL_GL_GetProcAddress (const char *proc)
SDL_DECLSPEC bool SDLCALL SDL_GL_GetSwapInterval (int *interval)
SDL_DECLSPEC bool SDLCALL SDL_GL_LoadLibrary (const char *path)
SDL_DECLSPEC bool SDLCALL SDL_GL_MakeCurrent (SDL_Window *window, SDL_GLContext context)
SDL_DECLSPEC void SDLCALL SDL_GL_ResetAttributes (void)
SDL_DECLSPEC bool SDLCALL SDL_GL_SetAttribute (SDL_GLAttr attr, int value)
SDL_DECLSPEC bool SDLCALL SDL_GL_SetSwapInterval (int interval)
SDL_DECLSPEC bool SDLCALL SDL_GL_SwapWindow (SDL_Window *window)
SDL_DECLSPEC void SDLCALL SDL_GL_UnloadLibrary (void)
Macro Definition Documentation
SDL_GL_CONTEXT_DEBUG_FLAG
#define SDL_GL_CONTEXT_DEBUG_FLAG 0x0001
Referenced by SDL_GL_SetAttribute().
SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG
#define SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG 0x0002
Referenced by SDL_GL_SetAttribute().
SDL_GL_CONTEXT_PROFILE_COMPATIBILITY
#define SDL_GL_CONTEXT_PROFILE_COMPATIBILITY 0x0002
OpenGL Compatibility Profile context
Referenced by SDL_GL_SetAttribute().
SDL_GL_CONTEXT_PROFILE_CORE
#define SDL_GL_CONTEXT_PROFILE_CORE 0x0001
OpenGL Core Profile context
Referenced by SDL_GL_SetAttribute().
SDL_GL_CONTEXT_PROFILE_ES
#define SDL_GL_CONTEXT_PROFILE_ES 0x0004
GLX_CONTEXT_ES2_PROFILE_BIT_EXT
Referenced by SDL_GL_ResetAttributes(), and SDL_GL_SetAttribute().
SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH
#define SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH 0x0001
Referenced by SDL_GL_GetAttribute(), and SDL_GL_ResetAttributes().
SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE
#define SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE 0x0000
Referenced by SDL_GL_GetAttribute().
SDL_GL_CONTEXT_RESET_ISOLATION_FLAG
#define SDL_GL_CONTEXT_RESET_ISOLATION_FLAG 0x0008
Referenced by SDL_GL_SetAttribute().
SDL_GL_CONTEXT_RESET_LOSE_CONTEXT
#define SDL_GL_CONTEXT_RESET_LOSE_CONTEXT 0x0001
SDL_GL_CONTEXT_RESET_NO_NOTIFICATION
#define SDL_GL_CONTEXT_RESET_NO_NOTIFICATION 0x0000
Referenced by SDL_GL_ResetAttributes().
SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG
#define SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG 0x0004
Referenced by SDL_GL_SetAttribute().
SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN
#define SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN "SDL.display.HDR_enabled"
Referenced by SDL_AddVideoDisplay().
SDL_PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER
#define SDL_PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER "SDL.display.KMSDRM.panel_orientation"
SDL_PROP_DISPLAY_WAYLAND_WL_OUTPUT_POINTER
#define SDL_PROP_DISPLAY_WAYLAND_WL_OUTPUT_POINTER "SDL.display.wayland.wl_output"
SDL_PROP_GLOBAL_VIDEO_WAYLAND_WL_DISPLAY_POINTER
#define SDL_PROP_GLOBAL_VIDEO_WAYLAND_WL_DISPLAY_POINTER "SDL.video.wayland.wl_display"
The pointer to the global wl_display object used by the Wayland video backend.
Can be set before the video subsystem is initialized to import an external wl_display object from an application or toolkit for use in SDL, or read after initialization to export the wl_display used by the Wayland video backend. Setting this property after the video subsystem has been initialized has no effect, and reading it when the video subsystem is uninitialized will either return the user provided value, if one was set prior to initialization, or NULL. See docs/README-wayland.md for more information.
SDL_PROP_WINDOW_ANDROID_SURFACE_POINTER
#define SDL_PROP_WINDOW_ANDROID_SURFACE_POINTER "SDL.window.android.surface"
SDL_PROP_WINDOW_ANDROID_WINDOW_POINTER
#define SDL_PROP_WINDOW_ANDROID_WINDOW_POINTER "SDL.window.android.window"
SDL_PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER
#define SDL_PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER "SDL.window.cocoa.metal_view_tag"
SDL_PROP_WINDOW_COCOA_WINDOW_POINTER
#define SDL_PROP_WINDOW_COCOA_WINDOW_POINTER "SDL.window.cocoa.window"
SDL_PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN "SDL.window.create.always_on_top"
SDL_PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN "SDL.window.create.borderless"
SDL_PROP_WINDOW_CREATE_COCOA_VIEW_POINTER
#define SDL_PROP_WINDOW_CREATE_COCOA_VIEW_POINTER "SDL.window.create.cocoa.view"
SDL_PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER
#define SDL_PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER "SDL.window.create.cocoa.window"
SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN "SDL.window.create.constrain_popup"
Referenced by SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID_STRING
#define SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID_STRING "SDL.window.create.emscripten.canvas_id"
SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING
#define SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING "SDL.window.create.emscripten.keyboard_element"
SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN "SDL.window.create.external_graphics_context"
Referenced by SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER
#define SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER "SDL.window.create.flags"
Referenced by SDL_CreatePopupWindow(), SDL_CreateWindow(), and SDL_GetWindowFlagProperties().
SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN "SDL.window.create.focusable"
SDL_PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN "SDL.window.create.fullscreen"
SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER
#define SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER "SDL.window.create.height"
Referenced by SDL_CreatePopupWindow(), SDL_CreateWindow(), and SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN "SDL.window.create.hidden"
SDL_PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN "SDL.window.create.high_pixel_density"
SDL_PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN "SDL.window.create.maximized"
SDL_PROP_WINDOW_CREATE_MENU_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_MENU_BOOLEAN "SDL.window.create.menu"
SDL_PROP_WINDOW_CREATE_METAL_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_METAL_BOOLEAN "SDL.window.create.metal"
SDL_PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN "SDL.window.create.minimized"
SDL_PROP_WINDOW_CREATE_MODAL_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_MODAL_BOOLEAN "SDL.window.create.modal"
SDL_PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN "SDL.window.create.mouse_grabbed"
SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN "SDL.window.create.opengl"
SDL_PROP_WINDOW_CREATE_PARENT_POINTER
#define SDL_PROP_WINDOW_CREATE_PARENT_POINTER "SDL.window.create.parent"
Referenced by SDL_CreatePopupWindow(), and SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN "SDL.window.create.resizable"
SDL_PROP_WINDOW_CREATE_TITLE_STRING
#define SDL_PROP_WINDOW_CREATE_TITLE_STRING "SDL.window.create.title"
Referenced by SDL_CreateWindow(), and SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN "SDL.window.create.tooltip"
SDL_PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN "SDL.window.create.transparent"
SDL_PROP_WINDOW_CREATE_UTILITY_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_UTILITY_BOOLEAN "SDL.window.create.utility"
SDL_PROP_WINDOW_CREATE_VULKAN_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_VULKAN_BOOLEAN "SDL.window.create.vulkan"
SDL_PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN "SDL.window.create.wayland.create_egl_window"
SDL_PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN
#define SDL_PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN "SDL.window.create.wayland.surface_role_custom"
SDL_PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER
#define SDL_PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER "SDL.window.create.wayland.wl_surface"
SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER
#define SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER "SDL.window.create.width"
Referenced by SDL_CreatePopupWindow(), SDL_CreateWindow(), and SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_CREATE_WIN32_HWND_POINTER
#define SDL_PROP_WINDOW_CREATE_WIN32_HWND_POINTER "SDL.window.create.win32.hwnd"
SDL_PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER
#define SDL_PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER "SDL.window.create.win32.pixel_format_hwnd"
SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER
#define SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER "SDL.window.create.x11.window"
SDL_PROP_WINDOW_CREATE_X_NUMBER
#define SDL_PROP_WINDOW_CREATE_X_NUMBER "SDL.window.create.x"
Referenced by SDL_CreatePopupWindow(), and SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_CREATE_Y_NUMBER
#define SDL_PROP_WINDOW_CREATE_Y_NUMBER "SDL.window.create.y"
Referenced by SDL_CreatePopupWindow(), and SDL_CreateWindowWithProperties().
SDL_PROP_WINDOW_EMSCRIPTEN_CANVAS_ID_STRING
#define SDL_PROP_WINDOW_EMSCRIPTEN_CANVAS_ID_STRING "SDL.window.emscripten.canvas_id"
SDL_PROP_WINDOW_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING
#define SDL_PROP_WINDOW_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING "SDL.window.emscripten.keyboard_element"
SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN
#define SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN "SDL.window.HDR_enabled"
Referenced by SDL_SetWindowHDRProperties().
SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT
#define SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT "SDL.window.HDR_headroom"
Referenced by SDL_SetWindowHDRProperties(), and UpdateHDRProperties().
SDL_PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER
#define SDL_PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER "SDL.window.kmsdrm.dev_index"
SDL_PROP_WINDOW_KMSDRM_DRM_FD_NUMBER
#define SDL_PROP_WINDOW_KMSDRM_DRM_FD_NUMBER "SDL.window.kmsdrm.drm_fd"
SDL_PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER
#define SDL_PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER "SDL.window.kmsdrm.gbm_dev"
SDL_PROP_WINDOW_OPENVR_OVERLAY_ID_NUMBER
#define SDL_PROP_WINDOW_OPENVR_OVERLAY_ID_NUMBER "SDL.window.openvr.overlay_id"
SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT
#define SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT "SDL.window.SDR_white_level"
Referenced by SDL_SetWindowHDRProperties(), and UpdateHDRProperties().
SDL_PROP_WINDOW_SHAPE_POINTER
#define SDL_PROP_WINDOW_SHAPE_POINTER "SDL.window.shape"
Referenced by SDL_OnWindowResized(), SDL_RenderApplyWindowShape(), and SDL_SetWindowShape().
SDL_PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER
#define SDL_PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER "SDL.window.uikit.metal_view_tag"
SDL_PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER
#define SDL_PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER "SDL.window.uikit.opengl.framebuffer"
SDL_PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER
#define SDL_PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER "SDL.window.uikit.opengl.renderbuffer"
SDL_PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER
#define SDL_PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER "SDL.window.uikit.opengl.resolve_framebuffer"
SDL_PROP_WINDOW_UIKIT_WINDOW_POINTER
#define SDL_PROP_WINDOW_UIKIT_WINDOW_POINTER "SDL.window.uikit.window"
SDL_PROP_WINDOW_VIVANTE_DISPLAY_POINTER
#define SDL_PROP_WINDOW_VIVANTE_DISPLAY_POINTER "SDL.window.vivante.display"
SDL_PROP_WINDOW_VIVANTE_SURFACE_POINTER
#define SDL_PROP_WINDOW_VIVANTE_SURFACE_POINTER "SDL.window.vivante.surface"
SDL_PROP_WINDOW_VIVANTE_WINDOW_POINTER
#define SDL_PROP_WINDOW_VIVANTE_WINDOW_POINTER "SDL.window.vivante.window"
SDL_PROP_WINDOW_WAYLAND_DISPLAY_POINTER
#define SDL_PROP_WINDOW_WAYLAND_DISPLAY_POINTER "SDL.window.wayland.display"
SDL_PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER
#define SDL_PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER "SDL.window.wayland.egl_window"
SDL_PROP_WINDOW_WAYLAND_SURFACE_POINTER
#define SDL_PROP_WINDOW_WAYLAND_SURFACE_POINTER "SDL.window.wayland.surface"
SDL_PROP_WINDOW_WAYLAND_VIEWPORT_POINTER
#define SDL_PROP_WINDOW_WAYLAND_VIEWPORT_POINTER "SDL.window.wayland.viewport"
SDL_PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER
#define SDL_PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER "SDL.window.wayland.xdg_popup"
SDL_PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER
#define SDL_PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER "SDL.window.wayland.xdg_positioner"
SDL_PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER
#define SDL_PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER "SDL.window.wayland.xdg_surface"
SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING
#define SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING "SDL.window.wayland.xdg_toplevel_export_handle"
SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER
#define SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER "SDL.window.wayland.xdg_toplevel"
SDL_PROP_WINDOW_WIN32_HDC_POINTER
#define SDL_PROP_WINDOW_WIN32_HDC_POINTER "SDL.window.win32.hdc"
SDL_PROP_WINDOW_WIN32_HWND_POINTER
#define SDL_PROP_WINDOW_WIN32_HWND_POINTER "SDL.window.win32.hwnd"
Referenced by windows_ShowFileDialog(), and windows_ShowFolderDialog().
SDL_PROP_WINDOW_WIN32_INSTANCE_POINTER
#define SDL_PROP_WINDOW_WIN32_INSTANCE_POINTER "SDL.window.win32.instance"
SDL_PROP_WINDOW_X11_DISPLAY_POINTER
#define SDL_PROP_WINDOW_X11_DISPLAY_POINTER "SDL.window.x11.display"
Referenced by SDL_Fcitx_UpdateTextInputArea().
SDL_PROP_WINDOW_X11_SCREEN_NUMBER
#define SDL_PROP_WINDOW_X11_SCREEN_NUMBER "SDL.window.x11.screen"
Referenced by SDL_Fcitx_UpdateTextInputArea().
SDL_PROP_WINDOW_X11_WINDOW_NUMBER
#define SDL_PROP_WINDOW_X11_WINDOW_NUMBER "SDL.window.x11.window"
Referenced by get_x11_window_handle(), and SDL_Fcitx_UpdateTextInputArea().
SDL_WINDOW_ALWAYS_ON_TOP
#define SDL_WINDOW_ALWAYS_ON_TOP SDL_UINT64_C(0x0000000000010000)
window should always be above others
Referenced by SDL_SetWindowAlwaysOnTop().
SDL_WINDOW_BORDERLESS
#define SDL_WINDOW_BORDERLESS SDL_UINT64_C(0x0000000000000010)
no window decoration
Referenced by SDL_CreateWindowWithProperties(), and SDL_SetWindowBordered().
SDL_WINDOW_EXTERNAL
#define SDL_WINDOW_EXTERNAL SDL_UINT64_C(0x0000000000000800)
window not created by SDL
Referenced by SDL_DestroyWindow(), SDL_FinishWindowCreation(), and SDL_RecreateWindow().
SDL_WINDOW_FULLSCREEN
#define SDL_WINDOW_FULLSCREEN SDL_UINT64_C(0x0000000000000001)
window is in fullscreen mode
Referenced by ApplyWindowFlags(), SDL_CreateWindowWithProperties(), SDL_GetDisplayForWindow(), SDL_GetDisplayForWindowPosition(), SDL_GetWindowFullscreenMode(), SDL_GetWindowPosition(), SDL_GetWindowSizeInPixels(), SDL_HideWindow(), SDL_OnWindowDisplayChanged(), SDL_OnWindowHidden(), SDL_OnWindowMinimized(), SDL_OnWindowRestored(), SDL_SendKeyboardKeyInternal(), SDL_SendWindowEvent(), SDL_SetWindowFullscreen(), SDL_ShouldMinimizeOnFocusLoss(), and SDL_UpdateFullscreenMode().
SDL_WINDOW_HIDDEN
#define SDL_WINDOW_HIDDEN SDL_UINT64_C(0x0000000000000008)
window is neither mapped onto the desktop nor shown in the taskbar/dock/window list; SDL_ShowWindow() is required for it to become visible
Referenced by SDL_CreateRendererWithProperties(), SDL_CreateWindowAndRenderer(), SDL_CreateWindowWithProperties(), SDL_FinishWindowCreation(), SDL_GetWindowPosition(), SDL_HideWindow(), SDL_MaximizeWindow(), SDL_MinimizeWindow(), SDL_RaiseWindow(), SDL_RecreateWindow(), SDL_RendererEventWatch(), SDL_RestoreWindow(), SDL_SendWindowEvent(), SDL_SetWindowFullscreen(), SDL_SetWindowKeyboardGrab(), SDL_SetWindowModal(), SDL_SetWindowMouseGrab(), SDL_ShowWindow(), and SDL_UnregisterTray().
SDL_WINDOW_HIGH_PIXEL_DENSITY
#define SDL_WINDOW_HIGH_PIXEL_DENSITY SDL_UINT64_C(0x0000000000002000)
window uses high pixel density back buffer if possible
SDL_WINDOW_INPUT_FOCUS
#define SDL_WINDOW_INPUT_FOCUS SDL_UINT64_C(0x0000000000000200)
window has input focus
Referenced by SDL_SendWindowEvent(), SDL_ShouldRelinquishPopupFocus(), and SDL_UpdateWindowGrab().
SDL_WINDOW_KEYBOARD_GRABBED
#define SDL_WINDOW_KEYBOARD_GRABBED SDL_UINT64_C(0x0000000000100000)
window has grabbed keyboard input
Referenced by ApplyWindowFlags(), SDL_GetGrabbedWindow(), SDL_GetWindowKeyboardGrab(), SDL_HideWindow(), SDL_SendKeyboardKeyInternal(), SDL_SetWindowKeyboardGrab(), and SDL_UpdateWindowGrab().
SDL_WINDOW_MAXIMIZED
#define SDL_WINDOW_MAXIMIZED SDL_UINT64_C(0x0000000000000080)
window is maximized
Referenced by ApplyWindowFlags(), SDL_CreateWindowWithProperties(), SDL_HideWindow(), SDL_MaximizeWindow(), SDL_OnWindowHidden(), SDL_RestoreWindow(), and SDL_SendWindowEvent().
SDL_WINDOW_METAL
#define SDL_WINDOW_METAL SDL_UINT64_C(0x0000000020000000)
window usable for Metal view
Referenced by SDL_CreateWindowWithProperties(), SDL_DefaultGraphicsBackends(), SDL_Metal_CreateView(), and SDL_RecreateWindow().
SDL_WINDOW_MINIMIZED
#define SDL_WINDOW_MINIMIZED SDL_UINT64_C(0x0000000000000040)
window is minimized
Referenced by ApplyWindowFlags(), SDL_CreateRendererWithProperties(), SDL_CreateWindowWithProperties(), SDL_HideWindow(), SDL_MinimizeWindow(), SDL_PerformWarpMouseInWindow(), SDL_RendererEventWatch(), SDL_RestoreWindow(), SDL_SendWindowEvent(), and SDL_SetKeyboardFocus().
SDL_WINDOW_MODAL
#define SDL_WINDOW_MODAL SDL_UINT64_C(0x0000000000001000)
window is modal
Referenced by ApplyWindowFlags(), SDL_CreateWindowWithProperties(), SDL_DestroyWindow(), SDL_RecreateWindow(), SDL_SetWindowModal(), and SDL_SetWindowParent().
SDL_WINDOW_MOUSE_CAPTURE
#define SDL_WINDOW_MOUSE_CAPTURE SDL_UINT64_C(0x0000000000004000)
window has mouse captured (unrelated to MOUSE_GRABBED)
Referenced by ConstrainMousePosition(), SDL_DestroyWindow(), SDL_MousePositionInWindow(), and SDL_UpdateMouseCapture().
SDL_WINDOW_MOUSE_FOCUS
#define SDL_WINDOW_MOUSE_FOCUS SDL_UINT64_C(0x0000000000000400)
window has mouse focus
Referenced by SDL_SendWindowEvent().
SDL_WINDOW_MOUSE_GRABBED
#define SDL_WINDOW_MOUSE_GRABBED SDL_UINT64_C(0x0000000000000100)
window has grabbed mouse input
Referenced by ApplyWindowFlags(), SDL_GetGrabbedWindow(), SDL_GetWindowMouseGrab(), SDL_HideWindow(), SDL_SetWindowMouseGrab(), and SDL_UpdateWindowGrab().
SDL_WINDOW_MOUSE_RELATIVE_MODE
#define SDL_WINDOW_MOUSE_RELATIVE_MODE SDL_UINT64_C(0x0000000000008000)
window has relative mode enabled
Referenced by SDL_GetWindowRelativeMouseMode(), SDL_PrivateSendMouseMotion(), SDL_SetWindowRelativeMouseMode(), and SDL_UpdateRelativeMouseMode().
SDL_WINDOW_NOT_FOCUSABLE
#define SDL_WINDOW_NOT_FOCUSABLE SDL_UINT64_C(0x0000000080000000)
window should not be focusable
Referenced by SDL_SetWindowFocusable(), and SDL_ShouldRelinquishPopupFocus().
SDL_WINDOW_OCCLUDED
#define SDL_WINDOW_OCCLUDED SDL_UINT64_C(0x0000000000000004)
window is occluded
Referenced by SDL_SendWindowEvent().
SDL_WINDOW_OPENGL
#define SDL_WINDOW_OPENGL SDL_UINT64_C(0x0000000000000002)
window usable with OpenGL context
Referenced by createWindow(), SDL_CreateWindowWithProperties(), SDL_DefaultGraphicsBackends(), SDL_DestroyWindow(), SDL_GL_CreateContext(), SDL_GL_MakeCurrent(), SDL_GL_SwapWindow(), SDL_Metal_CreateView(), and SDL_RecreateWindow().
SDL_WINDOW_POPUP_MENU
#define SDL_WINDOW_POPUP_MENU SDL_UINT64_C(0x0000000000080000)
window should be treated as a popup menu, requires a parent window
Referenced by SDL_CreatePopupWindow(), and SDL_CreateWindowWithProperties().
SDL_WINDOW_RESIZABLE
#define SDL_WINDOW_RESIZABLE SDL_UINT64_C(0x0000000000000020)
window can be resized
Referenced by SDL_MaximizeWindow(), and SDL_SetWindowResizable().
SDL_WINDOW_SURFACE_VSYNC_ADAPTIVE
#define SDL_WINDOW_SURFACE_VSYNC_ADAPTIVE (-1)
SDL_WINDOW_SURFACE_VSYNC_DISABLED
#define SDL_WINDOW_SURFACE_VSYNC_DISABLED 0
SDL_WINDOW_TOOLTIP
#define SDL_WINDOW_TOOLTIP SDL_UINT64_C(0x0000000000040000)
window should be treated as a tooltip and does not get mouse or keyboard focus, requires a parent window
Referenced by SDL_CreatePopupWindow(), and SDL_CreateWindowWithProperties().
SDL_WINDOW_TRANSPARENT
#define SDL_WINDOW_TRANSPARENT SDL_UINT64_C(0x0000000040000000)
window with transparent buffer
Referenced by SDL_ClaimWindowForGPUDevice(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_OnWindowResized(), and SDL_SetWindowShape().
SDL_WINDOW_UTILITY
#define SDL_WINDOW_UTILITY SDL_UINT64_C(0x0000000000020000)
window should be treated as a utility window, not showing in the task bar and window list
Referenced by SDL_CreateWindowWithProperties().
SDL_WINDOW_VULKAN
#define SDL_WINDOW_VULKAN SDL_UINT64_C(0x0000000010000000)
window usable for Vulkan surface
Referenced by SDL_CreateWindowWithProperties(), SDL_DestroyWindow(), SDL_Metal_CreateView(), SDL_RecreateWindow(), and SDL_Vulkan_CreateSurface().
SDL_WINDOWPOS_CENTERED
#define SDL_WINDOWPOS_CENTERED SDL_WINDOWPOS_CENTERED_DISPLAY(0)
Used to indicate that the window position should be centered.
This always uses the primary display.
Since
This macro is available since SDL 3.2.0.
SDL_WINDOWPOS_CENTERED_DISPLAY
#define SDL_WINDOWPOS_CENTERED_DISPLAY (X)
Value:
(SDL_WINDOWPOS_CENTERED_MASK|(X))
Used to indicate that the window position should be centered.
SDL_WINDOWPOS_CENTERED is the same, but always uses the primary display instead of specifying one.
Parameters
X the SDL_DisplayID of the display to use.
Since
This macro is available since SDL 3.2.0.
SDL_WINDOWPOS_CENTERED_MASK
#define SDL_WINDOWPOS_CENTERED_MASK 0x2FFF0000u
A magic value used with SDL_WINDOWPOS_CENTERED.
Generally this macro isn't used directly, but rather through SDL_WINDOWPOS_CENTERED or SDL_WINDOWPOS_CENTERED_DISPLAY.
Since
This macro is available since SDL 3.2.0.
SDL_WINDOWPOS_ISCENTERED
#define SDL_WINDOWPOS_ISCENTERED (X)
Value:
            (((X)&0xFFFF0000) == SDL_WINDOWPOS_CENTERED_MASK)
A macro to test if the window position is marked as "centered."
Parameters
X the window position value.
Since
This macro is available since SDL 3.2.0.
#define SDL_WINDOWPOS_ISCENTERED(X)    \
            (((X)&0xFFFF0000) == SDL_WINDOWPOS_CENTERED_MASK)
Referenced by SDL_CreateWindowWithProperties(), and SDL_SetWindowPosition().
SDL_WINDOWPOS_ISUNDEFINED
#define SDL_WINDOWPOS_ISUNDEFINED (X)
Value:
(((X)&0xFFFF0000) == SDL_WINDOWPOS_UNDEFINED_MASK)
A macro to test if the window position is marked as "undefined."
Parameters
X the window position value.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_CreateWindowWithProperties(), and SDL_SetWindowPosition().
SDL_WINDOWPOS_UNDEFINED
#define SDL_WINDOWPOS_UNDEFINED SDL_WINDOWPOS_UNDEFINED_DISPLAY(0)
Used to indicate that you don't care what the window position/display is.
This always uses the primary display.
Since
This macro is available since SDL 3.2.0.
Referenced by SDL_CreateWindowWithProperties().
SDL_WINDOWPOS_UNDEFINED_DISPLAY
#define SDL_WINDOWPOS_UNDEFINED_DISPLAY (X)
Value:
(SDL_WINDOWPOS_UNDEFINED_MASK|(X))
Used to indicate that you don't care what the window position is.
If you really don't care, SDL_WINDOWPOS_UNDEFINED is the same, but always uses the primary display instead of specifying one.
Parameters
X the SDL_DisplayID of the display to use.
Since
This macro is available since SDL 3.2.0.
SDL_WINDOWPOS_UNDEFINED_MASK
#define SDL_WINDOWPOS_UNDEFINED_MASK 0x1FFF0000u
A magic value used with SDL_WINDOWPOS_UNDEFINED.
Generally this macro isn't used directly, but rather through SDL_WINDOWPOS_UNDEFINED or SDL_WINDOWPOS_UNDEFINED_DISPLAY.
Since
This macro is available since SDL 3.2.0.
Typedef Documentation
SDL_DisplayID
typedef Uint32 SDL_DisplayID
CategoryVideo
SDL's video subsystem is largely interested in abstracting window management from the underlying operating system. You can create windows, manage them in various ways, set them fullscreen, and get events when interesting things happen with them, such as the mouse or keyboard interacting with a window.
The video subsystem is also interested in abstracting away some platform-specific differences in OpenGL: context creation, swapping buffers, etc. This may be crucial to your app, but also you are not required to use OpenGL at all. In fact, SDL can provide rendering to those windows as well, either with an easy-to-use 2D API or with a more-powerful GPU API . Of course, it can simply get out of your way and give you the window handles you need to use Vulkan, Direct3D, Metal, or whatever else you like directly, too.
The video subsystem covers a lot of functionality, out of necessity, so it is worth perusing the list of functions just to see what's available, but most apps can get by with simply creating a window and listening for events, so start with SDL_CreateWindow() and SDL_PollEvent(). This is a unique ID for a display for the time it is connected to the system, and is never reused for the lifetime of the application.
If the display is disconnected and reconnected, it will get a new ID.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
SDL_DisplayMode
typedef struct SDL_DisplayMode SDL_DisplayMode
The structure that defines a display mode.
Since
This struct is available since SDL 3.2.0.
See also
SDL_GetFullscreenDisplayModes
SDL_GetDesktopDisplayMode
SDL_GetCurrentDisplayMode
SDL_SetWindowFullscreenMode
SDL_GetWindowFullscreenMode
SDL_DisplayModeData
typedef struct SDL_DisplayModeData SDL_DisplayModeData
Internal display mode data.
This lives as a field in SDL_DisplayMode, as opaque data.
Since
This struct is available since SDL 3.2.0.
See also
SDL_DisplayMode
SDL_DisplayOrientation
typedef enum SDL_DisplayOrientation SDL_DisplayOrientation
Display orientation values; the way a display is rotated.
Since
This enum is available since SDL 3.2.0.
SDL_EGLAttrib
typedef intptr_t SDL_EGLAttrib
An EGL attribute, used when creating an EGL context.
Since
This datatype is available since SDL 3.2.0.
SDL_EGLAttribArrayCallback
typedef SDL_EGLAttrib *(SDLCALL * SDL_EGLAttribArrayCallback) (void *userdata)
EGL platform attribute initialization callback.
This is called when SDL is attempting to create an EGL context, to let the app add extra attributes to its eglGetPlatformDisplay() call.
The callback should return a pointer to an EGL attribute array terminated with EGL_NONE. If this function returns NULL, the SDL_CreateWindow process will fail gracefully.
The returned pointer should be allocated with SDL_malloc() and will be passed to SDL_free().
The arrays returned by each callback will be appended to the existing attribute arrays defined by SDL.
Parameters
userdata an app-controlled pointer that is passed to the callback.
Returns
a newly-allocated array of attributes, terminated with EGL_NONE.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_EGL_SetAttributeCallbacks
SDL_EGLConfig
typedef void* SDL_EGLConfig
Opaque type for an EGL config.
Since
This datatype is available since SDL 3.2.0.
SDL_EGLDisplay
typedef void* SDL_EGLDisplay
Opaque type for an EGL display.
Since
This datatype is available since SDL 3.2.0.
SDL_EGLint
typedef int SDL_EGLint
An EGL integer attribute, used when creating an EGL surface.
Since
This datatype is available since SDL 3.2.0.
SDL_EGLIntArrayCallback
typedef SDL_EGLint *(SDLCALL * SDL_EGLIntArrayCallback) (void *userdata, SDL_EGLDisplay display, SDL_EGLConfig config)
EGL surface/context attribute initialization callback types.
This is called when SDL is attempting to create an EGL surface, to let the app add extra attributes to its eglCreateWindowSurface() or eglCreateContext calls.
For convenience, the EGLDisplay and EGLConfig to use are provided to the callback.
The callback should return a pointer to an EGL attribute array terminated with EGL_NONE. If this function returns NULL, the SDL_CreateWindow process will fail gracefully.
The returned pointer should be allocated with SDL_malloc() and will be passed to SDL_free().
The arrays returned by each callback will be appended to the existing attribute arrays defined by SDL.
Parameters
userdata an app-controlled pointer that is passed to the callback.
display the EGL display to be used.
config the EGL config to be used.
Returns
a newly-allocated array of attributes, terminated with EGL_NONE.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_EGL_SetAttributeCallbacks
SDL_EGLSurface
typedef void* SDL_EGLSurface
Opaque type for an EGL surface.
Since
This datatype is available since SDL 3.2.0.
SDL_FlashOperation
typedef enum SDL_FlashOperation SDL_FlashOperation
Window flash operation.
Since
This enum is available since SDL 3.2.0.
SDL_GLAttr
typedef enum SDL_GLAttr SDL_GLAttr
An enumeration of OpenGL configuration attributes.
While you can set most OpenGL attributes normally, the attributes listed above must be known before SDL creates the window that will be used with the OpenGL context. These attributes are set and read with SDL_GL_SetAttribute() and SDL_GL_GetAttribute().
In some cases, these attributes are minimum requests; the GL does not promise to give you exactly what you asked for. It's possible to ask for a 16-bit depth buffer and get a 24-bit one instead, for example, or to ask for no stencil buffer and still have one available. Context creation should fail if the GL can't provide your requested attributes at a minimum, but you should check to see exactly what you got.
Since
This enum is available since SDL 3.2.0.
SDL_GLContext
typedef struct SDL_GLContextState* SDL_GLContext
An opaque handle to an OpenGL context.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_GL_CreateContext
SDL_GLContextFlag
typedef Uint32 SDL_GLContextFlag
Possible flags to be set for the SDL_GL_CONTEXT_FLAGS attribute.
Since
This datatype is available since SDL 3.2.0.
SDL_GLContextReleaseFlag
typedef Uint32 SDL_GLContextReleaseFlag
Possible values to be set for the SDL_GL_CONTEXT_RELEASE_BEHAVIOR attribute.
Since
This datatype is available since SDL 3.2.0.
SDL_GLContextResetNotification
typedef Uint32 SDL_GLContextResetNotification
Possible values to be set SDL_GL_CONTEXT_RESET_NOTIFICATION attribute.
Since
This datatype is available since SDL 3.2.0.
SDL_GLProfile
typedef Uint32 SDL_GLProfile
Possible values to be set for the SDL_GL_CONTEXT_PROFILE_MASK attribute.
Since
This datatype is available since SDL 3.2.0.
SDL_HitTest
typedef SDL_HitTestResult(SDLCALL * SDL_HitTest) (SDL_Window *win, const SDL_Point *area, void *data)
Callback used for hit-testing.
Parameters
win the SDL_Window where hit-testing was set on.
area an SDL_Point which should be hit-tested.
data what was passed as callback_data to SDL_SetWindowHitTest().
Returns
an SDL_HitTestResult value.
See also
SDL_SetWindowHitTest
SDL_HitTestResult
typedef enum SDL_HitTestResult SDL_HitTestResult
Possible return values from the SDL_HitTest callback.
Thread Safety
This function should only be called on the main thread.
Since
This enum is available since SDL 3.2.0.
See also
SDL_HitTest
SDL_ProgressState
typedef enum SDL_ProgressState SDL_ProgressState
Window progress state
Since
This enum is available since SDL 3.2.8.
SDL_SystemTheme
typedef enum SDL_SystemTheme SDL_SystemTheme
System theme.
Since
This enum is available since SDL 3.2.0.
SDL_Window
typedef struct SDL_Window SDL_Window
The struct used as an opaque handle to a window.
Since
This struct is available since SDL 3.2.0.
See also
SDL_CreateWindow
SDL_WindowFlags
typedef Uint64 SDL_WindowFlags
The flags on a window.
These cover a lot of true/false, or on/off, window state. Some of it is immutable after being set through SDL_CreateWindow(), some of it can be changed on existing windows by the app, and some of it might be altered by the user or system outside of the app's control.
When creating windows with SDL_WINDOW_RESIZABLE, SDL will constrain resizable windows to the dimensions recommended by the compositor to fit it within the usable desktop space, although some compositors will do this automatically without intervention as well. Use SDL_SetWindowResizable after creation instead if you wish to create a window with a specific size.
Since
This datatype is available since SDL 3.2.0.
See also
SDL_GetWindowFlags
SDL_WindowID
typedef Uint32 SDL_WindowID
This is a unique ID for a window.
The value 0 is an invalid ID.
Since
This datatype is available since SDL 3.2.0.
Enumeration Type Documentation
SDL_DisplayOrientation
enum SDL_DisplayOrientation
Display orientation values; the way a display is rotated.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_ORIENTATION_UNKNOWN
The display orientation can't be determined
SDL_ORIENTATION_LANDSCAPE
The display is in landscape mode, with the right side up, relative to portrait mode
SDL_ORIENTATION_LANDSCAPE_FLIPPED
The display is in landscape mode, with the left side up, relative to portrait mode
SDL_ORIENTATION_PORTRAIT
The display is in portrait mode
SDL_ORIENTATION_PORTRAIT_FLIPPED
The display is in portrait mode, upside down
{
    SDL_ORIENTATION_UNKNOWN,            /**< The display orientation can't be determined */
    SDL_ORIENTATION_LANDSCAPE,          /**< The display is in landscape mode, with the right side up, relative to portrait mode */
    SDL_ORIENTATION_LANDSCAPE_FLIPPED,  /**< The display is in landscape mode, with the left side up, relative to portrait mode */
    SDL_ORIENTATION_PORTRAIT,           /**< The display is in portrait mode */
    SDL_ORIENTATION_PORTRAIT_FLIPPED    /**< The display is in portrait mode, upside down */
} SDL_DisplayOrientation;
SDL_FlashOperation
enum SDL_FlashOperation
Window flash operation.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_FLASH_CANCEL
Cancel any window flash state
SDL_FLASH_BRIEFLY
Flash the window briefly to get attention
SDL_FLASH_UNTIL_FOCUSED
Flash the window until it gets focus
{
    SDL_FLASH_CANCEL,                   /**< Cancel any window flash state */
    SDL_FLASH_BRIEFLY,                  /**< Flash the window briefly to get attention */
    SDL_FLASH_UNTIL_FOCUSED             /**< Flash the window until it gets focus */
} SDL_FlashOperation;
SDL_GLAttr
enum SDL_GLAttr
An enumeration of OpenGL configuration attributes.
While you can set most OpenGL attributes normally, the attributes listed above must be known before SDL creates the window that will be used with the OpenGL context. These attributes are set and read with SDL_GL_SetAttribute() and SDL_GL_GetAttribute().
In some cases, these attributes are minimum requests; the GL does not promise to give you exactly what you asked for. It's possible to ask for a 16-bit depth buffer and get a 24-bit one instead, for example, or to ask for no stencil buffer and still have one available. Context creation should fail if the GL can't provide your requested attributes at a minimum, but you should check to see exactly what you got.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_GL_RED_SIZE
the minimum number of bits for the red channel of the color buffer; defaults to 8.
SDL_GL_GREEN_SIZE
the minimum number of bits for the green channel of the color buffer; defaults to 8.
SDL_GL_BLUE_SIZE
the minimum number of bits for the blue channel of the color buffer; defaults to 8.
SDL_GL_ALPHA_SIZE
the minimum number of bits for the alpha channel of the color buffer; defaults to 8.
SDL_GL_BUFFER_SIZE
the minimum number of bits for frame buffer size; defaults to 0.
SDL_GL_DOUBLEBUFFER
whether the output is single or double buffered; defaults to double buffering on.
SDL_GL_DEPTH_SIZE
the minimum number of bits in the depth buffer; defaults to 16.
SDL_GL_STENCIL_SIZE
the minimum number of bits in the stencil buffer; defaults to 0.
SDL_GL_ACCUM_RED_SIZE
the minimum number of bits for the red channel of the accumulation buffer; defaults to 0.
SDL_GL_ACCUM_GREEN_SIZE
the minimum number of bits for the green channel of the accumulation buffer; defaults to 0.
SDL_GL_ACCUM_BLUE_SIZE
the minimum number of bits for the blue channel of the accumulation buffer; defaults to 0.
SDL_GL_ACCUM_ALPHA_SIZE
the minimum number of bits for the alpha channel of the accumulation buffer; defaults to 0.
SDL_GL_STEREO
whether the output is stereo 3D; defaults to off.
SDL_GL_MULTISAMPLEBUFFERS
the number of buffers used for multisample anti-aliasing; defaults to 0.
SDL_GL_MULTISAMPLESAMPLES
the number of samples used around the current pixel used for multisample anti-aliasing.
SDL_GL_ACCELERATED_VISUAL
set to 1 to require hardware acceleration, set to 0 to force software rendering; defaults to allow either.
SDL_GL_RETAINED_BACKING
not used (deprecated).
SDL_GL_CONTEXT_MAJOR_VERSION
OpenGL context major version.
SDL_GL_CONTEXT_MINOR_VERSION
OpenGL context minor version.
SDL_GL_CONTEXT_FLAGS
some combination of 0 or more of elements of the SDL_GLContextFlag enumeration; defaults to 0.
SDL_GL_CONTEXT_PROFILE_MASK
type of GL context (Core, Compatibility, ES). See SDL_GLProfile; default value depends on platform.
SDL_GL_SHARE_WITH_CURRENT_CONTEXT
OpenGL context sharing; defaults to 0.
SDL_GL_FRAMEBUFFER_SRGB_CAPABLE
requests sRGB capable visual; defaults to 0.
SDL_GL_CONTEXT_RELEASE_BEHAVIOR
sets context the release behavior. See SDL_GLContextReleaseFlag; defaults to FLUSH.
SDL_GL_CONTEXT_RESET_NOTIFICATION
set context reset notification. See SDL_GLContextResetNotification; defaults to NO_NOTIFICATION.
SDL_GL_CONTEXT_NO_ERROR
SDL_GL_FLOATBUFFERS
SDL_GL_EGL_PLATFORM
{
    SDL_GL_RED_SIZE,                    /**< the minimum number of bits for the red channel of the color buffer; defaults to 8. */
    SDL_GL_GREEN_SIZE,                  /**< the minimum number of bits for the green channel of the color buffer; defaults to 8. */
    SDL_GL_BLUE_SIZE,                   /**< the minimum number of bits for the blue channel of the color buffer; defaults to 8. */
    SDL_GL_ALPHA_SIZE,                  /**< the minimum number of bits for the alpha channel of the color buffer; defaults to 8. */
    SDL_GL_BUFFER_SIZE,                 /**< the minimum number of bits for frame buffer size; defaults to 0. */
    SDL_GL_DOUBLEBUFFER,                /**< whether the output is single or double buffered; defaults to double buffering on. */
    SDL_GL_DEPTH_SIZE,                  /**< the minimum number of bits in the depth buffer; defaults to 16. */
    SDL_GL_STENCIL_SIZE,                /**< the minimum number of bits in the stencil buffer; defaults to 0. */
    SDL_GL_ACCUM_RED_SIZE,              /**< the minimum number of bits for the red channel of the accumulation buffer; defaults to 0. */
    SDL_GL_ACCUM_GREEN_SIZE,            /**< the minimum number of bits for the green channel of the accumulation buffer; defaults to 0. */
    SDL_GL_ACCUM_BLUE_SIZE,             /**< the minimum number of bits for the blue channel of the accumulation buffer; defaults to 0. */
    SDL_GL_ACCUM_ALPHA_SIZE,            /**< the minimum number of bits for the alpha channel of the accumulation buffer; defaults to 0. */
    SDL_GL_STEREO,                      /**< whether the output is stereo 3D; defaults to off. */
    SDL_GL_MULTISAMPLEBUFFERS,          /**< the number of buffers used for multisample anti-aliasing; defaults to 0. */
    SDL_GL_MULTISAMPLESAMPLES,          /**< the number of samples used around the current pixel used for multisample anti-aliasing. */
    SDL_GL_ACCELERATED_VISUAL,          /**< set to 1 to require hardware acceleration, set to 0 to force software rendering; defaults to allow either. */
    SDL_GL_RETAINED_BACKING,            /**< not used (deprecated). */
    SDL_GL_CONTEXT_MAJOR_VERSION,       /**< OpenGL context major version. */
    SDL_GL_CONTEXT_MINOR_VERSION,       /**< OpenGL context minor version. */
    SDL_GL_CONTEXT_FLAGS,               /**< some combination of 0 or more of elements of the SDL_GLContextFlag enumeration; defaults to 0. */
    SDL_GL_CONTEXT_PROFILE_MASK,        /**< type of GL context (Core, Compatibility, ES). See SDL_GLProfile; default value depends on platform. */
    SDL_GL_SHARE_WITH_CURRENT_CONTEXT,  /**< OpenGL context sharing; defaults to 0. */
    SDL_GL_FRAMEBUFFER_SRGB_CAPABLE,    /**< requests sRGB capable visual; defaults to 0. */
    SDL_GL_CONTEXT_RELEASE_BEHAVIOR,    /**< sets context the release behavior. See SDL_GLContextReleaseFlag; defaults to FLUSH. */
    SDL_GL_CONTEXT_RESET_NOTIFICATION,  /**< set context reset notification. See SDL_GLContextResetNotification; defaults to NO_NOTIFICATION. */
    SDL_GL_CONTEXT_NO_ERROR,
    SDL_GL_FLOATBUFFERS,
    SDL_GL_EGL_PLATFORM
} SDL_GLAttr;
SDL_HitTestResult
enum SDL_HitTestResult
Possible return values from the SDL_HitTest callback.
Thread Safety
This function should only be called on the main thread.
Since
This enum is available since SDL 3.2.0.
See also
SDL_HitTest
Enumerator
SDL_HITTEST_NORMAL
Region is normal. No special properties.
SDL_HITTEST_DRAGGABLE
Region can drag entire window.
SDL_HITTEST_RESIZE_TOPLEFT
Region is the resizable top-left corner border.
SDL_HITTEST_RESIZE_TOP
Region is the resizable top border.
SDL_HITTEST_RESIZE_TOPRIGHT
Region is the resizable top-right corner border.
SDL_HITTEST_RESIZE_RIGHT
Region is the resizable right border.
SDL_HITTEST_RESIZE_BOTTOMRIGHT
Region is the resizable bottom-right corner border.
SDL_HITTEST_RESIZE_BOTTOM
Region is the resizable bottom border.
SDL_HITTEST_RESIZE_BOTTOMLEFT
Region is the resizable bottom-left corner border.
SDL_HITTEST_RESIZE_LEFT
Region is the resizable left border.
{
    SDL_HITTEST_NORMAL,             /**< Region is normal. No special properties. */
    SDL_HITTEST_DRAGGABLE,          /**< Region can drag entire window. */
    SDL_HITTEST_RESIZE_TOPLEFT,     /**< Region is the resizable top-left corner border. */
    SDL_HITTEST_RESIZE_TOP,         /**< Region is the resizable top border. */
    SDL_HITTEST_RESIZE_TOPRIGHT,    /**< Region is the resizable top-right corner border. */
    SDL_HITTEST_RESIZE_RIGHT,       /**< Region is the resizable right border. */
    SDL_HITTEST_RESIZE_BOTTOMRIGHT, /**< Region is the resizable bottom-right corner border. */
    SDL_HITTEST_RESIZE_BOTTOM,      /**< Region is the resizable bottom border. */
    SDL_HITTEST_RESIZE_BOTTOMLEFT,  /**< Region is the resizable bottom-left corner border. */
    SDL_HITTEST_RESIZE_LEFT         /**< Region is the resizable left border. */
} SDL_HitTestResult;
SDL_ProgressState
enum SDL_ProgressState
Window progress state
Since
This enum is available since SDL 3.2.8.
Enumerator
SDL_PROGRESS_STATE_INVALID
An invalid progress state indicating an error; check SDL_GetError()
SDL_PROGRESS_STATE_NONE
No progress bar is shown
SDL_PROGRESS_STATE_INDETERMINATE
The progress bar is shown in a indeterminate state
SDL_PROGRESS_STATE_NORMAL
The progress bar is shown in a normal state
SDL_PROGRESS_STATE_PAUSED
The progress bar is shown in a paused state
SDL_PROGRESS_STATE_ERROR
The progress bar is shown in a state indicating the application had an error
{
    SDL_PROGRESS_STATE_INVALID = -1,    /**< An invalid progress state indicating an error; check SDL_GetError() */
    SDL_PROGRESS_STATE_NONE,            /**< No progress bar is shown */
    SDL_PROGRESS_STATE_INDETERMINATE,   /**< The progress bar is shown in a indeterminate state */
    SDL_PROGRESS_STATE_NORMAL,          /**< The progress bar is shown in a normal state */
    SDL_PROGRESS_STATE_PAUSED,          /**< The progress bar is shown in a paused state */
    SDL_PROGRESS_STATE_ERROR            /**< The progress bar is shown in a state indicating the application had an error */
} SDL_ProgressState;
SDL_SystemTheme
enum SDL_SystemTheme
System theme.
Since
This enum is available since SDL 3.2.0.
Enumerator
SDL_SYSTEM_THEME_UNKNOWN
Unknown system theme
SDL_SYSTEM_THEME_LIGHT
Light colored system theme
SDL_SYSTEM_THEME_DARK
Dark colored system theme
{
    SDL_SYSTEM_THEME_UNKNOWN,   /**< Unknown system theme */
    SDL_SYSTEM_THEME_LIGHT,     /**< Light colored system theme */
    SDL_SYSTEM_THEME_DARK       /**< Dark colored system theme */
} SDL_SystemTheme;
Function Documentation
SDL_CreatePopupWindow()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_CreatePopupWindow (SDL_Window * parent, int offset_x, int offset_y, int w, int h, SDL_WindowFlags flags) extern
Create a child popup window of the specified parent window.
The window size is a request and may be different than expected based on the desktop layout and window manager policies. Your application should be prepared to handle a window of any size.
The flags parameter must contain at least one of the following:
SDL_WINDOW_TOOLTIP: The popup window is a tooltip and will not pass any input events.
SDL_WINDOW_POPUP_MENU: The popup window is a popup menu. The topmost popup menu will implicitly gain the keyboard focus.
The following flags are not relevant to popup window creation and will be ignored:
SDL_WINDOW_MINIMIZED
SDL_WINDOW_MAXIMIZED
SDL_WINDOW_FULLSCREEN
SDL_WINDOW_BORDERLESS
The following flags are incompatible with popup window creation and will cause it to fail:
SDL_WINDOW_UTILITY
SDL_WINDOW_MODAL
The parent parameter must be non-null and a valid window. The parent of a popup window can be either a regular, toplevel window, or another popup window.
Popup windows cannot be minimized, maximized, made fullscreen, raised, flash, be made a modal window, be the parent of a toplevel window, or grab the mouse and/or keyboard. Attempts to do so will fail.
Popup windows implicitly do not have a border/decorations and do not appear on the taskbar/dock or in lists of windows such as alt-tab menus.
By default, popup window positions will automatically be constrained to keep the entire window within display bounds. This can be overridden with the SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN property.
By default, popup menus will automatically grab keyboard focus from the parent when shown. This behavior can be overridden by setting the SDL_WINDOW_NOT_FOCUSABLE flag, setting the SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN property to false, or toggling it after creation via the SDL_SetWindowFocusable() function.
If a parent window is hidden or destroyed, any child popup windows will be recursively hidden or destroyed as well. Child popup windows not explicitly hidden will be restored when the parent is shown.
Parameters
parent the parent of the window, must not be NULL.
offset_x the x position of the popup window relative to the origin of the parent.
offset_y the y position of the popup window relative to the origin of the parent window.
w the width of the window.
h the height of the window.
flags SDL_WINDOW_TOOLTIP or SDL_WINDOW_POPUP_MENU, and zero or more additional SDL_WindowFlags OR'd together.
Returns
the window that was created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindow
SDL_CreateWindowWithProperties
SDL_DestroyWindow
SDL_GetWindowParent
{
    SDL_Window *window;
    SDL_PropertiesID props = SDL_CreateProperties();
    // Popups must specify either the tooltip or popup menu window flags
    if (!(flags & (SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU))) {
        SDL_SetError("Popup windows must specify either the 'SDL_WINDOW_TOOLTIP' or the 'SDL_WINDOW_POPUP_MENU' flag");
        return NULL;
    }
    SDL_SetPointerProperty(props, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, parent);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_X_NUMBER, offset_x);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_Y_NUMBER, offset_y);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, w);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, h);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, flags);
    window = SDL_CreateWindowWithProperties(props);
    SDL_DestroyProperties(props);
    return window;
}
References NULL, SDL_CreateProperties(), SDL_CreateWindowWithProperties(), SDL_DestroyProperties(), SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, SDL_PROP_WINDOW_CREATE_X_NUMBER, SDL_PROP_WINDOW_CREATE_Y_NUMBER, SDL_SetError(), SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_WINDOW_POPUP_MENU, and SDL_WINDOW_TOOLTIP.
SDL_CreateWindow()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_CreateWindow (const char * title, int w, int h, SDL_WindowFlags flags) extern
Create a window with the specified dimensions and flags.
The window size is a request and may be different than expected based on the desktop layout and window manager policies. Your application should be prepared to handle a window of any size.
flags may be any of the following OR'd together:
SDL_WINDOW_FULLSCREEN: fullscreen window at desktop resolution
SDL_WINDOW_OPENGL: window usable with an OpenGL context
SDL_WINDOW_OCCLUDED: window partially or completely obscured by another window
SDL_WINDOW_HIDDEN: window is not visible
SDL_WINDOW_BORDERLESS: no window decoration
SDL_WINDOW_RESIZABLE: window can be resized
SDL_WINDOW_MINIMIZED: window is minimized
SDL_WINDOW_MAXIMIZED: window is maximized
SDL_WINDOW_MOUSE_GRABBED: window has grabbed mouse focus
SDL_WINDOW_INPUT_FOCUS: window has input focus
SDL_WINDOW_MOUSE_FOCUS: window has mouse focus
SDL_WINDOW_EXTERNAL: window not created by SDL
SDL_WINDOW_MODAL: window is modal
SDL_WINDOW_HIGH_PIXEL_DENSITY: window uses high pixel density back buffer if possible
SDL_WINDOW_MOUSE_CAPTURE: window has mouse captured (unrelated to MOUSE_GRABBED)
SDL_WINDOW_ALWAYS_ON_TOP: window should always be above others
SDL_WINDOW_UTILITY: window should be treated as a utility window, not showing in the task bar and window list
SDL_WINDOW_TOOLTIP: window should be treated as a tooltip and does not get mouse or keyboard focus, requires a parent window
SDL_WINDOW_POPUP_MENU: window should be treated as a popup menu, requires a parent window
SDL_WINDOW_KEYBOARD_GRABBED: window has grabbed keyboard input
SDL_WINDOW_VULKAN: window usable with a Vulkan instance
SDL_WINDOW_METAL: window usable with a Metal instance
SDL_WINDOW_TRANSPARENT: window with transparent buffer
SDL_WINDOW_NOT_FOCUSABLE: window should not be focusable
The SDL_Window is implicitly shown if SDL_WINDOW_HIDDEN is not set.
On Apple's macOS, you must set the NSHighResolutionCapable Info.plist property to YES, otherwise you will not receive a High-DPI OpenGL canvas.
The window pixel size may differ from its window coordinate size if the window is on a high pixel density display. Use SDL_GetWindowSize() to query the client area's size in window coordinates, and SDL_GetWindowSizeInPixels() or SDL_GetRenderOutputSize() to query the drawable size in pixels. Note that the drawable size can vary after the window is created and should be queried again if you get an SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED event.
If the window is created with any of the SDL_WINDOW_OPENGL or SDL_WINDOW_VULKAN flags, then the corresponding LoadLibrary function (SDL_GL_LoadLibrary or SDL_Vulkan_LoadLibrary) is called and the corresponding UnloadLibrary function is called by SDL_DestroyWindow().
If SDL_WINDOW_VULKAN is specified and there isn't a working Vulkan driver, SDL_CreateWindow() will fail, because SDL_Vulkan_LoadLibrary() will fail.
If SDL_WINDOW_METAL is specified on an OS that does not support Metal, SDL_CreateWindow() will fail.
If you intend to use this window with an SDL_Renderer, you should use SDL_CreateWindowAndRenderer() instead of this function, to avoid window flicker.
On non-Apple devices, SDL requires you to either not link to the Vulkan loader or link to a dynamic library version. This limitation may be removed in a future version of SDL.
Parameters
title the title of the window, in UTF-8 encoding.
w the width of the window.
h the height of the window.
flags 0, or one or more SDL_WindowFlags OR'd together.
Returns
the window that was created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindowAndRenderer
SDL_CreatePopupWindow
SDL_CreateWindowWithProperties
SDL_DestroyWindow
{
    SDL_Window *window;
    SDL_PropertiesID props = SDL_CreateProperties();
    if (title && *title) {
        SDL_SetStringProperty(props, SDL_PROP_WINDOW_CREATE_TITLE_STRING, title);
    }
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, w);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, h);
    SDL_SetNumberProperty(props, SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, flags);
    window = SDL_CreateWindowWithProperties(props);
    SDL_DestroyProperties(props);
    return window;
}
References SDL_CreateProperties(), SDL_CreateWindowWithProperties(), SDL_DestroyProperties(), SDL_PROP_WINDOW_CREATE_FLAGS_NUMBER, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, SDL_PROP_WINDOW_CREATE_TITLE_STRING, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, SDL_SetNumberProperty(), and SDL_SetStringProperty().
Referenced by SDL_CreateWindowAndRenderer().
SDL_CreateWindowWithProperties()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_CreateWindowWithProperties (SDL_PropertiesID props) extern
Create a window with the specified properties.
The window size is a request and may be different than expected based on the desktop layout and window manager policies. Your application should be prepared to handle a window of any size.
These are the supported properties:
SDL_PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN: true if the window should be always on top
SDL_PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN: true if the window has no window decoration
SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN: true if the "tooltip" and "menu" window types should be automatically constrained to be entirely within display bounds (default), false if no constraints on the position are desired.
SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN: true if the window will be used with an externally managed graphics context.
SDL_PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN: true if the window should accept keyboard input (defaults true)
SDL_PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN: true if the window should start in fullscreen mode at desktop resolution
SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER: the height of the window
SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN: true if the window should start hidden
SDL_PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN: true if the window uses a high pixel density buffer if possible
SDL_PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN: true if the window should start maximized
SDL_PROP_WINDOW_CREATE_MENU_BOOLEAN: true if the window is a popup menu
SDL_PROP_WINDOW_CREATE_METAL_BOOLEAN: true if the window will be used with Metal rendering
SDL_PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN: true if the window should start minimized
SDL_PROP_WINDOW_CREATE_MODAL_BOOLEAN: true if the window is modal to its parent
SDL_PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN: true if the window starts with grabbed mouse focus
SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN: true if the window will be used with OpenGL rendering
SDL_PROP_WINDOW_CREATE_PARENT_POINTER: an SDL_Window that will be the parent of this window, required for windows with the "tooltip", "menu", and "modal" properties
SDL_PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN: true if the window should be resizable
SDL_PROP_WINDOW_CREATE_TITLE_STRING: the title of the window, in UTF-8 encoding
SDL_PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN: true if the window show transparent in the areas with alpha of 0
SDL_PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN: true if the window is a tooltip
SDL_PROP_WINDOW_CREATE_UTILITY_BOOLEAN: true if the window is a utility window, not showing in the task bar and window list
SDL_PROP_WINDOW_CREATE_VULKAN_BOOLEAN: true if the window will be used with Vulkan rendering
SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER: the width of the window
SDL_PROP_WINDOW_CREATE_X_NUMBER: the x position of the window, or SDL_WINDOWPOS_CENTERED, defaults to SDL_WINDOWPOS_UNDEFINED. This is relative to the parent for windows with the "tooltip" or "menu" property set.
SDL_PROP_WINDOW_CREATE_Y_NUMBER: the y position of the window, or SDL_WINDOWPOS_CENTERED, defaults to SDL_WINDOWPOS_UNDEFINED. This is relative to the parent for windows with the "tooltip" or "menu" property set.
These are additional supported properties on macOS:
SDL_PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER: the (__unsafe_unretained) NSWindow associated with the window, if you want to wrap an existing window.
SDL_PROP_WINDOW_CREATE_COCOA_VIEW_POINTER: the (__unsafe_unretained) NSView associated with the window, defaults to [window contentView]
These are additional supported properties on Wayland:
SDL_PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN - true if the application wants to use the Wayland surface for a custom role and does not want it attached to an XDG toplevel window. See [README-wayland](README-wayland) for more information on using custom surfaces.
SDL_PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN - true if the application wants an associated wl_egl_window object to be created and attached to the window, even if the window does not have the OpenGL property or SDL_WINDOW_OPENGL flag set.
SDL_PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER - the wl_surface associated with the window, if you want to wrap an existing window. See [README-wayland](README-wayland) for more information.
These are additional supported properties on Windows:
SDL_PROP_WINDOW_CREATE_WIN32_HWND_POINTER: the HWND associated with the window, if you want to wrap an existing window.
SDL_PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER: optional, another window to share pixel format with, useful for OpenGL windows
These are additional supported properties with X11:
SDL_PROP_WINDOW_CREATE_X11_WINDOW_NUMBER: the X11 Window associated with the window, if you want to wrap an existing window.
The window is implicitly shown if the "hidden" property is not set.
These are additional supported properties with Emscripten:
SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID_STRING: the id given to the canvas element. This should start with a '#' sign
SDL_PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING: override the binding element for keyboard inputs for this canvas. The variable can be one of:
"#window": the javascript window object (default)
"#document": the javascript document object
"#screen": the javascript window.screen object
"#canvas": the WebGL canvas element
"#none": Don't bind anything at all
any other string without a leading # sign applies to the element on the page with that ID. Windows with the "tooltip" and "menu" properties are popup windows and have the behaviors and guidelines outlined in SDL_CreatePopupWindow().
If this window is being created to be used with an SDL_Renderer, you should not add a graphics API specific property (SDL_PROP_WINDOW_CREATE_OPENGL_BOOLEAN, etc), as SDL will handle that internally when it chooses a renderer. However, SDL might need to recreate your window at that point, which may cause the window to appear briefly, and then flicker as it is recreated. The correct approach to this is to create the window with the SDL_PROP_WINDOW_CREATE_HIDDEN_BOOLEAN property set to true, then create the renderer, then show the window with SDL_ShowWindow().
Parameters
props the properties to use.
Returns
the window that was created or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProperties
SDL_CreateWindow
SDL_DestroyWindow
{
    SDL_Window *window;
    const char *title = SDL_GetStringProperty(props, SDL_PROP_WINDOW_CREATE_TITLE_STRING, NULL);
    int x = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_X_NUMBER, SDL_WINDOWPOS_UNDEFINED);
    int y = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_Y_NUMBER, SDL_WINDOWPOS_UNDEFINED);
    int w = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, 0);
    int h = (int)SDL_GetNumberProperty(props, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, 0);
    SDL_Window *parent = (SDL_Window *)SDL_GetPointerProperty(props, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, NULL);
    SDL_WindowFlags flags = SDL_GetWindowFlagProperties(props);
    SDL_WindowFlags type_flags, graphics_flags;
    bool undefined_x = false;
    bool undefined_y = false;
    bool external_graphics_context = SDL_GetBooleanProperty(props, SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN, false);
    if (!_this) {
        // Initialize the video system if needed
        if (!SDL_Init(SDL_INIT_VIDEO)) {
            return NULL;
        }
        // Make clang-tidy happy
        if (!_this) {
            return NULL;
        }
    }
    if ((flags & SDL_WINDOW_MODAL) && !SDL_ObjectValid(parent, SDL_OBJECT_TYPE_WINDOW)) {
        SDL_SetError("Modal windows must specify a parent window");
        return NULL;
    }
    if ((flags & (SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU)) != 0) {
        if (!(_this->device_caps & VIDEO_DEVICE_CAPS_HAS_POPUP_WINDOW_SUPPORT)) {
            SDL_Unsupported();
            return NULL;
        }
        // Tooltip and popup menu window must specify a parent window
        if (!SDL_ObjectValid(parent, SDL_OBJECT_TYPE_WINDOW)) {
            SDL_SetError("Tooltip and popup menu windows must specify a parent window");
            return NULL;
        }
        // Remove invalid flags
        flags &= ~(SDL_WINDOW_MINIMIZED | SDL_WINDOW_MAXIMIZED | SDL_WINDOW_FULLSCREEN | SDL_WINDOW_BORDERLESS);
    }
    // Ensure no more than one of these flags is set
    type_flags = flags & (SDL_WINDOW_UTILITY | SDL_WINDOW_TOOLTIP | SDL_WINDOW_POPUP_MENU | SDL_WINDOW_MODAL);
    if (type_flags & (type_flags - 1)) {
        SDL_SetError("Conflicting window type flags specified: 0x%.8x", (unsigned int)type_flags);
        return NULL;
    }
    // Make sure the display list is up to date for window placement
    if (_this->RefreshDisplays) {
        _this->RefreshDisplays(_this);
    }
    // Some platforms can't create zero-sized windows
    if (w < 1) {
        w = 1;
    }
    if (h < 1) {
        h = 1;
    }
    if (SDL_WINDOWPOS_ISUNDEFINED(x) || SDL_WINDOWPOS_ISUNDEFINED(y) ||
        SDL_WINDOWPOS_ISCENTERED(x) || SDL_WINDOWPOS_ISCENTERED(y)) {
        SDL_DisplayID displayID = 0;
        SDL_Rect bounds;
        if ((SDL_WINDOWPOS_ISUNDEFINED(x) || SDL_WINDOWPOS_ISCENTERED(x)) && (x & 0xFFFF)) {
            displayID = (x & 0xFFFF);
        } else if ((SDL_WINDOWPOS_ISUNDEFINED(y) || SDL_WINDOWPOS_ISCENTERED(y)) && (y & 0xFFFF)) {
            displayID = (y & 0xFFFF);
        }
        if (displayID == 0 || SDL_GetDisplayIndex(displayID) < 0) {
            displayID = SDL_GetPrimaryDisplay();
        }
        SDL_zero(bounds);
        SDL_GetDisplayUsableBounds(displayID, &bounds);
        if (w > bounds.w || h > bounds.h) {
            // This window is larger than the usable bounds, just center on the display
            SDL_GetDisplayBounds(displayID, &bounds);
        }
        if (SDL_WINDOWPOS_ISCENTERED(x) || SDL_WINDOWPOS_ISUNDEFINED(x)) {
            if (SDL_WINDOWPOS_ISUNDEFINED(x)) {
                undefined_x = true;
            }
            x = bounds.x + (bounds.w - w) / 2;
        }
        if (SDL_WINDOWPOS_ISCENTERED(y) || SDL_WINDOWPOS_ISUNDEFINED(y)) {
            if (SDL_WINDOWPOS_ISUNDEFINED(y)) {
                undefined_y = true;
            }
            y = bounds.y + (bounds.h - h) / 2;
        }
    }
    // ensure no more than one of these flags is set
    graphics_flags = flags & (SDL_WINDOW_OPENGL | SDL_WINDOW_METAL | SDL_WINDOW_VULKAN);
    if (graphics_flags & (graphics_flags - 1)) {
        SDL_SetError("Conflicting window graphics flags specified: 0x%.8x", (unsigned int)graphics_flags);
        return NULL;
    }
    // Some platforms have certain graphics backends enabled by default
    if (!graphics_flags && !external_graphics_context) {
        flags |= SDL_DefaultGraphicsBackends(_this);
    }
    if (flags & SDL_WINDOW_OPENGL) {
        if (!_this->GL_CreateContext) {
            SDL_ContextNotSupported("OpenGL");
            return NULL;
        }
        if (!SDL_GL_LoadLibrary(NULL)) {
            return NULL;
        }
    }
    if (flags & SDL_WINDOW_VULKAN) {
        if (!_this->Vulkan_CreateSurface) {
            SDL_ContextNotSupported("Vulkan");
            return NULL;
        }
        if (!SDL_Vulkan_LoadLibrary(NULL)) {
            return NULL;
        }
    }
    if (flags & SDL_WINDOW_METAL) {
        if (!_this->Metal_CreateView) {
            SDL_ContextNotSupported("Metal");
            return NULL;
        }
    }
    window = (SDL_Window *)SDL_calloc(1, sizeof(*window));
    if (!window) {
        return NULL;
    }
    SDL_SetObjectValid(window, SDL_OBJECT_TYPE_WINDOW, true);
    window->id = SDL_GetNextObjectID();
    window->floating.x = window->windowed.x = window->x = x;
    window->floating.y = window->windowed.y = window->y = y;
    window->floating.w = window->windowed.w = window->w = w;
    window->floating.h = window->windowed.h = window->h = h;
    window->undefined_x = undefined_x;
    window->undefined_y = undefined_y;
    SDL_VideoDisplay *display = SDL_GetVideoDisplayForWindow(window);
    if (display) {
        SDL_SetWindowHDRProperties(window, &display->HDR, false);
    }
    if (flags & SDL_WINDOW_FULLSCREEN || IsFullscreenOnly(_this)) {
        SDL_Rect bounds;
        SDL_GetDisplayBounds(display ? display->id : SDL_GetPrimaryDisplay(), &bounds);
        window->x = bounds.x;
        window->y = bounds.y;
        window->w = bounds.w;
        window->h = bounds.h;
        window->pending_flags |= SDL_WINDOW_FULLSCREEN;
        flags |= SDL_WINDOW_FULLSCREEN;
    }
    window->flags = ((flags & CREATE_FLAGS) | SDL_WINDOW_HIDDEN);
    window->display_scale = 1.0f;
    window->opacity = 1.0f;
    window->next = _this->windows;
    window->is_destroying = false;
    window->last_displayID = SDL_GetDisplayForWindow(window);
    window->external_graphics_context = external_graphics_context;
    window->constrain_popup = SDL_GetBooleanProperty(props, SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN, true);
    if (_this->windows) {
        _this->windows->prev = window;
    }
    _this->windows = window;
    // Set the parent before creation.
    SDL_UpdateWindowHierarchy(window, parent);
    if (_this->CreateSDLWindow && !_this->CreateSDLWindow(_this, window, props)) {
        PUSH_SDL_ERROR()
        SDL_DestroyWindow(window);
        POP_SDL_ERROR()
        return NULL;
    }
    /* Clear minimized if not on windows, only windows handles it at create rather than FinishWindowCreation,
     * but it's important or window focus will get broken on windows!
     */
#if !defined(SDL_PLATFORM_WINDOWS)
    if (window->flags & SDL_WINDOW_MINIMIZED) {
        window->flags &= ~SDL_WINDOW_MINIMIZED;
    }
#endif
    if (title) {
        SDL_SetWindowTitle(window, title);
    }
    SDL_FinishWindowCreation(window, flags);
    // Make sure window pixel size is up to date
    SDL_CheckWindowPixelSizeChanged(window);
#ifdef SDL_VIDEO_DRIVER_UIKIT
    SDL_UpdateLifecycleObserver();
#endif
    SDL_ClearError();
    return window;
}
References _this, CREATE_FLAGS, SDL_Rect::h, IsFullscreenOnly(), NULL, POP_SDL_ERROR, PUSH_SDL_ERROR, SDL_calloc(), SDL_CheckWindowPixelSizeChanged(), SDL_ClearError(), SDL_ContextNotSupported(), SDL_DefaultGraphicsBackends(), SDL_DestroyWindow(), SDL_FinishWindowCreation(), SDL_GetBooleanProperty(), SDL_GetDisplayBounds(), SDL_GetDisplayForWindow(), SDL_GetDisplayIndex(), SDL_GetDisplayUsableBounds(), SDL_GetNextObjectID(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetPrimaryDisplay(), SDL_GetStringProperty(), SDL_GetVideoDisplayForWindow(), SDL_GetWindowFlagProperties(), SDL_GL_LoadLibrary(), SDL_Init(), SDL_INIT_VIDEO, SDL_OBJECT_TYPE_WINDOW, SDL_ObjectValid(), SDL_PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN, SDL_PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN, SDL_PROP_WINDOW_CREATE_HEIGHT_NUMBER, SDL_PROP_WINDOW_CREATE_PARENT_POINTER, SDL_PROP_WINDOW_CREATE_TITLE_STRING, SDL_PROP_WINDOW_CREATE_WIDTH_NUMBER, SDL_PROP_WINDOW_CREATE_X_NUMBER, SDL_PROP_WINDOW_CREATE_Y_NUMBER, SDL_SetError(), SDL_SetObjectValid(), SDL_SetWindowHDRProperties(), SDL_SetWindowTitle(), SDL_Unsupported, SDL_UpdateLifecycleObserver(), SDL_UpdateWindowHierarchy(), SDL_Vulkan_LoadLibrary(), SDL_WINDOW_BORDERLESS, SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_METAL, SDL_WINDOW_MINIMIZED, SDL_WINDOW_MODAL, SDL_WINDOW_OPENGL, SDL_WINDOW_POPUP_MENU, SDL_WINDOW_TOOLTIP, SDL_WINDOW_UTILITY, SDL_WINDOW_VULKAN, SDL_WINDOWPOS_ISCENTERED, SDL_WINDOWPOS_ISUNDEFINED, SDL_WINDOWPOS_UNDEFINED, SDL_zero, VIDEO_DEVICE_CAPS_HAS_POPUP_WINDOW_SUPPORT, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_CreatePopupWindow(), and SDL_CreateWindow().
SDL_DestroyWindow()
SDL_DECLSPEC void SDLCALL SDL_DestroyWindow (SDL_Window * window) extern
Destroy a window.
Any child windows owned by the window will be recursively destroyed as well.
Note that on some platforms, the visible window may not actually be removed from the screen until the SDL event loop is pumped again, even though the SDL_Window is no longer valid after this call.
Parameters
window the window to destroy.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreatePopupWindow
SDL_CreateWindow
SDL_CreateWindowWithProperties
{
    CHECK_WINDOW_MAGIC(window,);
    window->is_destroying = true;
    // Destroy any child windows of this window
    while (window->first_child) {
        SDL_DestroyWindow(window->first_child);
    }
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_DESTROYED, 0, 0);
    SDL_Renderer *renderer = SDL_GetRenderer(window);
    if (renderer) {
        SDL_DestroyRendererWithoutFreeing(renderer);
    }
    // Restore video mode, etc.
    SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_LEAVE, true);
    if (!(window->flags & SDL_WINDOW_EXTERNAL)) {
        SDL_HideWindow(window);
    }
    SDL_DestroyProperties(window->text_input_props);
    SDL_DestroyProperties(window->props);
    /* Clear the modal status, but don't unset the parent just yet, as it
     * may be needed later in the destruction process if a backend needs
     * to update the input focus.
     */
    if (_this->SetWindowModal && (window->flags & SDL_WINDOW_MODAL)) {
        _this->SetWindowModal(_this, window, false);
    }
    // Make sure the destroyed window isn't referenced by any display as a fullscreen window.
    for (int i = 0; i < _this->num_displays; ++i) {
        if (_this->displays[i]->fullscreen_window == window) {
            _this->displays[i]->fullscreen_window = NULL;
        }
    }
    // Make sure this window no longer has focus
    if (SDL_GetKeyboardFocus() == window) {
        SDL_SetKeyboardFocus(NULL);
    }
    if ((window->flags & SDL_WINDOW_MOUSE_CAPTURE)) {
        SDL_UpdateMouseCapture(true);
    }
    if (SDL_GetMouseFocus() == window) {
        SDL_SetMouseFocus(NULL);
    }
    SDL_DestroyWindowSurface(window);
    // Make no context current if this is the current context window
    if (window->flags & SDL_WINDOW_OPENGL) {
        if (_this->current_glwin == window) {
            SDL_GL_MakeCurrent(window, NULL);
        }
    }
    if (_this->DestroyWindow) {
        _this->DestroyWindow(_this, window);
    }
    // Unload the graphics libraries after the window is destroyed, which may clean up EGL surfaces
    if (window->flags & SDL_WINDOW_OPENGL) {
        SDL_GL_UnloadLibrary();
    }
    if (window->flags & SDL_WINDOW_VULKAN) {
        SDL_Vulkan_UnloadLibrary();
    }
    if (_this->grabbed_window == window) {
        _this->grabbed_window = NULL; // ungrabbing input.
    }
    if (_this->current_glwin == window) {
        _this->current_glwin = NULL;
    }
    SDL_CompareAndSwapAtomicPointer(&_this->wakeup_window, window, NULL);
    // Now invalidate magic
    SDL_SetObjectValid(window, SDL_OBJECT_TYPE_WINDOW, false);
    // Free memory associated with the window
    SDL_free(window->title);
    SDL_DestroySurface(window->icon);
    // Unlink the window from its siblings.
    SDL_UpdateWindowHierarchy(window, NULL);
    // Unlink the window from the global window list
    if (window->next) {
        window->next->prev = window->prev;
    }
    if (window->prev) {
        window->prev->next = window->next;
    } else {
        _this->windows = window->next;
    }
    SDL_free(window->renderers);
    SDL_free(window);
#ifdef SDL_VIDEO_DRIVER_UIKIT
    SDL_UpdateLifecycleObserver();
#endif
}
References _this, CHECK_WINDOW_MAGIC, NULL, SDL_CompareAndSwapAtomicPointer(), SDL_DestroyProperties(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroySurface(), SDL_DestroyWindow(), SDL_DestroyWindowSurface(), SDL_EVENT_WINDOW_DESTROYED, SDL_free(), SDL_FULLSCREEN_OP_LEAVE, SDL_GetKeyboardFocus(), SDL_GetMouseFocus(), SDL_GetRenderer(), SDL_GL_MakeCurrent(), SDL_GL_UnloadLibrary(), SDL_HideWindow(), SDL_OBJECT_TYPE_WINDOW, SDL_SendWindowEvent(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_SetObjectValid(), SDL_UpdateFullscreenMode(), SDL_UpdateLifecycleObserver(), SDL_UpdateMouseCapture(), SDL_UpdateWindowHierarchy(), SDL_Vulkan_UnloadLibrary(), SDL_WINDOW_EXTERNAL, SDL_WINDOW_MODAL, SDL_WINDOW_MOUSE_CAPTURE, SDL_WINDOW_OPENGL, and SDL_WINDOW_VULKAN.
Referenced by SDL_CreateWindowAndRenderer(), SDL_CreateWindowWithProperties(), SDL_DestroyWindow(), and SDL_VideoQuit().
SDL_DestroyWindowSurface()
SDL_DECLSPEC bool SDLCALL SDL_DestroyWindowSurface (SDL_Window * window) extern
Destroy the surface associated with the window.
Parameters
window the window to update.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
SDL_WindowHasSurface
< Surface is referenced internally
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->surface) {
        window->surface->internal_flags &= ~SDL_INTERNAL_SURFACE_DONTFREE;
        SDL_DestroySurface(window->surface);
        window->surface = NULL;
        window->surface_valid = false;
    }
    if (_this->checked_texture_framebuffer) { // never checked? No framebuffer to destroy. Don't risk calling the wrong implementation.
        if (_this->DestroyWindowFramebuffer) {
            _this->DestroyWindowFramebuffer(_this, window);
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, NULL, SDL_DestroySurface(), and SDL_INTERNAL_SURFACE_DONTFREE.
Referenced by SDL_DestroyWindow(), and SDL_RecreateWindow().
SDL_DisableScreenSaver()
SDL_DECLSPEC bool SDLCALL SDL_DisableScreenSaver (void) extern
Prevent the screen from being blanked by a screen saver.
If you disable the screensaver, it is automatically re-enabled when SDL quits.
The screensaver is disabled by default, but this may by changed by SDL_HINT_VIDEO_ALLOW_SCREENSAVER.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_EnableScreenSaver
SDL_ScreenSaverEnabled
{
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (_this->suspend_screensaver) {
        return true;
    }
    _this->suspend_screensaver = true;
    if (_this->SuspendScreenSaver) {
        return _this->SuspendScreenSaver(_this);
    }
    return SDL_Unsupported();
}
References _this, SDL_UninitializedVideo(), and SDL_Unsupported.
Referenced by SDL_VideoInit().
SDL_EGL_GetCurrentConfig()
SDL_DECLSPEC SDL_EGLConfig SDLCALL SDL_EGL_GetCurrentConfig (void) extern
Get the currently active EGL config.
Returns
the currently active EGL config or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_VIDEO_OPENGL_EGL
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (!_this->egl_data) {
        SDL_SetError("There is no current EGL display");
        return NULL;
    }
    return _this->egl_data->egl_config;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_GetCurrentDisplay()
SDL_DECLSPEC SDL_EGLDisplay SDLCALL SDL_EGL_GetCurrentDisplay (void) extern
Get the currently active EGL display.
Returns
the currently active EGL display or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_VIDEO_OPENGL_EGL
    if (!_this) {
        SDL_UninitializedVideo();
        return EGL_NO_DISPLAY;
    }
    if (!_this->egl_data) {
        SDL_SetError("There is no current EGL display");
        return EGL_NO_DISPLAY;
    }
    return _this->egl_data->egl_display;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, EGL_NO_DISPLAY, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_GetProcAddress()
SDL_DECLSPEC SDL_FunctionPointer SDLCALL SDL_EGL_GetProcAddress (const char * proc) extern
Get an EGL library function by name.
If an EGL library is loaded, this function allows applications to get entry points for EGL functions. This is useful to provide to an EGL API and extension loader.
Parameters
proc the name of an EGL function.
Returns
a pointer to the named EGL function. The returned pointer should be cast to the appropriate function signature.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_EGL_GetCurrentDisplay
{
#ifdef SDL_VIDEO_OPENGL_EGL
    SDL_FunctionPointer func;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    func = NULL;
    if (_this->egl_data) {
        func = SDL_EGL_GetProcAddressInternal(_this, proc);
    } else {
        SDL_SetError("No EGL library has been loaded");
    }
    return func;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_GetWindowSurface()
SDL_DECLSPEC SDL_EGLSurface SDLCALL SDL_EGL_GetWindowSurface (SDL_Window * window) extern
Get the EGL surface associated with the window.
Parameters
window the window to query.
Returns
the EGLSurface pointer associated with the window, or NULL on failure.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#ifdef SDL_VIDEO_OPENGL_EGL
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (!_this->egl_data) {
        SDL_SetError("There is no current EGL display");
        return NULL;
    }
    if (_this->GL_GetEGLSurface) {
        return _this->GL_GetEGLSurface(_this, window);
    }
    return NULL;
#else
    SDL_SetError("SDL was not built with EGL support");
    return NULL;
#endif
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
SDL_EGL_SetAttributeCallbacks()
SDL_DECLSPEC void SDLCALL SDL_EGL_SetAttributeCallbacks (SDL_EGLAttribArrayCallback platformAttribCallback, SDL_EGLIntArrayCallback surfaceAttribCallback, SDL_EGLIntArrayCallback contextAttribCallback, void * userdata) extern
Sets the callbacks for defining custom EGLAttrib arrays for EGL initialization.
Callbacks that aren't needed can be set to NULL.
NOTE: These callback pointers will be reset after SDL_GL_ResetAttributes.
Parameters
platformAttribCallback callback for attributes to pass to eglGetPlatformDisplay. May be NULL.
surfaceAttribCallback callback for attributes to pass to eglCreateSurface. May be NULL.
contextAttribCallback callback for attributes to pass to eglCreateContext. May be NULL.
userdata a pointer that is passed to the callbacks.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (!_this) {
        return;
    }
    _this->egl_platformattrib_callback = platformAttribCallback;
    _this->egl_surfaceattrib_callback = surfaceAttribCallback;
    _this->egl_contextattrib_callback = contextAttribCallback;
    _this->egl_attrib_callback_userdata = userdata;
}
References _this.
SDL_EnableScreenSaver()
SDL_DECLSPEC bool SDLCALL SDL_EnableScreenSaver (void) extern
Allow the screen to be blanked by a screen saver.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DisableScreenSaver
SDL_ScreenSaverEnabled
{
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!_this->suspend_screensaver) {
        return true;
    }
    _this->suspend_screensaver = false;
    if (_this->SuspendScreenSaver) {
        return _this->SuspendScreenSaver(_this);
    }
    return SDL_Unsupported();
}
References _this, SDL_UninitializedVideo(), and SDL_Unsupported.
Referenced by SDL_VideoQuit().
SDL_FlashWindow()
SDL_DECLSPEC bool SDLCALL SDL_FlashWindow (SDL_Window * window, SDL_FlashOperation operation) extern
Request a window to demand attention from the user.
Parameters
window the window to be flashed.
operation the operation to perform.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (_this->FlashWindow) {
        return _this->FlashWindow(_this, window, operation);
    }
    return SDL_Unsupported();
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_Unsupported.
SDL_GetClosestFullscreenDisplayMode()
SDL_DECLSPEC bool SDLCALL SDL_GetClosestFullscreenDisplayMode (SDL_DisplayID displayID, int w, int h, float refresh_rate, bool include_high_density_modes, SDL_DisplayMode * closest) extern
Get the closest match to the requested display mode.
The available display modes are scanned and closest is filled in with the closest mode matching the requested mode and returned. The mode format and refresh rate default to the desktop mode if they are set to 0. The modes are scanned with size being first priority, format being second priority, and finally checking the refresh rate. If all the available modes are too small, then false is returned.
Parameters
displayID the instance ID of the display to query.
w the width in pixels of the desired display mode.
h the height in pixels of the desired display mode.
refresh_rate the refresh rate of the desired display mode, or 0.0f for the desktop refresh rate.
include_high_density_modes boolean to include high density modes in the search.
closest a pointer filled in with the closest display mode equal to or larger than the desired mode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
SDL_GetFullscreenDisplayModes
{
    if (!result) {
        return SDL_InvalidParamError("closest"); // Parameter `result` is called `closest` in the header.
    }
    const SDL_DisplayMode *mode, *closest = NULL;
    float aspect_ratio;
    int i;
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    SDL_zerop(result);
    CHECK_DISPLAY_MAGIC(display, false);
    if (h > 0) {
        aspect_ratio = (float)w / h;
    } else {
        aspect_ratio = 1.0f;
    }
    if (refresh_rate == 0.0f) {
        refresh_rate = display->desktop_mode.refresh_rate;
    }
    SDL_UpdateFullscreenDisplayModes(display);
    for (i = 0; i < display->num_fullscreen_modes; ++i) {
        mode = &display->fullscreen_modes[i];
        if (w > mode->w) {
            // Out of sorted modes large enough here
            break;
        }
        if (h > mode->h) {
            /* Wider, but not tall enough, due to a different aspect ratio.
             * This mode must be skipped, but closer modes may still follow */
            continue;
        }
        if (mode->pixel_density > 1.0f && !include_high_density_modes) {
            continue;
        }
        if (closest) {
            float current_aspect_ratio = (float)mode->w / mode->h;
            float closest_aspect_ratio = (float)closest->w / closest->h;
            if (SDL_fabsf(aspect_ratio - closest_aspect_ratio) < SDL_fabsf(aspect_ratio - current_aspect_ratio)) {
                // The mode we already found has a better aspect ratio match
                continue;
            }
            if (mode->w == closest->w && mode->h == closest->h &&
                SDL_fabsf(closest->refresh_rate - refresh_rate) < SDL_fabsf(mode->refresh_rate - refresh_rate)) {
                /* We already found a mode and the new mode is further from our
                 * refresh rate target */
                continue;
            }
        }
        closest = mode;
    }
    if (!closest) {
        return SDL_SetError("Couldn't find any matching video modes");
    }
    SDL_copyp(result, closest);
    return true;
}
References CHECK_DISPLAY_MAGIC, SDL_DisplayMode::h, NULL, SDL_DisplayMode::pixel_density, SDL_DisplayMode::refresh_rate, SDL_copyp, SDL_fabsf(), SDL_GetVideoDisplay(), SDL_InvalidParamError, SDL_SetError(), SDL_UpdateFullscreenDisplayModes(), SDL_zerop, and SDL_DisplayMode::w.
Referenced by SDL_OnWindowDisplayChanged().
SDL_GetCurrentDisplayMode()
SDL_DECLSPEC const SDL_DisplayMode *SDLCALL SDL_GetCurrentDisplayMode (SDL_DisplayID displayID) extern
Get information about the current display mode.
There's a difference between this function and SDL_GetDesktopDisplayMode() when SDL runs fullscreen and has changed the resolution. In that case this function will return the current display mode, and not the previous native display mode.
Parameters
displayID the instance ID of the display to query.
Returns
a pointer to the desktop display mode or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDesktopDisplayMode
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    // Make sure our mode list is updated
    SDL_UpdateFullscreenDisplayModes(display);
    return display->current_mode;
}
References CHECK_DISPLAY_MAGIC, NULL, SDL_GetVideoDisplay(), and SDL_UpdateFullscreenDisplayModes().
Referenced by SDL_GetWindowPixelFormat(), and SDL_GetWindowSizeInPixels().
SDL_GetCurrentDisplayOrientation()
SDL_DECLSPEC SDL_DisplayOrientation SDLCALL SDL_GetCurrentDisplayOrientation (SDL_DisplayID displayID) extern
Get the orientation of a display.
Parameters
displayID the instance ID of the display to query.
Returns
the SDL_DisplayOrientation enum value of the display, or SDL_ORIENTATION_UNKNOWN if it isn't available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, SDL_ORIENTATION_UNKNOWN);
    if (display->current_orientation != SDL_ORIENTATION_UNKNOWN) {
        return display->current_orientation;
    } else {
        // Default to landscape if the driver hasn't set it
        return SDL_ORIENTATION_LANDSCAPE;
    }
}
References CHECK_DISPLAY_MAGIC, SDL_GetVideoDisplay(), SDL_ORIENTATION_LANDSCAPE, and SDL_ORIENTATION_UNKNOWN.
SDL_GetCurrentVideoDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetCurrentVideoDriver (void) extern
Get the name of the currently initialized video driver.
The names of drivers are all simple, low-ASCII identifiers, like "cocoa", "x11" or "windows". These never have Unicode characters, and are not meant to be proper names.
Returns
the name of the current video driver or NULL if no driver has been initialized.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumVideoDrivers
SDL_GetVideoDriver
{
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    return _this->name;
}
References _this, NULL, and SDL_UninitializedVideo().
SDL_GetDesktopDisplayMode()
SDL_DECLSPEC const SDL_DisplayMode *SDLCALL SDL_GetDesktopDisplayMode (SDL_DisplayID displayID) extern
Get information about the desktop's display mode.
There's a difference between this function and SDL_GetCurrentDisplayMode() when SDL runs fullscreen and has changed the resolution. In that case this function will return the previous native display mode, and not the current display mode.
Parameters
displayID the instance ID of the display to query.
Returns
a pointer to the desktop display mode or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCurrentDisplayMode
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    return &display->desktop_mode;
}
References CHECK_DISPLAY_MAGIC, NULL, and SDL_GetVideoDisplay().
Referenced by SDL_CalculateSimulatedVSyncInterval(), and SDL_GetWindowSizeInPixels().
SDL_GetDisplayBounds()
SDL_DECLSPEC bool SDLCALL SDL_GetDisplayBounds (SDL_DisplayID displayID, SDL_Rect * rect) extern
Get the desktop area represented by a display.
The primary display is often located at (0,0), but may be placed at a different location depending on monitor layout.
Parameters
displayID the instance ID of the display to query.
rect the SDL_Rect structure filled in with the display bounds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayUsableBounds
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, false);
    if (!rect) {
        return SDL_InvalidParamError("rect");
    }
    if (_this->GetDisplayBounds) {
        if (_this->GetDisplayBounds(_this, display, rect)) {
            return true;
        }
    }
    // Assume that the displays are left to right
    if (displayID == SDL_GetPrimaryDisplay()) {
        rect->x = 0;
        rect->y = 0;
    } else {
        SDL_GetDisplayBounds(_this->displays[SDL_GetDisplayIndex(displayID) - 1]->id, rect);
        rect->x += rect->w;
    }
    rect->w = display->current_mode->w;
    rect->h = display->current_mode->h;
    return true;
}
References _this, CHECK_DISPLAY_MAGIC, SDL_Rect::h, SDL_GetDisplayBounds(), SDL_GetDisplayIndex(), SDL_GetPrimaryDisplay(), SDL_GetVideoDisplay(), SDL_InvalidParamError, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by GetDisplayForRect(), SDL_CreateWindowWithProperties(), SDL_GetDisplayBounds(), SDL_GetDisplayUsableBounds(), SDL_GetWindowPosition(), SDL_SetWindowPosition(), SDL_UpdateDesktopBounds(), and SDL_UpdateFullscreenMode().
SDL_GetDisplayContentScale()
SDL_DECLSPEC float SDLCALL SDL_GetDisplayContentScale (SDL_DisplayID displayID) extern
Get the content scale of a display.
The content scale is the expected scale for content based on the DPI settings of the display. For example, a 4K display might have a 2.0 (200%) display scale, which means that the user expects UI elements to be twice as big on this display, to aid in readability.
After window creation, SDL_GetWindowDisplayScale() should be used to query the content scale factor for individual windows instead of querying the display for a window and calling this function, as the per-window content scale factor may differ from the base value of the display it is on, particularly on high-DPI and/or multi-monitor desktop configurations.
Parameters
displayID the instance ID of the display to query.
Returns
the content scale of the display, or 0.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowDisplayScale
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, 0.0f);
    return display->content_scale;
}
References CHECK_DISPLAY_MAGIC, and SDL_GetVideoDisplay().
Referenced by SDL_CheckWindowDisplayScaleChanged().
SDL_GetDisplayForPoint()
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetDisplayForPoint (const SDL_Point * point) extern
Get the display containing a point.
Parameters
point the point to query.
Returns
the instance ID of the display containing the point or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    if (!point) {
        SDL_InvalidParamError("point");
        return 0;
    }
    return GetDisplayForRect(point->x, point->y, 1, 1);
}
References GetDisplayForRect(), SDL_InvalidParamError, SDL_Point::x, and SDL_Point::y.
SDL_GetDisplayForRect()
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetDisplayForRect (const SDL_Rect * rect) extern
Get the display primarily containing a rect.
Parameters
rect the rect to query.
Returns
the instance ID of the display entirely containing the rect or closest to the center of the rect on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    if (!rect) {
        SDL_InvalidParamError("rect");
        return 0;
    }
    return GetDisplayForRect(rect->x, rect->y, rect->w, rect->h);
}
References GetDisplayForRect(), SDL_Rect::h, SDL_InvalidParamError, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
SDL_GetDisplayForWindow()
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetDisplayForWindow (SDL_Window * window) extern
Get the display associated with a window.
Parameters
window the window to query.
Returns
the instance ID of the display containing the center of the window on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    SDL_DisplayID displayID = 0;
    CHECK_WINDOW_MAGIC(window, 0);
    /* sdl2-compat calls this function to get a display on which to make the window fullscreen,
     * so pass it the preferred fullscreen display ID in a property.
     */
    SDL_PropertiesID window_props = SDL_GetWindowProperties(window);
    SDL_VideoDisplay *fs_display = SDL_GetVideoDisplayForFullscreenWindow(window);
    if (fs_display) {
        SDL_SetNumberProperty(window_props, SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY, fs_display->id);
    } else {
        SDL_ClearProperty(window_props, SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY);
    }
    // An explicit fullscreen display overrides all
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        displayID = window->current_fullscreen_mode.displayID;
    }
    if (!displayID) {
        displayID = SDL_GetDisplayForWindowPosition(window);
    }
    return displayID;
}
References CHECK_WINDOW_MAGIC, SDL_VideoDisplay::id, SDL_ClearProperty(), SDL_GetDisplayForWindowPosition(), SDL_GetVideoDisplayForFullscreenWindow(), SDL_GetWindowProperties(), SDL_PROP_SDL2_COMPAT_WINDOW_PREFERRED_FULLSCREEN_DISPLAY, SDL_SetNumberProperty(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_CalculateSimulatedVSyncInterval(), SDL_CreateWindowWithProperties(), SDL_GetDisplayDriverDataForWindow(), SDL_GetVideoDisplayForWindow(), SDL_GetWindowPixelFormat(), SDL_GetWindowPosition(), SDL_GetWindowSizeInPixels(), SDL_SetDisplayHDRProperties(), and SDL_SetWindowPosition().
SDL_GetDisplayName()
SDL_DECLSPEC const char *SDLCALL SDL_GetDisplayName (SDL_DisplayID displayID) extern
Get the name of a display in UTF-8 encoding.
Parameters
displayID the instance ID of the display to query.
Returns
the name of a display or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, NULL);
    return display->name;
}
References CHECK_DISPLAY_MAGIC, NULL, and SDL_GetVideoDisplay().
SDL_GetDisplayProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetDisplayProperties (SDL_DisplayID displayID) extern
Get the properties associated with a display.
The following read-only properties are provided by SDL:
SDL_PROP_DISPLAY_HDR_ENABLED_BOOLEAN: true if the display has HDR headroom above the SDR white point. This is for informational and diagnostic purposes only, as not all platforms provide this information at the display level.
On KMS/DRM:
SDL_PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER: the "panel orientation" property for the display in degrees of clockwise rotation. Note that this is provided only as a hint, and the application is responsible for any coordinate transformations needed to conform to the requested display orientation.
On Wayland:
SDL_PROP_DISPLAY_WAYLAND_WL_OUTPUT_POINTER: the wl_output associated with the display
Parameters
displayID the instance ID of the display to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, 0);
    if (display->props == 0) {
        display->props = SDL_CreateProperties();
    }
    return display->props;
}
References CHECK_DISPLAY_MAGIC, SDL_CreateProperties(), and SDL_GetVideoDisplay().
Referenced by SDL_AddVideoDisplay().
SDL_GetDisplays()
SDL_DECLSPEC SDL_DisplayID *SDLCALL SDL_GetDisplays (int * count) extern
Get a list of currently connected displays.
Parameters
count a pointer filled in with the number of displays returned, may be NULL.
Returns
a 0 terminated array of display instance IDs or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    int i;
    SDL_DisplayID *displays;
    if (!_this) {
        if (count) {
            *count = 0;
        }
        SDL_UninitializedVideo();
        return NULL;
    }
    displays = (SDL_DisplayID *)SDL_malloc((_this->num_displays + 1) * sizeof(*displays));
    if (displays) {
        if (count) {
            *count = _this->num_displays;
        }
        for (i = 0; i < _this->num_displays; ++i) {
            displays[i] = _this->displays[i]->id;
        }
        displays[i] = 0;
    } else {
        if (count) {
            *count = 0;
        }
    }
    return displays;
}
References _this, count, NULL, SDL_malloc(), and SDL_UninitializedVideo().
Referenced by SDL_UpdateDesktopBounds().
SDL_GetDisplayUsableBounds()
SDL_DECLSPEC bool SDLCALL SDL_GetDisplayUsableBounds (SDL_DisplayID displayID, SDL_Rect * rect) extern
Get the usable desktop area represented by a display, in screen coordinates.
This is the same area as SDL_GetDisplayBounds() reports, but with portions reserved by the system removed. For example, on Apple's macOS, this subtracts the area occupied by the menu bar and dock.
Setting a window to be fullscreen generally bypasses these unusable areas, so these are good guidelines for the maximum space available to a non-fullscreen window.
Parameters
displayID the instance ID of the display to query.
rect the SDL_Rect structure filled in with the display bounds.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplayBounds
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, false);
    if (!rect) {
        return SDL_InvalidParamError("rect");
    }
    if (displayID == SDL_GetPrimaryDisplay() && ParseDisplayUsableBoundsHint(rect)) {
        return true;
    }
    if (_this->GetDisplayUsableBounds) {
        if (_this->GetDisplayUsableBounds(_this, display, rect)) {
            return true;
        }
    }
    // Oh well, just give the entire display bounds.
    return SDL_GetDisplayBounds(displayID, rect);
}
References _this, CHECK_DISPLAY_MAGIC, ParseDisplayUsableBoundsHint(), SDL_GetDisplayBounds(), SDL_GetPrimaryDisplay(), SDL_GetVideoDisplay(), and SDL_InvalidParamError.
Referenced by SDL_CreateWindowWithProperties(), and SDL_SetWindowPosition().
SDL_GetFullscreenDisplayModes()
SDL_DECLSPEC SDL_DisplayMode **SDLCALL SDL_GetFullscreenDisplayModes (SDL_DisplayID displayID, int * count) extern
Get a list of fullscreen display modes available on a display.
The display modes are sorted in this priority:
w -> largest to smallest
h -> largest to smallest
bits per pixel -> more colors to fewer colors
packed pixel layout -> largest to smallest
refresh rate -> highest to lowest
pixel density -> lowest to highest
Parameters
displayID the instance ID of the display to query.
count a pointer filled in with the number of display modes returned, may be NULL.
Returns
a NULL terminated array of display mode pointers or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    int i;
    int num_modes;
    SDL_DisplayMode **result;
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    if (count) {
        *count = 0;
    }
    CHECK_DISPLAY_MAGIC(display, NULL);
    SDL_UpdateFullscreenDisplayModes(display);
    num_modes = display->num_fullscreen_modes;
    result = (SDL_DisplayMode **)SDL_malloc((num_modes + 1) * sizeof(*result) + num_modes * sizeof(**result));
    if (result) {
        SDL_DisplayMode *modes = (SDL_DisplayMode *)((Uint8 *)result + ((num_modes + 1) * sizeof(*result)));
        SDL_memcpy(modes, display->fullscreen_modes, num_modes * sizeof(*modes));
        for (i = 0; i < num_modes; ++i) {
            result[i] = modes++;
        }
        result[i] = NULL;
        if (count) {
            *count = num_modes;
        }
    } else {
        if (count) {
            *count = 0;
        }
    }
    return result;
}
References CHECK_DISPLAY_MAGIC, count, NULL, SDL_GetVideoDisplay(), SDL_malloc(), SDL_memcpy, and SDL_UpdateFullscreenDisplayModes().
SDL_GetGrabbedWindow()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetGrabbedWindow (void) extern
Get the window that currently has an input grab enabled.
Returns
the window if input is grabbed or NULL otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowMouseGrab
SDL_SetWindowKeyboardGrab
{
    if (_this->grabbed_window &&
        (_this->grabbed_window->flags & (SDL_WINDOW_MOUSE_GRABBED | SDL_WINDOW_KEYBOARD_GRABBED)) != 0) {
        return _this->grabbed_window;
    } else {
        return NULL;
    }
}
References _this, NULL, SDL_WINDOW_KEYBOARD_GRABBED, and SDL_WINDOW_MOUSE_GRABBED.
SDL_GetNaturalDisplayOrientation()
SDL_DECLSPEC SDL_DisplayOrientation SDLCALL SDL_GetNaturalDisplayOrientation (SDL_DisplayID displayID) extern
Get the orientation of a display when it is unrotated.
Parameters
displayID the instance ID of the display to query.
Returns
the SDL_DisplayOrientation enum value of the display, or SDL_ORIENTATION_UNKNOWN if it isn't available.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    SDL_VideoDisplay *display = SDL_GetVideoDisplay(displayID);
    CHECK_DISPLAY_MAGIC(display, SDL_ORIENTATION_UNKNOWN);
    if (display->natural_orientation != SDL_ORIENTATION_UNKNOWN) {
        return display->natural_orientation;
    } else {
        // Default to landscape if the driver hasn't set it
        return SDL_ORIENTATION_LANDSCAPE;
    }
}
References CHECK_DISPLAY_MAGIC, SDL_GetVideoDisplay(), SDL_ORIENTATION_LANDSCAPE, and SDL_ORIENTATION_UNKNOWN.
Referenced by AttemptSensorFusion().
SDL_GetNumVideoDrivers()
SDL_DECLSPEC int SDLCALL SDL_GetNumVideoDrivers (void) extern
Get the number of video drivers compiled into SDL.
Returns
the number of built in video drivers.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetVideoDriver
{
    static int num_drivers = -1;
    if (num_drivers >= 0) {
        return num_drivers;
    }
    num_drivers = 0;
    // Build a list of unique video drivers.
    for (int i = 0; bootstrap[i] != NULL; ++i) {
        bool duplicate = false;
        for (int j = 0; j < i; ++j) {
            if (SDL_strcmp(bootstrap[i]->name, bootstrap[j]->name) == 0) {
                duplicate = true;
                break;
            }
        }
        if (!duplicate) {
            deduped_bootstrap[num_drivers++] = bootstrap[i];
        }
    }
    return num_drivers;
}
References bootstrap, deduped_bootstrap, NULL, and SDL_strcmp().
Referenced by SDL_GetVideoDriver().
SDL_GetPrimaryDisplay()
SDL_DECLSPEC SDL_DisplayID SDLCALL SDL_GetPrimaryDisplay (void) extern
Return the primary display.
Returns
the instance ID of the primary display on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetDisplays
{
    if (!_this || _this->num_displays == 0) {
        SDL_UninitializedVideo();
        return 0;
    }
    return _this->displays[0]->id;
}
References _this, and SDL_UninitializedVideo().
Referenced by AttemptSensorFusion(), SDL_CalculateSimulatedVSyncInterval(), SDL_CreateWindowWithProperties(), SDL_GetDisplayBounds(), SDL_GetDisplayForWindowPosition(), SDL_GetDisplayUsableBounds(), SDL_GetFullscreenModeMatch(), SDL_GetVideoDisplayForFullscreenWindow(), and SDL_SetWindowPosition().
SDL_GetSystemTheme()
SDL_DECLSPEC SDL_SystemTheme SDLCALL SDL_GetSystemTheme (void) extern
Get the current system theme.
Returns
the current system theme, light, dark, or unknown.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (_this) {
        return _this->system_theme;
    } else {
        return SDL_SYSTEM_THEME_UNKNOWN;
    }
}
References _this, and SDL_SYSTEM_THEME_UNKNOWN.
SDL_GetVideoDriver()
SDL_DECLSPEC const char *SDLCALL SDL_GetVideoDriver (int index) extern
Get the name of a built in video driver.
The video drivers are presented in the order in which they are normally checked during initialization.
The names of drivers are all simple, low-ASCII identifiers, like "cocoa", "x11" or "windows". These never have Unicode characters, and are not meant to be proper names.
Parameters
index the index of a video driver.
Returns
the name of the video driver with the given index, or NULL if index is out of bounds.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumVideoDrivers
{
    if (index >= 0 && index < SDL_GetNumVideoDrivers()) {
        return deduped_bootstrap[index]->name;
    }
    SDL_InvalidParamError("index");
    return NULL;
}
References deduped_bootstrap, NULL, SDL_GetNumVideoDrivers(), and SDL_InvalidParamError.
SDL_GetWindowAspectRatio()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowAspectRatio (SDL_Window * window, float * min_aspect, float * max_aspect) extern
Get the aspect ratio of a window's client area.
Parameters
window the window to query the width and height from.
min_aspect a pointer filled in with the minimum aspect ratio of the window, may be NULL.
max_aspect a pointer filled in with the maximum aspect ratio of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowAspectRatio
{
    CHECK_WINDOW_MAGIC(window, false);
    if (min_aspect) {
        *min_aspect = window->min_aspect;
    }
    if (max_aspect) {
        *max_aspect = window->max_aspect;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowBordersSize()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowBordersSize (SDL_Window * window, int * top, int * left, int * bottom, int * right) extern
Get the size of a window's borders (decorations) around the client area.
Note: If this function fails (returns false), the size values will be initialized to 0, 0, 0, 0 (if a non-NULL pointer is provided), as if the window in question was borderless.
Note: This function may fail on systems where the window has not yet been decorated by the display server (for example, immediately after calling SDL_CreateWindow). It is recommended that you wait at least until the window has been presented and composited, so that the window system has a chance to decorate the window and provide the border dimensions to SDL.
This function also returns false if getting the information is not supported.
Parameters
window the window to query the size values of the border (decorations) from.
top pointer to variable for storing the size of the top border; NULL is permitted.
left pointer to variable for storing the size of the left border; NULL is permitted.
bottom pointer to variable for storing the size of the bottom border; NULL is permitted.
right pointer to variable for storing the size of the right border; NULL is permitted.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSize
{
    int dummy = 0;
    if (!top) {
        top = &dummy;
    }
    if (!left) {
        left = &dummy;
    }
    if (!right) {
        right = &dummy;
    }
    if (!bottom) {
        bottom = &dummy;
    }
    // Always initialize, so applications don't have to care
    *top = *left = *bottom = *right = 0;
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->GetWindowBordersSize) {
        return SDL_Unsupported();
    }
    return _this->GetWindowBordersSize(_this, window, top, left, bottom, right);
}
References _this, bottom, CHECK_WINDOW_MAGIC, left, right, SDL_Unsupported, and top.
SDL_GetWindowDisplayScale()
SDL_DECLSPEC float SDLCALL SDL_GetWindowDisplayScale (SDL_Window * window) extern
Get the content display scale relative to a window's pixel size.
This is a combination of the window pixel density and the display content scale, and is the expected scale for displaying content in this window. For example, if a 3840x2160 window had a display scale of 2.0, the user expects the content to take twice as many pixels and be the same physical size as if it were being displayed in a 1920x1080 window with a display scale of 1.0.
Conceptually this value corresponds to the scale display setting, and is updated when that setting is changed, or the window moves to a display with a different scale setting.
Parameters
window the window to query.
Returns
the display scale, or 0.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, 0.0f);
    return window->display_scale;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowFlags()
SDL_DECLSPEC SDL_WindowFlags SDLCALL SDL_GetWindowFlags (SDL_Window * window) extern
Get the window flags.
Parameters
window the window to query.
Returns
a mask of the SDL_WindowFlags associated with window.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindow
SDL_HideWindow
SDL_MaximizeWindow
SDL_MinimizeWindow
SDL_SetWindowFullscreen
SDL_SetWindowMouseGrab
SDL_ShowWindow
{
    CHECK_WINDOW_MAGIC(window, 0);
    return window->flags | window->pending_flags;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_CreateRendererWithProperties(), and SDL_RendererEventWatch().
SDL_GetWindowFromID()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetWindowFromID (SDL_WindowID id) extern
Get a window from a stored ID.
The numeric ID is what SDL_WindowEvent references, and is necessary to map these events to specific SDL_Window objects.
Parameters
id the ID of the window.
Returns
the window associated with id or NULL if it doesn't exist; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowID
{
    SDL_Window *window;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    if (id) {
        for (window = _this->windows; window; window = window->next) {
            if (window->id == id) {
                return window;
            }
        }
    }
    SDL_SetError("Invalid window ID");
    return NULL;
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_ConvertEventToRenderCoordinates(), and SDL_GetWindowFromEvent().
SDL_GetWindowFullscreenMode()
SDL_DECLSPEC const SDL_DisplayMode *SDLCALL SDL_GetWindowFullscreenMode (SDL_Window * window) extern
Query the display mode to use when a window is visible at fullscreen.
Parameters
window the window to query.
Returns
a pointer to the exclusive fullscreen mode to use or NULL for borderless fullscreen desktop mode.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowFullscreenMode
SDL_SetWindowFullscreen
{
    CHECK_WINDOW_MAGIC(window, NULL);
    CHECK_WINDOW_NOT_POPUP(window, NULL);
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        return SDL_GetFullscreenModeMatch(&window->current_fullscreen_mode);
    } else {
        return SDL_GetFullscreenModeMatch(&window->requested_fullscreen_mode);
    }
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, NULL, SDL_GetFullscreenModeMatch(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_GetWindowSizeInPixels(), and SDL_UpdateFullscreenMode().
SDL_GetWindowICCProfile()
SDL_DECLSPEC void *SDLCALL SDL_GetWindowICCProfile (SDL_Window * window, size_t * size) extern
Get the raw ICC profile data for the screen the window is currently on.
Parameters
window the window to query.
size the size of the ICC profile.
Returns
the raw ICC profile data on success or NULL on failure; call SDL_GetError() for more information. This should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (!_this->GetWindowICCProfile) {
        SDL_Unsupported();
        return NULL;
    }
    return _this->GetWindowICCProfile(_this, window, size);
}
References _this, NULL, and SDL_Unsupported.
SDL_GetWindowID()
SDL_DECLSPEC SDL_WindowID SDLCALL SDL_GetWindowID (SDL_Window * window) extern
Get the numeric ID of a window.
The numeric ID is what SDL_WindowEvent references, and is necessary to map these events to specific SDL_Window objects.
Parameters
window the window to query.
Returns
the ID of the window on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFromID
{
    CHECK_WINDOW_MAGIC(window, 0);
    return window->id;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_RendererEventWatch(), SDL_SendTouch(), and SDL_SendTouchMotion().
SDL_GetWindowKeyboardGrab()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowKeyboardGrab (SDL_Window * window) extern
Get a window's keyboard grab mode.
Parameters
window the window to query.
Returns
true if keyboard is grabbed, and false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowKeyboardGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    return window == _this->grabbed_window && (_this->grabbed_window->flags & SDL_WINDOW_KEYBOARD_GRABBED);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_KEYBOARD_GRABBED.
SDL_GetWindowMaximumSize()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowMaximumSize (SDL_Window * window, int * w, int * h) extern
Get the maximum size of a window's client area.
Parameters
window the window to query.
w a pointer filled in with the maximum width of the window, may be NULL.
h a pointer filled in with the maximum height of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMinimumSize
SDL_SetWindowMaximumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (max_w) {
        *max_w = window->max_w;
    }
    if (max_h) {
        *max_h = window->max_h;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowMinimumSize()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowMinimumSize (SDL_Window * window, int * w, int * h) extern
Get the minimum size of a window's client area.
Parameters
window the window to query.
w a pointer filled in with the minimum width of the window, may be NULL.
h a pointer filled in with the minimum height of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMaximumSize
SDL_SetWindowMinimumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (min_w) {
        *min_w = window->min_w;
    }
    if (min_h) {
        *min_h = window->min_h;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowMouseGrab()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowMouseGrab (SDL_Window * window) extern
Get a window's mouse grab mode.
Parameters
window the window to query.
Returns
true if mouse is grabbed, and false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMouseRect
SDL_SetWindowMouseRect
SDL_SetWindowMouseGrab
SDL_SetWindowKeyboardGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    return window == _this->grabbed_window && (_this->grabbed_window->flags & SDL_WINDOW_MOUSE_GRABBED);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_MOUSE_GRABBED.
SDL_GetWindowMouseRect()
SDL_DECLSPEC const SDL_Rect *SDLCALL SDL_GetWindowMouseRect (SDL_Window * window) extern
Get the mouse confinement rectangle of a window.
Parameters
window the window to query.
Returns
a pointer to the mouse confinement rectangle of a window, or NULL if there isn't one.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowMouseRect
SDL_GetWindowMouseGrab
SDL_SetWindowMouseGrab
{
    CHECK_WINDOW_MAGIC(window, NULL);
    if (SDL_RectEmpty(&window->mouse_rect)) {
        return NULL;
    } else {
        return &window->mouse_rect;
    }
}
References CHECK_WINDOW_MAGIC, NULL, and SDL_RectEmpty().
Referenced by ConstrainMousePosition().
SDL_GetWindowOpacity()
SDL_DECLSPEC float SDLCALL SDL_GetWindowOpacity (SDL_Window * window) extern
Get the opacity of a window.
If transparency isn't supported on this platform, opacity will be returned as 1.0f without error.
Parameters
window the window to get the current opacity value from.
Returns
the opacity, (0.0f - transparent, 1.0f - opaque), or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowOpacity
{
    CHECK_WINDOW_MAGIC(window, -1.0f);
    return window->opacity;
}
References CHECK_WINDOW_MAGIC.
SDL_GetWindowParent()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GetWindowParent (SDL_Window * window) extern
Get parent of a window.
Parameters
window the window to query.
Returns
the parent of the window on success or NULL if the window has no parent.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreatePopupWindow
{
    CHECK_WINDOW_MAGIC(window, NULL);
    return window->parent;
}
References CHECK_WINDOW_MAGIC, and NULL.
SDL_GetWindowPixelDensity()
SDL_DECLSPEC float SDLCALL SDL_GetWindowPixelDensity (SDL_Window * window) extern
Get the pixel density of a window.
This is a ratio of pixel size to window size. For example, if the window is 1920x1080 and it has a high density back buffer of 3840x2160 pixels, it would have a pixel density of 2.0.
Parameters
window the window to query.
Returns
the pixel density or 0.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowDisplayScale
{
    int window_w, window_h, pixel_w, pixel_h;
    float pixel_density = 1.0f;
    CHECK_WINDOW_MAGIC(window, 0.0f);
    if (SDL_GetWindowSize(window, &window_w, &window_h) &&
        SDL_GetWindowSizeInPixels(window, &pixel_w, &pixel_h)) {
        pixel_density = (float)pixel_w / window_w;
    }
    return pixel_density;
}
References CHECK_WINDOW_MAGIC, SDL_GetWindowSize(), and SDL_GetWindowSizeInPixels().
Referenced by SDL_CheckWindowDisplayScaleChanged().
SDL_GetWindowPixelFormat()
SDL_DECLSPEC SDL_PixelFormat SDLCALL SDL_GetWindowPixelFormat (SDL_Window * window) extern
Get the pixel format associated with the window.
Parameters
window the window to query.
Returns
the pixel format of the window on success or SDL_PIXELFORMAT_UNKNOWN on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_DisplayID displayID;
    const SDL_DisplayMode *mode;
    CHECK_WINDOW_MAGIC(window, SDL_PIXELFORMAT_UNKNOWN);
    displayID = SDL_GetDisplayForWindow(window);
    mode = SDL_GetCurrentDisplayMode(displayID);
    if (mode) {
        return mode->format;
    } else {
        return SDL_PIXELFORMAT_UNKNOWN;
    }
}
References CHECK_WINDOW_MAGIC, SDL_DisplayMode::format, SDL_GetCurrentDisplayMode(), SDL_GetDisplayForWindow(), and SDL_PIXELFORMAT_UNKNOWN.
SDL_GetWindowPosition()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowPosition (SDL_Window * window, int * x, int * y) extern
Get the position of a window.
This is the current position of the window as last reported by the windowing system.
If you do not need the value for one of the positions a NULL may be passed in the x or y parameter.
Parameters
window the window to query.
x a pointer filled in with the x position of the window, may be NULL.
y a pointer filled in with the y position of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowPosition
{
    CHECK_WINDOW_MAGIC(window, false);
    // Fullscreen windows are always at their display's origin
    if (window->flags & SDL_WINDOW_FULLSCREEN) {
        SDL_DisplayID displayID;
        if (x) {
            *x = 0;
        }
        if (y) {
            *y = 0;
        }
        /* Find the window's monitor and update to the
           monitor offset. */
        displayID = SDL_GetDisplayForWindow(window);
        if (displayID != 0) {
            SDL_Rect bounds;
            SDL_zero(bounds);
            SDL_GetDisplayBounds(displayID, &bounds);
            if (x) {
                *x = bounds.x;
            }
            if (y) {
                *y = bounds.y;
            }
        }
    } else {
        const bool use_pending = (window->flags & SDL_WINDOW_HIDDEN) && window->last_position_pending;
        if (x) {
            *x = use_pending ? window->pending.x : window->x;
        }
        if (y) {
            *y = use_pending ? window->pending.y : window->y;
        }
    }
    return true;
}
References CHECK_WINDOW_MAGIC, SDL_GetDisplayBounds(), SDL_GetDisplayForWindow(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, SDL_zero, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_BLooper::_HandleMouseMove(), and SDL_Fcitx_UpdateTextInputArea().
SDL_GetWindowProgressState()
SDL_DECLSPEC SDL_ProgressState SDLCALL SDL_GetWindowProgressState (SDL_Window * window) extern
Get the state of the progress bar for the given windows taskbar icon.
Parameters
window the window to get the current progress state from.
Returns
the progress state, or SDL_PROGRESS_STATE_INVALID on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, SDL_PROGRESS_STATE_INVALID);
    CHECK_WINDOW_NOT_POPUP(window, SDL_PROGRESS_STATE_INVALID);
    return window->progress_state;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_PROGRESS_STATE_INVALID.
SDL_GetWindowProgressValue()
SDL_DECLSPEC float SDLCALL SDL_GetWindowProgressValue (SDL_Window * window) extern
Get the value of the progress bar for the given windows taskbar icon.
Parameters
window the window to get the current progress value from.
Returns
the progress value in the range of [0.0f - 1.0f], or -1.0f on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, -1.0f);
    CHECK_WINDOW_NOT_POPUP(window, -1.0f);
    return window->progress_value;
}
References CHECK_WINDOW_MAGIC, and CHECK_WINDOW_NOT_POPUP.
SDL_GetWindowProperties()
SDL_DECLSPEC SDL_PropertiesID SDLCALL SDL_GetWindowProperties (SDL_Window * window) extern
Get the properties associated with a window.
The following read-only properties are provided by SDL:
SDL_PROP_WINDOW_SHAPE_POINTER: the surface associated with a shaped window
SDL_PROP_WINDOW_HDR_ENABLED_BOOLEAN: true if the window has HDR headroom above the SDR white point. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT: the value of SDR white in the SDL_COLORSPACE_SRGB_LINEAR colorspace. On Windows this corresponds to the SDR white level in scRGB colorspace, and on Apple platforms this is always 1.0 for EDR content. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT: the additional high dynamic range that can be displayed, in terms of the SDR white point. When HDR is not enabled, this will be 1.0. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
On Android:
SDL_PROP_WINDOW_ANDROID_WINDOW_POINTER: the ANativeWindow associated with the window
SDL_PROP_WINDOW_ANDROID_SURFACE_POINTER: the EGLSurface associated with the window
On iOS:
SDL_PROP_WINDOW_UIKIT_WINDOW_POINTER: the (__unsafe_unretained) UIWindow associated with the window
SDL_PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER: the NSInteger tag associated with metal views on the window
SDL_PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER: the OpenGL view's framebuffer object. It must be bound when rendering to the screen using OpenGL.
SDL_PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER: the OpenGL view's renderbuffer object. It must be bound when SDL_GL_SwapWindow is called.
SDL_PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER: the OpenGL view's resolve framebuffer, when MSAA is used.
On KMS/DRM:
SDL_PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER: the device index associated with the window (e.g. the X in /dev/dri/cardX)
SDL_PROP_WINDOW_KMSDRM_DRM_FD_NUMBER: the DRM FD associated with the window
SDL_PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER: the GBM device associated with the window
On macOS:
SDL_PROP_WINDOW_COCOA_WINDOW_POINTER: the (__unsafe_unretained) NSWindow associated with the window
SDL_PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER: the NSInteger tag assocated with metal views on the window
On OpenVR:
SDL_PROP_WINDOW_OPENVR_OVERLAY_ID_NUMBER: the OpenVR Overlay Handle ID for the associated overlay window.
On Vivante:
SDL_PROP_WINDOW_VIVANTE_DISPLAY_POINTER: the EGLNativeDisplayType associated with the window
SDL_PROP_WINDOW_VIVANTE_WINDOW_POINTER: the EGLNativeWindowType associated with the window
SDL_PROP_WINDOW_VIVANTE_SURFACE_POINTER: the EGLSurface associated with the window
On Windows:
SDL_PROP_WINDOW_WIN32_HWND_POINTER: the HWND associated with the window
SDL_PROP_WINDOW_WIN32_HDC_POINTER: the HDC associated with the window
SDL_PROP_WINDOW_WIN32_INSTANCE_POINTER: the HINSTANCE associated with the window
On Wayland:
Note: The xdg_* window objects do not internally persist across window show/hide calls. They will be null if the window is hidden and must be queried each time it is shown.
SDL_PROP_WINDOW_WAYLAND_DISPLAY_POINTER: the wl_display associated with the window
SDL_PROP_WINDOW_WAYLAND_SURFACE_POINTER: the wl_surface associated with the window
SDL_PROP_WINDOW_WAYLAND_VIEWPORT_POINTER: the wp_viewport associated with the window
SDL_PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER: the wl_egl_window associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER: the xdg_surface associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER: the xdg_toplevel role associated with the window
'SDL_PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING': the export handle associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER: the xdg_popup role associated with the window
SDL_PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER: the xdg_positioner associated with the window, in popup mode
On X11:
SDL_PROP_WINDOW_X11_DISPLAY_POINTER: the X11 Display associated with the window
SDL_PROP_WINDOW_X11_SCREEN_NUMBER: the screen number associated with the window
SDL_PROP_WINDOW_X11_WINDOW_NUMBER: the X11 Window associated with the window
On Emscripten:
SDL_PROP_WINDOW_EMSCRIPTEN_CANVAS_ID_STRING: the id the canvas element will have
SDL_PROP_WINDOW_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING: the keyboard element that associates keyboard events to this window
Parameters
window the window to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, 0);
    if (window->props == 0) {
        window->props = SDL_CreateProperties();
    }
    return window->props;
}
References CHECK_WINDOW_MAGIC, and SDL_CreateProperties().
Referenced by get_x11_window_handle(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), SDL_DestroyRendererWithoutFreeing(), SDL_DestroyWindowTexture(), SDL_Fcitx_UpdateTextInputArea(), SDL_GetDisplayForWindow(), SDL_GetRenderer(), SDL_GetWindowTextureVSync(), SDL_RenderApplyWindowShape(), SDL_SetWindowHDRProperties(), SDL_SetWindowShape(), SDL_SetWindowTextureVSync(), SDL_UpdateWindowTexture(), UpdateHDRProperties(), windows_ShowFileDialog(), and windows_ShowFolderDialog().
SDL_GetWindows()
SDL_DECLSPEC SDL_Window **SDLCALL SDL_GetWindows (int * count) extern
Get a list of valid windows.
Parameters
count a pointer filled in with the number of windows returned, may be NULL.
Returns
a NULL terminated array of SDL_Window pointers or NULL on failure; call SDL_GetError() for more information. This is a single allocation that should be freed with SDL_free() when it is no longer needed.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (count) {
        *count = 0;
    }
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    SDL_Window *window;
    int num_added = 0;
    int num_windows = 0;
    for (window = _this->windows; window; window = window->next) {
        ++num_windows;
    }
    SDL_Window **windows = (SDL_Window **)SDL_malloc((num_windows + 1) * sizeof(*windows));
    if (!windows) {
        return NULL;
    }
    for (window = _this->windows; window; window = window->next) {
        windows[num_added++] = window;
        if (num_added == num_windows) {
            // Race condition? Multi-threading not supported, ignore it
            break;
        }
    }
    windows[num_added] = NULL;
    if (count) {
        *count = num_added;
    }
    return windows;
}
References _this, count, NULL, SDL_malloc(), SDL_UninitializedVideo(), and SDLCALL.
Referenced by SDL_UnregisterTray().
SDL_GetWindowSafeArea()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSafeArea (SDL_Window * window, SDL_Rect * rect) extern
Get the safe area for this window.
Some devices have portions of the screen which are partially obscured or not interactive, possibly due to on-screen controls, curved edges, camera notches, TV overscan, etc. This function provides the area of the window which is safe to have interactable content. You should continue rendering into the rest of the window, but it should not contain visually important or interactible content.
Parameters
window the window to query.
rect a pointer filled in with the client area that is safe for interactive content.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (rect) {
        SDL_zerop(rect);
    }
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        if (SDL_RectEmpty(&window->safe_rect)) {
            rect->w = window->w;
            rect->h = window->h;
        } else {
            SDL_copyp(rect, &window->safe_rect);
        }
    }
    return true;
}
References CHECK_WINDOW_MAGIC, SDL_Rect::h, SDL_copyp, SDL_RectEmpty(), SDL_zerop, and SDL_Rect::w.
Referenced by SDL_GetRenderSafeArea().
SDL_GetWindowSize()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSize (SDL_Window * window, int * w, int * h) extern
Get the size of a window's client area.
The window pixel size may differ from its window coordinate size if the window is on a high pixel density display. Use SDL_GetWindowSizeInPixels() or SDL_GetRenderOutputSize() to get the real client area size in pixels.
Parameters
window the window to query the width and height from.
w a pointer filled in with the width of the window, may be NULL.
h a pointer filled in with the height of the window, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderOutputSize
SDL_GetWindowSizeInPixels
SDL_SetWindowSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (w) {
        *w = window->w;
    }
    if (h) {
        *h = window->h;
    }
    return true;
}
References CHECK_WINDOW_MAGIC.
Referenced by SDL_BLooper::_HandleMouseMove(), SDL_ConvertEventToRenderCoordinates(), SDL_Fcitx_UpdateTextInputArea(), SDL_GetWindowPixelDensity(), SDL_GetWindowSizeInPixels(), and UpdateMainViewDimensions().
SDL_GetWindowSizeInPixels()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSizeInPixels (SDL_Window * window, int * w, int * h) extern
Get the size of a window's client area, in pixels.
Parameters
window the window from which the drawable size should be queried.
w a pointer to variable for storing the width in pixels, may be NULL.
h a pointer to variable for storing the height in pixels, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateWindow
SDL_GetWindowSize
{
    int filter;
    CHECK_WINDOW_MAGIC(window, false);
    if (!w) {
        w = &filter;
    }
    if (!h) {
        h = &filter;
    }
    if (_this->GetWindowSizeInPixels) {
        _this->GetWindowSizeInPixels(_this, window, w, h);
    } else {
        SDL_DisplayID displayID = SDL_GetDisplayForWindow(window);
        const SDL_DisplayMode *mode;
        SDL_GetWindowSize(window, w, h);
        if ((window->flags & SDL_WINDOW_FULLSCREEN) && SDL_GetWindowFullscreenMode(window)) {
            mode = SDL_GetCurrentDisplayMode(displayID);
        } else {
            mode = SDL_GetDesktopDisplayMode(displayID);
        }
        if (mode) {
            *w = (int)SDL_ceilf(*w * mode->pixel_density);
            *h = (int)SDL_ceilf(*h * mode->pixel_density);
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_DisplayMode::pixel_density, SDL_ceilf(), SDL_GetCurrentDisplayMode(), SDL_GetDesktopDisplayMode(), SDL_GetDisplayForWindow(), SDL_GetWindowFullscreenMode(), SDL_GetWindowSize(), and SDL_WINDOW_FULLSCREEN.
Referenced by SDL_CheckWindowPixelSizeChanged(), SDL_CreateWindowFramebuffer(), SDL_CreateWindowTexture(), SDL_GetRenderOutputSize(), SDL_GetWindowPixelDensity(), SDL_UpdateWindowSurface(), and SDL_UpdateWindowTexture().
SDL_GetWindowSurface()
SDL_DECLSPEC SDL_Surface *SDLCALL SDL_GetWindowSurface (SDL_Window * window) extern
Get the SDL surface associated with the window.
A new surface will be created with the optimal format for the window, if necessary. This surface will be freed when the window is destroyed. Do not free this surface.
This surface will be invalidated if the window is resized. After resizing a window this function must be called again to return a valid surface.
You may not combine this with 3D or the rendering API on this window.
This function is affected by SDL_HINT_FRAMEBUFFER_ACCELERATION.
Parameters
window the window to query.
Returns
the surface associated with the window, or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyWindowSurface
SDL_WindowHasSurface
SDL_UpdateWindowSurface
SDL_UpdateWindowSurfaceRects
< Surface is referenced internally
< Surface is referenced internally
{
    CHECK_WINDOW_MAGIC(window, NULL);
    if (!window->surface_valid) {
        if (window->surface) {
            window->surface->internal_flags &= ~SDL_INTERNAL_SURFACE_DONTFREE;
            SDL_DestroySurface(window->surface);
            window->surface = NULL;
        }
        window->surface = SDL_CreateWindowFramebuffer(window);
        if (window->surface) {
            window->surface_valid = true;
            window->surface->internal_flags |= SDL_INTERNAL_SURFACE_DONTFREE;
        }
    }
    return window->surface;
}
References CHECK_WINDOW_MAGIC, NULL, SDL_CreateWindowFramebuffer(), SDL_DestroySurface(), and SDL_INTERNAL_SURFACE_DONTFREE.
SDL_GetWindowSurfaceVSync()
SDL_DECLSPEC bool SDLCALL SDL_GetWindowSurfaceVSync (SDL_Window * window, int * vsync) extern
Get VSync for the window surface.
Parameters
window the window to query.
vsync an int filled with the current vertical refresh sync interval. See SDL_SetWindowSurfaceVSync() for the meaning of the value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowSurfaceVSync
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->GetWindowFramebufferVSync) {
        return SDL_Unsupported();
    }
    return _this->GetWindowFramebufferVSync(_this, window, vsync);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_Unsupported.
SDL_GetWindowTitle()
SDL_DECLSPEC const char *SDLCALL SDL_GetWindowTitle (SDL_Window * window) extern
Get the title of a window.
Parameters
window the window to query.
Returns
the title of the window in UTF-8 format or "" if there is no title.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowTitle
{
    CHECK_WINDOW_MAGIC(window, "");
    return window->title ? window->title : "";
}
References CHECK_WINDOW_MAGIC.
SDL_GL_CreateContext()
SDL_DECLSPEC SDL_GLContext SDLCALL SDL_GL_CreateContext (SDL_Window * window) extern
Create an OpenGL context for an OpenGL window, and make it current.
Windows users new to OpenGL should note that, for historical reasons, GL functions added after OpenGL version 1.1 are not available by default. Those functions must be loaded at run-time, either with an OpenGL extension-handling library or with SDL_GL_GetProcAddress() and its related functions.
SDL_GLContext is opaque to the application.
Parameters
window the window to associate with the context.
Returns
the OpenGL context associated with window or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_DestroyContext
SDL_GL_MakeCurrent
{
    SDL_GLContext ctx = NULL;
    CHECK_WINDOW_MAGIC(window, NULL);
    if (!(window->flags & SDL_WINDOW_OPENGL)) {
        SDL_SetError(NOT_AN_OPENGL_WINDOW);
        return NULL;
    }
    ctx = _this->GL_CreateContext(_this, window);
    // Creating a context is assumed to make it current in the SDL driver.
    if (ctx) {
        _this->current_glwin = window;
        _this->current_glctx = ctx;
        SDL_SetTLS(&_this->current_glwin_tls, window, NULL);
        SDL_SetTLS(&_this->current_glctx_tls, ctx, NULL);
    }
    return ctx;
}
References _this, CHECK_WINDOW_MAGIC, NOT_AN_OPENGL_WINDOW, NULL, SDL_SetError(), SDL_SetTLS(), and SDL_WINDOW_OPENGL.
SDL_GL_DestroyContext()
SDL_DECLSPEC bool SDLCALL SDL_GL_DestroyContext (SDL_GLContext context) extern
Delete an OpenGL context.
Parameters
context the OpenGL context to be deleted.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_CreateContext
{
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (!context) {
        return SDL_InvalidParamError("context");
    }
    if (SDL_GL_GetCurrentContext() == context) {
        SDL_GL_MakeCurrent(NULL, NULL);
    }
    return _this->GL_DestroyContext(_this, context);
}
References _this, context, NULL, SDL_GL_GetCurrentContext(), SDL_GL_MakeCurrent(), SDL_InvalidParamError, and SDL_UninitializedVideo().
SDL_GL_ExtensionSupported()
SDL_DECLSPEC bool SDLCALL SDL_GL_ExtensionSupported (const char * extension) extern
Check if an OpenGL extension is supported for the current context.
This function operates on the current GL context; you must have created a context and it must be current before calling this function. Do not assume that all contexts you create will have the same set of extensions available, or that recreating an existing context will offer the same extensions again.
While it's probably not a massive overhead, this function is not an O(1) operation. Check the extensions you care about after creating the GL context and save that information somewhere instead of calling the function every time you need to know.
Parameters
extension the name of the extension to check.
Returns
true if the extension is supported, false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    PFNGLGETSTRINGPROC glGetStringFunc;
    const char *extensions;
    const char *start;
    const char *where, *terminator;
    // Extension names should not have spaces.
    where = SDL_strchr(extension, ' ');
    if (where || *extension == '\0') {
        return false;
    }
    // See if there's a hint or environment variable override
    start = SDL_GetHint(extension);
    if (start && *start == '0') {
        return false;
    }
    // Lookup the available extensions
    glGetStringFunc = (PFNGLGETSTRINGPROC)SDL_GL_GetProcAddress("glGetString");
    if (!glGetStringFunc) {
        return false;
    }
    if (isAtLeastGL3((const char *)glGetStringFunc(GL_VERSION))) {
        PFNGLGETSTRINGIPROC glGetStringiFunc;
        PFNGLGETINTEGERVPROC glGetIntegervFunc;
        GLint num_exts = 0;
        GLint i;
        glGetStringiFunc = (PFNGLGETSTRINGIPROC)SDL_GL_GetProcAddress("glGetStringi");
        glGetIntegervFunc = (PFNGLGETINTEGERVPROC)SDL_GL_GetProcAddress("glGetIntegerv");
        if ((!glGetStringiFunc) || (!glGetIntegervFunc)) {
            return false;
        }
#ifndef GL_NUM_EXTENSIONS
#define GL_NUM_EXTENSIONS 0x821D
#endif
        glGetIntegervFunc(GL_NUM_EXTENSIONS, &num_exts);
        for (i = 0; i < num_exts; i++) {
            const char *thisext = (const char *)glGetStringiFunc(GL_EXTENSIONS, i);
            if (SDL_strcmp(thisext, extension) == 0) {
                return true;
            }
        }
        return false;
    }
    // Try the old way with glGetString(GL_EXTENSIONS) ...
    extensions = (const char *)glGetStringFunc(GL_EXTENSIONS);
    if (!extensions) {
        return false;
    }
    /*
     * It takes a bit of care to be fool-proof about parsing the OpenGL
     * extensions string. Don't be fooled by sub-strings, etc.
     */
    start = extensions;
    for (;;) {
        where = SDL_strstr(start, extension);
        if (!where) {
            break;
        }
        terminator = where + SDL_strlen(extension);
        if (where == extensions || *(where - 1) == ' ') {
            if (*terminator == ' ' || *terminator == '\0') {
                return true;
            }
        }
        start = terminator;
    }
    return false;
#else
    return false;
#endif
}
References GL_EXTENSIONS, GL_NUM_EXTENSIONS, GL_VERSION, SDL_GetHint(), SDL_GL_GetProcAddress(), SDL_strchr(), SDL_strcmp(), SDL_strlen(), and SDL_strstr().
Referenced by SDL_GL_DeduceMaxSupportedESProfile().
SDL_GL_GetAttribute()
SDL_DECLSPEC bool SDLCALL SDL_GL_GetAttribute (SDL_GLAttr attr, int * value) extern
Get the actual value for an attribute from the current context.
Parameters
attr an SDL_GLAttr enum value specifying the OpenGL attribute to get.
value a pointer filled in with the current value of attr.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_ResetAttributes
SDL_GL_SetAttribute
{
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    PFNGLGETERRORPROC glGetErrorFunc;
    GLenum attrib = 0;
    GLenum error = 0;
    /*
     * Some queries in Core Profile desktop OpenGL 3+ contexts require
     * glGetFramebufferAttachmentParameteriv instead of glGetIntegerv. Note that
     * the enums we use for the former function don't exist in OpenGL ES 2, and
     * the function itself doesn't exist prior to OpenGL 3 and OpenGL ES 2.
     */
#ifdef SDL_VIDEO_OPENGL
    PFNGLGETSTRINGPROC glGetStringFunc;
    PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameterivFunc;
    GLenum attachment = GL_BACK_LEFT;
    GLenum attachmentattrib = 0;
#endif
    if (!value) {
        return SDL_InvalidParamError("value");
    }
    // Clear value in any case
    *value = 0;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    switch (attr) {
    case SDL_GL_RED_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE;
#endif
        attrib = GL_RED_BITS;
        break;
    case SDL_GL_BLUE_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE;
#endif
        attrib = GL_BLUE_BITS;
        break;
    case SDL_GL_GREEN_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE;
#endif
        attrib = GL_GREEN_BITS;
        break;
    case SDL_GL_ALPHA_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE;
#endif
        attrib = GL_ALPHA_BITS;
        break;
    case SDL_GL_DOUBLEBUFFER:
#ifdef SDL_VIDEO_OPENGL
        attrib = GL_DOUBLEBUFFER;
        break;
#else
        // OpenGL ES 1.0 and above specifications have EGL_SINGLE_BUFFER
        // parameter which switches double buffer to single buffer. OpenGL ES
        // SDL driver must set proper value after initialization
        *value = _this->gl_config.double_buffer;
        return true;
#endif
    case SDL_GL_DEPTH_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachment = GL_DEPTH;
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE;
#endif
        attrib = GL_DEPTH_BITS;
        break;
    case SDL_GL_STENCIL_SIZE:
#ifdef SDL_VIDEO_OPENGL
        attachment = GL_STENCIL;
        attachmentattrib = GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE;
#endif
        attrib = GL_STENCIL_BITS;
        break;
#ifdef SDL_VIDEO_OPENGL
    case SDL_GL_ACCUM_RED_SIZE:
        attrib = GL_ACCUM_RED_BITS;
        break;
    case SDL_GL_ACCUM_GREEN_SIZE:
        attrib = GL_ACCUM_GREEN_BITS;
        break;
    case SDL_GL_ACCUM_BLUE_SIZE:
        attrib = GL_ACCUM_BLUE_BITS;
        break;
    case SDL_GL_ACCUM_ALPHA_SIZE:
        attrib = GL_ACCUM_ALPHA_BITS;
        break;
    case SDL_GL_STEREO:
        attrib = GL_STEREO;
        break;
#else
    case SDL_GL_ACCUM_RED_SIZE:
    case SDL_GL_ACCUM_GREEN_SIZE:
    case SDL_GL_ACCUM_BLUE_SIZE:
    case SDL_GL_ACCUM_ALPHA_SIZE:
    case SDL_GL_STEREO:
        // none of these are supported in OpenGL ES
        *value = 0;
        return true;
#endif
    case SDL_GL_MULTISAMPLEBUFFERS:
        attrib = GL_SAMPLE_BUFFERS;
        break;
    case SDL_GL_MULTISAMPLESAMPLES:
        attrib = GL_SAMPLES;
        break;
    case SDL_GL_CONTEXT_RELEASE_BEHAVIOR:
        attrib = GL_CONTEXT_RELEASE_BEHAVIOR;
        break;
    case SDL_GL_BUFFER_SIZE:
    {
        int rsize = 0, gsize = 0, bsize = 0, asize = 0;
        // There doesn't seem to be a single flag in OpenGL for this!
        if (!SDL_GL_GetAttribute(SDL_GL_RED_SIZE, &rsize)) {
            return false;
        }
        if (!SDL_GL_GetAttribute(SDL_GL_GREEN_SIZE, &gsize)) {
            return false;
        }
        if (!SDL_GL_GetAttribute(SDL_GL_BLUE_SIZE, &bsize)) {
            return false;
        }
        if (!SDL_GL_GetAttribute(SDL_GL_ALPHA_SIZE, &asize)) {
            return false;
        }
        *value = rsize + gsize + bsize + asize;
        return true;
    }
    case SDL_GL_ACCELERATED_VISUAL:
    {
        // FIXME: How do we get this information?
        *value = (_this->gl_config.accelerated != 0);
        return true;
    }
    case SDL_GL_RETAINED_BACKING:
    {
        *value = _this->gl_config.retained_backing;
        return true;
    }
    case SDL_GL_CONTEXT_MAJOR_VERSION:
    {
        *value = _this->gl_config.major_version;
        return true;
    }
    case SDL_GL_CONTEXT_MINOR_VERSION:
    {
        *value = _this->gl_config.minor_version;
        return true;
    }
    case SDL_GL_CONTEXT_FLAGS:
    {
        *value = _this->gl_config.flags;
        return true;
    }
    case SDL_GL_CONTEXT_PROFILE_MASK:
    {
        *value = _this->gl_config.profile_mask;
        return true;
    }
    case SDL_GL_SHARE_WITH_CURRENT_CONTEXT:
    {
        *value = _this->gl_config.share_with_current_context;
        return true;
    }
    case SDL_GL_FRAMEBUFFER_SRGB_CAPABLE:
    {
        *value = _this->gl_config.framebuffer_srgb_capable;
        return true;
    }
    case SDL_GL_CONTEXT_NO_ERROR:
    {
        *value = _this->gl_config.no_error;
        return true;
    }
    case SDL_GL_EGL_PLATFORM:
    {
        *value = _this->gl_config.egl_platform;
        return true;
    }
    default:
        return SDL_SetError("Unknown OpenGL attribute");
    }
#ifdef SDL_VIDEO_OPENGL
    glGetStringFunc = (PFNGLGETSTRINGPROC)SDL_GL_GetProcAddress("glGetString");
    if (!glGetStringFunc) {
        return false;
    }
    if (attachmentattrib && isAtLeastGL3((const char *)glGetStringFunc(GL_VERSION))) {
        // glGetFramebufferAttachmentParameteriv needs to operate on the window framebuffer for this, so bind FBO 0 if necessary.
        GLint current_fbo = 0;
        PFNGLGETINTEGERVPROC glGetIntegervFunc = (PFNGLGETINTEGERVPROC) SDL_GL_GetProcAddress("glGetIntegerv");
        PFNGLBINDFRAMEBUFFERPROC glBindFramebufferFunc = (PFNGLBINDFRAMEBUFFERPROC)SDL_GL_GetProcAddress("glBindFramebuffer");
        if (glGetIntegervFunc && glBindFramebufferFunc) {
            glGetIntegervFunc(GL_DRAW_FRAMEBUFFER_BINDING, &current_fbo);
        }
        glGetFramebufferAttachmentParameterivFunc = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)SDL_GL_GetProcAddress("glGetFramebufferAttachmentParameteriv");
        if (glGetFramebufferAttachmentParameterivFunc) {
            if (glBindFramebufferFunc && (current_fbo != 0)) {
                glBindFramebufferFunc(GL_DRAW_FRAMEBUFFER, 0);
            }
            // glGetFramebufferAttachmentParameterivFunc may cause GL_INVALID_OPERATION when querying depth/stencil size if the
            // bits is 0. From the GL docs:
            //      If the value of GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE is GL_NONE, then either no framebuffer is bound to target;
            //      or a default framebuffer is queried, attachment is GL_DEPTH or GL_STENCIL, and the number of depth or stencil bits,
            //      respectively, is zero. In this case querying pname GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME will return zero, and all
            //      other queries will generate an error.
            GLint fbo_type = GL_FRAMEBUFFER_DEFAULT;
            if (attachment == GL_DEPTH || attachment == GL_STENCIL) {
                glGetFramebufferAttachmentParameterivFunc(GL_FRAMEBUFFER, attachment, GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, &fbo_type);
            }
            if (fbo_type != GL_NONE) {
                glGetFramebufferAttachmentParameterivFunc(GL_FRAMEBUFFER, attachment, attachmentattrib, (GLint *)value);
            } else {
                *value = 0;
            }
            if (glBindFramebufferFunc && (current_fbo != 0)) {
                glBindFramebufferFunc(GL_DRAW_FRAMEBUFFER, current_fbo);
            }
        } else {
            return false;
        }
    } else
#endif
    {
        PFNGLGETINTEGERVPROC glGetIntegervFunc = (PFNGLGETINTEGERVPROC)SDL_GL_GetProcAddress("glGetIntegerv");
        if (glGetIntegervFunc) {
            glGetIntegervFunc(attrib, (GLint *)value);
        } else {
            return false;
        }
    }
    glGetErrorFunc = (PFNGLGETERRORPROC)SDL_GL_GetProcAddress("glGetError");
    if (!glGetErrorFunc) {
        return false;
    }
    error = glGetErrorFunc();
    if (error != GL_NO_ERROR) {
        if (error == GL_INVALID_ENUM) {
            return SDL_SetError("OpenGL error: GL_INVALID_ENUM");
        } else if (error == GL_INVALID_VALUE) {
            return SDL_SetError("OpenGL error: GL_INVALID_VALUE");
        }
        return SDL_SetError("OpenGL error: %08X", error);
    }
    // convert GL_CONTEXT_RELEASE_BEHAVIOR values back to SDL_GL_CONTEXT_RELEASE_BEHAVIOR values
    if (attr == SDL_GL_CONTEXT_RELEASE_BEHAVIOR) {
        *value = (*value == GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH) ? SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH : SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE;
    }
    return true;
#else
    return SDL_Unsupported();
#endif // SDL_VIDEO_OPENGL
}
References _this, GL_ACCUM_ALPHA_BITS, GL_ACCUM_BLUE_BITS, GL_ACCUM_GREEN_BITS, GL_ACCUM_RED_BITS, GL_ALPHA_BITS, GL_BACK_LEFT, GL_BLUE_BITS, GL_CONTEXT_RELEASE_BEHAVIOR, GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, GL_DEPTH, GL_DEPTH_BITS, GL_DOUBLEBUFFER, GL_DRAW_FRAMEBUFFER, GL_DRAW_FRAMEBUFFER_BINDING, GL_FRAMEBUFFER, GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE, GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE, GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE, GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE, GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE, GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE, GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE, GL_FRAMEBUFFER_DEFAULT, GL_GREEN_BITS, GL_INVALID_ENUM, GL_INVALID_VALUE, GL_NO_ERROR, GL_NONE, GL_RED_BITS, GL_SAMPLE_BUFFERS, GL_SAMPLES, GL_STENCIL, GL_STENCIL_BITS, GL_STEREO, GL_VERSION, SDL_GL_ACCELERATED_VISUAL, SDL_GL_ACCUM_ALPHA_SIZE, SDL_GL_ACCUM_BLUE_SIZE, SDL_GL_ACCUM_GREEN_SIZE, SDL_GL_ACCUM_RED_SIZE, SDL_GL_ALPHA_SIZE, SDL_GL_BLUE_SIZE, SDL_GL_BUFFER_SIZE, SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_MAJOR_VERSION, SDL_GL_CONTEXT_MINOR_VERSION, SDL_GL_CONTEXT_NO_ERROR, SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_RELEASE_BEHAVIOR, SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, SDL_GL_CONTEXT_RELEASE_BEHAVIOR_NONE, SDL_GL_DEPTH_SIZE, SDL_GL_DOUBLEBUFFER, SDL_GL_EGL_PLATFORM, SDL_GL_FRAMEBUFFER_SRGB_CAPABLE, SDL_GL_GetAttribute(), SDL_GL_GetProcAddress(), SDL_GL_GREEN_SIZE, SDL_GL_MULTISAMPLEBUFFERS, SDL_GL_MULTISAMPLESAMPLES, SDL_GL_RED_SIZE, SDL_GL_RETAINED_BACKING, SDL_GL_SHARE_WITH_CURRENT_CONTEXT, SDL_GL_STENCIL_SIZE, SDL_GL_STEREO, SDL_InvalidParamError, SDL_SetError(), SDL_UninitializedVideo(), and SDL_Unsupported.
Referenced by SDL_GL_GetAttribute().
SDL_GL_GetCurrentContext()
SDL_DECLSPEC SDL_GLContext SDLCALL SDL_GL_GetCurrentContext (void) extern
Get the currently active OpenGL context.
Returns
the currently active OpenGL context or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_MakeCurrent
{
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    return (SDL_GLContext)SDL_GetTLS(&_this->current_glctx_tls);
}
References _this, NULL, SDL_GetTLS(), and SDL_UninitializedVideo().
Referenced by SDL_GL_DestroyContext(), SDL_GL_GetSwapInterval(), SDL_GL_MakeCurrent(), and SDL_GL_SetSwapInterval().
SDL_GL_GetCurrentWindow()
SDL_DECLSPEC SDL_Window *SDLCALL SDL_GL_GetCurrentWindow (void) extern
Get the currently active OpenGL window.
Returns
the currently active OpenGL window on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    return (SDL_Window *)SDL_GetTLS(&_this->current_glwin_tls);
}
References _this, NULL, SDL_GetTLS(), and SDL_UninitializedVideo().
Referenced by SDL_GL_MakeCurrent(), and SDL_GL_SwapWindow().
SDL_GL_GetProcAddress()
SDL_DECLSPEC SDL_FunctionPointer SDLCALL SDL_GL_GetProcAddress (const char * proc) extern
Get an OpenGL function by name.
If the GL library is loaded at runtime with SDL_GL_LoadLibrary(), then all GL functions must be retrieved this way. Usually this is used to retrieve function pointers to OpenGL extensions.
There are some quirks to looking up OpenGL functions that require some extra care from the application. If you code carefully, you can handle these quirks without any platform-specific code, though:
On Windows, function pointers are specific to the current GL context; this means you need to have created a GL context and made it current before calling SDL_GL_GetProcAddress(). If you recreate your context or create a second context, you should assume that any existing function pointers aren't valid to use with it. This is (currently) a Windows-specific limitation, and in practice lots of drivers don't suffer this limitation, but it is still the way the wgl API is documented to work and you should expect crashes if you don't respect it. Store a copy of the function pointers that comes and goes with context lifespan.
On X11, function pointers returned by this function are valid for any context, and can even be looked up before a context is created at all. This means that, for at least some common OpenGL implementations, if you look up a function that doesn't exist, you'll get a non-NULL result that is NOT safe to call. You must always make sure the function is actually available for a given GL context before calling it, by checking for the existence of the appropriate extension with SDL_GL_ExtensionSupported(), or verifying that the version of OpenGL you're using offers the function as core functionality.
Some OpenGL drivers, on all platforms, will return NULL if a function isn't supported, but you can't count on this behavior. Check for extensions you use, and if you get a NULL anyway, act as if that extension wasn't available. This is probably a bug in the driver, but you can code defensively for this scenario anyhow.
Just because you're on Linux/Unix, don't assume you'll be using X11. Next-gen display servers are waiting to replace it, and may or may not make the same promises about function pointers.
OpenGL function pointers must be declared APIENTRY as in the example code. This will ensure the proper calling convention is followed on platforms where this matters (Win32) thereby avoiding stack corruption.
Parameters
proc the name of an OpenGL function.
Returns
a pointer to the named OpenGL function. The returned pointer should be cast to the appropriate function signature.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_ExtensionSupported
SDL_GL_LoadLibrary
SDL_GL_UnloadLibrary
{
    SDL_FunctionPointer func;
    if (!_this) {
        SDL_UninitializedVideo();
        return NULL;
    }
    func = NULL;
    if (_this->GL_GetProcAddress) {
        if (_this->gl_config.driver_loaded) {
            func = _this->GL_GetProcAddress(_this, proc);
        } else {
            SDL_SetError("No GL driver has been loaded");
        }
    } else {
        SDL_SetError("No dynamic GL support in current SDL video driver (%s)", _this->name);
    }
    return func;
}
References _this, NULL, SDL_SetError(), and SDL_UninitializedVideo().
Referenced by SDL_GL_ExtensionSupported(), and SDL_GL_GetAttribute().
SDL_GL_GetSwapInterval()
SDL_DECLSPEC bool SDLCALL SDL_GL_GetSwapInterval (int * interval) extern
Get the swap interval for the current OpenGL context.
If the system can't determine the swap interval, or there isn't a valid current context, this function will set *interval to 0 as a safe default.
Parameters
interval output interval value. 0 if there is no vertical retrace synchronization, 1 if the buffer swap is synchronized with the vertical retrace, and -1 if late swaps happen immediately instead of waiting for the next retrace.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_SetSwapInterval
{
    if (!interval) {
       return SDL_InvalidParamError("interval");
    }
    *interval = 0;
    if (!_this) {
        return SDL_SetError("no video driver");
    } else if (SDL_GL_GetCurrentContext() == NULL) {
        return SDL_SetError("no current context");
    } else if (_this->GL_GetSwapInterval) {
        return _this->GL_GetSwapInterval(_this, interval);
    } else {
        return SDL_SetError("not implemented");
    }
}
References _this, NULL, SDL_GL_GetCurrentContext(), SDL_InvalidParamError, and SDL_SetError().
SDL_GL_LoadLibrary()
SDL_DECLSPEC bool SDLCALL SDL_GL_LoadLibrary (const char * path) extern
Dynamically load an OpenGL library.
This should be done after initializing the video driver, but before creating any OpenGL windows. If no OpenGL library is loaded, the default library will be loaded upon creation of the first OpenGL window.
If you do this, you need to retrieve all of the GL functions used in your program from the dynamic library using SDL_GL_GetProcAddress().
Parameters
path the platform dependent OpenGL library name, or NULL to open the default OpenGL library.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetProcAddress
SDL_GL_UnloadLibrary
{
    bool result;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (_this->gl_config.driver_loaded) {
        if (path && SDL_strcmp(path, _this->gl_config.driver_path) != 0) {
            return SDL_SetError("OpenGL library already loaded");
        }
        result = true;
    } else {
        if (!_this->GL_LoadLibrary) {
            return SDL_DllNotSupported("OpenGL");
        }
        result = _this->GL_LoadLibrary(_this, path);
    }
    if (result) {
        ++_this->gl_config.driver_loaded;
    } else {
        if (_this->GL_UnloadLibrary) {
            _this->GL_UnloadLibrary(_this);
        }
    }
    return result;
}
References _this, SDL_DllNotSupported(), SDL_SetError(), SDL_strcmp(), and SDL_UninitializedVideo().
Referenced by SDL_CreateWindowWithProperties(), and SDL_RecreateWindow().
SDL_GL_MakeCurrent()
SDL_DECLSPEC bool SDLCALL SDL_GL_MakeCurrent (SDL_Window * window, SDL_GLContext context) extern
Set up an OpenGL context for rendering into an OpenGL window.
The context must have been created with a compatible window.
Parameters
window the window to associate with the context.
context the OpenGL context to associate with the window.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_CreateContext
{
    bool result;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    if (window == SDL_GL_GetCurrentWindow() &&
        context == SDL_GL_GetCurrentContext()) {
        // We're already current.
        return true;
    }
    if (!context) {
        window = NULL;
    } else if (window) {
        CHECK_WINDOW_MAGIC(window, false);
        if (!(window->flags & SDL_WINDOW_OPENGL)) {
            return SDL_SetError(NOT_AN_OPENGL_WINDOW);
        }
    } else if (!_this->gl_allow_no_surface) {
        return SDL_SetError("Use of OpenGL without a window is not supported on this platform");
    }
    result = _this->GL_MakeCurrent(_this, window, context);
    if (result) {
        _this->current_glwin = window;
        _this->current_glctx = context;
        SDL_SetTLS(&_this->current_glwin_tls, window, NULL);
        SDL_SetTLS(&_this->current_glctx_tls, context, NULL);
    }
    return result;
}
References _this, CHECK_WINDOW_MAGIC, context, NOT_AN_OPENGL_WINDOW, NULL, SDL_GL_GetCurrentContext(), SDL_GL_GetCurrentWindow(), SDL_SetError(), SDL_SetTLS(), SDL_UninitializedVideo(), and SDL_WINDOW_OPENGL.
Referenced by SDL_DestroyWindow(), and SDL_GL_DestroyContext().
SDL_GL_ResetAttributes()
SDL_DECLSPEC void SDLCALL SDL_GL_ResetAttributes (void) extern
Reset all previously set OpenGL context attributes to their default values.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetAttribute
SDL_GL_SetAttribute
{
    if (!_this) {
        return;
    }
    _this->egl_platformattrib_callback = NULL;
    _this->egl_surfaceattrib_callback = NULL;
    _this->egl_contextattrib_callback = NULL;
    _this->egl_attrib_callback_userdata = NULL;
    _this->gl_config.red_size = 8;
    _this->gl_config.green_size = 8;
    _this->gl_config.blue_size = 8;
    _this->gl_config.alpha_size = 8;
    _this->gl_config.buffer_size = 0;
    _this->gl_config.depth_size = 16;
    _this->gl_config.stencil_size = 0;
    _this->gl_config.double_buffer = 1;
    _this->gl_config.accum_red_size = 0;
    _this->gl_config.accum_green_size = 0;
    _this->gl_config.accum_blue_size = 0;
    _this->gl_config.accum_alpha_size = 0;
    _this->gl_config.stereo = 0;
    _this->gl_config.multisamplebuffers = 0;
    _this->gl_config.multisamplesamples = 0;
    _this->gl_config.floatbuffers = 0;
    _this->gl_config.retained_backing = 1;
    _this->gl_config.accelerated = -1; // accelerated or not, both are fine
#ifdef SDL_VIDEO_OPENGL
    _this->gl_config.major_version = 2;
    _this->gl_config.minor_version = 1;
    _this->gl_config.profile_mask = 0;
#elif defined(SDL_VIDEO_OPENGL_ES2)
    _this->gl_config.major_version = 2;
    _this->gl_config.minor_version = 0;
    _this->gl_config.profile_mask = SDL_GL_CONTEXT_PROFILE_ES;
#elif defined(SDL_VIDEO_OPENGL_ES)
    _this->gl_config.major_version = 1;
    _this->gl_config.minor_version = 1;
    _this->gl_config.profile_mask = SDL_GL_CONTEXT_PROFILE_ES;
#endif
    if (_this->GL_DefaultProfileConfig) {
        _this->GL_DefaultProfileConfig(_this, &_this->gl_config.profile_mask,
                                       &_this->gl_config.major_version,
                                       &_this->gl_config.minor_version);
    }
    _this->gl_config.flags = 0;
    _this->gl_config.framebuffer_srgb_capable = 0;
    _this->gl_config.no_error = 0;
    _this->gl_config.release_behavior = SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH;
    _this->gl_config.reset_notification = SDL_GL_CONTEXT_RESET_NO_NOTIFICATION;
    _this->gl_config.share_with_current_context = 0;
    _this->gl_config.egl_platform = 0;
}
References _this, NULL, SDL_GL_CONTEXT_PROFILE_ES, SDL_GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, and SDL_GL_CONTEXT_RESET_NO_NOTIFICATION.
Referenced by SDL_VideoInit().
SDL_GL_SetAttribute()
SDL_DECLSPEC bool SDLCALL SDL_GL_SetAttribute (SDL_GLAttr attr, int value) extern
Set an OpenGL window attribute before window creation.
This function sets the OpenGL attribute attr to value. The requested attributes should be set before creating an OpenGL window. You should use SDL_GL_GetAttribute() to check the values after creating the OpenGL context, since the values obtained can differ from the requested ones.
Parameters
attr an SDL_GLAttr enum value specifying the OpenGL attribute to set.
value the desired value for the attribute.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetAttribute
SDL_GL_ResetAttributes
{
#if defined(SDL_VIDEO_OPENGL) || defined(SDL_VIDEO_OPENGL_ES) || defined(SDL_VIDEO_OPENGL_ES2)
    bool result;
    if (!_this) {
        return SDL_UninitializedVideo();
    }
    result = true;
    switch (attr) {
    case SDL_GL_RED_SIZE:
        _this->gl_config.red_size = value;
        break;
    case SDL_GL_GREEN_SIZE:
        _this->gl_config.green_size = value;
        break;
    case SDL_GL_BLUE_SIZE:
        _this->gl_config.blue_size = value;
        break;
    case SDL_GL_ALPHA_SIZE:
        _this->gl_config.alpha_size = value;
        break;
    case SDL_GL_DOUBLEBUFFER:
        _this->gl_config.double_buffer = value;
        break;
    case SDL_GL_BUFFER_SIZE:
        _this->gl_config.buffer_size = value;
        break;
    case SDL_GL_DEPTH_SIZE:
        _this->gl_config.depth_size = value;
        break;
    case SDL_GL_STENCIL_SIZE:
        _this->gl_config.stencil_size = value;
        break;
    case SDL_GL_ACCUM_RED_SIZE:
        _this->gl_config.accum_red_size = value;
        break;
    case SDL_GL_ACCUM_GREEN_SIZE:
        _this->gl_config.accum_green_size = value;
        break;
    case SDL_GL_ACCUM_BLUE_SIZE:
        _this->gl_config.accum_blue_size = value;
        break;
    case SDL_GL_ACCUM_ALPHA_SIZE:
        _this->gl_config.accum_alpha_size = value;
        break;
    case SDL_GL_STEREO:
        _this->gl_config.stereo = value;
        break;
    case SDL_GL_MULTISAMPLEBUFFERS:
        _this->gl_config.multisamplebuffers = value;
        break;
    case SDL_GL_MULTISAMPLESAMPLES:
        _this->gl_config.multisamplesamples = value;
        break;
    case SDL_GL_FLOATBUFFERS:
        _this->gl_config.floatbuffers = value;
        break;
    case SDL_GL_ACCELERATED_VISUAL:
        _this->gl_config.accelerated = value;
        break;
    case SDL_GL_RETAINED_BACKING:
        _this->gl_config.retained_backing = value;
        break;
    case SDL_GL_CONTEXT_MAJOR_VERSION:
        _this->gl_config.major_version = value;
        break;
    case SDL_GL_CONTEXT_MINOR_VERSION:
        _this->gl_config.minor_version = value;
        break;
    case SDL_GL_CONTEXT_FLAGS:
        if (value & ~(SDL_GL_CONTEXT_DEBUG_FLAG |
                      SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG |
                      SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG |
                      SDL_GL_CONTEXT_RESET_ISOLATION_FLAG)) {
            result = SDL_SetError("Unknown OpenGL context flag %d", value);
            break;
        }
        _this->gl_config.flags = value;
        break;
    case SDL_GL_CONTEXT_PROFILE_MASK:
        if (value != 0 &&
            value != SDL_GL_CONTEXT_PROFILE_CORE &&
            value != SDL_GL_CONTEXT_PROFILE_COMPATIBILITY &&
            value != SDL_GL_CONTEXT_PROFILE_ES) {
            result = SDL_SetError("Unknown OpenGL context profile %d", value);
            break;
        }
        _this->gl_config.profile_mask = value;
        break;
    case SDL_GL_SHARE_WITH_CURRENT_CONTEXT:
        _this->gl_config.share_with_current_context = value;
        break;
    case SDL_GL_FRAMEBUFFER_SRGB_CAPABLE:
        _this->gl_config.framebuffer_srgb_capable = value;
        break;
    case SDL_GL_CONTEXT_RELEASE_BEHAVIOR:
        _this->gl_config.release_behavior = value;
        break;
    case SDL_GL_CONTEXT_RESET_NOTIFICATION:
        _this->gl_config.reset_notification = value;
        break;
    case SDL_GL_CONTEXT_NO_ERROR:
        _this->gl_config.no_error = value;
        break;
    case SDL_GL_EGL_PLATFORM:
        _this->gl_config.egl_platform = value;
        break;
    default:
        result = SDL_SetError("Unknown OpenGL attribute");
        break;
    }
    return result;
#else
    return SDL_Unsupported();
#endif // SDL_VIDEO_OPENGL
}
References _this, SDL_GL_ACCELERATED_VISUAL, SDL_GL_ACCUM_ALPHA_SIZE, SDL_GL_ACCUM_BLUE_SIZE, SDL_GL_ACCUM_GREEN_SIZE, SDL_GL_ACCUM_RED_SIZE, SDL_GL_ALPHA_SIZE, SDL_GL_BLUE_SIZE, SDL_GL_BUFFER_SIZE, SDL_GL_CONTEXT_DEBUG_FLAG, SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG, SDL_GL_CONTEXT_MAJOR_VERSION, SDL_GL_CONTEXT_MINOR_VERSION, SDL_GL_CONTEXT_NO_ERROR, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY, SDL_GL_CONTEXT_PROFILE_CORE, SDL_GL_CONTEXT_PROFILE_ES, SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_RELEASE_BEHAVIOR, SDL_GL_CONTEXT_RESET_ISOLATION_FLAG, SDL_GL_CONTEXT_RESET_NOTIFICATION, SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG, SDL_GL_DEPTH_SIZE, SDL_GL_DOUBLEBUFFER, SDL_GL_EGL_PLATFORM, SDL_GL_FLOATBUFFERS, SDL_GL_FRAMEBUFFER_SRGB_CAPABLE, SDL_GL_GREEN_SIZE, SDL_GL_MULTISAMPLEBUFFERS, SDL_GL_MULTISAMPLESAMPLES, SDL_GL_RED_SIZE, SDL_GL_RETAINED_BACKING, SDL_GL_SHARE_WITH_CURRENT_CONTEXT, SDL_GL_STENCIL_SIZE, SDL_GL_STEREO, SDL_SetError(), SDL_UninitializedVideo(), and SDL_Unsupported.
SDL_GL_SetSwapInterval()
SDL_DECLSPEC bool SDLCALL SDL_GL_SetSwapInterval (int interval) extern
Set the swap interval for the current OpenGL context.
Some systems allow specifying -1 for the interval, to enable adaptive vsync. Adaptive vsync works the same as vsync, but if you've already missed the vertical retrace for a given frame, it swaps buffers immediately, which might be less jarring for the user during occasional framerate drops. If an application requests adaptive vsync and the system does not support it, this function will fail and return false. In such a case, you should probably retry the call with 1 for the interval.
Adaptive vsync is implemented for some glX drivers with GLX_EXT_swap_control_tear, and for some Windows drivers with WGL_EXT_swap_control_tear.
Read more on the Khronos wiki: https://www.khronos.org/opengl/wiki/Swap_Interval#Adaptive_Vsync
Parameters
interval 0 for immediate updates, 1 for updates synchronized with the vertical retrace, -1 for adaptive vsync.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_GetSwapInterval
{
    if (!_this) {
        return SDL_UninitializedVideo();
    } else if (SDL_GL_GetCurrentContext() == NULL) {
        return SDL_SetError("No OpenGL context has been made current");
    } else if (_this->GL_SetSwapInterval) {
        return _this->GL_SetSwapInterval(_this, interval);
    } else {
        return SDL_SetError("Setting the swap interval is not supported");
    }
}
References _this, NULL, SDL_GL_GetCurrentContext(), SDL_SetError(), and SDL_UninitializedVideo().
SDL_GL_SwapWindow()
SDL_DECLSPEC bool SDLCALL SDL_GL_SwapWindow (SDL_Window * window) extern
Update a window with OpenGL rendering.
This is used with double-buffered OpenGL contexts, which are the default.
On macOS, make sure you bind 0 to the draw framebuffer before swapping the window, otherwise nothing will happen. If you aren't using glBindFramebuffer(), this is the default and you won't have to do anything extra.
Parameters
window the window to change.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!(window->flags & SDL_WINDOW_OPENGL)) {
        return SDL_SetError(NOT_AN_OPENGL_WINDOW);
    }
    if (SDL_GL_GetCurrentWindow() != window) {
        return SDL_SetError("The specified window has not been made current");
    }
    return _this->GL_SwapWindow(_this, window);
}
References _this, CHECK_WINDOW_MAGIC, NOT_AN_OPENGL_WINDOW, SDL_GL_GetCurrentWindow(), SDL_SetError(), and SDL_WINDOW_OPENGL.
SDL_GL_UnloadLibrary()
SDL_DECLSPEC void SDLCALL SDL_GL_UnloadLibrary (void) extern
Unload the OpenGL library previously loaded by SDL_GL_LoadLibrary().
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GL_LoadLibrary
{
    if (!_this) {
        SDL_UninitializedVideo();
        return;
    }
    if (_this->gl_config.driver_loaded > 0) {
        if (--_this->gl_config.driver_loaded > 0) {
            return;
        }
        if (_this->GL_UnloadLibrary) {
            _this->GL_UnloadLibrary(_this);
        }
    }
}
References _this, and SDL_UninitializedVideo().
Referenced by SDL_DestroyWindow(), SDL_Metal_CreateView(), and SDL_RecreateWindow().
SDL_HideWindow()
SDL_DECLSPEC bool SDLCALL SDL_HideWindow (SDL_Window * window) extern
Hide a window.
Parameters
window the window to hide.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShowWindow
SDL_WINDOW_HIDDEN
{
    SDL_Window *child;
    CHECK_WINDOW_MAGIC(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->restore_on_show = false;
        return true;
    }
    // Hide all child windows
    for (child = window->first_child; child; child = child->next_sibling) {
        if (child->flags & SDL_WINDOW_HIDDEN) {
            break;
        }
        SDL_HideWindow(child);
        child->restore_on_show = true;
    }
    // Store the flags for restoration later.
    const SDL_WindowFlags pending_mask = (SDL_WINDOW_MAXIMIZED | SDL_WINDOW_MINIMIZED | SDL_WINDOW_FULLSCREEN | SDL_WINDOW_KEYBOARD_GRABBED | SDL_WINDOW_MOUSE_GRABBED);
    window->pending_flags = (window->flags & pending_mask);
    window->is_hiding = true;
    if (_this->HideWindow) {
        _this->HideWindow(_this, window);
    } else {
        SDL_SetMouseFocus(NULL);
        SDL_SetKeyboardFocus(NULL);
    }
    window->is_hiding = false;
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_HIDDEN, 0, 0);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_Window::flags, SDL_Window::next_sibling, NULL, SDL_Window::restore_on_show, SDL_EVENT_WINDOW_HIDDEN, SDL_HideWindow(), SDL_SendWindowEvent(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, SDL_WINDOW_KEYBOARD_GRABBED, SDL_WINDOW_MAXIMIZED, SDL_WINDOW_MINIMIZED, and SDL_WINDOW_MOUSE_GRABBED.
Referenced by SDL_DestroyWindow(), SDL_HideWindow(), and SDL_RecreateWindow().
SDL_MaximizeWindow()
SDL_DECLSPEC bool SDLCALL SDL_MaximizeWindow (SDL_Window * window) extern
Request that the window be made as large as possible.
Non-resizable windows can't be maximized. The window must have the SDL_WINDOW_RESIZABLE flag set, or this will have no effect.
On some windowing systems this request is asynchronous and the new window state may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_MAXIMIZED event will be emitted. Note that, as this is just a request, the windowing system can deny the state change.
When maximizing a window, whether the constraints set via SDL_SetWindowMaximumSize() are honored depends on the policy of the window manager. Win32 and macOS enforce the constraints when maximizing, while X11 and Wayland window managers may vary.
Parameters
window the window to maximize.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MinimizeWindow
SDL_RestoreWindow
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->MaximizeWindow) {
        return SDL_Unsupported();
    }
    if (!(window->flags & SDL_WINDOW_RESIZABLE)) {
        return SDL_SetError("A window without the 'SDL_WINDOW_RESIZABLE' flag can't be maximized");
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->pending_flags |= SDL_WINDOW_MAXIMIZED;
        return true;
    }
    _this->MaximizeWindow(_this, window);
    SDL_SyncIfRequired(window);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SetError(), SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOW_HIDDEN, SDL_WINDOW_MAXIMIZED, and SDL_WINDOW_RESIZABLE.
Referenced by ApplyWindowFlags().
SDL_MinimizeWindow()
SDL_DECLSPEC bool SDLCALL SDL_MinimizeWindow (SDL_Window * window) extern
Request that the window be minimized to an iconic representation.
If the window is in a fullscreen state, this request has no direct effect. It may alter the state the window is returned to when leaving fullscreen.
On some windowing systems this request is asynchronous and the new window state may not have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_MINIMIZED event will be emitted. Note that, as this is just a request, the windowing system can deny the state change.
Parameters
window the window to minimize.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MaximizeWindow
SDL_RestoreWindow
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->MinimizeWindow) {
        return SDL_Unsupported();
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->pending_flags |= SDL_WINDOW_MINIMIZED;
        return true;
    }
    _this->MinimizeWindow(_this, window);
    SDL_SyncIfRequired(window);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOW_HIDDEN, and SDL_WINDOW_MINIMIZED.
Referenced by ApplyWindowFlags(), SDL_CheckWindowDisplayChanged(), SDL_OnWindowFocusLost(), SDL_PromptAssertion(), SDL_SendKeyboardKeyInternal(), and SDL_UpdateFullscreenMode().
SDL_RaiseWindow()
SDL_DECLSPEC bool SDLCALL SDL_RaiseWindow (SDL_Window * window) extern
Request that a window be raised above other windows and gain the input focus.
The result of this request is subject to desktop window manager policy, particularly if raising the requested window would result in stealing focus from another application. If the window is successfully raised and gains input focus, an SDL_EVENT_WINDOW_FOCUS_GAINED event will be emitted, and the window will have the SDL_WINDOW_INPUT_FOCUS flag set.
Parameters
window the window to raise.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        return true;
    }
    if (_this->RaiseWindow) {
        _this->RaiseWindow(_this, window);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_HIDDEN.
Referenced by SDL_ShowMessageBox().
SDL_RestoreWindow()
SDL_DECLSPEC bool SDLCALL SDL_RestoreWindow (SDL_Window * window) extern
Request that the size and position of a minimized or maximized window be restored.
If the window is in a fullscreen state, this request has no direct effect. It may alter the state the window is returned to when leaving fullscreen.
On some windowing systems this request is asynchronous and the new window state may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_RESTORED event will be emitted. Note that, as this is just a request, the windowing system can deny the state change.
Parameters
window the window to restore.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_MaximizeWindow
SDL_MinimizeWindow
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->RestoreWindow) {
        return SDL_Unsupported();
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        window->pending_flags &= ~(SDL_WINDOW_MAXIMIZED | SDL_WINDOW_MINIMIZED);
        return true;
    }
    _this->RestoreWindow(_this, window);
    SDL_SyncIfRequired(window);
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOW_HIDDEN, SDL_WINDOW_MAXIMIZED, and SDL_WINDOW_MINIMIZED.
Referenced by ApplyWindowFlags(), and SDL_PromptAssertion().
SDL_ScreenSaverEnabled()
SDL_DECLSPEC bool SDLCALL SDL_ScreenSaverEnabled (void) extern
Check whether the screensaver is currently enabled.
The screensaver is disabled by default.
The default can also be changed using SDL_HINT_VIDEO_ALLOW_SCREENSAVER.
Returns
true if the screensaver is enabled, false if it is disabled.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DisableScreenSaver
SDL_EnableScreenSaver
{
    if (!_this) {
        return true;
    }
    return !_this->suspend_screensaver;
}
References _this.
SDL_SetWindowAlwaysOnTop()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowAlwaysOnTop (SDL_Window * window, bool on_top) extern
Set the window to always be above the others.
This will add or remove the window's SDL_WINDOW_ALWAYS_ON_TOP flag. This will bring the window to the front and keep the window above the rest.
Parameters
window the window of which to change the always on top state.
on_top true to set the window always on top, false to disable.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFlags
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    const bool want = (on_top != false); // normalize the flag.
    const bool have = ((window->flags & SDL_WINDOW_ALWAYS_ON_TOP) != 0);
    if ((want != have) && (_this->SetWindowAlwaysOnTop)) {
        if (want) {
            window->flags |= SDL_WINDOW_ALWAYS_ON_TOP;
        } else {
            window->flags &= ~SDL_WINDOW_ALWAYS_ON_TOP;
        }
        _this->SetWindowAlwaysOnTop(_this, window, want);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_WINDOW_ALWAYS_ON_TOP.
SDL_SetWindowAspectRatio()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowAspectRatio (SDL_Window * window, float min_aspect, float max_aspect) extern
Request that the aspect ratio of a window's client area be set.
The aspect ratio is the ratio of width divided by height, e.g. 2560x1600 would be 1.6. Larger aspect ratios are wider and smaller aspect ratios are narrower.
If, at the time of this request, the window in a fixed-size state, such as maximized or fullscreen, the request will be deferred until the window exits this state and becomes resizable again.
On some windowing systems, this request is asynchronous and the new window aspect ratio may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window size changes, an SDL_EVENT_WINDOW_RESIZED event will be emitted with the new window dimensions. Note that the new dimensions may not match the exact aspect ratio requested, as some windowing systems can restrict the window size in certain scenarios (e.g. constraining the size of the content area to remain within the usable desktop bounds). Additionally, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to change.
min_aspect the minimum aspect ratio of the window, or 0.0f for no limit.
max_aspect the maximum aspect ratio of the window, or 0.0f for no limit.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowAspectRatio
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    window->min_aspect = min_aspect;
    window->max_aspect = max_aspect;
    if (_this->SetWindowAspectRatio) {
        _this->SetWindowAspectRatio(_this, window);
    }
    return SDL_SetWindowSize(window, window->floating.w, window->floating.h);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_SetWindowSize().
SDL_SetWindowBordered()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowBordered (SDL_Window * window, bool bordered) extern
Set the border state of a window.
This will add or remove the window's SDL_WINDOW_BORDERLESS flag and add or remove the border from the actual window. This is a no-op if the window's border already matches the requested state.
You can't change the border state of a fullscreen window.
Parameters
window the window of which to change the border state.
bordered false to remove border, true to add border.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFlags
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    const bool want = (bordered != false); // normalize the flag.
    const bool have = !(window->flags & SDL_WINDOW_BORDERLESS);
    if ((want != have) && (_this->SetWindowBordered)) {
        if (want) {
            window->flags &= ~SDL_WINDOW_BORDERLESS;
        } else {
            window->flags |= SDL_WINDOW_BORDERLESS;
        }
        _this->SetWindowBordered(_this, window, want);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_WINDOW_BORDERLESS.
SDL_SetWindowFocusable()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowFocusable (SDL_Window * window, bool focusable) extern
Set whether the window may have input focus.
Parameters
window the window to set focusable state.
focusable true to allow input focus, false to not allow input focus.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    const bool want = (focusable != false); // normalize the flag.
    const bool have = !(window->flags & SDL_WINDOW_NOT_FOCUSABLE);
    if ((want != have) && (_this->SetWindowFocusable)) {
        if (want) {
            window->flags &= ~SDL_WINDOW_NOT_FOCUSABLE;
        } else {
            window->flags |= SDL_WINDOW_NOT_FOCUSABLE;
        }
        if (!_this->SetWindowFocusable(_this, window, want)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, and SDL_WINDOW_NOT_FOCUSABLE.
SDL_SetWindowFullscreen()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowFullscreen (SDL_Window * window, bool fullscreen) extern
Request that the window's fullscreen state be changed.
By default a window in fullscreen state uses borderless fullscreen desktop mode, but a specific exclusive display mode can be set using SDL_SetWindowFullscreenMode().
On some windowing systems this request is asynchronous and the new fullscreen state may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window state changes, an SDL_EVENT_WINDOW_ENTER_FULLSCREEN or SDL_EVENT_WINDOW_LEAVE_FULLSCREEN event will be emitted. Note that, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to change.
fullscreen true for fullscreen mode, false for windowed mode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFullscreenMode
SDL_SetWindowFullscreenMode
SDL_SyncWindow
SDL_WINDOW_FULLSCREEN
{
    bool result;
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        if (fullscreen) {
            window->pending_flags |= SDL_WINDOW_FULLSCREEN;
        } else {
            window->pending_flags &= ~SDL_WINDOW_FULLSCREEN;
        }
        return true;
    }
    if (fullscreen) {
        // Set the current fullscreen mode to the desired mode
        SDL_copyp(&window->current_fullscreen_mode, &window->requested_fullscreen_mode);
    }
    result = SDL_UpdateFullscreenMode(window, fullscreen ? SDL_FULLSCREEN_OP_ENTER : SDL_FULLSCREEN_OP_LEAVE, true);
    if (!fullscreen || !result) {
        // Clear the current fullscreen mode.
        SDL_zero(window->current_fullscreen_mode);
    }
    if (result) {
        SDL_SyncIfRequired(window);
    }
    return result;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_copyp, SDL_FULLSCREEN_OP_ENTER, SDL_FULLSCREEN_OP_LEAVE, SDL_SyncIfRequired(), SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN, SDL_WINDOW_HIDDEN, and SDL_zero.
Referenced by ApplyWindowFlags().
SDL_SetWindowFullscreenMode()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowFullscreenMode (SDL_Window * window, const SDL_DisplayMode * mode) extern
Set the display mode to use when a window is visible and fullscreen.
This only affects the display mode used when the window is fullscreen. To change the window size when the window is not fullscreen, use SDL_SetWindowSize().
If the window is currently in the fullscreen state, this request is asynchronous on some windowing systems and the new mode dimensions may not be applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the new mode takes effect, an SDL_EVENT_WINDOW_RESIZED and/or an SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED event will be emitted with the new mode dimensions.
Parameters
window the window to affect.
mode a pointer to the display mode to use, which can be NULL for borderless fullscreen desktop mode, or one of the fullscreen modes returned by SDL_GetFullscreenDisplayModes() to set an exclusive fullscreen mode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFullscreenMode
SDL_SetWindowFullscreen
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (mode) {
        if (!SDL_GetFullscreenModeMatch(mode)) {
            return SDL_SetError("Invalid fullscreen display mode");
        }
        // Save the mode so we can look up the closest match later
        SDL_copyp(&window->requested_fullscreen_mode, mode);
    } else {
        SDL_zero(window->requested_fullscreen_mode);
    }
    /* Copy to the current mode now, in case an asynchronous fullscreen window request
     * is in progress. It will be overwritten if a new request is made.
     */
    SDL_copyp(&window->current_fullscreen_mode, &window->requested_fullscreen_mode);
    if (SDL_WINDOW_FULLSCREEN_VISIBLE(window)) {
        SDL_UpdateFullscreenMode(window, SDL_FULLSCREEN_OP_UPDATE, true);
        SDL_SyncIfRequired(window);
    }
    return true;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_copyp, SDL_FULLSCREEN_OP_UPDATE, SDL_GetFullscreenModeMatch(), SDL_SetError(), SDL_SyncIfRequired(), SDL_UpdateFullscreenMode(), SDL_WINDOW_FULLSCREEN_VISIBLE, and SDL_zero.
SDL_SetWindowHitTest()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowHitTest (SDL_Window * window, SDL_HitTest callback, void * callback_data) extern
Provide a callback that decides if a window region has special properties.
Normally windows are dragged and resized by decorations provided by the system window manager (a title bar, borders, etc), but for some apps, it makes sense to drag them from somewhere else inside the window itself; for example, one might have a borderless window that wants to be draggable from any part, or simulate its own title bar, etc.
This function lets the app provide a callback that designates pieces of a given window as special. This callback is run during event processing if we need to tell the OS to treat a region of the window specially; the use of this callback is known as "hit testing."
Mouse input may not be delivered to your application if it is within a special area; the OS will often apply that input to moving the window or resizing the window and not deliver it to the application.
Specifying NULL for a callback disables hit-testing. Hit-testing is disabled by default.
Platforms that don't support this functionality will return false unconditionally, even if you're attempting to disable hit-testing.
Your callback may fire at any time, and its firing does not indicate any specific behavior (for example, on Windows, this certainly might fire when the OS is deciding whether to drag your window, but it fires for lots of other reasons, too, some unrelated to anything you probably care about and when the mouse isn't actually at the location it is testing). Since this can fire at any time, you should try to keep your callback efficient, devoid of allocations, etc.
Parameters
window the window to set hit-testing on.
callback the function to call when doing a hit-test.
callback_data an app-defined void pointer passed to callback.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->SetWindowHitTest) {
        return SDL_Unsupported();
    }
    window->hit_test = callback;
    window->hit_test_data = callback_data;
    return _this->SetWindowHitTest(window, callback != NULL);
}
References _this, CHECK_WINDOW_MAGIC, NULL, and SDL_Unsupported.
SDL_SetWindowIcon()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowIcon (SDL_Window * window, SDL_Surface * icon) extern
Set the icon for a window.
If this function is passed a surface with alternate representations added using SDL_AddSurfaceAlternateImage(), the surface will be interpreted as the content to be used for 100% display scale, and the alternate representations will be used for high DPI situations. For example, if the original surface is 32x32, then on a 2x macOS display or 200% display scale on Windows, a 64x64 version of the image will be used, if available. If a matching version of the image isn't available, the closest larger size image will be downscaled to the appropriate size and be used instead, if available. Otherwise, the closest smaller image will be upscaled and be used instead.
Parameters
window the window to change.
icon an SDL_Surface structure containing the icon for the window.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_AddSurfaceAlternateImage
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!icon) {
        return SDL_InvalidParamError("icon");
    }
    SDL_DestroySurface(window->icon);
    // Convert the icon into ARGB8888
    window->icon = SDL_ConvertSurface(icon, SDL_PIXELFORMAT_ARGB8888);
    if (!window->icon) {
        return false;
    }
    if (!_this->SetWindowIcon) {
        return SDL_Unsupported();
    }
    return _this->SetWindowIcon(_this, window, window->icon);
}
References _this, CHECK_WINDOW_MAGIC, SDL_ConvertSurface(), SDL_DestroySurface(), SDL_InvalidParamError, SDL_PIXELFORMAT_ARGB8888, and SDL_Unsupported.
SDL_SetWindowKeyboardGrab()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowKeyboardGrab (SDL_Window * window, bool grabbed) extern
Set a window's keyboard grab mode.
Keyboard grab enables capture of system keyboard shortcuts like Alt+Tab or the Meta/Super key. Note that not all system keyboard shortcuts can be captured by applications (one example is Ctrl+Alt+Del on Windows).
This is primarily intended for specialized applications such as VNC clients or VM frontends. Normal games should not use keyboard grab.
When keyboard grab is enabled, SDL will continue to handle Alt+Tab when the window is full-screen to ensure the user is not trapped in your application. If you have a custom keyboard shortcut to exit fullscreen mode, you may suppress this behavior with SDL_HINT_ALLOW_ALT_TAB_WHILE_GRABBED.
If the caller enables a grab while another window is currently grabbed, the other window loses its grab in favor of the caller's window.
Parameters
window the window for which the keyboard grab mode should be set.
grabbed this is true to grab keyboard, and false to release.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowKeyboardGrab
SDL_SetWindowMouseGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        if (grabbed) {
            window->pending_flags |= SDL_WINDOW_KEYBOARD_GRABBED;
        } else {
            window->pending_flags &= ~SDL_WINDOW_KEYBOARD_GRABBED;
        }
        return true;
    }
    if (!!grabbed == !!(window->flags & SDL_WINDOW_KEYBOARD_GRABBED)) {
        return true;
    }
    if (grabbed) {
        window->flags |= SDL_WINDOW_KEYBOARD_GRABBED;
    } else {
        window->flags &= ~SDL_WINDOW_KEYBOARD_GRABBED;
    }
    SDL_UpdateWindowGrab(window);
    if (grabbed && !(window->flags & SDL_WINDOW_KEYBOARD_GRABBED)) {
        return false;
    }
    return true;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_UpdateWindowGrab(), SDL_WINDOW_HIDDEN, and SDL_WINDOW_KEYBOARD_GRABBED.
Referenced by ApplyWindowFlags().
SDL_SetWindowMaximumSize()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMaximumSize (SDL_Window * window, int max_w, int max_h) extern
Set the maximum size of a window's client area.
Parameters
window the window to change.
max_w the maximum width of the window, or 0 for no limit.
max_h the maximum height of the window, or 0 for no limit.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMaximumSize
SDL_SetWindowMinimumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (max_w < 0) {
        return SDL_InvalidParamError("max_w");
    }
    if (max_h < 0) {
        return SDL_InvalidParamError("max_h");
    }
    if ((max_w && max_w < window->min_w) ||
        (max_h && max_h < window->min_h)) {
        return SDL_SetError("SDL_SetWindowMaximumSize(): Tried to set maximum size smaller than minimum size");
    }
    window->max_w = max_w;
    window->max_h = max_h;
    if (_this->SetWindowMaximumSize) {
        _this->SetWindowMaximumSize(_this, window);
    }
    // Ensure that window is not larger than maximal size
    int w = window->last_size_pending ? window->pending.w : window->floating.w;
    int h = window->last_size_pending ? window->pending.h : window->floating.h;
    w = window->max_w ? SDL_min(w, window->max_w) : w;
    h = window->max_h ? SDL_min(h, window->max_h) : h;
    return SDL_SetWindowSize(window, w, h);
}
References _this, CHECK_WINDOW_MAGIC, SDL_InvalidParamError, SDL_min, SDL_SetError(), and SDL_SetWindowSize().
SDL_SetWindowMinimumSize()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMinimumSize (SDL_Window * window, int min_w, int min_h) extern
Set the minimum size of a window's client area.
Parameters
window the window to change.
min_w the minimum width of the window, or 0 for no limit.
min_h the minimum height of the window, or 0 for no limit.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMinimumSize
SDL_SetWindowMaximumSize
{
    CHECK_WINDOW_MAGIC(window, false);
    if (min_w < 0) {
        return SDL_InvalidParamError("min_w");
    }
    if (min_h < 0) {
        return SDL_InvalidParamError("min_h");
    }
    if ((window->max_w && min_w > window->max_w) ||
        (window->max_h && min_h > window->max_h)) {
        return SDL_SetError("SDL_SetWindowMinimumSize(): Tried to set minimum size larger than maximum size");
    }
    window->min_w = min_w;
    window->min_h = min_h;
    if (_this->SetWindowMinimumSize) {
        _this->SetWindowMinimumSize(_this, window);
    }
    // Ensure that window is not smaller than minimal size
    int w = window->last_size_pending ? window->pending.w : window->floating.w;
    int h = window->last_size_pending ? window->pending.h : window->floating.h;
    w = window->min_w ? SDL_max(w, window->min_w) : w;
    h = window->min_h ? SDL_max(h, window->min_h) : h;
    return SDL_SetWindowSize(window, w, h);
}
References _this, CHECK_WINDOW_MAGIC, SDL_InvalidParamError, SDL_max, SDL_SetError(), and SDL_SetWindowSize().
SDL_SetWindowModal()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowModal (SDL_Window * window, bool modal) extern
Toggle the state of the window as modal.
To enable modal status on a window, the window must currently be the child window of a parent, or toggling modal status on will fail.
Parameters
window the window on which to set the modal state.
modal true to toggle modal status on, false to toggle it off.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowParent
SDL_WINDOW_MODAL
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (!_this->SetWindowModal) {
        return SDL_Unsupported();
    }
    if (modal) {
        if (!window->parent) {
            return SDL_SetError("Window must have a parent to enable the modal state; use SDL_SetWindowParent() to set the parent first.");
        }
        window->flags |= SDL_WINDOW_MODAL;
    } else if (window->flags & SDL_WINDOW_MODAL) {
        window->flags &= ~SDL_WINDOW_MODAL;
    } else {
        return true; // Already not modal, so nothing to do.
    }
    if (window->flags & SDL_WINDOW_HIDDEN) {
        return true;
    }
    return _this->SetWindowModal(_this, window, modal);
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_SetError(), SDL_Unsupported, SDL_WINDOW_HIDDEN, and SDL_WINDOW_MODAL.
Referenced by ApplyWindowFlags(), and SDL_RecreateWindow().
SDL_SetWindowMouseGrab()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMouseGrab (SDL_Window * window, bool grabbed) extern
Set a window's mouse grab mode.
Mouse grab confines the mouse cursor to the window.
Parameters
window the window for which the mouse grab mode should be set.
grabbed this is true to grab mouse, and false to release.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMouseRect
SDL_SetWindowMouseRect
SDL_SetWindowKeyboardGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (window->flags & SDL_WINDOW_HIDDEN) {
        if (grabbed) {
            window->pending_flags |= SDL_WINDOW_MOUSE_GRABBED;
        } else {
            window->pending_flags &= ~SDL_WINDOW_MOUSE_GRABBED;
        }
        return true;
    }
    if (!!grabbed == !!(window->flags & SDL_WINDOW_MOUSE_GRABBED)) {
        return true;
    }
    if (grabbed) {
        window->flags |= SDL_WINDOW_MOUSE_GRABBED;
    } else {
        window->flags &= ~SDL_WINDOW_MOUSE_GRABBED;
    }
    SDL_UpdateWindowGrab(window);
    if (grabbed && !(window->flags & SDL_WINDOW_MOUSE_GRABBED)) {
        return false;
    }
    return true;
}
References CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_UpdateWindowGrab(), SDL_WINDOW_HIDDEN, and SDL_WINDOW_MOUSE_GRABBED.
Referenced by ApplyWindowFlags().
SDL_SetWindowMouseRect()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowMouseRect (SDL_Window * window, const SDL_Rect * rect) extern
Confines the cursor to the specified area of a window.
Note that this does NOT grab the cursor, it only defines the area a cursor is restricted to when the window has mouse focus.
Parameters
window the window that will be associated with the barrier.
rect a rectangle area in window-relative coordinates. If NULL the barrier for the specified window will be destroyed.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowMouseRect
SDL_GetWindowMouseGrab
SDL_SetWindowMouseGrab
{
    CHECK_WINDOW_MAGIC(window, false);
    if (rect) {
        SDL_memcpy(&window->mouse_rect, rect, sizeof(*rect));
    } else {
        SDL_zero(window->mouse_rect);
    }
    if (_this->SetWindowMouseRect) {
        return _this->SetWindowMouseRect(_this, window);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_memcpy, and SDL_zero.
SDL_SetWindowOpacity()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowOpacity (SDL_Window * window, float opacity) extern
Set the opacity for a window.
The parameter opacity will be clamped internally between 0.0f (transparent) and 1.0f (opaque).
This function also returns false if setting the opacity isn't supported.
Parameters
window the window which will be made transparent or opaque.
opacity the opacity value (0.0f - transparent, 1.0f - opaque).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowOpacity
{
    bool result;
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->SetWindowOpacity) {
        return SDL_Unsupported();
    }
    if (opacity < 0.0f) {
        opacity = 0.0f;
    } else if (opacity > 1.0f) {
        opacity = 1.0f;
    }
    result = _this->SetWindowOpacity(_this, window, opacity);
    if (result) {
        window->opacity = opacity;
    }
    return result;
}
References _this, CHECK_WINDOW_MAGIC, and SDL_Unsupported.
SDL_SetWindowParent()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowParent (SDL_Window * window, SDL_Window * parent) extern
Set the window as a child of a parent window.
If the window is already the child of an existing window, it will be reparented to the new owner. Setting the parent window to NULL unparents the window and removes child window status.
If a parent window is hidden or destroyed, the operation will be recursively applied to child windows. Child windows hidden with the parent that did not have their hidden status explicitly set will be restored when the parent is shown.
Attempting to set the parent of a window that is currently in the modal state will fail. Use SDL_SetWindowModal() to cancel the modal status before attempting to change the parent.
Popup windows cannot change parents and attempts to do so will fail.
Setting a parent window that is currently the sibling or descendent of the child window results in undefined behavior.
Parameters
window the window that should become the child of a parent.
parent the new parent window for the child window.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowModal
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (parent) {
        CHECK_WINDOW_MAGIC(parent, false);
        CHECK_WINDOW_NOT_POPUP(parent, false);
    }
    if (window == parent) {
        return SDL_SetError("Cannot set the parent of a window to itself.");
    }
    if (!_this->SetWindowParent) {
        return SDL_Unsupported();
    }
    if (window->flags & SDL_WINDOW_MODAL) {
        return SDL_SetError("Modal windows cannot change parents; call SDL_SetWindowModal() to clear modal status first.");
    }
    if (window->parent == parent) {
        return true;
    }
    const bool ret = _this->SetWindowParent(_this, window, parent);
    SDL_UpdateWindowHierarchy(window, ret ? parent : NULL);
    return ret;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, NULL, SDL_SetError(), SDL_Unsupported, SDL_UpdateWindowHierarchy(), and SDL_WINDOW_MODAL.
SDL_SetWindowPosition()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowPosition (SDL_Window * window, int x, int y) extern
Request that the window's position be set.
If the window is in an exclusive fullscreen or maximized state, this request has no effect.
This can be used to reposition fullscreen-desktop windows onto a different display, however, as exclusive fullscreen windows are locked to a specific display, they can only be repositioned programmatically via SDL_SetWindowFullscreenMode().
On some windowing systems this request is asynchronous and the new coordinates may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window position changes, an SDL_EVENT_WINDOW_MOVED event will be emitted with the window's new coordinates. Note that the new coordinates may not match the exact coordinates requested, as some windowing systems can restrict the position of the window in certain scenarios (e.g. constraining the position so the window is always within desktop bounds). Additionally, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to reposition.
x the x coordinate of the window, or SDL_WINDOWPOS_CENTERED or SDL_WINDOWPOS_UNDEFINED.
y the y coordinate of the window, or SDL_WINDOWPOS_CENTERED or SDL_WINDOWPOS_UNDEFINED.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowPosition
SDL_SyncWindow
{
    SDL_DisplayID original_displayID;
    CHECK_WINDOW_MAGIC(window, false);
    const int w = window->last_size_pending ? window->pending.w : window->windowed.w;
    const int h = window->last_size_pending ? window->pending.h : window->windowed.h;
    original_displayID = SDL_GetDisplayForWindow(window);
    if (SDL_WINDOWPOS_ISUNDEFINED(x)) {
        x = window->windowed.x;
    }
    if (SDL_WINDOWPOS_ISUNDEFINED(y)) {
        y = window->windowed.y;
    }
    if (SDL_WINDOWPOS_ISCENTERED(x) || SDL_WINDOWPOS_ISCENTERED(y)) {
        SDL_DisplayID displayID = original_displayID;
        SDL_Rect bounds;
        if (SDL_WINDOWPOS_ISCENTERED(x) && (x & 0xFFFF)) {
            displayID = (x & 0xFFFF);
        } else if (SDL_WINDOWPOS_ISCENTERED(y) && (y & 0xFFFF)) {
            displayID = (y & 0xFFFF);
        }
        if (displayID == 0 || SDL_GetDisplayIndex(displayID) < 0) {
            displayID = SDL_GetPrimaryDisplay();
        }
        SDL_zero(bounds);
        if (!SDL_GetDisplayUsableBounds(displayID, &bounds) || w > bounds.w || h > bounds.h) {
            if (!SDL_GetDisplayBounds(displayID, &bounds)) {
                return false;
            }
        }
        if (SDL_WINDOWPOS_ISCENTERED(x)) {
            x = bounds.x + (bounds.w - w) / 2;
        }
        if (SDL_WINDOWPOS_ISCENTERED(y)) {
            y = bounds.y + (bounds.h - h) / 2;
        }
    }
    window->pending.x = x;
    window->pending.y = y;
    window->undefined_x = false;
    window->undefined_y = false;
    window->last_position_pending = true;
    if (_this->SetWindowPosition) {
        const bool result = _this->SetWindowPosition(_this, window);
        if (result) {
            SDL_SyncIfRequired(window);
        }
        return result;
    }
    return SDL_Unsupported();
}
References _this, CHECK_WINDOW_MAGIC, SDL_Rect::h, SDL_GetDisplayBounds(), SDL_GetDisplayForWindow(), SDL_GetDisplayIndex(), SDL_GetDisplayUsableBounds(), SDL_GetPrimaryDisplay(), SDL_SyncIfRequired(), SDL_Unsupported, SDL_WINDOWPOS_ISCENTERED, SDL_WINDOWPOS_ISUNDEFINED, SDL_zero, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
SDL_SetWindowProgressState()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowProgressState (SDL_Window * window, SDL_ProgressState state) extern
Sets the state of the progress bar for the given windows taskbar icon.
Parameters
window the window whose progress state is to be modified.
state the progress state. SDL_PROGRESS_STATE_NONE stops displaying the progress bar.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (state < SDL_PROGRESS_STATE_NONE || state > SDL_PROGRESS_STATE_ERROR) {
        return SDL_InvalidParamError("state");
    }
    window->progress_state = state;
    if (_this->ApplyWindowProgress) {
        if (!_this->ApplyWindowProgress(_this, window)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_InvalidParamError, and SDL_PROGRESS_STATE_ERROR.
Referenced by SDL_FinishWindowCreation().
SDL_SetWindowProgressValue()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowProgressValue (SDL_Window * window, float value) extern
Sets the value of the progress bar for the given windows taskbar icon.
Parameters
window the window whose progress value is to be modified.
value the progress value in the range of [0.0f - 1.0f]. If the value is outside the valid range, it gets clamped.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    value = SDL_clamp(value, 0.0f, 1.f);
    window->progress_value = value;
    if (_this->ApplyWindowProgress) {
        if (!_this->ApplyWindowProgress(_this, window)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_clamp.
Referenced by SDL_FinishWindowCreation().
SDL_SetWindowResizable()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowResizable (SDL_Window * window, bool resizable) extern
Set the user-resizable state of a window.
This will add or remove the window's SDL_WINDOW_RESIZABLE flag and allow/disallow user resizing of the window. This is a no-op if the window's resizable state already matches the requested state.
You can't change the resizable state of a fullscreen window.
Parameters
window the window of which to change the resizable state.
resizable true to allow resizing, false to disallow.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowFlags
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    const bool want = (resizable != false); // normalize the flag.
    const bool have = ((window->flags & SDL_WINDOW_RESIZABLE) != 0);
    if ((want != have) && (_this->SetWindowResizable)) {
        if (want) {
            window->flags |= SDL_WINDOW_RESIZABLE;
        } else {
            window->flags &= ~SDL_WINDOW_RESIZABLE;
            SDL_copyp(&window->windowed, &window->floating);
        }
        _this->SetWindowResizable(_this, window, want);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_copyp, and SDL_WINDOW_RESIZABLE.
SDL_SetWindowShape()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowShape (SDL_Window * window, SDL_Surface * shape) extern
Set the shape of a transparent window.
This sets the alpha channel of a transparent window and any fully transparent areas are also transparent to mouse clicks. If you are using something besides the SDL render API, then you are responsible for drawing the alpha channel of the window to match the shape alpha channel to get consistent cross-platform results.
The shape is copied inside this function, so you can free it afterwards. If your shape surface changes, you should call SDL_SetWindowShape() again to update the window. This is an expensive operation, so should be done sparingly.
The window must have been created with the SDL_WINDOW_TRANSPARENT flag.
Parameters
window the window.
shape the surface representing the shape of the window, or NULL to remove any current shape.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_PropertiesID props;
    SDL_Surface *surface;
    CHECK_WINDOW_MAGIC(window, false);
    if (!(window->flags & SDL_WINDOW_TRANSPARENT)) {
        return SDL_SetError("Window must be created with SDL_WINDOW_TRANSPARENT");
    }
    props = SDL_GetWindowProperties(window);
    if (!props) {
        return false;
    }
    surface = SDL_ConvertSurface(shape, SDL_PIXELFORMAT_ARGB32);
    if (!surface) {
        return false;
    }
    if (!SDL_SetSurfaceProperty(props, SDL_PROP_WINDOW_SHAPE_POINTER, surface)) {
        return false;
    }
    if (_this->UpdateWindowShape) {
        if (!_this->UpdateWindowShape(_this, window, surface)) {
            return false;
        }
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_ConvertSurface(), SDL_GetWindowProperties(), SDL_PIXELFORMAT_ARGB32, SDL_PROP_WINDOW_SHAPE_POINTER, SDL_SetError(), SDL_SetSurfaceProperty(), and SDL_WINDOW_TRANSPARENT.
SDL_SetWindowSize()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowSize (SDL_Window * window, int w, int h) extern
Request that the size of a window's client area be set.
If the window is in a fullscreen or maximized state, this request has no effect.
To change the exclusive fullscreen mode of a window, use SDL_SetWindowFullscreenMode().
On some windowing systems, this request is asynchronous and the new window size may not have have been applied immediately upon the return of this function. If an immediate change is required, call SDL_SyncWindow() to block until the changes have taken effect.
When the window size changes, an SDL_EVENT_WINDOW_RESIZED event will be emitted with the new window dimensions. Note that the new dimensions may not match the exact size requested, as some windowing systems can restrict the window size in certain scenarios (e.g. constraining the size of the content area to remain within the usable desktop bounds). Additionally, as this is just a request, it can be denied by the windowing system.
Parameters
window the window to change.
w the width of the window, must be > 0.
h the height of the window, must be > 0.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSize
SDL_SetWindowFullscreenMode
SDL_SyncWindow
{
    CHECK_WINDOW_MAGIC(window, false);
    if (w <= 0) {
        return SDL_InvalidParamError("w");
    }
    if (h <= 0) {
        return SDL_InvalidParamError("h");
    }
    // It is possible for the aspect ratio constraints to not satisfy the size constraints.
    // The size constraints will override the aspect ratio constraints so we will apply the
    // the aspect ratio constraints first
    float new_aspect = w / (float)h;
    if (window->max_aspect > 0.0f && new_aspect > window->max_aspect) {
        w = (int)SDL_roundf(h * window->max_aspect);
    } else if (window->min_aspect > 0.0f && new_aspect < window->min_aspect) {
        h = (int)SDL_roundf(w / window->min_aspect);
    }
    // Make sure we don't exceed any window size limits
    if (window->min_w && w < window->min_w) {
        w = window->min_w;
    }
    if (window->max_w && w > window->max_w) {
        w = window->max_w;
    }
    if (window->min_h && h < window->min_h) {
        h = window->min_h;
    }
    if (window->max_h && h > window->max_h) {
        h = window->max_h;
    }
    window->last_size_pending = true;
    window->pending.w = w;
    window->pending.h = h;
    if (_this->SetWindowSize) {
        _this->SetWindowSize(_this, window);
        SDL_SyncIfRequired(window);
    } else {
        return SDL_Unsupported();
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_InvalidParamError, SDL_roundf(), SDL_SyncIfRequired(), and SDL_Unsupported.
Referenced by SDL_SetWindowAspectRatio(), SDL_SetWindowMaximumSize(), and SDL_SetWindowMinimumSize().
SDL_SetWindowSurfaceVSync()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowSurfaceVSync (SDL_Window * window, int vsync) extern
Toggle VSync for the window surface.
When a window surface is created, vsync defaults to SDL_WINDOW_SURFACE_VSYNC_DISABLED.
The vsync parameter can be 1 to synchronize present with every vertical refresh, 2 to synchronize present with every second vertical refresh, etc., SDL_WINDOW_SURFACE_VSYNC_ADAPTIVE for late swap tearing (adaptive vsync), or SDL_WINDOW_SURFACE_VSYNC_DISABLED to disable. Not every value is supported by every driver, so you should check the return value to see whether the requested setting is supported.
Parameters
window the window.
vsync the vertical refresh sync interval.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurfaceVSync
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!_this->SetWindowFramebufferVSync) {
        return SDL_Unsupported();
    }
    return _this->SetWindowFramebufferVSync(_this, window, vsync);
}
References _this, CHECK_WINDOW_MAGIC, and SDL_Unsupported.
SDL_SetWindowTitle()
SDL_DECLSPEC bool SDLCALL SDL_SetWindowTitle (SDL_Window * window, const char * title) extern
Set the title of a window.
This string is expected to be in UTF-8 encoding.
Parameters
window the window to change.
title the desired window title in UTF-8 format.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowTitle
{
    CHECK_WINDOW_MAGIC(window, false);
    CHECK_WINDOW_NOT_POPUP(window, false);
    if (title == window->title) {
        return true;
    }
    if (!title) {
        title = "";
    }
    if (window->title && SDL_strcmp(title, window->title) == 0) {
        return true;
    }
    SDL_free(window->title);
    window->title = SDL_strdup(title);
    if (_this->SetWindowTitle) {
        _this->SetWindowTitle(_this, window);
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, SDL_free(), SDL_strcmp(), and SDL_strdup().
Referenced by SDL_CreateWindowWithProperties().
SDL_ShowWindow()
SDL_DECLSPEC bool SDLCALL SDL_ShowWindow (SDL_Window * window) extern
Show a window.
Parameters
window the window to show.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_HideWindow
SDL_RaiseWindow
{
    SDL_Window *child;
    CHECK_WINDOW_MAGIC(window, false);
    if (!(window->flags & SDL_WINDOW_HIDDEN)) {
        return true;
    }
    // If the parent is hidden, set the flag to restore this when the parent is shown
    if (window->parent && (window->parent->flags & SDL_WINDOW_HIDDEN)) {
        window->restore_on_show = true;
        return true;
    }
    if (_this->ShowWindow) {
        _this->ShowWindow(_this, window);
    } else {
        SDL_SetMouseFocus(window);
        SDL_SetKeyboardFocus(window);
    }
    SDL_SendWindowEvent(window, SDL_EVENT_WINDOW_SHOWN, 0, 0);
    // Restore child windows
    for (child = window->first_child; child; child = child->next_sibling) {
        if (!child->restore_on_show && (child->flags & SDL_WINDOW_HIDDEN)) {
            break;
        }
        SDL_ShowWindow(child);
        child->restore_on_show = false;
    }
    return true;
}
References _this, CHECK_WINDOW_MAGIC, SDL_Window::flags, SDL_Window::next_sibling, SDL_Window::restore_on_show, SDL_EVENT_WINDOW_SHOWN, SDL_SendWindowEvent(), SDL_SetKeyboardFocus(), SDL_SetMouseFocus(), SDL_ShowWindow(), and SDL_WINDOW_HIDDEN.
Referenced by SDL_CreateWindowAndRenderer(), SDL_FinishWindowCreation(), and SDL_ShowWindow().
SDL_ShowWindowSystemMenu()
SDL_DECLSPEC bool SDLCALL SDL_ShowWindowSystemMenu (SDL_Window * window, int x, int y) extern
Display the system-level window menu.
This default window menu is provided by the system and on some platforms provides functionality for setting or changing privileged state on the window, such as moving it between workspaces or displays, or toggling the always-on-top property.
On platforms or desktops where this is unsupported, this function does nothing.
Parameters
window the window for which the menu will be displayed.
x the x coordinate of the menu, relative to the origin (top-left) of the client area.
y the y coordinate of the menu, relative to the origin (top-left) of the client area.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_WINDOW_MAGIC(window, false)
    CHECK_WINDOW_NOT_POPUP(window, false)
    if (_this->ShowWindowSystemMenu) {
        _this->ShowWindowSystemMenu(window, x, y);
        return true;
    }
    return SDL_Unsupported();
}
References _this, CHECK_WINDOW_MAGIC, CHECK_WINDOW_NOT_POPUP, and SDL_Unsupported.
SDL_SyncWindow()
SDL_DECLSPEC bool SDLCALL SDL_SyncWindow (SDL_Window * window) extern
Block until any pending window state is finalized.
On asynchronous windowing systems, this acts as a synchronization barrier for pending window state. It will attempt to wait until any pending window state has been applied and is guaranteed to return within finite time. Note that for how long it can potentially block depends on the underlying window system, as window state changes may involve somewhat lengthy animations that must complete before the window is in its final requested state.
On windowing systems where changes are immediate, this does nothing.
Parameters
window the window for which to wait for the pending state to be applied.
Returns
true on success or false if the operation timed out before the window was in the requested state.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetWindowSize
SDL_SetWindowPosition
SDL_SetWindowFullscreen
SDL_MinimizeWindow
SDL_MaximizeWindow
SDL_RestoreWindow
SDL_HINT_VIDEO_SYNC_WINDOW_OPERATIONS
{
    CHECK_WINDOW_MAGIC(window, false)
    if (_this->SyncWindow) {
        return _this->SyncWindow(_this, window);
    } else {
        return true;
    }
}
References _this, and CHECK_WINDOW_MAGIC.
Referenced by SDL_SyncIfRequired().
SDL_UpdateWindowSurface()
SDL_DECLSPEC bool SDLCALL SDL_UpdateWindowSurface (SDL_Window * window) extern
Copy the window surface to the screen.
This is the function you use to reflect any changes to the surface on the screen.
This function is equivalent to the SDL 1.2 API SDL_Flip().
Parameters
window the window to update.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
SDL_UpdateWindowSurfaceRects
{
    SDL_Rect full_rect;
    CHECK_WINDOW_MAGIC(window, false);
    full_rect.x = 0;
    full_rect.y = 0;
    SDL_GetWindowSizeInPixels(window, &full_rect.w, &full_rect.h);
    return SDL_UpdateWindowSurfaceRects(window, &full_rect, 1);
}
References CHECK_WINDOW_MAGIC, SDL_Rect::h, SDL_GetWindowSizeInPixels(), SDL_UpdateWindowSurfaceRects(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
SDL_UpdateWindowSurfaceRects()
SDL_DECLSPEC bool SDLCALL SDL_UpdateWindowSurfaceRects (SDL_Window * window, const SDL_Rect * rects, int numrects) extern
Copy areas of the window surface to the screen.
This is the function you use to reflect changes to portions of the surface on the screen.
This function is equivalent to the SDL 1.2 API SDL_UpdateRects().
Note that this function will update at least the rectangles specified, but this is only intended as an optimization; in practice, this might update more of the screen (or all of the screen!), depending on what method SDL uses to send pixels to the system.
Parameters
window the window to update.
rects an array of SDL_Rect structures representing areas of the surface to copy, in pixels.
numrects the number of rectangles.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
SDL_UpdateWindowSurface
{
    CHECK_WINDOW_MAGIC(window, false);
    if (!window->surface_valid) {
        return SDL_SetError("Window surface is invalid, please call SDL_GetWindowSurface() to get a new surface");
    }
    SDL_assert(_this->checked_texture_framebuffer); // we should have done this before we had a valid surface.
    return _this->UpdateWindowFramebuffer(_this, window, rects, numrects);
}
References _this, CHECK_WINDOW_MAGIC, SDL_assert, and SDL_SetError().
Referenced by SDL_UpdateWindowSurface().
SDL_WindowHasSurface()
SDL_DECLSPEC bool SDLCALL SDL_WindowHasSurface (SDL_Window * window) extern
Return whether the window has a surface associated with it.
Parameters
window the window to query.
Returns
true if there is a surface associated with the window, or false otherwise.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetWindowSurface
{
    CHECK_WINDOW_MAGIC(window, false);
    return window->surface ? true : false;
}
References CHECK_WINDOW_MAGIC, and true.
Referenced by SDL_CreateRendererWithProperties().