SDL3: SDL-main/src/video/khronos/EGL/egl.h File Reference
egl.h File Reference
#include <EGL/eglplatform.h>
#include <KHR/khrplatform.h>
Macros
#define EGL_ALPHA_FORMAT 0x3088
#define EGL_ALPHA_FORMAT_NONPRE 0x308B
#define EGL_ALPHA_FORMAT_PRE 0x308C
#define EGL_ALPHA_MASK_SIZE 0x303E
#define EGL_ALPHA_SIZE 0x3021
#define EGL_BACK_BUFFER 0x3084
#define EGL_BAD_ACCESS 0x3002
#define EGL_BAD_ALLOC 0x3003
#define EGL_BAD_ATTRIBUTE 0x3004
#define EGL_BAD_CONFIG 0x3005
#define EGL_BAD_CONTEXT 0x3006
#define EGL_BAD_CURRENT_SURFACE 0x3007
#define EGL_BAD_DISPLAY 0x3008
#define EGL_BAD_MATCH 0x3009
#define EGL_BAD_NATIVE_PIXMAP 0x300A
#define EGL_BAD_NATIVE_WINDOW 0x300B
#define EGL_BAD_PARAMETER 0x300C
#define EGL_BAD_SURFACE 0x300D
#define EGL_BIND_TO_TEXTURE_RGB 0x3039
#define EGL_BIND_TO_TEXTURE_RGBA 0x303A
#define EGL_BLUE_SIZE 0x3022
#define EGL_BUFFER_DESTROYED 0x3095
#define EGL_BUFFER_PRESERVED 0x3094
#define EGL_BUFFER_SIZE 0x3020
#define EGL_CL_EVENT_HANDLE 0x309C
#define EGL_CLIENT_APIS 0x308D
#define EGL_COLOR_BUFFER_TYPE 0x303F
#define EGL_COLORSPACE 0x3087
#define EGL_COLORSPACE_LINEAR 0x308A
#define EGL_COLORSPACE_sRGB 0x3089
#define EGL_CONDITION_SATISFIED 0x30F6
#define EGL_CONFIG_CAVEAT 0x3027
#define EGL_CONFIG_ID 0x3028
#define EGL_CONFORMANT 0x3042
#define EGL_CONTEXT_CLIENT_TYPE 0x3097
#define EGL_CONTEXT_CLIENT_VERSION 0x3098
#define EGL_CONTEXT_LOST 0x300E
#define EGL_CONTEXT_MAJOR_VERSION 0x3098
#define EGL_CONTEXT_MINOR_VERSION 0x30FB
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT 0x00000002
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT 0x00000001
#define EGL_CONTEXT_OPENGL_DEBUG 0x31B0
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE 0x31B1
#define EGL_CONTEXT_OPENGL_PROFILE_MASK 0x30FD
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY 0x31BD
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS 0x31B2
#define EGL_CORE_NATIVE_ENGINE 0x305B
#define EGL_DEFAULT_DISPLAY EGL_CAST(EGLNativeDisplayType,0)
#define EGL_DEPTH_SIZE 0x3025
#define EGL_DISPLAY_SCALING 10000
#define EGL_DONT_CARE EGL_CAST(EGLint,-1)
#define EGL_DRAW 0x3059
#define EGL_EGL_PROTOTYPES 1
#define EGL_EXTENSIONS 0x3055
#define EGL_FALSE 0
#define EGL_FOREVER 0xFFFFFFFFFFFFFFFFull
#define EGL_GL_COLORSPACE 0x309D
#define EGL_GL_COLORSPACE_LINEAR 0x308A
#define EGL_GL_COLORSPACE_SRGB 0x3089
#define EGL_GL_RENDERBUFFER 0x30B9
#define EGL_GL_TEXTURE_2D 0x30B1
#define EGL_GL_TEXTURE_3D 0x30B2
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x30B4
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x30B6
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x30B8
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x30B3
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x30B5
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x30B7
#define EGL_GL_TEXTURE_LEVEL 0x30BC
#define EGL_GL_TEXTURE_ZOFFSET 0x30BD
#define EGL_GREEN_SIZE 0x3023
#define EGL_HEIGHT 0x3056
#define EGL_HORIZONTAL_RESOLUTION 0x3090
#define EGL_IMAGE_PRESERVED 0x30D2
#define EGL_LARGEST_PBUFFER 0x3058
#define EGL_LEVEL 0x3029
#define EGL_LOSE_CONTEXT_ON_RESET 0x31BF
#define EGL_LUMINANCE_BUFFER 0x308F
#define EGL_LUMINANCE_SIZE 0x303D
#define EGL_MATCH_NATIVE_PIXMAP 0x3041
#define EGL_MAX_PBUFFER_HEIGHT 0x302A
#define EGL_MAX_PBUFFER_PIXELS 0x302B
#define EGL_MAX_PBUFFER_WIDTH 0x302C
#define EGL_MAX_SWAP_INTERVAL 0x303C
#define EGL_MIN_SWAP_INTERVAL 0x303B
#define EGL_MIPMAP_LEVEL 0x3083
#define EGL_MIPMAP_TEXTURE 0x3082
#define EGL_MULTISAMPLE_RESOLVE 0x3099
#define EGL_MULTISAMPLE_RESOLVE_BOX 0x309B
#define EGL_MULTISAMPLE_RESOLVE_BOX_BIT 0x0200
#define EGL_MULTISAMPLE_RESOLVE_DEFAULT 0x309A
#define EGL_NATIVE_RENDERABLE 0x302D
#define EGL_NATIVE_VISUAL_ID 0x302E
#define EGL_NATIVE_VISUAL_TYPE 0x302F
#define EGL_NO_CONTEXT EGL_CAST(EGLContext,0)
#define EGL_NO_DISPLAY EGL_CAST(EGLDisplay,0)
#define EGL_NO_IMAGE EGL_CAST(EGLImage,0)
#define EGL_NO_RESET_NOTIFICATION 0x31BE
#define EGL_NO_SURFACE EGL_CAST(EGLSurface,0)
#define EGL_NO_SYNC EGL_CAST(EGLSync,0)
#define EGL_NO_TEXTURE 0x305C
#define EGL_NON_CONFORMANT_CONFIG 0x3051
#define EGL_NONE 0x3038
#define EGL_NOT_INITIALIZED 0x3001
#define EGL_OPENGL_API 0x30A2
#define EGL_OPENGL_BIT 0x0008
#define EGL_OPENGL_ES2_BIT 0x0004
#define EGL_OPENGL_ES3_BIT 0x00000040
#define EGL_OPENGL_ES_API 0x30A0
#define EGL_OPENGL_ES_BIT 0x0001
#define EGL_OPENVG_API 0x30A1
#define EGL_OPENVG_BIT 0x0002
#define EGL_OPENVG_IMAGE 0x3096
#define EGL_PBUFFER_BIT 0x0001
#define EGL_PIXEL_ASPECT_RATIO 0x3092
#define EGL_PIXMAP_BIT 0x0002
#define EGL_READ 0x305A
#define EGL_RED_SIZE 0x3024
#define EGL_RENDER_BUFFER 0x3086
#define EGL_RENDERABLE_TYPE 0x3040
#define EGL_RGB_BUFFER 0x308E
#define EGL_SAMPLE_BUFFERS 0x3032
#define EGL_SAMPLES 0x3031
#define EGL_SIGNALED 0x30F2
#define EGL_SINGLE_BUFFER 0x3085
#define EGL_SLOW_CONFIG 0x3050
#define EGL_STENCIL_SIZE 0x3026
#define EGL_SUCCESS 0x3000
#define EGL_SURFACE_TYPE 0x3033
#define EGL_SWAP_BEHAVIOR 0x3093
#define EGL_SWAP_BEHAVIOR_PRESERVED_BIT 0x0400
#define EGL_SYNC_CL_EVENT 0x30FE
#define EGL_SYNC_CL_EVENT_COMPLETE 0x30FF
#define EGL_SYNC_CONDITION 0x30F8
#define EGL_SYNC_FENCE 0x30F9
#define EGL_SYNC_FLUSH_COMMANDS_BIT 0x0001
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE 0x30F0
#define EGL_SYNC_STATUS 0x30F1
#define EGL_SYNC_TYPE 0x30F7
#define EGL_TEXTURE_2D 0x305F
#define EGL_TEXTURE_FORMAT 0x3080
#define EGL_TEXTURE_RGB 0x305D
#define EGL_TEXTURE_RGBA 0x305E
#define EGL_TEXTURE_TARGET 0x3081
#define EGL_TIMEOUT_EXPIRED 0x30F5
#define EGL_TRANSPARENT_BLUE_VALUE 0x3035
#define EGL_TRANSPARENT_GREEN_VALUE 0x3036
#define EGL_TRANSPARENT_RED_VALUE 0x3037
#define EGL_TRANSPARENT_RGB 0x3052
#define EGL_TRANSPARENT_TYPE 0x3034
#define EGL_TRUE 1
#define EGL_UNKNOWN EGL_CAST(EGLint,-1)
#define EGL_UNSIGNALED 0x30F3
#define EGL_VENDOR 0x3053
#define EGL_VERSION 0x3054
#define EGL_VERSION_1_0 1
#define EGL_VERSION_1_1 1
#define EGL_VERSION_1_2 1
#define EGL_VERSION_1_3 1
#define EGL_VERSION_1_4 1
#define EGL_VERSION_1_5 1
#define EGL_VERTICAL_RESOLUTION 0x3091
#define EGL_VG_ALPHA_FORMAT 0x3088
#define EGL_VG_ALPHA_FORMAT_NONPRE 0x308B
#define EGL_VG_ALPHA_FORMAT_PRE 0x308C
#define EGL_VG_ALPHA_FORMAT_PRE_BIT 0x0040
#define EGL_VG_COLORSPACE 0x3087
#define EGL_VG_COLORSPACE_LINEAR 0x308A
#define EGL_VG_COLORSPACE_LINEAR_BIT 0x0020
#define EGL_VG_COLORSPACE_sRGB 0x3089
#define EGL_WIDTH 0x3057
#define EGL_WINDOW_BIT 0x0004
Typedefs
typedef void(* __eglMustCastToProperFunctionPointerType) (void)
typedef const EGLint * attrib_list
typedef EGLConfig EGLint attribute
typedef EGLSurface EGLint buffer
typedef EGLenum buftype
typedef EGLConfig config
typedef const EGLint EGLConfig EGLint config_size
typedef const EGLint EGLConfig * configs
typedef EGLContext ctx
typedef EGLSurface draw
typedef intptr_t EGLAttrib
typedef unsigned int EGLBoolean
typedef void * EGLClientBuffer
typedef void * EGLConfig
typedef void * EGLContext
typedef void * EGLDisplay
typedef unsigned int EGLenum
typedef void * EGLImage
typedef void * EGLSurface
typedef void * EGLSync
typedef khronos_utime_nanoseconds_t EGLTime
typedef EGLSync EGLint flags
typedef EGLImage image
typedef EGLint interval
typedef EGLint * major
typedef EGLint EGLint * minor
typedef void * native_display
typedef EGLConfig void * native_pixmap
typedef EGLConfig void * native_window
typedef const EGLint EGLConfig EGLint EGLint * num_config
typedef const char *EGLAPIENTRYP PFNEGLQUERYSTRINGPROC(EGLDisplay dpy, EGLint name)
typedef EGLConfig EGLNativePixmapType pixmap
typedef EGLSurface EGLSurface read
typedef EGLConfig EGLContext share_context
typedef EGLSurface surface
typedef EGLSync sync
typedef EGLSurface EGLNativePixmapType target
typedef EGLSync EGLint EGLTime timeout
typedef EGLenum type
typedef EGLConfig EGLint EGLint * value
typedef EGLConfig EGLNativeWindowType win
Functions
typedef __eglMustCastToProperFunctionPointerType (EGLAPIENTRYP PFNEGLGETPROCADDRESSPROC)(const char *procname)
EGLAPI EGLBoolean EGLAPIENTRY eglBindAPI (EGLenum api)
EGLAPI EGLBoolean EGLAPIENTRY eglBindTexImage (EGLDisplay dpy, EGLSurface surface, EGLint buffer)
typedef EGLBoolean (EGLAPIENTRYP PFNEGLCHOOSECONFIGPROC)(EGLDisplay dpy
EGLAPI EGLBoolean EGLAPIENTRY eglChooseConfig (EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config)
EGLAPI EGLint EGLAPIENTRY eglClientWaitSync (EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout)
typedef EGLContext (EGLAPIENTRYP PFNEGLCREATECONTEXTPROC)(EGLDisplay dpy
EGLAPI EGLBoolean EGLAPIENTRY eglCopyBuffers (EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target)
EGLAPI EGLContext EGLAPIENTRY eglCreateContext (EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list)
EGLAPI EGLImage EGLAPIENTRY eglCreateImage (EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferFromClientBuffer (EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferSurface (EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePixmapSurface (EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePlatformPixmapSurface (EGLDisplay dpy, EGLConfig config, void *native_pixmap, const EGLAttrib *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePlatformWindowSurface (EGLDisplay dpy, EGLConfig config, void *native_window, const EGLAttrib *attrib_list)
EGLAPI EGLSync EGLAPIENTRY eglCreateSync (EGLDisplay dpy, EGLenum type, const EGLAttrib *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreateWindowSurface (EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list)
EGLAPI EGLBoolean EGLAPIENTRY eglDestroyContext (EGLDisplay dpy, EGLContext ctx)
EGLAPI EGLBoolean EGLAPIENTRY eglDestroyImage (EGLDisplay dpy, EGLImage image)
EGLAPI EGLBoolean EGLAPIENTRY eglDestroySurface (EGLDisplay dpy, EGLSurface surface)
EGLAPI EGLBoolean EGLAPIENTRY eglDestroySync (EGLDisplay dpy, EGLSync sync)
typedef EGLDisplay (EGLAPIENTRYP PFNEGLGETCURRENTDISPLAYPROC)(void)
typedef EGLenum (EGLAPIENTRYP PFNEGLQUERYAPIPROC)(void)
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigAttrib (EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value)
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigs (EGLDisplay dpy, EGLConfig *configs, EGLint config_size, EGLint *num_config)
EGLAPI EGLContext EGLAPIENTRY eglGetCurrentContext (void)
EGLAPI EGLDisplay EGLAPIENTRY eglGetCurrentDisplay (void)
EGLAPI EGLSurface EGLAPIENTRY eglGetCurrentSurface (EGLint readdraw)
EGLAPI EGLDisplay EGLAPIENTRY eglGetDisplay (EGLNativeDisplayType display_id)
EGLAPI EGLint EGLAPIENTRY eglGetError (void)
EGLAPI EGLDisplay EGLAPIENTRY eglGetPlatformDisplay (EGLenum platform, void *native_display, const EGLAttrib *attrib_list)
EGLAPI __eglMustCastToProperFunctionPointerType EGLAPIENTRY eglGetProcAddress (const char *procname)
EGLAPI EGLBoolean EGLAPIENTRY eglGetSyncAttrib (EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib *value)
typedef EGLImage (EGLAPIENTRYP PFNEGLCREATEIMAGEPROC)(EGLDisplay dpy
EGLAPI EGLBoolean EGLAPIENTRY eglInitialize (EGLDisplay dpy, EGLint *major, EGLint *minor)
typedef EGLint (EGLAPIENTRYP PFNEGLGETERRORPROC)(void)
EGLAPI EGLBoolean EGLAPIENTRY eglMakeCurrent (EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx)
EGLAPI EGLenum EGLAPIENTRY eglQueryAPI (void)
EGLAPI EGLBoolean EGLAPIENTRY eglQueryContext (EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint *value)
EGLAPI const char *EGLAPIENTRY eglQueryString (EGLDisplay dpy, EGLint name)
EGLAPI EGLBoolean EGLAPIENTRY eglQuerySurface (EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint *value)
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseTexImage (EGLDisplay dpy, EGLSurface surface, EGLint buffer)
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseThread (void)
typedef EGLSurface (EGLAPIENTRYP PFNEGLCREATEPBUFFERSURFACEPROC)(EGLDisplay dpy
EGLAPI EGLBoolean EGLAPIENTRY eglSurfaceAttrib (EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value)
EGLAPI EGLBoolean EGLAPIENTRY eglSwapBuffers (EGLDisplay dpy, EGLSurface surface)
EGLAPI EGLBoolean EGLAPIENTRY eglSwapInterval (EGLDisplay dpy, EGLint interval)
typedef EGLSync (EGLAPIENTRYP PFNEGLCREATESYNCPROC)(EGLDisplay dpy
EGLAPI EGLBoolean EGLAPIENTRY eglTerminate (EGLDisplay dpy)
EGLAPI EGLBoolean EGLAPIENTRY eglWaitClient (void)
EGLAPI EGLBoolean EGLAPIENTRY eglWaitGL (void)
EGLAPI EGLBoolean EGLAPIENTRY eglWaitNative (EGLint engine)
EGLAPI EGLBoolean EGLAPIENTRY eglWaitSync (EGLDisplay dpy, EGLSync sync, EGLint flags)
Macro Definition Documentation
EGL_ALPHA_FORMAT
#define EGL_ALPHA_FORMAT 0x3088
EGL_ALPHA_FORMAT_NONPRE
#define EGL_ALPHA_FORMAT_NONPRE 0x308B
EGL_ALPHA_FORMAT_PRE
#define EGL_ALPHA_FORMAT_PRE 0x308C
EGL_ALPHA_MASK_SIZE
#define EGL_ALPHA_MASK_SIZE 0x303E
EGL_ALPHA_SIZE
#define EGL_ALPHA_SIZE 0x3021
Referenced by chooseFormat().
EGL_BACK_BUFFER
#define EGL_BACK_BUFFER 0x3084
Referenced by glCreateContext().
EGL_BAD_ACCESS
#define EGL_BAD_ACCESS 0x3002
EGL_BAD_ALLOC
#define EGL_BAD_ALLOC 0x3003
EGL_BAD_ATTRIBUTE
#define EGL_BAD_ATTRIBUTE 0x3004
EGL_BAD_CONFIG
#define EGL_BAD_CONFIG 0x3005
EGL_BAD_CONTEXT
#define EGL_BAD_CONTEXT 0x3006
EGL_BAD_CURRENT_SURFACE
#define EGL_BAD_CURRENT_SURFACE 0x3007
EGL_BAD_DISPLAY
#define EGL_BAD_DISPLAY 0x3008
EGL_BAD_MATCH
#define EGL_BAD_MATCH 0x3009
EGL_BAD_NATIVE_PIXMAP
#define EGL_BAD_NATIVE_PIXMAP 0x300A
EGL_BAD_NATIVE_WINDOW
#define EGL_BAD_NATIVE_WINDOW 0x300B
EGL_BAD_PARAMETER
#define EGL_BAD_PARAMETER 0x300C
EGL_BAD_SURFACE
#define EGL_BAD_SURFACE 0x300D
EGL_BIND_TO_TEXTURE_RGB
#define EGL_BIND_TO_TEXTURE_RGB 0x3039
EGL_BIND_TO_TEXTURE_RGBA
#define EGL_BIND_TO_TEXTURE_RGBA 0x303A
EGL_BLUE_SIZE
#define EGL_BLUE_SIZE 0x3022
EGL_BUFFER_DESTROYED
#define EGL_BUFFER_DESTROYED 0x3095
EGL_BUFFER_PRESERVED
#define EGL_BUFFER_PRESERVED 0x3094
EGL_BUFFER_SIZE
#define EGL_BUFFER_SIZE 0x3020
Referenced by chooseFormat().
EGL_CL_EVENT_HANDLE
#define EGL_CL_EVENT_HANDLE 0x309C
EGL_CLIENT_APIS
#define EGL_CLIENT_APIS 0x308D
EGL_COLOR_BUFFER_TYPE
#define EGL_COLOR_BUFFER_TYPE 0x303F
EGL_COLORSPACE
#define EGL_COLORSPACE 0x3087
EGL_COLORSPACE_LINEAR
#define EGL_COLORSPACE_LINEAR 0x308A
EGL_COLORSPACE_sRGB
#define EGL_COLORSPACE_sRGB 0x3089
EGL_CONDITION_SATISFIED
#define EGL_CONDITION_SATISFIED 0x30F6
EGL_CONFIG_CAVEAT
#define EGL_CONFIG_CAVEAT 0x3027
EGL_CONFIG_ID
#define EGL_CONFIG_ID 0x3028
EGL_CONFORMANT
#define EGL_CONFORMANT 0x3042
EGL_CONTEXT_CLIENT_TYPE
#define EGL_CONTEXT_CLIENT_TYPE 0x3097
EGL_CONTEXT_CLIENT_VERSION
#define EGL_CONTEXT_CLIENT_VERSION 0x3098
Referenced by glCreateContext().
EGL_CONTEXT_LOST
#define EGL_CONTEXT_LOST 0x300E
EGL_CONTEXT_MAJOR_VERSION
#define EGL_CONTEXT_MAJOR_VERSION 0x3098
EGL_CONTEXT_MINOR_VERSION
#define EGL_CONTEXT_MINOR_VERSION 0x30FB
EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT
#define EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT 0x00000002
EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT
#define EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT 0x00000001
EGL_CONTEXT_OPENGL_DEBUG
#define EGL_CONTEXT_OPENGL_DEBUG 0x31B0
EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE
#define EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE 0x31B1
EGL_CONTEXT_OPENGL_PROFILE_MASK
#define EGL_CONTEXT_OPENGL_PROFILE_MASK 0x30FD
EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY
#define EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY 0x31BD
EGL_CONTEXT_OPENGL_ROBUST_ACCESS
#define EGL_CONTEXT_OPENGL_ROBUST_ACCESS 0x31B2
EGL_CORE_NATIVE_ENGINE
#define EGL_CORE_NATIVE_ENGINE 0x305B
EGL_DEFAULT_DISPLAY
#define EGL_DEFAULT_DISPLAY EGL_CAST(EGLNativeDisplayType,0)
Referenced by glLoadLibrary().
EGL_DEPTH_SIZE
#define EGL_DEPTH_SIZE 0x3025
Referenced by glGetConfig().
EGL_DISPLAY_SCALING
#define EGL_DISPLAY_SCALING 10000
EGL_DONT_CARE
#define EGL_DONT_CARE EGL_CAST(EGLint,-1)
EGL_DRAW
#define EGL_DRAW 0x3059
EGL_EGL_PROTOTYPES
#define EGL_EGL_PROTOTYPES 1
EGL_EXTENSIONS
#define EGL_EXTENSIONS 0x3055
EGL_FALSE
#define EGL_FALSE 0
Referenced by glLoadLibrary().
EGL_FOREVER
#define EGL_FOREVER 0xFFFFFFFFFFFFFFFFull
EGL_GL_COLORSPACE
#define EGL_GL_COLORSPACE 0x309D
EGL_GL_COLORSPACE_LINEAR
#define EGL_GL_COLORSPACE_LINEAR 0x308A
EGL_GL_COLORSPACE_SRGB
#define EGL_GL_COLORSPACE_SRGB 0x3089
EGL_GL_RENDERBUFFER
#define EGL_GL_RENDERBUFFER 0x30B9
EGL_GL_TEXTURE_2D
#define EGL_GL_TEXTURE_2D 0x30B1
EGL_GL_TEXTURE_3D
#define EGL_GL_TEXTURE_3D 0x30B2
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x30B4
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x30B6
EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
#define EGL_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x30B8
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x30B3
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x30B5
EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z
#define EGL_GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x30B7
EGL_GL_TEXTURE_LEVEL
#define EGL_GL_TEXTURE_LEVEL 0x30BC
EGL_GL_TEXTURE_ZOFFSET
#define EGL_GL_TEXTURE_ZOFFSET 0x30BD
EGL_GREEN_SIZE
#define EGL_GREEN_SIZE 0x3023
EGL_HEIGHT
#define EGL_HEIGHT 0x3056
EGL_HORIZONTAL_RESOLUTION
#define EGL_HORIZONTAL_RESOLUTION 0x3090
EGL_IMAGE_PRESERVED
#define EGL_IMAGE_PRESERVED 0x30D2
EGL_LARGEST_PBUFFER
#define EGL_LARGEST_PBUFFER 0x3058
EGL_LEVEL
#define EGL_LEVEL 0x3029
EGL_LOSE_CONTEXT_ON_RESET
#define EGL_LOSE_CONTEXT_ON_RESET 0x31BF
EGL_LUMINANCE_BUFFER
#define EGL_LUMINANCE_BUFFER 0x308F
EGL_LUMINANCE_SIZE
#define EGL_LUMINANCE_SIZE 0x303D
EGL_MATCH_NATIVE_PIXMAP
#define EGL_MATCH_NATIVE_PIXMAP 0x3041
EGL_MAX_PBUFFER_HEIGHT
#define EGL_MAX_PBUFFER_HEIGHT 0x302A
EGL_MAX_PBUFFER_PIXELS
#define EGL_MAX_PBUFFER_PIXELS 0x302B
EGL_MAX_PBUFFER_WIDTH
#define EGL_MAX_PBUFFER_WIDTH 0x302C
EGL_MAX_SWAP_INTERVAL
#define EGL_MAX_SWAP_INTERVAL 0x303C
EGL_MIN_SWAP_INTERVAL
#define EGL_MIN_SWAP_INTERVAL 0x303B
EGL_MIPMAP_LEVEL
#define EGL_MIPMAP_LEVEL 0x3083
EGL_MIPMAP_TEXTURE
#define EGL_MIPMAP_TEXTURE 0x3082
EGL_MULTISAMPLE_RESOLVE
#define EGL_MULTISAMPLE_RESOLVE 0x3099
EGL_MULTISAMPLE_RESOLVE_BOX
#define EGL_MULTISAMPLE_RESOLVE_BOX 0x309B
EGL_MULTISAMPLE_RESOLVE_BOX_BIT
#define EGL_MULTISAMPLE_RESOLVE_BOX_BIT 0x0200
EGL_MULTISAMPLE_RESOLVE_DEFAULT
#define EGL_MULTISAMPLE_RESOLVE_DEFAULT 0x309A
EGL_NATIVE_RENDERABLE
#define EGL_NATIVE_RENDERABLE 0x302D
EGL_NATIVE_VISUAL_ID
#define EGL_NATIVE_VISUAL_ID 0x302E
EGL_NATIVE_VISUAL_TYPE
#define EGL_NATIVE_VISUAL_TYPE 0x302F
EGL_NO_CONTEXT
#define EGL_NO_CONTEXT EGL_CAST(EGLContext,0)
Referenced by glCreateContext().
EGL_NO_DISPLAY
#define EGL_NO_DISPLAY EGL_CAST(EGLDisplay,0)
Referenced by glLoadLibrary(), and SDL_EGL_GetCurrentDisplay().
EGL_NO_IMAGE
#define EGL_NO_IMAGE EGL_CAST(EGLImage,0)
EGL_NO_RESET_NOTIFICATION
#define EGL_NO_RESET_NOTIFICATION 0x31BE
EGL_NO_SURFACE
#define EGL_NO_SURFACE EGL_CAST(EGLSurface,0)
Referenced by glCreateContext().
EGL_NO_SYNC
#define EGL_NO_SYNC EGL_CAST(EGLSync,0)
EGL_NO_TEXTURE
#define EGL_NO_TEXTURE 0x305C
EGL_NON_CONFORMANT_CONFIG
#define EGL_NON_CONFORMANT_CONFIG 0x3051
EGL_NONE
#define EGL_NONE 0x3038
Referenced by glCreateContext().
EGL_NOT_INITIALIZED
#define EGL_NOT_INITIALIZED 0x3001
EGL_OPENGL_API
#define EGL_OPENGL_API 0x30A2
EGL_OPENGL_BIT
#define EGL_OPENGL_BIT 0x0008
EGL_OPENGL_ES2_BIT
#define EGL_OPENGL_ES2_BIT 0x0004
Referenced by glGetConfig().
EGL_OPENGL_ES3_BIT
#define EGL_OPENGL_ES3_BIT 0x00000040
EGL_OPENGL_ES_API
#define EGL_OPENGL_ES_API 0x30A0
EGL_OPENGL_ES_BIT
#define EGL_OPENGL_ES_BIT 0x0001
EGL_OPENVG_API
#define EGL_OPENVG_API 0x30A1
EGL_OPENVG_BIT
#define EGL_OPENVG_BIT 0x0002
EGL_OPENVG_IMAGE
#define EGL_OPENVG_IMAGE 0x3096
EGL_PBUFFER_BIT
#define EGL_PBUFFER_BIT 0x0001
EGL_PIXEL_ASPECT_RATIO
#define EGL_PIXEL_ASPECT_RATIO 0x3092
EGL_PIXMAP_BIT
#define EGL_PIXMAP_BIT 0x0002
EGL_READ
#define EGL_READ 0x305A
EGL_RED_SIZE
#define EGL_RED_SIZE 0x3024
EGL_RENDER_BUFFER
#define EGL_RENDER_BUFFER 0x3086
Referenced by glCreateContext().
EGL_RENDERABLE_TYPE
#define EGL_RENDERABLE_TYPE 0x3040
Referenced by glGetConfig().
EGL_RGB_BUFFER
#define EGL_RGB_BUFFER 0x308E
EGL_SAMPLE_BUFFERS
#define EGL_SAMPLE_BUFFERS 0x3032
EGL_SAMPLES
#define EGL_SAMPLES 0x3031
EGL_SIGNALED
#define EGL_SIGNALED 0x30F2
EGL_SINGLE_BUFFER
#define EGL_SINGLE_BUFFER 0x3085
EGL_SLOW_CONFIG
#define EGL_SLOW_CONFIG 0x3050
EGL_STENCIL_SIZE
#define EGL_STENCIL_SIZE 0x3026
EGL_SUCCESS
#define EGL_SUCCESS 0x3000
EGL_SURFACE_TYPE
#define EGL_SURFACE_TYPE 0x3033
Referenced by glGetConfig().
EGL_SWAP_BEHAVIOR
#define EGL_SWAP_BEHAVIOR 0x3093
EGL_SWAP_BEHAVIOR_PRESERVED_BIT
#define EGL_SWAP_BEHAVIOR_PRESERVED_BIT 0x0400
EGL_SYNC_CL_EVENT
#define EGL_SYNC_CL_EVENT 0x30FE
EGL_SYNC_CL_EVENT_COMPLETE
#define EGL_SYNC_CL_EVENT_COMPLETE 0x30FF
EGL_SYNC_CONDITION
#define EGL_SYNC_CONDITION 0x30F8
EGL_SYNC_FENCE
#define EGL_SYNC_FENCE 0x30F9
EGL_SYNC_FLUSH_COMMANDS_BIT
#define EGL_SYNC_FLUSH_COMMANDS_BIT 0x0001
EGL_SYNC_PRIOR_COMMANDS_COMPLETE
#define EGL_SYNC_PRIOR_COMMANDS_COMPLETE 0x30F0
EGL_SYNC_STATUS
#define EGL_SYNC_STATUS 0x30F1
EGL_SYNC_TYPE
#define EGL_SYNC_TYPE 0x30F7
EGL_TEXTURE_2D
#define EGL_TEXTURE_2D 0x305F
EGL_TEXTURE_FORMAT
#define EGL_TEXTURE_FORMAT 0x3080
EGL_TEXTURE_RGB
#define EGL_TEXTURE_RGB 0x305D
EGL_TEXTURE_RGBA
#define EGL_TEXTURE_RGBA 0x305E
EGL_TEXTURE_TARGET
#define EGL_TEXTURE_TARGET 0x3081
EGL_TIMEOUT_EXPIRED
#define EGL_TIMEOUT_EXPIRED 0x30F5
EGL_TRANSPARENT_BLUE_VALUE
#define EGL_TRANSPARENT_BLUE_VALUE 0x3035
EGL_TRANSPARENT_GREEN_VALUE
#define EGL_TRANSPARENT_GREEN_VALUE 0x3036
EGL_TRANSPARENT_RED_VALUE
#define EGL_TRANSPARENT_RED_VALUE 0x3037
EGL_TRANSPARENT_RGB
#define EGL_TRANSPARENT_RGB 0x3052
EGL_TRANSPARENT_TYPE
#define EGL_TRANSPARENT_TYPE 0x3034
EGL_TRUE
#define EGL_TRUE 1
Referenced by glGetConfig(), glMakeCurrent(), glSetSwapInterval(), and glSwapWindow().
EGL_UNKNOWN
#define EGL_UNKNOWN EGL_CAST(EGLint,-1)
EGL_UNSIGNALED
#define EGL_UNSIGNALED 0x30F3
EGL_VENDOR
#define EGL_VENDOR 0x3053
EGL_VERSION
#define EGL_VERSION 0x3054
EGL_VERSION_1_0
#define EGL_VERSION_1_0 1
EGL_VERSION_1_1
#define EGL_VERSION_1_1 1
EGL_VERSION_1_2
#define EGL_VERSION_1_2 1
EGL_VERSION_1_3
#define EGL_VERSION_1_3 1
EGL_VERSION_1_4
#define EGL_VERSION_1_4 1
EGL_VERSION_1_5
#define EGL_VERSION_1_5 1
EGL_VERTICAL_RESOLUTION
#define EGL_VERTICAL_RESOLUTION 0x3091
EGL_VG_ALPHA_FORMAT
#define EGL_VG_ALPHA_FORMAT 0x3088
EGL_VG_ALPHA_FORMAT_NONPRE
#define EGL_VG_ALPHA_FORMAT_NONPRE 0x308B
EGL_VG_ALPHA_FORMAT_PRE
#define EGL_VG_ALPHA_FORMAT_PRE 0x308C
EGL_VG_ALPHA_FORMAT_PRE_BIT
#define EGL_VG_ALPHA_FORMAT_PRE_BIT 0x0040
EGL_VG_COLORSPACE
#define EGL_VG_COLORSPACE 0x3087
EGL_VG_COLORSPACE_LINEAR
#define EGL_VG_COLORSPACE_LINEAR 0x308A
EGL_VG_COLORSPACE_LINEAR_BIT
#define EGL_VG_COLORSPACE_LINEAR_BIT 0x0020
EGL_VG_COLORSPACE_sRGB
#define EGL_VG_COLORSPACE_sRGB 0x3089
EGL_WIDTH
#define EGL_WIDTH 0x3057
EGL_WINDOW_BIT
#define EGL_WINDOW_BIT 0x0004
Referenced by glGetConfig().
Typedef Documentation
__eglMustCastToProperFunctionPointerType
typedef void(* __eglMustCastToProperFunctionPointerType) (void)
attrib_list
typedef EGLStreamKHR EGLenum const EGLint * attrib_list
attribute
typedef struct wl_resource EGLint attribute
buffer
typedef struct wl_resource * buffer
buftype
typedef EGLenum buftype
config
typedef EGLenum EGLClientBuffer EGLConfig config
config_size
typedef EGLConfig EGLint config_size
configs
typedef EGLConfig * configs
ctx
typedef EGLSurface EGLSurface EGLContext ctx
draw
typedef EGLSurface draw
EGLAttrib
typedef intptr_t EGLAttrib
EGLBoolean
typedef EGLBoolean
EGLClientBuffer
typedef EGLClientBuffer
EGLConfig
typedef void* EGLConfig
EGLContext
typedef EGLContext
EGLDisplay
typedef EGLDisplay
EGLenum
typedef unsigned int EGLenum
EGLImage
typedef void* EGLImage
EGLSurface
typedef EGLSurface
EGLSync
typedef void* EGLSync
EGLTime
typedef khronos_utime_nanoseconds_t EGLTime
flags
typedef EGLSync EGLint flags
image
typedef EGLStreamKHR EGLImage image
interval
typedef EGLint interval
major
typedef EGLint* major
minor
typedef EGLint EGLint* minor
native_display
typedef void* native_display
native_pixmap
typedef EGLConfig void* native_pixmap
native_window
typedef EGLConfig void* native_window
num_config
typedef EGLConfig EGLint EGLint * num_config
PFNEGLQUERYSTRINGPROC
typedef const char *EGLAPIENTRYP PFNEGLQUERYSTRINGPROC(EGLDisplay dpy, EGLint name)
pixmap
typedef EGLSurface EGLNativePixmapType * pixmap
read
typedef EGLSurface EGLSurface read
share_context
typedef EGLConfig EGLContext share_context
surface
typedef EGLSurface surface
sync
typedef EGLStreamKHR EGLImage EGLSync sync
target
typedef EGLContext EGLenum target
timeout
typedef EGLSync EGLint EGLTime timeout
type
GLint GLenum GLsizei const GLvoid *pointer GLdouble GLdouble GLdouble GLdouble GLdouble GLdouble zFar GLfloat GLfloat GLfloat GLfloat y2 GLint GLenum GLsizei const GLvoid *pointer GLenum GLint GLint GLint GLsizei GLsizei GLenum GLenum type
value
typedef struct wl_resource EGLint EGLint * value
win
typedef EGLConfig EGLNativeWindowType win
Function Documentation
__eglMustCastToProperFunctionPointerType()
typedef __eglMustCastToProperFunctionPointerType (EGLAPIENTRYP PFNEGLGETPROCADDRESSPROC) const
References EGLAPIENTRYP.
eglBindAPI()
EGLAPI EGLBoolean EGLAPIENTRY eglBindAPI (EGLenum api)
References EGLAPI, and EGLAPIENTRY.
eglBindTexImage()
EGLAPI EGLBoolean EGLAPIENTRY eglBindTexImage (EGLDisplay dpy, EGLSurface surface, EGLint buffer)
References EGLAPI, and EGLAPIENTRY.
EGLBoolean()
typedef EGLBoolean (EGLAPIENTRYP PFNEGLCHOOSECONFIGPROC)
eglChooseConfig()
EGLAPI EGLBoolean EGLAPIENTRY eglChooseConfig (EGLDisplay dpy, const EGLint * attrib_list, EGLConfig * configs, EGLint config_size, EGLint * num_config)
References EGLAPI, and EGLAPIENTRY.
eglClientWaitSync()
EGLAPI EGLint EGLAPIENTRY eglClientWaitSync (EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout)
References EGLAPI, and EGLAPIENTRY.
EGLContext()
typedef EGLContext (EGLAPIENTRYP PFNEGLCREATECONTEXTPROC)
eglCopyBuffers()
EGLAPI EGLBoolean EGLAPIENTRY eglCopyBuffers (EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target)
References EGLAPI, and EGLAPIENTRY.
eglCreateContext()
EGLAPI EGLContext EGLAPIENTRY eglCreateContext (EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint * attrib_list)
References EGLAPI, and EGLAPIENTRY.
Referenced by glCreateContext().
eglCreateImage()
EGLAPI EGLImage EGLAPIENTRY eglCreateImage (EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglCreatePbufferFromClientBuffer()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferFromClientBuffer (EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglCreatePbufferSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferSurface (EGLDisplay dpy, EGLConfig config, const EGLint * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglCreatePixmapSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePixmapSurface (EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglCreatePlatformPixmapSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePlatformPixmapSurface (EGLDisplay dpy, EGLConfig config, void * native_pixmap, const EGLAttrib * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglCreatePlatformWindowSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePlatformWindowSurface (EGLDisplay dpy, EGLConfig config, void * native_window, const EGLAttrib * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglCreateSync()
EGLAPI EGLSync EGLAPIENTRY eglCreateSync (EGLDisplay dpy, EGLenum type, const EGLAttrib * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglCreateWindowSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreateWindowSurface (EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint * attrib_list)
References EGLAPI, and EGLAPIENTRY.
Referenced by glCreateContext().
eglDestroyContext()
EGLAPI EGLBoolean EGLAPIENTRY eglDestroyContext (EGLDisplay dpy, EGLContext ctx)
References EGLAPI, and EGLAPIENTRY.
Referenced by glDeleteContext().
eglDestroyImage()
EGLAPI EGLBoolean EGLAPIENTRY eglDestroyImage (EGLDisplay dpy, EGLImage image)
References EGLAPI, and EGLAPIENTRY.
eglDestroySurface()
EGLAPI EGLBoolean EGLAPIENTRY eglDestroySurface (EGLDisplay dpy, EGLSurface surface)
References EGLAPI, and EGLAPIENTRY.
eglDestroySync()
EGLAPI EGLBoolean EGLAPIENTRY eglDestroySync (EGLDisplay dpy, EGLSync sync)
References EGLAPI, and EGLAPIENTRY.
EGLDisplay()
typedef EGLDisplay (EGLAPIENTRYP PFNEGLGETCURRENTDISPLAYPROC)
References EGLAPIENTRYP, and void().
EGLenum()
typedef EGLenum (EGLAPIENTRYP PFNEGLQUERYAPIPROC)
References EGLAPIENTRYP, and void().
eglGetConfigAttrib()
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigAttrib (EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint * value)
References EGLAPI, and EGLAPIENTRY.
Referenced by chooseFormat(), and glGetConfig().
eglGetConfigs()
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigs (EGLDisplay dpy, EGLConfig * configs, EGLint config_size, EGLint * num_config)
References EGLAPI, and EGLAPIENTRY.
Referenced by glGetConfig().
eglGetCurrentContext()
EGLAPI EGLContext EGLAPIENTRY eglGetCurrentContext (void)
References EGLAPI, and EGLAPIENTRY.
eglGetCurrentDisplay()
EGLAPI EGLDisplay EGLAPIENTRY eglGetCurrentDisplay (void)
References EGLAPI, and EGLAPIENTRY.
eglGetCurrentSurface()
EGLAPI EGLSurface EGLAPIENTRY eglGetCurrentSurface (EGLint readdraw)
References EGLAPI, and EGLAPIENTRY.
eglGetDisplay()
EGLAPI EGLDisplay EGLAPIENTRY eglGetDisplay (EGLNativeDisplayType display_id)
References EGLAPI, and EGLAPIENTRY.
Referenced by glLoadLibrary().
eglGetError()
EGLAPI EGLint EGLAPIENTRY eglGetError (void)
References EGLAPI, and EGLAPIENTRY.
eglGetPlatformDisplay()
EGLAPI EGLDisplay EGLAPIENTRY eglGetPlatformDisplay (EGLenum platform, void * native_display, const EGLAttrib * attrib_list)
References EGLAPI, and EGLAPIENTRY.
eglGetProcAddress()
EGLAPI __eglMustCastToProperFunctionPointerType EGLAPIENTRY eglGetProcAddress (const char * procname)
References EGLAPI, and EGLAPIENTRY.
Referenced by glGetProcAddress().
eglGetSyncAttrib()
EGLAPI EGLBoolean EGLAPIENTRY eglGetSyncAttrib (EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib * value)
References EGLAPI, and EGLAPIENTRY.
EGLImage()
typedef EGLImage (EGLAPIENTRYP PFNEGLCREATEIMAGEPROC)
References EGLAPIENTRYP.
eglInitialize()
EGLAPI EGLBoolean EGLAPIENTRY eglInitialize (EGLDisplay dpy, EGLint * major, EGLint * minor)
References EGLAPI, and EGLAPIENTRY.
Referenced by glLoadLibrary().
EGLint()
typedef EGLint (EGLAPIENTRYP PFNEGLGETERRORPROC)
References EGLAPIENTRYP, and void().
eglMakeCurrent()
EGLAPI EGLBoolean EGLAPIENTRY eglMakeCurrent (EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx)
References EGLAPI, and EGLAPIENTRY.
Referenced by glCreateContext(), and glMakeCurrent().
eglQueryAPI()
EGLAPI EGLenum EGLAPIENTRY eglQueryAPI (void)
References EGLAPI, and EGLAPIENTRY.
eglQueryContext()
EGLAPI EGLBoolean EGLAPIENTRY eglQueryContext (EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint * value)
References EGLAPI, and EGLAPIENTRY.
eglQueryString()
EGLAPI const char *EGLAPIENTRY eglQueryString (EGLDisplay dpy, EGLint name)
References EGLAPI, and EGLAPIENTRY.
eglQuerySurface()
EGLAPI EGLBoolean EGLAPIENTRY eglQuerySurface (EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint * value)
References EGLAPI, and EGLAPIENTRY.
eglReleaseTexImage()
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseTexImage (EGLDisplay dpy, EGLSurface surface, EGLint buffer)
References EGLAPI, and EGLAPIENTRY.
eglReleaseThread()
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseThread (void)
References EGLAPI, and EGLAPIENTRY.
EGLSurface()
typedef EGLSurface (EGLAPIENTRYP PFNEGLCREATEPBUFFERSURFACEPROC)
References EGLAPIENTRYP.
eglSurfaceAttrib()
EGLAPI EGLBoolean EGLAPIENTRY eglSurfaceAttrib (EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value)
References EGLAPI, and EGLAPIENTRY.
eglSwapBuffers()
EGLAPI EGLBoolean EGLAPIENTRY eglSwapBuffers (EGLDisplay dpy, EGLSurface surface)
References EGLAPI, and EGLAPIENTRY.
Referenced by glSwapWindow().
eglSwapInterval()
EGLAPI EGLBoolean EGLAPIENTRY eglSwapInterval (EGLDisplay dpy, EGLint interval)
References EGLAPI, and EGLAPIENTRY.
Referenced by glSetSwapInterval().
EGLSync()
typedef EGLSync (EGLAPIENTRYP PFNEGLCREATESYNCPROC)
References EGLAPIENTRYP.
eglTerminate()
EGLAPI EGLBoolean EGLAPIENTRY eglTerminate (EGLDisplay dpy)
References EGLAPI, and EGLAPIENTRY.
Referenced by glUnloadLibrary().
eglWaitClient()
EGLAPI EGLBoolean EGLAPIENTRY eglWaitClient (void)
References EGLAPI, and EGLAPIENTRY.
eglWaitGL()
EGLAPI EGLBoolean EGLAPIENTRY eglWaitGL (void)
References EGLAPI, and EGLAPIENTRY.
eglWaitNative()
EGLAPI EGLBoolean EGLAPIENTRY eglWaitNative (EGLint engine)
References EGLAPI, and EGLAPIENTRY.
eglWaitSync()
EGLAPI EGLBoolean EGLAPIENTRY eglWaitSync (EGLDisplay dpy, EGLSync sync, EGLint flags)
References EGLAPI, and EGLAPIENTRY.