SDL3: SDL_BLooper Class Reference
SDL_BLooper Class Reference
#include <SDL_BApp.h>
Inherits BLooper.
Public Member Functions
void ClearID (SDL_BWin *bwin)
int32 GetID (SDL_Window *win)
SDL_Window * GetSDLWindow (int32 winID)
virtual void MessageReceived (BMessage *message)
SDL_BLooper (const char *name)
virtual ~SDL_BLooper ()
Private Member Functions
int32 _GetNumWindowSlots ()
bool _GetWinID (BMessage *msg, int32 *winID)
void _HandleBasicWindowEvent (BMessage *msg, SDL_EventType sdlEventType)
void _HandleKey (BMessage *msg)
void _HandleKeyboardFocus (BMessage *msg)
void _HandleMouseButton (BMessage *msg)
void _HandleMouseFocus (BMessage *msg)
void _HandleMouseMove (BMessage *msg)
void _HandleMouseWheel (BMessage *msg)
void _HandleWindowMoved (BMessage *msg)
void _HandleWindowResized (BMessage *msg)
void _PopBackWindow ()
void _PushBackWindow (SDL_Window *win)
void _SetSDLWindow (SDL_Window *win, int32 winID)
Private Attributes
std::vector< SDL_Window * > _window_map
Constructor & Destructor Documentation
SDL_BLooper()
SDL_BLooper::SDL_BLooper (const char * name) inline
                                  : BLooper(name)
    {
#ifdef SDL_VIDEO_OPENGL
        _current_context = NULL;
#endif
    }
References NULL.
~SDL_BLooper()
virtual SDL_BLooper::~SDL_BLooper () inline virtual
    {
    }
Member Function Documentation
_GetNumWindowSlots()
int32 SDL_BLooper::_GetNumWindowSlots () inline private
    {
        return _window_map.size();
    }
References _window_map.
Referenced by GetID().
_GetWinID()
bool SDL_BLooper::_GetWinID (BMessage * msg, int32 * winID) inline private
    {
        return msg->FindInt32("window-id", winID) == B_OK;
    }
Referenced by _HandleBasicWindowEvent(), _HandleKeyboardFocus(), _HandleMouseButton(), _HandleMouseFocus(), _HandleMouseMove(), _HandleMouseWheel(), _HandleWindowMoved(), and _HandleWindowResized().
_HandleBasicWindowEvent()
void SDL_BLooper::_HandleBasicWindowEvent (BMessage * msg, SDL_EventType sdlEventType) inline private
    {
        SDL_Window *win;
        int32 winID;
        if (
            !_GetWinID(msg, &winID)) {
            return;
        }
        win = GetSDLWindow(winID);
        SDL_SendWindowEvent(win, sdlEventType, 0, 0);
    }
References _GetWinID(), GetSDLWindow(), and SDL_SendWindowEvent().
Referenced by MessageReceived().
_HandleKey()
void SDL_BLooper::_HandleKey (BMessage * msg) inline private
    {
        int32 scancode;
        bool down;
        if (
            msg->FindInt32("key-scancode", &scancode) != B_OK ||
            msg->FindBool("key-down", &down) != B_OK) {
            return;
        }
        SDL_SendKeyboardKey(0, SDL_DEFAULT_KEYBOARD_ID, scancode, HAIKU_GetScancodeFromBeKey(scancode), down);
        if (down) {
            SDL_Window *win = SDL_GetKeyboardFocus();
            if (win && SDL_TextInputActive(win)) {
                const int8 *keyUtf8;
                ssize_t count;
                if (msg->FindData("key-utf8", B_INT8_TYPE, (const void **)&keyUtf8, &count) == B_OK) {
                    char text[64];
                    SDL_zeroa(text);
                    SDL_memcpy(text, keyUtf8, count);
                    SDL_SendKeyboardText(text);
                }
            }
        }
    }
References count, HAIKU_GetScancodeFromBeKey(), scancode, SDL_DEFAULT_KEYBOARD_ID, SDL_GetKeyboardFocus(), SDL_memcpy, SDL_SendKeyboardKey(), SDL_SendKeyboardText(), SDL_TextInputActive(), and SDL_zeroa.
Referenced by MessageReceived().
_HandleKeyboardFocus()
void SDL_BLooper::_HandleKeyboardFocus (BMessage * msg) inline private
    {
        SDL_Window *win;
        int32 winID;
        bool bSetFocus; // If false, lose focus
        if (
            !_GetWinID(msg, &winID) ||
            msg->FindBool("focusGained", &bSetFocus) != B_OK) {
            return;
        }
        win = GetSDLWindow(winID);
        if (bSetFocus) {
            SDL_SetKeyboardFocus(win);
        } else if (SDL_GetKeyboardFocus() == win) {
            // Only lose all focus if this window was the current focus
            SDL_SetKeyboardFocus(NULL);
        }
    }
References _GetWinID(), GetSDLWindow(), NULL, SDL_GetKeyboardFocus(), and SDL_SetKeyboardFocus().
Referenced by MessageReceived().
_HandleMouseButton()
void SDL_BLooper::_HandleMouseButton (BMessage * msg) inline private
    {
        SDL_Window *win;
        int32 winID;
        int32 button;
        bool down;
        if (
            !_GetWinID(msg, &winID) ||
            msg->FindInt32("button-id", &button) != B_OK ||
            msg->FindBool("button-down", &down) != B_OK) {
            return;
        }
        win = GetSDLWindow(winID);
        SDL_SendMouseButton(0, win, SDL_DEFAULT_MOUSE_ID, button, down);
    }
References _GetWinID(), GetSDLWindow(), SDL_DEFAULT_MOUSE_ID, and SDL_SendMouseButton().
Referenced by MessageReceived().
_HandleMouseFocus()
void SDL_BLooper::_HandleMouseFocus (BMessage * msg) inline private
    {
        SDL_Window *win;
        int32 winID;
        bool bSetFocus; // If false, lose focus
        if (
            !_GetWinID(msg, &winID) ||
            msg->FindBool("focusGained", &bSetFocus) != B_OK) {
            return;
        }
        win = GetSDLWindow(winID);
        if (bSetFocus) {
            SDL_SetMouseFocus(win);
        } else if (SDL_GetMouseFocus() == win) {
            // Only lose all focus if this window was the current focus
            SDL_SetMouseFocus(NULL);
        }
    }
References _GetWinID(), GetSDLWindow(), NULL, SDL_GetMouseFocus(), and SDL_SetMouseFocus().
Referenced by MessageReceived().
_HandleMouseMove()
void SDL_BLooper::_HandleMouseMove (BMessage * msg) inline private
    {
        SDL_Window *win;
        int32 winID;
        int32 x = 0, y = 0;
        if (
            !_GetWinID(msg, &winID) ||
            msg->FindInt32("x", &x) != B_OK || // x movement
            msg->FindInt32("y", &y) != B_OK    // y movement
        ) {
            return;
        }
        win = GetSDLWindow(winID);
        // Simple relative mode support for mouse.
        if (SDL_GetMouse()->relative_mode) {
            int winWidth, winHeight, winPosX, winPosY;
            SDL_GetWindowSize(win, &winWidth, &winHeight);
            SDL_GetWindowPosition(win, &winPosX, &winPosY);
            int dx = x - (winWidth / 2);
            int dy = y - (winHeight / 2);
            SDL_SendMouseMotion(0, win, SDL_DEFAULT_MOUSE_ID, SDL_GetMouse()->relative_mode, (float)dx, (float)dy);
            set_mouse_position((winPosX + winWidth / 2), (winPosY + winHeight / 2));
            if (!be_app->IsCursorHidden())
                be_app->HideCursor();
        } else {
            SDL_SendMouseMotion(0, win, SDL_DEFAULT_MOUSE_ID, false, (float)x, (float)y);
            if (SDL_CursorVisible() && be_app->IsCursorHidden())
                be_app->ShowCursor();
        }
    }
References _GetWinID(), GetSDLWindow(), SDL_CursorVisible(), SDL_DEFAULT_MOUSE_ID, SDL_GetMouse(), SDL_GetWindowPosition(), SDL_GetWindowSize(), and SDL_SendMouseMotion().
Referenced by MessageReceived().
_HandleMouseWheel()
void SDL_BLooper::_HandleMouseWheel (BMessage * msg) inline private
    {
        SDL_Window *win;
        int32 winID;
        int32 xTicks, yTicks;
        if (
            !_GetWinID(msg, &winID) ||
            msg->FindInt32("xticks", &xTicks) != B_OK ||
            msg->FindInt32("yticks", &yTicks) != B_OK) {
            return;
        }
        win = GetSDLWindow(winID);
        SDL_SendMouseWheel(0, win, SDL_DEFAULT_MOUSE_ID, xTicks, -yTicks, SDL_MOUSEWHEEL_NORMAL);
    }
References _GetWinID(), GetSDLWindow(), SDL_DEFAULT_MOUSE_ID, SDL_MOUSEWHEEL_NORMAL, and SDL_SendMouseWheel().
Referenced by MessageReceived().
_HandleWindowMoved()
void SDL_BLooper::_HandleWindowMoved (BMessage * msg) inline private
    {
        SDL_Window *win;
        int32 winID;
        int32 xPos, yPos;
        // Get the window id and new x/y position of the window
        if (
            !_GetWinID(msg, &winID) ||
            msg->FindInt32("window-x", &xPos) != B_OK ||
            msg->FindInt32("window-y", &yPos) != B_OK) {
            return;
        }
        win = GetSDLWindow(winID);
        SDL_SendWindowEvent(win, SDL_EVENT_WINDOW_MOVED, xPos, yPos);
    }
References _GetWinID(), GetSDLWindow(), SDL_EVENT_WINDOW_MOVED, and SDL_SendWindowEvent().
Referenced by MessageReceived().
_HandleWindowResized()
void SDL_BLooper::_HandleWindowResized (BMessage * msg) inline private
    {
        SDL_Window *win;
        int32 winID;
        int32 w, h;
        // Get the window id ]and new x/y position of the window
        if (
            !_GetWinID(msg, &winID) ||
            msg->FindInt32("window-w", &w) != B_OK ||
            msg->FindInt32("window-h", &h) != B_OK) {
            return;
        }
        win = GetSDLWindow(winID);
        SDL_SendWindowEvent(win, SDL_EVENT_WINDOW_RESIZED, w, h);
    }
References _GetWinID(), GetSDLWindow(), SDL_EVENT_WINDOW_RESIZED, and SDL_SendWindowEvent().
Referenced by MessageReceived().
_PopBackWindow()
void SDL_BLooper::_PopBackWindow () inline private
    {
        _window_map.pop_back();
    }
References _window_map.
_PushBackWindow()
void SDL_BLooper::_PushBackWindow (SDL_Window * win) inline private
    {
        _window_map.push_back(win);
    }
References _window_map.
Referenced by GetID().
_SetSDLWindow()
void SDL_BLooper::_SetSDLWindow (SDL_Window * win, int32 winID) inline private
    {
        _window_map[winID] = win;
    }
References _window_map.
Referenced by GetID().
ClearID()
void SDL_BLooper::ClearID (SDL_BWin * bwin)
GetID()
int32 SDL_BLooper::GetID (SDL_Window * win) inline
    {
        int32 i;
        for (i = 0; i < _GetNumWindowSlots(); ++i) {
            if (GetSDLWindow(i) == NULL) {
                _SetSDLWindow(win, i);
                return i;
            }
        }
        // Expand the vector if all slots are full
        if (i == _GetNumWindowSlots()) {
            _PushBackWindow(win);
            return i;
        }
        // TODO: error handling
        return 0;
    }
References _GetNumWindowSlots(), _PushBackWindow(), _SetSDLWindow(), GetSDLWindow(), and NULL.
GetSDLWindow()
SDL_Window * SDL_BLooper::GetSDLWindow (int32 winID) inline
    {
        return _window_map[winID];
    }
References _window_map.
Referenced by _HandleBasicWindowEvent(), _HandleKeyboardFocus(), _HandleMouseButton(), _HandleMouseFocus(), _HandleMouseMove(), _HandleMouseWheel(), _HandleWindowMoved(), _HandleWindowResized(), and GetID().
MessageReceived()
virtual void SDL_BLooper::MessageReceived (BMessage * message) inline virtual
    {
        // Sort out SDL-related messages
        switch (message->what) {
        case BAPP_MOUSE_MOVED:
            _HandleMouseMove(message);
            break;
        case BAPP_MOUSE_BUTTON:
            _HandleMouseButton(message);
            break;
        case BAPP_MOUSE_WHEEL:
            _HandleMouseWheel(message);
            break;
        case BAPP_KEY:
            _HandleKey(message);
            break;
        case BAPP_REPAINT:
            _HandleBasicWindowEvent(message, SDL_EVENT_WINDOW_EXPOSED);
            break;
        case BAPP_MAXIMIZE:
            _HandleBasicWindowEvent(message, SDL_EVENT_WINDOW_MAXIMIZED);
            break;
        case BAPP_MINIMIZE:
            _HandleBasicWindowEvent(message, SDL_EVENT_WINDOW_MINIMIZED);
            break;
        case BAPP_SHOW:
            _HandleBasicWindowEvent(message, SDL_EVENT_WINDOW_SHOWN);
            break;
        case BAPP_HIDE:
            _HandleBasicWindowEvent(message, SDL_EVENT_WINDOW_HIDDEN);
            break;
        case BAPP_MOUSE_FOCUS:
            _HandleMouseFocus(message);
            break;
        case BAPP_KEYBOARD_FOCUS:
            _HandleKeyboardFocus(message);
            break;
        case BAPP_WINDOW_CLOSE_REQUESTED:
            _HandleBasicWindowEvent(message, SDL_EVENT_WINDOW_CLOSE_REQUESTED);
            break;
        case BAPP_WINDOW_MOVED:
            _HandleWindowMoved(message);
            break;
        case BAPP_WINDOW_RESIZED:
            _HandleWindowResized(message);
            break;
        case B_LOCALE_CHANGED:
            SDL_SendLocaleChangedEvent();
            break;
        case BAPP_SCREEN_CHANGED:
            // TODO: Handle screen resize or workspace change
            break;
        default:
            BLooper::MessageReceived(message);
            break;
        }
    }
References _HandleBasicWindowEvent(), _HandleKey(), _HandleKeyboardFocus(), _HandleMouseButton(), _HandleMouseFocus(), _HandleMouseMove(), _HandleMouseWheel(), _HandleWindowMoved(), _HandleWindowResized(), BAPP_HIDE, BAPP_KEY, BAPP_KEYBOARD_FOCUS, BAPP_MAXIMIZE, BAPP_MINIMIZE, BAPP_MOUSE_BUTTON, BAPP_MOUSE_FOCUS, BAPP_MOUSE_MOVED, BAPP_MOUSE_WHEEL, BAPP_REPAINT, BAPP_SCREEN_CHANGED, BAPP_SHOW, BAPP_WINDOW_CLOSE_REQUESTED, BAPP_WINDOW_MOVED, BAPP_WINDOW_RESIZED, SDL_EVENT_WINDOW_CLOSE_REQUESTED, SDL_EVENT_WINDOW_EXPOSED, SDL_EVENT_WINDOW_HIDDEN, SDL_EVENT_WINDOW_MAXIMIZED, SDL_EVENT_WINDOW_MINIMIZED, SDL_EVENT_WINDOW_SHOWN, and SDL_SendLocaleChangedEvent().
Field Documentation
_window_map
std::vector<SDL_Window *> SDL_BLooper::_window_map private
Referenced by _GetNumWindowSlots(), _PopBackWindow(), _PushBackWindow(), _SetSDLWindow(), and GetSDLWindow().
The documentation for this class was generated from the following file:
SDL-main/src/core/haiku/SDL_BApp.h