SDL3: SDL-main/src/thread/SDL_thread.c File Reference
SDL_thread.c File Reference
#include "SDL_internal.h"
#include "SDL_thread_c.h"
#include "SDL_systhread.h"
#include "../SDL_error_c.h"
Data Structures
struct SDL_TLSEntry
Typedefs
typedef struct SDL_TLSEntry SDL_TLSEntry
Functions
void SDL_CleanupTLS (void)
SDL_Thread * SDL_CreateThreadRuntime (SDL_ThreadFunction fn, const char *name, void *userdata, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
SDL_Thread * SDL_CreateThreadWithPropertiesRuntime (SDL_PropertiesID props, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
SDL_Thread * SDL_CreateThreadWithStackSize (SDL_ThreadFunction fn, const char *name, size_t stacksize, void *userdata)
void SDL_DetachThread (SDL_Thread *thread)
static void SDLCALL SDL_FreeErrBuf (void *data)
SDL_TLSData * SDL_Generic_GetTLSData (void)
void SDL_Generic_InitTLSData (void)
void SDL_Generic_QuitTLSData (void)
bool SDL_Generic_SetTLSData (SDL_TLSData *data)
SDL_error * SDL_GetErrBuf (bool create)
static SDL_error * SDL_GetStaticErrBuf (void)
SDL_ThreadID SDL_GetThreadID (SDL_Thread *thread)
const char * SDL_GetThreadName (SDL_Thread *thread)
SDL_ThreadState SDL_GetThreadState (SDL_Thread *thread)
void * SDL_GetTLS (SDL_TLSID *id)
void SDL_InitTLSData (void)
void SDL_QuitTLSData (void)
void SDL_RunThread (SDL_Thread *thread)
bool SDL_SetCurrentThreadPriority (SDL_ThreadPriority priority)
void SDL_SetInitialized (SDL_InitState *state, bool initialized)
bool SDL_SetTLS (SDL_TLSID *id, const void *value, SDL_TLSDestructorCallback destructor)
bool SDL_ShouldInit (SDL_InitState *state)
bool SDL_ShouldQuit (SDL_InitState *state)
bool SDL_TryWaitSemaphore (SDL_Semaphore *sem)
void SDL_WaitCondition (SDL_Condition *cond, SDL_Mutex *mutex)
bool SDL_WaitConditionTimeout (SDL_Condition *cond, SDL_Mutex *mutex, Sint32 timeoutMS)
void SDL_WaitSemaphore (SDL_Semaphore *sem)
bool SDL_WaitSemaphoreTimeout (SDL_Semaphore *sem, Sint32 timeoutMS)
void SDL_WaitThread (SDL_Thread *thread, int *status)
static bool ThreadValid (SDL_Thread *thread)
Variables
static SDL_TLSEntry * SDL_generic_TLS
static SDL_Mutex * SDL_generic_TLS_mutex
static SDL_AtomicInt SDL_tls_allocated
static SDL_AtomicInt SDL_tls_id
Typedef Documentation
SDL_TLSEntry
typedef struct SDL_TLSEntry SDL_TLSEntry
Function Documentation
SDL_CleanupTLS()
void SDL_CleanupTLS (void)
Cleanup all TLS data for this thread.
If you are creating your threads outside of SDL and then calling SDL functions, you should call this function before your thread exits, to properly clean up SDL memory.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_TLSData *storage;
    // Cleanup the storage for the current thread
    storage = SDL_SYS_GetTLSData();
    if (storage) {
        int i;
        for (i = 0; i < storage->limit; ++i) {
            if (storage->array[i].destructor) {
                storage->array[i].destructor(storage->array[i].data);
            }
        }
        SDL_SYS_SetTLSData(NULL);
        SDL_free(storage);
        (void)SDL_AtomicDecRef(&SDL_tls_allocated);
    }
}
References SDL_TLSData::array, SDL_TLSData::data, SDL_TLSData::limit, NULL, SDL_AtomicDecRef, SDL_free(), SDL_SYS_GetTLSData(), SDL_SYS_SetTLSData(), SDL_tls_allocated, and void().
Referenced by SDL_QuitTLSData(), and SDL_RunThread().
SDL_CreateThreadRuntime()
SDL_Thread * SDL_CreateThreadRuntime (SDL_ThreadFunction fn, const char * name, void * data, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
The actual entry point for SDL_CreateThread.
Parameters
fn the SDL_ThreadFunction function to call in the new thread
name the name of the thread
data a pointer that is passed to fn
pfnBeginThread the C runtime's _beginthreadex (or whatnot). Can be NULL.
pfnEndThread the C runtime's _endthreadex (or whatnot). Can be NULL.
Returns
an opaque pointer to the new thread object on success, NULL if the new thread could not be created; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    const SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, (void *) fn);
    SDL_SetStringProperty(props, SDL_PROP_THREAD_CREATE_NAME_STRING, name);
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, userdata);
    SDL_Thread *thread = SDL_CreateThreadWithPropertiesRuntime(props, pfnBeginThread, pfnEndThread);
    SDL_DestroyProperties(props);
    return thread;
}
References SDL_CreateProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_DestroyProperties(), SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, SDL_PROP_THREAD_CREATE_NAME_STRING, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, SDL_SetPointerProperty(), SDL_SetStringProperty(), and SDL_TLSEntry::thread.
SDL_CreateThreadWithPropertiesRuntime()
SDL_Thread * SDL_CreateThreadWithPropertiesRuntime (SDL_PropertiesID props, SDL_FunctionPointer pfnBeginThread, SDL_FunctionPointer pfnEndThread)
The actual entry point for SDL_CreateThreadWithProperties.
Parameters
props the properties to use
pfnBeginThread the C runtime's _beginthreadex (or whatnot). Can be NULL.
pfnEndThread the C runtime's _endthreadex (or whatnot). Can be NULL.
Returns
an opaque pointer to the new thread object on success, NULL if the new thread could not be created; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    // rather than check this in every backend, just make sure it's correct upfront. Only allow non-NULL if Windows, or Microsoft GDK.
    #if !defined(SDL_PLATFORM_WINDOWS)
    if (pfnBeginThread || pfnEndThread) {
        SDL_SetError("_beginthreadex/_endthreadex not supported on this platform");
        return NULL;
    }
    #endif
    SDL_ThreadFunction fn = (SDL_ThreadFunction) SDL_GetPointerProperty(props, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, NULL);
    const char *name = SDL_GetStringProperty(props, SDL_PROP_THREAD_CREATE_NAME_STRING, NULL);
    const size_t stacksize = (size_t) SDL_GetNumberProperty(props, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, 0);
    void *userdata = SDL_GetPointerProperty(props, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, NULL);
    if (!fn) {
        SDL_SetError("Thread entry function is NULL");
        return NULL;
    }
    SDL_InitMainThread();
    SDL_Thread *thread = (SDL_Thread *)SDL_calloc(1, sizeof(*thread));
    if (!thread) {
        return NULL;
    }
    thread->status = -1;
    SDL_SetAtomicInt(&thread->state, SDL_THREAD_ALIVE);
    // Set up the arguments for the thread
    if (name) {
        thread->name = SDL_strdup(name);
        if (!thread->name) {
            SDL_free(thread);
            return NULL;
        }
    }
    thread->userfunc = fn;
    thread->userdata = userdata;
    thread->stacksize = stacksize;
    SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, true);
    // Create the thread and go!
    if (!SDL_SYS_CreateThread(thread, pfnBeginThread, pfnEndThread)) {
        // Oops, failed.  Gotta free everything
        SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, false);
        SDL_free(thread->name);
        SDL_free(thread);
        thread = NULL;
    }
    // Everything is running now
    return thread;
}
References NULL, SDL_calloc(), SDL_free(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetStringProperty(), SDL_InitMainThread(), SDL_OBJECT_TYPE_THREAD, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, SDL_PROP_THREAD_CREATE_NAME_STRING, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, SDL_SetAtomicInt(), SDL_SetError(), SDL_SetObjectValid(), SDL_strdup(), SDL_SYS_CreateThread(), SDL_THREAD_ALIVE, SDL_Thread::status, and SDL_TLSEntry::thread.
Referenced by SDL_CreateThreadRuntime().
SDL_CreateThreadWithStackSize()
SDL_Thread * SDL_CreateThreadWithStackSize (SDL_ThreadFunction fn, const char * name, size_t stacksize, void * userdata)
{
    const SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, (void *) fn);
    SDL_SetStringProperty(props, SDL_PROP_THREAD_CREATE_NAME_STRING, name);
    SDL_SetPointerProperty(props, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, userdata);
    SDL_SetNumberProperty(props, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, (Sint64) stacksize);
    SDL_Thread *thread = SDL_CreateThreadWithProperties(props);
    SDL_DestroyProperties(props);
    return thread;
}
References SDL_CreateProperties(), SDL_CreateThreadWithProperties, SDL_DestroyProperties(), SDL_PROP_THREAD_CREATE_ENTRY_FUNCTION_POINTER, SDL_PROP_THREAD_CREATE_NAME_STRING, SDL_PROP_THREAD_CREATE_STACKSIZE_NUMBER, SDL_PROP_THREAD_CREATE_USERDATA_POINTER, SDL_SetNumberProperty(), SDL_SetPointerProperty(), SDL_SetStringProperty(), and SDL_TLSEntry::thread.
SDL_DetachThread()
void SDL_DetachThread (SDL_Thread * thread)
Let a thread clean up on exit without intervention.
A thread may be "detached" to signify that it should not remain until another thread has called SDL_WaitThread() on it. Detaching a thread is useful for long-running threads that nothing needs to synchronize with or further manage. When a detached thread is done, it simply goes away.
There is no way to recover the return code of a detached thread. If you need this, don't detach the thread and instead use SDL_WaitThread().
Once a thread is detached, you should usually assume the SDL_Thread isn't safe to reference again, as it will become invalid immediately upon the detached thread's exit, instead of remaining until someone has called SDL_WaitThread() to finally clean it up. As such, don't detach the same thread more than once.
If a thread has already exited when passed to SDL_DetachThread(), it will stop waiting for a call to SDL_WaitThread() and clean up immediately. It is not safe to detach a thread that might be used with SDL_WaitThread().
You may not call SDL_WaitThread() on a thread that has been detached. Use either that function or this one, but not both, or behavior is undefined.
It is safe to pass NULL to this function; it is a no-op.
Parameters
thread the SDL_Thread pointer that was returned from the SDL_CreateThread() call that started this thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateThread
SDL_WaitThread
{
    if (!ThreadValid(thread)) {
        return;
    }
    // The thread may vanish at any time, it's no longer valid
    SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, false);
    // Grab dibs if the state is alive+joinable.
    if (SDL_CompareAndSwapAtomicInt(&thread->state, SDL_THREAD_ALIVE, SDL_THREAD_DETACHED)) {
        SDL_SYS_DetachThread(thread);
    } else {
        // all other states are pretty final, see where we landed.
        SDL_ThreadState thread_state = SDL_GetThreadState(thread);
        if (thread_state == SDL_THREAD_DETACHED) {
            return; // already detached (you shouldn't call this twice!)
        } else if (thread_state == SDL_THREAD_COMPLETE) {
            SDL_WaitThread(thread, NULL); // already done, clean it up.
        }
    }
}
References NULL, SDL_CompareAndSwapAtomicInt(), SDL_GetThreadState(), SDL_OBJECT_TYPE_THREAD, SDL_SetObjectValid(), SDL_SYS_DetachThread(), SDL_THREAD_ALIVE, SDL_THREAD_COMPLETE, SDL_THREAD_DETACHED, SDL_WaitThread(), SDL_TLSEntry::thread, and ThreadValid().
Referenced by MaybeSpinNewWorkerThread(), SDL_Zenity_ShowFileDialogWithProperties(), ShowFileDialog(), and ShowFolderDialog().
SDL_FreeErrBuf()
void SDLCALL SDL_FreeErrBuf (void * data) static
{
    SDL_error *errbuf = (SDL_error *)data;
    if (errbuf->str) {
        errbuf->free_func(errbuf->str);
    }
    errbuf->free_func(errbuf);
}
References SDL_error::free_func, SDLCALL, and SDL_error::str.
Referenced by SDL_GetErrBuf().
SDL_Generic_GetTLSData()
SDL_TLSData * SDL_Generic_GetTLSData (void)
{
    SDL_ThreadID thread = SDL_GetCurrentThreadID();
    SDL_TLSEntry *entry;
    SDL_TLSData *storage = NULL;
    SDL_LockMutex(SDL_generic_TLS_mutex);
    for (entry = SDL_generic_TLS; entry; entry = entry->next) {
        if (entry->thread == thread) {
            storage = entry->storage;
            break;
        }
    }
    SDL_UnlockMutex(SDL_generic_TLS_mutex);
    return storage;
}
References SDL_TLSEntry::next, NULL, SDL_generic_TLS, SDL_generic_TLS_mutex, SDL_GetCurrentThreadID(), SDL_LockMutex(), SDL_UnlockMutex(), SDL_TLSEntry::storage, and SDL_TLSEntry::thread.
Referenced by SDL_SYS_GetTLSData().
SDL_Generic_InitTLSData()
void SDL_Generic_InitTLSData (void)
{
    if (!SDL_generic_TLS_mutex) {
        SDL_generic_TLS_mutex = SDL_CreateMutex();
    }
}
References SDL_CreateMutex(), and SDL_generic_TLS_mutex.
Referenced by SDL_SYS_InitTLSData().
SDL_Generic_QuitTLSData()
void SDL_Generic_QuitTLSData (void)
{
    SDL_TLSEntry *entry;
    // This should have been cleaned up by the time we get here
    SDL_assert(!SDL_generic_TLS);
    if (SDL_generic_TLS) {
        SDL_LockMutex(SDL_generic_TLS_mutex);
        for (entry = SDL_generic_TLS; entry; ) {
            SDL_TLSEntry *next = entry->next;
            SDL_free(entry->storage);
            SDL_free(entry);
            entry = next;
        }
        SDL_generic_TLS = NULL;
        SDL_UnlockMutex(SDL_generic_TLS_mutex);
    }
    if (SDL_generic_TLS_mutex) {
        SDL_DestroyMutex(SDL_generic_TLS_mutex);
        SDL_generic_TLS_mutex = NULL;
    }
}
References SDL_TLSEntry::next, NULL, SDL_assert, SDL_DestroyMutex(), SDL_free(), SDL_generic_TLS, SDL_generic_TLS_mutex, SDL_LockMutex(), SDL_UnlockMutex(), and SDL_TLSEntry::storage.
Referenced by SDL_SYS_QuitTLSData().
SDL_Generic_SetTLSData()
bool SDL_Generic_SetTLSData (SDL_TLSData * data)
{
    SDL_ThreadID thread = SDL_GetCurrentThreadID();
    SDL_TLSEntry *prev, *entry;
    bool result = true;
    SDL_LockMutex(SDL_generic_TLS_mutex);
    prev = NULL;
    for (entry = SDL_generic_TLS; entry; entry = entry->next) {
        if (entry->thread == thread) {
            if (data) {
                entry->storage = data;
            } else {
                if (prev) {
                    prev->next = entry->next;
                } else {
                    SDL_generic_TLS = entry->next;
                }
                SDL_free(entry);
            }
            break;
        }
        prev = entry;
    }
    if (!entry && data) {
        entry = (SDL_TLSEntry *)SDL_malloc(sizeof(*entry));
        if (entry) {
            entry->thread = thread;
            entry->storage = data;
            entry->next = SDL_generic_TLS;
            SDL_generic_TLS = entry;
        } else {
            result = false;
        }
    }
    SDL_UnlockMutex(SDL_generic_TLS_mutex);
    return result;
}
References SDL_TLSEntry::next, NULL, SDL_free(), SDL_generic_TLS, SDL_generic_TLS_mutex, SDL_GetCurrentThreadID(), SDL_LockMutex(), SDL_malloc(), SDL_UnlockMutex(), SDL_TLSEntry::storage, and SDL_TLSEntry::thread.
Referenced by SDL_SYS_SetTLSData().
SDL_GetErrBuf()
SDL_error * SDL_GetErrBuf (bool create)
{
#ifdef SDL_THREADS_DISABLED
    return SDL_GetStaticErrBuf();
#else
    static SDL_TLSID tls_errbuf;
    SDL_error *errbuf;
    errbuf = (SDL_error *)SDL_GetTLS(&tls_errbuf);
    if (!errbuf) {
        if (!create) {
            return NULL;
        }
        /* Get the original memory functions for this allocation because the lifetime
         * of the error buffer may span calls to SDL_SetMemoryFunctions() by the app
         */
        SDL_realloc_func realloc_func;
        SDL_free_func free_func;
        SDL_GetOriginalMemoryFunctions(NULL, NULL, &realloc_func, &free_func);
        errbuf = (SDL_error *)realloc_func(NULL, sizeof(*errbuf));
        if (!errbuf) {
            return SDL_GetStaticErrBuf();
        }
        SDL_zerop(errbuf);
        errbuf->realloc_func = realloc_func;
        errbuf->free_func = free_func;
        SDL_SetTLS(&tls_errbuf, errbuf, SDL_FreeErrBuf);
    }
    return errbuf;
#endif // SDL_THREADS_DISABLED
}
References free_func, SDL_error::free_func, NULL, realloc_func, SDL_error::realloc_func, SDL_FreeErrBuf(), SDL_GetOriginalMemoryFunctions(), SDL_GetStaticErrBuf(), SDL_GetTLS(), SDL_SetTLS(), and SDL_zerop.
Referenced by SDL_ClearError(), SDL_GetError(), SDL_OutOfMemory(), and SDL_SetErrorV().
SDL_GetStaticErrBuf()
SDL_error * SDL_GetStaticErrBuf (void) static
{
    static SDL_error SDL_global_error;
    static char SDL_global_error_str[128];
    SDL_global_error.str = SDL_global_error_str;
    SDL_global_error.len = sizeof(SDL_global_error_str);
    return &SDL_global_error;
}
References SDL_error::len, and SDL_error::str.
Referenced by SDL_GetErrBuf().
SDL_GetThreadID()
SDL_ThreadID SDL_GetThreadID (SDL_Thread * thread)
Get the thread identifier for the specified thread.
This thread identifier is as reported by the underlying operating system. If SDL is running on a platform that does not support threads the return value will always be zero.
Parameters
thread the thread to query.
Returns
the ID of the specified thread, or the ID of the current thread if thread is NULL.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCurrentThreadID
{
    SDL_ThreadID id = 0;
    if (thread) {
        if (ThreadValid(thread)) {
            id = thread->threadid;
        }
    } else {
        id = SDL_GetCurrentThreadID();
    }
    return id;
}
References SDL_GetCurrentThreadID(), SDL_TLSEntry::thread, and ThreadValid().
SDL_GetThreadName()
const char * SDL_GetThreadName (SDL_Thread * thread)
Get the thread name as it was specified in SDL_CreateThread().
Parameters
thread the thread to query.
Returns
a pointer to a UTF-8 string that names the specified thread, or NULL if it doesn't have a name.
Since
This function is available since SDL 3.2.0.
{
    if (ThreadValid(thread)) {
        return SDL_GetPersistentString(thread->name);
    } else {
        return NULL;
    }
}
References NULL, SDL_GetPersistentString(), SDL_TLSEntry::thread, and ThreadValid().
SDL_GetThreadState()
SDL_ThreadState SDL_GetThreadState (SDL_Thread * thread)
Get the current state of a thread.
Parameters
thread the thread to query.
Returns
the current state of a thread, or SDL_THREAD_UNKNOWN if the thread isn't valid.
Since
This function is available since SDL 3.2.0.
See also
SDL_ThreadState
{
    if (!ThreadValid(thread)) {
        return SDL_THREAD_UNKNOWN;
    }
    return (SDL_ThreadState)SDL_GetAtomicInt(&thread->state);
}
References SDL_GetAtomicInt(), SDL_THREAD_UNKNOWN, SDL_TLSEntry::thread, and ThreadValid().
Referenced by SDL_DetachThread(), and SDL_RunThread().
SDL_GetTLS()
void * SDL_GetTLS (SDL_TLSID * id)
Get the current thread's value associated with a thread local storage ID.
Parameters
id a pointer to the thread local storage ID, may not be NULL.
Returns
the value associated with the ID for the current thread or NULL if no value has been set; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTLS
{
    SDL_TLSData *storage;
    int storage_index;
    if (id == NULL) {
        SDL_InvalidParamError("id");
        return NULL;
    }
    storage_index = SDL_GetAtomicInt(id) - 1;
    storage = SDL_SYS_GetTLSData();
    if (!storage || storage_index < 0 || storage_index >= storage->limit) {
        return NULL;
    }
    return storage->array[storage_index].data;
}
References SDL_TLSData::array, SDL_TLSData::data, SDL_TLSData::limit, NULL, SDL_GetAtomicInt(), SDL_InvalidParamError, and SDL_SYS_GetTLSData().
Referenced by SDL_GetErrBuf(), SDL_GetPersistentString(), SDL_GetTemporaryMemoryState(), SDL_GL_GetCurrentContext(), and SDL_GL_GetCurrentWindow().
SDL_InitTLSData()
void SDL_InitTLSData (void)
{
    SDL_SYS_InitTLSData();
}
References SDL_SYS_InitTLSData().
Referenced by SDL_InitMainThread(), and SDL_SetTLS().
SDL_QuitTLSData()
void SDL_QuitTLSData (void)
{
    SDL_CleanupTLS();
    if (SDL_GetAtomicInt(&SDL_tls_allocated) == 0) {
        SDL_SYS_QuitTLSData();
    } else {
        // Some thread hasn't called SDL_CleanupTLS()
    }
}
References SDL_CleanupTLS(), SDL_GetAtomicInt(), SDL_SYS_QuitTLSData(), and SDL_tls_allocated.
Referenced by SDL_QuitMainThread().
SDL_RunThread()
void SDL_RunThread (SDL_Thread * thread)
{
    void *userdata = thread->userdata;
    int(SDLCALL *userfunc)(void *) = thread->userfunc;
    int *statusloc = &thread->status;
    // Perform any system-dependent setup - this function may not fail
    SDL_SYS_SetupThread(thread->name);
    // Get the thread id
    thread->threadid = SDL_GetCurrentThreadID();
    // Run the function
    *statusloc = userfunc(userdata);
    // Clean up thread-local storage
    SDL_CleanupTLS();
    // Mark us as ready to be joined (or detached)
    if (!SDL_CompareAndSwapAtomicInt(&thread->state, SDL_THREAD_ALIVE, SDL_THREAD_COMPLETE)) {
        // Clean up if something already detached us.
        if (SDL_GetThreadState(thread) == SDL_THREAD_DETACHED) {
            SDL_free(thread->name); // Can't free later, we've already cleaned up TLS
            SDL_free(thread);
        }
    }
}
References SDL_CleanupTLS(), SDL_CompareAndSwapAtomicInt(), SDL_free(), SDL_GetCurrentThreadID(), SDL_GetThreadState(), SDL_SYS_SetupThread(), SDL_THREAD_ALIVE, SDL_THREAD_COMPLETE, SDL_THREAD_DETACHED, SDLCALL, and SDL_TLSEntry::thread.
Referenced by RunThread().
SDL_SetCurrentThreadPriority()
bool SDL_SetCurrentThreadPriority (SDL_ThreadPriority priority)
Set the priority for the current thread.
Note that some platforms will not let you alter the priority (or at least, promote the thread to a higher priority) at all, and some require you to be an administrator account. Be prepared for this to fail.
Parameters
priority the SDL_ThreadPriority to set.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.2.0.
{
    return SDL_SYS_SetThreadPriority(priority);
}
References SDL_SYS_SetThreadPriority().
Referenced by SDL_AudioThreadInit_Default(), and SDL_CameraThreadSetup().
SDL_SetInitialized()
void SDL_SetInitialized (SDL_InitState * state, bool initialized)
Finish an initialization state transition.
This function sets the status of the passed in state to SDL_INIT_STATUS_INITIALIZED or SDL_INIT_STATUS_UNINITIALIZED and allows any threads waiting for the status to proceed.
Parameters
state the initialization state to check.
initialized the new initialization state.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ShouldInit
SDL_ShouldQuit
{
    SDL_assert(state->thread == SDL_GetCurrentThreadID());
    if (initialized) {
        SDL_SetAtomicInt(&state->status, SDL_INIT_STATUS_INITIALIZED);
    } else {
        SDL_SetAtomicInt(&state->status, SDL_INIT_STATUS_UNINITIALIZED);
    }
}
References SDL_assert, SDL_GetCurrentThreadID(), SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_UNINITIALIZED, SDL_SetAtomicInt(), SDL_InitState::status, and SDL_InitState::thread.
Referenced by PrepareThreadpool(), SDL_GetPixelFormatDetails(), SDL_InitLog(), SDL_InitProperties(), SDL_InitTimers(), SDL_QuitLog(), SDL_QuitPixelFormatDetails(), SDL_QuitProperties(), SDL_QuitTimers(), SDL_SetObjectsInvalid(), SDL_SetObjectValid(), SDL_SetupAudioResampler(), and ShutdownThreadpool().
SDL_SetTLS()
bool SDL_SetTLS (SDL_TLSID * id, const void * value, SDL_TLSDestructorCallback destructor)
Set the current thread's value associated with a thread local storage ID.
If the thread local storage ID is not initialized (the value is 0), a new ID will be created in a thread-safe way, so all calls using a pointer to the same ID will refer to the same local storage.
Note that replacing a value from a previous call to this function on the same thread does not call the previous value's destructor!
destructor can be NULL; it is assumed that value does not need to be cleaned up if so.
Parameters
id a pointer to the thread local storage ID, may not be NULL.
value the value to associate with the ID for the current thread.
destructor a function called when the thread exits, to free the value, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTLS
{
    SDL_TLSData *storage;
    int storage_index;
    if (id == NULL) {
        return SDL_InvalidParamError("id");
    }
    /* Make sure TLS is initialized.
     * There's a race condition here if you are calling this from non-SDL threads
     * and haven't called SDL_Init() on your main thread, but such is life.
     */
    SDL_InitTLSData();
    // Get the storage index associated with the ID in a thread-safe way
    storage_index = SDL_GetAtomicInt(id) - 1;
    if (storage_index < 0) {
        int new_id = (SDL_AtomicIncRef(&SDL_tls_id) + 1);
        SDL_CompareAndSwapAtomicInt(id, 0, new_id);
        /* If there was a race condition we'll have wasted an ID, but every thread
         * will have the same storage index for this id.
         */
        storage_index = SDL_GetAtomicInt(id) - 1;
    }
    // Get the storage for the current thread
    storage = SDL_SYS_GetTLSData();
    if (!storage || storage_index >= storage->limit) {
        unsigned int i, oldlimit, newlimit;
        SDL_TLSData *new_storage;
        oldlimit = storage ? storage->limit : 0;
        newlimit = (storage_index + TLS_ALLOC_CHUNKSIZE);
        new_storage = (SDL_TLSData *)SDL_realloc(storage, sizeof(*storage) + (newlimit - 1) * sizeof(storage->array[0]));
        if (!new_storage) {
            return false;
        }
        storage = new_storage;
        storage->limit = newlimit;
        for (i = oldlimit; i < newlimit; ++i) {
            storage->array[i].data = NULL;
            storage->array[i].destructor = NULL;
        }
        if (!SDL_SYS_SetTLSData(storage)) {
            SDL_free(storage);
            return false;
        }
        SDL_AtomicIncRef(&SDL_tls_allocated);
    }
    storage->array[storage_index].data = SDL_const_cast(void *, value);
    storage->array[storage_index].destructor = destructor;
    return true;
}
References SDL_TLSData::array, SDL_TLSData::data, SDL_TLSData::limit, NULL, SDL_AtomicIncRef, SDL_CompareAndSwapAtomicInt(), SDL_const_cast, SDL_free(), SDL_GetAtomicInt(), SDL_InitTLSData(), SDL_InvalidParamError, SDL_realloc(), SDL_SYS_GetTLSData(), SDL_SYS_SetTLSData(), SDL_tls_allocated, SDL_tls_id, and TLS_ALLOC_CHUNKSIZE.
Referenced by SDL_GetErrBuf(), SDL_GetPersistentString(), SDL_GetTemporaryMemoryState(), SDL_GL_CreateContext(), and SDL_GL_MakeCurrent().
SDL_ShouldInit()
bool SDL_ShouldInit (SDL_InitState * state)
Return whether initialization should be done.
This function checks the passed in state and if initialization should be done, sets the status to SDL_INIT_STATUS_INITIALIZING and returns true. If another thread is already modifying this state, it will wait until that's done before returning.
If this function returns true, the calling code must call SDL_SetInitialized() to complete the initialization.
Parameters
state the initialization state to check.
Returns
true if initialization needs to be done, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetInitialized
SDL_ShouldQuit
{
    while (SDL_GetAtomicInt(&state->status) != SDL_INIT_STATUS_INITIALIZED) {
        if (SDL_CompareAndSwapAtomicInt(&state->status, SDL_INIT_STATUS_UNINITIALIZED, SDL_INIT_STATUS_INITIALIZING)) {
            state->thread = SDL_GetCurrentThreadID();
            return true;
        }
        // Wait for the other thread to complete transition
        SDL_Delay(1);
    }
    return false;
}
References SDL_CompareAndSwapAtomicInt(), SDL_Delay(), SDL_GetAtomicInt(), SDL_GetCurrentThreadID(), SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_INITIALIZING, SDL_INIT_STATUS_UNINITIALIZED, SDL_InitState::status, and SDL_InitState::thread.
Referenced by PrepareThreadpool(), SDL_GetPixelFormatDetails(), SDL_InitLog(), SDL_InitProperties(), SDL_InitTimers(), SDL_SetObjectValid(), and SDL_SetupAudioResampler().
SDL_ShouldQuit()
bool SDL_ShouldQuit (SDL_InitState * state)
Return whether cleanup should be done.
This function checks the passed in state and if cleanup should be done, sets the status to SDL_INIT_STATUS_UNINITIALIZING and returns true.
If this function returns true, the calling code must call SDL_SetInitialized() to complete the cleanup.
Parameters
state the initialization state to check.
Returns
true if cleanup needs to be done, false otherwise.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetInitialized
SDL_ShouldInit
{
    while (SDL_GetAtomicInt(&state->status) != SDL_INIT_STATUS_UNINITIALIZED) {
        if (SDL_CompareAndSwapAtomicInt(&state->status, SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_UNINITIALIZING)) {
            state->thread = SDL_GetCurrentThreadID();
            return true;
        }
        // Wait for the other thread to complete transition
        SDL_Delay(1);
    }
    return false;
}
References SDL_CompareAndSwapAtomicInt(), SDL_Delay(), SDL_GetAtomicInt(), SDL_GetCurrentThreadID(), SDL_INIT_STATUS_INITIALIZED, SDL_INIT_STATUS_UNINITIALIZED, SDL_INIT_STATUS_UNINITIALIZING, SDL_InitState::status, and SDL_InitState::thread.
Referenced by SDL_QuitLog(), SDL_QuitPixelFormatDetails(), SDL_QuitProperties(), SDL_QuitTimers(), SDL_SetObjectsInvalid(), and ShutdownThreadpool().
SDL_TryWaitSemaphore()
bool SDL_TryWaitSemaphore (SDL_Semaphore * sem)
See if a semaphore has a positive value and decrement it if it does.
This function checks to see if the semaphore pointed to by sem has a positive value and atomically decrements the semaphore value if it does. If the semaphore doesn't have a positive value, the function immediately returns false.
Parameters
sem the semaphore to wait on.
Returns
true if the wait succeeds, false if the wait would block.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalSemaphore
SDL_WaitSemaphore
SDL_WaitSemaphoreTimeout
{
    return SDL_WaitSemaphoreTimeoutNS(sem, 0);
}
References SDL_WaitSemaphoreTimeoutNS().
Referenced by SDL_TryLockMutex().
SDL_WaitCondition()
void SDL_WaitCondition (SDL_Condition * cond, SDL_Mutex * mutex)
Wait until a condition variable is signaled.
This function unlocks the specified mutex and waits for another thread to call SDL_SignalCondition() or SDL_BroadcastCondition() on the condition variable cond. Once the condition variable is signaled, the mutex is re-locked and the function returns.
The mutex must be locked before calling this function. Locking the mutex recursively (more than once) is not supported and leads to undefined behavior.
This function is the equivalent of calling SDL_WaitConditionTimeout() with a time length of -1.
Parameters
cond the condition variable to wait on.
mutex the mutex used to coordinate thread access.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitConditionTimeout
{
    SDL_WaitConditionTimeoutNS(cond, mutex, -1);
}
References SDL_WaitConditionTimeoutNS().
Referenced by hidapi_thread_cond_wait(), SDL_LockRWLockForWriting(), SDL_WaitThreadBarrier(), SerializePhysicalDeviceClose(), and ShutdownThreadpool().
SDL_WaitConditionTimeout()
bool SDL_WaitConditionTimeout (SDL_Condition * cond, SDL_Mutex * mutex, Sint32 timeoutMS)
Wait until a condition variable is signaled or a certain time has passed.
This function unlocks the specified mutex and waits for another thread to call SDL_SignalCondition() or SDL_BroadcastCondition() on the condition variable cond, or for the specified time to elapse. Once the condition variable is signaled or the time elapsed, the mutex is re-locked and the function returns.
The mutex must be locked before calling this function. Locking the mutex recursively (more than once) is not supported and leads to undefined behavior.
Parameters
cond the condition variable to wait on.
mutex the mutex used to coordinate thread access.
timeoutMS the maximum time to wait, in milliseconds, or -1 to wait indefinitely.
Returns
true if the condition variable is signaled, false if the condition is not signaled in the allotted time.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_BroadcastCondition
SDL_SignalCondition
SDL_WaitCondition
{
    Sint64 timeoutNS;
    if (timeoutMS >= 0) {
        timeoutNS = SDL_MS_TO_NS(timeoutMS);
    } else {
        timeoutNS = -1;
    }
    return SDL_WaitConditionTimeoutNS(cond, mutex, timeoutNS);
}
References SDL_MS_TO_NS, and SDL_WaitConditionTimeoutNS().
Referenced by AsyncIOThreadpoolWorker(), generic_asyncioqueue_wait_results(), and hidapi_thread_cond_timedwait().
SDL_WaitSemaphore()
void SDL_WaitSemaphore (SDL_Semaphore * sem)
Wait until a semaphore has a positive value and then decrements it.
This function suspends the calling thread until the semaphore pointed to by sem has a positive value, and then atomically decrement the semaphore value.
This function is the equivalent of calling SDL_WaitSemaphoreTimeout() with a time length of -1.
Parameters
sem the semaphore wait on.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalSemaphore
SDL_TryWaitSemaphore
SDL_WaitSemaphoreTimeout
{
    SDL_WaitSemaphoreTimeoutNS(sem, -1);
}
References SDL_WaitSemaphoreTimeoutNS().
Referenced by SDL_BroadcastCondition(), SDL_LockMutex(), SDL_RunOnMainThread(), SDL_SignalCondition(), and SDL_WaitConditionTimeoutNS_generic().
SDL_WaitSemaphoreTimeout()
bool SDL_WaitSemaphoreTimeout (SDL_Semaphore * sem, Sint32 timeoutMS)
Wait until a semaphore has a positive value and then decrements it.
This function suspends the calling thread until either the semaphore pointed to by sem has a positive value or the specified time has elapsed. If the call is successful it will atomically decrement the semaphore value.
Parameters
sem the semaphore to wait on.
timeoutMS the length of the timeout, in milliseconds, or -1 to wait indefinitely.
Returns
true if the wait succeeds or false if the wait times out.
Since
This function is available since SDL 3.2.0.
See also
SDL_SignalSemaphore
SDL_TryWaitSemaphore
SDL_WaitSemaphore
{
    Sint64 timeoutNS;
    if (timeoutMS >= 0) {
        timeoutNS = SDL_MS_TO_NS(timeoutMS);
    } else {
        timeoutNS = -1;
    }
    return SDL_WaitSemaphoreTimeoutNS(sem, timeoutNS);
}
References SDL_MS_TO_NS, and SDL_WaitSemaphoreTimeoutNS().
SDL_WaitThread()
void SDL_WaitThread (SDL_Thread * thread, int * status)
Wait for a thread to finish.
Threads that haven't been detached will remain until this function cleans them up. Not doing so is a resource leak.
Once a thread has been cleaned up through this function, the SDL_Thread that references it becomes invalid and should not be referenced again. As such, only one thread may call SDL_WaitThread() on another.
The return code from the thread function is placed in the area pointed to by status, if status is not NULL.
You may not wait on a thread that has been used in a call to SDL_DetachThread(). Use either that function or this one, but not both, or behavior is undefined.
It is safe to pass a NULL thread to this function; it is a no-op.
Note that the thread pointer is freed by this function and is not valid afterward.
Parameters
thread the SDL_Thread pointer that was returned from the SDL_CreateThread() call that started this thread.
status a pointer filled in with the value returned from the thread function by its 'return', or -1 if the thread has been detached or isn't valid, may be NULL.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateThread
SDL_DetachThread
{
    if (!ThreadValid(thread)) {
        if (status) {
            *status = -1;
        }
        return;
    }
    SDL_SYS_WaitThread(thread);
    if (status) {
        *status = thread->status;
    }
    SDL_SetObjectValid(thread, SDL_OBJECT_TYPE_THREAD, false);
    SDL_free(thread->name);
    SDL_free(thread);
}
References SDL_free(), SDL_OBJECT_TYPE_THREAD, SDL_SetObjectValid(), SDL_SYS_WaitThread(), SDL_TLSEntry::thread, and ThreadValid().
Referenced by ClosePhysicalAudioDevice(), ClosePhysicalCamera(), hidapi_thread_join(), SDL_DetachThread(), and SDL_QuitTimers().
ThreadValid()
bool ThreadValid (SDL_Thread * thread) static
{
    return SDL_ObjectValid(thread, SDL_OBJECT_TYPE_THREAD);
}
References SDL_OBJECT_TYPE_THREAD, SDL_ObjectValid(), and SDL_TLSEntry::thread.
Referenced by SDL_DetachThread(), SDL_GetThreadID(), SDL_GetThreadName(), SDL_GetThreadState(), and SDL_WaitThread().
Variable Documentation
SDL_generic_TLS
SDL_TLSEntry* SDL_generic_TLS static
Referenced by SDL_Generic_GetTLSData(), SDL_Generic_QuitTLSData(), and SDL_Generic_SetTLSData().
SDL_generic_TLS_mutex
SDL_Mutex* SDL_generic_TLS_mutex static
Referenced by SDL_Generic_GetTLSData(), SDL_Generic_InitTLSData(), SDL_Generic_QuitTLSData(), and SDL_Generic_SetTLSData().
SDL_tls_allocated
SDL_AtomicInt SDL_tls_allocated static
Referenced by SDL_CleanupTLS(), SDL_QuitTLSData(), and SDL_SetTLS().
SDL_tls_id
SDL_AtomicInt SDL_tls_id static
Referenced by SDL_SetTLS().