SDL3: SDL-main/src/render/SDL_render.c File Reference
SDL_render.c File Reference
#include "SDL_internal.h"
#include "SDL_sysrender.h"
#include "SDL_render_debug_font.h"
#include "software/SDL_render_sw_c.h"
#include "../events/SDL_windowevents_c.h"
#include "../video/SDL_pixels_c.h"
#include "../video/SDL_video_c.h"
Macros
#define ADD_TRIANGLE(i1, i2, i3)
#define CHECK_RENDERER_MAGIC(renderer, result)
#define CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG(renderer, result)
#define CHECK_TEXTURE_MAGIC(texture, result)
#define DONT_DRAW_WHILE_HIDDEN 0
#define SDL_BLENDMODE_ADD_FULL
#define SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL
#define SDL_BLENDMODE_BLEND_FULL
#define SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL
#define SDL_BLENDMODE_MOD_FULL
#define SDL_BLENDMODE_MUL_FULL
#define SDL_BLENDMODE_NONE_FULL
#define SDL_COMPOSE_BLENDMODE(srcColorFactor, dstColorFactor, colorOperation, srcAlphaFactor, dstAlphaFactor, alphaOperation)
#define SDL_DEBUG_FONT_GLYPHS_PER_ROW 14
#define SDL_PROP_TEXTURE_PARENT_POINTER "SDL.internal.texture.parent"
#define SDL_PROP_WINDOW_RENDERER_POINTER "SDL.internal.window.renderer"
#define SETVAL(ptr, val)
Functions
static SDL_RenderCommand * AllocateRenderCommand (SDL_Renderer *renderer)
static bool CreateDebugTextAtlas (SDL_Renderer *renderer)
static SDL_INLINE void DebugLogRenderCommands (const SDL_RenderCommand *cmd)
static bool DrawDebugCharacter (SDL_Renderer *renderer, float x, float y, Uint32 c)
static bool FlushRenderCommands (SDL_Renderer *renderer)
static bool FlushRenderCommandsIfGPURenderStateNeeded (SDL_GPURenderState *state)
static bool FlushRenderCommandsIfTextureNeeded (SDL_Texture *texture)
static SDL_PixelFormat GetClosestSupportedFormat (SDL_Renderer *renderer, SDL_PixelFormat format)
static void GetRenderViewportSize (SDL_Renderer *renderer, SDL_FRect *rect)
static bool IsSupportedBlendMode (SDL_Renderer *renderer, SDL_BlendMode blendMode)
static bool IsSupportedFormat (SDL_Renderer *renderer, SDL_PixelFormat format)
static SDL_RenderCommand * PrepQueueCmdDraw (SDL_Renderer *renderer, const SDL_RenderCommandType cmdtype, SDL_Texture *texture)
static bool QueueCmdClear (SDL_Renderer *renderer)
static bool QueueCmdCopy (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, const SDL_FRect *dstrect)
static bool QueueCmdCopyEx (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcquad, const SDL_FRect *dstrect, const double angle, const SDL_FPoint *center, const SDL_FlipMode flip, float scale_x, float scale_y)
static bool QueueCmdDrawLines (SDL_Renderer *renderer, const SDL_FPoint *points, const int count)
static bool QueueCmdDrawPoints (SDL_Renderer *renderer, const SDL_FPoint *points, const int count)
static bool QueueCmdFillRects (SDL_Renderer *renderer, const SDL_FRect *rects, const int count)
static bool QueueCmdGeometry (SDL_Renderer *renderer, SDL_Texture *texture, const float *xy, int xy_stride, const SDL_FColor *color, int color_stride, const float *uv, int uv_stride, int num_vertices, const void *indices, int num_indices, int size_indices, float scale_x, float scale_y, SDL_TextureAddressMode texture_address_mode_u, SDL_TextureAddressMode texture_address_mode_v)
static bool QueueCmdSetClipRect (SDL_Renderer *renderer)
static bool QueueCmdSetDrawColor (SDL_Renderer *renderer, SDL_FColor *color)
static bool QueueCmdSetViewport (SDL_Renderer *renderer)
static bool RenderLineBresenham (SDL_Renderer *renderer, int x1, int y1, int x2, int y2, bool draw_last)
static bool RenderLinesWithRectsF (SDL_Renderer *renderer, const SDL_FPoint *points, const int count)
static bool RenderPointsWithRects (SDL_Renderer *renderer, const SDL_FPoint *fpoints, const int count)
bool SDL_AddSupportedTextureFormat (SDL_Renderer *renderer, SDL_PixelFormat format)
bool SDL_AddVulkanRenderSemaphores (SDL_Renderer *renderer, Uint32 wait_stage_mask, Sint64 wait_semaphore, Sint64 signal_semaphore)
void * SDL_AllocateRenderVertices (SDL_Renderer *renderer, size_t numbytes, size_t alignment, size_t *offset)
static void SDL_CalculateSimulatedVSyncInterval (SDL_Renderer *renderer, SDL_Window *window)
SDL_BlendMode SDL_ComposeCustomBlendMode (SDL_BlendFactor srcColorFactor, SDL_BlendFactor dstColorFactor, SDL_BlendOperation colorOperation, SDL_BlendFactor srcAlphaFactor, SDL_BlendFactor dstAlphaFactor, SDL_BlendOperation alphaOperation)
bool SDL_ConvertEventToRenderCoordinates (SDL_Renderer *renderer, SDL_Event *event)
void SDL_ConvertFromLinear (SDL_FColor *color)
void SDL_ConvertToLinear (SDL_FColor *color)
SDL_Renderer * SDL_CreateGPURenderer (SDL_Window *window, SDL_GPUShaderFormat format_flags, SDL_GPUDevice **device)
SDL_GPURenderState * SDL_CreateGPURenderState (SDL_Renderer *renderer, SDL_GPURenderStateDesc *desc)
SDL_Renderer * SDL_CreateRenderer (SDL_Window *window, const char *name)
SDL_Renderer * SDL_CreateRendererWithProperties (SDL_PropertiesID props)
SDL_Renderer * SDL_CreateSoftwareRenderer (SDL_Surface *surface)
SDL_Texture * SDL_CreateTexture (SDL_Renderer *renderer, SDL_PixelFormat format, SDL_TextureAccess access, int w, int h)
SDL_Texture * SDL_CreateTextureFromSurface (SDL_Renderer *renderer, SDL_Surface *surface)
SDL_Texture * SDL_CreateTextureWithProperties (SDL_Renderer *renderer, SDL_PropertiesID props)
bool SDL_CreateWindowAndRenderer (const char *title, int width, int height, SDL_WindowFlags window_flags, SDL_Window **window, SDL_Renderer **renderer)
void SDL_DestroyGPURenderState (SDL_GPURenderState *state)
void SDL_DestroyRenderer (SDL_Renderer *renderer)
void SDL_DestroyRendererWithoutFreeing (SDL_Renderer *renderer)
void SDL_DestroyTexture (SDL_Texture *texture)
static void SDL_DestroyTextureInternal (SDL_Texture *texture, bool is_destroying)
static void SDL_DiscardAllCommands (SDL_Renderer *renderer)
bool SDL_FlushRenderer (SDL_Renderer *renderer)
SDL_BlendOperation SDL_GetBlendModeAlphaOperation (SDL_BlendMode blendMode)
SDL_BlendOperation SDL_GetBlendModeColorOperation (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeDstAlphaFactor (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeDstColorFactor (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeSrcAlphaFactor (SDL_BlendMode blendMode)
SDL_BlendFactor SDL_GetBlendModeSrcColorFactor (SDL_BlendMode blendMode)
bool SDL_GetCurrentRenderOutputSize (SDL_Renderer *renderer, int *w, int *h)
bool SDL_GetDefaultTextureScaleMode (SDL_Renderer *renderer, SDL_ScaleMode *scale_mode)
static SDL_BlendMode SDL_GetLongBlendMode (SDL_BlendMode blendMode)
int SDL_GetNumRenderDrivers (void)
bool SDL_GetRenderClipRect (SDL_Renderer *renderer, SDL_Rect *rect)
bool SDL_GetRenderColorScale (SDL_Renderer *renderer, float *scale)
bool SDL_GetRenderDrawBlendMode (SDL_Renderer *renderer, SDL_BlendMode *blendMode)
bool SDL_GetRenderDrawColor (SDL_Renderer *renderer, Uint8 *r, Uint8 *g, Uint8 *b, Uint8 *a)
bool SDL_GetRenderDrawColorFloat (SDL_Renderer *renderer, float *r, float *g, float *b, float *a)
const char * SDL_GetRenderDriver (int index)
SDL_Renderer * SDL_GetRenderer (SDL_Window *window)
SDL_Renderer * SDL_GetRendererFromTexture (SDL_Texture *texture)
const char * SDL_GetRendererName (SDL_Renderer *renderer)
SDL_PropertiesID SDL_GetRendererProperties (SDL_Renderer *renderer)
static SDL_RenderLineMethod SDL_GetRenderLineMethod (void)
bool SDL_GetRenderLogicalPresentation (SDL_Renderer *renderer, int *w, int *h, SDL_RendererLogicalPresentation *mode)
bool SDL_GetRenderLogicalPresentationRect (SDL_Renderer *renderer, SDL_FRect *rect)
void * SDL_GetRenderMetalCommandEncoder (SDL_Renderer *renderer)
void * SDL_GetRenderMetalLayer (SDL_Renderer *renderer)
bool SDL_GetRenderOutputSize (SDL_Renderer *renderer, int *w, int *h)
bool SDL_GetRenderSafeArea (SDL_Renderer *renderer, SDL_Rect *rect)
bool SDL_GetRenderScale (SDL_Renderer *renderer, float *scaleX, float *scaleY)
SDL_Texture * SDL_GetRenderTarget (SDL_Renderer *renderer)
bool SDL_GetRenderTextureAddressMode (SDL_Renderer *renderer, SDL_TextureAddressMode *u_mode, SDL_TextureAddressMode *v_mode)
bool SDL_GetRenderViewport (SDL_Renderer *renderer, SDL_Rect *rect)
bool SDL_GetRenderVSync (SDL_Renderer *renderer, int *vsync)
SDL_Window * SDL_GetRenderWindow (SDL_Renderer *renderer)
static SDL_BlendMode SDL_GetShortBlendMode (SDL_BlendMode blendMode)
bool SDL_GetTextureAlphaMod (SDL_Texture *texture, Uint8 *alpha)
bool SDL_GetTextureAlphaModFloat (SDL_Texture *texture, float *alpha)
bool SDL_GetTextureBlendMode (SDL_Texture *texture, SDL_BlendMode *blendMode)
bool SDL_GetTextureColorMod (SDL_Texture *texture, Uint8 *r, Uint8 *g, Uint8 *b)
bool SDL_GetTextureColorModFloat (SDL_Texture *texture, float *r, float *g, float *b)
SDL_PropertiesID SDL_GetTextureProperties (SDL_Texture *texture)
bool SDL_GetTextureScaleMode (SDL_Texture *texture, SDL_ScaleMode *scaleMode)
bool SDL_GetTextureSize (SDL_Texture *texture, float *w, float *h)
bool SDL_LockTexture (SDL_Texture *texture, const SDL_Rect *rect, void **pixels, int *pitch)
static bool SDL_LockTextureNative (SDL_Texture *texture, const SDL_Rect *rect, void **pixels, int *pitch)
bool SDL_LockTextureToSurface (SDL_Texture *texture, const SDL_Rect *rect, SDL_Surface **surface)
void SDL_QuitRender (void)
static void SDL_RenderApplyWindowShape (SDL_Renderer *renderer)
bool SDL_RenderClear (SDL_Renderer *renderer)
bool SDL_RenderClipEnabled (SDL_Renderer *renderer)
bool SDL_RenderCoordinatesFromWindow (SDL_Renderer *renderer, float window_x, float window_y, float *x, float *y)
bool SDL_RenderCoordinatesToWindow (SDL_Renderer *renderer, float x, float y, float *window_x, float *window_y)
bool SDL_RenderDebugText (SDL_Renderer *renderer, float x, float y, const char *s)
bool SDL_RenderDebugTextFormat (SDL_Renderer *renderer, float x, float y, SDL_PRINTF_FORMAT_STRING const char *fmt,...)
static bool SDL_RendererEventWatch (void *userdata, SDL_Event *event)
bool SDL_RenderFillRect (SDL_Renderer *renderer, const SDL_FRect *rect)
bool SDL_RenderFillRects (SDL_Renderer *renderer, const SDL_FRect *rects, int count)
bool SDL_RenderGeometry (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_Vertex *vertices, int num_vertices, const int *indices, int num_indices)
bool SDL_RenderGeometryRaw (SDL_Renderer *renderer, SDL_Texture *texture, const float *xy, int xy_stride, const SDL_FColor *color, int color_stride, const float *uv, int uv_stride, int num_vertices, const void *indices, int num_indices, int size_indices)
bool SDL_RenderingLinearSpace (SDL_Renderer *renderer)
bool SDL_RenderLine (SDL_Renderer *renderer, float x1, float y1, float x2, float y2)
bool SDL_RenderLines (SDL_Renderer *renderer, const SDL_FPoint *points, int count)
static void SDL_RenderLogicalBorders (SDL_Renderer *renderer, const SDL_FRect *dst)
static void SDL_RenderLogicalPresentation (SDL_Renderer *renderer)
bool SDL_RenderPoint (SDL_Renderer *renderer, float x, float y)
bool SDL_RenderPoints (SDL_Renderer *renderer, const SDL_FPoint *points, int count)
bool SDL_RenderPresent (SDL_Renderer *renderer)
SDL_Surface * SDL_RenderReadPixels (SDL_Renderer *renderer, const SDL_Rect *rect)
bool SDL_RenderRect (SDL_Renderer *renderer, const SDL_FRect *rect)
bool SDL_RenderRects (SDL_Renderer *renderer, const SDL_FRect *rects, int count)
bool SDL_RenderTexture (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, const SDL_FRect *dstrect)
bool SDL_RenderTexture9Grid (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, float left_width, float right_width, float top_height, float bottom_height, float scale, const SDL_FRect *dstrect)
bool SDL_RenderTexture9GridTiled (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, float left_width, float right_width, float top_height, float bottom_height, float scale, const SDL_FRect *dstrect, float tileScale)
bool SDL_RenderTextureAffine (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, const SDL_FPoint *origin, const SDL_FPoint *right, const SDL_FPoint *down)
static bool SDL_RenderTextureInternal (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, const SDL_FRect *dstrect)
bool SDL_RenderTextureRotated (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, const SDL_FRect *dstrect, const double angle, const SDL_FPoint *center, const SDL_FlipMode flip)
bool SDL_RenderTextureTiled (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, float scale, const SDL_FRect *dstrect)
static bool SDL_RenderTextureTiled_Iterate (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, float scale, const SDL_FRect *dstrect)
static bool SDL_RenderTextureTiled_Wrap (SDL_Renderer *renderer, SDL_Texture *texture, const SDL_FRect *srcrect, float scale, const SDL_FRect *dstrect)
static bool SDL_RenderVectorFromWindow (SDL_Renderer *renderer, float window_dx, float window_dy, float *dx, float *dy)
bool SDL_RenderViewportSet (SDL_Renderer *renderer)
bool SDL_SetDefaultTextureScaleMode (SDL_Renderer *renderer, SDL_ScaleMode scale_mode)
bool SDL_SetGPURenderStateFragmentUniforms (SDL_GPURenderState *state, Uint32 slot_index, const void *data, Uint32 length)
bool SDL_SetRenderClipRect (SDL_Renderer *renderer, const SDL_Rect *rect)
bool SDL_SetRenderColorScale (SDL_Renderer *renderer, float scale)
bool SDL_SetRenderDrawBlendMode (SDL_Renderer *renderer, SDL_BlendMode blendMode)
bool SDL_SetRenderDrawColor (SDL_Renderer *renderer, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
bool SDL_SetRenderDrawColorFloat (SDL_Renderer *renderer, float r, float g, float b, float a)
bool SDL_SetRenderGPUState (SDL_Renderer *renderer, SDL_GPURenderState *state)
bool SDL_SetRenderLogicalPresentation (SDL_Renderer *renderer, int w, int h, SDL_RendererLogicalPresentation mode)
bool SDL_SetRenderScale (SDL_Renderer *renderer, float scaleX, float scaleY)
bool SDL_SetRenderTarget (SDL_Renderer *renderer, SDL_Texture *texture)
bool SDL_SetRenderTextureAddressMode (SDL_Renderer *renderer, SDL_TextureAddressMode u_mode, SDL_TextureAddressMode v_mode)
bool SDL_SetRenderViewport (SDL_Renderer *renderer, const SDL_Rect *rect)
bool SDL_SetRenderVSync (SDL_Renderer *renderer, int vsync)
bool SDL_SetTextureAlphaMod (SDL_Texture *texture, Uint8 alpha)
bool SDL_SetTextureAlphaModFloat (SDL_Texture *texture, float alpha)
bool SDL_SetTextureBlendMode (SDL_Texture *texture, SDL_BlendMode blendMode)
bool SDL_SetTextureColorMod (SDL_Texture *texture, Uint8 r, Uint8 g, Uint8 b)
bool SDL_SetTextureColorModFloat (SDL_Texture *texture, float r, float g, float b)
bool SDL_SetTextureScaleMode (SDL_Texture *texture, SDL_ScaleMode scaleMode)
void SDL_SetupRendererColorspace (SDL_Renderer *renderer, SDL_PropertiesID props)
static void SDL_SimulateRenderVSync (SDL_Renderer *renderer)
void SDL_UnlockTexture (SDL_Texture *texture)
static void SDL_UnlockTextureNative (SDL_Texture *texture)
bool SDL_UpdateNVTexture (SDL_Texture *texture, const SDL_Rect *rect, const Uint8 *Yplane, int Ypitch, const Uint8 *UVplane, int UVpitch)
bool SDL_UpdateTexture (SDL_Texture *texture, const SDL_Rect *rect, const void *pixels, int pitch)
static bool SDL_UpdateTextureFromSurface (SDL_Texture *texture, SDL_Rect *rect, SDL_Surface *surface)
static bool SDL_UpdateTextureNative (SDL_Texture *texture, const SDL_Rect *rect, const void *pixels, int pitch)
bool SDL_UpdateYUVTexture (SDL_Texture *texture, const SDL_Rect *rect, const Uint8 *Yplane, int Ypitch, const Uint8 *Uplane, int Upitch, const Uint8 *Vplane, int Vpitch)
static void UpdateColorScale (SDL_Renderer *renderer)
static void UpdateHDRProperties (SDL_Renderer *renderer)
static void UpdateLogicalPresentation (SDL_Renderer *renderer)
static void UpdateMainViewDimensions (SDL_Renderer *renderer)
static void UpdatePixelClipRect (SDL_Renderer *renderer, SDL_RenderViewState *view)
static void UpdatePixelViewport (SDL_Renderer *renderer, SDL_RenderViewState *view)
static SDL_INLINE void VerifyDrawQueueFunctions (const SDL_Renderer *renderer)
Variables
static const int rect_index_order [] = { 0, 1, 2, 0, 2, 3 }
static const SDL_RenderDriver * render_drivers []
static SDL_Renderer * SDL_renderers
Macro Definition Documentation
ADD_TRIANGLE
#define ADD_TRIANGLE (i1, i2, i3)
Value:
    *ptr_indices++ = cur_index + (i1);  \
    *ptr_indices++ = cur_index + (i2);  \
    *ptr_indices++ = cur_index + (i3);  \
    num_indices += 3;
Referenced by SDL_RenderLines().
CHECK_RENDERER_MAGIC
#define CHECK_RENDERER_MAGIC (renderer, result)
Value:
    CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG(renderer, result); \
    if ((renderer)->destroyed) { \
        SDL_SetError("Renderer's window has been destroyed, can't use further"); \
        return result;                                          \
    }
#define CHECK_RENDERER_MAGIC(renderer, result)                  \
    CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG(renderer, result); \
    if ((renderer)->destroyed) { \
        SDL_SetError("Renderer's window has been destroyed, can't use further"); \
        return result;                                          \
    }
Referenced by SDL_AddVulkanRenderSemaphores(), SDL_ConvertEventToRenderCoordinates(), SDL_CreateGPURenderState(), SDL_CreateTextureFromSurface(), SDL_CreateTextureWithProperties(), SDL_GetCurrentRenderOutputSize(), SDL_GetDefaultTextureScaleMode(), SDL_GetRenderClipRect(), SDL_GetRenderColorScale(), SDL_GetRenderDrawBlendMode(), SDL_GetRenderDrawColorFloat(), SDL_GetRendererName(), SDL_GetRendererProperties(), SDL_GetRenderLogicalPresentation(), SDL_GetRenderLogicalPresentationRect(), SDL_GetRenderMetalCommandEncoder(), SDL_GetRenderMetalLayer(), SDL_GetRenderOutputSize(), SDL_GetRenderSafeArea(), SDL_GetRenderScale(), SDL_GetRenderTarget(), SDL_GetRenderTextureAddressMode(), SDL_GetRenderViewport(), SDL_GetRenderVSync(), SDL_GetRenderWindow(), SDL_RenderClear(), SDL_RenderClipEnabled(), SDL_RenderCoordinatesFromWindow(), SDL_RenderCoordinatesToWindow(), SDL_RenderDebugText(), SDL_RenderFillRect(), SDL_RenderFillRects(), SDL_RenderGeometryRaw(), SDL_RenderLines(), SDL_RenderPoints(), SDL_RenderPresent(), SDL_RenderReadPixels(), SDL_RenderRect(), SDL_RenderRects(), SDL_RenderTexture(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), SDL_RenderTextureAffine(), SDL_RenderTextureRotated(), SDL_RenderTextureTiled(), SDL_RenderViewportSet(), SDL_SetDefaultTextureScaleMode(), SDL_SetRenderClipRect(), SDL_SetRenderColorScale(), SDL_SetRenderDrawBlendMode(), SDL_SetRenderDrawColorFloat(), SDL_SetRenderGPUState(), SDL_SetRenderLogicalPresentation(), SDL_SetRenderScale(), SDL_SetRenderTextureAddressMode(), SDL_SetRenderViewport(), and SDL_SetRenderVSync().
CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG
#define CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG (renderer, result)
Value:
    if (!SDL_ObjectValid(renderer, SDL_OBJECT_TYPE_RENDERER)) {         \
        SDL_InvalidParamError("renderer");                              \
        return result;                                                  \
    }
#define CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG(renderer, result)   \
    if (!SDL_ObjectValid(renderer, SDL_OBJECT_TYPE_RENDERER)) {         \
        SDL_InvalidParamError("renderer");                              \
        return result;                                                  \
    }
Referenced by SDL_DestroyRenderer().
CHECK_TEXTURE_MAGIC
#define CHECK_TEXTURE_MAGIC (texture, result)
Value:
    if (!SDL_ObjectValid(texture, SDL_OBJECT_TYPE_TEXTURE)) {   \
        SDL_InvalidParamError("texture");                       \
        return result;                                          \
    }
#define CHECK_TEXTURE_MAGIC(texture, result)                    \
    if (!SDL_ObjectValid(texture, SDL_OBJECT_TYPE_TEXTURE)) {   \
        SDL_InvalidParamError("texture");                       \
        return result;                                          \
    }
Referenced by SDL_DestroyTexture(), SDL_GetRendererFromTexture(), SDL_GetTextureAlphaModFloat(), SDL_GetTextureBlendMode(), SDL_GetTextureColorModFloat(), SDL_GetTextureProperties(), SDL_GetTextureScaleMode(), SDL_GetTextureSize(), SDL_LockTexture(), SDL_RenderGeometryRaw(), SDL_RenderTexture(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), SDL_RenderTextureAffine(), SDL_RenderTextureRotated(), SDL_RenderTextureTiled(), SDL_SetRenderTarget(), SDL_SetTextureAlphaModFloat(), SDL_SetTextureBlendMode(), SDL_SetTextureColorModFloat(), SDL_SetTextureScaleMode(), SDL_UnlockTexture(), SDL_UpdateNVTexture(), SDL_UpdateTexture(), and SDL_UpdateYUVTexture().
DONT_DRAW_WHILE_HIDDEN
#define DONT_DRAW_WHILE_HIDDEN 0
SDL_BLENDMODE_ADD_FULL
#define SDL_BLENDMODE_ADD_FULL
Value:
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_SRC_ALPHA, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
#define SDL_BLENDMODE_ADD_FULL                                                                    \
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_SRC_ALPHA, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
Referenced by SDL_GetLongBlendMode(), and SDL_GetShortBlendMode().
SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL
#define SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL
Value:
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ONE,  SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
#define SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL                                                 \
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ONE,  SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
Referenced by SDL_GetLongBlendMode(), and SDL_GetShortBlendMode().
SDL_BLENDMODE_BLEND_FULL
#define SDL_BLENDMODE_BLEND_FULL
Value:
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_SRC_ALPHA, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD)
#define SDL_BLENDMODE_BLEND_FULL                                                                                  \
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_SRC_ALPHA, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD)
Referenced by SDL_GetLongBlendMode(), and SDL_GetShortBlendMode().
SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL
#define SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL
Value:
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD)
#define SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL                                                              \
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD)
Referenced by SDL_GetLongBlendMode(), and SDL_GetShortBlendMode().
SDL_BLENDMODE_MOD_FULL
#define SDL_BLENDMODE_MOD_FULL
Value:
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_SRC_COLOR, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
#define SDL_BLENDMODE_MOD_FULL                                                                     \
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_SRC_COLOR, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
Referenced by SDL_GetLongBlendMode(), and SDL_GetShortBlendMode().
SDL_BLENDMODE_MUL_FULL
#define SDL_BLENDMODE_MUL_FULL
Value:
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_DST_COLOR, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
#define SDL_BLENDMODE_MUL_FULL                                                                                    \
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_DST_COLOR, SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_ONE, SDL_BLENDOPERATION_ADD)
Referenced by SDL_GetLongBlendMode(), and SDL_GetShortBlendMode().
SDL_BLENDMODE_NONE_FULL
#define SDL_BLENDMODE_NONE_FULL
Value:
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ZERO, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ZERO, SDL_BLENDOPERATION_ADD)
#define SDL_BLENDMODE_NONE_FULL                                                              \
    SDL_COMPOSE_BLENDMODE(SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ZERO, SDL_BLENDOPERATION_ADD, \
                          SDL_BLENDFACTOR_ONE, SDL_BLENDFACTOR_ZERO, SDL_BLENDOPERATION_ADD)
Referenced by SDL_GetLongBlendMode(), and SDL_GetShortBlendMode().
SDL_COMPOSE_BLENDMODE
#define SDL_COMPOSE_BLENDMODE (srcColorFactor, dstColorFactor, colorOperation, srcAlphaFactor, dstAlphaFactor, alphaOperation)
Value:
    (SDL_BlendMode)(((Uint32)(colorOperation) << 0) |                         \
                    ((Uint32)(srcColorFactor) << 4) |                         \
                    ((Uint32)(dstColorFactor) << 8) |                         \
                    ((Uint32)(alphaOperation) << 16) |                        \
                    ((Uint32)(srcAlphaFactor) << 20) |                        \
                    ((Uint32)(dstAlphaFactor) << 24))
Referenced by SDL_ComposeCustomBlendMode().
SDL_DEBUG_FONT_GLYPHS_PER_ROW
#define SDL_DEBUG_FONT_GLYPHS_PER_ROW 14
Referenced by CreateDebugTextAtlas(), and DrawDebugCharacter().
SDL_PROP_TEXTURE_PARENT_POINTER
#define SDL_PROP_TEXTURE_PARENT_POINTER "SDL.internal.texture.parent"
Referenced by SDL_CreateTextureWithProperties(), SDL_GetRenderTarget(), and SDL_RenderReadPixels().
SDL_PROP_WINDOW_RENDERER_POINTER
#define SDL_PROP_WINDOW_RENDERER_POINTER "SDL.internal.window.renderer"
Referenced by SDL_CreateRendererWithProperties(), SDL_DestroyRendererWithoutFreeing(), and SDL_GetRenderer().
SETVAL
#define SETVAL (ptr, val)
Value:
if (ptr) { *ptr = val; }
Referenced by SDL_GetRenderLogicalPresentation().
Function Documentation
AllocateRenderCommand()
SDL_RenderCommand * AllocateRenderCommand (SDL_Renderer * renderer) static
{
    SDL_RenderCommand *result = NULL;
    result = renderer->render_commands_pool;
    if (result) {
        renderer->render_commands_pool = result->next;
        result->next = NULL;
    } else {
        result = (SDL_RenderCommand *)SDL_calloc(1, sizeof(*result));
        if (!result) {
            return NULL;
        }
    }
    SDL_assert((renderer->render_commands == NULL) == (renderer->render_commands_tail == NULL));
    if (renderer->render_commands_tail) {
        renderer->render_commands_tail->next = result;
    } else {
        renderer->render_commands = result;
    }
    renderer->render_commands_tail = result;
    return result;
}
References SDL_RenderCommand::next, NULL, SDL_Renderer::render_commands, SDL_Renderer::render_commands_pool, SDL_Renderer::render_commands_tail, SDL_assert, and SDL_calloc().
Referenced by PrepQueueCmdDraw(), QueueCmdClear(), QueueCmdSetClipRect(), QueueCmdSetDrawColor(), and QueueCmdSetViewport().
CreateDebugTextAtlas()
bool CreateDebugTextAtlas (SDL_Renderer * renderer) static
{
    SDL_assert(renderer->debug_char_texture_atlas == NULL);  // don't double-create it!
    const int charWidth = SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE;
    const int charHeight = SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE;
    // actually make each glyph two pixels taller/wider, to prevent scaling artifacts.
    const int rows = (SDL_DEBUG_FONT_NUM_GLYPHS / SDL_DEBUG_FONT_GLYPHS_PER_ROW) + 1;
    SDL_Surface *atlas = SDL_CreateSurface((charWidth + 2) * SDL_DEBUG_FONT_GLYPHS_PER_ROW, rows * (charHeight + 2), SDL_PIXELFORMAT_RGBA8888);
    if (!atlas) {
        return false;
    }
    const int pitch = atlas->pitch;
    SDL_memset(atlas->pixels, '\0', atlas->h * atlas->pitch);
    int column = 0;
    int row = 0;
    for (int glyph = 0; glyph < SDL_DEBUG_FONT_NUM_GLYPHS; glyph++) {
        // find top-left of this glyph in destination surface. The +2's account for glyph padding.
        Uint8 *linepos = (((Uint8 *)atlas->pixels) + ((row * (charHeight + 2) + 1) * pitch)) + ((column * (charWidth + 2) + 1) * sizeof (Uint32));
        const Uint8 *charpos = SDL_RenderDebugTextFontData + (glyph * 8);
        // Draw the glyph to the surface...
        for (int iy = 0; iy < charHeight; iy++) {
            Uint32 *curpos = (Uint32 *)linepos;
            for (int ix = 0; ix < charWidth; ix++) {
                if ((*charpos) & (1 << ix)) {
                    *curpos = 0xffffffff;
                } else {
                    *curpos = 0;
                }
                ++curpos;
            }
            linepos += pitch;
            ++charpos;
        }
        // move to next position (and if too far, start the next row).
        column++;
        if (column >= SDL_DEBUG_FONT_GLYPHS_PER_ROW) {
            row++;
            column = 0;
        }
    }
    SDL_assert((row < rows) || ((row == rows) && (column == 0)));  // make sure we didn't overflow the surface.
    // Convert temp surface into texture
    SDL_Texture *texture = SDL_CreateTextureFromSurface(renderer, atlas);
    if (texture) {
        SDL_SetTextureScaleMode(texture, SDL_SCALEMODE_PIXELART);
        renderer->debug_char_texture_atlas = texture;
    }
    SDL_DestroySurface(atlas);
    return texture != NULL;
}
References SDL_Renderer::debug_char_texture_atlas, SDL_Surface::h, NULL, SDL_Surface::pitch, SDL_Surface::pixels, SDL_assert, SDL_CreateSurface(), SDL_CreateTextureFromSurface(), SDL_DEBUG_FONT_GLYPHS_PER_ROW, SDL_DEBUG_FONT_NUM_GLYPHS, SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE, SDL_DestroySurface(), SDL_memset, SDL_PIXELFORMAT_RGBA8888, SDL_RenderDebugTextFontData, SDL_SCALEMODE_PIXELART, and SDL_SetTextureScaleMode().
Referenced by SDL_RenderDebugText().
DebugLogRenderCommands()
SDL_INLINE void DebugLogRenderCommands (const SDL_RenderCommand * cmd) static
{
#if 0
    unsigned int i = 1;
    SDL_Log("Render commands to flush:");
    while (cmd) {
        switch (cmd->command) {
        case SDL_RENDERCMD_NO_OP:
            SDL_Log(" %u. no-op", i++);
            break;
        case SDL_RENDERCMD_SETVIEWPORT:
            SDL_Log(" %u. set viewport (first=%u, rect={(%d, %d), %dx%d})", i++,
                    (unsigned int)cmd->data.viewport.first,
                    cmd->data.viewport.rect.x, cmd->data.viewport.rect.y,
                    cmd->data.viewport.rect.w, cmd->data.viewport.rect.h);
            break;
        case SDL_RENDERCMD_SETCLIPRECT:
            SDL_Log(" %u. set cliprect (enabled=%s, rect={(%d, %d), %dx%d})", i++,
                    cmd->data.cliprect.enabled ? "true" : "false",
                    cmd->data.cliprect.rect.x, cmd->data.cliprect.rect.y,
                    cmd->data.cliprect.rect.w, cmd->data.cliprect.rect.h);
            break;
        case SDL_RENDERCMD_SETDRAWCOLOR:
            SDL_Log(" %u. set draw color (first=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, color_scale=%g)", i++,
                    (unsigned int)cmd->data.color.first,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a, cmd->data.color.color_scale);
            break;
        case SDL_RENDERCMD_CLEAR:
            SDL_Log(" %u. clear (first=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, color_scale=%g)", i++,
                    (unsigned int)cmd->data.color.first,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a, cmd->data.color.color_scale);
            break;
        case SDL_RENDERCMD_DRAW_POINTS:
            SDL_Log(" %u. draw points (first=%u, count=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, blend=%d, color_scale=%g)", i++,
                    (unsigned int)cmd->data.draw.first,
                    (unsigned int)cmd->data.draw.count,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a,
                    (int)cmd->data.draw.blend, cmd->data.draw.color_scale);
            break;
        case SDL_RENDERCMD_DRAW_LINES:
            SDL_Log(" %u. draw lines (first=%u, count=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, blend=%d, color_scale=%g)", i++,
                    (unsigned int)cmd->data.draw.first,
                    (unsigned int)cmd->data.draw.count,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a,
                    (int)cmd->data.draw.blend, cmd->data.draw.color_scale);
            break;
        case SDL_RENDERCMD_FILL_RECTS:
            SDL_Log(" %u. fill rects (first=%u, count=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, blend=%d, color_scale=%g)", i++,
                    (unsigned int)cmd->data.draw.first,
                    (unsigned int)cmd->data.draw.count,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a,
                    (int)cmd->data.draw.blend, cmd->data.draw.color_scale);
            break;
        case SDL_RENDERCMD_COPY:
            SDL_Log(" %u. copy (first=%u, count=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, blend=%d, color_scale=%g, tex=%p)", i++,
                    (unsigned int)cmd->data.draw.first,
                    (unsigned int)cmd->data.draw.count,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a,
                    (int)cmd->data.draw.blend, cmd->data.draw.color_scale, cmd->data.draw.texture);
            break;
        case SDL_RENDERCMD_COPY_EX:
            SDL_Log(" %u. copyex (first=%u, count=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, blend=%d, color_scale=%g, tex=%p)", i++,
                    (unsigned int)cmd->data.draw.first,
                    (unsigned int)cmd->data.draw.count,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a,
                    (int)cmd->data.draw.blend, cmd->data.draw.color_scale, cmd->data.draw.texture);
            break;
        case SDL_RENDERCMD_GEOMETRY:
            SDL_Log(" %u. geometry (first=%u, count=%u, r=%.2f, g=%.2f, b=%.2f, a=%.2f, blend=%d, color_scale=%g, tex=%p)", i++,
                    (unsigned int)cmd->data.draw.first,
                    (unsigned int)cmd->data.draw.count,
                    cmd->data.draw.color.r, cmd->data.draw.color.g,
                    cmd->data.draw.color.b, cmd->data.draw.color.a,
                    (int)cmd->data.draw.blend, cmd->data.draw.color_scale, cmd->data.draw.texture);
            break;
        }
        cmd = cmd->next;
    }
#endif
}
References SDL_FColor::a, SDL_FColor::b, SDL_RenderCommand::blend, SDL_RenderCommand::cliprect, SDL_RenderCommand::color, SDL_RenderCommand::color_scale, SDL_RenderCommand::command, SDL_RenderCommand::count, SDL_RenderCommand::data, SDL_RenderCommand::draw, SDL_RenderCommand::enabled, SDL_RenderCommand::first, SDL_FColor::g, SDL_Rect::h, SDL_RenderCommand::next, SDL_FColor::r, SDL_RenderCommand::rect, SDL_INLINE, SDL_Log(), SDL_RENDERCMD_CLEAR, SDL_RENDERCMD_COPY, SDL_RENDERCMD_COPY_EX, SDL_RENDERCMD_DRAW_LINES, SDL_RENDERCMD_DRAW_POINTS, SDL_RENDERCMD_FILL_RECTS, SDL_RENDERCMD_GEOMETRY, SDL_RENDERCMD_NO_OP, SDL_RENDERCMD_SETCLIPRECT, SDL_RENDERCMD_SETDRAWCOLOR, SDL_RENDERCMD_SETVIEWPORT, SDL_RenderCommand::texture, SDL_RenderCommand::viewport, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by FlushRenderCommands().
DrawDebugCharacter()
bool DrawDebugCharacter (SDL_Renderer * renderer, float x, float y, Uint32 c) static
{
    SDL_assert(renderer->debug_char_texture_atlas != NULL);   // should have been created by now!
    const int charWidth = SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE;
    const int charHeight = SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE;
    // Character index in cache
    Uint32 ci = c;
    if ((ci <= 32) || ((ci >= 127) && (ci <= 160))) {
        return true;  // these are just completely blank chars, don't bother doing anything.
    } else if (ci >= SDL_DEBUG_FONT_NUM_GLYPHS) {
        ci = SDL_DEBUG_FONT_NUM_GLYPHS - 1;  // use our "not a valid/supported character" glyph.
    } else if (ci < 127) {
        ci -= 33;     // adjust for the 33 blank glyphs at the start
    } else {
        ci -= 67;     // adjust for the 33 blank glyphs at the start AND the 34 gap in the middle.
    }
    const float src_x = (float) (((ci % SDL_DEBUG_FONT_GLYPHS_PER_ROW) * (charWidth + 2)) + 1);
    const float src_y = (float) (((ci / SDL_DEBUG_FONT_GLYPHS_PER_ROW) * (charHeight + 2)) + 1);
    // Draw texture onto destination
    const SDL_FRect srect = { src_x, src_y, (float) charWidth, (float) charHeight };
    const SDL_FRect drect = { x, y, (float) charWidth, (float) charHeight };
    return SDL_RenderTexture(renderer, renderer->debug_char_texture_atlas, &srect, &drect);
}
References SDL_Renderer::debug_char_texture_atlas, NULL, SDL_assert, SDL_DEBUG_FONT_GLYPHS_PER_ROW, SDL_DEBUG_FONT_NUM_GLYPHS, SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE, and SDL_RenderTexture().
Referenced by SDL_RenderDebugText().
FlushRenderCommands()
bool FlushRenderCommands (SDL_Renderer * renderer) static
{
    bool result;
    SDL_assert((renderer->render_commands == NULL) == (renderer->render_commands_tail == NULL));
    if (!renderer->render_commands) { // nothing to do!
        SDL_assert(renderer->vertex_data_used == 0);
        return true;
    }
    DebugLogRenderCommands(renderer->render_commands);
    result = renderer->RunCommandQueue(renderer, renderer->render_commands, renderer->vertex_data, renderer->vertex_data_used);
    // Move the whole render command queue to the unused pool so we can reuse them next time.
    if (renderer->render_commands_tail) {
        renderer->render_commands_tail->next = renderer->render_commands_pool;
        renderer->render_commands_pool = renderer->render_commands;
        renderer->render_commands_tail = NULL;
        renderer->render_commands = NULL;
    }
    renderer->vertex_data_used = 0;
    renderer->render_command_generation++;
    renderer->color_queued = false;
    renderer->viewport_queued = false;
    renderer->cliprect_queued = false;
    return result;
}
References SDL_Renderer::cliprect_queued, SDL_Renderer::color_queued, DebugLogRenderCommands(), SDL_RenderCommand::next, NULL, SDL_Renderer::render_command_generation, SDL_Renderer::render_commands, SDL_Renderer::render_commands_pool, SDL_Renderer::render_commands_tail, SDL_Renderer::RunCommandQueue, SDL_assert, SDL_Renderer::vertex_data, SDL_Renderer::vertex_data_used, and SDL_Renderer::viewport_queued.
Referenced by FlushRenderCommandsIfGPURenderStateNeeded(), FlushRenderCommandsIfTextureNeeded(), SDL_DestroyRendererWithoutFreeing(), SDL_FlushRenderer(), SDL_GetRenderMetalCommandEncoder(), SDL_GetRenderMetalLayer(), SDL_RenderPresent(), SDL_RenderReadPixels(), and SDL_SetRenderTarget().
FlushRenderCommandsIfGPURenderStateNeeded()
bool FlushRenderCommandsIfGPURenderStateNeeded (SDL_GPURenderState * state) static
{
    SDL_Renderer *renderer = state->renderer;
    if (state->last_command_generation == renderer->render_command_generation) {
        // the current command queue depends on this state, flush the queue now before it changes
        return FlushRenderCommands(renderer);
    }
    return true;
}
References FlushRenderCommands(), SDL_GPURenderState::last_command_generation, SDL_Renderer::render_command_generation, and SDL_GPURenderState::renderer.
Referenced by SDL_DestroyGPURenderState(), and SDL_SetGPURenderStateFragmentUniforms().
FlushRenderCommandsIfTextureNeeded()
bool FlushRenderCommandsIfTextureNeeded (SDL_Texture * texture) static
{
    SDL_Renderer *renderer = texture->renderer;
    if (texture->last_command_generation == renderer->render_command_generation) {
        // the current command queue depends on this texture, flush the queue now before it changes
        return FlushRenderCommands(renderer);
    }
    return true;
}
References FlushRenderCommands(), SDL_Texture::last_command_generation, SDL_Renderer::render_command_generation, and SDL_Texture::renderer.
Referenced by SDL_DestroyTextureInternal(), SDL_LockTexture(), SDL_UpdateNVTexture(), SDL_UpdateTexture(), and SDL_UpdateYUVTexture().
GetClosestSupportedFormat()
SDL_PixelFormat GetClosestSupportedFormat (SDL_Renderer * renderer, SDL_PixelFormat format) static
{
    int i;
    if (format == SDL_PIXELFORMAT_MJPG) {
        // We'll decode to SDL_PIXELFORMAT_NV12 or SDL_PIXELFORMAT_RGBA32
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (renderer->texture_formats[i] == SDL_PIXELFORMAT_NV12) {
                return renderer->texture_formats[i];
            }
        }
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (renderer->texture_formats[i] == SDL_PIXELFORMAT_RGBA32) {
                return renderer->texture_formats[i];
            }
        }
    } else if (SDL_ISPIXELFORMAT_FOURCC(format)) {
        // Look for an exact match
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (renderer->texture_formats[i] == format) {
                return renderer->texture_formats[i];
            }
        }
    } else if (SDL_ISPIXELFORMAT_10BIT(format) || SDL_ISPIXELFORMAT_FLOAT(format)) {
        if (SDL_ISPIXELFORMAT_10BIT(format)) {
            for (i = 0; i < renderer->num_texture_formats; ++i) {
                if (SDL_ISPIXELFORMAT_10BIT(renderer->texture_formats[i])) {
                    return renderer->texture_formats[i];
                }
            }
        }
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (SDL_ISPIXELFORMAT_FLOAT(renderer->texture_formats[i])) {
                return renderer->texture_formats[i];
            }
        }
    } else {
        bool hasAlpha = SDL_ISPIXELFORMAT_ALPHA(format);
        // We just want to match the first format that has the same channels
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (!SDL_ISPIXELFORMAT_FOURCC(renderer->texture_formats[i]) &&
                SDL_ISPIXELFORMAT_ALPHA(renderer->texture_formats[i]) == hasAlpha) {
                return renderer->texture_formats[i];
            }
        }
    }
    return renderer->texture_formats[0];
}
References SDL_Renderer::num_texture_formats, SDL_ISPIXELFORMAT_10BIT, SDL_ISPIXELFORMAT_ALPHA, SDL_ISPIXELFORMAT_FLOAT, SDL_ISPIXELFORMAT_FOURCC, SDL_PIXELFORMAT_MJPG, SDL_PIXELFORMAT_NV12, SDL_PIXELFORMAT_RGBA32, and SDL_Renderer::texture_formats.
Referenced by SDL_CreateTextureWithProperties().
GetRenderViewportSize()
void GetRenderViewportSize (SDL_Renderer * renderer, SDL_FRect * rect) static
{
    const SDL_RenderViewState *view = renderer->view;
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    rect->x = 0.0f;
    rect->y = 0.0f;
    if (view->viewport.w >= 0) {
        rect->w = (float)view->viewport.w;
    } else {
        rect->w = view->pixel_w / scale_x;
    }
    if (view->viewport.h >= 0) {
        rect->h = (float)view->viewport.h;
    } else {
        rect->h = view->pixel_h / scale_y;
    }
}
References SDL_RenderViewState::current_scale, SDL_FRect::h, SDL_Rect::h, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, SDL_Renderer::view, SDL_RenderViewState::viewport, SDL_FRect::w, SDL_Rect::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by SDL_RenderFillRect(), SDL_RenderRect(), SDL_RenderTexture(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), SDL_RenderTextureAffine(), SDL_RenderTextureRotated(), and SDL_RenderTextureTiled().
IsSupportedBlendMode()
bool IsSupportedBlendMode (SDL_Renderer * renderer, SDL_BlendMode blendMode) static
{
    switch (blendMode) {
    // These are required to be supported by all renderers
    case SDL_BLENDMODE_NONE:
    case SDL_BLENDMODE_BLEND:
    case SDL_BLENDMODE_BLEND_PREMULTIPLIED:
    case SDL_BLENDMODE_ADD:
    case SDL_BLENDMODE_ADD_PREMULTIPLIED:
    case SDL_BLENDMODE_MOD:
    case SDL_BLENDMODE_MUL:
        return true;
    default:
        return renderer->SupportsBlendMode && renderer->SupportsBlendMode(renderer, blendMode);
    }
}
References SDL_BLENDMODE_ADD, SDL_BLENDMODE_ADD_PREMULTIPLIED, SDL_BLENDMODE_BLEND, SDL_BLENDMODE_BLEND_PREMULTIPLIED, SDL_BLENDMODE_MOD, SDL_BLENDMODE_MUL, SDL_BLENDMODE_NONE, and SDL_Renderer::SupportsBlendMode.
Referenced by SDL_SetRenderDrawBlendMode(), and SDL_SetTextureBlendMode().
IsSupportedFormat()
bool IsSupportedFormat (SDL_Renderer * renderer, SDL_PixelFormat format) static
{
    int i;
    for (i = 0; i < renderer->num_texture_formats; ++i) {
        if (renderer->texture_formats[i] == format) {
            return true;
        }
    }
    return false;
}
References SDL_Renderer::num_texture_formats, and SDL_Renderer::texture_formats.
Referenced by SDL_CreateTextureWithProperties().
PrepQueueCmdDraw()
SDL_RenderCommand * PrepQueueCmdDraw (SDL_Renderer * renderer, const SDL_RenderCommandType cmdtype, SDL_Texture * texture) static
{
    SDL_RenderCommand *cmd = NULL;
    bool result = true;
    SDL_FColor *color;
    SDL_BlendMode blendMode;
    if (texture) {
        color = &texture->color;
        blendMode = texture->blendMode;
    } else {
        color = &renderer->color;
        blendMode = renderer->blendMode;
    }
    if (cmdtype != SDL_RENDERCMD_GEOMETRY) {
        result = QueueCmdSetDrawColor(renderer, color);
    }
    /* Set the viewport and clip rect directly before draws, so the backends
     * don't have to worry about that state not being valid at draw time. */
    if (result && !renderer->viewport_queued) {
        result = QueueCmdSetViewport(renderer);
    }
    if (result && !renderer->cliprect_queued) {
        result = QueueCmdSetClipRect(renderer);
    }
    if (result) {
        cmd = AllocateRenderCommand(renderer);
        if (cmd) {
            cmd->command = cmdtype;
            cmd->data.draw.first = 0; // render backend will fill this in.
            cmd->data.draw.count = 0; // render backend will fill this in.
            cmd->data.draw.color_scale = renderer->color_scale;
            cmd->data.draw.color = *color;
            cmd->data.draw.blend = blendMode;
            cmd->data.draw.texture = texture;
            if (texture) {
                cmd->data.draw.texture_scale_mode = texture->scaleMode;
            }
            cmd->data.draw.texture_address_mode_u = SDL_TEXTURE_ADDRESS_CLAMP;
            cmd->data.draw.texture_address_mode_v = SDL_TEXTURE_ADDRESS_CLAMP;
            cmd->data.draw.gpu_render_state = renderer->gpu_render_state;
            if (renderer->gpu_render_state) {
                renderer->gpu_render_state->last_command_generation = renderer->render_command_generation;
            }
        }
    }
    return cmd;
}
References AllocateRenderCommand(), SDL_RenderCommand::blend, SDL_Renderer::blendMode, SDL_Texture::blendMode, SDL_Renderer::cliprect_queued, SDL_RenderCommand::color, SDL_Renderer::color, SDL_Texture::color, SDL_RenderCommand::color_scale, SDL_Renderer::color_scale, SDL_RenderCommand::command, SDL_RenderCommand::count, SDL_RenderCommand::data, SDL_RenderCommand::draw, SDL_RenderCommand::first, SDL_RenderCommand::gpu_render_state, SDL_Renderer::gpu_render_state, SDL_GPURenderState::last_command_generation, NULL, QueueCmdSetClipRect(), QueueCmdSetDrawColor(), QueueCmdSetViewport(), SDL_Renderer::render_command_generation, SDL_Texture::scaleMode, SDL_RENDERCMD_GEOMETRY, SDL_TEXTURE_ADDRESS_CLAMP, SDL_RenderCommand::texture, SDL_RenderCommand::texture_address_mode_u, SDL_RenderCommand::texture_address_mode_v, SDL_RenderCommand::texture_scale_mode, and SDL_Renderer::viewport_queued.
Referenced by QueueCmdCopy(), QueueCmdCopyEx(), QueueCmdDrawLines(), QueueCmdDrawPoints(), QueueCmdFillRects(), and QueueCmdGeometry().
QueueCmdClear()
bool QueueCmdClear (SDL_Renderer * renderer) static
{
    SDL_RenderCommand *cmd = AllocateRenderCommand(renderer);
    if (!cmd) {
        return false;
    }
    cmd->command = SDL_RENDERCMD_CLEAR;
    cmd->data.color.first = 0;
    cmd->data.color.color_scale = renderer->color_scale;
    cmd->data.color.color = renderer->color;
    return true;
}
References AllocateRenderCommand(), SDL_RenderCommand::color, SDL_Renderer::color, SDL_Renderer::color_scale, SDL_RenderCommand::command, SDL_RenderCommand::data, and SDL_RENDERCMD_CLEAR.
Referenced by SDL_RenderClear().
QueueCmdCopy()
bool QueueCmdCopy (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FRect * dstrect) static
{
    SDL_RenderCommand *cmd = PrepQueueCmdDraw(renderer, SDL_RENDERCMD_COPY, texture);
    bool result = false;
    if (cmd) {
        result = renderer->QueueCopy(renderer, cmd, texture, srcrect, dstrect);
        if (!result) {
            cmd->command = SDL_RENDERCMD_NO_OP;
        }
    }
    return result;
}
References SDL_RenderCommand::command, PrepQueueCmdDraw(), SDL_Renderer::QueueCopy, SDL_RENDERCMD_COPY, and SDL_RENDERCMD_NO_OP.
Referenced by SDL_RenderTextureInternal().
QueueCmdCopyEx()
bool QueueCmdCopyEx (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcquad, const SDL_FRect * dstrect, const double angle, const SDL_FPoint * center, const SDL_FlipMode flip, float scale_x, float scale_y) static
{
    SDL_RenderCommand *cmd = PrepQueueCmdDraw(renderer, SDL_RENDERCMD_COPY_EX, texture);
    bool result = false;
    if (cmd) {
        result = renderer->QueueCopyEx(renderer, cmd, texture, srcquad, dstrect, angle, center, flip, scale_x, scale_y);
        if (!result) {
            cmd->command = SDL_RENDERCMD_NO_OP;
        }
    }
    return result;
}
References SDL_RenderCommand::command, PrepQueueCmdDraw(), SDL_Renderer::QueueCopyEx, SDL_RENDERCMD_COPY_EX, and SDL_RENDERCMD_NO_OP.
Referenced by SDL_RenderTextureRotated().
QueueCmdDrawLines()
bool QueueCmdDrawLines (SDL_Renderer * renderer, const SDL_FPoint * points, const int count) static
{
    SDL_RenderCommand *cmd = PrepQueueCmdDraw(renderer, SDL_RENDERCMD_DRAW_LINES, NULL);
    bool result = false;
    if (cmd) {
        result = renderer->QueueDrawLines(renderer, cmd, points, count);
        if (!result) {
            cmd->command = SDL_RENDERCMD_NO_OP;
        }
    }
    return result;
}
References SDL_RenderCommand::command, count, NULL, PrepQueueCmdDraw(), SDL_Renderer::QueueDrawLines, SDL_RENDERCMD_DRAW_LINES, and SDL_RENDERCMD_NO_OP.
Referenced by SDL_RenderLines().
QueueCmdDrawPoints()
bool QueueCmdDrawPoints (SDL_Renderer * renderer, const SDL_FPoint * points, const int count) static
{
    SDL_RenderCommand *cmd = PrepQueueCmdDraw(renderer, SDL_RENDERCMD_DRAW_POINTS, NULL);
    bool result = false;
    if (cmd) {
        result = renderer->QueueDrawPoints(renderer, cmd, points, count);
        if (!result) {
            cmd->command = SDL_RENDERCMD_NO_OP;
        }
    }
    return result;
}
References SDL_RenderCommand::command, count, NULL, PrepQueueCmdDraw(), SDL_Renderer::QueueDrawPoints, SDL_RENDERCMD_DRAW_POINTS, and SDL_RENDERCMD_NO_OP.
Referenced by RenderLineBresenham(), and SDL_RenderPoints().
QueueCmdFillRects()
bool QueueCmdFillRects (SDL_Renderer * renderer, const SDL_FRect * rects, const int count) static
{
    SDL_RenderCommand *cmd;
    bool result = false;
    const int use_rendergeometry = (!renderer->QueueFillRects);
    cmd = PrepQueueCmdDraw(renderer, (use_rendergeometry ? SDL_RENDERCMD_GEOMETRY : SDL_RENDERCMD_FILL_RECTS), NULL);
    if (cmd) {
        if (use_rendergeometry) {
            bool isstack1;
            bool isstack2;
            float *xy = SDL_small_alloc(float, 4 * 2 * count, &isstack1);
            int *indices = SDL_small_alloc(int, 6 * count, &isstack2);
            if (xy && indices) {
                int i;
                float *ptr_xy = xy;
                int *ptr_indices = indices;
                const int xy_stride = 2 * sizeof(float);
                const int num_vertices = 4 * count;
                const int num_indices = 6 * count;
                const int size_indices = 4;
                int cur_index = 0;
                for (i = 0; i < count; ++i) {
                    float minx, miny, maxx, maxy;
                    minx = rects[i].x;
                    miny = rects[i].y;
                    maxx = rects[i].x + rects[i].w;
                    maxy = rects[i].y + rects[i].h;
                    *ptr_xy++ = minx;
                    *ptr_xy++ = miny;
                    *ptr_xy++ = maxx;
                    *ptr_xy++ = miny;
                    *ptr_xy++ = maxx;
                    *ptr_xy++ = maxy;
                    *ptr_xy++ = minx;
                    *ptr_xy++ = maxy;
                    *ptr_indices++ = cur_index + rect_index_order[0];
                    *ptr_indices++ = cur_index + rect_index_order[1];
                    *ptr_indices++ = cur_index + rect_index_order[2];
                    *ptr_indices++ = cur_index + rect_index_order[3];
                    *ptr_indices++ = cur_index + rect_index_order[4];
                    *ptr_indices++ = cur_index + rect_index_order[5];
                    cur_index += 4;
                }
                result = renderer->QueueGeometry(renderer, cmd, NULL,
                                                 xy, xy_stride, &renderer->color, 0 /* color_stride */, NULL, 0,
                                                 num_vertices, indices, num_indices, size_indices,
                                                 1.0f, 1.0f);
                if (!result) {
                    cmd->command = SDL_RENDERCMD_NO_OP;
                }
            }
            SDL_small_free(xy, isstack1);
            SDL_small_free(indices, isstack2);
        } else {
            result = renderer->QueueFillRects(renderer, cmd, rects, count);
            if (!result) {
                cmd->command = SDL_RENDERCMD_NO_OP;
            }
        }
    }
    return result;
}
References SDL_Renderer::color, SDL_RenderCommand::command, count, NULL, PrepQueueCmdDraw(), SDL_Renderer::QueueFillRects, SDL_Renderer::QueueGeometry, rect_index_order, SDL_RENDERCMD_FILL_RECTS, SDL_RENDERCMD_GEOMETRY, SDL_RENDERCMD_NO_OP, SDL_small_alloc, and SDL_small_free.
Referenced by RenderLinesWithRectsF(), RenderPointsWithRects(), and SDL_RenderFillRects().
QueueCmdGeometry()
bool QueueCmdGeometry (SDL_Renderer * renderer, SDL_Texture * texture, const float * xy, int xy_stride, const SDL_FColor * color, int color_stride, const float * uv, int uv_stride, int num_vertices, const void * indices, int num_indices, int size_indices, float scale_x, float scale_y, SDL_TextureAddressMode texture_address_mode_u, SDL_TextureAddressMode texture_address_mode_v) static
{
    SDL_RenderCommand *cmd;
    bool result = false;
    cmd = PrepQueueCmdDraw(renderer, SDL_RENDERCMD_GEOMETRY, texture);
    if (cmd) {
        cmd->data.draw.texture_address_mode_u = texture_address_mode_u;
        cmd->data.draw.texture_address_mode_v = texture_address_mode_v;
        result = renderer->QueueGeometry(renderer, cmd, texture,
                                         xy, xy_stride,
                                         color, color_stride, uv, uv_stride,
                                         num_vertices, indices, num_indices, size_indices,
                                         scale_x, scale_y);
        if (!result) {
            cmd->command = SDL_RENDERCMD_NO_OP;
        }
    }
    return result;
}
References SDL_RenderCommand::command, SDL_RenderCommand::data, SDL_RenderCommand::draw, PrepQueueCmdDraw(), SDL_Renderer::QueueGeometry, SDL_RENDERCMD_GEOMETRY, SDL_RENDERCMD_NO_OP, SDL_RenderCommand::texture_address_mode_u, and SDL_RenderCommand::texture_address_mode_v.
Referenced by SDL_RenderGeometryRaw(), SDL_RenderLines(), SDL_RenderTextureAffine(), SDL_RenderTextureInternal(), SDL_RenderTextureRotated(), and SDL_RenderTextureTiled_Wrap().
QueueCmdSetClipRect()
bool QueueCmdSetClipRect (SDL_Renderer * renderer) static
{
    bool result = true;
    const SDL_RenderViewState *view = renderer->view;
    SDL_Rect clip_rect = view->pixel_clip_rect;
    if (!renderer->cliprect_queued ||
        view->clipping_enabled != renderer->last_queued_cliprect_enabled ||
        SDL_memcmp(&clip_rect, &renderer->last_queued_cliprect, sizeof(clip_rect)) != 0) {
        SDL_RenderCommand *cmd = AllocateRenderCommand(renderer);
        if (cmd) {
            cmd->command = SDL_RENDERCMD_SETCLIPRECT;
            cmd->data.cliprect.enabled = view->clipping_enabled;
            SDL_copyp(&cmd->data.cliprect.rect, &clip_rect);
            SDL_copyp(&renderer->last_queued_cliprect, &clip_rect);
            renderer->last_queued_cliprect_enabled = view->clipping_enabled;
            renderer->cliprect_queued = true;
        } else {
            result = false;
        }
    }
    return result;
}
References AllocateRenderCommand(), SDL_RenderViewState::clipping_enabled, SDL_RenderCommand::cliprect, SDL_Renderer::cliprect_queued, SDL_RenderCommand::command, SDL_RenderCommand::data, SDL_RenderCommand::enabled, SDL_Renderer::last_queued_cliprect, SDL_Renderer::last_queued_cliprect_enabled, SDL_RenderViewState::pixel_clip_rect, SDL_RenderCommand::rect, SDL_copyp, SDL_memcmp(), SDL_RENDERCMD_SETCLIPRECT, and SDL_Renderer::view.
Referenced by PrepQueueCmdDraw(), SDL_SetRenderClipRect(), SDL_SetRenderScale(), SDL_SetRenderTarget(), and UpdateLogicalPresentation().
QueueCmdSetDrawColor()
bool QueueCmdSetDrawColor (SDL_Renderer * renderer, SDL_FColor * color) static
{
    bool result = true;
    if (!renderer->color_queued ||
        color->r != renderer->last_queued_color.r ||
        color->g != renderer->last_queued_color.g ||
        color->b != renderer->last_queued_color.b ||
        color->a != renderer->last_queued_color.a) {
        SDL_RenderCommand *cmd = AllocateRenderCommand(renderer);
        result = false;
        if (cmd) {
            cmd->command = SDL_RENDERCMD_SETDRAWCOLOR;
            cmd->data.color.first = 0; // render backend will fill this in.
            cmd->data.color.color_scale = renderer->color_scale;
            cmd->data.color.color = *color;
            result = renderer->QueueSetDrawColor(renderer, cmd);
            if (!result) {
                cmd->command = SDL_RENDERCMD_NO_OP;
            } else {
                renderer->last_queued_color = *color;
                renderer->color_queued = true;
            }
        }
    }
    return result;
}
References SDL_FColor::a, AllocateRenderCommand(), SDL_FColor::b, SDL_RenderCommand::color, SDL_Renderer::color_queued, SDL_Renderer::color_scale, SDL_RenderCommand::command, SDL_RenderCommand::data, SDL_FColor::g, SDL_Renderer::last_queued_color, SDL_Renderer::QueueSetDrawColor, SDL_FColor::r, SDL_RENDERCMD_NO_OP, and SDL_RENDERCMD_SETDRAWCOLOR.
Referenced by PrepQueueCmdDraw().
QueueCmdSetViewport()
bool QueueCmdSetViewport (SDL_Renderer * renderer) static
{
    bool result = true;
    SDL_Rect viewport = renderer->view->pixel_viewport;
    if (!renderer->viewport_queued ||
        SDL_memcmp(&viewport, &renderer->last_queued_viewport, sizeof(viewport)) != 0) {
        SDL_RenderCommand *cmd = AllocateRenderCommand(renderer);
        if (cmd) {
            cmd->command = SDL_RENDERCMD_SETVIEWPORT;
            cmd->data.viewport.first = 0; // render backend will fill this in.
            SDL_copyp(&cmd->data.viewport.rect, &viewport);
            result = renderer->QueueSetViewport(renderer, cmd);
            if (!result) {
                cmd->command = SDL_RENDERCMD_NO_OP;
            } else {
                SDL_copyp(&renderer->last_queued_viewport, &viewport);
                renderer->viewport_queued = true;
            }
        } else {
            result = false;
        }
    }
    return result;
}
References AllocateRenderCommand(), SDL_RenderCommand::command, SDL_RenderCommand::data, SDL_RenderCommand::first, SDL_Renderer::last_queued_viewport, SDL_RenderViewState::pixel_viewport, SDL_Renderer::QueueSetViewport, SDL_RenderCommand::rect, SDL_copyp, SDL_memcmp(), SDL_RENDERCMD_NO_OP, SDL_RENDERCMD_SETVIEWPORT, SDL_Renderer::view, SDL_RenderCommand::viewport, and SDL_Renderer::viewport_queued.
Referenced by PrepQueueCmdDraw(), SDL_SetRenderScale(), SDL_SetRenderTarget(), SDL_SetRenderViewport(), and UpdateLogicalPresentation().
RenderLineBresenham()
bool RenderLineBresenham (SDL_Renderer * renderer, int x1, int y1, int x2, int y2, bool draw_last) static
{
    const SDL_RenderViewState *view = renderer->view;
    const int MAX_PIXELS = SDL_max(view->pixel_w, view->pixel_h) * 4;
    int i, deltax, deltay, numpixels;
    int d, dinc1, dinc2;
    int x, xinc1, xinc2;
    int y, yinc1, yinc2;
    bool result;
    bool isstack;
    SDL_FPoint *points;
    SDL_Rect viewport;
    /* the backend might clip this further to the clipping rect, but we
       just want a basic safety against generating millions of points for
       massive lines. */
    viewport = view->pixel_viewport;
    viewport.x = 0;
    viewport.y = 0;
    if (!SDL_GetRectAndLineIntersection(&viewport, &x1, &y1, &x2, &y2)) {
        return true;
    }
    deltax = SDL_abs(x2 - x1);
    deltay = SDL_abs(y2 - y1);
    if (deltax >= deltay) {
        numpixels = deltax + 1;
        d = (2 * deltay) - deltax;
        dinc1 = deltay * 2;
        dinc2 = (deltay - deltax) * 2;
        xinc1 = 1;
        xinc2 = 1;
        yinc1 = 0;
        yinc2 = 1;
    } else {
        numpixels = deltay + 1;
        d = (2 * deltax) - deltay;
        dinc1 = deltax * 2;
        dinc2 = (deltax - deltay) * 2;
        xinc1 = 0;
        xinc2 = 1;
        yinc1 = 1;
        yinc2 = 1;
    }
    if (x1 > x2) {
        xinc1 = -xinc1;
        xinc2 = -xinc2;
    }
    if (y1 > y2) {
        yinc1 = -yinc1;
        yinc2 = -yinc2;
    }
    x = x1;
    y = y1;
    if (!draw_last) {
        --numpixels;
    }
    if (numpixels > MAX_PIXELS) {
        return SDL_SetError("Line too long (tried to draw %d pixels, max %d)", numpixels, MAX_PIXELS);
    }
    points = SDL_small_alloc(SDL_FPoint, numpixels, &isstack);
    if (!points) {
        return false;
    }
    for (i = 0; i < numpixels; ++i) {
        points[i].x = (float)x;
        points[i].y = (float)y;
        if (d < 0) {
            d += dinc1;
            x += xinc1;
            y += yinc1;
        } else {
            d += dinc2;
            x += xinc2;
            y += yinc2;
        }
    }
    if ((view->current_scale.x != 1.0f) || (view->current_scale.y != 1.0f)) {
        result = RenderPointsWithRects(renderer, points, numpixels);
    } else {
        result = QueueCmdDrawPoints(renderer, points, numpixels);
    }
    SDL_small_free(points, isstack);
    return result;
}
References SDL_RenderViewState::current_scale, d, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_viewport, SDL_RenderViewState::pixel_w, QueueCmdDrawPoints(), RenderPointsWithRects(), SDL_abs(), SDL_GetRectAndLineIntersection(), SDL_max, SDL_SetError(), SDL_small_alloc, SDL_small_free, SDL_Renderer::view, SDL_FPoint::x, SDL_Rect::x, x1, x2, SDL_FPoint::y, SDL_Rect::y, and y1.
Referenced by RenderLinesWithRectsF().
RenderLinesWithRectsF()
bool RenderLinesWithRectsF (SDL_Renderer * renderer, const SDL_FPoint * points, const int count) static
{
    const SDL_RenderViewState *view = renderer->view;
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    SDL_FRect *frect;
    SDL_FRect *frects;
    int i, nrects = 0;
    bool result = true;
    bool isstack;
    bool drew_line = false;
    bool draw_last = false;
    frects = SDL_small_alloc(SDL_FRect, count - 1, &isstack);
    if (!frects) {
        return false;
    }
    for (i = 0; i < count - 1; ++i) {
        bool same_x = (points[i].x == points[i + 1].x);
        bool same_y = (points[i].y == points[i + 1].y);
        if (i == (count - 2)) {
            if (!drew_line || points[i + 1].x != points[0].x || points[i + 1].y != points[0].y) {
                draw_last = true;
            }
        } else {
            if (same_x && same_y) {
                continue;
            }
        }
        if (same_x) {
            const float minY = SDL_min(points[i].y, points[i + 1].y);
            const float maxY = SDL_max(points[i].y, points[i + 1].y);
            frect = &frects[nrects++];
            frect->x = points[i].x * scale_x;
            frect->y = minY * scale_y;
            frect->w = scale_x;
            frect->h = (maxY - minY + draw_last) * scale_y;
            if (!draw_last && points[i + 1].y < points[i].y) {
                frect->y += scale_y;
            }
        } else if (same_y) {
            const float minX = SDL_min(points[i].x, points[i + 1].x);
            const float maxX = SDL_max(points[i].x, points[i + 1].x);
            frect = &frects[nrects++];
            frect->x = minX * scale_x;
            frect->y = points[i].y * scale_y;
            frect->w = (maxX - minX + draw_last) * scale_x;
            frect->h = scale_y;
            if (!draw_last && points[i + 1].x < points[i].x) {
                frect->x += scale_x;
            }
        } else {
            result &= RenderLineBresenham(renderer, (int)SDL_roundf(points[i].x), (int)SDL_roundf(points[i].y),
                                              (int)SDL_roundf(points[i + 1].x), (int)SDL_roundf(points[i + 1].y), draw_last);
        }
        drew_line = true;
    }
    if (nrects) {
        result &= QueueCmdFillRects(renderer, frects, nrects);
    }
    SDL_small_free(frects, isstack);
    return result;
}
References count, SDL_RenderViewState::current_scale, SDL_FRect::h, QueueCmdFillRects(), RenderLineBresenham(), SDL_max, SDL_min, SDL_roundf(), SDL_small_alloc, SDL_small_free, SDL_Renderer::view, SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by SDL_RenderLines().
RenderPointsWithRects()
bool RenderPointsWithRects (SDL_Renderer * renderer, const SDL_FPoint * fpoints, const int count) static
{
    bool result;
    bool isstack;
    SDL_FRect *frects;
    int i;
    if (count < 1) {
        return true;
    }
    frects = SDL_small_alloc(SDL_FRect, count, &isstack);
    if (!frects) {
        return false;
    }
    const SDL_RenderViewState *view = renderer->view;
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    for (i = 0; i < count; ++i) {
        frects[i].x = fpoints[i].x * scale_x;
        frects[i].y = fpoints[i].y * scale_y;
        frects[i].w = scale_x;
        frects[i].h = scale_y;
    }
    result = QueueCmdFillRects(renderer, frects, count);
    SDL_small_free(frects, isstack);
    return result;
}
References count, SDL_RenderViewState::current_scale, SDL_FRect::h, QueueCmdFillRects(), SDL_small_alloc, SDL_small_free, SDL_Renderer::view, SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by RenderLineBresenham(), and SDL_RenderPoints().
SDL_AddSupportedTextureFormat()
bool SDL_AddSupportedTextureFormat (SDL_Renderer * renderer, SDL_PixelFormat format)
{
    SDL_PixelFormat *texture_formats = (SDL_PixelFormat *)SDL_realloc((void *)renderer->texture_formats, (renderer->num_texture_formats + 2) * sizeof(SDL_PixelFormat));
    if (!texture_formats) {
        return false;
    }
    texture_formats[renderer->num_texture_formats++] = format;
    texture_formats[renderer->num_texture_formats] = SDL_PIXELFORMAT_UNKNOWN;
    renderer->texture_formats = texture_formats;
    SDL_SetPointerProperty(SDL_GetRendererProperties(renderer), SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER, texture_formats);
    return true;
}
References SDL_Renderer::num_texture_formats, SDL_GetRendererProperties(), SDL_PIXELFORMAT_UNKNOWN, SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER, SDL_realloc(), SDL_SetPointerProperty(), and SDL_Renderer::texture_formats.
SDL_AddVulkanRenderSemaphores()
bool SDL_AddVulkanRenderSemaphores (SDL_Renderer * renderer, Uint32 wait_stage_mask, Sint64 wait_semaphore, Sint64 signal_semaphore)
Add a set of synchronization semaphores for the current frame.
The Vulkan renderer will wait for wait_semaphore before submitting rendering commands and signal signal_semaphore after rendering commands are complete for this frame.
This should be called each frame that you want semaphore synchronization. The Vulkan renderer may have multiple frames in flight on the GPU, so you should have multiple semaphores that are used for synchronization. Querying SDL_PROP_RENDERER_VULKAN_SWAPCHAIN_IMAGE_COUNT_NUMBER will give you the maximum number of semaphores you'll need.
Parameters
renderer the rendering context.
wait_stage_mask the VkPipelineStageFlags for the wait.
wait_semaphore a VkSempahore to wait on before rendering the current frame, or 0 if not needed.
signal_semaphore a VkSempahore that SDL will signal when rendering for the current frame is complete, or 0 if not needed.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
It is NOT safe to call this function from two threads at once.
Since
This function is available since SDL 3.2.0.
{
    CHECK_RENDERER_MAGIC(renderer, false);
    if (!renderer->AddVulkanRenderSemaphores) {
        return SDL_Unsupported();
    }
    return renderer->AddVulkanRenderSemaphores(renderer, wait_stage_mask, wait_semaphore, signal_semaphore);
}
References SDL_Renderer::AddVulkanRenderSemaphores, CHECK_RENDERER_MAGIC, and SDL_Unsupported.
SDL_AllocateRenderVertices()
void * SDL_AllocateRenderVertices (SDL_Renderer * renderer, size_t numbytes, size_t alignment, size_t * offset)
{
    const size_t needed = renderer->vertex_data_used + numbytes + alignment;
    const size_t current_offset = renderer->vertex_data_used;
    const size_t aligner = (alignment && ((current_offset & (alignment - 1)) != 0)) ? (alignment - (current_offset & (alignment - 1))) : 0;
    const size_t aligned = current_offset + aligner;
    if (renderer->vertex_data_allocation < needed) {
        const size_t current_allocation = renderer->vertex_data ? renderer->vertex_data_allocation : 1024;
        size_t newsize = current_allocation * 2;
        void *ptr;
        while (newsize < needed) {
            newsize *= 2;
        }
        ptr = SDL_realloc(renderer->vertex_data, newsize);
        if (!ptr) {
            return NULL;
        }
        renderer->vertex_data = ptr;
        renderer->vertex_data_allocation = newsize;
    }
    if (offset) {
        *offset = aligned;
    }
    renderer->vertex_data_used += aligner + numbytes;
    return ((Uint8 *)renderer->vertex_data) + aligned;
}
References NULL, SDL_realloc(), SDL_Renderer::vertex_data, SDL_Renderer::vertex_data_allocation, and SDL_Renderer::vertex_data_used.
SDL_CalculateSimulatedVSyncInterval()
void SDL_CalculateSimulatedVSyncInterval (SDL_Renderer * renderer, SDL_Window * window) static
{
    SDL_DisplayID displayID = SDL_GetDisplayForWindow(window);
    const SDL_DisplayMode *mode;
    int refresh_num, refresh_den;
    if (displayID == 0) {
        displayID = SDL_GetPrimaryDisplay();
    }
    mode = SDL_GetDesktopDisplayMode(displayID);
    if (mode && mode->refresh_rate_numerator > 0 && mode->refresh_rate_denominator > 0) {
        refresh_num = mode->refresh_rate_numerator;
        refresh_den = mode->refresh_rate_denominator;
    } else {
        // Pick a good default refresh rate
        refresh_num = 60;
        refresh_den = 1;
    }
    // Flip numerator and denominator to change from framerate to interval
    renderer->simulate_vsync_interval_ns = (SDL_NS_PER_SECOND * refresh_den) / refresh_num;
}
References SDL_DisplayMode::refresh_rate_denominator, SDL_DisplayMode::refresh_rate_numerator, SDL_GetDesktopDisplayMode(), SDL_GetDisplayForWindow(), SDL_GetPrimaryDisplay(), SDL_NS_PER_SECOND, and SDL_Renderer::simulate_vsync_interval_ns.
Referenced by SDL_CreateRendererWithProperties().
SDL_ComposeCustomBlendMode()
SDL_BlendMode SDL_ComposeCustomBlendMode (SDL_BlendFactor srcColorFactor, SDL_BlendFactor dstColorFactor, SDL_BlendOperation colorOperation, SDL_BlendFactor srcAlphaFactor, SDL_BlendFactor dstAlphaFactor, SDL_BlendOperation alphaOperation)
Compose a custom blend mode for renderers.
The functions SDL_SetRenderDrawBlendMode and SDL_SetTextureBlendMode accept the SDL_BlendMode returned by this function if the renderer supports it.
A blend mode controls how the pixels from a drawing operation (source) get combined with the pixels from the render target (destination). First, the components of the source and destination pixels get multiplied with their blend factors. Then, the blend operation takes the two products and calculates the result that will get stored in the render target.
Expressed in pseudocode, it would look like this:
dstRGB = colorOperation(srcRGB * srcColorFactor, dstRGB * dstColorFactor);
dstA = alphaOperation(srcA * srcAlphaFactor, dstA * dstAlphaFactor);
Where the functions colorOperation(src, dst) and alphaOperation(src, dst) can return one of the following:
src + dst
src - dst
dst - src
min(src, dst)
max(src, dst)
The red, green, and blue components are always multiplied with the first, second, and third components of the SDL_BlendFactor, respectively. The fourth component is not used.
The alpha component is always multiplied with the fourth component of the SDL_BlendFactor. The other components are not used in the alpha calculation.
Support for these blend modes varies for each renderer. To check if a specific SDL_BlendMode is supported, create a renderer and pass it to either SDL_SetRenderDrawBlendMode or SDL_SetTextureBlendMode. They will return with an error if the blend mode is not supported.
This list describes the support of custom blend modes for each renderer. All renderers support the four blend modes listed in the SDL_BlendMode enumeration.
direct3d: Supports all operations with all factors. However, some factors produce unexpected results with SDL_BLENDOPERATION_MINIMUM and SDL_BLENDOPERATION_MAXIMUM.
direct3d11: Same as Direct3D 9.
opengl: Supports the SDL_BLENDOPERATION_ADD operation with all factors. OpenGL versions 1.1, 1.2, and 1.3 do not work correctly here.
opengles2: Supports the SDL_BLENDOPERATION_ADD, SDL_BLENDOPERATION_SUBTRACT, SDL_BLENDOPERATION_REV_SUBTRACT operations with all factors.
psp: No custom blend mode support.
software: No custom blend mode support.
Some renderers do not provide an alpha component for the default render target. The SDL_BLENDFACTOR_DST_ALPHA and SDL_BLENDFACTOR_ONE_MINUS_DST_ALPHA factors do not have an effect in this case.
Parameters
srcColorFactor the SDL_BlendFactor applied to the red, green, and blue components of the source pixels.
dstColorFactor the SDL_BlendFactor applied to the red, green, and blue components of the destination pixels.
colorOperation the SDL_BlendOperation used to combine the red, green, and blue components of the source and destination pixels.
srcAlphaFactor the SDL_BlendFactor applied to the alpha component of the source pixels.
dstAlphaFactor the SDL_BlendFactor applied to the alpha component of the destination pixels.
alphaOperation the SDL_BlendOperation used to combine the alpha component of the source and destination pixels.
Returns
an SDL_BlendMode that represents the chosen factors and operations.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderDrawBlendMode
SDL_GetRenderDrawBlendMode
SDL_SetTextureBlendMode
SDL_GetTextureBlendMode
{
    SDL_BlendMode blendMode = SDL_COMPOSE_BLENDMODE(srcColorFactor, dstColorFactor, colorOperation,
                                                    srcAlphaFactor, dstAlphaFactor, alphaOperation);
    return SDL_GetShortBlendMode(blendMode);
}
References SDL_COMPOSE_BLENDMODE, and SDL_GetShortBlendMode().
Referenced by SDL_RenderApplyWindowShape().
SDL_ConvertEventToRenderCoordinates()
bool SDL_ConvertEventToRenderCoordinates (SDL_Renderer * renderer, SDL_Event * event)
Convert the coordinates in an event to render coordinates.
This takes into account several states:
The window dimensions.
The logical presentation settings (SDL_SetRenderLogicalPresentation)
The scale (SDL_SetRenderScale)
The viewport (SDL_SetRenderViewport)
Various event types are converted with this function: mouse, touch, pen, etc.
Touch coordinates are converted from normalized coordinates in the window to non-normalized rendering coordinates.
Relative mouse coordinates (xrel and yrel event fields) are also converted. Applications that do not want these fields converted should use SDL_RenderCoordinatesFromWindow() on the specific event fields instead of converting the entire event structure.
Once converted, coordinates may be outside the rendering area.
Parameters
renderer the rendering context.
event the event to modify.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderCoordinatesFromWindow
{
    CHECK_RENDERER_MAGIC(renderer, false);
    if (event->type == SDL_EVENT_MOUSE_MOTION) {
        SDL_Window *window = SDL_GetWindowFromID(event->motion.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->motion.x, event->motion.y, &event->motion.x, &event->motion.y);
            SDL_RenderVectorFromWindow(renderer, event->motion.xrel, event->motion.yrel, &event->motion.xrel, &event->motion.yrel);
        }
    } else if (event->type == SDL_EVENT_MOUSE_BUTTON_DOWN ||
               event->type == SDL_EVENT_MOUSE_BUTTON_UP) {
        SDL_Window *window = SDL_GetWindowFromID(event->button.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->button.x, event->button.y, &event->button.x, &event->button.y);
        }
    } else if (event->type == SDL_EVENT_MOUSE_WHEEL) {
        SDL_Window *window = SDL_GetWindowFromID(event->wheel.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->wheel.mouse_x,
                                            event->wheel.mouse_y,
                                            &event->wheel.mouse_x,
                                            &event->wheel.mouse_y);
        }
    } else if (event->type == SDL_EVENT_FINGER_DOWN ||
               event->type == SDL_EVENT_FINGER_UP ||
               event->type == SDL_EVENT_FINGER_CANCELED ||
               event->type == SDL_EVENT_FINGER_MOTION) {
        // FIXME: Are these events guaranteed to be window relative?
        if (renderer->window) {
            int w, h;
            if (!SDL_GetWindowSize(renderer->window, &w, &h)) {
                return false;
            }
            SDL_RenderCoordinatesFromWindow(renderer, event->tfinger.x * w, event->tfinger.y * h, &event->tfinger.x, &event->tfinger.y);
            SDL_RenderVectorFromWindow(renderer, event->tfinger.dx * w, event->tfinger.dy * h, &event->tfinger.dx, &event->tfinger.dy);
        }
    } else if (event->type == SDL_EVENT_PEN_MOTION) {
        SDL_Window *window = SDL_GetWindowFromID(event->pmotion.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->pmotion.x, event->pmotion.y, &event->pmotion.x, &event->pmotion.y);
        }
    } else if ((event->type == SDL_EVENT_PEN_DOWN) || (event->type == SDL_EVENT_PEN_UP)) {
        SDL_Window *window = SDL_GetWindowFromID(event->ptouch.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->ptouch.x, event->ptouch.y, &event->ptouch.x, &event->ptouch.y);
        }
    } else if ((event->type == SDL_EVENT_PEN_BUTTON_DOWN) || (event->type == SDL_EVENT_PEN_BUTTON_UP)) {
        SDL_Window *window = SDL_GetWindowFromID(event->pbutton.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->pbutton.x, event->pbutton.y, &event->pbutton.x, &event->pbutton.y);
        }
    } else if (event->type == SDL_EVENT_PEN_AXIS) {
        SDL_Window *window = SDL_GetWindowFromID(event->paxis.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->paxis.x, event->paxis.y, &event->paxis.x, &event->paxis.y);
        }
    } else if (event->type == SDL_EVENT_DROP_POSITION ||
               event->type == SDL_EVENT_DROP_FILE ||
               event->type == SDL_EVENT_DROP_TEXT ||
               event->type == SDL_EVENT_DROP_COMPLETE) {
        SDL_Window *window = SDL_GetWindowFromID(event->drop.windowID);
        if (window == renderer->window) {
            SDL_RenderCoordinatesFromWindow(renderer, event->drop.x, event->drop.y, &event->drop.x, &event->drop.y);
        }
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_EVENT_DROP_COMPLETE, SDL_EVENT_DROP_FILE, SDL_EVENT_DROP_POSITION, SDL_EVENT_DROP_TEXT, SDL_EVENT_FINGER_CANCELED, SDL_EVENT_FINGER_DOWN, SDL_EVENT_FINGER_MOTION, SDL_EVENT_FINGER_UP, SDL_EVENT_MOUSE_BUTTON_DOWN, SDL_EVENT_MOUSE_BUTTON_UP, SDL_EVENT_MOUSE_MOTION, SDL_EVENT_MOUSE_WHEEL, SDL_EVENT_PEN_AXIS, SDL_EVENT_PEN_BUTTON_DOWN, SDL_EVENT_PEN_BUTTON_UP, SDL_EVENT_PEN_DOWN, SDL_EVENT_PEN_MOTION, SDL_EVENT_PEN_UP, SDL_GetWindowFromID(), SDL_GetWindowSize(), SDL_RenderCoordinatesFromWindow(), SDL_RenderVectorFromWindow(), and SDL_Renderer::window.
SDL_ConvertFromLinear()
void SDL_ConvertFromLinear (SDL_FColor * color)
{
    color->r = SDL_sRGBfromLinear(color->r);
    color->g = SDL_sRGBfromLinear(color->g);
    color->b = SDL_sRGBfromLinear(color->b);
}
References SDL_FColor::b, SDL_FColor::g, SDL_FColor::r, and SDL_sRGBfromLinear().
SDL_ConvertToLinear()
void SDL_ConvertToLinear (SDL_FColor * color)
{
    color->r = SDL_sRGBtoLinear(color->r);
    color->g = SDL_sRGBtoLinear(color->g);
    color->b = SDL_sRGBtoLinear(color->b);
}
References SDL_FColor::b, SDL_FColor::g, SDL_FColor::r, and SDL_sRGBtoLinear().
SDL_CreateGPURenderer()
SDL_Renderer * SDL_CreateGPURenderer (SDL_Window * window, SDL_GPUShaderFormat format_flags, SDL_GPUDevice ** device)
Create a 2D GPU rendering context for a window, with support for the specified shader format.
This is a convenience function to create a SDL GPU backed renderer, intended to be used with SDL_GPURenderState. The resulting renderer will support shaders in one of the specified shader formats.
If no available GPU driver supports any of the specified shader formats, this function will fail.
Parameters
window the window where rendering is displayed.
format_flags a bitflag indicating which shader formats the app is able to provide.
device a pointer filled with the associated GPU device, or NULL on error.
Returns
a valid rendering context or NULL if there was an error; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateRendererWithProperties
SDL_GetGPUShaderFormats
SDL_CreateGPUShader
SDL_CreateGPURenderState
SDL_SetRenderGPUState
{
    if (!device) {
        SDL_InvalidParamError("device");
        return NULL;
    }
    *device = NULL;
    SDL_Renderer *renderer;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_RENDERER_CREATE_WINDOW_POINTER, window);
    if (format_flags & SDL_GPU_SHADERFORMAT_SPIRV) {
        SDL_SetBooleanProperty(props, SDL_PROP_RENDERER_CREATE_GPU_SHADERS_SPIRV_BOOLEAN, true);
    }
    if (format_flags & SDL_GPU_SHADERFORMAT_DXIL) {
        SDL_SetBooleanProperty(props, SDL_PROP_RENDERER_CREATE_GPU_SHADERS_DXIL_BOOLEAN, true);
    }
    if (format_flags & SDL_GPU_SHADERFORMAT_MSL) {
        SDL_SetBooleanProperty(props, SDL_PROP_RENDERER_CREATE_GPU_SHADERS_MSL_BOOLEAN, true);
    }
    SDL_SetStringProperty(props, SDL_PROP_RENDERER_CREATE_NAME_STRING, "gpu");
    renderer = SDL_CreateRendererWithProperties(props);
    if (renderer) {
        *device = (SDL_GPUDevice *)SDL_GetPointerProperty(SDL_GetRendererProperties(renderer), SDL_PROP_RENDERER_GPU_DEVICE_POINTER, NULL);
    }
    SDL_DestroyProperties(props);
    return renderer;
}
References NULL, SDL_CreateProperties(), SDL_CreateRendererWithProperties(), SDL_DestroyProperties(), SDL_GetPointerProperty(), SDL_GetRendererProperties(), SDL_GPU_SHADERFORMAT_DXIL, SDL_GPU_SHADERFORMAT_MSL, SDL_GPU_SHADERFORMAT_SPIRV, SDL_InvalidParamError, SDL_PROP_RENDERER_CREATE_GPU_SHADERS_DXIL_BOOLEAN, SDL_PROP_RENDERER_CREATE_GPU_SHADERS_MSL_BOOLEAN, SDL_PROP_RENDERER_CREATE_GPU_SHADERS_SPIRV_BOOLEAN, SDL_PROP_RENDERER_CREATE_NAME_STRING, SDL_PROP_RENDERER_CREATE_WINDOW_POINTER, SDL_PROP_RENDERER_GPU_DEVICE_POINTER, SDL_SetBooleanProperty(), SDL_SetPointerProperty(), and SDL_SetStringProperty().
SDL_CreateGPURenderState()
SDL_GPURenderState * SDL_CreateGPURenderState (SDL_Renderer * renderer, SDL_GPURenderStateDesc * desc)
Create custom GPU render state.
Parameters
renderer the renderer to use.
desc GPU render state description, initialized using SDL_INIT_INTERFACE().
Returns
a custom GPU render state or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should be called on the thread that created the renderer.
Since
This function is available since SDL 3.4.0.
See also
SDL_SetGPURenderStateFragmentUniforms
SDL_SetRenderGPUState
SDL_DestroyGPURenderState
{
    CHECK_RENDERER_MAGIC(renderer, NULL);
    if (!desc) {
        SDL_InvalidParamError("desc");
        return NULL;
    }
    if (desc->version < sizeof(*desc)) {
        // Update this to handle older versions of this interface
        SDL_SetError("Invalid desc, should be initialized with SDL_INIT_INTERFACE()");
        return NULL;
    }
    if (!desc->fragment_shader) {
        SDL_SetError("desc->fragment_shader is required");
        return NULL;
    }
    SDL_GPUDevice *device = (SDL_GPUDevice *)SDL_GetPointerProperty(renderer->props, SDL_PROP_RENDERER_GPU_DEVICE_POINTER, NULL);
    if (!device) {
        SDL_SetError("Renderer isn't associated with a GPU device");
        return NULL;
    }
    SDL_GPURenderState *state = (SDL_GPURenderState *)SDL_calloc(1, sizeof(*state));
    if (!state) {
        return NULL;
    }
    state->renderer = renderer;
    state->fragment_shader = desc->fragment_shader;
    if (desc->num_sampler_bindings > 0) {
        state->sampler_bindings = (SDL_GPUTextureSamplerBinding *)SDL_calloc(desc->num_sampler_bindings, sizeof(*state->sampler_bindings));
        if (!state->sampler_bindings) {
            SDL_DestroyGPURenderState(state);
            return NULL;
        }
        SDL_memcpy(state->sampler_bindings, desc->sampler_bindings, desc->num_sampler_bindings * sizeof(*state->sampler_bindings));
        state->num_sampler_bindings = desc->num_sampler_bindings;
    }
    if (desc->num_storage_textures > 0) {
        state->storage_textures = (SDL_GPUTexture **)SDL_calloc(desc->num_storage_textures, sizeof(*state->storage_textures));
        if (!state->storage_textures) {
            SDL_DestroyGPURenderState(state);
            return NULL;
        }
        SDL_memcpy(state->storage_textures, desc->storage_textures, desc->num_storage_textures * sizeof(*state->storage_textures));
        state->num_storage_textures = desc->num_storage_textures;
    }
    if (desc->num_storage_buffers > 0) {
        state->storage_buffers = (SDL_GPUBuffer **)SDL_calloc(desc->num_storage_buffers, sizeof(*state->storage_buffers));
        if (!state->storage_buffers) {
            SDL_DestroyGPURenderState(state);
            return NULL;
        }
        SDL_memcpy(state->storage_buffers, desc->storage_buffers, desc->num_storage_buffers * sizeof(*state->storage_buffers));
        state->num_storage_buffers = desc->num_storage_buffers;
    }
    return state;
}
References CHECK_RENDERER_MAGIC, SDL_GPURenderState::fragment_shader, SDL_GPURenderStateDesc::fragment_shader, NULL, SDL_GPURenderState::num_sampler_bindings, SDL_GPURenderStateDesc::num_sampler_bindings, SDL_GPURenderState::num_storage_buffers, SDL_GPURenderStateDesc::num_storage_buffers, SDL_GPURenderState::num_storage_textures, SDL_GPURenderStateDesc::num_storage_textures, SDL_Renderer::props, SDL_GPURenderState::renderer, SDL_GPURenderState::sampler_bindings, SDL_GPURenderStateDesc::sampler_bindings, SDL_calloc(), SDL_DestroyGPURenderState(), SDL_GetPointerProperty(), SDL_InvalidParamError, SDL_memcpy, SDL_PROP_RENDERER_GPU_DEVICE_POINTER, SDL_SetError(), SDL_GPURenderState::storage_buffers, SDL_GPURenderStateDesc::storage_buffers, SDL_GPURenderState::storage_textures, SDL_GPURenderStateDesc::storage_textures, and SDL_GPURenderStateDesc::version.
SDL_CreateRenderer()
SDL_Renderer * SDL_CreateRenderer (SDL_Window * window, const char * name)
Create a 2D rendering context for a window.
If you want a specific renderer, you can specify its name here. A list of available renderers can be obtained by calling SDL_GetRenderDriver() multiple times, with indices from 0 to SDL_GetNumRenderDrivers()-1. If you don't need a specific renderer, specify NULL and SDL will attempt to choose the best option for you, based on what is available on the user's system.
If name is a comma-separated list, SDL will try each name, in the order listed, until one succeeds or all of them fail.
By default the rendering size matches the window size in pixels, but you can call SDL_SetRenderLogicalPresentation() to change the content size and scaling options.
Parameters
window the window where rendering is displayed.
name the name of the rendering driver to initialize, or NULL to let SDL choose one.
Returns
a valid rendering context or NULL if there was an error; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRendererWithProperties
SDL_CreateSoftwareRenderer
SDL_DestroyRenderer
SDL_GetNumRenderDrivers
SDL_GetRenderDriver
SDL_GetRendererName
{
    SDL_Renderer *renderer;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_RENDERER_CREATE_WINDOW_POINTER, window);
    SDL_SetStringProperty(props, SDL_PROP_RENDERER_CREATE_NAME_STRING, name);
    renderer = SDL_CreateRendererWithProperties(props);
    SDL_DestroyProperties(props);
    return renderer;
}
References SDL_CreateProperties(), SDL_CreateRendererWithProperties(), SDL_DestroyProperties(), SDL_PROP_RENDERER_CREATE_NAME_STRING, SDL_PROP_RENDERER_CREATE_WINDOW_POINTER, SDL_SetPointerProperty(), and SDL_SetStringProperty().
Referenced by SDL_CreateWindowAndRenderer(), and SDL_CreateWindowTexture().
SDL_CreateRendererWithProperties()
SDL_Renderer * SDL_CreateRendererWithProperties (SDL_PropertiesID props)
Create a 2D rendering context for a window, with the specified properties.
These are the supported properties:
SDL_PROP_RENDERER_CREATE_NAME_STRING: the name of the rendering driver to use, if a specific one is desired
SDL_PROP_RENDERER_CREATE_WINDOW_POINTER: the window where rendering is displayed, required if this isn't a software renderer using a surface
SDL_PROP_RENDERER_CREATE_SURFACE_POINTER: the surface where rendering is displayed, if you want a software renderer without a window
SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER: an SDL_Colorspace value describing the colorspace for output to the display, defaults to SDL_COLORSPACE_SRGB. The direct3d11, direct3d12, and metal renderers support SDL_COLORSPACE_SRGB_LINEAR, which is a linear color space and supports HDR output. If you select SDL_COLORSPACE_SRGB_LINEAR, drawing still uses the sRGB colorspace, but values can go beyond 1.0 and float (linear) format textures can be used for HDR content.
SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER: non-zero if you want present synchronized with the refresh rate. This property can take any value that is supported by SDL_SetRenderVSync() for the renderer.
With the SDL GPU renderer:
SDL_PROP_RENDERER_CREATE_GPU_SHADERS_SPIRV_BOOLEAN: the app is able to provide SPIR-V shaders to SDL_GPURenderState, optional.
SDL_PROP_RENDERER_CREATE_GPU_SHADERS_DXIL_BOOLEAN: the app is able to provide DXIL shaders to SDL_GPURenderState, optional.
SDL_PROP_RENDERER_CREATE_GPU_SHADERS_MSL_BOOLEAN: the app is able to provide MSL shaders to SDL_GPURenderState, optional.
With the vulkan renderer:
SDL_PROP_RENDERER_CREATE_VULKAN_INSTANCE_POINTER: the VkInstance to use with the renderer, optional.
SDL_PROP_RENDERER_CREATE_VULKAN_SURFACE_NUMBER: the VkSurfaceKHR to use with the renderer, optional.
SDL_PROP_RENDERER_CREATE_VULKAN_PHYSICAL_DEVICE_POINTER: the VkPhysicalDevice to use with the renderer, optional.
SDL_PROP_RENDERER_CREATE_VULKAN_DEVICE_POINTER: the VkDevice to use with the renderer, optional.
SDL_PROP_RENDERER_CREATE_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER: the queue family index used for rendering.
SDL_PROP_RENDERER_CREATE_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER: the queue family index used for presentation.
Parameters
props the properties to use.
Returns
a valid rendering context or NULL if there was an error; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProperties
SDL_CreateRenderer
SDL_CreateSoftwareRenderer
SDL_DestroyRenderer
SDL_GetRendererName
{
#ifndef SDL_RENDER_DISABLED
    SDL_Window *window = (SDL_Window *)SDL_GetPointerProperty(props, SDL_PROP_RENDERER_CREATE_WINDOW_POINTER, NULL);
    SDL_Surface *surface = (SDL_Surface *)SDL_GetPointerProperty(props, SDL_PROP_RENDERER_CREATE_SURFACE_POINTER, NULL);
    const char *driver_name = SDL_GetStringProperty(props, SDL_PROP_RENDERER_CREATE_NAME_STRING, NULL);
    const char *hint;
    SDL_PropertiesID new_props;
#ifdef SDL_PLATFORM_ANDROID
    if (!Android_WaitActiveAndLockActivity()) {
        return NULL;
    }
#endif
    SDL_Renderer *renderer = (SDL_Renderer *)SDL_calloc(1, sizeof(*renderer));
    if (!renderer) {
        goto error;
    }
    SDL_SetObjectValid(renderer, SDL_OBJECT_TYPE_RENDERER, true);
    if ((!window && !surface) || (window && surface)) {
        SDL_InvalidParamError("window");
        goto error;
    }
    if (window && SDL_WindowHasSurface(window)) {
        SDL_SetError("Surface already associated with window");
        goto error;
    }
    if (window && SDL_GetRenderer(window)) {
        SDL_SetError("Renderer already associated with window");
        goto error;
    }
    hint = SDL_GetHint(SDL_HINT_RENDER_VSYNC);
    if (hint && *hint) {
        SDL_SetNumberProperty(props, SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER, SDL_GetHintBoolean(SDL_HINT_RENDER_VSYNC, true));
    }
    if (surface) {
#ifdef SDL_VIDEO_RENDER_SW
        const bool rc = SW_CreateRendererForSurface(renderer, surface, props);
#else
        const bool rc = SDL_SetError("SDL not built with software renderer");
#endif
        if (!rc) {
            goto error;
        }
    } else {
        bool rc = false;
        if (!driver_name) {
            driver_name = SDL_GetHint(SDL_HINT_RENDER_DRIVER);
        }
        if (driver_name && *driver_name != 0) {
            const char *driver_attempt = driver_name;
            while (driver_attempt && *driver_attempt != 0 && !rc) {
                const char *driver_attempt_end = SDL_strchr(driver_attempt, ',');
                const size_t driver_attempt_len = (driver_attempt_end) ? (driver_attempt_end - driver_attempt) : SDL_strlen(driver_attempt);
                for (int i = 0; render_drivers[i]; i++) {
                    const SDL_RenderDriver *driver = render_drivers[i];
                    if ((driver_attempt_len == SDL_strlen(driver->name)) && (SDL_strncasecmp(driver->name, driver_attempt, driver_attempt_len) == 0)) {
                        rc = driver->CreateRenderer(renderer, window, props);
                        if (rc) {
                            break;
                        }
                    }
                }
                driver_attempt = (driver_attempt_end) ? (driver_attempt_end + 1) : NULL;
            }
        } else {
            for (int i = 0; render_drivers[i]; i++) {
                const SDL_RenderDriver *driver = render_drivers[i];
                rc = driver->CreateRenderer(renderer, window, props);
                if (rc) {
                    break;
                }
                SDL_DestroyRendererWithoutFreeing(renderer);
                SDL_zerop(renderer);  // make sure we don't leave function pointers from a previous CreateRenderer() in this struct.
            }
        }
        if (rc) {
            SDL_DebugLogBackend("render", renderer->name);
        } else {
            if (driver_name) {
                SDL_SetError("%s not available", driver_name);
            } else {
                SDL_SetError("Couldn't find matching render driver");
            }
            goto error;
        }
    }
    VerifyDrawQueueFunctions(renderer);
    renderer->window = window;
    renderer->target_mutex = SDL_CreateMutex();
    if (surface) {
        renderer->main_view.pixel_w = surface->w;
        renderer->main_view.pixel_h = surface->h;
    }
    renderer->main_view.viewport.w = -1;
    renderer->main_view.viewport.h = -1;
    renderer->main_view.scale.x = 1.0f;
    renderer->main_view.scale.y = 1.0f;
    renderer->main_view.logical_scale.x = 1.0f;
    renderer->main_view.logical_scale.y = 1.0f;
    renderer->main_view.current_scale.x = 1.0f;
    renderer->main_view.current_scale.y = 1.0f;
    renderer->view = &renderer->main_view;
    renderer->dpi_scale.x = 1.0f;
    renderer->dpi_scale.y = 1.0f;
    UpdatePixelViewport(renderer, &renderer->main_view);
    UpdatePixelClipRect(renderer, &renderer->main_view);
    UpdateMainViewDimensions(renderer);
    // new textures start at zero, so we start at 1 so first render doesn't flush by accident.
    renderer->render_command_generation = 1;
    if (renderer->software) {
        // Software renderer always uses line method, for speed
        renderer->line_method = SDL_RENDERLINEMETHOD_LINES;
    } else {
        renderer->line_method = SDL_GetRenderLineMethod();
    }
    renderer->scale_mode = SDL_SCALEMODE_LINEAR;
    renderer->SDR_white_point = 1.0f;
    renderer->HDR_headroom = 1.0f;
    renderer->desired_color_scale = 1.0f;
    renderer->color_scale = 1.0f;
    if (window) {
        if (SDL_GetWindowFlags(window) & SDL_WINDOW_TRANSPARENT) {
            renderer->transparent_window = true;
        }
        if (SDL_GetWindowFlags(window) & (SDL_WINDOW_HIDDEN | SDL_WINDOW_MINIMIZED)) {
            renderer->hidden = true;
        }
    }
    new_props = SDL_GetRendererProperties(renderer);
    SDL_SetStringProperty(new_props, SDL_PROP_RENDERER_NAME_STRING, renderer->name);
    if (window) {
        SDL_SetPointerProperty(new_props, SDL_PROP_RENDERER_WINDOW_POINTER, window);
    }
    if (surface) {
        SDL_SetPointerProperty(new_props, SDL_PROP_RENDERER_SURFACE_POINTER, surface);
    }
    SDL_SetNumberProperty(new_props, SDL_PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER, renderer->output_colorspace);
    UpdateHDRProperties(renderer);
    if (window) {
        SDL_SetPointerProperty(SDL_GetWindowProperties(window), SDL_PROP_WINDOW_RENDERER_POINTER, renderer);
        SDL_AddWindowRenderer(window, renderer);
    }
    SDL_SetRenderViewport(renderer, NULL);
    if (window) {
        SDL_AddWindowEventWatch(SDL_WINDOW_EVENT_WATCH_NORMAL, SDL_RendererEventWatch, renderer);
    }
    int vsync = (int)SDL_GetNumberProperty(props, SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER, 0);
    SDL_SetRenderVSync(renderer, vsync);
    SDL_CalculateSimulatedVSyncInterval(renderer, window);
    SDL_LogInfo(SDL_LOG_CATEGORY_RENDER,
                "Created renderer: %s", renderer->name);
    renderer->next = SDL_renderers;
    SDL_renderers = renderer;
#ifdef SDL_PLATFORM_ANDROID
    Android_UnlockActivityMutex();
#endif
    SDL_ClearError();
    return renderer;
error:
#ifdef SDL_PLATFORM_ANDROID
    Android_UnlockActivityMutex();
#endif
    if (renderer) {
        SDL_DestroyRenderer(renderer);
    }
    return NULL;
#else
    SDL_SetError("SDL not built with rendering support");
    return NULL;
#endif
}
References Android_UnlockActivityMutex(), Android_WaitActiveAndLockActivity(), SDL_Renderer::color_scale, SDL_RenderDriver::CreateRenderer, SDL_RenderViewState::current_scale, SDL_Renderer::desired_color_scale, SDL_Renderer::dpi_scale, SDL_Rect::h, SDL_Renderer::HDR_headroom, SDL_Renderer::hidden, SDL_Renderer::line_method, SDL_RenderViewState::logical_scale, SDL_Renderer::main_view, SDL_RenderDriver::name, SDL_Renderer::name, SDL_Renderer::next, NULL, SDL_Renderer::output_colorspace, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, SDL_Renderer::render_command_generation, render_drivers, SDL_RenderViewState::scale, SDL_Renderer::scale_mode, SDL_AddWindowEventWatch(), SDL_AddWindowRenderer(), SDL_CalculateSimulatedVSyncInterval(), SDL_calloc(), SDL_ClearError(), SDL_CreateMutex(), SDL_DebugLogBackend(), SDL_DestroyRenderer(), SDL_DestroyRendererWithoutFreeing(), SDL_GetHint(), SDL_GetHintBoolean(), SDL_GetNumberProperty(), SDL_GetPointerProperty(), SDL_GetRenderer(), SDL_GetRendererProperties(), SDL_GetRenderLineMethod(), SDL_GetStringProperty(), SDL_GetWindowFlags(), SDL_GetWindowProperties(), SDL_HINT_RENDER_DRIVER, SDL_HINT_RENDER_VSYNC, SDL_InvalidParamError, SDL_LOG_CATEGORY_RENDER, SDL_LogInfo(), SDL_OBJECT_TYPE_RENDERER, SDL_PROP_RENDERER_CREATE_NAME_STRING, SDL_PROP_RENDERER_CREATE_PRESENT_VSYNC_NUMBER, SDL_PROP_RENDERER_CREATE_SURFACE_POINTER, SDL_PROP_RENDERER_CREATE_WINDOW_POINTER, SDL_PROP_RENDERER_NAME_STRING, SDL_PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER, SDL_PROP_RENDERER_SURFACE_POINTER, SDL_PROP_RENDERER_WINDOW_POINTER, SDL_PROP_WINDOW_RENDERER_POINTER, SDL_RendererEventWatch(), SDL_renderers, SDL_RENDERLINEMETHOD_LINES, SDL_SCALEMODE_LINEAR, SDL_SetError(), SDL_SetNumberProperty(), SDL_SetObjectValid(), SDL_SetPointerProperty(), SDL_SetRenderViewport(), SDL_SetRenderVSync(), SDL_SetStringProperty(), SDL_strchr(), SDL_strlen(), SDL_strncasecmp(), SDL_WINDOW_EVENT_WATCH_NORMAL, SDL_WINDOW_HIDDEN, SDL_WINDOW_MINIMIZED, SDL_WINDOW_TRANSPARENT, SDL_WindowHasSurface(), SDL_zerop, SDL_Renderer::SDR_white_point, SDL_Renderer::software, SW_CreateRendererForSurface(), SDL_Renderer::target_mutex, SDL_Renderer::transparent_window, UpdateHDRProperties(), UpdateMainViewDimensions(), UpdatePixelClipRect(), UpdatePixelViewport(), VerifyDrawQueueFunctions(), SDL_Renderer::view, SDL_RenderViewState::viewport, SDL_Rect::w, SDL_Renderer::window, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_CreateGPURenderer(), SDL_CreateRenderer(), and SDL_CreateSoftwareRenderer().
SDL_CreateSoftwareRenderer()
SDL_Renderer * SDL_CreateSoftwareRenderer (SDL_Surface * surface)
Create a 2D software rendering context for a surface.
Two other API which can be used to create SDL_Renderer: SDL_CreateRenderer() and SDL_CreateWindowAndRenderer(). These can also create a software renderer, but they are intended to be used with an SDL_Window as the final destination and not an SDL_Surface.
Parameters
surface the SDL_Surface structure representing the surface where rendering is done.
Returns
a valid rendering context or NULL if there was an error; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_DestroyRenderer
{
#ifdef SDL_VIDEO_RENDER_SW
    SDL_Renderer *renderer;
    if (!surface) {
        SDL_InvalidParamError("surface");
        return NULL;
    }
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetPointerProperty(props, SDL_PROP_RENDERER_CREATE_SURFACE_POINTER, surface);
    renderer = SDL_CreateRendererWithProperties(props);
    SDL_DestroyProperties(props);
    return renderer;
#else
    SDL_SetError("SDL not built with rendering support");
    return NULL;
#endif // !SDL_RENDER_DISABLED
}
References NULL, SDL_CreateProperties(), SDL_CreateRendererWithProperties(), SDL_DestroyProperties(), SDL_InvalidParamError, SDL_PROP_RENDERER_CREATE_SURFACE_POINTER, SDL_SetError(), and SDL_SetPointerProperty().
SDL_CreateTexture()
SDL_Texture * SDL_CreateTexture (SDL_Renderer * renderer, SDL_PixelFormat format, SDL_TextureAccess access, int w, int h)
Create a texture for a rendering context.
The contents of a texture when first created are not defined.
Parameters
renderer the rendering context.
format one of the enumerated values in SDL_PixelFormat.
access one of the enumerated values in SDL_TextureAccess.
w the width of the texture in pixels.
h the height of the texture in pixels.
Returns
the created texture or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTextureFromSurface
SDL_CreateTextureWithProperties
SDL_DestroyTexture
SDL_GetTextureSize
SDL_UpdateTexture
{
    SDL_Texture *texture;
    SDL_PropertiesID props = SDL_CreateProperties();
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER, format);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER, access);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER, w);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER, h);
    texture = SDL_CreateTextureWithProperties(renderer, props);
    SDL_DestroyProperties(props);
    return texture;
}
References SDL_CreateProperties(), SDL_CreateTextureWithProperties(), SDL_DestroyProperties(), SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER, SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER, SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER, SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER, and SDL_SetNumberProperty().
Referenced by SDL_CreateWindowTexture().
SDL_CreateTextureFromSurface()
SDL_Texture * SDL_CreateTextureFromSurface (SDL_Renderer * renderer, SDL_Surface * surface)
Create a texture from an existing surface.
The surface is not modified or freed by this function.
The SDL_TextureAccess hint for the created texture is SDL_TEXTUREACCESS_STATIC.
The pixel format of the created texture may be different from the pixel format of the surface, and can be queried using the SDL_PROP_TEXTURE_FORMAT_NUMBER property.
Parameters
renderer the rendering context.
surface the SDL_Surface structure containing pixel data used to fill the texture.
Returns
the created texture or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTexture
SDL_CreateTextureWithProperties
SDL_DestroyTexture
{
    bool needAlpha;
    int i;
    SDL_PixelFormat format = SDL_PIXELFORMAT_UNKNOWN;
    SDL_Palette *palette;
    SDL_Texture *texture;
    SDL_PropertiesID props;
    SDL_Colorspace surface_colorspace = SDL_COLORSPACE_UNKNOWN;
    SDL_Colorspace texture_colorspace = SDL_COLORSPACE_UNKNOWN;
    CHECK_RENDERER_MAGIC(renderer, NULL);
    if (!SDL_SurfaceValid(surface)) {
        SDL_InvalidParamError("SDL_CreateTextureFromSurface(): surface");
        return NULL;
    }
    // See what the best texture format is
    if (SDL_ISPIXELFORMAT_ALPHA(surface->format) || SDL_SurfaceHasColorKey(surface)) {
        needAlpha = true;
    } else {
        needAlpha = false;
    }
    // If Palette contains alpha values, promotes to alpha format
    palette = SDL_GetSurfacePalette(surface);
    if (palette) {
        bool is_opaque, has_alpha_channel;
        SDL_DetectPalette(palette, &is_opaque, &has_alpha_channel);
        if (!is_opaque) {
            needAlpha = true;
        }
    }
    // Try to have the best pixel format for the texture
    // No alpha, but a colorkey => promote to alpha
    if (!SDL_ISPIXELFORMAT_ALPHA(surface->format) && SDL_SurfaceHasColorKey(surface)) {
        if (surface->format == SDL_PIXELFORMAT_XRGB8888) {
            for (i = 0; i < renderer->num_texture_formats; ++i) {
                if (renderer->texture_formats[i] == SDL_PIXELFORMAT_ARGB8888) {
                    format = SDL_PIXELFORMAT_ARGB8888;
                    break;
                }
            }
        } else if (surface->format == SDL_PIXELFORMAT_XBGR8888) {
            for (i = 0; i < renderer->num_texture_formats; ++i) {
                if (renderer->texture_formats[i] == SDL_PIXELFORMAT_ABGR8888) {
                    format = SDL_PIXELFORMAT_ABGR8888;
                    break;
                }
            }
        }
    } else {
        // Exact match would be fine
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (renderer->texture_formats[i] == surface->format) {
                format = surface->format;
                break;
            }
        }
    }
    // Look for 10-bit pixel formats if needed
    if (format == SDL_PIXELFORMAT_UNKNOWN && SDL_ISPIXELFORMAT_10BIT(surface->format)) {
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (SDL_ISPIXELFORMAT_10BIT(renderer->texture_formats[i])) {
                format = renderer->texture_formats[i];
                break;
            }
        }
    }
    // Look for floating point pixel formats if needed
    if (format == SDL_PIXELFORMAT_UNKNOWN &&
        (SDL_ISPIXELFORMAT_10BIT(surface->format) || SDL_ISPIXELFORMAT_FLOAT(surface->format))) {
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (SDL_ISPIXELFORMAT_FLOAT(renderer->texture_formats[i])) {
                format = renderer->texture_formats[i];
                break;
            }
        }
    }
    // Fallback, choose a valid pixel format
    if (format == SDL_PIXELFORMAT_UNKNOWN) {
        format = renderer->texture_formats[0];
        for (i = 0; i < renderer->num_texture_formats; ++i) {
            if (!SDL_ISPIXELFORMAT_FOURCC(renderer->texture_formats[i]) &&
                SDL_ISPIXELFORMAT_ALPHA(renderer->texture_formats[i]) == needAlpha) {
                format = renderer->texture_formats[i];
                break;
            }
        }
    }
    surface_colorspace = SDL_GetSurfaceColorspace(surface);
    texture_colorspace = surface_colorspace;
    if (surface_colorspace == SDL_COLORSPACE_SRGB_LINEAR ||
        SDL_COLORSPACETRANSFER(surface_colorspace) == SDL_TRANSFER_CHARACTERISTICS_PQ) {
        if (SDL_ISPIXELFORMAT_FLOAT(format)) {
            texture_colorspace = SDL_COLORSPACE_SRGB_LINEAR;
        } else if (SDL_ISPIXELFORMAT_10BIT(format)) {
            texture_colorspace = SDL_COLORSPACE_HDR10;
        } else {
            texture_colorspace = SDL_COLORSPACE_SRGB;
        }
    }
    props = SDL_CreateProperties();
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER, texture_colorspace);
    if (surface_colorspace == texture_colorspace) {
        SDL_SetFloatProperty(props, SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT,
                             SDL_GetSurfaceSDRWhitePoint(surface, surface_colorspace));
    }
    SDL_SetFloatProperty(props, SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT,
                         SDL_GetSurfaceHDRHeadroom(surface, surface_colorspace));
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER, format);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER, SDL_TEXTUREACCESS_STATIC);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER, surface->w);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER, surface->h);
    texture = SDL_CreateTextureWithProperties(renderer, props);
    SDL_DestroyProperties(props);
    if (!texture) {
        return NULL;
    }
    if (!SDL_UpdateTextureFromSurface(texture, NULL, surface)) {
        SDL_DestroyTexture(texture);
        return NULL;
    }
    return texture;
}
References CHECK_RENDERER_MAGIC, NULL, SDL_Renderer::num_texture_formats, SDL_COLORSPACE_HDR10, SDL_COLORSPACE_SRGB, SDL_COLORSPACE_SRGB_LINEAR, SDL_COLORSPACE_UNKNOWN, SDL_COLORSPACETRANSFER, SDL_CreateProperties(), SDL_CreateTextureWithProperties(), SDL_DestroyProperties(), SDL_DestroyTexture(), SDL_DetectPalette(), SDL_GetSurfaceColorspace(), SDL_GetSurfaceHDRHeadroom(), SDL_GetSurfacePalette(), SDL_GetSurfaceSDRWhitePoint(), SDL_InvalidParamError, SDL_ISPIXELFORMAT_10BIT, SDL_ISPIXELFORMAT_ALPHA, SDL_ISPIXELFORMAT_FLOAT, SDL_ISPIXELFORMAT_FOURCC, SDL_PIXELFORMAT_ABGR8888, SDL_PIXELFORMAT_ARGB8888, SDL_PIXELFORMAT_UNKNOWN, SDL_PIXELFORMAT_XBGR8888, SDL_PIXELFORMAT_XRGB8888, SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER, SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER, SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER, SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT, SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER, SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT, SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER, SDL_SetFloatProperty(), SDL_SetNumberProperty(), SDL_SurfaceHasColorKey(), SDL_SurfaceValid(), SDL_TEXTUREACCESS_STATIC, SDL_TRANSFER_CHARACTERISTICS_PQ, SDL_UpdateTextureFromSurface(), and SDL_Renderer::texture_formats.
Referenced by CreateDebugTextAtlas(), and SDL_RenderApplyWindowShape().
SDL_CreateTextureWithProperties()
SDL_Texture * SDL_CreateTextureWithProperties (SDL_Renderer * renderer, SDL_PropertiesID props)
Create a texture for a rendering context with the specified properties.
These are the supported properties:
SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER: an SDL_Colorspace value describing the texture colorspace, defaults to SDL_COLORSPACE_SRGB_LINEAR for floating point textures, SDL_COLORSPACE_HDR10 for 10-bit textures, SDL_COLORSPACE_SRGB for other RGB textures and SDL_COLORSPACE_JPEG for YUV textures.
SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER: one of the enumerated values in SDL_PixelFormat, defaults to the best RGBA format for the renderer
SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER: one of the enumerated values in SDL_TextureAccess, defaults to SDL_TEXTUREACCESS_STATIC
SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER: the width of the texture in pixels, required
SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER: the height of the texture in pixels, required
SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT: for HDR10 and floating point textures, this defines the value of 100% diffuse white, with higher values being displayed in the High Dynamic Range headroom. This defaults to 100 for HDR10 textures and 1.0 for floating point textures.
SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT: for HDR10 and floating point textures, this defines the maximum dynamic range used by the content, in terms of the SDR white point. This would be equivalent to maxCLL / SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT for HDR10 content. If this is defined, any values outside the range supported by the display will be scaled into the available HDR headroom, otherwise they are clipped.
With the direct3d11 renderer:
SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_POINTER: the ID3D11Texture2D associated with the texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_U_POINTER: the ID3D11Texture2D associated with the U plane of a YUV texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_D3D11_TEXTURE_V_POINTER: the ID3D11Texture2D associated with the V plane of a YUV texture, if you want to wrap an existing texture.
With the direct3d12 renderer:
SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_POINTER: the ID3D12Resource associated with the texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_U_POINTER: the ID3D12Resource associated with the U plane of a YUV texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_D3D12_TEXTURE_V_POINTER: the ID3D12Resource associated with the V plane of a YUV texture, if you want to wrap an existing texture.
With the metal renderer:
SDL_PROP_TEXTURE_CREATE_METAL_PIXELBUFFER_POINTER: the CVPixelBufferRef associated with the texture, if you want to create a texture from an existing pixel buffer.
With the opengl renderer:
SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_NUMBER: the GLuint texture associated with the texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_UV_NUMBER: the GLuint texture associated with the UV plane of an NV12 texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_U_NUMBER: the GLuint texture associated with the U plane of a YUV texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_OPENGL_TEXTURE_V_NUMBER: the GLuint texture associated with the V plane of a YUV texture, if you want to wrap an existing texture.
With the opengles2 renderer:
SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_NUMBER: the GLuint texture associated with the texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_NUMBER: the GLuint texture associated with the texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_UV_NUMBER: the GLuint texture associated with the UV plane of an NV12 texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_U_NUMBER: the GLuint texture associated with the U plane of a YUV texture, if you want to wrap an existing texture.
SDL_PROP_TEXTURE_CREATE_OPENGLES2_TEXTURE_V_NUMBER: the GLuint texture associated with the V plane of a YUV texture, if you want to wrap an existing texture.
With the vulkan renderer:
SDL_PROP_TEXTURE_CREATE_VULKAN_TEXTURE_NUMBER: the VkImage with layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL associated with the texture, if you want to wrap an existing texture.
Parameters
renderer the rendering context.
props the properties to use.
Returns
the created texture or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateProperties
SDL_CreateTexture
SDL_CreateTextureFromSurface
SDL_DestroyTexture
SDL_GetTextureSize
SDL_UpdateTexture
{
    SDL_Texture *texture;
    SDL_PixelFormat format = (SDL_PixelFormat)SDL_GetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER, SDL_PIXELFORMAT_UNKNOWN);
    SDL_TextureAccess access = (SDL_TextureAccess)SDL_GetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER, SDL_TEXTUREACCESS_STATIC);
    int w = (int)SDL_GetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER, 0);
    int h = (int)SDL_GetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER, 0);
    SDL_Colorspace default_colorspace;
    bool texture_is_fourcc_and_target;
    CHECK_RENDERER_MAGIC(renderer, NULL);
    if (!format) {
        format = renderer->texture_formats[0];
    }
    if (SDL_BYTESPERPIXEL(format) == 0) {
        SDL_SetError("Invalid texture format");
        return NULL;
    }
    if (SDL_ISPIXELFORMAT_INDEXED(format)) {
        if (!IsSupportedFormat(renderer, format)) {
            SDL_SetError("Palettized textures are not supported");
            return NULL;
        }
    }
    if (w <= 0 || h <= 0) {
        SDL_SetError("Texture dimensions can't be 0");
        return NULL;
    }
    int max_texture_size = (int)SDL_GetNumberProperty(SDL_GetRendererProperties(renderer), SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER, 0);
    if (max_texture_size && (w > max_texture_size || h > max_texture_size)) {
        SDL_SetError("Texture dimensions are limited to %dx%d", max_texture_size, max_texture_size);
        return NULL;
    }
    default_colorspace = SDL_GetDefaultColorspaceForFormat(format);
    texture = (SDL_Texture *)SDL_calloc(1, sizeof(*texture));
    if (!texture) {
        return NULL;
    }
    texture->refcount = 1;
    SDL_SetObjectValid(texture, SDL_OBJECT_TYPE_TEXTURE, true);
    texture->colorspace = (SDL_Colorspace)SDL_GetNumberProperty(props, SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER, default_colorspace);
    texture->format = format;
    texture->access = access;
    texture->w = w;
    texture->h = h;
    texture->color.r = 1.0f;
    texture->color.g = 1.0f;
    texture->color.b = 1.0f;
    texture->color.a = 1.0f;
    texture->blendMode = SDL_ISPIXELFORMAT_ALPHA(format) ? SDL_BLENDMODE_BLEND : SDL_BLENDMODE_NONE;
    texture->scaleMode = renderer->scale_mode;
    texture->view.pixel_w = w;
    texture->view.pixel_h = h;
    texture->view.viewport.w = -1;
    texture->view.viewport.h = -1;
    texture->view.scale.x = 1.0f;
    texture->view.scale.y = 1.0f;
    texture->view.logical_scale.x = 1.0f;
    texture->view.logical_scale.y = 1.0f;
    texture->view.current_scale.x = 1.0f;
    texture->view.current_scale.y = 1.0f;
    texture->renderer = renderer;
    texture->next = renderer->textures;
    if (renderer->textures) {
        renderer->textures->prev = texture;
    }
    renderer->textures = texture;
    UpdatePixelViewport(renderer, &texture->view);
    UpdatePixelClipRect(renderer, &texture->view);
    texture->SDR_white_point = SDL_GetFloatProperty(props, SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT, SDL_GetDefaultSDRWhitePoint(texture->colorspace));
    texture->HDR_headroom = SDL_GetFloatProperty(props, SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT, SDL_GetDefaultHDRHeadroom(texture->colorspace));
    // FOURCC format cannot be used directly by renderer back-ends for target texture
    texture_is_fourcc_and_target = (access == SDL_TEXTUREACCESS_TARGET && SDL_ISPIXELFORMAT_FOURCC(format));
    if (!texture_is_fourcc_and_target && IsSupportedFormat(renderer, format)) {
        if (!renderer->CreateTexture(renderer, texture, props)) {
            SDL_DestroyTexture(texture);
            return NULL;
        }
    } else {
        SDL_PixelFormat closest_format;
        SDL_PropertiesID native_props = SDL_CreateProperties();
        if (!texture_is_fourcc_and_target) {
            closest_format = GetClosestSupportedFormat(renderer, format);
        } else {
            closest_format = renderer->texture_formats[0];
        }
        if (format == SDL_PIXELFORMAT_MJPG && closest_format == SDL_PIXELFORMAT_NV12) {
            SDL_SetNumberProperty(native_props, SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER, SDL_COLORSPACE_JPEG);
        } else {
            default_colorspace = SDL_GetDefaultColorspaceForFormat(closest_format);
            if (SDL_COLORSPACETYPE(texture->colorspace) == SDL_COLORSPACETYPE(default_colorspace)) {
                SDL_SetNumberProperty(native_props, SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER, texture->colorspace);
            } else {
                SDL_SetNumberProperty(native_props, SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER, default_colorspace);
            }
        }
        SDL_SetNumberProperty(native_props, SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER, closest_format);
        SDL_SetNumberProperty(native_props, SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER, texture->access);
        SDL_SetNumberProperty(native_props, SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER, texture->w);
        SDL_SetNumberProperty(native_props, SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER, texture->h);
        texture->native = SDL_CreateTextureWithProperties(renderer, native_props);
        SDL_DestroyProperties(native_props);
        if (!texture->native) {
            SDL_DestroyTexture(texture);
            return NULL;
        }
        SDL_SetPointerProperty(SDL_GetTextureProperties(texture->native), SDL_PROP_TEXTURE_PARENT_POINTER, texture);
        // Swap textures to have texture before texture->native in the list
        texture->native->next = texture->next;
        if (texture->native->next) {
            texture->native->next->prev = texture->native;
        }
        texture->prev = texture->native->prev;
        if (texture->prev) {
            texture->prev->next = texture;
        }
        texture->native->prev = texture;
        texture->next = texture->native;
        renderer->textures = texture;
        if (texture->format == SDL_PIXELFORMAT_MJPG) {
            // We have a custom decode + upload path for this
        } else if (SDL_ISPIXELFORMAT_FOURCC(texture->format)) {
#ifdef SDL_HAVE_YUV
            texture->yuv = SDL_SW_CreateYUVTexture(texture->format, texture->colorspace, w, h);
#else
            SDL_SetError("SDL not built with YUV support");
#endif
            if (!texture->yuv) {
                SDL_DestroyTexture(texture);
                return NULL;
            }
        } else if (access == SDL_TEXTUREACCESS_STREAMING) {
            // The pitch is 4 byte aligned
            texture->pitch = (((w * SDL_BYTESPERPIXEL(format)) + 3) & ~3);
            texture->pixels = SDL_calloc(1, (size_t)texture->pitch * h);
            if (!texture->pixels) {
                SDL_DestroyTexture(texture);
                return NULL;
            }
        }
    }
    // Now set the properties for the new texture
    props = SDL_GetTextureProperties(texture);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_COLORSPACE_NUMBER, texture->colorspace);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_FORMAT_NUMBER, texture->format);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_ACCESS_NUMBER, texture->access);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_WIDTH_NUMBER, texture->w);
    SDL_SetNumberProperty(props, SDL_PROP_TEXTURE_HEIGHT_NUMBER, texture->h);
    SDL_SetFloatProperty(props, SDL_PROP_TEXTURE_SDR_WHITE_POINT_FLOAT, texture->SDR_white_point);
    if (texture->HDR_headroom > 0.0f) {
        SDL_SetFloatProperty(props, SDL_PROP_TEXTURE_HDR_HEADROOM_FLOAT, texture->HDR_headroom);
    }
    return texture;
}
References SDL_FColor::a, SDL_Texture::access, SDL_FColor::b, SDL_Texture::blendMode, CHECK_RENDERER_MAGIC, SDL_Texture::color, SDL_Texture::colorspace, SDL_Renderer::CreateTexture, SDL_RenderViewState::current_scale, SDL_Texture::format, SDL_FColor::g, GetClosestSupportedFormat(), SDL_Rect::h, SDL_Texture::h, SDL_Texture::HDR_headroom, IsSupportedFormat(), SDL_RenderViewState::logical_scale, SDL_Texture::native, SDL_Texture::next, NULL, SDL_Texture::pitch, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, SDL_Texture::pixels, SDL_Texture::prev, SDL_FColor::r, SDL_Texture::refcount, SDL_Texture::renderer, SDL_RenderViewState::scale, SDL_Renderer::scale_mode, SDL_Texture::scaleMode, SDL_BLENDMODE_BLEND, SDL_BLENDMODE_NONE, SDL_BYTESPERPIXEL, SDL_calloc(), SDL_COLORSPACE_JPEG, SDL_COLORSPACETYPE, SDL_CreateProperties(), SDL_CreateTextureWithProperties(), SDL_DestroyProperties(), SDL_DestroyTexture(), SDL_GetDefaultColorspaceForFormat(), SDL_GetDefaultHDRHeadroom(), SDL_GetDefaultSDRWhitePoint(), SDL_GetFloatProperty(), SDL_GetNumberProperty(), SDL_GetRendererProperties(), SDL_GetTextureProperties(), SDL_ISPIXELFORMAT_ALPHA, SDL_ISPIXELFORMAT_FOURCC, SDL_ISPIXELFORMAT_INDEXED, SDL_OBJECT_TYPE_TEXTURE, SDL_PIXELFORMAT_MJPG, SDL_PIXELFORMAT_NV12, SDL_PIXELFORMAT_UNKNOWN, SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER, SDL_PROP_TEXTURE_ACCESS_NUMBER, SDL_PROP_TEXTURE_COLORSPACE_NUMBER, SDL_PROP_TEXTURE_CREATE_ACCESS_NUMBER, SDL_PROP_TEXTURE_CREATE_COLORSPACE_NUMBER, SDL_PROP_TEXTURE_CREATE_FORMAT_NUMBER, SDL_PROP_TEXTURE_CREATE_HDR_HEADROOM_FLOAT, SDL_PROP_TEXTURE_CREATE_HEIGHT_NUMBER, SDL_PROP_TEXTURE_CREATE_SDR_WHITE_POINT_FLOAT, SDL_PROP_TEXTURE_CREATE_WIDTH_NUMBER, SDL_PROP_TEXTURE_FORMAT_NUMBER, SDL_PROP_TEXTURE_HDR_HEADROOM_FLOAT, SDL_PROP_TEXTURE_HEIGHT_NUMBER, SDL_PROP_TEXTURE_PARENT_POINTER, SDL_PROP_TEXTURE_SDR_WHITE_POINT_FLOAT, SDL_PROP_TEXTURE_WIDTH_NUMBER, SDL_SetError(), SDL_SetFloatProperty(), SDL_SetNumberProperty(), SDL_SetObjectValid(), SDL_SetPointerProperty(), SDL_SW_CreateYUVTexture(), SDL_TEXTUREACCESS_STATIC, SDL_TEXTUREACCESS_STREAMING, SDL_TEXTUREACCESS_TARGET, SDL_Texture::SDR_white_point, SDL_Renderer::texture_formats, SDL_Renderer::textures, UpdatePixelClipRect(), UpdatePixelViewport(), SDL_Texture::view, SDL_RenderViewState::viewport, SDL_Rect::w, SDL_Texture::w, SDL_FPoint::x, SDL_FPoint::y, and SDL_Texture::yuv.
Referenced by SDL_CreateTexture(), SDL_CreateTextureFromSurface(), and SDL_CreateTextureWithProperties().
SDL_CreateWindowAndRenderer()
bool SDL_CreateWindowAndRenderer (const char * title, int width, int height, SDL_WindowFlags window_flags, SDL_Window ** window, SDL_Renderer ** renderer)
Create a window and default renderer.
Parameters
title the title of the window, in UTF-8 encoding.
width the width of the window.
height the height of the window.
window_flags the flags used to create the window (see SDL_CreateWindow()).
window a pointer filled with the window, or NULL on error.
renderer a pointer filled with the renderer, or NULL on error.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRenderer
SDL_CreateWindow
{
    bool hidden = (window_flags & SDL_WINDOW_HIDDEN) != 0;
    if (!window) {
        return SDL_InvalidParamError("window");
    }
    if (!renderer) {
        return SDL_InvalidParamError("renderer");
    }
    // Hide the window so if the renderer recreates it, we don't get a visual flash on screen
    window_flags |= SDL_WINDOW_HIDDEN;
    *window = SDL_CreateWindow(title, width, height, window_flags);
    if (!*window) {
        *renderer = NULL;
        return false;
    }
    *renderer = SDL_CreateRenderer(*window, NULL);
    if (!*renderer) {
        SDL_DestroyWindow(*window);
        *window = NULL;
        return false;
    }
    if (!hidden) {
        SDL_ShowWindow(*window);
    }
    return true;
}
References NULL, SDL_CreateRenderer(), SDL_CreateWindow(), SDL_DestroyWindow(), SDL_InvalidParamError, SDL_ShowWindow(), and SDL_WINDOW_HIDDEN.
SDL_DestroyGPURenderState()
void SDL_DestroyGPURenderState (SDL_GPURenderState * state)
Destroy custom GPU render state.
Parameters
state the state to destroy.
Thread Safety
This function should be called on the thread that created the renderer.
Since
This function is available since SDL 3.4.0.
See also
SDL_CreateGPURenderState
{
    if (!state) {
        return;
    }
    FlushRenderCommandsIfGPURenderStateNeeded(state);
    if (state->num_uniform_buffers > 0) {
        for (int i = 0; i < state->num_uniform_buffers; i++) {
            SDL_free(state->uniform_buffers[i].data);
        }
        SDL_free(state->uniform_buffers);
    }
    SDL_free(state->sampler_bindings);
    SDL_free(state->storage_textures);
    SDL_free(state->storage_buffers);
    SDL_free(state);
}
References SDL_GPURenderStateUniformBuffer::data, FlushRenderCommandsIfGPURenderStateNeeded(), SDL_GPURenderState::num_uniform_buffers, SDL_GPURenderState::sampler_bindings, SDL_free(), SDL_GPURenderState::storage_buffers, SDL_GPURenderState::storage_textures, and SDL_GPURenderState::uniform_buffers.
Referenced by SDL_CreateGPURenderState().
SDL_DestroyRenderer()
void SDL_DestroyRenderer (SDL_Renderer * renderer)
Destroy the rendering context for a window and free all associated textures.
This should be called before destroying the associated window.
Parameters
renderer the rendering context.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRenderer
{
    CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG(renderer,);
    // if we've already destroyed the renderer through SDL_DestroyWindow, we just need
    // to free the renderer pointer. This lets apps destroy the window and renderer
    // in either order.
    if (!renderer->destroyed) {
        SDL_DestroyRendererWithoutFreeing(renderer);
    }
    SDL_Renderer *curr = SDL_renderers;
    SDL_Renderer *prev = NULL;
    while (curr) {
        if (curr == renderer) {
            if (prev) {
                prev->next = renderer->next;
            } else {
                SDL_renderers = renderer->next;
            }
            break;
        }
        prev = curr;
        curr = curr->next;
    }
    SDL_SetObjectValid(renderer, SDL_OBJECT_TYPE_RENDERER, false);  // It's no longer magical...
    SDL_free(renderer);
}
References CHECK_RENDERER_MAGIC_BUT_NOT_DESTROYED_FLAG, SDL_Renderer::destroyed, SDL_Renderer::next, NULL, SDL_DestroyRendererWithoutFreeing(), SDL_free(), SDL_OBJECT_TYPE_RENDERER, SDL_renderers, and SDL_SetObjectValid().
Referenced by SDL_CleanupWindowTextureData(), SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), and SDL_QuitRender().
SDL_DestroyRendererWithoutFreeing()
void SDL_DestroyRendererWithoutFreeing (SDL_Renderer * renderer)
{
    SDL_assert(renderer != NULL);
    SDL_assert(!renderer->destroyed);
    renderer->destroyed = true;
    SDL_RemoveWindowEventWatch(SDL_WINDOW_EVENT_WATCH_NORMAL, SDL_RendererEventWatch, renderer);
    if (renderer->window) {
        SDL_PropertiesID props = SDL_GetWindowProperties(renderer->window);
        if (SDL_GetPointerProperty(props, SDL_PROP_WINDOW_RENDERER_POINTER, NULL) == renderer) {
            SDL_ClearProperty(props, SDL_PROP_WINDOW_RENDERER_POINTER);
        }
        SDL_RemoveWindowRenderer(renderer->window, renderer);
    }
    if (renderer->software) {
        // Make sure all drawing to a surface is complete
        FlushRenderCommands(renderer);
    }
    SDL_DiscardAllCommands(renderer);
    if (renderer->debug_char_texture_atlas) {
        SDL_DestroyTexture(renderer->debug_char_texture_atlas);
        renderer->debug_char_texture_atlas = NULL;
    }
    // Free existing textures for this renderer
    while (renderer->textures) {
        SDL_Texture *tex = renderer->textures;
        SDL_DestroyTextureInternal(renderer->textures, true /* is_destroying */);
        SDL_assert(tex != renderer->textures); // satisfy static analysis.
    }
    // Clean up renderer-specific resources
    if (renderer->DestroyRenderer) {
        renderer->DestroyRenderer(renderer);
    }
    if (renderer->target_mutex) {
        SDL_DestroyMutex(renderer->target_mutex);
        renderer->target_mutex = NULL;
    }
    if (renderer->vertex_data) {
        SDL_free(renderer->vertex_data);
        renderer->vertex_data = NULL;
    }
    if (renderer->texture_formats) {
        SDL_free(renderer->texture_formats);
        renderer->texture_formats = NULL;
    }
    if (renderer->props) {
        SDL_DestroyProperties(renderer->props);
        renderer->props = 0;
    }
}
References SDL_Renderer::debug_char_texture_atlas, SDL_Renderer::destroyed, SDL_Renderer::DestroyRenderer, FlushRenderCommands(), NULL, SDL_Renderer::props, SDL_assert, SDL_ClearProperty(), SDL_DestroyMutex(), SDL_DestroyProperties(), SDL_DestroyTexture(), SDL_DestroyTextureInternal(), SDL_DiscardAllCommands(), SDL_free(), SDL_GetPointerProperty(), SDL_GetWindowProperties(), SDL_PROP_WINDOW_RENDERER_POINTER, SDL_RemoveWindowEventWatch(), SDL_RemoveWindowRenderer(), SDL_RendererEventWatch(), SDL_WINDOW_EVENT_WATCH_NORMAL, SDL_Renderer::software, SDL_Renderer::target_mutex, SDL_Renderer::texture_formats, SDL_Renderer::textures, SDL_Renderer::vertex_data, and SDL_Renderer::window.
Referenced by SDL_CreateRendererWithProperties(), SDL_DestroyRenderer(), and SDL_DestroyWindow().
SDL_DestroyTexture()
void SDL_DestroyTexture (SDL_Texture * texture)
Destroy the specified texture.
Passing NULL or an otherwise invalid texture will set the SDL error message to "Invalid texture".
Parameters
texture the texture to destroy.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateTexture
SDL_CreateTextureFromSurface
{
    CHECK_TEXTURE_MAGIC(texture, );
    if (--texture->refcount > 0) {
        return;
    }
    SDL_DestroyTextureInternal(texture, false /* is_destroying */);
}
References CHECK_TEXTURE_MAGIC, SDL_Texture::refcount, and SDL_DestroyTextureInternal().
Referenced by SDL_CleanupWindowTextureData(), SDL_CreateTextureFromSurface(), SDL_CreateTextureWithProperties(), SDL_CreateWindowTexture(), SDL_DestroyRendererWithoutFreeing(), and SDL_RenderApplyWindowShape().
SDL_DestroyTextureInternal()
void SDL_DestroyTextureInternal (SDL_Texture * texture, bool is_destroying) static
{
    SDL_Renderer *renderer;
    SDL_DestroyProperties(texture->props);
    renderer = texture->renderer;
    if (is_destroying) {
        // Renderer get destroyed, avoid to queue more commands
    } else {
        if (texture == renderer->target) {
            SDL_SetRenderTarget(renderer, NULL); // implies command queue flush
        } else {
            FlushRenderCommandsIfTextureNeeded(texture);
        }
    }
    SDL_SetObjectValid(texture, SDL_OBJECT_TYPE_TEXTURE, false);
    if (texture->next) {
        texture->next->prev = texture->prev;
    }
    if (texture->prev) {
        texture->prev->next = texture->next;
    } else {
        renderer->textures = texture->next;
    }
    if (texture->native) {
        SDL_DestroyTextureInternal(texture->native, is_destroying);
    }
#ifdef SDL_HAVE_YUV
    if (texture->yuv) {
        SDL_SW_DestroyYUVTexture(texture->yuv);
    }
#endif
    SDL_free(texture->pixels);
    renderer->DestroyTexture(renderer, texture);
    SDL_DestroySurface(texture->locked_surface);
    texture->locked_surface = NULL;
    SDL_free(texture);
}
References SDL_Renderer::DestroyTexture, FlushRenderCommandsIfTextureNeeded(), SDL_Texture::locked_surface, SDL_Texture::native, SDL_Texture::next, NULL, SDL_Texture::pixels, SDL_Texture::prev, SDL_Texture::props, SDL_Texture::renderer, SDL_DestroyProperties(), SDL_DestroySurface(), SDL_DestroyTextureInternal(), SDL_free(), SDL_OBJECT_TYPE_TEXTURE, SDL_SetObjectValid(), SDL_SetRenderTarget(), SDL_SW_DestroyYUVTexture(), SDL_Renderer::target, SDL_Renderer::textures, and SDL_Texture::yuv.
Referenced by SDL_DestroyRendererWithoutFreeing(), SDL_DestroyTexture(), and SDL_DestroyTextureInternal().
SDL_DiscardAllCommands()
void SDL_DiscardAllCommands (SDL_Renderer * renderer) static
{
    SDL_RenderCommand *cmd;
    if (renderer->render_commands_tail) {
        renderer->render_commands_tail->next = renderer->render_commands_pool;
        cmd = renderer->render_commands;
    } else {
        cmd = renderer->render_commands_pool;
    }
    renderer->render_commands_pool = NULL;
    renderer->render_commands_tail = NULL;
    renderer->render_commands = NULL;
    renderer->vertex_data_used = 0;
    while (cmd) {
        SDL_RenderCommand *next = cmd->next;
        SDL_free(cmd);
        cmd = next;
    }
}
References SDL_RenderCommand::next, NULL, SDL_Renderer::render_commands, SDL_Renderer::render_commands_pool, SDL_Renderer::render_commands_tail, SDL_free(), and SDL_Renderer::vertex_data_used.
Referenced by SDL_DestroyRendererWithoutFreeing().
SDL_FlushRenderer()
bool SDL_FlushRenderer (SDL_Renderer * renderer)
Force the rendering context to flush any pending commands and state.
You do not need to (and in fact, shouldn't) call this function unless you are planning to call into OpenGL/Direct3D/Metal/whatever directly, in addition to using an SDL_Renderer.
This is for a very-specific case: if you are using SDL's render API, and you plan to make OpenGL/D3D/whatever calls in addition to SDL render API calls. If this applies, you should call this function between calls to SDL's render API and the low-level API you're using in cooperation.
In all other cases, you can ignore this function.
This call makes SDL flush any pending rendering work it was queueing up to do later in a single batch, and marks any internal cached state as invalid, so it'll prepare all its state again later, from scratch.
This means you do not need to save state in your rendering code to protect the SDL renderer. However, there lots of arbitrary pieces of Direct3D and OpenGL state that can confuse things; you should use your best judgment and be prepared to make changes if specific state needs to be protected.
Parameters
renderer the rendering context.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (!FlushRenderCommands(renderer)) {
        return false;
    }
    renderer->InvalidateCachedState(renderer);
    return true;
}
References FlushRenderCommands(), and SDL_Renderer::InvalidateCachedState.
SDL_GetBlendModeAlphaOperation()
SDL_BlendOperation SDL_GetBlendModeAlphaOperation (SDL_BlendMode blendMode)
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendOperation)(((Uint32)blendMode >> 16) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeColorOperation()
SDL_BlendOperation SDL_GetBlendModeColorOperation (SDL_BlendMode blendMode)
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendOperation)(((Uint32)blendMode >> 0) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeDstAlphaFactor()
SDL_BlendFactor SDL_GetBlendModeDstAlphaFactor (SDL_BlendMode blendMode)
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 24) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeDstColorFactor()
SDL_BlendFactor SDL_GetBlendModeDstColorFactor (SDL_BlendMode blendMode)
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 8) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeSrcAlphaFactor()
SDL_BlendFactor SDL_GetBlendModeSrcAlphaFactor (SDL_BlendMode blendMode)
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 20) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetBlendModeSrcColorFactor()
SDL_BlendFactor SDL_GetBlendModeSrcColorFactor (SDL_BlendMode blendMode)
{
    blendMode = SDL_GetLongBlendMode(blendMode);
    return (SDL_BlendFactor)(((Uint32)blendMode >> 4) & 0xF);
}
References SDL_GetLongBlendMode().
SDL_GetCurrentRenderOutputSize()
bool SDL_GetCurrentRenderOutputSize (SDL_Renderer * renderer, int * w, int * h)
Get the current output size in pixels of a rendering context.
If a rendering target is active, this will return the size of the rendering target in pixels, otherwise return the value of SDL_GetRenderOutputSize().
Rendering target or not, the output will be adjusted by the current logical presentation state, dictated by SDL_SetRenderLogicalPresentation().
Parameters
renderer the rendering context.
w a pointer filled in with the current width.
h a pointer filled in with the current height.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderOutputSize
{
    if (w) {
        *w = 0;
    }
    if (h) {
        *h = 0;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    const SDL_RenderViewState *view = renderer->view;
    if (w) {
        *w = view->pixel_w;
    }
    if (h) {
        *h = view->pixel_h;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, and SDL_Renderer::view.
SDL_GetDefaultTextureScaleMode()
bool SDL_GetDefaultTextureScaleMode (SDL_Renderer * renderer, SDL_ScaleMode * scale_mode)
Get default texture scale mode of the given renderer.
Parameters
renderer the renderer to get data from.
scale_mode a SDL_ScaleMode filled with current default scale mode. See SDL_SetDefaultTextureScaleMode() for the meaning of the value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_SetDefaultTextureScaleMode
{
    if (scale_mode) {
        *scale_mode = SDL_SCALEMODE_LINEAR;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (scale_mode) {
        *scale_mode = renderer->scale_mode;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::scale_mode, and SDL_SCALEMODE_LINEAR.
SDL_GetLongBlendMode()
SDL_BlendMode SDL_GetLongBlendMode (SDL_BlendMode blendMode) static
{
    if (blendMode == SDL_BLENDMODE_NONE) {
        return SDL_BLENDMODE_NONE_FULL;
    }
    if (blendMode == SDL_BLENDMODE_BLEND) {
        return SDL_BLENDMODE_BLEND_FULL;
    }
    if (blendMode == SDL_BLENDMODE_BLEND_PREMULTIPLIED) {
        return SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL;
    }
    if (blendMode == SDL_BLENDMODE_ADD) {
        return SDL_BLENDMODE_ADD_FULL;
    }
    if (blendMode == SDL_BLENDMODE_ADD_PREMULTIPLIED) {
        return SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL;
    }
    if (blendMode == SDL_BLENDMODE_MOD) {
        return SDL_BLENDMODE_MOD_FULL;
    }
    if (blendMode == SDL_BLENDMODE_MUL) {
        return SDL_BLENDMODE_MUL_FULL;
    }
    return blendMode;
}
References SDL_BLENDMODE_ADD, SDL_BLENDMODE_ADD_FULL, SDL_BLENDMODE_ADD_PREMULTIPLIED, SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL, SDL_BLENDMODE_BLEND, SDL_BLENDMODE_BLEND_FULL, SDL_BLENDMODE_BLEND_PREMULTIPLIED, SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL, SDL_BLENDMODE_MOD, SDL_BLENDMODE_MOD_FULL, SDL_BLENDMODE_MUL, SDL_BLENDMODE_MUL_FULL, SDL_BLENDMODE_NONE, and SDL_BLENDMODE_NONE_FULL.
Referenced by SDL_GetBlendModeAlphaOperation(), SDL_GetBlendModeColorOperation(), SDL_GetBlendModeDstAlphaFactor(), SDL_GetBlendModeDstColorFactor(), SDL_GetBlendModeSrcAlphaFactor(), and SDL_GetBlendModeSrcColorFactor().
SDL_GetNumRenderDrivers()
int SDL_GetNumRenderDrivers (void)
Get the number of 2D rendering drivers available for the current display.
A render driver is a set of code that handles rendering and texture management on a particular display. Normally there is only one, but some drivers may have several available with different capabilities.
There may be none if SDL was compiled without render support.
Returns
the number of built in render drivers.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRenderer
SDL_GetRenderDriver
{
#ifndef SDL_RENDER_DISABLED
    return SDL_arraysize(render_drivers) - 1;
#else
    return 0;
#endif
}
References render_drivers, and SDL_arraysize.
Referenced by SDL_CreateWindowTexture(), and SDL_GetRenderDriver().
SDL_GetRenderClipRect()
bool SDL_GetRenderClipRect (SDL_Renderer * renderer, SDL_Rect * rect)
Get the clip rectangle for the current target.
Each render target has its own clip rectangle. This function gets the cliprect for the current render target.
Parameters
renderer the rendering context.
rect an SDL_Rect structure filled in with the current clipping area or an empty rectangle if clipping is disabled.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderClipEnabled
SDL_SetRenderClipRect
{
    if (rect) {
        SDL_zerop(rect);
    }
    CHECK_RENDERER_MAGIC(renderer, false)
    if (rect) {
        SDL_copyp(rect, &renderer->view->clip_rect);
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::clip_rect, SDL_copyp, SDL_zerop, and SDL_Renderer::view.
SDL_GetRenderColorScale()
bool SDL_GetRenderColorScale (SDL_Renderer * renderer, float * scale)
Get the color scale used for render operations.
Parameters
renderer the rendering context.
scale a pointer filled in with the current color scale value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderColorScale
{
    if (scale) {
        *scale = 1.0f;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (scale) {
        *scale = renderer->desired_color_scale;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, and SDL_Renderer::desired_color_scale.
SDL_GetRenderDrawBlendMode()
bool SDL_GetRenderDrawBlendMode (SDL_Renderer * renderer, SDL_BlendMode * blendMode)
Get the blend mode used for drawing operations.
Parameters
renderer the rendering context.
blendMode a pointer filled in with the current SDL_BlendMode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderDrawBlendMode
{
    if (blendMode) {
        *blendMode = SDL_BLENDMODE_INVALID;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (blendMode) {
        *blendMode = renderer->blendMode;
    }
    return true;
}
References SDL_Renderer::blendMode, CHECK_RENDERER_MAGIC, and SDL_BLENDMODE_INVALID.
SDL_GetRenderDrawColor()
bool SDL_GetRenderDrawColor (SDL_Renderer * renderer, Uint8 * r, Uint8 * g, Uint8 * b, Uint8 * a)
Get the color used for drawing operations (Rect, Line and Clear).
Parameters
renderer the rendering context.
r a pointer filled in with the red value used to draw on the rendering target.
g a pointer filled in with the green value used to draw on the rendering target.
b a pointer filled in with the blue value used to draw on the rendering target.
a a pointer filled in with the alpha value used to draw on the rendering target; usually SDL_ALPHA_OPAQUE (255).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderDrawColorFloat
SDL_SetRenderDrawColor
{
    float fR, fG, fB, fA;
    if (!SDL_GetRenderDrawColorFloat(renderer, &fR, &fG, &fB, &fA)) {
        if (r) {
            *r = 0;
        }
        if (g) {
            *g = 0;
        }
        if (b) {
            *b = 0;
        }
        if (a) {
            *a = 0;
        }
        return false;
    }
    if (r) {
        *r = (Uint8)(fR * 255.0f);
    }
    if (g) {
        *g = (Uint8)(fG * 255.0f);
    }
    if (b) {
        *b = (Uint8)(fB * 255.0f);
    }
    if (a) {
        *a = (Uint8)(fA * 255.0f);
    }
    return true;
}
References SDL_GetRenderDrawColorFloat().
Referenced by SDL_RenderDebugText().
SDL_GetRenderDrawColorFloat()
bool SDL_GetRenderDrawColorFloat (SDL_Renderer * renderer, float * r, float * g, float * b, float * a)
Get the color used for drawing operations (Rect, Line and Clear).
Parameters
renderer the rendering context.
r a pointer filled in with the red value used to draw on the rendering target.
g a pointer filled in with the green value used to draw on the rendering target.
b a pointer filled in with the blue value used to draw on the rendering target.
a a pointer filled in with the alpha value used to draw on the rendering target.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderDrawColorFloat
SDL_GetRenderDrawColor
{
    SDL_FColor color;
    if (r) {
        *r = 0.0f;
    }
    if (g) {
        *g = 0.0f;
    }
    if (b) {
        *b = 0.0f;
    }
    if (a) {
        *a = 0.0f;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    color = renderer->color;
    if (r) {
        *r = color.r;
    }
    if (g) {
        *g = color.g;
    }
    if (b) {
        *b = color.b;
    }
    if (a) {
        *a = color.a;
    }
    return true;
}
References SDL_FColor::a, SDL_FColor::b, CHECK_RENDERER_MAGIC, SDL_Renderer::color, SDL_FColor::g, and SDL_FColor::r.
Referenced by SDL_GetRenderDrawColor().
SDL_GetRenderDriver()
const char * SDL_GetRenderDriver (int index)
Use this function to get the name of a built in 2D rendering driver.
The list of rendering drivers is given in the order that they are normally initialized by default; the drivers that seem more reasonable to choose first (as far as the SDL developers believe) are earlier in the list.
The names of drivers are all simple, low-ASCII identifiers, like "opengl", "direct3d12" or "metal". These never have Unicode characters, and are not meant to be proper names.
Parameters
index the index of the rendering driver; the value ranges from 0 to SDL_GetNumRenderDrivers() - 1.
Returns
the name of the rendering driver at the requested index, or NULL if an invalid index was specified.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetNumRenderDrivers
{
#ifndef SDL_RENDER_DISABLED
    if (index < 0 || index >= SDL_GetNumRenderDrivers()) {
        SDL_InvalidParamError("index");
        return NULL;
    }
    return render_drivers[index]->name;
#else
    SDL_SetError("SDL not built with rendering support");
    return NULL;
#endif
}
References NULL, render_drivers, SDL_GetNumRenderDrivers(), SDL_InvalidParamError, and SDL_SetError().
Referenced by SDL_CreateWindowTexture().
SDL_GetRenderer()
SDL_Renderer * SDL_GetRenderer (SDL_Window * window)
Get the renderer associated with a window.
Parameters
window the window to query.
Returns
the rendering context on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    return (SDL_Renderer *)SDL_GetPointerProperty(SDL_GetWindowProperties(window), SDL_PROP_WINDOW_RENDERER_POINTER, NULL);
}
References NULL, SDL_GetPointerProperty(), SDL_GetWindowProperties(), and SDL_PROP_WINDOW_RENDERER_POINTER.
Referenced by SDL_CreateRendererWithProperties(), and SDL_DestroyWindow().
SDL_GetRendererFromTexture()
SDL_Renderer * SDL_GetRendererFromTexture (SDL_Texture * texture)
Get the renderer that created an SDL_Texture.
Parameters
texture the texture to query.
Returns
a pointer to the SDL_Renderer that created the texture, or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_TEXTURE_MAGIC(texture, NULL);
    return texture->renderer;
}
References CHECK_TEXTURE_MAGIC, NULL, and SDL_Texture::renderer.
SDL_GetRendererName()
const char * SDL_GetRendererName (SDL_Renderer * renderer)
Get the name of a renderer.
Parameters
renderer the rendering context.
Returns
the name of the selected renderer, or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRenderer
SDL_CreateRendererWithProperties
{
    CHECK_RENDERER_MAGIC(renderer, NULL);
    return SDL_GetPersistentString(renderer->name);
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::name, NULL, and SDL_GetPersistentString().
SDL_GetRendererProperties()
SDL_PropertiesID SDL_GetRendererProperties (SDL_Renderer * renderer)
Get the properties associated with a renderer.
The following read-only properties are provided by SDL:
SDL_PROP_RENDERER_NAME_STRING: the name of the rendering driver
SDL_PROP_RENDERER_WINDOW_POINTER: the window where rendering is displayed, if any
SDL_PROP_RENDERER_SURFACE_POINTER: the surface where rendering is displayed, if this is a software renderer without a window
SDL_PROP_RENDERER_VSYNC_NUMBER: the current vsync setting
SDL_PROP_RENDERER_MAX_TEXTURE_SIZE_NUMBER: the maximum texture width and height
SDL_PROP_RENDERER_TEXTURE_FORMATS_POINTER: a (const SDL_PixelFormat *) array of pixel formats, terminated with SDL_PIXELFORMAT_UNKNOWN, representing the available texture formats for this renderer.
SDL_PROP_RENDERER_OUTPUT_COLORSPACE_NUMBER: an SDL_Colorspace value describing the colorspace for output to the display, defaults to SDL_COLORSPACE_SRGB.
SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN: true if the output colorspace is SDL_COLORSPACE_SRGB_LINEAR and the renderer is showing on a display with HDR enabled. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
SDL_PROP_RENDERER_SDR_WHITE_POINT_FLOAT: the value of SDR white in the SDL_COLORSPACE_SRGB_LINEAR colorspace. When HDR is enabled, this value is automatically multiplied into the color scale. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
SDL_PROP_RENDERER_HDR_HEADROOM_FLOAT: the additional high dynamic range that can be displayed, in terms of the SDR white point. When HDR is not enabled, this will be 1.0. This property can change dynamically when SDL_EVENT_WINDOW_HDR_STATE_CHANGED is sent.
With the direct3d renderer:
SDL_PROP_RENDERER_D3D9_DEVICE_POINTER: the IDirect3DDevice9 associated with the renderer
With the direct3d11 renderer:
SDL_PROP_RENDERER_D3D11_DEVICE_POINTER: the ID3D11Device associated with the renderer
SDL_PROP_RENDERER_D3D11_SWAPCHAIN_POINTER: the IDXGISwapChain1 associated with the renderer. This may change when the window is resized.
With the direct3d12 renderer:
SDL_PROP_RENDERER_D3D12_DEVICE_POINTER: the ID3D12Device associated with the renderer
SDL_PROP_RENDERER_D3D12_SWAPCHAIN_POINTER: the IDXGISwapChain4 associated with the renderer.
SDL_PROP_RENDERER_D3D12_COMMAND_QUEUE_POINTER: the ID3D12CommandQueue associated with the renderer
With the vulkan renderer:
SDL_PROP_RENDERER_VULKAN_INSTANCE_POINTER: the VkInstance associated with the renderer
SDL_PROP_RENDERER_VULKAN_SURFACE_NUMBER: the VkSurfaceKHR associated with the renderer
SDL_PROP_RENDERER_VULKAN_PHYSICAL_DEVICE_POINTER: the VkPhysicalDevice associated with the renderer
SDL_PROP_RENDERER_VULKAN_DEVICE_POINTER: the VkDevice associated with the renderer
SDL_PROP_RENDERER_VULKAN_GRAPHICS_QUEUE_FAMILY_INDEX_NUMBER: the queue family index used for rendering
SDL_PROP_RENDERER_VULKAN_PRESENT_QUEUE_FAMILY_INDEX_NUMBER: the queue family index used for presentation
SDL_PROP_RENDERER_VULKAN_SWAPCHAIN_IMAGE_COUNT_NUMBER: the number of swapchain images, or potential frames in flight, used by the Vulkan renderer
With the gpu renderer:
SDL_PROP_RENDERER_GPU_DEVICE_POINTER: the SDL_GPUDevice associated with the renderer
Parameters
renderer the rendering context.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_RENDERER_MAGIC(renderer, 0);
    if (renderer->props == 0) {
        renderer->props = SDL_CreateProperties();
    }
    return renderer->props;
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::props, and SDL_CreateProperties().
Referenced by SDL_AddSupportedTextureFormat(), SDL_CreateGPURenderer(), SDL_CreateRendererWithProperties(), SDL_CreateTextureWithProperties(), SDL_CreateWindowTexture(), SDL_GetRenderVSync(), SDL_SetRenderVSync(), and UpdateHDRProperties().
SDL_GetRenderLineMethod()
SDL_RenderLineMethod SDL_GetRenderLineMethod (void) static
{
    const char *hint = SDL_GetHint(SDL_HINT_RENDER_LINE_METHOD);
    int method = 0;
    if (hint) {
        method = SDL_atoi(hint);
    }
    switch (method) {
    case 1:
        return SDL_RENDERLINEMETHOD_POINTS;
    case 2:
        return SDL_RENDERLINEMETHOD_LINES;
    case 3:
        return SDL_RENDERLINEMETHOD_GEOMETRY;
    default:
        return SDL_RENDERLINEMETHOD_POINTS;
    }
}
References SDL_atoi(), SDL_GetHint(), SDL_HINT_RENDER_LINE_METHOD, SDL_RENDERLINEMETHOD_GEOMETRY, SDL_RENDERLINEMETHOD_LINES, and SDL_RENDERLINEMETHOD_POINTS.
Referenced by SDL_CreateRendererWithProperties().
SDL_GetRenderLogicalPresentation()
bool SDL_GetRenderLogicalPresentation (SDL_Renderer * renderer, int * w, int * h, SDL_RendererLogicalPresentation * mode)
Get device independent resolution and presentation mode for rendering.
This function gets the width and height of the logical rendering output, or the output size in pixels if a logical resolution is not enabled.
Each render target has its own logical presentation state. This function gets the state for the current render target.
Parameters
renderer the rendering context.
w an int to be filled with the width.
h an int to be filled with the height.
mode the presentation mode used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderLogicalPresentation
{
    #define SETVAL(ptr, val) if (ptr) { *ptr = val; }
    SETVAL(w, 0);
    SETVAL(h, 0);
    SETVAL(mode, SDL_LOGICAL_PRESENTATION_DISABLED);
    CHECK_RENDERER_MAGIC(renderer, false);
    const SDL_RenderViewState *view = renderer->view;
    SETVAL(w, view->logical_w);
    SETVAL(h, view->logical_h);
    SETVAL(mode, view->logical_presentation_mode);
    #undef SETVAL
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::logical_h, SDL_RenderViewState::logical_presentation_mode, SDL_RenderViewState::logical_w, SDL_LOGICAL_PRESENTATION_DISABLED, SETVAL, and SDL_Renderer::view.
SDL_GetRenderLogicalPresentationRect()
bool SDL_GetRenderLogicalPresentationRect (SDL_Renderer * renderer, SDL_FRect * rect)
Get the final presentation rectangle for rendering.
This function returns the calculated rectangle used for logical presentation, based on the presentation mode and output size. If logical presentation is disabled, it will fill the rectangle with the output size, in pixels.
Each render target has its own logical presentation state. This function gets the rectangle for the current render target.
Parameters
renderer the rendering context.
rect a pointer filled in with the final presentation rectangle, may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderLogicalPresentation
{
    if (rect) {
        SDL_zerop(rect);
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (rect) {
        SDL_copyp(rect, &renderer->view->logical_dst_rect);
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::logical_dst_rect, SDL_copyp, SDL_zerop, and SDL_Renderer::view.
SDL_GetRenderMetalCommandEncoder()
void * SDL_GetRenderMetalCommandEncoder (SDL_Renderer * renderer)
Get the Metal command encoder for the current frame.
This function returns void *, so SDL doesn't have to include Metal's headers, but it can be safely cast to an id<MTLRenderCommandEncoder>.
This will return NULL if Metal refuses to give SDL a drawable to render to, which might happen if the window is hidden/minimized/offscreen. This doesn't apply to command encoders for render targets, just the window's backbuffer. Check your return values!
Parameters
renderer the renderer to query.
Returns
an id<MTLRenderCommandEncoder> on success, or NULL if the renderer isn't a Metal renderer or there was an error.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderMetalLayer
{
    CHECK_RENDERER_MAGIC(renderer, NULL);
    if (renderer->GetMetalCommandEncoder) {
        FlushRenderCommands(renderer); // in case the app is going to mess with it.
        return renderer->GetMetalCommandEncoder(renderer);
    }
    return NULL;
}
References CHECK_RENDERER_MAGIC, FlushRenderCommands(), SDL_Renderer::GetMetalCommandEncoder, and NULL.
SDL_GetRenderMetalLayer()
void * SDL_GetRenderMetalLayer (SDL_Renderer * renderer)
Get the CAMetalLayer associated with the given Metal renderer.
This function returns void *, so SDL doesn't have to include Metal's headers, but it can be safely cast to a CAMetalLayer *.
Parameters
renderer the renderer to query.
Returns
a CAMetalLayer * on success, or NULL if the renderer isn't a Metal renderer.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderMetalCommandEncoder
{
    CHECK_RENDERER_MAGIC(renderer, NULL);
    if (renderer->GetMetalLayer) {
        FlushRenderCommands(renderer); // in case the app is going to mess with it.
        return renderer->GetMetalLayer(renderer);
    }
    return NULL;
}
References CHECK_RENDERER_MAGIC, FlushRenderCommands(), SDL_Renderer::GetMetalLayer, and NULL.
SDL_GetRenderOutputSize()
bool SDL_GetRenderOutputSize (SDL_Renderer * renderer, int * w, int * h)
Get the output size in pixels of a rendering context.
This returns the true output size in pixels, ignoring any render targets or logical size and presentation.
For the output size of the current rendering target, with logical size adjustments, use SDL_GetCurrentRenderOutputSize() instead.
Parameters
renderer the rendering context.
w a pointer filled in with the width in pixels.
h a pointer filled in with the height in pixels.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetCurrentRenderOutputSize
{
    if (w) {
        *w = 0;
    }
    if (h) {
        *h = 0;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (renderer->GetOutputSize) {
        return renderer->GetOutputSize(renderer, w, h);
    } else if (renderer->window) {
        return SDL_GetWindowSizeInPixels(renderer->window, w, h);
    } else {
        SDL_assert(!"This should never happen");
        return SDL_SetError("Renderer doesn't support querying output size");
    }
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::GetOutputSize, SDL_assert, SDL_GetWindowSizeInPixels(), SDL_SetError(), and SDL_Renderer::window.
Referenced by UpdateLogicalPresentation(), and UpdateMainViewDimensions().
SDL_GetRenderSafeArea()
bool SDL_GetRenderSafeArea (SDL_Renderer * renderer, SDL_Rect * rect)
Get the safe area for rendering within the current viewport.
Some devices have portions of the screen which are partially obscured or not interactive, possibly due to on-screen controls, curved edges, camera notches, TV overscan, etc. This function provides the area of the current viewport which is safe to have interactible content. You should continue rendering into the rest of the render target, but it should not contain visually important or interactible content.
Parameters
renderer the rendering context.
rect a pointer filled in with the area that is safe for interactive content.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (rect) {
        SDL_zerop(rect);
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (renderer->target || !renderer->window) {
        // The entire viewport is safe for rendering
        return SDL_GetRenderViewport(renderer, rect);
    }
    if (rect) {
        // Get the window safe rect
        SDL_Rect safe;
        if (!SDL_GetWindowSafeArea(renderer->window, &safe)) {
            return false;
        }
        // Convert the coordinates into the render space
        float minx = (float)safe.x;
        float miny = (float)safe.y;
        float maxx = (float)safe.x + safe.w;
        float maxy = (float)safe.y + safe.h;
        if (!SDL_RenderCoordinatesFromWindow(renderer, minx, miny, &minx, &miny) ||
            !SDL_RenderCoordinatesFromWindow(renderer, maxx, maxy, &maxx, &maxy)) {
            return false;
        }
        rect->x = (int)SDL_ceilf(minx);
        rect->y = (int)SDL_ceilf(miny);
        rect->w = (int)SDL_ceilf(maxx - minx);
        rect->h = (int)SDL_ceilf(maxy - miny);
        // Clip with the viewport
        SDL_Rect viewport;
        if (!SDL_GetRenderViewport(renderer, &viewport)) {
            return false;
        }
        if (!SDL_GetRectIntersection(rect, &viewport, rect)) {
            return SDL_SetError("No safe area within viewport");
        }
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_Rect::h, SDL_ceilf(), SDL_GetRectIntersection(), SDL_GetRenderViewport(), SDL_GetWindowSafeArea(), SDL_RenderCoordinatesFromWindow(), SDL_SetError(), SDL_zerop, SDL_Renderer::target, SDL_Rect::w, SDL_Renderer::window, SDL_Rect::x, and SDL_Rect::y.
SDL_GetRenderScale()
bool SDL_GetRenderScale (SDL_Renderer * renderer, float * scaleX, float * scaleY)
Get the drawing scale for the current target.
Each render target has its own scale. This function gets the scale for the current render target.
Parameters
renderer the rendering context.
scaleX a pointer filled in with the horizontal scaling factor.
scaleY a pointer filled in with the vertical scaling factor.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderScale
{
    if (scaleX) {
        *scaleX = 1.0f;
    }
    if (scaleY) {
        *scaleY = 1.0f;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    const SDL_RenderViewState *view = renderer->view;
    if (scaleX) {
        *scaleX = view->scale.x;
    }
    if (scaleY) {
        *scaleY = view->scale.y;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::scale, SDL_Renderer::view, SDL_FPoint::x, and SDL_FPoint::y.
SDL_GetRenderTarget()
SDL_Texture * SDL_GetRenderTarget (SDL_Renderer * renderer)
Get the current render target.
The default render target is the window for which the renderer was created, and is reported a NULL here.
Parameters
renderer the rendering context.
Returns
the current render target or NULL for the default render target.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderTarget
{
    CHECK_RENDERER_MAGIC(renderer, NULL);
    if (!renderer->target) {
        return NULL;
    }
    return (SDL_Texture *) SDL_GetPointerProperty(SDL_GetTextureProperties(renderer->target), SDL_PROP_TEXTURE_PARENT_POINTER, renderer->target);
}
References CHECK_RENDERER_MAGIC, NULL, SDL_GetPointerProperty(), SDL_GetTextureProperties(), SDL_PROP_TEXTURE_PARENT_POINTER, and SDL_Renderer::target.
SDL_GetRenderTextureAddressMode()
bool SDL_GetRenderTextureAddressMode (SDL_Renderer * renderer, SDL_TextureAddressMode * u_mode, SDL_TextureAddressMode * v_mode)
Get the texture addressing mode used in SDL_RenderGeometry().
Parameters
renderer the rendering context.
u_mode a pointer filled in with the SDL_TextureAddressMode to use for horizontal texture coordinates in SDL_RenderGeometry(), may be NULL.
v_mode a pointer filled in with the SDL_TextureAddressMode to use for vertical texture coordinates in SDL_RenderGeometry(), may be NULL.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.4.0.
See also
SDL_SetRenderTextureAddressMode
{
    if (u_mode) {
        *u_mode = SDL_TEXTURE_ADDRESS_INVALID;
    }
    if (v_mode) {
        *v_mode = SDL_TEXTURE_ADDRESS_INVALID;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (u_mode) {
        *u_mode = renderer->texture_address_mode_u;
    }
    if (v_mode) {
        *v_mode = renderer->texture_address_mode_v;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_TEXTURE_ADDRESS_INVALID, SDL_Renderer::texture_address_mode_u, and SDL_Renderer::texture_address_mode_v.
SDL_GetRenderViewport()
bool SDL_GetRenderViewport (SDL_Renderer * renderer, SDL_Rect * rect)
Get the drawing area for the current target.
Each render target has its own viewport. This function gets the viewport for the current render target.
Parameters
renderer the rendering context.
rect an SDL_Rect structure filled in with the current drawing area.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderViewportSet
SDL_SetRenderViewport
{
    if (rect) {
        SDL_zerop(rect);
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (rect) {
        const SDL_RenderViewState *view = renderer->view;
        rect->x = view->viewport.x;
        rect->y = view->viewport.y;
        if (view->viewport.w >= 0) {
            rect->w = view->viewport.w;
        } else {
            rect->w = (int)SDL_ceilf(view->pixel_w / view->current_scale.x);
        }
        if (view->viewport.h >= 0) {
            rect->h = view->viewport.h;
        } else {
            rect->h = (int)SDL_ceilf(view->pixel_h / view->current_scale.y);
        }
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::current_scale, SDL_Rect::h, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, SDL_ceilf(), SDL_zerop, SDL_Renderer::view, SDL_RenderViewState::viewport, SDL_Rect::w, SDL_FPoint::x, SDL_Rect::x, SDL_FPoint::y, and SDL_Rect::y.
Referenced by SDL_GetRenderSafeArea().
SDL_GetRenderVSync()
bool SDL_GetRenderVSync (SDL_Renderer * renderer, int * vsync)
Get VSync of the given renderer.
Parameters
renderer the renderer to toggle.
vsync an int filled with the current vertical refresh sync interval. See SDL_SetRenderVSync() for the meaning of the value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderVSync
{
    if (vsync) {
        *vsync = 0;
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    if (vsync) {
        *vsync = (int)SDL_GetNumberProperty(SDL_GetRendererProperties(renderer), SDL_PROP_RENDERER_VSYNC_NUMBER, 0);
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_GetNumberProperty(), SDL_GetRendererProperties(), and SDL_PROP_RENDERER_VSYNC_NUMBER.
Referenced by SDL_GetWindowTextureVSync().
SDL_GetRenderWindow()
SDL_Window * SDL_GetRenderWindow (SDL_Renderer * renderer)
Get the window associated with a renderer.
Parameters
renderer the renderer to query.
Returns
the window on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_RENDERER_MAGIC(renderer, NULL);
    return renderer->window;
}
References CHECK_RENDERER_MAGIC, NULL, and SDL_Renderer::window.
SDL_GetShortBlendMode()
SDL_BlendMode SDL_GetShortBlendMode (SDL_BlendMode blendMode) static
{
    if (blendMode == SDL_BLENDMODE_NONE_FULL) {
        return SDL_BLENDMODE_NONE;
    }
    if (blendMode == SDL_BLENDMODE_BLEND_FULL) {
        return SDL_BLENDMODE_BLEND;
    }
    if (blendMode == SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL) {
        return SDL_BLENDMODE_BLEND_PREMULTIPLIED;
    }
    if (blendMode == SDL_BLENDMODE_ADD_FULL) {
        return SDL_BLENDMODE_ADD;
    }
    if (blendMode == SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL) {
        return SDL_BLENDMODE_ADD_PREMULTIPLIED;
    }
    if (blendMode == SDL_BLENDMODE_MOD_FULL) {
        return SDL_BLENDMODE_MOD;
    }
    if (blendMode == SDL_BLENDMODE_MUL_FULL) {
        return SDL_BLENDMODE_MUL;
    }
    return blendMode;
}
References SDL_BLENDMODE_ADD, SDL_BLENDMODE_ADD_FULL, SDL_BLENDMODE_ADD_PREMULTIPLIED, SDL_BLENDMODE_ADD_PREMULTIPLIED_FULL, SDL_BLENDMODE_BLEND, SDL_BLENDMODE_BLEND_FULL, SDL_BLENDMODE_BLEND_PREMULTIPLIED, SDL_BLENDMODE_BLEND_PREMULTIPLIED_FULL, SDL_BLENDMODE_MOD, SDL_BLENDMODE_MOD_FULL, SDL_BLENDMODE_MUL, SDL_BLENDMODE_MUL_FULL, SDL_BLENDMODE_NONE, and SDL_BLENDMODE_NONE_FULL.
Referenced by SDL_ComposeCustomBlendMode().
SDL_GetTextureAlphaMod()
bool SDL_GetTextureAlphaMod (SDL_Texture * texture, Uint8 * alpha)
Get the additional alpha value multiplied into render copy operations.
Parameters
texture the texture to query.
alpha a pointer filled in with the current alpha value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureAlphaModFloat
SDL_GetTextureColorMod
SDL_SetTextureAlphaMod
{
    float fA = 1.0f;
    if (!SDL_GetTextureAlphaModFloat(texture, &fA)) {
        if (alpha) {
            *alpha = 255;
        }
        return false;
    }
    if (alpha) {
        *alpha = (Uint8)SDL_roundf(SDL_clamp(fA, 0.0f, 1.0f) * 255.0f);
    }
    return true;
}
References SDL_clamp, SDL_GetTextureAlphaModFloat(), and SDL_roundf().
SDL_GetTextureAlphaModFloat()
bool SDL_GetTextureAlphaModFloat (SDL_Texture * texture, float * alpha)
Get the additional alpha value multiplied into render copy operations.
Parameters
texture the texture to query.
alpha a pointer filled in with the current alpha value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureAlphaMod
SDL_GetTextureColorModFloat
SDL_SetTextureAlphaModFloat
{
    if (alpha) {
        *alpha = 1.0f;
    }
    CHECK_TEXTURE_MAGIC(texture, false);
    if (alpha) {
        *alpha = texture->color.a;
    }
    return true;
}
References SDL_FColor::a, CHECK_TEXTURE_MAGIC, and SDL_Texture::color.
Referenced by SDL_GetTextureAlphaMod().
SDL_GetTextureBlendMode()
bool SDL_GetTextureBlendMode (SDL_Texture * texture, SDL_BlendMode * blendMode)
Get the blend mode used for texture copy operations.
Parameters
texture the texture to query.
blendMode a pointer filled in with the current SDL_BlendMode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextureBlendMode
{
    if (blendMode) {
        *blendMode = SDL_BLENDMODE_INVALID;
    }
    CHECK_TEXTURE_MAGIC(texture, false);
    if (blendMode) {
        *blendMode = texture->blendMode;
    }
    return true;
}
References SDL_Texture::blendMode, CHECK_TEXTURE_MAGIC, and SDL_BLENDMODE_INVALID.
SDL_GetTextureColorMod()
bool SDL_GetTextureColorMod (SDL_Texture * texture, Uint8 * r, Uint8 * g, Uint8 * b)
Get the additional color value multiplied into render copy operations.
Parameters
texture the texture to query.
r a pointer filled in with the current red color value.
g a pointer filled in with the current green color value.
b a pointer filled in with the current blue color value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureAlphaMod
SDL_GetTextureColorModFloat
SDL_SetTextureColorMod
{
    float fR = 1.0f, fG = 1.0f, fB = 1.0f;
    if (!SDL_GetTextureColorModFloat(texture, &fR, &fG, &fB)) {
        if (r) {
            *r = 255;
        }
        if (g) {
            *g = 255;
        }
        if (b) {
            *b = 255;
        }
        return false;
    }
    if (r) {
        *r = (Uint8)SDL_roundf(SDL_clamp(fR, 0.0f, 1.0f) * 255.0f);
    }
    if (g) {
        *g = (Uint8)SDL_roundf(SDL_clamp(fG, 0.0f, 1.0f) * 255.0f);
    }
    if (b) {
        *b = (Uint8)SDL_roundf(SDL_clamp(fB, 0.0f, 1.0f) * 255.0f);
    }
    return true;
}
References SDL_clamp, SDL_GetTextureColorModFloat(), and SDL_roundf().
SDL_GetTextureColorModFloat()
bool SDL_GetTextureColorModFloat (SDL_Texture * texture, float * r, float * g, float * b)
Get the additional color value multiplied into render copy operations.
Parameters
texture the texture to query.
r a pointer filled in with the current red color value.
g a pointer filled in with the current green color value.
b a pointer filled in with the current blue color value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureAlphaModFloat
SDL_GetTextureColorMod
SDL_SetTextureColorModFloat
{
    SDL_FColor color;
    if (r) {
        *r = 1.0f;
    }
    if (g) {
        *g = 1.0f;
    }
    if (b) {
        *b = 1.0f;
    }
    CHECK_TEXTURE_MAGIC(texture, false);
    color = texture->color;
    if (r) {
        *r = color.r;
    }
    if (g) {
        *g = color.g;
    }
    if (b) {
        *b = color.b;
    }
    return true;
}
References SDL_FColor::b, CHECK_TEXTURE_MAGIC, SDL_Texture::color, SDL_FColor::g, and SDL_FColor::r.
Referenced by SDL_GetTextureColorMod().
SDL_GetTextureProperties()
SDL_PropertiesID SDL_GetTextureProperties (SDL_Texture * texture)
Get the properties associated with a texture.
The following read-only properties are provided by SDL:
SDL_PROP_TEXTURE_COLORSPACE_NUMBER: an SDL_Colorspace value describing the texture colorspace.
SDL_PROP_TEXTURE_FORMAT_NUMBER: one of the enumerated values in SDL_PixelFormat.
SDL_PROP_TEXTURE_ACCESS_NUMBER: one of the enumerated values in SDL_TextureAccess.
SDL_PROP_TEXTURE_WIDTH_NUMBER: the width of the texture in pixels.
SDL_PROP_TEXTURE_HEIGHT_NUMBER: the height of the texture in pixels.
SDL_PROP_TEXTURE_SDR_WHITE_POINT_FLOAT: for HDR10 and floating point textures, this defines the value of 100% diffuse white, with higher values being displayed in the High Dynamic Range headroom. This defaults to 100 for HDR10 textures and 1.0 for other textures.
SDL_PROP_TEXTURE_HDR_HEADROOM_FLOAT: for HDR10 and floating point textures, this defines the maximum dynamic range used by the content, in terms of the SDR white point. If this is defined, any values outside the range supported by the display will be scaled into the available HDR headroom, otherwise they are clipped. This defaults to 1.0 for SDR textures, 4.0 for HDR10 textures, and no default for floating point textures.
With the direct3d11 renderer:
SDL_PROP_TEXTURE_D3D11_TEXTURE_POINTER: the ID3D11Texture2D associated with the texture
SDL_PROP_TEXTURE_D3D11_TEXTURE_U_POINTER: the ID3D11Texture2D associated with the U plane of a YUV texture
SDL_PROP_TEXTURE_D3D11_TEXTURE_V_POINTER: the ID3D11Texture2D associated with the V plane of a YUV texture
With the direct3d12 renderer:
SDL_PROP_TEXTURE_D3D12_TEXTURE_POINTER: the ID3D12Resource associated with the texture
SDL_PROP_TEXTURE_D3D12_TEXTURE_U_POINTER: the ID3D12Resource associated with the U plane of a YUV texture
SDL_PROP_TEXTURE_D3D12_TEXTURE_V_POINTER: the ID3D12Resource associated with the V plane of a YUV texture
With the vulkan renderer:
SDL_PROP_TEXTURE_VULKAN_TEXTURE_NUMBER: the VkImage associated with the texture
With the opengl renderer:
SDL_PROP_TEXTURE_OPENGL_TEXTURE_NUMBER: the GLuint texture associated with the texture
SDL_PROP_TEXTURE_OPENGL_TEXTURE_UV_NUMBER: the GLuint texture associated with the UV plane of an NV12 texture
SDL_PROP_TEXTURE_OPENGL_TEXTURE_U_NUMBER: the GLuint texture associated with the U plane of a YUV texture
SDL_PROP_TEXTURE_OPENGL_TEXTURE_V_NUMBER: the GLuint texture associated with the V plane of a YUV texture
SDL_PROP_TEXTURE_OPENGL_TEXTURE_TARGET_NUMBER: the GLenum for the texture target (GL_TEXTURE_2D, GL_TEXTURE_RECTANGLE_ARB, etc)
SDL_PROP_TEXTURE_OPENGL_TEX_W_FLOAT: the texture coordinate width of the texture (0.0 - 1.0)
SDL_PROP_TEXTURE_OPENGL_TEX_H_FLOAT: the texture coordinate height of the texture (0.0 - 1.0)
With the opengles2 renderer:
SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_NUMBER: the GLuint texture associated with the texture
SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_UV_NUMBER: the GLuint texture associated with the UV plane of an NV12 texture
SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_U_NUMBER: the GLuint texture associated with the U plane of a YUV texture
SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_V_NUMBER: the GLuint texture associated with the V plane of a YUV texture
SDL_PROP_TEXTURE_OPENGLES2_TEXTURE_TARGET_NUMBER: the GLenum for the texture target (GL_TEXTURE_2D, GL_TEXTURE_EXTERNAL_OES, etc)
Parameters
texture the texture to query.
Returns
a valid property ID on success or 0 on failure; call SDL_GetError() for more information.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_TEXTURE_MAGIC(texture, 0);
    if (texture->props == 0) {
        texture->props = SDL_CreateProperties();
    }
    return texture->props;
}
References CHECK_TEXTURE_MAGIC, SDL_Texture::props, and SDL_CreateProperties().
Referenced by SDL_CreateTextureWithProperties(), SDL_GetRenderTarget(), SDL_RenderReadPixels(), and SDL_UpdateTextureFromSurface().
SDL_GetTextureScaleMode()
bool SDL_GetTextureScaleMode (SDL_Texture * texture, SDL_ScaleMode * scaleMode)
Get the scale mode used for texture scale operations.
Parameters
texture the texture to query.
scaleMode a pointer filled in with the current scale mode.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetTextureScaleMode
{
    if (scaleMode) {
        *scaleMode = SDL_SCALEMODE_LINEAR;
    }
    CHECK_TEXTURE_MAGIC(texture, false);
    if (scaleMode) {
        *scaleMode = texture->scaleMode;
    }
    return true;
}
References CHECK_TEXTURE_MAGIC, SDL_Texture::scaleMode, and SDL_SCALEMODE_LINEAR.
SDL_GetTextureSize()
bool SDL_GetTextureSize (SDL_Texture * texture, float * w, float * h)
Get the size of a texture, as floating point values.
Parameters
texture the texture to query.
w a pointer filled in with the width of the texture in pixels. This argument can be NULL if you don't need this information.
h a pointer filled in with the height of the texture in pixels. This argument can be NULL if you don't need this information.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    if (w) {
        *w = 0;
    }
    if (h) {
        *h = 0;
    }
    CHECK_TEXTURE_MAGIC(texture, false);
    if (w) {
        *w = (float)texture->w;
    }
    if (h) {
        *h = (float)texture->h;
    }
    return true;
}
References CHECK_TEXTURE_MAGIC, SDL_Texture::h, and SDL_Texture::w.
SDL_LockTexture()
bool SDL_LockTexture (SDL_Texture * texture, const SDL_Rect * rect, void ** pixels, int * pitch)
Lock a portion of the texture for write-only pixel access.
As an optimization, the pixels made available for editing don't necessarily contain the old texture data. This is a write-only operation, and if you need to keep a copy of the texture data you should do that at the application level.
You must use SDL_UnlockTexture() to unlock the pixels and apply any changes.
Parameters
texture the texture to lock for access, which was created with SDL_TEXTUREACCESS_STREAMING.
rect an SDL_Rect structure representing the area to lock for access; NULL to lock the entire texture.
pixels this is filled in with a pointer to the locked pixels, appropriately offset by the locked area.
pitch this is filled in with the pitch of the locked pixels; the pitch is the length of one row in bytes.
Returns
true on success or false if the texture is not valid or was not created with SDL_TEXTUREACCESS_STREAMING; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockTextureToSurface
SDL_UnlockTexture
{
    SDL_Rect full_rect;
    CHECK_TEXTURE_MAGIC(texture, false);
    if (texture->access != SDL_TEXTUREACCESS_STREAMING) {
        return SDL_SetError("SDL_LockTexture(): texture must be streaming");
    }
    if (!rect) {
        full_rect.x = 0;
        full_rect.y = 0;
        full_rect.w = texture->w;
        full_rect.h = texture->h;
        rect = &full_rect;
    }
#ifdef SDL_HAVE_YUV
    if (texture->yuv) {
        if (!FlushRenderCommandsIfTextureNeeded(texture)) {
            return false;
        }
        return SDL_LockTextureYUV(texture, rect, pixels, pitch);
    } else
#endif
        if (texture->native) {
        // Calls a real SDL_LockTexture/SDL_UnlockTexture on unlock, flushing then.
        return SDL_LockTextureNative(texture, rect, pixels, pitch);
    } else {
        SDL_Renderer *renderer = texture->renderer;
        if (!FlushRenderCommandsIfTextureNeeded(texture)) {
            return false;
        }
        return renderer->LockTexture(renderer, texture, rect, pixels, pitch);
    }
}
References SDL_Texture::access, CHECK_TEXTURE_MAGIC, FlushRenderCommandsIfTextureNeeded(), SDL_Rect::h, SDL_Texture::h, SDL_Renderer::LockTexture, SDL_Texture::native, SDL_Texture::renderer, SDL_LockTextureNative(), SDL_SetError(), SDL_TEXTUREACCESS_STREAMING, SDL_Rect::w, SDL_Texture::w, SDL_Rect::x, SDL_Rect::y, and SDL_Texture::yuv.
Referenced by SDL_LockTextureToSurface(), SDL_UnlockTextureNative(), and SDL_UpdateTextureNative().
SDL_LockTextureNative()
bool SDL_LockTextureNative (SDL_Texture * texture, const SDL_Rect * rect, void ** pixels, int * pitch) static
{
    texture->locked_rect = *rect;
    *pixels = (void *)((Uint8 *)texture->pixels +
                       rect->y * texture->pitch +
                       rect->x * SDL_BYTESPERPIXEL(texture->format));
    *pitch = texture->pitch;
    return true;
}
References SDL_Texture::format, SDL_Texture::locked_rect, SDL_Texture::pitch, SDL_Texture::pixels, SDL_BYTESPERPIXEL, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_LockTexture().
SDL_LockTextureToSurface()
bool SDL_LockTextureToSurface (SDL_Texture * texture, const SDL_Rect * rect, SDL_Surface ** surface)
Lock a portion of the texture for write-only pixel access, and expose it as a SDL surface.
Besides providing an SDL_Surface instead of raw pixel data, this function operates like SDL_LockTexture.
As an optimization, the pixels made available for editing don't necessarily contain the old texture data. This is a write-only operation, and if you need to keep a copy of the texture data you should do that at the application level.
You must use SDL_UnlockTexture() to unlock the pixels and apply any changes.
The returned surface is freed internally after calling SDL_UnlockTexture() or SDL_DestroyTexture(). The caller should not free it.
Parameters
texture the texture to lock for access, which must be created with SDL_TEXTUREACCESS_STREAMING.
rect a pointer to the rectangle to lock for access. If the rect is NULL, the entire texture will be locked.
surface a pointer to an SDL surface of size rect. Don't assume any specific pixel content.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockTexture
SDL_UnlockTexture
{
    SDL_Rect real_rect;
    void *pixels = NULL;
    int pitch = 0; // fix static analysis
    if (!texture || !surface) {
        return false;
    }
    real_rect.x = 0;
    real_rect.y = 0;
    real_rect.w = texture->w;
    real_rect.h = texture->h;
    if (rect) {
        SDL_GetRectIntersection(rect, &real_rect, &real_rect);
    }
    if (!SDL_LockTexture(texture, &real_rect, &pixels, &pitch)) {
        return false;
    }
    texture->locked_surface = SDL_CreateSurfaceFrom(real_rect.w, real_rect.h, texture->format, pixels, pitch);
    if (!texture->locked_surface) {
        SDL_UnlockTexture(texture);
        return false;
    }
    *surface = texture->locked_surface;
    return true;
}
References SDL_Texture::format, SDL_Rect::h, SDL_Texture::h, SDL_Texture::locked_surface, NULL, SDL_CreateSurfaceFrom(), SDL_GetRectIntersection(), SDL_LockTexture(), SDL_UnlockTexture(), SDL_Rect::w, SDL_Texture::w, SDL_Rect::x, and SDL_Rect::y.
SDL_QuitRender()
void SDL_QuitRender (void)
{
    while (SDL_renderers) {
        SDL_DestroyRenderer(SDL_renderers);
    }
}
References SDL_DestroyRenderer(), and SDL_renderers.
Referenced by SDL_QuitSubSystem().
SDL_RenderApplyWindowShape()
void SDL_RenderApplyWindowShape (SDL_Renderer * renderer) static
{
    SDL_Surface *shape = (SDL_Surface *)SDL_GetPointerProperty(SDL_GetWindowProperties(renderer->window), SDL_PROP_WINDOW_SHAPE_POINTER, NULL);
    if (shape != renderer->shape_surface) {
        if (renderer->shape_texture) {
            SDL_DestroyTexture(renderer->shape_texture);
            renderer->shape_texture = NULL;
        }
        if (shape) {
            // There's nothing we can do if this fails, so just keep on going
            renderer->shape_texture = SDL_CreateTextureFromSurface(renderer, shape);
            SDL_SetTextureBlendMode(renderer->shape_texture,
                SDL_ComposeCustomBlendMode(
                    SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_SRC_ALPHA, SDL_BLENDOPERATION_ADD,
                    SDL_BLENDFACTOR_ZERO, SDL_BLENDFACTOR_SRC_ALPHA, SDL_BLENDOPERATION_ADD));
        }
        renderer->shape_surface = shape;
    }
    if (renderer->shape_texture) {
        SDL_RenderTexture(renderer, renderer->shape_texture, NULL, NULL);
    }
}
References NULL, SDL_BLENDFACTOR_SRC_ALPHA, SDL_BLENDFACTOR_ZERO, SDL_BLENDOPERATION_ADD, SDL_ComposeCustomBlendMode(), SDL_CreateTextureFromSurface(), SDL_DestroyTexture(), SDL_GetPointerProperty(), SDL_GetWindowProperties(), SDL_PROP_WINDOW_SHAPE_POINTER, SDL_RenderTexture(), SDL_SetTextureBlendMode(), SDL_Renderer::shape_surface, SDL_Renderer::shape_texture, and SDL_Renderer::window.
Referenced by SDL_RenderPresent().
SDL_RenderClear()
bool SDL_RenderClear (SDL_Renderer * renderer)
Clear the current rendering target with the drawing color.
This function clears the entire rendering target, ignoring the viewport and the clip rectangle. Note, that clearing will also set/fill all pixels of the rendering target to current renderer draw color, so make sure to invoke SDL_SetRenderDrawColor() when needed.
Parameters
renderer the rendering context.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderDrawColor
{
    CHECK_RENDERER_MAGIC(renderer, false);
    return QueueCmdClear(renderer);
}
References CHECK_RENDERER_MAGIC, and QueueCmdClear().
SDL_RenderClipEnabled()
bool SDL_RenderClipEnabled (SDL_Renderer * renderer)
Get whether clipping is enabled on the given render target.
Each render target has its own clip rectangle. This function checks the cliprect for the current render target.
Parameters
renderer the rendering context.
Returns
true if clipping is enabled or false if not; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderClipRect
SDL_SetRenderClipRect
{
    CHECK_RENDERER_MAGIC(renderer, false)
    return renderer->view->clipping_enabled;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::clipping_enabled, and SDL_Renderer::view.
SDL_RenderCoordinatesFromWindow()
bool SDL_RenderCoordinatesFromWindow (SDL_Renderer * renderer, float window_x, float window_y, float * x, float * y)
Get a point in render coordinates when given a point in window coordinates.
This takes into account several states:
The window dimensions.
The logical presentation settings (SDL_SetRenderLogicalPresentation)
The scale (SDL_SetRenderScale)
The viewport (SDL_SetRenderViewport)
Parameters
renderer the rendering context.
window_x the x coordinate in window coordinates.
window_y the y coordinate in window coordinates.
x a pointer filled with the x coordinate in render coordinates.
y a pointer filled with the y coordinate in render coordinates.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderLogicalPresentation
SDL_SetRenderScale
{
    float render_x, render_y;
    CHECK_RENDERER_MAGIC(renderer, false);
    // Convert from window coordinates to pixels within the window
    render_x = window_x * renderer->dpi_scale.x;
    render_y = window_y * renderer->dpi_scale.y;
    // Convert from pixels within the window to pixels within the view
    const SDL_RenderViewState *view = &renderer->main_view;
    if (view->logical_presentation_mode != SDL_LOGICAL_PRESENTATION_DISABLED) {
        const SDL_FRect *src = &view->logical_src_rect;
        const SDL_FRect *dst = &view->logical_dst_rect;
        render_x = ((render_x - dst->x) * src->w) / dst->w;
        render_y = ((render_y - dst->y) * src->h) / dst->h;
    }
    render_x = (render_x / view->scale.x) - view->viewport.x;
    render_y = (render_y / view->scale.y) - view->viewport.y;
    if (x) {
        *x = render_x;
    }
    if (y) {
        *y = render_y;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::dpi_scale, SDL_FRect::h, SDL_RenderViewState::logical_dst_rect, SDL_RenderViewState::logical_presentation_mode, SDL_RenderViewState::logical_src_rect, SDL_Renderer::main_view, SDL_RenderViewState::scale, SDL_LOGICAL_PRESENTATION_DISABLED, SDL_RenderViewState::viewport, SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_Rect::x, SDL_FPoint::y, SDL_FRect::y, and SDL_Rect::y.
Referenced by SDL_ConvertEventToRenderCoordinates(), and SDL_GetRenderSafeArea().
SDL_RenderCoordinatesToWindow()
bool SDL_RenderCoordinatesToWindow (SDL_Renderer * renderer, float x, float y, float * window_x, float * window_y)
Get a point in window coordinates when given a point in render coordinates.
This takes into account several states:
The window dimensions.
The logical presentation settings (SDL_SetRenderLogicalPresentation)
The scale (SDL_SetRenderScale)
The viewport (SDL_SetRenderViewport)
Parameters
renderer the rendering context.
x the x coordinate in render coordinates.
y the y coordinate in render coordinates.
window_x a pointer filled with the x coordinate in window coordinates.
window_y a pointer filled with the y coordinate in window coordinates.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_SetRenderLogicalPresentation
SDL_SetRenderScale
SDL_SetRenderViewport
{
    CHECK_RENDERER_MAGIC(renderer, false);
    const SDL_RenderViewState *view = &renderer->main_view;
    x = (view->viewport.x + x) * view->scale.x;
    y = (view->viewport.y + y) * view->scale.y;
    // Convert from render coordinates to pixels within the window
    if (view->logical_presentation_mode != SDL_LOGICAL_PRESENTATION_DISABLED) {
        const SDL_FRect *src = &view->logical_src_rect;
        const SDL_FRect *dst = &view->logical_dst_rect;
        x = dst->x + ((x * dst->w) / src->w);
        y = dst->y + ((y * dst->h) / src->h);
    }
    // Convert from pixels within the window to window coordinates
    x /= renderer->dpi_scale.x;
    y /= renderer->dpi_scale.y;
    if (window_x) {
        *window_x = x;
    }
    if (window_y) {
        *window_y = y;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::dpi_scale, SDL_FRect::h, SDL_RenderViewState::logical_dst_rect, SDL_RenderViewState::logical_presentation_mode, SDL_RenderViewState::logical_src_rect, SDL_Renderer::main_view, SDL_RenderViewState::scale, SDL_LOGICAL_PRESENTATION_DISABLED, SDL_RenderViewState::viewport, SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_Rect::x, SDL_FPoint::y, SDL_FRect::y, and SDL_Rect::y.
SDL_RenderDebugText()
bool SDL_RenderDebugText (SDL_Renderer * renderer, float x, float y, const char * str)
Draw debug text to an SDL_Renderer.
This function will render a string of text to an SDL_Renderer. Note that this is a convenience function for debugging, with severe limitations, and not intended to be used for production apps and games.
Among these limitations:
It accepts UTF-8 strings, but will only renders ASCII characters.
It has a single, tiny size (8x8 pixels). One can use logical presentation or scaling to adjust it, but it will be blurry.
It uses a simple, hardcoded bitmap font. It does not allow different font selections and it does not support truetype, for proper scaling.
It does no word-wrapping and does not treat newline characters as a line break. If the text goes out of the window, it's gone.
For serious text rendering, there are several good options, such as SDL_ttf, stb_truetype, or other external libraries.
On first use, this will create an internal texture for rendering glyphs. This texture will live until the renderer is destroyed.
The text is drawn in the color specified by SDL_SetRenderDrawColor().
Parameters
renderer the renderer which should draw a line of text.
x the x coordinate where the top-left corner of the text will draw.
y the y coordinate where the top-left corner of the text will draw.
str the string to render.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderDebugTextFormat
SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE
{
    CHECK_RENDERER_MAGIC(renderer, false);
    // Allocate a texture atlas for this renderer if needed.
    if (!renderer->debug_char_texture_atlas) {
        if (!CreateDebugTextAtlas(renderer)) {
            return false;
        }
    }
    bool result = true;
    Uint8 r, g, b, a;
    result &= SDL_GetRenderDrawColor(renderer, &r, &g, &b, &a);
    result &= SDL_SetTextureColorMod(renderer->debug_char_texture_atlas, r, g, b);
    result &= SDL_SetTextureAlphaMod(renderer->debug_char_texture_atlas, a);
    float curx = x;
    Uint32 ch;
    while (result && ((ch = SDL_StepUTF8(&s, NULL)) != 0)) {
        result &= DrawDebugCharacter(renderer, curx, y, ch);
        curx += SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE;
    }
    return result;
}
References CHECK_RENDERER_MAGIC, CreateDebugTextAtlas(), SDL_Renderer::debug_char_texture_atlas, DrawDebugCharacter(), NULL, SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE, SDL_GetRenderDrawColor(), SDL_SetTextureAlphaMod(), SDL_SetTextureColorMod(), and SDL_StepUTF8().
Referenced by SDL_RenderDebugTextFormat().
SDL_RenderDebugTextFormat()
bool SDL_RenderDebugTextFormat (SDL_Renderer * renderer, float x, float y, SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
Draw debug text to an SDL_Renderer.
This function will render a printf()-style format string to a renderer. Note that this is a convinence function for debugging, with severe limitations, and is not intended to be used for production apps and games.
For the full list of limitations and other useful information, see SDL_RenderDebugText.
Parameters
renderer the renderer which should draw the text.
x the x coordinate where the top-left corner of the text will draw.
y the y coordinate where the top-left corner of the text will draw.
fmt the format string to draw.
... additional parameters matching % tokens in the fmt string, if any.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderDebugText
SDL_DEBUG_TEXT_FONT_CHARACTER_SIZE
{
    va_list ap;
    va_start(ap, fmt);
    // fast path to avoid unnecessary allocation and copy. If you're going through the dynapi, there's a good chance
    // you _always_ hit this path, since it probably had to process varargs before calling into the jumptable.
    if (SDL_strcmp(fmt, "%s") == 0) {
        const char *str = va_arg(ap, const char *);
        va_end(ap);
        return SDL_RenderDebugText(renderer, x, y, str);
    }
    char *str = NULL;
    const int rc = SDL_vasprintf(&str, fmt, ap);
    va_end(ap);
    if (rc == -1) {
        return false;
    }
    const bool retval = SDL_RenderDebugText(renderer, x, y, str);
    SDL_free(str);
    return retval;
}
References NULL, SDL_free(), SDL_PRINTF_FORMAT_STRING, SDL_RenderDebugText(), SDL_strcmp(), and SDL_vasprintf().
SDL_RendererEventWatch()
bool SDL_RendererEventWatch (void * userdata, SDL_Event * event) static
{
    SDL_Renderer *renderer = (SDL_Renderer *)userdata;
    SDL_Window *window = renderer->window;
    if (event->window.windowID != SDL_GetWindowID(window)) {
        return true;
    }
    if (renderer->WindowEvent) {
        renderer->WindowEvent(renderer, &event->window);
    }
    if (event->type == SDL_EVENT_WINDOW_RESIZED ||
        event->type == SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED ||
        event->type == SDL_EVENT_WINDOW_METAL_VIEW_RESIZED) {
            SDL_RenderViewState *view = renderer->view;
            renderer->view = &renderer->main_view;  // only update the main_view (the window framebuffer) for window changes.
            UpdateLogicalPresentation(renderer);
            renderer->view = view;  // put us back on whatever the current render target's actual view is.
    } else if (event->type == SDL_EVENT_WINDOW_HIDDEN) {
        renderer->hidden = true;
    } else if (event->type == SDL_EVENT_WINDOW_SHOWN) {
        if (!(SDL_GetWindowFlags(window) & SDL_WINDOW_MINIMIZED)) {
            renderer->hidden = false;
        }
    } else if (event->type == SDL_EVENT_WINDOW_MINIMIZED) {
        renderer->hidden = true;
    } else if (event->type == SDL_EVENT_WINDOW_RESTORED ||
               event->type == SDL_EVENT_WINDOW_MAXIMIZED) {
        if (!(SDL_GetWindowFlags(window) & SDL_WINDOW_HIDDEN)) {
            renderer->hidden = false;
        }
    } else if (event->type == SDL_EVENT_WINDOW_DISPLAY_CHANGED ||
               event->type == SDL_EVENT_WINDOW_HDR_STATE_CHANGED) {
        UpdateHDRProperties(renderer);
    }
    return true;
}
References SDL_Renderer::hidden, SDL_Renderer::main_view, SDL_EVENT_WINDOW_DISPLAY_CHANGED, SDL_EVENT_WINDOW_HDR_STATE_CHANGED, SDL_EVENT_WINDOW_HIDDEN, SDL_EVENT_WINDOW_MAXIMIZED, SDL_EVENT_WINDOW_METAL_VIEW_RESIZED, SDL_EVENT_WINDOW_MINIMIZED, SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED, SDL_EVENT_WINDOW_RESIZED, SDL_EVENT_WINDOW_RESTORED, SDL_EVENT_WINDOW_SHOWN, SDL_GetWindowFlags(), SDL_GetWindowID(), SDL_WINDOW_HIDDEN, SDL_WINDOW_MINIMIZED, UpdateHDRProperties(), UpdateLogicalPresentation(), SDL_Renderer::view, SDL_Renderer::window, and SDL_Renderer::WindowEvent.
Referenced by SDL_CreateRendererWithProperties(), and SDL_DestroyRendererWithoutFreeing().
SDL_RenderFillRect()
bool SDL_RenderFillRect (SDL_Renderer * renderer, const SDL_FRect * rect)
Fill a rectangle on the current rendering target with the drawing color at subpixel precision.
Parameters
renderer the renderer which should fill a rectangle.
rect a pointer to the destination rectangle, or NULL for the entire rendering target.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderFillRects
{
    SDL_FRect frect;
    CHECK_RENDERER_MAGIC(renderer, false);
    // If 'rect' == NULL, then fill the whole surface
    if (!rect) {
        GetRenderViewportSize(renderer, &frect);
        rect = &frect;
    }
    return SDL_RenderFillRects(renderer, rect, 1);
}
References CHECK_RENDERER_MAGIC, GetRenderViewportSize(), and SDL_RenderFillRects().
Referenced by SDL_RenderLogicalBorders().
SDL_RenderFillRects()
bool SDL_RenderFillRects (SDL_Renderer * renderer, const SDL_FRect * rects, int count)
Fill some number of rectangles on the current rendering target with the drawing color at subpixel precision.
Parameters
renderer the renderer which should fill multiple rectangles.
rects a pointer to an array of destination rectangles.
count the number of rectangles.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderFillRect
{
    SDL_FRect *frects;
    int i;
    bool result;
    bool isstack;
    CHECK_RENDERER_MAGIC(renderer, false);
    if (!rects) {
        return SDL_InvalidParamError("SDL_RenderFillRects(): rects");
    }
    if (count < 1) {
        return true;
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    frects = SDL_small_alloc(SDL_FRect, count, &isstack);
    if (!frects) {
        return false;
    }
    const SDL_RenderViewState *view = renderer->view;
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    for (i = 0; i < count; ++i) {
        frects[i].x = rects[i].x * scale_x;
        frects[i].y = rects[i].y * scale_y;
        frects[i].w = rects[i].w * scale_x;
        frects[i].h = rects[i].h * scale_y;
    }
    result = QueueCmdFillRects(renderer, frects, count);
    SDL_small_free(frects, isstack);
    return result;
}
References CHECK_RENDERER_MAGIC, count, SDL_RenderViewState::current_scale, SDL_FRect::h, SDL_Renderer::hidden, QueueCmdFillRects(), SDL_InvalidParamError, SDL_small_alloc, SDL_small_free, SDL_Renderer::view, SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by SDL_RenderFillRect().
SDL_RenderGeometry()
bool SDL_RenderGeometry (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_Vertex * vertices, int num_vertices, const int * indices, int num_indices)
Render a list of triangles, optionally using a texture and indices into the vertex array Color and alpha modulation is done per vertex (SDL_SetTextureColorMod and SDL_SetTextureAlphaMod are ignored).
Parameters
renderer the rendering context.
texture (optional) The SDL texture to use.
vertices vertices.
num_vertices number of vertices.
indices (optional) An array of integer indices into the 'vertices' array, if NULL all vertices will be rendered in sequential order.
num_indices number of indices.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderGeometryRaw
SDL_SetRenderTextureAddressMode
{
    if (vertices) {
        const float *xy = &vertices->position.x;
        int xy_stride = sizeof(SDL_Vertex);
        const SDL_FColor *color = &vertices->color;
        int color_stride = sizeof(SDL_Vertex);
        const float *uv = &vertices->tex_coord.x;
        int uv_stride = sizeof(SDL_Vertex);
        int size_indices = 4;
        return SDL_RenderGeometryRaw(renderer, texture, xy, xy_stride, color, color_stride, uv, uv_stride, num_vertices, indices, num_indices, size_indices);
    } else {
        return SDL_InvalidParamError("vertices");
    }
}
References SDL_Vertex::color, SDL_Vertex::position, SDL_InvalidParamError, SDL_RenderGeometryRaw(), SDL_Vertex::tex_coord, and SDL_FPoint::x.
SDL_RenderGeometryRaw()
bool SDL_RenderGeometryRaw (SDL_Renderer * renderer, SDL_Texture * texture, const float * xy, int xy_stride, const SDL_FColor * color, int color_stride, const float * uv, int uv_stride, int num_vertices, const void * indices, int num_indices, int size_indices)
Render a list of triangles, optionally using a texture and indices into the vertex arrays Color and alpha modulation is done per vertex (SDL_SetTextureColorMod and SDL_SetTextureAlphaMod are ignored).
Parameters
renderer the rendering context.
texture (optional) The SDL texture to use.
xy vertex positions.
xy_stride byte size to move from one element to the next element.
color vertex colors (as SDL_FColor).
color_stride byte size to move from one element to the next element.
uv vertex normalized texture coordinates.
uv_stride byte size to move from one element to the next element.
num_vertices number of vertices.
indices (optional) An array of indices into the 'vertices' arrays, if NULL all vertices will be rendered in sequential order.
num_indices number of indices.
size_indices index size: 1 (byte), 2 (short), 4 (int).
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderGeometry
SDL_SetRenderTextureAddressMode
{
    int i;
    int count = indices ? num_indices : num_vertices;
    SDL_TextureAddressMode texture_address_mode_u;
    SDL_TextureAddressMode texture_address_mode_v;
    CHECK_RENDERER_MAGIC(renderer, false);
    if (!renderer->QueueGeometry) {
        return SDL_Unsupported();
    }
    if (texture) {
        CHECK_TEXTURE_MAGIC(texture, false);
        if (renderer != texture->renderer) {
            return SDL_SetError("Texture was not created with this renderer");
        }
    }
    if (!xy) {
        return SDL_InvalidParamError("xy");
    }
    if (!color) {
        return SDL_InvalidParamError("color");
    }
    if (texture && !uv) {
        return SDL_InvalidParamError("uv");
    }
    if (count % 3 != 0) {
        return SDL_InvalidParamError(indices ? "num_indices" : "num_vertices");
    }
    if (indices) {
        if (size_indices != 1 && size_indices != 2 && size_indices != 4) {
            return SDL_InvalidParamError("size_indices");
        }
    } else {
        size_indices = 0;
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    if (num_vertices < 3) {
        return true;
    }
    if (texture && texture->native) {
        texture = texture->native;
    }
    texture_address_mode_u = renderer->texture_address_mode_u;
    texture_address_mode_v = renderer->texture_address_mode_v;
    if (texture &&
        (texture_address_mode_u == SDL_TEXTURE_ADDRESS_AUTO ||
         texture_address_mode_v == SDL_TEXTURE_ADDRESS_AUTO)) {
        for (i = 0; i < num_vertices; ++i) {
            const float *uv_ = (const float *)((const char *)uv + i * uv_stride);
            float u = uv_[0];
            float v = uv_[1];
            if (u < 0.0f || u > 1.0f) {
                if (texture_address_mode_u == SDL_TEXTURE_ADDRESS_AUTO) {
                    texture_address_mode_u = SDL_TEXTURE_ADDRESS_WRAP;
                    if (texture_address_mode_v != SDL_TEXTURE_ADDRESS_AUTO) {
                        break;
                    }
                }
            }
            if (v < 0.0f || v > 1.0f) {
                if (texture_address_mode_v == SDL_TEXTURE_ADDRESS_AUTO) {
                    texture_address_mode_v = SDL_TEXTURE_ADDRESS_WRAP;
                    if (texture_address_mode_u != SDL_TEXTURE_ADDRESS_AUTO) {
                        break;
                    }
                }
            }
        }
        if (texture_address_mode_u == SDL_TEXTURE_ADDRESS_AUTO) {
            texture_address_mode_u = SDL_TEXTURE_ADDRESS_CLAMP;
        }
        if (texture_address_mode_v == SDL_TEXTURE_ADDRESS_AUTO) {
            texture_address_mode_v = SDL_TEXTURE_ADDRESS_CLAMP;
        }
    }
    if (indices) {
        for (i = 0; i < num_indices; ++i) {
            int j;
            if (size_indices == 4) {
                j = ((const Uint32 *)indices)[i];
            } else if (size_indices == 2) {
                j = ((const Uint16 *)indices)[i];
            } else {
                j = ((const Uint8 *)indices)[i];
            }
            if (j < 0 || j >= num_vertices) {
                return SDL_SetError("Values of 'indices' out of bounds");
            }
        }
    }
    if (texture) {
        texture->last_command_generation = renderer->render_command_generation;
    }
    // For the software renderer, try to reinterpret triangles as SDL_Rect
#ifdef SDL_VIDEO_RENDER_SW
    if (renderer->software &&
        texture_address_mode_u == SDL_TEXTURE_ADDRESS_CLAMP &&
        texture_address_mode_v == SDL_TEXTURE_ADDRESS_CLAMP) {
        return SDL_SW_RenderGeometryRaw(renderer, texture,
                                        xy, xy_stride, color, color_stride, uv, uv_stride, num_vertices,
                                        indices, num_indices, size_indices);
    }
#endif
    const SDL_RenderViewState *view = renderer->view;
    return QueueCmdGeometry(renderer, texture,
                            xy, xy_stride, color, color_stride, uv, uv_stride,
                            num_vertices, indices, num_indices, size_indices,
                            view->current_scale.x, view->current_scale.y,
                            texture_address_mode_u, texture_address_mode_v);
}
References CHECK_RENDERER_MAGIC, CHECK_TEXTURE_MAGIC, count, SDL_RenderViewState::current_scale, SDL_Renderer::hidden, SDL_Texture::last_command_generation, SDL_Texture::native, QueueCmdGeometry(), SDL_Renderer::QueueGeometry, SDL_Renderer::render_command_generation, SDL_Texture::renderer, SDL_InvalidParamError, SDL_SetError(), SDL_TEXTURE_ADDRESS_AUTO, SDL_TEXTURE_ADDRESS_CLAMP, SDL_TEXTURE_ADDRESS_WRAP, SDL_Unsupported, SDL_Renderer::software, SDL_Renderer::texture_address_mode_u, SDL_Renderer::texture_address_mode_v, SDL_Renderer::view, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_RenderGeometry().
SDL_RenderingLinearSpace()
bool SDL_RenderingLinearSpace (SDL_Renderer * renderer)
{
    SDL_Colorspace colorspace;
    if (renderer->target) {
        colorspace = renderer->target->colorspace;
    } else {
        colorspace = renderer->output_colorspace;
    }
    if (colorspace == SDL_COLORSPACE_SRGB_LINEAR) {
        return true;
    }
    return false;
}
References SDL_Texture::colorspace, SDL_Renderer::output_colorspace, SDL_COLORSPACE_SRGB_LINEAR, and SDL_Renderer::target.
SDL_RenderLine()
bool SDL_RenderLine (SDL_Renderer * renderer, float x1, float y1, float x2, float y2)
Draw a line on the current rendering target at subpixel precision.
Parameters
renderer the renderer which should draw a line.
x1 the x coordinate of the start point.
y1 the y coordinate of the start point.
x2 the x coordinate of the end point.
y2 the y coordinate of the end point.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderLines
{
    SDL_FPoint points[2];
    points[0].x = x1;
    points[0].y = y1;
    points[1].x = x2;
    points[1].y = y2;
    return SDL_RenderLines(renderer, points, 2);
}
References SDL_RenderLines(), SDL_FPoint::x, x1, x2, SDL_FPoint::y, and y1.
SDL_RenderLines()
bool SDL_RenderLines (SDL_Renderer * renderer, const SDL_FPoint * points, int count)
Draw a series of connected lines on the current rendering target at subpixel precision.
Parameters
renderer the renderer which should draw multiple lines.
points the points along the lines.
count the number of points, drawing count-1 lines.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderLine
{
    bool result = true;
    CHECK_RENDERER_MAGIC(renderer, false);
    if (!points) {
        return SDL_InvalidParamError("SDL_RenderLines(): points");
    }
    if (count < 2) {
        return true;
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    SDL_RenderViewState *view = renderer->view;
    const bool islogical = (view->logical_presentation_mode != SDL_LOGICAL_PRESENTATION_DISABLED);
    if (islogical || (renderer->line_method == SDL_RENDERLINEMETHOD_GEOMETRY)) {
        const float scale_x = view->current_scale.x;
        const float scale_y = view->current_scale.y;
        bool isstack1;
        bool isstack2;
        float *xy = SDL_small_alloc(float, 4 * 2 * count, &isstack1);
        int *indices = SDL_small_alloc(int, (4) * 3 * (count - 1) + (2) * 3 * (count), &isstack2);
        if (xy && indices) {
            int i;
            float *ptr_xy = xy;
            int *ptr_indices = indices;
            const int xy_stride = 2 * sizeof(float);
            int num_vertices = 4 * count;
            int num_indices = 0;
            const int size_indices = 4;
            int cur_index = -4;
            const bool is_looping = (points[0].x == points[count - 1].x && points[0].y == points[count - 1].y);
            SDL_FPoint p; // previous point
            p.x = p.y = 0.0f;
            /*       p            q
                    0----1------ 4----5
                    | \  |``\    | \  |
                    |  \ |   ` `\|  \ |
                    3----2-------7----6
            */
            for (i = 0; i < count; ++i) {
                SDL_FPoint q = points[i]; // current point
                q.x *= scale_x;
                q.y *= scale_y;
                *ptr_xy++ = q.x;
                *ptr_xy++ = q.y;
                *ptr_xy++ = q.x + scale_x;
                *ptr_xy++ = q.y;
                *ptr_xy++ = q.x + scale_x;
                *ptr_xy++ = q.y + scale_y;
                *ptr_xy++ = q.x;
                *ptr_xy++ = q.y + scale_y;
#define ADD_TRIANGLE(i1, i2, i3)        \
    *ptr_indices++ = cur_index + (i1);  \
    *ptr_indices++ = cur_index + (i2);  \
    *ptr_indices++ = cur_index + (i3);  \
    num_indices += 3;
                // closed polyline, dont draw twice the point
                if (i || !is_looping) {
                    ADD_TRIANGLE(4, 5, 6)
                    ADD_TRIANGLE(4, 6, 7)
                }
                // first point only, no segment
                if (i == 0) {
                    p = q;
                    cur_index += 4;
                    continue;
                }
                // draw segment
                if (p.y == q.y) {
                    if (p.x < q.x) {
                        ADD_TRIANGLE(1, 4, 7)
                        ADD_TRIANGLE(1, 7, 2)
                    } else {
                        ADD_TRIANGLE(5, 0, 3)
                        ADD_TRIANGLE(5, 3, 6)
                    }
                } else if (p.x == q.x) {
                    if (p.y < q.y) {
                        ADD_TRIANGLE(2, 5, 4)
                        ADD_TRIANGLE(2, 4, 3)
                    } else {
                        ADD_TRIANGLE(6, 1, 0)
                        ADD_TRIANGLE(6, 0, 7)
                    }
                } else {
                    if (p.y < q.y) {
                        if (p.x < q.x) {
                            ADD_TRIANGLE(1, 5, 4)
                            ADD_TRIANGLE(1, 4, 2)
                            ADD_TRIANGLE(2, 4, 7)
                            ADD_TRIANGLE(2, 7, 3)
                        } else {
                            ADD_TRIANGLE(4, 0, 5)
                            ADD_TRIANGLE(5, 0, 3)
                            ADD_TRIANGLE(5, 3, 6)
                            ADD_TRIANGLE(6, 3, 2)
                        }
                    } else {
                        if (p.x < q.x) {
                            ADD_TRIANGLE(0, 4, 7)
                            ADD_TRIANGLE(0, 7, 1)
                            ADD_TRIANGLE(1, 7, 6)
                            ADD_TRIANGLE(1, 6, 2)
                        } else {
                            ADD_TRIANGLE(6, 5, 1)
                            ADD_TRIANGLE(6, 1, 0)
                            ADD_TRIANGLE(7, 6, 0)
                            ADD_TRIANGLE(7, 0, 3)
                        }
                    }
                }
                p = q;
                cur_index += 4;
            }
            result = QueueCmdGeometry(renderer, NULL,
                                      xy, xy_stride, &renderer->color, 0 /* color_stride */, NULL, 0,
                                      num_vertices, indices, num_indices, size_indices,
                                      1.0f, 1.0f, SDL_TEXTURE_ADDRESS_CLAMP, SDL_TEXTURE_ADDRESS_CLAMP);
        }
        SDL_small_free(xy, isstack1);
        SDL_small_free(indices, isstack2);
    } else if (renderer->line_method == SDL_RENDERLINEMETHOD_POINTS) {
        result = RenderLinesWithRectsF(renderer, points, count);
    } else if (view->scale.x != 1.0f || view->scale.y != 1.0f) {  /* we checked for logical scale elsewhere. */
        result = RenderLinesWithRectsF(renderer, points, count);
    } else {
        result = QueueCmdDrawLines(renderer, points, count);
    }
    return result;
}
References ADD_TRIANGLE, CHECK_RENDERER_MAGIC, SDL_Renderer::color, count, SDL_RenderViewState::current_scale, SDL_Renderer::hidden, SDL_Renderer::line_method, SDL_RenderViewState::logical_presentation_mode, NULL, QueueCmdDrawLines(), QueueCmdGeometry(), RenderLinesWithRectsF(), SDL_RenderViewState::scale, SDL_InvalidParamError, SDL_LOGICAL_PRESENTATION_DISABLED, SDL_RENDERLINEMETHOD_GEOMETRY, SDL_RENDERLINEMETHOD_POINTS, SDL_small_alloc, SDL_small_free, SDL_TEXTURE_ADDRESS_CLAMP, SDL_Renderer::view, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_RenderLine(), and SDL_RenderRect().
SDL_RenderLogicalBorders()
void SDL_RenderLogicalBorders (SDL_Renderer * renderer, const SDL_FRect * dst) static
{
    const SDL_RenderViewState *view = renderer->view;
    if (dst->x > 0.0f || dst->y > 0.0f) {
        SDL_BlendMode saved_blend_mode = renderer->blendMode;
        SDL_FColor saved_color = renderer->color;
        SDL_SetRenderDrawBlendMode(renderer, SDL_BLENDMODE_NONE);
        SDL_SetRenderDrawColorFloat(renderer, 0.0f, 0.0f, 0.0f, 1.0f);
        if (dst->x > 0.0f) {
            SDL_FRect rect;
            rect.x = 0.0f;
            rect.y = 0.0f;
            rect.w = dst->x;
            rect.h = (float)view->pixel_h;
            SDL_RenderFillRect(renderer, &rect);
            rect.x = dst->x + dst->w;
            rect.w = (float)view->pixel_w - rect.x;
            SDL_RenderFillRect(renderer, &rect);
        }
        if (dst->y > 0.0f) {
            SDL_FRect rect;
            rect.x = 0.0f;
            rect.y = 0.0f;
            rect.w = (float)view->pixel_w;
            rect.h = dst->y;
            SDL_RenderFillRect(renderer, &rect);
            rect.y = dst->y + dst->h;
            rect.h = (float)view->pixel_h - rect.y;
            SDL_RenderFillRect(renderer, &rect);
        }
        SDL_SetRenderDrawBlendMode(renderer, saved_blend_mode);
        SDL_SetRenderDrawColorFloat(renderer, saved_color.r, saved_color.g, saved_color.b, saved_color.a);
    }
}
References SDL_FColor::a, SDL_FColor::b, SDL_Renderer::blendMode, SDL_Renderer::color, SDL_FColor::g, SDL_FRect::h, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, SDL_FColor::r, SDL_BLENDMODE_NONE, SDL_RenderFillRect(), SDL_SetRenderDrawBlendMode(), SDL_SetRenderDrawColorFloat(), SDL_Renderer::view, SDL_FRect::w, SDL_FRect::x, and SDL_FRect::y.
Referenced by SDL_RenderLogicalPresentation().
SDL_RenderLogicalPresentation()
void SDL_RenderLogicalPresentation (SDL_Renderer * renderer) static
{
    SDL_assert(renderer->view == &renderer->main_view);
    SDL_RenderViewState *view = &renderer->main_view;
    const SDL_RendererLogicalPresentation mode = view->logical_presentation_mode;
    if (mode == SDL_LOGICAL_PRESENTATION_LETTERBOX) {
        // save off some state we're going to trample.
        const int logical_w = view->logical_w;
        const int logical_h = view->logical_h;
        const float scale_x = view->scale.x;
        const float scale_y = view->scale.y;
        const bool clipping_enabled = view->clipping_enabled;
        SDL_Rect orig_viewport, orig_cliprect;
        const SDL_FRect logical_dst_rect = view->logical_dst_rect;
        SDL_copyp(&orig_viewport, &view->viewport);
        if (clipping_enabled) {
            SDL_copyp(&orig_cliprect, &view->clip_rect);
        }
        // trample some state.
        SDL_SetRenderLogicalPresentation(renderer, logical_w, logical_h, SDL_LOGICAL_PRESENTATION_DISABLED);
        SDL_SetRenderViewport(renderer, NULL);
        if (clipping_enabled) {
            SDL_SetRenderClipRect(renderer, NULL);
        }
        SDL_SetRenderScale(renderer, 1.0f, 1.0f);
        // draw the borders.
        SDL_RenderLogicalBorders(renderer, &logical_dst_rect);
        // now set everything back.
        view->logical_presentation_mode = mode;
        SDL_SetRenderViewport(renderer, &orig_viewport);
        if (clipping_enabled) {
            SDL_SetRenderClipRect(renderer, &orig_cliprect);
        }
        SDL_SetRenderScale(renderer, scale_x, scale_y);
        SDL_SetRenderLogicalPresentation(renderer, logical_w, logical_h, mode);
    }
}
References SDL_RenderViewState::clip_rect, SDL_RenderViewState::clipping_enabled, SDL_RenderViewState::logical_dst_rect, SDL_RenderViewState::logical_h, SDL_RenderViewState::logical_presentation_mode, SDL_RenderViewState::logical_w, SDL_Renderer::main_view, NULL, SDL_RenderViewState::scale, SDL_assert, SDL_copyp, SDL_LOGICAL_PRESENTATION_DISABLED, SDL_LOGICAL_PRESENTATION_LETTERBOX, SDL_RenderLogicalBorders(), SDL_SetRenderClipRect(), SDL_SetRenderLogicalPresentation(), SDL_SetRenderScale(), SDL_SetRenderViewport(), SDL_Renderer::view, SDL_RenderViewState::viewport, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_RenderPresent().
SDL_RenderPoint()
bool SDL_RenderPoint (SDL_Renderer * renderer, float x, float y)
Draw a point on the current rendering target at subpixel precision.
Parameters
renderer the renderer which should draw a point.
x the x coordinate of the point.
y the y coordinate of the point.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderPoints
{
    SDL_FPoint fpoint;
    fpoint.x = x;
    fpoint.y = y;
    return SDL_RenderPoints(renderer, &fpoint, 1);
}
References SDL_RenderPoints(), SDL_FPoint::x, and SDL_FPoint::y.
SDL_RenderPoints()
bool SDL_RenderPoints (SDL_Renderer * renderer, const SDL_FPoint * points, int count)
Draw multiple points on the current rendering target at subpixel precision.
Parameters
renderer the renderer which should draw multiple points.
points the points to draw.
count the number of points to draw.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderPoint
{
    bool result;
    CHECK_RENDERER_MAGIC(renderer, false);
    if (!points) {
        return SDL_InvalidParamError("SDL_RenderPoints(): points");
    }
    if (count < 1) {
        return true;
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    const SDL_RenderViewState *view = renderer->view;
    if ((view->current_scale.x != 1.0f) || (view->current_scale.y != 1.0f)) {
        result = RenderPointsWithRects(renderer, points, count);
    } else {
        result = QueueCmdDrawPoints(renderer, points, count);
    }
    return result;
}
References CHECK_RENDERER_MAGIC, count, SDL_RenderViewState::current_scale, SDL_Renderer::hidden, QueueCmdDrawPoints(), RenderPointsWithRects(), SDL_InvalidParamError, SDL_Renderer::view, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_RenderPoint().
SDL_RenderPresent()
bool SDL_RenderPresent (SDL_Renderer * renderer)
Update the screen with any rendering performed since the previous call.
SDL's rendering functions operate on a backbuffer; that is, calling a rendering function such as SDL_RenderLine() does not directly put a line on the screen, but rather updates the backbuffer. As such, you compose your entire scene and present the composed backbuffer to the screen as a complete picture.
Therefore, when using SDL's rendering API, one does all drawing intended for the frame, and then calls this function once per frame to present the final drawing to the user.
The backbuffer should be considered invalidated after each present; do not assume that previous contents will exist between frames. You are strongly encouraged to call SDL_RenderClear() to initialize the backbuffer before starting each new frame's drawing, even if you plan to overwrite every pixel.
Please note, that in case of rendering to a texture - there is no need to call SDL_RenderPresent after drawing needed objects to a texture, and should not be done; you are only required to change back the rendering target to default via SDL_SetRenderTarget(renderer, NULL) afterwards, as textures by themselves do not have a concept of backbuffers. Calling SDL_RenderPresent while rendering to a texture will fail.
Parameters
renderer the rendering context.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_CreateRenderer
SDL_RenderClear
SDL_RenderFillRect
SDL_RenderFillRects
SDL_RenderLine
SDL_RenderLines
SDL_RenderPoint
SDL_RenderPoints
SDL_RenderRect
SDL_RenderRects
SDL_SetRenderDrawBlendMode
SDL_SetRenderDrawColor
{
    bool presented = true;
    CHECK_RENDERER_MAGIC(renderer, false);
    if (renderer->target) {
        return SDL_SetError("You can't present on a render target");
    }
    SDL_RenderLogicalPresentation(renderer);
    if (renderer->transparent_window) {
        SDL_RenderApplyWindowShape(renderer);
    }
    FlushRenderCommands(renderer); // time to send everything to the GPU!
#if DONT_DRAW_WHILE_HIDDEN
    // Don't present while we're hidden
    if (renderer->hidden) {
        presented = false;
    } else
#endif
    if (!renderer->RenderPresent(renderer)) {
        presented = false;
    }
    if (renderer->simulate_vsync ||
        (!presented && renderer->wanted_vsync)) {
        SDL_SimulateRenderVSync(renderer);
    }
    return true;
}
References CHECK_RENDERER_MAGIC, FlushRenderCommands(), SDL_Renderer::hidden, SDL_Renderer::RenderPresent, SDL_RenderApplyWindowShape(), SDL_RenderLogicalPresentation(), SDL_SetError(), SDL_SimulateRenderVSync(), SDL_Renderer::simulate_vsync, SDL_Renderer::target, SDL_Renderer::transparent_window, and SDL_Renderer::wanted_vsync.
Referenced by SDL_UpdateWindowTexture().
SDL_RenderReadPixels()
SDL_Surface * SDL_RenderReadPixels (SDL_Renderer * renderer, const SDL_Rect * rect)
Read pixels from the current rendering target.
The returned surface contains pixels inside the desired area clipped to the current viewport, and should be freed with SDL_DestroySurface().
Note that this returns the actual pixels on the screen, so if you are using logical presentation you should use SDL_GetRenderLogicalPresentationRect() to get the area containing your content.
WARNING: This is a very slow operation, and should not be used frequently. If you're using this on the main rendering target, it should be called after rendering and before SDL_RenderPresent().
Parameters
renderer the rendering context.
rect an SDL_Rect structure representing the area to read, which will be clipped to the current viewport, or NULL for the entire viewport.
Returns
a new SDL_Surface on success or NULL on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
{
    CHECK_RENDERER_MAGIC(renderer, NULL);
    if (!renderer->RenderReadPixels) {
        SDL_Unsupported();
        return NULL;
    }
    FlushRenderCommands(renderer); // we need to render before we read the results.
    SDL_Rect real_rect = renderer->view->pixel_viewport;
    if (rect) {
        if (!SDL_GetRectIntersection(rect, &real_rect, &real_rect)) {
            SDL_SetError("Can't read outside the current viewport");
            return NULL;
        }
    }
    SDL_Surface *surface = renderer->RenderReadPixels(renderer, &real_rect);
    if (surface) {
        SDL_PropertiesID props = SDL_GetSurfaceProperties(surface);
        if (renderer->target) {
            SDL_Texture *target = renderer->target;
            SDL_Texture *parent = SDL_GetPointerProperty(SDL_GetTextureProperties(target), SDL_PROP_TEXTURE_PARENT_POINTER, NULL);
            SDL_PixelFormat expected_format = (parent ? parent->format : target->format);
            SDL_SetFloatProperty(props, SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT, target->SDR_white_point);
            SDL_SetFloatProperty(props, SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT, target->HDR_headroom);
            // Set the expected surface format
            if ((surface->format == SDL_PIXELFORMAT_ARGB8888 && expected_format == SDL_PIXELFORMAT_XRGB8888) ||
                (surface->format == SDL_PIXELFORMAT_RGBA8888 && expected_format == SDL_PIXELFORMAT_RGBX8888) ||
                (surface->format == SDL_PIXELFORMAT_ABGR8888 && expected_format == SDL_PIXELFORMAT_XBGR8888) ||
                (surface->format == SDL_PIXELFORMAT_BGRA8888 && expected_format == SDL_PIXELFORMAT_BGRX8888)) {
                surface->format = expected_format;
                surface->fmt = SDL_GetPixelFormatDetails(expected_format);
            }
        } else {
            SDL_SetFloatProperty(props, SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT, renderer->SDR_white_point);
            SDL_SetFloatProperty(props, SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT, renderer->HDR_headroom);
        }
    }
    return surface;
}
References CHECK_RENDERER_MAGIC, FlushRenderCommands(), SDL_Texture::format, SDL_Renderer::HDR_headroom, NULL, SDL_RenderViewState::pixel_viewport, SDL_Renderer::RenderReadPixels, SDL_GetPixelFormatDetails(), SDL_GetPointerProperty(), SDL_GetRectIntersection(), SDL_GetSurfaceProperties(), SDL_GetTextureProperties(), SDL_PIXELFORMAT_ABGR8888, SDL_PIXELFORMAT_ARGB8888, SDL_PIXELFORMAT_BGRA8888, SDL_PIXELFORMAT_BGRX8888, SDL_PIXELFORMAT_RGBA8888, SDL_PIXELFORMAT_RGBX8888, SDL_PIXELFORMAT_XBGR8888, SDL_PIXELFORMAT_XRGB8888, SDL_PROP_SURFACE_HDR_HEADROOM_FLOAT, SDL_PROP_SURFACE_SDR_WHITE_POINT_FLOAT, SDL_PROP_TEXTURE_PARENT_POINTER, SDL_SetError(), SDL_SetFloatProperty(), SDL_Unsupported, SDL_Renderer::SDR_white_point, SDL_Renderer::target, and SDL_Renderer::view.
SDL_RenderRect()
bool SDL_RenderRect (SDL_Renderer * renderer, const SDL_FRect * rect)
Draw a rectangle on the current rendering target at subpixel precision.
Parameters
renderer the renderer which should draw a rectangle.
rect a pointer to the destination rectangle, or NULL to outline the entire rendering target.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderRects
{
    SDL_FRect frect;
    SDL_FPoint points[5];
    CHECK_RENDERER_MAGIC(renderer, false);
    // If 'rect' == NULL, then outline the whole surface
    if (!rect) {
        GetRenderViewportSize(renderer, &frect);
        rect = &frect;
    }
    points[0].x = rect->x;
    points[0].y = rect->y;
    points[1].x = rect->x + rect->w - 1;
    points[1].y = rect->y;
    points[2].x = rect->x + rect->w - 1;
    points[2].y = rect->y + rect->h - 1;
    points[3].x = rect->x;
    points[3].y = rect->y + rect->h - 1;
    points[4].x = rect->x;
    points[4].y = rect->y;
    return SDL_RenderLines(renderer, points, 5);
}
References CHECK_RENDERER_MAGIC, GetRenderViewportSize(), SDL_FRect::h, SDL_RenderLines(), SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by SDL_RenderRects().
SDL_RenderRects()
bool SDL_RenderRects (SDL_Renderer * renderer, const SDL_FRect * rects, int count)
Draw some number of rectangles on the current rendering target at subpixel precision.
Parameters
renderer the renderer which should draw multiple rectangles.
rects a pointer to an array of destination rectangles.
count the number of rectangles.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderRect
{
    int i;
    CHECK_RENDERER_MAGIC(renderer, false);
    if (!rects) {
        return SDL_InvalidParamError("SDL_RenderRects(): rects");
    }
    if (count < 1) {
        return true;
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    for (i = 0; i < count; ++i) {
        if (!SDL_RenderRect(renderer, &rects[i])) {
            return false;
        }
    }
    return true;
}
References CHECK_RENDERER_MAGIC, count, SDL_Renderer::hidden, SDL_InvalidParamError, and SDL_RenderRect().
SDL_RenderTexture()
bool SDL_RenderTexture (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FRect * dstrect)
Copy a portion of the texture to the current rendering target at subpixel precision.
Parameters
renderer the renderer which should copy parts of a texture.
texture the source texture.
srcrect a pointer to the source rectangle, or NULL for the entire texture.
dstrect a pointer to the destination rectangle, or NULL for the entire rendering target.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderTextureRotated
SDL_RenderTextureTiled
{
    CHECK_RENDERER_MAGIC(renderer, false);
    CHECK_TEXTURE_MAGIC(texture, false);
    if (renderer != texture->renderer) {
        return SDL_SetError("Texture was not created with this renderer");
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    SDL_FRect real_srcrect;
    real_srcrect.x = 0.0f;
    real_srcrect.y = 0.0f;
    real_srcrect.w = (float)texture->w;
    real_srcrect.h = (float)texture->h;
    if (srcrect) {
        if (!SDL_GetRectIntersectionFloat(srcrect, &real_srcrect, &real_srcrect)) {
            return true;
        }
    }
    SDL_FRect full_dstrect;
    if (!dstrect) {
        GetRenderViewportSize(renderer, &full_dstrect);
        dstrect = &full_dstrect;
    }
    if (texture->native) {
        texture = texture->native;
    }
    texture->last_command_generation = renderer->render_command_generation;
    return SDL_RenderTextureInternal(renderer, texture, &real_srcrect, dstrect);
}
References CHECK_RENDERER_MAGIC, CHECK_TEXTURE_MAGIC, GetRenderViewportSize(), SDL_FRect::h, SDL_Texture::h, SDL_Renderer::hidden, SDL_Texture::last_command_generation, SDL_Texture::native, SDL_Renderer::render_command_generation, SDL_Texture::renderer, SDL_GetRectIntersectionFloat(), SDL_RenderTextureInternal(), SDL_SetError(), SDL_FRect::w, SDL_Texture::w, SDL_FRect::x, and SDL_FRect::y.
Referenced by DrawDebugCharacter(), SDL_RenderApplyWindowShape(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), SDL_RenderTextureRotated(), and SDL_UpdateWindowTexture().
SDL_RenderTexture9Grid()
bool SDL_RenderTexture9Grid (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float left_width, float right_width, float top_height, float bottom_height, float scale, const SDL_FRect * dstrect)
Perform a scaled copy using the 9-grid algorithm to the current rendering target at subpixel precision.
The pixels in the texture are split into a 3x3 grid, using the different corner sizes for each corner, and the sides and center making up the remaining pixels. The corners are then scaled using scale and fit into the corners of the destination rectangle. The sides and center are then stretched into place to cover the remaining destination rectangle.
Parameters
renderer the renderer which should copy parts of a texture.
texture the source texture.
srcrect the SDL_Rect structure representing the rectangle to be used for the 9-grid, or NULL to use the entire texture.
left_width the width, in pixels, of the left corners in srcrect.
right_width the width, in pixels, of the right corners in srcrect.
top_height the height, in pixels, of the top corners in srcrect.
bottom_height the height, in pixels, of the bottom corners in srcrect.
scale the scale used to transform the corner of srcrect into the corner of dstrect, or 0.0f for an unscaled copy.
dstrect a pointer to the destination rectangle, or NULL for the entire rendering target.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderTexture
{
    SDL_FRect full_src, full_dst;
    SDL_FRect curr_src, curr_dst;
    float dst_left_width;
    float dst_right_width;
    float dst_top_height;
    float dst_bottom_height;
    CHECK_RENDERER_MAGIC(renderer, false);
    CHECK_TEXTURE_MAGIC(texture, false);
    if (renderer != texture->renderer) {
        return SDL_SetError("Texture was not created with this renderer");
    }
    if (!srcrect) {
        full_src.x = 0;
        full_src.y = 0;
        full_src.w = (float)texture->w;
        full_src.h = (float)texture->h;
        srcrect = &full_src;
    }
    if (!dstrect) {
        GetRenderViewportSize(renderer, &full_dst);
        dstrect = &full_dst;
    }
    if (scale <= 0.0f || scale == 1.0f) {
        dst_left_width = SDL_ceilf(left_width);
        dst_right_width = SDL_ceilf(right_width);
        dst_top_height = SDL_ceilf(top_height);
        dst_bottom_height = SDL_ceilf(bottom_height);
    } else {
        dst_left_width = SDL_ceilf(left_width * scale);
        dst_right_width = SDL_ceilf(right_width * scale);
        dst_top_height = SDL_ceilf(top_height * scale);
        dst_bottom_height = SDL_ceilf(bottom_height * scale);
    }
    // Center
    curr_src.x = srcrect->x + left_width;
    curr_src.y = srcrect->y + top_height;
    curr_src.w = srcrect->w - left_width - right_width;
    curr_src.h = srcrect->h - top_height - bottom_height;
    curr_dst.x = dstrect->x + dst_left_width;
    curr_dst.y = dstrect->y + dst_top_height;
    curr_dst.w = dstrect->w - dst_left_width - dst_right_width;
    curr_dst.h = dstrect->h - dst_top_height - dst_bottom_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Upper-left corner
    curr_src.x = srcrect->x;
    curr_src.y = srcrect->y;
    curr_src.w = left_width;
    curr_src.h = top_height;
    curr_dst.x = dstrect->x;
    curr_dst.y = dstrect->y;
    curr_dst.w = dst_left_width;
    curr_dst.h = dst_top_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Upper-right corner
    curr_src.x = srcrect->x + srcrect->w - right_width;
    curr_src.w = right_width;
    curr_dst.x = dstrect->x + dstrect->w - dst_right_width;
    curr_dst.w = dst_right_width;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Lower-right corner
    curr_src.y = srcrect->y + srcrect->h - bottom_height;
    curr_src.h = bottom_height;
    curr_dst.y = dstrect->y + dstrect->h - dst_bottom_height;
    curr_dst.h = dst_bottom_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Lower-left corner
    curr_src.x = srcrect->x;
    curr_src.w = left_width;
    curr_dst.x = dstrect->x;
    curr_dst.w = dst_left_width;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Left
    curr_src.y = srcrect->y + top_height;
    curr_src.h = srcrect->h - top_height - bottom_height;
    curr_dst.y = dstrect->y + dst_top_height;
    curr_dst.h = dstrect->h - dst_top_height - dst_bottom_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Right
    curr_src.x = srcrect->x + srcrect->w - right_width;
    curr_src.w = right_width;
    curr_dst.x = dstrect->x + dstrect->w - dst_right_width;
    curr_dst.w = dst_right_width;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Top
    curr_src.x = srcrect->x + left_width;
    curr_src.y = srcrect->y;
    curr_src.w = srcrect->w - left_width - right_width;
    curr_src.h = top_height;
    curr_dst.x = dstrect->x + dst_left_width;
    curr_dst.y = dstrect->y;
    curr_dst.w = dstrect->w - dst_left_width - dst_right_width;
    curr_dst.h = dst_top_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Bottom
    curr_src.y = srcrect->y + srcrect->h - bottom_height;
    curr_src.h = bottom_height;
    curr_dst.y = dstrect->y + dstrect->h - dst_bottom_height;
    curr_dst.h = dst_bottom_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, CHECK_TEXTURE_MAGIC, GetRenderViewportSize(), SDL_FRect::h, SDL_Texture::h, SDL_Texture::renderer, SDL_ceilf(), SDL_RenderTexture(), SDL_SetError(), SDL_FRect::w, SDL_Texture::w, SDL_FRect::x, and SDL_FRect::y.
SDL_RenderTexture9GridTiled()
bool SDL_RenderTexture9GridTiled (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float left_width, float right_width, float top_height, float bottom_height, float scale, const SDL_FRect * dstrect, float tileScale)
Perform a scaled copy using the 9-grid algorithm to the current rendering target at subpixel precision.
The pixels in the texture are split into a 3x3 grid, using the different corner sizes for each corner, and the sides and center making up the remaining pixels. The corners are then scaled using scale and fit into the corners of the destination rectangle. The sides and center are then tiled into place to cover the remaining destination rectangle.
Parameters
renderer the renderer which should copy parts of a texture.
texture the source texture.
srcrect the SDL_Rect structure representing the rectangle to be used for the 9-grid, or NULL to use the entire texture.
left_width the width, in pixels, of the left corners in srcrect.
right_width the width, in pixels, of the right corners in srcrect.
top_height the height, in pixels, of the top corners in srcrect.
bottom_height the height, in pixels, of the bottom corners in srcrect.
scale the scale used to transform the corner of srcrect into the corner of dstrect, or 0.0f for an unscaled copy.
dstrect a pointer to the destination rectangle, or NULL for the entire rendering target.
tileScale the scale used to transform the borders and center of srcrect into the borders and middle of dstrect, or 1.0f for an unscaled copy.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_RenderTexture
{
    SDL_FRect full_src, full_dst;
    SDL_FRect curr_src, curr_dst;
    float dst_left_width;
    float dst_right_width;
    float dst_top_height;
    float dst_bottom_height;
    CHECK_RENDERER_MAGIC(renderer, false);
    CHECK_TEXTURE_MAGIC(texture, false);
    if (renderer != texture->renderer) {
        return SDL_SetError("Texture was not created with this renderer");
    }
    if (!srcrect) {
        full_src.x = 0;
        full_src.y = 0;
        full_src.w = (float)texture->w;
        full_src.h = (float)texture->h;
        srcrect = &full_src;
    }
    if (!dstrect) {
        GetRenderViewportSize(renderer, &full_dst);
        dstrect = &full_dst;
    }
    if (scale <= 0.0f || scale == 1.0f) {
        dst_left_width = SDL_ceilf(left_width);
        dst_right_width = SDL_ceilf(right_width);
        dst_top_height = SDL_ceilf(top_height);
        dst_bottom_height = SDL_ceilf(bottom_height);
    } else {
        dst_left_width = SDL_ceilf(left_width * scale);
        dst_right_width = SDL_ceilf(right_width * scale);
        dst_top_height = SDL_ceilf(top_height * scale);
        dst_bottom_height = SDL_ceilf(bottom_height * scale);
    }
    // Center
    curr_src.x = srcrect->x + left_width;
    curr_src.y = srcrect->y + top_height;
    curr_src.w = srcrect->w - left_width - right_width;
    curr_src.h = srcrect->h - top_height - bottom_height;
    curr_dst.x = dstrect->x + dst_left_width;
    curr_dst.y = dstrect->y + dst_top_height;
    curr_dst.w = dstrect->w - dst_left_width - dst_right_width;
    curr_dst.h = dstrect->h - dst_top_height - dst_bottom_height;
    if (!SDL_RenderTextureTiled(renderer, texture, &curr_src, tileScale, &curr_dst)) {
        return false;
    }
    // Upper-left corner
    curr_src.x = srcrect->x;
    curr_src.y = srcrect->y;
    curr_src.w = left_width;
    curr_src.h = top_height;
    curr_dst.x = dstrect->x;
    curr_dst.y = dstrect->y;
    curr_dst.w = dst_left_width;
    curr_dst.h = dst_top_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Upper-right corner
    curr_src.x = srcrect->x + srcrect->w - right_width;
    curr_src.w = right_width;
    curr_dst.x = dstrect->x + dstrect->w - dst_right_width;
    curr_dst.w = dst_right_width;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Lower-right corner
    curr_src.y = srcrect->y + srcrect->h - bottom_height;
    curr_src.h = bottom_height;
    curr_dst.y = dstrect->y + dstrect->h - dst_bottom_height;
    curr_dst.h = dst_bottom_height;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Lower-left corner
    curr_src.x = srcrect->x;
    curr_src.w = left_width;
    curr_dst.x = dstrect->x;
    curr_dst.w = dst_left_width;
    if (!SDL_RenderTexture(renderer, texture, &curr_src, &curr_dst)) {
        return false;
    }
    // Left
    curr_src.y = srcrect->y + top_height;
    curr_src.h = srcrect->h - top_height - bottom_height;
    curr_dst.y = dstrect->y + dst_top_height;
    curr_dst.h = dstrect->h - dst_top_height - dst_bottom_height;
    if (!SDL_RenderTextureTiled(renderer, texture, &curr_src, tileScale, &curr_dst)) {
        return false;
    }
    // Right
    curr_src.x = srcrect->x + srcrect->w - right_width;
    curr_src.w = right_width;
    curr_dst.x = dstrect->x + dstrect->w - dst_right_width;
    curr_dst.w = dst_right_width;
    if (!SDL_RenderTextureTiled(renderer, texture, &curr_src, tileScale, &curr_dst)) {
        return false;
    }
    // Top
    curr_src.x = srcrect->x + left_width;
    curr_src.y = srcrect->y;
    curr_src.w = srcrect->w - left_width - right_width;
    curr_src.h = top_height;
    curr_dst.x = dstrect->x + dst_left_width;
    curr_dst.y = dstrect->y;
    curr_dst.w = dstrect->w - dst_left_width - dst_right_width;
    curr_dst.h = dst_top_height;
    if (!SDL_RenderTextureTiled(renderer, texture, &curr_src, tileScale, &curr_dst)) {
        return false;
    }
    // Bottom
    curr_src.y = srcrect->y + srcrect->h - bottom_height;
    curr_src.h = bottom_height;
    curr_dst.y = dstrect->y + dstrect->h - dst_bottom_height;
    curr_dst.h = dst_bottom_height;
    if (!SDL_RenderTextureTiled(renderer, texture, &curr_src, tileScale, &curr_dst)) {
        return false;
    }
    return true;
}
References CHECK_RENDERER_MAGIC, CHECK_TEXTURE_MAGIC, GetRenderViewportSize(), SDL_FRect::h, SDL_Texture::h, SDL_Texture::renderer, SDL_ceilf(), SDL_RenderTexture(), SDL_RenderTextureTiled(), SDL_SetError(), SDL_FRect::w, SDL_Texture::w, SDL_FRect::x, and SDL_FRect::y.
SDL_RenderTextureAffine()
bool SDL_RenderTextureAffine (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FPoint * origin, const SDL_FPoint * right, const SDL_FPoint * down)
Copy a portion of the source texture to the current rendering target, with affine transform, at subpixel precision.
Parameters
renderer the renderer which should copy parts of a texture.
texture the source texture.
srcrect a pointer to the source rectangle, or NULL for the entire texture.
origin a pointer to a point indicating where the top-left corner of srcrect should be mapped to, or NULL for the rendering target's origin.
right a pointer to a point indicating where the top-right corner of srcrect should be mapped to, or NULL for the rendering target's top-right corner.
down a pointer to a point indicating where the bottom-left corner of srcrect should be mapped to, or NULL for the rendering target's bottom-left corner.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
You may only call this function from the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderTexture
{
    SDL_FRect real_srcrect;
    SDL_FRect real_dstrect;
    bool result;
    CHECK_RENDERER_MAGIC(renderer, false);
    CHECK_TEXTURE_MAGIC(texture, false);
    if (renderer != texture->renderer) {
        return SDL_SetError("Texture was not created with this renderer");
    }
    if (!renderer->QueueCopyEx && !renderer->QueueGeometry) {
        return SDL_SetError("Renderer does not support RenderCopyEx");
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    real_srcrect.x = 0.0f;
    real_srcrect.y = 0.0f;
    real_srcrect.w = (float)texture->w;
    real_srcrect.h = (float)texture->h;
    if (srcrect) {
        if (!SDL_GetRectIntersectionFloat(srcrect, &real_srcrect, &real_srcrect)) {
            return true;
        }
    }
    GetRenderViewportSize(renderer, &real_dstrect);
    if (texture->native) {
        texture = texture->native;
    }
    texture->last_command_generation = renderer->render_command_generation;
    const SDL_RenderViewState *view = renderer->view;
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    {
        float xy[8];
        const int xy_stride = 2 * sizeof(float);
        float uv[8];
        const int uv_stride = 2 * sizeof(float);
        const int num_vertices = 4;
        const int *indices = rect_index_order;
        const int num_indices = 6;
        const int size_indices = 4;
        float minu = real_srcrect.x / texture->w;
        float minv = real_srcrect.y / texture->h;
        float maxu = (real_srcrect.x + real_srcrect.w) / texture->w;
        float maxv = (real_srcrect.y + real_srcrect.h) / texture->h;
        uv[0] = minu;
        uv[1] = minv;
        uv[2] = maxu;
        uv[3] = minv;
        uv[4] = maxu;
        uv[5] = maxv;
        uv[6] = minu;
        uv[7] = maxv;
        // (minx, miny)
        if (origin) {
            xy[0] = origin->x;
            xy[1] = origin->y;
        } else {
            xy[0] = real_dstrect.x;
            xy[1] = real_dstrect.y;
        }
        // (maxx, miny)
        if (right) {
            xy[2] = right->x;
            xy[3] = right->y;
        } else {
            xy[2] = real_dstrect.x + real_dstrect.w;
            xy[3] = real_dstrect.y;
        }
        // (minx, maxy)
        if (down) {
            xy[6] = down->x;
            xy[7] = down->y;
        } else {
            xy[6] = real_dstrect.x;
            xy[7] = real_dstrect.y + real_dstrect.h;
        }
        // (maxx, maxy)
        if (origin || right || down) {
            xy[4] = xy[2] + xy[6] - xy[0];
            xy[5] = xy[3] + xy[7] - xy[1];
        } else {
            xy[4] = real_dstrect.x + real_dstrect.w;
            xy[5] = real_dstrect.y + real_dstrect.h;
        }
        result = QueueCmdGeometry(
            renderer, texture,
            xy, xy_stride,
            &texture->color, 0 /* color_stride */,
            uv, uv_stride,
            num_vertices, indices, num_indices, size_indices,
            scale_x, scale_y, SDL_TEXTURE_ADDRESS_CLAMP, SDL_TEXTURE_ADDRESS_CLAMP
        );
    }
    return result;
}
References CHECK_RENDERER_MAGIC, CHECK_TEXTURE_MAGIC, SDL_Texture::color, SDL_RenderViewState::current_scale, GetRenderViewportSize(), SDL_FRect::h, SDL_Texture::h, SDL_Renderer::hidden, SDL_Texture::last_command_generation, SDL_Texture::native, QueueCmdGeometry(), SDL_Renderer::QueueCopyEx, SDL_Renderer::QueueGeometry, rect_index_order, SDL_Renderer::render_command_generation, SDL_Texture::renderer, right, SDL_GetRectIntersectionFloat(), SDL_SetError(), SDL_TEXTURE_ADDRESS_CLAMP, SDL_Renderer::view, SDL_FRect::w, SDL_Texture::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
SDL_RenderTextureInternal()
bool SDL_RenderTextureInternal (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FRect * dstrect) static
{
    const SDL_RenderViewState *view = renderer->view;
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    const bool use_rendergeometry = (!renderer->QueueCopy);
    bool result;
    if (use_rendergeometry) {
        float xy[8];
        const int xy_stride = 2 * sizeof(float);
        float uv[8];
        const int uv_stride = 2 * sizeof(float);
        const int num_vertices = 4;
        const int *indices = rect_index_order;
        const int num_indices = 6;
        const int size_indices = 4;
        float minu, minv, maxu, maxv;
        float minx, miny, maxx, maxy;
        minu = srcrect->x / texture->w;
        minv = srcrect->y / texture->h;
        maxu = (srcrect->x + srcrect->w) / texture->w;
        maxv = (srcrect->y + srcrect->h) / texture->h;
        minx = dstrect->x;
        miny = dstrect->y;
        maxx = dstrect->x + dstrect->w;
        maxy = dstrect->y + dstrect->h;
        uv[0] = minu;
        uv[1] = minv;
        uv[2] = maxu;
        uv[3] = minv;
        uv[4] = maxu;
        uv[5] = maxv;
        uv[6] = minu;
        uv[7] = maxv;
        xy[0] = minx;
        xy[1] = miny;
        xy[2] = maxx;
        xy[3] = miny;
        xy[4] = maxx;
        xy[5] = maxy;
        xy[6] = minx;
        xy[7] = maxy;
        result = QueueCmdGeometry(renderer, texture,
                                  xy, xy_stride, &texture->color, 0 /* color_stride */, uv, uv_stride,
                                  num_vertices, indices, num_indices, size_indices,
                                  scale_x, scale_y, SDL_TEXTURE_ADDRESS_CLAMP, SDL_TEXTURE_ADDRESS_CLAMP);
    } else {
        const SDL_FRect rect = { dstrect->x * scale_x, dstrect->y * scale_y, dstrect->w * scale_x, dstrect->h * scale_y };
        result = QueueCmdCopy(renderer, texture, srcrect, &rect);
    }
    return result;
}
References SDL_Texture::color, SDL_RenderViewState::current_scale, SDL_FRect::h, SDL_Texture::h, QueueCmdCopy(), QueueCmdGeometry(), SDL_Renderer::QueueCopy, rect_index_order, SDL_TEXTURE_ADDRESS_CLAMP, SDL_Renderer::view, SDL_FRect::w, SDL_Texture::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by SDL_RenderTexture(), and SDL_RenderTextureTiled_Iterate().
SDL_RenderTextureRotated()
bool SDL_RenderTextureRotated (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, const SDL_FRect * dstrect, double angle, const SDL_FPoint * center, SDL_FlipMode flip)
Copy a portion of the source texture to the current rendering target, with rotation and flipping, at subpixel precision.
Parameters
renderer the renderer which should copy parts of a texture.
texture the source texture.
srcrect a pointer to the source rectangle, or NULL for the entire texture.
dstrect a pointer to the destination rectangle, or NULL for the entire rendering target.
angle an angle in degrees that indicates the rotation that will be applied to dstrect, rotating it in a clockwise direction.
center a pointer to a point indicating the point around which dstrect will be rotated (if NULL, rotation will be done around dstrect.w/2, dstrect.h/2).
flip an SDL_FlipMode value stating which flipping actions should be performed on the texture.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderTexture
{
    SDL_FRect real_srcrect;
    SDL_FPoint real_center;
    bool result;
    if (flip == SDL_FLIP_NONE && (int)(angle / 360) == angle / 360) { // fast path when we don't need rotation or flipping
        return SDL_RenderTexture(renderer, texture, srcrect, dstrect);
    }
    CHECK_RENDERER_MAGIC(renderer, false);
    CHECK_TEXTURE_MAGIC(texture, false);
    if (renderer != texture->renderer) {
        return SDL_SetError("Texture was not created with this renderer");
    }
    if (!renderer->QueueCopyEx && !renderer->QueueGeometry) {
        return SDL_SetError("Renderer does not support RenderCopyEx");
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    real_srcrect.x = 0.0f;
    real_srcrect.y = 0.0f;
    real_srcrect.w = (float)texture->w;
    real_srcrect.h = (float)texture->h;
    if (srcrect) {
        if (!SDL_GetRectIntersectionFloat(srcrect, &real_srcrect, &real_srcrect)) {
            return true;
        }
    }
    // We don't intersect the dstrect with the viewport as RenderCopy does because of potential rotation clipping issues... TODO: should we?
    SDL_FRect full_dstrect;
    if (!dstrect) {
        GetRenderViewportSize(renderer, &full_dstrect);
        dstrect = &full_dstrect;
    }
    if (texture->native) {
        texture = texture->native;
    }
    if (center) {
        real_center = *center;
    } else {
        real_center.x = dstrect->w / 2.0f;
        real_center.y = dstrect->h / 2.0f;
    }
    texture->last_command_generation = renderer->render_command_generation;
    const SDL_RenderViewState *view = renderer->view;
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    const bool use_rendergeometry = (!renderer->QueueCopyEx);
    if (use_rendergeometry) {
        float xy[8];
        const int xy_stride = 2 * sizeof(float);
        float uv[8];
        const int uv_stride = 2 * sizeof(float);
        const int num_vertices = 4;
        const int *indices = rect_index_order;
        const int num_indices = 6;
        const int size_indices = 4;
        float minu, minv, maxu, maxv;
        float minx, miny, maxx, maxy;
        float centerx, centery;
        float s_minx, s_miny, s_maxx, s_maxy;
        float c_minx, c_miny, c_maxx, c_maxy;
        const float radian_angle = (float)((SDL_PI_D * angle) / 180.0);
        const float s = SDL_sinf(radian_angle);
        const float c = SDL_cosf(radian_angle);
        minu = real_srcrect.x / texture->w;
        minv = real_srcrect.y / texture->h;
        maxu = (real_srcrect.x + real_srcrect.w) / texture->w;
        maxv = (real_srcrect.y + real_srcrect.h) / texture->h;
        centerx = real_center.x + dstrect->x;
        centery = real_center.y + dstrect->y;
        if (flip & SDL_FLIP_HORIZONTAL) {
            minx = dstrect->x + dstrect->w;
            maxx = dstrect->x;
        } else {
            minx = dstrect->x;
            maxx = dstrect->x + dstrect->w;
        }
        if (flip & SDL_FLIP_VERTICAL) {
            miny = dstrect->y + dstrect->h;
            maxy = dstrect->y;
        } else {
            miny = dstrect->y;
            maxy = dstrect->y + dstrect->h;
        }
        uv[0] = minu;
        uv[1] = minv;
        uv[2] = maxu;
        uv[3] = minv;
        uv[4] = maxu;
        uv[5] = maxv;
        uv[6] = minu;
        uv[7] = maxv;
        /* apply rotation with 2x2 matrix ( c -s )
         *                                ( s  c ) */
        s_minx = s * (minx - centerx);
        s_miny = s * (miny - centery);
        s_maxx = s * (maxx - centerx);
        s_maxy = s * (maxy - centery);
        c_minx = c * (minx - centerx);
        c_miny = c * (miny - centery);
        c_maxx = c * (maxx - centerx);
        c_maxy = c * (maxy - centery);
        // (minx, miny)
        xy[0] = (c_minx - s_miny) + centerx;
        xy[1] = (s_minx + c_miny) + centery;
        // (maxx, miny)
        xy[2] = (c_maxx - s_miny) + centerx;
        xy[3] = (s_maxx + c_miny) + centery;
        // (maxx, maxy)
        xy[4] = (c_maxx - s_maxy) + centerx;
        xy[5] = (s_maxx + c_maxy) + centery;
        // (minx, maxy)
        xy[6] = (c_minx - s_maxy) + centerx;
        xy[7] = (s_minx + c_maxy) + centery;
        result = QueueCmdGeometry(renderer, texture,
                                  xy, xy_stride, &texture->color, 0 /* color_stride */, uv, uv_stride,
                                  num_vertices, indices, num_indices, size_indices,
                                  scale_x, scale_y, SDL_TEXTURE_ADDRESS_CLAMP, SDL_TEXTURE_ADDRESS_CLAMP);
    } else {
        result = QueueCmdCopyEx(renderer, texture, &real_srcrect, dstrect, angle, &real_center, flip, scale_x, scale_y);
    }
    return result;
}
References CHECK_RENDERER_MAGIC, CHECK_TEXTURE_MAGIC, SDL_Texture::color, SDL_RenderViewState::current_scale, GetRenderViewportSize(), SDL_FRect::h, SDL_Texture::h, SDL_Renderer::hidden, SDL_Texture::last_command_generation, SDL_Texture::native, QueueCmdCopyEx(), QueueCmdGeometry(), SDL_Renderer::QueueCopyEx, SDL_Renderer::QueueGeometry, rect_index_order, SDL_Renderer::render_command_generation, SDL_Texture::renderer, SDL_cosf(), SDL_FLIP_HORIZONTAL, SDL_FLIP_NONE, SDL_FLIP_VERTICAL, SDL_GetRectIntersectionFloat(), SDL_PI_D, SDL_RenderTexture(), SDL_SetError(), SDL_sinf(), SDL_TEXTURE_ADDRESS_CLAMP, SDL_Renderer::view, SDL_FRect::w, SDL_Texture::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
SDL_RenderTextureTiled()
bool SDL_RenderTextureTiled (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float scale, const SDL_FRect * dstrect)
Tile a portion of the texture to the current rendering target at subpixel precision.
The pixels in srcrect will be repeated as many times as needed to completely fill dstrect.
Parameters
renderer the renderer which should copy parts of a texture.
texture the source texture.
srcrect a pointer to the source rectangle, or NULL for the entire texture.
scale the scale used to transform srcrect into the destination rectangle, e.g. a 32x32 texture with a scale of 2 would fill 64x64 tiles.
dstrect a pointer to the destination rectangle, or NULL for the entire rendering target.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_RenderTexture
{
    SDL_FRect real_srcrect;
    CHECK_RENDERER_MAGIC(renderer, false);
    CHECK_TEXTURE_MAGIC(texture, false);
    if (renderer != texture->renderer) {
        return SDL_SetError("Texture was not created with this renderer");
    }
    if (scale <= 0.0f) {
        return SDL_InvalidParamError("scale");
    }
#if DONT_DRAW_WHILE_HIDDEN
    // Don't draw while we're hidden
    if (renderer->hidden) {
        return true;
    }
#endif
    real_srcrect.x = 0.0f;
    real_srcrect.y = 0.0f;
    real_srcrect.w = (float)texture->w;
    real_srcrect.h = (float)texture->h;
    if (srcrect) {
        if (!SDL_GetRectIntersectionFloat(srcrect, &real_srcrect, &real_srcrect)) {
            return true;
        }
    }
    SDL_FRect full_dstrect;
    if (!dstrect) {
        GetRenderViewportSize(renderer, &full_dstrect);
        dstrect = &full_dstrect;
    }
    if (texture->native) {
        texture = texture->native;
    }
    texture->last_command_generation = renderer->render_command_generation;
    // See if we can use geometry with repeating texture coordinates
    if (!renderer->software &&
        (!srcrect ||
         (real_srcrect.x == 0.0f && real_srcrect.y == 0.0f &&
          real_srcrect.w == (float)texture->w && real_srcrect.h == (float)texture->h))) {
        return SDL_RenderTextureTiled_Wrap(renderer, texture, &real_srcrect, scale, dstrect);
    } else {
        return SDL_RenderTextureTiled_Iterate(renderer, texture, &real_srcrect, scale, dstrect);
    }
}
References CHECK_RENDERER_MAGIC, CHECK_TEXTURE_MAGIC, GetRenderViewportSize(), SDL_FRect::h, SDL_Texture::h, SDL_Renderer::hidden, SDL_Texture::last_command_generation, SDL_Texture::native, SDL_Renderer::render_command_generation, SDL_Texture::renderer, SDL_GetRectIntersectionFloat(), SDL_InvalidParamError, SDL_RenderTextureTiled_Iterate(), SDL_RenderTextureTiled_Wrap(), SDL_SetError(), SDL_Renderer::software, SDL_FRect::w, SDL_Texture::w, SDL_FRect::x, and SDL_FRect::y.
Referenced by SDL_RenderTexture9GridTiled().
SDL_RenderTextureTiled_Iterate()
bool SDL_RenderTextureTiled_Iterate (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float scale, const SDL_FRect * dstrect) static
{
    float tile_width = srcrect->w * scale;
    float tile_height = srcrect->h * scale;
    float float_rows, float_cols;
    float remaining_w = SDL_modff(dstrect->w / tile_width, &float_cols);
    float remaining_h = SDL_modff(dstrect->h / tile_height, &float_rows);
    float remaining_src_w = remaining_w * srcrect->w;
    float remaining_src_h = remaining_h * srcrect->h;
    float remaining_dst_w = remaining_w * tile_width;
    float remaining_dst_h = remaining_h * tile_height;
    int rows = (int)float_rows;
    int cols = (int)float_cols;
    SDL_FRect curr_src, curr_dst;
    SDL_copyp(&curr_src, srcrect);
    curr_dst.y = dstrect->y;
    curr_dst.w = tile_width;
    curr_dst.h = tile_height;
    for (int y = 0; y < rows; ++y) {
        curr_dst.x = dstrect->x;
        for (int x = 0; x < cols; ++x) {
            if (!SDL_RenderTextureInternal(renderer, texture, &curr_src, &curr_dst)) {
                return false;
            }
            curr_dst.x += curr_dst.w;
        }
        if (remaining_dst_w > 0.0f) {
            curr_src.w = remaining_src_w;
            curr_dst.w = remaining_dst_w;
            if (!SDL_RenderTextureInternal(renderer, texture, &curr_src, &curr_dst)) {
                return false;
            }
            curr_src.w = srcrect->w;
            curr_dst.w = tile_width;
        }
        curr_dst.y += curr_dst.h;
    }
    if (remaining_dst_h > 0.0f) {
        curr_src.h = remaining_src_h;
        curr_dst.h = remaining_dst_h;
        curr_dst.x = dstrect->x;
        for (int x = 0; x < cols; ++x) {
            if (!SDL_RenderTextureInternal(renderer, texture, &curr_src, &curr_dst)) {
                return false;
            }
            curr_dst.x += curr_dst.w;
        }
        if (remaining_dst_w > 0.0f) {
            curr_src.w = remaining_src_w;
            curr_dst.w = remaining_dst_w;
            if (!SDL_RenderTextureInternal(renderer, texture, &curr_src, &curr_dst)) {
                return false;
            }
        }
    }
    return true;
}
References SDL_FRect::h, SDL_copyp, SDL_modff(), SDL_RenderTextureInternal(), SDL_FRect::w, SDL_FRect::x, and SDL_FRect::y.
Referenced by SDL_RenderTextureTiled().
SDL_RenderTextureTiled_Wrap()
bool SDL_RenderTextureTiled_Wrap (SDL_Renderer * renderer, SDL_Texture * texture, const SDL_FRect * srcrect, float scale, const SDL_FRect * dstrect) static
{
    float xy[8];
    const int xy_stride = 2 * sizeof(float);
    float uv[8];
    const int uv_stride = 2 * sizeof(float);
    const int num_vertices = 4;
    const int *indices = rect_index_order;
    const int num_indices = 6;
    const int size_indices = 4;
    float minu, minv, maxu, maxv;
    float minx, miny, maxx, maxy;
    minu = 0.0f;
    minv = 0.0f;
    maxu = dstrect->w / (srcrect->w * scale);
    maxv = dstrect->h / (srcrect->h * scale);
    minx = dstrect->x;
    miny = dstrect->y;
    maxx = dstrect->x + dstrect->w;
    maxy = dstrect->y + dstrect->h;
    uv[0] = minu;
    uv[1] = minv;
    uv[2] = maxu;
    uv[3] = minv;
    uv[4] = maxu;
    uv[5] = maxv;
    uv[6] = minu;
    uv[7] = maxv;
    xy[0] = minx;
    xy[1] = miny;
    xy[2] = maxx;
    xy[3] = miny;
    xy[4] = maxx;
    xy[5] = maxy;
    xy[6] = minx;
    xy[7] = maxy;
    const SDL_RenderViewState *view = renderer->view;
    return QueueCmdGeometry(renderer, texture,
                            xy, xy_stride, &texture->color, 0 /* color_stride */, uv, uv_stride,
                            num_vertices, indices, num_indices, size_indices,
                            view->current_scale.x, view->current_scale.y,
                            SDL_TEXTURE_ADDRESS_WRAP, SDL_TEXTURE_ADDRESS_WRAP);
}
References SDL_Texture::color, SDL_RenderViewState::current_scale, SDL_FRect::h, QueueCmdGeometry(), rect_index_order, SDL_TEXTURE_ADDRESS_WRAP, SDL_Renderer::view, SDL_FRect::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by SDL_RenderTextureTiled().
SDL_RenderVectorFromWindow()
bool SDL_RenderVectorFromWindow (SDL_Renderer * renderer, float window_dx, float window_dy, float * dx, float * dy) static
{
    // Convert from window coordinates to pixels within the window
    window_dx *= renderer->dpi_scale.x;
    window_dy *= renderer->dpi_scale.y;
    // Convert from pixels within the window to pixels within the view
    const SDL_RenderViewState *view = &renderer->main_view;
    if (view->logical_presentation_mode != SDL_LOGICAL_PRESENTATION_DISABLED) {
        const SDL_FRect *src = &view->logical_src_rect;
        const SDL_FRect *dst = &view->logical_dst_rect;
        window_dx = (window_dx * src->w) / dst->w;
        window_dy = (window_dy * src->h) / dst->h;
    }
    window_dx /= view->scale.x;
    window_dy /= view->scale.y;
    *dx = window_dx;
    *dy = window_dy;
    return true;
}
References SDL_Renderer::dpi_scale, SDL_FRect::h, SDL_RenderViewState::logical_dst_rect, SDL_RenderViewState::logical_presentation_mode, SDL_RenderViewState::logical_src_rect, SDL_Renderer::main_view, SDL_RenderViewState::scale, SDL_LOGICAL_PRESENTATION_DISABLED, SDL_FRect::w, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_ConvertEventToRenderCoordinates().
SDL_RenderViewportSet()
bool SDL_RenderViewportSet (SDL_Renderer * renderer)
Return whether an explicit rectangle was set as the viewport.
This is useful if you're saving and restoring the viewport and want to know whether you should restore a specific rectangle or NULL.
Each render target has its own viewport. This function checks the viewport for the current render target.
Parameters
renderer the rendering context.
Returns
true if the viewport was set to a specific rectangle, or false if it was set to NULL (the entire target).
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderViewport
SDL_SetRenderViewport
{
    CHECK_RENDERER_MAGIC(renderer, false);
    const SDL_RenderViewState *view = renderer->view;
    return (view->viewport.w >= 0 && view->viewport.h >= 0);
}
References CHECK_RENDERER_MAGIC, SDL_Rect::h, SDL_Renderer::view, SDL_RenderViewState::viewport, and SDL_Rect::w.
SDL_SetDefaultTextureScaleMode()
bool SDL_SetDefaultTextureScaleMode (SDL_Renderer * renderer, SDL_ScaleMode scale_mode)
Set default scale mode for new textures for given renderer.
When a renderer is created, scale_mode defaults to SDL_SCALEMODE_LINEAR.
Parameters
renderer the renderer to update.
scale_mode the scale mode to change to for new textures.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.4.0.
See also
SDL_GetDefaultTextureScaleMode
{
    CHECK_RENDERER_MAGIC(renderer, false);
    renderer->scale_mode = scale_mode;
    return true;
}
References CHECK_RENDERER_MAGIC, and SDL_Renderer::scale_mode.
SDL_SetGPURenderStateFragmentUniforms()
bool SDL_SetGPURenderStateFragmentUniforms (SDL_GPURenderState * state, Uint32 slot_index, const void * data, Uint32 length)
Set fragment shader uniform variables in a custom GPU render state.
The data is copied and will be pushed using SDL_PushGPUFragmentUniformData() during draw call execution.
Parameters
state the state to modify.
slot_index the fragment uniform slot to push data to.
data client data to write.
length the length of the data to write.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should be called on the thread that created the renderer.
Since
This function is available since SDL 3.4.0.
{
    if (!state) {
        return SDL_InvalidParamError("state");
    }
    if (!FlushRenderCommandsIfGPURenderStateNeeded(state)) {
        return false;
    }
    for (int i = 0; i < state->num_uniform_buffers; i++) {
        SDL_GPURenderStateUniformBuffer *buffer = &state->uniform_buffers[i];
        if (buffer->slot_index == slot_index) {
            void *new_data = SDL_realloc(buffer->data, length);
            if (!new_data) {
                return false;
            }
            SDL_memcpy(new_data, data, length);
            buffer->data = new_data;
            buffer->length = length;
            return true;
        }
    }
    SDL_GPURenderStateUniformBuffer *buffers = (SDL_GPURenderStateUniformBuffer *)SDL_realloc(state->uniform_buffers, (state->num_uniform_buffers + 1) * sizeof(*state->uniform_buffers));
    if (!buffers) {
        return false;
    }
    SDL_GPURenderStateUniformBuffer *buffer = &buffers[state->num_uniform_buffers];
    buffer->slot_index = slot_index;
    buffer->length = length;
    buffer->data = SDL_malloc(length);
    if (!buffer->data) {
        SDL_free(buffers);
        return false;
    }
    SDL_memcpy(buffer->data, data, length);
    state->uniform_buffers = buffers;
    ++state->num_uniform_buffers;
    return true;
}
References FlushRenderCommandsIfGPURenderStateNeeded(), SDL_GPURenderState::num_uniform_buffers, SDL_free(), SDL_InvalidParamError, SDL_malloc(), SDL_memcpy, SDL_realloc(), and SDL_GPURenderState::uniform_buffers.
SDL_SetRenderClipRect()
bool SDL_SetRenderClipRect (SDL_Renderer * renderer, const SDL_Rect * rect)
Set the clip rectangle for rendering on the specified target.
Each render target has its own clip rectangle. This function sets the cliprect for the current render target.
Parameters
renderer the rendering context.
rect an SDL_Rect structure representing the clip area, relative to the viewport, or NULL to disable clipping.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderClipRect
SDL_RenderClipEnabled
{
    CHECK_RENDERER_MAGIC(renderer, false)
    SDL_RenderViewState *view = renderer->view;
    if (rect && rect->w >= 0 && rect->h >= 0) {
        view->clipping_enabled = true;
        SDL_copyp(&view->clip_rect, rect);
    } else {
        view->clipping_enabled = false;
        SDL_zero(view->clip_rect);
    }
    UpdatePixelClipRect(renderer, view);
    return QueueCmdSetClipRect(renderer);
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::clip_rect, SDL_RenderViewState::clipping_enabled, SDL_Rect::h, QueueCmdSetClipRect(), SDL_copyp, SDL_zero, UpdatePixelClipRect(), SDL_Renderer::view, and SDL_Rect::w.
Referenced by SDL_RenderLogicalPresentation().
SDL_SetRenderColorScale()
bool SDL_SetRenderColorScale (SDL_Renderer * renderer, float scale)
Set the color scale used for render operations.
The color scale is an additional scale multiplied into the pixel color value while rendering. This can be used to adjust the brightness of colors during HDR rendering, or changing HDR video brightness when playing on an SDR display.
The color scale does not affect the alpha channel, only the color brightness.
Parameters
renderer the rendering context.
scale the color scale value.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderColorScale
{
    CHECK_RENDERER_MAGIC(renderer, false);
    renderer->desired_color_scale = scale;
    UpdateColorScale(renderer);
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::desired_color_scale, and UpdateColorScale().
SDL_SetRenderDrawBlendMode()
bool SDL_SetRenderDrawBlendMode (SDL_Renderer * renderer, SDL_BlendMode blendMode)
Set the blend mode used for drawing operations (Fill and Line).
If the blend mode is not supported, the closest supported mode is chosen.
Parameters
renderer the rendering context.
blendMode the SDL_BlendMode to use for blending.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderDrawBlendMode
{
    CHECK_RENDERER_MAGIC(renderer, false);
    if (blendMode == SDL_BLENDMODE_INVALID) {
        return SDL_InvalidParamError("blendMode");
    }
    if (blendMode == SDL_BLENDMODE_INVALID) {
        return SDL_InvalidParamError("blendMode");
    }
    if (!IsSupportedBlendMode(renderer, blendMode)) {
        return SDL_Unsupported();
    }
    renderer->blendMode = blendMode;
    return true;
}
References SDL_Renderer::blendMode, CHECK_RENDERER_MAGIC, IsSupportedBlendMode(), SDL_BLENDMODE_INVALID, SDL_InvalidParamError, and SDL_Unsupported.
Referenced by SDL_RenderLogicalBorders().
SDL_SetRenderDrawColor()
bool SDL_SetRenderDrawColor (SDL_Renderer * renderer, Uint8 r, Uint8 g, Uint8 b, Uint8 a)
Set the color used for drawing operations.
Set the color for drawing or filling rectangles, lines, and points, and for SDL_RenderClear().
Parameters
renderer the rendering context.
r the red value used to draw on the rendering target.
g the green value used to draw on the rendering target.
b the blue value used to draw on the rendering target.
a the alpha value used to draw on the rendering target; usually SDL_ALPHA_OPAQUE (255). Use SDL_SetRenderDrawBlendMode to specify how the alpha channel is used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderDrawColor
SDL_SetRenderDrawColorFloat
{
    const float fR = (float)r / 255.0f;
    const float fG = (float)g / 255.0f;
    const float fB = (float)b / 255.0f;
    const float fA = (float)a / 255.0f;
    return SDL_SetRenderDrawColorFloat(renderer, fR, fG, fB, fA);
}
References SDL_SetRenderDrawColorFloat().
SDL_SetRenderDrawColorFloat()
bool SDL_SetRenderDrawColorFloat (SDL_Renderer * renderer, float r, float g, float b, float a)
Set the color used for drawing operations (Rect, Line and Clear).
Set the color for drawing or filling rectangles, lines, and points, and for SDL_RenderClear().
Parameters
renderer the rendering context.
r the red value used to draw on the rendering target.
g the green value used to draw on the rendering target.
b the blue value used to draw on the rendering target.
a the alpha value used to draw on the rendering target. Use SDL_SetRenderDrawBlendMode to specify how the alpha channel is used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderDrawColorFloat
SDL_SetRenderDrawColor
{
    CHECK_RENDERER_MAGIC(renderer, false);
    renderer->color.r = r;
    renderer->color.g = g;
    renderer->color.b = b;
    renderer->color.a = a;
    return true;
}
References SDL_FColor::a, SDL_FColor::b, CHECK_RENDERER_MAGIC, SDL_Renderer::color, SDL_FColor::g, and SDL_FColor::r.
Referenced by SDL_RenderLogicalBorders(), and SDL_SetRenderDrawColor().
SDL_SetRenderGPUState()
bool SDL_SetRenderGPUState (SDL_Renderer * renderer, SDL_GPURenderState * state)
Set custom GPU render state.
This function sets custom GPU render state for subsequent draw calls. This allows using custom shaders with the GPU renderer.
Parameters
renderer the renderer to use.
state the state to to use, or NULL to clear custom GPU render state.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should be called on the thread that created the renderer.
Since
This function is available since SDL 3.4.0.
{
    CHECK_RENDERER_MAGIC(renderer, false);
    renderer->gpu_render_state = state;
    return true;
}
References CHECK_RENDERER_MAGIC, and SDL_Renderer::gpu_render_state.
SDL_SetRenderLogicalPresentation()
bool SDL_SetRenderLogicalPresentation (SDL_Renderer * renderer, int w, int h, SDL_RendererLogicalPresentation mode)
Set a device-independent resolution and presentation mode for rendering.
This function sets the width and height of the logical rendering output. The renderer will act as if the current render target is always the requested dimensions, scaling to the actual resolution as necessary.
This can be useful for games that expect a fixed size, but would like to scale the output to whatever is available, regardless of how a user resizes a window, or if the display is high DPI.
Logical presentation can be used with both render target textures and the renderer's window; the state is unique to each render target, and this function sets the state for the current render target. It might be useful to draw to a texture that matches the window dimensions with logical presentation enabled, and then draw that texture across the entire window with logical presentation disabled. Be careful not to render both with logical presentation enabled, however, as this could produce double-letterboxing, etc.
You can disable logical coordinates by setting the mode to SDL_LOGICAL_PRESENTATION_DISABLED, and in that case you get the full pixel resolution of the render target; it is safe to toggle logical presentation during the rendering of a frame: perhaps most of the rendering is done to specific dimensions but to make fonts look sharp, the app turns off logical presentation while drawing text, for example.
For the renderer's window, letterboxing is drawn into the framebuffer if logical presentation is enabled during SDL_RenderPresent; be sure to reenable it before presenting if you were toggling it, otherwise the letterbox areas might have artifacts from previous frames (or artifacts from external overlays, etc). Letterboxing is never drawn into texture render targets; be sure to call SDL_RenderClear() before drawing into the texture so the letterboxing areas are cleared, if appropriate.
You can convert coordinates in an event into rendering coordinates using SDL_ConvertEventToRenderCoordinates().
Parameters
renderer the rendering context.
w the width of the logical resolution.
h the height of the logical resolution.
mode the presentation mode used.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ConvertEventToRenderCoordinates
SDL_GetRenderLogicalPresentation
SDL_GetRenderLogicalPresentationRect
{
    CHECK_RENDERER_MAGIC(renderer, false);
    SDL_RenderViewState *view = renderer->view;
    view->logical_presentation_mode = mode;
    view->logical_w = w;
    view->logical_h = h;
    UpdateLogicalPresentation(renderer);
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::logical_h, SDL_RenderViewState::logical_presentation_mode, SDL_RenderViewState::logical_w, UpdateLogicalPresentation(), and SDL_Renderer::view.
Referenced by SDL_RenderLogicalPresentation().
SDL_SetRenderScale()
bool SDL_SetRenderScale (SDL_Renderer * renderer, float scaleX, float scaleY)
Set the drawing scale for rendering on the current target.
The drawing coordinates are scaled by the x/y scaling factors before they are used by the renderer. This allows resolution independent drawing with a single coordinate system.
If this results in scaling or subpixel drawing by the rendering backend, it will be handled using the appropriate quality hints. For best results use integer scaling factors.
Each render target has its own scale. This function sets the scale for the current render target.
Parameters
renderer the rendering context.
scaleX the horizontal scaling factor.
scaleY the vertical scaling factor.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderScale
{
    bool result = true;
    CHECK_RENDERER_MAGIC(renderer, false);
    SDL_RenderViewState *view = renderer->view;
    if ((view->scale.x == scaleX) && (view->scale.y == scaleY)) {
        return true;
    }
    view->scale.x = scaleX;
    view->scale.y = scaleY;
    view->current_scale.x = scaleX * view->logical_scale.x;
    view->current_scale.y = scaleY * view->logical_scale.y;
    UpdatePixelViewport(renderer, view);
    UpdatePixelClipRect(renderer, view);
    // The scale affects the existing viewport and clip rectangle
    result &= QueueCmdSetViewport(renderer);
    result &= QueueCmdSetClipRect(renderer);
    return result;
}
References CHECK_RENDERER_MAGIC, SDL_RenderViewState::current_scale, SDL_RenderViewState::logical_scale, QueueCmdSetClipRect(), QueueCmdSetViewport(), SDL_RenderViewState::scale, UpdatePixelClipRect(), UpdatePixelViewport(), SDL_Renderer::view, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_RenderLogicalPresentation().
SDL_SetRenderTarget()
bool SDL_SetRenderTarget (SDL_Renderer * renderer, SDL_Texture * texture)
Set a texture as the current rendering target.
The default render target is the window for which the renderer was created. To stop rendering to a texture and render to the window again, call this function with a NULL texture.
Viewport, cliprect, scale, and logical presentation are unique to each render target. Get and set functions for these states apply to the current render target set by this function, and those states persist on each target when the current render target changes.
Parameters
renderer the rendering context.
texture the targeted texture, which must be created with the SDL_TEXTUREACCESS_TARGET flag, or NULL to render to the window instead of a texture.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderTarget
{
    // texture == NULL is valid and means reset the target to the window
    if (texture) {
        CHECK_TEXTURE_MAGIC(texture, false);
        if (renderer != texture->renderer) {
            return SDL_SetError("Texture was not created with this renderer");
        }
        if (texture->access != SDL_TEXTUREACCESS_TARGET) {
            return SDL_SetError("Texture not created with SDL_TEXTUREACCESS_TARGET");
        }
        if (texture->native) {
            // Always render to the native texture
            texture = texture->native;
        }
    }
    if (texture == renderer->target) {
        // Nothing to do!
        return true;
    }
    FlushRenderCommands(renderer); // time to send everything to the GPU!
    SDL_LockMutex(renderer->target_mutex);
    renderer->target = texture;
    if (texture) {
        renderer->view = &texture->view;
    } else {
        renderer->view = &renderer->main_view;
    }
    UpdateColorScale(renderer);
    if (!renderer->SetRenderTarget(renderer, texture)) {
        SDL_UnlockMutex(renderer->target_mutex);
        return false;
    }
    SDL_UnlockMutex(renderer->target_mutex);
    if (!QueueCmdSetViewport(renderer)) {
        return false;
    }
    if (!QueueCmdSetClipRect(renderer)) {
        return false;
    }
    // All set!
    return true;
}
References SDL_Texture::access, CHECK_TEXTURE_MAGIC, FlushRenderCommands(), SDL_Renderer::main_view, SDL_Texture::native, QueueCmdSetClipRect(), QueueCmdSetViewport(), SDL_Texture::renderer, SDL_LockMutex(), SDL_SetError(), SDL_TEXTUREACCESS_TARGET, SDL_UnlockMutex(), SDL_Renderer::SetRenderTarget, SDL_Renderer::target, SDL_Renderer::target_mutex, UpdateColorScale(), SDL_Renderer::view, and SDL_Texture::view.
Referenced by SDL_DestroyTextureInternal().
SDL_SetRenderTextureAddressMode()
bool SDL_SetRenderTextureAddressMode (SDL_Renderer * renderer, SDL_TextureAddressMode u_mode, SDL_TextureAddressMode v_mode)
Set the texture addressing mode used in SDL_RenderGeometry().
Parameters
renderer the rendering context.
u_mode the SDL_TextureAddressMode to use for horizontal texture coordinates in SDL_RenderGeometry().
v_mode the SDL_TextureAddressMode to use for vertical texture coordinates in SDL_RenderGeometry().
Returns
true on success or false on failure; call SDL_GetError() for more information.
Since
This function is available since SDL 3.4.0.
See also
SDL_RenderGeometry
SDL_RenderGeometryRaw
SDL_GetRenderTextureAddressMode
{
    CHECK_RENDERER_MAGIC(renderer, false);
    renderer->texture_address_mode_u = u_mode;
    renderer->texture_address_mode_v = v_mode;
    return true;
}
References CHECK_RENDERER_MAGIC, SDL_Renderer::texture_address_mode_u, and SDL_Renderer::texture_address_mode_v.
SDL_SetRenderViewport()
bool SDL_SetRenderViewport (SDL_Renderer * renderer, const SDL_Rect * rect)
Set the drawing area for rendering on the current target.
Drawing will clip to this area (separately from any clipping done with SDL_SetRenderClipRect), and the top left of the area will become coordinate (0, 0) for future drawing commands.
The area's width and height must be >= 0.
Each render target has its own viewport. This function sets the viewport for the current render target.
Parameters
renderer the rendering context.
rect the SDL_Rect structure representing the drawing area, or NULL to set the viewport to the entire target.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderViewport
SDL_RenderViewportSet
{
    CHECK_RENDERER_MAGIC(renderer, false);
    SDL_RenderViewState *view = renderer->view;
    if (rect) {
        if ((rect->w < 0) || (rect->h < 0)) {
            return SDL_SetError("rect has a negative size");
        }
        SDL_copyp(&view->viewport, rect);
    } else {
        view->viewport.x = view->viewport.y = 0;
        view->viewport.w = view->viewport.h = -1;
    }
    UpdatePixelViewport(renderer, view);
    return QueueCmdSetViewport(renderer);
}
References CHECK_RENDERER_MAGIC, SDL_Rect::h, QueueCmdSetViewport(), SDL_copyp, SDL_SetError(), UpdatePixelViewport(), SDL_Renderer::view, SDL_RenderViewState::viewport, SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_CreateRendererWithProperties(), SDL_CreateWindowTexture(), and SDL_RenderLogicalPresentation().
SDL_SetRenderVSync()
bool SDL_SetRenderVSync (SDL_Renderer * renderer, int vsync)
Toggle VSync of the given renderer.
When a renderer is created, vsync defaults to SDL_RENDERER_VSYNC_DISABLED.
The vsync parameter can be 1 to synchronize present with every vertical refresh, 2 to synchronize present with every second vertical refresh, etc., SDL_RENDERER_VSYNC_ADAPTIVE for late swap tearing (adaptive vsync), or SDL_RENDERER_VSYNC_DISABLED to disable. Not every value is supported by every driver, so you should check the return value to see whether the requested setting is supported.
Parameters
renderer the renderer to toggle.
vsync the vertical refresh sync interval.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetRenderVSync
{
    CHECK_RENDERER_MAGIC(renderer, false);
    renderer->wanted_vsync = vsync ? true : false;
    // for the software renderer, forward the call to the WindowTexture renderer
#ifdef SDL_VIDEO_RENDER_SW
    if (renderer->software) {
        if (!renderer->window) {
            if (!vsync) {
                return true;
            } else {
                return SDL_Unsupported();
            }
        }
        if (SDL_SetWindowTextureVSync(NULL, renderer->window, vsync)) {
            renderer->simulate_vsync = false;
            return true;
        }
    }
#endif
    if (!renderer->SetVSync ||
        !renderer->SetVSync(renderer, vsync)) {
        switch (vsync) {
        case 0:
            renderer->simulate_vsync = false;
            break;
        case 1:
            renderer->simulate_vsync = true;
            break;
        default:
            return SDL_Unsupported();
        }
    }
    SDL_SetNumberProperty(SDL_GetRendererProperties(renderer), SDL_PROP_RENDERER_VSYNC_NUMBER, vsync);
    return true;
}
References CHECK_RENDERER_MAGIC, NULL, SDL_GetRendererProperties(), SDL_PROP_RENDERER_VSYNC_NUMBER, SDL_SetNumberProperty(), SDL_SetWindowTextureVSync(), SDL_Unsupported, SDL_Renderer::SetVSync, SDL_Renderer::simulate_vsync, SDL_Renderer::software, true, SDL_Renderer::wanted_vsync, and SDL_Renderer::window.
Referenced by SDL_CreateRendererWithProperties(), and SDL_SetWindowTextureVSync().
SDL_SetTextureAlphaMod()
bool SDL_SetTextureAlphaMod (SDL_Texture * texture, Uint8 alpha)
Set an additional alpha value multiplied into render copy operations.
When this texture is rendered, during the copy operation the source alpha value is modulated by this alpha value according to the following formula:
srcA = srcA * (alpha / 255)
Alpha modulation is not always supported by the renderer; it will return false if alpha modulation is not supported.
Parameters
texture the texture to update.
alpha the source alpha value multiplied into copy operations.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureAlphaMod
SDL_SetTextureAlphaModFloat
SDL_SetTextureColorMod
{
    const float fA = (float)alpha / 255.0f;
    return SDL_SetTextureAlphaModFloat(texture, fA);
}
References SDL_SetTextureAlphaModFloat().
Referenced by SDL_RenderDebugText(), and SDL_UpdateTextureFromSurface().
SDL_SetTextureAlphaModFloat()
bool SDL_SetTextureAlphaModFloat (SDL_Texture * texture, float alpha)
Set an additional alpha value multiplied into render copy operations.
When this texture is rendered, during the copy operation the source alpha value is modulated by this alpha value according to the following formula:
srcA = srcA * alpha
Alpha modulation is not always supported by the renderer; it will return false if alpha modulation is not supported.
Parameters
texture the texture to update.
alpha the source alpha value multiplied into copy operations.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureAlphaModFloat
SDL_SetTextureAlphaMod
SDL_SetTextureColorModFloat
{
    CHECK_TEXTURE_MAGIC(texture, false);
    texture->color.a = alpha;
    if (texture->native) {
        return SDL_SetTextureAlphaModFloat(texture->native, alpha);
    }
    return true;
}
References SDL_FColor::a, CHECK_TEXTURE_MAGIC, SDL_Texture::color, SDL_Texture::native, and SDL_SetTextureAlphaModFloat().
Referenced by SDL_SetTextureAlphaMod(), and SDL_SetTextureAlphaModFloat().
SDL_SetTextureBlendMode()
bool SDL_SetTextureBlendMode (SDL_Texture * texture, SDL_BlendMode blendMode)
Set the blend mode for a texture, used by SDL_RenderTexture().
If the blend mode is not supported, the closest supported mode is chosen and this function returns false.
Parameters
texture the texture to update.
blendMode the SDL_BlendMode to use for texture blending.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureBlendMode
{
    SDL_Renderer *renderer;
    CHECK_TEXTURE_MAGIC(texture, false);
    if (blendMode == SDL_BLENDMODE_INVALID) {
        return SDL_InvalidParamError("blendMode");
    }
    renderer = texture->renderer;
    if (!IsSupportedBlendMode(renderer, blendMode)) {
        return SDL_Unsupported();
    }
    texture->blendMode = blendMode;
    if (texture->native) {
        return SDL_SetTextureBlendMode(texture->native, blendMode);
    }
    return true;
}
References SDL_Texture::blendMode, CHECK_TEXTURE_MAGIC, IsSupportedBlendMode(), SDL_Texture::native, SDL_Texture::renderer, SDL_BLENDMODE_INVALID, SDL_InvalidParamError, SDL_SetTextureBlendMode(), and SDL_Unsupported.
Referenced by SDL_RenderApplyWindowShape(), SDL_SetTextureBlendMode(), and SDL_UpdateTextureFromSurface().
SDL_SetTextureColorMod()
bool SDL_SetTextureColorMod (SDL_Texture * texture, Uint8 r, Uint8 g, Uint8 b)
Set an additional color value multiplied into render copy operations.
When this texture is rendered, during the copy operation each source color channel is modulated by the appropriate color value according to the following formula:
srcC = srcC * (color / 255)
Color modulation is not always supported by the renderer; it will return false if color modulation is not supported.
Parameters
texture the texture to update.
r the red color value multiplied into copy operations.
g the green color value multiplied into copy operations.
b the blue color value multiplied into copy operations.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureColorMod
SDL_SetTextureAlphaMod
SDL_SetTextureColorModFloat
{
    const float fR = (float)r / 255.0f;
    const float fG = (float)g / 255.0f;
    const float fB = (float)b / 255.0f;
    return SDL_SetTextureColorModFloat(texture, fR, fG, fB);
}
References SDL_SetTextureColorModFloat().
Referenced by SDL_RenderDebugText(), and SDL_UpdateTextureFromSurface().
SDL_SetTextureColorModFloat()
bool SDL_SetTextureColorModFloat (SDL_Texture * texture, float r, float g, float b)
Set an additional color value multiplied into render copy operations.
When this texture is rendered, during the copy operation each source color channel is modulated by the appropriate color value according to the following formula:
srcC = srcC * color
Color modulation is not always supported by the renderer; it will return false if color modulation is not supported.
Parameters
texture the texture to update.
r the red color value multiplied into copy operations.
g the green color value multiplied into copy operations.
b the blue color value multiplied into copy operations.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureColorModFloat
SDL_SetTextureAlphaModFloat
SDL_SetTextureColorMod
{
    CHECK_TEXTURE_MAGIC(texture, false);
    texture->color.r = r;
    texture->color.g = g;
    texture->color.b = b;
    if (texture->native) {
        return SDL_SetTextureColorModFloat(texture->native, r, g, b);
    }
    return true;
}
References SDL_FColor::b, CHECK_TEXTURE_MAGIC, SDL_Texture::color, SDL_FColor::g, SDL_Texture::native, SDL_FColor::r, and SDL_SetTextureColorModFloat().
Referenced by SDL_SetTextureColorMod(), and SDL_SetTextureColorModFloat().
SDL_SetTextureScaleMode()
bool SDL_SetTextureScaleMode (SDL_Texture * texture, SDL_ScaleMode scaleMode)
Set the scale mode used for texture scale operations.
The default texture scale mode is SDL_SCALEMODE_LINEAR.
If the scale mode is not supported, the closest supported mode is chosen.
Parameters
texture the texture to update.
scaleMode the SDL_ScaleMode to use for texture scaling.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetTextureScaleMode
{
    CHECK_TEXTURE_MAGIC(texture, false);
    switch (scaleMode) {
    case SDL_SCALEMODE_NEAREST:
    case SDL_SCALEMODE_LINEAR:
    case SDL_SCALEMODE_PIXELART:
        break;
    default:
        return SDL_InvalidParamError("scaleMode");
    }
    texture->scaleMode = scaleMode;
    if (texture->native) {
        return SDL_SetTextureScaleMode(texture->native, scaleMode);
    }
    return true;
}
References CHECK_TEXTURE_MAGIC, SDL_Texture::native, SDL_Texture::scaleMode, SDL_InvalidParamError, SDL_SCALEMODE_LINEAR, SDL_SCALEMODE_NEAREST, SDL_SCALEMODE_PIXELART, and SDL_SetTextureScaleMode().
Referenced by CreateDebugTextAtlas(), and SDL_SetTextureScaleMode().
SDL_SetupRendererColorspace()
void SDL_SetupRendererColorspace (SDL_Renderer * renderer, SDL_PropertiesID props)
{
    renderer->output_colorspace = (SDL_Colorspace)SDL_GetNumberProperty(props, SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER, SDL_COLORSPACE_SRGB);
}
References SDL_Renderer::output_colorspace, SDL_COLORSPACE_SRGB, SDL_GetNumberProperty(), and SDL_PROP_RENDERER_CREATE_OUTPUT_COLORSPACE_NUMBER.
SDL_SimulateRenderVSync()
void SDL_SimulateRenderVSync (SDL_Renderer * renderer) static
{
    Uint64 now, elapsed;
    const Uint64 interval = renderer->simulate_vsync_interval_ns;
    if (!interval) {
        // We can't do sub-ns delay, so just return here
        return;
    }
    now = SDL_GetTicksNS();
    elapsed = (now - renderer->last_present);
    if (elapsed < interval) {
        Uint64 duration = (interval - elapsed);
        SDL_DelayPrecise(duration);
        now = SDL_GetTicksNS();
    }
    elapsed = (now - renderer->last_present);
    if (!renderer->last_present || elapsed > SDL_MS_TO_NS(1000)) {
        // It's been too long, reset the presentation timeline
        renderer->last_present = now;
    } else {
        renderer->last_present += (elapsed / interval) * interval;
    }
}
References SDL_Renderer::last_present, SDL_DelayPrecise(), SDL_GetTicksNS(), SDL_MS_TO_NS, and SDL_Renderer::simulate_vsync_interval_ns.
Referenced by SDL_RenderPresent().
SDL_UnlockTexture()
void SDL_UnlockTexture (SDL_Texture * texture)
Unlock a texture, uploading the changes to video memory, if needed.
Warning: Please note that SDL_LockTexture() is intended to be write-only; it will not guarantee the previous contents of the texture will be provided. You must fully initialize any area of a texture that you lock before unlocking it, as the pixels might otherwise be uninitialized memory.
Which is to say: locking and immediately unlocking a texture can result in corrupted textures, depending on the renderer in use.
Parameters
texture a texture locked by SDL_LockTexture().
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockTexture
{
    CHECK_TEXTURE_MAGIC(texture,);
    if (texture->access != SDL_TEXTUREACCESS_STREAMING) {
        return;
    }
#ifdef SDL_HAVE_YUV
    if (texture->yuv) {
        SDL_UnlockTextureYUV(texture);
    } else
#endif
        if (texture->native) {
        SDL_UnlockTextureNative(texture);
    } else {
        SDL_Renderer *renderer = texture->renderer;
        renderer->UnlockTexture(renderer, texture);
    }
    SDL_DestroySurface(texture->locked_surface);
    texture->locked_surface = NULL;
}
References SDL_Texture::access, CHECK_TEXTURE_MAGIC, SDL_Texture::locked_surface, SDL_Texture::native, NULL, SDL_Texture::renderer, SDL_DestroySurface(), SDL_TEXTUREACCESS_STREAMING, SDL_UnlockTextureNative(), SDL_Renderer::UnlockTexture, and SDL_Texture::yuv.
Referenced by SDL_LockTextureToSurface(), SDL_UnlockTextureNative(), and SDL_UpdateTextureNative().
SDL_UnlockTextureNative()
void SDL_UnlockTextureNative (SDL_Texture * texture) static
{
    SDL_Texture *native = texture->native;
    void *native_pixels = NULL;
    int native_pitch = 0;
    const SDL_Rect *rect = &texture->locked_rect;
    const void *pixels = (void *)((Uint8 *)texture->pixels +
                                  rect->y * texture->pitch +
                                  rect->x * SDL_BYTESPERPIXEL(texture->format));
    int pitch = texture->pitch;
    if (!SDL_LockTexture(native, rect, &native_pixels, &native_pitch)) {
        return;
    }
    SDL_ConvertPixels(rect->w, rect->h,
                      texture->format, pixels, pitch,
                      native->format, native_pixels, native_pitch);
    SDL_UnlockTexture(native);
}
References SDL_Texture::format, SDL_Rect::h, SDL_Texture::locked_rect, SDL_Texture::native, NULL, SDL_Texture::pitch, SDL_Texture::pixels, SDL_BYTESPERPIXEL, SDL_ConvertPixels(), SDL_LockTexture(), SDL_UnlockTexture(), SDL_Rect::w, SDL_Rect::x, and SDL_Rect::y.
Referenced by SDL_UnlockTexture().
SDL_UpdateNVTexture()
bool SDL_UpdateNVTexture (SDL_Texture * texture, const SDL_Rect * rect, const Uint8 * Yplane, int Ypitch, const Uint8 * UVplane, int UVpitch)
Update a rectangle within a planar NV12 or NV21 texture with new pixels.
You can use SDL_UpdateTexture() as long as your pixel data is a contiguous block of NV12/21 planes in the proper order, but this function is available if your pixel data is not contiguous.
Parameters
texture the texture to update.
rect a pointer to the rectangle of pixels to update, or NULL to update the entire texture.
Yplane the raw pixel data for the Y plane.
Ypitch the number of bytes between rows of pixel data for the Y plane.
UVplane the raw pixel data for the UV plane.
UVpitch the number of bytes between rows of pixel data for the UV plane.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_UpdateTexture
SDL_UpdateYUVTexture
{
#ifdef SDL_HAVE_YUV
    SDL_Renderer *renderer;
    SDL_Rect real_rect;
    CHECK_TEXTURE_MAGIC(texture, false);
    if (!Yplane) {
        return SDL_InvalidParamError("Yplane");
    }
    if (!Ypitch) {
        return SDL_InvalidParamError("Ypitch");
    }
    if (!UVplane) {
        return SDL_InvalidParamError("UVplane");
    }
    if (!UVpitch) {
        return SDL_InvalidParamError("UVpitch");
    }
    if (texture->format != SDL_PIXELFORMAT_NV12 &&
        texture->format != SDL_PIXELFORMAT_NV21) {
        return SDL_SetError("Texture format must by NV12 or NV21");
    }
    real_rect.x = 0;
    real_rect.y = 0;
    real_rect.w = texture->w;
    real_rect.h = texture->h;
    if (rect) {
        SDL_GetRectIntersection(rect, &real_rect, &real_rect);
    }
    if (real_rect.w == 0 || real_rect.h == 0) {
        return true; // nothing to do.
    }
    if (texture->yuv) {
        return SDL_UpdateTextureNVPlanar(texture, &real_rect, Yplane, Ypitch, UVplane, UVpitch);
    } else {
        SDL_assert(!texture->native);
        renderer = texture->renderer;
        SDL_assert(renderer->UpdateTextureNV);
        if (renderer->UpdateTextureNV) {
            if (!FlushRenderCommandsIfTextureNeeded(texture)) {
                return false;
            }
            return renderer->UpdateTextureNV(renderer, texture, &real_rect, Yplane, Ypitch, UVplane, UVpitch);
        } else {
            return SDL_Unsupported();
        }
    }
#else
    return false;
#endif
}
References CHECK_TEXTURE_MAGIC, FlushRenderCommandsIfTextureNeeded(), SDL_Texture::format, SDL_Rect::h, SDL_Texture::h, SDL_Texture::native, SDL_Texture::renderer, SDL_assert, SDL_GetRectIntersection(), SDL_InvalidParamError, SDL_PIXELFORMAT_NV12, SDL_PIXELFORMAT_NV21, SDL_SetError(), SDL_Unsupported, SDL_Rect::w, SDL_Texture::w, SDL_Rect::x, SDL_Rect::y, and SDL_Texture::yuv.
SDL_UpdateTexture()
bool SDL_UpdateTexture (SDL_Texture * texture, const SDL_Rect * rect, const void * pixels, int pitch)
Update the given texture rectangle with new pixel data.
The pixel data must be in the pixel format of the texture, which can be queried using the SDL_PROP_TEXTURE_FORMAT_NUMBER property.
This is a fairly slow function, intended for use with static textures that do not change often.
If the texture is intended to be updated often, it is preferred to create the texture as streaming and use the locking functions referenced below. While this function will work with streaming textures, for optimization reasons you may not get the pixels back if you lock the texture afterward.
Parameters
texture the texture to update.
rect an SDL_Rect structure representing the area to update, or NULL to update the entire texture.
pixels the raw pixel data in the format of the texture.
pitch the number of bytes in a row of pixel data, including padding between lines.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_LockTexture
SDL_UnlockTexture
SDL_UpdateNVTexture
SDL_UpdateYUVTexture
{
    SDL_Rect real_rect;
    CHECK_TEXTURE_MAGIC(texture, false);
    if (!pixels) {
        return SDL_InvalidParamError("pixels");
    }
    if (!pitch) {
        return SDL_InvalidParamError("pitch");
    }
    real_rect.x = 0;
    real_rect.y = 0;
    real_rect.w = texture->w;
    real_rect.h = texture->h;
    if (rect) {
        if (!SDL_GetRectIntersection(rect, &real_rect, &real_rect)) {
            return true;
        }
    }
    if (real_rect.w == 0 || real_rect.h == 0) {
        return true; // nothing to do.
#ifdef SDL_HAVE_YUV
    } else if (texture->yuv) {
        return SDL_UpdateTextureYUV(texture, &real_rect, pixels, pitch);
#endif
    } else if (texture->native) {
        return SDL_UpdateTextureNative(texture, &real_rect, pixels, pitch);
    } else {
        SDL_Renderer *renderer = texture->renderer;
        if (!FlushRenderCommandsIfTextureNeeded(texture)) {
            return false;
        }
        return renderer->UpdateTexture(renderer, texture, &real_rect, pixels, pitch);
    }
}
References CHECK_TEXTURE_MAGIC, FlushRenderCommandsIfTextureNeeded(), SDL_Rect::h, SDL_Texture::h, SDL_Texture::native, SDL_Texture::renderer, SDL_GetRectIntersection(), SDL_InvalidParamError, SDL_UpdateTextureNative(), SDL_Renderer::UpdateTexture, SDL_Rect::w, SDL_Texture::w, SDL_Rect::x, SDL_Rect::y, and SDL_Texture::yuv.
Referenced by SDL_UpdateTextureFromSurface(), SDL_UpdateTextureNative(), and SDL_UpdateWindowTexture().
SDL_UpdateTextureFromSurface()
bool SDL_UpdateTextureFromSurface (SDL_Texture * texture, SDL_Rect * rect, SDL_Surface * surface) static
{
    SDL_TextureAccess access;
    bool direct_update;
    SDL_PixelFormat tex_format;
    SDL_PropertiesID surface_props;
    SDL_PropertiesID tex_props;
    SDL_Colorspace surface_colorspace = SDL_COLORSPACE_UNKNOWN;
    SDL_Colorspace texture_colorspace = SDL_COLORSPACE_UNKNOWN;
    if (texture == NULL || surface == NULL) {
        return false;
    }
    tex_props = SDL_GetTextureProperties(texture);
    if (!tex_props) {
        return false;
    }
    surface_props = SDL_GetSurfaceProperties(surface);
    if (!surface_props) {
        return false;
    }
    tex_format = (SDL_PixelFormat)SDL_GetNumberProperty(tex_props, SDL_PROP_TEXTURE_FORMAT_NUMBER, 0);
    access = (SDL_TextureAccess)SDL_GetNumberProperty(tex_props, SDL_PROP_TEXTURE_ACCESS_NUMBER, 0);
    if (access != SDL_TEXTUREACCESS_STATIC && access != SDL_TEXTUREACCESS_STREAMING) {
        return false;
    }
    surface_colorspace = SDL_GetSurfaceColorspace(surface);
    texture_colorspace = surface_colorspace;
    if (surface_colorspace == SDL_COLORSPACE_SRGB_LINEAR ||
        SDL_COLORSPACETRANSFER(surface_colorspace) == SDL_TRANSFER_CHARACTERISTICS_PQ) {
        if (SDL_ISPIXELFORMAT_FLOAT(tex_format)) {
            texture_colorspace = SDL_COLORSPACE_SRGB_LINEAR;
        } else if (SDL_ISPIXELFORMAT_10BIT(tex_format)) {
            texture_colorspace = SDL_COLORSPACE_HDR10;
        } else {
            texture_colorspace = SDL_COLORSPACE_SRGB;
        }
    }
    if (tex_format == surface->format && texture_colorspace == surface_colorspace) {
        if (SDL_ISPIXELFORMAT_ALPHA(surface->format) && SDL_SurfaceHasColorKey(surface)) {
            /* Surface and Renderer formats are identical.
             * Intermediate conversion is needed to convert color key to alpha (SDL_ConvertColorkeyToAlpha()). */
            direct_update = false;
        } else {
            // Update Texture directly
            direct_update = true;
        }
    } else {
        // Surface and Renderer formats are different, it needs an intermediate conversion.
        direct_update = false;
    }
    if (direct_update) {
        if (SDL_MUSTLOCK(surface)) {
            SDL_LockSurface(surface);
            SDL_UpdateTexture(texture, rect, surface->pixels, surface->pitch);
            SDL_UnlockSurface(surface);
        } else {
            SDL_UpdateTexture(texture, rect, surface->pixels, surface->pitch);
        }
    } else {
        SDL_Surface *temp = NULL;
        // Set up a destination surface for the texture update
        temp = SDL_ConvertSurfaceAndColorspace(surface, tex_format, NULL, texture_colorspace, surface_props);
        if (temp) {
            SDL_UpdateTexture(texture, NULL, temp->pixels, temp->pitch);
            SDL_DestroySurface(temp);
        } else {
            return false;
        }
    }
    {
        Uint8 r, g, b, a;
        SDL_BlendMode blendMode;
        SDL_GetSurfaceColorMod(surface, &r, &g, &b);
        SDL_SetTextureColorMod(texture, r, g, b);
        SDL_GetSurfaceAlphaMod(surface, &a);
        SDL_SetTextureAlphaMod(texture, a);
        if (SDL_SurfaceHasColorKey(surface)) {
            // We converted to a texture with alpha format
            SDL_SetTextureBlendMode(texture, SDL_BLENDMODE_BLEND);
        } else {
            SDL_GetSurfaceBlendMode(surface, &blendMode);
            SDL_SetTextureBlendMode(texture, blendMode);
        }
    }
    return true;
}
References NULL, SDL_Surface::pitch, SDL_Surface::pixels, SDL_BLENDMODE_BLEND, SDL_COLORSPACE_HDR10, SDL_COLORSPACE_SRGB, SDL_COLORSPACE_SRGB_LINEAR, SDL_COLORSPACE_UNKNOWN, SDL_COLORSPACETRANSFER, SDL_ConvertSurfaceAndColorspace(), SDL_DestroySurface(), SDL_GetNumberProperty(), SDL_GetSurfaceAlphaMod(), SDL_GetSurfaceBlendMode(), SDL_GetSurfaceColorMod(), SDL_GetSurfaceColorspace(), SDL_GetSurfaceProperties(), SDL_GetTextureProperties(), SDL_ISPIXELFORMAT_10BIT, SDL_ISPIXELFORMAT_ALPHA, SDL_ISPIXELFORMAT_FLOAT, SDL_LockSurface(), SDL_MUSTLOCK, SDL_PROP_TEXTURE_ACCESS_NUMBER, SDL_PROP_TEXTURE_FORMAT_NUMBER, SDL_SetTextureAlphaMod(), SDL_SetTextureBlendMode(), SDL_SetTextureColorMod(), SDL_SurfaceHasColorKey(), SDL_TEXTUREACCESS_STATIC, SDL_TEXTUREACCESS_STREAMING, SDL_TRANSFER_CHARACTERISTICS_PQ, SDL_UnlockSurface(), and SDL_UpdateTexture().
Referenced by SDL_CreateTextureFromSurface().
SDL_UpdateTextureNative()
bool SDL_UpdateTextureNative (SDL_Texture * texture, const SDL_Rect * rect, const void * pixels, int pitch) static
{
    SDL_Texture *native = texture->native;
    if (!rect->w || !rect->h) {
        return true; // nothing to do.
    }
    if (texture->access == SDL_TEXTUREACCESS_STREAMING) {
        // We can lock the texture and copy to it
        void *native_pixels = NULL;
        int native_pitch = 0;
        if (!SDL_LockTexture(native, rect, &native_pixels, &native_pitch)) {
            return false;
        }
        SDL_ConvertPixelsAndColorspace(rect->w, rect->h,
                                       texture->format, texture->colorspace, 0, pixels, pitch,
                                       native->format, native->colorspace, 0, native_pixels, native_pitch);
        SDL_UnlockTexture(native);
    } else {
        // Use a temporary buffer for updating
        const int temp_pitch = (((rect->w * SDL_BYTESPERPIXEL(native->format)) + 3) & ~3);
        const size_t alloclen = (size_t)rect->h * temp_pitch;
        if (alloclen > 0) {
            void *temp_pixels = SDL_malloc(alloclen);
            if (!temp_pixels) {
                return false;
            }
            SDL_ConvertPixelsAndColorspace(rect->w, rect->h,
                                           texture->format, texture->colorspace, 0, pixels, pitch,
                                           native->format, native->colorspace, 0, temp_pixels, temp_pitch);
            SDL_UpdateTexture(native, rect, temp_pixels, temp_pitch);
            SDL_free(temp_pixels);
        }
    }
    return true;
}
References SDL_Texture::access, SDL_Texture::colorspace, SDL_Texture::format, SDL_Rect::h, SDL_Texture::native, NULL, SDL_BYTESPERPIXEL, SDL_ConvertPixelsAndColorspace(), SDL_free(), SDL_LockTexture(), SDL_malloc(), SDL_TEXTUREACCESS_STREAMING, SDL_UnlockTexture(), SDL_UpdateTexture(), and SDL_Rect::w.
Referenced by SDL_UpdateTexture().
SDL_UpdateYUVTexture()
bool SDL_UpdateYUVTexture (SDL_Texture * texture, const SDL_Rect * rect, const Uint8 * Yplane, int Ypitch, const Uint8 * Uplane, int Upitch, const Uint8 * Vplane, int Vpitch)
Update a rectangle within a planar YV12 or IYUV texture with new pixel data.
You can use SDL_UpdateTexture() as long as your pixel data is a contiguous block of Y and U/V planes in the proper order, but this function is available if your pixel data is not contiguous.
Parameters
texture the texture to update.
rect a pointer to the rectangle of pixels to update, or NULL to update the entire texture.
Yplane the raw pixel data for the Y plane.
Ypitch the number of bytes between rows of pixel data for the Y plane.
Uplane the raw pixel data for the U plane.
Upitch the number of bytes between rows of pixel data for the U plane.
Vplane the raw pixel data for the V plane.
Vpitch the number of bytes between rows of pixel data for the V plane.
Returns
true on success or false on failure; call SDL_GetError() for more information.
Thread Safety
This function should only be called on the main thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_UpdateNVTexture
SDL_UpdateTexture
{
#ifdef SDL_HAVE_YUV
    SDL_Renderer *renderer;
    SDL_Rect real_rect;
    CHECK_TEXTURE_MAGIC(texture, false);
    if (!Yplane) {
        return SDL_InvalidParamError("Yplane");
    }
    if (!Ypitch) {
        return SDL_InvalidParamError("Ypitch");
    }
    if (!Uplane) {
        return SDL_InvalidParamError("Uplane");
    }
    if (!Upitch) {
        return SDL_InvalidParamError("Upitch");
    }
    if (!Vplane) {
        return SDL_InvalidParamError("Vplane");
    }
    if (!Vpitch) {
        return SDL_InvalidParamError("Vpitch");
    }
    if (texture->format != SDL_PIXELFORMAT_YV12 &&
        texture->format != SDL_PIXELFORMAT_IYUV) {
        return SDL_SetError("Texture format must by YV12 or IYUV");
    }
    real_rect.x = 0;
    real_rect.y = 0;
    real_rect.w = texture->w;
    real_rect.h = texture->h;
    if (rect) {
        SDL_GetRectIntersection(rect, &real_rect, &real_rect);
    }
    if (real_rect.w == 0 || real_rect.h == 0) {
        return true; // nothing to do.
    }
    if (texture->yuv) {
        return SDL_UpdateTextureYUVPlanar(texture, &real_rect, Yplane, Ypitch, Uplane, Upitch, Vplane, Vpitch);
    } else {
        SDL_assert(!texture->native);
        renderer = texture->renderer;
        SDL_assert(renderer->UpdateTextureYUV);
        if (renderer->UpdateTextureYUV) {
            if (!FlushRenderCommandsIfTextureNeeded(texture)) {
                return false;
            }
            return renderer->UpdateTextureYUV(renderer, texture, &real_rect, Yplane, Ypitch, Uplane, Upitch, Vplane, Vpitch);
        } else {
            return SDL_Unsupported();
        }
    }
#else
    return false;
#endif
}
References CHECK_TEXTURE_MAGIC, FlushRenderCommandsIfTextureNeeded(), SDL_Texture::format, SDL_Rect::h, SDL_Texture::h, SDL_Texture::native, SDL_Texture::renderer, SDL_assert, SDL_GetRectIntersection(), SDL_InvalidParamError, SDL_PIXELFORMAT_IYUV, SDL_PIXELFORMAT_YV12, SDL_SetError(), SDL_Unsupported, SDL_Rect::w, SDL_Texture::w, SDL_Rect::x, SDL_Rect::y, and SDL_Texture::yuv.
UpdateColorScale()
void UpdateColorScale (SDL_Renderer * renderer) static
{
    float SDR_white_point;
    if (renderer->target) {
        SDR_white_point = renderer->target->SDR_white_point;
    } else {
        SDR_white_point = renderer->SDR_white_point;
    }
    renderer->color_scale = renderer->desired_color_scale * SDR_white_point;
}
References SDL_Renderer::color_scale, SDL_Renderer::desired_color_scale, SDL_Renderer::SDR_white_point, SDL_Texture::SDR_white_point, and SDL_Renderer::target.
Referenced by SDL_SetRenderColorScale(), SDL_SetRenderTarget(), and UpdateHDRProperties().
UpdateHDRProperties()
void UpdateHDRProperties (SDL_Renderer * renderer) static
{
    SDL_PropertiesID window_props;
    SDL_PropertiesID renderer_props;
    window_props = SDL_GetWindowProperties(renderer->window);
    if (!window_props) {
        return;
    }
    renderer_props = SDL_GetRendererProperties(renderer);
    if (!renderer_props) {
        return;
    }
    if (renderer->output_colorspace == SDL_COLORSPACE_SRGB_LINEAR) {
        renderer->SDR_white_point = SDL_GetFloatProperty(window_props, SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT, 1.0f);
        renderer->HDR_headroom = SDL_GetFloatProperty(window_props, SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT, 1.0f);
    } else {
        renderer->SDR_white_point = 1.0f;
        renderer->HDR_headroom = 1.0f;
    }
    if (renderer->HDR_headroom > 1.0f) {
        SDL_SetBooleanProperty(renderer_props, SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN, true);
    } else {
        SDL_SetBooleanProperty(renderer_props, SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN, false);
    }
    SDL_SetFloatProperty(renderer_props, SDL_PROP_RENDERER_SDR_WHITE_POINT_FLOAT, renderer->SDR_white_point);
    SDL_SetFloatProperty(renderer_props, SDL_PROP_RENDERER_HDR_HEADROOM_FLOAT, renderer->HDR_headroom);
    UpdateColorScale(renderer);
}
References SDL_Renderer::HDR_headroom, SDL_Renderer::output_colorspace, SDL_COLORSPACE_SRGB_LINEAR, SDL_GetFloatProperty(), SDL_GetRendererProperties(), SDL_GetWindowProperties(), SDL_PROP_RENDERER_HDR_ENABLED_BOOLEAN, SDL_PROP_RENDERER_HDR_HEADROOM_FLOAT, SDL_PROP_RENDERER_SDR_WHITE_POINT_FLOAT, SDL_PROP_WINDOW_HDR_HEADROOM_FLOAT, SDL_PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT, SDL_SetBooleanProperty(), SDL_SetFloatProperty(), SDL_Renderer::SDR_white_point, UpdateColorScale(), and SDL_Renderer::window.
Referenced by SDL_CreateRendererWithProperties(), and SDL_RendererEventWatch().
UpdateLogicalPresentation()
void UpdateLogicalPresentation (SDL_Renderer * renderer) static
{
    SDL_RenderViewState *view = renderer->view;
    const bool is_main_view = (view == &renderer->main_view);
    const float logical_w = view->logical_w;
    const float logical_h = view->logical_h;
    int iwidth, iheight;
    if (is_main_view) {
        SDL_GetRenderOutputSize(renderer, &iwidth, &iheight);
    } else {
        SDL_assert(renderer->target != NULL);
        iwidth = (int)renderer->target->w;
        iheight = (int)renderer->target->h;
    }
    view->logical_src_rect.x = 0.0f;
    view->logical_src_rect.y = 0.0f;
    view->logical_src_rect.w = logical_w;
    view->logical_src_rect.h = logical_h;
    if (view->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_DISABLED) {
        view->logical_dst_rect.x = 0.0f;
        view->logical_dst_rect.y = 0.0f;
        view->logical_dst_rect.w = iwidth;
        view->logical_dst_rect.h = iheight;
        view->logical_offset.x = view->logical_offset.y = 0.0f;
        view->logical_scale.x = view->logical_scale.y = 1.0f;
        view->current_scale.x = view->scale.x;  // skip the multiplications against 1.0f.
        view->current_scale.y = view->scale.y;
    } else {
        const float output_w = (float)iwidth;
        const float output_h = (float)iheight;
        const float want_aspect = logical_w / logical_h;
        const float real_aspect = output_w / output_h;
        if ((logical_w <= 0.0f) || (logical_h <= 0.0f)) {
            view->logical_dst_rect.x = 0.0f;
            view->logical_dst_rect.y = 0.0f;
            view->logical_dst_rect.w = output_w;
            view->logical_dst_rect.h = output_h;
        } else if (view->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_INTEGER_SCALE) {
            float scale;
            if (want_aspect > real_aspect) {
                scale = (float)((int)output_w / (int)logical_w); // This an integer division!
            } else {
                scale = (float)((int)output_h / (int)logical_h); // This an integer division!
            }
            if (scale < 1.0f) {
                scale = 1.0f;
            }
            view->logical_dst_rect.w = SDL_floorf(logical_w * scale);
            view->logical_dst_rect.x = (output_w - view->logical_dst_rect.w) / 2.0f;
            view->logical_dst_rect.h = SDL_floorf(logical_h * scale);
            view->logical_dst_rect.y = (output_h - view->logical_dst_rect.h) / 2.0f;
        } else if (view->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_STRETCH || SDL_fabsf(want_aspect - real_aspect) < 0.0001f) {
            view->logical_dst_rect.x = 0.0f;
            view->logical_dst_rect.y = 0.0f;
            view->logical_dst_rect.w = output_w;
            view->logical_dst_rect.h = output_h;
        } else if (want_aspect > real_aspect) {
            if (view->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_LETTERBOX) {
                // We want a wider aspect ratio than is available - letterbox it
                const float scale = output_w / logical_w;
                view->logical_dst_rect.x = 0.0f;
                view->logical_dst_rect.w = output_w;
                view->logical_dst_rect.h = SDL_floorf(logical_h * scale);
                view->logical_dst_rect.y = (output_h - view->logical_dst_rect.h) / 2.0f;
            } else { // view->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_OVERSCAN
                /* We want a wider aspect ratio than is available -
                   zoom so logical height matches the real height
                   and the width will grow off the screen
                 */
                const float scale = output_h / logical_h;
                view->logical_dst_rect.y = 0.0f;
                view->logical_dst_rect.h = output_h;
                view->logical_dst_rect.w = SDL_floorf(logical_w * scale);
                view->logical_dst_rect.x = (output_w - view->logical_dst_rect.w) / 2.0f;
            }
        } else {
            if (view->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_LETTERBOX) {
                // We want a narrower aspect ratio than is available - use side-bars
                const float scale = output_h / logical_h;
                view->logical_dst_rect.y = 0.0f;
                view->logical_dst_rect.h = output_h;
                view->logical_dst_rect.w = SDL_floorf(logical_w * scale);
                view->logical_dst_rect.x = (output_w - view->logical_dst_rect.w) / 2.0f;
            } else { // view->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_OVERSCAN
                /* We want a narrower aspect ratio than is available -
                   zoom so logical width matches the real width
                   and the height will grow off the screen
                 */
                const float scale = output_w / logical_w;
                view->logical_dst_rect.x = 0.0f;
                view->logical_dst_rect.w = output_w;
                view->logical_dst_rect.h = SDL_floorf(logical_h * scale);
                view->logical_dst_rect.y = (output_h - view->logical_dst_rect.h) / 2.0f;
            }
        }
        view->logical_scale.x = (logical_w > 0.0f) ? view->logical_dst_rect.w / logical_w : 0.0f;
        view->logical_scale.y = (logical_h > 0.0f) ? view->logical_dst_rect.h / logical_h : 0.0f;
        view->current_scale.x = view->scale.x * view->logical_scale.x;
        view->current_scale.y = view->scale.y * view->logical_scale.y;
        view->logical_offset.x = view->logical_dst_rect.x;
        view->logical_offset.y = view->logical_dst_rect.y;
    }
    if (is_main_view) {
        // This makes sure the dpi_scale is right. It also sets pixel_w and pixel_h, but we're going to change them directly below here.
        UpdateMainViewDimensions(renderer);
    }
    view->pixel_w = (int) view->logical_dst_rect.w;
    view->pixel_h = (int) view->logical_dst_rect.h;
    UpdatePixelViewport(renderer, view);
    UpdatePixelClipRect(renderer, view);
    QueueCmdSetViewport(renderer);
    QueueCmdSetClipRect(renderer);
}
References SDL_RenderViewState::current_scale, SDL_FRect::h, SDL_Texture::h, SDL_RenderViewState::logical_dst_rect, SDL_RenderViewState::logical_h, SDL_RenderViewState::logical_offset, SDL_RenderViewState::logical_presentation_mode, SDL_RenderViewState::logical_scale, SDL_RenderViewState::logical_src_rect, SDL_RenderViewState::logical_w, SDL_Renderer::main_view, NULL, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, QueueCmdSetClipRect(), QueueCmdSetViewport(), SDL_RenderViewState::scale, SDL_assert, SDL_fabsf(), SDL_floorf(), SDL_GetRenderOutputSize(), SDL_LOGICAL_PRESENTATION_DISABLED, SDL_LOGICAL_PRESENTATION_INTEGER_SCALE, SDL_LOGICAL_PRESENTATION_LETTERBOX, SDL_LOGICAL_PRESENTATION_STRETCH, SDL_Renderer::target, UpdateMainViewDimensions(), UpdatePixelClipRect(), UpdatePixelViewport(), SDL_Renderer::view, SDL_FRect::w, SDL_Texture::w, SDL_FPoint::x, SDL_FRect::x, SDL_FPoint::y, and SDL_FRect::y.
Referenced by SDL_RendererEventWatch(), and SDL_SetRenderLogicalPresentation().
UpdateMainViewDimensions()
void UpdateMainViewDimensions (SDL_Renderer * renderer) static
{
    int window_w = 0, window_h = 0;
    if (renderer->window) {
        SDL_GetWindowSize(renderer->window, &window_w, &window_h);
    }
    SDL_GetRenderOutputSize(renderer, &renderer->main_view.pixel_w, &renderer->main_view.pixel_h);
    if (window_w > 0 && window_h > 0) {
        renderer->dpi_scale.x = (float)renderer->main_view.pixel_w / window_w;
        renderer->dpi_scale.y = (float)renderer->main_view.pixel_h / window_h;
    } else {
        renderer->dpi_scale.x = 1.0f;
        renderer->dpi_scale.y = 1.0f;
    }
    UpdatePixelViewport(renderer, &renderer->main_view);
}
References SDL_Renderer::dpi_scale, SDL_Renderer::main_view, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_w, SDL_GetRenderOutputSize(), SDL_GetWindowSize(), UpdatePixelViewport(), SDL_Renderer::window, SDL_FPoint::x, and SDL_FPoint::y.
Referenced by SDL_CreateRendererWithProperties(), and UpdateLogicalPresentation().
UpdatePixelClipRect()
void UpdatePixelClipRect (SDL_Renderer * renderer, SDL_RenderViewState * view) static
{
    const float scale_x = view->current_scale.x;
    const float scale_y = view->current_scale.y;
    view->pixel_clip_rect.x = (int)SDL_floorf(view->clip_rect.x * scale_x);
    view->pixel_clip_rect.y = (int)SDL_floorf(view->clip_rect.y * scale_y);
    view->pixel_clip_rect.w = (int)SDL_ceilf(view->clip_rect.w * scale_x);
    view->pixel_clip_rect.h = (int)SDL_ceilf(view->clip_rect.h * scale_y);
}
References SDL_RenderViewState::clip_rect, SDL_RenderViewState::current_scale, SDL_Rect::h, SDL_RenderViewState::pixel_clip_rect, SDL_ceilf(), SDL_floorf(), SDL_Rect::w, SDL_FPoint::x, SDL_Rect::x, SDL_FPoint::y, and SDL_Rect::y.
Referenced by SDL_CreateRendererWithProperties(), SDL_CreateTextureWithProperties(), SDL_SetRenderClipRect(), SDL_SetRenderScale(), and UpdateLogicalPresentation().
UpdatePixelViewport()
void UpdatePixelViewport (SDL_Renderer * renderer, SDL_RenderViewState * view) static
{
    view->pixel_viewport.x = (int)SDL_floorf((view->viewport.x * view->current_scale.x) + view->logical_offset.x);
    view->pixel_viewport.y = (int)SDL_floorf((view->viewport.y * view->current_scale.y) + view->logical_offset.y);
    if (view->viewport.w >= 0) {
        view->pixel_viewport.w = (int)SDL_ceilf(view->viewport.w * view->current_scale.x);
    } else {
        view->pixel_viewport.w = view->pixel_w;
    }
    if (view->viewport.h >= 0) {
        view->pixel_viewport.h = (int)SDL_ceilf(view->viewport.h * view->current_scale.y);
    } else {
        view->pixel_viewport.h = view->pixel_h;
    }
}
References SDL_RenderViewState::current_scale, SDL_Rect::h, SDL_RenderViewState::logical_offset, SDL_RenderViewState::pixel_h, SDL_RenderViewState::pixel_viewport, SDL_RenderViewState::pixel_w, SDL_ceilf(), SDL_floorf(), SDL_RenderViewState::viewport, SDL_Rect::w, SDL_FPoint::x, SDL_Rect::x, SDL_FPoint::y, and SDL_Rect::y.
Referenced by SDL_CreateRendererWithProperties(), SDL_CreateTextureWithProperties(), SDL_SetRenderScale(), SDL_SetRenderViewport(), UpdateLogicalPresentation(), and UpdateMainViewDimensions().
VerifyDrawQueueFunctions()
SDL_INLINE void VerifyDrawQueueFunctions (const SDL_Renderer * renderer) static
{
    /* all of these functions are required to be implemented, even as no-ops, so we don't
        have to check that they aren't NULL over and over. */
    SDL_assert(renderer->QueueSetViewport != NULL);
    SDL_assert(renderer->QueueSetDrawColor != NULL);
    SDL_assert(renderer->QueueDrawPoints != NULL);
    SDL_assert(renderer->QueueDrawLines != NULL || renderer->QueueGeometry != NULL);
    SDL_assert(renderer->QueueFillRects != NULL || renderer->QueueGeometry != NULL);
    SDL_assert(renderer->QueueCopy != NULL || renderer->QueueGeometry != NULL);
    SDL_assert(renderer->RunCommandQueue != NULL);
}
References NULL, SDL_Renderer::QueueCopy, SDL_Renderer::QueueDrawLines, SDL_Renderer::QueueDrawPoints, SDL_Renderer::QueueFillRects, SDL_Renderer::QueueGeometry, SDL_Renderer::QueueSetDrawColor, SDL_Renderer::QueueSetViewport, SDL_Renderer::RunCommandQueue, SDL_assert, and SDL_INLINE.
Referenced by SDL_CreateRendererWithProperties().
Variable Documentation
rect_index_order
const int rect_index_order[] = { 0, 1, 2, 0, 2, 3 } static
{ 0, 1, 2, 0, 2, 3 };
Referenced by QueueCmdFillRects(), SDL_RenderTextureAffine(), SDL_RenderTextureInternal(), SDL_RenderTextureRotated(), and SDL_RenderTextureTiled_Wrap().
render_drivers
const SDL_RenderDriver* render_drivers[] static
{
#ifdef SDL_VIDEO_RENDER_D3D11
    &D3D11_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_D3D12
    &D3D12_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_D3D
    &D3D_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_METAL
    &METAL_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_NGAGE
    &NGAGE_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_OGL
    &GL_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_OGL_ES2
    &GLES2_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_PS2
    &PS2_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_PSP
    &PSP_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_VITA_GXM
    &VITA_GXM_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_VULKAN
    &VULKAN_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_GPU
    &GPU_RenderDriver,
#endif
#ifdef SDL_VIDEO_RENDER_SW
    &SW_RenderDriver,
#endif
    NULL
};
Referenced by SDL_CreateRendererWithProperties(), SDL_GetNumRenderDrivers(), and SDL_GetRenderDriver().
SDL_renderers
SDL_Renderer* SDL_renderers static
Referenced by SDL_CreateRendererWithProperties(), SDL_DestroyRenderer(), and SDL_QuitRender().