SDL3: SDL-main/src/SDL_error.c File Reference
SDL_error.c File Reference
#include "SDL_internal.h"
#include "stdlib/SDL_vacopy.h"
#include "SDL_error_c.h"
Functions
bool SDL_ClearError (void)
const char * SDL_GetError (void)
bool SDL_OutOfMemory (void)
bool SDL_SetError (SDL_PRINTF_FORMAT_STRING const char *fmt,...)
bool SDL_SetErrorV (SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap)
Function Documentation
SDL_ClearError()
bool SDL_ClearError (void)
Clear any previous error message for this thread.
Returns
true.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetError
SDL_SetError
{
    SDL_error *error = SDL_GetErrBuf(false);
    if (error) {
        error->error = SDL_ErrorCodeNone;
    }
    return true;
}
References SDL_error::error, SDL_ErrorCodeNone, and SDL_GetErrBuf().
Referenced by register_error_str(), register_string_error_to_buffer(), register_winapi_error_to_buffer(), SDL_CreateRendererWithProperties(), SDL_CreateWindowWithProperties(), SDL_FlushIO(), SDL_GetHapticEffectStatus(), SDL_InitSubSystem(), SDL_LoadBMP_IO(), SDL_PushEvent(), SDL_ReadIO(), SDL_ShowMessageBox(), and SDL_WriteIO().
SDL_GetError()
const char * SDL_GetError (void)
Retrieve a message about the last error that occurred on the current thread.
It is possible for multiple errors to occur before calling SDL_GetError(). Only the last error is returned.
The message is only applicable when an SDL function has signaled an error. You must check the return values of SDL function calls to determine when to appropriately call SDL_GetError(). You should not use the results of SDL_GetError() to decide if an error has occurred! Sometimes SDL will set an error string even when reporting success.
SDL will not clear the error string for successful API calls. You must check return values for failure cases before you can assume the error string applies.
Error strings are set per-thread, so an error set in a different thread will not interfere with the current thread's operation.
The returned value is a thread-local string which will remain valid until the current thread's error string is changed. The caller should make a copy if the value is needed after the next SDL API call.
Returns
a message with information about the specific error that occurred, or an empty string if there hasn't been an error message set since the last call to SDL_ClearError().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearError
SDL_SetError
{
    const SDL_error *error = SDL_GetErrBuf(false);
    if (!error) {
        return "";
    }
    switch (error->error) {
    case SDL_ErrorCodeGeneric:
        return error->str;
    case SDL_ErrorCodeOutOfMemory:
        return "Out of memory";
    default:
        return "";
    }
}
References SDL_error::error, SDL_ErrorCodeGeneric, SDL_ErrorCodeOutOfMemory, SDL_GetErrBuf(), and SDL_error::str.
Referenced by SDL_CameraThreadIterate(), SDL_LoadBMP_IO(), SDL_ReadIO(), SDL_ShowMessageBox(), and SDL_SYS_ShowFileDialogWithProperties().
SDL_OutOfMemory()
bool SDL_OutOfMemory (void)
Set an error indicating that memory allocation failed.
This function does not do any memory allocation.
Returns
false.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_error *error = SDL_GetErrBuf(true);
    if (error) {
        error->error = SDL_ErrorCodeOutOfMemory;
    }
    return false;
}
References SDL_error::error, SDL_ErrorCodeOutOfMemory, and SDL_GetErrBuf().
Referenced by SDL_calloc(), SDL_malloc(), SDL_realloc(), and SDL_SYS_ShowFileDialogWithProperties().
SDL_SetError()
bool SDL_SetError (SDL_PRINTF_FORMAT_STRING const char * fmt, ...)
CategoryError
Simple error message routines for SDL.
Most apps will interface with these APIs in exactly one function: when almost any SDL function call reports failure, you can get a human-readable string of the problem from SDL_GetError().
These strings are maintained per-thread, and apps are welcome to set their own errors, which is popular when building libraries on top of SDL for other apps to consume. These strings are set by calling SDL_SetError().
A common usage pattern is to have a function that returns true for success and false for failure, and do this when something fails:
if (something_went_wrong) {
   return SDL_SetError("The thing broke in this specific way: %d", errcode);
}
It's also common to just return false in this case if the failing thing is known to call SDL_SetError(), so errors simply propagate through. Set the SDL error message for the current thread.
Calling this function will replace any previous error message that was set.
This function always returns false, since SDL frequently uses false to signify a failing result, leading to this idiom:
if (error_code) {
    return SDL_SetError("This operation has failed: %d", error_code);
}
Parameters
fmt a printf()-style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Returns
false.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearError
SDL_GetError
SDL_SetErrorV
{
    va_list ap;
    bool result;
    va_start(ap, fmt);
    result = SDL_SetErrorV(fmt, ap);
    va_end(ap);
    return result;
}
References SDL_PRINTF_FORMAT_STRING, and SDL_SetErrorV().
Referenced by CHIDDevice::BOpen(), CheckAudioStreamIsFullySetup(), convert_ext_list(), convert_filters(), detect_available_methods(), fd_close(), fd_flush(), fd_read(), fd_seek(), fd_write(), FindPenByInstanceId(), GDK_RegisterChangeNotifications(), GENERIC_ReadStorageFile(), GENERIC_WriteStorageFile(), get_appindicator_id(), GetAudioDevices(), GetAudioStreamDataInternal(), GetDisplayForRect(), IMA_ADPCM_CalculateSampleFrames(), IMA_ADPCM_Decode(), IMA_ADPCM_Init(), init_gtk(), IOS_JoystickOpen(), IOS_JoystickRumble(), IOS_JoystickRumbleTriggers(), IOS_JoystickSetLED(), IOS_JoystickSetSensorsEnabled(), LAW_Decode(), LAW_Init(), Map1toN(), mem_seek(), MS_ADPCM_CalculateSampleFrames(), MS_ADPCM_Decode(), MS_ADPCM_DecodeBlockHeader(), MS_ADPCM_Init(), new_tmp_filename(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), ObtainPhysicalCamera(), OpenPhysicalAudioDevice(), PCM_ConvertSint24ToSint32(), PCM_Decode(), PCM_Init(), PeekIntoAudioQueueFuture(), PLATFORM_hid_open_path(), PS2AUDIO_OpenDevice(), PutAudioStreamBuffer(), ReadFromAudioQueue(), register_error_str(), register_string_error_to_buffer(), register_winapi_error_to_buffer(), RenderLineBresenham(), RequestAsyncIO(), run_zenity(), SDL_AcquireCameraFrame(), SDL_AddEvent(), SDL_AddGamepadMappingsFromIO(), SDL_AsyncIOFromFile(), SDL_AttachVirtualJoystick(), SDL_BeginGPURenderPass(), SDL_BindAudioStreams(), SDL_BlitSurface(), SDL_BlitSurfaceScaled(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_BlitSurfaceUncheckedScaled(), SDL_CalculateBlit(), SDL_CalculateRGBSize(), SDL_CalculateYUVSize(), SDL_CameraInit(), SDL_CaptureMouse(), SDL_ClaimWindowForGPUDevice(), SDL_CloseAsyncIO(), SDL_ContextNotSupported(), SDL_ConvertPixels_STB(), SDL_ConvertPixels_YUV_to_YUV(), SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateColorCursor(), SDL_CreateCondition(), SDL_CreateGPUDevice(), SDL_CreateGPUDeviceWithProperties(), SDL_CreateGPURenderState(), SDL_CreateHapticEffect(), SDL_CreateMutex(), SDL_CreatePopupWindow(), SDL_CreateProcessWithProperties(), SDL_CreateRendererWithProperties(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateSoftwareRenderer(), SDL_CreateSurfacePalette(), SDL_CreateSystemCursor(), SDL_CreateTextureWithProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateTray(), SDL_CreateTraySubmenu(), SDL_CreateWindowFramebuffer(), SDL_CreateWindowTexture(), SDL_CreateWindowWithProperties(), SDL_DateTimeIsValid(), SDL_DateTimeToTime(), SDL_DetachVirtualJoystick(), SDL_DllNotSupported(), SDL_EGL_GetCurrentConfig(), SDL_EGL_GetCurrentDisplay(), SDL_EGL_GetProcAddress(), SDL_EGL_GetWindowSurface(), SDL_FillSurfaceRects(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetAudioDeviceName(), SDL_GetAudioStreamDevice(), SDL_GetAudioStreamFormat(), SDL_GetCameraFormat(), SDL_GetCameras(), SDL_GetClosestFullscreenDisplayMode(), SDL_GetDayOfWeek(), SDL_GetDayOfYear(), SDL_GetDaysInMonth(), SDL_GetDisplayIndex(), SDL_GetDriverAndJoystickIndex(), SDL_GetDriverAndSensorIndex(), SDL_GetEventCategory(), SDL_GetGamepadMappingForGUID(), SDL_GetGDKTaskQueue(), SDL_GetHapticEffectStatus(), SDL_GetHapticIndex(), SDL_GetJoystickAxis(), SDL_GetJoystickAxisInitialState(), SDL_GetJoystickBall(), SDL_GetJoystickButton(), SDL_GetJoystickHat(), SDL_GetKeyboardNameForID(), SDL_GetMasksForPixelFormat(), SDL_GetMouseNameForID(), SDL_GetProcessInput(), SDL_GetProcessOutput(), SDL_GetRenderDriver(), SDL_GetRenderOutputSize(), SDL_GetRenderSafeArea(), SDL_GetSurfaceColorKey(), SDL_GetTouch(), SDL_GetWindowFromID(), SDL_GL_CreateContext(), SDL_GL_GetAttribute(), SDL_GL_GetProcAddress(), SDL_GL_GetSwapInterval(), SDL_GL_LoadLibrary(), SDL_GL_MakeCurrent(), SDL_GL_SetAttribute(), SDL_GL_SetSwapInterval(), SDL_GL_SwapWindow(), SDL_GPU_FetchBlitPipeline(), SDL_GPUSelectBackend(), SDL_GPUSupportsProperties(), SDL_GPUSupportsShaderFormats(), SDL_HASINTERSECTION(), SDL_InitAudio(), SDL_InitHapticRumble(), SDL_InitSubSystem(), SDL_InsertIntoHashTable(), SDL_INTERSECTRECT(), SDL_INTERSECTRECTANDLINE(), SDL_IOFromFile(), SDL_IsTraySupported(), SDL_KillProcess(), SDL_LoadBMP_IO(), SDL_LockTexture(), SDL_MaximizeWindow(), SDL_Metal_GetLayer(), SDL_MixAudio(), SDL_OpenAudioDevice(), SDL_OpenCamera(), SDL_OpenGamepad(), SDL_OpenHapticFromJoystick(), SDL_OpenHapticFromMouse(), SDL_OpenIO(), SDL_OpenStorage(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_PauseHaptic(), SDL_PeepEventsInternal(), SDL_PlayHapticRumble(), SDL_PremultiplyAlphaPixelsAndColorspace(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateParseGamepadConfigString(), SDL_ReadProcess(), SDL_RecreateWindow(), SDL_RemoveTimer(), SDL_RemoveTrayEntry(), SDL_RenderGeometryRaw(), SDL_RenderPresent(), SDL_RenderReadPixels(), SDL_RenderTexture(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), SDL_RenderTextureAffine(), SDL_RenderTextureRotated(), SDL_RenderTextureTiled(), SDL_RunApp(), SDL_RunOnMainThread(), SDL_SaveBMP_IO(), SDL_SendJoystickVirtualSensorData(), SDL_SetAudioStreamFrequencyRatio(), SDL_SetClipboardData(), SDL_SetCursor(), SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_SetHintWithPriority(), SDL_SetJoystickVirtualAxis(), SDL_SetJoystickVirtualBall(), SDL_SetJoystickVirtualButton(), SDL_SetJoystickVirtualHat(), SDL_SetJoystickVirtualTouchpad(), SDL_SetKeyboardFocus(), SDL_SetPrimarySelectionText(), SDL_SetRelativeMouseMode(), SDL_SetRelativeMouseTransform(), SDL_SetRenderTarget(), SDL_SetRenderViewport(), SDL_SetSurfacePalette(), SDL_SetTrayEntryLabel(), SDL_SetWindowFullscreenMode(), SDL_SetWindowMaximumSize(), SDL_SetWindowMinimumSize(), SDL_SetWindowModal(), SDL_SetWindowParent(), SDL_SetWindowShape(), SDL_ShowFileDialogWithProperties(), SDL_ShowMessageBox(), SDL_ShowOpenFileDialog(), SDL_ShowOpenFolderDialog(), SDL_ShowSaveFileDialog(), SDL_StopHapticRumble(), SDL_StretchSurface(), SDL_SYS_CreateThread(), SDL_SYS_GetPreferredLocales(), SDL_SYS_GetPreferredLocales_winxp(), SDL_SYS_OpenURL(), SDL_SYS_SetThreadPriority(), SDL_SYS_SetTLSData(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UninitializedVideo(), SDL_UNIONRECT(), SDL_UnlockMutex(), SDL_UpdateHapticEffect(), SDL_UpdateNVTexture(), SDL_UpdateWindowSurfaceRects(), SDL_UpdateWindowTexture(), SDL_UpdateYUVTexture(), SDL_VideoInit(), SDL_vswprintf(), SDL_Vulkan_CreateSurface(), SDL_Vulkan_GetVkGetInstanceProcAddr(), SDL_Vulkan_LoadLibrary(), SetAudioStreamChannelMap(), ShowFileDialog(), ShowFolderDialog(), STEAM_CloseStorage(), STEAM_GetStoragePathInfo(), STEAM_GetStorageSpaceRemaining(), STEAM_ReadStorageFile(), STEAM_User_Create(), STEAM_WriteStorageFile(), ValidateStoragePath(), ValidEffect(), WaveAdjustToFactValue(), WaveCheckFormat(), WaveLoad(), WaveReadFormat(), and windows_ShowFileDialog().
SDL_SetErrorV()
bool SDL_SetErrorV (SDL_PRINTF_FORMAT_STRING const char * fmt, va_list ap)
Set the SDL error message for the current thread.
Calling this function will replace any previous error message that was set.
Parameters
fmt a printf()-style message format string.
ap a variable argument list.
Returns
false.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearError
SDL_GetError
SDL_SetError
{
    // Ignore call if invalid format pointer was passed
    if (fmt) {
        int result;
        SDL_error *error = SDL_GetErrBuf(true);
        va_list ap2;
        error->error = SDL_ErrorCodeGeneric;
        va_copy(ap2, ap);
        result = SDL_vsnprintf(error->str, error->len, fmt, ap2);
        va_end(ap2);
        if (result >= 0 && (size_t)result >= error->len && error->realloc_func) {
            size_t len = (size_t)result + 1;
            char *str = (char *)error->realloc_func(error->str, len);
            if (str) {
                error->str = str;
                error->len = len;
                va_copy(ap2, ap);
                (void)SDL_vsnprintf(error->str, error->len, fmt, ap2);
                va_end(ap2);
            }
        }
// Enable this if you want to see all errors printed as they occur.
// Note that there are many recoverable errors that may happen internally and
// can be safely ignored if the public API doesn't return an error code.
#if 0
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "%s", error->str);
#endif
    }
    return false;
}
References SDL_error::error, SDL_error::len, SDL_error::realloc_func, SDL_ErrorCodeGeneric, SDL_GetErrBuf(), SDL_LOG_CATEGORY_ERROR, SDL_LogError(), SDL_PRINTF_FORMAT_STRING, SDL_vsnprintf(), SDL_error::str, and void().
Referenced by SDL_SetError().