SDL3: SDL-main/src/events/SDL_touch_c.h File Reference
SDL_touch_c.h File Reference
#include "SDL_internal.h"
Data Structures
struct SDL_Touch
Typedefs
typedef struct SDL_Touch SDL_Touch
Functions
int SDL_AddTouch (SDL_TouchID id, SDL_TouchDeviceType type, const char *name)
void SDL_DelTouch (SDL_TouchID id)
SDL_Touch * SDL_GetTouch (SDL_TouchID id)
bool SDL_InitTouch (void)
void SDL_QuitTouch (void)
void SDL_SendTouch (Uint64 timestamp, SDL_TouchID id, SDL_FingerID fingerid, SDL_Window *window, SDL_EventType type, float x, float y, float pressure)
void SDL_SendTouchMotion (Uint64 timestamp, SDL_TouchID id, SDL_FingerID fingerid, SDL_Window *window, float x, float y, float pressure)
bool SDL_TouchDevicesAvailable (void)
Typedef Documentation
SDL_Touch
typedef struct SDL_Touch SDL_Touch
Function Documentation
SDL_AddTouch()
int SDL_AddTouch (SDL_TouchID id, SDL_TouchDeviceType type, const char * name) extern
{
    SDL_Touch **touchDevices;
    int index;
    SDL_assert(touchID != 0);
    index = SDL_GetTouchIndex(touchID);
    if (index >= 0) {
        return index;
    }
    // Add the touch to the list of touch
    touchDevices = (SDL_Touch **)SDL_realloc(SDL_touchDevices,
                                             (SDL_num_touch + 1) * sizeof(*touchDevices));
    if (!touchDevices) {
        return -1;
    }
    SDL_touchDevices = touchDevices;
    index = SDL_num_touch;
    SDL_touchDevices[index] = (SDL_Touch *)SDL_malloc(sizeof(*SDL_touchDevices[index]));
    if (!SDL_touchDevices[index]) {
        return -1;
    }
    // Added touch to list
    ++SDL_num_touch;
    // we're setting the touch properties
    SDL_touchDevices[index]->id = touchID;
    SDL_touchDevices[index]->type = type;
    SDL_touchDevices[index]->num_fingers = 0;
    SDL_touchDevices[index]->max_fingers = 0;
    SDL_touchDevices[index]->fingers = NULL;
    SDL_touchDevices[index]->name = SDL_strdup(name ? name : "");
    return index;
}
References NULL, SDL_assert, SDL_GetTouchIndex(), SDL_malloc(), SDL_num_touch, SDL_realloc(), SDL_strdup(), and SDL_touchDevices.
Referenced by SDL_MouseTouchEventsChanged(), and SDL_PenTouchEventsChanged().
SDL_DelTouch()
void SDL_DelTouch (SDL_TouchID id) extern
{
    int i, index;
    SDL_Touch *touch;
    if (SDL_num_touch == 0) {
        // We've already cleaned up, we won't find this device
        return;
    }
    index = SDL_GetTouchIndex(id);
    touch = SDL_GetTouch(id);
    if (!touch) {
        return;
    }
    for (i = 0; i < touch->max_fingers; ++i) {
        SDL_free(touch->fingers[i]);
    }
    SDL_free(touch->fingers);
    SDL_free(touch->name);
    SDL_free(touch);
    SDL_num_touch--;
    SDL_touchDevices[index] = SDL_touchDevices[SDL_num_touch];
}
References SDL_Touch::fingers, SDL_Touch::max_fingers, SDL_Touch::name, SDL_free(), SDL_GetTouch(), SDL_GetTouchIndex(), SDL_num_touch, and SDL_touchDevices.
Referenced by SDL_MouseTouchEventsChanged(), SDL_PenTouchEventsChanged(), SDL_QuitMouse(), and SDL_QuitTouch().
SDL_GetTouch()
SDL_Touch * SDL_GetTouch (SDL_TouchID id) extern
{
    int index = SDL_GetTouchIndex(id);
    if (index < 0 || index >= SDL_num_touch) {
        if ((id == SDL_MOUSE_TOUCHID) || (id == SDL_PEN_TOUCHID)) {
            // this is a virtual touch device, but for some reason they aren't added to the system. Just ignore it.
        } else if ( SDL_GetVideoDevice()->ResetTouch) {
            SDL_SetError("Unknown touch id %d, resetting", (int)id);
            SDL_GetVideoDevice()->ResetTouch(SDL_GetVideoDevice());
        } else {
            SDL_SetError("Unknown touch device id %d, cannot reset", (int)id);
        }
        return NULL;
    }
    return SDL_touchDevices[index];
}
References NULL, SDL_VideoDevice::ResetTouch, SDL_GetTouchIndex(), SDL_GetVideoDevice(), SDL_MOUSE_TOUCHID, SDL_num_touch, SDL_PEN_TOUCHID, SDL_SetError(), and SDL_touchDevices.
Referenced by SDL_DelTouch(), SDL_GetTouchDeviceName(), SDL_GetTouchDeviceType(), SDL_GetTouchFingers(), SDL_SendTouch(), and SDL_SendTouchMotion().
SDL_InitTouch()
bool SDL_InitTouch (void) extern
{
    return true;
}
Referenced by SDL_VideoInit().
SDL_QuitTouch()
void SDL_QuitTouch (void) extern
{
    int i;
    for (i = SDL_num_touch; i--;) {
        SDL_DelTouch(SDL_touchDevices[i]->id);
    }
    SDL_assert(SDL_num_touch == 0);
    SDL_free(SDL_touchDevices);
    SDL_touchDevices = NULL;
}
References NULL, SDL_assert, SDL_DelTouch(), SDL_free(), SDL_num_touch, and SDL_touchDevices.
Referenced by SDL_VideoInit(), and SDL_VideoQuit().
SDL_SendTouch()
void SDL_SendTouch (Uint64 timestamp, SDL_TouchID id, SDL_FingerID fingerid, SDL_Window * window, SDL_EventType type, float x, float y, float pressure) extern
{
    SDL_Finger *finger;
    bool down = (type == SDL_EVENT_FINGER_DOWN);
    SDL_Touch *touch = SDL_GetTouch(id);
    if (!touch) {
        return;
    }
    SDL_Mouse *mouse = SDL_GetMouse();
    // SDL_HINT_TOUCH_MOUSE_EVENTS: controlling whether touch events should generate synthetic mouse events
    // SDL_HINT_VITA_TOUCH_MOUSE_DEVICE: controlling which touchpad should generate synthetic mouse events, PSVita-only
    {
        // FIXME: maybe we should only restrict to a few SDL_TouchDeviceType
        if ((id != SDL_MOUSE_TOUCHID) && (id != SDL_PEN_TOUCHID)) {
#ifdef SDL_PLATFORM_VITA
            if (mouse->touch_mouse_events && ((mouse->vita_touch_mouse_device == id) || (mouse->vita_touch_mouse_device == 3))) {
#else
            if (mouse->touch_mouse_events) {
#endif
                if (window) {
                    if (down) {
                        if (finger_touching == false) {
                            float pos_x = (x * (float)window->w);
                            float pos_y = (y * (float)window->h);
                            if (pos_x < 0) {
                                pos_x = 0;
                            }
                            if (pos_x > (float)(window->w - 1)) {
                                pos_x = (float)(window->w - 1);
                            }
                            if (pos_y < 0.0f) {
                                pos_y = 0.0f;
                            }
                            if (pos_y > (float)(window->h - 1)) {
                                pos_y = (float)(window->h - 1);
                            }
                            SDL_SendMouseMotion(timestamp, window, SDL_TOUCH_MOUSEID, false, pos_x, pos_y);
                            SDL_SendMouseButton(timestamp, window, SDL_TOUCH_MOUSEID, SDL_BUTTON_LEFT, true);
                        }
                    } else {
                        if (finger_touching == true && track_touchid == id && track_fingerid == fingerid) {
                            SDL_SendMouseButton(timestamp, window, SDL_TOUCH_MOUSEID, SDL_BUTTON_LEFT, false);
                        }
                    }
                }
                if (down) {
                    if (finger_touching == false) {
                        finger_touching = true;
                        track_touchid = id;
                        track_fingerid = fingerid;
                    }
                } else {
                    if (finger_touching == true && track_touchid == id && track_fingerid == fingerid) {
                        finger_touching = false;
                    }
                }
            }
        }
    }
    // SDL_HINT_MOUSE_TOUCH_EVENTS: if not set, discard synthetic touch events coming from platform layer
    if (!mouse->mouse_touch_events && (id == SDL_MOUSE_TOUCHID)) {
        return;
    } else if (!mouse->pen_touch_events && (id == SDL_PEN_TOUCHID)) {
        return;
    }
    finger = SDL_GetFinger(touch, fingerid);
    if (down) {
        if (finger) {
            /* This finger is already down.
               Assume the finger-up for the previous touch was lost, and send it. */
            SDL_SendTouch(timestamp, id, fingerid, window, SDL_EVENT_FINGER_CANCELED, x, y, pressure);
        }
        if (!SDL_AddFinger(touch, fingerid, x, y, pressure)) {
            return;
        }
        if (SDL_EventEnabled(type)) {
            SDL_Event event;
            event.type = type;
            event.common.timestamp = timestamp;
            event.tfinger.touchID = id;
            event.tfinger.fingerID = fingerid;
            event.tfinger.x = x;
            event.tfinger.y = y;
            event.tfinger.dx = 0;
            event.tfinger.dy = 0;
            event.tfinger.pressure = pressure;
            event.tfinger.windowID = window ? SDL_GetWindowID(window) : 0;
            SDL_PushEvent(&event);
        }
    } else {
        if (!finger) {
            // This finger is already up
            return;
        }
        if (SDL_EventEnabled(type)) {
            SDL_Event event;
            event.type = type;
            event.common.timestamp = timestamp;
            event.tfinger.touchID = id;
            event.tfinger.fingerID = fingerid;
            // I don't trust the coordinates passed on fingerUp
            event.tfinger.x = finger->x;
            event.tfinger.y = finger->y;
            event.tfinger.dx = 0;
            event.tfinger.dy = 0;
            event.tfinger.pressure = pressure;
            event.tfinger.windowID = window ? SDL_GetWindowID(window) : 0;
            SDL_PushEvent(&event);
        }
        SDL_DelFinger(touch, fingerid);
    }
}
References finger_touching, SDL_Mouse::mouse_touch_events, SDL_Mouse::pen_touch_events, SDL_AddFinger(), SDL_BUTTON_LEFT, SDL_DelFinger(), SDL_EVENT_FINGER_CANCELED, SDL_EVENT_FINGER_DOWN, SDL_EventEnabled(), SDL_GetFinger(), SDL_GetMouse(), SDL_GetTouch(), SDL_GetWindowID(), SDL_MOUSE_TOUCHID, SDL_PEN_TOUCHID, SDL_PushEvent(), SDL_SendMouseButton(), SDL_SendMouseMotion(), SDL_SendTouch(), SDL_TOUCH_MOUSEID, SDL_Mouse::touch_mouse_events, track_fingerid, track_touchid, SDL_Finger::x, and SDL_Finger::y.
Referenced by SDL_PrivateSendMouseButton(), SDL_SendPenTouch(), SDL_SendTouch(), and SDL_SendTouchMotion().
SDL_SendTouchMotion()
void SDL_SendTouchMotion (Uint64 timestamp, SDL_TouchID id, SDL_FingerID fingerid, SDL_Window * window, float x, float y, float pressure) extern
{
    SDL_Touch *touch;
    SDL_Finger *finger;
    float xrel, yrel, prel;
    touch = SDL_GetTouch(id);
    if (!touch) {
        return;
    }
    SDL_Mouse *mouse = SDL_GetMouse();
    // SDL_HINT_TOUCH_MOUSE_EVENTS: controlling whether touch events should generate synthetic mouse events
    {
        if ((id != SDL_MOUSE_TOUCHID) && (id != SDL_PEN_TOUCHID)) {
            if (mouse->touch_mouse_events) {
                if (window) {
                    if (finger_touching == true && track_touchid == id && track_fingerid == fingerid) {
                        float pos_x = (x * (float)window->w);
                        float pos_y = (y * (float)window->h);
                        if (pos_x < 0.0f) {
                            pos_x = 0.0f;
                        }
                        if (pos_x > (float)(window->w - 1)) {
                            pos_x = (float)(window->w - 1);
                        }
                        if (pos_y < 0.0f) {
                            pos_y = 0.0f;
                        }
                        if (pos_y > (float)(window->h - 1)) {
                            pos_y = (float)(window->h - 1);
                        }
                        SDL_SendMouseMotion(timestamp, window, SDL_TOUCH_MOUSEID, false, pos_x, pos_y);
                    }
                }
            }
        }
    }
    // SDL_HINT_MOUSE_TOUCH_EVENTS: if not set, discard synthetic touch events coming from platform layer
    if (mouse->mouse_touch_events == 0) {
        if (id == SDL_MOUSE_TOUCHID) {
            return;
        }
    }
    finger = SDL_GetFinger(touch, fingerid);
    if (!finger) {
        SDL_SendTouch(timestamp, id, fingerid, window, SDL_EVENT_FINGER_DOWN, x, y, pressure);
        return;
    }
    xrel = x - finger->x;
    yrel = y - finger->y;
    prel = pressure - finger->pressure;
    // Drop events that don't change state
    if (xrel == 0.0f && yrel == 0.0f && prel == 0.0f) {
#if 0
        printf("Touch event didn't change state - dropped!\n");
#endif
        return;
    }
    // Update internal touch coordinates
    finger->x = x;
    finger->y = y;
    finger->pressure = pressure;
    // Post the event, if desired
    if (SDL_EventEnabled(SDL_EVENT_FINGER_MOTION)) {
        SDL_Event event;
        event.type = SDL_EVENT_FINGER_MOTION;
        event.common.timestamp = timestamp;
        event.tfinger.touchID = id;
        event.tfinger.fingerID = fingerid;
        event.tfinger.x = x;
        event.tfinger.y = y;
        event.tfinger.dx = xrel;
        event.tfinger.dy = yrel;
        event.tfinger.pressure = pressure;
        event.tfinger.windowID = window ? SDL_GetWindowID(window) : 0;
        SDL_PushEvent(&event);
    }
}
References finger_touching, SDL_Mouse::mouse_touch_events, SDL_Finger::pressure, SDL_EVENT_FINGER_DOWN, SDL_EVENT_FINGER_MOTION, SDL_EventEnabled(), SDL_GetFinger(), SDL_GetMouse(), SDL_GetTouch(), SDL_GetWindowID(), SDL_MOUSE_TOUCHID, SDL_PEN_TOUCHID, SDL_PushEvent(), SDL_SendMouseMotion(), SDL_SendTouch(), SDL_TOUCH_MOUSEID, SDL_Mouse::touch_mouse_events, track_fingerid, track_touchid, SDL_Finger::x, and SDL_Finger::y.
Referenced by SDL_PrivateSendMouseMotion(), SDL_SendPenAxis(), and SDL_SendPenMotion().
SDL_TouchDevicesAvailable()
bool SDL_TouchDevicesAvailable (void) extern
{
    return SDL_num_touch > 0;
}
References SDL_num_touch.