SDL3: SDL-main/include/SDL3/SDL_error.h File Reference
SDL_error.h File Reference
#include <SDL3/SDL_stdinc.h>
#include <SDL3/SDL_begin_code.h>
#include <SDL3/SDL_close_code.h>
Macros
Internal error functions
Private error reporting function - used internally.
#define SDL_InvalidParamError(param)
#define SDL_Unsupported()
Functions
SDL_DECLSPEC bool SDLCALL SDL_ClearError (void)
SDL_DECLSPEC const char *SDLCALL SDL_GetError (void)
SDL_DECLSPEC bool SDLCALL SDL_OutOfMemory (void)
SDL_DECLSPEC bool SDLCALL SDL_SetError (SDL_PRINTF_FORMAT_STRING const char *fmt,...) SDL_PRINTF_VARARG_FUNC(1)
SDL_DECLSPEC bool SDLCALL SDL_SetErrorV (SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap) SDL_PRINTF_VARARG_FUNCV(1)
Macro Definition Documentation
SDL_InvalidParamError
#define SDL_InvalidParamError (param)
Value:
SDL_SetError("Parameter '%s' is invalid", (param))
A macro to standardize error reporting on unsupported operations.
This simply calls SDL_SetError() with a standardized error string, for convenience, consistency, and clarity.
A common usage pattern inside SDL is this:
bool MyFunction(const char *str) {
    if (!str) {
        return SDL_InvalidParamError("str");  // returns false.
    }
    DoSomething(str);
    return true;
}
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by RequestAsyncIO(), SDL_AcquireCameraFrame(), SDL_AcquireGPUSwapchainTexture(), SDL_AddHintCallback(), SDL_AddSurfaceAlternateImage(), SDL_AsyncIOFromFile(), SDL_BeginGPUComputePass(), SDL_BeginGPUCopyPass(), SDL_BeginGPURenderPass(), SDL_BindAudioStreams(), SDL_BindGPUComputePipeline(), SDL_BindGPUComputeSamplers(), SDL_BindGPUComputeStorageBuffers(), SDL_BindGPUComputeStorageTextures(), SDL_BindGPUFragmentSamplers(), SDL_BindGPUFragmentStorageBuffers(), SDL_BindGPUFragmentStorageTextures(), SDL_BindGPUGraphicsPipeline(), SDL_BindGPUIndexBuffer(), SDL_BindGPUVertexBuffers(), SDL_BindGPUVertexSamplers(), SDL_BindGPUVertexStorageBuffers(), SDL_BindGPUVertexStorageTextures(), SDL_BlitGPUTexture(), SDL_BlitSurface(), SDL_BlitSurface9Grid(), SDL_BlitSurfaceScaled(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_CancelGPUCommandBuffer(), SDL_ClaimWindowForGPUDevice(), SDL_ClearAudioStream(), SDL_ClearSurface(), SDL_CloseAsyncIO(), SDL_ConvertAudioSamples(), SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurface(), SDL_ConvertSurfaceAndColorspace(), SDL_CopyFile(), SDL_CopyGPUBufferToBuffer(), SDL_CopyGPUTextureToTexture(), SDL_CopyProperties(), SDL_CopyStorageFile(), SDL_CreateColorCursor(), SDL_CreateDirectory(), SDL_CreateGPUBuffer(), SDL_CreateGPUComputePipeline(), SDL_CreateGPUGraphicsPipeline(), SDL_CreateGPURenderer(), SDL_CreateGPURenderState(), SDL_CreateGPUSampler(), SDL_CreateGPUShader(), SDL_CreateGPUTexture(), SDL_CreateGPUTransferBuffer(), SDL_CreateHapticEffect(), SDL_CreatePalette(), SDL_CreateProcess(), SDL_CreateProcessWithProperties(), SDL_CreateRendererWithProperties(), SDL_CreateSoftwareRenderer(), SDL_CreateStorageDirectory(), SDL_CreateSurface(), SDL_CreateSurfaceFrom(), SDL_CreateSurfacePalette(), SDL_CreateTextureFromSurface(), SDL_CreateTimer(), SDL_CreateTrayMenu(), SDL_CreateTraySubmenu(), SDL_CreateWindowAndRenderer(), SDL_DateTimeToTime(), SDL_DispatchGPUCompute(), SDL_DispatchGPUComputeIndirect(), SDL_DownloadFromGPUBuffer(), SDL_DownloadFromGPUTexture(), SDL_DrawGPUIndexedPrimitives(), SDL_DrawGPUIndexedPrimitivesIndirect(), SDL_DrawGPUPrimitives(), SDL_DrawGPUPrimitivesIndirect(), SDL_DuplicateSurface(), SDL_ENCLOSEPOINTS(), SDL_EndGPUComputePass(), SDL_EndGPUCopyPass(), SDL_EndGPURenderPass(), SDL_EnumerateDirectory(), SDL_EnumerateProperties(), SDL_FillSurfaceRect(), SDL_FillSurfaceRects(), SDL_FindInHashTable(), SDL_FlipSurface(), SDL_FlushAudioStream(), SDL_FlushIO(), SDL_GenerateMipmapsForGPUTexture(), SDL_GetAppMetadataProperty(), SDL_GetAsyncIOSize(), SDL_GetAudioDeviceFormat(), SDL_GetAudioDriver(), SDL_GetAudioStreamAvailable(), SDL_GetAudioStreamDataAdjustGain(), SDL_GetAudioStreamDevice(), SDL_GetAudioStreamFormat(), SDL_GetAudioStreamFrequencyRatio(), SDL_GetAudioStreamGain(), SDL_GetAudioStreamProperties(), SDL_GetAudioStreamQueued(), SDL_GetCameraDriver(), SDL_GetCameraFormat(), SDL_GetCameraID(), SDL_GetCameraPermissionState(), SDL_GetCameraProperties(), SDL_GetClipboardData(), SDL_GetClosestFullscreenDisplayMode(), SDL_GetDefaultKeyFromScancode(), SDL_GetDisplayBounds(), SDL_GetDisplayForPoint(), SDL_GetDisplayForRect(), SDL_GetDisplayUsableBounds(), SDL_GetEnvironmentVariables(), SDL_GetGamepadTouchpadFinger(), SDL_GetGPUDriver(), SDL_GetGPUSwapchainTextureFormat(), SDL_GetIOProperties(), SDL_GetIOSize(), SDL_GetIOStatus(), SDL_GetKeyName(), SDL_GetPathInfo(), SDL_GetPrefPath(), SDL_GetProcessInput(), SDL_GetProcessOutput(), SDL_GetProcessProperties(), SDL_GetRenderDriver(), SDL_GetScancodeFromName(), SDL_GetScancodeName(), SDL_GetSpanEnclosingRect(), SDL_GetStoragePathInfo(), SDL_GetSurfaceAlphaMod(), SDL_GetSurfaceBlendMode(), SDL_GetSurfaceClipRect(), SDL_GetSurfaceColorKey(), SDL_GetSurfaceColorMod(), SDL_GetSurfaceImage(), SDL_GetSurfaceImages(), SDL_GetSurfaceProperties(), SDL_GetTLS(), SDL_GetTrayEntries(), SDL_GetTrayEntryChecked(), SDL_GetTrayEntryEnabled(), SDL_GetTrayEntryLabel(), SDL_GetTrayEntryParent(), SDL_GetTrayMenu(), SDL_GetTrayMenuParentEntry(), SDL_GetTrayMenuParentTray(), SDL_GetTraySubmenu(), SDL_GetUserFolder(), SDL_GetVideoDriver(), SDL_GL_DestroyContext(), SDL_GL_GetAttribute(), SDL_GL_GetSwapInterval(), SDL_HasClipboardData(), SDL_HashTableEmpty(), SDL_HASINTERSECTION(), SDL_InsertGPUDebugLabel(), SDL_InsertIntoHashTable(), SDL_InsertTrayEntryAt(), SDL_InternalGlobDirectory(), SDL_INTERSECTRECT(), SDL_INTERSECTRECTANDLINE(), SDL_IOFromConstMem(), SDL_IOFromFile(), SDL_IOFromMem(), SDL_IterateHashTable(), SDL_KillProcess(), SDL_LoadBMP_IO(), SDL_LoadFile_IO(), SDL_LoadFileAsync(), SDL_LoadWAV_IO(), SDL_LockAudioStream(), SDL_LockProperties(), SDL_LockSurface(), SDL_MapGPUTransferBuffer(), SDL_MapRGB(), SDL_MapRGBA(), SDL_MapSurfaceRGBA(), SDL_Metal_GetLayer(), SDL_OpenIO(), SDL_OpenStorage(), SDL_OpenURL(), SDL_PeepEventsInternal(), SDL_PopGPUDebugGroup(), SDL_PremultiplyAlphaPixelsAndColorspace(), SDL_PremultiplySurfaceAlpha(), SDL_PrivateAddGamepadMapping(), SDL_PrivateSetProperty(), SDL_PushGPUComputeUniformData(), SDL_PushGPUDebugGroup(), SDL_PushGPUFragmentUniformData(), SDL_PushGPUVertexUniformData(), SDL_PutAudioStreamData(), SDL_PutAudioStreamDataNoCopy(), SDL_PutAudioStreamPlanarData(), SDL_QueryGPUFence(), SDL_ReadIO(), SDL_ReadProcess(), SDL_ReadStorageFile(), SDL_ReadSurfacePixel(), SDL_ReadSurfacePixelFloat(), SDL_ReleaseWindowFromGPUDevice(), SDL_RemoveFromHashTable(), SDL_RemovePath(), SDL_RemoveStoragePath(), SDL_RemoveTimer(), SDL_RenamePath(), SDL_RenameStoragePath(), SDL_RenderFillRects(), SDL_RenderGeometry(), SDL_RenderGeometryRaw(), SDL_RenderLines(), SDL_RenderPoints(), SDL_RenderRects(), SDL_RenderTextureTiled(), SDL_ResetHint(), SDL_SaveBMP_IO(), SDL_SaveFile_IO(), SDL_ScaleSurface(), SDL_SeekIO(), SDL_SetAppMetadataProperty(), SDL_SetAudioDeviceGain(), SDL_SetAudioStreamFormat(), SDL_SetAudioStreamFrequencyRatio(), SDL_SetAudioStreamGain(), SDL_SetAudioStreamGetCallback(), SDL_SetAudioStreamPutCallback(), SDL_SetEnvironmentVariable(), SDL_SetGamepadMapping(), SDL_SetGPUBlendConstants(), SDL_SetGPUBufferName(), SDL_SetGPURenderStateFragmentUniforms(), SDL_SetGPUScissor(), SDL_SetGPUStencilReference(), SDL_SetGPUSwapchainParameters(), SDL_SetGPUTextureName(), SDL_SetGPUViewport(), SDL_SetHintWithPriority(), SDL_SetLogPriorityPrefix(), SDL_SetMemoryFunctions(), SDL_SetRenderDrawBlendMode(), SDL_SetScancodeName(), SDL_SetSurfaceAlphaMod(), SDL_SetSurfaceBlendMode(), SDL_SetSurfaceColorKey(), SDL_SetSurfaceColorMod(), SDL_SetSurfaceColorspace(), SDL_SetSurfacePalette(), SDL_SetSurfaceRLE(), SDL_SetTextureBlendMode(), SDL_SetTextureScaleMode(), SDL_SetTLS(), SDL_SetWindowIcon(), SDL_SetWindowMaximumSize(), SDL_SetWindowMinimumSize(), SDL_SetWindowProgressState(), SDL_SetWindowSize(), SDL_ShowMessageBox(), SDL_StretchSurface(), SDL_SubmitGPUCommandBuffer(), SDL_SubmitGPUCommandBufferAndAcquireFence(), SDL_UNIONRECT(), SDL_UnlockAudioStream(), SDL_UnmapGPUTransferBuffer(), SDL_UnsetEnvironmentVariable(), SDL_UpdateHapticEffect(), SDL_UpdateNVTexture(), SDL_UpdateTexture(), SDL_UpdateYUVTexture(), SDL_UploadToGPUBuffer(), SDL_UploadToGPUTexture(), SDL_Vulkan_CreateSurface(), SDL_Vulkan_GetPresentationSupport(), SDL_WaitAndAcquireGPUSwapchainTexture(), SDL_WaitForGPUFences(), SDL_WaitForGPUSwapchain(), SDL_WaitProcess(), SDL_WindowSupportsGPUPresentMode(), SDL_WindowSupportsGPUSwapchainComposition(), SDL_WriteIO(), SDL_WriteStorageFile(), SDL_WriteSurfacePixel(), SDL_WriteSurfacePixelFloat(), and SetAudioStreamChannelMap().
SDL_Unsupported
#define SDL_Unsupported ()
Value:
SDL_SetError("That operation is not supported")
A macro to standardize error reporting on unsupported operations.
This simply calls SDL_SetError() with a standardized error string, for convenience, consistency, and clarity.
Thread Safety
It is safe to call this macro from any thread.
Since
This macro is available since SDL 3.2.0.
Referenced by IOS_JoystickRumble(), IOS_JoystickRumbleTriggers(), IOS_JoystickSendEffect(), IOS_JoystickSetLED(), IOS_JoystickSetSensorsEnabled(), JNI_OnLoad(), SDL_AddVulkanRenderSemaphores(), SDL_AudioOpenDevice_Default(), SDL_AudioRecordDevice_Default(), SDL_CalculateYUVSize(), SDL_CaptureMouse(), SDL_CopyStorageFile(), SDL_CreateStorageDirectory(), SDL_CreateTray(), SDL_CreateWindowWithProperties(), SDL_DINPUT_HapticGetEffectStatus(), SDL_DINPUT_HapticMaybeAddDevice(), SDL_DINPUT_HapticMaybeRemoveDevice(), SDL_DINPUT_HapticNewEffect(), SDL_DINPUT_HapticOpen(), SDL_DINPUT_HapticOpenFromJoystick(), SDL_DINPUT_HapticPause(), SDL_DINPUT_HapticResume(), SDL_DINPUT_HapticRunEffect(), SDL_DINPUT_HapticSetAutocenter(), SDL_DINPUT_HapticSetGain(), SDL_DINPUT_HapticStopAll(), SDL_DINPUT_HapticStopEffect(), SDL_DINPUT_HapticUpdateEffect(), SDL_DINPUT_JoystickOpen(), SDL_DINPUT_JoystickRumble(), SDL_DisableScreenSaver(), SDL_EnableScreenSaver(), SDL_EnumerateStorageDirectory(), SDL_FlashWindow(), SDL_FlipSurfaceHorizontal(), SDL_GDKSuspendComplete(), SDL_GetAndroidActivity(), SDL_GetAndroidCachePath(), SDL_GetAndroidExternalStoragePath(), SDL_GetAndroidExternalStorageState(), SDL_GetAndroidInternalStoragePath(), SDL_GetAndroidJNIEnv(), SDL_GetAndroidSDKVersion(), SDL_GetDirect3D9AdapterIndex(), SDL_GetDXGIOutputInfo(), SDL_GetGamepadSensorData(), SDL_GetGDKDefaultUser(), SDL_GetGDKTaskQueue(), SDL_GetJoystickPath(), SDL_GetJoystickPathForID(), SDL_GetStoragePathInfo(), SDL_GetStorageSpaceRemaining(), SDL_GetWindowBordersSize(), SDL_GetWindowICCProfile(), SDL_GetWindowSurfaceVSync(), SDL_GL_GetAttribute(), SDL_GL_SetAttribute(), SDL_IsChromebook(), SDL_IsDeXMode(), SDL_MaximizeWindow(), SDL_Metal_CreateView(), SDL_MinimizeWindow(), SDL_OnApplicationDidChangeStatusBarOrientation(), SDL_Portal_ShowFileDialogWithProperties(), SDL_ReadIO(), SDL_ReadStorageFile(), SDL_RegisterApp(), SDL_RemoveStoragePath(), SDL_RenameStoragePath(), SDL_RenderGeometryRaw(), SDL_RenderReadPixels(), SDL_RequestAndroidPermission(), SDL_RestoreWindow(), SDL_SeekIO(), SDL_SendAndroidBackButton(), SDL_SendAndroidMessage(), SDL_SetGamepadSensorEnabled(), SDL_SetiOSAnimationCallback(), SDL_SetiOSEventPump(), SDL_SetLinuxThreadPriority(), SDL_SetLinuxThreadPriorityAndPolicy(), SDL_SetRenderDrawBlendMode(), SDL_SetRenderVSync(), SDL_SetSurfaceBlendMode(), SDL_SetTextureBlendMode(), SDL_SetWindowHitTest(), SDL_SetWindowIcon(), SDL_SetWindowModal(), SDL_SetWindowOpacity(), SDL_SetWindowParent(), SDL_SetWindowPosition(), SDL_SetWindowSize(), SDL_SetWindowsMessageHook(), SDL_SetWindowSurfaceVSync(), SDL_ShowAndroidToast(), SDL_ShowWindowSystemMenu(), SDL_SYS_GetCurrentDirectory(), SDL_SYS_GetPreferredLocales(), SDL_SYS_GetUserFolder(), SDL_SYS_OpenURL(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UnregisterApp(), SDL_UpdateNVTexture(), SDL_UpdateYUVTexture(), SDL_WarpMouseGlobal(), SDL_WriteIO(), SDL_WriteStorageFile(), SDL_WriteSurfacePixel(), SDL_WriteSurfacePixelFloat(), SDL_XINPUT_JoystickOpen(), SDL_XINPUT_JoystickRumble(), WIN_InitGameInput(), and WIN_UpdateGameInputEnabled().
Function Documentation
SDL_ClearError()
SDL_DECLSPEC bool SDLCALL SDL_ClearError (void) extern
Clear any previous error message for this thread.
Returns
true.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_GetError
SDL_SetError
{
    SDL_error *error = SDL_GetErrBuf(false);
    if (error) {
        error->error = SDL_ErrorCodeNone;
    }
    return true;
}
References SDL_error::error, SDL_ErrorCodeNone, and SDL_GetErrBuf().
Referenced by register_error_str(), register_string_error_to_buffer(), register_winapi_error_to_buffer(), SDL_CreateRendererWithProperties(), SDL_CreateWindowWithProperties(), SDL_FlushIO(), SDL_GetHapticEffectStatus(), SDL_InitSubSystem(), SDL_LoadBMP_IO(), SDL_PushEvent(), SDL_ReadIO(), SDL_ShowMessageBox(), and SDL_WriteIO().
SDL_GetError()
SDL_DECLSPEC const char *SDLCALL SDL_GetError (void) extern
Retrieve a message about the last error that occurred on the current thread.
It is possible for multiple errors to occur before calling SDL_GetError(). Only the last error is returned.
The message is only applicable when an SDL function has signaled an error. You must check the return values of SDL function calls to determine when to appropriately call SDL_GetError(). You should not use the results of SDL_GetError() to decide if an error has occurred! Sometimes SDL will set an error string even when reporting success.
SDL will not clear the error string for successful API calls. You must check return values for failure cases before you can assume the error string applies.
Error strings are set per-thread, so an error set in a different thread will not interfere with the current thread's operation.
The returned value is a thread-local string which will remain valid until the current thread's error string is changed. The caller should make a copy if the value is needed after the next SDL API call.
Returns
a message with information about the specific error that occurred, or an empty string if there hasn't been an error message set since the last call to SDL_ClearError().
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearError
SDL_SetError
{
    const SDL_error *error = SDL_GetErrBuf(false);
    if (!error) {
        return "";
    }
    switch (error->error) {
    case SDL_ErrorCodeGeneric:
        return error->str;
    case SDL_ErrorCodeOutOfMemory:
        return "Out of memory";
    default:
        return "";
    }
}
References SDL_error::error, SDL_ErrorCodeGeneric, SDL_ErrorCodeOutOfMemory, SDL_GetErrBuf(), and SDL_error::str.
Referenced by SDL_CameraThreadIterate(), SDL_LoadBMP_IO(), SDL_ReadIO(), SDL_ShowMessageBox(), and SDL_SYS_ShowFileDialogWithProperties().
SDL_OutOfMemory()
SDL_DECLSPEC bool SDLCALL SDL_OutOfMemory (void) extern
Set an error indicating that memory allocation failed.
This function does not do any memory allocation.
Returns
false.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
{
    SDL_error *error = SDL_GetErrBuf(true);
    if (error) {
        error->error = SDL_ErrorCodeOutOfMemory;
    }
    return false;
}
References SDL_error::error, SDL_ErrorCodeOutOfMemory, and SDL_GetErrBuf().
Referenced by SDL_calloc(), SDL_malloc(), SDL_realloc(), and SDL_SYS_ShowFileDialogWithProperties().
SDL_SetError()
SDL_DECLSPEC bool SDLCALL SDL_SetError (SDL_PRINTF_FORMAT_STRING const char * fmt, ...) extern
CategoryError
Simple error message routines for SDL.
Most apps will interface with these APIs in exactly one function: when almost any SDL function call reports failure, you can get a human-readable string of the problem from SDL_GetError().
These strings are maintained per-thread, and apps are welcome to set their own errors, which is popular when building libraries on top of SDL for other apps to consume. These strings are set by calling SDL_SetError().
A common usage pattern is to have a function that returns true for success and false for failure, and do this when something fails:
if (something_went_wrong) {
   return SDL_SetError("The thing broke in this specific way: %d", errcode);
}
It's also common to just return false in this case if the failing thing is known to call SDL_SetError(), so errors simply propagate through. Set the SDL error message for the current thread.
Calling this function will replace any previous error message that was set.
This function always returns false, since SDL frequently uses false to signify a failing result, leading to this idiom:
if (error_code) {
    return SDL_SetError("This operation has failed: %d", error_code);
}
Parameters
fmt a printf()-style message format string.
... additional parameters matching % tokens in the fmt string, if any.
Returns
false.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearError
SDL_GetError
SDL_SetErrorV
{
    va_list ap;
    bool result;
    va_start(ap, fmt);
    result = SDL_SetErrorV(fmt, ap);
    va_end(ap);
    return result;
}
References SDL_PRINTF_FORMAT_STRING, and SDL_SetErrorV().
Referenced by CHIDDevice::BOpen(), CheckAudioStreamIsFullySetup(), convert_ext_list(), convert_filters(), detect_available_methods(), fd_close(), fd_flush(), fd_read(), fd_seek(), fd_write(), FindPenByInstanceId(), GDK_RegisterChangeNotifications(), GENERIC_ReadStorageFile(), GENERIC_WriteStorageFile(), get_appindicator_id(), GetAudioDevices(), GetAudioStreamDataInternal(), GetDisplayForRect(), IMA_ADPCM_CalculateSampleFrames(), IMA_ADPCM_Decode(), IMA_ADPCM_Init(), init_gtk(), IOS_JoystickOpen(), IOS_JoystickRumble(), IOS_JoystickRumbleTriggers(), IOS_JoystickSetLED(), IOS_JoystickSetSensorsEnabled(), LAW_Decode(), LAW_Init(), Map1toN(), mem_seek(), MS_ADPCM_CalculateSampleFrames(), MS_ADPCM_Decode(), MS_ADPCM_DecodeBlockHeader(), MS_ADPCM_Init(), new_tmp_filename(), ObtainLogicalAudioDevice(), ObtainPhysicalAudioDevice(), ObtainPhysicalAudioDeviceDefaultAllowed(), ObtainPhysicalCamera(), OpenPhysicalAudioDevice(), PCM_ConvertSint24ToSint32(), PCM_Decode(), PCM_Init(), PeekIntoAudioQueueFuture(), PLATFORM_hid_open_path(), PS2AUDIO_OpenDevice(), PutAudioStreamBuffer(), ReadFromAudioQueue(), register_error_str(), register_string_error_to_buffer(), register_winapi_error_to_buffer(), RenderLineBresenham(), RequestAsyncIO(), run_zenity(), SDL_AcquireCameraFrame(), SDL_AddEvent(), SDL_AddGamepadMappingsFromIO(), SDL_AsyncIOFromFile(), SDL_AttachVirtualJoystick(), SDL_BeginGPURenderPass(), SDL_BindAudioStreams(), SDL_BlitSurface(), SDL_BlitSurfaceScaled(), SDL_BlitSurfaceTiled(), SDL_BlitSurfaceTiledWithScale(), SDL_BlitSurfaceUncheckedScaled(), SDL_CalculateBlit(), SDL_CalculateRGBSize(), SDL_CalculateYUVSize(), SDL_CameraInit(), SDL_CaptureMouse(), SDL_ClaimWindowForGPUDevice(), SDL_CloseAsyncIO(), SDL_ContextNotSupported(), SDL_ConvertPixels_STB(), SDL_ConvertPixels_YUV_to_YUV(), SDL_ConvertPixelsAndColorspace(), SDL_ConvertSurfaceAndColorspace(), SDL_CreateColorCursor(), SDL_CreateCondition(), SDL_CreateGPUDevice(), SDL_CreateGPUDeviceWithProperties(), SDL_CreateGPURenderState(), SDL_CreateHapticEffect(), SDL_CreateMutex(), SDL_CreatePopupWindow(), SDL_CreateProcessWithProperties(), SDL_CreateRendererWithProperties(), SDL_CreateRWLock(), SDL_CreateSemaphore(), SDL_CreateSoftwareRenderer(), SDL_CreateSurfacePalette(), SDL_CreateSystemCursor(), SDL_CreateTextureWithProperties(), SDL_CreateThreadWithPropertiesRuntime(), SDL_CreateTray(), SDL_CreateTraySubmenu(), SDL_CreateWindowFramebuffer(), SDL_CreateWindowTexture(), SDL_CreateWindowWithProperties(), SDL_DateTimeIsValid(), SDL_DateTimeToTime(), SDL_DetachVirtualJoystick(), SDL_DllNotSupported(), SDL_EGL_GetCurrentConfig(), SDL_EGL_GetCurrentDisplay(), SDL_EGL_GetProcAddress(), SDL_EGL_GetWindowSurface(), SDL_FillSurfaceRects(), SDL_FindPhysicalAudioDeviceByCallback(), SDL_FindPhysicalCameraByCallback(), SDL_GetAudioDeviceName(), SDL_GetAudioStreamDevice(), SDL_GetAudioStreamFormat(), SDL_GetCameraFormat(), SDL_GetCameras(), SDL_GetClosestFullscreenDisplayMode(), SDL_GetDayOfWeek(), SDL_GetDayOfYear(), SDL_GetDaysInMonth(), SDL_GetDisplayIndex(), SDL_GetDriverAndJoystickIndex(), SDL_GetDriverAndSensorIndex(), SDL_GetEventCategory(), SDL_GetGamepadMappingForGUID(), SDL_GetGDKTaskQueue(), SDL_GetHapticEffectStatus(), SDL_GetHapticIndex(), SDL_GetJoystickAxis(), SDL_GetJoystickAxisInitialState(), SDL_GetJoystickBall(), SDL_GetJoystickButton(), SDL_GetJoystickHat(), SDL_GetKeyboardNameForID(), SDL_GetMasksForPixelFormat(), SDL_GetMouseNameForID(), SDL_GetProcessInput(), SDL_GetProcessOutput(), SDL_GetRenderDriver(), SDL_GetRenderOutputSize(), SDL_GetRenderSafeArea(), SDL_GetSurfaceColorKey(), SDL_GetTouch(), SDL_GetWindowFromID(), SDL_GL_CreateContext(), SDL_GL_GetAttribute(), SDL_GL_GetProcAddress(), SDL_GL_GetSwapInterval(), SDL_GL_LoadLibrary(), SDL_GL_MakeCurrent(), SDL_GL_SetAttribute(), SDL_GL_SetSwapInterval(), SDL_GL_SwapWindow(), SDL_GPU_FetchBlitPipeline(), SDL_GPUSelectBackend(), SDL_GPUSupportsProperties(), SDL_GPUSupportsShaderFormats(), SDL_HASINTERSECTION(), SDL_InitAudio(), SDL_InitHapticRumble(), SDL_InitSubSystem(), SDL_InsertIntoHashTable(), SDL_INTERSECTRECT(), SDL_INTERSECTRECTANDLINE(), SDL_IOFromFile(), SDL_IsTraySupported(), SDL_KillProcess(), SDL_LoadBMP_IO(), SDL_LockTexture(), SDL_MaximizeWindow(), SDL_Metal_GetLayer(), SDL_MixAudio(), SDL_OpenAudioDevice(), SDL_OpenCamera(), SDL_OpenGamepad(), SDL_OpenHapticFromJoystick(), SDL_OpenHapticFromMouse(), SDL_OpenIO(), SDL_OpenStorage(), SDL_OpenTitleStorage(), SDL_OpenUserStorage(), SDL_PauseHaptic(), SDL_PeepEventsInternal(), SDL_PlayHapticRumble(), SDL_PremultiplyAlphaPixelsAndColorspace(), SDL_PrivateAddGamepadMapping(), SDL_PrivateAddMappingForGUID(), SDL_PrivateParseGamepadConfigString(), SDL_ReadProcess(), SDL_RecreateWindow(), SDL_RemoveTimer(), SDL_RemoveTrayEntry(), SDL_RenderGeometryRaw(), SDL_RenderPresent(), SDL_RenderReadPixels(), SDL_RenderTexture(), SDL_RenderTexture9Grid(), SDL_RenderTexture9GridTiled(), SDL_RenderTextureAffine(), SDL_RenderTextureRotated(), SDL_RenderTextureTiled(), SDL_RunApp(), SDL_RunOnMainThread(), SDL_SaveBMP_IO(), SDL_SendJoystickVirtualSensorData(), SDL_SetAudioStreamFrequencyRatio(), SDL_SetClipboardData(), SDL_SetCursor(), SDL_SetHapticAutocenter(), SDL_SetHapticGain(), SDL_SetHintWithPriority(), SDL_SetJoystickVirtualAxis(), SDL_SetJoystickVirtualBall(), SDL_SetJoystickVirtualButton(), SDL_SetJoystickVirtualHat(), SDL_SetJoystickVirtualTouchpad(), SDL_SetKeyboardFocus(), SDL_SetPrimarySelectionText(), SDL_SetRelativeMouseMode(), SDL_SetRelativeMouseTransform(), SDL_SetRenderTarget(), SDL_SetRenderViewport(), SDL_SetSurfacePalette(), SDL_SetTrayEntryLabel(), SDL_SetWindowFullscreenMode(), SDL_SetWindowMaximumSize(), SDL_SetWindowMinimumSize(), SDL_SetWindowModal(), SDL_SetWindowParent(), SDL_SetWindowShape(), SDL_ShowFileDialogWithProperties(), SDL_ShowMessageBox(), SDL_ShowOpenFileDialog(), SDL_ShowOpenFolderDialog(), SDL_ShowSaveFileDialog(), SDL_StopHapticRumble(), SDL_StretchSurface(), SDL_SYS_CreateThread(), SDL_SYS_GetPreferredLocales(), SDL_SYS_GetPreferredLocales_winxp(), SDL_SYS_OpenURL(), SDL_SYS_SetThreadPriority(), SDL_SYS_SetTLSData(), SDL_SYS_ShowFileDialogWithProperties(), SDL_UninitializedVideo(), SDL_UNIONRECT(), SDL_UnlockMutex(), SDL_UpdateHapticEffect(), SDL_UpdateNVTexture(), SDL_UpdateWindowSurfaceRects(), SDL_UpdateWindowTexture(), SDL_UpdateYUVTexture(), SDL_VideoInit(), SDL_vswprintf(), SDL_Vulkan_CreateSurface(), SDL_Vulkan_GetVkGetInstanceProcAddr(), SDL_Vulkan_LoadLibrary(), SetAudioStreamChannelMap(), ShowFileDialog(), ShowFolderDialog(), STEAM_CloseStorage(), STEAM_GetStoragePathInfo(), STEAM_GetStorageSpaceRemaining(), STEAM_ReadStorageFile(), STEAM_User_Create(), STEAM_WriteStorageFile(), ValidateStoragePath(), ValidEffect(), WaveAdjustToFactValue(), WaveCheckFormat(), WaveLoad(), WaveReadFormat(), and windows_ShowFileDialog().
SDL_SetErrorV()
SDL_DECLSPEC bool SDLCALL SDL_SetErrorV (SDL_PRINTF_FORMAT_STRING const char * fmt, va_list ap) extern
Set the SDL error message for the current thread.
Calling this function will replace any previous error message that was set.
Parameters
fmt a printf()-style message format string.
ap a variable argument list.
Returns
false.
Thread Safety
It is safe to call this function from any thread.
Since
This function is available since SDL 3.2.0.
See also
SDL_ClearError
SDL_GetError
SDL_SetError
{
    // Ignore call if invalid format pointer was passed
    if (fmt) {
        int result;
        SDL_error *error = SDL_GetErrBuf(true);
        va_list ap2;
        error->error = SDL_ErrorCodeGeneric;
        va_copy(ap2, ap);
        result = SDL_vsnprintf(error->str, error->len, fmt, ap2);
        va_end(ap2);
        if (result >= 0 && (size_t)result >= error->len && error->realloc_func) {
            size_t len = (size_t)result + 1;
            char *str = (char *)error->realloc_func(error->str, len);
            if (str) {
                error->str = str;
                error->len = len;
                va_copy(ap2, ap);
                (void)SDL_vsnprintf(error->str, error->len, fmt, ap2);
                va_end(ap2);
            }
        }
// Enable this if you want to see all errors printed as they occur.
// Note that there are many recoverable errors that may happen internally and
// can be safely ignored if the public API doesn't return an error code.
#if 0
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "%s", error->str);
#endif
    }
    return false;
}
References SDL_error::error, SDL_error::len, SDL_error::realloc_func, SDL_ErrorCodeGeneric, SDL_GetErrBuf(), SDL_LOG_CATEGORY_ERROR, SDL_LogError(), SDL_PRINTF_FORMAT_STRING, SDL_vsnprintf(), SDL_error::str, and void().
Referenced by SDL_SetError().